### ISSUE TITLE
Sample .runsettings file invalid 

### ISSUE THREAD

**Issue by anondawg21** [MicrosoftDocs/visualstudio-docs#10009]
[Enter feedback here]
These lines are not supported in Visual Studio 2019 so it breaks in a build pipeline with failing to run CodeCoverage.exe

` 
            <EnableStaticNativeInstrumentation>True</EnableStaticNativeInstrumentation>
            
            <EnableDynamicNativeInstrumentation>True</EnableDynamicNativeInstrumentation>
            
            <EnableStaticNativeInstrumentationRestore>True</EnableStaticNativeInstrumentationRestore>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 43dc6fcf-df9f-9d2a-5c6e-8da0f6925afc
* Version Independent ID: d0bf2cae-9b59-d537-7acb-7af5f560d8c1
* Content: [Customizing Code Coverage Analysis - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019)
* Content Source: [docs/test/customizing-code-coverage-analysis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/customizing-code-coverage-analysis.md)
* Service: **visual-studio-windows**
* Sub-service: **test-tools**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@jakubch1 Jakub, Are EnableStaticNativeInstrumentation and EnableDynamicNativeInstrumentation supported only in VS 2022? I can update the article with verision monikers if that is the case.

**Comment by jakubch1** [comment]
Yes. Those options are supported only in VS 2022.

**Comment by Mikejo5000** [comment]
Updating sample with version monikers. Fix should be live by noon today, PST.
