### ISSUE TITLE
The first bullet point under "Download and Install the remote tools" contradicts itself

### ISSUE THREAD

**Issue by RevitIRL** [MicrosoftDocs/visualstudio-docs#10002]
[Enter feedback here]

The first bullet point under "Download and Install the remote tools" contradicts itself (copied below). It says "The latest remote tools version is compatible with earlier Visual Studio versions" which would mean that the remote tools for 2022 would work for Visual Studio 2019, but the last sentence explicitly states otherwise, and the first sentence implies the opposite as well. 

Maybe the opposite was meant: "The latest Visual Studio version is compatible with earlier remote tools versions."? In that case, you could also modify the last sentence: "In this scenario, do not download the remote tools for Visual Studio 2022, but using the remote tools for Visual Studio 2017 is possible.)"

If not, it should just explicitly state that. Remove the 2nd sentence and change the last to: "In this scenario, do not download the remote tools for Visual Studio 2022, 2017, etc.)"

Current text for reference:

> Download the most recent remote tools for your version of Visual Studio. The latest remote tools version is compatible with earlier Visual Studio versions, but earlier remote tools versions aren't compatible with later Visual Studio versions. (For example, if you are using Visual Studio 2019, download the latest update of the remote tools for Visual Studio 2019. In this scenario, do not download the remote tools for Visual Studio 2022.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/remote-debugging.md)
* Service: **visual-studio-windows**
* Sub-service: **debug-diagnostics**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@RevitIRL Thanks for the feedback! The article should be updated by EOD today, PST.
