### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by markdcarringer** [MicrosoftDocs/visualstudio-docs#1000]
"Looki" should be "Look". The error is found in the second paragraph of the section "Continue the analysis". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* Content: [Create and run unit tests for managed code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@markdcarringer Thanks for letting us know; I just fixed it. You should see the change later today. And congrats on issue no. 1000!
