### ISSUE TITLE
VS download accelerate

### ISSUE THREAD

**Issue by KingAndroid** [MicrosoftDocs/visualstudio-docs#1001]
Whenever vs has been update, i need to take time to update / download them from server.
It consumes not so short time, and i want to save time.
1. could you provide any multi threading download method?
2. to save time, can you provide one archive formatted?
3. would update download only updated? - due every updates will download more than 3 gbs.
Thank you for your great support.

**Comment by gewarren** [comment]
@TerryGLee Can you take this one?

**Comment by TerryGLee** [comment]
@KingAndroid Thanks for your feedback; we appreciated it. Please do know, however, that this venue is for documentation feedback, and it looks like you want to provide product feedback by way of feature requests. To be sure that it gets routed to the right place please consider submitting these sorts of feature requests to our [UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide) page. And for more information about all our feedback options, see our [Talk to Us](https://docs.microsoft.com/visualstudio/ide/talk-to-us) page.

Thanks again,
~ Terry
