### ISSUE TITLE
How do I change the default encoding for line breaks?

### ISSUE THREAD

**Issue by spalt-alfred** [MicrosoftDocs/visualstudio-docs#10017]
This article is a nice description what to do if you want so save files with different line break encodings.
However, it does not tell me, how to change my personal default value for line encodings.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2642c7f-04bb-56eb-0f26-d867703cf2f4
* Version Independent ID: 9c3f65b2-143b-8053-35ad-866152ea905e
* Content: [Encoding and line break characters - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks?view=vs-2022)
* Content Source: [docs/ide/encodings-and-line-breaks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/encodings-and-line-breaks.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@spalt-alfred -- Alfred, thank you for your question.  In the lower right corner of the primary Visual Studio window, select your preferred line ending:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/27738025/933ef0b5-1f79-4d50-8318-ef06c067322c)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by spalt-alfred** [comment]
Thank you, @WilliamAntonRohm for your prompt answer!

I already know that you can change your desired line ending on a per project base.
However, if you create a new project, VisualStudio's default setting applies again.
Example:
I'm on a Windows machine. When I create a new Console Project, I can change my desired line encoding for *this* project by clicking on "LF" in the lower right corner. That works.
However, if I create a new Project, the line endings are again "CRLF", which is the obvious default on a Windows machine.

Obviously, my question was not precise enough.
What I wanted to ask was: How can I *permanently* change my desired line encoding. For this and all future VisualStudio projects.

As I already googled for some time and did not find an answer to this question, I suspect that there is no "global" setting in VisualStudio. (As there is one in VS Code. There you can define it in the JSON settings file.)

**Comment by WilliamAntonRohm** [comment]
@spalt-alfred -- Alfred, thank you for your follow-up.  My own researches agree with your conclusion.  If you feel this is a product issue, please add it here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

**Comment by spalt-alfred** [comment]
@WilliamAntonRohm -- William, let me put it this way: a feature like the one we discussed here would be "nice-to-have" for **me**. Since no one else in the world is missing it - I can perfectly live without it. 
Thanks for your help! :-)
