### ISSUE TITLE
Link broken for Visual Studio 2010 Tool

### ISSUE THREAD

**Issue by ozturkergin** [MicrosoftDocs/visualstudio-docs#10011]
[Enter feedback here]
Link broken for Visual Studio 2010 Tool

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 452374f5-e8d0-37e6-558d-c44c3926fec4
* Version Independent ID: 8f3cb5a2-ed9e-3c10-a507-6a9e3bc0588e
* Content: [Install the Visual Studio Tools for Office Runtime Redistributable](https://learn.microsoft.com/en-us/visualstudio/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable?view=vs-2022)
* Content Source: [docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md)
* Service: **visual-studio-windows**
* Sub-service: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by j-martens** [comment]
@John-Hart the links show that IE was retired.

<img width="842" alt="image" src="https://github.com/MicrosoftDocs/visualstudio-docs/assets/8481597/c7343d49-28bb-4e98-a446-a04cd619f56a">

**Comment by ghogen** [comment]
@ozturkergin 
I just checked all the links on the page, and they are all working at the moment. In such cases, we normally suspect a transient network issue. Thanks for reporting this, but we will close this now that the links are all verified to work at this time.
