### ISSUE TITLE
Not able to see any projects from the server

### ISSUE THREAD

**Issue by eric99r** [MicrosoftDocs/visualstudio-docs#1002]
I'm able to connect to my VSTS server and enter the credentials correctly to see the next screen. But the right hand side of the dialog box where the projects are shown is empty. I do have projects that i want to access but i don't know what's going on.
![image](https://user-images.githubusercontent.com/35573343/40362224-83edfeb6-5d91-11e8-8bf9-20d76eea0c8a.png)

**Comment by gewarren** [comment]
@erickson-doug who on the VSTS team should I ask about this? Or, which issues page should this be logged at instead? (@eric99r this issues page is actually for the VS docs, so not really for VSTS, but we can help send you to the right place.)

**Comment by nschonni** [comment]
Might be the same as this https://github.com/MicrosoftDocs/visualstudio-docs/issues/1017#issuecomment-391489044

**Comment by gewarren** [comment]
@eric99r Are you using VS for Mac? If so, this is the same issue that @nschonni referenced above, and it's a known issue that's being tracked on [Developer Community](https://developercommunity.visualstudio.com/content/problem/248618/cant-connect-to-tfs-version-control-in-visual-stud.html). Please reopen this issue if this is not the case.
