### ISSUE TITLE
Support for custom analysis dictionary is not yet implemented?

### ISSUE THREAD

**Issue by FrankHeimes** [MicrosoftDocs/visualstudio-docs#10026]
The section "To apply a custom dictionary to a project" does not apply to current versions of Visual Studio (i.e. VS 2022, 17.9.0 Preview 5.0)

* The "Add Existing Item" dialog does not offer an option "Add As Link".
* There is no "Build Action" list and no entry "CodeAnalysisDictionary" in the properties page for "CustomDictionary.xml", just the General properties for an XML content file.

It seems that the page describes what is _intended_ to be implemented but not actually implemented yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0c5937-e895-d2e3-0e14-655cf4e52d6a
* Version Independent ID: abe9dea4-c830-c476-1e9d-fd2386d014c3
* Content: [Customize the Code Analysis Dictionary - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/code-quality/how-to-customize-the-code-analysis-dictionary?view=vs-2022)
* Content Source: [docs/code-quality/how-to-customize-the-code-analysis-dictionary.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/code-quality/how-to-customize-the-code-analysis-dictionary.md)
* Service: **visual-studio-windows**
* Sub-service: **code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I tested these steps for a .NET Framework project (legacy analysis is not supported on .NET), and everything worked. I did have to set file types to **All Files** in the **Add Existing Item** dialog box. I'm updating the steps accordingly. Update should be live by noon today PST.
