### ISSUE TITLE
There's no Platform toolset on general tab...

### ISSUE THREAD

**Issue by rafael-f** [MicrosoftDocs/visualstudio-docs#10024]
Documentation says:

In Visual Studio 2022, the UI has changed and there is no longer a Retarget solution menu option. Instead, in the project properties, under General, change the Platform toolset to Visual Studio 2022.

But there's no Platform toolset on general tab...

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/14276684/24146ff4-b2ae-4386-a4db-b10801285525)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d901b841-b868-50e8-3036-c2eb1d129c86
* Version Independent ID: d901b841-b868-50e8-3036-c2eb1d129c86
* Content: [MSBuild error MSB8020 - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8020?view=vs-2022&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8020)%26rd%3Dtrue)
* Content Source: [docs/msbuild/errors/msb8020.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb8020.md)
* Service: **visual-studio-windows**
* Sub-service: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@rafael-f 
Can you give more details on the project where you're not seeing the Platform toolset property? Clearly, some C++ projects created in Visual Studio 2022 have the Platform toolset property in General. The C++ Console Application has this, for example.

**Comment by ghogen** [comment]
Apparently, there should be a Retarget solution option in the menu as suggested in the error message. Do you see that?

**Comment by ghogen** [comment]
This issue can be closed now, as I updated the page so it doesn't misdirect users to this property setting.
