### ISSUE TITLE
Unsatisfactory experience

### ISSUE THREAD

**Issue by aaron-oxford** [MicrosoftDocs/visualstudio-docs#10021]
https://visualstudio.microsoft.com/vs/github/

Click on the first link on the page.

Below is where I end up.

Thanks for the help! /s

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d2102750-53e7-cb23-b39a-5a9e133a9e99
* Version Independent ID: d2102750-53e7-cb23-b39a-5a9e133a9e99
* Content: [Git Changes window with no active repo - Visual Studio (Windows)](https://learn.microsoft.com/en-au/visualstudio/version-control/git-changes-with-no-active-repo?view=vs-2022&wt.mc_id=visualstudio_vscomwebsite_webpage_cnl)
* Content Source: [docs/version-control/git-changes-with-no-active-repo.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-changes-with-no-active-repo.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@aaron-oxford -- Aaron, thank you for your feedback.  Which link are you following from https://visualstudio.microsoft.com/vs/github?

**Comment by aaron-oxford** [comment]
@WilliamAntonRohm the one that says "[Learn how to use GitHub with Visual Studio](https://aka.ms/vsgitdocs-landing/?wt.mc_id=visualstudio_vscomwebsite_webpage_cnl)"
