### ISSUE TITLE
Out of date: Distribute code snippets as an Visual Studio extension

### ISSUE THREAD

**Issue by w-woodbury-splicedinc** [MicrosoftDocs/visualstudio-docs#10031]
This page describes a process that applies to VS version 16, not newer versions. For example the reg key described doesn't exist at all, and snippets added manually (vis the Snippet Manager) don't appear to be in the registry at all. I tried to create an extension using the described method, and it doesn't work for VS 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c60cdeb-c3af-ebb1-80e7-1ec682896734
* Version Independent ID: 04010067-02f9-548e-467b-fa4efa391860
* Content: [Distribute code snippets as an extension - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-distribute-code-snippets?view=vs-2022)
* Content Source: [docs/ide/how-to-distribute-code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-distribute-code-snippets.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@w-woodbury-splicedinc It's possible you need to set this registry key in the private registry for VS, as described here: https://github.com/microsoft/VSProjectSystem/blob/master/doc/overview/examine_registry.md.

**Comment by Mikejo5000** [comment]
I created a work item to re-test this article and check the registry key, and whether the private registry is required. I will be tracking the issue internally at this point, so closing this.

**Comment by Mikejo5000** [comment]
@w-woodbury-splicedinc I'm updating the article with updated information on the registry. As far as I can tell, that information is only useful to confirm that steps are working correctly. I retested all the steps in the article for the VB example, and everything worked fine. A few steps were slightly trickier: (1) making sure .xml was not included in the file extension for the .snippet file, and (2) making sure that the file properties were set correctly for the .snippet file and the .pkgdef file.
