### ISSUE TITLE
The server tracing option is incorrect

### ISSUE THREAD

**Issue by DanTup** [MicrosoftDocs/visualstudio-docs#1004]
The docs say you should set "foo.server.trace" but I had to set "foo.trace.server" to make it work!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff91657a-173a-0013-62e4-e7c8531b8240
* Version Independent ID: 27988cad-5114-41e3-c48a-357431af0fe1
* Content: [Adding a Language Server Protocol extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension#creating-a-simple-language-client)
* Content Source: [docs/extensibility/adding-an-lsp-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
This was fixed last July - https://github.com/MicrosoftDocs/visualstudio-docs/commit/b6c26be1a6e27cf79bbf4242117536b34ca42876#diff-235cbfb59d41b2181f444b5da10bd2bd.
