### ISSUE TITLE
Icon ldentification?

### ISSUE THREAD

**Issue by crhammon** [MicrosoftDocs/visualstudio-docs#10053]
Hi,

I cannot seems to find a list of all icons used in Visual Studio and what they mean, especially for the solution explorer. Does this exist, if not then why not?

Thanks,

Charlie

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1f9dc4a-d8a6-6642-635c-6c6204467b3e
* Version Independent ID: 05f0ffc9-109a-43bc-d9f3-55d14242db33
* Content: [Learn about Solution Explorer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/use-solution-explorer?view=vs-2022)
* Content Source: [docs/ide/use-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/use-solution-explorer.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by ghogen** [comment]
@crhammon 
If you hover over an icon that's a button, you see a tooltip which tells you what the button does. 

The only icon reference I can think of is this one:
https://learn.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/visual-language-dictionary-for-visual-studio?view=vs-2022

**Comment by crhammon** [comment]
Thanks for that. It really seems like that should solve my problem, but it doesn't! Here is a screenshot. I am now inferring that the box with the ++ means a project with C++ code and that just a ++ means cpp code, but I can't find that anywhere in the dictionary your provided. I am just a beginner trying to sort out what everything means in Visual Studio.

![Screenshot 2024-02-16 152504](https://github.com/MicrosoftDocs/visualstudio-docs/assets/26095391/e5e9f617-b57e-4cee-9340-a35ea4e3782d)
