### ISSUE TITLE
Walkthrough in doc page "Create a C++ extension for Python" does not work

### ISSUE THREAD

**Issue by goofy2k** [MicrosoftDocs/visualstudio-docs#10054]
I had some success with using pybind11 for calling Python scripts from the C++ side. But this does not bring solutions for my project nearer. So I returned to creating C++ extensions for Python.

I try to follow the walkthrough in the relevant doc page for Visual Studio 2022, but still without success. I am prepared to note down my experiences here and hope that I get it running in the end and that it contributes to improving the docs. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Service: **visual-studio-windows**
* Sub-service: **python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
@goofy2k Thanks for filing the issue. Are there specific sections of the tutorial that you are running into issues with so that we can better update the documentation and provide help?

**Comment by goofy2k** [comment]
Hi, my issues start when I try to build the fastcode and fastcode2 projects I will prepare a detailed description, but this will take me a while. Appreciate that you are very responsive!

**Comment by goofy2k** [comment]
Here is the first part of the walkthrough. I only give details when they are different than in the docs. Maybe this already contains some clues why things are not working.
-------------------------------------------
To be honest:  I have read the Prerequisites section and I am not sure that my existing Python installation contains the recommended debugging symbols. Nevertheless I will describe my experiences.

### Create the Python application

**After step 2.** in creating the Python application I get a warning:

Warning		The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	Python_app	C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	1241

But the pure Python script from the docs runs OK.

### Create the core C++ projects

My solution header reads Python_app, which is the same as the name of the script file.

**Step 2.** I had to remove the already existing folders superfastcode and superfastcode2. Did this outside the VS IDE.
**Step 4.** After this step I have the superfastcode.cpp file. It is an empty file in this stage.
**Step 7.** Configuration Properties > General > Target Name: $(ProjectName)  (kept this, I don't have python_d.exe or the _d.lib

        C/C++ Preprocessor > Preprocessor Definitions:  was _DEBUG  _CONSOLE   set to NDEBUG, so removed _CONSOLE
        C/C++ Preprocessor > Code Generation: set to Multi-threaded DLL (/MD)
 
**Step 9.** debug config builds OK.  release config gives:
Error	LNK2001	unresolved external symbol main	superfastcode	C:\Users\Fred\source\repos\superfastcode\MSVCRT.lib(exe_main.obj)	1	
Error	LNK1120	1 unresolved externals	superfastcode	C:\Users\Fred\source\repos\Python_app\x64\Release\superfastcode.exe	1

Debug folder contains superfastcode.pyd.recipe (not superfastcode.pyd)
Release folder does not contain such a file.

NOTE: in this stage the .cpp files are still empty files.
Q: is there a way to make the settings for superfastcode defaults such that I can re-use them for superfastcode2?

**Comment by goofy2k** [comment]
**For conversion to extensions** for Python I prefer the pybind11 option.
Step 5. The superfastcode builds OK in the Debug config 
	
### Make the DLL available to Python

**Step 2.** Only selected superfastcode for now

Did not follow the alternative method (yet)

### Call the DLL from Python

**Step 1.** Only copied the lines for superfastcode
**Step 2.** gives: ImportError: dynamic module does not define module export function (PInit_superfastcode)

**Comment by goofy2k** [comment]
(excuse me for the header format in some of the lines. Don't know how to remove that. In my editor window I don't see markup symbols. )

I tried to repair this last error. Noticed that the code in step 4 under Use PyBind11 contains:

PYBIND11_MODULE(superfastcode2, m) {

I assume that the 2 must not be there for the superfastcode project.

The error does not disappear after rebuilding the superfastcode project.

**Comment by goofy2k** [comment]
The error IS resolved after I also removed the 2 in the code under step 4 under Use PyBind11. (the line with PYBIND11_MODULE)

I think it is wise to describe in the doc that for the 2 projects the C++ AND the Python codes are slightly different.
What remains:  the code only runs for the debug config and not for release.

Remark: for COUNT = 500000 the Python calculation takes 0.689 seconds, against 3.00 seconds for the C++ / pybind11 code.

**Comment by goofy2k** [comment]
Got the release version of superfastcode running ! The setting Configuration type was still .exe

**Comment by goofy2k** [comment]
Now I have project superfastcode running in the 2 configs, debug and release.
Is it posiible to copy/clone this project to have a quickstart for project superfastcode2?

**Comment by goofy2k** [comment]
After some time a newbie, like me, starts to learn the workflow....

The steps under Create the core C++ projects could be clearer. 
Step 6a. let's the reader select Active (Debug)
Step 9. let's the reader test both configurations

If the reader follows the steps literally, the test of the release config will fail as it was never configured.
So in fact steps 1 to 11 should be done 4 times: for the two projects and, per project, for the two configs.
In the end this is logical to me, but when one starts from scratch it is not clear.

Going through these repetitive configuration tasks helps for learning, but in the end a few words could be spent to re-using already configured matters. E.g. can you copy a project (fastcode) and use it as a template for fastcode2? Or: can you promote settings in one project or one of the configs to default settings that can be re-used.

**Comment by goofy2k** [comment]
In step 7. the reader has to change _DEBUG into NDEBUG.
In my setup there was also an entry _CONSOLE.
I had to remove this to get rid of the Error LNK2001 when building.

**Comment by goofy2k** [comment]
In the section Convert the C++ projects to extensions for Python it is not clear _a priori_ that it will be project superfastcode that will be converted using CPython extensions   and that superfastcode2 will be done with pybind11.  Am I correct that this is the procedure?

If so, step 1 unde Use CPython extensions should read:

At the top of the _module.cpp_ file **of the fastcode projec**t, include Python.h  etc. etc.

Now I have converted both projects with my preferred method (pybind11) and did I run into some of the errors above.

**Comment by goofy2k** [comment]
In the end I managed to use the CPython and PyBind11 routes in both the release and debug configurations!

**Comment by anandmeg** [comment]
Thanks for the feedback, @goofy2k!
We've made updates to the docs.

**Comment by goofy2k** [comment]
Thats great! I will have a look

Fred
(Goofy2k is just an alias....)

Op vr 15 mrt. 2024 20:23 schreef Megha Anand ***@***.***>:
