### ISSUE TITLE
Conda configurability in product tab

### ISSUE THREAD

**Issue by farisachugthai** [MicrosoftDocs/visualstudio-docs#1005]
Can you elaborate on how much we're allowed to modify Conda's behavior while installing new packages? I was downloading a few packages, and one of my modules was incompatible with a previously downloaded one. However with no prompt, conda simply uninstalled the first package and continued on.

In the bottom left of the screen, I noticed the command
install -p \path\to\env -y [package] 

it seems that these are hard coded because the basic command

conda update -n base conda fails due to -p not receiving it's expected argument

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a61810c3-c215-1b07-3bc8-17af0b6676ad
* Version Independent ID: dd1701c0-9117-29ba-bbd2-413949e305da
* Content: [Python environments window reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/python-environments-window-tab-reference#packages-tab)
* Content Source: [docs/python/python-environments-window-tab-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/python-environments-window-tab-reference.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks @farisachugthai. I'll check with the engineering team whether there's any latitude here.

**Comment by farisachugthai** [comment]
No problem! If you don't mind me continuing to pester you, then I'd also note that if you download anaconda and set it up as a global environment, then create a new environment using a version of conda that isn't up to date, then the 2nd conda [or CONDASHLVL=2 if thats any more clear hahaha] can't update itself. you have to enter the global environment and then conda update conda for any changes to be observed.

however at that point, all conda versions change so.....i'm suspecting a lot of symlinked paths and hard coded paths. obviously this is a new product and kinks need to be worked out but intertwined dependencies was the very problem Conda was made to solve. 

All the best Kraig. I really appreciate your quick and courteous responses.

**Comment by kraigb** [comment]
To answer your first question: you can specify arguments along with a package name in the search box on the Package (Conda) (and Packages (PyPI)) tabs in the Python Environments window. Without arguments, the search results show various matches to the search term, and the first results is "conda install (name)". If you include arguments, then the one result is "conda install (name) (args)". I've just made those edits on the page.

For your second question, you've identified a likely product bug, in which case you should file an issue on https://github.com/Microsoft/ptvs/issues where the engineering team can discuss details with you.

Also, if you have scenarios where the arguments for conda install aren't sufficient, then also file an issue on the ptvs repo, as that's no longer a docs issue.

**Comment by kraigb** [comment]
PS, see the referenced commit above for the doc changes, which will take another day or two to migrate to the live site.
