### ISSUE TITLE
Version error with Note

### ISSUE THREAD

**Issue by cgsgood** [MicrosoftDocs/visualstudio-docs#10061]
[Enter feedback here]
"To get the path to the profiling tools, see [Specify the path to command line tools](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2017/profiling/specifying-the-path-to-profiling-tools-command-line-tools)."

The above note is vs 2017, not vs 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5cbcf6d-7a04-3018-11aa-cffd16106765
* Version Independent ID: f5cbcf6d-7a04-3018-11aa-cffd16106765
* Content: [Profiler command line - Instrument native component, get timing data - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/profiling/instrument-native-component-and-collect-timing-data?view=vs-2022)
* Content Source: [docs/profiling/instrument-native-component-and-collect-timing-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/profiling/instrument-native-component-and-collect-timing-data.md)
* Service: **visual-studio-windows**
* Sub-service: **debug-diagnostics**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updating article

**Comment by Mikejo5000** [comment]
Update should be live by EOD today 3/18/24 PST.
