### ISSUE TITLE
Misleading and missing instructions

### ISSUE THREAD

**Issue by MrWrightAZ** [MicrosoftDocs/visualstudio-docs#10060]
MS VisualStudio 2022 - v17.9.0
MS .NET Framework v4.8.09032

Instructions call for creating a dataset to be added under section, "Create the dataset that receives the XML data". There is no dataset option in the Toolbox.

Further, in order to make example work correctly, the addition of the following code is required:

    Dim AuthorsDataSet As New DataSet()

This instruction is missing.

In addition, the code offered for each of the buttons will work with the presented default option when double-clicking on each button by only inserting:

    Dim filePath As String = "Complete path where you saved the XML file"

    AuthorsDataSet.ReadXml(filePath)

    DataGridView1.DataSource = AuthorsDataSet
    DataGridView1.DataMember = "authors"

and

    Dim swXML As New System.IO.StringWriter()
    AuthorsDataSet.WriteXmlSchema(swXML)
    TextBox1.Text = swXML.ToString

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8ef3c94-32d7-fbe9-a271-3ac7efeb1e17
* Version Independent ID: 078a61ff-8bd7-1f6c-3637-76940c4cf904
* Content: [Read XML data into dataset in .NET Framework apps - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/data-tools/read-xml-data-into-a-dataset?view=vs-2022&tabs=vb)
* Content Source: [docs/data-tools/read-xml-data-into-a-dataset.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/read-xml-data-into-a-dataset.md)
* Service: **visual-studio-windows**
* Sub-service: **data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@MrWrightAZ 
I tried the steps and found that it worked correctly for .NET 4.8, with VB. I also tried .NET 4.7.2 with C#.  I was able to see the DataSet in the Toolbox, and when added, the hidden file Form1.Designer.vb automatically gets the line that creates the DataSet.

```
Me.AuthorsDataSet = New System.Data.DataSet()
```

So, consequently, I did not have to add that.

Would you double-check to see if you installed the "Data storage and processing" workload?
