### ISSUE TITLE
missing EventHandler statement

### ISSUE THREAD

**Issue by rvwilliams88** [MicrosoftDocs/visualstudio-docs#10075]
The timer won't work unless and EventHandler is defined.  It took me a while to work this out.  Once I inserted 

`timer1.Tick += new EventHandler(timer1_Tick);`

the code worked as intended.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af83dce0-a830-c876-e355-d9e3ca095b30
* Version Independent ID: af83dce0-a830-c876-e355-d9e3ca095b30
* Content: [Tutorial: Add a timer to a Windows Forms app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer?view=vs-2022&tabs=csharp)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by ghogen** [comment]
@rvwilliams88 
Thanks for the feedback. I tested the scenario you mentioned, and found that the line of code that adds the event handler is automatically added to the *.Designer.cs file when you double-click on "timer1" (at the bottom left of the Form designer window). I guess it would be helpful to add a comment in the article saying that code is added to that file. If instead you opened the code file and added the code without double-clicking on the timer1 control, then you wouldn't have had that important line of code added automatically.
