### ISSUE TITLE
New multiple startup projects functionality

### ISSUE THREAD

**Issue by tingram-hp** [MicrosoftDocs/visualstudio-docs#10078]
Visual Studio 2022 17.9 added new functionality for multiple startup projects that is not present in the documentation.

Here is the relevant release note:
https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#multi-project-configuration

There is also a new "Share profile" checkbox that even the release notes do not describe.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c932420b-6870-bfd6-d664-2db92053bfaf
* Version Independent ID: fde787e7-1307-5b2c-206e-e67657e80090
* Content: [Set multiple startup projects - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-set-multiple-startup-projects?view=vs-2022)
* Content Source: [docs/ide/how-to-set-multiple-startup-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-set-multiple-startup-projects.md)
* Service: **visual-studio-windows**
* Sub-service: **compile-build**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@tingram-hp 
Thanks for your note. We're aware there isn't documentation at this time. The work for this is on hold for the moment; at this time, it is intentionally not documented.

We'll close this issue at this time, but there may be updates in the coming months about this feature.
