### ISSUE TITLE
Default launch configuration for ASP.NET Core + React template with Docker is incorrect. 

### ISSUE THREAD

**Issue by janheindejong** [MicrosoftDocs/visualstudio-docs#10074]
When using the template for an ASP.NET core + React project with Docker enabled, the default launch configuration runs the backend project in a docker container; however, the front-end searches for the HTTPS launch configuration port (i.e. 7138). Changing the launch configuration to "Multiple Projects" and specifying the HTTPS configuration for the backend explicitly fixed the problem. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Service: **visual-studio-windows**
* Sub-service: **javascript-typescript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@janheindejong Thanks for the feedback! In the non-Docker scenario, the solution sets up a "Multiple Projects" configuration by default, and uses the https profile by default. It sounds like that is not the case when you choose the Docker configuration? I can add a note about that.

**Comment by Mikejo5000** [comment]
I created a work item to re-test this article and check the launch configuration for Docker scenario. I will be tracking the issue internally at this point, so closing this.
