### ISSUE TITLE
/clear command is not available in GitHub Copilot Chat extension

### ISSUE THREAD

**Issue by SIkebe** [MicrosoftDocs/visualstudio-docs#10081]
This page lists `/clear` command in GitHub Copilot Chat. However GitHub Copilot Chat extension v0.2.242.43722 doesn't have the command.
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/17608272/ae8a4f98-687d-4be1-9a47-16d17e09c70d)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b7f89f48-5156-1f40-c7c1-4b5853167194
* Version Independent ID: b7f89f48-5156-1f40-c7c1-4b5853167194
* Content: [Tips & Tricks for GitHub Copilot Chat in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022)
* Content Source: [docs/ide/copilot-chat-context.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/copilot-chat-context.md)
* Service: **visual-studio-windows**
* Sub-service: **ai-tools**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by SIkebe** [comment]
Visual Studio Code uses `/newChat` to start a new session.
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/17608272/c6a8894c-700e-4f72-a53d-2181a4432874)

**Comment by anandmeg** [comment]
@SIkebe, thanks for your feedback! We've updated the doc, the changes should be live later today.
You can use the [UI to organize (add & delete)](https://learn.microsoft.com/en-us/visualstudio/ide/copilot-chat-context?view=vs-2022#threads) chat threads.

**Comment by SIkebe** [comment]
FYI, GitHub Copilot Chat extension for Visual Studio Code re-enabled `/clear` command and stopped using `/newChat` in the recent version (v0.13.2024022301).
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/17608272/2af26562-6321-461a-bb16-11fd7e907b87)
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/17608272/4700588d-6f3e-4f99-aebc-1976e416253a)
