### ISSUE TITLE
Webdings not shwing correctly

### ISSUE THREAD

**Issue by rvwilliams88** [MicrosoftDocs/visualstudio-docs#10087]
The instructions for setting the properties of the label need to include an instruction to set UseCompatibleTextRendering to True.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 110f0922-f6cd-ffb0-7a77-6ef9808ca4fd
* Version Independent ID: 110f0922-f6cd-ffb0-7a77-6ef9808ca4fd
* Content: [Tutorial: Create a matching game - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-create-match-game?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-create-match-game.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-create-match-game.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@rvwilliams88, thanks for your feedback. 
Using the UseCompatibleTextRendering for Webdings display issue is called out in [Tutorial Step2: Add icons to your match game](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-match-game-icons?view=vs-2022&tabs=csharp#assign-a-random-icon-to-each-label).

We've updated [Tutorial Step1: Create a matching game](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-create-match-game?view=vs-2022#add-and-format-labels-to-display) also to add this note. Changes should be live later today. Thanks!
