### ISSUE TITLE
Nullable reference types are not mentioned in the C# tutorial

### ISSUE THREAD

**Issue by ineternet** [MicrosoftDocs/visualstudio-docs#10082]
The linked page instructs how to create a .NET 8.0 project and write code, but does not mention nullability or the NRT setting. When the tutorial is followed word for word, the code ends up having warnings because some methods (like `Console.ReadLine`) return `string?` and the tutorial assigns them to a `string` variable, all while the default project template for a .NET 8 console app enables NRT by default.

The warnings themselves are not very beginner friendly either, because VS does not have a code fix for any of them (besides suppressing the warning). The tutorial should take some approach to eliminate the warning before it is ever introduced, for example:

- Instruct to swap the `<Nullable>` csproj setting to `disabled`.
- Suppress the warning on some level. This may not be ideal because the 2nd part of the tutorial involves creating a new library project.
- Rewrite the code examples to work with NRTs correctly (use `string?`) and explain this.

At the very least there should be an info block explaining the meaning of the warning.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Version Independent ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Content: [Tutorial: Create a simple C# console app  - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-console.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@ineternet -- thank you for your feedback.

@anandmeg -- please look into this issue.
