### ISSUE TITLE
are they ALL REALLY necessary?

### ISSUE THREAD

**Issue by sbrickey** [MicrosoftDocs/visualstudio-docs#1008]
are you really telling me that VS cannot be stable unless it's running 14 processes (VS + 13)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72292f7a-7616-4727-ccd3-cf44bb130477
* Version Independent ID: fe3cca82-dfd7-a85c-ab4f-014bc546d668
* Content: [Visual Studio unrecoverable process error - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/visual-studio-unrecoverable-process-error)
* Content Source: [docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by heejaechang** [comment]
@sbrickey can you be more specific? are you asking whether you should have a way to decide what external process you want? or VS should keep working even though some of processes are killed?

**Comment by gewarren** [comment]
@sbrickey,

The error message mentioned in the topic isn’t shown for all of these processes, so the topic should be reworded a bit (I'll do that soon).

The processes listed in the topic includes processes that launch in specific workflows/scenarios, and so in most cases they won’t all be running at the same time. However, if any of these processes is running and then terminates unexpectedly, then some functionality within VS will stop working. The functionality and stability of the rest of VS after that happens depends on which process it is that’s terminated.

**Comment by sbrickey** [comment]
I very much want to reduce the number of processes running... I seem to (rather frequently) run into blocking issues whereby one of the compilers is locking the bin/debug output files (thus causing VS to be unable to build in-process), and my solutions include ZERO javascript whatsoever - no need for NPM, no node, no client-side web app, NOTHING.

**Comment by heejaechang** [comment]
@sbrickey I am not right person to say whether VS now moving from traditional 1 single process model to multiple process models is good thing or not. that probably for another person to answer. (but we are moving to that model, more and more features will be moved to dedicated its own process)

but I can help you on this - "I seem to (rather frequently) run into blocking issues whereby one of the compilers is locking the bin/debug output files (thus causing VS to be unable to build in-process)"

but we probably want to do that on VS feedback site that let us to gather diagnostics info more easily. when that issue happen again, can you click feedback from VS and report through there with dump and logs in %temp%\servicehub\logs?

if possible, other info like what processes are holding locks on those files will be helpful for us to figure out.

**Comment by gewarren** [comment]
@sbrickey Closing this documentation issue in the hopes we can continue the investigation, if necessary, through Visual Studio's "[Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017)" feature (which syncs with Developer Community).
