### ISSUE TITLE
Why is curl installed twice?

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/visualstudio-docs#10091]
The sample docker file has these two lines..

```
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
```
Curl is in the second as well as the first - is there a reason?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1abf884f-eb39-1007-25a6-d049b87504a3
* Version Independent ID: 33636e79-d3e1-8c24-f3a5-0c3c79e2a488
* Content: [Build React app with Visual Studio Container Tools](https://learn.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2022)
* Content Source: [docs/containers/container-tools-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/container-tools-react.md)
* Service: **visual-studio-windows**
* Sub-service: **container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@phatcher
Yes, it is because Node is being installed (using cURL) on both the base and dev stages. The dev stages is based on a different image that contains build support infrastructure, but that adds too much extra size for the final image.
