### ISSUE TITLE
There is no All Accounts

### ISSUE THREAD

**Issue by coderskarma** [MicrosoftDocs/visualstudio-docs#10092]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0fbbc520-9d46-ff40-59af-3ec0c0c5dc84
* Version Independent ID: a3c07335-ea71-1b0e-6da8-080bfe34937d
* Content: [Add GitHub accounts to your keychain - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/work-with-github-accounts?view=vs-2022)
* Content Source: [docs/ide/work-with-github-accounts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/work-with-github-accounts.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@coderskarma -- Lasse, thank you for your feedback.  I am finding All Accounts in Visual Studio 2022:

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/27738025/6816b302-0f99-498c-8a3c-bb5f8f985681)
