### ISSUE TITLE
File nesting in Solution Explorer

### ISSUE THREAD

**Issue by AngelosP** [MicrosoftDocs/visualstudio-docs#1010]
It's a new feature that we recently shipped in Visual Studio 2017, but not documented anywhere except in [this blog post](https://blogs.msdn.microsoft.com/webdev/2018/02/07/file-nesting-in-solution-explorer/).

**Comment by AngelosP** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/pull/1011

**Comment by gewarren** [comment]
#2116 in the private repo was merged.
