### ISSUE TITLE
Code Map not proposed when modifying MSVS Enterprise 2022

### ISSUE THREAD

**Issue by OlivierJ1** [MicrosoftDocs/visualstudio-docs#10109]
Ms Visual Studio Enterprise 2022 - 17.9.2 // Want to install & use Code Map
Not proposed as shown in the following screen copy:

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/153212359/410bccf8-191f-48c8-ad9c-4fcf5eeeab0a)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2022)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/install-architecture-tools.md)
* Service: **visual-studio-windows**
* Sub-service: **modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
That is strange indeed. When I search for "code" in the search box above then Code Map is listed for me under Code tools:

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/14282894/3b78dd41-c285-4921-9666-b6638114e15c)

Do you see "Architecture and analysis tools" as an optional component under the ".NET desktop development" workload?

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/14282894/4b410f18-9328-4f36-860e-06b0786be352)

**Comment by OlivierJ1** [comment]
No, I don't have it as an optional component under the ".NET desktop development" workload:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/153212359/45536585-7e96-48fd-b256-03b7c03c4d42)

But I can see it as an optional component under the "Universal Windows Platform development" workload:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/153212359/08426500-695e-45ce-8015-4d434b05c769)

**Comment by mgoertz-msft** [comment]
Strange but shouldn't really matter as it's the exact same setup component. Do you see a menu item called `Show on Code Map` when you right click on a .NET project?

If this is the only machine that exhibits this behavior then perhaps you may want to try and run `Repair` on your installation.

**Comment by OlivierJ1** [comment]
I didn't installed .Net:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/153212359/7dee1590-5f25-4372-ac07-3760370f3216)
Shall I ?

**Comment by mgoertz-msft** [comment]
Yes, it would be worth trying to install ".NET desktop development". Although, in your earlier screenshot it looked like you did have it installed.

**Comment by OlivierJ1** [comment]
I'll try that + tell you if it works.

/// "Although, in your earlier screenshot it looked like you did have it installed." ///. >>>> I had to set the check box to see the .Net component list.

**Comment by OlivierJ1** [comment]
NOK // Now trying 'Repair'.

**Comment by OlivierJ1** [comment]
Tried repair twice (2nd time after removing "Universal Windows Platform development") --> NOK
No more "Architecture and analysis tools" checkbox anywhere.  :((
Any idea ?

**Comment by mgoertz-msft** [comment]
That's bizarre. Besides completely uninstalling and then reinstalling VS the only thing left would be to `Report a problem` in the VS Installer, so that the installer team can take a look at it.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/14282894/4125493a-8604-4848-9061-eabe6d508027)

**Comment by OlivierJ1** [comment]
Hello Marco,
I just finished completly uninstalling Visual Studio and restarted the computer.
The installer still does not propose 'Architecture and analysis tools' as an optional component under the ".NET desktop development" workload.    ????
So if you have any advice before I launch the installation... my ears are opened. 

I searched for information over the Internet and on [this page](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/includes/vs-2022/workload-component-id-vs-enterprise.md), I found the following:
<img width="1048" alt="image" src="https://github.com/MicrosoftDocs/visualstudio-docs/assets/153212359/239e2429-aa6b-4e50-862a-89ab4f94e26c">
<img width="1038" alt="image" src="https://github.com/MicrosoftDocs/visualstudio-docs/assets/153212359/e5f27709-30a7-4e82-b15e-842c2251a709">
--> Version = 17.9.34511.75, while the installer pushed MSVS Enterprise 2022 version 17.9.2.

And at the top of the page there is the following:
<img width="1048" alt="image" src="https://github.com/MicrosoftDocs/visualstudio-docs/assets/153212359/4b440449-01c2-4911-ab10-9f544fdd363c">

Does this ring any bell?

**Comment by mgoertz-msft** [comment]
I'm afraid not. Just to double-check though, this isn't by chance an ARM64 version of VS you are trying to install, is it?

**Comment by OlivierJ1** [comment]
I am running W11 in Parallel Desktop on a MacBook Pro based on an ARM64.
Is the issue because the processor is a ARM64?

I can run x86 & 64b Intel executable. Just need the right exe.

**Comment by mgoertz-msft** [comment]
Ah, yes, that is the problem. None of the Architecture Tools have been ported to ARM, so that's why they don't get installed by VS.

Honestly, I don't even know if you can trick the installer to install the non-ARM version of VS. Even if you could I'm not sure it would run right, and if it did it would probably be very slow.

**Comment by mgoertz-msft** [comment]
@WilliamAntonRohm Would you mind updating the note to mention that ARM is not supported? Thank you!

**Comment by OlivierJ1** [comment]
Not the result I was expecting :(, anyway thanks for your assistance @mgoertz-msft.
Is there any chance that the Architecture Tools will be ported to ARM for the next release?

**Comment by mgoertz-msft** [comment]
I'm sorry, but there are no plans at the current time. There hasn't really been any demand and the team is working on other high priority items.

**Comment by OlivierJ1** [comment]
@mgoertz-msft , @TimShererWithAquent 
Too bad :( 
I was hoping this would be a simple matter of rebuild for ARM... but it's never that simple.
Anyway, thank you for your time.
All the best.
Olivier
