### ISSUE TITLE
Why does this page recommend a module that was replaced years ago?

### ISSUE THREAD

**Issue by blakeduffey** [MicrosoftDocs/visualstudio-docs#10100]
HttpPlatformHandler has been replaced by ASP.NET Core Module

https://github.com/aspnet/Announcements/issues/164

Why recommend something that was deprecated in 2016?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed35685d-e409-d962-c450-7297a1f3c003
* Version Independent ID: 224fab0f-fd26-396f-cdd8-921533d2aeba
* Content: [Configure Python web apps for IIS - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/configure-web-apps-for-iis-windows?view=vs-2022)
* Content Source: [docs/python/configure-web-apps-for-iis-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/configure-web-apps-for-iis-windows.md)
* Service: **visual-studio-windows**
* Sub-service: **python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
Thanks for filing this issue! I am looking into this now and found an older thread with a similar discussion (https://github.com/MicrosoftDocs/visualstudio-docs/issues/4734). I will investigate and see if we can update the docs in accordance with ASP.NET Core Module.

**Comment by blakeduffey** [comment]
Thanks very much - in researching this topic, nearly all the online references I was able to find leverage deprecated tools.

**Comment by cwebster-99** [comment]
The team has made edits to the doc in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/12295. #please-close

**Comment by blakeduffey** [comment]
The url referenced is a 404 - has this documentation been updated?

**Comment by lextm** [comment]
@blakeduffey That's a common misinterpretation of that ASP.NET Core team announcement,

https://docs.lextudio.com/blog/the-rough-history-of-iis-httpplatformhandler/#the-mist-of-aspnet-core

In short, Python people should continue to use HttpPlatformHandler, which is fully supported by IIS/Azure.
