### ISSUE TITLE
The description of this extract method does not match the behavior in VS 2022

### ISSUE THREAD

**Issue by dmartensson** [MicrosoftDocs/visualstudio-docs#10111]
[Enter feedback here]
In the latest VS 2022 when I tried this it did not extract the selection I had made, rather it expanded the selection to the next parentesis.

Using this example

namespace MyTest
{
    internal class Test
    {
        public void DoTest(int a, int b, int c)
        {
            if(a < 10 && b > 100 && c == 5)
            {
                Console.WriteLine("Hello");
            }

        }
    }
}

If I select the "b > 100 && c == 5" and right click and choose QuickRefactoring and select extract method, it will extract the full "a < 10 && b > 100 && c == 5" to the new method, not just my selection.

This makes the feature much less useful.

Now I am not sure if this is how its always worked since I on work always have been using a plugin that gives better tools for this.

![Extract_Method](https://github.com/MicrosoftDocs/visualstudio-docs/assets/639559/db7ffc62-c61f-4ef3-b1ee-0c56066b617d)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3506512-caae-6f4e-d27c-5204edb95e77
* Version Independent ID: 84c00803-50fe-c354-491e-e5c2f65d8d07
* Content: [Extract a method - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/extract-method?view=vs-2022)
* Content Source: [docs/ide/reference/extract-method.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/extract-method.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@dmartensson  Thanks for your feedback; I do see the same behavior and from the article it's not clear what kind of fragment or portion of a statement can be selected. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
Closing this here.
