### ISSUE TITLE
Solution Explorer docs should mention "external items"

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/visualstudio-docs#10118]
At least on my machine, neither "search within file contents" or "search within external items" are on by default.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/5030577/42cb4abf-e1e6-4c43-9ff3-c09e802fbd19)

Searching external items is extremely useful, because in .NET projects, it allows you to search for transitive packages, and see the package graph that caused the package to be included: 

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/5030577/65706cd3-d049-457a-82c6-8df48de489ee)

I think this should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c1f9dc4a-d8a6-6642-635c-6c6204467b3e
* Version Independent ID: 05f0ffc9-109a-43bc-d9f3-55d14242db33
* Content: [Learn about Solution Explorer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/use-solution-explorer?view=vs-2022)
* Content Source: [docs/ide/use-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/use-solution-explorer.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
Thanks for the feedback, @zivkan! We've updated the doc and changes should be live later today.
