### ISSUE TITLE
Visio chat github

### ISSUE THREAD

**Issue by Kahute344** [MicrosoftDocs/visualstudio-docs#10113]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 502be84d-8d2a-6c03-a118-279608698898
* Version Independent ID: 502be84d-8d2a-6c03-a118-279608698898
* Content: [About the GitHub Copilot Chat extension for Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-gb/visualstudio/ide/visual-studio-github-copilot-chat?view=vs-2022)
* Content Source: [docs/ide/visual-studio-github-copilot-chat.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/visual-studio-github-copilot-chat.md)
* Service: **visual-studio-windows**
* Sub-service: **ai-tools**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by TimShererWithAquent** [comment]
@Kahute344 There's no description of the issue that you encountered. Can you clarify your feedback?

**Comment by ghogen** [comment]
@Kahute344
We'll close this issue for now. If you get a chance to write up your feedback, we can take a look at that.
