### ISSUE TITLE
error creating .log file

### ISSUE THREAD

**Issue by YeshuaNun** [MicrosoftDocs/visualstudio-docs#10110]
I am working through this tutorial and have followed the instructions. I can run the program and perform calculations. But it is not creating the calculator.log file. When I press 'n' and then enter, instead I get some error on the screen. This is a screen shot of what I am getting.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/145120313/dc6543c4-f29e-4d68-9dbf-a6c6621f19ba)

Thinking I had followed some instructions wrong, I then copied and pasted the code for the CalculatorLinbrary.cs and Program.cs exactly as written in the tutorial.

What could I have done wrong?

**Comment by TimShererWithAquent** [comment]
@YeshuaNun Can you clarify - is this feedback for a particular article?

**Comment by YeshuaNun** [comment]
It is for the following:
https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/145120313/43348163-678c-45ab-b544-14ba27651aff)

When you click the feedback link, it takes you to this github area. So that is where I have submitted my issue.

**Comment by ghogen** [comment]
@YeshuaNun 
Thanks for the feedback! It turns out the location of the log file is incorrect, it should be bin/Debug/net8.0 (or whatever .NET version you used). I'm updating this article now to correct that.
