### ISSUE TITLE
I setup visual studio 2017  professional offline and failed.

### ISSUE THREAD

**Issue by jsrdzhk** [MicrosoftDocs/visualstudio-docs#1012]
After i type the command and execute.The setup program stopped directly.It seems like the visual studio installer cannot work in my computer.Please give me an answer.Thanks!

**Comment by gewarren** [comment]
@TerryGLee Can you point @jsrdzhk to the right place to log his issue with installation?

**Comment by TerryGLee** [comment]
@jsrdzhk We're sorry to hear that you are having problems installing Visual Studio. Unfortunately, this venue is meant for reporting problems with our documentation. To report a problem with the product itself, please use our "[Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us#i-want-to-report-a-problem-with-visual-studio)" tool. 

Please note that you can report a problem even if you cannot install Visual Studio by using the Visual Studio Installer. You can find more information about that in the "Reporting alternatives" section of the [How to report a problem with Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#reporting-alternatives-a-namealternatereportinga) page.

Last but not least, we do offer other support solutions for installation problems. For example, we offer a [live chat](https://www.visualstudio.com/vs/support/#talktous) option. For more information about that and other product support options for installation, see the "Get support" section of the [Install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio#get-support) page.

Thanks,
~ Terry
