### ISSUE TITLE
Dependency Diagram not available

### ISSUE THREAD

**Issue by seawerst** [MicrosoftDocs/visualstudio-docs#10125]
Are we sure dependency diagram are still available in Visual Studio? This choice no longer seems to be available with the latest two versions.
[Whats new in 2017](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2017/modeling/what-s-new-for-design-in-visual-studio?view=vs-2017#uml-designers-have-been-removed)

I have Visual Studio 2022 Enterprise edition with these two components installed.
- Code Map
- Live Dependency Validation
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/5280138/763b8419-9f56-4a9e-bc89-ec5b3dc7266a)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6db0df9a-ef09-a374-d289-9beda002a71d
* Version Independent ID: 2fcc9ad1-f65f-b242-ef0b-3a128ecd23a6
* Content: [Create dependency diagrams from your code - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/create-layer-diagrams-from-your-code?view=vs-2022&source=recommendations)
* Content Source: [docs/modeling/create-layer-diagrams-from-your-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/create-layer-diagrams-from-your-code.md)
* Service: **visual-studio-windows**
* Sub-service: **modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
I'm afraid I'm not following. What choice is no longer available? The screenshot shows the `New Dependency Validation Diagram` command, which indicates it's installed.

**Comment by ghogen** [comment]
@seawerst
We'll close this issue for now, but if you can show us what exactly you think is missing here, we can take another look. Thanks!
