### ISSUE TITLE
Missing details in 'Application Files dialog box'

### ISSUE THREAD

**Issue by HughWarrington** [MicrosoftDocs/visualstudio-docs#10120]
I'm looking at the 'Application Files dialog box' section of this page.

Could this include more information about how that list of files is generated?

Currently it says:

> It contains a grid that lists the project files that are not excluded by default, or that have a download group.

What does 'excluded by default' mean? Is the list generated by analysing the project files, looking at the build output, or something else? As far as I can see, the answer is 'something else', since the list of files does not match either of those other sources. Also, the contents of the list are different after cleaning my build output directories compared to after a successful build.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab856c02-f379-f49e-e802-87bf64aaaf64
* Version Independent ID: cef1c93e-b929-502d-a553-158aea470c1c
* Content: [Publishing ClickOnce Applications - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/deployment/publishing-clickonce-applications?view=vs-2022)
* Content Source: [docs/deployment/publishing-clickonce-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/publishing-clickonce-applications.md)
* Service: **visual-studio-windows**
* Sub-service: **deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@HughWarrington Did you already read this article? https://learn.microsoft.com/en-us/visualstudio/deployment/how-to-specify-which-files-are-published-by-clickonce
"...all non-code files in the project are deployed along with the application." And the article has information such as this: "Files with the Build Action property set to Content are designated as application files and will be marked as included by default." along with exceptions to this. 
What are you seeing that does not conform to expected behavior?

**Comment by Mikejo5000** [comment]
@HughWarrington Let me know if you have any more details and we can re-open this.

**Comment by HughWarrington** [comment]
Hi @Mikejo5000 thank you for your reply.

Yes I read that other page too. It has helpful information, although as it happens I find that first sentence  "...all non-code files in the project are deployed along with the application" to be vague (1), technically incorrect (2), and contradicted by the rest of the page (3).

(1) What are "non-code files in the project"? Is a dll file code or non-code?
(2) Looking in my current project for example, here's a file which is surely 'non-code' which is _not_ deployed along with the the application: an .ico file with build action 'None'.
(3) Even within the same paragraph, we learn that files can selectively be excluded -- so not 'all' files are deployed necessarily.

The linked page does tell you one way to add files to the Application Files dialog box (set Build Action to Content) but that's clearly not the only way, since my built .dlls are included in the dialog box already and they don't appear in Solution Explorer. Furthermore as I wrote above "the contents of the list are different after cleaning my build output directories compared to after a successful build" so that's another part of the answer.

My question remains 'how exactly is the contents of the Application Files dialog box arrived at?'

**Comment by HughWarrington** [comment]
For what it's worth, despite my ranting above I don't think this is a 'badly written documentation' issue, more an 'undocumented behaviour' issue.

**Comment by Mikejo5000** [comment]
@HughWarrington We will be tracking this issue internally as I look into the details, so I'm closing it here.
