### ISSUE TITLE
Various clarifications to remote testing

### ISSUE THREAD

**Issue by tylermontneyacc** [MicrosoftDocs/visualstudio-docs#10122]
- Which test project templates are supported? Requirements states "Currently, the feature supports .NET tests only.", so "Unit Test Project (.NET Framework)"?
- Where is Windows Projected File System supposed to be installed, Development or Test machine?
- Is .NET 6.0 required for remote testing? Requirements makes reference to 6.0 if that happened to be your targeted framework; however, [this](https://developercommunity.visualstudio.com/t/Remote-Unit-Testing-on-Windows-environme/10491687?space=21&scope=follow&sort=newest) shows the Test Windows Remote Agent seems to require it. (**What is the Test Windows Remote Agent, anyway?**)
- What type of configuration is required for the Remote Debugger? It's referenced in Step 4 of "Prerequisites for a remote Windows environment"; however, we're using SSH to connect to the test machine. This isn't a traditional VS project, so it's ambiguous how the Remote Debugger operates here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ec9455-ef64-8854-94bc-9be28887a6a4
* Version Independent ID: 9adeea5e-7ba1-065f-5de0-aae9147f9c85
* Content: [Remote Testing in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022#prerequisites-for-a-remote-windows-environment)
* Content Source: [docs/test/remote-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/remote-testing.md)
* Service: **visual-studio-windows**
* Sub-service: **test-tools**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo***

**Comment by Mikejo5000** [comment]
@tylermontneyacc I believe .NET Framework projects are excluded when it says that only .NET is supported, but this should be clarified. Usually we try to say, as an example, " '.NET Core 3.1 and .NET 5+' to be more specific when excluding .NET Framework. 
It appears to me that WPFS should be running on the remote test machine. According to the instructions, starting the remote tools is a requirement. @AbhitejJohn Abhitej, can you take a look at these questions and advise? Thanks!

**Comment by AbhitejJohn** [comment]
Thanks @Mikejo5000 . Adding @peterwald to help. 

@tylermontneyacc :thank you for reaching out. 
Here's what I'm aware off and Peter please feel free to correct me:

> Which test project templates are supported? Requirements states "Currently, the feature supports .NET tests only.", so "Unit Test Project (.NET Framework)"?

This would work for projects targetting both .NET Framework and .NET Core. Of course the projects targeting .NET Framework would only be able to run on a remote windows environment.

> Where is Windows Projected File System supposed to be installed, Development or Test machine?

This would be on the machine where the tests are being run remotely and not where VS is.

> Is .NET 6.0 required for remote testing? Requirements makes reference to 6.0 if that happened to be your targeted framework; however, [this](https://developercommunity.visualstudio.com/t/Remote-Unit-Testing-on-Windows-environme/10491687?space=21&scope=follow&sort=newest) shows the Test Windows Remote Agent seems to require it. (What is the Test Windows Remote Agent, anyway?)

.NET 6.0 is not a requirement. We just need the same runtime installed as what the project targets. So, if the project targets .NET 8.0, the remote environment would need to have that installed.

> What type of configuration is required for the Remote Debugger? It's referenced in Step 4 of "Prerequisites for a remote Windows environment"; however, we're using SSH to connect to the test machine. This isn't a traditional VS project, so it's ambiguous how the Remote Debugger operates here.

As far as I'm aware it is just these two that the document calls out:
"Install the [Remote tools SKU](https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022&preserve-view=true) on the remote environment.

Start up the remote debugger as an admin and ensure the Visual Studio user has permissions to connect."
Is that not working?

**Comment by tylermontneyacc** [comment]
> This would work for projects targetting both .NET Framework and .NET Core. Of course the projects targeting .NET Framework would only be able to run on a remote windows environment.

> This would be on the machine where the tests are being run remotely and not where VS is.

Can these two items be better clarified in the docs?

> .NET 6.0 is not a requirement. We just need the same runtime installed as what the project targets. So, if the project targets .NET 8.0, the remote environment would need to have that installed.

How does "Test Windows Remote Agent" fit into this? (It requires .NET 6.)

> As far as I'm aware it is just these two that the document calls out:
> "Install the [Remote tools SKU](https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022&preserve-view=true) on the remote environment.

> 
> Start up the remote debugger as an admin and ensure the Visual Studio user has permissions to connect."
> Is that not working?

I have it running as admin without authentication. I'm assuming it doesn't require me to configure Debug > Use Remote Machine? (I have remote debugging working for other projects.)

After following this doc, I cannot get this to work. I have the same issue as https://developercommunity.visualstudio.com/t/Remote-Unit-Testing-on-Windows-environme/10491687?space=21&scope=follow&sort=newest.

**Comment by AbhitejJohn** [comment]
> Can these two items be better clarified in the docs?

Absolutely.

> How does "Test Windows Remote Agent" fit into this? (It requires .NET 6.)

That should ideally not require .NET 6. It's a process that helps us coordinate test runs remotely. 

> I have it running as admin without authentication. I'm assuming it doesn't require me to configure Debug > Use Remote Machine? (I have remote debugging working for other projects.)

That's correct. 

>After following this doc, I cannot get this to work. I have the same issue as https://developercommunity.visualstudio.com/t/Remote-Unit-Testing-on-Windows-environme/10491687?space=21&scope=follow&sort=newest.

Ah I see your post and that @peterwald has been looking into the problem. We'll keep investigating on the ticket and keep you posted if we need any additional logs/details. Thank you for sharing.

**Comment by Mikejo5000** [comment]
@AbhitejJohn Thanks, Abhitej! I will clarify these points in the article.

**Comment by Mikejo5000** [comment]
Clarifications to the requirements should be live by EOD today, 3/19/24 PST.
