### ISSUE TITLE
Can't fetch projects from TFS

### ISSUE THREAD

**Issue by MJRomka** [MicrosoftDocs/visualstudio-docs#1017]
I use Visual Studio for Mac (latest version) with TFS extension installed. Once I provide my credentials it shows "Choose Projects" dialog box that never stops loading, see attached
![add remove server 2018-05-23 18-35-22](https://user-images.githubusercontent.com/3237392/40435107-97cddd5c-5eb8-11e8-8789-7799ae7a8ccc.png)

**Comment by gewarren** [comment]
@asb3993 Can you help with this at all?

**Comment by asb3993** [comment]
Hi @MJRomka. Thanks for trying out this preview feature and reporting this issue. It looks like this is a known issue and has quite a number of followers on [this developer community ](https://developercommunity.visualstudio.com/content/problem/248618/cant-connect-to-tfs-version-control-in-visual-stud.html) issue. I would recommend upvoting and following this bug to be alerted of any potential workarounds and fixes. 

As this is a preview feature, I'm going add some known issues and workarounds to the article and will continue to keep it updated while the product is in preview.

**Comment by MJRomka** [comment]
Will track it there then. Thank you
