### ISSUE TITLE
Instructions for opening admin cmd are wrong

### ISSUE THREAD

**Issue by benmcmorran** [MicrosoftDocs/visualstudio-docs#1020]
Following the instructions, you end up at the run dialog with "cmd" typed in the Open box, but then there's no "Command Prompt" to right click on. Instructions should read:

On the Start menu, type cmd.
Right-click Command Prompt, and then click Run as administrator.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
@tglee I have a fix for this available.

**Comment by TerryGLee** [comment]
@heaths Please feel free to create a PR for the fix :)

**Comment by TerryGLee** [comment]
@heaths Thanks for the PR with the fix. :)
@benmcmorran Thanks for your feedback; the fix for the issue you noted should go live by noon tomorrow.
