### ISSUE TITLE
Why doesn't copying settings... actually copy settings?

### ISSUE THREAD

**Issue by nic-hartley** [MicrosoftDocs/visualstudio-docs#1021]
I'm trying to create an x64 configuration. Because it's not an entirely new project, I don't want to retype every single setting from scratch. However, when I try to copy settings from my existing configurations, the settings aren't actually copied, and they all have their default values instead of the values present in the other platform, which in theory should have been copied. Why is this and how do I fix it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb5a706d-01d5-40c8-69af-e223a73a5948
* Version Independent ID: 8d5a1950-1b98-7e22-0f40-02a8ab0e7233
* Content: [How to: Configure projects to target platforms - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms)
* Content Source: [docs/ide/how-to-configure-projects-to-target-platforms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-configure-projects-to-target-platforms.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@nic-hartley I will try this out and let you know.

**Comment by gewarren** [comment]
@nic-hartley I tried this out and it seems to have copied the settings from the [Build tab](https://docs.microsoft.com/en-us/visualstudio/ide/reference/build-page-project-designer-csharp) of the project properties into the new configuration correctly. Which settings were you expecting to get copied that didn't?

**Comment by nic-hartley** [comment]
Er, all of them -- no settings are copied. Everything "resets" to its default value in the new platform.

I also realize that my initial description wasn't at all clear. I'm currently waiting for a video showing it to upload, but in the mean time, this is a step-by-step description of exactly what I'm doing:

1. Opening a solution with some projects in it
2. Right-clicking one of them (let's call it `pcppe`, because that's what it's called) and opening the Properties menu
(Note: Here I can double-check that something is set to something other than the default -- my output directory is `$(SolutionDir)build\$(Configuration)\` -- which is useful for confirming later)
3. Clicking the button in the top right labeled "Configuration Manager"
4. Ensuring that no x64 configuration exists by going through both Debug and Release active configurations and checking all of the dropdowns under "Platform" to confirm that the only one that exists is Win32/x86
5. Clicking `<New...>` in the dropdown under "Active solution platform" (*not* the per-project one; the one at the top of the window)
6. Selecting x64 in the top dropdown (Type or select the new platform), and x86 in the bottom dropdown (Copy settings from)
7. Check "Create new project platforms".
8. Click OK.
9. Navigate to the x64 platform.
10. Notice that the Output Directory is now set to `$(SolutionDir)$(Platform)\$(Configuration)\`.
(Note: The original platform, x86, isn't changed, thankfully. I think I'd go insane if it did. It's just that x64 doesn't have any of x86's settings.)

I did notice an odd discrepancy while doing this more carefully -- sometimes the platform is called x86, sometimes it's Win32. Specifically, at the solution level it seems to be called x86, while at the project level it seems to be called Win32. Could this be causing the issue?

**Comment by gewarren** [comment]
@nic-hartley I see what you're seeing too. I'll investigate a little more. We have a similar issue #667.

**Comment by gewarren** [comment]
@nic-hartley This certainly seems like a bug to me, and I think it is specific to C++ projects (I tried in a C# project and the settings were copied correctly). And thank you for providing the clear steps and even a video. Can you open an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html)? I did a brief search there and didn't find any existing issues for copying settings.

I'm going to close this documentation issue as I don't believe it's a documentation issue. If you feel that this issue should be reopened, just leave me a comment here.

**Comment by nic-hartley** [comment]
I've reported this to Developer Community [here](https://developercommunity.visualstudio.com/content/problem/269259/settings-in-c-projects-arent-copied-with-the-confi.html). No need to reopen; you're right, this isn't a documentation issue. (I assumed I was missing a setting or something, which is why I posted it here.)

**Comment by gewarren** [comment]
@nic-hartley Thanks so much for reporting the issue!
