### ISSUE TITLE
Obsolete SuggestedActionSet ctor

### ISSUE THREAD

**Issue by Regenhardt** [MicrosoftDocs/visualstudio-docs#1022]
The constructor for SuggestedActionSet in the GetSuggestedActions snippet is obsolete and will result in a build error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128df8db-917f-1049-feff-52e861d7646a
* Version Independent ID: ef42a322-b94d-8d1a-13aa-e1e57d67b78f
* Content: [Walkthrough: Displaying Light Bulb Suggestions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-light-bulb-suggestions#feedback)
* Content Source: [docs/extensibility/walkthrough-displaying-light-bulb-suggestions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-light-bulb-suggestions.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@Regenhardt Thanks for reporting this. @gregvanl could you add this to you or Mads' TODO list?

**Comment by tunguyen305** [comment]
I added code like this walkthrough, but when open a *.cshtml file and mouse click into a word on file, there are more than 1 context menu item are display (for each suggest action)
Like this:
Convert 'abc' to upper
Convert 'abc' to upper

(I remove lower action for testing)

**Comment by LaraSQP** [comment]
So, what is the non-obsolete alternative?

**Comment by LaraSQP** [comment]
You guys should comment your code better.

Turns out that using the **obsolete** constructor is the only way to avoid the following exception.

> System.InvalidOperationException: Can only compare ISuggestedActionCategories defined with SuggestedActionCategoryRegistryServiceat Microsoft.VisualStudio.Language.Intellisense.Implementation.SuggestedActionCategoryComparer.Compare(String x, String y)at System.Linq.EnumerableSorter`2.CompareKeys(Int32 index1, Int32 index2)at System.Linq.EnumerableSorter`1.QuickSort(Int32[] map, Int32 left, Int32 right)at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultLightBulbPresenterDefaultIconUIElementProvider.GetUIElement(ISuggestedActionCategorySet itemToRender, ILightBulbSession context, UIElementType elementType)at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb..ctor(LightBulbSession session, LightBulbPresenterStyleFactory presenterStyleFactory)at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbTagger.<Microsoft.VisualStudio.Text.Tagging.ITagger<Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbTag>.GetTags>b__10_1()at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbTag.get_Glyph()at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbGlyphFactory.GenerateGlyph(IWpfTextViewLine line, ISuggestionTag tag)at Microsoft.VisualStudio.Text.Editor.Implementation.CanvasAndGlyphFactory`1.GenerateGlyph(IWpfTextViewLine line, ITag tag)at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMarginVisualManager`1.AddGlyph(TGlyphTag tag, SnapshotSpan span)at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMargin`1.RefreshGlyphsOver(ITextViewLine textViewLine)at Microsoft.VisualStudio.Text.Editor.Implementation.GlyphMargin`1.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args) --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

Not cool. Not at all.

This is a breaking change.

Let me know if you need more details.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
