### ISSUE TITLE
The link of "Managed Package Framework for Projects" points to deprecated codeplex site

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/visualstudio-docs#1027]
The link on this paragraph points to deprecated (for viewing only?) site:

> You can create your own project types with the Visual Studio SDK and the Managed Package Framework for Projects, which you can download at _Managed Package Framework for Projects_. 

Has the link been migrated to other OSS repo such as Github? Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e54b888-936c-aaff-c5f9-cd8d2324df39
* Version Independent ID: ad62b5a4-3198-b135-b7a1-9574cec41573
* Content: [Extending Projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-projects)
* Content Source: [docs/extensibility/extending-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extending-projects.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by eriawan** [comment]
Here's the deprecated Codeplex link: 

https://archive.codeplex.com/?p=mpfproj12

Is there any plan to move/migrate this mpf to Github or somewhere else? Otherwise this article contains link that looks stale.

**Comment by gewarren** [comment]
@eriawan Thanks for the feedback about the stale link. @gregvanl do you know if MPF for Projects has been migrated off of CodePlex?

**Comment by eriawan** [comment]
hi @gewarren 

Any updates on this issue? 

cc @gregvanl

**Comment by eriawan** [comment]
hi @gewarren and @gregvanl 

It's almost a month, and I hope there should be any update on this.
Please confirm for any update on this issue.

**Comment by gewarren** [comment]
@eriawan It looks like it's available on GitHub here: https://github.com/tunnelvisionlabs/MPFProj10

**Comment by eriawan** [comment]
@gewarren 
Thanks! I have checked and it is the correct updated link for the deprecated codeplex link.

Since this is quite easy to fix, I have submitted a PR: #1410

**Comment by gewarren** [comment]
@eriawan That's great, thanks so much!
