### ISSUE TITLE
Obtaining thumbprint

### ISSUE THREAD

**Issue by wpoust** [MicrosoftDocs/visualstudio-docs#1028]
A word of caution about obtaining the thumbprint from the certificate using the 'Obtain the SHA-1 Hash of a Trusted Root CA Certificate 'in the Note.  On Windows Server 2016, select all, copy and paste from the certificate details included an extra (3F) invisible character that caused SignFile to be unable to find the certificate.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09ffd23-115c-368b-c17f-7d3af54f0a67
* Version Independent ID: b640eb45-9978-0a9e-f8dc-fd2581e84fb5
* Content: [SignFile Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/signfile-task)
* Content Source: [docs/msbuild/signfile-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/signfile-task.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
@wpoust Thanks for mentioning this. @Mikejo5000 should we include this info in the topic?

**Comment by Mikejo5000** [comment]
Yes, I can plan to add a note about that. Thanks!
