### ISSUE TITLE
Using ms-help protocol links

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#1034]
EX: used in a few of the code quality descriptions https://github.com/MicrosoftDocs/visualstudio-docs/search?q=ms-help%3A%2F%2F&unscoped_q=ms-help%3A%2F%2F
Might work if people have the particular offline docs (I think ?), but probably a good idea to swap to published links if possible.

**Comment by gewarren** [comment]
@nschonni Thanks for reporting these. @mikeblome are links such as this kosher? They appear in four C++ code-quality topics.

Consider using ... [FAILED](ms-help://MS.VSCC.2003/MS.MSDNQTR.2003FEB.1033/com/htm/error_899v.htm)

**Comment by corob-msft** [comment]
This is addressed in a fix that should be visible on September 12th. Thanks for bringing it to our attention, @nschonni !
