### ISSUE TITLE
Dead link roundup (no more spamming)

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#1035]
Instead of posting individual issues I figure this might be easier for our inboxes.
Here is a gist of what I ran and what it found https://gist.github.com/nschonni/65167b88c4b187ba242c837e5ec6e666
Caveats:
- markdown-link-check has no concept of the redirect.json so there are false possitives
- can search in file for "dead" to see the flagged issues
- I've PR'd things for typo-ish ones, but a bunch are fwlink or other permalinks that I'm not sure how you fix
- False positives for stuff that requires login, like `my.visualstudio.com`. It can hand auth headers, but I didn't do that
- Some of the office fwlinks resolve to the docs homepage, but are still flagged since it doesn't resolve to an actual page

Keep up the great work ❤️ ❤️ ❤️

**Comment by gewarren** [comment]
@nschonni Thank you for reporting all of these! It will take us a while to get through them but this is a great help.

**Comment by nschonni** [comment]
@gewarren no problem, I'm trying to get this functionality built into Markdownlint in the long term so it's just another check for the tech writers before they publish.
I know a flood of issues can be annoying 😉

**Comment by gewarren** [comment]
Given that this is pretty out-of-date now (we've since fixed a bunch of broken links found using our internal "CATS" tool) and that it has some false positives, I'm going to close the issue. Thanks for providing us with the list.
