### ISSUE TITLE
Documentation needs to state clearly if editor config styles can be enforced during build or not

### ISSUE THREAD

**Issue by sinapis** [MicrosoftDocs/visualstudio-docs#1037]
Many people are using CI/CD pipelines and need to know if they can rely on .editorconfig for enforcement  during build or not. Enforcement only using VS IDE is not enough - since anyone can use some other editor and bypass the style guidelines.

AFAIU this is still a work in progress: https://github.com/dotnet/roslyn/projects/18

**Comment by gewarren** [comment]
@sinapis Thanks for pointing this out. I'll find out and then clarify in https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#language-conventions.

**Comment by gewarren** [comment]
@sinapis You're correct that there is currently no support for .EditorConfig enforcement in CI/CD builds. There are plans to add this functionality in a future release. I'll make sure the documentation states this limitation.
