### ISSUE TITLE
.editorconfig settings web page does not include new "prefer readonly" setting.

### ISSUE THREAD

**Issue by Gav-Brown** [MicrosoftDocs/visualstudio-docs#1041]
In a recent Visual Studio update, a new "Field preferences" section was added to the C# Code Style options dialog. This included the new "**prefer readonly**" setting. This isn't yet described in the [.NET Coding Convention Settings](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference) web page.

Can this be added so we can update our .editorconfig files with the correct setting name.

**Comment by nschonni** [comment]
Being done in #1039
