### ISSUE TITLE
Change the layout of "editorconfig-code-style-settings-reference" to make it easier to apply rules to an editorconfig

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/visualstudio-docs#1043]
While I was making changes to my .editorconfig based on "editorconfig-code-style-settings-reference", I found the layout where the default value and the available values were in two different locations caused me to be constantly scrolling back up the page as I applied each rule. I propose a layout change that would resolve this. Here we remove the table that that lists all the like-kind rules, and instead move it to under each individual rule. 

---------------

# Before

| Rule name | Rule ID | Applicable languages | Visual Studio default | Visual Studio 2017 version |
| --------- | ------- | -------------------- | ----------------------| ----------------  |
| dotnet_style_require_ accessibility_modifiers | IDE0040 | C# and Visual Basic | for_non_interface_members:none | 15.5 |
| csharp_preferred_modifier_order | IDE0036 | C# | public, private, protected, internal, static, extern, new, virtual, abstract, sealed, override, readonly, unsafe, volatile, async:none | 15.5 |
| visual_basic_preferred_modifier_order | IDE0036 | Visual Basic | Partial, Default, Private, Protected, Public, Friend, NotOverridable, Overridable, MustOverride, Overloads, Overrides, MustInherit, NotInheritable, Static, Shared, Shadows, ReadOnly, WriteOnly, Dim, Const,WithEvents, Widening, Narrowing, Custom, Async:none | 15.5 |

**dotnet\_style\_require\_accessibility_modifiers**

This rule does not accept a **true** or **false** value; instead it accepts a value from the following table:

| Value | Description |
| ----- |:----------- |
| always | Prefer accessibility modifiers to be specified |
| for\_non\_interface_members | Prefer accessibility modifiers to be declared except for public interface members. This will currently not differ from **always** and will act as future proofing for if C# adds default interface methods. |
| never | Do not prefer accessibility modifiers to be specified |

---------------

# After

**dotnet\_style\_require\_accessibility_modifiers**

| Rule ID | Applicable languages | Minimum Visual Studio version | Default | 
| -------: | -------------------- | ----------------------| ---------------- |
| IDE0040 | C# and Visual Basic | 15.5 | for_non_interface_members:none | 

| Value | Description |
| ----- |:----------- |
| always | Prefer accessibility modifiers to be specified |
| for\_non\_interface_members | Prefer accessibility modifiers to be declared except for public interface members. This will currently not differ from **always** and will act as future proofing for if C# adds default interface methods. |
| never | Do not prefer accessibility modifiers to be specified |

**Comment by davkean** [comment]
I think that the table would actually look better like:

![image](https://user-images.githubusercontent.com/1103906/40591513-fff5e2bc-6255-11e8-92bb-d1403cf8f372.png)

But cannot figure out how to do this in markdown.

Tag @kuhlenh.

**Comment by gewarren** [comment]
@davkean Thanks, that's a good suggestion. Unless @kuhlenh is opposed to it, we can change it.

I don't think that you can do "row header" tables in Markdown, but it's possible we could do it in html...

**Comment by davkean** [comment]
Yeah @kuhlenh is out right now, so I'll wait for her opinion before we do it.

How do you do it in HTML? Is there a way indicate that a section is HTML?

**Comment by gewarren** [comment]
I'm not sure how to create a table like that in html, but I believe you just insert the html directly into the markdown. We sometimes use html for line breaks and heading anchors in the markdown files.

**Comment by davkean** [comment]
Okay that's good to know.

**Comment by gewarren** [comment]
@davkean We can probably format the table in markdown like this:

```
|||
|-|-|
|**Rule ID**|IDE0040|
|**Applicable Languages**|C# and Visual Basic|
|**Minimum Visual Studio version**|15.5|
|**Default**|for_non_interface_members:none|
```

**Comment by Logerfo** [comment]
I think there should be an option for `dotnet_style_require_accessibility_modifiers` to skip the diagnostic for partial classes. In which repo should I fill this request?

**Comment by gewarren** [comment]
@Logerfo I believe that should go in the dotnet/roslyn repo - https://github.com/dotnet/roslyn/issues.

**Comment by Logerfo** [comment]
Thanks, @gewarren. Out of curiosity for anyone stepping in this issue, I found that https://github.com/dotnet/roslyn/issues/27837 was already open.
