### ISSUE TITLE
Need more examples / best practices.

### ISSUE THREAD

**Issue by henrygab** [MicrosoftDocs/visualstudio-docs#1048]
Here are two example structures that are common complex structures in legacy C.

A) a variable-count final array element

```C
    typedef struct {
        USHORT FirstField; /* This header length */
        // … additional fields …
        UINT32  AdditionalDataLength; /* bytes of additional data immediately following */
    } SAMPLE_STRUCT_A;
    typedef struct {
        USHORT FirstField; /* This header length */
        // … additional fields …
        UINT32  AdditionalDataLength; /* bytes of additional data immediately following */
        BYTE Data[0];
    } SAMPLE_STRUCT_B;
```

B) a variable-length of data immediately follows the structure

```c
    typedef struct { … } SAMPLE_STRUCT_C; /* simple fixed-length struct */
    typedef struct {
        USHORT FirstField; /* This header length */
        // … additional fields …
        UINT32  ItemCount; /* bytes of additional data immediately following */
        SAMPLE_STRUCT_C Items[1]; /* legacy definition */
    } SAMPLE_STRUCT_D;
    typedef struct {
        USHORT FirstField; /* This header length */
        // … additional fields …
        UINT32  ItemCount; /* bytes of additional data immediately following */
        SAMPLE_STRUCT_C Items[0]; /* other version definition */
    } SAMPLE_STRUCT_E;
```

It'd be great to provide examples of how to properly annotate these types of structures, so that the analysis tools will have an understanding of the length of a valid structure of each type.

For example, for SAMPLE_STRUCT_D, example might show:

```C
    typedef _Struct_size_bytes_(FIELD_OFFSET(USBPCAP_BUFFER_ISOC_HEADER, Items) + (numberOfPackets * sizeof(USBPCAP_BUFFER_ISO_PACKET)))
    struct {
        USHORT FirstField; /* This header length */
        // … additional fields …
        UINT32  ItemCount; /* bytes of additional data immediately following */
        SAMPLE_STRUCT_C Items[1]; /* legacy definition */
    } SAMPLE_STRUCT_D;
```

With the explanation that the following annotation (which would check for zero packets) is not required, because the valid size is min(sizeof(STRUCT), annotation):

```C
    typedef _Struct_size_bytes_(FIELD_OFFSET(USBPCAP_BUFFER_ISOC_HEADER, Items) + ((numberOfPackets <= 1) ? 0 : (numberOfPackets * sizeof(USBPCAP_BUFFER_ISO_PACKET))))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba4f50a-d731-4bb2-e8ec-7d1caaca5659
* Version Independent ID: fb6232e4-5303-764c-ddac-686375ac2339
* Content: [Annotating Structs and Classes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-structs-and-classes)
* Content Source: [docs/code-quality/annotating-structs-and-classes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/annotating-structs-and-classes.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
invstigating

**Comment by henrygab** [comment]
Thanks @mikeblome .  For examples of these structures "in the wild", you likely need to look no further than the Windows DDK.  Hope that helps!
