### ISSUE TITLE
Whats the diff between the two places you can set this?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1051]
Asp.net Web Application (full framework) Project Properties -> Web  tab

Tools -> Options -> Debugging -> General

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9c2f239-d577-fe61-fed2-4fff6d77a877
* Version Independent ID: c1f1d143-13e2-c58e-04b6-a1e0b822add4
* Content: [Edit and Continue (Visual C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/edit-and-continue-visual-csharp)
* Content Source: [docs/debugger/edit-and-continue-visual-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/edit-and-continue-visual-csharp.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@StingyJack Hi Stingy, Tools -> Options sets properties for all relevant projects. The project properties only apply to the project where you change the setting.

**Comment by StingyJack** [comment]
The project setting is the priority?

(sorry if this seems tedious, but 15.7 broke debugging and turning this option off fixes it. i need to give proper and complete workaround instructions to teammates)

**Comment by Mikejo5000** [comment]
@andysterland Andy, can you confirm that the project setting would always override a setting in Tools > Options?

**Comment by Mikejo5000** [comment]
@StingyJack Sorry for taking a long while to get back to you. I absolutely would expect the project setting to override the general setting. Let me know if you find any different. Thanks!
