### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by SriharshaHack** [MicrosoftDocs/visualstudio-docs#1052]
"Defend your code with top ten security tips every developer must know" is broken in "Understand security".  Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b6663c0-8464-1363-9038-94df9f62b6f6
* Version Independent ID: 707fc083-a0b5-0f61-f6fe-e88bf1f0aee7
* Content: [Security in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/security-in-visual-studio)
* Content Source: [docs/ide/security-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/security-in-visual-studio.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@SriharshaHack Thanks for reporting this broken link. I'll fix it.

**Comment by gewarren** [comment]
I think this link has been removed as of June 1.
