### ISSUE TITLE
To create and deploy functions

### ISSUE THREAD

**Issue by paulceli** [MicrosoftDocs/visualstudio-docs#1054]
Hey,
Nice introduction. Could you explain how to deploy to Azure?
We have this convenient 1 click "Publish" button that spoils us on Web Apps. And I can't find an easy way to deploy a function from VS on the Mac.

thanks, bye

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4caaf0cc-3cea-375a-1160-6540db5557f1
* Version Independent ID: cfd2fe36-1325-9ff0-bc18-af563bb920e4
* Content: [Introduction to Azure Functions - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions)
* Content Source: [mac/azure-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/azure-functions.md)
* Service: **unspecified**
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by paulceli** [comment]
Hey, thanks Amy.
I created a fresh new "Azure Functions" project, but when I try to deploy, always get the msg "Error deploying app instance".
It manage to create an "App service plan" and a dedicated "Storage account" to my azure though.
Any idea what could go wrong? where I could see more log ?
bye

**Comment by asb3993** [comment]
@paulceli Once you managed to manually create the app and deploy to it, did it work as expected for you?

**Comment by paulceli** [comment]
Not on first try.  
Like I said, I had to accept to change to beta version in a Visual Studio Pop-up.
Then project deployed but it wasn't working at first.
I also had to change the app setting FUNCTIONS_EXTENSION_VERSION value from "~1" to "beta" as mentioned here : [https://stackoverflow.com/questions/48952452/azure-function-implemented-locally-wont-work-in-the-cloud](https://stackoverflow.com/questions/48952452/azure-function-implemented-locally-wont-work-in-the-cloud)
Didn't have time to test a lot but the default "hello" function works.

**Comment by asb3993** [comment]
@paulceli Thanks for your feedback, I really appreciate it. That definitely sounds like a bit of an obtuse workflow so I'll make sure to add this information to the guide. I've also spoken to the engineering team, particularly about the app setting issue and have been assured that they're fixing it.

**Comment by sm1th** [comment]
Wow... Spent a whole day looking for why I can't publish functions from Mac, and then I finally see this little comment thread. Hope publishing makes it to public soon.

**Comment by asb3993** [comment]
@sm1th The functionality is still in preview, which you can access through the Alpha or Beta channel. Feel free to try it out and provide feedback on [developer community](https://developercommunity.visualstudio.com/spaces/41/index.html).

**Comment by sm1th** [comment]
@asb3993 I've done that, thanks.

**Comment by asb3993** [comment]
The docs have been updated for the VSMac 7.6 release. There are a couple of outstanding issues that will be fixed in an upcoming service release, but I've documented the workarounds for those.
