### ISSUE TITLE
Full List of Primary Interop Assemblies Does Not include Office 2016?

### ISSUE THREAD

**Issue by FBoyne** [MicrosoftDocs/visualstudio-docs#1056]
I may have my numbers mixed up but if Office 15.0 is Office 2013 then Office 2016 PIAs are missing from the list.  Even if PIAs don't exist in Office 2016 for some reason (seems unlikely) that should be explicitly called out so the reader knows where they stand wrt Office 2016.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88fddd73-1fac-2149-71db-5f20c8c94934
* Version Independent ID: 46e037ee-a5fd-7274-b072-8df92ce70eda
* Content: [Office Primary Interop Assemblies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/office-primary-interop-assemblies#pialist)
* Content Source: [docs/vsto/office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/office-primary-interop-assemblies.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@FBoyne Thanks for your feedback. I do believe you are correct in your assessment. This task is on our backlog and we will attend to it when time permits.

**Comment by FBoyne** [comment]
@TerryGLee  Thanks but sadly I'm half right at best.  The "seems unlikely" comment is probably wrong because .NET 4 introduced the ["No PIA" feature](http://blogs.microsoft.co.il/sasha/2013/12/28/back-basics-com-interop-pia/) which I think eliminated the need to ship PIAs.  

Assuming I'm more right now, it would still be good if the PIA documentation explained that PIAs were no longer needed and so were no longer shipped (if in fact they are no longer shipped).  

Sorry, I should have thought this all through more carefully.  I got fixated on finding a certain version of a PIA.

**Comment by TerryGLee** [comment]
@FBoyne Thanks for the update. We'll verify and then update the docs. But please be advised that this is in our backlog queue, so it won't happen right away.

**Comment by FBoyne** [comment]
No problem.  I'm in the software business myself o I totally understand.  😊  I just didn't want to leave you with the mistaken idea that a 2016 PIA definitely existed.

**Comment by John-Hart** [comment]
this was fixed with PR #4107

#please-close
