### ISSUE TITLE
error in the 3rd screenshot

### ISSUE THREAD

**Issue by Lamphi90** [MicrosoftDocs/visualstudio-docs#1057]
It should be #include ../ but the screenshot shows three dots .../ -> can be misleading. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18bdf17-06e1-aaf2-b6ce-c606c0e260da
* Version Independent ID: bd627b8f-54f0-84e0-55cd-285597af022d
* Content: [Write unit tests for C/C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp)
* Content Source: [docs/test/writing-unit-tests-for-c-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/writing-unit-tests-for-c-cpp.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@Lamphi90 Thanks for catching this! I have fixed the image and it should be visible tomorrow May 31.

**Comment by gewarren** [comment]
Verified the change.
