### ISSUE TITLE
VB code in C# example

### ISSUE THREAD

**Issue by digitus0** [MicrosoftDocs/visualstudio-docs#1058]
The code that it's asking you to create is VB and not C# so the entire documentation falls apart at that stage....

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a448aa-4d5d-f827-6511-6c4ac9528122
* Version Independent ID: 5a8e5560-40c3-3787-ae3c-ce84ed28cc79
* Content: [Walkthrough: Create a simple application with C# or Visual Basic - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/walkthrough-create-a-simple-application-with-visual-csharp-or-visual-basic)
* Content Source: [docs/ide/walkthrough-create-a-simple-application-with-visual-csharp-or-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-create-a-simple-application-with-visual-csharp-or-visual-basic.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gewarren** [comment]
@digitus0 Thank you for the feedback. There is a language drop-down at the top right of the page where you can select your code example language. Based on your feedback and others', it seems like this language selector is not obvious enough, so I'm going to see if we can do something to improve its discoverability.

@TerryGLee on a side note, we may want to revise this line slightly to say "Visual Basic or Visual C#":

Choose the Visual Basic or the Visual C# WPF App template by choosing in the left pane Installed > **Visual C#** > Windows Classic Desktop, [...]
