### ISSUE TITLE
Typo - wrong class name

### ISSUE THREAD

**Issue by Stanley-G** [MicrosoftDocs/visualstudio-docs#1060]
Refactor the code under test

"First, define two constants for the error messages at class scope. Put these in the class under test (Bank):"

This should be BankAccount

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* Content: [Create and run unit tests for managed code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Stanley-G Thank you for pointing this out. I'm fixing it today.
