### ISSUE TITLE
Cannot create the workspace. Please, try again.

### ISSUE THREAD

**Issue by fchau-ralis** [MicrosoftDocs/visualstudio-docs#1061]
Hi,

I'm able to connect to my VSTS team solution and see all the directories that lie within it. However, when I follow the steps for creating a workspace, I keep getting the error: Cannot create the workspace. Please, try again.

Can anyone help? My steps were:
1. Click on 'Manage Workspaces' button.
2. Click on 'Add'\
3. When the window pops up, I add a working folder and map the remote directory with my local directory and check 'Local Workspace' checkbox.
4. When I hit 'Ok', the error: "Cannot create the workspace. Please, try again." pops up. 

I'm unsure why this is happening. Can anyone help guide me in the right direction?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [TF Version Control - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control#creating-a-new-workspace)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Service: **unspecified**
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by gewarren** [comment]
This could be related to the issues noted in #1017 and #981. @asb3993 what do you think?

**Comment by asb3993** [comment]
Hi @fchau-ralis thanks for trying out the preview! This can happen for several reasons. For example, invalid characters in the name, use of more than 64 characters in the name, the local path is used by another workspace, etc.

We're working to improve the error messages and logging for the next release of this preview, in the meantime, if you've double-checked the ideas above and are still unsuccessfully I would recommend filing an issue in [Developer Community](https://developercommunity.visualstudio.com/spaces/41/index.html) with information on exactly what you are entering.
