### ISSUE TITLE
Menu directions are incorrect (Mac vs. Windows)

### ISSUE THREAD

**Issue by hkdeven** [MicrosoftDocs/visualstudio-docs#1063]
I'm setting up VS for the first time and perusing the docs.  There are a lot of references to navigate from Tools  to sub menu option 'Options' which doesn't exist for Mac users.  I believe this should simply be updated to 'Add Custom Tool' which does exist under the Tool menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00e3e8d0-48c3-3df6-8aeb-acd9624ffcd5
* Version Independent ID: 13f5da30-9f06-236f-4110-b6a172c52d1f
* Content: [How to: Manage Word Wrap in the Editor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor)
* Content Source: [docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@hkdeven Thank you for the feedback. I will try to come up with a strategy for making it more clear which docs apply to VS for Windows and which are for VS for Mac.
