### ISSUE TITLE
password part followed by sudo command does not function properly

### ISSUE THREAD

**Issue by WayneXYZ** [MicrosoftDocs/visualstudio-docs#1065]
By the title I mean that whenever I paste lines with sudo, terminal asks for the Password, but as I type the first one or two letters it quickly enters the next line and says password incorrect. Thus all the sections with sudo lines cannot work on my Macbook.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Uninstalling Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall.md)
* Service: **unspecified**
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by asb3993** [comment]
Sorry to hear that you had issues with this @WayneXYZ.

This sounds like an issue with terminal. Have you tried quitting the terminal window (Cmd + Q) and opening it and trying again? Also, if you're using a trackpad make sure that nothing is touching it as you type. I've found that that can cause this type of unexpected behavior .
