### ISSUE TITLE
Where is the C# Code? 

### ISSUE THREAD

**Issue by abyteman** [MicrosoftDocs/visualstudio-docs#1066]
Why would you place vb code when you started showing C# code?
Just another waste of time.  The object is to learn not just waste time building 
forms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e2e854-d2d8-8ec2-ae41-beee6636fae3
* Version Independent ID: 2c1c8dae-ea87-e7a0-f0eb-7bc0b775f8d5
* Content: [Create a simple data application by using ADO.NET in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-by-using-adonet#create-the-forms-and-add-controls)
* Content Source: [docs/data-tools/create-a-simple-data-application-by-using-adonet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-simple-data-application-by-using-adonet.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@abyteman there is a language drop-down at the top right of the page, and you can choose between VB and C# code examples.

**Comment by gewarren** [comment]
If this doesn't solve the problem or you still aren't seeing the C# code, please let me know and I'll reopen this issue.

**Comment by preaytech** [comment]
There is not language drop down just C# top left and a Copy to clipboard at the top right? Can you help remedy this please.

**Comment by preaytech** [comment]
scratch that its at the top of the page rather than each code section, my apologies
