### ISSUE TITLE
Missing show group in ribbon

### ISSUE THREAD

**Issue by MrFojo** [MicrosoftDocs/visualstudio-docs#1068]
I followed this walkthrough but I could not find the show group in the ribbon or the map it button in Outlook 2016
I also checked out the video and it uses Outlook 2010. Seems the walkthrough is outdated.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55a77e0b-bbca-7721-d088-ba944ca76cc3
* Version Independent ID: 7b99953c-952d-affa-b97e-f51387b72c0a
* Content: [Walkthrough: Designing an Outlook Form Region - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-designing-an-outlook-form-region)
* Content Source: [docs/vsto/walkthrough-designing-an-outlook-form-region.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-designing-an-outlook-form-region.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@MrFojo Thanks for your feedback. We are aware that this documentation is due for an update; it's on our backlog to do so.

**Comment by MrFojo** [comment]
@TerryGLee Is there an alternative walkthrough I can use that is recommended for the meantime?

**Comment by TerryGLee** [comment]
@MrFojo You might consider searching [StackOverflow](https://stackoverflow.com/questions/tagged/outlook-2016) to see if they've got an answers to any specific Outlook 2016-related questions that you might have.

**Comment by MrFojo** [comment]
Ok. I will definitely try that

**Comment by ucheNkadiCode** [comment]
Tutorial fully works in office 365. Updated document for clarity.

#please-close

**Comment by ucheNkadiCode** [comment]
#please-close

**Comment by ucheNkadiCode** [comment]
#sign-off
