### ISSUE TITLE
"nse" (no side effect) format specifier is missing

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#1069]
I've just learned from a video of a Microsoft Build 2018 talk that there is a "nse" format specifier that prevents side effects from debugger evaluations. Seems like that specifier is missing in the documentation.

References:
- Video of the talk where it is shown: https://youtu.be/yAZLibpil_c?t=11m30s
- Written documentation: https://github.com/Microsoft/vs-diagnostics-demo-recipe-app/blob/master/tips/NoSideEffects.md

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ab3309-0c6a-5150-64d8-0339a03f3238
* Version Independent ID: e29ede27-d73c-7294-cdcc-c1227353bbb9
* Content: [Format specifiers in the debugger (C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-csharp)
* Content Source: [docs/debugger/format-specifiers-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/format-specifiers-in-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@cremor Thanks! I'll look into this.

**Comment by Mikejo5000** [comment]
Adding "nse" to this doc
