### ISSUE TITLE
Debugger tutorials - needed a how-to on understanding unexpected exceptions

### ISSUE THREAD

**Issue by pavel-a** [MicrosoftDocs/visualstudio-docs#1071]
In the debugger tutorials or Quick starts, please add a tutorial for debugging from "Exception thrown at ...". This is a frequent question from beginners.  
See [this thread](https://social.msdn.microsoft.com/Forums/en-US/c35f4389-b084-4361-ba04-f8c451582a69/kernelbasedll-access-is-denied?forum=visualstudiogeneral#060fbe44-ea69-4a5a-88ad-f35198c5e600) for example.

Existing tutorials (Call stack, JIT) do not exactly describe this situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b22d4492-032d-0c5b-807a-9a04d124a86d
* Version Independent ID: 78ccc822-c680-71b9-12d2-2d9d8e13a44d
* Content: [Debugger overview - Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-overview)
* Content Source: [docs/debugger/debugger-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debugger-overview.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@pavel-a Thanks for the suggestion. I'll take a look at the thread.

**Comment by Mikejo5000** [comment]
This is a really good idea, but the additional docs to debug specific errors are currently out of scope.
