### ISSUE TITLE
Several items seem to be incorrect/outdated

### ISSUE THREAD

**Issue by wilFab** [MicrosoftDocs/visualstudio-docs#1072]
*Adding a "custom command item" to the project required VS be launched with administrator privileges (this wasn't mentioned), otherwise a "No resource file set the resource merger." error occurs.
*VSPackage.resx needs to have the namespace (FileFilter) prepended to its name (e.g. FileFilter.VSPackage.resx), otherwise the .resources file generated by Resgen.exe won't contain the namespace.
*FileFilterPackageGuids.cs wasn't created in the project (it was called FileFilterPackage.cs).
*FileFilterPackage doesn't need to define FileFilterId, as FileFilter already has that value (CommandID), or guidFileFilterPackageCmdSetString, as FileFilter already has that value too.  FileFilter should define CommandSetString and use it when defining CommandSet.  [SolutionTreeFilterProvider()] in FileNameFilter should use those values in FileFilter instead.
*There is no ShowMessageBox() method in FileFilter.cs.  Should the ShowMessageBox method call be referenced instead?  Better still, should the MenuItemCallback() method be removed instead?
*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 435b58a5-49f7-b1eb-05b1-8f1d7598343a
* Version Independent ID: 2eb8a331-8aab-ca9f-fc0b-c594a75e934b
* Content: [Extending the Solution Explorer Filter - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-solution-explorer-filter)
* Content Source: [docs/extensibility/extending-the-solution-explorer-filter.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extending-the-solution-explorer-filter.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
