### ISSUE TITLE
Incorrect URL shown for Step 1 under "Add the Alternate Account"

### ISSUE THREAD

**Issue by snowstormlife** [MicrosoftDocs/visualstudio-docs#1074]
Step 1 under "Add the Alternate Account" uses the wrong link. "Sign in to Visual Studio with your Microsoft account (https://{youraccount}.visualstudio.com)." 

Signing in with {youraccount}.visualstudio.com logs into a VSTS account, not a person's Visual Studio account. 

For people to be able to add an alternate account to their Visual Studio subscription, Step 1 should read "Sign in to your Visual Studio account using your Microsoft account (https://my.visualstudio.com)." (Or something to that effect.) 

At that point they can go into Subscriptions and add an alternate account. 

Step 5 has the correct URL to sign into a VSTS account, but the instruction should be worded differently. Current wording: "Use your work or school account to sign in to Visual Studio (https://{youraccount}.visualstudio.com)." More accurate wording: "Use your work or school account to sign in to Visual Studio Team Services (https://{youraccount}.visualstudio.com)."

-- Blizz 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e967e1-0b8e-a6b5-13ef-bd206ca6d13a
* Version Independent ID: 612623f5-6252-6353-8c7c-c1be43bd8801
* Content: [Identities for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-alternate-identity?toc=%2Fvsts%2Faccounts%2Ftoc.json&bc=%2Fvsts%2Faccounts%2Fbreadcrumb%2Ftoc.json&view=vsts)
* Content Source: [subscriptions/vs-alternate-identity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-alternate-identity.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@evanwindom could you please take a look at this?
@prrana FYI

**Comment by evanwindom** [comment]
snowstormlife is correct.  I agree with the proposed changes.

**Comment by evanwindom** [comment]
#sign-off

**Comment by TerryGLee** [comment]
@evanwindom Please sign off on the actual PR, which is here: [https://github.com/MicrosoftDocs/visualstudio-docs/pull/1075](https://github.com/MicrosoftDocs/visualstudio-docs/pull/1075) 

Thanks!
~ Terry
