### ISSUE TITLE
Unclear description of Modify Visual Studio in case of pending updates

### ISSUE THREAD

**Issue by pmisik** [MicrosoftDocs/visualstudio-docs#1078]
Hi, 

We are situation we cannot upgrade to latest update due to already reported bug in c++ codegen.
I need to install new workload for UWP development that we didn't developed before.
What will happen if I choose Modify add new Workload and there are pending updates?
a) It will install pending updates and than new workload
b) It will install just selected workload without updating rest of Visual Studio.

I guess it will do a) - I've chosen modify without changing anything and installer reports Total Space required 155MB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d0cb94-2886-79ce-39dd-0336282369b9
* Version Independent ID: e8bcc58e-98af-e3ad-2629-0b4515047d0b
* Content: [Modify Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio)
* Content Source: [docs/install/modify-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/modify-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@pmisik Thanks for your feedback! We'll investigate and if necessary, we'll update the documentation. More, soon.

**Comment by TerryGLee** [comment]
@pmisik The answer is that it will install just the selected workload without updating. On the [Modify Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio) page, Step 2 tells you how to modify Visual studio if you have an update pending. But, we've added more information to Step 2 that makes it clear that you can modify Visual Studio without updating it, if that is your preference. We hope this helps you and others that might have the same inquiry.
