### ISSUE TITLE
Quickstart: Use Visual Studio to create your first ASP.NET Core web app

### ISSUE THREAD

**Issue by rkindred** [MicrosoftDocs/visualstudio-docs#1079]
At the url  https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core

This tutorial says to open the Pages folder, but the Pages folder does not exist in the solution explorer, at least not in Visual Studio 2017 Community edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Use Visual Studio to create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@rkindred Thanks for letting us know; I'll investigate and report back soon.

**Comment by TerryGLee** [comment]
@rkindred I've reviewed this topic and updated it with current screenshots. I can verify that the **Pages** folder does exist in Visual Studio Community 2017 version 15.7.5, which is what I used to update the topic. (It is also the most current version of Visual Studio as I write this, per the [Visual Studio 2017 build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates) page.)
