### ISSUE TITLE
MyTemplate.vstemplate versus ProjectName.vstemplate ?

### ISSUE THREAD

**Issue by kadorken** [MicrosoftDocs/visualstudio-docs#1083]
The first XML example shows a structure where the Project1\Project1.vstemplate file needs to exist. Yet when you export an existing project, the .vstemplate is called "MyTemplate.vstemplate" (not ProjectName.vstemplate).

The two project example shows the use of MyTemplate.vstemplate in the sample XML.

So which is it? (I suspect the latter)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e208-2a2a-9fc3-98ff-147540157f32
* Version Independent ID: 5f5c9adf-da1d-ec0b-8af3-ccd2e27eaadc
* Content: [Create multi-project templates for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates)
* Content Source: [docs/ide/how-to-create-multi-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-multi-project-templates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@kadorken Thanks, I'll take a look and clarify.
