### ISSUE TITLE
This document does not tell me how to delete a bad environment

### ISSUE THREAD

**Issue by CBrauer** [MicrosoftDocs/visualstudio-docs#1086]
I no longer use python 2.7.  I deleted it from Anaconda, but it still show up in Environments and I cannot delete it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563f476d-a91b-58c7-9e32-b238756cc97d
* Version Independent ID: 0a0e9cac-a8dc-47a1-14e1-1dacc3441613
* Content: [Manage Python environments and interpreters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio#moving-an-existing-interpreter)
* Content Source: [docs/python/managing-python-environments-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/managing-python-environments-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
When you say you deleted it from Anaconda, what does that mean, exactly? Did Anaconda uninstall that interpreter, or does it still exist on your computer? The reason I ask is that VS looks in the registry for installed interpreters, so if removing an interpreter from Anaconda changes a setting, but does not wholly remove the interpreter from the computer, then I imagine VS would still pick it up.

**Comment by CBrauer** [comment]
Here is what is on my machine now:

 

Microsoft Windows [Version 10.0.17134.81]

(c) 2018 Microsoft Corporation. All rights reserved.

 

H:\ML\BlogExperiments\Python\SKLearn>conda list | findstr python

ipython                   6.4.0                    py36_0    conda-forge

ipython_genutils          0.2.0                    py36_0    conda-forge

msgpack-python            0.5.6            py36he980bc4_2    conda-forge

python                    3.6.5                         1    conda-forge

python-crfsuite           0.9.2               py36_vc14_0  [vc14]  conda-forge

python-dateutil           2.7.3                      py_0    conda-forge

python-utils              2.3.0                    py36_0    conda-forge

rgf-python                2.3.0                     <pip>

 

My Python Environments looks like:

 



 

Charles

**Comment by kraigb** [comment]
Hi, your image didn't come through. Can you send it straight to me via email at kraigb at microsoft dot com? And also, how did you remove the environment from Anaconda (what command)?

**Comment by kraigb** [comment]
Thanks for the email; I see now that those environments are marked with strikethrough, but still visible in the window. I'm investigating with the PTVS engineering team who should be able to advise. Stay tuned.

**Comment by kraigb** [comment]
OK, the environments shown with a strikethrough are those for which registry entries exist, but the paths specified in those entries do not exist, specifically the InstallPath\ExecutablePath value.

Check the registry entries under HKEY_LOCAL_MACHINE\SOFTWARE\Python (32-bit installs) and HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python (64-bit installs). In those nodes you should see nodes for the Anaconda 4 (under a node "ContinuumAnalytics") and Python 2.7 (under "PythonCore") installs. Their InstallPath\ExecutablePath entries likely point to non-existent folders.

Once you verify that those are the correct installations, you can delete their nodes in the registry and the entries should disappear from the Python Environments window (even with VS running). If the installations are still on your file system, but the paths are incorrect, you can update those paths in the registry and VS should show them without the strikethrough.

**Comment by kraigb** [comment]
Excellent. I'll add notes to this effect in the docs. Thanks for filing the issue and bringing it to my attention.
