### ISSUE TITLE
Why is the docker image size so gargantuan ?

### ISSUE THREAD

**Issue by jkhoogland** [MicrosoftDocs/visualstudio-docs#1087]
Thanks for providing this example build.
Could you explain why this build should take up ~ 50 GB ?
Any linux/gcc is doable in a couple of GB as most...
Thanks

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container - Visual Studio](https://docs.microsoft.com/nl-nl/visualstudio/install/build-tools-container)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
Because this has much more than just a C++ compiler. It contains compilers and toolsets for many workloads as documented in our linked workload documentation. This large size is why we haven't yet pushed an image to Docker Hub. Most people won't need everything in it, which is why we've published documentation about how to customize your own workload selection.

@TerryGLee, please feel free to close as this is a question. The original poster can reply, but there's no action item here.

**Comment by jkhoogland** [comment]
thanks for the clarification, 
the image whith just C++ toolchain is indeed smaller, but still quite massive at ~9GB.

Looking at the resulting images, the folder C:\BuildTools contains all the compiler versions,
but there seems to be a bunch of folders added to C:\Program Files (x68) as well (see below).

Are the folders `Microsoft SDKs`, `Microsoft Visual Studio`, `Microsoft.NET`, `MSBuild` still needed or remnants of the install process and can they be deleted (in order to reduce the size of the image) ?
 
Thanks
Jiri  

```
PS C:\> ls 'C:\Program Files (x86)\'


    Directory: C:\Program Files (x86)


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        9/29/2017  12:28 PM                common files
d-----        9/29/2017  12:28 PM                internet explorer
d-----         6/7/2018   2:19 PM                Microsoft SDKs
d-----         6/7/2018   2:16 PM                Microsoft Visual Studio
d-----        9/29/2017  12:28 PM                Microsoft.NET
d-----         6/7/2018   2:18 PM                MSBuild
d-----        9/29/2017   2:39 PM                Windows Defender
d-----         6/7/2018   2:18 PM                Windows Kits
d-----        9/29/2017  12:28 PM                WindowsPowerShell
```

**Comment by TerryGLee** [comment]
@heaths There is a follow-up question from @jkhoogland; FYI.

**Comment by heaths** [comment]
If there is content in them, the development teams who own those features have reasons to do so. Deleting them may cause issues and is not supported if you modify your image beyond going through setup. What is supported is that you can use `--add` and `--remove` through the setup command line interface to customize the image for your needs.

**Comment by TerryGLee** [comment]
Thanks, @heaths. I'll close this issue now, per your earlier request. :)

**Comment by dudi938** [comment]
re-exec error:
exit status 1: output: time="2018-10-17T17:16:40+03:00" level=error msg="hcsshim::ImportLayer failed in Win32:
 The system cannot find the path specified. (0x3) layerId=\\\\?\\C:\\ProgramData\\Docker\\windowsfilter\\d9c80f6bea48a36df56d1ae6ef3a0ac215437e35cc645e695f452c2870eac7cd flavour=1 folder=C:\\ProgramData\\Docker\\tmp\\hcs085605583"hcsshim::ImportLayer failed in Win32: 
 The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\d9c80f6bea48a36df56d1ae6ef3a0ac215437e35cc645e695f452c2870eac7cd flavour=1 folder=C:\ProgramData\Docker\tmp\hcs085605583

What Cat the reason of this error?
