### ISSUE TITLE
Missing docs for some Tools > Options options

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#1090]
@SetTrend commented on [Sun Jun 03 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/7)

This page is missing a bunch of options I see in Visual Studio 15.7 on the same Options page. Please add the corresponding documentation here. This is particularly important for translated versions of Visual Studio 2017 as the translation is often misleading and poor.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Optionen, Text-Editor, Allgemein](https://docs.microsoft.com/de-de/visualstudio/ide/reference/options-text-editor-general?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.General)%26rd%3Dtrue)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---

@CeciAc commented on [Mon Jun 04 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/7#issuecomment-394439207)

Hi @SetTrend 
Thank you for your feedback.

**Can you please specify which are these missing options you mention so we can investigate it?**

Kind regards,
Microsoft DOCS International Team

---

@SetTrend commented on [Tue Jun 05 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/7#issuecomment-394765421)

Sure, here they are:

![text-editor allgemein](https://user-images.githubusercontent.com/9283914/40988028-5ae8d0fe-68ea-11e8-9fd3-4002e0984c3f.png)

![text-editor alle sprache scrollleisten](https://user-images.githubusercontent.com/9283914/40988036-5e342790-68ea-11e8-9af8-1241958791b2.png)

![text-editor basic erweitert](https://user-images.githubusercontent.com/9283914/40988039-616c00ea-68ea-11e8-93f7-2b1b551acfaa.png)

**Comment by gewarren** [comment]
Currently, the only non-self explanatory item on the options page is "Show file health indicator".

https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?view=vs-2019

**Comment by SetTrend** [comment]
I'm not sure if this is the correct place to add additional missing documentation ... Should I open a new issue for this?

These panels don't lead to their documentation, explaining what these options are used for (screenshots show options in German):

![image](https://user-images.githubusercontent.com/9283914/56579337-3519d880-65d0-11e9-8b1c-fc7d896e9786.png)

![image](https://user-images.githubusercontent.com/9283914/56579496-9641ac00-65d0-11e9-87d9-79789c1bfc91.png)

(Visual Studio 2019 - v16.0.2)

**Comment by gewarren** [comment]
@SetTrend I think it's fine to add on to this issue. Thanks so much for providing all those screenshots!

**Comment by ssimontis** [comment]
@gewarren The Text Editor->Advanced screen is missing completely from the documentation. Pretty sure this is a fairly recent addition as I don't recall ever seeing these menu choices before.

**Comment by SetTrend** [comment]
Hi, I just installed the latest 16.5 edition of Visual Studio Enterprise.

Again, quite a number of `Tools > Options > ...` pages doesn't come with option help at all or is missing information for a number of tools.

Would you please establish a discussion at Microsoft to not publish options that don't have a corresponding thorough explanation at Microsoft Docs (i.e. not just the tooltip text) of what they are doing. It's appaling to work with a critical tool that's potentially out of control, doing things (potentially communicating with external severs without consent) I cannot evaluate.

**Comment by TerryGLee** [comment]
@SetTrend Thanks for your feedback; we are looking in to updating this page very soon.

**Comment by TerryGLee** [comment]
We're pursuing this issue via the following issue: https://github.com/MicrosoftDocs/visualstudio-docs/issues/5495
