### ISSUE TITLE
Das Tool ist nicht auffindbar

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#1091]
@manuth commented on [Wed Jun 06 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/9)

Ich habe, wie im Dokument "Installieren des Visual Studio SDKs" nachzulesen, die SDK installiert und kann das Tool, welches hier thematisiert wird über die Such-Funktion von Visual Studio 2017 nicht finden.
Im gesamten Dokument wird nirgends aufgezeigt, wie und wo sich das Tool finden lässt - habe ich irgendetwas überlesen?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a79c0a5f-2226-f484-31d4-2ea98abba400
* Version Independent ID: f9356223-144a-d1d7-0715-6dcc1b05a955
* Content: [Image Bibliotheksviewer](https://docs.microsoft.com/de-de/visualstudio/extensibility/internals/image-library-viewer)
* Content Source: [docs/extensibility/internals/image-library-viewer.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/extensibility/internals/image-library-viewer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

---

@CeciAc commented on [Wed Jun 06 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/9#issuecomment-395190248)

Hallo, @manuth

vielen Dank für Ihren Beitrag. Unser Team kann nur Feedback beantworten, das sich auf die Dokumentation bezieht. 
Übermitteln Sie Feedback zu Produkten über die Schaltfläche „Feedback zu Produkten“ ganz unten auf der Dokumentationsseite. 

Wenn Sie Feedback zur Dokumentation haben, können Sie dieses gerne hier übermitteln. 
Vielen Dank, dass Sie eine gute Qualität unserer Artikel gewährleisten.  

Mit freundlichen Grüßen 
das Microsoft DOCS International Team 

---

@manuth commented on [Wed Jun 06 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/9#issuecomment-395223608)

Sollte sich der Weg zum Öffnen des entsprechenden Tools nicht in dessen Dokumentation befinden?
In meinen Augen macht das mehr Sinn als ein Feedback zu Visual Studio 2017 abzugeben, denn die Dokumentation ist der Ort, an dem auch andere Leute die notwendigen Schritte finden können und auch suchen würden.

Danke für die prompte Antwort

**Comment by gregvanl** [comment]
Old issue, closing

**Comment by gregvanl** [comment]
C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin
