### ISSUE TITLE
BuildTools 15.0: "The attribute "TaskName" in element <UsingTask> is unrecognized." in a c# project file.

### ISSUE THREAD

**Issue by AraHaan** [MicrosoftDocs/visualstudio-docs#1092]
I am getting this error above when loading my Core.props (which contains my task to locate the latest version of rc.exe to compile a resource script) makes my c# project then not load whenever I import the Core.props file. My version of vs2017 is 15.5.6. I would update but currently only my iPhone has internet unless there is a offline updater for my vs2017 install that I can transfer using iTunes that contains only the updated components since my version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87459e0-a40b-d8ae-3f74-76e8f84ef6f8
* Version Independent ID: 57affef6-ead8-8c44-be7e-a9a3e9bda92b
* Content: [Walkthrough: Creating an Inline Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-inline-task)
* Content Source: [docs/msbuild/walkthrough-creating-an-inline-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-creating-an-inline-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by AraHaan** [comment]
Apperently it only works in the project file, but seems in visual studio to not write to the output window with Log.LogMessage or System.Console.WriteLine for some reason.

**Comment by Mikejo5000** [comment]
@AraHaan Are you still offline and can't update VS? I'm not sure if you can install offline via iTunes, but we have this offline installation topic: https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio

**Comment by AraHaan** [comment]
I am temporarily back online. However I do think I need to do a cache of all the components I got currently on my VS install in case it breaks for some unknown reason.

However not sure yet on the command currently for this layout:
![](https://i.alexflipnote.xyz/05788e.png)
![](https://i.alexflipnote.xyz/3284df.png)
![](https://i.alexflipnote.xyz/f565e4.png)
![](https://i.alexflipnote.xyz/47312f.png)
![](https://i.alexflipnote.xyz/c89d84.png)
![](https://i.alexflipnote.xyz/bb3198.png)

**Comment by AraHaan** [comment]
Alright so I got that part working and I decided to also test creating an layout with the vs2017 preview installer to see if I can layout that version too, but seems the layout option instead does not run anything after it does the progress bar stuff.

**Comment by Mikejo5000** [comment]
@TerryGLee Any suggestions, Terry? This appears to be more of an offline installation issue than an MSBuild issue.

**Comment by TerryGLee** [comment]
@AraHaan Is this still an issue? Apologies that this has lain fallow for some time, but let us know if this is still an issue and we'll see what we can do to help.

**Comment by AraHaan** [comment]
Yes, I had to move the tasks to the csproj file instead of having them in the props file. Unless I was supposed to put the tasks in a *.targets file?

**Comment by Mikejo5000** [comment]
That looks like an msbuild question. Arahaan was trying to update VS to help address the problem he was experiencing, I believe. @AraHaan, were you able to update VS?

**Comment by tydunkel** [comment]
>           Alright so I got that part working and I decided to also test creating an layout with the vs2017 preview installer to see if I can layout that version too, but seems the layout option instead does not run anything after it does the progress bar stuff.

@AraHaan I'm not sure I understand what issue you were hitting when creating the layout. Were you following the instructions at https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#use-the-command-line-to-create-a-local-cache? Once a layout is created you can install only new instances of VS from it. You do this by running the vs_<SKU>.exe that is copied into the layout directory.

**Comment by AraHaan** [comment]
Yes, but I wanted to use the preview bootstrappers which seems to ignore the option and not generate a offline layout like what the stable ones do.

**Comment by TerryGLee** [comment]
@tydunkel Are layouts supported in Preview?

**Comment by tydunkel** [comment]
@TerryGLee yes, Preview installers support layout mode. There could have been an issue with that specific preview installer, but in general layout mode should be supported. @AraHaan have you experienced any layout issues recently?

**Comment by AraHaan** [comment]
I will try it again when I get my latop on internet again. Currently viewing github on my iPhone 5s thought so. I will report back if it works now or not on the VS2019 Preview installer.

**Comment by TerryGLee** [comment]
@AraHaan We haven't heard back from you yet and so we're closing this GitHub Issue. We hope though that the issue you reported is now resolved; if it is not, please feel free to respond to this GitHub Issue with that information, or open a new GitHub Issue.
