### ISSUE TITLE
Specifying exact path for temporary opc file

### ISSUE THREAD

**Issue by aircatcher** [MicrosoftDocs/visualstudio-docs#1093]
Instead of deleting the temp file (%localappdata%\Temp\x.xxx\vs_installer.obc) after exiting the installer, what about allowing me to specify the custom path for it, so I don't have to re-download each time I want to relaunch my customized parameters in a batch file. I am trying to install for multiple computers, so I can save an extra 67 MB of bandwidth for each computer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@aircatcher Thanks for your feedback! It looks like you have a suggest to improve the product. This venue is meant to help improve the documentation, and so while we've noted your input, it would be best placed with us on our [UserVoice](https://visualstudio.uservoice.com/) page, where we collect product suggestions. (For more information about how and where to contact us, please see our [Talk to us](https://docs.microsoft.com/visualstudio/ide/talk-to-us) page.
