### ISSUE TITLE
How do you make a game

### ISSUE THREAD

**Issue by oooobi** [MicrosoftDocs/visualstudio-docs#1094]
Is there any tutorial on making a game

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1daec8-269e-40fd-0cc3-6c38f9074399
* Version Independent ID: e9b4d9e3-8692-339b-e1f3-ff417d1a09cd
* Content: [Develop apps for the Universal Windows Platform (UWP) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/develop-apps-for-the-universal-windows-platform-uwp)
* Content Source: [docs/cross-platform/develop-apps-for-the-universal-windows-platform-uwp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/develop-apps-for-the-universal-windows-platform-uwp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @stevehoag
* Microsoft Alias: **shoag**

**Comment by TerryGLee** [comment]
@oooobi Thanks for your inquiry. For more information about how to use UWP to create a game, please see the "Game development" section on the [Universal Windows Platform documentation](https://docs.microsoft.com/en-us/windows/uwp/index) page.

Cheers,
~ Terry

**Comment by 3121084329** [comment]
不懂

**Comment by TerryGLee** [comment]
@3121084329 谢谢你的反馈。请问, 你能提供更多的信息, 你不明白, 以便我们可以帮助？
(Thanks for your feedback. Please, can you provide more information about what you do not understand so that we can help?)
