### ISSUE TITLE
Awesome article.

### ISSUE THREAD

**Issue by nathan130200** [MicrosoftDocs/visualstudio-docs#1097]
Nice!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c165c6c-3afb-ec14-fc40-13c504aa2492
* Version Independent ID: eb03852b-8ccf-a6f7-b62d-a6912a97430d
* Content: [Code Snippets - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/snippets)
* Content Source: [mac/snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/snippets.md)
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by TerryGLee** [comment]
@nathan130200 We appreciate your positive feedback! We'll be sure that the author, @asb3993, sees this, too.

**Comment by asb3993** [comment]
Hi @nathan130200, thanks for your kind feedback. I really appreciate it!
