### ISSUE TITLE
Documentation Website - Long tables on portrait monitor awkward to scroll 

### ISSUE THREAD

**Issue by deltafsdevelopment** [MicrosoftDocs/visualstudio-docs#1098]
Hello 

My issue can be seen here: [https://docs.microsoft.com/en-gb/visualstudio/msbuild/msbuild-reserved-and-well-known-properties](https://docs.microsoft.com/en-gb/visualstudio/msbuild/msbuild-reserved-and-well-known-properties) but it is a general issue _with the documentation site_ which seems to have been designed with only landscape aspect ratios in mind:

* Monitor in portrait mode, browser Chrome
* Table content does not wrap to the table width
* Meaning I must scroll horizontally to view it 
* But the scroll bar is right at the bottom of the table

Suggestion:
* Allow the RH and LH menus and navigation to be able to be hidden away so the content can take up more width
* OR wrap the content in the table so I do not have to scroll right

![image](https://user-images.githubusercontent.com/16683437/41227388-79458d2c-6d6c-11e8-90eb-ad8e164e2c82.png)

Thanks

**Comment by gewarren** [comment]
@deltafsdevelopment Thanks for these great suggestions. I agree the experience is not optimal. I've let the design team know about your issue and two suggested improvements.

**Comment by TerryGLee** [comment]
@gewarren Thanks for forwarding this to the site design team for their consideration. I'll close this issue now, as it's being handled via another venue.
@deltafsdevelopment Thanks for your suggestions on how we can improve the documentation!

**Comment by deltafsdevelopment** [comment]
Hi I can confirm this is still an issue for me ... can you link to the "other venue" that is fixing this now? Thanks.

**Comment by TerryGLee** [comment]
@deltafsdevelopment Typically, issues related to overall site experience, or suggestions for improved site functionality or design, are recorded on [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
