### ISSUE TITLE
MD document renders incorrectly

### ISSUE THREAD

**Issue by ddv239** [MicrosoftDocs/visualstudio-docs#110]
This looks like a publishing/rendering bug in docs.microsoft.com.
This document https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box renders this way in all my browsers:
![md rendered](https://cloud.githubusercontent.com/assets/23296092/25823195/28f67ae0-33f0-11e7-9612-bfa1911b15bb.png)
Note that starting with one paragraph, all subsequent paragraphs are indented despite the sources on github apparently not having this formatting issue:
![md source](https://cloud.githubusercontent.com/assets/23296092/25823235/486240a8-33f0-11e7-8b90-5c0ccfd8acbe.png)

**Comment by Mikejo5000** [comment]
Fixed

**Comment by ddv239** [comment]
Mike,

Can you elaborate your reply: what and where was changed to fix this bug? The way you resolved it is not informative enough.

--- 

Dmitri Davydok (Дмитрий Давыдок)

**Comment by Mikejo5000** [comment]
Dmitry,

I updated the formatting during a content refresh a while back. Fixes involved mainly correcting the indents and spacing. The topic no longer appears as shown in your original comment. Please take a look at the topic and let me know if you still see formatting issues.

https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box

**Comment by ddv239** [comment]
OK, did you realize that this bug was not about this topic, but about the fact that somehow, the same markdown was rendered differently between Github and docs.microsoft.com?

Because this issue is not addressed, I am going to reactivate it.

---
Dmitri Davydok (Дмитрий Давыдок)

**Comment by ddv239** [comment]
Do I have access to reactivate this issue?

**Comment by Mikejo5000** [comment]
OK, gotcha--but whatever the rendering issue was (or is), I don't see it now when I compare the GitHub page and the docs.microsoft.com page. It might have been fixed by our build team as other bug fix work. It looks like No Repro and the page appears as expected (by design). If you still see an issue, I'd be happy to re-open it for you.
