### ISSUE TITLE
Incorrect file name mentioned in section "Set and hit a breakpoint in the client-side React code"

### ISSUE THREAD

**Issue by arpitadessai** [MicrosoftDocs/visualstudio-docs#1100]
Section: Set and hit a breakpoint in the client-side React code
Point number: 3
Line: "Switch to Visual Studio and set a breakpoint in app-bundle.js code in"
Fix required: The file name is actually "app.tsx" instead of "app-bundle.js".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b3b809-00c3-5637-ab09-0180827ffe4c
* Version Independent ID: 2e5782ba-8234-95d5-cc22-1a68c3b4ae34
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/nodejs/tutorial-nodejs-with-react-and-jsx#set-and-hit-a-breakpoint-in-the-client-side-react-code)
* Content Source: [docs/nodejs/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/nodejs/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@arpitadessai Thanks for the feedback! I'll take a look at it.

**Comment by Mikejo5000** [comment]
This is by design. Step 8 has more info about setting and hitting breakpoints in app.tsx
