### ISSUE TITLE
Cannot uninstall .NET Core+ASP.NET Core workload - VS MAC

### ISSUE THREAD

**Issue by phinneydad** [MicrosoftDocs/visualstudio-docs#1101]
On VS for Mac I ran uninstall scripts and everything was removed except for .NET Core + ASP.NET Core component.  Is there a separate script to uninstall this part?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Uninstalling Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall.md)
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by mrward** [comment]
There is an uninstall script provided for .NET Core available from the dotnet cli repository on GitHub:

https://github.com/dotnet/cli/blob/master/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh

You will probably need to give this script execute permissions using `chmod +x` to be able to run it. It also needs to be run as `sudo`.

**Comment by aleroot** [comment]
The execution of the dotnet-uninstall-pkgs.sh should be added at the end of the visual studio uninstall script : https://raw.githubusercontent.com/MicrosoftDocs/visualstudio-docs/master/mac/resources/uninstall-vsmac.sh  .

Maybe a question about removing the the .net core, and if the user answer yes then proceeding with the removal
