### ISSUE TITLE
I cannot find TFS extension in Visual Studio Community

### ISSUE THREAD

**Issue by kuzun9x** [MicrosoftDocs/visualstudio-docs#1102]
Is TFS extension available in Visual Studio Community latest version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [TF Version Control - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by asb3993** [comment]
Hi @kuzun9x, The TFS extension is available in all versions of Visual Studio for Mac. You'll have to install the extension through the extensions gallery via **Visual Studio > Extensions...**  as described here: https://docs.microsoft.com/visualstudio/mac/tf-version-control#installation

**Comment by kuzun9x** [comment]
Yup, I have seen and installed this plugin.
Some day ago, i cannot find it in market.

Thanks,

**Comment by jsuarezruiz** [comment]
Hi @kuzun9x,

I'm not sure what it can be. I can see the addin with VS Community. Can you try to refresh the repositories, restart Visual Studio and try again?

![imagen](https://user-images.githubusercontent.com/6755973/41556897-4befde92-733c-11e8-8ff2-9d9a08c7e96e.png)

Regards.

**Comment by Wowotoe** [comment]
The installation is fine. But after I downloaded the projects from TFVC, I'll get Load Failed: File Not Found error when trying to open the solution. The path in the error is the correct path.

**Comment by asb3993** [comment]
@Wowotoe This area is just for issues with the documentation. This sounds like a bug in the product, so I'd recommend creating an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/41/index.html)
