### ISSUE TITLE
Dead links on license terms

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#1104]
The following links don't resolve in the license terms for VS
https://www.microsoft.com/info/nareturns.htm
http://go.microsoft.com/fwlink/?Linkid=104610
http://go.microsoft.com/fwlink/?Linkid=104611
https://www.microsoft.com/licensing/userights
http://aka.ms/georestrict
http://microsoft.com/products/ceip/EN-US/privacypolicy.mspx
http://o15.officeredir.microsoft.com/r/rlidIRMHelp?clid=1033

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2c630f-bb11-e092-d5c1-263ba42fb18e
* Version Independent ID: 80e2c72a-f2b1-2901-5606-c3bf164bc256
* Content: [Visual Studio subscriptions license terms](https://docs.microsoft.com/en-ca/visualstudio/subscriptions/vs-license-terms)
* Content Source: [subscriptions/vs-license-terms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-license-terms.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@evanwindom @prrana If this doc is deprecated, we might consider removing it from the repo altogether...

**Comment by TerryGLee** [comment]
FYI: We've removed the file that had the dead links and redirected to a more current version of the licensing information.

**Comment by nschonni** [comment]
That one looks specific to Volume Licensing stuff, although the Visual Studio License whitepaper http://aka.ms/vslicensing points to http://www.microsoftvolumelicensing.com/userights/PUR.aspx (also dead) and http://www.microsoft.com/useterms/

The aka.ms link to the whitepaper PDF might be a more general link

**Comment by TerryGLee** [comment]
@evanwindom @prrana Can you verify if we need to make a change in our redirect strategy for license terms?

**Comment by TerryGLee** [comment]
@nschonni Thanks for your additional suggestions, but after some discussion, we're happy with the linking strategy that we've chosen with regard to license terms.
