### ISSUE TITLE
Needs update

### ISSUE THREAD

**Issue by iant-ee** [MicrosoftDocs/visualstudio-docs#1117]
This is written for Windows 8 and an old version of Visual Studio.
In my Windows 10 start menu I don't have an all programs option, but I do have Developer Command Prompt for VS 2017 and MSBuild Command Prompt for VS2015

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41d57f6-25bf-bc84-7ba8-4cb4ecedac05
* Version Independent ID: 69c3bd43-6c2b-834b-18d2-0555a79961a7
* Content: [Walkthrough: Using MSBuild - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/msbuild/walkthrough-using-msbuild)
* Content Source: [docs/msbuild/walkthrough-using-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-using-msbuild.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I'll take a look at it.
