### ISSUE TITLE
Windows Forms - VB & C# - THE Solution

### ISSUE THREAD

**Issue by DavidSwiss** [MicrosoftDocs/visualstudio-docs#1120]
The installer normally installs UWP.  To get Windows Forms, you must choose .Net Desktop Development.  The Forms App is then listed for both VB and C#.  
It just isn't evident in the beginning

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d0cb94-2886-79ce-39dd-0336282369b9
* Version Independent ID: e8bcc58e-98af-e3ad-2629-0b4515047d0b
* Content: [Modify Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio#modify-individual-components)
* Content Source: [docs/install/modify-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/modify-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@DavidSwiss Thanks for your feedback! Actually, there isn't a default workload that installs; the UWP workload just happens to be the first workload listed, and would only install if you've selected it. But yes, you do need the .NET Desktop Development workload for [Windows Forms](https://docs.microsoft.com/en-us/visualstudio/ide/create-a-visual-basic-winform-in-visual-studio). For more information about how to select and install workloads, please see the Select Workloads section of the [Install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio#step-4---select-workloads) page.

Thanks,
~ Terry
