### ISSUE TITLE
How we can get full list of workloads and components fast?

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/visualstudio-docs#1121]
If I wanna install only component I need to specify the list of workloads or components. But where and how I can get full list of components and workloads?
It's not mentioned in the article. It's also not mentioned in a commandline documentation https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio 
Could you give direct links to https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids to reduce the number of hops and number of frustrated devs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network#step-3---install-visual-studio-from-the-local-cache)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@SychevIgor A great suggestion; we'll get it implemented. The doc fix should go live tomorrow. And thanks for your feedback!

**Comment by TerryGLee** [comment]
The doc fix is live. Thanks again for the suggestion!
