### ISSUE TITLE
What {0} should mean here? 

### ISSUE THREAD

**Issue by michaelbaranov** [MicrosoftDocs/visualstudio-docs#1122]
Looks like autogeneration artifacts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1364960c-6182-b82a-a216-a4b4b27c5ebd
* Version Independent ID: c639343f-2346-9729-a781-317c0cc72e86
* Content: [CA1063: Implement IDisposable correctly - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1063-implement-idisposable-correctly)
* Content Source: [docs/code-quality/ca1063-implement-idisposable-correctly.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1063-implement-idisposable-correctly.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@michaelbaranov Hmm, very good question! I'll fix this, thanks.
