### ISSUE TITLE
2-1 step 2

### ISSUE THREAD

**Issue by mrlimsllc** [MicrosoftDocs/visualstudio-docs#1123]
File name is incorrect __init.py__ vs __init__.py

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3acaa1b-ee19-c571-7c5c-8611722bc0ac
* Version Independent ID: 82c0c673-a82c-3443-0b9c-e30ef39bc894
* Content: [Tutorial - Learn Flask in Visual Studio, step 2 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-02-create-app)
* Content Source: [docs/python/learn-flask-visual-studio-step-02-create-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-flask-visual-studio-step-02-create-app.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@mrlimsllc Thanks so much for pointing that out! It's a typo that I made in a couple of places, primarily because I haven't quite trained my brain and fingers to type the dunders in the middle of conversational text. :)
