### ISSUE TITLE
Clarification that workloads/components should be targeted by the Build Tools installer needed

### ISSUE THREAD

**Issue by lmf-mx** [MicrosoftDocs/visualstudio-docs#1124]
The only direct reference to the Build Tools installer is the link to it in the "See also" section. The second link on the page, "Use Command-Line Parameters to Install Visual Studio 2017", refers to the installers for VS. While the syntax and switches of the installer are the same, this can imply that these components can be targeted from the VS installers.
The document could use some modification in a prominent location to make it obvious, __especially when landing on the page from an Internet search__, that the Build Tools installer should be used to target these components.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e062363-94e9-f776-650f-a0723ab713a3
* Version Independent ID: 9181db12-cbdf-6f95-27f1-833930d6d323
* Content: [Visual Studio Build Tools 2017 workload and component IDs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools#feedback)
* Content Source: [docs/install/workload-component-id-vs-build-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-build-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@lmf-mx Thanks for your feedback! We'll certainly take this under advisement for either improving this page, or creating a different experience with regard to documenting Build Tools. We'll place this in our backlog catalog for the moment, but will report back soon.

**Comment by msebolt** [comment]
@lmf-mx The document has been adjusted to highlight using the installer.

**Comment by TerryGLee** [comment]
@lmf-mx We've added information that you requested to the page. We'll close this issue now. Thanks for helping us improve the documentation!
