### ISSUE TITLE
Step 9 didn't work for me.

### ISSUE THREAD

**Issue by nhwilly** [MicrosoftDocs/visualstudio-docs#1125]
&gt;"Select the base directory, and from the right-click or context menu, choose Send to &gt; Compressed (zipped) folder."

When I did that, I got a parent folder inside a zip file.  That didn't work, so I selected all the files in the base directory and sent them to a zip file and it worked.

Maybe I'm doing it wrong.  FWIW.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e208-2a2a-9fc3-98ff-147540157f32
* Version Independent ID: 5f5c9adf-da1d-ec0b-8af3-ccd2e27eaadc
* Content: [Create multi-project templates for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates)
* Content Source: [docs/ide/how-to-create-multi-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-multi-project-templates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@nhwilly Thank you, I will see if the step needs to be modified.

**Comment by harshalsinha** [comment]
@nhwilly Thank you for sharing, even I had been facing the same issue.
