### ISSUE TITLE
Problem encountered (and resolved)

### ISSUE THREAD

**Issue by CaspianCanuck** [MicrosoftDocs/visualstudio-docs#1129]
While following the doc's instructions I encountered the following problem in VS Community 2017:

The new files server.js, index.html, tsconfig.json and webpack-config.js added to the project were misidentified as TS. VS automatically changed their extension to .ts and created &lt;TypeScriptCompile&gt; nodes for them in the project file.  Project build then failed with errors:

"Build: File xxx has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'."

Fixing it required a manual edit of the project file outside of VS to delete the &lt;TypeScriptCompile&gt; nodes. That removed these files from the project once VS refreshed it, so they had to be added one by one manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b3b809-00c3-5637-ab09-0180827ffe4c
* Version Independent ID: 2e5782ba-8234-95d5-cc22-1a68c3b4ae34
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/nodejs/tutorial-nodejs-with-react-and-jsx#feedback)
* Content Source: [docs/nodejs/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/nodejs/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@CaspianCanuck Hi, what version of 2017 are you running? E.g., 15.7.2? Did you start with a JavaScript or TypeScript template? (Blank Node.js Web Application template under the JS or TS node?) I have not seen this problem as of yet.

**Comment by Mikejo5000** [comment]
No repro so far.
