### ISSUE TITLE
Renewing the benefit

### ISSUE THREAD

**Issue by AlWoj** [MicrosoftDocs/visualstudio-docs#1132]
What does renewable mean? Will I be ablke to renew it after subscription ends or is it renewing itself every year while I have subscription? Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b2872e-438a-b86e-9ff5-6dc0021f3fe8
* Version Independent ID: 8b9e935e-07ad-4992-edb9-e8361d867617
* Content: [EMS Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ems)
* Content Source: [subscriptions/vs-ems.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-ems.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@AlWoj Thanks for reaching out.  "Renewable" means that the benefit is renewed when you renew your subscription so that it's available as long as you have your subscription.  If you choose to let your subscription expire, you can switch EMS to a paid service if you wish to continue using it.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for your response; I will close the issue now as "asked and answered." (@AlWoj Even though we have closed the issue, you are more than welcome to add any follow-up comments that you might have.)

**Comment by reisi1** [comment]
our subscription was renewed but not the EMS part. It's also not possbile to activate the service with following message. 
It’s no longer offered by Microsoft.
You’ve already tried this service. You can sign up for a trial only once.
The beta or trial you’re requesting has expired.
The promotion code has already been used.

**Comment by davidguest44** [comment]
Can we get this resolved, please?  When it comes to renewing a benefit being told that it is not available is simply wrong.  While this is not really a documentation issue the doc implies that the license allocation is renewable and yet it does not work.  I don't want to have to spin up a new Azure tenancy each year just to assign the relevant license as I lose all of the previous configuration.

**Comment by evanwindom** [comment]
@davidguest44 - Thanks for reaching out.  I understand your frustration.  The behavior of EMS included in the subscription is set by the EMS offer rather than the subscription.  The EMS team is aware of the issue, and exploring solutions, but as of right now, I don't have any news to offer you.

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger18** [comment]
Only Microsoft employees can manage issues via commenting in this repo.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for your further response to this comment thread. (FYI: Because this issue was previously closed, it looks like the PRMerger automation returned an odd message; we'll look into this.)
