### ISSUE TITLE
CA1063 Contradicts VS Boiler plate comments - .NET Standard

### ISSUE THREAD

**Issue by Korporal** [MicrosoftDocs/visualstudio-docs#1134]
If a class is updated to implement `IDisposable` and then the VS 2017 prompt followed to insert default implementation code (_Implement interface with Dispose pattern_), then the comments in that inserted boiler plate code contradicts advice given by the analyzer.

The analyzer advice in this case is: 

Modify `ExtendedFile.Dispose` so that it calls `Dispose(true)`, then calls `GC.SuppressFinalize` on the current object instance ('this' or 'Me' in Visual Basic), and then returns.

Yet the inserted boiler plate code ALREADY does call `Dispose(true)` and the boiler plate comments also say there is no need to call `GC.SuppressFinalize` unless the finalizer is overridden and that should not even be overridden unless there are unmanaged resources to free.

Which is correct `CA1063` or the boiler plate code? It seems that the analyzer is doing a rather feeble analysis here.

UPDATE - It seems that the analyzer reports this intermittently, I have two solutions each with a relatively simple class that implements `IDisposable` in the same way yet one doesn't report this and the other does. 

The project that gets the analyzer warning targets `.NET Standard 2.0`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1364960c-6182-b82a-a216-a4b4b27c5ebd
* Version Independent ID: c639343f-2346-9729-a781-317c0cc72e86
* Content: [CA1063: Implement IDisposable correctly - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1063-implement-idisposable-correctly)
* Content Source: [docs/code-quality/ca1063-implement-idisposable-correctly.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1063-implement-idisposable-correctly.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Manish, can you take a look at the customer's concern here? It seems like this may be an issue with the analyzer only in .NET Standard projects, and may be generating a warning when it shouldn't be.

**Comment by mavasani** [comment]
@Korporal Can you please confirm how are executing the analysis? Are you executing "Run Code Analysis" command or are you installing FxCop analyzers?

**Comment by gewarren** [comment]
Closing due to lack of information.

**Comment by jv42** [comment]
@gewarren @mavasani I have the exact same issue here, it seems it only occurs with the 'live' CodeAnalysis feature.

**Comment by jv42** [comment]
I mean, you probably need this extension: https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.MicrosoftCodeAnalysis2017

**Comment by gewarren** [comment]
@mavasani In answer to your question, the customer installed the FxCop analyzers package.

**Comment by jv42** [comment]
Here is the exact message:
`Modify MyDisposableClass.Dispose so that it calls Dispose(true), then calls GC.SuppressFinalize on the current object instance ('this' or 'Me' in Visual Basic), and then returns.`

And the relevant part of the Dispose pattern implementation:
```
// Override a finalizer only if Dispose(bool disposing) above has code to free unmanaged resources.
// ~MyDisposableClass() {
//   // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
//   Dispose(false);
// }

public void Dispose()
{
    // Do not change this code. Put cleanup code in Dispose(bool disposing) above.
    Dispose(true);
    // Uncomment the following line if the finalizer is overridden above.
    // GC.SuppressFinalize(this);
}```

Hope this helps!

**Comment by jv42** [comment]
Here's another bit of info, maybe useful: I'm not using .NET Standard but .NET Framework 4.7.2, so this doesn't seem limited to one or the other.

@gewarren Any updates on your side?

**Comment by mavasani** [comment]
@jv42 Indeed seems like a bug in the analyzer - it should warn on missing `GC.SuppressFinalize` only if the type has a finalizer. Filed https://github.com/dotnet/roslyn-analyzers/issues/1974 to fix the analyzer.

**Comment by jv42** [comment]
@mavasani Ok thanks! I'll monitor that issue then.

**Comment by mavasani** [comment]
@jv42 - https://github.com/dotnet/roslyn-analyzers/pull/1975 should fix it

**Comment by jv42** [comment]
@mavasani Awesome, this was very quick indeed! Looking forward to the update then.

**Comment by gewarren** [comment]
@mavasani Thanks for fixing this, and @jv42 thanks for the additional information on the issue.
