### ISSUE TITLE
How does one create an inline task that only executes after all projects.

### ISSUE THREAD

**Issue by AraHaan** [MicrosoftDocs/visualstudio-docs#1135]
So like I am not always sure on the build order to hard code the task to execute in a specific project because one can always add new projects that would make the task need to be moved to that project. Instead if would be nice if inline tasks can be coded in the solution file itself and configured to only execute after all projects even added ones are built. This would fix my issue I am facing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868d865b-89d9-ec87-d569-862d168dc6ca
* Version Independent ID: a95f34e2-8f4b-4a4b-cb7e-075e4ceebd69
* Content: [How to: Extend the Visual Studio Build Process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process)
* Content Source: [docs/msbuild/how-to-extend-the-visual-studio-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-extend-the-visual-studio-build-process.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I believe this would be a new feature. If you'd like to suggest it, please go here and click "Suggest a feature":
https://developercommunity.visualstudio.com/spaces/8/index.html
