### ISSUE TITLE
Custom Build Documentation for "Open Folder" Lacks Example for Simple Single-Source Build 

### ISSUE THREAD

**Issue by drankinatty** [MicrosoftDocs/visualstudio-docs#1136]
The documentation pages for VS2017 "Open Folder", e.g.

https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions
https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects
https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs
https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio 

all lack a simple example for building single-source C/C++ files using 'tasks.vs.json'. The final link above does a good job for 'makefile' based projects, but lacks anything related to a single-source compile using 'cl.exe'. A short example similar to the following would help, e.g adding a task in 'tasks.vs.json' similar to:

{
  "version": "0.2.1",
  "tasks": [
    {
        "taskName": "Compile",
        "appliesTo": "*.c",
        "type": "command",
        "command": "cl",
        "args": [ "/nologo /W3 /wd4996 /Ox /Foobj/ /Febin/${fileBasename} /Tc ${file}" ],
        "envVars": {
            "VSCMD_START_DIR": "\"${workspaceRoot}\""
        }
    }
  ]
}

There may be a better way of creating the task, and you could utilize the 'outDir' parameter instead of the '/Febin/' option, but some example like this would be much appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f6ef2c-e616-bf4c-6de4-1448814e4f73
* Version Independent ID: b223e86b-b0d8-3a78-3fe5-0938e6641042
* Content: [Customize build and debug tasks in Visual Studio using tasks.vs.json and launch.vs.json - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio)
* Content Source: [docs/ide/customize-build-and-debug-tasks-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/customize-build-and-debug-tasks-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mikeblome** [comment]
Thanks for reporting this @drankinatty. I'll follow up with the product team.

**Comment by mikeblome** [comment]
@WillBuik do we have a good example for single-source task.json files?

**Comment by mikeblome** [comment]
following up

**Comment by simoncal** [comment]
@WillBuik and @mluparu, can you assist to get a good sample, or verify that @drankinatty's example above is good to go?

**Comment by corob-msft** [comment]
@drankinatty 

This issue hasn't gotten any traction, so it's safe to assume it's not going to. I suspect that it's a case of "the examples don't show the *precise thing* I wanted to know", which we can't fully address without creating the problem "There's way too much stuff here to find the precise thing I wanted to know." Maybe that's the better problem to have, if only we had the time.

You did manage to synthesize our docs into something that worked. The example of creating a generic task in [Define arbitrary tasks](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019#define-arbitrary-tasks), plus the g++ build example in [Define build tasks with tasks.vs.json](https://docs.microsoft.com/en-us/cpp/build/open-folder-projects-cpp?view=vs-2019#define-build-tasks-with-tasksvsjson), combined with the compiler command line docs, let you create something that compiles an arbitrary .c file with a particular set of options into an executable. Sounds like a success, really.

**Comment by drankinatty** [comment]
Thank you for your reply. I've been coding for a very long time (since the 80's). What prompted the issue was running across something in documentation where the answer was readily apparent. As an engineer, I try and pass those things along to help the next soul that runs across the same issue. I understand that you can't cater to everything "I want to see", that's legitimate, but here, unlike other sections, there was no simple example that made thing apparent. I got it sorted, so I suspect the next person will as well. Thanks.
