### ISSUE TITLE
xUnit Does not work for Visual Studio 2017

### ISSUE THREAD

**Issue by sscoleman** [MicrosoftDocs/visualstudio-docs#1138]
There is not a working extension for Visual Studio 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b8edaf-7667-a3e6-38dc-371c53bcd386
* Version Independent ID: 580e757e-8ce7-1437-3843-c88ff4f3ab54
* Content: [Generate unit tests for your code with IntelliTest in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/generate-unit-tests-for-your-code-with-intellitest)
* Content Source: [docs/test/generate-unit-tests-for-your-code-with-intellitest.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/generate-unit-tests-for-your-code-with-intellitest.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@sscoleman Is this still a problem for you? Have you tried to create a unit test project using one of the xUnit test project templates in Visual Studio?

**Comment by TerryGLee** [comment]
@sscoleman We haven't heard back from you, so we'll close this issue now. 

However, if you have further product feedback for us about functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.

(Alternatively, if you are experiencing problem with the product as-is, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.)

Thanks for your interest in Visual Studio!
