### ISSUE TITLE
Ambiguity in overriding ToolsVersion settings

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#1140]
The "Order of Precedence" section should describe a 100% precise and unambiguous algorithm for determining the ToolsVersion to be used to build the given project.

Many of the cases mention extremely ambiguous terms "ToolsVersion" and "current ToolsVersion". The whole algorithm is about determining "the ToolsVersion value to use"; there is a "ToolsVersions" attribute in the project, "ToolsVersions" property in the MSBuild task, a "ToolsVersions" value of the version of Visual Studio used or installed on the machine. I have no idea which of these distinct things is used in each context in the algorithm description. the cases listed are not mutually exclusive and not exhaustive. Please apply strict logic to fix this algorithm and make it precise and unambiguous.

Copied from https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_queries/edit/460302/?triage=true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 578f06ee-4e25-db51-aafc-0932c805b455
* Version Independent ID: a47ae76e-5748-b469-fce2-03e0e7f15fb7
* Content: [Overriding ToolsVersion Settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/overriding-toolsversion-settings#order-of-precedence)
* Content Source: [docs/msbuild/overriding-toolsversion-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/overriding-toolsversion-settings.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I'll take a look at this.

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, is "current ToolsVersion in steps 3, 4 and 6d in the Order of Precedence section ambiguous? And "ToolsVersion" in 6a?

**Comment by ArsenShnurkov** [comment]
see also https://developercommunity.visualstudio.com/content/problem/404485/vs2019-msbuildtoolsversion-is-not-a-version.html
