### ISSUE TITLE
Minor typo: ArrangeOverride, and ArrangeOverride

### ISSUE THREAD

**Issue by Raulland** [MicrosoftDocs/visualstudio-docs#1143]
In Layout section: The Layout event accurately determines the cost of laying out each element (that is, the time spent in Arrange, Measure, ApplyTemplate, ArrangeOverride, and ArrangeOverride) 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70bc0a73-a7f3-df8a-3c28-9be2f70638e3
* Version Independent ID: f83b9422-120d-576a-201a-5da098f60a91
* Content: [Analyze Resource Consumption in XAML Apps in Visual Studio - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/profiling/application-timeline)
* Content Source: [docs/profiling/application-timeline.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/application-timeline.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Raulland Thanks for pointing it out. I'll fix it.

**Comment by redoced** [comment]
@Mikejo5000 you fixed it by removing it, but I think it's supposed to be 
"(that is, the time spent in Arrange, Measure, ApplyTemplate, ArrangeOverride, and MeasureOverride)"

**Comment by Mikejo5000** [comment]
@redoced Thanks! I'm making the fix.
