### ISSUE TITLE
The described way to change template location doesn't work

### ISSUE THREAD

**Issue by drwatson1** [MicrosoftDocs/visualstudio-docs#1145]
I found a less complicated way to change the location. After I add project template zip file as a VSIX asset I have this folder tree:
&lt;VSIX Project Root Folder&gt;
/ProjectTemplates
/ProjectTemplates/ExampleTemplate.zip

The source.extension.vsixmanifest file contains these lines:

    &lt;Assets&gt;
        &lt;Asset Type="Microsoft.VisualStudio.ProjectTemplate" d:Source="File" Path="ProjectTemplates" d:TargetPath="ProjectTemplates\ExampleTemplate.zip" /&gt;
    &lt;/Assets&gt;

If you create Visual C# project and want to change project template location from the default position (in the root of Visual C#) to, for example, Visual C#\Web you should:

1. In the VS IDE create subfolder "CSharp\Web" in the "ProjectTemplates" folder
2. Move ExampleTemplate.zip to this new folder. Now you have this folder tree:

/ProjectTemplates
/ProjectTemplates/CSharp
/ProjectTemplates/CSharp/Web
/ProjectTemplates/CSharp/Web/ExampleTemplate.zip

3. Open the source.extension.vsixmanifest file and change the line:

&lt;Asset Type="Microsoft.VisualStudio.ProjectTemplate" d:Source="File" Path="ProjectTemplates" d:TargetPath="ProjectTemplates\ExampleTemplate.zip" /&gt;

To:

&lt;Asset Type="Microsoft.VisualStudio.ProjectTemplate" d:Source="File" Path="ProjectTemplates" d:TargetPath="ProjectTemplates\CSharp\Web\ExampleTemplate.zip" /&gt;

4. Build VSIX project

That's all! Install it and use. Without any magic with extension changing from vsix to zip and back to vsix and so forth...

You can see example in this repo: https://github.com/drwatson1/AspNet-WebApi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4359c3-e7ae-fac2-8dc8-0edfc543f46a
* Version Independent ID: ba448b8a-8bfc-bdc7-e22d-751cd84bcbe6
* Content: [Getting Started with the VSIX Project Template - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-the-vsix-project-template#deploying-a-custom-project-template-using-the-vsix-project-template)
* Content Source: [docs/extensibility/getting-started-with-the-vsix-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/getting-started-with-the-vsix-project-template.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
