### ISSUE TITLE
Documentation on how to create Solution Templates

### ISSUE THREAD

**Issue by kelps** [MicrosoftDocs/visualstudio-docs#1146]
Documentation on how to create Solution Templates with pre defined structure (solution folders) and basic files in those folders (readmes, docs, scripts, .ignore...). Some companies and dev teams have their own standards and being able to create templates like this would be great. I know it is possible to create multi-project templates, but what I'm asking for is some documentation on how to create solution templates without projects but with some structure and basic files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb0873f-6486-57fb-93db-1bc662cbbfca
* Version Independent ID: 91f46431-09ff-2f01-bd20-e8e1a9490a0b
* Content: [Project and Solution File Types - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/project-and-solution-file-types)
* Content Source: [docs/ide/reference/project-and-solution-file-types.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/project-and-solution-file-types.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@kelps Thanks for the suggestion. I'll add this to our backlog.

**Comment by gewarren** [comment]
@prnadago Is it possible to create custom solution templates (without projects) as described?

**Comment by gewarren** [comment]
@kelps It is possible to author a solution template with whatever content you like, using the **Blank Solution** template as a starting point. You won't be able to automatically create the template by using **Export Template** (that only works for project templates), but you should be able to author a solution template manually. Even though these steps are specific for web templates, the general steps to create a template manually are here: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-manually-create-web-templates?view=vs-2019#to-manually-create-a-web-template.

Given that we haven't had many requests for the documentation you're requesting, I'm closing out this issue. We can revisit adding documentation for this scenario if we get more requests.
