### ISSUE TITLE
CEO

### ISSUE THREAD

**Issue by dannyspeagle** [MicrosoftDocs/visualstudio-docs#1147]
I was on Microsoft Visual Studio working on a program when I noticed at the very bottom on the far right was an action that read " (uparrow) Add to Source Control".  Well, I don't know what Source Control is.  So, I came here.  And what do you know...There is no definition on the very page that is supposed to tell me about Source Control.  Ugh...  So, I still don't know.  

Now, how can I determine if I want to use Source Control if I don't know what it is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d694b45-7f91-63cb-e02e-352af73e54a4
* Version Independent ID: 0162239a-2140-1f7f-2bc1-0e4686637621
* Content: [Source Control - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/source-control)
* Content Source: [docs/extensibility/internals/source-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/source-control.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @dannyspeagle, Sorry you landed on this topic which is for Visual Studio extenders wanting to provide source control (version control) plug-ins. We'll update the topic header to make this clearer.
For a general introduction to source control, you might try https://en.wikipedia.org/wiki/Version_control.  For Visual Studio supported source control systems, see https://docs.microsoft.com/en-us/vsts/tfvc/comparison-git-tfvc?view=vsts
