### ISSUE TITLE
Unit test apps that use the camera?

### ISSUE THREAD

**Issue by devluz** [MicrosoftDocs/visualstudio-docs#1149]
How can you run unit tests automatically that use video devices? By default UWP will ask the user to allow access thus stalling all tests. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ad1796-f0fa-b93d-f885-542e7e50e3d2
* Version Independent ID: bacdf7a8-a577-bd17-769c-46397b5850b5
* Content: [Creating and Running Unit Tests for UWP apps in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@PBoraMSFT do you know who can answer this question? Thanks!

**Comment by msebolt** [comment]
@devluz UWP unit test projects should work similar to code projects with regard to setting the Capabilities tab of the Package.appxmanifest file.  After allowing access, you need to approve initially, but can then run tests unrestricted until either another manifest change is made or you reopen the project.  Are you experiencing different results or does the project have different requirements?

**Comment by devluz** [comment]
If I remember correctly every single code change would trigger the window to show up again asking for access to the camera / microphone. So there was really no way of running the test completely automated. Someone had to manually allow webcam / microphone access after every single change.

**Comment by TerryGLee** [comment]
@devluz It looks like you have an excellent suggestion for functionality that isn’t currently provided by the product. Please consider using our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.

For now, we'll close this issue as it isn't documentation specific. We thank you though for your feedback, and your continued interest in Visual Studio!
