### ISSUE TITLE
Error in EnvDTE.ToolBoxItems.Add code sample, no way to edit

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/visualstudio-docs#1150]
The issue is transferred from https://github.com/MicrosoftDocs/feedback/issues/246
In the second code sample under https://docs.microsoft.com/en-us/dotnet/api/envdte.toolboxitems.add#Examples, it has "C:\Libraries\ADotNetControl.dll(" where I believe it's supposed to just be "C:\Libraries\ADotNetControl.dll".
Why can't I submit a PR for this?

Migrated from MicrosoftDocs/Docs
Feedback from @jnm2

**Comment by Powerhelmsman** [comment]
Please assign this to @gregvanl

**Comment by gregvanl** [comment]
My mistake, this is code block is in the API reference and needs to be fixed elsewhere
