### ISSUE TITLE
Is the term correct ? (MVP and RD)

### ISSUE THREAD

**Issue by k-takai** [MicrosoftDocs/visualstudio-docs#1152]
> Microsoft Valued Partner (MVP)
> Region Director (RD)

There are written the above terms in some pages.
I think followings are correct, isn't it?

> Most Valuable Professional (MVP)
> Regional Director (RD)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 104e12fa-1d63-852f-1e4d-460d323fa3e9
* Version Independent ID: c9d28ce0-c253-05dc-0643-4474e454457a
* Content: [Visual Studio IDE Benefit in Visual Studio Subscription](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ide-benefit#feedback)
* Content Source: [subscriptions/vs-ide-benefit.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-ide-benefit.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by gewarren** [comment]
@k-takai I think you are correct Kazuki. @TerryGLee can you take a look?

**Comment by evanwindom** [comment]
@gewarren  Kazuki is correct.  I will take care of it.   @TerryGLee - FYI

**Comment by TerryGLee** [comment]
@evanwindom FYI.

**Comment by gewarren** [comment]
@evanwindom Do we also need to change 'Region Director' to 'Regional Director'?

Includes:  Not for Resale (NFR), Microsoft Valued Professional (MVP), Region Director (RD), Visual Studio Industry Partner (VSIP), BizSpark, Imagine, MCT

**Comment by evanwindom** [comment]
@gewarren -- Yes.  That's correct.

**Comment by TerryGLee** [comment]
@gewarren This was fixed, per [PR# 3686](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/3686) @evanwindom Thanks for fixing this.
