### ISSUE TITLE
Async Task intellitrace events

### ISSUE THREAD

**Issue by anantharamakrishnans** [MicrosoftDocs/visualstudio-docs#1153]
If I create a async task in controller and hook up intellitrace standalone collector which just uses HttpClient to call a web service then would trace be collected? I tried and it didn't result in any trace file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 995e3a2f-5674-63c4-5899-ba9a6b0e5da6
* Version Independent ID: b93833ad-9195-96b4-6fac-8893836cde4e
* Content: [Using the IntelliTrace stand-alone collector - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-intellitrace-stand-alone-collector)
* Content Source: [docs/debugger/using-the-intellitrace-stand-alone-collector.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-the-intellitrace-stand-alone-collector.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@andysterland Andy, who might best answer this question?

**Comment by anantharamakrishnans** [comment]
[HomeController.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/2135721/HomeController.zip)

[HomeController WebService.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/2135736/HomeController.WebService.zip)

The web application (MVC Application controller code snippet shared as HomeController.zip)- "WEBUI" calls Web Service "WEBSERVICE"(Again MVC application and controller code snippet shared as HomeController WebService.zip) whose code snippet I have attached.

I am able to get trace files for "WebService" app however I am unable to get trace files for "WebUI" app.
Although the trace file for WebService doesn't have any informations probably because there are no intellitrace events for the method - GetEmpDetails().

Please note I am testing WebUI application - (method in HomeController.zip - Index() method) to check for trace files which is not getting generated.

**Comment by Mikejo5000** [comment]
@anantharamakrishnans  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
