### ISSUE TITLE
How about Core or Standard Target Frameworks?

### ISSUE THREAD

**Issue by mwpowellhtx** [MicrosoftDocs/visualstudio-docs#1154]
Is that all the Target Frameworks that are supported? Surely ``netcoreapp`` or ``netstandard`` are also supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a80e5d7-2db7-48c0-e8b6-ca8c3ff30017
* Version Independent ID: ad64635b-06d5-1b87-8f02-80cf25c12520
* Content: [MSBuild Target Framework and Target Platform - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform)
* Content Source: [docs/msbuild/msbuild-target-framework-and-target-platform.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-target-framework-and-target-platform.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Hi, you will want to use the Sdk element for .NET Core. For more info, see https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0. There are several links to more info on this page. Also, this page: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk

**Comment by mwpowellhtx** [comment]
Admittedly, I was "here" in the docs on something of a rabbit hole chasing the infamous ``Assets file doesn't have a target for '.NETCoreApp,Version=v2.0'. Ensure that restore has run and that you have included 'netcoreapp2.0' in the TargetFrameworks for your project`` error. Which I followed down the path of verifying my *MSBuild* options, potentially including ``TargetFrameworks``.

As it turns out the solution was to delete (or rename) my ``<path-to-sdk/>\...`` folders. Then my programmatic *MSBuild* invocation succeeded.

However, as regards this documentation page, I do not see any mention of the ``netcoreapp`` or ``netstandard`` target frameworks. Only the *runtimes*.

**Comment by Mikejo5000** [comment]
Asked @rainersigwald about this.

**Comment by rainersigwald** [comment]
This page should add 4.7.2 and 4.8, since they're supported by the type of projects it's mostly covering.

I think it'd also be a good idea to put something along the lines of this in this article

> ⚠This is the old way; SDK-style projects enable different TargetFrameworks like `netstandard`. See https://docs.microsoft.com/en-us/dotnet/standard/frameworks

It's definitely very confusing to have these parallel constructions, and someone stumbling along this page while looking for https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-target-frameworks is totally understandable.

**Comment by Mikejo5000** [comment]
Thanks! Updating doc
