### ISSUE TITLE
Export Template wizard now located under "Project" menu

### ISSUE THREAD

**Issue by zzhhbyt1** [MicrosoftDocs/visualstudio-docs#116]
... But many relative documents still orient to the old version which it's under 'Files' section.

**Comment by kempb** [comment]
Thanks for reporting this issue. I've added it to our task backlog for fixing.

**Comment by gewarren** [comment]
[How to: update existing templates](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-update-existing-templates) still needs to be updated, but how to create project templates and how to create item templates have been updated already.

**Comment by gewarren** [comment]
@zzhhbyt1 thanks for reporting this. All 3 topics have been updated now, but it might take a few days for the last one to go live.
