### ISSUE TITLE
StoredProcedure.R or SqlSProc.R

### ISSUE THREAD

**Issue by datarelish** [MicrosoftDocs/visualstudio-docs#1160]
hi there, the documentation refers to StoredProcedure.R but the actual R template shows the file as SqlSProc.R.
It's a bit confusing, and it's not clear if you want someone to set up a new file or whether they should use the existing file in the template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ee57e7-f1a1-3ea5-b188-41af8106ac92
* Version Independent ID: 08a2d04e-9ac5-ca1e-49fa-3441ea39b672
* Content: [Integrating SQL Server with R - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/integrating-sql-server-with-r)
* Content Source: [docs/rtvs/integrating-sql-server-with-r.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/integrating-sql-server-with-r.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
OK, thanks for letting us know. I'll get it clarified.

**Comment by kraigb** [comment]
Just to note, the item template uses "SqlSProc.R" by default for the filename; the documentation indicates that you can change the name to anything you want, which is of course necessary if you have more than one such file.

**Comment by kraigb** [comment]
Edits made.
