### ISSUE TITLE
Erroneous dialog text for Advanced Save Options

### ISSUE THREAD

**Issue by hollasch** [MicrosoftDocs/visualstudio-docs#1163]
The text in this dialog should be changed. For one, modern Windows is quite happy with LF line endings (even .bat and .reg files). Secondly, Macintosh systems have abandoned CR line endings since they migrated to OS X in 2001. This _could_ be replaced with "Legacy [pre-2001] Macintosh (CR)", but probably better to just leave it at CR.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2642c7f-04bb-56eb-0f26-d867703cf2f4
* Version Independent ID: 9c3f65b2-143b-8053-35ad-866152ea905e
* Content: [Visual Studio encoding and line break characters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks)
* Content Source: [docs/ide/encodings-and-line-breaks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/encodings-and-line-breaks.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@hollasch Are you referring to the "line endings" selections in the drop-down list? E.g.

Windows (CR LF)
Macintosh (CR)

**Comment by hollasch** [comment]
Yes, sorry about not being clear.

**Comment by hollasch** [comment]
One additional note: for several years now developers have been asking for better line-ending control in Visual Studio. This might take several forms: an option to specify desired line endings, an option to detect and preserve line endings, and so forth. I'm not raising that issue in this one, but noting that there is likely another issue related to this one with respect to line endings and Visual Studio (possibly parked) that may need to be reconciled with the documentation/UI for this issue.

**Comment by gewarren** [comment]
@markw-t Can you take a look at this feedback about the Advanced Save Options dialog? Steve thinks that the following "line endings" selections in the drop-down list should be updated:

Windows (CR LF)
Macintosh (CR)

**Comment by gewarren** [comment]
@hollasch There's a new way to suggest features on [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8). Can you please file this suggestion over there to get better traction on it?
