### ISSUE TITLE
"largest" and "smallest" do not unambiguously convey ordering

### ISSUE THREAD

**Issue by kwbskf** [MicrosoftDocs/visualstudio-docs#1168]
Wording choice:  highest or greatest is better than "largest", lowest or least is better than "smallest", since in most people's minds, the value of -98,765 is certain "larger" than 1.03612E-08, having a much larger *magnitude*, despite falling below it in the natural ordering of real numbers.  This is important, because when dealing with range a precision of a type (in a programming language) that can hold floating-point values, the concept of precision of the smallest-magnitude value is another characteristic we sometimes want to know.  Saying "smallest" suggests that you are speaking of such a smallest-magnitude value, not the lowest possible value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d90002ac-ff25-b1a6-e79a-1ba214b92e30
* Version Independent ID: ecf0e8ef-eed7-4d6a-8ffc-ae4fc8423f7d
* Content: [Infinity Constant (JavaScript)](https://docs.microsoft.com/en-us/scripting/javascript/reference/infinity-constant-javascript)
* Content Source: [scripting-docs/javascript/reference/infinity-constant-javascript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/scripting-docs/javascript/reference/infinity-constant-javascript.md)
* Product: **windows-client-threshold**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
We are using MDN for JS ref now.
https://blogs.windows.com/msedgedev/2018/06/26/chakra-docs-mdn-web-docs/
