### ISSUE TITLE
Where does App.config file get deployed when installing "published" Office solution by OneClick?

### ISSUE THREAD

**Issue by anjalibapat** [MicrosoftDocs/visualstudio-docs#1169]
I have and Excel Document Office solution, and in order to package it, I implemented the Publishing method.   My office solution also uses application configuration file.  Once setup is executed the Excel document customization functions as expected.  But when I want to make change to configuration setting sin config file, I am not able to locate it.  The only copies I find are OSolution.dll.config.Deploy.  When I make changes to values for keys in app settings section, I receive application error, stating manifest error.  Any suggestions for this issue?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4baae220-67c0-09b8-caf6-43a6dedb8f5a
* Version Independent ID: 498f0add-fbd5-c603-e350-1ddf5d9bb740
* Content: [Server and Client Configuration Issues in ClickOnce Deployments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/server-and-client-configuration-issues-in-clickonce-deployments)
* Content Source: [docs/deployment/server-and-client-configuration-issues-in-clickonce-deployments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/server-and-client-configuration-issues-in-clickonce-deployments.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@anjalibapat  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
