### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by nertilpoci** [MicrosoftDocs/visualstudio-docs#1171]
Are there some working samples that go with the post? Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bb17b17-4dc8-7ba1-0318-af21f9d5ac43
* Version Independent ID: f704dbc4-472c-0ba9-e867-3daf24ae7ab9
* Content: [Extending the Output Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-output-window)
* Content Source: [docs/extensibility/extending-the-output-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extending-the-output-window.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
There is currently no sample code for the tutorial.
