### ISSUE TITLE
Solution Explorer filter buttons should have dynamic button visibility

### ISSUE THREAD

**Issue by vukelich** [MicrosoftDocs/visualstudio-docs#1176]
Change the button definition in the .vsct file to the following:

&lt;Button guid="guidFileFilterPackageCmdSet" id="FileFilterId" priority="0x0400" type="Button"&gt;  
    &lt;Parent guid="guidSHLMainMenu" id="IDG_VS_TOOLBAR_PROJWIN_FILTERS" /&gt;  
    &lt;Icon guid="guidImages" id="bmpPic1" /&gt;  
    &lt;CommandFlag&gt;DynamicVisibility&lt;/CommandFlag&gt;
    &lt;CommandFlag&gt;DefaultInvisible&lt;/CommandFlag&gt;
    &lt;CommandFlag&gt;DefaultDisabled&lt;/CommandFlag&gt;
    &lt;Strings&gt;  
        &lt;ButtonText&gt;FileNameFilter&lt;/ButtonText&gt;  
    &lt;/Strings&gt;  
&lt;/Button&gt;  

This makes sure the button is only visible when a Solution is open.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 435b58a5-49f7-b1eb-05b1-8f1d7598343a
* Version Independent ID: 2eb8a331-8aab-ca9f-fc0b-c594a75e934b
* Content: [Extending the Solution Explorer Filter - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-solution-explorer-filter)
* Content Source: [docs/extensibility/extending-the-solution-explorer-filter.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extending-the-solution-explorer-filter.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Fixed with https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/4598
