### ISSUE TITLE
Python environment wrongly detected after IronPython v2.7.8 upgrade

### ISSUE THREAD

**Issue by VinayGupta23** [MicrosoftDocs/visualstudio-docs#1177]
Hi,

I have been using IronPython 2.7.7 with Visual Studio without any problem. For 32-bit, there was `ipy.exe` and 64-bit had `ipy64.exe`.
After updating to IronPython 2.7.8, there was a change where 32-bit was moved to `ipy32.exe` and 64-bit to  `ipy.exe`.
Since then, the Python environment configuration has broken.

## What I tried

1. Repair installation of IronPython 2.7.8
2. Search through registry for manual editing - could not find IronPython paths as per what the [docs say](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio#fix-invalid-environments).

### 32-bit path is wrong:

![image](https://user-images.githubusercontent.com/8874825/42025982-96aa8596-7ae3-11e8-9eaa-6e9139d5ab51.png)

### 64-bit path is wrong:

![image](https://user-images.githubusercontent.com/8874825/42026010-a65b8cba-7ae3-11e8-8fc6-4dd3f4f98d00.png)

#### (No IronPython path options)

![image](https://user-images.githubusercontent.com/8874825/42026177-13ff68ea-7ae4-11e8-8d0e-c6e066235152.png)

![image](https://user-images.githubusercontent.com/8874825/42026134-f8e64380-7ae3-11e8-8773-e0341f1a6d2f.png)

---

*If I have filed this issue in the wrong place, please pardon me and direct me to the right repository - PTVS? IronPython? I have also filed this in [PTVS](https://github.com/Microsoft/PTVS/issues/4457) as it may also be a bug.*

**Comment by gewarren** [comment]
@kraigb Can you take a look at this issue?

**Comment by kraigb** [comment]
@VinayGupta23 Thanks for the report. I suspect this is a product bug, but one that likely also needs some docs treatment, so I appreciate your filing an issue with PTVS as well.

**Comment by kraigb** [comment]
Looks like the product issue was resolved for 15.8 (currently in Preview). I've added a few notes about registry locations for IronPython, which seems to be all that's needed doc-wise.
