### ISSUE TITLE
Building improperly

### ISSUE THREAD

**Issue by MaskMaster4048** [MicrosoftDocs/visualstudio-docs#1181]
Microsoft Visual Studio (with no settings changed), builds my solution into a folder containing a dll that cannot be run through the command line. I cannot get it to build into an exe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5db8407-cc91-c741-6bc4-9d059ab40308
* Version Independent ID: 8d477def-5203-6085-915b-31971afeccab
* Content: [Walkthrough: Build an application - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application)
* Content Source: [docs/ide/walkthrough-building-an-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-building-an-application.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@MaskMaster4048 Can you open the project properties, Application page, and see what the "Output type" is? For an executable, you'll want output type to be Windows Application or Console Application.

![image](https://user-images.githubusercontent.com/24882762/42115728-0262cf8a-7ba9-11e8-8512-309c597ee3a1.png)

**Comment by MaskMaster4048** [comment]
@gewarren This is how the application page looked when I opened it. I went through Windows app, Console app, and class lib to see if that would change anything, but every one built a dll. Also, I did some digging and found that the dll file runs (when debugging) through `Program Files\dotnet\dotnet.exe`, in case that helps.
![capture](https://user-images.githubusercontent.com/28271645/42118131-86393c5a-7bc6-11e8-893f-f886f8f3b50d.PNG)

**Comment by gewarren** [comment]
Ah, okay it looks like you have a .NET Core app with "framework-dependent deployment", which is the default. If you want to build an executable, you need "self-contained deployment". For more info see:

https://docs.microsoft.com/en-us/dotnet/core/deploying/index
https://stackoverflow.com/questions/39155571/how-to-run-net-core-console-app-from-the-command-line

**Comment by MaskMaster4048** [comment]
@gewarren I followed every article in that section, all failed me. I took several screenshots for you to look at. What confuses me the most is the output type is set to `Exe`, but it's outputting the dll instead. I tried to change that setting to see if there was any affect, but every option outputted a dll. 
![inkedcommand prompt 01 07 2018 1_02_10_li](https://user-images.githubusercontent.com/28271645/42131652-47ade13c-7ccc-11e8-9e99-bd607e9265ca.jpg)
![204](https://user-images.githubusercontent.com/28271645/42131654-4bad8968-7ccc-11e8-9aa7-c0da2c142cbb.PNG)
![207](https://user-images.githubusercontent.com/28271645/42131655-4f15d218-7ccc-11e8-8882-b28e8da3663a.PNG)

**Comment by gewarren** [comment]
I'm not that familiar with .NET Core apps but I'm guessing this is expected behavior. Is there a reason you need a .NET Core app? If you create a .NET Framework app you can easily build an executable.

**Comment by MaskMaster4048** [comment]
@gewarren I am just learning C# and I have no idea what the difference between the two are. I see that you are talking about `<TargetFramevork>netcoreapp2.0</TargetFramework>`, however. What do I change that to, and are there any other changes I need to make, in order to make it a .NET Framework app?

**Comment by gewarren** [comment]
.NET Core is useful for building cross-platform apps. See here for more info: https://docs.microsoft.com/en-us/dotnet/core/

It sounds like [it's possible to convert your project](https://stackoverflow.com/questions/42623103/convert-net-core-to-net-framework) to .NET Framework, but if you can, I'd highly suggest creating a new project and then copying your code/files into the new project.

This would be a good project template to use when you create the new project:

![image](https://user-images.githubusercontent.com/24882762/42181443-b1106afe-7def-11e8-81c1-080d7b2ee50f.png)

**Comment by MaskMaster4048** [comment]
@gewarren I had to open Visual Studio Installer and install the .NET Framework. It's compiling into an exe now, Thank you!
