### ISSUE TITLE
Utilities for modifying feed

### ISSUE THREAD

**Issue by luckielordie** [MicrosoftDocs/visualstudio-docs#1182]
Are there any examples of how to modify this feed?

Do I need to write my own service so my users can update their extensions? Does one already exist?

**Comment by gregvanl** [comment]
Hi @luckielordie, there is not enough context in this issue for us to redirect it to the correct people. Can you provide the topic link and a brief description of the feed you want to modify. Thanks.

**Comment by gregvanl** [comment]
Closing as no response from user
