### ISSUE TITLE
Code Map and Live Dependency Validation not available in Visual Studio Professional 15.7.1

### ISSUE THREAD

**Issue by nhristova** [MicrosoftDocs/visualstudio-docs#1183]
Clicking on Tools &gt; Get Tools and Features &gt; Individual Components &gt; Code Tools dose not have Code Map and Live Dependency Validation in the list.
Here is a link to a screen shot: https://drive.google.com/file/d/1n8k-xMRtKX071xkBdioycul9WIiWLZAe/view?usp=sharing

Has this been removed from VS Professional? 
If not, how can I install it.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c6b3cd-fc32-1501-68a6-1da597bfd33b
* Version Independent ID: 499fd553-6e2e-aefe-aefd-2711c01e39e0
* Content: [Code maps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions)
* Content Source: [docs/modeling/map-dependencies-across-your-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/map-dependencies-across-your-solutions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@nhristova Thanks for this feedback. I'll try to find out what's going on for VS Professional edition.

**Comment by lukaszpitulski** [comment]
Exactly the same here, VS17Pro 15.7.4 
Based on : [https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions]
in Visual Studio I don't have Architecture option in main menu and no Show on Code Map option in Solution Explorer at all.

I can create only empty .dgml file and add all things manually one by one :/ (without any links, dependencies etc.)

Regards,
Łukasz

**Comment by reiherric** [comment]
Yep, couldn't find it on VS Professional 15.7.5 either :(

**Comment by dangarbri** [comment]
Just wasted a few hours here trying to figure out why I don't have it.
https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions

**Comment by dangarbri** [comment]
Darn the fine print.

**Comment by adambose1990** [comment]
Here for the same reason, is there any other alternative to the codemap?
