### ISSUE TITLE
Incorrect XML?

### ISSUE THREAD

**Issue by kylejrp** [MicrosoftDocs/visualstudio-docs#1185]
This line seems strange:
    &lt;proxy bypassonlocal="True" proxyaddress=" HYPERLINK "http://&lt;yourproxy:port#" http://&lt;yourproxy:port#&gt;"/&gt;

Should this be:
    &lt;proxy bypassonlocal="True" proxyaddress="http://&lt;yourproxy:port#&gt;"/&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c02d9ac-3066-a613-ad20-7362541a0e1e
* Version Independent ID: 74bd1b09-9269-1a01-1429-6b548cc343e6
* Content: [Troubleshooting network-related errors when you install or use Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-network-related-errors-in-visual-studio)
* Content Source: [docs/install/troubleshooting-network-related-errors-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/troubleshooting-network-related-errors-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@kylejrp Thanks for your feedback! We'll investigate and report back.

**Comment by TerryGLee** [comment]
@kylejrp We'll have this fixed with tomorrow's regularly scheduled publish at noon. Thanks again for reporting it!

**Comment by kylejrp** [comment]
The line still seems off to me. Is this the correct line of code? The syntax highlighting makes me think that this is incorrect:

<proxy bypassonlocal="True" proxyaddress=" HYPERLINK "http://<yourproxy:port#>" http://<yourproxy:port#>"/>

**Comment by arche89** [comment]
You still haven't fixed that. I'm trying to set it in VS and nothing is working. This sample code is useless.

**Comment by ronanjordan** [comment]
All you need is  :
```
<system.net>
          <defaultProxy useDefaultCredentials="true" enabled="true">
           <proxy usesystemdefault="True" />
         </defaultProxy>
    </system.net>
```

It should pickup the proxy settings from IE settings

**Comment by TerryGLee** [comment]
@kylejrp After consulting with our engineering team, I've verified that the updates to the page are now correct. Thanks again to you for reporting the issue, and everyone else for your input, too.
