### ISSUE TITLE
[VS2017] File.OpenSolution not a valid command?

### ISSUE THREAD

**Issue by devesh95** [MicrosoftDocs/visualstudio-docs#1186]
Context: Running devenv commands for Visual Studio Professional 2017.

When I tried to run `devenv /command "File.OpenSolution"` I was met with an error that stated the command does not exist. This was confirmed using the command window in the IDE itself.

Either the documentation here is incorrect or outdated.

![image](https://user-images.githubusercontent.com/6236599/42110887-8dcfb04a-7b97-11e8-9e39-9ae1b3a587fc.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c909fb19-91e8-327f-8f9f-ff46b34c5198
* Version Independent ID: 19982960-d80d-d5a1-7ec9-4ff6f216cd41
* Content: [Open Solution Command - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/open-solution-command)
* Content Source: [docs/ide/reference/open-solution-command.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/open-solution-command.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This command was combined with File.OpenProject. You should be able to just call File.OpenProject with your solution and it will work. I'll update the documentation. Thanks for letting us know!
