### ISSUE TITLE
Animate objects - no video link

### ISSUE THREAD

**Issue by AhmadKelany** [MicrosoftDocs/visualstudio-docs#1189]
There is no video link at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a762743-426f-ae8a-5c4a-fdb7fcfe250d
* Version Independent ID: b1ec684f-90fc-04f4-19cf-c6b6dce6d078
* Content: [Animate objects in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/animate-objects-in-xaml-designer)
* Content Source: [docs/designers/animate-objects-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/animate-objects-in-xaml-designer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@AhmadKelany Were you expecting the illustration to be a video, or are you just asking for a link to a video tutorial? We address issues based on the number of page views of the page in question, and currently adding a video to this topic is not a priority (apologies).

**Comment by AhmadKelany** [comment]
@gewarren 
Thanks for the reply,
The page had a link to a video,
A fellow protested back in April 2018 that the link is no longer working,
you replied then that you will fix the link,

But when I viewed the article, I found no video link at all, hence my comment
![Untitled](https://user-images.githubusercontent.com/12924528/58674422-708a8e00-8358-11e9-836f-f58bdc0a9b0a.png)

**Comment by gewarren** [comment]
@AhmadKelany Thanks for explaining. When I went to update the broken link, I couldn't find a suitable replacement, so I removed it instead.

Related to #778.
