### ISSUE TITLE
Include info on how to pass and use Output values

### ISSUE THREAD

**Issue by fiksen99** [MicrosoftDocs/visualstudio-docs#1190]
None of the examples include outputs, it would be helpful to demonstrate how this is used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dbbe593-3f96-ce66-ceb3-0f7e6161dba9
* Version Independent ID: 3afb0fe4-6c5a-e899-61e1-37cd33963eba
* Content: [Task Writing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/task-writing)
* Content Source: [docs/msbuild/task-writing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/task-writing.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by dotMorten** [comment]
Agreed! Also working it input/output of a collection items/itemsgroups

**Comment by Mikejo5000** [comment]
There are a lot of potential examples that could be shown here, but most examples are in the Task Reference (tasks like Copy and Csc), including examples with outputs. I will add a link to the ref docs.

**Comment by Mikejo5000** [comment]
#2809 also shows a request for an updated sample

**Comment by Mikejo5000** [comment]
Currently out of scope to add additional examples. See #2809

**Comment by dotMorten** [comment]
How's that out of scope to add a clearly missing example on a key feature in this doc?

**Comment by Mikejo5000** [comment]
I mean out of scope based on our current available resources. If you would like to open a PR with an example, I can get it reviewed.
