### ISSUE TITLE
Severity

### ISSUE THREAD

**Issue by darrentraffk** [MicrosoftDocs/visualstudio-docs#1191]
In Severity, for "none or silent", it states, "When this style is not being followed, do not show anything to the user; however, auto-generated code follows this style."  How do you define "auto-generated"?  If we're using a tt file that generates code, does that count as "auto-generated"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b402d2e0-a53a-b61a-4da8-b5ee766d9301
* Version Independent ID: 612695df-5934-d967-d709-500ce02b1395
* Content: [.NET Naming Conventions For EditorConfig files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions)
* Content Source: [docs/ide/editorconfig-naming-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-naming-conventions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@kuhlenh Do you tt files that generate code honor EditorConfig settings?

**Comment by darrentraffk** [comment]
To add, we can mark files as autogen in the .csproj file:

`    
<Compile Update="{GeneratedFile}.cs">
    <DesignTime>True</DesignTime>
    <AutoGen>True</AutoGen>
    <DependentUpon>{TTFile}.tt</DependentUpon>
</Compile>
`

So does this mean that {GeneratedFile}.cs should conform to .editorconfig settings?

**Comment by darrentraffk** [comment]
Any updates @kuhlenh @gewarren ?

**Comment by darrentraffk** [comment]
Any updates @kuhlenh @gewarren ?

**Comment by gewarren** [comment]
@sharwell Can you or someone else help out with this question?

**Comment by sharwell** [comment]
It means code generated by an IDE feature, e.g. Generate Constructor, should be generated in a manner consistent with the rules. In some cases it's not possible to follow the rules, but in most cases where the generated code does not follow the patterns we would consider it a bug and accept a fix from a contributor to make it follow the defined style.

**Comment by gewarren** [comment]
Thanks @sharwell. @darrentraffk it sounds like the answer to whether code generated by tt files is considered auto-generated for naming validation purposes is "no".
