### ISSUE TITLE
unable to reinstall after update destroys my Dev pc:(

### ISSUE THREAD

**Issue by timberzen** [MicrosoftDocs/visualstudio-docs#1192]
I have wasted a day, just because I said 'OK' to the latest update, now my dev PC is fucked. Running   InstallCleanup.exe -i did not work, deleting the install folder did not work. What a mess.The product failed to install the listed workloads and components due to one or more package failures.

Incomplete workloads
    ASP.NET and web development (Microsoft.VisualStudio.Workload.NetWeb,version=15.0.26208.0)

Incomplete components
    .NET Portable Library targeting pack (Microsoft.VisualStudio.Component.PortableLibrary,version=15.0.26208.0)
    ASP.NET and web development tools (Microsoft.VisualStudio.Component.Web,version=15.0.26208.0)
    Data sources for SQL Server support (Microsoft.VisualStudio.Component.SQL.DataSources,version=15.0.26208.0)
    Managed Desktop Workload Core (Microsoft.VisualStudio.Component.ManagedDesktop.Core,version=15.0.26208.0)
    SQL Server Data Tools (Microsoft.VisualStudio.Component.SQL.SSDT,version=15.0.26208.0)

You can search for solutions using the information below, modify your selections for the above workloads and components and retry the installation, or remove the product from your machine.

Following is a collection of individual package failures that led to the incomplete workloads and components above. To search for existing reports of these specific problems, please copy and paste the URL from each package failure into a web browser. If the issue has already been reported, you can find solutions or workarounds there. If the issue has not been reported, you can create a new issue where other people will be able to find solutions or workarounds.

Package 'Microsoft.Net.CoreSDK.50,version=1.0.23908' failed to install.
    Search URL: https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.Net.CoreSDK.50;PackageAction=Install;ReturnCode=1632
    Impacted workloads
        ASP.NET and web development (Microsoft.VisualStudio.Workload.NetWeb,version=15.0.26208.0)
    Impacted components
        .NET Portable Library targeting pack (Microsoft.VisualStudio.Component.PortableLibrary,version=15.0.26208.0)
        ASP.NET and web development tools (Microsoft.VisualStudio.Component.Web,version=15.0.26208.0)
        Data sources for SQL Server support (Microsoft.VisualStudio.Component.SQL.DataSources,version=15.0.26208.0)
        Managed Desktop Workload Core (Microsoft.VisualStudio.Component.ManagedDesktop.Core,version=15.0.26208.0)
        SQL Server Data Tools (Microsoft.VisualStudio.Component.SQL.SSDT,version=15.0.26208.0)
    Log
        C:\Users\doug\AppData\Local\Temp\dd_setup_20180701185023_112_Microsoft.Net.CoreSDK.50.log
    Details
        MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.Net.CoreSDK.50,version=1.0.23908\netfx_NETCoreSDK.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1  MSIFASTINSTALL="7" 
        Return code: 1632
        Return code details: The Temp folder is on a drive that is full or is inaccessible. Free up space on the drive or verify that you have write permission on the Temp folder. - yet i have 200gb free!

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/install/remove-visual-studio)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
For support, please use the Feedback tool from the Visual Studio installer to send necessary logs through the appropriate channel.

**Comment by TerryGLee** [comment]
@timberzen Thanks for your feedback. You might have noted the response from HeathS, which is the best method of reporting errors to us so that it's routed to the right team. For more information about how to do this, please see the [How to report a problem with Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) page.
