### ISSUE TITLE
%ERRORLEVEL% == 1, I need to know the meaning, because ...

### ISSUE THREAD

**Issue by Blonder** [MicrosoftDocs/visualstudio-docs#1193]
I got it after updating from 15.5.7 to 15.6.7 see https://developercommunity.visualstudio.com/content/problem/273349/offline-update-of-visual-studio-2017-professional.html

**Comment by TerryGLee** [comment]
@Blonder Thanks for your inquiry. It looks like this is being addressed in the proper place, which is through the [Developer Community](https://developercommunity.visualstudio.com/content/problem/273349/offline-update-of-visual-studio-2017-professional.html). We'll close this GitHub Issue for now (because it's designed specifically for documentation issues).

**Comment by Blonder** [comment]
It is a documentaion issue, https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio 

Value | Result
-- | --
0 | Operation completed successfully
3010 | Operation completed successfully, but install requires reboot before it can be used
Other | Failure condition occurred - check the logs for more information

What is Other? I always get a 1, I would like to know the meaning of 1.
Thanks for the help,
Andreas.

**Comment by TerryGLee** [comment]
@Blonder Thanks for the further clarification re: the page you'd like to see updated. We'll investigate doing so and report back.

**Comment by Blonder** [comment]
Thanks a lot, this may help me with offline installation issues.

**Comment by TerryGLee** [comment]
@tydunkel FYI about the customer request to add more error-related info to the [Create a network installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio) page.

**Comment by TerryGLee** [comment]
@Blonder We've updated the following pages to include an expanded error list:

- [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio)
- [Create a network installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio)

The additional information includes the following:

| **Value** | **Result** |
| --------- | ---------- |
| 0 | Operation completed successfully |
| 1602 | Operation was canceled |
| 1641 | Operation completed successfully, and reboot was initiated |
| 3010 | Operation completed successfully, but install requires reboot before it can be used |
| 5003 | Bootstrapper failed to download installer |
| 5004 | Operation was canceled |
| 5005 | Bootstrapper command-line parse error |
| 5007 | Operation was blocked - the computer does not meet the requirements |
| -1073741510 | Microsoft Visual Studio Installer was terminated (by the user or external process) |
| Other<br>(for example:<br>-1, 1, 1603) | Failure condition occurred - check the logs for more information |

We'll close this issue now. And thanks again for helping us to improve the documentation!
