### ISSUE TITLE
Registering the Project Template Failed

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/visualstudio-docs#1194]
The steps at issue:
1. "Creating a  Basic Project Type" | "Extensibility | Visual Studio Package" didn't exist as an option.  The only available option was "Visual Studio AsyncPackage", which was selected.

2. "Create a Basic Project Template", Step 6.  The code that was copied and pasted into Visual Studio contained MANY errors.  According to the note below the step, these errors would be fixed in a later step.

3. "To register the project template", Step 2.  The code didn't compile because all the errors from my issue 2 above were not resolved.

I could not continue from this point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8135def2-30e0-d9e4-af54-5a8d3a073c63
* Version Independent ID: fea902ab-e883-51bd-c291-04d1988f37f6
* Content: [Creating a Basic Project System, Part 1 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-basic-project-system-part-1)
* Content Source: [docs/extensibility/creating-a-basic-project-system-part-1.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-a-basic-project-system-part-1.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by sjointer** [comment]
I forgot to mention: I'm running Visual Studio 2017 Community Edition 15.7.4, updated 1 July, 2018.

**Comment by MichelLaplane** [comment]
- I have continued successfully using "Visual Studio AsyncPackage". You just need to replace the protected override async Task InitializeAsync with function with the following code :

    protected override void Initialize()
      {
      base.Initialize();
      this.RegisterProjectFactory(new SimpleProjectFactory(this));
      }

- About the error during the compile process for registering the project template, it does not matter (assuming the file's BuildAction is Content for all the file of the SimpleProject Template project). You should see the SimpleProject in the experimental instance.

- but in the step "Test the project factory implementation"

**Comment by MichelLaplane** [comment]
but in the step "Test the project factory implementation", be sure to replace the InitializeAsync with 

protected override void Initialize()
{
base.Initialize();
this.RegisterProjectFactory(new SimpleProjectFactory(this));
}

**Comment by MichelLaplane** [comment]
A slight caveat. When closing the experimental instance an exception occurs in the "public virtual EnvDTE.Property Item(object index)" method. Not so much consequences.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
