### ISSUE TITLE
Useful page but not easy to be found

### ISSUE THREAD

**Issue by wschin** [MicrosoftDocs/visualstudio-docs#1197]
Try to Google for "&lt;Complier Include=", you will see that it's impossible to find this page which explains the meaning of this syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4c1957-1da1-073e-e5d2-b88dbb6e4f0c
* Version Independent ID: da079116-5827-d486-271b-9e2cb10bf063
* Content: [MSBuild Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items#BKMK_Creating1)
* Content Source: [docs/msbuild/msbuild-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-items.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I can make some SEO changes for this topic.
