### ISSUE TITLE
Docker for Windows with Linux Container Issues

### ISSUE THREAD

**Issue by aderderian** [MicrosoftDocs/visualstudio-docs#1198]
This doesn't work with the latest docker for windows and linux containers. Docker fails on mounting drives. Is there a way around having it build your image locally with Docker?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools)
* Content Source: [docs/deployment/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-kubernetes-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
The doc doesn't address building locally with Docker.  However, there is a troubleshooting doc that talks about a setting in Docker Desktop to enable shared drives.  More recent editions of Visual Studio handle this correctly.  I think we can close this issue now.
