### ISSUE TITLE
Where is the actual Javascript language reference documentation?

### ISSUE THREAD

**Issue by SeanGephardt1** [MicrosoftDocs/visualstudio-docs#1200]
Where is the actual Javascript language reference documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdd1c8ed-73a2-a511-2d8e-7f0582d0a0ed
* Version Independent ID: 5f96f2ff-a494-3e00-e3bf-3689da9f1f0a
* Content: [JavaScript in Visual Studio](https://docs.microsoft.com/en-us/scripting/javascript/javascript-in-vs-2017)
* Content Source: [scripting-docs/javascript/javascript-in-vs-2017.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/scripting-docs/javascript/javascript-in-vs-2017.md)
* Product: **windows-client-threshold**
* GitHub Login: @bowdenk7
* Microsoft Alias: **wilkelly**

**Comment by gewarren** [comment]
Here? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects @Mikejo5000

**Comment by Mikejo5000** [comment]
Hi, please see this:
https://docs.microsoft.com/en-us/scripting/javascript/javascript-language-reference
and this:
https://blogs.windows.com/msedgedev/2018/06/26/chakra-docs-mdn-web-docs/

I probably need to add the note to the topic you are looking at...

**Comment by SeanGephardt1** [comment]
Thanks, sorry to see it go!
