### ISSUE TITLE
MSBuildExtensionsPath32 paths are reversed

### ISSUE THREAD

**Issue by mobsoftware** [MicrosoftDocs/visualstudio-docs#1201]
The paths are as follows, "This path always points to the 32-bit \Program Files (x86) folder on a 32-bit machine and \Program Files on a 64-bit machine."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a5a0e-ae03-1237-6ebe-743066f27fa9
* Version Independent ID: a342bfa4-4b0c-0a47-3695-858044f5aa5f
* Content: [MSBuild Reserved and Well-Known Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties)
* Content Source: [docs/msbuild/msbuild-reserved-and-well-known-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-reserved-and-well-known-properties.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I'll make the fix.
