### ISSUE TITLE
More Information about Custom Context GUIDs

### ISSUE THREAD

**Issue by RoyMalka** [MicrosoftDocs/visualstudio-docs#1202]
https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-command-to-the-solution-explorer-toolbar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1723bf1-2209-4ea2-2072-8ea949a0585b
* Version Independent ID: 3cc58555-77e6-f50e-bb73-fdfb547b5d54
* Content: [Making Commands Available - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/making-commands-available)
* Content Source: [docs/extensibility/internals/making-commands-available.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/making-commands-available.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@RoyMalka Are you suggesting that we should link to the "Adding a command to the Solution Explorer toolbar" article from the "Making commands available" article?

**Comment by RoyMalka** [comment]
Yes I spent time to find this article and it should be linked from there to my opinion 

נשלח מה-iPhone שלי

‫ב-15 בינו׳ 2019, בשעה 1:50, ‏‏Genevieve Warren ‏<notifications@github.com> כתב/ה:‬

**Comment by gewarren** [comment]
@RoyMalka Thanks for helping us improve the docs!
