### ISSUE TITLE
ImageWatch is dead

### ISSUE THREAD

**Issue by bkietz** [MicrosoftDocs/visualstudio-docs#1203]
Either maintain ImageWatch (please! I loved using ImageWatch) or remove it as an example of UIVisualizer (its marketplace page says it doesn't even support VS 2017)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of native objects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I'll take a look at this. Thanks!

**Comment by Mikejo5000** [comment]
In the Q&A section on this ImageWatch, there's a comment pointing to the new version here:
https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.ImageWatch2017
Have you tried that?
