### ISSUE TITLE
built in text editor

### ISSUE THREAD

**Issue by gitterman** [MicrosoftDocs/visualstudio-docs#1204]
The drawback of most text editors is that you need the mouse or cursor keys to move around and manipulate things.
This is ergonomically worse than allowing to control everything with the keyboard alone.
Thus editors like emacs or vim are a superior solution.
I prefer vim as using always 2 keys to achieve an operation (meta+x) is more RSI stress than the vim model with two distinct modes (insert and command mode) which you switch with just one key.
The drawback of a pure keyboard based approach is the steeper learning curve.
All in all it pays off in speed, less coding errors and less RSI problems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb032bdf-ccea-19a3-d083-7e0466cdf332
* Version Independent ID: f794a23f-f86c-3b9e-962e-171f8e7d9aa9
* Content: [Introduction to editing in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-editor)
* Content Source: [docs/ide/quickstart-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-editor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@gitterman Thank you for this feedback about the VS editor. @markw-t @abuchholtzau for awareness.

**Comment by gewarren** [comment]
@gitterman If you want to ensure that your feedback is seen by the editor team, please log it at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) as a product issue or feature suggestion.
