### ISSUE TITLE
The priority support tile brings me to this page and not to the forum

### ISSUE THREAD

**Issue by BarrieK** [MicrosoftDocs/visualstudio-docs#1205]
According to Step 2, above, clicking on the "Get Help" link should take me to the "Priority Support in Select Microsoft Forums" page. Actually the link takes me to this page, so you get into a bit of a loop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d40a75-d2eb-44ab-656f-4ea80109c54d
* Version Independent ID: a069527e-6c7f-7d51-4aa6-82ad8be32bf1
* Content: [Priority Support Benefit in Visual Studio Subscription](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-priority-support)
* Content Source: [subscriptions/vs-priority-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-priority-support.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@BarrieK Thanks for letting us know! We'll investigate and report back.
@evanwindom Would you mind taking a look at this? Much appreciated!

**Comment by evanwindom** [comment]
@BarrieK 
@TerryGLee 
The link has been corrected to point to a list of the forums via the Support Team Blog as an interim fix.
