### ISSUE TITLE
What is AddListToSiteHelper?

### ISSUE THREAD

**Issue by Crisp771** [MicrosoftDocs/visualstudio-docs#1206]
In the line, SPList list = AddListToSiteHelper(site); in the second code snippet,  what is AddListToSiteHelper and what namespace does it live in?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 738e0793-372b-a9fd-feae-46f971652064
* Version Independent ID: 552fe8ea-6972-aa79-dbff-0b84e20a4638
* Content: [Using emulators to isolate unit tests for Sharepoint 2010 applications - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/test/using-emulators-to-isolate-unit-tests-for-sharepoint-2010-applications)
* Content Source: [docs/test/using-emulators-to-isolate-unit-tests-for-sharepoint-2010-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-emulators-to-isolate-unit-tests-for-sharepoint-2010-applications.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Crisp771 Given that this page has been removed from the Visual Studio 2017 and 2019 documentation, we are not planning to update it at this time. If you found the answer to your question, perhaps you can comment here so that others can find the answer too.
