### ISSUE TITLE
Last update date is a future date

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/visualstudio-docs#1207]
Date at the top of the page is 11/12/2018 which is in the future. 

dabu@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22a69a8-de38-2929-144a-0bd738f40a25
* Version Independent ID: a1d94b1f-c61e-df28-d412-1195aa9ace6d
* Content: [The Office 365 Developer Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office-dev)
* Content Source: [subscriptions/vs-office-dev.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-office-dev.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@dburnison Thanks for letting us know; we'll get this fixed. 
@evanwindom Could you take a look? And thanks. :)

**Comment by TerryGLee** [comment]
@dburnison This will be updated tomorrow; thanks again for bringing it to our attention. 👍
