### ISSUE TITLE
Selecting More Options in VS2015 ultimately ends up displaying these 2017 instructions

### ISSUE THREAD

**Issue by maurymarkowitz** [MicrosoftDocs/visualstudio-docs#121]
VS2015 had a rather confusing "send a frown" option that was being used for VS bug reporting. This was rather obscure, and thankfully changed to the newer language in 2017. However, as I am still on 2015, I needed instructions to find the correct option, which leads me here...

Today I wanted to report a bug in my 2015, so I selected Help->Customer Feedback Options. Not knowing which of these to select, I chose More Options. That page (url below) has a Report a Problem link right near the top. When you click on it it takes you to these 2017 instructions, and you're right where you started again.

Suggestions:

1) these instructions should have a link to previous versions of the same document

2) the main redirect page could potentially be version-aware so clicking Report a Problem takes you directly to the correct version

Here is the page in question, I hope it's the right one:

https://connect.microsoft.com/VisualStudio

**Comment by TerryGLee** [comment]
We're checking in to this. And, apologies for the late reply to that effect.

**Comment by DiablosOffens** [comment]
What's the status of this? I also need to report a bug for VS2015.

**Comment by TerryGLee** [comment]
@maurymarkowitz We've retired the Connect page where you reported a link issue. For more information, please see the following page:  [Microsoft Connect Has Been Retired](https://docs.microsoft.com/en-us/collaborate/connect-redirect)

@DiablosOffens For our previous version, consider checking out the [Developer Community for Visual Studio 2015](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+problem&type=question+OR+problem+OR+problem&c=&redirect=search%2Fsearch&sort=relevance&q=Visual+Studio+2015) page to see if your problem has already been reported. Or, check out the [How to report a problem with Visual Studio 2015](https://msdn.microsoft.com/library/mt632287.aspx).

**Comment by maurymarkowitz** [comment]
I understand that it has been retired, but that's not the problem I'm reporting, and the page you link to has no information on the topic either (the only mention is an email drop-box).
