### ISSUE TITLE
Tittle [letu]

### ISSUE THREAD

**Issue by 1123347cg119** [MicrosoftDocs/visualstudio-docs#1211]
Leave a comment, Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d662deed-71c4-5823-2af3-0a982d90d33f
* Version Independent ID: 54f94e5f-d034-dfba-070f-ed4a4e0c8063
* Content: [Deployment manifests for Office solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/deployment-manifests-for-office-solutions)
* Content Source: [docs/vsto/deployment-manifests-for-office-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/deployment-manifests-for-office-solutions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by 1123347cg119** [comment]
Title j

**Comment by gewarren** [comment]
@1123347cg119 This doesn't appear to be actionable feedback, so we are closing the issue. If I missed something, please provide more details and we can reopen the issue.

**Comment by nschonni** [comment]
@gewarren  you might have already done it, but you can use this to report spam comments and PRs https://help.github.com/articles/reporting-abuse-or-spam/#reporting-an-issue-or-pull-request

**Comment by gewarren** [comment]
@nschonni Didn't know about that, thanks!
