### ISSUE TITLE
How to resolve LNK2019 Error.

### ISSUE THREAD

**Issue by wkjau** [MicrosoftDocs/visualstudio-docs#1212]
After following the instructions on this page I receive:

error LNK2019: unresolved external symbol "int __cdecl add(int,int)" (?add@@YAHHH@Z) referenced in function "private: virtual void __thiscall TestCaseName_TestName_Test::TestBody(void)" (?TestBody@TestCaseName_TestName_Test@@EAEXXZ)
2&gt;C:\Users\wjackson\Documents\GitHub\CppProjects\TicTacToe\Debug\TicTacToeTests.exe : fatal error LNK1120: 1 unresolved externals
2&gt;Done building project "TicTacToeTests.vcxproj" -- FAILED.

How do you resolve this? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee608ee-eb3f-e95d-1eea-d9e35a6e0bc0
* Version Independent ID: daf80b3e-5bf1-652c-d6a0-602c8bc2bb0c
* Content: [How to use Google Test for C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-google-test-for-cpp)
* Content Source: [docs/test/how-to-use-google-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-google-test-for-cpp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by WillJAU** [comment]
I can not seem to find a solution on this anywhere within the testing documentation or online. Any help with this would be appreciated.

**Comment by corob-msft** [comment]
@wkjau Given that it's months later, you've probably resolved your issue, For anyone else, the top solutions for error LNK2019 are found on the [Linker Tools Error LNK2019](https://docs.microsoft.com/cpp/error-messages/tool-errors/linker-tools-error-lnk2019?view=vs-2017) page. There are many possible causes, so you need to work through the possibilities to find the one that's the cause of your error.
