### ISSUE TITLE
Commands for Components

### ISSUE THREAD

**Issue by its4zahoor** [MicrosoftDocs/visualstudio-docs#1214]
This page should also contain the commands of C++, C# and other optional installation features of the Visual Studio 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f80d9f-168b-e3cb-6499-e03a44206826
* Version Independent ID: 4b235b0d-1436-0a36-ef55-f76ba8d95bd1
* Content: [Visual Studio 2017 workload and component IDs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids)
* Content Source: [docs/install/workload-and-component-ids.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-and-component-ids.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@its4zahoor Thanks for your feedback. Might I inquire, what is it exactly that you seek? Is it workload and component information for C++, such as is listed from the links for each release (i.e., were you to click [Visual Studio Community 2017](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community), you'd see components for C++) -- or is it the command-line commands you'd use to install Visual Studio, such as is presented on the [Use command-line parameters to install Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio) page?

**Comment by TerryGLee** [comment]
@its4zahoor Feel free to comment again if you have further information for us, but we'll close this for now.
