### ISSUE TITLE
More robust options around indentation, braces?

### ISSUE THREAD

**Issue by GravenImageRD** [MicrosoftDocs/visualstudio-docs#1215]
We have a fairly odd C# coding standard to keep it similar to our C++ standard including no indentation for namespace and indenting the closing brace. The latter is one I'm not expecting support for since it is incredibly non-standard, but the former is supported for C++ formatting but not C#. Would be great if it could be supported there as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **kaseyu**

**Comment by gewarren** [comment]
@GravenImageRD You can now log feature suggestions on [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8). Could you file this suggestion over there? You'll get better traction with the product team.
