### ISSUE TITLE
broken link to supporte forum listing page

### ISSUE THREAD

**Issue by gpadvorac** [MicrosoftDocs/visualstudio-docs#1220]
this link puts me in an endless loop back to the subscriber msdn page.
I'm trying to get to the listing of supported forums shown in this page
https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-priority-support
for several weeks now.  please let me know how to find it again

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50d40a75-d2eb-44ab-656f-4ea80109c54d
* Version Independent ID: a069527e-6c7f-7d51-4aa6-82ad8be32bf1
* Content: [Priority Support Benefit in Visual Studio Subscription](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-priority-support)
* Content Source: [subscriptions/vs-priority-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-priority-support.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@gpadvorac Thanks for your feedback! We'll investigate this and report back.
@evanwindom @lankaim @prrana Is this something we can clarify/fix in the documentation?

**Comment by evanwindom** [comment]
@gpadvorac 
@TerryGLee 
The link in the tile has been redirected to a forum list on the MSDN Support Team Blog as an interim solution.  Thank you for the report.
