### ISSUE TITLE
How to probe Unity whether it has Visual Studio setup in Preference

### ISSUE THREAD

**Issue by shaochun** [MicrosoftDocs/visualstudio-docs#1221]
When Unity Preferences>External Tools>External Script Editor in Unity is not set to Visual Studio, the code 

`using SyntaxTree.VisualStudio.Unity.Bridge;`

will fail. Is there any way to get around this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3255850c-b57f-3a66-a689-333e78e822e8
* Version Independent ID: efa89608-001f-c243-64f4-ce173218b363
* Content: [Troubleshooting and Known Issues (Visual Studio Tools for Unity) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity#feedback)
* Content Source: [docs/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev15**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@shaochun we are investigating. What exactly do you wish to achieve?

**Comment by jbevain** [comment]
@shaochun the way to achieve this is to wrap that in the Unity defined constant `ENABLE_VSTU`, like this:

```csharp
#if ENABLE_VSTU
using SyntaxTree.VisualStudio.Unity.Bridge;

// ...
#endif
```

That's indeed something worth documenting.

**Comment by conceptdev** [comment]
We're looking to add this tip in the documentation too. Thanks for your feedback @shaochun.
