### ISSUE TITLE
Create a new landing page for FxCop migration in 16.0

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#1223]
Landing page should at least contain the following information:

1. Explain or have pointers to documentation on differences between legacy binary FxCop analysis and FxCop analyzers. This should include both functional and user experience differences.
2. Pointers to FxCop analyzers NuGet package and recommended analyzer versions to choose. We should consider moving the data from [here](https://github.com/dotnet/roslyn-analyzers#recommended-version-of-analyzer-packages) into its own section on docs.microsoft.com.
3. We need to explicitly mention that analyzers execute automatically as part of build and don't need "RunCodeAnalysis" MSBuild property or "Run Code Analysis" VS command to be executed. Users still seem to be confused here as they always end up executing run code analysis command even after installing FxCop analyzers. We should also mention:
    1.  New error message that we will show in Dev16 P1 from VS and command line when users attempt to do invoke RunCodeAnalysis (possibly with a mention of MSBuild property that can be set to suppress this error).
    2. We are likely to remove this VS command and deprecate the MSBuild property in subsequent VS release.
4. Command line behavior: Most of our existing documentation on the analyzers/FxCop analyzers focuses on VS IDE experience, which is expected. However, given that binary FxCop was invocable from command line as a post-build MSBuild task, our documentation on migration should also explain the new experience with FxCop analyzers from command line.
5. FxCop Rulesets: Binary FxCop shipped with various rulesets that enabled users to easily configure minimum/recommended/all rules for their projects. These rulesets cannot be used as-is with FxCop analyzers due to differences in defaults. To enable easier migration for legacy FxCop customers that use these rulesets, we ship our FxCop analyzer NuGet packages with equivalent rulesets and more (see https://github.com/dotnet/roslyn-analyzers/pull/1718). We should document this and probably also have a simple example showing mapping between old and new ruleset.

We need to create an fwlink for this landing page upfront so that our migration related diagnostic messages in VS IDE and the post-build FxCop task can redirect customers to this page.

**Comment by mavasani** [comment]
Tagging @gewarren @jinujoseph @kuhlenh

**Comment by gewarren** [comment]
@mavasani when do you need the link by?

**Comment by mavasani** [comment]
Sooner the better, but it is not super urgent. We need to have the error messages blocking binary FxCop in Dev16.0 P1, and these messages would need to embed this link.

**Comment by gewarren** [comment]
Not everything that Manish requested is there yet, but here's the (live) landing page: https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers

**Comment by gewarren** [comment]
I believe all this work has been completed now.
