### ISSUE TITLE
Where does MSBuild look for implicit imports?

### ISSUE THREAD

**Issue by Jazzman123** [MicrosoftDocs/visualstudio-docs#1225]
This says that the Sdk attribute/element is used "to create implicit Import statements that are added to the .proj file."  Where can I get more detail on how this works?  Based on the value of Sdk, what path and filename will MSBuild be importing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2d4b23-f7b9-7f95-0690-7d528fb4b323
* Version Independent ID: 2c45725e-2689-bfd3-001b-ea1f7043128a
* Content: [Project Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/project-element-msbuild)
* Content Source: [docs/msbuild/project-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/project-element-msbuild.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Hi, did you already find this topic? https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk
There's a section on how the project SDKs are resolved. There are links to additional .NET topics for the Sdk element at the bottom of the page.

**Comment by Jazzman123** [comment]
I hadn’t seen that page before.  Thanks; that’s very helpful.  I do wish there was more detail on SDK resolvers—how does the resolution process work? How does it decide which folder to look for sdk.props/targets?
But thanks for pointing me to this page.  It still has lots of useful information.

________________________________
