### ISSUE TITLE
Documentation missing details on how to compile / link binaries such that VSInstr can process them

### ISSUE THREAD

**Issue by paddymcd-MSFT** [MicrosoftDocs/visualstudio-docs#1226]
Can't find any details on this page or searching docs.microsoft.com on what compiler / linker switches are required in order for VSInstr to be able to instrument a binary for a profile session

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aba0d313-eb56-c062-8e1f-9e51b784a236
* Version Independent ID: 789474e7-3460-28a1-ee95-d8c582d9b0a0
* Content: [VSInstr - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/vsinstr)
* Content Source: [docs/profiling/vsinstr.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/vsinstr.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Closing this as using VSIntr is deprecated (VS 2017 only). In VS 2019, there is an Instrumentation tool (Debug > Performance Profiler, choose Instrumentation).
For a little info on the changes, see: https://docs.microsoft.com/en-us/visualstudio/profiling/profiling-feature-tour?view=vs-2019#analyze-performance-legacy-tools

**Comment by macdew** [comment]
Even though this is closed, in VS2022 my application fails to profile due to:

Unable to instrument this binary.  This may be due to a malformed binary or a compiler feature VsInstr doesn't support.
[BB0113]

This is via the Debug -> Performance Profiler dialog.  So this path is definitely still triggering the same error as in the original post.

**Comment by plade** [comment]
```
d:\UnmanagedTest\ConsoleApplication\x64\Debug>dir
 Volume in drive D is DATADRIVE1
 Volume Serial Number is DEE3-6E71

 Directory of d:\UnmanagedTest\ConsoleApplication\x64\Debug

09/26/2022  12:17 PM    <DIR>          .
09/26/2022  12:16 PM    <DIR>          ..
09/26/2022  12:17 PM    <DIR>          ConsoleA.80bcd3ce.tlog
09/26/2022  12:17 PM            67,072 ConsoleApplication.exe
09/26/2022  12:17 PM               311 ConsoleApplication.exe.recipe
09/26/2022  12:17 PM           656,800 ConsoleApplication.ilk
09/26/2022  12:17 PM             6,102 ConsoleApplication.log
09/26/2022  12:17 PM            71,614 ConsoleApplication.obj
09/26/2022  12:17 PM         1,241,088 ConsoleApplication.pdb
09/26/2022  12:17 PM                70 ConsoleApplication.vcxproj.FileListAbsolute.txt
09/26/2022  12:17 PM           158,720 vc143.idb
09/26/2022  12:17 PM           397,312 vc143.pdb
               9 File(s)      2,599,089 bytes
               3 Dir(s)  211,304,873,984 bytes free

d:\UnmanagedTest\ConsoleApplication\x64\Debug>ConsoleApplication.exe
Hello World!

d:\UnmanagedTest\ConsoleApplication\x64\Debug>microsoft.codecoverage.console instrument ConsoleApplication.exe
Unable to instrument this binary.  This may be due to a malformed binary or a compiler feature VsInstr doesn't support.

d:\UnmanagedTest\ConsoleApplication\x64\Debug>which microsoft.codecoverage.console
'which' is not recognized as an internal or external command,
operable program or batch file.

d:\UnmanagedTest\ConsoleApplication\x64\Debug>where microsoft.codecoverage.console
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Microsoft\CodeCoverage.Console\Microsoft.CodeCoverage.Console.exe
```

Freshly built default C++ ConsoleApplication from Visual Studio 2022 also gives the same error message when trying to instrument the binary using Microsoft.CodeCoverage.Console.

**Comment by rtosman** [comment]
Yes, this should not be closed.  Dynamic instrumentation does not apply to C/C++ native executables, and VSInstr is the only way that instrumentation can (theoretically) work.
