### ISSUE TITLE
Reset from Visual Studio to default settings from IDE

### ISSUE THREAD

**Issue by windson** [MicrosoftDocs/visualstudio-docs#1227]
Launch Visual Studio 2017 (may be same with 2015)
Menu
-&gt; Tools 
-&gt; Import and Export Settings... 
-&gt; Select 'Reset all settings' radio button
-&gt; Next
-&gt; Select 'No, just reset settings, overwriting my current settings' radio button if you want to reset VS to a fresh install settings
-&gt; Choose 'General' or setting you want to restore to.
-&gt; Finish

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3151203e-b627-3e43-b05e-51f46edc71bd
* Version Independent ID: a9633d15-154e-0d19-16d3-60432f0e6f98
* Content: [-ResetSettings (devenv.exe) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/resetsettings-devenv-exe)
* Content Source: [docs/ide/reference/resetsettings-devenv-exe.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/resetsettings-devenv-exe.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@windson Thanks, this is a useful cross-reference to an alternative way of resetting.
