### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by altimmons** [MicrosoftDocs/visualstudio-docs#1228]
I have been searching how to open code documentation within VS.  It must be possible. It that feature not discussed anywhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6094a598-a7b5-b696-eb4e-fcd4adf4485b
* Version Independent ID: 53cd9992-470f-0a0f-f251-65a06606b9c2
* Content: [Advanced features of Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/advanced-feature-overview)
* Content Source: [docs/ide/advanced-feature-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/advanced-feature-overview.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@altimmons Do you mean how to go directly to help for, e.g., a programming language keyword, or how to open help documentation within VS itself as opposed to in a browser? If the former, you position your cursor on the keyword and press F1. If the latter, this article should help: https://docs.microsoft.com/visualstudio/ide/microsoft-help-viewer

**Comment by gewarren** [comment]
Please leave a comment if this doesn't address your question.
