### ISSUE TITLE
Newer tags for microsoft/dotnet-framework switch the SHELL

### ISSUE THREAD

**Issue by heaths** [MicrosoftDocs/visualstudio-docs#1230]
If people use newer tags for `microsoft/dotnet-framework` (like `4.7.2-sdk-windowsservercore-1803`) the Dockerfile in the basic page will not work because it depends on batch processing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@heaths Thanks for the input; @gewarren have you run in to this?

**Comment by heaths** [comment]
I actually already fixed this, but did the PR all in the other repo. I keep forgetting we have two separate ones.
