### ISSUE TITLE
ASP.NET Core 2.0 IIS Running

### ISSUE THREAD

**Issue by Allann** [MicrosoftDocs/visualstudio-docs#1231]
This also occurs on a subsequent run of a solution when IIS Express was still running from the previous debug session.  
Setup I am using is an ASP.NET MVC Core 2.0 and a WebAPI Core 2.0 project, both set as start with debugging enabled.  Neither references the other, but MVC calls Api via url (using Flurl).
For whatever reason IIS Express does not shutdown when you stop debugging, when you then restart another debug session, you will get this error and the WebAPI project fails to start.  Mvc starts correctly, but obvious fails on calls to the API as it doesn't start.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfd7078-683e-9fd6-247b-e75d4ed16a32
* Version Independent ID: ae3300c4-55a8-59b6-846b-50c48c88dcfe
* Content: [Error: Evaluating the function 'function' timed out and needed to be aborted in an unsafe way - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.unsafe_func_eval_abort)%3Bk(DevLang-dhtml)%26rd%3Dtrue)
* Content Source: [docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
See #831 Please use the Send Feedback link > Report a Problem for this issue.
