### ISSUE TITLE
Lots of love for TFVC, but lacking on TFS

### ISSUE THREAD

**Issue by lclaytont** [MicrosoftDocs/visualstudio-docs#1232]
TFS information is not represented. In the source control explorer I cannot get any context actions to show up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [TF Version Control - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by asb3993** [comment]
@lclaytont thanks for report! What happens you you try to click on a mapped folder in the solution explorer?

**Comment by asb3993** [comment]
Closing this as it seems to be more of a product issue, which should be filed [here](https://developercommunity.visualstudio.com/spaces/41/index.html). If there is anything that should be updated in the docs, please feel free to reopen.
