### ISSUE TITLE
nuget

### ISSUE THREAD

**Issue by bqstony** [MicrosoftDocs/visualstudio-docs#1233]
how it works with a nuget package like xunit?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c7c36c-84d9-9237-3d78-689e76d080f9
* Version Independent ID: 6584735a-e8db-429d-5427-687fc709e6f8
* Content: [Walkthrough: Create a code snippet - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet)
* Content Source: [docs/ide/walkthrough-creating-a-code-snippet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-creating-a-code-snippet.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Mikejo5000** [comment]
I don't believe this is supported natively, but snippets would need to be included with the NuGet packages. See this issue:
https://github.com/NuGet/Home/issues/7758
