### ISSUE TITLE
Can't Link

### ISSUE THREAD

**Issue by philippecp** [MicrosoftDocs/visualstudio-docs#1238]
With Visual Studio 15.7.5 I get the following error:
fatal error C1047: The object or library file 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\VS\lib\x64\VSCustomNativeHeapEtwProvider.lib' was created with an older compiler than other objects; rebuild old objects and libraries

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1493402f-5aef-24a2-ad7d-d508e4e1e72d
* Version Independent ID: 4a689fe8-6e96-1162-3070-fba2277a0ac5
* Content: [Custom Native ETW Heap Events - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/custom-native-etw-heap-events)
* Content Source: [docs/profiling/custom-native-etw-heap-events.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/custom-native-etw-heap-events.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@andysterland Andy, is there someone to advise on this? Thanks

**Comment by Mikejo5000** [comment]
@philippecp 
Hi, we are going through old issues. This looks like a support request. If it's still an issue, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
