### ISSUE TITLE
Clarify how to use BindingContext

### ISSUE THREAD

**Issue by vanderleipires** [MicrosoftDocs/visualstudio-docs#1239]
Will help if a note is added informing how to configure binding, for example: "To bind property [Temperature] to respective value we should insert a label in the format &lt;Label Text="{Binding Temperature}" ...&gt;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b25d4cd-0c3f-e9a6-6256-ea54d0972d4b
* Version Independent ID: babd49b7-8e18-13dc-99f2-6783495cb0dc
* Content: [Learn app-building basics with Xamarin.Forms in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio)
* Content Source: [docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
Please refer to the [XAML Basics](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/) documentation, which has a number of pages on binding. The syntax is largely the same as WPF and UWP, and it is our expectation that many readers will be familiar with this before they start working with Xamarin.

**Comment by rgreen88** [comment]
Well, that's a bit irresponsible to assume that isn't it? I'm sure I'll figure it out eventually, but I would imagine that it probably doesn't take no more than half of your first line for an explanation on basic BindingContext when starting an app.

**Comment by rgreen88** [comment]
Ah forgive me for not noticing the App.xaml.cs file. You can control the file launch page from there. The XAML Basics documentation gives a nice detailed explanation on binding. I haven't worked with binding much so thanks for the documentation above.

**Comment by tomeberhard** [comment]
@conceptdev Thank you for the tutorial, it's very useful. Agreeing with rgreen88: Your expectation regarding reader familiarity with WPF and UWP bindings is incorrect, at least in my case as well. This is my 2nd Xamarin tutorial, so it's very helpful to have the explanation of how to setup the bindings.

**Comment by conceptdev** [comment]
Thanks for the feedback in this thread. From what I can understand, the commenters above are unblocked for now. We are taking the suggestions about when & how to introduce data-binding on board for future updates of these docs.
