### ISSUE TITLE
Not updated for vs2017 and its private registry hive

### ISSUE THREAD

**Issue by r3m0t** [MicrosoftDocs/visualstudio-docs#1241]
Regedit doesn't show the contents of the private hive

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda15bb6-a9d7-fbc7-fa47-c75ac51ccc88
* Version Independent ID: f0c858f7-c1fa-4c06-c394-d0de661ed7ee
* Content: [Writing to the User Settings Store - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/extensibility/writing-to-the-user-settings-store)
* Content Source: [docs/extensibility/writing-to-the-user-settings-store.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/writing-to-the-user-settings-store.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by FurkanKambay** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/breaking-changes-2017?view=vs-2017#visual-studio-registry

**Comment by dksimpson** [comment]
The Visual Studio registry backup instructions no longer apply and have been removed from the article. Closing issue.
