### ISSUE TITLE
In what component of VS is that editor?

### ISSUE THREAD

**Issue by mpalladinru** [MicrosoftDocs/visualstudio-docs#1245]
What component should be installed for that editor to appear? I don't have it in "Open with..." menu and I don't have "Graphics" item at "Add new item..." menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa613491-943f-f0b4-f4ea-90e09f96f669
* Version Independent ID: ae52c49c-93b9-b907-5925-fff11e6cd324
* Content: [Shader Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/shader-designer)
* Content Source: [docs/designers/shader-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/shader-designer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mpalladinru You probably need the **Image and 3D model editors** component. Try following the steps in the blue box in this section and see if that gives you the graphics features you need. https://docs.microsoft.com/en-us/visualstudio/designers/model-editor#to-add-a-3d-model-to-your-project

**Comment by gewarren** [comment]
@prnadago Pratik, do you know which project types you can add 3D scenes (.fbx) and Visual Shader Graphs (.dgsl) to? And do you know why they can't be added to a WPF project?

**Comment by gewarren** [comment]
@mpalladinru You make a great point. I clarified with the product team that the shader and 3D scenes items are only supported for C++ projects. I'm updating the topic with this info.
