### ISSUE TITLE
Displaying Light Bulb Suggestions has null reference check bug (typo)

### ISSUE THREAD

**Issue by jselbie** [MicrosoftDocs/visualstudio-docs#1247]
On this page [Github here](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-light-bulb-suggestions.md) and [on MSDN](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-light-bulb-suggestions).

The following code sample:
```
public ISuggestedActionsSource CreateSuggestedActionsSource(ITextView textView, ITextBuffer textBuffer)  
{  
    if (textBuffer == null && textView == null)  
    {  
        return null;  
    }  
    return new TestSuggestedActionsSource(this, textView, textBuffer);  
} 
```

Should likely be:

```
public ISuggestedActionsSource CreateSuggestedActionsSource(ITextView textView, ITextBuffer textBuffer)  
{  
    if (textBuffer == null || textView == null)  
    {  
        return null;  
    }  
    return new TestSuggestedActionsSource(this, textView, textBuffer);  
} 
```

The TestSuggestedActionsSource assumes that both textBuffer and textView passed in are valid references.  I was initially confused when I saw this because I thought the ISuggestedActionsSource was expected to have two different behaviors (one for a textView and another for a textBuffer).  When in fact, it simply needs both.

I submitted a pull request as well.

#1246

**Comment by gregvanl** [comment]
Thanks! I've approved your PR and it should be merged and published shortly.
