### ISSUE TITLE
Missing step to run C++ unit tests?

### ISSUE THREAD

**Issue by david-toro** [MicrosoftDocs/visualstudio-docs#1248]
After following this guide in every detail occurs the error "LNK2019: unresolved external symbol...", apparently the test project can not find the binary of the source file corresponding to the class being tested, after researching a bit in the web, i think that the simplest solution is to add the cpp file to the test project (context menu of test project -> "Add" -> "Existing Item ..."), after that extra step you can run unit tests without errors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18bdf17-06e1-aaf2-b6ce-c606c0e260da
* Version Independent ID: bd627b8f-54f0-84e0-55cd-285597af022d
* Content: [Write unit tests for C/C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp)
* Content Source: [docs/test/writing-unit-tests-for-c-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/writing-unit-tests-for-c-cpp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by JasonFevang** [comment]
I tried this and it got me one step further, but on the added .cpp file I now get C1010, "unexpected end of file while looking for precompiled header. Did you forget to add '#include "stdafx.h"' to your source?" Any ideas why?

**Comment by JasonFevang** [comment]
Adding #include "stdafx.h" gives even more errors

**Comment by JasonFevang** [comment]
I solved my problem, I needed to follow the instructions on this document: https://msdn.microsoft.com/en-us/library/hh419385.aspx?f=255&MSPPError=-2147217396#projectRef following the "To link the tests to the object or library files" instructions

**Comment by gewarren** [comment]
The info that needs to be linked to can be found here: https://docs.microsoft.com/en-us/visualstudio/test/unit-testing-existing-cpp-applications-with-test-explorer?view=vs-2015#objectRef.

**Comment by dksimpson** [comment]
I updated the article by adding a link to the instructions for adding obj and lib files. Thanks for reporting this issue.

**Comment by Bortronx** [comment]
Hello. 
I followed step by step of C++ unit tests and I get a "error LNK2019: unresolved external symbol" Using Google Test as the test project. 

As depicted here: https://docs.microsoft.com/en-us/visualstudio/test/unit-testing-existing-cpp-applications-with-test-explorer?view=vs-2015#objectRef.

Any tips would be greatly appreciated.

I created a test project to assure me it wasn't my C++ solution. See my test project:
https://github.com/Bortronx/ta1_project

I get the following error:
`_error LNK2019: unresolved external symbol "public: int __thiscall DataContainer::GetContainerCount(void)" (?GetContainerCount@DataContainer@@QAEHXZ) referenced in function "private: virtual void __thiscall DataContainerTest_GetDataContainer_Test::TestBody(void)" (?TestBody@DataContainerTest_GetDataContainer_Test@@EAEXXZ)_`
