### ISSUE TITLE
Override default keybinding?

### ISSUE THREAD

**Issue by hacksoi** [MicrosoftDocs/visualstudio-docs#1249]
How would one go about overriding a default VS keybinding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03642526-b5f8-c874-6bc8-ecb7d4ebb239
* Version Independent ID: d26304d6-a361-5b33-6103-410d597c626c
* Content: [Binding Keyboard Shortcuts to Menu Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/binding-keyboard-shortcuts-to-menu-items)
* Content Source: [docs/extensibility/binding-keyboard-shortcuts-to-menu-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/binding-keyboard-shortcuts-to-menu-items.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @hacksoi You can use the Tools > Options > Environment > Keyboard dialog to override the default keybindings. 

![image](https://user-images.githubusercontent.com/12818376/42741343-2ba64682-8866-11e8-8fba-b1e69c27e9d0.png)
