### ISSUE TITLE
Typo in documentation for the Quick Shortcut

### ISSUE THREAD

**Issue by zuluonezero** [MicrosoftDocs/visualstudio-docs#1251]
"... the Quick MonoBehavior wizard puts them right at your fingertips. Press CTRL+ALT+Q."  should be CRTL + SHIFT + Q

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27057a9-85be-f96c-29aa-0fa60b488f35
* Version Independent ID: cd80ccea-8ecd-d21f-08b8-af0a2ada7cf3
* Content: [Overview of Visual Studio Tools for Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/overview-of-visual-studio-tools-for-unity)
* Content Source: [docs/cross-platform/overview-of-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/overview-of-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev15**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by dantogno** [comment]
Hey @zuluonezero. This feature has actually been removed in the latest version of Visual Studio Tools for Unity, now that we have IntelliSense support for the Unity API. We're working on updating the documentation to reflect this. Thanks for the feedback!

**Comment by dantogno** [comment]
@zuluonezero We've just finished a fairly large overhaul of the VSTU docs, including addressing this issue. Take a look at your convenience! https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-studio-tools-for-unity
