### ISSUE TITLE
Forever clueless -> Microsoft

### ISSUE THREAD

**Issue by dexception** [MicrosoftDocs/visualstudio-docs#1252]
As usual Microsoft seems to be clueless about the developer community. Not giving ISO just makes me want to switch to Linux completely. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an Offline Installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@dexception We appreciate your feedback. There is one specific GitHub Issue previously tendered to this topic that if you haven't already read it, you might want to take a look at it now: [https://github.com/MicrosoftDocs/visualstudio-docs/issues/607](https://github.com/MicrosoftDocs/visualstudio-docs/issues/607). Specifically, it includes a comment from @tedvz as to the reasons why chose not to release an ISO for Visual Studio 2017.

**Comment by dexception** [comment]
@TerryGLee 
Moved to Linux and loving every bit of it.
