### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by relief12** [MicrosoftDocs/visualstudio-docs#1257]
Will this work if I use Xamarin Android?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0686fa95-cbeb-1f4d-ceca-80c04255fb0e
* Version Independent ID: 68f4a465-066f-5cb8-ed0c-346dc9d38bd1
* Content: [Walkthrough: Creating a simple WCF Service in Windows Forms - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/walkthrough-creating-a-simple-wcf-service-in-windows-forms)
* Content Source: [docs/data-tools/walkthrough-creating-a-simple-wcf-service-in-windows-forms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/walkthrough-creating-a-simple-wcf-service-in-windows-forms.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@charlespetzold do you know if you can create a WCF service in a Xamarin app?

**Comment by conceptdev** [comment]
We have a page and sample for WCF and Xamarin: [Consuming a WCF service (in Xamarin)](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/data-cloud/consuming/wcf). Note that only BasicHttpBinding is supported.
