### ISSUE TITLE
Make suggested improvements to msbuild-task doc around properties

### ISSUE THREAD

**Issue by geeeyetee** [MicrosoftDocs/visualstudio-docs#1258]
1. Sections _Properties Metadata_ and _AdditionalProperties Metadata_ : Clarify that the difference between `Properties` metadata and `AdditionalProperties` metadata is that the presence of `Properties` metadata causes the `MSBuild` task to ignore its `Properties` attribute value.

1. Section _Parameters_ : Clarify the phrase "different global properties" in the sentence below. I observe consistent global properties behavior regardless of whether the `MSBuild` task passes no properties, passes properties using the `Properties` attribute, passes properties using `Properties` metadata or passes properties using `AdditionalProperties` metadata. In each case the called project receives the calling project's global properties, and any changes to those properties that the called project makes are not conveyed to the calling project.
_"When a new instance of the project has been created, MSBuild treats it as a different project that has different global properties and that can be built in parallel with other instances of the project."_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ae888a-0777-7e09-cd0c-c864df8376db
* Version Independent ID: 29dd0025-ff74-ec07-ad71-4a75a276d8d8
* Content: [MSBuild Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-task)
* Content Source: [docs/msbuild/msbuild-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, do these updates seem reasonable?

**Comment by rainersigwald** [comment]
I have a half-written doc talking about some of these here: https://gist.github.com/rainersigwald/1fbd21a24a41b9b7c6204cb9cfcbb1cf

Until I get around to finishing that, I think these are some good suggestions.

1. Yes, something like "when specified, `Properties` metadata overrides the task's `Properties` parameter, while `AdditionalProperties` are appended to the parameter's definitions" would be really nice here.
2. Not sure of a succinct way to say this. What happens is, MSBuild will have a single project instance for a given project path + unique set of global properties. So only setting never-before-seen-in-the-build properties will create a new instance. But that's the whole point of passing properties; all of the examples given elsewhere are good, but you can (for instance) have multiple MSBuild tasks call `foo.proj`, with `Configuration=Release` and they will get single-instanced.

@Mikejo5000 think you can massage that into something readable? I can expand at greater length and with diagrams if it'd help :)

**Comment by Mikejo5000** [comment]
For #2, what about this?
MSBuild creates a single project instance for a given project path and a unique set of global properties. For example, this behavior allows you to create multiple MSBuild tasks that call *myproject.proj*, with Configuration=Release and you get a single instance of *myproject.proj* (if no unique properties are specified in the task). If you specify a property that has not yet been seen by MSBuild, MSBuild creates a new instance of the project, which can be built in parallel to other instances of the project. For example, a Release configuration can build at the same time as a Debug configuration.

**Comment by Mikejo5000** [comment]
Updating the docs. Thanks!

**Comment by geeeyetee** [comment]
Thank you very much, @rainersigwald, @Mikejo5000 and @gewarren!
