### ISSUE TITLE
Only for Managed Builds

### ISSUE THREAD

**Issue by SamuelEnglard** [MicrosoftDocs/visualstudio-docs#1260]
It should be noted somewhere that this only works for Managed builds. VC++ does not call these targets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build#feedback)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, I'll make that change.

**Comment by socholo** [comment]
I also agree with this comment - I think it is an important change to make. After reading the document, I thought "wow, I need to start using this", but fortunately I read this comment that indicates the functionality is *not* available for native (C++) builds so I didn't end-up wasting my time.
