### ISSUE TITLE
Missing step: helm init

### ISSUE THREAD

**Issue by y6nH** [MicrosoftDocs/visualstudio-docs#1261]
Publishing to AKS, I got the error `Could not find tiller`. To get it working, I had to run `helm init` in PowerShell. I then ran `helm ls`, which opened a prompt to allow Helm through the Windows firewall. I think the init step needs to be added to the instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools)
* Content Source: [docs/deployment/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-kubernetes-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
I've updated the doc with more explicit instructions, @y6nH thanks for your suggestion!
