### ISSUE TITLE
Useless script for installing required certificates

### ISSUE THREAD

**Issue by brettjacobson** [MicrosoftDocs/visualstudio-docs#1264]
The "batch" file (cmd) above in Option 3 (https://docs.microsoft.com/en-us/visualstudio/install/install-certificates-for-visual-studio-offline#option-3---install-certificates-as-part-of-a-scripted-deployment-of-visual-studio) is using a dependency (certmgr.exe) that you only have on your machine, after you have installed Visual Studio.  Since this is documentation for installing Visual Studio, OBVIOUSLY you do not yet have this tool thus you cannot use that script to install the certificates. Its a chicken and egg problem.  Please rewrite Option 3 to use built in OOTB PowerShell instead of relying on a Visual Studio tool!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e4bce72-0471-4ff0-6948-671f2e1f9f9f
* Version Independent ID: 3a255b89-a741-5bcc-4342-e4e4943197e1
* Content: [Install certificates required for Visual Studio offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-certificates-for-visual-studio-offline#feedback)
* Content Source: [docs/install/install-certificates-for-visual-studio-offline.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-certificates-for-visual-studio-offline.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@brettjacobson Thanks for your feedback; we appreciate it! Your request is on record and in the queue. We'll report back on its status, soon.

**Comment by brettjacobson** [comment]
I'm not sure how correct this is, but this is what I'm using
```powershell
Import-PfxCertificate -FilePath .\certificates\manifestSignCertificates.p12 -CertStoreLocation Cert:\LocalMachine\CA
Import-PfxCertificate -FilePath .\certificates\manifestSignCertificates.p12 -CertStoreLocation Cert:\LocalMachine\Root
Import-PfxCertificate -FilePath .\certificates\manifestCounterSignCertificates.p12 -CertStoreLocation Cert:\LocalMachine\CA
Import-PfxCertificate -FilePath .\certificates\manifestCounterSignCertificates.p12 -CertStoreLocation Cert:\LocalMachine\Root
Import-PfxCertificate -FilePath .\certificates\vs_installer_opc.SignCertificates.p12 -CertStoreLocation Cert:\LocalMachine\CA
Import-PfxCertificate -FilePath .\certificates\vs_installer_opc.SignCertificates.p12 -CertStoreLocation Cert:\LocalMachine\Root
```

**Comment by TerryGLee** [comment]
@tydunkel FYI on this.

**Comment by TerryGLee** [comment]
@tydunkel A quick reminder of this issue; we'll want to add some PowerShell scripts to the page.

**Comment by tydunkel** [comment]
> @tydunkel A quick reminder of this issue; we'll want to add some PowerShell scripts to the page.

@TerryGLee thanks, we have this on our backlog and will update in the near future.

**Comment by tydunkel** [comment]
The doc has been updated to use certutil.exe which ships with Windows. #please-close
