### ISSUE TITLE
--wait help for layout installations

### ISSUE THREAD

**Issue by taylorbindon** [MicrosoftDocs/visualstudio-docs#1266]
Could the support article be updated to explicitly state that the --wait parameter must be used immediately after the executable. Eg. vs_Professional.exe --wait --norestart. Just to make it a little less ambiguous.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@taylorbindon Thanks for your feedback; we appreciate it! Your request is on record and in the queue. We'll report back soon.

**Comment by mrweiland** [comment]
How can this important change take so long time to fix? Without this little parameter --wait it just dont work. So please update for all developers out there that missing to add this... like for me.

**Comment by tydunkel** [comment]
@taylorbindon I'm not sure I understand the request here. The `--wait` option can be provided anywhere in the list of args passed to `vs_enterprise.exe`.

e.g. `vs_enterprise.exe --norestart --wait` is equivalent to `vs_enterprise.exe --wait --norestart`

When you were hitting issues, were you seeing this to not be the case? I verified with the latest installer from https://www.visualstudio.com/downloads that the order does not matter.

A common issue when writing scripts, particularly with powershell, is not instructing the script to also wait until the process exits before continuing. If you use the `Start-Process` command in powershell you will also need the `-Wait` flag to prevent the script from continuing until the process exits.

**Comment by taylorbindon** [comment]
Hey @tydunkel I definitely shouldn't have been so hasty to attribute it to the position of the argument, my bad. I was using Packer, and provisioning with Powershell, to create an updated image with software pre-installed. From memory, I tried with and without `Start-Process`. I'll see if I can reproduce the error soon, this was almost six months ago, not sure if something might have changed or if it's plain old operator error.

Failed
`& vs_Professional.exe --layout vs2017layout --add "components" --includeRecommended --lang en-US --wait`

Failed
`Start-Process -Wait -FilePath "vs_Professional.exe" -ArgumentList "--layout vs2017layout --add "components" --includeRecommended --lang en-US --wait"`

**Comment by TerryGLee** [comment]
@taylorbindon I'm going to close this issue now; if you do get a chance to see if you can reproduce the error and want to report back, we'll reopen it then.
