### ISSUE TITLE
Load/Performance testing on-premises?

### ISSUE THREAD

**Issue by Bebo2345** [MicrosoftDocs/visualstudio-docs#1269]
So is the only way to do load/performance testing on-premises is with 2013 Update 5 controller and agents? Documentation isn't definitive.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6edb165c-eeda-64cd-f34f-459f48ff9cb2
* Version Independent ID: 50e6d9fe-e48b-0824-bd9b-6a58e1482ab9
* Content: [Install test agents and test controllers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/lab-management/install-configure-test-agents?view=vsts)
* Content Source: [docs/test/lab-management/install-configure-test-agents.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/lab-management/install-configure-test-agents.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@boraprachi Can you help to answer this question?

**Comment by gewarren** [comment]
@alexhomer1 This is a question about the line in [this table](https://docs.microsoft.com/en-us/visualstudio/test/lab-management/install-configure-test-agents?view=vs-2017#upgrade-from-visual-studio-2013-test-agents) for TFS/Azure Test Plans alternatives. Can you answer it?

**Comment by gewarren** [comment]
@PBoraMSFT Can you help to answer this question?

**Comment by PBoraMSFT** [comment]
@Bebo2345 - we did not ship Test controller/agents (TC/TA) in the VS 2015 release. So the doc outlines that you should use 2013 TC/TA. However, later releases of VS (2017 and now 2019), did ship with the TC/TA SKU and you can use those for on-premises load testing.

**Comment by Bebo2345** [comment]
Excellent! Thank you!
