### ISSUE TITLE
Lenght of benefit

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#1270]
Hello,

I understand this benefit is included within the subscription however is this linked to the subscription status? I would like more clarification as to when this benefit expires or if I have to pay for it after the subscription expires, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22a69a8-de38-2929-144a-0bd738f40a25
* Version Independent ID: a1d94b1f-c61e-df28-d412-1195aa9ace6d
* Content: [The Office 365 Developer Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office-dev)
* Content Source: [subscriptions/vs-office-dev.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-office-dev.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@Nathan-Tarin -- Thanks for your question.  The Office 365 Developer benefit is set to automatically renew as long as your subscription is active.  If your subscription expires, you have the option to purchase the service.
