### ISSUE TITLE
test

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#1271]
testing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* Content: [Overview of Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide)
* Content Source: [docs/ide/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-ide.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gosali** [comment]
@gewarren Can we close this issue?
CC @Sara-Nicolini , @nokura

**Comment by gewarren** [comment]
@SarikaCalla just testing, please ignore. I wanted to see if we can @mention Microsoft GitHub accounts that aren't part of MicrosoftDocs org.
