### ISSUE TITLE
gps

### ISSUE THREAD

**Issue by leifpe** [MicrosoftDocs/visualstudio-docs#1273]
[Skriv din feedback här]

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 38035aeb-b80c-dc79-47bf-e7e114c07fe1
* Version Independent ID: 4f0ed253-d5b4-dd06-216e-e24b9a37e8db
* Content: [Unblock the remote tools download - Visual Studio](https://docs.microsoft.com/sv-se/visualstudio/debugger/remote-debugging-unblock-file-download)
* Content Source: [docs/debugger/remote-debugging-unblock-file-download.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-unblock-file-download.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by TerryGLee** [comment]
@leifpe Tack för din feedback; kan du ange mer information om doc-problemet som vi kan hjälpa dig med? (@Mikejo5000 - FYI.)
