### ISSUE TITLE
gps

### ISSUE THREAD

**Issue by leifpe** [MicrosoftDocs/visualstudio-docs#1274]
[Skriv din feedback här]

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 75c19e4f-4623-c462-e399-008a85ea1523
* Version Independent ID: bc0b82bb-acc8-7438-7b18-5165de39d847
* Content: [Remote Debugger Port Assignments - Visual Studio](https://docs.microsoft.com/sv-se/visualstudio/debugger/remote-debugger-port-assignments)
* Content Source: [docs/debugger/remote-debugger-port-assignments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugger-port-assignments.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by TerryGLee** [comment]
@leifpe FYI: Avslutande eftersom detta är en dubblett av en tidigare Inlämnad fråga.
