### ISSUE TITLE
Installation paths are greyed out and unable to be changed

### ISSUE THREAD

**Issue by trosel** [MicrosoftDocs/visualstudio-docs#1275]
Hey all, this article is very helpful except that nothing can be changed in these install paths.

Even in the screenshot, it shows the greyed out install locations that can't be changed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f065a76a-2046-ebfd-2aa2-ebb0afbc4110
* Version Independent ID: f3501eb1-bfa1-1c2e-9e05-bc0f1fa8971d
* Content: [Change installation locations in Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/change-installation-locations)
* Content Source: [docs/install/change-installation-locations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/change-installation-locations.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@WildYorkies Thanks for your feedback; we appreciate it. Question: Are you trying to modify a previous installation? If so, please know that the **Installations locations** feature works only for *new* installations of Visual Studio. That being said, we can update the page to make this clearer, and we can update the screenshot accordingly.

**Comment by WildYorkies** [comment]
Thanks @TerryGLee . I'm trying to change the install location for _new_ packages. For example, I don't want 20 gigs of xamarin files going on my C drive. I want them on my D drive instead.

However, because the locations are greyed out, I cannot change them. Not sure why.

**Comment by Mayitzin** [comment]
I'm having the same problem. I already have the core installation of Visual Studio in my second drive (D), but the extra tools (Xamarin, dotnet, etc.) are set for my main drive (C) and cannot change them.

**Comment by jrhawley** [comment]
I have the same issue. I'd like to move the "Shared Components" location to a different hard drive, but it's just greyed out and I can't change it, without uninstalling/reinstalling Visual Studio entirely

**Comment by benjisanders** [comment]
$o the clear micro$oft $olution is to download the profe$$ional (or higher) ver$ion.  Way to go micro$oft.

**Comment by benjisanders** [comment]
$o the clear micro$oft $olution i$ to download the profe$$ional (or higher) ver$ion. Way to go micro$oft.

**Comment by heaths** [comment]
You can't move these directories after installing anything at this time. This is because many packages we install (first- and third-party), once installed, must keep going to the same location and themselves cannot be moved.

**Comment by fahnix** [comment]
Problem here is clearly some inept focus on Microsoft's end as to what a high priority issue is. This is a high priority issue! The thing automatically picks your existing drive for beta installations, even if you choose [Custom Installation]. You end up in a position to where you have to remove your original installation & re-install that to another drive, so the product will automatically pick the alternate drive. It's really pathetic that you would waste so many programmer's time on something that should be less than a 1-day fix for your company on its end, to automatically prompt for drive location for all beta product installations would be a best case scenario.
