### ISSUE TITLE
Deletion of invalid environments or auto detected environments

### ISSUE THREAD

**Issue by mrduncle** [MicrosoftDocs/visualstudio-docs#1278]
Deletion of invalid environments or auto detected environments is covered in the content on this page, but there is no heading that gives the game away (nor is there any mention in the "In this article section"....you actually have to read the docs).  Would be helpful to have a more obvious Deletion section or include it as a link in the "In this article" section.

Thank you for the improved Microsoft documentation available with the "docs.microsoft.com" strategy/philosophy, has no doubt been a huge and ongoing effort but it makes a huge difference to the end users.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563f476d-a91b-58c7-9e32-b238756cc97d
* Version Independent ID: 0a0e9cac-a8dc-47a1-14e1-1dacc3441613
* Content: [Manage Python environments and interpreters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio#feedback)
* Content Source: [docs/python/managing-python-environments-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/managing-python-environments-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@mrduncle Thanks for the feedback. Would it help if the heading "Fix invalid environments" was "Fix or delete invalid environments"? That heading does appear in the "In this article" section (which is auto-generated for all H2's in the article), so I'm thinking it just needs to include both scenarios of correcting and deleting.

**Comment by mrduncle** [comment]
Kraig,

Thank you for the prompt response. Your suggested solution would work
perfectly.

Regards,

Duncan

**Comment by kraigb** [comment]
Thanks. Done.
