### ISSUE TITLE
Build numbers do not match up when specifying VSIX supported version ranges

### ISSUE THREAD

**Issue by briman0094** [MicrosoftDocs/visualstudio-docs#1279]
I referenced this article when building a VSIX package so that I could specify the correct minimum Studio version for my extension. It requires at least 15.6.0, which maps to build number 15.6.27428.0 according to this article. If I specified that version in the VSIX manifest, however, the VSIX installer would report that it was not installable on any Studio versions (even above 15.6). I attached a debugger to the VSIXInstaller process and discovered that my instance of Studio (15.7.5) was reporting its build number as 15.0.27703.2042, as opposed to 15.7.27703.2042 as listed by the article. This caused the installer to see "15.0" as less than "15.6". It seems that either the article is incorrect in listing all build numbers as starting with "15.x." when Studio reports all build numbers as starting with "15.0.". When I changed the minimum Studio version in my VSIX manifest to 15.0.27428.0, the extension was able to be installed on 15.6 and above, confirming my suspicion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio 2017 build numbers and release dates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates#feedback)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by SpeedHighway** [comment]
Thank you so much for this.  I was trying to create an extension that didn't work without version 15.7.0 because it was templates requiring .netcore 2.1 and none of the versions on the build numbers page worked.  I appreciate you reporting this and also finding the version that I could finally use for my extension. :)

**Comment by TerryGLee** [comment]
@briman0094 We've applied some fixes to the doc; please let us know if the issue you experienced is still a problem.

**Comment by TerryGLee** [comment]
@briman0094 Having not heard back, we'll assume that the issue is taken care of; if not, please respond back and we'll re-open it.
