### ISSUE TITLE
Add documentation for analyzer "AdditionalFiles"

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#1280]
See all the user comments in https://github.com/dotnet/project-system/issues/879. The current terminology seems confusing, with no documentation at all. We should add documentation for current concept of AdditionalFiles BuildAction, which is based upon the `/additionalFile:<File>` compiler switch that passes non-source additional files to analyzers. You can read more detailed documentation about additional files in C#/VB compilers at https://github.com/dotnet/roslyn/blob/master/docs/analyzers/Using%20Additional%20Files.md

**Comment by mavasani** [comment]
Tagging @gewarren

**Comment by gewarren** [comment]
@mavasani How does this look? https://review.docs.microsoft.com/en-us/visualstudio/ide/build-actions?view=vs-2017&branch=pr-en-us-3326

**Comment by mavasani** [comment]
LGTM. Thanks for adding the documentation!

**Comment by mavasani** [comment]
Also tagging @davkean and @pilchie

**Comment by Pilchie** [comment]
Definitely a nit-pick but to me:

> This build action is mainly used in analyzer projects

implies that you only use this if you are *building* an analyzer, when in fact the primary use case is in *consuming* an analyzer.  Perhaps something like:

> This build action is mainly used to provide inputs to analyzers used in the project

**Comment by gewarren** [comment]
@Pilchie Yes, that makes much more sense, thanks for clarifying that.
