### ISSUE TITLE
Relation between configuration and simulators?

### ISSUE THREAD

**Issue by petemillermultimedia** [MicrosoftDocs/visualstudio-docs#1281]
What is the relation between configurations and the simulators that become available under the configuration selection dropdown? I have two projects that are downloaded from Xamarin University tutorials; both have configurations called "Debug" and "Debug | iPhoneSimulator". Out of the four combinations, three offer simulators from Xcode, but the fourth only offers Generic Device. Where and how is this determined?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23c5c017-e749-191e-b123-eefe89188edf
* Version Independent ID: 4c84b539-1756-17dc-1848-df2a7a6462cc
* Content: [Creating and Editing Build Configurations - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/create-and-edit-configurations)
* Content Source: [mac/create-and-edit-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/create-and-edit-configurations.md)
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by TerryGLee** [comment]
@asb3993 FYI

**Comment by VincentDondain** [comment]
Hi,

Simulators and devices do not require the same `csproj` properties (e.g: architecture) so we need independent configurations for them. In addition, the IDE uses the constant names of the configurations to determine if we need to show devices or simulators in the simulator/device toolbar.

So your fourth configuration that only offers "Generic Device" must be a **device only** configuration and you have no currently connected device.
