### ISSUE TITLE
Document contradicts itself in successive paragraphs

### ISSUE THREAD

**Issue by rich-newman** [MicrosoftDocs/visualstudio-docs#1282]
"The Office extensions for the .NET Framework 4 or later are not installed with Office,..."

Next paragraph":
"The Office extensions for the .NET Framework 4 are installed with Office."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33168414-e535-551c-b501-3f9884b1281b
* Version Independent ID: 869b29bd-ac4f-107f-0da8-5d1cb7b25a3f
* Content: [Visual Studio Tools for Office runtime installation scenarios - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/visual-studio-tools-for-office-runtime-installation-scenarios)
* Content Source: [docs/vsto/visual-studio-tools-for-office-runtime-installation-scenarios.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/visual-studio-tools-for-office-runtime-installation-scenarios.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@rich-newman Thanks for letting us know; this is in the queue to be addressed.

**Comment by John-Hart** [comment]
I believe the reason for the difference in the two paragraphs is one is covering the runtime when installed with Visual Studio and one when it is installed with Office.   @rich-newman does that make sense?

**Comment by rich-newman** [comment]
@John-Hart That may be the intention but it isn't really what it says, is it?  I actually think the confusion is that some combinations of various versions of .NET Framework 4 and versions of Office do install the extensions and others don't, although I'm not sure.  This page is meant to be explaining that.  At the least those two paragraphs are very confusing.

**Comment by John-Hart** [comment]
Thanks @rich-newman  for the feedback.  We'll work on making it a little clearer.

**Comment by rich-newman** [comment]
This has been fixed, really well given how complicated it is.  Thanks.
