### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by markbrents** [MicrosoftDocs/visualstudio-docs#1284]
It's great that you provide example code. But the example code relies on Visual Basic 6.0, which most people don't have installed. Can you provide a compiled version of the COM object for use in the example? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24a7bafe-ebef-e897-cc0c-87e0ecd28c27
* Version Independent ID: c4f862f7-c845-728e-bcfc-f8006dee5af1
* Content: [Deploying COM Components with ClickOnce - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-com-components-with-clickonce)
* Content Source: [docs/deployment/deploying-com-components-with-clickonce.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/deploying-com-components-with-clickonce.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Request for new sample code is on the backlog.

**Comment by Mikejo5000** [comment]
Closing as this work is currently out of scope
