### ISSUE TITLE
First code sample has an error

### ISSUE THREAD

**Issue by controlaware** [MicrosoftDocs/visualstudio-docs#1287]
The first sample [in the snippet walkthrough](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet) is missing the ">" in the top of the snippet:

```
<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets
    xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
    <CodeSnippet Format="1.0.0">
        <Header>
            <Title></Title>
        </Header>
        <Snippet>
            <Code Language="">
                <![CDATA[]]>
            </Code>
        </Snippet>
    </CodeSnippet>
</CodeSnippets>
```

Line 2 should be `<CodeSnippets>`, it is missing the closing >.

**Comment by TerryGLee** [comment]
@controlaware Thanks for the heads-up; we'll take a look at this. @gewarren FYI.

**Comment by nschonni** [comment]
The `xmlns` is the continuation of the first line  just wrapped to a second line
EX: 
```xml
<CodeSnippets xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
```

**Comment by controlaware** [comment]
You are right, not sure how I missed that, it would be better if it were on the same line.

**Comment by jpreese** [comment]
Thanks for pointing this out @controlaware. I would agree with you about keeping them on the same line, especially since the following line is kept together as well.

I've also gone ahead and cleaned up a couple other spots in the document.
