### ISSUE TITLE
I have got Running transformation: System.NullReferenceException

### ISSUE THREAD

**Issue by pranithan-kang** [MicrosoftDocs/visualstudio-docs#1289]
I constructed many .tt and .ttinclude files in my project.
Every T4 files work fine when saving.
However, the errors occur three records (equal to my .tt files) when building the project

Here is the error what I got.
Error		Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.TextTemplatingAD26E64916BA06DE2CBBECE8584847A28413AC8DD9754FEA3F505C8E94C09131DAE54D32C525943DF610E9893CF415DD55219970D9C7C378C8A0FB14B3FE0A11.GeneratedTextTransformation.ConfigurationAccessor..ctor(IServiceProvider host, String configProjectLocation)
   at Microsoft.VisualStudio.TextTemplatingAD26E64916BA06DE2CBBECE8584847A28413AC8DD9754FEA3F505C8E94C09131DAE54D32C525943DF610E9893CF415DD55219970D9C7C378C8A0FB14B3FE0A11.GeneratedTextTransformation.TransformText(). Line=0, Column=0	Implementation			

My Environment
=====
Microsoft Visual Studio Community 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C# 2017   00369-60000-00001-AA447
Microsoft Visual C# 2017

[Ignored content]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca46de41-5103-a318-3553-3bf05c59751b
* Version Independent ID: 27b60762-dfe8-9320-c891-164e2f0ca980
* Content: [Code Generation in a Build Process in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process#q--a)
* Content Source: [docs/modeling/code-generation-in-a-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/code-generation-in-a-build-process.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@pranithan-kang Thanks for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. To report such an issue, consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.
