### ISSUE TITLE
Doesn't explain how to distribute the pkgdef file

### ISSUE THREAD

**Issue by r3m0t** [MicrosoftDocs/visualstudio-docs#1291]
Is this only possible with a vsix, or are there other ways?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e45c1ad-ec51-d4ac-e312-aa3f00d1aa17
* Version Independent ID: ddf8b9a6-f8d9-2642-be36-0856e639ac85
* Content: [How to: Manage a Private Gallery By Using Registry Settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-manage-a-private-gallery-by-using-registry-settings)
* Content Source: [docs/extensibility/how-to-manage-a-private-gallery-by-using-registry-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-manage-a-private-gallery-by-using-registry-settings.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
You can manually install a .pkgdef as well and VS will pick it up. See https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/createpkgdef-utility?view=vs-2017#remarks
