### ISSUE TITLE
Running R code from windows forms app

### ISSUE THREAD

**Issue by sessler** [MicrosoftDocs/visualstudio-docs#1292]
I have a windows Forms app in c#. I would like to perform some calculations in R. I tried to add an R project to the solution, but when I wanted to add a reference to the R project, I got the error message "A reference to RProject1 could not be added". How can this be overcome?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2e46c-3c08-18f7-dc72-bf5b69ea667e
* Version Independent ID: 61e033e8-4d38-1b9e-c7d4-e7dde5b86fad
* Content: [R projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/r-projects-in-visual-studio#feedback)
* Content Source: [docs/rtvs/r-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/r-projects-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@sessler Thanks for your question. As written in the "Note" at the end of the docs page here, the R Tools for Visual Studio don't currently support direct C#/R integration (e.g. adding project references), but there are libraries available such as R.Net. See https://www.nuget.org/packages?q=R.Net for a variety of R.Net and related packages. R.Net (https://www.nuget.org/packages/R.NET/) is certainly one, and there's also Microsoft.R.Host.Client.API (https://www.nuget.org/packages/Microsoft.R.Host.Client.API/). Docs for those are in their respective GitHub repos, which you get to through the "Project Site" link on the right side of the description page.

**Comment by sessler** [comment]
Thank you for the information

Kraig Brockschmidt <notifications@github.com> ezt írta (időpont: 2018. júl.
25., Sze, 18:51):
