### ISSUE TITLE
Typo in section "To collect and view data at the command line"

### ISSUE THREAD

**Issue by dueringa** [MicrosoftDocs/visualstudio-docs#1295]
Step 2 says to run VsPefCLREnv, but it should be VsPerfCLREnv

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600aa596-eb13-980a-76a5-215c9c1352ca
* Version Independent ID: 50651218-3f4e-167b-2a44-d1acb7e5ff4f
* Content: [Walkthrough: Using Profiler APIs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/walkthrough-using-profiler-apis)
* Content Source: [docs/profiling/walkthrough-using-profiler-apis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/walkthrough-using-profiler-apis.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@dueringa Thanks! I'll make that fix.
