### ISSUE TITLE
This benefit no longer shows up in the list of benefits on https://my.visualstudio.com/

### ISSUE THREAD

**Issue by sebastianzolg** [MicrosoftDocs/visualstudio-docs#1296]
We have all developers assigned to Visual Studio Enterprise E6 subscription. However, the Enterprise Mobility & Security Benefit doesn't show up there. 

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b2872e-438a-b86e-9ff5-6dc0021f3fe8
* Version Independent ID: 8b9e935e-07ad-4992-edb9-e8361d867617
* Content: [EMS Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ems)
* Content Source: [subscriptions/vs-ems.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-ems.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@BenAffleckIsBatman Thanks for reaching out.  We're working to resolve an issue with the EMS benefit on the my.visualstudio.com portal and hope to have it resolved soon.  We apologize for any inconvenience.

**Comment by iromanovsky** [comment]
Also, 'Office E3 Developer' subscription (see https://docs.microsoft.com/en-us/office/developer-program/office-365-developer-program-faq#as-a-microsoft-full-time-employee-can-i-receive-a-subscription) is not visible on my benefits page on my.visualstudio.com.

**Comment by evanwindom** [comment]
@iromanovsky If you are an FTE, your subscription should include Office 365 Developer.  If you can't see it, it's possible you're viewing a different subscription, such as Visual Studio Dev Essentials.  You can click on https://my.visualstudio.com/subscriptions to view and change your subscriptions.  If you still have trouble, you'll want to reach out to the subscriptions support team via the "Contact us" button at the top of the page on https://visualstudio.microsoft.com/subscriptions/support/.

**Comment by gewarren** [comment]
@evanwindom Can this be closed?

**Comment by evanwindom** [comment]
@gewarren Yes

**Comment by ShaXam-King** [comment]
Is there an updated timeline on when the EMS benefit will again be available for activation?

**Comment by rtwaddell** [comment]
Any update on this?
