### ISSUE TITLE
talk more about replacing with regEx

### ISSUE THREAD

**Issue by mostafa8026** [MicrosoftDocs/visualstudio-docs#1300]
I think it is better to talk more about replacing with regEx especially replace a captured group with name like (&lt;pet&gt;dog|animal).
thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.netregularexpressionhelp)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.0)%26rd%3Dtrue)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mostafa8026 Thanks for the suggestion.

**Comment by gewarren** [comment]
~12K page views per month = P0
