### ISSUE TITLE
Add parameter to existing constructor is also available for methods.

### ISSUE THREAD

**Issue by MaStr11** [MicrosoftDocs/visualstudio-docs#1302]
VS 15.8 extends the option *Add a parameter to an existing constructor* to methods. The corresponding PR can be found in the Roslyn repo dotnet/roslyn#22314.

The documentation should mention this new option. The [Generate overload](https://docs.microsoft.com/en-US/visualstudio/ide/reference/generate-override) chapter should also contain a description of the feature (or link to the description).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd39fe2-328a-b8a2-9795-ab8c6c735761
* Version Independent ID: 075639a3-171c-6ade-85fc-a3845f933b82
* Content: [Generate a constructor in Visual Studio - Visual Studio](https://docs.microsoft.com/en-US/visualstudio/ide/reference/generate-constructor)
* Content Source: [docs/ide/reference/generate-constructor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-constructor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **kaseyu**

**Comment by gewarren** [comment]
@MaStr11 Thanks for the heads up Martin!
