### ISSUE TITLE
Please annotate tips with applicable Visual Studio 2017 versions

### ISSUE THREAD

**Issue by geekycrooner** [MicrosoftDocs/visualstudio-docs#1303]
It's disheartening to see a really cool feature in the docs and then go to use it only to have it not work because it is an Enterprise-only function and all I have is Professional (or Community). Could you please find some very obvious way to indicate Enterprise-only functions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e598ea-9607-4e7e-e708-84573519ccaf
* Version Independent ID: 75f00085-0835-78b6-1098-1be6371f5c07
* Content: [Increase your productivity for .NET development - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-2017-for-dotnet-developers?WT.mc_id=ondotnet-channel9-cephilli#i-want-to-run-and-see-my-unit-tests)
* Content Source: [docs/ide/visual-studio-2017-for-dotnet-developers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-2017-for-dotnet-developers.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **kaseyu**

**Comment by geekycrooner** [comment]
Examples on this page: Live Unit Testing (only Enterprise) and CodeLens (only Enterprise and Professional) bear no indication that they are version-specific until the links are clicked and the next page of documentation is read.

**Comment by StingyJack** [comment]
@geekycrooner - I dont think you are missing something "really cool" with those two features. They both slow the IDE down and you cant really turn LUT off =/
