### ISSUE TITLE
Possible to hook into the C# Debugger Step In/Over/Out actions?

### ISSUE THREAD

**Issue by Linchy** [MicrosoftDocs/visualstudio-docs#1304]
Hi I would like to augment the current C# debugger, specifically when I am stepping over code with multiple threads running, I would like the plugin to manually check that I am in a specific thread id, and if not then automatically continue.

I need to be able hook into the 'break' event (that I hope is emitted by Visual Studio or the Debugger), and to get access to the current Thread Id, and finally also be able to call .StepIn() again if the thread Id does not match a specified value.

Is this sort of functionality possible?

**Comment by Mikejo5000** [comment]
@Linchy Hi, you can set filters on breakpoints based on Thread ID:
https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints#filter
When you hit the breakpoint on the particular thread, you can then step through code on that thread.
Also see this:
https://docs.microsoft.com/en-us/visualstudio/debugger/get-started-debugging-multithreaded-apps#bkmk_follow_a_thread

It sounds like you want to write your own plugin, however.

There are extensibility APIs here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger?view=visualstudiosdk-2017
and here (native):
https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/threads

The conceptual docs on extensibility are based on the native APIs, however, so I'm not sure how much conceptual doc support you will find if you write in managed code:
https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/roadmap-for-extending-the-debugger

**Comment by Linchy** [comment]
Thanks for the reply @Mikejo5000, I have found though that even when stepping after a breakpoint the debugger still switches between threads. It never stays on one thread.

thank for the link to the docs, though I am having trouble understanding how to actually hook the step events? Is there any specific vsix c# sample code that I can use here?

**Comment by Mikejo5000** [comment]
The trick--which seemed to work for me during some tests quite a while back--is to avoid breaking into code on any other threads while the app runs. So if you set a conditional breakpoint for a unique thread ID or for data that is unique to the thread, then you can continue stepping through code just that one thread (F10, F11...) after you hit the conditional breakpoint. If any other breakpoints are hit on another thread (before or after), or multiple threads meet the condition and are hit, then the debugger will switch threads.

Unfortunately, I do not know offhand of any managed sample code for these APIs. They are not used that often, I think. I will ask though, in case someone knows of any relevant samples.

**Comment by Mikejo5000** [comment]
Put another way: The debugger is supposed to only break into code on a per-thread basis. If you never give it an opportunity to break into another thread, it's not supposed to do it.

**Comment by Mikejo5000** [comment]
BTW, I don't know if you already saw this, but this looks like the main API for the task:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.debugger.stepping?view=visualstudiosdk-2017

**Comment by Mikejo5000** [comment]
@Linchy I have some comments from the product team:
- [It looks like you want] to be able to always step on the same thread in C# regardless of hitting a break condition in another thread or not
- [It looks like you want] to extend the current debugger just a tiny bit (not build a new debug engine) 
 
One option is to look at the OnEnterBreakMode events that can be subscribed too:
https://docs.microsoft.com/en-us/dotnet/api/envdte.debuggereventsclass.onenterbreakmode?view=visualstudiosdk-2017

**Comment by Linchy** [comment]
Thanks @Mikejo5000 I will look into this this week, but that definitely looks like what I'm after. I tested the conditional breakpoint filter and it does seem to work, though the cursor journey is a hassle enough to make me still think about writing this plugin. Thanks again for your responses.
