### ISSUE TITLE
Does TargetFrameworkVersion work with .Net Core unit tests?

### ISSUE THREAD

**Issue by erhuan-msft** [MicrosoftDocs/visualstudio-docs#1305]
Does runsettings work with test dll built with .Net Core? It would be nice to update this documentation to add examples of framework versions for .Net Core so we can specify which framework version tests will be running under.

If I keep TargetFrameworkVersion as Framework45, I will be getting the following error:

2018-07-20T21:40:49.4558296Z Starting test execution, please wait...
2018-07-20T21:40:49.5808282Z Test run will use DLL(s) built for framework .NETFramework,Version=v4.5 and platform X64. Following DLL(s) do not match framework/platform settings.
2018-07-20T21:40:49.5809088Z Service.Tests.dll is built for Framework 2.1 and Platform X64.
2018-07-20T21:40:49.5810422Z Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@erhuan-msft Thanks for the feedback, this looks like useful info to have in the doc. @pvlakshm can you answer this question about .NET Core framework version in .runsettings file?

**Comment by renemadsen** [comment]
Any news about the correct way of setting up runsettings for .Net Core?

**Comment by SamJongenelen** [comment]
Can confirm that, using `xUnit.net` runner.

` NetCoreApp, Version=2.1` **does** gives errors during test run.
`FrameworkCore20` **does** give runtime (output panel) errors.
FrameworkCore21` **does** give runtime (output panel) errors.
`FrameworkCore10` **does not** give runtime (output panel) errors.

For now I can use the ` FrameworkCore10` workaround

**Comment by gewarren** [comment]
@renemadsen and @SamJongenelen, thanks for providing that info!

**Comment by gewarren** [comment]
~8000 page views per month = P0

**Comment by alenmeister** [comment]
> Can confirm that, using `xUnit.net` runner, with `NetcoreApp2.1` UnitTest projects
> 
> ` NetCoreApp,Version=2.1` **does** gives errors during test run.
> `FrameworkCore20` **does** give runtime (output panel) errors.
> `FrameworkCore21` **does** give runtime (output panel) errors.
> `FrameworkCore10` **does not** give runtime (output panel) errors.
> 
> For now I can use the ` FrameworkCore10` workaround

This workaround does not work for me on VS2019 with NUnit and NetcoreApp2.2, sadly 👎

`[03.06.2019 11:49:59 Informational] ------ Run test started ------
[03.06.2019 11:50:00 Warning] Test run will use DLL(s) built for framework .NETCoreApp,Version=v1.0 and platform X64. Following DLL(s) do not match framework/platform settings.
DuckDuckGo.dll is built for Framework 2.2 and Platform AnyCPU.
Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.

[03.06.2019 11:50:01 Informational] NUnit Adapter 3.13.0.0: Test execution started
[03.06.2019 11:50:01 Informational] Running all tests in C:\Repositories\selenium-dotnet\DuckDuckGo\bin\Debug\netcoreapp2.2\DuckDuckGo.dll
[03.06.2019 11:50:01 Informational]    NUnit3TestExecutor converted 1 of 1 NUnit test cases
[03.06.2019 11:50:06 Informational] NUnit Adapter 3.13.0.0: Test execution complete
[03.06.2019 11:50:06 Informational] ========== Run test finished: 1 run (0:00:06,6765399) ==========`

**Comment by keithwillcode** [comment]
We are seeing the same warning while attempting to use the `FrameworkCore10` workaround mentioned.

VS 2019 and MSTest.
Microsoft.NET.Test.Sdk v16.1.1
MSTest.TestAdapter v1.4.0
MSTest.TestFramework v1.4.0

[6/12/2019 2:21:30 PM Warning] Test run will use DLL(s) built for framework .NETCoreApp,Version=v1.0 and platform X86. Following DLL(s) do not match framework/platform settings.
[Edited].UnitTests.dll is built for Framework 2.2 and Platform AnyCPU.
[Edited].SystemTests.dll is built for Framework 2.2 and Platform AnyCPU.
Go to http://go.microsoft.com/fwlink/?LinkID=236877&clcid=0x409 for more details on managing these settings.

**Comment by gewarren** [comment]
@AbhitejJohn Can you help provide an answer here, and then I can update the docs?

**Comment by AbhitejJohn** [comment]
Speaking on behalf of the test platform team, you could choose to omit the TargetFrameworkVersion from the runsettings and the platform would automatically figure out the platform based on built binaries. We do have a bug in VS IDE where this still shows a warning despite not specifying a runsettings which we are looking at fixing with [this](https://developercommunity.visualstudio.com/content/problem/579073/test-discovery-reporting-dlls-do-not-match.html) feedback. 

As for the valid values for TargetFrameworkVersion, this doc should be able to explain that better: https://github.com/microsoft/vstest-docs/blob/master/docs/configure.md#section-1-run-configuration. For VS IDE scenarios though, until the bug above is fixed these are the valid values: 

 Framework35 -> .Net Framework 3.5.
 Framework40 -> .Net Framework 4.0.
 Framework45 -> .Net Framework 4.5 and higher .
 FrameworkCore10 -> All Net Core sources.
 FrameworkUap10 -> all UWP based sources.

**Comment by effyteva** [comment]
+1 on this issue
We face similar issue, as for some reason the unit tests choose to use .NET core 1.0, and some refers doesn't support .NET core 1.0 anymore.
We tried updating manually the TargetFrameworkVersion to 2.1/2.2, but couldn't get it to work...

**Comment by gewarren** [comment]
I'm updating the docs page now with the valid values that Abhitej [listed](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1305#issuecomment-501469555), and when merged it will close this issue. Please log any product issues by using [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) in Visual Studio. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by mikgam** [comment]
Another +1 on the issue.
From what I am seeing, quote "Framework45 -> .Net Framework 4.5 and higher" isn't correct.  I've adjusted the platform to be x64 everywhere, and it is still giving me grief.

[date/time Warning] Test run will use DLL(s) built for framework .NETFramework,Version=v4.5 and platform X64. Following DLL(s) do not match framework/platform settings.
UnitTestBlahBlahBlahBlah.dll is built for Framework 4.7.2 and Platform X64.

**Comment by AbhitejJohn** [comment]
@mikgam : You are running into [the bug](https://developercommunity.visualstudio.com/content/problem/579073/test-discovery-reporting-dlls-do-not-match.html) I mentioned above which should be addressed in the next preview of VS 2019.

**Comment by yaseminyarnell2** [comment]
Hi, My application is running .net core 2.2. For TargetFrameworkVersion, I tried framework45, FrameworkCore10 and FrameworkCore22. I also did not specify  but nothing worked. Can you please let me know when you resolve this bug.

**Comment by AbhitejJohn** [comment]
@yaseminyarnell2 : The issue I've mentioned has already been fixed in VS 2019 update 2. Would you mind filing an issue on https://developercommunity.visualstudio.com/ with the version of VS and the scenario you are running please?

**Comment by yaseminyarnell2** [comment]
https://developercommunity.visualstudio.com/content/problem/772061/cannot-run-automated-tests-from-azure-test-plans-i.html

**Comment by SamJongenelen** [comment]
@yaseminyarnell2  I've had succes running netcore 2.2+ tests by NOT specifying any TargetFramework. However, it also needs the x64/x86 setting to be correct. Are you using the _dotnet test_ command? 

Personally, I've been using Xunit without a runsettings file with great success. I configure the test run using command line switches combined with the xunit preferred way: using an _xunit.config.json_ file in the root of the directory. 
This approach has the advantage of working on any machine - build agent or visual studio.

**Comment by SamJongenelen** [comment]
@yaseminyarnell2 you should include more nuget packages in your csproj. It seems you are missing Microsoft.Test.SDK. I've personally also set the _<DebugType>Full</DebugType>_ flag
