### ISSUE TITLE
Unclear description of the "\w" special character

### ISSUE THREAD

**Issue by PawelWMS** [MicrosoftDocs/visualstudio-docs#1307]
The description of the "\w" character states that it matches "any alphanumeric character" and it is not entirely clear, which characters does the author have in mind. For instance "\w" matches the underscore "_" character from the standard ASCII set, which is neither a letter, not a digit. From the extended set the ordinal indicators (0x170 and 0x186) seem somewhat controversial or at least not intuitive as well. I think it might help to provide a separate link where the logic behind "\w" is explained in more detail with a list of all characters covered by this special character (if feasible).

ASCII values taken from https://www.ascii-code.com.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@PawelWMS Thanks for the feedback. I'll add this to our backlog for consideration.

**Comment by gewarren** [comment]
@PawelWMS This page contains more info about the \w character class: https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-classes-in-regular-expressions#word-character-w. For the 10 "connector punctuation" category characters it includes, you can view those here: https://www.compart.com/en/unicode/category/Pc#UNC_DB. I'll update this docs page with more info/links, as you requested.

**Comment by PawelWMS** [comment]
@gewarren: thank you, I appreciate it!
