### ISSUE TITLE
right-click on the Dockerfile and choose Build Docker Image does not exist

### ISSUE THREAD

**Issue by spacecat** [MicrosoftDocs/visualstudio-docs#1309]
"If you prefer to work directly with the Docker image, you can right-click on the Dockerfile and choose Build Docker Image."

I have all the prerequisites installed but I can't find this menu item?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools)
* Content Source: [docs/deployment/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-kubernetes-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Using VS 2017 version 15.8, I see the menu item when I choose the "Add Container Orchestration support" option as described in the tutorial.  If I just create a project with Enable Docker support checked, but don't choose the Add > Container Orchestration Support item, then there is no Build Docker Image menu item. Is this consistent with what you're seeing?

**Comment by ghogen** [comment]
I also just tried this with the Container Application for Kubernetes template as the tutorial describes, and I do see the "Build Docker Image" option on the shortcut menu.

**Comment by ghogen** [comment]
After checking with the engineering team, it appears that the menu item only appears after the NuGet package is loaded, so there is a delay from when a project is first created before the menu item appears. They say the delay should only be about 5 seconds.  Let me know if this seems to explain the issue.

**Comment by spacecat** [comment]
I have a new machine with a clean VS 2017 CE install with Docker tools installed and it's working fine now. Thanks!
