### ISSUE TITLE
best practice on how to deploy application updates using a chart using Visual Studio

### ISSUE THREAD

**Issue by spacecat** [MicrosoftDocs/visualstudio-docs#1310]
Can you post a best practice on how to deploy application updates using a chart using Visual Studio? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools#add-kubernetes-support-to-an-existing-project)
* Content Source: [docs/deployment/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-kubernetes-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by craigcaseyMSFT** [comment]
This article includes a link to Helm which describes how to use Helm charts to "define, install, and upgrade" Kubernetes applications. It looks like this issue has been addressed, so I am closing this. Thanks!
