### ISSUE TITLE
SourceDirectory variable incorrect

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/visualstudio-docs#1312]
In the example code, the property group declares a variable `ZipOutputPath`, but the `ZipDirectory` task is expecting to take in a variable named `OutputPath`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2cbd60-5d56-af4f-b196-4c9f190a1586
* Version Independent ID: 6408870a-85cd-428c-5ede-2338804481d6
* Content: [ZipDirectory Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/zipdirectory-task)
* Content Source: [docs/msbuild/zipdirectory-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/zipdirectory-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I'll take a look at that.

**Comment by jpreese** [comment]
Thanks for reporting this @Keboo! We have an open PR to resolve this issue.
