### ISSUE TITLE
Example description is incorrect 

### ISSUE THREAD

**Issue by Keboo** [MicrosoftDocs/visualstudio-docs#1313]
The description for the example code states: "The following example creates a .zip archive from the output directory after building a project.". However it is using `$(MSBuildProjectDirectory)` which is [defined](https://msdn.microsoft.com/en-us/library/ms164309.aspx?f=255&MSPPError=-2147217396) as "The absolute path of the directory where the project file is located". This is highly misleading, since it will zip of the entire project directory (which will likely include the output directory).
Either this description should be updated to reflect what is actually happening or the example should be updated to be the output directory. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2cbd60-5d56-af4f-b196-4c9f190a1586
* Version Independent ID: 6408870a-85cd-428c-5ede-2338804481d6
* Content: [ZipDirectory Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/zipdirectory-task)
* Content Source: [docs/msbuild/zipdirectory-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/zipdirectory-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by jpreese** [comment]
#1330 should resolve this as well. 

We're not longer attempting to use the `ZipOutputPath` variable (resolving to MSBuildProjectDirectory) and instead are relying purely on the output directory which matches the example text.

**Comment by Mikejo5000** [comment]
Resolved by #1330
