### ISSUE TITLE
Looks like there's an easier way to do this...

### ISSUE THREAD

**Issue by ciphernemo** [MicrosoftDocs/visualstudio-docs#1314]
For the most part you have the commands correct. However, they are not in their simplest form, and some are not functioning as intended.

For caching, this is all you need...
Caching: vs_[edition].exe --layout [destination_folder] --add Package1 --add Pacakge2[...]
Install: vs_setup.exe

The install should be run from within the newly created cache folder. Both a vs_[edition].exe and vs_setup.exe file are created and both work the same from my limited testing.

For passive install of pro, enterprise, etc...
vs_setup.exe --productKey MY-PRODUCT-KEY --passive --norestart
Or for silent...
vs_setup.exe --productKey MY-PRODUCT-KEY --quiet--norestart

A caching example:
vs_community.exe --layout C:\vs2017 --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Component.GitHub.VisualStudio

The --lang is not needed if both the system doing the caching and the target install system have the same locality settings. And the extra --add and other options for the install after caching is done is not required, IF the installer is run directly from the cache folder.

Also the --includeOptional does not work as desired. It will install all optional packages, but REMOVE all recommended packages. The --includeRecommended works the same way, in reverse. And including neither will only install the recommended and not the optional. Therefore when creating a cache, the optional packages in each workload have to be include in new --add options. I don't think this is working as intended by Microsoft, but it's the only way I found how to circumvent this issue. Perhaps I'm missing something? Or is this a bug in the offline cache installer for VS2017?

All of this I tested first-hand with Visual Studio 2017 Professional (latest version downloaded as of 7/27/2018) on a Windows 7 system with deployment targeting Windows 10 systems. I have also tested a little with Visual Studio 2017 Community, but the bulk of my testing is with Professional.

**Comment by gewarren** [comment]
@ciphernemo Thanks for the feedback. Is this the topic you're referring to? @TerryGLee fyi.

**Comment by ShayneHau** [comment]
Seconded on the issue about including recommended and optional packages.
#1693 

Think I will follow the process you have outlined here, of adding optionals explicitly thanks.

> Also the --includeOptional does not work as desired. It will install all optional packages, but REMOVE all recommended packages. The --includeRecommended works the same way, in reverse. And including neither will only install the recommended and not the optional. Therefore when creating a cache, the optional packages in each workload have to be include in new --add options. I don't think this is working as intended by Microsoft, but it's the only way I found how to circumvent this issue. Perhaps I'm missing something? Or is this a bug in the offline cache installer for VS2017?

**Comment by TerryGLee** [comment]
@ciphernemo As we have not heard back from you, we are closing this GitHub Issue. We hope that you are not still experiencing the problem that you initially described; if so, please do open another GitHub Issue against the [Disable or move the package cache](https://docs.microsoft.com/en-us/visualstudio/install/disable-or-move-the-package-cache) page (it that indeed includes the content you referred to when you first registered this GitHub Issue). 

@ShayneHau I believe the issue you referenced, [#1693](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1693), has since been resolved, and so no further action needs to be taken here.

Thanks again to you both for your feedback!
