### ISSUE TITLE
Publish to Azure AKS menu item missing

### ISSUE THREAD

**Issue by spacecat** [MicrosoftDocs/visualstudio-docs#1316]
I installed the AKS Publishing Tools but the menu item from the screenshot does not appear in my Visual Studio Community edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools#publish-to-azure-kubernetes-service-aks)
* Content Source: [docs/deployment/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-kubernetes-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by FelschR** [comment]
Same issue here with VS Enterprise 15.8.1.
I've published the projects to the Azure Container Registry but the "Add Azure AKS" option on the Solution content menu isn't showing up.

I've even tried with a new solution with the "Container Application for Kubernetes" project template.

Maybe we're just missing something and the docs aren't specific enough when this option shows up.

**Comment by kkho** [comment]
Still missing. Any updates on this?

**Comment by ghogen** [comment]
We checked with the engineers who own this feature. This menu item should appear if you install the VSIX and run through the configuration steps documented in the linked articles under the "If you wish to publish to AKS from Visual Studio" heading. This includes the CLI commands to ensure connection to the cluster such as "az aks get-credentials …", kubectl installed, helm installed, and helm init run. I just tried this on a recent VS 15.9 preview build, and was able to see this - in a new Container Application for Kubernetes project.

**Comment by kkho** [comment]
Thank you, I think what you have described solved the problem on this.

**Comment by cklepeis** [comment]
Not seeing it in VS v15.8.5 ... followed the steps and installed prerequisites from here https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools?view=vs-2017#prerequisities

**Comment by FelschR** [comment]
Have you setup the Azure cli, helm & installed both of the Kubernetes extensions (there's one specifically for publishing)?

**Comment by cklepeis** [comment]
Pretty sure I missed installing the Tiller part. Will go through that once I work through another issue I'm having publishing to my azure container service - commented on that separate issue here https://github.com/MicrosoftDocs/visualstudio-docs/issues/1311

**Comment by cklepeis** [comment]
After installing helm with chocolatey, it shows up. Previously I just d/l the binary to a folder on my computer and ran helm init with it.

**Comment by gewarren** [comment]
@ghogen Should we update the article with the info you added in the [comment](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1316#issuecomment-420407486)?

**Comment by ghogen** [comment]
I believe we can safely close this, as the article references the steps required to get this working.
