### ISSUE TITLE
List all currently installed component id?

### ISSUE THREAD

**Issue by SidShetye** [MicrosoftDocs/visualstudio-docs#1317]
How do we enumerate all the component IDs installed on a given machine? The idea is to replicate a known good install by dumping the component IDs from that install into a file/command line and feed it back to the installer on other machines (e.g. scripting it in with the `--add` arg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f80d9f-168b-e3cb-6499-e03a44206826
* Version Independent ID: 4b235b0d-1436-0a36-ef55-f76ba8d95bd1
* Content: [Visual Studio 2017 workload and component IDs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids)
* Content Source: [docs/install/workload-and-component-ids.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-and-component-ids.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by midspace** [comment]
I've been looking for an answer to this. So far I've only got this...
There is a file called devenv.isolation.ini located here.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.isolation.ini
It has a InstallationWorkloads and InstallationPackages sections which match up with what I have installed.
But note, InstallationPackages also contains third party components that are installed from other sources.

**Comment by fishbits** [comment]
this is terrific, midspace... thank you!

**Comment by TerryGLee** [comment]
@SidShetye We appreciate the inquiry, and @midspace thanks for your input!
@tedvz FYI.

**Comment by tydunkel** [comment]
@SidShetye The latest release of Visual Studio has the solution you will need for this. A new [export feature](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017#using-export) was added that will allow you to export the selections from a good install of VS and use that for a clean, new install.

**Comment by SidShetye** [comment]
Fantastic!

**Comment by nextbenjy** [comment]
thanks midspace :)

**Comment by Dean-NC** [comment]
midspace's comment about the devenv.isolation.ini file is great, and is still valid for VS 16.6.0.

@tydunkel The dumb thing Microsoft did with the 2019 installer is that if the installer is not the latest version, it won't even show you what you currently have installed, unless you update the installer!!  What a non-professional thing to do! Also, when it's not the latest version, you can't even use the command-line export feature!!  Ridiculous.
