### ISSUE TITLE
There instructions don't apply to VB.

### ISSUE THREAD

**Issue by paul1956** [MicrosoftDocs/visualstudio-docs#1323]
Solution #3: Tools &gt; Options, and uncheck the setting Debugging &gt; General &gt; Enable property evaluation and other implicit function calls. does not exist in VB Settings but the crash still happens. Solutions 1 and 2 don't work when the issue is internal to VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfd7078-683e-9fd6-247b-e75d4ed16a32
* Version Independent ID: ae3300c4-55a8-59b6-846b-50c48c88dcfe
* Content: [Error: Evaluating the function 'function' timed out and needed to be aborted in an unsafe way - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.unsafe_func_eval_abort)%3Bk(DevLang-VB)%26rd%3Dtrue)
* Content Source: [docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@paul1956 Thanks, I will take a look at this.

**Comment by Mikejo5000** [comment]
No repro. I see this setting, which should apply globally.

**Comment by paul1956** [comment]
The setting does not exist as described.
![image](https://user-images.githubusercontent.com/12789369/46239720-3bedaf00-c351-11e8-863b-95d043559be3.png)

**Comment by paul1956** [comment]
Thanks, you can close. But if possible the picture is needed. I never found it searching.

**Comment by Mikejo5000** [comment]
It does seem like the search feature is scoped to the selected settings (which seems buggy). If I select the 'Debugging' node, I can find the setting via search (search for 'function', for example).
![debugging-props-2](https://user-images.githubusercontent.com/11948536/46361146-c3714180-c621-11e8-863b-3dc756cef1a0.png)
