### ISSUE TITLE
Offline Install is not Offline....

### ISSUE THREAD

**Issue by sharkbit** [MicrosoftDocs/visualstudio-docs#1328]
I Download the entire package of 38G of installs,   using the `vs_enterprise.exe --layout c:\vs2017layout --lang en-US`.  Moved it to my Closed Environment and it is still trying to go the internet to download things...  
  Error :  "After 9 attempts,  there was a problem downloading the file:
'https://download.visualstudio.microsoft.com/download/pr/11659718/6596c40bbdf0e18301b66a1f7c1f28cf/payload.vsix'

Added the --noWeb to the command and fails with Couldn't download Microsoft.VisualStudios.Branding.Professional    

Why didn't this download when I downloaded EVERYTHING....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by sharkbit** [comment]
Just did a full download of Enterprise to patch 15.8.2,  downloaded over 48 Gigs and it says I'm Missing the "Microsoft.VisualStudios.Branding.Enterprise" & "Microsoft.VisualStudios.Setup.Configuration".

My Environment is Offline and I will NEVER be able to use the 'Report this problem' button.  If I download the Full package at Enterprise Level it Better Include All the Packages Below,  Including Professional.   As My Enviroment has Many developers, some wit hPro Licences and some with Ent Licences.

**Comment by mitsukuri** [comment]
Obviously, m$ just wants to incrementally extinguish any will to keep development machines offline. Because offline machines send no data home and their users demonstrate disobedience by refusing to conform to the [Panopticon](https://en.wikipedia.org/wiki/Jeremy_Bentham#Death_and_the_auto-icon) model of society that m$ has been pedaling so zealously.

**Comment by pheest** [comment]
I am experiencing this issue with VS2017 15.9.30.

https://download.visualstudio.microsoft.com/download/pr/c77cdde4-54c4-4715-92f2-5da3455e5483/377079f969525a1a48fe1323bcfff5f0c984982ba826db831a0e33aa0449a12a/payload.vsix

I work on an internal secure network, having no access to the Internet.

**Comment by sharkbit** [comment]
For anyone running into this issue,   My solution was to set up an internal server to replicate their download site.   Then monitoring the servers logs I would see what extra packages it thought it was missing and had to download them one at a time to include the with previously downloaded files.
