### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by aendie** [MicrosoftDocs/visualstudio-docs#1331]
Please correct typo in the hyperlink "Walkthrough: Create a site column, content type, and tist for SharePoint". tist => list
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8f996d-d327-4961-7582-d5716f559f24
* Version Independent ID: 0c77b628-0db6-2767-2a1c-c60716f56aca
* Content: [Create SharePoint Solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/sharepoint/create-sharepoint-solutions)
* Content Source: [docs/sharepoint/create-sharepoint-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/sharepoint/create-sharepoint-solutions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@aendie Thanks for letting us know; we'll get this fixed.

**Comment by jpreese** [comment]
Echoing what @TerryGLee said, thanks @aendie! There's an open PR to fix this.
