### ISSUE TITLE
Wording in file extension registration article has aged badly

### ISSUE THREAD

**Issue by rmcdonald** [MicrosoftDocs/visualstudio-docs#1334]
I would guess this MSDN article was created a long time ago, when Windows XP was the current version of Windows.  It says:

`The OpenWithProgids key is only supported in Windows XP. Because **other** operating systems ignore this key, do not use it as the only registration for file handlers. Use this key to provide a better user experience in Windows XP.` (my emphasis)

When this article apparently was written, it was easy to interpret correctly.  Reading it today, it appears to tell readers to not use OpenWithProgids for Windows Vista/7/8/10, and thus to use OpenWithList instead.  This is because an author used the word _other_ instead of _earlier_, _prior_, or _older_.  _Other_ can refer to past or future, whereas the other three words refer only to the past.

I incorrectly coded file registration based on the information I got from reading this article.  Fortunately, I recently encountered the article at [How to Include an Application on the _Open With_ Dialog Box](https://docs.microsoft.com/en-us/windows/desktop/shell/how-to-include-an-application-on-the-open-with-dialog-box); the conflict between the two articles made me realize that the article about which I am reporting has a problem and so I was able to correct my file registration code.

I would rewrite that section of the article something like what follows:

`The OpenWithProgids key is only supported in Windows **versions XP and later**. Because **versions of Windows prior to XP** ignore this key, do not use it as the only registration for file handlers. Use this key to provide a better user experience in Windows **versions XP and later**.`

Maybe the second sentence could be deleted, and the first and third sentences could be combined.

I would also amend the section on OpenWithList to specify that this key should be used only for Windows versions earlier than XP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51dbf08a-8515-023f-2eda-25568ae56255
* Version Independent ID: c049ec37-5dba-5dda-7c75-fe6394ffba95
* Content: [Specifying File Handlers for File Name Extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/specifying-file-handlers-for-file-name-extensions)
* Content Source: [docs/extensibility/specifying-file-handlers-for-file-name-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/specifying-file-handlers-for-file-name-extensions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
