### ISSUE TITLE
Requirements are outdated on this page

### ISSUE THREAD

**Issue by aendie** [MicrosoftDocs/visualstudio-docs#1344]
I quote a requirement from this page : "Microsoft SharePoint Server 2010 installed on 64-bit Windows Server 2008 or 64-bit Windows Server 2008 R2". I have SharePoint Server 2016 installed on 64-bit Windows Server 2012 R2. Does this mean I cannot develop SharePoint Farm Solutions? Kind Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 921f0ae8-47c9-a0bc-06bc-3e3385f6f201
* Version Independent ID: bb6abbd5-3b12-eb5e-33c0-9a5ee9460f2a
* Content: [Requirements for Developing SharePoint Solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/sharepoint/requirements-for-developing-sharepoint-solutions)
* Content Source: [docs/sharepoint/requirements-for-developing-sharepoint-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/sharepoint/requirements-for-developing-sharepoint-solutions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@aendie Thanks for your feedback. This is in the backlog queue; FYI.

**Comment by ucheNkadiCode** [comment]
This page has been changed and there are no longer any problematic requirements listed. It now redirects to 
[Getting Started (Sharepoint Development in Visual Studio)](https://docs.microsoft.com/en-us/visualstudio/sharepoint/getting-started-sharepoint-development-in-visual-studio?view=vs-2017)

**Comment by ucheNkadiCode** [comment]
#please-close
