### ISSUE TITLE
This script deleted my keystore

### ISSUE THREAD

**Issue by jvlppm** [MicrosoftDocs/visualstudio-docs#1345]
My Android app (that is on the store) was signed by a key generated by Visual Studio,
When my Visual Studio stopped working I had to uninstall it, and then reinstall it (just reinstalling didn't work).

I just found out that the Android signing keys generated by VS were stored by default under ~/Library/Developer/Xamarin/Keystore

And this directory was deleted by this script, now I can't update my app anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Uninstalling Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall.md)
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by MarkMcGee1** [comment]
It looks like this issue has been addressed, so I am closing this. Thanks!
