### ISSUE TITLE
Deployment Errors with SharePoint 2016

### ISSUE THREAD

**Issue by aendie** [MicrosoftDocs/visualstudio-docs#1346]
Error occured in deployment step 'Activate Features': Cannot complete this action ...
Please try again.
I tried this twice, obviously adapting the steps suitably to Visual Studio 2017 and SharePoint 2016.
Using DEBUG mode, I had an error on line 1647 of the ScriptResource:
if (Sys.__registeredTypes[name]) throw Error.invalidOperation(String.format(Sys.Res.typeRegisteredTwice, name));
I have no idea how to continue and this is the first Walkthrough I am attempting on a new SharePoint 2017 installation on Windows Server 2012 R2. My trial license expires in 135 days. Any help appreciated as I need to get onto more complicated examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7178d59e-622a-fcd3-0d76-229a8b42dfc0
* Version Independent ID: 691c82da-8ed3-6dc0-b37e-b5e4c219f2c2
* Content: [Walkthrough: Create a Site Column, Content Type, and List for SharePoint - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint)
* Content Source: [docs/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@aendie Thanks for your feedback. We are aware that the documentation is outdated; it's in our backlog queue at the moment. However, for immediate assistance, please consider using the [StackOverflow](https://stackoverflow.com/questions/tagged/sharepoint-2016) site (and note that the link I've included goes directly to a collection of questions and answers that are tagged with "SharePoint 2016").

**Comment by John-Hart** [comment]
The document has been updated
