### ISSUE TITLE
safeitemname and itemname usage

### ISSUE THREAD

**Issue by DaanV2** [MicrosoftDocs/visualstudio-docs#1347]
safeitemname and itemname are based on my experience on the filename that gets added into the project. so when you added something onto the filename that same addition goes onto the parameters safeitemname and itemname

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Visual Studio project and item template parameters - Visual Studio](https://docs.microsoft.com/nl-nl/visualstudio/ide/template-parameters)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by daniloToebdot** [comment]
We can use $rootnamespace$ at item templates which contains the whole namespace, however there seems to be no way to get only the $projectname$ for an item template, which would help me greatly.
The problem I'm facing is to create an item which will access 'global::$projectname$.Properties.Resources', is there a way to do this on an item template?
