### ISSUE TITLE
Where is the listing of MSBuild properties

### ISSUE THREAD

**Issue by mwpowellhtx** [MicrosoftDocs/visualstudio-docs#1350]
Those that can appear in a ``PropertyGroup`` for instance.

On one hand, I get it, that some can be user-defined. But where are the sort of boilerplate, built-in ones listed? Having a hard time finding that reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73afcd0b-3717-082a-e429-428bfac1c826
* Version Independent ID: 7f6f3bd1-c584-6a63-513d-a541db4e585c
* Content: [MSBuild Project File Schema Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference)
* Content Source: [docs/msbuild/msbuild-project-file-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-project-file-schema-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Did you see this page? 
https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties
It would not include properties that are specific to certain app types.

**Comment by mwpowellhtx** [comment]
@Mikejo5000 Does not include references to things such as ``AssemblyVersion`` or ``FileVersion``, which is what I am chiefly after, and correspondence between the *CSPROJ* style specifications and the *AssemblyInfo* ``Attribute`` specs. I was able to uncover the actual ``MSBuild`` targets which make the mapping happen, which is helpful to me learning what the names should be.

**Comment by mwpowellhtx** [comment]
@Mikejo5000 @rainersigwald I don't think it's a question whether you are. You are. The question is what you want to do about that lack of coverage.
