### ISSUE TITLE
Incorrect Example

### ISSUE THREAD

**Issue by dckrinke** [MicrosoftDocs/visualstudio-docs#1353]
The HelloWorld code does not work. The Visual Studio 17 compiler gives: 
1 Error: Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0017	Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point.	HelloWorld	C:\Users\dckri\Documents\Visual Studio 2017\Projects\HelloWorld\HelloWorld\Program.cs	7	Active

How do I get the most simple example to work? 
Dennis Krinke 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* Content: [Overview of Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide#tour-of-the-ide)
* Content Source: [docs/ide/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-ide.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@dckrinke I'm surprised you're getting this error. Can you paste the contents of your Program.cs file here?

**Comment by dckrinke** [comment]
using System;
namespace HelloWorld
{
    class HelloWorld
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}

**Comment by gewarren** [comment]
When I create a new .NET Core console app the class is named Program, not HelloWorld, which might be the issue. Try renaming your class to Program and see if that fixes it. Do you have any other .cs files in your project?

**Comment by dckrinke** [comment]
You are right, that was it.
Thanks for your help,
Dennis Krinke

**Comment by gewarren** [comment]
You're welcome!
