### ISSUE TITLE
Are there any drawbacks to using "Embedded" other than file size?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1354]
"please fill out this field"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56f58310-fec4-2374-f9b1-253ae98fccf9
* Version Independent ID: 38ebce67-8953-ce1b-a082-e39c936d5865
* Content: [Advanced Build Settings Dialog Box (C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/advanced-build-settings-dialog-box-csharp)
* Content Source: [docs/ide/reference/advanced-build-settings-dialog-box-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/advanced-build-settings-dialog-box-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by cartermp** [comment]
No, there are not meaningful drawbacks. The feature is generally for more advanced scenarios though, such as easing the use of various performance analysis tools.

**Comment by StingyJack** [comment]
Thanks!
