### ISSUE TITLE
Data binding in unit test?

### ISSUE THREAD

**Issue by kasturi3k** [MicrosoftDocs/visualstudio-docs#1356]
If I have a unit test that is part of the text mix in my load test, can I use data binding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7520d8a3-ed9d-7f74-d948-09d1c8e1bd7b
* Version Independent ID: 00dfbec4-e63a-27d7-1935-8475ff770516
* Content: [Add a data source to a web performance test in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/add-a-data-source-to-a-web-performance-test)
* Content Source: [docs/test/add-a-data-source-to-a-web-performance-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/add-a-data-source-to-a-web-performance-test.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@boraprachi Can you help to answer this question please?

**Comment by PBoraMSFT** [comment]
@kasturi3k You can add data-binding by declaring the appropriate data source as an attribute on the unit test.
See this doc for example https://docs.microsoft.com/en-us/visualstudio/test/creating-a-data-driven-coded-ui-test?view=vs-2017 

@gewarren - can you please close the issue? I dont seem to have the permissions.
