### ISSUE TITLE
Solution Outline

### ISSUE THREAD

**Issue by RCVarley** [MicrosoftDocs/visualstudio-docs#1357]
It would be helpful if, at the start, you could show a solution outline to give us an 'at a glance' overview of the solution structure.

Even more helpful, would be an interactive element that contains the file structure (similar to that of the Solution Explorer) of the finished product that can be downloaded.  Linking this to a GitHub repository would be the icing on the cake.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21714a79-85d5-7bc4-be1a-f8309ffbd15a
* Version Independent ID: 5611a3ee-ec02-e60d-550b-14eb4b38917a
* Content: [How to: Use Wizards with Project Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates)
* Content Source: [docs/extensibility/how-to-use-wizards-with-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-wizards-with-project-templates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by PawcioCNCProfi** [comment]
I believe this is not exactly how it's described in the article but it works for me. I'm using only item template at the moment. 

I have 3 projects 

- **ExtensionVISX**  - main project of the extension to start experimental instance with.
- **TemplatesWizardsVSIX** - containing the `IWizard` implementation. I believe it can contain wizards for multiple templates, based on `<FullClassName>` element existence.
- **ItemTemplateProject** - containing the template definition.



1. Create `key.snk` file through project's properties (from solution item context menu) of **TemplatesWizardsVSIX** project

2. Use `sn.exe` to extract public key from the `key.snk` file

3. Add `<WizardExtension>` element to `<VSTemplate>`  element of `.vstemplate` file in **ItemTemplateProject** as described in the article. Use previously extracted key as `PublicKeyToken` attribute of `<Assembly>` element.

4. Add both of the projects as assets to `.vsixmanifest` file of the **ExtensionVISX** project.

   I've added:

   - **TemplatesWizardsVSIX** as  `VSPackage` asset type
   - **ItemTemplateProject** as `ItemTemplate` asset type

   Both assets are add as "project in solution"

5. Compile wizards and template projects first and start the **ExtensionVISX** project.

![templates](https://user-images.githubusercontent.com/57447464/71085582-248a2400-2198-11ea-97d1-70e6f9bcc2c5.png)

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
