### ISSUE TITLE
Where is the default projects folder?

### ISSUE THREAD

**Issue by drich-colorman** [MicrosoftDocs/visualstudio-docs#1359]
In ALL earlier versions of VS my new projects were always placed in a Projects folder in Visual Studio in My Documents.  Now, they are splattered all over my computer and most annoyingly in folders that I cannot even find with a search.  A search in HELP on how to setup or assign a default projects folder returns .. Nothing.  So not only have you changed how the Studio works you did not even both to document that fact.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@drich-colorman the default location for new project creation is `%USERPROFILE%\source\repos`. I'll try to find out if this is configurable and if it is I'll update this article.

**Comment by gewarren** [comment]
There is a setting to change the default project location in Tools > Options > Projects and Solutions > Locations:

![image](https://user-images.githubusercontent.com/24882762/56515049-ccf1c680-64eb-11e9-9647-0c94c3f8dcb5.png)

**Comment by craigcaseyMSFT** [comment]
Issue resolved in referenced PR. Closing now. Thanks!
