### ISSUE TITLE
Update, please...

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/visualstudio-docs#1360]
@NakSuKao commented on [Tue Aug 07 2018](https://github.com/MicrosoftDocs/visualstudio-docs.it-it/issues/5)

This documentation is ok for old framework versions.

Please, update because the following configSections element in the app.config file isn't good for .Net Framework 4.6.1.

&lt;configSections&gt;
        &lt;section name="microsoft.visualstudio.testtools" type="Microsoft.VisualStudio.TestTools.UnitTesting.TestConfigurationSection, Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"/&gt;&lt;/configSections&gt;

See the following issue, I've just found looking for a solution because I have the same problem.

https://github.com/Microsoft/testfx/issues/129

I hope to be helpfull.

ES

P.S.: sorry for my English... :-D

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 53d4d170-fcf4-6caf-da44-dfe6e194a257
* Version Independent ID: c980b0f6-ed24-9c4a-0b2e-77962aafc81d
* Content: [Procedura dettagliata: Uso di un file di configurazione per definire un'origine dati in Visual Studio](https://docs.microsoft.com/it-it/visualstudio/test/walkthrough-using-a-configuration-file-to-define-a-data-source)
* Content Source: [docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md](https://github.com/MicrosoftDocs/visualstudio-docs.it-it/blob/live/docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by LisandroSu** [comment]
Hi team,

Can you check on this request for an update on the file?

Thanks!

**Comment by samkramer** [comment]
The following configuration file works for modern .NET framework versions:
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="microsoft.visualstudio.testtools" type="Microsoft.VisualStudio.TestTools.UnitTesting.TestConfigurationSection, Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions" />
  </configSections>
  <connectionStrings>
    <add name="ExcelConnLegacy" connectionString="Driver={Microsoft Excel Driver (*.xls)};dbq=data.xls;defaultdir=.;driverid=1046;" providerName="System.Data.Odbc" />
  </connectionStrings>
  <microsoft.visualstudio.testtools>
    <dataSources>
      <add name="ExcelDataSourceLegacy" connectionString="ExcelConnLegacy" dataTableName="Sheet1$" dataAccessMethod="Sequential"/>
    </dataSources>
  </microsoft.visualstudio.testtools>
</configuration>

**Comment by craigcaseyMSFT** [comment]
Issue resolved in referenced PR. Closing now. Thanks!
