### ISSUE TITLE
Symbols Local Variables

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/visualstudio-docs#1366]
trying to write a rule that says "local variables should be camelCase"

How do specify local variables in symbols?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b402d2e0-a53a-b61a-4da8-b5ee766d9301
* Version Independent ID: 612695df-5934-d967-d709-500ce02b1395
* Content: [.NET Naming Conventions For EditorConfig files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions)
* Content Source: [docs/ide/editorconfig-naming-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-naming-conventions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by StevenTCramer** [comment]
https://github.com/dotnet/roslyn/blob/master/.editorconfig

Has an example of how to use locals but the docs still need updated to include local.

**Comment by gewarren** [comment]
@StevenTCramer Thanks, good suggestion.

**Comment by StevenTCramer** [comment]
while at it local_functions also :)

```
# Local functions are PascalCase
dotnet_naming_rule.local_functions_should_be_pascal_case.severity = suggestion
dotnet_naming_rule.local_functions_should_be_pascal_case.symbols = local_functions
dotnet_naming_rule.local_functions_should_be_pascal_case.style = local_function_style

dotnet_naming_symbols.local_functions.applicable_kinds = local_function

dotnet_naming_style.local_function_style.capitalization = pascal_case
```

**Comment by gewarren** [comment]
@StevenTCramer Is it okay to close this issue now?
