### ISSUE TITLE
Benefit Accounts

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#1371]
Hello,

Can it be possible to include a section that states that all the benefit accounts, such as Azure credits, Office 365 Developer and VSTS, are one time benefits that cannot be recovered after activated? So, for example if a VS subscription is assigned to user  "A" via Volume Licensing, and this subscription is reassigned to user "B". In the event that the "A" user activated all the benefit accounts, user "B" will not have those benefits available once he accesses his subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58c83add-3638-8dd7-6f4a-3537aa6adff6
* Version Independent ID: fb37fe41-88ed-e7e1-f701-456625e81adb
* Content: [Visual Studio Subscriptions - Subscriber Benefits](https://docs.microsoft.com/en-us/visualstudio/subscriptions/subscriber-benefits)
* Content Source: [subscriptions/subscriber-benefits.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/subscriber-benefits.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@Nathan-Tarin thanks for your feedback! @evanwindom FYI

**Comment by evanwindom** [comment]
@Nathan-Tarin - Thanks for the question.  The benefits don't all behave the same way when a subscription is transferred from one customer to another, so addressing that in any kind of an overview isn't practical due to the complexity across the various benefits and subscription levels.
