### ISSUE TITLE
Not available on Windows 7

### ISSUE THREAD

**Issue by kvarkel** [MicrosoftDocs/visualstudio-docs#1375]
The documentation should clearly state what the requirements are to run this. This feature is not available on Windows 7 (still used by much of corporate America ).  Windows 7 users see the message "CPU Profiling while debugging is not available on this version of Windows".  
See https://developercommunity.visualstudio.com/content/problem/172052/diagnostic-tools-cpu-usage-doesnt-support-in-windo.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cbdc658-5505-37f6-3b0b-06cafe7e7c82
* Version Independent ID: c5676187-184a-8c3d-fe25-76e6c56765b0
* Content: [Measure CPU usage in your apps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-performance-profiling)
* Content Source: [docs/profiling/beginners-guide-to-performance-profiling.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/beginners-guide-to-performance-profiling.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thank you for reporting this. I'll update the docs.
