### ISSUE TITLE
Exception one

### ISSUE THREAD

**Issue by Infraton11** [MicrosoftDocs/visualstudio-docs#1378]
customize a single storage device on xbox one using linux

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and use Visual Studio extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions#extension-crashunresponsiveness-notifications)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Infraton11 Can you provide some more details about your issue or request?

**Comment by gewarren** [comment]
Closing due to lack of information.

**Comment by Infraton11** [comment]
check your local library!!Please
