### ISSUE TITLE
How to bypass 'License Term' and 'Microsoft Privacy Statement' when using Response file in command line

### ISSUE THREAD

**Issue by mirsaeidi** [MicrosoftDocs/visualstudio-docs#138]
Hi there, 

How can I bypass 'License Term' and 'Microsoft Privacy Statement' when using a `response.json` file in command line? 
I am trying to automate the installation process in chef and every-time I use `'vs_enterprise.exe --in response.json ` another windows open for 'License Term' and 'Microsoft Privacy Statement' which I have to select 'continue'. is there a way that I can bypass that or add it to my response file?

In my Response file i have; 
```
{
"installChannelUri":".\\ChannelManifest.json",
"channelUri":"https://aka.ms/vs/15/release/channel",
"installCatalogUri":".\\Catalog.json",
"channelId":"VisualStudio.15.Release",
"productId":"Microsoft.VisualStudio.Product.Enterprise",
"installPath": "C:\\VS2017",
"quiet": true,
"passive": false,
"norestart": false
} 
```
Thanks
Shah

**Comment by riverar** [comment]
Due to bugs in the installer, you must also provide --quiet or --passive to the outer installer. (e.g. `vs_enterprise.exe --quiet --in response.json`)

**Comment by riverar** [comment]
@ghogen Can you provide a status to complement this closure?
