### ISSUE TITLE
Clean up offline folder from previous

### ISSUE THREAD

**Issue by nolme** [MicrosoftDocs/visualstudio-docs#1381]
When running offline download every month (to get one location up to date for VS2017), it seems keeping previous package versions (Win10SDK, Xamarin, PortableFacades... and much more than these 3 ones).
How can we purge old not used packages ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by tydunkel** [comment]
@nolme Please see the [documentation for the clean](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2017#how-to-remove-older-versions-from-a-layout) command. This will allow you to remove the old, obsolete packages from your layout.
