### ISSUE TITLE
Give more detail on what repair will do

### ISSUE THREAD

**Issue by apawsey** [MicrosoftDocs/visualstudio-docs#1384]
When you click Repair you are presented with a warning... "Repairing visual studio will reset the environment...". It would be much more useful to explain the implications of that process in detail, rather than simply telling me where to find the button.

For example, will I need to repair other installs (like component packages, resharper, code rush, etc).  What files might it delete or reset? Is it worth backing up any of those?

Generally explain what impact it might actually have on me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5c36c-d8ef-6b2d-2c62-5243d1ac2ce1
* Version Independent ID: 91c57e20-c75c-3c8d-e31f-727fa1e2af29
* Content: [Repair Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio)
* Content Source: [docs/install/repair-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/repair-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @PoulChapman
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@apawsey Apologies that this GitHub Issue has taken us some time to respond to, but please be advised that this request, while currently placed in our backlog, is in our queue.

**Comment by TerryGLee** [comment]
@tydunkel FYI, for consideration.

**Comment by tydunkel** [comment]
@apawsey can you please file the issue in our [developer community](https://developercommunity.visualstudio.com) since this is product feedback? This will allow the product team to track upvotes and copy to the backlog for updating.

In general, a repair will reset user settings of Visual Studio like window layouts. It will also clear per-user extensions added to that instance of Visual Studio.

**Comment by apawsey** [comment]
Well no... I disagree.

The whole point here is that I went to the documentation to find out exactly what the repair process does, and the documentation is lacking. How is that product feedback? I don't want to change what repair does, just for you to explain it in the documentation better.

**Comment by tydunkel** [comment]
@apawsey sorry for the confusion. Are you requesting that the docs online be updated with more information on repair, or that the popup within the Visual Studio Installer be updated with more information?

**Comment by apawsey** [comment]
Yes sorry, I wasn't being clear. My fault. See my edit above.

**Comment by tydunkel** [comment]
@apawsey thanks for the clarification! @TerryGLee FYI, doc update to clarify the implications of a repair operation.

**Comment by TerryGLee** [comment]
@apawsey We've added a note to Step 2 on the Repair Visual Studio page that describes what Repair does; we hope that that additional information answers your inquiry. As such, we'll close the issue. However, you can still comment on the issue, and we can reopen it if need be.
