### ISSUE TITLE
Videos on Coded UI test walk through page cannot be played

### ISSUE THREAD

**Issue by Shawn1874** [MicrosoftDocs/visualstudio-docs#1386]
The issue is on the following page.
https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-editing-and-maintaining-a-coded-ui-test

The video links do not work.  Clicking the link results in "HTTP Error 503. The service is unavailable."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 449c8c80-5302-0d8b-c5a0-04b56ccb4f97
* Version Independent ID: 16c81ae7-bda9-6599-e64c-a8f73602513e
* Content: [Create a Coded UI Test in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-editing-and-maintaining-a-coded-ui-test)
* Content Source: [docs/test/walkthrough-creating-editing-and-maintaining-a-coded-ui-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-creating-editing-and-maintaining-a-coded-ui-test.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Shawn1874 Thanks for reporting this. Are you able to to access this link? It contains the videos that are linked to.

https://onedrive.live.com/?id=2DB0E1EFE1C1D3B8%21110&cid=2DB0E1EFE1C1D3B8

**Comment by Shawn1874** [comment]
Yes, thank you.
