### ISSUE TITLE
Running unit tests as part of load test

### ISSUE THREAD

**Issue by Dileep17** [MicrosoftDocs/visualstudio-docs#1387]
Below is mentioned as second line of this article. 
"Load tests execute web performance or unit tests to simulate many users accessing a server at the same time." 

I tried to find a tutorial on how to run unit tests as part of load tests (visual studio 2017). It would be of great help if you can provide/add an article on how to run unit tests as part of load test. 

Reason I ask is, all the article I could found says "add unit tests to web performance project and in 'test mix' select the unit test". But I couldn't find unit test added in test mix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0780169-4b7b-97ce-5ccd-9f962472a2c8
* Version Independent ID: f0c68169-baeb-cba0-ccf0-a149fa96bb67
* Content: [Create a web performance and load test project in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project#feedback)
* Content Source: [docs/test/quickstart-create-a-load-test-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/quickstart-create-a-load-test-project.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by tdaniely** [comment]
This is a complete mystery, Must have something to do with the version of ms test used by the test project, but I can't seem to figure it out.

**Comment by gewarren** [comment]
@tdaniely Thanks for providing a solution!

Since load testing is deprecated, we are not planning to update this documentation at this time.

**Comment by MsbYuva** [comment]
VS 2019 is not supporting load test, seeing this issue when running web/load test 

"The Augument type 'System.MarshakbyRefObject' cannot be converted into parameter type 'Microsoft.vISUALStudio.TestTools.Common.FileCopyService.'

Any help is greatly appreciated..

**Comment by MsbYuva** [comment]
"The Augument type 'System.MarshalbyRefObject' cannot be converted into parameter type 'Microsoft.vISUALStudio.TestTools.Common.FileCopyService.'

**Comment by gewarren** [comment]
@msbyuva Since this issue is closed, and to make sure that your problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, you can engage directly with the engineering team while they address and fix the problem.
