### ISSUE TITLE
Incorrect callout format 

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/visualstudio-docs#1388]
The callout "Because Source Link will download files using http or https, make sure you trust the .pdb file." is formatted as source code rather than as a callout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c524aa1d-eec4-d776-8346-dfdc632eec76
* Version Independent ID: c0f65c4f-6369-10ce-5edc-0ab5fbae736a
* Content: [General, Debugging, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Debugger.General)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396)
* Content Source: [docs/debugger/general-debugging-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/general-debugging-options-dialog-box.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
@breyed Thanks for pointing this out. BTW there's an Edit button near the top right of each Visual Studio topic if you ever want to fix things like this yourself.

**Comment by breyed** [comment]
I see from the commit to fix this that it's just a matter of removing a space. Not sure if that would have been obvious had I tried to make the edit myself, but from a larger picture, it's probably good that I didn't, since the issue seems to be systemic. If it is, a systemic solution is better than a one-off fix.

A line below has a similar problem: 
> Because Source Link will download files using http or https, make sure you trust the .pdb file.  

It wouldn't surprise me if the problem exists elsewhere. A regex search through the docs codebase for cleanup would be a good idea. Even better would be identifying how the spaces are slipping in unnoticed in the first place.

**Comment by gewarren** [comment]
@breyed Thanks for the feedback. I believe the extra whitespaces were introduced when we moved the docs from MSDN to markdown format on docs.microsoft.com. We are planning a systemic fix for the extra spaces in callout blocks like IMPORTANT and NOTE. That will happen in October, I believe.
