### ISSUE TITLE
Types in Step 4.2

### ISSUE THREAD

**Issue by Shawn1874** [MicrosoftDocs/visualstudio-docs#1389]
The first two lines of coded are concatenated.   A carriage return after the first semi-colon would be helpful.  UIItemWindow21 needs to be changed to UIItemWindow2.  UIItem2TextDisplayText needs changed to UIItem3TextDisplayText .  If I follow all of the instructions exactly, the code won't compile in step 4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67f0f36-9638-5022-d856-721441de8892
* Version Independent ID: 389b1847-55a8-c97a-a562-1a6e266f4358
* Content: [Creating a Data-Driven Coded UI Test in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/creating-a-data-driven-coded-ui-test#CreateDataDrivenCUIT_QA_DataSourceAttributes)
* Content Source: [docs/test/creating-a-data-driven-coded-ui-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/creating-a-data-driven-coded-ui-test.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Shawn1874 Thanks for the feedback on these issues in the topic. I'll add this to our backlog of things to fix.
