### ISSUE TITLE
Q&A not detailed enough

### ISSUE THREAD

**Issue by Shawn1874** [MicrosoftDocs/visualstudio-docs#1390]
It would be nice to see an example or a link to where I can find an example data.xml.  The answer to the one question doesn't show an example of what data source files would look like.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c67f0f36-9638-5022-d856-721441de8892
* Version Independent ID: 389b1847-55a8-c97a-a562-1a6e266f4358
* Content: [Creating a Data-Driven Coded UI Test in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/creating-a-data-driven-coded-ui-test#CreateDataDrivenCUIT_QA_DataSourceAttributes)
* Content Source: [docs/test/creating-a-data-driven-coded-ui-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/creating-a-data-driven-coded-ui-test.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Given that Coded UI Test is deprecated, we are not planning to update this documentation at this time.
