### ISSUE TITLE
Silverlight Project Support in VS2017

### ISSUE THREAD

**Issue by LooWooL** [MicrosoftDocs/visualstudio-docs#1391]
It's really annoying that you don't support Silver-light projects in VS2017. You created this tech, and you dropped support for it. We depend on it, and we're forced to use an old version of VS to maintain it. This is irresponsible from your part towards developers that been working with your tools from the start for years and decades.
You should work on an extension that would support such projects in VS2017, as it would help us work with one single tool, and stay up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3315d1-e6d3-e86d-9cce-1ff9ce0fc482
* Version Independent ID: ae3fd143-bf0b-4cfe-bcad-557eb41fdc2c
* Content: [Port, Migrate, and Upgrade Projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects)
* Content Source: [docs/porting/port-migrate-and-upgrade-visual-studio-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/porting/port-migrate-and-upgrade-visual-studio-projects.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by gewarren** [comment]
@LooWooL Thanks for this feedback. Since your feedback is not about the documentation, you'll get more traction if you file a new report through [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) in Visual Studio. There could also be an existing issue that you could upvote instead.

**Comment by kraigb** [comment]
@LooWooL Genevieve is correct, Silverlight support is a product issue rather than a docs issue. Closing.
