### ISSUE TITLE
Parentheses can be removed (IDE0047) false-positives

### ISSUE THREAD

**Issue by shadow-cs** [MicrosoftDocs/visualstudio-docs#1392]
Following code produces false-positive when `dotnet_style_parentheses_in_relational_binary_operators` is set to `always_for_clarity`.

```csharp
public static bool Foo(int a, int b, bool c)
{
  return (a == b) == c;
}
```

Since the rule is set to always for clarity, my assumption is that the code is indeed fine as-is.

I understand that the analyzer cannot always guess the parenthesis right in these situations and should ignore the statement rather than producing the message.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **kaseyu**

**Comment by BhaaLseN** [comment]
This sounds like it belongs to [dotnet/roslyn](https://github.com/dotnet/roslyn/issues) instead, as bug in the analyzer (rather than a documentation issue).

**Comment by gewarren** [comment]
@shadow-cs I agree with @BhaaLseN this is not a documentation issue, and should be logged at https://github.com/dotnet/roslyn/issues instead.

**Comment by shadow-cs** [comment]
Thanks I'll move it to Roslyn repo then, I wasn't quite clear on where to post it actually.
