### ISSUE TITLE
This doesn't actually work

### ISSUE THREAD

**Issue by jeffkotula** [MicrosoftDocs/visualstudio-docs#1393]
When selecting code analysis for solution through the Build or Tools menu, all projects are analyzed regardless of the check box on each project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573429a4-7c2d-5ede-9c34-934cc26a4045
* Version Independent ID: 351b628e-ff1c-7a64-0c46-74887a97cd0d
* Content: [How to: Enable and Disable Automatic Code Analysis for Managed Code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code)
* Content Source: [docs/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jeffkotula It sounds like you probably have Roslyn analyzers installed, and that's what's producing the warnings at build time. The "Enable code analysis on build" checkbox doesn't have any effect on Roslyn analyzers - see the blue note box in this section https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview#roslyn-analyzers-vs-static-code-analysis. If you want to "baseline" the warnings and suppress them all, you can do that. See https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers#suppress-violations.
