### ISSUE TITLE
Clarification on the "Renewable" column

### ISSUE THREAD

**Issue by nickpainter** [MicrosoftDocs/visualstudio-docs#1394]
Can you clarify if the "Renewable" column of the eligibility table indicates the number of times that the resource can be used within each one month period?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79453c-3962-2f0c-5b99-4fbde91972f8
* Version Independent ID: c845c29e-dfd7-316e-81b2-ebe288a384c1
* Content: [Technical Support Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-tech-support#eligibility)
* Content Source: [subscriptions/vs-tech-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-tech-support.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@nickpainter  - Thanks for your question.  The "renewable" indicates whether the benefit renews if the subscription is renewed.  For the technical support benefit, the number of incidents provided depends on the subscription level.  The incidents can be used at any time during the term of the subscription, but if they are used, they are not replaced until the subscription is renewed.  So, for example, if you purchase an annual subscription with four incidents, you can use those four at any time, but once they're used, you will need to purchase additional incidents directly from Customer Service and Support if you need additional assistance.  When you renew your annual subscription, you will once again have four incidents available.
