### ISSUE TITLE
Code metrics - command line alternative? 

### ISSUE THREAD

**Issue by pjmagee** [MicrosoftDocs/visualstudio-docs#1395]
Is there a way to calculate these without having to interact or use Visual Studio, so that it can be automated or used somehow as part of a build CI? 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b417a6f-2527-9ec4-7e00-a0ce8e55f997
* Version Independent ID: d250f719-b8d7-7b03-d883-968e0b961d49
* Content: [Calculate code metrics in Visual Studio - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/code-quality/code-metrics-values)
* Content Source: [docs/code-quality/code-metrics-values.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-metrics-values.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Manish, do you know if code metrics can be obtained at the command line?

**Comment by mavasani** [comment]
Yes, we added support for both the following:

1. Metrics.exe tool to generate a metrics report file from command line
2. Code metrics analyzer rules that flag warnings when your code metrics go above the configured or default threshold values.

See the `UPDATE` sections in https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/33459643--netcore-code-metrics for details. @gewarren, we should probably update the docs accordingly.

**Comment by pjmagee** [comment]
Okay I see the project in Github now that does this, however it's internal and not published as a NuGet package :( I was hoping to somehow hook in to this using a custom .NET Core Built project that scans a selection of .NET projects with a dashboard. Will this become a NuGet package at some point or will I have to build and use the exe?

**Comment by mavasani** [comment]
@pjmagee For now, you will have to build and use the exe. Please upvote or comment on  https://github.com/dotnet/roslyn-analyzers/issues/1756 so we can prioritize that work item. Tagging @jinujoseph as well.

**Comment by gewarren** [comment]
I added a section about calculating code metrics at the command line - https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017#command-line-code-metrics. Closing this issue.
