### ISSUE TITLE
Further Directory.Build.props/targets inclusion can be made more generic

### ISSUE THREAD

**Issue by grantborthwick** [MicrosoftDocs/visualstudio-docs#1396]
The current article recommends including the following Import to include subsequent Directory.Build.props files in your project's directory tree.
&lt;Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" /&gt;

This can be made more generic to work for both Directory.Build.props and Directory.Build.targets
&lt;Import Project="$([MSBuild]::GetPathOfFileAbove($(MSBuildThisFile), $(MSBuildThisFileDirectory)..\))" /&gt;

Further, this can be made to work regardless of whether subsequent Directory.Build.* files exist (only recommended if you control and trust parent directories).
&lt;Import Project="$([MSBuild]::GetPathOfFileAbove($(MSBuildThisFile), $(MSBuildThisFileDirectory)..\))" Condition="Exists($([MSBuild]::GetPathOfFileAbove($(MSBuildThisFile), $(MSBuildThisFileDirectory)..\)))" /&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by roozbehid** [comment]
actually I was having some strange errors with "value of the project attribute in element import is invalid " this solution solved my problem.

**Comment by msebolt** [comment]
@grantborthwick Thank you for the feedback!  Though while this solution is more flexible, it moves away from the main topic of concern which is Directory.Build.props.

Thank you for this suggestion and will definitely keep it under consideration for future restructuring of the article.
