### ISSUE TITLE
Synchronized settings changed in VS 15.8

### ISSUE THREAD

**Issue by dparvin** [MicrosoftDocs/visualstudio-docs#1399]
It looks like this page has changed in VS 15.8 to the Accounts page. An addition of a new checkbox has also been added to the page and the page in VS 15.8 sends you here when you press F1, which means there might be a change to VS that needs to point to a new page if you make one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb842290-abbe-1af6-f560-466ce31fd37f
* Version Independent ID: 10a3fd9b-3c63-2d34-ad52-1c285e3fa39b
* Content: [Synchronized Settings, Environment, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/synchronized-settings-environment-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Environment.RoamingSettings)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6)%3Bk(DevLang-VB)%26rd%3Dtrue)
* Content Source: [docs/ide/reference/synchronized-settings-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/synchronized-settings-environment-options-dialog-box.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@dparvin Thank you David! I'll update this as time permits.

**Comment by gewarren** [comment]
Reopening to address the undocumented check box on the Accounts option page.

**Comment by gewarren** [comment]
The topic has been updated with the new options - https://docs.microsoft.com/en-us/visualstudio/ide/reference/accounts-environment-options-dialog-box?view=vs-2017.
