### ISSUE TITLE
Modifier not working correctly

### ISSUE THREAD

**Issue by KamarasV** [MicrosoftDocs/visualstudio-docs#1400]
I have specified these two rules because I want the static fields to start with s_ and the other fields to start with m_

dotnet_naming_rule.rule1.symbols                      = rule1_symbol
dotnet_naming_rule.rule1.style                                           = rule1_style
dotnet_naming_rule.rule1.severity                                      = error
dotnet_naming_symbols.rule1_symbol.applicable_kinds   = field
dotnet_naming_symbols.rule1_symbol.required_modifiers = static
dotnet_naming_style.rule1_style.capitalization        = pascal_case
dotnet_naming_style.rule1_style.required_prefix       = s_

dotnet_naming_rule.rule2.symbols                      = rule2_symbol
dotnet_naming_rule.rule2.style                        = rule2_style
dotnet_naming_rule.rule2.severity                     = error
dotnet_naming_symbols.rule2_symbol.applicable_kinds   = field
dotnet_naming_style.rule2_style.capitalization        = pascal_case
dotnet_naming_style.rule2_style.required_prefix       = m_

After that if a simple class like this is created:

public class StringHandling
{
        public const int m_Abc = 1;
        public static int s_Age;
}

The VS underlines the m_Abc: "Missing prefix s_"
I really do not understand it because the first rule is for static fields only.

**Comment by gewarren** [comment]
@KamarasV Thanks for this feedback. It sure seems like a bug to me. I noticed that if you remove the 'const' modifier from m_Abc then the naming rule for s_ doesn't show a violation. @sharwell Can you take a look at this? @KamarasV you should also open an issue at https://github.com/dotnet/roslyn/issues because this issues page is for the docs repo, and this doesn't appear to be a documentation issue.

**Comment by sharwell** [comment]
`static` matches both explicitly `static` and implicit static (`const`). To provide a separate behavior for `const` fields, you'll need to create a rule for `required_modifiers=const` before the rule for static fields.
