### ISSUE TITLE
Modifier problem

### ISSUE THREAD

**Issue by KamarasV** [MicrosoftDocs/visualstudio-docs#1401]
I have specified these two rules because I want the static fields to start with s_ and the other fields to start with m_

dotnet_naming_rule.rule1.symbols                      = rule1_symbol
dotnet_naming_rule.rule1.style                                           = rule1_style
dotnet_naming_rule.rule1.severity                                      = error
dotnet_naming_symbols.rule1_symbol.applicable_kinds   = field
dotnet_naming_symbols.rule1_symbol.required_modifiers = static
dotnet_naming_style.rule1_style.capitalization        = pascal_case
dotnet_naming_style.rule1_style.required_prefix       = s_

dotnet_naming_rule.rule2.symbols                      = rule2_symbol
dotnet_naming_rule.rule2.style                        = rule2_style
dotnet_naming_rule.rule2.severity                     = error
dotnet_naming_symbols.rule2_symbol.applicable_kinds   = field
dotnet_naming_style.rule2_style.capitalization        = pascal_case
dotnet_naming_style.rule2_style.required_prefix       = m_

After that if a simple class like this is created:

public class StringHandling
{
        public const int m_Abc = 1;
        public static int s_Age;
}

The VS underlines the m_Abc: "Missing prefix s_"
I really do not understand it because the first rule is for static fields only.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b402d2e0-a53a-b61a-4da8-b5ee766d9301
* Version Independent ID: 612695df-5934-d967-d709-500ce02b1395
* Content: [.NET Naming Conventions For EditorConfig files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions)
* Content Source: [docs/ide/editorconfig-naming-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-naming-conventions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@KamarasV This looks like the same issue as #1400. Can I close this one in favor of #1400?
