### ISSUE TITLE
Visual studio build tool installation failed

### ISSUE THREAD

**Issue by user2301** [MicrosoftDocs/visualstudio-docs#1402]
Hi, I am trying to install visual studio build tools in windows docker container following this link as reference https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container.
I changed the base image microsoft/dotnet-framework:4.7.1, as I got Host OS and container os version do not match. I have configured the proxy settings. Whenever I try to build the docker image it fails to download. I also tried to download https://aka.ms/vs/15/release/vs_buildtools.exe  first and then copy the executable to container. But it did not work. Internally, it was calling another web request. 
If this is the problem with network, How can I completely do the offline installation for Visual studio build tools 2015 or 2017 in docker container? 
 PFA vslogs.
[vslogs.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/2297085/vslogs.zip)

Below are the details of OS, docker. 
```
OS Edition : Windows Server 2016 Datacenter
OS build 14393.2363
Version: 1607

C:\Windows\system32>docker version
Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

dockerfile
```
# escape=`

#ARG FROM_IMAGE=microsoft/dotnet-framework:4.7.1-20180410-windowsservercore-1709
#FROM ${FROM_IMAGE} 
FROM microsoft/windowsservercore:10.0.14393.2189

# Copy our Install script.
COPY Install.cmd C:\TEMP\

# Download collect.exe in case of an install failure.
ADD https://aka.ms/vscollect.exe C:\TEMP\collect.exe

# Use the latest release channel. For more control, specify the location of an internal layout.
ARG CHANNEL_URL=https://aka.ms/vs/15/release/channel
ADD ${CHANNEL_URL} C:\TEMP\VisualStudio.chman

# Download and install Build Tools excluding workloads and components with known issues.
ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe
RUN C:\TEMP\Install.cmd C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --channelUri C:\TEMP\VisualStudio.chman `
    --installChannelUri C:\TEMP\VisualStudio.chman `
    --all `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK

# Start developer command prompt with any other commands specified.
ENTRYPOINT C:\BuildTools\Common7\Tools\VsDevCmd.bat &&

# Default to PowerShell if no other command specified.
CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]

```

**Comment by tydunkel** [comment]
@user2301 A layout can be created first, allowing you to install Visual Studio without an internet connection. To do this, follow the directions at [Create a network installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017). You will need access from the container to the layout, so you will likely need to copy the layout from the host into the container before running the install.
