### ISSUE TITLE
ios must have secure endpoint 

### ISSUE THREAD

**Issue by Oostwegel** [MicrosoftDocs/visualstudio-docs#1403]
string queryString = "http://api.openweathermap.org/data/2.5/weather?zip="
                + zipCode + ",us&appid=" + key + "&units=imperial";

should use https://api.openweathermap.org

**Comment by gewarren** [comment]
This is the topic: https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio#write-shared-data-service-code

@Oostwegel Thanks for reporting this.

**Comment by gewarren** [comment]
This article now redirects to a different one. Closing the issue.
