### ISSUE TITLE
Muddled walkthrough

### ISSUE THREAD

**Issue by SteveMcArthur** [MicrosoftDocs/visualstudio-docs#1404]
This seems to be a bit muddled.
When you create a new project using the "Excel VSTO Add-in project template" the "ThisAddIn.cs" or "ThisAddIn.vb" file are not created - this only happens when creating a project without the template.

Later on we create a new class "AddInUtilities" in a corresponding .cs or .vb file. However, later on the "ThisAddIn" file returns and we are told the AddInUtilities class is in that file.

Now, this wouldn't be so bad but I get errors when trying to use "Globals.ThisAddIn" and  errors when trying to add the "RequestComAddInAutomationService" override. So I think something is wrong with the walkthrough.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3411102-1d97-d7b3-4e25-6c67ae3ad3cf
* Version Independent ID: 63316592-1e4c-39c1-406c-553ae883a90b
* Content: [Walkthrough: Call code in a VSTO Add-in from VBA - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/vsto/walkthrough-calling-code-in-a-vsto-add-in-from-vba)
* Content Source: [docs/vsto/walkthrough-calling-code-in-a-vsto-add-in-from-vba.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-calling-code-in-a-vsto-add-in-from-vba.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@SteveMcArthur Thanks for letting us know. We're aware that the page could use some updating; it's in our backlog.

**Comment by ucheNkadiCode** [comment]
This walkthrough worked exactly as intented. There is a chance the user made a mistake in the walkthrough or misunderstood that the  AddInUtilities file is an interface (excel writing tool) that is put into the main "ThisAddIn" file. There was no errors in using the VS2017 and the newest excel.

**Comment by ucheNkadiCode** [comment]
#please-close
