### ISSUE TITLE
Current release notes for VS 2017 15.8 still missing some related new features information

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/visualstudio-docs#1405]
Current release notes for VS 2017 15.8 (especially 15.8.0) still missing some features information.

For example:

- [x]  ASP.NET new feature on build performance tooling: https://github.com/aspnet/Tooling/blob/master/optimize-build-performance-for-solution.md
- [ ] VS Account login changes: https://github.com/MicrosoftDocs/visualstudio-docs/issues/1399
 
And this list will be updated if there are other elements found.

**Comment by gewarren** [comment]
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes?context=visualstudio/default&contextView=vs-2017

**Comment by eriawan** [comment]
@gewarren 

The link https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes?context=visualstudio/default&contextView=vs-2017 only display release notes of 15.9.0, and the release notes of 15.8 still has no mention about the VS account login changes and ASP.NET new feature on build tooling.

Please confirm.

**Comment by gewarren** [comment]
Yes, I just put the link in there to have a direct link to the article in question. I wasn't stating that the work had been done. I'm contacting someone about this issue now.

**Comment by eriawan** [comment]
@gewarren 
Apologize, I thought that link has the updated content. Thanks for the reply and update!

I hope the content will be updated soon, especially for 15.8 release notes.

**Comment by gewarren** [comment]
@anzhou5 Can you take a look at updating the release notes?

**Comment by gewarren** [comment]
The ASP.NET build performance tooling has been added to the release notes - https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-v15.8#aspnetbuildperf. Thank you @anzhou5!

**Comment by eriawan** [comment]
@gewarren 

Thanks for the update! What about the VS login changes as described in #1399 ? Has this feature documented?

**Comment by gewarren** [comment]
@eriawan The account changes are documented here:

https://docs.microsoft.com/en-us/visualstudio/ide/work-with-multiple-user-accounts?view=vs-2017#add-an-account-using-device-code-flow

and 

https://docs.microsoft.com/en-us/visualstudio/ide/reference/accounts-environment-options-dialog-box?view=vs-2017

Please let me know if you still feel something is missing.
