### ISSUE TITLE
Offline installation only usable for 30 days

### ISSUE THREAD

**Issue by Jon007** [MicrosoftDocs/visualstudio-docs#1406]
While the offline installation according to these instructions does work, the article fails to mention an important limitation, that the install will only be usable for 30 days due to online activation requirement.   
Environments with limited or no internet access do still exist and it would be helpful to explain here whether or not Visual Studio can be used in an offline environment and if so, how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an Offline Installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Jon007 Thanks for your feedback! We'll investigate and update the page as necessary. @tedvz FYI.

**Comment by jose8789** [comment]
Do the new "Download, then install" files can be used as local cache and install in many computers?

**Comment by tvkit** [comment]
The 30 day limit was a rude surprise.  Would have been helpful for MS to mention this limit prior to the numerous offline installations that were made.

**Comment by maxwellb** [comment]
@Jon007 You may want to check ["Enable VS Community activation/registration offline" on UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/9563619).

It sounds like your use case is not supported.

> This may not be the answer that you want to hear, but we do require occasional online connectivity as a requirement of using Visual Studio Community.

**Comment by Jon007** [comment]
This github issue is not a complaint about the use case, this is a complaint that the restriction and related guidance are not mentioned AT ALL in the referenced documentation about offline installations.
The article gives solution for offline installation, however the fact that offline usage is not supported is a significant relevant point that users should take into account before considering offline installation for environments which cannot be connected to the internet.
By not mentioning the connectivity requirement the article may mislead users into thinking offline use is supported and result in frustration and wasted time.
The issue remains open as the article still appears to encourage offline use and no note has been added.

**Comment by SpiritualMadMan** [comment]
I am confused... Is it the Layout files that are limited to 30 days or activation after installation?

I would expect to have to go on line for activation, at some point.

But, I wouldn't expect the layout/installation files to be disallowed after 30 days...

**Comment by Jon007** [comment]
It's activation after installation.

A common use case for offline installation files is usage on machines which are not allowed internet access - otherwise you wouldn't really need offline installation.

The offline installation should come with a warning that offline use is not supported, to avoid surprises 30 days after installing on a machine where it cannot be activated, otherwise the offline installation seems to imply offline usability.

For those who have used Visual Studio since the 1990s this online activation requirement is still quite a new thing and judging by the widespread comments, not everyone is used to it yet.

**Comment by tvkit** [comment]
@TerryGLee  Why can't the documentation for offline installations be corrected, and this case closed?

The issue points to a major documentation failure that cost our firm a grand in consulting fees  -- certainly something worth discussing.

**Comment by TerryGLee** [comment]
The documentation will be updated shortly. Our delay was due to our performing an internal review of this content.

**Comment by TerryGLee** [comment]
We've updated the "Use the command line to create a local cache" section of the [Create an offline installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#use-the-command-line-to-create-a-local-cache) page to say, "If you install Visual Studio Community 2017, you must activate it within 30 days of installation. This requires an internet connection."

**Comment by Jon007** [comment]
thanks, this has been a fascinating insight into the documentation update process, and yes, I hope for Microsoft's sake that other updates are quicker.
Microsoft documentation used to be the best, now with the retirement and/or deprecation of entire MS documentation sites (which are still referred to by innumerable other sites) and indeed technologies, it isn't always getting easier to find the correct information but it's good to know that updates and corrections can happen.
