### ISSUE TITLE
Document ProduceOnlyReferenceAssembly option 

### ISSUE THREAD

**Issue by chsienki** [MicrosoftDocs/visualstudio-docs#1407]
I've exposed a new MSBuild property for the CSC and VBC compilers that allows a user to instruct the compiler to emit only a reference assembly rather than compiled code. See https://github.com/dotnet/roslyn/pull/29352

I'm opening this here to track adding it to the documentation when it becomes available for use in the public release. 

We should document it with something like:

> ProduceOnlyReferenceAssembly: A boolean value that when set to true enables producing a reference assembly as the primary output assembly. The assembly created when using this option cannot be used for execution. This property corresponds to the /refonly switch of the vbc.exe and csc.exe compilers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
@chsienki Which sprint will this be available in?

**Comment by Mikejo5000** [comment]
Updating
