### ISSUE TITLE
Publishing to MiniKube?

### ISSUE THREAD

**Issue by natiki** [MicrosoftDocs/visualstudio-docs#1411]
Is there any chance of support for MiniKube?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools)
* Content Source: [docs/deployment/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-kubernetes-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by bremnes** [comment]
I wish Microsoft could be more neutral with these kind of tools. If you want to provide Kubernetes support, an _open source_ project, why not provide an agnostic Visual Studio tool which lets you deploy to Minikube, Docker for windows/mac, EKS, AKS, GKE or even a self-provided Kubernetes cluster hosted in your own data center?

(This goes for the tightly coupling to dev spaces as well. Why not make a little effort in to opening this toolkit for the entire community? Do as others, open source the project, create an operator of some kind for running on the cluster, and then allow cloud/local providers to add their own implementation layer if necessary.)

**Comment by gewarren** [comment]
A better place to file a product suggestion is at [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8). There, the suggestion can be upvoted, and the product team will update the status of the suggestion with labels as it moves through the system.

**Comment by craigcaseyMSFT** [comment]
It looks like this issue has been addressed, so I am closing this. Thanks!

**Comment by natiki** [comment]
@craigcaseyMSFT It has not been addressed because ultimately there is still no documentation about Minikube on https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-kubernetes-tools so for me it is not done.  ;-)

@gewarren  As for logging this to the Developer Community, as the original "log an issue with documentation" comes to this repo. If Microsoft needs it somewhere else then we should:

a) Not be directed to this repo

OR

b) Add the necessary log wherever they need it to be actioned and then close this issue

Reporters of cases should not have to know MS internal processes. I followed the reporting link.

**Comment by gewarren** [comment]
@natiki Apologies, I thought you were requesting MiniKube support in the product. Rather, you are asking for this scenario to be covered in the docs. I'll change the issue type to documentation feedback in that case.

**Comment by ckarras** [comment]
So what's the answer? If I understand correctly: Minikube is supported by VS2019 but there's no documentation on how to use it yet?

**Comment by ckarras** [comment]
In case the real answer is that it's not supported, please vote for https://developercommunity.visualstudio.com/idea/425380/kubernetes-tools-for-visual-studio-support-for-loc.html to increase our chances of getting this supported eventually.

**Comment by ghogen** [comment]
The Marketplace [page](https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools) says that MiniKube support is experimental.  It sounds like a scenario that would be interesting to cover in the docs.

**Comment by davidbIQ** [comment]
The link for marketplace is for vscode, not for full visual studio, IMO the pass park for this is start new Kubernetes project, and if you have minikube installed, it is a option in the drop down run list like Docker, IIS, Kuberneties2, and AzureDevSpaces.  It may require installing an extension but it really shouldn't.

**Comment by ghogen** [comment]
It looks like this is not a supported product scenario in Visual Studio, so we really have no choice but to close this issue until that changes.  As stated earlier, Dev Community is the place to advocate for adding support.
