### ISSUE TITLE
Add info about yellow/green borders around Bindings in Live Property Explorer

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/visualstudio-docs#1414]
VS highlights bindings in the property explorer in Yellow or Green.  I originally thought this had to do with the `IsBindingValid` property, but that doesn't appear to be the case.  I can't seem to find any info about what the two colors are supposed to represent.  Having them here in the docs would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2baf39-d3c3-5d5a-d93c-f4040430c3dd
* Version Independent ID: c443e681-03f0-ea47-a09d-718693448b3d
* Content: [Inspect XAML properties while debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/inspect-xaml-properties-while-debugging)
* Content Source: [docs/debugger/inspect-xaml-properties-while-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/inspect-xaml-properties-while-debugging.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@michael-hawker Thanks! I'll try to find that info and get it in the doc.

**Comment by Mikejo5000** [comment]
Here's what I have on this:
Yellow border means that the property value is set through a binding   Color = {Binding xXXX}.   Green border means that the value is set using a resource  Color = {StaticResource XXXX} 

I'll update the docs.

**Comment by JimHume** [comment]
Updating the docs would be great, however they don't appear where I think they would. I selected the control with the yellow binding and pressed F1. It took me to the following link which describes how to setup projects and solutions: https://docs.microsoft.com/en-us/visualstudio/ide/creating-solutions-and-projects?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.2)%26rd%3Dtrue&view=vs-2017

A tooltip would be very valuable.

**Comment by Mikejo5000** [comment]
Updated doc with info about the yellow and green borders.

The F1 keyword passed is generic, so I get the default F1 help page. To get an F1 keyword added in the IDE for these windows, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
