### ISSUE TITLE
CA1014 - Obsolete?

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/visualstudio-docs#1417]
@Thieum commented on [Tue Aug 21 2018](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/issues/17)

Should this rule and associated attribute be considered obsolete considering even dlls from .NET Core won't be CLS Compliant? https://github.com/aspnet/Home/issues/2689 . Considering it's "viral form" since all dependencies exposed on public api need to be CLS compliant too, it would relieve the library authors of the requests about supporting this.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 94e36897-6dc2-65f6-30c0-a53d054bd9fd
* Version Independent ID: 58289e5c-cb97-cdfb-58e5-3f4a315d047f
* Content: [CA1014 : Marquer les assemblys avec CLSCompliantAttribute](https://docs.microsoft.com/fr-ca/visualstudio/code-quality/ca1014-mark-assemblies-with-clscompliantattribute)
* Content Source: [docs/code-quality/ca1014-mark-assemblies-with-clscompliantattribute.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/code-quality/ca1014-mark-assemblies-with-clscompliantattribute.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by LisandroSu** [comment]
Hi Team,

Can you help the user with their concern?

Thanks!

**Comment by gewarren** [comment]
@mavasani Will CA1014 be ported to Roslyn analyzers?

**Comment by mavasani** [comment]
CA1014 has already been ported to roslyn-analyzers, see https://github.com/dotnet/roslyn-analyzers/issues/652. Note the rule only fires if the compilation has a definition for CLSCompiant attribute.

This rule is not really dependent on the platform - it depends on existence of a non-obsolete CLSCompiant attribute in the compilation. So, I am not sure if the fact that one specific platform decides to ship non-compliant libraries should make this rule obsolete. If a specific platform really considers CLSCompliant attribute to be obsolete, then it should mark it obsolete or remove its definition, and the analysis will do the right thing for that platform.

**Comment by gewarren** [comment]
@mavasani Thanks for responding. Closing the issue.
