### ISSUE TITLE
Visual Studio 2017 Version 15.8.1で利用できる ptvsdバージョンについて

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/visualstudio-docs#1419]
@bardno1 commented on [Tue Aug 21 2018](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/65)

Python ツール/ptvsd のバージョンを「4.1.1a9」にしろと怒られます。
大事な内容なので記載をお願いします

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 904b359d-de5e-adf4-9966-e1ab5be204be
* Version Independent ID: 564c35dd-ac25-8db4-ea48-e76476c50f89
* Content: [リモート Linux コンピューターでの Python コードのデバッグ](https://docs.microsoft.com/ja-jp/visualstudio/python/debugging-python-code-on-remote-linux-machines)
* Content Source: [docs/python/debugging-python-code-on-remote-linux-machines.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/python/debugging-python-code-on-remote-linux-machines.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by LisandroSu** [comment]
Hi team,

The user wants the "Python tool/ptvsd to "4.1.1a9"."  listed in the document "it's important content".

Thanks!

**Comment by kraigb** [comment]
@bardno1 thanks for letting me know! I see that the table with ptvsd and VS versions needs an update, which I'll do shortly.

**Comment by kraigb** [comment]
Changes made. The default ptvsd version in 15.7 is 4.1.1a1, and in 15.8 it's 4.1.1a9.
