### ISSUE TITLE
CONTRIBUTING.md file missing

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#1421]
@p1v0t commented on [Mon Jul 23 2018](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr/issues/3)

CONTRIBUTING.md file missing in [this repo](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr) therefore some links broken on [README.md](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr/blob/live/README.md). 

---

@LisandroSu commented on [Tue Jul 24 2018](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr/issues/3#issuecomment-407533822)

Hello, @p1v0t , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team 

---

@p1v0t commented on [Tue Jul 24 2018](https://github.com/MicrosoftDocs/visualstudio-docs.tr-tr/issues/3#issuecomment-407542445)

Ohh, thank you for care.

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since it has to do with the source files for this repo

**Comment by gewarren** [comment]
@p1v0t thanks for letting us know! I'll add this to my backlog.

**Comment by gewarren** [comment]
This is fixed now.
