### ISSUE TITLE
VS UX Guidelines is nested twice

### ISSUE THREAD

**Issue by MV10** [MicrosoftDocs/visualstudio-docs#1425]
The "Visual Studio User Experince Guidelines" is a top-level item, and if you expand that, the only contents is another node with the same name, and the real docs are under that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc3bf85-14ed-5cd1-608a-064975587367
* Version Independent ID: adc0a5fb-1b6b-5ed7-1a56-e903f5eeb3be
* Content: [Visual Studio User Experience Guidelines - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/visual-studio-user-experience-guidelines)
* Content Source: [docs/extensibility/ux-guidelines/visual-studio-user-experience-guidelines.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/visual-studio-user-experience-guidelines.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@MV10 Thanks for pointing this out. @gregvanl The issue is in the TOC.yml file.
