### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by prnadago** [MicrosoftDocs/visualstudio-docs#1426]
Link in the Note to develop code without projects and solutions is 404.
https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@prnadago This seems to be a glitch on the site. Can you try the link again? I think a 404 may have just flashed in front of me, too, but now it's working.

**Comment by gewarren** [comment]
@prnadago We are tracking this site issue holistically, so I'll close this issue.

**Comment by prnadago** [comment]
Oh yeah it's working now. Weird :/
