### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by lavahot** [MicrosoftDocs/visualstudio-docs#1427]
The two links in the notes box: Create a network installation of Visual Studio 2017 and Install certificates required for Visual Studio offline installation, both point to 404s. Please fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an Offline Installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by ghogen** [comment]
@lavahot  These were down today due to a site issue. They should be working again now.

**Comment by lavahot** [comment]
Yep! Thank you!
