### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by patrickjopia** [MicrosoftDocs/visualstudio-docs#1429]
I'm not sure if I missed anything on this example. 

Here's the error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'MobileApp1, Version=0.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'MobileApp1.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(DirectoryAssemblyResolver res, ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.&lt;ExecuteInstantiatedTask&gt;d__26.MoveNext()	MobileApp1.Android			
Error	CS0103	The name 'zipCodeEntry' does not exist in the current context	MobileApp1	C:\Users\Now Corporation\VSProjects\MobileApp2\MobileApp1\MobileApp1\MobileApp1\WeatherPage.xaml.cs	18	Active
Error	CS0103	The name 'zipCodeEntry' does not exist in the current context	MobileApp1	C:\Users\Now Corporation\VSProjects\MobileApp2\MobileApp1\MobileApp1\MobileApp1\WeatherPage.xaml.cs	20	Active
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	MobileApp1	C:\Users\Now Corporation\VSProjects\MobileApp2\MobileApp1\MobileApp1\MobileApp1\WeatherPage.xaml.cs	10	Active
Error	CS0103	The name 'getWeatherBtn' does not exist in the current context	MobileApp1	C:\Users\Now Corporation\VSProjects\MobileApp2\MobileApp1\MobileApp1\MobileApp1\WeatherPage.xaml.cs	22	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b25d4cd-0c3f-e9a6-6256-ea54d0972d4b
* Version Independent ID: babd49b7-8e18-13dc-99f2-6783495cb0dc
* Content: [Learn app-building basics with Xamarin.Forms in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio?view=vs-2017#set-up-your-solution)
* Content Source: [docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
There is a link to the completed sample at the end of the page - you can view/download it from [GitHub](https://github.com/xamarin/xamarin-forms-samples/tree/master/Weather).

**Comment by wandabwa2004** [comment]
Same error with this https://github.com/xamarin/xamarin-forms-samples/tree/master/Weather. Something missing?

**Comment by conceptdev** [comment]
I was just able to build this sample successfully. Can you provide more information on what platform you are using and what Android SDKs you have installed. We recommend Visual Studio 2019 and the SDK for Android API Level 27 (8.1, Oreo) which is what this sample is currently set to use. Also ensure that you have restored NuGet packages, so that Xamarin.Forms and the Android support library packages are correctly installed.

**Comment by conceptdev** [comment]
Our testing has shown the sample working, so I'm going to close this issue. If you still have a problem please create a new issue with additional feedback either on the doc or the sample repo on GitHub.
Thanks
