### ISSUE TITLE
small suggestion ... title

### ISSUE THREAD

**Issue by OzBob** [MicrosoftDocs/visualstudio-docs#1434]
on
https://manage.visualstudio.com/administrators?onbd_id=
The "Row actions grid-context-menu bowtie-ellipsis mouse over" dispalys a blank div with no description. The title attribute is blank.

May i suggest reuse the 'aria-label' value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec954beb-b170-4bf7-37e7-a7d7474c528b
* Version Independent ID: f9f87bac-6ec0-a386-403c-39469de44e2d
* Content: [Edit Subscriptions in the Administrator Portal](https://docs.microsoft.com/en-us/visualstudio/subscriptions/edit-license)
* Content Source: [subscriptions/edit-license.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/edit-license.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@OzBob Thanks for your feedback! @evanwindom, @prrana, @lankaim - FYI

**Comment by evanwindom** [comment]
@OzBob Thanks for your feedback!  I have passed your suggestion along to our engineering team for evaluation.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for forwarding the info. @OzBob Thanks again for your feedback. We'll close specific GitHub Issue now, as this forum is meant to track documentation issues rather that product issues, and the info has been forwarded to the product engineering team.
