### ISSUE TITLE
Ambiguity in a sentence.

### ISSUE THREAD

**Issue by fpl9000** [MicrosoftDocs/visualstudio-docs#1435]
This page says: "Beginning in 2015, VSIX packages signed using anything other than SHA256 encryption will be identified as having an invalid signature." Does the "2015" mean "Visual Studio 2015" or does it mean "the year 2015 in all versions of Visual Studio"? I think this is a valid issue, because you version your compilers with year numbers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf20479-c8a0-eb31-45f8-3599c759b4d6
* Version Independent ID: f9ca0232-6aa0-543b-2b37-6685e69cfdb9
* Content: [Signing VSIX Packages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/signing-vsix-packages?view=vs-2017)
* Content Source: [docs/extensibility/signing-vsix-packages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/signing-vsix-packages.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@gregvanl  or @madskristensen can you answer this?

**Comment by carlos-quintero** [comment]
It's "Beginning with Visual Studio 2015", since it's the product (and not the year) what forces to use SHA56 encryption. I have created the pull request https://github.com/MicrosoftDocs/visualstudio-docs/pull/1703

**Comment by madskristensen** [comment]
@carlos-quintero is right. Thanks for the PR!

**Comment by gewarren** [comment]
Verified the fix, so closing.

"Beginning with Visual Studio 2015, VSIX packages signed using anything other than SHA256 encryption will be identified as having an invalid signature."
