### ISSUE TITLE
Windows based docker image

### ISSUE THREAD

**Issue by Canutza** [MicrosoftDocs/visualstudio-docs#1439]
Is there a Windows based docker image?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b74c2c0-d611-1bc2-3d1d-f6c8484a565a
* Version Independent ID: 127e4784-1416-2a97-7ca1-0f183f312aef
* Content: [R and Docker containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/using-docker-containers-with-r?view=vs-2017)
* Content Source: [docs/rtvs/using-docker-containers-with-r.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/using-docker-containers-with-r.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@Canutza Not at this time, and I don't know of any plans at present to add one. The best thing to do is to use check if there are existing requests on https://visualstudio.uservoice.com/forums/121579-visual-studio and upvote them, or create the suggestion if necessary.
