### ISSUE TITLE
What does the second checkbox do?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1440]
There are a few other settings on this tab now that aren't described on the docs page that opens when clicking the ? button on this option page. 

![image](https://user-images.githubusercontent.com/15381181/44632835-d7a18f00-a94f-11e8-96be-4eed498641c8.png)

Specifically, what is  "device code flow"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f452163a-5b45-243c-9601-585359deec53
* Version Independent ID: 881229c0-dfb7-6e68-00ae-868abd0c6687
* Content: [Synchronize your settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/synchronized-settings-in-visual-studio?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Environment.RoamingSettings)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/ide/synchronized-settings-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/synchronized-settings-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to #1399.

**Comment by gewarren** [comment]
This reference article has been updated with the new options - https://docs.microsoft.com/en-us/visualstudio/ide/reference/accounts-environment-options-dialog-box?view=vs-2017.
