### ISSUE TITLE
Clicking the help button in Tools -> Options -> Windows Forms Designer

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1442]
Takes me to [this page](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/5aazxs78(v=vs.100)) where I get a pair of "alert/FYI/warning" (I dont know what else to call them, but at least they aren't yellow bar) messages.

![image](https://user-images.githubusercontent.com/15381181/44634007-5bb04280-a961-11e8-9e81-a9d6f84387f2.png)

I'm not sure what to make of this, as clicking "Recommended Version" takes me to a general VS docs page.  Is the link in VS need updating or is this the announcement of the EOL for windows forms?

**Comment by gewarren** [comment]
@StingyJack Thanks for letting us know. It is not EOL for Windows Forms, in face for .NET Core 3.0 Microsoft is releasing a "desktop pack" for Windows Forms. We do need to hook up the help keyword (VS.ToolsOptionsPages.WindowsFormsDesigner.General) for that Options page so it lands on a current topic (that we'll need to create), so thanks for alerting us.
