### ISSUE TITLE
So how does one make a webtest?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1443]
Trying to add a recording on WebTest1.webtest of opening a page, logging in, and clicking a menu item never adds anything to webtest1.webtest. 

I dont see a link here that explains what is supposed to happen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0780169-4b7b-97ce-5ccd-9f962472a2c8
* Version Independent ID: f0c68169-baeb-cba0-ccf0-a149fa96bb67
* Content: [Create a web performance and load test project in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2017)
* Content Source: [docs/test/quickstart-create-a-load-test-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/quickstart-create-a-load-test-project.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by SwayTex** [comment]
Hi. When you start recording does it open a web browser? And in it does it request to allow a extension?

**Comment by PBoraMSFT** [comment]
Webtest can be recorded or hand-coded by adding requests one by one. recording depends on a browser extension, that is installed automatically when you install Visual Studio with the web performance and load test component. 
Please ensure that the "webtest recorder" and "recorder helper" show as Enabled in IE. (IE Settings gear -> Internet Options -> Programs -> Manage add-ons)
![image](https://user-images.githubusercontent.com/23308203/51426985-d1ba8c00-1c17-11e9-8d76-fee9cd1a2ae9.png)

If that doesn't resolve the issue, please report a problem on developer community https://developercommunity.visualstudio.com/content/problem/post.html?space=8

**Comment by StingyJack** [comment]
@PBoraMSFT - thanks, but i was not having that problem.

**Comment by PBoraMSFT** [comment]
@StingyJack - so, is the issue resolved then? Should we go ahead and close it? 
If not, can you share more details of the problem so we can help?

**Comment by PBoraMSFT** [comment]
@gewarren - I have sent you a mail about a topic that can be added here about webtest recording and playback. Can you please take it forward and close this issue when you are done? 

@StingyJack - please note that web and load test functionality is deprecated in VS 2019. VS 2019 will be the last release. https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#test-tools

**Comment by StingyJack** [comment]
@PBoraMSFT - I'm not sure what difference reporting a feature's deprecation makes to the question asked. Also the article you linked talks about Coded UI and load testing deprecation. I think this was for the webtest recording that appeared to be non-functional when I tried to use it. Even if you consider WTR part of the other two, your customer base has a reasonable expectation that this module will be supported until ~2029 and not before then.

**Comment by StingyJack** [comment]
@PboraMSFT - the OP has the STR + A/E.

**Comment by StingyJack** [comment]
@PBoraMSFT - can you please answer or address the original posted question?

**Comment by StingyJack** [comment]
> For docs - I have already asked @gewarren to look into adding a topic.

@PBoraMSFT  - Is that a topic about what is supposed to happen after recording a simulated login or other sequence? 

> For the issue you are facing with recording being non-functional, 

@PBoraMSFT  - Is the description I gave in the original post a description of something that is non-functional?  I dont know. Which is why I asked.

> I have asked that you share details of the problem, without which we will not be able to make much progress in helping you.

@PBoraMSFT  - I already stated the problem.  You had the time to answer someone else's question on this thread but not the one that started the thread. And then instead of answering when prompted a second time, chose to attempt misdirection by bringing up feature deprecation (that wont come to pass for at least 5-10 years). 

It was a simple question - what is supposed to happen after recording steps?  Instead of just answering the question with " it should do X, but if its not, please log a feedback ticket. Thank you for helping to build a better Visual Studio", it really looks like you are trying to antagonize or give _me_ a hard time because _your_ program isnt working right.  

You still have the chance to answer the question now, even if its going to result in me opening dev community feedback ticket number 467. (That is a legitimate and real count of items I've posted. Its actually a dozen or so more than that but I cant get to those issues anymore)

**Comment by gewarren** [comment]
Setting priority at P2 for adding the new topic using this info as a basis: https://www.softwaretestingclass.com/how-to-create-web-performance-test-with-vsts/

**Comment by StingyJack** [comment]
@gewarren - you can close this if you want. PBora has made it clear that this is a dead and unsupported tech already, and no further questions will be answered about it. Its not worth spending time on something already slated for the dumpster. Thank you for trying, its appreciated.
