### ISSUE TITLE
browser mix options way out of date

### ISSUE THREAD

**Issue by donjenseth** [MicrosoftDocs/visualstudio-docs#1444]
Is there a way to update the browser options in the browser mix control to more current versions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d33f7e4-bfd4-77aa-2c23-17d46d277b56
* Version Independent ID: e636ebeb-13e4-40c6-1411-4a3ccbb0d28d
* Content: [Browser test mix for load testing in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/edit-the-test-mix-to-specify-which-web-browsers-types-in-a-load-test-scenario?view=vs-2017#add-new-browsers-to-a-scenario)
* Content Source: [docs/test/edit-the-test-mix-to-specify-which-web-browsers-types-in-a-load-test-scenario.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/edit-the-test-mix-to-specify-which-web-browsers-types-in-a-load-test-scenario.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
On looking more closely at this issue, it appears that you are requesting a product change and not a documentation change. If that is the case, the best place to make product feature suggestions or provide feedback is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Look for the "Suggest a Feature" button:

![image](https://user-images.githubusercontent.com/24882762/50102736-a7218180-01da-11e9-9aaf-ea3a99ccd030.png)

When you suggest a feature on Developer Community, you can engage directly with the engineering team as they consider the suggestion. It also provides a way for other customers to upvote your suggestion.

Given that load testing is deprecated, it's unlikely that the engineering team will act on this feedback, however.
