### ISSUE TITLE
Request for the VSSDK in the Build Tools Installer

### ISSUE THREAD

**Issue by awschristou** [MicrosoftDocs/visualstudio-docs#1447]
Hi, I'd like to know if it is possible/appropriate to add the `Microsoft.VisualStudio.Component.VSSDK` component into the build tools installer (possibly within `Visual Studio extension development` or somewhere similar)?

I'm trying to set up a docker image with the build tools, and use the image to compile code that references the Visual Studio SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e062363-94e9-f776-650f-a0723ab713a3
* Version Independent ID: 9181db12-cbdf-6f95-27f1-833930d6d323
* Content: [Visual Studio Build Tools 2017 workload and component IDs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2017#visual-studio-extension-development)
* Content Source: [docs/install/workload-component-id-vs-build-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-build-tools.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@awschristou Thanks for your input! @PhastPhood FYI

**Comment by jazzdelightsme** [comment]
I think `Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools` should add that (just tried it).

**Comment by awschristou** [comment]
@TerryGLee  @jazzdelightsme  Thank you - I haven't had a chance to try it out, but it looks like what I am after.

**Comment by TerryGLee** [comment]
@awschristou OK I'll close this issue then. Thanks for your response. :)
