### ISSUE TITLE
Image's text is incorrect

### ISSUE THREAD

**Issue by JohnCOsborne** [MicrosoftDocs/visualstudio-docs#1449]
In the section **Split a test method into two separate methods** the image's text "... where you want the new test method to being" is incorrect

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d5b6c05-b06e-2dc0-8461-f2d5580068ff
* Version Independent ID: 7ecc39c0-b8ed-8026-7575-3f16889bed0f
* Content: [Editing Coded UI Tests - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/editing-coded-ui-tests-using-the-coded-ui-test-editor?view=vs-2017#split-a-test-method-into-two-separate-methods)
* Content Source: [docs/test/editing-coded-ui-tests-using-the-coded-ui-test-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/editing-coded-ui-tests-using-the-coded-ui-test-editor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by sourabh1031** [comment]
I would like to work on this. I am a newbie to this project. can you please tell me the prerequisites to solve this

**Comment by gewarren** [comment]
@sourabh1031 Thanks for offering to help fix the image. Since the text is part of the image, it's not a straightforward fix as the image must either be "doctored" to change "being" to "begin", or a new image must be generated.
