### ISSUE TITLE
Extension Point link points to codeplex site

### ISSUE THREAD

**Issue by johnmcbride** [MicrosoftDocs/visualstudio-docs#1453]
The extension point link in the "See the Extension Point reference for a more in-depth explanation" points to an old codeplex site, should this be updated to point to a more updated reference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81fd881-9387-165a-846c-37025ccf433b
* Version Independent ID: a0bfdf42-fc87-0b73-8cdb-fb935434be70
* Content: [Extending Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac#feedback)
* Content Source: [mac/extending-visual-studio-mac.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/extending-visual-studio-mac.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @johnmcbride, _think_ the correct link will be https://github.com/mono/mono-addins, but I'm going to verify before I update the doc.

**Comment by conceptdev** [comment]
Updated the link to the actual Extension Points page: https://github.com/mono/mono-addins/wiki/Extension-Points
