### ISSUE TITLE
Normalize the line endings in the repo

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#1456]
Just moving over from #1437 from @ghogen's comment. I think this is part of your internal process since the the files are in the repo and the original https://github.com/MicrosoftDocs/feedback/issues/362

Here is the steps to fix the repo to match the settings currently in the config:
- git rm -rf --cached . removes all files from the git index, but leaves them on the disk
- git add . add back the files looking at the .gitattributes and .gitignore settings
- Commit the re-encoded files

Note: it seems like when there are encoding issues the bots can't parse the YAML frontmatter and notify authors on changes

**Comment by gewarren** [comment]
This was taken care of by #2116.

**Comment by nschonni** [comment]
Thanks, has #2198 also been done in the internal repo too?

**Comment by gewarren** [comment]
No, not yet.

**Comment by gewarren** [comment]
The scripting-docs folder has been normalized too now (in the private repo).
