### ISSUE TITLE
Debug tasks section lacks example for launching a remote debug session 

### ISSUE THREAD

**Issue by petrroll** [MicrosoftDocs/visualstudio-docs#1457]
I couldn't find any documentation on how to create a lunch task to start a process on remote server (Linux) & immediately attach a debugger. 

I can start a process on remote server using custom task and I can attach debugger to running process on such server using GUI but I'd like to see documentation on how to create a task / lunch task to do both of these things at once. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f6ef2c-e616-bf4c-6de4-1448814e4f73
* Version Independent ID: b223e86b-b0d8-3a78-3fe5-0938e6641042
* Content: [Customize build and debug tasks in Visual Studio using tasks.vs.json and launch.vs.json - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2017)
* Content Source: [docs/ide/customize-build-and-debug-tasks-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/customize-build-and-debug-tasks-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Mikejo5000** [comment]
I'll ask about this.

**Comment by gregg-miskelly** [comment]
@petrroll: 
What kind of debugger do you want to use? (ex: C/C++, node, etc)
To make sure I understand, you want to launch the process under a debugger and immediately start debugging the code, right?

Assuming I have that right - what you want to do is configure launch.vs.json to launch the process you want to debug under a debugger on the remote Linux box. But the exact details of how that works will depend on what kind of code you want to debug.

**Comment by petrroll** [comment]
Ok, my use-case is following. I have a local Windows box with Visual Studio 2017, a remote Linux VM, and a Linux C app (compiled with GCC) with source code both on my local Windows box & the Linux VM (I keep the sources synchronized, but that's not relevant).

I want to be able to launch and debug (not necessarily copy sources & build) my app on the Linux VM using Visual Studio debugger from within the Windows box.

Visual Studio supports attaching debugger (some gdb adapter) to a remote (native) process via ssh. I know how to do that but for it to work I need to SSH to the Linux VM first, start the process, and then through VS GUI attach its debugger to the process (VS is then able to download all required header files, … and it works flawlessly). I'd link documentation for this feature but TBH I can't find it anywhere (1).

Visual Studio (for projects opened as folder) also supports creating custom tasks for projects opened as folders via `launch.vs.json` and `tasks.vs.json`. Both of these also support remote tasks. I know how to copy my source files from my local Windows machine to the remote one, I also know how to run arbitrary shell command on the remote machine. I know how to theoretically start the process on the remote machine through custom `task`. The issue is twofold.

First, creating a task that starts the process works but since the task only redirects output but doesn't give me full terminal I have no easy way to kill the process. 

Second, which is way more important, I can't attach the Visual studio debugger using a (shell or otherwise) command on the remote machine. And I don't know how to create a task that would instruct Visual studio to do the attach to remote process it just started on the remote machine. 

I know it's a bit longer but I wanted to be clear. If something isn't clear yet feel free to ping me at t-pehous or we can grab a lunch sometime (I'm at Redmond campus ATM).

(1) On that note, when my team investigated debugging Linux apps from Windows we actually almost went for the VisualGDB extension. I stumbled on the fact that VS can do that natively only by accident and even though it might be documented somewhere it's definitely not advertised.

**Comment by petrroll** [comment]
Finishing my internship this week so ping me here instead of my alias in case of any questions.

**Comment by Mikejo5000** [comment]
@petroll BTW, since you mentioned you couldn't find any docs on Linux debugging from VS, there's an article on remote debugging C++ on Linux here:
https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=vs-2017
That doesn't help with creating a custom launch task, though.

**Comment by petrroll** [comment]
I've seen this article but it's about debugging a _project based solution_ not a _folder based_ solution. Generally it seems to me that there's a bit of confusion in regards what's possible on what types of "solutions" (project based, folder based, Linux, windows, …). Fortunately it seems that more than documented is usually possible.

**Comment by gewarren** [comment]
@Mikejo5000 I'm reassigning this to you since you've been more involved in this one.

**Comment by petrroll** [comment]
I'm coming back to MS as intern in three weeks, so I'm happy to chat about it again. That said, I think most of aforementioned issues could be "solved" (or rather avoided) with the new VSCode remote stuff.

**Comment by range4life** [comment]
VSCode remote is great and definitely cleaner (it is what I do on my workstation for debugging) But it shouldn't be the case that we have to use it simply because the documentation for features that the VS developers spent time on is insufficient.

I've linked to this issue from another related issue on which I've given an example of what I feel is missing from the docs for remote debug using open folder instead of CMake, which seems to be the issue described here.

**Comment by petrroll** [comment]
My original request would've been 98 % solved by VSCode's remote capabilities (or its equivalent for VS if/when it comes).

**Comment by Mikejo5000** [comment]
This topic has been updated for launch configurations for open folder:
https://docs.microsoft.com/en-us/cpp/build/open-folder-projects-cpp?view=vs-2017
Per MicrosoftDocs/cpp-docs#836, is that enough info to configure for the remote scenario?

**Comment by petrroll** [comment]
Seems ok, thanks!

**Comment by Mikejo5000** [comment]
OK, thanks. I'm adding a link to the C++ topic from this open folder topic in VS.
