### ISSUE TITLE
TFS 2018 - Containerized agents having build issues

### ISSUE THREAD

**Issue by nishantyedla** [MicrosoftDocs/visualstudio-docs#1458]
Environment
TFS 2018
Agent.OSVersion - 10.0.14393
Agent.Version - 2.117.2

##Agent - Hosted or Private:
Containerized agents followed the VS build Tools steps by Microsoft to setup the base image and installed Build agents on top of it:
https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017

Issue Description
Running a dotnet regression test and facing trouble building that. Complains about not able to import powershell modules and missing dlls

![image](https://user-images.githubusercontent.com/42752634/44790657-73581880-ab65-11e8-9ff9-cca1a2bf486d.png)

![image](https://user-images.githubusercontent.com/42752634/44790672-7bb05380-ab65-11e8-8ab9-8513473e2ed5.png)

**Comment by nishantyedla** [comment]
Looks like there is an issue with microsoft/dotnet-framework:4.7.1 image which is used for setting up the build tools.
I used the latest framework image 4.7.2 and I don't see this error anymore. Thanks!

**Comment by TerryGLee** [comment]
@nishantyedla We appreciate you following up with us; we'll go ahead and close this issue.

Cheers,
~ Terry
