### ISSUE TITLE
Can't locate previously created workspace.

### ISSUE THREAD

**Issue by waqas-zia-confiz** [MicrosoftDocs/visualstudio-docs#1460]
I am just trying to use TFVS on MAC with the provided extension. I was able to setup everything and pulled the code from the server. A few days later I was disconnected and wanted to reconnect and now I can't see the previously created workspace. When I try to create new workspace with same name it says the workspace already exists but shows no workspaces otherwise.

**Comment by gewarren** [comment]
@conceptdev Can you take a look at this question?

**Comment by conceptdev** [comment]
The extension is still in preview, and we appreciate you trying it out. Please follow the guidelines on the [docs](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control) and let us know about any issues on [Developer Community](https://developercommunity.visualstudio.com/spaces/41/index.html). Thanks!
