### ISSUE TITLE
csharp_space_between_parentheses = false doesn't seem to work

### ISSUE THREAD

**Issue by DerekSMorin** [MicrosoftDocs/visualstudio-docs#1461]
csharp_space_between_parentheses = false

A colleague found a post that made him come up with this:
csharp_space_between_parentheses = expressions,control_flow_statements

https://kent-boogaart.com/blog/editorconfig-reference-for-c-developers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#example-editorconfig-file)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **kaseyu**

**Comment by gewarren** [comment]
@DerekSMorin Thank you for reporting this. Our article does seem to contradict itself for this convention. It sounds like the allowable values are:

none
type_casts
control_flow_statements
expressions

**Comment by cremor** [comment]
@gewarren Are you sure? This was already discussed in #513 and back then it was determined that `false` is correct.

**Comment by cremor** [comment]
> it seems that 'false' is an acceptable value, only in that it isn't one of the documented values. And 'none' would have the same effect as 'false'.

Yes, that's definitely still true. See [code for VS 2017 15.9](https://github.com/dotnet/roslyn/blob/dev15.9.x/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.Parsers.cs#L9-L25) and [code that might be in VS 2019](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.Parsers.cs#L13-L23) ([refrenced dictionary](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs#L27-L33)).
 
> I'm just wondering whether the **default value = false** statement in [this table](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#spacing) of the article is correct. I think it might just be saying that by default, no spaces are added between parentheses?

Yes, I assume that's what it should mean currently.
But it got clearer with dotnet/roslyn#30043 which will be in VS 2019. `false` is there exported to the generated .editorconfig if none of the other options are set in the settings GUI (see [code](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.Parsers.cs#L25-L47)).
Therefore I think the current documentation is fine.

**Comment by gewarren** [comment]
@cremor Thanks for your input. Closing the issue now.
