### ISSUE TITLE
I can't see the Extension in my Gallery

### ISSUE THREAD

**Issue by AnsonWooBizCloud** [MicrosoftDocs/visualstudio-docs#1462]
I have tried to refresh and restart my VS for Mac but I can't see any available Official Extension, is my VS for Mac's extension manager corrupted? I can only see Prism Template Pack, thanks

I am using 7.6.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [TF Version Control - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
I also see this issue. It has been reported on [developer community](https://developercommunity.visualstudio.com/content/problem/320614/tfs-extension-does-not-show-up-in-gallery.html) - product issues are raised and tracked there.
