### ISSUE TITLE
Cannot map to local workspace

### ISSUE THREAD

**Issue by thetypebeast** [MicrosoftDocs/visualstudio-docs#1463]
Using Visual Studio for Mac Community, v7.6.1 (build 9)

I am able to connect to team foundation server, but it states there are 0 projects, when I know for a fact there are 3. Below the list, the workspace dropdown is disabled with the text "There is no local Workspace". Where are my projects, and how am I supposed to create a workspace when the dropdown won't allow me to select anything at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [TF Version Control - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
The extension is still in preview, so there might still be issues.

Please follow the instructions at the top of the page, and report the issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/41/index.html) so it can be addressed by our engineers.

Thanks.

**Comment by MinkyuH** [comment]
Hi any updates on this? I'm experiencing same issue as well thanks :)

**Comment by conceptdev** [comment]
Please report any problems at [DeveloperCommunity](https://developercommunity.visualstudio.com/spaces/41/index.html). We need feedback to identify and fix these issues.

**Comment by cnzhnet** [comment]
服务器无法处理请求。 ---> TF400367: 该请求无法执行，因为主机类型不匹配。请检查所有连接信息并验证信息是否正确。该请求是针对 Deployment, Application 执行的。

The server was unable to process the request. ---> TF400367: The request cannot be performed because the host type does not match. Please check all connection information and verify that the information is correct. The request was executed against Deployment, application.

**Comment by conceptdev** [comment]
@cnzhnet https://developercommunity.visualstudio.com/
