### ISSUE TITLE
Missing info (where is target framework value stored)

### ISSUE THREAD

**Issue by MiroslavMikus** [MicrosoftDocs/visualstudio-docs#1465]
Could you please extend this docu with information where exactly is the target framework value stored? All I can find in the csproj file is the 'TargetFrameworkVersion' value. I would like to know if my project is targeting regular/core/standard framework. Some more info: I'm creating something like an inventory scan for all my solutions. And I would like to create an nuget package dependency map. The problem is that Nuget packages can target multiple frameworks and I need a way how to get the target framework from the solution or project file. 

Thank you in advice
Miro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57adfe0d-2b80-3afc-91c9-bd2a05696556
* Version Independent ID: f332c66b-81a5-e054-3c5f-db82609cbb76
* Content: [Target a .NET Framework version in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-target-a-version-of-the-dotnet-framework?view=vs-2017)
* Content Source: [docs/ide/how-to-target-a-version-of-the-dotnet-framework.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-target-a-version-of-the-dotnet-framework.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by chadwixk** [comment]
It's stored in the web.config file:
<system.web>
    <compilation debug="true" targetFramework="4.6.1"/>

**Comment by MiroslavMikus** [comment]
There are many C# project templates without web.config. If I create a new .Net/Standard/Core/UWP project there is no *.config file by default.

**Comment by gewarren** [comment]
@MiroslavMikus Is this the kind of info you'd like to see added to the topic?

For a .NET Core console app: `<TargetFramework>netcoreapp2.1</TargetFramework>`
For .NET Standard: `<TargetFramework>netstandard2.0</TargetFramework>`
For .NET Framework: `<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>` (as you noted)
