### ISSUE TITLE
NET 4.x Sample Unity Project

### ISSUE THREAD

**Issue by bdominguez** [MicrosoftDocs/visualstudio-docs#1466]
It doesn't exist. The link is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f103240-7b3b-4732-12a9-39fdef044a08
* Version Independent ID: 0c9fb9a9-f254-fa5c-a334-3fff7dfccb92
* Content: [Using .NET 4.x in Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/unity-scripting-upgrade?view=vs-2017)
* Content Source: [docs/cross-platform/unity-scripting-upgrade.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/unity-scripting-upgrade.md)
* Product: **visual-studio-dev15**
* GitHub Login: @dantogno
* Microsoft Alias: **v-davian**

**Comment by BrianPeek** [comment]
My bad! I neglected to press the "Make public" button on the repo.  It is visible now.  Thanks for filing the issue!
