### ISSUE TITLE
Need topic for CA2008 - Do not create tasks without passing a TaskScheduler

### ISSUE THREAD

**Issue by anorborg** [MicrosoftDocs/visualstudio-docs#1467]
I get this when running Microsoft.CodeAnalysis.FxCopAnalyzers - 2.6.1, but no references in Microsoft documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f935929-e6b1-d110-4d2f-8a4150a27755
* Version Independent ID: d4c2d5fd-b9e3-85fd-7d21-22cdb8c06f9d
* Content: [Visual Studio Code Analysis Warnings for Managed Code by CheckId - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-warnings-for-managed-code-by-checkid?view=vs-2017)
* Content Source: [docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@anorborg Thanks for reporting this (and sorry we're only responding now). We'll add this new rule to the backlog for the documentation.

**Comment by sshukurov** [comment]
Missing topic for CA2007 DoNotDirectlyAwaitATaskAnalyzer as well.

**Comment by JuanMejiaVelez** [comment]
Any update on this? I just added a comment to https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-warnings?view=vs-2019#feedback before finding this, and seems to be still in the backlog for a year now.

**Comment by Mikejo5000** [comment]
Looks like this is one of the .NET 5 analyzer rules. Issue is being tracked here instead.
https://github.com/dotnet/roslyn-analyzers/issues/3549
