### ISSUE TITLE
Offline reporting?

### ISSUE THREAD

**Issue by zandr14** [MicrosoftDocs/visualstudio-docs#1468]
What if I'm working with VS offline?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* Content: [How to report a problem with Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio-2017.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@zandr14 Thanks for your inquiry; I or one of my colleagues will respond with more details, soon.
