### ISSUE TITLE
Vue-cli version 3

### ISSUE THREAD

**Issue by bourpie** [MicrosoftDocs/visualstudio-docs#1475]
Please update the documentation to include vue-cli version 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a644716-10c3-cc90-eeab-495c265e5728
* Version Independent ID: c356a0d8-1d24-2ab7-18de-b9b3088fd4d9
* Content: [Create a Vue.js app using Node.js Tools for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/create-application-with-vuejs?view=vs-2017#create-a-vuejs-project-with-aspnet-core-and-the-vue-cli)
* Content Source: [docs/javascript/create-application-with-vuejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/create-application-with-vuejs.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@bourpie Closing this as the Vue.js template and the ASP.NET + Vue.js instructions in this doc already reference vue-cli version 3. If there is some specific content that needs to be corrected, please let me know and re-open. Thanks!
