### ISSUE TITLE
Missing information about URL configure to lauch a web load test

### ISSUE THREAD

**Issue by cloudmelon** [MicrosoftDocs/visualstudio-docs#1476]
The doc ( Url : https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2017 ) _explains how to create a web test project and how to launch a test and show test results ( screenshot with 0 requests, response time), but it is not enough clear,  please mention how to 'add request'  which is strongly recommended and this represents the URL of web page to launch a real web test and what it exactly happens. So it is not enough to help readers especially those starting with Azure understand how to get started it. I add request by clicking right ( add request and then fill my website URL ). 

Ref without adding web request will display as the following :
![image](https://user-images.githubusercontent.com/4621560/44993723-d4378480-af9b-11e8-8ec9-737ef147ca6c.png)

**Comment by gewarren** [comment]
Prioritizing as P2 due to deprecation of load and web perf testing.

**Comment by gewarren** [comment]
@cloudmelon Unfortunately we don't currently have the resources to address this issue, based on its priority. Feel free to submit a doc edit yourself if you wish (the Edit button is in the upper right-hand corner of each docs page).
