### ISSUE TITLE
Azure Function Project Function File Listed Multiple Time

### ISSUE THREAD

**Issue by EdwardRushDeveloper** [MicrosoftDocs/visualstudio-docs#1477]
I have a MacBook Pro. I use Parallels to run Windows 10 and Visual Studio 2017. I also run Visual Studio for Mac. When creating an Azure Function Project and working with it in Visual Studio for Mac my Function class files progressively get listed multiple times. For example:
Solution -
   Project - 
         MyFunctionClass.cs  
         MyFunctionClass.cs
         MyFunctionClass.cs
         MyFunctionClass.cs
         MyFunctionClass.cs
         MyFunctionClass.cs

However, when checking the project into VSTS(Git), deploying to Azure and then also Checking out with Visual Studio on Windows 10, I don't see the behavior in Windows and I don't see the files listed in VSTS multiple times.  I have checked the project file, and the solution file to see if the files got multiple entries with in the raw file, but they are not. 

I do not have this problem with .NET Standard Libraries that my project is referencing, so it leads me to believe that this is an Azure Function Project issue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4caaf0cc-3cea-375a-1160-6540db5557f1
* Version Independent ID: cfd2fe36-1325-9ff0-bc18-af563bb920e4
* Content: [Introduction to Azure Functions - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions)
* Content Source: [mac/azure-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/azure-functions.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for the feedback @EdwardRushDeveloper. From your description it does sound like an issue with the IDE's behavior.

To raise an issue for the engineering team to address, you can press the **Product Feedback** button [at the bottom](https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions#feedback) of the docs page, or via the **Report a problem** feature in Visual Studio on [Windows](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) or [Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem).
