### ISSUE TITLE
Inconsistent representation of keys on the keyboard

### ISSUE THREAD

**Issue by DavidApps2** [MicrosoftDocs/visualstudio-docs#1479]
Your content uses inconsistent ways to represent keys on the keyboard. For example:
https://docs.microsoft.com/en-gb/visualstudio/ide/reference/how-to-use-the-keyboard-exclusively?view=vs-2017
This topic uses both "Up Arrow" and "UPARROW". "UPARROW" is unsuitable because many pieces of screen reader software badly mispronounce it.
Please improve the consistency and accessibility of your content.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6452222-881f-0b4e-447f-7ad35230ab31
* Version Independent ID: 2037a1d4-a9e0-e569-c73f-200df1278ee0
* Content: [How to: Use the keyboard exclusively - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/reference/how-to-use-the-keyboard-exclusively?view=vs-2017)
* Content Source: [docs/ide/reference/how-to-use-the-keyboard-exclusively.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/how-to-use-the-keyboard-exclusively.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@DavidApps2 Thanks for your feedback; this is in our backlog to fix.

**Comment by TerryGLee** [comment]
@DavidApps2 Thanks again for letting us know about how screen reader software interacts with our content when it includes inconsistent keyboard references. We've updated this page to address the issue, and we're also taking a look at all our accessibility-related content to improve it, too.
