### ISSUE TITLE
Unable to specify ApplicationRevision from commandline

### ISSUE THREAD

**Issue by henrikib** [MicrosoftDocs/visualstudio-docs#1483]
You state that it is possible to specify:
&lt;ApplicationVersion&gt;1.0.0.*&lt;/ApplicationVersion&gt;  
&lt;ApplicationRevision&gt;1&lt;/ApplicationRevision&gt;  
But this is not possible from UI. If I edit the csproj file in notepad, I will get error: "Invalid value for 'AssemblyVersion'", when I reload project. 
I would like to specify ApplicationRevision from Commandline. Will You specify how?
I work on latest VS2017 (15.8.2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1672c325-b08a-dbc0-0e3e-31c832753613
* Version Independent ID: c479d585-37bb-795d-1e1c-4833c2262db6
* Content: [Building ClickOnce Applications from the Command Line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2017)
* Content Source: [docs/deployment/building-clickonce-applications-from-the-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/building-clickonce-applications-from-the-command-line.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by NikolaMilosavljevic** [comment]
These steps worked fine for me:
1) Created a new project, with new solution, and closed the solution
2) Modified .csproj file to add the two lines, you shared, to the first PropertyGroup section.
3) Reopened the project in Visual Studio - no issues
4) Published ClickOnce application - no issues

Can you try the same steps, and share your steps?

**Comment by Mikejo5000** [comment]
@henrikib  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
