### ISSUE TITLE
Typo in Step 3

### ISSUE THREAD

**Issue by pondybala** [MicrosoftDocs/visualstudio-docs#1484]
I could not find the Export Template under project menu. Step 3 should read: On the File menu, choose Export Template.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e16e6e-e5d1-964b-f220-cbb2c7e4b5e2
* Version Independent ID: 94f82ff9-c61f-31d1-df37-f5e4320daf1c
* Content: [Create project templates for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates?view=vs-2017)
* Content Source: [docs/ide/how-to-create-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-project-templates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@pondybala That's interesting. Which version of Visual Studio are you using?
