### ISSUE TITLE
Update content to reflect ports used for Service Fabric cluster, for debugging and ETW traceing

### ISSUE THREAD

**Issue by pisees** [MicrosoftDocs/visualstudio-docs#1486]
I can see in the load balancer that a port range is used to create for example the following entries for a 5 node cluster. So additional ports beyond what is outlined in this document would be needed. 

Debugger
31413 - 31417
30398 - 30402
31398 - 31402
32398 - 32402

Etw streaming
810 - 814

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use Visual Studio and Azure Services behind a firewall or proxy server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2017)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@pisees Thanks for your feedback; we'll investigate this and update the page as necessary.

**Comment by TerryGLee** [comment]
@tydunkel FYI

**Comment by ornellaalt** [comment]
Hi @pisees, we've updated this page on 1/31/2020 with a more robust explanation for Service Fabric remote debugging and ETW traces that includes the additional ports necessary. Please check it out and feel free to provide further feedback if there is still insufficient information.
