### ISSUE TITLE
Creating a Database in VS 2017 

### ISSUE THREAD

**Issue by stevehtml** [MicrosoftDocs/visualstudio-docs#1489]
NO ISSUE , JUST THANKS .... wanted to learn to use a DB in small personal projects , Got It !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d19e1d-1448-e5b3-6580-9b11042e03ab
* Version Independent ID: 549472fa-f3be-53bc-cf9f-170c1183c834
* Content: [Create a database file and use table designer in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2017)
* Content Source: [docs/data-tools/create-a-sql-database-by-using-a-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-sql-database-by-using-a-designer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@stevehtml That's great to hear; thanks for the feedback!
