### ISSUE TITLE
Hardware acceleration

### ISSUE THREAD

**Issue by r3m0t** [MicrosoftDocs/visualstudio-docs#1491]
What's the value for disabling hardware graphics acceleration under General?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6159d774-f257-769d-27ca-cc7b7bdae54a
* Version Independent ID: c88c5ada-49c7-7333-cd36-234ddb2a9cb0
* Content: [Options Page, Environment Node Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-page-environment-node-properties?view=vs-2017)
* Content Source: [docs/ide/reference/options-page-environment-node-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-page-environment-node-properties.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by rub8n** [comment]
Hi @r3m0t! Can you clarify what you mean?
