### ISSUE TITLE
The format for Option Admin:Security is not properly provided on this page

### ISSUE THREAD

**Issue by bogdan-mabo** [MicrosoftDocs/visualstudio-docs#1494]
It should be Admin:Security,&lt;ALLOW|DENY&gt;,Right[Right],&lt;User|Group&gt;
Please notice the commas between switches.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8b802ed-2874-0a02-2245-e7cea64ee3ee
* Version Independent ID: 9c8f278d-f293-df95-1314-ad2ea7ea1172
* Content: [VSPerfCmd - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/vsperfcmd?view=vs-2017)
* Content Source: [docs/profiling/vsperfcmd.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/vsperfcmd.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@bogdan-mabo Thanks! Updating doc.
