### ISSUE TITLE
More info needed for code snippets

### ISSUE THREAD

**Issue by jraldrin** [MicrosoftDocs/visualstudio-docs#1497]
Looks like there are some snippet keywords. Please add link to more info on snippet keywords.  
Note, I heard a Xamarin/MSoft employee, on a podcast, recommend buying MRefacor because Snippets were so hard to write. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c165c6c-3afb-ec14-fc40-13c504aa2492
* Version Independent ID: eb03852b-8ccf-a6f7-b62d-a6912a97430d
* Content: [Code Snippets - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/snippets)
* Content Source: [mac/snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/snippets.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by jraldrin** [comment]
Title should be "More info needed for code snippets"

**Comment by conceptdev** [comment]
Thanks for your feedback @jraldrin. By keywords do you mean placeholders in the snippet?

**Comment by conceptdev** [comment]
Added more detail about snippet keywords to the end of the page. New content will be published soon.
#please-close
