### ISSUE TITLE
Step 3 is confusing 

### ISSUE THREAD

**Issue by drowhunter** [MicrosoftDocs/visualstudio-docs#1498]
my app-bundle.js file is way longer that that and there is no code anywhere in that file with that code in it.

also when I change the app.tsx Hello component by adding more html to it.
Rebuilding doesn't update the dist folder.

You should add more to this tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2017)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@drowhunter For step 3 (step 3 in Transpile the JSX section, I think you mean? or do you mean a different section?), did you choose Add > Existing File or Add > Existing Folder? I see the Select Folder option when I choose Add > Existing Folder.

For app-bundle.js, yes, it is a long file. I find this equivalent code in this file:
    Hello.prototype.render = function () {
        return (React.createElement("h1", null, "Welcome to React!!"));
    };

**Comment by magnuskarlssonhm** [comment]
@Mikejo5000 @drowhunter I find step 3 in "Set and hit a breakpoint in the client-side React code" confusing as well. The image clearly shows the code "class Hello extends React" which is not what it looks like after compilation. It looks like @Mikejo5000 describes in the comment above this, not like in the picture in the docs. However, when running the debugger correctly attached to the process it will jump to the code in this picture.

**Comment by Mikejo5000** [comment]
@magnuskarlssonhm Thanks for the clarification! I'm updating the doc.

**Comment by Mikejo5000** [comment]
@gewarren Maybe we should have "Area - nodejs" added?
