### ISSUE TITLE
InstallCleanup.exe path is misleading

### ISSUE THREAD

**Issue by kg** [MicrosoftDocs/visualstudio-docs#1500]
EDIT: Okay, I was just confused by the two paths in the docs. I was reading the part that said 'always located at %ProgramFiles(x86)%\Microsoft Visual Studio' so I looked there for InstallCleanup.exe. I see that there is another path provided in the docs page and I found it there after a reinstall. :/

So I think this docs page just needs to be updated so it clearly states the correct dir in both places. Naturally I only found this after 30 minutes of digging around and then filing the bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2017)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
Could you clarify what appears to be incorrect or confusing? I don't understand what problem you're reporting.

**Comment by kg** [comment]
'always located at %ProgramFiles(x86)%\Microsoft Visual Studio' suggests to me that it's in that folder, when it's in a nested subfolder. (I did a search with windows search and it didn't show up, which is probably an indexing service problem?) ultimately it is a failure by me to read the docs carefully, but it would be sufficient to just update it so both paths in the page match.
