### ISSUE TITLE
How to write lines with Metadata?

### ISSUE THREAD

**Issue by lindexi** [MicrosoftDocs/visualstudio-docs#1501]
How to write lines by WriteLinesToFile and the lines with Metadata?

I use https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-batching?view=vs-2017 but it can run in Message but can not run in WriteLinesToFile.

```
 &lt;ItemGroup&gt;  
        &lt;MyTextFile Include="Items.txt" Foo="foo"/&gt;  
    &lt;/ItemGroup&gt; 

&lt;Target Name="WriteLaunchers" AfterTargets="CopyFilesToOutputDirectory"&gt;
    &lt;WriteLinesToFile File="foo.md" Lines="@(MyTextFile)  foo = %(MyTextFile.Foo)"/&gt;
&lt;/Target&gt;
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee06fdb3-143d-fa36-54ee-5f9af813615e
* Version Independent ID: 5739dfe6-6a88-1487-4f29-1b91502ec7ad
* Content: [WriteLinesToFile Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/writelinestofile-task?view=vs-2017)
* Content Source: [docs/msbuild/writelinestofile-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/writelinestofile-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@lindexi Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
