### ISSUE TITLE
Add a new Language Highlighting Syntax on VSCode

### ISSUE THREAD

**Issue by MelvinG24** [MicrosoftDocs/visualstudio-docs#1502]
I have create my own language highlighting syntax for VSCode with it syntax and snippets folders; However, I do not know how make it work on the software. I already place the language folder on the extension folder on my mac, but my new highlighting syntax still not showing up on the list of programming languages.
Any subjection?

**Comment by gewarren** [comment]
@MelvinG24 This issues page is for Visual Studio documentation, not the Visual Studio Code product. Can you log your issue at https://github.com/Microsoft/vscode/issues instead?

**Comment by gregvanl** [comment]
@MelvinG24 Have a look at the VS Code extension authors documentation https://vscode-docs-master.azurewebsites.net/docs/extensions/overview and specifically https://vscode-docs-master.azurewebsites.net/docs/extensions/themes-snippets-colorizers
