### ISSUE TITLE
identifier

### ISSUE THREAD

**Issue by Kanokwaree** [MicrosoftDocs/visualstudio-docs#1505]
goods

---
#### รายละเอียดเอกสาร

⚠ *อย่าแก้ไขส่วนนี้ กำหนดให้ต้องจัดทำ docs.microsoft.com ➟ การเชื่อมโยงปัญหา GitHub*

* ID: 6ed17d69-010e-49c1-a227-a8a509713809
* Version Independent ID: e351a41c-c220-9173-db68-258c53dc84d9
* Content: [Expected identifier, string or number](https://docs.microsoft.com/th-th/scripting/javascript/misc/expected-identifier-string-or-number)
* Content Source: [scripting-docs/javascript/misc/expected-identifier-string-or-number.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/scripting-docs/javascript/misc/expected-identifier-string-or-number.md)
* Product: **windows-client-threshold**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Kanokwaree Sounds like you are happy with the content here?
