### ISSUE TITLE
'TestContext' does not contain a definition for 'DataRow' 

### ISSUE THREAD

**Issue by reuss** [MicrosoftDocs/visualstudio-docs#1506]
I have UWP project. Using VS Community 2017 I added a unit test to my solution (Add project-&gt; Windows Universal -&gt; Unit Test App (Windows Universal)),
I added reference to my project, 
I added .csv file with test data, 
I added DataSource Attribute
But still I can't use TestContext.DataRow:
  Error CS1061 'TestContext' does not contain a definition for 'DataRow' and no accessible extension method 
  'DataRow' accepting a first argument of type 'TestContext' could be found (are you missing a using 
  directive or an assembly reference?)
Do I miss something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1351cc8-f703-27a2-32c7-904256cb9e82
* Version Independent ID: 7a6912ef-da8d-6690-6da9-cc741fd5acde
* Content: [How To: Create a Data-Driven Unit Test in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2017)
* Content Source: [docs/test/how-to-create-a-data-driven-unit-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-create-a-data-driven-unit-test.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@reuss Sorry for the delay in responding. Did you resolve your issue? I'm wondering if adding a using directive for 'Microsoft.VisualStudio.TestTools.UnitTesting' would solve the problem?

**Comment by JimInWA** [comment]
I am running into the same issue, using .NET Core 2.x and the latest MSTestAdapter.

The issue has been reported by someone else here - https://github.com/Microsoft/testfx/issues/233

There is an RFC in the testfx-docs GitHub Repo but I can't find any corresponding code in the testfx repo for it - https://github.com/Microsoft/testfx-docs/blob/master/RFCs/006-DynamicData-Attribute.md

**Comment by pgoldman5699** [comment]
@gewarren @reuss @JimInWA @TerryGLee 

To resolve 'DataRow' I had to add a reference to System.Data. This was in Visual Studio 2017. If it's ok with everyone, I'm going to go ahead and create a new PR and fix this.

**Comment by gewarren** [comment]
As @JimInWA pointed out, there's not currently support for `DataSourceAttribute` in .NET Core and therefore in UWP projects too (they use .NET Core). We'll add a note to this article.

**Comment by shilpamalhotra-git** [comment]
Is there any update on this? How are we usually doing Data Driven testing in .net core with MsTest
