### ISSUE TITLE
When using Visual Studio to collect a dump file from another crashing visual studio instance...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1507]
... where exactly should the 

&gt; Choose Debug, then Save Dump As, then Debug. In the Save Dump As dialog box,

... be invoked from? Its not in the Debug menu or File menu. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb93b89e-4490-e703-94f3-324b9f7254ff
* Version Independent ID: 49c0d3a0-a0e5-5b16-eada-5d6aa5285ad9
* Content: [Use Dump Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2017)
* Content Source: [docs/debugger/using-dump-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-dump-files.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by StingyJack** [comment]
I dont. =<  

Instance on the left is being debugged by the one on the right. That's VS 15.8.3 on both counts.

![image](https://user-images.githubusercontent.com/15381181/45332228-6a8c1d00-b53d-11e8-8cee-16e2b09cec00.png)

**Comment by Mikejo5000** [comment]
Would you use the Send Feedback > Report a Problem link in VS to report this issue? It seems like that ought to work.

**Comment by StingyJack** [comment]
Sure thing. Figured I would check here to see if I was following the correct steps first.
