### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by smarts** [MicrosoftDocs/visualstudio-docs#1508]
The documentation is confusing because the **Syntax** section shows that the project file - and presumably the path, solution file, etc. if you are not specifying a project file directly - should come last, ***after*** all of the options. However, all examples that I could find on the page (including the two **Example** sections at the bottom of the page) show the project file (or equivalent argument) appearing ***before*** all options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, should project file come before the switches in the syntax section?

**Comment by rainersigwald** [comment]
The command line parser handles either case just fine--there's no order component, only the structure of the arguments themselves (no leading `/` means "this is the project").

I don't know what that means for the docs. It is a bit unusual for command-line programs which usually do have that order dependence.

**Comment by Mikejo5000** [comment]
@smarts @rainersigwald Seems OK to leave as-is, but if one of you think otherwise, please re-open and let me know. Thanks!
