### ISSUE TITLE
'ManageTaskPaneRibbon' is not a member of 'ThisRibbonCollection'

### ISSUE THREAD

**Issue by christianovitch** [MicrosoftDocs/visualstudio-docs#1509]
I'm trying to learn from this example, but am having a problem with the "Globals.Ribbons(inspector).ManageTaskPaneRibbon.ToggleButton1.Checked = taskPane.Visible" statement.  It generates the following error:

BC30456	'ManageTaskPaneRibbon' is not a member of 'ThisRibbonCollection'.

This is in Visual Studio 2017 and using Outlook 2010.  Any help would be much appreciated.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0d46e89-4015-af21-4e5d-77cb0acc9c7e
* Version Independent ID: ebdb0d6a-ce37-d0bb-bd10-b1f5ba061784
* Content: [Walkthrough: Display custom task panes with email messages in Outlook - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-displaying-custom-task-panes-with-e-mail-messages-in-outlook?view=vs-2017)
* Content Source: [docs/vsto/walkthrough-displaying-custom-task-panes-with-e-mail-messages-in-outlook.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-displaying-custom-task-panes-with-e-mail-messages-in-outlook.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@christianovitch Thanks for your feedback. We are aware that the documentation is outdated; it's in our backlog queue to be updated. However, for immediate assistance, please consider using the [StackOverflow](https://stackoverflow.com/search?q=outlook+visual+studio) site (and note that the link I've included goes directly to a collection of questions and answers that are tagged with "Outlook" and "VSTO").

**Comment by John-Hart** [comment]
I believe the document is correct.  I expect what happened was the name of the ManageTaskPaneRibbon wasn't quite correct when the project was created.
#please-close

**Comment by John-Hart** [comment]
#please-close
