### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by heyucongtom** [MicrosoftDocs/visualstudio-docs#1511]
Peek To Defintion -&gt; Peek Definition in Tour the IDE section.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* Content: [Overview of Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide?view=vs-2017#feedback)
* Content Source: [docs/ide/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-ide.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@heyucongtom Thanks for letting us know. I'm happy to fix this, but just to let you know in case you didn't, there's an Edit button at the top right of each Visual Studio topic that you can use to make small edits, if you'd like to contribute to the docs!

**Comment by heyucongtom** [comment]
Thanks! I didn’t see it at first :)
