### ISSUE TITLE
Instructions for word wrap on VS for Mac

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/visualstudio-docs#1512]
@m0rph90 commented on [Tue Sep 11 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/14)

Euch ist schon bewusst, dass ihr auch eine Mac OS Version habt....

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 00e3e8d0-48c3-3df6-8aeb-acd9624ffcd5
* Version Independent ID: 13f5da30-9f06-236f-4110-b6a172c52d1f
* Content: [Gewusst wie: Verwalten des Zeilenumbruchs im Editor - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor?view=vs-2017)
* Content Source: [docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by LisandroSu** [comment]
Hi team,

This issue is about the lack of instructions for the Mac OS version.

Thanks!

**Comment by gewarren** [comment]
@m0rph90 Unfortunately there is no word wrap support on VS for Mac. Please see #430 .

**Comment by jjacquetva** [comment]
is this a joke?
