### ISSUE TITLE
CA2214 - Different Message

### ISSUE THREAD

**Issue by JranZu** [MicrosoftDocs/visualstudio-docs#1515]
Not sure where the conflict is, but I show this warning code as:

Warning	CA2214	contains a call chain that results in a call to a virtual method defined by the class. Review the following call stack for unintended consequences

Also, it shows up with the VS implementation of this dispose method on an abstract class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78518637-409c-e51b-5dfc-75449565ee49
* Version Independent ID: bf378336-08a3-de6c-1c60-18907691342a
* Content: [CA2214: Do not call overridable methods in constructors - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2214-do-not-call-overridable-methods-in-constructors?view=vs-2017)
* Content Source: [docs/code-quality/ca2214-do-not-call-overridable-methods-in-constructors.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2214-do-not-call-overridable-methods-in-constructors.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@JranZu Thanks for the feedback. It may be that the rule changed when it was ported from FxCop static code analysis to Roslyn analyzers.

**Comment by gewarren** [comment]
@mavasani Do you know if the message for CA2214 changed from static code analysis to FxCop analyzers?

There's a SO question [here](https://stackoverflow.com/questions/41323614/warning-about-calling-overridable-auto-property-when-using-generics) from Visual Studio 2015 with the same warning mentioned in this issue ("'Derived.Derived()' contains a call chain that results in a call to a virtual method defined by the class...").

@JranZu Can you tell if the warning is coming from static code analysis or the Microsoft.CodeQuality.Analyzers package? (Look under the "Tool" column in the Error List - you might need to add this column.)

**Comment by mavasani** [comment]
@gewarren Seems like the CA2214 FxCop analyzers port changed the [diagnostic message](https://github.com/dotnet/roslyn-analyzers/blob/b5c77c05d0629e20dfe85fdf534e4196e14cb455/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MicrosoftQualityGuidelinesAnalyzersResources.resx#L193) to `Do not call overridable methods in constructors`. I am not sure if this was intentional or not. We can change the message if you feel it needs to be more descriptive.
