### ISSUE TITLE
Update command exits before the actual installation complete

### ISSUE THREAD

**Issue by guest512** [MicrosoftDocs/visualstudio-docs#1518]
Hi guys,
I using the next script (.cmd file) to update VS:

echo off
echo "Updating installer"
&lt;PATH&gt;\vs_enterprise.exe --update --quiet --wait
echo "Updating VS"
&lt;PATH&gt;\vs_enterprise.exe update --wait --passive --norestart --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
echo "All done"

And while the first command work perfectly well and I see that the installer is updated and script waits for its completion, the second command to perform actual update of the VS2017 returns before the setup even begins, and scripts shows me "All done" message, while the vs_installer process runs and performs update. As commands on this page are worked correctly? Or what parameter should I add to them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for Visual Studio installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by ben-dan-kelly** [comment]
Also running into this issue @TerryGLee @tedvz. When running in ps or bat file, the command "vs_enterprise.exe --update --quiet --wait" does not respect the --wait argument and returns almost instantly (verified that the installer does need to be updated).

**Comment by MikeMarlowe** [comment]
The documentation is correct.  The commands you listed should work (they worked for me in a similar cmd script).  

If you are having issues with these commands, please use https://developercommunity.visualstudio.com where you can search for existing issues and/or report a problem for a new issue.  That site will allow you to post log files and other data that may be needed to diagnose what is happening on your machine.

**Comment by guest512** [comment]
I think I should clarify myself, this script is used by TeamCity server in order to update VS on build agents, so it's running under a service logon session without UI, and in this case, this script doesn't work correctly.

Also, I tried to run this command on my local machine to update VS from 15.8.4 to 15.8.5 version, and for some reason, installers windows don't close at all! So my script waited until I close installer window after installer upgrade (the command: <PATH>\vs_enterprise.exe --update --quiet --wait) and only then it continues to work and update VS
