### ISSUE TITLE
Ctrl+Alt+G

### ISSUE THREAD

**Issue by tko39** [MicrosoftDocs/visualstudio-docs#1519]
Pressing Ctrl-Alt-G while debugging works perfectly on VS2015

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9abd0c2-b3c4-d544-c330-2940a193b854
* Version Independent ID: 4099b7e4-a7ec-4be2-cdf3-0eeed59e7472
* Content: [View Register Values in the Visual Studio Debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-registers-window?view=vs-2017)
* Content Source: [docs/debugger/how-to-use-the-registers-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-use-the-registers-window.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@tko39 Thanks! I'll make that update.
