### ISSUE TITLE
Broken link to this page

### ISSUE THREAD

**Issue by benmcmorran** [MicrosoftDocs/visualstudio-docs#1522]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.tagging.textmarkertag?view=visualstudiosdk-2017 has a broken link to this walkthrough.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0202ec00-b320-aa14-484c-06b37e38dcd1
* Version Independent ID: 73d6ad23-9bd0-6231-d2f6-a7be2f187049
* Content: [Walkthrough: Displaying Matching Braces - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-matching-braces?view=vs-2017)
* Content Source: [docs/extensibility/walkthrough-displaying-matching-braces.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-matching-braces.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@benmcmorran Thanks for letting us know, Ben.

**Comment by gregvanl** [comment]
Working on a fix to remove trailing .md file extension in conceptual topic links in Remarks.

**Comment by gregvanl** [comment]
Fixed and published
