### ISSUE TITLE
Example crashes

### ISSUE THREAD

**Issue by joshuamaiche** [MicrosoftDocs/visualstudio-docs#1523]
This example, as-is, does not seem to work on VS 15.8.4.

In TriggerCompletion(), the call to m_session.Start() will trigger OnSessionDismissed(), nullifying m_session and causing call to m_session.Filter() to throw an exception.

There seems to be a problem with the CompletionBroker, as calls to TriggerCompletion() will also return null.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e759cd22-3920-94e9-5d7a-e1766e2f79db
* Version Independent ID: b4796726-14a3-342e-448f-10fb0ba2deb1
* Content: [Walkthrough: Displaying Statement Completion - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-statement-completion?view=vs-2017#prerequisites)
* Content Source: [docs/extensibility/walkthrough-displaying-statement-completion.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-statement-completion.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by joshuamaiche** [comment]
I've identified the fix. The top of TestCompletionSourceProvider has [Name("token completion")]. This seems to conflict with an existing source provider's name, and changing it fixes the problem. Seems like some extension is using the example name. Since I'm only using default-installed Visual Studio extensions, I suspect most people following this example will have the same problem. Would be worth changing the name in the example, and maybe checking on the default extensions to ensure none are using example names.

**Comment by gewarren** [comment]
@joshuamaiche Thank you for letting us know, and for posting the solution!

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
