### ISSUE TITLE
Unable to add domain and hostnames to firewall rules

### ISSUE THREAD

**Issue by behzadian** [MicrosoftDocs/visualstudio-docs#1524]
I'm using windows firewall and blocked all outgoing connections except allowed
There are some problems with visual studio downloader:
1. Windows Firewall does not accept domains. Only IPs can be specified
2. In every request, IP of a domain may be different, for example aka.ms will point to 23.77.144.151 and 23.64.45.216 (in nslookup from different locations and different time)
3. There are a lot of addresses to be add
5. Visual studio downloader, extracts itself into tmp folder and one of extracted executable in that folder, connects to network, so it is not possible to add a rule with specific executable in Windows Firewall

After all, I couldn't download vs without disabling firewall

Please change visual studio downloader so a permanent and specific executable connect to internet. In this case, we can add that executable to Windows Firewall and trust it

**Comment by TerryGLee** [comment]
@behzadian Thanks for your input. If you would like to see a change in how the product works, please consider using either the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) tool, or the [Suggest a feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017) tool. Meanwhile, your input here is on record.
