### ISSUE TITLE
Modify the instructions of installing certificates required for Visual Studio offline vs2018.8

### ISSUE THREAD

**Issue by moh-hassan** [MicrosoftDocs/visualstudio-docs#1525]
The instructions of  [Install certificates required for Visual Studio offline installation](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-certificates-for-visual-studio-offline.md)
isn't applicable because:

1) The certification downloaded in certification folder of vs2017.8 are:
>manifestCounterSignRootCertificate.cer
manifestRootCertificate.cer
vs_installer_opc.RootCertificate.cer

it's cer format not p12 format and the names of files  in commandline are different.

2) In some computers, there is no commandline tool certmgr.exe available, only windows  crtmgr.msc (interactive tool).

Modify the instructions of installing certificates required for Visual Studio offline vs2018.8 using both the interactive tool certmgr.msc or the cmmandline tool (if the tool available).
Explain where the certification should be stored (user/computer account, . etc.)

**Comment by TerryGLee** [comment]
Please note that in "Option 3 - Install certificates as part of a scripted deployment of Visual Studio" section, we added an example that shows certutil.exe, which Visual Studio 2017 version 15.8 Preview 2 or later uses. If this doesn't work for you, let us know by using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
