### ISSUE TITLE
What is websiteurl here?

### ISSUE THREAD

**Issue by agrabhi** [MicrosoftDocs/visualstudio-docs#1526]
Its not clear from the documentation what is the websiteurl. 
When we are profiling on the production machine on whcih website is running, what is the website url? 
1. Is it the location of the website on the disk? 
2. Or localhost url? 
3. or something else. 

A real example will help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3b258a-663f-090d-bea6-4d741df7343e
* Version Independent ID: 1f997137-0c54-7646-3214-aeb1dc25889e
* Content: [Rapid Web Site Profiling with VSPerfASPNETCmd - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd?view=vs-2017)
* Content Source: [docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@agrabhi You might take a look at this topic; it has information on using the Performance Profiler on local sites and external sites. https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-collect-performance-data-for-a-web-site?view=vs-2017

**Comment by gewarren** [comment]
@Mikejo5000 Can this be closed, or do we need to add a link to the topic you mentioned, perhaps?

**Comment by Mikejo5000** [comment]
Updating doc, adding link
