### ISSUE TITLE
A sample wil help here 

### ISSUE THREAD

**Issue by agrabhi** [MicrosoftDocs/visualstudio-docs#1527]
I tried 
&gt;VSPerfASPNETCmd /i WEBSITE https://abc.com
It threw error 
&gt;VSPerfASPNETCmd /i https://abc.com
also threw error

May be a good tool but bad documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd3b258a-663f-090d-bea6-4d741df7343e
* Version Independent ID: 1f997137-0c54-7646-3214-aeb1dc25889e
* Content: [Rapid Web Site Profiling with VSPerfASPNETCmd - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd?view=vs-2017)
* Content Source: [docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/rapid-web-site-profiling-with-vsperfaspnetcmd.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Adding more info on website URL and a link.
