### ISSUE TITLE
cannot see the images

### ISSUE THREAD

**Issue by torontom** [MicrosoftDocs/visualstudio-docs#1528]
followed the steps but in the end cannot see those images! 
deployed to Azure using web deploy successfully tho.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa65a08-a9e2-721d-e00c-1f28afffe2be
* Version Independent ID: babf20c3-c235-d839-7340-fb9c11c449dc
* Content: [Create a Node.js and Express app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs?view=vs-2017)
* Content Source: [docs/javascript/tutorial-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@torontom Hi, I checked the URLs and they are still good. Did you press the buttons? The images don't show until you press the first button.

**Comment by saf-itpro** [comment]
@Mikejo5000  The images folder is empty. Please see my post above.

**Comment by Mikejo5000** [comment]
@saf-itpro Please see my note in the other post. Thanks.

**Comment by gewarren** [comment]
@Mikejo5000  Seems like this can probably be closed?
