### ISSUE TITLE
Can you create a guide for mvc / web api?

### ISSUE THREAD

**Issue by CarlosOnline** [MicrosoftDocs/visualstudio-docs#1529]
Can you create a guide for mvc / web api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a644716-10c3-cc90-eeab-495c265e5728
* Version Independent ID: c356a0d8-1d24-2ab7-18de-b9b3088fd4d9
* Content: [Create a Vue.js app using Node.js Tools for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/create-application-with-vuejs?view=vs-2017#limitations)
* Content Source: [docs/javascript/create-application-with-vuejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/create-application-with-vuejs.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@CarlosOnline Do you want to use MVC / web API with Node.js and Vue.js? If not, the ASP.NET docs would be helpful.
If you want to do this with Node.js and Vue.js I haven't seen that specific guidance, but this doc does give you info on using Vue.js and Node.js with ASP.NET Core: https://docs.microsoft.com/en-us/visualstudio/javascript/create-application-with-vuejs?view=vs-2017
Maybe this will help?

**Comment by GusBeare** [comment]
I want to use Vue.js with TS in Visual Studio for an MVC project but I want VS to build the .ts files without Webpack. I have managed this with AngularJS and have a very simple setup that compiles the .ts files to .js. I then use the .Net bundler to bundle all the files at build.  I can't seem to find any help on how to do this with Vue.js. All the examples are very complicated and involved a build step outside of VS. Any suggestions?

**Comment by Mikejo5000** [comment]
@GusBeare What are you using the compile to .ts files to .js? @billti @armanio123 for suggestions

**Comment by GusBeare** [comment]
I am using Visual Studio. If you create a tsconfig.json file in visual studio and point it at your .ts files it then trasnpiles them to .js. That works fine. With AngularJS I am able to get VS to transpile all my .ts controllers into .js.  I can do this with Vue.js.   However, I think there is no way of doing it without some kind of module loader/bundler.  My knowledge of this stuff is poor.  

However, I have managed to get the simplest build set up I can find. But I had to accept defeat and use webpack + vue-loader to make it work.  So now I have Visual Studio with ASP.NET MVC project with Typescript and Vue single file components.  I installed the NPM Task Runner extension for VS so I can now run npm build when I build in VS.

**Comment by billti** [comment]
If you are using .vue files, then you need to use WebPack or similar with a loader to do the conversion. TypeScript or Visual Studio don't know how to compile .vue files. Similarly for bundling. TypeScript doesn't know how to convert ES2015 modules (i.e. import/export statements) into a single final .js file to load in the browser. Again, WebPack is the best choice here.

You can drive this external build/package process from within MSBuild (Which is what the ASP.NET Core templates for Angular and React do, as well as the Node.js Vue.js template). There is no ASP.NET template for Vue.js development currently in the box.

**Comment by GusBeare** [comment]
Thanks, that's very helpful. There are many tutorials out there but all they seem to do is list the steps it takes to get something running and not why you need yarn, gulp, npm, webpack etc etc. It's a minefield.

It would be useful if there was a ASP.NET (not Core) + Vue.js template similar to the .NET Core one but most of the effort seems to be centered around .Net Core and VS code. To get under way quickly with a project and a new .js framework I am not keen to to also burden myself with learning .Net Core at this stage. Besides none of the team know .Net Core well too.

**Comment by gewarren** [comment]
@Mikejo5000 Should we add Bill's response info to an article, or can this be closed as-is?

**Comment by Mikejo5000** [comment]
Adding some of Bill's comments.
