### ISSUE TITLE
Incorrect help file from a Linux build

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/visualstudio-docs#1530]
I was trying to change the setting "Remote Build Machine" on a Linux cross platform build; pressing F1 leads me to this page - it is NOT Android C++.

The larger problem is that I can't seem to change the target property - the IP address changed. You would think the property sheet would let you change it (you can edit the line but the changes disappear), or make a reference to where you can change it.

So there's two problems - F1 goes to the wrong help page, and "Remote Build Machine" isn't documented (obviously as we're on the wrong page).

== John ==

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34bd2a39-b0f4-5a70-1222-0e5390487ee3
* Version Independent ID: 1a486245-adeb-b21a-8885-06f054c3478a
* Content: [General Project Properties (Android C++) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/general-android-prop-page?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.VCConfiguration.BuildLogFile)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2017)
* Content Source: [docs/cross-platform/general-android-prop-page.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/general-android-prop-page.md)
* Product: **visual-studio-dev15**
* GitHub Login: @corob
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@jgwinner 

Sorry you ran into trouble. We recently addressed some F1 issues, so in Visual Studio 2019 version 16.5 (currently in preview), you're not taken to this clearly wrong page. Unfortunately, we just discovered there's another bug in Visual Studio, where it's sending the wrong keyword for many of the Linux properties. This bug had been hidden by the other bug that got fixed. That means a real fix will probably be in the next minor release after 16.5. As a workaround, the page you'll be taken to now has links to the correct pages in its first paragraph. Specifically, you'll want to look at [General properties (Linux C++)](https://docs.microsoft.com/en-us/cpp/linux/prop-pages/general-linux?view=vs-2019). 

On the latter page, I added some information about adding and editing remote machine connections. Even though it looks like these should be editable properties, you have to use the Connection Manager to set up and change remote machine connections. Select the **Tools** > **Options** menu to open the Options dialog. Edit connections in the **Cross Platform** > **Connection Manager** page. This doc update will be published on the live site within a day. You should be good to go.
