### ISSUE TITLE
FileLogger no longer in Microsoft.Build.Engine on Core

### ISSUE THREAD

**Issue by dasMulli** [MicrosoftDocs/visualstudio-docs#1534]
trying to use `FileLogger` from `Microsoft.Build.Engine` using MSBuild's netcoreapp build results in:
```
dotnet msbuild "-l:FileLogger,Microsoft.Build.Engine;logfile=MyLog.log"
Microsoft (R) Build Engine version 15.8.166+gd4e8d81a88 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1021: Cannot create an instance of the logger. Could not load file or assembly 'Microsoft.Build.Engine, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

when using the now correct `Microsoft.Build` assembly:

```
dotnet msbuild "-l:FileLogger,Microsoft.Build;logfile=MyLog.log"
```
then the build continues and works as expected, producing the `MyLog.log` file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updating. @rainersigwald for possible comments.

**Comment by rainersigwald** [comment]
> Probably this also needs a scan for all documents referencing the deprecated `Microsoft.Build.Engine` assembly which exists on full-fx distributions (AFAIK only for backwards-compatibility).

I agree, we shouldn't be advising use of `Microsoft.Build.Engine.dll` or `Microsoft.Build.Conversion.dll` anywhere in the docs, unless we have a big "don't do this, it's deprecated" warning next to it.
