### ISSUE TITLE
My emulator Doesn't work

### ISSUE THREAD

**Issue by bobjoe13221** [MicrosoftDocs/visualstudio-docs#1536]
Everytime I run the program it opens the emulator but then it opens the emulator to the android home screen instead of the app i made

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14465304-3ced-6b36-5054-a85ac11e667e
* Version Independent ID: 9d2d9ca3-8d71-b81c-dbbb-bf4b269db034
* Content: [Build apps with native UI using Xamarin in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio?view=vs-2017#design-the-look-and-feel-of-your-app)
* Content Source: [docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by gewarren** [comment]
@conceptdev FYI. Should we update the author in these topics?

**Comment by bobjoe13221** [comment]
@gewarren I think we should

**Comment by dbybanez** [comment]
Just to add, in my end, when running it in an emulator, it shows an error:

ADB0000 value cannot be null

**Comment by conceptdev** [comment]
@bobjoe13221 if you are experiencing issues with Xamarin or Visual Studio, please use the **Help > Report a problem** menu item or visit [Developer Community](https://developercommunity.visualstudio.com/).

These issues are to improve the documentation, you can also click on the **Product feedback** link on the documentation page to report product issues.

**Comment by conceptdev** [comment]
#please-close

**Comment by conceptdev** [comment]
Sorry to hear that, as I said [above](https://github.com/MicrosoftDocs/visualstudio-docs/issues/1536#issuecomment-423251039) the correct place to report issues with the product is on the [Developer Community](https://developercommunity.visualstudio.com/) site.
