### ISSUE TITLE
csharp_new_line_before_open_brace --> object_collection_array_initializers

### ISSUE THREAD

**Issue by LukeOwlclaw** [MicrosoftDocs/visualstudio-docs#1540]
I believe there is a typo in section **csharp_new_line_before_open_brace** 

The list of possible values contains: `object_collection_array_initializers`

My hunch suggests that it should be two options: `object_collection` and `array_initializers`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@LukeOwlclaw According to [this](https://github.com/dotnet/roslyn/issues/18010#issuecomment-288192477), your hunch is incorrect.

**Comment by LukeOwlclaw** [comment]
Thanks, agreed! Then it was just a mistake by [IntelliCode ](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio). It added `object_collection` to my `.editorconfig` file. Maybe it was because the line was too long and it was cropped.

**Comment by gewarren** [comment]
Thanks @LukeOwlclaw . If you think it's a bug in IntelliCode, please file an issue here: https://github.com/MicrosoftDocs/intellicode/issues
