### ISSUE TITLE
The scripts doesn't work

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/visualstudio-docs#1542]
@Schinwinkwinsky commented on [Tue Sep 18 2018](https://github.com/MicrosoftDocs/visualstudio-docs.pt-br/issues/3)

I use a MacBook Pro with Brazilian Portuguese Language. I made all the steps as mentioned above, but the script doesn't run because there are "commands not recognized". Could it be because of the language?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Desinstalando o Visual Studio para Mac - Visual Studio for Mac](https://docs.microsoft.com/pt-br/visualstudio/mac/uninstall)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs.pt-br/blob/live/mac/uninstall.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by LisandroSu** [comment]
Hi team,

Please check on this issue.

Thanks!

**Comment by conceptdev** [comment]
That's great, I'm so glad you were able to get it working. 

Thanks for this information - we'll try to add some help on the page as well.
