### ISSUE TITLE
Build is successful, but emulator never loads anything. Only "Android" logo

### ISSUE THREAD

**Issue by exe404** [MicrosoftDocs/visualstudio-docs#1543]
At step: "In the Visual Studio toolbar, you'll see WeatherApp.Android listed as the target project. Select one of the Android emulators for debugging and hit F5. We recommend using one of the VisualStudio emulator options that will run the app in the Visual Studio Emulator for Android."

I am getting multiple warnings, and my emulator never loads. It notifies that there are build errors, do I wish to continue. I except with a "Yes" and nothing ever loads.

Here is the errors:
https://i.imgur.com/L5MrFrK.png

Edit Update: I Changed the Emulator to run the "tablet" version. It gave a different error, so I did a rebuild, then launched again. The emulator then came up a screen saying intitializing app X of X. Then finally launched. Not sure if the "phone" version is buggy or what. I am able to at least see the app now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b25d4cd-0c3f-e9a6-6256-ea54d0972d4b
* Version Independent ID: babd49b7-8e18-13dc-99f2-6783495cb0dc
* Content: [Learn app-building basics with Xamarin.Forms in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio?view=vs-2017)
* Content Source: [docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @charlespetzold
* Microsoft Alias: **chape**

**Comment by conceptdev** [comment]
I'm really glad you got it working. You can read more about [Android emulators](https://docs.microsoft.com/xamarin/android/get-started/installation/android-emulator/) in the Xamarin docs.

In future, if you have issues with the product, click on the **Product feedback** link on the documentation page. Alternatively, you can use the **Help > Report a problem** menu item or visit [Developer Community](https://developercommunity.visualstudio.com/).
