### ISSUE TITLE
Defining required extensions for a project

### ISSUE THREAD

**Issue by amervitz** [MicrosoftDocs/visualstudio-docs#1546]
Is there a way to define a list of extensions that are required for a project, and have Visual Studio detect when they are missing? This would be similar to what is described in https://github.com/Microsoft/vscode/issues/5559.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and use Visual Studio extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2017)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by cartermp** [comment]
@gewarren I think this should be `area-extensibility`.

**Comment by gewarren** [comment]
Visual Studio considered adding this functionality at one time, but unfortunately the feature was cut.

**Comment by amervitz** [comment]
@gewarren according to this idea, this functionality is being added to vs2019 https://developercommunity.visualstudio.com/content/idea/351158/allow-to-automatically-install-extensionsplugins-p.html
