### ISSUE TITLE
Naming suggestions for comments in the example editorconfig

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#1550]
https://github.com/dotnet/roslyn/pull/30043 aims at adding functionality in Visual Studio to automatically generate an .editorconfig from the current Visual Studio settings. During the PR, @CyrusNajmabadi had a bunch of feedback about the naming and consistency for the comments. We should try to fix these in the documentation here, and I will submit a follow-up Roslyn change to make similar changes in the generated .editorconfig for the Visual Studio feature mentioned above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#example-editorconfig-file)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
Please add a comment to https://github.com/dotnet/roslyn/issues/30083, once this issue has been fixed/resolved. Thanks!

**Comment by gewarren** [comment]
@kendrahavens This needs some PM input as it affects strings in the autogenerated EditorConfig file too. The concerns are:

- Should we refer to "C# coding conventions", or "C# code style rules"?
- Should we refer to VB or Visual Basic? (The DevDiv style guide says always expand VB to "Visual Basic".)
- "Pattern matching preferences" or "pattern-matching preferences"? (The second one is more correct.)

**Comment by kendrahavens** [comment]
Definitely refer to VB as Visual Basic. I'd go by that style doc as well.

@jinujoseph I don't have a strong opinion on the other two points. Were those the only issues Cyrus brought up?

**Comment by kendrahavens** [comment]
Yes, that's one of the ones I don't have a strong opinion on. I'm happy if Genevieve goes with what she notes is more correct. :)

**Comment by jinujoseph** [comment]
lets go with pattern-matching preferences

**Comment by gewarren** [comment]
Thanks all. Last point in question:

Should we refer to "C# coding conventions", or "C# code style rules"?

**Comment by kendrahavens** [comment]
Thanks, let's go with "C# code style rules". It's what we've been using in talks and a more popular search term: https://trends.google.com/trends/explore?geo=US&q=C%23%20code%20style,C%23%20code%20convention
