### ISSUE TITLE
Update to E5

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/visualstudio-docs#1552]
Are there plans to update this to an E5 level for O365 and EM+S.  This would extremely useful from a dev/test standpoint.  Including a sandbox CRM instance would also be a huge win if you want people to develop against the platform.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22a69a8-de38-2929-144a-0bd738f40a25
* Version Independent ID: a1d94b1f-c61e-df28-d412-1195aa9ace6d
* Content: [The Office 365 Developer Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office-dev)
* Content Source: [subscriptions/vs-office-dev.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-office-dev.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@lankaim @caitybuschlen FYI

**Comment by evanwindom** [comment]
@danmyhre Thanks for the inquiry.  I'm not aware of any plans to change those benefits, but I will pass your suggestions along to our benefits planners.

**Comment by evanwindom** [comment]
@danmyhre  - I did some checking on this, and it looks like we're already at E5 for EMS.

**Comment by danmyhre** [comment]
Mine is all E3 level.  It is also missing Dynamics, which makes developing/demoing Dynamics difficult.

Office 365 Enterprise E3 Developer
Enterprise Mobility + Security E3

**Comment by TerryGLee** [comment]
@danmyhre Thanks for your additional feedback. I'm certain that @evanwindom will pass that along too, to our benefits partners. Meanwhile, I will close the issue, as the original question of "Are there plans to update this to an E5 level for O365 and EM+S" has been asked and answered.
