### ISSUE TITLE
Pease update layout disk space estimate

### ISSUE THREAD

**Issue by TASlavens** [MicrosoftDocs/visualstudio-docs#1555]
The important note in section "Create an offline installation folder" states that a full layout may take up to 35GB.  That size estimate is outdated.  My English-only full layout of 15.8.5 takes 42.7 GB.  With full language support, it would surely have been much larger still.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@TASlavens Thanks for your feedback. Please note that the documentation states that it will take "at least 35 GB" which denotes a minimum number that could go higher. However, we'll investigate and change the documentation if necessary.

**Comment by TASlavens** [comment]
I have a correction:  My English-only full layout of 15.8.5 takes 41.5 GB after pruning the archive of 15.8.4.  Thanks!
