### ISSUE TITLE
Is Namespace element supported for C# projects?

### ISSUE THREAD

**Issue by robertlarkins** [MicrosoftDocs/visualstudio-docs#1559]
I'm creating a code snippet, and the _Note_ under Namespace element (as well as under _Import_ and _Imports_) says

> The `Namespace` element is only supported for Visual Basic projects.

But when using the following

```xml
<Imports>
    <Import>
        <Namespace>Xunit</Namespace>
    </Import>
</Imports>
```

on a C# snippet it will insert a `using Xunit;` at the start of the class. Is this note correct (and I misunderstood it), or is it outdated?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91faad91-f76f-1c35-3ff7-b8dea92c00f1
* Version Independent ID: d974b7e1-f76a-c575-bff8-cf4d38d19771
* Content: [Code snippets schema reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2017#namespace-element)
* Content Source: [docs/ide/code-snippets-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-snippets-schema-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@robertlarkins Thanks, I will try to find out and update the topic.
