### ISSUE TITLE
Kind attribute provides no restrictions

### ISSUE THREAD

**Issue by robertlarkins** [MicrosoftDocs/visualstudio-docs#1560]
The `Code` element has the `Kind` Attribute, but the way it is worded (at least for me) indicates that if I use a `Kind` of _method decl_ then the code snippet should either indicate or restrict its insertion if it is outside of a `class` block. When attempting to use a C# code snippet with this Kind outside of a `class` block in Visual Studio 2017 there is no indication that this shouldn't be done, nor any restriction on the snippet being inserted.

What effect should `Kind` have on the use of a code snippet? Should it convey some sort of information somewhere on where the snippet can be inserted? Should it restrict its insertion in incorrect locations? Or am I misunderstanding the purpose of the Kind attribute?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91faad91-f76f-1c35-3ff7-b8dea92c00f1
* Version Independent ID: d974b7e1-f76a-c575-bff8-cf4d38d19771
* Content: [Code snippets schema reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2017)
* Content Source: [docs/ide/code-snippets-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-snippets-schema-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@robertlarkins Thank you for the feedback.

You are correct, the `Kind` attribute provides no restrictions on where to the code snippet.

The documentation has been updated accordingly.
