### ISSUE TITLE
InstallShield Limited Edition Project

### ISSUE THREAD

**Issue by manimaran66** [MicrosoftDocs/visualstudio-docs#1564]
InstallShield Limited Edition Project is not available for vs 2017. Please include the steps for 'How to use the existing setup project for office solution deployment'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 283a3669-9f0e-c872-028d-9eac66fc221b
* Version Independent ID: bdfea87a-3b7d-80ef-51f2-ceadb1ba26bb
* Content: [Deploy an Office solution by using Windows Installer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-an-office-solution-by-using-windows-installer?view=vs-2017#Download)
* Content Source: [docs/vsto/deploying-an-office-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/deploying-an-office-solution-by-using-windows-installer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@manimaran66 Thanks for your feedback! We're aware that this page needs updating. It's on our backlog to fix.

**Comment by manimaran66** [comment]
@TerryGLee - Thanks for your quick response. :)

**Comment by gewarren** [comment]
@manimaran66 You might check out this section and see if it helps you. https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components?view=vs-2017#create-an-installer-package-windows-client

**Comment by akeeton** [comment]
https://marketplace.visualstudio.com/items?itemName=VisualStudioClient.MicrosoftVisualStudio2017InstallerProjects

**Comment by TerryGLee** [comment]
@John-Hart FYI

**Comment by John-Hart** [comment]
Please see the updated document: https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2019
