### ISSUE TITLE
Totally Offline Installation /Update

### ISSUE THREAD

**Issue by GCPD** [MicrosoftDocs/visualstudio-docs#1566]
I have seen some other comments similar to this which appear to have been resolved but I am still a little confused.  There are a number of full licensed Visual Studio Profession installations at this establishment, one of which is on a TOTALLY ISOLATED SYSTEM WITH NO EXTERNAL NETWORK  CONNECTIONS.  Following my interpretation of the instructions for creating an OFFLINE installation, or in my case update to Visual Studio, on a system which is allowed an Internet connection I used the command line  vs-professional.exe --layout g:\vs2017layout --lang en-us
This ran, as expected, for a considerable length of time and has produced a folder vs2017layout containing a significant amount of data - 39.3GB in size.
After passing the internal validation checks, (which are carried out via a writeblocker so can not affect the contents,) the media containing the vs2017layout folder wasattached to the OFFLINE system,(not via a writeblocker). The command vs_professional.exe within the vs2017layout folder, which mimics the one used to create that folderis run.  After a short while it recognised that an earlier edition of the VS 15 was installed and suggested that update was chosen.  It then ran for a short while before complaining that it was unable to access the Internet to download essential files.  The whole purpose of this exercise was to carry out the update on a system TOTALLY ISOLATED from the INTERNET and I would be grateful for any advice  on how this is achieved. Note in parallel to this another system which is alowed INTERNET access was also updated and appears to have carried this out without any issues at all.  Did I miss something in the documentation for the OFFLINE?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017#get-support)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@GCPD To resolve installation problems such as this, please consider using either our [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by MilesGibson** [comment]
Why would you go away from the standard and reliable .iso method of installing?  The writer above is absolutely right in his assertion that he needs a completely offline method of installation. With the rapid rise in ransomware and intellectual property theft by foreign nationals, it is reasonable to want to have systems that are completely isolated from the Internet.  In fact, I suspect that a lot of dev shops are doing exactly that right now.

**Comment by TerryGLee** [comment]
@MikeGibson We appreciate your feedback. There is one specific GitHub Issue previously tendered to this topic that if you haven't already read it, you might want to take a look at it now: #[607](https://github.com/MicrosoftDocs/visualstudio-docs/issues/607). Specifically, it includes a comment from @tedvz as to the reasons why we chose not to release an ISO for Visual Studio 2017.

**Comment by komondor5** [comment]
I have downloaded the files and done quite a few offline installs with no issue.  I believe the issue was that VS 2015 was there before.  I would suggest testing on a virgin system and verify that it does work for you.  Don't forget that you need to get the updates on whatever schedule you prefer and update your repository then the users run the update command to update their installs.   The reason there is no ISO is the size of the download which is over 30GB.  I do wish they made it easier to include or exclude certain platforms.  Since we are on a closed network we wil never be using anything that has to do with cell phone applications or running on anything but Windows.

**Comment by tydunkel** [comment]
@GCPD Was the original install of Visual Studio on the isolated system installed from the web? Or was the system isolated at that time? Installations from the web can only be updated from the web, and installs from an offline layout can only be updated from the same layout location they were installed.

e.g. if the original install was installed from C:\VS2017Layout, then it can only be updated from C:\VS2017Layout or from the web.

To update an offline installation offline, the original layout location needs to be updated. Documentation for this is described in [Update a network-based installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2017#how-to-update-a-network-layout). Once the updated packages are downloaded to the layout, running the update should use the packages from the layout and avoid attempting to download from the web.
