### ISSUE TITLE
You need to select the “All accessible accounts” option in the dropdown

### ISSUE THREAD

**Issue by jcansdale** [MicrosoftDocs/visualstudio-docs#1568]
I wasn't able to get this to work until I got the following tip:
https://github.com/jcansdale/TemporaryProjects/issues/7#issuecomment-424073242

Maybe the “All accessible accounts” option should be mentioned in the docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71dd9bd6-f1f7-e030-3ee7-3a3faf7d7e59
* Version Independent ID: f4e9045e-daa2-55ed-9449-d13c80e29138
* Content: [Walkthrough: Publishing a Visual Studio Extension via command line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line?view=vs-2017)
* Content Source: [docs/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by Ackara** [comment]
How do you get the personal access token?

**Comment by gregvanl** [comment]
@Ackara There is a write-up in the VS Code docs at https://code.visualstudio.com/docs/extensions/publish-extension#_get-a-personal-access-token. VS Code extensions are also on the Visual Studio Marketplace.

**Comment by yannduran** [comment]
Even better would be an explanation of **WHY** you need to select "_All accessible accounts_" in the dropdown.

It makes perfect sense that you might want to create a PAT for just **ONE** organisation. So why do we have to choose "all"?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
