### ISSUE TITLE
why theres no application designer in my settings of vb

### ISSUE THREAD

**Issue by beberly11** [MicrosoftDocs/visualstudio-docs#1569]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36735fb-5d5f-72c0-e71d-cff66dd1e909
* Version Independent ID: 8f3d80cc-7f07-1f8e-130a-cc28051418db
* Content: [Application Page, Project Designer (Visual Basic) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/application-page-project-designer-visual-basic?view=vs-2017)
* Content Source: [docs/ide/reference/application-page-project-designer-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/application-page-project-designer-visual-basic.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by beberly11** [comment]
why that i cant see the application designer in the settings project

**Comment by gewarren** [comment]
@beberly11 Can you provide a little more information, like what kind of Visual Basic project did you create? Is it a .NET Framework or a .NET Core project?
