### ISSUE TITLE
Create a cut-down layout from an existing layout

### ISSUE THREAD

**Issue by uecasm** [MicrosoftDocs/visualstudio-docs#1570]
If I have an existing "full" layout (no `--add` filters), and I want to create a new layout with fewer components (for reduced disk space) while still using the existing layout as a source rather than re-downloading packages ... what is the command for that?

I tried specifying `--installChannelUri` as documented in "Use the command line" but apparently this is not valid with `--layout`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@uecasm For installation support requests, please consider using either our [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by uecasm** [comment]
This was a feature request, not a support request.

**Comment by TerryGLee** [comment]
@uecasm Thanks for the further clarification. For information about that, please see our [Suggest a feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017) page. (As an FYI, these options are listed in the "Get support" section of any installation-related page.)
