### ISSUE TITLE
No annotations 2017

### ISSUE THREAD

**Issue by bharath-ram** [MicrosoftDocs/visualstudio-docs#1571]
Not able to see any annotations in my vs2017 scroll bar

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9440cd51-f00a-2a66-c895-0c093c6c883d
* Version Independent ID: 77cf076b-949f-ce9a-882f-7a0c02d268d0
* Content: [How to: Track your code by customizing the scrollbar - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-track-your-code-by-customizing-the-scrollbar?view=vs-2017)
* Content Source: [docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@bharath-ram Perhaps you need to switch to "bar mode" instead of "map mode". Can you check in Tools > Options > Text Editor > All Languages > Scroll Bars?

![image](https://user-images.githubusercontent.com/24882762/46032876-9d8fee00-c0b1-11e8-8ec5-4cbade43925e.png)

**Comment by ermajo89** [comment]
Same issue here. VS 15.8.6. Map and bar mode doesn't work. After disabling and enabling annotations for vertical scroll bar, annotations a short time visible after OK click in Options window.

**Comment by gewarren** [comment]
@ermajo89 @bharath-ram If you are still having scroll bar issues, please report the issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) (which will ask you to use the Help > Send Feedback > Report a Problem menu in Visual Studio so that diagnostic information is captured along with the report).
