### ISSUE TITLE
com addin disabled, and cannot enable again

### ISSUE THREAD

**Issue by eriksten** [MicrosoftDocs/visualstudio-docs#1572]
When - In Outlook 365 -  I click on the "enable" button, nothing happens. I've tried to uninstall the addin completely and reinstall, but still  it's not possible to enable the addin again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38dd704e-cbe0-8e26-9b37-ec8b72d9e7c8
* Version Independent ID: 675c782d-dae8-3559-616f-9c74859dbbb8
* Content: [How to: Re-enable a VSTO Add-in that has been disabled - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-re-enable-a-vsto-add-in-that-has-been-disabled?view=vs-2017)
* Content Source: [docs/vsto/how-to-re-enable-a-vsto-add-in-that-has-been-disabled.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-re-enable-a-vsto-add-in-that-has-been-disabled.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@eriksten Thanks for your feedback. We are aware that the documentation is outdated, which might contribute to the behavior that you noted. The VSTO documentation is in our backlog queue to update. Meanwhile, for more immediate assistance, please consider posting your inquiry to the [StackOverflow](https://stackoverflow.com/search?tab=newest&q=vsto%20enable%20add-in) site (and note that the link I've included goes directly to a collection of questions and answers that are tagged with "enable add-in" and "VSTO").

**Comment by John-Hart** [comment]
The document describes an issue where the Add-in may immediately be disabled if there are issues, it's hard to tell but that maybe the issue.  The recommendation of posting on StackOverflow is the best solution.
#please-close
