### ISSUE TITLE
CA2202 - This seems incorrect.

### ISSUE THREAD

**Issue by kingmotley** [MicrosoftDocs/visualstudio-docs#1575]
The example, and the code that Visual Studio is using the detect multiple disposes seems to be incorrect.  The inner using statement should not (and currently does not that I can see) dispose of the object defined in the outer using.  It does/may close the object, but that is (or could be) very different from disposing it.  Please review this for accuracy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836e7028-0bda-ef7c-fc11-4babb54ae70a
* Version Independent ID: 540dfe05-8e43-ed02-93d9-444c22485f84
* Content: [CA2202: Do not dispose objects multiple times - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2202-do-not-dispose-objects-multiple-times?view=vs-2017)
* Content Source: [docs/code-quality/ca2202-do-not-dispose-objects-multiple-times.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2202-do-not-dispose-objects-multiple-times.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by dynamatt** [comment]
I tend to agree with kingmotley. The static analyser should detect classes which dispose objects that they didn't create. Shouldn't we be alerting people to code that is written incorrectly, rather than polluting the calling code with checks to make sure the code it calls does the right thing?

**Comment by kingmotley** [comment]
I looked through a bunch of different implementations of classes that take an object, and apparently there are some that do dispose of the outer object even though it really shouldn't be doing that.  It's not even consistent within the .Net framework itself which makes it even worse.

Although I still believe this is backwards.  The warning should be that the inner object (when it does this) is incorrectly disposing of an object that doesn't belong to it.

For example, this should be perfectly correct:

```
using(var something = new object())
{
  using(var adapter1 = new adapter(something))
  {
    adapter1.DoSomething();
  }
  using(var adapter2 = new adapter(something))
  {
    adapter2.DoSomething();
  }
}
```

Which doesn't work if adapter1's disposing is also disposing of something.

**Comment by ptoye** [comment]
A well as `using` the detection seems to be over-enthusiastic in `for each` loops as well. The following code snippet gives an error `Warning	CA2202	Object 'Me.PlayableList.GetEnumerator()' can be disposed more than once in method 'ButtonGrid.Play(Boolean)'. To avoid generating a System.ObjectDisposedException you should not call Dispose more than one time on an object.`

`
    While EmptyCount <> 0
    
      Do While PlayableCount > 0
        For Each KVP In PlayableList
       
        Next KVP

      Loop 

    End While 
`
`PlayableList` is a SortedList.

This looks like a bug to me.

**Comment by gewarren** [comment]
It appears that this rule CA2202 has not been ported to [FxCop analyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers). @mavasani Are there any plans to port CA2202? If not, can you comment on the likelihood of this rule being changed according to the above feedback?

**Comment by mavasani** [comment]
@gewarren We have decided to not port this rule given the large amount of negative feedback around it. For example, see https://github.com/dotnet/roslyn-analyzers/issues/528#issuecomment-161314351. The rule seems to cause more pain then benefit for customers, especially given that dispose implementations that follow recommended dispose pattern work just fine on multiple dispose invocations.

**Comment by gewarren** [comment]
Thanks Manish. In that case I'm going to close this issue because [we recommend using FxCop analyzers](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2019) over static code analysis.
