### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bradyswenson** [MicrosoftDocs/visualstudio-docs#1576]
Typo: "changed" should be "changes"

https://cl.ly/25fce5023862

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a29f3723-6a51-ae9f-c1a7-07d59b30d0a2
* Version Independent ID: 9cd1552e-1579-7da1-ffc0-e41b51fb3ae1
* Content: [Visual Studio for Mac Tour - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/ide-tour)
* Content Source: [mac/ide-tour.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/ide-tour.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @bradyswenson I've just updated it, should be published soon.
