### ISSUE TITLE
The extension for visual studio community for Mac doesn't list all projects

### ISSUE THREAD

**Issue by apis3445** [MicrosoftDocs/visualstudio-docs#1577]
Hi! I install the extension for get the TFS / VSTS I log to my account but I only see 3 projects of 19 project in Visual Studio Community for Windows I can see all projects, how I can see all projects?

**Comment by asb3993** [comment]
@jmatthiesen can you address this?

**Comment by jmatthiesen** [comment]
Sorry for a large delay here! The Team Foundation Version Control extension for Visual Studio for Mac, which is now no longer supported, would only list TFVC repos and perhaps you had these projects created as Git repos in your account?
