### ISSUE TITLE
Undocumented debugging information options

### ISSUE THREAD

**Issue by hultqvist** [MicrosoftDocs/visualstudio-docs#158]
By default my projects have "debugging information" set to "portable" but it is not documented here.

https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/reference/advanced-build-settings-dialog-box-csharp.md

There is also the option "embedded" which also isn't documented.

**Comment by hultqvist** [comment]
Found this but don't know if it's right

https://stackoverflow.com/a/44309771/33236

**Comment by Mikejo5000** [comment]
Thanks, I'll get some info added. Here is some information on the portable format: https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md

**Comment by kempb** [comment]
FYI, I added info on the new options to the Advanced Build Settings Dialog Box topic. The changes should appear online soon. Thanks for the feedback, @hultqvist!

**Comment by Mikejo5000** [comment]
Fixed, I believe.
