### ISSUE TITLE
Please add information relevant to Azure Web Apps

### ISSUE THREAD

**Issue by gituser227** [MicrosoftDocs/visualstudio-docs#1580]
Please add information that clarifies if/when MSBuild will be added to Azure Web Apps, or if there is something that we must do to be able to install MSBuild 15 in Azure Web Apps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb723883-dd62-0c53-8617-7bc867b9aaf3
* Version Independent ID: de1ff8ce-885c-9df0-077c-48c82f163c83
* Content: [What's New in MSBuild 15 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0?view=vs-2017)
* Content Source: [docs/msbuild/what-s-new-in-msbuild-15-0.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/what-s-new-in-msbuild-15-0.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gituser227** [comment]
Microsoft Azure supports a PaaS model, "Platform as a Service".  In that
model, Azure users do not maintain a traditional IIS server for web
applications, because Microsoft is handling the underlying infrastructure
of the web server itself (which is presumably some form of IIS).  Microsoft
handles the maintenance of the web server itself, and Azure users simply
deploy their applications to an "Azure Web App".   When using continuous
deployment, that means Azure will pull the code from your repo, and then
build/deploy.  In order to do that, Microsoft (not the end user) makes sure
that the "Azure Web App" has anything needed to build the code, for
example, Microsoft has already installed MSBuild.exe (v 14 I believe) and
other related tools that would be needed to build ASP.NET code.

Since Microsoft is handling everything "server side" for "Azure Web App"s,
what is the consequence of someone beginning to use VS 2017 and new
features of C# 7.0 etc. and then trying to deploy that to the Azure
environment?  In a more traditional scenario, someone might just install VS
2017 on their server running IIS.  A Microsoft Azure user is not going to
be able to do that.  Microsoft maintains the server.

I have since learned the hard way, that many updates from VS 2017, and
definitely new language features of C# 7.0 are not compatible "as is" with
Azure, since they seem to depend on a later version of MSBuild than
Microsoft actually provides in the Azure Web App environment.  It would
have been good if the Visual Studio team and the Azure team were in
contact, so when there's an update to Visual Studio that could potentially
be a breaking change for Azure Web Apps, you could warn us in advance, and
also the Azure team could be aware of something like "Hey, we need to make
sure we make updates to Azure to correspond."   It seems the Azure team is
trying to catch up now, and has installed a particular release of MSBuild
15 in the Azure Web App environment, but v 14 is still the default.  At
least that allows for someone to add a few environment variables related to
MSBuild to ensure that the v15 that Microsoft installed would be used for
build processes.  Rather than having to scour the Internet for many other
users and eventually stumble onto a place where members of the Azure team
and the VS team did discuss the issue and their plan, it would have save a
great deal of time and headache if the VS team and the Azure team had been
more proactive about making sure they were aware of the impact of these
changes and notified Visual Studio users that they may run into problems if
deploying to Azure.

david.ebbo AT microsoft could probably explain this to you way better than
I.

Thanks for consideration.

Keep up the great work!

-A-

**Comment by gituser227** [comment]
DevOps is not needed for CI/CD with Azure Web Apps at all.  We've been
doing it for a couple of years without DevOps, and I've seen no official
documentation from Microsoft stating DevOps is required and only DevOps is
supported.  BitBucket and GitHub are also supported.  We got started with
CI/CD on our Azure Web Apps by following Microsoft documentation.  See
https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment
 DevOps is only one of a number of repos supported.   Isn't that why
Microsoft includes MSBuild on the Web Apps hard drives to begin with?

**Comment by rainersigwald** [comment]
@gituser227, are you talking about Azure App Service continuous deployment, as in https://docs.microsoft.com/en-us/azure/app-service/deploy-continuous-deployment#deploy-continuously-from-github? Since that system builds code as part of its deployment, it might be subject to a mismatch in MSBuild/Visual Studio versions, and I don't know the details of their update schedule.
