### ISSUE TITLE
Potentially Another false Positive for CA2000

### ISSUE THREAD

**Issue by insulind** [MicrosoftDocs/visualstudio-docs#1581]
See this Stackoverflow question https://stackoverflow.com/q/52520390/6915929

Essentially it is using 'using statements' within a try catch with a filter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c370a407-b61d-0de6-6ac4-9b0ab49216b9
* Version Independent ID: a96e421e-65d3-07ba-097e-3feff2b3c677
* Content: [CA2000: Dispose objects before losing scope - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2017)
* Content Source: [docs/code-quality/ca2000-dispose-objects-before-losing-scope.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2000-dispose-objects-before-losing-scope.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to #898

**Comment by gewarren** [comment]
@insulind From your SO post it sounds like you encountered this in VS 2015, which means you are using static code analysis. Do you get this same false positive in the [FxCop analyzer](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers) version of this rule? If so, please log an issue at [roslyn-analyzer issues](https://github.com/dotnet/roslyn-analyzers/issues).

**Comment by msebolt** [comment]
Closing the issue due to inactivity.

If there are any concerns, please comment below.
