### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by syendev** [MicrosoftDocs/visualstudio-docs#1582]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Build:Cannot find type definition file for 'node'.	VuejsApp2	tsc	0	
Error		Build:Cannot find type definition file for 'node'.	VuejsApp2	tsc	0	
Error	TS2688	Cannot find type definition file for 'node'.	C:\Users\...\VuejsApp2\VuejsApp2 (tsconfig or jsconfig project)		1	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59adf9c7-5894-84ba-32ee-df842aa4658d
* Version Independent ID: 50683e7c-4b31-1773-f20e-00732a0ffbcc
* Content: [Quickstart: Use Visual Studio to create your first Vue.js app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/quickstart-vuejs-with-nodejs?view=vs-2017)
* Content Source: [docs/javascript/quickstart-vuejs-with-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/quickstart-vuejs-with-nodejs.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by syendev** [comment]
after adding types for node you get the following errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2688	Cannot find type definition file for 'node'.	C:\Users\elema\dev\source\repos\VuejsApp6\VuejsApp6 (tsconfig or jsconfig project)		1	Active
Error		Build:Cannot find name 'Set'.	VuejsApp6	C:\Users\...\VuejsApp6\node_modules\@types\node\index.d.ts	815	
Error		Build:Cannot find name 'Set'.	VuejsApp6	C:\Users\...\VuejsApp6\node_modules\@types\node\index.d.ts	815

**Comment by Mikejo5000** [comment]
@syendev I will ask about this.

**Comment by armanio123** [comment]
To manually fix this, you just need to change on the `tsconfig.json` :
```js
"types": [
    "node"
],
```
for:
```js
"types": [
    "webpack-env"
],
```
Note that this change will only your project if you have installed Vue.js 3.0.3 or later.

This issue will be fixed for future releases by this nodejstools pull request: https://github.com/Microsoft/nodejstools/pull/2085 .

**Comment by gewarren** [comment]
@Mikejo5000 Is there a doc update needed here, or can we close this?

**Comment by Mikejo5000** [comment]
Looks like the product fix is in.
