### ISSUE TITLE
C6326: undesired warning when the comparison depends on a template parameter

### ISSUE THREAD

**Issue by MaartenHilferink** [MicrosoftDocs/visualstudio-docs#1583]
Consider the following example, taken from boost\random\linear_conguential.hpp:

template&lt;class IntType, IntType a, IntType c, IntType m&gt;
class linear_congruential_engine
{
   static const IntType modulus = m;
    /**
     * If c mod m is zero and x0 mod m is zero, changes the current value of
     * the generator to 1. Otherwise, changes it to x0 mod m. If c is zero,
     * distinct seeds in the range [1,m) will leave the generator in distinct
     * states. If c is not zero, the range is [0,m).
     */
    void seed(const IntType&  x0_)
    {
        if(modulus == 0) {
            _x = x0;
        } else {
            _x = x0 % modulus;
        }
   }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 735f8012-a55e-0ec9-ccd8-c1393499d8aa
* Version Independent ID: caa4822b-a7cd-e807-94c1-b9c9b097696f
* Content: [C6326 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c6326?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C6326);k(vs.output)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/code-quality/c6326.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c6326.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@MaartenHilferink  Thanks for the feedback! Since PREfast is a local code analysis tool, it has a very limited capability to trace assignments outside of the current function under analysis. In this case we cannot know that the variable depends on the template parameter. This warning should not reproduce if the actual parameter is used in place of the const variable: if(m == 0) {  …
