### ISSUE TITLE
Missing change log for VS Tools for Unity 3.8.0.7

### ISSUE THREAD

**Issue by mabakay** [MicrosoftDocs/visualstudio-docs#1584]

**Comment by gewarren** [comment]
@conceptdev fyi

**Comment by conceptdev** [comment]
I've let the team know, thanks.

**Comment by sailro** [comment]
See https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/3004

cc @jbevain 

Thanks.

**Comment by mabakay** [comment]
> See MicrosoftDocs/visualstudio-docs-pr#3004

404

**Comment by sailro** [comment]
@mabakay yes sorry the above URL requires special access rights.

To summarize here, 3.8.0.7 is a bugfix release, we found and fixed a deadlock in the library used to communicate with Unity’s debugger engine, making Visual Studio or Unity freeze, especially when hitting ‘Attach to Unity’ or restarting the game.

Thank you.

**Comment by conceptdev** [comment]
The updated build log has been approved and publishing is in progress.

Thanks for your feedback @mabakay.

#please-close
