### ISSUE TITLE
"Debug with Native Only" from command line?

### ISSUE THREAD

**Issue by dfunny990** [MicrosoftDocs/visualstudio-docs#1585]
I'm looking at processing multiple dmp files via script. I can open the relavent solution, and add the dmp file, but I can't seem to find any information on performing that operation from the command line. I've looked at the devenv Commands information page, and while I appreciate the "start" command, that's not what I'm looking for. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb93b89e-4490-e703-94f3-324b9f7254ff
* Version Independent ID: 49c0d3a0-a0e5-5b16-eada-5d6aa5285ad9
* Content: [Use Dump Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2017)
* Content Source: [docs/debugger/using-dump-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-dump-files.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@dfunny990 I'll check. I'm not sure whether this is supported.

**Comment by gregg-miskelly** [comment]
You could do this with a little VS extension, but I don't think there is a way to do this via a command line arguments. To do this as a VS extension - don't use the dump summery page at all, but instead call IVSDebugger4.LaunchDebugTargets, specifying the full path to the .dmp file as 'bstrExe' field of [VsDebugTargetInfo4](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.vsdebugtargetinfo4?view=visualstudiosdk-2017). I believe the only other argument you will need to fill out is guidLaunchDebugEngine. Set that field to VSConstants.DebugEnginesGuids.ManagedOnlyEngineV4_guid. if you want to managed desktop debug the dump.

**Comment by gewarren** [comment]
@Mikejo5000 Does this need a doc update, or should it be closes as-is?
