### ISSUE TITLE
Sample GlobalSuppression Entry

### ISSUE THREAD

**Issue by sarajang** [MicrosoftDocs/visualstudio-docs#1587]
Would it be possible to provide a sample entry for GlobalSuppressions.cs to suppress this at the namespace level?

**Comment by gewarren** [comment]
@sarajang Does this section give you the info you need? https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#global-level-suppressions

`[module: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "MyNamespace")]`

Note that when you suppress a warning with `namespace` scope, it suppresses the warning against the namespace itself. It does not suppress the warning against types within the namespace. There's a [new scope in VS 2019](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#suppressmessage-attribute) `namespaceanddescendants` that might suit your needs better.

**Comment by sarajang** [comment]
@gewarren  I think so. Thanks.
