### ISSUE TITLE
YouTube version

### ISSUE THREAD

**Issue by krchome** [MicrosoftDocs/visualstudio-docs#1588]
[Enter feedback here]
The Youtube version of this tutorial is here:
https://youtu.be/f17mj6EFLbw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94de0eb4-b24d-7573-dc5d-a62c334cb136
* Version Independent ID: fe60f231-3de5-0c95-6e4c-63db4613dd91
* Content: [Analyze CPU usage data (managed code) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/quickstart-cpu-usage-managed?view=vs-2017)
* Content Source: [docs/profiling/quickstart-cpu-usage-managed.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/quickstart-cpu-usage-managed.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Not a doc issue
