### ISSUE TITLE
Feedback and suggestion for Alternative Approaches

### ISSUE THREAD

**Issue by LeslieGerman** [MicrosoftDocs/visualstudio-docs#1589]
Hi,
I liked your article!
Especially the evaluation of pybind11 vs Standard API was useful.

I suggest to add one more player to the "Alternative approaches" section: [cppyy](https://cppyy.readthedocs.io/en/latest/).
It's approach is similar to CFFI, but with C++.

(Note that actually it has some issues with VS 2017 ([see here](https://bitbucket.org/wlav/cppyy/issues/43/cannot-pip-install-on-windows)), but I think this will be solved soon).
Regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Working with C++ and Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2017#call-the-dll-from-python)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for the info! I'm adding an entry to that page (see PR above, though it's probably in our private repo so I'm not sure you can see it). I'm also happy to hear that you enjoyed the article as a whole...I just recently added the pybind11 material and I'm glad it's proven useful. (And if you have a moment to click "Yes" on the "Is this page helpful?" control on the article, that helps our data. :)

**Comment by LeslieGerman** [comment]
> And if you have a moment to click "Yes" on the "Is this page helpful?" control on the article, that helps our data.

Done :)
Cheers.
