### ISSUE TITLE
About the renewal

### ISSUE THREAD

**Issue by toxarisswe** [MicrosoftDocs/visualstudio-docs#1590]
Please remove this deal-breaker as soon as posible "If you purchase a multi-year subscription through volume licensing, the EMS benefit is currently only available in the first year". 
To me this is just weird compaired to the price you pay for VS. You should also be able to renew the subscription in the same tennant otherwise its pointless, you dont want to tear down your lab environment once a year.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b2872e-438a-b86e-9ff5-6dc0021f3fe8
* Version Independent ID: 8b9e935e-07ad-4992-edb9-e8361d867617
* Content: [EMS Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ems)
* Content Source: [subscriptions/vs-ems.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-ems.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by toxarisswe** [comment]
Ohh, my bad

**Comment by TerryGLee** [comment]
@evanwindom @lankaim @CaityBuschlen FYI.

**Comment by BakxM** [comment]
Curious too if there is any progress in having this issue resolved anytime soon. As toxarisswe pointed out, rebuilding your Testlab is cumbersome. And other VS Ent benefits are renewable.

**Comment by JeremyTBradshaw** [comment]
@nschonni @toxarisswe Just wanted to point out that when you select "Product Feedback", you are brought to https://developercommunity.visualstudio.com where you can give product feedback or suggest a feature, BUT, nothing related to My.VisualStudio.com subscriptions and/or their benefits.  Only products - Visual Studio (Windows/Mac), .NET, C++, Azure DevOps, and TFS.

If would be giving the same product feedback - that is, that the benefit should a) include more than a single EMS E5 license (really, just 1?), and b) it should be renewable in the same tenant.

**Comment by evanwindom** [comment]
@JeremyTBradshaw - Thanks for the feedback and the additional context.  I will bring your feedback to the attention of the EMS team, as they determine the specifics of any offers featuring EMS.

**Comment by toxarisswe** [comment]
Looking forward to re-enable EMS E5 licenses in my lab, thx.
