### ISSUE TITLE
Need a comprehensive and official reference

### ISSUE THREAD

**Issue by EdSF** [MicrosoftDocs/visualstudio-docs#1601]
There seems to be a lack of "one reference" for these `csproj` elements. While one can successfully go to the interwebs and see some bits and pieces, it's been rough to find an actual official reference for this. 

For example in the above, one would think that the only child element of `ItemGroup` is `Item`, yet somehow  `None`, `Content` will work just fine (.net core), but it's not mentioned here. So either I'm just "getting away with it" or the documentation above needs to be revisited(?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7148a9c-77db-81c7-0362-f2ce6b0c6274
* Version Independent ID: ccef6249-9a81-9376-a9c8-fe884d0b094f
* Content: [ItemGroup Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/itemgroup-element-msbuild?view=vs-2017)
* Content Source: [docs/msbuild/itemgroup-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/itemgroup-element-msbuild.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@EdSF The common project <item> elements are doc'ed here: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2017, including the None and Content items that you mentioned. I can add a few links to make this topic more discoverable.
There are plans to create a new doc for .NET Core specific .csproj elements
dotnet/docs#2642, but I'm not sure when that will be published. Also, for .NET Core, there are a few topic specific to .NET Core in the .NET docs, such as this one, https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

**Comment by Mikejo5000** [comment]
I will plan to close this one in favor of dotnet/docs/#2642, once I add some additional links.
