### ISSUE TITLE
Opsgility Benefit Update

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#1604]
Hello team,

As of September 30th, 2018, the Opsgility benefit has been rebranded as "Skill Me Up - Powered by Opsgility". May I request your contact information to provide any documentation you may need to perform this update on this article. This is customer-facing data so we need to prioritize it.

Best regards!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d1f1153-9a32-1d43-b029-a67a94d455ca
* Version Independent ID: 29f31674-aebf-7f87-4d0b-8e781c955881
* Content: [The Opsgility Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-opsgility)
* Content Source: [subscriptions/vs-opsgility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-opsgility.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by gewarren** [comment]
@Nathan-Tarin Evan's updates are live now at https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-opsgility. Closing this issue but let us know if more changes are needed.

**Comment by Nathan-Tarin** [comment]
Hi Genevieve,

I can see the changes now, thank you very much for your prompt action.

Quick question, is the benefit title on the menu on the left (see below) also going to be changed?

[cid:image001.png@01D45B15.2B7B2AC0]

**Comment by gewarren** [comment]
Yes, we have a PR in place to update the table of contents title too.
