### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by horusofoz** [MicrosoftDocs/visualstudio-docs#1605]
Visual Studio advises that the code provided includes a redundant cast, utilises a deprecated interface and the "this." can be removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f21fd44e-005c-521c-a0ac-e4ab052539d8
* Version Independent ID: 5ac6da5f-3575-dc7c-a40f-187c431cb2b2
* Content: [How to: Programmatically retrieve a folder by name - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-retrieve-a-folder-by-name?view=vs-2017)
* Content Source: [docs/vsto/how-to-programmatically-retrieve-a-folder-by-name.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-retrieve-a-folder-by-name.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by supriyanta** [comment]
I want to work on this issue, please help, beginner here.

**Comment by TerryGLee** [comment]
@horusofoz Thanks for letting us know your findings. We are aware that the VSTO documentation is outdated; it's in our backlog queue to update. We'll keep this on file so that we can make sure to address the issue that you've pointed out.

**Comment by John-Hart** [comment]
#please-close  this is fixed
