### ISSUE TITLE
How to set BeforBuild to run when all projects are up-to-date.

### ISSUE THREAD

**Issue by JethroCZ** [MicrosoftDocs/visualstudio-docs#1606]
I have a question.
I have some files, and I want to run scrip which will copy those files into output directory of my Project. I have put that script into BeforeBuild event in project properties. (Adding those files into project as reference isnt an option, for first, there are plenty of them, and for the second, there are new files every now and then)
It works fine, when there are changes on this project, or when I use the Rebuild option.
However when I use the Build option, and there are no changes, VS only say that project is up-to-date, and doesnt run my script.
I have tried different settups with Targets, but it seems to work only when project is changed/or run Rebuild.
Is there a way to set script to start every time, even when the project is Up-to-date?
Thaks in advance, Aleš.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868d865b-89d9-ec87-d569-862d168dc6ca
* Version Independent ID: a95f34e2-8f4b-4a4b-cb7e-075e4ceebd69
* Content: [How to: Extend the Visual Studio Build Process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2017)
* Content Source: [docs/msbuild/how-to-extend-the-visual-studio-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-extend-the-visual-studio-build-process.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@JethroCZ Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Science-and-Motion-Sports** [comment]
@JethroCZ I had the same issue. I noticed that everything was fine when I ran msbuild.exe from the command line. The reason for that is that Visual Studio contains its own (faulty) logic to determine if anything changed and if it thinks nothing changed then Visual Studio does not even run msbuild.exe. The solution is to disable this logic and always run msbuild.
To do that, add the following to your project file:
```
  <PropertyGroup>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>
```
This property is documented here: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019

**Comment by JethroCZ** [comment]
@Science-and-Motion-Sports I have tried that. And it was not the solution that I was looking for. This forces "rebuild" every time. Since that project was not that smal, rebuild took several minutes. 
However we were forced to refactor our project and implement everything inside. Creating lower number of bigger projects in the solution solved this problem. Thanks anyway.
