### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/visualstudio-docs#1607]
@asierdanjou commented on [Wed Oct 03 2018](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/issues/3)

Tras seguir los pasos de la primera parte y copiar el código, tengo el siguiente error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0656	Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'	WeatherApp	C:\Pro\WeatherApp\WeatherApp\WeatherApp\Core.cs	16	Active

Alguna idea para arreglarlo ?
Gracias.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 3b25d4cd-0c3f-e9a6-6256-ea54d0972d4b
* Version Independent ID: babd49b7-8e18-13dc-99f2-6783495cb0dc
* Content: [Información sobre los conceptos básicos de la compilación de aplicaciones con Xamarin.Forms en Visual Studio - Visual Studio](https://docs.microsoft.com/es-es/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio?view=vs-2017)
* Content Source: [docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/blob/live/docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by LisandroSu** [comment]
Hi team,

The user is having problems with the code in the document. After following all the steps and pasting the code they get this error:

_Severity Code Description Project File Line Suppression State
Error CS0656 Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create' WeatherApp C:\Pro\WeatherApp\WeatherApp\WeatherApp\Core.cs 16 Active_

Thanks!

**Comment by conceptdev** [comment]
I found an answer in the [forums](https://social.msdn.microsoft.com/Forums/vstudio/en-US/2b855369-a721-4010-9e33-72d699960994/how-to-fix-missing-compiler-member-error-microsoftcsharpruntimebindercsharpargumentinfocreate?forum=visualstudiogeneral)

**Right-click Project -> add reference -> Framework ->Microsoft.CSharp**

I hope that helps.
