### ISSUE TITLE
visual studio 2013 & 2015 & 2017 cannot configure HTML editor Formating

### ISSUE THREAD

**Issue by zengyunchun** [MicrosoftDocs/visualstudio-docs#161]
## Visual Studio text editor options as below
![](https://ooo.0o0.ooo/2017/06/20/594895754838b.png)

1.  As the picture, I can find Html(Web Forms) Formatting to change configuration, but when I use asp.net MVC project , CSHTML extension file will auto use HTML configuration that cannot allow me to configure the Formatting
2. Could you give me an advice for how to configure CSHTML formatting so that I can disable auto transferring the tag to lowercase when formatting the code.

Thanks a lot, Microsoft Engineers !!!!!!

**Comment by Rick-Anderson** [comment]
@zengyunchun  That setting is for Web Forms, not for Razor. Why would you want **As entered**?

![image](https://user-images.githubusercontent.com/3605364/27399683-78485222-5672-11e7-971f-389606ebbabe.png)

cc @MadsTorgersen

**Comment by zengyunchun** [comment]
@Rick-Anderson Because our team will custom some element like `<GoodBoy></GoodBoy>` that do not want to be formatted to `<goodboy><goodboy>`, as my thinking , Web Forms HTML can configure the formatting of tag and attribute, why Razor not?
Thanks for your answer, do you have any workaround configuration or solution?

**Comment by Rick-Anderson** [comment]
@zengyunchun  I'm afraid you out of luck. Most people like that behavior.

**Comment by zengyunchun** [comment]
@Rick-Anderson Yes. I know most people like that but is there any way to configure it ?

**Comment by Rick-Anderson** [comment]
@zengyunchun  I don't think so but @madskristensen will know.

**Comment by madskristensen** [comment]
I can not reproduce the issue. The formatter doesn't change the casing of HTML tags. Are you by chance using ReSharper?

**Comment by Rick-Anderson** [comment]
@madskristensen  I can repo it. Create a ASP.NET Core MVC app using the templates. When I enter `<P>` it changes it to `<p></p>`

**Comment by Rick-Anderson** [comment]
>  but when I use asp.net MVC project , CSHTML extension file will auto use HTML configuration that cannot allow me to configure the Formatting

**Comment by madskristensen** [comment]
@Rick-Anderson that is not the formatter changing it. It is because `<p>` is in the Intellisense list and you commit from it when writing `<P` and typing the end `>`. That commits from the selected Intellisense item which is the lower case `<p>`.

**Comment by Rick-Anderson** [comment]
@madskristensen  You're right
`<GoodBoy></GoodBoy>` is not changed when I format it.

**Comment by zengyunchun** [comment]
@Rick-Anderson @madskristensen

**Comment by zengyunchun** [comment]
@Rick-Anderson @madskristensen 
Dear both, how about your discussion of this issue?

**Comment by Rick-Anderson** [comment]
@zengyunchun  I can't repro your problem. 

`<GoodBoy></GoodBoy>` is not changed when I format it.
