### ISSUE TITLE
The Add Bookmark Control dialog box appears.

### ISSUE THREAD

**Issue by davepile** [MicrosoftDocs/visualstudio-docs#1610]
The Add Bookmark Control dialog box appears.

No it doesnt

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89eb61fa-81bf-878b-148e-52df4634d8d9
* Version Independent ID: 5494bd57-78e4-ceff-f990-74e9412bd7be
* Content: [Walkthrough: Insert text into a document from an actions pane - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-inserting-text-into-a-document-from-an-actions-pane?view=vs-2017)
* Content Source: [docs/vsto/walkthrough-inserting-text-into-a-document-from-an-actions-pane.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-inserting-text-into-a-document-from-an-actions-pane.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@davepile Thanks for your feedback. We are aware that the documentation is outdated; it's in our backlog queue to update. Meanwhile, if you require immediate assistance, please consider perusing the [StackOverflow](https://stackoverflow.com/search?q=VSTO+action+pane+) website (and note that the link I've included goes directly to a collection of questions and answers that are tagged with "action pane" and "VSTO").

**Comment by John-Hart** [comment]
The document is correct. 
There should be a "Add Bookmark Control" dialog that states:  "Make a selection or place the insertion point where you want to add a bookmark control, and click OK."

**Comment by John-Hart** [comment]
#please-close
