### ISSUE TITLE
Solution for a single project

### ISSUE THREAD

**Issue by cja-github** [MicrosoftDocs/visualstudio-docs#1617]
Article does not explain whether I should have a solution if it will contain only one project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2017)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@cja-github Thanks, that is good feedback to add to the topic. You do need a solution, even just for one project.

**Comment by cja-github** [comment]
Hi,

I'm able to compile a project without a solution.
