### ISSUE TITLE
 .NET Standard with DialogDebuggerVisualizer

### ISSUE THREAD

**Issue by VaclavElias** [MicrosoftDocs/visualstudio-docs#1620]
I am not sure the instructions here are correct for Visual Studio 2017 and .NET Standard library (Targeting .NETStandard 2.0)?

"3. In Solution Explorer, right-click References and choose Add Reference on the shortcut menu." 
- there are not References, there are Dependencies

"4. In the Add Reference dialog box, on the .NET tab, choose Microsoft.VisualStudio.DebuggerVisualizers.DLL."
- there is not such a tab, probably you meant Assemblies and you cannot choose DebuggerVisualizers, at least in my case it says "No Framework assemblies were found on the machine."

I think these instructions are not for .NET Standard library but .NET Framework 4.xx Class Library where you can see all as mentioned in all steps?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5d2403-0edc-8ee9-22f6-6ca370b40346
* Version Independent ID: d34a6007-354e-0bdb-3ad7-9f15a2cb56f2
* Content: [Walkthrough: Writing a Visualizer in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2017)
* Content Source: [docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@VaclavElias Thanks! I'll get that updated.

**Comment by VaclavElias** [comment]
@Mikejo5000 no problem :) 

I was actually trying to do it with .NET Standard class library, somehow was able to add **System.Windows.Forms** and reference directly **Microsoft.VisualStudio.DebuggerVisualizers.dll** and it compiled but when testing it made Visual Studio unresponsive. 

So I reversed back to NET Framework (4.7.1) class library and all works well :)

**Comment by regal60740** [comment]
No .Net tab. I can't add reference to "Microsoft.VisualStudio.DebuggerVisualizers.DLL". Someone needs to update this tutorial.

**Comment by regal60740** [comment]
Microsoft.VisualStudio.DebuggerVisualizers.dll lives in the Common7\IDE\PublicAssemblies subdirectory of Visual Studio's installation directory. You could add it manually from there.

**Comment by Mikejo5000** [comment]
@regal60740 Thanks! Retesting doc and updating.
