### ISSUE TITLE
Mismatch of doc with app

### ISSUE THREAD

**Issue by dreappdev** [MicrosoftDocs/visualstudio-docs#1621]
The content in the Quickstarts and other sections of the VS documentation are way out of sync with the current version of VS (7.6.8 (build 38)) for a Mac. Virtually useless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53c91aa-0a65-d186-77cd-d5c2e018d8d4
* Version Independent ID: 5eec8b47-4f0b-186d-43ec-a403f57d4c3b
* Content: [Tour of the Visual Studio IDE - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-ide-orientation?view=vs-2017)
* Content Source: [docs/ide/quickstart-ide-orientation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-ide-orientation.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@dreappdev Thanks for the feedback. The quickstarts in this section of the docs are not applicable to VS for Mac, which has its own set of documentation at https://docs.microsoft.com/en-us/visualstudio/mac/. We have heard previous feedback that the docs need to more clearly state if they're for Windows or Mac, so this reinforces that feedback.

**Comment by conceptdev** [comment]
As mentioned above, please visit the Visual Studio for Mac docs at
https://docs.microsoft.com/en-us/visualstudio/mac/

Please leave us feedback there if you find issues with the content.
