### ISSUE TITLE
New checkbox not defined in documentation

### ISSUE THREAD

**Issue by MikeFarrington** [MicrosoftDocs/visualstudio-docs#1623]
There is a new checkbox for "Auto-generate binding redirects" that is not described in this documentation.  I'd like an example of why one might choose this option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55a4bbc-1ccd-7091-283b-7b3aa6718605
* Version Independent ID: 931d7ffe-fa6c-44c4-f812-64794b042f8c
* Content: [Build Page, Project Designer (C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/build-page-project-designer-csharp?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(cs.ProjectPropertiesBuild);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.1)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/ide/reference/build-page-project-designer-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/build-page-project-designer-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by MikeFarrington** [comment]
While that topic does go into depth on the given issue, the page I linked to still makes no mention of what this setting does nor what toggling the setting is meant to achieve.  The link you provided could be placed in the document I mentioned after a summarized explanation.

**Comment by gewarren** [comment]
@MikeFarrington Thanks for the feedback. I've labeled this issue as 'doc feedback' which means that the doc needs to be updated, so yes I will add the info you requested.
