### ISSUE TITLE
Update shortcuts from version 15.8

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/visualstudio-docs#1624]
## Summary

The new productivity shortcuts in VS version 15.8 need to be added to these docs:

[Tips for .NET Developers](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-2017-for-dotnet-developers?view=vs-2017)
[Keyboard shortcuts for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/tips-and-tricks-for-visual-studio?view=vs-2017)
[Default Keyboard short cuts in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2017)

The new shortcuts can be found in the [update 15.8 release notes](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#productivity).

@gewarren Do you have a tool that is generating these tables or do we do them by hand?

**Comment by gewarren** [comment]
@kendrahavens As far as I know they are generated automatically. Your link to the release notes isn't correct - can you fix?

**Comment by kendrahavens** [comment]
## Complete list of Productivity short cuts to be added:

### Updates to Tips for .NET Developers:
- [ ] New keyboard bindings for ReSharper and VS Code
- [ ] Multi-caret
 - You can now create insertion points and selections at multiple, arbitrary locations in a file with multiple caret support. This allows you to add, edit, or delete text in multiple places simultaneously. 
Insert carets with Ctrl + Alt + LeftMouseClick.
 - Add a selection and caret at next location that matches current selection with Shift + Alt + Ins.
 - All multi-caret options: Edit > Multiple Carets


### Keyboard shortcuts for Visual Studio and default Keyboard short cuts:
- [ ] Code cleanup with Format Document (Ctrl + K, D or Ctrl + E, D) for C# development.
- [ ] Go to All window: Go to Recent files (Ctrl + T, R)
- [ ] Go to Enclosing Block (Ctrl + Alt + UpArrow) allows you to quickly navigate up to the beginning of the enclosing code block.
 - [ ] Go to Next/Previous Issue (Alt + PgUp/PgDn) allows you to skip to the next/previous issue (error, squiggle, lightbulb).
- [ ] Access a contextual navigation menu with Alt + `.
- [ ] Multi-caret
 - You can now create insertion points and selections at multiple, arbitrary locations in a file with multiple caret support. This allows you to add, edit, or delete text in multiple places simultaneously. 
Insert carets with Ctrl + Alt + LeftMouseClick.
 - Add a selection and caret at next location that matches current selection with Shift + Alt + Ins.
 - All multi-caret options: Edit > Multiple Carets

**Comment by kendrahavens** [comment]
## Complete list of Productivity short cuts to be added:

### Updates to Tips for .NET Developers:
- [ ] New keyboard bindings for ReSharper and VS Code
- [ ] Multi-caret
 - You can now create insertion points and selections at multiple, arbitrary locations in a file with multiple caret support. This allows you to add, edit, or delete text in multiple places simultaneously. 
Insert carets with Ctrl + Alt + LeftMouseClick.
 - Add a selection and caret at next location that matches current selection with Shift + Alt + Ins.
 - All multi-caret options: Edit > Multiple Carets


### Keyboard shortcuts for Visual Studio and default Keyboard short cuts:
- [ ] Code cleanup with Format Document (Ctrl + K, D or Ctrl + E, D) for C# development.
- [ ] Go to All window: Go to Recent files (Ctrl + T, R)
- [ ] Go to Enclosing Block (Ctrl + Alt + UpArrow) allows you to quickly navigate up to the beginning of the enclosing code block.
 - [ ] Go to Next/Previous Issue (Alt + PgUp/PgDn) allows you to skip to the next/previous issue (error, squiggle, lightbulb).
- [ ] Access a contextual navigation menu with Alt + `.
- [ ] Multi-caret
 - You can now create insertion points and selections at multiple, arbitrary locations in a file with multiple caret support. This allows you to add, edit, or delete text in multiple places simultaneously. 
Insert carets with Ctrl + Alt + LeftMouseClick.
 - Add a selection and caret at next location that matches current selection with Shift + Alt + Ins.
 - All multi-caret options: Edit > Multiple Carets

**Comment by kendrahavens** [comment]
We need to update the others as well. I can open a separate issue if needed and include the 2019 Preview 1 and 2 updates that we will need.

**Comment by gewarren** [comment]
@kendrahavens That would be great, thank you! And then please close this issue once that's done.

**Comment by kendrahavens** [comment]
Remaining work captured in https://github.com/MicrosoftDocs/visualstudio-docs/issues/2432
