### ISSUE TITLE
How do you use vssetup.powershell

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/visualstudio-docs#1629]
It would be great if there was an example of how to use vssetup.powershell to find MSBuild

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb723883-dd62-0c53-8617-7bc867b9aaf3
* Version Independent ID: de1ff8ce-885c-9df0-077c-48c82f163c83
* Content: [What's New in MSBuild 15 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0?view=vs-2017)
* Content Source: [docs/msbuild/what-s-new-in-msbuild-15-0.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/what-s-new-in-msbuild-15-0.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
This is a great idea for a topic, but the work is currently out of scope for MSBuild docs
