### ISSUE TITLE
Residential Addressing

### ISSUE THREAD

**Issue by eengurra** [MicrosoftDocs/visualstudio-docs#1632]
Must be native of Arizona

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b949fd1-8b49-95e0-5543-d87d842dd3c7
* Version Independent ID: b2de8822-aa20-31b2-a7b3-3f4f285b9b42
* Content: [Performance Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/performance-explorer?view=vs-2017)
* Content Source: [docs/profiling/performance-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/performance-explorer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Off topic
