### ISSUE TITLE
Need to save a native document in different Location

### ISSUE THREAD

**Issue by hariharan605** [MicrosoftDocs/visualstudio-docs#1633]
How to programatically change the document location while the doucment is still open ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94f8bfde-ca47-8818-ddee-de08b629f227
* Version Independent ID: c905e565-ccfb-5a44-2aff-85eaa7db3a7e
* Content: [How to: Programmatically save documents - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-save-documents?view=vs-2017)
* Content Source: [docs/vsto/how-to-programmatically-save-documents.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-save-documents.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@hariharan605 Thanks for your feedback. It looks like the document that you've referenced doesn't provide the information you seek. Our VSTO documentation is on our backlog to update, so we won't be adding such information right away. Meanwhile, for  immediate assistance, please consider consulting the [StackOverflow](https://stackoverflow.com/search?tab=newest&q=vsto%20save%20document%20location) website (and note that the link I've included goes directly to a collection of questions and answers that are tagged with "document location" and "VSTO").

**Comment by John-Hart** [comment]
@hariharan605 this document mentions using SaveAs (https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-save-documents?view=vs-2017#save-a-document-with-a-new-name) did you try that?

**Comment by John-Hart** [comment]
I believe the document is correct. 
#please-close
