### ISSUE TITLE
Please correct MVP in your documentation

### ISSUE THREAD

**Issue by ThomasPoett** [MicrosoftDocs/visualstudio-docs#1634]
*Includes Not for Resale (NFR), Microsoft Valued Partner (MVP), Region Director (RD), Visual Studio Industry Partner (VSIP)
Please correct MVP as: Microsoft Valuable Professional - https://mvp.microsoft.com/
Tnx ;)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73356ab4-87d3-09fb-557f-4533fc133156
* Version Independent ID: ce5ed4b4-1406-9126-832a-ddcdc5cf25bc
* Content: [Microsoft Azure Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure)
* Content Source: [subscriptions/vs-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
I checked some other articles and the same reference is incorrect in them, too, so I’ll do a sweep.  Thanks, Thomas, for pointing that out.

**Comment by ThomasPoett** [comment]
HI all,

You are all welcome and thanks in advanced for the modifications.


with best regards
Thomas Poett

Thomas Poett
Head of Customer Success
(Microsoft MVP & P-Seller SSP, Microsoft Redmond Teams Elite Team Founding Member)

Phone:    +49 351 501945-284
E-Mail:    thomas.poett@outlook.com<mailto:thomas.poett@outlook.com>
Teams/ SfB:  thomas.poett@uclabs.blog<mailto:thomas.poett@uclabs.blog>
Web:      www.uclabs.blog<http://www.uclabs.blog/>


[MVP+P-Seller]

**Comment by evanwindom** [comment]
The PR has been submitted to correct this reference in all of our benefits articles.

**Comment by TerryGLee** [comment]
Thanks @evanwindom
