### ISSUE TITLE
Path must start lowercase

### ISSUE THREAD

**Issue by jflepp** [MicrosoftDocs/visualstudio-docs#1635]
The shown runsettings are incorrect, the `path` attribute of the `Directory` element must be lowercase in order to work.

~~~~
&lt;AssemblyResolution&gt;
      &lt;Directory Path="D:\myfolder\bin\" includeSubDirectories="false"/&gt;
    &lt;/AssemblyResolution&gt;
~~~~

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This has been fixed.
