### ISSUE TITLE
Build-time check

### ISSUE THREAD

**Issue by sstcvetkov** [MicrosoftDocs/visualstudio-docs#1654]
How can I check the rules before build on my CI pipeline?
I heard that there is no one ready-to-use lib, so I want to find out how I can develop it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to #2172.

**Comment by gewarren** [comment]
@sstcvetkov Please see [this comment](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2172#issuecomment-452465312). Does that answer your question?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
