### ISSUE TITLE
 Custom uppercase attribute but intellisense lowercase in cshtml file

### ISSUE THREAD

**Issue by zengyunchun** [MicrosoftDocs/visualstudio-docs#166]
1. I find it's useful intellisense in cshtml file that customing indivadual element and attribute in html.xsd file, following is the html.xsd path and defination of intellisense: 
    ![html.xsd](https://ooo.0o0.ooo/2017/06/22/594b8eb3e6426.png)

    ![Imagebutton Intellisense](https://ooo.0o0.ooo/2017/06/22/594b9179300fc.png)

2. Our team want uppercase style of element and attribute, as you can see in picture, the `ImageButton` uppercase element intellisense in cshtml is perfect, but for the `Src` uppercase attribute will auto transfer to `src` lowercase style, that bothers me a long time and cannot find a good solution

    ![ImageButton](https://ooo.0o0.ooo/2017/06/22/594b9077f0682.png)
    ![src](https://ooo.0o0.ooo/2017/06/22/594b91420829c.png)

3. Could you give me some advices for above mentioned, thanks you a lot!!!

**Comment by ghogen** [comment]
This appears to be a request for a product change.

**Comment by ToddGrun** [comment]
Hi zengyunchun,
  Can you try putting vs:isxmlschema="true" at the top of your augmented html.xsd (near where the vs:ishtmlschema="true" attribute is)? This isn't a fully tested scenario, but this might give you your desired behavior.

Thanks!
-- Todd

**Comment by gewarren** [comment]
@zengyunchun can you try out the solution above and close the issue if it fixes your problem?

**Comment by gewarren** [comment]
@zengyunchun please reopen the issue if that doesn't solve your problem.

**Comment by zengyunchun** [comment]
@ToddGrun , reply late I'm sorry, just now I try the solution, it's pretty good and wonderful, thank you a lot!!!
by the way, thank you @gewarren reminding me, you are so beautiful!!!!

**Comment by gewarren** [comment]
@zengyunchun I'm glad this fixed your problem, and thank you!
