### ISSUE TITLE
AKS publishing tools fails on VS 2017 Enterprise 15.6.5

### ISSUE THREAD

**Issue by rahulvmarathe** [MicrosoftDocs/visualstudio-docs#1664]
AKS publishing tool installation fails with message This extension is not installable on any currently installed products. I am running VS 2017 Enterprise 15.6.5. The installation log has following message

- 	Supported Products : 
Microsoft.VisualStudio.Community
: [15.0.27701.1,16.0)

**Comment by gewarren** [comment]
@lisaguthrie Have you seen this issue before? Any suggestions for Rahul?

**Comment by kkgoli** [comment]
I am experiencing same issue. Not seen any response to this thread.

**Comment by WilliamAntonRohm** [comment]
@rahulvmarathe -- Rahul, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

-Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

 

Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 

 

Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
