### ISSUE TITLE
Updates please??

### ISSUE THREAD

**Issue by BrianWKing** [MicrosoftDocs/visualstudio-docs#1665]
Can you please update this doc with the latest shortcuts?  Its handy to have them all in one spot and on the article that comes up at the top of search results, as this one does.  There are new productivity shortcuts, such as Ctrl + Alt + Click, for multi-caret support, Ctrl + D for line duplication.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 695b44df-48a8-2b96-847d-651649e1d91c
* Version Independent ID: 8d13e517-75cd-abdd-e770-4a8241f14451
* Content: [Visual Studio keyboard shortcuts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/tips-and-tricks-for-visual-studio?view=vs-2017)
* Content Source: [docs/ide/tips-and-tricks-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/tips-and-tricks-for-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by BrianWKing** [comment]
I see Ctrl+ D is in there.

**Comment by gewarren** [comment]
Thanks Brian. This is something we're actively working on. FYI @abuchholtzau

**Comment by kendrahavens** [comment]
Added with https://github.com/MicrosoftDocs/visualstudio-docs/commit/198643e35cb5c6fbf9c3ffc929580899682c9a77#diff-cbb827733ff7e0e501a3ed9d7d1519ec

([Private PR](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/3213) for internal reference)

I think we can close this.

**Comment by gewarren** [comment]
Thanks Kendra. Closing.
