### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by jaydgus** [MicrosoftDocs/visualstudio-docs#1666]
A link to a download of MSBuild would be great

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 911666fa-55ac-cbc1-ce79-66c058859ad9
* Version Independent ID: 571eec5d-8fb9-2401-fc4c-8a7896723eb7
* Content: [MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2017)
* Content Source: [docs/msbuild/msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by crick3t** [comment]
Agreed! There is so much information, but how can I get the latest version???

**Comment by Mikejo5000** [comment]
For VS 2017, you need Build Tools for Visual Studio 2017
https://visualstudio.microsoft.com/downloads/?q=build+tools

**Comment by usernamedd** [comment]
why is it closed , the problem is still there , i can not download the msbuild alone without vs.
