### ISSUE TITLE
If the developer community doesn't answer within two days...

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1669]
I read this as... 

If problems posted to https://developercommunity.visualstudio.com do not receive a non-MSFT response within two days, MSFT will respond.

... is this a correct understanding?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8c9862f-0b51-5291-2379-6f5bdc192508
* Version Independent ID: d11ddf5e-640f-ff45-a158-53a0aca61c00
* Content: [Technical Support Benefits in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/technical-support)
* Content Source: [subscriptions/technical-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/technical-support.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by TerryGLee** [comment]
@StingyJack Thanks for your inquiry. @CaityBuschlen @lankaim - FYI.

**Comment by evanwindom** [comment]
@StingyJack Yes, that's correct.  If the community doesn't respond within two days, Microsoft will respond. Please note that in this context, a response may not be the same as an answer, since there may be a need for further information, investigation, etc.  Thanks!

**Comment by StingyJack** [comment]
@evanwindom - I understand that a response doesnt mean an answer, and wouldn't ask for something unreasonable.  Who (and how) should be contacted when that two (or 10, or 50, or 500) days comes and goes and I dont have meaningful response? 

The current strategy of creating another issue or post does not seem very efficient for either party.

**Comment by evanwindom** [comment]
@StingyJack My apologies.  I misread your original question.  You're asking about the https://developercommunity.visualstudio.com forums, which are not part of the forums covered under the Visual Studio subscriptions.  The forums provided through the subscriptions are listed in the document, and are hosted on https://social.msdn.microsoft.com/Forums/home.

**Comment by seaniyer** [comment]
@StingyJack  - 
@TerryGLee looped me to help with devcomm related questions.  Please let me know any specific issues on devcomm that need better response.  I'll bring it to the attention of the right team so they can get back on devcomm.

**Comment by StingyJack** [comment]
Hi @seaniyer  - you are free to look up either account ([primary](https://developercommunity.visualstudio.com/users/3413/7c42cb1e-b33d-4935-b113-190f1a64ddf5.html) , [secondary](https://developercommunity.visualstudio.com/users/7487/102e2eab-bc62-695d-8578-76020f847485.html)) I have issues open with (the listed counts are low, answerhub cant count), I already have discussed ones that were most problematic with Maria G. and some of the feedback team whom I believe have helped as much as is reasonably possible (and then some more on top of that). 

I have a bad habit of starting too many tangents or diversions in a conversation, and started to do that that here. I'll open another issue if i am really curious about the escalation procedure, or how you come to identify items that are past that 2 day mark and what you do with them.

**Comment by seaniyer** [comment]
@StingyJack - Ok, I understand asking for clarity.  Maria, myself and rest of the team will continue to help on that.  Thanks.
