### ISSUE TITLE
What about Visual Studio Community?

### ISSUE THREAD

**Issue by elliptic1** [MicrosoftDocs/visualstudio-docs#1673]
My Help menu for VSC doesn't have the Report a Problem link -- maybe link me to that help page from here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11bc8109-61f8-89c4-88f2-ea99c480eec9
* Version Independent ID: 3fb40299-caeb-f933-c64c-1825cee9f418
* Content: [Report a Problem with Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem)
* Content Source: [mac/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/report-a-problem.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
All recent releases of Visual Studio Community should have the **Help > Report a Problem** menu item. If you do not see it, I would encourage you to update to the latest version via the **Visual Studio > Check for Updates** menu item. This will also ensure you have the most up-to-date release with recent bug fixes.

The **Report a problem** feature is also available on the 'welcome page' when you open Visual Studio for Mac:

<img width="408" alt="report-problem" src="https://user-images.githubusercontent.com/199373/46806476-8b05ed80-cd1c-11e8-9ca5-1d21e0f8e0f4.png">

The link for reviewing existing entries is https://developercommunity.visualstudio.com/ - we'll look at adding this to the page.
