### ISSUE TITLE
"secret" and other features not supported since 4.0+

### ISSUE THREAD

**Issue by asouini** [MicrosoftDocs/visualstudio-docs#1677]
there have been major changes in ptvsd since 4.0 (secret is one of them : https://github.com/Microsoft/ptvsd/issues/254) but this pages doesn't go into that and that can be confusing for people with a newer version of visual studio or those updating to a newer one.

one other point that doesn't seem to work anymore is placing breakpoints from the VS UI, i now need to place `ptvsd.break_into_debugger()` lines everywhere on the code i want VS to break

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 904b359d-de5e-adf4-9966-e1ab5be204be
* Version Independent ID: 564c35dd-ac25-8db4-ea48-e76476c50f89
* Content: [Debugging Python code on remote Linux computers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines?view=vs-2017)
* Content Source: [docs/python/debugging-python-code-on-remote-linux-machines.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/debugging-python-code-on-remote-linux-machines.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@asouini Regarding your issue with breakpoints, can you file that on https://github.com/Microsoft/ptvs/issues? That's much more of a product bug than a doc bug.
