### ISSUE TITLE
Noticed an error

### ISSUE THREAD

**Issue by ZILtoid1991** [MicrosoftDocs/visualstudio-docs#1678]
The code says GetInfo, while it should be GetMachineInfo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 562a3013-ba63-b5b3-4630-d81ea46a23b4
* Version Independent ID: ad6a5543-b7bc-9c81-808f-b3b7f91ca0df
* Content: [IDebugCoreServer2::GetMachineInfo - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/reference/idebugcoreserver2-getmachineinfo?view=vs-2017)
* Content Source: [docs/extensibility/debugger/reference/idebugcoreserver2-getmachineinfo.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/debugger/reference/idebugcoreserver2-getmachineinfo.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by mikkelbu** [comment]
@gewarren It looks like this was corrected by #1681.

**Comment by gewarren** [comment]
@mikkelbu Yes you're right, thanks for pointing this out. Closing now.
