### ISSUE TITLE
Missing `csharp_indent_case_contents_when_block`

### ISSUE THREAD

**Issue by creinke-sandia** [MicrosoftDocs/visualstudio-docs#1680]
[`csharp_indent_case_contents_when_block`](https://github.com/dotnet/roslyn/blob/9a2ab8c91f9146f475414cc50f469aaaf87279b2/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.cs#L298) is not listed but is working in VS2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@creinke-sandia Thanks, we'll add this to our backlog.

**Comment by gewarren** [comment]
@cremor Thanks for pointing this out. Closing this issue in favor of #1070.
