### ISSUE TITLE
Incomplete

### ISSUE THREAD

**Issue by cboozb** [MicrosoftDocs/visualstudio-docs#1682]
If you don't have access to the code, Solution #1 and #2 is out. This is certainly a possibility if the code is in a .NET Framework assembly or a third-party assembly.  So in Solution #3, what if you already have Debugging Option "Enable property evaluation.." UNCHECKED already. Then what do you try.... At least you could mention this possibility .. somebody must know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfd7078-683e-9fd6-247b-e75d4ed16a32
* Version Independent ID: ae3300c4-55a8-59b6-846b-50c48c88dcfe
* Content: [Error: Evaluating the function 'function' timed out and needed to be aborted in an unsafe way - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?view=vs-2017)
* Content Source: [docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by kvigor** [comment]
I cannot perform steps 1 and 2 because I'm using HttpContext.Request.Form.Get("MyProperty") it always times out even with: 
1. Disabling property evaluation and other implicit function calls
2. Use Manage Compatibility Mode

**Comment by Mikejo5000** [comment]
See #831 Please use the Send Feedback link > Report a Problem for this issue. Thx!
