### ISSUE TITLE
Searching for a more efficient way to copy Debug Folder

### ISSUE THREAD

**Issue by lonelam** [MicrosoftDocs/visualstudio-docs#1683]
I'm currently running a script to copy the whole folder to my remote computer on every build, it takes about five minutes and waste a lot of time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2fd746-82f7-1bac-9932-27c14cdfe0ca
* Version Independent ID: 46b43a94-b750-2073-5e28-82183af092a9
* Content: [Remote Debug a C# or VB Project in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp?view=vs-2017)
* Content Source: [docs/debugger/remote-debugging-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@lonelam What kind of app?

**Comment by TerryGLee** [comment]
@lonelam We haven't heard back, so we're closing this issue. We're sorry to hear though that you experienced the issue that you described. You might have great feedback on how we might improve our product. To that end, please consider using the “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.
