### ISSUE TITLE
.runsettings or .testsettings?

### ISSUE THREAD

**Issue by brandonh-msft** [MicrosoftDocs/visualstudio-docs#1685]
In VS2017.15.8.7 I go to "Add New File" and can choose "Test Settings" on the left. When I do this, the filename it creates for me ends in **.testsettings** not .runsettings. Yet this doco alludes to runsettings. Seems either the docs are wrong, or the product isn't matching up with what we're telling folks to do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I agree this is confusing and the docs can be improved here. I believe that [.testsettings files](https://docs.microsoft.com/en-us/visualstudio/test/collect-diagnostic-information-using-test-settings?view=vs-2017) are used for load tests, and .runsettings files are used to configure unit tests. To [add a .runsettings file](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017#customize-tests), you create an XML file and then change the file extension to .runsettings. @boraprachi Can you verify this information?

**Comment by StingyJack** [comment]
TestSettings are for legacy mstest v1. You cant use them with v2, only runsettings are supported.   VS is giving you the wrong file.

**Comment by brandonh-msft** [comment]
Could we fwd this as a bug to the appropriate team if in fact it is a VS issue, then? Happy to do this if you can point me in the right direction.

**Comment by omaslo** [comment]
why is this feedback closed? I use VS 2017 and it stills create .testsettings which is incompatible with mstest v2, which is the default test framework in this version of VS 2017. How can this critical piece of functionality which are tests be so screwed in your product that I pay a lot of money for? FIX IT!

**Comment by gewarren** [comment]
@brandonh-msft Per our email conversation, did you report an issue or contact @kendrahavens? If there's a report on Developer Community, people could upvote it.

**Comment by StingyJack** [comment]
> If there's a report on Developer Community, people could upvote it

@gewarren if only that were true. Issue reports there get closed and locked faster than the MSDN forums. Once closed, items can't accrue votes and eventually can't be commented on.

Then again, this is the kind of broken thing we expect to just be fixed, without having to vote on it.

**Comment by brandonh-msft** [comment]
> @brandonh-msft Per our email conversation, did you report an issue or contact @kendrahavens? If there's a report on Developer Community, people could upvote it.

https://developercommunity.visualstudio.com/content/problem/433205/deprecated-testsettings-file-created-when-adding-n.html

![image](https://user-images.githubusercontent.com/20270743/74184343-7c269800-4bfb-11ea-823e-7874b7948a35.png)

**Comment by omaslo** [comment]
I converted my tests to xunit today, unfortunately. xunit is also downloaded twice as much as mstest (63 mil vs 32 mil) and in addition used by Microsoft as well. I guess it gives us all a hint what framework to use and which one to ignore.

**Comment by StingyJack** [comment]
@brandonh-msft nobody can vote on closed items, so if you want to get traction you will need to reopen that. 

For which I bid you best of luck. I've got issues that have 90+ votes that were closed in error and nobody seems to be able to figure out how to reopen or create a new issue and transfer the votes and comments.

**Comment by brandonh-msft** [comment]
> @brandonh-msft nobody can vote on closed items, so if you want to get traction you will need to reopen that.
> 

understood; was merely answering the prompt by my colleague, showing what happened when I did contact Kendra :/

**Comment by kendrahavens** [comment]
Apologies, we were unable to fix the issue at the time because some features (such as load test) still required a testsettings file. That is why we recommended you use the extension to generate a runsettings template as a workaround while using Visual Studio 2017. (https://marketplace.visualstudio.com/items?itemName=OsirisTerje.Runsettings-19151) Visual Studio 2017 will continue to support testsettings so removing the template entirely is not an option. Adding a runsettings template in Visual Studio 2019 that you can optionally choose is currently planned and on the backlog.
