### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/visualstudio-docs#1687]
Ok, I found the images by just coping/pasting the links - from getData() method of the code - to a browser. But the project created in `VS2017` shows the `public\image` sub-folder with no such sub-folder created in File explorer. And after I created this sub-folder and copy the images there and ran the app again, the images still do not show-up in the app.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa65a08-a9e2-721d-e00c-1f28afffe2be
* Version Independent ID: babf20c3-c235-d839-7340-fb9c11c449dc
* Content: [Create a Node.js and Express app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs?view=vs-2017)
* Content Source: [docs/javascript/tutorial-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@saf-itpro Hi, it sounds like you are trying to do something different than the steps in the tutorial? Like copying images locally and then showing them in the app? The tutorial is only showing you how to load the images as a web resource. The images should show up when you click the buttons, if you use the code described in the article.

**Comment by c6wayne** [comment]
Possibly you typed getElementByID (cap "ID") when it should be getElementById (lower "d" in Id).  That is what I did.  Hope that helps.

**Comment by gewarren** [comment]
Same as #1528.

**Comment by praveen2916** [comment]
> Possibly you typed getElementByID (cap "ID") when it should be getElementById (lower "d" in Id) - see the index.pug file in this tutorial. That is what I did. Hope that helps.

Hi, 
I checked getElementById and it is as it should be in the code.  The problem still persists.
Any Ideas??
Thanks.
