### ISSUE TITLE
What is the behavior for multiple installations?

### ISSUE THREAD

**Issue by GearedToWar** [MicrosoftDocs/visualstudio-docs#1692]
Does the tool clean/remove all SxS installation of VS under '%ProgramFiles(x86)%\Microsoft Visual Studio'\?
I was expecting it would take a path as a parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2017)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
Yes, it removes all instances. This is meant as a last resort for any catastrophic configuration errors. Uninstalling through the Visual Studio Installer should be the first thing you should try. Reliability has greatly improved from version to version, so if you find you are in a terribly corrupt state and think you require running the cleanup tool, please first open a feedback ticket from within the Visual Studio Installer in the upper-right corner so we can investigate.

**Comment by gewarren** [comment]
Adding doc feedback label in case you want to note this in the topic, @TerryGLee.
