### ISSUE TITLE
Create Layout with --includeOptional is erroring

### ISSUE THREAD

**Issue by ShayneHau** [MicrosoftDocs/visualstudio-docs#1693]
Issuing the following:
vs_enterprise.exe --layout c:\cache\VS2017 --lang en-US --add Microsoft.VisualStudio.Workload.Azure --includeOptional
results in error:
VisualStudio Bootstrapper:16/10/2018 5:24:46 PM: Vs setup process exited with code 87

I found doco suggesting code 87 relates to an invalid argument. 
Sure enough, running without --includeOptional succeeds, but then only the required packages are downloaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017#list-of-language-locales)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ShayneHau Thanks for your feedback. We'll take this under advisement and augment the documentation if necessary, (@tedvz - FYI.)

**Comment by ShayneHau** [comment]
Think I've found the source of the problem. The version of vs_enterprise.exe used was sourced from Visual Studio Subscriptions downloads. Assumed that would be latest version, but is v15.0
Re-downloaded v15.8 and now it is behaving more as expected.

**Comment by TerryGLee** [comment]
@ShayneHau Thanks for letting us know! We're glad to hear that this has worked out for you. We'll close this issue.
