### ISSUE TITLE
Invalidate a match missing '<'

### ISSUE THREAD

**Issue by KeithBeardmore** [MicrosoftDocs/visualstudio-docs#1694]
(?!abc) should read (?&lt;!abc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2017)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@KeithBeardmore I believe that `<` is used to invalidate a match only when the match occurs before the string, i.e. it's a negative look-behind character. I verified that the existing example works as it says it does.

`(?<!ity)real` matches "lyreal" but not "ityreal".
