### ISSUE TITLE
CodeTaskFactory using the Class type

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/visualstudio-docs#1696]
All the samples here uses the Fragment type. It would be good with an example using the Class and Method types as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8c66d6-dd9b-dddc-dd69-41d22284ec10
* Version Independent ID: 1b750d67-95da-aa4c-ad32-2de54d7a46c5
* Content: [MSBuild Inline Tasks with RoslynCodeTaskFactory - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-roslyncodetaskfactory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-roslyncodetaskfactory.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
This is a good idea, but the work is currently out of scope.
