### ISSUE TITLE
Add links for Python 2.7.12-15

### ISSUE THREAD

**Issue by ag-stephan** [MicrosoftDocs/visualstudio-docs#1697]
Debug symbols for Python 2.7.12-15 do not have links. They are available from python.org, so they can and should be linked here as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a28d662-7af8-e0cc-dc6c-b300d22eb16d
* Version Independent ID: 61410436-ef1f-6858-618d-c3a2da35309a
* Content: [Symbols for mixed-mode Python/C++ debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-symbols-for-mixed-mode-c-cpp-python?view=vs-2017#official-distributions)
* Content Source: [docs/python/debugging-symbols-for-mixed-mode-c-cpp-python.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/debugging-symbols-for-mixed-mode-c-cpp-python.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by minkushjain** [comment]
Done. Created a PR for the change. https://github.com/MicrosoftDocs/visualstudio-docs/pull/1699
