### ISSUE TITLE
VS SDK API Reference is missing

### ISSUE THREAD

**Issue by huguesv** [MicrosoftDocs/visualstudio-docs#170]
I was looking for documentation on IVsSetupCompositionService, which is new to VS 2017, but it's nowhere to be found.

Links to VS interface definitions, like in https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/list-of-available-services, are redirecting to VS 2015 documentation.

**Comment by ghogen** [comment]
This is an known issue and we are in the process of publishing the VS SDK API Reference. Once that process completes, we can update the links to point to the new VS 2017 content on docs.microsoft.com.

**Comment by gewarren** [comment]
This looks to be resolved now, e.g. https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivssetupcompositionservice?view=visualstudiosdk-2017 for IVsSetupCompositionService. Please reopen the issue if you are still seeing redirects to VS 2015 documentation.
