### ISSUE TITLE
Morteza jan jani 

### ISSUE THREAD

**Issue by Wphelp98737** [MicrosoftDocs/visualstudio-docs#1704]
#### Document Details

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-dev15**
* GitHub Login: @seiyer
* Microsoft Alias: **seiyer**

**Comment by Wphelp98737** [comment]
https://developercommunity.visualstudio.com/solutions/360316/view.html

**Comment by gewarren** [comment]
@Wphelp98737 Morteza, can you describe what your issue is about?
