### ISSUE TITLE
hcsshim::ImportLayer failed in Win32

### ISSUE THREAD

**Issue by dudi938** [MicrosoftDocs/visualstudio-docs#1706]
I try build Image from this Dockerfile:
 # escape=`

FROM microsoft/dotnet-framework:4.7.1

SHELL ["cmd", "/S", "/C"]

ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --all `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

ENTRYPOINT C:\BuildTools\Common7\Tools\VsDevCmd.bat &&

CMD ["powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass"]

And i get this error:
**re-exec error:
exit status 1: output: time="2018-10-17T17:16:40+03:00" level=error msg="hcsshim::ImportLayer failed in Win32:
 The system cannot find the path specified. (0x3) layerId=\\\\?\\C:\\ProgramData\\Docker\\windowsfilter\\d9c80f6bea48a36df56d1ae6ef3a0ac215437e35cc645e695f452c2870eac7cd flavour=1 folder=C:\\ProgramData\\Docker\\tmp\\hcs085605583"hcsshim::ImportLayer failed in Win32: 
 The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\Docker\windowsfilter\d9c80f6bea48a36df56d1ae6ef3a0ac215437e35cc645e695f452c2870eac7cd flavour=1 folder=C:\ProgramData\Docker\tmp\hcs085605583**

What can be the reason of this error?

**Comment by gewarren** [comment]
@lisaguthrie Can you take a look at this issue?

**Comment by lisaguthrie** [comment]
It's a Docker error. This might help with resolving it: https://github.com/moby/moby/issues/32838#issuecomment-399622268
