### ISSUE TITLE
Great idea! ... but where is the list of suggestions to vote?

### ISSUE THREAD

**Issue by neoDD69** [MicrosoftDocs/visualstudio-docs#1708]
I've tried to find a list of suggestions before adding mine and voting they … but no UI to reach the list!
I can only add new suggestions and the only signal that there are others suggestions is that during the typing the UI shoe me a list with others suggestions.

Moreover there are trivial errors in the UI … talk about issue and not about suggestions ;)
"Add a topic for the product version and issue type you are reporting. For example, start typing "Visual Studio", "TFS" or "Visual Studio for Mac" in the topics field below and auto-complete should help."

I hope you will fix the BUGS and open a suggestions section for the developer SITE … in some feature/bug is very embarrassing for a software house like Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-dev15**
* GitHub Login: @seiyer
* Microsoft Alias: **seiyer**

**Comment by gewarren** [comment]
@seaniyer FYI - the user is looking to just see a list of suggestions. Also the text "Add a topic for the product version and issue type you are reporting." should be changed to "Add a topic for the product version and type of feature you're suggesting.

**Comment by seaniyer** [comment]
@neoDD69 - Thanks for sharing your feedback.  We are working on addressing these UI problems.  Since these are bug reports, would you please file them on https://developercommunity.visualstudio.com or upvote existing problems as it enables us to track them better and keep you posted.

**Comment by DataJuggler** [comment]
You closed the issue and never fixed it. I can't find any suggested features to vote on, or see if others voted on mine.

Less work for you I supposed if you hide all the suggestions.
