### ISSUE TITLE
Update command

### ISSUE THREAD

**Issue by JamesMBristow2** [MicrosoftDocs/visualstudio-docs#1709]
Wouldn't running the "vs_installer.exe update --passive --installpath '&lt;pathToVS&gt;'" option be preferable since it updates both in one line?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for Visual Studio installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@JamesMBristow2 Thanks for your feedback; we appreciate it. And yes, while you could use one line, we chose to use multiple lines in our examples so that the individual command lines can be more easily differentiated between. But thanks for including an alternate example via this inquiry mechanism.

**Comment by mattsmacblog** [comment]
Can you update the command reference?  Nowhere on here does it mention that "--update" is a valid option or that it updates the Updater.  - https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019 or https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017

vs_enterprise.exe --update --quiet --wait
vs_enterprise.exe update --wait --passive --norestart --installPath "C:\installPathVS"
