### ISSUE TITLE
Could not generate any test in x runs

### ISSUE THREAD

**Issue by MuhammadAliSaeed** [MicrosoftDocs/visualstudio-docs#1711]
I am facing this warning for a long time.

Kindly review the details on  stackoverflow .
[https://stackoverflow.com/questions/52817033/intellitest-could-not-generate-any-test-in-x-runs](url)

**Comment by gewarren** [comment]
@MuhammadAliSaeed The issues in this repo are for documentation issues, and this sounds like a product issue. Please use the Help > Send Feedback > Report a Problem menu in Visual Studio to report your issue. Using that menu automatically includes configuration information from your machine in the problem report.

**Comment by MuhammadAliSaeed** [comment]
@gewarren Thanks for feedback, also apologize for raising product issue in this repo.
