### ISSUE TITLE
Custom Layout builds layout but install gives an error

### ISSUE THREAD

**Issue by Jonathan811** [MicrosoftDocs/visualstudio-docs#1712]
Hello

I have created a custom layout using above guide and the layout is created.  I copy the layout to a VM (with internet) and start the install using above syntax but get a error.

Layout command:
vs_professional.exe --layout e:\vs2017layout --add Microsoft.VisualStudio.Workload.CoreEditor --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.Azure --includeOptional --add Microsoft.VisualStudio.Workload.Data --includeOptional --add Microsoft.VisualStudio.Workload.DataScience --includeOptional

Install command (run on VM on E:):
vs_professional.exe e:\vs2017layout --add Microsoft.VisualStudio.Workload.CoreEditor --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.Azure --includeOptional --add Microsoft.VisualStudio.Workload.Data --includeOptional --add Microsoft.VisualStudio.Workload.DataScience --includeOptional

But this gives error:
Visual Studio Installer

At most one command parameter can be specified

Usage: vs_installershell.exe /finalizeinstall [command[options]]
Commands
install installs a product
modify modifies an installed product
update updates an installed product....etc

Any ideas on the commands to create an offline layout and then install that same layout?

Many Thanks
Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Jonathan811 For installation support requests, please consider using either our [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us an other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by Jonathan811** [comment]
to get past this the command line for install IS NOT THE SAME AS to create the layout


c:\vs2017layout\vs_professional.exe --add Microsoft.VisualStudio.Workload.CoreEditor --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.Azure  --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Workload.DataScience --includeOptional 

in case that helps anyone else
