### ISSUE TITLE
No such checkbox in VS2017 15.8.7

### ISSUE THREAD

**Issue by tlhintoq** [MicrosoftDocs/visualstudio-docs#1713]
Title says it all.  If you follow those step there is no such checkbox.  However its kinda hard to say since choosing any of the actual configurations from the dropdown crashes VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573429a4-7c2d-5ede-9c34-934cc26a4045
* Version Independent ID: 351b628e-ff1c-7a64-0c46-74887a97cd0d
* Content: [How to: Enable and Disable Automatic Code Analysis for Managed Code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code?view=vs-2017)
* Content Source: [docs/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@tlhintoq What type of project are you working in? I see the checkbox for a console app project in 15.8.7.

For the crashing issue, can you please file a report using the Help > Send Feedback > Report a Problem menu in Visual Studio? That way the problem report automatically contains configuration information from your machine. (This repo's issues are for documentation issues, not product issues.)

**Comment by tlhintoq** [comment]
Project type is: Xamarin cross-platform appliction 

Crash: Already reported. 

Thanks for the super fast reply! 

Regards, 

Clint

On 19.10.2018 15:39, Genevieve Warren wrote:

> @tlhintoq [1] What type of project are you working in? I see the checkbox for a console app project in 15.8.7. 
> 
> For the crashing issue, can you please file a report using the Help > Send Feedback > Report a Problem menu in Visual Studio? That way the problem report automatically contains configuration information from your machine. (This repo's issues are for documentation issues, not product issues.) 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/tlhintoq
[2]
https://github.com/MicrosoftDocs/visualstudio-docs/issues/1713#issuecomment-431476084
[3]

**Comment by gewarren** [comment]
@tlhintoq Thanks for reporting the crash. I don't even have a **Code Analysis** tab in the properties for a Xamarin mobile app project. Do you?

**Comment by richteel** [comment]
I may have found the error of my ways. It appears that you need to save all before building. If you don't, the build will hang. Too use to web and Windows development where this is not a problem. Just starting to learn Xamarin. (Finally)

**Comment by memark** [comment]
There is no Code Analysis tab on a freshly created ASP.NET Core project either in 15.8.7.

**Comment by gewarren** [comment]
@tlhintoq The issue was closed because I added a note that the Code Analysis tab is not available for .NET Core, .NET Standard, and other "new" project types. This is by design.

What is the actual problem you're trying to solve, and then perhaps I can point you in the right direction? Are you trying to suppress code analysis warnings from the Error List?

**Comment by tlhintoq** [comment]
@gewarren 
Ok.  I'll try to rephrase it.
Hitting 'build' causes Visual Studio 2017 build 15.8.x to go off into limbo - if you've made any changes to a XAML document.  
If you hover over the animated building icon of a box with arrows going into it, its stuck on the `Code Analysis` task.
In following the MSDN documentation to turn off automatic code analysis we are unable to turn it off because the checkbox that governs it, as described in the documentation doesn't exist.
This is the documenation I'm referring to:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code.md

As for the tab not being available... It sure seems to be because I can see.  Just like others here have and said they see it.  And we all report the same behavior that selecting it causes VS to again go off into endless loading.
![image](https://user-images.githubusercontent.com/11351506/47590123-65dac700-d939-11e8-923e-1c315a22b7a4.png)

I'm starting to get the impression that the people working this bug are not trying to follow the directions that we are referring to.  Or are in some way in an area of Visual Studio than the rest of us seeing the bug are in.  So let me ask you this... If you follow those same directions are you taken to the same dialog I have just posted?  And do you see the same thing the rest of us see and report?

**Comment by gewarren** [comment]
@tlhintoq It looks like you're looking at the properties for the *solution* instead of the *project*. The topic you refer to asks you to right-click on the _project_ and select Properties, not right-click on the solution. I think that explains why you don't see the checkbox you expect to see. For a project type that has static code analysis, this is what you should see in the Code Analysis tab of the project properties:

![image](https://user-images.githubusercontent.com/24882762/47600009-ef58bc00-d96e-11e8-8d45-85d98fd96c82.png)

**Comment by tlhintoq** [comment]
@gewarren 
You are right.  My mistake.  A picture really is worth a thousand words.  I feel silly now. Amazing how one can read the thing, wrong, a dozen times.  Once you think you know what you're seeing you see it the same way every time.  

I hope you have a terrific weekend!
