### ISSUE TITLE
What is a Roaming Extension

### ISSUE THREAD

**Issue by jchesshir** [MicrosoftDocs/visualstudio-docs#1714]
On the left panel, there are 4 categories: Installed, Online, Updates,  and Roaming Extensions Manager.  The first three make sense, but the Roaming Extension Manager doesn't make sense, and I cannot find documentation describing its functionality in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and use Visual Studio extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.ExtensionManager)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2017)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jchesshir Thanks for the very specific feedback. I'll try to find out what Roaming Extensions Manager means.

**Comment by gewarren** [comment]
The Roaming Extension Manager tab keeps track of all the extensions you've installed in the past, so you can more easily install them again. It’s like a view of your favorites, but the list is automatically generated for you.

I'll keep this issue open so I can update the topic too.

**Comment by jchesshir** [comment]
Looks good @gewarren.  Thank you for the clarification.

**Comment by Dboingue** [comment]
Then what does it mean to start or stop roaming for an extension?  because it seems that an extension can be enabled generally but roaming can be stopped.... Is it that a stopped roaming extension, that is disabled as well, will stop showing up in the roaming category?

**Comment by abelbraaksma** [comment]
@Dboingue, did you meanwhile find out what it does? When I click it, I only see it swap between "Start roaming" and "stop roaming" and the little cloud-overlay icon appears/disappears. I don't know if it changes whether the extension is available to other instances of VS or not. @gewarren, any idea?

Btw, you wrote in the docs:

> It's designed to let you find your favorite extensions more easily.

It seems to only list them. It doesn't allow install/uninstall/update/enable/disable from that list. Sometimes there's a button "download" (which _does seem to work_), and the confusing button "stop roaming".

**Comment by sercanparan** [comment]
If it's designed to let us find our favorite extensions more easily then why don't you call it "Favorite Extensions" instead of "Roaming Extension Manager"?
