### ISSUE TITLE
Add note on extra result on DataDriven Tests

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/visualstudio-docs#1715]
### Summary
Data Driven tests give an extra result that is the sum of all the data driven tests. So if all are passing then the summary test passes, if one fails then the summary test also fails. We got [some feedback](https://twitter.com/kitokeboo/status/1053372805096427520) that this extra result was confusing and does not provide them much value.

> If the test fails, I am only about which set of input data caused the failure. A comment on this docs would also help eliminate the confusion.

Adding a note to docs would help reduce confusion while we take this design feedback into account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1351cc8-f703-27a2-32c7-904256cb9e82
* Version Independent ID: 7a6912ef-da8d-6690-6da9-cc741fd5acde
* Content: [How To: Create a Data-Driven Unit Test in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2017)
* Content Source: [docs/test/how-to-create-a-data-driven-unit-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-create-a-data-driven-unit-test.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Infraton11** [comment]
CRUNCH!
