### ISSUE TITLE
Need info if multiple devenv.exe processes are running

### ISSUE THREAD

**Issue by rwjdk** [MicrosoftDocs/visualstudio-docs#1723]
This is a nice feature but it seems to just use the first devenv.exe file it finds. Is there any way to specify which of the existing devenv.exe processes that should open it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e9a90e4-f661-bf81-7963-aee066e1551a
* Version Independent ID: 76b608a1-d052-ce5d-4896-fbeb1bdd33c0
* Content: [-Edit (devenv.exe) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/edit-devenv-exe?view=vs-2017)
* Content Source: [docs/ide/reference/edit-devenv-exe.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/edit-devenv-exe.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
A comment on this [blog post](https://blogs.msdn.microsoft.com/saraford/2008/11/19/did-you-know-you-can-use-devenv-exe-edit-to-open-a-file-in-an-existing-visual-studio-instance-360/) indicates the most recently used instance of VS will be used. If there's a way to specify an instance, I'll update the page.

100 page views/month = P2

**Comment by gewarren** [comment]
@rwjdk I confirmed with the product team that there's no way to specify which instance will open the file, unfortunately.
