### ISSUE TITLE
InstallShield Limited sidebar link doesn't work

### ISSUE THREAD

**Issue by elitree** [MicrosoftDocs/visualstudio-docs#173]
On the page https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components, the InstallShield Limited sidebar link doesn't seem to do anything other than reloading the current page.

Should the sidebar link be updated to point to this page? Not sure what the live URL is or if there is a live version, but the GitHub link is https://github.com/Microsoft/visualstudio-docs/blob/master/docs/deployment/installshield-limited-edition.md.

Thanks!

**Comment by gewarren** [comment]
I don't see the link anymore on the Deploying Application page anymore. The installshield-limited-edition.md topic is no longer part of our live doc set (but yet, is still in the GitHub repo). Closing this issue.
