### ISSUE TITLE
Failure to connect due to authentication

### ISSUE THREAD

**Issue by alpinedelight** [MicrosoftDocs/visualstudio-docs#1730]
I received the following message whilst trying to remote debug a C++ program:
"visual studio was unable to create a secure connection to &lt;remote machine name&gt; authentication failed". It would connect and prompt for user and password. However, it never accepted the password and didn't present an error.
After some investigation I realised that it had nothing to do  remote debugger, and was actually due to the fact that "local accounts" was in the group policy "Deny access to this computer from the network" (under secpol.msc &gt; Security Settings &gt; Local Policies &gt; User Rights Assignment ). Removed local accounts from the list and was able to connect.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 284b9094-8c91-69e1-01a2-0183ca3ec2a9
* Version Independent ID: 8f7a16bb-32f6-3047-16e3-b82b82fbb7c0
* Content: [Unable to Connect to the Microsoft Visual Studio Remote Debugging Monitor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor?view=vs-2017)
* Content Source: [docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Need more context.
