### ISSUE TITLE
Please step through this page yourself.

### ISSUE THREAD

**Issue by mrmsbarnes** [MicrosoftDocs/visualstudio-docs#1732]
This page HAS to be correct.  Hopefully for both Visual Studio 2015 and Visual Studio 2017.
When I try to follow this I get LNK 1561 entry point must be defined (regardless of No Entry Point setting).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec762474-4eeb-cba2-5290-fd664ab88f8c
* Version Independent ID: 318fa7f6-e54a-1777-1f3f-3a30bb736f69
* Content: [Tutorial: Debug managed and native code (mixed mode) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-managed-and-native-code?view=vs-2017)
* Content Source: [docs/debugger/how-to-debug-managed-and-native-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-managed-and-native-code.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by mrmsbarnes** [comment]
"Any CPU" setting can't be made.  Is this equivalent to Linker option /clr:safe (Common Language Runtime Suport)?

**Comment by mrmsbarnes** [comment]
Sorry, that's C/C++ option not Linker.

**Comment by Mikejo5000** [comment]
@mrmsbarnes Thanks, I'll take a look at this.

**Comment by Mikejo5000** [comment]
@mrmsbarnes I went through this doc for a .NET and a .NET Core calling app. There were a bunch of clarifications I made. Any CPU is only in C# apps now, so I fixed that. I believe the main issue you were seeing with the LNK 1561 error is that the configuration properties for the DLL apply on a per-platform basis, so if you set to a DLL configuration type for x64 build, you need to set it again for x86 build to make it work. Also, the mixed use of hyphens and underscores in naming projects was not good and was quite confusing, I thought. That becomes an issue if you need to manually update the path to the DLL.

**Comment by Mikejo5000** [comment]
Also, this is focused on the mixed mode debugging scenario, unlike the C++ topic you link to, so I need to keep this. I only tested on VS 2017, since these are VS 2017 docs. However, the improvements should also help with VS 2015.

**Comment by mrmsbarnes** [comment]
To Mike Jones,

Thank you very much.  I love c# but I still need c++ speed sometimes.  This will help.  (So will UWP I hear).
