### ISSUE TITLE
subtype missing

### ISSUE THREAD

**Issue by hyang336** [MicrosoftDocs/visualstudio-docs#1733]
I'm fairly new to VS and machine learning, I followed the steps in this tutorial, and installed the latest VS community 2017. But when I try to load any of the tensorflow projects it gave me this error:

There is a missing project subtype.
Subtype: '{D22814C2-A430-4A53-8052-A3A64BFB2240}' is unsupported by this installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edd39419-ab4d-4b4a-6756-281654dd7921
* Version Independent ID: 880914b1-d00c-e53b-e830-0aefab80805d
* Content: [Train a tensorflow model locally - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ai/tensorflow-local?view=vs-2017)
* Content Source: [docs/ai/tensorflow-local.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ai/tensorflow-local.md)
* Service: **multiple**
* Product: **visual-studio-dev15**
* GitHub Login: @lisawong19
* Microsoft Alias: **liwong**

**Comment by brettcoryell** [comment]
I have the same issue.

**Comment by lisawong19** [comment]
@TerryGLee I no longer work for docs. 
@rloutlaw @thomps23

**Comment by WilliamAntonRohm** [comment]
@hyang336 -- here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

If you’re having an issue with installation, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.
We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.
Here are a few more support options:
-	Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).
-	Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).


I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
