### ISSUE TITLE
Couple the test project to the DLL project, No common properies

### ISSUE THREAD

**Issue by AmirHMousavi** [MicrosoftDocs/visualstudio-docs#1735]
I am using VC++ 2017 on Community v15.8.8
following the instruction at [Coupling ](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-writing-unit-tests-for-cpp-dlls?view=vs-2017#make_functions_visible), I do not see any `Common Properties ` and hence no `Framework and references` to add new reference in test project properties. Both `dll `and `test `project are created in one solution . in general the screenshots in tutorial looks totally different from what I see in my VS.

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@AmirHMousavi thanks for the report and apologies for very delayed response. This topic was out of date. For VS 2017 and later, choose Add > Reference from the project shortcut menu. Topic is fixed and correct instructions should be visible in a couple of days.
