### ISSUE TITLE
Version Update 15.8.8 Not Displayed

### ISSUE THREAD

**Issue by tecky7** [MicrosoftDocs/visualstudio-docs#1736]
after doing a 120GB dowload from my ISP "the updates from this morning". The servers were OK but when compiling the files to the hard drive.  I was expecting 15.9 preview , but the system reportly a different version update "15.8.8"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio 2017 build numbers and release dates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2017)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by tecky7** [comment]
here is a Screenshot of my system
https://imgur.com/a/EoxQGzw

**Comment by TerryGLee** [comment]
@tecky7 Thanks; the update you mention (15.8.8) will be reflected on the page within the next few hours.

**Comment by TerryGLee** [comment]
Also, @tecky7, please note that Visual Studio will notify you of an update that matches the version number of its most current iteration. For your system, currently, that's 15.8._x_. If you want to download a Preview copy of the next version, 15.9.0, there are several ways to do that:
1.) Use the Visual Studio Installer (for more information, see the  [Update Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2017) page.
2.) Download directly from the Release Notes pages:
     a.) [Preview release](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes?context=visualstudio/default&contextView=vs-2017)
     b.) [Current release](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes?context=visualstudio/default&contextView=vs-2017) 
Hope this helps,
~ Terry

**Comment by tecky7** [comment]
As a programmer and a enginner at Bolton University dating back 2001 - 2004

https://courses.bolton.ac.uk/course/COM001-F-UOB-SX/2018-19/?_ga=2.45029156.1010388917.1540486729-1401855886.1540486729

You guys never verified the program installer verses the webpage

**Comment by TerryGLee** [comment]
@tecky7 Our publishing platform for documentation is separate from our software distribution channel. Typically, we mesh these together but sometimes they can get out of sync. This is one of those times.
