### ISSUE TITLE
Totally not useful

### ISSUE THREAD

**Issue by MrSent** [MicrosoftDocs/visualstudio-docs#1738]
How about a full read of the data, then an update so you can see the whole cycle? This is garbage

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4af8d633-f9be-cab0-195e-94e4f775aa35
* Version Independent ID: b0bf09be-4557-4427-b548-1c5d83aaa146
* Content: [Update data by using a TableAdapter - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/update-data-by-using-a-tableadapter?view=vs-2017)
* Content Source: [docs/data-tools/update-data-by-using-a-tableadapter.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/update-data-by-using-a-tableadapter.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
2300 page views per month = P1

**Comment by ghogen** [comment]
Closing out issues in older technology areas. Users are advised to consider using newer data access technologies such as Entity Framework.
