### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by jg15** [MicrosoftDocs/visualstudio-docs#1744]
Is it possible to provide a few code examples for when these annotations should be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4652882-17eb-e661-8283-968c19191752
* Version Independent ID: 4762e718-55eb-248b-4adc-a53e44d9189e
* Content: [Specifying When and Where an Annotation Applies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/specifying-when-and-where-an-annotation-applies?view=vs-2017)
* Content Source: [docs/code-quality/specifying-when-and-where-an-annotation-applies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/specifying-when-and-where-an-annotation-applies.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@sunnychatterjee Do you have any sources for examples of using these SAL annotations?

**Comment by corob-msft** [comment]
Closing for lack of developer response. Sorry.
