### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by alexiorodrigues** [MicrosoftDocs/visualstudio-docs#1751]
I was looking for a keyboard shortcut to easy the process. To access the override menu just Alt+Enter and it should be the 5th option, "Generate Overrides ..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2dad35-15b3-7597-6bca-4a7d617dac55
* Version Independent ID: e0fee980-8e2c-d52e-a713-cd92530d926b
* Content: [Generate a method override in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-override?view=vs-2017)
* Content Source: [docs/ide/reference/generate-override.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-override.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@alexiorodrigues Could you log this is a feature suggestion at [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8) instead? It will get more traction with the product team there, and can also be upvoted more easily.
