### ISSUE TITLE
Debug at Design Time with Immediate Window not working in .Net Core console app.

### ISSUE THREAD

**Issue by crowcoder** [MicrosoftDocs/visualstudio-docs#1752]
In a .Net Core 2.1 console app, breakpoints are not hit when using the Immediate Window.  I do see things like this output to the Immediate Window: "Cannot evaluate expression because the current thread is stopped in the prolog of a function." and "Expression has been evaluated and has no value". A .Net Framework console app works as described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c195bbb1-22be-9da7-9792-1c829d73a21b
* Version Independent ID: 0d83875a-56c4-d897-e771-aa3ef9bf910d
* Content: [Debug at Design Time - Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-at-design-time?view=vs-2017)
* Content Source: [docs/debugger/walkthrough-debugging-at-design-time.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-debugging-at-design-time.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@crowcoder Thanks! We'll take a look at updating this.

**Comment by Mikejo5000** [comment]
@crowcoder Since you are trying to hit a breakpoint, I presume you are in design mode, and not in the middle of a debugging session. Is that right?

**Comment by crowcoder** [comment]
That is correct, I was executing code from the immediate window. Had no problem with a full framework app.

Sent from my Windows 10 device

**Comment by crowcoder** [comment]
Update: I do not experience the problem on my home PC with VS 2017 Community 15.8.9. It also worked before I updated from 15.7.4.
My work PC where I am still experiencing the problem has been updated to 15.8.9 .
I guess the issue is environmental to my PC somehow.

**Comment by Mikejo5000** [comment]
That's a little surprising. Do both PCs have .NET Core 2.1? (maybe a bug fix). Otherwise, could there be a debugging option set different on the two PCs? I'm thinking mainly of the "Use Managed Compatibility Mode" or "Use the legacy C#...expression evaluator" options in Tools > Options > Debugging

**Comment by gregg-miskelly** [comment]
This is NOT due to managed compatibility mode or an expression evaluator issue. I believe it is a bug in the debugger exposed by .NET Core 2.1. You can work around it if you like by using .NET Core 2.0.

I opened a bug to track this internally. @crowcoder if you would like visibility into when it is fixed, please open a VS feedback ticket and post a link to it.

@Mikejo5000 please close this issue.

**Comment by Mikejo5000** [comment]
@gregg-miskelly Thanks, Greg.
