### ISSUE TITLE
Add docs on how to find the "Performance Explorer Toolbar"

### ISSUE THREAD

**Issue by KorkyPlunger** [MicrosoftDocs/visualstudio-docs#1753]
It would be quite helpful if these docs could tell you how to actually find the Performance Explorer toolbar, because it took me a full 25 minutes to find it. 

It doesn't show up under "View &gt; Toolbars" or "Analyze &gt; Windows". It's buried under "Debug &gt; Profiler &gt; Performance Explorer &gt; Show Performance Explorer" (which seems like an odd place for it, since it's not a debugging tool but analysis tool -- shouldn't it be under "Analyze?").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92336bb4-2fe8-692f-0aba-0f428fb4e3f3
* Version Independent ID: 55737936-9f79-34f4-993e-37819e561dd2
* Content: [Performance Explorer Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/performance-explorer-window?view=vs-2017)
* Content Source: [docs/profiling/performance-explorer-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/performance-explorer-window.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by kvarkel** [comment]
Ditto.  Thanks to Korky for helping me find it.

**Comment by Mikejo5000** [comment]
I'll update the doc. Thanks!

**Comment by Mikejo5000** [comment]
Adding link

**Comment by asm128** [comment]
There is no such option "Debug > Profiler"
