### ISSUE TITLE
Importance?

### ISSUE THREAD

**Issue by ThermoX360** [MicrosoftDocs/visualstudio-docs#1757]
How about describing what effects the Importance setting does? What's the difference between High, Normal, Low??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1eac2fe-feb2-6128-8509-208ed9b4ca04
* Version Independent ID: cb15b5ff-651f-9392-b2a8-69ea97350010
* Content: [Message Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/message-task?view=vs-2017)
* Content Source: [docs/msbuild/message-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/message-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ScotSalmon** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.framework.loggerverbosity?view=netframework-4.7.2 explains at least one effect, although by experiment it seems inconsistent with what I observe, which is that "low" shows at detailed verbosity or above, "normal" shows at normal verbosity or above (intuitively), and "high" shows at minimal verbosity or above.

**Comment by Mikejo5000** [comment]
Updating doc
