### ISSUE TITLE
MSBuild Items shouldn't contain File Tracking section

### ISSUE THREAD

**Issue by arturek** [MicrosoftDocs/visualstudio-docs#1762]
It seems that the File Tracking section is included by mistake as a part of MSBuild Items description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401f8953-3165-194b-3706-92336a5a93e1
* Version Independent ID: 1b4ee143-9b5e-58fe-f82e-6614f36b8113
* Content: [File Tracking - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/file-tracking?view=vs-2017)
* Content Source: [docs/msbuild/file-tracking.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/file-tracking.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald for comment on this issue

**Comment by rainersigwald** [comment]
Yeah, I'd say everything under `File Tracking` should instead be under `MSBuild Advanced Concepts`.

**Comment by martingbrown** [comment]
This feels like it should be under MSBuild Reference to me. This does not really introduce the concept at all.

**Comment by Mikejo5000** [comment]
Updating TOC
