### ISSUE TITLE
Link to adding feedback directly on GitHub is invalid

### ISSUE THREAD

**Issue by arturek** [MicrosoftDocs/visualstudio-docs#1763]
The link from the content feedback dropdown leads to https://docs.microsoft.com/en-us/visualstudio/msbuild/%7B0%7D which displays a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401f8953-3165-194b-3706-92336a5a93e1
* Version Independent ID: 1b4ee143-9b5e-58fe-f82e-6614f36b8113
* Content: [File Tracking - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/file-tracking?view=vs-2017)
* Content Source: [docs/msbuild/file-tracking.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/file-tracking.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
This seems to be working now. The link goes here:

https://github.com/MicrosoftDocs/visualstudio-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A%E2%9A%A0%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20%E2%9E%9F%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%20401f8953-3165-194b-3706-92336a5a93e1%0A*%20Version%20Independent%20ID%3A%201b4ee143-9b5e-58fe-f82e-6614f36b8113%0A*%20Content%3A%20%5BFile%20Tracking%20-%20Visual%20Studio%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fmsbuild%2Ffile-tracking%3Fview%3Dvs-2017)%0A*%20Content%20Source%3A%20%5Bdocs%2Fmsbuild%2Ffile-tracking.md%5D(https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fvisualstudio-docs%2Fblob%2Fmaster%2Fdocs%2Fmsbuild%2Ffile-tracking.md)%0A*%20Product%3A%20**visual-studio-dev15**%0A*%20GitHub%20Login%3A%20%40Mikejo5000%0A*%20Microsoft%20Alias%3A%20**mikejo**
