### ISSUE TITLE
Is there a way to control the amount of "fade" that is on this panel?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#1764]
its currently an on/off. I want to know when something is unused, but the fade level is too faint. Is there any way to control the darkness of the fading?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41602f7-2c5e-bf2a-9eab-50740dd10784
* Version Independent ID: c6b1f7c4-eb2d-a62a-7e1b-eb32b8a88947
* Content: [Options, Text Editor, C#, Advanced - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.CSharp.Advanced);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.2)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/ide/reference/options-text-editor-csharp-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-advanced.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@StingyJack I don't think controlling the amount of fade is currently supported. If you'd like to suggest this as a feature in a future version, please use the new “Suggest a feature” option on [Developer Community]( https://developercommunity.visualstudio.com/spaces/8/index.html).
