### ISSUE TITLE
Incorrect filename app.ts

### ISSUE THREAD

**Issue by scouser27** [MicrosoftDocs/visualstudio-docs#1767]
The file name in section #1 of Modify your app and push changes should be app.js

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d4b59f-07fd-b894-01f7-9bc2fc06e98a
* Version Independent ID: 1cb6913e-21a7-48d2-8b83-cb416304b0c5
* Content: [Publish a Node.js app to Linux App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/publish-nodejs-app-azure?view=vs-2017)
* Content Source: [docs/javascript/publish-nodejs-app-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/publish-nodejs-app-azure.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@billti I think app.ts is correct but we need to change the screenshot earlier. It shows a JS project instead of a TS project.

**Comment by Mikejo5000** [comment]
Thanks, Bill. I'll update the screenshot.
