### ISSUE TITLE
Hyperlink to C.21 please

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/visualstudio-docs#1773]
Make it easy for people to find things.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeb33abc-c866-3403-2092-ce5e5ed572da
* Version Independent ID: fa68b7a3-14f5-7143-deed-a9ee7d5ca04a
* Content: [C26432 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26432?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C26432)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/code-quality/C26432.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26432.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
fixed
