### ISSUE TITLE
How to auto upgrade VS2017 when there is a new upgrade available

### ISSUE THREAD

**Issue by Rajkumar-Uppala** [MicrosoftDocs/visualstudio-docs#1774]
Hi Team,
Currently our team is focusing on How to upgrade the VS2017 automatically with out any manual intervention.
Any kind of settings/configuration/privileges are required on the local machine?

We are currently at VS 2017 15.8.8 version following the process mentioned in below link
https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2017 

Please share your thoughts if any on this.

Thanks,
Rajkumar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3386e-6b18-1cbd-9f1b-523b27b6521b
* Version Independent ID: 5ddf5e28-86d1-28b6-80ef-332bf93e17ac
* Content: [Update Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2017)
* Content Source: [docs/install/update-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Rajkumar-Uppala Thanks for your inquiry. If you require support for your installation, please consider contacting us by using either our dedicated [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
