### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by christylopez111** [MicrosoftDocs/visualstudio-docs#1775]
Good tutorial for beginners

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10a448aa-4d5d-f827-6511-6c4ac9528122
* Version Independent ID: 5a8e5560-40c3-3787-ae3c-ce84ed28cc79
* Content: [Walkthrough: Create a simple application with C# or Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-create-a-simple-application-with-visual-csharp-or-visual-basic?view=vs-2017)
* Content Source: [docs/ide/walkthrough-create-a-simple-application-with-visual-csharp-or-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-create-a-simple-application-with-visual-csharp-or-visual-basic.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@christylopez111 Thank you for your positive feedback! We very much appreciate it. :)
