### ISSUE TITLE
Example code is wrong

### ISSUE THREAD

**Issue by ViktorHofer** [MicrosoftDocs/visualstudio-docs#1776]
Duplicate closing parenthesis "&gt;" vs "/&gt;".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2cbd60-5d56-af4f-b196-4c9f190a1586
* Version Independent ID: 6408870a-85cd-428c-5ede-2338804481d6
* Content: [ZipDirectory Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/zipdirectory-task?view=vs-2017)
* Content Source: [docs/msbuild/zipdirectory-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/zipdirectory-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
This is fixed.
