### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by islambeddair** [MicrosoftDocs/visualstudio-docs#1778]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b7e2601-1fe4-228c-bde4-e29e52c8f7b9
* Version Independent ID: f5e06a1c-63aa-75fb-8398-0cb32db19677
* Content: [Step 3: Set your form properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-3-set-your-form-properties?view=vs-2017)
* Content Source: [docs/ide/step-3-set-your-form-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-3-set-your-form-properties.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@islambeddair Do you have some specific feedback for us?
