### ISSUE TITLE
There's no "Text" property for the checkbox control

### ISSUE THREAD

**Issue by GeVanCo** [MicrosoftDocs/visualstudio-docs#1779]
In secion "To add controls...", point 7 there's mentioned to select Text and change content to "Stretch".  However, there's no property "Text", there's only "(Name)" available in the Properties view when the checkbox is selected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e155a58-40dd-c4f9-5089-dabc1870c5a8
* Version Independent ID: e257ebf0-4506-408f-c078-18a35820fe60
* Content: [Step 5: Add controls to your form - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-5-add-controls-to-your-form?view=vs-2017)
* Content Source: [docs/ide/step-5-add-controls-to-your-form.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-5-add-controls-to-your-form.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@GeVanCo Thanks for letting us know; this is in our backlog to fix.

**Comment by salomonsk8r2003** [comment]
Looks good to me. Must have been fixed.

**Comment by gewarren** [comment]
"Choose the Text property and type in the word Stretch, as shown in the following picture." - is the offending line.

**Comment by salomonsk8r2003** [comment]
There is a text property. It is a property of the Check Box, and it wants you to type "Stretch" into it. 
So either you have a different version of Visual Studio, or you are misreading the instructions. But there is definitely a Text property on my side. And I was able to type the word "Stretch" into it exactly how the tutorial shows.

**Comment by gewarren** [comment]
@salomonsk8r2003 Thanks for confirming this. I'm closing the issue. @GeVanCo If you still feel there's an error in the article, please leave a comment.
