### ISSUE TITLE
ISerializable

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#1780]
What about types implementing `ISerializable`? Should this rule be applied to types `ISerializable`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6530e4d7-de03-64c6-972e-f5c2482db82c
* Version Independent ID: 8900d6df-d062-0d77-1756-525a8b4bd9a9
* Content: [CA2235: Mark all non-serializable fields - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2235-mark-all-non-serializable-fields?view=vs-2017)
* Content Source: [docs/code-quality/ca2235-mark-all-non-serializable-fields.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2235-mark-all-non-serializable-fields.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
@paulomorgado That is a potential improvement, but not a requirement currently. The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.iserializable?redirectedfrom=MSDN&view=netframework-4.7.2#remarks) states:
`Any class that might be serialized must be marked with the SerializableAttribute. If a class needs to control its serialization process, it can implement the ISerializable interface.`
My only concern would be now this will flag more cases, so even if we were to implement this, it should be a separate rule ID.

**Comment by mavasani** [comment]
Actually, given that [CA2237](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2237-mark-iserializable-types-with-serializableattribute?view=vs-2017) already recommends marking types implementing `ISerializable` with `SerializedAttribute`, we don't need to extend CA2235 - these rules in conjuction are sufficient. @paulomorgado does that sound reasonable to you? If so, we can document this relationship between CA2235 and CA2237 in the docs for these rules and close this issue.

**Comment by paulomorgado** [comment]
Can you do me a favor, @mavasani? Apply the analyzers to the `MyItemType` tell me what violations do you get and why do you think they are correct.

**Comment by gewarren** [comment]
Just to clarify, CA2235 now explicitly excludes _fields_ that are types that implement ISerializable. But if a _type_ implements ISerializable, CA2237 will fire to suggest also marking it with SerializableAttribute if it doesn't already. And if you mark that ISerializable type with SerializableAttribute, then CA2235 will analyze its fields to check if they are serializable. Is that correct @mavasani?
