### ISSUE TITLE
Running Python unit test by vstest.console.exe

### ISSUE THREAD

**Issue by Boruc04** [MicrosoftDocs/visualstudio-docs#1781]
I read this post and It was very helpful to me, but now I want to set up unit test written in Python in TFS CD pipeline. I found some post from Microsoft Support ( https://bit.ly/2JqLNbI ) that I need to run this code first with vstest.console.exe.
After hours and of investigations on how to run some simple test from python through vstest.console.exe do you know is there any way to do this? 
I reach the point that I need adapter but none of those that I found was working. Is it possible to somehow get what code is running behind test explorer in Visual Studio and what adapter is it using?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
* Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
* Content: [Unit testing for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2017)
* Content Source: [docs/python/unit-testing-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/unit-testing-python-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by zooba** [comment]
We strongly recommend using [pytest](https://docs.pytest.org/en/latest/) to run tests in continuous integration, or at least the built-in [unittest](https://docs.python.org/3/library/unittest.html) module.

The Visual Studio test adapter uses the latter behind the scenes, but does extra work to stream results. This means that tests take longer to run, and it is totally unnecessary when you are not in Visual Studio.

Using `pytest` is very straightforward if your tests already work in Visual Studio, and it can generate JUnit XML output that is useful for later analysis.

**Comment by Boruc04** [comment]
@kaigb - Thanks, I did run my test with adapter that you proposed and in return i receive message "Starting test execution, please wait..." - so same as when I run c# tests but after that nothing has happen.
I will than use pytest as @zooba recommend.
Thank you both for your help!
