### ISSUE TITLE
Full list of item metadata?

### ISSUE THREAD

**Issue by yhvicey** [MicrosoftDocs/visualstudio-docs#1783]
I'm seeking for documentation for &lt;LinkBase&gt; element and it seems missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62db4b12-8d5d-6a33-b5f6-b3f7320dd3f8
* Version Independent ID: 19ee6154-2eb2-b6a0-ab2e-96de2cfc05b2
* Content: [MSBuild Well-known Item Metadata - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-well-known-item-metadata.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-well-known-item-metadata.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
<LinkBase> looks like it's specific to SDK-style projects. Closing this one in favor of #2016.

**Comment by gewarren** [comment]
Related to dotnet/docs#2642.

**Comment by Mikejo5000** [comment]
@ghogen fyi, since there's a lot of doc issues around this. Not sure who is doing the work.
