### ISSUE TITLE
Change to Visual Studio Installer

### ISSUE THREAD

**Issue by GlennDOrr** [MicrosoftDocs/visualstudio-docs#1788]
The "Snapshot Debugger" is now under "Azure development" instead of "ASP.NET" and web development"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f13f80-a3b0-9602-db14-48130d47ef7c
* Version Independent ID: 96ee1b24-bc43-5e46-f645-f4ccfe9f1ba1
* Content: [Debug live ASP.NET Azure apps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-applications?view=vs-2017)
* Content Source: [docs/debugger/debug-live-azure-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-live-azure-applications.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@andysterland Andy, might this refer to the App Insights Snapshot Debugger? Or is our Snapshot Debugger under the Azure workload now?

**Comment by Mikejo5000** [comment]
Checking on this.

**Comment by Mikejo5000** [comment]
Updating doc
