### ISSUE TITLE
Expected Behavior Combining Multiple Rulesets

### ISSUE THREAD

**Issue by evshieh-msft** [MicrosoftDocs/visualstudio-docs#1795]
What's the expected behavior when combining multiple rulesets? For instance, if one ruleset ignores a rule while the other throws a warning, what will happen when the two are used together?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 546e8122-8074-7a9f-0ec5-de27f6c27637
* Version Independent ID: 827d1628-ecba-4f3f-51f2-0a5c9dd1424f
* Content: [Create a custom code analysis rule set in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-create-a-custom-rule-set?view=vs-2017)
* Content Source: [docs/code-quality/how-to-create-a-custom-rule-set.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-create-a-custom-rule-set.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@evshieh-msft Do you mean if you have a rule listed twice in the ruleset, with different behaviors, which one takes precedence?

**Comment by evshieh-msft** [comment]
@gewarren yes exactly!

**Comment by evshieh-msft** [comment]
@gewarren any updates on this?
