### ISSUE TITLE
(Exception from HRESULT: 0x80070057 (E_INVALIDARG))

### ISSUE THREAD

**Issue by leonelhs** [MicrosoftDocs/visualstudio-docs#1798]
just following the example when trying to add a command gets an error, it rises an exception  (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

**Comment by gewarren** [comment]
@leonelhs Can you provide a link to the page with the example you were following?

**Comment by leonelhs** [comment]
https://docs.microsoft.com/en-us/visualstudio/extensibility/extensibility-hello-world?view=vs-2017
![visixerrorr](https://user-images.githubusercontent.com/3288436/47878005-e0489280-dde2-11e8-8456-4da4f71a63bf.PNG)

**Comment by gregvanl** [comment]
Hi @leonelhs, I wasn't able to reproduce the issue. You might try repairing or upgrading your VS installation.

**Comment by gewarren** [comment]
@leonelhs Let us know if you're still facing this issue.
