### ISSUE TITLE
Mention commands

### ISSUE THREAD

**Issue by bugybunny** [MicrosoftDocs/visualstudio-docs#1800]
"In the Modules window (while debugging, choose Debug &gt; Windows &gt; Modules)" could be extended to include the default shortcut + name of the command (Ctrl+Alt+U, Debug.Module).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e04e717-61a6-99eb-60cd-34263fa597b5
* Version Independent ID: 3ee15675-d5bd-f3c9-fb85-1b65b3d71897
* Content: [How to: Debug .NET Framework Source - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-dotnet-framework-source?view=vs-2017)
* Content Source: [docs/debugger/how-to-debug-dotnet-framework-source.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-dotnet-framework-source.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks. I'll add that info.

**Comment by Mikejo5000** [comment]
Updating doc.
