### ISSUE TITLE
Explanation of different sized red dots

### ISSUE THREAD

**Issue by bugybunny** [MicrosoftDocs/visualstudio-docs#1801]
I noticed today that the red dots on the left side can have different sizes. For example in this code example
    class Program
    {
        public static void Main()
(1)    {
(2)        Console.WriteLine("foo");
        }
    }

(2) is the normal sized dot that most people will know I guess and (1) is a smaller dot. I guess it has to do with there being no command on this line. An explanation about that and if there may be other differences between sizes and why would be good somewhere in the article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use breakpoints in the Visual Studio debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2017)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-breakpoints.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, I'll take a look at this. Sometimes, it's tricky to catch every adjustment to icons, etc. when the product gets updated.

**Comment by bugybunny** [comment]
I just realized today that this comes from https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.SyntacticLineCompression that is bundled with https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProductivityPowerPack2017. So it’s nothing to be updated

**Comment by Mikejo5000** [comment]
@bugybunny Thanks for the follow up!
