### ISSUE TITLE
Primitive types identified as non serializable

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#1802]
In the above example, if you decorate the `Mouse` class with `SerializableAttribute`, you'll get a violation of this rule on the fields. If you change the implementation of the properties to auto-implemented properties, you'll get a violation of this rule on the properties.

Is that intended result?

If so, why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6530e4d7-de03-64c6-972e-f5c2482db82c
* Version Independent ID: 8900d6df-d062-0d77-1756-525a8b4bd9a9
* Content: [CA2235: Mark all non-serializable fields - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2235-mark-all-non-serializable-fields?view=vs-2017)
* Content Source: [docs/code-quality/ca2235-mark-all-non-serializable-fields.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2235-mark-all-non-serializable-fields.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Can you take a look at this question?

**Comment by mavasani** [comment]
@gewarren This looks like a bug in the FxCop analyzers implementation. Can we please port this issue to roslyn-analyzers? Thanks.

**Comment by gewarren** [comment]
@paulomorgado Can you log this issue at [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/issues) and comment here once you've done so? Thanks very much.

**Comment by paulomorgado** [comment]
Done! https://github.com/dotnet/roslyn-analyzers/issues/2381

**Comment by gewarren** [comment]
@paulomorgado Thank you so much!
