### ISSUE TITLE
MsBuild is no longer installed in the GAC

### ISSUE THREAD

**Issue by ViktorHofer** [MicrosoftDocs/visualstudio-docs#1804]
"MSBuild is no longer installed in the Global Assembly Cache. To reference MSBuild programmatically, use NuGet packages.". It would be great if you could instructions how to to this (i.e. vswhere) or link to another page that already explains this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb723883-dd62-0c53-8617-7bc867b9aaf3
* Version Independent ID: de1ff8ce-885c-9df0-077c-48c82f163c83
* Content: [What's New in MSBuild 15 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0?view=vs-2017)
* Content Source: [docs/msbuild/what-s-new-in-msbuild-15-0.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/what-s-new-in-msbuild-15-0.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Adding link to this topic:
https://docs.microsoft.com/en-us/visualstudio/msbuild/updating-an-existing-application?view=vs-2019
