### ISSUE TITLE
Hi, cannot install the 0.4.3 on latest 7.6 VS for Mac 

### ISSUE THREAD

**Issue by GermaniU** [MicrosoftDocs/visualstudio-docs#1806]
Hi, cannot install tfs version control 0.4.3 on latest 7.6 VS4mac.. 
apparently 0.4.3 requires 7.7 version... 
"dependencies not resolved: 
Core v7.7 
ide v7.7 
Version Control v7.7"

**Comment by asb3993** [comment]
Hi @GermaniU, Have you been able to update this to Visual Studio for Mac 7.7 and get it working?

Thanks
