### ISSUE TITLE
CA2202 - Finally Block

### ISSUE THREAD

**Issue by gmanbandit** [MicrosoftDocs/visualstudio-docs#1808]
Use null propagation in finally block. Replace "if" decision with...

stream?.Dispose();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836e7028-0bda-ef7c-fc11-4babb54ae70a
* Version Independent ID: 540dfe05-8e43-ed02-93d9-444c22485f84
* Content: [CA2202: Do not dispose objects multiple times - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2202-do-not-dispose-objects-multiple-times?view=vs-2017)
* Content Source: [docs/code-quality/ca2202-do-not-dispose-objects-multiple-times.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2202-do-not-dispose-objects-multiple-times.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@gmanbandit Yes you could write it that way too to save a line of code. I think that the way it's currently written is simpler to follow for developers that may not be familiar with the C# null propagation operator.
