### ISSUE TITLE
The VS for MAC unable to complete online installation in China

### ISSUE THREAD

**Issue by charliefr** [MicrosoftDocs/visualstudio-docs#181]
I've tried countless times，Unable to complete online installation in China。
Please provide offline installation packages

**Comment by mrward** [comment]
@charliefr - Would you be able to report his on the [Visual Studio for Mac forum](https://developercommunity.visualstudio.com/spaces/41/index.html) or file a bug on the [bug tracking system](https://bugzilla.xamarin.com)? Thanks.

**Comment by sailro** [comment]
cc @TerryGLee, we could close this issue. Thank you.

**Comment by TerryGLee** [comment]
Closed per request
