### ISSUE TITLE
/admin/doc/   error

### ISSUE THREAD

**Issue by timbryden** [MicrosoftDocs/visualstudio-docs#1815]
Just a heads up for 5.1.10 ... I had to add 
  'django.contrib.admindocs', 
to INSTALLED_APPS within settings.py to see the documentation page (and avoid an error).  But then the documentation page displayed...
The admin documentation system requires Python's docutils library.

Note: I am using Python 3.6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e07a-6d43-8800-fd06-be7f8ad21d20
* Version Independent ID: e6b188d8-adc0-cb16-cffa-63bfe2d3ecd4
* Content: [Tutorial - Learn Django in Visual Studio, step 5 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-05-django-authentication?view=vs-2017)
* Content Source: [docs/python/learn-django-in-visual-studio-step-05-django-authentication.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-05-django-authentication.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks. Can you clarify that you're referring to with v 5.1.10, exactly?

And if I understand you correctly, you're making the *documentation* link in the admin interface work correctly, not the admin interface overall. Is that right?

**Comment by kraigb** [comment]
@timbryden Can you again clarify what error you're referring to when you say "and avoid an error"? I'm also unsure that you mean by seeing a documentation page, because even if I add the app as you suggest, I don't see any changes on the running site. Thanks.

**Comment by timbryden** [comment]
Hi.  5.1.10 is just the section of the tutorial.  This discusses Admin.   The Admin piece works fine.

However when  I clicked on the Documentation link it errored as admindocs was not referenced until I added it.  I'm assuming it's meant to be there by default.

Finally I needed to pip install docutils in my Env environment to actually read the docs.
