### ISSUE TITLE
Linux Visual Studio Code use F11 to toggle Full Screen

### ISSUE THREAD

**Issue by invegat** [MicrosoftDocs/visualstudio-docs#1816]
Linux Visual Studio Code use F11 to toggle Full Screen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68544507-42a5-6364-b7e2-17115bd5c88d
* Version Independent ID: e588245e-c033-32a1-18b8-8bb81d7461fe
* Content: [Visual Studio full screen and virtual space mode - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-manage-editor-modes?view=vs-2017)
* Content Source: [docs/ide/how-to-manage-editor-modes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-manage-editor-modes.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gregvanl** [comment]
Hi @invegat You have found the GitHub repo for the Visual Studio documentation, not the VS Code documentation. You are correct that VS Code uses F11 to toggle full screen mode, but regular Visual Studio uses Alt+Shift+Enter as correctly documented.

**Comment by invegat** [comment]
Ok, Visual Studio code is different from Visual Studio Code
