### ISSUE TITLE
I updated VS community edition 2017 15.8.9 on 05-11-2018

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/visualstudio-docs#1817]
Just now  i installed  Visual Studio Community Edition 2017  15.8.9  on top of Visual Studio Community Edition 2017  15.8.4 .

First i downloaded Visual Studio Community Edition 2017 webinstaller from below website &gt;&gt;
https://download.visualstudio.microsoft.com/download/pr/221150da-35d1-45bf-9666-44bb9097fbaf/dd6bc2e5b597338cbd5b58cf1c678b58/vs_community.exe

and then i disabled antivirus and all firewall  applications , i  run  the "vs_community.exe"  with administrator rights ,  new page opened , i seen updates  available , i clicked on that , downloads started and then its  sucessfully updated  with 30 minutes because my ISP speed .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3386e-6b18-1cbd-9f1b-523b27b6521b
* Version Independent ID: 5ddf5e28-86d1-28b6-80ef-332bf93e17ac
* Content: [Update Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2017)
* Content Source: [docs/install/update-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@RAJU2529 Thanks for letting us know. It sounds like you experienced a successful installation. If there were problems with it, please see our support options in the "[Get support](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2017#get-support)" section of the [Update Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2017) page.
