### ISSUE TITLE
How to have visual studio full? (+ commands)

### ISSUE THREAD

**Issue by ddivito** [MicrosoftDocs/visualstudio-docs#1824]
Unfortunately Microsoft is not going to launch an .ISO image. What is the command that I must use to have all the Visual Studio components and all the third-party components?

Is this?:

vs_enterprise.exe --layout d: \ VS2017Layout --all --lang en-US

**Comment by TerryGLee** [comment]
@ddivito You can find an example of what you seek, here: [Command-line parameter examples: Using --includeRecommended](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017#using---includerecommended)
