### ISSUE TITLE
GUID

### ISSUE THREAD

**Issue by wschin** [MicrosoftDocs/visualstudio-docs#1826]
How to generate GUID? Where is doc for guidgen.exe? It can't be found by searching "guidgen" in this site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d2694da-4313-f535-16ff-a993214cf692
* Version Independent ID: 34db0e5f-e5da-7d18-6215-e4a6d33037a1
* Content: [Creating a Core Editor and Registering an Editor File Type - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-creating-a-core-editor-and-registering-an-editor-file-type?view=vs-2017)
* Content Source: [docs/extensibility/walkthrough-creating-a-core-editor-and-registering-an-editor-file-type.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-creating-a-core-editor-and-registering-an-editor-file-type.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
You can either use the VS IDE Tools > Create GUID command or guidgen.exe from the Developer Command Prompt for VS 2017

**Comment by wschin** [comment]
I know how to do that. The reason why I opened this issue is that by Goolgling for "GUID", I saw a bunch of people asking this question and I realize that doc site can't help them. There are also some 3rd packages written specifically for GUID, which should not happen if there is an easy doc.
