### ISSUE TITLE
Broken video link

### ISSUE THREAD

**Issue by andysinclair** [MicrosoftDocs/visualstudio-docs#1827]
The video link is not found:
"For a related video demonstration, see How do I: Manage task panes in Word VSTO Add-ins?."
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2daec754-1a5d-07ed-a047-00c8f815afa7
* Version Independent ID: e97b35c2-303f-27f0-8b3f-cd6075709ba2
* Content: [Custom task panes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/custom-task-panes?view=vs-2017#feedback)
* Content Source: [docs/vsto/custom-task-panes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/custom-task-panes.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@andysinclair Thanks for letting us know; this is on our backlog to fix.

**Comment by John-Hart** [comment]
this was fixed with PR #4101
#please-close
