### ISSUE TITLE
which type of encoding is  suitable for  .JSON file ?

### ISSUE THREAD

**Issue by RAJU2529** [MicrosoftDocs/visualstudio-docs#1834]
Which type of  encoding is  suitable,  while copied layout  commands and  saving as  layout.json 
1.ANSI
2.unicode
3.UTF-8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee82e78-02d5-bfe3-eb67-c69bdad01fa8
* Version Independent ID: 72f8b130-354d-a164-cb37-3d9b0b7cff19
* Content: [Automate Visual Studio installation with a response file - Visual Studio](https://docs.microsoft.com/en-in/visualstudio/install/automated-installation-with-response-file?view=vs-2017)
* Content Source: [docs/install/automated-installation-with-response-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/automated-installation-with-response-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@RAJU2529 @name For installation support requests, please consider using either our [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
