### ISSUE TITLE
Need to add 2024 for VS 2019

### ISSUE THREAD

**Issue by jsandersrocks** [MicrosoftDocs/visualstudio-docs#1836]
Need to add 2024 for VS 2019, this is enabled as a port in Azure App Services now and customers want to know what it is

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c19e4f-4623-c462-e399-008a85ea1523
* Version Independent ID: bc0b82bb-acc8-7438-7b18-5165de39d847
* Content: [Remote Debugger Port Assignments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugger-port-assignments?view=vs-2017)
* Content Source: [docs/debugger/remote-debugger-port-assignments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugger-port-assignments.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I'll plan to add it.

**Comment by Mikejo5000** [comment]
Adding this info
