### ISSUE TITLE
Feature not available?

### ISSUE THREAD

**Issue by stephenchill** [MicrosoftDocs/visualstudio-docs#1837]
The menu option "Generate Equals and GetHasCode..." does not show in the context menu when the class name is selected.  Is there a way to fix this for VS 2017 5.8.9?  Have the installed/uninstalled Refactoring extensions (Roslynator, etc.) destroyed this menu?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb48054-70fa-c5eb-748e-4db24ef64fd4
* Version Independent ID: 9ca41665-2e31-87da-4ba9-a8c60150db51
* Content: [Generate C# Equals and GetHashCode Method Overrides in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2017#see-also)
* Content Source: [docs/ide/reference/generate-equals-gethashcode-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-equals-gethashcode-methods.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@stephenchill I tried this out and it appears that the cursor has to be somewhere on the line that declares the type. The menu option doesn't appear if the cursor is elsewhere in the type, or if the type name is selected (double-click). Can you try that out and let me know if it works for you?

**Comment by stephenchill** [comment]
You are a dream!  I really had a lot of these overrides to do and this will
be a life saver.  My problem was the double-click as you pointed out.  I
don't know why I hadn't thought to try it but I've even gone to the trouble
of updating my Windows, Visual Studio and installing .Net core 2.1 on three
development machines..  But this was the trick so thanks again.

Steve

**Comment by gewarren** [comment]
Ha ha, thanks! I'll update the topic to be more explicit about that because it's confusing the way it's written.
