### ISSUE TITLE
Wrong wording

### ISSUE THREAD

**Issue by eparizzi** [MicrosoftDocs/visualstudio-docs#1838]
In the "Breakpoint Mappings" section where it says: 
"In Visual Studio, you cannot directly debug SERVER-side code, but you can set a breakpoint in a SERVER-side file." -- I guess it should say client-side code, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36553c7f-23dc-e3bf-821d-55e2c415b47a
* Version Independent ID: cca0433d-2d55-93c6-533c-3458cf455e3a
* Content: [Client-Side Script Debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/client-side-script-debugging?view=vs-2017)
* Content Source: [docs/debugger/client-side-script-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/client-side-script-debugging.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@eparizzi This topic is in need of a refresh. Yes, that should be client-side. There are some differences between app types, and some different ways to debug client-side script. Are you working with a ASP.NET or Node.js app, or some other app type? This topic is currently oriented for ASP.NET.

**Comment by Mikejo5000** [comment]
Closing this for now as the work is currently out of scope.
