### ISSUE TITLE
The start menu path

### ISSUE THREAD

**Issue by HekiShavik** [MicrosoftDocs/visualstudio-docs#1839]
The start menu path will look like this: 
%appdata%\Microsoft\Windows\Programs\{Publisher}\{Product name}.appref-ms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7db85d2b-3cc1-3c20-ebfc-4e5253706f86
* Version Independent ID: 0514187a-f39e-80f2-296d-807babb40694
* Content: [How to: Specify a Start Menu Name for a ClickOnce Application - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-specify-a-start-menu-name-for-a-clickonce-application?view=vs-2017)
* Content Source: [docs/deployment/how-to-specify-a-start-menu-name-for-a-clickonce-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-specify-a-start-menu-name-for-a-clickonce-application.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@HekiShavik Thanks! I'll add that info.

**Comment by Mikejo5000** [comment]
Adding the path to topic.
