### ISSUE TITLE
Step 6 doesn't tell you what assemblies are to be added

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/visualstudio-docs#184]
In the section **Creating a Custom Template Wizard** at step 6 where it implements the code for the WizardImplementation class, the last thing step 6 says is:

> This example adds a parameter value from the user input form to the Dictionary<TKey, TValue> parameter. Every instance of the $custommessage$ parameter in the project will be replaced with the text entered by the user. You must add the following assemblies to your project:

And that's it. There's no listing of any assemblies to add, even though the instructions say that you **must** add them.

**Comment by gewarren** [comment]
It looks like [this section](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates#creating-a-custom-template-wizard) is rendering correctly now:

This example adds a parameter value from the user input form to the Dictionary<TKey,TValue> parameter. Every instance of the $custommessage$ parameter in the project will be replaced with the text entered by the user. You must add the following assemblies to your project: System and System.Drawing.

**Comment by gewarren** [comment]
@Rod-in-NM sorry this wasn't rendering correctly before, and thanks for reporting it.

**Comment by Rod-in-NM** [comment]
Thank you very much for getting the documentation updated and letting me know about it!!
