### ISSUE TITLE
[TFS + VSMac] Version Control Plugin 0.4.3.2 error

### ISSUE THREAD

**Issue by Abhijit-Revamp** [MicrosoftDocs/visualstudio-docs#1844]
The latest Update 0.4.3.2 shows dependency error while installing. See the attached error image

<img width="831" alt="tfs-err4" src="https://user-images.githubusercontent.com/44320018/48313099-b3b02a00-e5dd-11e8-80a1-95b3a27360a5.png">

**Comment by gewarren** [comment]
@Abhijit-Revamp Thanks for reporting this error, however this is not the correct avenue to do that. Please report it over at [Developer Community](https://developercommunity.visualstudio.com/content/problem/post.html?space=41).
