### ISSUE TITLE
Support restricted environments - How to do this if the VSTO redistributable is not found on the machine?

### ISSUE THREAD

**Issue by demyte** [MicrosoftDocs/visualstudio-docs#1846]
A pre-requisite for a VSTO addin is the VSTO runtime which requires admin level to install - how do we get around this to keep the addin "Support restricted environments"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c5fc31-985e-b4c4-c036-78d38156ad54
* Version Independent ID: 83fe159c-6e3f-63e5-1a52-728782b51e5c
* Content: [Development best practices for COM, VSTO, and VBA add-ins in Office - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/development-best-practices-for-com-vsto-and-vba-add-ins-in-office?view=vs-2017)
* Content Source: [docs/vsto/development-best-practices-for-com-vsto-and-vba-add-ins-in-office.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/development-best-practices-for-com-vsto-and-vba-add-ins-in-office.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@John-Hart FYI

**Comment by John-Hart** [comment]
@demyte the VSTO runtime will also be installed with Office. If Office is already installed on the machine the runtime should be available.

**Comment by demyte** [comment]
@John-Hart 

Thanks for the response.

Our installer checks the following registry key to get the version of VSTO and if it is not there or it is there but a lower version than the runtime we need, we prompt to install it for our users:

`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VSTO Runtime Setup\v4R`

We find that even if Office (2010/2013/2016) is installed, this registry key is not there.

Is there a different way we should be detecting the VSTO runtime?

**Comment by John-Hart** [comment]
@demyte depending on how VSTO runtime is installed you may find the version under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VSTO Runtime Setup\v4

This Stackflow discussion has some good information: https://stackoverflow.com/questions/2799941/how-to-determine-if-vsto-2010-runtime-is-installed
