### ISSUE TITLE
add colors for icons in the Solution Explorer!

### ISSUE THREAD

**Issue by ericbl** [MicrosoftDocs/visualstudio-docs#1863]
The current icons in the solution explorer for the code analyser rules is not easy to see.
For better visibility, it would be better to get colors as in the dedicated editor (blue for info, yellow for warning, red for error)!
Could we get that in a next iteration of Visual Studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Use and configure Roslyn analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2017)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ericbl Thanks for the feedback and suggestion. Can you please log your suggestion over at the new [Suggest a Feature page on Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8) instead of here in the documentation feedback?

**Comment by ericbl** [comment]
suggestion added in 
https://developercommunity.visualstudio.com/idea/385034/visual-studio-solution-explorer-analysers-colorize.html#

**Comment by gewarren** [comment]
@ericbl Thanks for following up. I'll close this issue then.
