### ISSUE TITLE
CodeAnalysisRuleSet within PropertyGroup 

### ISSUE THREAD

**Issue by ericbl** [MicrosoftDocs/visualstudio-docs#1864]
please complete how to use CodeAnalysisRuleSet is the project file, its actually requires the PropertyGroup tag around, e.g.

 &lt;PropertyGroup&gt;
    &lt;CodeAnalysisRuleSet&gt;{mypath}\{mybasic.ruleset}&lt;/CodeAnalysisRuleSet&gt;
  &lt;/PropertyGroup&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f961b0d-0ef1-f507-d8ad-626903a9d848
* Version Independent ID: e2ef819f-6c68-4776-cd36-499ca7661d85
* Content: [Code analysis rule sets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2017)
* Content Source: [docs/code-quality/using-rule-sets-to-group-code-analysis-rules.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/using-rule-sets-to-group-code-analysis-rules.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ericbl I'll take a look at this and update the topic as necessary.
