### ISSUE TITLE
 Application Configuration File in vs 2017

### ISSUE THREAD

**Issue by viskri-msft** [MicrosoftDocs/visualstudio-docs#1865]
I can't find Application Configuration File / Visual C# items under installed. I am on VS 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f03b50b-74c7-2e0e-ff49-eb747d887979
* Version Independent ID: 7aff7001-a1ac-6088-4b19-94b5e870c709
* Content: [How to add an app.config file to a project in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-app-config-file?view=vs-2017)
* Content Source: [docs/ide/how-to-add-app-config-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-add-app-config-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@viskri-msft Have you installed the **Windows desktop development** workload for VS?

**Comment by gewarren** [comment]
@viskri-msft Please comment if you are still encountering an issue. I'm closing this for now.

**Comment by minhtam-nguyennhat** [comment]
@gewarren What exactly the component is called ?
