### ISSUE TITLE
Give example usage of Directory.Build.targets

### ISSUE THREAD

**Issue by sy-github** [MicrosoftDocs/visualstudio-docs#1866]
Can you expand Directory.Build.targets above to give example usage? What types of targets are suitable in it? At what stage is it called?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6f7f1d-2f33-e083-f8de-1ecd9f1a4a93
* Version Independent ID: 8aac17e8-5a10-bbbb-4c52-783c9f0c7e10
* Content: [MSBuild .Targets Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-dot-targets-files?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-dot-targets-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-dot-targets-files.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Doc is missing a link to more info in Customize your build article. Adding link.
