### ISSUE TITLE
VistualStudio Profiler DLL Paths in Visual Studio 2017

### ISSUE THREAD

**Issue by akerd** [MicrosoftDocs/visualstudio-docs#1877]
For Visual Studio 2017 the DLL paths are the following:
32-bit: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\Microsoft.VisualStudio.Profiler.dll
64-bit: c:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\Microsoft.VisualStudio.Profiler.dll

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 600aa596-eb13-980a-76a5-215c9c1352ca
* Version Independent ID: 50651218-3f4e-167b-2a44-d1acb7e5ff4f
* Content: [Walkthrough: Using Profiler APIs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/walkthrough-using-profiler-apis?view=vs-2017)
* Content Source: [docs/profiling/walkthrough-using-profiler-apis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/walkthrough-using-profiler-apis.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@akerd Thanks! I'll take a look at that.

**Comment by Mikejo5000** [comment]
Updating
