### ISSUE TITLE
Update Visual Studio default values for "silent" severity

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#1878]
dotnet/roslyn#27220 changed some Visual Studio default values to the "silent" severity. This should be reflected in the documentation.

Some examples of properties that now have the wrong default severity in the documentation:

- dotnet_style_parentheses_in_*
- dotnet_style_predefined_type_for_*
- dotnet_style_prefer_auto_properties
- (Most likely more)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@kendrahavens Any chance you can update this article with the new default values?

**Comment by kendrahavens** [comment]
Sure. @sharwell, Is there a complete list  ([or commit](https://github.com/dotnet/roslyn/pull/27220/commits/24888acc6a293b881190a8db904207094cbb4bfc)) I should work from?

**Comment by tonyhallett** [comment]
@ cremor @kendrahavens @sharwell There are others as well from that pull that was merged 11 Jun.  The files src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs and src/Workspaces/CSharp/Portable/CodeStyle/CSharpCodeStyleOptions.cs contain the defaults.

Additional defaults with severity to silent:

csharp_style_expression_bodied_constructors
csharp_style_expression_bodied_methods
csharp_style_expression_bodied_operators
csharp_style_expression_bodied_properties
csharp_style_expression_bodied_indexers
csharp_style_expression_bodied_accessors
csharp_preferred_modifier_order
csharp_prefer_braces
dotnet_style_require_accessibility_modifiers

**Comment by sharwell** [comment]
@kendrahavens I believe everything that was `none` changed to `silent` as the default

**Comment by gewarren** [comment]
@sharwell I [changed all the defaults that were 'none' to 'silent'](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/4358/files). This includes some rules that weren't explicitly listed in this issue, including:

- dotnet_style_qualification_for*
- dotnet_style_prefer_conditional_expression_over*
- csharp_style_var*

Is that correct?

**Comment by gewarren** [comment]
These changes will go live tomorrow.
