### ISSUE TITLE
how to use '$'

### ISSUE THREAD

**Issue by anh76qn** [MicrosoftDocs/visualstudio-docs#1880]
in my code snippet have character '$', how to use it ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c7c36c-84d9-9237-3d78-689e76d080f9
* Version Independent ID: 6584735a-e8db-429d-5427-687fc709e6f8
* Content: [Walkthrough: Create a code snippet - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2017)
* Content Source: [docs/ide/walkthrough-creating-a-code-snippet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-creating-a-code-snippet.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by JoseRaul1991** [comment]
You need to create a NoEditable Literal
<Literal Editable="false">
	<ID>dollar</ID>
	<ToolTip>$</ToolTip>
	<Default>$</Default>
</Literal>
...
and then use it inside ![CDATA[ like this:
...
_logger.LogError($dollar$"Failed to get by id:{id}");

**Comment by JoseRaul1991** [comment]
this is an example https://www.screencast.com/t/QGEWmqEgyf

**Comment by gewarren** [comment]
@JoseRaul1991 Thanks for providing a solution.

**Comment by ThiloE** [comment]
Thanks, @JoseRaul1991!
Just a remark: Take care to insert the <Literal> element inside the <Snippet> element.
