### ISSUE TITLE
No mention of schema versions

### ISSUE THREAD

**Issue by kwbskf** [MicrosoftDocs/visualstudio-docs#1881]
When dealing with intellisense warnings about invalid elements while editing a project file, I notice that the schema is http://schemas.microsoft.com/developer/msbuild/2003, but I'm using VS2010.  Surely VS2010 can understand a more recent version, right?  But I've sought for schema version info here and cannot find any.  It would be nice to show which versions of the schema are understood by different versions of MSBuild or Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73afcd0b-3717-082a-e429-428bfac1c826
* Version Independent ID: 7f6f3bd1-c584-6a63-513d-a541db4e585c
* Content: [MSBuild Project File Schema Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-project-file-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-project-file-schema-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, do you have any suggestions for this one? Thx.

**Comment by rainersigwald** [comment]
The date in that schema identifier is a regrettable choice. It is expected to say 2003 for the rest of time. Changes to the allowed project elements are documented in the individual element documentation pages--MSBuild is not actually representable via XML Schema, so any formal XSD is necessarily incomplete.
