### ISSUE TITLE
Documentation fails to provide all settings specifications

### ISSUE THREAD

**Issue by DanRegalia** [MicrosoftDocs/visualstudio-docs#1882]
I have a solution built and tested with Outlook (Office 2016/365).
When I try to run it on a machine with Office 2013 installed, I get the error:
"You cannot debug or run this project because the required version of the Microsoft Office"
This document has no troubleshooting or examples or exact requirements posted beyond general information.  Could you please post more detailed settings instructions?  Thanks.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c81ef68-355f-a059-91fa-904a7979ae48
* Version Independent ID: 777a14e8-58e0-f08a-116f-315f8f1aa86f
* Content: [Run solutions in different versions of Microsoft Office - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/running-solutions-in-different-versions-of-microsoft-office?view=vs-2017)
* Content Source: [docs/vsto/running-solutions-in-different-versions-of-microsoft-office.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/running-solutions-in-different-versions-of-microsoft-office.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@DanRegalia Thanks for letting us know; this is in the backlog to fix. @John-Hart, FYI.

**Comment by John-Hart** [comment]
This document is a simple list of the various version of Office, VSTO runtime and .NET framework for a running VSTO app.  @DanRegalia, it sounds like the error you mentioned is actually coming from Visual Studio and it simple means either Office 2013 or Office 2016 was not installed on the same machine
