### ISSUE TITLE
Examples with all parameters

### ISSUE THREAD

**Issue by Alan-d** [MicrosoftDocs/visualstudio-docs#1884]
Please give examples that use all the parameters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c98183-151e-7f93-8463-34518c030861
* Version Independent ID: 36e2369d-f5cd-2024-f235-68b13aa2d7bf
* Content: [CallTarget Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/calltarget-task?view=vs-2017)
* Content Source: [docs/msbuild/calltarget-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/calltarget-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Good idea, but this work is currently out of scope. Closing for the time being.
