### ISSUE TITLE
Update Solution deletes files

### ISSUE THREAD

**Issue by elahshalev** [MicrosoftDocs/visualstudio-docs#1897]
Is there a way to get the local machine's last version of a solution after clicking "Update Solution" with version control?

**Comment by gewarren** [comment]
@KathrynEE Any idea on this one?

**Comment by cartermp** [comment]
Not sure if this is a label yet, but `area-source control` feels like the most appropriate one here.

**Comment by msebolt** [comment]
@elahshalev  The only way is by using git:

- check `stash` to see if any local changes were saved
- try `git reflog` (see specifics [here](https://forums.xamarin.com/discussion/6579/git-update-overwrote-all-my-code-and-deleted-new-files/p2))
- try ` git fsck` (see specifics [here](https://stackoverflow.com/questions/2780402/how-to-restore-files-that-were-removed-by-git))

If you'd like to file this as a bug, please use the [VisualStudio forums](https://developercommunity.visualstudio.com/spaces/41/index.html).
