### ISSUE TITLE
How many votes does each person get? Is that tracked by the email address that is tied to their Visual Studio Subscription? 

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/visualstudio-docs#1898]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-dev15**
* GitHub Login: @seiyer
* Microsoft Alias: **seiyer**

**Comment by dburnison** [comment]
To clarify, does this mean I can vote on each feature suggestion just once but, I can vote on an unlimited number of feature suggestions?

**Comment by seaniyer** [comment]
Yes, that is correct.
