### ISSUE TITLE
visual studio installer

### ISSUE THREAD

**Issue by rismoney** [MicrosoftDocs/visualstudio-docs#190]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md

all references here to `--lang` I believe should be `--addProductLang`

**Comment by TerryGLee** [comment]
Thanks for your comment; we'll investigate and respond soon.

**Comment by rismoney** [comment]
I think it actually is Lang unless you are not using /layout.
very confusing...

**Comment by tedvz** [comment]
Actually, the documentation in this case is correct.  Actually, when using --layout you can use --lang or --addProductLang.  But, as rismoney points out, if not using --layout you must use --addProductLang.
