### ISSUE TITLE
devenv options list is incomplete

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/visualstudio-docs#1903]
It does not include:
/NoVSIP	        Disables the VSIP developer's license key for VSIP testing.
/sqldbaction    Start SQL Server Data Tools and perform the action specified in the argument string. 
/TfsLink	        Opens Team Explorer and launches a viewer for the provided artifact URI if one is registered.

/rootsuffix        For launching other instances

And possibly more....?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05945d0a-396b-0697-ab78-81d617b365c9
* Version Independent ID: 860cb1bf-47aa-b35d-4d30-be9f62796d40
* Content: [Visual Studio devenv command line switches - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2017)
* Content Source: [docs/ide/reference/devenv-command-line-switches.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/devenv-command-line-switches.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mrlacey Thanks for the feedback. I'll check whether these options should be documented or not.

**Comment by Regenhardt** [comment]
Would be nice to have this. I automatically start dev command prompt in powershell with a scirpt, and would like to echo the VS version in case of several VS installations active.

**Comment by robotdad** [comment]
/Updateconfiguration is also missing. If the command is valid it should be documented, valid commands should not be selectively undocumented. I'd also add that devenv /? should list all commands or provide a link to this article for more info.

**Comment by gewarren** [comment]
We recently updated the devenv switches articles - see https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2017 and https://docs.microsoft.com/en-us/visualstudio/extensibility/devenv-command-line-switches-for-vspackage-development?view=vs-2017. @DennisLee-DennisLee can provide more insight into why we did or didn't add specific options, if you still feel that something's still missing.
