### ISSUE TITLE
Dokumentation link to the use of  resource file for icon and manifest

### ISSUE THREAD

**Issue by PeterPann23** [MicrosoftDocs/visualstudio-docs#1907]
Please provide a link to the format that is needed for the res file that holds manifest and icons and application version. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db2f3877-b9ea-1ee4-b4ab-ec146139cf5b
* Version Independent ID: b9e98d4e-1053-4ac3-f1f0-a31c12e72f6f
* Content: [Application page of C# project properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/application-page-project-designer-csharp?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(cs.ProjectPropertiesApplication);k(SolutionItemsProject);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.2)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/ide/reference/application-page-project-designer-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/application-page-project-designer-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@PeterPann23 Is this the kind of info you're looking for? https://docs.microsoft.com/en-us/windows/desktop/menurc/about-resource-files

**Comment by PeterPann23** [comment]
Yes, kinde hoped to see some samples of how to format it to get say 2 or more icons in the file and use it in a .net project
