### ISSUE TITLE
Pluralsight Subscription Changes

### ISSUE THREAD

**Issue by willydavidjr** [MicrosoftDocs/visualstudio-docs#1909]
[The Pluralsight subscription on this content was 3 months. Upon checking my Visual Studio account, it now goes down to 1 month only. ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e41abd-81dd-4dd2-d2d2-6bc513ad9e48
* Version Independent ID: 911d149e-8d78-b552-12a2-b061e2c1f41c
* Content: [Pluralsight Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-pluralsight)
* Content Source: [subscriptions/vs-pluralsight.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-pluralsight.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@willydavidjr -- Thank you for reaching out.  The Pluralsight offer has changed from three months to one month for new activations.  If you claimed the benefit and created your account with Pluralsight while the 3-month offer was in place, you will still have the three months of access from the time you created the account.

**Comment by TerryGLee** [comment]
@willydavidjr Thanks for your follow-up. I see that the Pluralsight offer was changed to one month in a table of editions that includes Visual Studio Dev Essentials. @evanwindom Does this change apply only to that edition or all editions?

**Comment by artemis15** [comment]
It is changed, Now it does not offer free subscription.

**Comment by mgadirocks** [comment]
Even for Enterprise Level Subscription of Visual Studio, Pluralsight Free subscription is not offered now?

**Comment by evanwindom** [comment]
@artemis15 , @mgadirocks - Thanks for reaching out.  What type of subscriptions are you using?  If you connect to https://my.visualstudio.com, what type of subscription is displayed in the blue banner at the top of the page?

Pluralsight is not currently available through Dev Essentials.  The Dev Essentials program works with a variety of partners to bring exclusive benefits to our members. These exclusive benefits are offered with a limited quantity and some benefits run out quicker than others. The goal is to ensure there's enough to meet the demand, but we often don't have a say in the quantity available.
We've reached out to Pluralsight to discuss expanding this offer to more members and doing everything we can to make this benefit available again soon.

Pluralsight should still be available to the same Enterprise subscribers as before.  (It is not included in the monthly cloud subscriptions, or some of the programs such as MPN, MCT, BizSpark, Imagine, etc.)  If you believe you're using an Enterprise subscription that includes Pluralsight, please let me know what type of Enterprise subscription you're using so we can investigate for you.

**Comment by srinivasadnt3** [comment]
As part of Visual studio dev essentials popup content i see it  says "Online courses from Pluralsight, Xamarin University and more" is available but once i confirm and go to the page. I am not able to see Pluralsight subscription available there? Can you confirm if this program is completely removed?

**Comment by willydavidjr** [comment]
@srinivasadnt3 Unfortunately, Pluralsight is not available on Visual Studio Dev Essentials. You can see the eligibility list [here](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-pluralsight).

![image](https://user-images.githubusercontent.com/20619236/65759248-14d8e180-e14d-11e9-8739-ad1a9e338c72.png)

Here are the only list available currently for Visual Studio Dev Essentials program:

![image](https://user-images.githubusercontent.com/20619236/65759312-3afe8180-e14d-11e9-8c64-bdcf20e6c6d9.png)

**Comment by evanwindom** [comment]
@srinivasadnt3 - When you say "Visual studio dev essentials popup content", what content do you mean?  Where are you seeing it?
