### ISSUE TITLE
erroneous reference to .vb source files under Text Editor - C#, Advanced options

### ISSUE THREAD

**Issue by jibal** [MicrosoftDocs/visualstudio-docs#1911]
The section on outlining of .vb source files is misplaced in the C# options section; it should refer to .cs files.

Also, a lot of the C# options in VS 2017 are not documented on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41602f7-2c5e-bf2a-9eab-50740dd10784
* Version Independent ID: c6b1f7c4-eb2d-a62a-7e1b-eb32b8a88947
* Content: [Options, Text Editor, C#, Advanced - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?view=vs-2017)
* Content Source: [docs/ide/reference/options-text-editor-csharp-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-advanced.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This has been fixed.
