### ISSUE TITLE
correct "Package designer options" -> "Deployment Server Type"

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/visualstudio-docs#1926]
Docs under "Package designer options" seem to be wrong. 
The property seems not to be required and the default seems to be "WebFrontEnd".
Also, please specify what implications this property has.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c1570c27-001b-130f-e581-451c32dd8386
* Version Independent ID: 42166a8a-c563-85e8-736a-052cc2e6ed05
* Content: [Creating SharePoint Solution Packages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/sharepoint/creating-sharepoint-solution-packages?view=vs-2017)
* Content Source: [docs/sharepoint/creating-sharepoint-solution-packages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/sharepoint/creating-sharepoint-solution-packages.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
Thanks for letting us know; this is in the backlog to fix. @John-Hart, FYI.

**Comment by John-Hart** [comment]
The document has been updated
