### ISSUE TITLE
Documented certificate file names have changed and are not correct starting with Visual Studio 2017 version 15.8

### ISSUE THREAD

**Issue by ManuelRin** [MicrosoftDocs/visualstudio-docs#1927]
The certificate file names documentation in Option 3 (https://docs.microsoft.com/en-us/visualstudio/install/install-certificates-for-visual-studio-offline?view=vs-2017#option-3---install-certificates-as-part-of-a-scripted-deployment-of-visual-studio) is outdated for Visual Studio 2017 version 15.8 and above. The file names have changed. The documentation doesn't reflect these changes.

Certificate file names up to Visual Studio 2017 version 15.7:
manifest**Sign**Certificate**s**.cer
manifestCounterSignCertificate**s**.cer
vs_installer_opc.**Sign**Certificate**s**.cer

Actual certificate file names starting with Visual Studio 2017 version 15.8:
manifest**Root**Certificate.cer
manifestCounterSign**Root**Certificate.cer
vs_installer_opc.**Root**Certificate.cer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e4bce72-0471-4ff0-6948-671f2e1f9f9f
* Version Independent ID: 3a255b89-a741-5bcc-4342-e4e4943197e1
* Content: [Install certificates required for Visual Studio offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-certificates-for-visual-studio-offline?view=vs-2017)
* Content Source: [docs/install/install-certificates-for-visual-studio-offline.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-certificates-for-visual-studio-offline.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ManuelRin Thanks for letting us know. @frayus Can you verify? Then, we can get the page updated accordingly.

**Comment by ScottHutchinson** [comment]
I sure wish you had fixed this. It ruined my installation DVD, which I now have to burn again.

This script that worked for me is:

certmgr.exe -add Offline\certificates\manifestCounterSignRootCertificate.cer -s -r LocalMachine root
certmgr.exe -add Offline\certificates\manifestRootCertificate.cer -s -r LocalMachine root
certmgr.exe -add Offline\certificates\vs_installer_opc.RootCertificate.cer -s -r LocalMachine root

**Comment by TerryGLee** [comment]
@ScottHutchinson Thanks for your input, and apologies for the inconvenience this caused. @tydunkel @tedvz FYI.

**Comment by tydunkel** [comment]
@ManuelRin Thank you for filing this issue! We will be updating the documentation to reflect these changes. Sorry for any confusion this may have caused.

**Comment by TerryGLee** [comment]
@tydunkel Thanks for reviewing this issue; the requested updates to the documentation will be published by mid-morning tomorrow.
