### ISSUE TITLE
New update of Visual Studio 15.9.1 highlights code in green for C26496 warning

### ISSUE THREAD

**Issue by marcobeninca71** [MicrosoftDocs/visualstudio-docs#1928]
A code C++ file with no USE_CONST_FOR_VARIABLE define highligth some line of code in green giving C26496 warning
After closing and reopening the file no more green highligth is shown

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b377dac2-9bdf-acb5-bb87-7572adbc6c40
* Version Independent ID: 60f966b9-7a8d-b27f-2de3-e50618fe2040
* Content: [C26496 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26496?view=vs-2017)
* Content Source: [docs/code-quality/c26496.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26496.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gewarren** [comment]
@sunnychatterjee Could you take a look at this feedback?

**Comment by WilliamAntonRohm** [comment]
@marcobeninca71 -- Marco, thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
