### ISSUE TITLE
Commandline example is an image and the copy button doesn't do anything.

### ISSUE THREAD

**Issue by stansw** [MicrosoftDocs/visualstudio-docs#1929]
This is an image and it is ridiculous because the image has a button that does noting. Instead of telling me to go there and click the button just give me a package name in a text so that I can copy it. I tried to copy it form the image before I read that this is just an example.

![](https://docs.microsoft.com/en-us/visualstudio/code-quality/media/nuget-install-command.png?view=vs-2017)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa028191-ecee-41ce-530c-263ada533515
* Version Independent ID: b43c95f9-90aa-8b15-7a5d-20f31b80d410
* Content: [Install Roslyn analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-roslyn-analyzers?view=vs-2017#feedback)
* Content Source: [docs/code-quality/install-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-roslyn-analyzers.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@stansw Thanks for the feedback. I can see why this might be confusing. I'll remove the image and replace it with copyable example text.

**Comment by rocifier** [comment]
This is quite an amusing problem. It may be better to just link to a few commonly used packages on nuget. Nuget keeps their package versioning information realtime, which would mean we wouldn't have to go back and update package version numbers. Having more than one example would also continue to show the page doesn't favour one particular package over another.
