### ISSUE TITLE
Does Documentation Installation in Offline Environment Supported ?

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftDocs/visualstudio-docs#1933]
Creating Offline Installation Layout with Documentation
Does Documentation Installation in Offline Environment Supported ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@IrakliLomidze Are you referring to our [Help Viewer documentation](https://docs.microsoft.com/en-us/visualstudio/ide/microsoft-help-viewer?view=vs-2017)? If so, the "[Deploy pre-installed local Help content on client computers](https://docs.microsoft.com/en-us/visualstudio/ide/help-viewer-administrator-guide?view=vs-2017#deploy-pre-installed-local-help-content-on-client-computers)" section of our Help Viewer Administrator Guide might prove useful to you.

**Comment by RaviRathod492** [comment]
Will the "Download all, then install feature" save the downloaded files at a specific location(for reuse and creating iso) or they will get deleted after downloading ?

**Comment by TerryGLee** [comment]
@RaviRathod492 The "download all, then install" feature will save temporarily (to a temp folder), so it's designed to use one time and  guarantees only that your installation will not start before everything is downloaded. If you need to download Visual Studio and then install later or to a different machine, your best option is to create a layout by using command-line options.

**Comment by IanKemp** [comment]
@TerryGLee I assume that the "Download all, then install" is essentially calling `vs_community.exe --layout %temp% --lang <language> --add <workload1> [--add <workloadN> ...]`.

If so, could another option be added (something like "Download all to specified folder, then install" which just pops up a folder chooser dialog, then runs `vs_community.exe --layout <folder chosen by user> --lang <language> --add <workload1> [--add <workloadN> ...]`?

That would save users from having to run *anything* from the command-line, and would also mean it's no longer necessary for users to know and specify the IDs of every component they want to install.

**Comment by SelmaI** [comment]
@IanKemp, 
the 'Download all, then install' is not calling the layout command. Instead, it's using a sequential approach to our default (parallel download and install) mechanism. 

If I am interpreting your ask correctly, you would like use the create a layout and install from it, but use the installer interface, or make the commandline options more streamlined. If so, we have a suggestion ticket https://developercommunity.visualstudio.com/idea/390526/gui-for-layoutoffline-installer-download.html at our developer community, please feel free to vote as well as comments there. 

Thanks,
Selma
