### ISSUE TITLE
Database Project Context

### ISSUE THREAD

**Issue by PrometheusRising1** [MicrosoftDocs/visualstudio-docs#1935]
It would be extremely helpful to have a version of these documents with .sql and publish.xml profiles as examples.  A great deal of building and maintaining ALM for business intelligence projects (.dacpac, .ispac, etc.) is poorly documented when it comes to continuous integration and even basic builds.  Since data projects are supposed to be the focus of the future, it would really help if there was better documentation on how to treat database and data projects as version controlled/DevOps projects.  While Azure's analytical and big data components may be handled differently (and I know that Microsoft wants to promote these for the future), there will always be a need to integrate on-premises code projects for SQL Server, Integration Services, and Analysis Services in a version-controlled, continuously deployed manner.  Please update or add documentation that treats the topic from this perspective.

**Comment by gewarren** [comment]
@PrometheusRising1 Are you referring to these topics about data-tier applications? https://docs.microsoft.com/en-us/sql/relational-databases/data-tier-applications/data-tier-applications?view=sql-server-2017

Or these ones about database projects? https://docs.microsoft.com/en-us/sql/ssdt/project-oriented-offline-database-development?view=sql-server-2017
