### ISSUE TITLE
Incorrect cleaning example

### ISSUE THREAD

**Issue by akochepasov** [MicrosoftDocs/visualstudio-docs#1937]
The command in the clean example cannot find the archive catalog: 
c:\VS2017Layout\vs_enterprise.exe --layout c:\VS2017Layout --clean c:\VS2017Layout\Archive\1cd70189-fc55-4583-8ad8-a2711e928325\Catalog.json --clean c:\VS2017Layout\Archive\d420889f-6aad-4ba4-99e4-ed7833795a10\Catalog.json

It should be as follows (tested on vs_enterprise 15.8.28010.2046):
c:\VS2017Layout\vs_enterprise.exe --layout c:\VS2017Layout --clean Archive\1cd70189-fc55-4583-8ad8-a2711e928325\Catalog.json --clean Archive\d420889f-6aad-4ba4-99e4-ed7833795a10\Catalog.json

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc51a257-b7a9-4660-7e12-88cdfcd9cd53
* Version Independent ID: dad2fd97-7244-6802-e853-5d5974838996
* Content: [Update a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2017#how-to-remove-older-versions-from-a-layout)
* Content Source: [docs/install/update-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@akochepasov Thanks for letting us know; we'll look in to this. @tedvz FYI.

**Comment by TerryGLee** [comment]
@tydunkel FYI.

**Comment by TerryGLee** [comment]
@akochepasov This is under investigation; we will either have some input that we can add to this GitHub Issue, or updates to the [Update a network-based installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2017#how-to-remove-older-versions-from-a-layout) page, soon.

**Comment by tydunkel** [comment]
@akochepasov I could not reproduce the issue using the latest vs_enterprise.exe from the web. Can you confirm if this is still an issue?

Command line used:
`vs_enterprise.exe --layout C:\vslayout --clean  "C:\vslayout\Archive\578027b7-bfa3-49b3-9045-c8d022150d55\Catalog.json"`

This then loaded the catalog and prompted if I wanted to remove the obsolete payloads.

**Comment by TerryGLee** [comment]
@akochepasov We haven't heard back from you re: the inquiry from our engineering partner, @tydunkel. We'll close this now, but if it's still an issue for you, please let us know. 

Thanks,
~ Terry

**Comment by akochepasov** [comment]
@TerryGLee I've met a few significant issues in VS2017 in 2018 to understand that this version is not ready to be deployed offline (1st time while uninstalling, it deleted WinSDK, which was along VS2015, 2nd time it bluescreened the whole windows so that I had to throw away this windows image and reinstall everything). It may be fixed now, but let me wait till VS2019, which is on the way. Thanks for closing it.
