### ISSUE TITLE
What are the defaults for these switches?

### ISSUE THREAD

**Issue by jimmcslim** [MicrosoftDocs/visualstudio-docs#1938]
It would be handy to know what the defaults for these switches are; particularly the -consoleloggerparameters and -verbosity switches.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
Verbosity has a default of "Normal".

**Comment by rainersigwald** [comment]
And consoleloggerparameters follows the overall verbosity (so defaults to normal) and includes a Summary.

**Comment by ghogen** [comment]
Updated the command line topic to add the default for verbosity and /clp.
