### ISSUE TITLE
IntelliTrace supports attach.

### ISSUE THREAD

**Issue by kceiw** [MicrosoftDocs/visualstudio-docs#194]
The IntelliTrace document (https://docs.microsoft.com/en-us/visualstudio/debugger/intellitrace) has a note that "If you want to debug a process that is already running, you can't use IntelliTrace. You must start IntelliTrace when the process starts. "

Actually, you still can attach to the process. If the process is one of the supported (including limited supported) application and IntelliTrace is enabled in tools options, IntelliTrace will start collecting data for that process. Note that events before IntelliTrace attaches won't be able to be collected. And IntelliTrace will only collect events. That means, if you turn on collecting events and calls information from tools options, IntelliTrace still collect events only.
Also note that remote debugging isn't supported. IntelliTrace attach only support 32bit and 64bit application on the local machine.

**Comment by Mikejo5000** [comment]
Thanks! Fixed and will be publishing soon.
