### ISSUE TITLE
Typo 'System.Diagnosis.CodeAnalysis.SuppressMessage' .. should be '...Diagnostics...'

### ISSUE THREAD

**Issue by glenn-slayden** [MicrosoftDocs/visualstudio-docs#1941]
A typo on this page: 'System.Diagnosis.CodeAnalysis.SuppressMessage' .. should be '...Diagnostics...'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963d8d4a-0021-e10a-3a72-358eadced263
* Version Independent ID: 688674ea-4fc0-8d1e-9895-b5f096e80ff1
* Content: [Static code analysis for managed code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-overview?view=vs-2017)
* Content Source: [docs/code-quality/code-analysis-for-managed-code-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-for-managed-code-overview.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@glenn-slayden Thanks for catching this. We'll get it fixed!
