### ISSUE TITLE
Dead Link in Ribbon Documentation

### ISSUE THREAD

**Issue by prasadgl** [MicrosoftDocs/visualstudio-docs#1943]
In the link https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/ribbon-xml.md under the section **Assign callback methods to controls**, there is a link in the text "_For a complete list of the callback method signatures for Ribbon controls, see the technical article Customize the Office (2007) Ribbon user interface for developers (Part 3 of 3)_".  The link is giving a 404.  Please connect to the appropriate content.

**Comment by gewarren** [comment]
[This is the article](https://docs.microsoft.com/en-us/visualstudio/vsto/ribbon-xml?view=vs-2017#assign-callback-methods-to-controls) with the link, but the link works for me. @prasadgl can you try again to see if it was a transient 404?
