### ISSUE TITLE
Create a Python extension for C#...?

### ISSUE THREAD

**Issue by blueincmultimedia** [MicrosoftDocs/visualstudio-docs#1946]
This and the mixed-mode debugging articles are superb; thanks!
Is it possible to create something similar but using Csharp as the base and Python as the extension? 
Here's what I mean: I'm delveloping an AddIn for ArcGISPro. Perviously, in my python addin for ArcGIS 10.6, I use a great method to handle code changes on the fly: I use the regular python addin code (let's call it the 'pythonButtonWrapper') to:
- import a pythonModule.function code that runs when a particular button is clicked;
- 'recompile' that pythonModule code on the fly and;
- handle the button clicks, telling the pythonModule code what button was clicked.
The pythonModule code then takes over execution. It works great. Because I recompile the pythonModule code on the fly, I can code the functionality into the pythonModule code and never have to touch the pythonButtonWrapper. It never changes (unless of course I add new buttons, etc).

ArcGISPro uses Csharp for its addin code and I can generate a 'CsharpButtonWrapper' for it. 
My question: how can I preserve the same functionality, calling my PYTHON module code functions from the 'CsharpButton Wrapper' that I get with VS 2017, passing in the button clicks? The last thing I want to do is translate all of the python module's code functionality into C#! Note: I've found lots of oneline example code that calls python.exe from C# but that's not what I want to do. I need access to the python module functions themselves, likely through a module.dll(?)
Thanks in advance for your helpful response,
Brian

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Working with C++ and Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2017)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@blueincmultimedia Great question! I can't say I know enough to advise you here (the docs repo), however.

I suggest that you instead open this question in the PTVS repo, https://github.com/Microsoft/ptvs/issues, where you'll get you in touch with the engineers who understand much more about embedding Python into other language environments. (The docs you refer to here are about calling C++ *from* Python, but there's also ways to be calling Python from C++, and so I imagine there's a way to do that from C# even if it means creating an intermediate layer in C++.)

Do @ mention me in the issue you open, so I can track it and see if there's anything to surface in the docs (the part I own). I'm closing this docs repo issue in the meantime.

Thanks!
