### ISSUE TITLE
IntelliTrace is also in VS 2017

### ISSUE THREAD

**Issue by kceiw** [MicrosoftDocs/visualstudio-docs#195]
The IntelliTrace documentation (https://docs.microsoft.com/en-us/visualstudio/debugger/intellitrace) states that:

>  You can save IntelliTrace data from these sources:
>         An IntelliTrace session in Visual Studio 2015 Enterprise or previous versions of Visual Studio Ultimate.
> 
> 

IntelliTrace is also in Visual Studio 2017 Enterprise.

**Comment by Mikejo5000** [comment]
Thanks. Making fixes
