### ISSUE TITLE
Inappropriate title

### ISSUE THREAD

**Issue by ajventi** [MicrosoftDocs/visualstudio-docs#1955]
This is a nice article to give an overview of Blend, but the title is quite misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb4a86d-efe1-3ff6-2456-eac6659c6d09
* Version Independent ID: a1faa99b-0e1a-8291-f87c-747dcccb3b0b
* Content: [Creating a UI by using Blend for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/creating-a-ui-by-using-blend-for-visual-studio?view=vs-2017)
* Content Source: [docs/designers/creating-a-ui-by-using-blend-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/creating-a-ui-by-using-blend-for-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ajventi Thanks for the feedback, and I agree. Do you think something like "Overview of Blend for Visual Studio" would be more appropriate?

**Comment by ajventi** [comment]
Absolutely, thanks for your response, and efforts.
