### ISSUE TITLE
VSPerfCmd.exe CrossSession example is incorrect

### ISSUE THREAD

**Issue by jludden** [MicrosoftDocs/visualstudio-docs#1956]
Hi all - I appreciate the effort going into these docs. However, I noticed an issue looking at  [CrossSession.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/crosssession.md), a switch used in VSPerfCmd.exe. The example given is :

`VSPerfCmd.exe /Start:Sample /Output:TestApp.exe.vsp /CrossSession`  
`VSPerfCmd.exe /Attach:12345 /CS  `

However, when I try it (with an appropriate PID) the second command fails:

> Error VSP1311: Incompatible switch usage. Switch START is required with switch CROSSSESSION. Aborting.

**Comment by gewarren** [comment]
Topic is here: https://docs.microsoft.com/en-us/visualstudio/profiling/crosssession?view=vs-2019.

Reassigning this to Mike.

**Comment by Mikejo5000** [comment]
This doc, and sampling via the legacy performance explorer command-line tools, is removed in Visual Studio 2019, so closing this as low priority.
