### ISSUE TITLE
Unclear where to use this code.

### ISSUE THREAD

**Issue by H35am** [MicrosoftDocs/visualstudio-docs#1957]
Please provide some background information about how and where to use this code, maybe a example project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fca93cc7-67e9-c5a7-814f-2d7ca58fd391
* Version Independent ID: 3306c5f1-8247-1f00-c374-cd9269eba550
* Content: [How to: Programmatically add shapes to a Visio document - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-add-shapes-to-a-visio-document?view=vs-2017)
* Content Source: [docs/vsto/how-to-programmatically-add-shapes-to-a-visio-document.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-add-shapes-to-a-visio-document.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@H35am Thanks for letting us know; this content set is in our backlog to update. @John-Hart, FYI.

**Comment by Auvite** [comment]
Example would be great. This is quite hard to understand without example source.

**Comment by YigalB1** [comment]
I also think a real example, that works, is required.

**Comment by John-Hart** [comment]
@H35am this is just a code snippet that you could place anywhere in your VSTO VISIO add-in.  For example, you could place this code in a button click on a form.  A good place to start is looking through the [Getting Started Programming VSTO Add-ins document](https://docs.microsoft.com/en-us/visualstudio/vsto/getting-started-programming-vsto-add-ins?view=vs-2017)
