### ISSUE TITLE
[Web perf tests] Obsolete properties

### ISSUE THREAD

**Issue by bigian** [MicrosoftDocs/visualstudio-docs#1958]
In your example you are using the RuleName and RuleDescription Properties these have been obsolete since at least 2012

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bc9cd67-df12-fcf9-9e1c-f12d8abadbe8
* Version Independent ID: f6dbfb88-ca36-fc5a-4dc2-977d3739eb5a
* Content: [Coding a custom extraction rule for a web performance test in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/code-a-custom-extraction-rule-for-a-web-performance-test?view=vs-2017)
* Content Source: [docs/test/code-a-custom-extraction-rule-for-a-web-performance-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/code-a-custom-extraction-rule-for-a-web-performance-test.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@bigian Thanks for the feedback!

**Comment by gewarren** [comment]
Given that web performance tests are deprecated, we are not planning to update this documentation at this time. If you'd like to suggest an edit (there's an Edit button near the top right of the page), please feel free to.

**Comment by MarkMcGee1** [comment]
It looks like this issue has been addressed, so I am closing this. Thanks!
