### ISSUE TITLE
IntelliTrace doesn't collect file access events by default

### ISSUE THREAD

**Issue by kceiw** [MicrosoftDocs/visualstudio-docs#196]
The IntelliTrace document (https://docs.microsoft.com/en-us/visualstudio/debugger/intellitrace) mistakenly states that IntelliTrace collects file access events by default. Actually it's not. Users can enable that though.

> .NET Framework events
> By default, IntelliTrace records the most common .NET Framework events. For example:
> For a File Access event, IntelliTrace collects the file name.

**Comment by Mikejo5000** [comment]
Thanks! Fixed and will be publishing soon.
