### ISSUE TITLE
Can't  Figure out this line

### ISSUE THREAD

**Issue by VivekKPatel** [MicrosoftDocs/visualstudio-docs#1962]
Open the Visual Studio command prompt, and then change directories to the c:\publish\Application Files\ExcelWorkbook_MostRecentPublishedVersion folder (for example, c:\publish\Application Files\ExcelWorkbook_1_0_0_4).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 367b3af3-0c14-753c-9eca-26fc41ff4769
* Version Independent ID: a4c5941c-a60e-5258-aaed-3fed333febf8
* Content: [Deploy an Office solution by using ClickOnce - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-an-office-solution-by-using-clickonce?view=vs-2017)
* Content Source: [docs/vsto/deploying-an-office-solution-by-using-clickonce.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/deploying-an-office-solution-by-using-clickonce.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@VivekKPatel Thanks for letting us know; this content set is in our backlog to update. @John-Hart, FYI.

**Comment by ucheNkadiCode** [comment]
Updated the document to be slightly more clear that c:/publish is a CREATED FOLDER for this example and not a folder that is supposed to already be present on the user's computer

**Comment by ucheNkadiCode** [comment]
#sign-off
