### ISSUE TITLE
Document Level Addin

### ISSUE THREAD

**Issue by vivek-nodes** [MicrosoftDocs/visualstudio-docs#1963]
How to Set Custom Action Explain in this https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-an-office-solution-by-using-windows-installer?view=vs-2017#to-add-a-custom-action-that-runs-your-program Section using visual studio Installer

 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 283a3669-9f0e-c872-028d-9eac66fc221b
* Version Independent ID: bdfea87a-3b7d-80ef-51f2-ceadb1ba26bb
* Content: [Deploy an Office solution by using Windows Installer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-an-office-solution-by-using-windows-installer?view=vs-2017)
* Content Source: [docs/vsto/deploying-an-office-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/deploying-an-office-solution-by-using-windows-installer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@VivekKPatel Thanks for letting us know; this content set is in our backlog to update. @John-Hart, FYI.

**Comment by John-Hart** [comment]
Please see the updated document: https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2019
