### ISSUE TITLE
How can this be done for a WEB SITE PROJECT now?

### ISSUE THREAD

**Issue by mkamoski** [MicrosoftDocs/visualstudio-docs#1969]
How can this be done for a WEB SITE PROJECT now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30273668-658c-d411-5b6d-7f58256bb0f3
* Version Independent ID: c8812ae3-0fb1-a30f-02dd-ebc2d28b9dc8
* Content: [How to: Exclude Files from the Build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-exclude-files-from-the-build?view=vs-2017)
* Content Source: [docs/msbuild/how-to-exclude-files-from-the-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-exclude-files-from-the-build.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mkamoski  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
