### ISSUE TITLE
Does "Download all then install" support saving files at particular location or accessing them for reuse?

### ISSUE THREAD

**Issue by RaviRathod492** [MicrosoftDocs/visualstudio-docs#1972]
Can i have access to those downloaded files like downloading files from command lines so that it can be used for future usage?

**Comment by TerryGLee** [comment]
@RaviRathod492 The "download all then install" feature will save temporarily (to a temp folder), so it's designed to use one time and  guarantees only that your installation will not start before everything is downloaded. If you need to download Visual Studio and then install later or to a different machine, your best option is to create a layout by using command-line options.
