### ISSUE TITLE
.NET Framework 2.0 references could be misunderstood

### ISSUE THREAD

**Issue by Dave-Lowndes** [MicrosoftDocs/visualstudio-docs#1974]
Where this mentions ".NET Framework 2.0", presumably it really means ".NET Framework 2.0 or later"?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f3ceb02-4221-a0ba-455e-a6b6e3e767b9
* Version Independent ID: 0c03be05-0295-5705-cbd9-56b42f0a7b3e
* Content: [CA1820: Test for empty strings using string length - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1820-test-for-empty-strings-using-string-length?view=vs-2017)
* Content Source: [docs/code-quality/ca1820-test-for-empty-strings-using-string-length.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1820-test-for-empty-strings-using-string-length.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Dave-Lowndes Thanks for noticing this, and yes you are correct. I'll get it updated.
