### ISSUE TITLE
"Sdk" attribute is not documented

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/visualstudio-docs#1976]
The Sdk attribute hasn't been documented, see: https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2017 for usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af512ce8-46bd-b15a-c5a2-f8315d2b258a
* Version Independent ID: e2c221b8-466f-df7f-078c-bab89be71828
* Content: [Import Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017)
* Content Source: [docs/msbuild/import-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/import-element-msbuild.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by MarkMcGee1** [comment]
I submitted a fix in PR [3226](https://github.com/MicrosoftDocs/visualstudio-docs/pull/3226), thanks for reporting this.
