### ISSUE TITLE
I am not able to step into scikit-learn functions

### ISSUE THREAD

**Issue by wschin** [MicrosoftDocs/visualstudio-docs#1977]
F11 is not working for me. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f46b5339-857e-3398-c654-97bd9757ea44
* Version Independent ID: ed197ab6-8b08-2d23-d8b5-5a85eedda590
* Content: [Working with Python Tutorial, Step 4, debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-04-debugging?view=vs-2017)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-04-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-04-debugging.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
The Step Into feature works only when you have the source code for the function you're stepping into. By default, expect Step Into to work only for code in your own project or code in a library that's implemented in Python and not C/C++. In the case of scikit-learn, those libraries are likely implemented in C++ and so you cannot step into them using the Python debugger. It is possible to do so, however, if you use Python/C++ mixed-mode debugging and have the scikit-learn symbols present on your computer. For more information on that debugging mode, see https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2017 and https://docs.microsoft.com/en-us/visualstudio/python/debugging-symbols-for-mixed-mode-c-cpp-python?view=vs-2017. 

I don't know if symbols are available for scikit-learn; you'll need to check its repo, https://github.com/scikit-learn/scikit-learn.

**Comment by wschin** [comment]
The problem is that pycharm works perfectly for me. I am honestly a pycharm user because of this.

**Comment by kraigb** [comment]
Be sure to include that point in an issue files for PTVS; the engineering team will want to know that.
