### ISSUE TITLE
This help text is missing crucial information

### ISSUE THREAD

**Issue by niderost** [MicrosoftDocs/visualstudio-docs#1979]
I select "Attach to Process" to start debugging an existing project. Then I would like to select the code type. The dialog box shows me a lot of options whose purpose isn't very clear for a non-experienced user of the debugger:
* GPU - Software Emulator
* JavaScript (Chrome DevTools Protocol)
* Managed (CoreCLR)
* Managed (Native compilation)
* Managed (v3.5, v3.0, v2.0)
* Managed (v4.6, v4.5, v4.0)
* Native
* Node.js Debugging
* Script
* T-SQL
* WebKit
* Workflow
* Managed Compatibility Mode

The meaning of some of the code types I can guess. Also, some I can search for on the Internet and find an answer. However, some of the options seem redundant: there are 5 different "Managed" options, 3 script-like options, 2 options with "native" in the name and one "workflow"option where it's unclear what workflow technology is meant. Also, it seems to me that sometimes, multiple options should be enabled simultaneously for certain debugging scenario's. So I need more precise information.

Pressing the Help button only shows this rather generic help text. The See Also links don't provide any more detailed information on the different options I can select. Clarifying these options in this help text would be very useful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f459c09e-facc-32b1-084c-e2d780907db1
* Version Independent ID: 82358346-df35-3bde-bb6e-d6920a2f3671
* Content: [Select Code Type Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/select-code-type-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.selectengines)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/debugger/select-code-type-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/select-code-type-dialog-box.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, I'll take a look at this.

**Comment by MarcHWR** [comment]
Please also include information on how the automatic determination of the code type works and how or if one can influence it in cases where the code type is detected wrong. That would be a great help.

**Comment by Mikejo5000** [comment]
Updating doc for VS 2019. Adding links to troubleshooting info as well.
