### ISSUE TITLE
No link to tools

### ISSUE THREAD

**Issue by weloytty** [MicrosoftDocs/visualstudio-docs#1980]
I was looking for a download link for the remote tools for VS2017, and it took a bit of googling before I found the right answer on stackoverflow.  Can we add a link to the tools here?

https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2017

I know they move links around to mess with people, but maybe this one will stay static.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 730d6782-df15-d7b3-4b71-744cf85cf3b9
* Version Independent ID: 1faf359b-4729-db8e-3ee7-841e3972fa39
* Content: [IntelliTrace - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/intellitrace?view=vs-2017)
* Content Source: [docs/debugger/intellitrace.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/intellitrace.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@weloytty Your scenario is using IntelliTrace on a remote machine? Are you trying to use features like the standalone collector, or just standard IntelliTrace? Thx!

**Comment by weloytty** [comment]
Oh, I use the standalone collector a lot, I always have a hard time finding it though.  I am getting a server ready to deploy, and I wanted to make sure I had the latest and greatest collector.  I guess I commented too fast, as I don't have a question or need clarification, I just needed to find the download site.

**Comment by Mikejo5000** [comment]
OK, I needed to make sure what tool you were talking about here. I can take a look at this. Thx!

**Comment by Mikejo5000** [comment]
Links to tools on this page were outdated:
https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-intellitrace-stand-alone-collector?view=vs-2017#BKMK_Install_the_IntelliTrace_Stand_Alone_Collector
Updating this page. It's best if we keep the links in one place.
The IntelliTrace overview already links to this page, so that page appears to be OK.
