### ISSUE TITLE
full path must be less than 80 chars

### ISSUE THREAD

**Issue by nickbeagley** [MicrosoftDocs/visualstudio-docs#1982]
Might be worth noting that the full install path has to be less than 80 characters for installation to work otherwise it drops out with a complaint.  If you are hosting the offline install on a network share, don't put it too deep. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@nickbeagley Thanks for letting us know! We'll investigate and report back.

**Comment by tydunkel** [comment]
@nickbeagley Thanks for the feedback! As you noted, it is a known condition in the installer that the layout path needs to be less than 80 characters. @TerryGLee this should be doc feedback to add this information to the [layout documentation](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017).

**Comment by TerryGLee** [comment]
@tydunkel Thanks for answering the inquiry; I've updated the pages requested, which should go live by mid-morning tomorrow.
