### ISSUE TITLE
Missing topic for CA2007 DoNotDirectlyAwaitATaskAnalyzer as well.

### ISSUE THREAD

**Issue by sshukurov** [MicrosoftDocs/visualstudio-docs#1983]
Could not find anything on this warning, but the latest FxCopAnalyzers yields it on my project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f935929-e6b1-d110-4d2f-8a4150a27755
* Version Independent ID: d4c2d5fd-b9e3-85fd-7d21-22cdb8c06f9d
* Content: [Visual Studio Code Analysis Warnings for Managed Code by CheckId - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-warnings-for-managed-code-by-checkid?view=vs-2017)
* Content Source: [docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This topic is now available: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007-do-not-directly-await-task?view=vs-2017
