### ISSUE TITLE
ts-loader, webpack and webpack-cli not loading

### ISSUE THREAD

**Issue by krunal29385** [MicrosoftDocs/visualstudio-docs#1984]
Hi,

I am using VS 2017 version 15.9.2 and Node.js v10.14.0. I refer your steps from below URL
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2017
But when I tried to add ts-loader, webpack and webpack-cli from install missing package its not installed.

Please let me know how can I install it. 
I also attached screenshot for the same.
![nodereact-error](https://user-images.githubusercontent.com/10114810/49215671-509d0080-f3ef-11e8-9aa4-de902aab2b1a.PNG)
 
Thanks in advance..

**Comment by Mikejo5000** [comment]
It may be that the versions specified in package.json are out of date. This has probably been fixed in an update (i.e., the versions of those npm packages updated in package.json). But if not, you can right-click the npm node, choose Install package, and install each npm package separately.
