### ISSUE TITLE
Documentation layout broken

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#1986]
The layout of the table in the section "Download the Visual Studio bootstrapper" is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@cremor Thanks for letting us know! We'll take a look and get it fixed.

**Comment by TerryGLee** [comment]
@cremor We have a PR in the queue to fix this formatting error; it'll be published Monday 12/3. Thanks again for reporting it.
