### ISSUE TITLE
Misleading comment

### ISSUE THREAD

**Issue by schibu007** [MicrosoftDocs/visualstudio-docs#1987]
This comment is misleading:
&lt;!-- Path relative to solution directory --&gt;
It's not the solution directory but the directory where the *.runsettings file lies.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This relates to the 6th line of the example .runsettings file.

**Comment by MarkMcGee1** [comment]
I submitted a fix in https://github.com/MicrosoftDocs/visualstudio-docs/pull/3224, thanks for reporting this.
