### ISSUE TITLE
Outdated Documentation?

### ISSUE THREAD

**Issue by Saulzi** [MicrosoftDocs/visualstudio-docs#1988]
Does this document need to be updated to include Jest (https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32738a06-835b-5bd5-7a6c-942c681aca97
* Version Independent ID: e715d12c-a4aa-eec3-c05f-1ff6243d209b
* Content: [Unit testing in Node.js - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2017#feedback)
* Content Source: [docs/javascript/unit-testing-javascript-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/unit-testing-javascript-with-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Saulzi I'll need to look into this.

**Comment by Mikejo5000** [comment]
Updating doc
