### ISSUE TITLE
Outdated Documentation?

### ISSUE THREAD

**Issue by Saulzi** [MicrosoftDocs/visualstudio-docs#1989]
Does this documentation need to be updated to include Jest (https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fdc4321-1bc2-215a-7696-c25bb6e5bf04
* Version Independent ID: 13350cc1-b3f5-f01d-44c8-18dd1019ae22
* Content: [Write JavaScript code in Visual Studio without a solution or project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/develop-javascript-code-without-solutions-projects?view=vs-2017)
* Content Source: [docs/javascript/develop-javascript-code-without-solutions-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/develop-javascript-code-without-solutions-projects.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I'll ask about it

**Comment by armanio123** [comment]
@Mikejo5000 We have added Jest support in release 15.9. It needs to be added to the list of supported frameworks.

**Comment by Mikejo5000** [comment]
@armanio123 OK, thanks, I'll add it to the list

**Comment by Saulzi** [comment]
Could it please be noted that the jest support does not work in TypeScript due to how tests are discovered.

**Comment by Mikejo5000** [comment]
@Saulzi Do you mean that the tests are not discovered? Can you be more specific?

**Comment by Saulzi** [comment]
They are not discovered when file is typescript but are when using javascript, this is because of how the 'glue' code for the new out of process testing works (https://github.com/Microsoft/nodejstools/blob/abe9726ef173b8d5546aa90e8735f190f679ddd8/Nodejs/Product/TestAdapter/TestFrameworks/Jest/jest.js). 

Basically you are using the jest-editor-support package in the test discovery. (this means that you need to have this in your package.json or it will not detect tests in javascript code, does it need to be documented? as a pre-req?) unfortunately this npm package will not work with typescript files as it cannot strip types / traverse ast to find tests.

Perhaps a solution like chutzpah does for discovering tests may be required i.e. run jest and parsing output for discovery / running as this will have less dependencies.

One more point
likewise I have noticed in the 2019 documentation the following statement

'We have added support for enabling JavaScript debugging within unit tests in Node.js projects'
(https://docs.microsoft.com/en-gb/visualstudio/releases/2019/release-notes#jsts)

Is this javascript only or is running nodejs with sourcemaps also supported?

**Comment by Saulzi** [comment]
it does say about tests being compiled in test root to js (on existing documentation), jest is a bit of a funny one here as it can transpile typescript itself using babel7 or the ts-jest plugin before running tests..

**Comment by Mikejo5000** [comment]
@Saulzi OK, thank you @armanio123 For now, it seems I should include a caveat that jest is only supported in javascript, and that you need to include jest-editor-support npm package? That correct?

Also, see Saulzi's last question about using sourcemaps with JS unit tests. Thanks!

**Comment by Saulzi** [comment]
may sound stupid but note source maps are in the context of debugging unit tests written in typescript

**Comment by armanio123** [comment]
Thanks for the details @Saulzi, TypeScript is supported in jest tests as well because Visual Studio first transpiles the files and then discovers test. By then `jest-editor-support` is able to find the test since now is a JavaScript file. I wasn't aware that jest is able to transpile through babel. It might be worth checking how can we implement this so that we remove one dependency.

Debugging is supported through sourcemaps and it should work on your jest tests.

**Comment by Saulzi** [comment]
More information overload below

Please see https://jestjs.io/docs/en/getting-started#using-typescript, I am currently using ts-jest 
for transpilation for testing as it gives type / javascript errors as part of the test output. using jest with babel wont do this and the suggestion is to give the typescript compiler the noemit option and only use it for type checking here.

Previously we used chutzpah with jasmine using requirejs to load modules into the browser / phantomjs for testing but due to the large amount of tests for the frontend of the application to do a full test run would take over 30 mins (this is less than a min when running through jest and required little changes to get running). This was also somewhat flaky if there was a error in one of the files / loading a file as that suite would not run / get discovered. 

My current solution is to use vs-code to run jest tests with tasks to allow debugging tests in node and launching the application attached to chrome, this is far from ideal as there currently I have found no nice way to debug individual scenarios within a module, I have to run all of the tests in the current module.

@armanio123 have you seen the new Vuejs templates in visual studio, out of the box when creating a typescript application the noemit flag is specified in the typescript compiler. I don't think that this is a uncommon scenario, likewise it is also common to compile source to different folder.

Our solution is similar to this, for development we watch all of the source files and emit them as AMD modules to a different folder which the browser can load in this way we get quick feedback without having to rebuild a lot of stuff (we have legacy / third party javascript alongside typescript source which is moved to this location), for deployment we then bundle / minify these artefacts as barrels and load functionality on demand.

**Comment by Saulzi** [comment]
I thought that I would give you an update on getting test discovery to work.

I managed to get some some of the tests written in typescript to be discovered although they will not run (spinner spins forever) in Visual Studio 2019 / 2017 by making the following changes to my solution. 

Moved package.json to top of project and set options in project file to ./ and Jest. (would not work pointing at source subfolder)
Changed tsconfig to emit files alongside source as discovery only seems to support this scenario, 
Changed module type to UMD so that it can be used in both node and the browser.
Changed jest config to run tests using emitted UMD rather than using ts-jest.

Please note that it only discovered 1304 (in project) +285 (in external?) out of 2046. note that this is just the core of the application.
The test hierarchy is somewhat incorrect in visual studio.

**Comment by armanio123** [comment]
That doesn't sounds right. I suggest to file an issue in in https://github.com/Microsoft/nodejstools/ and share your project, or a project that reproduces if possible. That would make things much easier.

**Comment by Saulzi** [comment]
Note that documentation at https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2017 is still missing jest.

I am in currently creating a list of issue's that I have with your current jest integration and I will put that onto the nodejs tools repo and link here with some examples in another repo on github.

**Comment by Saulzi** [comment]
note that the documentation at https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2017 does not say that jest is supported.

**Comment by Saulzi** [comment]
as discussed examples etc can be found in this ticket https://github.com/Microsoft/nodejstools/issues/2140

**Comment by Mikejo5000** [comment]
Updating doc
