### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by gernotpokorny** [MicrosoftDocs/visualstudio-docs#199]
Source: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-creating-a-code-snippet.md

> 7. To test the shortcut, open a Visual Basic project and open a code file. Type hello in the file and press TAB. The snippet code should be inserted.

should be

7. To test the shortcut, open a Visual Basic project and open a code file. Type hello in the file and press **two times** TAB. The snippet code should be inserted.

---------------

Source: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-distribute-code-snippets.md

> In the Add New Asset dialog, set the Type to Microsoft.VisualStudio.VsPackage, the Type to File on filesystem, and the Path to HelloWorldVB.pkgdef (which should appear in the dropdown).

should be 

In the Add New Asset dialog, set the Type to Microsoft.VisualStudio.VsPackage, the **Source** to File on filesystem, and the Path to HelloWorldVB.pkgdef (which should appear in the dropdown).

(based on vs2017)

Source: https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference

> The Assembly element is only supported by Visual Basic code snippets.

> The Reference element is only supported for Visual Basic projects.

> The References element is only supported for Visual Basic projects.

That's not correct. C# also supports the References-element, Reference-element and Assembly-element

**Comment by gewarren** [comment]
@gernotpokorny thanks, I will get this fixed.
