### ISSUE TITLE
Download links under "Official distributions" are broken links

### ISSUE THREAD

**Issue by cpatulea** [MicrosoftDocs/visualstudio-docs#1991]
For example for 2.7.6 the link target is:
  https://www.org/ftp/python/2.7.6/python-2.7.6-pdb.zip

it should be:
  https://www.python.org/ftp/python/2.7.6/python-2.7.6-pdb.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a28d662-7af8-e0cc-dc6c-b300d22eb16d
* Version Independent ID: 61410436-ef1f-6858-618d-c3a2da35309a
* Content: [Symbols for mixed-mode Python/C++ debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-symbols-for-mixed-mode-c-cpp-python?view=vs-2017#official-distributions)
* Content Source: [docs/python/debugging-symbols-for-mixed-mode-c-cpp-python.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/debugging-symbols-for-mixed-mode-c-cpp-python.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
These have been corrected by community contributions.
