### ISSUE TITLE
Table markdown is not rendered well 

### ISSUE THREAD

**Issue by junjiequ** [MicrosoftDocs/visualstudio-docs#1992]
Table markdown is not rendered well here on the html page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485faedb-302a-5b6c-8a5b-d9dc4bedfbd2
* Version Independent ID: d236f0a6-2bcb-2cdd-de7d-522dfc4b6dde
* Content: [Deploy an ASP.NET Docker container to Azure Container Registry (ACR) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/docker/vs-azure-tools-docker-hosting-web-apps-in-docker?view=vs-2017)
* Content Source: [docs/docker/vs-azure-tools-docker-hosting-web-apps-in-docker.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/docker/vs-azure-tools-docker-hosting-web-apps-in-docker.md)
* Service: **azure-container-service**
* Product: **visual-studio-dev15**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by gewarren** [comment]
@junjiequ Thanks for letting us know! This should be an easy fix.

**Comment by ghogen** [comment]
This is fixed now, @junjiequ -- thanks for reporting this issue
