### ISSUE TITLE
Missing word in Note section

### ISSUE THREAD

**Issue by akeeton** [MicrosoftDocs/visualstudio-docs#1994]
"This means that if you create a user control that uses a property of the Globals class from inside a user control class, you must **&lt;missing word&gt;** whether the property returns null before you try to use the returned object."  Maybe it's supposed to be "check?"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b8a8724-a3da-2972-ce83-af76692bedfe
* Version Independent ID: 24f4c46c-bd9d-c731-2dc0-d8f9cfb4601f
* Content: [Global access to objects in Office projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/global-access-to-objects-in-office-projects?view=vs-2017)
* Content Source: [docs/vsto/global-access-to-objects-in-office-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/global-access-to-objects-in-office-projects.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@akeeton Thanks for letting us know; this content set is in our backlog to update. @John-Hart, FYI.

**Comment by John-Hart** [comment]
this was fixed with PR #4106
#please-close
