### ISSUE TITLE
Youtube playlist for C++ using Visual Studio 2017 

### ISSUE THREAD

**Issue by krchome** [MicrosoftDocs/visualstudio-docs#1998]
Here is the playlist:
https://www.youtube.com/watch?v=WorTYNFNV8Q&list=PLnVvOWNfuhGXpRfzT_AgShA4JQYMNoQUr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89847656-bea8-b9a7-a50a-3d7e75e14ff6
* Version Independent ID: 9f6c1029-6d5b-1d41-10dd-65863848c2e5
* Content: [Get started with C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2017)
* Content Source: [docs/ide/getting-started-with-cpp-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/getting-started-with-cpp-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @corob-msft
* Microsoft Alias: **tglee**

**Comment by SyntaxC4** [comment]
@krchome Would you be able to expand on the intent of your youtube link? Do you think there are elements of our documentation which could be improved upon which is covered in these videos?

**Comment by gewarren** [comment]
@SyntaxC4 This issue is locked so the OP won't be able to comment. Feel free to unlock if you think it's warranted.
