### ISSUE TITLE
Suppressing Multiple Violations within a method body

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/visualstudio-docs#200]
In the document [In Source Suppression Overview](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/in-source-suppression-overview.md), under the section "Suppressing Multiple Violations within a method body" it is stated:

> Attributes can only be applied to a method and cannot be embedded within the method body. **However, you can specify the identifier as the message ID to distinguish multiple occurrences of a violation within a method.**

Emphasis mine.

The code examples  show MessageId being set to the name of a method parameter and to the returning type of a method, but it doesn´t really show multiple occurences of a (same) violation nor does the document state what constitutes a valid identifier for message ID or anything else.

For instance, given the following code:

```        
UserStore<IdentityUser> CreateUserStore()
{
    IdentityDbContext<IdentityUser> context = null;
    UserStore<IdentityUser> userStore = null;
    try
    {
        context = new IdentityDbContext<IdentityUser>();
        userStore = new UserStore<IdentityUser>(context) { DisposeContext = true };

        context = null;

        return userStore;
    }
    finally
    {
        if (context != null)
        {
            context.Dispose();
        }
    }
}
```
I tried using `context` as a identifier on MessageId to separate this occurence of a CA2000 from the one below on `userStore` ...
```
[SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", 
    MessageId = "context")]
```

But it doesn't seem to have any effect on FxCop which keeps reporting an occurrence for `context`.

**Comment by gewarren** [comment]
@alfredmyers thanks I own these topics now so i'll take a look.

**Comment by gewarren** [comment]
@alfredmyers I finally got time to investigate this. It seems that the MessageId property is only used by certain rules, namely legacy (non-Roslyn) rules for violations on a specific symbol (as opposed to executable code). For example, “CA1500:VariableNamesShouldNotMatchFieldNames”, is a naming rule that is always fired on a symbol, so you can use the MessageId property of the suppression attribute. On the other hand, "CA2000:Dispose objects before losing scope", is a non-symbol rule that can fire on any executable code that causes an allocation that is not disposed. The MessageId attribute property is ignored for this rule. 

For symbol violation rules, you specify the symbol name for the MessageId.

I am in the process of updating the documentation with this information.
