### ISSUE TITLE
Breakpoints still not working in 2.1

### ISSUE THREAD

**Issue by shoff** [MicrosoftDocs/visualstudio-docs#2003]
aspnet core 2.1 suddenly controllers that are not in the start up project will no longer break on any breakpoint when debugging. They do not break on exceptions or even Debugger.Break. Yes they are debug mode, pdbs are built module is loaded, code is being executed (I see it in the logs) but the debugger will not break.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95bc6d7e-2b58-4755-4411-c5f369011a6c
* Version Independent ID: d5710161-bc97-6d33-6c6b-77fc9cfe9c62
* Content: [Troubleshoot Breakpoints in the Visual Studio Debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/troubleshooting-breakpoints?view=vs-2017)
* Content Source: [docs/debugger/troubleshooting-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/troubleshooting-breakpoints.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by chriswolf-nrg** [comment]
I am having this very issue myself.  In my case, I am trying to debug a library, [serilog-sinks-loggly](https://github.com/serilog/serilog-sinks-loggly), so this library is not the startup project.  
I am on Windows-10, Visual Studio 15.8.1 and DotNet-Core SDK info:
```
dotnet --list-sdks
2.1.102 [C:\Program Files\dotnet\sdk]
2.1.104 [C:\Program Files\dotnet\sdk]
2.1.200 [C:\Program Files\dotnet\sdk]
2.1.201 [C:\Program Files\dotnet\sdk]
2.1.202 [C:\Program Files\dotnet\sdk]
2.1.302 [C:\Program Files\dotnet\sdk]
2.1.400 [C:\Program Files\dotnet\sdk]
```

**Comment by TerryGLee** [comment]
@shoff @chriswolf-nrg First, we apologize for our late response to this GitHub Issue. And we're sorry to hear that you both experienced the issue that you described here. We do appreciate your feedback. However, going forward ... if you experience a product-related issue, we'd like to make sure that is logged in the right place, which is via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
