### ISSUE TITLE
Visual Studio 2017 v15.9 will generate C26455 instead of C26439 for default constructors

### ISSUE THREAD

**Issue by vbaderks** [MicrosoftDocs/visualstudio-docs#2004]
The behavior in Visual Studio 2017 v15.9 has been changed:
https://developercommunity.visualstudio.com/content/problem/236762/c-code-analysis-warning-c26439-this-kind-of-functi.html

C26455 is now generated for default constructors not marked noexcept, which may be suppressed by adding noexcept or an explicit noexcept(false), "... noexcept(false) = default" is now also supported for the constructor.

Note: The link from C26455 to docs.microsoft.com from the Visual Studio error window doesn't work at the moment, as there is no page for C26455.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6aa6301e-fa20-242a-6710-fe4cbf2b51b3
* Version Independent ID: 75e708e3-3356-1c8b-741d-9d6a558e3307
* Content: [C26439 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26439?view=vs-2017)
* Content Source: [docs/code-quality/C26439.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26439.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@vbaderks thanks for reporting this! We now have a page for [C26455](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26455?view=vs-2017) so it seems to me the only fix here is to remove the bullet point for default constructors from the Remarks section. Let me know if you feel there is more to do here.
