### ISSUE TITLE
Need help with Export --config commandline

### ISSUE THREAD

**Issue by mrweiland** [MicrosoftDocs/visualstudio-docs#2005]
I have installed Preview latest 15.9 and also i have installed 2017 Enterprise 15.8.9. I wanna export config so i can use it later. 

What im a doing wrong - tried different installPath but none works
`.\vs_enterprise__preview.exe export --installPath "C:\Program Files (x86)\Microsoft Visual Studio\Preview" --config "C:\.vsconfig"`

Can someone give me a working example of export config?

**Comment by tydunkel** [comment]
@mrweiland The command needs to be passed directly to the installer that is on your system. e.g. "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" export --installPath "C:\Program Files (x86)\Microsoft Visual Studio\Preview" --config "C:\.vsconfig"

**Comment by tydunkel** [comment]
I see that the [examples](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017#using-export) are pointing to vs_enterprise.exe. I will work on updating those to use vs_installer.exe instead.

**Comment by tydunkel** [comment]
@mrweiland thank you for pointing out this issue! The docs have been updated to reflect the proper use of the export command.

@TerryGLee this issue can be closed out now that the docs have been updated.

**Comment by TerryGLee** [comment]
@tydunkel Thanks
