### ISSUE TITLE
Content suggestion

### ISSUE THREAD

**Issue by GrantMeStrength** [MicrosoftDocs/visualstudio-docs#2006]
I'd like more information on designing user interfaces, and how this works with Xcode. Some examples of creating an app using Interface Builder would be great. I get no sense how a control I add in Interface Builder would be referenced from my C# code? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1535449d-101b-e535-5b85-6c0417096760
* Version Independent ID: 8c6a261b-6b1f-cb9b-7901-1f19bde005b6
* Content: [Introducing Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/)
* Content Source: [mac/index.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/index.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Designing iOS apps is covered in the Xamarin documentation, starting with the [ios user interfaces section](https://docs.microsoft.com/xamarin/ios/user-interface/designer/), [ios storyboards](https://docs.microsoft.com/xamarin/ios/user-interface/storyboards/), and for Mac development, [xib files in Xcode](https://docs.microsoft.com/xamarin/mac/app-fundamentals/xib).

In general we recommend the iOS Designer built in to **Visual Studio for Mac** for iOS, and for macOS apps you use Xcode.

**Comment by GrantMeStrength** [comment]
And that's exactly the kind of thing I would like to see referenced from here. Thank you.
