### ISSUE TITLE
Cannot Convert Shape to Path!

### ISSUE THREAD

**Issue by dan-meier** [MicrosoftDocs/visualstudio-docs#2007]
The embedded video describing the procedure to convert a shape into a path uses the now-discontinued Expression Blend. The procedure in the current Blend for Visual Studio is different, and the Format &gt; Path &gt; Convert to Path menu item seems to be permanently disabled.  Is there NO WAY to convert a shape to a path within Visual Studio or Blend for Visual Studio???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0301c8-416c-59be-43a1-b5489716e50b
* Version Independent ID: c20b4f11-e646-5ba3-d5c7-82a753c4eef3
* Content: [Draw shapes and paths - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/draw-shapes-and-paths?view=vs-2017)
* Content Source: [docs/designers/draw-shapes-and-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/draw-shapes-and-paths.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@diverdan92 Can you answer this question?

**Comment by diverdan92** [comment]
@LyalinDotCom fyi

@dan-meier - you are building a UWP application with TargetPlatformVersion >= 10.0.16299.0? This should still work for other XAML based applications.

**Comment by dan-meier** [comment]
That's correct...UWP with min version 10.0.16299.  What are my options?

**Comment by diverdan92** [comment]
@dan-meier - if you don't have any hard dependencies on APIs in the later SDKs, you could retarget to an SDK before 10.0.16299.0, create the XAML Path, and then retarget higher again. Alternatively, you could create a simple project just designed to get the XAML path you need (with a Target Version < 10.0.16299.0) and copy the output into your main project. 

For context, this is an artifact of our significant updates to the underlying architecture of the [XAML Designer](https://blogs.msdn.microsoft.com/visualstudio/2017/09/11/a-significant-update-to-the-xaml-designer/). We haven't yet had a chance to re-implement this functionality on the updated designer.

**Comment by kaamil1984** [comment]
It doesn't work in VS2022, no matter what framework or target I have. Menu item is disabled.
