### ISSUE TITLE
Microsoft Docs website contain broken links that should point to this repository

### ISSUE THREAD

**Issue by hugolundin** [MicrosoftDocs/visualstudio-docs#201]
On [this website](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall), [the first link](https://raw.githubusercontent.com/MicrosoftDocs/visualstudio-docs/tree/master/mac/resources/uninstall-vsmac.sh) should point to https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/resources/uninstall-vsmac.sh instead.

**Comment by kraigb** [comment]
@TerryGLee Craig Dunn's team owns VS Mac content.

**Comment by asb3993** [comment]
This has already fixed.
