### ISSUE TITLE
How does project sub-typing work with the new .NET Standard csproj format?

### ISSUE THREAD

**Issue by aleksander-oven** [MicrosoftDocs/visualstudio-docs#2010]
I already have a custom project subtype (a.k.a. flavored project) for the C# DLL Library project, which uses ProjectTypeGuids tag to make things work. How can I transition my csproj templates to the new .NET Standard format?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd451a65-f5a0-fc0b-d4c2-96354f53046b
* Version Independent ID: 2183f9c7-2c12-740f-f1eb-5d3d03e9e272
* Content: [Project Subtypes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/project-subtypes?view=vs-2017)
* Content Source: [docs/extensibility/internals/project-subtypes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/project-subtypes.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by johnwc** [comment]
I too would like to know this.

**Comment by aleksander-oven** [comment]
@johnwc FWIW, I figured this out on my own some time ago. See this SO question that I've opened and then answered myself: https://stackoverflow.com/questions/53632661/vsix-flavored-project-that-targets-net-standard-and-uses-the-new-csproj-format

**Comment by msebolt** [comment]
The appears to have been resolved, closing this now.
