### ISSUE TITLE
EditorConfig language service extension is not working

### ISSUE THREAD

**Issue by d07RiV** [MicrosoftDocs/visualstudio-docs#2011]
Trying to add a config file using this extension shows an error:

    The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [Using EditorConfig settings in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@madskristensen Can you take a look at this feedback about the extension https://marketplace.visualstudio.com/items?itemName=MadsKristensen.EditorConfig?

**Comment by madskristensen** [comment]
Can you tell me what version of VS are you seeing this in and how I can repro this issue?

**Comment by d07RiV** [comment]
VS 2017 Professional, I just installed the extension (and restarted VS) and selected the option to create editor config file in my project.

There is an existing ticket where someone is having the same issue on the extension repository, dated half a year ago.

**Comment by gewarren** [comment]
@madskristensen Should @d07RiV log this issue on Developer Community via Help > Send Feedback > Report a problem instead, so you can get diagnostic info? (I'm not sure if extension issues are supposed to be logged there.)

**Comment by madskristensen** [comment]
@gewarren all issues with the extension should be opened on its GitHub issue tracker.

**Comment by gewarren** [comment]
@madskristensen Ahh, thank you. @d07RiV Can you please open this issue at https://github.com/madskristensen/EditorConfigLanguage/issues?
