### ISSUE TITLE
Can't use Sharepoint online as a private gallery 

### ISSUE THREAD

**Issue by DevKumar4Git** [MicrosoftDocs/visualstudio-docs#2014]
I am trying to create a private gallery pointing to a sharepoint site. I uploaded vsix file on to the sharepoint site but when I try to add the link to my gallery in Visual Studio & try to access my extension, I get 
"remote server returned 403"

**Comment by madskristensen** [comment]
No, you need to use a ATOM feed, but that along with the .vsix files can be hosted anywhere - including on SharePoint. See this https://github.com/madskristensen/PrivateGalleryCreator

**Comment by msebolt** [comment]
Closing the issue due to inactivity, please comment below if there are further issues.
