### ISSUE TITLE
Supported Operating Systems for remote computer

### ISSUE THREAD

**Issue by stamminator** [MicrosoftDocs/visualstudio-docs#2015]
Windows Server 2016 is not listed on the supported operating systems for the remote machine. Is this accurate?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2017)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@stamminator Hi, I'll update that. Thanks! WS 2016 is supported.

**Comment by Mikejo5000** [comment]
Updating this.
