### ISSUE TITLE
Need information about MSBuild for .NET Core vs .NET Framework

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/visualstudio-docs#2016]
See discussion at https://github.com/Microsoft/msbuild/pull/3987#discussion_r239223544 for more info

/cc @rainersigwald @AaronRobinsonMSFT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 911666fa-55ac-cbc1-ce79-66c058859ad9
* Version Independent ID: 571eec5d-8fb9-2401-fc4c-8a7896723eb7
* Content: [MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2017)
* Content Source: [docs/msbuild/msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by rainersigwald** [comment]
Once this is available, we need to point to it from https://aka.ms/msbuild/MSB4803 (which currently just points to the root of the MSBuild docs).

**Comment by Mikejo5000** [comment]
#2257 mentions EnableDefaultContentItems

**Comment by Mikejo5000** [comment]
#1783 mentions LinkBase

**Comment by Mikejo5000** [comment]
#4126 mentions ProjectGuid, TargetFramework, AssemblyTitle, Product, Copyright, OutputPath, and AppendTargetFrameworkToOutputPath

**Comment by gewarren** [comment]
The .NET Core properties will be covered by dotnet/docs#2642.

**Comment by bmenees** [comment]
The docs need to discuss ResolveComReference as another difference. I ended up here after running `dotnet test Libraries.sln` (in [this repo](https://github.com/bmenees/Libraries)) and getting the error:

* C:\Program Files\dotnet\sdk\3.1.101\Microsoft.Common.CurrentVersion.targets(2726,5): error : MSB4803: The task "ResolveComReference" is not supported on the .NET Core version of MSBuild. Please use the .NET Framework version of MSBuild. See https://aka.ms/msbuild/MSB4803 for further details.
