### ISSUE TITLE
== vs Equals

### ISSUE THREAD

**Issue by pierrebai** [MicrosoftDocs/visualstudio-docs#2017]
Should not the Equals() code call Equals on the sub-objects instead of using ==?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb48054-70fa-c5eb-748e-4db24ef64fd4
* Version Independent ID: 9ca41665-2e31-87da-4ba9-a8c60150db51
* Content: [Generate C# Equals and GetHashCode Method Overrides - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2017&viewFallbackFrom=vs-2015)
* Content Source: [docs/ide/reference/generate-equals-gethashcode-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-equals-gethashcode-methods.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by kendrahavens** [comment]
Interesting, it looks like it uses "==" only for built-in types. Even if the == operator is defined in a user type it will default to Equals.

@sharwell @jinujoseph Does this seem inconsistent? Should Equals() be used everywhere?

![image](https://user-images.githubusercontent.com/8293542/53832879-2736c800-3f3c-11e9-8baa-b9e149c7bbb2.png)

**Comment by sharwell** [comment]
@kendrahavens This is the behavior I would expect. The `==` operator is easier to read and generally more efficient for primitives, so it's preferred for those.

It's possible we should be using `Equals` for `double` since it impacts the return value for NaN.

**Comment by kendrahavens** [comment]
I think we can mark this "by design" then and close. We can open a separate ticket for `float`/`double` if needed.
