### ISSUE TITLE
unchecked in GetHashCode

### ISSUE THREAD

**Issue by pierrebai** [MicrosoftDocs/visualstudio-docs#2018]
In one blog, the author claims we need to use unchecked{} around the hash code calculation to silence overflow exceptions. Is that true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb48054-70fa-c5eb-748e-4db24ef64fd4
* Version Independent ID: 9ca41665-2e31-87da-4ba9-a8c60150db51
* Content: [Generate C# Equals and GetHashCode Method Overrides - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2017&viewFallbackFrom=vs-2015)
* Content Source: [docs/ide/reference/generate-equals-gethashcode-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-equals-gethashcode-methods.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
If [Eric Lippert says it's a good idea](https://ericlippert.com/2015/04/13/what-is-the-unchecked-keyword-good-for-part-two/), then it probably is. @BillWagner Do you have any opinion on this?

**Comment by xJonathanLEI** [comment]
I don't see how that will be beneficial though now that `unchecked` is the default behavior at runtime.

**Comment by oddbear** [comment]
@xJonathanLEI Some projects might have a different default through the `-checked` option _(and good reason for it to)_, should be up to them if they need it or not. And can libraries then rely on this being the default behavior at all?

**Comment by TerryGLee** [comment]
@pierrebai @oddbear I checked in with the engineering team, who said the following...

We currently respect the project properties.  If you're in a project with 'checked' math we emit:

![image](https://user-images.githubusercontent.com/23244653/81875281-c7bb4b80-9534-11ea-94dd-e5233bee9dd4.png)

That said, this is old-style GetHashCode emit when you're targetting an older framework.  On newer ones we'll just emit the idiomatic HashCode.Combine:

![image](https://user-images.githubusercontent.com/23244653/81875382-ff29f800-9534-11ea-814f-1ffdfb6b8309.png)

This has the benefit of working in checked or unchecked without any problems.

...

This should answer the original inquiry as well as the follow-up inquiry. As such, we'll go ahead and close this (older) issue now. And, thanks for your feedback!
