### ISSUE TITLE
Where to find Filter menu

### ISSUE THREAD

**Issue by MatrixRonny** [MicrosoftDocs/visualstudio-docs#2019]
I would like to point out that the Filter menu from "CPU Usage" tab is only present in the diagnostic session. If a method call is opened for details, even if the view is switched to "Call Tree", there is no Filter menu next to Search area.

This feedback is helpful for readers interested in the "External code" subsection of "Analyze the CPU Usage report". More specific, it describes how to obtain the results from the following picture (from current page):
https://docs.microsoft.com/en-us/visualstudio/profiling/media/cpu_use_wt_filterview.png?view=vs-2017

A better overview of where to find the Filter menu is provided by the next picture (from current page):
https://docs.microsoft.com/en-us/visualstudio/profiling/media/cpu_use_wt_report.png?view=vs-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0410dc57-c6ba-8256-a844-d6951e8b7c2f
* Version Independent ID: 80be647c-e762-acb5-cf56-2cf6b6f423c7
* Content: [Analyze CPU usage in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/cpu-usage?view=vs-2017#BKMK_External_Code)
* Content Source: [docs/profiling/cpu-usage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/cpu-usage.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@MatrixRonny Thanks, that does seem a little confusing. I will plan to fix it. So, it sounds like the Filter menu is only present when running the tool with the debugger attached, over in the Diagnostic Tools window on the right. Does that sound correct?

**Comment by MatrixRonny** [comment]
I'm no longer at work, but I will send you a picture tomorrow. My feedback only applies to VS2017, since in VS2015 I could not find a way to get additional details about method calls.

Regarding your question, I remember that the Filter menu is present in both cases, when using profiling tools with and without the debugger attached. In VS2017, additional call details can be displayed in a file tab, outside Diagnostic Tools. The tab is named "CPU Usage" (like in Diagnostic Tools) and has a view named "Call Tree" (similar with that from Diagnostic Tools). The problem is that the "CPU Usage" file tab outside the Diagnostic Tools (or diagsession) has no Filter menu. It looks like in this picture (from this page):
https://docs.microsoft.com/en-us/visualstudio/profiling/media/cpu_use_wt_showexternalcodetoowide_found.png?view=vs-2017
