### ISSUE TITLE
UI support

### ISSUE THREAD

**Issue by Campbellony** [MicrosoftDocs/visualstudio-docs#2020]
I like this addition. I'm curious if there are plans for a UI to help design these files.  I'm thinking something like the settings tab in the project properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [Using EditorConfig settings in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
There may be plans for a UI designer - hopefully the product team will answer that. Also, if your codebase is C#, you can use the IntelliCode extension for VS to automatically create/infer an .EditorConfig file. See https://blogs.msdn.microsoft.com/visualstudio/2018/07/17/visual-studio-intellicode-inferring-coding-conventions-for-consistent-code/ and https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio.

**Comment by cremor** [comment]
VS2019 will have a feature to export an EditorConfig file from the current VS settings.

**Comment by gewarren** [comment]
@cremor Thanks for bumping this issue, and you are correct, [Visual Studio 2019](https://visualstudio.microsoft.com/downloads/) includes a button on the text editor code style options page to generate an .EditorConfig file from your settings:

![image](https://user-images.githubusercontent.com/24882762/54375752-e5460a00-463e-11e9-85cd-86013f4b9461.png)

**Comment by mloskot** [comment]
> plans for a UI to help design these files. 

The world is shifting towards editing basic human-friendly formats (e.g. JSON).
We need no UI. We need no more UI bloat in VS. Learn to use your text editor.
The EditorConfig format is easy peasy to understand.
