### ISSUE TITLE
Windows Server 2019 base images.

### ISSUE THREAD

**Issue by yusuf-gunaydin** [MicrosoftDocs/visualstudio-docs#2023]
Does this work with Server 2019 images? When I try to run the executable it returns immediately. If I watch the %Temp% folder I can see that the installation continues. It is as if the --wait argument does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
Only 15.9 or greater will work with Server 2019. I'll add a note to the docs and get a blog post out.
