### ISSUE TITLE
error occurs when using denvenv to build C++ project 

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/visualstudio-docs#2025]
This issue is created by @SysFlat from https://github.com/MicrosoftDocs/feedback/issues/931
I want to build my c++ project in command line. So i follow this :
https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/build-devenv-exe?view=vs-2017

My command is:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional&gt;
Devenv G:\00-CodeCoverage\GMP5.0_Adapter_GTJ2018_4-10_Git\build\src\GAEA.sln /build Release|Win
32 /project G:\00-CodeCoverage\GMP5.0_Adapter_GTJ2018_4-10_Git\source\GCLCollect
\src\GCLCollect\GCLCollect.vcxproj /projectconfig Release|Win32
however it tells me belows :
Win32 is not an internal or external command nor is it a runnable program Or batch file.
Environment configuration
OS: WIN 7 X64
VS version:
Visual Studio Locator version 2.5.2+gebb9f26a3d [query version 1.17.1230.42073]
Copyright (C) Microsoft Corporation. All rights reserved.
installDate: 2018/6/27 18:00:39
installationName: VisualStudio/15.8.5+28010.2036
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
installationVersion: 15.8.28010.2036
productId: Microsoft.VisualStudio.Product.Professional
productPath: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe
isPrerelease: 0
displayName: Visual Studio Professional 2017
channelId: VisualStudio.15.Release
channelUri: https://aka.ms/vs/15/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660692#15.8.5
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660708
updateDate: 2018-09-27T05:47:16.5653768Z
catalog_buildBranch: d15.8
catalog_buildVersion: 15.8.28010.2036
catalog_id: VisualStudio/15.8.5+28010.2036
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 15.8.5
catalog_productLine: Dev15
catalog_productLineVersion: 2017
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 5
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productRelease: RTW
catalog_productSemanticVersion: 15.8.5+28010.2036
catalog_requiredEngineVersion: 1.17.1230.42073
properties_campaignId: 997337031.1530093492
properties_canceled: 0
properties_channelManifestId: VisualStudio.15.Release/15.8.5+28010.2036
properties_defaultProgram: VisualStudio.166b79d2
properties_nickname:
properties_setupEngineFilePath: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installershell.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 977d821f-ce22-b324-8348-a3777e476e37
* Version Independent ID: 86413bc0-26dc-5bfb-0bdd-9471b9c8a26a
* Content: [DevEnv Build switch - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/build-devenv-exe?view=vs-2017)
* Content Source: [docs/ide/reference/build-devenv-exe.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/build-devenv-exe.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@sysflat Could you try the command without specifying "Win32"?

**Comment by gewarren** [comment]
If you're still experiencing this, to make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
