### ISSUE TITLE
Does not contain all required information

### ISSUE THREAD

**Issue by evilC** [MicrosoftDocs/visualstudio-docs#2030]
Does not detail which component you need to install to have Spy++ available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c44ce60-3191-4090-0f47-1f8fe05eca45
* Version Independent ID: d5c700f5-e09c-544b-2347-db1b36c898cd
* Content: [Introducing Spy++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/introducing-spy-increment?view=vs-2017)
* Content Source: [docs/debugger/introducing-spy-increment.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/introducing-spy-increment.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, I'll take a look. Did you get it working correctly?

**Comment by evilC** [comment]
Yes, I did in the end, I think it was in the `C++ Core Features` component?

**Comment by Mikejo5000** [comment]
Updating doc
