### ISSUE TITLE
Unity Editor appearing in Windows processes, but never opening

### ISSUE THREAD

**Issue by SativaPhoenix** [MicrosoftDocs/visualstudio-docs#2031]
I solved mine by unplugging a USB gamepad: NAcon Revolution controller ;) so Im guessing Unity doesn't like it, 
Visual studio however fully runs with this controller plugged in, and is worth keeping vs unity, as you can code C# obviously in Visual STudio, render in unity, ,Peace™

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3255850c-b57f-3a66-a689-333e78e822e8
* Version Independent ID: efa89608-001f-c243-64f4-ce173218b363
* Content: [Troubleshooting and Known Issues (Visual Studio Tools for Unity) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity?view=vs-2017)
* Content Source: [docs/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev15**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by WilliamAntonRohm** [comment]
@SativaPhoenix -- Darryn, thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
