### ISSUE TITLE
Deprecated notice

### ISSUE THREAD

**Issue by juancamilor** [MicrosoftDocs/visualstudio-docs#2032]
There is a deprecated notice for the Web performance and load test functionality in Visual Studio
https://docs.microsoft.com/en-us/visualstudio/test/how-to-delete-load-test-results-from-a-repository?view=vs-2017
 Note
Web performance and load test functionality is deprecated. Visual Studio 2019 is the last version where web performance and load testing will be available.

Would be good to have some more details on what will replace this excellent functionality (if anything).

Thanks in advance

**Comment by gewarren** [comment]
@boraprachi Could you comment on this?

**Comment by gewarren** [comment]
A blog post about this is coming soon.

**Comment by timcools** [comment]
can you keep us posted when the blog post is published please

**Comment by felipepessoto** [comment]
Does it affect Azure DevOps Load Test?

**Comment by gewarren** [comment]
I will keep you posted. The blog post is slated to publish this Friday 1/25. It affects Azure DevOps load testing too - specific dates and scenarios will be covered in the blog post.

**Comment by theEyeD** [comment]
@gewarren Has the blog post been published?

**Comment by gewarren** [comment]
The blog post has been delayed until late next week.

**Comment by juarola** [comment]
@gewarren So, about that blog post...any news?

**Comment by gewarren** [comment]
I'm looking forward to the blog post as much as you are - sorry that it's delayed even further. In the meantime, here is some info that I think will be shared in the blog post:

Currently there are no alternatives planned from Microsoft and customers should choose alternative tools in the market that best fit their needs. For example, [Apache JMeter](https://jmeter.apache.org/) is a free, popular OSS tool with strong community backing. It supports many different protocols, including HTTP(S), and has rich extensibility that can be leveraged to customize the tool to your needs. Many commercial services also support running Apache JMeter tests. [Blazemeter](https://www.blazemeter.com/) is one such service that has made sustained investments in this space.

If you use code-based tests with load test and familiarity with .NET is an important consideration, tools such as [Neoload](https://www.neotys.com/neoload/overview), [Micro Focus Silk Performer](https://www.microfocus.com/en-us/products/silk-performer/overview) and [Micro Focus Load Runner](https://www.microfocus.com/en-us/products/loadrunner-load-testing/overview) are some of the options to consider.

In addition, extensions from several load test vendors such as [SOASTA](https://marketplace.visualstudio.com/items?itemName=SOASTA.SOASTA-Extension) (now Akamai CloudTest), [Apica Loadtest](https://marketplace.visualstudio.com/items?itemName=apicasystem.apica-loadtest), and [Load Impact](https://marketplace.visualstudio.com/items?itemName=julienstroheker.loadimpact) are available in the Azure DevOps and Azure marketplace.

**Comment by juarola** [comment]
Thank you! We already took the JMeter route. A bit sad to see VS performance testing functionality go - it was in many ways much more pleasant to use.

**Comment by karthikdevarakonda** [comment]
Hi,

One of the challenges with the deprecation of the load tests is that we are heavily dependent on Cloud based load generators from MS due to security reasons. For example my company's security policy doesn't allow any third party vendors other than MS to access our internal websites or applications and being a completely MS shop we already have suites built based on these. What is the solution for these kind of situations?

**Comment by ishepherd** [comment]
I assume this is the blog post referred to above:
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/

**Comment by gewarren** [comment]
@ishepherd Thanks for pointing that out. I hadn't been notified that it was published. I'll add a link to that blog post in the load testing docs.
