### ISSUE TITLE
out-of-date documentation and links

### ISSUE THREAD

**Issue by bubianchi** [MicrosoftDocs/visualstudio-docs#2035]
This documentation has links to VS Vizualization SDK which is not available anymore. 
In addition, the documentation is based on TextTemplate files provided by SDK, so these files are not available anymore also: why not include them in this documentation as source code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d35830e-6592-cee0-4025-59c1167c61f3
* Version Independent ID: 37f34ecc-9d1a-bf43-905f-082b57ec9f68
* Content: [Integrating Models by using Modelbus - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/integrating-models-by-using-visual-studio-modelbus?view=vs-2017#feedback)
* Content Source: [docs/modeling/integrating-models-by-using-visual-studio-modelbus.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/integrating-models-by-using-visual-studio-modelbus.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to #481.

**Comment by gewarren** [comment]
This page gets 80 page views per month.

**Comment by gewarren** [comment]
Due to the low page views on this topic and the fact that Microsoft is not actively developing the modeling technology, I unfortunately have to close this issue as "won't fix" due to its lower priority.
