### ISSUE TITLE
How can I update the item template the "Create Unit Tests" uses?

### ISSUE THREAD

**Issue by xinpeng-MSFT** [MicrosoftDocs/visualstudio-docs#2036]
Currently the created UT file places the imported namespaces outside of the namespace block, also the attributes TestClass and TestMethod are followed by parenthesis, neither are preferred.
I updated the templates under Common7\IDE\ItemTemplates\CSharp\Test\1033, but seems doesn't work. Curious why the command and the project don't share the same item templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a859ec6-03a2-2d8c-bcfe-c9499db55286
* Version Independent ID: 4ac4f045-660e-e159-edeb-315cf491568c
* Content: [Create unit test method stubs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/create-unit-tests-menu?view=vs-2017)
* Content Source: [docs/test/create-unit-tests-menu.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/create-unit-tests-menu.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@kendrahavens Do you know which template, if any, the **Create Unit Tests** command uses? And if it can be customized?

**Comment by kendrahavens** [comment]
@AbhitejJohn @jinujoseph Is there anyway to apply preferences to new item templates? I believe we run the formatter, but it doesn't include apply all code style options to new code.

**Comment by AbhitejJohn** [comment]
@kendrahavens : Because Create Unit Test supports more than one framework, we just use the generic class template to add a new class. If @xinpeng-MSFT could file an issue in developercommunity.visualstudio.com/ we could look into addressing this.

**Comment by xinpeng-MSFT** [comment]
https://developercommunity.visualstudio.com/content/problem/737581/cant-update-the-template-the-create-unit-tests-men.html

**Comment by gewarren** [comment]
@xinpeng-MSFT Thank you!
