### ISSUE TITLE
The `Edit.GenerateMethod` shortcut is not available

### ISSUE THREAD

**Issue by JinGangRed** [MicrosoftDocs/visualstudio-docs#2045]
I have fine the default shortcut of `Edit.GenerateMethod` is Ctrl+K, Ctrl+M, and I didn't modify it on the keyboard. However, when i press them in the Visual Studio 2015. It did not generate a method. And there are messages like this: `The key combination(Ctrl + K, Ctrl + M) is bound to command which is not currently available`.

So I want to know which the shortcut can generate method in Visual Studio 2015?
--

**Comment by JinGangRed** [comment]
Thanks @gewarren , I just want to quickly generate a method at the editor. For example, we can tap the `prop` and double press the `Tab`, it will create a public property.  And I want to know if there is a shortcut to quickly generate a method. This method has default access control, return value type, method name, etc., and then I can modify it.
Note that, I have create a shortcut to create a class, when i press `Ctrl + N, Ctrl + C`, there will a pop-up, I can modify the class name, then the IDE generate a class file with the default property

**Comment by gewarren** [comment]
I know we have the generate method from first usage functionality, but not sure about something that just creates a generic method body. @kendrahavens Do you know?

**Comment by kendrahavens** [comment]
As @gewarren mentioned, I find [creating a method from a call](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-method) is the easiest way to do this.

We do have a C# code snippet for a main method.
1. Type (Ctrl + K, Ctrl + X)
2. Select `C#`
3. Select `svm`

![image](https://user-images.githubusercontent.com/8293542/50028064-3e03f900-ffa3-11e8-9528-80b4649e3ea9.png)

When you select `svm` a main method code snippet is inserted:

![image](https://user-images.githubusercontent.com/8293542/50028118-7277b500-ffa3-11e8-8879-5602004d0e8f.png)

If you are looking for a different generic method you can [create your own code snippet](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet).

**Comment by JinGangRed** [comment]
OK, Thanks @gewarren and @kendrahavens, I will try it. Thanks so much.
