### ISSUE TITLE
Documentation on TEST_DESCRIPTION appears to be incorrect

### ISSUE THREAD

**Issue by TypePun** [MicrosoftDocs/visualstudio-docs#2046]
The documentation states: 

These pre-defined attribute macros can be substituted for the macros TEST_METHOD_ATTRIBUTE, TEST_CLASS_ATTRIBUTE, OR TEST_MODULE_ATTRIBUTE described above.

But the declaration of TEST_DESCRIPTION is:

#define TEST_DESCRIPTION(description) TEST_METHOD_ATTRIBUTE(L"Description", description)

Which means it can only be used in place of a TEST_METHOD_ATTRIBUTE.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3ec17-4193-8059-56de-fbad2fab239c
* Version Independent ID: e0e84806-41ff-fa5e-1aa1-775beed16d78
* Content: [Microsoft.VisualStudio.TestTools.CppUnitTestFramework API Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference?view=vs-2017#cppUnitTest_h)
* Content Source: [docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by SergeyVSB** [comment]
Although, there is no way to see description in Test Explorer

**Comment by mikeblome** [comment]
@TypePun thanks! This is fixed and should be visible in a couple of days.

@SergeyVSB Yes I can repro that. Please file an issue on [Developer Community](https://developercommunity.visualstudio.com/topics/C%2B%2B.html) so the product team can decide whether to implement it.
