### ISSUE TITLE
unclear what [$RootKey$\OpenFolder\Settings\VSWorkspaceSettings\[settings-name]] should be

### ISSUE THREAD

**Issue by martijnhoekstra** [MicrosoftDocs/visualstudio-docs#2049]
It's not clear what `[settings-name]` should be replaced with.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff91657a-173a-0013-62e4-e7c8531b8240
* Version Independent ID: 27988cad-5114-41e3-c48a-357431af0fe1
* Content: [Adding a Language Server Protocol extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2017#)
* Content Source: [docs/extensibility/adding-an-lsp-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
This has been fixed.
