### ISSUE TITLE
SetThreadDescription API is the recommended way of naming threads now

### ISSUE THREAD

**Issue by KorkyPlunger** [MicrosoftDocs/visualstudio-docs#2057]
The exception-based example above is the old way of naming a thread, and only works if the debugger is attached at the time the code runs. 
To work around this problem, I believe the SetThreadDescription API is the new Microsoft-recommended approach? https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/17608120-properly-support-native-thread-naming-via-the-sett

If so, expanding this article with information on that approach would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e8eef4f-1681-98f0-be2d-fcf83f7459fe
* Version Independent ID: 36a3b826-ad6d-e4f4-1719-2c061e711f0a
* Content: [How to: Set a Thread Name in Native Code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2017)
* Content Source: [docs/debugger/how-to-set-a-thread-name-in-native-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-set-a-thread-name-in-native-code.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@KorkyPlunger Great info, thanks! I'll get it updated.

**Comment by Mikejo5000** [comment]
@KorkyPlunger I'm checking on this. For clarity, you mean the old method works by F5 (Start Debugging) but does not work if you need to attach to a running process?

**Comment by Mikejo5000** [comment]
Reading through the linked material, it looks like SetThreadDescription is currently used only for viewing minidumps in the debugger. If you are using the debugger, you need to use the old method at this point.

**Comment by KorkyPlunger** [comment]
@Mikejo5000 

> For clarity, you mean the old method works by F5 (Start Debugging) but does not work if you need to attach to a running process?

Yes, correct

> Reading through the linked material, it looks like SetThreadDescription is currently used only for viewing minidumps in the debugger. If you are using the debugger, you need to use the old method at this point.

Interesting. Re-reading the docs this does appear to be the case. For that reason, in our code we perform both methods (the exception-based approach as well as the SetThreadDescription approach) to ensure that we can see thread names in both debugging scenarios and dump analysis (and xperf/WPA performance analysis) scenarios. 

This is a bit confusing for developers, since (as far as I can tell) none of the Microsoft docs make this disparity clear. Perhaps it would be worth amending this documentation to make it clear that the exception-based approach only works if the debugger is attached at the time the exception-based method is used, and that these names will not be available in dumps or performance analysis tools (with a link to the SetThreadDescription information)?

**Comment by Mikejo5000** [comment]
@KorkyPlunger That's great. I appreciate the info. You mind if I use your code here to update the doc?

Note that this PR might get closed by my previous fix before the final doc update.

**Comment by KorkyPlunger** [comment]
Sure, feel free to use that code. Thanks for the update
