### ISSUE TITLE
Very slow loading after "Enable native code debugging"

### ISSUE THREAD

**Issue by dilbert168** [MicrosoftDocs/visualstudio-docs#2060]
I have following this post and get mix mode debug working.
VS version : Community 2017
Python version : 3.71
Running on Window-10

The loading time of the project become very slow (&gt; 30 secs) after the "Enable native code debugging" feature is enabled.  
I believe due to matplotlib & socket is imported in Python project.
As I use a sample project to start, it cut down to (10 secs), still longer than normal Python Debug start (1 sec).

As my most interest is debugging the C code, any method to improve loading time ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702dd6fa-5ad3-b9c7-04bc-e9431c228623
* Version Independent ID: 4d8a2c98-429a-b04e-1489-74475df5951a
* Content: [Mixed-mode debugging for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2017#feedback)
* Content Source: [docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@dilbert168 Your issue here is more appropriately filed at https://github.com/Microsoft/ptvs/issues because it's related to product performance rather than being a doc issue (which we hande in this repo here). Please re-file there and reference this present one. Thanks.
