### ISSUE TITLE
Very difficult to figure out how to use find and replace in a single file

### ISSUE THREAD

**Issue by ORESoftware** [MicrosoftDocs/visualstudio-docs#2061]
Very difficult to figure out how to use find and replace in a single file. Why does cmd+r do nothing, or ctrl+r also does nothing. Why can't I replace text with ctrl/cmd+r?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b328a871-7747-31d6-737c-4e3f6d10d9d1
* Version Independent ID: 2b455842-a4ef-25bd-c386-f36e0d14ce3d
* Content: [Find and replace text, and multi-caret selection - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2017#find-and-replace-control)
* Content Source: [docs/ide/finding-and-replacing-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-replacing-text.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Sorry for the slow response, and thank you for the feedback/suggestion. The best place to provide feedback and/or make feature suggestions is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). I will also add the shortcuts Ctrl+F (find) and Ctrl+H (find and replace) more prominently in this article.
