### ISSUE TITLE
Custom Messaging and Notification In Visual Studio

### ISSUE THREAD

**Issue by smrazavian** [MicrosoftDocs/visualstudio-docs#2063]
Hi
Two things which I thought should be in Visual Studio:
1. **Custom Messaging:** 
I want to send a message to other developers in my team that work on one solution. I mean when I push message on the solution in broadcast manner or to single or group of user defined in TFS then those users when opening solution receives my message.
2. **Notification:**
I want to push some notification or comments on my solution or part of the code. I mean I could augment the code. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e598ea-9607-4e7e-e708-84573519ccaf
* Version Independent ID: 75f00085-0835-78b6-1098-1be6371f5c07
* Content: [Increase your productivity for .NET development - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-2017-for-dotnet-developers?view=vs-2017)
* Content Source: [docs/ide/visual-studio-2017-for-dotnet-developers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-2017-for-dotnet-developers.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@smrazavian Thanks for the suggestions. The best place to make your suggestions is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There's a relatively new "Suggest a Feature" button you can use.

![image](https://user-images.githubusercontent.com/24882762/50102659-780b1000-01da-11e9-97ac-ca4af8a03308.png)

(This issues page is for documentation feedback.)
