### ISSUE TITLE
It worked. See my configuration and issues.

### ISSUE THREAD

**Issue by dyaros27** [MicrosoftDocs/visualstudio-docs#2064]
Thanks its work. 
Didn't check the performance and stability, just the connection.
Tested with:
remote server: Windows Server 2016 with R SQL 2017 server as remote R, with Visual Studio Community 15.9.4 
client machine: Windows 10 Pro with Visual Studio Pro 15.9.4
Issues: Remote R Services ver. 1.3 doesn't work for me, I have used previous version 1.2
All other issues was because me missing (misunderstanding) configuration steps.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12d26329-412d-73f0-2d58-640f77cd6ba1
* Version Independent ID: 4d9a1e5a-84c4-a3a2-af63-7c64c7679aa0
* Content: [Remote workspaces for R - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/setting-up-remote-r-workspaces?view=vs-2017)
* Content Source: [docs/rtvs/setting-up-remote-r-workspaces.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/setting-up-remote-r-workspaces.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Hi @dyaros27 Is there an open issue here? I'm unclear whether there's an issue that the docs need to address. It sounds like you found the solution you need. Please confirm.
