### ISSUE TITLE
Great!

### ISSUE THREAD

**Issue by Zanardi1** [MicrosoftDocs/visualstudio-docs#2065]
Great page! Short and to the point.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1261884-8284-53f9-a325-15061bf897f8
* Version Independent ID: 4520c20f-86f6-5066-298b-d3d428901f87
* Content: [Use the Task List - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2017)
* Content Source: [docs/ide/using-the-task-list.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-the-task-list.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thank you for the positive feedback. It's nice to hear!
