### ISSUE TITLE
Issue I encounter 

### ISSUE THREAD

**Issue by shanmak** [MicrosoftDocs/visualstudio-docs#2066]
In Transpile the JSX step,
after executing this cmd "node_modules\.bin\webpack app.tsx --config webpack-config.js"
 I got file created in dist is main.js not app-bundle.js, so my project is not working, I check Developer mode in Browser it show app-bundle.js file is missing, then manually re-name as app-bundle in web-config file then again run cmd command  its work perfectly. 

I don't know why is happened and how its resolved, but one thing I want  to be clarified why main.js created ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2017#transpile-the-jsx)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by shanmak** [comment]
@Mikejo5000 Thank you

**Comment by lloydmonteiro** [comment]
I get this error
rosoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Node.js Tools\Microsoft.NodejsTools.targets(115,5): error MSB4018: The "AssignTargetPath" task failed unexpectedly.
System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.PathHelper.GetFullPathName()

**Comment by lloydmonteiro** [comment]
i now get this error and page doesnt load
(node:636) [DEP0062] DeprecationWarning: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` or `node --inspect-brk` instead.
Press any key to continue...
