### ISSUE TITLE
The Walkthrough does not work

### ISSUE THREAD

**Issue by TPIvan** [MicrosoftDocs/visualstudio-docs#2067]
.NET Standard with DialogDebuggerVisualizer https://github.com/MicrosoftDocs/visualstudio-docs/issues/1620

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acfc5457-74ed-4e9b-ff4e-677aa78b82d3
* Version Independent ID: 98bb5302-d3fb-a7e3-322e-2d4acd9c524b
* Content: [Write a visualizer in Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-visual-basic?view=vs-2017)
* Content Source: [docs/debugger/walkthrough-writing-a-visualizer-in-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-writing-a-visualizer-in-visual-basic.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, I'll plan to retest this.

**Comment by Mikejo5000** [comment]
Should be fixed
