### ISSUE TITLE
The link does not work anymore

### ISSUE THREAD

**Issue by spellmanliu** [MicrosoftDocs/visualstudio-docs#2068]
For a related video demonstration, see How do I: Access and manipulate custom document properties in Microsoft Word?. The link does not work. I cannot find a video named "How do I: Access and manipulate custom document properties in Microsoft Word?" on that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7941790-134c-39a5-d0e4-0df82f723870
* Version Independent ID: 11357b83-d186-2df2-f73e-adf79191ea9c
* Content: [How to: Create and modify custom document properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-create-and-modify-custom-document-properties?view=vs-2017)
* Content Source: [docs/vsto/how-to-create-and-modify-custom-document-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-create-and-modify-custom-document-properties.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
Thanks for letting us know; this content set is in our backlog to update. @John-Hart, FYI.

**Comment by John-Hart** [comment]
This was fixed with PR #4103

#please-close
