### ISSUE TITLE
Hello wrold

### ISSUE THREAD

**Issue by Leejiezh** [MicrosoftDocs/visualstudio-docs#2069]
leejie 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394742b8-d974-8b1e-5800-b0fca1ef6a54
* Version Independent ID: 3065ca4c-b293-aa89-ca76-bcf718f9e21c
* Content: [Python in Visual Studio tutorial step 0, installation - ](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-00-installation?view=vs-2017)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-00-installation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-00-installation.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
If there's a legitimate issue here, please amend and reopen.
