### ISSUE TITLE
What i do?

### ISSUE THREAD

**Issue by oswal92** [MicrosoftDocs/visualstudio-docs#2070]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63281b03-c455-5a80-3716-e374372330fe
* Version Independent ID: 05617725-bce1-fe54-7dda-d0767f9cc527
* Content: [Visual Studio Subscriptions Professional Development](https://docs.microsoft.com/en-us/visualstudio/subscriptions/professional-development?irgwc=1&OCID=AID681541_aff_7794_1246483&tduid=(ir__qv0qintyqt39dumtfmt31gpz2e2xhyotcjwwh2nq00)(7794)(1246483)(%28d8a8409da3b8b8ef3b22d323e82302da%29%28266696%29%282142931%29%280e007955tfl4%29%28%29)(d8a8409da3b8b8ef3b22d323e82302da)&irclickid=_qv0qintyqt39dumtfmt31gpz2e2xhyotcjwwh2nq00)
* Content Source: [subscriptions/professional-development.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/professional-development.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by gewarren** [comment]
@oswal92 Were you trying to leave feedback for this topic?

**Comment by TerryGLee** [comment]
@oswal92 We're closing this for now; if you do have feedback to add, please do so and we'll reopen it.
