### ISSUE TITLE
Dependency diagrams are not supported for .NET Core projects in Visual Studio 2017

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/visualstudio-docs#2073]
Is this still true? Is this fixed in the preview of VS2019? Are there any workarounds?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a2f39b7-a366-bcf8-2ab2-21d9dbdccdd4
* Version Independent ID: 371066b5-ce84-29d5-8284-5836448c8275
* Content: [Dependency Diagrams Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/layer-diagrams-reference?view=vs-2017)
* Content Source: [docs/modeling/layer-diagrams-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/layer-diagrams-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@SrinivasMSFT Could you comment on whether dependency diagrams will be supported for .NET Core projects in VS 2019?

**Comment by msebolt** [comment]
@gewarren @SrinivasMSFT Is this still an issue?

According to [Validate code with layer diagrams](https://docs.microsoft.com/en-us/visualstudio/modeling/validate-code-with-layer-diagrams?view=vs-2019) .NET Core is now supported.

**Comment by gewarren** [comment]
Yes dependency diagrams for .NET Core apps are supported starting in Visual Studio 2019 version 16.2. I'll update the note. Thanks @msebolt!
