### ISSUE TITLE
Cannot see DevOps projects

### ISSUE THREAD

**Issue by RMarietta** [MicrosoftDocs/visualstudio-docs#2075]
After I select "Connect Provider", then "Dev Ops", then enter my credentials, it refreshes the list and doesn't display anything most of the time. Sometimes it will display the Dev Ops organization but there are no projects listed. It says above that this could be a permission issue, but I'm able to access the projects from VS (Windows) as well as online at dev.azure.com using the same credentials. Is there a specific permission needed to see the projects from VS Mac? Are there any other steps I can take to troubleshoot this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [Team Foundation Version Control (TFVC) - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by MartinHelvig** [comment]
I have the same problem, I cannot find any of my projects on Mac.

**Comment by jmatthiesen** [comment]
Hey, @RMarietta and @MartinHelvig! Are your repos, within your Azure DevOps organization, using Git for version control or TFVC?

**Comment by RMarietta** [comment]
@jmatthiesen - we started using TFVC but because we couldn't access the projects we switched to Git.

**Comment by asb3993** [comment]
@jmatthiesen can you address this?

**Comment by jmatthiesen** [comment]
Thanks for the comment! To access your Git repos in Azure DevOps, you can use the Version Control > Checkout… menu and point it at the URL for your hosted Git repo. We made some changes in the past few versions to improve Azure DevOps support here, so if you tried it in the past and it didn’t work, it may be improved now.
