### ISSUE TITLE
This information is no longer valid and it's a big issue

### ISSUE THREAD

**Issue by storkinsj** [MicrosoftDocs/visualstudio-docs#2076]
I don't understand how we are still discussing "media". No one does anything but download these days. In addition, you had a download link for the tool previously and it has been removed. Google is pointing us to the broken link. https://www.microsoft.com/en-us/download/details.aspx?id=23205 .

I think it's important to correct the article so that we can find the profiler, which doesn't seem to have gotten installed on my version and as mentioned- no media. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb6a064-a3ec-7013-d28f-36d860bb9128
* Version Independent ID: 78db436e-7099-f9b0-4ca4-79a796a595df
* Content: [How to: Install the Stand-Alone Profiler - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-install-the-stand-alone-profiler?view=vs-2017)
* Content Source: [docs/profiling/how-to-install-the-stand-alone-profiler.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/how-to-install-the-stand-alone-profiler.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@storkinsj Thanks for the feedback! Updating this now.
I believe this is the correct link. Let me know how it goes:
https://visualstudio.microsoft.com/downloads/?q=performance+tools#performance-tools-for-visual-studio-2017

**Comment by storkinsj** [comment]
Fantastic- Great job!
Greg

    On Wednesday, December 19, 2018, 9:46:11 AM GMT+9, Mike Jones <notifications@github.com> wrote:  
 
 
@storkinsj Thanks for the feedback! Updating this now.
I believe this is the correct link. Let me know how it goes:
https://visualstudio.microsoft.com/downloads/?q=performance+tools#performance-tools-for-visual-studio-2017
