### ISSUE TITLE
After installing the textmate bundle... then what?

### ISSUE THREAD

**Issue by bradcray** [MicrosoftDocs/visualstudio-docs#2077]
This document seems to end on something of a cliffhanger.  It makes it clear where the textmate bundle should be installed (though things are a bit vague on the Mac), but then doesn't indicate how to create new files using that language's highlighting once the user has done so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* Content: [Add editor support for other languages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages?view=vs-2017)
* Content Source: [docs/ide/adding-visual-studio-editor-support-for-other-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Related to #410. I'm looking into getting more info for you.

**Comment by bradcray** [comment]
Thanks @gewarren!  My specific situation is that I've put the textmate files where (I think) they're supposed to go, but now am not sure how to say "OK, Visual Studio, now that you know how to color programming language foo, I'd like to create a new file in language foo (or to color this existing file according to language foo).

**Comment by gewarren** [comment]
@bradcray I don't think there's anything else actionable on this issue. Once the textmate bundle is in the right directory it should just "work". Let me know if you feel something else needs to be added.
