### ISSUE TITLE
EMS Support

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#2079]
Hello team,

The support for EMS is not clearly specified, and the site you referenced for Technical Support does not have the product listed as one of the options. Can you please clarify who do we have to contact for support pertaining this Microsoft Service?

thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b2872e-438a-b86e-9ff5-6dc0021f3fe8
* Version Independent ID: 8b9e935e-07ad-4992-edb9-e8361d867617
* Content: [EMS Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ems)
* Content Source: [subscriptions/vs-ems.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-ems.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@Nathan-Tarin  Thanks for reaching out.  I see an opportunity to clean up the page a little to provide better guidance.  I will take care of that.  Thanks for bringing it to our attention.  

The EMS team is currently using a docs.microsoft.com page to outline the support processes for EMS.  That page is:  https://docs.microsoft.com/en-us/enterprise-mobility-security/solutions/ems-support-faq.  From there, you can identify the support path that is appropriate to your particular support question.  

Thanks!
Evan

**Comment by evanwindom** [comment]
@Nathan-Tarin  The updates have been made, and should be visible shortly.  Thanks again for bringing the issue to our attention!

**Comment by gewarren** [comment]
@evanwindom Can we close this?
