### ISSUE TITLE
Annual subscriptions no longer available

### ISSUE THREAD

**Issue by jochenvangasse** [MicrosoftDocs/visualstudio-docs#2088]
Microsoft no longer offers Visual Studio Professional Annual Subscription and Visual Studio Enterprise Annual Subscriptions in Cloud Subscriptions. There will be no change to existing customers experience and ability to renew, increase, decrease, or cancel their subscriptions.
This should be reflected in the docs here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f413cb5d-d6c4-2036-62e2-0af9b041ade3
* Version Independent ID: 7c96f714-fb4f-a578-546e-2cfba9366d76
* Content: [Visual Studio cloud subscription purchasing for CSPs](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-csp)
* Content Source: [subscriptions/vscloud-csp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-csp.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@jochenvangasse Thank you for reaching out.  We have already submitted changes to that page and others to reflect the change to the availability of annual cloud subscriptions.  We're waiting for them to replicate.
