### ISSUE TITLE
Publishing project

### ISSUE THREAD

**Issue by quillby** [MicrosoftDocs/visualstudio-docs#2090]
The project runs great. Even the created .exe file is running the project. Publishing works okay creating the setup.exe etc. But when running setup.exe it causes a BSOD on Windows 10. Am I missing something? Thanks for any help on this.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 38ae1727-4def-5921-86ec-bc65e9f0b8e4
* Version Independent ID: aed7dda1-6bfd-945f-04a5-86ee0fe62d95
* Content: [Overview of Visual Studio 2017](https://docs.microsoft.com/nl-nl/visualstudio/get-started/visual-studio-ide?view=vs-2017)
* Content Source: [docs/get-started/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-studio-ide.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
*blue screen of death

**Comment by gewarren** [comment]
@quillby Is this for an app you created, or were you following one of our tutorials?

**Comment by gewarren** [comment]
Closing due to not enough info about the app in question. We can reopen this issue if we get more info.
