### ISSUE TITLE
GitHub app no installed

### ISSUE THREAD

**Issue by PRMerger6** [MicrosoftDocs/visualstudio-docs#2091]
:warning: The Git Automator app is not installed on this repo, which will cause the Git Automator service to be unavailable, please click [here](https://github.com/apps/prmerger-for-apex-content-teams/installations/203064) to install it.

@meganbradley; @antonygnanasekar; @EstherGaddindla; @seshenoy; @v-caxian; @TinaLiuGirl;

**Comment by PRMerger19** [comment]
The Git Automator app has been installed to this repo.
