### ISSUE TITLE
answers for the quiz

### ISSUE THREAD

**Issue by yescas8000** [MicrosoftDocs/visualstudio-docs#2099]
the answers for the quiz are not the real answers like: 78 - 26 = 52 and in the quiz 78 - 26 = 509
it is in all the answers not only this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac26546d-191a-6600-a683-db4fbc5f4e46
* Version Independent ID: d3341bf4-795c-0854-a272-8a9cc906976d
* Content: [Step 7: Add multiplication and division problems - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-7-add-multiplication-and-division-problems?view=vs-2017#feedback)
* Content Source: [docs/ide/step-7-add-multiplication-and-division-problems.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-7-add-multiplication-and-division-problems.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@yescas8000 Thanks for your feedback; we've got this in our backlog to investigate/fix.

**Comment by gewarren** [comment]
@TerryGLee I also suggest adding dev_langs metadata to this article to free up screen real estate. Only the VB or C# code snippets will be shown, but not both at the same time.

**Comment by ornellaalt** [comment]
Hi @yescas8000, I wasn't able to reproduce your issue. Please double check your code, and reopen this issue if you are still seeing this problem. Please provide your code for more context. Closing this out for now.
