### ISSUE TITLE
How to attach Live Visual Tree to a hosted application (PowerPoint plugin)

### ISSUE THREAD

**Issue by AlekseyPi** [MicrosoftDocs/visualstudio-docs#2100]
I am developing a PowerPoint add-in, and my Live Visual Tree is always empty. Is it possible to attach it to a hosted assembly in mine case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2baf39-d3c3-5d5a-d93c-f4040430c3dd
* Version Independent ID: c443e681-03f0-ea47-a09d-718693448b3d
* Content: [Inspect XAML properties while debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/inspect-xaml-properties-while-debugging?view=vs-2017)
* Content Source: [docs/debugger/inspect-xaml-properties-while-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/inspect-xaml-properties-while-debugging.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by TerryGLee** [comment]
@AlekseyPi First, apologies for the much delayed response on this. Second, an inquiry: Can you tell us how you are building your plug-in? Currently, the Live Visual Tree works only with XAML apps in specific scenarios, and is likely not supported for your scenario.

(@LyalinDotCom FYI)

**Comment by TerryGLee** [comment]
@AlekseyPi Having not heard back from you, we are closing this issue now. Please do feel free to create a new issue if you find you are still experiencing the problem, and we'll do what we can to help you.
