### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by geoduderino** [MicrosoftDocs/visualstudio-docs#2103]
Is this out of date? 

When I look for installed templates, there is none called 'Windows forms application' I don't think this is an installation issue... However I am unsure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8db6086-d530-8705-595d-a37fbbb94178
* Version Independent ID: 9fd77d3f-8607-0030-018d-5fd78a485c8f
* Content: [Step 1: Create a Windows Forms Application project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-1-create-a-windows-forms-application-project?view=vs-2017)
* Content Source: [docs/ide/step-1-create-a-windows-forms-application-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-1-create-a-windows-forms-application-project.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gewarren** [comment]
@geoduderino You likely need to install the .NET desktop development workload through Visual Studio Installer.

**Comment by gewarren** [comment]
@TerryGLee It looks like we might need to add a step to the topic to install the .NET desktop development workload.

**Comment by TerryGLee** [comment]
@geoduderino Thanks for letting us know; we've updated the page, which should be published by Tuesday of next week (if not sooner).

**Comment by 161134050** [comment]
When I look for installed templates, there is none called 'Windows forms application' I don't think this is an installation issue... However I am unsure.
