### ISSUE TITLE
The tutorial is not enough to solve my problem

### ISSUE THREAD

**Issue by onmagic** [MicrosoftDocs/visualstudio-docs#2104]
win 7 pro, x64, install vs2017, the problem is suddenly happening maybe change / uninstall sth. because i got another error, finally solve the "another error", but found "unable to start debugging on the web server. unable to connect to the remote server", I spend about 1 full day to find the solution, at least read this page over 10 times, cannot understand how

Very sad and disappointed.

I try to uninstall vs and iis over 5 times already, how can i restore previous.... cannot... why cannot... why cannot... do i need to remove any thing related to microsoft ? .net framework ( all version ), can complete remove iis, completely remove vs ? 

really bad.... !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b3da70-ab86-495d-abfe-384f369660fe
* Version Independent ID: 2456d73a-68bd-cc6b-bff0-e7666e53f404
* Content: [Error: Unable to Start Debugging on the Web Server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-unable-to-start-debugging-on-the-web-server?view=vs-2017#cannot_connect)
* Content Source: [docs/debugger/error-unable-to-start-debugging-on-the-web-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-unable-to-start-debugging-on-the-web-server.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@onmagic @andysterland I'm sorry you are experiencing this issue. Please click the icon in the upper right in VS and "Report a Problem". This is a support issue.
Sounds like you just upgraded from VS 2015 to VS 2017 and started having the issue?

**Comment by gewarren** [comment]
@Mikejo5000 Can this be closed in favor of Report a Problem?

**Comment by Mikejo5000** [comment]
Yes.
