### ISSUE TITLE
Error at compiling time

### ISSUE THREAD

**Issue by FransPinos** [MicrosoftDocs/visualstudio-docs#2114]
Error al instalar el paquete. El dispositivo '' no es válido o no se ejecuta. Cambie a otro dispositivo o use Android Virtual Device (AVD) Manager para iniciar un emulador compatible, o conecte un dispositivo con Android compatible.	MyAndroid.Packaging		0	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 904f29a0-43c8-dfff-01d2-581111957f32
* Version Independent ID: db5b2081-71e6-785a-d665-2a12e4bed46d
* Content: [Create an Android Native Activity App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/create-an-android-native-activity-app?view=vs-2017)
* Content Source: [docs/cross-platform/create-an-android-native-activity-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/create-an-android-native-activity-app.md)
* Product: **visual-studio-dev15**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by banelingn** [comment]
you ether need to install the android emulator in extensions, get tools and features in the tools menu, or connect an android device.

**Comment by rademaker13** [comment]
Which emulator should you install, I installed this, doesn't work keeps loading (Can I ask this here?)

Emulators installed

Google Android Emulator (API Level 23) (global install)
Intel Hardware Accelerated Execution Manager (HAXM) (global install)

not installed

Google Android Emulator (API Level 23) (local install)
Google Android Emulator (API Level 25)
Google Android Emulator (API Level 27)
Intel Hardware Accelerated Execution Manager (HAXM) (local install)

**Comment by corob-msft** [comment]
@rademaker13 The Google emulators should work fine. Choose one with the minimum API Level you intend to support. You'll need to configure the HAXM support in the control panel, which will disable Windows VM support and requires at least one reboot. There is sometimes flakiness in getting the emulators recognized by the IDE. A reboot will often fix this issue. One annoyance is that the Google Store is only supported by some emulators. If that matters to you, you'll have to pay attention to which emulators include that support, which may be in a later API level than your app supports.

**Comment by rademaker13** [comment]
I have a Ryzen 5 2400

**Comment by rademaker13** [comment]
- Normally AMD is supported, 
- Google Android Emulator (API Level 23) (global install) so this should be fine?
- which should you pick, x64, x86, I think x86?
- kind of build? Native only?
- Is there more information on this somwhere?

**Comment by corob-msft** [comment]
@rademaker13 
HAXM doesn't work on AMD, but there are other options. The Android documentation here on [Configuring VM acceleration](https://developer.android.com/studio/run/emulator-acceleration#accel-vm)
is probably your best source of information.
