### ISSUE TITLE
missing redirects from old docs to new docs

### ISSUE THREAD

**Issue by nonbob** [MicrosoftDocs/visualstudio-docs#2115]
[Enter feedback here]
This is not about the documentation, but about how one gets to the documentation.  I'm not sure this is the correct spot, but it was the closest match I could find.

I got here via diagnostic output from msbuild, which gave me: [http://go.microsoft.com/fwlink/?LinkId=293424](http://go.microsoft.com/fwlink/?LinkId=293424).  I suspect that link should've taken me to [https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2017](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2017).  Instead, it sent me to [https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/bb383796(v=vs.120)](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/bb383796(v=vs.120))

Nicely, that page has a Recommended Version button near the top.  Not so nicely, that button just sent me to the generic VS2017 page [https://docs.microsoft.com/en-us/visualstudio/?view=vs-2017](https://docs.microsoft.com/en-us/visualstudio/?view=vs-2017).  Once again, I expected to be sent to the new ToolsVersion page.

I don't know how common this is, but it seems like I've run into this before.

I bet you guys already have a broken link crawler.  Perhaps it's letting some links fall through the cracks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77079cd6-4aaf-f6d9-bbe8-22e7c710d4ac
* Version Independent ID: 33bd5e27-8763-c387-15f1-9218a20d82c1
* Content: [MSBuild Toolset (ToolsVersion) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-toolset-toolsversion.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-toolset-toolsversion.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Requested update to this FwLink.

**Comment by Mikejo5000** [comment]
Fixed now

**Comment by nonbob** [comment]
Thanks for getting the fwlink working.

I would consider this semi-closed.  But that's what I get for opening two issues in one.  The Recommended Version link on the VS-2013 page still goes to the generic VS page (2019 now) instead of revectoring to the corresponding page in the VS-2019 world.
