### ISSUE TITLE
Is there a "Add the previous matching text as a selection" command and shortcut?

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/visualstudio-docs#2125]
Hello. Is there a reverse of `Shift+Alt+.`	(Add the next matching text as a selection)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b328a871-7747-31d6-737c-4e3f6d10d9d1
* Version Independent ID: 2b455842-a4ef-25bd-c386-f36e0d14ce3d
* Content: [Find and replace text, and multi-caret selection - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2017)
* Content Source: [docs/ide/finding-and-replacing-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-replacing-text.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@abuchholtzau Could you answer this question about multiple selections?

**Comment by abuchholtzau** [comment]
Andrew Cheung owns this now - although I'm not sure what his GitHub username is.
As far as I know, there isn't a command like this. We only move forward - although it should wrap back around if you skip selection enough times!
