### ISSUE TITLE
Doc is not up to date 

### ISSUE THREAD

**Issue by Mandrakx** [MicrosoftDocs/visualstudio-docs#2126]
"The deployment options page appears while syncing." ITy doesn't. It takes you through Kudu instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d4b59f-07fd-b894-01f7-9bc2fc06e98a
* Version Independent ID: 1cb6913e-21a7-48d2-8b83-cb416304b0c5
* Content: [Publish a Node.js app to Linux App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/publish-nodejs-app-azure?view=vs-2017)
* Content Source: [docs/javascript/publish-nodejs-app-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/publish-nodejs-app-azure.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Mandrakx Were you able to resolve this? If so, can you suggest a fix here? Thanks!

**Comment by Mikejo5000** [comment]
Doc needs a refresh for validation. Creating a work item and closing this.
