### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by IFinnimore** [MicrosoftDocs/visualstudio-docs#2149]
Add missing example for EnumerateLiteral function
Change "Example" Titles to be specific to individual function, so the "In this article" doesn't just list "Example" "Example" "Example"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87786dea-7de0-a5c1-cbeb-d551219f38c5
* Version Independent ID: ef34ed8f-8e9d-ee55-3dfd-7689315f2fc9
* Content: [Code Snippet Functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippet-functions?view=vs-2017#example-2)
* Content Source: [docs/ide/code-snippet-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-snippet-functions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@IFinnimore Thanks for the feedback. I'm fixing the example headings. However, there is no EnumerateLiteral function that I can see in this article.

**Comment by IFinnimore** [comment]
Actually the function is EnumerationLiteral I was referring to.  Upon further review, I note it is just part of the GenerateSwitchCases.  The wrapping of the cells in the functions table tripped me up.

Sent from Mail for Windows 10
