### ISSUE TITLE
I have a problem!

### ISSUE THREAD

**Issue by mvladd1** [MicrosoftDocs/visualstudio-docs#2150]
i have this problem when i press LOCAL WINDOWS DEBUGER :
Error	MSB6006	"CL.exe" exited with code -1073741515.

And i don t know how to resolve it. Some ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9b755e9-4fe2-7d3d-b593-1b89cc53c858
* Version Independent ID: e126e7d0-a1c4-d6cd-4e68-8916cc57c6e9
* Content: [ToolTaskExtension Base Class - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/tooltaskextension-base-class?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(MSBuild.ToolTask.ToolCommandFailed)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/msbuild/tooltaskextension-base-class.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/tooltaskextension-base-class.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mvladd1 Hi, I'm sorry you are experiencing this issue. This is a support issue rather than a doc issue. Please click the icon in the upper right in VS and "Report a Problem".
