### ISSUE TITLE
VS2017/2019 F1 documentation in C# Interactive lands here

### ISSUE THREAD

**Issue by vilu85** [MicrosoftDocs/visualstudio-docs#2151]
Highlighting any keyword, text, etc. in C# Interactive window (View -&gt; Other Windows -&gt; C# Interactive) and pressing F1 lands here.

This was the code I used in case you want to reproduce the problem:

[code]
&gt; long time1 = DateTime.Now.Ticks / TimeSpan.TicksPerMillisecond;
&gt; Console.WriteLine("time1.GetHashCode() = " + ((int)(time1.GetHashCode() ^ 0xfffff)));
time1.GetHashCode() = 549326803
[/code]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a28ee58-bd99-e74a-0c0c-30f5a41da08e
* Version Independent ID: 2467c672-a567-583c-2801-87dcaf0f2c91
* Content: [Default page for F1 help - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.Ambient);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv3.5)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/ide/not-in-toc/default.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/not-in-toc/default.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@vilu85 Thanks for letting us know!

**Comment by msebolt** [comment]
For now, please use the [C# Interactive walkthrough](https://github.com/dotnet/roslyn/wiki/C%23-Interactive-Walkthrough).

@gewarren  Is this a topic slated to be written?  There currently seems to be nothing in Microsoft Docs. 

I would create this as a product issue, but not until there is something to redirect to.

**Comment by gewarren** [comment]
Yes, this does seem to be a hole in the docs.microsoft.com documentation. @chborl @mikadumont @kendrahavens Do you agree that the [C# interactive docs from the roslyn wiki](https://github.com/dotnet/roslyn/wiki/Interactive-Window) should be ported to docs.microsoft.com, somewhere in [this area](https://docs.microsoft.com/en-us/visualstudio/ide/reference/command-window?view=vs-2019) perhaps?

**Comment by kendrahavens** [comment]
Yes! I think that'd be a good idea. We'd need to update the samples. I know it supports past C# 6.0, but I'm not sure the limit. @tmat was also mentioned as a C# interactive expert.

**Comment by SMailman** [comment]
Title says "VS2017" but also occurs in VS2019.

**Comment by LBynum77** [comment]
I'm unable to reproduce in VS 2019 16.5 both from within the interactive window, and the code editor.  Can you share a more specific example/key word?

**Comment by Mikejo5000** [comment]
@LBynum77 I can repro F1 issue for the C# Interactive window using the example code above. The window passes VS.Ambient, not the specific keyword. Are you seeing different behavior? This appears to be a bug.

**Comment by Mikejo5000** [comment]
Thanks for reporting this issue. I created a product request to add correct F1 Help functionality to the C# Interactive window. Since this is a product bug and not a doc issue, we will not be tracking this work here. Thanks!
