### ISSUE TITLE
How to refactor HTML/CSS?

### ISSUE THREAD

**Issue by VashJuan** [MicrosoftDocs/visualstudio-docs#2152]
Can Visual Studio refactor CSS & HTML files? This page should list (or link to) all about refactoring, not a tiny paragraph that lists one minor aspect...C/C++.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ce42b1-5ca3-2bba-be51-172e0ad715fd
* Version Independent ID: 3e28ccb0-f87e-bb74-c4f0-ed0ed2f1b364
* Content: [Refactoring - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2017)
* Content Source: [docs/ide/refactoring-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/refactoring-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Visual Studio doesn't technically have any refactoring support for HTML or CSS. The closest we have is formatting, but that’s restricted to making non-significant changes to the code, for example, adjusting whitespace.

Refactoring tools like extracting styles to a CSS class or renaming a class are interesting ideas but not something we’ve invested in.
