### ISSUE TITLE
VSTU for Mac & Symlinked Script Files

### ISSUE THREAD

**Issue by mleesago** [MicrosoftDocs/visualstudio-docs#2159]
When using Visual Studio Mac as code editor for Unity and opening scripts that have been symlinked to be exposed to Unity project, intellisense does not recognize the script file to be part of the solution. So initially opening the symlinked script (by double clicking on the script file inside Unity Editor) using Visual Studio, you will see that intellisense does not work but if you search for the same file inside Visual Studio code editor and open that, which pretty much uses the same window as the file you initially opened, you will notice that now intellisense recognizes the script file as being part of the solution and everything works fine. Suspecting that it might have to do with how VSTU for Mac and its bridge code is being used to open scripts that have been symlinked.

Attached an example project that illustrates this problem. If you open the project (on MacOS) and click "Link/Link Master" then it will expose "Code/master" folder to Unity via symlink, and target path being "Assets/Code". Then if you open "Master.cs" script file with Visual Studio, you will see that you can't use intellisense to navigate to the parent class that it inherited from. But if you search for the same script file, either from search bar located top right corner or using solution navigator to find the file, and then opening it will let intellisense pick up the script file and it works like normal again.

Link to example Unity project:
https://drive.google.com/file/d/1LkA-oXgx-sCXany0g0iXVh4Vnad1XMvY/view?usp=sharing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12f6a983-3232-80c8-922f-29391d757d90
* Version Independent ID: edaf80a3-58fe-9e81-0b81-929a9284fe1d
* Content: [Visual Studio for Mac Tools for Unity - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/unity-tools)
* Content Source: [mac/unity-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/unity-tools.md)
* Product: **visual-studio-mac**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by mleesago** [comment]
Also tried to launch manually via command line "/Applications/Visual Studio.app/Contents/MacOS/VisualStudio" <PATH_TO_RESOLVED_SYMLINKED_FILE_PATH>;0;0 and this basically produces the same effect. So it seems that Visual Studio for Mac itself does not quite work well with symlinked files.

**Comment by conceptdev** [comment]
@mleesago thanks for your detailed feedback. If you're still experiencing these issues, please [report an issue using Visual Studio for Mac](https://docs.microsoft.com/visualstudio/mac/report-a-problem). This will create a [developer community](https://developercommunity.visualstudio.com/spaces/41/index.html) item that you can add to and discuss with the team. This issues list is primarily for documentation feedback but is not well-suited to tracking product problems.
