### ISSUE TITLE
How to troubleshoot if this happens frequently?

### ISSUE THREAD

**Issue by gojanpaolo** [MicrosoftDocs/visualstudio-docs#2165]
Hello. Is there a documentation on how we should proceed on to troubleshooting if this happens frequently? I use Live Unit Testing a lot and it stops working for me multiple times a day. I would need to restart the solution to get it working again.
Thank you! :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72292f7a-7616-4727-ccd3-cf44bb130477
* Version Independent ID: fe3cca82-dfd7-a85c-ab4f-014bc546d668
* Content: [A process has encountered an unrecoverable error - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/visual-studio-unrecoverable-process-error?view=vs-2017)
* Content Source: [docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@gojanpaolo I spoke to the devs for this area and we'd like you to please create an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, the product team can follow up with you more easily and hopefully get a repro of the crash. To create the issue, use the Help > Send Feedback > Report a Problem menu in Visual Studio.

After you have created the issue, please comment on this thread.

**Comment by gewarren** [comment]
@gojanpaolo Thank you! I'm closing this issue in favor of the developer community one.
