### ISSUE TITLE
Fast clicking breaks game (sometimes with exception thrown)

### ISSUE THREAD

**Issue by salomonsk8r2003** [MicrosoftDocs/visualstudio-docs#2167]
You should add this at the top of the `label_Click()` method:

`if (secondClicked != null) return;`

This way a fast clicking user doesn't get a third or more clicks until the game is ready (for another first click).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0c3b06a-a4e2-1d1c-1c92-b88c6ce0dda4
* Version Independent ID: 652bbf5e-ef1f-63c5-cafa-8e3a0d9f261a
* Content: [Step 9: Try other features - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-9-try-other-features?view=vs-2017)
* Content Source: [docs/ide/step-9-try-other-features.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-9-try-other-features.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by ornellaalt** [comment]
Hi @salomonsk8r2003, thanks for your feedback! I've added code that checks for the secondClick to  be reset to both the C# and VB code snippets (and provided the reasoning) on  [this page](https://docs.microsoft.com/en-us/visualstudio/ide/step-6-add-a-timer?view=vs-2017). Closing this issue now.
