### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by suhailmahmood** [MicrosoftDocs/visualstudio-docs#2168]
Take a look at the "Using --includeRecommended" section. It says to "Start an interactive installation of all workloads and components that are available in the Visual Studio 2017 Enterprise edition:"

    vs_enterprise.exe --all --includeRecommended --includeOptional

That's in fact nonsense. It gives the wrong impression that we need "--includeRecommended --includeOptional" to start an interactive installation of *all workloads and components*, whereas "--all" does the job, as mentioned in [this article](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2017#list-of-command-line-parameters) (look for the install option --all).

I have tested myself, just the following is what you need to "Start an interactive installation of all workloads and components that are available in the Visual Studio 2017 Enterprise edition:"

    vs_enterprise.exe --all

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017#using---includerecommended)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@suhailmahmood Thanks for your input. We'll take a look and update the documentation as necessary. @tydunkel FYI.

**Comment by tydunkel** [comment]
@suhailmahmood you are correct that `--all` is the only option needed to install all workloads and components, as `--all` will implicitly add `--includeRecommended` and `--includeOptional`. We will update the documentation to reflect this. Thank you for your feedback!

**Comment by TerryGLee** [comment]
@tydunkel Thanks for your response; the updates to the [Command-line parameter examples for Visual Studio 2017 installation](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017) page will go live mid-morning tomorrow.
