### ISSUE TITLE
There is no option for repair under more section

### ISSUE THREAD

**Issue by bhanuchhabra7** [MicrosoftDocs/visualstudio-docs#2169]
I am having vs installer for:
Visual Studio Community 2017
15.9.4

after clicking more only 2 options are there:
export configuration
import configuration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5c36c-d8ef-6b2d-2c62-5243d1ac2ce1
* Version Independent ID: 91c57e20-c75c-3c8d-e31f-727fa1e2af29
* Content: [Repair Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2017)
* Content Source: [docs/install/repair-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/repair-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @PoulChapman
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@bhanuchhabra7 Thanks for your inquiry; we'll investigate and report back. @tydunkel FYI.

**Comment by tydunkel** [comment]
@bhanuchhabra7 did you happen to open the menu under a non-installed product? In 15.9 the "Export configuration" and "Import configuration" buttons were added to both installed and non-installed products. This added a "More" dropdown to products available to install which may have lead to some confusion.

Installed product:
![image](https://user-images.githubusercontent.com/40210514/51137258-48f4b800-17f3-11e9-8c96-c2819aff37b5.png)

Non-installed product:
![image](https://user-images.githubusercontent.com/40210514/51137164-1945b000-17f3-11e9-9b0a-d169a18c49a3.png)

**Comment by TerryGLee** [comment]
@tydunkel Thanks for your response. I've updated the [Repair Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2017) page with this information. @bhanuchhabra7 We're going to close this issue; thanks again for your input.
