### ISSUE TITLE
How would you do it for a Dictionary?

### ISSUE THREAD

**Issue by gbelzile** [MicrosoftDocs/visualstudio-docs#2171]
Dictionary doesn't have a AddRange method. How would your replace its content without having a setter on the property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db6af07-b7d6-9395-223e-1a0f83fb2405
* Version Independent ID: 5ee87730-ff01-2571-494e-91d29c5fe211
* Content: [CA2227: Collection properties should be read only - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227-collection-properties-should-be-read-only?view=vs-2017)
* Content Source: [docs/code-quality/ca2227-collection-properties-should-be-read-only.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2227-collection-properties-should-be-read-only.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@gbelzile I'm guessing that for a Dictionary property you would just suppress this rule. @mavasani Can you confirm?

**Comment by msebolt** [comment]
Closing the issue due to inactivity.

Please try to suppress the rule for now and comment below if there are any issues.
