### ISSUE TITLE
Using WPF instead of WinForms

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#2176]
How would I go about using a WPF window instead of a WinForms window?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5d2403-0edc-8ee9-22f6-6ca370b40346
* Version Independent ID: d34a6007-354e-0bdb-3ad7-9f15a2cb56f2
* Content: [Write a visualizer in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2017)
* Content Source: [docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@zspitz Updated this doc so that steps are current with VS 2017 and VS 2019. Updating to a WPF sample will need to go on the backlog for now.
