### ISSUE TITLE
Cant find check in button on source control explorer on Mac

### ISSUE THREAD

**Issue by tessarolli** [MicrosoftDocs/visualstudio-docs#2177]
Hi,  have successfully connected to my project on VSTS, created a workspace, mapped and downloaded the solutions, run the solution on the Mac, no problem on that.
But I can't seen to find a way to checkin my code updates, the way I`m used to do on VS for Windows.
I did find an option when you right click a single file on the source control explorer, to checkin that file, but where is all my changes located, and how do I checkin all modified files at once?

**Comment by asb3993** [comment]
@jmatthiesen can you comment on this?

**Comment by jmatthiesen** [comment]
Hello! When using the TFVC extension your easiest way to check-in a file is to open a project in TFVC that uses that project, then you can use the Version Control menu to review changes and commit. Otherwise, the source control explorer doesn’t have an option for Check-in.
