### ISSUE TITLE
MSBuild 15.0 ignores publxml file when set to some location other than properties folder in the project.

### ISSUE THREAD

**Issue by UbaidBashir** [MicrosoftDocs/visualstudio-docs#2179]
Hi guys,
MSBuild fetches publish profile only from Properties folder. when i am trying to assign pubxml file to some other location it ignores. Could you help me with this

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb723883-dd62-0c53-8617-7bc867b9aaf3
* Version Independent ID: de1ff8ce-885c-9df0-077c-48c82f163c83
* Content: [What's New in MSBuild 15 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0?view=vs-2017)
* Content Source: [docs/msbuild/what-s-new-in-msbuild-15-0.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/what-s-new-in-msbuild-15-0.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by UbaidBashir** [comment]
This actually happens only with .NetCore applications.

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, is there a way to use another location for the Properties folder?

**Comment by rainersigwald** [comment]
I believe that's an ASP.NET concept. @Rick-Anderson, it looks like you've touched some of the ASP.NET deployment documentation recently. Can you help or help route?

**Comment by UbaidBashir** [comment]
When i try to deploy .Net Core application by using Publish profile, it cant read the pubxml file. i also try to give complete path of pubxml path but the problem still is there.
This is what i am trying to do
$msbuildExe = "C:\Program Files (x86)\Microsoft VisualStudio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe"

$filePath = "C:\Projects\PublicApi\src\DeveloperPortal\DeveloperPortal.csproj"
$pxmlUID="XXXXXXXXX"
$pxmlPWD="XXXXXXXXX"
$pxmlPath = "C:\Test\Base.pubxml"

&$msbuildExe $filePath, '/p:DeployOnBuild=true',"/p:PublishProfile=$pxmlPath","/p:Username=$pxmlUID", "/p:Password=$pxmlPWD", '/p:Configuration=Release', '/p:AllowUntrustedCertificate=True', '/p:WarningLevel=0', '/p:verbosity=quiet', '/p:MvcBuildViews=false'

This only happens with .Net Core applications
Could you please help me with this. Thank you

**Comment by UbaidBashir** [comment]
Same behavior with below command

dotnet publish C:\Test\ASP.netCOre\ASP.netCOre\ASP.netCOre.csproj /p:PublishProfile=C:\Test\Base.pubxml /p:Username=$pxmlUID /p:Password=$pxmlPWD

**Comment by Mikejo5000** [comment]
@UbaidBashir If you'd like to report a bug, please use the "Send Feedback" link in the upper right of the Visual Studio IDE.

**Comment by Mikejo5000** [comment]
Closing, as [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) is the correct place to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
