### ISSUE TITLE
msbuild task documentation missing for new tasks: hash

### ISSUE THREAD

**Issue by japj** [MicrosoftDocs/visualstudio-docs#2180]
It seems that the msbuild task reference documentation is missing for several "new" tasks:

Tasks/Hash.cs
Tasks/FileIO/GetFileHash.cs
Tasks/FileIO/VerifyFileHash.cs

**Comment by Mikejo5000** [comment]
We have docs for GetFileHash and VerifyFileHash.
https://docs.microsoft.com/en-us/visualstudio/msbuild/getfilehash-task?view=vs-2017
https://docs.microsoft.com/en-us/visualstudio/msbuild/verifyfilehash-task?view=vs-2017
@rainersigwald Are there plans to doc Hash as well, or is it not needed?
