### ISSUE TITLE
Incomplete uninstall instructions

### ISSUE THREAD

**Issue by stefankreitmayer** [MicrosoftDocs/visualstudio-docs#2181]
Under the heading "Uninstall Visual Studio for Mac", it says:

> To remove all traces of Visual Studio for Mac, run the following commands in Terminal

Apparently, these commands **don't** remove all traces of Visual Studio for Mac. Deleting the folder  `~/.vscode` manually wasn't a big deal. However, I am left with an uneasy feeling about what other traces may be left after following the instructions.

Could someone please clarify?

**Comment by asb3993** [comment]
Adding to PR, note should be added shortly.
