### ISSUE TITLE
VS 2017 crashes and restart when i update the database 

### ISSUE THREAD

**Issue by tachf** [MicrosoftDocs/visualstudio-docs#2182]
VS 2017 crushes when i try to update the  SQL server database file  tables, and restart not saving any file, i find it more easier to work with databases in VS 2008.
any help !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d19e1d-1448-e5b3-6580-9b11042e03ab
* Version Independent ID: 549472fa-f3be-53bc-cf9f-170c1183c834
* Content: [Create a database file and use table designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2017)
* Content Source: [docs/data-tools/create-a-sql-database-by-using-a-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-sql-database-by-using-a-designer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@tachf Since this is a product issue, please log your issue on Developer Community by choosing Help > Send Feedback > Report a Problem in Visual Studio. @stevestein FYI.
