### ISSUE TITLE
Reset performance warnings

### ISSUE THREAD

**Issue by jauseg** [MicrosoftDocs/visualstudio-docs#2183]
I have fixed my extension.
But the Visual Studio continues messaging me about performance warning.
How I can reset this warning with saving all other IDE preferences?

**Comment by gewarren** [comment]
@varunguptacode or @aditya-kadam can you comment on how the user can disable the performance warning?

**Comment by jauseg** [comment]
I am sorry. I want to clarify. I need to reset only not disable. I want to check if this warning will not show again. I am sorry.

**Comment by jauseg** [comment]
Thank you for the advice. I did not try to update the version. I`ll try to do this after the weekends.
