### ISSUE TITLE
Description of Format Document settings

### ISSUE THREAD

**Issue by Nk54** [MicrosoftDocs/visualstudio-docs#2186]
It would be nice to see exemple of those action.
I would like to see the result.

The description is like adding such comment to a method :
/// Save a person.
///&lt;param name="person"&gt;the person&lt;/param&gt;
SavePerson(Person person)

You can't do that in 2019 :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf1a218-2295-22ac-03eb-1ccc63b4a3e6
* Version Independent ID: baa311a7-6b87-6196-ae8a-b8759a1df73c
* Content: [C# editor formatting options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-formatting?view=vs-2017)
* Content Source: [docs/ide/reference/options-text-editor-csharp-formatting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-formatting.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
It would be worthwhile to copy the settings mapping from [this section for VS 2017](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-formatting?view=vs-2017#format-document-settings) to [this section about Code Cleanup in VS 2019](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#apply-code-styles). At the same time, we could add examples of each preference.

Meanwhile @Nk54 you can check the "preview" window at the bottom of the Tools > Options > Text Editor > C# > Code Style dialog box for examples:

![image](https://user-images.githubusercontent.com/24882762/58599754-7daf5c00-8236-11e9-8489-ea41d413ed8b.png)

**Comment by TerryGLee** [comment]
@Nk54 Apologies that it's taken us some time to report back. Per our colleague's earlier suggestion, we've added a work item to our backlog queue to copy the settings mapping from [this section for VS 2017](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-formatting?view=vs-2017#format-document-settings) to [this section about Code Cleanup in VS 2019](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#apply-code-styles), and then possibly add examples of each preference.

Meanwhile, it looks as if our colleague addressed your original inquiry about how you could use the "preview" window at the bottom of the **Tools** > **Options** > **Text Editor** > **C#** > **Code Style** dialog box for examples.

We'll close this issue now, with our thanks to you for your feedback. We hope to hear from you again if you have suggestions on how we can improve the documentation.
