### ISSUE TITLE
Msbuild 15.0 ignores pubxml file when kept at any location other than properties->publishprofiles

### ISSUE THREAD

**Issue by UbaidBashir** [MicrosoftDocs/visualstudio-docs#2187]
Hi,

Currently i am facing an issue where in i want to keep Pubxml file at any location other than the solution folder. When i try to do that the MSbuild cant read that file. i also tries to give complete path but the problem still is there.
This is what i am trying to do
$msbuildExe = "C:\Program Files (x86)\Microsoft VisualStudio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe"

$filePath = "C:\Projects\PublicApi\src\DeveloperPortal\DeveloperPortal.csproj"
$pxmlUID="XXXXXXXXX"
$pxmlPWD="XXXXXXXXX"
$pxmlPath = "C:\Test\Base.pubxml"

&$msbuildExe $filePath, '/p:DeployOnBuild=true',"/p:PublishProfile=$pxmlPath","/p:Username=$pxmlUID", "/p:Password=$pxmlPWD", '/p:Configuration=Release', '/p:AllowUntrustedCertificate=True', '/p:WarningLevel=0', '/p:verbosity=quiet', '/p:MvcBuildViews=false'

This only happens with .Net Core applications
Could you please help me with this. Thank you

**Comment by Mikejo5000** [comment]
@UbaidBashir Hi, this appears to be a product support issue. If you'd like to report a bug, please use the "Send Feedback" link in the upper right of the Visual Studio IDE.
