### ISSUE TITLE
"Context menu" is not defined; and more screenshots would be better

### ISSUE THREAD

**Issue by mysunnytime** [MicrosoftDocs/visualstudio-docs#2189]
This doc mentioned 6 times about a "context menu", but never define what is a context menu. I was about to try how to add new playlist (https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2017#create-custom-playlists), but I can't find the "context menu" mentioned here - this is frustrating to a reader.

Also, I hope there are more screenshots/pictures than text description, which can let the reader capture the idea at the first sight.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3681419-a041-da72-a134-37401922a536
* Version Independent ID: 57b6194d-cb07-0e89-8f38-544bf4ce9816
* Content: [Run, build, and debug unit tests with the Test Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2017#create-custom-playlists)
* Content Source: [docs/test/run-unit-tests-with-test-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/run-unit-tests-with-test-explorer.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I've fixed the context menu jargon issue. Thanks for letting us know! We are also aware from customer studies that they like screenshots and code samples, so thank you for that feedback too.
