### ISSUE TITLE
no else

### ISSUE THREAD

**Issue by stevev6** [MicrosoftDocs/visualstudio-docs#2192]
The issue with the text it gives: If { you do not have or do not want to use debugging information) 
then do 3 steps
else ...good luck sucker.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 355a0abd-dc5f-5db3-ad95-c37fd2d3dc0f
* Version Independent ID: 86138b4b-4c7f-4113-dd9e-afcb442cb1e0
* Content: [How to: Debug COM Servers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-com-servers?view=vs-2017)
* Content Source: [docs/debugger/how-to-debug-com-servers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-com-servers.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@stevev6 The content here is also included in the [parent topic](https://docs.microsoft.com/en-us/visualstudio/debugger/com-server-and-container-debugging?view=vs-2017), along with some additional scenarios (such as container debugging). In fact, this topic looks extraneous so I'll remove it. Let me know if you have any specific suggestions. Thanks!
