### ISSUE TITLE
Unable to checkout folders

### ISSUE THREAD

**Issue by shgzon** [MicrosoftDocs/visualstudio-docs#2194]
I am only able to check-out specific files not an entire folder. For that reason it is a really time consuming process to work with TFS on Visual Studio for Mac.

It gives this error when trying to checkout any folder: 
TF14040: The folder $/path_to_folder may not be checked out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [Team Foundation Version Control (TFVC) - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by keithrz** [comment]
@shgzon Thank you for this message!  It's good to see the issue narrowed down to Mac.  I am experiencing the same issue.

@jmatthiesen Do you know of any workarounds that are less time-consuming than checking out each individual file?  It can be a huge pain to do this with even a normal-sized project.

**Comment by mattisthenation** [comment]
Thanks also for bringing this up. I've been having the same issue. I can checkout one file at a time, but not a folder. I get the same TF14040.

Has anyone found a workaround in the meantime?

**Comment by SrimanPilli** [comment]
Installed TFS/Azure from extensions version control
then,
From Mac -> version control -> Team Explorer / Open from remote repository is not enables to click on that ?
whats wrong with that ?

**Comment by conceptdev** [comment]
Thanks everyone for your feedback. It will be helpful if you can use the [report a problem](https://docs.microsoft.com/visualstudio/mac/report-a-problem) menuitem when these issues occur, so that the relevant logs and system information are provided for troubleshooting.

**Comment by asb3993** [comment]
@jmatthiesen can you comment on this? thanks

**Comment by jmatthiesen** [comment]
Thanks for your feedback about the Team Foundation Version Control extension. Unfortunately, at this time we’re focusing our efforts in Visual Studio for Mac on improving our support for Git and we don’t have plans to continue working on Team Foundation Version Control support. You could try some of the other options mentioned in this document. Sorry I couldn’t be more helpful!
