### ISSUE TITLE
Main page has a broken link to What's new in IDE

### ISSUE THREAD

**Issue by mrcaron** [MicrosoftDocs/visualstudio-docs#2197]
I found a broken link on the main page. "What's New in Visual Studio 2017" points to Intro to C#.

I fixed it in https://github.com/MicrosoftDocs/visualstudio-docs/pull/2196. Unfortunately the PR bot didn't seem to know who to send it to for approval?

![image](https://user-images.githubusercontent.com/72183/51056609-dee8d280-15a8-11e9-984c-16a22f82a936.png)

**Comment by Jak-MS** [comment]
@mrcaron - I've assigned the other PR #2196 to the author for approval. thanks.

Please close this PR; we'll move forward with the other PR.
