### ISSUE TITLE
This page should be for C26402

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/visualstudio-docs#2200]
You've got the C26401 content on the C26402 page.

I sure would like to read about C26402 DONT_HEAP_ALLOCATE_MOVABLE_RESULT

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca5168d1-cf30-c466-23ae-533e08a7b25d
* Version Independent ID: 86e51007-6648-172e-90f7-10002f27f08f
* Content: [C26401 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26402?view=vs-2017)
* Content Source: [docs/code-quality/C26402.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26402.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
This topic now refers to the correct warning, albeit with minimal content. Should be live by Sept 6.
