### ISSUE TITLE
installer (and VS) is crashing

### ISSUE THREAD

**Issue by NenadSteric** [MicrosoftDocs/visualstudio-docs#2202]
how can i send a report then ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* Content: [How to report a problem with Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio-2017.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by tydunkel** [comment]
@NenadSteric thank you for the feedback! Sorry you are having this issue. Is this a recent issue? Have both the installer and VS worked in the past? Have you added a NODE_OPTIONS environment variable recently?

**Comment by TerryGLee** [comment]
@NenadSteric We haven't heard back from you for a while and so we'll close out this issue now (3/4/19). If you are still experiencing the problem that you outlined (and we hope that you aren't), please feel free to reply to this GitHub Issue or open a new one.

**Comment by NenadSteric** [comment]
Yes it was the systemwide NODE_OPTIONS which i had to remove.
The bad thing is that there is no indication whatsoever in the logs - visual studio just closed when i opened a solution and the installer just disappeared and crashed without trace.
