### ISSUE TITLE
Open the Visual Studio Installer failed with one of the call to GetModuleHandleExW

### ISSUE THREAD

**Issue by Funcer8** [MicrosoftDocs/visualstudio-docs#2203]
I could not even open the Visual Studio Installer!
So I use the API Monitor to monitor the vs_installer.exe under the "C:\Program Files\Microsoft Visual Studio\Installer", and it showed that after the call to GetModuleHandleExW ( 0, "mscoree.dll", 0x002ffb6c ) failed with error code 126, the process exited itself with ExitProcess function.In addition, mscoree.dll was not in the list of the loaded modules of the process provided by API Monitor.
The version of the Dot Net Framework in my computer is 4.7.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-dev15**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by tydunkel** [comment]
@Funcer8 this sounds like you may have a corrupted .NET Framework installation. Are you able to run any .NET applications on the system?

**Comment by TerryGLee** [comment]
@Funcer8 Since we haven't heard back, we're going to close this issue for now. If you do have further input, please do feel free to add it to this issue, and if we need to re-open it, we will.
