### ISSUE TITLE
Better documentation for DebugType (mention embedded)

### ISSUE THREAD

**Issue by KirillOsenkov** [MicrosoftDocs/visualstudio-docs#2204]
https://github.com/tmat should update the DebugType section with embedded option as well as clarify that pdbonly is useless and should never be used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caef0578-7b6a-6b5a-8cc4-268ddb2fb743
* Version Independent ID: a99db5b2-2ff5-a675-95c2-333db10231ff
* Content: [Csc Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/csc-task?view=vs-2017)
* Content Source: [docs/msbuild/csc-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/csc-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@KirillOsenkov pdbonly Do you mean it is useless for debugging purposes? In the -debug compiler docs, it looks like they recommend -pbdonly or no pdb's for release code, so I would need to be careful about wording. If you have a link, that would be great.

**Comment by tmat** [comment]
It is clarified here: https://github.com/dotnet/roslyn/blob/master/docs/compilers/CSharp/CommandLine.md

**Comment by Mikejo5000** [comment]
Thanks, looks to me like the compiler docs are out of date here, but I can update this doc. @mairaw

**Comment by KirillOsenkov** [comment]
I see, that's what I thought. `pdbonly` is identical to `full`, is obsolete and should not be used.

**Comment by BillWagner** [comment]
I think this is a duplicate of #6773

I'll close this, and continue tracking there.
