### ISSUE TITLE
Navigation code behind not quite minimal

### ISSUE THREAD

**Issue by OldVSDeveloper** [MicrosoftDocs/visualstudio-docs#2206]
The navigation 'next' and 'previous' command handlers require further work since it is possible to navigate off the beginning and off the end of the data using them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c0fa43-0ca5-9c86-f8c4-4b3eb7176250
* Version Independent ID: bb93e3ff-0d52-9e93-c3a8-545b16f03a30
* Content: [Create a simple data application with WPF and Entity Framework 6 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2017)
* Content Source: [docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by OldVSDeveloper** [comment]
?Sorry for not getting back sooner.   Thanks for message.  In your piece you state that the navigation code behind is minimal.  However, I found that by directly implementing the tutorial, the navigator would appear to move before the beginning of the collection or past the end of the collection (by repeatedly pressing the left arrow, or repeatedly pressing the right arrow, respectively).  In my attempt at implementing the tutorial, I simply checked whether the Current position was, say, at the end of the Collection before implementing MoveCurrentToNext.  If it was at the end of the Collection, then do nothing.  I guess the ICollectionView.MoveCurrentToNext may return an error if the current position is at the end of the Collection, but I haven't tried that.

The context of the comment was that the Windows Forms implemented a Navigation Toolbar which managed the Navigation through Collections.  However, in WPF this is no longer true.  This seems a retrograde step.


Dr David Haworth,
MD, MalvteQ Ltd.
Tel: +44(0)1905 429010
e-mail: dphaworth@malvteq.com

This e-mail contains information that is confidential to MalvteQ Ltd.  Some or all of the  information may be legally privileged.  It is for the intended recipient only.  If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to this e-mail. If you are not the intended recipient, you must not use, distribute, print or rely on this e-mail.
________________________________

**Comment by gewarren** [comment]
@OldVSDeveloper Okay, thanks for the clarification that the article needs to be updated.

**Comment by OldVSDeveloper** [comment]
I suggest if you were to update the article, standard CRUD functionality should be addressed, including the situation where a customer has no orders, none of the customers have any orders  and where there are no customers and no orders (eg when the underlying database has just been created)

**Comment by jotway** [comment]
I have found this example immensely helpful in learning C#/WPF/EF6.
Recently I added TextChanged and SelectedDateChanged events which did some arithmetic that failed when I paged outside of my record set.  I paged outside the recordset because the tests  IsCurrentBeforeFirst and IsCurrentAfterLast are applied after you are out-of-bounds.

My solution is as follows.

`        private void NextOrgUnitAssetRskCommandHandler(object sender, ExecutedRoutedEventArgs e)               //Next record
        {
            numberOfOrgUnitAssetRskRecords = orgUnitAssetRskViewSource.View.SourceCollection.Cast<OrgUnitAssetRsk>().Count();    //  Count the records in the view.
            if ((numberOfOrgUnitAssetRskRecords - 1) > orgUnitAssetRskViewSource.View.CurrentPosition)        //  Subtract 1 to compensate for zero-based CurrentPosition.
            {
                orgUnitAssetRskViewSource.View.MoveCurrentToNext();
                selectedRecordPosition = orgUnitAssetRskViewSource.View.CurrentPosition;
            }
        }

        private void PreviousOrgUnitAssetRskCommandHandler(object sender, ExecutedRoutedEventArgs e)           //Previous record
        {
            if ((0) < orgUnitAssetRskViewSource.View.CurrentPosition)        //  0 to compensate for zero-based CurrentPosition.
            {
                orgUnitAssetRskViewSource.View.MoveCurrentToPrevious();
                selectedRecordPosition = orgUnitAssetRskViewSource.View.CurrentPosition;
            }
        }
`
Probably not very elegant but I'm struggling to get on top of this stuff.

**Comment by jotway** [comment]
I have found this application immensely helpful in learning WPF/EF6.  It is the best pattern I have been able to find.
Paging back and forward through the viewsource needs to be controlled to prevent the user paging out of bounds and executing SelectedDateChanged and TextChanged events with spurious data lurking outside the bounds of the viewsource..
Nevertheless a very valuable learning aid.

**Comment by gewarren** [comment]
This topic gets about 7000 page views per month.

**Comment by Faraz2018** [comment]
Well! Obviously the said article needs to be updated, it's worthy for sure!
However, while starting learning WPF with the same, came across to note that while I am debugging the same and the app is in running, at the same time if I change any value of a Northwind's table (via SSMS or Access Front-End) the WPF doesn't reflect the updated data via custViewSource.View.Refresh();
How to overcome this with an event like timer or a button click any other event?
