### ISSUE TITLE
Content desolately outdated

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#2207]
@SetTrend commented on [Wed Dec 26 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/31)

Documentation of the Options pages doesn't reflect the actual content of Tools &gt; Options at all.

This is true for many of the Options pages.

Please revise urgently. What option am I supposed to choose if I don't know that that option is all about?

### Example

![options example](https://user-images.githubusercontent.com/9283914/50450552-16137e80-092f-11e9-98be-e019e82b8f58.png)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4d00f758-96fa-f849-18b7-350e5d5ec107
* Version Independent ID: a79f1c88-5b93-5aa1-d948-91a5d21609b5
* Content: [Optionen, Text-Editor, Standard (VB), Erweitert - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/ide/reference/options-text-editor-basic-visual-basic?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.Basic.Advanced)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/ide/reference/options-text-editor-basic-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/ide/reference/options-text-editor-basic-visual-basic.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

---

@gewarren commented on [Wed Dec 26 2018](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/31#issuecomment-450003647)

@craigcaseyMSFT FYI.
@SetTrend Thanks we are aware and working on it!

---

@CeciAc commented on [Mon Jan 14 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/31#issuecomment-454056663)

@gewarren @craigcaseyMSFT 
Any update on this?
Should I move this to the en-us repro to work on it better?

---

@gewarren commented on [Mon Jan 14 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/31#issuecomment-454083256)

@CeciAc Can you move this to the en-us repo please? We are still actively working on updating the options pages.

**Comment by gewarren** [comment]
@CeciAc Thanks Cecilia!

**Comment by gewarren** [comment]
This [particular article](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-basic-visual-basic?view=vs-2017) was updated 3 days ago to include the new options. The rest are coming shortly and are being tracked by an internal work item.
