### ISSUE TITLE
Msbuild Import Project Note is not valid and need correction

### ISSUE THREAD

**Issue by moh-hassan** [MicrosoftDocs/visualstudio-docs#2210]
The note for Import Eelement isn't valid at:
 https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017

It causes a trouble with that issue in msbuild project: https://github.com/Microsoft/msbuild/issues/4070

Document say:
&gt;While conditional import statements work in command-line MSBuilds, they do not work with MSBuild in the Visual Studio integrated development environment (IDE)

This is wrong, conditional import is working in vs 2017.9.5

also, it says:
&gt;To work around this, put conditional imports in the .targets files or put code in a conditional block such as a Choose element (MSBuild) block.

The correction is: Choose element isn't supporting Import.

For details review the issue at msbuild: https://github.com/Microsoft/msbuild/issues/4070

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af512ce8-46bd-b15a-c5a2-f8315d2b258a
* Version Independent ID: e2c221b8-466f-df7f-078c-bab89be71828
* Content: [Import Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2017)
* Content Source: [docs/msbuild/import-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/import-element-msbuild.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Getting fixed in #2213
