### ISSUE TITLE
Confirmation Email

### ISSUE THREAD

**Issue by ericnewton76** [MicrosoftDocs/visualstudio-docs#2211]
Would it make sense to put a link wherever the "Confirmation pending for contact email" is displayed?

INstead of having to search for "How to I confirm my email for azure" or "VSTS team profile" or whatnot?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bbbde6d-478e-b19c-4592-484bbab98acc
* Version Independent ID: 162585c5-1bf2-af83-caba-3fd0c3719ccb
* Content: [How to Resend Subscription Assignment Emails from Within Manage.visualstudio.com or VLSC](https://docs.microsoft.com/en-us/visualstudio/subscriptions/resend-assignment-email)
* Content Source: [subscriptions/resend-assignment-email.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/resend-assignment-email.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by ericnewton76** [comment]
Actually this isnt even the correct place.  GRRR.

On my Azure DevOps profile, I see "Confirmation pending for contact email" at this url: https://aex.dev.azure.com/me?campaign=o~msft~vsts~usercard&tab=home&mkt=en-US

UX needs to examine that...

**Comment by evanwindom** [comment]
@ericnewton76 - Hi Eric.  You're right -- your feedback is actually more applicable to Azure DevOps.  You can explore their documentation and submit your feedback here:  https://docs.microsoft.com/en-us/azure/devops/?view=vsts 

Thanks!
Evan
