### ISSUE TITLE
Not available on Visual Studio for Mac?

### ISSUE THREAD

**Issue by christiand** [MicrosoftDocs/visualstudio-docs#2216]
This window doesn't appear to exist

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1b431a-4afc-27ae-b2d9-0d1299eba257
* Version Independent ID: 72c6c954-6989-4ca7-1db4-38d6ac3f3c40
* Content: [Using the Tasks Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-tasks-window?view=vs-2017)
* Content Source: [docs/debugger/using-the-tasks-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-the-tasks-window.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@christiand Hi, all the Visual Studio for Mac doc are here:
https://docs.microsoft.com/en-us/visualstudio/mac/
Features supported in VS for Mac would be under the Debugging node.
