### ISSUE TITLE
Windows 8.1 SDK

### ISSUE THREAD

**Issue by uljo2** [MicrosoftDocs/visualstudio-docs#2218]
Is it the installation of SDK 8.1 through VS BuildTools that has isses, or would it be possible to install Windows 8.1 SDK in another way?

Is it something that will be fixed so that it is supported in the future?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-gb/visualstudio/install/build-tools-container?view=vs-2017)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-dev15**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@uljo2 Thanks for your feedback; @heaths FYI.

**Comment by heaths** [comment]
I've forwarded this question to someone who can better answer it for the Windows SDK.

**Comment by heaths** [comment]
We can't guarantee it will work in all Windows Server Core container images, so you can try in whatever image you require and see if it worked. The issues that necessitated excluding them from the example Dockerfiles ocurred during install so you should know right away whether setup worked or not based on whether it returned 0 or 3010 (`ERROR_REBOOT_REQUIRED`, which contains actually don't support doing).

**Comment by TerryGLee** [comment]
@heaths Thanks for your input here :)
@uljo2 Per request from HeathS, I am closing this issue.
