### ISSUE TITLE
Modifying the msbuild default build system

### ISSUE THREAD

**Issue by MirceaStroe** [MicrosoftDocs/visualstudio-docs#2225]
I am developing an iOS & Android white label app in Xamarin and aim is to add some customization to the building process, ideally outside Visual Studio.

It would be great to selectively choose what files will reach the compiler, App Icons & Resx translation files in special, like specify custom locations from which these will be picked up during building. 

How would I be able to accomplish this?

**Comment by conceptdev** [comment]
There is no Xamarin-specific msbuild advice, but you can review capabilities in the [msbuild documentation](https://docs.microsoft.com/visualstudio/msbuild/msbuild?view=vs-2019).

There are also a number of open-source/community projects and blogs about white labeling Xamarin apps that you can search for.
