### ISSUE TITLE
Debugging does not work as you say it will

### ISSUE THREAD

**Issue by DulcetTone** [MicrosoftDocs/visualstudio-docs#2228]
I have set VS as the editor for Unity scripts, and it indeed opens them when I click on them within Unity.

However, within VS, pressing Command+enter does nothing, as the "play" icon in VS is instead a hammer icon, most of the time.

I have seen it TRY to work, when the hammer was indeed a play symbol, but it did not seem to function in any way.  Instead, it appeared to run some tests.  Likewise, Attaching the debugger to a process seems to work, but you can never pause a running Unity standalone app: it presents a pop-up saying as much.

I am running your 7.7.3 and Unity 2017.3

Tony

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55502210-e9fc-ac0a-acd2-f505d3626b57
* Version Independent ID: bdd0ad92-67f6-64f3-b9e1-26ca89230d4b
* Content: [Using Visual Studio for Mac Tools for Unity - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/using-vsmac-tools-unity)
* Content Source: [mac/using-vsmac-tools-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/using-vsmac-tools-unity.md)
* Product: **visual-studio-mac**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by greay** [comment]
same here, except sometimes it works for some projects and not others and I really have no idea why.

**Comment by therealjohn** [comment]
@DulcetTone, @greay 

Thanks for raising this and I apologize things are not working as expected. Have you tried any of the suggestions in [our troubleshooting guide](https://docs.microsoft.com/en-us/visualstudio/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity?view=vs-2017)? 

If you've tried the relevant tips in there and things are not working, please report a bug via the Help > Send Feedback > Report a Problem menu in Visual Studio for Mac. That will be a better way for us to track the issue and followup quickly. This area is for bugs related to documentation. Thanks!
