### ISSUE TITLE
Can't find CLSID_ProgramPublisher

### ISSUE THREAD

**Issue by jordan83** [MicrosoftDocs/visualstudio-docs#2229]
Where does this guid come from? I assumed it would be somewhere in VSConstants but I'm unable to find it. Is this doc up to date?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64fee83a-3045-6c0d-0fd7-6d072f4a20f3
* Version Independent ID: 90ddf5d5-67f5-e1d5-103c-ac6bc35236c3
* Content: [IDebugProgramPublisher2 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/reference/idebugprogrampublisher2?view=vs-2017)
* Content Source: [docs/extensibility/debugger/reference/idebugprogrampublisher2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/debugger/reference/idebugprogrampublisher2.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @jordan83 You can get the CLSID from the msdbg.h header file mentioned in the Requirements section.

```
EXTERN_C const CLSID CLSID_ProgramPublisher;

#ifdef __cplusplus

class DECLSPEC_UUID("d04d550d-1ea8-4e37-830e-700fea447688")
ProgramPublisher;
#endif
```

**Comment by jordan83** [comment]
Thanks Greg. Is there a way to access this constant from C#?
