### ISSUE TITLE
Add a doc to show publish to App Service from VSMac

### ISSUE THREAD

**Issue by sayedihashimi** [MicrosoftDocs/visualstudio-docs#2230]
It looks like we don't have a doc covering publishing to Azure App Service from VSMac.

I am working on a doc and will submit a PR today.

cc @Rick-Anderson

**Comment by Rick-Anderson** [comment]
I'll add a link to that doc to our TOC
![image](https://user-images.githubusercontent.com/3605364/51408218-1522d680-1b02-11e9-8a7f-7f74f7050f44.png)

and we can add the link to next steps in our other tutorials.
cc @tdykstra

**Comment by sayedihashimi** [comment]
@asb3993 I've submitted a PR for this content in the private repo. @Rick-Anderson has reviewed, and I made all the changes he requested. I think it now needs to get approved and merged, I'm not sure if there is any other action that I need to take here. Please let me know if there is.

**Comment by tdykstra** [comment]
Sure, but I advise waiting a bit on the TOC as we're in the middle of converting from MD to YAML, and the convert-to-YAML PR is stuck at the moment.  What else besides Pub to App Svc from VSMac do you need to add to the TOC?

**Comment by sayedihashimi** [comment]
@tdykstra ok, I see. I have a new PR out for a new doc covering **Publish to Folder**.

**Comment by Rick-Anderson** [comment]
@sayedihashimi 	when your doc is published, create a new issue in https://github.com/aspnet/Docs asking @tdykstra 	to link to your doc. He can do the work.

**Comment by sayedihashimi** [comment]
Sounds good, thanks guys.

**Comment by asb3993** [comment]
@sayedihashimi if this is merged are you happy to close it?

**Comment by sayedihashimi** [comment]
Yes closing
