### ISSUE TITLE
What about VSIX deployment? And the Project Template template?

### ISSUE THREAD

**Issue by leithmc** [MicrosoftDocs/visualstudio-docs#2234]
This is the most helpful doc I've been able to find for my scenario. Can we update it to include the VSIX deployment? When I follow the VSIX docs it assumes single project in the same solution.
Also, it would be nice to cover the scenario for people creating their templates from the Project Template template in the SDK if that's still a recommended scenario, and if it's not, it would be good to know that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e208-2a2a-9fc3-98ff-147540157f32
* Version Independent ID: 5f5c9adf-da1d-ec0b-8af3-ccd2e27eaadc
* Content: [Create multi-project templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2017)
* Content Source: [docs/ide/how-to-create-multi-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-multi-project-templates.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@leithmc Have you taken a look at this article? https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-custom-project-and-item-templates?view=vs-2017

**Comment by leithmc** [comment]
Yes I have. A few times.
I tried going that route early on but it creates a template for a class library by default, and when I tried to make it create a console application I ran into all sorts of errors, eventually gave up, and went back to using the Export Template wizard.

Coincidentally, I wrote the first version of that doc in 2007 (or the doc it replaces.) The current version is much better than mine was but it still doesn't get me to my goal, which is a template that outputs a console app and a test project and includes a NuGet.
I was able to get everything but the NuGet working with the Export Template wizard and following the steps here: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2017
[https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png]<https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2017>

Create multi-project templates - Visual Studio | Microsoft Docs<https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2017>
Multi-project templates act as containers for two or more projects. When you create a project that is based on a multi-project template from the New Project dialog box, every project in the template is added to the solution. A multi-project template has two or more project templates, and a root ...
docs.microsoft.com




Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by leithmc** [comment]
BTW, I sent a more detailed version through my MS account. Forwarding that to your work mail now....
Look for subject: FW: Packages in Visual Studio templates -- doc feedback and question


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by KKacer** [comment]
What if when we want to put several projects and their directories in a custom physical folder, for example: "Business Logic" ?

**Comment by d4e666** [comment]
it would also be convinient to 
1. have the naste "additional folder" bug solved
2. put all the code here for the wizard extension that is a workaround for this in the meanwhile

**Comment by jacksinclairaudley** [comment]
This really looks to be a workaround for missing functionality in the 'export project template' wizard. These steps should really be part of the wizard as it's a common use case to want to export a solution template rather than a single project.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
