### ISSUE TITLE
Unable to Sign In on the Visual Studio Developer Community Page

### ISSUE THREAD

**Issue by RobDev23** [MicrosoftDocs/visualstudio-docs#2235]
The Visual Studio Developer Community page has a 'Sign In' link, however the link is dead. It does nothing when clicked and I am, therefore, unable to sign in. So I can't follow the progress of my Visual Studio suggestions and reported errors. Can you tell me what's happening here, please?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd373ab5-4b8b-8289-c735-22512e42a26c
* Version Independent ID: c166ffd0-f201-ebec-643f-c4535c4aa652
* Content: [Talk to us - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/talk-to-us?view=vs-2017)
* Content Source: [docs/ide/talk-to-us.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/talk-to-us.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@RobDev23 Thanks for your feedback, and I'm sorry to hear that you've experienced this issue. Unfortunately, however, I've not been able to repro it. I've logged onto the [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) by using two different accounts on two different computers and also by using three different browsers (Edge, Chrome, Firefox), and the sign-in is working for me. Perhaps this was a temporary anomaly for you? Are you still unable to sign in?

**Comment by RobDev23** [comment]
Hi @TerryGLee, many thanks for your reply. I’ve always accessed the Developer Community website via IE11, which is the browser that showed up the ‘sign in ‘ anomaly. However, when I access the website using the Edge browser the ‘Sign In’ link is active and I’m able to sign in. Is it official that the Developer Community website no longer supports IE11? If so, why didn't anybody tell me?

Also, are there any other Microsoft websites that no longer support IE11?

**Comment by gewarren** [comment]
@seaniyer for comment about browser support.

**Comment by RobDev23** [comment]
Hi Genevieve,

I’ve tried finding info about browser support from @seaniyer. Unfortunately, I can’t find any browser support info from that user on GitHub. Can you please supply me with the browser support info or, at least, a link to where I can find it.

Kind regards,

Robert Ashcroft

**Comment by seaniyer** [comment]
@RobDev23 

Hi Robert, 

Thank you for making us aware of the sign in issue on IE11.  At this time, we strongly recommend using Edge over IE11 for Developer Community as we prioritize support for optimal experience on Edge.

- Sean

**Comment by RobDev23** [comment]
Hi Sean,

if, at some point, you’re going to fix the ‘Sign In’ issue with IE11 then could you also fix another problem with it; only a small fragment of the ‘reported problem’ on the Developer Community site is being displayed by IE11. The ‘Show’ link does not work either.

IE11 is still a very popular browser, it would be nice is you could keep it working alongside Edge.

Kind regards,

Robert Ashcroft

**Comment by gewarren** [comment]
@RobDev23 If you'd like to request features or browser support for Developer Community, please file a new suggestion there instead.
