### ISSUE TITLE
So, where is this mysterious XML Editor?

### ISSUE THREAD

**Issue by LJ9999** [MicrosoftDocs/visualstudio-docs#2237]
You refer to something I have no clue how to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65ceeabd-a020-1121-fc1d-7631655455da
* Version Independent ID: 2fc5375e-2133-dc60-6c34-21ab4e0b7307
* Content: [XML editor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xml-tools/xml-editor?view=vs-2017)
* Content Source: [docs/xml-tools/xml-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xml-tools/xml-editor.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by NextTurn** [comment]
Open any XML file and Visual Studio will become an XML editor. To

**Comment by gewarren** [comment]
@LJ9999 Did you see this paragraph in the article you referenced? It seems to answer your questions.

The XML editor is invoked for well-known file extensions, such as .xml, .xsd, .xsl, and .config. It is also invoked on any unknown file extension if the file appears to contain XML. You can also open any file with the XML editor by using the Open With option and selecting the XML editor from the list.

**Comment by cbmgit** [comment]
I use this one. https://jsonformatter.org/xml-editor for XML Editing.
