### ISSUE TITLE
Visual studio for mac

### ISSUE THREAD

**Issue by Lakachew91** [MicrosoftDocs/visualstudio-docs#2238]
thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08320b48-33b6-b3e5-3be1-72202019e3dd
* Version Independent ID: 3a66757e-649d-6415-ff5e-00d628eb17f6
* Content: [Install Visual Studio 2019 for Mac Preview - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/installation?view=vsmac-2019)
* Content Source: [mac/2019/installation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/2019/installation.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by asb3993** [comment]
Thanks for your response @Lakachew91 !
