### ISSUE TITLE
When is Attach called?

### ISSUE THREAD

**Issue by jordan83** [MicrosoftDocs/visualstudio-docs#2240]
Playing around with the MIEngine implementation has given some insight. It looks like when the SDM calls IDebugEngineLaunch2::ResumeProcess, the code natvigates to a IDebugPortNotify2 instance and adds the program node. The implementation of IDebugPortNotify2::AddProgramNode calls Attach before it returns.

https://github.com/Microsoft/MIEngine/blob/master/src/MIDebugEngine/AD7.Impl/AD7Engine.cs#L677

This obviously depends heavily on who is implementing the debug process and the port. If the debug process is coming from a custom port implementation (i.e. a process running on a remote machine), does the implementer have to also implement the IDebugDefaultPort2 and IDebugPortNotify2 interfaces? If so, how do those implementations force the SDM to call Attach?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bec0601-d4d8-f75e-a52a-af41718a241e
* Version Independent ID: a341eb85-a6a1-7324-c0d2-ebf7e9e5e68b
* Content: [IDebugEngine2::Attach - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/reference/idebugengine2-attach?view=vs-2017)
* Content Source: [docs/extensibility/debugger/reference/idebugengine2-attach.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/debugger/reference/idebugengine2-attach.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by Mikejo5000** [comment]
@jordan83 Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
