### ISSUE TITLE
The link for annotation support is wrong

### ISSUE THREAD

**Issue by jb-wisemo** [MicrosoftDocs/visualstudio-docs#2243]
The link needs to go to https://docs.microsoft.com/en-us/visualstudio/code-quality/using-sal-annotations-to-reduce-c-cpp-code-defects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 392c386c-755c-3a5e-dab1-f157cac7f4f2
* Version Independent ID: 75a83eac-2475-4fd8-c9e3-2b2c9cea885e
* Content: [Code Analysis for C/C++ Overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-c-cpp-overview?view=vs-2017)
* Content Source: [docs/code-quality/code-analysis-for-c-cpp-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-for-c-cpp-overview.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gewarren** [comment]
Link is in this section - https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-c-cpp-overview?view=vs-2017#annotation-support
