### ISSUE TITLE
The lock kinds and kind specific annotations needs clarification

### ISSUE THREAD

**Issue by jb-wisemo** [MicrosoftDocs/visualstudio-docs#2244]
As written the documentation for _xxx_exclusive_lock_, _xxx_nonreentrant_lock_ and _xxx_shared_lock_ need to be clarified as to what those words are intended to mean in this feature.  Throughout locking literature, different and contradictory use of such words can be found, so it is necessary to be specific as to what is meant in this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3befc1e4-e459-fb78-f12e-db45a16e9f98
* Version Independent ID: 32f54ed6-6189-4d05-66aa-b0e7dc66680d
* Content: [Annotating Locking Behavior - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-locking-behavior?view=vs-2017)
* Content Source: [docs/code-quality/annotating-locking-behavior.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/annotating-locking-behavior.md)
* Product: **visual-studio-dev15**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@jb-wisemo sorry for the very delayed response on this one. The terms reentrant and shared here are used in the accepted sense as you will find in any good textbook. It's beyond the scope of the article to explain those concepts in depth. Is there a particular question that you had about their behavior?

**Comment by jb-wisemo** [comment]
Clarification of what was already in my initial report:

Over the past 50 years, the textbooks and academic literature about synchronization primitives have refined and sometimes redefined terms such as an "exclusive lock".  If you only ever read textbooks from one school of thought, you might not notice.  But once you branch out to reading more than that, you will run into authors who use terms quite differently.

The problem here is that mapping actual synchronization primitives with known behavior to the limited set of 3 categories in the annotation language (without knowing the internal thinking in the MS Research team that originally created PREfast) will result in doubts, not only as to which one to choose, but also which incorrect information one might inadvertently be passing to the Analysis engine.

A starting point for improving the documentation would be to list how each of the Win32 (SDK) and NT kernel mode (WDK) lock APIs map to these annotations.

- Is a Win32 Mutex/NT MUTANT used by multiple processes a "shared" or "reentrant" lock?
- Is a Win32/NT auto-reset Event an "exclusive" lock?
- What is the appropriate annotation for a Win32 CRITICAL_SECTION?
- What about an NT kernel/WDK ERESOURCE Lite (which has more features than a CRITICAL_SECTION)?
- What about a Win32 counted Semaphore?
- What about advanced mechanisms pulled from the academic literature and implemented in a private software component with an annotated header?

The other part is what behavioral properties are expressed in these annotations:

- Does Code analysis assume, require or check that a "shared" lock is not held upon entry to a function that is labeled as acquiring that lock?
- Does Code analysis assume, require or check that a function not mentioning a lock will not net acquire or net release a counted lock?
- Does Code analysis assume, require or prohibit that an "exclusive" lock can be used for interthread signaling (like a Win32 Event or Win32 Semaphore)?

And of cause:
- How does all this differ between different versions of the MS compiler family, as a DOCFIX made for VS2019 doesn't always state if it reflects a code change in VS2019 or is a DOCFIX applicable to the same feature in VS2017 (still within its 10 year life cycle).
