### ISSUE TITLE
How do I set the verbosity switch

### ISSUE THREAD

**Issue by schemburkar** [MicrosoftDocs/visualstudio-docs#2247]
I'm trying to set the  /verbosity:quiet in msbuild.exe, but there is no way to provide this in the MSBuild task. Any way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ae888a-0777-7e09-cd0c-c864df8376db
* Version Independent ID: 29dd0025-ff74-ec07-ad71-4a75a276d8d8
* Content: [MSBuild Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-task?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@schemburkar I believe you would normally do this from the command line, or in a custom logger. Sounds like you want to limit logging to a specific Task? @rainersigwald for comment

**Comment by schemburkar** [comment]
I'm doing something like 
MyLib.csproj

```xml
<Project>
<!-- Regular csproj stuff-->
...
<Target Name="Example">
  <MSBuild Projects="FooDependency.csproj" Targets="Restore" />
</Target>
...
</Project>
```

I need to set the Verbosity on the MSBuild task element.
Setting `Properties="Verbosity=Quiet"` does not work, so something like should be possible:
```xml
<MSBuild Projects="FooDependency.csproj" Targets="Restore" Verbosity="Quiet" />
```

The equivalent cmd syntax is 
```
msbuild /t:restore /v:quiet FooDependency.csproj
```

**Comment by rainersigwald** [comment]
There's no way to control verbosity from within an MSBuild execution; it's a property only of the loggers attached to the whole build, either through the API or from the command line.

**Comment by Mikejo5000** [comment]
No doc issue here that I can see. Closing this.
