### ISSUE TITLE
When available for .NET Core?

### ISSUE THREAD

**Issue by LockTar** [MicrosoftDocs/visualstudio-docs#2252]
I see the note: ![NOTE] This refactoring is not yet available for .NET Standard and .NET Core projects.

When will it be available? I have the situation a lot that I want to rename the file to match the type. Now only the other way around is possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1290998c-f264-73c8-1e42-ace297da8cd1
* Version Independent ID: 129df6c6-6098-bd70-e57e-27ed3df1b7ed
* Content: [Rename a filename to match a type - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/sync-type-and-file?view=vs-2017)
* Content Source: [docs/ide/reference/sync-type-and-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/sync-type-and-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by drmcclelland** [comment]
I have the same question - when will this be available in Visual Studio for .NET Core projects?  It was frustrating that this wasn't working after following the steps in the article all the way down...  then I read the last sentence of the article:

> ![NOTE] This refactoring is not yet available for .NET Standard and .NET Core projects.

**Comment by gewarren** [comment]
@kendrahavens Can you find out if/when this refactoring will be available for .NET Core projects?

Meanwhile I have a [PR ](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/3815)in our private repo to move the NOTE up to the first section of the article.

**Comment by kendrahavens** [comment]
It's not currently available for .NET Core projects. 

@LockTar This request is being tracked [in this issue](https://github.com/dotnet/roslyn/issues/5378), but we don't have it tied to a release yet. I suggest upvoting and following that issue to help us prioritize. Thank you for your feedback!

**Comment by LockTar** [comment]
Thanks, following the issue right now and have upvoted it. The issue is already open for 3 years...
