### ISSUE TITLE
Document intellisense accessibility modifiers

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/visualstudio-docs#2254]
In the #examples-of-intellisense-icons section we should add that each icon has a modifier indicating accessibility. A "lock" appears on the icon if the method is private, a star if it is protected, etc.

Screenshots of the different modifiers: https://imgur.com/a/rJuu12u
Related customer feedback on unclear documentation: https://developercommunity.visualstudio.com/idea/426045/intellisense-may-show-also-the-accessibility-level.html?childToView=431481#comment-431481

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2fab7f9-2e3a-a463-047c-d1f4a2d5a3ed
* Version Independent ID: 24b51017-45a1-164b-7aec-2974277dcd3d
* Content: [Images and Icons for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2017#examples-of-intellisense-icons)
* Content Source: [docs/extensibility/ux-guidelines/images-and-icons-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/images-and-icons-for-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
This is the section: https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2017#icon-types

@kendrahavens, do you want this new documentation to be for extension writers, or for end users? If the latter, then the information probably belongs in a different article.

**Comment by kendrahavens** [comment]
A question from an end user is what prompted me to ask for the doc. Do you have a suggestion for where this should go for the end user?

**Comment by gewarren** [comment]
@kendrahavens I'd suggest it goes into a new section in [this article](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2017), or a new reference article that's a child of that one in the TOC.
