### ISSUE TITLE
Control ID / Office Id

### ISSUE THREAD

**Issue by yyou** [MicrosoftDocs/visualstudio-docs#2255]
"Set the OfficeId property to the control ID of the built-in tab that you want to customize."

I downloaded the "Office 2010 help files: Office fluent user interface control identifiers" from the link in this document. But which column in those spreadsheets will be the column to setup the Control ID here?  the column "Control Name"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a0b25-416d-8a39-c054-32d4520cb887
* Version Independent ID: 5842f7a6-11f8-86cb-01b2-d739c7dcf12d
* Content: [How to: Customize a built-in tab - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-customize-a-built-in-tab?view=vs-2017)
* Content Source: [docs/vsto/how-to-customize-a-built-in-tab.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-customize-a-built-in-tab.md)
* Product: **visual-studio-dev15**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@yyou, you've probably already figured this out but yes, the column in the spreadsheet that you should get the "Control ID" from is the Control Name

**Comment by John-Hart** [comment]
#please-close
