### ISSUE TITLE
EnableDefaultContentItems 

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/visualstudio-docs#2257]
`EnableDefaultContentItems` is not documented. See [this thread on SO](https://stackoverflow.com/questions/46983930) and https://github.com/aspnet/Docs/issues/7951

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a5a0e-ae03-1237-6ebe-743066f27fa9
* Version Independent ID: a342bfa4-4b0c-0a47-3695-858044f5aa5f
* Content: [MSBuild Reserved and Well-known Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-reserved-and-well-known-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-reserved-and-well-known-properties.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Closing this one in favor of #2016
