### ISSUE TITLE
This refactoring does always work as expected

### ISSUE THREAD

**Issue by yairush88** [MicrosoftDocs/visualstudio-docs#2261]
For example, in the following code snippet:
            var index = 1;
            for (int i = 0; i &lt; 10; ++i)
            {
                index++;
                // Some more work...
            }

After trying to apply the "Move declaration near reference" refactoing, I get the following:
            for (int i = 0; i &lt; 10; ++i)
            {
                var index = 1;
                index++;
            }

And this of course creates a bug! Because expected value of index after loop iteration should be 10, whereas after refactoring it would be 2. This is a SERIOUS bug of this refactoring! Please fix it ASAP.

Thanks
Yair

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34be1855-140a-0545-6a25-eff5c0a9f8d3
* Version Independent ID: c98bcf79-1b6c-76e3-efe8-7ec66db05fd1
* Content: [Move variable declaration near reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/move-declaration-near-reference?view=vs-2017)
* Content Source: [docs/ide/reference/move-declaration-near-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/move-declaration-near-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yairush88 Thanks for reporting this. Since this is a product issue, please report it at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which the product team actively monitors (these issues here are for docs). Initiate your report by choosing Help > Send Feedback > Report a Problem from Visual Studio.
