### ISSUE TITLE
"This project does not reference any Dependency Validation diagrams or..."

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#2262]
"referenced diagrams are not valid. Dependency validation will not be performed."

I didn't ask for any dep val, yet this message is showing up in my Error List as warnings.
![image](https://user-images.githubusercontent.com/15381181/51683845-c620e980-1fb8-11e9-9091-a9b3cbe32a8c.png)

How does this "feature" get turned off?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a25a17b-a48c-f9f1-f61e-6b3e1479a199
* Version Independent ID: 3ccc0a49-c4d3-8c92-1b11-81a4198441d3
* Content: [Validate code with dependency diagrams - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/validate-code-with-layer-diagrams?view=vs-2017)
* Content Source: [docs/modeling/validate-code-with-layer-diagrams.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/validate-code-with-layer-diagrams.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mgoertz-msft Can you help answer how to get rid of these warnings?

**Comment by Marraz** [comment]
If you are not using the analyzers, removing them would be enough but if this is not possible due to dependency, you can suppress the warning (in this case DV2001) 

How to suppress warnings:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings

**Comment by StingyJack** [comment]
@Marraz I've historically had very little success with making the DV messages go away (2-3 issues on devcomm still unresolved after a few years). In this case the problem was caused due to the DV package not declaring itself as a development dependency, so when we run nuget pack on one of our projects that uses the DV analyzer, nuget forces consumers of our package to take the DV package too.

**Comment by StingyJack** [comment]
@Marraz - I did finally remove that DV package from all the projects in the solution, yet VS is still telling me that
![image](https://user-images.githubusercontent.com/15381181/75287089-c1e08480-57e7-11ea-9def-2a9adae4cefb.png)
 when I open the solution.  

Can you point me to the GH page or place where I can report this?  Ive tried using the developer community for dependency validation issues but things I report never seem to leave triage before getting auto-closed for inactivity.

**Comment by Marraz** [comment]
@StingyJack Well, developer community is where it should be reported (https://developercommunity.visualstudio.com/spaces/8/index.html). Open the report there and send me the url, I'll help out with the triage

**Comment by StingyJack** [comment]
@Marraz - 

https://developercommunity.visualstudio.com/content/problem/36322/dependency-validation-messages-wont-stop-bothering.html  

https://developercommunity.visualstudio.com/content/problem/102206/one-or-more-projects-needs-to-be-updated-to-perfor.html

https://developercommunity.visualstudio.com/content/problem/24318/dependency-validation-dead-end.html  (this may look familiar to you)

There are bunch of other complaints about DV that have been collecting and getting ignore-closed for a few years now.  These things are closed, so they cant accrue any votes if you were expecting to use that as a metric for feedback.  
https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+idea&type=question+OR+problem+OR+idea&c=&redirect=search%2Fsearch&sort=relevance&q=dependency+validation

**Comment by StingyJack** [comment]
@Marraz  - not sure if you got tagged on this correctly as I used the docs page and not GH

**Comment by StingyJack** [comment]
@github-actions bot you are a cancer on the community

**Comment by StingyJack** [comment]
@github-actions bot you are a cancer on the community

**Comment by j-martens** [comment]
👋  @StingyJack

Since this is a documentation 📝 issue repo, and your feedback is for the product, there isn't anything for us to take action here. 

The best place to suggest a feature, track product issues, and find answers is in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).  I highly recommend you add yours there so it gets surfaced properly. If you've done so already, please follow up on that thread. 

Best regards,
j-martens
