### ISSUE TITLE
Linkedin learning benefit not activating from dev essentials page. Link looks broken.

### ISSUE THREAD

**Issue by mrincmr** [MicrosoftDocs/visualstudio-docs#2272]
Linkedin learning benefit not activating from dev essentials page. Link looks broken.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4948f37c-a328-34ea-5980-5ac3115e2f8e
* Version Independent ID: f8c0f599-0711-a98e-b254-04407ba864de
* Content: [LinkedIn Learning Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-linkedin-learning)
* Content Source: [subscriptions/vs-linkedin-learning.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-linkedin-learning.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@mrincmr - Thanks for reaching out.  We're working to resolve a technical issue that is resulting in codes not being available to activate the LinkedIn Learning benefits in some subscriptions.  I apologize for the inconvenience, and appreciate your patience.

**Comment by imakshaybora** [comment]
By when this issue can be fixed? I meed to start learning through LinkedIn Learning. Your help and support will be highly appreciated.

**Comment by evanwindom** [comment]
@imakshaybora - We appreciate your patience.  We anticipate having this issue resolved sometime this week.

**Comment by evanwindom** [comment]
@mrincmr @imakshaybora - The issue has been resolved, and you should be able to activate your LinkedIn Learning benefits now.  Thank you for your patience! @TerryGLee - FYI.

**Comment by uzairsaiyed** [comment]
Hi, 
My Linkedin Learning premium is having problem in activation. When I click on activation code the page link keeps on continues loading forever and something it shows error with following message.

"We are sorry, but our system has detected a problem with your account. 
If you are still getting this error message after 24 hours, please contact support with the date and time you started having this problem and with your subscription information. Message code: 715-123150."

Please help me resolve this issue asap as I need to start learning on Linkedin. Your response is highly appreciated.

**Comment by evanwindom** [comment]
@uzairsaiyed  - Thanks for reaching out.  If you're seeing an error code like 715-123150, it's likely that the portal has detected multiple failed attempts to download the code and is interpreting those as a potential threat. That's something our technical support folks can address for you. Please visit https://visualstudio.microsoft.com/subscriptions/support/#talktous and click the "Account, Subscription and Billing Support" button at the bottom of the page. Be sure to mention the 715 error. They will be able to set up a case with the appropriate escalation team to resolve this for you.

What type of subscription are you using?  (Visual Studio Dev Essentials, for example?)

**Comment by uzairsaiyed** [comment]
Thanks @evanwindom  for your reply. I contacted the support/help team at Microsoft visual studio. They checked my visual studio ID and verified my email address and told me they have forwarded my case and it will take 3 business days to resolve and they will notify me by email. Yes my subscription is Visual Studio Dev Essentials. I will wait for them to respond and hopefully it gets resolved and I can get access to LinkedIn Learning. Thanks again.

**Comment by evanwindom** [comment]
Thank you for letting me know.  We’re currently experiencing an issue with the Dev Essentials portal running out of those codes and are working to correct the problem.

**Comment by Momilijaz96** [comment]
Same here!!! My 1 month premium of Linked in expired and now I want to use my MV Dev benefit of linked in learning but it keeps redirecting me to reactivation or buying page

**Comment by evanwindom** [comment]
@Momilijaz96 - What do you mean when you say MV Dev benefit?

**Comment by Momilijaz96** [comment]
Pardon ! I meant visual studio dev essentials

**Comment by Momilijaz96** [comment]
@evanwindom I meant visual studio dev essentials, when I click on benefit of linked din learning I am redirected to linked in reactivation/buying page.

**Comment by Momilijaz96** [comment]
As seen here....
![Screen Shot 2019-08-09 at 11 29 57 PM](https://user-images.githubusercontent.com/53872365/62800984-2a8f3a80-bafe-11e9-9a21-10a015d7c042.png)
![Screen Shot 2019-08-09 at 11 30 45 PM](https://user-images.githubusercontent.com/53872365/62800986-2b27d100-bafe-11e9-96f7-e40a2625d69f.png)

**Comment by evanwindom** [comment]
@Momilijaz96  - The LinkedIn Learning is a component of the LinkedIn Premium membership.  So, when the premium subscription expires, the learning benefit is no longer available.

**Comment by Momilijaz96** [comment]
@evanwindom but can't I access more free subscription from my visual studio dev essentials benefits? even after expiring of my premium trial

**Comment by evanwindom** [comment]
@Momilijaz96 - No, because the LinkedIn Learning is part of the LinkedIn Premium membership.  You get access to the learning plus other benefits of the Premium membership, but once that expires, access to the learning benefit also expires.

**Comment by Momilijaz96** [comment]
oh!is there any other way to get courses for free, i was almost down with a course, and my subscription expired,

**Comment by evanwindom** [comment]
@Momilijaz96 - Not through the Visual Studio Dev Essentials program.  You may want to contact LinkedIn directly to see if they have any other trial offers.

**Comment by Momilijaz96** [comment]
@evanwindom thanks dude!
