### ISSUE TITLE
Document if it is possible to use VS Code and how

### ISSUE THREAD

**Issue by TomasHubelbauer** [MicrosoftDocs/visualstudio-docs#2273]
Hey, thanks for this documentation page. I'd be interested in learning how to build and develop UWP apps using VS Code as opposed to full Visual Studio. I am not clear on whether this is possible or not, I can imagine there being prerequisites and dependencies that prevent this from working, but if it is possible, I'd like to learn how to do it and whether it is a supported scenario by Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1daec8-269e-40fd-0cc3-6c38f9074399
* Version Independent ID: e9b4d9e3-8692-339b-e1f3-ff417d1a09cd
* Content: [Develop apps for the Universal Windows Platform (UWP) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/develop-apps-for-the-universal-windows-platform-uwp?view=vs-2017)
* Content Source: [docs/cross-platform/develop-apps-for-the-universal-windows-platform-uwp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/develop-apps-for-the-universal-windows-platform-uwp.md)
* Product: **visual-studio-dev15**
* GitHub Login: @stevehoag
* Microsoft Alias: **shoag**

**Comment by gewarren** [comment]
@gregvanl Can you comment on this?

**Comment by TomasHubelbauer** [comment]
Understood. Is it possible to build an existing UWP app without Visual Studio? I found a thread which seems to indicate that MSBuild and the .NET SDK is not enough, that VS installs the UWP targets. Is that still the case? Is building UWP apps without VS something you would consider supporting?

**Comment by gewarren** [comment]
@diverdan92 might be able to offer additional insight on whether UWP apps can be developed outside of VS.

**Comment by diverdan92** [comment]
@TomasHubelbauer - you could build UWP applications with the Visual Studio Build edition. Some more information is available in this [post](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/introducing-the-visual-studio-build-tools/).

Just curious - is there a reason you would want to build and develop apps without Visual Studio?

**Comment by TomasHubelbauer** [comment]
Thanks!

I am usually doing .NET webdev + other tech and for that I've migrated to VS Code as I like it better for JS and other non-MS stacks and can have all under one roof that way.

I still have VS on other machines, but do not want to install it on my main laptop due to its size and decreased utility / fragmentation of IDEs now that I use VS Code for a majority of my coding.

In this particular case I need to build someone else's UWP app, with some slight tweaks, and can do so just find on the other machines, but sending the binary to my laptop without VS with each tweak is a pain. So I'd like to build through command line installing just the most essential dependencies and invoking the build script from VS Code integrated terminal while I make changes in VS Code.
