### ISSUE TITLE
Linkedin learning benefits are not activating from my.visualstudio.com . Please help 

### ISSUE THREAD

**Issue by msaleem3k** [MicrosoftDocs/visualstudio-docs#2274]
Linkedin learning benefits are not activating from my.visualstudio.com . Please help 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4948f37c-a328-34ea-5980-5ac3115e2f8e
* Version Independent ID: f8c0f599-0711-a98e-b254-04407ba864de
* Content: [LinkedIn Learning Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-linkedin-learning)
* Content Source: [subscriptions/vs-linkedin-learning.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-linkedin-learning.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@msaleem3k - Thanks for reaching out.  We're working to resolve a technical issue that is resulting in codes not being available to activate the LinkedIn Learning benefits in some subscriptions.  I apologize for the inconvenience, and appreciate your patience.

**Comment by evanwindom** [comment]
@NexusComputerCentre - Thanks for reaching out.  When you say the code doesn't work, are you receiving a message that we're temporarily out of codes, or is something else happening?  We're currently working to resolve a technical issue that is resulting in no codes being available for LinkedIn Learning in some subscriptions.

**Comment by opiumfever** [comment]
I am getting following error while requesting get code for linkedin in - "Oops! We've temporarily run out.
Please try again later."

**Comment by evanwindom** [comment]
@opiumfever - Thanks for reaching out.  We're aware of the issue and working to resolve it.  We anticipate having a solution in place this week.

**Comment by evanwindom** [comment]
@msaleem3k @NexusComputerCentre @opiumfever - The issue has been resolved, and you should be able to activate your LinkedIn Learning benefits now.  Thank you for your patience! @TerryGLee - FYI.

**Comment by omarDG** [comment]
@evanwindom,

I'm not getting the error message but i'm not able to get the code. It gives me a loading process and after that nothing happens. When I reload the page I get  "Something went wrong!" I can retest after few minutes but same result.

**Comment by evanwindom** [comment]
@omarDG Are you seeing that behavior and message on the http://my.visualstudio.com portal, or on the LinkedIn Learning page?  When you see the tile for LinkedIn Learning on the http://my.visualstudio.com portal, does the link in the lower right say "Get code" or "Activate"?

**Comment by omarDG** [comment]
I'm seeing it on the [http://my.visualstudio.com](http://my.visualstudio.com) portal,  and i have "Get code" in the lower right say. 
NB: My colleague  has successfully got code and activated is Linkedin benefits and just to precise we have both Visual Studio Dev Essentials

**Comment by ShubhG** [comment]
I am unable to get the LinkedIn subscription code. I have tried many times but it is not working.

**Comment by zoohair** [comment]
Have the same problem as @omarDG : I click the link, and there is a "loading state" in the card, but nothing opens/happens. Eventually if I reload the page I get a "Something went wrong!" error.

I tried on Safari and Chrome with the same problem.

**Comment by evanwindom** [comment]
@zoohair, @ShubhG, @omarDG  - Thanks for reaching out.  I apologize for the inconvenience.  

If you're seeing an error code like 715-123150, it's likely that the portal has detected multiple failed attempts to download the code and is interpreting those as a potential threat.  That's something our technical support folks can address for you.  Please visit https://visualstudio.microsoft.com/subscriptions/support/#talktous and click the "Account, Subscription and Billing Support" button at the bottom of the page.  Be sure to mention the 715 error.  They will be able to set up a case with the appropriate escalation team to resolve this for you.

**Comment by inam12341** [comment]
I'm seeing it on the http://my.visualstudio.com portal, and i have "Get code" in the lower right say. when i click it is loading  and loading and not going any where, and then it finished by itself, i cannot activate my linkedin subscription.

**Comment by brendaferreirap** [comment]
I'm seeing it on the http://my.visualstudio.com portal, and i have "Get code" in the lower right say. when i click it is loading and loading and not going any where, and then it finished by itself, i cannot activate my linkedin subscription.

**Comment by AbhijithSpericorn** [comment]
unable to activate linked learning subscription for 3 months with visual studio code. 
Oops! We've temporarily run out.

Please try again later.

**Comment by AungMy0** [comment]
Oops! We've temporarily run out. issue happening "my.visualstudio.com/Benefits"

**Comment by jessecha** [comment]
I am also seeing this issue: Oops! We've temporarily run out.

**Comment by AhmedElKordey** [comment]
> I am also seeing this issue: Oops! We've temporarily run out.

same issue with me

**Comment by TerryGLee** [comment]
@evanwindom FYI

**Comment by concita** [comment]
same issue with me...Oops! We've temporarily run out. Please try again later.
Why?

**Comment by tolek102** [comment]
> unable to activate linked learning subscription for 3 months with visual studio code.
> Oops! We've temporarily run out.
> 
> Please try again later.

same issue... ;/

**Comment by jeremqui** [comment]
Hi, I am facing same issue. Getting "Oops! We've temporarily run out. Please try again later" error. Please help.

**Comment by premnathdeveloper** [comment]
I am too having the same issue (oops we've temporarily run out)

**Comment by evanwindom** [comment]
Hi, and thanks for reaching out. The Dev Essentials program works with a variety of partners to bring exclusive benefits to our members. These exclusive benefits are offered with a limited quantity and some benefits run out quicker than others. The goal is to ensure there's enough to meet the demand, but we often don't have a say in the quantity available.
We've reach out to LinkedIn to discuss expanding this offer to more members and doing everything we can to make this benefit available again soon.

**Comment by zeeshoo** [comment]
Hi there! Is this offer removed? or temporarily down?

**Comment by evanwindom** [comment]
When the supply runs out, the benefit tile is removed from the portal to ensure members don’t encounter errors.

We've reach out to LinkedIn In to discuss expanding this offer to more members and doing everything we can to make this benefit available again soon.

**Comment by zeeshoo** [comment]
Thanks for information

**Comment by sdsouza33** [comment]
The linkedin benefits is not even visible now on visiualstudio/benefits . Please resolve this asap

**Comment by evanwindom** [comment]
LinkedIn is no longer offering the 3-month Premium benefit through Visual Studio Dev Essentials.  A one-month free trial is available at https://www.linkedin.com/learning/me.

**Comment by abdennour** [comment]
@evanwindom  what's a bad news!

**Comment by TerryGLee** [comment]
@evanwindom Thanks for providing us with the status of the LinkedIn Learning benefit. We are closing this issue now.

**Comment by ambikaarora2304** [comment]
Hi team, I'm not able to activate linkedin from Visual studio, when I'm clicking on it and adding credentials for lInkedin it's showing me the amount which I have to put. instead of 0 for 1 month. Could you please help here.

**Comment by evanwindom** [comment]
@ambikaarora2304 - Thank you for reaching out.  The trial offer includes 30 days of free use, and then converts to a paid offering after the 30 days.  The offer is provided and managed by LinkedIn, so problems with activation of the trial should be referred to LinkedIn's support team.  https://www.linkedin.com/help/learning

**Comment by evanwindom** [comment]
@ambikaarora2304 - I should have mentioned that my previous response is based on the assumption that you are using a Visual Studio Dev Essentials membership to access the LinkedIn offer.  If that's not the case, please let me know.

**Comment by ambikaarora2304** [comment]
Hi,

Thanks it's working now !!

Regards,
Ambika

**Comment by shiraze** [comment]
> Hi, I am facing same issue. Getting "Oops! We've temporarily run out. Please try again later" error. Please help.

I'm also seeing this issue, with a Visual Studio Professional sub trying to get 3 month code

**Comment by evanwindom** [comment]
@shiraze Thanks for reaching out.  The LinkedIn Learning benefit uses a promo code that is supplied by LinkedIn.  We have reached out to them and they are working on the problem.  Once the issue is resolved, you'll be able to claim a code and activate the benefit.  We apologize for the inconvenience.

**Comment by sengel24** [comment]
> @shiraze Thanks for reaching out. The LinkedIn Learning benefit uses a promo code that is supplied by LinkedIn. We have reached out to them and they are working on the problem. Once the issue is resolved, you'll be able to claim a code and activate the benefit. We apologize for the inconvenience.

Hello, my colleagues with Visual Studio Professional with Github Enterprise are unable to see the LinkedIn Learning 3 month premium benefit anymore. It was working fine last month (colleagues were able to get the code and activate it). However now the entire box with "Get Code" is missing. I'm hoping this a temporary technical issue? Do you have any insight into this? For reference, these colleagues have never activated the benefit before.

**Comment by evanwindom** [comment]
@shiraze -- Hi.  Thanks for reaching out.  The November issue was caused by running out of codes.  We got new codes, but then learned that there were some problems on our side with how the codes were uploaded.  That resulted in customers claiming codes only to find out they were invalid.  We've been working on correcting that issue with the codes.  We made the decision to remove the offers from the portal until the issue was resolved so that customers weren't being issued codes that didn't work.  We have resolved the issue, and are in the process of uploading codes.  We hope to have that completed in the next 24 hours and will turn the tiles back on in the portal as soon as possible.  Thanks for your patience!

**Comment by sengel24** [comment]
> @shiraze -- Hi. Thanks for reaching out. The November issue was caused by running out of codes. We got new codes, but then learned that there were some problems on our side with how the codes were uploaded. That resulted in customers claiming codes only to find out they were invalid. We've been working on correcting that issue with the codes. We made the decision to remove the offers from the portal until the issue was resolved so that customers weren't being issued codes that didn't work. We have resolved the issue, and are in the process of uploading codes. We hope to have that completed in the next 24 hours and will turn the tiles back on in the portal as soon as possible. Thanks for your patience!

This is great, I'm happy to hear that the tiles will be back in the next 24 hours - I'll communicate this to those encountering the issue. Also I can't express how much I appreciate the extremely fast response on this.

**Comment by sengel24** [comment]
> @shiraze -- Hi. Thanks for reaching out. The November issue was caused by running out of codes. We got new codes, but then learned that there were some problems on our side with how the codes were uploaded. That resulted in customers claiming codes only to find out they were invalid. We've been working on correcting that issue with the codes. We made the decision to remove the offers from the portal until the issue was resolved so that customers weren't being issued codes that didn't work. We have resolved the issue, and are in the process of uploading codes. We hope to have that completed in the next 24 hours and will turn the tiles back on in the portal as soon as possible. Thanks for your patience!

Hello, the tiles appear to be back but users are reporting that they receive the error message from LinkedIn when activating: "Something went wrong. This coupon has expired. Please contact customer support for additional assistance." Do you have any suggestions/ideas on how to address this?

**Comment by evanwindom** [comment]
@shiraze -  Thanks for the report. We haven't heard of the issue from any other users, but that doesn't mean there's not a problem.  Can you provide the any of the codes that are being returned as expired?  The way to do that is to hover over the "Activate" button on the tile, right-click, and copy the link.

**Comment by evanwindom** [comment]
@shiraze I just tried activating the benefit with a test subscription, and it worked.  I suspect you might be dealing with situations where people claimed codes back when we had the problem with the expiration, and that code is still assigned to them, so they're not able to claim and use a new code.  If that's the case, they can contact our support team, who can reset that benefit so that they can claim a fresh code.  

https://visualstudio.microsoft.com/subscriptions/support/#talktous
Scroll to the bottom of the page.
Choose "Account, Subscription and Billing Support". 
Select the appropriate region to find the contact phone number.  

Please let me know if this helps.  
Thanks, 
Evan

**Comment by shiraze** [comment]
Thanks @evanwindom - this is working for me now

**Comment by sengel24** [comment]
Hi @evanwindom - is there something specific that we should be mentioning to Visual Studio support to reset the benefit so they can claim a fresh code? 4 developers (that has not previously use the benefit) on our end are receiving the same error (this coupon has expired) in LinkedIn when trying to activate and although I appreciate that the support team is trying to address the problem, they are requesting that each person with the problem use PSR to record the steps, which poses a security risk in our environment. I imagine there must be a simpler way to reset the benefit? Any insight would be greatly appreciated!

**Comment by evanwindom** [comment]
Hi @sengel24 - I'm not aware of an alternative method, unfortunately.  The process they have in place is designed to prevent people from randomly calling and asking for resets to high value benefits.  I'll drop a note to a support contact and see if there is a way to streamline things for the short term.  The problem would be gating anything like that, though, to prevent abuse.

**Comment by evanwindom** [comment]
@sengel24 - Can you tell me what messages the users are getting?

**Comment by sengel24** [comment]
> @sengel24 - Can you tell me what messages the users are getting?

The error the users are getting are largely identical as far as I can tell. When they go to activate the benefit, it opens LinkedIn in a new window/tab and says:
"Something Went Wrong
This coupon has expired. Please contact customer support for additional assistance." I've also included a screenshot below:

![320539742-435ada31-52f8-48f1-b378-9ab1b42bef72](https://github.com/MicrosoftDocs/visualstudio-docs/assets/165961581/59235695-f7b4-4907-b784-f76c68e5a5f4)
