### ISSUE TITLE
Referencing newer assemblies

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/visualstudio-docs#2276]
I created a Dependency Validation project, named ArchitectureModel, that references various local projects using various .NET versions (.NET Standard 2.0, .NET Framework 4.7.2 and .NET Core 2.1). Before adding the DV project, I didn't have any framework reference issues, but with the DV project, I'm getting errors like this:

![image](https://user-images.githubusercontent.com/1784452/51814912-4b3f2380-2283-11e9-86ba-1fd678b5515c.png)

The most interesting thing part is: `It cannot be referenced by a project that targets '.NETFramework,Version=v4.5'.` because none of my projects target .NET 4.5.

After searching the web, I added `<ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch>true</ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch>`, but to no avail.

The only other thing I could think of is that the DV project itself needs a .NET version and simply defaults to 4.5. So I then added `<TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion>` and most of the errors went away! All except the one Azure Functions project that targets .NET Core 2.1. So that's an incomplete solution...

Why am I getting these errors and what's the best way to suppress them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a25a17b-a48c-f9f1-f61e-6b3e1479a199
* Version Independent ID: 3ccc0a49-c4d3-8c92-1b11-81a4198441d3
* Content: [Validate code with dependency diagrams - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/validate-code-with-layer-diagrams?view=vs-2017)
* Content Source: [docs/modeling/validate-code-with-layer-diagrams.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/validate-code-with-layer-diagrams.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mgoertz-msft** [comment]
Targeting 4.7.2 sounds like the right thing to do. However, I'm afraid .NET Core is not supported by the Dependency Validation (or any of the other Architecture Tools).

**Comment by MisinformedDNA** [comment]
Well that's a surprising and a, quite frankly, alarming statement. Why aren't they supported? Will they be supported?

**Comment by mgoertz-msft** [comment]
I could be wrong but AFAIK these tools have never really worked with .NET Core.

**Comment by msebolt** [comment]
You could try using `<TargetFrameworks>` and specifying both versions using the [framework versions monikers](https://docs.microsoft.com/en-us/dotnet/standard/frameworks).

**Comment by WilliamAntonRohm** [comment]
@MisinformedDNA -- Dan, here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
