### ISSUE TITLE
Visual Studio 2017 15.9 Installer not working

### ISSUE THREAD

**Issue by Mikolaj98p** [MicrosoftDocs/visualstudio-docs#2277]
I cannot install visual studio because offline installer after initial progress done is closing without any affect in files.

**Comment by tydunkel** [comment]
@Mikolaj98p Thank you for reporting this! Are you seeing this screen at all after being prompted to elevate?
![image](https://user-images.githubusercontent.com/40210514/51861834-11f1cc80-22f2-11e9-9af8-747bf419064e.png)
If not, you may have a corrupted .NET framework installation. If so, could you check if this feedback item applies to you? [Installer won't open with NODE_OPTIONS environment variable set](https://developercommunity.visualstudio.com/content/problem/224084/installer-wont-show-up-when-i-have-node-options-va.html)

**Comment by TerryGLee** [comment]
@Mikolaj98p We haven't heard back, and so we're closing this GitHub Issue for now. If you require further assistance or have further information, feel free to respond again to this issue, and we'll reopen it if necessary.
