### ISSUE TITLE
Error in sample code

### ISSUE THREAD

**Issue by pressacco** [MicrosoftDocs/visualstudio-docs#2278]
Sample code references a class that has not yet been defined: `ClassC`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c3d4e72-7dfd-9fc6-631e-298d47156220
* Version Independent ID: e05bb3f5-1133-a57f-298e-d50c10b0a9e7
* Content: [Debug a C++ access violation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-can-i-debug-an-access-violation-q?view=vs-2017)
* Content Source: [docs/debugger/how-can-i-debug-an-access-violation-q.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-can-i-debug-an-access-violation-q.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@pressacco Thanks! I'll take a look at that.
