### ISSUE TITLE
System requires a key press after layout finished, makes it hard to automate a layout + subsequent install, like in a script

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/visualstudio-docs#2281]
Hi all,

I just did ```vs_<sku>.exe --layout --lang en-US`` and I put this in a batch file script that had the installer set to be kicked off right after the layout was completed.  I thought it would be a good idea, since I could set this all up after I got home from work and then I could go out, work out in the gym, and grab dinner all while the layout process was taking the several hours that it usually takes to complete.  Therefore, I thought "gee, this is great, I can just script this all up in a batch file."

Little did I realize, after I got done from working out and grabbing some Pei Wei (yum), it had sat there for approx 1-2 hours, with that precious time having been wasted, since there was a prompt, "the layout is finished, press a key to continue."  It seems that the there should be a command-line option for the layout to make it non-user-interactive, so that the 'press a key to continue' prompt does not show up when the layout is completed; rather, the installer just quits, and it will let my batch script go on to the next step.

You Microsoft people are probably asking me now, "gee Brian, that is all a swell suggestion but why post it as an issue in the docs GitHub?  Doesn't it belong on the feature suggestion or UserVoice boards we have set up?"  Well, yes, but if you'll let me finish, I think this is a docs issue, since all the layout examples I've seen in the docs just put --layout and --lang on the command line (maybe some others) but the docs do not go into any sort of exposition as to whether, when I am doing a layout, whether it's allowed to combine the --layout and --passive or --layout and --quiet flags.  Given that the download of the layout takes an extremely long amount of time, I was hoping the docs could go into more detail, so I can look up the docs and then I can save myself hours and hours.  Thanks!

**Comment by TerryGLee** [comment]
@astrohart Thanks for your feedback, and your detailed suggestion as to how we can improve our docs. Am I correct in assuming that you are referring to our [Command-line parameter examples for Visual Studio 2017 installation](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017) page? Or the [Create an offline installation of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017) page? (Or both?)

**Comment by astrohart** [comment]
Both

Regards,
 
Brian C. Hart, Ph.D.
CEO, xyLOGIX, LLC

San Diego:
5663 Balboa Avenue Suite 412
San Diego, California 92111

Washington, DC:
1845 Cain Drive Suite 1
Fort George G. Meade, Maryland 20755

‭(443) 679-8247‬ mobile
www.xylogix.net

**Comment by TerryGLee** [comment]
@tydunkel FYI

**Comment by TerryGLee** [comment]
@astrohart Apologies that this issue you filed has lain fallow for some time now. But taking a look at it now, I'd like to respond by saying that you can find the information you might need to create a batch file to do that which you want it to do in our [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/visualstudio/install/use-command-line-parameters-to-install-visual-studio) page. 

For example, in the [Install options](https://docs.microsoft.com/visualstudio/install/use-command-line-parameters-to-install-visual-studio?#install-options) section of this page, there are explanations that describe the difference between the `--quiet` flag and the `--passive` flag, as follows:

| `--quiet, -q` | **Optional**: Don't display any user interface while performing the installation. |
| `--passive, -p` | **Optional**: Display the user interface, but don't request any interaction from the user. |

From this, the idea is you'd use one or the other, but not both. 

You might have noticed that the [Command-line parameter examples for Visual Studio installation](https://docs.microsoft.com/visualstudio/install/command-line-parameter-examples) page includes a lot of examples that you can use to pattern your own installation scripts. In fact, the [Using --installPath](https://docs.microsoft.com/visualstudio/install/command-line-parameter-examples#using---installpath) section includes examples of both the `--passive` flag and `--quiet` flag, along with use cases to support them. 

That being said, I hear what you are saying about having more information available about how to use command-line parameters, along with examples there-of. We do have content for both, but it might not have been linked to optimally. I've reviewed all our documentation for offline installations and have made sure that references to both the [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/visualstudio/install/use-command-line-parameters-to-install-visual-studio) page and the [Command-line parameter examples for Visual Studio installation](https://docs.microsoft.com/visualstudio/install/command-line-parameter-examples) are placed where they should be.

I'm going to close this issue now, but I'd like to thank you once again for your feedback, and for helping to improve the documentation. We appreciate it!

Cheers,
~ Terry

p.s. I hope the updates we've made to the documentation are helpful, but if you find that there is product functionality that's missing or could be improved, please consider using our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​

**Comment by astrohart** [comment]
Yes, I know about the procedures you outlined; however, even doing the steps you tell me, the installer forces user interaction.   It requires an interactive user to press a key to continue.

This negates the purposes of unattended install command line switches, and makes them completely ineffective. 

There is not an issue with the documentation; I understand the documentation.  The software has a bug.

Brian Hart

**Comment by astrohart** [comment]
I dispute the need to close this issue as the fundamental bug in the software itself remains unaddressed.

**Comment by TerryGLee** [comment]
@astrohart I'm sorry to hear this. Unfortunately, this forum is for documentation issues only. To make sure that this issue is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report it. After you do so, the report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
