### ISSUE TITLE
Identify which ASP.NET Core version accompanies VS?

### ISSUE THREAD

**Issue by malachib** [MicrosoftDocs/visualstudio-docs#2282]
I recently needed to verify whether ASP.NET Core 2.2 was or was not a part of VS 2017 15.9.6

After a lot of looking around, I could not get a canonical answer.  I inferred that it isn't, so my initial question was answered, but the new question arises - where should I look for a proper answer to this question?  The best candidate seems to be:
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes

but as you can see it's not in there

please advise.  I've filled out a "report a problem" as well indicating this issue

**Comment by TerryGLee** [comment]
@malachib Thanks for your feedback; @Paul-Chapman FYI.

**Comment by PoulChapman** [comment]
Hi! Thank you for asking. We provide compat/supported version information for .NET Core here: https://dotnet.microsoft.com/download/dotnet-core

For your specific questions: ASP.NET Core 2.2 was included with Visual Studio 2019. It can be used by -- but is not shipped with -- Visual Studio 2017.

-Paul

**Comment by TerryGLee** [comment]
@PoulChapman Thanks for answering this; I'll close the issue now.
