### ISSUE TITLE
Schema XSD

### ISSUE THREAD

**Issue by patware** [MicrosoftDocs/visualstudio-docs#2284]
The creation of a .runSettings file from an empty XML without schema is not a good experience.  There has to be a better way to guide us in creating/edition this file: An XML Schema (XSD), a Visual Studio or add-on Dialog/Editor, even a Web page that outputs the xml.  

.RunSettings feels like an afterthought or something deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2017)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The best place to make feature suggestions or provide feedback is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Look for the "Suggest a Feature" button:

![image](https://user-images.githubusercontent.com/24882762/50102736-a7218180-01da-11e9-9aaf-ea3a99ccd030.png)

When you create a feature suggestion on Developer Community, you can engage directly with the engineering team as they consider the suggestion. It also provides a way for other customers to upvote your suggestion.
