### ISSUE TITLE
CA2213 - Gives warning on null propagation

### ISSUE THREAD

**Issue by trivli** [MicrosoftDocs/visualstudio-docs#2285]
Even if DisposableMember in this case is disposed (if it is created), the CA2213 kicks in:

        public void Dispose()
        {
            DisposableMember?.Dispose();
        }

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7193fffc-ff49-d551-417e-6f004dd1e216
* Version Independent ID: 8370a61d-8d8a-bec4-b49d-e5cae67a0d86
* Content: [CA2213: Disposable fields should be disposed - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed?view=vs-2017)
* Content Source: [docs/code-quality/ca2213-disposable-fields-should-be-disposed.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2213-disposable-fields-should-be-disposed.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Can you comment on this?

**Comment by mavasani** [comment]
I think this is a known bug in legacy FxCop. @trivli can you try with FxCop analyzers following the steps here: https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers

**Comment by gewarren** [comment]
@trivli If this still reproes with the FxCop analyzer implementation of CA2213, please file an issue at [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/issues).
