### ISSUE TITLE
Publishing "New Project" to new GitHub repo

### ISSUE THREAD

**Issue by mjarosch** [MicrosoftDocs/visualstudio-docs#2288]
None of this documentation covers when you checked "Use git for version control" made a local commit and now want to push those changes to a newly created GitHub repo. 

I can add the repository as a remote (origin), but because it is a new GitHub repo and it doesn't yet have a master branch, there isn't a way to push the branch or tell it to track the remote master branch. The equivalent of "git push -u origin master".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606d4c70-3daf-8b03-9c31-b690927a7136
* Version Independent ID: 24a13aaf-3d14-c810-182c-2c2d93fc299b
* Content: [Setting up a Git Repository - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository)
* Content Source: [mac/set-up-git-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/set-up-git-repository.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
@mjarosch the page has been updated with a section on [publishing a new project](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository#publishing-a-new-project) - hope that helps!
