### ISSUE TITLE
Section PDF download

### ISSUE THREAD

**Issue by AnneCHPostma** [MicrosoftDocs/visualstudio-docs#2289]
While I like the option that you can download a PDF for the total Visual Studio Mac documentation, I'd love an option to just download a pdf of the section that I am reading (so for example this section about keyboard shortcuts). That will save me a lot of browsing through the full PDF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a1d38f-f2fc-3fe6-bfb4-b73b7f4a56bc
* Version Independent ID: 90b1f5ca-71dd-2c14-8023-c3f238fc2686
* Content: [Source Editor Common Keyboard Shortcuts - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/keyboard-shortcuts)
* Content Source: [mac/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/keyboard-shortcuts.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @AnneCHPostma - the PDF generation is a feature of docs.microsoft.com, designed to download a set of pages for easy reference.

For a single page, if you choose to print-to-PDF, our print stylesheet should result in a readable PDF file.

Specifically for the keyboard shortcuts, I think a PDF download of those is a great idea, which I'll pass on to our team.
