### ISSUE TITLE
CA1822 example is misleading

### ISSUE THREAD

**Issue by pieriv** [MicrosoftDocs/visualstudio-docs#2293]
The example about the CA1822 in the [Configure and use Roslyn analyzer rules](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2017) page cannot be reproduced, because it only fires when the member is visible outside of the assembly ([see the documentation](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822-mark-members-as-static?view=vs-2017)).

The given example should be replaced by:
```
namespace A1
{
    internal class A2 { }

    public class Program
    {
        static void Main(string[] args)
        {
        }

        public int Add(int i1, int i2)
        {
            return i1 + i2;
        }
    }
}
```

**Comment by gewarren** [comment]
@pieriv Thanks for letting us know.

The code screenshot in [this section](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2017#rule-severity) needs to be replaced.
