### ISSUE TITLE
Load Testing Alternatives after Visual Studio 2019

### ISSUE THREAD

**Issue by rolfik** [MicrosoftDocs/visualstudio-docs#2294]
Because you are making Load testing in Visual Studio deprecated, it would be nice to give some guidance to other alternatives for doing performance or load testing.

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0780169-4b7b-97ce-5ccd-9f962472a2c8
* Version Independent ID: f0c68169-baeb-cba0-ccf0-a149fa96bb67
* Content: [Create a web performance and load test project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2017)
* Content Source: [docs/test/quickstart-create-a-load-test-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/quickstart-create-a-load-test-project.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by tom-miseur** [comment]
Check out Eggplant Performance (disclaimer: I work for Eggplant):
https://eggplant.io/products/performance-and-load-testing/eggplant-performance

You can get a 50 VU license for free here:
https://eggplant.io/free-trial-eggplant-performance

Scripting can be done in C# and is therefore quite similar to VS Load Test. It also isn't limited to existing within the Visual Studio IDE; this is a tool made from the ground up to be a performance and load testing tool.

**Comment by gewarren** [comment]
Please see [this comment](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2032#issuecomment-465317158). Closing this issue in favor of #2032.

**Comment by rolfik** [comment]
Thank You @gewarren I will follow the issue.

**Comment by FF2bricker** [comment]
funny how microsoft doesn't respond with an answer.

**Comment by MsbYuva** [comment]
https://stackoverflow.com/questions/61804272/system-marshalbyrefobject-visual-studio-2019-load-test

 am using VS 2019, I did setup for a load test. I am trying to run web performance test under remote server (controller/agents). I am seeing an error "The Augument type 'System.MarshalbyRefObject' cannot be converted into parameter type 'Microsoft.vISUALStudio.TestTools.Common.FileCopyService.'

**Comment by MsbYuva** [comment]
https://i.stack.imgur.com/PYect.png

**Comment by MsbYuva** [comment]
![image](https://user-images.githubusercontent.com/18167011/82127998-840b5080-9785-11ea-8d1e-429738b74011.png)

**Comment by djpirra** [comment]
This was closed under what conclusion? I am also trying to migrate a project that was using the LoadTestFramework to VS2019 but the library been deprecated.

Regards
