### ISSUE TITLE
error when created a new solution configuration with empty of "Copy settings from"

### ISSUE THREAD

**Issue by StevenFlyover** [MicrosoftDocs/visualstudio-docs#2297]
if i created a new solution configuration with empty of "Copy settings from", then publish the project, an error "Target ValidateMSBuildTollsVersion skipped. Previously built unsuccessfully.". Publish failed.
but success when i choose Debug or Release of "Copy settings from". so, why an option "Empty" existed if must to choose one of Debug and Release? if can choose the option item "Empty", where to complete this new configuration for success publish?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd27543-2a22-9a63-eefd-4cf5f786191c
* Version Independent ID: b7aa9bfd-4e9a-42bf-9e20-44caf2141cd8
* Content: [How to: Create and edit configurations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-and-edit-configurations?view=vs-2017)
* Content Source: [docs/ide/how-to-create-and-edit-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-and-edit-configurations.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@StevenFlyover The product team isn't completely sure of your repro steps and has requested that you please report this issue using Report a Problem in Visual Studio. Initiate your report by choosing Help > Send Feedback > Report a Problem from Visual Studio.
