### ISSUE TITLE
Vbc task LangVersion param claims it must be 9 or 10, but the newest is 15.5

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#2299]
The documentation of the `LangVersion` parameter of the `Vbc` task says:

&gt; Specifies the language version, either "9" or "10".

However, &lt;https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/configure-language-version#edit-the-vbproj-file&gt; lists many other language versions, including "15.5" and "latest". It might be best to remove the list of Visual Basic language versions from MSBuild documentation and instead link to that page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 74881bfb-5d3d-cbe8-cd52-f4b3ef048b1d
* Version Independent ID: 467bc35b-0f6a-05ca-f1d9-6fd2167eadc5
* Content: [Vbc Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/vbc-task?view=vs-2017)
* Content Source: [docs/msbuild/vbc-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/vbc-task.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@KalleOlaviNiemitalo Good idea, thanks! I'll update it.
