### ISSUE TITLE
provide an example for unattended installation from the command line

### ISSUE THREAD

**Issue by rgl** [MicrosoftDocs/visualstudio-docs#23]
can you please provide an example on using `vs_Community.exe` to [install from the command line](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)? For example, there is no explanation on what should we use in the `--catalog` parameter value.

also, `vs_Community.exe --help` (or `-h`, `/?`) do not seem to work, it just opens the normal installation window as if `--help` was not specified at all.

**Comment by TerryGLee** [comment]
RGL, we'll check in to this and report back.

**Comment by timsneath** [comment]
Hi, @rgl - please see #65 and let us know if that helps?

**Comment by TerryGLee** [comment]
This was addressed in https://github.com/MicrosoftDocs/visualstudio-docs/pull/65. Closing...

**Comment by rgl** [comment]
Thanks guys, its working nicely at https://github.com/rgl/visual-studio-community-vagrant/blob/master/provision-vs.ps1 :-)
