### ISSUE TITLE
Display static code metrics in Html Format

### ISSUE THREAD

**Issue by eraj2587** [MicrosoftDocs/visualstudio-docs#2304]
Can we export static code metrics results in html format. Or do we have plan to upgrade metrics.exe version to create html report along with xml file. Secondly do we have plan for keeping history of results with subsequent changes in the codebase.

**Comment by mavasani** [comment]
@eraj2587 There are no planned work items for this. Feel to create an issue here: https://github.com/dotnet/roslyn-analyzers/issues/new.
