### ISSUE TITLE
The TestVariableContosoPrice is not correct

### ISSUE THREAD

**Issue by pappasa** [MicrosoftDocs/visualstudio-docs#2305]
The correct one is: 

```
   [TestMethod]
    public void TestVariableContosoPrice()
    {
        // Arrange:
        int priceToReturn = 345;
        string companyCodeUsed = "";
        var componentUnderTest = new StockAnalysis.StockAnalyzer(new StockAnalysis.Fakes.StubIStockFeed()
        {
            GetSharePriceString = (company) =>
            {
                    // Store the parameter value:
                    companyCodeUsed = company;
                    // Return the value prescribed by this test:
                    return priceToReturn;
            }
        });

        // Act:
        int actualResult = componentUnderTest.GetContosoPrice();

        // Assert:
        // Verify the correct result in the usual way:
        Assert.AreEqual(priceToReturn, actualResult);

        // Verify that the component made the correct call:
        Assert.AreEqual("COOO", companyCodeUsed);
    }

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1834a8fa-cc25-bacf-1379-b6691051cf39
* Version Independent ID: 56f3b218-56c5-6135-0593-41e83370a813
* Content: [Using stubs to isolate parts of your application for unit testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-stubs-to-isolate-parts-of-your-application-from-each-other-for-unit-testing?view=vs-2017)
* Content Source: [docs/test/using-stubs-to-isolate-parts-of-your-application-from-each-other-for-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-stubs-to-isolate-parts-of-your-application-from-each-other-for-unit-testing.md)
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@pappasa Thanks, I'm updating this now.
