### ISSUE TITLE
Update SKUs throughout documentation

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/visualstudio-docs#231]
Sprinkled throughout the documentation are several references to previous Visual Studio SKUs such as:
- Visual Studio Premium
- Visual Studio Ultimate

The current SKUs for Visual Studio 2017 are:
- Visual Studio Community
- Visual Studio Professional
- Visual Studio Enterprise

Example of a page with referencing previous SKUs:
https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-collect-performance-data-for-a-web-site

**Comment by kraigb** [comment]
Once the final set is published to live, the old SKUs should be out of the docs.

@alfredmyers Thanks for bringing this to our attention, an apologies for having taken so long to address it. We very much appreciate your input. :)

**Comment by kraigb** [comment]
PS, https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1475 was the second set of changes, in which I neglected to mention this issue so it's not in the log above.
