### ISSUE TITLE
Testen von Django Datenbank-Zugrifffen

### ISSUE THREAD

**Issue by LisandroSu** [MicrosoftDocs/visualstudio-docs#2312]
@sprevrha commented on [Sat Feb 02 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/37)

Über den Test-Explorer gestartete Tests rufen nicht zuerst Django setup auf, und die Apps und Objekte werden vor der Ausführung des Tests nicht geladen. Man kann Extra-Code schreiben, aber dieser sollte dem CLI-Aufruf "python manage.py test" nicht in den Weg kommen. Dies könnte besser gelöst sein.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
* Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
* Content: [Komponententest für Python-Code - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/unit-testing-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/python/unit-testing-python-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by LisandroSu** [comment]
Hi team,
Please check this issue. Rough translation:

> Tests launched through the Test Explorer do not first invoke Django setup, and the apps and objects are not loaded before running the test. You can write extra code, but it should not get in the way of the CLI call "python manage.py test". This could be better solved.

Thanks!

**Comment by kraigb** [comment]
@sprevrha Vielen Dank für den Bericht. (And that's as far as I'll allow my Deutsche to go! :) ) Because the behavior you're seeing is related to the product itself, rather than the documentation, please follow up on https://github.com/Microsoft/ptvs/issues where the engineering team can discuss the matter with you.
