### ISSUE TITLE
"Download all, then install" will not work if Visual Studio is already installed

### ISSUE THREAD

**Issue by duckfist** [MicrosoftDocs/visualstudio-docs#2315]
"Download all, then install" doesn't work if Visual Studio is already installed, since the installer simply detects a completed installation and immediately finishes. Do I need to completely uninstall Visual Studio from my primary machine, just to turn around and reinstall it, JUST to prepare a standalone install package? There's no reasonable way to prepare an install for a separate offline system. What a huge mess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@duckfist Thanks for your feedback. @tydunkel FYI.

**Comment by TerryGLee** [comment]
@tydunkel Thanks; I've submitted a PR that will make this clear; the updated page will be published tomorrow by noon. @duckfist Thanks again for bringing this to our attention.
