### ISSUE TITLE
Keep getting email on renewal

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/visualstudio-docs#2319]
My O365 is associated with MSDN and I have enabled Auto Renewal as well. Still getting an email every month with subject "Your Office 365 subscription expires in &lt;n&gt; days/months"

Based on the date in the email, it will expire in next 7 days and not sure what is going to happen. I also contacted support team earlier on the same and they confirmed that I am all set but still getting the same email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22a69a8-de38-2929-144a-0bd738f40a25
* Version Independent ID: a1d94b1f-c61e-df28-d412-1195aa9ace6d
* Content: [The Office 365 Developer Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office-dev)
* Content Source: [subscriptions/vs-office-dev.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-office-dev.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@ravick4u - Thanks for reaching out.  Are you having an issue with the Office 365 Developer benefit, or with Office 365?  The Visual Studio subscriptions portal provides access to the benefits, but doesn't manage the registration or billing processes, so unfortunately we are unable to provide technical support for Office 365 accounts/billing issues.  I recommend contacting https://support.microsoft.com/contactus/ for assistance.

**Comment by ravick4u** [comment]
As per this post O365 Subscription created with MSDN is renewable every year which has been confirmed by you in my previous comment. So I was wondering why I am getting that email. Will get in touch with Support team. Thanks @evanwindom.
