### ISSUE TITLE
unable to finish this tutorial, where is the "Manifest node"

### ISSUE THREAD

**Issue by peterremote1980** [MicrosoftDocs/visualstudio-docs#2356]
really can't find the "Manifest node"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3edfcdaa-2fac-15dd-003f-c2133daa368d
* Version Independent ID: 85d95dfa-14d0-30f7-593c-0bc0e098320b
* Content: [Custom actions in Outlook form regions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/custom-actions-in-outlook-form-regions?view=vs-2017)
* Content Source: [docs/vsto/custom-actions-in-outlook-form-regions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/custom-actions-in-outlook-form-regions.md)
* Product: **visual-studio-dev15**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by TerryGLee** [comment]
@peterremote1980 Thanks for letting us know; this content set is in our backlog to update. @John-Hart, FYI.

**Comment by peterremote1980** [comment]
thanks Terry G Lee

**Comment by John-Hart** [comment]
this is fixed with PR #4107

#please-close
