### ISSUE TITLE
dotnet_style_require_accessibility_modifiers missing omit_if_default

### ISSUE THREAD

**Issue by onovotny** [MicrosoftDocs/visualstudio-docs#2357]
The accessibility modifier docs are missing the `omit_if_default` value, which removes modifiers that are the language default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#normalize_modifiers)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kuhlenh
* Microsoft Alias: **gewarren**

**Comment by tonyhallett** [comment]
Please add https://github.com/dotnet/roslyn/commit/896e3f360d948184282f0bc7d27d09de91530d0f
