### ISSUE TITLE
Charge/Fee

### ISSUE THREAD

**Issue by himensuthar** [MicrosoftDocs/visualstudio-docs#2375]
I got subscription from my company. Is there any fees/charge applicable to claim any keys ? Do they will get notification if I claim any key ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5819c75-be9a-4545-2cce-300c84b7e2aa
* Version Independent ID: 61ab6656-53e4-7de8-cb53-22d60bc7ed20
* Content: [Using Product Keys](https://docs.microsoft.com/en-us/visualstudio/subscriptions/product-keys)
* Content Source: [subscriptions/product-keys.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/product-keys.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@himensuthar - Thanks for reaching out.  There are limits on the number of keys you can use, but there are no fees or charges associated with claiming any keys.  No notifications of your use of product keys are provided to the administrators.
