### ISSUE TITLE
Lambdas in breakpoint conditional expression support

### ISSUE THREAD

**Issue by JiriCepelkaFirstLineSoftware** [MicrosoftDocs/visualstudio-docs#2376]
Are lambdas supposed to work in breakpoint conditional expression?

I searched for info on this but with very [little success](https://stackoverflow.com/questions/25629584/why-cant-you-have-a-lambda-in-a-conditional-breakpoint-in-visual-studio-2013#answer-25629727). In official documentation there is no info on this.

I find it working in some (possibly simple) cases but for (complex one) other situations there is often failure at debugger site to evaluate the expression.

**Example of failure:**

    namespace ConsoleApp1
    {
        using System.Collections.Generic;
        using System.Linq;
    
        class Program
        {
            static void Main(string[] args)
            {
                //IEnumerable<string> enumerArgs = args.AsEnumerable();
                var t = "t";
            }
        }
    } 
 
 

If you put breakpoint with conditional expression _!args.Any( a => a.EndsWith("a"))_ on line with var declaration you’ll got error on [picture](http://software919.sweb.cz/Args[].png). If you uncomment the line you’ll get expression evaluated.

Another [example](http://software919.sweb.cz/Entries.png) relates to really simple lambda.

I find this somewhat buggy with no official doc on this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use breakpoints in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2017)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-breakpoints.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@andysterland @leslierichardson95 Do we have any more info on lambda support? I see this blog post that says they are supported in most scenarios:
https://blogs.msdn.microsoft.com/devops/2014/11/12/support-for-debugging-lambda-expressions-with-visual-studio-2015/

**Comment by JiriCepelkaFirstLineSoftware** [comment]
> @andysterland @leslierichardson95 Do we have any more info on…

I found also this article but it does not explicitly states breakpoint conditional expression.

**Comment by Mikejo5000** [comment]
@JiriCepelkaFirstLineSoftware  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
