### ISSUE TITLE
R tool for VS 2019 not available

### ISSUE THREAD

**Issue by isaac34mi** [MicrosoftDocs/visualstudio-docs#2379]
R is not an option in the Data science and analytical applications workload for 2019 version. Is it not yet available or will be discontinued ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11431a6-8401-2c63-b53c-e7f489b08ba7
* Version Independent ID: 1f8a17a4-122f-b2ef-f866-87dfdeaf3332
* Content: [R Tools for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/?view=vs-2019)
* Content Source: [docs/rtvs/index.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/index.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@isaac34mi Yes, R Tools for Visual Studio (RTVS) isn't being carried forward to VS 2019 (and won't appear in the documentation when we put out VS 2019 updates). Microsoft's R efforts are being focused on Azure Notebooks instead (https://notebooks.azure.com). 

If you have additional feedback on the availability of RTVS, follow up on https://github.com/microsoft/rtvs/issues, which is monitored by the engineering team.

**Comment by zekeargus** [comment]
Is this because R is a terrible language?

**Comment by kraigb** [comment]
Not necessarily. :) It's primarily that usage of R is much more prominent in the context of Jupyter Notebooks than in an IDE like Visual Studio, hence the people who were working on RTVS are working on Azure Notebooks now.

**Comment by zekeargus** [comment]
:) 
Would you know whether debugging is possible in the manner of VS in azure?

**Comment by kraigb** [comment]
In Azure Notebooks, no; but they're reworking all that anyway. For now, we encourage people to download the notebook and load into VS Code where you have all the debugging facilities.

**Comment by zekeargus** [comment]
Hello. I am going to ask another question please.
So far I have been using VS 2017 for this purpose. Alternatively, via Anaconda I use the R-environment and use Jupyter.
What you are suggesting is load Azure (or Jupyter) notebook in VS code and load R-environment and work/debug/run from there?
If this is the case would you have a suggested guide to follow?
Thanks.

**Comment by craigbrett17** [comment]
Is Azure now required to use R with Visual Studio then? Might be a deal breaker for those who aren't using Azure as their cloud.

**Comment by BenWiseman** [comment]
But why? Notebooks are horrible for larger workloads? I mean, I get it, Rstudio is hard to compete with, but really, rtvs was so useful to have everything all setup in one place. 

That really sucks to hear, man.
