### ISSUE TITLE
I get this warning when using smart pointers but the documentation doesn't mention them

### ISSUE THREAD

**Issue by jscarrott** [MicrosoftDocs/visualstudio-docs#2393]
I have a weakPtr bar, and a function foo that takes bar and locks it returning a sharedPtr or throws an exception if the weakPtr is expired. I then call a function baz on that sharedPtr all in one line. 
A bit like this foo(bar)-&gt;baz()
This gives a C26486 warning.
I solved it by returning a const r-value reference from foo, which makes sense as foo is checked to return a valid pointer and it is qualified that it never changes. Still, it would have been nice for the documentation to point me in the right direction with the new lifetime checker warnings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2b55e4b-0473-1a82-2fce-6a099cb7e3e2
* Version Independent ID: 18a66256-6dfc-bc14-7d04-022487a596be
* Content: [C26486 - Visual Studio](https://docs.microsoft.com/en-us/cpp/code-quality/C26486)
* Content Source: [docs/code-quality/C26486.md](https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/code-quality/c26486.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kylereedmsft
* Microsoft Alias: **kylereed**

**Comment by Mikejo5000** [comment]
Updated content links (C++ rule)

**Comment by Mikejo5000** [comment]
Moved issue to C++
Closing this in favor of [https://github.com/MicrosoftDocs/cpp-docs/issues/2662](https://github.com/MicrosoftDocs/cpp-docs/issues/2662)
