### ISSUE TITLE
Inheritance and DebuggerDisplay

### ISSUE THREAD

**Issue by drewnoakes** [MicrosoftDocs/visualstudio-docs#2394]
The documentation doesn't specify whether applying `DebuggerDisplayAttribute` on a base class causes it to be used on subclasses.

It should also make clear what happens when a base class has the attribute and a subclass overrides `ToString`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653452d1-1586-e971-1f6c-370a91be613f
* Version Independent ID: 348f41ea-994c-7ed2-7af5-77077f2b5696
* Content: [Using the DebuggerDisplay Attribute - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2017#feedback)
* Content Source: [docs/debugger/using-the-debuggerdisplay-attribute.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-the-debuggerdisplay-attribute.md)
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@drewnoakes Asking about this.

**Comment by Mikejo5000** [comment]
It is supported on an inherited class. Updating the doc.

**Comment by drewnoakes** [comment]
The other half of this was not addressed:

> It should also make clear what happens when a base class has the attribute and a subclass overrides ToString.

If a type overrides `ToString` and has a `DebuggerDisplay` attribute, which is used in the debugger?

In my experience there's inconsistency on when the attribute is used vs when `ToString` is used. This has led me to replacing `DebuggerDisplay` with `ToString` on types I control.

A specific example of inconsistency is seen when expanding a dictionary debugger tool tip, the keys and values use the `ToString` output rather than the `DebuggerDisplay`. This is probably a product bug, rather than a documentation bug. I'm not sure there's anything we can document here, but it is currently misleading to think that using `DebuggerDisplay` will work reliably everywhere in the debugger.

**Comment by Mikejo5000** [comment]
I'm told the attribute should win over an override of ToString on a subclass. So, this appears to be a product bug if that is not happening. I will plan to update the doc. @andysterland @leslierichardson95 

Would you mind using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue? That way, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem. Thx!
