### ISSUE TITLE
Can't suppress individual warnings in the IDE

### ISSUE THREAD

**Issue by InteXX** [MicrosoftDocs/visualstudio-docs#2398]
This documentation doesn't indicate how to use the IDE to suppress specific warnings (e.g. `/nowarn:1603`). The instructions provided apply to a command-line compile only. Of course, the IDE does run `vbc` on the command line, but there's no (obvious) place in the IDE to enter these switches—nor does the documentation provide such guidance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3def1356-54a4-486f-8a50-a52501cbe90e
* Version Independent ID: c6ae86dc-6b3a-75f8-b9c2-390f6a521df3
* Content: [Configuring Warnings in Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/configuring-warnings-in-visual-basic?view=vs-2017)
* Content Source: [docs/ide/configuring-warnings-in-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/configuring-warnings-in-visual-basic.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@rpetrusha Do you know if it's possible to suppress specific VB compiler warnings from the IDE?

**Comment by rpetrusha** [comment]
No, it's not, @gewarren. There are some limited options (disable all compiler warnings, treat all warnings as errors). There's also an option to suppress individual kinds of warnings (like unused local variable), but they're not explicitly mapped to individual compiler warnings.   

![image](https://user-images.githubusercontent.com/10886961/52680991-369f9400-2eef-11e9-9159-db4acd24b6a9.png)

**Comment by InteXX** [comment]
I've raised a problem report [here](https://developercommunity.visualstudio.com/content/problem/448916/persistent-nu1603-warning-cant-suppress.html).

**Comment by gewarren** [comment]
Thank you @rpetrusha and @InteXX. I'm closing this since it's not a docs issue and it's being tracked on Developer Community now.
