### ISSUE TITLE
Doesn't say how to create a new theme

### ISSUE THREAD

**Issue by Stokestack** [MicrosoftDocs/visualstudio-docs#2431]
It's a glaring omission. The article says, "Once you have found or created a new theme..." but conspicuously fails to state how you create one.  It's a reasonable expectation that any modern editor is going to have a UI for setting up colors, but this is nowhere to be found.

Compounding this problem is the perplexing selection of TextMate themes as the standard, when even TextMate lacks any way to edit its own themes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 584ac5ab-9547-f2d8-6186-783520b9e1ef
* Version Independent ID: 1f76cf76-b4b8-4cbb-c4ed-1c6a6f2130bd
* Content: [Editor Themes - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/editor-themes)
* Content Source: [mac/editor-themes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/editor-themes.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Visual Studio for Mac does not have a built-in theme editor, however this online tool https://tmtheme-editor.herokuapp.com/ has a wide variety available and the ability to edit and save.

Visual Studio on Windows requires an extension to edit themes - https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2017ColorThemeEditor - so if have you have a Windows computer handy you could also use that, and transfer the theme to your Mac.

I hope this helps liven up your IDE experience.

**Comment by Stokestack** [comment]
Thank you for the information, but the document still hasn't been fixed. This is a bug report on the documentation, not the product. Why isn't the information you just provided **in the document**?
