### ISSUE TITLE
The steps for vs 2019 to specify a custom ruleset aren't valid

### ISSUE THREAD

**Issue by fiksen99** [MicrosoftDocs/visualstudio-docs#2434]
The steps for vs2019 indicate:
"To make a rule set the active rule set for analysis, right-click on the project in Solution Explorer and choose Properties. In the project property pages, select the Code Analysis tab. Under Run this rule set, select Browse, and then select the desired rule set that you copied to the project directory. Now you only see rule violations for those rules that are enabled in the selected rule set."

In vs2019, the Code Analysis tab indicates this tab is deprecated, how can we set custom rules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1d7a06-e1b8-e57f-0511-3b0c0cfad150
* Version Independent ID: b0be1eb1-f908-f0fc-c553-5bea971805bb
* Content: [Analyzer rule sets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/analyzer-rule-sets?view=vs-2019)
* Content Source: [docs/code-quality/analyzer-rule-sets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/analyzer-rule-sets.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@fiksen99 This can get a bit confusing, and it seems the deprecation notice "Run Code Analysis has been deprecated in favor of FxCop analyzers, which run during build." might be a bit misleading, but the steps to set the active rule set are still accurate. If it's not working as expected, please let us know.

**Comment by fiksen99** [comment]
![image](https://user-images.githubusercontent.com/2607336/52612812-2d0b2300-2e40-11e9-84e1-a8685ac217a4.png)

See the above image, in Visual Studio 2019 Preview version 2.2, the entire tab is empty and marked for deprecation

**Comment by gewarren** [comment]
@fiksen99 I think you right-clicked on the *solution* instead of on the *project*. Can you try that?

**Comment by gewarren** [comment]
@fiksen99 Please comment if this is still an issue for you, but I believe if you right-click on the project node instead of the solution node, you should be good to go.

**Comment by stevenbrix** [comment]
@gewarren, should the message displayed to users indicate this? not sure how you'd figure out otherwise, except maybe by luck

**Comment by gewarren** [comment]
@stevenbrix Just to clarify - are you referring to the message on the Code Analysis Settings tab for the solution properties, and suggesting that it should point users to open the project properties instead?

**Comment by stevenbrix** [comment]
Yeah. I guess to be more nuanced, if someone's familiar workflow was to right-click Solution and then go to Properties->Code Analysis Settings, what are they supposed to do now? Your response implies that we've deprecated this for something else. If this is true, we should guide the user to where/what they are supposed to do. The current message is about as helpful as just removing the tab entirely (i.e. Code Analysis Settings not showing up under Common Properties). If this deprecation is documented somewhere on docs.microsoft.com, a link to it would be helpful.

**Comment by gewarren** [comment]
@mavasani Would it be reasonable to add a link to [this page](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2017) on the code analysis tab of a solution's properties?

**Comment by mavasani** [comment]
@stevenbrix @gewarren We are planning to deprecate this page soon. You can read the reasoning and suggested approach(es) at https://developercommunity.visualstudio.com/content/problem/317861/code-analysis-settings-doesnt-load.html

Tagging @jinujoseph - do we have an internal work item to track removal of solution level Code Analysis settings page?
