### ISSUE TITLE
LinkedIn Learning code not working

### ISSUE THREAD

**Issue by POG1991** [MicrosoftDocs/visualstudio-docs#2462]
Hello

I am having an issued with the Linkedin code which I cannot access. Last week I got a message saying the site was out of codes and today, I tried again and it justs shows a loading icon.
Moreover, when I want to try again, the site gives me the following error code : 715-123150 

Thank you very much in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4948f37c-a328-34ea-5980-5ac3115e2f8e
* Version Independent ID: f8c0f599-0711-a98e-b254-04407ba864de
* Content: [LinkedIn Learning Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-linkedin-learning#support-resources)
* Content Source: [subscriptions/vs-linkedin-learning.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-linkedin-learning.md)
* Product: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@POG1991 - Thanks for reaching out. I apologize for the inconvenience.
If you're seeing an error code like 715-123150, it's likely that the portal has detected multiple failed attempts to download the code and is interpreting those as a potential threat. That's something our technical support folks can address for you. Please visit https://visualstudio.microsoft.com/subscriptions/support/#talktous and click the "Account, Subscription and Billing Support" button at the bottom of the page. Be sure to mention the 715 error. They will be able to set up a case with the appropriate escalation team to resolve this for you.

**Comment by cesardba** [comment]
I have the same problem and support has not been able to solve it for more than 15 days, I'm already desperate without access and solution.
![image](https://user-images.githubusercontent.com/8593684/180327827-cb3aa77d-fc4e-4977-8b17-6ed12bb08059.png)

**Comment by evanwindom** [comment]
@cesardba Hi Cesar.  Did support provide you with a case number?
