### ISSUE TITLE
Download isn't available

### ISSUE THREAD

**Issue by EliFivelzon** [MicrosoftDocs/visualstudio-docs#2463]
The download is not available:
https://www.microsoft.com/download/confirmation.aspx?id=23734

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c5b210-2ecd-fc40-54c9-38a8ba9c7493
* Version Independent ID: a9236354-4965-a214-17f7-746c20de8ec4
* Content: [Connect to data in an Access database (Windows Forms) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms?view=vs-2017)
* Content Source: [docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks, I'll try to find a better target and/or determine if that step is still required.

**Comment by EliFivelzon** [comment]
Thanks, I got an error message "Unrecognized database format....".
I installed Microsoft Access Database Engine 2016 Redistributable from here:
https://www.microsoft.com/en-us/download/details.aspx?id=54920 .
When I tried to connect I got a different error message "microsoft ace oledb 12.0 provider is not registered on the local machine."
I uninstalled Office(64) and installed 32 bit version of Office and the Microsoft Access Database Engine, now it's working.
