### ISSUE TITLE
.fsi

### ISSUE THREAD

**Issue by jamessdixon** [MicrosoftDocs/visualstudio-docs#2471]
How do I reference a reference nuget package from the .fsi?  In Windows version, I can #r "/somelocation/file.dll"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e32dfe2-b389-c1ec-cd29-14c081d140a2
* Version Independent ID: 3d0606b2-e98a-819e-6090-1ca8b7d1ed51
* Content: [Including a NuGet package in your project - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/nuget-walkthrough)
* Content Source: [mac/nuget-walkthrough.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/nuget-walkthrough.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @jamessdixon, I'm going to have to check in with the F# team on this one! Will write you back when I have an answer.

**Comment by jamessdixon** [comment]
This may not be a F# only question?
When I look at the nuget references in the project, there are 4 (the original 2 and the 2 I added):
![screen shot 2019-02-13 at 7 22 07 am](https://user-images.githubusercontent.com/1394644/52711608-35f31600-2f60-11e9-9208-99002b0f7298.png)

However, in the packages folder, there are only the original 2
![screen shot 2019-02-13 at 7 22 32 am](https://user-images.githubusercontent.com/1394644/52711623-40151480-2f60-11e9-9b4e-a0d706cfddff.png)

So I assume that the ones I added are somewhere else on the Mac hard drive?
The only reference I could find is this:  https://lastexitcode.com/projects/NuGet/FileLocations/
and that points to the packages folder on the project root

**Comment by jamessdixon** [comment]
I think I see the problem
The files are here:
"/Users/jamesdixon/.nuget/packages/newtonsoft.json/12.0.1/lib/netstandard2.0/Newtonsoft.Json.dll"

However, the Mac Finder does not list any folder with a dot in front of it
<img width="219" alt="screen shot 2019-02-13 at 8 21 01 am" src="https://user-images.githubusercontent.com/1394644/52714632-5a52f080-2f68-11e9-8468-161a3b35a474.png">

I found the folder following the auto complete in the .fsi

<img width="1003" alt="screen shot 2019-02-13 at 8 21 36 am" src="https://user-images.githubusercontent.com/1394644/52714648-676fdf80-2f68-11e9-9fb2-936ea328d74f.png">

**Comment by jamessdixon** [comment]
and this is how to alter the Mac to find the files...

https://ianlunn.co.uk/articles/quickly-showhide-hidden-files-mac-os-x-mavericks/

**Comment by lobrien** [comment]
It sounds like you've solved this problem, but I thought you might like this small script that I use (I name it `mdfindx`) that I find helpful for chasing down files on the mac : 

    #!/bin/bash

    mdfind "kMDItemDisplayName == '$1'c"

And then use it like `mdfindx Newtonsoft*`

**Comment by conceptdev** [comment]
Closing this as it sounds like the issue's been resolved. Thanks for your feedback, and sharing your investigations.
