### ISSUE TITLE
Standardize the display of lists of articles

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/visualstudio-docs#253]
Lists of articles are displayed in different ways on diferent pages thoughout the documentation.

Let's take [Custom Native ETW Heap Events](https://docs.microsoft.com/en-us/visualstudio/profiling/custom-native-etw-heap-events) as our first example which end with a list of links under its **See Also** section:

> ## See Also
> * [Profiling Tools](https://docs.microsoft.com/en-us/visualstudio/profiling/profiling-tools)
> * [Memory Usage](https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage)

---
**[PerfTips](https://docs.microsoft.com/en-us/visualstudio/profiling/perftips)** shows each link on it's own link in source but renders all links on the same line (Markdown seems to work diferently here on Issues so I carved out markdown to emulate how it renders in docs.microsoft.com):

## See Also
 [Profiling in Visual Studio](../profiling/index.md) [Profiling Feature Tour](../profiling/profiling-feature-tour.md)

---
**[Analyze Memory Usage](https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage)** goes one way for **Blogs and videos** and another way for **See Also**:

## Blogs and videos  
 [Diagnostic Tools debugger window in Visual Studio 2015](http://blogs.msdn.com/b/visualstudioalm/archive/2015/01/16/diagnostic-tools-debugger-window-in-visual-studio-2015.aspx)  
  
 [Blog: Memory Usage Tool while debugging in Visual Studio 2015](http://blogs.msdn.com/b/visualstudioalm/archive/2014/11/13/memory-usage-tool-while-debugging-in-visual-studio-2015.aspx)  
  
 [Visual C++ Blog: Native Memory Diagnostics in VS2015 Preview](http://blogs.msdn.com/b/vcblog/archive/2014/11/21/native-memory-diagnostics-in-vs2015-preview.aspx)  
  
 [Visual C++ Blog: Native Memory Diagnostic Tools for Visual Studio 2015 CTP](http://blogs.msdn.com/b/vcblog/archive/2014/06/04/native-memory-diagnostic-tools-for-visual-studio-14-ctp1.aspx)

## See Also
 [Profiling in Visual Studio](../profiling/index.md)  [Profiling Feature Tour](../profiling/profiling-feature-tour.md)

---

If I were to pick one style, I'd pick the one used on  [Custom Native ETW Heap Events](https://docs.microsoft.com/en-us/visualstudio/profiling/custom-native-etw-heap-events).

**Comment by gewarren** [comment]
@alfredmyers thanks for pointing this out. Each See Also link is supposed to be on its own line, but as you pointed out, it sometimes looks different in source than in the rendered html. This usually happens if there are not two spaces at the end of each line. We will address the two topics you pointed out - PerfTips and Analyze Memory Usage.

**Comment by Mikejo5000** [comment]
Added fix to debugger and profiling topic set in this PR: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/923

**Comment by Mikejo5000** [comment]
One example of fix: https://review.docs.microsoft.com/en-us/visualstudio/profiling/memory-usage?branch=mikejo-br4
