### ISSUE TITLE
.editorconfig Naming Conventions: applicable_kinds

### ISSUE THREAD

**Issue by ashmind** [MicrosoftDocs/visualstudio-docs#254]
In [.editorconfig, Naming Conventions](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md#-naming-conventions-), `dotnet_naming_symbols.<symbolTitle>.applicable_kinds` lists:
```
class, struct, interface, enum, property, method, field, event, namespace, delegate, type_parameter
```

However [Symbol Specification](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md#symbol-specification) lists:
```
*, class, struct, interface, enum, property, method, field, event, delegate
```
(no `namespace` or `type_parameter`)

When I look at [Roslyn source](http://source.roslyn.io/#Microsoft.CodeAnalysis.Workspaces/NamingStyles/Serialization/SymbolSpecification.cs,60) it seems to have all of those and also maybe `parameter`.

I think it would be useful to consolidate both lists so it's clear what is supported. Also the table heading (**Symbol**) is a bit confusing as it specifically lists `applicable_kinds`?

**Comment by gewarren** [comment]
@ashmind thanks for pointing this out. I will resolve it.

**Comment by gewarren** [comment]
@kuhlenh can you resolve the discrepancies between the Roslyn source and what's listed in the topic?

**Comment by kuhlenh** [comment]
Hmmm, looks like I have made a mistake and thought we implemented `type_parameter` and `namespace` but we didn't actually. @dpoeschl can you please confirm?

**Comment by kuhlenh** [comment]
@ashmind `namespace` and `type_parameter` do not work today. I will update the documentation accordingly--sorry for the inconvenience!

**Comment by gewarren** [comment]
Documentation has been updated. Thanks @ashmind !
