### ISSUE TITLE
[CA2227] Update how to fix it.

### ISSUE THREAD

**Issue by Peppers911** [MicrosoftDocs/visualstudio-docs#2548]
I would suggest that "How to fix violations" would include other types of fixing this design problem, not just by saying remove "setters".
Other resolutions:
1) Explicitly make ReadOnly collection
2) Explicitly make Concurrent collection if by design you will modify collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db6af07-b7d6-9395-223e-1a0f83fb2405
* Version Independent ID: 5ee87730-ff01-2571-494e-91d29c5fe211
* Content: [CA2227: Collection properties should be read only - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227)
* Content Source: [docs/code-quality/ca2227-collection-properties-should-be-read-only.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca2227.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Kmaczek** [comment]
3. Setter can also be constructed in such a way that it preserve original reference:

List<BinanceSymbolValueVM> symbolsValues = new List<BinanceSymbolValueVM>();
public List<BinanceSymbolValueVM> SymbolsValues
{
    get { return symbolsValues; }
    set
    {
        symbolsValues.Clear();
        symbolsValues.AddRange(value);
    }
}

**Comment by gewarren** [comment]
@mavasani Could you comment on these suggestions? I see that this is a ported rule.

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22048](https://github.com/dotnet/docs/issues/22048)
