### ISSUE TITLE
VS Installer Exception (network layout silent installation without connectivity) 

### ISSUE THREAD

**Issue by ferdiozturk** [MicrosoftDocs/visualstudio-docs#256]
From my network layout folder I'm trying to install on a machine _without_ Internet connectivity
I'm using this command line:
`vs_setup.exe --passive --norestart --channelId "VisualStudio.15.Release" --installCatalogUri "file:///E:/Software/VisualStudio/layout_visual_studio_enterprise_2017/Catalog.json" --channelUri --installChannelUri "file:///E:/Software/VisualStudio/layout_visual_studio_enterprise_2017/ChannelManifest.json" --addProductLang de-DE --addProductLang en-US --includeRecommended --includeOptional --add Microsoft.Net.Component.4.7.SDK --add Microsoft.Net.Component.4.7.TargetingPack --add Microsoft.Net.ComponentGroup.4.7.DeveloperTools --add Component.GitHub.VisualStudio --add Microsoft.VisualStudio.Component.TypeScript.2.0 --add Microsoft.VisualStudio.Component.TypeScript.2.1 --add Microsoft.VisualStudio.Component.TypeScript.2.2 --add Microsoft.VisualStudio.Workload.Azure --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetCoreTools --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.Node --add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Workload.VisualStudioExtension`

It gives me this exception in logs, what is UpdateUri and where can I set it?
`2017-08-21T18:47:37 : Error : Failed to start the products provider service. error: Microsoft.VisualStudio.Setup.ChannelManifestDownloadException: Exception of type 'Microsoft.VisualStudio.Setup.ChannelManifestDownloadException' was thrown. ---> System.InvalidOperationException: UpdateUri must be set.
   at Microsoft.VisualStudio.Setup.Cache.ChannelManifestRepository.ValidateChannelUris(IChannelManifest channelManifest, IChannelManifest installChannelManifest)
   at Microsoft.VisualStudio.Setup.Cache.ChannelManifestRepository.AddChannel(ChannelManifestPair channelManifestPair, Boolean removeExistingCatalog)
   at Microsoft.VisualStudio.Setup.Cache.CacheManager.AddChannel(ChannelManifestPair channelManifestPair, Boolean removeExistingCatalog)
   at Microsoft.VisualStudio.Setup.ChannelManager.<AddAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---`

**Comment by ferdiozturk** [comment]
@TerryGLee Is this still being investigated? Is there a solution? We are blocked here. 300+ team projects waiting for VS2017. Thank you.

**Comment by TLai1** [comment]
@ferdiozturk Hello, I noticed that you don't have any value for your "--channelUri". This is causing the issue that you are seeing. This "channelUri" controls where Visual Studio will look for updates. If you want to keep the default behavior (Visual Studio looks online for updates), you can simply remove the "--channelUri" from your command line. If you wish to control how updates are deployed, please find more information here: https://docs.microsoft.com/en-us/visualstudio/install/controlling-updates-to-visual-studio-deployments

**Comment by ferdiozturk** [comment]
@TLa1 "If updates are not desired, --channelUri must be specified without an argument." (together with --installChannelUri). From: https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio

What I really try to achieve here is to NOT getting the installer or components updated, and run the installation automated on an build agent. I already also tried the new --noWeb and --noUpdateInstaller options. Still no luck

I would be very thankful if you could provide me a working CLI for the "really" offline installations, without the installer phoning home. Or just release the Offline .ISO installers again as always in previous VS versions. This online-first webinstaller behaviour is very frustrating

**Comment by TLai1** [comment]
@ferdiozturk 

There are two operations involved here. 

The first operation is you invoke the setup executable you downloaded from VisualStudio.com to create an offline layout for you. You use "vs_enterprise.exe --layout [layoutDir]" to achieve the goal. Here, as you said, the vs_enterprise.exe always downloads the latest components to create this offline layout. There is currently no way to force this to stay on a certain version. 

Once the first operation is done, the second operation is you install Visual Studio from the offline layout, and this is where you hit the issue in your description. To be 100% clear, this installation is always installing the exact version of this offline layout, no matter what value you give to the "channelUri" parameter. And it should not need any internet connection if you have created the offline layout in the first operation with all components that you want to install. The value of the "channelUri" controls what available FUTURE updates you will see after you finish this installation. It will be presented in either of two ways: an update notification in the Visual Studio IDE, or an "update" button for this product in the Visual Studio installer. If you wish not to have Visual Studio check for future updates, you can give the "channelUri" an arbitrary value of your choice. If you would like to control your own update cadence, you can follow the instruction in the below link to give a "channelUri" a proper value, which basically forms your own source of update to Visual Studio: https://docs.microsoft.com/en-us/visualstudio/install/controlling-updates-to-visual-studio-deployments

Leaving the "channelUri" value to be blank does not work here, and the documentation should be updated to reflect this.

**Comment by ferdiozturk** [comment]
@TLai1 I created the offline layout with the full set of workloads and components (en_US), including Recommended + Optional, but I want to deploy VS by cherrypicking from there (so I don't have to re-create the offline layout again when a component is missing). I tried to install on the offline Agent now without the channelId channelUri catalogUri etc. This does not work either, in the logs it tells it cannot download ChannelManifest.json...

Can you build me a commandline with the exact Options that you *know* will work on a completely offline Agent + with the workloads I specified to install (see above in my command line) - the layout on the Network path is up-to-date and language is en_US
Plus: I do not use the Response.json, I deleted this file, because I wanted to cherry pick workloads for different Scenarios (dev machines, build/release agents, etc)

**Comment by TLai1** [comment]
@ferdiozturk You can give the channelUri an arbitrary value to make this work, given that you are installing Visual Studio on an offline Agent and I presume you don't want to get this Agent online access to receive future update notification. You can just use this command line:

vs_setup.exe --passive --norestart --channelId "VisualStudio.15.Release" --installCatalogUri "file:///E:/Software/VisualStudio/layout_visual_studio_enterprise_2017/Catalog.json" --channelUri "https://visualstudio.com" --installChannelUri "file:///E:/Software/VisualStudio/layout_visual_studio_enterprise_2017/ChannelManifest.json" --addProductLang de-DE --addProductLang en-US --includeRecommended --includeOptional --add Microsoft.Net.Component.4.7.SDK --add Microsoft.Net.Component.4.7.TargetingPack --add Microsoft.Net.ComponentGroup.4.7.DeveloperTools --add Component.GitHub.VisualStudio --add Microsoft.VisualStudio.Component.TypeScript.2.0 --add Microsoft.VisualStudio.Component.TypeScript.2.1 --add Microsoft.VisualStudio.Component.TypeScript.2.2 --add Microsoft.VisualStudio.Workload.Azure --add Microsoft.VisualStudio.Workload.Data --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetCoreTools --add Microsoft.VisualStudio.Workload.NetWeb --add Microsoft.VisualStudio.Workload.Node --add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Workload.VisualStudioExtension

**Comment by timsneath** [comment]
@TerryGLee do you have what you need to update the docs here? Or do we need @TLai1 to help with a PR?

**Comment by TerryGLee** [comment]
I have what I need; thanks for checking in. We'll post an update to the page forthwith.

**Comment by TerryGLee** [comment]
Following up: We've posted updated information about the --channelURI to the following page:
https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio. Specifically, we added information that says, "If updates are not desired, `--channelUri` can point to a non-existent file. (for example, --channelUri C:\doesntExist.chman)"
