### ISSUE TITLE
Unused References button missing in Visual Studio 2017

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/visualstudio-docs#2593]
This states that this button is available in Visual Studio 2017, but I cannot find it where it is described to be.  There is also no indication that a Visual Studio component needs to be added to enable this ability.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faa89b2d-a184-5483-c774-cdabc9647b23
* Version Independent ID: 271c63d6-b480-8f87-8c40-e3270f670f0e
* Content: [References Page, Project Designer (Visual Basic) - Visual Studio](https://docs.microsoft.com/en-sg/visualstudio/ide/reference/references-page-project-designer-visual-basic?view=vs-2017)
* Content Source: [docs/ide/reference/references-page-project-designer-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/references-page-project-designer-visual-basic.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mdell-seradex Thanks, looking into it.

**Comment by gewarren** [comment]
I confirmed that "unused references" was removed from Visual Studio some time back. I'm updating the article now. Thank you for letting us know!

**Comment by mdell-seradex** [comment]
It is unfortunate that it was removed.  It was a handy feature that I have found no good replacement for.

Mark Dell

Seradex Inc.

**Comment by zoharyosef** [comment]
Why was it removed?
