### ISSUE TITLE
Feedback on Tutorial for Visual Studio Enterprise 2019

### ISSUE THREAD

**Issue by ekklhol** [MicrosoftDocs/visualstudio-docs#2596]
I would like to get access to the tutorials for Visual Studio 2019 so I can review and give feedback but I don't know where to find them. I only get access to VS 2017 version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2017)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ekklhol Thanks for your feedback! We do indeed have plans for adding Visual Studio 2019 versions of our tutorials, but we won't post them until the product is out of Preview.
