### ISSUE TITLE
Installing as a Visual Studio extension

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#2597]
Is it possible to include a visualizer as part of a VS extension? How can this be done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0470059-27e3-58a0-155e-84fbaefae158
* Version Independent ID: 95c9afb2-32f3-945b-9381-9f711179c77d
* Content: [How to: Install a Visualizer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2017)
* Content Source: [docs/debugger/how-to-install-a-visualizer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-install-a-visualizer.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by zspitz** [comment]
Posted on Developer Community -- https://developercommunity.visualstudio.com/idea/463047/enable-custom-visualizer-authors-to-wrap-them-in-v.html

**Comment by Mikejo5000** [comment]
@zspitz Thanks for updating this. Closing this doc issue.
