### ISSUE TITLE
Edit and Continue with static members

### ISSUE THREAD

**Issue by elliott-beach** [MicrosoftDocs/visualstudio-docs#2600]
It appears Edit and Continue doesn't work with static members: if I edit a static member `private static string ReadOnlyString = "foo"` to "not-foo", that change will not be reflected in code execution. My guess is that references to static variables are bound too early for this to work. It's true in this simple example, I could just use "edit value" in the debugger, but it's still unintuitive. I think what I can expect from VS here should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0b8848-c2af-28e9-28bf-761d1cdf3d6d
* Version Independent ID: 7cc1bef7-ef0c-5c62-2b5f-45910764ba80
* Content: [Supported Code Changes (C# and Visual Basic) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-csharp?view=vs-2017)
* Content Source: [docs/debugger/supported-code-changes-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/supported-code-changes-csharp.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@elliott-beach Thanks, I'll ask about it.

**Comment by Mikejo5000** [comment]
I'm told that if you already accessed the value of the variable and then changed the original value, then it should not work. Not by EnC reasons but by code execution design. Otherwise, EnC with static values should be supported.
Making a doc edit for this.
