### ISSUE TITLE
what is the replacement if this is deprecated?

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/visualstudio-docs#2643]
The article says "Web performance and load test functionality is deprecated. Visual Studio 2019 is the last version where web performance and load testing will be available." - what is the replacement feature (if there is one)? I don't want to learn an out of date skill!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91dd5df5-a6e9-dba6-470e-bfeb1f040ab4
* Version Independent ID: d56e043e-d5df-0802-6d14-00110785c210
* Content: [Fix non-detectable dynamic parameters in web performance test - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/fix-non-detectable-dynamic-parameters-in-a-web-performance-test?view=vs-2017)
* Content Source: [docs/test/fix-non-detectable-dynamic-parameters-in-a-web-performance-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/fix-non-detectable-dynamic-parameters-in-a-web-performance-test.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@dombat Please see [this comment](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2032#issuecomment-465317158).

**Comment by gewarren** [comment]
Closing in favor of #2032 .
