### ISSUE TITLE
Docker Hub example needed ?

### ISSUE THREAD

**Issue by mtmazurik** [MicrosoftDocs/visualstudio-docs#2644]
IMHO, this area should have in the left nav, a general description of Publish to DockerHub repository example / walkthrough.   It is a radio button for a Container Registry publish target type (Docker Hub).    

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff24ef73-d15f-83e5-d5d4-2b091b0a3e4b
* Version Independent ID: 90b6657e-19fd-1780-1897-727e7e1c4a2b
* Content: [Visual Studio Tools for Docker with ASP.NET Core - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/docker-tools?view=vs-2017)
* Content Source: [docs/containers/docker-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/docker-tools.md)
* Product: **visual-studio-windows**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Please see
https://docs.microsoft.com/en-us/visualstudio/containers/deploy-docker-hub?view=vs-2019

**Comment by ghogen** [comment]
@mtmazurik - Thanks for the feedback!  If you have any thoughts on this topic or suggestions for improvement, let me know.
