### ISSUE TITLE
Top Level Menus aren't possible anymore

### ISSUE THREAD

**Issue by javierdlg** [MicrosoftDocs/visualstudio-docs#2673]
With the recent changes to VS 2019, you can no longer add top level menus to VS. Instead you add them to the extensions top level menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b4a51b4-fb22-6621-8e50-915c95973701
* Version Independent ID: b8800c03-0708-eca0-e749-ea01879d5cc6
* Content: [Adding a Menu to the Visual Studio Menu Bar - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-menu-to-the-visual-studio-menu-bar?view=vs-2017)
* Content Source: [docs/extensibility/adding-a-menu-to-the-visual-studio-menu-bar.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-menu-to-the-visual-studio-menu-bar.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Fixed with https://github.com/MicrosoftDocs/visualstudio-docs-pr/commit/0cf1e165fb8e7ec6336824f07b1df1b5a240bace
Added note at top of page and 2019 specific section on new location
