### ISSUE TITLE
BuildDependsOn not correct

### ISSUE THREAD

**Issue by ciceroneves** [MicrosoftDocs/visualstudio-docs#2684]
After reading the documentation on [how to override depends on property](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2017#override-dependson-properties), I create a sample project and added my own target to be run before the build is started. The target only prints a message to the console.
When I build the project the message is not printed.
The project is class library targeting .NET Standard 2.0
Here is the csproj file

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>



  <PropertyGroup>
    <BuildDependsOn>
      $(BuildDependsOn);
      MyTarget;
    </BuildDependsOn>
  </PropertyGroup>

  <Target Name="MyTarget">
    <Message Importance="High" Text="######################## COWABUNGA!!!! ###################" />
  </Target>

</Project>
```

Here is the output in the console:
```
1>------ Rebuild All started: Project: BuildTargetTest, Configuration: Debug Any CPU ------
1>BuildTargetTest -> C:\Users\c.neves\source\repos\BuildTargetTest\BuildTargetTest\bin\Debug\netstandard2.0\BuildTargetTest.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

The name of the project is BuildTargetTest and I am using VS 2017 Professional

**Comment by Mikejo5000** [comment]
@ciceroneves Sorry for the slow reploy, but thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
