### ISSUE TITLE
Great first step

### ISSUE THREAD

**Issue by jubberman** [MicrosoftDocs/visualstudio-docs#2721]
Thanks Terry this is a perfect first step for a C# noob like me!  One thing that did confuse me for a couple of minutes is that the about.cshtml.cs file is locked for editing while the app is running in the browser.  Nothing beats hitting a problem to help the learning process though!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2376dee-30e0-850f-7572-6d32b351be3f
* Version Independent ID: 9c06f47f-8195-4736-3575-fffe1c51f763
* Content: [Tutorial: Get started with C# and ASP.NET Core](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core?view=vs-2017)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@jubberman Thanks so much for letting us know! I'll take a look at adding some information about the file being locked for edit.

**Comment by TerryGLee** [comment]
@jubberman To follow up... In the [Run, debug, and make changes](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core#run-debug-and-make-changes) section of this page, I added a note after step 2 that says, "You cannot edit code in the Visual Studio code editor when your project is open in a browser window."

Thanks again for the suggestion, and for the kudos!

Cheers,
~ Terry
