### ISSUE TITLE
Adding support to $projectname$ in Item Templates?

### ISSUE THREAD

**Issue by daniloToebdot** [MicrosoftDocs/visualstudio-docs#2722]
When creating item templates the documentation specifies that $rootnamespace$ can be used only for item templates, while $projectname$ only for new project dialogs, it makes sense to support using $projectname$ in item templates since it's part of the value of $rootnamespace$.
This specific case could be used in something like:
`global::$projectname$.Properties.Resources` 
Which is why I attempted to do. Please reply if this is the wrong place to add this issue so I can fix it and thanks for your time.

**Comment by gewarren** [comment]
@daniloToebdot If you feel this is a product suggestion rather than a docs issue, the best place to file it is at [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8).

**Comment by daniloToebdot** [comment]
@gewarren it indeed does feel more like a suggestion, the documentation is clear on what it does. I'm closing this issue and posting where you suggested,, thanks for the feedback.
