### ISSUE TITLE
Remove unused using with .editorconfig

### ISSUE THREAD

**Issue by aclerbois** [MicrosoftDocs/visualstudio-docs#2726]
Hello, 

There is an option to remove unused using when saving ? 

Thank you,

**Comment by gewarren** [comment]
@kendrahavens Do you know the answer to this?

**Comment by kendrahavens** [comment]
This isn't currently in the built-in tools, but you can apply code cleanup on save with an extension (and include the 'remove unused usings' fixer in your cleanup profile): https://marketplace.visualstudio.com/items?itemName=MadsKristensen.CodeCleanupOnSave

We are working on adding the code cleanup on save option to the built-in tools of Visual Studio. If this is something you are interested in be sure to [upvote to help us prioritize the issue](https://developercommunity.visualstudio.com/idea/525336/code-cleanup-on-save.html
).
