### ISSUE TITLE
Step 2 - editing Main() has error

### ISSUE THREAD

**Issue by fatherjack** [MicrosoftDocs/visualstudio-docs#2727]
The template code does not include "Import sys" so when adjusting Main() as per step 2 it generates an error.
Once the Import is added then there is a subsequent Exception unhandled error for 0 ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f46b5339-857e-3398-c654-97bd9757ea44
* Version Independent ID: ed197ab6-8b08-2d23-d8b5-5a85eedda590
* Content: [Python in Visual Studio tutorial step 4, debugging](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-04-debugging?view=vs-2017)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-04-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-04-debugging.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for pointing out the glitch. I'll get it fixed.

**Comment by kraigb** [comment]
Just FYI, I'm replacing that bit of code in favor of the option that closes the window automatically. See the PR above for details.

**Comment by fatherjack** [comment]
Thanks for giving it attention 👍
