### ISSUE TITLE
Not nearly enough detail here

### ISSUE THREAD

**Issue by Kyudos** [MicrosoftDocs/visualstudio-docs#2733]
Following these steps does not enable syntax highlighting for a new language (e.g., Fortran). Is it supposed to happen automatically once the grammar is in place? How do you figure out why it isn't working? Can you see in VS what language the TextMate system is picking up? (How) Can you edit the grammar and / or theme in VS? Please describe what is supposed to happen and how to diagnose problems. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* Content: [Add editor support for other languages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages?view=vs-2017)
* Content Source: [docs/ide/adding-visual-studio-editor-support-for-other-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Kyudos** [comment]
Ok... I figure out my problem...file's already open in your solution won't be highlighted until you close and re-open them. This makes it look like the highlighting isn't working.

**Comment by gewarren** [comment]
@Kyudos Thanks, I'll add that step to the article.
