### ISSUE TITLE
visual studio 2017 enterprise online installation doesn't work

### ISSUE THREAD

**Issue by pantrahul** [MicrosoftDocs/visualstudio-docs#2742]
I am trying to install visual studio 2017 enterprise version through installer, there are 2 packages which doesn't download - 
1) Microsoft.VisualStudio.AspNetPackages.Msi,version=1.0.30615.0
2) Microsoft.VisualStudio.AspNetCoreLocalFeed.Msi
All other packages got installed without any issue, i am facing the similar issue while installing professional version.

Package 'Microsoft.VisualStudio.AspNetPackages.Msi,version=1.0.30615.0' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/6c1b43f2-7c8c-4e81-b637-e8fca94a4558/438a75e1009cbbc50ef85b132a862623/aspnetwebtoolspackagesvs15_enu.msi'.
    Search URL
        https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualStudio.AspNetPackages.Msi;PackageAction=DownloadPackage;ReturnCode=0x80070002
    Details
        WebClient download failed: The operation has timed out
        WinInet download failed: Function: HttpQueryInfo-ResponseCode, HR: -2147024493, Message: Url 'https://download.visualstudio.microsoft.com/download/pr/6c1b43f2-7c8c-4e81-b637-e8fca94a4558/438a75e1009cbbc50ef85b132a862623/aspnetwebtoolspackagesvs15_enu.msi'
        Bits download failed: File not found.
    Impacted workloads
        .NET Core cross-platform development (Microsoft.VisualStudio.Workload.NetCoreTools,version=15.8.27906.1)
        .NET desktop development (Microsoft.VisualStudio.Workload.ManagedDesktop,version=15.8.27906.1)
        ASP.NET and web development (Microsoft.VisualStudio.Workload.NetWeb,version=15.8.27906.1)
    Impacted components
        ASP.NET and web development tools (Microsoft.VisualStudio.Component.Web,version=15.8.27825.0)
        ASP.NET and web development tools prerequisites (Microsoft.VisualStudio.ComponentGroup.Web,version=15.9.28219.51)
        Cloud tools for web development (Microsoft.VisualStudio.ComponentGroup.Web.CloudTools,version=15.8.27729.1)
        Microsoft Azure WebJobs Tools (Component.Microsoft.VisualStudio.Web.AzureFunctions,version=15.7.27617.1)
        Microsoft Azure WebJobs Tools (Microsoft.VisualStudio.ComponentGroup.AzureFunctions,version=15.7.27617.1)
        Windows Communication Foundation (Microsoft.VisualStudio.Component.Wcf.Tooling,version=15.8.27924.0)

**Comment by gewarren** [comment]
@pantrahul This is not a good place to report product issues (it's for documentation issues). Could you please report it at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html)? You should be able to [initiate the report from Visual Studio Installer](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017#report-a-problem-by-using-visual-studio).

**Comment by nitincomplete** [comment]
Downloaded Aspnetpackages.msi from below URL, installed separately, resume Visual Studio installation/Update wrke perfect for me.

https://download.visualstudio.microsoft.com/download/pr/6c1b43f2-7c8c-4e81-b637-e8fca94a4558/438a75e1009cbbc50ef85b132a862623/aspnetwebtoolspackagesvs15_enu.msi

**Comment by Omzig** [comment]
> Downloaded Aspnetpackages.msi from below URL, installed separately, resume Visual Studio installation/Update worked perfect for me.
> 
> https://download.visualstudio.microsoft.com/download/pr/6c1b43f2-7c8c-4e81-b637-e8fca94a4558/438a75e1009cbbc50ef85b132a862623/aspnetwebtoolspackagesvs15_enu.msi

I just had to do this on a new windows 11 box. what in the world is going on here.....
