### ISSUE TITLE
Add a note to documentation for NetCore/NetStandard support

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#2745]
As highlighted in https://github.com/dotnet/roslyn-analyzers/issues/2110, `Calculate Code Metrics` command does not work for NetCore/NetStandard projects in VS2017 or prior versions. This has been fixed in VS2019 and works identical for all C#/VB project types/target frameworks.

Note that the two other alternate approaches to compute code metrics (analyzer NuGet package and command line Code metrics generation) do work fine for NetCore/NetStandard projects even in VS2017.

We should document this for clarity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c654586-8571-cfe1-1ee1-3adaf79e2dcf
* Version Independent ID: 334b3914-dbcd-3ece-26b3-fab7c766a377
* Content: [Generate code metrics from the IDE or command line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017#command-line-code-metrics)
* Content Source: [docs/code-quality/how-to-generate-code-metrics-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-generate-code-metrics-data.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by MelbourneDeveloper** [comment]
Thanks @mavasani . Documentation is one step forward, but the IDE itself should give you some kind of indication as to **_why_** it cannot calculate the code metrics.

**Comment by MelbourneDeveloper** [comment]
@mavasani is this issue not going to be fixed in Visual Studio 2017?

**Comment by MelbourneDeveloper** [comment]
@mavasani the documentation is basically wrong. The Microsoft.CodeAnalysis.Metrics NuGet package is only in pre release so most people won't even be able to see it:

![image](https://user-images.githubusercontent.com/16697547/53271992-29cb3d80-3744-11e9-9ddc-9ac173416273.png)

I tried adding the package, but the Code Metrics tool inside Visual Studio 2017 still does not work.

![image](https://user-images.githubusercontent.com/16697547/53272150-92b2b580-3744-11e9-8496-6aa8b238f123.png)

**Comment by mavasani** [comment]
> I tried adding the package, but the Code Metrics tool inside Visual Studio 2017 still does not work.

@MelbourneDeveloper This NuGet package is not tied to Visual Studio's `Calculate Code Metrics` command at all. It is only for command line code metrics report generation: https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2017#command-line-code-metrics

**Comment by MelbourneDeveloper** [comment]
@masasani again, just so I understand correctly... 

Calculate code metrics does not work through the Visual Studio 2017 front end with .NET Core and .NET Standard projects. Is this correct? Shouldn't this be added to the documentation? This is what confused me.

**Comment by mavasani** [comment]
> Calculate code metrics does not work through the Visual Studio 2017 front end with .NET Core and .NET Standard projects. Is this correct?

Yes, this issue tracks exactly adding this information.
