### ISSUE TITLE
Couldn't find the solution explorer on linux

### ISSUE THREAD

**Issue by sbadan2** [MicrosoftDocs/visualstudio-docs#2747]
I couldn't find the solution explorer menu on a linux installation (version 1.31 on Ubuntu 16.04). I want to add a folder to the path in python and just couldn't figure out how to do it from this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34b9c9a-6356-61fa-d895-97c459465e75
* Version Independent ID: c317a64e-06a3-1081-08db-3fb278ea7fbf
* Content: [How Python search paths are applied - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/search-paths?view=vs-2017#feedback)
* Content Source: [docs/python/search-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/search-paths.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
I expect that you're using Visual Studio **Code**, the documentation is found on https://code.visualstudio.com/docs/python (and https://code.visualstudio.com/docs/python/environments#_use-of-the-pythonpath-variable for PYTHONPATH specifically).

The documentation on https://docs.microsoft.com/visualstudio/python, which you're commenting on here, is specifically for Visual Studio 2017, which is a Windows-only product to begin with. VS Code is the only Visual Studio product that runs on Linux.

I know it's confusing, and I certainly wish marketing wouldn't be so attached to trying brand everything with Visual Studio X or Y.

Hope that helps.

**Comment by sbadan2** [comment]
Hi @kraigb .
Thank you for the good explanation. Yes, I was confused.
