### ISSUE TITLE
DebugType

### ISSUE THREAD

**Issue by pzgulyas** [MicrosoftDocs/visualstudio-docs#2761]
Isn't "portable" also a valid value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2017)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by VPeruS** [comment]
And "embedded".
https://github.com/dotnet/roslyn/blob/5b81420f62b3bea0aabfd54d2876db5e5d53a2f1/src/Workspaces/Core/MSBuild/MSBuild/ProjectFile/CommandLineArgumentReader.cs#L156

**Comment by Mikejo5000** [comment]
Updating doc
