### ISSUE TITLE
Re: Cookiecutters

### ISSUE THREAD

**Issue by jawineh** [MicrosoftDocs/visualstudio-docs#2775]
Issue opened previously solved. the missing piece was the absence of Anaconda3 interpreter, which I had presumed was part of existing installed python package.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d264fa-6d4e-0128-b0a0-f997d01c19a9
* Version Independent ID: 7d2e1867-4890-20fc-f60c-45f0242b4f7f
* Content: [Quickstart - Create a Python project using Cookiecutter - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter?view=vs-2017)
* Content Source: [docs/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@jawineh If I understand correctly, this present issue can be closed, yes?

**Comment by kraigb** [comment]
Closing, because I think this is resolved. Feel free to reopen if necessary.
