### ISSUE TITLE
VB code missing from examples

### ISSUE THREAD

**Issue by n9jcv** [MicrosoftDocs/visualstudio-docs#2776]
At the top of this how to guide, it says this;
In this step, you create a Visual Basic or Visual C# project.

The only example code provided is C#.  Can you please make the Visual Basic code examples available?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ef3c94-32d7-fbe9-a271-3ac7efeb1e17
* Version Independent ID: 078a61ff-8bd7-1f6c-3637-76940c4cf904
* Content: [Read XML data into a dataset - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/read-xml-data-into-a-dataset?view=vs-2017)
* Content Source: [docs/data-tools/read-xml-data-into-a-dataset.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/read-xml-data-into-a-dataset.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@n9jcv The VB code is available if you select VB from the language picker at the top right. I realize this is not obvious at all so I can see why people miss it.

![image](https://user-images.githubusercontent.com/24882762/53435778-73b75c00-39ae-11e9-819a-bf8b4ca4a0f0.png)

**Comment by n9jcv** [comment]
Wow thanks for the quick response   yes I missed that function.  Seems if the choice was directly above each code block it would be more intuitive!  Thanks again very much

**Comment by gewarren** [comment]
Yes, I agree!

**Comment by shirgoldbird** [comment]
@n9jcv @gewarren We just shipped an update to the UI to hopefully make the code language picker more discoverable:

![image](https://user-images.githubusercontent.com/3937986/55592753-5af93f00-56ee-11e9-9e9c-09855320d633.png)

Down the line, we hope to add the picker to individual code blocks as well. Thanks for the feedback!

**Comment by n9jcv** [comment]
Thanks. I am really suprised some answered let alone make a change.  Again thanks!!!!!
-- 
Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 4/4/19, 17:29 Shir Goldberg <notifications@github.com> wrote:
@n9jcv @gewarren We just shipped an update to the UI to hopefully make the code language picker more discoverable:

Down the line, we hope to add the picker to individual code blocks as well. Thanks for the feedback!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MicrosoftDocs/visualstudio-docs","title":"MicrosoftDocs/visualstudio-docs","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/MicrosoftDocs/visualstudio-docs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shirgoldbird in #2776: @n9jcv @gewarren We just shipped an update to the UI to hopefully make the code language picker more discoverable:\r\n\r\n![image](https://user-images.githubusercontent.com/3937986/55592753-5af93f00-56ee-11e9-9e9c-09855320d633.png)\r\n\r\nDown the line, we hope to add the picker to individual code blocks as well. Thanks for the feedback!"}],"action":{"name":"View Issue","url":"https://github.com/MicrosoftDocs/visualstudio-docs/issues/2776#issuecomment-480086493"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/visualstudio-docs/issues/2776#issuecomment-480086493",
"url": "https://github.com/MicrosoftDocs/visualstudio-docs/issues/2776#issuecomment-480086493",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
