### ISSUE TITLE
Multiple Format Specifiers

### ISSUE THREAD

**Issue by yxrkt** [MicrosoftDocs/visualstudio-docs#2778]
Is there a way to use multiple format specifiers at once? For example, if I have an array of enums:
m_enums, 2,en

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5c135d-ace1-1f09-041a-13411c054ff3
* Version Independent ID: 083fc572-d877-2216-19a9-326636c1d8e6
* Content: [Format specifiers in the debugger (C++) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2017)
* Content Source: [docs/debugger/format-specifiers-in-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/format-specifiers-in-cpp.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@yxrkt I would expect you can use multiple specifiers, when they are not mutually exclusive. Did you test this and it didn't work?

**Comment by yxrkt** [comment]
I've tried many different syntaxes, but I haven't found anything that works yet

**Comment by Mikejo5000** [comment]
@andysterland @leslierichardson95 Is there anything we can say in the docs about support for using multiple specifiers?

**Comment by haferburg** [comment]
The following worked in 2017:

    <DisplayString>{Data,[Length]s}</DisplayString>

**Comment by Mikejo5000** [comment]
@yxrkt  Thanks for your feedback; we appreciate it. If you have additional questions, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
