### ISSUE TITLE
Detailed documentation on workflow for async packages

### ISSUE THREAD

**Issue by manjeetsingh02** [MicrosoftDocs/visualstudio-docs#2779]
I would really appreciate if we could have a sample test for InitializeAsync() for AsyncPackage. I could not find a way to initialize package asynchronously with a ServiceProvider- one similar to IVsPackage.SetSite()

It'd also be great if we could get more documentation on how packages are loaded asynchronously - eg. - AsyncPackage implements one interface with name IAsyncLoadablePackageInitialize. Implementation of its method "Initialize" does the important initializations before the InitializeAsync. It'd be really helpful to see under the hood on when this method is called, and from where.

**Comment by manjeetsingh02** [comment]
Is there any update on this?

**Comment by WilliamAntonRohm** [comment]
@manjeetsingh02 -- please provide additional context regarding your feedback, such as a topic page link.
