### ISSUE TITLE
MSBuild Documentation example for Exclude in Item does not work and is clearly untested

### ISSUE THREAD

**Issue by ncook-vero** [MicrosoftDocs/visualstudio-docs#2780]
[Enter feedback here]
I am struggling to make Exclude in MSBuild work. 
The following does not exclude any of the items requested to be excluded. Why?

```
        <CommonDllsSDK 
            Include="$(SignedBinaries)\CommonDlls\**\*.*"
            Exclude="$(SignedBinaries)\CommonDlls\**\*Res*.*;
                     $(SignedBinaries)\CommonDlls\**\Helper.exe;
                     $(SignedBinaries)\CommonDlls\**\Application*.*;
                     $(SignedBinaries)\CommonDlls\**\ErrorReporter*.*" 
         />
```

Your documentation doesn't even provide a working example.
This is not conducive to an adoption of your technology.
Spot the error here:
```
<Project DefaultTargets="Compile"
    xmlns="http://schemas.microsoft.com/developer/msbuild/2003" >

    <PropertyGroup>
        <builtdir>built</builtdir>
    </PropertyGroup>

    <ItemGroup>
        <CSFile Include="*.cs Exclude="Form2.cs"/>

        <Reference Include="System.dll"/>
        <Reference Include="System.Data.dll"/>
        <Reference Include="System.Drawing.dll"/>
        <Reference Include="System.Windows.Forms.dll"/>
        <Reference Include="System.XML.dll"/>
    </ItemGroup>

    <Target Name="PreBuild">
        <Exec Command="if not exist $(builtdir) md $(builtdir)"/>
    </Target>

    <Target Name="Compile" DependsOnTargets="PreBuild">
        <Csc Sources="@(CSFile)"
            References="@(Reference)"
            OutputAssembly="$(builtdir)\$(MSBuildProjectName).exe"
            TargetType="exe" />
    </Target>
</Project>

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30273668-658c-d411-5b6d-7f58256bb0f3
* Version Independent ID: c8812ae3-0fb1-a30f-02dd-ebc2d28b9dc8
* Content: [How to: Exclude Files from the Build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-exclude-files-from-the-build?view=vs-2017)
* Content Source: [docs/msbuild/how-to-exclude-files-from-the-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-exclude-files-from-the-build.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
The example has been fixed in #3070

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, do you see a problem in the example cited by @ncook-vero ?

**Comment by ncook-vero** [comment]
@Mikejo5000 it's in here (#3070 ?)
` <CSFile Include="*.cs Exclude="Form2.cs"/>`

**Comment by Mikejo5000** [comment]
OK, that is a good idea. It's possible the error in the example came into the content later, as a change to the example that also included a typo.
