### ISSUE TITLE
The title is incorrect - should not be limited to c# and VB

### ISSUE THREAD

**Issue by olgaark** [MicrosoftDocs/visualstudio-docs#2781]
The title is incorrect - the feature can be used in any msbuild based projects, like vcxproj, etc. not only c# and VB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017#feedback)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updating doc
