### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by JWillis12** [MicrosoftDocs/visualstudio-docs#2784]
It opened google chrome but nothing appeared. Also I only had main instead of app-bundle.js and app-bundle.js.map when I opened the dist folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2017)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@JWillis12 Hi, see this section of the doc, where "app-bundle.js" gets specified as your output file in the webconfig.js:
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2017#configure-webpack-and-typescript-compiler-options

**Comment by Mikejo5000** [comment]
Need more info
