### ISSUE TITLE
Certificate Chain issue not mentioned here

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/visualstudio-docs#2785]
Selecting a certificate with a certificate chain still appears to be unsupported but it is not mentioned here.
This issue is mentioned on the following Microsoft page along with possibly outdated information on how to address it: https://docs.microsoft.com/en-us/previous-versions/aa730868(v=vs.80)#signing-assemblies
Specifically it is the area that mentions "The .pfx file cannot include certificate chaining information. (If the .pfx file does include this information, the following import error will occur: "Cannot find the certificate and private key for decryption.")" and how to address it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9bfda6b-ea3e-78b5-0cb3-13b8295efdae
* Version Independent ID: 60b80786-71a8-b947-7aa8-a9d9720c304e
* Content: [How to: Sign application and deployment manifests - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/ide/how-to-sign-application-and-deployment-manifests?view=vs-2017#feedback)
* Content Source: [docs/ide/how-to-sign-application-and-deployment-manifests.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-sign-application-and-deployment-manifests.md)
* Product: **visual-studio-windows**
* GitHub Login: @MikeJo5000
* Microsoft Alias: **gewarren**

**Comment by mdell-seradex** [comment]
Thank you for the update, however can a link also be added the refers to how to remove the certificate chain?
Thank you!

**Comment by gewarren** [comment]
@Mikejo5000 Can you help out with that question?

**Comment by Mikejo5000** [comment]
Sure, I'll take a look at this.

**Comment by mdell-seradex** [comment]
Thank you!
Much appreciated.
