### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by gmanvel** [MicrosoftDocs/visualstudio-docs#2786]
Link to MSDN blog is broken:

For more information, see "Performance pattern 1: Identifying lock contention" in Hazim Shafi's Parallel performance tools for Windows blog on the MSDN blog Web site.

URL returns page not found
https://blogs.msdn.microsoft.com/hshafi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84100a50-c4c1-7369-12e1-3489487d6f58
* Version Independent ID: d5ab85d8-7456-78df-8aec-5dac0ad1a710
* Content: [Common Patterns for Poorly-Behaved Multithreaded Applications - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/common-patterns-for-poorly-behaved-multithreaded-applications?view=vs-2017)
* Content Source: [docs/profiling/common-patterns-for-poorly-behaved-multithreaded-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/common-patterns-for-poorly-behaved-multithreaded-applications.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@gmanvel Thanks, I'll take a look at that.

**Comment by Mikejo5000** [comment]
@gmanvel Looks like the blog post was decomissioned. Similar content referencing Hazim Shafi's post is available here:
https://msdn.microsoft.com/en-us/magazine/ff714587.aspx
I can update the link
