### ISSUE TITLE
Code samples

### ISSUE THREAD

**Issue by BHboss** [MicrosoftDocs/visualstudio-docs#2787]
Instructions in the tutorial are confusing when the user is directed to modify existing code with sample code. It is not intuitive where to place the new code. (lots of trial-and-error to get it right)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1cd413-a2a8-9cb5-3f3a-94822a96af51
* Version Independent ID: feadb7ab-ebba-051d-e68c-a758235ce514
* Content: [Learn Django tutorial in Visual Studio step 3, static files and pages](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages?view=vs-2017)
* Content Source: [docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@BHboss Thanks for the feedback. We'll look into making improvements.

**Comment by JoshuaPartlow** [comment]
@BHboss are you able to provide more details about which code copy steps you found unclear? It sounds like you eventually got things in the right place, so any feedback you have would be helpful. If you're interested, we also welcome PRs for content improvements.

**Comment by JoshuaPartlow** [comment]
Closing issue pending more details.
