### ISSUE TITLE
get_machineType does not return CV_CPU_TYPE_e

### ISSUE THREAD

**Issue by rayfo** [MicrosoftDocs/visualstudio-docs#2791]
*pRetVal is not a value from the CV_CPU_TYPE_e enumeration.
Rather, it is an IMAGE_FILE_MACHINE_* value (from the DDK's ntimage.h).
For example:
IMAGE_FILE_MACHINE_I386 = 0x014c
IMAGE_FILE_MACHINE_AMD64 = 0x8664
etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61154141-cb12-76e8-6b63-6db8ed8ea767
* Version Independent ID: 722f0c89-f957-0b74-3ab9-f8c4f094a8c2
* Content: [IDiaSymbol::get_machineType - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/idiasymbol-get-machinetype?view=vs-2017#feedback)
* Content Source: [docs/debugger/debug-interface-access/idiasymbol-get-machinetype.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-interface-access/idiasymbol-get-machinetype.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rayfo Thanks for the feedback. Looks like it should link here: https://docs.microsoft.com/en-us/windows/desktop/SysInfo/image-file-machine-constants
Sound correct to you?

**Comment by Mikejo5000** [comment]
Updating
