### ISSUE TITLE
Support for IronPython and .NET?

### ISSUE THREAD

**Issue by Shalin1234** [MicrosoftDocs/visualstudio-docs#2806]
Does Visual Studio need separate extensions to work with IronPython and .NET ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 394742b8-d974-8b1e-5800-b0fca1ef6a54
* Version Independent ID: 3065ca4c-b293-aa89-ca76-bcf718f9e21c
* Content: [Python in Visual Studio tutorial step 0, installation](https://docs.microsoft.com/en-za/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-00-installation?view=vs-2017#feedback)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-00-installation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-00-installation.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Support for IronPython is built in with the Python workload for Visual Studio, as indicated on https://docs.microsoft.com/en-za/visualstudio/python/overview-of-python-tools-for-visual-studio?view=vs-2017#features-matrix under the table for "Desktop." VS also detects IronPython environments. So no, you don't need any other extension.

Python support includes IronPython application templates (see https://docs.microsoft.com/en-za/visualstudio/python/managing-python-projects-in-visual-studio?view=vs-2017#project-templates) and debugging (see https://docs.microsoft.com/en-za/visualstudio/python/debugging-python-in-visual-studio?view=vs-2017#launch-mode-options).

**Comment by Shalin1234** [comment]
Okay, thank you very much for that.
