### ISSUE TITLE
The Example Is Incomplete

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/visualstudio-docs#2809]
The incomplete example is unhelpful. How about an example that shows the task executing in the context of a REAL build, even if it's only HelloWorld.c?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dbbe593-3f96-ce66-ceb3-0f7e6161dba9
* Version Independent ID: 3afb0fe4-6c5a-e899-61e1-37cd33963eba
* Content: [Task Writing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/task-writing?view=vs-2017)
* Content Source: [docs/msbuild/task-writing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/task-writing.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I tested the last two examples on the page (the project XML code that invokes SampleTask3), and yes, I'm having difficulty getting it to work. Specifically, the Log.LogMessage throws InvalidOperationException, with the message "Task attempted to log before it was initialized..." @rainersigward Rainer, do you have any thoughts about making the sample more complete?

**Comment by rainersigwald** [comment]
@Mikejo5000 I'd like to hear more about your failure. I just tried with that example and it worked fine: [2809.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/3458775/2809.zip)

**Comment by Mikejo5000** [comment]
I'm sure it's something incorrect in my environment or the command I'm using (.NET Framework project). I tried your zip, and I can build the DLL fine using "dotnet msbuild -restore". I just need to test it.

**Comment by Mikejo5000** [comment]
Tested fine after fixing the path reference. So, in terms of the original issue here, the request is for a "Hello World" type example, which probably means a more E2E experience. I would say that doesn't really belong in this topic, though perhaps in a "Get started" topic similar to the two walkthroughs. (What could be added in a walkthrough is SimpleTask.csproj, nuget.config file, the dotnet CLI command, and the final MSBuild command.) PV's on this article aren't that high, so I'm not sure if writing MSBuild Tasks in C# code is a high-priority scenario that warrants a separate "Get started" topic. Also, the zip example is SDK-style, so maybe that would be confusing to some folks. @rainersigwald for any additional comments.

**Comment by Mikejo5000** [comment]
Currently out of scope to add a new getting started type topic.
