### ISSUE TITLE
How do I create a Docker container for a .NET Framework app??

### ISSUE THREAD

**Issue by Cloudmersive** [MicrosoftDocs/visualstudio-docs#2810]
This article only applies to .NET Core!  And it doesn't even make that clear

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3adcabc-7e2b-da97-6899-35f1d97f1758
* Version Independent ID: 0684394a-7371-f3b5-d6aa-f236882db6f4
* Content: [Debugging apps in a local Docker container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/vs-azure-tools-docker-edit-and-refresh?view=vs-2017#feedback)
* Content Source: [docs/containers/vs-azure-tools-docker-edit-and-refresh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/vs-azure-tools-docker-edit-and-refresh.md)
* Service: **multiple**
* Product: **visual-studio-windows**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by delormej** [comment]
+1 to the comment above, but I found good instructions on how to remote debug a non-ASP.NET application (.NET Framework console app) here: https://www.richard-banks.org/2017/02/debug-net-in-windows-container.html

**Comment by StingyJack** [comment]
I logged another [issue](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3078) for this and other related topics. Hopefully one of us can elicit a usable response.

**Comment by ghogen** [comment]
Added a section for a console app in May - I think we can close now.  There should be no need to do anything to add the remote debugger components to the container- both VS 2017 and VS 2019 do this.
