### ISSUE TITLE
Error in Step 6: "Sample project for creating unit tests" code has an error

### ISSUE THREAD

**Issue by grayrhino** [MicrosoftDocs/visualstudio-docs#2812]
The the last line of the sample code says "Console.WriteLine("Current balance is ${0}", ba.Balance);". However, the "Console" function is only available if you create a Console App(.NET Core) or (.Net Framework). In this example, at step 4, we are creating Class Library therefore calling Console function gives an error. The solution is adding System.Diagnostics namespace and changing Console function to Debug function as so: The "Console" function is only available if you create a Console App(.NET Core) or (.Net Framework);. Please correct me if I am missing something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* Content: [Create and run unit tests for managed code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2017#feedback)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I'm changing the article to create a console app instead of a class library. Thanks for the heads up on this @grayrhino !
