### ISSUE TITLE
Tutorial seems incomplete at Step #3

### ISSUE THREAD

**Issue by chriscallan** [MicrosoftDocs/visualstudio-docs#2817]
Step #3 of the tutorial on making a memory game clearly assigns single character strings to the label.Text field, but the exampel showing what the game would look like after that step shows an image box with images that hadn't been seen before that in the tutorial.  I know how to work around it, but it's still frustrating to see a tutorial that skips steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac5e066-696c-95ba-8fa1-19d8afe5dc4d
* Version Independent ID: 1239320c-0e15-da0e-c6b4-72af0a8dac9c
* Content: [Step 3: Assign a random icon to each label - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-3-assign-a-random-icon-to-each-label?view=vs-2017#to-continue-or-review)
* Content Source: [docs/ide/step-3-assign-a-random-icon-to-each-label.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-3-assign-a-random-icon-to-each-label.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@chriscallan Thanks for your feedback! We'll put this in the April queue to get fixed. (We have other higher priority content plans for our March queue.)

**Comment by ornellaalt** [comment]
Hi @chriscallan, I'm having trouble understanding your feedback-- in part 1 of Step 3, we assign iconLabel.Text to a random icon in the AssignIconsToSquares() method. In part 3, we call the AssignIconsToSquares() method to fill up the board game with icons, which is shown in the photo in part 5 (after we re-run the program). 

Could you please clarify what you would like to see added to [this page](https://docs.microsoft.com/en-us/visualstudio/ide/step-3-assign-a-random-icon-to-each-label?view=vs-2019), and what you are needing to work around?

**Comment by chriscallan** [comment]
I filed that so long ago that it took me a while to figure out what was
wrong again.  As I stated in the original defect, “Step #3
<https://github.com/MicrosoftDocs/visualstudio-docs/pull/3> of the tutorial
on making a memory game clearly assigns single character strings to the
label.Text field, but the example showing what the game would look like
after that step shows an image box with images that hadn't been seen before
that in the tutorial. I know how to work around it, but it's still
frustrating to see a tutorial that skips steps."

Follow things back to the Step #2, and you can see the ‘icons’ variable
populated as,

List<string> icons = new List<string>()

    {

        "!", "!", "N", "N", ",", ",", "k", "k",

        "b", "b", "v", "v", "w", "w", "z", "z"

    };

So when you get to item #5 in Step #3, you’ve assigned things like “!”,
“N”, “,” to the Text label, but you show the WinForm with icon images
populated in the Label’s ‘Text’ property.



Chris Callan

*Senior QA Engineer*

www.Base2S.com

*Cell:* (206) 383-5829

“Don't be fooled by the calendar. There are only as many days in the year
as you make use of.”

--Charles Richards



*From:* Ornella Altunyan <notifications@github.com>
*Sent:* Tuesday, March 31, 2020 11:20 AM
*To:* MicrosoftDocs/visualstudio-docs <visualstudio-docs@noreply.github.com>
*Cc:* chriscallan <Chris.Callan@Base2s.com>; Mention <
mention@noreply.github.com>
*Subject:* Re: [MicrosoftDocs/visualstudio-docs] Tutorial seems incomplete
at Step #3 (#2817)



Hi @chriscallan <https://github.com/chriscallan>, I'm having trouble
understanding your feedback-- in part 1 of Step 3, we assign iconLabel.Text
to a random icon in the AssignIconsToSquares() method. In part 3, we call
the AssignIconsToSquares() method to fill up the board game with icons,
which is shown in the photo in part 5 (after we re-run the program).

Could you please clarify what you would like to see added to this page
<https://docs.microsoft.com/en-us/visualstudio/ide/step-3-assign-a-random-icon-to-each-label?view=vs-2019>,
and what you are needing to work around?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/MicrosoftDocs/visualstudio-docs/issues/2817#issuecomment-606792009>,
or unsubscribe

**Comment by ornellaalt** [comment]
Thanks  @chriscallan--  I'll add another clarification that the "icons" are actually just letters in the Webdings font in item #5 of Step #3. There's already a comment in the code you copied above from Step #2 that says "Each of these letters is an interesting icon in the Webdings font, and each icon appears twice in this list." Closing out this issue.
