### ISSUE TITLE
Missing data in the description of natvis files for Visual studio

### ISSUE THREAD

**Issue by rchiodo** [MicrosoftDocs/visualstudio-docs#282]
This topic here:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md

Doesn't describe what the Exec keyword in CustomListItems does, and what's allowed. There should be some mention of native intrinsics that are allowed. In fact here's the full list of what's allowed:

- Logical operators
- Arithmetic operators
- Assignment operators
- strlen,
        wcslen,
        strnlen,
        wcsnlen,
        strcmp,
        wcscmp,
        _stricmp,
        _strcmpi,
        _wcsicmp,
        strncmp,
        wcsncmp,
        _strnicmp,
        _wcsnicmp,
        memcmp,
        memicmp,
        wmemcmp,
        strchr,
        wcschr,
        memchr,
        wmemchr,
        strstr,
        wcsstr,        
        __log2,
        GetLastError,
        TlsGetValue,
        DecodeHString,
        WindowsGetStringLen,
        WindowsGetStringRawBuffer,
        WindowsCompareStringOrdinal,
        RoInspectCapturedStackBackTrace,
        CoDecodeProxy,
        GetEnvBlockLength,
        DecodeWinRTRestrictedException,
        DynamicMemberLookup,
        ConcurrencyArray_OperatorBracket_idx, //Concurrency::array<>::operator[index<>] and operator(index<>)
        ConcurrencyArray_OperatorBracket_int, //Concurrency::array<>::operator(int, int, ...)
        ConcurrencyArray_OperatorBracket_tidx, //Concurrency::array<>::operator[tiled_index<>] and operator(tiled_index<>)
        ConcurrencyArrayView_OperatorBracket_idx, //Concurrency::array_view<>::operator[index<>] and operator(index<>)
        ConcurrencyArrayView_OperatorBracket_int, //Concurrency::array_view<>::operator(int, int, ...)
        ConcurrencyArrayView_OperatorBracket_tidx, //Concurrency::array_view<>::operator[tiled_index<>] and operator(tiled_index<>)
        TreeTraverse_Init,  //Initializes a new tree traversal
        TreeTraverse_Next,  //Returns nodes in a tree
        TreeTraverse_Skip,  //Skips nodes in a pending tree traversal
        Stdext_HashMap_Int_OperatorBracket_idx,
        Std_UnorderedMap_Int_OperatorBracket_idx,
        DecodePointer,
        __findNonNull,
        DynamicCast

**Comment by Mikejo5000** [comment]
Opened new PR on the issue:
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/923

**Comment by rchiodo** [comment]
I get a 404 on that PR link? Can you double check?

**Comment by Mikejo5000** [comment]
The fix is on the private repo. You would need to be in the MicrosoftDocs group. But you should be able to review it here:
https://review.docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?branch=mikejo-br4
Note: First sentence will read "You can use Exec..." after typo fix comes in.

**Comment by rchiodo** [comment]
Thanks looks good :)
