### ISSUE TITLE
What happends regarding the benefits that only came with annual subscription

### ISSUE THREAD

**Issue by Trissy08** [MicrosoftDocs/visualstudio-docs#2823]
As stated under https://visualstudio.microsoft.com/vs/pricing/ on the Cloud vs Standard subscriptions tab.  Under 'Includes subscriber benefits' section.  It states 'Yes for annual / No for monthly'

What happens now that new users can only purchase monthly subscriptions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bdcfd-bb8a-a0c5-8a57-fd713889e849
* Version Independent ID: 1fe48f30-7069-d58f-5207-07b58b01d1fa
* Content: [How to purchase Visual Studio cloud subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-overview#feedback)
* Content Source: [subscriptions/vscloud-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-overview.md)
* Product: **visual-studio-windows**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by Trissy08** [comment]
If the new users who can only purchase monthly subscriptions and no longer get the same benefit as the annual users on the previous model.  What benefits do they lose?  Azure credits?  Licensing?  Services?

I cannot see any reference to this subject in any of the articles I've read.  Surely this should be highlighted.

**Comment by Trissy08** [comment]
The following shows some of the benefits you get with annual subscriptions

Azure Credits = https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure
Technical Support = https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-tech-support
PluralSight = https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-pluralsight

I think this needs to be clearer.  As it feels like only providing monthly subscriptions - no benefits @ same pricing is not an attractive proposition

**Comment by evanwindom** [comment]
@Trissy08 -- Thanks for reaching out.  The articles are intended to provide information about the specific benefits, and really aren't designed to compare subscription offers.  Subscriber benefits never were part of the monthly subscriptions -- They never had the same benefits as the annual subscriptions.    

The price differences between the monthly and annual cloud or standard (retail & Volume License) subscriptions has always reflected the differences in the benefits.  For example, twelve months of a Visual Studio Enterprise cloud subscription costs $3,000US.  The first year of a standard Visual Studio Enterprise subscription costs $5,999US.  Those prices reflect the significant differences in the benefits included in the monthly versus standard subscriptions. 

Regarding the change to the annual cloud subscriptions, while they're not available to new subscribers, subscribers who already have annual cloud subscriptions can continue to use them, and can increase the number of subscriptions they have.  So, anyone who still has an annual subscription will not experience any change to their benefits.
