### ISSUE TITLE
Incorrect content in the 'Learn about the similarities between Swift and C#' poster

### ISSUE THREAD

**Issue by ttitus** [MicrosoftDocs/visualstudio-docs#2825]
In the classes section of the poster, the content for 'access' row is placed against the 'inheritance' row causing many row contents to be misaligned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a762b2ab-91e6-eda8-01ad-977f89d4462b
* Version Independent ID: cca4863b-8658-968f-b1fa-5e2b0d292f56
* Content: [Cross-Platform Mobile Development in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/cross-platform-mobile-development-in-visual-studio?view=vs-2017#feedback)
* Content Source: [docs/cross-platform/cross-platform-mobile-development-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/cross-platform-mobile-development-in-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Can you share a screenshot? This is how it looks for me:
![classes](https://user-images.githubusercontent.com/199373/53828894-bbe8f800-3f33-11e9-8f29-a1b3a34c3a59.png)

**Comment by ttitus** [comment]
That is the way it looks for me too.
I believe it should look like:
![updated](https://user-images.githubusercontent.com/12654443/54047329-9eae6680-418b-11e9-9cb6-63ad50f2a36d.png)

(Except for those two block shifts everything else seems ok. So I did a tear-off to focus on the changes only.)

**Comment by conceptdev** [comment]
Sorry, I did not fully understand the original comment. You're definitely right about the mismatch.

I'll have to see if I can find the source of the poster to fix. Until then, hopefully anyone else who's confused by this will notice your comment!

Thanks for the feedback!
