### ISSUE TITLE
Fix FRAMEINFO members list

### ISSUE THREAD

**Issue by ulex** [MicrosoftDocs/visualstudio-docs#283]
https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/reference/frameinfo

Frame info member m_fHasDebugInfo described three times:

> m_fHasDebugInfo
> Non-zero (TRUE) if debug information exists in the given frame.
> 
> m_fHasDebugInfo
> Non-zero (TRUE) if the stack frame is associated with code that is no longer valid.
> 
> m_fHasDebugInfo
> Non-zero (TRUE) if the stack frame is annotated by the session debug manager (SDM).

Also last parameter is incorrect. In documentation it calls either `int m_fAnnotatedFrame` or `int               m_fAnnotatedFrame`, but in metadata it has name `uint m_dwFlags` with undocumented meaning.
In my samples it can be 0, 2 or 3. What does this parameter actually means?

**Comment by ulex** [comment]
Found enum in metadata, it is called enum_FRAMEINFO_FLAGS_VALUES
But documentation is absent for this enum 🙁

**Comment by Mikejo5000** [comment]
Updating doc
