### ISSUE TITLE
How to access Relationships from Text Templates

### ISSUE THREAD

**Issue by fuzzifikation** [MicrosoftDocs/visualstudio-docs#2833]
This may be a stupid question but... How do I access a Relationship (and it's properties) from the Text Template of a Generated Language?

This content clearly describes how to access Models - but what about Relationships?
I've defined Properties in my Relationships between the Elements of my DSL. I would like to access the Relationship Properties that the user of the DSL assigns values to in my Text Template. How do I do that?

Please please include an Example of this.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a408ced-a168-b944-6f91-321a5b9c9416
* Version Independent ID: 9b22f9f4-6d37-3fd1-b962-74d7049c8001
* Content: [Accessing Models from Text Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/accessing-models-from-text-templates?view=vs-2017)
* Content Source: [docs/modeling/accessing-models-from-text-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/accessing-models-from-text-templates.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Unfortunately, we don't currently have the resources to address this issue, based on its priority. If you do figure out how to access relationships, feel free to submit a doc edit yourself (the Edit button is in the upper right-hand corner of each docs page).
