### ISSUE TITLE
False alarm of C6313

### ISSUE THREAD

**Issue by snowendless** [MicrosoftDocs/visualstudio-docs#2837]
a well known lib we used is repidxml, which is complained C6313 by Visaul Studio code analysis tool at:
 //////////////code start//////////////    
       if (!(Flags & parse_no_string_terminators))
                *text = Ch('\0');
////////////code end/////////////
while the value of "parse_no_string_terminators" is not zero

    const int parse_no_string_terminators = 0x4;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0552e955-57d6-6fe7-06d4-f5d5684d2506
* Version Independent ID: 285fef01-50a8-286b-8f73-5689bdb8e9dc
* Content: [C6313 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c6313?view=vs-2017)
* Content Source: [docs/code-quality/c6313.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c6313.md)
* Product: **visual-studio-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gewarren** [comment]
Since this sounds like a product issue, please report it at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which the product team actively monitors. Initiate your report by choosing Help > Send Feedback > Report a Problem from Visual Studio.
