### ISSUE TITLE
Completely irrelevant for Visual Studio for Mac

### ISSUE THREAD

**Issue by jelmerS2** [MicrosoftDocs/visualstudio-docs#2838]
I'm running Visual Studio for Mac with Unity. Hardly anything from this guide seems to apply... Where should I look?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56378a75-b639-d64b-d7fb-00a7eafa20b5
* Version Independent ID: c66870c5-4153-7b42-7aad-fc454c39f9cd
* Content: [Using Visual Studio Tools for Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2017)
* Content Source: [docs/cross-platform/using-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/using-visual-studio-tools-for-unity.md)
* Product: **visual-studio-windows**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by conceptdev** [comment]
Hi @jelmerS2 thanks for your feedback. There is some Mac-specific info here
https://docs.microsoft.com/visualstudio/mac/unity-tools

We'll try to make this more obvious on the pages.
