### ISSUE TITLE
This should be more clear and the (some of the) sets should be hierarchically built.

### ISSUE THREAD

**Issue by mkamoski** [MicrosoftDocs/visualstudio-docs#2839]
...

This should be more clear and the sets should be hierarchically built

For example, "This should be more clear" in that it should either have NO overlaps in rules set (that is Rule1 does NOT exist in &gt;1 set)... 
...OR... 
....it should specifically state the overlaps-- for example, it is NOT clear if "Managed Recommend" includes all of "Basic Design Guidelines" rules, from the description given...
...OR....
...it should specifically state what happens if RuleSetA and RuleSetB are put in CustomRuleSetC, and if RuleSetA and RuleSetB both contain Rule1, is it idempotent resolution (hopefully!) or some other type of adjudication???

Regarding "the sets should be hierarchically built", it would be one way to make this more simple and clear.

SetA
SetB = SetA + OtherRules
SetC = SetA + SetB + OtherRules
...etc...
...and ensure there is NO rule that exists in more than 1 set...
...so they become building blocks...
...and then one can build CustomRuleSetX and include at-will what is desired, and know there is no redundancy, etc.

Yes, I know we can "just build a custom set" but that does NOT answer the "can a given Rule be in more than one BuiltInRuleSet? And what happens if it does? Etc.

HTH.

Thanks.

-- Mark Kamoski

...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 046fd91e-d711-3919-209b-800512e7f25a
* Version Independent ID: ea6dbd7c-cb69-38ad-e9d7-f0a56f6b5793
* Content: [Code analysis rule set reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/rule-set-reference?view=vs-2017#feedback)
* Content Source: [docs/code-quality/rule-set-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/rule-set-reference.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mkamoski Thank you for the thoughtful feedback! I'll add this to the backlog.
