### ISSUE TITLE
Nonsensical sentence regarding parallel builds and threads section.

### ISSUE THREAD

**Issue by jwdonahue** [MicrosoftDocs/visualstudio-docs#2845]
"Project systems can run builds asynchronously, but such systems must not call build functions from within call backs is provided to the build manager"

"backs is provided" seems to indicate either a typo or franken-sentence.  Either way, it should fixed. Perhaps it should just be:

Project systems can run builds asynchronously, but such systems must not call build functions from within call-backs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8ec22e2-c48a-30fa-c2aa-da4d5c15d63a
* Version Independent ID: 425b0040-c15e-5d85-bfe7-8e646530fa70
* Content: [Starting a Build from within the IDE - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/starting-a-build-from-within-the-ide?view=vs-2017#feedback)
* Content Source: [docs/msbuild/starting-a-build-from-within-the-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/starting-a-build-from-within-the-ide.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@jwdonahue That sounds correct. I'll make the change. Thanks!
