### ISSUE TITLE
Djangoweb

### ISSUE THREAD

**Issue by jawineh** [MicrosoftDocs/visualstudio-docs#2847]
Build of DjangoWeb failed due to "ModuleNotFoundError: No module named 'django.contrib.admindocsdjango'". Any ideas?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e07a-6d43-8800-fd06-be7f8ad21d20
* Version Independent ID: e6b188d8-adc0-cb16-cffa-63bfe2d3ecd4
* Content: [Learn Django tutorial in Visual Studio, step 5, authentication](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-05-django-authentication?view=vs-2017)
* Content Source: [docs/python/learn-django-in-visual-studio-step-05-django-authentication.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-05-django-authentication.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by Anapo14** [comment]
Hi! Can you confirm that  `Django project's settings.py file, navigate to the INSTALLED_APPS collection and add 'django.contrib.admindocs'.`?

**Comment by jawineh** [comment]
Don't quite remember. You may ignore the thread. Thanks.On Jun 5, 2019 5:02 PM, Tyreke White <notifications@github.com> wrote:Hi! Can you confirm that  Django project's settings.py file, navigate to the INSTALLED_APPS collection and add 'django.contrib.admindocs'.?

**Comment by JoshuaPartlow** [comment]
Feel free to reopen if you're able to duplicate the issue again. Thanks!
