### ISSUE TITLE
Should mention adding references too

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/visualstudio-docs#2848]
This feature can also add in a reference to the project in some situations. One such example is a reference to another project in the same solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e4d9b29-d1e3-1ef9-7169-28c098c56fac
* Version Independent ID: 103bb41e-4db7-dc1f-84f0-560da4a53d0b
* Content: [Generate usings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-usings?view=vs-2017)
* Content Source: [docs/ide/reference/generate-usings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-usings.md)
* Product: **visual-studio-windows**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kendrahavens**

**Comment by gewarren** [comment]
@henke37 Thanks, we will get this added.

**Comment by kendrahavens** [comment]
Fixed in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6081
