### ISSUE TITLE
Installer not in Start menu

### ISSUE THREAD

**Issue by cdonner** [MicrosoftDocs/visualstudio-docs#2849]
On a freshly installed machine with Visual Studio 2017, Visual Studio Installer is not an entry in my Start menu. I had to go find it at "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d0cb94-2886-79ce-39dd-0336282369b9
* Version Independent ID: e8bcc58e-98af-e3ad-2629-0b4515047d0b
* Content: [Modify Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2017#feedback)
* Content Source: [docs/install/modify-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/modify-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@cdonner I'm not sure why the Visual Studio Installer didn't appear in your Start menu. That should be the exception, not the rule. But, we do have a Note in Step 1 of the [Modify workloads](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2017#modify-workloads) section that says the following: 

"Alternatively, you can find the Visual Studio Installer in the following location: `C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe`"
