### ISSUE TITLE
redirect docs to legal owner geneva adams

### ISSUE THREAD

**Issue by adamskahlil39** [MicrosoftDocs/visualstudio-docs#2850]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c9101a1-5ee1-ab69-3182-0e7d6e1ea805
* Version Independent ID: 468c1fb7-f5f4-ccd8-682e-7092362e8167
* Content: [Access is denied](https://docs.microsoft.com/en-us/scripting/javascript/misc/access-is-denied)
* Content Source: [scripting-docs/javascript/misc/access-is-denied.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/scripting-docs/javascript/misc/access-is-denied.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@adamskahlil39 Do you have a link?

**Comment by gewarren** [comment]
@Mikejo5000 This is the page in reference, but I'm not sure what the ask is.

https://docs.microsoft.com/en-us/scripting/javascript/misc/access-is-denied

**Comment by Mikejo5000** [comment]
@gewarren I think the ask is to redirect this page to a page written by Geneva Adams. I'd like to see a link to the Geneva Adams page.

**Comment by Mikejo5000** [comment]
Need more info

**Comment by lurch** [comment]
This appears to be an issue from a spam github account :confused:
