### ISSUE TITLE
Is the Class Designer not available in .NET Core?

### ISSUE THREAD

**Issue by rlundy** [MicrosoftDocs/visualstudio-docs#2853]
If it *is* available, it would be great to have some documentation about how to find it, because Add New Item doesn't show it in a .NET Core MVC project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8eb126-b9c4-b81f-ee87-97ba405c0c25
* Version Independent ID: efdcd83c-0280-dbeb-97de-b4da4895c5bc
* Content: [How to: Add Class Diagrams to Projects (Class Designer) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/class-designer/how-to-add-class-diagrams-to-projects?view=vs-2017)
* Content Source: [docs/ide/class-designer/how-to-add-class-diagrams-to-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/class-designer/how-to-add-class-diagrams-to-projects.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@rlundy I contacted the engineering team and the answer is that Class Designer is *not* currently supported in .NET Core. You may get some stuff to work today but not in a supported state.

**Comment by weitzhandler** [comment]
@gewarren, shame but thanks for your input!

**Comment by weitzhandler** [comment]
>I contacted the engineering team and the answer is that Class Designer is _not_ currently supported in .NET Core.

This issue is tracked [here](https://developercommunity.visualstudio.com/content/problem/33831/class-diagram-not-available-in-aspnet-core-project.html).

>You may get some stuff to work today but not in a supported state.

To achieve this, edit a text or XML file with the _.cd_ extension, and replace its content with:

```xml
<?xml version="1.0" encoding="utf-8"?> 
<ClassDiagram MajorVersion="1" MinorVersion="1">   
  <Font Name="Segoe UI" Size="9" /> 
</ClassDiagram>
```

[Credit](https://stackoverflow.com/questions/47967459/how-to-generate-class-diagram-from-asp-net-core-1-1-project)

**Comment by weitzhandler** [comment]
@gewarren Is this verdict gonna change?
