### ISSUE TITLE
Clarify future Visual Studio version

### ISSUE THREAD

**Issue by jawn** [MicrosoftDocs/visualstudio-docs#2854]
"One or more of your installed extensions will not be compatible with a future Visual Studio update"

From this I understand only extensions using AsyncPackage will be supported at some point.

Can this document clarify when that will happen? Is this something in the Visual Studio 2019 timeline (minor version updates) or something that will only be enforced starting with the next major version (2020?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47d448c4-f5a5-626f-a127-8c72c378d20f
* Version Independent ID: 389e04ed-15de-4882-6cb0-010218767b54
* Content: [Synchronously autoloaded extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/synchronously-autoloaded-extensions?view=vs-2017)
* Content Source: [docs/extensibility/synchronously-autoloaded-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/synchronously-autoloaded-extensions.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@madskristensen Can you answer this?

**Comment by akeeton** [comment]
[Version 16.1 Preview 1][1] disables synchronous extensions:

> * Disabled synchronous auto-loading of extensions

> * Extensions that registers themselves to be auto-loaded will no longer be loaded, unless they are implementing AsyncPackage and enables background load. View our [blog post on improving the responsiveness of critical scenarios by updating auto load behavior for extensions][2] to read more about this change.

  [1]: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.1_Preview1
  [2]: https://devblogs.microsoft.com/visualstudio/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/

**Comment by Daedalus72** [comment]
@akeeton I don't think so, my obsolete extensions are still running with 16.1.2.

**Comment by spottedmahn** [comment]
FYI, I'm on 16.1 preview 3 and I'm seeing https://github.com/tafuji/Pcl-To-NetStandard as disabled:

![image](https://user-images.githubusercontent.com/14079228/57645640-ba1f5e80-758c-11e9-9e7d-08816dde47dd.png)

**Comment by priyasgs** [comment]
https://devblogs.microsoft.com/visualstudio/new-features-for-extension-authors-in-visual-studio-2019-version-16-1/ says:
18 months ago, we sent an email to extension partners announcing the deprecation of synchronous auto-loading of extension packages. A year ago, we followed up with a blog post with more details that outlined that synchronously auto-loaded package would be unsupported in a future version of Visual Studio. **That version is 16.1.**

We are seeing the message changing with the different versions of Visual Studio 2019:
16.0
One or more of your installed extensions will not be compatible with a future Visual Studio update.

16.1 Preview 2
Visual Studio did not load one or more extensions that were using unsupported APIs.

16.1
Visual Studio did not load one or more extensions that were using deprecated APIs.
with an option to "**Allow synchronous autoload**"

16.2 Preview 1
Visual Studio did not load one or more extensions that were using deprecated APIs.

The extensions though don't seem to be disabled/unloaded in any of these versions. Also, there seems to be an option to allow synchronous autoload of extensions. 
![Extensions](https://user-images.githubusercontent.com/45686136/58470830-2939ad00-8160-11e9-8195-c9d3d39829d6.png)

Which is the future update of Visual Studio 2019 when extensions that autoload synchronously will stop working?

**Comment by priyasgs** [comment]
Seems like synchronous autoload is not going away: https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/

**Comment by madskristensen** [comment]
It's not going away, but it is disabled by default

**Comment by yannduran** [comment]
This is how all new features/behavior should be implemented, enabled by default, but able to be switched off if the user decides that's how **they** want it.

**Comment by mdunka** [comment]
With update to v. 16.2.5, I once again got a warning about one of my (older) extensions being disabled. Although the option to allow synchronous autoload of extensions was checked, (see Tools / Options / Environment / Extensions), the it is also grayed now. 
As a result I added the group policy mentioned above to the registry, restarted VStudio and the warning changed to the previous simple notification about one of my extensions using synchronous autoload.

**Comment by PoulChapman** [comment]
I've updated the page for the current behavior in version 16.4. 

@mdunka -- that issue looks like it may require engineering investigation. (note to @madskristensen ) Can you open an issue on Developer Community for this? Doing so gives us setup and other logs that helps diagnose the issues. From within Visual Studio, go to Help > Send Feedback > Report a Problem

#please-close
