### ISSUE TITLE
"managed project sample" link invalid

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/visualstudio-docs#2856]
The link to the "managed project sample" is no longer valid. Please provide the direct link or other instructions on localizing the displayed options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 675b3475-6f70-41ae-dd68-6de1ad7532c0
* Version Independent ID: 640dc5b6-f567-2982-b41d-6947e4f7ba51
* Content: [Options and Options Pages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/options-and-options-pages?view=vs-2017#feedback)
* Content Source: [docs/extensibility/internals/options-and-options-pages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/options-and-options-pages.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
Yes the link target is bad, thanks for letting us know.

Could this be the file that contains the mentioned resources? https://github.com/Microsoft/VSSDK-Extensibility-Samples/blob/master/ArchivedSamples/Options_Page/C%23/VsPackage.resx#L120

**Comment by mrlacey** [comment]
That file shows localized resources that are used for the name of the page, but not the entries within the Options Page.

That example does not localize the entries. See hardcoded values at 
https://github.com/Microsoft/VSSDK-Extensibility-Samples/blob/master/ArchivedSamples/Options_Page/C%23/OptionsPageGeneral.cs#L46

I'm looking to use `SRCategory, LocDisplayName, and SRDescription` but can't see how. I can only even ifind reference to `LocDisplayName` anywhere else in the docs.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

**Comment by mrlacey** [comment]
> Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

Sad to hear that localization is a low priority.

Are the extensibility changes you refer to with regard to changes relating to a more distributed model regarding the VS instances and where code and extensions are located? If so then my understanding is that such a change will be a slow (possibly multi-year transition) What can we expect in terms of documentation updates during this time? What will get changed/fixed during that time? So we can know what to expect with any other issues we might raise in the future or have raised previously.

If you intend to revisit this at some point in the future, how are you tracking such issues that need revisiting? Presumably you're not planning on going through all closed issues. Do you have a tag or external list that you're using? If a tag then we can monitor that too. If an external/separate list, why that and not something in GitHub where changes/progress/accountability can be monitored by people without access to your private list?


"We're closing this issue but may revisit it in the future" [paraphrase] is code for 'we're never going to do this.' - Convince me otherwise.
