### ISSUE TITLE
Adding RadioButton

### ISSUE THREAD

**Issue by appawin** [MicrosoftDocs/visualstudio-docs#2858]
When adding a RadioButton control , the TextBlock control  will be removed. Did you ever test the description you gave us? One solution could be to first add a Grid container and then add the controls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329e32a3-766c-1739-022b-5d1a8bc6f4aa
* Version Independent ID: d74a678c-d9b5-90c4-cd63-8451fefaa887
* Content: [Tutorial: Hello World app with Windows Presentation Foundation (WPF) in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2017#feedback)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@appawin Thanks for letting us know; we'll review this documentation and get it updated appropriately.

**Comment by DickBaker** [comment]
having shown code for HelloButton
IsChecked="True"
the immediately following screenshot still shows both buttons unchecked. doh!
