### ISSUE TITLE
Beware of example when using async-await

### ISSUE THREAD

**Issue by Laniusexcubitor** [MicrosoftDocs/visualstudio-docs#2859]
In the example `CompilerServices.CompilerGeneratedAttribute` is excluded from code coverage. If you exclude this attribute all your async await code will be excluded. When using async-await the code is translated by the jitter and marked with this attribute.
Truly generated code (code not written by you) should have `Compiler.GeneratedCodeAttribute`, which is also included in the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dc6fcf-df9f-9d2a-5c6e-8da0f6925afc
* Version Independent ID: d0bf2cae-9b59-d537-7acb-7af5f560d8c1
* Content: [Customizing Code Coverage Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2017#feedback)
* Content Source: [docs/test/customizing-code-coverage-analysis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/customizing-code-coverage-analysis.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by patricksadowski** [comment]
Excluding the `CompilerGeneratedAttribute` also excludes `yield return` implementations and auto-implemented properties and maybe more... t`hese
