### ISSUE TITLE
What's this about some file named SimpleProjectPackageGuids.cs?

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/visualstudio-docs#286]
Your document is incomplete and therefore confusing. In the section on this page titled, "Creating a Basic Project Factory", in sub-section "To create a basic project factory" the first item reads, "1. Open SimpleProjectPackageGuids.cs". Huh? Where in heck is that? I tried searching through the whole solution; hate to break it to ya but it doesn't exist. And since this is the first time its mentioned I have no idea at all where I'm supposed to look. I don't even know if I'm supposed to create it. And if I am supposed to create it, where do I put it???

**Comment by Rod-in-NM** [comment]
Hi @gregvanl, thank you very much for looking into this. I've been busy with other urgent matters, so haven't had a chance to look back into this. Thought I'd check on it and see how things are coming along?

**Comment by gregvanl** [comment]
Hi @Rod-in-NM The VS Package template was changed to put the package GUID directly in the package class and avoid creating a separate *Guids.cs file. You can put the GUIDs mentioned in the walkthrough directly in the Package class. We'll update the walkthrough shortly to reflect this change. Thank you for calling this out.
