### ISSUE TITLE
first word of methods lower

### ISSUE THREAD

**Issue by bluekuen** [MicrosoftDocs/visualstudio-docs#2860]
Hello,

i want a rule to make the first word  my method/function names in lower, for example:

public Color getCarColor(){ return car.Color; }

I have this block of code:

#method names first word lower
dotnet_naming_rule.functions_should_be_camel_case.severity = warning
dotnet_naming_rule.functions_should_be_camel_case.symbols = functions
dotnet_naming_rule.functions_should_be_camel_case.style = function_style

dotnet_naming_symbols.functions.applicable_kinds = method
dotnet_naming_symbols.functions.required_modifiers = *
dotnet_naming_symbols.functions.applicable_accessibilites = *

dotnet_naming_style.function_style.capitalization = camel_case

But it's not working. 

I searched the docs: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference but could only find these capitalization styles:

The allowable values for this property are:

    pascal_case
    camel_case
    first_word_upper
    all_upper
    all_lower

Is it even possible to make the first word of my function lower  in EditorConfig file ?

**Comment by gewarren** [comment]
@bluekuen I think this should work by specifying camel_case. Did you try removing the `required_modifiers` specification from your rule? [This](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2017#symbol-modifiers) seems to imply that if you want the naming rule to apply to all modifiers, you should just omit it.

**Comment by bluekuen** [comment]
@gewarren thank you, that did the trick. It's working now. I think someone should mention it anywhere.

**Comment by gewarren** [comment]
@bluekuen Thanks, will do.
