### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/visualstudio-docs#2868]
This article could use some information on how the indentation in the &lt;Code&gt;&lt;![CDATA[]]&gt; section affects the indentation of the inserted snippet. If I want to insert three lines all at the same level of indentaion as the first line, how would I do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c7c36c-84d9-9237-3d78-689e76d080f9
* Version Independent ID: 6584735a-e8db-429d-5427-687fc709e6f8
* Content: [Walkthrough: Create a code snippet - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2017)
* Content Source: [docs/ide/walkthrough-creating-a-code-snippet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-creating-a-code-snippet.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@martingbrown I'm in the process of updating the documentation. The answer is that you can't predict or control how the inserted code will be formatted. When it's inserted, the language service for that code language automatically formats/indents the code.
