### ISSUE TITLE
Missing documentation for some vstest.console command line options

### ISSUE THREAD

**Issue by romanliv** [MicrosoftDocs/visualstudio-docs#2869]
E.g. ListFullyQualifiedTests, ListTestsTargetPath, see the discussion about these undocumented arguments here: https://github.com/Microsoft/vstest/issues/1732

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27af73d-196c-4653-aa07-acf7e8b425e3
* Version Independent ID: b8957d80-ffa0-1c42-d3f0-6e4d00bf7a1e
* Content: [VSTest.Console.exe command-line options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2017#feedback)
* Content Source: [docs/test/vstest-console-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/vstest-console-options.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Discussion of these two arguments is here: https://github.com/microsoft/vstest/issues/1732#issuecomment-416519608. @singhsarab Can you help out with documenting these options?

**Comment by L4ZZA** [comment]
What should /TestAdapterPath point to? nobody ever says where the test adapter are located, especially the ones that come with Visual Studio 2019 16.5.0 (i.e Boost Tests adapter, Google Tests adapter)

similar: 
- https://github.com/microsoft/vstest/issues/2195 
- https://github.com/microsoft/vstest/issues/1732

**Comment by EmpeRoar** [comment]
/Logger:trx[;LogFileName=<Defaults to unique file name>]
is actually
/Logger:"trx;LogFileName=filename.test.trx"

**Comment by L4ZZA** [comment]
Thanks for the note @EmpeRoar 
I wish that was the problem ;)

**Comment by dondrakon** [comment]
Could anyone explain to me what does this parameter and describe expected file format for the parameter?

> 

/ListTests:[file name] | Lists discovered tests from the given test container.
-- | --
