### ISSUE TITLE
Beautifully written - thanks!

### ISSUE THREAD

**Issue by sergeimgithub** [MicrosoftDocs/visualstudio-docs#2872]
Beautifully written - thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b79a889-79f3-3e2b-41b0-4d3b33783cda
* Version Independent ID: b4fcb3b9-4fac-79e1-95bd-34247324ae5d
* Content: [Design-Time Code Generation by using T4 Text Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/design-time-code-generation-by-using-t4-text-templates?view=vs-2017#feedback)
* Content Source: [docs/modeling/design-time-code-generation-by-using-t4-text-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/design-time-code-generation-by-using-t4-text-templates.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@sergeimgithub Thanks very much!
