### ISSUE TITLE
Not which dotnet.exe

### ISSUE THREAD

**Issue by hightech2** [MicrosoftDocs/visualstudio-docs#2875]
It says that I should attach to "dotnet.exe" for ASP.NET Core. But I have 5 processes with that name. Somehow describe how I could find out which process Id to attach. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7e8ce6c-965b-dbd7-97c8-94fd1558a487
* Version Independent ID: 6f1491a1-37c8-4515-4050-2b651b8e419d
* Content: [Find the running ASP.NET process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-find-the-name-of-the-aspnet-process?view=vs-2017#feedback)
* Content Source: [docs/debugger/how-to-find-the-name-of-the-aspnet-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-find-the-name-of-the-aspnet-process.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
It's been a while since I checked this for dotnet.exe. Often, the Title field in the process table gives a clue what process ID to attach to. Do any of the Title fields give you more information?
