### ISSUE TITLE
Incorrect link?

### ISSUE THREAD

**Issue by user2150** [MicrosoftDocs/visualstudio-docs#2883]
Cannot open the link "Why does Visual Studio require debugger symbol files to exactly match the binary files that they were built with?"
(Oops! That page can’t be found.
This page has been disabled.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce80d99-822d-3e3a-4c7f-6ec593029cef
* Version Independent ID: 61420028-368e-e122-1490-003b9340cb39
* Content: [Set symbol (.pdb) and source files in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2017#feedback)
* Content Source: [docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Looks like its been fixed.
