### ISSUE TITLE
hezhijun80

### ISSUE THREAD

**Issue by hezhijun80** [MicrosoftDocs/visualstudio-docs#2884]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-windows**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by gewarren** [comment]
@hezhijun80 What feedback were you trying to leave? There's no info in this issue other than the doc you're referring to.

**Comment by aronwarner** [comment]
There a many features in visual studio you have to understand which you want to tell people. I want to say if you faced any issue regarding <a href="https://www.canonsupportnumber.org/connect-canon-mg2922-printer-to-wifi/">canon pixma mg2922</a> then you can contact them directly.
