### ISSUE TITLE
"This site uses cookies ..." cannot be removed on Chrome on Android

### ISSUE THREAD

**Issue by bersbersbers** [MicrosoftDocs/visualstudio-docs#2885]
Visit https://code.visualstudio.com/docs on Chrome on Android - notice the top banner saying "This site uses cookies for analytics, personalized content and ads. By continuing to browse this site, you agree to this use. Learn more."

This banner cannot be removed and - unlike on Chrome on Windows 10 - does not disappear after using the site, for example, reloading or navigating.

Chrome 72.0.3626.121 on OnePlus 3T with Android 8.0.0, same on Huawei Mate 10 Pro with Android 9.

**Comment by gregvanl** [comment]
Hi @bersbersbers This repository handles Visual Studio documentation hosted on docs.microsoft.com. For Visual Studio Code website (code.visualstudio.com) issues, please go to https://github.com/Microsoft/vscode-docs.

**Comment by bersbersbers** [comment]
Oh yes, sorry!

**Comment by gregvanl** [comment]
No worries, I would have moved it but the GitHub move issue feature doesn't seem to be enabled for visualstudio-docs.
