### ISSUE TITLE
Report a Problem on Visual Studio setup

### ISSUE THREAD

**Issue by bobsort** [MicrosoftDocs/visualstudio-docs#2887]
How do you report a problem when visual studio fail to install or fail to open or in general if Report A Problem menu option integrated in Visual studio cannot be reached? 

As Far as I know a bug or problem is not a suggestion which I think visual studio developers also think same as they immediately click close on suggestions that report bugs! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#feedback)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by mariaghiondea** [comment]
Thank you for presenting this scenario to us! This is something that we are aware of and trying to find a way to mitigate, while still keeping the actionability of reports that we get with the Feedback Tool. 
As a workaround, you can also report a problem from the Visual Studio Installer. 
Please also see https://developercommunity.visualstudio.com/idea/398744/problems-cannot-be-reported-when-the-ide-doesnt-wo.html

As a side note, please log suggestions and problems about the product through Developer Community or the Feedback Tool. This is a medium that is used for problems about docs, and it's harder to track and make the connection.

Maria Ghiondea
Visual Studio Feedback System

**Comment by OscarLai** [comment]
> As a workaround, you can also report a problem from the Visual Studio Installer if that one is working.

Installer fail to install, how to report a problem?

**Comment by seaniyer** [comment]
I'd suggest first searching the Installation knowledgebase https://visualstudio.microsoft.com/vs/support/?c=Download+and+Installation.  If you are not able to find an existing solution, file a support request by following the options at the bottom of that page.
