### ISSUE TITLE
No mention of the default naming rules of visual studio

### ISSUE THREAD

**Issue by tonyhallett** [MicrosoftDocs/visualstudio-docs#2889]
The .Net language and formatting conventions provides the defaults for visual studio https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017 and this page does not.

From https://github.com/dotnet/roslyn/blob/5b05de681c46ae58c9d5e05b85bd736c4986cd3c/src/Workspaces/Core/Portable/NamingStyles/Serialization/NamingStylePreferences.cs#L107

Interface 
public, internal, private, protected, protected_internal
Prefix I and pascal case
Suggestion

Class, struct, interface, enum
public, internal, private, protected, protected_internal
Pascal case
Suggestion

Property, method, event
public, internal, private, protected, protected_internal
Pascal case
Suggestion

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b402d2e0-a53a-b61a-4da8-b5ee766d9301
* Version Independent ID: 612695df-5934-d967-d709-500ce02b1395
* Content: [.NET Naming Conventions For EditorConfig files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2017)
* Content Source: [docs/ide/editorconfig-naming-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-naming-conventions.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@tonyhallett Thanks for providing the defaults. If you'd like to take a stab at updating the document, there's an Edit button near the top right corner. Otherwise we will add this sooner or later.
