### ISSUE TITLE
Intellisense for external modules

### ISSUE THREAD

**Issue by ccc159** [MicrosoftDocs/visualstudio-docs#2898]
*By adding search paths, Visual Studio inspects the libraries in those locations and builds IntelliSense databases for them when needed (Visual Studio 2017 version 15.5 and earlier; constructing the database may take some time depending on the number of libraries).*

I wonder why from Visual Studio 2017 Intellisense is not supported anymore for external modules. Isn't this what an IDE essentially should do? I am currently suffering from this *feature* that I have to use VS2015.

Am I missing something to setup correctly to get intelisense back?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34b9c9a-6356-61fa-d895-97c459465e75
* Version Independent ID: c317a64e-06a3-1081-08db-3fb278ea7fbf
* Content: [How Python search paths are applied - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/search-paths?view=vs-2019#feedback)
* Content Source: [docs/python/search-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/search-paths.md)
* Product: **visual-studio-windows**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks @ccc159 for the question. Because you're asking about feature details, it's best to discuss the matter directly with the engineering team via https://github.com/Microsoft/ptvs/issues. In the meantime, I'm closing the present issue because doesn't pertain directly to the docs. Thanks,
