### ISSUE TITLE
ProjectFilesGenerator.ProjectFileGeneration name

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#2899]
Hi team, 
I'm copy/pasting this from here: https://github.com/MicrosoftDocs/visualstudio-docs.cs-cz/issues/6 
since the contributor is requesting additions to the original documentation.

>  @xmedeko commented: Please, document how `name` in the `ProjectFilesGenerator.ProjectFileGeneration` looks like - is that the project name, csproj file name or csproj full path?

-----
Podrobnosti dokumentu

⚠ Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.

    ID: 70a4fd25-8def-13c4-d35f-e81043b21e4d
    Version Independent ID: 55ceba14-64a8-20a9-73ce-e16f410f1936
    Content: Přizpůsobení souborů projektu vytvořených nástrojem VSTU - Visual Studio
    Content Source: docs/cross-platform/customize-project-files-created-by-vstu.md
    Product: visual-studio-windows
    GitHub Login: @conceptdev
    Microsoft Alias: crdun

**Comment by gewarren** [comment]
@conceptdev This is feedback about a Unity page: https://docs.microsoft.com/en-us/visualstudio/cross-platform/customize-project-files-created-by-vstu?view=vs-2017

**Comment by conceptdev** [comment]
I found some examples on the Unity support site: [script 1](https://answers.unity.com/questions/1123734/where-are-the-extensions-filter-of-visual-studio-t.html), [script 2](https://answers.unity.com/questions/867993/unityvs-keep-target-framework-in-rewritten-and-rel.html), [script 3](https://answers.unity.com/questions/999080/how-to-fix-losing-systemdatadll-in-project.html). From what I can tell, it is either the project file name (which is the same thing as csproj filename), possibly including the full path. One of the examples tests for `name.EndsWith("CSharp.Editor.csproj")` which is what leads me to believe this.

Hope that helps.

**Comment by xmedeko** [comment]
Well, I have found that source too, later. This issue is to have that in the official doc:  
https://docs.microsoft.com/en-us/visualstudio/cross-platform/customize-project-files-created-by-vstu?view=vs-2017

It's not only for me, it should be there for all users!

**Comment by conceptdev** [comment]
Thanks for the suggestion - I will pass that along to the team.
