### ISSUE TITLE
Update the example to .NET Core

### ISSUE THREAD

**Issue by SabotageAndi** [MicrosoftDocs/visualstudio-docs#2911]
The example is MSTest V1. Please update the example to use MSTest V2 on .NET Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107f3c03-dac2-0226-d5c1-f2f49daa413d
* Version Independent ID: aaf80310-28eb-462b-d4f1-6b97a8abe260
* Content: [Get started with unit testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2017#feedback)
* Content Source: [docs/test/getting-started-with-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/getting-started-with-unit-testing.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
This topic was updated in early April. Thanks for the feedback to help us improve!
