### ISSUE TITLE
fileSuffixToExtension rule not exists in schema

### ISSUE THREAD

**Issue by GKotfis** [MicrosoftDocs/visualstudio-docs#2925]
I don't know if it's a bug in documentation or  [vs-nesting](http://json.schemastore.org/vs-nesting) schema.
Schema define something like "filePartToExtension" instead. So which is correct? Or maybe these are two different option?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio](https://docs.microsoft.com/en-Us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2017#feedback)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by gewarren** [comment]
@AngelosP Could you answer this one Angelos?

**Comment by AngelosP** [comment]
The documentation is correct, we have to fix the schema. The schema was once correct, but the name in question was renamed and the schema was not updated. I'll reach out to the team maintaining the schema and get it fixed. Thank you!
