### ISSUE TITLE
When there are multiple update notifications

### ISSUE THREAD

**Issue by donaldnp** [MicrosoftDocs/visualstudio-docs#2926]
I have a couple of update notifications, and reading through this it's not clear to me if I have to install each update, or if I only need to install the latest update and it'll automatically install the older update too? e.g. when I click on the older notification, the installer shows only that the older update is available, rather than showing the latest update, so this is why I'm not sure if both have to be installed individually, or just click on the newest notification and install that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3386e-6b18-1cbd-9f1b-523b27b6521b
* Version Independent ID: 5ddf5e28-86d1-28b6-80ef-332bf93e17ac
* Content: [Update Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2017)
* Content Source: [docs/install/update-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@donaldnp I'm not sure what you are seeing; can you add a screenshot?

**Comment by donaldnp** [comment]
![2updates](https://user-images.githubusercontent.com/20635275/54885236-112e7e80-4ece-11e9-849c-cde3f6fb192d.jpg)
![ClickedOnNewerUpdate](https://user-images.githubusercontent.com/20635275/54885278-7bdfba00-4ece-11e9-8083-09b3cced774a.jpg)
![ClickedOnOlderUpdate](https://user-images.githubusercontent.com/20635275/54885281-80a46e00-4ece-11e9-8265-ee6742257cf6.jpg)

**Comment by TerryGLee** [comment]
@donaldnp Thanks for providing the screenshots. Now I fully understand the scenario that you described. The answer is that the updates for a particular edition of Visual Studio 2017 should be cumulative, so please choose to install the one with the most recent version number.

**Comment by donaldnp** [comment]
Ok, thanks. That's what I suspected, but when clicking on the older update and didn't actually display the newer update it threw me, and then the wording in the document is unclear about it. Would be helpful to add some words to the effect that you only need to install the latest update and it will automatically do the older ones too.

**Comment by donaldnp** [comment]
I'm also not sure why the installer doesn't just show the latest update

**Comment by TerryGLee** [comment]
@donaldnp Thanks for the suggestion; we'll look at adding that information, soon.

FYI: The Notifications hub shows a history of recent updates by design; sometimes, some folks might want to install an earlier version of a recent update (for example, if they are working on a particular extension that relies on a specific set of versioned components, or it they have an enterprise-level policy in place to stay on a specific recent update).

**Comment by TerryGLee** [comment]
@donaldnp We've added a note to the "notifications hub" section of the [Update Visual Studio](https://docs.microsoft.com/visualstudio/install/update-visual-studio?view=vs-2019#use-the-notifications-hub) page to address your feedback. Thanks again for taking the time to provide it. :)
