### ISSUE TITLE
VisibilityConstraints is not terminated correctly

### ISSUE THREAD

**Issue by yannduran** [MicrosoftDocs/visualstudio-docs#2927]
The final &lt;/VisibilityConstraint&gt; should be &lt;/VisibilityConstraints&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 943b50ae-a7ab-983f-66f2-b81ff08922b6
* Version Independent ID: 908cf5f3-6fcb-04cf-d53d-fa9bc96d3be2
* Content: [VisibilityConstraints Element - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/visibilityconstraints-element?view=vs-2017#feedback)
* Content Source: [docs/extensibility/visibilityconstraints-element.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/visibilityconstraints-element.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@yannduran Thanks for letting us know. You can also fix it yourself if you want, by clicking Edit at the top right.

**Comment by yannduran** [comment]
Oh, OK I didn't know that.

**Comment by gewarren** [comment]
@yannduran I'm going to reopen this so we can make sure it gets fixed.

**Comment by yannduran** [comment]
@gewarren Sorry about that.

I've fixed the mistake(s) & created a pull request, like I should have done in the first place. At least I know how to suggest fixes to the docs now :-)

**Comment by gewarren** [comment]
@yannduran Thank you!
