### ISSUE TITLE
ActiveEditorContentType:<contentType>

### ISSUE THREAD

**Issue by yannduran** [MicrosoftDocs/visualstudio-docs#2929]
No examples are given for values`&lt;contentType&gt;` can be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9786c88-8bd3-8d62-5132-743e44b41dda
* Version Independent ID: 0bd057a1-b51c-b617-ca99-3979b4729f26
* Content: [How to: Use Rule-based UI Context for Visual Studio Extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions?view=vs-2017)
* Content Source: [docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by Emdot** [comment]
From what I can tell, it *seems* that valid values are identifiers for text management packages.

To find those identifiers, open "%LocalAppData%\Microsoft\VisualStudio\*\Settings\CurrentSettings.vssettings" and "%ProgramFiles(x86)%\Microsoft Visual Studio\*\Community\Common7\IDE\Profiles\General.vssettings", search for `PackageName="Text Management Package"`, and get the RegisteredName values of those nodes. I'm not sure whether non-<ToolsOptionSubCategory> elements count.

On my machine the list is: "Environment_Expansions"?, "AllLanguages", "Basic", "C/C++", "CSS", "CSharp", "CoffeeScript", "FSharp", "HTML", "HTMLX", "JSON", "JavaScript", "LESS", "PlainText", "ResJSON Resources", "SCSS", "SQL Server Tools", "T-SQL90", "TypeScript", "XAML", "XOML", "Xml", and (maybe) "Environment_Expansions".

**Comment by Emdot** [comment]
Note: `AllLanguages` doesn't appear to work.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
