### ISSUE TITLE
Task List does not work in VS2017 Community 15.9.9

### ISSUE THREAD

**Issue by pierrebai** [MicrosoftDocs/visualstudio-docs#2931]
For C++ projects, the task list does no fill up from TODO comments in the code. I verified that the fature is enabled in the C++ Text Editor options &gt; View.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1261884-8284-53f9-a325-15061bf897f8
* Version Independent ID: 4520c20f-86f6-5066-298b-d3d428901f87
* Content: [Use the Task List - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2017#feedback)
* Content Source: [docs/ide/using-the-task-list.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-the-task-list.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@pierrebai A better way to report a product issue is by selecting [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017?view=vs-2017) from the menu in Visual Studio:

![image](https://user-images.githubusercontent.com/24882762/50103023-80b01600-01db-11e9-9d0a-313b701272ed.png)

When you do this, it logs the issue at [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) along with diagnostic information about your setup. Developer Community is where the product engineering team tracks and resopnds to customer issues, and other users can also upvote and leave comments.
