### ISSUE TITLE
Availablity of older bootstrappers

### ISSUE THREAD

**Issue by uecasm** [MicrosoftDocs/visualstudio-docs#2932]
> If you need to create a layout for an older version of Visual Studio 2017, go to https://my.visualstudio.com to download "fixed" versions of the Visual Studio 2017 bootstrappers.

Currently it appears that only "Visual Studio 2017 15.0" and "Visual Studio 2017 15.9" appear at my.visualstudio.com.  I am expecting to find bootstrappers for each individual minor point release, to enable rollback scenarios.

As it is, it seems like if you update a network layout to a newer version, then later discover a critical bug in that version which requires rollback to an older version of VS (until the bug can either be patched or workarounded), you are completely screwed unless you had a full backup of the multi-GB older layout.  There **must** be an easy way to request an older version than the latest one.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio](https://docs.microsoft.com/en-nz/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2017)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@uecasm Thanks for your feedback; I am investigating the issue that you've reported and will report back, soon.

**Comment by TerryGLee** [comment]
@uecasm Here is a link that should help unblock you: [Installing an Earlier Release of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/productinfo/installing-an-earlier-release-of-vs2017#installing-the-earlier-release). However, please note that we'll be taking this page down soon, as we recommend that everyone use the [latest and most secure version of Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2017), which as I write this, is 15.8.11.

**Comment by TerryGLee** [comment]
@uecasm I've closed this issue; however, you can still comment on it if you like, and we can reopen it if there are further aspects to address beyond what I previously provided.
