### ISSUE TITLE
Example???

### ISSUE THREAD

**Issue by dotfield** [MicrosoftDocs/visualstudio-docs#2934]
You have shown there is such a thing as a task that goes in BeforeClean / AfterClean and that you might wish to override CleanDependsOn

You haven't given a proper example.

And I want an example that deletes something not just prints a message

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868d865b-89d9-ec87-d569-862d168dc6ca
* Version Independent ID: a95f34e2-8f4b-4a4b-cb7e-075e4ceebd69
* Content: [Extend the build process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2017)
* Content Source: [docs/msbuild/how-to-extend-the-visual-studio-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-extend-the-visual-studio-build-process.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, do you have any thoughts on a sample update here?

**Comment by sanepete** [comment]
This is a very good comment.
A++, would read this commenters comments again.

**Comment by ghogen** [comment]
Added example, should be published soon.
