### ISSUE TITLE
My VS 2017 does not have a Modules window

### ISSUE THREAD

**Issue by sfilipi** [MicrosoftDocs/visualstudio-docs#2936]
I don't have a Modules window in the VS 2017. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7bd93e4-509f-6fb9-594e-820d62c03479
* Version Independent ID: 2453d9ef-4bb3-91bc-820f-cd59d589ca0f
* Content: [View DLLs and executables - Visual Studio Modules window](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-modules-window?view=vs-2017)
* Content Source: [docs/debugger/how-to-use-the-modules-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-use-the-modules-window.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@sfilipi It's is only available while you are in a debugging session. So, you could see it while paused at a breakpoint.

**Comment by sfilipi** [comment]
Thanks @Mikejo5000
