### ISSUE TITLE
Insufficient documentation for "Collect video using the Visual Studio Test task"

### ISSUE THREAD

**Issue by hassanuz** [MicrosoftDocs/visualstudio-docs#2937]
Documentation on setting [this ](https://docs.microsoft.com/en-us/azure/devops/test/collect-screenshots-and-video?view=azure-devops#collect-video-using-the-visual-studio-test-task)up with **runsettings** doesn't seem to exist at all (or if it does, can someone point me in the right direction?). 

Is there a template of a runsettings files that purely only enables screen capture? I've got it working with **tests**ettings, but that doesn't work with MStest, so the VSTest runner fails on Pipelines. 

Thanks

**Comment by gewarren** [comment]
@alexhomer1 Can you help out with this question at all?

https://docs.microsoft.com/en-us/azure/devops/test/collect-screenshots-and-video?view=azure-devops#collect-video-using-the-visual-studio-test-task

**Comment by alexhomer1** [comment]
Thank you for your feedback. I have passed this on to the product team for advice.

**Comment by PBoraMSFT** [comment]
@hassanuz - an example runsettings file is documented [here](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#example-runsettings-file)

@gewarren - this issue can be closed.
