### ISSUE TITLE
Any way to break on unstructured errors?

### ISSUE THREAD

**Issue by rocifier** [MicrosoftDocs/visualstudio-docs#2938]
We are trying to debug some legacy code written in VB6. It uses unstructured error handling "On Error Goto Error" etc. in VB6 debugger there was an option under Error Trapping called "break on all errors". The equivalent seems to be "break on all exceptions" in the .Net debugger. Is there any way to break for "On Error" clauses in VB.NET?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45057ee-e31b-321c-93e6-3e4516cee1d3
* Version Independent ID: 7938c681-a902-c970-5b2b-924ca70d0ed1
* Content: [Manage exceptions with the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2017)
* Content Source: [docs/debugger/managing-exceptions-with-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/managing-exceptions-with-the-debugger.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rocifier If "break on all exceptions" doesn't work, you could add the "debugger;" statement in OnError code. That will launch the debugger.
You could switch to the older debugger (VS 2010) using Tools > Options > Debugging > Use Managed Compatibility Mode, but this will not change the available options in any of the Windows, so likely won't help you here.

**Comment by rocifier** [comment]
@Mikejo5000 thanks for your reply. Just confirming that "break on all exceptions" doesn't work. If I am to add debugger; statements manually to the code, it is easier to just add breakpoints. The reason I am trying to get the legacy break on all errors working is so I don't have to modify the code (we aren't scheduled for error refactoring), and so that I don't have to manually go through all the logic and put breakpoints. I am just interested in the flow when and where errors are being handled.

Is anyone able to confirm whether "Use Managed Compatibility Mode" turns on "break on all errors" when the checkbox is ticked for "break on all exceptions"? I doubt that it is, because you can also ignore certain exceptions, the check box for full exceptions seems to just simply check all the sub-exceptions as its behavior. Are there any other options?

**Comment by Mikejo5000** [comment]
@andysterland @leslierichardson95 Is there any way to break on VB6 On Error code?

**Comment by Mikejo5000** [comment]
What version of VS are you using? If VS 2019, I believe function breakpoints are now supported for additional languages. You could test it; Debug > New Breakpoint > Function breakpoint. Type OnError as the function name. I don't see VB in the language list :-(, but you could try all languages.

**Comment by rocifier** [comment]
That's a creative thought to try and use function breakpoints. I am on VS2017 but if there was a solution for my problem in VS2019 it would be significant motivation to use the preview release in our production environment. 

Unfortunately "On Error" (it has a space in it) is not a function, it is a statement in the VB language. This is suggested in the documentation page https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/on-error-statement which stated in a note:

> An error-handling routine is not a Sub procedure or a Function procedure. It is a section of code marked by a line label or a line number.

**Comment by rocifier** [comment]
Hi, I still haven't received any answer for this, and it is still an issue so I am asking for significant time to be scheduled for refactoring our code base. If there is any knowledge of how to do this, please update me ASAP as unstructured errors is still a currently supported feature of .NET.

**Comment by Mikejo5000** [comment]
@rocifier Hi, sorry for the delayed response. Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by rocifier** [comment]
Hi, I noticed that this was updated with P1 but then closed. What is the reasoning there? I use the Report a Problem tool on 17 April but from my knowledge that report hasn't been investigated yet. Is that a different team who takes those on board?

**Comment by Mikejo5000** [comment]
@rocifier I tagged it as P1 during a "tagging" pass due to page views, but this is actually not the only factor for assigning priority. In this case, this issue appears to be question around how to work around the current product feature set, so Report a Problem is where it ought to go rather than a doc issue. (If there is a workaround identified--or an undocumented feature--it would most likely make sense to doc it here, so please update this and re-open it if you do find out anything more about this.) If there's no workaround, we'd rather avoid just leaving this issue open indefinitely.
