### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by peteowen1** [MicrosoftDocs/visualstudio-docs#2939]
Bullet point 3 under Converting a folder of files to an R project should read:
In the Visual Studio Solution Explorer, right-click the project, select Add &gt; Exi(S)ting Item, and browse to the files you want to add. Those files appear in your project tree after selecting OK.

Otherwise very useful, thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2e46c-3c08-18f7-dc72-bf5b69ea667e
* Version Independent ID: 61e033e8-4d38-1b9e-c7d4-e7dde5b86fad
* Content: [R projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/r-projects-in-visual-studio?view=vs-2017#feedback)
* Content Source: [docs/rtvs/r-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/r-projects-in-visual-studio.md)
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by gewarren** [comment]
@peteowen1 Thanks for letting us know. If you want to help us out by fixing the typo, there's an Edit button near the top right of the window.

**Comment by peteowen1** [comment]
New to the whole Github contribution thing so cheers for explaining, can see now I can edit myself and create a pull request

**Comment by gewarren** [comment]
@peteowen1 Thanks for fixing the typo in #2942. One more tip for next time - if you comment "fixes #2939" in the commit message or in the PR description, when the PR is merged it automatically closes the referenced issue too. Pretty nifty.
