### ISSUE TITLE
/Blame option is unrecognized parameter

### ISSUE THREAD

**Issue by damon8or** [MicrosoftDocs/visualstudio-docs#2943]
I attempted to add the /Blame parameter to an Azure DevOps the vstest.console.exe doesn't recognize it as a parameter.  Perhaps the version in Azure DevOps doesn't support this option, but the documentation is no clear on that if so.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27af73d-196c-4653-aa07-acf7e8b425e3
* Version Independent ID: b8957d80-ffa0-1c42-d3f0-6e4d00bf7a1e
* Content: [VSTest.Console.exe command-line options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2017)
* Content Source: [docs/test/vstest-console-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/vstest-console-options.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Rod-in-NM** [comment]
Does -blame work?

**Comment by damon8or** [comment]
Not in Visual Studio 2015 tool chain.

Damon

**Comment by gewarren** [comment]
This documentation is for VS 2017/2019 so I'm not sure if /Blame was supported for VS 2015. @AbhitejJohn can you help?

**Comment by AbhitejJohn** [comment]
This would be better addressed by the test platform team. Tagging @cltshivash.

**Comment by WilliamAntonRohm** [comment]
@MicrosoftDocs/visual-studio-live-share -- please look into this aging issue.

**Comment by AbhitejJohn** [comment]
Searched around the test platform docs and found this: https://github.com/microsoft/vstest-docs/blob/master/RFCs/0024-Blame-Collector-Options.md. Hope that's useful. 
As for a support matrix, I can get in touch offline with the team.

**Comment by WilliamAntonRohm** [comment]
@damon8or -- Thanks for your question. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
