### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by danielricci** [MicrosoftDocs/visualstudio-docs#2945]
For more information about package manifests, see How to: Create a product manifest.

should read

For more information about **product** manifests, see How to: Create a product manifest.

**Comment by TerryGLee** [comment]
@danielricci Thanks for your feedback; please if you would, include the name of the page or its URL where you've noticed the text that must be changed?

**Comment by danielricci** [comment]
https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-a-product-manifest?view=vs-2017

![image](https://user-images.githubusercontent.com/615440/55099203-af207580-5095-11e9-8bcb-ada2f4ba9af6.png)

**Comment by gewarren** [comment]
There are actually two related typos in both https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-a-package-manifest?view=vs-2017 and https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-a-product-manifest?view=vs-2017, both in the same place. @Mikejo5000 fyi.

**Comment by Mikejo5000** [comment]
Fixing...

**Comment by danielricci** [comment]
Looks good, closing the issue
