### ISSUE TITLE
So it's not obvious?

### ISSUE THREAD

**Issue by swellhunter** [MicrosoftDocs/visualstudio-docs#2948]
How do we add flags for build? Force C, aggressive optimisation, and the like ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fd27543-2a22-9a63-eefd-4cf5f786191c
* Version Independent ID: b7aa9bfd-4e9a-42bf-9e20-44caf2141cd8
* Content: [How to: Create and edit configurations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-and-edit-configurations?view=vs-2017#feedback)
* Content Source: [docs/ide/how-to-create-and-edit-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-and-edit-configurations.md)
* Product: **visual-studio-windows**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by DevinJamesK** [comment]
Solution Explorer > Right Click Project Name (Under Solution Name) > Properties

**Comment by gewarren** [comment]
@swellhunter did @DevinJamesK answer your question?

**Comment by swellhunter** [comment]
@gewarren @DevinJamesK , well enough.  I am getting by.
Version 1.37.0-insider (user setup)

I don't have a solution, nor a Project Name.
 I have an open editor with a stand alone Python script and I have a host. 
So properties are global from File > Preferences > Settings ?
This is best done before debugging as the Extensions section is hidden then?

![screen1](https://user-images.githubusercontent.com/33498537/61010890-734abb00-a3bb-11e9-9edc-927292d67dca.png)

Yes, for key authentication I don't need to see the console, but prompt and banner server to remind me of the host identity.  

What was desirable was for the login terminal to be conditionally displayed for password logons, without regard to the state of this checkbox. 

For password authentication, there are 2-3 connections, and a wget (or similar) of updated server code.
It is now second nature to ensure focus on the terminal tab for each password entry but having focus return to the terminal prompt would be a nice to have.

**Comment by swellhunter** [comment]
(I am in fact well impressed with the drop down password prompt as currently implemented.)

**Comment by gewarren** [comment]
@swellhunter Ah, you are asking about Visual Studio Code, not Visual Studio. In that case, please look for and/or ask your question here: https://stackoverflow.com/questions/tagged/visual-studio-code?tab=Newest. The Visual Studio Code documentation is [here](https://code.visualstudio.com/docs).

**Comment by swellhunter** [comment]
@gewarren @DevinJamesK
A thousand apologies for the noise, I confused my threads. Yes my question was answered. Thank you.
