### ISSUE TITLE
Ability to automatically associate .natjmc / .natstepfiler files with a solution or project?

### ISSUE THREAD

**Issue by KorkyPlunger** [MicrosoftDocs/visualstudio-docs#2949]
With .natvis debugger visualizers, it is possible for us to commit our default visualizers to our source control system, add them to our visual studio projects, and then Visual Studio will automatically recognize them. The user does not need to do any work except check out, build, and run.

Is there similar support for .natjmc and .natstepfiler files? I did not see that option mentioned in this document.

Forcing users to manually copy them to "%USERPROFILE%\My Documents\&lt;Visual Studio version&gt;\Visualizers" is cumbersome and makes it difficult to deploy organization-wide default filters. So we would really love the ability to just include them in our projects, like we can with .natvis files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c93cd83-ee45-dbd4-e3b2-48c731e46419
* Version Independent ID: e8920cca-b8db-369a-e249-938b995b5f14
* Content: [Debug user code with Just My Code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2017#BKMK_CPP_Customize_call_stack_behavior)
* Content Source: [docs/debugger/just-my-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/just-my-code.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@KorkyPlunger Hi, I'm asking whether this is currently supported. If I find out that it's supported, I'll update this issue and the doc, too. I'm guessing it would be a new feature, so I suggest that you please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2017) page.

**Comment by Mikejo5000** [comment]
@KorkyPlunger Confirmed - no plans to add this any time soon. Please use Suggest a feature.
