### ISSUE TITLE
Visual Studio 2019 Start Page

### ISSUE THREAD

**Issue by kmarois** [MicrosoftDocs/visualstudio-docs#2950]
In the page "What's new in Visual Studio 2019", there is a section titled "New start window".

In previous version of Visual Studio it was possible to create customized start pages. Is this feature still available? If so, what resources are available to create one?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6ebefd-fcc0-7e65-6450-c5908dbb61f8
* Version Independent ID: 83656699-f59b-5c22-94ad-bb2c8d58b2ae
* Content: [What's new in Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2019?view=vs-2019)
* Content Source: [docs/ide/whats-new-visual-studio-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/whats-new-visual-studio-2019.md)
* Product: **visual-studio-dev16**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gewarren** [comment]
@kmarois The Start page does not exist in Visual Studio 2019, so it cannot be customized. Are you asking whether the start window can be customized? If so, I think the answer to that is currently "no".

**Comment by DL444** [comment]
Actually the Start Page command in the main toolbar, which has always been hidden by default, is still working. You can also use toolbar customize settings to place it wherever you want. 
Not sure if they will remove this altogether in the future, and this won't make it show up automatically when you start. But for now it is still there.

**Comment by gewarren** [comment]
@DL444 You are not incorrect :) However, the Start Page command may be removed at any point in the future so you shouldn't count on it always being there. If you feel strongly about keeping the Start Page, please upvote [this suggestion on Developer Community](https://developercommunity.visualstudio.com/idea/434456/start-page-please-give-it-back.html).
