### ISSUE TITLE
VS Fills Out the Port Number

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/visualstudio-docs#2951]
Hello 👋 - Visual Studio will fill out the port number so the user doesn't need to enter that (unless they use a custom port)

&gt;Set the Qualifier field to &lt;remote computer name&gt;:port.

IMHO should be:

&gt;Set the Qualifier field to &lt;remote computer name&gt;.

While it's not a big deal, it makes it cleaner and easier to follow IMHO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4215ecb-721f-9b0b-66ae-042ffd7c9842
* Version Independent ID: 0d58ec46-8b09-f184-24f3-ac53ac0d1b50
* Content: [Remote Debug ASP.NET Core on a Remote IIS Computer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-computer?view=vs-2017)
* Content Source: [docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@spottedmahn Thanks for the info. Last I tested these features, I didn't see that behavior, so including information about the port was very important. I will need to retest the behavior. You are on VS 2019?

**Comment by spottedmahn** [comment]
>I didn't see that behavior

Weird.  2017 and 2019.  I enter the computer name and **hit enter** and the port number automatically fills out.

**Comment by Mikejo5000** [comment]
Hmm. It seems likely that when VS finds the machine based on computer name, it auto-fills the port. Due I think to running the server on VMs and/or Azure, and/or due to network restrictions here, I often need to use the IP address instead, and so you don't the port. I can make some edits here.

**Comment by spottedmahn** [comment]
Hi @Mikejo5000 - I just tried in VS 2017 w/ a computer name and IP address and both times it added the port number after hitting enter.  Just an FYI 😊

**Comment by Mikejo5000** [comment]
@spottedmahn OK, thanks, again. Could be this improvement was made in one of the VS 2017 updates. I'll update the docs.
