### ISSUE TITLE
Which Exe to Attach to?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/visualstudio-docs#2952]
When I've been remote debugging ASP.NET Core apps I've been attaching to my exe i.e. `MyASPApp.exe` in this example but the demo attaches to `dotnet.exe`.

Is there pros/cons to either approach?  Same difference?

Attaching to my exe feels safer compared to attaching to `dotnet.exe`.  Seems like I could effect other apps, no?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4215ecb-721f-9b0b-66ae-042ffd7c9842
* Version Independent ID: 0d58ec46-8b09-f184-24f3-ac53ac0d1b50
* Content: [Remote Debug ASP.NET Core on a Remote IIS Computer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-computer?view=vs-2017)
* Content Source: [docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@spottedmahn That's very interesting. I don't think that it was possible to connect to MyASP.exe in previous versions of the remote debugger and/or VS. If attaching to MyASP.exe gets you the debugger features you expect, yes, that sounds safer. I will need to test this before changing the doc, as that may not work in VS 2017. What version of VS are you running?

**Comment by spottedmahn** [comment]
Works in VS 2017 on a .NET Core 2.0 web app for me.

**Comment by Mikejo5000** [comment]
@spottedmahn I'm updating the doc, mentioning the method you described. I can't get a repro on a local IIS, so I will also leave in the dotnet.exe info for the time being until I have better info.

**Comment by spottedmahn** [comment]
Hi @Mikejo5000 - I think I figured it out today why I'm seeing the differences: **full** framework **vs** **core** framework...

When targeting the full framework the exe is the app name.  In core, I guess only a dll is produced and that DLL runs under `dotnet.exe`

Reference: [Attaching the debugger](https://github.com/dotnet/core-setup/issues/2007#issuecomment-370030584)
