### ISSUE TITLE
Class Structure with EditorConfig

### ISSUE THREAD

**Issue by bluekuen** [MicrosoftDocs/visualstudio-docs#2956]
Is it possible with editorconfig to mantain a custom hierarchy where variables and fields in a class should appear?

e.g. I want the private fields first, then Properties, then constructor etc.  like so:

public class Structure {
//first private fields
private int test;
//then Properties 
public string Test {get;set;}
//Constructor
public Structure(){}
//Methods
private int addTwoCents();

}

**Comment by gewarren** [comment]
@bluekuen I don't think that's currently possible. @kendrahavens for comment.

**Comment by kendrahavens** [comment]
@gewarren is correct. That option is not offered. You can open a request to add that formatting option to editorconfig in our open source repository: https://github.com/dotnet/roslyn/issues
