### ISSUE TITLE
[Fakes] Docs are old, samples are wrong.

### ISSUE THREAD

**Issue by mbickle** [MicrosoftDocs/visualstudio-docs#2958]
&lt;Types&gt; is not valid as part of the schema as far as I can see for the .fakes, so why is it shown here?
It shouldn't be so difficult to create fakes and have things be clean without warnings.  I can't for the life of me fake the System.Web.Mvc without letting it shim everything and then I have to "Remove" ALL the stuff I don't want.  I just want the Controller, but adding the specific namespace, typename, fullname and I can't get anything to work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99be7810-3759-ab36-bb72-cdcb74c5b272
* Version Independent ID: b0c72031-cbc4-1179-668d-43555f76755b
* Content: [Code generation, compilation, and naming conventions in Microsoft Fakes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/code-generation-compilation-and-naming-conventions-in-microsoft-fakes?view=vs-2017#feedback)
* Content Source: [docs/test/code-generation-compilation-and-naming-conventions-in-microsoft-fakes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/code-generation-compilation-and-naming-conventions-in-microsoft-fakes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by riverar** [comment]
For @mbickle and others that may look here:

Here's a working `.fake` you can use as a starting point. This will generate an _empty_ fake assembly, that is, an assembly with neither stubs or shims:
```xml
<Fakes xmlns="http://schemas.microsoft.com/fakes/2011/">
  <Assembly Name="MyAssembly"/>
  <StubGeneration>
    <Clear />
  </StubGeneration>
  <ShimGeneration>
    <Clear />
  </ShimGeneration>
</Fakes>
```

You can then utilize `<Add ...>` nodes in either section to cherry pick what you want stubbed/shimmed.

For example:
```xml
<Fakes xmlns="http://schemas.microsoft.com/fakes/2011/">
  <Assembly Name="MyAssembly"/>
  <StubGeneration>
    <Clear />
  </StubGeneration>
  <ShimGeneration>
    <Clear />
    <Add Namespace="MyAssembly.Services"/>
    <Add Namespace="MyAssembly.Helpers"/>
  </ShimGeneration>
</Fakes>
```

**Comment by Mikejo5000** [comment]
@kendrahavens Looks like I could just update the sample code with this code instead?

**Comment by RobLSDev** [comment]
I think .NET Standard support should now be listed as in preview as well.
