### ISSUE TITLE
FileSystem Deploy: targets after the whole process

### ISSUE THREAD

**Issue by ronkpunk** [MicrosoftDocs/visualstudio-docs#2959]
Is it possible to create a custom target "after" the all deployment process?
I mean also after the "publishing" process.

I've a project that I deploy on local folder and I want, after the whole deployment process, to:
- Zip all files in output folder into an archive
- Delete all files except for the Zip created
- commit & push Zip file to our git repository

I need to have different deployment profiles to deploy the solution with different config transformations, excluding specific folders/files and put output files in different folders

I'm playing with deployment targets but I can't find one that run after all

Thank you in advance
Stefano

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7acfded6-bb6d-cf61-0cf0-a4457bbff059
* Version Independent ID: c1974839-4571-e19c-e484-a98e4121e17c
* Content: [Deploy to a local folder - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-local-folder?view=vs-2017)
* Content Source: [docs/deployment/quickstart-deploy-to-local-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/quickstart-deploy-to-local-folder.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ronkpunk What version of VS are you using? There should be an option in the Advanced settings of the profile to Delete all other files in the Output folder. As far as zipping and pushing to GitHub, you might want to looking into Azure Pipelines (in latest versions of VS, you can see links to Continuous Delivery in the Publish dialog box. 

![image](https://user-images.githubusercontent.com/11948536/55247795-b6ff2780-5205-11e9-8228-4a118b8fd433.png)

Otherwise, you probably need some kind of script or 3rd party tool to do this.

**Comment by ronkpunk** [comment]
I'm using Visual Studio 2017 Community.
I'm working directly on pubxml file and, as a work-around, I've done all my tasks through the AfterTarget "GatherAllFilesToPublish". It's not the best solution because all published files remains in other directory while I'd prefer to use directly those files and this directory to create zip the published files and remove them from folder (just for tidy issue).

Thank you for help

**Comment by Mikejo5000** [comment]
@ronkpunk  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
