### ISSUE TITLE
Missing description of x86 flag names

### ISSUE THREAD

**Issue by bogiord** [MicrosoftDocs/visualstudio-docs#2960]
This is the content I'm referring to:

https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-3.0/kwydd1t7(v=vs.85)

I couldn't find it in the current version of the docs; it only seems to be available in older versions.

This is important content. The flag names displayed in the Registers Window are completely different from the ones used in Intel's documentation (why that is so is a product feedback issue I guess). Without these explanations, it's quite difficult to guess that `PL` means "Sign", for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9abd0c2-b3c4-d544-c330-2940a193b854
* Version Independent ID: 4099b7e4-a7ec-4be2-cdf3-0eeed59e7472
* Content: [View register values in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-registers-window?view=vs-2017)
* Content Source: [docs/debugger/how-to-use-the-registers-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-use-the-registers-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@bogiord My guess is that the topic was removed at some point because page views were very low. I will look into this a bit closer, and might then port the old table into the "About" topic here.

**Comment by bogiord** [comment]
@Mikejo5000 Thanks for looking into it. 

I must say that I'm quite worried by the fact that the page view count even features as a criterion in the decision to remove reference information from the documentation of an active product.

**Comment by Mikejo5000** [comment]
@bogiord The reason may well have been (what seemed to be at the time) a lot better reason than low PVs. Some topics do get PVs as low as 0 in a monthly period, which occasionally can make them a candidate for removal. I agree that reference info such as you see in this page should be retained though.

**Comment by StrongBishop** [comment]
Thanks @bogiord!  I was looking all over for that.  Good recommendation to put it back.  +1 @Mikejo5000.

**Comment by Mikejo5000** [comment]
Updating the doc
