### ISSUE TITLE
wintellectnow Benefit - not there

### ISSUE THREAD

**Issue by Boogaloos007** [MicrosoftDocs/visualstudio-docs#2961]
Hi Support, what happened to the wintellectnow benefit? I dont see it there anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63281b03-c455-5a80-3716-e374372330fe
* Version Independent ID: 05617725-bce1-fe54-7dda-d0767f9cc527
* Content: [Visual Studio Subscriptions Professional Development](https://docs.microsoft.com/en-us/visualstudio/subscriptions/professional-development)
* Content Source: [subscriptions/professional-development.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/professional-development.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@Boogaloos007 - Thanks for reaching out.  The WintellectNOW benefit is no longer offered in Visual Studio Dev Essentials.  If you have already activated your benefit, you should still be able to use it for the original term of the offer by visiting WintellectNOW directly.
