### ISSUE TITLE
Edit and continue debugging feature in c# code is not working when running via docker

### ISSUE THREAD

**Issue by SaidAlSouti** [MicrosoftDocs/visualstudio-docs#2962]
Edit and continue debugging feature is available in c# code such as controllers, when running app locally with IIS express, but it does not work the same with dockers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3adcabc-7e2b-da97-6899-35f1d97f1758
* Version Independent ID: 0684394a-7371-f3b5-d6aa-f236882db6f4
* Content: [Debugging apps in a local Docker container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/vs-azure-tools-docker-edit-and-refresh?view=vs-2017#feedback)
* Content Source: [docs/containers/vs-azure-tools-docker-edit-and-refresh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/vs-azure-tools-docker-edit-and-refresh.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by pratiksanglikar** [comment]
Edit and continue debugging feature in c# code only works for Windows containers at the moment. Please verify what type of container are you using.

**Comment by TerryGLee** [comment]
@SaidAlSouti We've not heard back from you, so we'll close this issue now. But as an FYI, here are some other support venues to consider if you want to pursue this product-related inquiry, going forward:

-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, if you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.

**Comment by mannok** [comment]
Hi developers, is there any plan or roadmap to support it on Linuxs containers?
