### ISSUE TITLE
automatically select one neary character when clicking on the code(not always, but at a high rates)

### ISSUE THREAD

**Issue by benrui** [MicrosoftDocs/visualstudio-docs#2967]
When clicking on the c# document, the cursor will automatically select a nearby character, the expected action should be put the cursor "I" between two characters. If you do 10 clicks, you will get 3-5 random auto-selected, it's really annoying.
I have tested the same action with Xcode, VS Code, Sublime and other editors event web form, they all doing good, so this is not a hardware(Mouse) issue.

This bug is nothing about the "Insert" mode. I have confirmed that the setting is correct.

if you need further information or screen recording, pls contact me at  wangbenrui@gmail.com

system information as below:

Visual Studio Community 2017 for Mac
Version 7.8.3 (build 2)
Installation UUID: 012eece2-68c1-403a-a7fc-c6d3a5c68f6a
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.0.0.0 ( / b40230c0)

	Package version: 516010000

Mono Framework MDK
Runtime:
	Mono 5.16.1.0 (2018-06/a76b50e5faa) (64-bit)
	Package version: 516010000

NuGet
版本: 4.8.2.5835

.NET Core
运行时: /usr/local/share/dotnet/dotnet
运行时版本:
	2.1.9
	2.0.5
	2.0.0
	1.1.2
	1.0.5
SDK: /usr/local/share/dotnet/sdk/2.1.505/Sdks
SDK 版本:
	2.1.505
	2.1.4
	2.0.0
	1.0.4
MSBuild SDK: /Library/Frameworks/Mono.framework/Versions/5.16.1/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Profiler
版本: 1.6.4
位置:/Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
版本: 11

Xamarin.Android
版本: 9.1.8.0 (Visual Studio Community)
Android SDK: /Users/wangbenrui/Applications/android-sdk-macosx
	受支持的 Android 版本:
		4.0.3 (API 级别 15)
		4.1   (API 级别 16)
		5.1   (API 级别 22)
		6.0   (API 级别 23)
		7.0   (API 级别 24)
		7.1   (API 级别 25)
		8.0   (API 级别 26)
		8.1   (API 级别 27)

SDK Tools 版本: 26.1.1
SDK 平台工具版本: 28.0.2
SDK 生成工具版本: 29.0.0 rc1

Microsoft Mobile OpenJDK
Java SDK: /Users/wangbenrui/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
1.8.0-25
Android Designer EPL 代码在此处提供:
https://github.com/xamarin/AndroidDesigner.EPL

Android Device Manager
Version: 7.8.1.0
Hash: 8924ea4a

Apple Developer Tools
Xcode 10.1 (14460.46)
Build 10B61

Xamarin.Mac
Version: 5.2.1.16 (Visual Studio Community)
Hash: 2dc06c71
Branch: 
Build date: 2019-02-12 23:09:50-0500

Xamarin.iOS
Version: 12.2.1.16 (Visual Studio Community)
Hash: 2dc06c71
Branch: d15-9
Build date: 2019-02-12 23:09:50-0500

Xamarin Inspector
Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

Build Information
Release ID: 708030002
Git revision: fd02e670fdd6b101bc9c08b1cc5b7710d9f58cd8
Build date: 2019-03-08 10:30:21+00
Build branch: release-7.8
Xamarin extensions: 1f72f0a3737128552336f27e189d3c4f0cdebd00

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Fri Nov  2 20:43:16 PDT 2018
    root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

Enabled user installed extensions
Show in Github 1.0.4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8d535de-1048-64ac-ffa6-c4338a62056a
* Version Independent ID: 88885b9f-d83d-ce59-90e9-890c958f8721
* Content: [Visual Studio Customer Experience Improvement Program - Visual Studio 2017 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/visual-studio-experience-improvement-program?view=vsmac-2017#feedback)
* Content Source: [mac/2017/visual-studio-experience-improvement-program.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/2017/visual-studio-experience-improvement-program.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Hi @benrui that does sound like an issue. Please follow the instructions to [report an issue in Visual Studio](https://docs.microsoft.com/visualstudio/mac/report-a-problem) - this will help our team to diagnose and resolve.

Also, you might be interested to know that Visual Studio 2019 for Mac (currently in Preview) has a completely new editor being tested. Details are here:
https://devblogs.microsoft.com/visualstudio/visual-studio-2019-for-mac-preview-3/
This might help resolve your issue in the future too.

Thanks for your feedback.
