### ISSUE TITLE
Fix the installer package path

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#2968]
@geforce-hisa0904 commented on [Sun Mar 31 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1784)

Regarding the 1 of section of "To add an installer package by using Package.xml", I guess that the path of installer package is wrong at least when using Visual Studio 2017 and Microsoft Visual Studio Installer Projects.
Could you confirm it?

**Current:**
32 bit system : C:\Program Files\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages
64 bit system : C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages

>1. In File Explorer, open the Packages folder.
>By default, the path is C:\Program Files\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages on a 32-bit system and C:\Program Files (x86)\Microsoft Visual Studio 14.0\SDK\Bootstrapper\Packages on a 64-bit system.

**Suggestion:**
32 bit system : C:\Program Files\Microsoft SDKs\ClickOnce Bootstrapper\Packages
64 bit system : C:\Program Files (x86)\Microsoft SDKs\ClickOnce Bootstrapper\Packages

[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 73a13e0d-b415-6953-0a25-bbfd3f6a3724
* Version Independent ID: d422e2a7-5595-9274-ace8-38a91fcef21a
* Content: [方法: ClickOnce アプリケーションと共に必須コンポーネントを含める - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/deployment/how-to-include-prerequisites-with-a-clickonce-application?view=vs-2017#feedback)
* Content Source: [docs/deployment/how-to-include-prerequisites-with-a-clickonce-application.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/deployment/how-to-include-prerequisites-with-a-clickonce-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this since the user is reporting an error in the original documentation
best

**Comment by geforce-hisa0904** [comment]
Hello @CeciAc 
I seem that this page is fixed. (I don't know when fixed.) Therefore, I guess that this issues can close.
Thanks,
