### ISSUE TITLE
VSTO Outlook-Task Pane get Current MailItem

### ISSUE THREAD

**Issue by 0412Python** [MicrosoftDocs/visualstudio-docs#2969]
I build a VSTO Outlook C# addin by this Link:

[Walkthrough: Display custom task panes with email messages in Outlook](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-displaying-custom-task-panes-with-e-mail-messages-in-outlook.md)
I insert a button on the task pane.
Now I want to use this button to insert a mail titel like"tset for button"by action Button_Click
I try to use
`Outlook.Inspector inspector = Globals.ThisAddIn.Application.ActiveInspector();`
or
`Outlook.MailItem mailItem = Inspector.CurrentItem as Outlook.MailItem;`
to get current inspector but seems not work.
Here is my code below:

> private void InsertButton_Click(object sender, EventArgs e)
>         {
>             Outlook.Inspector inspector = Globals.ThisAddIn.Application.ActiveInspector();
>             if (inspector is Outlook.MailItem)
>             {
>                 public Outlook.MailItem mailItem;
>                 mailItem = inspector as Outlook.MailItem;
>                 mailItem.subject = "test for button";                
>             }                               
>         }

And I also tried this founction:

> private void InsertButton_Click(object sender, EventArgs e)
>         {
>             Outlook.MailItem mailItem = Inspector.CurrentItem as Outlook.MailItem;
>             mailItem.subject = "test for button";
>         }

Can you tell me what's wrong with me?

**Comment by TerryGLee** [comment]
@John-Hart FYI.

**Comment by John-Hart** [comment]
@0412Python, you're close.  Try something like this: 

            var inspector = e.Control.Context as Inspector;
            var mailItem = inspector.CurrentItem as MailItem;

**Comment by John-Hart** [comment]
#please-close

**Comment by 0412Python** [comment]
@John-Hart thank you for your answer.
But in`private void InsertButton_Click(object sender, EventArgs e)`
`EventArgs` was not definition `Control` property.

**Comment by John-Hart** [comment]
Sorry @0412Python  I misread where you had placed the button.  The code I provided works for a button on a Ribbon.  

Does this work for you? 

        private void Button1_Click(object sender, EventArgs e)
        {
            Inspector inspector = Globals.ThisAddIn.Application.ActiveInspector();
            MailItem mailItem = inspector.CurrentItem as MailItem;
            mailItem.Subject = "test for button";
        }

**Comment by 0412Python** [comment]
Thank you for your support. It works!
