### ISSUE TITLE
LinkedIn Learning 3 months free NOT ACTIVATING!!!

### ISSUE THREAD

**Issue by davenisarg** [MicrosoftDocs/visualstudio-docs#2971]
I am trying to activate my LinkedIn Learning three months free trial but link isn’t working and it says ‘We are out of codes, Please try later'

**Comment by TerryGLee** [comment]
@evanwindom FYI

**Comment by evanwindom** [comment]
@davenisarg Thanks for reaching out.  We're aware of the issue and are working on a resolution.  Please do not make additional attempts to retrieve the code as this may cause further errors.  I will post here once the issue is resolved.

Thank you for your patience.

**Comment by davenisarg** [comment]
@evanwindom Sorry I closed it by mistake. May I know whether it is solved or not?

**Comment by davenisarg** [comment]
Hello @evanwindom and @TerryGLee,

I am still getting this error,

"Oops! We've temporarily run out. Please try again later."

**Comment by evanwindom** [comment]
LinkedIn is no longer offering the 3-month Premium benefit through Visual Studio Dev Essentials.  A one-month free trial is available at https://www.linkedin.com/learning/me.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for providing us with the status of the LinkedIn Learning benefit. We are closing this issue now.
