### ISSUE TITLE
Update article?

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/visualstudio-docs#2972]
The screenshots in this article date back to before Microsoft bought Xamarin, and the IDE was still called Xamarin Studio. (I can tell because the iconography has changed between then and now.) Would it be possible to update the screenshots to reflect the current UI?

Also, I noticed a distinct lack of context with regards to the Add-in Maker. While I already know what it is, there is no introduction for users who are unfamiliar with it, nor are there directions on how to install it. I would appreciate it if this could be added as well. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81fd881-9387-165a-846c-37025ccf433b
* Version Independent ID: a0bfdf42-fc87-0b73-8cdb-fb935434be70
* Content: [Extending Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac?view=vsmac-2019)
* Content Source: [mac/extending-visual-studio-mac.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/extending-visual-studio-mac.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-sdk**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @wjk.

As you might have seen, Visual Studio for Mac is getting a completely re-written editor experience. As part of the ongoing improvements, there is a questionnaire linked [from the "extending" page](https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac?view=vsmac-2019#additional-information) where you can help us by sharing your use-cases for the AddInManager.

Your input would be appreciated. The documentation will be updated along with our improvements to the product.
