### ISSUE TITLE
Could you share the configured project?

### ISSUE THREAD

**Issue by fei4xu** [MicrosoftDocs/visualstudio-docs#2973]
[Enter feedback here]

The document seems to be interesting, but I can't follow it by modifying my project. Could you share the whole configured project so that I can test and follow?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6261e48-d28d-38ce-a32c-3394c1122f32
* Version Independent ID: 2b115f45-6220-cdc3-b99e-49c8dae885a0
* Content: [Find memory leaks with the CRT Library - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library?view=vs-2017)
* Content Source: [docs/debugger/finding-memory-leaks-using-the-crt-library.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/finding-memory-leaks-using-the-crt-library.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@fe4xu We'd need to recreate the project and then share it as a public sample. We have to balance that against other work on the backlog. At minimum, we can plan to retest this topic and update if any important info is missing.

**Comment by Mikejo5000** [comment]
We have a backlog item for this work, but not sure yet when we will get to it vs. other priorities. Closing this issue.

**Comment by Mikejo5000** [comment]
Re-opening. I'm adding an example with a memory leak for the first section of the article for malloc. A full example for the `new` keyword is already present in the article.

**Comment by Mikejo5000** [comment]
Fix should be live by EOD 12/13/22
