### ISSUE TITLE
Should the use of xcopy be robocopy instr

### ISSUE THREAD

**Issue by lucasfolino** [MicrosoftDocs/visualstudio-docs#2977]
[Enter feedback here]
In this document it reference to use xcopy for copying files to a remote network share.  Should that be robocopy?  I thought xcopy superseded xcopy?  If not please close and ignore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@lucasfolino Thanks for your inquiry 
@tydunkel Your input, please?

**Comment by tydunkel** [comment]
Robocopy was created to be the replacement for xCopy, but both can be used to copy files. We could add documentation using robocopy to provide more options, but as a general guidance either would work.
