### ISSUE TITLE
"Read more here" is missing a link

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#2980]
&gt; Leverage Azure Test Plans (part of Azure DevOps) for your manual and exploratory testing needs. Read more here.

The "Read more here" doesn't include a link to the additional content

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3315d1-e6d3-e86d-9cce-1ff9ce0fc482
* Version Independent ID: ae3fd143-bf0b-4cfe-bcad-557eb41fdc2c
* Content: [Port, migrate, and upgrade projects - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2019)
* Content Source: [docs/porting/port-migrate-and-upgrade-visual-studio-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/porting/port-migrate-and-upgrade-visual-studio-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@nschonni Thanks for letting us know; we'll take a look and get that fixed.

**Comment by TerryGLee** [comment]
@nschonni Thanks again for reporting this; we've fixed the link issue.
