### ISSUE TITLE
Component ID Typo

### ISSUE THREAD

**Issue by pierre-mounir** [MicrosoftDocs/visualstudio-docs#2982]
Component Ids statring with
"Microsoft.Net.Core.Component.SDK...."
are listed as .NET Core ... Development Tools (Not SDK)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019#feedback)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@pierre-mounir Thanks for letting us know; we'll investigate and report back.

**Comment by TerryGLee** [comment]
@pierre-mounir I've both inquired internally and reviewed the history of this page over time, and discovered that we've always referred to "Microsoft.Net.Core.Component.SDK" as "development tools" in the Name column. Because this information is an automated pull from the product manifest, we (respectfully) decline to change this. But thanks again for your inquiry; we always appreciate feedback on our documentation. :)

**Comment by TerryGLee** [comment]
(I'll close this issue now, but you can still add comments to it, should you wish.)

**Comment by pierre-mounir** [comment]
@TerryGLee thanks for your reply.
It's just strange to find out that all other components like .Net Framework SDK "Microsoft.Net.Component...SDK" are named with the SDK suffix.
And .NET Core SDK is named "Development Tools" like the component "Microsoft.NetCore.ComponentGroup.DevelopmentTools..."

**Comment by TerryGLee** [comment]
@pierre-mounir You're right. I noticed this inconsistency myself after you filed this issue -- and I made it known to others. Although we won't fix it now (at least in the short term), we're aware of it. Perhaps that might be enough to get it changed in the future.

Thanks again for bringing this to our attention. :)
