### ISSUE TITLE
Possibly incorrect wildcard example for including files

### ISSUE THREAD

**Issue by adem** [MicrosoftDocs/visualstudio-docs#2983]
In the section [Include, Exclude, and wildcards](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2017#include-exclude-and-wildcards), the second snippet suggests that "it adds all files with the file extension .jpeg in the images folder, and all its subfolders, to the Photos item type."

`<Photos Include="images\**.jpeg" />`

This is inconsistent with the working example in the article [How to: Select the files to build](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-select-the-files-to-build?view=vs-2017), where the glob pattern `*.jpg` is preceded by `\**\`:

`<Photos Include="Images\**\*.jpg" />`

Here's my folder structure:
```
│
└───textfiles
    ├───bar
    │   └───baz
    │           file2.txt
    │           file3.txt
    │
    └───foo
            file1.txt
```

Here's what each syntax yields:
```
<ItemGroup>
  <TextFiles Include="textfiles\**.txt"></TextFiles>
</ItemGroup>
<Target Name="HelloWorld">
  <Message Text="Files to include: @(TextFiles, '%0A%0D')" />
</Target>
```
yields
```
[...]HelloWorld:
  Files to include: textfiles\**.txt
Done Building Project "C:\[...]
```
and
```
<ItemGroup>
  <TextFiles Include="textfiles\**\*.txt"></TextFiles>
</ItemGroup>
<Target Name="HelloWorld">
  <Message Text="Files to include: @(TextFiles, '%0A%0D')" />
</Target>
```
yields
```
[...]HelloWorld:
  Files to include: textfiles\bar\baz\file2.txt
textfiles\bar\baz\file3.txt
textfiles\foo\file1.txt
Done Building Project "C:\[...]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41d57f6-25bf-bc84-7ba8-4cb4ecedac05
* Version Independent ID: 69c3bd43-6c2b-834b-18d2-0555a79961a7
* Content: [Walkthrough: Using MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2017)
* Content Source: [docs/msbuild/walkthrough-using-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-using-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Looks correct. Updating doc.
