### ISSUE TITLE
Mac Desktop apps  in the type of app.

### ISSUE THREAD

**Issue by flemingm** [MicrosoftDocs/visualstudio-docs#2984]
You say Mac Desktop apps  in the type of app. 

But do not include any details below -- list all other type of app have sections and links to additional docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c51e5f1-10c6-bf93-8ccf-092a2c587903
* Version Independent ID: f445f27b-642c-e62b-b0cf-27c4bb3fda46
* Content: [Visual Studio for Mac Workloads - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/workloads?view=vsmac-2019#feedback)
* Content Source: [mac/workloads.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/workloads.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your feedback @flemingm.

The pages you are looking for are [Xamarin.Mac](https://docs.microsoft.com/xamarin/mac/) which covers Mac apps built with Cocoa UI, and [Xamarin.Forms on Mac](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/platform/other/mac) which lets you build a shared UI with XAML.

We'll update the page to reflect this as well.
