### ISSUE TITLE
Assembly Not Found for framework Xamarin.Android v9.0

### ISSUE THREAD

**Issue by pandiyan022** [MicrosoftDocs/visualstudio-docs#2985]
I have installed new Version of Visual Studio 2019. after that i created a new Xamarin project, then i try to build a Application. Its Showing Assembly Reference issue in Following Dll.  

System.dll
System.Core
System.xml 

![Screen Shot 2019-04-03 at 8 09 59 PM](https://user-images.githubusercontent.com/5680380/55488153-1d90a500-564d-11e9-8e1f-d5c075e90995.png)

please give me any solution  for solving the Issue

**Comment by orestesgaolin** [comment]
I have the same problem. I tried to add the .dll directly in Rider but this doesn't fix problem and causes dozens of errors later.

**Comment by patel-pragnesh** [comment]
i have same problem.

**Comment by eduardo-rta** [comment]
I'm having the same issue, tried to install newest mono but didn't work. Now I can't even compile existing projects that I had.

**Comment by kyurkchyan** [comment]
Having the same issue...

**Comment by awattar** [comment]
Same here. It also does not list 9.0 (Android 28) as supported.

=== Visual Studio Enterprise 2019 for Mac ===

Version 8.0.5 (build 9)

=== Xamarin.Android ===

Version: 9.2.3.0 (Visual Studio Enterprise)
Android SDK: /Users/mwesolowski/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.2
SDK Build Tools Version: 28.0.3

**Comment by biapar** [comment]
I've too.

**Comment by ExtremeKaos** [comment]
Same here,

**Comment by biapar** [comment]
I solved:

- manually change project file adding .net reference
- delete obj and bin
- close solution and reopen
- rebuild solution

**Comment by SteHiggins** [comment]
> I solved:
> 
> * manually change project file adding .net reference
> * delete obj and bin
> * close solution and reopen
> * rebuild solution

I have the same issue.  

What .net reference did you add?

**Comment by acmngmbh** [comment]
Same Problem here with an existing project, that already compiled

**Comment by marcnegri** [comment]
Same issue here :
It's an old big project with a lot of assemblies. But, impossibe to compile + weird behavior when trying to release etc..

**Comment by patel-pragnesh** [comment]
Today update VS studio. 
other error resolved. Still issue in java.interop.dll

**Comment by Afshin1980** [comment]
Same problem!

**Comment by conceptdev** [comment]
Please use the **Help > Report a problem** menu item in Visual Studio, as it will provide additional information about your system to help diagnose the problem. Thanks!

**Comment by tele-bird** [comment]
Closed but no resolution??

**Comment by SABlyu** [comment]
same issue... and I assume low priority label tells everybody that no chance to get a fix in the nearest years 8(

**Comment by Aleksey7151** [comment]
Same here! VS for Mac 8.5.1 Java.Interop not found

**Comment by Aleksey7151** [comment]
> Please use the **Help > Report a problem** menu item in Visual Studio, as it will provide additional information about your system to help diagnose the problem. Thanks!

We have provided all information about our systems. What additional info do you need? Why you've closed the bug, without solving it?

**Comment by fmacedoo** [comment]
2021 and I have almost the same issue, but with v10.0 and that's why I leave Xamarin years ago! :(

**Comment by vas1l3nk** [comment]
Same here! Vs for Mac 8.10.19(build 2) Java.Interop not found
