### ISSUE TITLE
Image says Apache And

### ISSUE THREAD

**Issue by nightst4r** [MicrosoftDocs/visualstudio-docs#2987]
I think you meant Apache Ant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab51e2f8-b5b5-007a-a9b3-23a85b2f2d88
* Version Independent ID: 9cd86e2f-b4d8-00d9-1d02-294bb2692a1d
* Content: [Install Visual C++ for Cross-Platform Mobile Development - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-visual-cpp-for-cross-platform-mobile-development?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@nightst4r That's hilarious. That's what comes of using pre-release bits to do the screenshots, I guess.

**Comment by corob-msft** [comment]
A spiffy new screenshot should appear sometime tomorrow before noon Pacific time.
