### ISSUE TITLE
Feature availability note is missing

### ISSUE THREAD

**Issue by alpaix** [MicrosoftDocs/visualstudio-docs#2988]
The original feature availability note only appears at the top in Visual Studio 2017 view.
> CodeLens is available only in Visual Studio Enterprise and Visual Studio Professional editions. It is not available in Visual Studio Community edition.

Although, this note is relevant for Visual Studio 2019 as well. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aeed9cef-8a01-ad6e-36a7-c858ac44c952
* Version Independent ID: 43948287-86e7-cf04-344f-48bb32592e1a
* Content: [Find code changes and other history with CodeLens - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/find-code-changes-and-other-history-with-codelens?view=vs-2019#feedback)
* Content Source: [docs/ide/find-code-changes-and-other-history-with-codelens.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/find-code-changes-and-other-history-with-codelens.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@alpaix The note was actually purposefully omitted from the 2019 version of the page because CodeLens *is* available in Community edition of Visual Studio 2019.

**Comment by alpaix** [comment]
That's right, CodeLens is available in Community edition of Visual Studio 2019. Although, lenses for source control history and IntelliTrace are still an Enterprise-only feature. And our team received a number of customer complaints regarding git lenses not working. I think it'd be great keeping the note clarifying the availability aspect.

**Comment by gewarren** [comment]
Gotcha, thanks for clarifying. I'll update it.

**Comment by alpaix** [comment]
Correction. Source control lenses are available in Pro and Enterprise. Intellitrace lenses is an Enterprise-only feature.

**Comment by gewarren** [comment]
@alpaix Can you clarify what the IntelliTrace lenses are for? Also, is this part of the doc about Skype still applicable or does it need an update?

### Q: Why don't I see the Skype indicators?

**A:** Skype indicators don't appear if you're not signed into Skype for Business, don't have it installed, or don't have a supported configuration. However, you can still send email.

**Which Skype and Lync configurations are supported?**

- Skype for Business (32-bit or 64-bit)

- Lync 2010 or later alone (32-bit or 64-bit), but not Lync Basic 2013 with Windows 8.1

CodeLens doesn't support having different versions of Lync or Skype installed. They might not be localized for all localized versions of Visual Studio.

**Comment by alpaix** [comment]
IntelliTrace is a debug assistant. It adds a code lens with method execution diagnostic data. I presume mentioning it in this particular article is not needed.

Skype information is correct and still relevant.

Thanks!

**Comment by gewarren** [comment]
@Mikejo5000 Do we mention the IntelliTrace data in CodeLens anywhere in the debugging docs? I couldn't find any mentions.

**Comment by Mikejo5000** [comment]
@gewarren Hmm, this diagnostic data would show in the CodeLens UI? If so, I wouldn't expect to find that in the IntelliTrace docs, which don't really talk about CodeLens. The best thing might be a note in the CodeLens docs that if you enable IntelliTrace (VS Enterprise only), then you get method execution diagnostic data. I suspect we don't need much more than a note... plus maybe a mention and a link from the IntelliTrace overview docs, which I could add. How does this sound?
