### ISSUE TITLE
Request for improvement

### ISSUE THREAD

**Issue by mcurko** [MicrosoftDocs/visualstudio-docs#2990]
I'm not sure where exactly to post this, so I'll put it here. I think it would be very useful to add a tutorial on how to debug .NET Core web application, including Framework code and exceptions thrown in razor views. Although having searched several times for solution for this, I have never been able to find an exact solution on how to accomplish this. I believe that this is something very useful for the developer community.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24b3bf43-8ca1-4de3-7b01-a45526b7536b
* Version Independent ID: df5c509c-3b30-775c-9e6e-5fab0bb77bfd
* Content: [What is debugging? - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/what-is-debugging?view=vs-2019#feedback)
* Content Source: [docs/debugger/what-is-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/what-is-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mcurko I believe debugging Razor syntax is supported:
https://docs.microsoft.com/en-us/aspnet/web-pages/overview/testing-and-debugging/introduction-to-debugging#using-debugging-tools-in-visual-studio
Let me know if you find issues. As far as generally debugging .NET Core, this is supported. If you are running the app locally, you should be able to debug as any other supported app type. If you are running the app on a web server, there are different remote debugging scenarios. See links here:
https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019

**Comment by Mikejo5000** [comment]
@mcurko. If this is still an issue, it looks like a product bug. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. At the point, it will get listed in [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
