### ISSUE TITLE
Azure Test Plans

### ISSUE THREAD

**Issue by sazimi** [MicrosoftDocs/visualstudio-docs#2993]
I got redirected from Azure Test plans (via AzureDevOps) page which stated Unit and functional testing. I was hoping to see some content\tips & tricks on Azure test plans w.r.t unit and functional testing. Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 904d0bfe-b144-c2d1-3f1e-4db6c64e049e
* Version Independent ID: 6eda8810-d777-e4b7-0e1c-0bd7b16d450b
* Content: [Unit Testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-your-code?view=vs-2019#feedback)
* Content Source: [docs/test/unit-test-your-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/unit-test-your-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by sazimi** [comment]
And all the content here is about visual studio.

**Comment by gewarren** [comment]
@sazimi Did you click the last link on [this page](https://docs.microsoft.com/en-us/azure/devops/test/?view=azure-devops) when you arrived here on the Visual Studio docs? I'm not sure if the Azure DevOps documentation includes any info about writing unit tests but I'll try to find out.

**Comment by gewarren** [comment]
@TerryGLee Is there a way we can move this issue to the [vsts-docs repo](https://github.com/MicrosoftDocs/vsts-docs/issues)?

**Comment by gewarren** [comment]
> @TerryGLee Is there a way we can move this issue to the vsts-docs repo?

It looks like we'd need to be an admin on that repo. @sazimi Can you please log your issue on the [vsts-docs repo](https://github.com/MicrosoftDocs/vsts-docs/issues) instead? They track their docs issues separately to us (Visual Studio). Thank you for helping us improve the docs.
