### ISSUE TITLE
DependsOnTargets Vs AfterTargets

### ISSUE THREAD

**Issue by itanex** [MicrosoftDocs/visualstudio-docs#2994]
What are the use cases for these two? They seem to do the same thing. If I say my target depends on another target, does this not mean the same thing as run my target after another target? Can someone help clarify this for me?
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2edf4455-765e-3107-5b5b-11162a965b65
* Version Independent ID: 37110ada-36c1-f545-d0e0-1c5bacbf71ab
* Content: [Target Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/target-element-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/target-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/target-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@itanex I believe the difference is that AfterTargets actually runs those targets, whereas DependsOnTargets doesn't do anything to actually run the dependent targets, and just waits to make sure that they have already completed. @rainersigwald to verify

**Comment by rainersigwald** [comment]
`<Target Name="x" DependsOnTargets="y" />` means: 

* If something wants to run `x`, `y` must run first.

`<Target Name="a" AfterTargets="b" />` means: 

* If something runs `b`, then run `a` after it.

They differ in a couple of ways. `BeforeTargets` and `AfterTargets` are generally used for _extending_ the build: "I have a custom target I want to run after `ResolveReferences`". The target that's being hooked onto doesn't need to know anything about the new target.

In contrast, `DependsOnTargets` is the basic building block of the target-dependency graph. When authoring a target, use `DependsOnTargets` to ensure that all of your inputs (both file and MSBuild item/property) have already been brought up to date.

**Comment by itanex** [comment]
Thanks, that helps me better understand this a bit better now. And why my solution passed my tests. :)
