### ISSUE TITLE
App.config is the default file name created

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/visualstudio-docs#2997]
The documentation indicates that you can enter a name for app.config file.  The entered name will be the name of the config file (myname.config).  The default if you don't change the name will create an app.config file.

Also, this should indicate that visual studio will only copy app.config file to bin/BinOutputName.config during a build.  Any other .config filenames must be explicitly copied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f03b50b-74c7-2e0e-ff49-eb747d887979
* Version Independent ID: 7aff7001-a1ac-6088-4b19-94b5e870c709
* Content: [How to add an app.config file to a project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-app-config-file?view=vs-2019)
* Content Source: [docs/ide/how-to-add-app-config-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-add-app-config-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by binpatel31** [comment]
We have to just make changes in Documentation only ? (just adding note that other .config filenames are needed to be explicitly copied.)
