### ISSUE TITLE
Need to point to Tools>Extensions and Updates to get to the first image

### ISSUE THREAD

**Issue by KathrynEE** [MicrosoftDocs/visualstudio-docs#2998]
I found the steps to get to the first image on this page not adequate. I didn't see how to get to Manage Extensions. I'm using VS 2017. I had to search to find Tools&gt;Extensions and Updates to open a dialog that looks similar to what is shown. Also - I was surprised that entering Marketplace in the TOC filter didn't bring up any topics. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and use extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2017#feedback)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Hi Kathryn. It sounds like you were looking at the VS 2019 version of the page and not the VS 2017 version. Can you see if the VS 2017 version makes more sense? I'll add marketplace to the TOC as a displayName.

**Comment by TobiasDeVries** [comment]
Hi, I'm using Visual Studio2017 and had the same Problem.

**Comment by gewarren** [comment]
@TobiasDeVries Are you referring to these instructions and image? If so, make sure you have Visual Studio 2017 selected (in the left pane above the table of contents).

![image](https://user-images.githubusercontent.com/24882762/63182117-9abe2480-c006-11e9-9b3d-a6a606c4ba80.png)
