### ISSUE TITLE
Documentation provided in the "More information" link of the "One-Way Upgrade" dialog is inaccurate in the context of .NET Core and ASP.NET Core projects 

### ISSUE THREAD

**Issue by morrisjoe** [MicrosoftDocs/visualstudio-docs#30]
Copied over from dotnet/roslyn-project-system#967

Fix here is to add a pj->csproj migration related blurb to https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects and cross-link it to more info in .NET Core docs.

Suggest reviewers @morrisjoe

**Comment by morrisjoe** [comment]
cc @ghogen @mairaw

**Comment by mairaw** [comment]
I think this is done. Can we close @morrisjoe?
