### ISSUE TITLE
Activation doesn't work

### ISSUE THREAD

**Issue by jok26r** [MicrosoftDocs/visualstudio-docs#3005]
Tried to activate VisualStudio 2019 Professional using StorePID.exe in accordance with the article and unsuccessful. Activativation through GUI works fine as well as StorePID for VisualStudio 2017 Professional. Is that correct that MPC codes stayed the same as for the version 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11e2b93a-e89d-42ce-23d7-4cf85f47ba25
* Version Independent ID: 4083c0d5-c871-ef24-d11c-b6ec1adbb571
* Content: [Automatically apply product keys - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/automatically-apply-product-keys-when-deploying-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@jok26r Thanks for letting us know; we'll investigate and report back.

**Comment by skyJG** [comment]
@TerryGLee Same for me. :(
I'm unable to activate VS2019 Professional using your guide.

**Comment by mikolaisebastian** [comment]
@TerryGLee Same here. Tried to deploy with keys, but doesn't work for me.

**Comment by crmann1** [comment]
Visual Studio Enterprise | 09260
Visual Studio Professional | 09262

If it is not working can you check to make sure you are in an administrator developer command prompt and that the product key is for the type of VS you are installing, for example enterprise and professional have different MPC's which need to be used.

**Comment by jok26r** [comment]
@grossag thanks you a lot. It works fine now.

**Comment by mikolaisebastian** [comment]
@grossag @jok26r  Do you have VS2019 Version 16.0.0 or 16.0.1?

**Comment by jok26r** [comment]
@mikolaisebastian I have both and I have activated them without a problem with the correct MPC.

**Comment by skyJG** [comment]
@grossag @jok26r We tried to activate VS2019 Proffessional Version 16.0.0 and 16.0.0.1 with MPC 09262 via Elevated PowerShell and Elevated Command Prompt, but the Key was not accepted by Visual Studio.
If the Key is entered in Visaul Studio via Activation Prompt, it works.
So unfortunatley no Key Deployment for us :(

**Comment by TerryGLee** [comment]
Thanks everyone for your feedback. We've updated the documentation with the correct codes. Also, we're aware that folks would like more PowerShell info; we've taken that under advisement and will add it to our future content plans.
