### ISSUE TITLE
Configure unit tests by using a .runsettings file - video data collector

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/visualstudio-docs#3006]
Applies to: [Configure unit tests by using a .runsettings file](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)

Dear Docs team,

With the release of VS 2019, do we need to update the version number in `VideoRecorder, Version=15.0.0.0` or is that staying the same?

**Example of sample .runsettings file:**

```
      <DataCollector uri="datacollector://microsoft/VideoRecorder/1.0" assemblyQualifiedName="Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder.VideoRecorderDataCollector, Microsoft.VisualStudio.TestTools.DataCollection.VideoRecorder, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" friendlyName="Screen and Voice Recorder">
        <!--Video data collector was introduced in Visual Studio 2017 version 15.5 -->
      </DataCollector>
```

Thanks,
--Neno

**Comment by gewarren** [comment]
@PBoraMSFT Can you answer this one?

**Comment by mayankbansal018** [comment]
@NenoLoje you don't need to change the `version`.

**Comment by NenoLoje** [comment]
OK, thanks for confirming @mayankbansal018 . Closing case.

**Comment by alvarou** [comment]
@mayankbansal018 , is not working on VS2019 Enterprise 16.1.1.
@NenoLoje, does it work for you?

Regards.

**Comment by NenoLoje** [comment]
@alvarou I haven't tried with VS 2019 yet, still running agents with VS 2017.

Did it work for you before (with VS 2017)?

**Comment by alvarou** [comment]
@NenoLoje  , It was working on VS2017, both locally and cloud. 

@mayankbansal018 have you tried the video data collector setting on VS2019 16.1.1?

Regards.

**Comment by mayankbansal018** [comment]
@alvarou , I don't remember if I tired on Vs2019 update 1 or not, but will look into this on Monday
