### ISSUE TITLE
Table of contents out of synch?

### ISSUE THREAD

**Issue by kaimikael** [MicrosoftDocs/visualstudio-docs#3007]
In the left column I have selected the item “Inspect data”, but this page is titled “Learn about Debugger Windows in Visual Studio” and does not seem to be directly relevant to inspecting data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf50588d-e604-c240-302e-28bee2f7fd2d
* Version Independent ID: c1b633ea-4e4f-70ce-d049-ac4d6ce988de
* Content: [Debugger windows - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-windows?view=vs-2017)
* Content Source: [docs/debugger/debugger-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debugger-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@kaimikael Thanks for the feedback! I will plan to make some edits so this makes better sense. Most of the debugger windows are for data inspection, so that is why the window content is here.

**Comment by Mikejo5000** [comment]
Updating title and H1
