### ISSUE TITLE
Apply all C# Formatting rules option is missing in VS2019

### ISSUE THREAD

**Issue by dsokhach** [MicrosoftDocs/visualstudio-docs#3008]
Where can I find option "Apply all C# Formatting rules" in VS 2019?
I used to Format Document on save in 2017 and now in 2019, but now I have to additionally keep looking at modified files and manually press Code Cleanup.
Please give ability to apply code cleanup on document format if it is was removed in VS2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf1a218-2295-22ac-03eb-1ccc63b4a3e6
* Version Independent ID: baa311a7-6b87-6196-ae8a-b8759a1df73c
* Content: [C# editor formatting options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-formatting?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/options-text-editor-csharp-formatting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-formatting.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@kendrahavens Can you answer this one?

**Comment by kendrahavens** [comment]
Format document still works in Visual Studio 2019, could you share more on what you are missing? Are you requesting a feature to "Run code cleanup on save"?

**Comment by dsokhach** [comment]
@kendrahavens  In general, **yes**, I'm trying to achieve "run code cleanup on save" behavior.
In VS 2017 each member of my team had 2 things:
1. "Format document on Save" extension 
2. And checked "Perform additional code cleanup during formatting"
![image](https://user-images.githubusercontent.com/40269037/55789073-e2adc780-5ab9-11e9-885a-69c1920df3a7.png)
I find this feature very handy and didn't expect it disappear in VS2019 :-)

**Comment by kendrahavens** [comment]
Thank you for the further details!

The settings just moved to be configured under the Code cleanup UI in Visual Studio 2019.
![CleanupOptions](https://user-images.githubusercontent.com/8293542/55821760-0f121580-5ab3-11e9-8682-71065765b60d.png)
![MovedCleanUpOptions](https://user-images.githubusercontent.com/8293542/55821763-10dbd900-5ab3-11e9-814f-f10a88c788ca.png)

Thank you for noting that this change broke your scenario. Since this is a product bug as well as a documentation bug I've opened an issue to [track it developer ](https://developercommunity.visualstudio.com/idea/525336/code-cleanup-on-save.html)community.

**Comment by kendrahavens** [comment]
@gewarren We do need to update these docs to reflect that these settings now pertain to the Code cleanup experience. I'm circling with the product team to figure out what all updates they may be planning.

**Comment by kendrahavens** [comment]
I just learned there is a [Code cleanup on save extension](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.CodeCleanupOnSave) that you can use while we work on getting this into the product by default.

**Comment by dsokhach** [comment]
@kendrahavens Thank you for finding this one. Tried it and it works as expected.
