### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by SylTeamSoft** [MicrosoftDocs/visualstudio-docs#3009]
VS 2019 and 2017 Remote tool download links are broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019#feedback)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@SlyTeamSoft Thanks--sometimes that can happen at a new release. I'll check them.

**Comment by Mikejo5000** [comment]
Looks like VS 2017 remote tools are here now:
https://my.visualstudio.com/Downloads?q=remote%20tools%20visual%20studio%202017
