### ISSUE TITLE
Visual Studio Installer Kills Powershell

### ISSUE THREAD

**Issue by KZeronimo** [MicrosoftDocs/visualstudio-docs#301]
Sometime post the 15.3 release of Visual studio the installer kills Powershell instances during the install of PS modules

See [here](https://developercommunity.visualstudio.com/content/problem/47251/no-reboot.html) and [here](https://github.com/Azure/azure-powershell/issues/2220)

I'm sure there is a better place for this issue - not sure quite where that is ...

**Comment by gewarren** [comment]
@KZeronimo this is not really the right place for the issue, but since someone has already created an issue on developercommunity.visualstudio.com, could you upvote it to make it more likely to be addressed by the product team?
