### ISSUE TITLE
msbuild could not find the latest .net core sdk

### ISSUE THREAD

**Issue by bryanchen-d** [MicrosoftDocs/visualstudio-docs#3012]
so I installed VS2017 which comes with a .net core sdk 2.1.105, and then I installed .net core sdk 2.2.202 and via VS I created a .net core web app on .net core app version 2.2.

Then the problem is building the project in VS and with msbuild on command line both give me error:

C:\Program Files\dotnet\sdk\2.1.505\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2

but if the .net CLI tool shows the 2.2.202 version is already installed, and build it using the CLI command "dotnet build &lt;project&gt;" works perfectly.

What did I miss to get msbuild and VS work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1927440c-08b4-d442-d315-24b677603034
* Version Independent ID: e334f0d3-627a-a3f6-cdfb-b3abfcccd1e7
* Content: [How to: Reference an MSBuild Project SDK - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019#feedback)
* Content Source: [docs/msbuild/how-to-use-project-sdk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-use-project-sdk.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by loop-evgeny** [comment]
I'm running into this as well. Installed .NET Core 2.2 SDK (`dotnet --info` output: 
[dotnet-info.txt](https://github.com/MicrosoftDocs/visualstudio-docs/files/3057929/dotnet-info.txt) ). Created a new .NET Core console project in VS 2017 15.9.9. It targets .NET Core project by default:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>

</Project>
```

When I try to build it, either in VS or using msbuild from the command line, I get the error above. `dotnet build` succeeds, however. In project properties VS does not show .NET Core 2.2 as an installed framework: ![image](https://user-images.githubusercontent.com/34301024/55786248-2dc4dc00-5ab4-11e9-8548-9ca775c26749.png)

Log of `msbuild /v:diag`: [build-diag.txt](https://github.com/MicrosoftDocs/visualstudio-docs/files/3057948/build-diag.txt)

**Comment by Mikejo5000** [comment]
@bryanchen-d  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by bryanchen-d** [comment]
I think I have figured out the problem, the dotnet core v2.2.202 has a breaking change that it requires msbuild v16. However msbuild with VS2017 is of version v15.*. so the workaround to this issue would be either
* install lower version of dotnet core, e.g. v2.2.105
* install VS2019

**Comment by Mikejo5000** [comment]
@bryanchen-d Thanks for following up with that! That seems to make sense.
