### ISSUE TITLE
First code sample has four errors

### ISSUE THREAD

**Issue by fourdragons** [MicrosoftDocs/visualstudio-docs#3013]
The first code sample give four errors when copied.  Since this is the very first experience with WPF and XAML, it's kind of imperative to have the code be exact, for us newbies.  Thanks!

&lt;TextBlock HorizontalAlignment="Center" TextWrapping="Wrap" VerticalAlignment="Center" RenderTransformOrigin="4.08,2.312" Margin="237,57,221,238"&gt;&lt;Run Text="TextBlock"/&gt;&lt;InlineUIContainer&gt;&lt;TextBlock TextWrapping="Wrap" Text="TextBlock"/&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d0e9bb1-0842-e173-6a51-2527d08d9b2a
* Version Independent ID: bfedaa98-f816-f7c5-dba1-6837b94b3962
* Content: [Tutorial: Hello World app with Windows Presentation Foundation (WPF) in Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-basic/tutorial-wpf?view=vs-2019#feedback)
* Content Source: [docs/get-started/visual-basic/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-basic/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@fourdragons Sorry to hear that this didn't work for you; we'll investigate and report back.

**Comment by TerryGLee** [comment]
@fourdragons You're right; the code wasn't correct. It should be now, though (per a fix we published a few days ago).

Thanks for letting us know so that we could get this fixed! We want these tutorials to be useful to you, whether you're a newbie altogether or an experienced developer trying out a new programming language/platform.

Cheers,
~ Terry
