### ISSUE TITLE
How to reset synchronized settings?

### ISSUE THREAD

**Issue by prjm** [MicrosoftDocs/visualstudio-docs#3017]
With a new VS major release, I would like to reset all settings to its defaults. I tried to use a command-line-switch for that (devenv.exe /resetuserdata), which seemed to work initially. But after a few moments, my old settings had been restored from the cloud. So what should I do in this case? Can you add a hint to this page how to reset synchronized settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f452163a-5b45-243c-9601-585359deec53
* Version Independent ID: 881229c0-dfb7-6e68-00ae-868abd0c6687
* Content: [Synchronize settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/synchronized-settings-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/synchronized-settings-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/synchronized-settings-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by MasihAkbari** [comment]
yes i can't find any doc about clearing synced settings on cloud too

**Comment by thwyster** [comment]
Same problem!

**Comment by gewarren** [comment]
I'm looking into this today.

**Comment by MasihAkbari** [comment]
I have a way to solve this but it's kind of hacky.
I installed a fresh instant of visual studio on a computer without signing into my vs account and then exported the environment settings. then i transfer it to my main machine with my synced VS and imported that fresh clean setting, now setting is changing across cloud data and would sync to all of your VS instants with your account.

**Comment by MasihAkbari** [comment]
So, my above hacky way should work but i discover a bug in exporting environment setting that not all of code style rules exported correctly in vssettings file. i reported this bug [here](https://developercommunity.visualstudio.com/content/problem/536234/export-settings-not-export-all-text-editor-code-st.html) hope it get fixed soon

**Comment by gewarren** [comment]
I'm still waiting for an official answer...

**Comment by gewarren** [comment]
The way to do this is to sign into Visual Studio, choose **Tools** > **Import and Export Settings**, and then choose **Reset all settings**. However, there's a bug in Visual Studio 2019 version 16.0 (that will be fixed in version 16.1) that causes reset to not work fully for some settings such as key bindings. The workaround is to edit all the files under `%ProgramFiles%\Microsoft Visual Studio\<version>\<edition>\Common7\IDE\Profiles` to specify “16.0” instead of “15.0” in their **ApplicationIdentity** element.  After doing that, the reset operation should work correctly.

**Comment by AmusementRides** [comment]
@gewarren 
Even with the version 16.1 Preview 2 it is not fixed yet. My sync data saved in my account always turns my Visual Studio 2019 over. I've experimented a bit with the settings and now do not know what I've changed everything. Well, nothing works and the internal reset does not reset everything to factory settings. You should really think about a function for deleting the account as it works with the Win10 sync data via OneDrive. Anyway, I can do nothing more with VS, only confused only 😒.

**Comment by RayKoopa** [comment]
Also awaiting an option to reset or download synced settings. The latter especially to conform to EU data protection laws.
