### ISSUE TITLE
Very light on iOS Device Debugging

### ISSUE THREAD

**Issue by markti** [MicrosoftDocs/visualstudio-docs#3018]
I can get VS for Mac to deploy to a simulator but I cannot get it to deploy or even show my usb connected iphone in the list of deployment targets. I am able to deploy to the iphone using XCode so its clearly a problem with VS for Mac configuration. But there is no documentation on how to do this!

**Comment by asb3993** [comment]
Hi @markti, this documentation is covered in the Xamarin.iOS documentation, which you find here: https://docs.microsoft.com/en-us/xamarin/ios

Make sure that the device is properly provisioned to deploy to a device: https://docs.microsoft.com/en-us/xamarin/ios/get-started/installation/device-provisioning/ 
You can also use Wireless deployment for Visual Studio for Mac: https://docs.microsoft.com/en-us/xamarin/ios/deploy-test/wireless-deployment?tabs=macos

Let me know if you're still having issues.
