### ISSUE TITLE
ERRORLEVEL 2 when applying key

### ISSUE THREAD

**Issue by bitsrules** [MicrosoftDocs/visualstudio-docs#3019]
I followed the instructions on this page but got an error 2, what does this mean?
Can I turn on a log file to get more info?

https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md

**Comment by TerryGLee** [comment]
@bitsrules Sorry to hear that you are receiving a PID_ACTION_INVALID error. 

Question: Are you using [Visual Studio 2017 Enterprise](https://docs.microsoft.com/visualstudio/install/automatically-apply-product-keys-when-deploying-visual-studio?view=vs-2017) or [Visual Studio 2019 Enterprise](https://docs.microsoft.com/visualstudio/install/automatically-apply-product-keys-when-deploying-visual-studio?view=vs-2019)?

Also, it's probably best to log this problem to the Developer Community. That way, people who are best able to answer support questions can provide further assistance. For more information on how to do so, see the [How to report a problem with Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) page.

**Comment by bitsrules** [comment]
Is it Visual Studio 2019 Professional.

I will post the same on the developer community forum.
