### ISSUE TITLE
Visual Studio 2017 (TE) - FileNotFoundException:Microsoft.VisualStudio.QualityTools.Common

### ISSUE THREAD

**Issue by Kis-Janos-Zoltan** [MicrosoftDocs/visualstudio-docs#3021]
The following FileNotFoundException was thrown by opening "STEPS" and "ASSOCIATED AUTOMATION" tabs of a "Test Case" work item type in Microsoft Visual Studio 2017 Test Edition:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.QualityTools.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.QualityTools.Common, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.TeamFoundation.TestManagement.Controls.AssociatedAutomationControl.get_TestManagementService()
   at Microsoft.TeamFoundation.TestManagement.Controls.AssociatedAutomationControl.get_TestCase()
   at Microsoft.TeamFoundation.TestManagement.Controls.AssociatedAutomationControl.RelayoutControls()
   at Microsoft.TeamFoundation.TestManagement.Controls.AssociatedAutomationControl.InvalidateDatasource()
   at Microsoft.TeamFoundation.WorkItemTracking.WpfControls.LegacyWorkItemControl.InvalidateDatasource()
   at Microsoft.TeamFoundation.WorkItemTracking.WpfControls.WorkItemControl.ControlFactory_ControlCreated(Object sender, ControlCreatedEventArgs e)
   at Microsoft.TeamFoundation.WorkItemTracking.WpfControls.WpfControlFactory.OnControlCreated(ControlCreatedEventArgs args)
   at Microsoft.TeamFoundation.WorkItemTracking.WpfControls.WpfControlFactory.CreateControl(String fieldName, String preferredControlType, String fallbackControlType, StringDictionary properties)
   at Microsoft.TeamFoundation.WorkItemTracking.WpfControls.WpfFormRenderer.CreateControl(FormElement element)
   at Microsoft.TeamFoundation.WorkItemTracking.WpfControls.WpfFormRenderer.RenderCollection(Grid panel, FormElementCollection collection, Int32& currentCol)

The user has the rights the view the content on web interface. The behavior is not reproducable with other versions of Visual Studio 2017 (Premium, Enterprise etc.) I tryed to workaround the issue by copying the missing dll (Microsoft.VisualStudio.QualityTools.Common.dll) from a Visual Studio 2017 Enterprise installation of a diffrent machine to following folders of the Test Edition installation, but not helped:
•Common7\IDE\CommonExtensions\Microsoft\TestWindow
•Common7\IDE\Extensions\TestPlatform\TestHost
•Common7\IDE\PublicAssemblies
•Common7\IDE\ReferenceAssemblies\v2.0

Please let me know, how can be this issue solved.

**Comment by TerryGLee** [comment]
@Kis-Janos-Zoltan Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) venue to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Kis-Janos-Zoltan** [comment]
Dear Terry G. Lee,

thank you for your email and recommendation.
unfortunately I cannot use the "Report a problem" feature of Visual Studio,
because our corporate network do not have direct internet access and
therefore the report form has trouble reaching visual studio developer
community servers through firewalls.
I tried to submit my issue on developercommunity.visualstudio.com, but
there is the same description like you sent me.

Do you know, how can I access the submit page on web?

Regards,
János

P.S.: I also submitted this problem on:
https://superuser.com/questions/1422839/visual-studio-2017-te-filenotfoundexceptionmicrosoft-visualstudio-qualityto

Terry G. Lee <notifications@github.com> ezt írta (időpont: 2019. ápr. 8.,
H, 19:13):

**Comment by Kis-Janos-Zoltan** [comment]
Finally I was able the workaround the issue. 

Setting the registry value "EnableLog" DWORD to 1 under
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Fusion
provided more details about the problem in the fusion log, in particular the path of the assembly (C:\Program Files (x86)\Microsoft Visual Studio\2017\TeamExplorer\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer):
> === Pre-bind state information === LOG: DisplayName = Microsoft.VisualStudio.QualityTools.Common, Version=15.0.0.0,
> Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a  (Fully-specified)
> LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual
> Studio/2017/TeamExplorer/Common7/IDE/ LOG: Initial PrivatePath = NULL
> Calling assembly : Microsoft.TeamFoundation.TestManagement.Controls,
> Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.

In ActivityLog.xml were several download attempts logged for Microsoft.VisualStudio.QualityTools.Resource.DLL
I took the first one (which was the same as in Fusion Log):

> C:\Program Files (x86)\Microsoft Visual
> Studio\2017\TeamExplorer\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team
> Explorer

and copyed following three missing dlls there:

> Microsoft.VisualStudio.QualityTools.Common.dll
> Microsoft.VisualStudio.QualityTools.Resource.dll
> Microsoft.VisualStudio.QualityTools.Vsip.dll

After a Visual Studio restart all content of the test case work item was loadad correctly.

**Comment by gewarren** [comment]
@Kis-Janos-Zoltan Thanks for letting us know you found a resolution.
