### ISSUE TITLE
Clarify Activation Key Changes for VS2019

### ISSUE THREAD

**Issue by nzubair** [MicrosoftDocs/visualstudio-docs#3022]
> You can apply your product key programmatically as part of a script that is used to automate the deployment of Visual Studio.

One scenario for creating a deployment script is to distribute Visual Studio to multiple machines/users via something like SCCM. In the past, we've used activation keys from Volume Licensing portal as part of the deployment script. 

However, it seems that activation keys are no longer being made available via Volume Licensing portal for VS2019. Instead, the keys are present with the individual subscriptions. Which makes it rather difficult to create a single redistributable package. Each developer, either needs to obtain the key from their subscription or sign-in to Visual Studio with their subscription account.

This change should be clarified in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11e2b93a-e89d-42ce-23d7-4cf85f47ba25
* Version Independent ID: 4083c0d5-c871-ef24-d11c-b6ec1adbb571
* Content: [Automatically apply product keys - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/automatically-apply-product-keys-when-deploying-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@nzubair Thanks for your feedback; we'll investigate, report back, and update the documentation as necessary.

**Comment by castellcoch** [comment]
I have the same issue. How do we create a single redistributable package for installation to classrooms without a volume license key?

**Comment by castellcoch** [comment]
As described in VLSC, the product keys for Visual Studio subscriptions are now "found in each individual subscription" - so what is the point of enterprise deployment tools described on this page?

**Comment by ornellaalt** [comment]
Hi @nzubair and @castellcoch, the information in the document is correct in that "You can apply your product key programmatically as part of a script that is used to automate the deployment of Visual Studio." Keys obtained via the Volume Licensing portal function equivalently to the keys found in subscriptions and can be used interchangeably. If you have feedback about the product, please submit it in the forum [here](https://developercommunity.visualstudio.com/spaces/8/index.html) for review by the engineering team.
