### ISSUE TITLE
Documentation bug certificates for offline environments

### ISSUE THREAD

**Issue by ChristianHaefner** [MicrosoftDocs/visualstudio-docs#3023]
Documentation [https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-certificates-for-visual-studio-offline.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-certificates-for-visual-studio-offline.md) states for "Visual Studio 2017 version 15.8 Preview 2 or later" that vs_installer_opc.RootCertificate.cer should be installed. 

After downloading VS2017 15.9.11 offline, only manifestCounterSignRootCertificate.cer, manifestRootCertificate.cer and vs_installer_opc.SignCertificates.p12 are located in subfolder "certificates", so mentioned vs_installer_opc.RootCertificate.cer is not available.

**Comment by TerryGLee** [comment]
@ChristianHaefner Thanks for letting us know; we'll investigate and report back.

**Comment by TerryGLee** [comment]
@ChristianHaefner It looks like you might be using an older version of the Visual Studio bootstrapper. If you update your layout with the most current bootstrapper for Visual Studio 2017 version 15.9.15, the correct certificates should be populated. If this doesn't do the trick, let us know by using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
