### ISSUE TITLE
Missing browse button in add reference

### ISSUE THREAD

**Issue by AliSafieddine** [MicrosoftDocs/visualstudio-docs#3024]
I cannot add any reference because the browse button is missing in add reference! what is the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284369-f16f-2748-2a55-8cd24a06b940
* Version Independent ID: f7b0c577-b584-98dc-90a2-4efcf095b35d
* Content: [Add references in the Reference Manager - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@alisofi123 Thanks for your inquiry; we'll investigate and report back.

**Comment by gewarren** [comment]
@alisofi123 What kind of project are you trying to add a reference to? Can you add a screenshot?

**Comment by wtilton** [comment]
I have a .NET Core 2.1 class library project and I'm missing the Assemblies, Universal Windows, COM tabs. I was mainly looking for the assemblies tab and am totally stumped why it would be missing.

**Comment by gewarren** [comment]
@wtilton In .NET Core projects you add dependencies as NuGet packages. For more info, see https://docs.microsoft.com/en-us/dotnet/core/tools/dependencies. You can also use the NuGet Package Manager UI.

**Comment by gewarren** [comment]
Closing due to lack of further info about the missing Browse button. @alisafieddine if the problem persists, to make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by ortymd** [comment]
Actually, I'm missing Browse button as well (in a C++ project). If "Browse" is avaliable only for certain types of projects, please specify explicitly which one.

**Comment by TerryGLee** [comment]
Related to https://github.com/MicrosoftDocs/visualstudio-docs/issues/5165; we'll pursue the issue there.

**Comment by didiersalle** [comment]
I still have the issue in VisualStudio 2022 on windows10, for a C++ project. It is supposed to be fixed on VS2022 ?

**Comment by gewarren** [comment]
It looks like the Developer Community work item was closed as low priority: https://developercommunity.visualstudio.com/t/Add-Reference-is-missing-browse-tab/181732?ftype=problem&q=browse+button+add+reference+c%2B%2B

**Comment by didiersalle** [comment]
Is there at least a workaround ?
