### ISSUE TITLE
No info on Code Cleanup and Roslyn analyzers

### ISSUE THREAD

**Issue by tillig** [MicrosoftDocs/visualstudio-docs#3027]
The documentation on this page says Code Cleanup "will format the code and apply any code fixes as suggested by the current settings, .editorconfig files, or Roslyn analyzers." The fixes available to run only appear to be based on current settings or .editorconfig and do not include Roslyn analyzer fixes. Following the link to "Roslyn analyzers" takes you to a page that explains what Roslyn analyzers are, not how to hook them up to Code Cleanup.

How do you get Code Cleanup to run Roslyn analyzer fixes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6ebefd-fcc0-7e65-6450-c5908dbb61f8
* Version Independent ID: 83656699-f59b-5c22-94ad-bb2c8d58b2ae
* Content: [What's new in Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2019?view=vs-2019#code-cleanup)
* Content Source: [docs/ide/whats-new-visual-studio-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/whats-new-visual-studio-2019.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@tillig Thanks for your inquiry; I'll investigate and report back.

**Comment by gewarren** [comment]
@tillig I think that Roslyn analyzers may have been mentioned here because VS has built-in Roslyn analyzers (and code fixers) that are used to format a document according to the text editor settings and/or .editorconfig file settings. I think that "Roslyn analyzers" should probably be removed from that sentence. See this [FAQ question](https://docs.microsoft.com/en-us/visualstudio/code-quality/analyzers-faq?view=vs-2019#roslyn-analyzers-versus-editorconfig) about Roslyn analyzers and editorconfig.

**Comment by tillig** [comment]
Agreed, it's somewhat confusing. If you don't remove it, I might recommend clarifying it by calling them "Visual Studio built-in Roslyn analyzers" to avoid confusion with analyzers that can be added from NuGet packages.

Of course, now I should probably file an enhancement request to allow Code Cleanup to hook into NuGet-based analyzers. :)

**Comment by TerryGLee** [comment]
@tillig Thanks again for your feedback; we appreciate your helping us improve our documentation. (@gewarren Thanks for your input, too.) I have removed the reference to Roslyn analyzers, and am closing this issue now.
