### ISSUE TITLE
[File nesting] Empty examples?

### ISSUE THREAD

**Issue by NetherGranite** [MicrosoftDocs/visualstudio-docs#3028]
![image](https://user-images.githubusercontent.com/5344234/55746710-a2861080-59f7-11e9-98c7-7f38f59a16ce.png)

These examples look empty. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019#feedback)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by TerryGLee** [comment]
@NetherGranite To verify, is this the page that you are referring to? 

[Customize file nesting in Solution Explorer](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019)

**Comment by NetherGranite** [comment]
> @NetherGranite To verify, is this the page that you are referring to?
> 
> [Customize file nesting in Solution Explorer](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019)

Oops, I totally forgot to link it. Yes, that's the page.

**Comment by gewarren** [comment]
@AngelosP are the examples missing something, or is the following syntax correct?

```
"dependentFileProviders": {
   "add": {
      "addedExtension": {}
      "pathSegment": {}
   }
}
```

**Comment by AngelosP** [comment]
@AntonPiksunov

**Comment by NetherGranite** [comment]
@gewarren I figured out how to add that Document Details section for linking this issue to the page. Should I remove the [File Nesting] tag in the title?

**Comment by AngelosP** [comment]
I don't see anything wrong with the documentation. Was something tried out and didn't work as documented? If so, please share the repro steps and I'll have somebody from the team take a look.

**Comment by gewarren** [comment]
Nothing to fix here so closing the issue.

**Comment by NetherGranite** [comment]
@AngelosP 

> I don't see anything wrong with the documentation.

For the first one, how does

```
"dependentFileProviders": {
   "add": {
      "addedExtension": {}
   }
}
```

cause _file.html.css_ to be nested under _file.html_?

For the second one, how does

```
"dependentFileProviders": {
   "add": {
      "pathSegment": {}
   }
}
```
cause _jquery.min.js_ to be nested under _jquery.js_?

I'm pretty certain these examples are missing the actual rules.

**Comment by NetherGranite** [comment]
@gewarren I just noticed that this is a duplicate of #2271.

**Comment by gewarren** [comment]
@NetherGranite Thank you for noting that. I'll update the docs to be more explicit about what's going on for those two examples.
