### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by omahena** [MicrosoftDocs/visualstudio-docs#3033]
Have you tested these instructions recently?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f33eba-a747-c57b-02e3-853d2a8a5c3b
* Version Independent ID: 1ddd9492-f5b1-d0ae-b813-c3838452a17a
* Content: [Install And Configure Tools to Build using iOS - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios?view=vs-2017#feedback)
* Content Source: [docs/cross-platform/install-and-configure-tools-to-build-using-ios.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/install-and-configure-tools-to-build-using-ios.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@omahena 
I think the instructions were written about three years ago, and last updated almost a year ago. Where did you run into trouble?

**Comment by omahena** [comment]
@corob-msft
Hi Colin,
When I look at vcremote it seems to me it is implemented in such a way that I am not surprised it stops working in a few months due to changes in all of the dependencies maintained by other people. Add to this the pace of Apple and all the changes they might be introducing... Although I don't think I have spotted any obvious issues caused by Apple. It does seem strange that the VS generated XCode projects are for XCode 3.2 or something like that and now Apple released XCode 10.2... I suppose the project files are XCode 3.2 compatible to allow compatibility with as many XCode versions as possible.

Where did I run into trouble? There is trouble pretty much from the get-go and throughout the deployment procedure as well as with the product itself. Starting with version of node, then brew comes with various outdated modules that fail to work (ios-webkit-debug-proxy, ideviceinstaller, libimobiledevice, usbmuxd, ....) after that starting to push code to the mac machine doesn't work and you have to pair and re-pair it to finally get it to work. Then there are missing settings in visual studio for the code signing part. Then the iOS static library project doesn't have the remote machine tools in the context menu of the project file and you have to delete the .desc files on Windows and timestamps on the Mac system to tickle it into submission. Then unpacking of ZIP files with the source code pushed from VS doesn't work and vcremote kept crashing. I had to debug and fix the source code of vcremote and make sure the zip file stays on the filesystem long enough so that it can be decompressed. Then if you have a little more than a hello world project the sync mechanism is overwhelmed with syncing the files and building takes ages (I am tempted to somehow cripple the sync mechanism and add a rsync call in the pre-compile stage like I had to do with the Unix remote builds... don't ask...).

I am sure I stopped seeing some of the problems after I got so used to the workarounds I use to work around them. Oh, right! Debugging iOS apps from visual studio simply never worked for me. I figured out how to create several .xcconfig files for additional XCode project targets to tweak settings and allow compiling and debugging directly from XCode. I can survive with debugging from XCode. Although I must say that after more than 20 years of PC and Unix keyboards Mac keyboards and keyboard shortcuts are **tough** to get used to...

I filed a couple of bug reports on the subject of problems in vcremote about a year ago and... Well... Not much has happened about the issues.

From the point of view of documentation also the code signing instructions had me running in circles for a day or so before I found an alternative. I think Apple may have changed how they do stuff.

I would suggest that the VS team gets some Apple hardware (or a hackintosh VMWare) and install Mojave with XCode from scratch. Then try to follow the instructions and compile the Visual Studio Cross Platform project that generates C++ code for iOS, Android and Windows. Problems should become apparent rather quickly. I don't think I was... Holding it **that** wrong... 😃 Also the Internet is littered with posts about people having the same type of problems. It may be smart to repeat this installation test every couple of months if vcremote remains to be implemented in Node.

Visual Studio was my primary development tool for over two decades. There is lots of goodness in there. And I was hoping it would remain my primary workhorse. 

I was even presenting Visual C++ at MS Developer Days in three countries when 6.0 came out. And when I saw support for Cross platform development in Visual Studio 2017 I thought it was a really excellent idea and was really excited to try it. The implementation of it is... Ugh... To be polite... A little disappointing. But I managed to kind of make it work for me. But I use a lot of Android Studio and XCode on the side. Sometimes when Visual Studio with ReSharper starts to feel real slow and CPU won't drop under 80%... I have to admit I do most of my coding in Android Studio and use Visual Studio just as a build tool and debugger for Unix and Windows. 😞 

I have a feeling MS also understands the potential of Cross platform development as I often see it mentioned in visible places. I for one would really appreciate it if the VS team would find the time to dust off the cross platform solution a bit. The implementation of the Unix cross platform development part is a LOT better than iOS but the ssh sync quickly becomes unusable for any real work.

I appreciate all the work that must have gone into this. And I realise my writing exceeded the area of responsibility of the VS-docs team but I hope my feedback can be shared with the relevant people on other team(s).

**Comment by corob-msft** [comment]
@omahena 
While I can address docs issues like updating the installation procedures to use new paths, URLs, version numbers, and reflect product UI changes, I can't do much about how the product works (or doesn't). For that, I'm going to strongly suggest you take what you wrote here, and repeat it in an issue on the C++ [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) site. You can use the feedback controls inside the VS IDE (either the one just left of the Quick Launch control, or the menu **Help** > **Send feedback**), to get there directly. It doesn't sound like one of the usual repro case submission scenarios could apply here, so skip that step if it asks for one. After a first look by a layer of triage people, these issues go right to the product team. We use it for all issues, including ones from other groups at Microsoft - there's no privileged internal short-circuiting of the process. It's your best bet for a real solution, if one is going to happen at all. If doc changes are called for, it will come back around to me.

To set expectations, I know the iOS solution hasn't gotten much attention from the product team, because Apple licensing requirements limited it to essentially running Xcode and your iOS device or simulator by remote control. As far as iOS is concerned, the C++ Mobile Development component exists mainly as a way of keeping your common C++ library code on one platform. It never saw adoption numbers like the Linux and IoT solutions, which see more active development. Maybe you can prod some people into action.

**Comment by omahena** [comment]
@corob-msft
Thank you for getting back to me. Updating the documentation would already be a huge step. I understand you write documentation and not code and that there is a process behind working out the issues. It would be worrying if there were no well defined process behind communication and issue solving at MS.

Apple is indeed rather close minded and I have a feeling that will bite them back in the end. Making developers suffer and cough up a pretty penny to be able to target their crowd amid stiff competition is short sighted. After Apple extorted 100EUR/year from me just for the privilege of targeting my test iOS device I for one decided I will never buy a physical product from Apple first hand. It's a matter or principle. But I digress.

The result of Apple's licensing requirements is indeed pretty much remote controlling XCode. But the point of it all is that it does help developers to use a familiar environment  (Visual Studio) to not just have one single high performance source code for all targeted platforms, but also one tool to do it all.

Thank you for your time and your feedback targeting suggestions. Let me know if you would find my (partial) notes on how to kind of bring vcremote to life useful. But I think they need to reach you  through the triage teams. I'll try some more prodding...

**Comment by WindowsNT** [comment]
It would be best to pay Apple a license and make it working correctly. See my other issue I just posted.

**Comment by corob-msft** [comment]
Our documentation was updated in May, and while everything involved is a moving target, it was working when I tried it using the Simulator on my MacBook. I'm closing this issue rather than leaving it to hang out.
