### ISSUE TITLE
Cannot Connect to Access Database

### ISSUE THREAD

**Issue by stevelhunt** [MicrosoftDocs/visualstudio-docs#3034]
Using Visual Studio 2019, I attempt to establish a connection to an Access .accdb file and I get a 
"Unrecognized Database Format" error.

Why does this have to be so difficult?

**Comment by TerryGLee** [comment]
@stevelhunt I'm sorry to hear that you're experiencing an issue with using the product. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
