### ISSUE TITLE
Interface is not a contract

### ISSUE THREAD

**Issue by FrankHileman** [MicrosoftDocs/visualstudio-docs#3036]
It is better to reserve the word "contract" for preconditions, postconditions, and invariants, none of which are defined by an interface.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f01b6ea-8d81-6903-0e28-dd6c369ce808
* Version Independent ID: 5376ea88-e452-77e6-600f-bc81a1377bf5
* Content: [CA1040: Avoid empty interfaces - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1040-avoid-empty-interfaces?view=vs-2019)
* Content Source: [docs/code-quality/ca1040-avoid-empty-interfaces.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1040-avoid-empty-interfaces.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@FrankHileman Thanks for your feedback; we'll take a look at this.

**Comment by BillWagner** [comment]
I don't think any change is warranted here.  The [C# Language Specification](https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/interfaces) defines an interface as follows:

> An interface defines a contract. A class or struct that implements an interface must adhere to its contract. 

@FrankHileman is correct that "contract" can be used to mean pre-conditions and post-conditions. Both definitions are correct, and I think most developers can determine the correct use from the context.

**Comment by gewarren** [comment]
Thanks for the nice explanation @BillWagner - closing.
