### ISSUE TITLE
No Preview Channel

### ISSUE THREAD

**Issue by memark** [MicrosoftDocs/visualstudio-docs#3039]
There is no Preview Channel (and not 2 channels as mentioned above). In fact there are 4 channels:

Stable
Beta
Alpha
XCode 10.2 Previews

---
#### Dokumentinformation

⚠ *Redigera inte det här avsnittet. Det krävs för docs.microsoft.com ➟ länkning till GitHub-problem.*

* ID: 19507b70-367f-e7dc-88b8-fd8dc6881cf1
* Version Independent ID: 8a6e3e13-0ae2-e98a-2726-c791c69385d8
* Content: [Install a preview or update for Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/sv-se/visualstudio/mac/install-preview?view=vsmac-2019)
* Content Source: [mac/install-preview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/install-preview.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by sclyde** [comment]
Seeing the same. Also assuming based on this article that there's no way to run the preview side-by-side with the current version like you can on Windows? Is it at least as easy as switching channels and updating again to switch back and forth?

**Comment by conceptdev** [comment]
Thank you both for your feedback.

@memark historically there were only ever two channels available. Visual Studio for Mac recently introduced the ability to offer additional, time-limited channels for beta testing (eg. the Xcode Preview channel). The page will be updated to mention this - however the specific list of additional channels may change over time.

@sclyde it was possible to run the Visual Studio 2019 for Mac _Preview_ side-by-side with the previous (2017) version; but you're correct, it's not possible to run different 'channels' side-by-side. Generally you can switch between them easily, although if you are also using Visual Studio 2019 on Windows (and sharing this Mac), the versions should be "in sync" for your iOS projects to work correctly on Windows. The IDE will warn you if it notices a difference.

**Comment by asb3993** [comment]
@memark We updated the names of the channels in Visual Studio 2019 (8.XX series) to better reflect how we are making releases. If you're seeing these channels, you are on Visual Studio 2017. You can either use the dropdown menu to change to 2017 docs, or you can can update to Visual Studio 2019 by using the updater or by installing it from here: https://visualstudio.microsoft.com/vs/mac/
