### ISSUE TITLE
Snappoints not being hit

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/visualstudio-docs#3041]
I went through all the steps to get snapshot debugging working but no span points are appearing. Here's some facts:

- .NET 4.6.1
- Azure App Service B1
- Code has not changed since published
- Snapshot debugger is attached
- Hexagons are solid purple
- "Diagnostic Tools" window has event "Collection Started"

I keep reloading the site, but no snappoint events are ever added to the "Diagnostic Tools" window

How can I figure out what is going wrong?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0557fd8-48c5-bbee-04b9-27baeb8858e6
* Version Independent ID: 2b397dd4-cfd5-78a8-9256-d1fb981b30bf
* Content: [Troubleshooting snapshot debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-apps-troubleshooting?view=vs-2019)
* Content Source: [docs/debugger/debug-live-azure-apps-troubleshooting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-live-azure-apps-troubleshooting.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@MisinformedDNA  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem. Thx!

**Comment by MisinformedDNA** [comment]
Will do.
