### ISSUE TITLE
SQL Server Integration Services - SSIS

### ISSUE THREAD

**Issue by Rob-Schook** [MicrosoftDocs/visualstudio-docs#3042]
The SSIS entry links to an official Microsoft blog site, which hasn't been updated in 2 years.  The last entry I have is from 2017.  Why link to an obviously outdated page that is apparently dormant.

Also the link to the "Download SSDT Tools" states that Integration Services support can be download from the extensions menu in Visual Studio, however, there is no Integration Services extension available to download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3315d1-e6d3-e86d-9cce-1ff9ce0fc482
* Version Independent ID: ae3fd143-bf0b-4cfe-bcad-557eb41fdc2c
* Content: [Port, migrate, and upgrade projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2019#feedback)
* Content Source: [docs/porting/port-migrate-and-upgrade-visual-studio-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/porting/port-migrate-and-upgrade-visual-studio-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Rob-Schook Apologies for this. You're right, the SSDT blog is outdated. I'll investigate to determine future blog plans for both SSIS and SSDT, and report back. 

Meanwhile, I added a link to another page: [Download and install SQL Server Data Tools (SSDT) for Visual Studio](https://docs.microsoft.com/sql/ssdt/download-sql-server-data-tools-ssdt), which includes more current information (although not yet for SSIS). 

Please know that we're aware of this and should have more info soon, per a related GitHub Issue #[2592](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2592).

(@dnethi FYI)

**Comment by dnethi** [comment]
SSIS extension should be coming out very soon .. please stay tuned..

**Comment by framm** [comment]
@dnethi but why update the documentation as of 04/05/2019, (https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017) and state that SSIS is available for 2019 - when it's not?

**Comment by timchenyx** [comment]
SSIS is available now. https://marketplace.visualstudio.com/items?itemName=SSIS.SqlServerIntegrationServicesProjects&ssr=false#overview

**Comment by TerryGLee** [comment]
We've added the SSIS Marketplace link to the [Project migration and upgrade reference for Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-upgrade-visual-studio-projects-2019?view=vs-2019) page. I am closing this issue as the SSDT/SSIS documentation updates to this page are now complete. Thanks everyone for your feedback!
