### ISSUE TITLE
Remove multiple blank lines

### ISSUE THREAD

**Issue by MichalPetr** [MicrosoftDocs/visualstudio-docs#3043]
I would like remove multiple blank lines with VS2019 code cleanup. Is it posible create/set this rule?

**Comment by gewarren** [comment]
@kendrahavens Do you know?

**Comment by kendrahavens** [comment]
No, there is currently no code style rule for enforcing no multiple blank lines. If this is something you are interested in I'd encourage you to open an issue on our repository! https://github.com/dotnet/roslyn/issues
