### ISSUE TITLE
Which type of certificate is required?

### ISSUE THREAD

**Issue by holterandreasb** [MicrosoftDocs/visualstudio-docs#3044]
Do I need a specific type of certificate in order to get a properly signed VSIX file? I created different certificates with our internal CA but no matter which certificate I'm using with VSIXSignTool, upon installing the extension, i get the info that the digital signature uses an invalid certificate. Anybody got a solution to that? Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf20479-c8a0-eb31-45f8-3599c759b4d6
* Version Independent ID: f9ca0232-6aa0-543b-2b37-6685e69cfdb9
* Content: [Signing VSIX Packages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/signing-vsix-packages?view=vs-2019#feedback)
* Content Source: [docs/extensibility/signing-vsix-packages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/signing-vsix-packages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by holterandreasb** [comment]
I found the solution, you need a Code Signing certificate. This post saved my day in terms of how to create your own Code Signing certificate on an internal CA:
https://blogs.msdn.microsoft.com/emeamsgdev/2014/06/10/how-to-create-and-use-a-code-signing-certificate-for-clickonce-vsto-applications-using-active-directory-certificate-services/

**Comment by TerryGLee** [comment]
@holterandreasb Thanks for your inquiry, and also for your response with the answer! (@gregvanl FYI)

**Comment by gregvanl** [comment]
@madskristensen Should we update the topic?

**Comment by madskristensen** [comment]
That's not a bad idea. Also, I think we retired SHA1 certificates and now require SHA2 so that would be worth mentioning too

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
