### ISSUE TITLE
Opening the library project by Visual studio loads few projects

### ISSUE THREAD

**Issue by saqw3r** [MicrosoftDocs/visualstudio-docs#3047]
Environment:
- Windows 10
- VS2017 Community Edition/ VS2019 Community Edition

Loading a single project leads to load a few projects. I still don't know how come that it continue happening?

**Comment by TerryGLee** [comment]
@saqw3r Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
