### ISSUE TITLE
Xcode version

### ISSUE THREAD

**Issue by sjong13** [MicrosoftDocs/visualstudio-docs#3048]
requirements state "Xcode 11.0 or above". I believe this is a typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3989ef3-79d0-03b7-6a17-749ee96b9550
* Version Independent ID: 3a66757e-649d-6415-ff5e-00d628eb17f6
* Content: [Install Visual Studio 2019 for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/installation?view=vsmac-2019#feedback)
* Content Source: [mac/installation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/installation.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Oops, you're right (unless we can see into the future 😉). Fixing it now, thanks!
