### ISSUE TITLE
Step 4 graphic needs numbers overlaid to reflect references in the paragraph above the image

### ISSUE THREAD

**Issue by HoundCat** [MicrosoftDocs/visualstudio-docs#3049]
While the image displayed for step 5 contains numbers overlaid for references made in the text description, step 4 references windows in the IDE with numbers though the image fails to show the numbers in the windows that are referenced above the image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3adec9eb-97b5-4f9f-77d6-a9eb9130ed10
* Version Independent ID: 90fb8ff4-4ccd-98c1-92c2-02a33252c681
* Content: [Python in Visual Studio tutorial step 1, create a project](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-01-create-project?view=vs-2019#feedback)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-01-create-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-01-create-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Thank you for the feedback, the image has been updated in the topic.
