### ISSUE TITLE
Missing information about "Unwind the call stack on unhandled exceptions" option

### ISSUE THREAD

**Issue by amali8** [MicrosoftDocs/visualstudio-docs#305]
On https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-csharp

> Editing code after an unhandled exception, when the "Unwind the call stack on unhandled exceptions" option is not selected.

It is unclear where this option is located, and it also seems to not exist in VS 2017.

**Comment by Mikejo5000** [comment]
Looking at this issue

**Comment by Mikejo5000** [comment]
Removing item; this option is no longer present in Visual Studio

**Comment by Mikejo5000** [comment]
Verified removed live
