### ISSUE TITLE
Can't publish a dotnetcore2.2 app to a folder for Raspberry Pi

### ISSUE THREAD

**Issue by daveyostcom** [MicrosoftDocs/visualstudio-docs#3053]
Lots of articles about Raspberry Pi talk about publishing to a folder then copying the folder to the RPi. But I see no Publish in any menu. This page says the project seems to be saying that the project has to be ASP. Why is that?

VS for Mac 8.0.2 (build 23)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9d2be7-406b-0422-c49c-d62f972419e0
* Version Independent ID: 127bdbb0-a2ce-dd7c-99b7-1ee55d691e48
* Content: [Publish to a folder - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-folder?view=vsmac-2019)
* Content Source: [mac/publish-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-folder.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by asb3993** [comment]
@sayedihashimi do you have insight on this?

**Comment by sayedihashimi** [comment]
Hi @daveyostcom, we have support for publishing ASP.NET **Core** projects to a folder. If you're working with an ASP.NET project targeting the standard .net framework then that feature may not be available. The doc you are following looks like the correct doc.

If you are not seeing that option then [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019). I believe there is no doc issue, so I believe we can close.

**Comment by daveyostcom** [comment]
Then can someone move this over to the VS project? For embedded use we need to be able to publish to folder, even if the project is not ASP. Thanks.

**Comment by sayedihashimi** [comment]
What you mean by `Then can someone move this over to the VS project`?

> For embedded use we need to be able to publish to folder, even if the project is not ASP

We support Publish to Folder for ASP.NET Core projects, but not ASP projects. We do not have any plans to bring this functionality to Visual Studio for Mac at this time.

**Comment by gkarabin** [comment]
How about vanilla .NET Core projects (which is what I believe the OP is asking about for embedded use, e.g., IoT)? VS for Mac is unable to publish those.  The "Publishing to folder..." tool reports:

dotnet publish
Required argument missing for option: --configuration
Required argument missing for option: --output

It's surprising to me that those options are marked as required - https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21#options say that they are both optional.  Additionally, there is a Configuration element in the .pubxml file that I'm trying to publish (created in VS2019 on Windows)  but its value is not being respected.

If anyone notices this, is it worth my time to file an issue or feature request?

**Comment by daveyostcom** [comment]
I discovered that a simple [`rsync`](https://rsync.samba.org) command does the trick and does it as efficiently as possible.
