### ISSUE TITLE
offline installer not working

### ISSUE THREAD

**Issue by oguzhankahyaoglu** [MicrosoftDocs/visualstudio-docs#3054]
I tried installing certificates and running vs_community.exe with different cache layout parameters, non of them worked. 
I solved the issue running vs_setup.exe in cache folder, instead of vs_community.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@oguzhankahyaoglu Thanks for letting us know. @tydunkel FYI.

**Comment by bqstony** [comment]
Same here, try to install 16.0.1 from .\chache\vs_setup.exe --layout C:\Temp\VS2019\chache --add Microsoft.VisualStudio.Workload.ManagedDesktop --add ..... --lang en-US
But trys to download from internet

i have to started the ui with C:\Temp\VS2019\chache\vs_setup.exe

**Comment by TerryGLee** [comment]
@oguzhankahyaoglu @bqstony Thanks again for this information. If you wouldn't mind, we'd really appreciate if you would use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem. Plus, others can view it and upvote it, too.

Meanwhile, I'll investigate whether or not we need a documentation update.

**Comment by LowJack187** [comment]
Damit Terry, How the hell are you supposed to use the tool if it won't install? Do something useful and program the Send Feedback about: This Product button to have the functionality of you passing the buck!

**Comment by TerryGLee** [comment]
@LowJack187 This venue is meant for [documentation feedback](https://docs.microsoft.com/visualstudio/ide/feedback-options?view=vs-2019#improve-the-documentation), although we still accept product feedback, as sometimes the product issues reported here provide us with information that we can use to improve our documentation. However, when a solution must be provided for a product issue, we re-route it to the proper support venue (typically, the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool, where you can include diagnostic information in your feedback that helps Visual Studio engineering teams diagnose and fix issues much more effectively). 

That being said, please know that often, one can use the Visual Studio Installer to access the Report a Problem tool. However, if that route won't work, here are a few more ways to get support for a product issue:

- Connect with us by using our [**live chat**](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

Please note: I'm closing this product-specific GitHub Issue now. If you are still experiencing a problem with an installation, please consider using one of the previously mentioned methods for obtaining support. And if you have feedback on how we can improve our documentation, please let us know by opening a new GitHub Issue with that information.

Thanks,
~ Terry

**Comment by allen-sparks** [comment]
I did live chat with customer service. He tried to do a partial install for c++ and it didn't work for him either. He suggested I do the entire layout
> vs_community.exe --layout c:\vslayout --lang en-US

It took forever and I had to use 7zip to split the volume when using a usb drive but it worked.
Admins please update or remove steps that don't work, its not helpful to constantly direct us to customer service
