### ISSUE TITLE
Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2).	

### ISSUE THREAD

**Issue by harshamodini** [MicrosoftDocs/visualstudio-docs#3056]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5724c8bf-466a-4d2e-86ce-8c4a21638a37
* Version Independent ID: 0e95fb87-b584-25dc-16a8-6c5936ac9368
* Content: [C26451 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26451?view=vs-2019)
* Content Source: [docs/code-quality/C26451.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26451.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@harshamodini did you have a specific question or issue concerning this topic?
