### ISSUE TITLE
How do we get an AsyncServiceProvider from a window component

### ISSUE THREAD

**Issue by deadlydog** [MicrosoftDocs/visualstudio-docs#3058]
As per [this documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background?view=vs-2019) you should no longer be using `GetService` in your extensions initialization code. Instead, we are supposed to use `GetServiceAsync`, which is provided by an `IAsyncServiceProvider` instead of the older `IServiceProvider`. However, none of the controls I am dealing with provide an `IAsyncServiceProvider`; they all still provide a `IServiceProvider`. e.g. [Microsoft.TeamFoundation.Controls.SectionInitializeEventArgs ](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/hh725322(v%3dvs.110)). For the Team Explorer controls (and other Visual Studio windows?), how can we get an IAsyncServiceProvider in order to have our extensions be supported by Visual Studio 2019+ without displaying a warning that they use a deprecated API. Should I not be using the Microsoft.TeamFoundations.Controls.dll that ships with VS 2019, but some other assembly instead? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29aaef6b-255a-a889-0118-f03f88df6d7c
* Version Independent ID: de72beb3-1138-776e-2c14-6f416d277dcd
* Content: [How to: Get a Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-get-a-service?view=vs-2019#feedback)
* Content Source: [docs/extensibility/how-to-get-a-service.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-get-a-service.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by BertanAygun** [comment]
Hi, the advise linked applies to asynchronous code paths such as async initiliazation of an AsyncPackage or initialization of async tool windows. In those cases, you should have a reference to IAsyncServiceProvider already. For example, the AsyncPackage base class itself implements IAsyncServiceProvider. 

For other async paths, that didn't have access to IAsyncProvider, it can be queried through IServiceProvider as a one time operation to allow remaining of service queries to be asynchronous.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
