### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by corradin** [MicrosoftDocs/visualstudio-docs#3059]
.\* matches a string of any characters
Should be:
.* matches a string of any characters

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dc6fcf-df9f-9d2a-5c6e-8da0f6925afc
* Version Independent ID: d0bf2cae-9b59-d537-7acb-7af5f560d8c1
* Content: [Customizing Code Coverage Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019#feedback)
* Content Source: [docs/test/customizing-code-coverage-analysis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/customizing-code-coverage-analysis.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@corradin Thanks for your inquiry. But for clarification, are you saying that this:
`.\* matches a string of any characters`
Should be this:
`.* matches a string of any characters`
(I used code markup so that the backslash would appear.)

**Comment by corradin** [comment]
Hi Terry, 
Your assumption is correct. I see now that my backslash vanished. Maybe I made a typo.

**Comment by TerryGLee** [comment]
@corradin I don't think you did; it's a markup "feature."  
As for the typo in the documentation, we'll review this and report back. 
Meanwhile, thanks for your feedback; we always appreciate it!

**Comment by gewarren** [comment]
@corradin Would you be interested in fixing this yourself? You can just click the Edit button on the top-right if you scroll back to the top of the page.

**Comment by lennartb-** [comment]
Seems to be fixed already?

**Comment by gewarren** [comment]
Nope, still there:

![image](https://user-images.githubusercontent.com/24882762/56820013-c28f3f80-67ff-11e9-8b30-b3ddfb80f294.png)

**Comment by lennartb-** [comment]
@gewarren My bad, misunderstood the typo. Created a PR to fix it.
