### ISSUE TITLE
Which launchsettings are used for each project

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/visualstudio-docs#3062]
If I select multiple projects I no longer get to pick the launchsettings for my ASP.NET Core projects, it just says Start. Is there a way of picking a particular launchsettings name to use across multiple webs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c932420b-6870-bfd6-d664-2db92053bfaf
* Version Independent ID: fde787e7-1307-5b2c-206e-e67657e80090
* Content: [How to: Set multiple startup projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-set-multiple-startup-projects?view=vs-2019)
* Content Source: [docs/ide/how-to-set-multiple-startup-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-set-multiple-startup-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Rick-Anderson Do you know the answer to this?

**Comment by Rick-Anderson** [comment]
Just edit your *ProjectName\Properties\launchSettings.json* file.

**Comment by phatcher** [comment]
@Rick-Anderson I have edited the launch settings for each project, the issue is once you are starting more than one project the drop down says "Multiple Projects", so there's no indication of what environment you are running against.

Each project seems to obey the last one set but this makes the inner loop awkward, to change you have to flip to each single project and change to the target, then go back and select the multiple start projects options.

May be change the select multiple options to show/change which launchsettings are used for each?

**Comment by Rick-Anderson** [comment]
This repo is to report docu issues.
To report Visual Studio problems
**Help > Send Feedback > Report a Problem**

![image](https://user-images.githubusercontent.com/3605364/52737321-27145f80-2f70-11e9-8eb0-828478541672.png)

**Comment by gewarren** [comment]
@phatcher From what Rick posted, it sounds like what you want to do isn't currently possible. To make a product suggestion, you can actually do that directly on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Look for the "Suggest a Feature" button:

![image](https://user-images.githubusercontent.com/24882762/50102736-a7218180-01da-11e9-9aaf-ea3a99ccd030.png)

When you suggest a feature on Developer Community, you can engage directly with the engineering team as they consider the suggestion. It also provides a way for other customers to upvote your suggestion.
