### ISSUE TITLE
Line counting seems off

### ISSUE THREAD

**Issue by corradin** [MicrosoftDocs/visualstudio-docs#3063]
"it is counted as one line". I don't think this is true. For example if I create the following class property:
private readonly IDictionary&lt;string, string&gt; myDictionary = new Dictionary&lt;string, string&gt;
{
     {"a", "apple"},
     {"b", "balloon"}
};
It is counted as 4 lines, while if I remove the second entry it is counted as 3 lines. I believe it should be counted as 1 line.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Code coverage testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019#report-in-blocks-or-lines)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@corradin It sounds like you are reporting an issue with code coverage functionality as opposed to a documentation issue. Is that correct?

**Comment by gewarren** [comment]
@AbhitejJohn Can you take a look at this feedback and let me know if the wording in the document about what's considered to be "one line" should be changed?

**Comment by singhsarab** [comment]
@corradin @gewarren 

The full line says
"If the test run exercised all the code blocks in any line of code, it is counted as one line"

Here the intent is to convey the following
"if there are more than one code blocks in a single line and all the blocks are covered, it is counted as one line."

@gewarren we should probably fix the wording if you think it is confusing.
/cc: @mayankbansal018 @cltshivash

**Comment by corradin** [comment]
The issue is not wording, but as @gewarren states code coverage. If I would create a large dictionary it will increase my coverage substantially, while I believe this should be minimal.

**Comment by gewarren** [comment]
@corradin Since this is a product issue or suggestion, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, you can engage directly with the engineering team while they address and fix the problem.
