### ISSUE TITLE
Missing topic for CA5368: Page does not set the ViewStateUserKey property in method OnInit

### ISSUE THREAD

**Issue by guitarzan** [MicrosoftDocs/visualstudio-docs#3067]
Running Microsoft.CodeAnalysis.FxCopAnalyzers version 2.6.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f935929-e6b1-d110-4d2f-8a4150a27755
* Version Independent ID: d4c2d5fd-b9e3-85fd-7d21-22cdb8c06f9d
* Content: [Code Analysis Warnings for Managed Code by CheckId - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-warnings-for-managed-code-by-checkid?view=vs-2019#feedback)
* Content Source: [docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-warnings-for-managed-code-by-checkid.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Mikejo5000** [comment]
Issue is captured now in MicrosoftDocs/visualstudio-docs#3479
