### ISSUE TITLE
More out of date documentation

### ISSUE THREAD

**Issue by Korporal** [MicrosoftDocs/visualstudio-docs#3068]
This is becoming endemic. First the assembly Microsoft.VisualStudio.DebuggerVisualizers.DLL didn't exist on my machine. So - as usual - I scanned the web only to find this is now a Nuget package. Next the publisher of the [package](https://www.nuget.org/packages/VSSDK.DebuggerVisualizers/) is a person's name "Sam Harwell" not "Microsoft" so I have no idea if this really is Microsoft code. Next at runtime the console app could not find Microsoft.VisualStudio.DebuggerVisualizers.dll and I had to manually set Copy Loacl to true for that assembly. 

I'm done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5d2403-0edc-8ee9-22f6-6ca370b40346
* Version Independent ID: d34a6007-354e-0bdb-3ad7-9f15a2cb56f2
* Content: [Write a visualizer in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2019)
* Content Source: [docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Retesting and updating docs.
Best thing is to browse to the DLLs. See #1620
