### ISSUE TITLE
Fail in vs_Community offline install with --remove

### ISSUE THREAD

**Issue by adibikar** [MicrosoftDocs/visualstudio-docs#307]
Fail with : "Error: parameter --remove". I am trying to install on my Windows 7 SP1. So I think I do not to need these following components. Why I am fail with this command?
`vs_Community.exe --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --remove Microsoft.VisualStudio.Component.Windows10SDK.15063.Desktop --remove Microsoft.VisualStudio.Component.Windows10SDK.15063.UWP --remove Microsoft.VisualStudio.Component.Windows10SDK.15063.UWP.Native --remove Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 --remove Microsoft.VisualStudio.Component.Windows81SDK --remove Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81 --layout E:\vs\vs2017 --lang en-US`

**Comment by gewarren** [comment]
@TerryGLee could you ask the product team about this?

**Comment by adibikar** [comment]
Thanks @gewarren , but I have solved this problem with I just install all those component. Because after googling I know that I must use Windows 10 SDK to update the c++ (latest version) for windows  that I use.
