### ISSUE TITLE
"Add" Button Greyed Out Visual Studio 2019

### ISSUE THREAD

**Issue by evanricard** [MicrosoftDocs/visualstudio-docs#3071]
Hey Microsoft, I want to add a symbol that will appear in the "Task List" window that says "DEBUG". It is my understanding we do this through the token symbol options window like mentioned above but I am not sure if it's working properly in 2019 or if it's just my own environment that is malfunctioning. Thanks! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1261884-8284-53f9-a325-15061bf897f8
* Version Independent ID: 4520c20f-86f6-5066-298b-d3d428901f87
* Content: [Use the Task List - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2019#feedback)
* Content Source: [docs/ide/using-the-task-list.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-the-task-list.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@evanricard This is working for me. The trick is that you have to enter a name and then Add becomes enabled. It's not a good design, I agree. I'll make this more clear in the document.
