### ISSUE TITLE
Query: Is there a staging/integration environment for marketplace?

### ISSUE THREAD

**Issue by ClydeDz** [MicrosoftDocs/visualstudio-docs#3072]
Similar to the [integration environment for NuGet](https://int.nugettest.org/), do we have one for the marketplace where we could deploy extensions and test it out instead of deploying straight to production?

Any other suggestions of setting up a pre-prod environment if the above isn't available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac223936-2fe5-45ea-bd78-656013f0d6e0
* Version Independent ID: fcae191e-6ea3-85ca-25a9-7cc5c32ca008
* Content: [Walkthrough: Publishing a Visual Studio Extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension?view=vs-2019)
* Content Source: [docs/extensibility/walkthrough-publishing-a-visual-studio-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-publishing-a-visual-studio-extension.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by madskristensen** [comment]
There is no official staging environment, but a lot of people are using the [Open VSIX Gallery](http://vsixgallery.com) for hosting CI builds

**Comment by ClydeDz** [comment]
Awesome, thanks!
