### ISSUE TITLE
"Break when value change" does show on VB.net 2019

### ISSUE THREAD

**Issue by Jean-Georges** [MicrosoftDocs/visualstudio-docs#3074]
I was all anxious to finally retrieve the good old feature that I like so much in VB6.  I am a lazy programmer, that feature was really an easy way to find the problem in a 34 years old code.
But it does not show in the Watch1.
Jean-Georges

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd6ebefd-fcc0-7e65-6450-c5908dbb61f8
* Version Independent ID: 83656699-f59b-5c22-94ad-bb2c8d58b2ae
* Content: [What's new in Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-2019?view=vs-2019#give-us-feedback)
* Content Source: [docs/ide/whats-new-visual-studio-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/whats-new-visual-studio-2019.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Jean-Georges Thanks for your feedback on Visual Studio 2019! However, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.

**Comment by gewarren** [comment]
@Mikejo5000 This is a debugging question - is there a way to break execution when a value changes in VB?

**Comment by Mikejo5000** [comment]
@Jean-Georges Hi, some features from VB6 are not available, and I'm not familiar with that one. However, it's possible that you can set a conditional breakpoint on an expression that will do the same thing. For the conditional expression, select "When changed"
![image](https://user-images.githubusercontent.com/11948536/56446933-65a10000-62ba-11e9-8ffe-2eb4d22b2048.png)

**Comment by TerryGLee** [comment]
@gewarren @Mikejo5000 Thanks for your additional help in providing an answer to this inquiry. @Jean-Georges We hope that the answer that was offered proves to be of help to you. Let us know if not. Meanwhile, I am closing this GitHub Issue. (Although, we can re-open it if need be. And you can still comment on the issue, even though it's closed. Last but not least - we appreciate your feedback! Thanks again for taking the time to provide  it.)

**Comment by protegesolutions** [comment]
A conditional breakpoint at a specific code location _isn't the same_ as breaking when a value changes anywhere in the code. It's pretty fundamental to want to do this as often it's difficult to discover exactly where the value change is occurring. This used to be available I'm pretty sure. But now, in its absence, you can spend hours trying to find the culprit.

I _still_ haven't been able to work out why changing a tab on a windows form changes the _SelectedIndex_ property on a Combo Box. If I could set a breakpoint on the _SelectedIndex_ value change, I'd be done in 5 minutes. _Please_ reinstate this - for all frameworks, not just Core.

**Comment by TerryGLee** [comment]
@protegesolutions Steve, thank you for your feedback. Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

If you discover an issue with the documentation, please open a new GitHub Issue to describe it and we'll address it there.
