### ISSUE TITLE
conversion error

### ISSUE THREAD

**Issue by srecov** [MicrosoftDocs/visualstudio-docs#3075]
Hi, 

an exellent article, however I am getting the following conversion error in line populating CollectionViewSource Resource, like "custViewSource.Source = context.Customers.Local;" :

Cannot implicitly convert type 'System.Collections.ObjectModel.ObservableCollection&lt; ....&gt;' to 'System.Windows.Data.CollectionViewSource'

I have populated Items source with ObservableCollection like 

"productDataGrid.ItemsSource= context.Products.Local;"

and it works. Could you suggest what I have done wrong. 
I am using W10, VS2019 and EF6.

Best Regards
Srečo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c0fa43-0ca5-9c86-f8c4-4b3eb7176250
* Version Independent ID: bb93e3ff-0d52-9e93-c3a8-545b16f03a30
* Content: [Create a simple data application with WPF and Entity Framework 6 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2019#feedback)
* Content Source: [docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by divega** [comment]
@srecov I am unable to repro this problem. I was able to follow the tutorial and I execute the program in step 8, and now I can see the first customer with its list of orders loaded into the user interface. 

I suspect your model or your code could be slightly off if you missed just a few step in the instructions. In particular, the text replacements to the Northwind_model.tt file is very error prone, and you have to be careful not to change other files. 

Could you try to start over and see if it works for you too?

**Comment by gewarren** [comment]
@divega Thanks for confirming there's not a problem with the document as written.

@srecov If you continue to have trouble after rechecking your work, here are a few options where you might consider asking for help:​

https://social.msdn.microsoft.com/Forums/vstudio
https://www.stackoverflow.com
https://www.reddit.com/r/VisualStudio/
