### ISSUE TITLE
RegularExpression is a lie

### ISSUE THREAD

**Issue by henke37** [MicrosoftDocs/visualstudio-docs#3076]
The name of "ReularExpression" is a lie. It's not a regular expression at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c64c1b1c-bfc1-cee4-aba7-07f9986b9015
* Version Independent ID: 5250428c-2be8-00cc-090d-07955770ca74
* Content: [NameSearchOptions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/namesearchoptions?view=vs-2019)
* Content Source: [docs/debugger/debug-interface-access/namesearchoptions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-interface-access/namesearchoptions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@henke37 -- please provide addtional context for your feedback, so we may better understand this issue.

**Comment by henke37** [comment]
The context is that the identifier is incorrect. It is not a regular expression. It is a completely different matching language, the shell filename globbing one. This discrepancy needs to be noted so that people won't get fooled by the incorrect name,

**Comment by WilliamAntonRohm** [comment]
Thank you Henrik -- I have passed this information along to the article's author (@Mikejo5000).

**Comment by Mikejo5000** [comment]
Thanks for the feedback. Asking about this...

**Comment by Mikejo5000** [comment]
Updating doc. Noting in doc that it is a limited form of regular expression support.
