### ISSUE TITLE
Develop and Debug with Docker in Visual Studio (netfx)

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#3078]
This is an offshoot of #688. 

The docs are conspicuously absent of any .net framework assistance in regards to develop and debugging with docker containers, or how to port existing investments into using docker. A working example that uses .net framework, but does not rely on or include other technologies like EF, netcore, Asp.net's flavor of MVC, etc. would be very useful for many of us who have considered using Docker but just cant figure out how to make the tooling work efficiently.

If it could cover non-web technologies like console apps and other [ServiceHost](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.servicehost?view=netframework-4.7.2) candidates that would be the ideal. 

The existing docs also needs a section for when you want to publish the thing you have been debugging to for use somewhere else. Like how to get it from the debugger into a local container registry, (the full steps encompassing checkin into version control, and from there build the image and distribute to a container would be nice).

**Comment by ghogen** [comment]
Added a section to https://docs.microsoft.com/en-us/visualstudio/containers/edit-and-refresh?view=vs-2019 in May, 2019 that covers the basic .NET Framework console app debug scenario - note there is no need to install remote debugging components manually in either VS 2017 or VS 2019.  

It doesn't cover a Windows Service scenario, but the Windows Service project template is not one of the supported project types that have Docker support enabled.
