### ISSUE TITLE
PDF generation

### ISSUE THREAD

**Issue by Depechie** [MicrosoftDocs/visualstudio-docs#3080]
I know the first request already got closed, but a gentle reminder that having these Keyboard shortcuts in a handy small PDF format would be nice, instead of getting whole PDF of docs.
But the PDF generation does not render the Mac chars correctly... something about character encoding I guess!

For example:
Next Issue in File	⌥⇟

Renders like so in the PDF:
Next Issue in File        []⇟

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a1d38f-f2fc-3fe6-bfb4-b73b7f4a56bc
* Version Independent ID: 90b1f5ca-71dd-2c14-8023-c3f238fc2686
* Content: [Default Keyboard Shortcuts in Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/keyboard-shortcuts?view=vsmac-2019#code-navigation)
* Content Source: [mac/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/keyboard-shortcuts.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @BytesGuy
* Microsoft Alias: **adhartle**

**Comment by asb3993** [comment]
Hi @Depechie we're actively working with the design team on making this available in a nice, easy to reference format. Hopefully we'll have something for you soon!

**Comment by timeyoutakeit** [comment]
I no longer work on this product, hopefully this is something @heiligerdankgesang can address!

**Comment by heiligerdankgesang** [comment]
We added a pdf download of keyboard shortcuts to this documentation page.

**Comment by heiligerdankgesang** [comment]
@TerryGLee I don't have permissions to close this. Can you please help us get this closed, thanks?

**Comment by TerryGLee** [comment]
Closing per request. Thanks all for helping to improve our documentation!
