### ISSUE TITLE
First unit tests never completes

### ISSUE THREAD

**Issue by TonyKenny666** [MicrosoftDocs/visualstudio-docs#3085]
If you follow the link to the Hello World project and add the code from that document then return here to create the first test, then the unit test never completes because the hello world is waiting for Console.ReadLine();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107f3c03-dac2-0226-d5c1-f2f49daa413d
* Version Independent ID: aaf80310-28eb-462b-d4f1-6b97a8abe260
* Content: [Get started with unit testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2019#feedback)
* Content Source: [docs/test/getting-started-with-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/getting-started-with-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@TonyKenny666 Thanks for pointing this out. And actually with Visual Studio 2019, the console automatically waits for a keystroke, so [this section](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-csharp-console?view=vs-2019#add-some-code) of "Quickstart: Use Visual Studio to create your first C# console app" can be removed (@TerryGLee fyi). Here's the output if you press F5 on the default .NET Core console app project template:

```
Hello World!

C:\Program Files\dotnet\dotnet.exe (process 17616) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```
