### ISSUE TITLE
missing redirects from old docs to new docs

### ISSUE THREAD

**Issue by nonbob** [MicrosoftDocs/visualstudio-docs#3087]
This is a continuation of [2115](https://github.com/MicrosoftDocs/visualstudio-docs/issues/2115), which I now realize was really 2 bug reports.  The [fwlink from the msbuild diagnostic output ](http://go.microsoft.com/fwlink/?LinkId=293424)now points to the correct spot, but the [Recommended Version link](https://docs.microsoft.com/en-us/visualstudio/) on [the old (VS 2013) page](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/bb383796(v=vs.120)) still fails to revector to the corresponding VS 2019 page (which is were the fwlink now correctly goes).

**Comment by gewarren** [comment]
@nonbob The "Recommended Version" link is designed to go to a high-level page and not the corresponding page for the one you're on. Thank you for following through so thoughtfully! /cc @Mikejo5000
