### ISSUE TITLE
Assembly Version: *

### ISSUE THREAD

**Issue by veevandyke** [MicrosoftDocs/visualstudio-docs#3088]
You cannot put a wildcard in the assembly version in Visual Studio 2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d868fc5c-dbe0-e662-fb8f-6931ed0f1aab
* Version Independent ID: cf346c2b-04e8-9075-1034-632499a5ffeb
* Content: [Troubleshoot Office solution deployment - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/troubleshooting-office-solution-deployment?view=vs-2019#feedback)
* Content Source: [docs/vsto/troubleshooting-office-solution-deployment.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/troubleshooting-office-solution-deployment.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
#please-close this is now fixed
