### ISSUE TITLE
Hiding child projects in multiproject template

### ISSUE THREAD

**Issue by batizar** [MicrosoftDocs/visualstudio-docs#3091]
I have created a multiproject template but in new project window I just want to see the parent template and not the child project templates as it gets confusing for users. 

Is there a way to hide child project templates and disable them from showing in new project list?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e208-2a2a-9fc3-98ff-147540157f32
* Version Independent ID: 5f5c9adf-da1d-ec0b-8af3-ccd2e27eaadc
* Content: [Create multi-project templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-create-multi-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-multi-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@batizar Hmm, I'm surprised that's happening. @prnadago If you have a multi-project template, are the subprojects supposed to appear in the new project dialog box?

**Comment by prnadago** [comment]
Inner templates within a project group are full-fledged templates and if they are in a location being looked up, they will show up.

If the intent is not use them directly, the inner templates need to be marked as hidden.
https://docs.microsoft.com/en-us/visualstudio/extensibility/hidden-element-visual-studio-templates?view=vs-2019

Hope this helps!

**Comment by gewarren** [comment]
Thanks Pratik. I'll update the doc with this info too.

**Comment by batizar** [comment]
Thanks @prnadago
