### ISSUE TITLE
Icon does not show in new project 

### ISSUE THREAD

**Issue by batizar** [MicrosoftDocs/visualstudio-docs#3099]
I'm trying to set a custom icon for our project template but no matter what I do visual studio still shows the default icon for my projects. 

Is there anything else beside adding the .ico file inside zip that I need to do? 

Do I need to provide multiple sizes and qualities of icons for this to work?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 397b0790-ed8b-822d-931a-98a06c594ec6
* Version Independent ID: f1b1aa72-1bd7-c0b1-3d77-5e9b978a9b11
* Content: [Creating Custom Project and Item Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-custom-project-and-item-templates?view=vs-2019)
* Content Source: [docs/extensibility/creating-custom-project-and-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-custom-project-and-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@madskristensen Could you help with this question?

**Comment by madskristensen** [comment]
The .ico or .png file should be in the zip file AND the icon must be references from within the .vstemplate file like [this sample](https://github.com/madskristensen/TextmateExtensionTemplate/blob/82978dc16c8644415b3b6cac6fdb196974664cd0/Template/TextmateExtensionTemplate.vstemplate#L6)

**Comment by batizar** [comment]
@madskristensen thanks for reply, I tried that and checked the zip file to make sure it contains the icon file but VS completely ignores my icon and still shows the default custom template icon. Are there some sort of validations for image quality like 32/16 bit or size 16/32pix? I see some guidelines here but not sure if they are compulsory.

https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2019

https://docs.microsoft.com/en-us/cpp/windows/creating-an-icon-or-other-image-image-editor-for-icons?view=vs-2019

Thanks.

**Comment by gewarren** [comment]
@batizar If you continue to have a problem with the icon, it's probably best to file a report at Developer Community. Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by madskristensen** [comment]
It could be that there are restrictions on the .ico file. Try with a square .png and see if that makes a difference.

**Comment by PoulChapman** [comment]
Thanks for the feedback. If this above discussion hasn't helped you solve this issue, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

#please-close
