### ISSUE TITLE
What is the reason this rule will is obsolete and will be removed? 

### ISSUE THREAD

**Issue by kinloongTong** [MicrosoftDocs/visualstudio-docs#3107]
Should I ignore or suppress this warning for my existing project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea104862-8cc3-ee21-6613-1da6428bde9f
* Version Independent ID: a22201d7-db7d-f821-0809-1b67592b5929
* Content: [CA2104: Do not declare read only mutable reference types - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2104-do-not-declare-read-only-mutable-reference-types?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2104-do-not-declare-read-only-mutable-reference-types.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2104-do-not-declare-read-only-mutable-reference-types.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Could you answer this?

**Comment by mavasani** [comment]
See https://github.com/dotnet/roslyn-analyzers/issues/793#issuecomment-206621893

**Comment by mavasani** [comment]
@gewarren We should probably update the documentation to add this justification or add the above link to the docs.

**Comment by gewarren** [comment]
@mavasani Does this sound okay?

Rule CA2104 is obsolete and will be removed in a future version of Visual Studio. It will not be implemented as an analyzer due to the complicated analysis that's required to determine the actual immutability of a type.

**Comment by mavasani** [comment]
@gewarren Looks good to me!

**Comment by gewarren** [comment]
The note has been updated in the article now.

**Comment by kinloongTong** [comment]
Should the implementation change the list of a known mutable type, rather obsolete it?

"> FxCop's implementation of CA2104 basically had a list of type that were known to have immutable semantics and it considered anything else mutable. It didnt really check for immutability of a type which requires complicated analysis. We've decided to not reimplement CA2104 as an analyzer (see #716) since in it's current form it is very noisy."
