### ISSUE TITLE
Nice and tidy but doesn't work

### ISSUE THREAD

**Issue by VincentLavello** [MicrosoftDocs/visualstudio-docs#3108]
Missing Workgroup file. Never had one nor did any googled answer. Red herring error and I'm stuck - cannot connect to access database in visual studio 2019 - guess I got to reinstall 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c5b210-2ecd-fc40-54c9-38a8ba9c7493
* Version Independent ID: a9236354-4965-a214-17f7-746c20de8ec4
* Content: [Connect to data in an Access database (Windows Forms) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms?view=vs-2019#feedback)
* Content Source: [docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@VincentLavello I just tried to connect to an .accdb file using Visual Studio 2019 and it worked by following the steps described here. Are you connecting to an .accdb file or an older .mdb file?

**Comment by gewarren** [comment]
If you continue to have trouble, here are a few options where you might consider asking for help:​

https://social.msdn.microsoft.com/Forums/vstudio
https://www.stackoverflow.com
https://www.reddit.com/r/VisualStudio/

If you still feel there's a problem in the documentation, please let us know.
