### ISSUE TITLE
Navigation is not working

### ISSUE THREAD

**Issue by ravimp** [MicrosoftDocs/visualstudio-docs#3109]
Clicking on "Data Science and Analytical Applications" doesn't take me there. Works for some of the links not all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4891ebc9-fdea-c376-94f6-17295ca275d7
* Version Independent ID: ccc61918-cc18-a7ff-cc6c-8659d6c9c78a
* Content: [Visual Studio Community workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019#data-science-and-analytical-applications)
* Content Source: [docs/install/workload-component-id-vs-community.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-community.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ravimp Thanks for letting us know. This should work and I'm not sure why it's not. I'll investigate and report back.

**Comment by TerryGLee** [comment]
@ravimp I've double-checked the Markdown for this page and there isn't anything in it that would cause the issue that you're reporting. Unfortunately, it isn't anything that I personally can fix. 

It's an annoyance, certainly. If you'd like to pursue getting it fixed, please consider filing this issue through our site feedback channel, where such issues related to overall site experience, or suggestions for improved site functionality or design, are collected and addressed. Here's where to do so: [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
