### ISSUE TITLE
LinkedIn Learning Benefit is no longer available

### ISSUE THREAD

**Issue by BrennanGlynn** [MicrosoftDocs/visualstudio-docs#3110]
LinkedIn Learning Benefit is no longer available

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4948f37c-a328-34ea-5980-5ac3115e2f8e
* Version Independent ID: f8c0f599-0711-a98e-b254-04407ba864de
* Content: [LinkedIn Learning Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-linkedin-learning#feedback)
* Content Source: [subscriptions/vs-linkedin-learning.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-linkedin-learning.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by shameelsfdc** [comment]
It's no longer available. Please check

**Comment by shameelsfdc** [comment]
Hi Team,
Even I don't see this feature in the benefits section.

**Comment by evanwindom** [comment]
Hello all, 
Thanks for reaching out. The Dev Essentials program works with a variety of partners to bring exclusive benefits to our members. These exclusive benefits are offered with a limited quantity and some benefits run out quicker than others. The goal is to ensure there's enough to meet the demand, but we often don't have a say in the quantity available.

When the supply runs out, the benefit tile is removed from the portal to ensure members don’t encounter errors.

We've reached out to LinkedIn to discuss expanding this offer to more members and doing everything we can to make this benefit available again soon.

**Comment by Boogaloos007** [comment]
Any update on this benefit?

**Comment by evanwindom** [comment]
@Boogaloos007 - We're still working on the issue.  We'll post more information here when it is available.

**Comment by leachjames** [comment]
Anyone found a fix yet?

**Comment by willydavidjr** [comment]
After the degrade of Pluralsight to 1 month, now this one was also gone?

**Comment by vj15987** [comment]
Please bring LinkedIn learning back!

**Comment by narenarjun** [comment]
When will LinkedIn learning will be available to us ?? Is there any definitive timeline that states when this benefit will be available? 
Please bring it back soon !!

**Comment by Boogaloos007** [comment]
@evanwindom - Seems like many people are pleading with Microsoft to bring back the Linkedin Learning benefit to Visual Studio Essential Subscribers.

**Comment by Junth19** [comment]
LinkedIn Learning Benefit is not available yet. When will it be available?
Please bring LinkedIn Learning Benefit back!

**Comment by narenarjun** [comment]
hello dev essentials support team!!! 
when will the LinkedIn Learning benefits be available for us? is there any tentative time line of when it'll be back? 

give  us an update on this issue please !

**Comment by prkpro** [comment]
Hi team,
Please bring back LinkedIn learning benefit back.

**Comment by evanwindom** [comment]
LinkedIn is no longer offering the 3-month Premium benefit through Visual Studio Dev Essentials.  A one-month free trial is available at https://www.linkedin.com/learning/me.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for providing us with the status of the LinkedIn Learning benefit. We are closing this issue now.
