### ISSUE TITLE
[RegEx] Improve captured expression documentation

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/visualstudio-docs#3115]
The way the doc is written, the Replacement patterns section is off by itself and explains this one syntax feature in paragraph form before any other syntax elements are described. The syntax it actually refers to is buried, without any reference to the illuminating text, in the middle of the lookup table of other syntax examples. Which is where someone looking for syntax is going to look--at the symbols (because that is what regex consists of). As it turns out, the lookup table is misleading because it documents the () syntax but in an entirely different context--the use of \1 to repeat a captured expression in a matching pattern. Since the $1 syntax is not documented in the lookup table, one is understandably led to think this is the syntax for capture and replacement.

My suggestion would be to include a reference to the $1 replacement syntax in the lookup table, and possibly refer to the Replacement pattern text for further explanation. Also some language to differentiate it from the \1 syntax. The fact that I was misled and confused by the current arrangement tends to support the argument that it might be improved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@buzzwick Are you referring to the example for "Capture and implicitly number the expression contained within parentheses"? I.e. this text?

`([a-z])X\1` matches "aXa"and "bXb", but not "aXb". "\1" refers to the first expression group "[a-z]".

If so, I believe that this text is correct. In this case, `\1` is used in a "find" expression and is not used as a replacement in a "replace" expression. The [Replacement patterns](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019#replacement-patterns) section correctly identifies `$number` as the way to refer to a numbered capture group in a replacement expression.

**Comment by buzzwick** [comment]
Gewarren,
Technically, you are correct.  The Replacement patterns section does correctly identify $number as the way to reference a captured group. 
But the way the doc is written, The Replacement patterns section is off by itself and explains this one syntax feature in paragraph form before any other syntax elements are described. The syntax it actually refers to is buried, without any reference to the illuminating text, in the middle of the lookup table of other syntax examples. Which is where someone looking for syntax is going to look--at the symbols (because that is what regex consists of). As it turns out, the lookup table is misleading because it documents the () syntax but in an entirely different context--the use of \1 to repeat a captured expression in a matching pattern. Since the $1 syntax is not documented in the lookup table, one is understandably led to think this is the syntax for capture and replacement. 
My suggestion would be to include a reference to the $1 replacement syntax in the lookup table, and possibly refer to the Replacement pattern text for further explanation. Also some language to differentiate it from the \1 syntax. The fact that I was misled and confused by the current arrangement tends to support the argument that it might be improved. If you were so inclined. 
Thank you for pointing out the explanatory text, in any case. Now I won't forget.

**Comment by gewarren** [comment]
Related to #1300.
