### ISSUE TITLE
Deploy <Some Database Name>

### ISSUE THREAD

**Issue by datAdrenaline** [MicrosoftDocs/visualstudio-docs#3117]
All the Deploy help deals with an App of some sort, but not much help for SQL Server Database, SSIS, SSAS, etc.  basically we are on our own if the solution/project is not a web app or other form of web app.  Please expand your documentation to included the deployment of non-app related projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852946c7-d511-76d8-ce40-a03c7d9d7ff2
* Version Independent ID: 4b1be0b3-7e28-d414-553f-9e1be7ef04a0
* Content: [Deployment feature tour - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components?view=vs-2019#feedback)
* Content Source: [docs/deployment/deploying-applications-services-and-components.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/deploying-applications-services-and-components.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@datAdrenaline Thanks for your suggestion. I will add some links to other topics. I believe there will be too many database-specific issues to try doc'ing them here.
