### ISSUE TITLE
Missing 'Text Editor - Advanced' help page

### ISSUE THREAD

**Issue by noelgifford** [MicrosoftDocs/visualstudio-docs#3121]
The 'Text Editor Options Dialog Box' category is missing a help page for 'Text Editor - Advanced'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f01023-67c3-af23-1256-996e0543aa3a
* Version Independent ID: d19f4d8f-7f3b-1098-9240-335c14d86b24
* Content: [Options dialog box: Text Editor > General](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The corresponding F1 keyword is `VS.ToolsOptionsPages.Text_Editor.Advanced`.

**Comment by jameszliao-msft** [comment]
#assign: @jameszliao-msft

**Comment by PRMerger7** [comment]
Only Microsoft employees can manage issues via commenting in this repo.

**Comment by TerryGLee** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/issues/3121

**Comment by TerryGLee** [comment]
@noelgifford Thanks for taking the time to write up this issue. We've received several reports about this missing page, and we're currently working on creating it and should have the new page published soon. However, in the interest of efficiency, we're closing this older report now in deference to the newest report of the same problem. However, to close the loop, we will report back here when the new page is published. In the interim, please accept our sincere thanks for helping to improve the Visual Studio documentation!

**Comment by TerryGLee** [comment]
@noelgifford To follow up, this previously missing page is now published; see [Options dialog box: Text Editor > Advanced](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-advanced).
