### ISSUE TITLE
dockerfile syntax issues

### ISSUE THREAD

**Issue by stevieflash42** [MicrosoftDocs/visualstudio-docs#3123]
on this line: `ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe`

if you get this error: "failed to copy files: failed to copy file: mkdir \\?\Volume..."

the solution is to change the line to `ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\\TEMP\\vs_buildtools.exe`
- note that all references of `\` have been changed to `\\`

You'll likely get this error on the RUN command immediately after this line. Same solution.

The `` ` `` character that is used to denote a multi-line command may also give you trouble. Replace them with `\`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
The instructions specifically change the escape character to a backtick so escaping backlashes is not necessary. This is documented for the dockerfile syntax and, as they suggest, recommended for dockerfiles for Windows containers.

**Comment by stevieflash42** [comment]
ah gotcha.

I had that after a comment I put at the top of the file. Looks like it gets upset about that.
Seems to be working now. Thank-you!
