### ISSUE TITLE
The tutorial only works as shown with ASP.NET Core 2.1, not with 2.2

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/visualstudio-docs#3124]
The tutorial page only works if ASP.NET Core 2.1 is selected. It will not create an About page when 
ASP.NET Core 2.2 is selected.

Also, the user must stop debugging, Shift+F5, before making a change in step 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2376dee-30e0-850f-7572-6d32b351be3f
* Version Independent ID: 9c06f47f-8195-4736-3575-fffe1c51f763
* Content: [Tutorial: Get started with C# and ASP.NET Core](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Liturgist Thanks for the feedback; we'll get this doc updated and report back when we do so.

**Comment by TerryGLee** [comment]
@Liturgist A follow-up question: Were you using a Preview version of Visual Studio, per chance? I just tested the instructions in this tutorial for both the GA releases of Visual Studio 2017 (version 15.9.11) and Visual Studio 2019 (version 16.0.2) and did not see the option to choose anything other than ASP.NET Core 2.1 in the UI.

**Comment by Liturgist** [comment]
I was not using a Preview version. I was using the available Community version.

**Comment by TerryGLee** [comment]
@Liturgist I am at a loss then, as per the following screenshot, Visual Studio Community 2019 doesn't allow for ASP.NET Core 2.2:

![image](https://user-images.githubusercontent.com/23244653/57736263-32a12080-765c-11e9-8e9d-86d209802aa8.png)

**Comment by TerryGLee** [comment]
@Liturgist I've made changes to the tutorial to address the issues that you brought up. The updates should be published by noon on May 30th. 

Thanks for your help with improving our documentation!
