### ISSUE TITLE
How to view and edit .gitignore and README.md at root of repo inside Visual Studio 2019 for Mac

### ISSUE THREAD

**Issue by wilsonmar** [MicrosoftDocs/visualstudio-docs#3127]
After I clone repository https://github.com/wilsonmar/github-emojis
I can't figure out how to navigate above the solution folder to the root repo folder where the .gitignore and README.md files are located and be changed from.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606d4c70-3daf-8b03-9c31-b690927a7136
* Version Independent ID: 24a13aaf-3d14-c810-182c-2c2d93fc299b
* Content: [Setting up a Git Repository - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository?view=vsmac-2019#feedback)
* Content Source: [mac/set-up-git-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/set-up-git-repository.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
You can right-click on the solution and **Display Options > Show All Files** to view files that aren't in the solution (such as .gitignore or readme files). 

<img width="509" alt="Display Options Show All Files" src="https://user-images.githubusercontent.com/199373/58210746-1bd37d00-7c9f-11e9-942c-9a09d62be8e9.png">

You cannot browse _up_ folders from where the solution file is. Right-click and choose **Reveal in Finder** to view/open those files using the editor of your choice. Note that files beginning with a dot `.` are often hidden by default in macOS.
