### ISSUE TITLE
VS 2019 - convert to lowercase

### ISSUE THREAD

**Issue by gustavf** [MicrosoftDocs/visualstudio-docs#3131]
Seems to not work to make lowercase in VS 2019 (Ctrl+U). Upper case works fine. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b27ada-f62b-0853-2a8f-38c81af480a4
* Version Independent ID: 4fa67498-a0f2-87c9-fc1d-acb3d6dfc796
* Content: [Convert text to uppercase or lowercase - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-text-case-in-the-editor?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-change-text-case-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-change-text-case-in-the-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@gustavf It works for me. The U does not need to be "capitalized" - just click Ctrl + the U key on the keyboard. If it still doesn't work, can you provide a screenshot of what you're trying to convert?

**Comment by gustavf** [comment]
Seems my shortcut is just missing (blank in the dropdown), not sure why. I added it under Options and seems fine now.
