### ISSUE TITLE
Unnecessarily complex examples

### ISSUE THREAD

**Issue by buzzwick** [MicrosoftDocs/visualstudio-docs#3133]
The illustration for "match a hexadecimal character" uses the string `\b0[xX]([0-9a-fA-F]+)\b` to illustrate. This string incorporates, by my count, at least four separate regex syntax elements: \b word boundary, [] character class, () expression capture, and + occurrence count. Why? This makes it impossible to distinguish syntax specific to the matching of hex characters--if there even is any. Moreover, hex characters do not appear as strings in text (like "0x1f"), which is precisely why we need specific syntax to match them. I am not convinced that there is anything in this example that would match an actual hex value, as opposed to its string representation. But the example is so needlessly overburdened that it is impossible for me to identify what it is. It might be helpful to distinguish between documentation of the primary syntax elements, and recipes--which combine multiple syntax elements to accomplish a defined task. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@buzzwick Can you give an example of a hex value that you're trying to match?

I think the example given is more of a sample pattern expression than a specific "escaped character" that correlates to a hex value. To me, it is a real world example of how to piece together a regular expression using different syntax elements to match something that's familiar to most developers (i.e. the prefix 0x and the number that follows that represents a hexadecimal value).

**Comment by buzzwick** [comment]
Genevieve,
The short answer? 0[xX]([0-9a-fA-F]+) does not find the hex value 01F in a text file; \u001F does.

Thank you for your query. As it turns out, to find the hex value 1F in a text file (mind you, 1F is the actual hex value, not the string representation 0x1F), we had to use \u001F. Where \u tells the engine it is looking for a Unicode value and 001F is the Unicode representation of hex 1F.  There does not appear to be a special regex character (like \u) to tell the engine it is looking for a hex value.
To take your "real world example"  \b0[xX]([0-9a-fA-F]+)\b:  If you remove the characters that have nothing to do with searching for hex values (\b indicates word boundaries, [] indicates a character group, () captures a match result, + indicates character repetition), you are left with a search for 0x1F, or a literal character string. No amount of searching for the hex value 1F as 0x1F will find the hex value in a text file. unless there is an escaped character like \u to tell the engine it is searching for a hex value, the engine merely searches for a string. 
Compare this syntax definition with that for the \u character:  "\uXXXX where XXXX specifies the Unicode character value." Simple. Clear. No extraneous syntax. No need to decode a complex example to try and find out what the hex search syntax actually is (or, in this case, that it is not actually there). 
Examples are wonderful. But again I would distinguish between syntax documentation and recipes. Each has their place, but their places should be kept distinct.
Thanks again,

**Comment by gewarren** [comment]
@buzzwick I understand your point, and recently removed some of the examples that were, as you describe, recipes as opposed to special regular expression syntax. Hopefully this reads better and is less confusing.
