### ISSUE TITLE
Line length limit has been removed

### ISSUE THREAD

**Issue by Gooseman** [MicrosoftDocs/visualstudio-docs#3134]
Visual Studio used to have an option to hard-wrap lines at a specific number of characters.  This is useful for people who want to keep the code readable.  In 2019 this setting has been removed as far as I can tell.  I've searched the options and can't find a setting.  Is this a bug or is this Microsoft saying that we should have to download extensions to get standard IDE functionality?

Craig

**Comment by gewarren** [comment]
@Gooseman Thanks for the feedback. When you say Visual Studio used to have a setting, do you mean way back in VS 2008? Or, if you're referring to a setting in VS 2017, which setting are you referring to exactly?

**Comment by Gooseman** [comment]
Well, until yesterday I was using 2017.  Unfortunately it decided to start
randomly discarding keyboard shortcuts and permanently disable edit and
continue, so I decided it was worth the several hours it took to uninstall
and install 2019.  Prior to that I was using 2015 and prior to that 2013
and prior to that 2010.

**Comment by gewarren** [comment]
@Gooseman As far as I'm aware VS 2017 did not have a hard line length setting. However, you are welcome to suggest this as a feature for VS 2019 if it is important to you. The best place to make product feature suggestions or provide feedback is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Look for the "Suggest a Feature" button:

![image](https://user-images.githubusercontent.com/24882762/50102736-a7218180-01da-11e9-9aaf-ea3a99ccd030.png)

When you suggest a feature on Developer Community, you can engage directly with the engineering team as they consider the suggestion. It also provides a way for other customers to upvote your suggestion.

Also as an aside, you can install VS 2017 and VS 2019 side by side. No need to uninstall VS 2017, although it sounds like it's too late.

**Comment by Gooseman** [comment]
Weird, I was so sure I specifically explained why I had to uninstall 2017.
Perhaps that part of my email got deleted.
