### ISSUE TITLE
correction

### ISSUE THREAD

**Issue by donaldnp** [MicrosoftDocs/visualstudio-docs#3137]
"To set a breakpoint in source code, click in the far left margin next to a line of code" - should be right-click

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use breakpoints in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2019#feedback)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@donaldnp Thanks for the suggested fix. You can right-click and choose Insert Breakpoint. You should also be able to just click in the left margin to add the breakpoint. That doesn't work for you?

**Comment by donaldnp** [comment]
No, tried clicking in various places to the left with no success, and then tried right-click and it worked.

**Comment by donaldnp** [comment]
Scratch that. I just found what you mean. I never even knew that area was clickable! Maybe a picture would help so that people can see where to click.

**Comment by Mikejo5000** [comment]
@donaldnp OK, thanks for the follow up. There is a picture here:
https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-feature-tour?view=vs-2019
This topic is more reference-y, but maybe I will switch out the screenshot with a new one...
