### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hxingpax** [MicrosoftDocs/visualstudio-docs#3138]
> If you want more precise control over the memory diagnostic features

precise => percise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 705680a5-9d13-9ad6-3fdf-5223d50b6cc5
* Version Independent ID: 008027a0-d0ba-32b4-aecc-de0d9322e312
* Content: [MFC Debugging Techniques - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/mfc-debugging-techniques?view=vs-2019#BKMK_Tracking_memory_allocations)
* Content Source: [docs/debugger/mfc-debugging-techniques.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/mfc-debugging-techniques.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by nschonni** [comment]
"percise" isn't a correct spelling https://en.oxforddictionaries.com/definition/precise
The current text is correct
