### ISSUE TITLE
Poor documentation in CA1814

### ISSUE THREAD

**Issue by johnnyasantoss** [MicrosoftDocs/visualstudio-docs#3139]
Poor documentation on the "why" of this rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 088ac03f-0e6c-9b9b-24dc-e17564a970da
* Version Independent ID: a49e1b15-68c0-896c-18a7-c7347565a387
* Content: [CA1814: Prefer jagged arrays over multidimensional - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1814)
* Content Source: [docs/code-quality/ca1814-prefer-jagged-arrays-over-multidimensional.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1814.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Edit to trigger priority labeling.

**Comment by gewarren** [comment]
@johnnyasantoss The article states that jagged arrays use less memory space than multidimensional arrays. @mavasani Can you comment on whether this is the only reason why CA1814 recommends jagged arrays over multidimensional?

This [SO post](https://stackoverflow.com/questions/597720/what-are-the-differences-between-a-multidimensional-array-and-an-array-of-arrays) has a nice discussion of the pros and cons of each. In July 2017, one use noted that according to their calculations, in .NET Core, multi-dimensional arrays are faster than jagged arrays. If that is true, should we get rid of CA1814?

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22047](https://github.com/dotnet/docs/issues/22047)
