### ISSUE TITLE
The "Azure Boards & Repos (Basic)" link is broken

### ISSUE THREAD

**Issue by dburnison** [MicrosoftDocs/visualstudio-docs#3140]
When I click on the "Azure Boards & Repos (Basic)" link I get a 401 page not found error. Not sure if its a bad link on this page or, that page is unavailable. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@dburnison - I just tried it using two different browsers on each of two different OS versions, and it worked fine.  Can you try going directly to the target page at https://azure.microsoft.com/en-us/services/devops/compare-features/?

**Comment by dburnison** [comment]
Ok, now it is working but, the link on the page is https://visualstudio.microsoft.com/team-services/compare-features/ so there is a redirection going on. Perhaps the page should be updated to go directly to https://azure.microsoft.com/en-us/services/devops/compare-features/

**Comment by TerryGLee** [comment]
@dburnison It looks like this issue has been fixed on the https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops page. We'll close this issue now. We thank you for helping us improve our documentation!

**Comment by dburnison** [comment]
Thank you! The link works as expected for me now.
