### ISSUE TITLE
Extensions menu parameter is missing

### ISSUE THREAD

**Issue by BigHoss** [MicrosoftDocs/visualstudio-docs#3144]
The extensions menu where the "Manage Extensions" button is located is not specified here. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27088666-73eb-b621-253e-1957218cf765
* Version Independent ID: da38ef89-6570-a27e-9f9a-eaac22baec07
* Content: [GUIDs and IDs of Visual Studio Menus - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/guids-and-ids-of-visual-studio-menus?view=vs-2019)
* Content Source: [docs/extensibility/internals/guids-and-ids-of-visual-studio-menus.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/guids-and-ids-of-visual-studio-menus.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @BigHoss Thank you for pointing this out. PRs welcome.

**Comment by BigHoss** [comment]
I would PR that if i knew how to get that information :sweat_smile:

**Comment by gregvanl** [comment]
@dgriffen Can you find this value?

**Comment by madskristensen** [comment]
The ID is **IDM_VS_MENU_EXTENSIONS** AFAICT
