### ISSUE TITLE
Question: Supported Roslyn package version mappings

### ISSUE THREAD

**Issue by tpodolak** [MicrosoftDocs/visualstudio-docs#3147]
The docs say, that for Roslyn package version 2.8.2 is supported by

> Visual Studio 2017 version 15.7 or higher

Does it mean that it is supported only by VS2017 - versions 15.7 - 15.x
or the support also includes VS2019 - versions 16.0 - 16.x? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0997f041-1ecb-af6d-c4a6-8c61ec177dac
* Version Independent ID: 45c55eac-dff7-812a-7e95-15952047d19f
* Content: [Supported Roslyn package version mappings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2017#feedback)
* Content Source: [docs/extensibility/roslyn-version-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/roslyn-version-support.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Good question. @mavasani?

**Comment by mavasani** [comment]
`Visual Studio 2017 version 15.7 or higher` should include later versions of VS, so VS2019 and even future versions of VS should be supported.

**Comment by gewarren** [comment]
Thanks. I'll make this more clear in the docs.
