### ISSUE TITLE
Vue version 3.0 no longer supports capital letters for names

### ISSUE THREAD

**Issue by helmut-steiner** [MicrosoftDocs/visualstudio-docs#3149]
The project name "ClientApp" should be changed to client-app in the docs to be compatible with Vue version 3.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a644716-10c3-cc90-eeab-495c265e5728
* Version Independent ID: c356a0d8-1d24-2ab7-18de-b9b3088fd4d9
* Content: [Create a Vue.js app using Node.js - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/create-application-with-vuejs?view=vs-2019#feedback)
* Content Source: [docs/javascript/create-application-with-vuejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/create-application-with-vuejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@helmut-steiner Thanks for the feedback! I'll make that change.
