### ISSUE TITLE
editorconfig rules for Typescript not enforced

### ISSUE THREAD

**Issue by Regenhardt** [MicrosoftDocs/visualstudio-docs#3152]
We have naming rules in our editorconfig, and I jsut realized VS isn't applying them to Typescript files, although the class_names rule is in the [*]-section:

dotnet_naming_rule.class_names.symbols = classes
dotnet_naming_rule.class_names.style = class_style
dotnet_naming_rule.class_names.severity = error

dotnet_naming_symbols.classes.applicable_kinds = class, struct, enum
dotnet_naming_style.class_style.capitalization = pascal_case

Do I have to put it in an extra [*.ts]-section or something? 
I have Typescript Analyzer and Typescript SDK 3.4.5 installed if that helps.

Edit: This is my .ts section:

[*.{ts,js}]
indent_size = 2
max_line_length = 80
\# Interfaces
dotnet_naming_rule.interface_names.symbols = interfaces
dotnet_naming_rule.interface_names.style = interface_style
dotnet_naming_rule.interface_names.severity = error

dotnet_naming_symbols.interfaces.applicable_kinds = interface
dotnet_naming_style.interface_style.capitalization = pascal_case

**Comment by gewarren** [comment]
@kendrahavens Do dotnet naming rules apply to TypeScript?

**Comment by kendrahavens** [comment]
No, the dotnet style rules only pertain to C# and Visual Basic. Typescript predominantly uses TSLint to manage code style. There is a very popular [VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin) for this. I don't *believe* we have a TSLint extension in Visual Studio. (@sana-ajani to correct me)

**Comment by sana-ajani** [comment]
There is a typescript-tslint-plugin that you can use: https://github.com/Microsoft/typescript-tslint-plugin#with-visual-studio
