### ISSUE TITLE
Help in automating installation or update of specific VSIX extensions

### ISSUE THREAD

**Issue by tristanbarcelon** [MicrosoftDocs/visualstudio-docs#3155]
I've automated my installation of VS2017/VS2019 using the provided examples. Our developer and build environment needs necessitate us to build SSRS, SSAS, and SSIS project types. According to the [VS2019 SSDT instructions](https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-2017) , we're supposed to download them from the marketplace and I've tracked these extension names to: ProBITools.MicrosoftReportProjectsforVisualStudio, ProBITools.MicrosoftAnalysisServicesModelingProjects, SSIS.SqlServerIntegrationServicesProjects. Is there an automated method I can use for applying them to my VS2019 instance?

**Comment by TerryGLee** [comment]
@tristanbarcelon Thanks for your inquiry. Although the page you reference is not in the visualstudio-docs repo, I'll investigate to see if I can find the answer you seek. Meanwhile, if an answer doesn't present itself in a timely fashion, please see our [Feedback](https://docs.microsoft.com/visualstudio/ide/feedback-options?view=vs-2019) page for more support options. 
@dnethi FYI @stevestein FYI

**Comment by dnethi** [comment]
Pinged @Tim Chen (SH)<mailto:tichen@microsoft.com> to  see if he can add something..


Thanks,
Dinakar

**Comment by tristanbarcelon** [comment]
Thank you. I received [twitter feedback](https://twitter.com/mkristensen/status/1121876801020514305) from @madskristensen about possible efforts for installing vsix extensions using .vsconfig file but no timetable has been provided. I was, however, able to automatically install VSIX packages one time using Powershell after a brand new install. Most of the logic for handling vsixinstaller.exe was obtained from this post: https://weblog.west-wind.com/posts/2016/Mar/01/Registering-and-Unregistering-a-VSIX-Extension-from-the-Command-Line

The only portion I'm missing now is a way to enumerate currently installed VSIX packages like the Extension Tools pack by @madskristensen so I could uninstall them first when the same VSIX is already found before installing a newer version or simply short-circuiting when the desired/newer version is already installed. In [here](https://github.com/madskristensen/ExtensionPackTools/blob/master/src/ExtensionManager.Shared/ExtensionService.cs) he's using Microsoft.VisualStudio.ExtensionManager to enumerate. I haven't quite figured out the mechanics of using that assembly from Powershell.

**Comment by dnethi** [comment]
+ @Tim Chen (SH)<mailto:tichen@microsoft.com> to comment..


Thanks,
Dinakar

**Comment by fan130** [comment]
For automate the installation of SSIS designer, you can launch the installer with "/?" argument, it will display the command line options for installing SSIS designer automatically.

Here is the example:
Microsoft.DataTools.IntegrationServices.exe /install:25e4e023 /quiet

Please run this command under elevated privilege

**Comment by tristanbarcelon** [comment]
Thank you @fan130  for your feedback. I actually was able to install SSIS and the 2 VSIX extensions reliably. Unfortunately, they return an error when running the script twice because they are already installed. What I sought in my request here was a method for enumerating existing installed visual studio 2017/2019 addins so I could unregister/uninstall the existing addin before updating to a newer version. This way, it won't matter if the addins were already installed or not.

**Comment by TerryGLee** [comment]
@tristanbarcelon It looks like you have a good idea to pass along by using our “Suggest a feature” option in the [Visual Studio Developer Community]( https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature]( https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) page.​

**Comment by tristanbarcelon** [comment]
Hi @fan130, I tried to use the same installation method for IntegrationServices.exe but this time on Windows Server Core 1803. Is there a specific issue with running the installer on that operating system? I just get an errorcode 1603. Is this OS not supported?

**Comment by fan130** [comment]
Has this log file generated: ssisinstall_24_ISVsix.txt? Actually the log file seems invalid. Windows doesn't support "<user>" as folder name.

**Comment by tristanbarcelon** [comment]
Hi @fan130 , ssisinstall_24_isvix.txt did get generated. The "<user>" value was placed by me to replace a service account I was using at the time.

**Comment by fan130** [comment]
I saw such error message in your log when installing SSAS and SSRS: Could not find Windows Runtime type 'Windows.Networking.Connectivity.NetworkCostType'
Could you confirm whether ssisinstall_24_isvix.txt contains same error message? I expect that the error message would be same because we reused some work from SSAS and SSRS to build our VSIX.

Back to the error message, seems windows server core doesn't have some dll which is required to install our VSIX. Technically our VSIX doesn't directly have dependency on this dll, but I'm not sure if our depended VS components requires this dll. Our biggest depended VS components is Microsoft.VisualStudio.Component.SQL.SSDT. Could you first try to install this component on server core?

**Comment by tristanbarcelon** [comment]
I'll get back to you after tomorrow. The build server which was encountering these installation issue is currently inaccessible due to having lost trust relationship with domain. As far as I could tell, SSDT component (which allows us to build sqlproj files) is there and that's installed by the Microsoft.VisualStudio.Workload.Data workload. This is confirmed by the fact we're able to build repositories that have sqlproj files.

**Comment by fan130** [comment]
Actually from this document: https://docs.microsoft.com/en-us/visualstudio/releases/2019/system-requirements

Server core is not officially supported by VS 2019. So we don't recommend to install and VS2019 and SSIS designer on server core.

**Comment by TerryGLee** [comment]
@tristanbarcelon It looks like your request for support was responded to and possible solutions were provided. Because this venue is meant specifically for documentation feedback on content that resides on https://docs.microsoft.com/visualstudio, we're going to close this issue now. However, should you have more input for us, please see our [Feedback](https://docs.microsoft.com/visualstudio/ide/feedback-options?view=vs-2019) page for a list of all our support options.
