### ISSUE TITLE
vswhere doesn't detect installation

### ISSUE THREAD

**Issue by Rychard** [MicrosoftDocs/visualstudio-docs#3158]
I've used the steps on this page to produce a trimmed-down installation of Visual Studio in order to compile our application.

The build scripts for our application attempt to resolve the path of `msbuild` by using `vswhere`, which is located in a static location regardless of where Visual Studio is installed, shown below:

    C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

However, running this executable inside the container (with or without the `-all` argument) produces no output:

```
PS C:\> & 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -all
Visual Studio Locator version 2.6.7+91f4c1d09e [query version 2.0.2250.60958]
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\>
```

Is there something I must do to allow `vswhere` to detect the installation?

Perhaps this is related to [this issue?](https://github.com/Microsoft/vswhere/issues/178)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
Please file an issue with https://github.com/Microsoft/vswhere for proper tracking. I can also tell you that `-all` just means "products in any state". If you install Build Tools as the documentation describes, you need to pass `-products *`. See https://github.com/Microsoft/vswhere/pull/8.

**Comment by Rychard** [comment]
It appears that the issue was indeed user-error on my part.  I appreciate your timely response.

For completeness, here's the output after including `-products *`, as suggested:

```
PS C:\> $vswhere = Join-Path -Path ${Env:ProgramFiles(x86)} -ChildPath 'Microsoft Visual Studio\Installer\vswhere.exe'
PS C:\> & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
C:\BuildTools
```
