### ISSUE TITLE
Balance Between Extensibility and Unnecessary Complexity

### ISSUE THREAD

**Issue by Oneibus** [MicrosoftDocs/visualstudio-docs#3159]
I would love to see a best practice guide here aimed at describing in detail the design goals of MSBuild extensibility, while warning against complexity for maintenance.  I have already sensed that props and target churn across CPP, Windows SDK and other potential nuget package tricks can lead to a total obfuscation of the build pipeline.  And in some cases incorrectly authored property conditions can lead to unexpected behaviors down stream with tools that were not expecting deviations in properties.  As part of the best practice around this, I would like to see process or tooling for build props and target chain analysis.  A "Dry Run" property and environment evaluation tool to validate props get passed correctly to lower tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3640922f-bdb4-dfee-6b1c-7342e0a89ed2
* Version Independent ID: d33c6cb1-fe9b-656a-ade4-5d488143a898
* Content: [MSBuild Best Practices - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-best-practices?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-best-practices.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-best-practices.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Oneibus** [comment]
As I read more MSBuild documentation here, I see that there is indeed a lot of good How To content.  I understand "How To" does not imply "Best Practice" - though you should sweep the How To documents and land on prescriptions for simplicity and best practice.

Example:  https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2019

**Comment by Mikejo5000** [comment]
We did just add guidelines around .props and .targets for #2774 
I know that doesn't answer this issue fully. Closing though as this work is currently out of scope for us.
