### ISSUE TITLE
Modify string pattern for test discovery

### ISSUE THREAD

**Issue by jelizaga3-gatech** [MicrosoftDocs/visualstudio-docs#3160]
&gt; By convention, Visual Studio identifies tests as methods whose names start with `test`.

Is it possible to modify the process that Visual Studio identifies the string pattern  to discover tests? I.e. see python doc here: https://docs.python.org/3/library/unittest.html#test-discovery

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
* Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
* Content: [Unit test Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/unit-testing-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/unit-testing-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
@jelizaga3-gatech - As discussed in the referenced issue setting a custom test pattern is available as part of the 16.3 release of Visual Studio 2019 and the Unit Testing topic for Python has been updated. If you have any further problems, please feel free to open additional GH issues.
