### ISSUE TITLE
How can I choose same section for more than one configurations? 

### ISSUE THREAD

**Issue by srikcgaa2** [MicrosoftDocs/visualstudio-docs#3165]
I have a requirement where I need to include one ItemGroup for three build configurations and another ItemGroup and three other build configurations.  What is the syntax for having more than one configuration under the When condition?  This information may be updated under https://docs.microsoft.com/en-us/visualstudio/msbuild/choose-element-msbuild?view=vs-2017 as well which is the documentation for the Choose element

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9555b2e3-0394-0e64-e7a2-4e1adc5e99bf
* Version Independent ID: ed70f624-65ad-556c-25c3-08e00415f6cd
* Content: [MSBuild Conditional Constructs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2017#feedback)
* Content Source: [docs/msbuild/msbuild-conditional-constructs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditional-constructs.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ps-gssleap** [comment]
You could put the ItemGroup in a separate file and import it for each of the appropriate configurations.

**Comment by Mikejo5000** [comment]
@srikcgaa2 Did @ps-gssleap 's suggestion work to resolve this?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
