### ISSUE TITLE
Issue with Step 6, In Creating The Model

### ISSUE THREAD

**Issue by RyanMConstable** [MicrosoftDocs/visualstudio-docs#3175]
Issue with step 6 while creating the model. After opening the Northwind_model to replace the two versions of ICollection with ObservableCollection<T> and the first replacement of HashSet with ObservableCollection<T> and finally to change System.Collections.Generic to System.Collections.ObjectModel, while building we ran into 7 errors. We thought we could continue on with the walk through, however, on DataBind the model to the XAML page step 5, we could not open the details for the customers. 
Here is a link to the walkthrough: 
https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2019

**Comment by gewarren** [comment]
@RyanMConstable One of our PMs recently tried out the tutorial and he had no did not encounter any errors. Take a look at his advice [here](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3075#issuecomment-513050915). If you continue to encounter errors after rechecking your work, here are a few options where you might consider asking for help:​

https://social.msdn.microsoft.com/Forums/vstudio
https://www.stackoverflow.com
https://www.reddit.com/r/VisualStudio/
