### ISSUE TITLE
VB.Net doesn't support Shared classes

### ISSUE THREAD

**Issue by DiskCrasher** [MicrosoftDocs/visualstudio-docs#3176]
This error is a bit misleading for VB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4303a22-627d-4024-fee7-40db88a544ac
* Version Independent ID: 37cc2f4d-7002-1b29-cfa4-b8be2924d0a7
* Content: [CA1812: Avoid uninstantiated internal classes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1812-avoid-uninstantiated-internal-classes?view=vs-2019)
* Content Source: [docs/code-quality/ca1812-avoid-uninstantiated-internal-classes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1812-avoid-uninstantiated-internal-classes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@DiskCrasher Good point - I'll update the documentation with this info. It's probably also worth opening an issue at https://github.com/dotnet/roslyn-analyzers/issues to change the error message that shows in the Error List - for example:

"Class2 is an internal class that is apparently never instantiated. If so, remove the code from the assembly. If this is a C# class that is intended to contain only static members, make it static."

**Comment by gewarren** [comment]
Also take a look at https://github.com/dotnet/roslyn-analyzers/issues/1878.
