### ISSUE TITLE
Here's a video walkthrough of how to compile the markup and code-behind example

### ISSUE THREAD

**Issue by annieorben** [MicrosoftDocs/visualstudio-docs#3177]
This could be helpful to provide someone with little to no experience with Visual Studio to see a way to run the first example.

https://youtu.be/0c8tBueI5h0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd07825f-02ab-8a76-44d6-e5163b652d38
* Version Independent ID: e4b4ed91-ce37-5ffc-a98f-2bd4a1ff9643
* Content: [Introduction to WPF - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/introduction-to-wpf?view=vs-2019#feedback)
* Content Source: [docs/designers/introduction-to-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/introduction-to-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@annieorben Thanks so much for pointing out this video and linking it to its corresponding docs article via these issues.

**Comment by annieorben** [comment]
@gewarren. Sorry, I created the video as a suggestion for improving the MSDN documentation. It's good to have several methods of learning available for people to get familiar with what the documentation is explaining.
