### ISSUE TITLE
Meaning of 'BROKEN' code

### ISSUE THREAD

**Issue by ddobric** [MicrosoftDocs/visualstudio-docs#3178]
Sometimes, invoked code on call-tree indicates additionally to 'External Code', invocation of 'Broken' code. What is the meaning of this? Unfortunately in such cases, I'm usually looking exactly at code, which is probably hidden behind 'Broken' instrumentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cbdc658-5505-37f6-3b0b-06cafe7e7c82
* Version Independent ID: c5676187-184a-8c3d-fe25-76e6c56765b0
* Content: [Measure CPU usage in your apps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-performance-profiling?view=vs-2019)
* Content Source: [docs/profiling/beginners-guide-to-performance-profiling.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/beginners-guide-to-performance-profiling.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ddobric I'll ask about this. To clarify, you see code in the call-tree marked as "Broken"?

**Comment by Mikejo5000** [comment]
@ddobric More info:
“Broken” in the stack view means there was an error when trying to walk the stack at that point in time. Could be missing/dropped ETW events.
There is a good chance that collecting the same trace will result in fixing this “Broken” message.
Strictly speaking it isn’t broken, and it’s very unlikely that the code the user wants to see is hidden behind this.
We are however planning on changing this message to “Unwalkable stack” or something similar in the next release.

**Comment by ddobric** [comment]
I guess, in this specific case, the problem was that no events were collected. However, this can mean, that some error happened (I couldn't have noticed any) or events have not been collected. But in a second case, this must be clear (provide information = better message than "broken") solvable by changing of sample rate, which didn't help.

**Comment by Mikejo5000** [comment]
Adding note
