### ISSUE TITLE
Unable to attach snapshot debugger to azure functions

### ISSUE THREAD

**Issue by AjayKumar-MSFT** [MicrosoftDocs/visualstudio-docs#3182]
[Re-posting customer's feedback here to get the doc source context and for quicker traction: 
For more details and screenshots on the issue refer this GitHub post: https://github.com/MicrosoftDocs/azure-docs/issues/29654]

" 
I am using Visual studio Enterprise 2019 and trying to attach snapshot debugger to azure function but not able to do so.
I am not getting any azure resource for snapshot debugging as per below screenshot
-Screenshot in the above GitHub URL-

While storage account selection is working as expected for me as per below screenshot:
-Screenshot in the above GitHub URL-

" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f13f80-a3b0-9602-db14-48130d47ef7c
* Version Independent ID: 96ee1b24-bc43-5e46-f645-f4ccfe9f1ba1
* Content: [Debug live ASP.NET Azure apps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-applications?view=vs-2019)
* Content Source: [docs/debugger/debug-live-azure-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-live-azure-applications.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
