### ISSUE TITLE
There is actually a way to build the vue-cli 3.0 project as a pre-build event.

### ISSUE THREAD

**Issue by tylermercer** [MicrosoftDocs/visualstudio-docs#3183]
You just have to put these three lines in the pre-build event command line box:
```
cd ./ClientApp
npm run build
cd ../
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a644716-10c3-cc90-eeab-495c265e5728
* Version Independent ID: c356a0d8-1d24-2ab7-18de-b9b3088fd4d9
* Content: [Create a Vue.js app using Node.js - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/create-application-with-vuejs?view=vs-2019#feedback)
* Content Source: [docs/javascript/create-application-with-vuejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/create-application-with-vuejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by tylermercer** [comment]
You can also install [NodeJsAndNpm](https://www.nuget.org/packages/NodeJSAndNpm/) and set up the build as a BeforeBuild target in your project's .csproj.

**Comment by Mikejo5000** [comment]
@tylermercer Thanks, so this is an update to the section "Build with vue-cli 3.0", correct? I don't see a pre-build event command line box. Where do you see that?

**Comment by Mikejo5000** [comment]
Nevermind. I see it in the ASP.NET project properties. Thanks!

**Comment by Mikejo5000** [comment]
Updating doc
