### ISSUE TITLE
Where is the DLL for Office365 interop?

### ISSUE THREAD

**Issue by jgfet** [MicrosoftDocs/visualstudio-docs#3185]
see subject!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88fddd73-1fac-2149-71db-5f20c8c94934
* Version Independent ID: 46e037ee-a5fd-7274-b072-8df92ce70eda
* Content: [Office primary interop assemblies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/office-primary-interop-assemblies?view=vs-2019)
* Content Source: [docs/vsto/office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/office-primary-interop-assemblies.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@jgfet just to be clear these interop assemblies are for use with the Office Client on the desktop not Office in the browser.  If that's what you're looking for and you're using Visual Studio.  For VS 2017 and 2019 you can find them under: %ProgramFiles(x86)%\Microsoft Visual Studio\Shared\Visual Studio Tools for Office\PIA\.  Earlier versions are inside the VS folder: %ProgramFiles(x86)%\Microsoft Visual Studio 14.0\Visual Studio Tools for Office\PIA

**Comment by John-Hart** [comment]
#please-close

**Comment by khamille** [comment]
Hello, I am not seeing the "Visual Studio Tools for Office" directory in %ProgramFiles(x86)%\Microsoft Visual Studio\Shared. The Microsoft website says, that the .NET Programmability Support feature is included in the default installation. Please help.

**Comment by John-Hart** [comment]
@khamille please make sure you've selected the Office Workload and the Visual Studio Tools for Office to be installed when you install Visual Studio 2017 or 2019.  If you're still having problems I just sending feedback through the Visual Studio Help menu.

**Comment by GaffaneyB** [comment]
Re-running the VS 2019 Installer to add Office Workload and VS Tools for Office was the answer! Thanks John-Hart!!!

I dug around on the web for hours before finding this post!!
