### ISSUE TITLE
False positive with a field not locally created

### ISSUE THREAD

**Issue by jherby2k** [MicrosoftDocs/visualstudio-docs#3188]
I'm getting false positives if an IDisposable field is not disposed, even if the object was not locally created. It only happens if the class implements IDisposable.

```c#
    sealed class StreamTest : IDisposable
    {
        readonly Stream _stream;

        public StreamTest(Stream stream)
        {
            _stream = stream;
        }

        public void Dispose()
        {
            // _stream shouldn't get disposed in this class!
        }
    }
```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7193fffc-ff49-d551-417e-6f004dd1e216
* Version Independent ID: 8370a61d-8d8a-bec4-b49d-e5cae67a0d86
* Content: [CA2213: Disposable fields should be disposed - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed?view=vs-2019)
* Content Source: [docs/code-quality/ca2213-disposable-fields-should-be-disposed.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2213-disposable-fields-should-be-disposed.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by jherby2k** [comment]
Opened https://github.com/dotnet/roslyn-analyzers/issues/2413

**Comment by gewarren** [comment]
Closing in favor of the roslyn-analyzers issue.
