### ISSUE TITLE
Outdated Products by Benefit Level Spreadsheet

### ISSUE THREAD

**Issue by LMoyer** [MicrosoftDocs/visualstudio-docs#3191]
Can you please provide the most up to date Products by Benefit Level spreadsheet?  I send this out to colleagues who request VS/MSDN and I'm guessing this one from 2017 is not fully accurate.  Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ab4ecc-3cca-8224-8b30-7bccd1ebae31
* Version Independent ID: 2e89b277-021e-b185-ea1a-bc153481b0e1
* Content: [Using Subscriber Downloads on Visuals Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/subscriber-downloads#feedback)
* Content Source: [subscriptions/subscriber-downloads.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/subscriber-downloads.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by mhyon** [comment]
It looks like the "download the full list" link near the top under "Product availability" needs to be updated to http://download.microsoft.com/download/1/5/4/15454442-CF17-47B9-A65D-DF84EF88511B/Visual_Studio_by_Subscription_Level.xlsx like the "Products By Benefit Level" in the "What do I get?" section.

**Comment by LMoyer** [comment]
Thanks!  This looks more accurate than before-- I'm seeing VS Pro 2017 and 2019 which were not there previously.  Appreciate your assistance!

**Comment by evanwindom** [comment]
@TerryGLee Please close this. Thanks.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for your follow-up; closing this now.
