### ISSUE TITLE
Activation online never is available

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/visualstudio-docs#3193]
MSDN Subscriber Benefits used to provide a phone number for incident reporting.  The Live Chat feature is never available when I try to use it, so I haven't been able to activate my support because of that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79453c-3962-2f0c-5b99-4fbde91972f8
* Version Independent ID: c845c29e-dfd7-316e-81b2-ebe288a384c1
* Content: [Technical Support Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-tech-support)
* Content Source: [subscriptions/vs-tech-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-tech-support.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@varnk My apologies for not getting this answered sooner.  I checked with the support teams, and they're not aware of any outages.  If you experience another outage, please contact us at 800-936-5800.  You can set up your support at that number, and they can escalate any outage issues.  Thanks!

**Comment by TerryGLee** [comment]
@evanwindom Thanks for responding to @varnk; we'll close this issue now.
