### ISSUE TITLE
Linked page does not say how to resolve the CA0507 warning

### ISSUE THREAD

**Issue by SergioEduardoAntonio** [MicrosoftDocs/visualstudio-docs#3194]
Aviso CA0507 “Run Code Analysis” has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to FxCop analyzers. Ativo”

I think that here in Brazil we have a tranlation mistake in this link “https://docs.microsoft.com/pt-br/visualstudio/code-quality/fxcop-analyzers?view=vs-2019” and this mistake dont teach the correct way to fix the warning CA0507. Please let me know how to fix it on Visual Studio 2019 running on Windows 10 Pro (Brazilian Portuguese).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019#feedback)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by SergioEduardoAntonio** [comment]
Aviso CA0507 “Run Code Analysis” has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to FxCop analyzers. Ativo”
I think that here in Brazil we have a tranlation mistake in this link “https://docs.microsoft.com/pt-br/visualstudio/code-quality/fxcop-analyzers?view=vs-2019” and this mistake dont teach the correct way to fix the warning CA0507.
Please let me know how to fix it on Visual Studio 2019 running on Windows 10 Pro (Brazilian Portuguese).

**Comment by JasonCard** [comment]
@SergioEduardoAntonio Could you please help to specify which sentence has the translation mistake? If you have a suggested translation, then please go to [https://docs.microsoft.com/pt-br/visualstudio/code-quality/fxcop-analyzers?view=vs-2019](https://docs.microsoft.com/pt-br/visualstudio/code-quality/fxcop-analyzers?view=vs-2019), click and the "Edit" button and open a PR with your suggested translation.
cc @gewarren

**Comment by SergioEduardoAntonio** [comment]
Dear Jaso Card,

Could you please help me to find in the referred link, how can I follow the recommendation that is present on Visual Studio 2019 Community that I am send you back again attached with this email.
I mentioned on Developers Community  that "I think that here in Brazil we have a translation mistake in this link "https://docs.microsoft.com/pt-br/visualstudio/code-quality/fxcop-analyzers?view=vs-2019" and this mistake dont teach the correct way to fix the warning CA0507."
And in my comprehension I'm not asserting that in the link has the translation mistake?
Than please show me where, following the link, can I find how to solve Visual Studio recommendation message that I am send to you because I am still receiving the warning "
Gravidade

Código

Descrição

Projeto

Arquivo

Linha

Estado de Supressão

Aviso

CA0507

"Run Code Analysis" has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to FxCop analyzers.







Ativo

" .

Regards,

Sergio Eduardo Antonio.


De: Jason Card <notifications@github.com>
Enviada em: sexta-feira, 3 de maio de 2019 20:21
Para: MicrosoftDocs/visualstudio-docs <visualstudio-docs@noreply.github.com>
Cc: Sergio Eduardo Antonio <sea-56@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [MicrosoftDocs/visualstudio-docs] Localization error (Brazilian Portuguese) (#3194)


@SergioEduardoAntonio<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSergioEduardoAntonio&data=02%7C01%7C%7C71e0d2b737a8410eea4e08d6d01e0322%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636925224648579979&sdata=leeVJnX0pdTd9oWxOaMhpXpUoLbBU7Bmp5MLh7ASRq8%3D&reserved=0> Could you please help to specify which sentence has the translation mistake? If you have a suggested translation, then please go to https://docs.microsoft.com/pt-br/visualstudio/code-quality/fxcop-analyzers?view=vs-2019<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fpt-br%2Fvisualstudio%2Fcode-quality%2Ffxcop-analyzers%3Fview%3Dvs-2019&data=02%7C01%7C%7C71e0d2b737a8410eea4e08d6d01e0322%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636925224648589978&sdata=9Wbqdjl%2ByyhWAirffOsVwl%2F%2Fjn13bBcR7y3DCw2BqKI%3D&reserved=0>, click and the "Edit" button and open a PR with your suggested translation.
cc @gewarren<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgewarren&data=02%7C01%7C%7C71e0d2b737a8410eea4e08d6d01e0322%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636925224648599983&sdata=B4Jgh41YHqf3uzZyTQnw1BRy1fyEBoGYc%2Fm0X2xwDIg%3D&reserved=0>

-

**Comment by JasonCard** [comment]
@SergioEduardoAntonio If I understand you correctly, you are not asserting that there is translation mistake, but you are asking for information on how to fix the warning CA0507. 
I'm managing the localization, so if there is no translation issue, then I will let the English writer @gewarren help you with this question.

**Comment by gewarren** [comment]
@SergioEduardoAntonio Sorry for the confusion. I think I see what the problem you're stating is now. The solution to your issue is likely to add the following msbuild property to your project file to turn off static code analysis:

```
<RunCodeAnalysis>false</RunCodeAnalysis>
```

That solution is explained [here](https://docs.microsoft.com/pt-br/visualstudio/code-quality/fxcop-analyzers-faq?view=vs-2019#i-get-warning-ca0507-even-after-ive-installed-the-fxcop-analyzers-nuget-package).

**Comment by gewarren** [comment]
That's a good question. @mavasani can you comment on why unchecking "Enable Code Analysis on Build" doesn't also set the msbuild property in the project file to false?

`<RunCodeAnalysis>false</RunCodeAnalysis>`

**Comment by mavasani** [comment]
@gewarren that might be a bug. Hopefully, the checkbox will be removed soon and not lead to any confusion. For time being, hopefully the workaround to edit the project file is sufficient.
