### ISSUE TITLE
Add note about dispose ownership transfer for special cases

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3198]
We need to add documentation to CA2000 and CA2213 rule about special cases of dispose ownership transfer: https://github.com/dotnet/roslyn-analyzers/issues/2413#issuecomment-489175251 to align with majority of common code patterns. Users can suppress these violations if there is no dispose ownership transfer happening for their code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c370a407-b61d-0de6-6ac4-9b0ab49216b9
* Version Independent ID: a96e421e-65d3-07ba-097e-3feff2b3c677
* Content: [CA2000: Dispose objects before losing scope - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2019)
* Content Source: [docs/code-quality/ca2000-dispose-objects-before-losing-scope.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2000-dispose-objects-before-losing-scope.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Can you review these changes please?

https://review.docs.microsoft.com/en-us/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed?view=vs-2017&branch=pr-en-us-4620#rule-description
https://review.docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2017&branch=pr-en-us-4620#rule-description

**Comment by mavasani** [comment]
@gewarren Thanks, those look good to me. I think you also want to enhance the `When to suppress warnings` section to mention that it might be fine to suppress a flagged CA2000 violation if the allocating method does not have dispose ownership (it is transferred to some other object or wrapper created in the method and returned to the caller) AND fine to suppress a flagged CA2213 violation if the dispose ownership of the disposable object held by the flagged field is not with the containing type.
