### ISSUE TITLE
..

### ISSUE THREAD

**Issue by dddns** [MicrosoftDocs/visualstudio-docs#3199]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e23c15-7abd-d973-48c0-e4b23e305c5c
* Version Independent ID: 97329301-f6ac-4cba-8b85-a958a0bfc1a5
* Content: [Set color theme and fonts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-personalize-the-ide?view=vs-2019)
* Content Source: [docs/ide/quickstart-personalize-the-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-personalize-the-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by thomps23** [comment]
@dddns It looks like the tool didn't catch your feedback. If you could provide more information it will help use triage.

**Comment by TerryGLee** [comment]
@dddns Closing until we get further info.
