### ISSUE TITLE
There is no "Code Analysis" tab

### ISSUE THREAD

**Issue by ManfredLange** [MicrosoftDocs/visualstudio-docs#3201]
I've got a C# project for a class library and following the instructions in this page, there is no "Code Analysis" tab.

I've checked all tabs available for the project, and none of them has a "Enable Code Analysis on Build" check box.

I'm using VS 2019. The library is C# of type "Class Library" and targeting ".NET Framework 4.6.2". The project file format is the new one where the first line is `&lt;Project Sdk="Microsoft.NET.Sdk"&gt;`

Perhaps it'd make sense to review this page and update it to match with current products.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 573429a4-7c2d-5ede-9c34-934cc26a4045
* Version Independent ID: 351b628e-ff1c-7a64-0c46-74887a97cd0d
* Content: [Enable or disable code analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code?view=vs-2019)
* Content Source: [docs/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-enable-and-disable-automatic-code-analysis-for-managed-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ManfredLange I just created a new class library project for .NET Framework and I have the Code Analysis tab. Can you tell me how you created this project?
