### ISSUE TITLE
unity project explore

### ISSUE THREAD

**Issue by BigBrotherLi** [MicrosoftDocs/visualstudio-docs#3203]
Article problem sections:

https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2019#debug-in-the-unity-editor

https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2019#keyboard-shortcuts

**Comment by BigBrotherLi** [comment]
I cant find Unity Project Explore in View and there is no Attach Unity and Play button.

**Comment by gewarren** [comment]
@BigBrotherLi Can you let us know which documentation page this in in reference to? That info wasn't captured unfortunately.

**Comment by BigBrotherLi** [comment]
Thank you for reply.I want to use Visual Studio 2019 with Visual Studio Tools for Unity.Then, i read the Visual Studio 2019 Doc, page name is Use Visual Studio Tools for Unity.There are many problem i have get.There is no Button named Attach to unity and Attach to unity play, but a run debug button.If i want to debug to unity, i can not use F5 to start.I can only debug unity by click menu Debug and Attack to Unity.Well, it dose not matter.Then, i want to use Unity Project Explore, but the keyboard is invalid, and cant find any info in menu.Of caurse i set unity right as the doc write, and Vsisual Studio Tools for Unity build success.




------------------ 原始邮件 ------------------
发件人: "Genevieve Warren"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 上午7:29
收件人: "MicrosoftDocs/visualstudio-docs"<visualstudio-docs@noreply.github.com>;
抄送: "0杨路0"<1025394400@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [MicrosoftDocs/visualstudio-docs] unity project explore (#3203)




@BigBrotherLi Can you let us know which documentation page this in in reference to? That info wasn't captured unfortunately.

**Comment by gewarren** [comment]
@therealjohn @crdun Can you take a look at this issue?

**Comment by therealjohn** [comment]
@BigBrotherLi 

Visual Studio 2019 requires Unity 2018.3 or higher. If you're already using that version, take a peek at the troubleshooting steps we have and make sure that Visual Studio Tools for Unity is loaded by following the steps in the guide: https://docs.microsoft.com/en-us/visualstudio/cross-platform/troubleshooting-and-known-issues-visual-studio-tools-for-unity?view=vs-2017

If you continue having issues, please use the Help > Send Feedback > Report a Problem to log an issue. We'll be able to better track the problem through Developer Community. Thanks!

**Comment by therealjohn** [comment]
@gewarren this can be closed. There is no documentation issue here.

**Comment by gewarren** [comment]
@therealjohn Thanks!
