### ISSUE TITLE
Inverted colors for dark theme

### ISSUE THREAD

**Issue by mmatrosov** [MicrosoftDocs/visualstudio-docs#3204]
We use Visual C++ Project templates in our company with custom icons. When Visual Studio uses dark theme, colors on these icons are inverted in the new project dialog. How to prevent this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40b8aae3-9be4-7879-3826-d8cf29a573e2
* Version Independent ID: 133d7fbe-a485-6cb5-2eb5-3efbc131634b
* Content: [Icon Element (Visual Studio Templates) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/icon-element-visual-studio-templates?view=vs-2019#feedback)
* Content Source: [docs/extensibility/icon-element-visual-studio-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/icon-element-visual-studio-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by acangialosi** [comment]
Assign to vixmix for followup.
