### ISSUE TITLE
Do I need to say where boost is installed?

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/visualstudio-docs#3205]
&gt; Run vcpkg integrate install to configure Visual Studio with the library and include paths to the Boost headers and binaries.

I tried to get this to work for VS 2017 15.6, but to no avail.  It doesn't show up in my new projects.  I've tried to restart VS with no  effect either. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45fbddc-51f2-1c42-eaf2-f78e6220a9e7
* Version Independent ID: 1ce72223-80ab-651a-40f3-dc8112b2a3cf
* Content: [How to use Boost.Test for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp?view=vs-2019)
* Content Source: [docs/test/how-to-use-boost-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-boost-test-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
I just tried this on a new machine and it works as expected...well up to the point where a linker error is generated---I'm investigating that with the product team now.

Clone vcpkg from github.
From powershell, cd to vcpkg folder and run
     .\bootstrap-vcpkg.bat
     .\vcpkg integrate install
     .\vcpkg install boost

Open VS, from the project node in Solution Explorer, click on Add > New Item and then click Test in the left pane. Choose Boost.Test and a .cpp file is added to your project with the include paths already set up (that's was vcpkg integrate install does). 

But as I said I'm getting a linker error at that point so not sure how to deal with that at the moment.

**Comment by corob-msft** [comment]
I'm not sure if the instructions for adding a Boost test source file to an existing project ever worked. The only way I could get it to work was by creating a special test configuration to build a test version, and excluding the test source file from the Debug and Release versions. I've updated the procedures to match. Some automation will be along to close this issue shortly.
