### ISSUE TITLE
No Boost.Test Template project

### ISSUE THREAD

**Issue by okmechak** [MicrosoftDocs/visualstudio-docs#3209]
Reproducing step by step this instruction.. in the end there where no Boost.Test template project(on both Visual Studio 2017 and 2019) also I configured Unit Test project by myself(to use Boost Test framework, binaries of boost from oficial page on sourceforge, then General-&gt;VCDirectories include and libraries was configured, DLL, and linker input: libboost_unit_test_framework-vc141-mt-x64-1_69.lib;), but Test Explorer did't find it.
Regards, 
Oleg.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45fbddc-51f2-1c42-eaf2-f78e6220a9e7
* Version Independent ID: 1ce72223-80ab-651a-40f3-dc8112b2a3cf
* Content: [How to use Boost.Test for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp?view=vs-2019#feedback)
* Content Source: [docs/test/how-to-use-boost-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-boost-test-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@okmechak Boost.Test is available as an _item_ template, not a project template. Right click on the project in Solution Explorer, then Add > New Item and look for "Test" in the left pane. Click on that and you will see Boost.Test and Google Test.

**Comment by okmechak** [comment]
> @okmechak Boost.Test is available as an _item_ template, not a project template. Right click on the project in Solution Explorer, then Add > New Item and look for "Test" in the left pane. Click on that and you will see Boost.Test and Google Test.

Thanks for pointing this out! Tested it on vs 2019 and it works as should(Test Explorer too).

PS: May I ask how it works? In properties of test.cpp(that one created by Boost.Test item template) file I found that it inludes dir $(Vcpkg)inlude, but how it links *.lib files?

Best,
Oleg
