### ISSUE TITLE
Signature Help Documentation

### ISSUE THREAD

**Issue by Bloodb0ne** [MicrosoftDocs/visualstudio-docs#3210]
While fooling around with IClassifiers and the flexibility customizing the editor. When i specify [Content-Type("sighelp")] i can classify the signature but the text buffer doesnt cover the doc string, so then i tried [Content-Type("sighelp-doc")] and it doesnt trigger at all. Are there any specifics into classifying [Content-Type("sighelp-doc")] or customizing the documentation string in the signature help ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c80f34ed-f876-6490-af53-dd6968ad6591
* Version Independent ID: 51cd1707-9139-8873-51e8-237a153bd0a9
* Content: [Language Service and Editor Extension Points - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/language-service-and-editor-extension-points?view=vs-2019#feedback)
* Content Source: [docs/extensibility/language-service-and-editor-extension-points.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/language-service-and-editor-extension-points.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by madskristensen** [comment]
@gundermanc can you help?

**Comment by gundermanc** [comment]
I don't have too much experience with SigHelp. @olegtk ?

**Comment by WilliamAntonRohm** [comment]
@Bloodb0ne -- Emilian, thank you for your question. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

My apologies for the delay in responding.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
