### ISSUE TITLE
wrong project type mentioned

### ISSUE THREAD

**Issue by ish-1313** [MicrosoftDocs/visualstudio-docs#3211]
it seems, that this tutorial about windows forms, not about wpf 
so, the create project part should be corrected
tia

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18ba8b48-f46a-62fc-1177-aefcd958e6ff
* Version Independent ID: 19f09429-5fc2-a039-f8bd-3a7de1f93fe6
* Content: [Step 1: Create a project and add labels to your form - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-1-create-a-project-and-add-labels-to-your-form?view=vs-2019&fbclid=IwAR0Q62m5_asBZVs3OPfyoNe-mnXDqYPR7v4gYtn9edxvzv9OPLzexbUehqI#feedback)
* Content Source: [docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-1-create-a-project-and-add-labels-to-your-form.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ish-1313 Thanks for your inpuy; we'll take a look and report back.

**Comment by TerryGLee** [comment]
@ish-1313 Thanks again for submitting this GitHub Issue to us. We've changed the project type from WPF to Windows Forms; the change should be published on Monday 6/3/2019 by noon Pacific Daylight Time. We appreciate your help in improving our documentation!
