### ISSUE TITLE
Big fubar

### ISSUE THREAD

**Issue by garyhutto** [MicrosoftDocs/visualstudio-docs#3212]
this process SUCKS. What kind of idiots developed it? You GDI"s made what should have been a simple one location action into multiple platforms, NEW accounts and the installation of TWO additional apps. your product manager should be incarcerated and never allowed to work in  the INDUSTRY again. You incompetent analysists and coders should seek employment in food retail (BURGER KING). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd4d05c-4aa3-0376-f3a1-b0ea0793f482
* Version Independent ID: 7f1ff943-61b0-60e1-9ca3-d4a84bfdb068
* Content: [Install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by jillre** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so we have closed it.
