### ISSUE TITLE
How about targetting different netcore versions?

### ISSUE THREAD

**Issue by RowlandShaw** [MicrosoftDocs/visualstudio-docs#3213]
This is great for .Net Framework, but how can I set a project template up to target .Net Core 2.2 (or later)? Or is my assumption that the template then won't show if the 2.2 workload is not installed false?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8aa305bd-12c4-689f-1398-bae83bde4ba4
* Version Independent ID: 67a2e7ec-f55e-80b9-dec0-054891f3861b
* Content: [Target the .NET Framework - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2019)
* Content Source: [docs/ide/visual-studio-multi-targeting-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-multi-targeting-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
I believe that the template would still show as available even if .NET Core 2.2 wasn't on the machine. @prnadago to confirm.

**Comment by RowlandShaw** [comment]
Still be good to add to the docs what to put in there for targetting .net core versions (appreciate point will become moot with 5, but that's over a year away)

**Comment by gewarren** [comment]
Edit to trigger priority labeling.

**Comment by gewarren** [comment]
@RowlandShaw You are asking how to set the target framework in a project _template_, correct? I created a .NET Core 2.2 project and then [exported it as a template](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates?view=vs-2019). The project file in the template contains the following - `TargetFramework` specifies the .NET Core version:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
  </PropertyGroup>
</Project>
```

For a .NET Core 3.0 project, the `TargetFramework` value would be `netcoreapp3.0`.
