### ISSUE TITLE
Dependency Injection (Interface/Class) Nesting

### ISSUE THREAD

**Issue by snelljef** [MicrosoftDocs/visualstudio-docs#3214]
Using this, how would you nest Interfaces with their class with Dependency Injection classes? For example, IBlahRepository.cs nested with BlahRepository.cs. Unless I am missing something obvious, I don't see a way to handle file prefixes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019#feedback)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by gewarren** [comment]
@AngelosP Could you comment on this issue?

**Comment by AngelosP** [comment]
The comment by snelljef is accurate. The framework is extensible and snelljef could write custom rules to achieve the desired functionality. I was waiting for sample code on how to achieve that before responding, but other priorities have pushed this back a bit. I will still update this comment with sample code once I have it.

**Comment by snelljef** [comment]
@AngelosP Very cool. Didn't realize we could expand on this. Looking forward to the example. Might try investigating this ahead of it even.

**Comment by AngelosP** [comment]
It turns out that the extensibility point is not public and you are not able to extend the nesting logic at the moment. We have added an item on our backlog to make the extensibility point public in an upcoming release. Until then I'm afraid that the scenario you are describing will not be possible.
