### ISSUE TITLE
MSTest run settings section is incomplete

### ISSUE THREAD

**Issue by alainbryden** [MicrosoftDocs/visualstudio-docs#3217]
The documentation on the following page appears out of date, at least for the &lt;MSTest&gt; settings:
https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#mstest-run-settings

For instance, I understand that for almost a year now a &lt;Parallelize&gt; configuration can be provided, e.g.:

```xaml
  <MSTest>
    <Parallelize>
      <Workers>32</Workers>
      <Scope>MethodLevel</Scope>
    </Parallelize>
  </MSTest>
```

It would great to see what else has been made in the way of improvements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#mstest-run-settings)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@AbhitejJohn Should `<Parallelize>` be added to this document?

**Comment by AbhitejJohn** [comment]
@gewarren , @alainbryden : it'd probably be nice to add all these new features in a runsettings format under https://github.com/microsoft/testfx-docs and add a comment in docs linking to this, because that's where all documentation for MSTest is kept up-to-date. I've filed [this](https://github.com/microsoft/testfx-docs/issues/74) issue in testfx to track that.

**Comment by gewarren** [comment]
Keeping this issue open until the testfx-docs issue is fixed, and then we'll link to that document.
