### ISSUE TITLE
example is incorrect- _Lock_level_order_ is broken

### ISSUE THREAD

**Issue by tyotypic** [MicrosoftDocs/visualstudio-docs#3219]
At least in VS2017, the given snippet does not produce *any* Code Analysis warning. 

Also, this document is wrong, in that the annotation _Set_lock_level_order_(a,b) has been replaced by _Lock_level_order_(a,b). (I assume, given the evidence)

It was very useful, however, that this document specified what relationship _Set_lock_level_order_(A,B) implied between A and B, as the main SAL locking annotation document does not: https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-locking-behavior?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ee573a6-7960-da77-2362-78f207f18b3d
* Version Independent ID: b2dd782b-f622-cb9c-f24a-c9948f95259e
* Content: [C26105 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26105?view=vs-2019#feedback)
* Content Source: [docs/code-quality/c26105.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26105.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by hwisungi** [comment]
These annotations apply to Concurrency Check. Can we ask the customer to enable one of the following rules and retry?
- Microsoft All Rules
- Concurrency Rules
- Concurrency Check Rules

BTW, Microsoft Native Recommended and Microsoft Minimum Rules do not generate concurrency warnings.

I would expect customers who are interested in Concurrency warnings know how to run the analysis to get concurrency warnings. If that is not a proper assumption, we may want to add some template text to all concurrency checker related documentations.

**Comment by hwisungi** [comment]
BTW, here are the example warnings:
Source3.cpp(25): warning C26105: Lock order violation. Acquiring lock 'gMutex' with level "MutexLockLevel" causes order inversion.
Source3.cpp(26): warning C26105: Lock order violation. Acquiring lock 'pTunnel->cs' with level "TunnelLockLevel" causes order inversion.
Source3.cpp(28): warning C26165: Possibly failing to release lock 'gMutex' in function 'OrderInversion'.

**Comment by hwisungi** [comment]
As for the reference to "_Set_lock_level_order_" in the description should be changed to _Lock_level_order_ as pointed out by the customer.

**Comment by tyotypic** [comment]
Hi. Thank you for pointing out that I was using the wrong ruleset. On "Microsoft All Rules", the code snippet produces the expected warnings. I am very satisfied now that I can begin to annotate my legacy codebase with locking levels.

I would strongly agree with adding some template text on concurrency checker documentation. I approached these concurrency annotations through the more general SAL documentation (rather than through knowledge of the code analyser), and I'll admit I may not have read it closely enough, but I certainly don't remember the SAL documentation saying specific rulesets needed to be active. I would also have expected to read, on the C26105 warning page itself, which rulesets would generate the warning, much like the C++ warnings say which warning level they generated by.

One more thing to consider, a source of my confusion was probably that more basic concurrency warnings _are_ generated by "Microsoft Native Recommended Rules". The following code will generate a "warning C26110: Caller failing to hold lock '& l2' before calling function 'Lock_2::use_self'." under "Microsoft Native Recommended Rules" in VS2017:

#pragma region test2
struct Lock_2
{
	_Acquires_lock_(this)
		void aquire_self()
	{
	}

	_Releases_lock_(this)
		void relenquish_self()
	{
	}

	_Requires_lock_held_(this)
		void use_self()
	{
	}
};

void test2()
{
	Lock_2 l2;
	//l2.aquire_self();
	l2.use_self();
}
#pragma endregion test2

Thanks for your time.

**Comment by mikeblome** [comment]
thanks @tyotypic for your helpful feedback. I have updated the topics you refer to and will update the individual warning topics when I get a list of which ones require the Concurrency rule sets. Fix should be live in a couple of days.
