### ISSUE TITLE
CMake docs don't mention how to use launch.vs.json with variables

### ISSUE THREAD

**Issue by rchiodo** [MicrosoftDocs/visualstudio-docs#322]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/6ee19c57958de69dabb7669347af8dec8df6de54/docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md

doesn't describe how the variables in use inside of the CmakeSettings.json can be applied to launch.vs.json. 

See customer feedback here:
https://developercommunity.visualstudio.com/content/problem/32446/workspaceroot-and-name-cannot-be-used-when-configu.html

We should document how to use those variables in launch.vs.json (for example that you need to prefix some of the variables with "cmake." before they can be used outside of the CMakeSettings.json.)

**Comment by gewarren** [comment]
Thanks @rchiodo . I think the appropriate topic for this request is https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp#cmake_settings.

**Comment by mikeblome** [comment]
moved to internal database for tracking
