### ISSUE TITLE
Web App for Containers

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/visualstudio-docs#3220]
Am I correct in understanding that the App Service and App Service Linux options for deployment do not offer the ability to deploy as a Web App for Containers at this time?
I'm working with a customer who has a "Container Registry" option on the screen in Step 4 (after choosing App Service Linux), but the App Service ultimately created does not have the "Container settings" menu that we would expect to see on a Web App for Containers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d91844e-d0d6-362a-eae7-575a0b03505f
* Version Independent ID: dc6bc695-7c25-8cb2-f4bd-12a866587bb2
* Content: [Publish to Azure App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-azure?view=vs-2019)
* Content Source: [docs/deployment/quickstart-deploy-to-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/quickstart-deploy-to-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ghogen Gordon, is there a doc that includes deploying a Web App for Containers?

**Comment by Mikejo5000** [comment]
Gordon, I think you will have some insight on this. Can you assign back to me if a doc update here is required?

**Comment by dcbrown16** [comment]
Internally I have heard that Visual Studio may need to reconfigure some settings to make the portal expose the Container Settings menu.

**Comment by ghogen** [comment]
This is a product issue, which is already planned to be addressed in an update to Visual Studio. I think we can close this as a doc issue.
