### ISSUE TITLE
Configure your new project page

### ISSUE THREAD

**Issue by nitinjs** [MicrosoftDocs/visualstudio-docs#3221]
there is no Configure your new project page in my vs 2019,

how do I go back to old project creation dialog?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b25eea-0531-fc29-14c3-97b01d3c9ffc
* Version Independent ID: 93399d12-64f7-aa0c-f7d6-7ed8ecd95086
* Content: [Create a new project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-new-project?view=vs-2019#feedback)
* Content Source: [docs/ide/create-new-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-new-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@nitinjs What type of project did you create that you didn't see the Configure page? There's no way to use the old "new project dialog" in VS 2019, unfortunately.

**Comment by softworkz** [comment]
@gewarren - no longer correct...​

For all those being annoyed by the new dialog (same like me):

Check out this extension:

**Classic 'New Project' Dialog**

https://marketplace.visualstudio.com/items?itemName=softworkz.SwitchProjectDialog

**Brings back the classic 'New Project' Dialog for Visual Studio 2019**

**Comment by MantieReid** [comment]
@softworkz  Thank you.  This extension solves this problem for now.
