### ISSUE TITLE
Company name pre-populated with my laptop manufacturer

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/visualstudio-docs#3222]
It would be nice to know where to change the default values for these fields. On my new laptop, Company name and Copyright are both populated with the laptop manufacturer and not my company.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1490ea17-1bce-6eb1-0a78-1b8159b82e4e
* Version Independent ID: 4350b38b-6f06-16b6-da75-4d85c6c43909
* Content: [Assembly Information Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/assembly-information-dialog-box?view=vs-2019)
* Content Source: [docs/ide/reference/assembly-information-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/assembly-information-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@dombat I'm updating the article with this info now. The answer is that the Company value comes from the **RegisteredOrganization** value in the registry. Look for this value under **Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows NT\CurrentVersion** or **Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion**, depending on whether you're using 64-bit Windows or not.
