### ISSUE TITLE
Where did app.py come from?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#3225]
@okssss commented on [Thu May 09 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/42)

Откуда вдруг взялся файл  app.py (Написано "The contents of app.py appears as follows when using the name "HelloDjangoApp":")

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 09d5f2d3-bebb-5564-87df-8ab0eedb410c
* Version Independent ID: c1dac521-a8f2-1b81-af35-bd9da71fb6e8
* Content: [Руководство по Django в Visual Studio. Шаг 2. Представления и шаблоны страниц](https://docs.microsoft.com/ru-ru/visualstudio/python/learn-django-in-visual-studio-step-02-create-an-app?view=vs-2017#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-02-create-an-app.md](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/blob/live/docs/python/learn-django-in-visual-studio-step-02-create-an-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the user is suggesting additional information on the original documentation
Translation:

> Where did the app.py file come from (Written by "The contents of the app.py"
> When using the HelloDjangoApp name, the app.py file has the following contents:

**Comment by JoshuaPartlow** [comment]
Addressed in mentioned PR.
