### ISSUE TITLE
Import .editorConfig

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/visualstudio-docs#3227]
Feature request:

Code Styles would be a nice editor for .editorconfig files if we could import them.

I maintain a editorconfig file but then if I reset VS I have to go through and reapply them all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faebd126-53cd-1a98-bf75-38225933b0f2
* Version Independent ID: 4340fcba-6779-68d2-6c51-2ae37123dc26
* Content: [Code style options and code cleanup - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#feedback)
* Content Source: [docs/ide/code-styles-and-code-cleanup.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-styles-and-code-cleanup.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@StevenTCramer Thanks for this interesting idea! The best place to make product feature suggestions is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Look for the "Suggest a Feature" button:

![image](https://user-images.githubusercontent.com/24882762/50102736-a7218180-01da-11e9-9aaf-ea3a99ccd030.png)

When you suggest a feature on Developer Community, you can engage directly with the engineering team as they consider the suggestion. It also provides a way for other customers to upvote your suggestion.

**Comment by kendrahavens** [comment]
@StevenTCramer It'd be great if you could open a bug for this on our product team via [developer community](developercommunity.visualstudio.com/
) as Genevieve mentioned! That said, the editorconfig file in any open solution should override code style settings you've set locally in Tools > Options. Hopefully, this means you don't have to reset *all* of them when you reset Visual Studio. I'm interested in what behavior you are experiencing.

There are some options in Tools > Settings that we don't yet have in editorconfig. Are those the only ones you are required to reset?
