### ISSUE TITLE
Exception with required property

### ISSUE THREAD

**Issue by motz-art** [MicrosoftDocs/visualstudio-docs#3228]
[Enter feedback here]

Hi,

I would like to suggest an enhancement for case when Exception must have some properties initialized.

Documentation says that "Failure to provide the full set of constructors can make it difficult to correctly handle exceptions.". Is it fine to Suppress the warning in this case when next constructors provided: CustomException(RequiredData), CustomException(RequiredData, string), CustomException(RequiredData, string, Exception)?

So having CustomException(RequiredData, string, Exception) would still allow me to create custom exception and specify that it's caused by another exception.

If it's not fine to suppress, please explain why and what is the best practice?

Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55e7ba0-f8c0-68fb-d2db-c8b45d60c4ad
* Version Independent ID: e21c9a8e-faf0-e484-f8b0-f8e991b1e601
* Content: [CA1032: Implement standard exception constructors - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1032)
* Content Source: [docs/code-quality/ca1032-implement-standard-exception-constructors.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1032.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Who is the best person to answer this one?

**Comment by gewarren** [comment]
@morrisjoe It looks like you originally [ported the rule](https://github.com/dotnet/roslyn-analyzers/issues/382). Do you think it's fine to suppress CA1032 for the situation that @motz-art describes?

**Comment by Mikejo5000** [comment]
This seems like a question as to whether the warning should occur if the CustomException(RequiredData, string, Exception) constructor is provided, but not CustomException(RequiredData) and CustomException(RequiredData, string), so it's more of a product question than a doc issue. @mavasani Or, do you think we should document that it's OK to suppress in this scenario? I'm inclined to close this, but does it warrant an update to the rule?

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Issue moved to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22046](https://github.com/dotnet/docs/issues/22046)
