### ISSUE TITLE
CMake docs don't mention linux support

### ISSUE THREAD

**Issue by rchiodo** [MicrosoftDocs/visualstudio-docs#323]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md

Only mentions the windows configurations in its description of the CMakeSettings.json. We have two new configurations now (and many more keys possible) - Linux-Debug and Linux-Release.

**Comment by mikeblome** [comment]
moved to internal database for tracking
