### ISSUE TITLE
Suppress Code Analysis Warnings Deprecated in VS2019

### ISSUE THREAD

**Issue by liliankasem** [MicrosoftDocs/visualstudio-docs#3230]
I tried to follow the documentation for suppressing the CA warnings for auto-generated code, but in VS2019 it says this is deprecated:

Solution Explorer -&gt; Properties -&gt; Code Analysis Settings:
`NOTE: This property page has been deprecated and will be removed in a future product release.`

What is the alternative solution to this? Can the docs be updated?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b48962e-6961-ecd8-9b3f-4e60b97600c5
* Version Independent ID: 4f2b0b4b-d0a0-e4e3-445c-026c66de4c59
* Content: [How to: Suppress Code Analysis Warnings for Generated Code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code?view=vs-2019#feedback)
* Content Source: [docs/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Is there a way to suppress warnings from Roslyn analyzers only for auto-generated code?

**Comment by mavasani** [comment]
@liliankasem @gewarren The title of the issue (suppressing warnings) and "Code Analysis Settings" page seems unrelated. For the former, you should still be able to suppress/escalate/configure your analysis using a ruleset file, which can also be opened from the Code Analysis project properties page. For the latter, I suggest you read my comments posted on https://developercommunity.visualstudio.com/content/problem/317861/code-analysis-settings-doesnt-load.html for alternatives to "Code Analysis Settings" page. It cites the functional, accessibility and maintenance overhead for customers using this page as opposed to using a central ruleset file shared between projects in a solution via common props/targets file.

**Comment by mavasani** [comment]
Ah, I read the content of https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code more carefully. This setting is supported only for legacy code analysis. Currently, we have no way for end users to just disable analyzer diagnostics just in generated code files. This should be resolved with .editorconfig based configuration in future, where users can disable/configure rules as individual file/folder level.

**Comment by mavasani** [comment]
I believe we have an existing feature request for the supported requested here: https://github.com/dotnet/roslyn/issues/6999.

**Comment by AroglDarthu** [comment]
**On a related note...**
It was possible to also suppress `CS1591:Missing XML comment for publicly visible type or member` for generated code via that properties page (Solution Explorer -> Properties -> Code Analysis Settings).

How can this be established now?
I have tried the following, but that does not seem to work, as it is a compiler warning and not a code analysis warning?
`[assembly: SuppressMessage("Compiler", "CS1591", Justification="Generated Code", Scope="namespaceanddescendants", Target="MyNamespaceContainingGeneratedCode")]`

The only option I see at the moment, is to move all generated code to a separate project and just set `<noWarn>1591</noWarn>` in the project file. A viable option, but it falls short if you want to add your own logic to some of the generated `partial` classes.
