### ISSUE TITLE
No mention of support (or lack of support) for Class Designer for Python

### ISSUE THREAD

**Issue by sparkle999** [MicrosoftDocs/visualstudio-docs#3235]
As far as I can tell, there is no support for class diagrams or use of the class designer within VS for python? You may want to update this page to add a statement about whether this is supported or not. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ccada0-aa56-4952-5ba5-3c39137f41e4
* Version Independent ID: 083f73fd-0085-e8a3-d451-1e78ea172ad4
* Content: [Python support in Visual Studio on Windows](https://docs.microsoft.com/en-us/visualstudio/python/overview-of-python-tools-for-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/overview-of-python-tools-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/overview-of-python-tools-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by huguesv** [comment]
Thanks for the feedback.

We do not support class diagrams/class designer (this could be added to the docs)

We also no longer support object browser / class view in 2017 and 2019 (this should be corrected in the docs). We might bring back support at a later time https://github.com/microsoft/PTVS/issues/1213.

**Comment by JoshuaPartlow** [comment]
Opened https://github.com/MicrosoftDocs/visualstudio-docs/issues/4590 to track the creation of a VS 2019 feature support table.
