### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Matthiasclee** [MicrosoftDocs/visualstudio-docs#3236]
How do I compile it into an EXE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33ddb9d3-4439-6258-68f6-c8d7fb3b6d03
* Version Independent ID: c3b4db40-76a8-fce8-d282-2c6469c36a31
* Content: [Step 2: Run your program - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-2-run-your-program?view=vs-2019#feedback)
* Content Source: [docs/ide/step-2-run-your-program.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-2-run-your-program.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Matthiasclee Thanks for your inquiry. For information on how to do this, see our [Compile and build in Visual Studio](https://docs.microsoft.com/visualstudio/ide/compiling-and-building-in-visual-studio?view=vs-2019) page.
