### ISSUE TITLE
This rule basically prevents the use of the new $"..." syntax when "Current culture" is correct

### ISSUE THREAD

**Issue by pgrawehr** [MicrosoftDocs/visualstudio-docs#3239]
This rule prevents that I can use the $-Syntax for string concatenation when I want to use the current culture. There's no `FormattableString.CurrentCulture()` method. In addition, the rule has false positives if the argument type is not language dependent (such as a string). 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f418cad-87d9-537a-497c-991d209cb178
* Version Independent ID: 10bbdf2e-c425-4f8d-bfec-a5b821a41698
* Content: [CA1305: Specify IFormatProvider - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1305-specify-iformatprovider?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1305-specify-iformatprovider.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1305-specify-iformatprovider.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@pgrawehr The best place to provide this feedback is at https://github.com/dotnet/roslyn-analyzers/issues (this page is for documentation feedback). You'll get a better response from the product team over there. Please comment here once you've opened the issue over there and I'll close this one.

**Comment by pgrawehr** [comment]
Done: https://github.com/dotnet/roslyn-analyzers/issues/2481

**Comment by gewarren** [comment]
@pgrawehr Thanks Patrick!
