### ISSUE TITLE
CMake docs don't make mention of inheritEnvironments 

### ISSUE THREAD

**Issue by rchiodo** [MicrosoftDocs/visualstudio-docs#324]
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/ide/cmake-tools-for-visual-cpp.md
CmakeSettings.json now supports values like so:

      "inheritEnvironments": [ "msvc_x64_x64" ],

This sets up a whole bunch of variables that are automatically passed to CMake.exe when it's run. In the example above, this is the same as if the user ran the "Developer Command Prompt for VS 2017" with the -arch=amd64 -host_arch=amd64 arguments.

This is the list that I know of. There might be more.

{ "vsdev",          defaultContextData },
                { "msvc_x86",       defaultContextData },
                { "msvc_x64",       new ContextData { ScriptParams="-arch=amd64 -host_arch=x86", IntelliSenseMode="msvc-x64"} },
                { "msvc_arm",       new ContextData { ScriptParams="-arch=arm -host_arch=x86", IntelliSenseMode="msvc-arm"} },
                { "msvc_arm64",     new ContextData { ScriptParams="-arch=arm64 -host_arch=x86", IntelliSenseMode="msvc-arm64"} },
                { "msvc_x86_x64",   new ContextData { ScriptParams="-arch=x86 -host_arch=amd64", IntelliSenseMode="msvc-x86"} },
                { "msvc_x64_x64",   new ContextData { ScriptParams="-arch=amd64 -host_arch=amd64", IntelliSenseMode="msvc-x64"} },
                { "msvc_arm_x64",   new ContextData { ScriptParams="-arch=arm -host_arch=amd64", IntelliSenseMode="msvc-arm"} },
                { "msvc_arm64_x64", new ContextData { ScriptParams="-arch=arm64 -host_arch=amd64", IntelliSenseMode="msvc-arm64"} },

**Comment by mikeblome** [comment]
Moved to internal database for tracking.
