### ISSUE TITLE
Equivalent support for aligning arguments

### ISSUE THREAD

**Issue by johncrim** [MicrosoftDocs/visualstudio-docs#3240]
This is a useful refactoring, but it seems a major omission that you can only do this with parameters, not with arguments when calling the method. If the parameter/argument list is long enough to need wrapping + alignment, it's usually long enough on both sides of the call.

Argument alignment is even more useful when using inline lambda function arguments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 801fcd63-0608-4536-02b8-d69c8abdbf89
* Version Independent ID: c523fd43-842d-00a4-9c6f-8b1de9beafae
* Content: [Wrap, Indent, Align parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/wrap-align-indent-parameters?view=vs-2019)
* Content Source: [docs/ide/reference/wrap-align-indent-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/wrap-align-indent-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by kendrahavens** [comment]
You can definitely do this with long argument lists when calling a method.
![image](https://user-images.githubusercontent.com/8293542/58132973-8620ea80-7bd7-11e9-8f62-9b25c73c6d19.png)

I can update the documentation to include this. Thanks for the catch!
