### ISSUE TITLE
visualstudio remote tool  download url error

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#3241]
@HeMinzhang commented on [Fri May 10 2019](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/127)

**In this doc:**
https://docs.microsoft.com/zh-cn/visualstudio/debugger/remote-debugging?view=vs-2019

![QQ截图20190511103729](https://user-images.githubusercontent.com/2683269/57564075-cfec2280-73d8-11e9-92a1-449a8da46b8f.png)

**this link:**
https://visualstudio.microsoft.com/downloads/?q=remote+tools#remote-tools-for-visual-studio-2019

**Comment by CeciAc** [comment]
Hi team, 
the link highlighted in the screenshot returns an empty page

**Comment by HeMinzhang** [comment]
I think it's just a problem with the Chinese page. It only shows the error when the language is Chinese.

Other problems I just discovered:
![QQ截图20190514105350](https://user-images.githubusercontent.com/2683269/57667575-a7616400-7636-11e9-8682-de4a5877aed9.png)

Visual Studio 2017 download link error:
https://my.visualstudio.com/Downloads?q=remote%20tools%20visual%20studio%202017
![QQ截图20190514105846](https://user-images.githubusercontent.com/2683269/57667739-471ef200-7637-11e9-903a-6abeb7bc72cc.png)


Visual Studio 2015 download link error:
https://my.visualstudio.com/Downloads?q=remote%20tools%20visual%20studio%202015
![QQ截图20190514105915](https://user-images.githubusercontent.com/2683269/57667755-5867fe80-7637-11e9-9302-ec30a974fbc7.png)


Visual Studio 2012 download link error(The English page is normal. The Chinese page shows Visual Studio 2013?):
https://docs.microsoft.com/zh-cn/previous-versions/visualstudio/visual-studio-2012/bt727f1t(v=vs.110)#installing-the-remote-tools

![QQ截图20190514105810](https://user-images.githubusercontent.com/2683269/57667717-31a9c800-7637-11e9-954e-8c46e96bbd51.png)

**Comment by HeMinzhang** [comment]
Visual Studio 2019 download error:
![QQ截图20190514110027](https://user-images.githubusercontent.com/2683269/57667831-af6dd380-7637-11e9-876c-7e2929b49796.png)
![QQ截图20190514110118](https://user-images.githubusercontent.com/2683269/57667838-b3015a80-7637-11e9-8455-7c374e560e47.png)

**Comment by Mikejo5000** [comment]
Checked the en-us links and they are good, as was mentioned previously, so labelled this as a loc issue. @CeciAc @HeMinzhang Is the reason for the failed links known yet?

**Comment by CeciAc** [comment]
Hi @Mikejo5000 
I try the links no matter if I'm in the en-us page or the localized one and it takes me to this page (always in my PC default language):
https://visualstudio.microsoft.com/es/downloads/?q=remote+tools&rr=https%3A%2F%2Fdocs.microsoft.com%2Fzh-cn%2Fvisualstudio%2Fdebugger%2Fremote-debugging%3Fview%3Dvs-2019
![imagen](https://user-images.githubusercontent.com/26746247/57717114-dedd0a00-7650-11e9-8f85-d7c265f5b967.png)

**Comment by Mikejo5000** [comment]
Started e-mail thread on this

**Comment by Mikejo5000** [comment]
Updating VS 2019 link to use an anchor
