### ISSUE TITLE
if you can't even install VS how can you use this workflow!

### ISSUE THREAD

**Issue by largeDachshund** [MicrosoftDocs/visualstudio-docs#3245]
This workflow effectively excludes issues relating to installation.  I have a bug related to installing VS 2019 community.  

When you click on the .exe, it fires a ridiculuous warning about not having .Net 4.6 installed.  Not possible, since I have VS 2017 installed.

If you can't post bugs, how are you going to fix them?!?

![image](https://user-images.githubusercontent.com/7054672/57653156-03b87b00-7586-11e9-834f-feb281e0b4ff.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#feedback)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by mariaghiondea** [comment]
Are you able to launch the Visual Studio Installer? If yes, does the Feedback Tool launch from there? That is another place to report feedback from, especially installer feedback.

**Comment by obij** [comment]
Please I have a related problem, and i can't report it, using the report feature on visual studio, and my problem is also an installation issue. My problem: After successfully installing visual studio community 2017, i am unable to launch or run it. In addition, it does not show in my uninstall programs list. Furthermore, my investigation showed that   in my installation path, there is no devenv.exe (that is, my path is: C:\Program Files (x86)\Microsoft Visual Studio 8\Common7\IDE\ but no devenv.exe file, that i could have alternatively used to launch vs community 2017. Please i would be grateful for any assistance in resolving this issue. Thanks.

**Comment by seaniyer** [comment]
@obij 

Report feature is also available in the installer and you can report a problem from there.  For step by step instructions on how to use the installer to report, please see https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019

Sean
Visual Studio Feedback Team

**Comment by obij** [comment]
@sean
Sorry, but the installer never gets to the point , where the feedback
button appears. Additionally, i downloaded visual studio community 2019,
visual studio community 2019 preview and visual studio Enterprise 2019
preview, and tried installing all of them, and none ever got to the point
where I could access the feedback button. Hence, my applying for help
through this medium.

**Comment by seaniyer** [comment]
@'Matt<mailto:matcav@microsoft.com>,

Is there anything we can tell this customer to help with their installer issue?  Please feel free to reply directly on GitHub.

**Comment by seaniyer** [comment]
+ VS Setup Hotseat

@Chee Seong<mailto:ongchees@microsoft.com>: Can you please follow up on this and see if anyone has guesses here?  I can't imagien why this would be happening for him like this.

From: Sean Iyer <seiyer@microsoft.com>
Sent: Tuesday, August 6, 2019 12:10 PM
To: MicrosoftDocs/visualstudio-docs <reply@reply.github.com>; MicrosoftDocs/visualstudio-docs <visualstudio-docs@noreply.github.com>; Matt Cavallari <matcav@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [MicrosoftDocs/visualstudio-docs] if you can't even install VS how can you use this workflow! (#3245)

@'Matt<mailto:matcav@microsoft.com>,

Is there anything we can tell this customer to help with their installer issue?  Please feel free to reply directly on GitHub.

**Comment by ongcs100** [comment]
@obij 

Sorry to hear about the issue.

I would like to refer you to https://visualstudio.microsoft.com/vs/support/.  Under the **Support links** section, you will find the "Installation Help" link where you can chat with a support engineer on this issue. They will be able to help you out.

Chee Seong
Visual Studio Acquisition Team

**Comment by obij** [comment]
@ Sean et al,
Thanks for all the concern you showed.  However,  I have finally resolved
the issue. What I did: I set my computer to do some pending windows 7
update, so after the updates, I had the idea to try the installation
again.  And when I did it,  the installation was successful.
   once more thanks for the concern showed.

**Comment by gewarren** [comment]
Closing since it sounds like all issues here are resolved. @largeDachshund If you were not able to log your issue using Visual Studio Installer, please comment here.
