### ISSUE TITLE
Add documentation for new rule CA1507 (UseNameofInPlaceOfString)

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3247]
1. Implemented only in FxCop analyzers package, not legacy FxCop

2. Flags the use of string literal as an argument to an invocation (i.e. method call) or object creation where a nameof expression would add more readability and maintainability. It is fired under following conditions:
   1. Argument is a string literal or constant
   2. The argument corresponds to a "string" typed parameter of the method or the constructor being invoked (i.e. there is no conversion involved at callsite)
   3. The constant value of the string literal matches either of the following:
      1. Name of a parameter of the containing method (or any of the containing lambda or local function) within which the method or constructor is being invoked. See example [here](https://github.com/dotnet/roslyn-analyzers/blob/bcf2215966b9ba579111287cadf03727ea33fece/src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/UseNameOfInPlaceOfStringTests.cs#L293)
      2. Name of a property of the containing type within which the method or constructor is being invoked. See example [here](https://github.com/dotnet/roslyn-analyzers/blob/bcf2215966b9ba579111287cadf03727ea33fece/src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/UseNameOfInPlaceOfStringTests.cs#L322)

Implementation Reference:
https://github.com/dotnet/roslyn-analyzers/blob/3bb0de8da1b17cdd2f8e39af52510a6083f1abff/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/UseNameofInPlaceOfString.cs#L14

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784927d7-2cab-8a78-9c03-42867f207774
* Version Independent ID: bdf8c31c-f20e-7761-6fcd-560d63f134b8
* Content: [Maintainability Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/maintainability-warnings?view=vs-2019)
* Content Source: [docs/code-quality/maintainability-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/maintainability-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
We also have a code fix for this analyzer, which might make it easier to understand the recommendation. See unit tests for the code fix: https://github.com/dotnet/roslyn-analyzers/blob/2f94c36db114d8ab2517939c01e4390806c95cdb/src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/UseNameOfInPlaceOfStringTests.Fixer.cs#L17

**Comment by mavasani** [comment]
Also tagging @chborl who implemented this analyzer/fixer.

**Comment by gewarren** [comment]
@mavasani @chborl Could you review the new topic please? I put that it's a non-breaking change; let me know if I got that wrong. Also please check the use case I put in the rule description.

https://review.docs.microsoft.com/en-us/visualstudio/code-quality/ca1507?view=vs-2017&branch=pr-en-us-4645
