### ISSUE TITLE
Khmer language please.

### ISSUE THREAD

**Issue by Alone2Me** [MicrosoftDocs/visualstudio-docs#3249]
Khmer language please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9996cb85-f867-e5bf-3ac6-77971f45062e
* Version Independent ID: afefb77c-4530-0643-64fa-b99ceec93139
* Content: [Data access and tools - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/accessing-data-in-visual-studio?view=vs-2019)
* Content Source: [docs/data-tools/accessing-data-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/accessing-data-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@Alone2Me  Thank you for the feedback.

Does the [Khmer language pack](https://www.microsoft.com/km-kh/download/details.aspx?id=17036) address your needs?  

If there are issues, please comment below.  This issue might be better suited as a feature request per the [Visual Studio forums](https://developercommunity.visualstudio.com/spaces/8/index.html).
