### ISSUE TITLE
Consider adding the double quote character to the list

### ISSUE THREAD

**Issue by TPucke** [MicrosoftDocs/visualstudio-docs#3251]
Consider adding the double quote character to the list

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e990c1d-5b08-0b80-6851-68bd737f9c7b
* Version Independent ID: f898e9ad-99e7-5584-4b7e-a808d3f63728
* Content: [Special Characters to Escape - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/special-characters-to-escape?view=vs-2019#feedback)
* Content Source: [docs/msbuild/special-characters-to-escape.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/special-characters-to-escape.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, is there any reason the double quote character was not included in this list?

**Comment by rainersigwald** [comment]
It looks like neither double quote nor single quote (nor backtick) is escaped by MSBuild's built-in escaping function:

https://github.com/microsoft/msbuild/blob/f82477f7cbc53febd3256a0c3004c34d5b3a0cb2/src/Shared/EscapingUtilities.cs#L301

@tpucke Have you encountered a situation where it would have been helpful to escape these characters?

**Comment by TPucke** [comment]
Yes, I had to do this in an `<Exec ... />` where my command line requires use of double quotes.

**Comment by TPucke** [comment]
Just an added note, it would also be helpful to include the ASCII codes, so that we don't need to elsewhere to hunt these down.

**Comment by Mikejo5000** [comment]
Sounds like the scenario where you need to escape a double quote is a bit of a corner case. I'm thinking I will add it as a note.
