### ISSUE TITLE
"Example: Use the project name for a file name"

### ISSUE THREAD

**Issue by vwilson** [MicrosoftDocs/visualstudio-docs#3252]
This section does not include important information.  One must edit the template csproj such that the Content Include or Compile Include nodes' file names match the formatted filenames in the vstemplate file.  If one does not follow this step, the template will fail upon project creation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Project and item template parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019#feedback)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Comment to trigger priority labeling.

**Comment by O4D** [comment]
> This section does not include important information.  One must edit the template csproj such that the Content Include or Compile Include nodes' file names match the formatted filenames in the vstemplate file.  If one does not follow this step, the template will fail upon project creation.
> 
> Document Details
> ⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.
> 
> ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
> Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
> Content: Project and item template parameters - Visual Studio
> Content Source: docs/ide/template-parameters.md
> Product: visual-studio-windows
> Technology: vs-ide-general
> GitHub Login: @gewarren
> Microsoft Alias: gewarren

Can you explain more precisely what are the missing steps ?
I'm trying to use $safeprojectname$/$projectname$/$specifiedSolutionName$/$SpecifiedSolutionName$/$specifiedsolutionname$ without any succes !
