### ISSUE TITLE
Is Coded UI going to be supported in Windows 2016 ?

### ISSUE THREAD

**Issue by ManoranjanKanungo** [MicrosoftDocs/visualstudio-docs#3253]
Hi,

Is coded UI going to be supported in Windows 2016, we are having UI automated test case which running fine in Windows8 , Now we need to upgrade to 2016 , wish to know if is test will or not.

**Comment by gewarren** [comment]
@PBoraMSFT Could you answer this?

**Comment by PBoraMSFT** [comment]
Coded UI is supported on the platforms that Visual Studio supports. Please refer the system requirements documentation for details - https://docs.microsoft.com/en-us/visualstudio/releases/2019/system-requirements?view=vs-2019.

**Comment by gewarren** [comment]
@PBoraMSFT Thanks!
