### ISSUE TITLE
This should be updated to include the post rename code fix

### ISSUE THREAD

**Issue by ryzngard** [MicrosoftDocs/visualstudio-docs#3256]
When a type is renamed, it gets surrounded by a white (in dark theme) dotted box. As long as the user doesn't leave the symbol name while editing, they can use ctrl + . to invoke a code fix  to rename.

![image](https://user-images.githubusercontent.com/475144/57808017-5d9c7a80-7717-11e9-8fdf-7d4c9629ff98.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d231e9f6-7c0c-7073-6727-81a08019e589
* Version Independent ID: d0078914-0fc3-e988-ce0e-559c09f0b4c8
* Content: [Refactor rename - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/rename?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/rename.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/rename.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ryzngard Thanks, I'm adding this now.
