### ISSUE TITLE
.NET Core 2.2: Environment variable is not exposed as a property in a .csproj file

### ISSUE THREAD

**Issue by Gehbrial** [MicrosoftDocs/visualstudio-docs#3260]
To my understanding, a system-wide environment variable should be exposed as Property in a .csproj file. That is the equivalent as setting a property using `dotnet msbuild -p:SomeProperty=Value`. However, it is simply not working and I am forced to do:
```
  <PropertyGroup>
    <SomeProperty>$([System.Environment]::GetEnvironmentVariable("SomeProperty", EnvironmentVariableTarget.Machine))</Environment>
  </SomeProperty>
```

Am I missing in the documentation or is it outdated/broken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7747726-ffba-1139-b3f3-138a1992d5fc
* Version Independent ID: 19e5ed3a-4e7c-2c2f-185f-b681ba3a9a23
* Content: [How to: Use Environment Variables in a Build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-environment-variables-in-a-build?view=vs-2019#feedback)
* Content Source: [docs/msbuild/how-to-use-environment-variables-in-a-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-use-environment-variables-in-a-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Is there a workaround here for .NET Core/

**Comment by rainersigwald** [comment]
MSBuild inherits from the current environment in both .NET Core and full framework scenarios. Can you confirm that the environment variable is visible in the current environment? If it is, this sounds like an MSBuild bug that we should investigate.

`GetEnvironmentVariable("SomeProperty", EnvironmentVariableTarget.Machine)` doesn't actually look in the environment, but in a registry key (that is used when creating fresh environment blocks at a later time, but doesn't directly apply to existing environments). So if you're freshly setting an environment variable with the machine-wide mechanism and then expecting it to be exposed to the current process, that won't work.

One nit: inheriting from the environment isn't exactly the same as passing `-p:Name=Value`. 
An environment variable can be overridden by the building project, while a passed-in property overrides any value set by the project's evaluation.

**Comment by Gehbrial** [comment]
Thank you!

**Comment by Mikejo5000** [comment]
I believe this issue has been resolved with the clarification provided.
