### ISSUE TITLE
Stacking in stead of nesting two using statements

### ISSUE THREAD

**Issue by flixcor** [MicrosoftDocs/visualstudio-docs#3261]
Does this apply when stacking in stead of nesting the two using statements? Is the outer object disposed twice in the following code?

using (var stream = new FileStream("file.txt", FileMode.OpenOrCreate))
using (var writer = new StreamWriter(stream))
{
    // Use the writer object...
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836e7028-0bda-ef7c-fc11-4babb54ae70a
* Version Independent ID: 540dfe05-8e43-ed02-93d9-444c22485f84
* Content: [CA2202: Do not dispose objects multiple times - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2202-do-not-dispose-objects-multiple-times?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2202-do-not-dispose-objects-multiple-times.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2202-do-not-dispose-objects-multiple-times.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@flixcor Your example code is still a nested using statement - it just doesn't have the curly braces for the outer using statement. So yes, the outer object is still disposed twice.
