### ISSUE TITLE
Ctrl+Alt+S to open Server Explorer

### ISSUE THREAD

**Issue by gaclab** [MicrosoftDocs/visualstudio-docs#3265]
The documentation says "Press Ctrl+Alt+S to open Server Explorer" but this appears to no longer be available as a keybinding in Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d80b776-c83a-2d67-d18d-7dbecc7bc190
* Version Independent ID: b9190b2a-9826-8830-16b0-eb35574b14c9
* Content: [Work with multiple user accounts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/work-with-multiple-user-accounts?view=vs-2019)
* Content Source: [docs/ide/work-with-multiple-user-accounts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/work-with-multiple-user-accounts.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gcopley** [comment]
![serverexplorer](https://user-images.githubusercontent.com/1197835/57885471-a1af7e00-77f0-11e9-9b6e-da44fcc3cd43.png)
