### ISSUE TITLE
Getting date instead of time in the web browser https://localhost:44335/

### ISSUE THREAD

**Issue by maiormarso** [MicrosoftDocs/visualstudio-docs#3267]
Please advise: Instead of 
It's 11:31 PM right now on the server!
the browser is displaying
It's Friday,17 May, 2019 right now on the server!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96bf0705-d0c2-d0ad-3e77-60b99a462e25
* Version Independent ID: 022345f2-1126-ec6c-e268-a73ca554aa39
* Content: [Step 2: Creating Your First ASP.NET Core Web App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-02?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-02.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-02.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by ghogen** [comment]
The output there depends on CurrentCulture setting, so output may vary - there's a note I added a while ago to this topic that explains that.  I think we can close this now.
