### ISSUE TITLE
The link to this page is misleading

### ISSUE THREAD

**Issue by scottpage** [MicrosoftDocs/visualstudio-docs#3268]
The link states "Publish to a Docker Image".  I'm thinking this is exactly what I need.  Then I click the link, and it's nothing but Azure.   Not forgetting to mention that the actual title is "Deploy an ASP.NET container to a container registry using Visual Studio".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485faedb-302a-5b6c-8a5b-d9dc4bedfbd2
* Version Independent ID: d236f0a6-2bcb-2cdd-de7d-522dfc4b6dde
* Content: [Deploy an ASP.NET Docker container to Azure Container Registry (ACR) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/hosting-web-apps-in-docker?view=vs-2019)
* Content Source: [docs/containers/hosting-web-apps-in-docker.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/hosting-web-apps-in-docker.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by scottpage** [comment]
If "Deploy an ASP.NET container to a container registry using Visual Studio" is what I wanted, I wouldn't have clicked on "Publish to a Docker Image".

**Comment by ghogen** [comment]
That link appears to be in the ASP.NET docs - so I created a PR to address that here: https://github.com/aspnet/AspNetCore.Docs/pull/13325
