### ISSUE TITLE
"Add > New Item > C++ Unit Test" in "To write unit tests in the same project" is not possible

### ISSUE THREAD

**Issue by ErazorBlade** [MicrosoftDocs/visualstudio-docs#3269]
In the section "To write unit tests in the same project", it says to choose Add &gt; New Item &gt; C++ Unit Test. This is not possible in Visual Studio 2019 and there is no component available to download the functionality.

Unit testing an executable is very annoying anyway because having to link every obj file for every new cpp file is too much work and there is almost no information available on it (or I'm just not able to find it)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83cfa6a-8be4-e7b5-bf06-9f70023aaa65
* Version Independent ID: 92877cae-f39e-6653-ce1e-233f75988ba0
* Content: [Use the Microsoft Unit Testing Framework for C++ - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp?view=vs-2019#feedback)
* Content Source: [docs/test/how-to-use-microsoft-test-framework-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-microsoft-test-framework-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by ErazorBlade** [comment]
I am using VS Community 2019

**Comment by mikeblome** [comment]
@ErazorBlade apologies! The doc fix will be published in a day or so. In the meantime, here are the correct steps (pls ignore the markdown formatting):
1. Modify the project properties to include the headers and library files that are required for unit testing.

   1. In **Solution Explorer**, right-click on project node for the program you are testing, then choose **Properties** > **Configuration Properties** > **VC++ Directories**.

   2. Click on the down arrow in the following rows and choose **\<Edit>**. Add these paths:

      | Directory | Property |
      |-| - |
      | Include Directories | $(VCInstallDir)Auxiliary\VS\UnitTest\include |
      | Library Directories| $(VCInstallDir)Auxiliary\VS\UnitTest\lib |
2. Add a C++ Unit Test file:
   - Right-click on the project node in **Solution Explorer** and choose **Add** > **New Item** > **C++ Source File**.

**Comment by mikeblome** [comment]
fixed
