### ISSUE TITLE
Problems in Walkthrough: Creating an SDK using C# or Visual Basic 

### ISSUE THREAD

**Issue by phraemer** [MicrosoftDocs/visualstudio-docs#327]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-creating-an-sdk-using-csharp-or-visual-basic.md

I'm pretty sure the `source.extension.vsixmanifest` is out of date.
At step "27. On the menu bar, choose Build, Build SimpleMathVSIX." I'm getting the error **error VSSDK1078: The VSIX manifest must contain element 'Prerequisites'**

Also in the sample app walk through it refers to "Simple Math SDK" which is not previously mentioned.
There seems to be a few mix up in names, IDs, namespaces etc.

**Comment by gewarren** [comment]
@phraemer Thank you for this feedback. Hopefully we can look into this soon (and sorry for the long delay!)

**Comment by msebolt** [comment]
@phraemer Thank you for the noting this, the tutorial has been updated.

Please comment below if there are any issues.
