### ISSUE TITLE
Show output from: Build - Run Error CS1061 and CS0246

### ISSUE THREAD

**Issue by maiormarso** [MicrosoftDocs/visualstudio-docs#3271]
Please advise, Attempted this Games ASP.net application five times, just in case, but the errors persist.
1&gt;-- Build started: Project: WebApplication1, Configuration: Debug Any CPU --
1&gt;Program.cs(19,46,19,57): error CS1061: 'IServiceProvider' does not contain a definition for 'CreateScope' and no accessible extension method 'CreateScope' accepting a first argument of type 'IServiceProvider' could be found (are you missing a using directive or an assembly reference?)
1&gt;Program.cs(25,63,25,75): error CS0246: The type or namespace name 'AppDbContext' could not be found (are you missing a using directive or an assembly reference?)
1&gt;Done building project "WebApplication1.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
One or more compilation references are missing. Ensure that your project is referencing 'Microsoft.NET.Sdk.Web' and the 'PreserveCompilationContext' property is not set to false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f156aaa-839a-b9bb-5912-b3a537dfdb36
* Version Independent ID: 51888076-400e-0a51-8ae4-6fe745829436
* Content: [Step 3: Working with Data in Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-03?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by AjuKurienJohn** [comment]
I had to add the following 2 use statements to Program.cs
using WebApp1.Models;   (where WebApp1 is your project name)_
using Microsoft.Extensions.DependencyInjection;

I also had to change schoolContext to AppDBContext in the following line but based on your error you may have already done that 
var context = services.GetRequiredService<SchoolContext>();
to
var context = services.GetRequiredService<AppDBContext>();

**Comment by DickBaker** [comment]
+1 the text still says SchoolContext when itshould be AppDbContext
is nobody monitoring these important pages ?

**Comment by ghogen** [comment]
Thanks - we have now updated this topic to address these issues.
