### ISSUE TITLE
Unable to find the tool listed in my subscriptions

### ISSUE THREAD

**Issue by arjunUnniumbath** [MicrosoftDocs/visualstudio-docs#3272]
Hi team, 
Is this subscription still available forocroaoft accounts ? I'm unable to view this in my benefits .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4463ef6f-8bad-66e9-e9c2-f52c867625c0
* Version Independent ID: 99230beb-7158-cfc7-7607-8fc3270fae29
* Content: [Parasoft Virtualize/SOAtest Professional Desktop Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-parasoft#feedback)
* Content Source: [subscriptions/vs-parasoft.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-parasoft.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@arjunUnniumbath - Thanks for reaching out.  Whether the Parasoft benefit is available to you depends on the type of subscription you have.  It's currently only available to Visual Studio Enterprise standard and annual cloud subscriptions.  You can log in to https://my.visualstudio.com/subscriptions to see what subscriptions are available to you.  If you have an Enterprise subscription that's not marked "NFR", you should have the benefit.  (If you have multiple subscriptions, be sure to select the Enterprise subscription and then click on the Benefits tab to see your benefits.)

It's in the "Tools" group, and you will need to scroll to the right a couple of times to see it.  It's the 15th tile listed in the Tools category.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for your answer to the customer's inquiry. We'll close this issue now.
