### ISSUE TITLE
Flask/ views.py

### ISSUE THREAD

**Issue by jawineh** [MicrosoftDocs/visualstudio-docs#3273]
Much as the page is helpful there is however the unresolved issue of non-creation of 'views.py' file within Helloflask folder in the solution. could this be peculiar to VS 2018?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7542d51c-4ba4-db5d-cd34-4517779684a8
* Version Independent ID: ef7b3a39-814e-9c56-c2e1-6611464aa650
* Content: [Learn Flask tutorial in Visual Studio step 1, Flask basics](https://docs.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-01-project-solution?view=vs-2019)
* Content Source: [docs/python/learn-flask-visual-studio-step-01-project-solution.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-flask-visual-studio-step-01-project-solution.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hello - [Step 2: Create a Flask app with views and page templates](https://docs.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-02-create-app?view=vs-2019) should walk through the creation of views.py. If this was referring to something else, please feel free to reopen.
