### ISSUE TITLE
install offline

### ISSUE THREAD

**Issue by harithchen** [MicrosoftDocs/visualstudio-docs#3277]
I Use the Command [vs_enterprise.exe --layout .\vs2017-offline.NativeDesktop.eng --add Microsoft.VisualStudio.Workload.NativeDesktop --includeOptional --lang En-us] to download Eng Version.Then I disable all network adapter, and I Can Install VS2017 From the offline package.
But When I Use the Command [vs_enterprise.exe --layout .\vs2017-offline.NativeDesktop.chs --add Microsoft.VisualStudio.Workload.NativeDesktop --includeOptional --lang Zh-cn] To download chs Version,with the Same Operation,I Can not Install VS2017.The Setup always need to download microsoft.visualstudio.webtoolsextensions.common.resources.vsix.The net address returned by Setup is https://download.visualstudio.microsoft.com/download/pr/c785f3fe-634d-41b8-82fe-5f4facb95f85/c777af65b5c0c4f7d3c5dbd50a8557a5/microsoft.visualstudio.webtoolsextensions.common.resources.vsix。
How Can I Solve this Proplem?

**Comment by TerryGLee** [comment]
@harithchen Thanks for letting us know. 
@tydunkel FYI.

**Comment by tydunkel** [comment]
@harithchen I believe the offline layout will contain the zh-cn packages, but installing from the layout may not be telling the installer to install the zh-cn packages. Without any options, the installer will default to using the system locale as the language to install. Can you verify if the vs2017\response.json contains a line with `--addProductLang: ["zh-CN"]`?

**Comment by TerryGLee** [comment]
@harithchen We haven't heard back from you, so we're closing this issue.
