### ISSUE TITLE
The installation path is wrong for VS2019

### ISSUE THREAD

**Issue by salowenh** [MicrosoftDocs/visualstudio-docs#3278]
I was able to find the Python under C:\Program Files (x86)\Microsoft Visual Studio\Shared

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3dfab77-abe5-b079-1561-8ebd926f5cf8
* Version Independent ID: 2b799f56-7a98-83cb-5e18-c2be93cafd49
* Content: [Install Python support - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/installing-python-support-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/installing-python-support-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/installing-python-support-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by danien** [comment]
For some reason, the Visual Studio 2019 Installer puts the actual Python folder and executable files into C:\ (e.g., C:\Python27, C:\Python27amd64) for me.

**Comment by rlussier** [comment]
Is there a written step by step of this. I've tried fixing it and my app still won't work.

**Comment by JoshuaPartlow** [comment]
@huguesv - Any ideas here what the default should be? Thanks!

**Comment by judej** [comment]
@salowenh, the default path of the Python 2.7 kernel is ```c:\```. For the current version 3.7+, the kernel will be in ```Program Files (x86)\Microsoft Visual Studio\Shared```

Hope this addresses the confusion
thanks
