### ISSUE TITLE
Support plan not displayed, close and reopen browser 

### ISSUE THREAD

**Issue by AndrewCussons** [MicrosoftDocs/visualstudio-docs#3279]
When you submit an incident online and add a contract using the Access ID and Contract ID you may have a problem. Occasionally, you do not see the support plan displayed or get an error. You may be able to click support request, new and cycle through your previous selection and it refreshes the support plan. If this does not work, copy your issue details, close the browser and sign-in again, then the support plan is displayed.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79453c-3962-2f0c-5b99-4fbde91972f8
* Version Independent ID: c845c29e-dfd7-316e-81b2-ebe288a384c1
* Content: [Technical Support Benefit](https://docs.microsoft.com/en-gb/visualstudio/subscriptions/vs-tech-support#feedback)
* Content Source: [subscriptions/vs-tech-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-tech-support.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@AndrewCussons - Thanks for bringing this to our attention.  I've verified that it's a known issue and our support engineering team is working on it.  I've also asked them to provide specific instructions we can include in the vs-tech-support.md article to help customers who encounter the issue.  Thanks again for the report.

**Comment by evanwindom** [comment]
The article has been updated to provide steps to display the support plan.  We will update it again once the underlying technical issue is resolved.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for updating this page with the latest status about how to display the support plan. We'll close this issue now. @AndrewCussons Thanks for helping us to improve our documentation!
