### ISSUE TITLE
Missing information in VSIX Extension Schema 2.0 Reference

### ISSUE THREAD

**Issue by phraemer** [MicrosoftDocs/visualstudio-docs#328]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/vsix-extension-schema-2-0-reference.md

The attributes for `<InstallationTarget>` are only documented for when the `Scope` attribute has the explicit or default value "ProductExtension".

The attributes for when it has the value "Global" are not not documented.

However, the [walk-through for creating an SDK](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-creating-an-sdk-using-csharp-or-visual-basic.md) requires the use of several undocumented attributes. Namely,  `Id="Microsoft.ExtensionSDK" TargetPlatformIdentifier="Windows" TargetPlatformVersion="v8.0" SdkName="WinRT Math (CS)" SdkVersion="1.0"`

**Comment by gregvanl** [comment]
@fenxu I don't think the referenced commit has anything to do with this issue. Was this issue closed by mistake?

**Comment by fenxu** [comment]
@gregvanl Sorry, it was closed by mistake.
