### ISSUE TITLE
When are unused open statements removed?

### ISSUE THREAD

**Issue by bender2k14** [MicrosoftDocs/visualstudio-docs#3282]
&gt; - Remove unused open statements
&gt;   If this check box is selected, open statements in the current file that aren't used are removed.

When?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31ba4504-a2c7-abcc-17e0-aed923f4b3fd
* Version Independent ID: 48fa3d22-6d8f-f39d-8753-51067c2b77b0
* Content: [Options, Text Editor, F#, Code Fixes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-fsharp-code-fixes?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/options-text-editor-fsharp-code-fixes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-fsharp-code-fixes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@cartermp Could you help answer this? Would these code fixes appear in the light bulb icon menu on the line of code with the issue?

**Comment by cartermp** [comment]
@gewarren Correct, this will do two things:

* Analyze a document for unused `open` declarations
* Offer a lightbulb that removes all unused `open` declarations
