### ISSUE TITLE
Remote tools not backward compatible

### ISSUE THREAD

**Issue by gururajks** [MicrosoftDocs/visualstudio-docs#3284]
> Download the most recent remote tools for your version of Visual Studio. The latest remote tools version is compatible with earlier Visual Studio versions, but earlier remote tools versions aren't compatible with later Visual Studio versions.

This is incorrrect. I am getting an error message that says the remote debugger is newer than your version of Visual Studio 2017. I was using the remote tools of 2019 as it said that the remote tools are backward compatible and instructed to download the latest version. 
![image](https://user-images.githubusercontent.com/4934049/58121504-9b951500-7bd5-11e9-8045-b9000a7177e7.png)

**Comment by Mikejo5000** [comment]
@gururajks Thanks for the feedback! I'll ask about it. For now, I'd recommend you try the latest version of the VS 2017 remote tools.

**Comment by Mikejo5000** [comment]
Clarifying text
