### ISSUE TITLE
Remote tools are not backward compatible

### ISSUE THREAD

**Issue by gururajks** [MicrosoftDocs/visualstudio-docs#3285]
created an issue here
https://github.com/MicrosoftDocs/visualstudio-docs/issues/3284
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019#feedback)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Closing in favor of #3284
