### ISSUE TITLE
Update component list for Visual Studio 2019 16.1

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#3287]
Visual Studio 2019 16.1 contains at least one new component, IntelliCode. Please update this page for all new components in version 16.1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?vs-2019&view=vs-2019)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@cremor Thanks for your feedback; the page update is in the publishing queue and will be live before noon PST on 5/22/19.
