### ISSUE TITLE
Wrong configuration

### ISSUE THREAD

**Issue by Chavoshi** [MicrosoftDocs/visualstudio-docs#3290]
"storage-opts": [
    "size=120GB"
  ]

This configuration causes Docker to crash, "size=120G" is the correct one

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
Mine is currently set to the following, which is working fine in docker engine 18.09.2:

```json
  "storage-opts": [
    "size=127GB"
  ]
```

On what version are you?

**Comment by heaths** [comment]
I tried just "G" and it works, and I see is what is documented in [their docs](https://docs.docker.com/engine/reference/commandline/dockerd/) so I'll just update these anyway.
