### ISSUE TITLE
Update Prerequisites

### ISSUE THREAD

**Issue by f1ben** [MicrosoftDocs/visualstudio-docs#3291]
In Visual Studio Community 2019's installer, "Data storage and processing" is not in the "Web & Cloud" group.  It's in "Other Toolsets".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d19e1d-1448-e5b3-6580-9b11042e03ab
* Version Independent ID: 549472fa-f3be-53bc-cf9f-170c1183c834
* Content: [Create a database file and use table designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2019#prerequisites)
* Content Source: [docs/data-tools/create-a-sql-database-by-using-a-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-sql-database-by-using-a-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@f1ben Thanks for letting us know! We'll get it updated.
