### ISSUE TITLE
Add column showing exact escape sequence for each row

### ISSUE THREAD

**Issue by BruceForstall** [MicrosoftDocs/visualstudio-docs#3293]
This would include the % and hex ASCII value needed to escape each character.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e990c1d-5b08-0b80-6851-68bd737f9c7b
* Version Independent ID: f898e9ad-99e7-5584-4b7e-a808d3f63728
* Content: [Special Characters to Escape - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/special-characters-to-escape?view=vs-2019#feedback)
* Content Source: [docs/msbuild/special-characters-to-escape.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/special-characters-to-escape.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@BruceForstall Thanks, Bruce. I believe this is by design, as the main intent is to tell which characters need escaping, vs. providing the list of % and ASCII values. If you would like to open a PR with these improvements, though, I will make sure it gets reviewed. Thanks!
