### ISSUE TITLE
Update for 16.1

### ISSUE THREAD

**Issue by tavrez** [MicrosoftDocs/visualstudio-docs#3294]
This page need update for 16.1, some new components added(i.e. 18362 SDK) and some required components are now optional and new ones are required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f80d9f-168b-e3cb-6499-e03a44206826
* Version Independent ID: 4b235b0d-1436-0a36-ef55-f76ba8d95bd1
* Content: [Visual Studio workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019)
* Content Source: [docs/install/workload-and-component-ids.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-and-component-ids.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@tavrez The updated pages were published earlier today, per the update date of 5/21/19. Is there something missing that you think should be there that isn't? If so, please let us know. 

(@minsa110 FYI)

**Comment by tavrez** [comment]
Thanks, I saw it. I think there are some problems with catalog itself not with the docs(18362 should be in c++ desktop development sections too).
So now, only the title update remains:
![image](https://user-images.githubusercontent.com/9096461/58214541-58d55900-7d0b-11e9-9748-c5928c86616b.png)

**Comment by TerryGLee** [comment]
@tavrez I'll get that RC mention fixed; thanks so much for pointing that out!
