### ISSUE TITLE
Method not found: 'Microsoft.CodeAnalysis.Emit.EmitResult' when running TextTemplating build targets on build server

### ISSUE THREAD

**Issue by RaphaelFourdrilis** [MicrosoftDocs/visualstudio-docs#3299]
Hello,

I've been trying to solve a strange behavior for a week now, but to no avail.
We use T4 to generate some C# code in our solution, and everything works great locally (on a machine where VS 2017 Pro is installed).
But then, when we try to run the build on TeamCity, we encounter a MissingMethodException from Microsoft.CodeAnalysis as soon as TextTemplating.targets tries to transform ou t4 templates.
I've tried pretty much anything that can be found by a Google search at this point ...
- I've installed the relevant packages in vs_buildtools.exe installer (namely      "Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools" and      "microsoft.visualstudio.component.texttemplating").
- I've trying manually copying the files from my desktop to the TC agent (as per [this doc page](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process?view=vs-2017)
- I've tried summoning some pagan divinities to help

All of this to absolutely no avail. I get the following error every time:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\VisualStudio\v15.0\TextTemplating\Microsoft.TextTemplating.targets(340, 5): An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
System.MissingMethodException: Method not found: 'Microsoft.CodeAnalysis.Emit.EmitResult Microsoft.CodeAnalysis.Compilation.Emit(System.IO.Stream, System.IO.Stream, System.IO.Stream, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.ResourceDescription>, Microsoft.CodeAnalysis.Emit.EmitOptions, Microsoft.CodeAnalysis.IMethodSymbol, System.IO.Stream, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.EmbeddedText>, System.IO.Stream, System.Threading.CancellationToken)'.
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.Compile()
```

Here is the extract from the installer:

```
"Microsoft.VisualStudio.Workload.WebBuildTools",
"Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools",
"Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools",
"Microsoft.VisualStudio.Workload.OfficeBuildTools",
"Microsoft.VisualStudio.Workload.DataBuildTools",
"microsoft.visualstudio.component.testtools.buildtools",
"microsoft.net.componentgroup.targetingpacks.common",
"microsoft.net.core.component.sdk.2.1",
"microsoft.visualstudio.component.dockertools.buildtools",
"microsoft.visualstudio.component.aspnet45",
"microsoft.visualstudio.component.webdeploy",
"microsoft.net.component.4.7.1.sdk",
"microsoft.net.component.4.7.1.targetingpack",
"microsoft.net.core.component.sdk",
"microsoft.visualstudio.component.teamoffice.buildtools",
"microsoft.visualstudio.component.sql.ssdtbuildsku",
"microsoft.visualstudio.component.roslyn.languageservices",
"microsoft.visualstudio.component.texttemplating"
```

Here is the relevant part of my `.csproj`:

```xml
<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>

<!-- Optionally make the import portable across VS versions -->
<PropertyGroup>
    <!-- Get the Visual Studio version: -->
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' != ''">15.0</VisualStudioVersion>
    <!-- Keep the next element all on one line: -->
    <VSToolsPath Condition="'$(VisualStudioVersion)' == '15.0'">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
</PropertyGroup>

<!-- This is the important line: -->
<Import Project="$(VSToolsPath)\TextTemplating\Microsoft.TextTemplating.targets"/>

[...]

<PropertyGroup>
    <TransformOnBuild>true</TransformOnBuild>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <BeforeTransform>ResolveReferences</BeforeTransform>
</PropertyGroup>
```

Does anyone have an idea what goes wrong here ? It looks like Microsoft.CodeAnalysis is missing some dll, but I can't figure out which one, since I have the same files on my desktop.

**Comment by russbearl** [comment]
We're seeing the same issue.  Our build works fine locally but fails with this same error when running on a Jenkins agent.

**Comment by gewarren** [comment]
Did this just recently start happening? @mavasani any idea on this one?

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-compiler for assistance.

**Comment by mavasani** [comment]
Tagging @jcouv for compiler assistance

**Comment by jcouv** [comment]
Assuming this is on Windows and you have access to an environment that reproes the problem, I'd be tempted to look at the fusion log. `MissingMethodException` feels like some assembly is not getting loaded. 
Tagging @davidwrighton for advice.

You may also want to look through the roslyn issues that mention `MissingMethodException` ([here](https://github.com/dotnet/roslyn/issues?q=is%3Aissue+MissingMethodException+is%3Aclosed)) to see if any provides a clue.

**Comment by davidwrighton** [comment]
Text templates use a non-standard mechanism for resolving assembly references for Roslyn. You'll need to file an issue with the engineers behind the text templating infrastructure.

**Comment by russbearl** [comment]
Thank you all for the responses.  It turns out that we resolved an internal build issue that resolved this problem. So sorry for the confusion.

**Comment by RaphaelFourdrilis** [comment]
@davidbargeron How would I go about doing that ? My initial problem is *far* from resolved :/

**Comment by branh** [comment]
@RaphaelFourdrilis , you can file an issue against T4 through the Visual Studio feedback tool or at https://developercommunity.visualstudio.com/ .

As for how Roslyn assembly resolution currently works, T4 expects the Roslyn assemblies to be located in a directory called Roslyn next to the MSBuild.exe, or whatever executable is doing the build. So, if MsBuild.exe is located at C:\pathToMsBuild\MSBuild.exe (for example), the Roslyn dlls would need to be at C:\pathToMSBuild\Roslyn .

**Comment by RaphaelFourdrilis** [comment]
@branh Thanks for the link!

I'll try having this folder precisely next to MSBuild.exe, maybe that'll fix everything. I'd still like to point out that the documentation page I linked in the issue may be wrong / out of date then... Nothing there helped
