### ISSUE TITLE
[VS Options] Need docs for Preview Features, Product Updates, Tab & windows, Trust settings

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/visualstudio-docs#3301]
This page is missing the following:

- [x] Preview Features
- [x] Product Updates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 628d0bf4-32e2-c37e-a39a-a05492a54305
* Version Independent ID: f90dc3d7-e9c5-dbb1-e856-5d902294c5b5
* Content: [Environment Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/environment-options-dialog-box?view=vs-2019)
* Content Source: [docs/ide/reference/environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Rick-Anderson** [comment]
The **Use previews of .NET Core SDK** setting is under **Environment**  on the **Options** Dialog.

**Tools > Options > Environment **

![image](https://user-images.githubusercontent.com/3605364/58282419-63124a00-7d41-11e9-91bf-1fe280eff79b.png)

**Comment by gewarren** [comment]
Trust Settings is documented here: https://docs.microsoft.com/en-us/visualstudio/ide/reference/trust-settings?view=vs-2019

**Comment by gewarren** [comment]
Product Updates is documented here, and F1 goes to this page too: https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2019#customize-update-settings

**Comment by Rick-Anderson** [comment]
I was looking for a link to tell folks how to select `Use previews of .NET Core SDK` so I didn't have to explain that.

**Comment by gewarren** [comment]
> I was looking for a link to tell folks how to select `Use previews of .NET Core SDK` so I didn't have to explain that.

I'm adding a Preview Features page now, and you can update your fwlink to point there. This issue will close automatically once it's live.
