### ISSUE TITLE
cppyy

### ISSUE THREAD

**Issue by wlav** [MicrosoftDocs/visualstudio-docs#3302]
I'm the author of cppyy and ran across this page (https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019). Since some time, cppyy has wheels for MS Windows on pypi.org and installing it, both on 32 and 64 bits Windows, should be a breeze. I use VS2017 myself (community edition; compiler version 19.15.26730), and have no current issues. Perhaps the page can be updated?

Taking your example code, usage of cppyy can be as simple as:
```
import cppyy

cppyy.cppdef("""
#include <Windows.h>
#include <cmath>

const double e = 2.7182818284590452353602874713527;

double fast_sinh(double x) {
    return (1 - pow(e, (-2 * x))) / (2 * pow(e, -x));
}

double fast_cosh(double x) {
    return (1 + pow(e, (-2 * x))) / (2 * pow(e, -x));
}

double fast_tanh(double x) {
    return fast_sinh(x) / fast_cosh(x);
}
""")

from cppyy.gbl import fast_tanh
# etc. ...
```

Aside, not super-relevant, but cppyy goes back a lot longer than 2017 (its roots reach 2002, its current name is from 2010), but it's true that Windows support wasn't there back then.

**Comment by anparoct** [comment]
Hi @wlav, were you able to do a mixed-debugging session also? 

Thanks for your work by the way

**Comment by wlav** [comment]
I haven't done that before under Visual Studio (which either way is quite slow to work with under VMware on my poor laptop, so I've so far only used the CLI tools :) ).

In general, however, it all depends on the code being debugged: since wrappers are generated by the JIT, if the function is inline, it will be part of the JITted code and typically not directly visible to a debugger that can not handle JITed code. But even if not, the call itself is JITted, so typically it is not possible to set a breakpoint there w/o further steps. For example, under Intel's Amplifier, one needs to provide the JIT entry point, under gdb you have to find the exact address of the JITted function and break on that.

There didn't seem to be anything relevant in the Visual Studio docs pertaining to JITs.

I managed to get a mixed-debugging session going, but did not get beyond "[external code]" when going from Python to C++. When I force a segfault in JITted code, I get "Frame not in module" and the callstack does not point outside the JIT (i.e. not back into Python). So, it looks to me, that VS also needs a separate recipe for debugging JITed code (like Amplifier and gdb do).

It behaves more as expected when linking in library code: breaking on the first line of a function of interest works normally.

(The wheels on PyPI do not have debugging sumbols, but should not need them as that code is used for JITing itself, not for the actual call. However, the intermediate layer CPyCppyy needs to be rebuild with debugging symbols. As-is, it's not.)

Aside, while on the topic of debugging: one use case of cppyy is its use to write C++ unit tests (as unit tests are some much nicer in Python), and as a way to debug C++ as you get an instant interactive environment (yes, you can make all the inspection and calls in a good debugger as well, but now you can e.g. load matplotlib to plot data). I need to do a tutorial/write-up on such use.

**Comment by JoshuaPartlow** [comment]
@zooba - Any thoughts here?

**Comment by JoshuaPartlow** [comment]
The columns referenced are being removed from the table, so closing this issue.
