### ISSUE TITLE
What are the "vstest.console.exe" command line versions of "rerunFailedTests: true" and "rerunMaxAttempts: 3"

### ISSUE THREAD

**Issue by BrianMouncer** [MicrosoftDocs/visualstudio-docs#3303]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/visual-studio-test-agent-deployment?view=azure-devops

I would like to use the VSTEST test options "rerunFailedTests: true" and "rerunMaxAttempts: 3".
however we have some cases where our YAML build runs a bash script to copy tests and select what tests to run, then call "vstest.console.exe" to run the tests.

What are the "vstest.console.exe" command line versions of "rerunFailedTests: true" and "rerunMaxAttempts: 3"

Same question for "dotnet.exe test" command line options, as we use that in some cases as well?

Thanks,

Brian.

**Comment by PBoraMSFT** [comment]
@BrianMouncer - these options are currently only supported through the VSTest task, not throught the CLI. If you need this on the CLI, request you to open a feature request on the test platform repo. 
https://github.com/microsoft/vstest

@TerryGLee - this issue on the pipeline docs can be closed.

**Comment by TerryGLee** [comment]
Closing per request.
