### ISSUE TITLE
Missing syntax element

### ISSUE THREAD

**Issue by BruceForstall** [MicrosoftDocs/visualstudio-docs#3304]
The "syntax" section doesn't show `ItemName`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fcd9d10-b620-994d-a92e-3fe2ac7b9cae
* Version Independent ID: 5b884eee-e0fd-5741-6ab8-b0c1b0222753
* Content: [Output Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/output-element-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/output-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/output-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@BruceForstall Looks like you typically have either ItemName or PropertyName, but not both.

**Comment by BruceForstall** [comment]
Yes. Shouldn't the "Syntax" section show that?

**Comment by Mikejo5000** [comment]
I think it's OK as-is as it is shown in the example. @rainersigwald for possible comment.

**Comment by rainersigwald** [comment]
I tend to agree with @mikejo5000.
