### ISSUE TITLE
Non-english component name

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#3305]
The component with the id "Microsoft.VisualStudio.Component.VC.Llvm.Clang" has the name "Windows için clang derleyicisi". This should be in english.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?vs-2019&view=vs-2019)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@cremor Thanks for letting us know!
@minsa110 I've verified that this is appearing on the "en-us" version of the page. Let's see what we can do to get this fixed, please?

**Comment by TerryGLee** [comment]
@cremor We'll have a revised page published tomorrow by noon; "Windows için clang derleyicisi" will then read as "Clang Compiler for Windows" instead, as it should. 

Thanks for helping us improve the docs!
