### ISSUE TITLE
How to set the timeout for unmanaged c++ unit tests? I haven't found any way to do this so far....

### ISSUE THREAD

**Issue by Laro88** [MicrosoftDocs/visualstudio-docs#3307]
using namespace Microsoft::VisualStudio::CppUnitTestFramework;

TEST_METHOD(Connect_disconnect)
		{ and here goes the code that freezes when remote test server is down....

I need a way to fail after a couple of seconds - right now it jo freezes everything.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66fe9e04-c830-3350-3ff9-9a3ecb7cfe5e
* Version Independent ID: e1063d2e-aace-86b2-a4b4-6378c45c55a0
* Content: [Unit Test Basics - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019)
* Content Source: [docs/test/unit-test-basics.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/unit-test-basics.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mikeblome Do you know?

**Comment by mikeblome** [comment]
@Laro88 Apologies this is something we need to document:

Right Click solution -> Add New Item -> Test Settings
Choose “Test Timeouts” from the left-hand menu, and specify down to the “seconds” granularity.

Note that you are right-clicking the Solution node, not the project node.

**Comment by Laro88** [comment]
@mikeblome, hmm, that is a little cumbersome, and it seems to be for all tests.

What I wish for is something like in Node.JS where I can specify the max test duration for the individual tests in code -  then I programmatically can address the fact that some test are running for extended periods of time.

**Comment by mikeblome** [comment]
@laro88 according to dev team, setting max duration for individual tests is not supported for native C++.  If you like, you can go to [Visual Studio developer community](https://developercommunity.visualstudio.com/spaces/62/index.html) and file a feature request. Sorry we don't have a better answer here.
