### ISSUE TITLE
TEST_METHOD_ATTRIBUTE timeout?

### ISSUE THREAD

**Issue by Laro88** [MicrosoftDocs/visualstudio-docs#3308]
Is there a way to set a timeout for a specific TEST_METHOD?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83cfa6a-8be4-e7b5-bf06-9f70023aaa65
* Version Independent ID: 92877cae-f39e-6653-ce1e-233f75988ba0
* Content: [Use the Microsoft Unit Testing Framework for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp?view=vs-2019#feedback)
* Content Source: [docs/test/how-to-use-microsoft-test-framework-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-microsoft-test-framework-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@Laro88 see my reply on your other issue. Unfortunately this is not supported for native C++.
