### ISSUE TITLE
What's the workload ID for CodeAnalysis?

### ISSUE THREAD

**Issue by MikeChristensen** [MicrosoftDocs/visualstudio-docs#3310]
In VS2017, the workload ID was Microsoft.VisualStudio.Component.Static.Analysis.Tools, which doesn't seem to work anymore in VS2019.  The docs seem to hint that it's now Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools, but I still don't have \MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis folder on my machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Can you help to answer this? I'm guessing it has something to do with the deprecation of static code analysis?

**Comment by mavasani** [comment]
@gewarren I am not very sure. We (Managed code analysis team) did not make any setup authoring changes in VS2019. Tagging @jinujoseph in case she knows of any changes in this area done by any partner team.

**Comment by MikeChristensen** [comment]
It kinda _appears_ that the folder still gets installed with Visual Studio 2019 Pro, but does _not_ get installed using the vs_buildtools.exe (which we use on our build servers).  This looks like a change, since the VS2017 version of vs_buildtools.exe did install.

We're totally cool moving to some other code analysis technology though.  We'd just appreciate some pointers on how to install it (preferably using vs_buildtools.exe) on our build agents and how to run it from the command line and what not.  Thanks!!

**Comment by mavasani** [comment]
> We're totally cool moving to some other code analysis technology though. We'd just appreciate some pointers on how to install it

@MikeChristensen - https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2019. You just install the FxCop analyzers NuGet package and the analysis runs as part of your regular builds. No separate tooling required other then the core compiler toolset.

**Comment by gewarren** [comment]
Since the underlying problem has been addressed, I'm closing this issue.
