### ISSUE TITLE
Shortcuts for GUI elements

### ISSUE THREAD

**Issue by grendeld** [MicrosoftDocs/visualstudio-docs#3312]
This list is great and there's lots of options. Is there a keyboard shortcut or menu option somewhere that allow a VS user to explore the actual VS GUI elements names? This would be highly desirable to those whom want a complete custom experience in VS.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23332067-130b-a343-b902-7d09680d3519
* Version Independent ID: 09bb5d36-f067-5422-2ab2-e4c7a8f1d6ed
* Content: [Default keyboard shortcuts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2019#visual-studio)
* Content Source: [docs/ide/default-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/default-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@grendeld Can you describe a little more precisely what you're looking for or how you would use that info to create a custom experience?

**Comment by gewarren** [comment]
@grendeld For information about extending Visual Studio, see [Visual Studio SDK](https://docs.microsoft.com/en-us/visualstudio/extensibility/visual-studio-sdk?view=vs-2019). Specifically for the question you asked, you might find the IDs on these pages useful:

https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/guids-and-ids-of-visual-studio-menus?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/guids-and-ids-of-visual-studio-toolbars?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/guids-and-ids-of-visual-studio-commands?view=vs-2019
