### ISSUE TITLE
Installing VS2019 from a local cache doesn't work

### ISSUE THREAD

**Issue by zkyll** [MicrosoftDocs/visualstudio-docs#3313]
I've been doing my installations from local cache since VS2017. But in VS2019, "offline installation" doesn't work anymore. It keeps trying to connect to the internet. 

I have --includeRecommended and --includeOptional in my layout options just to make sure that required components will be included in the local cache. But still, the problem persists. I'm getting frustrated now. Been trying this since the release of VS2019.

Also, I tried the other suggestion to use vs_setup instead of vs_community, still doesn't work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by abubakarm** [comment]
my command is this:

vs_professional__1645676357.1549550999.exe --layout c:\vslayout --add Microsoft.VisualStudio.Workload.ManagedDesktop --add Microsoft.VisualStudio.Workload.NetWeb --add Component.GitHub.VisualStudio --includeOptional --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --lang en-US

and its downloading, its in progress, I am going to install once it finishes. But i want to say Microsoft could have made it seemless I have no idea why they just "chose" to make it so confusing.

**Comment by TerryGLee** [comment]
@zkyll Thanks for letting us know. 
@tydunkel FYI

**Comment by tydunkel** [comment]
@zkyll Could you provide feedback through our [product feedback site](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)? It will be difficult to determine what the root cause is without logs from the installation and a full repro description.

**Comment by TerryGLee** [comment]
@tydunkel Thanks for your response :)
@zkyll Please do report this through the product feedback site; for more information about how to do so, see the [Report a problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) page. 
@abubakarm It sounds like you have a suggestion to report to us; for more information about how to do so, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) page.

**Comment by allen-sparks** [comment]
I did live chat with customer service. He tried to do a partial install for c++ and it didn't work for him either. He suggested I do the entire layout
>vs_community.exe --layout c:\vslayout --lang en-US

It took forever and I had to use 7zip to split the volume when using a usb drive but it worked.
Admins please update or remove steps that don't work, its not helpful to constantly direct us to customer service
