### ISSUE TITLE
Warning C6217 is spurious; it should be removed

### ISSUE THREAD

**Issue by rgatkinson** [MicrosoftDocs/visualstudio-docs#3314]
The Component Object Model specification (which defines HRESULTs and their use) specifices that the set of 'successful' HRESULTs that may legally be returned from a method or function must be explicitly enumerated in the specification. Often, this is just the single HRESULT 'S_OK'. In such situations, it is perfectly reasonable (and better code is generated) to test against the one S_OK value with a "if (!hr) ... " test rather than using the more verbose "if (SUCCEEDED(hr)) ...". The warning C6217 erroneously flags this reasonable behavior.

Note: I am the original author of the Component Object Model specification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db915c06-a040-2026-150e-8cff941625d5
* Version Independent ID: 3352335b-6955-dd97-5a15-b6a8e593a058
* Content: [C6217 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c6217?view=vs-2019#feedback)
* Content Source: [docs/code-quality/c6217.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c6217.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@rgatkinson apologies for delayed response. As this is potentially a product bug, the place to report it is at [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). The product team actively monitors incoming issues there. Thanks!
