### ISSUE TITLE
Is this still relevant for VS 2017+ ? 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#3315]
...considering they have moved out of the registry?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffe0e292-13f2-0d70-1759-7d750d840c3a
* Version Independent ID: 1f92ed1b-94fb-092e-c604-d891fe22c8d5
* Content: [Registering Single File Generators - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/registering-single-file-generators?view=vs-2019)
* Content Source: [docs/extensibility/internals/registering-single-file-generators.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/registering-single-file-generators.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by madskristensen** [comment]
It may be for native implementations. For managed single-file-generators, [this sample](https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/SingleFileGenerator) is the most up-to-date way of writing them

**Comment by StingyJack** [comment]
@madskristensen - ty for that link. I'll share that with the colleague I was explaining SFG to.
