### ISSUE TITLE
Exporting all projects at once

### ISSUE THREAD

**Issue by thewebchameleon** [MicrosoftDocs/visualstudio-docs#3317]
I know I'm asking much but here's my scenario.

I have a template that I use for most new projects and I constantly add updates to it. I would like to create a visual studio template to make this an easier process going forward rather than renaming the solution manually.

Following these steps solves my immediate problem but the process become rather laborious. It would be great to be able to export all projects at once. Even better would be to automate this with an Azure Pipelines task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e16e6e-e5d1-964b-f220-cbb2c7e4b5e2
* Version Independent ID: 94f82ff9-c61f-31d1-df37-f5e4320daf1c
* Content: [Create project templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-create-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Thanks for this suggestion Adrian. The best place to make product feature suggestions or provide feedback is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Look for the "Suggest a Feature" button:

![image](https://user-images.githubusercontent.com/24882762/50102736-a7218180-01da-11e9-9aaf-ea3a99ccd030.png)

When you suggest a feature on Developer Community, you can engage directly with the engineering team as they consider the suggestion. It also provides a way for other customers to "upvote" your suggestion.
