### ISSUE TITLE
You need to use Visual Basic Windows Forms to make the math quiz!

### ISSUE THREAD

**Issue by All-About-Code** [MicrosoftDocs/visualstudio-docs#3328]

**Comment by TerryGLee** [comment]
@All-About-Code Are you referring to this page? 
https://docs.microsoft.com/en-us/visualstudio/ide/tutorial-2-create-a-timed-math-quiz?view=vs-2019

**Comment by TerryGLee** [comment]
@All-About-Code Haven't heard back regarding my inquiry, but I wanted to let you know that if you were referring to the tutorial that I linked to in my earlier comment, it does include Visual Basic code, starting on this page: https://docs.microsoft.com/en-us/visualstudio/ide/step-2-create-a-random-addition-problem?view=vs-2019.
