### ISSUE TITLE
Visual Studio 2019 for mac Xamarin.Android debugger Does Not Work 

### ISSUE THREAD

**Issue by ethanyuxinzhang** [MicrosoftDocs/visualstudio-docs#3329]
Hi. 

Recently, I have been programming on two similar Apps with Xamarin. For one app, the debugger for Xamarin. Android works fine. However, for the other one, the debugger just won't work at all. According to the doc that on your website (https://docs.microsoft.com/en-us/visualstudio/mac/debugging?view=vsmac-2019), there should be control buttons for stepping through the codes. But the app just doesn't show these buttons and ignored all of the breakpoints. Is there anything special settings for the app itself?

![image](https://user-images.githubusercontent.com/7537190/58457613-76bb1780-816a-11e9-877b-4efaf028a259.png)

**Comment by conceptdev** [comment]
Hi @ethanyuxinzhang, please use the [Report a problem](https://docs.microsoft.com/en-us/visualstudio/mac/report-a-problem?view=vsmac-2019) menuitem in Visual Studio for Mac. If the debugger works fine for one project but not another project, it may be a problem with Visual Studio or the project - but for us to diagnose we need a lot more information, which is automatically gathered when you use that menuitem.
Thanks.
