### ISSUE TITLE
Incorrect description for Microsoft.Net.Core.Component.SDK

### ISSUE THREAD

**Issue by iskiselev** [MicrosoftDocs/visualstudio-docs#333]
Component Microsoft.Net.Core.Component.SDK installs dotnet-sdk-2.0.2-win-x64.exe, but per description it is ".NET Core 1.0 - 1.1 development tools". Description should be ".NET Core 2.0 development tools". Same issue is visible in Visual Studio Build Tools installer - more generally, it contains incorrect description in catalog.json.

**Comment by gewarren** [comment]
This is the topic: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools.

**Comment by iskiselev** [comment]
BTW, description for Microsoft.Net.Core.Component.SDK.1x also looks strange: ".NET Core 1.0 - 1.1 development tools for Desktop".
What does mean there "for Desktop" words? Should they be removed?

**Comment by TerryGLee** [comment]
We are investigating; thanks for your post, @iskiselev.

**Comment by TerryGLee** [comment]
@iskiselev Thanks for reporting this. We've fixed the issue, and it will release with the upcoming Visual Studio 2017 version 15.6 release.
