### ISSUE TITLE
The option Publish does NOT exist in Visual Studio Community

### ISSUE THREAD

**Issue by chelder86** [MicrosoftDocs/visualstudio-docs#3330]
Is it the only option to pay $45 per month to get VS Professional to be able to publish on Azure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92da5d51-dd0e-f62e-c453-8bdaafe04776
* Version Independent ID: 645d4899-f7c6-ffcd-53fa-3b6fb64be765
* Content: [Publish to Azure App Service - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-app-svc?view=vsmac-2019#feedback)
* Content Source: [mac/publish-app-svc.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-app-svc.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by asb3993** [comment]
Hi @chelder86, Publish to Azure is available in all versions of Visual Studio for Mac, including Community. If you're not seeing Publish when you right click on a .NET Core project, please use the "Report an Issue" feature to file it as a bug. Thanks!

**Comment by TerryGLee** [comment]
@asb3993 Thanks for your response; I'll close the issue here as this venue is specific to documentation issues.
