### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by AndyRB** [MicrosoftDocs/visualstudio-docs#3336]
"Learn more about Microsoft for Startups" link returns 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a00c3abb-f124-2ecf-6e37-c20af5c0e9df
* Version Independent ID: 0a80a37a-66ca-89f2-a366-b9704b571884
* Content: [Visual Studio subscriptions offered to startups through the Microsoft for Startups program](https://docs.microsoft.com/en-us/visualstudio/subscriptions/program-startups#feedback)
* Content Source: [subscriptions/program-startups.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/program-startups.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
@AndyRB Thanks for bringing this to our attention.  It looks like that page has been deleted.  I've redirected the link to the home page for Microsoft for Startups.  

@TerryGLee The PR for this has been submitted.  We can close this.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for the follow-up; closing this now.
