### ISSUE TITLE
Directly specify VS version

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/visualstudio-docs#3337]
Based on https://devblogs.microsoft.com/devops/uml-designers-have-been-removed-layer-designer-now-supports-live-architectural-analysis/ and last update date (2016) - I assume, that "class diagrams." feature not available for VS2019.
Could you please directly specify it here to prevent any confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da5ece28-1cef-ffee-c8c1-91877c62c015
* Version Independent ID: 77f11d93-ab0e-8480-5a7b-9a0bc86a2490
* Content: [Visualize code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/visualize-code?view=vs-2019)
* Content Source: [docs/modeling/visualize-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/visualize-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@SychevIgor Sorry for the slow response. Class diagrams are still supported in Visual Studio 2019, but you must first install the **Class Designer** component. For more information, see [How to: Add class diagrams](https://docs.microsoft.com/visualstudio/ide/class-designer/how-to-add-class-diagrams-to-projects?view=vs-2019).

**Comment by SychevIgor** [comment]
@gewarren thank you. I just missed this statement, that it's not working with .net core. 
![image](https://user-images.githubusercontent.com/578954/62680296-97e88180-b9bf-11e9-9b00-f228f57cb356.png)
It will be nice to have this support for .net core projects as well (Microsoft announced that .net 4.8 is the last version of .net framework and future versions will based on .net core), but it's definitely not a scope for this question.
