### ISSUE TITLE
export TF_AUTO_SAVE_CREDENTIALS=1 not working

### ISSUE THREAD

**Issue by zatchgordon** [MicrosoftDocs/visualstudio-docs#3338]
I run the command `export TF_AUTO_SAVE_CREDENTIALS=1`.
Then I'll run a command which runs against a login.. this took me through an OAuth flow.
It wouldn't "auto" save my credentials =&gt; next time I logged in it still asked for my credentials.
I tried `TF_BYPASS_BROWSER_LOGIN=true`
And then logging in as my normal user/password but TFS doesn't allow that anymore.
Next, I made a Personal Access Token and tried that (still assuring the env variable to auto save was still there).
Logged in but still asked for my credentials on subsequent log ins.
Next I tried "alternate credentials"
Logged in but still asked for my credentials on subsequent login ins.

The thing that catches my eye the most is it always defaults to trying "authenticating as..." my actual email whereas I would want it to try my PAT or Alternate Credential. Any help on getting the AUO_SAVE to work?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [Team Foundation Version Control (TFVC) - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control?view=vsmac-2019#feedback)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by zatchgordon** [comment]
Solved by deleting old entries in my Mac Keychain for my email address.
>Open app Keychain Access
>search for the domain
>delete any entries where the account had my email address in it

**Comment by conceptdev** [comment]
Glad you got it working - thanks for sharing the solution.
