### ISSUE TITLE
Doesn't mention tuple member identifier

### ISSUE THREAD

**Issue by Logerfo** [MicrosoftDocs/visualstudio-docs#3339]
Even if it's not supported (I do not possess this knowledge), it should be mentioned as not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b402d2e0-a53a-b61a-4da8-b5ee766d9301
* Version Independent ID: 612695df-5934-d967-d709-500ce02b1395
* Content: [.NET Naming Conventions For EditorConfig files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-naming-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-naming-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mikadumont or @sharwell Can you confirm if naming conventions can target tuple member names?

**Comment by sharwell** [comment]
It's not currently supported. The request for it is https://github.com/dotnet/roslyn/issues/38705.

**Comment by mikadumont** [comment]
@Logerfo I went ahead and made that update!
