### ISSUE TITLE
Microsoft Interop Word Does not work in UWP development

### ISSUE THREAD

**Issue by rajasandeep17** [MicrosoftDocs/visualstudio-docs#3343]
There is no way right now to edit word documents in UWP apps.  There is no code that allows to access/open the word documents on the network folders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 341031d8-e029-a1cf-6d85-159066a9cc8e
* Version Independent ID: 7629f12e-e7cb-4d35-8097-43b800789d03
* Content: [How to: Programmatically update bookmark text - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-update-bookmark-text?view=vs-2019#feedback)
* Content Source: [docs/vsto/how-to-programmatically-update-bookmark-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-update-bookmark-text.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
#please-close
