### ISSUE TITLE
REFERENCE is under the ADD context menu

### ISSUE THREAD

**Issue by AlainPilon** [MicrosoftDocs/visualstudio-docs#3347]
Adding a reference to the project from the test project requires to click on ADD, then REFERENCE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107f3c03-dac2-0226-d5c1-f2f49daa413d
* Version Independent ID: aaf80310-28eb-462b-d4f1-6b97a8abe260
* Content: [Get started with unit testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2019)
* Content Source: [docs/test/getting-started-with-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/getting-started-with-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by hcalxhcalxhcalx** [comment]
Also, default VS Console app is created without any public members, so it can't be referenced in HelloWorldTests code, out of the box
