### ISSUE TITLE
Typo in https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-provide-a-service.md

### ISSUE THREAD

**Issue by maxperga** [MicrosoftDocs/visualstudio-docs#335]
Hello,
  I'm trying to understand how to write a service and I've found a potential typo here:

https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-provide-a-service.md

Could you please double check this code:

> private object CreateService(IServiceContainer container, Type serviceType)  
> {  
>     if (typeof(SMyService) == serviceType)  
>         return new SMyService(this);  
>     return null;  
> }  

Shouldn't this code be "return new MyService(this)" and not a "return new SMyService(this)"?

**Comment by gewarren** [comment]
@maxperga thanks, we'll take a look.

**Comment by gregvanl** [comment]
@maxperga Thanks for pointing this out. You are correct and we will update the code snippet shortly.
