### ISSUE TITLE
Should be using SDK versions not runtime versions

### ISSUE THREAD

**Issue by mrward** [MicrosoftDocs/visualstudio-docs#3352]
I think we should be using SDK versions in the left hand column. It looks like we are using .NET Core runtime numbers. The problem here is that the same runtime can be available in different SDK versions and a particular SDK version may not supported by VS Mac. If I go to the following page it is not obvious to me based on the table shown here what is supported.

https://dotnet.microsoft.com/download/dotnet-core/2.2

For example:

.NET Core 2.2.300 SDK has .NET Core runtime 2.2.5. This SDK version is supported by VS Mac 8.1 but not 8.0.
.NET Core 2.2.107 SDK has .NET Core runtime 2.2.5 also. However this SDK version is supported by VS Mac 8.0.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aecb3dcf-8452-6f71-9202-3ee7564abe06
* Version Independent ID: b57059a9-c666-2481-d2c0-452382220c7b
* Content: [.NET Core support - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/net-core-support?view=vsmac-2019)
* Content Source: [mac/net-core-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/net-core-support.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by mrward** [comment]
It looks like this table was based on the one Jose created. However the information presented here is confusing to me. The problem is that 2.1.5 should be 2.1.500. Jose's matrix:

.NET Core SDK	VSMac
2.1.5nn	8.0
2.1.6nn	8.1
2.2.1nn	8.0
2.2.2nn	8.1	
3.0.1nn	8.1

2.1.5nn here means 2.1.500, etc.

**Comment by asb3993** [comment]
I've made a PR to fix this. It should be updating soon.
