### ISSUE TITLE
Where does it generate the nu get package and how to consume it

### ISSUE THREAD

**Issue by PeterPann23** [MicrosoftDocs/visualstudio-docs#3357]
perhaps this is a nice place to document where it creates the nuget package and what the license settings needs to work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1490ea17-1bce-6eb1-0a78-1b8159b82e4e
* Version Independent ID: 4350b38b-6f06-16b6-da75-4d85c6c43909
* Content: [Assembly Information Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/assembly-information-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(vb.ProjectPropertiesAssemblyInfo)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/reference/assembly-information-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/assembly-information-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Comment to trigger priority label.

**Comment by Mikejo5000** [comment]
I think we're better off linking to NuGet docs from here. I'll update.
