### ISSUE TITLE
How do you configure a python entry_point in launch.vs.json?

### ISSUE THREAD

**Issue by PeterSandberg** [MicrosoftDocs/visualstudio-docs#3358]
How do you configure a python entry_point in launch.vs.json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfaa1bb6-20e0-dadf-7b12-30fa947c520e
* Version Independent ID: 87b861c0-0a08-f6fd-6fa2-9117e853dbbc
* Content: [Quickstart - Open a Python code folder - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/quickstart-05-python-visual-studio-open-folder?view=vs-2019#feedback)
* Content Source: [docs/python/quickstart-05-python-visual-studio-open-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/quickstart-05-python-visual-studio-open-folder.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by Anapo14** [comment]
@bschnurr any thoughts here?

**Comment by bschnurr** [comment]
Can you clarify what you are trying to configure? 

If you're trying to change the startup/entry_point file you can manually edit the "project" field in the launch.vs.json.

If you are trying to pass arguments to your startup/entry_point file you can edit the  "scriptArguments" field.

You can also have multiple entries in "configurations"

**Comment by JoshuaPartlow** [comment]
Closing give time without response. If this is still a problem, please feel free to reopen.
