### ISSUE TITLE
Deploying a UWP project needs to be done from a NTFS formatted drive

### ISSUE THREAD

**Issue by Reynolds-Beta** [MicrosoftDocs/visualstudio-docs#3359]
**Description**
Going through the tutorial to create a UWP app. I'm an experienced developer, but mostly for UI-less services so coding isn't an issue. Just trying to learn something new. Anyways, no problem following the basic steps to create the app and get used to XAML. However, while the code would build just fine, I could not get it to run locally. After checking to make sure my machine was indeed set to developer-mode and still getting error when trying to deploy:

**Expected result**
Application builds and runs

**Actual result**
"Error DEP0700 : Registration of the app failed (0x80073CFD)"

**Root cause**
Turns out, this situation was caused not by VS configuration, but by location of the source project. The project needs to be on a NTFS formatted drive in order to deploy - a footnote that I cannot find anywhere in the requirements for writing a UWP app. Once I moved the project folder to my OS drive, the application was able build and run successfully.

**Change requested**
I think it would be great if this issue would have a KB article, and linked to this page in a troubleshooting section. That, or just highlight the NTFS requirement somewhere on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b088cce-5638-75f8-e42f-a235287cb22c
* Version Independent ID: a36f877f-0fe4-ac36-883f-27a8ec098611
* Content: [Create a Universal Windows Platform (UWP) App with Visual Studio and C#](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-uwp?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-uwp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-uwp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Reynolds-Beta Thanks for letting us know; we'll take this under consideration and report back.

**Comment by Reynolds-Beta** [comment]
Thanks!

Jeff Reynolds
206.979.4047
________________________________

**Comment by ornellaalt** [comment]
Hi @Reynolds-Beta, I added a note on the page that highlights the importance of this requirement. You should see it under step #3, when you are creating the new project. Closing out this issue.
