### ISSUE TITLE
CreateService doesn't compile 

### ISSUE THREAD

**Issue by maxperga** [MicrosoftDocs/visualstudio-docs#336]
Hello,
  I'm reviewing https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md 

and it looks like the snippet around CreateService has some problems.

> protected override async System.Threading.Tasks.Task InitializeAsync(CancellationToken cancellationToken, IProgress<ServiceProgressData> progress)  
> {  
>     this.AddService(typeof(STextWriterService), CreateService);  
> 
>     await base.InitializeAsync(cancellationToken, progress);  
> }  

It looks like CreateService needs something more.

**Comment by gewarren** [comment]
@maxperga thanks for reporting this, we'll take a look.

**Comment by gregvanl** [comment]
Hi @maxperga, I tried the walkthrough and I didn't see any issues with CreateService. The order of the code snippets shows the actual implementation of CreateService in step 3 is a couple of steps below where it is used in step 1. Did you still have problems compilinig when you completed step 3?
