### ISSUE TITLE
IT HELPED ME SO MUCH THANKS!!!

### ISSUE THREAD

**Issue by CBminecraft06** [MicrosoftDocs/visualstudio-docs#3361]
Keep up the good work Microsoft!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f103240-7b3b-4732-12a9-39fdef044a08
* Version Independent ID: 0c9fb9a9-f254-fa5c-a334-3fff7dfccb92
* Content: [Using .NET 4.x in Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/unity-scripting-upgrade?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/unity-scripting-upgrade.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/unity-scripting-upgrade.md)
* Product: **visual-studio-windows**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by therealjohn** [comment]
@CBminecraft06 Thank you!
