### ISSUE TITLE
Visual Studio C++ Core Guideline Checker reports C26485 on correct code

### ISSUE THREAD

**Issue by schoetbi** [MicrosoftDocs/visualstudio-docs#3363]
See: https://godbolt.org/z/4ESplP
The array is passed by reference including the size. When changing line 19 to 

   Format (&v)[4] = AllFormats();@

the code is not compilable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05e8d660-9f3c-74f8-145b-43857fce9fe1
* Version Independent ID: 82b0888a-1662-c3e5-b06b-59f5621c5131
* Content: [C26485 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26485?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C26485)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/code-quality/C26485.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26485.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
@schoetbi Thanks for reporting this. We can repro it, but it needs to be reported on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html) so that we can track it properly. Are you willing to do that? You can also get there by clicking the feedback icon in the upper right of the VS main menu.

**Comment by schoetbi** [comment]
@mikeblome I have reported it here: https://developercommunity.visualstudio.com/content/problem/618317/visual-studio-c-core-guideline-checker-reports-c26.html
Thanks for your investigation.

**Comment by mikeblome** [comment]
@schoetbi thanks very much! Closing this issue because not a documentation problem.
