### ISSUE TITLE
Is it legal to decompile .NET Framework using tools like JetBrains dotPeek?

### ISSUE THREAD

**Issue by user2150** [MicrosoftDocs/visualstudio-docs#3364]
Sometimes it's impossible to get things work (for example, when the downloaded PDB is stripped we get "Source not available" message). There are tools like JetBrains dotPeek which can help, but is it legal? Almost every license agreement nowadays prohibits decompilation, and, if I'm not mistaken, the .NET Framework is no exception:

"You may not" ... "reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software;"

https://dotnet.microsoft.com/dotnet_library_license.htm

But at the same time the Framework is kind of opensource (although we can't get the source code sufficient for building the product, we can get it for investigation), and decompilation doesn't add anything except the ability to debug.

So can we do it?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e04e717-61a6-99eb-60cd-34263fa597b5
* Version Independent ID: 3ee15675-d5bd-f3c9-fb85-1b65b3d71897
* Content: [How to: Debug .NET Framework source - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-dotnet-framework-source?view=vs-2017#feedback)
* Content Source: [docs/debugger/how-to-debug-dotnet-framework-source.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-dotnet-framework-source.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@user2150 Hi, I think it's a better question for the .NET folks rather than VS. @mairaw

**Comment by Mikejo5000** [comment]
@user2150 If this is still a question for you, please re-open on the dotnet repo:
https://github.com/dotnet/standard
