### ISSUE TITLE
An Office 365 subscription is NOT an MSDN benefit

### ISSUE THREAD

**Issue by donr484** [MicrosoftDocs/visualstudio-docs#3367]
This page leads you to believe that you get an Office 365 subscription as an MSDN benefit, which is not true. The keys provided do not provide an Office 365 Subscription. You do not get "1TB of OneDrive storage, 60 Skype minutes per month" etc. You only get the Office Pro Plus 2019 software.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 737f8499-4067-8033-6e5e-edc9eba38fcb
* Version Independent ID: cf03c560-a70c-256e-fc22-f39c51b38b7e
* Content: [Office 365 Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office365#feedback)
* Content Source: [subscriptions/vs-office365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-office365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@donr484 - Thanks for reaching out.  We've corrected the article.

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger16** [comment]
Only Microsoft employees can manage issues via commenting in this repo.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for addressing the issues; I am closing it per your request.

**Comment by evanwindom** [comment]
Thanks, Terry!

**Comment by robliao** [comment]
Has this article been fixed? 
https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office365#getting-started-with-office-365-proplus
Still says
>  Note
> 
> Your Visual Studio subscription entitles you to use Office 365 for production use.

**Comment by evanwindom** [comment]
@robliao  - You are entitled to use the Office 365 subscription included with Visual Studio subscriptions for production use.

**Comment by donr484** [comment]
@evanwindom There is no Office 365 subscription included with Visual Studio subscriptions, only Office 2019 Pro Plus.

**Comment by evanwindom** [comment]
@donr484 --  That's incorrect.  If you have a qualifying subscription, you will see Office 365 listed on the https://my.visualstudio.com/downloads/featured page.

**Comment by donr484** [comment]
@evanwindom I used that very link you provided to get a key that I am using right now, and I do not have an Office 365 subscription. I spent months with Microsoft support (Office, MSDN, etc) trying to activate that benefit, and even used a paid support ticket. 

Microsoft support finally admitted the benefit is for Office Pro Plus, not the Office 365 subscription. You will not get +1TB of OneDrive or Skype Minutes. Office 365 Subscription will not show up on your Microsoft Account. 

When they ended Xbox Music, I lost a huge amount of OneDrive space. Despite the fact that I am paying thousands of dollar per year for MSDN, I still have to pay for extra OneDrive space because there is no Office365 benefit to give me the +1TB of OneDrive space that is advertised. 

It should be removed from MSDN to avoid the very confusion you are experiencing and the pain I went through dealing with support.

**Comment by donr484** [comment]
@robliao
> Has this article been fixed?
> https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office365#getting-started-with-office-365-proplus
> Still says
> 
> Note
> Your Visual Studio subscription entitles you to use Office 365 for production use.

The article to no longer mentions +1TB OneDrive, 60 Skype minutes, etc. That big purple blob, and anywhere on MSDN where it says Office 365 Subscription without qualifying that it is just Office Pro Plus software, is still misleading.

I see Office 2019 Pro Plus now being referred to as Office 365 Pro Plus, which is also confusing and might lead someone to believe they are getting an Office 365 subscription. The Office Pro Plus benefit gives you the latest version of Office, but it is not an Office 365 subscription that comes with +1TB OneDrive, 60 Skype minutes, etc.

When you click get keys under "Office 365 - Production Use", you are only getting the equivalent of the Office 2019 Pro Plus retail key. If you install it and go to your Microsoft Account Services page, you will see "Office Professional Plus 2019". You will not see Office 365 anywhere.

**Comment by evanwindom** [comment]
@donr484 - Thanks for the additional context.  I've confirmed the problem and have escalated the issue to our ops and engineering teams.  I'll provide additional information as it becomes available.

**Comment by pnandak** [comment]
@evanwindom Any Update on this

**Comment by cnelson123** [comment]
It has not been fixed. I just spent two hours trying to figure out how to get 365 so I could upgrade my Android Office apps to the premium versions. The articles still suggest I can get it with my MSDN subscription through the "Office 365 for Production Use" download, but, as others have stated, all you get is the standard Office Pro 2019.
