### ISSUE TITLE
Add .NET Productivity features in Visual Studio 2019 16.1 on

### ISSUE THREAD

**Issue by mikadumont** [MicrosoftDocs/visualstudio-docs#3370]
All features to be added to docs for Visual Studio 2019 Preview 1 and 2, and Update 15.8:

Dev16 Preview 2 ([release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#net-productivity))
- [x] 1. Sync Namespace and Folder Name to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))

Dev16.1 Preview 1 ([release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#--visual-studio-2019-version-1611-))
- [x] 1. Regex completion through intellisense menu to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))
- [ ] 2. Binary expression wrap to be added to wrap parameters ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))
- [x] 3. Split/Merge if statement to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))
- [x] 4. Find All References "Kind" column to be added to ([Find references in your code]( https://docs.microsoft.com/en-us/visualstudio/ide/finding-references?view=vs-2019))

Dev16.1 Preview 2 ([release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#--visual-studio-2019-version-1611-))
- [x] 1. One click code cleanup for projects and solution to be added to ([Code style preferences]( https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019)) and ([Visual Studio productivity guide for C# developers](https://docs.microsoft.com/en-us/visualstudio/ide/csharp-developer-productivity?view=vs-2017))
- [x] 2. Move type to namespace or folder to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))
- [x] 3. Toggle Block Comment add shortcut to ([Visual Studio productivity guide for C# developers](https://docs.microsoft.com/en-us/visualstudio/ide/csharp-developer-productivity?view=vs-2017))
- [ ] 4. Add a private field from a constructors to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))

Dev16.1 Preview 3 ([release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#--visual-studio-2019-version-1611-))
- [x] 1. Toggle Single  Line Comment add shortcut to ([Visual Studio productivity guide for C# developers](https://docs.microsoft.com/en-us/visualstudio/ide/csharp-developer-productivity?view=vs-2017))
- [x] 2. Experimental intellisense completion for unimported types to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))

Dev16.2 Preview 2 ([release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#net-productivity-162p2))
- [x] 1. Sort Usings to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))
- [x] 2. Convert Switch Statement to a Switch Expression to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))
- [x] 3. Generate Parameter to be added to ([Refactor code](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019))

**Comment by kendrahavens** [comment]
Sounds good!
* Maybe split/merge if statement can be its own topic. I'm on the fence. You can decide.
* Maybe don't include "make readonly struct writable". That wasn't a big headline and users can discover it more organically than through docs.

**Comment by gewarren** [comment]
Should this be assigned to Mika instead of Kendra?

**Comment by kendrahavens** [comment]
@mikadumont Maybe we can close this and start a new doc if we don't plan on documenting the missing check immediately.

**Comment by mikadumont** [comment]
Yes lets do that!
