### ISSUE TITLE
Other annotations can lead to this warning

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/visualstudio-docs#3372]
I am seeing this warning emitted for a function annotated by _Releases_lock_, so it's not just _Requires_lock_held_.  There may be other annotations to mention, as there are several _Requires... and _Releases... annotations available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8a3ee91-9cd3-044a-64a5-d3a2de9558f5
* Version Independent ID: ac6fa45e-b857-8e18-0564-9ac06824e374
* Content: [C26110 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26110?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C26110)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/code-quality/c26110.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26110.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by mikeblome** [comment]
Added a link to Annotating Locking Behavior for a list of lock-related annotations. https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-locking-behavior?view=vs-2019
