### ISSUE TITLE
Can't log in to report a problem VS2019

### ISSUE THREAD

**Issue by Unbeneva** [MicrosoftDocs/visualstudio-docs#3376]
In both VS2019 and VS2019 Preview when I try to report a bug I get a "Method not Supported" error and am unable to complete sign in.
The problem I am trying to report is no intellisense for Cocossharp in a project I moved to a different directory.  I have tried using the Nuget package manager to uninstall and reinstall the package, rebooting etc. The original folder works fine.  The project compiles and runs. The path to the reference .dll is correct and it is there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#feedback)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by seaniyer** [comment]
@Unbeneva, Can you try to report the issue from Visual Studio Installer?  In the Installer, select the feedback icon in the upper-right corner and select Report a Problem.

Sean
Visual Studio Feedback Team

**Comment by Unbeneva** [comment]
Hi,  I tried it from the installer and I got the same log in dialog.  After logging in to my microsoft account I get this message:
Your sign-in info has expired. Please sign in again. Re-enter your credentials
This is exactly the same as within the IDE.
I can sign into my GitHub account on the IDE, but I can't activate the license because I get the 'mode no supported' error when trying to log into my microsoft account. Any help would be greatly appreciated. I really don't want it to expire soon.
Thanks

**Comment by acangialosi** [comment]
@Unbeneva Could you email me directly at anthc att microsoft dott com so i can follow up with the engineering team??

**Comment by TerryGLee** [comment]
@Unbeneva I am closing this GitHub Issue now, as it's product-related instead of docs-related, and the product engineering team has reached out to follow up via another venue.
