### ISSUE TITLE
UWP Simulator NFC

### ISSUE THREAD

**Issue by pw3107** [MicrosoftDocs/visualstudio-docs#3378]
Is it possible in VS 2019 using the UWP simulator to simulate NFC tag read/write?
Thanks
Paul. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ccd79a7-1ce8-ecb1-765a-db03899e8158
* Version Independent ID: 7b026550-e924-8969-0ff1-76cd7f4bdffc
* Content: [Run UWP apps in the simulator - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/run-windows-store-apps-in-the-simulator?view=vs-2019)
* Content Source: [docs/debugger/run-windows-store-apps-in-the-simulator.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/run-windows-store-apps-in-the-simulator.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@pw3107 I don't think there is much, if any, ongoing development of the simulator. My recollection is that the use cases for the simulator are pretty minimal after support was added for debugging on a directly connected local device, which was quite a while back.
