### ISSUE TITLE
Report a problem doc is out of date

### ISSUE THREAD

**Issue by karann-msft** [MicrosoftDocs/visualstudio-docs#338]
I am looking at [How to report a problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017).

The screenshots and the flow is out of date.

Also, consider documenting the scenario on how to collect dump when VS has crashed.

**Comment by gewarren** [comment]
@TerryGLee can you look at this? Maybe we can fix the SEO issue at the same time.

**Comment by TerryGLee** [comment]
Thanks for reporting this, @karann-msft. We should have the screenshots updated soon (at the latest, by Monday 11/6).

**Comment by TerryGLee** [comment]
We've updated the screenshots on this page to reflect the latest UI:
https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017  Thanks again for letting us know.

**Comment by karann-msft** [comment]
That's awesome! Thanks Terry!
