### ISSUE TITLE
Please provide small sample project

### ISSUE THREAD

**Issue by mterwoord** [MicrosoftDocs/visualstudio-docs#3380]
This functionality is awesome, and provides great possibilities, but it's difficult to get right.

It would be great if there was a small sample project somewhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe4d604b-9fc6-0c6e-df87-5d68a24b83f5
* Version Independent ID: 4fa85b87-55c7-a165-28f7-f8e1df73613a
* Content: [XAML Designer Extensibility Migration - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/xaml-designer-extensibility-migration?view=vs-2019#feedback)
* Content Source: [docs/extensibility/xaml-designer-extensibility-migration.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/xaml-designer-extensibility-migration.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @lutzroeder
* Microsoft Alias: **lutzr**

**Comment by lutzroeder** [comment]
@mterwoord https://github.com/microsoft/XamlBehaviorsWpf/pull/35 might be helpful as an example. It shows how to implement a `.designtools.dll` for the XAML Behaviors library.

**Comment by mterwoord** [comment]
Awesome. Thanks. That helped a lot. 
See https://github.com/mterwoord/wpf-designer-experiments for my experiments.

My next objective is to get a list of types (and some metadata) in all assemblies, from the perspective of the designer. (ie, referenced assemblies etc)

How can I do that? I can request the AssemblyReferences service, and use GetTypes, but that seems to load the assemblies into the main visual studio process.

**Comment by hemantbajpai4** [comment]
The new Extensibility is still a work in progress, any existing API is potentially subject to change or removal.

**Comment by mterwoord** [comment]
Any idea on when those api's will be roughly fleshed out?

**Comment by lutzroeder** [comment]
Closing as the sample project is now available.

@mterwoord We are working towards enabling `AssemblyReference`. The first iteration will likely be limited to adding assembly references and not include `GetTypes`. We hope adding `GetTypes` in a later release. It isn't committed for a specific release at this point.

**Comment by lutzroeder** [comment]
#please-close
