### ISSUE TITLE
Needs to describe the Intrinsic tag

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/visualstudio-docs#3381]
There is a tag with the name Intrinsic that appears to allow users how to define user defined intrinsic functions.  It would be VERY helpful if this could be documented as I still can't figure out how it works.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#feedback)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Ma-XX-oN There is a link from this page to debugger intrinsic functions:
https://docs.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger?view=vs-2019#BKMK_Using_debugger_intrinisic_functions_to_maintain_state
I don't see a tag for "Intrinsic". Do you have a link with any more info?

**Comment by Mikejo5000** [comment]
This doesn't appear to be supported, as far as I can tell.

**Comment by Ma-XX-oN** [comment]
> This doesn't appear to be supported, as far as I can tell.

Then why does it show up in the natvis.xsd file, which is located on my computer in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Packages\Debugger\natvis.xsd`.  This file is where the popup help I get from the VS IDE:

![image](https://user-images.githubusercontent.com/10625935/63450913-122df280-c411-11e9-8696-676256421860.png)

**Comment by tim-weis** [comment]
The `<Intrinsic>` element is indeed *incredibly* useful for visualizers, both when authoring them and comprehending foreign visualizers. It is supported by at least the following debuggers: CDB, NTSD, WinDbg, WinDbg Preview, and Visual Studio (both for C++ and Rust code).

It is de facto formally specified through .natvis' XSD file, which has also been [published](https://code.visualstudio.com/docs/cpp/natvis#_schema) in VSCode's documentation.

It is being used by the [*stl.natvis*](https://github.com/microsoft/STL/blob/main/stl/debugger/STL.natvis) file that ships with Visual Studio and the Debugging Tools for Windows. Whether this was *intended* to remain an implementation detail doesn't make a difference at this point: Information is out there, and developers [are using](https://github.com/microsoft/windows-rs/blob/master/crates/libs/core/windows.natvis#L30-L31) the `<Intrinsic>` element.

At this point, the best you can do is provide official documentation describing its use and—at your option—a note about its (intended) support status.

Would you reconsider re-opening this issue?

**Comment by WilliamAntonRohm** [comment]
@tim-weis -- Tim, thank you for your follow-up.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
I'm asking about this

**Comment by Mikejo5000** [comment]
Updating the article. The update should be live by EOD today, 2/20/24, PST.
