### ISSUE TITLE
Cannot report a problem from ARM64 windows machine

### ISSUE THREAD

**Issue by paddymcd-MSFT** [MicrosoftDocs/visualstudio-docs#3382]
ARM64 only supported by the remote tools installer.
This installer does not contain facility to leave feedback (it does not appear to be Willow based)
There is apparently no way to report a new problem via the https://developercommunity.visualstudio.com website.

Only work around is to email the details from the ARM64 machine and report the problem from an x64 machine with Visual Studio installed.  This is not a good workflow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#feedback)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by DjArt** [comment]
Also you can't report issue about VS installer on ARM64 machine because VS installer are broken on ARM64.

**Comment by DJGHOSTMACHINE** [comment]
#

**Comment by WilliamAntonRohm** [comment]
@seaniyer -- Sean, please look into this issue.

**Comment by mariaghiondea** [comment]
Please report this suggestion by following this link: https://developercommunity.visualstudio.com/content/idea/post.html?space=8. This will allow us and you to easily track the status of your item, as well as have the community involved in providing comments, votes, answers and which will give us more context and understanding of impact.
