### ISSUE TITLE
Have no "publish" selection on console project

### ISSUE THREAD

**Issue by adsioj** [MicrosoftDocs/visualstudio-docs#3384]
Have no "publish" selection on console project

**Comment by TerryGLee** [comment]
@adsioj Can you tell us what page in our documentation that you are referring to? Thanks in advance for your help.

**Comment by TerryGLee** [comment]
@adsioj Without further information from you, we cannot address the documentation issue that you've logged. So, we're closing this issue now. 

If you'd like to provide us with more information &mdash; and in specific, the name of or a link to the page that you'd like us to fix &mdash; then please feel free to create a new issue and we'll address the documentation feedback. However, if you are looking to provide feedback on a product issue instead, please see our [Visual Studio feedback options](https://docs.microsoft.com/visualstudio/ide/feedback-options?view=vs-2019) page for more information on how best to do so.
