### ISSUE TITLE
What if you have no choice but to write C++ unit tests for separate projects? 

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/visualstudio-docs#3385]
This section here:

-------
# To write unit tests in a separate project

Typically, you run your test code in its own project in the same solution as the code you want to test. To set up and configure a new test project, see Writing unit tests for C/C++.
-------

It does not go in depth on what you need to do if you are forced to create a separate C++ test project and you must test another separate project? In such a scenario, couldn't we make the project to be tested become a dependent project, by adding the project to be tested to this C++ unit test project as a project dependency?

Or will this article be updated so C++ modules may be used for C++ unit testing?

Anyway, in my opinion, I feel the passage above should say, "It is a good idea to keep the tests separate from the code (either as another extra library, or written directly into the test applications.", and it must expand upon this with examples on how to do C++ unit testing with separate projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83cfa6a-8be4-e7b5-bf06-9f70023aaa65
* Version Independent ID: 92877cae-f39e-6653-ce1e-233f75988ba0
* Content: [Use the Microsoft Unit Testing Framework for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp?view=vs-2019)
* Content Source: [docs/test/how-to-use-microsoft-test-framework-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-microsoft-test-framework-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@tommai78101 Sorry the wording perhaps is not clear.  Typically, you right-click on Solution node and choose Add > New Project. Then choose test project.  So you have tests in their own project and they are automatically configured so they can access the other projects in that solution. 

Does that answer your question?

**Comment by tommai78101** [comment]
@mikeblome Yep, it does. I'm assuming that, as this ticket is closed, in the near future, the documentation article will reflect this. Thanks.

**Comment by mikeblome** [comment]
@tommai78101 there is now a link in the first paragraph to a topic that says how to create a new test project. We try not to duplicate information when it already exists somewhere else.
