### ISSUE TITLE
Section should mention about adding header files to "Additional Include Headers" configuration page in Unit Test project

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/visualstudio-docs#3386]
https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2019#add-include-directives-for-header-files

That section above should mention about including project headers into the Additional Include Headers settings of the configuration page of the Unit Testing project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18bdf17-06e1-aaf2-b6ce-c606c0e260da
* Version Independent ID: bd627b8f-54f0-84e0-55cd-285597af022d
* Content: [Write unit tests for C/C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2019)
* Content Source: [docs/test/writing-unit-tests-for-c-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/writing-unit-tests-for-c-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@tommai78101 thanks for the feedback. Topic has been updated.

**Comment by tommai78101** [comment]
Thank you. I'm assuming it's still ongoing, hence the ticket is staying open. Let me know if it's my responsibility to close this ticket, or it's the maintainers' responsibility.

**Comment by mikeblome** [comment]
@tommai78101 that's typically my job although you can also close it if resolved to your satisfaction. I sometimes leave the issue open until the fix is live, which sometimes takes a day or so. Thanks again for helping to improve the documentation.
