### ISSUE TITLE
Missing pages in sample project

### ISSUE THREAD

**Issue by tbrconsulting** [MicrosoftDocs/visualstudio-docs#3387]
I've just downloaded the latest version of Visual Studio 2019.  I have followed the guidance in this page and the following pages are not showing in the project:   About.cshtml and Contact.cshtml.   There is an additional page Privacy.cshtml.   Are these pages available to download separately so I can complete the task?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/quickstart-aspnet-core?view=vs-2019#feedback)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by tbrconsulting** [comment]
The pages are only missing when ASP.Net 2.2 is selected, your guide says open 2.1 or higher.   I've tried again using 2.1 and the pages are there.   I am using VS 2019 version 16.1.2

**Comment by TerryGLee** [comment]
@tbrconsulting Thanks for letting us know; I'll update the doc to remove the "or later" text.
