### ISSUE TITLE
"Extension crash and unresponsiveness notifications"

### ISSUE THREAD

**Issue by MikeDiack** [MicrosoftDocs/visualstudio-docs#3388]
When a crash of Visual Studio occurs, and it is suspected that an extension may be directly or indirectly involved (i.e. there are traces of it in the stack dump), as well as Visual Studio warning us that a specific extension (e.g. Resharper in my case), may have been involved/caused the crash, could the stack dump be made available as a log file to send to the extension maker?

It seems a bit odd that VS does the analysis, makes a determination but then doesn't make the data publically / readily available  so that the extension author(s) can check and if needs be, fix the problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and use extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2019#feedback)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@seaniyer Could you comment on this?

**Comment by seaniyer** [comment]
@MikeDiack 

Could you suggest this feature on https://developercommunity.visualstudio.com?  You can first search that site and see if there is an existing suggestion for the same capability and if so, you can add your vote.  Or create a new suggestion.  Either way, when Visual Studio team follows up you'll automatically receive email updates from the team.

Thanks
Sean
Visual Studio Feedback Team
