### ISSUE TITLE
This warning should not be raised for members of a union when one has been initialized

### ISSUE THREAD

**Issue by ScotBren** [MicrosoftDocs/visualstudio-docs#3391]
Given a union of multiple members, you are allowed to initialize only one of them. But this warning gets raised for others, even though it's not allowed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c92afc49-c727-b9a1-6a49-dc1227bff14f
* Version Independent ID: a914038d-1de0-732a-97dd-0a68e340c0db
* Content: [C26495 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26495?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C26495)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/code-quality/c26495.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26495.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
Hi Scot! For product issues like this, you'll get way better traction on [Developer Community for C++](https://developercommunity.visualstudio.com/topics/C%2B%2B.html)

**Comment by TerryGLee** [comment]
@mikeblome Thanks for your response; we'll close this issue now.
