### ISSUE TITLE
Following links are 404

### ISSUE THREAD

**Issue by merlynoppenheim** [MicrosoftDocs/visualstudio-docs#3393]
Open Folder projects for C++
CMake projects in C++

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f6ef2c-e616-bf4c-6de4-1448814e4f73
* Version Independent ID: b223e86b-b0d8-3a78-3fe5-0938e6641042
* Content: [Customize build debug tasks using tasks.vs.json launch.vs.json - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019&branch=master#feedback)
* Content Source: [docs/ide/customize-build-and-debug-tasks-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/customize-build-and-debug-tasks-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@corob @mikeblome Please try to remember to add redirects for any files that you move. It's probably a good idea to do this retroactively given that these are probably not the only broken links out in the wild.

**Comment by mikeblome** [comment]
@gewarren yes sorry about that. we did a big refactoring a couple months ago and broke these. I created a PR last week that fixed these links and several others in the visual-studio repo: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/4779
