### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by zkyll** [MicrosoftDocs/visualstudio-docs#3396]
I'm losing hope to make things work with vs2019 offline installation. It simply doesn't work. I'm using the same layout as I used in vs2017 and offline installation is working in vs2017. But in vs2019, during installation, always asking to connect to the internet. I'll just revert to vs2017 where everything was smooth. Pfft!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@zkyll Thanks for letting us know. We'll look in to this. @tydunkel FYI.

**Comment by tydunkel** [comment]
@zkyll Thank you for the info! Could you please file an issue through our [feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)? Offline install issues tend to be case-by-case issues that require logs to investigate. Thanks!

**Comment by TerryGLee** [comment]
@tydunkel Thanks for your response. I'll close this product issue now, as it is best handled via the [feedback tool](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).

**Comment by allen-sparks** [comment]
I did live chat with customer service. He tried to do a partial install for c++ and it didn't work for him either. He suggested I do the entire layout
>  vs_community.exe --layout c:\vslayout --lang en-US
It took forever and I had to use 7zip to split the volume when using a usb drive but it worked.
Admins please update or remove steps that don't work, its not helpful to constantly direct us to customer service
