### ISSUE TITLE
MSBuild: Please document v. 15.1

### ISSUE THREAD

**Issue by borgdylan** [MicrosoftDocs/visualstudio-docs#34]
I was reading the documentation site and noticed reference to MSBuild 12. I'd like a place with guidance for the latest MSBuild that is in RC. When is such documentation expected?

**Comment by ghogen** [comment]
We are aware this work and have plans to update the docs for MSBuild 15.1 fairly soon.

**Comment by kempb** [comment]
FYI, some topics have been updated, and more will be coming.

**Comment by Mikejo5000** [comment]
Addressed several issues in docs and created PR. I need to investigate a few other issues.

**Comment by Mikejo5000** [comment]
PM will be back in December

**Comment by Mikejo5000** [comment]
PR for this: MicrosoftDocs/visualstudio-docs-pr#1357

**Comment by Mikejo5000** [comment]
Merged linked PR, updates should be live on 2/13/18
