### ISSUE TITLE
Microsoft.VisualStudio.Threading API docs need refresh from xml doc file

### ISSUE THREAD

**Issue by AArnott** [MicrosoftDocs/visualstudio-docs#3400]
This [doc on JoinableTaskFactory.SwitchToMainThreadAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.joinabletaskfactory.switchtomainthreadasync?view=visualstudiosdk-2017) needs to be updated to include the more descriptive parameter documentation and the details on the OperationCanceledException throwing that are [documented here](https://github.com/microsoft/vs-threading/blob/8c9c7a44eb4ff6284b373fc416fc1e9dbfae4cab/src/Microsoft.VisualStudio.Threading/JoinableTaskFactory.cs#L142-L153).

You can get the .xml file to regenerate/refresh docs from [the nuget package](https://www.nuget.org/packages/microsoft.visualstudio.threading) or from [a recent CI build's](https://dev.azure.com/azure-public/vside/_build?definitionId=12&_a=summary) "deployables" artifact. Find the xml file in the `lib\net46` folder of the package.

Also, the API itself is shown as if the default parameter value was null, when in fact it's a value type so null doesn't apply here. The default is "default(CancellationToken)".

**Comment by TerryGLee** [comment]
FYI: Here is a helpful URL re: this issue: [Documenting NuGet Packages](https://review.docs.microsoft.com/en-us/help/onboard/admin/reference/dotnet/documenting-nuget?branch=master)
