### ISSUE TITLE
Very Helpful!

### ISSUE THREAD

**Issue by AnonyMeXx** [MicrosoftDocs/visualstudio-docs#3403]
This was extremely helpful to me and let me follow around my variables to see what is going on. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72264f70-4d8e-7612-87c9-3dab87fb2f14
* Version Independent ID: b7b7d351-5d53-c225-47e4-5ae46d6afc75
* Content: [Set a watch on variables - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/watch-and-quickwatch-windows?view=vs-2019#feedback)
* Content Source: [docs/debugger/watch-and-quickwatch-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/watch-and-quickwatch-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AnonyMeXx Thank you!
