### ISSUE TITLE
Base image wrong

### ISSUE THREAD

**Issue by csteenwyk** [MicrosoftDocs/visualstudio-docs#3404]
I tried the above dockerfile, it didn't work. I think you need the FROM in the dockerfile to read: 4.7.2-20190312-windowsservercore-ltsc2019

According to this https://github.com/dotnet/announcements/issues/109 the above image now contains VS2019 runtimes which seems to cause the VS2017 build tools installer to fail silently

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
It will change as newer Windows images are released. @TerryGLee, should we be keeping this up to date as newer base images are released? These are samples, after all.

**Comment by TerryGLee** [comment]
@heaths Thanks for your response; I'll investigate and report back.
