### ISSUE TITLE
Why not just give a link?

### ISSUE THREAD

**Issue by VisualMicro** [MicrosoftDocs/visualstudio-docs#3405]
Considering all the sign in problems when trying to log issues via Visual Studio it would be nice to avoid the endless internet searches just to report an issue. Would be nice to just get the link!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by seaniyer** [comment]
@VisualMicro

I'm sorry you are experiencing sign in issues.  If you are still experiencing difficulty with sign in, would you be able to share details such as error message received?  Reporting issues from Visual Studio enables us to collect diagnostics that help address your problem more effectively. It also reduces effort for customers like you to have to provide logs and other diagnostic details.

**Comment by VisualMicro** [comment]
Thanks for the reply. I can understand that reporting issues from vs makes sense a lot of the time but I have windows universal subscription and I expect to be able to report bugs or seek assistance.

The problem I have is that on two completely different machines (home/work) and with two different ms logons I am unable to use either vs2017 or 2019 to report issues.

The error that appears in the awful issue reporting window can't be copied so I write it by hand.

Error signing in: '{}' Let us know
Problem signing in? Please try signing in using Visual Studio.

I have rebooted, I have signed into vs a number of times cleanly. Each time using either of my two accounts in the hope that the issue is related to one account. My other account is tl@interactivesoftware.co.uk

I stated, this happens on two entirely different networks and machines I can also tell you that my Visual Studo versions are up to date. The issue happen in Vs2017 Pro, VS2019 16.1 (.0, .1, .2 and .3) community and VS2019 Preview.

One problem I want to report is that VS2019 is reporting that our extension is delaying VS for 5+ seconds. The line of code causing the delay is simply this:-
 DTE.Properties("Projects", "VCGeneral")

The slowness accessing the dte properties exists in vs2017 + and is very slow after any extension has been installed and randomly slow at other times. Sometimes the line of code takes on 220ms but most times much loner. We access the property in Package IntializeAsync after switching to the main thread and getting the DTE2 service. It's very simply.

So this is one example of where our reputation with our our customers is being damaged by a slowness in VS yet we have been unable to contact Microsoft to report the problem.

Your help will be appreciated

Thanks


Tim Leek

Visual Micro Limited

web: https://www.visualmicro.com


________________________________

**Comment by agpreynolds** [comment]
Same issue for me:

Error is:
Error signing in: '{}' Let us know
Problem signing in? Please try signing in using Visual Studio.

Really frustrating when you have an issue to report

**Comment by seaniyer** [comment]
@VisualMicro 

Tim, I have submitted a problem on your behalf. Please go to the report using below link and vote so you will be notified on progress updates from Visual Studio team.
https://developercommunity.visualstudio.com/content/problem/696373/slowness-accessing-dte-properties.html

Thanks
Sean

**Comment by seaniyer** [comment]
> Same issue for me:
> Error is:
> Error signing in: '{}' Let us know
> Problem signing in? Please try signing in using Visual Studio.
> Really frustrating when you have an issue to report

@agpreynolds, @VisualMicro - We are sorry sign in has been a frustrating experience.  We are working to fix it.  The issue is being tracked and updated at the issue linked below.  You can vote so you get automatic notifications when there are updates.
https://developercommunity.visualstudio.com/content/problem/583234/error-signing-to-vs-feedback-tool.html?childToView=681384#comment-681384

Thanks
Sean
Visual Studio Feedback Team

**Comment by VisualMicro** [comment]
Thank you

Tim

**Comment by Legends** [comment]
If MS had a github repo for VS issues, I guess it would explode :D ;-)
