### ISSUE TITLE
Would be nice to make mention of what the plan is for NodeJS.

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/visualstudio-docs#3407]
I came here hoping to find support for NodeJS projects. From what I understand is that NodeJS is not yet supported but is planning to be supported soon. If you can make mention of it in this article, that would benefit me and possible others a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 794dde29-e54d-a2bb-4cb0-2fdf1a4cc067
* Version Independent ID: 9ef5f973-dcd6-da26-957d-28d1604cf739
* Content: [JavaScript and TypeScript - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/javascript?view=vsmac-2019)
* Content Source: [mac/javascript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/javascript.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks for your question @AskYous. Future product plans are not something we generally cover in the documentation, which is focused on current features and how to use them. We do have a [Roadmap page](https://docs.microsoft.com/visualstudio/productinfo/mac-roadmap) where you can learn about upcoming releases - it also has links where you can make suggestions or report issues.
