### ISSUE TITLE
Use var when extracting variable

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#3413]
Would it be possible to get a setting (if not default behavior) to use var when introducing the variable, instead of the explicit type (e.g. Random in the example above)?

(Recreating this on behalf of @sbrockway due to accidental transfer of the original issue he logged.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f5507b1-1a79-329c-9c0b-074af493e641
* Version Independent ID: 48a6a90c-2876-0162-c3cb-900f85f09c8b
* Content: [Introduce a local variable - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/introduce-local-variable?view=vs-2019)
* Content Source: [docs/ide/reference/introduce-local-variable.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/introduce-local-variable.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
/cc @kendrahavens 
I'm wondering if the code style settings for "var" preferences have any effect on this refactoring?

![image](https://user-images.githubusercontent.com/24882762/59288417-9b15fa00-8c28-11e9-9784-592d0952fae1.png)

**Comment by gewarren** [comment]
Apologies for the accidental transfer of the original issue @sbrockway - and GitHub won't let me transfer it back.

**Comment by sbrockway** [comment]
@gewarren you are correct. Those settings work perfectly. Thank you!
