### ISSUE TITLE
Followed instructions but HTTP function responds with a 404

### ISSUE THREAD

**Issue by AskYous** [MicrosoftDocs/visualstudio-docs#3415]
I wanted to create an HTTP triggered function with "functions" permissions. I did the following:

1. Set the function type to HTTP trigger,
2. Set the permission level to "function"
3. Deployed it Azure.
4. It launched my browser to my function and I see a blue welcome page saying "Your Function App is up and running"
5. I navigate to my function: http://idb-dialog-flow.azurewebsites.net/api/idb_dialog_flow, and it responds with a 404.

Is it because something went wrong? Is it because I didn't provide a key due to the permission levels I set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4caaf0cc-3cea-375a-1160-6540db5557f1
* Version Independent ID: cfd2fe36-1325-9ff0-bc18-af563bb920e4
* Content: [Introduction to Azure Functions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions?view=vsmac-2019)
* Content Source: [mac/azure-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/azure-functions.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by TerryGLee** [comment]
@AskYous Thanks for letting us know; we'll take a look at this to see if there is a documentation impact. Meanwhile, here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

@conceptdev Please take a look to see if there is a documentation impact to this support request; if not, please close the issue.

**Comment by sayedihashimi** [comment]
@AskYous can you provide a link to the specific doc that you followed?

**Comment by AskYous** [comment]
@sayedihashimi 

It is this one:
https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions?view=vsmac-2019

**Comment by AskYous** [comment]
I just created a function from the azure portal instead of VS for Mac and it's working now.
