### ISSUE TITLE
Incorrect character to ASCII mapping

### ISSUE THREAD

**Issue by vukelich** [MicrosoftDocs/visualstudio-docs#3416]
In the fourth row of the Special Characters table, the grave accent (i.e. backtick `) is in the character column, but the ASCII code 0x27 is for the single quote character ( ' ). Which is the actual reserved character?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 665605c0-95ba-10a1-1d91-3c2b863630b1
* Version Independent ID: 2b544ce8-21dc-74b9-4bc2-53d36a0add15
* Content: [MSBuild Special Characters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-special-characters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-special-characters.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by TerryGLee** [comment]
@vukelich Thanks for letting us know; we have a PR in place to change this, which should go live tomorrow (Pacific Daylight Time).
