### ISSUE TITLE
XSLT debugger available in the Professional edition of Visual Studio

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [MicrosoftDocs/visualstudio-docs#3417]
The note "The XSLT debugger is only available in the Enterprise edition of Visual Studio." is wrong.

The XSLT debugger was and is available in the Professional edition also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd893f19-8b45-6789-ee72-15439f7a7816
* Version Independent ID: 12d0b503-0dc0-3777-d73f-306fbdc425b4
* Content: [Ways to debug XSLT code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xml-tools/debugging-xslt?view=vs-2019#feedback)
* Content Source: [docs/xml-tools/debugging-xslt.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xml-tools/debugging-xslt.md)
* Product: **visual-studio-windows**
* Technology: **vs-xml-tools**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by HaraldMuehlhoffCC** [comment]
I'm very impressed with the speed this issue was handled! Thank you!

May I ask when the other language versions (like my native German) will be updated?

**Comment by gewarren** [comment]
@HaraldMuehlhoffCC Thanks - well it was any easy fix :) In fact, did you know you can even update the docs yourself? There's an edit button on the top right, and we welcome contributions.

As for when the localized version will be updated, I think it normally takes about a week but @JasonCard to confirm.

**Comment by JasonCard** [comment]
Hi @HaraldMuehlhoffCC 
This article is being machine-translated and we pick up updates daily in the morning.
So update will be picked up tomorrow morning and updated translation should be published by end of day tomorrow.
cc @gewarren
