### ISSUE TITLE
VS 2019 Release 16.1.3 is missing from releases page

### ISSUE THREAD

**Issue by LazerFX** [MicrosoftDocs/visualstudio-docs#3419]
The latest release (16.1.3) is missing on the releases page for Visual Studio 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019#feedback)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@LazerFX Thanks for letting us know; we have already a PR in place and this page will be updated with 16.1.3 data no later than noon today (Pacific Daylight Time, or PDT).
