### ISSUE TITLE
Python > Django Create Superuser

### ISSUE THREAD

**Issue by rraajjeevv** [MicrosoftDocs/visualstudio-docs#3424]
When creating a super user I am getting the following error -
---
Microsoft Visual Studio\Shared\Python37_64\lib\getpass.py:100: GetPassWarning: Can not control echo on the terminal.
  return fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
----

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485e6157-bf3f-1065-d944-9860f198662c
* Version Independent ID: 8daa9161-23cb-8bfb-b736-6695b6e50ee8
* Content: [Learn Django tutorial in Visual Studio step 4, web project template](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-04-full-django-project-template?view=vs-2019#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by TerryGLee** [comment]
@rraajjeevv Thanks for letting us know. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

Meanwhile, here are a few more places where you might find more information: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
