### ISSUE TITLE
Changing channelUri value has no effect

### ISSUE THREAD

**Issue by dukeofdarkness23** [MicrosoftDocs/visualstudio-docs#3425]
If the channelUri property in the reponse.json file is updated after client machines have installed VS - does it have any affect?

I have a layout on a network share that client machines used for their initial installation with the default response.json file.

However, even if I change the channelUri value to point to the network share location of the ChannelManifest.json  ("\\\\server\\share\\VS\\ChannelManifest.json") the VS Installer client still prompts users to update to a later version than is on the layout.

i.e. I have machines that are at 15.4. The Layout was updated to 15.12. The response.json is updated to use layout location of manifest. - Whenever I run the Installer it shows 15.13 is available and installs that version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba75701e-a3d1-4127-01a5-1170e9c20814
* Version Independent ID: 1206143e-7c82-dde1-8b75-657525fb7d6b
* Content: [Control updates to deployments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/controlling-updates-to-visual-studio-deployments?view=vs-2019)
* Content Source: [docs/install/controlling-updates-to-visual-studio-deployments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/controlling-updates-to-visual-studio-deployments.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@tydunkel FYI about this.

@dukeofdarkness23 Thanks for letting us know. We'll take a look but our response might be delayed. Meanwhile, if you require immediate assistance, here are a few more support options:

- We offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.

-	Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

-	You can report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.

**Comment by tydunkel** [comment]
@dukeofdarkness23 The `installChannelUri` needs to be set before VS is installed. Otherwise, the URI is saved and the installer will always look to that URI for updates. Unfortunately, there is no supported way to change this short of uninstalling and reinstalling.

**Comment by TerryGLee** [comment]
@tydunkel Thanks for your response; I will close this issue now.

**Comment by satorp** [comment]
@tydunkel Is it `channelUri` or `installChannelUri` that needs to be set before installation? The [documentation](https://docs.microsoft.com/en-us/visualstudio/install/controlling-updates-to-visual-studio-deployments?view=vs-2019) says `channelUri` is the URI that the installer will look for updates. I think the documentation does not explain the difference of the two properties very well. So what's the correct procedure to control updates?

**Comment by tydunkel** [comment]
@satorp sorry, I meant `channelUri`. The `channelUri` informs the installer about where to look for updates for that Visual Studio installation. Setting it during the first installation is how updates can be controlled. `installChannelUri` is used just for that session. It can be used to control a single update.

**Comment by satorp** [comment]
@tydunkel Thanks for the clarification. I have a VS 2019 offline installation on a network shared folder, and I want to control the updates using the procedure described in the documentation. Here's the content of my `Response.json`:
```
{
    "installChannelUri": ".\\ChannelManifest.json",
    "channelUri": "https://aka.ms/vs/16/release/channel",
    "installCatalogUri": ".\\Catalog.json",
    "channelId": "VisualStudio.16.Release",
    "productId": "Microsoft.VisualStudio.Product.Professional",
    "addProductLang": [
        "en-US"
    ]
}
```
The installation is for VS 2019 version 13.2 and what I want to do is to have all users install that version on their machines, and disable the automatic update, until I've updated the installation to a newer version. The [documentation](https://docs.microsoft.com/en-us/visualstudio/install/controlling-updates-to-visual-studio-deployments?view=vs-2019) says that I should point the `channelUri` to a network shared location, but when I set it to the same file as `installChannelUri` the installer returns an error saying the the specified `channelId` and `productId` cannot be found. The installer works when `channelUri` is pointed to the Microsoft URL as above, but it will always try to install the newest version (currently 13.3.2), not the version on the shared folder. It seems that the only workaround now is to copy the whole folder to a local folder on user machine and execute the installer from there.

**Comment by tydunkel** [comment]
@satorp The ".\\" prefix on the path implies a relative path to the channel manifest. Is the channel manifest next to the installer when it runs on all machines? Without logs I am guessing that the download of the channel manifest from the share is failing, but from the web is successful. This leads to installing the latest (16.3.2) rather than the version in your manifest.

I would suggest using an absolute path.

e.g. "channelUri": "\\\\fileshare\\share\\ChannelManifest.json"

With that, the update will be controlled by the channel manifest in that location. Until it is updated, clients will never be allowed to update to another version. Similarly, I believe the `installCatalogUri` and `installChannelUri` should be absolute paths.

You also should set `layoutPath` in the response file to point to the share with all the packages in your layout. Without it, the install will not know where the packages are to download and will instead download from the web rather than the offline layout.

**Comment by satorp** [comment]
@tydunkel Changing to absolute path was also the first thing that came into my mind, but it doesn't seem to make any difference. Now I've also tried your suggestion of adding the `layoutPath`, but the installer still tries to install the latest version.

The error I mentioned previously (`channelId` and `productId` cannot found) seems to be related to the installer certificates (the log says "channel manifest failed test signature validation"). After installing the appropriate certificates as described [here](https://developercommunity.visualstudio.com/content/problem/664198/vs-2019-unable-to-install-offline.html), the error has disappeared. So now I can have the `channelUri` pointed to a network shared file, but the installer still tries to get the latest version.

**Comment by Otiel** [comment]
For those interested, it is possible to update the `channelUri` of an existing VS installation, without having to uninstall VS.

Steps are described [here](https://developercommunity.visualstudio.com/t/changing-an-existing-installation-to-use-an-offlin/358584#T-N358674) by gavin.lambert, copied verbatim below:

>Ok, after more fiddling around, I have determined that the following procedure seems to work. (I don't know if it's safe, but it seems to do what I want):
>
>1. Ensure that the channelUri in the Response.json in the network layout is set to the full path and filename to the ChannelManifest.json file, as documented.
>2. Edit C:\ProgramData\Microsoft\VisualStudio\Packages\_Instances\hex code\state.json and change both channelUri and installChannelUri to the same filename, and change layoutPath to the directory containing that file.
>3. Delete all but one directory in C:\ProgramData\Microsoft\VisualStudio\Packages\_Channels (ideally keep the directory where the channelManifest.json file has the same "id" as the version of VS in the network layout, but I don't know if that actually matters).
>4. Copy and replace the ChannelManifest.json and Catalog.json files from the network layout to the _Channels subdirectory that you kept above.
>5. Edit the copied channelManifest.json file and (immediately before the "channelItems" property) add "updateUri": "full path to network ChannelManifest.json", "canUpdate": true,
>6. Go to %localappdata%\Microsoft\VisualStudio\Packages\_Channels, delete all subdirectories, and then copy in the whole hexcode subdirectory with the _Channels files that were modified just above.
>
>I'm not entirely clear on why there are two sets of _Channels folders or if both need to be updated. However I did notice that if the %localappdata% folders exist, then they override the ones in C:\ProgramData, so it's not sufficient to update ProgamData alone. It's possible that it's sufficient to merely delete the local _Channel folders (as presumably the installer will then look at the ProgramData folders), but I didn't test that.
