### ISSUE TITLE
Windows containers

### ISSUE THREAD

**Issue by kedves93** [MicrosoftDocs/visualstudio-docs#3429]
The Node.js install commands work because the example uses a Linux container. I need exactly the same for an ASP .NET Core app with Angular, but on a Windows container. This is a Microsoft page and instead of a Windows container the example uses a Linux container. Why is that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1abf884f-eb39-1007-25a6-d049b87504a3
* Version Independent ID: 33636e79-d3e1-8c24-f3a5-0c3c79e2a488
* Content: [Visual Studio Container Tools with ASP.NET Core - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019)
* Content Source: [docs/containers/container-tools-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-tools-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
I agree that we should cover both Linux and Windows container scenarios. Will update appropriately.

**Comment by ghogen** [comment]
Section added.
https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019#modify-the-dockerfile-windows-containers
