### ISSUE TITLE
This is happening every time I open my solution now

### ISSUE THREAD

**Issue by blmille1** [MicrosoftDocs/visualstudio-docs#3431]
How do I fix this?  It happens within a couple of minutes of reopening the solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72292f7a-7616-4727-ccd3-cf44bb130477
* Version Independent ID: fe3cca82-dfd7-a85c-ab4f-014bc546d668
* Content: [A process has encountered an unrecoverable error - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/visual-studio-unrecoverable-process-error?view=vs-2019#feedback)
* Content Source: [docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@blmille1  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by andy-soft** [comment]
I suffer the same issue, every single time I open my solution!!!

**Comment by dinobu** [comment]
Same here, VS 2019 v16.1.6 (Enterprise)
