### ISSUE TITLE
No generic runtime-agnostic TypeScript documentation

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/visualstudio-docs#3434]
No documentation on how to create a plain TypeScript project. All examples and everything else involve NodeJs in one form or another.
There should at the very least be info on the most basic use-case, like a single html-file and a single typescript file.
But really, there should really be core TypeScript documentation, without any assumption on run-time environment or anything else as a base, then on top of that you can include samples for popular frameworks and use cases.

### Things that need clarification and elaboration
1. Why are there several packages/distributions for TypeScript?
    1. When to use the different ones?
    2. What are the purpose of the different pacgages?
    3. What's the recommended way to include full support for all features of TypeScript in Visual Studio?
    4. How do you manage updates of TypeScript when using the TypeScript Extension from the Visual Studio Market place, when the T[ypeScriptTeam release a completely new package for each new version of TypeScript](https://marketplace.visualstudio.com/publishers/TypeScriptTeam)?
    5. What if you have the TypeScript SDK from the Visual Studio Installer, should you still use NuGet or other additional TypeScript Packages?

2. TypeScript and source maps

3. TypeScript and types
    1. What options are there?
    2. Which is the recommended way of referencing types?
    3. how do you keep any references to types up to date?

4. What settings are there that control the various aspects of how TypeScript work, function, operate and interact with a project and it's files.
    1. where can these settings be found
    2. how does the different settings in the different files and in the  GUI-based options in Visual Studio (Menu: Tools -> Options) relate and interact with each other?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34d7baa-5b74-4a87-ed21-d7fc8d9366b3
* Version Independent ID: 0249ae3d-5f05-812d-46f0-ad5a921358a4
* Content: [JavaScript and TypeScript in Visual Studio 2019 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2019?view=vs-2019&lc=1033)
* Content Source: [docs/javascript/javascript-in-vs-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/javascript-in-vs-2019.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by wangzimei** [comment]
when studying tasks in vs code
https://code.visualstudio.com/docs/editor/tasks
by typing tsc --init in dev cmd prompt i got "tsc is not recognized as an internal or external command, ..."
in "new project" dialog in visual studio i see typescript project template is unavailable
go to vs installer i see typescript sdk 3.4 is checked
go to this doc i see Visual Studio 2019 provides 3 options for integrating TypeScript
https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2019?view=vs-2019
2. The TypeScript SDK, available by default in the Visual Studio installer

reminds me that years ago vs code announced it has node.js support, yet i can't use node.js without download and install it.

**Comment by Mikejo5000** [comment]
There are some more docs planned for this area, but it's on the backlog. Do you have access here:
https://github.com/Microsoft/JSTSdocs

**Comment by Bartolomeus-649** [comment]
I don't get a 404 or something like that when visiting https://github.com/Microsoft/JSTSdocs , but I have no way of knowing if I see everything there or not.

**Comment by Mikejo5000** [comment]
You probably see everything. Some of the articles here are stubs, but some we plan to move to the main doc site. None are probably basic Hello World articles for plain TS, but there are some TS docs here.

**Comment by AaronLS** [comment]
I've been through several documents and as someone with 10+ years javascript and C# experience it's hard to believe that not a single one of them leads to a working solution.

**Comment by Mikejo5000** [comment]
For non-Nodejs dependent scenarios, we added this tutorial on ASP.NET Core with TypeScript.
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2019
Since ASP.NET and Node.js are the two main runtime scenarios here, we're prioritizing those over a single HTML file + TS file scenario (I don't see an "empty project" template that would be useful for this).

**Comment by Bartolomeus-649** [comment]
A tutorial is not documentation!

**Comment by Mikejo5000** [comment]
Right, and I didn't close the issue here. The other work is on the backlog.

**Comment by Mikejo5000** [comment]
As noted previously, doc priority is on the ASP.NET Core and Node.js scenarios. NuGet or tsc are recommended over the TypeScript SDK, as noted in the docs.

Recent docs have provided more details on TS installation / build /configuration:

https://docs.microsoft.com/en-us/visualstudio/javascript/compile-typescript-code-nuget?view=vs-2019
https://docs.microsoft.com/en-us/visualstudio/javascript/compile-typescript-code-npm?view=vs-2019

And we have the ASP.NET Core tutorial that describes adding third-party libraries and getting IntelliSense for them:
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2019

If there is high priority content that you think still needs to be added, please open a new issue. Thanks!
