### ISSUE TITLE
type ‘<-’

### ISSUE THREAD

**Issue by wanghanlin9821** [MicrosoftDocs/visualstudio-docs#3437]
I wanna to type the '<-' quickly in vs2017 while programming R language, is there any keyboard shortcut about '<-' in vs?

**Comment by TerryGLee** [comment]
@wanghanlin9821 Thanks for your question. We do have a few pages that include our keyboard shortcuts; for more information, see the following:

- [Default keyboard shortcuts in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2019)
- [Popular keyboard shortcuts for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-for-frequently-used-commands-in-visual-studio?view=vs-2019)

However, I don't see anything specific to the R language in that documentation. You might consider asking your question in a different forum. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by gewarren** [comment]
Closing this issue now.
