### ISSUE TITLE
Linkedin learning benefits are not activating from my.visualstudio.com . Please help

### ISSUE THREAD

**Issue by basitbilwani** [MicrosoftDocs/visualstudio-docs#3438]
What to do now?

**Comment by evanwindom** [comment]
@basitbilwani - Thanks for reaching out.  LinkedIn is no longer offering the 3-month Premium benefit through Visual Studio Dev Essentials.  A one-month free trial is available at https://www.linkedin.com/learning/me.  If you are using a Visual Studio Dev Essentials membership, you also have access to training benefits from Pluralsight and DataCamp.  

@TerryGLee - #please-close
