### ISSUE TITLE
VS 2017 remote debugging tools link broken

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/visualstudio-docs#3443]
It redirects to a page that says "Sorry, we couldn't find any downloads for you."  The VS 2019 remote debugging tools download link works fine.  This might affect other links - I didn't check them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2fd746-82f7-1bac-9932-27c14cdfe0ca
* Version Independent ID: 46b43a94-b750-2073-5e28-82183af092a9
* Content: [Remote Debug a C# or VB project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@jordanmills Hi Jordan, which link did you have trouble with ? VS 2017? The links all work for me. For VS 2017 and VS 2015 (my.visualstudio.com links), you have to either sign in or be signed in already. What browser are you using?

**Comment by jordanmills** [comment]
I missed that message (I see the email now).  I think it was VS 2017 and 2014(?).  Yes the links want me to sign in, that was the problem.  It's lame when they put a human-only interface in front of a download link, needs to be fixed.

**Comment by Mikejo5000** [comment]
I don't believe you need to sign in for the VS 2019, but you do for VS 2017/2015, because those links are on my.visualstudio.com, which was a business decision.
