### ISSUE TITLE
Add documentation for new rule CA2244 (AvoidDuplicateElementInitialization) added in FxCopAnalyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3449]
1. Does not exist in legacy FxCop
2. Rule implementation is here: https://github.com/dotnet/roslyn-analyzers/blob/3bb0de8da1b17cdd2f8e39af52510a6083f1abff/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AvoidDuplicateElementInitialization.cs#L17
3. Rule diagnostic message and desription are defined here: https://github.com/dotnet/roslyn-analyzers/blob/5ed057905c4e4def7f9e5abd4baccf8fc7286b4a/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/MicrosoftQualityGuidelinesAnalyzersResources.resx#L225-L233
```
  &lt;data name="AvoidDuplicateElementInitializationDescription" xml:space="preserve"&gt;
    &lt;value&gt;Indexed elements in objects initializers must initialize unique elements. A duplicate index might overwrite a previous element initialization.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AvoidDuplicateElementInitializationMessage" xml:space="preserve"&gt;
    &lt;value&gt;The element at index [{0}] has already been initialized. Previous initializations of this element may be overwritten.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AvoidDuplicateElementInitializationTitle" xml:space="preserve"&gt;
    &lt;value&gt;Do not duplicate indexed element initializations&lt;/value&gt;
  &lt;/data&gt;
```
4. Some unit tests to show the flagged duplicate initializers inside object/collection initializers: https://github.com/dotnet/roslyn-analyzers/blob/bcf2215966b9ba579111287cadf03727ea33fece/src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/AvoidDuplicateElementInitializationTests.cs#L49

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efeb8cf2-d939-bb4e-3853-a6cf7a6c561f
* Version Independent ID: 01010ef0-bf36-9e98-1047-3f63c925bdb1
* Content: [Usage Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/usage-warnings?view=vs-2019)
* Content Source: [docs/code-quality/usage-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/usage-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/2244
