### ISSUE TITLE
Community provided article on Cross Platform App Development White Paper

### ISSUE THREAD

**Issue by terrysheng** [MicrosoftDocs/visualstudio-docs#345]
Hi all, attached please find an article submitted by a China RD a while back which was published on a local section of the MSDN library and had higher views that other articles, meaning customers were looking at it. It provides an overview of cross-platform app development through VS from a Business Manager's point of view.
It has been reverse-machine-translated to provide you with a readable English version - if you think it has some merit and could find a place in the official documentation, please do let me know and we can work with the author to have it amended as necessary.
This also serves as a test, to see if it's efficient to use this process for such submissions/proposals (that's why I'm using the private repo instead of the public one)
thanks to let me know your thoughts

[ZH-CN Cross Platform App Development White Paper.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/1456670/ZH-CN.Cross.Platform.App.Development.White.Paper.zip)

**Comment by gewarren** [comment]
@ghogen can you take a look at this?

**Comment by gewarren** [comment]
@conceptdev does this fall into your area? Can you comment on the request to include the whitepaper as part of our doc set?

**Comment by conceptdev** [comment]
it seems to be a translation of [this article](http://devopshub.cn/2015/10/30/cross-platform-dev-1-cost-analysis/)?

i would say it reads like a case-study and probably isn't appropriate for the docs site... it might fit better on visualstudio.com in a marketing/customer case study capacity, or in a local community blog? it seems a little outdated (Connect 2014 is mentioned, and the [myshuttle](http://myshuttle-demo.azurewebsites.net) azure sample they discuss appears to be offline). 

> This also serves as a test, to see if it's efficient to use this process for such submissions/proposals 

i am separately working with the localization team to figure out how we can accept localized submissions, but (to my knowledge) we do not have a system in place for this at the moment.
