### ISSUE TITLE
Add documentation for new Reliability rule CA2010 (AlwaysConsumeTheValueReturnedByMethodsMarkedWithPreserveSigAttribute) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3450]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Microsoft.NetCore.Analyzers/Core/InteropServices/AlwaysConsumeTheValueReturnedByMethodsMarkedWithPreserveSigAttribute.cs#L11
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Microsoft.NetCore.Analyzers/Core/InteropServices/SystemRuntimeInteropServicesAnalyzersResources.resx#L168-L176
```
  &lt;data name="AlwaysConsumeTheValueReturnedByMethodsMarkedWithPreserveSigAttributeTitle" xml:space="preserve"&gt;
    &lt;value&gt;Always consume the value returned by methods marked with PreserveSigAttribute&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AlwaysConsumeTheValueReturnedByMethodsMarkedWithPreserveSigAttributeDescription" xml:space="preserve"&gt;
    &lt;value&gt;PreserveSigAttribute indicates that a method will return an HRESULT, rather than throwing an exception. Therefore, it is important to consume the HRESULT returned by the method, so that errors can be detected. Generally, this is done by calling Marshal.ThrowExceptionForHR.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AlwaysConsumeTheValueReturnedByMethodsMarkedWithPreserveSigAttributeMessage" xml:space="preserve"&gt;
    &lt;value&gt;Consume the hresult returned by method '{0}' and call Marshal.ThrowExceptionForHR.&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests: Seems like the rule was added with no unit tests :-(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b1e122-10d7-7c20-b802-097db9dfa58a
* Version Independent ID: 465b7427-04d3-ba5d-5a3a-88425b82f171
* Content: [Reliability Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/reliability-warnings?view=vs-2019)
* Content Source: [docs/code-quality/reliability-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/reliability-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/2010

**Comment by mavasani** [comment]
Rule has been deprecated/removed: https://github.com/dotnet/roslyn-analyzers/pull/3581
