### ISSUE TITLE
Add documentation for new Reliability rule CA2009 (DoNotCallToImmutableCollectionOnAnImmutableCollectionValue) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3451]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/2f94c36db114d8ab2517939c01e4390806c95cdb/src/Microsoft.NetCore.Analyzers/Core/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValue.cs
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/be88d50ca67287ea8d0e64afb5484893c8acedfe/src/Microsoft.NetCore.Analyzers/Core/ImmutableCollections/SystemCollectionsImmutableAnalyzersResources.resx#L120-L125
```
  &lt;data name="DoNotCallToImmutableCollectionOnAnImmutableCollectionValueTitle" xml:space="preserve"&gt;
    &lt;value&gt;Do not call ToImmutableCollection on an ImmutableCollection value&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="DoNotCallToImmutableCollectionOnAnImmutableCollectionValueMessage" xml:space="preserve"&gt;
    &lt;value&gt;Do not call {0} on an {1} value&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests: https://github.com/dotnet/roslyn-analyzers/blob/42ea4c1a782881ab8a94071eabc6d1137ed31542/src/Microsoft.NetCore.Analyzers/UnitTests/ImmutableCollections/DoNotCallToImmutableCollectionOnAnImmutableCollectionValueTests.cs#L17

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b1e122-10d7-7c20-b802-097db9dfa58a
* Version Independent ID: 465b7427-04d3-ba5d-5a3a-88425b82f171
* Content: [Reliability Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/reliability-warnings?view=vs-2019)
* Content Source: [docs/code-quality/reliability-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/reliability-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/2009
