### ISSUE TITLE
Add documentation for new Reliability rule CA2008 (DoNotCreateTasksWithoutPassingATaskScheduler) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3452]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Microsoft.NetCore.Analyzers/Core/Tasks/DoNotCreateTasksWithoutPassingATaskScheduler.cs#L14
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Microsoft.NetCore.Analyzers/Core/Tasks/SystemThreadingTasksAnalyzersResources.resx#L120-L128
```
  &lt;data name="DoNotCreateTasksWithoutPassingATaskSchedulerTitle" xml:space="preserve"&gt;
    &lt;value&gt;Do not create tasks without passing a TaskScheduler&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="DoNotCreateTasksWithoutPassingATaskSchedulerDescription" xml:space="preserve"&gt;
    &lt;value&gt;Do not create tasks unless you are using one of the overloads that takes a TaskScheduler. The default is to schedule on TaskScheduler.Current, which would lead to deadlocks. Either use TaskScheduler.Default to schedule on the thread pool, or explicitly pass TaskScheduler.Current to make your intentions clear.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="DoNotCreateTasksWithoutPassingATaskSchedulerMessage" xml:space="preserve"&gt;
    &lt;value&gt;Do not create tasks without passing a TaskScheduler&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests for reference: https://github.com/dotnet/roslyn-analyzers/blob/9c08642f76abffb8cce34aa1971a046e69ce710d/src/Microsoft.NetCore.Analyzers/UnitTests/Tasks/DoNotCreateTasksWithoutPassingATaskSchedulerTests.cs#L16

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b1e122-10d7-7c20-b802-097db9dfa58a
* Version Independent ID: 465b7427-04d3-ba5d-5a3a-88425b82f171
* Content: [Reliability Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/reliability-warnings?view=vs-2019)
* Content Source: [docs/code-quality/reliability-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/reliability-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca2008
