### ISSUE TITLE
Add documentation for new Performance rule CA1826 (DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectly) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3453]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/8652fbcc81b1dcc133c0f53da0d5bbd9f3d0d28b/src/Microsoft.NetCore.Analyzers/Core/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectly.cs#L19
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/760b9c9188cf95ec6ab8cbadb75a1d129d15442f/src/Microsoft.NetCore.Analyzers/Core/Runtime/SystemRuntimeAnalyzersResources.resx#L276-L284
```
  &lt;data name="DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTitle" xml:space="preserve"&gt;
    &lt;value&gt;Do not use Enumerable methods on indexable collections. Instead use the collection directly&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyDescription" xml:space="preserve"&gt;
    &lt;value&gt;This collection is directly indexable. Going through LINQ here causes unnecessary allocations and CPU work.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyMessage" xml:space="preserve"&gt;
    &lt;value&gt;Do not use Enumerable methods on indexable collections. Instead use the collection directly&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests: https://github.com/dotnet/roslyn-analyzers/blob/bcf2215966b9ba579111287cadf03727ea33fece/src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTests.cs#L10
5. Code fixer unit tests: https://github.com/dotnet/roslyn-analyzers/blob/1d48d1e19f7cf966947560b92afc9da6c8c1ae3b/src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/DoNotUseEnumerableMethodsOnIndexableCollectionsInsteadUseTheCollectionDirectlyTests.Fixer.cs#L14

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6821238-fc59-9229-824a-c7ddc6d6e98b
* Version Independent ID: 518e70a1-9dc2-be79-76f7-13689ebacaea
* Content: [Performance Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/performance-warnings?view=vs-2019)
* Content Source: [docs/code-quality/performance-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/performance-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca1826
