### ISSUE TITLE
Add documentation for new Performance rule CA1825 (AvoidZeroLengthArrayAllocations) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3454]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Microsoft.NetCore.Analyzers/Core/Runtime/AvoidZeroLengthArrayAllocations.cs#L14
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/760b9c9188cf95ec6ab8cbadb75a1d129d15442f/src/Microsoft.NetCore.Analyzers/Core/Runtime/SystemRuntimeAnalyzersResources.resx#L270-L275
```
  &lt;data name="AvoidZeroLengthArrayAllocationsTitle" xml:space="preserve"&gt;
    &lt;value&gt;Avoid zero-length array allocations.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AvoidZeroLengthArrayAllocationsMessage" xml:space="preserve"&gt;
    &lt;value&gt;Avoid unnecessary zero-length array allocations.  Use {0} instead.&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests: https://github.com/dotnet/roslyn-analyzers/blob/9c08642f76abffb8cce34aa1971a046e69ce710d/src/Microsoft.NetCore.Analyzers/UnitTests/Runtime/AvoidZeroLengthArrayAllocationsTests.cs#L18

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6821238-fc59-9229-824a-c7ddc6d6e98b
* Version Independent ID: 518e70a1-9dc2-be79-76f7-13689ebacaea
* Content: [Performance Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/performance-warnings?view=vs-2019)
* Content Source: [docs/code-quality/performance-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/performance-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca1825
