### ISSUE TITLE
Add documentation for new Maintainability rule CA1509 (InvalidEntryInCodeMetricsConfigFile) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3455]
The Code metrics rules (CA1501, CA1502, CA1505, CA1506) allow configuring code metrics via a special code metrics rule specification file provided as an additional file. For example, see https://github.com/dotnet/roslyn-analyzers/blob/3bb0de8da1b17cdd2f8e39af52510a6083f1abff/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/CodeMetricsAnalyzer.cs#L33-L43. Any invalid entries in this file flag CA1509 to warn the users about unintentional configuration bugs. See unit tests for CA1509 for more concrete examples: https://github.com/dotnet/roslyn-analyzers/blob/9c08642f76abffb8cce34aa1971a046e69ce710d/src/Microsoft.CodeQuality.Analyzers/UnitTests/Maintainability/CodeMetricsAnalyzerTests.cs#L514

Diagnostic message and description: https://github.com/dotnet/roslyn-analyzers/blob/a53d969164f500dde4609757d23f853544080694/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/MicrosoftMaintainabilityAnalyzersResources.resx#L237-L245

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784927d7-2cab-8a78-9c03-42867f207774
* Version Independent ID: bdf8c31c-f20e-7761-6fcd-560d63f134b8
* Content: [Maintainability Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/maintainability-warnings?view=vs-2019)
* Content Source: [docs/code-quality/maintainability-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/maintainability-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca1509
