### ISSUE TITLE
Add documentation for new Documentation rule CA1200 (AvoidUsingCrefTagsWithAPrefix) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3456]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Microsoft.CodeQuality.Analyzers/Core/Documentation/AvoidUsingCrefTagsWithAPrefix.cs#L13
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/32d8f1e397439035f0ecb5f61a9e672225f0ecdb/src/Microsoft.CodeQuality.Analyzers/Core/Documentation/XmlDocumentationCommentsAnalyzersResources.resx#L121-L129
```
  &lt;data name="AvoidUsingCrefTagsWithAPrefixTitle" xml:space="preserve"&gt;
    &lt;value&gt;Avoid using cref tags with a prefix&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AvoidUsingCrefTagsWithAPrefixDescription" xml:space="preserve"&gt;
    &lt;value&gt;Use of cref tags with prefixes should be avoided, since it prevents the compiler from verifying references and the IDE from updating references during refactorings. It is permissible to suppress this error at a single documentation site if the cref must use a prefix because the type being mentioned is not findable by the compiler. For example, if a cref is mentioning a special attribute in the full framework but you're in a file that compiles against the portable framework, or if you want to reference a type at higher layer of Roslyn, you should suppress the error. You should not suppress the error just because you want to take a shortcut and avoid using the full syntax.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AvoidUsingCrefTagsWithAPrefixMessage" xml:space="preserve"&gt;
    &lt;value&gt;Avoid using cref tags with a prefix&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests: https://github.com/dotnet/roslyn-analyzers/blob/9c08642f76abffb8cce34aa1971a046e69ce710d/src/Microsoft.CodeQuality.Analyzers/UnitTests/Documentation/AvoidUsingCrefTagsWithAPrefixTests.cs#L18

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84d427d-0ae4-f380-c544-041141e6c541
* Version Independent ID: a4601b4b-bbda-3502-4bbc-e66367781bce
* Content: [Code Analysis for Managed Code Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-warnings?view=vs-2019)
* Content Source: [docs/code-quality/code-analysis-for-managed-code-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-for-managed-code-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca1200

**Comment by mavasani** [comment]
Taking this up
