### ISSUE TITLE
Add documentation for new Design rule CA1068 (CancellationTokenParametersMustComeLast) in FxCop analyzers

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3458]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/2d5189b4042e7b85ea2a4257b06f4f27bce853a7/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/CancellationTokenParametersMustComeLast.cs#L13
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/6f1134023da162fe19af94d7006ada8bfa694608/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx#L433-L438
```
  &lt;data name="CancellationTokenParametersMustComeLastTitle" xml:space="preserve"&gt;
    &lt;value&gt;CancellationToken parameters must come last&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="CancellationTokenParametersMustComeLastMessage" xml:space="preserve"&gt;
    &lt;value&gt;Method '{0}' should take CancellationToken as the last parameter&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests: https://github.com/dotnet/roslyn-analyzers/blob/2d5189b4042e7b85ea2a4257b06f4f27bce853a7/src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/CancellationTokenParametersMustComeLastTests.cs#L10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149bfa5d-cc9d-086c-8ced-42d47eeb576d
* Version Independent ID: b6cc25f3-a35e-0a95-8f40-0fc6c3c6d218
* Content: [Design Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/design-warnings?view=vs-2019)
* Content Source: [docs/code-quality/design-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/design-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca1068

**Comment by mavasani** [comment]
Taking this up.
