### ISSUE TITLE
Add documentation for new Design rules CA1066 (ImplementIEquatable) and CA1067(OverrideObjectEquals)

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3459]
1. Does not exist in legacy FxCop
2. Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/8984fd672f4d1ad6ce05bebe048e841d1f99d4b4/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/EquatableAnalyzer.cs#L13
3. Rule message and description: https://github.com/dotnet/roslyn-analyzers/blob/6f1134023da162fe19af94d7006ada8bfa694608/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx#L427-L432, https://github.com/dotnet/roslyn-analyzers/blob/6f1134023da162fe19af94d7006ada8bfa694608/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx#L958-L963 and https://github.com/dotnet/roslyn-analyzers/blob/6f1134023da162fe19af94d7006ada8bfa694608/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/MicrosoftApiDesignGuidelinesAnalyzersResources.resx#L988-L993
```
    &lt;data name="ImplementIEquatableWhenOverridingObjectEqualsTitle" xml:space="preserve"&gt;
    &lt;value&gt;Type {0} should implement IEquatable&lt;T&gt; because it overrides Equals&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="ImplementIEquatableWhenOverridingObjectEqualsMessage" xml:space="preserve"&gt;
    &lt;value&gt;Implement IEquatable when overriding Object.Equals&lt;/value&gt;
  &lt;/data&gt;
    &lt;data name="OverrideObjectEqualsMessage" xml:space="preserve"&gt;
    &lt;value&gt;Type {0} should override Equals because it implements IEquatable&lt;T&gt;&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="OverrideObjectEqualsTitle" xml:space="preserve"&gt;
    &lt;value&gt;Override Object.Equals(object) when implementing IEquatable&lt;T&gt;&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="ImplementIEquatableWhenOverridingObjectEqualsDescription" xml:space="preserve"&gt;
    &lt;value&gt;When a type T overrides Object.Equals(object), the implementation must cast the object argument to the correct type T before performing the comparison. If the type implements IEquatable&lt;T&gt;, and therefore offers the method T.Equals(T), and if the argument is known at compile time to be of type T, then the compiler can call IEquatable&lt;T&gt;.Equals(T) instead of Object.Equals(object), and no cast is necessary, improving performance.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="OverrideObjectEqualsDescription" xml:space="preserve"&gt;
    &lt;value&gt;When a type T implements the interface IEquatable&lt;T&gt;, it suggests to a user who sees a call to the Equals method in source code that an instance of the type can be equated with an instance of any other type. The user might be confused if their attempt to equate the type with an instance of another type fails to compile. This violates the "principle of least surprise".&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests: https://github.com/dotnet/roslyn-analyzers/blob/1c10fbedffe6fc268b4ddba3ad3df6b1bd6fbf72/src/Microsoft.CodeQuality.Analyzers/UnitTests/ApiDesignGuidelines/EquatableAnalyzerTests.cs#L9

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 149bfa5d-cc9d-086c-8ced-42d47eeb576d
* Version Independent ID: b6cc25f3-a35e-0a95-8f40-0fc6c3c6d218
* Content: [Design Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/design-warnings?view=vs-2019)
* Content Source: [docs/code-quality/design-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/design-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.

**Comment by paulomorgado** [comment]
This is a chicken and egg problem. The link needs to exist to be on the diagnostic and the diagnostic needs to exist to have documentation.

I propose that the links be like [C# compiler message links](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/) and have just the ID. This way, a diagnostic can have a link automatically assigned.
