### ISSUE TITLE
VS Mac uninstall steps do not remove third party addins

### ISSUE THREAD

**Issue by mrward** [MicrosoftDocs/visualstudio-docs#346]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall.md

The Visual Studio for Mac uninstall guide has:

```
To remove all traces of Visual Studio for Mac, the following commands should be run in Terminal:

sudo rm -rf "/Applications/Visual Studio.app"
rm -rf ~/Library/Caches/VisualStudio
rm -rf ~/Library/Preferences/VisualStudio
rm -rf "~/Library/Preferences/Visual Studio"
rm -rf ~/Library/Logs/VisualStudio
rm -rf ~/Library/VisualStudio
rm -rf ~/Library/Preferences/Xamarin/
rm -rf ~/Library/Developer/Xamarin
```

This seems to not remove any third party extensions/addins that may have been installed. Just wondering if we should list this addin location as a folder to remove or have a section about removing third party extensions. Third party extensions are installed in `~/Library/Application Support/VisualStudio/7.0/LocalInstall/Addins/`

However there also seems to be an installer folder here in `~/Library/Application Support/VisualStudio/7.0/LocalInstall/Installer/` so it might be worth just listing the `~/Library/Application Support/VisualStudio` as a folder to remove.

**Comment by gewarren** [comment]
@conceptdev could you take a look at this?

**Comment by asb3993** [comment]
PR created so closing this.
