### ISSUE TITLE
Add documentation for Maintainability rule CA1509 (CodeMetricsAnalyzer) in FxCopAnalyzers

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#3465]
Rule Implementation: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/Maintainability/CodeMetricsAnalyzer.cs#L26

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efeb8cf2-d939-bb4e-3853-a6cf7a6c561f
* Version Independent ID: 01010ef0-bf36-9e98-1047-3f63c925bdb1
* Content: [Usage Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/usage-warnings?view=vs-2019)
* Content Source: [docs/code-quality/usage-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/usage-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca1509

**Comment by mavasani** [comment]
Duplicate of https://github.com/MicrosoftDocs/visualstudio-docs/issues/3455?

**Comment by paulomorgado** [comment]
Yes!
