### ISSUE TITLE
Add documentation for new Reliability rule CA2007 (DoNotCreateTasksWithoutPassingATaskScheduler) in FxCopAnalyzers

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#3466]
Rule implementation: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/ApiDesignGuidelines/DoNotDirectlyAwaitATask.cs#L17

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1b1e122-10d7-7c20-b802-097db9dfa58a
* Version Independent ID: 465b7427-04d3-ba5d-5a3a-88425b82f171
* Content: [Reliability Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/reliability-warnings?view=vs-2019)
* Content Source: [docs/code-quality/reliability-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/reliability-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca2007

**Comment by eddynaka** [comment]
I think we can close this issue.

the ca2007 page is available at: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007-do-not-directly-await-task?view=vs-2019

**Comment by gewarren** [comment]
@eddynaka Thanks, closing now!
