### ISSUE TITLE
Add documentation for Security rule CA5378 (DoNotSetSwitch) in FxCopAnalyzers

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#3489]
Rule implementation: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Core/Security/DoNotSetSwitch.cs#L23

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1295961-36c4-75a0-f50a-c5d86159746c
* Version Independent ID: 3d4bba1e-0d05-f577-3b78-65dd6ab10635
* Content: [Security Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/security-warnings?view=vs-2019)
* Content Source: [docs/code-quality/security-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/security-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by paulomorgado** [comment]
Bootsrapped: https://github.com/paulomorgado/MicrosoftDocs-visualstudio-docs/tree/paulomorgado/ca5378

**Comment by eddynaka** [comment]
I think we can close this issue.

the ca5378 page is available at: https://docs.microsoft.com/en-us/visualstudio/code-quality/ca5378?view=vs-2019

**Comment by gewarren** [comment]
Awesome, thanks @eddynaka.
