### ISSUE TITLE
Code Map - Some Options not available or working when using .NET Core 2.2 Framework 

### ISSUE THREAD

**Issue by Sh4dowfox007** [MicrosoftDocs/visualstudio-docs#3500]
When right clicking a class while on the edit screen for a C# file in .NET Framework 4.7.1 you can see the Code Map options, however when doing the same action on a class using .NET Core 2.2 Framework there are no Code Map options. 

Note you have the right click option to show on code map when done via the Solution Explorer. 

Expected Results:
Have ALL Code Map options.

Additionally, while viewing the the classes/methods in the Code Map Viewer if you double click or right click -> View Content the system does not navigate to the related object while using .NET Core 2.2. Also the right click option of Find All References is not available. 

Expected Results:
The user should be navigated to the correct location similar to .NET Framework, and all options should be displayed in both context menus.

**Comment by msebolt** [comment]
@Sh4dowfox007  Thanks for your feedback; we appreciate it. 

To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
