### ISSUE TITLE
How can I add all the projects for an azure devops or tfs project collection at once?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#3501]
Clicking each one is really tedious, and the TeamExplorer.config has values I dont know how to get via API.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f31dd7-e676-aa47-cb11-8ad77412fb5a
* Version Independent ID: 6cce7a4b-8f62-610d-f75f-fafc7b4c444a
* Content: [Connect to projects in Team Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/connect-team-project?view=vs-2019)
* Content Source: [docs/ide/connect-team-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/connect-team-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by KathrynEE** [comment]
@StingyJack - Thank you for your inquiry. The method you use may depend on the version of Team Explorer/Visual Studio that you are using.  I will update the topic to illustrate these methods. 

For Visual Studio 2015, there is a Select All check box you can use. 

![image](https://user-images.githubusercontent.com/10856840/63067247-d7810300-bec2-11e9-9470-11557af8804c.png)


For VS-2017 or VS-2019, you can shift-click to select multiple projects and then choose Connect. 


![image](https://user-images.githubusercontent.com/10856840/63067452-e74d1700-bec3-11e9-9c08-d3a3a6c93f57.png)
