### ISSUE TITLE
VSPerfCmd /start option lists invalid keywords

### ISSUE THREAD

**Issue by mtrdp642** [MicrosoftDocs/visualstudio-docs#3502]
Using the Performance Tools for Visual Studio 2019 version 16.0.28917.181, obtained from [here](https://visualstudio.microsoft.com/downloads/).

[The docs site](https://docs.microsoft.com/en-us/visualstudio/profiling/start?view=vs-2019#feedback) lists valid `/start` methods as 'trace', 'sample', 'coverage', and 'concurrency', but running `vsperfcmd /?` only lists 'trace' and 'coverage' as valid modes. Attempting to use 'sample' results in an error: `Switch sample is not a valid value for the START switch. Aborting.`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0d83d03-a6c7-9f13-c75d-b5abfe3286e8
* Version Independent ID: 8ac09799-df92-435a-afc6-9cc6f64ff760
* Content: [Start - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/start?view=vs-2019#feedback)
* Content Source: [docs/profiling/start.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/start.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Correct, sampling via the command line is not supported in VS 2019. The doc has been previously removed from VS 2019 docs. For more info, see:
https://docs.microsoft.com/en-us/visualstudio/profiling/profiling-feature-tour?view=vs-2019#analyze-performance-legacy-tools
