### ISSUE TITLE
Certificates downloaded by the tool seems to be inconsistent with #what-are-the-certificates-files-in-the-certificates-folder

### ISSUE THREAD

**Issue by johnaho** [MicrosoftDocs/visualstudio-docs#3504]
Following the layout instructions on a related page (https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019#use-the-command-line-to-create-a-local-cache)

I ran: vs_professional --layout c:\vslayout --lang en-US
And when it was done my certificates folder only has 3 certs in it. 
manifestCounterSignRootCertificate.cer
manifestRootCertificate.cer
vs_installer_opc.RootCertificate.cer

And I don't see : ManifestSignCertificates.p12   which yields 'Microsoft Root Certificate Authority 2011' - A cert I need for an install that is currently stuck erroring out there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e4bce72-0471-4ff0-6948-671f2e1f9f9f
* Version Independent ID: 3a255b89-a741-5bcc-4342-e4e4943197e1
* Content: [Install certificates required for an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-certificates-for-visual-studio-offline?view=vs-2019#what-are-the-certificates-files-in-the-certificates-folder)
* Content Source: [docs/install/install-certificates-for-visual-studio-offline.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-certificates-for-visual-studio-offline.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@johnaho Thanks for letting us know; we're investigating and will update our documentation as necessary. 

Meanwhile, if you are receiving an error that is preventing you with proceeding, consider also filing a bug by using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by TerryGLee** [comment]
@johnaho We recently updated this page so it should match what you expect to see. Thanks for helping us improve the documentation!
