### ISSUE TITLE
Not available offline through Help Viewer 2.3

### ISSUE THREAD

**Issue by LoadLibrary** [MicrosoftDocs/visualstudio-docs#3505]
This page is not available offline through Help Viewer 2.3.
Help Viewer 2.3 doesn't have option for downloading documentation for VS 2019 Extensibility.

**Comment by TerryGLee** [comment]
@LoadLibrary Thanks for your feedback; to clarify, you're referring to the content here, correct?
https://docs.microsoft.com/en-us/visualstudio/extensibility/?view=vs-2019

**Comment by LoadLibrary** [comment]
Yes, the up-to-date content for VS 2019 SDK.

**Comment by ghogen** [comment]
Yes, this will be available soon. We are working on building the offline books.

**Comment by ghogen** [comment]
The offline books for VS 2019 have been published.
