### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by BruceForstall** [MicrosoftDocs/visualstudio-docs#3508]
The example in "Batch one item at a time" doesn't work because the quotes need to be escaped: `"` =&gt; `&quot;`, i.e.: `&lt;Message Text = "Identity: &quot;%(Identity)&quot; -- Items in ExampColl: @(ExampColl)"/&gt;`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b17d417b-9aa2-b39e-53a9-169d8148bf38
* Version Independent ID: e5c51cbf-c4fb-264d-e465-af914ff703f6
* Content: [Item Metadata in Task Batching - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-metadata-in-task-batching?view=vs-2019)
* Content Source: [docs/msbuild/item-metadata-in-task-batching.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/item-metadata-in-task-batching.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by BruceForstall** [comment]
Of course, this web page did a transformation on my example...

**Comment by NextTurn** [comment]
MicrosoftDocs/feedback#1987
