### ISSUE TITLE
Linked enum references have incorrect link text

### ISSUE THREAD

**Issue by darthwalsh** [MicrosoftDocs/visualstudio-docs#351]
When looking at the [MenuCommands Vs. OleMenuCommands](https://docs.microsoft.com/en-us/visualstudio/extensibility/menucommands-vs-olemenucommands) page, I see that the [source](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/menucommands-vs-olemenucommands.md) "MenuCommand Property | OLECMDF flag" table has the wrong data in the `OLECMDF flag` column:

|MenuCommand Property|OLECMDF flag|  
|--------------------------|------------------|  
|<xref:System.ComponentModel.Design.MenuCommand.Checked%2A> = `true`|<xref:Microsoft.VisualStudio.OLE.Interop.OLECMDF>|  
|<xref:System.ComponentModel.Design.MenuCommand.Visible%2A> = `false`|<xref:Microsoft.VisualStudio.OLE.Interop.OLECMDF>|  
|<xref:System.ComponentModel.Design.MenuCommand.Enabled%2A> = `true`|<xref:Microsoft.VisualStudio.OLE.Interop.OLECMDF>|  

Compare that to the correct [original MSDN docs](https://msdn.microsoft.com/en-us/library/bb165468.aspx?f=255&MSPPError=-2147217396), which has different values in the `OLECMDF flag` column:

|MenuCommand Property|OLECMDF flag|
|--- |--- |
|Checked = true|OLECMDF_LATCHED|
|Visible = false|OLECMDF_INVISIBLE|
|Enabled = true|OLECMDF_ENABLED|

It would be simple to fix this one issue, but I doubt the issue only happens in this one file.

It seems that when HTML anchors were converted to markdown xref tags, the link text was ignored‽
Maybe the bug in the conversion tool could be fixed, and then the delta could be merged back into this documentation?

**Comment by gewarren** [comment]
@darthwalsh thanks for reporting this. Unfortunately I have seen this issue with other enumeration references too, so it is systemic. @gregvanl could you fix this one and any other enumeration references you can find in extensibility docs?

**Comment by gewarren** [comment]
@gregvanl I'm assigning this back to you since no-one picked it up in the PM bootcamp.

**Comment by gregvanl** [comment]
Updated to show values as there are no individual enum value pages on dotnet/api.

**Comment by gewarren** [comment]
@gregvanl this is a way to reference enum values:

[Visible](xref:System.ComponentModel.Design.MenuCommand#System_ComponentModel_Design_MenuCommand_Visible)
