### ISSUE TITLE
Add documentation for Usage rule CA2245 (AvoidPropertySelfAssignment) in CodeQuality.Analyzers doc-bug

### ISSUE THREAD

**Issue by mclayton7** [MicrosoftDocs/visualstudio-docs#3510]
Rule implementation: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AvoidPropertySelfAssignment.cs

@gewarren I'm not sure how to make this link back to the visual studio page here: https://docs.microsoft.com/en-us/visualstudio/code-quality/usage-warnings?view=vs-2019

**Comment by gewarren** [comment]
Closing as a dupe of #3511.
