### ISSUE TITLE
How can we integrate FxCop analyzers into the CI/CD pipeline?

### ISSUE THREAD

**Issue by NenoLoje** [MicrosoftDocs/visualstudio-docs#3512]
When using Azure DevOps, it seems that the analyzers (from the NuGet Package) get executed - but their warnings and errors are ignored and don't show up in the build result. Any tips?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8b46f1e-f497-6606-18b5-6e2a4c6d64db
* Version Independent ID: c1e762c4-ae37-541d-f3b9-038cb7041305
* Content: [FxCop code analysis and FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers-faq?view=vs-2019#feedback)
* Content Source: [docs/code-quality/fxcop-analyzers-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/fxcop-analyzers-faq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
The only thing I can think of is the rule severity is set to "Info", which means any violations don't appear in build output. If you build from the command line, do you see errors and warnings?

**Comment by NenoLoje** [comment]
@gewarren I've done some research today. Here's what I learned:

- When the rule severity is set to "Error", then indeed msbuild (or dotnet.exe) fails. However, you need to look into the logs to figure out why. Azure Pipelines only shows you that msbuild/dotnet.exe failed (and not why). This isn't a nice experience.

- When the rule severity is set to "Warning", the warning is indeed printed to the log. However, as it's not failing the build, that warning does not show up anywhere in Azure Pipelines. While there is a concept of pipeline warnings, this one does not get added. This is actually worse, because user might not have noticed them at all. It's just such an unpleasing experience right now.

I'm not sure if this is something that needs to be fixed in Azure Pipelines or msbuild/dotnet.exe, or the analyzers itself - but the current experience when integrating with Azure DevOps/Pipelines is less than ideal. Is there anything you can do on your end?

For reference, I tried addressing this with the Azure Pipelines team as well:
https://github.com/microsoft/azure-pipelines-tasks/issues/9957
https://developercommunity.visualstudio.com/content/problem/616986/pipelines-code-analysis-analyzers-warningserrors-d.html

**Comment by gewarren** [comment]
@NenoLoje Thanks for following up. Indeed Developer Community is a better place to track this issue as it seems to be an Azure Pipelines problem. I'm closing this issue now in favor of your Developer Community problem report.
