### ISSUE TITLE
Numbering table rows

### ISSUE THREAD

**Issue by hn0598** [MicrosoftDocs/visualstudio-docs#3519]
I was populating the table with rows and had to delete some of the rows. The row numbering now doesnt seem to start with 1 and instead starts with a much higher number. How do i get the row number to start again from 1. It seems locked when i try to change it manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d19e1d-1448-e5b3-6580-9b11042e03ab
* Version Independent ID: 549472fa-f3be-53bc-cf9f-170c1183c834
* Content: [Create a database file and use table designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2019#feedback)
* Content Source: [docs/data-tools/create-a-sql-database-by-using-a-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-sql-database-by-using-a-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by hn0598** [comment]
<img width="270" alt="table" src="https://user-images.githubusercontent.com/52120658/59972143-ceb52600-953e-11e9-9aec-aebab54cd047.png">

**Comment by hn0598** [comment]
Anyone knows how I can get the numbering restarted with 1?

**Comment by hn0598** [comment]
I am using the table designer in Visual Studio 2017

**Comment by nschonni** [comment]
Not really related to the document, but I think you're looking for https://stackoverflow.com/questions/21824478/reset-identity-seed-after-deleting-records-in-sql-server

**Comment by hn0598** [comment]
Thanks!

**Comment by TerryGLee** [comment]
@nschonni Thanks for your response to @hn0598 regarding this support request. 
@hn0598 As an FYI, here are a few options for asking questions, too:​  
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
