### ISSUE TITLE
Report a Problem doc does not show the menu location of "Report a Problem" in the IDE

### ISSUE THREAD

**Issue by brendanzagaeski** [MicrosoftDocs/visualstudio-docs#352]
A commit a little while ago (https://github.com/MicrosoftDocs/visualstudio-docs/commit/47d761e9aeb3cfe0b703240371ea43efccc114d6) removed the "Open the Report a Problem tool" section from _[How to report a problem with Visual Studio 2017](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017)_. That section explained how to open **Report a Problem** from the IDE under **Help &#124; Send Feedback &#124; Report a Problem**. It would probably be helpful to add the menu location back into the document. (The location is mentioned on <https://docs.microsoft.com/visualstudio/ide/talk-to-us>, but I suspect users won't always be landing on that page first on their way to the Report a Problem page.)

Another issue that adds to the potential user confusion is that the current document says to "Sign in to Visual Studio" and then shows a screenshot that looks more like a web browser than Visual Studio. Based on that screenshot alone, it almost looks like users are supposed to navigate to <https://developercommunity.visualstudio.com/spaces/8/index.html> in a web browser and sign in there. The first places I would think of to "Sign in to Visual Studio" in the IDE are **File &#124; Account Settings** or **Help &#124; Register Product**. So on a first glance at this document if I hadn't ever used Report a Problem before, I wouldn't necessarily guess that I was supposed to be looking for a menu command in the IDE.

Thanks!

**Comment by gewarren** [comment]
@brendanzagaeski thanks for this thoughtful feedback. @TerryGLee can you take a look?

**Comment by TerryGLee** [comment]
I'll take a look at this and see what I can do to improve the experience. Thanks, @brendanzagaeski

**Comment by TerryGLee** [comment]
We should have this revised and published by Weds, FYI.

**Comment by TerryGLee** [comment]
Apologies; this fell off the radar. I'll report back when we've updated the page.

**Comment by TerryGLee** [comment]
@brendanzagaeski We have a PR in the queue that updates the procedure and resolves the issue that you identified: https://github.com/MicrosoftDocs/visualstudio-docs/pull/506. That PR should be live by the end of today. Thanks again for your excellent suggestion!
