### ISSUE TITLE
Error when running build with storage-opts set

### ISSUE THREAD

**Issue by schreibubi** [MicrosoftDocs/visualstudio-docs#3523]
Hi,

when I change the storage-opts of the docker daemon like specified in the instructions, I get the following error during the build:
hcsshim::PrepareLayer failed in Win32: The parameter is incorrect. (0x57) path=C:\ProgramData\Docker\windowsfilter\57da5c77f4290bce34c408cf013675985afdfd3ad2b9b5c578b2b93521c96559

This bug seems to have been introduced in Windows 1903 (see https://github.com/moby/moby/issues/36831), is there a workaround available for this?

Thanks,

Joerg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@schreibubi Thanks for your feedback; we appreciate it. We'll take a look at the page to make sure that there isn't something here that we need to address in the documentation (@heaths FYI). 

Meanwhile, for immediate assistance, please consider the following options:

* To make sure that the error message that you are receiving is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. 

* For installation-related issues, we also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ You might also consider using your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio) about this specific issue.

**Comment by heaths** [comment]
You may be able to ignore setting the storage limits since the default is now supposed to be 127GB in newer versions of Docker; however, please monitor their bug you referenced for more information about workarounds and status.
