### ISSUE TITLE
 Windows User Experience Interaction Guidelines link is broken

### ISSUE THREAD

**Issue by Jalalx** [MicrosoftDocs/visualstudio-docs#3524]
Link to the Windows User Experience Interaction Guidelines seems to be broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdc3bf85-14ed-5cd1-608a-064975587367
* Version Independent ID: adc0a5fb-1b6b-5ed7-1a56-e903f5eeb3be
* Content: [Visual Studio User Experience Guidelines - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/visual-studio-user-experience-guidelines?view=vs-2019#feedback)
* Content Source: [docs/extensibility/ux-guidelines/visual-studio-user-experience-guidelines.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/visual-studio-user-experience-guidelines.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by gregvanl** [comment]
@Jalalx Seems to be working now. Can you retry?

**Comment by Jalalx** [comment]
Sorry, I shouldn't have used the word _"broken"_. I meant it's linked to a page that is generally about desktop application development and the subject is too broad for _"Windows User Experience Interaction Guidelines"_. It seems a bit misleading to me. I was expecting content about UX Guidelines for Windows developers or something like that.
