### ISSUE TITLE
Duplicated steps

### ISSUE THREAD

**Issue by jcondina** [MicrosoftDocs/visualstudio-docs#3528]
Under "Run the application", steps 1 and 2 are the same

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db7f9ca8-40ce-6b6d-15df-bbb3b6829430
* Version Independent ID: 3dd10fed-b3d3-269c-623e-00031a81ed83
* Content: [Quickstart: use Visual Studio to create a Python web app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-python?view=vs-2019)
* Content Source: [docs/ide/quickstart-python.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-python.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
@jcondina Thanks for opening an issue. I'll get the duplicate step removed.

**Comment by JoshuaPartlow** [comment]
Duplicate removed with [9eced2](https://github.com/MicrosoftDocs/visualstudio-docs-pr/commit/9eced246fb945b1047c6c502f9a9d4a866dd3683)
