### ISSUE TITLE
Can't see Analyze Code Coverage in vs2019 professional

### ISSUE THREAD

**Issue by Irisbingjie** [MicrosoftDocs/visualstudio-docs#3529]
In the Unit Test, I can't see Analyze Code Coverage on the Test menu. 
My vs version is 2019 pro.
how can i do next?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d41fc7-bc52-8fe3-6b25-c1b2c3f89eb1
* Version Independent ID: 9d141754-5f8f-d330-0974-75cbcf45a011
* Content: [Troubleshooting Code Coverage - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/troubleshooting-code-coverage?view=vs-2019#feedback)
* Content Source: [docs/test/troubleshooting-code-coverage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/troubleshooting-code-coverage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by nschonni** [comment]
https://docs.microsoft.com/en-us/visualstudio/test/troubleshooting-code-coverage?view=vs-2019#do-you-have-the-right-edition-of-visual-studio

> Do you have the right edition of Visual Studio?

> You need Visual Studio Enterprise.

**Comment by WilliamAntonRohm** [comment]
@Irisbingjie Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by TerryGLee** [comment]
(see also #[3514](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3514))
