### ISSUE TITLE
How to list multiple values for applicable_kinds required_modifiers

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#353]
When reading the docs at https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#naming-conventions , I do not see any example or mention of how to specify multiple `applicable_kinds` or `required_modifiers` when defining a symbol. I am going to try and see if it works with `;`. But could the docs be updated to describe how to form a list for this?

Thanks.

**Comment by gewarren** [comment]
@binki thanks I will take a look.

**Comment by gewarren** [comment]
@binki I found an example file on GitHub that uses a comma to separate multiple values:

dotnet_naming_symbols.method_and_property_symbols.applicable_kinds = method,property

I will try this out and update the documentation to clarify. Thanks for your help in making the docs better!

**Comment by binki** [comment]
I’m pretty sure the actual list separator is `;`. I have tested and verified that it works. And even though `.editorconfig` and Python’s ConfigParser document `;` as a comment-starting character, it seems to *not* start a comment if it is in the middle of a value (much like how `#` is not a comment character in POSIX `sh` when it is in the middle of a parameter, e.g., `$ echo hi#friend` → `hi#friend`).

So if the docs could just specify `;` with no spaces on either side and show an example of it, that’d be great!

**Comment by kuhlenh** [comment]
Hi @binki -- the list has to be comma-separated. I am unable to reproduce the bug you are seeing by having a semi-colon-separated list. Can you confirm the following:

- after editing the EditorConfig file to have a comma-separated list, you closed all open files and reopened them
- your naming conventions are ordered with the most specific rule first, followed by the least specific (naming conventions do *not* cascade, the first applicable rule is applied)
- your current version of VS

**Comment by binki** [comment]
OK, I verified that `applicable_kinds` ignores anything after the first `;` and that it works with `,`. I wasn’t exhaustive enough in my earlier tests, I think I was only verifying the first thing I put in my list worked or something. This also applies to `applicable_accessibilities`.

I’m using vs-15.4.5 and I think I am seeing the same behavior as you, @kuhlenh.

I see that the docs at https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions now state that the values should be separated by comma.

Thanks for investigating this and updating the docs, and sorry for my false report about semi-colons!
