### ISSUE TITLE
These templates don't appear in VS Mac 

### ISSUE THREAD

**Issue by ChrisAllisonMalta** [MicrosoftDocs/visualstudio-docs#3530]
I upgraded to version 8 and I lost this ability. Currently running v8.1.1 (build 27) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4caaf0cc-3cea-375a-1160-6540db5557f1
* Version Independent ID: cfd2fe36-1325-9ff0-bc18-af563bb920e4
* Content: [Introduction to Azure Functions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions?view=vsmac-2019#available-function-templates)
* Content Source: [mac/azure-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/azure-functions.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by ChrisAllisonMalta** [comment]
The dropdown when you right click on Add doesn't include "Add Function"

**Comment by WilliamAntonRohm** [comment]
@ChrisAllisonMalta  Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
