### ISSUE TITLE
Quick update - who can buy VS Cloud subscriptions

### ISSUE THREAD

**Issue by chcomley** [MicrosoftDocs/visualstudio-docs#3538]
FROM
Who can buy Visual Studio cloud subscriptions?
Anyone with owner and contributor access to the Azure subscription can purchase cloud subscriptions.
TO
Who can buy Visual Studio cloud subscriptions?
Anyone with owner, service admin, or co-admin access to the Azure subscription can purchase cloud subscriptions.
Thanks!

"owner" should link to: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Frole-based-access-control%2Fbuilt-in-roles%23owner&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Ca0454e45ae724204809b08d6fb17d211%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972477053797778&sdata=6um8YJZyJeQkc8oFynNpAWdNaq6qUIrgaLyExS8dUEI%3D&reserved=0 

(resolves to https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#owner}

"service admin" should link to: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbilling%2Fbilling-add-change-azure-subscription-administrator%23change-the-service-administrator-for-an-azure-subscription&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Ca0454e45ae724204809b08d6fb17d211%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972477053807768&sdata=RDTzsoUGvzERs6aCoDs5UBwpnnkxrVEuUzLymj1emd0%3D&reserved=0

(resolves to 
https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator#change-the-service-administrator-for-an-azure-subscription)

"co-admin" should link to: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbilling%2Fbilling-add-change-azure-subscription-administrator%23add-or-change-co-administrator&data=02%7C01%7CChrystal.Comley%40microsoft.com%7Ca0454e45ae724204809b08d6fb17d211%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636972477053807768&sdata=LWNeZFGbKq4wMlAbrHthzM927duoUUgtfAWOqrO6EkI%3D&reserved=0

(resolves to https://docs.microsoft.com/en-us/azure/billing/billing-add-change-azure-subscription-administrator#add-or-change-co-administrator)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bdcfd-bb8a-a0c5-8a57-fd713889e849
* Version Independent ID: 1fe48f30-7069-d58f-5207-07b58b01d1fa
* Content: [How to purchase Visual Studio cloud subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-overview#who-can-buy-visual-studio-cloud-subscriptions)
* Content Source: [subscriptions/vscloud-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-overview.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by evanwindom** [comment]
PR #4930 submitted.

**Comment by TerryGLee** [comment]
@chcomley I'll close this now as we have a PR in play that should be published by noon Monday 7/1/2019.
