### ISSUE TITLE
Is this current

### ISSUE THREAD

**Issue by davidekarasek** [MicrosoftDocs/visualstudio-docs#3539]
Is this current to June, 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a644716-10c3-cc90-eeab-495c265e5728
* Version Independent ID: c356a0d8-1d24-2ab7-18de-b9b3088fd4d9
* Content: [Create a Vue.js app using Node.js - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/create-application-with-vuejs?view=vs-2019#feedback)
* Content Source: [docs/javascript/create-application-with-vuejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/create-application-with-vuejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by wojcikp** [comment]
Yes this is still valid. I literally created a project today and using it as a base for a prototype. I did not use TypeScript as I have had problems with TypeScript in Visual Studio 2017/2019 before (it would work for weeks then randomly I would have issues with TypeScript not working, probably package compatibility issues)

**Comment by Mikejo5000** [comment]
@davidekarasek David, was there something you saw in the article that made you think it is out of date?

**Comment by Mikejo5000** [comment]
Need more info
