### ISSUE TITLE
Where is VSTest.console.exe located?

### ISSUE THREAD

**Issue by mehagar** [MicrosoftDocs/visualstudio-docs#3541]
There is no mention of where to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27af73d-196c-4653-aa07-acf7e8b425e3
* Version Independent ID: b8957d80-ffa0-1c42-d3f0-6e4d00bf7a1e
* Content: [VSTest.Console.exe command-line options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019#feedback)
* Content Source: [docs/test/vstest-console-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/vstest-console-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
We need to add the following location info to the doc:

%Program Files(x86)%\Microsoft Visual Studio\<version>\<edition>\common7\ide\CommonExtensions\microsoft\TestWindow

**Comment by mehagar** [comment]
Based on [this comment](https://github.com/microsoft/vstest/issues/2077#issuecomment-506635370) it should be from a different location.

**Comment by LirazShay** [comment]
Is it applied also for running visual studio load test?
In the previous version we used mstest to run the load test but it doesn't work with on premise (test controller) in 2019, we don't know what is the problem.

**Comment by nzain** [comment]
For VS 2017 Professional, I found `vstest.console.exe` under

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\TestPlatform`

Note the difference to the comment from @gewarren : `Extensions\` vs `TestExtensions\`.

**Comment by Mikejo5000** [comment]
Updating doc. Referencing Developer Command Prompt, and file location. Looks like there are several valid locations.

**Comment by Filip01011010** [comment]
This path in DOC still seems invalid

%Program Files(x86)%\Microsoft Visual Studio\<version>\<edition>\common7\ide\CommonExtensions\<Platform | Microsoft>

It should be more like:

%Program Files(x86)%\Microsoft Visual Studio\<version>\<edition>\common7\ide\<Extensions | CommonExtensions>\<TestPlatform | Platform | Microsoft>
