### ISSUE TITLE
HTTPS connections

### ISSUE THREAD

**Issue by simonziegler** [MicrosoftDocs/visualstudio-docs#3542]
Once I have an ASP.NET app both working with Azure Dev Spaces and deploying to AKS with Azure Devops Pipelines, how do I enforce an HTTPS connection rather than HTTP on port 80? Many thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-kubernetes-tools?view=vs-2019#feedback)
* Content Source: [docs/containers/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-kubernetes-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
I'm not sure the suggested scenario makes sense - why not use port 443 for HTTPS connections.  Typically, port 80 is used for HTTP and 443 for HTTPS connections.  @simonziegler can you clarify?

**Comment by ghogen** [comment]
Closing - because the docs already use HTTPS in most scenarios, but on port 443 which is how the Dockerfile is set up.  I don't think it makes sense to use port 80 instead of port 443 for HTTPS.
