### ISSUE TITLE
Instructions to disable warning by increasing stack size allowed are not correct

### ISSUE THREAD

**Issue by jhudsoncedaron** [MicrosoftDocs/visualstudio-docs#3544]
Adding add /analyze:stacksize262144 to all configurations still displays warning in Visual Studio IDE even after reloading project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e580bcb-77cd-2ad8-8ed1-9e4b156276ab
* Version Independent ID: 62f15705-03cb-cb29-ea29-fa38a5d79f4e
* Content: [C6262 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c6262?view=vs-2019#feedback)
* Content Source: [docs/code-quality/c6262.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c6262.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by h3xp1017** [comment]
same issue

there is also inconsistency in msdn docs because /analyze article says that there should be a space between (https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=vs-2019)
>/analyze:stacksize number

while in warning article it suggests to use without space (https://docs.microsoft.com/en-us/visualstudio/code-quality/c6262?view=vs-2019)
>/analyze:stacksizenumber

anyway both is not working lold

**Comment by mikeblome** [comment]
@h3xp1017 thanks for the feedback. This sounds like a product issue so I'm going to close this documentation bug. The developer team has requested that you file an issue on [Visual Studio Dev Community](https://developercommunity.visualstudio.com/spaces/62/index.html) with a code example that shows the behavior. Thanks!

As for the space between /Analyze:xxxx option and the option’s value, it is optional and I will update the document. Agreed it is confusing.
