### ISSUE TITLE
Deploying generated Docker configuration outside Visual Studio

### ISSUE THREAD

**Issue by piotrek-k** [MicrosoftDocs/visualstudio-docs#3545]
I thought that one of the main advantages of Docker for developers is that one can create single container configuration that can be easily deployed, without changes, on any platform (Linux, Windows).

That's not exactly true for Docker tools on Visual Studio 2019. I've created an ASP.net project and Visual Studio automatically generated docker and docker-compose configuration. I can without any problems run it using Visual Studio 2019 (on Windows using linux container). Then, I've pushed my code to git repo and cloned it on other device (Linux).

When I run `docker-compose up` on that other device, I can see such error:
> Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.

After some investigation I found out, that it's because Visual Studio uses some additional config file (`\obj\Docker\docker-compose.vs.debug.g.yml`) that is platform dependent and is not included in git repo. It contains paths to folders that are relevant only on my Windows device.

Am I using it wrong? Is it OK, that docker configuration works in Visual Studio only? Is it a bug? Should I configure HTTPS endpoint by hand (I mean: modify automatically generated Docker configuration so it configure HTTPS at startup)? If so, what is the purpose of such generator if I need to, either way, write it myself?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76adc87-d3e4-d443-b1ae-d49d039d08ae
* Version Independent ID: 4c3938df-6bbe-0ef0-50a8-14b6f192deed
* Content: [Visual Studio Container Tools on Windows - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2019#feedback)
* Content Source: [docs/containers/overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Hi, you've entered this in a doc feedback repo, unfortunately we don't work with product feedback issues here, but the good news is that you can easily enter this in the appropriate product database here:  https://github.com/microsoft/dockertools/issues
