### ISSUE TITLE
Snippets reference does not apply to visual studio for mac

### ISSUE THREAD

**Issue by JssDWt** [MicrosoftDocs/visualstudio-docs#3548]
The link in the bottom (Visual Studio code snippets reference) refers to code snippets for Windows. (&lt;Codesnippet&gt;). On Visual studio for mac, it is &lt;CodeTemplate&gt;. This should refer to the &lt;CodeTemplate&gt; schema.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c165c6c-3afb-ec14-fc40-13c504aa2492
* Version Independent ID: eb03852b-8ccf-a6f7-b62d-a6912a97430d
* Content: [Code Snippets - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/snippets?view=vsmac-2019#feedback)
* Content Source: [mac/snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/snippets.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
The section on **keywords** was relevant to Visual Studio for Mac, however to avoid confusion with the rest of the page content, the link (and paragraph) has been removed from the page.
