### ISSUE TITLE
npm ERR! missing script: build'

### ISSUE THREAD

**Issue by PhilMchenry** [MicrosoftDocs/visualstudio-docs#3549]
Hi,
this was a interesting tutorial and has taken me sometime to get the React bit going.
Had to take things apart to get it working which is a good way to learn
I had issues getting Node.JS installed, had to set Enviroment PATH to point at local Node install location and fiddle with Typescript compiler.
I can take the above but my biggest sticking point was getting 
'npm run build
		npm ERR! missing script: build'
repeatedly, adding the following into Packages.json solved this issue
scripts": {
    "build": "webpack-cli app.tsx --config webpack-config.js"
  },
Did I miss something in the tutorial? And will this just replace the transpile step each time you build??
I am on VS2019 community.
Cheers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by KickassMgee** [comment]
Hello,

I also got this error and this is my first time using React or Node and wanted to get to grips with setting up a project.

Firstly, thank you for the solution to this issue, secondly, how did you know to do it? Do I need more experience or did I miss something? Because to me, the build command you listed as the solution does not make much sense.

**Comment by PhilMchenry** [comment]
Hi,
This was my first node/react app to, so I approached it like a .NET visual studio project and was trying to get a build going.
I don't think you missed anything, I spent several hours looking at links with this error in and also had a look at other react apps in visual studio code.
Not sure if visual studio code is possibly a better a IDE for Node/React, have read a thread suggesting Visual studio is too heavyweight and visual studio code more appropriate. Have been using visual studio code and had issues with the NPM to, mostly to do with read-only files but might be a better call to use.
Also be interesting to see what the feedback is from this article's author.
Cheers

**Comment by KickassMgee** [comment]
I was also debating using visual studio code but to the setup time involved
with VS, but i dont know how well it works with deployments and packages.

**Comment by kevingy** [comment]
I'm getting the same error on VS 2019 as well. Perhaps the original poster doesn't have VS 2019?

**Comment by Mikejo5000** [comment]
@PhilM Thanks for the feedback. Typically, the article has needed updates as packages get deprecated, and so forth. I'll take a look at it.

**Comment by PhilMchenry** [comment]
Thanks @Mikejo5000 . Be interested to know what the issue was. From a basic understanding it looks like when VS2019 is looking to start the Node JS part with Express, something is issuing a NPM build command in the output window, and NPM then expects a build entry in the packages.json file. 
![image](https://user-images.githubusercontent.com/51723896/61390623-0d769b80-a8b3-11e9-9af4-76af23ef1496.png)

**Comment by PhilMchenry** [comment]
Damn, didn't mean to close this....

**Comment by Mikejo5000** [comment]
On VS 2019, node.js v10.13.0, and using the npm package versions specified in the article:

The step to switch your default browser has changed in VS. But the main issue I had was that the template doesn't include the path to Node.exe (you can set this by right-clicking project in Solution Explorer, choosing Properties). Without the path set, I see a lot of TypeScript errors. When I set the path, the errors went away and the page loaded correctly.

**Comment by Mikejo5000** [comment]
@armanio123 Armando, is this a bug in the Blank Node.js Web Application template for JavaScript, or in Node.js tooling for VS? I'm sure that the path to Node.exe had been set in earlier versions of VS.

**Comment by Mikejo5000** [comment]
I updated to node v10.16.0, and now I get a repro on this issue. Your suggestion--adding the following to package.json--did fix the problem, and let me load the page without errors.
scripts": {
"build": "webpack-cli app.tsx --config webpack-config.js"
},
At first glance, it appears that the latest version of Node requires the build script.

**Comment by Mikejo5000** [comment]
By adding the script to package.json, as you mentioned you don't need to do the steps under "Transpile the JSX" (instead, you transpile on running the build script). I will edit this section so it says "Test the JSX", since it will be kind of handy to check for errors. Also, there are steps in there to add the dist folder to your project, which is also handy though not required.

**Comment by armanio123** [comment]
@Mikejo5000 since VS 2019 the Node.js templates started using `npm run build` script for building the project and `npm run clean` for cleaning. You can either customize the `build` script or add on the `njsproj` file the following code for replacing this behavior:

```xml
<Target Name="AfterClean">
  <Exec Condition="'$(EnableTypeScript)' == 'true'" Command="npm run clean" />
</Target>

<Target Name="AfterCompile">
  <Exec Condition="'$(EnableTypeScript)' == 'true'" Command="npm run build" />
</Target>
```

In my opinion, the solution @PhilMchenry propose of adding the command `webpack-cli app.tsx --config webpack-config.js` to the `build` script looks like the better approach that leverages this feature. I'll suggest to update the documentation to this.

**Comment by armanio123** [comment]
It's a little bit difficult to find if you don't know what you're looking for. The code is located on the file `Microsoft.NodejsToolsV2.targets`. Most likely you'll find it on a path similar to: `C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Microsoft\VisualStudio\v16.0\Node.js Tools\Microsoft.NodejsToolsV2.targets`.

That `targets` file gets imported into the project. If you unload and edit your project you'll see the import like: `<Import Project="$(VSToolsPath)\Node.js Tools\Microsoft.NodejsToolsV2.targets" />`.

**Comment by PhilMchenry** [comment]
Thanks @armanio123 and everyone else.
