### ISSUE TITLE
CA2213 - No example of solution

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#3550]
@feiandytan commented on [Fri Jun 28 2019](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/129)

This page doesn't have example of how to fix the violation.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7193fffc-ff49-d551-417e-6f004dd1e216
* Version Independent ID: 8370a61d-8d8a-bec4-b49d-e5cae67a0d86
* Content: [CA2213:应释放可释放的字段 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2213-disposable-fields-should-be-disposed.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/code-quality/ca2213-disposable-fields-should-be-disposed.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by CeciAc** [comment]
Hi team, 
I'm moving this here since the contributor is asking for aditional examples
best regards

**Comment by mattmunich** [comment]
See `See also` above:

https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose

**Comment by gewarren** [comment]
@mattmunich Thank you. @feiandytan Does the topic linked from the See Also section give you the examples you need?

**Comment by feiandytan** [comment]
Hi @gewarren, the See Also section does not contain example for the ca2213.
