### ISSUE TITLE
'Info' could not be found

### ISSUE THREAD

**Issue by hwiguna** [MicrosoftDocs/visualstudio-docs#3554]
In regards to 'Info' in AddSwaggerGen() in startup.cs, as of June 29, 2019, I had to change 'Info' to 'OpenApiInfo', add Microsoft.OpenApi reference, and add 'using Microsoft.OpenApi.Models'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788828c4-74bc-1bcb-7480-38e490358f18
* Version Independent ID: d62da0a4-9a26-a89d-ff8f-d3314cf35724
* Content: [Step 4: Exposing a web API From Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-04?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
Terry -- there doesn't appear to be an "ardalis" in our GitHub.

**Comment by ardalis** [comment]
I'm here, but I'm no longer under contract to develop/maintain some of these docs, so while I might answer the odd question I'm probably not making major updates.

**Comment by ghogen** [comment]
Thanks for contacting us about this topic.

Investigating this, I find that Info is not meant to be OpenApiInfo - it's meant to be Swashbuckle.AspNetCore.Swagger - the topic mentions that you need to add a using statement to the topic for this.  So, I think we can close this issue.
