### ISSUE TITLE
Saying I can't add a floating point number.

### ISSUE THREAD

**Issue by All-About-Code** [MicrosoftDocs/visualstudio-docs#3555]
# I can't add a floating point number.

 #### When I do I get this error (from all the compilers I have):
System.FormatException: Input string was not in a correct format.

**Comment by WilliamAntonRohm** [comment]
@All-About-Code Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
