### ISSUE TITLE
Errors CS0103 and CS0246

### ISSUE THREAD

**Issue by compprogrammer** [MicrosoftDocs/visualstudio-docs#3556]
After coping code to create DB to Program.cs  these errors came up.

{
    var host = CreateWebHostBuilder(args).Build();

    using (var scope = host.Services.CreateScope())
    {
        var services = scope.ServiceProvider;

        try
        {
            var context = services.GetRequiredService&lt;SchoolContext&gt;();
            context.Database.EnsureCreated();
        }
        catch (Exception ex)
        {
            var logger = services.GetRequiredService&lt;ILogger&lt;Program&gt;&gt;();
            logger.LogError(ex, "An error occurred creating the DB.");
        }
    }

    host.Run();
}

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'CreateWebHostBuilder' does not exist in the current context	WhereIsAllMyStuff	C:\Users\compp\source\repos\WhereIsAllMyStuff\Program.cs	17	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SchoolContext' could not be found (are you missing a using directive or an assembly reference?)	WhereIsAllMyStuff	C:\Users\compp\source\repos\WhereIsAllMyStuff\Program.cs	25	Active

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f156aaa-839a-b9bb-5912-b3a537dfdb36
* Version Independent ID: 51888076-400e-0a51-8ae4-6fe745829436
* Content: [Step 3: Working with Data in Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-03?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by mar1asm** [comment]
I'm dealing with the same problem, Have you figured out how to solve it?

**Comment by compprogrammer** [comment]
No joy on a solution. I’ll get back to it in a couple of days with fresh eyes.

REB

**Comment by d-pipper** [comment]
I was able to fix this by adding the namespace extension to the get required service call. Like this `var context = services.GetRequiredService<Models.AppDbContext>();`

**Comment by mar1asm** [comment]
I still have this error: Error	CS0103	The name 'CreateWebHostBuilder' does not exist in the current context

**Comment by rgonv** [comment]
@mar1asm  Your issue may be that when pasting the Main() method code, you overwrote the CreateWebHostBuilder Method too.  
The complete Program class should look like this:

` public class Program
    {
        public static void Main(string[] args)
        {
            var host = CreateWebHostBuilder(args).Build();

            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;

                try
                {
                    var context = services.GetRequiredService<AppDbContext>();
                    context.Database.EnsureCreated();
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService<ILogger<Program>>();
                    logger.LogError(ex, "An error occurred creating the DB.");
                }
            }

            host.Run();
        }

        public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }`

**Comment by ghogen** [comment]
Thanks - we've now updated the topic accordingly.
