### ISSUE TITLE
Please Change One Feature on Windows Forms - Naming a Button or Other Object

### ISSUE THREAD

**Issue by toddalbers** [MicrosoftDocs/visualstudio-docs#3558]
Visual Studio Forms Team - Please consider adding this feature in Visual Studio.  My son wants to learn C# and I am using Windows Forms to teach him the basics by putting code in simple buttons and text fields for output.  We will advance from there.  But, this one suggestion might help a lot for new learners.  If this is the wrong location or forum for this request, my apologies.  Just let me know where to re-post it.  Here it is using a simple example.

Please do the following to understand what I am talking about.

1) Create a Windows Form and leave the name as Form1.cs and Form1.Designer.cs
2) Now Add a Button to the Form.  The button will default to a name and text of "button1"
3) Now double click that button.  (A natural action that a newbie might expect to bring up the properties of the button.)
4) After double clicking the button, now simply change the name of the button from button1 to something else.  Maybe "btnCloseWindow" or something like that.  Just simply change the name of the button.  Real simple.
...
... wait for it ...
...
5) No seriously, simply change the name of the button.

See the problem?

Please consider putting in an option box under the following location in Visual Studio
 \Tools\Options\Windows Forms Designer\

"Prompt for Renaming Objects when Added or Created"  (Checkbox)  [Default is check "ON"]

Resulting Behavior from Checking that "ON" would be the following:

If you check that option "ON", then whenever a developer adds a button (or any other object) to a form, a dialogue box pops up prompting them to rename the button right away before doing anything else. 

Whenever you add a button to a form, the very first thing you do is rename it anyway.  You are basically almost forced to do this right away anyway because of the "convenient" auto generation of code when you double click the button in design mode.  And I don't know of anyone that likes to just stick with the button1, button2, button3 naming convention for their buttons.

Double clicking a newly created button is kind of a natural action for a newbie or even someone that just doesn't work on windows forms often.  It seems like a natural action that might bring up the properties of the button.  But, it doesn't do that.  It auto generates code for the button in the code behind Form1.cs and in Form1.Designers.cs.  Convenient but confusing if you don't work in Windows Forms regularly and irritating if you haven't renamed the button yet.

This one little feature would be really helpful for people trying to learn how to code using Windows forms.  I suggest considering little things like this as I think they will really help out newbies (especially) before they give up and go to a different development language\environment.  It also is just a nice convenience for experienced pros in my opinion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec42e9c9-1127-3815-a2cc-14efbbf78926
* Version Independent ID: 9f04d176-173f-43a2-cb9c-a6d35f2cf516
* Content: [Step 6: Name your button controls - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-6-name-your-button-controls?view=vs-2019)
* Content Source: [docs/ide/step-6-name-your-button-controls.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-6-name-your-button-controls.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@toddalbers It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.
