### ISSUE TITLE
image location should be updated to use mcr.microsoft.com

### ISSUE THREAD

**Issue by mozts2005** [MicrosoftDocs/visualstudio-docs#3562]
The example on this page, the current base image path is to docker hub, not the new Microsoft container registry  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2019)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by heaths** [comment]
I will update the sample to showcase mcr.microsoft.com, but the base image is representation of being a sample. It will change as Windows releases new base images (depending on your host), so users reading this will need to update accordingly. I will be adding a note to that effect.
