### ISSUE TITLE
explanation for icons?

### ISSUE THREAD

**Issue by aardvarkkrill** [MicrosoftDocs/visualstudio-docs#3563]
Solution explorer has lots of lovely icons.  I'm sure they're really useful.  But why aren't they documented here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by jimenezfer** [comment]
I literally was looking to see what the icons were about. Lacks information.

**Comment by TerryGLee** [comment]
@aardvarkkrill Thanks for your feedback; we appreciate it. To address your feedback, we added a Note to the [Solutions and projects in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019) page that includes a link that lists some of the icons that you're looking for, as follows:

"To view a list of some of the icons that appear in Solution Explorer, see the [Class View and Object Browser icons](class-view-and-object-browser-icons.md) page."

We realize that we need to do some more work on listing _all_ the icons, and so I personally have created an internal action item to do just that. However, the refreshed, completed list won't appear on the [Solutions and projects in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019) page, but on another page that we'll link to from the Solutions & Projects page, similarly as we've just done with the link to the [Class View and Object Browser icons](class-view-and-object-browser-icons.md) page. 

Meanwhile, we'll close this issue, with our thanks to you for helping us to improve the documentation!
