### ISSUE TITLE
How does the "Dash" decorator work?

### ISSUE THREAD

**Issue by johan-buret** [MicrosoftDocs/visualstudio-docs#3565]
This page doesn't describe how to make the double dash appear in the Person Shape.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb79e97f-6d8a-0f06-96db-db4fc1e135ae
* Version Independent ID: 097107da-2105-400d-3ad3-1f47c1422209
* Content: [Getting Started with Domain-Specific Languages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/getting-started-with-domain-specific-languages?view=vs-2019#feedback)
* Content Source: [docs/modeling/getting-started-with-domain-specific-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/getting-started-with-domain-specific-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mgoertz-msft** [comment]
The topic on customizing shapes is here: https://docs.microsoft.com/en-us/visualstudio/modeling/defining-shapes-and-connectors?view=vs-2019
