### ISSUE TITLE
Registry key

### ISSUE THREAD

**Issue by KrOstir** [MicrosoftDocs/visualstudio-docs#3568]
On Windows 10 the 64-bit Python interpreters are listed in HKEY_LOCAL_MACHINE\SOFTWARE\Python and not in HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Python.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 563f476d-a91b-58c7-9e32-b238756cc97d
* Version Independent ID: 0a0e9cac-a8dc-47a1-14e1-1dacc3441613
* Content: [Manage Python environments and interpreters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/managing-python-environments-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/managing-python-environments-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@JoshuaPartlow -- Joshua, please confirm the new path for 64-bit Python interpreters is `HKEY_LOCAL_MACHINE\SOFTWARE\Python`.  If it is, I'll create a PR to update this article.

**Comment by WilliamAntonRohm** [comment]
@JoshuaPartlow -- please advise on this issue at your convenience.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
