### ISSUE TITLE
Are paths updated for VS2019?

### ISSUE THREAD

**Issue by loicmorvan-ansys** [MicrosoftDocs/visualstudio-docs#3571]
I'm viewing the version 2019 of this page but the paths still contains "2017" inside. Can you replace "2017" by "2019"?
I checked that these new paths work as expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8177d9b-f8d7-419e-d81d-ce25a44b084f
* Version Independent ID: 43a69770-1eab-06e1-868c-3d8f1c32716d
* Content: [Generating Files with the TextTransform Utility - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/generating-files-with-the-texttransform-utility?view=vs-2019)
* Content Source: [docs/modeling/generating-files-with-the-texttransform-utility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/generating-files-with-the-texttransform-utility.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
I updated the paths accordingly, and the updated documentation should be live by tomorrow.
