### ISSUE TITLE
How do I see the problems that I reported?

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/visualstudio-docs#3572]
I would think that this would be pretty straight forward, but I don't see any way to do this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by seaniyer** [comment]
@Ma-XX-oN 

In Visual Studio when you open Feedback tool (by selecting 'report a problem') the initial view is 'Items I follow'.  This view contains items either you reported or follow.  Although we don't have a view that is exclusively items reported, that is the closest available at this time.

On the web 'Items I follow' is available under Sign in control located at the very top right at https://developercommunity.visualstudio.com

I hope this helps.
Sean
VS Feedback team
