### ISSUE TITLE
Gives a warning when using the ++ operator and not assigning the result

### ISSUE THREAD

**Issue by bpeikes** [MicrosoftDocs/visualstudio-docs#3574]
Example:
auto iterStart = function.that_returns_an_iterator();

for(auto it = iterStart; it != collection.end(); it++) &lt;- warning about it++
{
}

for(auto it = iterStart; it != collection.end(); it = it++) &lt;- warning is gone
{
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ca2429e-66c0-466b-7dd0-cfc494f10528
* Version Independent ID: 5cfccdb3-7537-de8e-618d-673d3ce4aa74
* Content: [C26444 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26444?view=vs-2019#feedback)
* Content Source: [docs/code-quality/c26444.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26444.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by WilliamAntonRohm** [comment]
@bpeikes Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
