### ISSUE TITLE
Doc not informative enough

### ISSUE THREAD

**Issue by Barina** [MicrosoftDocs/visualstudio-docs#3590]
"Delete the existing class files" means to delete the auto generated "ProjectNamePackage" class as well?
Can you be more specific please?

Edit:
I was referring to [this document](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-quickinfo-tooltips?view=vs-2019#to-create-a-mef-project).

**Comment by msebolt** [comment]
@Barina Thank you for the feedback!  Could you please specify the doc in question?

**Comment by msebolt** [comment]
Similar to issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/3592.

**Comment by acangialosi** [comment]
Reassign to Dante Gange.
