### ISSUE TITLE
Is/Will there be an "integrated" terminal in the IDE

### ISSUE THREAD

**Issue by EdSF** [MicrosoftDocs/visualstudio-docs#3591]
Just curious about the above - kind of like how VSCode  where you can choose to work with Git via the IDE or integrated terminal. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1ebf72-a4ef-3b5f-99d5-95a0a83973d9
* Version Independent ID: b839d4b7-e42d-758c-2762-8fc7a93551e9
* Content: [Working with Git - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/working-with-git?view=vsmac-2019#feedback)
* Content Source: [mac/working-with-git.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/working-with-git.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by msebolt** [comment]
@EdSF Thank you for the question.

For Visual Studio on Windows this is the [Developer Command Prompt](https://docs.microsoft.com/en-us/dotnet/framework/tools/developer-command-prompt-for-vs).   

For Mac support, either [add the idea](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) to our forums or use the [VSCode integrated terminal](https://code.visualstudio.com/docs/editor/integrated-terminal) as you suggest.​
