### ISSUE TITLE
Doesn't work at all.

### ISSUE THREAD

**Issue by Barina** [MicrosoftDocs/visualstudio-docs#3592]
Attaching the full source could've  helped...................................................

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28863dd2-b54a-4733-ebc7-57d0235bfc95
* Version Independent ID: b9062a5a-ac9a-d8c5-00d9-204a6bd98d30
* Content: [Walkthrough: Displaying QuickInfo Tooltips - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-quickinfo-tooltips?view=vs-2019)
* Content Source: [docs/extensibility/walkthrough-displaying-quickinfo-tooltips.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-quickinfo-tooltips.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by hyryel** [comment]
Hello all,

I've managed to make it work.
DO NOT do the step : 

 - Add an Editor Classifier item template to the project. For more information, see Create an extension with an editor item template.
 - DO NOT delete the *package.cs Class, as mentionned in the third point. This file is critical to make the package workable.

Create a new class, name it whatever you want.
For this Walkthrough to work, First, implement the QuickInfoSourceProvider,
then the QuickInfoSource.
Then the QuickInfoControllerProvider,
Then the QuickInfoController.

This way, you will not have compillation error nor intellisense red waves under your code.

I attache the complete file, just create an empty VSIX project and add this file. (perhaps check namespaces :p)

https://pastebin.com/iK6GZLVh

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
