### ISSUE TITLE
I can't create a project in vscode

### ISSUE THREAD

**Issue by Densfi** [MicrosoftDocs/visualstudio-docs#3595]
![Untitled](https://user-images.githubusercontent.com/44140486/60807393-3b126500-a18e-11e9-8418-6f33e6e27a5a.png)
Alert: I'm a newbie.
The whole Internet says it's very simple. Just File > New > Project. Or there is a big button right on start page. But I don't have any of these buttons, I don't even have start page, only 'Welcome' page. And when I click on 'File' there is only 'New File' and 'New window'. So, I don't know what to do, please help.
![Untitled22](https://user-images.githubusercontent.com/44140486/60807448-6d23c700-a18e-11e9-8dc1-321bd501f61e.png)

**Comment by nschonni** [comment]
Visual Studio (the documentation in this repo, and a paid product), and Visual Studio Code (docs over https://code.visualstudio.com/docs and a free product) are not the same thing

**Comment by msebolt** [comment]
@Densfi Thank you for submitting your issue.  

As per @nschonni response, VS Code does not support full IDE development.  

You can either request the feature [here](https://github.com/Microsoft/vscode/issues) or check out the [Visual Studio downloads](https://visualstudio.microsoft.com/downloads/) to get started.
