### ISSUE TITLE
Visual Studio 2019 update 16.1.5 broke BIDS\SSIS project types

### ISSUE THREAD

**Issue by JekelEars** [MicrosoftDocs/visualstudio-docs#3598]
I have read the other threads on this.  SSIS and the dtproj were working fine in the Visual Studio 2019 release *before* 16.1.5 However, now they are broken.  I have installed the new version of the project templates\visx from the Visual Studio market place.  I have also installed the older 2017 SSDT toolkit.  Niether are working.  I can not open or create a SSIS project, *.dtproj with Visual Studio 2019 version 16.1.5... as of about July 2nd.

I tried running a repair operation on the new market place installer for the VS2019 SSIS extensions and it errored out, I have included the log file.

[Microsoft.DataTools.IntegrationServices_20190708131633.log](https://github.com/MicrosoftDocs/visualstudio-docs/files/3369533/Microsoft.DataTools.IntegrationServices_20190708131633.log)

**Comment by msebolt** [comment]
@JekelEars We're sorry to hear you're experiencing a problem.  

Changes here are generally limited to documentation only.  Please try the **Report a problem** feature in the [Visual Studio forum](https://developercommunity.visualstudio.com/spaces/8/index.html) to get the best traction.

**Comment by JekelEars** [comment]
ok, I tried that and received the following error, so, there is no way for me to report the error.  Can I have a free license?  The client site I'm at really needed this to work!
![eRRORReportingProblem](https://user-images.githubusercontent.com/52672975/60911220-ade41480-a250-11e9-9b7e-fde1fc26b332.png)

**Comment by msebolt** [comment]
@JekelEars Please refer to https://developercommunity.visualstudio.com/content/problem/400935/ssis-project-will-not-open-in-vs-2019-preview.html.

**Comment by JekelEars** [comment]
Please read the thread in its entirety.  On July 5th, update 16.1.5 to VS 2019 BROKE the SSDT Visx, that WAS working from the market place.  THIS IS NEW! The visx and extensions and project types, .dtxs were working in the RELEASE VERSION of vs2019 that are less then release 16.1.5.  THIS IS A NEW PROBLEM WITH THE NEWEST VS2019 RELEASE. There is no fix, repair operation, or work around as of today, July 9th, 2019.

**Comment by JekelEars** [comment]
I am not using the 'preview' version of VS2019, its the released version.  All threads referenced in your link are as of April 2019 and not helpful.

**Comment by msebolt** [comment]
@JekelEars Please refer to https://developercommunity.visualstudio.com/content/problem/638893/visual-studio-2019-update-1615-broke-bidsssis-proj.html.

**Comment by JekelEars** [comment]
Fantastic msebolt.  I added the log file for some developer to review of a repair operation.

**Comment by sylus** [comment]
Wonder if this is my problem also ^_^

https://github.com/microsoft/dotnet-framework-docker/issues/311

**Comment by msebolt** [comment]
@JekelEars The forum has posted a response requesting further log information.  

Please update when you get the chance.

**Comment by JekelEars** [comment]
sylus - This has NOTHING to do with DOCKER!

**Comment by JekelEars** [comment]
What log? I don't see any request for information?  You got a repair operation log that failed.  The toolkit should not fail on a repair operation.  What do you want?

**Comment by msebolt** [comment]
@JekelEars There was a comment posted in the under the solution you posted in the forum link above:  

Please give the entire log folder which contains more detailed log files. The log folder is %TEMP%\SsdtisSetup by default.

**Comment by msebolt** [comment]
Closing due to inaction, please add the log file to the support issue as described above if there are further issues.
