### ISSUE TITLE
How to deploy to Azure via Visual studio

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/visualstudio-docs#3601]
Is there document on how to deploy the project to Azure, ideally via Visual studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-kubernetes-tools?view=vs-2019#feedback)
* Content Source: [docs/containers/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-kubernetes-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by msebolt** [comment]
@PingPongSet Have you tried [Visual Studio Tools for Kubernetes](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vs-tools-for-kubernetes)?

**Comment by PingPongSet** [comment]
I am using VS 2019.

I am looking for an example show how to create projects for Kubernetes Orchestration and deploy to AKS. I searched through all docs from MS, but I cannot find one.

**Comment by ghogen** [comment]
In VS 2017, there was a manual option to Publish to AKS.  That is not available in VS 2019.  It is still possible to deploy to Azure from within VS during the development cycle using Azure Dev Spaces, and for production work, using Azure Pipelines.  The work here is to add steps and instructions for those procedures.

**Comment by ghogen** [comment]
Closing this issue since the deploy functionality was removed in VS 2019 - the topic here provides links to both Azure Dev Spaces, which lets you deploy during the development/debug part of the application development cycle, and CI/CD docs which is the recommended way to publish/deploy to AKS for integrated services.
