### ISSUE TITLE
Add VB code example to this page

### ISSUE THREAD

**Issue by Nukepayload2** [MicrosoftDocs/visualstudio-docs#3602]
Page url: 
https://docs.microsoft.com/en-us/visualstudio/extensibility/xaml-designer-extensibility-migration

I'll send a pull request later.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe4d604b-9fc6-0c6e-df87-5d68a24b83f5
* Version Independent ID: 4fa85b87-55c7-a165-28f7-f8e1df73613a
* Content: [XAML Designer Extensibility Migration - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/xaml-designer-extensibility-migration?view=vs-2019#feedback)
* Content Source: [docs/extensibility/xaml-designer-extensibility-migration.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/xaml-designer-extensibility-migration.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @lutzroeder
* Microsoft Alias: **lutzr**

**Comment by Nukepayload2** [comment]
Please review and merge pull request #3603

**Comment by lutzroeder** [comment]
#please-close
