### ISSUE TITLE
Inconsistent guidance

### ISSUE THREAD

**Issue by Tu9a2** [MicrosoftDocs/visualstudio-docs#3609]
Prior to 'Save your layout options' the local cache path was referred to as 'C:\vsoffline'. However, from that specific section, it changes to C:\VSLayout. Should it be consistent to avoid any misunderstanding?

Also, the section 'Deploy from a network installation' is also incorrect. The setup file name should be 'vs_setup.exe', instead of 'vs_enterprise.exe'. The 2nd command for Administrators also misses a '' signal at the beginning (it should be \server...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019#deploy-from-a-network-installation)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by Tu9a2** [comment]
somehow this page cannot display the code properly. 2 backslash icon becomes only 1!?

**Comment by Tu9a2** [comment]
The 2nd command for Administrator should be '\\server...'

**Comment by TerryGLee** [comment]
@Tu9a2 Thanks for your feedback; we'll take a look at this and report back.

**Comment by TerryGLee** [comment]
@Tu9a2 We've got a PR staged that will fix the issues you identified in this issue; the revised page should go live tomorrow by noon. Thanks for helping us improve the documentation!
