### ISSUE TITLE
Missing documentation and samples for /deterministic and /pathmap MSBuild switch

### ISSUE THREAD

**Issue by martinsuchan** [MicrosoftDocs/visualstudio-docs#361]
MSBuild supports building deterministic build when the **/deterministic** switch is present.
Additionaly it supports hermetic builds (deterministic even when built in different folders) by using the **/pathmap** option.
**These arguments are not documented anywhere**
https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild

The only description of these arguments I was able to find is here:

Deterministic builds in Roslyn
http://blog.paranoidcoding.com/2016/04/05/deterministic-builds-in-roslyn.html

MSBuild support for the pathmap option
https://github.com/dotnet/roslyn/issues/5830

Add /deterministic switch to compiler, MSBuild and Workspaces
https://github.com/dotnet/roslyn/issues/5417

**Comment by gewarren** [comment]
@Mikejo5000 can you look at this one?

**Comment by Mikejo5000** [comment]
We will need a PM to review updates. Rayner is back in December.

**Comment by rainersigwald** [comment]
The `Deterministic` property was added in https://github.com/MicrosoftDocs/visualstudio-docs/pull/229.

We can easily add the `PathMap` property, but I don't know how to describe it, so I think that's pending on https://github.com/dotnet/docs/issues/1800--once a description for the command-line compiler argument is available we can use the same description for the property, since it basically just gets plumbed through.

**Comment by gewarren** [comment]
@rainersigwald It looks like /pathmap was documented last May. Here's the article:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/pathmap-compiler-option

"The -pathmap compiler option specifies how to map physical paths to source path names output by the compiler."

Could you or @Mikejo5000 add it to the [msbuild project properties article](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2017)?

**Comment by Mikejo5000** [comment]
@gewarren I can plan to add it.

**Comment by Mikejo5000** [comment]
Updating
