### ISSUE TITLE
Containernized ASP.NET Core apps not working when using Kubernetes Orchestrator

### ISSUE THREAD

**Issue by PingPongSet** [MicrosoftDocs/visualstudio-docs#3612]
I followed the steps on the link below:

https://docs.microsoft.com/en-gb/visualstudio/containers/tutorial-multicontainer?view=vs-2019

Instead of using Docker Compose, Kubertnes is selected for Container Orchestrator Support for each project. 

[![enter image description here][1]][1]
However, the project, WebFrontEnd, runs forever (the VS build progress bar is half way) and web app endpoint is not working when it is in debug mode with Azure Dev Spaces.

**Update**

I tried switching to Docker mode when debugging, and switching back to Azure Dev Spaces mode, WebFrontEnd launchs at the url below.

http://localhost:51927/

Should the url not contain "localhost"?

However, the text below is not displayed, which means there is an issue with communication between two containers.

> "Hello from webfrontend and webapi (with value 1)."

  [1]: https://i.stack.imgur.com/ggppf.png

**Comment by PingPongSet** [comment]
I am looking for an example that shows how to create projects for Kubernetes Orchestration and deploy to AKS. I searched through all docs from MS, but I cannot find one.

**Comment by ghogen** [comment]
For deployment during the dev life cycle, Azure Dev Spaces provides the CLI command 'azds up' which can be invoked from Visual Studio during a build when the Azure Dev Space is selected as the debug target.  The work here is to add more information to this topic.  For now, docs on this are provided at https://docs.microsoft.com/en-us/azure/dev-spaces/get-started-netcore-visualstudio

**Comment by ghogen** [comment]
Closing this as per previous comment - the article refers to the Docker Compose steps and for the Kubernetes scenario, refer to the Azure Dev Spaces docs.
