### ISSUE TITLE
Path to headers and libs

### ISSUE THREAD

**Issue by mlop3s** [MicrosoftDocs/visualstudio-docs#3615]
The path to both header and libs are not up to date. On visual studios 2019 they are on a different place. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3ec17-4193-8059-56de-fbad2fab239c
* Version Independent ID: e0e84806-41ff-fa5e-1aa1-775beed16d78
* Content: [Microsoft.VisualStudio.TestTools.CppUnitTestFramework API - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference?view=vs-2019#feedback)
* Content Source: [docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@mlop3s thanks for the feedback! Topic has been updated.
