### ISSUE TITLE
"Expressions and formatting" section needs note about XML escaping

### ISSUE THREAD

**Issue by SRM256** [MicrosoftDocs/visualstudio-docs#3620]
Please add the following note. I realize that this is implied by the rest of the document, but the VS feedback isn't clear, and it took quite a while to connect the dots to get some simple Boolean logic working.
 
Because the natvis document is XML, your expressions cannot directly use the ampersand, greater than, less than, or shift operators. You must escape these characters in both the item body and the condition statements. For example:

>     <Item Name="HiByte">(byte)(_flags &gt;&gt; 24),x</Item>
>     <Item Name="HiByteStatus" Condition="(_flags &amp; 0xFF000000) == 0">"None"</Item>
>     <Item Name="HiByteStatus" Condition="(_flags &amp; 0xFF000000) != 0">"Some"</Item>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#feedback)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I'll take a look at it.

**Comment by Mikejo5000** [comment]
Suggested Note looks good. Added to the docs. Should be live by end of day, 1/15/21
