### ISSUE TITLE
Natvis does not work for typedefs or plain types

### ISSUE THREAD

**Issue by SRM256** [MicrosoftDocs/visualstudio-docs#3621]
I think it is important to explicitly mention in the introduction that natvis cannot create custom visualizations for typedefs. Natvis only works for class and struct types. There is no way to give "typdef int color" a custom view where you show RGB values. Similarly, you cannot have a special view for a class when it is typedef'd, for example "typedef std::string address". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#feedback)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I'll take a look at this.

**Comment by Mikejo5000** [comment]
Asking about this...

**Comment by Mikejo5000** [comment]
From product team: Correct, the debugger doesn't see the typedef 'alias' at debug time so it cannot match the typedef 'alias' with the name in the natvis file.

I'll add the note. Thanks!

**Comment by Mikejo5000** [comment]
Fix is live.

**Comment by SRM256** [comment]
Fix verified. Looks good. Thank you.
