### ISSUE TITLE
How to collect memory usage on remote server?

### ISSUE THREAD

**Issue by wwc7654321** [MicrosoftDocs/visualstudio-docs#3622]
Is there anything I can do to collect memory usage of c++ software from remote server ,where Visual Studio is too big to be installed.
maybe RemoteDebugger.exe ? or VSDiagnostics.exe ? or anything else...
Only got some way for collecting CPU usage, not any for Memory.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32ee515-19a1-748e-3f83-8c398a6e159a
* Version Independent ID: c72c41a3-c3cf-b696-e2de-031fcd755502
* Content: [Analyze memory usage without debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/memory-usage-without-debugging2?view=vs-2019#feedback)
* Content Source: [docs/profiling/memory-usage-without-debugging2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/memory-usage-without-debugging2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Sorry for the delayed response. Yes, I believe you want to download the Performance Tools for Visual Studio 2019
https://visualstudio.microsoft.com/downloads/#performance-tools-for-visual-studio-2019
I don't see a doc on using the tools remotely, so I'll ask about this.

**Comment by andysterland** [comment]
The tools, VSDiagnostics.exe, needs to run on the device where the data is being collected. It can't be started remotely unless you scripted it to be deployed and started remotely.

**Comment by Mikejo5000** [comment]
I will clarify in the docs that the Remote Tools (w/VSDiagnostics.exe) need to be installed on the remote machine for this scenario. The command-line profiling tools appears to be another way to do this remotely. @andysterland @esteban-herrera for any additional input.
