### ISSUE TITLE
Download Link for VS2017 and VS2015 Version broken

### ISSUE THREAD

**Issue by SebastianBecker2** [MicrosoftDocs/visualstudio-docs#3624]
The download link on my.visualstudio.com didn't work for me.
It said the download couldn't be found.
When switching to another site on my.visualstudio.com,
I had to confirm Terms of Use or something.
(Which I obviously read, thoroughly!)
After accepting that dialog, the link worked again.

More of a my.visualstudio.com issue.
But it might be important for people trying to get the download working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019#feedback)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@SebastianBecker2 Thanks for the feedback! We hear this occasionally, but it seems to be very hard to get a repro. What browser are you using?

**Comment by SebastianBecker2** [comment]
Hi Mike,

I’m using chrome. Up to date version.
I guess this issue only happens if you are logged into your Microsoft account while also having to agree to some terms of service changes.
And you have to have a direct link to the download page.
That is a rare situation. Especially if you’re working on Microsoft sites and trigger the terms of services dialog pretty immediately when those changes arise.

I hope this is helpful.

__________________________________________

Sebastian Becker
Softwareentwicklung

comundus REGISAFE GmbH
Heerstraße 111, D-71332 Waiblingen

Durchwahl    +49 7151-96528-227
Zentrale       +49 7151-96528-0
Fax              +49 7151-96528-999
E-Mail     s.becker@comundus.com<mailto:s.becker@comundus.com>
Internet   www.regisafe-comundus.de<http://www.regisafe-comundus.de/>

Geschäftsführer Thomas Behrend, Siegfried Fitzel, Klaus Hillemeier
Amtsgericht Stuttgart, HRB 264290
__________________________________________

Sie sind von unserer E-Akte genauso begeistert wie wir?
Dann unterstützen Sie uns bei den eGovernment Reader's Choice Award 2019.
regisafe ist in der Kategorie "E-Akte" nominiert. Hier geht's zur Umfrage: http://bit.ly/eGovAwards2019

Von: Mike Jones <notifications@github.com>
Gesendet: Friday, 12 July, 2019 17:28
An: MicrosoftDocs/visualstudio-docs <visualstudio-docs@noreply.github.com>
Cc: Becker, Sebastian <s.Becker@comundus.com>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftDocs/visualstudio-docs] Download Link for VS2017 and VS2015 Version broken (#3624)


@SebastianBecker2<https://github.com/SebastianBecker2> Thanks for the feedback! We hear this occasionally, but it seems to be very hard to get a repro. What browser are you using?

**Comment by Mikejo5000** [comment]
Thanks for the clarification. Yes, that's helpful information.

**Comment by Mikejo5000** [comment]
I think I'll leave doc as-is for now. Thanks!
