### ISSUE TITLE
Wizard will not load

### ISSUE THREAD

**Issue by jaredf55** [MicrosoftDocs/visualstudio-docs#3626]
This is my first Project Template and Template Wizard solution.  So, I am relying completely on the documentation to learn how to do this.  I have followed the steps exactly as described in this guide, using Visual Studio 2019, but the wizard will not display when using the Template in Visual Studio.  Basically, in the Use the Custom Wizard section, between step 3 and 4, where it says the wizard user input form opens, nothing happens.  The project is just created and no wizard appears.  I have checked and re-checked the steps provided and can't find anything amiss with my solution.  Is there any documentation on troubleshooting wizard creation? Or any ideas on why this didn't work in 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21714a79-85d5-7bc4-be1a-f8309ffbd15a
* Version Independent ID: 5611a3ee-ec02-e60d-550b-14eb4b38917a
* Content: [How to: Use Wizards with Project Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates?view=vs-2019#feedback)
* Content Source: [docs/extensibility/how-to-use-wizards-with-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-use-wizards-with-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by jaredf55** [comment]
Or is there a functioning project template/wizard solution I can download from github to compare?

**Comment by msebolt** [comment]
@jaredf55 My apologies on the delay, please refer to issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/2816.  

If there are any further issues please comment below.
