### ISSUE TITLE
Running fails

### ISSUE THREAD

**Issue by WindowsNT** [MicrosoftDocs/visualstudio-docs#3627]
404 from the server, cannot find the package.
My question is there
https://stackoverflow.com/questions/56920868/trying-to-debug-native-ios-app-with-vs-2019?noredirect=1

```
Device.installApp executing command: /usr/local/lib/node_modules/vcremote/node_modules/ios-deploy/build/Release/ios-deploy --id 355c4a7afbd0e98ac9596c146fa1d051e9b2b3fe --nostart --bundle "/Volumes/DATA/r/F/ITOOLS/Tralala/Tralala/ARM64/Debug//Tralala.app" --timeout 5
Installed app on device: 'iPad'
GET /projects/2df69712-b4b8-43f3-9ada-fc50ca3fa6b1/build/ce4ed9aa-f673-4c78-99cb-968e2dc5bb7c/install?ver=1.4.0&appName=Tralala.app 200 5856ms
Debug Listener already listening
GET /debug/appRemotePath?package=com.Tralala&deviceUdid=xxxx 404 38ms - 196b
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f33eba-a747-c57b-02e3-853d2a8a5c3b
* Version Independent ID: 1ddd9492-f5b1-d0ae-b813-c3838452a17a
* Content: [Install And Configure Tools to Build using iOS - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios?view=vs-2019)
* Content Source: [docs/cross-platform/install-and-configure-tools-to-build-using-ios.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/install-and-configure-tools-to-build-using-ios.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@WindowsNT 
I'm sorry to hear the debugging connection isn't working for you. It sounds like an issue in either the vcremote server setup, or permissions between your device and computer. As far as I can tell, it's not (yet) a documentation issue. Your best bet is a post or follow-up on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html), where the engineering team can see issues and take them on. They don't usually look here for support questions. Be aware that iOS development issues may not be a high priority, but they do get some attention. Here on the documentation side, we update things when the engineers have changed something or a description needs to be fixed. If that's the case here, they'll let us know.

CC @michelleangela for awareness.
