### ISSUE TITLE
Advice on CA2225 and operator naming in the face of preexisting conversion methods

### ISSUE THREAD

**Issue by peteroupc** [MicrosoftDocs/visualstudio-docs#3629]
This page should include advice on dealing with this rule with a class that implements preexisting methods
that are alternatives to operators, but have different names than suggested.  In my case, this issue occurs with [classes](https://github.com/peteroupc/Numbers/tree/master/Numbers/PeterO/Numbers) named EInteger, EDecimal, EFloat, and ERational.

1.  If a class implements, say, the `&` operator, but has an alternative method named `And` (not `BitwiseAnd` as suggested), and that method occurs in shipped code, should CA2225 be suppressed?  Or should the class include a method with the suggested name anyway?

2.  If a class implements multiple versions of a method that converts to the same data type, each serving a different purpose but not having the suggested name (e.g., the class has `ToInt32Checked`, `ToInt32Unchecked`, and `ToInt32IfExact`, but not `ToInt32` because the name doesn't make its behavior obvious enough), and also has an explicit operator converting to that data type, should CA2225 be suppressed?  Or should the class include a method with the suggested name anyway despite the disadvantages of that name compared to the names it does implement?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7461911-4502-1e60-82b1-cc3cf1545ddf
* Version Independent ID: 2deb7000-b80d-01b1-644e-2748a113f637
* Content: [CA2225: Operator overloads have named alternates - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2225)
* Content Source: [docs/code-quality/ca2225-operator-overloads-have-named-alternates.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca2225.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@peteroupc Sorry it took so long to reply. I'd say you should probably suppress the warning for the cases you described. Tagging @mavasani for comment too.

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22045](https://github.com/dotnet/docs/issues/22045)
