### ISSUE TITLE
missing line of code in gif

### ISSUE THREAD

**Issue by pb-balt** [MicrosoftDocs/visualstudio-docs#3630]
int c = a + b; is missing in the gif

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@pb-balt Thank you for the feedback!  

I think the purpose of the GIF is to facilitate an understanding on how auto-complete works and not necessarily follow the code snippet verbatim, though I will include the author here for future consideration.

FYI @tglee

**Comment by chuckwolber** [comment]
My apologies for opening a ticket an issue along the same lines, I missed this before reporting. However, the purpose of the GIF is very obviously to show how to implement the example in all its glory. The GIF is simply incorrect and should be fixed.

**Comment by TerryGLee** [comment]
@msebolt This does not need to be reopened; I will address it with #4000 - Thanks.
