### ISSUE TITLE
How to permanently "Select Test Settings File" in Visual Studio?

### ISSUE THREAD

**Issue by Swimburger** [MicrosoftDocs/visualstudio-docs#3632]
Every time I open Visual Studio I have to re-select the .runsettings before running my tests. How can we link this once and not have to do this over and over again?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#feedback)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@Swimburger Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  
[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
[https://www.stackoverflow.com](https://www.stackoverflow.com) 
[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by Swimburger** [comment]
Thank you for pointing that out. I have asked the [question on the suggested VS forum](https://social.msdn.microsoft.com/Forums/vstudio/en-US/1d577f3d-4371-440e-a042-6074ffc7546a/how-to-permanently-select-test-settings-file-in-visual-studio?forum=vsunittest).

**Comment by b8adamson** [comment]
Consider making it more prominent/evident that for the "Select Test Settings File" selection to persist across closing and re-opening Visual Studio that you must be working with (and saving) Solution (.sln) files.  For those of us that only want to work with project files it seems that we are stuck reselecting the the correct file via the menu bar every time we re-open Visual Studio.

**Comment by gewarren** [comment]
Reopening this issue to document the project vs. solution behavior. Thank you @b8adamson.

**Comment by Swimburger** [comment]
@b8adamson FYI, I have always been using the Solution approach when the test setting file stopped persisting.

**Comment by gewarren** [comment]
@b8adamson I moved a project to a folder without a solution, and then opened that folder in VS using "File -> Open -> Folder". I selected a runsettings file and closed the folder in VS. When I reopen that folder, the runsettings file is still selected. Did you read somewhere that test settings files only persist if you use solution files, or is it just from your experience?

**Comment by gewarren** [comment]
Closing as there doesn't seem to be anything to document.
