### ISSUE TITLE
this info is wrong and wasted my time

### ISSUE THREAD

**Issue by shaig4** [MicrosoftDocs/visualstudio-docs#3636]
thanks ms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed74b634-19be-61b4-ad2e-9520b1a89502
* Version Independent ID: e52821c5-306c-6cc4-4a37-ce8bb35b4539
* Content: [What's New in MSBuild 16.0 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/whats-new-msbuild-16-0?view=vs-2019#feedback)
* Content Source: [docs/msbuild/whats-new-msbuild-16-0.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/whats-new-msbuild-16-0.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@shaig4 Hi, thanks for the feedback. What was the information you wanted to find in this article? I assume it was missing?

**Comment by Mikejo5000** [comment]
Need more info on this.
