### ISSUE TITLE
CA2202 - use null propagation instead (syntactic sugar)

### ISSUE THREAD

**Issue by qub1n** [MicrosoftDocs/visualstudio-docs#3637]
In the example of https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2202-do-not-dispose-objects-multiple-times?view=vs-2019

please change the finally statement from

if(stream != null)
        stream.Dispose();

to 

       stream?.Dispose();

**Comment by msebolt** [comment]
@qub1n Thank you for the feedback!

@TerryGLee Are these documents auto-generated?  

If so, the issue should be re-assigned.

**Comment by gewarren** [comment]
These docs are not auto-generated. The OP is referring to the [null-conditional operator](https://docs.microsoft.com/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-). @WilliamAntonRohm Feel free to update the example and perhaps add a link to the null-conditional operator docs in a TIP box below the example.

**Comment by WilliamAntonRohm** [comment]
Private repo PR 5009 contains the new code -- https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5009.

**Comment by WilliamAntonRohm** [comment]
The updated code sample document should be live by tomorrow.
