### ISSUE TITLE
VCProjectUpgraderObjectName property doesn't work with VS2019

### ISSUE THREAD

**Issue by CarlPoirier** [MicrosoftDocs/visualstudio-docs#3639]
Hi,

In the following document, we can read that setting `<VCProjectUpgraderObjectName>NoUpgrade</VCProjectUpgraderObjectName>` disables the upgrade prompt. I tried it with Visual Studio 2015 and works well, but it has no effect with Visual Studio 2019. What is the correct property to accomplish the same thing in 2019?

Thank you,

Carl

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ff894fc-450a-8bee-641c-680e403ab467
* Version Independent ID: e8097aa3-6469-b861-37b5-054af0b267c6
* Content: [Visual C++ project extensibility - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/visual-cpp-project-extensibility?view=vs-2019)
* Content Source: [docs/extensibility/visual-cpp-project-extensibility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/visual-cpp-project-extensibility.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@CarlPoirier  I'm sorry to hear it's given you trouble. I've asked some relevant people on the dev team, and I'm told that if this method doesn't work, it's a bug. The documentation is correct, at least as far as how it's supposed to behave. I haven't seen this issue reported on Developer Community, either. I suggest you [use the Report a Problem feature in VS to report it](https://docs.microsoft.com/en-us/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=vs-2019), which will get the developers' attention and let them report back to you on any solution. 

I'm closing this as it's not a documentation issue. At least, not yet. Good luck!

**Comment by CarlPoirier** [comment]
Awesome, thanks for the quick reply.
