### ISSUE TITLE
Add reference docs for refactoring code style options

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#3641]
Some editorconfig options don't have a severity and don't appear in the Error List as warnings or suggestions. Instead, they are only used during a refactoring. For example, `dotnet_style_operator_placement_when_wrapping`.

[Values](https://github.com/dotnet/roslyn/blob/master/src/Workspaces/Core/Portable/CodeStyle/CodeStyleOptions.cs#L126) are `end_of_line` and `beginning_of_line`.

```csharp
if (true
    && true)

if (true && 
    true)
```

**Comment by gewarren** [comment]
As noted in #1070 by @alexrp @cremor.

**Comment by TerryGLee** [comment]
@gewarren This looks to be a duplicate now. OK to close? (If not, I'll reassign to @mikadumont.)

**Comment by gewarren** [comment]
@TerryGLee Yes that's fine.

**Comment by hamjo** [comment]
This is not a duplicate anymore. The previous issue was closed, but this setting got left out of the fix. The only place where this setting is mentioned in https://docs.microsoft.com is in this page : https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options

It would need it's own documentation page.

**Comment by cremor** [comment]
Please don't close. All EditorConfig rules should be documented.

**Comment by j-martens** [comment]
#reassign: @TerryGLee  to create the work item of what's needed here please.

**Comment by TerryGLee** [comment]
@Mikejo5000 Please take a look at this; thanks.

**Comment by cremor** [comment]
Please don't close. All EditorConfig rules should be documented.

**Comment by cremor** [comment]
Please don't close. All EditorConfig rules should be documented.

**Comment by Mikejo5000** [comment]
dotnet_style_operator_placement_when_wrapping is now documented here:
https://learn.microsoft.com/en-us/visualstudio/ide/reference/code-styles-refactoring-options?view=vs-2022
This appears to be the only rule relevant to this VS doc issue.
