### ISSUE TITLE
GetRequiredService<SchoolContext>

### ISSUE THREAD

**Issue by Vincent-Jeevan** [MicrosoftDocs/visualstudio-docs#3642]
Had to change the SchoolContext to AppDb to get the expected results.
Other than that the whole page was brilliant. Thank you very much for your work.  

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f156aaa-839a-b9bb-5912-b3a537dfdb36
* Version Independent ID: 51888076-400e-0a51-8ae4-6fe745829436
* Content: [Step 3: Working with Data in Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-nz/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-03?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by ghogen** [comment]
Thanks, we've now updated the topic to fix the problem.
