### ISSUE TITLE
having an issue with this code; EnsureCreated();

### ISSUE THREAD

**Issue by omboho** [MicrosoftDocs/visualstudio-docs#3643]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'object' does not contain a definition for 'EnsureCreated' and no accessible extension method 'EnsureCreated' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)	WebApplication3

**Comment by WilliamAntonRohm** [comment]
@omboho Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
