### ISSUE TITLE
Document Analyzer Configuration in .editorconfig

### ISSUE THREAD

**Issue by mikadumont** [MicrosoftDocs/visualstudio-docs#3646]
We need to make sure we have docs that tell users how to use .editorconfig with analyzers.

**Comment by mikadumont** [comment]
cc: @agocke @jasonmalinowski I believe you both worked on this feature?

**Comment by jasonmalinowski** [comment]
@mikadumont Yep. @JoeRobich a bit too.

**Comment by gewarren** [comment]
@mikadumont Are you referring to the FxCop analyzers or the built-in IDE analyzers? We already have docs for both that you could build on.

**Comment by gewarren** [comment]
Closing since this is already documented here: https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers. If there's something else that's missing, let me know and I'll reopen.
