### ISSUE TITLE
What about changing the output path to an *.ifc file when /module:export is specified?

### ISSUE THREAD

**Issue by AraHaan** [MicrosoftDocs/visualstudio-docs#3647]
I would like to know this because I want to have it output to $(OutputPath) not sure why it does not default to that in the first place???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4938a042-e5db-4f9c-2288-930b904e888c
* Version Independent ID: 6db1e386-22e4-4940-cc2c-bdeaa5883299
* Content: [How to: Change the build output directory - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2019)
* Content Source: [docs/ide/how-to-change-the-build-output-directory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-change-the-build-output-directory.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@AraHaan Thank you for the feedback.

This sounds more like a feature request then an issue with the documentation.  

Please use the **Suggest a Feature** option in the [Visual Studio forums](https://developercommunity.visualstudio.com/spaces/8/index.html) to get the most traction.

**Comment by AraHaan** [comment]
Also it seems that program db for edit and comtinue (when module:export is set) causes the compiler to ICE as well saying it is not implemented yet.

Also is there a way that (for the reason of vs not having a way to provide module:export automatically when it sees someone type ``export module <module name>`` to if the compiler reads that and sees it is not specified; to warn that it was not and to have it then export then as of it was specified? For the case of the option not existing yet in vs2019 that I know of. But ye I think each one can be suggested individually there. If only there was a way to suggest it from my iphone as rn my laptop does not have internet rn (I use public wifi rn to go on it to do just that). Unless you guys can help file them there for me?
