### ISSUE TITLE
Add missing VB style options

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#3648]
Add these style [options](https://github.com/dotnet/roslyn/blob/bef4da75dd034df803a4b6dac4bf811c6990e200/src/Workspaces/VisualBasic/Portable/CodeStyle/VisualBasicCodeStyleOptions.vb
) to https://docs.microsoft.com/visualstudio/ide/editorconfig-language-conventions.

- [x] visual_basic_style_unused_value_expression_statement_preference
- [x] visual_basic_style_unused_value_assignment_preference

Use the example of [visual_basic_preferred_modifier_order](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#normalize-modifiers).

Related to #1070.

**Comment by mikadumont** [comment]
I went ahead and added the two rules!
