### ISSUE TITLE
Please provide documentation on references to "Shared Projects"

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/visualstudio-docs#3649]
### Visual Studio & Shared Projects
In the "Reference Manager" dialog for a project in Visual Studio, it is possible to set up references to something called "Shared Projects", but the documentation page for adding/managing references to a project have no information on this type of reference at all.
![image](https://user-images.githubusercontent.com/7513795/61372003-52400980-a896-11e9-8922-0f0f1d3e1c5a.png)

As a matter of fact, I can't find any documentation on the concept "Shard Project" anywhere in the entire documentation of visual studio.
When searching for "shard project" it returns 8 result, where non has anything to do with shared projects.
.<details><summary>**Search Result when searching for: ["Shard Project"](https://docs.microsoft.com/en-us/search/?search=%22Shared%20Project%22&scope=VS%20IDE&view=vs-2019)**
</summary>
<p>

> ### 8 Results for ""Shared Project""
> **How to: Set Permissions - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-set-permissions
> The second procedure, "To grant access to shared project files," describes how to grant that access. ... This grants permissions to the user for the shared folder tree that begins with the folder selected in step 5.
> 
> **How to: Create Types by using Class Designer - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/ide/class-designer/how-to-create-types
> To design new types for C# and Visual Basic projects, create them on a class diagram. ... Select the file where you want to add the initial code for the type: To create a new file and add it to the current project, select Create new file and name the file.
> 
> **How to: View Existing Types (Class Designer) - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/ide/class-designer/how-to-view-existing-types
> To see types in a project on a class diagram From a project in Solution Explorer, open an existing class diagram (.cd) file. ... See How to: Add Class Diagrams to Projects.
> 
> **Use code maps to debug your applications - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/modeling/use-code-maps-to-debug-your-applications
> For example, when you're debugging, you might have to look at code across many files and projects. ... So, if you change the context to another app project, then the context on the map also changes for any newly added items from the shared project.
> 
> **Cross-Platform Mobile Development in Visual Studio - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/cross-platform/cross-platform-mobile-development-in-visual-studio
> You can share your code by using a shared project, a Portable Class Library project, or both. ... You can share C++ code between Android and Windows by creating a static or dynamic shared library.
> 
> **Visual C++ for Cross-Platform Mobile Development - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-cpp-for-cross-platform-mobile-development
> This is an option available in Visual Studio 2015 that installs the SDKs and tools you need for cross-platform development of shared libraries and native apps. ... Dynamic Shared Library (Android) Creates an Android dynamic library (.so) file by using C++ code.
> 
> **C++ IntelliSense - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/ide/visual-cpp-intellisense
> Cross-platform IntelliSense In a shared code project, some IntelliSense features such as squiggles are available even when you are working in an Android context. ... The illustration shows shared code being edited.
> 
> **Code maps - Visual Studio**
> https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions
> If you change context to another app project and add more items from the shared project, those items now appear with the newly active app project. ... Operations that you perform with an item on the map apply only to those items that share the same context.

</p>
</details>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab2b85e-d741-293c-b994-8673ebf9ec2b
* Version Independent ID: a3697a8f-ea35-c2ca-9cb3-fd15c6bd5ca3
* Content: [Manage references in a project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/managing-references-in-a-project?view=vs-2019)
* Content Source: [docs/ide/managing-references-in-a-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/managing-references-in-a-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@Bartolomeus-649 Thank you for the feedback.

The **Shared Projects** is a newer feature in Visual Studio that's currently documented for [Xamarin solutions](https://docs.microsoft.com/xamarin/cross-platform/app-fundamentals/shared-projects?tabs=windows) though we can try to get this added to Visual Studio docs as time permits.

In the meantime, please see this [synopis](https://stackoverflow.com/questions/30634753/what-is-the-difference-between-a-shared-project-and-a-class-library-in-visual-st) for an overview on how **Shared Projects** work.

@gewarren FYI

**Comment by Bartolomeus-649** [comment]
If it's a generic feature, then why is it documented under Xamarin?

As it is now with the current documentation, "Shared Projects" are not even mentioned anywhere in the entire Visual Studio Documentation.

Why not just move whatever you now have under Xamarin to where it really belong, or are you planing of maintaining a duplicate version of the whole thing a second time for Visual Studio?

_Also, I think you should provide some documentation on why Xamarin is not part of Visual Studio, I think a lot of people will be surprised to know that Microsoft don't consider it part of Visual Studio, especially since you might get that impression when it seems like you are using Visual Studio to create, code and build Xamarin projects..._
