### ISSUE TITLE
juki666

### ISSUE THREAD

**Issue by jukka62** [MicrosoftDocs/visualstudio-docs#3653]
very intresting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d0cb94-2886-79ce-39dd-0336282369b9
* Version Independent ID: e8bcc58e-98af-e3ad-2629-0b4515047d0b
* Content: [Modify Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/modify-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/modify-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@jukka62 Thank you for the feedback.

If you have anything further to add to this issue, please comment below.
