### ISSUE TITLE
error in to

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#3656]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/visualstudio-docs.pl-pl/issues/9
The user is refering to the original documentation

@Systu commented 3 days ago
(Translated)
In spite of following the line's content:
SPFieldUserValue currentUser = new SPFieldUserValue
(this.Web, this.Web.CurrentUser.ID, this.Web.CurrentUser.Name);

indicates error:
Severity Code Description Project File Line Suppression State
Error CS1061 'SearchItemsUserControl' does not contain a definition for 'Web' and no accessible extension method 'Web' accepting a first argument of type 'SearchItemsUserControl' could be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5b49d36-e361-397d-562a-7da841d8e939
* Version Independent ID: d61038f6-ca8e-3d0c-7712-5a90e0f510e2
* Content: [Walkthrough: Creating a SharePoint Application Page - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/sharepoint/walkthrough-creating-a-sharepoint-application-page?view=vs-2019#feedback)
* Content Source: [docs/sharepoint/walkthrough-creating-a-sharepoint-application-page.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/sharepoint/walkthrough-creating-a-sharepoint-application-page.md)
* Product: **visual-studio-windows**
* Technology: **sharepoint-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@CeciAc  please make sure you have the **using Microsoft.SharePoint.WebControls;** in the includes section at the top of the code file as mentioned in Step 3 of the [Handle the events of controls on the page](https://docs.microsoft.com/en-us/visualstudio/sharepoint/walkthrough-creating-a-sharepoint-application-page?view=vs-2019#handle-the-events-of-controls-on-the-page) section.
