### ISSUE TITLE
Ctrl+U shortcut NOT assigned to Make Lowercase

### ISSUE THREAD

**Issue by graymatter00** [MicrosoftDocs/visualstudio-docs#3661]
VS 2019 Make Lowercase does not have a default keyboard shortcut.  That is, Ctrl+U is NOT assigned to Make Lowercase.  On a clean installation of VS 2019 Community there is no shortcut assigned to Make Lowercase.

![image](https://user-images.githubusercontent.com/7201626/61604979-e63f1600-ac86-11e9-9329-6a08693b2841.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7b27ada-f62b-0853-2a8f-38c81af480a4
* Version Independent ID: 4fa67498-a0f2-87c9-fc1d-acb3d6dfc796
* Content: [Convert text to uppercase or lowercase - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-text-case-in-the-editor?view=vs-2019)
* Content Source: [docs/ide/how-to-change-text-case-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-change-text-case-in-the-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@graymatter00 Thanks for letting us know, however, I can't repro what you're seeing. Do you happen to know which development settings profile you chose? I checked the General, C#, and C++ profiles, and they all have Ctrl+U set as the shortcut for Edit.MakeLowercase.

![image](https://user-images.githubusercontent.com/24882762/61649060-8e43e780-ac65-11e9-99af-e5e282254c62.png)

**Comment by gewarren** [comment]
Closing this as Not Reproducible.

**Comment by mhuguet** [comment]
@gewarren I can repro it. Ping me internally, if you want to see my environment. I am using VS 2017. My alias is michu.

**Comment by mhuguet** [comment]
![image](https://user-images.githubusercontent.com/12263630/62710630-345d5480-b9bd-11e9-83b1-76ac9a20e5bc.png)

**Comment by gewarren** [comment]
It seems that the C++ workload is overriding the keybinding for Make Lowercase. I'll update the doc with this info.
