### ISSUE TITLE
Effectively useless “backwards compatibility”?

### ISSUE THREAD

**Issue by ite-klass** [MicrosoftDocs/visualstudio-docs#3663]
In the build target import code with comments there it defines a block for backwards compatibility. I do not get what the backwards compatibility is for.

I can use the VS2019 MSBuild without the backwards compatibility code just fine. The backwards compatibility code itself sets VS version 16.0 though, which is for VS2019. So the backwards compatibility seems to be unnecessary for VS2019, but fall back to VS2019 anyway.

So I would expect a VS2017 build without VS2019 installed to fail. That's not backwards compatibility as I would expect it. It effectively does not add any backwards compatibility at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca46de41-5103-a318-3553-3bf05c59751b
* Version Independent ID: 27b60762-dfe8-9320-c891-164e2f0ca980
* Content: [Code Generation in a Build Process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process?view=vs-2019)
* Content Source: [docs/modeling/code-generation-in-a-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/code-generation-in-a-build-process.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by ite-klass** [comment]
Is it to allow command line invocation overwriting the default version?

Found in best practices https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-best-practices?view=vs-2019

Then the wording “portable across VS versions” is at least misleading still though.

**Comment by JoshuaPartlow** [comment]
Not seeing content associated with this issue, so closing.
