### ISSUE TITLE
"Before .NET"

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/visualstudio-docs#3665]
There was no before .NET. I suspect that is supposed to say "Before .NET 2". 2 was the version that introduced generics. Also I suspect where it says "targets .NET" it should also be giving a version number.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efb4c520-95e7-d46f-6e44-4a755bd12af3
* Version Independent ID: 45213f1e-b1c8-7251-b6d9-21fb64159b57
* Content: [CA1003: Use generic event handler instances - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1003-use-generic-event-handler-instances?view=vs-2019)
* Content Source: [docs/code-quality/ca1003-use-generic-event-handler-instances.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1003-use-generic-event-handler-instances.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Mikejo5000** [comment]
Looks reasonable. Updating.
