### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/visualstudio-docs#3666]
Is this documentation applicable to creating .NET Core templates?

![image](https://user-images.githubusercontent.com/14079228/61644482-caca1000-ac72-11e9-8fcd-663aea5d2bf5.png)

In the framework dropdown, I only see the full framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 397b0790-ed8b-822d-931a-98a06c594ec6
* Version Independent ID: f1b1aa72-1bd7-c0b1-3d77-5e9b978a9b11
* Content: [Creating Custom Project and Item Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-custom-project-and-item-templates?view=vs-2019)
* Content Source: [docs/extensibility/creating-custom-project-and-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-custom-project-and-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by spottedmahn** [comment]
I'm guessing, looks like this is the place for .NET Core: https://docs.microsoft.com/en-us/dotnet/core/tutorials/cli-templates-create-project-template

**Comment by spottedmahn** [comment]
If I only want to do it **once**, is that an option?

If I use the `dotnet new` cli option do those show up in VS?  Or do I have to do it two times?

Thanks for the quick response BTW! 👏

**Comment by madskristensen** [comment]
@sayedihashimi Would the new SideWaffle project help with this?

**Comment by sayedihashimi** [comment]
@spottedmahn with .NET Core templates the idea is that you create the template for ***dotnet new*** by creating a NuGet package, and then you can wrap that into a .vsix for surfacing in Visual Studio.

You can use an OSS project that I work on [SideWaffleV2](https://github.com/ligershark/sidewafflev2/) to create the NuGet package, as well as the .vsix for Visual Studio. In the Readme for that repo there are a couple of videos linked that show how to get started. After creating the extension, you would need to upload the .nupkg file to nuget.org to enable ***dotnet new***, and the .vsix to the VS Marketplace for VS consumers.

Ideally VS would have built in support for .NET Core templates but that doesn't exist, as far as I'm aware at least.
