### ISSUE TITLE
CA1019 - Better explanation needed

### ISSUE THREAD

**Issue by ronwarner** [MicrosoftDocs/visualstudio-docs#3669]
"For every mandatory argument, the attribute should also provide a corresponding read-only property so that the value of the argument can be retrieved at execution time."

This position is stated in the description, but said position is not adequately justified.  There needs to be some explanation on why Attributes "should" do this.  I can't think of any Attribute I've made where I've needed, or even wanted, to allow public access to the data passed into the constructor.  If my approach has been wrong, I need to know why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3989ba41-ee9e-0aaa-e25f-33307a16f131
* Version Independent ID: 3e9dec58-6d34-8ce2-9e4e-20723700430d
* Content: [CA1019: Define accessors for attribute arguments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1019-define-accessors-for-attribute-arguments?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1019-define-accessors-for-attribute-arguments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1019-define-accessors-for-attribute-arguments.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Mikejo5000** [comment]
@ronwarner Looks like a design recommendation. Later in the article, it says "Positional and named arguments make it clear to consumers of your library which arguments are mandatory for the attribute and which arguments are optional." So, mandator arguments have a getter, optional arguments have a getter and a setter. So, the issue appears to be consistency for users of the library.
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1019?view=vs-2019#positional-and-named-arguments

**Comment by Mikejo5000** [comment]
Since the reason is already stated in the article, though in a later section, closing this issue.
