### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by DaveInCaz** [MicrosoftDocs/visualstudio-docs#3671]
I can't find anything which specifies what license is used for the "Microsoft Visual Studio Image Library 2017". It gives the impression that developers are allowed to use these images in their own applications, but if there is a specific set of terms for this I can't find it.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05fe994a-b63e-dfc1-9de9-97e56a4e4917
* Version Independent ID: 95c63cef-e907-f443-a885-d1265f47c171
* Content: [Image Library - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/the-visual-studio-image-library?view=vs-2019)
* Content Source: [docs/designers/the-visual-studio-image-library.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/the-visual-studio-image-library.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@DaveInCaz From the download link on the page, [Download the Visual Studio image library](http://go.microsoft.com/fwlink/p/?LinkId=275090), there is a list of files in the Details section, which includes EULA (end-user license agreement) information:

![image](https://user-images.githubusercontent.com/23244653/61751868-959aec00-ad5e-11e9-83e6-615b0184fda2.png)

It looks like the "Visual Studio 2017 Image library EULA.rtf" file should include the information you seek.

**Comment by DaveInCaz** [comment]
Thanks. It wasn't obvious from the filename that "EULA" meant that.
