### ISSUE TITLE
SpecificSolutionName should be SpecifiedSolutionName

### ISSUE THREAD

**Issue by georgechang** [MicrosoftDocs/visualstudio-docs#3674]
The `Reserved template parameters` section has the wrong token for a solution - the correct token is `SpecifiedSolutionName` and not `SpecificSolutionName` as shown in the document. Additionally, might be a good idea to have it as `specifiedsolutionname` to match the formatting of the rest of the tokens.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Project and item template parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019#feedback)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by chandrababumaddipatla** [comment]
I am looking for same, i have entire template ready with multiple projects But unable to correct reference since these, I was depending on $SpecifiedSolutionName$ and $SpecificSolutionName$ values. Since these are empty I am not able to handle this.

**Comment by chandrababumaddipatla** [comment]
And another question is why we need to depend on the checkbox as per the documentation SpecificSolutionName - The name of the solution. When "create solution directory" is checked, SpecificSolutionName has the solution name. When "create solution directory" is not checked, SpecificSolutionName is blank. Since this is an optional field most of the times user may not check or un-check this checkbox, I prefer this value needs to populated for all the scenarios.

**Comment by gewarren** [comment]
@chandrababumaddipatla - The best place to make product feature suggestions or provide feedback is on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). Look for the "Suggest a Feature" button:

![image](https://user-images.githubusercontent.com/24882762/50102736-a7218180-01da-11e9-9aaf-ea3a99ccd030.png)

When you suggest a feature on Developer Community, you can engage directly with the engineering team as they consider the suggestion. It also provides a way for other customers to upvote your suggestion.
