### ISSUE TITLE
Out of date Perfview Link

### ISSUE THREAD

**Issue by KevinCathcart** [MicrosoftDocs/visualstudio-docs#3677]
The link on this page leads to a download center page with a note that explains that this is an out of date version, and that the up to date version is found on GitHub. 

Unless you specifically need 1.9 for some reason, it might be wise to update the link to point to https://github.com/Microsoft/perfview/blob/master/documentation/Downloading.md 

(That is where the download center page points to users to. It is a direct link apparently not using the fwlink service.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef410b52-1f8f-6f71-1b86-92d73fd258f6
* Version Independent ID: 7b83a96b-1d79-48f7-c702-da151b91ddff
* Content: [Collect an ETL trace with PerfView - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem-perfview?view=vs-2019#feedback)
* Content Source: [docs/ide/report-a-problem-perfview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem-perfview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@KevinCathcart thanks for the feedback. Topic has been updated.
