### ISSUE TITLE
Major Test Explorer Update in 16.2

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/visualstudio-docs#3681]
There was a major test explorer update in Visual Studio 2019 16.2 and as of this morning 16.2 is GA released!

- [Read more in the Release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#test-explorer)
- [Blog](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-version-16-1-generally-available-and-16-2-preview-1/)

Several docs should be updated with 2019 pictures and a few sections should be added as well to cover the main new features:
- [X]  [Get started](https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2019) was already recently updated
- [x] [Testing tools in VS](https://docs.microsoft.com/en-us/visualstudio/test/improve-code-quality?view=vs-2019) : [PR](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5075)
- [x] [Unit Testing Basics](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019) ([PR](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5169
))
- [x] [Run Unit Tests in the Test Explorer](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019) : [PR](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5075)

New sections to be added in Test Explorer doc
- [x] Filter buttons
- [x] Adjustable and filterable columns
- [x] New groupby
- [x] New playlists tabbed view
- [x] Live Unit Testing tab MicrosoftDocs/visualstudio-docs-pr#6386, MicrosoftDocs/visualstudio-docs-pr#6373

More minor updates:
- [x] [Test Explorer FAQ](https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq?view=vs-2019) [(PR)](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5205)
- [x] [Get Started with Live Unit Testing](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-start?view=vs-2019&tabs=csharp)
- [x] [Use Live Unit Testing with VS Enterprise](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2019)
- [ ] [Code coverage doc](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019)

**Comment by Mikejo5000** [comment]
"Use Live Unit Testing..." updated in MicrosoftDocs/visualstudio-docs-pr#6386, and "Get started with Live Unit Testing" updated in MicrosoftDocs/visualstudio-docs-pr#6373

**Comment by kendrahavens** [comment]
Since we are tracking code coverage on the new internal issue, https://github.com/MicrosoftDocs/visualstudio-docs-pr/issues/6300, I'll go ahead and close this. @Mikejo5000 Thank you for your work!
