### ISSUE TITLE
Unrecognized Database format

### ISSUE THREAD

**Issue by TrevCan** [MicrosoftDocs/visualstudio-docs#3689]
![image](https://user-images.githubusercontent.com/44383325/61998648-a73f0500-b078-11e9-9246-81350d4941d8.png)

**Comment by msebolt** [comment]
@TrevCan  Thank you for the feedback.

It appears you are trying to open an Access database file in Visual Studio, a feature currently unsupported at this time.

Please try the [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) to have this added in a future release.
