### ISSUE TITLE
Migration Inquiry: 2008 to 2019

### ISSUE THREAD

**Issue by pawtonyjack** [MicrosoftDocs/visualstudio-docs#3691]
Hi!

We have a working application that was developed using VS 2008 (VB with Crystal Report Basic for VS 2008), with a back-end using SQL Server 2008. Upon reading this article, we assumed there could be minor to none compatibility issues once an old version is migrated to the latest one. Still, we would like to seek professional guidance from you. What could be the compatibility issues we could encounter if we migrate from 2008 to 2019? 

Thank you so much for your help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3315d1-e6d3-e86d-9cce-1ff9ce0fc482
* Version Independent ID: ae3fd143-bf0b-4cfe-bcad-557eb41fdc2c
* Content: [Port, migrate, and upgrade projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2019#feedback)
* Content Source: [docs/porting/port-migrate-and-upgrade-visual-studio-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/porting/port-migrate-and-upgrade-visual-studio-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@pawtonyjack Thank you for the question.

Crystal Reports is [no longer directly supported](https://support.microsoft.com/en-us/help/317789/support-for-crystal-reports-for-visual-studio) in Visual Studio and is now supported with the [SAP extension](https://marketplace.visualstudio.com/items?itemName=SAP.CRforVS) from the Visual Studio marketplace.

Also, please consider downloading the [latest preview](https://visualstudio.microsoft.com/vs/preview/) of Visual Studio and [latest version](https://www.microsoft.com/en-us/sql-server/sql-server-2019) of SQL Server (you can refer to the [SQL Server upgrade](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/upgrade-sql-server?view=sql-server-2017) documentation), before the upgrade.
