### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by echuck66** [MicrosoftDocs/visualstudio-docs#3692]
What do you do when your existing Azure app services do not show up and when creating a new one creates a new service, but will not publish. All attempts to publish the web app result in a 405 (Method not allowed) error. This worked before with vs2019, and I had no issues in vs2017, but has since stopped working in vs2019.

I really wish Microsoft would proof their code a bit better before releasing it. This version of VS for the Mac is REALLY buggy and REALLLLLLLLLLYYYYYYYYY SLLOOOOOOOOOWWWWW

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92da5d51-dd0e-f62e-c453-8bdaafe04776
* Version Independent ID: 645d4899-f7c6-ffcd-53fa-3b6fb64be765
* Content: [Publish to Azure App Service - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-app-svc?view=vsmac-2019#feedback)
* Content Source: [mac/publish-app-svc.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-app-svc.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by msebolt** [comment]
@echuck66 Thank you for the feedback, we appreciate it.

To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

The report is then listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/) and allows you to engage directly with the engineering team as they address and fix the problem.

**Comment by echuck66** [comment]
Please explain why you closed this without providing a working solution or even a comment about what is wrong... It's starting to look like everyone is closing tickets because you have no desire to crack open a rabbit hole of problems..

**Comment by msebolt** [comment]
@echuck66 Please provide a specific example and I will re-open the issue and have the engineering team diagnose.

**Comment by echuck66** [comment]
I have reported bugs via Visual Studio. What do you need? Log files? Screenshots? Azure portal info? Please elaborate. 

If you google issues for publish to Azure and look for '405 Method Not Authorized', or Azure App Services do not show up in the list, or any variety of publishing issues, you'll find ticket after ticket that was closed with no explanation of the cause or a solution. 

I run a development firm and we are deciding on a development platform going forward, getting ready to purchase hardware and software, but we cannot get the basic functions to work as advertised and it's making it very difficult to recommend either Visual Studio (Mac) or Azure.

**Comment by echuck66** [comment]
At a very minimum, this documentation should provide links to troubleshooting guidance, lists of issues related to the deployment process, and what to do if things don't go as advertised. This documentation is nothing but a happy-path scenario.

**Comment by msebolt** [comment]
@echuck66 Okay, let's have the article re-tested then.

**Comment by sayedihashimi** [comment]
Hi @echuck66, I'm sorry that you are running into these issues. I'm a PM working in this area. I'd like to get more info to see what's going on. If you have some time, perhaps we can have a quick meeting so that I can see what you're experiencing. Please email me at sayedha at MICROSOFT dot COM.

**Comment by echuck66** [comment]
Thank you. It appears as if the problem was the App Service OS type. I had chosen Linux, and those services never displayed in Visual Studio (Mac). Once I created Windows app services, I was able to see and deploy to them. It took a while last night, but I was able to get things configured.

I was suggesting someone add some type of FAQ or troubleshooting guide because I see a lot of people had the same type of issues and the tickets were just closed with no real explanation.

Thanks,

Charlie

**Comment by WarBorg** [comment]
I am also having the same issue, I am running VS for Mac 8.5.1 and the Azure services running on Linux are not displayed and when I try to make a .net core web api service with .net core 3.1 on the Azure portal it allows me to choose only Linux as operating systems, this is very odd

**Comment by echuck66** [comment]
I quit Azure. Terrible platform.

**Comment by sayedihashimi** [comment]
We do not support publishing to Linux App Service instances yet. It is on our backlog, but we are still working through some more fundamental issue at the moment. Sorry about that.

**Comment by WarBorg** [comment]
@sayedihashimi ok, understood that, maybe add this info somewhere in the docs, but  still a question is left unanswered, why can't I create a web api app running core 3.1 on a windows server on the azure portal? any thoughts on that? the windows button is disabled :(

**Comment by sayedihashimi** [comment]
@WarBorg sounds good, I will get it updated.

@bradygaster you familiar with the new issue that WarBorg bring up?
> why can't I create a web api app running core 3.1 on a windows server on the azure portal?

**Comment by bradygaster** [comment]
@sayedihashimi there was a known and long-running issue in which the .NET 3.1 SDK wasn't installed on App Service. That has been mitigated. It's there now so publish should work for folks.
