### ISSUE TITLE
Code Analysis settings is deprecated?

### ISSUE THREAD

**Issue by baruchiro** [MicrosoftDocs/visualstudio-docs#3695]
> NOTE: This property page has been deprecated and will be removed in a future product release.

![image](https://user-images.githubusercontent.com/17686879/62149116-aff73b80-b303-11e9-8b3c-4e2d6180427c.png)

VS 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111c5e43-7341-3c2a-3130-e11aa0e0af50
* Version Independent ID: db4f1bef-94ee-0ce1-6b13-9966364b498b
* Content: [Configure Code Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-configure-code-analysis-for-a-managed-code-project?view=vs-2019)
* Content Source: [docs/code-quality/how-to-configure-code-analysis-for-a-managed-code-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-configure-code-analysis-for-a-managed-code-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Yes, the settings page you referenced does not apply to the new code analyzers. Please see https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019#roslyn-analyzers-vs-static-code-analysis for more details about legacy vs. current code analysis.

**Comment by mark-monteiro** [comment]
@gewarren The documentation page referenced in this ticket is for configuring RuleSets for code analysis, which is still used by the new code analyzers.

The page has a section "Specify rule sets for multiple projects in a solution", but the instructions detailed there do not work if you are using the new analyzers.

That section of the documentation should be updated to say that you cannot specify a RuleSet at the solution level if you are using the new analyzers (or provide alternative instructions on how to do this when working with the new analyzers)
