### ISSUE TITLE
Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsExtensionWithDebugInfo' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by caojinqin** [MicrosoftDocs/visualstudio-docs#3698]
I can't generate Controllers in EF Power Tools.

Could not load type 'Microsoft.EntityFrameworkCore.Infrastructure.IDbContextOptionsExtensionWithDebugInfo' from assembly 'Microsoft.EntityFrameworkCore, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

My csproj file:

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.0.0-preview7.19362.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.0.0-preview7-19378-04" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WuBai.Model\WuBai.Model.csproj" />
  </ItemGroup>

</Project>

VS2019

**Comment by msebolt** [comment]
@caojinqin We're sorry to hear you're having issues.

This appears to be an issue with [fixed with version 6 preview](https://stackoverflow.com/questions/56999602/could-not-load-type) of `EntityFrameworkCore.SqlServer`.

**Comment by hodzanassredin** [comment]
Just note about the same problem in ef core 3.1.5. Fixed by removing package Microsoft.EntityFrameworkCore.SqlServer.Design
