### ISSUE TITLE
Vertical scroll bar in VS VB

### ISSUE THREAD

**Issue by stewl** [MicrosoftDocs/visualstudio-docs#3699]
I can not find information about the various indicators in the vertical scroll bar. I see larger and smaller grey rectangles, smaller green and red and orange rectangles of various heights - some of them are distributed in three vertical rows within the scroll bar. And a thin horizontal line.  
I did see a help page that said orange blocks could indicate searched and/or replaced items.
Please explain how to interpret the rest of these.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47f44d8d-2cab-51ac-b09a-be8732fd910a
* Version Independent ID: 8c36fc48-9339-227a-2ea3-f17b8bdcb64e
* Content: [Options, Text Editor, All Languages, Scroll Bars - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-all-languages-scroll-bars?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/options-text-editor-all-languages-scroll-bars.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-all-languages-scroll-bars.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@stewl Thank you for the feedback.

Please see [this blog post](https://blogs.msdn.microsoft.com/cdnstudents/2014/01/21/visual-studio-tips-and-tricks-enhanced-scroll-bar/) for more information, which has now been added to the documentation for further reference.
