### ISSUE TITLE
Expand on FAQ - LSP Extension for Existing Languages

### ISSUE THREAD

**Issue by mklosterboer** [MicrosoftDocs/visualstudio-docs#3700]
One of the FAQ's in the article below mentions that LSP language server extensions are not intended for tasks such as Linting, but provides no alternative route. 

If trying to extend already supporting languages for linting, is there a recommended path? If so, could this be added to the FAQ?

In my case, I'm researching creating an extension to add support for .ts and .tsx file extensions for the already present ESLint features. I came across this article which mentions this specifically but has no suggested path. 

Not a huge issue and I will continue looking, just thought I would give some feedback. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff91657a-173a-0013-62e4-e7c8531b8240
* Version Independent ID: 27988cad-5114-41e3-c48a-357431af0fe1
* Content: [Adding a Language Server Protocol extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2019#feedback)
* Content Source: [docs/extensibility/adding-an-lsp-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@mklosterboer Thank you for the question.

As the article states, it's best to [extend a supported language](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-editor-and-language-services?view=vs-2019) and determine which editor feature you want to support the Linting.

Please check out [editor and extension points](https://docs.microsoft.com/en-us/visualstudio/extensibility/language-service-and-editor-extension-points?view=vs-2019) for the list of code editor features supported.  For example, if you wanted to build an JS Linter via Intellisense, you would refer to [Extending JavaScript intellisense](https://docs.microsoft.com/en-us/visualstudio/ide/extending-javascript-intellisense?view=vs-2015), though documentation this specific is currently limited.

**Comment by msebolt** [comment]
...or consider the [VS Code Extension API](https://code.visualstudio.com/api).
