### ISSUE TITLE
Provide actual direct download links!

### ISSUE THREAD

**Issue by rnburn** [MicrosoftDocs/visualstudio-docs#3701]
The links provided don't actually provide the file. If someone wants to install via the command line, it's likely that they'll also want to download from the command line.

Please prove a link so that you can run
curl -O &lt;link&gt;
and get the actual installer. 

The links mentioned just give a mess of html.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@rnburn Thanks for your feedback. Currently, we provide access to the bootstrapper via the https://visualstudio.microsoft.com/ web page. The **[Create an offline installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)** page includes direct download URLs for specific editions. And, the command-line process is further outlined in the "[Use the command-line to create a local cache](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019#use-the-command-line-to-create-a-local-cache)" section of this page.
