### ISSUE TITLE
Error using selected REPL back-end / IPython 0.11 or later required

### ISSUE THREAD

**Issue by jcridgeNATS** [MicrosoftDocs/visualstudio-docs#3702]
The following community suggestion 
https://github.com/microsoft/PTVS/issues/5279
fixes the unexpected error that occurs under the REPL Step 3.3
i.e.
"Error using selected REPL back-end:
IPython mode requires IPython 0.11 or later: No module named 'IPython'
Using standard backend instead"

etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 781f50f5-dc28-6776-71e9-c3cfbcb87ff4
* Version Independent ID: 8d7da87c-b17d-d3d2-aacd-3242e632b652
* Content: [Python in Visual Studio tutorial step 3, interactive REPL](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl?view=vs-2019#feedback)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by msebolt** [comment]
@jcridgeNATS Thank you for the feedback.

Your change has been added to the documentation.
