### ISSUE TITLE
Differentiate between PublishURL and PublishDir

### ISSUE THREAD

**Issue by penenkel** [MicrosoftDocs/visualstudio-docs#3708]
As far as I can tell, the Wizard populates and uses the *PublishURL* parameter to specify the output location. The msbuild command on the other hand seems to ignore *PublishURL* and instead requires the use of *PublishDir*. This really should be mentioned here especially as it conflicts with the information provided in step 4 and 5 of "To reproduce the build from the command line". (Using VS 16.2)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1672c325-b08a-dbc0-0e3e-31c832753613
* Version Independent ID: c479d585-37bb-795d-1e1c-4833c2262db6
* Content: [Building ClickOnce Applications from the Command Line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2019#feedback)
* Content Source: [docs/deployment/building-clickonce-applications-from-the-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/building-clickonce-applications-from-the-command-line.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@penenkel Thank you for the feedback.

A note has been added to the documentation to help clarify.

**Comment by HughWarrington** [comment]
As of now, `msbuild /t:publish` seems to ignore both `PublishUrl` and `PublishDir` set in your publish profile.
