### ISSUE TITLE
cant' downlod the "PeopleTrax Sample" application

### ISSUE THREAD

**Issue by dengyakui** [MicrosoftDocs/visualstudio-docs#3709]
it's link was correct, and can'd find the application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 436e19f7-ac7c-0f0e-f128-2ec79336d192
* Version Independent ID: fa1e33fa-51a5-8d77-7005-f28b1bd4db47
* Content: [Walkthrough: Command-Line Profiling Using Sampling - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/walkthrough-command-line-profiling-using-sampling?view=vs-2019#feedback)
* Content Source: [docs/profiling/walkthrough-command-line-profiling-using-sampling.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/walkthrough-command-line-profiling-using-sampling.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@dengyakui  Thank you for the feedback.

It appears [PeopleTrax](https://archive.msdn.microsoft.com/VSTS2010B1PeopleTrax) is no longer available.  Re-assigning this to the author.

**Comment by Mikejo5000** [comment]
Scenario is only supported in VS 2017, not VS 2019, and sample is unavailable. Will remove this topic and redirect.

**Comment by Mikejo5000** [comment]
Removed this page
