### ISSUE TITLE
Double-click a file in the Changes list to open a diff view for that file: / DID NOT SHOW CONTENT in 2nd pane

### ISSUE THREAD

**Issue by jcridgeNATS** [MicrosoftDocs/visualstudio-docs#3710]
If I DO NOT commit the changes in Step4, I DO have a file to double click on as per the diagram. However, the comparison of 2 files side by side does not seem to work as expected. I DO get some sort of split pane but there is no content in the RHS pane.

If I do COMMIT the changes in Step4, I do NOT have a file to double click on as per the diagram. In general I would slightly re-word step 4 to ensure that the reader is left in no doubt about how to reproduce the outcomes etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2103a566-905f-f3a1-08b6-a07d076398ad
* Version Independent ID: 926343f9-0e59-1991-473c-f604ab369eb5
* Content: [Python in Visual Studio tutorial step 6, work with Git](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by msebolt** [comment]
@jcridgeNATS Thank you for the feedback.

Our apologies on the delay on this, re-assigning to the author for investigation.

**Comment by JoshuaPartlow** [comment]
Hi @jcridgeNATS - Thanks for your feedback. Just to confirm, is the confusion that the step doesn't:
1.Talk about making a code file change that will result in a diff (the #Add a comment is only shown in the image)
2. Make it clear that the diff view image is meant to be prior to making the commit

**Comment by jcridgeNATS** [comment]
Hi Josh, It's been a while since I made the comment and I don't have access to VS at this moment, but looking again at : 
-----
Step 6: Work with Git > (4) Select Changes (or the Git control with the pencil icon) to review uncommitted changes and to commit them when desired.
-----

the confusion arises I think because I think it would have been better to leave it as just the "review" element i.e.

----------
"Step 6: Work with Git > (stage 4a) Select Changes (or the Git control with the pencil icon) to review uncommitted changes"
----------
which I believe would allow the use to see the split pane for example "CosineWave.py" HEAD and the un-committed changed code.

Then add a new sub-stage 4b 
----------
Step 6: Work with Git > (4b) Select Changes (or the Git control with the pencil icon) to commit changes when desired.  
----------

**Comment by JoshuaPartlow** [comment]
Closing given time open. If you believe this is still an issue that should be addressed, please feel free to reopen.
