### ISSUE TITLE
CA1707 - Microsoft should ensure their code adheres to all FxCop rules.

### ISSUE THREAD

**Issue by DrGriff** [MicrosoftDocs/visualstudio-docs#3714]
Using the latest Roslyn FxCop analyzers and for my MvcApplication class it's complaining about the methods:
protected void Application_Start()
protected void Application_End()

Suggest Microsoft follow these rules....
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06cee199-3ccc-7575-2c1d-296e2714a16e
* Version Independent ID: 2be241bf-b98a-5088-1e1b-0e39b1384b9a
* Content: [CA1707: Identifiers should not contain underscores - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1707-identifiers-should-not-contain-underscores?view=vs-2019)
* Content Source: [docs/code-quality/ca1707-identifiers-should-not-contain-underscores.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1707-identifiers-should-not-contain-underscores.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@DrGriff Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
