### ISSUE TITLE
Incorrect values for Severity drop down

### ISSUE THREAD

**Issue by irongut** [MicrosoftDocs/visualstudio-docs#3718]
"For each code style setting on this page, you can set the Preference and Severity values using the drop-downs on each line. Severity can be set to None, Suggestion, Warning, or Error."

In VS2019 v16.2 the options available in the Severity drop-down are: Refactoring Only, Suggestion, Warning, Error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faebd126-53cd-1a98-bf75-38225933b0f2
* Version Independent ID: 4340fcba-6779-68d2-6c51-2ae37123dc26
* Content: [Code style options and code cleanup - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#feedback)
* Content Source: [docs/ide/code-styles-and-code-cleanup.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-styles-and-code-cleanup.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mikadumont Should None be changed to Refactoring Only?

**Comment by msebolt** [comment]
@irongut  Thank you for the feedback.

The documentation has been updated.

**Comment by TobiasKnauss** [comment]
you should also change other occurences of "None".
