### ISSUE TITLE
Missing option: Open SDK-Style Project files

### ISSUE THREAD

**Issue by AlthalusDGr8** [MicrosoftDocs/visualstudio-docs#3719]
There is a missing explanation of the open SD-style project files with double-sclick or the Enter key

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28461613-82d6-e8f7-7f12-da24a594775d
* Version Independent ID: d7758211-e43d-9fca-4ca2-52be17a7cd63
* Content: [Projects and Solutions, Options dialog box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/projects-and-solutions-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Projects.General)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.1)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/ide/reference/projects-and-solutions-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/projects-and-solutions-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@AlthalusDGr8  Thank you for the feedback.

The missing option is in part due to that this is currently in **Visual Studio 2019 Preview**.  For now see the [Visual Studio 2019 release notes](https://docs.microsoft.com/visualstudio/releases/2019/release-notes) for information on this.

Re-assigning to the author.

**Comment by StingyJack** [comment]
@msebolt - you may want to check your sources, this checkbox has been available for at least a month or two. 16.1 was the first release that should have had it.

**Comment by gewarren** [comment]
Referring to this option:

![image](https://user-images.githubusercontent.com/24882762/63182288-17e99980-c007-11e9-9b1f-39bce3b13073.png)
