### ISSUE TITLE
Attach Snapshot Debugger failed: System.Net.WebException: The remote server returned an error: (401) Unauthorized

### ISSUE THREAD

**Issue by MegoCs** [MicrosoftDocs/visualstudio-docs#3722]
> Unable to Start Snapshot Debugger - Attach Snapshot Debugger failed: System.Net.WebException: The remote server returned an error: (401) Unauthorized.
>    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRequest.<GetResponseInternal>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRequest.<GetResponseInternal>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRequest.<GetResponse>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.<<GetAzureAppServiceAsync>b__99_0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.<ExecuteWithRetryTokenRefresh>d__101`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.<GetAzureAppServiceAsync>d__99.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.ProductionDebug.Utilities.Communication.AzureRMCommunicationClient.<InitializeSessionConfig>d__42.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.VisualStudio.ProductionDebug.DebugSession.ProductionDebugSession.<StartSessionAsync>d__41.MoveNext()

the docs to make sure you are authorized to the resource select from existing and select you app service. and i did. also i was able to open it from cloud explorer menu.

**Comment by msebolt** [comment]
@MegoCs Thank you for the feedback.

Due to the nature of this request, it helps to have an associated article for reference.

Please attach at your earliest convenience.
