### ISSUE TITLE
data has null item values

### ISSUE THREAD

**Issue by tadamkewicz** [MicrosoftDocs/visualstudio-docs#3724]
the page source shows that the item values are empty hence no image is displayed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa65a08-a9e2-721d-e00c-1f28afffe2be
* Version Independent ID: babf20c3-c235-d839-7340-fb9c11c449dc
* Content: [Create a Node.js and Express app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@tadamkewicz Do the pictures show when you click the buttons? The URLs appear to be valid.

**Comment by tadamkewicz** [comment]
No but I figured it out finally. My call to getData didn't have () but I
didn't get a syntax error, something I think should be there.

**Comment by Mikejo5000** [comment]
Updating doc
