### ISSUE TITLE
Separate header for code cell section

### ISSUE THREAD

**Issue by joelostblom** [MicrosoftDocs/visualstudio-docs#3725]
It would be great if the last two paragraphs under the "Send to interactive" heading (just under the Tip div) had their own heading and anchor point so that it can be linked directly. The header could be "Code cells" or "Working with code cells". 

Additionally, organizing code in cells has many more applications than just using it as a scratch pad. It is common in exploratory data analysis and helps organize separate analysis sections, and it is supported by many editors. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a426e3db-8d10-e7d2-0957-5eb07d28e76d
* Version Independent ID: e54ea195-0592-0424-a5b1-54dba78257e4
* Content: [Python interactive window (REPL) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/python-interactive-repl-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/python-interactive-repl-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/python-interactive-repl-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by msebolt** [comment]
@joelostblom Thank for your feedback.

Your suggestions have been added to the documentation.
