### ISSUE TITLE
Advice on how to implement comparison operators for a type whose CompareTo is inconsistent with Equals

### ISSUE THREAD

**Issue by peteroupc** [MicrosoftDocs/visualstudio-docs#3728]
This page should include advice on how comparison operators should be implemented in the following circumstance.

- A custom number class (not from the base class library) represents a number by its significand and exponent.
- It overrides Object.Equals with a method that compares the significand and exponent for equality.
- It has a CompareTo method that does a numerical comparison of the two numbers, which is a non-total ordering that is inconsistent with Equals.
- It implements the "&lt;", "&lt;=", "&gt;=", and "&gt;" operators to do comparisons that are consistent with CompareTo.

Should it implement the "==" and "!=" operators to be consistent with Equals or with CompareTo, or should it refrain from implementing those operators?

What if CompareTo instead does a total ordering of the two numbers (making it consistent with Equals)?  Can it implement the "&lt;", "&lt;=", "&gt;=", and "&gt;" operators to do a numerical comparison rather than a total ordering, if a numerical comparison makes more sense?  If so, should the "==" and "!=" operators be implemented to be consistent with Equals, with a non-total comparison, or with a total ordering comparison, or not be implemented?

For the purpose of this issue, an example of the number class is found in my library's EDecimal class ([EDecimal.cs](https://github.com/peteroupc/Numbers/blob/master/Numbers/PeterO/Numbers/EDecimal.cs), [EDecimalExtra.cs](https://github.com/peteroupc/Numbers/blob/master/Numbers/PeterO/Numbers/EDecimalExtra.cs)), except that it doesn't implement the "&lt;", "&lt;=", "&gt;=", and "&gt;" operators at the time of this writing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d1a8f14-3432-06fa-4984-a27f8aba771d
* Version Independent ID: 7e6abc8c-264f-13dd-ddd2-bb875eb8316c
* Content: [CA1036: Override methods on comparable types - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1036)
* Content Source: [docs/code-quality/ca1036-override-methods-on-comparable-types.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1036.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@peteroupc  Thank you for the question.

You should be overriding [Equals](https://docs.microsoft.com/dotnet/api/system.object.equals) when there is any doubt between the two.

With the aforementioned inconsistencies in the [Equals](https://docs.microsoft.com/dotnet/api/system.object.equals) and [CompareTo](https://docs.microsoft.com/dotnet/api/system.icomparable.compareto) implementations, I would suggest moving the issue to the [dotnet-api-docs repo](https://github.com/dotnet/dotnet-api-docs/issues).

Re-assigning to the author.

**Comment by peteroupc** [comment]
I have edited the opening post to clarify the following:

- The number class in question is a custom written number class, not one from the base class library.
- The number class overrides Object.Equals with a method that compares the significand and exponent for equality.

The question is whether to implement "<", "<=", ">=", and ">" operators, and/or the  "==" and "!=" operators, in certain circumstances, not whether to override the Equals method.

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved to .NET
Closing this issue in favor of [https://github.com/dotnet/docs/issues/22044](https://github.com/dotnet/docs/issues/22044)
