### ISSUE TITLE
Usability and notifications

### ISSUE THREAD

**Issue by staff0rd** [MicrosoftDocs/visualstudio-docs#3730]
Navigation and alerting of responses of a current issue could be more user friendly.  For example see [this issue](https://developercommunity.visualstudio.com/content/problem/613157/new-cron-schedule-not-working.html).  The latest information pertinent to the issue is hidden at the bottom - I need to scroll down to the bottom of the page, expand the comments on the _Solution_ and scroll down to the bottom of the page again.

When I get an email notification of a response on the solution thread, the email includes a link with a button that claims to navigate directly to the newly created comment, like [this one](https://developercommunity.visualstudio.com/content/problem/613157/new-cron-schedule-not-working.html?childToView=678047#comment-678047), however, that just navigates me to the top of the page and I have to wade through the content again to get to the latest comment.

Tested on Windows 10 Chrome 75, Edge 44 &  iOS 12 Safari.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-nz/visualstudio/ide/report-a-problem?view=vs-2019)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by WilliamAntonRohm** [comment]
@staff0rd  It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​

**Comment by WilliamAntonRohm** [comment]
@staff0rd -- I misunderstood your question.  We are looking into your issue.

**Comment by staff0rd** [comment]
Upon re-reading I can also see that my context at the tine was not inferred with my explanation.

To be clear, this is feedback about the usability and design of the developer community site itself, and not about the products the site collects feedback for.  I could not find a better place to submit it, if there is one please advise.

**Comment by seaniyer** [comment]
@staff0rd 

Thanks for taking the time to share your input.  I checked the issue you provided as an example and understand the problem you have brought up.  We'll account for it in future site improvements.  

By the way, if you have any other feedback on the Developer Community site, best place to share it is on the site itself.  You can suggest a feature (under Visual Studio is fine) and provide your input.  It will get routed to my team.

Thanks!
Sean
Visual Studio Feedback Team
