### ISSUE TITLE
Warning not emited in .NET Core 2.2

### ISSUE THREAD

**Issue by Rimobul** [MicrosoftDocs/visualstudio-docs#3732]
I have the following code, which should emit a warning, but does not:

```
public interface IMyDisposable : IDisposable
{
    bool IsItFalse();
}

public class MyDisposable : IMyDisposable
{
    public void Dispose()
    {
        return;
    }

    public bool IsItFalse()
    {
        return false;
    }
}

public class Consumer
{
    public IMyDisposable CreateMyDisposable()
    {
        return new MyDisposable();
    }

    public bool Foo()
    {
        // Should display CA2000 warning, but does not
        var myDisposable = CreateMyDisposable();
        return myDisposable.IsItFalse();
    }
}
```

I have tested it on Windows 10 and .NET Core 2.2, both in Microsoft Visual Studio and JetBrains Rider. No warning appears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c370a407-b61d-0de6-6ac4-9b0ab49216b9
* Version Independent ID: a96e421e-65d3-07ba-097e-3feff2b3c677
* Content: [CA2000: Dispose objects before losing scope - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2000-dispose-objects-before-losing-scope.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2000-dispose-objects-before-losing-scope.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Rimobul A better place to log this issue is on the roslyn-analyzers repo at https://github.com/dotnet/roslyn-analyzers/issues. You might search for it first too. Thanks for helping us improve the developer experience. (This repo is for documentation issues.)
