### ISSUE TITLE
Add guide to update layout when android sdk version changed

### ISSUE THREAD

**Issue by mmaier2307** [MicrosoftDocs/visualstudio-docs#3733]
As described in this issue https://developercommunity.visualstudio.com/content/problem/662829/layout-update-from-build-tools-1616-to-1620-failed.html# there is a problem updating a layout if the included android sdk version changed. The layout updater cant find the old version and fails. This can be fixed using the described workaround.

This should be noted somewhere in this documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc51a257-b7a9-4660-7e12-88cdfcd9cd53
* Version Independent ID: dad2fd97-7244-6802-e853-5d5974838996
* Content: [Update a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/update-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Spaze-Maurice Thanks for contacting us. You might have missed this note in the "How to update a network layout" section of the page, which describes the workaround for the issue that you've linked to. The note reads as follows:

![image](https://user-images.githubusercontent.com/23244653/65552876-6cbbe200-deda-11e9-8c07-e13ba64fe183.png)

Thanks for letting us know, though, about your experience. We'll close this issue now (although it is still viewable from the "Closed" tab, so that others with similar issues can view it, too).

**Comment by Spaze-Maurice** [comment]
I understand that new optional components are not added after updating a layout. But the described workaround does not work. Im not able to "Run a separate modify operation **after** an upgrade" because the upgrade itself is not working.

**Comment by TerryGLee** [comment]
@Spaze-Maurice Thanks for the additional information. We'll investigate further.

**Comment by TerryGLee** [comment]
@tydunkel FYI

**Comment by tobyhu87** [comment]
> I understand that new optional components are not added after updating a layout. But the described workaround does not work. Im not able to "Run a separate modify operation **after** an upgrade" because the upgrade itself is not working. Also i think this note is about installation on the client and not about the layout because the creation of a layout does not take a response file.

Hi @mmaier2307 ,

Can you please share your command line for creating your layout?  and If you still have the client machine where you install VS to; can you please run collect.exe to collect the setup logs?  The logs will tell us why your update failed.

Collect instructions:
1) Download collect.exe from the link https://aka.ms/vscollect 
2) You may choose to save the tool for later use, or to run directly. 
3) The utility creates a compressed cabinet of all the VS and .NET logs to %TEMP%\vslogs.zip. 
4) Share this vslogs.zip with us.

thanks
toby.

**Comment by mmaier2307** [comment]
Hey, thanks for the reply,

I used this command to create the layout (Version 16.1.6):

`vs_buildtools.exe --layout "C:\Users\Administrator\Desktop\vs_buildtools_2019" --lang en-US --includeRecommended --add Microsoft.VisualStudio.Component.Roslyn.Compiler --add Microsoft.Component.MSBuild --add Microsoft.VisualStudio.Component.CoreBuildTools --add Microsoft.VisualStudio.Workload.MSBuildTools --add Microsoft.VisualStudio.Component.TestTools.BuildTools --add Microsoft.Net.Component.4.6.1.SDK --add Microsoft.Net.Component.4.6.1.TargetingPack --add Microsoft.VisualStudio.Component.NuGet.BuildTools --add Microsoft.VisualStudio.Web.BuildTools.ComponentGroup --add Microsoft.Net.Component.4.7.2.SDK --add Microsoft.Net.Component.4.7.2.TargetingPack --add Microsoft.Net.ComponentGroup.DevelopmentPrerequisites --add Microsoft.VisualStudio.Component.TypeScript.3.4 --add Microsoft.Net.Component.4.TargetingPack --add Microsoft.Net.Component.4.5.TargetingPack --add Microsoft.Net.Component.4.5.1.TargetingPack --add Microsoft.Net.Component.4.5.2.TargetingPack --add Microsoft.Net.Component.4.6.TargetingPack --add Microsoft.Net.ComponentGroup.TargetingPacks.Common --add Microsoft.Net.Core.Component.SDK.2.1 --add Microsoft.VisualStudio.Component.DockerTools.BuildTools --add Microsoft.Component.ClickOnce.MSBuild --add Microsoft.VisualStudio.Wcf.BuildTools.ComponentGroup --add Microsoft.VisualStudio.Component.AspNet45 --add Microsoft.VisualStudio.Component.WebDeploy --add Microsoft.Net.Component.3.5.DeveloperTools --add Microsoft.Net.Component.4.6.2.SDK --add Microsoft.Net.Component.4.6.2.TargetingPack --add Microsoft.Net.Component.4.7.SDK --add Microsoft.Net.Component.4.7.TargetingPack --add Microsoft.Net.Component.4.7.1.SDK --add Microsoft.Net.Component.4.7.1.TargetingPack --add Microsoft.Net.Core.Component.SDK.2.2 --add Microsoft.VisualStudio.Workload.WebBuildTools --add Component.OpenJDK --add Component.Android.SDK27 --add Microsoft.VisualStudio.Workload.XamarinBuildTools --add Microsoft.NetCore.BuildTools.ComponentGroup --add Microsoft.VisualStudio.Workload.NetCoreBuildTools --add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --add Microsoft.VisualStudio.Component.VSSDKBuildTools --add Microsoft.VisualStudio.ComponentGroup.VisualStudioExtensionBuildTools.Prerequisites --add Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools --add Microsoft.VisualStudio.Component.NuGet --add Microsoft.VisualStudio.Component.Workflow.BuildTools --add Microsoft.VisualStudio.Component.Sharepoint.BuildTools --add Microsoft.VisualStudio.Component.TeamOffice.BuildTools --add Microsoft.VisualStudio.Workload.OfficeBuildTools --add Microsoft.VisualStudio.Component.SQL.SSDTBuildSku --add Microsoft.VisualStudio.Component.Roslyn.LanguageServices --add Microsoft.VisualStudio.Workload.DataBuildTools`

In the linked developercommunity issue are two logs. But these logs are from the layout update because I never got to the point where i could update on a machine VS was installed on because the layout update failed.

I just tested to update a copy of the layout I fixed using the described workaround back then to get it to version 16.2.0:

> Because you selected a partial layout when you first created the offline layout, those settings are saved in Layout.json file. Any future layout commands use the previous options plus any new options that you specify. So when you updated your layout, --add Microsoft.VisualStudio.Component.TypeScript.3.4 and -add Component.Android.SDK27 are included. But these components are no longer in the latest release (16.2.0), it got replaced by 'Microsoft.VisualStudio.Component.TypeScript.3.5' and 'Component.Android.SDK28'.
Workaround: You can edit the Layout.json file in your offline layout, changing those to 'Microsoft.VisualStudio.Component.TypeScript.3.5' and 'Component.Android.SDK28', then update the layout should be able to work for you.

This worked without any problems. My layout got updated to version 16.6.2

**Comment by ornellaalt** [comment]
Thank you for your feedback! We've added the additional workaround to the documentation. Closing out this issue now.
