### ISSUE TITLE
Live chat will not support VS Build Tools install in containers

### ISSUE THREAD

**Issue by ledettwy** [MicrosoftDocs/visualstudio-docs#3736]
This documentation references a "live chat", but the live chat representative (Oscar Nunez) I was connected to refused to provide assistance with the Build Tools installer.

I started a live chat to ask about which components I needed to include (via --add) in the install in order to get cl.exe, since just Microsoft.VisualStudio.Workload.VCTools doesn't seem to be enough.

"I see, unfortunately as I said before this issue is out of scope due to we only assist with the installation of visual studio (excluding the use of docker container, json files and scripts), the installation of extensions and components such as Build Tools and/or SSDT are out of the scope of this support, however you can check for the information in the developers community forum"

If live chat will not support any of the installation issues that people might be asking about when following these instructions, then the reference to the live chat should be removed from these pages so developers do not waste time.

Thanks,
- Lisanna

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by Raviuppa** [comment]
Hi Lisanna,
   Sorry for the inconvenience caused to you. There appears to be some confusion regarding the support which is resulted in conveying the message from Oscar. If you are trying to install and get help for stand alone Build Tools for Visual Studio package installation then yes, that support is out of scope of VS Setup Chat support. Perhaps that might have been communicated to you but we are looking into it to avoid any confusion such as documentation and links etc.. . Thank you for bringing this to our attention. 

Regarding the question you have about the workload to add to get cl.exe, please do chose "Desktop Development With C++" workload from VS Setup Installation Window, and then selecting any build tool components will have cl.exe installed as part of Platform Tool Set. That includes, Compilers, Linker and other build tools. For more information about what component includes cl.exe, you can refer the "**[Microsoft C++ tool set usage from Command Line](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=vs-2019)**" doc.
 
Please try the above option and let us know if that answered and resolved your issue.

**Comment by ledettwy** [comment]
Hi Raviuppa,

Thanks for the response. I was able to determine the components I needed for my project.

Thanks!
