### ISSUE TITLE
Unclear how to configure this inspection from an .editorconfig file

### ISSUE THREAD

**Issue by r-k-b** [MicrosoftDocs/visualstudio-docs#3737]
With Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.4 installed to a project, it's not clear what naming is expected within the project's .editorconfig file to configure the severity of CA1507.

These don't seem to work:

```
[*.cs]
dotnet_code_quality.CA1507.severity = error
csharp_use_nameof_in_place_of_string_analyzer = true:error
CSharpUseNameofInPlaceOfStringAnalyzer = true:error
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b712c22f-88cd-12ee-395f-c082368a9c4c
* Version Independent ID: 43d36c34-3194-1d80-9b68-d426ca907fb9
* Content: [CA1507: Use nameof instead of string - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1507?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1507.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1507.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@r-k-b Which version of Visual Studio are you using? Configuring analyzer rules using EditorConfig isn't supported in Visual Studio version 16.2.

**Comment by r-k-b** [comment]
@gewarren 16.1.3, but I'm not expecting it to show in VS yet - I was checking the build output from msbuild (which is 16.1.76+g14b0a930a7 ... are msbuild & VS versions tied together?)

**Comment by gewarren** [comment]
@mavasani Is it possible to configure the severity of FxCop rules from .editorconfig for command line builds?

**Comment by mavasani** [comment]
> Is it possible to configure the severity of FxCop rules from .editorconfig for command line builds?

This should be possible _very soon_ once Visual Studio VS2019 16.3 is released. You should be able to use the following syntax in your editorconfig file:

```
[*.cs]
dotnet_diagnostic.CA1507.severity = error
```
