### ISSUE TITLE
Documentation wording on expected result is unclear

### ISSUE THREAD

**Issue by VeXHarbinger** [MicrosoftDocs/visualstudio-docs#3738]
The [page ](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2019)reads;

> Like MSBuild properties, targets can be redefined. For example,
> _Code Snippet_
> 
> **If AfterBuild executes, it displays only "Second occurrence".**
> MSBuild is import-order dependent, and the last definition of a target is the definition used.

My question is on that next to last line.  Is it asking us "If we see only the 2nd message" as a debugging step? 
Or should the text be stating that you will only see the 2nd message? 

I don't know the answer myself, as of yet, but thought I'd log it to help the next person to stumble upon it.

**Comment by ghogen** [comment]
The point that the second definition of AfterBuild overrides the first, so you don't see "First occurrence" in the output, only "Second occurrence."
