### ISSUE TITLE
Doesn't tell me how to access the build log

### ISSUE THREAD

**Issue by vhe1** [MicrosoftDocs/visualstudio-docs#3739]
The doc doesn't actually tell me how to "obtain" the log, i.e. how it's named and where it is in the solution.
Example: So I've set the build verbosity to "Detailed":
![grafik](https://user-images.githubusercontent.com/12475356/62639422-c3c42280-b93f-11e9-9e38-3bb19933f0f0.png)
Now I click on "Build -> Rebuild solution" in the top menu bar of visual studio.
Now what? There is nothing called *.log or similar in the solution directory or its project directories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab4c199-c44d-b8c6-9bf5-5500a30a6992
* Version Independent ID: ed692025-4ede-d7f1-be2f-6ee1f8ce16eb
* Content: [Obtaining Build Logs with MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019#feedback)
* Content Source: [docs/msbuild/obtaining-build-logs-with-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/obtaining-build-logs-with-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@vhe1  Thank you for the question.

In general, build files (including logs) are located in the project's *Debug* folder (see [How to: View, Save, Configure Build Files](https://docs.microsoft.com/visualstudio/ide/how-to-view-save-and-configure-build-log-files)).

Also note this is only supported with C++ projects.  Other projects will require you to either run **msbuild** from the command-line (with the appropriate options set), or use **Ctrl+S** in the **Output** window.
