### ISSUE TITLE
Example potentially misleading

### ISSUE THREAD

**Issue by tene666** [MicrosoftDocs/visualstudio-docs#3743]
Example code has an incorrect property and description that may be misleading:

"The following example uses the SignFile task to sign the files (...) with the certificate specified by the Certificate property." 

However, CertificateThumbprint specifies the certificate to use for signing. This certificate must be in the current user's personal store.

So you have to use this param to provide thumbprint of cert installed in the personal store of current user, so the Certificate property is obsolete / not used.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09ffd23-115c-368b-c17f-7d3af54f0a67
* Version Independent ID: b640eb45-9978-0a9e-f8dc-fd2581e84fb5
* Content: [SignFile Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/signfile-task?view=vs-2019)
* Content Source: [docs/msbuild/signfile-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/signfile-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
Thanks for the feedback. Replaced "Certificate" with "CertificateThumbprint."
