### ISSUE TITLE
release notes typo

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/visualstudio-docs#3744]
I couldn't find the source file in this repo (otherwise I would've sent a PR), but I hope I am in the right place to report.

On page https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes there is a type: "thier" instead of "their" 

![typo](https://user-images.githubusercontent.com/1635825/62661191-a0659b80-b970-11e9-90dd-f86d17c395c9.png)

**Comment by TerryGLee** [comment]
@Styxxy I've passed your report on to the correct folks; thanks for helping us improve our documentation!
