### ISSUE TITLE
Add documentation for new Performance rules CA1827 and CA1828 (DoNotUseCountWhenAnyCanBeUsedAnalyzer) in FxCop analyzers

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#3745]
1. Does not exist in legacy FxCop
2. Rules Implementation:
    * https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetCore.Analyzers/Core/Performance/DoNotUseCountWhenAnyCanBeUsed.cs#L103
3. Rules message and description:
    * https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetCore.Analyzers/Core/MicrosoftNetCoreAnalyzersResources.resx#L231-L239
    * https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetCore.Analyzers/Core/MicrosoftNetCoreAnalyzersResources.resx#L1113-L1121
4. Unit tests:
    * https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetCore.Analyzers/UnitTests/Performance/DoNotUseCountWhenAnyCanBeUsedTests.Base.cs
    * https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetCore.Analyzers/UnitTests/Performance/DoNotUseCountWhenAnyCanBeUsedTests.Code.cs
    * https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetCore.Analyzers/UnitTests/Performance/DoNotUseCountWhenAnyCanBeUsedTests.Data.cs
    * https://github.com/dotnet/roslyn-analyzers/blob/cda75fffd1087d375452a6f2a725547a9fbf5c5f/src/Microsoft.NetCore.Analyzers/UnitTests/Performance/DoNotUseCountWhenAnyCanBeUsedTests.Tests.cs
5. The analyzers already have the following URLs assigned:
    CA1827: https://docs.microsoft.com/visualstudio/code-quality/ca1827
    CA1828: https://docs.microsoft.com/visualstudio/code-quality/ca1828

## Use cases

detected | fix
-------- | --- 
`enumerable.Count() == 0` | `!enumerable.Any()`
`enumerable.Count() != 0` | `enumerable.Any()`
`enumerable.Count() <= 0` | `!enumerable.Any()`
`enumerable.Count() > 0` | `enumerable.Any()`
`enumerable.Count() < 1` | `!enumerable.Any()`
`enumerable.Count() >= 1` | `enumerable.Any()`
`0 == enumerable.Count()` | `!enumerable.Any()`
`0 != enumerable.Count()` | `enumerable.Any()`
`0 >= enumerable.Count()` | `!enumerable.Any()`
`0 < enumerable.Count()` | `enumerable.Any()`
`1 > enumerable.Count()` | `!enumerable.Any()`
`1 <= enumerable.Count()` | `enumerable.Any()`
`enumerable.Count().Equals(0)` | `!enumerable.Any()`
`0.Equals(enumerable.Count())` | `!enumerable.Any()`
`enumerable.Count(_ => true) == 0` | `!enumerable.Any(_ => true)`
`enumerable.Count(_ => true) != 0` | `enumerable.Any(_ => true)`
`enumerable.Count(_ => true) <= 0` | `!enumerable.Any(_ => true)`
`enumerable.Count(_ => true) > 0` | `enumerable.Any(_ => true)`
`enumerable.Count(_ => true) < 1` | `!enumerable.Any(_ => true)`
`enumerable.Count(_ => true) >= 1` | `enumerable.Any(_ => true)`
`0 == enumerable.Count(_ => true)` | `!enumerable.Any(_ => true)`
`0 != enumerable.Count(_ => true)` | `enumerable.Any(_ => true)`
`0 < enumerable.Count(_ => true)` | `!enumerable.Any(_ => true)`
`0 >= enumerable.Count(_ => true)` | `enumerable.Any(_ => true)`
`1 > enumerable.Count(_ => true)` | `!enumerable.Any(_ => true)`
`1 <= enumerable.Count(_ => true)` | `enumerable.Any(_ => true)`
`enumerable.Count(_ => true).Equals(0)` | `!enumerable.Any(_ => true)`
`0.Equals(enumerable.Count(_ => true))` | `!enumerable.Any(_ => true)`

Also applies to `LongCount`, `CountAsync` and `LongCountAsync`.

/cc @mavasani

**Comment by mavasani** [comment]
Thank you @paulomorgado

**Comment by mavasani** [comment]
Marking this one as blocked based on https://github.com/dotnet/roslyn/issues/37959#issuecomment-521303539

**Comment by mavasani** [comment]
@gewarren I don't see a label to mark the issue as blocked, but please hold of on adding this documentation until we resolve the above issue offline.

**Comment by WilliamAntonRohm** [comment]
@mavasani -- Manish, please update this issue's status.

**Comment by mavasani** [comment]
Ah sorry. We decided to go ahead with @paulomorgado's original implementation. This issue is now unblocked.

**Comment by WilliamAntonRohm** [comment]
@mavasani -- thank you.
