### ISSUE TITLE
Needs to be updated for vs2019 v 16.2

### ISSUE THREAD

**Issue by realbart** [MicrosoftDocs/visualstudio-docs#3746]
In vs2019 16.2 the settings dropdown menu has moved to the test explorer far right settings gear icon.
please update your screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#feedback)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Kendra, can I assign this to you?

**Comment by kendrahavens** [comment]
@gewarren Yes, feel free!

**Comment by gewarren** [comment]
For 16.3 the Test menu has been fully restored. The screenshot was updated to match 16.3.
