### ISSUE TITLE
Clarity

### ISSUE THREAD

**Issue by zombie-jojo** [MicrosoftDocs/visualstudio-docs#3747]
Suggest change "through a service such as a service" to "through a service" or something which adds value e.g. "through a service such as a Windows service or web service"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59ecf28c-12bc-522d-c919-5c8cb95c8044
* Version Independent ID: 0c528049-bf1c-8b0d-1b6d-3d4f9c1fc970
* Content: [N-Tier Data Applications Overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/n-tier-data-applications-overview?view=vs-2019#feedback)
* Content Source: [docs/data-tools/n-tier-data-applications-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/n-tier-data-applications-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@zombie-jojo Thank you for the feedback.

The documentation has been updated.
