### ISSUE TITLE
Bad Instructions

### ISSUE THREAD

**Issue by MAlabaster** [MicrosoftDocs/visualstudio-docs#3748]
I am trying to use VS2019 Communty to debug a 3rd party app and there is no option as described in the instructions on this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5cc545a-f0ff-2f8a-a20a-e220a5a84c19
* Version Independent ID: d03c8ed7-d691-7b09-be11-c45f3cb739d2
* Content: [Attach to running processes with the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019#feedback)
* Content Source: [docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@MAlabaster Which options was missing? Debug > Attach to Process?

**Comment by MAlabaster** [comment]
Doh! It would help if I installed the whole package, didn't expect to have VB & C# as an add-on.

**Comment by Mikejo5000** [comment]
OK, sounds like you resolved it. Thx!

**Comment by MAlabaster** [comment]
It's a while since I've used VS and it has become a lot more difficult to get started and work out which bits you need
