### ISSUE TITLE
Visual Studio 2019 - for console apps, publishing dialog is missing the "Advanced..." option

### ISSUE THREAD

**Issue by jwatkin** [MicrosoftDocs/visualstudio-docs#3749]
I'm using Visual Studio 2019 (16.2.1) to publish a .NET Core console app to a folder. I want the existing files in the publish target folder to be deleted before the new ones are published there. My understanding is that I'll need to go through the "Advanced..." option to set that target folder file deletion feature. However, unlike what's shown on this page of documentation, the  "Advanced..." button option isn't displayed in my Visual Studio 2019 dialog. If I try publishing a web app instead, then the "Advanced..." button option is available in my VS dialog. If this discrepancy isn't a Visual Studio bug, then perhaps you can warn users on this page about this particular discrepancy between console and web app publishing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7acfded6-bb6d-cf61-0cf0-a4457bbff059
* Version Independent ID: c1974839-4571-e19c-e484-a98e4121e17c
* Content: [Deploy to a local folder - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-local-folder?view=vs-2019)
* Content Source: [docs/deployment/quickstart-deploy-to-local-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/quickstart-deploy-to-local-folder.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@jwatkin Thanks, I'll take a look at that.

**Comment by Mikejo5000** [comment]
It looks like screenshots were updated and I don't see the Advanced option anymore.
