### ISSUE TITLE
editorconfig not honored

### ISSUE THREAD

**Issue by k3davis** [MicrosoftDocs/visualstudio-docs#3750]
I have created essentially the most basic .editorconfig file one can create, and saved it in the root of my project, but Visual Studio doesn't honor it. It _does_ briefly say in the status bar that "user preferences overridden by .editorconfig" but the styles aren't applied.

```
root = true 

# All files 
[*] 
indent_style = space 
indent_size = 4 
insert_final_newline = false
```

When I do Add > Class..., it creates a default class with the newline still there.

I don't care about the specific rule; I'm just trying to figure out how to apply any rule. I'm sure I am missing something obvious, so I'd appreciate grace in answering this question... thanks.

VS 2019 Professional 16.2.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [EditorConfig settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019#feedback)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@k3davis Have you tried to format the document? Edit > Advanced > Format Document or Ctrl+K, Ctrl+D. When you add a new class file, it's coming from a template so it may not format according to your preferences until you do it explicitly.

**Comment by k3davis** [comment]
@gewarren Yes, I should have specified that. Ctrl+K+D doesn't apply any changes to match the .editorconfig file either.

**Comment by k3davis** [comment]
On further investigation I've discovered that it is only the specific rule that isn't being honored:

`insert_final_newline = false`

When I add other, more complex rules, it is working as expected.

**Comment by gewarren** [comment]
@k3davis Thanks for the update. To make sure that this problem is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, you can engage directly with the engineering team while they address and fix the problem.
