### ISSUE TITLE
Custom toolset clarification

### ISSUE THREAD

**Issue by jblanchet** [MicrosoftDocs/visualstudio-docs#3751]
This article states that: "ToolsetConfigurationSection is a custom configuration section that can be used by any MSBuild host for custom configuration. If you use a custom Toolset, a host does not have to do anything to initialize the build engine except provide the configuration file entries. By defining entries in the registry, you can specify computer-wide Toolsets that apply to MSBuild.exe, Visual Studio, and all hosts of MSBuild."

Does setting up the registry entry in this way this still work for Visual Studio 2017 and above or is it just for the earlier versions that still used registry keys? 

Is a custom toolset possible with VS 2017/2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a149d2bb-ccbf-42d8-5ea4-971fe211fdb6
* Version Independent ID: 3bcdf305-4f85-fe4d-24f5-1ce2ecec8d15
* Content: [Standard and Custom Toolset Configurations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/standard-and-custom-toolset-configurations?view=vs-2019#feedback)
* Content Source: [docs/msbuild/standard-and-custom-toolset-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/standard-and-custom-toolset-configurations.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
You can edit the registry with newer versions of Visual Studio by using vsregedit.exe utility.
https://docs.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances?view=vs-2019#editing-the-registry-for-a-visual-studio-instance
You can also use the vsregedit.exe utility, but I see that we should provide some documentation for it.

**Comment by ghogen** [comment]
The info about the registry was out-of-date and I removed that.
