### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by mcbobby123** [MicrosoftDocs/visualstudio-docs#3753]
Microsoft.Build.Tasks.Deployment.ManifestUtilities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e85eb697-fd62-62d1-cc5a-24b4f7f18017
* Version Independent ID: 715fa2ac-cc41-596b-bb07-38b6be492fe7
* Content: [ClickOnce Security and Deployment - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment?view=vs-2019)
* Content Source: [docs/deployment/clickonce-security-and-deployment.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/clickonce-security-and-deployment.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review my changes in the above-mentioned PR 5213

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
