### ISSUE TITLE
Document missing switches and options

### ISSUE THREAD

**Issue by staylorftr** [MicrosoftDocs/visualstudio-docs#3755]
There are some significant differences between this page and the MSBuild command line help. For example...

-warnAsError, -warnAsMessage, -profileEvaluation, -restoreProperty, -isolateProjects and a few more switches are not documented here.
-consoleLoggerParameters can accept a "ForceConsoleColor" option, which is not documented here.

It would be good to bring the docs in line with the command line so the options are searchable on the net. It was more difficult to discover -warnAsError than it should have been.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
This is fixed and should be published later today - thanks for the feedback.
