### ISSUE TITLE
So what comes along with those predefined targets file? I

### ISSUE THREAD

**Issue by goyzhang** [MicrosoftDocs/visualstudio-docs#3756]
I know there are Build, Clean, Rebuild etc. But I haven't seen any docs about these targets or a list of what the common target files provide. Maybe a see also or remark?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c6f7f1d-2f33-e083-f8de-1ecd9f1a4a93
* Version Independent ID: 8aac17e8-5a10-bbbb-4c52-783c9f0c7e10
* Content: [MSBuild .Targets Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-dot-targets-files?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-dot-targets-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-dot-targets-files.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@goyzhang Thank you for the feedback.

Does [Extend the build process](https://docs.microsoft.com/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process) cover the information you're looking for?

**Comment by msebolt** [comment]
Please comment below if there are any further issues.
