### ISSUE TITLE
Description of the usage new command-line code metrics tool is incorrect

### ISSUE THREAD

**Issue by gremlm** [MicrosoftDocs/visualstudio-docs#3758]
For calculating code metrics I have included Microsoft.CodeAnalysis.Metrics 2.9.4 nuget package to my csproj project.
Before executing msbuild from the command line, I have called  "nuget.exe restore", and it correctly found MSBuild and restore package:
"MSBuild auto-detection: using msbuild version '16.200.19.32702' from 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin'.
Restoring NuGet package Microsoft.CodeAnalysis.Metrics.2.9.4. ..."

Then, from command line I am calling msbuild with /t:Metrics option:
"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\MSBuild.exe" /p:Configuration=Debug /t:Metrics My.sln "

which ended with following error:
"Unhandled Exception: System.ArgumentException: Directory "C:\Program Files (x86)\Microsoft Visual Studio\2019\TestAgent\MSBuild\Current\Bin" does not exist
  Parameter name: msbuildPath
     at Microsoft.Build.Locator.MSBuildLocator.RegisterMSBuildPath(String msbuildPath)
     at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()
     at Metrics.Program.&lt;RunAsync&gt;d__1.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)"

It looks like  Metrics.exe looking for msbuild in wrong location, but nugget.exe in correct one. 
Why msbuildPath is set to the wrong location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c654586-8571-cfe1-1ee1-3adaf79e2dcf
* Version Independent ID: 334b3914-dbcd-3ece-26b3-fab7c766a377
* Content: [Generate code metrics from the IDE or command line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2019)
* Content Source: [docs/code-quality/how-to-generate-code-metrics-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-generate-code-metrics-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@gremlm  We're sorry you're experiencing difficulties.

Please try solution posted on issue https://github.com/Microsoft/azure-pipelines-agent/issues/902 while we work on getting this resolved.

**Comment by gremlm** [comment]
Thank you for quick response, but that approach won't work for MSBuild 16. Before MSBuild was installed in the GAC or referenced in registree. VS 2019 changed that. I have two installations of the MSBuild 16. One as part of VS 2019 Professional, another as build agent. Metrics looks in some different spot.

Sincerely, Grigoriy Milman

On Aug 9, 2019 8:28 PM, Matthew Sebolt <notifications@github.com> wrote:

@gremlm<https://github.com/gremlm> We're sorry you're experiencing difficulties.

Please try solution posted on issue microsoft/azure-pipelines-agent#902<https://github.com/microsoft/azure-pipelines-agent/issues/902> while we work on getting this resolved.

**Comment by msebolt** [comment]
This has been moved to the product support forums, see https://developercommunity.visualstudio.com/content/problem/703898/metricsexe-looking-for-msbuild-in-wrong-location.html.

**Comment by msebolt** [comment]
There is nothing further that can be done with the documentation.

Please use the link above to direct any further feedback.
