### ISSUE TITLE
Repeating PassThroughNonNull call for CA1062 (Validate arguments of public methods) is unnecessary

### ISSUE THREAD

**Issue by ChrisTorng** [MicrosoftDocs/visualstudio-docs#3759]
The last example calls `PassThroughNonNull(other)` many times. That is repeating, useless and unnecessary:

    // Copy constructor
    public Person(Person other)
        : this(PassThroughNonNull(other).Name,
          PassThroughNonNull(other).Age)
    {
    }

 Just check it for the first time is enough:

    // Copy constructor
    public Person(Person other)
        : this(PassThroughNonNull(other).Name, other.Age)
    {
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80979f5-bdc4-f5c8-9adf-fea83bafaa7e
* Version Independent ID: a28c47de-cf33-0aff-cff2-e3da9c709623
* Content: [CA1062: Validate arguments of public methods - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019)
* Content Source: [docs/code-quality/ca1062-validate-arguments-of-public-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1062-validate-arguments-of-public-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Protiguous** [comment]
Alternate last example, uses a private constructor to pre-validate the "other" Person.

    public interface IPerson {
        String Name { get; }
        Int32 Age { get; }
    }

    public class Person : IPerson {
        public String Name { get; }
        public Int32 Age { get; }

        public Person( String name, Int32 age ) {
            this.Name = name ?? throw new ArgumentNullException( nameof( name ) );
            this.Age = age;
        }

        private Person( Person other ) : this(other.Name, other.Age) { }
        
        public Person( [CanBeNull] IPerson other ) : this( PassThroughNonNull( other ) ) { }

        private static Person PassThroughNonNull( IPerson person ) => person == null ? throw new ArgumentNullException( nameof( person ) ) : ( Person ) person;
    }

**Comment by Protiguous** [comment]
Alternate solution to validation. Uses a private constructor to pre-validate the "other" Person.

    public interface IPerson {
        String Name { get; }
        Int32 Age { get; }
    }

    public class Person : IPerson {

        public String Name { get; }

        public Int32 Age { get; }

        public Person( String name, Int32 age ) {
            this.Name = name ?? throw new ArgumentNullException( nameof( name ) );
            this.Age = age;
        }

        private Person( IPerson other ) : this(other.Name, other.Age) { }
        
        public Person( [CanBeNull] Person other ) : this( PassThroughNonNull( other ) ) { }

        private static IPerson PassThroughNonNull( Person person ) => person ?? throw new ArgumentNullException( nameof( person ) );
    }

**Comment by Mikejo5000** [comment]
Updating doc
