### ISSUE TITLE
Warning "Running unit tests after every build is supported only in Visual Studio Enterprise." no longer applies to Visual Studio 2019

### ISSUE THREAD

**Issue by carlos-quintero** [MicrosoftDocs/visualstudio-docs#3760]
This page (https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019), for Visual Studio 2019, contains this section with this warning:

"Run tests after every build
Warning
Running unit tests after every build is supported only in Visual Studio Enterprise."

That warning was correct for Visual Studio 2017, but no longer applies to Visual Studio 2019. See this note of this page for Visual Studio 2017 https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2017 (that no longer appears for Visual Studio 2019 https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019):

"Running unit tests after each build requires Visual Studio 2017 Enterprise or Visual Studio 2019. In Visual Studio 2019 it is included in Community and Professional as well as Enterprise."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66fe9e04-c830-3350-3ff9-9a3ecb7cfe5e
* Version Independent ID: e1063d2e-aace-86b2-a4b4-6378c45c55a0
* Content: [Unit testing fundamentals - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019#feedback)
* Content Source: [docs/test/unit-test-basics.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/unit-test-basics.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@carlos-quintero Thanks. It looks like this was fixed yesterday in https://github.com/MicrosoftDocs/visualstudio-docs/commit/daf6c639c9ff1c644945cfa81f36222d49e93efd#diff-eca8bcdd948030312f308301802e4e1e.
