### ISSUE TITLE
Missing UI for toggling assembly-based discovery of tests

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#3763]
![image](https://user-images.githubusercontent.com/312166/62904478-32a1e100-bd6f-11e9-9e45-445e84fc1481.png)

If it's no longer needed, then the relevant docs should be fixed.

Otherwise, there should be some information as to how to display it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fa1671-f27f-484e-8994-ceb85b1a73d6
* Version Independent ID: 5b90e41e-b4ba-7cb7-b798-59ea1ae38eb4
* Content: [Test Explorer FAQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq?view=vs-2019)
* Content Source: [docs/test/test-explorer-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/test-explorer-faq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by kendrahavens** [comment]
Thank you for taking the time to provide feedback!
Assembly based discovery would be the default discovery mechanism that the Test Explorer would fall back to if real time test discovery was unchecked. Would changing the text make this clearer?

**Comment by kendrahavens** [comment]
Updating the doc to only show the new options.

**Comment by zspitz** [comment]
Thanks, this looks much better.

**Comment by kendrahavens** [comment]
Woah, that was quick! Yes, I needed to add monikers to the nuget reference for test adapters section.
