### ISSUE TITLE
Profiling with VSPerfCmd on Command Line fails with error to use vsperf.exe - vsperf is undocumented and not working

### ISSUE THREAD

**Issue by halifir** [MicrosoftDocs/visualstudio-docs#3765]
Due To https://docs.microsoft.com/en-us/visualstudio/profiling/vsperfcmd?view=vs-2017 and https://docs.microsoft.com/en-us/visualstudio/profiling/vsperfcmd?view=vs-2019 

VSPerfCmd should start profiling.
But when using VSPerfCmd it says
Error VSP1535 : Verwenden Sie zum Erfassen von Samplingdaten f³r diese Version von Windows die Datei "vsperf.exe".
But vsperf is a) undocumented and b) not working either

psy_lsdir.exe "psy_lsdir.c"
just a psyochdelic sampe test program opening directory and showing content
working ouput is just psy_lsdir.c, if the file is in the direcory

VsPerfCmd.exe /start:sample /output:$TMPDIR/psy_lsdir.vsp /WAITSTART /SHUTDOWN /launch:psy_lsdir.exe /ARGS:psy_lsdir.c
result:
Fehler VSP1535 : Verwenden Sie zum Erfassen von Samplingdaten f³r diese Version von Windows die Datei "vsperf.exe".

doing this:
vsPerf.exe /start:sample /output:$TMPDIR/psy_lsdir.vsp /WAITSTART /SHUTDOWN /launch:psy_lsdir.exe /ARGS:psy_lsdir.c

Unbekannte oder fehlerhaft formatierte Befehlszeilenoption: /start:sample. Führen Sie VSPerf /? Aus, um die Syntax abzurufen.

D:/GNU9PAISY/SRC $vsperf.exe /?
Microsoft (R) VSPerf-Datensammler, Version 15.0.0.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Verwendungsbeispiele:

vsperf /app:AppName [/js] [/file:ReportName] [/pause] [/noclr]
vsperf /package:PackageFullName [/js] [/file:ReportName] [/pause] [/noclr]
vsperf /launch:Executable [/args:Arguments] [/console] [/file:ReportName] [/pause] [/noclr]
vsperf /attach:PID|ProcessName [/file:ReportName] [/pause] [/noclr]
vsperf /stop
vsperf /listapps

vsperf /launch:psy_lsdir.exe /args:psy_lsdir.c

doing this a simple as possible:
vsperf /launch:psy_lsdir.exe /args:psy_lsdir.c
Microsoft (R) VSPerf-Datensammler, Version 15.0.0.0
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
Fehler beim Starten der Sammlungssitzung: die Sitzung wurde bereits gestartet.

"Error in collecting datas, because a sessino is active" - not showing which session. 
There is no session active.

**Comment by Mikejo5000** [comment]
Sampling using the legacy profiling tools is not supported in VS 2019. For more info about the changes, see 
https://docs.microsoft.com/en-us/visualstudio/profiling/profiling-feature-tour?view=vs-2019#analyze-performance-legacy-tools
