### ISSUE TITLE
Wrong namespace mentioned.

### ISSUE THREAD

**Issue by penenkel** [MicrosoftDocs/visualstudio-docs#3766]
> The deployment element is required and is in the urn:schemas-microsoft-com:asm.v1 namespace.

As far as I can tell this is not true. The default namespace for deploment-manifests generated by mage.exe (newest version) is v2, thus the deployment-node is also in v2. This seems to be congruent with the manifest schema as specified [here](https://docs.microsoft.com/en-us/openspecs/sharepoint_protocols/ms-osco/21301d88-1922-4e85-99f6-9e7053fdbc44)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bffc1afe-3609-21bd-d489-6ac93202caf8
* Version Independent ID: 0878a1fe-599c-0806-f9cf-115ce5fedb46
* Content: [&lt;deployment&gt; Element (ClickOnce Deployment) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/deployment-element-clickonce-deployment?view=vs-2019#elements-and-attributes)
* Content Source: [docs/deployment/deployment-element-clickonce-deployment.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/deployment-element-clickonce-deployment.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updating doc. Thx!
