### ISSUE TITLE
Visual Studio Installer does not work in offline mode

### ISSUE THREAD

**Issue by gaheath** [MicrosoftDocs/visualstudio-docs#3768]
I followed the instructions (using cut and paste) on the offline install page.
Download appeared to work - success was displayed at the end.
Then run the vs_professional.exe from the downloaded folder and it tries to access the Internet and fails with "check your Internet connection" - I had not expected that from an "offline" installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Troubleshoot installation or upgrade issues - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues?view=vs-2019#feedback)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/troubleshooting-installation-issues.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@gaheath It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 
We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 
Here are a few more support options:​ 
-Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
 
Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
 
Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by TerryGLee** [comment]
@gaheath Additionally, please note that there are detailed instructions for creating an offline installation on the following page: [Create an offline installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019). However, you must have an internet connection to download the bootstrapper.

**Comment by haunguyen84** [comment]
It's also failed when installing with offline version.
The root cause is NODE_OPTIONS. Here is the genius instruction of my friend:

"If you open a new cmd window and check with "echo %NODE_OPTIONS%", if the result is anything _else_ than "%NODE_OPTIONS%", then that is probably your problem.

The VS Installer runs its own version of Node.js and if the Node.js version the the VS installer uses does not know about all of the options defined in that envrionment variables, it just crashes the installer with absolutely no message..."

Hope it can help you out.
Thanks and best regards!
Hau Nguyen.
