### ISSUE TITLE
Topic specifies Preview image should be 200x200 pixels but published extensions typically use 128x128 pixel images.

### ISSUE THREAD

**Issue by mbranscomb** [MicrosoftDocs/visualstudio-docs#3770]
The topic states the Preview image must be 200x200 pixels but it's not clear where that 200 pixel image will ever be displayed. Extensions published on Visual Studio Marketplace all appear to use images that are 128x128 pixels e.g. https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsls-vs.

- Download and unzip the extension
- The `extension.vsixmanifest` defines the preview image as `&lt;PreviewImage&gt;Resources\Market_Cascade_128x.png&lt;/PreviewImage&gt;`
- The file at `Microsoft.VisualStudio.LiveShare\Resources\Market_Cascade_128x.png` is 128x128 pixels.

This text would appear to be incorrect (although based on the 2.0 vsixmanifest schema information 
```
Preview image Specifies the graphics file (.png, .bmp, .jpeg, .ico) that contains the preview image to be displayed in Extension Manager, if a preview image is present. The preview image must be 200x200 pixels. If no preview image is specified, Extension Manager uses a default image.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0f9d9de-1ab2-0f11-72cc-8afa6d64c3d2
* Version Independent ID: 290fb60b-b8f3-00d6-6796-81a541e7bdb2
* Content: [VSIX Manifest Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-manifest-designer?view=vs-2019#feedback)
* Content Source: [docs/extensibility/vsix-manifest-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/vsix-manifest-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by madskristensen** [comment]
The Preview image hasn't been shown anywhere since Visual Studio 2017. It's only recommended for extensions supporting down to version 2015 or earlier.

**Comment by mbranscomb** [comment]
@madskristensen Thanks for the response.

Is the recommendation now to only have one single icon of 128x128 pixels?

**Comment by madskristensen** [comment]
Yes, for any extension targeting VS 2017 and above, only the Icon is recommended and it should be 128x128 pixels.

**Comment by mbranscomb** [comment]
@madskristensen Thanks for confirming. We'll update our extension accordingly.

**Comment by mbranscomb** [comment]
Is there a plan to update the docs / schema?

**Comment by madskristensen** [comment]
Not currently since it's still valid for VS2015 and below.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by mbranscomb** [comment]
@WilliamAntonRohm 

For our internal graphics team, a 200x200 image can still be considered a small 'splash screen' whereas 128x128 falls under the 'logo' category and will have a different design. We now have a new graphics request in progress. 

It would be good to see additional clarification added to the doc topic to indicate that extension developers targeting VS2017 and above should be planning for an image at 128x128, rather than two different images (one at 32x32 and one at 200x200) since there might be internal costs associated with the creation of these.

Cheers

**Comment by WilliamAntonRohm** [comment]
@mbranscomb -- Mike, thank you for your feedback.

@madskristensen -- Mads, please look into this issue 3770.

**Comment by WilliamAntonRohm** [comment]
@madskristensen -- please consider this issue 3770.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
