### ISSUE TITLE
Argument order

### ISSUE THREAD

**Issue by sergey-mukhamedshin** [MicrosoftDocs/visualstudio-docs#3772]
The first code example is not accurate. Arguments order in Log.LogMessage call should be updated to: 
```
   <Code Type="Fragment" Language="cs">
      Log.LogMessage(MessageImportance.High, "Hello, world!");
    </Code>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87459e0-a40b-d8ae-3f74-76e8f84ef6f8
* Version Independent ID: 57affef6-ead8-8c44-be7e-a9a3e9bda92b
* Content: [Walkthrough: Creating an Inline Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-inline-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/walkthrough-creating-an-inline-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-creating-an-inline-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@sergey-akhalkov I'm wondering if overloads support both ways. Did you get an error on this code?

**Comment by ghogen** [comment]
I agree with @sergey-akhalkov the arguments should be reversed. The call might not fail, but the arguments after the string argument are string formatting args, not the message importance arg.  See https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.utilities.tasklogginghelper.logmessage?view=netframework-4.8#Microsoft_Build_Utilities_TaskLoggingHelper_LogMessage_Microsoft_Build_Framework_MessageImportance_System_String_System_Object___

**Comment by sergey-akhalkov** [comment]
Hi @ghogen, @Mikejo5000  seems like you've pinged me by mistake 🙂 Are you trying to reach out @sergey-mukhamedshin ?
