### ISSUE TITLE
Not a lot of info

### ISSUE THREAD

**Issue by crojasd00** [MicrosoftDocs/visualstudio-docs#3775]
The information in this page isn't very complete. I'd expect to have a bit of information on what each of those "folders" and drop down menus are. What are properties? What are references? What are assets? Are they folders?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by TerryGLee** [comment]
@crojasd00 Thanks for your feedback and apologies that it's taken some time for us to respond. As of today's date, we can report that we've revaluated this page and its related pages. We’ve confirmed that the intent of this page is to introduce solutions and projects at a conceptual level and then link to related pages that include in-depth information. However, to respond to your feedback that this page was missing the in-depth information that you expected to see, we revised it to include more links to the pages that include that in-depth information. We hope this helps. Meanwhile, we’ll close this issue now with our thanks to you for helping improve the documentation!
