### ISSUE TITLE
Not found pdf 

### ISSUE THREAD

**Issue by HKimhab** [MicrosoftDocs/visualstudio-docs#3780]
Hello
I wanna pdf of this document. 

Thank you so much. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6d2b64e-ee32-5451-edca-89c758f20f07
* Version Independent ID: 4816ae3c-7352-7abc-df1d-f5fee3a28767
* Content: [Default keyboard shortcuts for frequently used commands - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-for-frequently-used-commands-in-visual-studio?view=vs-2019#file)
* Content Source: [docs/ide/default-keyboard-shortcuts-for-frequently-used-commands-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/default-keyboard-shortcuts-for-frequently-used-commands-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@HKimhab -- there should be a link in the lower left of your screen that says "Download PDF".  Please try that, and if it doesn't work, let us know at https://aka.ms/sitefeedback.
