### ISSUE TITLE
Visible metadata works fine in csproj projects but isn't honored for vcxproj projects

### ISSUE THREAD

**Issue by sergey-mukhamedshin** [MicrosoftDocs/visualstudio-docs#3783]
The below is not accurate:

> To hide an item from display, set the Visible metadata to false. For example, the following item will participate in the build process but not be displayed in Solution Explorer.

While _Visible_ metadata works fine in _csproj_ projects it isn't honored for _vcxproj_ projects. At least it is how it works in VS2019 Community Edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1010063-a8b2-7ff9-4ad6-10eebde154c3
* Version Independent ID: 1202745a-e34a-aabd-7cde-337726579377
* Content: [Visual Studio Integration (MSBuild)](https://docs.microsoft.com/en-us/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/visual-studio-integration-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/visual-studio-integration-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald This issue (and the content in general) seems like it might be easier for IDE folks to answer? It seems more about how the IDE works with MSBuild, rather than MSBuild specific issues. What do you think?

**Comment by rainersigwald** [comment]
Yes, this is a question about what the project system does with the information from the MSBuild project. @olgaark, do you know if there's a C++ equivalent to `Visible`?

**Comment by Mikejo5000** [comment]
@olgaark for input
