### ISSUE TITLE
Warning c26814

### ISSUE THREAD

**Issue by tawmoto** [MicrosoftDocs/visualstudio-docs#3785]
I copied the examples at your page, but I don't get c26814, instead I got different similar warnings:

```
c:\users\taw\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(13): warning C26497: The function 'bar' could be marked constexpr if compile-time evaluation is desired (f.4).
c:\users\taw\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(16): warning C26498: The function 'getMagicNumber' is constexpr, mark variable 'magicNumber' constexpr if compile-time evaluation is desired (con.5).
c:\users\taw\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(13): warning C26440: Function 'bar' can be declared 'noexcept' (f.6).
c:\users\taw\source\repos\consoleapplication5\consoleapplication5\consoleapplication5.cpp(18): warning C26440: Function 'main' can be declared 'noexcept' (f.6).
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e578eb30-f294-9f1a-3615-0fd48845f4bc
* Version Independent ID: 492a39c3-88ae-2b4c-f13f-a9bde959add7
* Content: [c26814 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26814?view=vs-2019)
* Content Source: [docs/code-quality/c26814.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26814.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @JordanMaples
* Microsoft Alias: **jomaples**

**Comment by JordanMaples** [comment]
Hi @tawmoto, 

I'll install the latest release and check right now.

In the meantime, are you running the code in Visual Studio itself or are you running from the command line? If you're running from VS, please make sure you've either enabled C26814 inside your currently selected ruleset, or are using the "C++ Core Check Const Rules."

-Jordan

**Comment by tawmoto** [comment]
I am using latest VS 2017 with all analyser options enabled. Thanks

**Comment by JordanMaples** [comment]
You'll need to update to the latest Visual Studio 2019 to use this check. It was released with [Preview 2](https://devblogs.microsoft.com/cppblog/new-c-core-check-rules/).

**Comment by JordanMaples** [comment]
@WilliamAntonRohm there's no bug here. can you close the issue.

**Comment by TerryGLee** [comment]
I'll close it; thanks.
