### ISSUE TITLE
Missing Option: Restore Solution Explorer project hierarchy state on solution load

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#3786]
This sounds useless to provide as an option. What does it do and why would anyone not want to load a solution properly when they open it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28461613-82d6-e8f7-7f12-da24a594775d
* Version Independent ID: d7758211-e43d-9fca-4ca2-52be17a7cd63
* Content: [Projects and Solutions, Options dialog box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/projects-and-solutions-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Projects.General)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/reference/projects-and-solutions-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/projects-and-solutions-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Referring to this new option:

![image](https://user-images.githubusercontent.com/24882762/63181027-3ac67e80-c004-11e9-86ba-faf60e5a6d2e.png)
