### ISSUE TITLE
Missing option for /Diff command line switch: "Open in new instance of IDE"

### ISSUE THREAD

**Issue by ruslan528** [MicrosoftDocs/visualstudio-docs#3787]
It's a very uncomfortable to merge csproj file in IDE where this project has already be opened

**Comment by WilliamAntonRohm** [comment]
@ruslan528 Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by gewarren** [comment]
This sounds like product feedback, not documentation feedback. Is that correct?

**Comment by ruslan528** [comment]
Yes, I'm sorry :)
