### ISSUE TITLE
How to skip verification on layout update?

### ISSUE THREAD

**Issue by yatagarasu25** [MicrosoftDocs/visualstudio-docs#3793]
Verification uses to much time how to disable it? I am pretty sure my install dir is not broken, I was not touching it, Why I should wait half an hour before installer will load new components?

**Comment by WilliamAntonRohm** [comment]
@yatagarasu25 -- Igor, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by yatagarasu25** [comment]
Interesting system you have created - people can open and create issues from your documentation pages, but you can not track which one it belong to.

https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019
I am talking about updating network installer. 

If i will launch layout update with command like this "vs_Community.exe --layout "E:\Visual Studio\Visual Studio 2017\Layout" --lang en-US" it will be verifying all my already downloaded packages. for no useful reason - because all downloaded packages are ok. To download 200mb of updates it will check all my 30gigs. It takes much more time then downloading, especially on convenient hdds.

**Comment by WilliamAntonRohm** [comment]
@yatagarasu25  It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.
We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.
Here are a few more support options:
-	-Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.

-	Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).

-	Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by yatagarasu25** [comment]
I don't have issues with installation, I ask you to add flag to visual studio installer.

**Comment by WilliamAntonRohm** [comment]
@yatagarasu25 -- Igor, thank you for clarifying. It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.
