### ISSUE TITLE
Obsolete plus missing info on VS for Mac

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/visualstudio-docs#3794]
This is obsolete and it is missing same information for VS for Mac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2df4c6fa-3c52-7129-fb99-576fbc573386
* Version Independent ID: f4538a2b-56bf-48e2-e885-2d632032a31e
* Content: [Options, Text Editor, All Languages, Tabs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-all-languages-tabs?view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-all-languages-tabs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-all-languages-tabs.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@conceptdev @asb3993 Does VS for Mac have docs for options pages?

**Comment by asb3993** [comment]
Hello, we have docs on various options or Preferences in Visual Studio for Mac. You can find them here: https://docs.microsoft.com/en-us/visualstudio/mac/source-editor?view=vsmac-2019. We're also continuing to add many more docs around the new editor, so let me know if you notice anything missing!
