### ISSUE TITLE
Obsolete and Missing VS for Mac Information

### ISSUE THREAD

**Issue by dinobu** [MicrosoftDocs/visualstudio-docs#3795]
Please add information on how to do tabs vs spaces setting for VS 4 mac

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2bf1a218-2295-22ac-03eb-1ccc63b4a3e6
* Version Independent ID: baa311a7-6b87-6196-ae8a-b8759a1df73c
* Content: [C# editor formatting options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-formatting?view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-csharp-formatting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-formatting.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@dinobu This particular help topic is only for VS on Windows. For configuring tabs versus spaces for VS for Mac, you can do that with an EditorConfig file: https://docs.microsoft.com/visualstudio/mac/editorconfig?view=vsmac-2019.

/cc  @asb3993
