### ISSUE TITLE
Sharepoint or Outlook

### ISSUE THREAD

**Issue by mmoriartyCMC** [MicrosoftDocs/visualstudio-docs#3796]
It looks like an outlook article but references the Sharepoint project template. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd2cccf4-e8b1-aa69-b3ae-50d27b2a4d50
* Version Independent ID: 9c3a644a-f267-4092-24be-2566788e7500
* Content: [Walkthrough: Create your first VSTO Add-in for Outlook - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook?view=vs-2019#feedback)
* Content Source: [docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@mmoriartyCMC the document just mentioned that the templates are under the Office/SharePoint node in Visual Studio.  This was true for all versions of Visual Studio prior to Visual Studio 2019
