### ISSUE TITLE
Missing information and wrong link on `TargetFrameworkProfile`

### ISSUE THREAD

**Issue by ite-klass** [MicrosoftDocs/visualstudio-docs#3797]
The section on `TargetFrameworkProfile` describes how to set a configuration value, but nothing more.

It refers and links to a how to page that has no information about `TargetFrameworkProfile` at all.

So I think this link should be removed. And the question is: Is there more information on `TargetFrameworkProfile` elsewhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a80e5d7-2db7-48c0-e8b6-ca8c3ff30017
* Version Independent ID: ad64635b-06d5-1b87-8f02-80cf25c12520
* Content: [MSBuild Target Framework and Target Platform - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-target-framework-and-target-platform.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-target-framework-and-target-platform.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Yes, there seems to be a lack of .NET docs on TargetFrameworkProfile. I see a ref doc, but that doesn't appear very helpful. @rainersigwald Rainer, do you know if it is OK to remove the content on TargetFrameworkProfile?

**Comment by rainersigwald** [comment]
@terrajobst, do you know who might be able to provide a definitive answer on this?

**Comment by terrajobst** [comment]
Profiles were a way to create subsets of .NET platforms (e.g. .NET Framework 4.5 Client). We also used this in Portable Class Libraries. Moving forward, this feature isn't useful.

@ite-klass why do you ask?

**Comment by ite-klass** [comment]
@terrajobst What question are you referring to? Whether there is more information?

Because “For more information, see” clearly indicates there is more information, while linking to an article that does not.

**Comment by Mikejo5000** [comment]
I'll update the doc to explain that it only applies to portable class libraries.
For more info:
https://docs.microsoft.com/en-us/dotnet/standard/cross-platform/cross-platform-development-with-the-portable-class-library
