### ISSUE TITLE
There is no Run on the Test branch of the menu bar

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#3799]
The comment below was machine translated

@wraith13 commented on [Mon Aug 19 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1828)

https://docs.microsoft.com/ja-jp/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019#next-steps
```md
Select ** Tests ** ** Run **** ** All Tests ** from the menu bar.
```

However, when I checked in the Japanese version of Mirosoft Visual Studio Community 2019 Version 16.2.2, only [Window] existed in [Test] on the menu bar. (The same function appears to be usable without problems from Test Explorer.)
![image](https://user-images.githubusercontent.com/645907/63291864-5f21a400-c2ff-11e9-9733-9729ae46b7f1.png)

---

@srvbpigh commented on [Mon Aug 19 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1828#issuecomment-522707637)

Hello, @wraith13
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Not sure if a product feedback or if the user is reporting an inaccuracy in the documentation
best regard

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, please forward this reply on to wraith13:

Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by wraith13** [comment]
https://developercommunity.visualstudio.com/content/problem/672211/test-menu-items-missing-except-windows.html
I found it. But I'm sad...
