### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by casterle** [MicrosoftDocs/visualstudio-docs#3802]
There is no documentation for the "Advanced" settings section of the "Text Editor" options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed1ad3bb-8825-c292-1dc7-9cb101106124
* Version Independent ID: 47e2bf35-21c1-584a-4e84-7cc28ab24726
* Content: [Options dialog - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-dialog-box-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/options-dialog-box-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-dialog-box-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@casterle Thanks, this is already being tracked by #3121.
