### ISSUE TITLE
Licensing Issue

### ISSUE THREAD

**Issue by joshrpg** [MicrosoftDocs/visualstudio-docs#3803]
I'm not sure if it's worth stating in the documentation but it seems that if you want to virtualize Visual Studio, you must first run this before running the StorePID.exe. Otherwise, the licensing process will fail. 

```"C:\Program Files (x86)\Microsoft Visual Studio <VERSION>\Common7\IDE\DDConfigCA.exe"```

**Comment by msebolt** [comment]
@joshrpg  Thank you for the feedback.

The documentation has been updated.

**Comment by msebolt** [comment]
Re-assigning for confirmation with the product team.

**Comment by TerryGLee** [comment]
@msbolt We've reviewed this and are adding some additional information, which should go live this afternoon.

@joshrpg Thanks for helping us improve our documentation!
