### ISSUE TITLE
XAML Hot Reload Only Works With "Debug" Configuration

### ISSUE THREAD

**Issue by djohansing** [MicrosoftDocs/visualstudio-docs#3804]
We have a solution that uses WPF XAML. We are using the latest version of Visual Studio and it seems that [this feature](https://docs.microsoft.com/en-us/visualstudio/debugger/xaml-hot-reload?view=vs-2019) only works when the configuration name is "Debug". Anything else and it will not reload any changes to xaml while running the application.

**Comment by msebolt** [comment]
@djohansing  Thank you for the feedback, we're sorry you're having issues with the product.

Unfortunately this is a known limitation of **Hot Reload**, as mentioned in [Write and debug XAML Hot Reload](https://docs.microsoft.com/en-us/visualstudio/debugger/xaml-hot-reload?view=vs-2019):

```
Visual Studio XAML Hot Reload is currently only supported when running your application in Visual Studio or Blend for Visual Studio with the debugger attached (F5 or Start debugging). You can't enable this experience by using Attach to process.
```

If you'd like this available, please try [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019).

**Comment by djohansing** [comment]
I saw that note, we are not using "Attach to process" and the debugger is attached. We can use "Edit and Continue", etc. with our code, just the XAML reload did not work until we changed the config name, which seems very odd.

So, the limitation description is misleading.

**Comment by Mikejo5000** [comment]
@djohansing That is a current limitation of the feature. A custom build configuration name is not supported. We are currently updating these docs.

**Comment by Mikejo5000** [comment]
@djohansing This doc is published now and should clarify the issue:
https://docs.microsoft.com/en-us/visualstudio/debugger/xaml-hot-reload-troubleshooting?view=vs-2019#verify-that-you-are-using-the-correct-build-configuration-name

**Comment by djohansing** [comment]
Thanks! Adding the tag to the .proj settings fixes the issue.
