### ISSUE TITLE
Option does not exist in Test menu

### ISSUE THREAD

**Issue by Nate0922** [MicrosoftDocs/visualstudio-docs#3806]
https://developercommunity.visualstudio.com/content/problem/332481/analyze-code-coverage-no-longer-on-test-menu.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Code coverage testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019#feedback)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@Nate0922  Thank you for the feedback.

The documentation has been updated.

**Comment by michaelakin** [comment]
So, where can we find this option?

**Comment by msebolt** [comment]
@michaelakin  It's in Enterprise version's **Test Explorer**, under the **Run** options:

<img width="395" alt="86469-codecoverage" src="https://user-images.githubusercontent.com/6675884/63960002-4fface80-ca42-11e9-939f-55fc8e06e155.png">

**Comment by michaelakin** [comment]
Gotcha.  Thanks.
*Michael Akin*
Phone: 405-313-8126
Email:  michael@akin-family.org
Linked In:  http://www.linkedin.com/in/michaelakin
