### ISSUE TITLE
SDK style projects did not require unloading in order to edit them.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#3808]
&gt; This is an easy way to edit the project XML file without having to first unload the project and then open the project file for editing

You could always edit SDK files by right clicking and choosing the Edit..csproj menu item. The better file format required unloading first, and that was a semi-artificial requirement since editing values on the project property pages didn't require unloading of the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28461613-82d6-e8f7-7f12-da24a594775d
* Version Independent ID: d7758211-e43d-9fca-4ca2-52be17a7cd63
* Content: [Projects and Solutions, Options dialog box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/projects-and-solutions-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Projects.General)%26rd%3Dtrue&view=vs-2019#restore-solution-explorer-project-hierarchy-state-on-solution-load)
* Content Source: [docs/ide/reference/projects-and-solutions-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/projects-and-solutions-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Ah thanks, I'll get that fixed.
