### ISSUE TITLE
NotImplementedException should be allowed for abstract class.

### ISSUE THREAD

**Issue by rtaylor72** [MicrosoftDocs/visualstudio-docs#3809]
You should be allowed to have NotImplementedException in an abstract class.  None of the other allowed exceptions define the issue where someone has not fully implemented a concrete class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97481308-03ef-f29b-5483-616a6beae238
* Version Independent ID: 00357ee6-530e-d8ee-2287-a5f3e4ce77ab
* Content: [CA1065: Do not raise exceptions in unexpected locations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1065-do-not-raise-exceptions-in-unexpected-locations?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1065-do-not-raise-exceptions-in-unexpected-locations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1065-do-not-raise-exceptions-in-unexpected-locations.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@rtaylor72 Are you saying the rule shouldn't fire in this case, or the documentation needs to state that it's okay to suppress the warning in this case?

**Comment by gewarren** [comment]
If you are asking for the rule to be changed, please file an issue in the roslyn-analyzers github repo. Here is a related issue: https://github.com/dotnet/roslyn-analyzers/issues/2761.

**Comment by rtaylor72** [comment]
Correct, I feel that the rule needs to be changed to include NotImplementedException . I will make a comment on that thread as well.  Thanks!

**Comment by Zenexer** [comment]
This is a bug: https://github.com/dotnet/roslyn-analyzers/issues/2761.  NotImplementedException is supposed to be allowed in most places.

**Comment by Zenexer** [comment]
@rtaylor72 To be clear, you probably shouldn't be using NotImplementedException in abstract classes.  Instead, favor this:

``` csharp
public abstract class A
{
	public abstract void SomeMethod();
}

public class B : A
{
}
```

This won't compile because B doesn't implement SomeMethod.  The following is less ideal:

``` csharp
public abstract class A
{
	public void SomeMethod() => throw new NotImplementedException();
}

public class B : A
{
}
```

This will compile; you won't actually get an exception until something attempts to call SomeMethod, which may never happen during your testing.  You can apply the same trick to properties.
