### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by DMX-DCardinal** [MicrosoftDocs/visualstudio-docs#3813]
Hi, I think there is a lot of missing information in the "Extend exisiting tool windows". Here are the tutorials that I was looking for when I was looking to "extend existing tool windows":
Extend existing tool window functionality: https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-the-solution-explorer-filter?view=vs-2019
Add functionality to existing tool windows: https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-command-to-the-solution-explorer-toolbar?view=vs-2019

Which both qualify, in my opinion, as "extending existing tool windows". Furthermore, I notice that the link to "Extend the Properties, Task List, Output, and Options windows" link is duplicated? Would be good to fix this.

Thank you for your consideration

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de8f3d05-2544-c058-390a-e891f884fa17
* Version Independent ID: 498f1db6-4ff2-b317-84df-3377eef4bb75
* Content: [Extending and Customizing Tool Windows - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/extending-and-customizing-tool-windows?view=vs-2019#feedback)
* Content Source: [docs/extensibility/extending-and-customizing-tool-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extending-and-customizing-tool-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@DMX-DCardinal Thank you for the feedback.

The documentation has been updated.
