### ISSUE TITLE
How to debug extension assembly not being loaded

### ISSUE THREAD

**Issue by rlivings39** [MicrosoftDocs/visualstudio-docs#3819]
Thanks for the walk through in this documentation. In following it I've been able to:

* Add an extension for a language
* Define a content type for my language
* Register a .tmLanguage file for syntax highlighting
* Verify that syntax highlighting works properly for the new language/file extension/content type
* Write a language client class associated with the content type

The issue I'm having is that the assembly from my VSIX project is never loaded and therefore `ActivateAsync` is never being called on my language client class. So I'm unable to start my language server. I don't see any errors, warnings, messages, etc. that seem relevant. Any tips on how to debug?

My guess is that some registration step is incorrect but I'm at a loss for where to go. These kind of debugging tips would be helpful for the future.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff91657a-173a-0013-62e4-e7c8531b8240
* Version Independent ID: 27988cad-5114-41e3-c48a-357431af0fe1
* Content: [Adding a Language Server Protocol extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension?view=vs-2019)
* Content Source: [docs/extensibility/adding-an-lsp-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by tfosmark** [comment]
Thanks for your question. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
