### ISSUE TITLE
CA2000 not ported/active

### ISSUE THREAD

**Issue by anfangda** [MicrosoftDocs/visualstudio-docs#3825]
You list the rule under "Ported", but it is not active.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd01f814-2fb6-066f-bdae-c7070e5f22d7
* Version Independent ID: 32f4ae71-bfb3-259f-0f10-bc56f184a9ad
* Content: [FxCop rule port status - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status?view=vs-2019#feedback)
* Content Source: [docs/code-quality/fxcop-rule-port-status.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/fxcop-rule-port-status.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@anfangda Can you clarify what you mean by the rule is not active?

**Comment by anfangda** [comment]
Hi, I think the real problem is that it does not trigger in our VS 2019. When I found [Issue 476](https://github.com/dotnet/roslyn-analyzers/issues/476) being closed with a label called "Will-Not-Implement-Fixer", I thought it was not implemented yet. But now I see that all those Issues and versions are much more complex than I expected. It seems to be implemented and I have to find out why it doesn't work in our project. Sorry, not your problem ;-)

**Comment by gewarren** [comment]
Got it - closing this issue in that case.
