### ISSUE TITLE
open folder option not available in MAC ???

### ISSUE THREAD

**Issue by hichits** [MicrosoftDocs/visualstudio-docs#3830]
This page does not talk about how to handle the same in MAC

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970f0d59-b2b4-7082-1c2c-a468c93571ef
* Version Independent ID: a3135966-c343-5a6b-cd97-772a0c34fd93
* Content: [Develop code without projects or solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions?view=vs-2019#feedback)
* Content Source: [docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by bgbruno** [comment]
yes that "banality" is crucial to development omg - link is closed because not enough info wtf??? - make it happened ms - I cannot use your product from 2010 because many failings

**Comment by bgbruno** [comment]
would be great show some workaround like - open it through command line
