### ISSUE TITLE
Download PDF in other language

### ISSUE THREAD

**Issue by jmroyb** [MicrosoftDocs/visualstudio-docs#3833]
Hi folks,
I can download as PDF https://docs.microsoft.com/en-us/visualstudio/test/improve-code-quality?view=vs-2019

But PDF link is missing for https://docs.microsoft.com/es-es/visualstudio/test/improve-code-quality?view=vs-2019

Do you plan to allow dowload this link and others in other language than English?

Cheers

**Comment by WilliamAntonRohm** [comment]
@jmroyb -- Josep, thanks for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
