### ISSUE TITLE
How to add custom menu items to the Dynamic list

### ISSUE THREAD

**Issue by amunger** [MicrosoftDocs/visualstudio-docs#3835]
The article shows how to create a dynamic menu that will be populated with the project names of the solution, but how would I specify my own items?

The introduction explains that:
"To populate the dynamic list, Visual Studio asks the VSPackage to look for a command with an ID whose first characters are the same as the ID of the placeholder. "
But this example only ever creates one CommandID and we only add that one command with the CommandService.
A rootItemId field is created but never used - was that once used to create the items?
Who is providing each of the project commands and how are they being assigned to the correct IDs? (I have confirmed that they do get created, I just don't see how)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c56b13-124c-4a9d-cbb8-6e98c468bb82
* Version Independent ID: 852cf409-c76b-360b-22cc-c675fc7259fa
* Content: [Dynamically Adding Menu Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/dynamically-adding-menu-items?view=vs-2019#feedback)
* Content Source: [docs/extensibility/dynamically-adding-menu-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/dynamically-adding-menu-items.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by amunger** [comment]
I think I figured out the source of my confusion. The `IsValidDynamicItem` predicate is used to establish a range of IDs by sending in each ID until the predicate returns false, and then one Command object is sent repeatedly to `OnBeforeQueryStatusDynamicItem`, with the selection of valid IDs in the `MatchedCommandID` field to set the text.
It wasn't clear that the Menu item would stop checking IDs when `DynamicItemMatch` returned false. Although I'm not sure that is the intended behavior since it also receives queries about IDs not anywhere near that range.

**Comment by tfosmark** [comment]
@amunger Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
