### ISSUE TITLE
Regex documentation pipe character not rendering properly

### ISSUE THREAD

**Issue by stratusjerry** [MicrosoftDocs/visualstudio-docs#3837]
The pipe | character in docs/ide/using-regular-expressions-in-visual-studio.md used for the "Match either the expression before or the one after the symbol" is not properly escaped which makes the example case fail. Github markdown renderer show's the correct output:
`(sponge|mud) bath`

However, docs.microsoft.com example show's incorrect output:
`(sponge\|mud)`

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
