### ISSUE TITLE
There is no NPM node in my project

### ISSUE THREAD

**Issue by davidekarasek** [MicrosoftDocs/visualstudio-docs#3838]
I'm using Visual Studio 2019 and there is no NPM in my project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25963783-6129-cbef-174c-9dd4adde494b
* Version Independent ID: 85926796-ac02-c41b-8ffc-c8987e22f387
* Content: [Manage npm packages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/npm-package-management?view=vs-2019)
* Content Source: [docs/javascript/npm-package-management.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/npm-package-management.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@davidekarasek -- David, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around the general task.

**Comment by msebolt** [comment]
@davidekarasek  

You need to create a Node.js solution from a new project or use the **From existing Node.js code** project template.

![Untitled](https://user-images.githubusercontent.com/6675884/64289217-b5563000-cf18-11e9-8534-17446b89fa8c.png)

The documentation is pending review.

**Comment by msebolt** [comment]
The documentation has been updated.  

Please comment below if there are further issues.
