### ISSUE TITLE
dev.azure.com missing in list

### ISSUE THREAD

**Issue by jesfer** [MicrosoftDocs/visualstudio-docs#3843]
The new base url dev.azure.com for Azure DevOps Services is missing in this list:
[https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019#use-visual-studio-and-azure-services](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019#use-visual-studio-and-azure-services)

**Comment by msebolt** [comment]
@jesfer  Thank you for the feedback.

The documentation has been updated.
