### ISSUE TITLE
False alarm for serialization constructor - CA1801

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#3844]
The serialization constructor should be an exception for this rule as well.
This way it conflicts also with CA2229.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5030cf5c-ae08-5a08-0b47-995006379292
* Version Independent ID: 9e1df70a-127c-eafc-e027-360797faf3a6
* Content: [CA1801: Review unused parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1801-review-unused-parameters?view=vs-2019)
* Content Source: [docs/code-quality/ca1801-review-unused-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1801-review-unused-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@koszeggy Since this is an issue with the analyzer itself and not the documentation, please log an issue over at [roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/issues).
