### ISSUE TITLE
False alarm if GetObjectData has a SerializationInfo.SetType call - CA2229

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#3845]
If `ISerializable.GetObjectData` has a `SerializationInfo.SetType` call, then another type will be deserialized (often used for singletons along with `IObjectReference`).

Either fix the analysis or change the *"Do not suppress a violation of the rule."* part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc2f617-a860-4e1c-1873-e113989ef4b3
* Version Independent ID: 93d3e1f5-67b6-48e5-37d5-c3376e9b4bb2
* Content: [CA2229: Implement serialization constructors - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2229-implement-serialization-constructors?view=vs-2019)
* Content Source: [docs/code-quality/ca2229-implement-serialization-constructors.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2229-implement-serialization-constructors.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Can you advise on this one whether an analyzer bug should be opened or if we should modify the "when to suppress" section of the docs?

**Comment by mavasani** [comment]
@gewarren Seems like another analyzer false positive. @koszeggy Can you please port it to roslyn-analyzers repo?
