### ISSUE TITLE
The new analyzer includes the complexity of local methods

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#3846]
Earlier I refactored a lot of complex methods like this:

![Screenshot](https://i.imgur.com/MM4sh1m.png)

Now these kind of methods trigger CA1502 again. Moving the local methods solves the problem but then it wouldn't be obvious that they are used only from a single method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0a288d0-68c8-dd18-d54f-921a03b33cf3
* Version Independent ID: 0cce318f-63f0-4a2b-0c75-a9e6e0eb12e5
* Content: [CA1502: Avoid excessive complexity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1502-avoid-excessive-complexity?view=vs-2019)
* Content Source: [docs/code-quality/ca1502-avoid-excessive-complexity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1502-avoid-excessive-complexity.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@koszeggy This issue belongs better in the roslyn-analyzers repo since you're requesting a change to the analyzer itself - https://github.com/dotnet/roslyn-analyzers/issues. If you're also requesting a documentation change, please comment here and we can reopen the issue.
