### ISSUE TITLE
CA1062 - False alarm for switch pattern matching

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#3847]
The following example triggers CA1062 mistakenly:

```csharp
[SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "False alarm: see the null case")]
public static int IndexOf<T>(this IEnumerable<T> source, T element)
{
    switch (source)
    {
        case null:
            throw new ArgumentNullException(nameof(source), Res.ArgumentNull);
        case IList<T> genericList:
            return genericList.IndexOf(element);
        case IList list:
            return list.IndexOf(element);
        default:
            var comparer = ComparerHelper<T>.EqualityComparer;
            var index = 0;
            foreach (T item in source)
            {
                if (comparer.Equals(item, element))
                    return index;
                index++;
            }

            return -1;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80979f5-bdc4-f5c8-9adf-fea83bafaa7e
* Version Independent ID: a28c47de-cf33-0aff-cff2-e3da9c709623
* Content: [CA1062: Validate arguments of public methods - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019#)
* Content Source: [docs/code-quality/ca1062-validate-arguments-of-public-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1062-validate-arguments-of-public-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Should @koszeggy open an issue in the roslyn-analyzers repo about this? Also, there is a configuration option coming soon for CA1062 to exclude the 'this' parameter of extension methods.

**Comment by mavasani** [comment]
Yes, this looks to be a bug. Can you please port it to the analyzers repo? Thanks!

**Comment by gewarren** [comment]
@koszeggy Please log this issue in the [roslyn-analyzers repo](https://github.com/dotnet/roslyn-analyzers/issues), please. Unfortunately we don't have the ability to transfer the issue.
