### ISSUE TITLE
False alarm - CA3077

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#3848]
The following example triggers CA3077:

```csharp
private sealed class ResXReader : XmlTextReader
{
    [SuppressMessage("Security", "CA3077:Insecure DTD processing in XML",
        Justification = "False alarm, DTD processing is set to prohibited in constructor body.")]
    internal ResXReader(Stream stream)
        : base(stream, InitNameTable())
    {
        DtdProcessing = DtdProcessing.Prohibit;
    }

    // [...]
}
```

The warning does not go away even if I include `XmlResolver = null;` as it is suggested in `TestClass2`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90516fdb-8445-97f4-364d-d59e4f07dca4
* Version Independent ID: 2d057d34-c44d-98ce-62c4-da3bc9a6564a
* Content: [CA3077: Insecure Processing in API Design, XML Document and XML Text Reader - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca3077-insecure-processing-in-api-design-xml-document-and-xml-text-reader?view=vs-2019)
* Content Source: [docs/code-quality/ca3077-insecure-processing-in-api-design-xml-document-and-xml-text-reader.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca3077-insecure-processing-in-api-design-xml-document-and-xml-text-reader.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@dotpaul Can you take a look at this one? It seems like there are two issues: 1) setting XmlResolver to null doesn't stop the warning and 2) the warning shouldn't fire if DtdProcessing is set to DtdProcessing.Prohibit.

**Comment by gewarren** [comment]
@koszeggy I've been advised to ask you to log this issue in the [roslyn-analyzers repo](https://github.com/dotnet/roslyn-analyzers/issues), please. Unfortunately we don't have the ability to transfer the issue.
