### ISSUE TITLE
The issue cannot be fixed when targeting earlier frameworks

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#3849]
The rule should consider the version of the targeted frameworks.

For example, the `Rfc2898DeriveBytes(string, byte[])` constructor triggers the warning in .NET 4.5; however, the overload with the `HashAlgorithmName` argument requires at least .NET 4.7.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 491d8182-a4d8-91a3-051e-a78b635a8849
* Version Independent ID: d1350ad0-a553-b92d-a00d-51e28c78f021
* Content: [CA5350: Do Not Use Weak Cryptographic Algorithms - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca5350-do-not-use-weak-cryptographic-algorithms?view=vs-2019)
* Content Source: [docs/code-quality/ca5350-do-not-use-weak-cryptographic-algorithms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca5350-do-not-use-weak-cryptographic-algorithms.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@EvaSchmotzerova Can you take a look at this feedback? Or let me know if you're not the right person.

**Comment by EvaSchmotzerova** [comment]
> @EvaSchmotzerova Can you take a look at this feedback? Or let me know if you're not the right person.

hi @gewarren,
I'm not the rule author, I'm merely responsible for publishing the documentation. please reach out to @filipsebesta as a PM for these rules - he can redirect you to the engineer who developed it

**Comment by gewarren** [comment]
@dotpaul Can you take a look and advise?

**Comment by gewarren** [comment]
@koszeggy I've been advised to ask you to log this issue in the [roslyn-analyzers repo](https://github.com/dotnet/roslyn-analyzers/issues), please. Unfortunately we don't have the ability to transfer the issue.
