### ISSUE TITLE
Very Nice & Attractive feature!

### ISSUE THREAD

**Issue by roniaxe** [MicrosoftDocs/visualstudio-docs#385]

**Comment by ghogen** [comment]
Thanks, roniaxe, what feature are you referring to?

**Comment by roniaxe** [comment]
Hey Gordon !

Thanks for your reply, I was actually though I'm commenting rather than
creating a new github issue :).
I was reffering to the 'intellitrace step-back' feature of latest 15.5
version. this is really really nice.
I wanted to ask, when is it getting (if) to the community VS version? I
know it's only on the Enterprise version at the moment.

Thanks,
Roni.

**Comment by TerryGLee** [comment]
Hello @roniaxe - I'm not sure if we can answer your inquiry at the present time, but another option to pursue is to share this with us as a product suggestion on UserVoice, at https://visualstudio.uservoice.com/forums/121579.
