### ISSUE TITLE
False alarm for generic types - CA2225

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#3851]
The _"Do not suppress a warning from this rule"_ part is way too rigorous this way. Consider the following example:

```cs
public static implicit operator Range<T>(T upperBound) => new Range<T>(upperBound);

public static implicit operator Range<T>((T lowerBound, T upperBound) bounds) =>
    new Range<T>(bounds.lowerBound, bounds.upperBound);
```

As `Range<T>` is generic the "best" solution to satisfy the rule would be two `ToRange` extension methods on any `T` and on `ValueTuple<T, T>`, respectively. But that would introduce a `ToRange` on every object, which is insane.

Not mentioning that the main purpose of the operator is to spare typing `new Range<T>(low, high)` and use simply `(low, high)` or `high` in place of any `Range<T>` assignment, which of course would be much bulkier in a `(low, high).ToRange()` form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7461911-4502-1e60-82b1-cc3cf1545ddf
* Version Independent ID: 2deb7000-b80d-01b1-644e-2748a113f637
* Content: [CA2225: Operator overloads have named alternates - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2225)
* Content Source: [docs/code-quality/ca2225-operator-overloads-have-named-alternates.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca2225.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Should the [When to suppress warnings section](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2225-operator-overloads-have-named-alternates?view=vs-2019#when-to-suppress-warnings) be updated?

**Comment by Mikejo5000** [comment]
@mavasani for input on this suggestion

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22042](https://github.com/dotnet/docs/issues/22042)
