### ISSUE TITLE
I needed double quotes for more than 1 -clp:"parameter1;parameter2"

### ISSUE THREAD

**Issue by ardalon** [MicrosoftDocs/visualstudio-docs#3853]
for example:
Does not work:
&gt; msbuild SolutionName.sln /p:NuGetRestorePackages=false /verbosity:quiet /p:WarningLevel=0 /clp:ErrorsOnly;Summary
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: SolutionName.sln

&gt; msbuild SolutionName.sln /p:NuGetRestorePackages=false /verbosity:quiet /p:WarningLevel=0 /clp:"ErrorsOnly;Summary"
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

    44 Warning(s)
    0 Error(s)

Works a treat!!

edit: removed additional remarks as I thought i was commenting on a page rather than logging a github issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2017#feedback)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, is it generally true that double quotes are needed for multiple parameter entries?

**Comment by rainersigwald** [comment]
It depends on your operating system and shell's escaping rules. `;` is a special character in many shells including PowerShell and bash, but it isn't in cmd.exe. The example command line given works fine in cmd:

```
C:\play>msbuild SolutionName.sln /p:NuGetRestorePackages=false /verbosity:quiet /p:WarningLevel=0 /clp:ErrorsOnly;Summary
Microsoft (R) Build Engine version 16.3.0-preview-19426-01+faf5e5d75 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.



    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.60
```

Since other shells are becoming more common for MSBuild users, we should probably update the examples to add quotes around any command-line argument that contains a semicolon.

**Comment by Mikejo5000** [comment]
Thanks, I'll plan to update the doc.

**Comment by ardalon** [comment]
Thanks, I was a bit frustrated when I wrote this initially, and should say i am not singling out msbuild only, this sort of thing crops up with other utilities and other shells and I feel this confusion could really be eliminated by linking to a page that keeps us weary of the different shells and contexts that we could be making calls from.  Would be a huge productivity boost.

For example, I still had problems with using double quotes when running this in Windows Docker containers.  I switched the SHELL to powershell not realizing that this is not equivalent to being  _in_ a [can i call it?] native powershell session but in actuality every line of your Docker for Windows Dockerfile is invoking PS from cmd.exe like so:  `powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; $params = "ErrorsOnly;Summary" ; msbuild $ENV:SOLUTION_FILENAME -p:NuGetRestorePackages=false -verbosity:quiet -p:WarningLevel=0 -clp:'ErrorsOnly;Summary's`  --- so actually single quotes were best for powershell

**Comment by Mikejo5000** [comment]
Double quotes are not the right fix then. Are there scenarios where single quotes won't work?

**Comment by ghogen** [comment]
I think it depends on the user intent, so in bash for example double-quotes allow expansion of variables, and single quotes do not.  For now, I have a PR for the MSBuild command-line topic that says to use quotes (single or double as appropriate) if running from a shell other than the Windows command prompt.

**Comment by ghogen** [comment]
Added a note to mention that if you are using a shell other than cmd, you might have to use single or double quotes.

**Comment by ghogen** [comment]
Reopening to discuss whether to do any global modifications to the content to add single or double quotes.

**Comment by ghogen** [comment]
Discussed and closing - customers who call MSBuild from a shell environment should refer to the documentation for their shell.
