### ISSUE TITLE
WHERE IS THE SEARCH

### ISSUE THREAD

**Issue by djfwalker** [MicrosoftDocs/visualstudio-docs#3854]
This documentation needs to be searchable, otherwise it is just not fit for purpose. It is definitely harder to use than msdn

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a9076d0-2cda-08cc-71e0-c1080a9fdd59
* Version Independent ID: b8caa4a1-f7ea-d439-4653-988dda48eebd
* Content: [Compiling building - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/compiling-and-building-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/compiling-and-building-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/compiling-and-building-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@djfwalker  Thanks for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
