### ISSUE TITLE
The Python development workload is no longer available for VS 2017

### ISSUE THREAD

**Issue by AaronAtDuo** [MicrosoftDocs/visualstudio-docs#3856]

**Comment by AaronAtDuo** [comment]
Per articles https://nicolaiarocci.com/python-workload-pulled-off-visual-studio-2017-rc3/ and https://nicolaiarocci.com/python-support-in-visual-studio-2017-or-the-lack-thereof/, the Python development workload was removed in RC 3 and never returned.  I can confirm that the 2017 Enterprise installer does not list the Python workload as available.

**Comment by TerryGLee** [comment]
@AaronAtDuo I took a look at the Visual Studio Installer and the Python workload is still there: 

<img width="643" alt="python-workload" src="https://user-images.githubusercontent.com/23244653/64211271-7cf01c80-ce5a-11e9-9bf0-40484d32ef96.png">

Then, I added the Python workload and can see it in the Open Project dialog box:

<img width="341" alt="python-in-IDE" src="https://user-images.githubusercontent.com/23244653/64211427-01429f80-ce5b-11e9-87b3-f882cce3169f.png">

I used the most recent release of Visual Studio 2017, which is 15.9.15, per this list: https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2017.

And, I modified my installation by using the instructions listed on this page: https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2017

Please note that the links you provided are dated and refer to a "release candidate" (i.e., a pre-release) of Visual Studio 2017.

**Comment by AaronAtDuo** [comment]
Interesting, I've somehow got a slightly older version of 2017:
![Selection_013](https://user-images.githubusercontent.com/26978047/64211995-f6493880-ce75-11e9-8f13-7af3a26e3b12.png)
I'll pull down 15.9.15, thanks.
