### ISSUE TITLE
What are the parameters for /catalogName? 

### ISSUE THREAD

**Issue by FrankHileman** [MicrosoftDocs/visualstudio-docs#3857]
I am not sure what is correct for Visual Studio 2019, since the help viewer version did not change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9932d702-581e-2183-2ea7-94e6973deedf
* Version Independent ID: 9fe7a5d4-81b2-884d-4fea-43e173a48e75
* Content: [Command-line arguments for the Help Content Manager - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/help-viewer/command-line-arguments?view=vs-2019)
* Content Source: [docs/help-viewer/command-line-arguments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/help-viewer/command-line-arguments.md)
* Product: **visual-studio-windows**
* Technology: **vs-help-viewer**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
The catalogName is VisualStudio15 and corresponds to the Catalogs subfolder on disk at C:\ProgramData\Microsoft\HelpLibrary2\Catalogs\VisualStudio15\

I will update these topics to reference this. I agree, it's not what you might expect.

**Comment by FrankHileman** [comment]
You might want to explain as well that the catalog is shared (this is the first time two VS versions shared the same catalog, to my knowledge).

**Comment by ghogen** [comment]
Topic updated.
