### ISSUE TITLE
FQDN related Visual Studio installation

### ISSUE THREAD

**Issue by tamatsuxyz** [MicrosoftDocs/visualstudio-docs#3859]
From the following doc, snapshot debugger requests to msvsmon as DNS endpoint.
But this is not FQDN. (I can’t search IP address in WHOIS)

Install and use Visual Studio and Azure Services behind a firewall or proxy server:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md

Service   or scenario | DNS   endpoint | Protocol | Port | Description
-- | -- | -- | -- | --
Snapshot    Debugger | 1.   go.microsoft.com    2. management.azure.com    3. *azurewebsites.net    4. *scm.azurewebsites.net   5. api.nuget.org/v3/index.json    6. msvsmon | 1.   https    2. https    3. http    4. https    5. https    6. Concord | 1.   443   2. 443   3. 80    4. 443   5. 443   6. 4022 (Visual Studio version dependent) | 1.   Query .json file for app service SKU size    2. Various Azure RM calls    3. Site warmup call via    4. Customer's targeted App Service Kudu endpoint    5. Query Site Extension version published in nuget.org    6. Remote debugging channel

What is the correct FQDN ?

**Comment by msebolt** [comment]
@tamatsuxyz Thank you for the question.

**msvsmon** is an executable that needs to be run on the machine.  More information can be found [here](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019).

I'll update the documentation to clarify.

**Comment by msebolt** [comment]
The documentation has been updated.

**Comment by tamatsuxyz** [comment]
Thanks @msebolt 

I saw document you showed, and I tried this function.
I suggest to change the following

Service or scenario | DNS endpoint | Protocol | Port | Description
-- | -- | -- | -- | --
Snapshot  Debugger | 1. go.microsoft.com  2. management.azure.com  3. *azurewebsites.net  4. *scm.azurewebsites.net 5. api.nuget.org/v3/index.json  6. **Remote Service/Servers IP address/FQDN** | 1. https  2. https  3. http  4. https  5. https  6. Concord | 1. 443 2. 443 3. 80  4. 443 5. 443 6. 4022 (Visual Studio version dependent) | 1. Query .json file for app service SKU size  2. Various Azure RM calls  3. Site warmup call via  4. Customer's targeted App Service Kudu endpoint  5. Query Site Extension version published in nuget.org  6. Remote debugging channel **([see also](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2019))**


All of NW admin don't know all of visual studio function. So, it's better to clarify more

**Comment by tamatsuxyz** [comment]
Sorry for rush submit

Additionally, I think both of these is lack of "."
3. *azurewebsites.net         => *.azurewebsites.net
4. *scm.azurewebsites.net  => *.scm.azurewebsites.net

It's different between *azurewebsites.net and *.azurewebsites.net.
The latter means all of sub-domain for azurewebistes.net. The former means XXXXazurewiebsites.net (e.x. testazurewebsites.net / aaaazurewebsites.net)

**Comment by msebolt** [comment]
Assigning this to the author now.

**Comment by TerryGLee** [comment]
@tamatsuxyz This is under review; FYI.

**Comment by tamatsuxyz** [comment]
thanks!

**Comment by ornellaalt** [comment]
Thanks for your feedback, @tamatsuxyz! The documentation has been updated.
