### ISSUE TITLE
Testing the new system

### ISSUE THREAD

**Issue by mgblythe** [MicrosoftDocs/visualstudio-docs#386]
Trying this out to see how it works on our content.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5416573b-dd99-f3c9-1707-32fb38023788
* Version Independent ID: 45ebd856-0161-4ea2-2833-d1ec165ebc97
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/improve-code-quality)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/improve-code-quality.md)

**Comment by WilliamAntonRohm** [comment]
#assign:WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
#unassign:WilliamAntonRohm
