### ISSUE TITLE
For VB Contract.ThrowIfNull does not supress CA1062

### ISSUE THREAD

**Issue by paul1956** [MicrosoftDocs/visualstudio-docs#3860]
Adding a Code.Contract Precondition as the error/warning instructions say does not suppress CA1062
```VB
 Public Function ConvertInputRequest(RequestToConvert As ConvertRequest) as Boolean
    Contract.ThrowIfNull(RequestToConvert,$"{NameOf(RequestToConvert)} cannot be Nothing")
    Dim languages As String() = {RequestToConvert.GetSourceExtension, RequestToConvert.GetTargetExtension}
```
The following does work to suppress the warning.
```VB
If RequestToConvert Is Nothing Then
    Throw New ArgumentException
End If
```
Also the message says Null Vs. Nothing where other messages gives separate instructions for VB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* Content: [CA1062](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1062)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@paul1956 Thank you for the feedback.

Can you verify if either of the following resolves the issue?

- https://stackoverflow.com/questions/15188631/code-analysis-rule-ca1062-behaviour (also points to https://github.com/dotnet/roslyn-analyzers/issues/2369)

- https://stackoverflow.com/questions/53448427/ca1062-not-evaluating-on-net-standard-2-0-class-library

**Comment by paul1956** [comment]
@msebolt, not really. They are both C# issues,
1) C# and VB don't handle Null/Nothing Strings the same. In VB a Null/Nothing String = "" so it is valid to pass it to a function expecting a String.
2) I am using the recommended way to check for Null a Contract that shouldn't be necessary for a String.

**Comment by paul1956** [comment]
There are 2 related issues, treatment of Null Strings and using Contract to address the issue.
```VB
 Public Function Y(OriginalText As String)
    Dim Text As String = OriginalText.Trim(" "c) ' There should be no warning here because if OriginalText is Nothing/Null or "" Text will be ""
```
```VB
 Public Function Y(OriginalText As String)
    Contract.ThrowIfNull(OriginalText ,"Error Message")
    Dim Text As String = OriginalText.Trim(" "c) 
```

**Comment by gewarren** [comment]
@paul1956 This sounds mostly like a problem with the analyzer itself rather than with the documentation, although we could add note to the "When to suppress warnings" section if the analyzer does not get changed. Can you please log an issue at https://github.com/dotnet/roslyn-analyzers/issues?

**Comment by paul1956** [comment]
Both, I already filed #2815 against the analyzer as you asked, but you should always suppress this for VB and Strings (until fixed when it will not apear for strings). Your VB example using String and the test is always unnecessary. You do want an example but it should not use String.

**Comment by gewarren** [comment]
Thanks, I agree the example for VB is bad. We'll also update the When to suppress section.

**Comment by gewarren** [comment]
The [roslyn-analyzers issue](https://github.com/dotnet/roslyn-analyzers/issues/2815) was closed as not reproducible, but the docs should still be updated.

**Comment by Mikejo5000** [comment]
Updated content link

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22041](https://github.com/dotnet/docs/issues/22041)
