### ISSUE TITLE
How to add a specific version of  a component?

### ISSUE THREAD

**Issue by cfahrenholz** [MicrosoftDocs/visualstudio-docs#3861]
The --add switch always adds the latest version of a workload or components.
How can I update to a specific (previous) version of a component?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@cfahrenholz Thank you for the question.

Workload components are tied directly to the version of Visual Studio you're using, so upgrades/rollbacks require you to install a different version of Visual Studio.

For Visual Studio upgrades (or previous versions), use the `--installPath` (see [command line parameters](https://docs.microsoft.com/visualstudio/install/use-command-line-parameters-to-install-visual-studio#install-options)) and use a version selected from the [releases history](https://docs.microsoft.com/visualstudio/releases/2019/history).

There's an active debate about this issue [here](https://developercommunity.visualstudio.com/idea/395028/introduce-the-ability-to-roll-back-a-visual-studio.html) if you'd like to contribute or create a new feature request specifically for workload components.
