### ISSUE TITLE
Reporting without VS

### ISSUE THREAD

**Issue by VanAwful** [MicrosoftDocs/visualstudio-docs#3862]
My issue is such I can not access VS to report the issue. This page provides no information on how to report the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#feedback)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by msebolt** [comment]
@VanAwful  Thank you for the feedback.

Please refer to https://github.com/MicrosoftDocs/visualstudio-docs/issues/3245.
