### ISSUE TITLE
CA1824 Dropdown Grayed out in Application Section for VB Core 3.0

### ISSUE THREAD

**Issue by paul1956** [MicrosoftDocs/visualstudio-docs#3867]
Warning CA1824 Mark assemblies with NeutralResourcesLanguageAttribute, instructions don't work for VB Core 3.0 WinForm or SDK projects becuase the button is grayed out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* Content: [CA1824](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1824-mark-assemblies-with-neutralresourceslanguageattribute?view=vs-2019)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@paul1956  Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by gewarren** [comment]
@paul1956 Did you look on the Package tab of the properties pages? I was not able to create a VB WinForms .NET Core app, but this is what it looks like for a VB console app:

![image](https://user-images.githubusercontent.com/24882762/64381617-755e7e00-cfe8-11e9-9b60-62d8cbde75c3.png)

**Comment by paul1956** [comment]
Yes that is the information I was looking for. I missed the purple comment that it is under the package tab. The grayed out option confused me.
