### ISSUE TITLE
How to set TimeoutAttribute for test method?

### ISSUE THREAD

**Issue by gazette2** [MicrosoftDocs/visualstudio-docs#387]
I've tried like this:

		BEGIN_TEST_METHOD_ATTRIBUTE(TestMethod1)
		        TEST_METHOD_ATTRIBUTE(L"Timeout", "1000")
		END_TEST_METHOD_ATTRIBUTE()

but it's not working properly as I intended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3ec17-4193-8059-56de-fbad2fab239c
* Version Independent ID: e0e84806-41ff-fa5e-1aa1-775beed16d78
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md)

**Comment by nickuhlenhuth** [comment]
Hi @gazette2 ,
Please follow the instructions for [Setting a Time-Out  Period for All Tests](https://msdn.microsoft.com/en-us/library/ms243175.aspx#Anchor_0). Hopefully this solves your problem!
If you don't feel like the above solution addresses your needs, please feel free to file an issue on our [UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide).
Cheers!

**Comment by mikeblome** [comment]
The latest docs are actually here: https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics . On the right you'll see a link to the heading called "Set timeouts for unit tests". Please let us know if there's something missing there!
