### ISSUE TITLE
Suppress compiler warnings

### ISSUE THREAD

**Issue by AroglDarthu** [MicrosoftDocs/visualstudio-docs#3871]
Related to: https://github.com/MicrosoftDocs/visualstudio-docs/issues/3230

> Solution Explorer -> Properties -> Code Analysis Settings:
> NOTE: This property page has been deprecated and will be removed in a future product release.

It was possible to also suppress `CS1591:Missing XML comment for publicly visible type or member` for generated code via that properties page (Solution Explorer -> Properties -> Code Analysis Settings).

How can this be established now?
I have tried the following, but that does not seem to work, as it is a compiler warning and not a code analysis warning?
`[assembly: SuppressMessage("Compiler", "CS1591", Justification="Generated Code", Scope="namespaceanddescendants", Target="MyNamespaceContainingGeneratedCode")]`

The only option I see at the moment, is to move all generated code to a separate project and just set `<noWarn>1591</noWarn>` in the project file. A viable option, but it falls short if you want to add your own logic to some of the generated `partial` classes.

_Originally posted by @AroglDarthu in https://github.com/MicrosoftDocs/visualstudio-docs/issues/3230#issuecomment-528384214_

**Comment by gewarren** [comment]
Actually I believe this should go to @ghogen.

**Comment by ghogen** [comment]
@AroglDarthu Have you looked at https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings?view=vs-2019 ?

**Comment by AroglDarthu** [comment]
I did. But it doesn't help. That way warnings can only be suppressed for the entire project or for specific NuGet package references.
The aim is to suppress a specific warning, like CS1591, for generated code only. For instance a ServiceReference. It is not really an option to add `pragma disable` to the generated code, as it will be overwritten at the next generation.

**Comment by ghogen** [comment]
I think the docs are correct and it's not supported in the current product design. You're welcome to submit a feature request - please file at https://developercommunity.visualstudio.com/spaces/8/index.html?all

**Comment by AroglDarthu** [comment]
> I think the docs are correct and it's not supported in the current product design. You're welcome to submit a feature request - please file at https://developercommunity.visualstudio.com/spaces/8/index.html?all

Done: https://developercommunity.visualstudio.com/idea/887015/suppress-warning-for-generated-code.html
