### ISSUE TITLE
Mention embeded analyzer configuration files in FxCop analyzer NuGet package starting 2.9.5 release

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3873]
See https://github.com/dotnet/roslyn-analyzers/pull/2818

Starting 2.9.5 (not yet published), we will embed the analyzer configuration files in each analyzer NuGet package. This page can contain the set of available options in the latest packages. Users that are on older packages can use the embedded documentation file in the NuGet package to check the available options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b376237-1957-7b92-899d-0c816dac5412
* Version Independent ID: 0a02458c-2f69-80c3-4215-436f2250ced0
* Content: [FxCop analyzer configuration options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzer-options?view=vs-2019)
* Content Source: [docs/code-quality/fxcop-analyzer-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/fxcop-analyzer-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani Hi Manish. I see that 2.9.5 is released, but I'm not finding the embedded configuration file. Is it in the 'editorconfig' folder?

**Comment by mavasani** [comment]
@gewarren it should be in `.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.5\documentation\Analyzer Configuration.md`

As an aside, we should also document the embedded helper editorconfig files analogous to the helper rulesets inside `\.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.5\editorconfig`. Do you want me to file a separate issue at https://docs.microsoft.com/en-us/visualstudio/code-quality/analyzer-rule-sets?view=vs-2019?
