### ISSUE TITLE
Dictionary/Words/Compound/Term[@CompoundAlternate] Does Not Work

### ISSUE THREAD

**Issue by MadQ** [MicrosoftDocs/visualstudio-docs#3875]
In a legacy application, we have a lot of occurrences of the term "Username" (lower case "n"), which correctly causes CA1702 errors/warnings. i.e.:
     warning CA1702: Microsoft.Naming : The discrete term 'Username' in member name '[redacted]' should be expressed as a compound word, 'UserName'

Adding this:
    &lt;Term CompoundAlternate="Username"&gt;username&lt;/Term&gt;
to the Dictionary/Words/Compound section, the expectation is that "Username" should no longer cause CA1702 warnings/errors.

However, adding the CompundAlternate only changes the message to this:

    warning CA1702: Microsoft.Naming : The discrete term 'Username' in member name '[redacted]' should be expressed as a compound word, 'Username'.

Note the lower case "n" in both instances of the term "Username". 

Refactoring all occurrences of "Username" is not feasible, ans suppressing literally thousands of CA violations is not desirable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c0c5937-e895-d2e3-0e14-655cf4e52d6a
* Version Independent ID: abe9dea4-c830-c476-1e9d-fd2386d014c3
* Content: [How to: Customize the Code Analysis Dictionary - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-customize-the-code-analysis-dictionary?view=vs-2017#BKMK_DictionaryWordsCompoundTermCompoundAlternate)
* Content Source: [docs/code-quality/how-to-customize-the-code-analysis-dictionary.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-customize-the-code-analysis-dictionary.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@MadQ Thank you for the feedback.

This is product-related and might be better suited for the [Roslyn issues](https://github.com/dotnet/roslyn/issues) queue.

@gewarren Can the issue be transferred there?

**Comment by gewarren** [comment]
My suggestion is to add `username` as a [Recognized word](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-customize-the-code-analysis-dictionary?view=vs-2017#BKMK_DictionaryWordsRecognizedWord) instead of as a CompoundAlternate.

Note that this rule [CA1702 is deprecated](https://github.com/dotnet/roslyn-analyzers/issues/711) for FxCop analyzers.

**Comment by MadQ** [comment]
@gewarren <https://github.com/gewarren> I actually did try adding it as
a Recognized word, with the same result. I tried quite a few other things,
which are probably not relevant. Since it is a legacy application, we try
to touch it as little as possible; I just happened to be updating the
ruleset for the TFS project, and was trying to minimize the number of build
warnings. As it stands now, there are so many warnings that the important
ones are being lost in the noise. We probably cannot justify the time to
switch that one solution over to FxCop analyzer, which I am doing for all
the active ones.

Thank you all for the replies. For the most part, I just wanted to add the
issue to the documentation to possibly save others the time, effort and
frustration I went through. Due to binary CA being deprecated, I don't
really expect it to be fixed.

  -- Quinten Martens

**Comment by gewarren** [comment]
Ah okay, sorry that didn't work either.

Since this is a product issue, you'd need to log it through "Report a Problem" in Visual Studio. However, as you noted, it's not likely to be fixed at this point.

I'm closing this issue now, but it will still appear associated with the referenced topic.
