### ISSUE TITLE
No reference to program languages 

### ISSUE THREAD

**Issue by lds0m01** [MicrosoftDocs/visualstudio-docs#3876]
There should be a topic about program languages with a sub-topic for each language supported. This is the first topic from Visual Studio menu Help/view help so there needs to be a way to get to help with languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ae1727-4def-5921-86ec-bc65e9f0b8e4
* Version Independent ID: aed7dda1-6bfd-945f-04a5-86ee0fe62d95
* Content: [Overview of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-studio-ide?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3Den-US%26k%3Dk(MSDNSTART)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/get-started/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-studio-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
Assigning this to Gordon who will make the VS hub page the new target page for the MSDNSTART F1 keyword, which maps to the Help menu entry.

**Comment by gewarren** [comment]
Verified the new behavior so closing this issue.
