### ISSUE TITLE
NoWin32Manifest listed twice in https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md

### ISSUE THREAD

**Issue by cdorst** [MicrosoftDocs/visualstudio-docs#388]
Hello, I noticed that NoWin32Manifest is under the "List of Common Properties and Parameters" twice (each with different descriptions). The first occurrence also appears out of alphabetical order.

Is this intentional? Should these items be merged?

https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md

**Comment by mikeblome** [comment]
Thanks cdorst! Yes that was an error. I removed the first entry and merged it into the second one. Should be visible on public site after the new year.
