### ISSUE TITLE
Remote tools for Visual Studio 2019 - invalid link

### ISSUE THREAD

**Issue by Mikilll94** [MicrosoftDocs/visualstudio-docs#3881]
The link for remote tools for Visual Studio 2019 is invalid.

Here is the link:

https://visualstudio.microsoft.com/downloads#remote-tools-for-visual-studio-2019

It follows to Visual Studio 2019 download page, not to remote tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4215ecb-721f-9b0b-66ae-042ffd7c9842
* Version Independent ID: 0d58ec46-8b09-f184-24f3-ac53ac0d1b50
* Content: [Remote Debug ASP.NET Core on a Remote IIS Computer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-computer?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikilll94 -- I checked that link in the article and it is working for me.  Can you please elaborate?

**Comment by Mikilll94** [comment]
@WilliamAntonRohm 
The link is working but it is not pointing to the site where you can download Remote tools for Visual Studio 2019.

Just check it:
https://visualstudio.microsoft.com/downloads#remote-tools-for-visual-studio-2019

From this link you can download only Visual Studio 2019 - NOT the remote tools.

**Comment by Mikejo5000** [comment]
@Mikilll94 For me, that link does get me to the "remote tools". What browser are you using? There was (is) an issue for the link not working if you need to update your license.

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000, thank you for stepping in to help.

@Mikilll94 -- this is what I see:

![download](https://user-images.githubusercontent.com/27738025/64737914-cbc53400-d4a2-11e9-9901-a03b7a87cd79.png)

**Comment by WilliamAntonRohm** [comment]
@Mikilll94 -- thank you for the followup.  
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
