### ISSUE TITLE
Additional Info

### ISSUE THREAD

**Issue by shazam19** [MicrosoftDocs/visualstudio-docs#3883]
These assemblies are available as nuget packages. Which in fact you should use anyway if you have CI/CD implemented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97e75d6-dc3e-800e-7cff-d097023df034
* Version Independent ID: 89401b4f-16db-66ab-512c-cce9f949ac10
* Content: [How to: Install Office primary interop assemblies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-office-primary-interop-assemblies?view=vs-2019#feedback)
* Content Source: [docs/vsto/how-to-install-office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-install-office-primary-interop-assemblies.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
It does look like someone has created a Nuget package for these but I don't believe it was created by us .
