### ISSUE TITLE
"Test adapter NuGet reference" section missing

### ISSUE THREAD

**Issue by IGx89** [MicrosoftDocs/visualstudio-docs#3887]
Hello! The "Test adapter NuGet reference" section appears to be missing. It's in the latest document on GitHub (and wasn't added recently) but is completely missing here. HTML rendering issue perhaps?

Edit: it appears the issue is that I was looking at the VS2019 version of the page but that section is labeled for only VS2017. That topic is still very relevant for VS2019 however (following its instructions just fixed my issue in VS2019), so the solution here would seem to be making it show for VS2017 and later, instead of just VS2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fa1671-f27f-484e-8994-ceb85b1a73d6
* Version Independent ID: 5b90e41e-b4ba-7cb7-b798-59ea1ae38eb4
* Content: [Test Explorer FAQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq?view=vs-2019)
* Content Source: [docs/test/test-explorer-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/test-explorer-faq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by kendrahavens** [comment]
@IGx89 Thank you for the note! I had incorrectly supposed folks would stop hitting this by VS2019. We also removed the 'fallback to vsix test adapter' check boxes in VS2019. I'll remove the VS2017 moniker so the section is apparent all the time.
