### ISSUE TITLE
Typo fix

### ISSUE THREAD

**Issue by Walt-White** [MicrosoftDocs/visualstudio-docs#389]
Step 2 in Debugging has incomplete sentence.  Should be something like "Press any key to close the window."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d684aa29-fb98-1d88-a930-89813a98eb17
* Version Independent ID: db38dce1-01d0-dc84-da3f-67cd925dd134
* [Content](https://docs.microsoft.com/en-us/visualstudio/python/vs-tutorial-01-04)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/python/vs-tutorial-01-04.md)

**Comment by kraigb** [comment]
Thanks! This is addressed in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1192, which you may not be able to see because it's in our private repo.
