### ISSUE TITLE
Professional edition does not appear in the September usage pricing sheet?

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/visualstudio-docs#3896]
I looked back over all the price sheets available and Enterprise is listed twice as expected, Professional is absent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f413cb5d-d6c4-2036-62e2-0af9b041ade3
* Version Independent ID: 7c96f714-fb4f-a578-546e-2cfba9366d76
* Content: [Visual Studio cloud subscription purchasing for CSPs](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-csp)
* Content Source: [subscriptions/vscloud-csp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-csp.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by msebolt** [comment]
@jonwbstr Thank you for the feedback, adding the author.

@evanwindom Please review and make any changes as needed.

**Comment by evanwindom** [comment]
@jonwbstr - I've passed your feedback along to the Visual Studio marketing team for investigation.

**Comment by evanwindom** [comment]
@jonwbstr - Since we haven't heard from you, we're going to close this issue.  Please let us know if you're still seeing problems with current lists.

**Comment by evanwindom** [comment]
@TerryGLee - Please close

**Comment by TerryGLee** [comment]
@evanwindom Closing per request.
