### ISSUE TITLE
Microsoft.Common.targets does not contain a single <Target> anymore.

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [MicrosoftDocs/visualstudio-docs#3900]
It might have in the past, but the target definitions apparently moved to C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868d865b-89d9-ec87-d569-862d168dc6ca
* Version Independent ID: a95f34e2-8f4b-4a4b-cb7e-075e4ceebd69
* Content: [Extend the build process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2019)
* Content Source: [docs/msbuild/how-to-extend-the-visual-studio-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-extend-the-visual-studio-build-process.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, this looks like a VS 2019 change, is that right? I'll plan to update this.

**Comment by rainersigwald** [comment]
That change happened quite a while ago, actually--looks like dev12. Instead of referring to the new file everywhere, I'd say it "contains _or imports_ targets", and mention that the bulk of it is in `Microsoft.Common.CurrentVersion.targets`.

I don't want to change everything to point to `CurrentVersion`, because that's mostly an implementation detail--projects/SDKs should continue to import `Microsoft.Common.targets`.

**Comment by rainersigwald** [comment]
Actually, I might prefer an edit to the article that mentions both physical files but refers to them in the abstract as "the common targets" like

```diff
- You can guard against unintended overrides of targets by overriding the DependsOn properties that are used in `DependsOnTargets` attributes throughout the *Microsoft.Common.targets* file.
+ You can guard against unintended overrides of targets by overriding the DependsOn properties that are used in `DependsOnTargets` attributes throughout the common targets.
```

**Comment by Mikejo5000** [comment]
OK, thanks, I'll update the doc.

Is it OK on first mention to bring up Microsoft.Common.targets? I'm concerned that new users might wonder what we're talking about with no context for it. Suggested first bullet point (in the intro):

- Overriding specific predefined targets defined in the common targets (*Microsoft.Common.targets* or the common *.targets* file that it imports).

I'm guessing that it is probably too much of an implementation detail to tell them to check CommonTargetsPath in Microsoft.Common.targets for the filename?

**Comment by rainersigwald** [comment]
I'd just say "... or the files that it imports".

> I'm guessing that it is probably too much of an implementation detail to tell them to check CommonTargetsPath in Microsoft.Common.targets for the filename?

I'd say yes: no one should have to know about CommonTargetsPath.
