### ISSUE TITLE
<DisableFastUpToDateCheck>true</DisableFastUpToDateCheck> is also required for regular builds, not just "Debug -> Start Debugging" runs.

### ISSUE THREAD

**Issue by Science-and-Motion-Sports** [MicrosoftDocs/visualstudio-docs#3904]
When I do not set the `DisableFastUpToDateCheck` property to true and press on "Build Solution" or "Build ProjectName", then Visual Studio 2019 v16.2.5 just prints the following:

> ========== Build: 0 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

This means, that msbuild was not run. Howver, the documentation states, that this behavior is only expected when using "Debug -> Start Debugging".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1010063-a8b2-7ff9-4ad6-10eebde154c3
* Version Independent ID: 1202745a-e34a-aabd-7cde-337726579377
* Content: [Visual Studio Integration (MSBuild)](https://docs.microsoft.com/en-us/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/visual-studio-integration-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/visual-studio-integration-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Science-and-Motion-Sports Thanks! I'll update the doc.
