### ISSUE TITLE
Typo Error in Step 3 of the Create Project Section

### ISSUE THREAD

**Issue by Sean-LeBlanc** [MicrosoftDocs/visualstudio-docs#3905]
In Step 3 it says "Then name the file HelloWorld." This should be corrected to "Then name the file WhatIsYourName." In order to properly reflect the tutorial project being made and align with the image reference for the step below it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f3b242-e5be-0e07-79bf-c3f1652d3861
* Version Independent ID: 61c049c6-c028-692e-5b76-5cd8cb0ea020
* Content: [Tutorial: Get started with Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-basic/tutorial-console?view=vs-2017#feedback)
* Content Source: [docs/get-started/visual-basic/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-basic/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@Sean-LeBlanc Thank you for the feedback.

The documentation has been updated.
