### ISSUE TITLE
Missing subscription level in the Eligibility table

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/visualstudio-docs#3907]
My specific subscription is not listed.  It is 

> Visual Studio Enterprise (MPN)

 When I view the benefit in my.visualstudio.com it shows me

> This benefit is currently unavailable for new activations while we make important 

Any idea what this means for me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b2872e-438a-b86e-9ff5-6dc0021f3fe8
* Version Independent ID: 8b9e935e-07ad-4992-edb9-e8361d867617
* Content: [EMS Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ems#feedback)
* Content Source: [subscriptions/vs-ems.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-ems.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@JeremyTBradshaw - Thanks for reaching out.  The MPN subscriptions are part of the NFR list that's referenced in the first line of the eligibility table and detailed in the first footnote as follows:  
"1 Includes: Not for Resale (NFR), Visual Studio Industry Partner (VSIP), Microsoft Partner Network (MPN), FTE, MCT Software & Services Developer, BizSpark. Excludes: Most Valuable Professional (MVP), Regional Director (RD), MCT Software & Services, Imagine, Microsoft Partner Network (Professional)."

EMS is not currently accepting new sign-ups as we're making some updates and resolving a technical issue.  I hope to have news on this soon.  Thank you for your patience.  

Are you on your own tenant, or part of an organization?

**Comment by JeremyTBradshaw** [comment]
@evanwindom - Thanks for pointing me to that, I completely missed it 🤦‍♂️!  I am a mix, I have activated the benefit twice in the past - 1st year into my own tenant, 2nd year into my company's.  I'm still all set for ~1 month, so was just checking into it while doing some planning for upcoming things I'll have on the go.  I also have some E3 IUR licenses available to hold me over after that.

Glad to hear the benefit isn't leaving MPN subscription🙏.

**Comment by r0bu** [comment]
Hi, is there any update on when EMS sub will be resolved?
