### ISSUE TITLE
Out of date?

### ISSUE THREAD

**Issue by ptoye** [MicrosoftDocs/visualstudio-docs#391]
The toolbox in VS 2017 does not have any tabs at all.  Does this page refer to an outdated version of VS? It seems that way because the links at the bottom are all out of date.

Also, the Auto-hide button is greyed out (in my VS 2017 Community), so there might be a mistake in the firsts paragraph.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f92855d-5247-0ffa-ef6f-cb654d7b26a7
* Version Independent ID: 54b3a6ba-badb-29c0-f3b4-f013414263aa
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/reference/toolbox)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/reference/toolbox.md)

**Comment by TerryGLee** [comment]
Thanks for your inquiry, @ptoye. We will investigate this. (Please be advised that due to the holidays, our response might be delayed.)

**Comment by AraHaan** [comment]
It also seems that ``C26490``, ``C26425``, ``C26485``, and ``C26425`` which have been complaining on my good code and wont shut up necause I need direct use of some Windows API functions the C++ standard library never calls or other things like:

Caching the ``HINSTANCE`` of ``hDLL of ``DllMain()`` in an global variable for passing into ``Shell_NotifyIcon`` Unless I can use the process's ``HWND`` instead that I cache in an ``setup`` struct.

Another instance of that warning is when I need to pass the ``HWND`` handle of the process to an global instance of an struct for subclassing the target application's WndProc for telling the OS to never go into ``SC_SCREENSAVE`` and ``SC_MONITORPOWER`` by returning 0 from WndProc to ``cancel`` those syscommands while the process is running.

**Comment by gewarren** [comment]
@AraHaan your issue sounds very different to the subject of this issue, which is that the [Toolbox topic](https://docs.microsoft.com/en-us/visualstudio/ide/reference/toolbox) is out of date. Is your issue a product issue or a documentation issue?

**Comment by AraHaan** [comment]
I think more of an doc issue.

**Comment by gewarren** [comment]
@AraHaan Can you create a new issue in this repo to track your code analysis issues? That way we can assign it to the proper person to fix it. Thanks for helping to improve the documentation.

**Comment by AraHaan** [comment]
alright.

**Comment by gewarren** [comment]
@ptoye thanks for creating this issue. I am updating the topic and it should be live in a couple days. I fixed the broken links (thank you!). The auto-hide option is still applicable. Also, you will not see any tabs in Toolbox if you are in a project type where Toolbox items are not applicable - e.g. a console application. To see the tabs, create something with a designer, for example a Windows Forms app.
