### ISSUE TITLE
Management through API

### ISSUE THREAD

**Issue by davidcorrigan714** [MicrosoftDocs/visualstudio-docs#3910]
There should probably be a section added to detail using the Azure Service Management API to manage license subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82cfbc2f-5cd9-4e63-15e5-f1c41b6d9822
* Version Independent ID: 7e460208-140c-0a87-a1fb-a47690fb0f06
* Content: [Get started with the Subscriptions Administration Portal](https://docs.microsoft.com/en-us/visualstudio/subscriptions/using-admin-portal)
* Content Source: [subscriptions/using-admin-portal.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/using-admin-portal.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@davidcorrigan714  - Are you talking about using the API to assign subscriptions, or Visual Studio IDE licenses specifically?

**Comment by davidcorrigan714** [comment]
I'm referring to listing and assigning subscriptions. Basically all the REST endpoints available at https://manage.visualstudio.com/_apis/Agreement/ which I've never found docs for. Really just mentioning that the API Permission exist and applies to this page would go a long way. In my case we just needed a programmatic way to keep track of subscriptions against our HR database and there was no documented way to do so as far as I know.

**Comment by evanwindom** [comment]
@davidcorrigan714 - Hi David.  We don't have anything publicly available to manage subscriptions through an API.  Our engineering team is interested in hearing from you about your use case, etc.  If you're interested in working with them, please email vssub_team@microsoft.com.

**Comment by evanwindom** [comment]
#please-close

**Comment by davidcorrigan714** [comment]
@evanwindom I just tried emailing them and it bounced back as undeliverable.

**Comment by evanwindom** [comment]
@davidcorrigan714 - It's a new alias.  Let me check on that and get back with you.

**Comment by evanwindom** [comment]
@davidcorrigan714 - Please give it another try.  I believe the alias just needed to replicate.  It should be available to you now.
