### ISSUE TITLE
debug.print varA

### ISSUE THREAD

**Issue by dmcphaden** [MicrosoftDocs/visualstudio-docs#3911]
https://docs.microsoft.com/en-us/dotnet/visual-basic/misc/bc30800

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a958f3e5-0207-69f7-4fc9-82ac080fa7fc
* Version Independent ID: 8b02b646-01ba-5350-049f-1a31ec4780d4
* Content: [Immediate Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/immediate-window?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ImmediateWindow)%3Bk(vb.In)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.7.2)%3Bk(DevLang-VB)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/ide/reference/immediate-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/immediate-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
Closing this now, please comment below if there are any issues.
