### ISSUE TITLE
No description for: Enable nullable reference analysis

### ISSUE THREAD

**Issue by pgmagid** [MicrosoftDocs/visualstudio-docs#3913]
Looking for description of:
enable nullable reference analysis IDE features

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41602f7-2c5e-bf2a-9eab-50740dd10784
* Version Independent ID: c6b1f7c4-eb2d-a62a-7e1b-eb32b8a88947
* Content: [Options, Text Editor, C#, Advanced - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.CSharp.Advanced)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/ide/reference/options-text-editor-csharp-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-advanced.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
According to https://github.com/dotnet/roslyn/issues/38443#issuecomment-528142550 this option may go away in Visual Studio 2019 version 16.4. @ryzngard Can you clarify exactly what this option enables in the IDE? https://github.com/dotnet/roslyn/pull/35022 suggests Quick Info plus other things.

**Comment by jasonmalinowski** [comment]
We're planning on removing the checkbox in 16.4 with [this pull request](https://github.com/dotnet/roslyn/pull/38689). Turning the checkbox off only has the effect of not doing nullable analysis in the IDE, which is something we'd only tell users to do if something was broken and they were seeing perf/reliability issues. Assuming we're not seeing widespread issues it's being removed in 16.4.

**Comment by gewarren** [comment]
Closing this issue since we're not going to document the checkbox due to its short life.
