### ISSUE TITLE
Add documentation for new Usability rule CA2246 (AssigningSymbolAndItsMemberInSameStatement)

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3916]
1. Does not exist in legacy FxCop and was implemented recently in FxCop analyzers, should be first available in 2.9.5 package. It is C# only rule.
2. Rule implementation is here: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Core/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs. Original PR implementing the rule: https://github.com/dotnet/roslyn-analyzers/pull/2717
3. Rule diagnostic message and description are defined in `MicrosoftCodeQualityAnalyzersResources.resx`:
```
  &lt;data name="AssigningSymbolAndItsMemberInSameStatementDescription" xml:space="preserve"&gt;
    &lt;value&gt;Assigning to a symbol and its member (field/property) in the same statement is not recommended. It is not clear if the member access was intended to use symbol's old value prior to the assignment or new value from the assignment in this statement. For clarity, consider splitting the assignments into separate statements.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AssigningSymbolAndItsMemberInSameStatementMessage" xml:space="preserve"&gt;
    &lt;value&gt;Symbol '{0}' and its member '{1}' are both assigned in the same statement. You are at risk of assigning the member of an unintended object.&lt;/value&gt;
  &lt;/data&gt;
  &lt;data name="AssigningSymbolAndItsMemberInSameStatementTitle" xml:space="preserve"&gt;
    &lt;value&gt;Assigning symbol and its member in the same statement.&lt;/value&gt;
  &lt;/data&gt;
```
4. Unit tests for reference: https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/UnitTests/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatementTests.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efeb8cf2-d939-bb4e-3853-a6cf7a6c561f
* Version Independent ID: 01010ef0-bf36-9e98-1047-3f63c925bdb1
* Content: [Usage Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/usage-warnings?view=vs-2019)
* Content Source: [docs/code-quality/usage-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/usage-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by maxkoshevoi** [comment]
New location for rule implementation: https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatement.cs

New location for rule unit tests: https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/QualityGuidelines/AssigningSymbolAndItsMemberInSameStatementTests.cs
