### ISSUE TITLE
This sample from above makes no sense

### ISSUE THREAD

**Issue by kzu** [MicrosoftDocs/visualstudio-docs#392]
```
public async System.Threading.Tasks.Task<object> CreateService(IAsyncServiceContainer container, CancellationToken cancellationToken, Type serviceType)  
{
    STextWriterService service = null;  
    await System.Threading.Tasks.Task.Run(() => {  
                service = new TextWriterService(this);  
         });  

    return service;  
}
```

why wouldn't you do:

```
public System.Threading.Tasks.Task<object> CreateService(IAsyncServiceContainer container, CancellationToken cancellationToken, Type serviceType) => Task.FromResult(new TextWriterService(this));
```

??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4999b84e-a7f2-1ffc-6d02-d439ff0330de
* Version Independent ID: 7755af16-b4f5-e3b8-798f-35ea143ad306
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-provide-an-asynchronous-visual-studio-service)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/how-to-provide-an-asynchronous-visual-studio-service.md)

**Comment by gregvanl** [comment]
Thanks for your feedback. The sample has been updated and will be published shortly.
