### ISSUE TITLE
Incorrect step

### ISSUE THREAD

**Issue by timothytrimble** [MicrosoftDocs/visualstudio-docs#3920]
In "Select the standard Web Application template with No Authentication and click OK." The OK should be Create, per the screenshot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a870722a-3325-154a-6a06-5395af357222
* Version Independent ID: d595975b-8308-7d3b-b171-ae5a1ee782a8
* Content: [ASP.NET Core web app with Entity Framework & Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-01?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-01.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-01.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@timothytrimble Thank you for the feedback.

The documentation has been updated.
