### ISSUE TITLE
Incorrect screen for Step 1.

### ISSUE THREAD

**Issue by timothytrimble** [MicrosoftDocs/visualstudio-docs#3921]
The graphic for Step 1 shows "bundleconfig.json" in the list. It should not be there per the previous steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2376dee-30e0-850f-7572-6d32b351be3f
* Version Independent ID: 9c06f47f-8195-4736-3575-fffe1c51f763
* Content: [Tutorial: Get started with C# and ASP.NET Core](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@timothytrimble Thank you for the feedback.

The documentation has been updated and is pending review.

**Comment by TerryGLee** [comment]
@msebolt Thanks for your PR; the updated screenshot should go live by noon today. (And @timothytrimble - Thanks for helping us improve the documentation!)

**Comment by msebolt** [comment]
The documentation has been updated.
