### ISSUE TITLE
Missing step in "Run, Debug, Make Changes"

### ISSUE THREAD

**Issue by timothytrimble** [MicrosoftDocs/visualstudio-docs#3922]
The Note box in step 1 should also include:
"Approval request for storing Cookies might appear. Please accept to continue to the next step."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2376dee-30e0-850f-7572-6d32b351be3f
* Version Independent ID: 9c06f47f-8195-4736-3575-fffe1c51f763
* Content: [Tutorial: Get started with C# and ASP.NET Core](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@timothytrimble Thank you for the feedback.  

It appears the message you're getting is based on the browser settings.  

We currently don't support browser-specific instruction sets, but if you'd like to include the browser you're using it would be helpful for further reference.

**Comment by timothytrimble** [comment]
Matthew,

I am using the latest version of Chrome on Mac. Thanks for checking.

Tim
________________________
testimonium dominus ergo sum - TimothyTrimble.com
IG: TimothyTrimble
FB: IamTimothyTrimble
Jw.org

**Comment by msebolt** [comment]
Hi Timothy, thank you for the clarification.

Closing the issue now.
