### ISSUE TITLE
Add documentation for new Performance rule CA1829 (UsePropertyInsteadOfCountMethodWhenAvailableAnalyzer) in FxCop analyzers

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#3923]
1. Does not exist in legacy FxCop
2. Rules Implementation:
    * https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Core/Performance/UsePropertyInsteadOfCountMethodWhenAvailable.cs#L21
3. Rules message and description:
    * https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/Core/MicrosoftNetCoreAnalyzersResources.resx#L1137-L1145
4. Unit tests:
    * https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.NetCore.Analyzers/UnitTests/Performance/UsePropertyInsteadOfCountMethodWhenAvailableTests.cs
5. The analyzers already have the following URLs assigned:
    CA1829: https://docs.microsoft.com/visualstudio/code-quality/ca1829

/cc @mavasani

**Comment by mavasani** [comment]
Documentation for this rule was requested on developer community at https://developercommunity.visualstudio.com/content/problem/897563/missing-documentation-ca1829.html

**Comment by lhj42** [comment]
Since this was closed I tried to see if the documentation was online but does not seem so. Is this pending a release or has it been closed without resolution?

**Comment by paulomorgado** [comment]
This issue has been closed yesterday by PR https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6468.

It's probably waiting for a release.
