### ISSUE TITLE
borken dockerfile

### ISSUE THREAD

**Issue by ade90036** [MicrosoftDocs/visualstudio-docs#3924]
Hi, i have spent the last 2 days at battling to generate a docker image which could build a vs studio project c++.

First of all, i have 20 years experience in the field of computer science and i could never imagine that i would say this: "oh, Microsoft, what have you done???"

The status of the docker support for window is appalling, mine as well advertise as experimental, Beta at best.
You need to ditch the HyperV virtualization engine from scratch.

You have already lost a battle in the containerization space and where others now also provide containerization with GPU passthrought, you are still left at having problems supporting basic Windows OS compatibility.

Not to mention the process isolation vs hyperv on the VM, which doesn't work.

What a mess..

I would strongly encourage the engage 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ade90036 -- Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

You may find the following links helpful for your implementation:
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
