### ISSUE TITLE
.runsettings file: how to configure connection string information?

### ISSUE THREAD

**Issue by bertrandpons** [MicrosoftDocs/visualstudio-docs#3925]
Hello,

Question based on the following documentation: https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

Could you please indicate how to set connection string within .runsettings file?

Thank you

**Comment by gewarren** [comment]
@AbhitejJohn Would you specify a connection string in the [TestRunParameters](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#testrunparameters) section?

**Comment by AbhitejJohn** [comment]
@gewarren : you could, yes. From [here](https://stackoverflow.com/questions/55813638/recommendations-on-runsettings-file-for-connection-string-override) though it looks like the intent is to use this in a data driven test context though. TestRunParameters wouldn't work here cause it needs to be plugged in through an attribute. 
@bertrandpons : could you please file an issue at https://github.com/microsoft/testfx for alternatives please?

**Comment by bertrandpons** [comment]
@AbhitejJohn thank you for your reply. I filed the issue at https://github.com/microsoft/testfx
