### ISSUE TITLE
Controlling the generated folder structure.

### ISSUE THREAD

**Issue by taori** [MicrosoftDocs/visualstudio-docs#3927]
I was wondering how you can control the folder structure which is generated from the vstemplate files. I originally thought that this is maybe somehow controlled by "CreateNewFolder" but changing that to false had no effect. No matter what i do it seems like i always get a folder structure like 
solution/wizardname/wizardname.projectA 
solution/wizardname/wizardname.projectB
instead of
solution/wizardname.projectA 
solution/wizardname.projectB
https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019 did not seem to point out any ways of doing this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e208-2a2a-9fc3-98ff-147540157f32
* Version Independent ID: 5f5c9adf-da1d-ec0b-8af3-ccd2e27eaadc
* Content: [Create multi-project templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2019)
* Content Source: [docs/ide/how-to-create-multi-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-multi-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@taori -- Andreas, you may find these links helpful in finding answers:
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by taori** [comment]
@WilliamAntonRohm Not really no. All 3 of them involve digging through hundreds of unrelated articles. 

Personally i was so bothered with the tedious process that i wrote https://github.com/taori/Amusoft.VisualStudio.TemplateGenerator so i never have to deal with managing multi project templates again. Hence my request to get some information on this in order to generate the templates in a fashion where i can generate the templates into a flat folder hierarchy instead of a nested one :)

**Comment by alelom** [comment]
> Personally i was so bothered with the tedious process that i wrote https://github.com/taori/Amusoft.VisualStudio.TemplateGenerator so i never have to deal with managing multi project templates again. 

@taori THANK YOU! I've lost 2 days of research to no avail -- digging through all that mess of answers and information on these multi project templates on those suggested sites.
I am going to try your utility now.

**Comment by alelom** [comment]
This is so ridiculous. I've spent hours trying to solve the multi-project template structure, namely the now infamous "[weird additional folder](https://www.google.com/search?rlz=1C1GCEU_en-gb&sxsrf=ACYBGNR3KjT84KxrF2GPuaZzhW3uA0FjXQ%3A1569418785775&ei=IW6LXaX8LsfZgQbg6rzoCw&q=multi+project+template+visual+studio+weird+extra+folder&oq=multi+project+template+visual+studio+weird+extra+folder&gs_l=psy-ab.3...8124.8858..8986...0.2..1.177.425.5j1......0....1..gws-wiz.......0i71j35i304i39j0i8i13i30.g6JoSAgjehM&ved=0ahUKEwjlkOvJjOzkAhXHbMAKHWA1D70Q4dUDCAs&uact=5)". No way of dealing with it if not through [some kind of Wizard-ry magic](https://stackoverflow.com/a/31519898/3873799).

There is literally not a single clear, reliable source in MDSN that tackles this common problem. It can't be that hard to solve it.

**Comment by taori** [comment]
That "weird additional" made me result into writing this: https://github.com/taori/Amusoft.VisualStudio.Extensions/tree/master/src/Tooling so i can move folders to a new destination while altering the solution references. 

Took me dozens of hours to develop it and moving it manually is probably faster... but hey... it was more fun than being annoyed by the folder structure? :laughing: 

this really needs fixing though. Noone should go through this just to have a clean folder structure

**Comment by alelom** [comment]
> That "weird additional" made me result into writing this: https://github.com/taori/Amusoft.VisualStudio.Extensions/tree/master/src/Tooling so i can move folders to a new destination while altering the solution references.

That sounds great @taori -- any chance you could provide a bit of documentation on how to use the extension?

**Comment by omccully** [comment]
I'm bothered by this issue too. Project templates have so much potential, but they really need some work. I'll check out your project, taori.

**Comment by onerob2000** [comment]
> That "weird additional" made me result into writing this: https://github.com/taori/Amusoft.VisualStudio.Extensions/tree/master/src/Tooling so i can move folders to a new destination while altering the solution references.
> 
> Took me dozens of hours to develop it and moving it manually is probably faster... but hey... it was more fun than being annoyed by the folder structure? 😆
> 
> this really needs fixing though. Noone should go through this just to have a clean folder structure

Thank you for sharing this.

I, too, have spent countless hours attempting to get around this "weird" folder structure. I believe this is just another example of Microsoft providing a really great tool that stops short of providing a complete solution to their end users. It's a shame we need to resort to writing custom tools to provide the consistency (inherent folder structure when creating new Solutions in VS) that should have been a forethought in the minds of the team who developed this tool.

**Comment by angelicochris** [comment]
> 
> 
> > That "weird additional" made me result into writing this: https://github.com/taori/Amusoft.VisualStudio.Extensions/tree/master/src/Tooling so i can move folders to a new destination while altering the solution references.
> > Took me dozens of hours to develop it and moving it manually is probably faster... but hey... it was more fun than being annoyed by the folder structure? 😆
> > this really needs fixing though. Noone should go through this just to have a clean folder structure
> 
> Thank you for sharing this.
> 
> I, too, have spent countless hours attempting to get around this "weird" folder structure. I believe this is just another example of Microsoft providing a really great tool that stops short of providing a complete solution to their end users. It's a shame we need to resort to writing custom tools to provide the consistency (inherent folder structure when creating new Solutions in VS) that should have been a forethought in the minds of the team who developed this tool.

Running into this issue as well. It real sad that Microsoft can't fix what should be a simple issue for them. Going to try that tool and see if it is going to end up being the last step in our new solution making process because MS can't do their job.

**Comment by taori** [comment]
I would not expect them to invest a lot of time anymore on this. There is a new templating system now after all.
