### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by GabeSJones** [MicrosoftDocs/visualstudio-docs#393]
"Size specifier for pointers as arrays in interop debugging with C++/CLIt"
Should be "C++/CLI"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5c135d-ace1-1f09-041a-13411c054ff3
* Version Independent ID: 083fc572-d877-2216-19a9-326636c1d8e6
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/format-specifiers-in-cpp.md)

**Comment by mikeblome** [comment]
Thanks @GabeSJones! Typo is fixed now.
