### ISSUE TITLE
e.*?e does match eed

### ISSUE THREAD

**Issue by senad-meskin** [MicrosoftDocs/visualstudio-docs#3930]
In a section explaining "*?" said that "e.*?e" does not match "eed" and it's wrong. I tested it in Visual Studio and inside other editors supporting regex.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@senad-meskin -- Senad, I believe you are correct, as ? means "zero or more occurrences".  The article does say that pattern won't match "eede".
