### ISSUE TITLE
Be careful when using variables in path with **\*.*

### ISSUE THREAD

**Issue by axodox** [MicrosoftDocs/visualstudio-docs#3936]
I have managed to delete a significant amount of files from my C drive, by specifying `$(OutputDir)\**\*.*` for a delete. It seems that  msbuild could not find `$(OutputDir)`, so it just become `\**\*.*`, which tried to delete everything on the drive of the project, including half of program files, app data etc. resulting in a complete reinstall. Fortunately I had backup, but still wasted some time. 

Maybe msbuild should fail in this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22b02536-b99d-e0f5-165c-40c041b2178d
* Version Independent ID: 721b076f-0bab-642a-3754-fa7a2ad8f474
* Content: [Delete Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/delete-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/delete-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/delete-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
I added a warning to this topic.  MSBuild is an open-source project, so someone could submit an issue or PR in the MSBuild GitHub repo https://github.com/Microsoft/msbuild to change the behavior to warn or fail in that situation.
