### ISSUE TITLE
Where/when is the Remove attribute valid?

### ISSUE THREAD

**Issue by addestroyer24** [MicrosoftDocs/visualstudio-docs#3940]
It's not clear whether the Remove attribute was only supported until MSBuild 15, or whether the attribute became usable outside of targets starting in MSBuild 15.
[Attributes for items in an ItemGroup of a Target > Remove attribute](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019#BKMK_RemoveAttribute)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4c1957-1da1-073e-e5d2-b88dbb6e4f0c
* Version Independent ID: da079116-5827-d486-271b-9e2cb10bf063
* Content: [MSBuild Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-items.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@addestroyer24 Thank you for the question.

From the text:

```
This attribute was introduced in the .NET Framework 3.5, but was only supported inside targets until MSBuild 15.0.
```

...I'm not sure I understand your question.  The `Remove` attribute was supported from .NET 3.5 until MSBuild 15 (inside targets only).  After MSBuild 15 it was supported both inside and outside targets.

**Comment by addestroyer24** [comment]
Thank you, that is the clarification I was looking for. I originally read
the wording (until MsBuild 15.0) as saying that the remove attribute was no
longer supported at all, which is what I was hoping to have clarified in
the docs.

**Comment by msebolt** [comment]
You're welcome, I see what you mean now.  The documentation has been updated.
