### ISSUE TITLE
[Overview of C ++ in Visual Studio] is the first description based on VS 2019

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#3941]
@wraith13 commented on [Sun Sep 08 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1845)

https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/ide/getting-started-with-cpp-in-visual-studio.md
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/getting-started-with-cpp-in-visual-studio.md

The description on this page, including the original English version, is initially written for VS 2019, but to create a console app project/ But after `To create a console app project`  it becomes VS 2017

---

@srvbpigh commented on [Mon Sep 09 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1845#issuecomment-529175258)

こんにちは、@wraith13
フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team 

---

@CeciAc commented on [Mon Sep 09 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1845#issuecomment-529458257)

こんにちは、@wraith13
フィードバックをお送りいただきありがとうございました。
この問題はこれに関連しているようです：https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1830
ライブページでも複製されるかどうかを確認してください：https://docs.microsoft.com/ja-jp/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2019

敬具
Microsoft DOCS International Team

---

@wraith13 commented on [Mon Sep 09 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1845#issuecomment-529460280)

日本語版
https://docs.microsoft.com/ja-jp/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2019
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/645907/64532252-184a2b80-d34c-11e9-98ea-5b543a51eb3f.png">
英語版
https://docs.microsoft.com/en-us/visualstudio/ide/getting-started-with-cpp-in-visual-studio?view=vs-2019
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/645907/64532419-68c18900-d34c-11e9-95f3-5538467647e3.png">

このようにライブページでも再現しています。 #1830 とは違い、 moniker ディレクティブの問題などではなく、単純に VS 2019 対応の作業が途中までしか行われていないように見えます。

**Comment by CeciAc** [comment]
Hi team, 
I moved this here because the user reports the explanation on the documentation starts as VS 2019 and after **To create a console app** project follows as VS 2017
The issue would be also be present in the en-us version

best

**Comment by corob-msft** [comment]
The article has been redirected into the VS 2019 content in the C++ repo. It may take some time to be propagated into the localized versions, but the English version should be updated sometime later today.
