### ISSUE TITLE
Strongly disagree with 'text' as a rational for generating this warning.

### ISSUE THREAD

**Issue by GammaFour** [MicrosoftDocs/visualstudio-docs#3943]
I deal with third party libraries.  The use of the parameter name 'text' is widespread in methods that do not generate user visible text.  I could understand this warning on things like 'Message', or 'Label' or 'Caption', but 'text' is simply too generic to intuit the intention of the method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a0a1a48-3a9f-05c8-53fd-4d126bb275ad
* Version Independent ID: 65f77e05-47ac-9e01-ce54-9669c2dd9b2b
* Content: [CA1303: Do not pass literals as localized parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1303-do-not-pass-literals-as-localized-parameters?view=vs-2019)
* Content Source: [docs/code-quality/ca1303-do-not-pass-literals-as-localized-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1303-do-not-pass-literals-as-localized-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@GammaFour Thanks for the feedback. The best place to leave non-documentation feedback about code analyzers is on the [Roslyn-analyzers repo](https://github.com/dotnet/roslyn-analyzers/issues). Can you please open an issue there? Here's an example: https://github.com/dotnet/roslyn-analyzers/issues/2602.
