### ISSUE TITLE
This documentation is out of date

### ISSUE THREAD

**Issue by GammaFour** [MicrosoftDocs/visualstudio-docs#3944]
I have a .NET Core Web Service.  It includes Entity Framework generated code.  The Visual Studio compiler doesn't give me the option for Code Analysis for these kinds of projects, but still tries to interpret auto-generated code like it was written by a human.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b48962e-6961-ecd8-9b3f-4e60b97600c5
* Version Independent ID: 4f2b0b4b-d0a0-e4e3-445c-026c66de4c59
* Content: [Suppress Code Analysis violations for Generated Code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code?view=vs-2019)
* Content Source: [docs/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@GammaFour  Thank you for the feedback.  

What is specifically out of date?  Your code might fall under [.NET compiler analysis](https://docs.microsoft.com/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019) which cannot be suppressed.

If this is the case, please move the issue to the [roslyn-analyzer repo](https://github.com/dotnet/roslyn-analyzers/issues) where the product team can respond.
