### ISSUE TITLE
"Obtaining arguments from TextTemplate.exe" could use an example

### ISSUE THREAD

**Issue by ncook-hxgn** [MicrosoftDocs/visualstudio-docs#3947]
I've got no idea how this is supposed to work, the CLI help output doesn't provide an example either.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4771496c-436c-0b91-87ec-30e480d02a34
* Version Independent ID: d9431d72-6bc8-f0be-6ae7-c57f2a205e6f
* Content: [T4 Parameter Directive - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/t4-parameter-directive?view=vs-2019#feedback)
* Content Source: [docs/modeling/t4-parameter-directive.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/t4-parameter-directive.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@ncook-vero -- thanks for your feedback. Here are a few options you might consider: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

@gewarren -- please look into adding such an example.

**Comment by mgoertz-msft** [comment]
@Marraz Could you please help @JoshuaPartlow come up with an example for this?

**Comment by JoshuaPartlow** [comment]
Closing given the time open. If this is still an issue that you feel should be addressed, please feel free to re-open.
