### ISSUE TITLE
VS 2019?

### ISSUE THREAD

**Issue by ColbyRingeisen** [MicrosoftDocs/visualstudio-docs#3948]
This sample needs to be updated for VS 2019!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 904f29a0-43c8-dfff-01d2-581111957f32
* Version Independent ID: db5b2081-71e6-785a-d665-2a12e4bed46d
* Content: [Create an Android Native Activity App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/create-an-android-native-activity-app?view=vs-2019)
* Content Source: [docs/cross-platform/create-an-android-native-activity-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/create-an-android-native-activity-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by ColbyRingeisen** [comment]
Please delete my previous comment. That was supposed to be for the "Build an OpenGL ES application on Android and iOS" page and not the "Create an Android Native Activity App - Visual Studio" page.

**Comment by corob-msft** [comment]
Closing, per @ColbyRingeisen comment.
