### ISSUE TITLE
Would be nice if Substring could go back to front

### ISSUE THREAD

**Issue by julianparismorgan** [MicrosoftDocs/visualstudio-docs#3952]
I have a scenario where I want to get from the last character in a string until the fifth from last character in a string. If you try to do a Substring from back to front, like this:

&lt;Foo&gt; "$(Thing.Substring(-1, -4))" &lt;/Foo&gt;

you get the error: "MSB4184 The expression xxx cannot be evaluated. StartIndex cannot be less than zero. Parameter name: startIndex"

It would be nice if you a negative index referred to starting at the end of a string, like in Python,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019#feedback)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@julianparismorgan  Thank you for the feedback.

This appears to be more product-related than documentation.

Please add this issue to [Visual Studio suggestions](https://developercommunity.visualstudio.com/idea/555964/visual-studio-2019-suggestions.html) for a direct response from the product team.
