### ISSUE TITLE
The Tutorial says it's for VB and C# but only C# code is shown

### ISSUE THREAD

**Issue by bojanderson** [MicrosoftDocs/visualstudio-docs#3955]
The Tutorial covers creating either VB or C# files for hte project but then when code is given it's only C# code, making it much more difficult for somebody trying to create this project in VB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c15eb88-74b8-e0a1-b5ff-5f8a8c29231b
* Version Independent ID: 7db86e0c-baa4-9059-d971-8a1ab330d491
* Content: [Walkthrough: Create a custom tab by using the Ribbon Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-a-custom-tab-by-using-the-ribbon-designer?view=vs-2019)
* Content Source: [docs/vsto/walkthrough-creating-a-custom-tab-by-using-the-ribbon-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-creating-a-custom-tab-by-using-the-ribbon-designer.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by msebolt** [comment]
@bojanderson  Thank you for the feedback.

Which part of the document are you referring to?

If you select **VB** in the upper-right corner...

![Capture](https://user-images.githubusercontent.com/6675884/65164720-4d144d80-d9f2-11e9-9580-dac3c2cfeba3.PNG)

...the code snippets should show VB...

![Capture2](https://user-images.githubusercontent.com/6675884/65164727-4ede1100-d9f2-11e9-8642-2716d175136e.PNG)

**Comment by bojanderson** [comment]
Sorry I'm an idiot and didn't see that.

Bo Anderson

**Comment by gewarren** [comment]
> Sorry I'm an idiot and didn't see that.
> 
> Bo Anderson
> …

No, you're not an idiot. We've received quite a bit of feedback that the code language selector is hard to find. We're hoping to improve the experience.

**Comment by bojanderson** [comment]
Thank you for the quick response. Appreciate it!

Bo Anderson

**Comment by msebolt** [comment]
Sorry for the delay.

The code selector one of the newer features of Microsoft Docs, thank you for your interest.
