### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by gchirinos** [MicrosoftDocs/visualstudio-docs#396]
Great

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4bbd5e04-5e50-dd40-c359-e77fed8b1a9f
* Version Independent ID: 6e57e791-2bc8-5dac-48e6-cef4ad403dbe
* [Content](https://docs.microsoft.com/en-us/visualstudio/subscriptions/#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/subscriptions/index.md)

**Comment by TerryGLee** [comment]
Thanks @gchirinos for your comment. :)
