### ISSUE TITLE
Extending Visual Studio for Mac Walkthrough Does Not Work

### ISSUE THREAD

**Issue by gmoore** [MicrosoftDocs/visualstudio-docs#3963]
Hi! I'm working through the VS Mac extension walkthrough here: https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac-walkthrough?view=vsmac-2019

I follow the instructions and ran the plugin. I found this this line always evaluates to false

`info.Enabled = IdeApp.Workbench.ActiveDocument?.Editor != null;`

I changed the method to always return true and found this this expression is always null

`var editor = IdeApp.Workbench.ActiveDocument.Editor;`

Through the immedate pad, I can see that `IdeApp.Workbench.ActiveDocument` is initialized and has properties, but Editor is always null.  I've tried with new files, existing files, editing the file first, etc... Editor is always null. My immediate pad looks like so:

```
> IdeApp.Workbench.ActiveDocument
{MonoDevelop.Ide.Gui.Document}
	CommentTags: {string[1]}
	DocumentContext: {MonoDevelop.Ide.Gui.RoslynDocumentContext}
	Editor: (null)
	FileName: {/Users/garymoore/dev/monodevelop-simple-pad-addin/MonoDevelopSimplePadAddin/SimplePad.cs}
	FilePath: {/Users/garymoore/dev/monodevelop-simple-pad-addin/MonoDevelopSimplePadAddin/SimplePad.cs}
	Icon: {Xwt.Drawing.Image}
	IsDirty: false
	IsFile: true
	IsNewDocument: false
	IsViewOnly: false
	Name: "SimplePad.cs"
	Owner: {MonoDevelop.CSharp.Project.CSharpProject}
	TextBuffer: {CSharp:"
using System;
u"}
	Non-public members: 
> IdeApp.Workbench.ActiveDocument.Saved
{System.EventHandler}
	base: {System.MulticastDelegate}
> IdeApp.Workbench.ActiveDocument.Saved()
Method `Saved' not found in type `MonoDevelop.Ide.Gui.Document'.
> IdeApp.Workbench.ActiveDocument.Saved
{System.EventHandler}
	base: {System.MulticastDelegate}
> IdeApp.Workbench.ActiveDocument.Saved == true
false
> IdeApp.Workbench.ActiveDocument.Owner
{MonoDevelop.CSharp.Project.CSharpProject}
	base: {MonoDevelop.Projects.DotNetProject}
	CodePage: 0
	MainClass: ""
	Win32Icon: ""
	Win32Resource: ""
	Static members: 
	Non-public members: 
> IdeApp.Workbench.ActiveDocument.IsDirty
false
> IdeApp.Workbench.ActiveDocument.Name
"SimplePad.cs"
> IdeApp.Workbench.ActiveDocument.Editor
(null)
```

How can I resolve the Editor field of IdeApp.Workbench.ActiveDocument?

I'm using Visual Studio Community for Mac 8.2.5 build 5

**Comment by WilliamAntonRohm** [comment]
@gmoore -- Gary, you may find an answer here:
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

@asb3993 -- Amy, please look into updating the documentation.

**Comment by gmoore** [comment]
Thanks William!
