### ISSUE TITLE
Add Instruction for Program.Main() function

### ISSUE THREAD

**Issue by P13RC3** [MicrosoftDocs/visualstudio-docs#3964]
The typical way the past was command line args for startup Main(string[] args), but with clickonce you need to use AppDomain.CurrentDomain.SetupInformation.ActivationArguments.ActivationData.  Info about ActivationData should be mentions in this documentation about ClickOnce File Associations.  They go hand in hand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c2575a9-5973-2a77-ecf6-2142eefcd554
* Version Independent ID: 63223f10-3ed0-238c-545f-5dd810b304a7
* Content: [How to: Create File Associations For a ClickOnce Application - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-file-associations-for-a-clickonce-application?view=vs-2019#feedback)
* Content Source: [docs/deployment/how-to-create-file-associations-for-a-clickonce-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-create-file-associations-for-a-clickonce-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@P13RC3 Can you provide a few details about your scenario? Are the current instructions incomplete for creating the file association? Thanks!
