### ISSUE TITLE
One Vague Part

### ISSUE THREAD

**Issue by dm-learn** [MicrosoftDocs/visualstudio-docs#397]
The value description for setting the "General > Target Name" property is vague, "Set this field to exactly match the name of the module as Python sees it". However, how Python will see the module is not clear until later, in step 4 of "Converting the c++ project to an extension for Python".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daf42fdc-757b-147a-8216-5968829e82dc
* Version Independent ID: a2b820f3-3a77-4d60-b968-a1213b4cb32c
* [Content](https://docs.microsoft.com/en-us/visualstudio/python/cpp-and-python#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/python/cpp-and-python.md)

**Comment by kraigb** [comment]
I've clarified in the table that it applies to the module name used in from...import statements, and elaborated further in step 4 to provide examples. If this isn't sufficient, you can reopen this issue. Thanks.

**Comment by leehu** [comment]
Hi. I'm getting stuck as there's no defition for PyModuleDef in Python.h so I can't get past this step. Any ideas? thx

**Comment by kraigb** [comment]
First, where is your python.h coming from? You'll want to make sure there's not another file with the same name that's being picked up instead of the proper one.

Second, Python.h pulls in a variety of other header files; the one with PyModuleDef is moduleobject.h, which should be in the same include folder as python.h. In other words, do a search in the folder where python.h is for PyModuleDef and see if it shows up where it should.

**Comment by leehu** [comment]
\Python27\include is where I'm including it from. I've just reinstalled the version that comes with VS17 and now even PyObject is not defined. Not sure what's going on, but something is broken somewhere,

**Comment by leehu** [comment]
ah,  maybe that's it. No, I haven't tried 3.6 as I need to run a module against Python 2.7 so figured that wouldn't run a 3.x extension. I've checked the 2.7 header files and there is no PyModuleDef - must have been added for 3.x

**Comment by kraigb** [comment]
In that case, take a look at https://docs.python.org/2.7/howto/cporting.html, which shows the changes for module definitions between 2.7 and 3.x. I'll add a note with that link to the article here.

**Comment by kraigb** [comment]
I don't know of anything; looking at https://docs.python.org/2.7/extending/building.html, running setup.py in some manner seems to be a requirement. But you could ask on StackOverflow as someone in the wider community might have experience with this detail.
