### ISSUE TITLE
unclear documentation

### ISSUE THREAD

**Issue by hhoppe** [MicrosoftDocs/visualstudio-docs#3970]
Please define what slicing is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be6a0e19-d61f-fefb-4a83-afa87219e168
* Version Independent ID: 206fffd7-3651-5783-49e0-c586a9b8b992
* Content: [C26437 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26437?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26437)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/code-quality/C26437.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26437.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@hhoppe Thanks for the feedback. I have updated the topic with a link to the Wikipedia page on Object Slicing.
