### ISSUE TITLE
CA1707 warning In Test project

### ISSUE THREAD

**Issue by Leanwit** [MicrosoftDocs/visualstudio-docs#3971]
Best practices for test naming convention is defined in https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices as:

> 
> - The name of the method being tested.
> - The scenario under which it's being tested.
> - The expected behavior when the scenario is invoked.

And those three parts are represented in a method name separated by an underscore.
But the description's CA1707 warning is:

> By convention, identifier names do not contain the underscore (_) character. The rule checks namespaces, types, members, and parameters.
> 
> When to suppress warnings
> Do not suppress a warning from this rule.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06cee199-3ccc-7575-2c1d-296e2714a16e
* Version Independent ID: 2be241bf-b98a-5088-1e1b-0e39b1384b9a
* Content: [CA1707: Identifiers should not contain underscores - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1707-identifiers-should-not-contain-underscores?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1707-identifiers-should-not-contain-underscores.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1707-identifiers-should-not-contain-underscores.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
It seems to me like the example in the unit testing best practices article should be updated. I logged an issue for that: https://github.com/dotnet/docs/issues/14747.

**Comment by gewarren** [comment]
The suggestion is:

CA1707 is meant only for production code, so should be explicitly turned off for test projects using https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#rule-severity.

I'll update the doc with this.
