### ISSUE TITLE
Useful

### ISSUE THREAD

**Issue by P-v-K** [MicrosoftDocs/visualstudio-docs#3972]
This is a useful page. I tried to figure out how to get an easily readable view of longer strings in debug mode and never even noticed the little icon that brings up the String Visualizer. 

The UI design seems rather odd how it offers so much likely-uninteresting information about an object, but then makes the most easily useful control something you need to notice and interpret (or know about somehow) a very small icon that doesn't clearly communicate anything.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3761f60-ec2f-2c51-cfa1-1e192c71bebe
* Version Independent ID: 714a4254-b006-5509-9fa1-355da2184942
* Content: [String Visualizer dialog box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/string-visualizer-dialog-box?view=vs-2019#feedback)
* Content Source: [docs/debugger/string-visualizer-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/string-visualizer-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@P-v-K Thanks for the positive comments about the article! If you are looking for functionality that isn’t currently provided by the product, please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2017) page.
