### ISSUE TITLE
No information about pricing

### ISSUE THREAD

**Issue by yusuf-gunaydin** [MicrosoftDocs/visualstudio-docs#3973]
In the document it says: "To learn more about benefits, options, and pricing please visit https://visualstudio.microsoft.com/subscriptions/visual-studio-github." However, there is no pricing information there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e0dbc2-35de-0efe-ae1b-b9d2507f2b4d
* Version Independent ID: f1e1caeb-78d3-262f-6311-6606720893a3
* Content: [Visual Studio + GitHub Offer](https://docs.microsoft.com/en-us/visualstudio/subscriptions/access-github)
* Content Source: [subscriptions/access-github.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/access-github.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- please assign yourself or another domain expert this issue.

**Comment by evanwindom** [comment]
I am not a member of the docs org and cannot assign.  I have just submitted a PR to correct this article.

**Comment by TerryGLee** [comment]
@yusuf-gunaydin The text on the page that mentions pricing has been corrected and the updated page is published. We'll close this issue now, with our thanks to you for helping us improve our documentation.
