### ISSUE TITLE
Can't report a problem in VS because can't log in to Dev. Community!

### ISSUE THREAD

**Issue by MatejQ** [MicrosoftDocs/visualstudio-docs#3974]
I wanted to report some issues in VS but I can't log in to Developer Community. I found out that it's not possible to log in there outside of VS which is just ridiculous.
Everytime I open the Help - Report a problem menu, the Feedback popup opens, says Authenticating... for a while and then fails with "Error signing in: '{}'". It's clearly a bug somewhere in the Developer Community.

**Comment by MatejQ** [comment]
![Capture](https://user-images.githubusercontent.com/14346231/65419328-b33c0e80-ddfe-11e9-9820-2ed1143b721e.PNG)
A screenshot that may help.

**Comment by seaniyer** [comment]
@MatejQ 

Thanks for letting us know.  Sorry about the poor experience.  We are tracking an active issue for it here 
https://developercommunity.visualstudio.com/content/problem/583234/error-signing-to-vs-feedback-tool.html

Please vote/follow the item so you'll be notified of progress updates.

Thanks
Sean
Visual Studio Feedback Team

**Comment by TerryGLee** [comment]
@seaniyer Thanks for your response. We'll close this now, as it's being tracked to resolution in the Developer Community. And @MatejQ, thanks for letting us know!
