### ISSUE TITLE
missing api section

### ISSUE THREAD

**Issue by davidbIQ** [MicrosoftDocs/visualstudio-docs#3977]
In the prior tutorial it gave a build of the gui & api, and the docker compose put them together.  In this one it gave only the gui & kuberneties wrapper for it.  It would be much more helpful to show how to do the same thing as was done with the docker-compose file in the prior example, specifically how to use Kubernetes to include both the API & web interface in the dev/deployment pipeline with Kubernetes.  
Also it would be nice to show how to debug with Kuberneties on non azure devops platform as I haven't seen that anywhere but that's for a separate page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-kubernetes-tools?view=vs-2019#feedback)
* Content Source: [docs/containers/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-kubernetes-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Have you looked at the Dev Spaces quickstart?
https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-netcore-visualstudio
This covers Kubernetes development in VS with two projects, API and "webfrontend."
