### ISSUE TITLE
Update documentation for feature enhancements in VS2019 16.4 and Microsoft.CodeAnalysis.Metics (2.9.5) - both are now released

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#3979]
Given the large number of feedback on https://developercommunity.visualstudio.com/content/problem/400717/wrong-lines-of-code-at-calculate-code-metrics.html, we have changed VS2019 16.4 and Microsoft.CodeAnalysis.Metics (2.9.5) to now report 2 metrics for lines of code:

1. Lines of source code: The exact number of source code lines as in your source file, including blank lines.
2. Lines of executable code: Approximate number of executable code lines or operations, which should be a close match to the lines of code values in prior MSIL instructions based metric, i.e. legacy mode lines of code. This is a count of number of operations in executable code.

For example, a source line `a = b + c + d;` will be counted as a single source line of code, but have 2 executable lines of code, one for each add operation.

We should update this documentation accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c654586-8571-cfe1-1ee1-3adaf79e2dcf
* Version Independent ID: 334b3914-dbcd-3ece-26b3-fab7c766a377
* Content: [Generate code metrics from the IDE or command line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2019)
* Content Source: [docs/code-quality/how-to-generate-code-metrics-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-generate-code-metrics-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
![image](https://user-images.githubusercontent.com/10605811/65450650-7ec25580-ddf2-11e9-8d44-18fc8047f508.png)

**Comment by Mikejo5000** [comment]
In addition to the changes for MicrosoftDocs/visualstudio-docs#4531, looks like the topic referenced here needs updates to the sample output for VS 2019, and edits to the section on Previous versions. Updating docs.
