### ISSUE TITLE
Layout Update operation doesn't work on existing 16.2 layout

### ISSUE THREAD

**Issue by BhaaLseN** [MicrosoftDocs/visualstudio-docs#3980]
Similarly to #1385, I'm still preparing offline layout packages for use within my organization (to save bandwidth), and it worked ok until now.
Going from an existing 16.2 layout, attempting to run `vs_Enterprise.exe --layout "path\to\layout"` errors out:

```
Visual Studio Setup Command Line Utility, version 2.3.2276.2797
c Microsoft Corporation. All rights reserved.

Download of 'https://aka.ms/vs/16/release/channel' succeeded using engine 'WebClient'
Download of 'https://download.visualstudio.microsoft.com/download/pr/1d102ee6-9263-4353-8676-6430f0cc5998/53e26f3ff75e1f860c7528b99ce05b7d391578094bfd88faec5630b445284c34/VisualStudio.vsman' succeeded using engine 'WebClient'
Catalog load operation correlation: {"id":"b3f095d7-a11b-4947-b728-61a55f4af23a"}
UpdateLayout operation correlation: {"id":"1d42adda-a00e-44fe-9794-c1eb53bb88e0"}
Planning 'UpdateLayout' operation
Error: The package 'Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.2' is not recognized.
Error: Failed to plan for UpdateLayout.
Error: Setup completed with errors.
Error: The package 'Microsoft.NetCore.ComponentGroup.DevelopmentTools.2.2' is not recognized.
```

16.3 only just released (with all the announcements at DotNetConf, including .NET Core 3), so I'm wondering if this is just temporary or some other issue.
I've also redownloaded the setup utility to verify it is the most recent (and yet running it still insists on downloading _yet another_ one), no change.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc51a257-b7a9-4660-7e12-88cdfcd9cd53
* Version Independent ID: dad2fd97-7244-6802-e853-5d5974838996
* Content: [Update a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/update-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@BhaaLseN -- Bhaal, thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question: 
-	[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio)
-	[https://www.stackoverflow.com](https://www.stackoverflow.com)
-	[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by fredenocs** [comment]
I understand this is closed, but I had the similar issue.  I updated the 2.2 to 2.1, issue was resolved.

My question to the OP is; do you use a custom.json?

**Comment by BhaaLseN** [comment]
Nope, I've been using `vs_enterprise.exe --layout "path/to/layout" --add payload.names` to create it from scratch, then `vs_enterprise.exe --layout "path/to/layout"` for all subsequent runs (at least until the point where packages are removed, and the layout update just throws the errors mentioned above).
I wanted to use an expected settings.json once but this isn't supported by the layout operation.

**Comment by fredenocs** [comment]
I felt comfortable changing it from 2.2 to 2.1 when I didn't locate a "2.2" pkg here:
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?vs-2019&view=vs-2019

This was in process and just now completed successfully.  Funny how I did a verify before updating and came back "clean".

**Comment by BhaaLseN** [comment]
Same, except that I already had 2.1 in that list; and having it twice felt weird.
Verify also worked just fine.

**Comment by fredenocs** [comment]
One question if I may.  My version I has of vs_professional.exe was 16.2, never updated?  I downloaded it again and it is 16.3.  I wonder if I can replace it?

Question is, did your vs_enterprise.exe update?

**Comment by BhaaLseN** [comment]
I tried both the one that was in the layout folder, the one that was named `vs_setup.exe` instead _and_ a newly downloaded one. Neither worked, which is why I finally opened this issue (and afterwards another one on the developer community; which was shot down as well with the resolution "just make a new layout").
Since my coworkers were eager to update I just caved and made a new layout in the end 🤷‍♂
