### ISSUE TITLE
Xamain.Mac native library

### ISSUE THREAD

**Issue by Issuesneedfixin** [MicrosoftDocs/visualstudio-docs#3982]
every time I try to open visual studio, no matter how many different ways I try, I am met with 

"Could not launch Visual Studio
This application requires Xamarin.Mac native library side-by-side.

please download and install the latest version of Momo"  

however I have downloaded both Mono and VS multiple times the issue won't resolve

**Comment by msebolt** [comment]
@Issuesneedfixin Thank you for the question, we're sorry you're experiencing issues.

It looks like you need to use the [universal installer](https://visualstudio.microsoft.com/vs/mac/) mentioned in [this post](https://forums.xamarin.com/discussion/103004/installation-of-visual-studio-for-mac).  

If that doesn't work, please have [this ticket item](https://developercommunity.visualstudio.com/content/problem/326958/mac-visual-studio-cannot-be-launched-due-to-mono-f.html) reopened to correspond directly with the product team.  There you should have more traction with the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are questions.
