### ISSUE TITLE
Controlling the target framework and runtime identifier appended to the output path

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#3983]
If I am using the new SDK project format, it's not enough to just set the output path, because by default the target framework -- and possibly the runtime identifier -- will be appended to the output path:

    bin/Debug/net472/MyProject.dll

To prevent this, you have to use `AppendTargetFrameworkToOutputPath` and `AppendRuntimeIdentifierToOutputPath` set to `false`.

https://stackoverflow.com/questions/43602782/how-do-i-set-outputpath-in-a-visual-studio-2017-project-new-csproj-file-form

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4938a042-e5db-4f9c-2288-930b904e888c
* Version Independent ID: 6db1e386-22e4-4940-cc2c-bdeaa5883299
* Content: [How to: Change the build output directory - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2019)
* Content Source: [docs/ide/how-to-change-the-build-output-directory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-change-the-build-output-directory.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by msebolt** [comment]
@zspitz  Thank you for the feedback.

The documentation has been updated.
