### ISSUE TITLE
c:\vsoffline folder

### ISSUE THREAD

**Issue by desert-rover** [MicrosoftDocs/visualstudio-docs#3984]
After downloading the custom partial layout (C:\vsoffline), I copied that to a network location.  So would I then just need to copy that folder onto the C: drive of the computers that need VS 2019? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@desert-rover  Thank you for the question.

You can either copy the folder or run it directly from the network location as in the example:

```\\server\products\VS\vs_enterprise.exe```

There should be no issues running it remotely for multiple installations.

**Comment by desert-rover** [comment]
I'll give it a shot. Thanks!
