### ISSUE TITLE
simple brake over a loop causes the error

### ISSUE THREAD

**Issue by PeterPann23** [MicrosoftDocs/visualstudio-docs#3986]
var ix = 0;
                    for (var i=0; i &lt; sorted.Length; i++)
                    {
                        if (sorted[i].Id == best[0].Id)
                        {
                            ix = i;
                            break;
                        }
                    }

no need to crash and give the warning here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfd7078-683e-9fd6-247b-e75d4ed16a32
* Version Independent ID: ae3300c4-55a8-59b6-846b-50c48c88dcfe
* Content: [Error: Evaluating the function 'function' timed out and needed to be aborted in an unsafe way - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.unsafe_func_eval_abort)%3Bk(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2019#feedback)
* Content Source: [docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@PeterPann23 Thanks for your feedback. It looks like you'd like to see a change of behavior in the product. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
