### ISSUE TITLE
found the target extension

### ISSUE THREAD

**Issue by prelich** [MicrosoftDocs/visualstudio-docs#3987]
The target extension in this guide moved from general to advanced.  Its in configuration properties -&gt; advanced -&gt; target file extension.  Probably not a big deal, but it took me a while to get back on the trail of this tutorial.  Thanks for making this by the way, it's really helpful for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @prelich, thanks for trying the tutorial and opening an issue when you found a problem. Could you tell me which version of Visual Studio you're using?

**Comment by prelich** [comment]
Sure:  Microsofgt Visual Studio Professional 2019
Version 16.3.0

Target File Extension on superfastcode(2) project was found in
Configuration Properties-->Advanced-->Target File Extension

**Comment by zooba** [comment]
This has already been fixed and can be closed.
