### ISSUE TITLE
Can't store a table on SQL local server database

### ISSUE THREAD

**Issue by ruirrrr** [MicrosoftDocs/visualstudio-docs#3988]
I did what the article said and I even have a local SQL server database setup. However, when I right click on the Server Explorer Tables, then choose add a new table. A new table show up, however, it doesn't allow me to change the name on Properties and it won't save on the local server database. 

When I save, it asks me to choose a local address for a dbo.Table file on my computer. Please advise how can I save the new table on the server database, so that when I click table under Server Explorer, I will see my new table. 

I am using VS2019 community and have the right packages installed.

Thanks so much!!!

**Comment by gewarren** [comment]
@ruirrr Which article are you following when you run into the problem?
