### ISSUE TITLE
How do I use a local clone of the GTest Source Code

### ISSUE THREAD

**Issue by csm10495** [MicrosoftDocs/visualstudio-docs#3994]
Is there a way that I can have a pre-existing Clone of GTest and build it within my project then use it for tests (all in the same .sln)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee608ee-eb3f-e95d-1eea-d9e35a6e0bc0
* Version Independent ID: daf80b3e-5bf1-652c-d6a0-602c8bc2bb0c
* Content: [How to use Google Test for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-google-test-for-cpp?view=vs-2019)
* Content Source: [docs/test/how-to-use-google-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-google-test-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@csm10495 The easiest way is to use the Google Test project template, but assuming that isn't an option for you, yes you can use your own clone of GTest and add it as you would add any other library. The Test Explorer will still be able to discover/execute those tests.

Here is an example of how to build with CMake which can generate .vcxproj files which can either be built once and explicitly referenced or included as a project reference in the solution: https://github.com/google/googletest/tree/master/googletest
Then you can reference that googletest project.
From your test project:
•	Right click > Properties > C++ > General
•	In the part for “Additional include libraries” add the path to the google test folder and include folder.
For example, “..\googletest\include;..\googletest\”.
•	There might already be a folder called “%(AdditionalIncludeDirectories)”.
•	Right click > Properties > Linker > General
•	In the part for “”Additional Library directories” add the directory where the googletest.lib file was created, (the library, not the file).
•	Finaly, add a reference, (Right Click the project > References and add your googletest project).

**Comment by csm10495** [comment]
Cool. I just didn't know if the test explorer would pick up on tested
without using the template if I manually pulled in the Google Test code.
Thanks!

**Comment by mikeblome** [comment]
Good! Let us know if you run into any issues.
