### ISSUE TITLE
Missing build customization properties

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#3996]
Another way to customize the build of **C#** and **Visual Basic** projects is through the MSBuild properties:

* `CustomBeforeMicrosoftCommonProps`
* `CustomBeforeMicrosoftCommonTargets`
* `CustomAfterMicrosoftCommonProps`
* `CustomAfterMicrosoftCommonTargets`
* `CustomBeforeMicrosoftCSharpProps`
* `CustomBeforeMicrosoftVisualBasicProps`
* `CustomAfterMicrosoftCSharpProps`
* `CustomAfterMicrosoftVisualBasicProps`
* `CustomBeforeMicrosoftCSharpTargets`
* `CustomBeforeMicrosoftVisualBasicTargets`
* `CustomAfterMicrosoftCSharpTargets`
* `CustomAfterMicrosoftVisualBasicTargets`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
For a discussion of these properties, including equivalent techniques for C++ projects, see
https://stackoverflow.com/questions/3924404/msbuild-custom-after-microsoft-common-targets-for-native-c-projects-in-vs2010

**Comment by ghogen** [comment]
Examples of using this functionality:
dotnet.geir-sorensen.net/2010/04/msbuild-custom-targets.html

**Comment by ghogen** [comment]
Adding a new section: Customize all builds, and Customize C++ builds.
The new section covers how to use Custom.Before/After.Microsoft.Common.Targets files and those variables to customize all builds on an installation of MSBuild or VS.  For C++, equivalent or similar techniques are described as discussed in the StackOverflow answer by Sayed Hashimi.
