### ISSUE TITLE
This doesn't seem to work if the dll project is a CMake project generated by "open folder"

### ISSUE THREAD

**Issue by Mathias-Fuchs** [MicrosoftDocs/visualstudio-docs#3997]
I want to debug a dll generated by a cmake project that is opened by the "open folder" command in visual studio.
I have a debugging exe that calls that dll. The steps above just don't work in that case, I can't add an exisiting project because for "open folder" projects the menu entry under File just isn't there.
Please udate these docs for cmake projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 930e45d1-d15e-272e-ee8d-37e2a2fead2b
* Version Independent ID: fa0a6241-3503-77d4-4fcc-2ba3a2376609
* Content: [Debug an app that isn't part of a Visual Studio solution](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-an-executable-not-part-of-a-visual-studio-solution?view=vs-2019#feedback)
* Content Source: [docs/debugger/how-to-debug-an-executable-not-part-of-a-visual-studio-solution.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-an-executable-not-part-of-a-visual-studio-solution.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@Mathias-Fuchs Thank you for the feedback, we're sorry you're having issues.

Which version of Visual Studio are you using?

This might be related to the [CMake debug issue](https://developercommunity.visualstudio.com/content/problem/82176/no-way-to-launchdebug-a-dll-from-cmake-open-folder.html) resolved from 2017.

Also, have you tried using **File** > **Open** > **CMake...** instead of **Open Folder**?

**Comment by Mikejo5000** [comment]
@Mathias-Fuchs You might also check the procedures here to see if they work for your scenario. They are specific to open folder projects and C++.

https://docs.microsoft.com/en-us/cpp/build/open-folder-projects-cpp?view=vs-2017#configure-debugging-parameters-with-launchvsjson

Please let us know if you resolve the issue, and we can add appropriate links.

**Comment by Mikejo5000** [comment]
Adding links to debug info for open folder projects.
