### ISSUE TITLE
Pluralsight subscription is not available as a part of vs dev essentials 

### ISSUE THREAD

**Issue by prisar** [MicrosoftDocs/visualstudio-docs#3999]
Pluralsight subscriptions are not part of dev essentials. So please remove this documentation or state that it is not offered anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e41abd-81dd-4dd2-d2d2-6bc513ad9e48
* Version Independent ID: 911d149e-8d78-b552-12a2-b061e2c1f41c
* Content: [Pluralsight benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-pluralsight)
* Content Source: [subscriptions/vs-pluralsight.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-pluralsight.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@prisar - Thanks for reaching out.  Our documentation no longer covers the Visual Studio Dev Essentials program.  Our content is focused solely on Visual Studio subscriptions.  We use the "Eligibility" section of the benefits-related articles to indicate which subscriptions include each benefit.  In the case of the Pluralsight benefit, there's no mention of Dev Essentials in the table so there shouldn't be an expectation that it is included.  The Dev Essentials team has asked that we not make any statements about which benefits may or may not be included in their program.  I apologize for any confusion.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for your response; we'll close this issue now.
