### ISSUE TITLE
completely out of date

### ISSUE THREAD

**Issue by GeekActual** [MicrosoftDocs/visualstudio-docs#400]
This documentation is over a year old, and is completely out of date. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b25d4cd-0c3f-e9a6-6256-ea54d0972d4b
* Version Independent ID: babd49b7-8e18-13dc-99f2-6783495cb0dc
* [Content](https://docs.microsoft.com/en-us/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md)

**Comment by GeekActual** [comment]
The latest release of Xamarin forms in VS2017 does not create a .Droid (it creates .Android) project, neither does it create a Windows 8.1 or Windows Phone 8.1 project.

**Comment by TerryGLee** [comment]
Thanks for your input, @GeekActual. We'll investigate this and get back to you. (Although given the holidays, please expect a delay in our response.)

**Comment by kvenkazure** [comment]
"Microsoft.CSharp.RuntimeBinder.Binder.Convert" not found by the compiler with this line .

    dynamic results = await DataService.getDataFromService(queryString).ConfigureAwait(false);

            if (results["weather"] != null)

How to resolve the issue.

**Comment by jh-orange** [comment]
It's now April.  Tkink a response available before we start running into Mother's Day, Memorial Day, Father's Day, Fourth, Labor Day, ...?
