### ISSUE TITLE
VerifyFileHash task has no Items parameter

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#4005]
The documentation of the VerifyFileHash task of MSBuild claims that it has an `Items` output parameter. However, the implementation does not support such a parameter.

(The GetFileHash task has an `Items` output parameter, as documented.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffa6013d-443a-570a-ca70-f3cad50a3b34
* Version Independent ID: d422fed1-420d-bf97-33c4-1842d5861696
* Content: [VerifyFileHash  Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/verifyfilehash-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/verifyfilehash-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/verifyfilehash-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by KalleOlaviNiemitalo** [comment]
The XSD changes that were made in microsoft/msbuild#4103 do not have a similar error.

**Comment by Mikejo5000** [comment]
@rainersigwald I don't see the Items parameter for VerifyFileHash here:
https://github.com/santoshyadav198613/msbuild/commit/4ce2cc85e41d8f57dd790faa18bb71499144dff7
Should it be removed from the VerifyFileHash doc?

**Comment by rainersigwald** [comment]
Cross-checked with https://github.com/microsoft/msbuild/blob/vs16.3/src/Tasks/FileIO/VerifyFileHash.cs and yes: it doesn't exist and should be removed.

**Comment by KalleOlaviNiemitalo** [comment]
An output parameter of type `ITaskItem[]` would not make sense anyway, when the `File` and `Hash` parameters do not support multiple values.

**Comment by Mikejo5000** [comment]
Updating doc...
