### ISSUE TITLE
Automate assigning subscriptions

### ISSUE THREAD

**Issue by sirnumpty** [MicrosoftDocs/visualstudio-docs#4007]
Is there an API for automating subscription assignments? It seems incongruous that assigning access to a primary the toolset used for creating automation cannot be automated...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec954beb-b170-4bf7-37e7-a7d7474c528b
* Version Independent ID: f9f87bac-6ec0-a386-403c-39469de44e2d
* Content: [Edit subscriptions in the Administration Portal](https://docs.microsoft.com/en-us/visualstudio/subscriptions/edit-license#feedback)
* Content Source: [subscriptions/edit-license.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/edit-license.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by TerryGLee** [comment]
@sirnumpty Thanks for your inquiry.
@evanwindom For your review and comment.

**Comment by evanwindom** [comment]
@sirnumpty - Thank you for reaching out.  I reached out to our subscriptions engineering team, and we don't have currently anything available for customers to use to automate assignments.  We've had several similar requests lately, and I'll definitely keep an eye out for any news.  If something become publicly available, I'll post updates here.

**Comment by evanwindom** [comment]
#please-close
