### ISSUE TITLE
File parameter of VerifyFileHash task is String, not ITaskItem

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#4009]
The documentation of the VerifyFileHash task of MSBuild claims that it has a parameter with the name `File` and the type `ITaskItem`.  In the implementation however, the type of this parameter is `String`.  https://github.com/microsoft/msbuild/blob/vs16.3/src/Tasks/FileIO/VerifyFileHash.cs#L21

Also, the documentation describes this parameter as "The files to be hashed and validated." This is not quite right; the parameter only supports one file, rather than multiple.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffa6013d-443a-570a-ca70-f3cad50a3b34
* Version Independent ID: d422fed1-420d-bf97-33c4-1842d5861696
* Content: [VerifyFileHash  Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/verifyfilehash-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/verifyfilehash-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/verifyfilehash-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
That looks like a string to me, too. @rainersigwald to verify before I update.

**Comment by rainersigwald** [comment]
That _should_ have been an `ITaskItem` but it isn't. Update away.
