### ISSUE TITLE
Totally unclear description

### ISSUE THREAD

**Issue by evil-shrike** [MicrosoftDocs/visualstudio-docs#401]
> If you own extensions that use custom project or item templates, you need to update your extensions. This topic explains what you must do. 

But actually the page says nothing about what I must do and how to update a vsix project for VS2017. 
You just put samples of .vstemplate and .vstman from 2015 and probably 2017 (but called it 2015) without any description.
"Here is the .vstman file .. that resulted from the rebuilding of the VSIX project" - why should I care of .vstman if it's built by a tool?.
You said nothing about changes in vstemplate schema (if there're someones), nothing about changes in .vsixmanifest (Assets/Asset) (if there're someones).
In my case I have a vsix project with custom item templates but while it's built with vs2017 sdk the vsix doesn't contain templates anymore. So obviously there're breaking changes. And they are not documented anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3fd207-345e-db60-1731-37d200753677
* Version Independent ID: e1b7b843-548d-a1b3-9394-f71ed5881aee
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/upgrading-custom-project-and-item-templates-for-visual-studio-2017)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/upgrading-custom-project-and-item-templates-for-visual-studio-2017.md)

**Comment by gewarren** [comment]
@gregvanl this is an extensibility topic. Can you take a look?

**Comment by lmstearn** [comment]
It's all a bit bamboozling, admittedly. Came across the page referenced from the answer in the link of [my comment](https://stackoverflow.com/questions/27381941/how-can-i-load-a-template-i-have-created-in-visual-studio/47142565#comment83070744_47142565) after exporting a project to a template which was done from the file menu. No VSIX.
The docs may want a rejig. From a single user (no team) things are a bit awkward managing templates. Perhaps feature request for [renaming templates](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/32783965-renaming-templates) would help?
Thanks.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
