### ISSUE TITLE
Sample links still point to code.msdn.microsoft.com

### ISSUE THREAD

**Issue by wjk** [MicrosoftDocs/visualstudio-docs#4011]
What the title says, really. I'd appreciate it if the samples are moved elsewhere before the original site is closed. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caf3cc14-c914-da3a-b3ae-7e2d80712166
* Version Independent ID: 070a2258-3275-f62c-bb92-33067da26698
* Content: [Cross-Platform Mobile Development Examples - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/cross-platform-mobile-development-examples?view=vs-2019)
* Content Source: [docs/cross-platform/cross-platform-mobile-development-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/cross-platform-mobile-development-examples.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wjk 

Fear not, the samples will not disappear. They aren't being actively maintained or supported, so they won't go in the [docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/) browser. Instead, they'll be available in an archive repo on GitHub. I'll update the links when the repo is populated. I'm not sure when that's supposed to happen yet.

**Comment by corob-msft** [comment]
Closing, as the work in on the schedule but may take a while to show up.

**Comment by romancerny** [comment]
Sample links are still broken
