### ISSUE TITLE
Item doesn't show in Add New Item

### ISSUE THREAD

**Issue by cbordeman** [MicrosoftDocs/visualstudio-docs#4012]
Got some troubleshooting advice?  I use the wizard and verified it imported the exported item template, yet in the Add New Item dialog it's nowhere to be found. I restarted VS!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e44d5ce-a797-8367-d4d0-0c3a29f0b18c
* Version Independent ID: d3203ea3-2a1b-f418-62a9-0024c5e03685
* Content: [Create item templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-item-templates?view=vs-2019)
* Content Source: [docs/ide/how-to-create-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@cbordeman Thank you for the feedback, we're sorry your experiencing issues.

A few things to double-check...

- Verify the template is located in the correct folder, for example, `%USERPROFILE%\Documents\Visual Studio <version>\My Exported Templates`

- Check you're working with the correct version of Visual Studio (if multiple versions are installed)

- Make sure your `<TemplateID>`, `<ProjectType>`, and `<ProjectSubType>` match the project you're using

Please include these details and any `<VSTemplate>` code to further help troubleshoot this issue.

**Comment by msebolt** [comment]
Closing the the issue now, please comment below if there are any concerns.
