### ISSUE TITLE
Use of const directly contradicts documentation on C# const keyword

### ISSUE THREAD

**Issue by Kissaki** [MicrosoftDocs/visualstudio-docs#4013]
This 'use const' rule takes a practical approach with focus on performance.

However, it directly contradicts the documentation on the C# `const` keyword.

From the const keyword documentation:

> Don’t create a constant to represent information that you expect to change at any time. For example, don’t use a constant field to store the price of a service, a product version number, or the brand name of a company. These values can change over time, and because compilers propagate constants, other code compiled with your libraries will have to be recompiled to see the changes.

By this definition const should *not* be used for all static readonly strings in general.

This documentation should at least mention this opposed interest and argue when it makes sense anyway, or when it does not make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e57376-8f23-8a6d-49fe-4463331de6c7
* Version Independent ID: edfc1ca3-e006-bd18-c6fd-7ab9c7dd62bf
* Content: [CA1802: Use Literals Where Appropriate - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1802-use-literals-where-appropriate?view=vs-2019)
* Content Source: [docs/code-quality/ca1802-use-literals-where-appropriate.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1802-use-literals-where-appropriate.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Mikejo5000** [comment]
Adding a disclaimer note with link to the referenced documentation for const. MicrosoftDocs/visualstudio-docs-pr#5933
That seems preferable vs. discussing whether or not to use const in this topic.
