### ISSUE TITLE
Missing Prerequisites element section description

### ISSUE THREAD

**Issue by momchilstefanov** [MicrosoftDocs/visualstudio-docs#4014]
I've been interested in understanding the function of the Version attribute of the Prerequisite element in the VSIX extension schema 2.0 reference but the document is actually missing the entire Prerequisites element section.

We have ASP.NET Core VS extension which targets VS2017 and VS2019 and supports both .NET Core 2.1 and .NET Core 3.0 projects. We were using "Microsoft.NetCore.ComponentGroup.Web.2.1" as a prerequisite for the VSIX but with the 16.3 version of VS2019 it seems we need to start detecting "Microsoft.NetCore.Component.Web". I hoped that we could define 2 prerequisite elements which will be evaluated for different Visual Studio versions like this:
```xml
<Prerequisites>  
    <Prerequisite Id="Microsoft.NetCore.ComponentGroup.Web.2.1" Version="[15.0,16.3)" DisplayName=".NET Core 2.1 development tools" />
    <Prerequisite Id="Microsoft.NetCore.Component.Web" Version="[16.3,)" DisplayName=".NET Core 3.0 development tools" />
</Prerequisites>
```

This didn't work as we expected because the installation of the VSIX with such Prerequisites definition fails. In this context it could also be useful if you link some resources which describe the structure and interdependencies of the Visual Studio workloads, component groups and components so we could make better decisions when defining prerequisites.

**Comment by msebolt** [comment]
@momchilstefanov Thank you for the feedback.

It sounds like the [VSIX extension schema reference](https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2019) should be updated to include `Prerequisites`, assigning the author now.

Using multiple versions of Visual Studio sounds like an issue for the product team, please consider moving the issue to the [Visual Studio forum](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by madskristensen** [comment]
What version of Visual Studio has the `Prerequisites` element missing from the schema? It should be there in VS2017 and newer

**Comment by msebolt** [comment]
It's missing from the schema reference, not listed in https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference?view=vs-2019.
________________________________
