### ISSUE TITLE
sos

### ISSUE THREAD

**Issue by Djmattkoma** [MicrosoftDocs/visualstudio-docs#4016]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72292f7a-7616-4727-ccd3-cf44bb130477
* Version Independent ID: fe3cca82-dfd7-a85c-ab4f-014bc546d668
* Content: [A process has encountered an unrecoverable error - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/visual-studio-unrecoverable-process-error?view=vs-2019#feedback)
* Content Source: [docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/not-in-toc/visual-studio-unrecoverable-process-error.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@Djmattkoma Thank you for the feedback.

Can you please elaborate on the issue?

**Comment by gewarren** [comment]
Closing until we get further details.

**Comment by aleksander-ivanov** [comment]
Very often I meet this error (VS2019 Enterprise)
StreamJsonRpc.RemoteMethodNotFoundException : Unable to find method 'SynchronizeTextAsync/3' on {no object} for the following reasons: An argument was not supplied for a required parameter.
   at async StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](<Unknown Parameters>)
   at async Microsoft.VisualStudio.LanguageServices.Remote.JsonRpcEx.InvokeAsync(<Unknown Parameters>)
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
