### ISSUE TITLE
Button_Click event does not work

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/visualstudio-docs#4019]
@showery-hwang commented on [Mon Sep 30 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1853)

I tried to make it as in the tutorial, but when I click the "Display" button, nothing is displayed. Looking at debugging, it seems that Button_Click method is not entered. Is something wrong?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 329e32a3-766c-1739-022b-5d1a8bc6f4aa
* Version Independent ID: d74a678c-d9b5-90c4-cd63-8451fefaa887
* Content: [C# で WPF を使った Hello World アプリ - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

---

@srvbpigh commented on [Mon Sep 30 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1853#issuecomment-536406486)

Hello, @showery-hwang
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

---

@showery-hwang commented on [Mon Sep 30 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1853#issuecomment-536432846)

I add Click property to Button tag as follow, so it worked.
Click="Button_Click"

**Comment by lichasu** [comment]
Hi team, 

Please check this issue. The user finds out why it wasn't working. 

Thanks!

**Comment by timheuer** [comment]
@terryglee This can be closed as prior the original logger indicated he fixed his issue:
>I add Click property to Button tag as follow, so it worked.
Click="Button_Click"

**Comment by TerryGLee** [comment]
@timheuer We might need to add that to the tutorial (if it isn't already there). The tutorial has a new owner now, so I'll let @ornellaalt confirm and move forward from here.

**Comment by anandmeg** [comment]
@showery-hwang, thanks for your feedback! Apologies for the delay in getting back to you.
When the user completes the "Add code to the display button" section of the tutorial, the XAML markup gets updated to include the click property (_Click="Button_Click"_ ) for the Button.
We'll close this issue now, with our thanks to you for your feedback!
