### ISSUE TITLE
Broken Link: Microsoft Support Article 925521

### ISSUE THREAD

**Issue by rygar08** [MicrosoftDocs/visualstudio-docs#4021]
Hi, Can you please fix the broken link in the "Update expired certificates" section. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 639bf0f8-bebf-85f1-a66d-1195cc9dddd4
* Version Independent ID: 33414069-c000-92f4-2b38-63bd7c0213bb
* Content: [ClickOnce and Authenticode - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-and-authenticode?view=vs-2019#feedback)
* Content Source: [docs/deployment/clickonce-and-authenticode.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/clickonce-and-authenticode.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rygar08 Thx! I'll get it updated.

**Comment by rygar08** [comment]
Hi, Any update on fixing this link. Eagerly awaiting :)

**Comment by Mikejo5000** [comment]
Sorry for the delay, looks like this is not so easy after all. 925521 has been removed. At the moment, I'd recommend you open a support request or, perhaps, check for solutions based on the error message you're seeing.

To open a support request, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
This might be relevant: https://stackoverflow.com/questions/280472/how-can-i-renew-my-expired-clickonce-certificate

**Comment by Mikejo5000** [comment]
Doc update needed: remove the link
