### ISSUE TITLE
CA warnings from code analyzers shown as errors after migration

### ISSUE THREAD

**Issue by marhja** [MicrosoftDocs/visualstudio-docs#4022]
When migrating to code analyzers our legacy code analysis warnings changed to errors. We soon realized it was because we have set "Treat warnings as errors" under Build Properties for our projects in Visual Studio. But it was a surprise since it seems to be undocumented here.

We thought having compiler warnings as errors, code analysis violations as warnings and style violations as messages worked very well. Is it possible to set it up that way with code analyzers?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36455e6f-5542-5223-b242-9cddf6df267c
* Version Independent ID: 946abcdb-7e41-b5b5-e062-9cd8c914fbd3
* Content: [Code analysis using Roslyn analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019#feedback)
* Content Source: [docs/code-quality/roslyn-analyzers-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/roslyn-analyzers-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by WilliamAntonRohm** [comment]
@marhja -- Markus, thank you for your feedback.  Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@gewarren -- Genevieve, please consider adding this information.

**Comment by gewarren** [comment]
@mavasani Is it possible to have compiler warnings treated as errors but not code analyzer warnings?

**Comment by mavasani** [comment]
Yes, users can set the following MSBuild property in their project file:

```
<PropertyGroup>
   <CodeAnalysisTreatWarningsAsErrors>false</CodeAnalysisTreatWarningsAsErrors>
</PropertyGroup>
```

Please ensure that the above property is set prior to the imports for the FxCopAnalyzers props file.

**Comment by mavasani** [comment]
FYI: To work around the bug I mentioned above, you can do the following:

1. Add the Directory.build.props file with the contents above.
2. Add an explicit `Import` for the props file prior to the PackageReference:

```
  <Import Project="$(NuGetPackageRoot)\microsoft.codeanalysis.fxcopanalyzers\2.9.4\build\Microsoft.CodeAnalysis.FxCopAnalyzers.props" />
  
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.4" />
  </ItemGroup>
```

This will generate an MSBuild warning as follows, which can be ignored:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB4011	"C:\Users\mavasani\.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.4\build\Microsoft.CodeAnalysis.FxCopAnalyzers.props" cannot be imported again. It was already imported at "C:\Users\mavasani\source\repos\ConsoleApp19\ConsoleApp19\obj\ConsoleApp19.csproj.nuget.g.props (20,5)". This is most likely a build authoring error. This subsequent import will be ignored. 	ConsoleApp19		9	
```
