### ISSUE TITLE
Profiler Marks View not working as expected

### ISSUE THREAD

**Issue by rs38** [MicrosoftDocs/visualstudio-docs#4024]
I want to create a filter between two marks, select the marks, right-click, and then there is only "copy". No "Add Filter by Marks" or "Add Filter by Timestamp" as documented.
Tested with VS 2019.3 and VS 2017.9 and Sampling als well as Instrumented Profiler analysis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecfefa2c-7424-5c43-47ab-fe1091d5096b
* Version Independent ID: 3a72ce4b-9eaf-03a2-353e-7b0992d4bac7
* Content: [Marks View - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/marks-view?view=vs-2019)
* Content Source: [docs/profiling/marks-view.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/marks-view.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Only VS 2017 should provide the functionality described in the doc here. Deprecated in VS 2019. Probably, the VS 2017 doc is out of date, but closing this as low-priority fix for a legacy feature.

The best statement I've seen about the changes in VS 2019 is here, the comments by Allen Denver.
https://developercommunity.visualstudio.com/content/problem/441152/missing-profiler-options-under-debug-visual-studio.html

**Comment by rs38** [comment]
I'd like to add the content of the linked comment, as long as available.

> > In Visual Studio 2019 the Performance Explorer and related options (like the Performance Wizard) were folded into what is now called the Performance Profiler. This is available via ALT-F2 and from the "Performance Profiler..." command in the Debug menu. In the Performance Profiler (which is also known as the Diagnostics Hub) you'll find various types of diagnostics tools available depending on the target chosen and the type of project when the target is the F5 startup project (this is the most common option and the default). The CPU Usage tool provides the sampling capability that was in the Performance Wizard. The Instrumentation tool provides the instrumented profiling capability (for precise call counts and durations) that was in the Performance Wizard. There are a couple of different types of memory tools in the Diagnostics Hub too.
> 
> As a result of this merge, we've removed the Performance Explorer and the Performance Wizard. This change is by-design. The issue in the original post for this thread was interpreted at that time to be a transient problem with the new Performance Profiler that occurred in Preview 2 of Visual Studio 2019 which caused some parts of the Performance Profiler to be missing. That was an install issue and that problem was fixed so this issue was closed as Fixed.

**Comment by Mikejo5000** [comment]
Thanks! Good idea.
