### ISSUE TITLE
xUnit Test Generator extension not updated for VS 2019

### ISSUE THREAD

**Issue by i-b1** [MicrosoftDocs/visualstudio-docs#4027]
There is another one at https://marketplace.visualstudio.com/items?itemName=YowkoTsai.xUnitnetTestGenerator.  Perhaps should be linked as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b8edaf-7667-a3e6-38dc-371c53bcd386
* Version Independent ID: 580e757e-8ce7-1437-3843-c88ff4f3ab54
* Content: [Generate unit tests for your code with IntelliTest - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/generate-unit-tests-for-your-code-with-intellitest?view=vs-2019#feedback)
* Content Source: [docs/test/generate-unit-tests-for-your-code-with-intellitest.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/generate-unit-tests-for-your-code-with-intellitest.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@i-b1 Thanks for pointing this out. It looks like it doesn't work with Visual Studio 2017 either? Also, the extension from Yowko Tsai says it doesn't support IntelliTest, so we can't link to that one from this topic.

**Comment by i-b1** [comment]
Unfortunately you are correct. Old extension did not work in VS2017/2019. New extension can generate unit test via UI command, but does not support IntelliTest (yet). I think that ASP.NET team uses xUnit, so the lack of support is surprising. I do not see a good solution except unlinking of old extension for the time being.

**Comment by lanatmwan** [comment]
Microsoft, please consider devoting some resources to adding intellitest support to the linked test generator. It is an open source project on github: https://github.com/yowko/xUnit.net.TestGenerator
