### ISSUE TITLE
when the EMS benefit will again be available for activation

### ISSUE THREAD

**Issue by LegoSCCMGuy** [MicrosoftDocs/visualstudio-docs#4032]
Is there an updated timeline on when the EMS benefit will again be available for activation?

**Comment by msebolt** [comment]
@LegoSCCMGuy Thank you for the question.

EMS author @evanwindom should know more about this.

**Comment by evanwindom** [comment]
@LegoSCCMGuy - Thanks for reaching out.  We're making progress here and anticipate a resolution soon.  Thanks for your patience.  

If you haven't already activated the Office 365 Developer subscription, there's a new benefit that will solve this issue for you.  We're now offering Microsoft 365 (M365), which includes both the Office 365 Developer and EMS benefits.  Look for the Microsoft 365 benefit tile in the Tools category at https://my.visualstudio.com/benefits.  

(If you have already activated the Office 365 Developer subscription, you won't be able to activate M365.)

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
