### ISSUE TITLE
In a UWP project, how to set the environment variable ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO?

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/visualstudio-docs#4033]
In a UWP project, how does one set the environment variable ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8368af75-bb65-b3bc-bcbc-67a2739e5bc3
* Version Independent ID: f6142191-d659-83f2-76a2-6b8afda90774
* Content: [Troubleshooting XAML Hot Reload - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/xaml-hot-reload-troubleshooting?view=vs-2019)
* Content Source: [docs/debugger/xaml-hot-reload-troubleshooting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/xaml-hot-reload-troubleshooting.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@LyalinDotCom for input

**Comment by dpaulino** [comment]
Looks like the page was updated with instructions on how to set the environment variable. Thanks!

**Comment by Mikejo5000** [comment]
Yes, thanks for the follow up!
