### ISSUE TITLE
Doesn't work if using window's high contrast theme

### ISSUE THREAD

**Issue by behealed** [MicrosoftDocs/visualstudio-docs#4035]
If you set Windows 10 to High Contrast theme, then the Color Theme dropdown box inside VS2019 described on this page (under Environment-&gt;General) is greyed out and cannot be changed. And visual studio will appear all in black and white, and all your source code will be in white colored text only, which makes it slow and much more difficult to read your code. You lose all the colorization of your source code. If you know how to edit the registry, it is possible to copy all the values from the dark theme into the high contrast theme, thus forcing visual studio to use the dark theme. There is a tutorial that can be found on google, which worked on VS2017, explaining how to do this. But editing the registry is very advanced and dangerous. Also, every time you install any update to visual studio, it overwrites any edits you made to the registry, which means you have to do the registry hack all over again to get the colors fixed. That's a huge pain in the butt. There is no reason why visual studio shouldn't allow users of the high contrast windows theme to edit the color theme inside visual studio. The very fact that we can hack the registry to forcibly fix the problem, shows that there is no technical reason why visual studio can't use its "dark" theme when windows is set to high contrast theme. It CAN be done through registry hacking, so WHY can't it simply be done under Environment-&gt;General? Why does visual studio grey-out the option to switch the color theme? WHY? This problem existed in VS2017 and was reported as a bug many times by many people, but it was never fixed during the years that we had VS2017. And now we're on VS2019 and the problem still exists. Will it ever be fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e23c15-7abd-d973-48c0-e4b23e305c5c
* Version Independent ID: 97329301-f6ac-4cba-8b85-a958a0bfc1a5
* Content: [Set color theme and fonts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-personalize-the-ide?view=vs-2019#feedback)
* Content Source: [docs/ide/quickstart-personalize-the-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-personalize-the-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@behealed  Thank you for the feedback.

Unfortunately this is an issue only the product team can handle, however there's a [current thread](https://developercommunity.visualstudio.com/idea/527413/visual-studio-forces-the-user-to-use-its-high-cont.html) available for you to cast your vote, comment, etc.

**Comment by msebolt** [comment]
Closing this issue now, please comment below if there are any questions.
