### ISSUE TITLE
wrong instructions in step 7, missing: need to copy also the definition of make_dot_string to the interactive window

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/visualstudio-docs#4036]
@aisbergde commented on [Wed Oct 02 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/66)

if following the instruction in step 7 it will not work:
only bring the import part to the interactive Window and then to call the function will not work.

In the instruction you should write, that not only the import and from needs to be transfered to the interactiv window, but also the definition of make_dot_string.

The screenshot is write, only the instruction is missing a part.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 781f50f5-dc28-6776-71e9-c3cfbcb87ff4
* Version Independent ID: 8d7da87c-b17d-d3d2-aacd-3242e632b652
* Content: [Tutorial „Python in Visual Studio“, Schritt 3: Interaktive REPL](https://docs.microsoft.com/de-de/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

---

@srvbpigh commented on [Wed Oct 02 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/66#issuecomment-537497679)

Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue.

Thanks!

**Comment by msebolt** [comment]
The documentation has been updated.

**Comment by msebolt** [comment]
Need to clarify the second statement further, PR pending.
