### ISSUE TITLE
You should add information how to not execute the line but to add a new line to get the "..."

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/visualstudio-docs#4037]
@aisbergde commented on [Wed Oct 02 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/65)

at 4:
When writing a multi-line statement, such as a function definition, the interactive window will display the Python ... prompt to resume the lines, which provides automatic indenting, as opposed to command line REPL:

You should add information how to not execute the line but to add a new line to get the "..."
For example "press Ctrl-Enter instead of Enter to ..."

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 781f50f5-dc28-6776-71e9-c3cfbcb87ff4
* Version Independent ID: 8d7da87c-b17d-d3d2-aacd-3242e632b652
* Content: [Tutorial „Python in Visual Studio“, Schritt 3: Interaktive REPL](https://docs.microsoft.com/de-de/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/python/tutorial-working-with-python-in-visual-studio-step-03-interactive-repl.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

---

@srvbpigh commented on [Wed Oct 02 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/65#issuecomment-537497713)

Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue.

Thanks!

**Comment by JoshuaPartlow** [comment]
Thanks you for your feedback, the docs will be updated to reflect that `Shift+Enter` should be used to create a new **...** line shortly.
