### ISSUE TITLE
CA1001:  Allow this rule to be suppressed for types without dispose ownership

### ISSUE THREAD

**Issue by peteroupc** [MicrosoftDocs/visualstudio-docs#4047]
The statement "Do not suppress warning from this rule" on this page may be too strict.  Rather, this warning should be suppressable if the type in question does not have _dispose ownership_, as defined in and allowed by the documentation for CA2213.  Additionally, I believe that a type that&mdash;

- takes an `IDisposable` object as a constructor argument, and stores that argument in a `readonly` field, and
- does not otherwise store `IDisposable` objects in any of its fields,

is presumed not to have _dispose ownership_, because the responsibility for disposing the `IDisposable` object lies elsewhere.  (This is often the case for many types that "wrap" `IDisposable` objects and give them special functionality, as in my [StringOutput class](https://github.com/peteroupc/CBOR/blob/master/CBOR/PeterO/Cbor/StringOutput.cs).)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c11c2ae2-fde5-91d4-9fd9-b949c8527ede
* Version Independent ID: 6386b34b-5717-55b6-bef0-3cc979f33f0c
* Content: [CA1001: Types that own disposable fields should be disposable - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1001-types-that-own-disposable-fields-should-be-disposable?view=vs-2019)
* Content Source: [docs/code-quality/ca1001-types-that-own-disposable-fields-should-be-disposable.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1001-types-that-own-disposable-fields-should-be-disposable.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by peteroupc** [comment]
I have become aware that CA2213 has special rules for so-called _dispose ownership transfer_ that applies to certain `IDisposable` types, notably `System.IO.Stream`.  However, I believe this dispose ownership rule should not apply if _nothing_ in the assembly created the `IDisposable` object in question.

**Comment by gewarren** [comment]
> However, I believe this transfer rule should not apply if...the code that triggered the dispose ownership transfer disposes the IDisposable object by itself.

@peteroupc I think the statement in [when to suppress a warning](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2213-disposable-fields-should-be-disposed?view=vs-2019#when-to-suppress-warnings) for CA 2213 covers this case:

"The flagged type is not responsible for releasing the resource held by the field (that is, the type does not have dispose ownership)"

@mavasani Should I update the CA1001 and CA2213 docs to include any of the following?

CA1001: Safe to suppress if the type doesn't have dispose ownership of the disposable field
CA2213: Safe to suppress if DTO doesn't apply because nothing in the *assembly* created the IDisposable object

**Comment by mavasani** [comment]
> Should I update the CA1001 and CA2213 docs to include any of the following?

Sounds reasonable to mention that either of these rules can be suppressed when the dispose ownership of field(s) is not held by the containing type.

**Comment by Mikejo5000** [comment]
Updating in /MicrosoftDocs/visualstudio-docs-pr/5930

**Comment by Mikejo5000** [comment]
Fix went live
