### ISSUE TITLE
Visual Sudio for macOS Guidance

### ISSUE THREAD

**Issue by chuckwolber** [MicrosoftDocs/visualstudio-docs#4048]
This page appears to be geared towards the Windows version of Visual Studio. For example "On the File menu, select Add &gt; New Project." does not match what is found in the macOS version of Visual Studio. The "tip" below the aforementioned guidance, however, does. This seems more like an afterthought, rather than a concerted effort to document Visual Studio for all supported platforms.

I congratulate Microsoft for supporting Visual Studio on multiple platforms! I hope the documentation can catch up.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a29f3723-6a51-ae9f-c1a7-07d59b30d0a2
* Version Independent ID: 9cd1552e-1579-7da1-ffc0-e41b51fb3ae1
* Content: [Visual Studio for Mac Tour - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/ide-tour)
* Content Source: [mac/ide-tour.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/ide-tour.md)
* Product: **visual-studio-mac**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by Mikejo5000** [comment]
VS for Mac docs are here:
https://docs.microsoft.com/en-us/visualstudio/mac/ide-tour?view=vsmac-2019
It doesn't look like there are currently any docs here specific to unit testing on VS for Mac, so search probably caused you to end up in VS for Windows.

**Comment by Mikejo5000** [comment]
I'll try to transfer the issue to the other doc set.

**Comment by conceptdev** [comment]
Looks like this page has been updated since the feedback was submitted - the phrase "On the File menu, select Add > New Project" no longer appears in the text (and the entire page is most certainly focused on the macOS version of Visual Studio).

**Comment by Mikejo5000** [comment]
My mistake--I moved this from the original topic, but that's misleading. I'll move it back. I interpret this issue as a general request for unit testing docs for VS for Mac.

**Comment by conceptdev** [comment]
Ah, now the thread makes more sense! Yes, it appears we do not have Visual Studio for Mac-specific guidance on unit testing - I have passed that on to the team for their consideration.
