### ISSUE TITLE
Documentation out of date.

### ISSUE THREAD

**Issue by AraHaan** [MicrosoftDocs/visualstudio-docs#405]
It also seems that ``C26490``, ``C26425``, ``C26485``, and ``C26425`` which have been complaining on my good code and wont shut up because I need direct use of some Windows API functions the C++ standard library never calls or other things like:

Caching the ``HINSTANCE`` of ``hDLL`` on ``DllMain()`` in an global variable for passing into ``Shell_NotifyIconA`` Unless I can use the process's ``HWND`` instead that I cache in an ``setup`` struct.

Another instance of that warning is when I need to pass the ``HWND`` handle of the process to an global instance of an struct for subclassing the target application's WndProc for telling the OS to never go into ``SC_SCREENSAVE`` and ``SC_MONITORPOWER`` by returning 0 from WndProc to ``cancel`` those syscommands while the process is running.

**Comment by gewarren** [comment]
@corob-msft or @mikeblome can one of you look at this?

**Comment by AraHaan** [comment]
Also some example Code to test the warnings is like the following:

```cpp
struct WNDDATA {
  HWND m_hWnd;
  LONG m_OrigWndProc;
  BOOL m_Subclassed;
};
WNDDATA g_Window;
HINSTANCE dll_inst;

LRESULT CALLBACK SCWinProc(HWND hWnd,UINT uMsg,WPARAM wParam,LPARAM lParam) noexcept
{
  switch(uMsg) {
    case WM_DESTROY: {
      SetWindowLongPtr(g_Window.m_hWnd, GWL_WNDPROC, g_Window.m_OrigWndProc);
      break;
    }
    case WM_CLOSE: {
      SetWindowLongPtr(g_Window.m_hWnd, GWL_WNDPROC, g_Window.m_OrigWndProc);
      break;
    }
    case WM_SYSCOMMAND: {
      switch (wParam) {
        case SC_SCREENSAVE:
        case SC_MONITORPOWER:
        return 0;
      }
      break;
    }
    default:
      break;
  }
  return CallWindowProc(reinterpret_cast<WNDPROC>(g_Window.m_OrigWndProc), hWnd, uMsg, wParam, lParam);
}

__declspec(dllexport) BOOL SubClassWindowProc(HWND hWnd) noexcept
{
  g_Window.m_hWnd = hWnd;
  g_Window.m_OrigWndProc = GetWindowLongPtr(g_Window.m_hWnd, GWL_WNDPROC);
  if (SetWindowLongPtr(g_Window.m_hWnd, GWL_WNDPROC, (LONG)SCWinProc) == g_Window.m_OrigWndProc) {
    g_Window.m_Subclassed = TRUE;
  }
  else {
    g_Window.m_Subclassed = FALSE;
  }
  return g_Window.m_Subclassed;
}

BOOL __fastcall DllMain(HINSTANCE hDLL, DWORD reason, LPVOID lpReserved) noexcept
{
  switch (reason) {
  case DLL_PROCESS_ATTACH:
#if _MSC_VER >= 1911
#pragma warning(suppress: 26425)
#endif
    vbtrpint_inst = hDLL;
    break;
  }
  return TRUE;
}
```
Also seems to complain if I don't mark everything ``noexcept`` as well.

**Comment by corob-msft** [comment]
Was this comment intended to be about a particular code analysis warning article in our documentation? If so, that information has been lost.

Unfortunately, the documentation doesn't always keep up with the product. For C26490, see the blog post [C++ Core Check improvements in Visual Studio 2017 15.5](https://blogs.msdn.microsoft.com/vcblog/2017/11/15/c-core-check-improvements-in-visual-studio-2017-15-5/). C26485 is available at [C26485 NO_ARRAY_TO_POINTER_DECAY](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26485). We don't have any documentation available for C26425 yet. Maybe it's part of a general rule against global variables. 

Given the nature of the raw Windows APIs, there is no way to use them in a way that complies with all the C++ core guidelines. When you have to convert a long into a function pointer and vice-versa, type safety goes out the window. There are all sorts of type impedances in the Windows API that are like that. So, in my opinion, if you want to have code that compiles cleanly with all the analysis rules turned on, then the best you can do is to isolate the Windows API calls into a library where all the ugly plumbing is hidden, build it separately, and consume it from the code that must be clean.
