### ISSUE TITLE
Update Screenshots on Testing Page

### ISSUE THREAD

**Issue by Anapo14** [MicrosoftDocs/visualstudio-docs#4050]
The screenshots on [this ](https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2019)page below the section **Run Tests**, should be updated to reflect the new VS 2019 UI. The ones above it are updated.

**Comment by JoshuaPartlow** [comment]
Topic has been updated, but issue wasn't closed. Closing now.
