### ISSUE TITLE
Paths are wrong on 64bits computers

### ISSUE THREAD

**Issue by gfox1984** [MicrosoftDocs/visualstudio-docs#4053]
Paths on 64bits computer are wrong. Seems to be in there: C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\x64

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19fc0b32-aa03-b072-067c-f3d961dca152
* Version Independent ID: 6299d0c5-d674-7e2f-8d3d-4ba097d2ea52
* Content: [Specifying the Path to Profiling Tools Command Line Tools - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/specifying-the-path-to-profiling-tools-command-line-tools?view=vs-2019#feedback)
* Content Source: [docs/profiling/specifying-the-path-to-profiling-tools-command-line-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/specifying-the-path-to-profiling-tools-command-line-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Fixed already for managed path.

**Comment by Mikejo5000** [comment]
Updating to fix formatting. But it looks like native path is OK.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Performance Tools\x64
