### ISSUE TITLE
Excessive and uninformed.

### ISSUE THREAD

**Issue by warp-10** [MicrosoftDocs/visualstudio-docs#4057]
This misinterprets what was previously thought to be a benefit of inheritance. Such things are intended when functions must act through interface references instead of concrete types.

Implicit cast-to-base has its utility, and is why that feature exists in the first place. Moreover, the compiler should not warn in the case of a function "slicing" its return value in the presence of static_cast, etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be6a0e19-d61f-fefb-4a83-afa87219e168
* Version Independent ID: 206fffd7-3651-5783-49e0-c586a9b8b992
* Content: [C26437 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26437?view=vs-2019#feedback)
* Content Source: [docs/code-quality/C26437.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26437.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@warp-10 Interesting comments but I think you should address them to the authors of the core guidelines themselves. The source for the guideline is here: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Res-slice (and I will add that link to our topic).

**Comment by warp-10** [comment]
The guidelines apply to polymorphic objects. Your compiler is emitting this
warning for anything that results in "slicing", even for non-polymorphic
types. The example in your article even demonstrates this, which is why it
is not correctly implemented.

**Comment by mikeblome** [comment]
@warp-10 I see. Thanks for the clarification! Are you willing to raise this issue on the [C++ Developer Community forum](https://developercommunity.visualstudio.com/topics/C%2B%2B.html)? The product team actively monitors that site for actionable issues, and other developers can upvote your issue.

**Comment by warp-10** [comment]
Certainly. I was initially under the impression this was a Microsoft-specific warning, which is why I commented on the documentation page. This is really a bug, but I'm having trouble creating a minimal example that reproduces it. The function I'm trying to simplify needs to deliberately "slice" an almost-POD resource "pointer" into a lightweight "handle" (from which said pointer type derives).

**Comment by mikeblome** [comment]
@warp-10 I'm going to close this as it doesn't seem to be a documentation bug. Good luck on creating a repro. That will make a big difference in how it gets handled internally.
