### ISSUE TITLE
Broken numbering on "Enable Coded UI Testing Of Your Controls"

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/visualstudio-docs#406]
https://docs.microsoft.com/en-gb/visualstudio/test/enable-coded-ui-testing-of-your-controls

Ordered list numbering goes wrong half way down the page.

![image](https://user-images.githubusercontent.com/4837132/34408283-e8242f5c-ebba-11e7-8317-67d681a4b47c.png)

**Comment by gewarren** [comment]
@ChrisMaddock thanks for reporting this. It is fixed now.

**Comment by ChrisMaddock** [comment]
Thanks @gewarren!
