### ISSUE TITLE
Update CA2002 to detect usage of lock (this) and SyncLock Me

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#4062]
In https://github.com/dotnet/roslyn-analyzers/pull/2869 I have updated the rule CA2002 to also detect locks on `this`. Could you please update the documentation to match the new rule specification?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b97ee078-36f0-1f9b-cb29-93293989d5f6
* Version Independent ID: 786d0d32-ffdc-a6e5-fcd7-484b04cc3cf1
* Content: [CA2002: Do not lock on objects with weak identity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2002-do-not-lock-on-objects-with-weak-identity?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2002-do-not-lock-on-objects-with-weak-identity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2002-do-not-lock-on-objects-with-weak-identity.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by mavasani** [comment]
Additional note: This change will first be released as part of FxCop analyzers package 3.0.0

**Comment by Mikejo5000** [comment]
Updating in MicrosoftDocs/visualstudio-docs-pr/pull/5930
