### ISSUE TITLE
Remove Azure Artifacts from eligibility table

### ISSUE THREAD

**Issue by elbatk** [MicrosoftDocs/visualstudio-docs#4065]
Hello! I'm a PM from Azure Artifacts. I think we should remove the references to Azure Artifacts in the Eligibility section (in the table and the footer notes below), because every organization gets 2GB free of Azure Artifacts, regardless of VS subscription, thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by WilliamAntonRohm** [comment]
@elbatk -- Elijah, thank you for your feedback.

@evanwindom -- Evan, please assign this issue 4065 to yourself or to an appropriate author.

**Comment by WilliamAntonRohm** [comment]
@gdverrastro -- please look into this update.

@evanwindom -- never mind; my apologies for the churn.

**Comment by evanwindom** [comment]
@elbatk - Elijah - Thanks for bringing this to our attention.  A PR has been submitted to make this change.

**Comment by evanwindom** [comment]
Resolved by PR #5596.  @WilliamAntonRohm - please close this.

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- thank  you.
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
