### ISSUE TITLE
Associate tenant with diffirent MSDN subscription

### ISSUE THREAD

**Issue by dimachernov** [MicrosoftDocs/visualstudio-docs#4068]
If a user's MSDN subscription is getting cancelled, would it be possible to reassociate the O365 tenant with a different MSDN subscription, so that the tenant would still be renewable?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22a69a8-de38-2929-144a-0bd738f40a25
* Version Independent ID: a1d94b1f-c61e-df28-d412-1195aa9ace6d
* Content: [The Office 365 Developer Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-office-dev#feedback)
* Content Source: [subscriptions/vs-office-dev.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-office-dev.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by msebolt** [comment]
@dimachernov Thank you for the question, the issue has been assigned.

FYI @evanwindom

**Comment by evanwindom** [comment]
@dimachernov - Thanks for the question.  The Office Developer benefit and the tenant it creates cannot be moved between subscriptions.  However, after the subscription expires you have 90 days to migrate any data in the existing tenant to a different tenant.  After that 90 days, the data will no longer be accessible.  

Here are some articles that provide additional information about migrating:  

https://docs.microsoft.com/exchange/mailbox-migration/migrate-mailboxes-across-tenants 

https://docs.microsoft.com/office365/enterprise/powershell/use-powershell-to-perform-a-staged-migration-to-office-365 

https://social.technet.microsoft.com/Forums/ee507441-eb91-4b0a-ba6c-5bd9bb8c71b1/migration-from-one-o365-tenant-to-another-o365-without-third-party?forum=onlineservicesmigrationandcoexistence 

@msebolt - Please close. 
@gdverrastro - FYI.
