### ISSUE TITLE
How can I use Processor

### ISSUE THREAD

**Issue by KannanKrish** [MicrosoftDocs/visualstudio-docs#4069]
I want to create a multi-project template based on conditional. Simply I want to use #if like

               # if (condition/custom parameter)
			<SolutionFolder Name="$projectname$.ML" CreateOnDisk="true">
				<ProjectTemplateLink ProjectName="$projectname$.MLTrain" CopyParameters="true">
					App3.ML\App3.MLTrain\MyTemplate.vstemplate
				</ProjectTemplateLink>
				<ProjectTemplateLink ProjectName="$projectname$.MLConsume" CopyParameters="true">
					App3.ML\App3.MLConsume\MyTemplate.vstemplate
				</ProjectTemplateLink>
			</SolutionFolder>
	           # endif

I get a custom parameter value from the user using IWizard implementation.

**Comment by msebolt** [comment]
@KannanKrish Thank you for the question.

Right now, this only seems possible using XSD with [Project templates](https://docs.microsoft.com/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2019) (see [this post](https://stackoverflow.com/questions/5087134/can-i-add-conditions-in-app-config-file)).

For something built-in please consider starting a dialog with the product team under **Suggest a Feature** in the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by KannanKrish** [comment]
@msebolt thanks for your help.

Can I get any kind of source code sample to follow?

Thanks

**Comment by msebolt** [comment]
On second thought, this is a lot easier by just using `Choose` and `When`.

Here's an example that checks for a file called 'c.txt' and adds either 'a.txt' or 'b.txt' to the project accordingly:

```xml
<Choose>
        <When Condition="Exists('c.txt')">
            <PropertyGroup>
                <ProjectFile>a.txt</ProjectFile>
            </PropertyGroup>
        </When>
        <When Condition="!Exists('c.txt')">
            <PropertyGroup>
                <ProjectFile>b.txt</ProjectFile>
            </PropertyGroup>
        </When>
    </Choose>
  <ItemGroup>
    <Content Include="$(ProjectFile)" />
  </ItemGroup>
```

For more information, see [Conditional constructs](https://docs.microsoft.com/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2015).

**Comment by msebolt** [comment]
Closing the issue now, please add comments if there any concerns.

**Comment by KannanKrish** [comment]
**Choose** and **When** I can't use it in the multi-template project. Exactly in root.vstemplate. I have a problem with selecting project not project items. I can use MSBuild Constructs after the project created. But I want to select a project I want to create. 

For example, in xamarin Forms project I can create an Android, iOS, UWP project. Based on this user can select project type in the wizard. For example, I only selected the android project. Then Xamarin shared a project and Xamarin.Android project needs to create.

I am looking for that kind of solution.

**Comment by msebolt** [comment]
@KannanKrish I see, at this point I can only recommend using a [Multi-project template](https://docs.microsoft.com/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2015&redirectedfrom=MSDN) and keeping each project empty until you get the user's input and can then pull in the that particular project's items.

Since this is a limitation, start a dialog with the product team at [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) and they can either add it to the new feature list or perhaps know of a way this can be done currently.

**Comment by KannanKrish** [comment]
Thanks @msebolt

**Comment by msebolt** [comment]
Sure, no problem, apologies there's nothing more at this point.

Please refer back to this issue if you decide to involve the product team.
