### ISSUE TITLE
Document GenerateDocumentationFile msbuild property

### ISSUE THREAD

**Issue by dasMulli** [MicrosoftDocs/visualstudio-docs#407]
`common-msbuild-project-properties.md` should contain information about the `GenerateDocumentationFile` property which is easier to use than `DocumentationFile` alone since it does not require specifying an explicit name/path.

**Comment by gewarren** [comment]
@dasMulli thank you, we will take a look.

**Comment by dasMulli** [comment]
for context: This property only works in SDK-based projects but is especially needed when multi-targeting and the `DocumentationFile` property needs to be set differently for the inner builds.

Implementation: https://github.com/dotnet/sdk/blob/35471d2fa7d6ce4a94035f08c5661ea722299a08/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L161-L184

**Comment by svick** [comment]
> This property only works in SDK-based projects

As far as I can tell, properties specific to SDK-based projects are documented in [Additions to the csproj format for .NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj). Does that mean the `GenerateDocumentationFile` property should be documented there and not in `common-msbuild-project-properties.md`?

**Comment by dasMulli** [comment]
Maybe.

I'm not very happy that this document is so specific about .NET Core. but since there aren't any inbox templates (yet?) for .NET Framework SDK-based projects, it's probably okay.

cc @mairaw

**Comment by Mikejo5000** [comment]
Closing this one in favor of #2016, since the .NET Core issue also relates to the SDK-style project issue.

**Comment by SENya1990** [comment]
Hi. I am also interested in this issue. Will the `GenerateDocumentationFile` flag be documented somewhere at least for .Net Core?
I couldn't find it in the documentation except a very brief reference in the F# xml comments guide:
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/xml-documentation

I expected from the previous discussion in this issue that the flag would be described here:
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj
But there is nothing. Are there plans to document it?

**Comment by gewarren** [comment]
I tried to move this issue to the dotnet/docs repo, but I'm not succeeding.

We should document `GenerateDocumentationFile` at https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props and link to it from the C#, Visual Basic, and Visual Studio docs.
