### ISSUE TITLE
Not really 

### ISSUE THREAD

**Issue by josersleal** [MicrosoftDocs/visualstudio-docs#4070]
Azure offers IOS agents. No need to have a remote machine any longer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f33eba-a747-c57b-02e3-853d2a8a5c3b
* Version Independent ID: 1ddd9492-f5b1-d0ae-b813-c3838452a17a
* Content: [Install And Configure Tools to Build using iOS - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios?view=vs-2019)
* Content Source: [docs/cross-platform/install-and-configure-tools-to-build-using-ios.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/install-and-configure-tools-to-build-using-ios.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by msebolt** [comment]
@josersleal  Thank you for the feedback.

Is this a feature request or are you citing an issue with the article that refers to not needing a remote machine?

For feature requests, please consider starting a dialog with the product team using **Suggest a Feature** in the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html).  For documentation issues, I can assign the author.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are further issues.
