### ISSUE TITLE
nameof

### ISSUE THREAD

**Issue by user2150** [MicrosoftDocs/visualstudio-docs#4071]
Why is CA1303 generated on nameof?
How should it be localized?
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a0a1a48-3a9f-05c8-53fd-4d126bb275ad
* Version Independent ID: 65f77e05-47ac-9e01-ce54-9669c2dd9b2b
* Content: [CA1303: Do not pass literals as localized parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1303-do-not-pass-literals-as-localized-parameters?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1303-do-not-pass-literals-as-localized-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1303-do-not-pass-literals-as-localized-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@user2150  Thank you for the questions.

For localization, the article refers to [Resource Manager examples](https://docs.microsoft.com/dotnet/api/system.resources.resourcemanager?view=netframework-4.8#examples), please comment below if these examples are insufficient.

Assigning this to the author to address the issue on `nameof`.

**Comment by gewarren** [comment]
@mavasani The following code triggers CA1303. Is this a bug?

    public class Helpers
    {
        [Localizable(true)]
        public string Text { get; set; }

        public Helpers(string caption)
        {
            Text = nameof(caption);
        }
   }

**Comment by mavasani** [comment]
It looks like a bug... Can you please port it to roslyn-analyzers repo? Thanks.

**Comment by gewarren** [comment]
@user2150 Would you like to create the issue at https://github.com/dotnet/roslyn-analyzers/issues, or would you like me to?

**Comment by gewarren** [comment]
I ported the bug over: https://github.com/dotnet/roslyn-analyzers/issues/2950
@user2150 Thank you for reporting it!

**Comment by user2150** [comment]
gewarren,
Thank you!
