### ISSUE TITLE
Code coverage Menu...

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/visualstudio-docs#4076]
Hi team, please check this issue. I'm transferring from https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/issues/67.

@sybaris wrote:

> Hi,
> 
> I am using Visual Studio 2019 Enterprise. In the Test menu, I don't have the same menu like in your screenshoot. I have only "Live Unit Testing" and "Windows".
> I can find the menu item "Analyze Code Coverage for All Tests" only in Test Explorer window.
> 
> Please update the screenshoot and the text to explain where to find this option...
> 
> Regards
> Jean-Pierre
> 
> My menu Test :
> ![image](https://user-images.githubusercontent.com/51962333/66418554-b75c5480-e9d8-11e9-82ab-f845da3ea16a.png)
> 
> Where to find the menu "Analyze Code Coverage for All Tests"
> ![image](https://user-images.githubusercontent.com/51962333/66418569-be836280-e9d8-11e9-9292-8e3c5c31f3ab.png)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Code coverage testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@sybaris There was a glitch in the Test menu for version 16.2 of Visual Studio 2019. Please upgrade to version 16.3 and the menu should be complete again.
