### ISSUE TITLE
Is the UTF-8 BOM A Requirement of the Solution File Format?

### ISSUE THREAD

**Issue by aolszowka** [MicrosoftDocs/visualstudio-docs#4078]
Based on this pull https://github.com/dotnet/cli/pull/8199 the CLI Tool expects there to be a UTF-8 Byte Order Mark (BOM) in the file. Creating a new solution from Visual Studio also seems to include the BOM. Is this expected? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9177b266-5055-95d6-407f-ca4aad75257a
* Version Independent ID: 4586847b-d990-df3b-4cce-bd9a471eda33
* Content: [Solution (.Sln) file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2019#feedback)
* Content Source: [docs/extensibility/internals/solution-dot-sln-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/solution-dot-sln-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@aolszowka Thank you for the question, assigning this to the author for further information.

**Comment by tfosmark** [comment]
@aolszowka Thanks for your question. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by aolszowka** [comment]
Just to make it clear: You are saying that the place to get information about format produced, marketed, and serviced by Microsoft is the Community?

**Comment by aaronfranke** [comment]
Has anyone reported this to Visual Studio or MSBuild? Ideally those tools should interpret ANSI/UTF-8 files as UTF-8 by default since the encoding of all ANSI values is the same in UTF-8.
