### ISSUE TITLE
CA1707 is firing for discard _ parameter 

### ISSUE THREAD

**Issue by alandraper** [MicrosoftDocs/visualstudio-docs#4079]
CA1707 is triggered when the underscore indicates a discard parameter. 
https://docs.microsoft.com/en-us/dotnet/csharp/discards

The following causes CA1707 to fire:

`public void DoNothing(string _) {
 }`

**Comment by msebolt** [comment]
@alandraper  Thank you for the feedback.

Unfortunately this a bug and needs to be submitted under **Report a Problem** in the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html).  Please move the issue there to start a dialog with the product team.

@gewarren FYI on `CA1707`

**Comment by gewarren** [comment]
This looks like it's already been reported on the roslyn-analyzers repo: https://github.com/dotnet/roslyn-analyzers/issues/2440.
