### ISSUE TITLE
JavaScript Console window removed from Visual Studio 2019

### ISSUE THREAD

**Issue by sveinfid** [MicrosoftDocs/visualstudio-docs#4084]
The JavaScript Console window has been removed from Visual Studio 2019. The docs for Visual Studio 2019 should be updated to reflect the fact that this feature is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dd84513-cff5-84b5-40fa-4db1399fddcb
* Version Independent ID: d677568a-4b8d-c45d-a4a8-ab6309bb95d1
* Content: [JavaScript Console commands - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/javascript-console-commands?view=vs-2019)
* Content Source: [docs/debugger/javascript-console-commands.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/javascript-console-commands.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@sveinfid Thank you for the feedback, assigning to the author for review.

**Comment by Mikejo5000** [comment]
Thanks! I'll get those removed from VS 2019 docs.
