### ISSUE TITLE
Visualstudio Benefits - Linkedin 1 month activation code

### ISSUE THREAD

**Issue by pyaephyonaung** [MicrosoftDocs/visualstudio-docs#4085]
Hi Admin
Linkedin Subscription 1 month activate Code does not work in visualstudio Benefits
Please Help me

**Comment by msebolt** [comment]
@pyaephyonaung Thank you for contacting us, we're sorry you're having difficulties.  

Please escalate this through [Visual Studio support](https://visualstudio.microsoft.com/subscriptions/support/) where they can access your account information.

**Comment by TerryGLee** [comment]
@evanwindom FYI

**Comment by evanwindom** [comment]
@TerryGLee - Thanks!

@pyaephyonaung - Can you describe the problem you're seeing?  Is it occurring on the My Benefits page of my.visualstudio.com, or on the LinkedIn site?

**Comment by evanwindom** [comment]
@pyaephyonaung - As we haven't heard from you, I'm going to assume you've been able to get your issue resolved.  If that's not the case, please let us know. 

@TerryGLee - Please close.

**Comment by TerryGLee** [comment]
Closing this per request from @evanwindom
