### ISSUE TITLE
CodeLens stale information

### ISSUE THREAD

**Issue by tamlin-mike** [MicrosoftDocs/visualstudio-docs#4086]
find-code-changes-and-other-history-with-codelens.md states
"CodeLens indicators are not available in Visual Studio Community edition."

As of at least VS2019.3 (and .2 IIRC, but might be as early as the first VS2019), this is not the case. CodeLens is most certainly, to at least some extent, available in Community.

Recommendations:
- Fix the documentation. As it doesn't reflect well on Microsoft to spread erroneous information, perhaps expidite a push to docs.microsoft.com as that should be pretty quick and painless.
- Enact policies and safeguards to reduce (with the goal of eliminating) SNAFU's like this in the future. This would have been an entirely avoidable error if the PM(s) reponsible had a checklist where one point read something like "Before release, make _sure_ any and all product documentation is updated to match the shipping product".

For the second bullet point, that part might need to be escalated up the hierarchy to the VS "product owner", to make sure all concerned are on the same page, but it should be pretty non-controversial to contact a few select PM's within the VS umbrella to let them start the process before the slow gears of the corporation grinding has acted.

**Comment by msebolt** [comment]
@tamlin-mike  Thank you for the feedback, assigning this to the author for review.

**Comment by tamlin-mike** [comment]
@msebolt Thanks.

> That's not how Microsoft works. ;)

That is obvious. I would hope it's equally obvious that's why I suggested adding such a quality-improving policy.

**Comment by tamlin-mike** [comment]
@gewarren It would seem this was a misunderstanding, based in part on multiple functions embedded in one visible feature and name (**CodeLens**). The _references_ functionality of CodeLens is included in VS2019 Community, but indeed the _source control_ part is not.

Maybe it could benefit someone else in the future if the _source control_ part was made e.g. boldface?
