### ISSUE TITLE
Password in runsettings: Bad practice

### ISSUE THREAD

**Issue by thomasgalliker** [MicrosoftDocs/visualstudio-docs#4087]
TestRunParameters contains an example where username/password is used in a runsettings file. I know, most people know that this is very bad but you also have to take into account, that many people will copy the content from your documentations and use it in production software. If you like it or not... it's a fact :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@thomasgalliker Thank you for the feedback.

The documentation has been updated and is under review.
