### ISSUE TITLE
How to change default behaviour

### ISSUE THREAD

**Issue by mohed** [MicrosoftDocs/visualstudio-docs#4088]
Hi,
the post states that "In addition, when you open a solution, the default behavior is to open the solution in a new workspace and close the current workspace (if necessary). ". How do I change this default behaviour to open a new solution without closing the old ones?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6c338d-6f88-ff4d-9ba9-b6c5be0559ab
* Version Independent ID: f95c3515-48e2-1d4d-90f5-54288f672ac4
* Content: [How to: Open multiple solutions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-gb/visualstudio/mac/open-multiple-solutions?view=vsmac-2019#feedback)
* Content Source: [mac/open-multiple-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/open-multiple-solutions.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by msebolt** [comment]
@mohed  Thank you for the question.

This is currently a [requested feature](https://developercommunity.visualstudio.com/idea/508939/add-a-preference-to-not-close-solution-by-default.html) and an active issue for the product team. 

Please vote or comment there to increase if you'd like to increase its visibility and priority.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
