### ISSUE TITLE
lack of explanation! !

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/visualstudio-docs#4090]
Rough translation:

> How can I log in from step 5-7 to step 5-8?
> Please write the procedure.
> If you can't log in to the system, you won't understand even after reading Step 5-8!

@DoNgocLinh2010 commented on [Thu Oct 10 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1856)

手順5-7 から手順5-8まで、どうやってログインできますか？
手順を書いてください。
システムにログインできないと、手順５－８を読んでも理解できないです！

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4286e07a-6d43-8800-fd06-be7f8ad21d20
* Version Independent ID: e6b188d8-adc0-cb16-cffa-63bfe2d3ecd4
* Content: [Visual Studio での Django 学習チュートリアル、手順 5、認証](https://docs.microsoft.com/ja-jp/visualstudio/python/learn-django-in-visual-studio-step-05-django-authentication?view=vs-2019#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-05-django-authentication.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/python/learn-django-in-visual-studio-step-05-django-authentication.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

---

@srvbpigh commented on [Thu Oct 10 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1856#issuecomment-540352854)

Hello, @DoNgocLinh2010
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue. Thanks!

**Comment by JoshuaPartlow** [comment]
Hi @lichasu, did you create a super user (admin) account in step 5-1? I believe you should be able to use the credentials you specified there to login. Is that not working for you?

**Comment by DoNgocLinh2010** [comment]
Oh Sorry, i saw that!
Thank you

**Comment by JoshuaPartlow** [comment]
No problem. Closing the issue now because it sounds like all is ok. If that is incorrect, please reopen.
