### ISSUE TITLE
add instructions how to check the VS Version after step 1 and before step 2

### ISSUE THREAD

**Issue by lichasu** [MicrosoftDocs/visualstudio-docs#4091]
@aisbergde commented on [Thu Oct 10 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/68)

it looks like the download links are dynamically generated. So it can happen that a user downloads the wrong installer for the wrong version. Please add some instruction how a user can check the version of the installer. Executing it will not display the version but startes to download something. I suggest to add some instruction how to check the product version of the installer (properties of the file) and to provide a list wich product version belongs to which Visual Studio Version.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Erstellen einer Offlineinstallation - Visual Studio](https://docs.microsoft.com/de-de/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

---

@srvbpigh commented on [Thu Oct 10 2019](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/68#issuecomment-540434818)

Hello, @aisbergde
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hi team, please check this issue.

Thanks!

**Comment by msebolt** [comment]
@aisbergde Assigning this to the author for review.

Perhaps adding a link/note for [previous versions](https://visualstudio.microsoft.com/vs/older-downloads/)?

**Comment by aisbergde** [comment]
The question is, how to check the version of the downloaded installer. Instruction could be as I described in my comment. The question is not, how to load another version, but how to avoid the wrong usage of the wrong version. This happened to me: I prepared the setup, I executed the setup and only at this point I was able to see that the setup was prepared with a wrong version.

**Comment by TerryGLee** [comment]
@aisbergde We've added the information that you've requested. The _en-us_ page should be updated this afternoon. Thanks for helping us improve the documentation!
