### ISSUE TITLE
S is not declared

### ISSUE THREAD

**Issue by lopezroberto** [MicrosoftDocs/visualstudio-docs#4095]
Last line produce error CS0246: The type or namespace name 'S' could not be found.

static S mylock = new S();

All examples seem to have the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca39bde1-9872-c65b-5159-11427f3c8bb9
* Version Independent ID: c3e915dd-9c09-f7c6-8ad6-82dbda6fdac7
* Content: [Debug a parallel application - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-a-parallel-application?view=vs-2019#c-sample)
* Content Source: [docs/debugger/walkthrough-debugging-a-parallel-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-debugging-a-parallel-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@lopezroberto Thank you for the feedback.

What version of Visual Studio and type of project are you using?  Can you double-check the `class S` at the top?

The sample seems to work for me using Visual Studio 2019 and the default C# console project.

**Comment by lopezroberto** [comment]
I apologize, beginners mistake.

**Comment by WilliamAntonRohm** [comment]
We're all beginners somewhere!

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
