### ISSUE TITLE
Version element

### ISSUE THREAD

**Issue by markthesharknz** [MicrosoftDocs/visualstudio-docs#4097]
Please explain the attributes of the Version element better.  Do I need both Min and Max?  Is it correct that the name is the actual filename of the dll?  Can I include portions of the pathname?  Using "/" or "\" for separators?

I'm having trouble making a natvis for QHostAddress that varies depending if it is Qt5.6 or 5.12.  Adding a Version causes my visualiser to be ignored.  Nothing helpful when I set Tools &gt; Options &gt; Debugging &gt; Output Window &gt;Natvis diagnostic messages = Verbose.  VS2019 16.3.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#feedback)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by markthesharknz** [comment]
Using slash or backslash for separators?

**Comment by Mikejo5000** [comment]
@markthesharknz I'll ask about this

**Comment by Mikejo5000** [comment]
From the dev team:
- You don't need both Min and Max, they are optional. No wildcards allowed in versions.
- Name should be filename + extension (i.e. 'foo.dll', 'hello.exe'), no path names allowed

**Comment by Mikejo5000** [comment]
Updating doc to clarify.
