### ISSUE TITLE
More details needed in "add editor support for other languages".

### ISSUE THREAD

**Issue by watkinsmatthewp** [MicrosoftDocs/visualstudio-docs#410]
It would be helpful to give a bit more details on this. Maybe a screenshot showing the completed folder structure where each file was placed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* [Content - https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)

**Comment by gewarren** [comment]
@watkinsmatthewp Thanks for the suggestion. I've added it to our backlog.

**Comment by pbrubaker** [comment]
Seconded.  I'm attempting to add language support for the Intel SPMD Compiler to VS now that I've added it to Code.  I've tried following along with these docs and I'm not making any progress.

**Comment by gewarren** [comment]
@watkinsmatthewp Unfortunately we don't currently have the resources to address this issue, based on its priority. If you did manage to get editor support working, feel free to submit a doc edit yourself (the Edit button is in the upper right-hand corner of each docs page).
