### ISSUE TITLE
Learn how  to use vs to code the unity game.

### ISSUE THREAD

**Issue by AlexandAdmire** [MicrosoftDocs/visualstudio-docs#4102]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73ad57fa-5862-e7c9-fb0c-99298e461bfd
* Version Independent ID: 2e6eb5e8-de91-6515-76f4-69922152db43
* Content: [Visual Studio Tools for Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-studio-tools-for-unity?view=vs-2019)
* Content Source: [docs/cross-platform/visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/visual-studio-tools-for-unity.md)
* Product: **visual-studio-windows**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by therealjohn** [comment]
@AlexandAdmire It looks like your feedback didn't come through. Could you share your feedback in a comment here?

**Comment by msebolt** [comment]
Closing the issue now.

For more information, see [Build Unity Games with Visual Studio](https://visualstudio.microsoft.com/vs/unity-tools/).
