### ISSUE TITLE
Needed Assembly Reference Not Noted

### ISSUE THREAD

**Issue by morbius1st** [MicrosoftDocs/visualstudio-docs#4103]
Microsoft.VisualStudio.Shell.Framework reference must also be added to the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb4ce0ea-fd74-c3f1-5154-00db7cacab01
* Version Independent ID: 110c664a-cf94-0b5b-4052-3c96c5816452
* Content: [Access the DTE Object from an editor extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-accessing-the-dte-object-from-an-editor-extension?view=vs-2019#feedback)
* Content Source: [docs/extensibility/walkthrough-accessing-the-dte-object-from-an-editor-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-accessing-the-dte-object-from-an-editor-extension.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@morbius1st Thank you for the feedback, assigning this to the author to review.

**Comment by PoulChapman** [comment]
Thank you for the feedback. We've got an update coming for this issue shortly.
