### ISSUE TITLE
No Code Analysis tab

### ISSUE THREAD

**Issue by bruno-brant** [MicrosoftDocs/visualstudio-docs#4105]
The documentation for the NuGet package is completely straightforward: go to the code analysis page on project settings, and select install. 

Thing is, I have no Code Analysis tab. I've looked around the web a bit and no answers can be found concerning this. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019#feedback)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@bruno-brant Which version of Visual Studio are you using? It looks like we need to add a note to this topic to indicated that the install functionality is available starting in Visual Studio 2019 version 16.3.
