### ISSUE TITLE
Several links on the right nav bar don't work

### ISSUE THREAD

**Issue by AArnott** [MicrosoftDocs/visualstudio-docs#4108]
Several of the in-document anchor links in the right side navigation panel don't actually jump the document to the expected heading.
(repro at least in Edge Chromium)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e062363-94e9-f776-650f-a0723ab713a3
* Version Independent ID: 9181db12-cbdf-6f95-27f1-833930d6d323
* Content: [Visual Studio Build Tools workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#feedback)
* Content Source: [docs/install/workload-component-id-vs-build-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-build-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gewarren** [comment]
@AArnott Thanks for letting us know!

FYI Terry, I asked about this on Docs Support channel.

**Comment by DuncanmaMSFT** [comment]
Hey folks, this has been resolved. Thanks for reporting it @AArnott (FYI @gewarren )
