### ISSUE TITLE
For newer versions of .NET use nameof for argument names

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4110]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/visualstudio-docs.cs-cz/issues/11
The user i making a suggestion to the original documentation:

@OldrichDlouhy commented 5 hours ago — with docs.microsoft.com
For new versions of .NET, the better practice is to use nameof(parameter) instead of "parameter" to ensure parameter name stays correct in case of refactoring.

Example:
throw new ArgumentException(nameof(person));

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a80979f5-bdc4-f5c8-9adf-fea83bafaa7e
* Version Independent ID: a28c47de-cf33-0aff-cff2-e3da9c709623
* Content: [CA1062: Validate arguments of public methods - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1062-validate-arguments-of-public-methods?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1062-validate-arguments-of-public-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1062-validate-arguments-of-public-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@OldrichDlouhy  Thank you for the feedback, assigning this to the author for review.

**Comment by gewarren** [comment]
@OldrichDlouhy thank you for pointing this out, I'm fixing it.
