### ISSUE TITLE
CTest Test Explorer Support

### ISSUE THREAD

**Issue by danewalton** [MicrosoftDocs/visualstudio-docs#4113]
On this page here:
https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2019
it says that CTest support in Test Explorer is not available.
However on this page I'm writing feedback for it says that it is? Can someone confirm which it is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3f12b8-8048-3c19-8582-2ab35cbda74e
* Version Independent ID: 860805e8-915b-1c76-b6d3-4addc07da1a0
* Content: [How to use CTest for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-ctest-for-cpp?view=vs-2019#feedback)
* Content Source: [docs/test/how-to-use-ctest-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-ctest-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by msebolt** [comment]
@danewalton Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@kendrahavens Kendra, can you confirm support for CTest in Test Explorer?

**Comment by kendrahavens** [comment]
@nickuhlenhuth @AugP Could you answer? Thank you!
