### ISSUE TITLE
Need update image to ASP.NET Core 3

### ISSUE THREAD

**Issue by donhuvy** [MicrosoftDocs/visualstudio-docs#4118]
Need update image to ASP.NET Core 3 with .NET Core 3

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2019)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@donhuvy Thanks for letting us know; we'll get this updated.

**Comment by TerryGLee** [comment]
@donhuvy The page has been updated; thanks for your help in improving our documentation!
