### ISSUE TITLE
Build fails on this.ServiceProvider.GetService(typeof(IMenuCommandService) as OleMenuCommandService

### ISSUE THREAD

**Issue by gregdegruy** [MicrosoftDocs/visualstudio-docs#4122]
On the Instantiate the tool window and toolbar step, getting an error for this line of code and unable to Build.

`var mcs = this.ServiceProvider.GetService(typeof(IMenuCommandService)) as OleMenuCommandService;`

> Error	CS0411	The type arguments for method 'ServiceExtensions.GetService<TService, TInterface>(IServiceProvider, bool)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

Tried more explicit casting and this did not work either `OleMenuCommandService mcs = this.ServiceProvider.GetService(typeof(IServiceContainer)) as OleMenuCommandService;`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 554db2bb-c0c2-d694-be77-44cb0fd311f8
* Version Independent ID: e7a691ea-7540-f6c4-46e4-66abdbd07c37
* Content: [Adding a Tool Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-tool-window?view=vs-2019#add-a-mediaplayer-property-to-firsttoolwindowcontrol)
* Content Source: [docs/extensibility/adding-a-tool-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-tool-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by madskristensen** [comment]
The second line is wrong: `this.ServiceProvider.GetService(typeof(IServiceContainer)) as OleMenuCommandService`. An `IServiceContainer` cannot be cast to an `OleMenuCommandService`.

**Comment by gregdegruy** [comment]
Good catch. What's the correct implementation of this line`var mcs = this.ServiceProvider.GetService(typeof(IMenuCommandService)) as OleMenuCommandService;` , should I used this `OleMenuCommandService commandService = await package.GetServiceAsync(typeof(IMenuCommandService)) as OleMenuCommandService;` to resolve Error CS0411?

**Comment by Asugakoisi** [comment]
I met the same error, but I could stop it by using this code.
```csharp
var mcs = this.package.GetService<IMenuCommandService, OleMenuCommandService>();
```

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

**Comment by Merdin** [comment]
@leslierichardson95 did anything change yet? The code still doesn't work for me and the docs still show this line of code.
