### ISSUE TITLE
From command line - use /noscale switch

### ISSUE THREAD

**Issue by alansingfield** [MicrosoftDocs/visualstudio-docs#4123]
Devenv.exe takes /noscale as a command-line parameter to run in 100% scaling mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2019)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@OliaG Should I add this info to the docs page?

**Comment by OliaG** [comment]
@Tanya-Solyanik @merriemcgaw have we tried/tested  /noscale command for CLI to run in 100% scaling mode?

**Comment by merriemcgaw** [comment]
We use that from the Gold Bar to restart VS in 100% scaling mode. I think it would be great to doc it for people that would rather launch devenv.exe from the command line.

**Comment by TerryGLee** [comment]
@alansingfield We've added a Tip note to the [Disable DPI-awareness in Visual Studio](https://docs.microsoft.com/visualstudio/designers/disable-dpi-awareness) page that includes your suggested addition to content. Our thanks to you for helping us improve the documentation!

**Comment by alansingfield** [comment]
Thank you!
