### ISSUE TITLE
SetThreadDescription isn't backwards compatible

### ISSUE THREAD

**Issue by OfekShilon** [MicrosoftDocs/visualstudio-docs#4124]
This [doc](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-set-a-thread-name-in-native-code?view=vs-2017) doesn't mention OS version support, and even explicitly says:

> When post-mortem debugging a crash dump file, thread names are only visible if the crash was created on Windows 10 version 1607, Windows Server 2016 or later versions of Windows.

This is misleading. In pre win-10 or server-2016 versions _an application using SetThreadDescription cannot run_, and would crash at startup time for not being able to locate this entry point.

**Comment by msebolt** [comment]
@OfekShilon Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@OkefShilon Thanks! I'll update the doc.
