### ISSUE TITLE
How to run or generate code metrics on linux?

### ISSUE THREAD

**Issue by abhall724** [MicrosoftDocs/visualstudio-docs#4125]
Is this capable of running on Linux for the command line metrics?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c654586-8571-cfe1-1ee1-3adaf79e2dcf
* Version Independent ID: 334b3914-dbcd-3ece-26b3-fab7c766a377
* Content: [Generate code metrics from the IDE or command line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2019)
* Content Source: [docs/code-quality/how-to-generate-code-metrics-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-generate-code-metrics-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@abhall724 Thank you for the question, unfortunately this feature is not yet supported.

Please refer to the [cross platform docs](https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/cross-platform.md) for further information.

Or consider adding this as a feature request to the [rolyn repo issues](https://github.com/dotnet/roslyn/issues).  There you'll get a direct response from the product team.
