### ISSUE TITLE
Many "Microsoft.NET.Sdk" related properties are missing

### ISSUE THREAD

**Issue by robertmuehsig** [MicrosoftDocs/visualstudio-docs#4126]
From the new "SDK-style" format many options are not really documented. Maybe this is the wrong page, but I couldn't find the right page.

Small example: TargetFramework and AppendTargetFrameworkToOutputPath are not documented here.

    &lt;Project Sdk="Microsoft.NET.Sdk"&gt;
      &lt;PropertyGroup&gt;
        &lt;ProjectGuid&gt;{A335E763-3E79-4BF4-907E-8165EDEF1F17}&lt;/ProjectGuid&gt;
        &lt;TargetFramework&gt;net472&lt;/TargetFramework&gt;
        &lt;AssemblyTitle&gt;OneOffixx.CoreDocumentFunctions&lt;/AssemblyTitle&gt;
        &lt;Product&gt;OneOffixx.CoreDocumentFunctions&lt;/Product&gt;
        &lt;Copyright&gt;Copyright ©  2019&lt;/Copyright&gt;
        &lt;OutputPath&gt;bin\$(Configuration)\&lt;/OutputPath&gt;
        &lt;AppendTargetFrameworkToOutputPath&gt;false&lt;/AppendTargetFrameworkToOutputPath&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019#feedback)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@robertmuehsig Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
We are capturing this information in #2016 instead.
