### ISSUE TITLE
There should be an example

### ISSUE THREAD

**Issue by jazzdelightsme** [MicrosoftDocs/visualstudio-docs#4127]
There should be example code that would trigger the error, and then show how to fix the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e6579c-df50-045d-b380-5830e0a5169c
* Version Independent ID: 2b1031df-8407-c67b-fff0-beba66e734b0
* Content: [C26481 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26481?view=vs-2019)
* Content Source: [docs/code-quality/C26481.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26481.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by msebolt** [comment]
@jazzdelightsme Thank you for the feedback, assigning this to the author for review.

**Comment by corob-msft** [comment]
It's trivial to generate this error. Basically, anything that does arithmetic on a raw pointer, including increments, decrements, or invoking it using array syntax, will produce the error.

```cpp
constexpr wchar_t const* one_step_beyond(wchar_t const* const input, size_t const len) noexcept
{
    if (input && len)
    {
        return (input + 1);  // C26481
    }
    return input;
}
```

Likewise, it shouldn't be difficult for people familiar with the use of various flavors of `span` to change the code to use one. 

Teaching people how to use `span` (or any other GSL construct, for that matter) seems to be outside the scope of the code analysis error documentation, so I'm going to close this issue. That's not to say we never give examples and show how to fix them; it's more a function of our current relative priorities and resourcing. So, if you're reading this and happen to feel ambitious, you can submit a PR.

**Comment by jazzdelightsme** [comment]
>  it shouldn't be difficult for people familiar with the use of various flavors of span to change the code to use one.

As a developer, the VC++ error documentation has been a huge help for me in the past--having a code example for **this specific error that I'm hitting** is tremendously helpful for people who are *not* so familiar with stuff. And I imagine that for the audience of "people looking at error documentation", the number of people in the "are not as familiar" category is much, much larger than the number of people in the "I am already familiar with this" category.

I hope priorities will one day again include good error documentation.
