### ISSUE TITLE
Windows Presentation Foundation?

### ISSUE THREAD

**Issue by k-14** [MicrosoftDocs/visualstudio-docs#4130]
Page states, "Windows Presentation Foundation-You can open this project in Visual Studio 2017, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1." Does that mean that you can not open this project in VS 2019?
Also the page states that R Tools for Visual Studio is not supported in VS 2019. Is that currently true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3315d1-e6d3-e86d-9cce-1ff9ce0fc482
* Version Independent ID: ae3fd143-bf0b-4cfe-bcad-557eb41fdc2c
* Content: [Port, migrate, and upgrade projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2019#feedback)
* Content Source: [docs/porting/port-migrate-and-upgrade-visual-studio-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/porting/port-migrate-and-upgrade-visual-studio-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@k-14  Thank you for the questions.

WPF projects can be opened in Visual Studio 2019, assigning this to the author for review.

As for R Tools, it has been discontinued in Visual Studio 2019.  Instead users are encouraged to use R in Azure Notebooks, see https://github.com/MicrosoftDocs/visualstudio-docs/issues/2379.

**Comment by TerryGLee** [comment]
@k-14 We've updated the Windows Presentation Foundation information in the [Project migration and upgrade reference for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?view=vs-2019) page; the updates should go live at 4:00pm Pacific Daylight Time (PDT). Thanks for helping us improve the documentation!
