### ISSUE TITLE
Depracation in FxCop Analyzers

### ISSUE THREAD

**Issue by Uzivatel919** [MicrosoftDocs/visualstudio-docs#4131]
Regard https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status?view=vs-2019#deprecated-rules this rule is discontinued.

Here is not any mention on this but explanation is needed instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 973fb42e-35fc-1bfc-1889-d62558074ff6
* Version Independent ID: 1448ad56-d238-b24a-c356-cc6d31c306ec
* Content: [CA1026: Default parameters should not be used - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1026-default-parameters-should-not-be-used?view=vs-2019)
* Content Source: [docs/code-quality/ca1026-default-parameters-should-not-be-used.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1026-default-parameters-should-not-be-used.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@uzivatel919 Thanks for pointing this out. Ideally we would add a deprecation notice to each deprecated rule.

@eddynaka Is that something you'd be interested in helping out with? You can find the list of deprecated rules here: https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status?view=vs-2019#deprecated-rules

**Comment by eddynaka** [comment]
@gewarren what tag should i add to mark as deprecated? Do you have an example? Thanks!

**Comment by gewarren** [comment]
> @gewarren what tag should i add to mark as deprecated? Do you have an example? Thanks!

I added an example in this PR: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5631

**Comment by eddynaka** [comment]
@gewarren thanks for the example. I just created a PR to update the other files as well:
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/5635
