### ISSUE TITLE
Something to add to this page

### ISSUE THREAD

**Issue by dtdono0** [MicrosoftDocs/visualstudio-docs#4132]
Regarding 'The debugger cannot connect to the remote computer'

I was attempting to attach the VS debugger to my Web API site hosted on my local IIS and was still getting this error even with a matching url.  After reading about the part about Visual Studio being 32-bit, I changed the App Pool option for 'Enable 32-bit applications' from false to true, restarted IIS, and now the VS debugger works against the local IIS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b3da70-ab86-495d-abfe-384f369660fe
* Version Independent ID: 2456d73a-68bd-cc6b-bff0-e7666e53f404
* Content: [Error: Unable to Start Debugging on the Web Server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-unable-to-start-debugging-on-the-web-server?view=vs-2019#feedback)
* Content Source: [docs/debugger/error-unable-to-start-debugging-on-the-web-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-unable-to-start-debugging-on-the-web-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@dtdono0 That's good info! I will plan to update the doc.
