### ISSUE TITLE
Update documentation to mention that it CA1001 now handles IAsyncDisposable

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#4137]
Starting FxCopAnalyzers 3.x, this rule will respect types implementing IAsyncDisposable as disposable types. See https://github.com/dotnet/roslyn-analyzers/pull/2916 for details. The documentation in this page should be updated accordingly once we release FxCopAnalyzers 3.0.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c11c2ae2-fde5-91d4-9fd9-b949c8527ede
* Version Independent ID: 6386b34b-5717-55b6-bef0-3cc979f33f0c
* Content: [CA1001: Types that own disposable fields should be disposable - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1001-types-that-own-disposable-fields-should-be-disposable?view=vs-2019)
* Content Source: [docs/code-quality/ca1001-types-that-own-disposable-fields-should-be-disposable.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1001-types-that-own-disposable-fields-should-be-disposable.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Mikejo5000** [comment]
Updating doc. @mavasani Is "Starting in FxCop analyzers 3.x,..." OKI / correct, or is 3.x a placeholder for the actual version?
