### ISSUE TITLE
Macros in PreBuildEvent/PostBuildEvent don't work with SDK-style projects

### ISSUE THREAD

**Issue by mjrousos** [MicrosoftDocs/visualstudio-docs#4138]
As explained in [other issues](https://github.com/dotnet/sdk/issues/677#issuecomment-280164111), macro properties like $(ProjectDir) don't work in PreBuildEvent and PostBuildEvent properties when using SDK-style projects. Instead, users should create new targets (using the 'exec' command) that run before or after the PreBuildEvent and PostBuildEvent targets.

Visual Studio has [already been updated](https://github.com/dotnet/project-system/issues/1569#issuecomment-360951567) so that any pre/post build commands entered through the project properties UI will create new targets instead of using PreBuildEvent/PostBuildEvent directly. We should add a note to the docs, though, explaining this so that users migrating old csproj file to the new SDK-style format know that they will need to change PreBuildEvent and PostBuildEvent usage.

Other issues related to this problem: https://github.com/dotnet/sdk/issues/1055, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 319cf42a-5391-8a60-c005-cfbb92faf1c8
* Version Independent ID: ef79e00a-e2c9-12ec-6da9-2984c381e7d1
* Content: [Pre-build Event-Post-build Event Command Line Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/pre-build-event-post-build-event-command-line-dialog-box?view=vs-2019)
* Content Source: [docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Thanks. I see you also submitted a related doc issue: https://github.com/dotnet/docs/issues/15248. I will coordinate with the .NET content dev on it.

**Comment by ghogen** [comment]
This is fixed now.
