### ISSUE TITLE
document-level customization -> Excel Workbook or Excel Template project template

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/visualstudio-docs#4141]
> To create a document-level customization for Excel, use the Excel Workbook or Excel Template project template in the New Project dialog box.

Are they the same? What is the difference?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2fea0f0-ae7e-34c3-5604-abe01fe9da3a
* Version Independent ID: 8f377dd1-654f-a315-8071-90ccc77b64bb
* Content: [Excel: Get started programming document-level customizations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/getting-started-programming-document-level-customizations-for-excel?view=vs-2019#feedback)
* Content Source: [docs/vsto/getting-started-programming-document-level-customizations-for-excel.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/getting-started-programming-document-level-customizations-for-excel.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by msebolt** [comment]
@Legends  Thank you for the question.

The difference is in the extension and that a template creates a copy of itself each time it's opened, see [this post](https://stackoverflow.com/questions/1396029/excel-change-the-spreadsheets-from-templates-to-workbooks).

Assigning this to the author for review.

**Comment by Legends** [comment]
@msebolt The thing is, when I as a developer am looking for:

>  Excel: Get started programming document-level customizations

It would be nice why I can choose two project template types here:

> To create a document-level customization for Excel, use the Excel Workbook or Excel Template project template

As an improvement I would suggest at least a link to an explanation for each.
Or/And shortly cover the differences.

**Comment by John-Hart** [comment]
@Legends does this document (https://docs.microsoft.com/en-us/visualstudio/vsto/office-project-templates-overview?view=vs-2019) help explain the differences?

**Comment by John-Hart** [comment]
@Legends,  Actually I just realized this doc already has a link to the project template overview that I directed you to:

"For more information about the project templates, see [Office project templates overview](https://docs.microsoft.com/en-us/visualstudio/vsto/office-project-templates-overview?view=vs-2019)."

Does this explain the differences well enough?

**Comment by John-Hart** [comment]
I believe the link to  Office project templates overview does explain the differences.  If it's still not clear please let me know
