### ISSUE TITLE
Walkthrough: Create your first document-level customization for Excel

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/visualstudio-docs#4142]
But it starts with: 

> In the list of project templates, choose an Excel VSTO Add-in project
????????????

> That's why a VSTO add-in is also referred to as a "Application-level customization".

Irritating...
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a12b2f91-753b-4771-85c2-75808137088a
* Version Independent ID: a047d08b-9306-8f1e-2d69-a932417f97b2
* Content: [Create your first document-level customization for Excel - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-document-level-customization-for-excel?view=vs-2019#feedback)
* Content Source: [docs/vsto/walkthrough-creating-your-first-document-level-customization-for-excel.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-creating-your-first-document-level-customization-for-excel.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by msebolt** [comment]
@Legends  Thank you for the feedback.

These steps were provided for an older version of Visual Studio.

Are you not finding the project template or should the steps be updated?

**Comment by Legends** [comment]
Somewhere I have read:

> That's why a **VSTO add-i**n is also referred to as a **"Application-level customization**".

So I wouldn't expect a **VSTO add-in** to be created in the following walkthrough:

> Walkthrough: Create your first **document-level customization** for Excel

**Comment by msebolt** [comment]
Thank you for clarifying, both articles [Create document-level customization](https://docs.microsoft.com/visualstudio/vsto/walkthrough-creating-your-first-document-level-customization-for-excel?view=vs-2019) and [Create VSTO add-in](https://docs.microsoft.com/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel?view=vs-2019) appear to be accomplishing the same task using different methods.

Assigning this to the author for review.

**Comment by John-Hart** [comment]
The two walkthroughs are actually different and they try to describe the differences in the first paragraph:

[Walkthrough: Create document-level customization](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel):

_The features that you create in this kind of solution are **available to the application itself,** regardless of which workbooks are open._

[Walkthrough: Create your first VSTO Add-in for Excel](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel):

_The features that you create in this kind of solution are **available only when a specific workbook** is open_

Thanks for pointing out that we have the wrong template name in the document-level walkthrough

**Comment by John-Hart** [comment]
I've updated both the excel and word document-level walkthroughs.  Thanks again for pointing out the error
