### ISSUE TITLE
Add Container Support --> Kubernetes Missing in Visual Studio

### ISSUE THREAD

**Issue by shanavt** [MicrosoftDocs/visualstudio-docs#4143]
All of a sudden the Kubernetes option is missing from the options. It only shows Service Fabric and Docker Compose. It was working fine and disappeared after I installed VS 2017 for debugging another project. Uninstalling VS2017 and Repairing 2019 are not fixing the issue.

**Comment by msebolt** [comment]
@shanavt  Thank you for the feedback.

Unfortunately this sounds a Visual Studio 2019 bug, that the product team will need to respond to.

Please start a thread with the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) and add a link to this issue.

**Comment by ghogen** [comment]
We'll close this as a doc issue. I also sent a note to let the Container Tools team know about this via internal channels, but do file an issue at Dev Community for accountability.
