### ISSUE TITLE
Error VSP1005: Command line error: Switch /Launch:TestApp.exe is invalid. Aborting.

### ISSUE THREAD

**Issue by yychang** [MicrosoftDocs/visualstudio-docs#4144]
Running VSPerfCmd.exe /Launch:TestApp.exe results in an Error VSP1005. Is this page outdated? (I'm using VS 2019 Enterprise)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d30fa52-6cc6-4809-7a39-ab102261ada5
* Version Independent ID: 7d8f7701-d4a2-b02c-19f3-1473f1061e40
* Content: [Launch - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/launch?view=vs-2019#feedback)
* Content Source: [docs/profiling/launch.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/launch.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@yychang  Thank you for the feedback.

VSPerfCmd's use in sampling has been deprecated, see [this thread](https://developercommunity.visualstudio.com/content/problem/627521/attach-option-missing-from-vsperfcmdexe.html).  

Assigning this to the author for review.

**Comment by Mikejo5000** [comment]
Thanks, we are discussing doc updates that are required related to these changes.

**Comment by Mikejo5000** [comment]
This doc has been removed from the VS 2019 view. The best statement I've seen about the deprecated features are the comments by Allen Denver.
https://developercommunity.visualstudio.com/content/problem/441152/missing-profiler-options-under-debug-visual-studio.html
