### ISSUE TITLE
vcremote currently fails to install on Catalina 10.16 with Xcode 11.1

### ISSUE THREAD

**Issue by pryorm92** [MicrosoftDocs/visualstudio-docs#4147]
I have searched for this issue much of the day and found multiple posts in the past with similar issues that were resolved by having the vcremote developer(s) update the vcremote package. I followed the steps in 

https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios?view=vs-2019

When I reached the step to Install the remote agent for iOS and entered

&gt;sudo npm install -g --unsafe-perm vcremote

I received the following error when it finished running clang on ios-deploy.

&gt;ld: framework not found MobileDevice
&gt;clang: error: linker command failed with exit code 1 (use -v to see invocation)

Does vcremote need another update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32f33eba-a747-c57b-02e3-853d2a8a5c3b
* Version Independent ID: 1ddd9492-f5b1-d0ae-b813-c3838452a17a
* Content: [Install And Configure Tools to Build using iOS - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-and-configure-tools-to-build-using-ios?view=vs-2019)
* Content Source: [docs/cross-platform/install-and-configure-tools-to-build-using-ios.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/install-and-configure-tools-to-build-using-ios.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@pryorm92 

That's entirely possible, though it's also possible it's an Xcode installation problem. I don't know enough to say. The way to get the dev team's attention is by raising an issue on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). You can submit an issue there on the web page. Or you can do it from right within Visual Studio, using the **Help** > **Send feedback** > **Report a problem** menu command. There's more info on reporting problems available in [How to report a problem with the Microsoft C++ toolset](https://docs.microsoft.com/cpp/overview/how-to-report-a-problem-with-the-visual-cpp-toolset?view=vs-2019), but I'd say you've got the gist of what to report already.

I'm closing this, because this board is basically for Visual Studio documentation issues and errors. If it turns out we need to update the instructions in the docs, the developers will let us know.

**Comment by clnorris** [comment]
I followed the documentation and got the same "ld: framework not found MobileDevice" error when trying to install vcremote.  I am on Catalina.  The procedure in the documentation did not work.  Why is this closed?

**Comment by pryorm92** [comment]
> I followed the documentation and got the same "ld: framework not found MobileDevice" error when trying to install vcremote.  I am on Catalina.  The procedure in the documentation did not work.  Why is this closed?

@clnorris
The issue isn't related to the documentation. The problem is that the latest Mac OS X updates have caused the documentation steps to fail. More about the actual issue can be found here: https://github.com/ios-control/ios-deploy/issues/415#issue-510301426

**Comment by clnorris** [comment]
Thanks for the clarification, I am following the other link with interest.  Philosophically I believe the current documentation should reflect the actual procedure including workarounds, not a past/stale procedure.  It would be ok to show different steps for different O.S. revisions, especially if Catalina requires different installation steps for vcremote.  On the link you shared, I notice that some of the people there have methods to install ios-deploy specifically, but I am not seeing a method there that includes vcremote.

The suggestion on that link to modify the vcremote installation to deal with a different ios-deploy installation method was interesting.  I am wondering if any vcremote developers are engaged.

Thanks for the information.  Hopefully this is a temporary problem.

**Comment by pryorm92** [comment]
@clnorris The person who opened that issue provides vcremote support. I am not sure if michelleangela is a developer, but the issue report started from: https://developercommunity.visualstudio.com/content/problem/784499/vcremote-fails-to-install.html

In that link, I have provided a workaround (I accidentally created it as a possible solution) while we wait for Mac and/or Microsoft developers to resolve the issues and get vcremote up and running.
