### ISSUE TITLE
No longer called IntelliTrace (VS2017)

### ISSUE THREAD

**Issue by SvendK** [MicrosoftDocs/visualstudio-docs#4148]
This feature is no longer (visually) called IntelliTrace and no menu item is called that. Look for Diagnostic tools instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 053d151b-27df-20e3-d6c2-172033e56f55
* Version Independent ID: 0bc74663-de4a-d90b-cf46-d84edca8c0f7
* Content: [View events with IntelliTrace - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-using-intellitrace?view=vs-2019#feedback)
* Content Source: [docs/debugger/walkthrough-using-intellitrace.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-using-intellitrace.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
IntelliTrace is VS Enterprise only. Are you using Community? While debugging, I see Debug > IntelliTrace, and Debug > Windows > IntelliTrace Events
