### ISSUE TITLE
Some things about M365 subscription renew

### ISSUE THREAD

**Issue by cazeua** [MicrosoftDocs/visualstudio-docs#4149]
I activated and set up an M365 subscription from a VS Enterprise subscription. Last week, this VS subscription has expired, so the M365 subscription status is changed from "Automatically renew" to "XX days remaining". Now the administrator has assigned me a VS subscription again, but I checked the M365 subscription status, which is still "XX days remaining".
Do I need to re-create an M365 subscription? Can the previous M365 subscription be automatically renewed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [The Microsoft 365 benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365#feedback)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by msebolt** [comment]
@cazeua  Thank you for the feedback, assigning this to the author for review.

In the meantime, please contact [support](https://visualstudio.microsoft.com/subscriptions/support/) where you can speak with someone about your account status.

**Comment by msebolt** [comment]
Including @evanwindom

**Comment by cazeua** [comment]
Any updates?

**Comment by evanwindom** [comment]
I'm checking with the engineering team to determine the best path forward on this issue.  Thanks for your patience.

**Comment by evanwindom** [comment]
@cazeua 
I apologize for the delay.  Here are the answers to your questions:

Do I need to re-create an M365 subscription? 
Yes, you do. You should be able to create a second auto-renewable tenant if you go to the https://my.visualstudio.com/benefits page, click on the M365 tile and then create a new subscription in your dashboard.  The old tenant will expire and eventually be deleted several months from now.  

Can the previous M365 subscription be automatically renewed?
No, it can’t. Once you have a invalid subscription ID associated with it, we can’t update it as renewable.

@TerryGLee - Please close.

**Comment by TerryGLee** [comment]
Closing per request from @evanwindom
