### ISSUE TITLE
Visual Studio - Installation not possible

### ISSUE THREAD

**Issue by PeterBluewin** [MicrosoftDocs/visualstudio-docs#415]
Dear Supportteam,
thanks vor your reply. But it is not possible to install Visual Studio on my computer. The installation process tells me that I do not have an Internet connection, even though I am using an Internet connection. I don't have a connection problem with any pages or other software. After checking the Internet connection during the installation I have seen that different connections from the installer with American companies has been included. However, the installation process is canceled with the message that I do not have an Internet connection and should try again. I have repeated this process four times in total. That's why I'm not using the software now and I'm using another one.

Thank you very much.
Peter

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#report-a-new-problem)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)

**Comment by gewarren** [comment]
@PeterBluewin thanks for contacting us. You are having a product issue, and this page is for issues with the documentation. Please log your issue at [our developer community page](https://developercommunity.visualstudio.com/), and someone from the product team will help you.
