### ISSUE TITLE
How long is the grace period for Visual Studio Activation after your online subscription ends?

### ISSUE THREAD

**Issue by MarkIannucci** [MicrosoftDocs/visualstudio-docs#416]
My company is in the process of extending my MSDN subscription.  Unfortunately, we did not get this done before it expired at the end of the year.  How long will VS continue to work after the subscription ends?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3cb19f7-5f23-bf3a-0977-b8ce116b831b
* Version Independent ID: 0a67d7d2-8ca8-351b-b7b3-d8659c3b8a08
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-unlock-visual-studio)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/how-to-unlock-visual-studio.md)

**Comment by gewarren** [comment]
@MarkIannucci thank you for contacting us. Which version of Visual Studio are you using?

**Comment by MarkIannucci** [comment]
We're using Visual Studio 2017.

**Comment by ghogen** [comment]
This is really a doc feedback channel, so your question is beyond the scope of what we can answer.  If your company renews its subscription, you can continue to use Visual Studio.  Please direct any further questions to [subscriptions support](https://www.visualstudio.com/subscriptions/support/).

**Comment by MarkIannucci** [comment]
I'm working with my colleagues to get the i's dotted and t's crossed on our subscription.  

It would be helpful if the `grace period` (if one exists) were documented so I could light the fire under some people and not show up to work with to find an inactive VS instance on my desk.
