### ISSUE TITLE
Documentation is out of date

### ISSUE THREAD

**Issue by kevingy** [MicrosoftDocs/visualstudio-docs#4166]
The current version of Visual Studio (as of this writing) displays the message "NOTE: This property page has been deprecated and will be removed in a future product release." in the Code Analysis tab.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b48962e-6961-ecd8-9b3f-4e60b97600c5
* Version Independent ID: 4f2b0b4b-d0a0-e4e3-445c-026c66de4c59
* Content: [Suppress Code Analysis violations for Generated Code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code?view=vs-2019)
* Content Source: [docs/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-suppress-code-analysis-warnings-for-generated-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by msebolt** [comment]
@kevingy  Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
Updating doc to mention that the page is deprecated.
For alternatives to using these settings, there's an existing feature request here: https://github.com/dotnet/roslyn/issues/6999.
