### ISSUE TITLE
Link is dead: "Record and play back manual tests"

### ISSUE THREAD

**Issue by Milan1992** [MicrosoftDocs/visualstudio-docs#418]
Hi

The link provided for the text "Record and play back manual tests." is dead: https://docs.microsoft.com/en-us/devops-test-docs/test/record-and-play-back-manual-tests

Is it the good link: https://docs.microsoft.com/en-us/vsts/manual-test/getting-started/record-play-back-manual-tests ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75817b8c-177c-f5f0-2035-e18a9dd21ae3
* Version Independent ID: faa7aa5a-42d6-9695-8692-31e2d13e5bc9
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/use-ui-automation-to-test-your-code#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/use-ui-automation-to-test-your-code.md)

**Comment by gewarren** [comment]
Fixed link in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1318.
