### ISSUE TITLE
incorrect info

### ISSUE THREAD

**Issue by samtse** [MicrosoftDocs/visualstudio-docs#4187]
in the section adding additional  projects to a solution you suggest right-clicking the solution and selecting add n ew or existing project, however, right clicking the solution on osx (which is what this page is about)   does NOT provide this menu item!! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776b3956-55f3-6f3e-640c-d322203a8395
* Version Independent ID: 700a8e79-12a9-d4b9-7984-980e1cb9ed7f
* Content: [Creating new Projects and Solutions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/create-new-projects?view=vsmac-2019#feedback)
* Content Source: [mac/create-new-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/create-new-projects.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by msebolt** [comment]
@samtse  Thank you for the feedback, assigning this to the author for review.

**Comment by heiligerdankgesang** [comment]
@samtse Thank you very much for letting us know.

I've tried this out in Visual Studio for Mac. Here are my results: 

<img width="553" alt="Screen Shot 2019-11-06 at 12 54 12 PM" src="https://user-images.githubusercontent.com/6868428/68324070-ab75b800-0094-11ea-8d93-dcb630dc17b9.png">

It seems to work for me as documented. Could you let me know the exact steps you're taking so I can file a bug or update the documentation to be clearer if needed?

Thanks again!

**Comment by samtse** [comment]
I think it might be that I’m using the community edition ??

Jerome Mayeux

**Comment by heiligerdankgesang** [comment]
@samtse Seems to work in community for me as well - community and enterprise are the same installation and there are a few permissions changed by signing in. This shouldn't be affected by the version.

Do you see the add menu at all? We can continue chatting on GitHub if that works for you or I can get us a Teams meeting so we can chat in "person".

Thanks for the response!

**Comment by msebolt** [comment]
Closing now, comment below if there are any further issues.
