### ISSUE TITLE
Command line test running should be included.

### ISSUE THREAD

**Issue by mikeasage** [MicrosoftDocs/visualstudio-docs#419]
There should be some info here about how to run these unit tests via the command line.  Is it done via MS Test?  vstest.console.exe?  This would help me automate these tests outside of Visual Studio.  Unfortunately, we are not using VSTS version control, and need to automate running these tests at build manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90010c79-fead-60c0-61d4-1c624d4801c0
* Version Independent ID: 42445083-7b63-5640-2129-a5c672f5df88
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-for-store-apps-in-visual-studio)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/run-unit-tests-for-store-apps-in-visual-studio.md)

**Comment by gewarren** [comment]
@pvlakshm can you take this one?

**Comment by gewarren** [comment]
@mikeasage thanks for letting us know. We'll be moving the command line test topics over to docs.microsoft.com, but meanwhile you can reference the MSDN [VSTest.Console.exe topic](https://msdn.microsoft.com/en-CA/library/jj155796.aspx).

**Comment by gewarren** [comment]
We've added an article about running tests from the command line here: https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2017.
