### ISSUE TITLE
Fix "See Also" link typo

### ISSUE THREAD

**Issue by plangevin** [MicrosoftDocs/visualstudio-docs#4190]
Link text to "How to: Install prequisites with a ClickOnce application" should be "How to: Install prerequisites with a ClickOnce application"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73a13e0d-b415-6953-0a25-bbfd3f6a3724
* Version Independent ID: d422e2a7-5595-9274-ace8-38a91fcef21a
* Content: [How to: Include Prerequisites with a ClickOnce Application - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/deployment/how-to-include-prerequisites-with-a-clickonce-application?view=vs-2017&redirectedfrom=MSDN#feedback)
* Content Source: [docs/deployment/how-to-include-prerequisites-with-a-clickonce-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-include-prerequisites-with-a-clickonce-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Fixed in #4192
