### ISSUE TITLE
incorrect syntax under "TRUE in _Success_"

### ISSUE THREAD

**Issue by tyotypic** [MicrosoftDocs/visualstudio-docs#4199]
This document says:
"_Success_(return == TRUE, _Acquires_lock_(*lpCriticalSection))"
and
"_Success_(return != 0, _Acquires_lock_(*lpCriticalSection))"

This results in a "warning C4002: too many arguments for function-like macro invocation '_Success_'"

The correct syntax would be:
"_Success_(return != 0) _Acquires_lock_(*lpCriticalSection)"

... only took me 40 mins to work out. It's useful that MS is annotating their headers, because there's not nearly enough actual documentation to be able to use SAL.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dcefe1b-b2ad-b406-6fbb-526bd9b07750
* Version Independent ID: 2636888b-6093-64ba-b95a-aaa351e1dd6f
* Content: [Best Practices and Examples (SAL) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/best-practices-and-examples-sal?view=vs-2019)
* Content Source: [docs/code-quality/best-practices-and-examples-sal.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/best-practices-and-examples-sal.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by msebolt** [comment]
@tyotypic Thank you for the feedback and for working this out.

The documentation has been updated and is pending review.
