### ISSUE TITLE
Link "Specifying Test Settings for Visual Studio Tests" broken

### ISSUE THREAD

**Issue by mikeasage** [MicrosoftDocs/visualstudio-docs#420]
Clicking on the link under See Also with the text "Specifying Test Settings for Visual Studio Tests" results in a 404 not found error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)

**Comment by gewarren** [comment]
@mikeasage thanks for reporting this. I've removed the broken link.

**Comment by mophdog** [comment]
The broken link is still there.
Instead of removing the link, please can you point it at the right place? I'd like to follow it!

**Comment by gewarren** [comment]
@mophdog This link should be fixed next week with https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1553. Sorry, not sure what happened here before!
