### ISSUE TITLE
Format specifiers for memory locations don't work

### ISSUE THREAD

**Issue by fencepost-error** [MicrosoftDocs/visualstudio-docs#4201]
The memory format specifiers, ",m...", don't work.  Trying to use them, e.g. as "ptr,m" results in an error message "identifier 'm' is undefined".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5c135d-ace1-1f09-041a-13411c054ff3
* Version Independent ID: 083fc572-d877-2216-19a9-326636c1d8e6
* Content: [Format specifiers in the debugger (C++) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2019#feedback)
* Content Source: [docs/debugger/format-specifiers-in-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/format-specifiers-in-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@fencepost-error Thank you for the feedback, assigning this to the author for review.

What version of Visual Studio are you using?  Note the `m` specifiers are bold in the table and might require the latest version of the debugger.

**Comment by fencepost-error** [comment]
VS 2019 Community, all versions over the last six months or so, currently 16.3.5, which was updated a few days ago so I assume the very latest version.

The m specifier has worked since at last VC++ 6 over twenty years ago, so I doubt it's a new feature :-).

**Comment by Mikejo5000** [comment]
Asking about this. The use of bold here for some of the format specifiers seems a little inconsistent.

**Comment by Mikejo5000** [comment]
@fencepost-error Sorry for the slow response. Checking this. I see this error in a C++ app. Docs indicate this is now only supported in interop debugging with C++/CLI (the legacy debugger). What is the scenario you are testing?

**Comment by fencepost-error** [comment]
Various straight C projects, both DLLs called from a test application and standalone EXEs.  I've also reported it as a [bug in VS2019](https://developercommunity.visualstudio.com/content/problem/932735/m-format-specifier-isnt-recognised-in-watch-window.html) and it's under investigation there.

**Comment by Mikejo5000** [comment]
OK, thanks for reporting it!

**Comment by Mikejo5000** [comment]
This appears to be a product issue, if this feature was working previously without the use of Managed Compatibility Mode. Currently, it is only supported when the legacy debugger is enabled.

To clarify the docs, I'm adding this to the section on the 'm' specifiers:

Specifiers in **bold** are supported only for debugging native and C++/CLI code. This requires the legacy debugger, specified using [Managed Compatibility Mode](../debugger/general-debugging-options-dialog-box.md).

**Comment by fencepost-error** [comment]
Two things, firstly the compatibility-mode debugger is supposedly the debugger from before VS 2012 but the ,m specifier worked on every version of VS up until 2019 broke it, and secondly using the compatibility-mode debugger makes no difference, it produces exactly the same error as the standard VS 2019 debugger.

I agree that this is a product issue, but it's an issue in VS 2019, not in which version of which debugger you use.

Can this be reopened, or do I need to file another bug report for exactly the same bug, which hasn't been fixed or resolved?

And yes, I'm just a tiny bit p***d off that after 1 1/2 _years_ this tiny thing still hasn't been fixed.

**Comment by Mikejo5000** [comment]
Sorry about the frustration around this. The Developer Community issue you opened is the right place for a product bug. The issues here are for doc bugs, so I don't see much benefit in keeping it open at this point. However, we can re-open for visibility until I get more information.

**Comment by fencepost-error** [comment]
Ah, OK, so it's being processed as two separate issues, one for the product, one for the documentation.  In that case it's fine to close it, and I'll wait and see what the developer-side response is.
