### ISSUE TITLE
Are the Various GlobalSection Publically Documented?

### ISSUE THREAD

**Issue by aolszowka** [MicrosoftDocs/visualstudio-docs#4202]
The article describes in great detail the `GlobalSection(SolutionConfiguration)` and `GlobalSection(ProjectConfiguration)` which is very helpful. However there are other valid `GlobalSection` that are commonly encountered. Specifically the `GlobalSection(NestedProjects)` which consists of a KeyValuePair in the form `{GUID_OF_PROJECT} = {GUID_OF_SOLUTION_FOLDER}` which instructs Visual Studio on how to properly "nest" projects.

In addition the documentation is unclear if the ordering matters but FWIW Visual Studio will always seem to put this section near the end of the solution file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9177b266-5055-95d6-407f-ca4aad75257a
* Version Independent ID: 4586847b-d990-df3b-4cce-bd9a471eda33
* Content: [Solution (.Sln) file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2019)
* Content Source: [docs/extensibility/internals/solution-dot-sln-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/solution-dot-sln-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@aolszowka  Thank you for the feedback, assigning this to the author for review.

**Comment by aolszowka** [comment]
For anyone that comes across this while the ordering of the NestedProjects global section may not matter, it may uncover bugs which have been silently ignored due to various implementations. See https://github.com/microsoft/msbuild/issues/4835 for a more detailed explanation.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.

**Comment by dcorbin-wintellect** [comment]
A link back to tis issue from where ever the final resolution ended up would save time, rather than user [such as myself] not having to search and figure out where this information ever ended up [presuming ist was covered]....thanks in advance.

**Comment by aolszowka** [comment]
@dcorbin-wintellect I don't believe I ever got a list from them, nor improved documentation. I have since moved on from this employer, but if you describe your situation (or link me to a GitHub Issue or Gist) I would be happy to try and give knowledge transfer/help you troubleshoot your issue.

**Comment by aolszowka** [comment]
@dcorbin-wintellect No worries; I totally understand where you're coming from and why I'm a stickler for not only reporting the underlying bug (with a repro as you saw in the linked issue) but also trying to get the documentation improved. Mostly because someone (usually myself) comes back a number of years later with a similar issue and is looking for some good guidance to resolve an issue.

It sounds like both of my reports helped (Mission Accomplished!) which brings joy to my heart. Have a wonderful day!
