### ISSUE TITLE
Why is is called a "Solution"?

### ISSUE THREAD

**Issue by hwynn** [MicrosoftDocs/visualstudio-docs#4205]
I can't find the answer to this anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@hwynn -- Harrison, please see [this explanation of "Solution"](https://docs.microsoft.com/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019#solutions).  As to its etymology in the evolution of Visual Studio, I'm not sure.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
