### ISSUE TITLE
URL rewrite rules

### ISSUE THREAD

**Issue by JendaPerl** [MicrosoftDocs/visualstudio-docs#4210]
One possible reason for the failure is URL rewrite rules in the web.config and the error message provides no details in such case.
I had &lt;system.webServer&gt;&lt;rewrite&gt; section in web.config to implement automatic redirection from HTTP to HTTPS and it prevented debugging. As I do not really need that on the development machine I moved that setting to the web.Whatever.config files used when publishing and this way things work.
You may want to add this to the list of possible causes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12b3da70-ab86-495d-abfe-384f369660fe
* Version Independent ID: 2456d73a-68bd-cc6b-bff0-e7666e53f404
* Content: [Error: Unable to Start Debugging on the Web Server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-unable-to-start-debugging-on-the-web-server?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.http);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.6.2);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2019)
* Content Source: [docs/debugger/error-unable-to-start-debugging-on-the-web-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-unable-to-start-debugging-on-the-web-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@JendaPerl Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@JendaPerl What was the full error message that you saw? Some of the more detailed messages described in the article mention URL rewrite rules, so it would be helpful to know the more exact message in order to update the doc. Thanks!

**Comment by JendaPerl** [comment]
I'm sorry, I did not notice your response.
I added the section back to the web.config and tried to debug the project. I got a dialog box with title "Microsoft Visual Studio" and text "Unable to start debugging on the web server. Operation not supported. Unknown error: 0x80004005. Click Help for more information."

The Help loads the https://docs.microsoft.com/en-us/visualstudio/debugger/error-unable-to-start-debugging-on-the-web-server page.

I did not find anything related in the Event Viewer, but maybe I just did not know where to look.

**Comment by Mikejo5000** [comment]
Thanks for responding. So, you used the Event Viewer to get details on the error?

**Comment by Mikejo5000** [comment]
Oh, misread that. You tried the Event Viewer, but it didn't help. Looks like I need a new entry for "Operation not supported".

**Comment by JendaPerl** [comment]
Exactly. The "Operation not supported. Unknown error: 0x80004005" was all the error details I could find anywhere. Luckily I remembered the recent addition of the rewrite section in the web.config and tried to remove it and that fixed the problem.
Please add this into the list of possibly causes of the error in the document. :-)

**Comment by Mikejo5000** [comment]
Updating doc with new error message.
