### ISSUE TITLE
About.Cshtml page is missing

### ISSUE THREAD

**Issue by vij9218** [MicrosoftDocs/visualstudio-docs#4211]
I have followed the same procedure as shown above but I don't see any About.CShtml and Content.Cshtml pages. How can I get that pages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2019#feedback)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@vij9218 Thanks for letting us know; I'll investigate and report back.

**Comment by TerryGLee** [comment]
@vij9218 Thanks again for your feedback; with the recent integration of .NET Core 3.0 in to Visual Studio 2019, the About page became obsolete. We've changed the quickstart to use a page that is available in the new version of .NET Core 3.0. Thanks for helping us improve the documentation!
