### ISSUE TITLE
_Lock_level_order_ documentation should say what the order is

### ISSUE THREAD

**Issue by tyotypic** [MicrosoftDocs/visualstudio-docs#4215]
According to the documentation for C26105 (https://docs.microsoft.com/en-us/visualstudio/code-quality/c26105?view=vs-2019), _Lock_level_order_(A,B) means "locks that have level A must be acquired before locks that have level B". Please add this to this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3befc1e4-e459-fb78-f12e-db45a16e9f98
* Version Independent ID: 32f54ed6-6189-4d05-66aa-b0e7dc66680d
* Content: [Annotating Locking Behavior - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/annotating-locking-behavior?view=vs-2019)
* Content Source: [docs/code-quality/annotating-locking-behavior.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/annotating-locking-behavior.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by Mikejo5000** [comment]
Already fixed? Hmm, I see this statement by _Lock_level_order(name1, name2) in this doc:
"Locks that have level name1 must be acquired before locks that have level name2"
which sounds like the same thing.
