### ISSUE TITLE
But how to suppress for Test function names?

### ISSUE THREAD

**Issue by wizofaus** [MicrosoftDocs/visualstudio-docs#4218]
A widely adopted convention for unit test function names is &lt;unit&gt;_&lt;condition&gt;_&lt;expected-outcome&gt;, e.g. Multiply_TwoNegativeNumbers_ShouldReturnPositiveNumber().
This is the ONLY place we want to allow _ in identifiers - but there's no nice way to specify this rule to be excluded for test function names that I can see?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06cee199-3ccc-7575-2c1d-296e2714a16e
* Version Independent ID: 2be241bf-b98a-5088-1e1b-0e39b1384b9a
* Content: [CA1707: Identifiers should not contain underscores - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1707?view=vs-2019)
* Content Source: [docs/code-quality/ca1707.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1707.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@wizofaus Thank you for the feedback.  You're correct, this is a contradiction to [test case naming best practices](https://docs.microsoft.com/dotnet/core/testing/unit-testing-best-practices).

For now you need to keep test cases in a separate project to [suppress the warnings](https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#suppress-violations).

Assigning this to the author for review, including @jpreese.

**Comment by jpreese** [comment]
This has come up a couple times now, quite recently. It would be nice to be able to suppress the warnings for test function names, as it is a very common practice to do so in the scope of tests.

**Comment by StingyJack** [comment]
Its also common practice to not use the same CA rules (or any!) for unit test projects.

**Comment by wizofaus** [comment]
> Its also common practice to not use the same CA rules (or any!) for unit test projects.
For you perhaps. The only exception I want made is for test function names (i.e. for xUnit, those marked [Fact] or [Theory]).  Even helper function names in the test libraries should follow regular conventions.

**Comment by Mikejo5000** [comment]
If the current methods of suppressing warnings described in the docs aren't useful for restricting CA1707 to test functions, this sounds like a feature request to me. Please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2017) page.
