### ISSUE TITLE
Add documentation about DockerComposeBaseFilePath and AdditionalComposeFilePaths properties for dcproj files

### ISSUE THREAD

**Issue by BrunoZell** [MicrosoftDocs/visualstudio-docs#4219]
Currently, the Docker Compose `dcproj` documentation is missing two MSBuild properties added in https://github.com/Microsoft/DockerTools/issues/121#issuecomment-438098500. These are  `<DockerComposeBaseFilePath>` and `<AdditionalComposeFilePaths>` which are quire important when it comes to multiple docker-compose files within the same document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e8ab223-566b-c9bc-ce39-22e23531415a
* Version Independent ID: f58fe488-72a0-98aa-ff60-f1f7585ea107
* Content: [Visual Studio Container Tools Docker Compose build settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019#feedback)
* Content Source: [docs/containers/docker-compose-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/docker-compose-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by msebolt** [comment]
@BrunoZell  Thank you for the feedback, assigning this to the author for review.

**Comment by ghogen** [comment]
This is fixed now.
