### ISSUE TITLE
C1083 Cannot open include file: "Python.h": No such file or directory

### ISSUE THREAD

**Issue by SiqingYu** [MicrosoftDocs/visualstudio-docs#422]
I am following this post: [Creating a C++ extension for Python](https://docs.microsoft.com/en-us/visualstudio/python/cpp-and-python)
I have installed VS2017 on my fresh new Windows10LTSB system, with Desktop development with C++ and Python Development (including Python native development tools) workloads, following [Installing Python support in Visual Studio on Windows](https://docs.microsoft.com/en-us/visualstudio/python/installation)
My Python application worked fine.
I stuck at the _Create the core C++ project_ section for almost a day, I created Empty Project following the post and also tried creating a Python Extension Module template. 
The error is **E1696 cannot open source file "Python.h"**.
I strictly followed the post to set up the project property and tied several times, but it did not work at all.
My Python directory is C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64, which was also my Python application's default environment.
I have not installed the official Python distribution, because [Python environments](https://docs.microsoft.com/en-us/visualstudio/python/python-environments) mentions that VS ignore PYTHONPATH environment variable.

**Comment by kraigb** [comment]
I believe I neglected the step of making sure that the folder containing python.h is set in the project properties under "C/C++ > General > Additional Include Directories". In my test project I have "c:\python36-32\include" there, which is pointing to where Python is installed. (If you installed Anaconda, it might be in something like c:\Anaconda3\include.)

In your case it should be "c:\program file (x86)\Microsoft Visual Studio\Shared\Python36_64\include".

Can you make that change and let me know if it works for you? I'll update the doc accordingly.

**Comment by SiqingYu** [comment]
BTW, in the C++ superfastcode project property, what platform should be set?
I have **Active(Win32)**, **Win32**, **x64** and **All Platforms**.

**Comment by SiqingYu** [comment]
I created a C++ Empty Project, and followed the tutorial.
The Python.h header file was included, but there were other problems:
```
LNK1120	2 unresolved externals
LNK4272	library machine type 'x64' conflicts with target machine type 'X86'
LNK2019	unresolved external symbol __imp__PyFloat_AsDouble referenced in function "struct _object * __cdecl tanh_impl(struct _object *,struct _object *)" (?tanh_impl@@YAPAU_object@@PAU1@0@Z)
LNK2019	unresolved external symbol __imp__PyFloat_FromDouble referenced in function "struct _object * __cdecl tanh_impl(struct _object *,struct _object *)" (?tanh_impl@@YAPAU_object@@PAU1@0@Z)
```

**Comment by SiqingYu** [comment]
I found this post [Creating a C++ extension](https://stackoverflow.com/questions/46289978/creating-a-c-extension-for-python) for Python and retarget the C++ project target platform to x64 in the Solution Property and solved the problem.

**Comment by kraigb** [comment]
You should set the C++ project to match the architecture of your Python installation (32 or 64 bit). The LNK4272 message says as much, that your Python libraries are x64 and you were compiling for x32. That said, I think you do run run into trouble, as your StackOverflow post mentions, if using the setup.py method to compile the DLL, as I believe that route needs you to use x32.

**Comment by kraigb** [comment]
Check the edits I've made to the topic in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1221/files#diff-1519016a518e16173e06254c42482dec. If those changes aren't sufficient, please reopen this issue and provide details.
