### ISSUE TITLE
What happens if verification fails? Is this an assertion?

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#4220]
The documentation and example seem to indirectly suggest that the build will be failed if the hash doesn’t match. But it doesn’t explicitly say that.

From just its name, I assumed that this task would have an output parameter letting you know if the file’s hash was matched. However, it looks like, to do that, I would need to call `GetFileHash` instead and then use a condition to compare.

Please clarify what happens when the hash doesn’t match and provide guidance for how people should conditionally check if a file matches a hash or not and run their own code in response (which sounds like this task but probably isn’t).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ffa6013d-443a-570a-ca70-f3cad50a3b34
* Version Independent ID: d422fed1-420d-bf97-33c4-1842d5861696
* Content: [VerifyFileHash  Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/verifyfilehash-task?view=vs-2019)
* Content Source: [docs/msbuild/verifyfilehash-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/verifyfilehash-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@binki  Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@rainersigwald for input on this.

**Comment by rainersigwald** [comment]
The `VerifyFileHash` will fail if the hash does not match. That's not configurable. However, you can [allow task errors](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-ignore-errors-in-tasks?view=vs-2019) using `ContinueOnError="WarnAndContinue"` and then check `$(MSBuildLastTaskResult)` to guide further decisions.

You can't completely silence a failed task; you may wish to combine `WarnAndContinue` with a demotion of the specific warning to a message, but that doesn't work at the moment due to a bug in MSBuild: microsoft/msbuild#4851.

As a complete example:

```xml
  <PropertyGroup>
    <!-- This doesn't work due to https://github.com/microsoft/msbuild/issues/4851 -->
    <MSBuildWarningsAsMessages>$(MSBuildWarningsAsMessages);MSB3952</MSBuildWarningsAsMessages>
  </PropertyGroup>

  <Target Name="DemoVerifyCheck">
    <VerifyFileHash File="$(MSBuildThisFileFullPath)"
                    Hash="1"
                    ContinueOnError="WarnAndContinue" />

    <PropertyGroup>
      <HashMatched>$(MSBuildLastTaskResult)</HashMatched>
    </PropertyGroup>

    <Message Condition=" '$(HashMatched)' != 'true'"
             Text="The hash didn't match" />

    <Message Condition=" '$(HashMatched)' == 'true'"
             Text="The hash did match" />
  </Target>
```

**Comment by binki** [comment]
Hi @rainersigwald,

I have for now in my use case decided to use `GetFileHash` and use MSBuild conditions to branch logic based on that. Your suggestion of using `ContinueOnError="WarnAndContinue"` and `$(MSBuildLastTaskResult)` is interesting. I might have been able to write more terse code with that. But, I already wrote my two `GetFileHash` calls and the comparison of the resultant values.

I am verifying that file hashes match as a sort of updatedness check. If the hashes don’t match, that is a perfectly acceptable and supported condition for what I am trying to accomplish (I’d actually prefer a file comparison because that would be more correct, but it’s not security-critical, so using hashes is acceptable).

My (way too late) comment on `VerifyFileHash` is that its name could have been chosen to make its behavior more obvious. For example, it could have been named `AssertFileHash`. `VerifyFileHash` sounds like something that would have a boolean output parameter to me ;-).

Anyway, this is an issue filed against the documentation. May the documentation be updated to clearly show that `VerifyFileHash` is an assertion and will fail the build if the hash doesn’t match? And, if the `ContinueOnError="WarnAndContinue"` and `$(MSBuildLastTaskResult)` is actually a recommended usage, adding an example of that would be great too.

Thanks!
