### ISSUE TITLE
The FileHash metadata property is not formally documented

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#4221]
In reading the documentation for the `Items` parameter, it says that the hash is put in a metadata. It doesn’t say what the name of that metadata is. I have to look in the example (or play around with MSBuild directly a lot more) to find that out.

Please update the documentation so that I find this information where I expect to find it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0ec52e4-dbee-c9a1-0a88-04579afbc5f3
* Version Independent ID: 85c53b37-e9ac-222a-93e0-1f62308bc603
* Content: [GetFileHash  Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/getfilehash-task?view=vs-2019)
* Content Source: [docs/msbuild/getfilehash-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/getfilehash-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@binki  Thank you for the feedback.

Unfortunately this cannot be constituted a work item due to maintained consistency across all [msbuild tasks](https://docs.microsoft.com/visualstudio/msbuild/msbuild-tasks?view=vs-2019).

We will continue to work on improving the topics to include more in-depth examples in subsequent iterations of the documentation.

@Mikejo5000

**Comment by binki** [comment]
@msebolt Could you explain how documenting the `FileHash` item metadata would make the documentation inconsistent? Why should I have to read an example to learn what the name of the metadata in the emitted items is? The documentation for the `Items` parameter should clearly state something like “the hash is stored in a metadata property called `FileHash`”.
