### ISSUE TITLE
Show how to set MSBuild properties from within Visual Studio

### ISSUE THREAD

**Issue by BrunoZell** [MicrosoftDocs/visualstudio-docs#4228]
This page very neatly describes how one can use property values to alter the build behavior. However, it uses the msbuild cli to build the project. Since we are in the Visual Studio section of the documentation, I'd like to see how the same behavior is archived from within Visual Studio. For example, when starting a debug session, I want to be see how to set some specific properties. This is especially useful when you maintain different versions of your app, say a demo and a licensed product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f884fc9c-88e5-65d6-c00f-0b8e73b84cb7
* Version Independent ID: 6feedff7-4f94-82fc-d95d-20139dab479e
* Content: [How to: Build the Same Source Files with Different Options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-the-same-source-files-with-different-options?view=vs-2019)
* Content Source: [docs/msbuild/how-to-build-the-same-source-files-with-different-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-build-the-same-source-files-with-different-options.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@BrunoZell  Thank you for the question.

Please see the **Examine the project file** step of [Walkthrough using msbuild](https://docs.microsoft.com/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2019#examine-the-project-file) for instructions on editing these properties from within Visual Studio and comment below if there are any questions or issues.

**Comment by BrunoZell** [comment]
Hm, it seems to me as this article just goes over how to edit the `.csproj` file within Visual Studio. In the article I referred to you can set properties separately for each build.

What I am going for is getting that behaviour, but still starting each separate build/debugging session from within Visual Studio. Does this make sense in any way?

**Comment by rainersigwald** [comment]
@BrunoZell there is no general-purpose UI for setting project properties. Many properties can be manipulated using the project's properties menu (right-click on project, Properties), especially in the `Build` tab.

Those can be specialized by platform or by configuration. As @Mikejo5000 mentioned, the specific example of demo vs. licensed product might be represented by build configurations.

But I'm a bit confused by this

> For example, when starting a debug session, I want to be see how to set some specific properties.

MSBuild properties are relevant while the project is loading and building, but they aren't exposed to the application when it runs under a debugger. Are you interested in setting environment variables for the application that's being debugged?

**Comment by BrunoZell** [comment]
The configuration manager is probably what I was looking for. I just was confused with the difference between project configurations and solution configurations. So this is what I understand, correct me if I am wrong somewhere:

Each project can have its very own configurations, set by the `Configurations`  property in the csproj file, e.g.`<Configurations>Debug;Release;DebugDemo;ReleaseDemo</Configurations>`. On the command line, you then can choose one of those for each build (`-c ReleaseDemo`) which affects the build however specified further in the csproj.

And then there are solution configurations. Each solution configuration is basically just a mapping from each project in the solution to one of their configurations. It's stored in the solution file.

And then, specific for .NET Core, there is `launchSettings.json`, which can specify different profiles too. Visual Studio also picks them up and let's you choose one. It seems this is more of a thing to influence the execution of your program, e.g. to set environment variables and command-line arguments. However, it can influence the build as well. With `"commandName": "Docker"` specified for example, one can do a Docker build. Can we also set MSBuild properties here?
