### ISSUE TITLE
DefineConstants seperator?

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/visualstudio-docs#4230]
The example here `&lt;DefineConstants&gt;DEBUG;TRACE&lt;/DefineConstants&gt;` shows semicolon used as a separator.  When this is done only the first one will display in VS 2019 properties dialog.  If using a comma they both will display.

What is the proper separator?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9555b2e3-0394-0e64-e7a2-4e1adc5e99bf
* Version Independent ID: ed70f624-65ad-556c-25c3-08e00415f6cd
* Content: [MSBuild Conditional Constructs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-conditional-constructs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditional-constructs.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@StevenTCramer Thank you for the question, assigning this to the author for review.

**Comment by ghogen** [comment]
The preferred separator is semicolon, but comma is supported for historical reasons. If it's not showing in Visual Studio, that may be a bug in Visual Studio.

**Comment by ghogen** [comment]
Thanks for the feedback.  I sent the feedback to the Visual Studio engineering team to see if there's an issue there.
