### ISSUE TITLE
inconsistent white space (Visual studio 2019)

### ISSUE THREAD

**Issue by sandeepsubbenaik1985** [MicrosoftDocs/visualstudio-docs#4232]
I updated python settings on my Visual Studio 2019 per the above screenshot but I don't see my issues going away. There is a green zig-zag line on python code with a tooltip as an inconsistent white space. This is how I adjusted my settings Tools&gt;Editor&gt;Python&gt;Tabs&gt;Insert Spaces is checked, and Indenting is checked to Smart. Tab Size: 4 and Indent Size 4.  I am really upset because of these issues I cannot go further with my Object Detection with OpenCV. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67031305-2f97-3aa4-ced1-b66092dd4d41
* Version Independent ID: 37603282-7242-21de-fb56-9f1bbae9dc43
* Content: [Format Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/formatting-python-code?view=vs-2019)
* Content Source: [docs/python/formatting-python-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/formatting-python-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @sandeepsubbenaik1985 - After changing the setting did you apply formatting to the file (Edit > Advanced > Format Document)? Could you also clarify what warning you're getting and what happens when you try to run your code? You might also try Edit > Advanced > View whitespace to see if that helps identify the spacing that's inconsistent.

**Comment by JoshuaPartlow** [comment]
No reply, so closing the issue. Feel free to reopen if this is still a problem.

**Comment by rojas-ja** [comment]
> I updated python settings on my Visual Studio 2019 per the above screenshot but I don't see my issues going away. There is a green zig-zag line on python code with a tooltip as an inconsistent white space. This is how I adjusted my settings Tools>Editor>Python>Tabs>Insert Spaces is checked, and Indenting is checked to Smart. Tab Size: 4 and Indent Size 4. I am really upset because of these issues I cannot go further with my Object Detection with OpenCV.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 67031305-2f97-3aa4-ced1-b66092dd4d41
> * Version Independent ID: 37603282-7242-21de-fb56-9f1bbae9dc43
> * Content: [Format Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/formatting-python-code?view=vs-2019)
> * Content Source: [docs/python/formatting-python-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/formatting-python-code.md)
> * Product: **visual-studio-windows**
> * Technology: **vs-python**
> * GitHub Login: @JoshuaPartlow
> * Microsoft Alias: **joshuapa**

![image](https://user-images.githubusercontent.com/33053777/73717462-b6a9a580-46ce-11ea-9a55-0bd80934f704.png)

**Comment by rojas-ja** [comment]
That's how you render white space in Python... Well at least in a manner that you might be trying to do so?  (This will place a pale gray dot in each space so you can easily see if you are being consistent with your indentation.)

**Comment by gmonkman** [comment]
It might be that your document has a mix of tabs and spaces for indenting. You can choose Edit>Advanced>tabify/untabify selected lines to fix.

If you have a lot of files in this state, e.g. cloned someones repo, then the process can be scripted .. but i'll let you google that one!
