### ISSUE TITLE
Huge jump up from C# Introduction  

### ISSUE THREAD

**Issue by QFzzz** [MicrosoftDocs/visualstudio-docs#4234]
many new functions introduced without any explanation - 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@QFzzz  Thank you for the feedback.

Please provide additional details to help us fix the documentation.

For instance [Convert.ToInt32](https://docs.microsoft.com/en-us/dotnet/api/system.convert.toint32?view=netframework-4.8) can be found in the .NET API and so on.

In general only functions that require further explanation to understand the code functionality are linked, whereas common functions such as WriteLine, etc. are not.

**Comment by msebolt** [comment]
Closing the issue, please comment below if there are any issues.
