### ISSUE TITLE
Cursor in map mode

### ISSUE THREAD

**Issue by montoner0** [MicrosoftDocs/visualstudio-docs#4235]
> In map mode, when you click a location on the scroll bar, the cursor jumps to that location in the file instead of just scrolling up or down a page

That's not quite true, the cursor stays on its place in both modes. At least in 16.3.6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9440cd51-f00a-2a66-c895-0c093c6c883d
* Version Independent ID: 77cf076b-949f-ce9a-882f-7a0c02d268d0
* Content: [Scroll bar map mode and bar mode - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-track-your-code-by-customizing-the-scrollbar?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@montoner0  Thank you for the feedback, assigning this to the author for review.

**Comment by TerryGLee** [comment]
@montoner0 You are right about this, and it's the same behavior in [version 16.5](https://docs.microsoft.com/visualstudio/releases/2019/release-notes-history?view=vs-2019). 

I've amended the text in the [article](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-track-your-code-by-customizing-the-scrollbar?view=vs-2019). 

Thanks for helping us improve the documentation!
