### ISSUE TITLE
AA

### ISSUE THREAD

**Issue by lemanhhung0943437948** [MicrosoftDocs/visualstudio-docs#4237]
AA

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 9dd4d05c-4aa3-0376-f3a1-b0ea0793f482
* Version Independent ID: 7f1ff943-61b0-60e1-9ca3-d4a84bfdb068
* Content: [Install Visual Studio](https://docs.microsoft.com/vi-vn/visualstudio/install/install-visual-studio?view=vs-2019)
* Content Source: [docs/install/install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@lemanhhung0943437948  Thank you for contacting Microsoft Docs.

Please comment below if you have an issue.

**Comment by mhoelzel142** [comment]
Here's an issue: bring back the start page. Lots of people want it back, lots of people absolutely hate the start window, yet Microsoft seems unfazed at this. In fact, the latest visual studio 2019 release broke the only functioning start page extension, which seems to indicate that not only does Microsoft not want to give developers what we want, Microsoft is actively engaging in anti-consumer practices. Why can't you support the legacy start page alongside the current (horrible) "start window" in 2019? Stop hating the people who use your products!
