### ISSUE TITLE
The feedback app cannot log in

### ISSUE THREAD

**Issue by Grand-Poobah** [MicrosoftDocs/visualstudio-docs#4238]
since the feedback app cannot log in and the page to report a problem in visual studio only shows how to do it through VS

I CANNOT REPORT THE PROBLEM !!!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019#feedback)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by msebolt** [comment]
@m-pollack  Thank you for the feedback, we're sorry you're experiencing difficulties.

This issue was recently posted [here](https://developercommunity.visualstudio.com/content/problem/690716/visual-studio-feedback-login-problems.html) in the Visual Studio community.  

Please make sure you are using the latest version of Visual Studio and comment below any further issues.

**Comment by TerryGLee** [comment]
@seaniyer FYI

**Comment by msebolt** [comment]
Closing the issue now, please add any additional comments below.

**Comment by m-pollack** [comment]
updated to 16.3.8 
Running in admin mode
Still broken


Error signing in: '{"stack":"Error: Failed to acquire file lock on U:\\IdentityService\\AadConfigurations\\AadConfiguration.lock\n at Object.<anonymous> (C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\node_modules\\vs-report-problem-bundle\\ReportProblem.asar\\node_modules\\identity-client\\dist\\Utilities.js:252:15)\n at Generator.next (<anonymous>)\n at fulfilled (C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\node_modules\\vs-report-problem-bundle\\ReportProblem.asar\\node_modules\\identity-client\\dist\\Utilities.js:7:58)","message":"Failed to acquire file lock on U:\\IdentityService\\AadConfigurations\\AadConfiguration.lock"}' Let us know
Problem signing in? Please try signing in using Visual Studio.

**Comment by m-pollack** [comment]
After the update I found vs_installer still running in the background even though i closed it
using 25% + of my cpu

**Comment by m-pollack** [comment]
Just wondering if this is part of the same issue?
Happens too often for no apparent reason 

![vsinstellershell](https://user-images.githubusercontent.com/49539220/68626163-f24e1e00-0497-11ea-8d4e-0af67c9cd0c2.JPG)

**Comment by msebolt** [comment]
@Grand-Poobah Sorry for the delay.

This is a currently pending release and is being tracked in the Visual Studio community, see [here](https://developercommunity.visualstudio.com/content/problem/794620/visual-stufdio-feedback-sign-in-fails-for-failed-t.html).
