### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by tndata** [MicrosoftDocs/visualstudio-docs#4243]
I would like a better explanation on why I should use Microsoft Code Analysis 2019? what is the difference with FxCop? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@tndata -- Tore, thanks for your question.  You may find answers here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@jillre -- Jill, please look into this issue.

**Comment by Mikejo5000** [comment]
@tndata I think you would find more information about that here instead of this topic:
https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019#source-code-analysis-versus-legacy-analysis
Also, in general, a legacy tool is in maintenance mode. The new tools would be getting most of the engineering work.

**Comment by Mikejo5000** [comment]
Not a doc bug for the "Install" topic
