### ISSUE TITLE
The namespace name 'SyntaxTree' could not be found

### ISSUE THREAD

**Issue by DanJBower** [MicrosoftDocs/visualstudio-docs#4248]
When pasting this script into a Unity 2019.2.3f1 project, I am getting the error `CS0246: The type or namespace name 'SyntaxTree' could not be found (are you missing a using directive or an assembly reference?)`. I have Visual Studio 2019 installed, along with the Visual Studio Tools for Unity. These tools are enabled both in Unity and Visual Studio. Am I missing a step or an import? What is stopping the code from compiling?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a4fd25-8def-13c4-d35f-e81043b21e4d
* Version Independent ID: 55ceba14-64a8-20a9-73ce-e16f410f1936
* Content: [Customize Project Files Created by VSTU - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/customize-project-files-created-by-vstu?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/customize-project-files-created-by-vstu.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/customize-project-files-created-by-vstu.md)
* Product: **visual-studio-windows**
* Technology: **vs-unity-tools**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by DanJBower** [comment]
@therealjohn I've been having a look at the documentation and I can't find this information anywhere in it. Have I just missed it or is it not in the documentation?

**Comment by therealjohn** [comment]
@DanJBower Sorry for the confusion! It looks like that info is missing from the docs and it's something we need to add!
