### ISSUE TITLE
Shortcut element with dashes is not supported for C# in VS 2019

### ISSUE THREAD

**Issue by zhaparoff** [MicrosoftDocs/visualstudio-docs#4249]
Shortcut section of a document:
https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2019#shortcut-element
says that dash ('-') and underscore ('_') are not supported for C++ language.

But dash is not supported  for C# as well, at least in VS 2019 Pro.
Thus:
`<Shortcut>ensureempty</Shortcut>` and `<Shortcut>ensure_empty</Shortcut>` are working fine, but `<Shortcut>ensure-empty</Shortcut>` does not.

**Comment by ghogen** [comment]
fix should be published live today
