### ISSUE TITLE
Undeclared Identifier 'Textox'

### ISSUE THREAD

**Issue by resun555** [MicrosoftDocs/visualstudio-docs#425]
To the Author, you might have note that 'TextBox control with Stretch property'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e155a58-40dd-c4f9-5089-dabc1870c5a8
* Version Independent ID: e257ebf0-4506-408f-c078-18a35820fe60
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/step-5-add-controls-to-your-form#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/step-5-add-controls-to-your-form.md)

**Comment by gewarren** [comment]
Dupe of #426
