### ISSUE TITLE
How about a video on using VS for Mac to do database app dev

### ISSUE THREAD

**Issue by gregveres** [MicrosoftDocs/visualstudio-docs#4254]
[Enter feedback here]
That was a good introductory video. It would be nice to show how to do a full MVC app or just Web API app that uses a database on the Mac. 

If we are developing on the Mac what are our choices for EF database development?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a4578c-e8e5-77d0-3b87-ac36ba970cdd
* Version Independent ID: 3dcff517-c2cf-8873-11ef-90e3680b2261
* Content: [Getting started with ASP.NET Core in Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tutorial-aspnet-core-vsmac-getting-started?view=vsmac-2019&MC=Vstudio&MC=ASPNET&MC=MobileDev&MC=DevOps&MC=AppDnDTool)
* Content Source: [mac/tutorial-aspnet-core-vsmac-getting-started.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tutorial-aspnet-core-vsmac-getting-started.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
@gregveres we have a [workshop](https://github.com/dotnet-presentations/aspnetcore-for-beginners) which covers using a database. Can you let me know if that covers the type of info you are looking for?

I was discussing with @unniravindranathan the possibility of creating a video around the workshop content.

We also have the [eShopOnWeb videos + docs](https://docs.microsoft.com/en-us/visualstudio/mac/tutorial-aspnet-core-vsmac-extending?view=vsmac-2019) which covers a lot of great content, but it doesn't include info about databases.

**Comment by gregveres** [comment]
@sayedihashimi Thanks for pointing those out. I am reviewing the workshop now. If I have any comments on those, I will submit the comments there. 

I asked the original question because there seems to be a lack of information talking about doing .Net dev on a mac with a database. So if there is such documentation, I would recommend linking to it everywhere that you talk about beginning with Visual Studio for the mac. I have recently moved from developing .Net in Parallels on a mac to using a real Windows machine and I really miss MacOS, so I keep looking for ways to get back to the Mac, unfortunately my project is still .Net, not .Net Core and I am still using EF 6. 

One other thing I noticed in your video and on the workshop tutorial is that I don't like the coding style / format you guys use. It makes the "namespace" stand out as the most important item in the file when it is really the least important. For an example of what I am talking about, take a look at [this code snippet](https://github.com/dotnet-presentations/aspnetcore-for-beginners/blob/master/Tutorial/2-Add%20a%20model/Addamodel-VSMac.md#add-a-database-context-class). The thing that is the easiest to read is the namespace. The MovieContext class underneath is difficult to extract because it looks like it is just a continuation of the namespace line. I assume you guys choose the opening brace on the end of the line formatting because it takes up less space on the web page. I can appreciate that. But I think you should adopt putting a blank line after the namespace line because the namespace line is irrelevant for what you are trying to convey and, I would guess, 100% of the time the line directly after the namespace is the most important thing you are trying to convey, so it should be formatted in a way that makes it stand out. Putting a blank line between it and the namespace will help it to stand out.

**Comment by sayedihashimi** [comment]
@gregveres thanks for the comments. 

Another option that I forgot to mention is that you can [run SQL Server in a docker container](https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash) on the Mac. And you can use [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-ver15) to interact with the database.

I think we should have some docs, and possibly video(s), showing how to develop ASP.NET Core apps that use a DB with Visual Studio for Mac. I'm pretty busy for the next couple of weeks, but I'd like to get started on that once I free up a bit.

Regarding your code formatting suggestion, I'm not sure what the guidance is from the doc team on what the format for code is. @conceptdev what's the proper code formatting for docs? Also there is some feedback on code formatting in the previous comment here that may interest you. Craig, can you assign this item to me?

**Comment by gregveres** [comment]
@sayedihashimi 

Yes that type of video would be good. I have been looking over some other docs this morning and [found one that covered getting started](https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/sql?view=aspnetcore-3.0&tabs=visual-studio) for both mac, linux and windows. It was pretty good - no video though. It raised another question that I think should be answered:

The code for the windows portion was different than the code for the linux/mac portion. This really confused me because I would assume that a development shop would have a mix of windows and mac developers. They aren't developing the code to run on their local machine, they are developing the code to run somewhere like Azure. The key difference that I just couldn't wrap my head around was that the windows code explicitly calls UseSqlServer and the mac/linux one explicitly calls UseSqlite. 
I would think that any description that covers code like this would explain why the two platforms are different and how you write your code to:

1. work properly in a mixed platform environment 
1. work properly when deployed to Azure

I can understand how the configuration of the connection string can be different in those three environments, the configuration pages are pretty good for explaining the different options and the hierarchy rules for where the actual option comes from when it exists in multiple places. But it is this instantiating the db provider that seems so explicit for the different platforms that I can't wrap my head around given the docs I have seen so far.  (Not to mention the migration hassle of the sqlite provider not being able to handle average complexity migrations. but I get limitations like that. )

Anyway, thanks for listening. :)

**Comment by conceptdev** [comment]
Regarding the code formatting, we're always trying to balance clarity with succinctness. Lots of extra lines in a code block can make the whole block (and page) longer, but compressing lines can also make it hard to read.

In general I'd say the "proper" code formatting for docs would be our default Visual Studio auto-format, since that is probably what the majority of customers are used to seeing. But I understand when authors feel they need to stray from that in the interests of clarity.

As an interesting aside, @gregveres, you will frequently see code snippets in docs that completely omit the namespace and usings, specifically for the reasons you point out (they can be a distraction). For the majority of customers, this does help them understand the important parts of the code, but occasionally it will trip someone up too. We're always learning what works best, and appreciate your feedback.

**Comment by sayedihashimi** [comment]
I'm no longer working with Visual Studio for Mac. I think this would be better assigned to @jmatthiesen.
