### ISSUE TITLE
No Performance Wizard

### ISSUE THREAD

**Issue by BjornSigurd** [MicrosoftDocs/visualstudio-docs#4255]
In ASP.NET Core project, there seems to be no 'Analyze' &gt; 'Launch Performance Wizard' choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66747ef0-0cbb-8afa-5bfc-ac214bef9d5c
* Version Independent ID: e69d3816-91cf-25bb-c395-5678cb70ecab
* Content: [How to: Profile JavaScript Code in Web Pages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-profile-javascript-code-in-web-pages?view=vs-2019#feedback)
* Content Source: [docs/profiling/how-to-profile-javascript-code-in-web-pages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/how-to-profile-javascript-code-in-web-pages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
We are removing these docs from VS 2019. There are some limited features related to Performance Explorer / Wizard that are still supported, that is still being identified.

**Comment by Mikejo5000** [comment]
Docs are updated new, with Performance Explorer docs removed from VS 2019 view...
Example:
https://docs.microsoft.com/en-us/visualstudio/profiling/performance-explorer?view=vs-2017&viewFallbackFrom=vs-2019

**Comment by BjornSigurd** [comment]
Why is Performance Explorer removed from VS 2019?  Performance Explorer is very important.

**Comment by Mikejo5000** [comment]
I'm asking about the specific reasons. There are some new docs planned for scenarios that are still supported, but in general Performance Explorer is a legacy tool. What is the main scenario you have in mind?

**Comment by BjornSigurd** [comment]
Performance evaluation and tuning of ASP.Net Core server and client.

**Comment by Mikejo5000** [comment]
The best statement I've seen about the changes is here, the comments by Allen Denver.
https://developercommunity.visualstudio.com/content/problem/441152/missing-profiler-options-under-debug-visual-studio.html

**Comment by BjornSigurd** [comment]
Ok, thx.  

Debug>Performace Profiler looks ok.
