### ISSUE TITLE
Even if superfastcode2 (C ++) is set as a reference, it cannot be imported to python (pybind11)

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4257]
@hamukawa0406 commented on [Thu Oct 31 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1862)

visual studio 2019
windows 10
When this page was done in the above environment, c ++ file build was successful,
If you try to call a DLL from python,
"unresolved import 'superfastcode2'"
An error occurs.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Python 用の C++ 拡張機能の記述 - Visual Studio](https://docs.microsoft.com/ja-jp/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/blob/live/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

---

@srvbpigh commented on [Thu Oct 31 2019](https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1862#issuecomment-548228606)

Hello, @hamukawa0406
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by msebolt** [comment]
This is something that needs to be directed to the product team.

@hamukawa0406  Please see if https://github.com/microsoft/PTVS/issues/5027 describes the issue.

**Comment by msebolt** [comment]
Closing the issue now.

For additional product support, please use **Report a problem** in the [Azure DevOps community](https://developercommunity.visualstudio.com/spaces/21/index.html).
