### ISSUE TITLE
ProjectReference metadata is incomplete

### ISSUE THREAD

**Issue by cdmihai** [MicrosoftDocs/visualstudio-docs#4258]
There's more metadata that is not documented on this page, like metadata for controlling global properties and the output item type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e663f7-3bac-61af-28bb-f0e471dcdca6
* Version Independent ID: 97985f56-e0ac-a03d-f651-b86cc2b85804
* Content: [Common MSBuild Project Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019#projectreference)
* Content Source: [docs/msbuild/common-msbuild-project-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-items.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@cdmihai Thank you for the feedback, assigning this to the author for review.

**Comment by rainersigwald** [comment]
Here's my half-written doc on this which is not ready to publish but may help for now: https://gist.github.com/rainersigwald/1fbd21a24a41b9b7c6204cb9cfcbb1cf

**Comment by clisc** [comment]
Any update on this?  In the meantime, what is the best reference to use?

**Comment by ghogen** [comment]
This was fixed in the referenced PR.

**Comment by ghogen** [comment]
@rainersigwald 
If there's more to do here, please reactivate and let's get the remaining work identified.
