### ISSUE TITLE
Undeclared Identifier 'TextBox' 

### ISSUE THREAD

**Issue by resun555** [MicrosoftDocs/visualstudio-docs#426]
To the Author, you might have note that 'TextBox control with Stretch property' misappeared occasionally under Step 7.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e155a58-40dd-c4f9-5089-dabc1870c5a8
* Version Independent ID: e257ebf0-4506-408f-c078-18a35820fe60
* [Step 5: Add controls to your form](https://docs.microsoft.com/en-us/visualstudio/ide/step-5-add-controls-to-your-form#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/step-5-add-controls-to-your-form.md)

**Comment by TerryGLee** [comment]
@resun555 Thanks for the feedback! We'll take a look at this and make updates to the page as needed.

**Comment by TerryGLee** [comment]
@resun555 Apologies that it has taken us a while to get to this. But, we have fixed the misaligned screenshot captions on the [Step 5: Add controls to your form](https://docs.microsoft.com/visualstudio/ide/step-5-add-controls-to-your-form) page, which includes the caption that reads "TextBox control with Stretch property". 

We are closing this issue now. (However, if this isn't the problem you intended to identify when you first opened this issue, please create a new GitHub Issue and provide further detail as to what you'd like to see us fix. And, thanks for helping us improve the Visual Studio documentation!)
