### ISSUE TITLE
The table header in the roadmap page is incorrect.

### ISSUE THREAD

**Issue by PlusoneWang** [MicrosoftDocs/visualstudio-docs#4263]
> I didn't find the source code of this page, and I don't know where this issue should be posted, so I posted it here.

Please check the page and image below.
https://docs.microsoft.com/zh-tw/visualstudio/productinfo/vs-roadmap
![Image 2](https://user-images.githubusercontent.com/37727068/68015950-63d6e100-fcce-11e9-80de-6793733d7cc0.png)
As I point out in image, the second header "Feature" should not exist. The word `Feature` has been translate to `功能`, which is the first table header. This error causes the header to be out of alignment with the content.

This error happen in other non-English pages, like ja-jp:
![Image 4](https://user-images.githubusercontent.com/37727068/68016107-c62fe180-fcce-11e9-93b1-4855cd3bc65d.png)
and ko-kr:
![Image 5](https://user-images.githubusercontent.com/37727068/68016127-d5af2a80-fcce-11e9-8e3c-a6a041a35d94.png)
I didn't check all the languages, but all the pages I checked had this error.

**Comment by TerryGLee** [comment]
@CeciAc Could you please take a look at this issue? Many thanks in advance!

**Comment by CeciAc** [comment]
Hello, @PlusoneWang 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@PlusoneWang Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-tw/visualstudio/productinfo/vs-roadmap.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
#please-close
