### ISSUE TITLE
How to enable this behavior

### ISSUE THREAD

**Issue by roryap** [MicrosoftDocs/visualstudio-docs#4264]
I'm using VS 2017 and this feature is not showing in the refactor menu.  How do I enable it?  This URL indicates VS 2017.  https://docs.microsoft.com/en-us/visualstudio/ide/reference/move-type-to-namespace?view=vs-2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa5d8fa-b34c-4452-931d-b6230e0dff71
* Version Independent ID: 6b10c735-49f1-6341-84f7-6442a6febbdd
* Content: [Move type to namespace - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/move-type-to-namespace?view=vs-2017#feedback)
* Content Source: [docs/ide/reference/move-type-to-namespace.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/move-type-to-namespace.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by Jehoel** [comment]
VS2017 has multiple different Refactor menus with different options. I appreciate it's confusing.

Put your caret (the blinking I-bar cursor) on the identifier of the class declaration of the class you want to move, then press `[Ctrl] + '.' (dot)` on your keyboard to get the Code Fixes menu popup with those options.

A subtle icon will also appear in the left-side gutter that you can click to open the menu. Sometime over the past few months an update to VS2017 changed the icon from a bright and visible lightbulb to a blue screwdriver that doesn't stand out as well, unfortunately:

![image](https://user-images.githubusercontent.com/1693078/68078757-1f187c00-fd9a-11e9-8c9f-daa62c457e42.png)

This is how it used to look a few months ago:

![image](https://i.stack.imgur.com/vE4GT.png)

**Comment by WilliamAntonRohm** [comment]
@roryap -- thank you for your feedback.

@Jehoel, @mikadumont -- please look into a potential documentation update.

**Comment by roryap** [comment]
> 
> 
> VS2017 has multiple different Refactor menus with different options. I appreciate it's confusing.
> 
> Put your caret (the blinking I-bar cursor) on the identifier of the class declaration of the class you want to move, then press `[Ctrl] + '.' (dot)` on your keyboard to get the Code Fixes menu popup with those options.
> 
> A subtle icon will also appear in the left-side gutter that you can click to open the menu. Sometime over the past few months an update to VS2017 changed the icon from a bright and visible lightbulb to a blue screwdriver that doesn't stand out as well, unfortunately:
> 
> ![image](https://user-images.githubusercontent.com/1693078/68078757-1f187c00-fd9a-11e9-8c9f-daa62c457e42.png)
> 
> This is how it used to look a few months ago:
> 
> ![image](https://camo.githubusercontent.com/ba628a76e61c8c7628e24ca39736cd746ac5991b/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f76453447542e706e67)

I'm not sure how this comment addresses the missing "move to namespace" feature....

**Comment by Jehoel** [comment]
@roryap I thought you were referring to the Edit > Refactor menu, not the Editor > Code Fixes menu.

**Comment by roryap** [comment]
I'm referring to the "move type to namespace" feature which the link I provided says should be in the refactor menu.

**Comment by mikadumont** [comment]
Hi @roryap. The documentation says Quick Actions and Refactorings menu which refers to either the lightbulb menu (quick actions) or the screwdriver menu (refactoring menu).

**Comment by mikadumont** [comment]
@TerryGLee This feature doesnt exist in Visual Studio 2017. We added it in 16.1. Can we make sure it doesnt show up under 2017?

**Comment by TerryGLee** [comment]
@mikadumont Yes, there is a way to do this; I'll create a PR for it that we can get published tomorrow morning. (I'll @ mention you on the PR in the private repo.)

**Comment by mikadumont** [comment]
Thanks @TerryGLee! Can we go ahead and close this then?

**Comment by TerryGLee** [comment]
@mikadumont I'll take care of closing it after the update goes live. :)

**Comment by TerryGLee** [comment]
@roryap Thanks again for bringing this issue to our attention. We've changed the page so that it doesn't appear in the Visual Studio 2017 library of content. And, when anyone tries to visit the page for 2017, they'll receive the following message and are then redirected to the 2019 page:

![image](https://user-images.githubusercontent.com/23244653/77946145-b9f88200-7276-11ea-8b40-9808d5669f48.png)

We are closing this issue now. Thanks for your help in improving our documentation!
