### ISSUE TITLE
Well known or reserved property names? ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/visualstudio-docs#4269]
Might be a good idea to add details regarding well known or reserved property names to this page.  For example, if I create a new ASP.Net Core 3.0 project, Visual studio adds the following to my .csproj file:

```
   <PropertyGroup>
      <TargetFramework>netcoreapp3.0</TargetFramework>
   </PropertyGroup>
```

Details regarding  (or a link to) the **&lt;TargetFramework&gt;** node should be mentioned on this page as (obviously) the &lt;TargetFramework&gt; node is a valid child of &lt;PropertyGroup&gt;

So naturally, one asks the question:
What other reserved or well known child node names are also valid for &lt;PropertyGroup&gt;?  There is no mention of "system" defined properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa26a042-4407-51d2-7df9-f045aaef2a3d
* Version Independent ID: 57f71dc5-34b2-6431-c4a4-c308e48adf0b
* Content: [PropertyGroup Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/propertygroup-element-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/propertygroup-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/propertygroup-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Jehoel** [comment]
> What other reserved or well known child node names are also valid for <PropertyGroup>? There is no mention of "system" defined properties.

This?

>  https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019 
>
> ## Common MSBuild project properties
>
> AdditionalLibPaths, AddModules, ALToolPath, ApplicationIcon, etc

**Comment by bdcoder2** [comment]
@Jehoel - I do not see <TargetFramework> even mentioned on the page referenced: 

[https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019)

Where is the COMPLETE schema for the .csproj file -- that is, where are all elements and the valid values documented?

Thanks again.

**Comment by Jehoel** [comment]
> Where is the COMPLETE schema for the .csproj file -- that is, where are all elements and the valid values documented?

There isn't one. Each `.targets` and MSBuild file can add its own properties - for example, an ASP.NET Core project has its own properties for IIS debugging, and a `pubxml` file (which is also an MSBuild file) has its own properties too.

I think one of the reasons the `TargetFramework` property is underdocumented is because the design of the properties for .NET Core projects is seemingly constantly changing - for example there's now both `TargetFramework` and `TargetFrameworks` (for multi-targeting) - and apparently the `TargetFramework` element used to be hidden entirely (e.g. see https://github.com/dotnet/project-system/issues/1358 ).

Don't forget, you can always read through the `.targets` and other MSBuild files to see how and where each property is defined or consumed.

**Comment by bdcoder2** [comment]
@Jehoel - Thanks - but anyone new (myself) has found trying to find information about the various configuration files a rather daunting and time consuming task (it shouldn't be).   Having to spend hours trying to find out what a specific node or attribute does within a config file is a waste of time -- there needs to be a "dictionary" or schema of sorts that programmers can reference to find out (quickly and easily) what specific config properties do (and whether or not it pertains to their project type; as I understand from what you are saying.

With regard to the various configurations - It may be worthwhile to organize the documentation around specific **project types** instead of the current methodology employed - which seems to consist of sprinkling the odd tidbit of information in various places throughout the docs.  For example, I am creating a ASP.Net Core website (app?) - Currently, in the project and docs, I have run across 

- web.config
- appsettings.json
- launchsettings.json
- {projectname}.csproj,
- .pubxml files

... but have yet to grasp how each of them interact or even how one configuration file can transform another during the lifecycle of the project (somehow the {projectname.csproj apparently creates or transforms a web.config file -- but how, when, etc)?  Are these not relevant questions when one is trying to learn how all this stuff works?

Finding the relevant properties and valid values for attributes within each of these config files has been nothing short of a nightmare.   Usually, I find the answer via some code example / sample shown on StackOverflow or in the docs; but **details** about specific properties and/or attributes are completely lacking.  There is never an excuse for "under-documenting".

My kingdom for documentation we had 30+ years ago !!! (To be fair, things were a little simpler back then). 

Thanks.

**Comment by Jehoel** [comment]
* `web.config` is not used by ASP.NET Core. However your website might have one for IIS settings (`<system.webServer>`).
* `appSettings.json` is where you store most configuration data.
* `launchSettings.json` is used to configure the Visual Studio debugger. It lets you specify different environment variables and command-line arguments for your program without changing the Project Configuration. I wish this functionality worked for WinForms and WPF applications.
* `{project}.csproj` is your project file which is also an MSBuild file.
* `pubxml` is an MSBuild file that is only used when publishing your web-application. It can be used by both Visual Studio as well as build/deployment automation systems.

> Usually, I find the answer via some code example / sample shown on StackOverflow or in the docs;

"Software development in 2019" :)

> .Where pray-tell, do I find the docs regarding ".targets"?

As with MSBuild files in general, there isn't a reference or exhaustive listing of the properties, instead you just read the `.targets` files directly. A `.target` file is just another MSBuild file but the file-name extension tells you it it's intended to be included into another MSBuild file (i.e. your `.csproj` and `.pubxml` files).

An overview of MSBuild and .targets files is available here: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-dot-targets-files?view=vs-2019

> My kingdom for documentation we had 30+ years ago !!! (To be fair, things were a little simpler back then).

30 years ago we couldn't automate and extend the Visual Basic build process. Website deployment was over FTP or FPSE. And everyone used the Waterfall model :)

**Comment by bdcoder2** [comment]
> web.config is not used by ASP.NET Core. However your website might have one for IIS settings (<system.webServer>).
appSettings.json is where you store most configuration data.
launchSettings.json is used to configure the Visual Studio debugger. It lets you specify different environment variables and command-line arguments for your program without changing the Project Configuration. I wish this functionality worked for WinForms and WPF applications.
{project}.csproj is your project file which is also an MSBuild file.
pubxml is an MSBuild file that is only used when publishing your web-application. It can be used by both Visual Studio as well as build/deployment automation systems.

Had the docs for my project even opened with a paragraph like the one above, I would have saved myself 4+ days!!

Since 2018, others have been asking for docs regarding the same issues I am bringing up today:
[https://github.com/MicrosoftDocs/visualstudio-docs/issues/683](https://github.com/MicrosoftDocs/visualstudio-docs/issues/683)  -- but oh well ...

> "Software development in 2019"

Clearly, it looks like I am doomed to forever find the answer on StackOverflow.

> Website deployment was over FTP or FPSE. And everyone used the Waterfall model :)

Yes, but at least we understood how everything worked!
