### ISSUE TITLE
the last cell in the PictureBox -> the last cell in the TableLayoutPanel

### ISSUE THREAD

**Issue by resun555** [MicrosoftDocs/visualstudio-docs#427]
Dear Author @ghogen, @Saisang, @gewarren, @Mikejo5000, @mikeblome, 

Please read twice before you publish the documentation. Step 8, you might refer to adding a new control to the last cell in the TableLayoutPanel instead of the PictureBox. No cells within the PictureBox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e155a58-40dd-c4f9-5089-dabc1870c5a8
* Version Independent ID: e257ebf0-4506-408f-c078-18a35820fe60
* [Step 5: Add controls to your form](https://docs.microsoft.com/en-us/visualstudio/ide/step-5-add-controls-to-your-form#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/step-5-add-controls-to-your-form.md)

**Comment by TerryGLee** [comment]
@resun555 Thanks for your feedback; we appreciate it. This is in our backlog queue to get fixed; we'll report back when it is.

**Comment by TerryGLee** [comment]
@resun555 We have a fix in place to address the issue you brought up, which should go live by noon on 9/4/2019. Thanks for your help with improving our documentation!
