### ISSUE TITLE
_Analysis_assume

### ISSUE THREAD

**Issue by stewart-patch** [MicrosoftDocs/visualstudio-docs#4270]
Three places on this page (in text) spell it as above. The fourth place (in the example) has __analysis_assume, i.e. different capitalization and two leading underscores.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc8501a5-3dc2-5bb0-6457-48c36866cc9f
* Version Independent ID: 33802fb2-b687-b9d3-c5d4-79ab86e1cd63
* Content: [Use _Analysis_assume for code analysis hints - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume?view=vs-2019#feedback)
* Content Source: [docs/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-specify-additional-code-information-by-using-analysis-assume.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by asklar** [comment]
Actually the _Analysis_Assume_ syntax is for SAL2 while __analysis_assume is for SAL1
