### ISSUE TITLE
This page needs suppression guidance for things like Application_Start

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4272]
The current advice in "When to suppress warnings" doesnt make sense. Its a warning about a method name. It can be whatever is legal and still be "safe".  

It also doesnt explain what to do for the MSFT issued names like Application_Start that cause this CA rule to pop.  Clearly we want to suppress those instances, but really we dont want to be informed of them in the first place. 

Do note that some of us use "Treat Warnings as Errors" to prevent compiler warning creep, and that suppressing these kind of things is required for production code to even compile. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06cee199-3ccc-7575-2c1d-296e2714a16e
* Version Independent ID: 2be241bf-b98a-5088-1e1b-0e39b1384b9a
* Content: [CA1707: Identifiers should not contain underscores - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1707?view=vs-2019)
* Content Source: [docs/code-quality/ca1707.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1707.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
It appears that Application_Start needs to be renamed. Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. Then your report gets listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by StingyJack** [comment]
Thanks @Mikejo5000, I'm pretty familiar with devcomm. This is a document problem though, because the direction on how to fix this for some MSFT required method names (like application_start) will break functionality in an asp.net website. For those well known methods the rule should be suppressed.

I can create a separate issue for the CA rule flagging this once I can find that repo again (any hints? I know I've been there but GH search is returning a few hundred results)

**Comment by Mikejo5000** [comment]
Sure, I believe that is https://github.com/dotnet/roslyn-analyzers/

**Comment by Mikejo5000** [comment]
Updating When to Suppress section for well-known methods.
