### ISSUE TITLE
Not accurate

### ISSUE THREAD

**Issue by jpsjogren** [MicrosoftDocs/visualstudio-docs#4276]
I don't see publish to Azure after signing in.
Plus the whole application looks different

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92da5d51-dd0e-f62e-c453-8bdaafe04776
* Version Independent ID: 645d4899-f7c6-ffcd-53fa-3b6fb64be765
* Content: [Publish to Azure App Service - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-app-svc?view=vsmac-2019#feedback)
* Content Source: [mac/publish-app-svc.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-app-svc.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by msebolt** [comment]
@jpsjogren Thank you for the feedback, assigning this to the author for review.

**Comment by heiligerdankgesang** [comment]
@jpsjogren - Could you let us know what your Visual Studio for Mac version is? You can grab that from **Visual Studio > About Visual Studio". Let us know the exact steps you're taking and what looks different.

I just tried this on the latest version of Visual Studio for Mac and it works as described in the document.

**Comment by kcp210** [comment]
I do not have the Publish option in Visual Studio. I am on version 8.4.3 (Build 12)

**Comment by sayedihashimi** [comment]
@kcp210 can you paste the contents of your .csproj file here?

**Comment by sayedihashimi** [comment]
I'm no longer working with Visual Studio for Mac. I think this would be better assigned to @jmatthiesen.
