### ISSUE TITLE
Should also suppress on lambdas

### ISSUE THREAD

**Issue by Gutza** [MicrosoftDocs/visualstudio-docs#4278]
Here's a canonical use case not mentioned as a legitimate suppression reason in the VS doc pages: https://stackoverflow.com/questions/18226705/false-ca1812-warning-internal-class-that-is-apparently-never-instantiated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4303a22-627d-4024-fee7-40db88a544ac
* Version Independent ID: 37cc2f4d-7002-1b29-cfa4-b8be2924d0a7
* Content: [CA1812: Avoid uninstantiated internal classes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1812?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1812.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1812.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
@mavasani Is it OK to add lambdas be added in the "When to suppress warning" section?

**Comment by mavasani** [comment]
No, the rule should not fire in this case. @Gutza How are you running code analysis? Are you installing the latest Microsoft.CodeAnalysis.FxCopAnalyzers NuGet package: https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/?

**Comment by Gutza** [comment]
I did at the time. It's not reasonable to expect me to preserve the setup for three months, I can't even remember in which specific project I encountered this.

**Comment by Mikejo5000** [comment]
@Gutza Sorry for the slow response to the original issue. We will close this for now unless we get more information.
