### ISSUE TITLE
Permissions?

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/visualstudio-docs#428]
What permissions are needed to do this? I need to know what to request from our Infrastructure team.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37c9f861-f61b-0262-3763-1ed266a057c0
* Version Independent ID: 69f80401-52f7-70b6-e37d-7eba1a3bf1ca
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-apps-faq)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/debug-live-azure-apps-faq.md)

**Comment by nikhilrj** [comment]
@MisinformedDNA as of now, the Azure App Service you would like to debug must be visible to the user that wants to attach the Snapshot Debugger. This can be achieved by setting your access level to "Contributor" or higher in the Access Control (IAM) page on the relevant App Service on the Azure portal.

**Comment by Mikejo5000** [comment]
No doc update planned for this. Closing.
