### ISSUE TITLE
Extensions compatability

### ISSUE THREAD

**Issue by BobbyCGD** [MicrosoftDocs/visualstudio-docs#4285]
As someone who has never written an extension, I would have like to see/know if VS extensions are compatible with other versions of VS such as VS Code. What makes them compatible? Are VS Code and VS extensions the same? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f1f45a-7db7-44ca-9740-4098f1cd800e
* Version Independent ID: 8e2d59cc-af2d-71e0-8b4b-5fdbd2ecd278
* Content: [Starting to Develop Visual Studio Extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/starting-to-develop-visual-studio-extensions?view=vs-2019#feedback)
* Content Source: [docs/extensibility/starting-to-develop-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/starting-to-develop-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@BobbyCGD -- Boris, thanks for your question.  Here are a few options where you may find answers:​  

-  [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@madskristensen -- Mads, please look into this issue.

**Comment by BobbyCGD** [comment]
@WilliamAntonRohm -- Thanks for looking into this and suggesting additional sources. 
@madskristensen -- I will keep an eye out on this issue, looking forward to reading your content :)

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response.  Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant, structural doc changes, we are closing this lower priority issue.  We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
