### ISSUE TITLE
MSBuild Import doc claims relative paths are relative to the importing project's dir, but this is not true for imports in the imported file

### ISSUE THREAD

**Issue by dagood** [MicrosoftDocs/visualstudio-docs#4287]
This paragraph is correct in some cases, but not in others:

> Relative paths in imported projects are interpreted relative to the directory of the importing project. Therefore, if a project file is imported into several project files in different locations, the relative paths in the imported project file will be interpreted differently for each imported project.

This is generally true for properties and items (and I think that was the intent behind the writing because they're what people more often get tripped up by). It is incorrect for `Import`s within the imported project: these are actually relative to the imported project.

Example project: [import-relative.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/3816475/import-relative.zip)

* `ImportingProject\ImportingProject.csproj` -- default `dotnet new console` project.
* `ImportingProject\Program.csproj` -- default `dotnet new console` program.
* `Directory.Build.targets` -- targets file imported automatically by the SDK targets.
  * Contains `<Import Project="Outside.File.targets" />`
* `Outside.File.targets` -- prints `Hello World!` after the Build target to prove it's imported.

`dotnet build` succeeds, and prints `Hello World!`.

If the doc were correct, `<Import Project="Outside.File.targets" />` would search for the file relative to `ImportingProject\ImportingProject.csproj` and fail when it doesn't see `ImportingProject\Outside.File.targets`.

This doc caused some confusion over at https://github.com/dotnet/core-setup/pull/8785.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af512ce8-46bd-b15a-c5a2-f8315d2b258a
* Version Independent ID: e2c221b8-466f-df7f-078c-bab89be71828
* Content: [Import Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2019#remarks)
* Content Source: [docs/msbuild/import-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/import-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by rainersigwald** [comment]
cc @Mikejo5000 

maybe it should just say the "immediately importing" project? What it means by "importing project" is "the file that has the `<Import` element in it". But "project" generally means an entry point like a `.csproj`--for example, that's what you get with `$(MSBuildProjectFullPath)`.

**Comment by dagood** [comment]
The way I'm understanding that suggestion, I think it'd make the item/property scenario less clear. With that wording I might expect items defined in `\Outside.File.targets` to be relative to the "immediately importing" `\Directory.Build.targets`. (If I manage to interpret "project" to mean "MSBuild file" in the first place. 😄)

I don't have a tweak in mind that can solve this... in my mental model of what MSBuild's doing, how the imports vs. items/conditions are handled are fairly separate processes that probably can't be lumped together without _something_ being unclear.

**Comment by rainersigwald** [comment]
I'm not sure I understand what you're saying about items/properties. Items can't be used in import elements. If properties are used, they're either: 
a. expanded to a relative path, and that's treated as relative to the (immediately) importing project, or 
b. expanded to an absolute path and that gets imported.

Maybe the tweak should be around the first part of this sentence? Maybe something along the lines of

> Relative paths in the `Project` attribute are interpreted relative to the file that contains the `Import` element 

And maybe also a note that this doesn't affect items?

**Comment by dagood** [comment]
I think you're reading this bit completely differently than I am:

> Relative paths in imported projects

To me, this means "relative paths you find in an imported project", such as relative paths in properties, and in item `Include`s. This in my opinion it the way to read it to make the rest of the paragraph make sense:

> Therefore, if a project file is imported into several project files in different locations, the relative paths in the imported project file will be interpreted differently for each imported project.

Your suggestion sounds good to me in isolation, but I don't see how it fits with the rest of the paragraph:

> > Relative paths in the `Project` attribute are interpreted relative to the file that contains the `Import` element
> 
> Therefore, if a project file is imported into several project files in different locations, the relative paths in the imported project file will be interpreted differently for each imported project.

(If the solution is to have two paragraphs... that would make sense to me.)

**Comment by rainersigwald** [comment]
There are a few things at play here:
1. Properties are strings. You can use them to hold a relative path, but that's not known to MSBuild.
2. `<Import Project="relativepath" />` is relative to the file containing the `Import` element.
3. Item `Include="relativepath"` are relative to the primary project (`$(MSBuildProjectDirectory)`).

This page was trying to get at 3, 2 was what tripped up that other PR, and 3 doesn't seem to be documented in [the Items docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items) at all, which it probably should be.

**Comment by dagood** [comment]
Yep, that all matches my understanding. Thanks.

**Comment by Mikejo5000** [comment]
@rainersigwald Sounds like we need a minor update to the doc for point 3?

**Comment by ghogen** [comment]
@rainersigwald What about UsingTask?

**Comment by rainersigwald** [comment]
It is relative to the file in which the `UsingTask` appears:

https://github.com/microsoft/msbuild/blob/00781ad1353afba25451148dba61845ac139b572/src/Build/Instance/TaskRegistry.cs#L303-L304

**Comment by dagood** [comment]
Why was this issue closed?

The doc still makes this claim that is not correct and caused confusion:

> Relative paths in imported projects are interpreted relative to the directory of the importing project.

To be specific, it is not true in this case highlighted above by @rainersigwald:

> 2. `<Import Project="relativepath" />` is relative to the file containing the `Import` element.

The page needs to clarify that it's only trying to clarify this specific point about items:

> 3. Item `Include="relativepath"` are relative to the primary project (`$(MSBuildProjectDirectory)`).
