### ISSUE TITLE
npm ERR! missing script: clean

### ISSUE THREAD

**Issue by joseogl** [MicrosoftDocs/visualstudio-docs#4289]
Following the steps in this tutorial results in the error below below whne using Build Clean or Rebuild Solution.  There is indeed to clean in package.json.  Should there be?  If it needs to be added what should the command be?  It isn;t clear that it is needed as the project builds and runs.

I am having a problem with breakpoints in debugging the TS code.  Will create a new issue for it if I can't figure it out.

------ Clean started: Project: NodejsWebApp1, Configuration: Debug Any CPU ------
		npm ERR! missing script: clean
		npm ERR! A complete log of this run can be found in:
		npm ERR!     C:\Users\joseo\AppData\Roaming\npm-cache\_logs\2019-11-07T15_16_15_572Z-debug.log
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\Node.js Tools\Microsoft.NodejsToolsV2.targets(56,5): error MSB3073: The command "npm run clean" exited with code 1.
Done building project "NodejsWebApp1.njsproj" -- FAILED.

Build FAILED.
========== Clean: 0 succeeded, 1 failed, 0 sk

**Comment by msebolt** [comment]
@joseogl  Thank you for the feedback.

Please add a link to the tutorial below and we will have this issue investigated further.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are still issues.
