### ISSUE TITLE
Can not find ActivityLog.xml

### ISSUE THREAD

**Issue by brettc89** [MicrosoftDocs/visualstudio-docs#429]
In the folder "%AppData%\Microsoft\VisualStudio\15.0" I have ActivityLog.Setup.xml and ActivityLog.xsl. Neither has the information that ActivityLog.xml is supposed to have.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72794642-353e-46e5-c822-f471b5ef65b4
* Version Independent ID: 391aac5d-2695-9344-828e-8d5e8b9a334b
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/how-to-use-the-activity-log.md)

**Comment by gregvanl** [comment]
Hi @brettc89, to generate ActivityLog.xml, the user still needs to run Visual Studio with the /log switch. The file is not written to disk unless this switch is used. See https://msdn.microsoft.com/en-us/library/ms241272.aspx. I'll update this topic to make that more clear.
