### ISSUE TITLE
No longer works with the Runtime Stack Node.js option 8.9 above

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4293]
Hi team, 
I'm moving this here because it refers to the original documentation
https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/issues/71
The comment below was machine-translated

@ynguyenluat commented 9 hours ago — with docs.microsoft.com
Fix: add the application parameter WEBSITE_NODE_DEFAULT_VERSION = 8.9.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52d4b59f-07fd-b894-01f7-9bc2fc06e98a
* Version Independent ID: 1cb6913e-21a7-48d2-8b83-cb416304b0c5
* Content: [Publish a Node.js app to Linux App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/publish-nodejs-app-azure?view=vs-2019#feedback)
* Content Source: [docs/javascript/publish-nodejs-app-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/publish-nodejs-app-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
Assigning this to the author for review.

**Comment by Mikejo5000** [comment]
I'll plan to make this update. Thanks!

**Comment by Mikejo5000** [comment]
@ynguyenluat Did you set WEBSITE_NODE_DEFAULT_VERSION = 8.9.0 under "Application settings"?

**Comment by Mikejo5000** [comment]
Added details based on:
https://blogs.msdn.microsoft.com/azureossds/2018/09/25/how-to-set-node-version-for-windows-node-js-webapp-from-azure-portal/
