### ISSUE TITLE
CTest documentation does not tell all the truth

### ISSUE THREAD

**Issue by invy** [MicrosoftDocs/visualstudio-docs#4294]
consider the document:
docs/test/how-to-use-ctest-for-cpp.md#L17:
```
... and the add_test() command to add a new test. To learn more about CTest, see the CMake documentation.
```
and
docs/test/how-to-use-ctest-for-cpp.md#L29:
```
If you are using CTest but not the Google or Boost adapters, you see results at the CTest level instead of the individual test method level.
```

This is not fully true. One can use gtest_discover_tests() in cmake to allow Test Explorer see all Test Cases.

gtest_discover_tests
https://cmake.org/cmake/help/v3.10/module/GoogleTest.html#command:gtest_discover_tests

**Comment by corob-msft** [comment]
An update should appear in the next publishing cycle, usually less than a day.
