### ISSUE TITLE
VS2017 caches but does not updates the Directory.Build.props file

### ISSUE THREAD

**Issue by toebens** [MicrosoftDocs/visualstudio-docs#4295]
VS2017 caches but does not updates the Directory.Build.props file
https://developercommunity.visualstudio.com/content/problem/433497/visual-studio-directorybuildprops-caching.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2017#feedback)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by takekazuomi** [comment]
Please see the Issue below. In legacy project system, once cached in .vs, it is never updated.
https://github.com/dotnet/project-system/issues/2888
I think this limit should be documented.
