### ISSUE TITLE
This question / Answer does not belong in this tutorial.

### ISSUE THREAD

**Issue by chr1974** [MicrosoftDocs/visualstudio-docs#4297]
Hi, the following question on this page is for Django and not flask, thus it should be removed!

Question: When I run the project, I see an error that the template cannot be found. What's wrong?
Answer: If you see errors that the template cannot be found, make sure you added the app to the Flask project's settings.py in the INSTALLED_APPS list. Without that entry, Flask won't know to look in the app's templates folder.

flask do not use a installed apps setting :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3acaa1b-ee19-c571-7c5c-8611722bc0ac
* Version Independent ID: 82c0c673-a82c-3443-0b9c-e30ef39bc894
* Content: [Learn Flask tutorial in Visual Studio step 2, views and templates](https://docs.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-02-create-app?view=vs-2019#feedback)
* Content Source: [docs/python/learn-flask-visual-studio-step-02-create-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-flask-visual-studio-step-02-create-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by msebolt** [comment]
@chr1974  Thank you for the feedback, assigning this to the author for review.

**Comment by JoshuaPartlow** [comment]
Addressed in mentioned PR.
