### ISSUE TITLE
Comment on using FxCop to trace source of warning

### ISSUE THREAD

**Issue by hugoandrioli** [MicrosoftDocs/visualstudio-docs#4298]
Dear All,

I know this isn't the exact right place, but I am stuck with this issue and if someone knows the answer to my question it can save the team a lot of time.

As we have a large code base in C# we want to run Roslyn code analysis.
I added Microsoft Code Analysis to my project and it seems to have installed correctly.
(I saved the output from the installer)

It generates warnings that I can review and I can see the properties of each warning.

My question is how I can see which part of the code generates this warning ?
It seems to analyse the whole solution automatically, allthough you have to install the Code Analysis Project on just one assembly / project in your Solution.

All help is appreciated!

**Comment by msebolt** [comment]
@hugoandrioli Thank you for the question.

Code analysis violations should reference the line of code causing the non-compliance. 
 
For example, in this [command-line example](https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#command-line-usage), the warning refers to `Module1.vb(9,18)` for causing issue with [CA1822](https://docs.microsoft.com/visualstudio/code-quality/ca1822?view=vs-2019).

Please comment below if there are any questions.

**Comment by msebolt** [comment]
Closing the issue now, please add any concerns below.
