### ISSUE TITLE
VS2019 Configuration Manager 

### ISSUE THREAD

**Issue by jmemisevic** [MicrosoftDocs/visualstudio-docs#4299]
Hello team ,

can we get select all check box on top of  "Build" and "Deploy" in configuration manager.
In solutions where there are a lot of projects it's sometimes frustrating to check or uncheck project i want to build or deploy.
This is just a suggestion!

Thanks in advance !

**Comment by msebolt** [comment]
@jmemisevic Thank you for the feedback.

Product features are discussed through the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) under **Suggest a feature** and can elicit direct feedback from the product team.

Please start a thread there and link back to this issue.

**Comment by jmemisevic** [comment]
> @jmemisevic Thank you for the feedback.
> 
> Product features are discussed through the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) under **Suggest a feature** and can elicit direct feedback from the product team.
> 
> Please start a thread there and link back to this issue.

I will do that, thanks for quick reply .
