### ISSUE TITLE
Doesn't appear applicable to Visual Studio 2017 for Mac

### ISSUE THREAD

**Issue by milligna** [MicrosoftDocs/visualstudio-docs#430]
I can't find a word wrap option or an options menu item under "tools" in Visual Studio 2017 for Mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00e3e8d0-48c3-3df6-8aeb-acd9624ffcd5
* Version Independent ID: 13f5da30-9f06-236f-4110-b6a172c52d1f
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md)

**Comment by gewarren** [comment]
@asb3993 can you help out with this question about word wrap in VS for Mac?

**Comment by asb3993** [comment]
Hi @milligna, there is currently no support for the in Visual Studio for Mac

**Comment by hkdeven** [comment]
+1
