### ISSUE TITLE
React or Angular SPA in Visual Studio Docker Compose Problem

### ISSUE THREAD

**Issue by Iamguy84** [MicrosoftDocs/visualstudio-docs#4302]
Hi Folks,

I am using Asp.net Core 3 with Angular and Docker Windows Container.

I followed as below:
[https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019#modify-the-dockerfile-windows-containers](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019#modify-the-dockerfile-windows-containers)

I build and run Docker. It seems good. Now I have created docker compose.

**Docker-compose.yml**

> version: '3.4'
> services:
>   hardwareresources:
>     image: ${DOCKER_REGISTRY-}hardwareresources
>     build:
>       context: .
>       dockerfile: HardwareResources\Dockerfile

I run Docker compose and I am getting error pop up message and it says:

![Capture](https://user-images.githubusercontent.com/13044221/68647513-dc943380-053f-11ea-9cd2-e18e6c7e39e3.PNG)

Could you please advise how to resolve this issue?

Thanks

**Comment by WilliamAntonRohm** [comment]
@Iamguy84 Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by surenrao** [comment]
for aspnet:5.0 below Docker configuration for windows container worked for me
```
# escape=`

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN curl.exe -o node.zip https://nodejs.org/dist/v10.16.3/node-v10.16.3-win-x64.zip && `
  mkdir "C:\\node" && `
  tar.exe -xf node.zip -C "C:\\node" --strip-components=1
RUN setx path "%path%;C:\node"

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
RUN curl.exe -o node.zip https://nodejs.org/dist/v10.16.3/node-v10.16.3-win-x64.zip && `
  mkdir "C:\\node" && `
  tar.exe -xf node.zip -C "C:\\node" --strip-components=1
RUN setx path "%path%;C:\node"
WORKDIR /src
COPY ["Spa/Spa.csproj", "Spa/"]
RUN dotnet restore "Spa/Spa.csproj"
COPY . .
WORKDIR "/src/Spa"
RUN dotnet build "Spa.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Spa.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Spa.dll"]
```
In summary the changes were
  - using curl instead of powershell
  - not copying to system32.
  - after downloading node to c:\node, setting the windows correct PATH.

**Comment by WilliamAntonRohm** [comment]
@surenrao -- Surya, thank you for your follow-up answer.

cc @ghogen for awareness
