### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ulflunde** [MicrosoftDocs/visualstudio-docs#4303]
Very helpful page, clear and informative!
Solved my problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4cdce0-fb0c-5c4f-13a3-b24d39662b64
* Version Independent ID: 70146337-d649-c442-0a37-0810f3dfc9a8
* Content: [Publish to Azure by importing publish settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-import-publish-settings-azure?view=vs-2019)
* Content Source: [docs/deployment/tutorial-import-publish-settings-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-import-publish-settings-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! Appreciate the feedback.
