### ISSUE TITLE
Custom is no more

### ISSUE THREAD

**Issue by kirkktx** [MicrosoftDocs/visualstudio-docs#4306]
This ...
Step 3. Select the Extensibility section, and then choose Custom Command.
Should be changed to this:
Step 3. Select the Extensibility section, and then choose Command.
(Custom not shown in vs2019 16.3.8)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d54da6-38c2-4cc4-9b22-a8f817c83f29
* Version Independent ID: fffed6f2-3b8e-d2c7-e3e3-34ec8bf090d2
* Content: [Hello World extension tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/extensibility-hello-world?view=vs-2019#feedback)
* Content Source: [docs/extensibility/extensibility-hello-world.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/extensibility-hello-world.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@kirkktx -- Kirk, thank you for your feedback.

@madskristensen -- Mads, please look into the command name on line 71 & the image on line 75.

**Comment by PoulChapman** [comment]
Thanks for this feedback. We've got an update to this page coming.
