### ISSUE TITLE
Visual Studio 2017 vs. Visual Studio 2017 Test

### ISSUE THREAD

**Issue by residentx10** [MicrosoftDocs/visualstudio-docs#431]
Can you add some documentation that provides some guidance and when to each? Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f6f8f88-052e-5589-e047-6c2395922364
* Version Independent ID: 78e7c469-cca5-9c74-4578-7fcac33b994d
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-in-visual-studio#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/whats-new-in-visual-studio.md)

**Comment by gewarren** [comment]
@residentx10 can you clarify your question? There is not a separate Test edition of Visual Studio 2017.
