### ISSUE TITLE
how to change the code snippet insert shortcut?

### ISSUE THREAD

**Issue by felixmaomao** [MicrosoftDocs/visualstudio-docs#4310]
how to change the shortcut from double click tab to just click enter?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba6dc7b9-f7d2-9cf3-d0ce-70066af7daa9
* Version Independent ID: 053a95f0-ab8c-e684-dccc-1e6f4063a3ce
* Content: [C# code snippets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-csharp-code-snippets?view=vs-2019#feedback)
* Content Source: [docs/ide/visual-csharp-code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-csharp-code-snippets.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@felixmaomao Thank you for the question.

Are you referring to "...pressing Tab at any time will dismiss the Code Snippet Inserter and insert the currently selected code snippet"?

Unfortunately this is built-in functionality local to the Code Snippet Inserter.  Please also note use of `Enter` can be restricted as a shortcut key, see [Keyboard shortcuts](https://docs.microsoft.com/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2019#customize-a-keyboard-shortcut).

**Comment by felixmaomao** [comment]
@msebolt   Hi， thanks for you response.
I mean ,  for example .  when i print "svm" then i have a code snippet "static void main " for this . But i have to tab twice to insert this code snippet.  This is not quite friendly. I just want to click Enter after i print "svm",and then the snippet can be inserted. In other IDE like Intellj Idea,  this is supported. 
So i think this can also be supported in visual studio.

**Comment by msebolt** [comment]
@felixmaomao Thank you for clarifying this further.

I can assign this to the author to see if this option is currently available, though for feature requests you'll need to use **Suggest a feature** in [Visual Studio communty](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by tfosmark** [comment]
@felixmaomao Here are a few options where you might consider asking your question:​  

[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 

[https://www.stackoverflow.com](https://www.stackoverflow.com) 

[https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
