### ISSUE TITLE
There are extra steps needed for installing the visualizer

### ISSUE THREAD

**Issue by icalvo** [MicrosoftDocs/visualstudio-docs#4311]
In my case I needed two more steps for this to work, with VS 2019 16.3.8 (Windows 10) and a .NET Core 3.0 console project. The two extra steps were:

* Copy DLL to `My Documents\` _VisualStudioVersion_ `\Visualizers\netstandard2.0`
* Copy `MultiSelectTreeView.dll` (also available in the Releases page) to `My Documents\` _VisualStudioVersion_ `\Visualizers\netstandard2.0`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0470059-27e3-58a0-155e-84fbaefae158
* Version Independent ID: 95c9afb2-32f3-945b-9381-9f711179c77d
* Content: [How to: Install a Visualizer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2017#feedback)
* Content Source: [docs/debugger/how-to-install-a-visualizer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-install-a-visualizer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@icalvo Thanks for the information! I'll get the doc updated.

**Comment by Mikejo5000** [comment]
Fixes are getting published in #4368

**Comment by zspitz** [comment]
Presumably the visualizer under question is the [Expression Tree Visualizer](https://github.com/zspitz/ExpressionToString) that I've written. It should be noted that `MultiSelectTreeView.dll` is a dependency of the main visualizer dll, and as such needs to be in the same folder. It might be advisable to work that into the documentation somehow:

> 2. Copy the [Debugger Side DLL](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2019#to-create-the-debugger-side) (and any DLLs it depends on) to either of the following locations:

**Comment by icalvo** [comment]
@zspitz I'm not sure I understood you. Didn't you say the same I did in the OP?

**Comment by zspitz** [comment]
@icalvo Not quite. What you said makes it sound like every visualizer requires `MultiSelectTreeView.dll`, which is definitely not the case. But the general principle -- there might be dlls which the debugger-side dll depends on, and those need to be copied to the visualizer folder -- might be worth mentioning.

**Comment by Mikejo5000** [comment]
Updating this

**Comment by Mikejo5000** [comment]
Fixed in MicrosoftDocs/visualstudio-docs-pr#5877
