### ISSUE TITLE
This is redundant with CA2100

### ISSUE THREAD

**Issue by nirmand** [MicrosoftDocs/visualstudio-docs#4312]
CA2100 deals with the same issue, and covers a bit more area than CA3001. I think its covered there, so I am not sure if we still require 3001 or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 838f3edf-9990-5a78-e2a3-b3f6773bb367
* Version Independent ID: bdea7aed-d5d9-40c0-c259-3c096805dd8a
* Content: [CA3001: Review code for SQL injection vulnerabilities - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca3001?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca3001.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca3001.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @dotpaul
* Microsoft Alias: **paulming**

**Comment by msebolt** [comment]
@nirmand  Thank you for the feedback.

This is more of an issue with the code as opposed to any documentation.

For better support, please move this issue to the [roslyn](https://github.com/dotnet/roslyn/issues) repo.

**Comment by dotpaul** [comment]
[roslyn-analyzers](https://github.com/dotnet/roslyn-analyzers/issues) implements these rules

**Comment by msebolt** [comment]
@dotpaul  Thank you for the correction.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any further issues.
