### ISSUE TITLE
I wanna acknowledge why different solution build result and project build result.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4314]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/visualstudio-docs.ko-kr/issues/66 

@nicejmkim commented 4 hours ago — with docs.microsoft.com
Hi, I'm college student in Korea.
I got a one of MESServer solution and dll file.
So I set this program and built this project one by one.
Result is not Error status. then I build MESServer solution, I got this error.
(LINK : fatal error LNK1123 : failure during conversion to COFF: file invaild or corrupt.)
I don't know why I got this error. I wanna answer and wanna know what is different solution build and project built result.
thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@nicejmkim  Thank you for the question.

See if [this post](https://stackoverflow.com/questions/10888391/error-link-fatal-error-lnk1123-failure-during-conversion-to-coff-file-inval) helps resolve the issue.

If not, please move this to the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) and file as a bug with the product team.

**Comment by msebolt** [comment]
Closing the issue now, please comment below if there are any further issues.
