### ISSUE TITLE
Android SDK default path

### ISSUE THREAD

**Issue by wvc25** [MicrosoftDocs/visualstudio-docs#4315]
New to MSVS2019 here... is there any reason why the Tools &gt; Options &gt; Cross Platform &gt; C++ &gt; Android &gt; Android SDK [default path = C:\Microsoft\AndroidSDK\25] is different from Tools &gt; Options &gt; Xamarin &gt; Android Settings &gt; Android SDK Location [default path = C:\Program Files (x86)\Android\android-sdk]?  I can't properly build the "OpenGL ES application on Android and iOS" example and it seems that these two different Android SDK paths have something to do with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab51e2f8-b5b5-007a-a9b3-23a85b2f2d88
* Version Independent ID: 9cd86e2f-b4d8-00d9-1d02-294bb2692a1d
* Content: [Install cross-platform mobile development with C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-visual-cpp-for-cross-platform-mobile-development?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wvc25 

That's a good question. My guess would be the Microsoft directory default is to prevent the tools from clobbering an existing setup. You can edit the paths in the **Tools > Options > Cross Platform > C++ > Android** page to point to where your preferred tools are, if that helps.

@michelleangela Do you have any insights?

**Comment by michelleangela** [comment]
@wvc25, the settings **Tools > Options > Cross Platform > C++ > Android** is used by the C++ mobile development component, which supports to up Android SDK 25, therefore the path specifically points to `C:\Microsoft\AndroidSDK\25`. It is independent from Xamarin, which has its own setup for using Android SDKs.

As for the issue of not being able to build the sample project "OpenGL ES application on Android and iOS" from the C++ mobile development component, can you file a bug at https://developercommunity.visualstudio.com and also provide MSBuild Diagnostic logs?

![image](https://user-images.githubusercontent.com/38734287/68795865-a66db700-0606-11ea-90ec-a121bf7a5192.png)

**Comment by wvc25** [comment]
Thanks for the response, @corob-msft .. I did try changing the path in the Cross Platform to that of the Xamarin's path.. the problem is, the build process for the "OpenGL ES application on Android and iOS" example can't seem to write the "\ant\build.xml" in the Xamarin's "C:\Program Files (x86)\Android\android-sdk\tools" folder, whereas it does it with the Cross Platform's "C:\Microsoft\AndroidSDK\25\tools" folder.  As an additional info, I can only write into the Xamarin path if I login as an admin, whereas the Cross Platform path doesn't require it.  And so, I tried the other way around, changing the Xamarin path into the Cross Platform path.  This triggered VS2019 to "fix" the new Xamarin path by downloading the latest Android SDK and Tools.  I believe the Android SDK Manager is tied to the Xamarin path.  So the Cross Platform "C:\Microsoft\AndroidSDK\25" path got updated with the "android-28" SDK and other tools.  However, this time around the build process can't write the "\ant\build.xml" file in the "C:\Microsoft\AndroidSDK\25\tools" folder where it used to be able to do it before the "fix".  Now, I ran out of options to try.

**Comment by michelleangela** [comment]
The Android SDK Manager is only used by the Xamarin component.

Do you run Visual Studio as admin mode? Perhaps running Visual Studio either as admin or not is what's causing the write to file permissions issue.

**Comment by wvc25** [comment]
I already tried both to no avail.  I normally run it as a regular user, but each time I launch the "Tools > Android > Android Device Manager" or the "Tools > Android > Android SDK Manager", I'm prompted to login as an admin, which I can.

Having said that, VS2019 should be able to write to any folder since I login as an admin "whenever" it asks me to.  Just to clarify, the folder "C:\Microsoft\AndroidSDK\25" does not require me to login as an admin to modify it.  I can create a folder in it via Windows Explorer.  Thus, VS2019 shouldn't have a problem writing in it.  As I mentioned earlier, VS2019 can write the "\ant\build.xml" file in it prior to the "fix" brought about by changing the Xamarin path to point to it.  But now that the Adroid SDK Manager updated the "C:\Microsoft\AndroidSDK\25" folder with the android-28 SDK and tools, has that already "contaminated" the C++ mobile development component, which only supports to up Android SDK 25?

**Comment by michelleangela** [comment]
I'm not familiar with how the [Android SDK Manager](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-sdk?tabs=windows) works or writes to folders. It was created to provide Android tools for the Xamarin component. My guess is it could have specific functionality to work for Xamarin but are not intended for other components. The Android Device Manger is also used by Xamarin. Sounds like any tool used by Xamarin causes the required login as admin?

The Android SDK Manager could have overwritten some tools in "C:\Microsoft\AndroidSDK\25" that the C++ mobile development component uses, which could cause build issues for the sample C++ Android/iOS project.

To get the original contents of "C:\Microsoft\AndroidSDK\25", I suggest delete the folder "25" and uninstall and reinstall the C++ mobile development component. Also make sure the Android SDK Manager doesn't point to "C:\Microsoft\AndroidSDK\25" before uninstall/reinstall.

**Comment by wvc25** [comment]
Yes, it does look like Xamarin requires admin privileges in order to be used.  That's definitely bad for marketing since in the corporate world, only a small group of people gets admin access.

You mentioned that the Android Device Manger is also used by Xamarin.  But shouldn't this also be used by the C++ mobile development component in order to launch an Android emulator for testing?  The issue I'm trying to fix now is only the build process, after that I would have to deal with deployment, and I already saw a deployment failed message before.  But I'm trying to isolate the problem by focusing first on the build process.

**Comment by wvc25** [comment]
Okay, I was able to reinstall the C++ mobile development component by following your suggestion and I'm back to getting the original error message below:

1>------ Build started: Project: OpenGLESApp1.Android.NativeActivity, Configuration: Debug x86 ------
1>ANDROID_HOME=C:\\Microsoft\AndroidSDK\25
1>ANT_HOME=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Apps\apache-ant-1.9.3
1>JAVA_HOME=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25
1>NDK_ROOT=C:\\Microsoft\AndroidNDK64\android-ndk-r16b
1>pch.h
1>Cube.c
1>android_native_app_glue.c
1>main.cpp
1>OpenGLESApp1.Android.NativeActivity.vcxproj -> C:\wxWVC\OpenGLESApp1\x86\Debug\libOpenGLESApp1.so
2>------ Build started: Project: OpenGLESApp1.Android.Packaging, Configuration: Debug x86 ------
2>ANDROID_HOME=C:\\Microsoft\AndroidSDK\25
2>ANT_HOME=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Apps\apache-ant-1.9.3
2>JAVA_HOME=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25
2>NDK_ROOT=C:\\Microsoft\AndroidNDK64\android-ndk-r16b
2>ANDROID_NDK_HOME=C:\\Microsoft\AndroidNDK64\android-ndk-r16b
2>Buildfile: C:\wxWVC\OpenGLESApp1\OpenGLESApp1\OpenGLESApp1.Android.Packaging\x86\Debug\Package\build.xml
2>  [taskdef] Could not load definitions from resource anttasks.properties. It could not be found.
2>  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.
2>
2>-set-mode-check:
2>
2>-set-debug-files:
2>
2>-check-env:
2>
2>BUILD FAILED
2>C:\Microsoft\AndroidSDK\25\tools\ant\build.xml:396: Problem: failed to create task or type checkenv
2>Cause: The name is undefined.
2>Action: Check the spelling.
2>Action: Check that any custom tasks/types have been declared.
2>Action: Check that any <presetdef>/<macrodef> declarations have taken place.
2>
2>
2>Total time: 0 seconds
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\MDD\Android\V150\Android.Common.targets(445,5): error MSB3073: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Apps\apache-ant-1.9.3\bin\ant.bat" debug -Dout.final.file="C:\wxWVC\OpenGLESApp1\OpenGLESApp1\OpenGLESApp1.Android.Packaging\x86\Debug\OpenGLESApp1.apk"" exited with code 1.
2>Done building project "OpenGLESApp1.Android.Packaging.androidproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I did try searching for the error messages above in the internet before to try to find a fix myself before posting here, but the error messages seem to be generic as others have already reported them a couple of years back (as far as 2012?).

**Comment by corob-msft** [comment]
@wvc25 

This has turned into a product support question. Unfortunately, we're not equipped for those on the docs team. Since I don't see a specific issue to fix in the documentation to address this, I'm going to close it.

Product support is handled on [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). You can report issues from within Visual Studio directly. See [How to report a problem with Visual Studio or Visual Studio Installer](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) for details. Actual product engineers are notified about issues there, and other community members can comment and suggest solutions. It's what I recommend for issues like yours.
