### ISSUE TITLE
Guidance on MSBuild scripts with both `RoslynCodeTaskFactory` and `CodeTaskFactory`

### ISSUE THREAD

**Issue by augustoproiete** [MicrosoftDocs/visualstudio-docs#4320]
> The `RoslynCodeTaskFactory` is available in MSBuild 15.8 and above only.

It would be great to see documentation/guidance on how to add support for `RoslynCodeTaskFactory` to *existing* MSBuild scripts that already rely on `CodeTaskFactory`, and want to add `RoslynCodeTaskFactory` in order to take advantage of .NET Standard and cross-platform support, whilst still maintaining compatibility with older MSBuild < 15.8...

i.e. Having `RoslynCodeTaskFactory` and `CodeTaskFactory` in the same MSBuild script, and choose one or the other at run-time based on the MSBuild version executing the script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8c66d6-dd9b-dddc-dd69-41d22284ec10
* Version Independent ID: 1b750d67-95da-aa4c-ad32-2de54d7a46c5
* Content: [MSBuild Inline Tasks with RoslynCodeTaskFactory - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2017)
* Content Source: [docs/msbuild/msbuild-roslyncodetaskfactory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-roslyncodetaskfactory.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
I think this can be done using a Condition on the $(MSBuildVersion) property.

**Comment by augustoproiete** [comment]
Thank you @ghogen! Very helpful!
