### ISSUE TITLE
Build errors encountered

### ISSUE THREAD

**Issue by wvc25** [MicrosoftDocs/visualstudio-docs#4324]
Hi @corob-msft, I'm reposting my last update yesterday on the "Install cross-platform mobile development with C++" page into this page as we now focus more on the errors I encountered while building this "OpenGL ES application on Android and iOS" example.

But first, I wish to point out that when launching VS2019 as a normal user, the drop down list that shows the emulated Android device profiles as deployment target will actually not show any available Android device profile, instead it only has a single option that says, "No devices available."  Thus, users must have admin access by default, or at least run VS2019 as administrator in order to see these emulated Android device profiles in the deployment target drop down list.

Now, having installed the "Mobile Development with C++" workload and including the optional "C++ iOS development tools" component, and by simply creating a new project and selecting the "OpenGLES Application (Android, iOS)" example without modifying anything except for the Location folder, here's the build error I'm getting:

1&gt;------ Build started: Project: OpenGLESApp1.Android.NativeActivity, Configuration: Debug x86 ------
1&gt;ANDROID_HOME=C:\\Microsoft\AndroidSDK\25
1&gt;ANT_HOME=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Apps\apache-ant-1.9.3
1&gt;JAVA_HOME=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25
1&gt;NDK_ROOT=C:\\Microsoft\AndroidNDK64\android-ndk-r16b
1&gt;pch.h
1&gt;Cube.c
1&gt;android_native_app_glue.c
1&gt;main.cpp
1&gt;OpenGLESApp1.Android.NativeActivity.vcxproj -&gt; C:\wxWVC\OpenGLESApp1\x86\Debug\libOpenGLESApp1.so
2&gt;------ Build started: Project: OpenGLESApp1.Android.Packaging, Configuration: Debug x86 ------
2&gt;ANDROID_HOME=C:\\Microsoft\AndroidSDK\25
2&gt;ANT_HOME=C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Apps\apache-ant-1.9.3
2&gt;JAVA_HOME=C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25
2&gt;NDK_ROOT=C:\\Microsoft\AndroidNDK64\android-ndk-r16b
2&gt;ANDROID_NDK_HOME=C:\\Microsoft\AndroidNDK64\android-ndk-r16b
2&gt;Buildfile: C:\wxWVC\OpenGLESApp1\OpenGLESApp1\OpenGLESApp1.Android.Packaging\x86\Debug\Package\build.xml
2&gt;  [taskdef] Could not load definitions from resource anttasks.properties. It could not be found.
2&gt;  [taskdef] Could not load definitions from resource emma_ant.properties. It could not be found.
2&gt;
2&gt;-set-mode-check:
2&gt;
2&gt;-set-debug-files:
2&gt;
2&gt;-check-env:
2&gt;
2&gt;BUILD FAILED
2&gt;C:\Microsoft\AndroidSDK\25\tools\ant\build.xml:396: Problem: failed to create task or type checkenv
2&gt;Cause: The name is undefined.
2&gt;Action: Check the spelling.
2&gt;Action: Check that any custom tasks/types have been declared.
2&gt;Action: Check that any &lt;presetdef&gt;/&lt;macrodef&gt; declarations have taken place.
2&gt;
2&gt;
2&gt;Total time: 0 seconds
2&gt;C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\MDD\Android\V150\Android.Common.targets(445,5): error MSB3073: The command ""C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Apps\apache-ant-1.9.3\bin\ant.bat" debug -Dout.final.file="C:\wxWVC\OpenGLESApp1\OpenGLESApp1\OpenGLESApp1.Android.Packaging\x86\Debug\OpenGLESApp1.apk"" exited with code 1.
2&gt;Done building project "OpenGLESApp1.Android.Packaging.androidproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I'm getting this same build error regardless of whether I run VS2019 as a normal user or as an administrator.  Any suggestion what needs to be fixed?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61c068da-293e-ea09-c3ed-be7d3c7da17d
* Version Independent ID: 70af6750-b737-f536-8ebc-ad3a24becb80
* Content: [Build an OpenGL ES application on Android and iOS - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-an-opengl-es-application-on-android-and-ios?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/build-an-opengl-es-application-on-android-and-ios.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wvc25 

I mentioned in #4315 that we don't normally do product support here in the documentation issues forum. It looks to me like your Ant installation or configuration is causing a problem, but I know next to nothing about Ant and can't help. Your best bet is the community. I'll repeat the info on how to report issues and get answers from my earlier comment:

Product support is handled on [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). You can report issues from within Visual Studio directly. See [How to report a problem with Visual Studio or Visual Studio Installer](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) for details. Actual product engineers are notified about issues there, and other community members can comment and suggest solutions. It's what I recommend for issues like yours.

**Comment by wvc25** [comment]
Hi @corob-msft, thanks for the response.  With regards to my Ant installation, please note that all of that came from the VS2019 installation.  I haven't used Ant before so I didn't do any manual installation.  I guess I'm just assuming that if I follow the instructions on this doc, then I'll get the same result as what was documented.  But then I ran into this build process error unexpectedly.  Thus, I think it's fair to say that something is not right, or at least missing, in the documentation, and hopefully someone could check that out.  Thanks!

**Comment by corob-msft** [comment]
@wvc25 
Your expectation about the docs is completely reasonable. We try to write documentation that reflects the way the product is expected to work. And, this particular article does work as expected when I've tried it recently. That doesn't mean it will work correctly for everyone, though. Sometimes the product has a bug, and most likely, it only breaks in some unanticipated situations. That's why the product team needs a repro case: so they can fix the problems that didn't come up in testing that affect only a subset of customers. And that's why recommend you take your issue to [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). It's the place where the developers look for product issues to fix. If as part of their investigation they determine that the documentation needs some specific instructions to address cases like yours, they'll tell us what to include. Until they do, we don't know.
