### ISSUE TITLE
Where is the OpenGLES 2 Application (Android, iOS, Windows Universal) template?

### ISSUE THREAD

**Issue by wvc25** [MicrosoftDocs/visualstudio-docs#4325]
I have installed the "Mobile development with C++" workload with the optional "C++ iOS development tools" component, as well as the "Universal Windows Platform development" workload, but I still don't see the "OpenGLES 2 Application (Android, iOS, Windows Universal)" template when I try to create a new project.  Is there any other optional component that I need to install to see this project template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d4796d-315b-7ac5-c638-f7e77280036f
* Version Independent ID: 965c6d8b-7f63-9708-5d42-e8ed59f28655
* Content: [Cross-platform mobile development with C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-cpp-for-cross-platform-mobile-development?view=vs-2019)
* Content Source: [docs/cross-platform/visual-cpp-for-cross-platform-mobile-development.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/visual-cpp-for-cross-platform-mobile-development.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wvc25 
The VS 2015 version of this template included the UWP projects. In 2017 and 2019, only iOS and Android projects are created by the template. I'll update the documentation accordingly.

**Comment by corob-msft** [comment]
Updated content should appear sometime tomorrow.
