### ISSUE TITLE
What's the implications on package build when including the Analizers from Nuget?

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/visualstudio-docs#4328]
Would this only impacts the project source repo and are used only during build, or do the files or assemblies contained in the nuget package are part of the output of the project in this way increasing the size of the appx (msix) package file?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1e8a4-67b0-57f9-7026-dab24253f7a9
* Version Independent ID: b04dd946-edef-3bbc-ebd1-b6ac43d19689
* Content: [EditorConfig versus analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/analyzers-faq?view=vs-2019&source=docs#feedback)
* Content Source: [docs/code-quality/analyzers-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/analyzers-faq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@JuanMejiaVelez Thank you for the question.

Unless this is an issue specifically with the documentation, the product team would be better apt to respond.  

Please move this to the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) to start a dialogue.
