### ISSUE TITLE
Missing documentation for warning CA2008

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/visualstudio-docs#4329]
I would expect that every warning from FxCopAnalyzer would lead to a clean document explaining the violation and how to fix it. CA2008 does not have a document and clicking on Visual Studio no this warning opens the browser on bing search of "CA2008  C# Do not create tasks without passing a TaskScheduler" which results are not very helpful and they might change over time opening the possibility of misleading developers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84d427d-0ae4-f380-c544-041141e6c541
* Version Independent ID: a4601b4b-bbda-3502-4bbc-e66367781bce
* Content: [Code Analysis for Managed Code Warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-warnings?view=vs-2019#feedback)
* Content Source: [docs/code-quality/code-analysis-for-managed-code-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-for-managed-code-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@JuanMejiaVelez Thank you for the feedback.

This issue is currently active, please refer to https://github.com/MicrosoftDocs/visualstudio-docs/issues/1467.
