### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by zako16** [MicrosoftDocs/visualstudio-docs#433]
Please, you forgot character Visual Sudio Enterprise = >  Visual Studio Enterprise

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c989e4cf-29c4-6cf6-056f-00feca0a6ba1
* Version Independent ID: e6da849a-abd0-de96-d6b5-c94a02ba98de
* [Content](https://docs.microsoft.com/en-us/visualstudio/modeling/create-uml-modeling-projects-and-diagrams#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/modeling/create-uml-modeling-projects-and-diagrams.md)

**Comment by gewarren** [comment]
@zako16 thank you, i will fix it this week.

**Comment by gewarren** [comment]
Fixed in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1314.

**Comment by smoroz** [comment]
!!!!
