### ISSUE TITLE
Explain how to make msbuild respect errors for IDExxxx diagnostics

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#4333]
I tried putting in my `.editorconfig`:

```
[*.{cs,vb}]
dotnet_diagnostic.IDE0067.severity = error
```

In the IDE in the Error List window, it appears as an error. However, when I run `msbuild /r/ m`, the build succeeds (even if I remove `bin` and `obj` first). How do I instruct `msbuild` to properly fail in this situation?

I think this docs page should explain why the behavior I see is expected behavior and also describe how to get `msbuild` to fail when setting the severity to `error`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer rule severity and suppression - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#set-rule-severity-in-an-editorconfig-file)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
@binki You are using VS 2019 16.3 or later? In the doc, looks like this is required. 
@mavasani Manish, do you know why the build might fail with an error in the IDE, but succeed in MSBuild?

**Comment by mavasani** [comment]
Couple of things:

1. IDE diagnostics in default VS install are only for live analysis. These cannot cause build breaks by default - that would be a breaking change for everyone.

2. IDE analyzers currently have VS dependencies, and are not executable on CI. See https://github.com/dotnet/roslyn/issues/33558, which tracks enabling them to execute on CI.

**Comment by binki** [comment]
@Mikejo5000 I am using 16.4.2 currently. When I filed this issue, I am not sure what version I was using, but I normally stay on latest. I know that I was able to get the diagnostics to appear as errors in the IDE but not via MSBuild.

The docs I filed this issue against claim that setting the diagnostic severity to error will cause a command line build time failure. I was hoping the docs could be expanded to explain how to get that to work if it were really possible. From @mavasani’s remarks, it sounds like there are plans to make this possible but that it isn’t currently possible.

**Comment by mavasani** [comment]
> The docs I filed this issue against claim that setting the diagnostic severity to error will cause a command line build time failure. I was hoping the docs could be expanded to explain how to get that to work if it were really possible. From @mavasani’s remarks, it sounds like there are plans to make this possible but that it isn’t currently possible.

@binki Note that all the stuff mentioned in the docs work for all 3rd party analyzers in both CI and live analysis. It also works for IDE analyzers in live analysis. The only missing support is for IDE analyzers to be available as a NuGet package that can run in CI break build.

**Comment by Mikejo5000** [comment]
@mavasani Do you think this warrants a note in the docs? Since the issue may be addressed in the not-too-distant future, I'm inclined to leave the docs as they are.

**Comment by mavasani** [comment]
Yes, we are actively working towards porting IDE rules to a NuGet package, so probably it is fine.

**Comment by Mikejo5000** [comment]
Closing this for now
