### ISSUE TITLE
 Please specify which file is added to the above lines? where is it located?

### ISSUE THREAD

**Issue by TheGridLock** [MicrosoftDocs/visualstudio-docs#4335]
Example: .vbproj File? 
If the project is currently active, can it be edited? I usually select the file then right click and select exclude project

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30273668-658c-d411-5b6d-7f58256bb0f3
* Version Independent ID: c8812ae3-0fb1-a30f-02dd-ebc2d28b9dc8
* Content: [How to: Exclude Files from the Build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-exclude-files-from-the-build?view=vs-2019#feedback)
* Content Source: [docs/msbuild/how-to-exclude-files-from-the-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-exclude-files-from-the-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I think expected procedure is to right-click project, choose Unload Project, then right-click, Edit projectname, if you're editing in VS. So, it appears the project should be unloaded.
For the original question, can you clarify which lines (doc section) you are talking about?

**Comment by TheGridLock** [comment]
Hi,Mikejo5000 The article didn't mention how to use these xml code snippets. where is it located? Where do I need to go to fix it? , You know what I mean. Beginners will not know where to start.

**Comment by Mikejo5000** [comment]
Ah, yes, these are in the MSBuild project files, like .vbproj. There's a lot of more advanced topics here that assume general MSBuild knowledge. For a more beginning article, see 
https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2019
