### ISSUE TITLE
Edit Menu has no Intellisense item

### ISSUE THREAD

**Issue by JoeCodeswell** [MicrosoftDocs/visualstudio-docs#4337]
I am using
Version: 1.40.1 (user setup)
Commit: 8795a9889db74563ddd43eb0a897a2384129a619
Date: 2019-11-13T16:49:35.976Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

This page item 2 titled "To use surround-with code snippets through the Edit menu", says "... From the Edit menu, select IntelliSense and then select the Surround With command."

THERE IS NO IntelliSense item in the Edit menu.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0360876b-37ed-53ac-5b8a-5964574ee41a
* Version Independent ID: 27d1ddfd-0ec9-a6ac-b0f1-34b1f33f004b
* Content: [How to use surround-with code snippets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-use-surround-with-code-snippets?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-use-surround-with-code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-use-surround-with-code-snippets.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by TerryGLee** [comment]
@JoeCodeswell Thanks for your feedback; we'll investigate and respond back soon.

**Comment by DanteGagne** [comment]
@JoeCodeswell I'm sorry it's taken so long to get back to you. Can you confirm for me that you're using Visual Studio and not Visual Studio Code? That could be the cause of your problem.

**Comment by TerryGLee** [comment]
@JoeCodeswell Unfortunately, we cannot repro your issue. 

Either you are using Visual Studio Code instead of Visual Studio, or your cursor isn't in a code window within Visual Studio. 

Having not heard back from you regarding our previous inquiry, we are now closing this issue. Thanks for contacting us, and please do so again if you have any suggestions on how we might improve our documentation.
