### ISSUE TITLE
Online converter tool

### ISSUE THREAD

**Issue by james242** [MicrosoftDocs/visualstudio-docs#434]
There are a few online JSON to CSV converters available if you just need to parse a JSON file without automation.

For example: https://json-csv.com (also useful for debugging purposes).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0546edcb-73f7-f7f4-3d31-b6704916bbc1
* Version Independent ID: fb0b92e0-2d25-9d12-43f3-1e8adead7050
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/json-parse-function-javascript)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/reference/json-parse-function-javascript.md)

**Comment by gewarren** [comment]
@Mikejo5000 Should this info be added to the topic?

**Comment by Mikejo5000** [comment]
@gewarren Yes, I can add that to the topic

**Comment by Mikejo5000** [comment]
Added to the Exceptions section in the discussion about JSON validation.
