### ISSUE TITLE
Mention weird `ExitCode` behavior of the `Exec` task when Output contains `Error:` 

### ISSUE THREAD

**Issue by matthid** [MicrosoftDocs/visualstudio-docs#4340]
We internally encountered basically the same issue as https://github.com/nunit/nunit-console/issues/242
It seems there is some undocumented magic going on in the msbuild `Exec` Task (https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019)
This magic should be documented and the corresponding sections should be extended.
In particular:
- This should be mentioned in the `ExitCode` output parameter that this might not be the actual exit code
- It should be mentioned that the `Exec` Task might fail due to this, even if `CustomErrorRegularExpression` and `CustomWarningRegularExpression` are both unset.
- The behavior of the `Exec`-task should be explained in detail in the remarks section, including examples.

**Comment by rainersigwald** [comment]
That is indeed surprising, but evidently intentional:

https://github.com/microsoft/msbuild/blob/584ca5f11b28971f5651b4b8de5f173ad1cb2786/src/Utilities/ToolTask.cs#L753-L757

I agree that it should be documented (in the `ToolTask` doc section).

**Comment by rainersigwald** [comment]
Ah, it actually is:

https://github.com/MicrosoftDocs/visualstudio-docs/blob/fc3d3be2c6db14bd39ef3e6a37a7187bdc8e920d/docs/msbuild/includes/tooltaskextension-base-params.md#L17
