### ISSUE TITLE
Using simple for loop instead of foreach

### ISSUE THREAD

**Issue by himalayagarg** [MicrosoftDocs/visualstudio-docs#4341]
Why in [this](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-save-attachments-from-outlook-e-mail-items?view=vs-2019) article you are using simple **for** loop instead of **foreach**?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d3bb09-dfe3-f7f1-dc25-6e4a5ff799b4
* Version Independent ID: 02cbe976-d761-16ec-dd17-1a58d9aa64eb
* Content: [Save attachments from Outlook email items programmatically - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-save-attachments-from-outlook-e-mail-items?view=vs-2019)
* Content Source: [docs/vsto/how-to-programmatically-save-attachments-from-outlook-e-mail-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-save-attachments-from-outlook-e-mail-items.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@himalayagarg -- Himalaya, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
