### ISSUE TITLE
Describe solution for classes derived from disposable class

### ISSUE THREAD

**Issue by jameslear** [MicrosoftDocs/visualstudio-docs#4342]
Dispose is one of the more arcane methods for newbies, especially when it is overloaded.  System.Windows.Forms.Form is a common example.  Any chance we could see a sample implementation using a disposable base class with an overloaded Dispose?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c11c2ae2-fde5-91d4-9fd9-b949c8527ede
* Version Independent ID: 6386b34b-5717-55b6-bef0-3cc979f33f0c
* Content: [CA1001: Types that own disposable fields should be disposable - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001)
* Content Source: [docs/code-quality/ca1001.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1001.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22040](https://github.com/dotnet/docs/issues/22040)
