### ISSUE TITLE
Incorrect XML element <StartPrograms>

### ISSUE THREAD

**Issue by carlos-quintero** [MicrosoftDocs/visualstudio-docs#4343]
The &lt;StartPrograms&gt;...&lt;/StartPrograms&gt; is incorrect. It should be &lt;StartProgram&gt;...&lt;/StartProgram&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa63b4dc-21b4-307f-61d3-a13ce9d0475a
* Version Independent ID: de62d1bc-6f08-edf9-9624-fee65b90185e
* Content: [How to Roundtrip Extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-roundtrip-vsixs?view=vs-2019)
* Content Source: [docs/extensibility/how-to-roundtrip-VSIXs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-roundtrip-VSIXs.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @willbrown
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@carlos-quintero -- Carlos, thank you for your feedback.

@madskristensen -- Mads, please review my correction in the above-mentioned PR 5800.

**Comment by madskristensen** [comment]
@WilliamAntonRohm done
