### ISSUE TITLE
Update screenshot to not say Xamarin Studio

### ISSUE THREAD

**Issue by BretJohnson** [MicrosoftDocs/visualstudio-docs#4348]
We should update the screenshot here to not say Xamarin Studio Addin.
The latest version of the addin maker will actually show 3 choices for templates - IDE Extension, IDE Extension Tests, and IDE Library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc52ec0c-7053-51d0-c576-2d8ce60cf198
* Version Independent ID: 8bb8155e-d615-5ea8-cd83-3820f8484b43
* Content: [Extending Visual Studio for Mac Walkthrough - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac-walkthrough?view=vsmac-2019#feedback)
* Content Source: [mac/extending-visual-studio-mac-walkthrough.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/extending-visual-studio-mac-walkthrough.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-sdk**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by msebolt** [comment]
@BretJohnson Thank you for the feedback, assigning this to the author for review.

**Comment by conceptdev** [comment]
For what it's worth, that item – to create an Add-in – appears to be removed altogether in the version of VSMac I have installed (8.3.10(build 2)). I'll leave it to @heiligerdankgesang to decide what to do with this content.

**Comment by heiligerdankgesang** [comment]
@conceptdev is there a way to hide this content, but still retain it for when we revisit?

**Comment by heiligerdankgesang** [comment]
Creation of add-ins are not officially supported in Visual Studio for Mac 2019. I've removed the content from the 2019 docset in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6674

**Comment by heiligerdankgesang** [comment]
#please-close
