### ISSUE TITLE
More detailed information on how to manipulate and/or create/recreate solution files would be salutary

### ISSUE THREAD

**Issue by Diche-Bach** [MicrosoftDocs/visualstudio-docs#435]
For example:
http://www.onjava.com/pub/a/dotnet/excerpt/vshacks_chap1/index.html?page=4

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb0873f-6486-57fb-93db-1bc662cbbfca
* Version Independent ID: 91f46431-09ff-2f01-bd20-e8e1a9490a0b
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/reference/project-and-solution-file-types)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/reference/project-and-solution-file-types.md)

**Comment by gewarren** [comment]
@Diche-Bach Thanks, I will see if there's more information that can/should be added to the topic.

**Comment by gewarren** [comment]
@Diche-Bach We added information about the solution file header here: https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2019#file-header

Also, as noted in [this section](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019#solutions), solution files are not designed to be hand-edited.
