### ISSUE TITLE
ActiveWorkbook.Queries

### ISSUE THREAD

**Issue by mansoureh** [MicrosoftDocs/visualstudio-docs#4354]
I can see there is the property of Queries for Workbook object but apparently it is hidden. Is it possible to activate this property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8bf2638-9046-68cf-8e7a-714c35993cd1
* Version Independent ID: a4a1f2de-ee3b-4e31-9497-0c9f32806d78
* Content: [Work with workbooks - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/working-with-workbooks?view=vs-2019)
* Content Source: [docs/vsto/working-with-workbooks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/working-with-workbooks.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by msebolt** [comment]
@mansoureh Thank you for the question.

Please try creating a query using [Excel's Get and Tranform](https://support.office.com/article/getting-started-with-get-transform-in-excel-a8310388-2a12-438c-9d29-c6d29cb8df6a) and see if this enables the property.

For further information, refer to [Excel.Workbook](https://docs.microsoft.com/office/vba/api/excel.workbook).

**Comment by mansoureh** [comment]
@msebolt Thanks for the reply but unfortunately no; it does not activate the property when trying to use it via Microsoft.Office.Interop.Excel in c#. 
Basically I need to create a Power Query grammatically. I am not sure this is actually possible via Interop.Excel.

**Comment by msebolt** [comment]
@mansoureh Thank you for the update and sorry for the delay.

Unfortunately, this is more a product question and needs to be added [here](https://developercommunity.visualstudio.com/spaces/8/index.html) for a response from the product team.

Please move the issue and link back here.

@John-Hart
