### ISSUE TITLE
/Logger:TfsPublisher looks to be deprecated 

### ISSUE THREAD

**Issue by W0GER** [MicrosoftDocs/visualstudio-docs#4362]
Based on this GitHub posting, it appears the /Logger:TfsPublisher causes VS2017 to fall back to older functionality (eg ResultsDirectory is not supported with /Logger:TfsPublisher) and VS2019 won't support /Logger:TfsPublisher

https://github.com/microsoft/vstest/issues/1739#issuecomment-414669360

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27af73d-196c-4653-aa07-acf7e8b425e3
* Version Independent ID: b8957d80-ffa0-1c42-d3f0-6e4d00bf7a1e
* Content: [VSTest.Console.exe command-line options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019)
* Content Source: [docs/test/vstest-console-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/vstest-console-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by Mikejo5000** [comment]
Fix is live now
