### ISSUE TITLE
A Great Boon for OSS Development

### ISSUE THREAD

**Issue by Chiramisu** [MicrosoftDocs/visualstudio-docs#4364]
Imagine what a great help the Code Maps feature would have in contributing to Open Source projects by enabling the developer to understand the code more quickly. Please consider making this available in the Community edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6a5f0fc-0af8-6023-5b49-f5091a66dca5
* Version Independent ID: 9865696d-778c-4130-f1bc-9a551f15def2
* Content: [Create a visual map of the call stack - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Chiramisu** [comment]
Sorry, I realize now that I probably put this comment in the wrong place. This is not related to documentation. I'll make a feature request instead.

**Comment by Mikejo5000** [comment]
@Chiramisu Thanks for following up!
