### ISSUE TITLE
Case wrong for Command and CommandItem

### ISSUE THREAD

**Issue by BretJohnson** [MicrosoftDocs/visualstudio-docs#4365]
The XML elements `Command` and `CommandItem`, when they appear in the addin.xml file, should be in Pascal case, not all lower case.
Those element names are case sensitive and VSMac will show an error when loading the extension if the names are all lower case as in the current doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d81fd881-9387-165a-846c-37025ccf433b
* Version Independent ID: a0bfdf42-fc87-0b73-8cdb-fb935434be70
* Content: [Extending Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac?view=vsmac-2019)
* Content Source: [mac/extending-visual-studio-mac.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/extending-visual-studio-mac.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-sdk**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by BretJohnson** [comment]
Also: `defaulthandler` should be `defaultHandler`

I just spent a while tracking down an issue caused by that.

**Comment by msebolt** [comment]
@BretJohnson Thank you for the feedback, assigning this to the author for review.

**Comment by msebolt** [comment]
The documentation has been updated, changes should be live in another day or two.

Closing this now, please comment below if there are further issues.
