### ISSUE TITLE
Use two accounts on a connected windows machine

### ISSUE THREAD

**Issue by DennisBaekgaard** [MicrosoftDocs/visualstudio-docs#4366]
I can connect two accounts (personal and work account) two visual studio. I can also connect to my two different azure tenants/subscriptions (completely disconnected from each other).

If I sign out of all accounts, Visual Studio will connect with the work account, which is associated with the laptop /windows login.

So to sum up:

Cloud A, with Account A
and
Cloud B with Account B.

If I try to access Cloud B services with all accounts logged in, I cannot because Account A is used to authenticate against Cloud B, which obviously does not have access. If I log out of Account A and log in with Account B, then it will still default to Account A because of the windows account.

Is it possible to actually have this setup? The actual case is that I have a work laptop on which I work and administrate my works azure services, and develop on these. I also have a personal project for which I would like to use the same laptop, but I'm always signed in with my work-account to the actual computer. 

Can I choose which account visual studio selects as it's default when connecting up against services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d80b776-c83a-2d67-d18d-7dbecc7bc190
* Version Independent ID: b9190b2a-9826-8830-16b0-eb35574b14c9
* Content: [Work with multiple user accounts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/work-with-multiple-user-accounts?view=vs-2019)
* Content Source: [docs/ide/work-with-multiple-user-accounts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/work-with-multiple-user-accounts.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@DennisBaekgaard Thank you for the question.

Please try using either an [Alternate identity](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-alternate-identity) or re-configuring the Credential Manager as per [this post](https://stackoverflow.com/questions/12407668/how-can-i-change-the-default-credentials-used-to-connect-to-visual-studio-online) to see if this solves the problem.

If there are still issues, please provide the details below.

**Comment by msebolt** [comment]
Closing now, comment below if there are issues.
