### ISSUE TITLE
How to attach to ASP.NET Core 3.0 process?

### ISSUE THREAD

**Issue by Deilan** [MicrosoftDocs/visualstudio-docs#4367]
There's a [Attach to the ASP.NET application from the Visual Studio computer](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-computer?view=vs-2019#BKMK_attach), in which it is proposed to attach to `dotnet.exe` process. `dotnet.exe` process is missing in a list of remote processes while trying to debug ASP.NET Core 3.0 after completion all the previous steps, although the app is deployed and working properly and could be browsed. Something is definitely missing or should be updated for that case.

P. S. And the whole article is about remote debug **ASP.NET Core** app, not **ASP.NET** app... But the aforementioned section's title misleads us.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4215ecb-721f-9b0b-66ae-042ffd7c9842
* Version Independent ID: 0d58ec46-8b09-f184-24f3-ac53ac0d1b50
* Content: [Remote Debug ASP.NET Core on a Remote IIS Computer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-computer?view=vs-2019#BKMK_attach)
* Content Source: [docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-aspnet-on-a-remote-iis-computer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@Deilan  Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@Deilan Thanks for the info. It's possible there's been a name change for the process in .NET Core 3. Did you check "Show processes from all users"? I'll dig into this some more.

**Comment by Deilan** [comment]
@Mikejo5000 Yes, I did a check "Show processes from all users" and didn't find `dotnet.exe` process or something like that. 🤷‍♂

**Comment by Mikejo5000** [comment]
I'll ask about this. I would think it would show up as a dotnet.exe process. Given that the app is deployed and running, something in the process list should correspond to your app. Other app types often show up as myappname.exe, you could look for that in case something has been changed in the implementation for .NET Core 3.

**Comment by Mikejo5000** [comment]
@Deilan From the product team: The process name depends on how the app is running/launched. Asp.net core can run in IIS, from a dotnet foo.dll, IIS Express, or as an exe of it’s own. It all depends on how the project was built. How is the app being hosted?

**Comment by Mikejo5000** [comment]
From this article:
https://devblogs.microsoft.com/dotnet/announcing-net-core-3-preview-1-and-open-sourcing-windows-desktop-frameworks/
and the info in this section:
Applications now have executables by default
It seems possible that you would find it under myappname.exe.

**Comment by Mikejo5000** [comment]
Minor doc updates needed in a few spots

**Comment by JAspeling** [comment]
Any update on this? Attaching to a running IIS instance and debugging it should be a simple process and I've been struggling for hours trying to get it to work.

**Comment by Mikejo5000** [comment]
@JAspeling What is the issue you are seeing? App processes in .NET Core 3 may run by default as appname.exe (see link above) instead of dotnet.exe. After some testing, I'm planning a minor doc update. Or is there another issue?

For product support, please open an issue using [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by AlvinRamoutar** [comment]
A consideration for those who followed the guide identified by @Deilan and are trying to debug .NET Core 3 apps:

Ensure your build/publish configuration is set to Debug as mentioned in the article.
![image](https://user-images.githubusercontent.com/22155338/79027266-93312a00-7b59-11ea-8c74-6eccff914ce8.png)

Furthermore, when attaching to a process, look for IIS Worker Processes.
The 'User Name' will appear as **IIS APPPOOL\{application_pool_name}**
Where 'application_pool_name' is the App. pool assigned to your website.
![image](https://user-images.githubusercontent.com/22155338/79027527-88c36000-7b5a-11ea-9905-901b0340a8ca.png)


Tested with Server 2016, IIS 10.0 (1607).

**Comment by Mikejo5000** [comment]
@AlvinRamoutar Thanks for the info. I understand from this that you were able to attach/debug correctly? In ASP.NET Core 3, looks like you can host the app in IIS either in-process or out-of-process, and for debugging attach to w3wp.exe or dotnet.exe, respectively, depending on the hosting model.
See this: 
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#hosting-models
It's not clear to me yet how to configure one or the other, except that the doc says that "Apps published as a single file executable can't be loaded by the in-process hosting model." So for those, you might be connecting to dotnet.exe.

**Comment by AlvinRamoutar** [comment]
@Mikejo5000 Correct; managed to attach and debug as expected.

Unless if I'm mistaken, newly created .NET Core apps should default to In-Process.

Refer to:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-3.1#hosting-models

**Comment by Mikejo5000** [comment]
Thx! Updating doc.
