### ISSUE TITLE
Page is outdated, stuck at the first steps with both VS2017 and VS2019

### ISSUE THREAD

**Issue by adigostin** [MicrosoftDocs/visualstudio-docs#4370]
"Add a Visual Studio Package project item template (on the Solution Explorer, right-click the project node and select Add &gt; New Item, then go to Extensibility &gt; Visual Studio Package). Name the file SimpleProjectPackage"

There is no such thing as a "project item template" there!

Plus, under Extensibility there's no "Visual Studio Package". I only have "VSPackage"; I assume you meant that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8135def2-30e0-d9e4-af54-5a8d3a073c63
* Version Independent ID: fea902ab-e883-51bd-c291-04d1988f37f6
* Content: [Creating a Basic Project System, Part 1 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-a-basic-project-system-part-1?view=vs-2019#feedback)
* Content Source: [docs/extensibility/creating-a-basic-project-system-part-1.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-a-basic-project-system-part-1.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@adigostin Thank you for the question, we apologize for the confusion.

Please note that the **Visual Studio Package** template has been replaced by the **Visual Studio AsyncPackage** template (see [this post](https://developercommunity.visualstudio.com/content/problem/293478/visual-studio-package-template-not-available-on-sd.html)).

Assigning this to the author for review.

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
