### ISSUE TITLE
Activate M365 on existing tenant

### ISSUE THREAD

**Issue by hkusulja** [MicrosoftDocs/visualstudio-docs#4371]
Please document, if it is possible to activate mentioned M365 subscription on existing tenant, not having to open a new .onmicrosoft tenant.
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [The Microsoft 365 benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365#eligibility)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by msebolt** [comment]
@hkusulja Thank you for the feedback, including the author for review.

@evanwindom

**Comment by evanwindom** [comment]
@hkusulja - Thanks for your question.  To activate the Office Developer subscription, a new tenant is required.  I've submitted an update to the article to reflect that.

**Comment by evanwindom** [comment]
@TerryGLee - Please close.

**Comment by TerryGLee** [comment]
@evanwindom Thanks Evan. And @hkusulja Thanks for helping us to improve the documentation!
