### ISSUE TITLE
Edit and Continue not applied

### ISSUE THREAD

**Issue by IngmarBitter** [MicrosoftDocs/visualstudio-docs#4373]
Since recently (one or two VS updates? ago) Visual Studio 2019, now at 16.3.9, ceased to write protect my source files when I start a debugging run of my C# app. When I find an issue and want to fix it with edit and continue, VS is happily allowing me to change the code, even when the app is still running, but none of the changes are applied. And even after breaking I lost connection to the app and need to restart. Now if I remember to pause execution before edits, then edit and continue is fine. 

How do I restore the behavior that VS 2019 will not allow editing while execution is still ongoing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3138d123-1ea6-c9b5-454e-4cd458607b32
* Version Independent ID: 04fa7266-ac4c-f3f6-7ca3-929125f94a36
* Content: [How to: Use Edit and Continue (C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-edit-and-continue-csharp?view=vs-2019)
* Content Source: [docs/debugger/how-to-use-edit-and-continue-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-use-edit-and-continue-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@IngmarBitter Thank you for the feedback.

Please refer to the [Edit and continue](https://docs.microsoft.com/visualstudio/debugger/how-to-enable-and-disable-edit-and-continue?view=vs-2019) settings and see if this changes the behavior.  

Any discrepancies can be reported to the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) using **Report a problem** where you will get both a resolution and updates from the product team.

**Comment by IngmarBitter** [comment]
Thanks, but I already looked at those settings in detail. Nothing there is
about write access locking.

**Comment by msebolt** [comment]
@IngmarBitter Thank you for the update, I apologize for not realizing the article you referenced was the same one I mentioned.

I was able to find an [open issue](https://developercommunity.visualstudio.com/content/problem/717070/edit-and-continue-not-working-2.html) similar this one in the Visual Studio community.

Please see if this addresses the issue and if so you could vote or comment on its adoption.

**Comment by IngmarBitter** [comment]
Sorry, the issue is different. There the problem is "I cannot edit it when
the code is paused due to a breakpoint". I can do that - as long as i do
not touch my keyboard while the app is running. So in my case it is not
edit and continue directly that is broken, but the locking and unlocking of
the IDE for editing is broken.

**Comment by msebolt** [comment]
No problem, though I'm more referring to the statement:

```
Managed Edit and Continue feature is going through a major revamp for the upcoming 16.3 release.  The changes shipped in the first preview and we have been working on stabilization for the later previews.
```

I would add your comments here as this is likely a result of the product team's "stabilization".

**Comment by IngmarBitter** [comment]
ok.
Done.

**Comment by IngmarBitter** [comment]
Why was this closed? Just because I added a comment somewhere else? The
issue is clearly not fixed.
