### ISSUE TITLE
Error message PyLint

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4374]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/72

The comment below was machine-translated.

@ERueffel commented 8 hours ago — with docs.microsoft.com
Hello everybody. Have everything gem. Instructions and get the following error message from PyLint.
The reference assemblies for .NETFramework, Version = v4.0 framework were not found ...
This is likely to happen to anyone who follows this instruction. Could you please publish here how to handle it?
Greeting

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb4711da-9ab9-0341-1c2e-03bc88930cc5
* Version Independent ID: c5119fdb-a5ad-0e64-2bd9-bfa983e1a4f7
* Content: [Python in Visual Studio tutorial step 2, write and run code](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-02-writing-code?view=vs-2019#feedback)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-02-writing-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-02-writing-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
@RaymonGulati1 - Could you take a look at this issue and comment?

**Comment by JoshuaPartlow** [comment]
Appears like this might be an environment issue unrelated to the article. Closing given time open, but please reopen if this is still an issue you think should be addressed.
