### ISSUE TITLE
Expression level preferences, missing defaults

### ISSUE THREAD

**Issue by StevenTCramer** [MicrosoftDocs/visualstudio-docs#4377]
The code sample is missing some of the values and their defaults.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5299f22f-4b0f-9e81-883e-d34b2b520bf2
* Version Independent ID: 6a9db168-c592-29a0-59b7-1ff2f517e558
* Content: [.NET language conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#expression-level-preferences)
* Content Source: [docs/ide/editorconfig-language-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-language-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by jmarolf** [comment]
which defaults are missing?

**Comment by TerryGLee** [comment]
@StevenTCramer Thank for your feedback; we always appreciate information that helps us improve our documentation.

For this specific GitHub Issue, to make it actionable, we'd need a little more information about which defaults are missing, and perhaps some more context around your general task. We've requested such but haven't heard back, and so we'll close this issue for now. 

Please feel free to file a new issue with the requested information. We'd be happy to address it at that time.
