### ISSUE TITLE
What's the '@' character used throughout the examples?

### ISSUE THREAD

**Issue by adigostin** [MicrosoftDocs/visualstudio-docs#4378]
I started reading up on MSBuild and I'm beginning to see examples that use the '@' character, like in the one below. What does this character do? How is is different from '$'?

&lt;CSC Sources = "@(CSFile)"
    OutputAssembly = "$(MSBuildProjectName).exe"/&gt;
&lt;/CSC&gt;

Later edit: I eventually found all special characters explained here: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2019.
I.m.o. it would help mentioning "special characters" with a link to this page early on in the MSBuild documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c46b6520-8c1c-7729-9567-555b448fef7d
* Version Independent ID: ecba013d-aa2c-7c11-c8a0-71e6e7706c2b
* Content: [How to: Reference the Name or Location of the Project File - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-reference-the-name-or-location-of-the-project-file?view=vs-2019)
* Content Source: [docs/msbuild/how-to-reference-the-name-or-location-of-the-project-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-reference-the-name-or-location-of-the-project-file.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I think a link from this topic makes sense. We can plan to add that.

**Comment by Mikejo5000** [comment]
Updating doc.

**Comment by adigostin** [comment]
Thank you!
