### ISSUE TITLE
this page isnt about remote debugging on aZURE

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/visualstudio-docs#4380]
this page isnt about remote debugging on aZURE

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878a2a3e-60ac-aa4e-8166-fdd230d3d87d
* Version Independent ID: e7e9d77b-57c0-cd2b-fb00-a166cbcb7cf4
* Content: [Remote Debug ASP.NET Core on IIS and Azure - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-azure?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@stewa11 Thank you for the feedback.

Please add some details on how Azure is not mentioned.

Two of the article's sections go over [Remote debug on Azure App Service](https://docs.microsoft.com/visualstudio/debugger/remote-debugging-azure?view=vs-2019#remote_debug_azure_app_service) and [Remote debug on Azure VM](https://docs.microsoft.com/visualstudio/debugger/remote-debugging-azure?view=vs-2019#remote_debug_azure_vm).

**Comment by stewa11** [comment]
Hi msebolt,
I appreciate your time responding to me so much that I am also prepared to spend my valuable time improving this document.

In summary:
1) I think the document states what to do and, for me at least, it could be a bit more helpful with something on context and why we are doing this.
2) I anticipated that the document would include actually debugging from VS2019 to Azure. I struggled through on my own and I believe there are 3 options. I always keep a crumb trail of learning and here are my results. If you have an interest then contact me outside of this incident and I will take you through each option.
option 1) VS2019, Debug, Attach to Process - didn’t work
option 2) Cloud Explorer, Start Debugger for the Web App - THIS ONE IS THE ONE THAT WORKED!!
option 3) VS2019, Project Propeties, Debug, for the app, look for a debug process on the server - didn’t work. 

Best Regards
Stew

**Comment by msebolt** [comment]
Thank you for the update, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@stewa11 There are quite a few debugging scenarios for Azure. This topic applies only to debugging an app running on IIS on an Azure VM. There are links to some other Azure topics here. What is your scenario exactly?

**Comment by stewa11** [comment]
Ahhh! I see. Yes I understand that this is debugging on Azure VM. Would it be a good idea to add links to other debugging scenarios. My scenario is debugging code from my PC to a we app hosted on Azure. On the other hand, if you want me to explain what I mean by "the document could do with a bit more context" then let me know. Thank you. Stewart
