### ISSUE TITLE
Wrong Downloads coming from website

### ISSUE THREAD

**Issue by maxcramer** [MicrosoftDocs/visualstudio-docs#4382]
Every time I click to download VS code 2019 for Mac it downloads a program file name vs_enterprise__251865628.1574441020.exe then runs a program called Dr Unarchiver. What is this program and why doesn't VS code 2019 download and run? Please see screen shot of program: 
<img width="822" alt="Screenshot 2019-11-22 17 18 19" src="https://user-images.githubusercontent.com/39188094/69446371-2654f900-0d4c-11ea-9f82-477397ba3d4e.png">

**Comment by WilliamAntonRohm** [comment]
@maxcramer Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by ghogen** [comment]
@maxcramer Where is the link that you're clicking?  I suspect it's not the right link on the site.

**Comment by maxcramer** [comment]
Here, is this wrong?

<img width="1343" alt="Screenshot 2019-11-24 11 52 38" src="https://user-images.githubusercontent.com/39188094/69494233-f5da9f80-0eb0-11ea-982c-fdd324b43dcc.png">

**Comment by maxcramer** [comment]
@WilliamAntonRohm  what do you mean? I am trying to get vs 2019.....

**Comment by WilliamAntonRohm** [comment]
@maxcramer -- my question could have been clearer.  Please provide the URL of the link you're clicking on.

**Comment by ghogen** [comment]
It looks like you're trying to install VS Enterprise for Windows on a Mac.

**Comment by ghogen** [comment]
We'll close this for now.  The correct Mac download is at the bottom right of that page.
