### ISSUE TITLE
To find the path of this (and other) assemblies (dll and exe) in VS 2017 and later, use vswhere.exe

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4387]
This is how to find `TextTransform.exe` using powershell and vswhere.exe

``` powershell
#the path to VSWhere.exe is always in programfiles(x86)

$progFilesx86Path = [System.Environment]::ExpandEnvironmentVariables("%programfiles(x86)%")
$vsWherePath = Join-Path $progFilesx86Path "\Microsoft Visual Studio\Installer\vswhere.exe"

# this tells vswhere to use paths of the latest version of visual studio installed 
# to locate this exe anywhere in those paths, and return a single textual value (not a json object or xml payload)
$ttExe = & $vsWherePath -latest -find **\TextTransform.exe -format value
if (-Not(Test-Path $ttExe)){
	throw "Could not locate TextTransform.exe"
}

#then to invoke a transformation
& "$ttExe"  c:\Source\YourTransform.tt
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8177d9b-f8d7-419e-d81d-ce25a44b084f
* Version Independent ID: 43a69770-1eab-06e1-868c-3d8f1c32716d
* Content: [Generating Files with the TextTransform Utility - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/generating-files-with-the-texttransform-utility?view=vs-2019)
* Content Source: [docs/modeling/generating-files-with-the-texttransform-utility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/generating-files-with-the-texttransform-utility.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@StingyJack Thank you for the feedback, assigning this to the author for review.

**Comment by JoshuaPartlow** [comment]
Closed as this isn't a doc issue. If you'd like to suggest a change to the documentation, please feel free to open a GitHub pull request.

**Comment by StingyJack** [comment]
@JoshuaPartlow  there is a section in the doc that lists default, but possibly incorrect pathing. This is a reliable way to get the path.
