### ISSUE TITLE
This needs an example of how to use this tool with TT files in a sql project

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4388]
it doesnt seem to load something correctly. Perhaps an example of the correct parameters would be helpful
```
error : A processor named 'SqlModelDirectiveProcessor' could not be found for the directive named 'SqlModelDirective'. The transformation will not be run.  The following Exception was thrown:
System.IO.FileNotFoundException: Failed to load directive processor SqlModelDirectiveProcessor.
   at Microsoft.VisualStudio.TextTemplating.CommandLine.CommandLineHost.ResolveDirectiveProcessor(String processorName)
   at Microsoft.VisualStudio.TextTemplating.Engine.ProcessCustomDirectives(ITextTemplatingEngineHost host, TemplateProcessingSession session, ITelemetryScope scope, IEnumerable`1 directivesToBeProcessed)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8177d9b-f8d7-419e-d81d-ce25a44b084f
* Version Independent ID: 43a69770-1eab-06e1-868c-3d8f1c32716d
* Content: [Generating Files with the TextTransform Utility - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/generating-files-with-the-texttransform-utility?view=vs-2019)
* Content Source: [docs/modeling/generating-files-with-the-texttransform-utility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/generating-files-with-the-texttransform-utility.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@StingyJack Thank you for the feedback, assigning this to the author for review.

Please see if installing the latest `Microsoft.Net.Compilers` package as described in [this post](https://stackoverflow.com/questions/32505209/how-can-i-use-latest-features-of-c-sharp-v6-in-t4-templates) resolves the issue.

**Comment by StingyJack** [comment]
@msebolt Thanks for the suggestion, but this is for the TextTransform.exe standalone exe.

**Comment by JoshuaPartlow** [comment]
@gewarren - Do you have any insight into this issue or have a contact we could add?

**Comment by gewarren** [comment]
I think the last contact I had for modeling was @mgoertz-msft .

**Comment by mgoertz-msft** [comment]
AFAIK, this is only supported inside of Visual Studio, i.e. devenv.exe.

**Comment by StingyJack** [comment]
That's a shame. Anywhere that's documented?

**Comment by j-martens** [comment]
Not at this time, @StingyJack.  We appreciate the suggestion and I have added it to our backlog.  It will require investigation into what needs to happen or if it’s even possible. Thank you for being a valued customer.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
