### ISSUE TITLE
Needs documentation on how to do this without Visual Studio

### ISSUE THREAD

**Issue by vadim82** [MicrosoftDocs/visualstudio-docs#4389]
It would be nice if this article had instructions on how to do this via the Azure CLI or Azure powershell SDK. Not everyone uses Visual Studio for their development. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eaada6ef-a5cc-f152-860c-48238f9019d3
* Version Independent ID: 5f907b9e-a5b3-6e89-b8b6-3fa034ceecd0
* Content: [Deploy ASP.NET Docker container to ACR registry - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/hosting-web-apps-in-docker?view=vs-2019&viewFallbackFrom=aspnetcore-3.0#feedback)
* Content Source: [docs/containers/hosting-web-apps-in-docker.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/hosting-web-apps-in-docker.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by msebolt** [comment]
@vadim82 Thank you for the feedback, assigning this to the author for review.

In the interim, please refer to [this article](https://docs.microsoft.com/archive/msdn-magazine/2018/april/azure-deploying-containerized-asp-net-core-applications-to-azure) on MSDN.

**Comment by ghogen** [comment]
This is out of scope for the Visual Studio content - the Azure App Service docs should cover the use of the other tools you mentioned, e.g. https://docs.microsoft.com/en-us/azure/container-instances/container-instances-quickstart

However, I can add a link.

**Comment by ghogen** [comment]
I added a link to how to do this with the Azure CLI in the See Also section.

**Comment by ghogen** [comment]
Should go live later today.
