### ISSUE TITLE
What does ERRORCODE 3010 stands for?

### ISSUE THREAD

**Issue by moerwald** [MicrosoftDocs/visualstudio-docs#4390]
Please add a description whats to reason to check for ERRORCODE 3010.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@moerwald Thank you for the feedback.

A note has been added to the documentation and is pending review.

Please refer to [MsiExec.exe error messages](https://docs.microsoft.com/windows/win32/msi/error-codes).
