### ISSUE TITLE
NOT for Xamarin.Forms

### ISSUE THREAD

**Issue by jeffc111a** [MicrosoftDocs/visualstudio-docs#4397]
This page incorrectly states that the designer works for Xamarin.Forms, which has only a Previewer, where xaml must all be hand-written.
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/xaml-basics/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeeb6491-1f2c-73a7-fef2-afb69fd08948
* Version Independent ID: 7e3209b0-a116-3488-a80f-993edf9515a4
* Content: [XAML Designer overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/creating-a-ui-by-using-xaml-designer-in-visual-studio?view=vs-2019)
* Content Source: [docs/xaml-tools/creating-a-ui-by-using-xaml-designer-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/creating-a-ui-by-using-xaml-designer-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@jeffc111a Thank you for the feedback, assigning this to the author for review.

**Comment by TerryGLee** [comment]
@jeffc111a Thanks again for the feedback. We are going to update this page to say the following:

"Xamarin.Forms does not support a XAML designer. To view your Xamarin.Forms XAML UIs and edit them while the app is running, use XAML Hot Reload for Xamarin.Forms. For more information, see the [XAML Hot Reload for Xamarin.Forms (Preview)](https://docs.microsoft.com/xamarin/xamarin-forms/xaml/hot-reload) page."

The update will be published this afternoon after 4:00 P.M. Pacific Standard Time.

**Comment by fprimex** [comment]
> WPF, UWP, and Xamarin.Forms apps.

The note was added, but some incorrect text is still there. I was so incredibly excited that designer was going to finally support forms, only to be crushed a paragraph later :(

**Comment by TerryGLee** [comment]
@fprimex Thanks for the follow-up. We've fix the text in the first paragraph before the note, so that your experience isn't repeated by another.
