### ISSUE TITLE
"To link the tests to the object or library files." does not lead to the mentioned info.

### ISSUE THREAD

**Issue by kkluwehkg** [MicrosoftDocs/visualstudio-docs#4399]
The above link "To link the tests to the object or library files." does not lead to the mentioned info respectively flows into circular reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18bdf17-06e1-aaf2-b6ce-c606c0e260da
* Version Independent ID: bd627b8f-54f0-84e0-55cd-285597af022d
* Content: [Write unit tests for C/C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2019)
* Content Source: [docs/test/writing-unit-tests-for-c-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/writing-unit-tests-for-c-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by msebolt** [comment]
@kkluwehkg Thank you for the feedback, please refer to [this section](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp?view=vs-2019#same_project).

The documentation has been updated and is pending review.
