### ISSUE TITLE
Scope for .NET naming conventions for EditorConfig?

### ISSUE THREAD

**Issue by LukeOwlclaw** [MicrosoftDocs/visualstudio-docs#4400]
Is it possible to distinguish the scope for .editorconfig naming rules?

I'd like to **allow** public fields in structs:

    public struct MyStruct
    {
        public int StructField;
    }

But **disallow** public fields in classes:

    public class MyClass
    {
        public int ClassField;
    }

Is this possible using .editorconfig naming rules?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b402d2e0-a53a-b61a-4da8-b5ee766d9301
* Version Independent ID: 612695df-5934-d967-d709-500ce02b1395
* Content: [.NET Naming Conventions For EditorConfig files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-naming-conventions?view=vs-2019)
* Content Source: [docs/ide/editorconfig-naming-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-naming-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@LukeOwlclaw Thank you for the contacting Microsoft Docs.

Since the question is more geared to the product, please start a thread with the product team [here](https://developercommunity.visualstudio.com/spaces/8/index.html) and link back to this issue.

@jillre
