### ISSUE TITLE
linux or windows

### ISSUE THREAD

**Issue by MohammadMQ** [MicrosoftDocs/visualstudio-docs#4401]
When creating the "ASP.NET Core Web Application" and then "Web App" you will have the choice to choose Windows or Linux docker. I guess the choice will depend on what OS you are on. 
Second thing is what if you already have an existing ASP.NET Core Web Application that you would like to enable on docker, how is that possible?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6e74c3-2796-a2c3-ce35-18767cecb702
* Version Independent ID: 60d27ba1-d713-23dc-93ec-b72feda17016
* Content: [Debug apps in a local Docker container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/edit-and-refresh?view=vs-2019#feedback)
* Content Source: [docs/containers/edit-and-refresh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/edit-and-refresh.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by msebolt** [comment]
@MohammadMQ Thank you for the feedback and question, assigning this to the author for review of the documentation.

For product-related questions regarding Docker, please start a thread [here](https://developercommunity.visualstudio.com/spaces/8/index.html) for feedback from the product team.

**Comment by ghogen** [comment]
A fix for this will appear shortly.
