### ISSUE TITLE
Mention LoggerRunSettings

### ISSUE THREAD

**Issue by rossng** [MicrosoftDocs/visualstudio-docs#4402]
This page should document the [`<LoggerRunSettings>` element](https://github.com/abhishkk/vstest-docs/blob/master/RFCs/0016-Loggers-Information-From-RunSettings.md). It might also be useful to note that the user can see which loggers are available to them by running `vstest.console.exe /ListLoggers`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#feedback)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@rossng Thank you for the feedback, assigning this to the author for review.

**Comment by sdepouw** [comment]
I would like to show my support for this feature. The `<LoggerRunSettings>` is a critical element in order to get Test Explorer to actually log results. With the samples provided in the current documentation there is no clear direction on what you have to do in order to actually start generating test results. (In my case, it was for a .NET Core project using the XUnit test adapter -- no results are generated.)

Noting the available loggers from `vstest.console.exe /ListLoggers` would also be greatly beneficial.

**Comment by Mikejo5000** [comment]
@AbhitejJohn Should we add content for <LoggerRunSettings> to this doc? What do you suggest?

**Comment by AbhitejJohn** [comment]
I agree. Tagging @nohwnd and @cvpoienaru to help with this. Maybe we could automate bubbling in new features in vstest-docs to docs.microsoft.com so they are more visible.

@rossng , would you mind filing an issue for the /listloggers ask at https://github.com/Microsoft/vstest/issues please?

**Comment by rossng** [comment]
It looks like VSTest already have a mention of `/ListLoggers` in their docs: https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019

I'm happy to file an issue but not exactly sure what I would be asking of them.

**Comment by AbhitejJohn** [comment]
@rossng : ah never mind. I thought that wasn't supported. Looks like that documentation has been updated then which is good.

**Comment by Mikejo5000** [comment]
LoggerRunSettings was added to the doc in MicrosoftDocs/visualstudio-docs#5483
