### ISSUE TITLE
Add documentation for the static graph feature

### ISSUE THREAD

**Issue by dtrailin** [MicrosoftDocs/visualstudio-docs#4403]
Static graph for compilation were introduced in 16.3 but there is no documentation showing that this feature is available or how to use it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed74b634-19be-61b4-ad2e-9520b1a89502
* Version Independent ID: e52821c5-306c-6cc4-4a37-ce8bb35b4539
* Content: [What's New in MSBuild 16.0 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/whats-new-msbuild-16-0?view=vs-2019)
* Content Source: [docs/msbuild/whats-new-msbuild-16-0.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/whats-new-msbuild-16-0.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@dtrailin Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@dtrailin Thanks, it sounds like we need an addition to this topic.

**Comment by rainersigwald** [comment]
@cdmihai, we promoted the graph API out of experimental. Are we ready to document the behaviors and command-line options too?

**Comment by rainersigwald** [comment]
And for future reference, here's the dev spec for the graph features: https://github.com/microsoft/msbuild/blob/master/documentation/specs/static-graph.md

**Comment by cdmihai** [comment]
I would hold off until we augment it to support more complex scenarios like nuget pack. When it supports nuget pack there'll be a high chance it will support most runtime graph patterns :).

**Comment by ghogen** [comment]
Lower priority per discussion here.

**Comment by ghogen** [comment]
Closing this issue, which is really a work item that hasn't been scheduled yet. Eventually, this work will be done, but no need to track this as an issue.
