### ISSUE TITLE
Please explain each Scope.

### ISSUE THREAD

**Issue by mkamoski** [MicrosoftDocs/visualstudio-docs#4404]
...

Please describe "Scope" for the following:

module

resource

type

member

...and show an example of each, for the sake of clarity.

Thanks.

Mark Kamoski

...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517e8321-aa13-0814-3398-9606d7c2664b
* Version Independent ID: 59efa3c4-ceaf-a384-94af-0f76584efe3f
* Content: [Suppress code analysis warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019&source=docs#feedback)
* Content Source: [docs/code-quality/in-source-suppression-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/in-source-suppression-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@mkamoski Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@mavasani Are there descriptions we should add here? For module and resource? type and member seem more intuitive. An example of each seems like a "nice to have" addition, but lower priority.

**Comment by mavasani** [comment]
Module scope is basically an assembly level/global suppression that applies to the entire project.

Resource scope was defined in [legacy FxCop](https://docs.microsoft.com/en-us/visualstudio/code-quality/static-code-analysis-for-managed-code-overview?view=vs-2019), and was applicable to diagnostics that it produced in resource files that were part of the module/assembly. This scope is not read/respected in C#/VB compilers for Roslyn analyzer diagnostics, which only analyzes source files.

**Comment by Mikejo5000** [comment]
Thanks! I'll update the doc.
