### ISSUE TITLE
Could it be possible to document how FastUpToDateCheck works

### ISSUE THREAD

**Issue by Socolin** [MicrosoftDocs/visualstudio-docs#4405]
In the documentation for `DisableFastUpToDateCheck` there is mention of `FastUpToDateCheck` but I cannot find any documentation about that.

It would be great to document this one and let people write csproj compatible with that feature instead of having to disable this.

After some search I've found there are few attributes that seems to be used

- UpToDateCheckInput
- UpToDateCheckBuilt
- UpToDateCheckOutput

But I can't found anything about how to use those.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@Socolin Thank you for the feedback, assigning this to the author for review.

**Comment by rainersigwald** [comment]
I don't think there's any documentation on docs.microsoft.com, but there is some documentation here: https://github.com/dotnet/project-system/blob/master/docs/up-to-date-check.md
