### ISSUE TITLE
VS2019: Outdated HKLM\<Application ID Registry Root>\SolutionPersistence\AggregateGUIDs reference

### ISSUE THREAD

**Issue by ArjayHawco** [MicrosoftDocs/visualstudio-docs#4406]
Doesn't look like the project types are stored in the registry key under the above location any longer.  I've got VS 2019 installed, but there are no related keys anywhere related to Visual Studio.  I do have SQL Server Management Studio installed and can find references to 2150E333-8FDC-42A3-9474-1A3956D46DE8 which is a solution folder.

Given that the project type GUIDs are no longer in the registry, it would be helpful if this article listed the project type GUIDs and a short description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9177b266-5055-95d6-407f-ca4aad75257a
* Version Independent ID: 4586847b-d990-df3b-4cce-bd9a471eda33
* Content: [Solution (.Sln) file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file?view=vs-2019#feedback)
* Content Source: [docs/extensibility/internals/solution-dot-sln-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/solution-dot-sln-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@ArjayHawco Thank you for the feedback, assigning this to the author for review.

**Comment by wplong11** [comment]
> When the environment reads the GlobalSection('name') tag, it maps the name to a VSPackage using the registry. The key name should exist in the registry under [HKLM\<Application ID Registry Root>\SolutionPersistence\AggregateGUIDs]. The keys' default value is the Package GUID (REG_SZ) of the VSPackage that wrote the entries.

Where can I find a list of name?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
