### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by OysteinHH** [MicrosoftDocs/visualstudio-docs#4408]
There's should be a ) between typeof(TestClass) and .Deserialize.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfb766f-3790-89d3-8288-3241a975e87f
* Version Independent ID: d5f89f0b-5388-f4d8-3abc-f1b3d5e08564
* Content: [CA5369: Use XmlReader for Deserialize - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca5369?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca5369.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca5369.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @filipsebesta
* Microsoft Alias: **filipse**

**Comment by msebolt** [comment]
@OysteinHH Thank you for the feedback.

The documentation has been updated and is pending review.
