### ISSUE TITLE
Error in App.config

### ISSUE THREAD

**Issue by mariusbancila** [MicrosoftDocs/visualstudio-docs#4409]
In the beginning of the article you specify the following section:

`<section name="microsoft.visualstudio.testtools" type="Microsoft.VisualStudio.TestTools.UnitTesting.TestConfigurationSection, Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions" />`

But in the final App.config that you list it appears as follows:

`<section name="microsoft.visualstudio.testtools" type="Microsoft.VisualStudio.TestTools.UnitTesting.TestConfigurationSection, Microsoft.VisualStudio.QualityTools.UnitTestFramework, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"/>`

The latter one is wrong and should be replaced with what you have specified first.

This is the article: https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-using-a-configuration-file-to-define-a-data-source?view=vs-2019

**Comment by msebolt** [comment]
@mariusbancila Thank you for the feedback.

Please provide a link to the article referenced above for a fix to be made.

**Comment by mariusbancila** [comment]
I did not realize the link was not automatically available. What is the point of having the comments in github if they there not able to identify the docs article they are referring to?

Anyways, here is the article: https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-using-a-configuration-file-to-define-a-data-source?view=vs-2019

**Comment by WilliamAntonRohm** [comment]
@jillre -- Jill, please review the above-mentioned PR 5891.

**Comment by WilliamAntonRohm** [comment]
@jillre -- Jill, please review the above-mentioned PR 5891.

**Comment by TerryGLee** [comment]
@Mikejo5000 Please take a look at this
