### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by JasperE84** [MicrosoftDocs/visualstudio-docs#4410]
contact.Items can also contain DistItems in which case the code will fail. 
See https://stackoverflow.com/questions/59049623/outlook-vsto-plugin-stops-executing-while-iterating-over-contacts-in-default-con

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5ca3007-5e19-b843-32ac-0327813632e4
* Version Independent ID: 1c96468e-5519-1e86-3c00-fc11e795046d
* Content: [Find an email address in contacts programmatically - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-search-for-an-e-mail-address-in-contacts?view=vs-2019)
* Content Source: [docs/vsto/how-to-programmatically-search-for-an-e-mail-address-in-contacts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-search-for-an-e-mail-address-in-contacts.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by msebolt** [comment]
@JasperE84 Thank you for the feedback, assigning this to the author for review.

**Comment by John-Hart** [comment]
The sample has been fixed.  Thanks @JasperE84 for the feedback
