### ISSUE TITLE
Problem with the Hello World sample code

### ISSUE THREAD

**Issue by csolizoltan** [MicrosoftDocs/visualstudio-docs#4411]
I've had a problem with the code snippet in the "The Hello World of IntelliTest" section:
If instead of "[TestClass] public partial class HelloWorldTest" I use "[PexClass] public partial class HelloWorldTest" the test run in correct way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd1b2f6-e89f-ecdb-0060-de0c7e43d110
* Version Independent ID: 9195e48c-d85e-d940-519a-c3642d17aa33
* Content: [Overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/intellitest-manual/introduction?view=vs-2017#feedback)
* Content Source: [docs/test/intellitest-manual/introduction.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/intellitest-manual/introduction.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by csolizoltan** [comment]
Sorry, you are right:

1. Create a new Unit Test Project (.NET Framework) with VS 2017
1. Add Microsoft.Pex.Framework to references
1. Replace the content of the test class with the code snippet from the "The Hello World of IntelliTest" section
1. Delete Microsoft.VisualStudio.TestPlatform.TestFramework and Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions references
1. Add Microsoft.VisualStudio.QualityTools.UnitTestFramework reference to the project

After that the tests are generated successfully.

**Comment by msebolt** [comment]
@csolizoltan Thank you for the feedback and for providing the work-around.

A note will be added to the documentation.
