### ISSUE TITLE
auto-reloading of .py files

### ISSUE THREAD

**Issue by genegc** [MicrosoftDocs/visualstudio-docs#4414]
In the answer to "Question: What's the difference between using the Debug menu commands and the server commands on the project's Python submenu?"
it would be helpful to also point out when you start the server with the python submenu you get the advantage of having changes to .py files auto-loaded - so you can check changes without restarting the server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bb4dc5-b036-60f4-37aa-8b28b092cac9
* Version Independent ID: 06f64682-5a5a-2aa8-face-14ecc6823038
* Content: [Learn Django tutorial in Visual Studio, step 1, Django basics](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-01-project-and-solution?view=vs-2019#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-01-project-and-solution.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-01-project-and-solution.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by msebolt** [comment]
@genegc Thank you for the feedback, assigning this to the author for review.

**Comment by Anapo14** [comment]
@int19h could you add some thoughts here? Thanks!

**Comment by int19h** [comment]
I'm not familiar with how the menu does it, but by the sound of it, it starts the server without applying any settings from project properties to it? (in particular, the bits that suppress auto-reload, because VS doesn't support multiproc auto-attach)

**Comment by JoshuaPartlow** [comment]
Thank you for your input. We will go ahead and close this issue, but continue to track the work internally for upcoming updates to the tutorial.  If you think this issue should remain open, please reopen it with a comment explaining why. Tag me for visibility.
