### ISSUE TITLE
More questions to clarify...

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/visualstudio-docs#4415]
- If a CSP customer buys a monthly subscription, is it billed immediately, or later?
 - Is there a cancellation period, and if so how long for and how do you cancel? (For example, EU distance selling regulations require a 14-day cancellation period, see https://europa.eu/youreurope/citizens/consumers/shopping/guarantees-returns/index_en.htm)
 - Is there any way to change the permissions so a CSP customer cannot purchase a subscription?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 919bdcfd-bb8a-a0c5-8a57-fd713889e849
* Version Independent ID: 1fe48f30-7069-d58f-5207-07b58b01d1fa
* Content: [How to purchase Visual Studio cloud subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-overview#who-can-buy-visual-studio-cloud-subscriptions)
* Content Source: [subscriptions/vscloud-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-overview.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by msebolt** [comment]
@jtuliani Thank you for the questions, assigning this to the author for review.

@evanwindom

**Comment by tfosmark** [comment]
@jtuliani You can contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/) regarding your questions. ​

**Comment by evanwindom** [comment]
@jtuliani - Thanks for your patience.  
Monthly subscriptions are billed starting on the first of the month AFTER purchase, and on the first of the month thereafter.  To block a customer from making changes, demote them to "contributor" in the underlying Azure subscription.

**Comment by evanwindom** [comment]
@jtuliani -- On the subject of cancellations --- there's no automated process around that.  Customers desiring to cancel and obtain a refund can contact support to make that request.

**Comment by evanwindom** [comment]
@TerryGLee - Please close
