### ISSUE TITLE
Location of setting has changed

### ISSUE THREAD

**Issue by orfeasa** [MicrosoftDocs/visualstudio-docs#4419]
The setting is now at File --&gt; Preferences --&gt; Color Theme

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e23c15-7abd-d973-48c0-e4b23e305c5c
* Version Independent ID: 97329301-f6ac-4cba-8b85-a958a0bfc1a5
* Content: [Set color theme and fonts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-personalize-the-ide?view=vs-2019)
* Content Source: [docs/ide/quickstart-personalize-the-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-personalize-the-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by gregvanl** [comment]
Hi @orfeasa Could you be confusing Visual Studio Code, which does use File > Preferences > Color Theme, with Visual Studio IDE? The topic referenced in this issue is for VS IDE and changing the color theme is still done with the Tools > Options dialog as of release 16.3.

**Comment by orfeasa** [comment]
Ah yes, sorry about that 🙂

**Comment by gregvanl** [comment]
No worries. Closing.
