### ISSUE TITLE
Excellent Introduction

### ISSUE THREAD

**Issue by KennethThomasRose** [MicrosoftDocs/visualstudio-docs#442]
The first tutorial in the Visual Studio Documentation is at exactly the right level for an experienced programmer to get a feel for the development environment

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2376dee-30e0-850f-7572-6d32b351be3f
* Version Independent ID: 9c06f47f-8195-4736-3575-fffe1c51f763
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/tutorial-csharp-aspnet-core#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/tutorial-csharp-aspnet-core.md)

**Comment by gewarren** [comment]
@KennethThomasRose thanks for leaving this nice feedback for @TerryGLee !

**Comment by Victex** [comment]
@ Bob LaBonte - 1st one that I tried and succeeded to finish with VS2017 Community - Worked Great Thanks Only problem, had no vertical lines in the About.cshtml

**Comment by TerryGLee** [comment]
@ Bob LaBonte - Do you mean that you don't see vertical lines in the code window? If so, here's how to get them to show: From the **Tools** menu, click **Options**. Expand **Text Editor**, click **General**, and then click to select **Show structure guide lines**.
