### ISSUE TITLE
Release notes VS 2019 16.4.0 typo

### ISSUE THREAD

**Issue by Styxxy** [MicrosoftDocs/visualstudio-docs#4431]
Small typo in https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes?source=docs#16.4.0

> .NET Productivity additions in this release include the ability to configure the severity level of a code style rule directly in the error list, Find All References now has the option to group by type and member, and a refacotring to make a local function static and pass in variables defined outside of the function to the function's declaration and calls.

"refacotring" seems to be the typo --> refactoring

**Comment by AmandaSilver** [comment]
Appears to be fixed. #please-close
