### ISSUE TITLE
Sample .editorconfig not up-to-date

### ISSUE THREAD

**Issue by brads55** [MicrosoftDocs/visualstudio-docs#4432]
The sample .editorconfig on this pages states:

    "here is an example .editorconfig file with the default options"

However it is missing the defaults for some of the newer options like csharp_style_prefer_switch_expression. It would be good if this could be updated (and kept up to date), as it provides a good starting point to ensure nothing is missed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by TerryGLee** [comment]
@brads55 Thanks for your suggestion; we've placed it in the queue for an update.

**Comment by oliverjanik** [comment]
Is there a reference for all the properties that exist for C# and .net ?

**Comment by danstur** [comment]
Switching from old ReSharper configurations to editorconfig having a list of all the available values would be exceedingly helpful. Since this seems hard to keep up-to-date in the documentation, is there maybe a source file that would list all these options?

**Comment by BukeMan** [comment]
why not just put here the same .editorconfig as in .NET CoreFX github repository?
link: https://github.com/dotnet/runtime/blob/master/.editorconfig

**Comment by TerryGLee** [comment]
@brads55 Thanks again for your suggestion; we've replaced the example .editorconfig file in the [Example EditorConfig file](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019#example-editorconfig-file) section with one that we've created by using the recent [version 16.5 release](https://docs.microsoft.com/visualstudio/releases/2019/release-notes).

And for more information about what's listed in the example, please see the links that are listed in the [Convention categories](https://docs.microsoft.com/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019#convention-categories) section of the page.
