### ISSUE TITLE
Specify that this is depricated

### ISSUE THREAD

**Issue by JoshuaHillerup** [MicrosoftDocs/visualstudio-docs#4433]
Now that .Net Core 3+ has replaced .Net Framework, all the pages for Microsoft Fakes should be marked as legacy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b356f491-a828-65ee-915b-b1ccdf71024c
* Version Independent ID: 3fa9dddf-b328-8e2f-c7b2-016a38f71bf6
* Content: [Using shims to isolate your application for unit testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing?view=vs-2019#feedback)
* Content Source: [docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by ghogen** [comment]
@JoshuaHillerup Can you contact me internally - ghogen at microsoft.com - I have some questions about this.

**Comment by JoshuaHillerup** [comment]
> @JoshuaHillerup Can you contact me internally - ghogen at microsoft.com - I have some questions about this.

Emailed

**Comment by ghogen** [comment]
As I understand it, Microsoft Fakes is still a supported framework that supports .NET Framework, but not .NET Core.  .NET Framework is not legacy, it's a supported technology.
