### ISSUE TITLE
Some corrections in the documentation

### ISSUE THREAD

**Issue by Hari-Prasad-V** [MicrosoftDocs/visualstudio-docs#4436]
1) Since the project name is DynamicMenuItems, the "guidDynamicMenuPackageCmdSet" should be "guidDynamicMenuItemsPackageCmdSet" in all the code snippets.
2) Under "Add the command" section, "DynamicMenuPackage.cs" should be "DynamicMenuItemsPackage.cs"
3) In "DynamicMenu.cs" which is created using Add New Item -&gt; Command Sample, it uses AsyncPackage instead of Package, so the "package" and the "ServiceProvider" members should be changed accordingly.
4) In the sections "Add the command", "Implement the handlers" and "Implement the command ID match predicate", following should be changed:
DynamicMenuPackageGuids.guidDynamicMenuPackageCmdSet to DynamicMenuItemsPackage.guidDynamicMenuItemsPackageCmdSet
and
DynamicMenuPackageGuids.cmdidMyCommand to DynamicMenuItemsPackage.cmdidMyCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2c56b13-124c-4a9d-cbb8-6e98c468bb82
* Version Independent ID: 852cf409-c76b-360b-22cc-c675fc7259fa
* Content: [Dynamically Adding Menu Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/dynamically-adding-menu-items?view=vs-2019#feedback)
* Content Source: [docs/extensibility/dynamically-adding-menu-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/dynamically-adding-menu-items.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@Hari-Prasad-V Thank you for the feedback, assigning this to the author for review.

Before any files are re-named, you might just opt to re-name the project `DynamicMenu`.  Then files with `Packages` and `Items` in the name have more meaning.

From the statements above, it seems that item 3 is the only one causing issues with running the tutorial.

**Comment by Hari-Prasad-V** [comment]
@msebolt thanks for the suggestion. I feel renaming the project to `DynamicMenu` would make the documentation a little confusing, since the project also requires us to add a Command sample named as `DynamicMenu`

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
