### ISSUE TITLE
i can't create .net core 3.1 project by mac vs

### ISSUE THREAD

**Issue by iMaxSys** [MicrosoftDocs/visualstudio-docs#4438]
i can't create .net core 3.1 project by mac vs

**Comment by msebolt** [comment]
@iMaxSys Thank you for the feedback.

Can you verify you have the required installations (Mac 8.4 Preview 2) as per [this post](https://devblogs.microsoft.com/dotnet/announcing-net-core-3-1-preview-3/)?

**Comment by iMaxSys** [comment]
thx
