### ISSUE TITLE
Decent evolution of the example

### ISSUE THREAD

**Issue by PhillRoyle** [MicrosoftDocs/visualstudio-docs#4441]
I like that the example gets more complex gradually, and also throws in a few nice bits of syntax (the 'out' in while loop, and '{0:0.##}' were new to me.
If you're going to validate input though, surely validate the choice of operator too? You could have introduced enums too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@PhillRoyle Thanks for your feedback; we appreciate both it and the suggestions on how to improve the document. We'll keep these suggestions on file for a future update to the document. Thanks again!
