### ISSUE TITLE
What is new in MSBuild 16

### ISSUE THREAD

**Issue by qub1n** [MicrosoftDocs/visualstudio-docs#4443]
So what new features or bugfixes are in MSBuld 16? Why I should upgrade?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed74b634-19be-61b4-ad2e-9520b1a89502
* Version Independent ID: e52821c5-306c-6cc4-4a37-ce8bb35b4539
* Content: [What's New in MSBuild 16.0 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/whats-new-msbuild-16-0?view=vs-2019)
* Content Source: [docs/msbuild/whats-new-msbuild-16-0.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/whats-new-msbuild-16-0.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
Please see the link at the end of the first paragraph:  [MSBuild 16.0](https://gist.github.com/rainersigwald/009627466f03964d0028e16fda633d9c).
