### ISSUE TITLE
Visualizer useless for "visualizing" fixed column files/data

### ISSUE THREAD

**Issue by ajhmain** [MicrosoftDocs/visualstudio-docs#4444]
See title.  
In VS2019 16.3.10, there is no way to change the text visualizer font specifically.  I find this extremely ironic/sad this is for a tool you call 'visualizer'.
  
The 'global' Environment font can do this but it is an unacceptable workaround as it changes menus, solution explorer, and many other windows that I need to remain proportional for readability and screen space issues.

Have commented on the below issue page but it looks like it has been officially ignored.  This needs to be fixed!

 https://developercommunity.visualstudio.com/content/problem/653607/visual-studio-debugger-text-visualizer-font-is-not.html 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3761f60-ec2f-2c51-cfa1-1e192c71bebe
* Version Independent ID: 714a4254-b006-5509-9fa1-355da2184942
* Content: [String Visualizer dialog box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/string-visualizer-dialog-box?view=vs-2019)
* Content Source: [docs/debugger/string-visualizer-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/string-visualizer-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@ajhmain -- Thanks for letting us know. As this venue is specifically for reporting problems with the documentation, I'm closing this issue now (although the record of your post will remain on file here). You've done the right thing by commenting on this in the Developer Community; that also stays on record. Perhaps the following document might help it gain the traction you're looking for: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019.
