### ISSUE TITLE
IDM_VS_MENU_EXTENSIONS is not recognized by guidSHLMainMenu.

### ISSUE THREAD

**Issue by v-lali** [MicrosoftDocs/visualstudio-docs#4445]
IDM_VS_MENU_EXTENSIONS is one menu in VS menu bar. And as the doc said: the menus and groups on the Visual Studio menu bar use the GUID( guidSHLMainMenu).

But actually, when using something like `&lt;Parent guid="guidSHLMainMenu" id="IDM_VS_MENU_EXTENSIONS" /&gt;` will always cause build error : `Undefined 'Parent/@id' attribute 'IDM_VS_MENU_EXTENSIONS' ` Please help check this.

Many thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27088666-73eb-b621-253e-1957218cf765
* Version Independent ID: da38ef89-6570-a27e-9f9a-eaac22baec07
* Content: [GUIDs and IDs of Visual Studio Menus - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/guids-and-ids-of-visual-studio-menus?view=vs-2019#feedback)
* Content Source: [docs/extensibility/internals/guids-and-ids-of-visual-studio-menus.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/guids-and-ids-of-visual-studio-menus.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@v-lali -- Thanks for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by sarah-weinberger** [comment]
I just ran into the same problem, hence same question. I was about to post a new question stating this Microsoft [document](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/guids-and-ids-of-visual-studio-menus?view=vs-2019), when I realized the problem.

I decided to search for vsshlids.h by opening up a command prompt and doing a search for the file.

It came up with several instances:

C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VSSDK\VisualStudioIntegration\Common\Inc

and 3 others in 2013, 2015, and 2017.

Visual Studio uses an older version of the file. My guess is an environment variable points to the wrong build tools folder. The value is definitely there in 2019, but not obviously in older files.

//////////////////////////////////////////////////////////////////////////////
//
// Menu Identifiers, created by Visual Studio Shell
//
//////////////////////////////////////////////////////////////////////////////
#define IDM_VS_MENU_FILE              0x0080
#define IDM_VS_MENU_EDIT              0x0081
#define IDM_VS_MENU_VIEW              0x0082
#define IDM_VS_MENU_PROJECT           0x0083
#define IDM_VS_MENU_TOOLS             0x0085
#define IDM_VS_MENU_WINDOW            0x0086
#define IDM_VS_MENU_ADDINS            0x0087
#define IDM_VS_MENU_HELP              0x0088
#define IDM_VS_MENU_DEBUG             0x0089
#define IDM_VS_MENU_FORMAT            0x008A
#define IDM_VS_MENU_ALLMACROS         0x008B
#define IDM_VS_MENU_BUILD             0x008C
#define IDM_VS_MENU_CONTEXTMENUS      0x008D
#define IDG_VS_MENU_CONTEXTMENUS      0x008E
#define IDM_VS_MENU_REFACTORING       0x008f
#define IDM_VS_MENU_COMMUNITY         0x0090
#define IDM_VS_MENU_EXTENSIONS        0x0091

0x0091 is a new entry.

QED

**Comment by og1sha** [comment]
As a workaround i managed to get it working by defining IDM_VS_MENU_EXTENSIONS in my .vsct file:
```xml
<GuidSymbol name="guidSHLMainMenu" value="{d309f791-903f-11d0-9efc-00a0c911004f}">
    <IDSymbol name="IDM_VS_MENU_EXTENSIONS" value="0x0091" />
</GuidSymbol>

**Comment by WilliamAntonRohm** [comment]
@sarah-weinberger, @og1sha -- Sarah, Ognjen, thank you for clarifying.

@madskristensen -- Mads, please look into this issue.

**Comment by sarah-weinberger** [comment]
@og1sha I like your solution better than hard coding the path to the right vsshlids.h. Microsoft still needs to fix the problem. Thank you for the code fragment! :-)

**Comment by madskristensen** [comment]
I opened a [bug on the VS bug tracker](https://developercommunity.visualstudio.com/content/problem/1063901/idm-vs-menu-extensions-is-not-recognized-by-guidsh.html) for this instead.

@WilliamAntonRohm please close this issue since it is now being tracked elsewhere.

**Comment by WilliamAntonRohm** [comment]
@madskristensen -- thank you.
