### ISSUE TITLE
Attribute 'program' does not exist 

### ISSUE THREAD

**Issue by ghsatpute** [MicrosoftDocs/visualstudio-docs#4447]
I'm getting this error while running the app 

```
---------------------------
Microsoft Visual Studio
---------------------------
One or more errors occurred.

Failed to launch debug adapter.  Additional information may be available in the output window.

Attribute 'program' does not exist ('F:\code\HelloWorldReactFromVS\HelloWorldReactFromVS\server.js').
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ghsatpute Hi, at what point in the doc are you getting that message? What version of VS? Thanks!

**Comment by ghsatpute** [comment]
@Mikejo5000 VS2019

**Comment by Mikejo5000** [comment]
@ghsatpute I've seen this message when attempting to attach the debugger to client-side script; did you run into this error when you first tried to run the app? Or in the latter part of the tutorial where trying to attach to client-side script? Thanks.

**Comment by ghsatpute** [comment]
I was not trying to attach the debugger. I was trying to run the UI application.

**Comment by Mikejo5000** [comment]
OK, thanks. I will retest.

**Comment by amitbarik167** [comment]
Is there any further update ? I am also stuck with this :(

**Comment by ghsatpute** [comment]
@amitbarik167 Unfortunately, I'm not able to find the code that was causing the issue. If possible, can you share your code example, so that it helps the team here?

**Comment by Mikejo5000** [comment]
@amitbarik167 @ghsatpute I just retested this article and ran the app without any errors against Chrome, Edge, and the Edge Beta (chromium-based). This is using VS 16.4.2, which I think is the latest version. (As noted in article, Node.js workload must be installed.)

The easiest place to get tripped up is to choose the wrong template to start with. The steps instruct you to choose the "Blank Node.js Web Application (JavaScript)". It's easy to choose TypeScript or the Console template instead, which might not work quite the same.

Also, the section in the article "Transpile the JSX" is very important. If there are any errors here, they must be fixed before the app will run. Normally, you would only see errors here if you are using some mismatched package versions.

**Comment by Mikejo5000** [comment]
I get a repro on this issue if I start with the TS, rather than the JS, template.

**Comment by Mikejo5000** [comment]
The main issue here is that the TS template has a build script in package.json to transpile server.ts to server.js, and then expects to find the transpiled server.js when running the app. The quick workaround (if you started with the TS template only) is to change the name of server.ts to server.js, use the code in the tutorial, and replace the build/clean scripts in package.json with the script specified in the article in the article section "Add a build script...". Also, right-click the project in Solution Explorer, select Properties, and change the reference from server.ts to server.js. That essentially switches you over to the JS template as a starting point.

I'm sure there is a way to use TypeScript code in server.ts, transpile it, and make it work, but that would take some additional testing. I will make an edit to clarify that you want to use the JS template.
