### ISSUE TITLE
Correction in for each loop

### ISSUE THREAD

**Issue by sharmaayush** [MicrosoftDocs/visualstudio-docs#445]
m.forEach(function (value, key, mapObj) {  
    document.write(item.toString() + "<br />");  
});  

This should like below code because if we copy the code and will run it the item.toString() will give undefined.

m.forEach(function (value, key, mapObj) {  
    document.write(value.toString() + "<br />");  
});  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46d55306-4126-1106-7d55-c18cc7a0e1fc
* Version Independent ID: 320e1575-d28a-fc90-fdb9-3bbfffd8f9dd
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/advanced/collections-javascript)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/advanced/collections-javascript.md)

**Comment by gewarren** [comment]
@sharmaayush thanks for finding this error. @Mikejo5000 can you make this change please?

**Comment by Mikejo5000** [comment]
Working on it

**Comment by Mikejo5000** [comment]
@sharmaayush Fix live. Closing. Thanks!
