### ISSUE TITLE
Can't install from offline installer

### ISSUE THREAD

**Issue by rebnridgway** [MicrosoftDocs/visualstudio-docs#4452]
When I try and install Visual Studio from my local install cache, the Visual Studio Installer just ignores it and downloads everything from the internet.  I tried adding the --noWeb parameter to tell it not to connect to the internet, but it even ignores that!  I have set the channel manifest location to be my local cache, by hand-editing the response.json file, the catalog.json file, and adding the --channelUri parameter, but rather than use my local cache it just gives me this message:
"Setup can't continue.  We need to download some files to complete this operation, but the --noweb parameter was specified.  Please remove the --noweb parameter and try again."

What's the point in making a local cache if it doesn't contain all of the files?  What's the point in adding a --noweb parameter if the installer is going to ignore it?  What's the point in telling me to edit the channel manifest location if the installer is going to decide to ignore it and download everything again?  I want to control what the Visual Studio Installer downloads, and I want to control where it downloads it from.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@rebnridgway -- It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

-Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

 

Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 

 

Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by rebnridgway** [comment]
Thanks for the quick response.  You are correct that I am having an issue with installation.  I will try one of the other options.

**Comment by allen-sparks** [comment]
I did live chat with customer service. He tried to do a partial install for c++ and it didn't work for him either. He suggested I do the entire layout
>  vs_community.exe --layout c:\vslayout --lang en-US
It took forever and I had to use 7zip to split the volume when using a usb drive but it worked.
Admins please update or remove steps that don't work, its not helpful to constantly direct us to customer service

**Comment by arashkhamoosh** [comment]
I have the same problem with --noweb switch and get "Setup can't continue. We need to download some files to complete this operation, but the --noweb parameter was specified. Please remove the --noweb parameter and try again.", I want the Installer to use my shared network layout, and It is important to me that the client computers do not use internet to download files and use my network layout
