### ISSUE TITLE
.NET Core Export Project Requires Hand Edit of Project File

### ISSUE THREAD

**Issue by plntxt** [MicrosoftDocs/visualstudio-docs#446]
It's worth a note here, that you need to hand-edit the .csproj file if you are <a href="http://plntxt.com/blog/creating-visual-studio-project-templates-targeting-.net-core.html">exporting a project template that targets .NET core.</a>  The reason being is that with .NET Core, <a href="https://github.com/dotnet/core/blob/master/release-notes/1.0/sdk/1.0-rc3-default-compile-items.md">includes/excludes are handled by the SDK</a>, not the project file. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e16e6e-e5d1-964b-f220-cbb2c7e4b5e2
* Version Independent ID: 94f82ff9-c61f-31d1-df37-f5e4320daf1c
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/how-to-create-project-templates.md)

**Comment by gewarren** [comment]
@plntxt thanks for letting me know about this. I will update the topic.

**Comment by Matthew-Bonner** [comment]
This needs to be logged over at the Visual Studio website as the tooling needs to be updated, just updating the docs is not a good long-term solution.

**Comment by Matthew-Bonner** [comment]
I've logged this for you, visit the following web page to track the status of this:
https://developercommunity.visualstudio.com/content/problem/234081/net-core-export-project-requires-hand-edit-of-proj.html

**Comment by gewarren** [comment]
According to the [issue](https://developercommunity.visualstudio.com/content/problem/77773/vs-2017-针对-aspnet-core-导出模版功能有问题.html) that @Matthew-Bonner 's issue was duped against, template export for .NET core has been fixed in an upcoming release. Since the work is being tracked there, and, once it's fixed the docs shouldn't need to mention the hand edit, I'm closing this docs issue.
