### ISSUE TITLE
Create layout for specific Visual Studio version

### ISSUE THREAD

**Issue by pmisik** [MicrosoftDocs/visualstudio-docs#4460]
We usually try to upgrade Visual Studio (VS) as soon as possible.
But there are cases when VS introduces code generation bug which forces us to stop upgrading.
Is it possible to create offline layout of specific version of VS?
For example we need to create offline layout of VS2019 16.3.9.
On https://my.visualstudio.com is available just 16.0 or 16.4 that we cannot use we exactly need 16.3.9
There is no example in documentation. 
If it is supported could you please add it?
Thank You

Palo

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019&source=docs#feedback)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@pmisik -- Pavol, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

-Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

 

Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 


 

Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by TerryGLee** [comment]
@pmisik There is a document that might help you with your scenario; it's linked to from the [Create a network-based installation](https://docs.microsoft.com/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019), which is this one: [**Control updates to network-based Visual Studio deployments**](https://docs.microsoft.com/visualstudio/install/controlling-updates-to-visual-studio-deployments?view=vs-2019). 

As well, if it's a scenario you wish to pursue, we have more information about how to stay on a specific servicing baseline, here: [Visual Studio Product Lifecycle and Servicing](https://docs.microsoft.com/visualstudio/releases/2019/servicing).

Hope this additional information is useful. And thanks for your inquiry!
