### ISSUE TITLE
Required Project Settings

### ISSUE THREAD

**Issue by arnold256** [MicrosoftDocs/visualstudio-docs#4463]
it is worth adding that the following settings are required for this to work.
`<ItemGroup>
<ProjectCapability Include="DynamicDependentFile" />
<ProjectCapability Include="DynamicFileNesting" />
</ItemGroup>`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019#feedback)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by abpiskunov** [comment]
Those capabilities are added for web core projects automatically, For all other "core" project types that need nesting support users can add them as a workaround, since other project types don't support this type of nesting by default.

**Comment by AngelosP** [comment]
This is basically a hack/workaround to enabling a feature that we have deliberately not enabled for certain projects. We should not be documenting this publicly. #please-close
