### ISSUE TITLE
Replace with ASP.NET Core

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/visualstudio-docs#4465]
If you agree, assign to me, otherwise close.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 127fb41d-352d-d46e-6456-77231964bc2a
* Version Independent ID: 9b350380-51b0-9c24-990f-85b56f4339dd
* Content: [Debug ASP.NET - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/quickstart-debug-aspnet?view=vs-2019)
* Content Source: [docs/debugger/quickstart-debug-aspnet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/quickstart-debug-aspnet.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Rick-Anderson -- Rick, thanks for your feedback; we appreciate it and your offer to assist. To make sure we have all the information needed to triage your issue, please provide more context.

**Comment by Rick-Anderson** [comment]
More new developers are creating/debugging ASP.NET Core projects than ASP.NET 4.x projects.

**Comment by Rick-Anderson** [comment]
We haven't written any new content for ASP.NET 4.x in 3+ years. All the new content is ASP.NET Core.
