### ISSUE TITLE
Make it clear that namespaceanddescendants scope is compiler version dependent rather than visual studio version dependent

### ISSUE THREAD

**Issue by yohny** [MicrosoftDocs/visualstudio-docs#4469]
The namespaceanddescendants scope works only with 3.x version of compiler. Even if you have VS2019, but your projects use pre-3.x version of Microsoft.Net.Compilers package this will not work (common scenario, as the whole point of Microsoft.Net.Compilers nuget is to decouple compiler version from VS version)

based on:  https://github.com/dotnet/roslyn-analyzers/issues/3108

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517e8321-aa13-0814-3398-9606d7c2664b
* Version Independent ID: 59efa3c4-ceaf-a384-94af-0f76584efe3f
* Content: [Suppress code analysis warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#feedback)
* Content Source: [docs/code-quality/in-source-suppression-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/in-source-suppression-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by Mikejo5000** [comment]
Let me know if this looks OK
