### ISSUE TITLE
Azure Permissions

### ISSUE THREAD

**Issue by MisinformedDNA** [MicrosoftDocs/visualstudio-docs#447]
What permissions are needed to debug? What should I request from my admin?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5f13f80-a3b0-9602-db14-48130d47ef7c
* Version Independent ID: 96ee1b24-bc43-5e46-f645-f4ccfe9f1ba1
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-live-azure-applications)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/debugger/debug-live-azure-applications.md)

**Comment by MisinformedDNA** [comment]
Duplicate of #428

**Comment by nikhilrj** [comment]
As answered in the dupe, 

"as of now, the Azure App Service you would like to debug must be visible to the user that wants to attach the Snapshot Debugger. This can be achieved by setting your access level to "Contributor" or higher in the Access Control (IAM) page on the relevant App Service on the Azure portal."
