### ISSUE TITLE
Can't create an Azure Function in an existing folder structure

### ISSUE THREAD

**Issue by jn-altius** [MicrosoftDocs/visualstudio-docs#4473]
I have an existing Solution made up of 20+ Projects, arranged into a sensible folder structure.  When I right-click on a folder and Add New Project I get the silly new dialog box pop up.  I type "Azure Function" into the search box (as this is meant to be search-first), but the only letter that the search box seems to respect is 'A'.  Azure Functions are the 5th found option :-(  Which is pretty poor as that is the exact search term.

When I pick the Azure Function the next annoyance is the path this dialog displays is for the root of the Solution, and NOT the exact folder I right-clicked on.  This should be the standard behaviour.

When I correct the folder path and give the Function a name, I get another screen of options (containing the trigger type, and storage option) but the only option I see for trigger type is Empty.  Where have all the others gone??

Lastly when I pick Empty and click create, I can see the Project folder get created when I look in windows explorer, but nothing happens in VS except for a message box "Object not set to an instance of an object".  And no clue as to why VS 2019 cannot create a simple Function? :-(

Overall this UX is really poor.  Not happy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b25eea-0531-fc29-14c3-97b01d3c9ffc
* Version Independent ID: 93399d12-64f7-aa0c-f7d6-7ed8ecd95086
* Content: [Create a new project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-new-project?view=vs-2019)
* Content Source: [docs/ide/create-new-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-new-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by jn-altius** [comment]
![image](https://user-images.githubusercontent.com/46445786/70652331-57896080-1c4a-11ea-8980-88b95a3dd7fc.png)

The search experience - only works for 1 letter :-(

**Comment by jn-altius** [comment]
![image](https://user-images.githubusercontent.com/46445786/70652532-a8995480-1c4a-11ea-89ad-9b07feb63e11.png)

The Configure screen (Note: the folder I right-clicked on is about 4 levels deep!  The dialog tries to put everything at the Solution root)

**Comment by jn-altius** [comment]
![image](https://user-images.githubusercontent.com/46445786/70652670-e8f8d280-1c4a-11ea-95a8-27723d3ba663.png)

And there's no option any more to pick Trigger type at the point of creation :-(

**Comment by WilliamAntonRohm** [comment]
@jn-altius -- Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
