### ISSUE TITLE
Add pointer to ConfigureAwait blog post

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#4474]
We should potentially add a link here to the blog post being added in https://github.com/microsoft/dotnet-blog/pull/397. We get lot of similar questions on this rule. Tagging @stephentoub 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02d637a6-6f73-c865-94ea-28ca5d9861a0
* Version Independent ID: df24f234-848f-e04c-488d-6b6346e51fa6
* Content: [CA2007: Do not directly await a Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2007?view=vs-2019)
* Content Source: [docs/code-quality/ca2007.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2007.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by stephentoub** [comment]
https://devblogs.microsoft.com/dotnet/configureawait-faq/

**Comment by Mikejo5000** [comment]
Adding a link to the See Also section. Let me know if you need more visibility on the link.

**Comment by mavasani** [comment]
@Mikejo5000 That sounds good to me. Thanks!
