### ISSUE TITLE
TypeScript examples for Windows Server .Net Core deployments

### ISSUE THREAD

**Issue by GlynP** [MicrosoftDocs/visualstudio-docs#4480]
Why is there such an emphasis, to the exclusion of all else, on deploying to Linux environments? I'm currently prototyping a website using VS2019 which will be deployed to Windows Servers on a shared hosting package. This website is based on .Net Core 3.1 MVC Razor pages with some TypeScript, Bootstrap and jQuery. Where is the documentation, enthusiasm and examples for scenarios such as this? Is traditional Microsoft technology so last week that nobody cares?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa65a08-a9e2-721d-e00c-1f28afffe2be
* Version Independent ID: babf20c3-c235-d839-7340-fb9c11c449dc
* Content: [Create a Node.js and Express app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@GlypP We do have some doc gaps around the scenarios you described. At present, the VS docs here (https://docs.microsoft.com/en-us/visualstudio/javascript/) geared more toward Node.js users in VS (originally the docs for Node.js Tools in VS), and the inclusion of Linux is based on expected numbers of Linux deployments vs. Windows Server. These docs have since shifted to a more general TypeScript/JavaScript focus, but there are still a number of doc gaps.

**Comment by GlynP** [comment]
Do you have any idea when these 'gaps' will be closed, or do they simply reflect a decision to abandon support for non-Azure deployment scenarios?

Sent from Outlook on Glyn's Nokia 9

________________________________

**Comment by Mikejo5000** [comment]
IIS shared hosting on Windows Server? No, there has been no decision to abandon support for non-Azure deployment scenarios that I'm aware of. However, on the VS docs side, there's a focus on tasks that you would do from VS. So, the general deploy to a web server UI in VS might be relevant:
https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-a-web-site?view=vs-2019
If the UI is not applicable for your project type, or this content is too basic (which seems very likely), I believe the IIS docs would be the only place you are likely to find that:
https://docs.microsoft.com/en-us/iis/

**Comment by GlynP** [comment]
For me it is really more about the 'how' of writing the code; the technology building blocks we use and their combination, rather than the nitty gritty of the server configuration.

As an independent dev I have no control over how a hosting company runs their servers and I find myself typically deploying to either ISP shared hosting or 'internal' Windows Servers.

What I find odd is the lack of documentation and examples using major tech in these scenarios. So, given the emphasis on NET Core over NET Standard and the excitement over TypeScript I was expecting something somewhere discussing the use of TypeScript in NET Core MVC Web solution!

Further, I expected adding TypeScript and typedefs for jQuery and Bing Maps to such a project using NuGet within Vs2019 to work too. At the time of writing (Dec 2019) it does not.

I get the distinct feeling eyes are not on the ball, but on the new shiny toys, at Microsoft. Once things are started, they need to be finished, and supported. It's not exciting or glamorous, but it needs to be done and should be highly valued, respected and rewarded work. I'm betting it is not!


Sent from Outlook on Glyn's Nokia 9
________________________________

**Comment by Mikejo5000** [comment]
As far as getting TS support into a VS project (you mention adding TS and typedefs for jQuery and Bing Maps), did you try the NuGet (or npm) package described here:
https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2019?view=vs-2019
Does that help in your scenario? We do have a backlog item to create a basic app in TS in VS (no Node.js dependency) to add to the existing tutorials here. For TypeScript scenarios, we are tending to get a larger user base in VS Code, so these web app scenarios are getting more attention in those docs.

**Comment by GlynP** [comment]
The NuGet GUI built into VS2019.

I understand the excitement around VS Code (new shiny toy) and how it more relevant to a section of the 'younger' developer community not committed to and embroiled in more corporate Microsoft tech.

However, there are still plenty of us fossils out here doing things the (old) Microsoft way. Can we have some documentation love too please?

We need documentation because we're old and we forget sometimes. It comes to everyone sometime.

Sent from Outlook on Glyn's Nokia 9

________________________________

**Comment by Mikejo5000** [comment]
@GlynP I got this work started by publishing a new tutorial on ASP.NET Core with TypeScript:
https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2019
I'm closing this. If you have some improvements to suggest on the other topic, could you open it there. It might be helpful to include an example of adding a third party framework like jquery and showing IntelliSense, but I haven't had a chance to test it out yet. Thanks for your comments!
