### ISSUE TITLE
CA2100 rule (SQL queries potential vulnerability) doesn't take into account that a type may be sealed

### ISSUE THREAD

**Issue by Crono1981** [MicrosoftDocs/visualstudio-docs#4482]
The rule says that the `ToString` method of a type will also cause the warning to happen, because a malicious user could override the method.

Shouldn't the `ToString` method of a `sealed` type solves this concern?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14de0115-7385-33df-dfc2-b57b8d5b9edc
* Version Independent ID: ea0ea380-f11e-6787-c870-dc7b958b214d
* Content: [CA2100: Review SQL queries for security vulnerabilities - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2100?view=vs-2019)
* Content Source: [docs/code-quality/ca2100.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2100.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
@mavasani Would using a sealed type prevent the warning, at least in the case of ToSring?

**Comment by mavasani** [comment]
I think that is a fair assessment. You can probably port the issue to roslyn-analyzers repo to be fixed.

**Comment by Mikejo5000** [comment]
Closing the doc issue
