### ISSUE TITLE
docs

### ISSUE THREAD

**Issue by SametUCA** [MicrosoftDocs/visualstudio-docs#4485]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90a03cb3-5472-d3bc-3b4b-7eda41f2e22e
* Version Independent ID: dd54b123-53a5-e328-ea74-54fab50a6e6c
* Content: [Publish a Python app to Azure App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/publishing-python-web-applications-to-azure-from-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/publishing-python-web-applications-to-azure-from-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/publishing-python-web-applications-to-azure-from-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@SametUCA -- Samet, please provide more context around your general task.
