### ISSUE TITLE
Tutorial doesn't work in asp.net core 3.1

### ISSUE THREAD

**Issue by SidShetye** [MicrosoftDocs/visualstudio-docs#4487]
Following this on VS 2019 (16.4.1) and .net core 3.1 (LTS) tooling gives an exception at `WebFrontEnd.Pages.IndexModel.OnGetAsync() in C:\pocs\docker\DockerOrchestration\DockerOrchestration\WebFrontEnd\Pages\Index.cshtml.cs` ... basically the webfront end is up and running but it unable to route requests over to the webapi container.

There are two issues, both related to newer ASP.NET Core 3.1 VS2019 templates.

1. The newer webapi templates use `app.UseHttpsRedirection();` in `Startup.cs`. Comment that out in `MyWebAPI`'s `Startup.cs` file.

2. The newer webapi templates eliminate the `ValuesController` and switches to `WeatherController`, so `WebFrontEnd`'s index.cshtml.cs needs `request.RequestUri = new Uri("http://mywebapi/WeatherForecast");` instead

With those two changes, it works just fine once again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aee46f8-9db1-33ef-b637-fc8e8881fab9
* Version Independent ID: 6c469f9f-9751-669f-3dd4-c4fb49c9ae19
* Content: [Multicontainer tutorial using Docker Compose & ASP.NET Core - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2019)
* Content Source: [docs/containers/tutorial-multicontainer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-multicontainer.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
This has been updated now.
