### ISSUE TITLE
Outdated Uninstall Script

### ISSUE THREAD

**Issue by jgold6** [MicrosoftDocs/visualstudio-docs#4488]
Some locations that no longer exist but are still being removed (not a big deal and likely should be left in for legacy uninstalls):
sudo rm -rf /Developer/MonoTouch
sudo rm -rf /Developer/MonoDroid

More importantly, removing these locations should be added to the script:
sudo rm -rf /Developer/Xamarin
sudo rm -rf /Developer/XamarinStudio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Uninstall Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019&source=docs#visual-studio-for-mac-and-xamarin-script)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by jgold6** [comment]
Oh, and the page itself should be updated to remove those locations

**Comment by heiligerdankgesang** [comment]
Hey @jgold6 - thanks for the suggestions.

I can't recall exactly what is in each of these folders and don't have any legacy installs:
sudo rm -rf /Developer/Xamarin
sudo rm -rf /Developer/XamarinStudio

I'm assuming /Xamarin was extension related and the /XamarinStudio was for the IDE? Want to make sure I get them in the right spot in the scripts/doc.

**Comment by jgold6** [comment]
Oops, sorry, left out part of the path. I edited the description, but the oaths should be:

These are legacy:
sudo rm -rf ~Library/Developer/MonoTouch (old, no loner used... I believe these held the license files)
sudo rm -rf ~Library/Developer/MonoDroid (old, no loner used... I believe these held the license files)

These are not legacy:
sudo rm -rf ~Library//Developer/Xamarin (Has Android SDK, NDK, JDK, Android App Archives, Azure-Functions-cli, GooglePlayStore, and KeyStore)
sudo rm -rf ~Library//Developer/XamarinStudio (Has DeveloperPortal.db)
