### ISSUE TITLE
.NET Framework support by version

### ISSUE THREAD

**Issue by thomb1** [MicrosoftDocs/visualstudio-docs#4489]
Hi,
Is there a listing of which Roslyn packages run on particular .NET Framework versions? For me specifically I am looking to see if package version 3.4 is supported on .NET Framework 7.2  (I am running into Visual Studio related difficulties RE 3.4 and wanting to rule out attempting something impossible). Thanks in advance,
Thom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0997f041-1ecb-af6d-c4a6-8c61ec177dac
* Version Independent ID: 45c55eac-dff7-812a-7e95-15952047d19f
* Content: [Supported Roslyn package version mappings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2019#feedback)
* Content Source: [docs/extensibility/roslyn-version-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/roslyn-version-support.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@thomb1 -- Thom, thank you for your feedback.  You may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@jillre -- Jill, please look into this potential documentation issue.

**Comment by madskristensen** [comment]
@jaredpar do you know?

**Comment by jaredpar** [comment]
Roslyn 3.0 and higher requires 4.7.2 Desktop to function.

**Comment by thomb1** [comment]
Hi all,
Thank you very much!
I have gotten this working successfully using Framework 4.7.2 and Roslyn 3.4

For what it’s worth, the original problems I had were 100% unrelated to the topic alas. I renamed a project within my solution. I did change the namespaces etc. appropriately – but I did not rename the project’s folder on the drive. That coupled perhaps with Source Control on top of it caused havoc with the debugger…and then…I started chasing ghosts.

Regards,
Thom

Thom C. Blackwell,  VP Technical Services
Boston Software Systems, Inc.
Phone: 866.653.5105 x807
Mobile: 508.423.8463
Fax: 508.319.3015
www.bostonsoftwaresystems.com<http://www.bostonsoftwaresystems.com/>

The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.
