### ISSUE TITLE
The first link on this page is broken to download VS 2017 https://www.visualstudio.com/vs/visual-studio-2017/

### ISSUE THREAD

**Issue by seanmcbreen** [MicrosoftDocs/visualstudio-docs#449]
Need an updated link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide#install-the-visual-studio-ide)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/ide/visual-studio-ide.md)

**Comment by TerryGLee** [comment]
@seanmcbreen We will investigate this right away.

**Comment by TerryGLee** [comment]
@seanmcbreen We have a PR in place that should have the broken link fixed with tomorrow's daily publish. After we verify that the fix is live, we'll close this Issue. 

Thanks for bringing this to our attention.
~ Terry

**Comment by gewarren** [comment]
I'm not seeing that the link is broken. I wonder if that site was down yesterday?

**Comment by seanmcbreen** [comment]
The link has been updated now and is correct/working.
