### ISSUE TITLE
A couple of improvements

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/visualstudio-docs#4491]
1. The steps to get to the modify menu are inside the modify workloads section. Steps 1 and 2 are generic to anyone trying to access any of the changes.
2. Image of the step 2 in modify workloads is highlighting a product that doesn't have the Modify button because it needs to be updated first. Image should be replaced with one that is about modify, not update.
3. Can you also add info about modify language packs?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d0cb94-2886-79ce-39dd-0336282369b9
* Version Independent ID: e8bcc58e-98af-e3ad-2629-0b4515047d0b
* Content: [Modify Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019)
* Content Source: [docs/install/modify-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/modify-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@mairaw Thank you for the feedback, assigning this to the author for review.

**Comment by TerryGLee** [comment]
@mairaw I appreciate your suggestions; they're in the queue.

**Comment by mairaw** [comment]
Another thing I remembered. Sometimes, the Modify button is not available, so only Update shows up. In that case, they first need to update their VS and then the Modify button will show up.

**Comment by TerryGLee** [comment]
@mairaw Thanks for pointing that out. We had this info on the VS2017 version of the page, and it needs to be on the VS2019 version, too. I'll get that added. :)

**Comment by mairaw** [comment]
Cool! I have this published now in my doc:
https://docs.microsoft.com/en-us/dotnet/core/install/localized-intellisense#modify-visual-studio-language

(Grabbed a few parts of your doc and then added some specific info about language packs for the release today)

**Comment by TerryGLee** [comment]
@mairaw Thanks; glad the updates were timely :)
I'll close this GitHub Issue now, but let me know if more is required. I can open it again if need be. 
Cheers!
