### ISSUE TITLE
The `Function` element is *not* only supported in C# code snippets.

### ISSUE THREAD

**Issue by heroboy** [MicrosoftDocs/visualstudio-docs#4492]
I see the c++ snippet `switch.snippet` uses the `Function` element.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91faad91-f76f-1c35-3ff7-b8dea92c00f1
* Version Independent ID: d974b7e1-f76a-c575-bff8-cf4d38d19771
* Content: [Code snippets schema reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2019#function-element)
* Content Source: [docs/ide/code-snippets-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-snippets-schema-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by DanteGagne** [comment]
Thanks for the feedback. Yeah, this page is quite out of date, since C++ and VB at least both do support functions now. I've updated to a more generic text to encourage folks to check the language specific documentation, especially since we believe some languages still do not support functions.
