### ISSUE TITLE
Options not availible

### ISSUE THREAD

**Issue by JerrodV** [MicrosoftDocs/visualstudio-docs#4496]
I am using Visual Studio 2019 v16.4.1. Why are these options not available to me in the installer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c6b3cd-fc32-1501-68a6-1da597bfd33b
* Version Independent ID: 499fd553-6e2e-aefe-aefd-2711c01e39e0
* Content: [Code maps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/map-dependencies-across-your-solutions?view=vs-2019#feedback)
* Content Source: [docs/modeling/map-dependencies-across-your-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/map-dependencies-across-your-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@JerrodV -- Jerrod, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

 

Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 

 

Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
