### ISSUE TITLE
Full Screen Mode for MAC Keyboard shortcut is incorrect

### ISSUE THREAD

**Issue by AsimShakour** [MicrosoftDocs/visualstudio-docs#4498]
![image](https://user-images.githubusercontent.com/8389291/70840992-3ce6f100-1ddc-11ea-9c03-7e376ba99efc.png)
That's the correct Full Screen.
The image I added is for Visual Studio Mac 2019. FYI.

On the website, it incorrectly shows:
![image](https://user-images.githubusercontent.com/8389291/70841029-97804d00-1ddc-11ea-9fd3-2aecd5d92b2c.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a1d38f-f2fc-3fe6-bfb4-b73b7f4a56bc
* Version Independent ID: 90b1f5ca-71dd-2c14-8023-c3f238fc2686
* Content: [Default Keyboard Shortcuts - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/keyboard-shortcuts?view=vsmac-2019#feedback)
* Content Source: [mac/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/keyboard-shortcuts.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by heiligerdankgesang** [comment]
Thanks for reporting this issue. This document shows keyboard shortcuts for the default keybinding scheme in Visual Studio for Mac ("Visual Studio for Mac"). It looks like you might be using the "Visual Studio (Windows)" scheme. You can check by navigating to **Visual Studio > Preferences > Environment > Key Bindings**

Let me know if there's anything else I can do to help.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
