### ISSUE TITLE
%(RelativeDir) Clarification

### ISSUE THREAD

**Issue by yuehuang010** [MicrosoftDocs/visualstudio-docs#4499]
%(RelativeDir) includes %(RootDir) if Include is full path.

For example:
~~~~~~~~~
&lt;ItemGroup&gt;
    &lt;MyItem Include="C:\MyProject\Source\Program.cs" /&gt;
&lt;/ItemGroup&gt;
~~~~~~~~~
%(RelativeDir) is "C:\MyProject\Source\" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62db4b12-8d5d-6a33-b5f6-b3f7320dd3f8
* Version Independent ID: 19ee6154-2eb2-b6a0-ab2e-96de2cfc05b2
* Content: [MSBuild Well-known Item Metadata - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-well-known-item-metadata.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-well-known-item-metadata.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review the above-mentioned PR 5943.
