### ISSUE TITLE
If the debitAmount value is valid (i.e., less than the balance but greater than zero,....

### ISSUE THREAD

**Issue by LiaoXP** [MicrosoftDocs/visualstudio-docs#450]
when we need to consider this? The method Debit_WhenAmountIsMoreThanBalance_ShouldThrowArgumentOutOfRange() suppose to provide test input debit value more than balance, when it is not, it's correct logic to not cause the test method to fail.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)

**Comment by gewarren** [comment]
@pvlakshm can you take this one?

**Comment by gewarren** [comment]
@LiaoXP I agree it was a bit confusing as written, because that test method should never be using a valid debit amount - that's not its purpose. I've rewritten that section of the topic to be a bit less confusing.
