### ISSUE TITLE
"Add New Table" doesn't come up!

### ISSUE THREAD

**Issue by maitrey2** [MicrosoftDocs/visualstudio-docs#4500]
After creating Databse server and mapping database file to it. When I right click on "Tables", I only see "Refresh" and "Property" options. 

Any Ideas???

![image](https://user-images.githubusercontent.com/32009645/70843375-45045800-1dff-11ea-9328-e829c5c35abe.png)

**Comment by WilliamAntonRohm** [comment]
@maitrey2 -- Maitrey, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
