### ISSUE TITLE
Microsoft.VisualStudio.Shell.14.0 is not anymore needed as dependecy for vs19

### ISSUE THREAD

**Issue by BrayanKhosravian** [MicrosoftDocs/visualstudio-docs#4501]
Hello.

this package: `Microsoft.VisualStudio.Shell.14.0` is not anymore needed to install via the nuget explorer.
as the latest vs.sdk which is shiped directly with visual studio 2019 has a dependency with 
`Microsoft.VisualStudio.Shell.15.0`.
and this causes a nuget mismatch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e759cd22-3920-94e9-5d7a-e1766e2f79db
* Version Independent ID: b4796726-14a3-342e-448f-10fb0ba2deb1
* Content: [Walkthrough: Displaying Statement Completion - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-statement-completion?view=vs-2019)
* Content Source: [docs/extensibility/walkthrough-displaying-statement-completion.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-statement-completion.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@madskristensen -- please review the above-mentioned PR 5932.
