### ISSUE TITLE
Missing process to report a problem for build tools-only installation

### ISSUE THREAD

**Issue by mattr** [MicrosoftDocs/visualstudio-docs#4503]
The instructions all rely on having VS installed. I only have the build tools installed as I use JetBrains Rider as my primary IDE.

(I'm having the same reboot issue as https://developercommunity.visualstudio.com/content/problem/30007/visual-studio-installer-always-asking-for-reboot.html with install version 2.4.1080.1113. The PowerShell script solution proposed there did not work either.)

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by seaniyer** [comment]
@mattr Thanks for your input. We'll review the docs for improvement. You can file an issue on build tools online at Developer Community site here.  
https://developercommunity.visualstudio.com/content/problem/post.html?space=62

It is simply filling out the form on that page. VS IDE is not needed.  I hope that helps.

- Sean
