### ISSUE TITLE
Coded UI Test Project UWP is deprecated

### ISSUE THREAD

**Issue by cheles** [MicrosoftDocs/visualstudio-docs#4505]
Just a mention, in VS 2019 Coded UI Test Project is marked as Deprecated. It is also mentioned in one of our blogs here: https://devblogs.microsoft.com/devops/changes-to-coded-ui-test-in-visual-studio-2019/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d57f1593-d86c-b3a7-72d1-aca878059881
* Version Independent ID: f87b8265-a88b-16f8-9ca0-597266eaffdb
* Content: [Test a UWP app with a coded UI test - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/test-uwp-app-with-coded-ui-test?view=vs-2019#feedback)
* Content Source: [docs/test/test-uwp-app-with-coded-ui-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/test-uwp-app-with-coded-ui-test.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
Yes, there is a note at the top of these pages (it's just an include if you're reading on the repo) that mentions the deprecation.
