### ISSUE TITLE
"Create Unit Tests" menu command availability

### ISSUE THREAD

**Issue by OutgoingOpossum** [MicrosoftDocs/visualstudio-docs#4506]
The note about the "Create Unit Tests" menu command availability does not seem to be any longer valid as the command is now available for .NET Core and .NET Standard projects (tested in Visual Studio 2019 Professional v16.4.1)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a859ec6-03a2-2d8c-bcfe-c9499db55286
* Version Independent ID: 4ac4f045-660e-e159-edeb-315cf491568c
* Content: [Create unit test method stubs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/create-unit-tests-menu?view=vs-2019#feedback)
* Content Source: [docs/test/create-unit-tests-menu.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/create-unit-tests-menu.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by OutgoingOpossum** [comment]
This also effects:
- https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019#create-unit-test-projects-and-test-methods

**Comment by Mikejo5000** [comment]
Updating doc so that note applies only to VS 2017.
