### ISSUE TITLE
p3 is not defined

### ISSUE THREAD

**Issue by aykutkardas** [MicrosoftDocs/visualstudio-docs#451]
var p1 = new Promise(function(resolve, reject) {  
    setTimeout(resolve, 0, 'success');  
});  
var p2 = new Promise(function(resolve, reject) { });  
var p2 = new Promise(function(resolve, reject) { }); // <- var p3 = ...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60e916a9-a712-6b37-b914-ffe26cf3d5e4
* Version Independent ID: 7e1e2e91-f082-5178-396e-4c4452c2ebc2
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/promise-race-function-promise)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/scripting-docs/javascript/reference/promise-race-function-promise.md)

**Comment by gewarren** [comment]
@Mikejo5000 this looks like an easy fix. How come the scripting docs don't have an Edit button for customers to fix issues like this in the docs?

**Comment by Mikejo5000** [comment]
@gewarren They should have an Edit button. I think this issue was fixed before and regressed. I'll look into it.

**Comment by gewarren** [comment]
I'm adding the Edit button now. It should be available on the scripting topics tomorrow.

**Comment by Mikejo5000** [comment]
I didn't see your comment until just now. I just changed the config setting in the public repo to fix it at next merge to live.

**Comment by gewarren** [comment]
@aykutkardas thanks for addressing this with #453 .
