### ISSUE TITLE
Build tools in container Documentation is wrong

### ISSUE THREAD

**Issue by yololftw** [MicrosoftDocs/visualstudio-docs#4514]
https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017

The page mentions
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --all `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

This does not work since the Bootstrapper exits after download and launches the installer and Docker just skips to next step since it sees an exit code

I spent 2 days running around why this stopped working (This used to work a few months ago. Last time i did this)

In order to work around this user has to either Use 

RUN cmd /wait or
RUN Start-Process -Wait  

depending on the  the Shell being used

**Comment by yololftw** [comment]
I am assuming this is a bug with the installer rather than the Documentation as this is a regression!

**Comment by Mr-jiayunfei** [comment]
I get the same problem.add "RUN cmd /wait" command in dockfile can fix this problem？

**Comment by ojizero** [comment]
@Mr-jiayunfei a fix for this would be to use the `Start-Process` Cmdlet (if using PowerShell) as such

```pwsh
Start-Process -FilePath 'C:\TEMP\vs_buildtools.exe' -Wait -ArgumentList '--add Microsoft.VisualStudio.Workload.MSBuildTools', '--installPath C:\BuildTools', '--quiet', '--norestart', '--locale en-US' ;
```

I have tested it and it seems to be working

**Comment by yololftw** [comment]
@ojizero  I did that as you can see in my workaround

**Comment by Mr-jiayunfei** [comment]
Can you provide me with the complete dockerfile? I tried as you said, it may not be successful。

**Comment by yololftw** [comment]
`# Restore the default Windows shell for correct batch processing.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2019

ADD https://aka.ms/vs/15/release/vs_buildtools.exe C:\\TEMP\\vs_buildtools.exe

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN	Start-Process -Wait -NoNewWindow C:\TEMP\vs_buildtools.exe -ArgumentList "--quiet", "--wait", "--norestart", "--installPath=C:\BuildTools", `
	"--add=Microsoft.VisualStudio.Workload.VCTools", "--includeRecommended", "--add=Microsoft.VisualStudio.Component.VC.ATL"
`

**Comment by Mr-jiayunfei** [comment]
ok,Thank you very much,i will try it

**Comment by ornellaalt** [comment]
Hi @yololftw, we've updated the Build Tools documentation [here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019). Please give the new instructions a try. We look forward to your feedback, and I'll be closing out this issue in the meantime.
