### ISSUE TITLE
The "See also" link links back to this same page

### ISSUE THREAD

**Issue by unionthugface** [MicrosoftDocs/visualstudio-docs#4516]
The `Create and use code analysis check-in policies` link at the bottom links to this same page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b577d09-ca7e-76a7-e7fb-9e9d344db14f
* Version Independent ID: 079846d7-de24-ba8d-deb8-ddaedd2908af
* Content: [Create or Update Standard Code Analysis Check-in Policies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-create-or-update-standard-code-analysis-check-in-policies?view=vs-2019)
* Content Source: [docs/code-quality/how-to-create-or-update-standard-code-analysis-check-in-policies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-create-or-update-standard-code-analysis-check-in-policies.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@unionthugface Thank you for the feedback.

The documentation has been updated and is pending review.
