### ISSUE TITLE
Array Object with Expando Property Example

### ISSUE THREAD

**Issue by drewski19** [MicrosoftDocs/visualstudio-docs#452]
Is the Expando Property example correct? There are no integer properties given in the ARR object initialized in the first line of the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d864d2f-da04-407f-6c67-e6b95f139463
* Version Independent ID: 56a7bdb6-95b0-ede6-de02-4c17a5330d60
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/for-dot-dot-dot-in-statement-javascript#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/scripting-docs/javascript/reference/for-dot-dot-dot-in-statement-javascript.md)

**Comment by Mikejo5000** [comment]
Tested the expando example and it works correctly; by default, the element index is used as the property name for the enumerable values.

**Comment by Mikejo5000** [comment]
Closing
