### ISSUE TITLE
Request for Further Info - Visual Studio Subscriptions and Their Associated Azure Subscriptions

### ISSUE THREAD

**Issue by MChez** [MicrosoftDocs/visualstudio-docs#4520]
Could we have some information and best practices on managing the associated Azure Subscriptions when reassigning the Visual Studio subscriptions please?
i.e. Should the subscription be canceled so that the new MSDN/Visual Studio subscription owner can start with a clean slate or should it just be left to the new owner to clean out any unwanted Azure resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02ac813d-de10-3258-bd80-e58591cd1ff0
* Version Independent ID: 51723f6e-5433-558c-16a1-73e33f2883e0
* Content: [Delete subscription assignments in the Visual Studio Subscriptions Administration Portal](https://docs.microsoft.com/en-us/visualstudio/subscriptions/delete-license#feedback)
* Content Source: [subscriptions/delete-license.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/delete-license.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@MChez - Are you asking specifically about an Azure subscription set up by the person who originally held the Visual Studio subscription and was using the included Azure DevTest individual credits?

I'm checking with some of our engineering and support folks on this, and will post again when I have more information to share.  Stay tuned.

**Comment by MChez** [comment]
@evanwindom If I understand you correctly, yes. The Azure subscription that was created in my company's tenancy when someone activated the Azure DevTest individual credits.
Because this subscription was set up by a guided process (I think this is prompted from Visual Studio when first signing in, but don't quote me.) I don't know what would happen if someone did cancel it. Could the next developer who is assigned the MSDN Visual Studio license activate the credits again!?

**Comment by evanwindom** [comment]
@MChez Hi Mark.  The support folks let me know that there is an existing issue with trying to move an Azure subscription to a new user by reassigning the underlying Visual Studio subscription.  It turns out that the benefit doesn't reset for the new VS user, so they can't activate the Azure benefit.  The best approach is to assign a new subscription if they need to use Azure, rather than re-assigning a subscription if the Azure benefit for that subscription has been activated previously. 

We realize that's not a good situation, and we're working with the Azure team to identify solutions.  We appreciate your patience.

**Comment by MChez** [comment]
@evanwindom Hi Evan, thanks for the update. I'm glad I asked for clarity on this before I did anything.

Will you update the information on the doc page when something is sorted out?
Do you want me to close this ticket or should I leave it open until a solution is found?

**Comment by evanwindom** [comment]
@MChez - Hi Mark.  I'll definitely update the docs with the new process once it's deployed.

**Comment by evanwindom** [comment]
@TerryGLee - Please close this.
