### ISSUE TITLE
Debug R does not work - Vscode 1.41.0 x64 - Linux Lubuntu 18.04

### ISSUE THREAD

**Issue by AndyLuckert** [MicrosoftDocs/visualstudio-docs#4521]
Dear community,

usually, I program in Python. Now with my R-script, I did the same steps as usual:
Setting a breakpoint at a line of desire, and simply press F5 to start the debugging process.
Unfortunately, the debug-config file "launch.json" doesn't comprise of a R-related dictionary entry such as e.g. for python:

```
        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
```

If I imitate the above code-lines and exchange "python" with "R", it says there is no debugger installed named like that.
Searching the vscode market place for R-debugging doesn't seem to offer anything, which obviously contains a debugger. The closest I found was the extension [R LSP Client](https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp):

Nevertheless, after installing it, there was no way for me to add an R-debugger to my launch.json-file,
since there doesn't appear anything related to R in the available options when clicking the Tab "Debug" &gt; "Add configuration ...".

The simple way the debugging process is described here doesn't work for me since when starting a debugging process via F5, vscode selects one of the available debuggers (I have various for python available, such as "Current File", "Remote", "Flask", Django",.. BUT NOTHING FOR R).

I'd be very happy to get some help, since I really don't want to install RStudio on my system just because I can't debug R-codes in Visual Studio.

Thank you very much in advance!
Kind regards,
Andreas

PS:
The R-version I use is the following:
_R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dde63717-000d-d97c-0898-36c005d8541f
* Version Independent ID: 4c63fc76-7fac-4e58-cca7-e8476cb1248f
* Content: [Getting started with R Tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/getting-started-with-r?view=vs-2017&viewFallbackFrom=vs-2019#feedback)
* Content Source: [docs/rtvs/getting-started-with-r.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/getting-started-with-r.md)
* Product: **visual-studio-dev15**
* Technology: **vs-rtvs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@AndyLuckert First, to clarify, the only Microsoft tool that supports R directly is Visual Studio 2015, which is the context of the article on which you submitted this issue.

Visual Studio Code, on the other hand, which is the context of your question, supports the R language only through third-party extensions, as it you've already researched. It doesn't appear that any of those support debugging, unfortunately, and so far as I know Microsoft isn't investing in R tools for VS Code as they are for Python. (You can, of course, make sure a request through the VS Code GitHub repo: https://github.com/Microsoft/vscode/issues.)

At present, then, your options are R Studio, or you can install Visual Studio 2015 from https://visualstudio.microsoft.com/vs/older-downloads/ and select the R Tools for Visual Studio during the installation process. However, unless you can run a Windows program on your Linux system, it would seem that R Studio is your only option.

**Comment by AndyLuckert** [comment]
Thanks for your help!
