### ISSUE TITLE
Debug R does not work - Vscode 1.41.0 x64 - Linux Lubuntu 18.04

### ISSUE THREAD

**Issue by AndyLuckert** [MicrosoftDocs/visualstudio-docs#4522]
Dear community,

usually, I program in Python. Now with my R-script, I did the same steps as usual:
Setting a breakpoint at a line of desire, and simply press F5 to start the debugging process.
Unfortunately, the debug-config file "launch.json" doesn't comprise of a R-related dictionary entry such as e.g. for python:

        {
            "name": "Python: Current File (Integrated Terminal)",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }

If I imitate the above code-lines and exchange "python" with "R", it says there is no debugger installed named like that.
Searching the vscode market place for R-debugging doesn't seem to offer anything, which obviously contains a debugger. The closest I found was the extension R LSP Client:
https://marketplace.visualstudio.com/items?itemName=REditorSupport.r-lsp

Nevertheless, after installing it, there was no way for me to add an R-debugger to my launch.json-file,
since there doesn't appear anything related to R in the available options when clicking the Tab "Debug" &gt; "Add configuration ...".

The simple way the debugging process is described here doesn't work for me since when starting a debugging process via F5, vscode selects one of the available debuggers (I have various for python available, such as "Current File", "Remote", "Flask", Django",.. BUT NOTHING FOR R).

I'd be very happy to get some help, since I really don't want to install RStudio on my system just because I can't debug R-codes in Visual Studio.

Thank you very much in advance!
Kind regards,
Andreas

PS:
The R-version I use is the following:
R version 3.6.2 (2019-12-12) -- "Dark and Stormy Night"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bc6095-cfcf-cc39-957e-7498fe11f055
* Version Independent ID: ca58d770-957b-20e1-052f-b4e79bb73b30
* Content: [Debugging R code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/debugging-r-in-visual-studio?view=vs-2017)
* Content Source: [docs/rtvs/debugging-r-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/debugging-r-in-visual-studio.md)
* Product: **visual-studio-dev15**
* Technology: **vs-rtvs**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by msebolt** [comment]
@AndyLuckert Thank you for the feedback.

This appears to be a duplicate issue, please refer to https://github.com/MicrosoftDocs/visualstudio-docs/issues/4521.

**Comment by AndyLuckert** [comment]
Alright, thanks!
