### ISSUE TITLE
How to deploy an update to client machines - descriptin doesn't work!

### ISSUE THREAD

**Issue by hjrb** [MicrosoftDocs/visualstudio-docs#4523]
&gt;&gt; First, update the Visual Studio installer:
&gt;&gt; vs_enterprise.exe --quiet --update
First of all vs_enterprise.exe isn't available on the client machine. Without first downloading it or using if from a network share - how can we run it?
If you run it from a network share this does NOT update the VS installer on the PC!
Hence [vs_enterprise.exe update --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise" --quiet --wait --norestart] will fail as in --quiet mode the installer can not ask if it should update.
Also: why using install path? use productId: Microsoft.VisualStudio.Product.Enterprise and channelId: VisualStudio.16.Release. It would be even better if there was a parameter for the unique Instance ID  - that is the primary key and all the other required parameters can be uniquely determined from it - just saying.
And by the way: the vs_installer.exe mangels the console output when run from cmd.exe and also some weired error messages appear: 
(node:33268) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ApplicationInsights:CorrelationIdManager [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com',
    host: 'dc.services.visualstudio.com',
    port: 443 } ]
ApplicationInsights:CorrelationIdManager [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com',
    host: 'dc.services.visualstudio.com',
    port: 443 } ]
ApplicationInsights:CorrelationIdManager [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com',
    host: 'dc.services.visualstudio.com',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: getaddrinfo ENOTFOUND dc.services.visualstudio.com dc.services.visualstudio.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'dc.services.visualstudio.com',
    host: 'dc.services.visualstudio.com',
    port: 443 } ]
ApplicationInsights:Sender [ { Error: getaddrinfo ENOTFOUND vortex.data.microsoft.com vortex.data.microsoft.com:443
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'vortex.data.microsoft.com',

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc51a257-b7a9-4660-7e12-88cdfcd9cd53
* Version Independent ID: dad2fd97-7244-6802-e853-5d5974838996
* Content: [Update a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/update-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@hjrb -- It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

 

- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 

 

- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by hjrb** [comment]
@WilliamAntonRohm the link to the LiveChat takes me to nowhere. Why does this get closed for no reason and no solution given. My VS installation is all good and I don't have any issues. The procedure simply doesn't work.
