### ISSUE TITLE
Mr

### ISSUE THREAD

**Issue by JackHeeley** [MicrosoftDocs/visualstudio-docs#4527]
Its very difficult to search for examples of how to use gsl::at(). Why are there none here for e.g. &utf16[0]?

gsl::at&lt;std::wstring&gt;(utf16,0) isn't correct, so saying "easily replaced" is rather glib.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2472ab68-c97e-b72e-3fe9-609612cbebb6
* Version Independent ID: 0cba852d-dfc3-048c-9baf-0b1d5fbc5720
* Content: [C26446 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26446?view=vs-2019)
* Content Source: [docs/code-quality/c26446.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/c26446.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@JackHeeley 

Glibness issues aside, I'm not convinced the error documentation for Microsoft's code analyzer is where readers expect to learn how to use a GSL feature. At least, it shouldn't be. I'm closing the issue as outside the document's scope.

Absent some more official documentation for the GSL library, a good source for usage examples is in the GSL repo's *test* directory. For `gsl::at`, many clear examples are found in [at_tests.cpp](https://github.com/microsoft/GSL/blob/master/tests/at_tests.cpp). That's where I'd look. Good luck!

**Comment by JackHeeley** [comment]
@Colin Robertson<mailto:notifications@github.com> Fair point, accepted. The last thing we need is “random truths” (or lies) scattered all over the Microsoft docs. We’ve got the Internet for that!
Thanks for attending to my feedback, and for this tip and useful link!
