### ISSUE TITLE
Should Modify installation be added to this list as well?

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/visualstudio-docs#4529]
You could then add a link to https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc5e99e-c7bd-9519-c739-bfc6ab1a97fe
* Version Independent ID: 03884a15-6e09-1a83-e83a-584addb57248
* Content: [Run as administrator - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/user-permissions-and-visual-studio?view=vs-2019)
* Content Source: [docs/ide/user-permissions-and-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/user-permissions-and-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by TerryGLee** [comment]
@mairaw I assume you mean in the See Also list, correct?

**Comment by mairaw** [comment]
No. I meant here on the table:"

![image](https://user-images.githubusercontent.com/12971179/71225282-e884bb00-228c-11ea-824a-7155c627cd6c.png)

Modify is not listed there but you need the same perms as install, right?
