### ISSUE TITLE
I'm having trouble in signing into my Firefox account because the Android device information is completely different with my girlfriends FIrefox Plug-ins for the Firefox browser, that I beliecve is not my Firefox Browser becuase there is no way to troubleshoot unless I sign into my Firefox account with all of my infiration of a previous address. Because of this, my Firefox Brouser that I believe is the reason that their is knowone in Lake George. Like a guost town.

### ISSUE THREAD

**Issue by drexer1** [MicrosoftDocs/visualstudio-docs#4530]
I'm trying to change the email daddress for my Firefox Browser now that the Mistics had joined with the Skeksies to form an eternal being.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe690a0-e17d-4a9c-a107-7189e29fe815
* Version Independent ID: 87bbbd28-a5a0-76dd-468d-52c4a930f8cd
* Content: [Walkthrough: Creating an N-Tier Data Application - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/walkthrough-creating-an-n-tier-data-application?view=vs-2019)
* Content Source: [docs/data-tools/walkthrough-creating-an-n-tier-data-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/walkthrough-creating-an-n-tier-data-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@drexer1 -- GUY, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around the general task.

**Comment by StingyJack** [comment]
@WilliamAntonRohm why entertain this nonsense about a rejoining of skeksis and urRu into the being that was split to make those two races? We know it will never happen, the Gelflings stories tell us so!

Seriously though, this ramble about a Firefox password and marginally entertaining 40 year old _Muppet_ sci-fi is getting too much life. Either OP is really lost (and probably won't find their way back here), are screwing with you, or are experiencing some Timothy Leary kind of "good times".

**Comment by WilliamAntonRohm** [comment]
:^)
