### ISSUE TITLE
Step 3 has incorrect exe name

### ISSUE THREAD

**Issue by rtrusso** [MicrosoftDocs/visualstudio-docs#4533]
The step references vsintr.exe, it should be vsinstr.exe. I could not find the DLL referenced, msdis150.dll, installed anywhere from the download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb6a064-a3ec-7013-d28f-36d860bb9128
* Version Independent ID: 78db436e-7099-f9b0-4ca4-79a796a595df
* Content: [How to: Install the Stand-Alone Profiler - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-install-the-stand-alone-profiler?view=vs-2017#feedback)
* Content Source: [docs/profiling/how-to-install-the-stand-alone-profiler.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/how-to-install-the-stand-alone-profiler.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@rtrusso Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
It appears that msdis150.dll is an old reference. I'm updating the doc.
