### ISSUE TITLE
Edit your code and refresh with .Net Core >= 3.0

### ISSUE THREAD

**Issue by avanveelen** [MicrosoftDocs/visualstudio-docs#4535]
It is worth to mention that "Edit your code and refresh" is not enabled in the default templates in .NET Core >= 3.0.
To enable it,

Add `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` nuget package.
In the `Startup.cs`, add `services.AddRazorPages().AddRazorRuntimeCompilation();`
After making the above mentioned changes, Edit and refresh works for both Linux and Windows containers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6e74c3-2796-a2c3-ce35-18767cecb702
* Version Independent ID: 60d27ba1-d713-23dc-93ec-b72feda17016
* Content: [Debug apps in a local Docker container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/edit-and-refresh?view=vs-2019#feedback)
* Content Source: [docs/containers/edit-and-refresh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/edit-and-refresh.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
This has been updated now.
