### ISSUE TITLE
Update the vsmac uninstall step to also delete contents from ~/Library/Application\ Support/VisualStudio/7.0/LocalInstall/Addins/

### ISSUE THREAD

**Issue by cryophobia** [MicrosoftDocs/visualstudio-docs#454]
~/Library/Application\ Support/VisualStudio/7.0/LocalInstall/Addins/ may include local installed add-ins. Add-ins not installed via the installer, but manually by the developer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall#)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/mac/uninstall.md)

**Comment by asb3993** [comment]
I spoke to @cryophobia about this, the  information in the doc should already cover this. Closing

**Comment by rfog** [comment]
abs3993, open it because the folder is not deleted.
