### ISSUE TITLE
Issue with link in "Diagnose test method performance issues" section

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/visualstudio-docs#4541]
I am viewing this page with VS 2019 selected as the version.  When clicking the link to Performance Explorer (https://docs.microsoft.com/en-us/visualstudio/profiling/performance-explorer?view=vs-2019), the target page shows a message at the top: "
The requested page is not available for Visual Studio 2019. You have been redirected to the newest product version this page is available for."

Where is the documentation for the "Profile" context menu item when right-clicking a test in VS 2019's Test Explorer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3681419-a041-da72-a134-37401922a536
* Version Independent ID: 57b6194d-cb07-0e89-8f38-544bf4ce9816
* Content: [Run and debug unit tests with Test Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019)
* Content Source: [docs/test/run-unit-tests-with-test-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/run-unit-tests-with-test-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by Mikejo5000** [comment]
Performance Explorer is no longer supported in VS 2019. Some functionality is provided by Performance Profiling tools, CPU Usage, and Instrumentation. The best statement I've seen about the changes is here, see the comments by Allen Denver.
https://developercommunity.visualstudio.com/content/problem/441152/missing-profiler-options-under-debug-visual-studio.html

Updating links.

**Comment by Mikejo5000** [comment]
Looked at this more closely. Looks like that is the Instrumentation report. It is supported in VS 2019, but docs need to be updated from VS 2017.  Here's the best link I see right now:
https://docs.microsoft.com/en-us/visualstudio/profiling/understanding-instrumentation-data-values?view=vs-2017

**Comment by dialedin2014** [comment]
Excellent.  Thanks for finding that.
