### ISSUE TITLE
More details needed in the section SSL-enabled ASP.NET Core apps

### ISSUE THREAD

**Issue by SimonGeering** [MicrosoftDocs/visualstudio-docs#4542]
Step 1 
This does not mention that `dev-certs` is a param to `dotnet`
The correct command should be `dotnet dev-certs https`

Step 2
There is no explanation given on how to export the local development certificate

Step 3
No explanation is given on how to volume mount a directory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd3515a-c60f-141c-a27a-6a22bc47ad1e
* Version Independent ID: 8d117e3a-6089-74ba-1d0f-dd0ad1351fb2
* Content: [Visual Studio Container Tools build and debug overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#feedback)
* Content Source: [docs/containers/container-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-build.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Changed wording on this section to make it clear these are steps that VS performs, not steps the user needs to perform.  Also, see the link in this section for more details.
