### ISSUE TITLE
Modifying user secrets json breaks other launch profiles not using docker

### ISSUE THREAD

**Issue by SimonGeering** [MicrosoftDocs/visualstudio-docs#4543]
Add a note to the SSL section that is the user secrets json is modified with the Kestrel settings pointing to paths that assume docker folder mappings are in place then this will break kestrel on all other visual studio launch profiles since the folder will not exist on the host machine.
```
  "Kestrel": {
    "Certificates": {
      "Default": {
        "Path": "c:\\app\\mycert.pfx",
        "Password": "strongpassword"
      }
    }
  }
```
As such, if profiles in addition to Docker are to be used, it should be recomended to use the environment variables:
```
ASPNETCORE_Kestrel__Certificates__Default__Path and ASPNETCORE_Kestrel__Certificates__Default__Password
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd3515a-c60f-141c-a27a-6a22bc47ad1e
* Version Independent ID: 8d117e3a-6089-74ba-1d0f-dd0ad1351fb2
* Content: [Visual Studio Container Tools build and debug overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#ssl-enabled-aspnet-core-apps)
* Content Source: [docs/containers/container-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-build.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
I made some changes to help clarify this.
