### ISSUE TITLE
Confusion between terms "Item group", "Item type","Item list"

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/visualstudio-docs#4544]
Reading the docs I come to a conclusion that these 3 term are used to dentoe the same entity. Is this true? If yes, what is the reason to have 3 different terms for the same entitt? Thansk

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d4c1957-1da1-073e-e5d2-b88dbb6e4f0c
* Version Independent ID: da079116-5827-d486-271b-9e2cb10bf063
* Content: [MSBuild Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-items?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-items.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
They're not the same.  Item group refers to the XML <ItemGroup> element and its children that form a group.   The groups have elements that have various types, any of which is an item type.  Example, @(Compile) is the items that are to be compiled and the item type is "Compile". Item list is the string of names of the items with the separator ( usually semicolon).  I agree this is confusing and only by reading all the introductory topics would one get a clearer picture of this, so we need to find a way to rely less on these terms.

**Comment by ghogen** [comment]
There is a glossary topic that defines some of these terms.
