### ISSUE TITLE
example .editorconfig and documented Visual Studio default should match

### ISSUE THREAD

**Issue by rjvdboon** [MicrosoftDocs/visualstudio-docs#4547]
In nearly all example `.editorconfig` in this document the configured value matches the Visual Studio default, but not everywhere.  It would be helpful if it would be possible to take the examples from this page, and have a `.editorconfig` that is functionally identical to the Visual Studio default, to make it easier to align all editors that support editorconfig to the Visual Studio default.
Case in point here:
the example states
`csharp_indent_labels = flush_left`
but the Visual studio default states:
`no_change`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db54afa5-fc7b-394f-ede3-4d1d46ec695d
* Version Independent ID: 86441bf6-9e5b-85c2-d42d-3afd5a9a069b
* Content: [.NET formatting conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-formatting-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-formatting-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by jmarolf** [comment]
VS defaults are different between profiles and which settings you have roaming. I do not think we can provide a 'default' editorconfig

**Comment by rjvdboon** [comment]
@jmarolf In that case I wonder what the "Visual Studio Default" item is doing in the documentation? My point is, either make sure the example editorconfig sections are filled with the value stated as Visual Studio default value, or remove the Visual studio default value.
On the other hand, it is not that big a deal. Closing this issue as won't fix would make sense to me as well.

**Comment by TerryGLee** [comment]
@mikadumont FYI on this.

**Comment by jmarolf** [comment]
@rjvdboon yeah, I agree. I don't think its helpful @TerryGLee can you remove the `Visual Studio default` sections from the table?

**Comment by TerryGLee** [comment]
@jmarolf There's a PR ready for you to review. :)

**Comment by TerryGLee** [comment]
@rjvdboon The PR with the fix should be live tomorrow by noon. I'm closing this issue now; thanks for helping us improve the documentation!
