### ISSUE TITLE
How about a link to the Developer Community?

### ISSUE THREAD

**Issue by mikgam** [MicrosoftDocs/visualstudio-docs#455]
Nice article that talks about how to log into the site, and do stuff.  How about including a link to the site that you are trying to direct people to?   https://developercommunity.visualstudio.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)

**Comment by gewarren** [comment]
@TerryGLee can you take a look please?

**Comment by TerryGLee** [comment]
@mikgam There is a link at the bottom of the page that takes you to the Developer Community: It's the one that says, "Give product feedback." But, we'll add a link to the "See also" section, too. Expect that, soon. Thanks for your input!

**Comment by mairaw** [comment]
One suggestion about this. How about you add a note or a sentence that you can visit https://developercommunity.visualstudio.com/ directly from the instructions, not only See also? Some people want to report a problem but they can't do it through the tool because VS is crashing, etc.

**Comment by TerryGLee** [comment]
Thanks to both @mikgam and @mairaw; we've added a link to the [Visual Studio developer community](https://developercommunity.visualstudio.com/spaces/8/index.html) page as a See Also link and as a Note in the "Alternate Reporting" section.
