### ISSUE TITLE
Need documentation on how to remove components that were downloaded during installation

### ISSUE THREAD

**Issue by DavidPrio** [MicrosoftDocs/visualstudio-docs#4551]
Hi writing team. This is to report documentation need requested in https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/170.
In short, contributor would like to know how to remove components that were downloaded when the Visual Studio 2019 For Mac installation was terminated.
Thanks in advance!

Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@DavidPrio, @srvbpigh -- is there a specific article needing this additional documentation, or is this more open-ended?

It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by conceptdev** [comment]
There is an [uninstall doc](https://docs.microsoft.com/visualstudio/mac/uninstall?view=vsmac-2019): [卸载](https://docs.microsoft.com/zh-cn/visualstudio/mac/uninstall?view=vsmac-2019)
