### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by tymarats** [MicrosoftDocs/visualstudio-docs#4552]
The file referenced on this page cannot be found on the server. Also, "Requirements and Assets" seem nowhere to be found in the MPN portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e08350a4-04f7-0915-8447-023f317df2a9
* Version Independent ID: ca20d0e7-6c85-58d3-8265-4fc40fabf42f
* Content: [Manage Visual Studio subscriptions offered through the Microsoft Partner Network (MPN)](https://docs.microsoft.com/en-us/visualstudio/subscriptions/manage-mpn-subscriptions#feedback)
* Content Source: [subscriptions/manage-mpn-subscriptions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/manage-mpn-subscriptions.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@tymarats -- Thanks for bringing these issues to our attention. I've updated the link to the Administrators Guide, and the PR for that is in process.  I'm still researching the issue re:  "Requirements and assets".

**Comment by evanwindom** [comment]
@tymarats - Unfortunately, I don't have access to the MPN portal.  I recommend reaching out to https://partner.microsoft.com/support for assistance on this.

**Comment by evanwindom** [comment]
#please-close
