### ISSUE TITLE
Assumption that link to " To link the tests to the object or library files." is not working properly

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/visualstudio-docs#4559]
Hello,
the link mentioned in title does not show me the info related to linkin ob files in a test proect (or I'm missing something). Could you please double-check and let me know if I simply failed to find the proper info. Thanks !!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18bdf17-06e1-aaf2-b6ce-c606c0e260da
* Version Independent ID: bd627b8f-54f0-84e0-55cd-285597af022d
* Content: [Write unit tests for C/C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2019)
* Content Source: [docs/test/writing-unit-tests-for-c-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/writing-unit-tests-for-c-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@ortymd 
Sorry for the delayed response. The link you mention was mistakenly left behind in a rewrite of the content a year or two ago. You don't need to do anything differently from how you'd normally add an object file to a project. Update the test project properties to add the object or library files to the **Additional Dependencies** linker property, and add the paths to those files to the **Additional Library Directories** linker property. If needed, add a path to any required header file in the **Include Directories** property under **VC++ Directories**. That should be all that's required.

**Comment by corob-msft** [comment]
Updates should appear later today.
