### ISSUE TITLE
Unclear where the default library path comes from

### ISSUE THREAD

**Issue by al45tair** [MicrosoftDocs/visualstudio-docs#4563]
The default library path, at least on my machine, appears to point to the 64-bit libraries. If attempting to link a 32-bit executable using the Link task, it's unclear how I'm supposed to fix this. (I've chosen to set the LIB environment variable manually, but there must be a better way).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13622d44-5b73-908c-978b-818dc60c9f1f
* Version Independent ID: 033ae019-e168-9b71-9865-26c91ea6b95d
* Content: [Link Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/link-task?view=vs-2019)
* Content Source: [docs/msbuild/link-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/link-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ghogen** [comment]
Yes, the linker itself will always depend on the environment variables.  I'll add a couple of links to the MSBuild and command-line C++ docs that go into more details.

**Comment by al45tair** [comment]
@ghogen **This does not, in fact, fix this issue. Please re-open it.**
