### ISSUE TITLE
You have this great feature called Suggest A Feature, but you hide where the suggestions.

### ISSUE THREAD

**Issue by DataJuggler** [MicrosoftDocs/visualstudio-docs#4564]
I cannot find the Suggested Features I have suggested, or the ones from other users.

You have Active Issues, and Closed Issues, but not Suggested Features.

No wonder no one votes on any suggestions any one makes as you can't find them unless you search for them. I want to browse what others have suggested, and this should be visible to everyone if you want everyone's vote.

Currently, your suggestions are winners in the hide and seek game. User Voice was horrible because you gave users 10 votes, which I used in 10 email addresses in a few years. 

Please make Suggested Features more visible, and even create a Community Driven to have people actually view a suggestion before you say 'Didn't get enough votes'. People cannot vote on what they are not aware exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2019#feedback)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by mariaghiondea** [comment]
Per space, you can see Problems and Features:
![tempsnip](https://user-images.githubusercontent.com/11394867/78316353-4673a080-7514-11ea-882e-1fc44e3a9a9d.png)

From your Profile and Preferences/Activity/Features you can see your Suggestions
![MyFeatures](https://user-images.githubusercontent.com/11394867/78316380-5c816100-7514-11ea-977a-cc359b5fba14.png)

If the above are not what you are looking for, please report a new suggestion by following this link: https://developercommunity.visualstudio.com/content/idea/post.html?space=8. This will allow us and you to easily track the status of your item, as well as have the community involved in providing comments, votes, answers and which will give us more context and understanding of impact.
