### ISSUE TITLE
3rd sentence missing "be" :  This may (be) your Microsoft Account...

### ISSUE THREAD

**Issue by v-pethur** [MicrosoftDocs/visualstudio-docs#4565]
Leaving suggested correction in form of feedback as I could not find the "Edit" button for this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba23b3-e035-4cda-f764-51934a1553b2
* Version Independent ID: 4cd8cb86-9d5e-8121-8d0e-7beaa4394380
* Content: [Using the Subscriber Portal - https://my.visualstudio.com](https://docs.microsoft.com/en-us/visualstudio/subscriptions/using-the-subscriber-portal?source=docs#feedback)
* Content Source: [subscriptions/using-the-subscriber-portal.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/using-the-subscriber-portal.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@v-pethur - Thanks for bringing the error to our attention.  I've submitted the PR to correct it.

**Comment by evanwindom** [comment]
@TerryGLee - Please close.
