### ISSUE TITLE
About markup when adding a TextBlock control

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4566]
Hi team, 
I moved this from here: https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1869

The comments below were machine-translated

@cailte commented 3 days ago
In the section "Add a TextBlock control", a TextBlock control was added to the designer as described, but the XAML markup is different from the example.
In this environment, x: Name = "textBlock" exists in the TextBlock tag.

Also, I guess that this is related, but if you delete the added TextBlock control and add the TextBlock control again,
"Error XDG0062 Cannot register duplicate name 'textBlock' in this scope."
I get an error. Despite the deletion, it is said to be a duplicate name, and it is not clear where to correct if it is fixed.
If you change the x: Name of the re-added control, the error disappears, but it's not a fundamental solution.

&gt; Despite the deletion, the name is said to be duplicated, and I do not know where to correct it to resolve it.
About this, there seems to be a problem in the behavior of Visual Studio 2019.
When you add a control to the designer, the control information is added to memory and does not disappear when you delete the control.
Memory is released by closing the xaml file.
Even if you delete the control, you will see duplicate errors until you close the xaml file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329e32a3-766c-1739-022b-5d1a8bc6f4aa
* Version Independent ID: d74a678c-d9b5-90c4-cd63-8451fefaa887
* Content: [Hello World app with WPF in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- please pass the following information along.

@cailte -- thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by CeciAc** [comment]
Replied using HST in https://github.com/MicrosoftDocs/visualstudio-docs.ja-jp/issues/1869
