### ISSUE TITLE
[Create a load test project] Web Performance and Load Test Project [Deprecated]

### ISSUE THREAD

**Issue by dehghani-mehdi** [MicrosoftDocs/visualstudio-docs#4571]
If it's deprecated, why you mentioned and wrote about it?
What is the alternative solution?

**Comment by WilliamAntonRohm** [comment]
@dehghani-mehdi -- Medhi, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.  

You may find additional information here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by dehghani-mehdi** [comment]
@WilliamAntonRohm Hi, the first one, to more specific, this article: https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2019

I'm Mehdi, btw.

**Comment by WilliamAntonRohm** [comment]
@dehghani-mehdi -- Mehdi, thank you for clarifying.  My apologies for the typo in your name.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by dehghani-mehdi** [comment]
@WilliamAntonRohm You are welcome, I think Github allow you to edit your post and fix the typo ;)

**Comment by Mikejo5000** [comment]
For alternative solutions, there's a link to the blog post about the deprecation in the doc. Link goes here:
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/
