### ISSUE TITLE
Incorrect Mac version or name listed

### ISSUE THREAD

**Issue by remona-minett** [MicrosoftDocs/visualstudio-docs#4572]
On the [Mac Installation Documentation](https://docs.microsoft.com/en-us/visualstudio/mac/installation?view=vsmac-2019), under <b>Requirements</b>, it shows:
- A Mac with macOS <b>High Sierra 10.12</b> or above.  

This could confuse some as <i>High</i> Sierra is 10.<i>13</i>, while regular Sierra is 10.<i>12</i>.<br>
Either the software is compatible with High Sierra 10.13 or above, or Sierra 10.12 or above. At the moment I have successfully installed it on High Sierra 10.13. I don't know about 10.12.

**Comment by ghogen** [comment]
Submitting fix in private repo. Thanks for your contribution.
