### ISSUE TITLE
Example does not work on Mac and Linux

### ISSUE THREAD

**Issue by geekox86** [MicrosoftDocs/visualstudio-docs#4575]
I tried the same example step-by-step on my Mac with .NET Core 3.1 with no luck. When I execute dotnet msbuild Project.csproj -target:Build, it complaines that System namespace cannot be found:

CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bc6800-41dc-a7a4-5942-0f103a290cf9
* Version Independent ID: 56b974f2-30d2-ae79-2b78-7eb073ec7cd1
* Content: [Walkthrough: Creating an MSBuild Project File from Scratch - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch?view=vs-2019#feedback)
* Content Source: [docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@geekox86 -- thank you for your feedback.  You may find additional information here:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@ghogen -- please look into this potential documentation issue.

**Comment by ghogen** [comment]
The real issue is that the MSBuild docs are written for Visual Studio on Windows, and haven't been tested on the Mac with .NET Core.  This could a larger work item.

**Comment by mores** [comment]
Example does not work on Mac nor Linux
