### ISSUE TITLE
How do you configure the debugger when using Visual Studio?

### ISSUE THREAD

**Issue by cjblomqvist** [MicrosoftDocs/visualstudio-docs#4577]
All guidelines seems to be made for VS Code and using a launch config-file.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbb9adca-2c5c-edff-2c4e-4645579fb907
* Version Independent ID: 85cade65-f1b0-61d4-c69e-fb8ca94fefed
* Content: [Debug a JavaScript or TypeScript app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/debug-nodejs?view=vs-2019)
* Content Source: [docs/javascript/debug-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/debug-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@cjblomqvist Hi, are you trying to debug client-side scripts for minified or transpiled code? If so, those procedures are more complicated and do require the use of sourcemaps and Attach to Process, and it is similar to VS Code, but there is no launch.json file described here in this article. VS Code has an extension that simplifies the process somewhat.

**Comment by cjblomqvist** [comment]
My main problem is node is trying to open too many files simultaneously, so I get emfile errors. One way to work around it would be to skip all node modules (basically just my code)

**Comment by Mikejo5000** [comment]
Did you resolve?
I haven't test this, but you can apparently configure JS Just My Code:
https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2019#BKMK_JavaScript_Just_My_Code
If you have a template-based project, you should be able to configure some (general) properties in the properties page. If it is an "Open Folder" project, described here:
https://review.docs.microsoft.com/en-us/visualstudio/javascript/develop-javascript-code-without-solutions-projects?view=vs-2019&branch=master
you may need to configure debugging using launch.vs.json:
https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019#configure-debugging-with-launchvsjson

**Comment by cjblomqvist** [comment]
@Mikejo5000 I've had Just My Code enabled all the time. I can't open the second link. The third link is not applicable to js-files.

I think the problem is three-fold: A) There is no way to do Just my code since there's no way to configure the underlying node debugger equally well in VS as in VS Code. B) The node debugger is opening too many files simultaneously which causes issues. I've reported this to the node debugger repo (was after posting this isse). C) There is no knowledge of this documented anywhere really. It should probably be better documented what the limitations of using the node debugger in VS are.

Can't find links for you now unfortunately. From my POV, since I've already figured out the situation, you can close this issue if you want to - or you can fix C).

Thanks!

**Comment by Mikejo5000** [comment]
Fixed second link...

**Comment by cjblomqvist** [comment]
I run a multiple projects solution, where they are depending on each other. Thus, I think it'll be hard to not open the solution as a solution? (making the second link not really very applicable)

**Comment by Mikejo5000** [comment]
Closing for now unless I can get more info on C.
