### ISSUE TITLE
16.3.10 release notes missing

### ISSUE THREAD

**Issue by jespersh** [MicrosoftDocs/visualstudio-docs#4578]
The notes for 16.3.10 are missing from https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.3
![image](https://user-images.githubusercontent.com/1004198/71659128-ba9c7d80-2d46-11ea-9d8e-3e116ef93ebe.png)

**Comment by TerryGLee** [comment]
@JacquelineWiddis For some reason, I cannot assign this to you (it might be because you are not listed as a member of the “MicrosoftDocs” GitHub organization), but thanks for agreeing to take a look. :)

**Comment by JacquelineWiddis** [comment]
Issue is fixed.

**Comment by TerryGLee** [comment]
@jespersh Thanks for helping us improve our documentation! And @JacquelineWiddis, thanks for implementing the fix. Closing this issue, now.
