### ISSUE TITLE
Need to update getOwnPropertySymbols Example

### ISSUE THREAD

**Issue by mayurshedage** [MicrosoftDocs/visualstudio-docs#458]
From:

var obj = {};  
var key = Symbol('description');  

obj[key] = 'data';  

var symbols = Object.getOwnPropertySymbols(obj);  

console.log(s[0].toString()); 

To:

var obj = {};  
var key = Symbol('description');  

obj[key] = 'data';  

var symbols = Object.getOwnPropertySymbols(obj);  

console.log(symbols [0].toString());  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9d0ee8e-251b-685e-0b3b-58679b8a35ca
* Version Independent ID: 082f6ca8-5bb4-08e0-a3f1-4d2b71716449
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/object-getownpropertysymbols-function-javascript)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/reference/object-getownpropertysymbols-function-javascript.md)

**Comment by gewarren** [comment]
@mayurshedage Thanks for reporting this. If you'd like to take a stab at fixing the example yourself, there's an Edit button near the top-right of the page. We'd love to have you contribute!

**Comment by Mikejo5000** [comment]
Fix added to https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1263. Waiting to close until fix is merged

**Comment by Mikejo5000** [comment]
Merged
