### ISSUE TITLE
Configuration Manager limits builds of different configurations - add batch build

### ISSUE THREAD

**Issue by mkroels** [MicrosoftDocs/visualstudio-docs#4582]
If a project has several different configurations to be built, the Build Solution cannot build them all. The issue is that the Configuration Manager limits 1 project configuration to build. My recommendation is to include as a reference the Bulk Build option which allows any possible build configuration within the solution to be built.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b17767-3a4a-fd12-4690-e772b8aaccc6
* Version Independent ID: 2d66b972-2b14-49a4-4198-44214ce8574a
* Content: [Understand build configurations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/understanding-build-configurations?view=vs-2019#feedback)
* Content Source: [docs/ide/understanding-build-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/understanding-build-configurations.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by ZimFromIRK** [comment]
I agree, and it needs to also state that if there is even one VB.NET project in the solution, the Batch Build option is not available.  I have one such legacy project in a solution with 100+ C++ components and maybe 15 C#.NET components, but the one VB.NET component causes batch build to be unavailable.

**Comment by ghogen** [comment]
Thanks, I am looking into this now and will update the docs accordingly.  @ZimFromIRK you might also want to submit the suggestion to allow VB.NET components to participate in Batch Build on the [Dev Community](https://developercommunity.visualstudio.com/spaces/8/index.html) site.
