### ISSUE TITLE
Inheritdoc now available in Visual Studio 2019 16.4

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/visualstudio-docs#4583]
What needs to be documented:
- [ ] Overridden methods automatically inherit. [Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#net-productivity-164GA)
- [ ] How to use the inheritdoc tag. Inheritdoc is a standard existing outside of Msft and we should link to the official inheritdoc documentation.

![image](https://user-images.githubusercontent.com/8293542/71748626-ff4c1580-2e27-11ea-946c-8573c335af33.png)

The inheritdoc tag in a doc summary like the example below will be inherited:
```csharp
/// <summary>

/// <item><inheritdoc/></item>

/// </summary>
```

The class inheriting the doc will need this comment:
```csharp
///<inheritdoc cref = "MyClass" />
```

**Comment by WilliamAntonRohm** [comment]
@kendrahavens -- Kendra, thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.

**Comment by kendrahavens** [comment]
Thanks! 

This could be captured in a few places: 
- https://docs.microsoft.com/en-us/dotnet/csharp/codedoc
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/
- https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/recommended-tags-for-documentation-comments
  - Since each tag has there own page in the 'Recommended-tags-for-documentation-concepts' it be good to have a page with inherit doc examples.

**Comment by WilliamAntonRohm** [comment]
@kendrahavens -- Kendra, thank you for your considered suggestions.

@BillWagner -- Bill, please look into this issue, or re-assign it to this domain's author.

**Comment by kendrahavens** [comment]
@mikadumont for review/visibility.

**Comment by BillWagner** [comment]
@mikadumont had written [this article](https://docs.microsoft.com/dotnet/csharp/programming-guide/xmldoc/inheritdoc) which covers the new `<inheritdoc>` tag. 

I'll close this as resolved.
