### ISSUE TITLE
Wrong property "AdditionalComposeFiles" listed in the "Docker Compose MSBuild properties" table

### ISSUE THREAD

**Issue by AGiorgetti** [MicrosoftDocs/visualstudio-docs#4586]
the property named: "AdditionalComposeFiles" is wrong, it should be replaced by "AdditionalComposeFilePaths".

**Comment by WilliamAntonRohm** [comment]
@AGiorgetti -- Alessandro, please let us know which topic has this table and I'll update it.

**Comment by AGiorgetti** [comment]
sorry, the page I was referrring to is this one: 
https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019

I must have clicked the wrong "feedback" button, I thought I used the contextual "This Page" one.

**Comment by WilliamAntonRohm** [comment]
@AGiorgetti -- Alessandro, thank you for that information. 

@ghogen -- Gordon, please review the above-mentioned PR 5995.

**Comment by ghogen** [comment]
Thanks, I can confirm the change is correct.
