### ISSUE TITLE
Installation Locations

### ISSUE THREAD

**Issue by timg11** [MicrosoftDocs/visualstudio-docs#4587]
Moving the Visual Studio IDE to a non-system drive only reduces the system drive size from 15 GB to 12 GB.  How do I move the remaining 12 GB to the alternate drive?  All three install paths are on non-system drives, yet the install results in 12G onto the system drive and 9.6 G on all the other drives???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f065a76a-2046-ebfd-2aa2-ebb0afbc4110
* Version Independent ID: f3501eb1-bfa1-1c2e-9e05-bc0f1fa8971d
* Content: [Select installation locations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/change-installation-locations?view=vs-2019#feedback)
* Content Source: [docs/install/change-installation-locations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/change-installation-locations.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@timg11 -- Tim, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
