### ISSUE TITLE
Change marker colors in map mode 

### ISSUE THREAD

**Issue by richardhauer** [MicrosoftDocs/visualstudio-docs#4588]
I'm sure at some point I learned how to change the marker colors for map mode.  Please include some directions on this. 

When VS is using a "dark" theme many of the markers are too low contrast to see.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9440cd51-f00a-2a66-c895-0c093c6c883d
* Version Independent ID: 77cf076b-949f-ce9a-882f-7a0c02d268d0
* Content: [Scroll bar map mode and bar mode - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-track-your-code-by-customizing-the-scrollbar?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by richardhauer** [comment]
@TerryGLee   Is there somewhere I can see progress on this? Is there anything to see?

**Comment by TerryGLee** [comment]
@richardhauer Unfortunately, it doesn't look like you can change the colors of the markers. However, you *can* change the colors in the map mode scroll bar, and perhaps that might suffice to increase the contrast. 

Here's how: From the menu bar in Visual Studio, select **Tools** > **Options** > **Environment** > **Fonts and Colors**. Next, in **Display items**, choose any of the items that are preceded with "Overview", make the color changes you want, and then choose **OK**.

![image](https://user-images.githubusercontent.com/23244653/77126563-ca069b00-6a06-11ea-9c6e-0e536f75b4e6.png)

I've added this info to the bottom of the [How to: Customize the scroll bar](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-track-your-code-by-customizing-the-scrollbar) page. 

As a further FYI: 
- If you'd like to make a feature request to add functionality to the product, see the [Suggest a feature for Visual Studio](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page for more information about how to do so. 
- And, if you'd like to customize the colors in Visual Studio more than what's currently included in the product, you might consider using the [Visual Studio Color Theme Designer](https://marketplace.visualstudio.com/items?itemName=ms-madsk.ColorThemeDesigner) extension.

I am closing this issue now. Thanks for helping us improve the documentation!
