### ISSUE TITLE
How does one replace the existing "Clean" target?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#459]
I have a powershell script that will properly clean all the output directories and not just some of them. I'd like to be able to invoke it for whatever the current project or solution is instead of having to add targets in each project. Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868d865b-89d9-ec87-d569-862d168dc6ca
* Version Independent ID: a95f34e2-8f4b-4a4b-cb7e-075e4ceebd69
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/msbuild/how-to-extend-the-visual-studio-build-process.md)

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, do you have any thoughts, or is this out of scope?

**Comment by rainersigwald** [comment]
@StingyJack Can you clarify what you mean by 

> I'd like to be able to invoke it for whatever the current project or solution is instead of having to add targets in each project.

? Do you mean that you want to override the Clean target for every project (but only have to define it in one place), or that you want to cause a script of your own to run when hitting "clean" in Visual Studio, or something else?

**Comment by StingyJack** [comment]
I think just the replacement of the Clean actions (Clean and Rebuild) actions in VS, as it does not clean properly and I'm tired of weird and time consuming bugs from it leaving bits that interfere or from it trying to help me and including bits it couldn't find where i told it to look.

**Comment by StingyJack** [comment]
I just found and read through [this exchange](https://github.com/Microsoft/msbuild/issues/2408).

> The intuitive goal of the Clean target is to delete everything produced by previous non-clean runs

The difference in the interpretation of this is with the meaning of "previous". I need Clean to delete all previous non-clean runs, yet it looks to only make a best attempt at removing the results of a single immediately previous non-clean run for the selected configuration.

**Comment by Mikejo5000** [comment]
Closing as this is a product issue. This could be treated as a feature suggestion or a bug. If you want to make a feature suggestion, please do so on [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8). To report it as a bug, use the Send Feedback link in Visual Studio (upper right).

**Comment by ghogen** [comment]
I added two examples that show extending/customizing the Clean functionality.
