### ISSUE TITLE
This page no help

### ISSUE THREAD

**Issue by jeeptrick** [MicrosoftDocs/visualstudio-docs#4591]
The Visual Studio Community addition FLAT OUT WONT INSTALL.  I download it.  Run the web installer, it downloads a bunch of files then closes.  THAT IT.  NO INSTALL.  Also tried offline.  That is also BROKE.   No Log error or Error messages.

Boot strapper log.
Beginning of the log. Start Time: 1/5/2020 10:44:20 PM
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: Commandline arguments = --env,_SFX_CAB_EXE_PACKAGE:C:\vslayout\vs_setup.exe _SFX_CAB_EXE_ORIGINALWORKINGDIR:C:\vslayout
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: Parent process name = vs_setup
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: Parent process product version = 16.4.29613.14
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: CampaignId = 
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: ResponseId not available in 'vs_setup_bootstrapper.config'. Trying to parse filename.
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: loading config settings: -update --update --layout -offline --offline --locale --layout --originalworkingdir --installLayoutPath --env
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: DownloadURL = https://aka.ms/vs/16/release/installer
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: InstallLocation = C:\Program Files (x86)\Microsoft Visual Studio\Installer
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: OfflineFilePath = C:\vslayout\vs_installer.opc
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: LayoutLocation = 
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: ExecutableArguments = /finalizeInstall install --layoutPath "C:\vslayout" --in "C:\vslayout\Response.json" --locale en-US --activityId "82e3d2e8-3592-4344-ad4b-06d4dcd06074"
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: OSVersion = Microsoft Windows NT 6.1.7601 Service Pack 1
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: Starting to detect the existing VS and .NET...
VisualStudio Bootstrapper:1/5/2020 10:44:20 PM: Finished detecting the existing VS and .Net
VisualStudio Bootstrapper:1/5/2020 10:44:27 PM: Comparing client version '2.4.1080.1113' to autoSelfUpdateMinVersion '2.4.1080.1113'
VisualStudio Bootstrapper:1/5/2020 10:44:27 PM: Current OptIn value is 1
VisualStudio Bootstrapper:1/5/2020 10:44:27 PM: Comparing client candidate version '2.4.1080.1113' to autoSelfUpdateMinVersion '2.4.1080.1113'
VisualStudio Bootstrapper:1/5/2020 10:44:27 PM: Start named pipe: 758f6394-c0ee-4780-888e-50035205964e
VisualStudio Bootstrapper:1/5/2020 10:44:27 PM: Starting VS setup process 'vs_installer.exe' with arguments '/finalizeInstall install --layoutPath "C:\vslayout" --in "C:\vslayout\Response.json" --locale en-US --activityId "82e3d2e8-3592-4344-ad4b-06d4dcd06074" --pipe "758f6394-c0ee-4780-888e-50035205964e"'.
VisualStudio Bootstrapper:1/5/2020 10:44:27 PM: VS setup process C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe started. All done.
VisualStudio Bootstrapper:1/5/2020 10:44:27 PM: VS setup process starting. Exiting with code 0
VisualStudio Bootstrapper:1/5/2020 10:45:06 PM: Pipe disconnected.
VisualStudio Bootstrapper:1/5/2020 10:45:06 PM: Bootstrapper Successfully completed.

dd_vs_setup_decompression_log

[1/5/2020, 22:44:18] === Logging started: 2020/01/05 22:44:18 ===
[1/5/2020, 22:44:18] Executable: C:\vslayout\vs_setup.exe v16.4.29613.14
[1/5/2020, 22:44:18] --- logging level: standard ---
[1/5/2020, 22:44:18] Directory 'C:\Users\Gary\AppData\Local\Temp\86f84d9f0dae585fe5996b7d50f990\' has been selected for file extraction
[1/5/2020, 22:44:18] Extracting files to: C:\Users\Gary\AppData\Local\Temp\86f84d9f0dae585fe5996b7d50f990\
[1/5/2020, 22:44:18] Extraction took 156 milliseconds
[1/5/2020, 22:44:18] Executing extracted package: 'vs_bootstrapper_d15\vs_setup_bootstrapper.exe ' with commandline '  --env "_SFX_CAB_EXE_PACKAGE:C:\vslayout\vs_setup.exe _SFX_CAB_EXE_ORIGINALWORKINGDIR:C:\vslayout"'
[1/5/2020, 22:45:6] The entire Box execution exiting with result code: 0x0
[1/5/2020, 22:45:6] Launched extracted application exiting with result code: 0x0
[1/5/2020, 22:45:6] === Logging stopped: 2020/01/05 22:45:06 ===

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by WilliamAntonRohm** [comment]
@jeeptrick, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
