### ISSUE TITLE
Please update for Azure Service Bus

### ISSUE THREAD

**Issue by Camios** [MicrosoftDocs/visualstudio-docs#4592]
Connection string shows protcol/schema is "sb" - is that correct?
DNS endpoint is a "*.servicebus.windows.net".
Not sure about port numbers.

Connection string starts like "Endpoint=sb://[site].servicebus.windows.net/;..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019#feedback)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by ornellaalt** [comment]
Added.
