### ISSUE TITLE
Update documentation table to indicate IReadOnlyDictionary => Dictionary

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#4593]
On https://github.com/dotnet/roslyn-analyzers/pull/3149 the rule was updated to suggest the `Dictionary` suffix for types implementing `IReadOnlyDictionary` instead of the former `Collection`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83202117-8bd8-aa22-d55c-42ecc59fc11f
* Version Independent ID: 2374ea4f-0f8d-283e-5803-7c8de04b48f7
* Content: [CA1710: Identifiers should have correct suffix - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1710?view=vs-2019#rule-description)
* Content Source: [docs/code-quality/ca1710.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1710.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Evangelink -- Amaury, thank you for your feedback.  That page appears to be up-to-date, noting:

> Types that implement IDictionary have names that end with the word 'Dictionary' even if the type also implements IEnumerable or ICollection. 

Please let me know if that is sufficient.

**Comment by Evangelink** [comment]
@WilliamAntonRohm Types implementing [IReadOnlyDictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlydictionary-2?view=netframework-4.8) do not usually implement `IDictionary` so the statement is inaccurate (that was the goal of the PR).

The idea would be to add in the table the following mapping `System.Collections.Generic.IReadOnlyDictionary<TKey,TValue>` to `Dictionary`. And also, to update the quoted statement from `Types that implement IDictionary` to `Types that implement IDictionary or IReadOnlyDictionary`.

Thanks

**Comment by WilliamAntonRohm** [comment]
@Evangelink -- Amaury, thank you for clarifying.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
Updating doc
