### ISSUE TITLE
[VS] Add DockerDevelopmentMode property for Docker Compose projects

### ISSUE THREAD

**Issue by dbreshears** [MicrosoftDocs/visualstudio-docs#4594]
We added the "DockerDevelopmentMode" property recently for Docker Compose projects.   The  [https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019)](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019) article should be updated to reflect this property.     This is identical to the "ContainerDevelopmentMode" property for single

Controls whether "build-on-host" optimization ("Fast Mode" debugging) is enabled. Allowed values are Fast and Regular.    Default is Fast

**Comment by ghogen** [comment]
This is fixed now.

**Comment by MitkoZ** [comment]
@dbreshears @ghogen The article still hasn't been updated. (https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019)

**Comment by ghogen** [comment]
@MitkoZ This was added to the branch for Visual Studio 2019 update 16.5, which is scheduled to be published when the final 16.5 release is published.  I will leave this issue open until the change is published.  The property is "ContainerDevelopmentMode."

**Comment by ghogen** [comment]
The change is published live now.

**Comment by MitkoZ** [comment]
@ghogen Do you mean DockerDevelopmentMode instead of ContainerDevelopmentMode as @dbreshears said?

**Comment by ghogen** [comment]
If this property is DockerDevelopmentMode, not ContainerDevelopment mode, I will fix it now.
