### ISSUE TITLE
Remove Visual Studio Installer

### ISSUE THREAD

**Issue by Stannieman** [MicrosoftDocs/visualstudio-docs#460]
In containers you probably never want to update/modify the installed build tools, but instead just build a new image. Because of that it would be nice to uninstall the VS Installer after the build tools are installed to keep image size down. I tried to run '"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" /uninstall' which is the uninstall string found in the registry, but it doesn't work. I also tried with --uninstall --quiet --passive and a lot of combinations of these switches but none of them seem to actually remove the installer.

Is there any way this can be done apart from manually removing the folder from program files (which is rather hacky)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container#step-5-create-and-build-the-dockerfile)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/install/build-tools-container.md)

**Comment by gewarren** [comment]
@TerryGLee can you ask someone on the product team?

**Comment by TerryGLee** [comment]
Acknowledged; I'll check in with the appropriate parties and report back.

**Comment by heaths** [comment]
The Installer is not installed, really. Deleting the Installer folder is all you need to do.

**Comment by TerryGLee** [comment]
@Stannieman Does the response from HeathS answer your inquiry?

**Comment by Stannieman** [comment]
@TerryGLee sorry for the late response but yes, the answer is clear and I know what to do!

**Comment by TerryGLee** [comment]
@Stannieman Thanks; I'll close this, then. :)

**Comment by RNiss** [comment]
I have a follow up question to @heaths's answer. Microsoft Visual Studio Installer (MSVI) is listed in Windows 10 the apps list. Simply deleting the Installer folder, will not clear it from the list.
It seems that the deletion-type solution is not win10-oriented.
Do you know of another way that will also clear it from the app list?
Thanks!

![image](https://user-images.githubusercontent.com/46282695/50562627-639f3b00-0ce3-11e9-9b6b-554211b7575c.png)

**Comment by heaths** [comment]
We do write the necessary registry to show up here so it can be easily removed via the Settings app. This question was in the context of containers and clearing space, so if you're seeing that you're not in a container. The registry values we write should be no more than 1KB.

This isn't about how to complete remove the installer. If you want to do that in a physical or virtual machine, use the entry you see above instead of deleting the folder.

**Comment by TopGuo** [comment]
how public production winform pro.
