### ISSUE TITLE
Add Load test?  This option is not available after installing and restarting.  

### ISSUE THREAD

**Issue by FF2bricker** [MicrosoftDocs/visualstudio-docs#4601]
I can't get the option to add load test?  When creating a new load test project like above.  The option to add a load test is not there.
Do I have to connect to Azure?
Seems like I have to install something else or use some other framework?
"I wish there was better testing tools after azure load test is gone!"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5d3f6388-1ee7-b304-4255-d7b5822ef999
* Version Independent ID: 86d2beba-3186-0ed0-8770-ec7eb5a6f17b
* Content: [Create and run a load test - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-create-and-run-a-load-test?view=vs-2019)
* Content Source: [docs/test/walkthrough-create-and-run-a-load-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-create-and-run-a-load-test.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@FF2bricker -- It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

You may also find information here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@Mikejo5000 -- please look into possible clarifications in this topic.

**Comment by Mikejo5000** [comment]
@FF2bricker, sorry for the delayed response. Did you install the "web performance and load testing tools" component? Described here:
https://docs.microsoft.com/en-us/visualstudio/test/quickstart-create-a-load-test-project?view=vs-2019
@PBoraMSFT for additional input.

**Comment by Mikejo5000** [comment]
Adding a note about the required component.
