### ISSUE TITLE
The Runtime category ? is missing

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4602]
Trying to run IntelliTest can result in things like "Need help to find Types" that comes up in the warnings as "runtime warning", not as a "domain" warning. 

I'm not sure if the program is wrongly displaying the warning type or this document is incorrect. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 426d7e5f-94c3-2947-fe82-c62136032bff
* Version Independent ID: b6e7abd7-168f-37cd-a548-13c581862e88
* Content: [Warnings and errors - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/intellitest-manual/warnings-and-errors?view=vs-2019)
* Content Source: [docs/test/intellitest-manual/warnings-and-errors.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/intellitest-manual/warnings-and-errors.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by msebolt** [comment]
@StingyJack Thank you for the feedback, assigning this to the author for review.

Type `runtime` is not listed as a category.  Please attach additional details and/or a screenshot so we can further investigate.

**Comment by StingyJack** [comment]
@msebolt - here is an image that shows the Runtime Warnings
![image](https://user-images.githubusercontent.com/15381181/72112215-f6b57c80-330a-11ea-9b1d-f587be4cc935.png)

I deleted the intellitest created project I had with the specific "Need help to find Type", but can probably find it in my autoshelves if the above is not satisfactory to show the Runtime category

**Comment by Mikejo5000** [comment]
Checking on this...

**Comment by Mikejo5000** [comment]
Updating doc, per product unit feedback

**Comment by StingyJack** [comment]
@TedA-M I'm not clear on what was fixed or done here. Is there a PR or commit link somewhere that I'm missing?

**Comment by TedA-M** [comment]
@StingyJack I'm not sure why it said I closed this. I made a couple pencil edits to fix blocking issues in this PR https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6107, and merged that PR..

**Comment by Mikejo5000** [comment]
@StingyJack We often include special comments that auto-close associated issues when the PR gets merged into master. It should be live around 5 PM tonight. The PM suggested I change the Domain category to "Domain or Runtime".
