### ISSUE TITLE
Please list all options

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/visualstudio-docs#4603]
I know Intellisense can list out what JSON attributes are possible, but it would really help if this page had a list of all arguments, what they did, and under what runtime environment they are used.

This is partly in response to another open ticket I have https://github.com/MicrosoftDocs/visualstudio-docs/issues/4584 when I found 'args' doesn't pass through to Node.exe. 

The fix for THAT issue probably belongs here, not on that page. Please update as appropriate or you think best.

Thank you guys, I love the living documentation.

        == John ==

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f6ef2c-e616-bf4c-6de4-1448814e4f73
* Version Independent ID: b223e86b-b0d8-3a78-3fe5-0938e6641042
* Content: [Customize build debug tasks using tasks.vs.json launch.vs.json - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019#configure-debugging-with-launchvsjson)
* Content Source: [docs/ide/customize-build-and-debug-tasks-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/customize-build-and-debug-tasks-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
Thank you John for your compliment!

@TerryGLee -- the other issue referenced above (#4584) is already in Mike's hands.
