### ISSUE TITLE
This page needs a "How to make this work with DI"

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4604]
All I've been able to get out of Intellitest and Pex in the last 8+ years are unit tests for trivial or nonsensical inputs. Otherwise its an error or warning to the effect of "i dont know how to construct this object", even after supplying a type in the intellitest created unit test project with a `[PexUseType(typeof(TypePexNeverSeemsToUse))]`. "Fix"ing it takes me to a factory method that just looks silly.

At this point I would have expected that something be available that can generate a set of tests for existing code, so that if I change something I can know if it broke something elsewhere in the code. It needent be perfect, but that would make this feature worth an Enterprise subscription.

The docs are written for someone who has their head in academics of unit testing and not in practical programming.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b8edaf-7667-a3e6-38dc-371c53bcd386
* Version Independent ID: 580e757e-8ce7-1437-3843-c88ff4f3ab54
* Content: [Generate unit tests for your code with IntelliTest - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/generate-unit-tests-for-your-code-with-intellitest?view=vs-2019#q--a)
* Content Source: [docs/test/generate-unit-tests-for-your-code-with-intellitest.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/generate-unit-tests-for-your-code-with-intellitest.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@StingyJack Thank you for the feedback.

Please refer to [here](https://docs.microsoft.com/visualstudio/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing?view=vs-2019) for information on **Microsoft Fakes** and how to use stubs and shims to isolate dependencies as opposed to DI to see if this alleviates the issue.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
