### ISSUE TITLE
Same Problem

### ISSUE THREAD

**Issue by Mr-jiayunfei** [MicrosoftDocs/visualstudio-docs#4606]
I need your help.i get the same problem that cannot find buildTools folder in docker?how do you fix this problem?

**Comment by WilliamAntonRohm** [comment]
@Mr-jiayunfei -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.  

You may find information here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
