### ISSUE TITLE
Requirements for installing VS 2019 for Mac wrong

### ISSUE THREAD

**Issue by ColbyRingeisen** [MicrosoftDocs/visualstudio-docs#4609]
The requirements for installing VS 2019 for Mac listed on this page do not match the requirements listed in the VS 2019 for Mac release notes at this page: https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2019-system-requirements-mac

I installed VS 2019 for Mac on macOS 10.15.2 but with Xcode 10.3 instead of Xcode 11 (my code base requirement). When I attempt the 'Pair to Mac' from a Windows 10 system with VS 2019 in order to build an Xamarin.iOS project it fails saying "The Xcode version installed on the Mac (10.3) is not compatible with this version of Visual Studio. This may cause unexpected warnings or errors when building and deploying iOS projects. Please install Xcode '11.2' or visit the documentation to learn more."

It seems the mac being paired from a Windows system to build Xamarin.iOS projects requires Xcode 11 and does not work with Xcode 10.  Unfortunately, there are no separate requirements listed for Xamarin.iOS as the Xamarin.iOS document page points the user to the requirements listed on this page (which appear to be wrong).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3989ef3-79d0-03b7-6a17-749ee96b9550
* Version Independent ID: 3a66757e-649d-6415-ff5e-00d628eb17f6
* Content: [Install Visual Studio 2019 for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/installation?view=vsmac-2019)
* Content Source: [mac/installation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/installation.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment]
@ColbyRingeisen -- It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 @heiligerdankgesang -- please look into this issue.

**Comment by ColbyRingeisen** [comment]
Thanks William, but I am not having an issue with installation.  I have an issue with the documentation listed two different versions of Xcode as a dependency for Xamarin.iOS projects.  Which is it, "Xcode 10.0 or above" as indicated on this page or "The latest version of Xcode 11 requires macOS Mojave 10.14, therefore Xamarin.iOS and Xamarin.Mac projects also require that minimum version" as indicated in the VS 2019 Release Notes?

**Comment by WilliamAntonRohm** [comment]
@ColbyRingeisen -- thank you for clarifying.

**Comment by heiligerdankgesang** [comment]
The system requirements page outlines the minimum system requirements for the Visual Studio 2019 for Mac IDE itself. For the latest information on what included workloads require, please look to the release notes.

Thank you.

@WilliamAntonRohm this can be closed.
