### ISSUE TITLE
A empty feature appears in roadmap.

### ISSUE THREAD

**Issue by PlusoneWang** [MicrosoftDocs/visualstudio-docs#4611]
As the screenshot shown below, a row with no feature description appears in roadmap table(2019 Q4 (October-December)).  
Page URL: https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap
![screenshot](https://user-images.githubusercontent.com/37727068/72036223-1b8efd00-32d5-11ea-9c6d-46efcd15a037.png)

**Comment by TerryGLee** [comment]
@JacquelineWiddis Is this something that you can help with?

**Comment by PlusoneWang** [comment]
This issue seems to has been fixed a few days ago.

**Comment by TerryGLee** [comment]
@PlusoneWang Thanks for initially reporting this and then following up. We appreciate your helping us improve our documentation!
