### ISSUE TITLE
BuildInParallel default value is true?

### ISSUE THREAD

**Issue by mx-bernhard** [MicrosoftDocs/visualstudio-docs#4612]
> When BuildInParallel is set to true (its default value is false), 

Is this still valid? Our tests, the files Microsoft.Common.CrossTargeting.targets and Microsoft.Common.CurrentVersion.targets beg to differ:
```
    <BuildInParallel Condition="'$(BuildInParallel)' == ''">true</BuildInParallel>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a625a3cf-0959-49fc-d5ee-af8971bce20c
* Version Independent ID: ddfe2557-53b6-5cff-c7b9-4a729f53ce70
* Content: [Building Multiple Projects in Parallel with MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/building-multiple-projects-in-parallel-with-msbuild?view=vs-2017#feedback)
* Content Source: [docs/msbuild/building-multiple-projects-in-parallel-with-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/building-multiple-projects-in-parallel-with-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Thanks, you're right, the default value is 'true', even without the settings in the target files. Updated the topic.

**Comment by hickford** [comment]
According to https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-task?view=vs-2022


> **BuildInParallel**: Optional Boolean parameter. If true, the projects specified in the Projects parameter are built in parallel if it is possible. **Default is false.**
