### ISSUE TITLE
Proposal for improving section "Attach to an app from the XAML designer"

### ISSUE THREAD

**Issue by ackh** [MicrosoftDocs/visualstudio-docs#4613]
Recently, I needed to debug a custom XAML control at design time. I tried this by following the [documentation](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-at-design-time?view=vs-2019#attach-to-an-app-from-the-xaml-designer) available for that topic. However, I just couldn't make it work. Eventually, I created an issue regarding this [here](https://developercommunity.visualstudio.com/comments/877734/view.html). A Micrososft engineer's response (see comments) to that issue finally pointed out the missing steps required to make design time debugging work for me.

I have combined the steps given by that Microsoft engineer and those given in the existing documentation and created my own description on how to debug XAML controls at design time. My proposal is to change the documentation as follows:

Instead of the title **Attach to an app from the XAML designer** I propose **Debug a custom XAML control at design time by attaching to Visual Studio's XAML designer**.

Replace the steps associated with the above mentioned title with the following description:

1. Open your solution/project in a first Visual Studio instance.
2. Build the solution/project.
3. Open the XAML page containing the custom control you want to debug.
For UWP projects targeting Windows build 16299 or above, this step will start the UwpSurface.exe process. For WPF or UWP versions prior to 16299, this step will start the XDesProc.exe process.
4. Open a second Visual Studio instance. Do not open a solution/project in that instance.
5. In the second Visual Studio instance open the "Debug" menu and choose "Attach to Process…".
6. Depending on your project (see step 3), select either the UwpSurface.exe or the XDesProc.exe process from the list of available processes.
7. In the "Attach to:" field of that dialog, choose the correct code type for the custom control you want to debug. If your custom control has been written in a .NET language, choose the appropriate .NET code type such as "Managed (CoreCLR)". If your custom control has been written in C++, choose "Native".
8. Attach the second Visual Studio instance by clicking the "Attach button".
9. In the second Visual Studio instance open the code files associated with the custom control you want to debug. Make sure to just open these files, not the entire solution/project.
10. Place the necessary breakpoints in the previously opened files.
11. In the first Visual Studio instance close the XAML page you opened in step 3.
12. In the first Visual Studio instance open the XAML page you closed in the previous step. This will cause the debugger to stop at the first breakpoint you set in the second Visual Studio instance.
13. Debug the code in the second Visual Studio instance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c195bbb1-22be-9da7-9792-1c829d73a21b
* Version Independent ID: 0d83875a-56c4-d897-e771-aa3ef9bf910d
* Content: [Debug at design time - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-at-design-time?view=vs-2019)
* Content Source: [docs/debugger/walkthrough-debugging-at-design-time.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-debugging-at-design-time.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@ackh -- thank you for your feedback and thorough improvements.

**Comment by Mikejo5000** [comment]
Good feedback, thanks! Updating doc.
