### ISSUE TITLE
Update documentation to mention API surface configurability

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#4615]
See https://github.com/dotnet/roslyn-analyzers/pull/3176#discussion_r364393391

This page shall be updated to add the sub-section about API surface compatibility as it is done on https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1000?view=vs-2019#configurability

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0880ab33-6c9a-2541-880b-352e8a68043e
* Version Independent ID: 29e9a293-d06a-5a77-4b7e-cebf29df4c41
* Content: [CA1021: Avoid out parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1021?view=vs-2019)
* Content Source: [docs/code-quality/ca1021.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1021.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by mavasani** [comment]
This should be similar to existing rules which support this configuration option:

1. See last line of https://docs.microsoft.com/visualstudio/code-quality/ca1000#cause
2. See the note with example here: https://docs.microsoft.com/visualstudio/code-quality/ca1000#configurability

**Comment by WilliamAntonRohm** [comment]
@mavasani -- please look into this issue.
