### ISSUE TITLE
Incorrect VS installation instructions

### ISSUE THREAD

**Issue by ojizero** [MicrosoftDocs/visualstudio-docs#4616]
Unsure if this is a bug in the installer or in the documentation, but the instructions for installing VS Build Tools seems to be incorrect as they don't work properly. Assuming this is a mistake in the documentation then it should be fixed, I assume as follows:

The following line from the Dockerfile example
```dockerfile
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --all `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0
```

Should be replaced by the following, using PowerShell
```dockerfile
RUN `
    powershell -Command `
    Start-Process -FilePath 'C:\TEMP\vs_buildtools.exe' -Wait `
    -ArgumentList `
    '--quiet', `
    '--norestart', `
    '--nocache', `
    '--installPath C:\BuildTools', `
    '--all', `
    '--remove Microsoft.VisualStudio.Component.Windows10SDK.10240', `
    '--remove Microsoft.VisualStudio.Component.Windows10SDK.10586', `
    '--remove Microsoft.VisualStudio.Component.Windows10SDK.14393', `
    '--remove Microsoft.VisualStudio.Component.Windows81SDK' ;
```

And I think doing it in batch would be something like this (haven't tested it properly yet will update this when I get a chance to test it)
```dockerfile
RUN `
    start /WAIT "" `
    C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --all `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by ojizero** [comment]
This seems to have been encounter by others for example #4514

**Comment by Mr-jiayunfei** [comment]
I tried your way but it didn't work,can you offer a complete dockfile to me?

**Comment by ojizero** [comment]
@Mr-jiayunfei up to the point of installing VS build tools this is the Dockerfile

```dockerfile
# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2019 AS build
SHELL [ "powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';" ]

RUN `
  New-Item -Path C:\Downloads -ItemType Directory ; `
  Invoke-WebRequest 'https://aka.ms/vs/15/release/vs_buildtools.exe' -OutFile C:\Downloads\vs_buildtools.exe -UseBasicParsing ; `
  Invoke-WebRequest 'https://download.microsoft.com/download/E/4/1/E4173890-A24A-4936-9FC9-AF930FE3FA40/NDP461-KB3102436-x86-x64-AllOS-ENU.exe' -OutFile C:\Downloads\dotnet-installer.exe -UseBasicParsing ;
RUN `
  New-Item -Path C:\Nuget -ItemType Directory ; `
  Invoke-WebRequest 'https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe' -OutFile C:\Nuget\nuget.exe -UseBasicParsing ;

RUN `
  Start-Process -filepath 'C:\Downloads\dotnet-installer.exe' -Wait -ArgumentList '/q' ; `
  Start-Process -FilePath 'C:\Downloads\vs_buildtools.exe' -Wait `
    -ArgumentList `
      '--quiet', `
      '--norestart', `
      '--locale en-US', `
      '--installPath C:\BuildTools', `
      '--all', `
      '--remove Microsoft.VisualStudio.Component.Windows10SDK.10240', `
      '--remove Microsoft.VisualStudio.Component.Windows10SDK.10586', `
      '--remove Microsoft.VisualStudio.Component.Windows10SDK.14393', `
      '--remove Microsoft.VisualStudio.Component.Windows81SDK' ; `
  $PATH = $env:PATH + ';C:\Nuget;C:\BuildTools\MSBuild\15.0\Bin' ; `
  Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name PATH -Value $PATH ;
```

Please note I am using PowerShell as the main shell for building the image so it could be why it didn't work for you ¯\_(ツ)_/¯

**Comment by Mr-jiayunfei** [comment]
ok,thank you very much,i will try it

**Comment by ornellaalt** [comment]
Hi @ojizero, we've updated the Build Tools documentation [here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019). Please give the new instructions a try. We look forward to your feedback, and I'll be closing out this issue in the meantime.

**Comment by tobyhu87** [comment]
@ojizero , can you please install the latest docker and then try to latest instructions in our doc page?

**Comment by matthiasng** [comment]
@ornellaalt, @tobyhu87 why is this issue closed (and a number of others with the same problem) ?
Do you close the issues without reading them?
Their is still no hint/fix in the docs about the vs_buildtools.exe(only v15, v16 works) wait problematic

**Comment by tobyhu8787** [comment]
> @ornellaalt, @tobyhu87 why is this issue closed (and a number of others with the same problem) ?
> Do you close the issues without reading them?
> Their is still no hint/fix in the docs about the vs_buildtools.exe(only v15, v16 works) wait problematic

Hi @matthiasng we fixed the syntax errors in the instructions and the instructions should work for the latest VS 2017 and VS 2019 and Docker container.

If you are seeing new issues or if something doesn't work right, please open a feedback ticket.

thanks, Toby.
