### ISSUE TITLE
How do you change the column order after adding them to the list?

### ISSUE THREAD

**Issue by duncanspeidel** [MicrosoftDocs/visualstudio-docs#4619]
I have created a list that has many site columns.  I would like to move several to the top of the list.  In Visual Studio in the columns tab of the list I can only delete them or add more.  In the Views tab I can change the order and that changes the order for after they are created but not on the creation screen.  Is there a way to change the order without deleting them all and re-adding them or hacking the schema.xml?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7178d59e-622a-fcd3-0d76-229a8b42dfc0
* Version Independent ID: 691c82da-8ed3-6dc0-b37e-b5e4c219f2c2
* Content: [Create site column, content type, and list for SharePoint - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint?view=vs-2019)
* Content Source: [docs/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/sharepoint/walkthrough-create-a-site-column-content-type-and-list-for-sharepoint.md)
* Product: **visual-studio-windows**
* Technology: **sharepoint-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@duncanspeidel -- Thanks for your question.  You may find additional information here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@John-Hart -- Please look into this potential documentation issue.

**Comment by John-Hart** [comment]
@duncanspeidel, the list editor in Visual Studio does not allow you to reorder the fields.  The easiest way is to add them in the order you want. However, you can either reorder the fields on the View tab or if you want the Edit view to be in a certain order you can edit the <Fields> element manually in the Schema.xml for the list.

**Comment by duncanspeidel** [comment]
Yo cannot change the order using VS.  The view tab changes how they are displayed on read page, it does not change how they are displayed on the create page.  You can change the order on the create page by editing the schema.xml.  This works but you have to be very careful because if you screw that file up, your code will not compile.  If you add more fields to the list later you might lose the changes you made for the order.  I would highly recommend keeping a backup handy.
