### ISSUE TITLE
Any update?

### ISSUE THREAD

**Issue by takasurazeem** [MicrosoftDocs/visualstudio-docs#462]
Any update on the offline installer?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd139e6-bbd6-4c1a-1b40-5abd63031a9a
* Version Independent ID: bc91c619-c340-40e6-9c55-8c496eb24da5
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/create-offline-installer)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/mac/create-offline-installer.md)

**Comment by gewarren** [comment]
@asb3993 Can you provide an update?

**Comment by AdnanNazir** [comment]
needed !
Please help

**Comment by loflina** [comment]
Please update. This silence is unacceptable.

**Comment by conceptdev** [comment]
We understand this is a feature people care about, but unfortunately we have no additional information at this time.

To ensure your feedback is heard, please use the [Give product feedback](https://developercommunity.visualstudio.com/spaces/41/index.html) button. There you can vote for features and participate in the discussion on when and how they are implemented.

**Comment by fab1o** [comment]
I'm also voting for this feature at uservoice.com
