### ISSUE TITLE
Add documentation for solution filters

### ISSUE THREAD

**Issue by Forgind** [MicrosoftDocs/visualstudio-docs#4620]
See https://github.com/microsoft/msbuild/pull/4899

**Comment by rainersigwald** [comment]
@ghogen this is a new MSBuild feature that will light up in 16.5 (if all goes to plan). @Forgind can write or draft the docs, just wanted to get an item out so we don't forget.

**Comment by ghogen** [comment]
This was done a long time ago.
https://docs.microsoft.com/en-us/visualstudio/msbuild/solution-filters?view=vs-2019
