### ISSUE TITLE
Format the file when saving it not available

### ISSUE THREAD

**Issue by c-lamont** [MicrosoftDocs/visualstudio-docs#4622]
I have downloaded the latest VS Mac and dissapointed to see the option to format on saving the document is not available anymore.

I'm not sure if this is an issue with the document or with the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd65c9e-47f2-04ab-dcc3-c288ce158dd5
* Version Independent ID: c2375bfb-c1a9-7733-dbbe-1a3bdfaf80f7
* Content: [Code formatting - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/editor-behavior?view=vsmac-2019#feedback)
* Content Source: [mac/editor-behavior.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/editor-behavior.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @cobey
* Microsoft Alias: **cobey**

**Comment by WilliamAntonRohm** [comment]
@c-lamont -- Chris, thank you for your feedback.  You may find further information here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@cobey -- Cody, please look into this potential documentation issue.
