### ISSUE TITLE
Add Docker Support Does not exist

### ISSUE THREAD

**Issue by john-dieter** [MicrosoftDocs/visualstudio-docs#4625]
For .net framework console apps - only "add container orchestrator support" shows up after project creation, and NO advanced options show at all during project creation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76adc87-d3e4-d443-b1ae-d49d039d08ae
* Version Independent ID: 4c3938df-6bbe-0ef0-50a8-14b6f192deed
* Content: [Visual Studio Container Tools on Windows - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2019)
* Content Source: [docs/containers/overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@john-dieter There's a note in that topic about support for .NET Framework console projects, but I agree it doesn't say clearly that Add Docker Support is not available.  I modified the note to clarify this. This change will be appearing in a day or so. Thanks!

**Comment by ghogen** [comment]
You can request support by filing an issue at https://github.com/Microsoft/DockerTools/issues

**Comment by WilliamAntonRohm** [comment]
@ghogen -- thank you for updating the documentation.
