### ISSUE TITLE
Updated Please

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/visualstudio-docs#4627]
Can you please provide an update / ETA on this?
https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365#q-how-do-current-users-upgrade-to-e5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [The Microsoft 365 benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365#q-how-do-current-users-upgrade-to-e5)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by WilliamAntonRohm** [comment]
@danmyhre -- Dan, please let me know if this helps answer your question:
- https://developer.microsoft.com/en-us/office/blogs/new-microsoft-365-e5-subscription-with-ems-now-available-for-developers/

**Comment by evanwindom** [comment]
@WilliamAntonRohm - I believe @danmyhre is looking for a status on the efforts to build out a mechanism to enable the upgrade.  Michael's article doesn't include that.  

The latest word from the PM is that our systems today are still pretty rigid around creating developer tenants.  Unfortunately, I don't have any news on the work that would be required to remove those constraints.

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- thank you for that information.

@danmyhre -- it looks like that is the current answer.  I am closing this issue now.  You are welcome to @ mention me for any followup.

**Comment by danmyhre** [comment]
Any update on this yet? @evanwindom

**Comment by evanwindom** [comment]
@danmyhre  - No news yet.
