### ISSUE TITLE
Error installing VS build tools in Docker container

### ISSUE THREAD

**Issue by atwilso** [MicrosoftDocs/visualstudio-docs#4629]
I'm following the instructions on https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019 to try to install the Visual C++ workload in a container.  My Dockerfile works fine on a machine with no proxy but fails with error 5003 on a machine behind a proxy.

I am certain that the proxy settings in Docker Desktop are correct.  A separate installer that makes network connections (Miniconda) works just fine.

I'm attaching the Dockerfile I'm using, the batch file that collects the logs, and the log bundle from the most recent failure.  I've had to rename the Dockerfile and the CMD file to .txt files to upload them here; on the original system they are named Dockerfile and install.cmd.

Here is what I believe is the most relevant snippet from the logs.  This is from temp\dd_bootstrapper_<timestamp>.txt in the log bundle:

  VisualStudio Bootstrapper:1/10/2020 1:11:17 PM: Attempting download 'https://aka.ms/vs/16/release/installer' using engine 'WebClient'
  VisualStudio Bootstrapper:1/10/2020 1:11:38 PM: WebClient error 'ConnectFailure' - proxy setting 'Default' - 'https://aka.ms/vs/16/release/installer'.
  VisualStudio Bootstrapper:1/10/2020 1:11:59 PM: WebClient error 'ConnectFailure' - proxy setting 'DefaultCredentialsOrNoAutoProxy' - 'https://aka.ms/vs/16/release/installer'.
  VisualStudio Bootstrapper:1/10/2020 1:12:20 PM: WebClient error 'ConnectFailure' - proxy setting 'NetworkCredentials' - 'https://aka.ms/vs/16/release/installer'.
  VisualStudio Bootstrapper:1/10/2020 1:12:41 PM: WebClient error 'ConnectFailure' - proxy setting 'DirectAccess' - 'https://aka.ms/vs/16/release/installer'.
  VisualStudio Bootstrapper:1/10/2020 1:12:41 PM: WebClient failed in 'https://aka.ms/vs/16/release/installer' with 'Unable to connect to the remote server' - 'https://aka.ms/vs/16/release/installer'.

That occurs every time a download is attempted.

How do I troubleshoot and fix this?

[vslogs.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/4048212/vslogs.zip)
[Dockerfile.txt](https://github.com/MicrosoftDocs/visualstudio-docs/files/4048217/Dockerfile.txt)
[install-cmd.txt](https://github.com/MicrosoftDocs/visualstudio-docs/files/4048219/install-cmd.txt)

**Comment by atwilso** [comment]
PS.  If I should send this issue to a different repository, just point me in the right direction.

**Comment by WilliamAntonRohm** [comment]
@atwilso -- Andy, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

And you may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by atwilso** [comment]
@WilliamAntonRohm -- please consider changing the "We offer a Live Chat support option" recommendation.  I was told there that (1) Docker containers aren't supported and (2) VS Build Tools are an auxiliary product and that support option is for Visual Studio only.  

This was rather disconcerting.  I know it's boilerplate text, but either the text is wrong or the person on the chat line was wrong.  

The critical piece of information I need is how to get proxy settings to vs_buildtools.exe inside a container.  I was hoping that you or @HeathS would know.  I'll ask on the forums you suggested and report back with whatever I learn.

**Comment by heaths** [comment]
Proxy settings can only be set currently via IE proxy configuration you can set via [netsh](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/cc731131(v=ws.10)?redirectedfrom=MSDN). That should work, though I'm no longer on the Setup team. @mistymadonna may be able to point you at other options.

**Comment by theatricshrink** [comment]
Has someone figured that one out? I have exactly the same problem in a Win2019 Docker Cotainer when installing VS2019. Tried setting the proxy variables in various places (docker build argument, HTTP_PROXY env, netsh...) and it's not picked up correctly.
