### ISSUE TITLE
Document errata

### ISSUE THREAD

**Issue by SCordesHum** [MicrosoftDocs/visualstudio-docs#463]
Topic: https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code

"In the Name box, enter BankTest" should be "BankTests".
"Add a reference to the Bank solution."  "Solution" should be "project".
The "using BankAccountNS" statement came across from the copied sample code, so the user does not need to be instructed to add it again later.
Should the user be instructed to remove TestMethod1, for clarity of the demo?
"UnitTestExplorer" should be "Test Explorer"
Section header "Continue the analysis" (and the following paragraph) do not appear to be formatted at the correct level.
Is there a better way to indicate where a section of example code is supposed to go instead of using in-code comments?  As is, the "//unit test method" comment gets copied into the project, even though it is ultimately redundant with the [TestMethod] attribute.  That clutters the code and makes a bad example to the novice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)

**Comment by gewarren** [comment]
@SCordesHum Thanks for pointing out these errors. Most of the testing topics need a good refresh at this point. It's on my to-do list.

**Comment by gewarren** [comment]
@pvlakshm can you take this one?
