### ISSUE TITLE
Update offline installation of VisualStudio 

### ISSUE THREAD

**Issue by ali-h2010** [MicrosoftDocs/visualstudio-docs#4631]
I downloaded the offline version with the package i need but after sometime, this version will be outdated. 

Is there a way to update the installation files without creating a new installation?

**Comment by Desires01-dev** [comment]
CI CD rewrite code's intell computer software bucket list owners NASA talent flow Jason depuy and us implication documents policy spending time interaction intergaration building Mackintoch safria iOS 2 we speed processor cores firebase lion HP jsn servers cores 15 min faster 15 sec faster intell computer provide all the software inside GitHub Android studio Owners platform hub law firm as Porn hub redtube8 bizzare andhub computer traffic junk publisher account make digram scamitic foosie hoosi chutter frame

**Comment by WilliamAntonRohm** [comment]
@ali-h2010 -- Ali, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

And you may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by ali-h2010** [comment]
@WilliamAntonRohm Hi William. Sorry , i might not have been clear while stating the issue. I just don't want to download the whole offline installation every new update for VisualStudio or the packages that i downloaded with it. 

So i thought there could be an updater to the files before even installing the app by updating the offline instillation files. 

I hope it's clear
