### ISSUE TITLE
Suggest usings for types in reference assemblies

### ISSUE THREAD

**Issue by MV10** [MicrosoftDocs/visualstudio-docs#4634]
In VS2019 16.4.2 the option is actually "Suggest usings for types in _.NET Framework_ assemblies", not "reference" assemblies. (I no longer use .NET Framework, so I came here to to check whether it was truly limited to .NET Framework or if this was just an overlooked bit of verbiage in the UI.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41602f7-2c5e-bf2a-9eab-50740dd10784
* Version Independent ID: c6b1f7c4-eb2d-a62a-7e1b-eb32b8a88947
* Content: [Options, Text Editor, C#, Advanced - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.CSharp.Advanced)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/ide/reference/options-text-editor-csharp-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-advanced.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- please review the above-mentioned PR 6010.

**Comment by TerryGLee** [comment]
@WilliamAntonRohm I approved the PR but we'll need to check this in earlier versions (VS2017) and then create a monikered update instead.

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- thanks Terry for the heads-up.  I'll look into the VS2017 wording.
