### ISSUE TITLE
How to set command (script) in relative path like your example.

### ISSUE THREAD

**Issue by xenogew** [MicrosoftDocs/visualstudio-docs#4638]
I have tried to do it, but it show me with error cannot found the file (script) specific!

I need to specified with full path from `C:\...` I think it's not good practice due to the work we do it together with team, and use Git as source control, when change to other developer environment, it is different from the SPECIFIC path.

You don't provide a tool to select file or output just spamming the unknown reason of which path you mean is 'not found the file specific'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbca10bd-8636-496e-91a3-e77fb1dfcd84
* Version Independent ID: fb4fceda-3a4f-f8fd-3965-1a858e240d31
* Content: [Web application templates for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/python-web-application-project-templates?view=vs-2019)
* Content Source: [docs/python/python-web-application-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/python-web-application-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Thank you for your input. We agree and have added this work to our planning board. We will go ahead and close this issue, but continue to track the work internally.  If you think this issue should remain open, please reopen it with a comment explaining why. Tag me for visibility.
