### ISSUE TITLE
Cleaning up IDXGraphicsAnalysis* pGraphicsAnalysis; at the end of program execution.

### ISSUE THREAD

**Issue by dgnuff** [MicrosoftDocs/visualstudio-docs#464]
Since IDXGraphicsAnalysis inherits from IUknown it might be worthwhile adding a note as to whether pGraphicsAnalysis->Release(); should be called at program termination or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd29d8e-9ab8-965c-a14c-24c0137764f4
* Version Independent ID: 9f6e8219-83db-fd9d-0494-e202a36d7a15
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/walkthrough-capturing-graphics-information-programmatically#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/graphics/walkthrough-capturing-graphics-information-programmatically.md)

**Comment by Mikejo5000** [comment]
Looking into this

**Comment by Mikejo5000** [comment]
Fix in place. Thanks!
