### ISSUE TITLE
Spy++ is not visible under Tools in VS2019 after following these instructions

### ISSUE THREAD

**Issue by asfarley** [MicrosoftDocs/visualstudio-docs#4640]
Using VS2019 community 16.4.3, under "Individual Components", there is no package called "Visual Studio C++ core features". However, there is "C++ core features". I have installed this package. I have also installed the "C++ profiling tools" package. 

After installing these packages, Spy++ is NOT visible under the tools menu. However, the executable spyxx.exe *is* located on my hard drive at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools. 

Am I missing a step? Maybe these instructions need to be updated for VS2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e38caf-7077-963a-acd2-e815846041eb
* Version Independent ID: a24346a4-06e1-4943-c2c5-a4c0000ab980
* Content: [How to: Start Spy++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-start-spy-increment?view=vs-2019)
* Content Source: [docs/debugger/how-to-start-spy-increment.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-start-spy-increment.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@asfarley Thanks! I'll update this.

**Comment by Mikejo5000** [comment]
Checked Spy++ in a couple of versions of VS 2019 16.4, and I can't repro the issue. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
