### ISSUE TITLE
install incomplete

### ISSUE THREAD

**Issue by chenpei2** [MicrosoftDocs/visualstudio-docs#4644]
I gernerated a image exactly as the documentation said but it installed nothing in C:\BuildTools. Instead I found Micosoft Visual Studio within C:\Program Files (x86) ,while no windows 10 or windows 8.1 sdk could be get from Windows Kits. 
I removed " --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `" from the dockerfile and regenerated, it didn't work.
What should I do if I want to use windows sdk?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @jillre
* Microsoft Alias: **jillfra**

**Comment by WilliamAntonRohm** [comment]
@chenpei2 -- It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 @jillre -- please look into this potential documentation issue.

**Comment by chenpei2** [comment]
## 
I could install build tools on my host machine without any problem , using dockerfile below:
```
# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

# Set up environment to collect install errors.

COPY Install.cmd C:\TEMP\

ADD https://aka.ms/vscollect.exe C:\TEMP\collect.exe

# Download the Build Tools bootstrapper.
ADD https://aka.ms/vs/16/release/vs_buildtools.exe C:\TEMP\vs_buildtools.exe

# Install Build Tools excluding workloads and components with known issues.
RUN C:\TEMP\Install.cmd C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --add Microsoft.VisualStudio.Workload.MSBuildTools `
    --add Microsoft.VisualStudio.Component.Windows10SDK.16299 `
    --add Microsoft.VisualStudio.Component.Windows10SDK.17134 `
    --add Microsoft.VisualStudio.Component.Windows10SDK.17763 `
    --add Microsoft.VisualStudio.Workload.VCTools;includeRecommended `
    --installPath C:\BuildTools `
    || IF "%ERRORLEVEL%"=="3010" EXIT 0

ADD VsDevCmdPowerShell.cmd C:\BuildTools\
ENTRYPOINT C:\BuildTools\VsDevCmdPowerShell.cmd
```
install.cmd
```
@rem Copyright (C) Microsoft Corporation. All rights reserved.

@rem Licensed under the MIT license. See LICENSE.txt in the project root for license information.

@if not defined _echo echo off

setlocal enabledelayedexpansion

call %*
if "%ERRORLEVEL%"=="3010" (
    exit /b 0
) else (
    if not "%ERRORLEVEL%"=="0" (
        set ERR=%ERRORLEVEL%
        call C:\TEMP\collect.exe -zip:C:\vslogs.zip
        exit /b !ERR!
    )
)
```
But when I want to install it into a virtual machine created by hyper-v manager, I get error message below:
```
Preparing: C:\Users\ContainerAdministrator\AppData\Local\Temp\30ffeff2859d8fb248\vs_bootstrapper_d15\vs_setup_bootstrapper.json...
The command 'cmd /S /C C:\TEMP\Install.cmd C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache     --add Microsoft.VisualStudio.Workload.MSBuildTools     --add Microsoft.VisualStudio.Component.Windows10SDK.16299     --add Microsoft.VisualStudio.Component.Windows10SDK.17134     --add Microsoft.VisualStudio.Component.Windows10SDK.17763     --add Microsoft.VisualStudio.Workload.VCTools;includeRecommended     --installPath C:\BuildTools     || IF "%ERRORLEVEL%"=="3010" EXIT 0' returned a non-zero code: 4294967295: failed to shutdown container: container 62f6c22ba0112fac9b50a8f8f008981692bbdc337b83d7593fba04f61c31e1e2 encountered an error during WaitTimeout: hcsshim: timeout waiting for notification
```
I have been watching the disk during the installation process, no space change happened.Seems like nothing was written into the disk.
Since I have failed many times installing vs build tools into docker running on VM Workstation  machines, is it impossible to do it on virtual machines?

Btw, even if I used vscollect.exe, no log was collected.

### Information
  - Windows Version: Windows 10 pro 1909
  - Docker Desktop Version: 2.1.0.5 (docker engine 19.03.5)

**Comment by ornellaalt** [comment]
Hi @chenpei2, we've updated the Build Tools documentation [here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019). Please give the new instructions a try. We look forward to your feedback, and I'll be closing out this issue in the meantime.
