### ISSUE TITLE
Http Error 500.19

### ISSUE THREAD

**Issue by chiphum** [MicrosoftDocs/visualstudio-docs#4645]
When following above I get a 500.19 Error.  
Detailed Error Information:

Module
   IIS Web Core 

Notification
   Unknown 

Handler
   Not yet determined 

Error Code
   0x8007000d 

Config Error
    

Config File
   \\?\C:\Users\Public\web\web.config 

Requested URL
   http://localhost:80/ 

Physical Path
    

Logon Method
   Not yet determined 

Logon User
   Not yet determined 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed35685d-e409-d962-c450-7297a1f3c003
* Version Independent ID: 224fab0f-fd26-396f-cdd8-921533d2aeba
* Content: [Configure Python web apps for IIS - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/configure-web-apps-for-iis-windows?view=vs-2019#feedback)
* Content Source: [docs/python/configure-web-apps-for-iis-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/configure-web-apps-for-iis-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@chiphum -- Chip, thank you for your feedback.  You may find information here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@JoshuaPartlow -- Joshua, please look into this potential documentation issue.

**Comment by chiphum** [comment]
Took a lot of effort but I got it to work a last
1.  Must Install HttpPlatform https://www.iis.net/downloads/microsoft/httpplatformhandler
2.  Configuration Editor system.webServer/httpPlatform (Section is not locked)
3.  Make sure app has permissions for log path stdoutLogFile="c:\home\LogFiles\python.log"
4.  Had to setup up app.run(port=PORT)  PORT = int(environ.get('SERVER_PORT', '5555'))
5.  Setup firewall to allow http-incoming requests

**Comment by WilliamAntonRohm** [comment]
@chiphum, thanks for the followup research.

**Comment by chiphum** [comment]
I tried to scale this solution but the server is very slow.  It seems to only serve 3 connections at a time and does not close those connections when done send the content such as jquery source or bootstrap css.  An example is making the call to download jquery or bootstrap from my flask folder. It will only move on to the next item after it times out at 60s.

**Comment by DanielJBrown** [comment]
Flask: Change the WSGI_HANDLER value to <project_name>.app where <project_name> matches the name of your project. You can find the exact identifier by looking at the from <project_name> import app statement in the runserver.py. For example, if the project is named "FlaskAzurePublishExample", the entry would appear as follows:

XML
Copy

<add key="WSGI_HANDLER" value="flask_iis_example.app"/>

shouldn't value be value="FlaskAzurePublishExample.app"?

**Comment by JoshuaPartlow** [comment]
Closing given time open. If this is still an issue, please feel free to reopen.
