### ISSUE TITLE
Please document usage of Directory.Build.targets with PreBuildEvent

### ISSUE THREAD

**Issue by SidShetye** [MicrosoftDocs/visualstudio-docs#4648]
We're using a PreBuildEvent to fire a script `InjectVersionToBuildProps.ps1` that updates the `Directory.Build.targets` (solution root) with a `Version` and `InformationalVersion` value based on the git repo version/state.

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <!-- snipped -->
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="pwsh -ExecutionPolicy ByPass -File  $(SolutionDir)scripts\build\InjectVersionToBuildProps.ps1" />    
  </Target>
</Project>
```

This is in VS2019 and our script successfully updates `Directory.Build.targets` with the latest values. 

The issue is that the build still ends up with the *previous* values from `Directory.Build.targets` - _not_ the just-updated from our script in the `PreBuildEvent`. 

In other words,

#### Directory.Build.targets before PreBuildEvent
```
<Project>
  <PropertyGroup>
    <Version>1.0.0.0</Version>
    <InformationalVersion>PlaceHolder</InformationalVersion>
  </PropertyGroup>
</Project>
```

#### Directory.Build.targets after PreBuildEvent
```
<Project>
  <PropertyGroup>
    <Version>2020.1.07.0815</Version>
    <InformationalVersion>server-enterprise/20200107_081500-1-g1fa18dba</InformationalVersion>
  </PropertyGroup>
</Project>
```

The build still ends up with `Version=1.0.0.0` and `InformationalVersion=PlaceHolder`. How do we use `Directory.Build.targets` so the build correctly reflects the values we just write using `PreBuildEvent`s scripts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#feedback)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by KalleOlaviNiemitalo** [comment]
These solutions may be possible:

- Write the file before running MSBuild at all.
- Write the file in the NuGet restore phase (e.g. with `BeforeTargets="Restore"`), which likewise modifies files that MSBuild will later import.
- Write the properties to a separate text file and make Directory.Build.targets define a target that reads them using the ReadLinesFromFile task, so that you can control when the file is read.
- Use [Nerdbank.GitVersioning](http://www.nuget.org/packages/nerdbank.gitversioning), which already implements something similar.

AFAIK, the documentation does not really say when MSBuild reads each file, so one should not rely on that. But an explicit warning in the documentation could help.

**Comment by ghogen** [comment]
Yes, it seems the action here is to add a note to the doc that says when the files are loaded.

**Comment by SidShetye** [comment]
> AFAIK, the documentation does not really say when MSBuild reads each file, so one should not rely on that. But an explicit warning in the documentation could help.

@KalleOlaviNiemitalo : Perhaps but it’s literally called `PreBuildEvent` which is self-documenting to means “before build”. So if it doesn’t work that way, it’s basically a trap, worthy of a bug report.

**Comment by SidShetye** [comment]
[reported](https://github.com/dotnet/sdk/issues/10941)

**Comment by KalleOlaviNiemitalo** [comment]
> `BeforeTargets="Restore"` doesn't work because of this [issue](https://github.com/dotnet/sdk/issues/7741).

<https://github.com/NuGet/Home/issues/4634> and <https://github.com/NuGet/Home/issues/4781> seem to say that `BeforeTargets="CollectPackageReferences"` would work.

**Comment by NN---** [comment]
I added this but I don't see restoring of dotnet tools

```xml
  <Target Name="LocalToolRestore" BeforeTargets="CollectPackageRefereces">
    <Message Text="Restoring tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>

  <Target Name="LocalToolRestore2" BeforeTargets="_GenerateRestoreProjectSpec">
    <Message Text="Restoring tools" Importance="High" />
    <Exec Command="dotnet tool restore" />
  </Target>
```
