### ISSUE TITLE
container-launch-settings.md does not render correctly

### ISSUE THREAD

**Issue by jnpwly** [MicrosoftDocs/visualstudio-docs#4649]
The page located at https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2019 does not render correctly when displaying the VS2019 version of the page. Additionally, the parameters for the `launchUrl` are not surrounded by chevrons (`<` and `>`), but with curly braces (`{` and `}`).

![image](https://user-images.githubusercontent.com/10701621/72472802-2fdd7780-384a-11ea-8f70-90580ac40633.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0eb0463-50c5-9697-2eaf-a5f5fcb01513
* Version Independent ID: bf27ddf9-e6a3-0717-1d3c-620c054f0d5c
* Content: [Visual Studio Container Tools launch settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2019)
* Content Source: [docs/containers/container-launch-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-launch-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by jnpwly** [comment]
PR submitted to fix this: https://github.com/MicrosoftDocs/visualstudio-docs/pull/4643

**Comment by msebolt** [comment]
@jnpwly  Thank you for your feedback and for taking the time to contribute.

We're reviewing the changes now.

**Comment by msebolt** [comment]
Changes have been merged, thank you for contributing to Microsoft Docs!

Please refer to the [contributor's guide](https://docs.microsoft.com/contribute) for more information.
