### ISSUE TITLE
Suggest a note be added re what library to link in.

### ISSUE THREAD

**Issue by dgnuff** [MicrosoftDocs/visualstudio-docs#465]
For the above code snippets to work, it is necessary to link dxgi.lib into your program to resolve the otherwise undefined call to DXGIGetDebugInterface1().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fd29d8e-9ab8-965c-a14c-24c0137764f4
* Version Independent ID: 9f6e8219-83db-fd9d-0494-e202a36d7a15
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/walkthrough-capturing-graphics-information-programmatically#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/graphics/walkthrough-capturing-graphics-information-programmatically.md)

**Comment by Mikejo5000** [comment]
Adding link to DXGIGetDebugInterface1

**Comment by Bethannfrum** [comment]
Debug

**Comment by Mikejo5000** [comment]
Per instructions from product team, link to interface now published
