### ISSUE TITLE
List<T> triggers this warning

### ISSUE THREAD

**Issue by mtaylorfsmb** [MicrosoftDocs/visualstudio-docs#4650]
I'm unsure whether this is by design or not but deriving from `List&lt;T&gt;` and naming the type `List` generates this warning. If not by design then the rule is wrong and `List&lt;T&gt;` derived types should use suffix `List`. In either case add a mapping to the table to clarify what `List&lt;T&gt;` derived types should be using.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83202117-8bd8-aa22-d55c-42ecc59fc11f
* Version Independent ID: 2374ea4f-0f8d-283e-5803-7c8de04b48f7
* Content: [CA1710: Identifiers should have correct suffix - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1710?view=vs-2019)
* Content Source: [docs/code-quality/ca1710.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1710.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@mtaylorfsmb Thank you for the feedback and apologies for the confusion.

Perhaps [Systems.Collections.Generic](https://docs.microsoft.com/dotnet/api/system.collections.generic?view=netframework-4.8) needs to be included in the list.  Does the warning resolve if the suffix `Collection` is used?  

Assigning this to the author for further review.

**Comment by mtaylorfsmb** [comment]
Yes if I add `-Collection` to the type then the warning goes away.

**Comment by Mikejo5000** [comment]
Hi, please check the syntax for [IList<T>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1?view=netframework-4.8).
It implements System.Collections.Generic.ICollection<T>, which is on the list.
