### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by nicol-go** [MicrosoftDocs/visualstudio-docs#4655]
Visual Studio 2019 is very different from Visual Studio 2017, I cannot use the profile tool in Visual Studio 2019 by the way of this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e998101e-f5d8-517a-7f74-356b973a2b07
* Version Independent ID: 36f07905-43eb-019a-a0f6-a732b9d10da6
* Content: [Run profiling tools with or without the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/running-profiling-tools-with-or-without-the-debugger?view=vs-2019#feedback)
* Content Source: [docs/profiling/running-profiling-tools-with-or-without-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/running-profiling-tools-with-or-without-the-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@nicol-go Thank you for the feedback, assigning this to the author for review.

**Comment by Mikejo5000** [comment]
@nicol-go Are you trying to use the Performance Explorer / Performance Wizard in VS 2019? The Performance Exploer / Wizard is removed in VS 2019. Some features, such as instrumentation are available in VS 2019 in the Performance Profiler.
The best statement I've seen about the changes is here, see the comments by Allen Denver.
https://developercommunity.visualstudio.com/content/problem/441152/missing-profiler-options-under-debug-visual-studio.html
If there is something here not working in the Performance Profiler or Diagnostic Tools, as described on this page, please let us know.
