### ISSUE TITLE
Document SkipNonexistentProjects="Build" parameter of MSBuild task

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#4659]
The documentation of the MSBuild task claims that SkipNonexistentProjects is a Boolean parameter. In the [source code](https://github.com/microsoft/msbuild/blob/4400fa4e17ffea730e7a5bfeb83dcc73ba420d1a/src/Tasks/MSBuild.cs#L134-L175) however, it is a String parameter that recognizes the values "True", "False", and "Build". Please document the meaning of Build.

MSBuild emits &lt;SkipNonexistentProjects&gt;Build&lt;/SkipNonexistentProjects&gt; as metadata of ProjectReference items in *.sln.metaproj when MSBUILDEMITSOLUTION=1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24ae888a-0777-7e09-cd0c-c864df8376db
* Version Independent ID: 29dd0025-ff74-ec07-ad71-4a75a276d8d8
* Content: [MSBuild Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@rainersigwald

**Comment by rainersigwald** [comment]
I'm not sure this option is meaningful for users outside of MSBuild itself; it means "build this project even though it doesn't exist on disk, trusting that something else has already created an object that will match it in the engine", but it's not easy to meet that guarantee outside of MSBuild (which generates .metaproj projects in memory that don't exist on disk).

**Comment by ghogen** [comment]
Given that, we'll close this PR.
