### ISSUE TITLE
TEST

### ISSUE THREAD

**Issue by BensonWang743** [MicrosoftDocs/visualstudio-docs#466]
TEST

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd4d05c-4aa3-0376-f3a1-b0ea0793f482
* Version Independent ID: 7f1ff943-61b0-60e1-9ca3-d4a84bfdb068
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/install/install-visual-studio.md)

**Comment by raysefo** [comment]
How to install VS on a drive other than C? Is there a way to install all of the features on drive D?

**Comment by Thraka** [comment]
@gewarren if you lock this, it will disappear from the article closed issues.
