### ISSUE TITLE
MSBuild warning/error behavior properties

### ISSUE THREAD

**Issue by rainersigwald** [MicrosoftDocs/visualstudio-docs#4660]
https://github.com/microsoft/msbuild/pull/1928 introduced a few properties that can control MSBuild's error behavior:

- [ ] `MSBuildTreatWarningsAsErrors`
- [ ] `MSBuildWarningsAsErrors`
- [ ] `MSBuildWarningsAsMessages`

(I can write this up, but am filing this so we don't forget entirely.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a5a0e-ae03-1237-6ebe-743066f27fa9
* Version Independent ID: a342bfa4-4b0c-0a47-3695-858044f5aa5f
* Content: [MSBuild Reserved and Well-known Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-reserved-and-well-known-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-reserved-and-well-known-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@rainersigwald -- Rainer, thank you for filing this issue.  I'm assigning to you for bookkeeping, and you are welcome to re-assign.

**Comment by ghogen** [comment]
@rainersigwald Can you provide an ETA for this?

**Comment by rainersigwald** [comment]
1.	NoWarn was for compiler messages but as of 16.9 now applies to all warnings (dotnet/msbuild#5774)
2.	The $(WarningLevel) property is passed to compilers and does not affect MSBuild warnings
a.	MSBuild warnings do not have “levels” today
3.	You can specify properties to elevate/suppress warnings (initial implementation: dotnet/msbuild#1928):
a.	MSBuildTreatWarningsAsErrors makes all warnings into errors unless they’re suppressed
b.	MSBuildWarningsAsMessages suppresses specific warning codes
c.	MSBuildWarningsAsErrors elevates specific warning codes
4.	You can also pass these on the command line
a.	Msbuild.exe -WarnAsError
b.	MSBuild.exe -warnAsMessage:ABC1234;DEF5678
c.	MSBuild.exe -warnaserror:ABC1234;DEF5678
5.	Some MSBxxxx error cannot be suppressed by properties, because MSBuild emits the warnings before we’ve fully loaded the project so we can’t see the properties. Tracked by dotnet/msbuild#4038 but no clear solution so worth documenting as a caveat.
