### ISSUE TITLE
VS2019 Build process does not recognize changes to the Apache Ant path settings

### ISSUE THREAD

**Issue by wvc25** [MicrosoftDocs/visualstudio-docs#4664]
Hi there,

Still trying to figure out why I can't successfully deploy the default OpenGLES sample code from VS2019. After a couple rounds of experimentation, I was able to at least successfully build the OpenGLES sample code (I needed to run build & clean multiple times, my first few tries always fail). However, I noticed that changes to the Tools &gt; Options &gt; Cross Platform &gt; C++ &gt; Android &gt; Apache Ant path settings is not recognized by the Build & Clean processes even after multiple restarts of VS2019, and even after declaring the corresponding Windows (user and system) environment variables (yes, I also tried restarting my computer after setting these... also, the path C:\apache-ant-1.10.7 does exist in my computer). Please see attached screenshot. Thus, based on your documentation, setting the path in the Options window doesn't seem to take effect.

![VS2019_Tools_Options_paths](https://user-images.githubusercontent.com/57723998/72639706-33e5c400-3934-11ea-8eb6-bff7f51dc4e4.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab51e2f8-b5b5-007a-a9b3-23a85b2f2d88
* Version Independent ID: 9cd86e2f-b4d8-00d9-1d02-294bb2692a1d
* Content: [Install cross-platform mobile development with C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-visual-cpp-for-cross-platform-mobile-development?view=vs-2019#feedback)
* Content Source: [docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/install-visual-cpp-for-cross-platform-mobile-development.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-mobile**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wvc25 
@michelleangela 
This might actually be due to a bug in three out of four Android.Tools.props files. It appears to unconditionally override the Ant location set in the Options dialog if the directory $(VSInstallRoot)\Apps\apache-ant-1.9.3 exists. In an elevated command prompt, rename this directory, and see what happens.

**Comment by michelleangela** [comment]
@wvc25 
The latest version of Android.Tools.props does default to look for the Ant that is shipped with Visual Studio under directory $(VSInstallRoot)\Apps\apache-ant-1.9.3. However it should honor a user specified path. Could you file this bug on the [Visual Studio developer community](https://developercommunity.visualstudio.com/content/problem/post.html)?

 
Note that the Android C++ mobile development workload currently only support up to SDK 25 though, so trying to use a later version of Ant may not work as expected.

**Comment by wvc25** [comment]
@michelleangela 
Thanks for your response.  I will file a bug report as requested.  The reason why I'm trying to use a later version of apache-ant is because although the sample code can build successfully I can't get it to deploy.  Having searched for answers from the internet in vain, I'm basically experimenting to find out what is causing this error.  Please see the screenshot below.

![MSVS2019_Android_Deployment_Error1](https://user-images.githubusercontent.com/57723998/72914506-c7d8d680-3d0c-11ea-877d-f6b60eb837dd.png)

**Comment by wvc25** [comment]
@corob-msft 
Thanks for the tip.  I renamed the folder as you advised and VS2019 did finally recognize the new entry for the ANT_HOME path.  However, I'm still getting the same result.  The sample code builds successfully but the deployment fails.  Please see the screenshot below.

![MSVS2019_Android_Deployment_Error2](https://user-images.githubusercontent.com/57723998/72915110-c78d0b00-3d0d-11ea-848b-f63183fe05ba.png)

**Comment by corob-msft** [comment]
@wvc25 

Unfortunately, your question is really a product support one, rather than representing a documentation defect. For those kinds of questions, we strongly recommend asking on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). Without an obvious documentation problem to fix, I have to close the issue.

My support advice here is generic: Verify each step of the build process, see whether and where the build products are generated, and correct any issues you find. Good luck!
