### ISSUE TITLE
Not all files and directories are added to template

### ISSUE THREAD

**Issue by AcuarioCat** [MicrosoftDocs/visualstudio-docs#4668]
I created a template from a project that had several sub directories that contained files. The majority of the directories did not get added to the template. Also some files were moved from the root of the project (with extensions .ino and .txt ) to a different folder (PHP).

**Comment by WilliamAntonRohm** [comment]
@AcuarioCat -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
