### ISSUE TITLE
Language for C++ is CPP

### ISSUE THREAD

**Issue by mseld2** [MicrosoftDocs/visualstudio-docs#4670]
The article only tells Language attribute value for VB and C# (CSharp)...at least from what I saw. It would be nice to indicate that C++ is CPP.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77c7c36c-84d9-9237-3d78-689e76d080f9
* Version Independent ID: 6584735a-e8db-429d-5427-687fc709e6f8
* Content: [Walkthrough: Create a code snippet - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2019#feedback)
* Content Source: [docs/ide/walkthrough-creating-a-code-snippet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-creating-a-code-snippet.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@mseld2  Thank you for the feedback.

C++ code snippets have some additional properties, please refer to [Visual C++ code snippets](https://docs.microsoft.com/visualstudio/ide/visual-cpp-code-snippets).

Assigning this to the author for further review.

**Comment by madskristensen** [comment]
Map of content types:

Visual Basic: `Basic`
C++: `C/C++`
C#: `CSharp`
CSS: `CSS`
HTML: `HTML`
JavaScript: `JavaScript`
SQL: `SQL_SSDT`
XML: `XML`

**Comment by profexorgeek** [comment]
Thanks for the tip, @mseld2. We updated this doc and it should be live shortly.
