### ISSUE TITLE
The Tip to locate templates

### ISSUE THREAD

**Issue by Dyckie** [MicrosoftDocs/visualstudio-docs#4673]
The template locations suggested by the tip are empty directories.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f8f1c1-ffab-4a28-28e0-01ab59f8f827
* Version Independent ID: fb87ecb9-aaf2-a693-a30b-f5a4aea01ba8
* Content: [Locate templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-locate-and-organize-project-and-item-templates?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-locate-and-organize-project-and-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-locate-and-organize-project-and-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@Dyckie Thank you for the feedback.

User project and item templates require you to [create your own custom templates](https://docs.microsoft.com/visualstudio/ide/creating-project-and-item-templates).

For pre-installed templates, please refer to the `Program Files (x86)` directory:

![Capture](https://user-images.githubusercontent.com/6675884/72827394-8f16ff80-3c2f-11ea-823a-7fda8497afdc.PNG)

@TerryGLee

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
