### ISSUE TITLE
Default test architecture

### ISSUE THREAD

**Issue by nodermatt** [MicrosoftDocs/visualstudio-docs#4675]
I had to specify the default architecture for the unit tests in the tests settings page, see: https://docs.microsoft.com/en-us/visualstudio/test/run-a-unit-test-as-a-64-bit-process?view=vs-2019

Copied verbatim from the link above: "From the Visual Studio menu, choose Test, then choose Settings, and then choose Processor Architecture. Choose x64 to run the tests as a 64-bit process."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3681419-a041-da72-a134-37401922a536
* Version Independent ID: 57b6194d-cb07-0e89-8f38-544bf4ce9816
* Content: [Run and debug unit tests with Test Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019#feedback)
* Content Source: [docs/test/run-unit-tests-with-test-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/run-unit-tests-with-test-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@nodermatt  Thank you for the feecback.

What version of Visual Studio are you using?  Test settings have recently changed in version 2019.

Assigning this to the author for further review.

**Comment by nodermatt** [comment]
Hi @msebolt I'm using VS 2017. I will switch to 2019 once I am done with one project that is heavily bound to VS2017 for historic reasons.

**Comment by Mikejo5000** [comment]
@nodermatt To make this work, did you first have to recompile as Any CPU or x64 before setting the processor architecture? I'm wondering how to repro this issue.

**Comment by Mikejo5000** [comment]
To identify a doc issue here, we need more info for the repro. Refreshed the doc on the 64-bit process. Closing.
