### ISSUE TITLE
How can we restrict the "Product Keys" Tab to organisation Administrators only?

### ISSUE THREAD

**Issue by write2mee** [MicrosoftDocs/visualstudio-docs#4676]
Previosuly in MSDN there was a role need to be assigned to view the "Produckt Keys".  but this option is not available now.

currently if any user is having visual studio subscription assigned  then product keys are visible to the user.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a831c5d-68a7-79a9-7b67-6c6de00549ee
* Version Independent ID: b2ae1288-6bb3-ddb3-6bbb-114146af2158
* Content: [Finding and claiming product keys in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/find-keys)
* Content Source: [subscriptions/find-keys.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/find-keys.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@write2mee -- Thanks for reaching out.  You cannot prevent access to the product keys tab in the subscription, but an administrator can disable access to the software downloads.  In the administration portal, https://manage.visualstudio.com, click on the "..." next to a subscriber's name, and choose "Edit".  In the "Edit Subscriber Details" pane, click on the drop-down for "Download Settings" and toggle the setting from "Allow" to "Do not allow".  Then click "Save".

**Comment by evanwindom** [comment]
#please-close
