### ISSUE TITLE
Web platform installer has too many choices

### ISSUE THREAD

**Issue by patja** [MicrosoftDocs/visualstudio-docs#4677]
Telling people to "just install Web Deploy through Web Platform Installer" is not specific enough.  There are at least seven choices for this within the Web Platform Installer.  With and without SQL support, different versions, and some are "for hosting servers", the meaning of which is unclear.  There is no guidance on which to pick.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fd32d9-6fbe-11f8-3239-cf7f6166e286
* Version Independent ID: 910b1cdb-c055-5301-d00b-8e65672c0df4
* Content: [Publish to a website - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-a-web-site?view=vs-2019#feedback)
* Content Source: [docs/deployment/quickstart-deploy-to-a-web-site.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/quickstart-deploy-to-a-web-site.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@patja Thank you for the feedback.

Assigning this to the author for further review.

**Comment by patja** [comment]
Just want to add some context.  I had a difficult time over the span of about 4 hours spent trying to get Web Deploy to work from VS 2019 to a new Windows Server 2019 Standard server.  The prerequisites and varied means of finding the right thing to install were a challenge.  Use Web PI or install a standalone.  Try to find a standalone installer, and find that my VS workstation already has a later version, 4.0, installed...a version which is unavailable in Web PI, and cannot be found to download or install separate from VS.  I was also getting to a state where trace logs on the server showed the process beginning, but it was returning a 404 response which VS reported as an error with the site being unreachable (misleading!)

I noticed that I had no "deploy" option in IIS Manager under my sites, so finally focused on that, uninstalling and reinstalling Web Deploy through several different options until one made the deploy option appear.  From then on it worked.  

It should be easier to find the right install directions and get this working with the latest 2019 server and VS edition.

**Comment by Mikejo5000** [comment]
@patja Thanks for the detailed information. I will take a look at this. The "Deploy" option requires Web Deploy for Hosting Servers, and you need to uninstall the other versions first, I recall. Steps are detailed in the "Next Steps" topic, [here](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-import-publish-settings-iis?view=vs-2019). I will add another link to this topic where Web Deploy is discussed. A doc update might be needed for Web Deploy 4.0. It was 3.6 last time I tested these scenarios.

**Comment by Mikejo5000** [comment]
@patja Looking at this. Did you use Web Deploy 3.6 or 4.0 on the server to resolve issue? I assume you left 4.0 on the VS machine, and did not change that?

**Comment by Mikejo5000** [comment]
Added link, along with other updates for clarity.
