### ISSUE TITLE
WebAPI projects don't use the item template locations

### ISSUE THREAD

**Issue by Allann** [MicrosoftDocs/visualstudio-docs#4678]
Throughout this documentation and many related "create template" pages they make reference to a %User% location.  However, when creating a new file (via Add New Item dialog or keyboard shortcuts) the template does not appear.  

It isn't an issue of the template not being installed because if I change the currently referenced project to a class library in the same solution, I can then see the template. Switching focus back to the WebApi (or MVC Website) the template disappears again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e44d5ce-a797-8367-d4d0-0c3a29f0b18c
* Version Independent ID: d3203ea3-2a1b-f418-62a9-0024c5e03685
* Content: [Create item templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-item-templates?view=vs-2019&redirectedfrom=MSDN#feedback)
* Content Source: [docs/ide/how-to-create-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@Allann  Thank you for the feedback.

This issue seems like a bug specific to the **WebApi** projects and needs to be directed to the product team.

Please refer to [these instructions](https://developercommunity.visualstudio.com/content/problem/post.html?space=8), or let us know and we will create the ticket the ticket for you.

@TerryGLee

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
