### ISSUE TITLE
Missing some info

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/visualstudio-docs#468]
Hi @gewarren, I found the topic I was looking for but I've noticed it's missing a few things for me to be able to link to it.

For example:
- it doesn't show how to suppress compiler warnings for specific NuGet packages referenced by the project via Package Properties or edit the project file
- On a new VB .NET Core project, the NoWarn attribute cannot be found by default. I think you have to add that section manually. 

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13cf461-1a8c-adde-dbd5-39d5c97d9fd3
* Version Independent ID: 38eb2413-af33-2e71-6f42-d871fa00ccf1
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-suppress-compiler-warnings)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/ide/how-to-suppress-compiler-warnings.md)

**Comment by gewarren** [comment]
@mairaw thanks, i'll try to fix it this week.

**Comment by mairaw** [comment]
Thanks @gewarren. Some of this can be found on this blog post: https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/ (see section Reusing an existing .NET Framework library). So you can either suppress the warning globally on your project (as already covered in the topic) or per package.

**Comment by seraptoufektsi** [comment]
Ananızın amına koyayım Serap seninde amına koyayım

iOS için Outlook<https://aka.ms/o0ukef> uygulamasını edinin
________________________________
