### ISSUE TITLE
Two links to the same page (Overview of source code analyzers)

### ISSUE THREAD

**Issue by arphox** [MicrosoftDocs/visualstudio-docs#4685]
I think two links for the same page (Overview of source code analyzers) is unnecessary, especially for a short page writing like this.
I like collecting all links mentioned in an article to gain the most knowledge, but after scanning this page I ended up with two identical links.
This is not a huge problem but I think it would be enough to mention that page once.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963d8d4a-0021-e10a-3a72-358eadced263
* Version Independent ID: 688674ea-4fc0-8d1e-9895-b5f096e80ff1
* Content: [Code analysis for managed code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-overview?view=vs-2019)
* Content Source: [docs/code-quality/code-analysis-for-managed-code-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/code-analysis-for-managed-code-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review the above-mentioned PR.
