### ISSUE TITLE
/usr/local/share/dotnet/sdk/NuGetFallbackFolder folder cannot be added

### ISSUE THREAD

**Issue by mennolaan** [MicrosoftDocs/visualstudio-docs#4687]
Im trying to add /usr/local/share/dotnet/sdk/NuGetFallbackFolder folder to docker dekstop community v 2.2.0.0 with visual studio for mac community 2019 v 8.4.2, but docker doesnt allow me to add this folder. So i cannot start running the docker project because you will get the 
  Cannot start service dockertestsolution: Mounts denied:
error

Im on MacOs catalina 10.15.2

**Comment by WilliamAntonRohm** [comment]
@mennolaan -- Menno, thanks for your feedback.  To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.  

Meanwhile, here are a few options that may help:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
