### ISSUE TITLE
/usr/local/share/dotnet/sdk/NuGetFallbackFolder

### ISSUE THREAD

**Issue by mennolaan** [MicrosoftDocs/visualstudio-docs#4688]
I cannot add this folder with docker 2.2.0.0 community version on catalina 10.15.2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e20f91-d94c-419c-3a64-7616af5e7429
* Version Independent ID: 0f4f0b1a-2506-ec3d-6bda-ccce7565cb64
* Content: [Get started with Docker - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/docker-quickstart?view=vsmac-2019#feedback)
* Content Source: [mac/docker-quickstart.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/docker-quickstart.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by mennolaan** [comment]
For anybody running in to this issue use Command + Shirt +G after you click the add button in Docker and type /usr, now you can acces this folder

**Comment by WilliamAntonRohm** [comment]
@mennolaan -- Menno, thank you for your feedback and your tip.

@heiligerdankgesang -- Dominic, please look into this potential documentation issue.

**Comment by psatyaa** [comment]
NuGetFallbackFolder Folder is not at location. /usr/local/share/dotnet/sdk/. I can see .Net core Versions Folders{3.1 or 3.0} in my case. I am using Catalina and Docker Desktop 2.2.0.3.

**Comment by blackalbum** [comment]
In addition to mennolaan's solution, you can also edit ~/Library/Group Countainers/group.com.docker/settings.json and add the path under "filesharingDirectories" and restart docker

**Comment by p-stannis** [comment]
As soon as you click the plus button on docker file sharing, navigate to the root folder and you can press Command + shift + . (dot) and then navigate to the desired /usr folder

**Comment by heiligerdankgesang** [comment]
This doesn't seem to manifest in the latest version of Docker. Please reach out if you're still experiencing this issue.

#please-close
