### ISSUE TITLE
The mistype in menu color scheme

### ISSUE THREAD

**Issue by SENya1990** [MicrosoftDocs/visualstudio-docs#4689]
There is a mistype in the menu section:
https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/shared-colors-for-visual-studio?view=vs-2019#BKMK_CommandMenus

In the "Menu items: hover state" section the "Background" and "Foreground (Text)" resource names are the same which is probably incorrect - the text will have the same color as the background. The correct value for the "Foreground (Text)" should probably be "CommandBarMenuItemMouseOverText".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcce5094-5214-8d84-ba80-15ba4a5d82fc
* Version Independent ID: 44443f75-0fba-cd33-1287-b4dcfbe69a04
* Content: [Shared Colors for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/shared-colors-for-visual-studio?view=vs-2019#BKMK_CommandMenus)
* Content Source: [docs/extensibility/ux-guidelines/shared-colors-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/shared-colors-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@madskristensen -- please review the above-mentioned PR.
