### ISSUE TITLE
Support for value types?

### ISSUE THREAD

**Issue by Caleb-D** [MicrosoftDocs/visualstudio-docs#4690]
For example, I want to customize the visualizer for "double*"
Is this possible?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Caleb-D -- Thanks for your question.  You may find answers here:​  

 -[https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@Mikejo5000 -- please look into this potential documentation issue.

**Comment by Mikejo5000** [comment]
@Caleb-D I understand this feature works only with your own created types. So, perhaps it would work if you created a wrapper for double*. Have you tried doing that? Thanks.

**Comment by Caleb-D** [comment]
I think these visualizers work for any class, whether I created it or someone else.  In other words, I could override the visualizer for std::vector if I wanted.

However, it is not clear from the documentation whether it is possible to override for value types like int, float, double, etc.  My specific use-case is the pointer value type (double*).

Could you ask the developers if it's possible to have a visualizer for a value type?  This would be handy because I have some double arrays that it would be nice to visualize the first 100 elements or so (even if it indexes off the end of the array in some cases).

**Comment by Mikejo5000** [comment]
Sure, I'll ask about it.

**Comment by Mikejo5000** [comment]
Here's what we have on this:
It's not possible to have visualizers for primitive types (i.e. int, bool) or pointers to those. You can use array format specifier for your use case e.g. if you have "double* mydoublearray", you can use the expression "mydoublearray, [100]" in the watch window to see the first 100 elements.

**Comment by Caleb-D** [comment]
Hi Mike,

Thanks for checking on this.  I am aware of the other way to visualize it, but it takes several steps to do instead of just mousing over.  Maybe they will enhance it one day.

Regards,
Caleb

**Comment by Mikejo5000** [comment]
You might want to use the “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), so others can view and upvote the feature.

**Comment by Mikejo5000** [comment]
Adding a short section at the end describing limitations to help increase clarity around this.
