### ISSUE TITLE
How to verify that your MSBuild properties are correct?

### ISSUE THREAD

**Issue by etheaven** [MicrosoftDocs/visualstudio-docs#4693]
In which file should I look for XamlDebuggingInformation in WPF?

**Comment by msebolt** [comment]
@etheaven Thank you for the question.

Please refer to [Inspect XAML properites while debugging](https://docs.microsoft.com/visualstudio/xaml-tools/inspect-xaml-properties-while-debugging) if there are additional questions post them below.

Please note our support options are limited to documentation examples only.  For product-related issues, please start a thread [here](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by msebolt** [comment]
Closing this issue now.  Please comment below if there are any questions.
