### ISSUE TITLE
Document reserved properties MSBuildAssemblyVersion and MSBuildInteractive

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#4696]
These properties are defined as reserved in the MSBuild source code &lt;https://github.com/microsoft/msbuild/blob/v16.0.461.62831/src/Build/Resources/Constants.cs&gt; but not listed under "MSBuild reserved and well-known properties":
- MSBuildAssemblyVersion: This apparently existed in Visual Studio 2015 already, and Microsoft.Common.tasks and a few other files check this property, so it should be documented.
- MSBuildInteractive: This was added in &lt;https://github.com/microsoft/msbuild/pull/3697&gt;, and the corresponding /interactive switch is also not documented in &lt;https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019&gt; yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a5a0e-ae03-1237-6ebe-743066f27fa9
* Version Independent ID: a342bfa4-4b0c-0a47-3695-858044f5aa5f
* Content: [MSBuild Reserved and Well-known Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-reserved-and-well-known-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-reserved-and-well-known-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
MSBuildAssembly version is superceded by MSBuildVersion
We will add docs for MSBuildInteractive
