### ISSUE TITLE
Run android emulator as admin?

### ISSUE THREAD

**Issue by snow-jallen** [MicrosoftDocs/visualstudio-docs#4697]
I'm unable to launch the android emulator without elevating to admin rights.  Is that something wrong with my machine or should that be added to the list of "you have to be an admin to do these things in visual studio"?

**Comment by WilliamAntonRohm** [comment]
@snow-jallen -- J Allen, thanks for your feedback; we appreciate it. To make sure we have all the information needed to assess your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by snow-jallen** [comment]
Sorry, I clicked on a button from your docs page that sent me here, I didn't know it would lose all context of my referring page.

I'm referring to Tools -> Android -> {anything, Android Device Manager, Android SDK Manager} require admin rights to run them.  But I can run advmanager.bat and emulator.exe from the command line without being an admin, so you don't _really_ have to be an admin to edit/create/run emulators ...but visual studio requires admin.  For most developers that's probably not a problem, but I teach at a college where students don't have admin rights on the lab computers.  I've had to show them how to bypass visual studio's tooling and create their emulators from the command line.  It'd be nice if I didn't have to do that. :)

**Comment by WilliamAntonRohm** [comment]
@snow-jallen -- thank you for clarifying.  Is there a specific docs.microsoft.com topic we could update?

You're welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by blubamamogus2233** [comment]
your mom
