### ISSUE TITLE
Virtual clicks do not open documentation drop-down menus (accessibility issue)

### ISSUE THREAD

**Issue by zmcgohan** [MicrosoftDocs/visualstudio-docs#4699]
I navigate the web solely by voice. The extension I used to click things, Click by Voice, uses virtual clicks and keypresses to interact with the browser. When trying to expand drop-down menus in the navigation menu, I can see that the extension tries to click and open each menu, but nothing happens. I expect this has something to do with how click events are handled by the parent UI elements. Either way, documentation is extremely hard to navigate for me because of this issue. I would greatly appreciate a fix.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b960c4e0-ac54-9e65-6397-44d7a5750764
* Version Independent ID: 224d2c57-b542-8030-6b77-ce8a7889b466
* Content: [Class view, call hierarchy, object browser, code definition window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/viewing-the-structure-of-code?view=vs-2019#feedback)
* Content Source: [docs/ide/viewing-the-structure-of-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/viewing-the-structure-of-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@zmcgohan We apologize for the issues you're having with the documentation.

Please move this issue to the [Microsoft Docs repo](https://github.com/MicrosoftDocs/feedback/issues) for assistance with any UI-related issues, or let us know and we will create the issue for you.

**Comment by msebolt** [comment]
Closing this issue now.
