### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by mercadder** [MicrosoftDocs/visualstudio-docs#470]
latest version (1.19.2) is different  :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 584ac5ab-9547-f2d8-6186-783520b9e1ef
* Version Independent ID: 1f76cf76-b4b8-4cbb-c4ed-1c6a6f2130bd
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/editor-themes)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/mac/editor-themes.md)

**Comment by asb3993** [comment]
Hi @mercadder, I'm using the latest stable version of Visual Studio Mac (7.3.3) and it matches the information in the guide.

Are you using Visual Studio Code? If so, you're looking at the wrong guides. For themes in Visual Studio Code, visit this guide: https://code.visualstudio.com/docs/getstarted/themes

**Comment by mercadder** [comment]
perhaps you want to name Visual Studio, Visual Studio IDE.

you are welcome :)
