### ISSUE TITLE
How Can We Determine the Current Total Sizes of All Four Layouts Available?

### ISSUE THREAD

**Issue by VikingByNature** [MicrosoftDocs/visualstudio-docs#4703]
Would it be possible to include a feature on this web page that tells us the total size of each layout--for the Community, Professional, Enterprise and Build Tools Editions--that is dynamically updated on a regular basis?  Users should also be able to select whether it is for _all languages_ of that version or a _specific language_ if selecting a specific language helps to reduce the size of the layout overall.

Therefore, there should be two options for the user: **Select Version** and **Select Language** in order to display the total layout size.  I would rather know the size before downloading a layout in order to avoid purchasing a USB drive that is far larger than needed to store the layout.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by msebolt** [comment]
@VikingByNature Thank you for the feedback.

For suggestions like this we recommend you to solicit feedback from our product team.

Please move this issue [here](https://developercommunity.visualstudio.com/content/idea/post.html?space=8) or let us know and we can start a ticket for you.

**Comment by msebolt** [comment]
Closing this issue now.
