### ISSUE TITLE
How to use .net standard 2.1 in VSIX project

### ISSUE THREAD

**Issue by KannanKrish** [MicrosoftDocs/visualstudio-docs#4704]
I want to use .net standard 2.1 in VSIX project. How to do it. My VSIX project is in .net4.8. 
or how to migrate VSIX project into .net standard.

**Comment by msebolt** [comment]
@KannanKrish Thank you for the question.

Please refer to [Target frameworks](https://docs.microsoft.com/dotnet/standard/frameworks) and comment below if you have any further questions.

@mairaw

**Comment by msebolt** [comment]
Closing this issue now.
