### ISSUE TITLE
Make *.vs.json files visible

### ISSUE THREAD

**Issue by ZwergNaseXXL** [MicrosoftDocs/visualstudio-docs#4705]
"However, if you want to be able to check them into source control, drag the files into the root of your codebase, where they are visible."
It is unclear whether to do this in the file system or in the solution explorer. Please clarify!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f6ef2c-e616-bf4c-6de4-1448814e4f73
* Version Independent ID: b223e86b-b0d8-3a78-3fe5-0938e6641042
* Content: [Customize build debug tasks using tasks.vs.json launch.vs.json - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/customize-build-and-debug-tasks-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/customize-build-and-debug-tasks-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@ZwergNaseXXL Thank you for the feedback.

Assigning this to the author for further review.

**Comment by TerryGLee** [comment]
@ZwergNaseXXL Thanks for taking the time to write up this issue, and for our lengthy delay in answering it. After testing, I've discovered that you have to use your file system (for example, File Explorer) in Windows) to drag hidden files to the root of your codebase before they can be seen in Solution Explorer and then by source control. We've updated the article accordingly, and we thank you as well for helping to improve the documentation!
