### ISSUE TITLE
Move this page under refactor code

### ISSUE THREAD

**Issue by mikadumont** [MicrosoftDocs/visualstudio-docs#4709]
Can this be moved so its under the following path -&gt; (Path: Docs &gt; Visual Studio &gt; Windows &gt; IDE &gt; Develop &gt; Editor &gt; Code generation and refactoring &gt; Refactor code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f0a35e-c1f4-469e-4f1b-a125c7fb8a27
* Version Independent ID: 4e7f4a27-344d-e40a-f438-571aba2c0432
* Content: [Static local function refactorings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/static-local-function-refactor-options?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/static-local-function-refactor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/static-local-function-refactor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @GovernessS
* Microsoft Alias: **midumont**

**Comment by msebolt** [comment]
@mikadumont Thank you for contacting Microsoft.

@GovernessS @TerryGLee This article's alias is not assignable, please review and/or assign at your earliest convenience.

**Comment by TerryGLee** [comment]
@mikadumont It looks like you've fixed this with https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6090. I'll close this now, but happy to re-open it if need be.
