### ISSUE TITLE
Receiving this warning for valid usage of std::make_unique<T>

### ISSUE THREAD

**Issue by caspringer** [MicrosoftDocs/visualstudio-docs#4711]
The following code produces this warning but, in my opinion, it should not.  If you disagree, please explain why.  Thanks!

`auto instance{ std::make_unique<MyClass>(5) };`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20ea4c31-53fc-5230-e5ce-366f336ec461
* Version Independent ID: d4af8002-3407-4377-e677-5a1a353f9896
* Content: [C26414 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/c26414?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C26414)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/code-quality/C26414.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/C26414.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by corob-msft** [comment]
@caspringer 

This case comes under the final bullet point in the Remarks section. Unless you're doing something that needs the protection of `unique_ptr`, declaring  it as `MyClass instance{5};` avoids some needless overhead. Remember, the warning is just a reminder about a general rule. If you have a good reason for your specific declaration, be confident enough to ignore it.
