### ISSUE TITLE
Remote Debugger for Nunit tests

### ISSUE THREAD

**Issue by mlisowski** [MicrosoftDocs/visualstudio-docs#4715]
Is it possible to configure solution to run&debug unit tests using remote debugger?

Configuring solution and remote debugger with steps from "Remote Debugging a C# or Visual Basic project in Visual Studio" don't work for me. Maybe the point is that I should not debug whole project but only unit tests. The problem is that there aren't many options for "debug" mode in test explorer.

**Comment by msebolt** [comment]
@mlisowski Thank you for the question.

This feature is currently unavailable.

For further support, we recommend soliciting feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by mlisowski** [comment]
Thanks for clarifying.

**Comment by msebolt** [comment]
Unfortunately, it looks like your only options presently would be to [debug the unit tests locally](https://docs.microsoft.com/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019#debug-and-analyze-unit-tests), or create a hybrid approach, such as invoking the [debug environment](https://docs.microsoft.com/visualstudio/ide/reference/debugexe-devenv-exe) using [PowerShell](https://docs.microsoft.com/powershell/module/microsoft.powershell.core/invoke-command).

Out-of-box support requests should be sent to the product team, or let us know and we will create one for you.

**Comment by msebolt** [comment]
Closing the issue now.
