### ISSUE TITLE
AutoUnify Parameter listed twice

### ISSUE THREAD

**Issue by nickalbrecht** [MicrosoftDocs/visualstudio-docs#4718]
Looks like the AutoUnify parameter on this page is listed twice, they both have slightly different wording about the same functionality.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af885617-7979-5fb2-3fc2-d028695e4b8a
* Version Independent ID: a4615f96-f625-4b78-8068-7ae9b343d911
* Content: [ResolveAssemblyReference Task - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/msbuild/resolveassemblyreference-task?view=vs-2019&redirectedfrom=MSDN)
* Content Source: [docs/msbuild/resolveassemblyreference-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/resolveassemblyreference-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
This is fixed now. Thanks for the feedback!
