### ISSUE TITLE
relation between rule sets

### ISSUE THREAD

**Issue by TobiasKnauss** [MicrosoftDocs/visualstudio-docs#472]
It is unclear whether some rule sets base on others and enhance them (this seems to be the case, e.g. because CA1001 is part of multiple sets), or if every rule set stands for its own.
Thus please add more information and a comparison chart for all rule sets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e012f579-4db6-a56e-a82d-aa5158f62d91
* Version Independent ID: 347e3b42-05f2-2891-fd1d-f47c03247407
* Content: [https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-rule-set-reference](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-rule-set-reference#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/code-quality/code-analysis-rule-set-reference.md)

**Comment by gewarren** [comment]
@TobiasKnauss Thanks for the feedback. I'll add this to the backlog of things we need to address.

**Comment by tfosmark** [comment]
It looks like this issue has been addressed, so I am closing this. Thanks!

**Comment by gewarren** [comment]
@tfosmark I'm not sure this issue was addressed. Was that because I removed my assignment?

**Comment by gewarren** [comment]
Related to #2839

**Comment by gewarren** [comment]
2000 page views/month = P1
