### ISSUE TITLE
What's file tracking got to do with msbuild?

### ISSUE THREAD

**Issue by oskarb** [MicrosoftDocs/visualstudio-docs#4720]
It's entirely unclear how this relates to msbuild or how to use it when writing msbuild files. The examples are in C++.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401f8953-3165-194b-3706-92336a5a93e1
* Version Independent ID: 1b4ee143-9b5e-58fe-f82e-6614f36b8113
* Content: [File Tracking - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/file-tracking?view=vs-2019)
* Content Source: [docs/msbuild/file-tracking.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/file-tracking.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
https://stackoverflow.com/questions/27960893/how-to-implement-msbuild-file-tracking-feature-tracker-exe-for-a-not-native-vc - related StackOverflow question

**Comment by oskarb** [comment]
Well this is not fixed as such. The link from @ghogen shed some light on it, but I still think the page I linked to, which is named "File Tracking - **Overview**", could contain at least one or two sentences to explain why or when it is useful.
