### ISSUE TITLE
what about c++?

### ISSUE THREAD

**Issue by LordWolfenstein** [MicrosoftDocs/visualstudio-docs#4726]
I want to know how to change the icon of a c++ application in visual studio 2019. When I search for it I get here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 826f6de3-083c-37a0-0bff-ff12b690f37d
* Version Independent ID: 7ee0aa95-5a27-d6de-0715-07a40eda2ac3
* Content: [How to: Specify an application icon (Visual Basic, C#) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-specify-an-application-icon-visual-basic-csharp?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-specify-an-application-icon-visual-basic-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-specify-an-application-icon-visual-basic-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by corob-msft** [comment]
@LordWolfenstein 

The answer depends on what you're doing. Are you building an app from source, or are you trying to edit an existing, compiled app? Is it a traditional Desktop app, an MFC Desktop app, or an app for the Windows Runtime? In source form in Visual Studio, icons are stored in .ico files. These are bitmaps that can contain one or more icons, of varying sizes and bit depths. One place to get started on creating resources is in [Resource files (C++)](https://docs.microsoft.com/en-us/cpp/windows/resource-files-visual-studio?view=vs-2019). Visual Studio also has an [Image Editor for Icons (C++)](https://docs.microsoft.com/en-us/cpp/windows/image-editor-for-icons?view=vs-2019).

It's a little known fact, but you can open an executable file with Visual Studio, and see its resources. An app will typically have an Icon folder with icon resources listed by ID. Right click on one, and one of the options is to export. This will create a copy as a .ico file. If you open that in Visual Studio, it opens in the image editor. 

I'm closing this issue as unrelated to the document it's attached to. There is no simple equivalent doc for C++ in general.
