### ISSUE TITLE
How to repair file associations?

### ISSUE THREAD

**Issue by mikevanoo** [MicrosoftDocs/visualstudio-docs#4727]
"If you uninstall a version of Visual Studio on a computer that has more than one version installed, the file associations for Visual Studio are removed for all versions."

So, how to repair the file associations after uninstalling a version of VS?

**Comment by mikevanoo** [comment]
From this page: https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio-versions-side-by-side?view=vs-2019

**Comment by ornellaalt** [comment]
Hi @mikevanoo, thanks for your question! 
"Visual Studio will attempt to repair any broken file associations (those that are not associated with any valid application) at startup. That means if you have orphan file extensions that it can handle, it will re-associate itself as the default application to open those files." ([source](https://social.msdn.microsoft.com/Forums/en-US/c4e9bc78-38e4-4ead-a57e-c79a2087070b/visual-studio-2019-unattended-setup-file-associations?forum=vssetup)) 

If you are still having trouble, you can manually set whichever version of Visual Studio you'd like to use as the default on your machine. If you go to Control panel-> Default apps-> Choose default apps by file type, you can set the correct Visual Studio as the default for the appropriate file types. 

Closing this issue for now, but please do let us know if you have other issues.
