### ISSUE TITLE
Incorrect or outdated info on this doc

### ISSUE THREAD

**Issue by acadieman** [MicrosoftDocs/visualstudio-docs#4728]
In this portion of the doc : https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---installpath
we are shown these 2 commands:

vs_enterprise.exe --update --quiet --wait
vs_enterprise.exe update --wait --passive --norestart --installPath "C:\installPathVS"

followed by this note : "Both commands are required. The first command updates the Visual Studio Installer. The second command updates the Visual Studio instance. To avoid a User Account Control dialog, run the command prompt as an Administrator."

Currently I am updating our visual studio 2017 version on our build farm and I am finding this to be incorrect.
If I load up my Visual studio installer UI via control panel, to update. It prompts that I must update my installer first.

On command line I use this single command: "vs_Professional.exe update --quiet --wait" and it updates both my installer and my vs2017 version.

Update the doc please.

I am running this command: "vs_Professional.exe update --quiet --wait"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---installpath)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @acadieman, thank you for your feedback! I will confirm that this works in all scenarios and update the documentation accordingly.

**Comment by ornellaalt** [comment]
Hi @acadieman, I've looked into the issue and talked to our engineering team. It is correct that running "vs_Professional.exe update --quiet --wait" will update both the Visual Studio Installer and Visual Studio, but in a scripted environment, it will not wait properly. The documentation was misleading since we said both were "required." I've changed the language to say "advised," to be inclusive of all types of environments. We'll close this issue now- if you have any other feedback, please let us know!
