### ISSUE TITLE
What if we are using the Constructors with Default parameters to replace these 3 constructors?

### ISSUE THREAD

**Issue by sudhanshu1978** [MicrosoftDocs/visualstudio-docs#4730]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55e7ba0-f8c0-68fb-d2db-c8b45d60c4ad
* Version Independent ID: e21c9a8e-faf0-e484-f8b0-f8e991b1e601
* Content: [CA1032: Implement standard exception constructors - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1032?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca1032.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1032.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@sudhanshu1978 Seems like this would violate the rule. @mavasani to comment.

**Comment by Mikejo5000** [comment]
@sudhanshu1978 If you would like to see the rule changed so that default constructors do not violate the rule, please open the issue here:
https://github.com/dotnet/roslyn-analyzers/issues
Thanks! @mavasani fyi
