### ISSUE TITLE
Documentation on setting up LSP with colorized tagging is inadequate

### ISSUE THREAD

**Issue by kaby76** [MicrosoftDocs/visualstudio-docs#4735]
I have an LSP client and server for Antlr that works (the extension is called [AntlrVSIX](https://github.com/kaby76/AntlrVSIX)). It uses the [client](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServer.Client/) and [server](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServer.Protocol/) APIs provided by Microsoft, which I thought would save me time and sweat on writing my own LSP APIs. The [ILanguageClient](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md#main-interface---ilanguageclient) interface in the client works fine, and I am happy with that. The much harder problem remaining to solve is colorized tagging of the symbols in the file.

LSP 3.15 supposedly supports the definition of color attributes for symbols. However, it's been a couple years since this part of the spec was written, and the APIs still do not support color attributes.

Hence, the documentation in this git repository suggests a solution using [TextMate](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md#textmate-grammar-files). However, there are two problems with this approach. First,  most real programming languages, include Antlr, are not regular. Writing patterns to pick out symbols to tag, even for an expert, is hard to get right. I have tried two existing tmLanguage files, and neither work. [One](https://github.com/madskristensen/TextmateBundleInstaller/blob/master/src/Bundles/antlr/syntaxes/Antlr.tmLanguage) was written by Mads Kristensen who works for MS. Second, writing the TextMate patterns for symbol identification *duplicates* the functionality of the LSP server. It is, in fact, the *raison dêtre* for LSP. So, I would prefer not to go this route.

Another solution is to intercept messages between the client and server APIs and write my own ITagger<>. I have written these several times, so I feel comfortable with this solution. However, the APIs and/or documentation provided here does not work in intercepting LSP messages.

I have tried to follow the instructions describing the ["Middle Layer"](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md#middle-layer). (Note, the section contains several stale 404 links.) The code provided in this section (and the [previous section](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md#send-custom-messages)) do not work. Using ILanguageClientCustomMessage causes the ILanuageClient interface to never be called. Per chance, I did try an ILanguageClientCustomMessage2 interface, and that seemed to work. (PVTS--a Microsoft developed product for Python), in fact, uses ILanguageClientCustomMessage2 but it's not documented anywhere. ILanguageClientWorkspaceSymbolProvider, suggested in this documentation, is actually obsolete. However, neither ILanguageClientWorkspaceSymbolProvider or ILanguageClientMiddleLayer work.

Please update your documentation and APIs. At this moment, since I cannot rely on either of these interfaces, I will try to capture packets at the stream level and write my own handlers.

**Comment by kaby76** [comment]
I have a solution that is starting to work. Using ILanguageClientCustomMessage2, I can create a custom message that duplicates the [Document Symbols Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentSymbol), so I can query the LSP server for symbols and their types. I can also provide another custom message to query the LSP color scheme with the as yet unimplemented [Document Color Request](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentColor). With this, I can now create an ITagger.GetTags() that tags and colorizes the symbols in the text.  If the Microsoft client/server APIs for colorization are implemented, I can simply remove this functionality. For other LSP clients that do implement colorization, I can use the LSP server directly as is. I was very fortunate to stumble on using ILanguageClientCustomMessage2 instead of the completely non-functional ILanguageClientCustomMessage interface because VS2019 provided ILanguageClientCustomMessage2 as an alternative while typing ILanguageClientCustomMessage.

**Comment by kaby76** [comment]
So, some good news. I implemented an ITagger<> for text colorization using a custom message to perform an LSP query. This works fine and it is fast. So, what is being spec'ed out for VSCode and LSP version 4.16 for semantic highlighting should work out fine once implemented in VSSDK. It's important to note that in the case where you want to have the server implement a refactoring of the code, the server should use the LSP workspace/applyEdit request, and let the MS LSP client make the edits. Extension programmers should not write code to apply edits from the server using "var e = ITextBuffer.CreateEdit(); ...; e.Apply();".  The problem is that the client calls the ITagger<>.GetTags() before the MS LSP client has time to update the server with the edits, and there doesn't seem a way to control the order (whether GetTags() is called first, then the server updated, or vice versa). https://github.com/kaby76/AntlrVSIX/issues/43

**Comment by SLdragon** [comment]
Hi, team, any update about why ILanguageClientCustomMessage not work?

**Comment by kaby76** [comment]
I just retested the code with ILanguageClientCustomMessage with version 16.5.1063 of the LSP client and protocol packages and 16.6.2 of VS2019. It still does not call the ILanguageClient constructor. But, I now finally get an output message in VS at the top indicating this:

    System.TypeLoadException: Method AttachForCustomMessageAsync in type LspAntlr.AntlrLanguageClient from assembly AntlrVSIX, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null does not have an implementation.
       at LspAntlr.AntlrClassifier.&lt;GetTags&gt;d__8.MoveNext()
       at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

It does have a body, pretty much copied from the documentation:

        public async Task AttachForCustomMessageAsync(JsonRpc rpc)
        {
            await Task.Yield();
            _rpc = rpc;
        }

It sounds like you are trying to find the method but it's not fitting what you expect.

--Ken

**Comment by WilliamAntonRohm** [comment]
@kaby76 -- Ken, thank you for your continued contributions.

@acangialosi -- Anthony, assigning this issue back to you for housekeeping.

cc @leslierichardson95 for awareness

**Comment by kaby76** [comment]
FYI. [Microsoft.VisualStudio.LanguageServer.Protocol](https://www.nuget.org/packages/Microsoft.VisualStudio.LanguageServer.Protocol/) is tied heavily to the VS2019 client implementation. It is several years behind the spec, and thus cannot be used for other clients, e.g., VSCode. I spent a week and re-implemented the entire package completely from scratch from the [LSP Spec 3.16](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/) for all types in the spec. My LspTypes package is available [here](https://www.nuget.org/packages/LspTypes/). I don't scrape the implementation from the spec, but that's a future project I may do since hand-translation of the spec to implementation is far too primitive, slow, and error-prone.

**Comment by acangialosi** [comment]
Reassign to Dante Gange to triage and resolve.
