### ISSUE TITLE
ngocbauofficial

### ISSUE THREAD

**Issue by ngocbauofficial** [MicrosoftDocs/visualstudio-docs#4736]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ca4cea-be24-22ad-49d0-d34e3f800900
* Version Independent ID: 8cd52773-0617-684e-8136-bd4ea03515de
* Content: [Find calls to a method - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/call-hierarchy?view=vs-2019)
* Content Source: [docs/ide/reference/call-hierarchy.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/call-hierarchy.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ngocbauofficial -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
