### ISSUE TITLE
Will not work with the newer IAsyncQuickInfoSource API

### ISSUE THREAD

**Issue by sbobin** [MicrosoftDocs/visualstudio-docs#4737]
Querying navigator.GetExtentOfWord from the newer IAsyncQuickInfoSource API will freeze the IDE. It must be called from the main UI thread. Please update the provided examples. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28863dd2-b54a-4733-ebc7-57d0235bfc95
* Version Independent ID: b9062a5a-ac9a-d8c5-00d9-204a6bd98d30
* Content: [Walkthrough: Displaying QuickInfo Tooltips - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-quickinfo-tooltips?view=vs-2017#feedback)
* Content Source: [docs/extensibility/walkthrough-displaying-quickinfo-tooltips.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-displaying-quickinfo-tooltips.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by gundermanc** [comment]
Generally the Text structure navigator should be stateless and usable from any thread, however, in languages that rely on the IVsLanguageTextOps or another code path that requires the UI thread may have to force-marshal to the UI thread to acquire this information using `await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync()`.

**Comment by sbobin** [comment]
Hi!

Thanks for your reply!

If the customers use the “walkthrough” template provided in the doc, it uses the older IQuickInfoSource API. Then Visual Studio will add green scribbles under the related keywords and suggest to use the newer IAsyncQuickInfoSource API. If the customers follow that suggestion then they will quickly get stuck with a freezing IDE without more hints.

It is not quite obvious: it would really be worth documenting that and add a new “walkthrough” template for the newer IAsyncQuickInfoSource API in the Visual Studio extension documentation.

Thanks!

-- Stéphane

**Comment by gundermanc** [comment]
@madskristensen @olegtk do either of you know who owns the walk-through docs?

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
