### ISSUE TITLE
no dividebyzero despite written as 

### ISSUE THREAD

**Issue by decafbad** [MicrosoftDocs/visualstudio-docs#4738]
I didn't get DivideByZero exception; just an infinity sign printed. Because document says convert vars to floats, before that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@decafbad You're right; it looks like the steps in this tutorial no longer work the way they did when the tutorial was originally written and tested. We'll revise the tutorial soon and report back when the PR is merged.

**Comment by TerryGLee** [comment]
@decafbad The PR is merged and the updates will be published at approximately 4:00 P.M. (Pacific Daylight Time) today, 2/19/2020. Thanks for helping us improve the documentation!
