### ISSUE TITLE
BACK

### ISSUE THREAD

**Issue by nengherr** [MicrosoftDocs/visualstudio-docs#474]
visual studio interpris not install

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Service: unspecified

**Comment by gewarren** [comment]
@nengherr It sounds like you are having an issue installing Visual Studio Enterprise. Please enter your installation issue here: https://developercommunity.visualstudio.com/.
