### ISSUE TITLE
Broken links in PRMerger18 message on github PRs

### ISSUE THREAD

**Issue by Rastaban** [MicrosoftDocs/visualstudio-docs#4742]
The following [comment](https://github.com/MicrosoftDocs/visualstudio-docs/pull/4741#issuecomment-581586269) was left in PR #4741 by @PRMerger18, I get a 404 error for all of the links.  It makes sense that the private repo link may not work depending on permissions, but the public and contributor guide instructions links should work.  

> Microsoft authors of articles need to make updates through the private repository so the updates can be staged and validated by the current validation rules. After you review staging and fix all validation issues, you can add the sign-off comment to let the PR reviewers know the updates are ready to be merged.It's easy to access the private repo version of your articles in GitHub. Just add -pr to the URL, as follows:
> Public repo URL: https://github.com/Microsoft/azure-docs/blob/master/articles/azure-portal-overview.md
> Private repo URL: https://github.com/Microsoft/azure-docs-pr/blob/master/articles/azure-portal-overview.md
> We have closed this pull request. Please resubmit the updates through the private repo. If you need perms to the private repo, [see the contributor guide instructions](https://github.com/Microsoft/azure-docs/blob/master/contributor-guide/tools-and-setup.md#permissions)

**Comment by msebolt** [comment]
@Rastaban Thank you for the feedback.

This should probably moved to the [Microsoft Docs](https://github.com/MicrosoftDocs/feedback/issues) repo.

**Comment by WilliamAntonRohm** [comment]
You can also submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
