### ISSUE TITLE
csharp_using_directive_placement Is missing documentation

### ISSUE THREAD

**Issue by ryzngard** [MicrosoftDocs/visualstudio-docs#4743]
csharp_using_directive_placement was added in 16.1 and has not been documented

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db54afa5-fc7b-394f-ede3-4d1d46ec695d
* Version Independent ID: 86441bf6-9e5b-85c2-d42d-3afd5a9a069b
* Content: [.NET formatting conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019&source=docs#feedback)
* Content Source: [docs/ide/editorconfig-formatting-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-formatting-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by mikadumont** [comment]
Added documentation to this!
