### ISSUE TITLE
Component id Microsoft.Net.Core.Component.SDK.2.2 is not working

### ISSUE THREAD

**Issue by nideeshmanian** [MicrosoftDocs/visualstudio-docs#4745]
Component id Microsoft.Net.Core.Component.SDK.2.2 is not working. It is giving me error message "The package Microsoft.Net.Core.Component.SDK.2.2 is not found". I am able to install other packages "Microsoft.VisualStudio.Workload.WebBuildTools". This package has .net core 3.0 and not 2.2. As my project is on 2.2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e062363-94e9-f776-650f-a0723ab713a3
* Version Independent ID: 9181db12-cbdf-6f95-27f1-833930d6d323
* Content: [Visual Studio Build Tools workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#web-development-build-tools)
* Content Source: [docs/install/workload-component-id-vs-build-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-build-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@nideeshmanian -- thank you for your feedback.  You may find assistance here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
