### ISSUE TITLE
Common Error

### ISSUE THREAD

**Issue by upsampled** [MicrosoftDocs/visualstudio-docs#4746]
You should add to the  'Diagnosing a failed install'  section that a common error is that there is not enough disk space. This can be verified by checking the `vslogs\dd_setup_<timestamp>_errors.log`. 

```
[0ad0:0011][2020-02-04T10:29:29] Pre-check verification: Visual Studio needs at least 91.99 GB of disk space. Try to free up space on C:\ or change your target drive.
[0ad0:0011][2020-02-04T10:29:37] Pre-check verification failed with error(s) :  SizePreCheckEvaluator.
```
**references**
* https://developercommunity.visualstudio.com/content/problem/865867/get-visual-studio-builds-working-with-docker.html
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @upsampled, thank you for your feedback! I will look into this and edit the documentation appropriately.

**Comment by ornellaalt** [comment]
Hi @upsampled, I've added the error you mentioned to the section of our [known issues](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container-issues?view=vs-2019) page where this issue was documented. I'll close this issue, but please feel free to let us know if you have any other questions.
