### ISSUE TITLE
Visual Studio for Mac ignores allowedVersions

### ISSUE THREAD

**Issue by themadat** [MicrosoftDocs/visualstudio-docs#4747]
Package Manager still shows package can be updated and when you select update it works (this should fail)

<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[2.1.1]" allowedVersions="[2.1.1]" />

Select Update and this gets updated to 3.1.1 even though the above syntax should prevent that

**Comment by themadat** [comment]
`<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="[2.1.1]" allowedVersions="[2.1.1]" />`

**Comment by WilliamAntonRohm** [comment]
@themadat -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by themadat** [comment]
@WilliamAntonRohm Thanks for the followup, sorry for the vagueness.

In Visual Studio for Mac version 8.4.4 when you edit you .csproj file for a PackageReference to only allow it to have certain versions following the latest Nuget syntax there are two issues:
1. FUNCTIONAL - When you right click on the Dependencies Folder, Nuget Folder, or the Package itself in the Solution Explorer and select Update, it will update to the latest package even if the allowedVersions tag in the PackageReference is set to prevent that.
2. USER INTERFACE - The Green Update Arrow is present in the Solution explorer AND the package is in the Manage Nuget Packages Update column even though the allowedVersions specifies that it can't be updated.

**Comment by WilliamAntonRohm** [comment]
@themadat -- thank you for clarifying. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. 

Are you asking about a particular docs.microsoft.com article?  This repo is only for documentation issues, and we have limited support options here.

**Comment by themadat** [comment]
Thank you; I reported the bug. In terms of documentation this is where the issue is: https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages#constraining-upgrade-versions
This does not work with .csproj files which according to this article https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference
all features should have been ported

**Comment by WilliamAntonRohm** [comment]
@themadat -- thanks!

@karann-msft -- please look into this potential documentation update.

**Comment by karann-msft** [comment]
@themadat - 

> This does not work with .csproj files which according to this article https://docs.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference all features should have been ported
What feature are you referencing and can you point out the specific language on that page that gave you the impression that the feature had been ported.

**Comment by themadat** [comment]
@karann-msft 

The opening sentence of the article
>  Visual Studio 2017 Version 15.7 and later supports migrating a project from the packages.config management format to the PackageReference format.

That statement combined with the below infer this is the replacement and can be migrated as such
> PackageReference is under active development: ... packages.config is no longer under active development.

There is a **Limitations** AND **Known Issues** section in the article, but 'lack of support for AllowedVersions' is not listed in either of them (I would suggest it belongs in the Limitations sections unless there are plans to include it then it should be in known issues).

**Comment by karann-msft** [comment]
@themadat - we have taken the approach of listing what is supported, which is a much shorter list rather than listing every single thing that is not supported. I would ask that you not assume something as supported unless you see documentation that explicitly suggests that it is. In the case - there are no docs that suggest `allowedVersions` are supported with `PackageReference`. Makes sense?

**Comment by themadat** [comment]
@karann-msft 
Sort of. I guess this becomes a usability issue. You can't tell me I have replaced 'X' with 'Y' but then say I won't tell you, but not everything in Y supports what X did. Have fun figuring it out...

**Comment by karann-msft** [comment]
@themadat - made changes to call out that specific case explicitly.

@WilliamAntonRohm back to you.

**Comment by WilliamAntonRohm** [comment]
@themadat -- thank you for your feedback and followup.

@karann-msft -- thank you for your attention to this issue.
