### ISSUE TITLE
Sort the list please!

### ISSUE THREAD

**Issue by DJackman123** [MicrosoftDocs/visualstudio-docs#4753]
It would be much easier to find properties in this table if they were sorted alphabetically.  Most of them are alphabetical, but ProduceOnlyReferenceAssembly is after ProduceReferenceAssembly, and (even worse) ProcessorArchitecture, RootNamespace, and Satellite_AlgorithmId come after StartupObject.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019#feedback)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
This is fixed, thanks for the feedback!
