### ISSUE TITLE
"How to: Create multi-project templates" doesn't deal with project references

### ISSUE THREAD

**Issue by pm64** [MicrosoftDocs/visualstudio-docs#4758]
Currently, the creation of multi-project templates as documented does not contemplate project references.

When using the template to generate a solution, we can transform project names to our liking in the ProjectTemplateLink tags:

< ProjectTemplateLink ProjectName="$safeprojectname$.Foo.Bar" >...

In this case, the documentation does not explain how the transformation of the project's name would be reflected in project references to it elsewhere in the solution.

Project references appear to retain the names of the project references used in the original solution from which the solution template was generated. The process of overriding project reference names via templating in the .csproj file to correct such inconsistencies is not explained in the documentation.

**Comment by WilliamAntonRohm** [comment]
@pm64 -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing.

**Comment by TerryGLee** [comment]
@WilliamAntonRohm I believe it's this one: [How to: Create project templates](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates?view=vs-2019), as referenced in the issue title :)
