### ISSUE TITLE
Need to add "Closed" to the suggestion status

### ISSUE THREAD

**Issue by danieljllo** [MicrosoftDocs/visualstudio-docs#4759]
I was going to add a suggestion for Azure DevOps product and found someone already made it. The suggestion never got any votes or comments so it got "Closed". This "Closed" status (without a qualifier like "Duplicate" or "Other Product") is not listed on this page as one of the possible statuses for a suggestion. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2017#feedback)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by WilliamAntonRohm** [comment]
@danieljllo -- please see my response in #4760.  
I am closing this issue #4759 now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
