### ISSUE TITLE
How to build the actual command line executables from the IDE

### ISSUE THREAD

**Issue by garnetr** [MicrosoftDocs/visualstudio-docs#476]
This article doesn't tell how to create the HelloWorld.exe from the IDE.  I would like to see explicit instructions for creating Windows, Mac, and Linux target executables from the IDE.

I have tried options in the build menu, and none of them resulted in an .EXE getting created. I dont want to build the .exe from the commandline right now, because eventually the project will have many different modules, and perhaps borrow from other classes. 

When F5 is used from the VS 2017 IDE under Windows, the commandline that comes up is a window from c:\Program Files\dotnet\dotnet.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5022ad-0de6-a16f-3f79-394f57f78903
* Version Independent ID: ecc54693-3334-34f6-ff75-0a0413be4bec
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-visual-basic-console)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/ide/quickstart-visual-basic-console.md)
* Service: unspecified

**Comment by gewarren** [comment]
@garnetr thanks for the feedback. The quickstart you were looking at is not intended to go into detail about build targets. However, pressing F5 will build an executable for you. If you build your project (Build menu > Build Solution), and then look in the Output window, it will tell you where your executable is, e.g.:

1>------ Build started: Project: NotInToc, Configuration: Release Any CPU ------
1>  NotInToc -> C:\Users\gewarren\source\repos\not-in-toc\NotInToc\bin\Release\NotInToc.exe

For info about building and compiling, see https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application. For info about C++ Linux projects, see https://docs.microsoft.com/en-us/cpp/linux/download-install-and-setup-the-linux-development-workload.

**Comment by gewarren** [comment]
Also, here is more information about using Visual Studio 2017 for [Linux ](https://www.visualstudio.com/en-us/productinfo/vs2017-compatibility-vs#a-iddeveloplinux-avisual-studio-2017-support-for-linux-development) and [MacOS](https://www.visualstudio.com/en-us/productinfo/vs2017-compatibility-vs#a-iddevelopmacos-avisual-studio-2017-support-for-macos-development).
