### ISSUE TITLE
There is no such option "Debug > Profiler"

### ISSUE THREAD

**Issue by asm128** [MicrosoftDocs/visualstudio-docs#4761]
There is no such option "Debug &gt; Profiler"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eacdab81-3b22-7d46-b44b-94cebe32988c
* Version Independent ID: b7a188e4-1699-d2a5-ca2a-8042f6f0ece5
* Content: [Beginners guide to CPU sampling - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-cpu-sampling?view=vs-2017)
* Content Source: [docs/profiling/beginners-guide-to-cpu-sampling.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/beginners-guide-to-cpu-sampling.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@asm128 Hi, can you let us know what version of Visual Studio you are using? Thanks.

**Comment by asm128** [comment]
vs 2019 community 16.4.3 now updating to 16.4.4

**Comment by Mikejo5000** [comment]
Yes, the doc here is actually VS 2017 (the upper left corner of the doc above the left navigation has the version switcher). The Performance Wizard is removed in VS 2019. Some features, such as instrumentation are available in VS 2019 in the Performance Profiler.
The best statement I've seen about the changes is here, see the comments by Allen Denver.
https://developercommunity.visualstudio.com/content/problem/441152/missing-profiler-options-under-debug-visual-studio.html

**Comment by Mikejo5000** [comment]
Also, in case it's not clear the CPU Usage tool in VS 2019 is the closest equivalent to the VS 2017 CPU sampling in the Performance Explorer / Perf Wizard.
