### ISSUE TITLE
Stale Documentation

### ISSUE THREAD

**Issue by mlafleur** [MicrosoftDocs/visualstudio-docs#4762]
This page contains some out of date information:
- Feature Flags have been replaced by Preview Features
- Test Explorer screenshots do not reflect the recent UI overhaul. In particular, the Hierarchy View information is now quite stale. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fa1671-f27f-484e-8994-ceb85b1a73d6
* Version Independent ID: 5b90e41e-b4ba-7cb7-b798-59ea1ae38eb4
* Content: [Test Explorer FAQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq?view=vs-2019#test-explorer-hierarchy-view)
* Content Source: [docs/test/test-explorer-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/test-explorer-faq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by Mikejo5000** [comment]
@mlafleur Thanks! We will take a look at this.
