### ISSUE TITLE
Given suggestions don't help

### ISSUE THREAD

**Issue by pebr70** [MicrosoftDocs/visualstudio-docs#4765]
I've got tried solution #3 and #4 but the problem still hold on. The given suggestions don't help in my case!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfd7078-683e-9fd6-247b-e75d4ed16a32
* Version Independent ID: ae3300c4-55a8-59b6-846b-50c48c88dcfe
* Content: [Error: Evaluating the function 'function' timed out and needed to be aborted in an unsafe way - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.unsafe_func_eval_abort)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@pebr70. Hi, the product team needs more info to help resolve.  In VS, please Send Feedback > Report a Problem to provide additional data. You may want to look at MicrosoftDocs/visualstudio-docs#831 for more info. Otherwise, if you have more info on what helped to resolve the issue for you, let us know. Thanks!
