### ISSUE TITLE
I personally want to thank all of you for your services

### ISSUE THREAD

**Issue by catfishfishcat** [MicrosoftDocs/visualstudio-docs#477]
Much appreactiated.

-Catfish-

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92764c94-7850-82b9-d54d-9b55fc7c271b
* Version Independent ID: c0fef252-5e8d-93c3-1c63-029fb511d81a
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/microsoft-help-viewer-installation)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live-sxs/docs/ide/microsoft-help-viewer-installation.md)
* Service: unspecified

**Comment by gewarren** [comment]
@catfishfishcat Thank you!

**Comment by raysefo** [comment]
How to install VS on a drive other than C? Is there a way to install all of the features on drive D?

**Comment by gewarren** [comment]
@TerryGLee can you point @raysefo to to a topic about this, if it exists? Thanks!

**Comment by TerryGLee** [comment]
@raysefo Thanks for your feedback! We don't have a topic that describes how to do this, as we're still working on adding that functionality.

**Comment by SelmaI** [comment]
@raysefo , I am a Program Manager at Visual Studio team. I am currently working on the topic of your question. Could you please reach me directly at selmai at microsoft dot com?

**Comment by catfishfishcat** [comment]
Yes  I can. What can I help you with?

Sent from Mail for Windows 10
