### ISSUE TITLE
Incremental builds with adding/deleting input files

### ISSUE THREAD

**Issue by shahabhijeet** [MicrosoftDocs/visualstudio-docs#4770]
https://docs.microsoft.com/en-us/visualstudio/msbuild/incremental-builds?view=vs-2019
During incremental builds, outputs detect changes when Input files are changed.
But if files are added or delete, changes will not get detected and hence the output will not get updated.
We should mention that somewhere in the documentation and possibly provide an alternate solution (for e.g. providing a generated hash file)
Sample Target
```
<ItemGroup>
    <AllExtFiles Include="Common\**\*.js;Common\**\*.png" />
  </ItemGroup>
<Target Name="packageDevExt" Condition=" '$(Configuration)' == 'Debug' " Inputs="@(AllExtFiles)" Outputs="$(SourceDirPath).zip" >
    <Message Text="Generated Developer Extension Package" Importance="low"/>
    <ZipDirectory Overwrite="true" SourceDirectory="$(SourceDirPath)" DestinationFile="$(ZipSourceDirPath).zip" />
  </Target>
```
If you do not edit any files, the target will be skipped and If you edit any files within AllExtFiles, the output will get updated.
But if you add new files or delete existing files, especially when you are using wildcard, it will not detect changes and hence won't update the output.

**Comment by ghogen** [comment]
@shahabhijeet There's a [new doc](https://docs.microsoft.com/visualstudio/msbuild/build-process-overview) now that describes the MSBuild process, which includes information on when such things as item lists are evaluated.  When an ItemGroup is at the top level (not in a target), it gets evaluated during one of the initial evaluation phases, before any targets are run.  As such, yes, it includes the set of matching files at that stage of execution, and files that are created later do not get included. A possible solution is to move the creation of the ItemGroup into a target. In your ZipDirectory example, would it be possible to move the ItemGroup into the `packageDevExt` target?

**Comment by ghogen** [comment]
Closing this issue, since the new doc mentioned above should help users design their build systems to avoid such problems.
