### ISSUE TITLE
IDM_VS_MENU_EXTENSIONS is incorrect

### ISSUE THREAD

**Issue by DeanMauro** [MicrosoftDocs/visualstudio-docs#4774]
Similar to #4445 and #3144. The extensions menu ID is listed as `IDM_VS_MENU_EXTENSIONS`, but this key does not exist (see the vsshlids.h link below). What is the correct ID for adding a command to the Extensions menu?

https://github.com/microsoft/CodeContracts/blob/master/Common/Include/vsshlids.h#L612

**Comment by WilliamAntonRohm** [comment]
@DeanMauro -- Dean, thank you for your question.  You may find answers here:
 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

Do you have a particular docs.microsoft.com article in mind?  If so, please @ mention me for followup.

**Comment by DeanMauro** [comment]
I've looked further and the code needed to add to the Extensions menu differs from all the other menus.

To add to Tools, for example, the menu's parent is `IDM_VS_MENU_TOOLS`. 
To add to Project, it is `IDM_VS_MENU_PROJECT`.

To add to Extensions, the menu's parent is `IDG_VS_MM_TOOLSADDINS`

[As per this documentation](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-menu-to-the-visual-studio-menu-bar?view=vs-2019#create-a-menu-on-the-ide-menu-bar)

**Comment by acangialosi** [comment]
Reassign to leslierichardson95 to triage and resolve.
