### ISSUE TITLE
Productivity Docs for 16.5

### ISSUE THREAD

**Issue by mikadumont** [MicrosoftDocs/visualstudio-docs#4776]
- [x] Combine wrap, indent, and align doc into one and include binary expressions
- [x]  Add private field from Constructor
- [x] Convert if to switch expressions or switch statements
- [x] Simplify string interpolation 
- [x] Make member static
- [x] Extract local function

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ce42b1-5ca3-2bba-be51-172e0ad715fd
* Version Independent ID: 3e28ccb0-f87e-bb74-c4f0-ed0ed2f1b364
* Content: [Refactoring - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/refactoring-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/refactoring-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@mikadumont -- Mika, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task or desired documentation update.

**Comment by WilliamAntonRohm** [comment]
@mikadumont -- Mika, I misunderstood the context here; @TerryGLee enlightened me.
