### ISSUE TITLE
Simpler version

### ISSUE THREAD

**Issue by softlion** [MicrosoftDocs/visualstudio-docs#4778]
There is a much simple way to add a menu, not in the vsct file, which is fine, but in code, with this helper class. Usage:

```csharp
var menuCommandService = (OleMenuCommandService)await package.GetServiceAsync(typeof(IMenuCommandService));

menuCommandService.AddGenericCommand(YourPackageCommandSet, YourCommandId, () =>
{
  ThreadHelper.ThrowIfNotOnUIThread();

  var message = $"TODO {nameof(YourCommandId)}";
  var title = "Command executed";
  VsShellUtilities.ShowMessageBox(package, message, title, OLEMSGICON.OLEMSGICON_INFO, OLEMSGBUTTON.OLEMSGBUTTON_OK, OLEMSGDEFBUTTON.OLEMSGDEFBUTTON_FIRST);
});
```

```csharp
    internal static class GenericCommandExtensions
    {
        /// <summary>
        /// Adds our command handlers for menu (commands must exist in the command table file)
        /// </summary>
        public static MenuCommand AddGenericCommand(this OleMenuCommandService menuCommandService, Guid commandSet, int commandId, Action action)
        {
            menuCommandService = menuCommandService ?? throw new ArgumentNullException(nameof(menuCommandService));
            var menuCommandId = new CommandID(commandSet, commandId);
            var menuItem = new MenuCommand((s,e) => action(), menuCommandId);
            menuCommandService.AddCommand(menuItem);
            return menuItem;
        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0bef76dc-c6a5-b1ce-20d3-9d099ab07d60
* Version Independent ID: f3eef871-e93d-96af-db5d-efb72b840322
* Content: [Adding a Submenu to a Menu - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-submenu-to-a-menu?view=vs-2019)
* Content Source: [docs/extensibility/adding-a-submenu-to-a-menu.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/adding-a-submenu-to-a-menu.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by leslierichardson95** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. Due to current resourcing and substantial extensibility changes we are currently working on that will result in significant doc changes, we are closing this lower priority issue. We will return to this issue on a later date and address it based on it's relevance after those extensive extensibility updates are made. Feel free to comment here as necessary.
