### ISSUE TITLE
compile error c1041

### ISSUE THREAD

**Issue by chenpei2** [MicrosoftDocs/visualstudio-docs#4782]
Hi!
I installed vs build tools in container successfully, but when using it to build my project,I got error message :"fatal error C1041
: cannot open program database 'xxx.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS" . I could build this project with full IDE.
Any idea how to fix it without modifying the project configurations?Are there any missing components?
Here are the components I installed in docker container.

RUN C:\TEMP\Install.cmd C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --add Microsoft.VisualStudio.Workload.MSBuildTools `
    --add Microsoft.VisualStudio.Workload.VCTools;includeRecommended `
    --add Microsoft.VisualStudio.Component.VC.ATL `
    --add Microsoft.VisualStudio.Component.VC.ATLMFC `
    --add Microsoft.VisualStudio.Component.VC.CLI.Support `
    --installPath C:\BuildTools `
    || IF "%ERRORLEVEL%"=="3010" EXIT 0

Thanks a lot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@chenpei2 -- it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​  

 - We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

Regarding the compile error, these links may provide additional information:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by ornellaalt** [comment]
Hi @chenpei2, I'll investigate this issue and get back to you as soon as possible.

**Comment by chenpei2** [comment]
> Hi @chenpei2, I'll investigate this issue and get back to you as soon as possible.

Here is some information that maybe could help:
I have set /MP in my project.
I used msbuild command line to build in container 
```
"C:\BuildTools\MSBuild\Current\Bin\MSBuild.exe" C:\myproject.vcxproj -t:Rebuild /p:Configuration=Release;Platform=x64
```
Thank you.

**Comment by ornellaalt** [comment]
Hi @chenpei2, we've updated the Build Tools documentation [here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019). Please give the new instructions a try. We look forward to your feedback, and I'll be closing out this issue in the meantime.

**Comment by tobyhu87** [comment]
@chenpei2 can you please open a feedback ticket instead?  This is a VC build issue and not a docker related issue.

**Comment by ornellaalt** [comment]
Closing out this issue as per @tobyhu87's comment above.

**Comment by chenpei2** [comment]
> @chenpei2 can you please open a feedback ticket instead? This is a C++ build issue and not a docker related issue. After you open a feedback ticket, the C++ build team can help you with your issue.
> 
> To open a feedback ticket, follow these instruction:
> 
> Report product issues to us via the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​

ok,thanks
