### ISSUE TITLE
Azure Boards & Repos (Basic)

### ISSUE THREAD

**Issue by tripleacoder** [MicrosoftDocs/visualstudio-docs#4783]
When I click the "Azure Boards & Repos (Basic)" link, I can see "Basic Plan".
But this includes Azure Pipelines and Azure Artifacts, not just Azure Boards and Azure Repos.

"Azure Boards & Repos (Basic)" should be renamed to "Basic Plan" if they refer to the same. Otherwise it should be made clearer if Azure Pipeline and Azure Artifacts are included or not.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by TerryGLee** [comment]
@evanwindom FYI

**Comment by evanwindom** [comment]
@tripleacoder - I've updated the link to include (Basic Plan) instead of just (Basic).

**Comment by evanwindom** [comment]
#please-close
