### ISSUE TITLE
Not Correct - Outdated

### ISSUE THREAD

**Issue by jefferyp1138A** [MicrosoftDocs/visualstudio-docs#4784]
This article is incorrect. Based on the publication date, it looks like it was written for VS 2015. I'm using VS 2019 Enterprise and the menus and pics of the UI are incorrect. 

On the left side of this page is the Version selection drop-down. If I choose Visual Studio 2019, I expect to see documentation for 2019, not previous versions unless the Visual Studio feature is unchanged from earlier versions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d41fc7-bc52-8fe3-6b25-c1b2c3f89eb1
* Version Independent ID: 9d141754-5f8f-d330-0974-75cbcf45a011
* Content: [Troubleshooting Code Coverage - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/troubleshooting-code-coverage?view=vs-2019)
* Content Source: [docs/test/troubleshooting-code-coverage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/troubleshooting-code-coverage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@jefferyp1138A Thanks! We will plan to get this updated.

**Comment by Mikejo5000** [comment]
Updating doc
