### ISSUE TITLE
Code snippet incomplete or not latest information for https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-inline-task?view=vs-2019#handle-reserved-characters

### ISSUE THREAD

**Issue by kotpal** [MicrosoftDocs/visualstudio-docs#4785]
Currently doc says: 
To include the reserved characters in code expressions such as Files.Length > 0, write the Code element so that its contents are contained in a CDATA expression, as follows:

> &lt;Code Type="Fragment" Language="cs"&gt;
>  &lt;![CDATA[
> 
>  // Your code goes here.
> 
>  ]]&gt;
> &lt;/Code&gt;

There is no code-snippet - but also there doesn't seem to be any need to escape any characters like &lt; and &gt; in latest versions of msbuild.

**Comment by ghogen** [comment]
@kotpal Are you saying that you were able to use symbols such as > and < in a code snippet in a Code element in MSBuild, without using CDATA ?

**Comment by kotpal** [comment]
@ghogen CDATA is needed, but the wording on that page is a little bit confusing, especially because there was no example provided. English is not my first language - and I can understand code better.  

It would be clear, if the code-snippet was provided, as in:

> &lt;Code Type="Fragment" Language="cs"&gt;
>  &lt;![CDATA[
> 
> if (Files.Length &gt; 0)
> {
>  // Your code goes here.
> }
> 
>  ]]&gt;
> &lt;/Code&gt;
