### ISSUE TITLE
License sign in bug

### ISSUE THREAD

**Issue by MikeRosoft** [MicrosoftDocs/visualstudio-docs#4787]
When I installed Visual Studio 2019, I had just 30 days of trial with no apparent option to extend it. Finally, I found out that I was already signed in to a Microsoft account; when I signed out and then signed in, the trial was automatically extended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bff48e07-208e-a8b1-0855-3f677cdf788b
* Version Independent ID: 0fd3926f-d997-c744-3f48-85568a2d462e
* Content: [Sign in to Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/signing-in-to-visual-studio?view=vs-2019)
* Content Source: [docs/ide/signing-in-to-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/signing-in-to-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@MikeRosoft -- thank you for your feedback.  Please report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

fyi @gdverrastro
