### ISSUE TITLE
'Info' could not be found

### ISSUE THREAD

**Issue by reisthi** [MicrosoftDocs/visualstudio-docs#4789]
I had this issue with the version 5.0.0 of Swashbucle.AspNetCore. I installed the 4.0.1 version and it worked just fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788828c4-74bc-1bcb-7480-38e490358f18
* Version Independent ID: d62da0a4-9a26-a89d-ff8f-d3314cf35724
* Content: [Step 4: Exposing a web API From Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-04?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-04.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@reisthi Thanks for letting us know; we'll add this info to the instructions on the page.

**Comment by douzj** [comment]
Can you try 'OpenApiInfo' or 'Microsoft.OpenApi.Models.OpenApiInfo' instead of 'Info' ?
