### ISSUE TITLE
VS2017 F1 documentation for C# keyword nameof lands here

### ISSUE THREAD

**Issue by ItrelAtRevolution** [MicrosoftDocs/visualstudio-docs#479]
Using nameof(constructorArgument) from within a class constructor for passing the name of the argument to a new InvalidArgumentException.
Just double checking the usage of nameof landed me here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a28ee58-bd99-e74a-0c0c-30f5a41da08e
* Version Independent ID: 2467c672-a567-583c-2801-87dcaf0f2c91
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.TextEditor)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.5.1)%26rd%3Dtrue)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/not-in-toc/default.md)
* Service: unspecified

**Comment by gewarren** [comment]
@yunyunyunyun I was told you are the contact person for fixing F1 issues. In this case, the nameof keyword in C# is not sending the right query string. Can you address this?

@ItrelAtRevolution thanks for letting us know how you landed on this page. That will help us fix the issue.

**Comment by gewarren** [comment]
I moved this issue to the Roslyn repo where it can be fixed.

https://github.com/dotnet/roslyn/issues/36001
