### ISSUE TITLE
Possible contradicting information

### ISSUE THREAD

**Issue by pedromagueija** [MicrosoftDocs/visualstudio-docs#4796]
Hi everyone,

I've read some documentation that seems to be contradictory.
Please do apologize if I misunderstood it.

The following link https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2019 indicates that 

> You can target multiple frameworks in a single project.

But this link https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-multitargeting-overview?view=vs-2019 indicates that

> Despite the name "multitargeting", a project can target only one framework 
> and only one platform at a time.

It's not clear to me after reading both links which one is correct.
Can you help me with this matter?

Thank you.

**Comment by LBynum77** [comment]
#assign LBynum77

**Comment by TerryGLee** [comment]
@pedromagueija Thanks for letting us know. We updated the information in https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2019  with the following information:

A Visual Studio solution can contain projects that target different versions of .NET.  However, note that you can only build against a single version of .NET either using reference conditionals for a single build or recursively build different binaries for each version.  For more information about target frameworks, see [Target frameworks](/dotnet/standard/frameworks).

We appreciate your helping us improve the documentation!
