### ISSUE TITLE
Vague

### ISSUE THREAD

**Issue by DroidDragon** [MicrosoftDocs/visualstudio-docs#4797]
This path ' \...\Visual Studio &lt;Version&gt;\Projects\&lt;ProjectName&gt;\&lt;ProjectName&gt;\Debug\&lt;ProjectName&gt;.txt' starts WHERE, exactly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7ba2cc8-5e18-60e9-5473-8017d8724d96
* Version Independent ID: e2adb3a5-8c61-4211-ae96-637a0602c1a7
* Content: [How to: View, save, and configure build log files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-view-save-and-configure-build-log-files?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-view-save-and-configure-build-log-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-view-save-and-configure-build-log-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@DroidDragon That was confusing.  I improved the wording here.
