### ISSUE TITLE
What's the difference between ToolTask and ToolTaskExtension?

### ISSUE THREAD

**Issue by pekkah** [MicrosoftDocs/visualstudio-docs#4800]
"Many tasks inherit from the ToolTaskExtension class, which inherits from the ToolTask class, which itself inherits from the Task class. This inheritance chain adds several parameters to the tasks that derive from them. These parameters are listed in this document."

What does that mean? Where are the examples? MSBuild documentation needs some love. It's powerful but the documentation makes me want to give up trying to use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 939cc723-71ef-b3c2-3877-be6744e575ef
* Version Independent ID: cbdb1897-ab16-b3de-1161-2bb6a6eeb405
* Content: [MSBuild Task Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-task-reference?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-task-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-task-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
ToolTaskExtension is not intended to be used directly.
