### ISSUE TITLE
This page only shows built in parameters, when its linked to as how to use custom parameters.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4801]
How does a user supply values to a custom parameter in a template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ffd68f8-8ba6-f868-648c-2a2b6e8899b4
* Version Independent ID: 52b9100f-d71c-7e9c-303f-76d1eafcfa20
* Content: [Add name parameters to project and item templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-substitute-parameters-in-a-template?view=vs-2019)
* Content Source: [docs/ide/how-to-substitute-parameters-in-a-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-substitute-parameters-in-a-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by edwardmcleodjones** [comment]
Custom template parameters can be added by defining CustomParameter tags in the .vsproject files.

```
<TemplateContent>
    <CustomParameters>
        <CustomParameter Name="$repositoryrootdir$" Value="C:\RepositoryRoot"/>
        <CustomParameter Name="$frameworkdir$" Value="C:\Program Files\Framework"/> 
    </CustomParameters>
</TemplateContent>
```

These parameters are used in the same way the standard parameters are used. The ext_ prefix gives access to parameters defined at solution level.

From: 
https://github.com/HerrNyani/knowledge_base/wiki/visual_studio_multi_project_template#custom-template-parameters

**Comment by StingyJack** [comment]
@github-actions bot you are a cancer on the community.

However, I am closing this because the new dotnet new style templates are much friendlier to work with overall and has examples and instructions on how to customize.
