### ISSUE TITLE
None of these doc pages say where to put the exported template so that VS will recognize it

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#4804]
...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f36dca-129d-9839-0e4b-fcadaa4b63d7
* Version Independent ID: 02d93129-77e2-e667-a06f-ad79f5f7240a
* Content: [Templates for projects and files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/creating-project-and-item-templates?view=vs-2019)
* Content Source: [docs/ide/creating-project-and-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/creating-project-and-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by ctolkien** [comment]
If anyone knows where to put this, it would be a big help. I can't find that info either.

**Comment by StingyJack** [comment]
@ctolkien the zip needs to be placed in the ~\documents\visual studio 2019\templates\projectTemplates folder. 

The zip it makes gives me errors when unzipping in 7zip, so I haven't tried to update the contents.  The template shows up near the bottom of the new project template list, and searching for it does not work, even by exact string. I think this functionality is just broken and nobody is running regression testing at Microsoft anymore.

**Comment by ctolkien** [comment]
OK, so my issue was:

* IT had used "known folder move" to move my documents onto onedrive.
* This did not update the paths used in VS (and/or there is no form of symlink)
* Manually updated the paths in the Options -> Projects and Solutions -> Locations to the new locations.
* Profit.

**Comment by timheuer** [comment]
Hi @StingyJack on the last part of this part of the doc https://docs.microsoft.com/en-us/visualstudio/ide/creating-project-and-item-templates?view=vs-2019#contents-of-a-template it talks about the location of the templates.  Is that not sufficient?  Or not sufficiently highlighted?  perhaps a header breakout of that would have helped see that content/link better?

**Comment by StingyJack** [comment]
That bot needs to be deprogrammed.

**Comment by StingyJack** [comment]
@timheuer can you highlight in that doc where it says the template location? I'm missing it

**Comment by timheuer** [comment]
@StingyJack wow old bug 😮. The link in the last paragraph takes you to https://docs.microsoft.com/en-us/visualstudio/ide/how-to-locate-and-organize-project-and-item-templates?view=vs-2019

**Comment by TerryGLee** [comment]
@StingyJack Thanks for taking the time to write up this issue. It looks like the problem you outlined is resolved; as such, we'll close this issue now, with our thanks to you for your continued interest in improving the documentation.
