### ISSUE TITLE
Missing where DockerfileContext is relative to

### ISSUE THREAD

**Issue by jilleJr** [MicrosoftDocs/visualstudio-docs#4806]
A explanation of where the path from the DockerfileContext property is relative to. Like "relative to the solution", "relative to the csproj". Tried finding it here but had to find it through testing that it is relative to the DockerfileFile property (which itself seems a bit weird IMO, would expect it would be from somewhere more static like relative to the csproj).

Great docs otherwise!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84f968ae-2fa3-06af-06c0-74e122071ce5
* Version Independent ID: af37447f-bb94-abac-c4cc-cac649575d2c
* Content: [Visual Studio Container Tools build properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2019#feedback)
* Content Source: [docs/containers/container-msbuild-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-msbuild-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Thanks, @jilleJr - I added some text here. It should be published soon.

**Comment by Dragonheart91** [comment]
Might be worth mentioning - is it possible to use variables (macroses) in DockerfileContext property?
For example to use OutDir if I want the context to be my output folder:
<DockerfileContext>./$(OutDir)</DockerfileContext>
From my personal testing it doesn't work (my OutDir is bin\Debug\), but maybe I'm missing something? I don't want to build in container, I want to use output instead and I don't want the path to be hardcoded to have different context for Debug/Release configurations.
