### ISSUE TITLE
Visual Studio Mac ASP.NET Publish option missing

### ISSUE THREAD

**Issue by HeribertoRB** [MicrosoftDocs/visualstudio-docs#4808]
Hi,

I am trying to publish an asp.net project to the web but when I right click the project for some reason the publish option is missing. I am not sure why VS is not showing it. Even if a create another asp.net project the publish option is missing. I checked and it seems that my computer has .NET Core has the latest version. I uninstalled visual studio and re-installed it but still having the same problem.

**Comment by WilliamAntonRohm** [comment]
@HeribertoRB -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.
