### ISSUE TITLE
What's the Visual Studio ModelBus Extension?

### ISSUE THREAD

**Issue by evil-shrike** [MicrosoftDocs/visualstudio-docs#481]
> Download and install the Visual Studio ModelBus Extension, if you have not already done this. For more information, see Visualization and Modeling SDK. 

It's unclear where Visual Studio ModelBus Extension should be downloaded from. There's no such an extension in Visual Studio Marketplace. 
The link "Visualization and Modeling SDK." (http://go.microsoft.com/fwlink/?LinkID=185579) just leads to VS landing page - https://www.visualstudio.com/. Useless.

> Open the DSL definition file. Right-click the design surface and then click Enable Modelbus. 

There's no such operation in generated Dsl models from templates from Modeling SDK.
Modeling SDK has nothing about ModelBus.

So it seems that the information is completely obsolete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6079ff38-d1b8-2cf5-243f-99f518a3228a
* Version Independent ID: 10c57f08-ab25-8942-5f58-74fb29a33411
* [Content](https://docs.microsoft.com/en-us/visualstudio/modeling/using-visual-studio-modelbus-in-a-text-template#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/modeling/using-visual-studio-modelbus-in-a-text-template.md)
* Service: unspecified

**Comment by gewarren** [comment]
@evil-shrike Yes, these docs are out-of-date and I apologize for that. The most up-to-date info on the Modeling SDK is [here](https://blogs.msdn.microsoft.com/devops/2016/12/12/the-visual-studio-modeling-sdk-is-now-available-with-visual-studio-2017/).

**Comment by romanoza** [comment]
@gewarren  Unfortunately, there is no answer to the original question ("What's the Visual Studio ModelBus Extension?") in this up-to-date info you have pointed out.

**Comment by romanoza** [comment]
@gewarren Unfortunately, there is no answer to the original question ("What's the Visual Studio ModelBus Extension?") in this up-to-date info you have pointed out.

**Comment by dksimpson** [comment]
I submitted a fix for this in PR #4562, thanks for reporting this issue.

**Comment by ghogen** [comment]
I think this is still an issue.

**Comment by ghogen** [comment]
I think this is still an issue.

**Comment by carzaza** [comment]
Any news? I am also having this problem... Thanks in advance.

**Comment by VictorIranzo** [comment]
How is the issue going? This [section](https://docs.microsoft.com/en-US/visualstudio/modeling/using-visual-studio-modelbus-in-a-text-template?view=vs-2019#create-a-model-bus-adapter-for-access-from-text-templates) has no sense. Where is the option "Enable Modelbus"? I can't find it. Could someone update the documentation? ... :(

**Comment by JoshuaPartlow** [comment]
Hi @mgoertz-msft - Would you be able to comment here?

**Comment by mgoertz-msft** [comment]
The ModelBus extension was a utility that had been written by a PM a long time ago. Unfortunately, at some point it was removed from the VS Gallery and the original source code was not preserved either. So far, we have been unable to locate these sources to rebuild and republish this extension.

If anyone reading this happens to still have this extension installed, we would appreciate it if you could provide us with the VSIX (you can contact me for help with that). Thank you!

**Comment by JoshuaPartlow** [comment]
Closing given the time open, if this is still an issue you feel should be addressed, please feel free to re-open.
