### ISSUE TITLE
How to add conditions inside vsTemplate file?

### ISSUE THREAD

**Issue by dk511** [MicrosoftDocs/visualstudio-docs#4810]
If there are three projects with three vsTemplates file, how to conditionally create only those projects which user has selected in the IWizard?
```

<ProjectCollection>
      <ProjectTemplateLink ProjectName="Cat">
        CatProject\Cat.vstemplate
      </ProjectTemplateLink>
      <ProjectTemplateLink ProjectName="Dog">
        DogProject\Dog.vstemplate
      </ProjectTemplateLink>
      <ProjectTemplateLink ProjectName="Lion">
        LionProject\Lion.vstemplate
      </ProjectTemplateLink>
</ProjectCollection>
```

FYI I tried to update the parent vsTemplate file on the fly by removing the unwanted ProjectTemplateLink element but every-time the execution uses the zipped vsTemplate in the project directory and not the updated vsTemplate file? Is there any other way to do this?

**Comment by WilliamAntonRohm** [comment]
@dk511 -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by dk511** [comment]
I have a requirement to generate a custom projects template. I am showing the wizard (using vsix project) to the user which has three check boxes  in which user can select one or many of them, based on the selection the number of projects need to be created.

Suppose user choose one, then output solution must have one project.
Suppose user choose any two, then output solution must have those two projects.

At Present irrespective of selection three output projects are created. The root vsTemplate file looks like below, Is there a way achieve my requirement? 

```
<ProjectCollection>
      <ProjectTemplateLink ProjectName="Cat">
        CatProject\Cat.vstemplate
      </ProjectTemplateLink>
      <ProjectTemplateLink ProjectName="Dog">
        DogProject\Dog.vstemplate
      </ProjectTemplateLink>
      <ProjectTemplateLink ProjectName="Lion">
        LionProject\Lion.vstemplate
      </ProjectTemplateLink>
</ProjectCollection>
```

I tried two ways of doing it
1)At run time changing the root vsTemplate file accordingly , but always output project is created based on the vsTemplate file which is already in zip folder in bin directory.
2)using Development tool environment automation object , adding or removing projects programatically in ProjectItemFinished method of IWizard interface ,Example:
  Dte.Solution.AddFromTemplate( vsTemplatePath, NewProjectName) 
The above line creates a new project but folder structure is missed, and it is difficult to tweak it.

Is there any easy way to do like this?

<ProjectCollection>
      if(cat is selected)
      <ProjectTemplateLink ProjectName="Cat">
        CatProject\Cat.vstemplate
       </ProjectTemplateLink>
        end if
      if(Dog is selected)
      <ProjectTemplateLink ProjectName="Dog">
        DogProject\Dog.vstemplate
      </ProjectTemplateLink>
      end if
      if(Lion is selected)
      <ProjectTemplateLink ProjectName="Lion">
        LionProject\Lion.vstemplate
      </ProjectTemplateLink>
      end if
</ProjectCollection>

**Comment by WilliamAntonRohm** [comment]
@dk511 -- thank you for clarifying.  Are you reading a specific docs.microsoft.com article?

**Comment by WilliamAntonRohm** [comment]
Here are a few options where you might consider asking your questions:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
