### ISSUE TITLE
Copy task 'Copied files' description should be changed from 'Succesfully copied' to 'All files'

### ISSUE THREAD

**Issue by sommmen** [MicrosoftDocs/visualstudio-docs#4813]
Hiya,

The copy task description is wrong. It is not 'Succesfully copied' as the document states, but it lists all files that the copy task receives (which is a good thing). This is quite deceiving and if i hadn't 'stupidly' just tried what the output did i did never find this out.

There's a post dating as far back as 9 years;

https://stackoverflow.com/questions/5945230/the-output-parameter-copiedfiles-of-copy-task-is-returning-all-the-files-speci

I ran multiple iterations of this;

```
    <Copy SourceFiles="%(SrcFiles.FullPath)"
          DestinationFolder="$(OutputPath)%(SrcFiles.RecursiveDir)"
          SkipUnchangedFiles="true">
      <Output
        TaskParameter="CopiedFiles"
        ItemName="CopiedSrcFiles" />
    </Copy>
```

And each time `CopiedSrcFiles` contained all destination files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 160a060d-7dc1-5826-8beb-f47097d0928f
* Version Independent ID: cc8a11cf-df37-97e9-bd0a-8c8ddd5037c7
* Content: [Copy Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2019&redirectedfrom=MSDN)
* Content Source: [docs/msbuild/copy-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/copy-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@sommmen Thanks, I am looking at this now.

**Comment by ghogen** [comment]
This shoudl be fixed at the next publish cycle later today - https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6136

**Comment by sommmen** [comment]
> This shoudl be fixed at the next publish cycle later today - [MicrosoftDocs/visualstudio-docs-pr#6136](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6136)

Thanks for your efforts!

For good measure; the link you send here is broken - but i see the change on the docs.
