### ISSUE TITLE
Why specific exception like TimeoutException still triggers CA1031? What should be done to fix it?

### ISSUE THREAD

**Issue by Thieum** [MicrosoftDocs/visualstudio-docs#4814]
This description is really broad:

> A general exception such as System.Exception or System.SystemException is caught in a catch statement, or a general catch clause such as catch() is used.

Exceptions like `TimeoutException` even if more specific will still trigger CA1031. Is it really intended? Should TimeoutException be derived to a more specific exception? 

It may be helpful to have a complete list of exceptions that can trigger CA1031, and gives a hint for each, of what should be done.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89b0f64-db03-af39-fdf7-ccb31c9ae01b
* Version Independent ID: 95c4aac2-4e98-240b-54e5-64981ab68cec
* Content: [CA1031: Do not catch general exception types - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1031?view=vs-2019)
* Content Source: [docs/code-quality/ca1031.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1031.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Thieum Are there other non-general exceptions you've seen that trigger CA1031? @mavasani Is this a product issue? Seems like TimeoutException should not generate CA1031.

**Comment by Thieum** [comment]
@Mikejo5000 from one of my active project here are a few:
- SocketException
- IOException
- InvalidCastException

It might be an analyzer issue as you suggest - I'm using FXCopAnalyzers 2.9.8 in .Net Core and .Net Framework projects.

![image](https://user-images.githubusercontent.com/944894/74967805-b8ba7680-53e7-11ea-8f52-e555eaf0c207.png)

**Comment by KalleOlaviNiemitalo** [comment]
It seems the default list of too general exception types is only `Object`, `Exception`, and `SystemException`, but you can add more exception types by defining `disallowed_symbol_names` in an `.editorconfig` file.

**Comment by mavasani** [comment]
@KalleOlaviNiemitalo is correct. CA1031 is only meant to flag catch all handlers for Exception and SystemException by default. If you have not configured additional disallowed exception types for CA1031 as per https://github.com/dotnet/roslyn-analyzers/blob/master/docs/Analyzer%20Configuration.md#disallowed-symbol-names, then those additional exceptions should not fire.

@Thieum One other thing to verify is that you don't have an install of Microsoft CodeAnalysis 2017 or 2019 VSIX extension. That extension has older bits and had a bug where it reported CA1031 on other exception types. If you have just the 2.9.8 NuGet package for FxCopAnalyzers, you should not be hitting this issue.

**Comment by Thieum** [comment]
@mavasani disabling Microsoft Code Analysis 2019 did fix my issue, thanks a lot! Maybe the extension should be deprecated or updated? Let me know if I should open an issue elsewhere regarding that.

**Comment by mavasani** [comment]
@Thieum Yes, please file an issue on roslyn-analyzers repo. We are planning to deprecate it soon, but it would good to have a tracking issue for that work.

**Comment by Thieum** [comment]
@Mikejo5000 I will close this issue, as it seems it was more a tool issue than a doc issue. I'm not sure there's a more specific way to tell what can trigger this warning by default. Thanks for your help!
