### ISSUE TITLE
When is the task assembly loaded? 

### ISSUE THREAD

**Issue by pekkah** [MicrosoftDocs/visualstudio-docs#4816]
Is the task loaded from assembly when UsingTask is evaluated or when the task is used for the first time? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b3f5bf-9736-884e-9d08-e9422b4891a5
* Version Independent ID: fa34a483-01a9-8062-ac26-a0c8de0821b5
* Content: [UsingTask Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/usingtask-element-msbuild?view=vs-2019#feedback)
* Content Source: [docs/msbuild/usingtask-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/usingtask-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
It's loaded the first time it's required.
