### ISSUE TITLE
I'm still getting error following the instruction.

### ISSUE THREAD

**Issue by dm630w** [MicrosoftDocs/visualstudio-docs#4818]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'CreateWebHostBuilder' does not exist in the current context	WebApplication1	C:\Users\simplyme\source\repos\WebApplication1\WebApplication1\Program.cs	17	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'AppDbContext' could not be found (are you missing a using directive or an assembly reference?)	WebApplication1	C:\Users\simplyme\source\repos\WebApplication1\WebApplication1\Program.cs	25	Active

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace WebApplication1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = CreateWebHostBuilder(args).Build();

            using (var scope = host.Services.CreateScope())
            {
                var services = scope.ServiceProvider;

                try
                {
                    var context = services.GetRequiredService&lt;AppDbContext&gt;();
                    context.Database.EnsureCreated();
                    
                }
                catch (Exception ex)
                {
                    var logger = services.GetRequiredService&lt;ILogger&lt;Program&gt;&gt;();
                    logger.LogError(ex, "An error occurred creating the DB.");
                }
            }

            host.Run();
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f156aaa-839a-b9bb-5912-b3a537dfdb36
* Version Independent ID: 51888076-400e-0a51-8ae4-6fe745829436
* Content: [Step 3: Working with Data in Your ASP.NET Core App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-03?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-aspnet-core-ef-step-03.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ardalis
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@dm630w Sorry to hear that you are experiencing the same problem that was described in a previous GitHub issue, https://github.com/MicrosoftDocs/visualstudio-docs/issues/3556. In response to that earlier issue, we added the following note to the page, which says the following:

![image](https://user-images.githubusercontent.com/23244653/74993581-40ac7a80-5400-11ea-93b9-c0d94cd4a376.png)


Please let us know if this (or any other solution listed in the previous GitHub issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/3556) resolves the problem for you.

**Comment by TerryGLee** [comment]
@dm630w We haven't heard back but we've added a possible workaround to this issue (which has already been added to the [Step 3: Work with data using Entity Framework](https://docs.microsoft.com/visualstudio/get-started/csharp/tutorial-aspnet-core-ef-step-03) page, also). We're closing this issue now, but if the workaround doesn't help, let us know and we can consider reopening this issue for you.

**Comment by grumfellow** [comment]
I had to add 
using WebApplication1.Data; 
instead of
WebApplication1.Models;
