### ISSUE TITLE
Error in second last sample

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/visualstudio-docs#4819]
@VmpKalin commented on [Wed Feb 19 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/74)

This sample shouldn't have GetHashCode() override, should it?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 0cae86a4-dac8-2fcc-9e9e-d999b2bff138
* Version Independent ID: 658ee2ea-c979-ed5e-dc0e-30fe44f81eea
* Content: [CA2218: переопределяйте GetHashCode при переопределении Equals - Visual Studio](https://docs.microsoft.com/ru-ru/visualstudio/code-quality/ca2218?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca2218.md](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/blob/live/docs/code-quality/ca2218.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

---

@srvbpigh commented on [Wed Feb 19 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/74#issuecomment-588169416)

Hello, @VmpKalin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check the question from user?

Kind regards,
Microsoft DOCS International Team

**Comment by Mikejo5000** [comment]
@VmpKalin The second set of code in both example sections (Class example, Structure example) shows the fix, which requires the GetHashCode() override, so this looks OK to me. Let me know if I am missing something.
