### ISSUE TITLE
VS Support more languages than listed.

### ISSUE THREAD

**Issue by yuehuang010** [MicrosoftDocs/visualstudio-docs#4822]
VS supports more languages in addition those already listed.  They are:
Russian - 1049
Turkish - 1055
Portuguese (Brazil) - 1046
Polish - 1045
Czech - 1029

Source : https://www.microsoft.com/en-us/download/details.aspx?id=48157

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0c8040-b34d-4930-c5f2-7a3d74d01b27
* Version Independent ID: b90c390e-87e5-b668-600b-65bcd8e7949e
* Content: [-LCID (devenv.exe) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/lcid-devenv-exe?view=vs-2019)
* Content Source: [docs/ide/reference/lcid-devenv-exe.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/lcid-devenv-exe.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- please review the above-mentioned PR 6153.
