### ISSUE TITLE
XmlPeek could use an example

### ISSUE THREAD

**Issue by sommmen** [MicrosoftDocs/visualstudio-docs#4823]
XmlPoke has an example, XmlPeek does not.

I personally would like to read some config values from an xml file and i hope XmlPeek can help me with this. 
This stackoverflow seems to contain an appropriate sample; https://stackoverflow.com/questions/17558728/how-can-i-read-a-value-from-appsettings-config-in-csproj-conditional

If i have the time I may include a sample after i have tested one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4474bd-b6d2-241c-244a-695579a1e7af
* Version Independent ID: 458e32a8-93b3-5da1-b7e1-4718721be9dc
* Content: [XmlPeek Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/xmlpeek-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/xmlpeek-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/xmlpeek-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@sommen Thanks, adding an example.
