### ISSUE TITLE
AfterPublish ignored on .NET Core

### ISSUE THREAD

**Issue by JesperTreetop** [MicrosoftDocs/visualstudio-docs#4825]
Targets attached to the AfterPublish target do not seem to execute in .NET Core. There are [other issues](https://github.com/dotnet/sdk/issues/8976) hinting that other targets are affected too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 868d865b-89d9-ec87-d569-862d168dc6ca
* Version Independent ID: a95f34e2-8f4b-4a4b-cb7e-075e4ceebd69
* Content: [Extend the build process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2019#feedback)
* Content Source: [docs/msbuild/how-to-extend-the-visual-studio-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-extend-the-visual-studio-build-process.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@JesperTreetop -- Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by JesperTreetop** [comment]
Yes, sorry, it seems I was unclear. There already is an issue about the product - I created an issue here because I wanted the documentation to say what we're supposed to do instead. There will be .NET Core versions in support for years where I assume this won't be fixed (because it would be a breaking change in behavior from one bug fix release to the next), so it would be nice if it could be *documented* what we're to do instead on those versions.
