### ISSUE TITLE
When a Breakpoint is reached and we are typing game input the class gets the text.

### ISSUE THREAD

**Issue by JayFiraja** [MicrosoftDocs/visualstudio-docs#4828]
While debugging and a breakpoint is reached, Visual Studio window is focused
and for example in the most common scenario when the WASD keys are being used
the class will end up with this new "dddddddddddddddd" or "sssssssssssssssssss".

Is there a way to block keyboard input when a breakpoint is reached or this needs fixing?

Thanks in advance.
Jay

**Comment by WilliamAntonRohm** [comment]
@JayFiraja -- John, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by JayFiraja** [comment]
Never mind I found the options in Tools/Options/Debugging, [ ] Enable Edit and Continue 
apparently, the feature is called Edit and Continue, but for us Unity Game devs we can't use that. yet.
It was an issue because in games there is constant input from the keyboard while testing an app/game so the breakpoint ended up making changes in the class.

**Comment by WilliamAntonRohm** [comment]
@JayFiraja -- John, thank you for locating that information.  Best wishes for a successful game.
