### ISSUE TITLE
Show how to suppress Code Analysis for Managed Code Warnings

### ISSUE THREAD

**Issue by calvinhsia** [MicrosoftDocs/visualstudio-docs#483]
Please show how to suppress these warnings quickly: migrating a project suddenly yields thousands of errors and I'm initially unproductive because of these errors

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b84d427d-0ae4-f380-c544-041141e6c541
* Version Independent ID: a4601b4b-bbda-3502-4bbc-e66367781bce
* [Content](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-warnings#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/code-quality/code-analysis-for-managed-code-warnings.md)
* Service: unspecified

**Comment by gewarren** [comment]
Note added to https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-managed-code-overview#suppress-warnings.

**Comment by gewarren** [comment]
On further thought, disabling code analysis on build will not get rid of the warnings/errors if they are coming from Roslyn analyzers. You can select **Analyze > Run Code Analysis and Suppress Active Issues** to "baseline" the analysis state of the solution (or project). Sorry for the confusion.
