### ISSUE TITLE
Sample manifest: DisplayName tag doesn't end with correct xml tag.

### ISSUE THREAD

**Issue by yuehuang010** [MicrosoftDocs/visualstudio-docs#4831]
&lt;DisplayName&gt;Arbol de Familia&lt;/LocalizedName&gt;
                                                         ^

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414022bc-4a6c-3164-7c78-447c636ff8da
* Version Independent ID: e74d4a8e-8ef5-8d01-2ecb-f7563ede07ca
* Content: [VSIX Language Pack Schema 2.0 Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-language-pack-schema-2-0-reference?view=vs-2019)
* Content Source: [docs/extensibility/vsix-language-pack-schema-2-0-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/vsix-language-pack-schema-2-0-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @ZoeyR
* Microsoft Alias: **zorio**

**Comment by WilliamAntonRohm** [comment]
@ZoeyR -- please review the above-mentioned PR 6154.
