### ISSUE TITLE
CAST tool license is not showing in my VS Enterprise subscriptions benefit

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/visualstudio-docs#4832]
Is the license for CAST Migration tool available to anyone with VS Enterprise subscriptions ? Because I do not see it in the benefit sections of my VS Enterprise subscriptions ( I am MS FTE).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133670f1-3322-ee31-5e80-9f00a16ad8ab
* Version Independent ID: 050f5adf-5842-b1cf-540e-6522823b788a
* Content: [CAST Highlight Benefit in to Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-cast)
* Content Source: [subscriptions/vs-cast.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-cast.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@Anand-Moghe Thanks for the question.  The CAST Highlight benefit is not available to Enterprise subscriptions acquired through NFR channels, which include the FTE subscription.

**Comment by Anand-Moghe** [comment]
@evanwindom Thanks for the info. I just figured it out by reading this on the page.
