### ISSUE TITLE
Recommendation against MSBuild wildcards out of date

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#4833]
> However, we do not recommend the use of wildcard characters because it makes debugging and selective targeting more difficult if source files are added or deleted.

This recommendation against wildcards seems to be out of date. As described in [Default compilation includes – .NET Core project SDKs](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#default-compilation-includes), .NET SDK projects now select items with wildcards by default.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bc6800-41dc-a7a4-5942-0f103a290cf9
* Version Independent ID: 56b974f2-30d2-ae79-2b78-7eb073ec7cd1
* Content: [Walkthrough: Creating an MSBuild Project File from Scratch - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch?view=vs-2019#feedback)
* Content Source: [docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@rainersigwald what do we want to recommend here?

**Comment by ghogen** [comment]
Wildcards are OK in SDK-style projects, not in other projects.

**Comment by KalleOlaviNiemitalo** [comment]
Is that because of [globbing support in the new project system](https://github.com/dotnet/project-system/blob/06807fa9a8b9aec94390ecd6a0c1a79931945daf/docs/feature-comparison.md)? I don't see what that has to do with "debugging and selective targeting", which the current documentation gives as reasons.

**Comment by rainersigwald** [comment]
@KalleOlaviNiemitalo Correct. I wouldn't object to updating the reason to something like "Visual Studio and other tooling can corrupt wildcards when editing project files in some circumstances."
