### ISSUE TITLE
 I have a problem with an example, please contact me.

### ISSUE THREAD

**Issue by ticianaciminari** [MicrosoftDocs/visualstudio-docs#4836]
@psh9508 commented 17 hours ago — with docs.microsoft.com
Hello. In the examples on this page

The code below demonstrates IntelliSense's autocomplete

Please check the following problem.

int a = 42;
int b = 119;
int c = a + b; // this part is missing
Console.WriteLine (c);
Console.ReadKey ();

That is all.
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by ticianaciminari** [comment]
Hi Team,

Could you please check this issue from user?

Kind regards,
Microsoft DOCS International Team

**Comment by TerryGLee** [comment]
@psh9508 Please note that the animation isn't meant to duplicate the code exactly; instead, it's meant only to show the autocomplete feature. We recently added a note to explain this, as follows:

![image](https://user-images.githubusercontent.com/23244653/74996850-90437400-5409-11ea-9f59-30315cd4829c.png)

(We only recently added this note, so it probably hasn't been localized into Korean yet.)

Thanks for your feedback, though!
