### ISSUE TITLE
All npm commands fail

### ISSUE THREAD

**Issue by martinduo** [MicrosoftDocs/visualstudio-docs#4839]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by martinduo** [comment]
The npm commands all fail because file or directory is not found at this location: "...NodejsWebAppBlank\node_modules\scheduler".
There is no 'node_modules' directory, only npm, package.json, README.md, and server.js

After the first step to install react via the UI:

====Executing command 'npm install react --save '====
npm WARN nodejs-web-app-blank@0.0.0 No repository field.
npm WARN nodejs-web-app-blank@0.0.0 No license field.
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path C:\Users\Bruce\Dropbox\Code\NodejsWebAppBlank\node_modules\scheduler
npm ERR! dest C:\Users\Bruce\Dropbox\Code\NodejsWebAppBlank\node_modules\.scheduler.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Bruce\Dropbox\Code\NodejsWebAppBlank\node_modules\scheduler' -> 'C:\Users\Bruce\Dropbox\Code\NodejsWebAppBlank\node_modules\.scheduler.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bruce\AppData\Roaming\npm-cache\_logs\2020-02-22T20_39_57_547Z-debug.log

====npm command completed with exit code -4058====

**Comment by Mikejo5000** [comment]
@martinduo What version of Visual Studio are you using and what version of Node did you install? I can take a look at this.

**Comment by martinduo** [comment]
VS2019 Version 16.4.5
node v12.14.1

**Comment by Mikejo5000** [comment]
@martinduo Looks like the node_modules folder should get created when you try to install your first npm package. I can't repro the issue (Node v12.16.1) when I install the react npm package, so it seems that there may be something out of whack in the Node environment setup. If you right-click the project node in Solution Explorer (right pane) and select "Open command prompt here", then type "node --version", the result is v12.14.1?

If Node appears OK, did you install the Node.js VS workload mentioned in the prerequisities? I am assuming yes, or you wouldn't see the correct template. For this tutorial, the template needs to be "Blank Node.js Web Application" for JavaScript (not the TypeScript template).

@armanio123 Armando, do you know a reason why the node_modules folder might not get created?

**Comment by Mikejo5000** [comment]
@martinduo Not at all sure about this, but you might check whether you are seeing an incompatibility with Dropbox if you create the project in a non-Dropbox folder, then install the npm package...

**Comment by Mikejo5000** [comment]
Also, To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by martinduo** [comment]
"If you right-click the project node in Solution Explorer (right pane) and
select "Open command prompt here", then type "node --version", the result
is v12.14.1?"
YES

I made another project using the console  template, and still have a npm
problem.  Right clicking npm and selecting Install npm Packages does
nothing. Right clicking and selecting Install New npm Packagesgives me a
dialog to search and select a package. I found an interesting one:
"camelcase-keys" and clicked Install Package. The progress bar worked and I
closed it. No node_modules created. Now the npm directory has an entry:
camelcase@5.3.1 (not listed in package,json). Shouldn't that have been
created by the Install Package operation? Anyway, don't spend any more time
on this problem, it's not important for what I'm using VS2019 for at the
moment. And as soon as my one task that requires ReSharper is finished, I'm
back to using VSCode again. As an 87 year old retiree I've lost my capacity
for handling Visual Studio plumbing problems.

I have many JavaScript projects using npm all created under a Dropbox
directory without problems. I hate to think VS2019 would have problems
there. My prior Visual Studio work was using VB.net and worked for years
under Dropbox with no problem.

Thanks for responding and helping.

**Comment by Mikejo5000** [comment]
Looks like a product issue and no repro for me when I retest. Per earlier comments, we would need a product bug reported (Report a Problem tool) for this to move farther along.

**Comment by bazzofx** [comment]
The solution is the following for Windows system
Go to the C:\Program Files\nodejs ( or the location where you install the NodeJS)
Right Click on the folder "node_modules"
Change the security settings to your account to modify/read & execute/read files/ everything/
Also click on Advance, and make your account the Owner of the folder.
Thats it, once you do that you will be able to run the commands and it will be working as expected.

Altenativelly you can run the following command
icacls "C:\Program Files\nodejs\node_modules" /grant Administrators:F /T
