### ISSUE TITLE
No documentation for many CustomListItems intrinsic functions

### ISSUE THREAD

**Issue by KindDragon** [MicrosoftDocs/visualstudio-docs#4841]
Some of them described [here](https://docs.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger?view=vs-2019#BKMK_Using_debugger_intrinisic_functions_to_maintain_state). We should add link to page.
But many functions missing
At-least you should add description for `__findNonNull` and `TreeTraverse_*`, which seem useful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2019#feedback)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@KindDragon I can add a link to that page. Have you used __findNonNull and TreeTraverse_* in the debugger and they work as expected?

**Comment by KindDragon** [comment]
I've only seen Microsoft use _findNonNull in their natvis files. I think it might be useful. 
I don't know how TreeTraverse* works.

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by jbigalet** [comment]
Which doc was updated?
I still can't find any description of __findNonNull in the provided link [here](https://docs.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger?view=vs-2019#BKMK_Using_debugger_intrinisic_functions_to_maintain_state)

**Comment by KindDragon** [comment]
Nobody knows what this function does :)

**Comment by KindDragon** [comment]
Hi, @StephanTLavavej and @CaseyCarter. Sorry for mentioning you, but maybe you know someone who knows about a debugger intrinsic  `_findNonNull` and `TreeTraverse*` and can add a description to them?

**Comment by WilliamAntonRohm** [comment]
@All -- the updated articles are:
- [Create custom views of C++ objects in the debugger using the Natvis framework](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects)
- [Expressions in the Visual Studio debugger](https://docs.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger)

You are welcome to @ mention me for any followup.

cc @Mikejo5000 for awareness

**Comment by KindDragon** [comment]
@WilliamAntonRohm I can't find description/arguments for TreeTraverse_Init, TreeTraverse_Next, TreeTraverse_Skip and __findNonNull in this page https://docs.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger?view=vs-2019#BKMK_Using_debugger_intrinisic_functions_to_maintain_state

**Comment by WilliamAntonRohm** [comment]
@KindDragon -- Arkady, thank you for your followup.  We are looking into this issue.

**Comment by Mikejo5000** [comment]
Updating doc with better descriptions. Doc should be live by EOD.

**Comment by tim-weis** [comment]
The `TreeTraverse_*` intrinsics still lack sufficient documentation. Given what we have, there's no way for us to use those intrinsics. Could you please re-open this issue, @v-albemi?

**Comment by WilliamAntonRohm** [comment]
@tim-weis -- Tim, thank you for your follow-up.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@tim-weis There's a link to this article, which has information for the TreeTraverse functions.
https://learn.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger?view=vs-2019#BKMK_Using_debugger_intrinisic_functions_to_maintain_state
What information is missing from the description?

**Comment by Mikejo5000** [comment]
@tim-weis Thanks, I will ask about this.

**Comment by tim-weis** [comment]
I'm failing to comprehend. What is an *"extension-based visualizer"*?

**Comment by Mikejo5000** [comment]
@tim-weis I assume that refers to VS extensions like this: https://marketplace.visualstudio.com/items?itemName=CppWinRTTeam.cppwinrt101804264
