### ISSUE TITLE
The name of the XML element is Task, not TaskBody

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#4844]
This topic shows the XML element name `TaskBody` several times. However, the child element of `UsingTask` is actually named `Task`, not `TaskBody`. The MSBuild object model calls it `Microsoft.Build.Construction.ProjectUsingTaskBodyElement` though; perhaps the error came from that.

Related to this, [the "Child elements" list in "UsingTask element (MSBuild)"](https://docs.microsoft.com/en-us/visualstudio/msbuild/usingtask-element-msbuild?view=vs-2019#child-elements) mentions "Task" and links to [Task element (MSBuild)](https://docs.microsoft.com/en-us/visualstudio/msbuild/task-element-msbuild?view=vs-2019). The "Task" name there is correct but the link should point to [TaskBody element (MSBuild)](https://docs.microsoft.com/en-us/visualstudio/msbuild/taskbody-element-msbuild?view=vs-2019).

Perhaps it would be clearest to rename the topics like this:
- rename "TaskBody element" to "Task element in UsingTask"
- rename "Task element" to "Task element in Target"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8437fd21-e76f-93c6-5aa4-72027ac16278
* Version Independent ID: f7d3ffa3-9309-57fd-74eb-1e63a6ae8d7e
* Content: [TaskBody Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/taskbody-element-msbuild?view=vs-2019#feedback)
* Content Source: [docs/msbuild/taskbody-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/taskbody-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for your feedback.

@ghogen -- please look into this issue.

**Comment by KalleOlaviNiemitalo** [comment]
This part was not fixed yet:

> Related to this, [the "Child elements" list in "UsingTask element (MSBuild)"](https://docs.microsoft.com/en-us/visualstudio/msbuild/usingtask-element-msbuild?view=vs-2019#child-elements) mentions "Task" and links to [Task element (MSBuild)](https://docs.microsoft.com/en-us/visualstudio/msbuild/task-element-msbuild?view=vs-2019). The "Task" name there is correct but the link should point to [TaskBody element (MSBuild)](https://docs.microsoft.com/en-us/visualstudio/msbuild/taskbody-element-msbuild?view=vs-2019).
