### ISSUE TITLE
Document that parameters need not be defined in ParameterGroup if @Type="Class"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#4845]
> If the `Code` element has the `Type` attribute of `Fragment` or `Method`, then properties are automatically created for every parameter. Otherwise, properties must be explicitly declared in the task source code, and must exactly match their parameter definitions.

Actually, if `Type` is `Class` and the source code declares properties for the parameters, then the entire `ParameterGroup` element can be omitted, and RoslynCodeTaskFactory recognizes the properties and generates the corresponding parameters for the task. This is a deliberate feature: <https://github.com/microsoft/msbuild/blob/e481bbf88fd4a406cc8a98c2f46e9bda8e76be69/src/Tasks/RoslynCodeTaskFactory/RoslynCodeTaskFactory.cs#L168-L179>

The older CodeTaskFactory does not support this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8c66d6-dd9b-dddc-dd69-41d22284ec10
* Version Independent ID: 1b750d67-95da-aa4c-ad32-2de54d7a46c5
* Content: [MSBuild Inline Tasks with RoslynCodeTaskFactory - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-roslyncodetaskfactory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-roslyncodetaskfactory.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
If you specify a whole class, you don't have to specify the ParameterGroup.  But, if you specify the ParameterGroup, it must match what is defined in the class.

**Comment by KalleOlaviNiemitalo** [comment]
If you specify a whole class in CodeTaskFactory, you still have to specify the ParameterGroup. This difference between the task factories seems something that should be mentioned in the RoslynCodeTaskFactory topic.
