### ISSUE TITLE
RPC debugging feature was removed in VS2012

### ISSUE THREAD

**Issue by LongJohnCoder** [MicrosoftDocs/visualstudio-docs#4846]
This option does not exist in Tools-&gt;Options-&gt;Debugging. The RPC/Ole debugging feature itself was removed a long time ago in VS 2012 [1]. This page should be removed from VS2012+ docs because it is an ongoing source of confusion. [2]

[1] https://stackoverflow.com/questions/16785726/rpc-debugging-in-vs-2012
[2] https://social.msdn.microsoft.com/Forums/vstudio/en-US/a960cd38-a32e-4b42-8c3d-36a4a3b6e7ea/how-do-i-enable-rpc-debugging-on-visual-studio-2015-update-3?forum=vsdebug

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e146b3fd-9877-7535-8667-c9d715aa8ab0
* Version Independent ID: c7eef86c-3e80-9ab9-1352-fb7074836d00
* Content: [Debug COM clients and servers using RPC debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-com-clients-and-servers-using-rpc-debugging?view=vs-2019#feedback)
* Content Source: [docs/debugger/how-to-debug-com-clients-and-servers-using-rpc-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-com-clients-and-servers-using-rpc-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@LongJohnCoder Thanks! I'll get that removed.
