### ISSUE TITLE
No tools listed in menu bar

### ISSUE THREAD

**Issue by Witenite** [MicrosoftDocs/visualstudio-docs#4852]
I've been using VS Code for some time now, and would like to change the font. Unfortunately, unless I am looking at the wrong product here, (this does say Visual Studio though) I don't have any menu item named "Tools". Instead all I have is File -&gt; Preferences, but again, I don't really see where to change fonts in there, only the font family (whatever that means) which lists multiple fonts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2913896-b0f2-5f3c-d733-09fe5c4e86b1
* Version Independent ID: c997c373-c946-0f02-d4c2-0904e6aab42e
* Content: [Change fonts and colors - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gregvanl** [comment]
Hi @Witenite You want to have a look at the VS Code documentation at https://code.visualstudio.com. 

You might like to read the Tips and Tricks topic, which has a section of customizing the editor including the font size and family.
https://code.visualstudio.com/docs/getstarted/tips-and-tricks#_customization

To change the Font Family setting in VS Code, you can use the Settings editor (File > Preferences > Settings) and search for 'font'.

![image](https://user-images.githubusercontent.com/12818376/75368693-f51e2480-5876-11ea-8e6a-0b0b0082f5bd.png)

Closing this issue in visualstudio-docs, but if you have other questions or suggestions, you can open an issue on the VS Code documentation repo at https://github.com/microsoft/vscode-docs/issues

**Comment by Witenite** [comment]
Hi Greg,

thanks for the reply. I had already found the "Font family" window in VS
Code prior to contacting you. Confusion set in though, when Microsoft's
support page mentioned that you must go to Tools -> Options, and this menu
option does not exist! Furthermore, although I have found the Font family
option, how do I go about adding (or removing) a font from there. IE I
could type it in (comma separated) but is that enough? What Font name do I
use (does it have to be as per the "file name" of the font, or the font
name as specified by the font producer? I realize these might be stupid
questions, but with such an unconstrained input format I can see half a
dozen ways this may well not work. How do I eve know the font is recognized
or known to VS Code, if I just type it in manually, as opposed to selecting
it from a drop down list for example? And with multiple fonts listed in the
Font family, how do I select which specific font is to be used for my
document?

Regards,
Graham

**Comment by Witenite** [comment]
Hi again Greg,

I thought I should mention too, for the sake of clarity, that the font I am
trying to add is found here:
https://github.com/tonsky/FiraCode

Thanks again.
Graham

**Comment by gregvanl** [comment]
Hi Graham,

The Font Family list is comma delimited, using the font name which you can get from the platforms font settings (Settings > Fonts on Windows, Font book on macOS). If the font name contains a space, you should surround the name with single quotes, for example 'Courier New'. The order of the list defines the priority, with the later entries being fall backs.

For Fira Code, you can use:

![image](https://user-images.githubusercontent.com/12818376/75574878-ede04d80-5a13-11ea-942c-462d73d3a10d.png)

If you know you have Fira Code installed and don't need fallbacks, you can just list:

![image](https://user-images.githubusercontent.com/12818376/75574836-da34e700-5a13-11ea-90e5-301572b6c679.png)

**Comment by Witenite** [comment]
Thanks Greg, I will give that a try later next week.

Regards,
Graham
