### ISSUE TITLE
Excel is listed twice

### ISSUE THREAD

**Issue by tytech3** [MicrosoftDocs/visualstudio-docs#4855]
Under the "Comparison of UI Features" heading in section "Custom task panes", excel is listed twice in column "Supported Microsoft Office applications"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfb1800b-6c0b-43ae-95bb-ea6d66729970
* Version Independent ID: 63a85e3d-006a-9b4c-cf50-90d70ed22bc0
* Content: [Office UI customization - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/office-ui-customization?view=vs-2019)
* Content Source: [docs/vsto/office-ui-customization.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/office-ui-customization.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@tytech3  - thanks!

**Comment by John-Hart** [comment]
This should be fixed shortly
