### ISSUE TITLE
Unclear which version of NodeJS runtime to install

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/visualstudio-docs#4856]
The documentation says to go install the runtime for NodeJS but this unclear. Firstly there are different installers for x86 and x64. Which does VS need? In the NodeJS installer it wants to add NodeJS to the system path but if you add both x86/x64 then that will cause problems potentially. Additionally VS seems to have its own version of NodeJS as well and it is unclear when this version is used instead. For example I can go to a Powershell prompt and node -v and I'll get the path that I installed the runtime too. However within VS when doing builds it seems to be using a different version because (as mentioned in Developer Community) it is not always using the global instance. You have to muck with the system path to get it to work. How about some clear steps on how to get NodeJS working with VS both during a build and from the Dev Command Prompt?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed2bc34b-ee38-4dab-308c-a6c45c36200a
* Version Independent ID: e2b3ef7f-3106-674d-a995-c7b14cf53cc9
* Content: [Quickstart: Use Visual Studio to create your first Node.js app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-nodejs?view=vs-2019#feedback)
* Content Source: [docs/ide/quickstart-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@CoolDadTx If you select the project node in Solution Explorer, you should be able to see the path to Node.exe in the lower Properties pane. This is the version that gets used. You can manually set the path by right-clicking the project and choosing Properties. If you don't set the system path in the Node.js installer, it makes sense that you would have to do something about that; manually setting the path in the properties would be my first choice. I will see if I can clarify a few of these things. I expect x86 vs. x64 will depend on your host machine, but I'd need to look into that.

**Comment by Mikejo5000** [comment]
Updating the docs referencing the Node.js tools with the following:

If you don't have it installed, we recommend you install the LTS version from the [Node.js](https://nodejs.org/en/download/) website for best compatibility with outside frameworks and libraries. Node.js is built for 32-bit and 64-bit architectures. The Node.js tools in Visual Studio, included in the Node.js workload, support both versions. Only one is required and the Node.js installer only supports one being installed at a time.
    
In general, Visual Studio automatically detects the installed Node.js runtime. If it does not detect an installed runtime, you can configure your project to reference the installed runtime in the properties page (after you create a project, right-click the project node, choose **Properties**, and set the **Node.exe path**). You can use a global installation of Node.js or you can specify the path to a local interpreter in each of your Node.js projects.

**Comment by CoolDadTx** [comment]
@Mikejo5000 The text seems reasonable. However I don't see that the path to node is shown anywhere in Solution Explorer. To be clear this is an ASP.NET app. If I right click the project and select properties then I'm going to the project properties tab which doesn't show any options around node. If I bring up the Properties window instead then I just see the core set of properties that web apps have like the SSL enabled and Windows auth settings. Is this only applicable to ASP.NET Core apps?

**Comment by Mikejo5000** [comment]
@CoolDadTx I believe it's either/or as far as your runtime, either the CLR (for ASP.NET / Core) or the Node.js runtime. Depending on your VS workload installed, you would normally either start from an ASP.NET / Core project template or a Node.js template (as described in this article), which would determine the runtime. If your ASP.NET scenario requires npm packages, you can add an npm configuration file as a new project item. For some details, see this doc:
https://www.typescriptlang.org/docs/handbook/asp-net-core.html
What is your scenario for adding Node.js to an ASP.NET project?

**Comment by CoolDadTx** [comment]
The web apps rely on npm for finding JS packages. npm requires nodejs so our build needs it. 

We ran into issues with recent releases of nodejs shipping versions of npm that are not current. This issue was discussed over on nodejs's site. The net takeaway was that if you needed to use a newer version of npm then you had to ensure it appeared earlier in the path. This led to the recommendation of installing npm globally and ensuring your user-profile cached version is before nodejs's path. This got us past our original issue but caused subsequent issues. This ultimately led me to uninstalling nodejs from the machine, uninstalling the workload from all versions of VS and then reinstalling to get to the point where I could run VS and command line builds using the same npm/nodejs version.
