### ISSUE TITLE
what kind of a retarded  "suggestion" is this

### ISSUE THREAD

**Issue by d4e666** [MicrosoftDocs/visualstudio-docs#4862]
apparently the one the at created this "suggestion" has neber heard of the "LIBRARY" part inside "class library project". THE GOAL IS TO ALLOW OUTSIDE USERS TO ACESS THE CODE!!!!!!!!!

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: f4f6b569-4d16-9e25-0911-4dba75770bf4
* Version Independent ID: 92e73135-2bbf-e10c-fa67-3a0c624e45cb
* Content: [CA1033: Interface methods should be callable by child types - Visual Studio](https://docs.microsoft.com/nl-be/visualstudio/code-quality/ca1033?view=vs-2019)
* Content Source: [docs/code-quality/ca1033.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1033.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@d4e666 It sounds like you are unhappy with the rule itself, rather than some issue in the doc. If that's correct, please open an issue in the roslyn-analyzers repo.
https://github.com/dotnet/roslyn-analyzers/issues

**Comment by Mikejo5000** [comment]
Closing as a product feedback rather than a doc issue.
