### ISSUE TITLE
Publish profile to Azure wizard

### ISSUE THREAD

**Issue by svangeti** [MicrosoftDocs/visualstudio-docs#4863]
It doesn't list all Azure App services available in the subscription to chose from. The list is limited to only 14 app services from the subscription.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92da5d51-dd0e-f62e-c453-8bdaafe04776
* Version Independent ID: 645d4899-f7c6-ffcd-53fa-3b6fb64be765
* Content: [Publish to Azure App Service - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-app-svc?view=vsmac-2019)
* Content Source: [mac/publish-app-svc.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-app-svc.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
@svangeti I believe the issue is that we only show App Services that are running Windows. Is that the case for you or is it something different?

**Comment by svangeti** [comment]
@sayedihashimi why is that limitation? Why can't I publish to Linux app service from Mac Visual studio?

**Comment by sayedihashimi** [comment]
@svangeti yes, you are absolutely correct we should have that support. When we implemented the publish experience, at that time App Service didn't have full support of .NET Core apps in Linux. I have it on my backlog. I'll do some more investigation to see if I can move this up in priority.

**Comment by sayedihashimi** [comment]
I'm no longer working with Visual Studio for Mac. I think this would be better assigned to @jmatthiesen.
