### ISSUE TITLE
Missing curly bracket

### ISSUE THREAD

**Issue by amoebasinger** [MicrosoftDocs/visualstudio-docs#4865]
A minor complaint, but if you follow directions explicitly (in the Revise the Code section), you will be short a curly bracket at the end.
If you copy/paste, the last curly bracket will be missing because instruction 1 says to delete all the code following the first open curly bracket.
The "complete code" at the end has it.
Thanks.

J

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@amoebasinger -- J, thank you for catching this.

@ornellaalt -- Ornella, please review the above-mentioned PR 6186.
