### ISSUE TITLE
Instructions to change image size do not work

### ISSUE THREAD

**Issue by downstevedown** [MicrosoftDocs/visualstudio-docs#4868]
I've left feedback on the page linked above to the effect that the parameter name is spelled incorrectly, but even when correct, setting Docker to:

{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false,
  "storage-opt": [
    "dm.basesize=128GB",
    "size=128GB"
  ]
}

Docker for Windows still creates 20GB images. As a result, you won't be able to install build tools as indicated above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a03297c-c10e-c0e8-679c-df90b709d475
* Version Independent ID: 2e9073e3-4dc7-5ccc-55ac-ecbf039e7c29
* Content: [Known issues for containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container-issues?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container-issues.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @downstevedown, were you able to confirm that it was an image size issue using the instructions on this page? If so, I'd like to close this particular issue and allow the appropriate team to respond to your other issue (https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1338) about the problems with Docker for Windows. 

From what I understand, both the product team and documentation team is aware of the situation and is working on a fix.

**Comment by downstevedown** [comment]
I can confirm that it was image size. I ran the framework log collection tool as a part of the image build, allowed the image to build to a Powershell session, ran it, extracted the logs and found an error indicating that vs_buildtools.exe needed 91.99GB in order to install.

Given that it seemed from internet chatter to be related to something in Windows 10 1903, I created a Windows Server 2016 VM, installed Docker Engine , attempted the same, and it appeared that it wouldn't even collect the logs.

You may close this ticket out.

Regards,
Steve

________________________________

**Comment by ornellaalt** [comment]
@downstevedown Hi Steve, thanks for the additional information. I'll double check that the product team has this information.
