### ISSUE TITLE
How do I use complex condition?

### ISSUE THREAD

**Issue by itaibh** [MicrosoftDocs/visualstudio-docs#4869]
What I need is a short form of selecting checking if a $(TargetFramework) (for example) is either net45, net46, net47 or net48. Or if it's netcore of any version. And suppose I set my &lt;TargetFrameworks&gt; tag to support net45;net48;netcoreapp2.1;netcoreapp3.1;netstandard2.1;
Is there an easy way to do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@rainersigwald

**Comment by ghogen** [comment]
To accomplish your stated goal, you could use the Or operator on the condition with each individual $(TargetFramework) value:

<Target Name="CustomAfterBuild" AfterTargets="Build" Condition="$(TargetFramework) == 'net45' Or $(TargetFramework) == 'net46' Or $(TargetFramework) == 'net47' Or $(TargetFramework) == 'net48'">

If you really just care about .NET Framework vs. .NET Core you could use $(TargetFrameworkIdentifier):

<Target Name="CustomAfterBuild" AfterTargets="Build" Condition="$(TargetFrameworkIdentifier) == '.NETCoreApp'">

**Comment by rainersigwald** [comment]
We're hoping to improve the situation in the future: microsoft/msbuild#5171.

cc @dsplaisted -- we don't have any "best you can do for now" docs on this, do we?

**Comment by dsplaisted** [comment]
> we don't have any "best you can do for now" docs on this, do we?

No, I don't think we do.

If the condition is for a target, then I would recommend comparing to `TargetFrameworkIdentifier` and using the new [version comparison intrinsics](https://github.com/microsoft/msbuild/pull/4911) to compare against `TargetFrameworkVersion`.

**Comment by Nirmal4G** [comment]
`TargetFramework` is always inserted for multi-targeting builds at the top-level, so, you can use it like this...

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net45;net48;netstandard2.1;netcoreapp2.1;netcoreapp3.1</TargetFrameworks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(TargetFramework.Trim('0123456789.'))' == 'net'">
        <!-- Properties for .NET Framework -->
    </PropertyGroup>

    <!--
        You can also do it like this, since, 'TargetFrameworkIdentifier', 'TargetFrameworkVersion'
        will be available by now, as Properties are evaluated before Items.
    -->
    <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETCoreApp'">
        <!-- Items for .NET Core -->
    </ItemGroup>

</Project>
```

Remember, this only works at the property level because of the Multi-Targeting, since .NET SDK targets themselves insert `TargetFramework` for every framework in `TargetFrameworks`.

**Comment by itaibh** [comment]
All I wanted to know was if I can use string functions on variables. Seems
I can, but it wasn't documented, and I had to rely on mix and match from
various examples found in several different places. It would have helped me
a lot if a simple example was with clear list of possible method, or simple
stating that every method a string has can work, was present.

**Comment by ghogen** [comment]
@itaibh I'll use some of the examples given here to add to this topic, including some of the string functions. In MSBuild, using .NET methods in property definitions is a feature is known as property functions, documented at https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019).

**Comment by ses4j** [comment]
@ghogen As documented, this doesn't work for me, apparently due to all the single apostrophes and lack of escaping:

<PropertyGroup Condition="'$(TargetFramework.TrimEnd('0123456789.'))' == 'net'">

gives this error:

....csproj : error  : An unexpected token "0123456789." was found at character position 29 in condition "'$(TargetFramework.TrimEnd('0123456789.'))' == 'net'".  c:\wc\...\My.targets

**Comment by Nirmal4G** [comment]
Try backtick __`__ for arguments instead of single apostrophe.

OR

We can expect `TargetFramework` to be single word with no spaces, so in that case, you can drop the the apostrophe around the variable and the string constant. I think.

**Comment by michkot** [comment]
> Try backtick **`** for arguments instead of single apostrophe.
> 
> OR
> 
> We can expect `TargetFramework` to be single word with no spaces, so in that case, you can drop the the apostrophe around the variable and the string constant. I think.

backtick did not work -- but removing the outer apostrophe did. I guess the example (with the TrimEnd) included in the docs should be updated?
