### ISSUE TITLE
Unity + Visual Studio for Mac (community): Running and Debugging Unit Tests

### ISSUE THREAD

**Issue by feliperobledo** [MicrosoftDocs/visualstudio-docs#4870]
### Problem

I'm trying to figure out how to run my Unity game's unit tests on Visual Studio for Mac. I have the following 2 problems:

1. How to run my unit tests from inside of Visual Studio
1. How to debug my unit tests from inside of Visual Studio

For problem 1, I was hoping [visual studios docs on working with Unity](https://docs.microsoft.com/en-us/visualstudio/mac/using-vsmac-tools-unity?view=vsmac-2019#feedback) would have some answers, but it does not.

For problem 2, I found [this other visual studio thread](https://developercommunity.visualstudio.com/content/problem/125430/how-do-i-debug-unit-tests.html), and it makes sense what they suggest. I can see my test framework is being picked up by Visual Studio (see picture below)...
![Screen Shot 2020-02-29 at 8 39 37 AM](https://user-images.githubusercontent.com/6238302/75611402-16794d80-5acf-11ea-9d5a-20f20dd5f012.png)

But after I run my tests I don't see any output:
![Screen Shot 2020-02-29 at 8 39 58 AM](https://user-images.githubusercontent.com/6238302/75611411-25600000-5acf-11ea-9891-856786ce7479.png)

### Request
Could you please add some documentation on the [visual studio docs for unity](https://docs.microsoft.com/en-us/visualstudio/mac/using-vsmac-tools-unity?view=vsmac-2019#feedback) to help with this process?

This questions has been asked several times in different ways in the Unity forums but now one has answered it. See the links below:
- https://answers.unity.com/questions/1561447/running-unit-tests-from-visual-code.html
- https://answers.unity.com/questions/1360577/can-i-run-unit-tests-in-visual-studio-using-the-un.html

My hope is that by this being in the documentation there is no more need to ask this question on the Unity forums.

### Specs:
```
Visual Studio for Mac (Community) Version 8.4.7
Unity Version 2019.2.17f1 Personal
macOS Mojave 10.14.6
MacBook Pro 15-inch, Mid 2015
```

Thank you.

**Comment by therealjohn** [comment]
@feliperobledo VS doesn't currently support running Unit Tests from within the IDE. You would need to use the Unity editor and test runner to execute the tests. 

The best next step is to use the Help > Suggest a Feature menu from Visual Studio for Mac and document what you expect to happen. I know the team is already investigating Unit Testing support but this would give you a public way to track it and the request can be updated as soon as it's available. 

For future issues, it's best to use the Help > Report a Problem for the fastest response directly from the engineering team. This GitHub is for issues specifically related to the documentation.

**Comment by feliperobledo** [comment]
@therealjohn thank you for your prompt response.

I will do as you suggested. I thought I might have been missing a step, which is why I posted here.

I will mark this issue as resolved for now, then.
