### ISSUE TITLE
Error while trying to run project: Unable to start debugging (fuzzy message)

### ISSUE THREAD

**Issue by PawcioCNCProfi** [MicrosoftDocs/visualstudio-docs#4871]
I cannot connect to remote computer. I'm having error right after I hit start button "**Error while trying to run project: Unable to start debugging.**" Next part of the message is written in polish so I don't know how exactly to translate it but it's something like "**Connection with remote endpoint was finished.**"

![Capture4](https://user-images.githubusercontent.com/57447464/75683429-63a81b80-5c97-11ea-9ce2-acc9989c546c.PNG)

I don't event see a prompt to insert credentials.

My colleague is connecting to the same computer without any problem. We tried everything we could've thought of. Setting firewall rules, disabling antivirus, using IP instead of name, running VS as Administrator... Everything ends with the same message result, except when we turn off remote debugger. In such case I got the windows saying the operation takes longer than expected and after a wile I get standard error message which can be also seen by my colleague when the remote debugger in not running.

So I understand this means my VS can talk with the remote debugger but somehow can't agree with it.

I've also tried **Attach to Process** window and VS is finding the remote debugger when I hit **Find...** while **Connection type** is set to **SSH** Button. But when I fill the form of the  **Connect to Remote System** window and try to connect, the Host name and Port fields getting red border and it says "**Connectivity Failure. Please make sure Host name and Port number are correct**". Well, I'm pretty sure they are correct...

Another difference is that when **Connection type** is set to **Default**  I see only my computer, where's my colleague is seeing also the remote and my computer. I can **Find...** the remote debugger but when I hit **Select** on the item in **AutoDetected** items, the **Connect to Remote System** is not show but instead I get error similar to the on described in the first place: "**Unable to connect Microsoft Visual Studio Remote Debugger named "CNCIrek".**"  Rest of the message is the same polish message I got in the first place.

What else can I do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 284b9094-8c91-69e1-01a2-0183ca3ec2a9
* Version Independent ID: 8f7a16bb-32f6-3047-16e3-b82b82fbb7c0
* Content: [Unable to Connect to the Microsoft Visual Studio Remote Debugging Monitor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor?view=vs-2019#rejected)
* Content Source: [docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@PawcioCNCProfi Sorry you have experienced this issue. The error, in English, is "Connection with the remote endpoint has been terminated." The first thing to do is use [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem. 
You've already tried a few things I'd recommend (like run VS as an Admin). If you are able to resolve, it would be great if you could report the result here and I will update the doc.

**Comment by Mikejo5000** [comment]
One thread here:
https://developercommunity.visualstudio.com/content/problem/217242/debugger-failed-with-the-remote-endpoint-was-termi.html

**Comment by Mikejo5000** [comment]
Also, if you can tell us your debugging scenario that would help us to identify possible solutions, so that we can update the doc. Otherwise, I will close this as a product issue. Thanks!

**Comment by PawcioCNCProfi** [comment]
I'm not sure what you mean by "debugging scenario" and what can I tell more. I'm trying to connect  to a computer in a local network connected via router. The computer runs Win 7, I'm on Windows 10... I've managed to find and fix the problem without debugger but I still cannot connect the computer.

**Comment by Mikejo5000** [comment]
I've seen that some people running into this error were trying to debug an azure service, rather than say, an ASP.NET app running on IIS. There might be different possible solutions.

**Comment by PawcioCNCProfi** [comment]
No, I have desktop app .NET Framework 4.5 - don't think this is relevant since even **Attach To Process** window don't work as expected.

**Comment by Mikejo5000** [comment]
OK, thanks. If I can find out more, I'll update the issue here, but I will plan to close this out as a product issue. Please use Report a Problem tool to investigate further with the engineering team.

**Comment by PawcioCNCProfi** [comment]
Thanks, It's already reported: https://developercommunity.visualstudio.com/content/problem/937073/error-while-trying-to-run-project-unable-to-start-8.html

**Comment by Mikejo5000** [comment]
Closing as a product issue. If we can identify a doc update that should be made, please re-open.
