### ISSUE TITLE
How do I get the error list to remember my scoping filter?

### ISSUE THREAD

**Issue by v-kydela** [MicrosoftDocs/visualstudio-docs#4878]
I have to set the "show items contained by" dropdown to Current Project every time I open the solution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 619b7785-c2cb-c582-6478-debc1d5e40d6
* Version Independent ID: 91e701f2-a959-e25b-d9cc-48d0b4e8ba50
* Content: [Error List Window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/error-list-window?view=vs-2019&source=docs#feedback)
* Content Source: [docs/ide/reference/error-list-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/error-list-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@v-kydela  Thank you for the feedback and apologies for the delay.

Unfortunately, this is a product-related issue and can only be addressed by the product team, please consider starting an issue [here](https://developercommunity.visualstudio.com/spaces/8/index.html), or let us know and we can start one for you.

The likelihood of this being addressed may be somewhat low given similar cases on [column width](https://developercommunity.visualstudio.com/content/problem/1761/error-list-window-does-not-remember-column-widths.html) and [visibility](https://developercommunity.visualstudio.com/content/problem/568380/show-error-list-is-always-shown.html), however it's still worth soliciting further feedback and advice.

Closing the issue now.

@TerryGLee
