### ISSUE TITLE
list of weak types is not complete

### ISSUE THREAD

**Issue by TobiasKnauss** [MicrosoftDocs/visualstudio-docs#488]
The warning is also given on string-arrays, and also on int-arrays (likely on all arrays of value types).
Please add that including an explanation, why.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b97ee078-36f0-1f9b-cb29-93293989d5f6
* Version Independent ID: 786d0d32-ffdc-a6e5-fcd7-484b04cc3cf1
* [Content](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2002-do-not-lock-on-objects-with-weak-identity)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/code-quality/ca2002-do-not-lock-on-objects-with-weak-identity.md)
* Service: unspecified

**Comment by gewarren** [comment]
@TobiasKnauss Yes you are correct that arrays of primitive types are considered weak types too. I will update the topic, thank you.

**Comment by gewarren** [comment]
The updated topic should be live tomorrow.
