### ISSUE TITLE
missing information

### ISSUE THREAD

**Issue by mk-16** [MicrosoftDocs/visualstudio-docs#4886]
the guide/tutorial is very extensive and things do work as they should, my problem is as fallows
in the section "Add project files"  there you explain that the files are going to be created in root folder, and that if i want to create it in a subsection I'd have to modify directory accordingly, except that there is no explanation about how to do so....everytime then when i load the files the command on the terminal ''node_modules\.bin\webpack app.tsx --config webpack-config.js"
tells me that the file doesn't exist..... how do i modify this command directory ???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#transpile-the-jsx)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mk-16, so in your error message the only file it says it can't find right now is app.tsx. For that file, you should just need to modify the "entry" in webpack-config.js and I believe the "files" entry in tsconfig.json. These file references should include the subfolder.

https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#configure-webpack-and-typescript-compiler-options

If you are moving other files, like webpack-config.js, from the root folder, or changing the output folder (dist), there would be other modifications needed. Mostly in webpack-config.js and perhaps the script reference in index.html. I can't recall now, but tsconfig may need to stay in the root folder.

It shortens the instructions quite a bit to put everything in the root folder, so I did that for simplicity.

**Comment by mk-16** [comment]
tried to change the entry not working... this is why i think there is a problem ....
Original =>
 entry: "./app.tsx",
Modified =>
 entry: "/test/app.tsx",

still getting an error .  .. very sad i cant upload images

**Comment by Mikejo5000** [comment]
I would suggest trying ".test/app.tsx" instead and in tsconfig.json "test/app.tsx"

**Comment by Mikejo5000** [comment]
@mk-16 Did you get things running?

**Comment by mk-16** [comment]
hi just got back home (had a long drive) im giving it a try in a a few seconds TIA

**Comment by mk-16** [comment]
well mike, still getting this error telling me there is not such file

**Comment by mk-16** [comment]
the terminal does open root folder but doesnt get inside the directory path that i placed (in this case....    entry:"./test/app.tsx"

**Comment by Mikejo5000** [comment]
I tried this. I can eliminate the error by doing this in package.json:
  "scripts": {
    "build": "webpack-cli test/app.tsx --config webpack-config.js"
  }

**Comment by Mikejo5000** [comment]
Also, if you do run from a command line, you should run the command from the root folder (the folder that opens when you right-click the project and choose Open Command Prompt Here.

**Comment by mk-16** [comment]
{
  "scripts": {
    "build": "webpack-cli test/app.tsx --config webpack-config.js"
  },
  "name": "learning-react",
  "version": "0.0.0",
  "description": "LearningReact",
  "main": "server.js",
  "author": {
    "name": ""
  },
  "dependencies": {
    "react": "^16.13.0",
    "express": "~4.16.4",
    "path": "~0.12.7",
    "react-dom": "~16.6.0",
    "ts-loader": "~5.3.0",
    "typescript": "~3.1.5",
    "webpack": "~4.23.1",
    "webpack-cli": "~3.1.2"
  }
}


tried this .... didnt work i have a hunch im not understanding you correctly

**Comment by Mikejo5000** [comment]
To repro this and then fix the error, I put app.tsx in the /test folder (didn't move any other files). Everything else was the same as in the tutorial. Then three changes.
1. webpack-config.js: entry: "./test/app.tsx",
2. tsconfig.json: 
  "files": [
    "test/app.tsx"
  ]
3. package.json:
"scripts": {
"build": "webpack-cli test/app.tsx --config webpack-config.js"
},

**Comment by mk-16** [comment]
okey i think i  solved it with your huge guidance... thanks for patience and time... and for any1 else that reads this... i did those 3 steps (didnt work quite yet) ... i changed the command on the terminal 
from:
node_modules\.bin\webpack app.tsx --config webpack-config.js
to:
node_modules\.bin\webpack test\app.tsx --config webpack-config.js

that in addition to the 3 steps above solved... now terminal loaded all as should

**Comment by Mikejo5000** [comment]
Great! I'll close this for now. Maybe I will add some more instructions later.
I do notice that your package.json has different versions of "webpack" and "webpack-cli". If I recall correctly, the versions should match. Could be wrong but you ought to check it.
