### ISSUE TITLE
Nunit test sample is wrong

### ISSUE THREAD

**Issue by xmen824** [MicrosoftDocs/visualstudio-docs#4887]
the sample provided is just same as MStest, so by copying the code as provide will reflects a missing an assembly reference

![image](https://user-images.githubusercontent.com/12017577/75924478-e74a4e00-5ecb-11ea-86aa-a8e19fd2b10f.png)

**Comment by Mikejo5000** [comment]
@xmen824 Can you add a link to the page you're referencing? Thanks!

**Comment by xmen824** [comment]
https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2019

**Comment by Mikejo5000** [comment]
Thanks! I'll update the doc.
