### ISSUE TITLE
Create a multi-container app with Docker Compose and configure with same base URL in dot net core 3.0

### ISSUE THREAD

**Issue by adnannrajaa** [MicrosoftDocs/visualstudio-docs#4889]
![image2](https://user-images.githubusercontent.com/58033249/75978799-1fb84f00-5f01-11ea-8466-6a4de02ea357.PNG)

I have above project structure and want to configure all of them with same base url.

**Comment by WilliamAntonRohm** [comment]
@adnannrajaa -- Adnan, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by adnannrajaa** [comment]
i want to implement micro-services architecture using asp.net core 3.0, i have above application structure. and the issue i face is explained bellow
My "MicroservicesWithDocker.WebApi" have following base address
![webapi](https://user-images.githubusercontent.com/58033249/76056329-21812180-5f98-11ea-9c59-dc51011ba137.PNG)

My "MicroservicesWithDocker.TestApi" have following base address
![testApi](https://user-images.githubusercontent.com/58033249/76056401-44abd100-5f98-11ea-8cb4-5296a1b11ead.PNG)

My "MicroservicesWithDocker.FrontEnd" have following base address
![frontEnd](https://user-images.githubusercontent.com/58033249/76056410-49708500-5f98-11ea-95e5-3b6f3e2b6092.PNG)

i want to call all these three with same base url ?

**Comment by adnannrajaa** [comment]
**The reason to do that is i don't   want to call my each micro-service with individual URL.**

**Comment by WilliamAntonRohm** [comment]
@adnannrajaa -- Adnan, thank you for clarifying.  This repo is only for documentation issues.  You may find answers here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
