### ISSUE TITLE
Incorrect heading: "Initialize the Globals class"

### ISSUE THREAD

**Issue by sabuncu** [MicrosoftDocs/visualstudio-docs#4892]
The heading **"Initialize the Globals class"** implies that an initialization of the Globals class needs to be carried out by the developer, which is not the case, as this class is automatically initialized at runtime by VSTO itself.

A correct heading might be: **"Check before accessing the Globals class"**

If the heading is indeed about the need to initialize the Globals class for use _during design time_, then the instructions contained in the content under the heading are not helpful towards that goal.  In any case, the use of the Globals class during design time would _rarely_ be required.  I know of no examples of such use.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b8a8724-a3da-2972-ce83-af76692bedfe
* Version Independent ID: 24f4c46c-bd9d-c731-2dc0-d8f9cfb4601f
* Content: [Global access to objects in Office projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/global-access-to-objects-in-office-projects?view=vs-2019)
* Content Source: [docs/vsto/global-access-to-objects-in-office-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/global-access-to-objects-in-office-projects.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
This should be fixed shortly
