### ISSUE TITLE
Factory interface URLs are all displayed with identical text, not distinguishing the specific Office tools to which they point

### ISSUE THREAD

**Issue by sabuncu** [MicrosoftDocs/visualstudio-docs#4893]
Under the last bullet item (beginning with "A factory object that enables you to create..."), the four listed URLs are all displayed with the identical text of "Factory".

![2020-03-05 17_47_34-Global access to objects in Office projects - Visual Studio _ Microsoft Docs](https://user-images.githubusercontent.com/6242253/75993523-a45b9b00-5f0a-11ea-9c97-070b0746db62.png)
These are in fact pointing to the interfaces for Office, Excel, Outlook and Word (in their listed order).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b8a8724-a3da-2972-ce83-af76692bedfe
* Version Independent ID: 24f4c46c-bd9d-c731-2dc0-d8f9cfb4601f
* Content: [Global access to objects in Office projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/global-access-to-objects-in-office-projects?view=vs-2019)
* Content Source: [docs/vsto/global-access-to-objects-in-office-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/global-access-to-objects-in-office-projects.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
This should be fixed shortly
