### ISSUE TITLE
Install error on Visual Studio 2019 - Found setup instance but not in launchable state

### ISSUE THREAD

**Issue by leniel** [MicrosoftDocs/visualstudio-docs#4894]
These are the last lines of the log:

Found setup instance 883a9c0e but not in launchable state.
Install Error : System.InvalidOperationException: Cannot find setup engine instance.

I managed to install it by installing "Visual Studio extension development" workload as suggested here: https://stackoverflow.com/a/56001724/114029.

If "Visual Studio extension development" is necessary... it should be mentioned @ the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@leniel For context, you were trying to install the analyzers using VSIX, and you ran into this issue?

**Comment by leniel** [comment]
@Mikejo5000 exactly... using the VSIX package.

**Comment by Mikejo5000** [comment]
@mikadumont Mika, do you know whether the "Visual Studio extension development" workload is required to install the analyzers using the VSIX? If so, I can update this.

**Comment by Mikejo5000** [comment]
I tested this (no VS extension development workload installed), but no repro. Seems to have installed OK. Likely a product issue.

**Comment by Gopichandar** [comment]
Im having the similar issue when I tried to install "ML.NET Model builder" into my VS2019 community Edition 16.4.2

**Comment by mavasani** [comment]
Note that we are soon planning to deprecate Microsoft Code Analysis VS2019 VSIX (aka FxCop analyzers VSIX): https://github.com/dotnet/roslyn-analyzers/issues/3314. It is strongly recommended to install the analyzers through the NuGet package right now.

**Comment by msebolt** [comment]
Closing this issue now, if problems persist please comment below to re-open the issue.

Also consider using the **Report a problem** or **Suggest a feature** options in [Visual Studio community](https://developercommunity.visualstudio.com/spaces/21/index.html) where feedback can be solicited directly from the product team.

**Comment by ManniAT** [comment]
I had the same Issue with VS2017 - "PowerShell Tools for VS" and "Redgate SQL Change Automation" got an update today - and didn't install with this error message.
I uninstalled the feature "VS-Extension Developement workload" - and reinstalled it - after that it worked.

**Comment by vibs2006** [comment]
Never Expected Microsoft to be so naive. Now in 2019 too this bug is persistent. To resolve this please enable that you check the following.

![image](https://user-images.githubusercontent.com/18658498/132347802-dfd7f399-86df-4c00-82de-66230f57cf15.png)

**Comment by WilliamAntonRohm** [comment]
@vibs2006 -- thank you for your contribution to this discussion.

cc @Mikejo5000 for awareness

**Comment by bstordrup** [comment]
Experience this issue also with Visual Studio 2022 Community edition.

My install command looks like this:

```
    start /w vs_Community.exe install `
    --installPath "%ProgramFiles%\Microsoft Visual Studio\2022\Community" `
    --allWorkloads `
    --includeRecommended `
    --remove Microsoft.VisualStudio.Workload.Data `
    --remove Microsoft.VisualStudio.Workload.DataScience `
    --remove Microsoft.VisualStudio.Workload.ManagedGame `
    --remove Microsoft.VisualStudio.Workload.NativeCrossPlat `
    --remove Microsoft.VisualStudio.Workload.NativeGame `
    --remove Microsoft.VisualStudio.Workload.NativeMobile `
    --remove Microsoft.VisualStudio.Workload.NetCrossPlat `
    --remove Microsoft.VisualStudio.Workload.Node `
    --remove Microsoft.VisualStudio.Workload.Python `
    --remove Microsoft.VisualStudio.Workload.Universal`
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
    --add Microsoft.Net.ComponentGroup.4.8.1.DeveloperTools `
    --add Microsoft.Net.ComponentGroup.4.6.2-4.7.1.DeveloperTools `
    --add Microsoft.NetCore.Component.DevelopmentTools `
    --add Microsoft.VisualStudio.Component.Wcf.Tooling `
    --add Microsoft.VisualStudio.Component.TextTemplating `
    --add Microsoft.NetCore.Component.Runtime.6.0 `
    --add Microsoft.NetCore.Component.Runtime.7.0 `
    --add Microsoft.Net.Component.4.7.2.SDK `
    --add Microsoft.Net.Component.4.8.1.SDK `
    --add Microsoft.Net.Component.4.6.2.TargetingPack `
    --add Microsoft.Net.Component.4.7.TargetingPack `
    --add Microsoft.Net.Component.4.7.1.TargetingPack `
    --add Microsoft.Net.Component.4.8.1.TargetingPack `
    --add Microsoft.VisualStudio.Component.VC.ATLMFC `
    --add Microsoft.VisualStudio.Component.VC.ATL `
    --add Microsoft.VisualStudio.Component.VC.CLI.Support `
    --add Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64 `
    --add Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL `
    --add Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC `
    --add Microsoft.VisualStudio.Component.VC.14.37.17.7.CLI.Support `
    --add Microsoft.VisualStudio.Component.VC.14.38.17.8.x86.x64 `
    --add Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL `
    --add Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC `
    --add Microsoft.VisualStudio.Component.VC.14.38.17.8.CLI.Support `
    --add Microsoft.VisualStudio.Component.Windows10SDK.19041 `
    --quiet --wait --norestart --nocache && `
```

This should mean that the "Visual Studio extension development" workload should be present in the installation. And I assume it would not be a fix to uninstall it and install it again since this is a fresh and clean installation.

I'm installing into a docker image based on `mcr.microsoft.com/windows/servercore:ltsc2022` and recreated the docker image commands based on commands found in `mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2022`
