### ISSUE TITLE
Icon Label visibility

### ISSUE THREAD

**Issue by ihorbond** [MicrosoftDocs/visualstudio-docs#4896]
Great tutorial I'd just add that if you go with toggling label visibility instead of blending it by matching the ForeColor to BackColor the Click events won't be triggered on those labels

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac5e066-696c-95ba-8fa1-19d8afe5dc4d
* Version Independent ID: 1239320c-0e15-da0e-c6b4-72af0a8dac9c
* Content: [Step 3: Assign a random icon to each label - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-3-assign-a-random-icon-to-each-label?view=vs-2019#feedback)
* Content Source: [docs/ide/step-3-assign-a-random-icon-to-each-label.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-3-assign-a-random-icon-to-each-label.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @ihorbond, thanks for the call out! I removed that tip since it's not directly applicable to this tutorial (and we want the click events to be triggered in this case). Closing out this issue.
