### ISSUE TITLE
Undocumented csharp_new_line_before_while

### ISSUE THREAD

**Issue by euyuil** [MicrosoftDocs/visualstudio-docs#4899]
It looks like `csharp_new_line_before_while` is supported in VS 2019. But it hasn't been documented here.

Based on my testing, setting `csharp_new_line_before_while` to `true` will make the following style preferred:

```csharp
do
{
    // ...
}
while (flag);
```

If it's set to `false`, the following style is preferred:

```csharp
do
{
    // ...
} while (flag);
```

Would you please add `csharp_new_line_before_while` to the document if it's available now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db54afa5-fc7b-394f-ede3-4d1d46ec695d
* Version Independent ID: 86441bf6-9e5b-85c2-d42d-3afd5a9a069b
* Content: [.NET formatting conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-formatting-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-formatting-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@mikadumont FYI on this

**Comment by Gav-Brown** [comment]
This setting is also not written to the .editorconfig file if you export from the Visual Studio - Tools - Options - Text Editor - C# - Code Style options dialog. Using VS 16.6.1 (or earlier).

**Comment by cremor** [comment]
@euyuil Are you sure that this is actually a setting that Visual Studio supports? I've just tested it with VS 2019 version 16.7.2 (the current version at this time) and couldn't get it to work.

I'm also unable to find it in the Roslyn source code (see [code search query](https://github.com/dotnet/roslyn/search?q=csharp_new_line_before_while&unscoped_q=csharp_new_line_before_while)).

Google leads to a [ReSharper documentation page](https://www.jetbrains.com/help/resharper/EditorConfig_CSHARP_LineBreaksPageSchema.html#resharper_csharp_new_line_before_while). So I assume this is a ReSharper setting, which would mean it should not be documented here.

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#20885
