### ISSUE TITLE
There is an error in the examples list for backslash

### ISSUE THREAD

**Issue by Zoidborg7** [MicrosoftDocs/visualstudio-docs#490]
In the row with Purpose "Escape the character following the backslash", the middle column contains the wrong character along with what should be the third column's Example text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/using-regular-expressions-in-visual-studio.md)
* Service: unspecified

**Comment by gewarren** [comment]
@Zoidborg7 thanks so much for pointing this out. It's fixed now.
