### ISSUE TITLE
utf-8-bom usage

### ISSUE THREAD

**Issue by JamesSkemp** [MicrosoftDocs/visualstudio-docs#4901]
Today was the first time I used VS to create a .editorconfig using the .NET template and I was interested in why it was recommending utf-8-bom for the charset.

https://github.com/editorconfig/editorconfig/issues/297 and https://stackoverflow.com/a/2223926/11912 utf-8-bom is discouraged. Should this page and the new file template in Visual Studio (editorconfig File (.NET)) be updated accordingly?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@JamesSkemp Thank you for the feedback.

Assigning this to the author for further review.

**Comment by TerryGLee** [comment]
@JamesSkemp Thanks for bringing this to our attention. We've replaced the example .editorconfig file in the [Example EditorConfig file](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019#example-editorconfig-file) section with one that we've created by using the recent [version 16.5 release](https://docs.microsoft.com/visualstudio/releases/2019/release-notes), and the reference to utf-8-bom is no longer listed.

**Comment by TerryGLee** [comment]
@glen-84 Please create a new GitHub Issue for this by using the Feedback controls, here: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2019#feedback
