### ISSUE TITLE
CA1021 has been ported

### ISSUE THREAD

**Issue by jjhayworth** [MicrosoftDocs/visualstudio-docs#4902]
CA1021 has been ported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd01f814-2fb6-066f-bdae-c7070e5f22d7
* Version Independent ID: 32f4ae71-bfb3-259f-0f10-bc56f184a9ad
* Content: [FxCop rule port status - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status?view=vs-2019#deprecated-rules)
* Content Source: [docs/code-quality/fxcop-rule-port-status.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/fxcop-rule-port-status.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, I'll add it to the doc.
