### ISSUE TITLE
Unity MonoBehaviour Scripting Wizard is currently broken in VSTU for 2019.2 and up

### ISSUE THREAD

**Issue by tommai78101** [MicrosoftDocs/visualstudio-docs#4904]
There should be a disclaimer message stating that this feature is currently unresolved for Visual Studio 2019 Tools for Unity 2019.2 and up. The workaround is to uninstall VSTU 2019 and downgrade to VSTU 2017, and/or downgrade from Unity 2019.2 and up to Unity 2019.1.

This is stated by John Miller [MSFT]:

https://developercommunity.visualstudio.com/content/problem/605250/vs-tools-for-unity-2019-missing-event-autocomplete.html?childToView=606689#comment-606689

Affects this section:

https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2019#unity-monobehavior-scripting-wizard

Otherwise, please let me know when VSTU 2019 with Unity 2019.3 or Unity 2019.4 LTS will have the issue fixed? Currently, I cannot invoke "Quick MonoBehaviours Method Wizard" on VS 2019 with VSTU 2019 for Unity 2019.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56378a75-b639-d64b-d7fb-00a7eafa20b5
* Version Independent ID: c66870c5-4153-7b42-7aad-fc454c39f9cd
* Content: [Using Visual Studio Tools for Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2019#unity-monobehavior-scripting-wizard)
* Content Source: [docs/cross-platform/using-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/using-visual-studio-tools-for-unity.md)
* Product: **visual-studio-windows**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by msebolt** [comment]
@tommai78101 Thank you for the feedback.

It's probably best to keep this as an open issue until Unity provides the needed fix.

Assigning this to the author for review.

**Comment by tommai78101** [comment]
Thanks, will follow closely.

**Comment by therealjohn** [comment]
@tommai78101 I believed the issue I mentioned in the DeveloperCommunity post was fixed in the final release versions of 2019.3 and newer. Are you using an alpha or beta of 2019.3?

**Comment by tommai78101** [comment]
Beta 2019.3.

**Comment by therealjohn** [comment]
2019.3 finals work. I believe Unity fixed this in the 2019.3 betas, but to be sure, I just tried it with VS 2019 and Unity 2019.3.7f1 and it works as expected.

**Comment by tommai78101** [comment]
@therealjohn Cool! Thanks for letting me know. I guess my original issue is no longer relevant as it's fixed in the later versions.

Does the documentation still needs to let readers know of the issue that exists in 2019.2?

**Comment by therealjohn** [comment]
@tommai78101 No problem, thanks for reporting this. I added a Note to the docs about the 2019.2 issue in a Pull Request. Once it's approved, the docs will update. Thanks!

**Comment by tommai78101** [comment]
Thank you. I'll close my issue then, as I believed it's now resolved.
