### ISSUE TITLE
Boost docs inconsistent

### ISSUE THREAD

**Issue by L4ZZA** [MicrosoftDocs/visualstudio-docs#4906]
The Boost test documentation does not apply to the latest visual studio 2019 16.4.5
![boost_vs_docs](https://user-images.githubusercontent.com/17835185/75994471-f1337780-5ef2-11ea-80a8-3c285d77c9c0.png)

Even after installing the Boost.TestAdapter that option is not available. It doesn't matter if you build boost yourself or add it with package manager (NuGet, vcpgk) the test is not discovered by the Visual Studio.

Please fix the VS bug asap or update the docs to match reality.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45fbddc-51f2-1c42-eaf2-f78e6220a9e7
* Version Independent ID: 1ce72223-80ab-651a-40f3-dc8112b2a3cf
* Content: [How to use Boost.Test for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp?view=vs-2019)
* Content Source: [docs/test/how-to-use-boost-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-boost-test-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@L4ZZA 
I'm sorry it's not working for you. To the best of my knowledge, the documentation describes the way the product is supposed to work. The behavior you describe is a product issue, which you should report on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). That's the fastest and best way to bring the issue to the attention of the development team. You can do it right from the IDE, by using **Help** > **Send Feedback** > **Report a Problem**. If I'm wrong, and something needs to be updated in the documentation, the developers will let me know. Thanks for taking the time to report the issue.
