### ISSUE TITLE
Only break when unhandled?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/visualstudio-docs#4907]
The Exception settings window has checkboxes for breaking when an exception is thrown. But how do I configure VS to only break if the exception is unhandled?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d45057ee-e31b-321c-93e6-3e4516cee1d3
* Version Independent ID: 7938c681-a902-c970-5b2b-924ca70d0ed1
* Content: [Manage exceptions with the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/managing-exceptions-with-the-debugger?view=vs-2019)
* Content Source: [docs/debugger/managing-exceptions-with-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/managing-exceptions-with-the-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Bartolomeus-649 You are describing the default behavior for all exceptions, to break when unhandled, which opens the Exception Helper. The Exception Settings allows you to break when thrown instead, which also captures handled exceptions.

**Comment by Bartolomeus-649** [comment]
So how do I configure VS to not break at all?

**Comment by Mikejo5000** [comment]
Well, if there are particular exceptions you are concerned about, use Exception Settings, right-click exceptions you are interested in, and choose "Continue when Unhandled in User Code". You might need to set those individually.

**Comment by Mikejo5000** [comment]
I should probably add that you should be able to override the default behavior with the Exception Settings, but normally users running your app will hit an unhandled exception in user code, so you need to avoid them / get them handled, usually via try/catch. I expect that you already know that.

**Comment by Mikejo5000** [comment]
Just checked the doc. You can configure that for a whole category at a time.

**Comment by Mikejo5000** [comment]
I don't think there's a doc issue here, so closing this.
