### ISSUE TITLE
Best practice for a developer to use AzureServiceTokenProvider() parameter-less in a container.

### ISSUE THREAD

**Issue by sig9** [MicrosoftDocs/visualstudio-docs#4910]
I had trouble accessing keyvault as a developer on Windows when running in docker.  On the host I had already logged into azure and I wanted to volume mount ~/.azure into the container and have the exact same code work inside the container that was already working outside the container. 

The following addition  of azure cli into the base image, and adding DockerfileRunArguments seems to work.   Is this a good approach or is there a better way that I should develop and have code that calls 
`var azureServiceTokenProvider = new AzureServiceTokenProvider(); `
without any parameters. 

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
# Install azure cli into the base so that will work with AzureServiceTokenProvider parameterless constructor
# when local .azure is volume mounted into container. 
# e.g. from project.csproj <DockerfileRunArguments>-v $(HOMEDRIVE)$(HOMEPATH)\.azure:/root/.azure</DockerfileRunArguments>
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
WORKDIR /app
EXPOSE 80
EXPOSE 443```

**Comment by WilliamAntonRohm** [comment]
@sig9 -- Hal, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com topic you’re referencing, or provide more context around your general task.

**Comment by sig9** [comment]
@WilliamAntonRohm Thanks for letting me know about the linking issue.  I was reading either 
https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019
or 
https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication

I think this could be a potential duplicate with workaround for https://github.com/MicrosoftDocs/azure-docs/issues/47959

When I saw that the base container that Visual studio puts in the Dockerfile, I realized that it does not have the azure cli installed.  I thought I would try a volume mount with the az cli installed.  It worked.  Not sure if it is the optimal solution though. 

This error message was my first clue. 
`Tried to get token using Azure CLI. Access token could not be acquired. /bin/bash: az: No such file or directory'`

**Comment by ghogen** [comment]
@BigMorty What would you advise in this scenario?

**Comment by NCarlsonMSFT** [comment]
@BigMorty tagged me in as I've been playing in this space recently.

For azure authentication in the container tools I would recommend using a service principal:
https://docs.microsoft.com/en-us/azure/key-vault/general/service-to-service-authentication#running-the-application-using-a-service-principal 

Short version:
* Create a service principle (az ad sp create-for-rbac --sdk-auth)
* Grant it the permissions to the resources your app accesses
* Set the environment variable “AzureServicesAuthConnectionString” to “RunAs=App;AppId={AppId};TenantId={TenantId};AppKey={ClientSecret}”

Where things get complicated is keeping the secret out of source control. You can either exclude your launchsetting.json from source control (effective, but inconvenient) or something more complicated:  
**Using the built in secrets concept:**  
One approach is to store the client secret in the projects secrets. Which works great for keeping the secret, but then you need a block of code in your startup to copy the secret from the configuration to the environment before you need to authenticate with Azure. *Warning: If you are accessing Key Vault as a configuration provider this will not work!*

**Using msbuild properties:**  
The next simplest option is to have an excluded .props file that adds the msbuild property DockerfileRunArguments i.e.:  
`<DockerfileRunArguments>-e "AzureServicesAuthConnectionString=RunAs=App;AppId={AppId};TenantId={TenantId};AppKey={ClientSecret}"</ DockerfileRunArguments>`
I would highly recommend adding a script to the repo that could call out to azure and grab the value from a key vault and write out the props file to keep users from having to do it themselves.
One bonus to this method is that if you have several container projects in a solution that all need to authenticate with azure they could potentially share this file.

Using the service principle is a better match to how this will run in production and lets you keep your container a little cleaner.

**Comment by sig9** [comment]
Thanks for these ideas.  I have not tried AzureServicesAuthConnectionString before.   
The only advantage I see with the ~/.azure volume mount is that it is tied to a user's AzureAD credentials and avoids sharing credentials.  keyvault could have a secret per developer except that it lacks per-secret access controls.  That would imply a keyvault per developer or some other mechanism to distribute service principal secrets.    

This may be a case where there isn't a best practice, just a choice of several valid options.
