### ISSUE TITLE
How many alternative accounts can a subscription have?

### ISSUE THREAD

**Issue by fhack2** [MicrosoftDocs/visualstudio-docs#4911]
This does not mention how many alternative accounts you can link to your subscription. Believe it maybe only one. For a contractor with their own subscription, they would have to keep changing the alternative account to the different companies so they could utilize the subscription or have the company pay for one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e967e1-0b8e-a6b5-13ef-bd206ca6d13a
* Version Independent ID: 612623f5-6252-6353-8c7c-c1be43bd8801
* Content: [Identities for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-alternate-identity#feedback)
* Content Source: [subscriptions/vs-alternate-identity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-alternate-identity.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@fhack2 - You're correct.  One alternate ID is supported.

**Comment by evanwindom** [comment]
#please-close
