### ISSUE TITLE
where is the .runsettings documentation for GoogleTestAdapter and BoostTestsAdapter?

### ISSUE THREAD

**Issue by L4ZZA** [MicrosoftDocs/visualstudio-docs#4912]
I can't find anywhere in the microsoft/visual-studio docs all the options available to specify my own .runsetting file.
We are using two systems MsTest and GoogleTests and I can't specify the default filtering for any of those.

I have some c# and c++ tests with testCategory/traits set UnitTests and I need to only run those and not all the other groups of tests. 
I'm trying to filter them using _my.runsetting_ file, but at the moment is not possible to do so according to the documentation. Or at least it's really hard to find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee608ee-eb3f-e95d-1eea-d9e35a6e0bc0
* Version Independent ID: daf80b3e-5bf1-652c-d6a0-602c8bc2bb0c
* Content: [How to use Google Test for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-google-test-for-cpp?view=vs-2019)
* Content Source: [docs/test/how-to-use-google-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-google-test-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by kendrahavens** [comment]
Hi @L4ZZA, I am following up on if you can do this in the .runsettings file.

In the mean time, if you running these tests from Visual Studio or the command-line you have a few options:

In Visual Studio you can use the search bar to filter the Test Explorer to certain traits. https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019#search-and-filter-the-test-list

At the command-line you can filter using the /TestCaseFilter:[expression] option. https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019

You can also make a playlist of specific tests to run together and use that in Visual Studio or at the command-line.

Does one of the above options work or would you like to specifically specify this in a runsettings file?

**Comment by L4ZZA** [comment]
I'm not looking to specify the location of the file. I'm looking for an official working example of a runsetting file for boost.testadapter.
On the current latest release VS16.4.6 and Boost Test Adapter installed as additional component, boost test are still not discovered. 
So my only hope left is the runsetting file hoping it will work after specifying the right parameters.

See this [post](https://stackoverflow.com/questions/60671290/boost-tests-vc142-from-vcpkg-on-visual-studio-2019) for more details.

**Comment by kendrahavens** [comment]
Thank you for the clarification. You cannot currently filter boost tests in the runsettings file.

We are currently working on implementing the ability to add a test case filter: https://github.com/microsoft/vstest/pull/2356

**Comment by kendrahavens** [comment]
For the discovery issue, I suggest you post a bug on http://developercommunity.visualstudio.com/ if you haven't already so we can follow up!

**Comment by L4ZZA** [comment]
I have a while back [here](https://developercommunity.visualstudio.com/content/problem/943077/boosttest-discovery-and-run-is-broken.html)

**Comment by corob-msft** [comment]
Closing the doc issue, as I expect the dev team to communicate any needed changes when features are implemented.

**Comment by ahofinger-hexagon** [comment]
In the meantime, in the unit tests of the [BoostTestAdapter Source Code](https://github.com/etas/vs-boost-unit-test-adapter/blob/master/BoostTestAdapterNunit/BoostTestSettingsTest.cs#L206), you can find some sample `.runsettings`-files, e.g.:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<BoostTest>
		<TestBatchStrategy>TestSuite</TestBatchStrategy>
	</BoostTest>
</RunSettings>
```

**Comment by hofingerandi** [comment]
In the meantime, in the unit tests of the [BoostTestAdapter Source Code](https://github.com/etas/vs-boost-unit-test-adapter/blob/master/BoostTestAdapterNunit/BoostTestSettingsTest.cs#L206), you can find some sample `.runsettings`-files, e.g.:
```
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
	<BoostTest>
		<TestBatchStrategy>TestSuite</TestBatchStrategy>
	</BoostTest>
</RunSettings>
```
