### ISSUE TITLE
Page is totally confusing

### ISSUE THREAD

**Issue by JayD2019** [MicrosoftDocs/visualstudio-docs#4914]
Article is dated 02/13/2020.
In the Blue section at top it states: " Important:   In most scenarios, the Google Android emulator is recommended for use instead of the Visual Studio Emulator for Android: - Visual Studio Emulator for Android is not supported after Visual Studio 2015.... etc"

 Than carries on to tell you how to install/use the Visual Studio Emulator for Android which - according to the text -  is ONLY supported  on VS2015 - nothing before or after !!

 "Visual Studio Emulator for Android requires Visual Studio 2015; it is not backward compatible with earlier versions of Visual Studio."

SO WHERE is the page/instructions relevant to VS versions that are NOT 2015??
(Preferably VS2019 )

 Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bdda1ea-471b-6285-427f-4b14a44de863
* Version Independent ID: 0f51f444-6bad-3e06-928d-dbd70f2cc4b8
* Content: [Visual Studio Emulator for Android - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-studio-emulator-for-android?view=vs-2017)
* Content Source: [docs/cross-platform/visual-studio-emulator-for-android.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/visual-studio-emulator-for-android.md)
* Product: **visual-studio-dev15**
* Technology: **vs-ide-mobile**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by corob-msft** [comment]
@JayD2019 
We don't recommend the deprecated Visual Studio Emulator for Android, but we left in the instructions for VS 2015 users. Visual Studio 2019 (and 2017, and 2015) picks up and uses the installed Google Android emulators automatically. You can install those using the Android development kit tools. After you select and configure an emulator in the AVD Manager and launch it at least once, it should appear in the emulator target list in Visual Studio.

**Comment by JayD2019** [comment]
Hi Colin,
Thanks for the reply and sorry for delayed response.

I understand what you say. My main point (which I probably did not make
well before) is that the page should target *only *VS 2015 and should say
so at the top. And there should be links (at the top) to the equivalent
text for other VS versions (as is it is done elsewhere on msdn for
example). That would be much clearer.

Regards,

J
*Joanna Davidson MSc. IT*
Independent Software Consultant / Engineer

Phone:  +
1 868 763 8140 /
+44 754 335 8494
Email: jaydavidson09@gmail.com/joannad@idetect.net/jaydavidson@acm.org
Web:   http://tt.linkedin.com/in/jayd2010
