### ISSUE TITLE
Barely Adequate

### ISSUE THREAD

**Issue by mikerayginter** [MicrosoftDocs/visualstudio-docs#492]
Your documentation is horrible.   Once again, smart people doing stupid things.  This explanation is much better:
Passing in a function reference into array.sort()
As touched on already, array.sort() accepts an optional parameter in the form of a function reference (lets call it sortfunction). The format of this function looks like this:
function sortfunction(a, b){
    //Compare "a" and "b" in some fashion, and return -1, 0, or 1
}
array.sort(sortfunction)
When such a function is passed into array.sort(), the array elements are sorted based on the relationship between each pair of elements "a" and "b" and the function's return value. The three possible return numbers are: <0 (less than 0), 0, or >0 (greater than 0):

Less than 0: Sort "a" to be a lower index than "b"
 Zero: "a" and "b" should be considered equal, and no sorting performed.
 Greater than 0: Sort "b" to be a lower index than "a".

I would not have understood with your demonstration code.   You give an example with no context, or explanation.  This is true of almost ALL MICROSOFT DOCS I have ever come across in 25+ years.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98128a3-d334-a5d8-b930-af0c5a74bf93
* Version Independent ID: 322e7557-d005-9bb4-59ec-9dc6c9b8e69e
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/sort-method-array-javascript)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/reference/sort-method-array-javascript.md)
* Service: unspecified

**Comment by smoroz** [comment]
!!!

**Comment by mikerayginter** [comment]
I thought I was pretty straight forward with my comments.  I don't
understand your reply any more than I understand your / Microsoft's help
files.  No wonder your help system sucks so much.
Strike another fail for MS!  Perhaps you suck at communication as much as
MS sucks at writing help files.
MG

**Comment by gewarren** [comment]
@mikerayginter That reply was not from a Microsoft employee. Our writer @Mikejo5000 has assigned this to himself to look into.

**Comment by mikerayginter** [comment]
I thought that person was awfully rude.  Thank you for mentioning this.  I
have been trying to learn javascript and PHP and I am often very frustrated
at the documentation out there, but most times MS seems to be worse than
others at least to me.  It seems as if the writers ASSUME a certain amount
of knowledge about any topic with no pointers or context.  That is why I
pointed to a much more descriptive version that your team could perhaps use
as an example.  Thank you for your reply.
MG

**Comment by gewarren** [comment]
@mikerayginter thank you for your honest and thoughtful feedback. It does help us improve!

**Comment by Mikejo5000** [comment]
Updated remarks based on feedback. Thanks!
