### ISSUE TITLE
Code Analysis Settings are deprecated

### ISSUE THREAD

**Issue by bravadomizzou** [MicrosoftDocs/visualstudio-docs#4920]
"If necessary, expand Common Properties, and then select Code Analysis Settings." 
When you go to this, it says the page has been deprecated and will be removed in a future product release and wont let you do anything. What is the new way to configure Code Analysis Settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 111c5e43-7341-3c2a-3130-e11aa0e0af50
* Version Independent ID: db4f1bef-94ee-0ce1-6b13-9966364b498b
* Content: [Configure Code Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-configure-code-analysis-for-a-managed-code-project?view=vs-2019#feedback)
* Content Source: [docs/code-quality/how-to-configure-code-analysis-for-a-managed-code-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-configure-code-analysis-for-a-managed-code-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@bravadomizzou Legacy or source code analysis? This article applies to legacy analysis. For legacy analysis, rule sets:
https://docs.microsoft.com/en-us/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2019
For source code analysis, either EditorConfig or rulesets.

**Comment by Mikejo5000** [comment]
Also to note, legacy analysis is not supported in .NET Core or .NET Standard projects.

**Comment by Mikejo5000** [comment]
Article notes that it applies only to legacy analysis, so I don't think we need a doc update.
