### ISSUE TITLE
Package name not always correct

### ISSUE THREAD

**Issue by zrhpwr** [MicrosoftDocs/visualstudio-docs#4922]
In the section "NuGet package" is refered to "Microsoft.CodeAnalyzers.FxCopAnalyzers package" instead of "Microsoft.CodeAnalysis.FxCopAnalyzers".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019#nuget-package)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- please review the above-mentioned PR 6256.
