### ISSUE TITLE
Miss an explanation about resolution 

### ISSUE THREAD

**Issue by vhavard** [MicrosoftDocs/visualstudio-docs#4923]
Hello,
I am looking for an export in PNG that allow setting the resolution of the diagram exported, in order to cotrol quality.
I do not find the explanation.

Thank you to add it.
vincent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c320fda-9daf-1439-abb2-0cf1f58950ec
* Version Independent ID: feadf2c2-3ad3-66e6-d1b3-9f26b5f92ae5
* Content: [How to: Export Class Diagrams As Images (Class Designer) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/class-designer/how-to-export-class-diagrams-as-images?view=vs-2019#feedback)
* Content Source: [docs/ide/class-designer/how-to-export-class-diagrams-as-images.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/class-designer/how-to-export-class-diagrams-as-images.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@vhavard -- Vincent, thank you for your feedback.  You may find answers here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@TerryGLee -- Terry, please look into this issue.
