### ISSUE TITLE
doc is wrong

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#4924]
@nicol-go commented on [Tue Mar 10 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/178)

The part of "Run diagnostic sessions on installed or running apps" is out-dated. This way cannot work well in VS2019. Could you update the document?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e998101e-f5d8-517a-7f74-356b973a2b07
* Version Independent ID: 36f07905-43eb-019a-a0f6-a732b9d10da6
* Content: [运行带或不带调试器的分析工具 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/profiling/running-profiling-tools-with-or-without-the-debugger?view=vs-2019)
* Content Source: [docs/profiling/running-profiling-tools-with-or-without-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/profiling/running-profiling-tools-with-or-without-the-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

---

@srvbpigh commented on [Wed Mar 11 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/178#issuecomment-597420676)

Hello, @nicol-go
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Mikejo5000** [comment]
@CeciAc Cecilia, can you ask the customer what the app scenario is? What kind of app they are creating, and what they were trying to do that didn't work? Thanks.

**Comment by Mikejo5000** [comment]
@CeciAc Also, if the customer is trying a remote scenario, the Remote Tools (w/VSDiagnostics.exe) need to be installed on the remote machine. The command-line profiling tools appears to be another way to do this remotely. The latter requires the Performance Tools for VS 2019.
https://docs.microsoft.com/en-us/visualstudio/profiling/profile-apps-from-command-line?view=vs-2019

**Comment by Mikejo5000** [comment]
Updating the doc to resolve this based on the information we have so far. See MicrosoftDocs/visualstudio-docs-pr#6366. Leaving this open for now in case we get new information on the customer scenario and problem.

**Comment by Mikejo5000** [comment]
Updated the doc as noted. We can re-open this if we get additional information.
