### ISSUE TITLE
Isn't Lab Manager via Test Manager obsolete?

### ISSUE THREAD

**Issue by sulu99** [MicrosoftDocs/visualstudio-docs#4927]
We have been told not to use Test Manager as Microsoft is going to stop supporting it. To that end, we have been designing our automated test cases in such a way so that they can be run by anyone in our department via the web portal. Is the Test Manager going away?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff923f4c-388c-8630-794c-794c13db9ab5
* Version Independent ID: d6d35a68-205f-8408-57f8-d85a447bf96b
* Content: [Use a lab environment for devops - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/lab-management/using-a-lab-environment-for-your-application-lifecycle?view=vs-2019&source=docs)
* Content Source: [docs/test/lab-management/using-a-lab-environment-for-your-application-lifecycle.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/lab-management/using-a-lab-environment-for-your-application-lifecycle.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@sulu99 I believe Test Manager is not supported in VS 2019. @kendrahavens in case she has more info on this.
See this doc:
https://docs.microsoft.com/en-us/azure/devops/test/mtm/run-manual-tests-with-microsoft-test-manager?view=azure-devops

**Comment by kendrahavens** [comment]
Correct, the local Test Manager experience in Visual Studio 2017 is the last version. We recommend using Azure Test Plans the Test hub in TFS.

**Comment by Mikejo5000** [comment]
Thanks. For the doc here, I will update it so that the section on Test Manager is VS 2017 only.

**Comment by sulu99** [comment]
You guys are excellent! Thank you very much!
