### ISSUE TITLE
Corrupted File

### ISSUE THREAD

**Issue by ProgrammerAI** [MicrosoftDocs/visualstudio-docs#4929]
I am working on a solution in VS2019 and I need to open one of my files with the extension _**.xaml.cs**_. I try to open the file but it opens in notepad with a bunch of random characters. I look at the encoding and I see that it is in ascii encoding. I try to convert to UTF-8 encoding but the site I used returns an error. The file contents look like [this](https://github.com/MicrosoftDocs/visualstudio-docs/files/4320954/MainPage.xaml.zip). Can I fix it or is it permanent. Also, how do I get my file back?

**Comment by WilliamAntonRohm** [comment]
@ProgrammerAI -- Kayos, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.

**Comment by ProgrammerAI** [comment]
@WilliamAntonRohm -- Does this help?
```
**System Info**
OS: Windows 10 64 Bit
Using Visual Studio 2019
Project type: 
    C# 
    .NET CORE
    WPF
```

**Comment by WilliamAntonRohm** [comment]
@ProgrammerAI -- this repo is solely for documentation issues, with limited support options.  You may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.  

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
