### ISSUE TITLE
Out of date - project templates no longer available.

### ISSUE THREAD

**Issue by BioTurboNick** [MicrosoftDocs/visualstudio-docs#493]
Out of date - project templates no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: df5ae85d-e974-88c9-f530-1833b6862993
* Version Independent ID: b8469a0a-d783-edc1-2097-265ca0ff18b7
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/test-windows-store-8-1-apps-with-coded-ui-tests)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/test-windows-store-8-1-apps-with-coded-ui-tests.md)
* Service: unspecified

**Comment by gewarren** [comment]
@BioTurboNick thank you for letting us know. Most of our test documentation needs a good refresh at this point and it's on our to-do list.
