### ISSUE TITLE
The version of visual studio is not compatible with your version of windows

### ISSUE THREAD

**Issue by Tonymens31** [MicrosoftDocs/visualstudio-docs#4931]
Kindly help me resolve this as i am using windows 10 pro and i am getting issues while trying to install 2019 version of visual studio

**Comment by WilliamAntonRohm** [comment]
@Tonymens31 -- it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
