### ISSUE TITLE
How to debug an SLN solution in VS

### ISSUE THREAD

**Issue by Maheenmathew** [MicrosoftDocs/visualstudio-docs#4932]
Hi,
I am new to VS. I am trying to debug SLN solutio  that I generated for a Hololens project. I am able to deploy the solution successfully. But when I open the sln once built, I am unable to navigate to the cs files in the project to set up a debug point. If I open 2 sessions, one for the project and one for SLN, place the debug points in the cs code, then run the application it does not stop at the debug point. Please can you help. 
Thanks, M

**Comment by Mikejo5000** [comment]
If you want to debug a deployed app, see if the instructions here help. It should apply to HoloLens:
https://docs.microsoft.com/en-us/visualstudio/debugger/debug-installed-app-package?view=vs-2019

**Comment by Maheenmathew** [comment]
Hi Mikejo5000! The link looks really promising. Thanks a lot! Will let you know how it goes. Cheers!

**Comment by Maheenmathew** [comment]
Hi I tried the linke above, followd all the instructions, then when I launch the aplication I get the following error 'failed to launch remote debugger with the following error:'command failed: 0x80070490''. When I am not debugging the application works.  Any ideas?

**Comment by Mikejo5000** [comment]
@gregg-miskelly Gregg, any suggestion on this?

**Comment by Mikejo5000** [comment]
@Maheenmathew  Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
Closing as an apparent product bug.

@Maheenmathew If you were able to resolve, please let us know. ThxA
