### ISSUE TITLE
一处拼写错误:nMake拼成了nNake

### ISSUE THREAD

**Issue by mewiteor** [MicrosoftDocs/visualstudio-docs#494]
在“To create a custom build task”中第2项的结尾处

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970f0d59-b2b4-7082-1c2c-a468c93571ef
* Version Independent ID: a3135966-c343-5a6b-cd97-772a0c34fd93
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md)
* Service: unspecified

**Comment by gewarren** [comment]
There is a typo, it should say nMake and not nNake. @mewiteor thanks for reporting this! It will be fixed soon.

**Comment by gewarren** [comment]
Fixed/removed the typo.
