### ISSUE TITLE
Slow step over for remote debugging

### ISSUE THREAD

**Issue by liangdaxian** [MicrosoftDocs/visualstudio-docs#4941]
hi VS folks,

we have a product which is deployed to Azure VM, and dev can use remote debugging btw devbox and Azure VM, however the remtoe debugging sometimes is super slow (a step over take 6-12 seconds), is there any best practice or guidance we can follow to make it better ?

**Comment by WilliamAntonRohm** [comment]
@liangdaxian -- Thanks for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.  

Meanwhile, you may find answers here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
