### ISSUE TITLE
Cosmos DB

### ISSUE THREAD

**Issue by Camios** [MicrosoftDocs/visualstudio-docs#4942]
*.documents.azure.com/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@Camios -- Cameron, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around your general task.  

Meanwhile, you may find answers here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by Camios** [comment]
Hi @WilliamAntonRohm,
I noticed that the URL/subdomain for Azure Cosmos DB document database was missing from the list of URLs to whitelist (table 3 I believe) when working behind a proxy firewall. I request this be checked and added please

**Comment by ornellaalt** [comment]
Hi @Camios, are you just looking for public cloud?

Here is a complete listing of endpoint and ports by API and mode: 

Mode | Protocol | API | URI | Ports
-- | -- | -- | -- | --
Gateway | HTTPS | Cassandra | [account-name].cassandra.cosmos.azure.com | 10350
Gateway | HTTPS | Gremlin | [account-name].gremlin.cosmos.azure.com | 443
Gateway | HTTPS | Mongo 3.2 | [account-name].documents.azure.com | 10250, 10255, 10256
Gateway | HTTPS | Mongo 3.6 | [account-name].mongo.cosmos.azure.com | 10250, 10255, 10256
Gateway | HTTPS | Table | [account-name].table.cosmos.azure.com | 443
Gateway | HTTPS | Core (SQL) | [account-name].documents.azure.com | 443
Gateway | HTTPS | Core (SQL) | [account-name].sql.cosmos.azure.com | 443
Direct | TCP | Core (SQL) | [account-name].documents.azure.com | 10000-20000
Direct | TCP | Core (SQL) | [account-name].sql.cosmos.azure.com | 10000-20000

Please let me know which API you are looking for and I will create a work item to update the documentation. Closing out this issue for now.
