### ISSUE TITLE
VS 2019 link to release notes 16.4 is not available anymore

### ISSUE THREAD

**Issue by eriawan** [MicrosoftDocs/visualstudio-docs#4943]
The link to VS 2019 v16.4 release notes is not available anymore!

The link to 16.4 release notes in this link will always redirect to itself, although the link says 16.4 release notes:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

![image](https://user-images.githubusercontent.com/8773147/76819506-f66dbc00-683a-11ea-8743-634cd076c517.png)

Looking at the release history, the link goes to the 2019/release-notes page again:
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-history

Please fix this!

**Comment by TerryGLee** [comment]
@JacquelineWiddis Please take a look?

**Comment by TerryGLee** [comment]
@eriawan Thanks for letting us know; it looks like this is fixed now.

**Comment by eriawan** [comment]
@TerryGLee thanks!
