### ISSUE TITLE
Also

### ISSUE THREAD

**Issue by gusarov** [MicrosoftDocs/visualstudio-docs#4944]
* Disable map mode scroll bars: Option \ Text Editor \ All Languages \ Scroll Bars \ Behavior = Use bar mode
* For really big files disable word wrap: Edit \ Advanced \ Word Wrap

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f7e6c9-3f47-4caa-b69f-ae6393bde555
* Version Independent ID: dc59c52a-163f-40fb-c84d-ba7b1b8118b4
* Content: [Tips to improve performance - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-performance-tips-and-tricks?view=vs-2019#feedback)
* Content Source: [docs/ide/visual-studio-performance-tips-and-tricks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-performance-tips-and-tricks.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@gusarov We've added both the 'disable map mode' and 'disable word wrap' info that you suggested; the updated page will go live after 4:00 P.M. Pacific Daylight Time today, 8/13/2020. Thanks for your help with improving our documentation!
