### ISSUE TITLE
Missing "Convert between Auto property and Full property"

### ISSUE THREAD

**Issue by MechanoRealist** [MicrosoftDocs/visualstudio-docs#4945]
What the title says.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ce42b1-5ca3-2bba-be51-172e0ad715fd
* Version Independent ID: 3e28ccb0-f87e-bb74-c4f0-ed0ed2f1b364
* Content: [Refactoring - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/refactoring-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/refactoring-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/refactoring-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by mikadumont** [comment]
Yes, we are missing this to be documented. We do think this is discoverable within the tool. I will mark as low priority and help wanted.

**Comment by mikadumont** [comment]
@TerryGLee I dont have permissions to add labels.

**Comment by TerryGLee** [comment]
@mikadumont Thanks for your response; I've change the priority. @MechanoRealist Thanks for your feedback; this is in the queue. We'll report back after we've made updates to the docs.

**Comment by mikadumont** [comment]
Thanks @TerryGLee! Can you give me access to change labels?

**Comment by TerryGLee** [comment]
@mikadumont You should have this soon, if not already. (If you don't have this yet, please check again tomorrow. Then, let me know if you require further follow-up re: access.)

**Comment by mikadumont** [comment]
@TerryGLee I have it now - thank you!

**Comment by mikadumont** [comment]
[Here](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-between-auto-property-and-full-property?view=vs-2019) is the missing doc for this refactoring.
