### ISSUE TITLE
Update steps for current release?

### ISSUE THREAD

**Issue by ravensorb** [MicrosoftDocs/visualstudio-docs#4948]
These steps no longer work and I was curious if there are plans to update them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019#feedback)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @ravensorb, I am working with the product team to get these instructions updated soon. There are several other GitHub issues currently tracking this particular fix-- I will close this duplicate and ask you to please refer to https://github.com/MicrosoftDocs/visualstudio-docs/issues/4915 for updates.
