### ISSUE TITLE
Vs 2019 Seems to have broken the Drag of Tables on to the Data Set Designer

### ISSUE THREAD

**Issue by BicycleMark** [MicrosoftDocs/visualstudio-docs#4949]
Vs 2019 Seems to have broken the Drag of Tables on to the Data Set Designer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03e3ba56-450a-ff3f-6f76-2153e4941621
* Version Independent ID: 6e9f3066-f40b-b83f-5175-8abf2dda3da0
* Content: [Walkthrough: Creating a Dataset with the Dataset Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/walkthrough-creating-a-dataset-with-the-dataset-designer?view=vs-2019)
* Content Source: [docs/data-tools/walkthrough-creating-a-dataset-with-the-dataset-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/walkthrough-creating-a-dataset-with-the-dataset-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@BicycleMark -- Mark, please consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report this issue.  This repo is solely for documentation issues.
