### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by MalibuFilm** [MicrosoftDocs/visualstudio-docs#495]
nice work done

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 010a26f2-c143-8bbd-7268-3c33a1547997
* Version Independent ID: fec2a456-49c1-74f6-b362-24d11a03266f
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/asp-net-core#installing-net-core)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/mac/asp-net-core.md)
* Service: unspecified

**Comment by gewarren** [comment]
@MalibuFilm @asb3993 thank you for the feedback!
