### ISSUE TITLE
Rename to "Abstract types should not have public constructors"

### ISSUE THREAD

**Issue by Danghor** [MicrosoftDocs/visualstudio-docs#4952]
I think the title is a bit misleading. Since the suggested fix does not remove the constructor entirely, but rather changes it from 'public' to 'protected', a better title would be something like 'Abstract types should not have public constructors'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e78e1ff-9239-a6c2-f5ab-186b9fa45678
* Version Independent ID: 651023fb-2fe0-c581-52e0-76409bec2ba4
* Content: [CA1012: Abstract types should not have constructors - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1012?view=vs-2019)
* Content Source: [docs/code-quality/ca1012.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1012.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Danghor Product needs an update for this fix. Would you reopen this issue on /dotnet/roslyn-analyzers/issues ? Thanks.
