### ISSUE TITLE
Pretty out of date

### ISSUE THREAD

**Issue by LdsDannyStaten** [MicrosoftDocs/visualstudio-docs#4953]
Both Azure and Visual Studio are very different now, and I am running into strange errors when publishing, but I don't have a good way to be sure I adapted my configuration settings accurately.  So, this article leaves me in a bit of a murky spot right now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4faf174-cdfd-e0d5-3eaf-e2c47d6d8f70
* Version Independent ID: 3464f7d8-21bc-b920-93a8-f5447b835b82
* Content: [Debugging an Azure cloud service or virtual machine - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-debug-cloud-services-virtual-machines?view=vs-2019#feedback)
* Content Source: [docs/azure/vs-azure-tools-debug-cloud-services-virtual-machines.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/azure/vs-azure-tools-debug-cloud-services-virtual-machines.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@LdsDannyStaten I believe that doc is out of date. There are different scenarios in Azure that require different debugging solutions. Are you trying to debug an Azure App Service on Windows? Linux? containerized app?
You might take a look here, for starters:
https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-azure?view=vs-2019
