### ISSUE TITLE
ModulePaths Include doesn't work as described here

### ISSUE THREAD

**Issue by brdmllr** [MicrosoftDocs/visualstudio-docs#4954]
The example under the heading "The following example specifies that only a single assembly should be included in code coverage" does not work or me. I had to modify ModulePath line as follows for it to work -

&lt;ModulePath&gt;.*Fabrikam.Math.dll$&lt;/ModulePath&gt;

Brad

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dc6fcf-df9f-9d2a-5c6e-8da0f6925afc
* Version Independent ID: d0bf2cae-9b59-d537-7acb-7af5f560d8c1
* Content: [Customizing Code Coverage Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019#feedback)
* Content Source: [docs/test/customizing-code-coverage-analysis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/customizing-code-coverage-analysis.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@kendrahavens @AbhitejJohn Should the example be updated as suggested, from
Fabrikam.Math.dll to .*Fabrikam.Math.dll$ ? It's a little puzzling why the regular expression is required for specifying a single assembly...

**Comment by jakubch1** [comment]
At least .* has to be added at the beginning ( .*Fabrikam.Math.dll). Otherwise it's not working as we full path match is required.

**Comment by Mikejo5000** [comment]
I will go ahead and update the doc. Thx!
