### ISSUE TITLE
Get Current Date

### ISSUE THREAD

**Issue by jgedri** [MicrosoftDocs/visualstudio-docs#4956]
GetCurrentDate doesn't see to be defined, though GetDateTime is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5b432e-98af-2784-12f3-5da298a7a6a3
* Version Independent ID: 0d0b207d-4ea3-3716-3894-b898b279e667
* Content: [Introduction to projects and solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019#feedback)
* Content Source: [docs/get-started/tutorial-projects-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/tutorial-projects-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@jgedri -- Jorin, thank you for your feedback.  Please clarify your issue.  In the section [Add an item to the project](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019#add-an-item-to-the-project), GetCurrentDate is defined:

`         internal static DateTime GetCurrentDate()`

There doesn't seem to be a mention of `GetDateTime` in the referenced article.

**Comment by neillindberg** [comment]
In the body of this test the "QuickDate", "...does not exist in the current context." Calendar.cs does have the "InternalVisibleTo("QuickTest")".
using System;
using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("QuickTest")]

namespace QuickDate

...
When I added the "QuickTest" it did automatically add a "UnitTest1.cs". The singular difference from screenshots above is that the "QuickTest" project does not have a beaker in the icon - it looks the same as the QuickDate project icon.

**Comment by neillindberg** [comment]
Okay, I got it, but I think this should be in the directions above. I'm an old coder, but new to C# - and VS 2019. I had to goto: Solutions Explorer > Quick Test > Dependencies. Right-click. Add Reference > Click checkbox next to the "QuickDate" project (the only project in my choices).
I really think this needs added because, while brand new to C# and this IDE, it was not apparent I had to do this and this is an introductory tutorial.

**Comment by TerryGLee** [comment]
@neillindberg I'll place this in the queue for a page update. Thanks for adding the extra info.

**Comment by TerryGLee** [comment]
It doesn't look like there is extra info in this issue that would inform a page update, and the original question asked has been answered, so I am closing this issue now. Thanks for your feedback; we hope to hear from you again if you have suggestions on how we can improve our documentation.
