### ISSUE TITLE
dotnet_style_prefer_is_null_check_over_reference_equality_method not included in .NET code style settings

### ISSUE THREAD

**Issue by obohaciak** [MicrosoftDocs/visualstudio-docs#4957]
I noticed that `dotnet_style_prefer_is_null_check_over_reference_equality_method` setting is absent from the master list under [.NET Code style settings](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#net-code-style-settings) (bullet point list under h2 with id net-code-style-settings), item *Expression-level preferences* but it is documented further in the text in the [corresponding section](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#expression-level-preferences). Can we have it added to the list at the top?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5299f22f-4b0f-9e81-883e-d34b2b520bf2
* Version Independent ID: 6a9db168-c592-29a0-59b7-1ff2f517e558
* Content: [.NET language conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#net-code-style-settings)
* Content Source: [docs/ide/editorconfig-language-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-language-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by mikadumont** [comment]
@obohaciak I went ahead and updated the documentation!

**Comment by obohaciak** [comment]
Thanks @mikadumont!
