### ISSUE TITLE
csharp_preferred_modifier_order included in the wrong section

### ISSUE THREAD

**Issue by obohaciak** [MicrosoftDocs/visualstudio-docs#4958]
csharp_preferred_modifier_order is included under .NET code style settings, but should be under C# code style settings

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5299f22f-4b0f-9e81-883e-d34b2b520bf2
* Version Independent ID: 6a9db168-c592-29a0-59b7-1ff2f517e558
* Content: [.NET language conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019#feedback)
* Content Source: [docs/ide/editorconfig-language-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-language-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by mikadumont** [comment]
I went ahead and updated the documentation!

**Comment by obohaciak** [comment]
Great, thank you for taking my feedback. One observation though, I went to have a look at the page just now and while the option is now under the right section, it appears as part of the section only separated by dash. All the other sections have their contents listed out as items of a sublist.

**Comment by mikadumont** [comment]
Yes, I fixed that and should be there by tomorrow!

**Comment by obohaciak** [comment]
Great, thanks!
