### ISSUE TITLE
Typo in "Sett Bookmarks in Code"

### ISSUE THREAD

**Issue by fomrat** [MicrosoftDocs/visualstudio-docs#4959]
docs.microsoft.com/en-us/visualstudio/ide/reference/task-list-environment-options-dialog-box

See also
Use the Task List
Sett Bookmarks in Code

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b78b04-7dd5-453e-de60-8cdd16594a99
* Version Independent ID: 27ddd786-e4c5-2b2e-e7c8-e103745dd656
* Content: [Task List, Environment, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/task-list-environment-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Environment.Task_List)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/ide/reference/task-list-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/task-list-environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@fomrat -- Brian, thank you for catching that.

@TerryGLee -- Terry, please review the tiny above-mentioned PR 6306.

**Comment by TerryGLee** [comment]
@WilliamAntonRohm Thanks for the PR. And @fomrat, thanks for helping us improve the documentation!
