### ISSUE TITLE
Missing space after refactoring.

### ISSUE THREAD

**Issue by Duikmeester** [MicrosoftDocs/visualstudio-docs#4964]
GetMyValue()&lt;SPACE&gt;==&lt;SPACE&gt;0 will refactor into GetMyValue&lt;MISSINGSPACE&gt;==&lt;SPACE&gt;0.
I have to auto-format all files after this refactor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d607160-c3a8-eee6-c19b-9fcafe006c55
* Version Independent ID: 849e53d1-3093-d9d4-444a-c1af3d2c4ebc
* Content: [Convert Get method to property; convert property to Get method - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-get-method-to-property?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/convert-get-method-to-property.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/convert-get-method-to-property.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@Duikmeester -- Sebastiaan, thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
