### ISSUE TITLE
It works for me

### ISSUE THREAD

**Issue by hkmamun** [MicrosoftDocs/visualstudio-docs#4967]
It works for me for VS-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5d5d4b8-a788-27f3-d2c5-c23ee94ba26d
* Version Independent ID: 4f5b8171-1e24-bdff-dbe5-bd83387ea5b8
* Content: [Environment settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/environment-settings?view=vs-2019#feedback)
* Content Source: [docs/ide/environment-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/environment-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@hkmamun -- Humayun, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.
