### ISSUE TITLE
DemoCalculator

### ISSUE THREAD

**Issue by MedVenturian** [MicrosoftDocs/visualstudio-docs#4969]
I'm trying to work through the tutorial. When I'm working on the App I can't select the reference because its not in the dialog box for section.
Amature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15b81f2c-0402-fa4e-fdc7-0edd1f3c4ba9
* Version Independent ID: f2fbe0e0-67b6-995a-f1c1-2f1d135e07d5
* Content: [Windows Forms Designer tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/walkthrough-windows-forms-designer?view=vs-2019#feedback)
* Content Source: [docs/designers/walkthrough-windows-forms-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/walkthrough-windows-forms-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by idegugli** [comment]
Greetings, 
I have the same problem: any solution for this issue?
Thanks.

**Comment by TerryGLee** [comment]
@MedVenturian Thanks for taking the time to write up this issue, and apologies for our delayed response to it. The instruction where it said to select **Add Reference** from the right-click context menu in Solution Explorer to open the **Add Reference** dialog box was incorrect. Here's what is correct:

- For Visual Studio 2022 & Visual Studio 2019, select **Add** > **Project Reference** to open the **Reference Manager** dialog box.
- For Visual Studio 2017, select **Add** > **Reference** to open the **Reference Manager** dialog box.

We have updated the page to reflect the correct UI. We'll close this issue now, but if you find that it doesn't solve the problem or if there are more problems with the page, please create a new GitHub Issue and we'll attend to it.

Meanwhile, thanks also to you for helping improve the documentation!
