### ISSUE TITLE
How to completely remove a menu by code? (remove, not invisible)

### ISSUE THREAD

**Issue by heku** [MicrosoftDocs/visualstudio-docs#497]
Hi,

In the past days, I was looking for the approach to completely remove a menu which defined in .vsct file, but I find nothing about this. The 'completely' here is mean not make the menu invisible, but remove it by code looks like it never defines in the .vsct file. The background is I'd like some menus(features) in my vs extension can be completely turn on/off by user. Currently, I define these menus as Dynamic Visibility and set them invisible when user turn off them, also I remove the corresponding command from the OleMenuCommandService.

Hope to hear from you.

**Comment by gewarren** [comment]
@heku thanks for opening an issue. The issues on this GitHub repo are designed for issues in the documentation, not the product. However I will see if our extensibility writer @gregvanl can steer you in the right direction.

**Comment by heku** [comment]
Thank you, if there is the ability to achieve this, I think it is better to document it.

**Comment by gregvanl** [comment]
Hi @heku I didn't think that this is possible and I double-checked with the product team to confirm that it isn't supported. 
What is unsatisfactory about the Dynamic Visibility approach you are currently using?

**Comment by heku** [comment]
Thank you, the current solution works without problems. I'm trying to find better solution because I thought the dynamic one might have a little overhead, that VS check the menu's state even if it is turned off.

**Comment by heku** [comment]
Thanks again, I close this now.
