### ISSUE TITLE
yet anoterh DUMD rule

### ISSUE THREAD

**Issue by d4e666** [MicrosoftDocs/visualstudio-docs#4970]
Have you ever checked your impact on public methods???? just check the following code

 public class OperationController
    {
        #region Methods

        /// &lt;summary&gt;
        /// Check if the service is alive
        /// &lt;/summary&gt;
        /// &lt;returns&gt;&lt;/returns&gt;
        [HttpGet]
        public async Task&lt;bool&gt; IsAlive()
        {
            return await Task.FromResult(true)
                             .ConfigureAwait(false);
        }

        #endregion
    }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73190016-ddef-0e31-ffb2-d72d551e0d0b
* Version Independent ID: 44822112-d0c7-3f59-75c0-3e81f1ee57d7
* Content: [CA1822: Mark members as static - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822?view=vs-2019)
* Content Source: [docs/code-quality/ca1822.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1822.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@d4e666 I can repro CA1822 on this code. It sounds like you would like to see the rule changed so that this code does not emit the CS1822 warning? Can you clarify? Or, do you see a doc issue here? Thanks

**Comment by Mikejo5000** [comment]
Since you mentioned public methods, I'm guessing your question falls into the category described in the "When to suppress" section: i.e., "It is safe to suppress a warning from this rule for previously shipped code for which the fix would be a breaking change."
If you would like to see the behavior changed, please open an issue in https://github.com/dotnet/roslyn-analyzers/issues
