### ISSUE TITLE
No toolbars

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/visualstudio-docs#4972]
After creating a Scene1.fbx and dropping a cylinder into it, there are no toolbars to be found anywhere.

Also, read this: https://github.com/MicrosoftDocs/vsts-docs/issues/2879

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22efa8ac-f217-7a52-a4a9-fc83441ef183
* Version Independent ID: 1f2f0a17-a731-0c3d-3e1a-9f1a1959fd50
* Content: [Model Editor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/model-editor?view=vs-2019#ModifyingObjects)
* Content Source: [docs/designers/model-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/model-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Bartolomeus-649 -- thank you for your feedback.  You may find related information here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are also welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@TerryGLee -- please look into this issue.
