### ISSUE TITLE
Solution level management of analysers for a team?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/visualstudio-docs#4973]
Please provide documentation on how to manage analysers for a solution with a lot of projects for a team.
Where you want...
- Every user in the team should have the same settings for al analysers
- All analysers should apply (have the same config) for all projects
- One central solution-level config, like you could have before with the now deprecated analysers.
- Persist and version track all changes to analysers and their configuration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36455e6f-5542-5223-b242-9cddf6df267c
* Version Independent ID: 946abcdb-7e41-b5b5-e062-9cd8c914fbd3
* Content: [Code analysis using Roslyn analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019)
* Content Source: [docs/code-quality/roslyn-analyzers-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/roslyn-analyzers-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I believe you can use a shared .editorconfig file for this purpose.
https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019
@mikadumont Mika, is that correct?

**Comment by mikadumont** [comment]
@Mikejo5000 Yes that is correct. Here is the documentation:  https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019

**Comment by Bartolomeus-649** [comment]
Where's the GUI?  Like the one you had for the old Analysers....you can't possibly expect people to do this manually in a text file?

**Comment by mikadumont** [comment]
@Bartolomeus-649 Here is documentation on the GUI - https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#code-styles-in-editorconfig-files

**Comment by Mikejo5000** [comment]
It might be good to add a couple links to the IDE pages from the configure topics. I will plan to do that.

**Comment by mikadumont** [comment]
The links are there already in the first paragraph.

**Comment by Mikejo5000** [comment]
Thanks! I think we can close this then.

**Comment by Bartolomeus-649** [comment]
Not sure how you get the analysers to show up there.
I'm talking about something similar to the GUI we use to configure the Rulesets we use today in our solutions and projects.
![image](https://user-images.githubusercontent.com/7513795/78070484-27ea9980-739c-11ea-8c8a-0bb1238cc327.png)

**Comment by mikadumont** [comment]
We have a GUI that represents the built in .NET code style analyzers. We currently dont have a GUI for third party analyzers that come from NuGet packages like RuleSets. 

In general I recommend that you use an EditorConfig file since it works with CI and can be shared with your team. EditorConfig files support third party analyzer packages and we are working to have a UI for those third party rules in EditorConfig. 

In the mean time you can configure analyzers in the editor as through the light bulb icon by pressing Ctrl+. and select Suppress or configure issues and select configure severity: 

![image](https://user-images.githubusercontent.com/46729679/78071568-9f93d680-7352-11ea-8ffd-06958bdbc17b.png)

This will generate an editorconfig file for you as well.

**Comment by Mikejo5000** [comment]
Original issue is addressed here by Mika. There might be a feature request here, but if there is please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html) for that.
@mikadumont Mika, would you close this for proper visibility? Thx!
