### ISSUE TITLE
How do we express other Docker arguments?

### ISSUE THREAD

**Issue by SidShetye** [MicrosoftDocs/visualstudio-docs#4974]
How do we get VS to pass the Docker params to Docker? 

Trying that via ` "commandLineArgs": "-p 5000:5000 -p 22222:2222 -v ~/storage:/storage --name MyServer --cap-add=SYS_PTRACE ",` doesn't seem to work as the requested port mappings are simply ignored.

This is the project's `launchSettings.json`
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles" : {
    "Docker": {
      "commandName": "Docker",
      "commandLineArgs": "-p 5000:5000 -p 22222:2222 -v ~/storage:/storage --name MyServer --cap-add=SYS_PTRACE ",
      "environmentVariables": {
        "PORT": "5000",
        "ASPNETCORE_HTTPS_PORT": "",
        "ASPNETCORE_URLS": "http://+:5000"     
      }
    }
  }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0eb0463-50c5-9697-2eaf-a5f5fcb01513
* Version Independent ID: bf27ddf9-e6a3-0717-1d3c-620c054f0d5c
* Content: [Visual Studio Container Tools launch settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2019)
* Content Source: [docs/containers/container-launch-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-launch-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@SidShetye -- Sid, thank you for your question.  You may find answers here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@ghogen -- Gordon, please look into this potential documentation issue.

**Comment by SidShetye** [comment]
@WilliamAntonRohm thanks but we expect the solution from your documentation and not just searching on the internet.

**Comment by SidShetye** [comment]
Also, there is a related [issue](https://github.com/microsoft/DockerTools/issues/243) against DockerTools that requests a less confusing design at the product level itself.

**Comment by ghogen** [comment]
I think the product issue captures the problem. Once that change is made, we'll update the docs appropriately. In the meantime, the DockerfileRunArguments property is documented here:
https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2019
- so that is the only way now to pass the arguments to the docker run command.
Therefore, I think we can close this as a doc issue.

**Comment by ghogen** [comment]
At least, I can add a bit that clarifies that these command arguments are for "starting your app".
