### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by maloscat** [MicrosoftDocs/visualstudio-docs#4976]
commit

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3b4b98f-ca64-bb77-4359-13138b5d99d8
* Version Independent ID: cd79043f-e3d9-0d56-f9d7-a428ab7c6ed4
* Content: [Downloading software titles in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/download-software#feedback)
* Content Source: [subscriptions/download-software.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/download-software.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by WilliamAntonRohm** [comment]
@maloscat -- thank for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

**Comment by evanwindom** [comment]
@WilliamAntonRohm - This may have been an attempt to commit a change to the document.  Let's go ahead and close this since we haven't heard from the submitter.  
@maloscat - We're going to go ahead and close this.  Please let us know if you're encountering an issue and need assistance.

**Comment by evanwindom** [comment]
#Please-close
