### ISSUE TITLE
Backup of Custom (drag'n'drop) Html custom items in Toolbox?

### ISSUE THREAD

**Issue by martinandersen3d** [MicrosoftDocs/visualstudio-docs#4977]
Views &gt; Toolbox (When viewing HTML files)

Hi where is the files located in the harddrive, if I want to take a backup,  or send it to someone? :-)

Thanks

![VS-Toolbox](https://user-images.githubusercontent.com/19984581/77584806-bade8c00-6ee3-11ea-8c71-f9962e259ed2.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f92855d-5247-0ffa-ef6f-cb654d7b26a7
* Version Independent ID: 54b3a6ba-badb-29c0-f3b4-f013414263aa
* Content: [Toolbox window - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/toolbox?view=vs-2019)
* Content Source: [docs/ide/reference/toolbox.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/toolbox.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@martinandersen3d -- thank you for your question.  You may find answers here:​  
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@TerryGLee -- please look into this issue.

**Comment by martinandersen3d** [comment]
I did a scan of the hdd.

The Snippets in the toolbox is located in the **"CurrentSettings.vssettings"**

In my situation the file is stored here:
C:\Users\Martin\AppData\Local\Microsoft\VisualStudio\16.0_b91ee7f2\Settings\CurrentSettings.vssettings

**Comment by TerryGLee** [comment]
@martinandersen3d I am glad to know that you found the Snippets that you were looking for. We'll consider adding this information to the page, but meanwhile, we'll close this issue.
