### ISSUE TITLE
How do I change override preference?

### ISSUE THREAD

**Issue by Pentadome** [MicrosoftDocs/visualstudio-docs#4979]
For example when i override DoSomething(), I get:

``` C#

public override void DoSomething() => base.DoSomething();

```

But I want:

``` C#

public override void DoSomething()
{
     base.DoSomething();
}

```

Where and how do i change this behaviour? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b2dad35-15b3-7597-6bca-4a7d617dac55
* Version Independent ID: e0fee980-8e2c-d52e-a713-cd92530d926b
* Content: [Generate a method override - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-override?view=vs-2019)
* Content Source: [docs/ide/reference/generate-override.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-override.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@wrkettlitz -- thank you for your question.  You may find answers here:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@TerryGLee -- please look into this issue.
