### ISSUE TITLE
How to debug a remote C# Service?

### ISSUE THREAD

**Issue by HuAaron** [MicrosoftDocs/visualstudio-docs#498]
Is there any way to debug a remote c# service? I use installutil.exe to install it. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2fd746-82f7-1bac-9932-27c14cdfe0ca
* Version Independent ID: 46b43a94-b750-2073-5e28-82183af092a9
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/remote-debugging-csharp.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@HuAaron Did you have the source code, or do you have the debugging symbols (.pdb files) generated when the service was built? You would need those, and they would need to match the .exe (i.e, they'd need to be from the same build). If you have those, you should be able to attach to the process using the debugger (Debug > Attach to Process) while the service is running.

**Comment by Mikejo5000** [comment]
Closing - product support issue

**Comment by babuw** [comment]
test
