### ISSUE TITLE
CA1024 - Rule no longer report on interface implementation

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#4985]
Hi there,

With the release of fxcop 3.X the analyzer will no longer report on interface implementation as there is no way to fix them. I am not sure whether or not you want to update the doc to mention this part.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b128d86f-bbc8-2446-f67c-d58696605c27
* Version Independent ID: 300d4a05-887f-3cd9-0161-eeb42b8c91ac
* Content: [CA1024: Use properties where appropriate - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1024?view=vs-2019)
* Content Source: [docs/code-quality/ca1024.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1024.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Yes, I will plan to update the doc. Thx!

**Comment by Mikejo5000** [comment]
Looks like interfaces are not currently mentioned in the doc, so it seems OK to me not to add any new information for this.
