### ISSUE TITLE
I REALLY need this

### ISSUE THREAD

**Issue by tbivanspcc** [MicrosoftDocs/visualstudio-docs#499]
As an instructor of Game Development in Unity, I REALLY need to be able to Install VS offline.  Downloading a ~4Gb file on 19 machines is just asking too much of our bandwidth.  why?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd139e6-bbd6-4c1a-1b40-5abd63031a9a
* Version Independent ID: bc91c619-c340-40e6-9c55-8c496eb24da5
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/create-offline-installer)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/mac/create-offline-installer.md)
* Service: unspecified

**Comment by TerryGLee** [comment]
@tbivanspcc Perhaps the "Create a network installation of Visual Studio 2017" can help? The URL is https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio

**Comment by TerryGLee** [comment]
@tbivanspcc It looks like you're asking for a difference product experience than what is currently offered and described in our offline installation-related content, to include the "Create a network installation of Visual Studio 2017" (https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio) page. If this is the case, you might want to consider registering a product suggestion on our UserVoice page, at https://visualstudio.uservoice.com/forums/121579.

**Comment by TerryGLee** [comment]
@tbivanspcc Here is a link that takes you directly to the Visual Studio for Mac product feedback: https://visualstudio.uservoice.com/forums/563332-visual-studio-for-mac

**Comment by asb3993** [comment]
I've passed this feedback directly on to the engineering team.
