### ISSUE TITLE
CA1034 - Allow builder pattern

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#4994]
The rule was updated to allow the builder pattern. It is now allowed to have an inner type whose name ends in `Builder` and whose outer class has no publicly visible (public or protected) constructor. The containing type should not be nested.

See https://github.com/dotnet/roslyn-analyzers/pull/3318

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d124eb75-6775-f608-06cc-cbe2ef0dddf8
* Version Independent ID: 93507687-1962-6e38-1b5a-8794e579ecb0
* Content: [CA1034: Nested types should not be visible - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1034?view=vs-2019)
* Content Source: [docs/code-quality/ca1034.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1034.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
The When to suppress section includes a mention of the builder pattern. This can be removed when the doc is updated.
