### ISSUE TITLE
CA3009 - shall you mention sanitizers?

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#4996]
I am wondering whether the documentation shall be updated to list the sanitizers. WDYT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc7b065c-09be-9384-2559-fbaed5c0f783
* Version Independent ID: b9671a87-4b8f-11e7-d155-f4eb7a3d194b
* Content: [CA3009: Review code for XML injection vulnerabilities - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca3009)
* Content Source: [docs/code-quality/ca3009.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca3009.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @dotpaul
* Microsoft Alias: **paulming**

**Comment by WilliamAntonRohm** [comment]
@Evangelink -- Amaury, thank you for your attention to detail.

@Mikejo5000, @dotpaul -- Mike, Paul, there is a new handful of these CA* issues:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/created_by/Evangelink

**Comment by dotpaul** [comment]
@Evangelink I'd be fine with sanitizers. It'd be good to list those under the "How to fix violations" section. Is that something you would be willing to pick up? 😀

FYI @mavasani for the other issues by by @Evangelink.

**Comment by Mikejo5000** [comment]
@Evangelink Do you have a link to the sanitizers? I'm unable to find them.

**Comment by Evangelink** [comment]
@Mikejo5000 Here are the two lists of sanitizers for this rule: [general sanitizers](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/PrimitiveTypeConverterSanitizers.cs) and [xml specific sanitizers](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/XmlSanitizers.cs).

Let me know if you have some trouble to read/understand the methods from the code.

**Comment by Mikejo5000** [comment]
@Evangelink So, to resolve this, can I add something like the following to the "How to fix violations" section?

Or, validate user input by using sanitizers for [primitive type conversion](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/PrimitiveTypeConverterSanitizers.cs) and [XML encoding](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/TaintedDataAnalysis/XmlSanitizers.cs).

**Comment by Evangelink** [comment]
LGTM, I don't think that was your plan but don't refer directly to the classes as they might move.

**Comment by Mikejo5000** [comment]
OK, thanks. I guess there's no official reference docs for these types.

**Comment by Mikejo5000** [comment]
Updating. Doc should go live around noon PST.

**Comment by Evangelink** [comment]
@Mikejo5000 Sorry to bother you but looking at the doc for this rule I think it would be better to have either a table listing the sanitizers or to have a separate documentation page to refer too.

Here is the list I have extracted from the code (note that I didn't put the url link to the documentation for each method but it might be nice to do so).

### XML sanitizers
Microsoft.Security.Application.AntiXss.XmlAttributeEncode
Microsoft.Security.Application.AntiXss.XmlEncode
Microsoft.Security.Application.Encoder.XmlAttributeEncode
Microsoft.Security.Application.Encoder.XmlEncode
System.Web.Security.AntiXss.AntiXssEncoder.XmlAttributeEncode
System.Web.Security.AntiXss.AntiXssEncoder.XmlEncode

### Primitive type conversion
bool.Parse
bool.TryParse
byte.Parse
byte.TryParse
char.Parse
char.TryParse
short.Parse
short.TryParse
int.Parse
int.TryParse
long.Parse
long.TryParse
float.Parse
float.TryParse
double.Parse
double.TryParse
decimal.Parse
decimal.TryParse
System.DateTime.Parse
System.DateTime.TryParse
System.TimeSpan.Parse
System.TimeSpan.TryParse
System.Number.ParseInt32
System.Number.ParseInt64
System.Number.TryParseInt32
System.Number.TryParseInt64

**Comment by Mikejo5000** [comment]
No problem. Thanks! I'll re-open this for now and plan the updates.

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Closing this one in favor of dotnet/docs#24581
