### ISSUE TITLE
This page is half-baked.  Maybe finish it and include the TF31002 error that happen when trying to connect to an older TFS server.

### ISSUE THREAD

**Issue by jim-software** [MicrosoftDocs/visualstudio-docs#4997]
This page is half-baked.  Maybe finish it and include the TF31002 error that happen when trying to connect to an older TFS server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f31dd7-e676-aa47-cb11-8ad77412fb5a
* Version Independent ID: 6cce7a4b-8f62-610d-f75f-fafc7b4c444a
* Content: [Connect to projects in Team Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/connect-team-project?view=vs-2019#feedback)
* Content Source: [docs/ide/connect-team-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/connect-team-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by profexorgeek** [comment]
#assign: @LBynum77

**Comment by PRMerger6** [comment]
LBynum77 is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by TerryGLee** [comment]
@jim-software Thanks for your feedback. We've added a troubleshooting link that should be published live later this afternoon. @LBynum77 FYI on this follow-up.
