### ISSUE TITLE
The rule CA3147 doest not work correctly with AcceptVerbsAttribute attribute 

### ISSUE THREAD

**Issue by rezanid** [MicrosoftDocs/visualstudio-docs#4999]
This rule is not able to detect AcceptVerbsAttribute attribute and it only works with HttpGetAttribute and HttpPostAttribute attributes.

For example the following will give a false warning.
```csharp
    [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
    [ValidateAntiForgeryToken]
    public ActionResult Index() => View(GetModel());
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 207a37cd-a7c5-1d72-be83-f6707669d580
* Version Independent ID: 740d01fa-f6f2-c736-f7fa-3423734ebd46
* Content: [CA3147: Mark verb handlers with ValidateAntiForgeryToken - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca3147?view=vs-2019#feedback)
* Content Source: [docs/code-quality/ca3147.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca3147.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @dotpaul
* Microsoft Alias: **paulming**

**Comment by dotpaul** [comment]
Hi @rezanid, can you please open an issue in https://github.com/dotnet/roslyn-analyzers for this, and provide the warnings (with messages) you're not expecting?

**Comment by rezanid** [comment]
Oh sorry, I will do that.

Bests,
Reza.

On 26 Mar 2020, at 17:34, Paul Ming <notifications@github.com> wrote:

﻿

Hi @rezanid<https://github.com/rezanid>, can you please open an issue in https://github.com/dotnet/roslyn-analyzers for this, and provide the warnings (with messages) you're not expecting?

**Comment by WilliamAntonRohm** [comment]
@rezanid -- Reza, thank you for your feedback.

@dotpaul -- Paul, thank you for your suggestion.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
