### ISSUE TITLE
${repeated} does'nt work

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5000]
@fantasyhh commented on [Wed Mar 25 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/181)

Version:1.41.1
Commit:26076a
OS:Linux x64 4.15.0-88-generic

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [使用正则表达式 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

---

@srvbpigh commented on [Thu Mar 26 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/181#issuecomment-604201912)

Hello, @fantasyhh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, please ask @fantasyhh for further clarification and more context around their general task, and tell them that they may find answers here:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

If this is a product bug, ask them to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
