### ISSUE TITLE
Visual Studio Visualizer 32-bit 64-bit or ANY?

### ISSUE THREAD

**Issue by djmarcus1** [MicrosoftDocs/visualstudio-docs#5002]
Documentation should specify whether dll must be 32-bit or 64-bit or ANY

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0470059-27e3-58a0-155e-84fbaefae158
* Version Independent ID: 95c9afb2-32f3-945b-9381-9f711179c77d
* Content: [How to: Install a Visualizer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2019#feedback)
* Content Source: [docs/debugger/how-to-install-a-visualizer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-install-a-visualizer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@WardenGnaw Andrew, since VS is 32-bit, should the DLL be compiled for x86, or is Any CPU OK?

**Comment by Mikejo5000** [comment]
I asked about this:
The Debugger Side DLL has to be either Any CPU or 32-bit. The debuggee side will depend on what their debuggee process should be. Generally, it would be best if both were Any CPU.

I'll update the doc.
