### ISSUE TITLE
What are the valid target name format

### ISSUE THREAD

**Issue by jhv2017kam** [MicrosoftDocs/visualstudio-docs#5012]
Are there any restriction on the characters in the name e.g. can I use a name like mycompany.mytarget or should I add an xmlns:myxmlns="mycompany.com" and use myxmlns:mytarget

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2edf4455-765e-3107-5b5b-11162a965b65
* Version Independent ID: 37110ada-36c1-f545-d0e0-1c5bacbf71ab
* Content: [Target Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/target-element-msbuild?view=vs-2019#feedback)
* Content Source: [docs/msbuild/target-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/target-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@jhv2017kam -- thank you for your question.  You may find answers here:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- please look into this issue.

**Comment by rainersigwald** [comment]
A target name may contain any character except `$@()%*?.`.

https://github.com/microsoft/msbuild/blob/2d82e1a861d890fce68c8e2d42b569e5bbaf5687/src/Shared/XMakeElements.cs#L36

But I don't understand the other part of the question

> should I add an xmlns:myxmlns="mycompany.com" and use myxmlns:mytarget

This is not valid in MSBuild; elements must be in the MSBuild namespace or no namespace.
