### ISSUE TITLE
Missing help on "Show file health indicator"

### ISSUE THREAD

**Issue by franji1** [MicrosoftDocs/visualstudio-docs#5021]
Missing help on "Show file health indicator" checkbox at the end of the Display list (after "Show structure guide lines").  I'm sure it's on your TODO list, but FYI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.General)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by LBynum77** [comment]
franji1, can you provide more details?  I'm not seeing the "Show file health indicator" checkbox on the Tools -> Options -> Text Editor -> General dialog.

**Comment by LBynum77** [comment]
#assign  LBynum77

I'm working on a fix, I was inadvertently looking at an older version of VS from other investigations.

**Comment by franji1** [comment]
Here’s the details from Help->About:

Microsoft Visual Studio Professional 2019
Version 16.4.6
VisualStudio.16.Release/16.4.6+29905.134
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Visual C++ 2019   00435-60000-00000-AA313
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.4.462.24200
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.4.462.24200
Azure App Service Tools v3.0.0

C# Tools   3.4.1-beta4-20120-08+fa984e0202af4480c0273032da49cbbdeb32c582
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Visual Basic Tools   3.4.1-beta4-20120-08+fa984e0202af4480c0273032da49cbbdeb32c582
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.4.0-beta.19556.5+e7597deb7042710a7142bdccabd6f92b0840d354
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Mark Franjione
Sr. Software Engineer
Host Engineering, Inc.

**Comment by PRMerger8** [comment]
Only Microsoft employees can manage issues via commenting in this repo.

**Comment by LBynum77** [comment]
Thanks Franji1, and sorry for the confusion on my part.  This issue has been fixed.
