### ISSUE TITLE
MSBuild conditions documentation should clarify case-sensitivity

### ISSUE THREAD

**Issue by MrTrillian** [MicrosoftDocs/visualstudio-docs#5023]
The page doesn't mention whether operators ==, != and all others are case-sensitive or not. They appear not to be, but this should be clarified.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019&source=docs#feedback)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@MrTrillian -- Tristan, thank you for your feedback.

@ghogen -- Gordon, please look at the above-metioned PR.
