### ISSUE TITLE
"Source link specification" link is dead

### ISSUE THREAD

**Issue by logical-intent** [MicrosoftDocs/visualstudio-docs#5027]
The link takes you to a page that says, "This document has moved to https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md".  That link, in turn, just gives a 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c524aa1d-eec4-d776-8346-dfdc632eec76
* Version Independent ID: c0f65c4f-6369-10ce-5edc-0ab5fbae736a
* Content: [General, Debugging, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Debugger.General)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/debugger/general-debugging-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/general-debugging-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by poppastring** [comment]
Thanks for submitting the issue @logical-intent ! A fix is on the way. cc @Mikejo5000

**Comment by Mikejo5000** [comment]
@poppastring Fix should go live around 4. Mark, please go ahead and close this one for proper visibility. Thx!

**Comment by poppastring** [comment]
#please-close
