### ISSUE TITLE
Not Coordinated

### ISSUE THREAD

**Issue by morbius1st** [MicrosoftDocs/visualstudio-docs#5028]
the ProjectTypeTag list of built-in tags does not include CSharp but you used this in your example.  you do not have documentation for the new tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f66438c2-1bb4-f5f9-12f8-64c25f5460ce
* Version Independent ID: 5e9669ca-e652-1459-1dd7-542249a9d237
* Content: [Add or edit tags on project templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-tags?view=vs-2019)
* Content Source: [docs/ide/template-tags.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-tags.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @minsa110
* Microsoft Alias: **somin**

**Comment by WilliamAntonRohm** [comment]
@morbius1st -- Jeff, thank you for your feedback.  Please clarify your concern.  See https://docs.microsoft.com/en-us/visualstudio/ide/template-tags?view=vs-2019#built-in-tags.

**Comment by morbius1st** [comment]
The written verbiage versus the last example.  The written description directly above the last example identifies built-in tags with these headings: "Language", "Platform", and Project Type" However, the tags, per the example, are LanguageTag, PlatformTag, and ProjectTypeTag.  This is confusing because there is also a "ProjectType" (no "Tag" suffix).

**Comment by WilliamAntonRohm** [comment]
@minsa110 -- Soojin, please review [private PR 6418](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6418).
