### ISSUE TITLE
"Debug this application with the selected permission set" is missing in visual studio 2019 version 16.5.1

### ISSUE THREAD

**Issue by naji-makhoul** [MicrosoftDocs/visualstudio-docs#5029]
VS 2013, Update 5 - Advanced settings
![image](https://user-images.githubusercontent.com/5232373/77910993-bece2d80-7298-11ea-9f4d-6dd92a721190.png)

VS 2019 ,version :16.5.1- Advanced settings
![image](https://user-images.githubusercontent.com/5232373/77910808-6bf47600-7298-11ea-88e5-e9c3c55e48c4.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ac04b0c-c54e-ce1c-6099-bd4aef558975
* Version Independent ID: a558f829-ccc3-b726-d92c-6dfc010d457b
* Content: [Debug ClickOnce application with restricted permissions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-debug-a-clickonce-application-with-restricted-permissions?view=vs-2019)
* Content Source: [docs/deployment/how-to-debug-a-clickonce-application-with-restricted-permissions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-debug-a-clickonce-application-with-restricted-permissions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
I'll take a look. It looks like this doc needs to be removed from VS 2019

**Comment by naji-makhoul** [comment]
But how i can debug with clickonce?? Its not working in visual studio 2019!

**Comment by Mikejo5000** [comment]
I will ask about this. In the meantime, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by naji-makhoul** [comment]
https://developercommunity.visualstudio.com/content/problem/977753/how-to-debug-clickonce-winform-application-in-visu.html

**Comment by dreddy-work** [comment]
@naji-makhoul, we removed this feature from VisualStudio sometime back.  Docs will be updated soon to reflect it. Meanwhile, can you please help the exact scenario that is blocked for you?

**Comment by naji-makhoul** [comment]
@dreddy-work ,i have winform and i publish it twice
1. published and running with clickonce
2.copy release files to server and the client can run the applciation with rdp(remote desktop/remote app)

i want to check if the app running with clickonce if "Enable ClickOnce security setting" is checked in **debug mode**

if the checkbox is not checked, with "Deployment.Application.ApplicationDeployment.IsNetworkDeployed" it will return false and its ok , but if "enable clickonce" is checked need to return true.

after publish the application the Deployment.Application.ApplicationDeployment.IsNetworkDeployed work as expected, and returns true allways if the app running and published with clickonce and false if it running from rdp

with visual studio 2013.. its works fine, and its stop working after i moved to visual studio 2019

**Comment by Mikejo5000** [comment]
Removing this topic in MicrosoftDocs/visualstudio-docs-pr#6381

**Comment by naji-makhoul** [comment]
any updates ?

**Comment by Mikejo5000** [comment]
Topic has been removed. Closing this doc issue.
