### ISSUE TITLE
Where is this information printed

### ISSUE THREAD

**Issue by comarius** [MicrosoftDocs/visualstudio-docs#503]
Note the address where the crash occurred. ?!?!?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 327e022e-4af2-68dd-c57a-2b9d790a63b9
* Version Independent ID: 62b873c1-1cf6-6b7f-e8ab-d9b9963e4ee0
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-find-which-dll-your-program-crashed-in)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/how-to-find-which-dll-your-program-crashed-in.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@comarius If there is no exception thrown that shows the address, the DLL might have been built without debug information.

**Comment by Mikejo5000** [comment]
Adding suggestions for when the error message does not include the address.

**Comment by Mikejo5000** [comment]
Additional info published
