### ISSUE TITLE
Text in comments distorted.

### ISSUE THREAD

**Issue by Sunburst275** [MicrosoftDocs/visualstudio-docs#5030]
Sometimes the Text in the comment blocks is fat and distorted. How to fix this issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d87634e-4198-6552-6e5c-c81adf5c171c
* Version Independent ID: feff5377-0ce1-f08e-ed65-74c760525cc1
* Content: [How to: Add Comments to Class Diagrams (Class Designer) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/class-designer/how-to-add-comments-to-class-diagrams?view=vs-2019)
* Content Source: [docs/ide/class-designer/how-to-add-comments-to-class-diagrams.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/class-designer/how-to-add-comments-to-class-diagrams.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Sunburst275 -- thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
