### ISSUE TITLE
Text repeated

### ISSUE THREAD

**Issue by user2150** [MicrosoftDocs/visualstudio-docs#5031]
Section "Use the InitialTargets attribute"
The sentence
"The InitialTargets attribute of the Project element specifies a target that will run first, even if targets are specified on the command line or in the DefaultTargets attribute."
repeated twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 278adf26-4c90-922b-bc0b-3a8b59e4ad31
* Version Independent ID: e79bde47-f63e-30da-bd05-ae80c3d78bed
* Content: [How to: Specify Which Target to Build First - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-specify-which-target-to-build-first?view=vs-2019#feedback)
* Content Source: [docs/msbuild/how-to-specify-which-target-to-build-first.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-specify-which-target-to-build-first.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@user2150 -- thank you for catching that.

@ghogen -- please review [private PR 6359](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6359).

**Comment by ghogen** [comment]
Thanks, this fix should be published in a few hours.
