### ISSUE TITLE
Text repeated

### ISSUE THREAD

**Issue by user2150** [MicrosoftDocs/visualstudio-docs#5032]
Section "Use the Import element"
The text
"The Import element is used to insert one project file into another project file. The project file that is being imported must be a valid MSBuild project file and contain well-formed XML. The Project attribute specifies the path to the imported project file. For more information on the Import element, see Import element (MSBuild)."
is repeated twice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9785cadd-f789-523d-73e1-2e2ad7ee6037
* Version Independent ID: a3787414-4a5a-9a18-bcbe-6fd0813a7f41
* Content: [How to: Use the Same Target in Multiple Project Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-the-same-target-in-multiple-project-files?view=vs-2019#feedback)
* Content Source: [docs/msbuild/how-to-use-the-same-target-in-multiple-project-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-use-the-same-target-in-multiple-project-files.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@user2150 -- thank you for catching that typo as well.

@ghogen -- please review [private PR 6360](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6360).
