### ISSUE TITLE
CA1045 update documentation to mention configurability

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#5033]
With PR https://github.com/dotnet/roslyn-analyzers/pull/3366 the documentation needs to be updated to add the `api_surface` configurability section as it is done for https://docs.microsoft.com/fr-fr/visualstudio/code-quality/ca1000?view=vs-2019#configurability

**Comment by Mikejo5000** [comment]
Updating doc.

**Comment by Mikejo5000** [comment]
@Evangelink Is the configurability new starting in FxCop 3.0.0?
