### ISSUE TITLE
CA1047 update doc to mention configurability

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#5034]
With PR https://github.com/dotnet/roslyn-analyzers/pull/3457 the documentation needs to be updated to add the `api_surface` configurability section as it is done for https://docs.microsoft.com/fr-fr/visualstudio/code-quality/ca1000?view=vs-2019#configurability

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by Evangelink** [comment]
@Mikejo5000 I can see the ticket closed but I cannot find the associated PR and as far as I can see the doc page is not (yet) updated.

**Comment by Mikejo5000** [comment]
@Evangelink Right, We are required to do PRs on the private repo, so the link to the PR can't be seen. The linked issue gets auto-closed when the PR is merged to master. I see that the change isn't live yet, it should go live by noon today (we publish twice daily). Please let me know if we need any changes.
