### ISSUE TITLE
Update doc for CA1005 to mention configurability

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#5035]
With PR https://github.com/dotnet/roslyn-analyzers/pull/3455 the documentation needs to be updated to add the `api_surface` configurability section as it is done for https://docs.microsoft.com/fr-fr/visualstudio/code-quality/ca1000?view=vs-2019#configurability

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by Evangelink** [comment]
@Mikejo5000 I can see the ticket closed but I cannot find the associated PR and as far as I can see the doc page is not (yet) updated.
