### ISSUE TITLE
Update doc for CA1806 to mention new case

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#5036]
With PR https://github.com/dotnet/roslyn-analyzers/pull/3083 the rule will now start reporting on ignored disposable objects. The cause bullet points need to be updated accordingly.

**Comment by Mikejo5000** [comment]
Looks like dotnet/roslyn-analyzers#3083 was closed as partially redundant.

**Comment by Evangelink** [comment]
Yes you are right, I forgot to close this ticket! Thanks
