### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by AnushkaMishra** [MicrosoftDocs/visualstudio-docs#5044]
https://dev.office.com/docs/add-ins/overview/office-add-ins - link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97e75d6-dc3e-800e-7cff-d097023df034
* Version Independent ID: 89401b4f-16db-66ab-512c-cce9f949ac10
* Content: [How to: Install Office primary interop assemblies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-office-primary-interop-assemblies?view=vs-2019#feedback)
* Content Source: [docs/vsto/how-to-install-office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-install-office-primary-interop-assemblies.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@AnushkaMishra -- thank you for your feedback.  That link appears to be fixed. 
 The new destination is [here](https://docs.microsoft.com/en-us/office/dev/add-ins/).
