### ISSUE TITLE
ActiveDocument.Editor is null and other issues

### ISSUE THREAD

**Issue by craigbrown** [MicrosoftDocs/visualstudio-docs#5045]
A lot of this document seems to be out of date.

I followed all the steps, but it doesn't work since the Editor property of ActiveDocument (see the code snippets in steps 13 and 14) is always null. I think this could be related to the fact that VS for Mac has been given a new text editor since this document was published.

I managed to get it work with the following changes:
In step 9, at the top of InsertDateHandler.cs add the line:
```cs
using Microsoft.VisualStudio.Text.Editor;
```
and remove the line:
```cs
using MonoDevelop.Ide.Gui;
```

In step 13, change the line inside the Update method to:
```cs
info.Enabled = IdeApp.Workbench.ActiveDocument?.GetContent<ITextView>() != null;
```

In step 14, change the Run method to:
```cs
protected override void Run()
{
    // Generate a new date
    var date = DateTime.Now.ToString();

    // Get the VS text view
    var textView = IdeApp.Workbench.ActiveDocument.GetContent<ITextView>();

    // Get the caret position
    var caretPosition = textView.Caret.Position.BufferPosition.Position;

    // Insert the date at the caret position
    textView.TextBuffer.Insert(caretPosition, date);
}
```

Another change which is needed which is currently referenced in another open issue on this document - in step 5 the name of the template has been changed from 'Xamarin Studio Addin' to 'IDE Extension'.

Also, in step 3, the name of the extension you need to install is now called 'AddinMaker' - i.e. the space has been removed.

Hope this helps!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc52ec0c-7053-51d0-c576-2d8ce60cf198
* Version Independent ID: 8bb8155e-d615-5ea8-cd83-3820f8484b43
* Content: [Extending Visual Studio for Mac Walkthrough - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/extending-visual-studio-mac-walkthrough?view=vsmac-2019#feedback)
* Content Source: [mac/extending-visual-studio-mac-walkthrough.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/extending-visual-studio-mac-walkthrough.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-sdk**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by heiligerdankgesang** [comment]
@WilliamAntonRohm this is addressed in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6674

This is not a supported scenario in Visual Studio 2019 for Mac.

**Comment by WilliamAntonRohm** [comment]
@heiligerdankgesang -- thank you for your assistance.

@craigbrown -- the updates are now being reviewed and should be live in a day or so.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by tuyen-vuduc** [comment]
@WilliamAntonRohm Any updates here?

**Comment by WilliamAntonRohm** [comment]
@tuyen-vuduc -- Tuyen, thank for your followup.

@heiligerdankgesang -- Dominic please look into [private PR 7101](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7101).

**Comment by heiligerdankgesang** [comment]
PR was approved, thanks. 

@tuyen-vuduc please be advised that this is not a supported scenario in Visual Studio 2019 for Mac.

#please-close
