### ISSUE TITLE
Publishment not working

### ISSUE THREAD

**Issue by dimitrov-d** [MicrosoftDocs/visualstudio-docs#5046]
I have used this same tutorial to publish an ASP.NET MVC app. The static pages work, but the ones where the database access is required throw an error which says "An error occurred while processing your request." and no details are provided. How can I fix this?

**Comment by WilliamAntonRohm** [comment]
@dimitrov-d -- Damjan, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.  

Meanwhile, here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by dimitrov-d** [comment]
I was following [this](https://docs.microsoft.com/en-us/aspnet/core/tutorials/publish-to-azure-webapp-using-vs?view=aspnetcore-3.1) tutorial and it was my intention to post this there. 

I am using ASP.NET Core 4.7, .NET core 3.1 and Visual Studio 2019 for mac 8.5

@WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@dimitrov-d -- Damjan, thank you for clarifying.  This repo is solely for documentation issues, with limited support options.  Please see my previous links.
