### ISSUE TITLE
How does Code Cleanup relate to Severity?

### ISSUE THREAD

**Issue by GregWoods** [MicrosoftDocs/visualstudio-docs#5047]
for example:
.editorconfig
csharp_using_directive_placement = outside_namespace:warning

Code cleanup does nothing. Does severity affect which rules are applied?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faebd126-53cd-1a98-bf75-38225933b0f2
* Version Independent ID: 4340fcba-6779-68d2-6c51-2ae37123dc26
* Content: [Code style options and code cleanup - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#feedback)
* Content Source: [docs/ide/code-styles-and-code-cleanup.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-styles-and-code-cleanup.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@GregWoods -- Greg, thank you for your question.  If this is relevant to your issue, the article states:

> Rules configured with a severity of None don't participate in code cleanup but can be individually applied via the Quick Actions and Refactorings menu.

Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 


I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
