### ISSUE TITLE
IIS

### ISSUE THREAD

**Issue by lks-rst** [MicrosoftDocs/visualstudio-docs#5050]
The overall article is great but, how can I deploy the react application on IIS?
Every time I've tried to do this the browser shows up a white screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#feedback)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
IIS deploy is somewhat out of scope for these docs at present. I suspect you either need to install the Node.js runtime correctly on IIS, and/or point IIS to server.js as the startup file. For the latter, you may need to include a web.config file in your root directory.

For example, with Azure Pipelines, I saw that the build process was putting the app into an 's' subfolder, so I needed to edit the generated web.config file with this:

WebConfigParameters:
'-Handler
iisnode -NodeStartFile s/server.js -appType node' 

This might be helpful, though it's focused on Azure with IIS on Windows: https://github.com/Azure/iisnode

**Comment by Mikejo5000** [comment]
Maybe this would be helpful, too:
https://hostek.com/blog/node-js-applications-on-windows-iis/

**Comment by Mikejo5000** [comment]
Closing as external for JS/TS docs
