### ISSUE TITLE
Unable to see return values of method calls

### ISSUE THREAD

**Issue by dannyt-git** [MicrosoftDocs/visualstudio-docs#5051]
I have a very simple program that does this:
std::string a("hello");
assert(a.length() != 0);

When I step over the assert, Visual studio's Autos window doesn't show me the return value of length() as described above. Is there any setting that controls viewing return values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba01381-dfb4-7830-e86c-1ee94f346b03
* Version Independent ID: 11513787-4812-9d2d-3288-82d3dc73012d
* Content: [Inspect variables - Autos and Locals windows - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/autos-and-locals-windows?view=vs-2019#feedback)
* Content Source: [docs/debugger/autos-and-locals-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/autos-and-locals-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
You used F10? When I press F10 while paused on the assert line of code, I do see the return value for length.

![image](https://user-images.githubusercontent.com/11948536/78190553-14394480-7429-11ea-8c55-7c3cd7f35e73.png)

**Comment by Mikejo5000** [comment]
You might also try $returnvalue in the Watch window.
https://docs.microsoft.com/en-us/visualstudio/debugger/pseudovariables?view=vs-2019

**Comment by dannyt-git** [comment]
Hi Mike,

Yep I used F10 while at the assert. I have two dev boxes I'm using and on one machine it works like your screenshot. On the other dev box, it doesn't show up at all. 

On the problem box, I tried uninstalling, rebooting, and installing again. Then on the working box, I used the Visual Studio installer to export its configuration and then importing the configuration on the problem box. It's still not working. 

Does it have to do with symbols or anything? I know I didn't change many default settings in the working box.

**Comment by dannyt-git** [comment]
I tried the $returnvalue and I get a message saying it's undefined.
![image](https://user-images.githubusercontent.com/63021667/78191215-69298a80-742a-11ea-8c0e-e7824cbfcc3d.png)

**Comment by Mikejo5000** [comment]
Yes, it sounds like a setting or environment issue.
Not sure it's relevant, but I would make sure the following is enabled in Tools > Options:
**Enable property evaluation and other implicit function calls**

please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
You can also use Tools > Import and Export Settings to (1) reset your settings, and (2) export the settings from your good box, and import to your other box.

**Comment by Mikejo5000** [comment]
By the way, you should make sure that when you hover over 'a' while debugging, and that the size property is '5'. In other words, make sure the code is not actually returning undefined on the machined where it's not working correctly. If the C++ code is not working right, that sounds like a C++ app/property config issue, rather than the debugger. That might be a different setting in the property pages.

**Comment by dannyt-git** [comment]
Hi Mike,

I tried your last two suggestions and still no go. I do see that size is 5 when I hovered over the string object.
![image](https://user-images.githubusercontent.com/63021667/78193481-82810580-742f-11ea-916f-f52d2922cb93.png)

I just finished using the Report a Problem tool and now just waiting for a response.

**Comment by Mikejo5000** [comment]
Closing as a product issue. It doesn't appear this has doc impact.
