### ISSUE TITLE
Why can't I activate benefit

### ISSUE THREAD

**Issue by AshleyYang25** [MicrosoftDocs/visualstudio-docs#5054]
I'm a MS FTE and try to activate my 150$ Azure benefit, but got this:
![image](https://user-images.githubusercontent.com/22438762/78247057-c6056d80-751c-11ea-82aa-bf716c616ac7.png)
Then sign in Azure portal with the email used in activating, can't see any subscription there.
Do you have any idea?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73356ab4-87d3-09fb-557f-4533fc133156
* Version Independent ID: ce5ed4b4-1406-9126-832a-ddcdc5cf25bc
* Content: [Microsoft Azure benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure#feedback)
* Content Source: [subscriptions/vs-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@AshleyYang25 - Thanks for your report.  I'm going to investigate this and get back to you.

**Comment by evanwindom** [comment]
@AshleyYang25  - Since you're internal, let's take this out of GitHub and work through it internally.  I will email you directly.

**Comment by evanwindom** [comment]
#please-close
