### ISSUE TITLE
Infinitivo vs imperativo

### ISSUE THREAD

**Issue by DavidPrio** [MicrosoftDocs/visualstudio-docs#5056]
Paso 1: Asegurarse de que el equipo está listo para Visual Studio
Quizás debería ser "Asegúrese" en vez de "asegurarse" - https://docs.microsoft.com/es-es/visualstudio/install/install-visual-studio?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd4d05c-4aa3-0376-f3a1-b0ea0793f482
* Version Independent ID: 7f1ff943-61b0-60e1-9ca3-d4a84bfdb068
* Content: [Install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by srvbpigh** [comment]
Hello, @DavidPrio
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @DavidPrio
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/visualstudio-docs.es-es #35](https://github.com/MicrosoftDocs/visualstudio-docs.es-es/issues/35) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hola, @DavidPrio 

Apreciamos enormemente sus comentarios.

Debido a que sus comentarios son específicos a la localización de la documentación, hemos movido este problema al repositorio de localización correspondiente y cerraremos este. 

Revise el estado de este problema aquí https://github.com/MicrosoftDocs/visualstudio-docs.es-es/issues/36

Atentamente,

Equipo internacional de Microsoft Docs

**Comment by CeciAc** [comment]
#please-close
