### ISSUE TITLE
Ambiguous property!

### ISSUE THREAD

**Issue by Shvan11** [MicrosoftDocs/visualstudio-docs#5057]
Great article, but one thing not very obvious for me in this line of code:
` <Grid x:Name="newOrderGrid" Grid.Row="1" HorizontalAlignment="Left" VerticalAlignment="Top" Margin="5" DataContext="{Binding Path=newOrder, Mode=TwoWay}" Visibility="Collapsed" Background="LightGreen">`
What does "newOrder" in the above code refer to?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c0fa43-0ca5-9c86-f8c4-4b3eb7176250
* Version Independent ID: bb93e3ff-0d52-9e93-c3a8-545b16f03a30
* Content: [Simple data application with WPF and Entity Framework 6 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2019)
* Content Source: [docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Shvan11 -- thank you for the compliment.  Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Shvan11** [comment]
@WilliamAntonRohm Dear Sir
The article is not correct, I exactly followed everything step by step but I was not able to add new order because the customer ID property was not populated. The problem is when you click on new order button an order object is instantiated, however when you click the commit button another object is instantiated not related to first one so customer ID property of the order object is not populated.

**Comment by WilliamAntonRohm** [comment]
@Shvan11 -- thank you for clarifying and for your research.

@ghogen -- please look into this issue.

**Comment by ghogen** [comment]
@Shvan11 So, it looks like newOrder was declared in a couple of different methods, so that changes to one were not carried over to the other.  I changed the logic here, so that newOrder is only used in one method. These changes should appear live within a day or so. It seems to work now for me, but if you test it and find any issues, please reopen or enter a new issue.
