### ISSUE TITLE
Updating the location in preferences for enabling word wrap

### ISSUE THREAD

**Issue by jmatthiesen** [MicrosoftDocs/visualstudio-docs#5059]
This page currently says "To enable word wrap, navigate to Visual Studio &gt; Preferences &gt; Text Editor &gt; New Editor &gt; Word Wrap"; this should change to say "To enable word wrap, navigate to Visual Studio &gt; Preferences &gt; Text Editor &gt; Word Wrap"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9cf8d28f-b344-0fc3-1c19-97959af7ee96
* Version Independent ID: adf72a5e-9073-84e4-eb57-100bf71adaa2
* Content: [Source Editor - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/source-editor?view=vsmac-2019#feedback)
* Content Source: [mac/source-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/source-editor.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @cobey
* Microsoft Alias: **cobey**

**Comment by WilliamAntonRohm** [comment]
@cobey -- Cody, please review this change in [private PR 6377](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6377).
