### ISSUE TITLE
Updating the note about Visual Studio for Mac and word wrap

### ISSUE THREAD

**Issue by jmatthiesen** [MicrosoftDocs/visualstudio-docs#5060]
This document states that Visual Studio for Mac doesn't support word wrap. As of the v8.1 release from last year, word wrap is an option now. You can refer to this doc for more details: https://docs.microsoft.com/en-us/visualstudio/mac/source-editor?view=vsmac-2019#feedback

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00e3e8d0-48c3-3df6-8aeb-acd9624ffcd5
* Version Independent ID: 13f5da30-9f06-236f-4110-b6a172c52d1f
* Content: [Word wrap - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- Terry, please review [private PR 6378](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6378).

**Comment by WilliamAntonRohm** [comment]
@jmatthiesen -- Jordan, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
