### ISSUE TITLE
Typo: Redundancy in "allocation type and and functions" VS 2019 16.5 release notes

### ISSUE THREAD

**Issue by oneparameter** [MicrosoftDocs/visualstudio-docs#5061]
**Page**: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes
**Section**: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#debugging-1

**Sentence containing error**: 

> First, the backtrace view has been moved to a separate panel to more easily distinguish between allocation type **_and and_** functions called

As you can see the second 'and' is redundant, marked by the bold styling.

**Comment by TerryGLee** [comment]
@JacquelineWiddis FYI.

**Comment by JacquelineWiddis** [comment]
This fix will go live with our next servicing release notes.

**Comment by WilliamAntonRohm** [comment]
@TerryGLee, @JacquelineWiddis -- thank you for addressing this issue.
