### ISSUE TITLE
Warning for private code

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/visualstudio-docs#5063]
How code this is a warning for a private code? An informational suggestion to improve the code - maybe. Forcing developers to change private methods to static and refactor all call to the method is insane.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73190016-ddef-0e31-ffb2-d72d551e0d0b
* Version Independent ID: 44822112-d0c7-3f59-75c0-3e81f1ee57d7
* Content: [CA1822: Mark members as static - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822?view=vs-2019)
* Content Source: [docs/code-quality/ca1822.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1822.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@jozefizso -- Jozef, thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
