### ISSUE TITLE
Status column needs updating along with graphic

### ISSUE THREAD

**Issue by gordonwatts** [MicrosoftDocs/visualstudio-docs#507]
In VS2017 the window no longer looks like above. Further, I think "Awaiting" has replaced the "Waiting" in the status column. There is also now a context menu item called "Switch to frame".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1b431a-4afc-27ae-b2d9-0d1299eba257
* Version Independent ID: 72c6c954-6989-4ca7-1db4-38d6ac3f3c40
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-tasks-window)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/using-the-tasks-window.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Article needs a refresh

**Comment by Mikejo5000** [comment]
Working on this one
