### ISSUE TITLE
A confusing sentence

### ISSUE THREAD

**Issue by pstricks-fans** [MicrosoftDocs/visualstudio-docs#5070]
What does "Assume there's a bug in the method under test and the Debit method doesn't even throw an ArgumentOutOfRangeException never mind output the correct message with the exception. " mean?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* Content: [C# unit test tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2019)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks! I'll take a look at this.

**Comment by pstricks-fans** [comment]
I see now. "never mind" --> "let alone"
