### ISSUE TITLE
Information missing for "Run the application", step 2.

### ISSUE THREAD

**Issue by mloutris** [MicrosoftDocs/visualstudio-docs#5073]
In "Run the application", the text of step 2 is:
    **Right-click the project in Solution Explorer and select Properties. ** 
    **Then select the Debug tab and set the Port Number property to 4449.** 
The (potentially) missing step is, after selecting the Debug tab, the user may need to set 'Lauch mode:' to 'Web launcher' to be able to access the 'Port number: field. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db7f9ca8-40ce-6b6d-15df-bbb3b6829430
* Version Independent ID: 3dd10fed-b3d3-269c-623e-00031a81ed83
* Content: [Quickstart: use Visual Studio to create a Python web app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-python?view=vs-2019&toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fpython%2Ftoc.json%3Fview%3Dvs-2019&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2F_breadcrumb%2Ftoc.json%3Fview%3Dvs-2019#feedback)
* Content Source: [docs/ide/quickstart-python.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-python.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Thank you for your input. We agree and have added this work to our planning board. We will go ahead and close this issue, but continue to track the work internally.  If you think this issue should remain open, please reopen it with a comment explaining why. Tag me for visibility.

We appreciate your investment in our content.
