### ISSUE TITLE
<language>/Syntaxes?

### ISSUE THREAD

**Issue by ErikBongers** [MicrosoftDocs/visualstudio-docs#5074]
The %userprofile%\.vs\Extensions folder does not exist on my machine. (actually, even the .vs does not exist)
I assume I can just create it? 
If so, this might be added to page.

Also the \Syntaxes folder should be inside the &lt;language&gt; folder? 
If so, perhaps write "&lt;language&gt;\Syntaxes", to avoid confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* Content: [Add editor support for other languages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages?view=vs-2019#feedback)
* Content Source: [docs/ide/adding-visual-studio-editor-support-for-other-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ErikBongers -- Erik, thank you for your feedback.  The article states:
> In Windows, %userprofile% resolves to the path: c:\Users\<user name>. If the Extensions folder does not exist on your system, you will need to create it. If the folder already exists, it will be hidden.

The \<language name>, \Syntaxes, and \Snippets subfolders are apparently siblings under the Extensions folder.
