### ISSUE TITLE
Try the Extension samples 

### ISSUE THREAD

**Issue by ErikBongers** [MicrosoftDocs/visualstudio-docs#5075]
Hi everyone,
The extension samples: https://github.com/microsoft/VSSDK-Extensibility-Samples
...have 2 usefull exampes:
1: OOK! language integration (not using textmate, but apparently more functionality)
2: a Textmate example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* Content: [Add editor support for other languages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages?view=vs-2019)
* Content Source: [docs/ide/adding-visual-studio-editor-support-for-other-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ErikBongers -- Erik, thank you for your suggestions.

@TerryGLee -- Terry, please review [private PR 6385](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6385).
