### ISSUE TITLE
"This level" of full-application profiling

### ISSUE THREAD

**Issue by zooba** [MicrosoftDocs/visualstudio-docs#5076]
Could you clarify exactly what "this level" means?

I suspect it means that you can't start/stop profiling while running, so you always collect data for the whole process lifetime, but it's a little vague and could be interpreted differently.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399822f9-b83b-a607-4310-a7f496cf1f27
* Version Independent ID: c1300996-f8f4-e297-993a-1d614efe7e79
* Content: [Measure performance of Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/profiling-python-code-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/profiling-python-code-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/profiling-python-code-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@zooba -- Steve, thank you for your feedback.

@JoshuaPartlow -- Joshua, please review [private PR 6384](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6384).
