### ISSUE TITLE
The test code screenshot for NUnit is the code of MSTest

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5078]
@SCHQ commented on [Sat Apr 04 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/182)

The test code screenshot for NUnit is the code of MSTest

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 107f3c03-dac2-0226-d5c1-f2f49daa413d
* Version Independent ID: aaf80310-28eb-462b-d4f1-6b97a8abe260
* Content: [单元测试入门 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/test/getting-started-with-unit-testing?view=vs-2019#feedback)
* Content Source: [docs/test/getting-started-with-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/test/getting-started-with-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

---

@srvbpigh commented on [Sat Apr 04 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/182#issuecomment-609021930)

Hello, @SCHQ
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Mikejo5000** [comment]
Looks like the last screenshot in the doc should be NUnit.

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by Mikejo5000** [comment]
Fixed now in en-us
