### ISSUE TITLE
Multi-File Support for the Boost Test Adapter

### ISSUE THREAD

**Issue by ThatWileyGuy** [MicrosoftDocs/visualstudio-docs#509]
Could someone help me figure out how this would work with multiple files?

The only way I've found to get it to build without a pile of multiple definition errors is to have two files like this:
```
#define BOOST_TEST_MODULE TestModule
#include <boost/test/unit_test.hpp>

BOOST_AUTO_TEST_SUITE(Thing1)

BOOST_AUTO_TEST_CASE(Thing1Test)
{
  BOOST_CHECK_EQUAL(1, 1);
}

BOOST_AUTO_TEST_SUITE_END()
```

```
#include <boost/test/unit_test.hpp>

BOOST_AUTO_TEST_SUITE(Thing2)

BOOST_AUTO_TEST_CASE(Thing2Test)
{
  BOOST_CHECK_EQUAL(2, 2);
}

BOOST_AUTO_TEST_SUITE_END()
```

This builds successfully, but test discovery shows this:
```
[2018-02-01 21:13:52 Informational] ------ Discover test started ------
[2018-02-01 21:13:53 Informational] Logger initialized. Logging to C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\EXTENSIONS\5RESBQJP.LGW\BoostTestAdapter.dll.log
[2018-02-01 21:13:53 Warning] Could not locate debug symbols for 'C:\Users\wiley\Documents\Visual Studio 2017\Projects\PathPlannerWork\Debug\StepperPRUTests.exe'. To make use of '--list_content' discovery, ensure that debug symbols are available or make use of '<ForceListContent>' via a .runsettings file.
[2018-02-01 21:13:53 Informational] ========== Discover test finished: 0 found (0:00:00.8650724) ==========
```

But on the other hand, I can run it from the command line:
```
C:\Users\wiley\Documents\Visual Studio 2017\Projects\PathPlannerWork\Debug>StepperPRUTests.exe --list_content
Thing2*
    Thing2Test*
Thing1*
    Thing1Test*
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45fbddc-51f2-1c42-eaf2-f78e6220a9e7
* Version Independent ID: 1ce72223-80ab-651a-40f3-dc8112b2a3cf
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/test/how-to-use-boost-test-for-cpp.md)
* Service: unspecified

**Comment by gewarren** [comment]
@mikeblome can you ask someone from the product team about this?

**Comment by nickuhlenhuth** [comment]
Hi @ThatWileyGuy,
If you are using the Boost dynamic library, make sure you are using [Visual Studio 2017 15.6 Preview 2 or higher](https://www.visualstudio.com/vs/preview/). We didn't have dynamic support before then.
If you are using the static library, we have [documentation on using Boost.Test static library](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp).
Hope that helps!
Nick
