### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by HopWorks** [MicrosoftDocs/visualstudio-docs#5091]
Your link to Visual Studio 2010 Tools for Office runtime download is broken. This page is useless because you cannot use it to find vstor_redist.exe "to install the Visual Studio Tools for Office runtime" as described above. The link "https://www.microsoft.com/download/details.aspx?id=56961" goes to a general search page.
Without the ability to download vstor_redist.exe I cannot get rid of the error I get when working on office 10 excel documents I use at work. I have to manually remove the Microsoft Development Environment Properties 10.0 reference in order to proceed with my macros.
I need to know where to find the files listed on this page in order to complete the instructions on this page. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 452374f5-e8d0-37e6-558d-c44c3926fec4
* Version Independent ID: 8f3cb5a2-ed9e-3c10-a507-6a9e3bc0588e
* Content: [How to: Install the Visual Studio Tools for Office runtime redistributable](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable?view=vs-2019#feedback)
* Content Source: [docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@HopWorks - thanks for letting us know.

The latest VSTO Runtime can be found here: https://go.microsoft.com/fwlink/?LinkId=158918.  

The download page can be found here: https://www.microsoft.com/en-us/download/details.aspx?id=56961

**Comment by WilliamAntonRohm** [comment]
@John-Hart -- I'll update the Runtime link this document.

**Comment by HopWorks** [comment]
I found it using my laptop so I have to believe it was Chrome maybe that
was at fault. Also, after installing what I needed, my EXCEL VBA was still
complaining that the DLL was missing. I also noticed that there was another
listing offered for the same feature. Not sure why. I just made sure all my
work XLSX files did not have the reference toggled, at work, and that seems
to have worked.

THANKS!
