### ISSUE TITLE
Add possibility to include wildcards for which projects to include

### ISSUE THREAD

**Issue by wouterroos** [MicrosoftDocs/visualstudio-docs#5092]
Hi,

This feature is a great idea but very labor intensive if one has to add projects to the filter everytime a project is added. It would be far more useful if it supports the well-known wildcard (\MyDirectory\**\*.csproj) syntax to Include/Exclude certain projects in/from the filter so you can filter by convention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108b5373-83a5-8d82-0414-939b0caf2866
* Version Independent ID: 9bb010ce-5641-c2a4-ce2a-d53943ac5432
* Content: [Load a subset of projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019#feedback)
* Content Source: [docs/ide/filtered-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/filtered-solutions.md)
* Product: **visual-studio-dev16**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **stsu**

**Comment by WilliamAntonRohm** [comment]
@wouterroos -- Wouter, thanks for your feedback. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Please consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by jamiebarrow** [comment]
I created a feature request here, feel free to upvote:
https://developercommunity.visualstudio.com/idea/1090914/solution-filter-should-allow-for-includeexclude-ba.html

**Comment by WilliamAntonRohm** [comment]
@jamiebarrow -- James, thank you for your contribution.
