### ISSUE TITLE
Is InstallShield available on Visual Studio 2017 and 2019?

### ISSUE THREAD

**Issue by felipepessoto** [MicrosoftDocs/visualstudio-docs#5093]
Is InstallShield available on Visual Studio 2017 and 2019?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 283a3669-9f0e-c872-028d-9eac66fc221b
* Version Independent ID: bdfea87a-3b7d-80ef-51f2-ceadb1ba26bb
* Content: [Deploy an Office solution by using Windows Installer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-an-office-solution-by-using-windows-installer?redirectedfrom=MSDN&view=vs-2017#feedback)
* Content Source: [docs/vsto/deploying-an-office-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/deploying-an-office-solution-by-using-windows-installer.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@felipepessoto I would recommend looking at the InstallShield web site: https://www.flexerasoftware.com/install/products/installshield.html.

**Comment by felipepessoto** [comment]
@John-Hart shouldn't we update the docs to use the current installer project for Visual Studio? Since InstallShield is not freely available for VS 2017 and 2019?

**Comment by John-Hart** [comment]
I just recently updated this doc: [Deploying a Visual Studio Tools for Office Solution Using Windows Installer](https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer).  I've left this one as is for now but may consider deleting it

**Comment by felipepessoto** [comment]
Thanks @John-Hart
