### ISSUE TITLE
Schema link does not exist

### ISSUE THREAD

**Issue by nicole-caldwell** [MicrosoftDocs/visualstudio-docs#5096]
The page links this link: http://schemas.microsoft.com/developer/msbuild/2003 but when you visit that page, it says this page has been removed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73afcd0b-3717-082a-e429-428bfac1c826
* Version Independent ID: 7f6f3bd1-c584-6a63-513d-a541db4e585c
* Content: [MSBuild Project File Schema Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-project-file-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-project-file-schema-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@nicole-caldwell -- Nicole, thank you for your feedback.  You may find information here regarding the current destination link:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
@rainersigwald Is there an updated link for the schema reference?

**Comment by rainersigwald** [comment]
The schema specified in the XML is a string that's an identifier; I don't think it's ever been a real link. The choice to make it look like a URL was a bad one (but is unchangeable now).

**Comment by ghogen** [comment]
We'll close this issue, since that schema identifier is fixed and isn't intended to be a real link.
