### ISSUE TITLE
D3DX

### ISSUE THREAD

**Issue by tiredbunny** [MicrosoftDocs/visualstudio-docs#5099]
D3DX is deprecated and it seems like the docs aren't up-to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cdc48ec9-e36f-da8e-7f3e-cd303c929dca
* Version Independent ID: 94b3340e-f795-07e6-2c57-3476984763af
* Content: [Using 3D Assets in Your Game or App - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/using-3-d-assets-in-your-game-or-app?view=vs-2019#feedback)
* Content Source: [docs/designers/using-3-d-assets-in-your-game-or-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/using-3-d-assets-in-your-game-or-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@rednewt -- Abhij, thank you for your feedback.

@TerryGLee -- Terry, please look into this issue, and [this related page](https://docs.microsoft.com/en-us/windows/win32/direct3d11/d3d11-graphics-reference-d3dx11).
