### ISSUE TITLE
How Can I Debug Windows API Functions?

### ISSUE THREAD

**Issue by forderud** [MicrosoftDocs/visualstudio-docs#5106]
Some suggested improvements:
* Please extend the doc to explain why the "_" prefix and "@4" suffix are needed.
* The doc only mention 32-bit. What about breakpoints in 64-bit code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8e3adc3-9e25-13e7-b924-a7bf34b43c9b
* Version Independent ID: 96eae414-d83d-0ffd-9d25-8e2232f74b15
* Content: [Debug Windows API functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-can-i-debug-windows-api-functions-q?view=vs-2019#feedback)
* Content Source: [docs/debugger/how-can-i-debug-windows-api-functions-q.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-can-i-debug-windows-api-functions-q.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@forderud -- Fredrik, thank you for your questions. Please consider asking them here:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

@Mikejo5000 -- please look into this issue.

**Comment by forderud** [comment]
> @forderud -- Fredrik, thank you for your questions. Please consider asking them here:
> 
> * https://social.msdn.microsoft.com/Forums/vstudio
> * https://www.stackoverflow.com
> * [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
> 
> As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

I've managed to get Win32 breakpoints working myself after some fiddling last week, so I don't need support on this myself. My suggestion was rather to improve the doc for the next developer who's struggling down the road.

**Comment by Mikejo5000** [comment]
@forderud How did you get the feature working?

**Comment by forderud** [comment]
I managed to add a Win32 function breakpoint in 64-bit by removing the "_" prefix and "@4" suffix. Example breakpoint:
```
{,,USER32.DLL}MessageBeep
```
![image](https://user-images.githubusercontent.com/2671400/79272561-ed0b5a00-7ea1-11ea-9af8-006149a99c7d.png)


I'm not sure, but suspect that the prefix & suffix are dropped since there's only a single calling convention in x64.

**Comment by Mikejo5000** [comment]
Taking a look at this @forderud Were you able to view the source when hitting the breakpoint, or could you only view the disassembly code?

**Comment by forderud** [comment]
> Taking a look at this @forderud Were you able to view the source when hitting the breakpoint, or could you only view the disassembly code?

I am able to view my own code and call-stack when hitting the breakpoint, so everything works as expected. However, I can of course not step inside the Win32 implementation of e.g. `MessageBeep`, but that's kind of obvious.
