### ISSUE TITLE
Typo in publish profile file extension

### ISSUE THREAD

**Issue by undeniablyrob** [MicrosoftDocs/visualstudio-docs#5108]
&gt; Make sure to not change the extension of the file (.puxbml).
It should be `.pubxml` not `puxbml`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9d2be7-406b-0422-c49c-d62f972419e0
* Version Independent ID: 127bdbb0-a2ce-dd7c-99b7-1ee55d691e48
* Content: [Publish to a folder - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-folder?view=vsmac-2019#feedback)
* Content Source: [mac/publish-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-folder.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
Thanks for the report. I have submitted a fix, it should be published soon hopefully. It's an automated process, so I'm not sure how long it will take. Typically it gets updated within a day or two.

**Comment by sayedihashimi** [comment]
Change has been published, thanks for the report.

I think this can be closed now, I don't have permission to close this item.

**Comment by sayedihashimi** [comment]
#please-close
