### ISSUE TITLE
Report a problem dialog cannot report a problem which is not included in document.

### ISSUE THREAD

**Issue by bobsort** [MicrosoftDocs/visualstudio-docs#5109]
My machine which I installed visual studio is offline. 

According to your previous suggestion I should be able to use setup on any other online machine and report my issue. It is funny that your setup cannot connect either (online machine).

Clicking on sign in in report a problem page shows following screen (opens a blank dialog box for about 1 miunte then closes and shows the screen below)
clicking signin again does nothing, clicking on let us know, takes me to a support page which is for paid license (not community).

Your support page only allow me to do license and refund related requests.

Since you left me no other way to contact an organization that loves to collect user data without their knowledge but when user want to give you information willingly, you don't accept it, I'm putting the issue here, hoping you that are working in said organization, contact it internally and let them know they screwed again!

![Capture](https://user-images.githubusercontent.com/2040435/79094576-919a7880-7d8a-11ea-9f91-33f1c40c2500.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @seaniyer
* Microsoft Alias: **seiyer**

**Comment by WilliamAntonRohm** [comment]
@bobsort -- for sign-in errors or for issues with the Feedback Tool in Visual Studio, please email us at vsfeedback@microsoft.com.
