### ISSUE TITLE
TargetFramework.TrimEnd('0123456789.')  '0123456789.' unknown token

### ISSUE THREAD

**Issue by GioviQ** [MicrosoftDocs/visualstudio-docs#5110]
I copied exactly the same xml, but it does not work in Visual Studio 16.5.3.
The token '0123456789.' is an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@GioviQ -- thank you for your feedback. It looks like you're having an issue with the product itself. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by rainersigwald** [comment]
@WilliamAntonRohm can you please reactivate this? It's a doc bug--the docs have a bad example.

cc @ghogen.

**Comment by Nirmal4G** [comment]
Related Issue: https://github.com/MicrosoftDocs/visualstudio-docs/issues/4869#issuecomment-612058765
