### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by KurtOplev** [MicrosoftDocs/visualstudio-docs#5113]
https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-debug-a-clickonce-application-with-restricted-permissions?view=vs-2019 
points to
https://docs.microsoft.com/en-us/visualstudio/deployment/securing-clickonce-applications?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe8cafe-31f2-f1fc-2a56-3cc60abe530a
* Version Independent ID: 7d725c68-64d8-76b4-33a3-cd9c731554e9
* Content: [Securing ClickOnce Applications - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/securing-clickonce-applications?view=vs-2019#feedback)
* Content Source: [docs/deployment/securing-clickonce-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/securing-clickonce-applications.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@KurtOplev  Thank you for the feedback, the previous topic seems to have been replaced by [this article](https://docs.microsoft.com/visualstudio/deployment/debugging-clickonce-applications-that-use-system-deployment-application).  

Your change has been submitted and is pending review.
