### ISSUE TITLE
How to start a service program in the post-build event command line?

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5114]
The comments below were machine-translated

@wukongabc123 commented on [Sat Apr 11 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/185)

As the title says, if this service is not terminated, the generation process will always wait. The progress bar will get stuck until the program is closed.
The effect I want to achieve is to restart the service after copying the files to the destination directory after generation. However, now that the service is started, the generation process is stuck. The generated progress bar is displayed in the last few steps until you close the program started with the command line.

how to start a service program after the After-Generated event using command line.
I tried "start xxxService.exe","call StartxxxService.bat","xxxService.exe" and so on,while all of them would stuck the  generating progress. 
The purpose I want to accomplish is that after coping the generated files, restart the service.
however i was stuck here.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 319cf42a-5391-8a60-c005-cfbb92faf1c8
* Version Independent ID: ef79e00a-e2c9-12ec-6da9-2984c381e7d1
* Content: [预生成事件/生成后事件命令行对话框 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/pre-build-event-post-build-event-command-line-dialog-box?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

---

@srvbpigh commented on [Sat Apr 11 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/185#issuecomment-612315463)

Hello, @wukongabc123
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by msebolt** [comment]
@srvbpigh  Thank you for your question.

Unfortunately this forum is for documentation concerns only.

Please refer to [Visual Studio support](https://visualstudio.microsoft.com/support/) for help with support-related issues.

**Comment by msebolt** [comment]
If you feel this does relate to the document in question, please provide a specific reference to the section/text in particular and we can assign this to the author for correction/adjustment.

**Comment by lozziboy** [comment]
> The comments below were machine-translated
> 
> @wukongabc123 commented on [Sat Apr 11 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/185)
> 
> As the title says, if this service is not terminated, the generation process will always wait. The progress bar will get stuck until the program is closed. The effect I want to achieve is to restart the service after copying the files to the destination directory after generation. However, now that the service is started, the generation process is stuck. The generated progress bar is displayed in the last few steps until you close the program started with the command line.
> 
> how to start a service program after the After-Generated event using command line. I tried "start xxxService.exe","call StartxxxService.bat","xxxService.exe" and so on,while all of them would stuck the generating progress. The purpose I want to accomplish is that after coping the generated files, restart the service. however i was stuck here.
> 
> #### 文档详细信息
> ⚠ _请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。_
> 
> * ID: 319cf42a-5391-8a60-c005-cfbb92faf1c8
> * Version Independent ID: ef79e00a-e2c9-12ec-6da9-2984c381e7d1
> * Content: [预生成事件/生成后事件命令行对话框 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/ide/reference/pre-build-event-post-build-event-command-line-dialog-box?view=vs-2019#feedback)
> * Content Source: [docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/ide/reference/pre-build-event-post-build-event-command-line-dialog-box.md)
> * Product: **visual-studio-windows**
> * Technology: **vs-ide-compile**
> * GitHub Login: @TerryGLee
> * Microsoft Alias: **tglee**
> 
> @srvbpigh commented on [Sat Apr 11 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/185#issuecomment-612315463)
> 
> Hello, @wukongabc123
> 
> Thank you for your feedback.
> 
> We are actively reviewing your comments and will get back to you soon.
> 
> Kind regards, Microsoft DOCS International Team

I workarounded that bug by lunching the service through powershell:
powershell start-process xxxNameOfYourService.exe
It seems that using powershell workarounds this issue
