### ISSUE TITLE
NO

### ISSUE THREAD

**Issue by phuong127** [MicrosoftDocs/visualstudio-docs#5118]
The title was confusing. I think it is like converting VBA code to C #

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2a1e216-0563-2c67-1a6b-8705713a789d
* Version Independent ID: 539a79ff-f126-ca1c-ef83-f2a0f9efb13a
* Content: [Walkthrough: Call code from VBA in a Visual C# project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-calling-code-from-vba-in-a-visual-csharp-project?view=vs-2019#feedback)
* Content Source: [docs/vsto/walkthrough-calling-code-from-vba-in-a-visual-csharp-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-calling-code-from-vba-in-a-visual-csharp-project.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@phuong127 -- Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.
