### ISSUE TITLE
Add WCF service Reference VS2019

### ISSUE THREAD

**Issue by ashishakm** [MicrosoftDocs/visualstudio-docs#5119]
This is not updated article for Visual Studio 2019 , please update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a74dad-9ebf-c219-2ad8-3aefaa7f8127
* Version Independent ID: 353c73ea-98dc-b0d9-2a83-fd9af8f6840a
* Content: [How to: Add, Update, or Remove a WCF Data Service Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/how-to-add-update-or-remove-a-wcf-data-service-reference?view=vs-2019#feedback)
* Content Source: [docs/data-tools/how-to-add-update-or-remove-a-wcf-data-service-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/how-to-add-update-or-remove-a-wcf-data-service-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ashishakm** [comment]
For 2019: 
Go to --> Connected Service  then select Microsoft WCF Services the follow rest which given in this article

**Comment by ghogen** [comment]
Thanks, @ashishakm, this article is being updated as you suggested.
