### ISSUE TITLE
$safeprojectname$ Not Working for AssemblyName Element

### ISSUE THREAD

**Issue by Dealman** [MicrosoftDocs/visualstudio-docs#5121]
The assembly name is not being set properly when using `$safeprojectname$`. For example if the user makes a project called `My Example Project` the project name and root namespace etc will be using the parameter as intended.

AssemblyName however will be `My Example Project` instead of `My_Example_Project`. This also affects the built assembly file.

**Comment by WilliamAntonRohm** [comment]
@Dealman -- Dennis, thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. 

Are you looking at a particular docs.microsoft.com article?

**Comment by Dealman** [comment]
@WilliamAntonRohm Sorry, I thought it'd be linked automagically since I used the GitHub related info at the bottom of the documentation. More specifically it is related to [these docs](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-substitute-parameters-in-a-template?view=vs-2019).

**Comment by WilliamAntonRohm** [comment]
@Dealman -- Dennis, thank you for clarifying.  Please see my first reply to log this issue.

cc @TerryGLee for awareness

**Comment by Dealman** [comment]
> @Dealman -- Dennis, thank you for clarifying. Please see my first reply to log this issue.

I've now submitted a report via Visual Studio instead, I hope everything went through and was done properly this time around. Wasn't too sure what other information I could provide.

It doesn't show up under Issues or My Activity for me, so I can't link it here.

**Comment by WilliamAntonRohm** [comment]
@Dealman -- thank you for creating that report.
