### ISSUE TITLE
visual studio 2019 problems

### ISSUE THREAD

**Issue by hchand26** [MicrosoftDocs/visualstudio-docs#5122]
[First time, when I install visual studio 2019, my Python codes are running well but not the Fortran. Second time, I reinstall it, then even my python codes are not running. Perhaps, it may be due to new anaconda version 2020 that I install now, but I think this may not be the issue. Though, I have Intel parallel studio xe 2019,  yet both time my Fortran codes are not running in both case even I have also FTN95, G95, Code block. I have installed and reinstalled visual studio 2019 and intel parallel studio xe 2019 more than 20 times. My Fortran codes are not running in visual studio at any cost. This is my worst experience with these two visual studio 2019 and Intel parallel studio xe 2019. For setting Fortran environment in visual studio 2019, I have waisted more than one month. I have tried much because, I had much time during corona (COVID-19) lock-down in my country. I will use Silver-frost FTN95 the is very-very easy to use than in comparison to many other. If problem is resolved, then reply me as soon as possible.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@hchand26 -- Hari, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
