### ISSUE TITLE
Better examples for task launch

### ISSUE THREAD

**Issue by johnwc** [MicrosoftDocs/visualstudio-docs#5129]
I tried following the example given with the echo, and changing it to call pwsh.exe. But, it never seems to execute the powershell. I'd like to be able to create a few tasks that associate to PS1 scripts that each have different parameters to pass to the selected ps1 script. How can I do that with task.vs.json?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19f6ef2c-e616-bf4c-6de4-1448814e4f73
* Version Independent ID: b223e86b-b0d8-3a78-3fe5-0938e6641042
* Content: [Customize build debug tasks using tasks.vs.json launch.vs.json - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/customize-build-and-debug-tasks-in-visual-studio?view=vs-2019#additional-settings-files)
* Content Source: [docs/ide/customize-build-and-debug-tasks-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/customize-build-and-debug-tasks-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@johnwc -- John, thank you for your question.  Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

Also, if you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

cc @TerryGLee for awareness

**Comment by johnwc** [comment]
I'm pointing out that your example in your docs doesn't work.
