### ISSUE TITLE
Inconsistent Sidenote for "csharp_space_between_parentheses"

### ISSUE THREAD

**Issue by TheFanatr** [MicrosoftDocs/visualstudio-docs#513]
Under https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#a-namespacingspacing-optionsa it says, "This rule does not accept a true or false value", for the possible values of the "csharp_space_between_parentheses" property; however, in the last column of the Visual Studio defaults table for that section it says, "csharp_space_between_parentheses 	C# 	false 	15.3", implying that true and false are valid values. Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#a-namespacingspacing-optionsa)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/editorconfig-code-style-settings-reference.md)
* Service: unspecified

**Comment by gewarren** [comment]
@TheFanatr good catch! @kuhlenh can you clarify what the default value for csharp_space_between_parentheses is?

**Comment by cremor** [comment]
And according to https://github.com/dotnet/roslyn/blob/master/src/Workspaces/CSharp/Portable/Formatting/CSharpFormattingOptions.Parsers.cs#L9-L25 everything except the three documented values works and results in none of them being used.

**Comment by gewarren** [comment]
I'm updating the topic now. Interestingly, the following setting does result in spaces being applied to expressions.

csharp_space_between_parentheses = false, expressions
