### ISSUE TITLE
I'm not clear as to when to put in parameters

### ISSUE THREAD

**Issue by Rod-in-NM** [MicrosoftDocs/visualstudio-docs#5130]
In the example using _namespace name_, the instructions say 

> Insert the parameter in one or more of the code files in the template

But at what point? I can see three possible places to do the substitution:

* I could make all of the substitutions, such as putting in _namespace $safeprojectname$_ in the code files of a project I want to make into a template, before I export the project into a template project. But if I do that, then I've messed the project up from that point forward. 
* I could make a copy of the original project, then export the project. Edit all of the code files I want to put project template parameters into.
* I could export the project into a project template. Then extract all of the files out it somewhere, edit all of the code files I want to edit, and re-import them all into the .zip file.

Which of the 3 above should I do? Or is there a better way?

**Comment by WilliamAntonRohm** [comment]
@Rod-in-NM -- Rod, thank you for your questions. Which docs.microsoft.com article are you reading?

Meanwhile, here are a few options where you might consider asking your questions:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by Rod-in-NM** [comment]
@WilliamAntonRohm I'm looking at [How to: Substitute parameters in a template](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-substitute-parameters-in-a-template?view=vs-2019)

**Comment by Rod-in-NM** [comment]
I would like this issue addressed, please. I still don't know what to do when trying to create a project template. I know it's an issue at work as well, so please keep this issue open.

**Comment by Rod-in-NM** [comment]
At the time I created this issue I was working with VS 2019. And team dynamics were different than they are now. I'm primarily using VS 2022. I haven't investigated creating either project templates or item templates for VS 2022. So, I don't know if it is significantly different or not. I'm guessing it isn't. In any case, as I said team dynamics have changed such that I don't think it likely I'll need to create a project template. 

I'll close this issue with this comment.
