### ISSUE TITLE
The test code screenshot for NUnit is not correct

### ISSUE THREAD

**Issue by tianxiaaiwojs** [MicrosoftDocs/visualstudio-docs#5138]
in line "Or, for an NUnit project, you might use the following code." screen shot is using
using using NUnit.Framework; //this is not valid.

and [TestClass] is not exist inside NUnit.Framework. this one is from MSTest

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 107f3c03-dac2-0226-d5c1-f2f49daa413d
* Version Independent ID: aaf80310-28eb-462b-d4f1-6b97a8abe260
* Content: [Get started with unit testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2019#feedback)
* Content Source: [docs/test/getting-started-with-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/getting-started-with-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, I'll take a look.
