### ISSUE TITLE
Path needs quotes

### ISSUE THREAD

**Issue by grandmaster789** [MicrosoftDocs/visualstudio-docs#5140]
The path to InstallCleanup.exe needs to be in quotes because it contains spaces. This also means that actually using the 'copy' option on this page doesn't work out of the box.

The correct path should be (including quotes!):
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\layout\InstallCleanup.exe"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@ornellaalt -- Ornella, please review [private PR 6433](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6433).
