### ISSUE TITLE
A Github link to the example described would have been more useful

### ISSUE THREAD

**Issue by rvats** [MicrosoftDocs/visualstudio-docs#5141]
ReadLinesFromFile task Working Example Missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 265fb437-d5ed-1c0e-1c34-bd885e7a41cb
* Version Independent ID: 4846dbd1-b059-2f96-c94b-610f801a4abc
* Content: [ReadLinesFromFile Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/readlinesfromfile-task?view=vs-2019)
* Content Source: [docs/msbuild/readlinesfromfile-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/readlinesfromfile-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@rvats -- Rahul, thank you for your feedback.  Here are a few options you might consider asking:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
