### ISSUE TITLE
Cannot change InstallPath to 'C:\Program Files (x86)\Microsoft Visual Studio\'

### ISSUE THREAD

**Issue by jirikavi** [MicrosoftDocs/visualstudio-docs#5145]
When I tried to change the installPath param to `--installPath "C:\\Program Files (x86)\\Microsoft Visual Studio"` then I got this error:
```
docker: Error response from daemon: container 5a3ca07c5f4e0836b9f0ae16ae95b9f83e1ce87dd2ebbb2d531adb3b20eec6c1 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF639EE9D2B: (caller: 00007FF639E9E13A) Exception(2) tid(398) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"\"C:\\Program Files (x86)\\Microsoft Visual Studio\\Common7\\Tools\\VsDevCmd.bat\" \u0026\u0026 powershell.exe -NoLogo -ExecutionPolicy Bypass cmd","WorkingDirectory":"C:\\","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","NUGET_VERSION":"4.4.3","ROSLYN_COMPILER_LOCATION":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\Roslyn"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[20,216]}.
```

**Comment by WilliamAntonRohm** [comment]
@jirikavi -- it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
