### ISSUE TITLE
Noob Visual Studio

### ISSUE THREAD

**Issue by jlewis40** [MicrosoftDocs/visualstudio-docs#5147]
I am a newbie in the world of programming. The page is easy to follow and requires trial and error when doing the exercises. To help out noobs maybe a solutions repository. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4379a80f-e9e9-b0b3-15ed-e42aec4e439a
* Version Independent ID: 075e7150-13ef-0957-d672-c3cbd89eb3e9
* Content: [Overview for Visual Basic developers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-basic/visual-studio-ide?view=vs-2019#feedback)
* Content Source: [docs/get-started/visual-basic/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-basic/visual-studio-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@jlewis40 -- Racer_X, thank you for your feedback.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
