### ISSUE TITLE
list of component names

### ISSUE THREAD

**Issue by abbgrade** [MicrosoftDocs/visualstudio-docs#515]
Hello, it would be helpful to have a list of available installable components that can be used with the `--add` parameter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/install/command-line-parameter-examples.md)
* Service: unspecified

**Comment by abbgrade** [comment]
Something like that: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional

**Comment by TerryGLee** [comment]
@abbgrade Thanks for your feedback; we've added this request to our backlog queue.

**Comment by JamesMBristow2** [comment]
Wouldn't running the vs_installer.exe update --passive --installpath "<pathToVS>" option be preferable since it updates both in one line?

**Comment by JamesMBristow2** [comment]
Please ignore previous comment as part of this chain. I created a new feedback entry.

**Comment by TerryGLee** [comment]
@abbgrade Apologies that it's taken a while to work through our backlog, but for easier reference, the [Command-line parameter examples for Visual Studio 2017 installation](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples) page will now include references to our [Visual Studio 2017 workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2017) page, as you suggested. The updated content will be published by mid-morning tomorrow. Thanks again!
