### ISSUE TITLE
Is it possible to profile a project running in a container? 

### ISSUE THREAD

**Issue by 2Dews** [MicrosoftDocs/visualstudio-docs#5153]
I am doing my development in containers, and running a docker-compose  project. Should I be able to use the diagnostic tools when debugging or running in a container? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ac3ef9-6c7e-9150-cfed-9a2e72b5bd3f
* Version Independent ID: db3bac44-ca59-0a08-0c25-bba1c5718e7e
* Content: [Measure performance with profiling tools - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/profiling-feature-tour?view=vs-2019#feedback)
* Content Source: [docs/profiling/profiling-feature-tour.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/profiling-feature-tour.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@2Dews -- Gus, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by Mikejo5000** [comment]
This might not be supported. I will ask though.

**Comment by 2Dews** [comment]
> @2Dews -- Gus, thank you for your question. It looks like you're having an issue with the product itself, rather than an issue with the documentation. Here are a few options where you might consider asking your question:​
> 
> * https://social.msdn.microsoft.com/Forums/vstudio
> * https://www.stackoverflow.com
> * [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
> 
> As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

I thought I would pose it as an issue because I thought it would be helpful if the documentation addressed it. It seems as though there is some ambiguity between where container support starts and stops with VS.

**Comment by andysterland** [comment]
Thanks for the feedback on the documentation. As you mentioned VS doesn't support profiling docker containers as of yet and you make a great point about updating our container docs to be clear about that. 

Out of cusority were you interested in profiling a .NET Core running in docker? If so you can use the [dotnet-trace](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md) tool to record a trace and then the .nettrace file it creates can be taken back to Visual Studio and opened in the performance tools. I also just filled a super brief[ feature suggestion](https://developercommunity.visualstudio.com/idea/1012765/enable-profiling-of-net-core-apps-running-in-docke.html) for profiling docker   feel free to up vote the ask.

**Comment by 2Dews** [comment]
I am doing a .NET Core app in Docker. I will be trying the dotnet-trace soon. Thanks.

**Comment by andysterland** [comment]
@2Dews awesome, let us know how it goes. 

I think that closes this issue?

/cc @Mikejo5000

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
