### ISSUE TITLE
No help available for Options > Text Editor > Advanced settings

### ISSUE THREAD

**Issue by strelchun-dev** [MicrosoftDocs/visualstudio-docs#5158]
There is no help for the Visual Studio 2019 settings on the Tools &gt; Options &gt; Text Editor &gt; Advanced page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?view=vs-2019#feedback)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by intel-strelchun-dev** [comment]
This issue still has not been addressed... at least in Visual Studio 2019 Professional Version 16.11.9. Going to the _Tools > Options > Text Editor > Advanced_ page, and then clicking on the "?" icon loads the page [Options dialog box: Text Editor > General](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.Advanced)%26rd%3Dtrue&view=vs-2022) and there is no near-by page available for _Advanced_ options in the left navigation pane or linked at the bottom as a related page.

**Comment by TerryGLee** [comment]
@intel-strelchun-dev To follow up, this previously missing page is now published; see [Options dialog box: Text Editor > Advanced](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-advanced).
