### ISSUE TITLE
How to whilelist the URL?

### ISSUE THREAD

**Issue by Super169** [MicrosoftDocs/visualstudio-docs#516]
If the proxy server require login, the above solution does not work.
For general user, how to whilelist those address from proxy server?   Is it expected that all user can update the setting is proxy server?
As it already know the issue, why can't it popup the login dialog when proxy login is required, instead of showing the error message: Proxy Authorization Required.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b331c0-f6cf-bf78-8ec2-e027fc78ebf9
* Version Independent ID: 86c8831f-34f4-67ba-39bb-ddbaed38c35b
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/reference/proxy-authorization-required)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/reference/proxy-authorization-required.md)
* Service: unspecified

**Comment by gewarren** [comment]
@TerryGLee is in the process of updating these topics. Terry, can you look into this question and perhaps address it in the topic?

**Comment by TerryGLee** [comment]
FYI: The current locale for this information is [Troubleshooting network-related errors when you install or use Visual Studio](https://docs.microsoft.com/visualstudio/install/troubleshooting-network-related-errors-in-visual-studio)

**Comment by Super169** [comment]
Thanks for your reply.  Actually I have already follow the instruction to add the following entry under system.net in devenv.exe.config, but it does work also.
      <defaultProxy enabled="true" useDefaultCredentials="true">
        <proxy bypassonlocal="True" proxyaddress="http://------:8080"/>
      </defaultProxy>
(where ------ is the host name of company's proxy server, and 8080 is related port number)

When I attempt to "Sign in" in Visual Studio, it can popup the Sign in window, and after I have successfully sign in, it will prompt the error window as below:

> We could not refresh the credentials for the account
> An error occurred while sending the request.
 
After pressing [OK], it will report error:

> Sorry, we ran into a problem
> Proxy Authorization Required

I also use Visual Studio Code for some other projects, it will popup the windows of "Proxy Authentication Required" when I launch VS Code, and I can provide proxy login information here.   It works fine.

Moreover, even under Visual Studio, there has a button [Enter Credentials] under the page of Developer News, and I can enter proxy login here, and it can retrieve Developer News successfully.   But unfortunately,  the proxy information here only used in the page of "Developer News", it will not be shared for the "Sign in" process.

Just wonder why there has different proxy server handling under "Visual Studio".  Is it possible to use the same mechanism as Visual Studio Code or the page of Developer News in Visual Studio, both of them can handle proxy server require login already.

**Comment by TerryGLee** [comment]
@Super169 There seems to be a similar issue reported in the Developer Community, here: [https://developercommunity.visualstudio.com/content/problem/24557/problem-autenticating-right-after-launch-a-fresh-i.html](https://developercommunity.visualstudio.com/content/problem/24557/problem-autenticating-right-after-launch-a-fresh-i.html). Perhaps the solution(s) posted would be helpful? 

Or perhaps you could post specifics of what you are experiencing to the Developer Community as a new problem to investigate; you can find more information about how to do so, here: [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017). 

Last but not least, it looks like you have a suggestion for a feature request, i.e. a different way that Visual Studio could work that would make it similar to how VS Code works. The best place to suggest a feature request is through [UserVoice(https://visualstudio.uservoice.com/forums/121579-visual-studio-ide) page. (For more information about all the different ways that you can submit feedback to us, see the [Talk to Us](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) page.)
