### ISSUE TITLE
Document how to suppress in ruleset file

### ISSUE THREAD

**Issue by CoolDadTx** [MicrosoftDocs/visualstudio-docs#5160]
If  you are using analyzers across many projects in a team then you are likely using a custom .ruleset file instead of making per-solution/project suppressions. The documentation should be updated to include the instructions on how to suppress warnings using the .ruleset file.  The biggest challenge, in my opinion, is that the .ruleset file uses AnalyzerId and Rules groups to do the filtering and that information isn't documented in the information provided here. So there isn't an easy way to know what, say CA1822, should be added under in the .ruleset file to suppress it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517e8321-aa13-0814-3398-9606d7c2664b
* Version Independent ID: 59efa3c4-ceaf-a384-94af-0f76584efe3f
* Content: [Suppress code analysis warnings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019)
* Content Source: [docs/code-quality/in-source-suppression-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/in-source-suppression-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
We are recommending EditorConfig in place of .ruleset files. Not currently planning any updates to the docs related to .ruleset files.
