### ISSUE TITLE
Missed CA2101 rule

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5161]
@bocus commented on [Tue Apr 21 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/97)

There is page https://docs.microsoft.com/ru-ru/visualstudio/code-quality/ca2101?view=vs-2019, but current page has no link to it

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: f1295961-36c4-75a0-f50a-c5d86159746c
* Version Independent ID: 3d4bba1e-0d05-f577-3b78-65dd6ab10635
* Content: [Предупреждения безопасности - Visual Studio](https://docs.microsoft.com/ru-ru/visualstudio/code-quality/security-warnings?view=vs-2019)
* Content Source: [docs/code-quality/security-warnings.md](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/blob/live/docs/code-quality/security-warnings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

---

@srvbpigh commented on [Tue Apr 21 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/97#issuecomment-617343701)

Hello, @bocus
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for forwarding this issue.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
#2101 is under the Globalization warnings.
https://docs.microsoft.com/en-us/visualstudio/code-quality/globalization-warnings?view=vs-2019

**Comment by bocus** [comment]
Looks like it's wrong place... hmm

**Comment by Mikejo5000** [comment]
I'll check. Thx!

**Comment by Mikejo5000** [comment]
@dotpaul Paul, In the CA2101 doc, this rule is tagged as Microsost.Globalization. Is that correct, or should it be changed to security?

**Comment by dotpaul** [comment]
I'd keep this rule categorized as Globalization.

Dunno if we should have a list of rules that could have potential security implications, because most rules could arguably fall under that list.

This rule's docs should probably note that CAS should not be considered a security boundary; see the "Caution" in https://docs.microsoft.com/en-us/dotnet/framework/misc/code-access-security

**Comment by Mikejo5000** [comment]
Adding a note to CA2101 per recommendation.
