### ISSUE TITLE
for WPF nowadays you need to attach to WpfSurface.exe

### ISSUE THREAD

**Issue by hutterm** [MicrosoftDocs/visualstudio-docs#5163]
title

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c195bbb1-22be-9da7-9792-1c829d73a21b
* Version Independent ID: 0d83875a-56c4-d897-e771-aa3ef9bf910d
* Content: [Debug at design time - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-debugging-at-design-time?view=vs-2019#feedback)
* Content Source: [docs/debugger/walkthrough-debugging-at-design-time.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-debugging-at-design-time.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- please review [private PR 6502](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6502).
