### ISSUE TITLE
Lies Lies Lies

### ISSUE THREAD

**Issue by rwil02** [MicrosoftDocs/visualstudio-docs#5164]
"Performance Explorer" no longer exists in 2019, and you cannot set these options in any way I can find.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 117f8891-64c5-9a7d-0118-e6302011ccb4
* Version Independent ID: e1cb40b3-6b5d-430e-157a-24e310a2070c
* Content: [How to: Set Performance Data File Name Options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-set-performance-data-file-name-options?view=vs-2017&viewFallbackFrom=vs-2019)
* Content Source: [docs/profiling/how-to-set-performance-data-file-name-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/how-to-set-performance-data-file-name-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Correct. You were redirected to the VS 2017 version of the page (see version selector in upper left). When you are redirected, or the version selector is set to VS 2019, you see a message saying the page does not exist in VS 2019.

**Comment by Mikejo5000** [comment]
If you got to this page from a VS 2019 page, let me know, and I can remove the link.

**Comment by rwil02** [comment]
I got to the page from Google with "2017" selected.
I changed the selector to "2019", and it reloaded the same page.
And, huh, your link produces the banner at the top.
Hmm.  
Maybe I should be blaming Edge instead? It's been doing weird stuff on MS sites lately.

**Comment by Mikejo5000** [comment]
If you didn't get the banner, that would likely be a site issue. If we have a repro for it, I could open an issue on the site experience. I don't see a repro on Edge, though.

**Comment by rwil02** [comment]
Yeah, it's just been "weird" (and I'm in NZ, so very different traffic routing I think).
Load the page header and footer and never render anything in between, missing CSS, stuff like that.
But Chrome has no problem at all.
And they're supposed to be the same engine now.
