### ISSUE TITLE
No Browse tab in C++ project in vs2019

### ISSUE THREAD

**Issue by ortymd** [MicrosoftDocs/visualstudio-docs#5165]
No Browse tab in C++ project in vs2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284369-f16f-2748-2a55-8cd24a06b940
* Version Independent ID: f7b0c577-b584-98dc-90a2-4efcf095b35d
* Content: [Add references in the Reference Manager - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2019)
* Content Source: [docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by ortymd** [comment]
![no-browse-tab](https://user-images.githubusercontent.com/22126392/79979790-bd181400-84aa-11ea-9891-68218a3f8c33.PNG)

**Comment by TerryGLee** [comment]
Related to https://github.com/MicrosoftDocs/visualstudio-docs/issues/3024

**Comment by TerryGLee** [comment]
@ortymd Thanks for bringing this issue to our attention. We've added a Note our documentation to let folks know about the issue. Meanwhile, to make sure that this product issue is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report it. When you do so, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), where you can engage directly with the engineering team while they address and fix the problem.

**Comment by StevenRafft** [comment]
Hello there! I'm having this same issue with VS2019
Screenshot
![Screenshot_22](https://user-images.githubusercontent.com/61917452/139679523-601de4b6-fae6-46f3-9660-978cc3efafc7.png)
Project settings:
![Screenshot_23](https://user-images.githubusercontent.com/61917452/139679656-614d0e82-c5be-4f2a-ae2f-99feefcb5d94.png)

**Comment by zejunli** [comment]
I'm having the same issue in VS 2022, missing the 'Browse' button in Project -> add reference

**Comment by gewarren** [comment]
It looks like the Developer Community work item was closed as low priority: https://developercommunity.visualstudio.com/t/Add-Reference-is-missing-browse-tab/181732?ftype=problem&q=browse+button+add+reference+c%2B%2B
