### ISSUE TITLE
Incorrect namespace for PackageGuidString

### ISSUE THREAD

**Issue by mspruill** [MicrosoftDocs/visualstudio-docs#517]
The line [Guid(FirstPackageGuids.PackageGuidString)] is incorrect. It should read [Guid(FirstPackage.PackageGuidString)] - Mitch

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f7aca15b-bfa6-33ac-8f45-78d5d6c4ffc0
* Version Independent ID: c3dc31a4-cf7a-4b25-8e39-91cb19565203
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/creating-an-extension-with-a-vspackage#loading-the-vspackage)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/creating-an-extension-with-a-vspackage.md)
* Service: unspecified

**Comment by gregvanl** [comment]
Thanks for calling this out! Will be fixed shortly.
