### ISSUE TITLE
Good Basic Installation Instructions

### ISSUE THREAD

**Issue by givonz** [MicrosoftDocs/visualstudio-docs#5171]
Good Basic Installation Instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dd4d05c-4aa3-0376-f3a1-b0ea0793f482
* Version Independent ID: 7f1ff943-61b0-60e1-9ca3-d4a84bfdb068
* Content: [Install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@givonz -- thank you Givon!
