### ISSUE TITLE
Keyboard shortcut to open Team Explorer?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/visualstudio-docs#5172]
Hi,

Is there a built in shortcut open TE? Otherwise what's the command name so we can assign one on our own?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f31dd7-e676-aa47-cb11-8ad77412fb5a
* Version Independent ID: 6cce7a4b-8f62-610d-f75f-fafc7b4c444a
* Content: [Connect to projects in Team Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/connect-team-project?view=vs-2019)
* Content Source: [docs/ide/connect-team-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/connect-team-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by weitzhandler** [comment]
The answer is Ctrl+Shift+G, please update the article with the shortcuts.

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- please review [private PR 6292}(https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6592).

**Comment by TerryGLee** [comment]
@weitzhandler The keyboard shortcuts are listed in the **View** menu as follows:

![image](https://user-images.githubusercontent.com/23244653/82388129-9daed100-99ed-11ea-951e-8cf2f18aa4a1.png)

As you can see, the keyboard shortcut for Team Explorer is **Ctrl**+**&#92;**, **Ctrl**+**M**. We can get that keyboard shortcut added to the doc, but just as a quick FYI, **Ctrl**+**Shift**+**G** doesn't seem to work.

**Comment by TerryGLee** [comment]
@weitzhandler We have a PR to add the keyboard shortcut info that you requested; it'll soon be merged and the updated page will be published tomorrow by noon PDT (Pacific Daylight Time). 

Also... if you are looking for info on how assign your own keyboard shortcuts, please see the **[Identify and customize keyboard shortcuts in Visual Studio](https://docs.microsoft.com/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio)** page. 

We'll close this issue now; thanks for helping us improve the documentation!

**Comment by weitzhandler** [comment]
I don't think I ever messed with that shortcut. It's however Ctrl shift g by me

**Comment by TerryGLee** [comment]
@weitzhandler Thanks for the follow-up. I did check it on both Visual Studio 2019 build 16.5.5 and build 16.6.0 (which just [released today](https://docs.microsoft.com/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019)). Not sure why "Ctrl Shift G" works for you, but I'm glad that it does. Meanwhile, we'll have accessibility info for the defaults posted soon. Thanks again!
