### ISSUE TITLE
You're missing some icons in your description

### ISSUE THREAD

**Issue by dorsalmo** [MicrosoftDocs/visualstudio-docs#5173]
I get red-on-white Xs (instead of white-on-red) and green-on-white check marks (instead of white-on-green).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b1fa1671-f27f-484e-8994-ceb85b1a73d6
* Version Independent ID: 5b90e41e-b4ba-7cb7-b798-59ea1ae38eb4
* Content: [Test Explorer FAQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq?view=vs-2019#feedback)
* Content Source: [docs/test/test-explorer-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/test-explorer-faq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @kendrahavens
* Microsoft Alias: **kehavens**

**Comment by WilliamAntonRohm** [comment]
@dorsalmo -- thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by dorsalmo** [comment]
It’s not really a problem, though.  It’s missing information in the documentation.  Do I still use the “Report a Problem” link you gave me below?

**Comment by kendrahavens** [comment]
That is correct, this is a documentation issue. We should update the icons listed to include the new inverted colors icons that indicate tests were not in the last test run in this table. https://docs.microsoft.com/en-us/visualstudio/test/test-explorer-faq?view=vs-2019#test-explorer-hierarchy-view

**Comment by personaelit** [comment]
@kendrahavens Yes.  This would be nice.  I ran into this issue today and [ended up querying Stackoverflow.](https://stackoverflow.com/questions/66175017/visual-studio-test-explorer-icons)

**Comment by j-martens** [comment]
@kendrahavens - can fix this issue as multiple users have encountered this? Thanks!

**Comment by dorsalmo** [comment]
Do you often close a ticket without fixing it?  The doc page remains the same.  

Also, the link above (#8672) is broken.

**Comment by v-andreaco** [comment]
@dorsalmo 

This ticket was closed automatically as a result of me reviewing and merging the PR mentioned above. It looks like the images were updated in that PR, and should show up on the live site soon after the next publish cycle for this repo.

**Comment by dorsalmo** [comment]
So, how long until "the next publish cycle"?

**Comment by j-martens** [comment]
@dorsalmo should be live by now. You may need to clear your cache. Thank you.

**Comment by dorsalmo** [comment]
It's been so long that I don't remember what it was before.  Is this correct?
![test explorer doc](https://user-images.githubusercontent.com/6934037/134021019-4fa616c7-2038-47bc-b862-f89465bb9e0e.JPG)

**Comment by kendrahavens** [comment]
@dorsalmo Yes, that is the graphic with the new icons.
