### ISSUE TITLE
Condition only functions are not listed

### ISSUE THREAD

**Issue by Nirmal4G** [MicrosoftDocs/visualstudio-docs#5174]
Functions such as `Exists(...)` and `HasTrailingSlash(...)` are not listed.

They seem to not require class prefix as opposed to property functions.

If they are not property functions, what category are they?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019&source=docs)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Nirmal4G -- Nirmal, thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.

**Comment by Nirmal4G** [comment]
In MSBuild, the `Condition=''` attribute has some built-in functions that are not necessarily the same as property/item functions. Those are what I listed above.

These are not listed anywhere in this page. They should be listed as Condition only functions and/or redirect to the conditions page.

**Comment by WilliamAntonRohm** [comment]
@Nirmal4G -- Nirmal, thank you for clarifying.

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
@Nirmal4G These are listed here: https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019

**Comment by Nirmal4G** [comment]
@ghogen Thanks. I could not find it. Only property and item functions were listed in their own pages. No reference to conditional functions.

**Comment by ghogen** [comment]
Leaving open - this is still a discoverability issue.  Possible solutions include adding a link or moving the conditional functions into their own topic.

**Comment by Nirmal4G** [comment]
> redirect to the conditions page

Could be one solution. on each of those pages
