### ISSUE TITLE
Please document the <T4ParameterValues> element, including its  <Visible> element child

### ISSUE THREAD

**Issue by Jehoel** [MicrosoftDocs/visualstudio-docs#5177]
The example of &lt;T4ParameterValues&gt; given in this page also has &lt;Visible&gt;false&lt;/Visible&gt; set, but the documentation doesn't explain what &lt;Visible&gt; actually does - or why it's set to false in this case.

I have some specific questions that I couldn't find answers to in any of the current documentation:

- Regarding `<T4ParameterValues>`:
    - [ ] Why is it called `<T4ParameterValues>` and not `<T4ParameterValue>` when it can only be used to set a single named parameter, so you need multiple `<T4ParameterValues>` elements, and that just feels funny.
    - [ ] Besides `<Value>` and `<Visible>`, are there any other child elements or attributes?
- Regarding `<Visible>`:
    - [ ] What does `<Visible>false</Visible>` do? What does `true` do?
    - [ ] Why does my MSBuild project build fine when I omit `<Visible>false</Visible>`?
    - [ ] Is `false` the default value when it's unspecified?)
- Regarding importing/including/referencing `Microsoft.TextTemplating.targets`:
    - [ ]  I noticed that my project seems to build fine **without** adding `<Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v16.0\TextTemplating\Microsoft.TextTemplating.targets" />` (or any other version besides `v16.0`). Do any project configurations cause it to be imported implicitly?
    - [ ] Surely it isn't a good idea to add a hard-reference to Visual Studio 2019 (i.e. the `v16.0` part) please replace this with a version that will work regardless of the version of VS that's installed, or allows us to specify a minimum VS version.
    
Additionally,

Also, I think it would be better to provide an _additional_ example case where the T4 file uses a different parameter name to the MSBuild property name, so that readers can see that `Include=""` is for the T4 Parameter Name and `<Value>` is for the MSBuild property name. It's initially ambiguous because both T4 and MSBuild uses the same `$(name)` syntax, even though they operate in different namespaces based on the build environment.

e.g.

```
<!-- Define an MSBuild project property: "myLibFolder": -->
<PropertyGroup>
    <myLibFolder>$(MSBuildProjectDirectory)\..\libs</myLibFolder>
</PropertyGroup>

<!-- Tell the MSBuild T4 task to make the property available: -->
<ItemGroup>
    <T4ParameterValues Include="myT4LibFolder">
      <Value>$(myLibFolder)</Value>
    </T4ParameterValues>
</ItemGroup>

<!-- Usage in the T4 file: -->
<#@ include file="$(myT4LibFolder)\foobar.ttinclude"  #>
```

## Update:

I had a look inside `Microsoft.VisualStudio.TextTemplating.Build.Tasks.dll` with ILSpy and saw that `Visible` doesn't seem to be used by any of the T4 code at all - or is it still used by MSBuild?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca46de41-5103-a318-3553-3bf05c59751b
* Version Independent ID: 27b60762-dfe8-9320-c891-164e2f0ca980
* Content: [Code Generation in a Build Process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process?view=vs-2019)
* Content Source: [docs/modeling/code-generation-in-a-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/code-generation-in-a-build-process.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@Jehoel -- Dai, thank you for your detailed feedback.  Here are a few options you might consider for further research:  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@JoshuaPartlow -- Joshua, please look into this issue.

**Comment by mgoertz-msft** [comment]
FYI, `<Visible>false</Visible>` is being used to hide items from Solution Explorer in Visual Studio:
https://docs.microsoft.com/en-us/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#display-properties-and-items

`Value` is the only attribute of value (pun intended). And while I agree that singular `T4ParameterValue` would have been a better name changing it would be a breaking change now.
