### ISSUE TITLE
Link to Understanding T4: Preprocessed Text Templates by Oleg Sych not working

### ISSUE THREAD

**Issue by DocGitHub** [MicrosoftDocs/visualstudio-docs#518]
File not found (404) error
Understanding T4: Preprocessed Text Templates by Oleg Sych
http://www.olegsych.com/2009/09/t4-preprocessed-text-templates/

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 7a170869-23a9-96c9-d85b-372adcb19230
* Version Independent ID: d900eb64-973b-78dc-47eb-799aad1ee592
* [Content](https://docs.microsoft.com/nl-nl/visualstudio/modeling/run-time-text-generation-with-t4-text-templates)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/modeling/run-time-text-generation-with-t4-text-templates.md)
* Service: unspecified

**Comment by gewarren** [comment]
@DocGitHub this is fixed now. i changed the link to point to the T4 Toolbox website. Thanks again!
