### ISSUE TITLE
Does launchsettings support Docker with SSL during development?

### ISSUE THREAD

**Issue by phatcher** [MicrosoftDocs/visualstudio-docs#5183]
I've read the docs at https://github.com/dotnet/dotnet-docker/blob/master/samples/run-aspnetcore-https-development.md, but that implies executing docker run from a command line, not within VS.

If I run with SSL enabled, Kestrel fails to find the certificate as the location is not mounted by the launchsettings.  This is/should be related to https://github.com/microsoft/DockerTools/issues/243 where we need the ability to provide arguments to the docker run command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0eb0463-50c5-9697-2eaf-a5f5fcb01513
* Version Independent ID: bf27ddf9-e6a3-0717-1d3c-620c054f0d5c
* Content: [Visual Studio Container Tools launch settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2019)
* Content Source: [docs/containers/container-launch-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-launch-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by NCarlsonMSFT** [comment]
@phatcher There is a launch setting to support Docker will SSL. It is `"useSSL": true`. This should automatically get set when adding Docker support to a project if SSL is detected. But in case it wasn't you can add it to your Docker profile to enable the same logic detailed in the doc.

If that is not working please open an issue in [microsoft/DockerTools](https://github.com/microsoft/DockerTools) with a detailed repro so we can investigate.
