### ISSUE TITLE
Non blocking window

### ISSUE THREAD

**Issue by MaxThom** [MicrosoftDocs/visualstudio-docs#5184]
Hi,
simple suggestion. It would be really nice for the string/json/html visualizer to be non blocking.
It would allow us to copy/paste the stuff and work while seeing the data.
Ty

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3761f60-ec2f-2c51-cfa1-1e192c71bebe
* Version Independent ID: 714a4254-b006-5509-9fa1-355da2184942
* Content: [String Visualizer dialog box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/string-visualizer-dialog-box?view=vs-2019)
* Content Source: [docs/debugger/string-visualizer-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/string-visualizer-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@MaxThom Thank you for the suggestion, at Microsoft we're constantly striving to improve our products and documentation.

Please consider starting this as a thread in the [Visual Studio community](https://developercommunity.visualstudio.com/spaces/8/index.html) to solicit additional feedback from the product team, or let us know and we will start a ticket for you.

For additional ideas, please add additional comments below or see [here](https://docs.microsoft.com/contribute) on how to become Microsoft Docs contributor.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
