### ISSUE TITLE
debugging .net core code

### ISSUE THREAD

**Issue by ahanusa** [MicrosoftDocs/visualstudio-docs#519]
When will VS for Mac support debugging .NET Core code via symbols?  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8807282b-10f0-06aa-0db3-565bf5b56664
* Version Independent ID: f49fb163-23d4-3315-eee6-e59293016681
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/debugging)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/mac/debugging.md)
* Service: unspecified

**Comment by asb3993** [comment]
Hi @ahanusa, thanks for your comment. I think this question is best answered by our product team.

@jmatthiesen @mrward do you have any insight into this question?

Thanks!

**Comment by mrward** [comment]
@ahanusa - Not sure what you exactly mean by 'debugging by symbols'. Is this debugging code you do not own and just have assemblies for? Or support for symbol servers? Or something else?

**Comment by ahanusa** [comment]
Yeah, symbol servers, like Visual Studio for Win supports.

**Comment by mrward** [comment]
Support for symbol servers is a known missing feature and it is on the Visual Studio for Mac backlog. Currently there is no definite date when this feature will be available in Visual Studio for Mac.
