### ISSUE TITLE
Unity Projects need additional steps

### ISSUE THREAD

**Issue by AmazinJacks** [MicrosoftDocs/visualstudio-docs#5190]
I just spent several hours trying to figure out why I could not view project properties.  

I am making a C# Unity application.  I was not able to access the properties pages until I went into Tools&gt;Options&gt;Tools For Unity&gt;General and in the Miscellaneous section changed "Access to project properties" to true.

This was not obvious to me because both in Visual Studio Community 2019 Preview16.6.0 Preview 4.0 and Visual Studio Community 2019 16.5.4, selecting Properties from the project right-click context menu appears to try to open the appropriate window, but then closes it with no error message or other information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30631bf6-bd74-a200-27b4-277ea35325e8
* Version Independent ID: 45a25442-c600-2b20-e815-792bbf67a47a
* Content: [Publish ClickOnce application using Publish wizard - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard?view=vs-2019#feedback)
* Content Source: [docs/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AmazinJacks I'll add that info. You could use the Publish Wizard after making that change?

**Comment by AmazinJacks** [comment]
> @AmazinJacks I'll add that info. You could use the Publish Wizard after making that change?

No.  I was eventually able to figure out how to get Publish Wizard and ClickOnce to work for web apps, but I was never able to figure out how to make it work for Unity apps and eventually wrote my own updater.
