### ISSUE TITLE
Component ID EXCEL 2019 of the main interactive assembly of Microsoft Office

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5192]
The comments below were machine-translated

@jinzi960423 commented on [Sun Apr 26 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/187)

Component ID of the Microsoft Office main interactive assembly

What is the EXCEL 2019 component ID? Where can I find it!
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3df9904c-bc2c-49e6-b661-5598354dbc40
* Version Independent ID: 6dca41d0-9c34-f5cc-a2b0-6c6e9df76063
* Content: [使用 Windows 安装程序部署用于办公室解决方案的可视化工作室工具 - Visual Studio](https://docs.microsoft.com/zh-cn/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2019)
* Content Source: [docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

---

@srvbpigh commented on [Sun Apr 26 2020](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/issues/187#issuecomment-619516249)

Hello, @jinzi960423
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by msebolt** [comment]
@jinzi960423  Thank you for the feedback.

Please refer to issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/5191 for further guidance.
