### ISSUE TITLE
Can we please start marking the pages with some indication of what Frameworks are supported?

### ISSUE THREAD

**Issue by cbuzzsaw** [MicrosoftDocs/visualstudio-docs#5194]
It would be nice and save developers quite a bit of time if there was some indication on what framework versions the topics supported.  It is frustrating to read the article only to find out that it doesn't work with .NET Core only by hitting a NOTE halfway through the article. Although the notes are helpful they should also elaborate on if there is a workaround for .NET Core instead of simply saying that  ".NET Core does not support the DataSource Attribut..." I was left wondering if there was some other way to support it or that simply means it will not work with .NET Core!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1351cc8-f703-27a2-32c7-904256cb9e82
* Version Independent ID: 7a6912ef-da8d-6690-6da9-cc741fd5acde
* Content: [Create Data-Driven Unit Tests - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-data-driven-unit-test?view=vs-2019#feedback)
* Content Source: [docs/test/how-to-create-a-data-driven-unit-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-create-a-data-driven-unit-test.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by cbuzzsaw** [comment]
A suggestion would be to have a section in the same column as "In this article"  which can be expanded to show frameworks supported.

**Comment by WilliamAntonRohm** [comment]
@cbuzzsaw -- Buzz, thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
