### ISSUE TITLE
Slight amendment to instructions

### ISSUE THREAD

**Issue by adrobson** [MicrosoftDocs/visualstudio-docs#5196]
Also need to change Startup constructor to :
public Startup(IConfiguration configuration, IWebHostEnvironment webHostEnvironment)
        {
            Configuration = configuration;
            Env = webHostEnvironment;
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6e74c3-2796-a2c3-ce35-18767cecb702
* Version Independent ID: 60d27ba1-d713-23dc-93ec-b72feda17016
* Content: [Debug apps in a local Docker container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/edit-and-refresh?view=vs-2019#feedback)
* Content Source: [docs/containers/edit-and-refresh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/edit-and-refresh.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Thank you, @adrobson. The article will be updated on the site later today.
