### ISSUE TITLE
Publish of Quickstart fails

### ISSUE THREAD

**Issue by aadhoc** [MicrosoftDocs/visualstudio-docs#5200]
The Quickstart needs a fix. Try it yourself.
(I provided my solution below.)

When switching to release mode and publishing, the publish build fails with:
```
  /bin/sh: 2: /tmp/tmp36d963c730664c048eb04eb2aaba7ea2.exec.cmd: npm: not found
/src/WebApplication37/WebApplication37.csproj(39,5): error MSB3073: The command "npm install" exited with code 127.
Removing intermediate container d47276ab0938
The command '/bin/sh -c dotnet publish "WebApplication37.csproj" -c Release -o /app/publish' returned a non-zero code: 1
C:\DEV\WebApplication37\WebApplication37\Dockerfile(0,0): Error CTC1014: Docker command failed with exit code 1.
The command '/bin/sh -c dotnet publish "WebApplication37.csproj" -c Release -o /app/publish' returned a non-zero code: 1
2&gt;Build failed. Check the Output window for more details.
```

(I'm using Visual Studio 2019)
The problem is that the Quickstart makes us add nodejs to the base image, but later, the publish image doesn't have it and fails.

The Debug image is layered as: 3.1-buster-slim -&gt; base -&gt; dev
The Publish Release image is layed as: 3.1-buster -&gt; build -&gt; publish

I fixed mine by adding the same 2 RUN commands to build.

The QuickStart says to add these RUNs:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
```

I copied those RUNs here also:
```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1abf884f-eb39-1007-25a6-d049b87504a3
* Version Independent ID: 33636e79-d3e1-8c24-f3a5-0c3c79e2a488
* Content: [Visual Studio Container Tools with ASP.NET Core and React.js - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019#feedback)
* Content Source: [docs/containers/container-tools-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-tools-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Thanks @aadhoc, the fix you suggested should be visible on the live site very soon.

**Comment by WilliamAntonRohm** [comment]
@ghogen -- thank you for fixing this issue.
