### ISSUE TITLE
Misleading Instructions "Find and Replace"

### ISSUE THREAD

**Issue by nick1941** [MicrosoftDocs/visualstudio-docs#5204]
In the coding tutorial, we are told to us "Find and Replace (Ctrl + F)".  Ctrl + F is the shortcut to "Find".  The shortcut for "Find and Replace" is Ctrl + H.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@ornellaalt -- Ornella, please review [private PR 6503](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6503).
