### ISSUE TITLE
Update package version table

### ISSUE THREAD

**Issue by billybednar** [MicrosoftDocs/visualstudio-docs#5207]
The latest analyzer package no longer supports VS 2017. From the information in the [release notes](https://github.com/dotnet/roslyn-analyzers/releases), it seems that 2.6.4 should be recommended for 15.5 to 15.8 and 2.9.9 for 15.9+.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019#feedback)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- please review [private PR 6526](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6526).
