### ISSUE TITLE
Multiple ItemGroup elements vs single ItemGroup element

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#5209]
It's quite possible to use either multiple `ItemGroup` elements, or have a single `ItemGroup` element containing all the child items. Either this should be mentioned; or, if there is some reason to prefer one or the other, that reason should be noted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7148a9c-77db-81c7-0362-f2ce6b0c6274
* Version Independent ID: ccef6249-9a81-9376-a9c8-fe884d0b094f
* Content: [ItemGroup Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/itemgroup-element-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/itemgroup-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/itemgroup-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Using a single ItemGroup is best if there's no reason not to.

Two considerations came to mind:
•	You can apply a Condition to an ItemGroup, so multiple ItemGroups could have different conditions
•	ItemGroups could be present in different files
