### ISSUE TITLE
What about the VC project type?

### ISSUE THREAD

**Issue by hpetschko** [MicrosoftDocs/visualstudio-docs#521]
In the Syntax section, the project type VC is shown, but not mentioned any further (neither on this page nor anywhere else). I have made some successful experiments with this type and would like to know whether it is officially supported or not.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cca18c9f-45b4-0a7b-6ce8-d6c88d507dc4
* Version Independent ID: 8030dd04-f507-46bc-2e85-c03568984312
* [Content](https://docs.microsoft.com/en-gb/visualstudio/extensibility/projecttype-element-visual-studio-templates)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/projecttype-element-visual-studio-templates.md)
* Service: unspecified

**Comment by gregvanl** [comment]
Yes, ProjectType VC is officially supported.

**Comment by marckassay** [comment]
@gregvanl, what about TypeScript? And JavaScript?

It seems having the word "must" in the following is too absolute:

> This value specifies the type of project the template will create, and must contain one of the following values:
