### ISSUE TITLE
Can Choose be used against a compiler constant?

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#5211]
If yes, an example showing this might be nice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9555b2e3-0394-0e64-e7a2-4e1adc5e99bf
* Version Independent ID: ed70f624-65ad-556c-25c3-08e00415f6cd
* Content: [MSBuild Conditional Constructs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditional-constructs?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-conditional-constructs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditional-constructs.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@zspitz -- Zev, thank you for your question. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
@zspitz Do you mean a constant created with #define (or -D / -define on the command line, etc.) ?

**Comment by ghogen** [comment]
This answers here might be helpful.
https://stackoverflow.com/questions/12957061/how-do-i-test-for-compiler-directives-with-an-msbuild-condition-in-a-csproj-fil
I can add something like this to this article as well.

**Comment by zspitz** [comment]
@ghogen My specific use case is for constants defined in a (referencing) project file using the `DefineConstants` element. I'm assuming the other mechanisms you describe would work the same.

**Comment by ghogen** [comment]
@zspitz Yes, we should use a regular expression, then, instead of Contains.  The DefineConstants in the referencing project can be referenced in the referenced project, as with other properties, so that should work in your case.
