### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5214]
@EnemyArea commented on [Thu Apr 30 2020](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/83)

https://github.com/MicrosoftDocs/visualstudio-docs.de-de/blob/live/docs/javascript/tutorial-aspnet-with-typescript.md

The typescript output-path is wrong. It should be 
"outDir": "wwwroot/js"
instead of "outDir": "../wwwroot/js"

The path in "exclude" gives the hint :)

---

@srvbpigh commented on [Thu Apr 30 2020](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/83#issuecomment-621792429)

Hello, @EnemyArea
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for bringing this to my attention.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review [private PR 6504](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6504).

**Comment by Mikejo5000** [comment]
No repro. Just retested and this change would break the app. tsconfig.json is not in the root directory, otherwise this would probably work.

**Comment by EnemyArea** [comment]
Why it es closed? Is the wrong path you have set!

**Comment by Mikejo5000** [comment]
In the tutorial, the Output needs to be in the already-existing wwwroot/js folder in the project. The tsconfig.json is in the /scripts folder, so the relative link is "../wwwroot/js". The app won't work if it is set to "wwwroot/js". Can you give an explanation of why you would like the path changed? Do you have tsconfig.json in a different folder? Thanks.

**Comment by Mikejo5000** [comment]
I used the same /scripts folder setup as described in this TypeScript doc: https://www.typescriptlang.org/docs/handbook/asp-net-core.html

**Comment by Mikejo5000** [comment]
Looked at this in more detail -- I do see your point about the path in "excludes". It might improve the example to move tsconfig.json to the root, so the "excludes" can remain unmodified. That is a different set of changes though, and I will need to test it.

**Comment by Mikejo5000** [comment]
Yes, that works. I'm updating the steps to have tsconfig.json added to the project root instead. Some of the other instructions, and tsconfig.json content, needed to be updated as well.
Thanks for reporting this!
