### ISSUE TITLE
no working example  :(

### ISSUE THREAD

**Issue by IngmarBitter** [MicrosoftDocs/visualstudio-docs#5215]
The section **Using Graphics Diagnostics for the first time** refers to 
* DirectX templates, but they do not exist in Visual Studio 2019
* Direct3D 12 UAP sample for Windows 10, but at the page linked to searching for **direct3d uap** yields zero results
* at page linked to above I found **SimpleTexturePC12**, but its not simple (pretty complex project), is configured by default for Visual Studio 2015, has many compile errors out of the box, and when finally is running, crashes the Graphics Analyzer
* Nvidia has a d3d-graphics-compute-samples-1.2 sample project, but that is even older, using VS2010 and VS2012 and it has so many compile errors I don't even want to try to fix it.
* The closest to what I want is https://github.com/discosultan/dx12-game-programming which combines C# and DirectX 12, the two technologies I want to use and seems to work reasonably well. The Graphics Analyzer even is able to take snapshots, but when collection is finished and I select a snapshot, the new popup window tells me that 'Playback of your application may be incomplete. "No such interface supported"'.
* Finally, further searches for a hello world of C# + DirectX 12 with break point in shader code did not turn up anything useful.

Can you please add to this section a zip file with a Visual Studio 2019 solution that actually works and lets you follow the steps described? Or fix the templates in Visual Studio 2019 so that there is one for C# + DirectX 12?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ec9e816-7830-74ae-2fad-0ab34cd5b579
* Version Independent ID: 64d8723a-f5e5-cd97-2d32-423cf16641cd
* Content: [Getting started with graphics diagnostics - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/getting-started-with-visual-studio-graphics-diagnostics?view=vs-2019)
* Content Source: [docs/debugger/graphics/getting-started-with-visual-studio-graphics-diagnostics.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/graphics/getting-started-with-visual-studio-graphics-diagnostics.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks for the feedback! I will take a look at this issue.

**Comment by IngmarBitter** [comment]
Hi Mike, anything else I can provide to help fix this? I can demonstrate reproducing the issue while sharing my desktop if you like.

**Comment by Mikejo5000** [comment]
Hi, thanks! When I get to the doc update/refresh, I may need your help. Sounds like you are trying to resolve the issue now to continue your work? For that, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
@IngmarBitter Were you able to get this working? I suspect you need to install the "Game development with C++" Visual Studio workload to see the DirectX project templates.

**Comment by Mikejo5000** [comment]
I added the Game development workload and the UWP workload, but it looks like the templates have been removed, so you need to start from a Direct3D sample.

**Comment by IngmarBitter** [comment]
by now I found that the rest of the active community seems to have abandoned **Graphics Diagnostics** and is using **PIX** instead. Is that indeed the more recommended tool for graphics debugging?

**Comment by Mikejo5000** [comment]
Thanks, I'll ask about it.

**Comment by Mikejo5000** [comment]
Not sure about the preferred tool yet, but I could get the Graphics Diagnostics tools working using the sample here:
https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/simple3dgamedx/
I'll update the doc with current information.
