### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by IBrooke** [MicrosoftDocs/visualstudio-docs#5219]
This entire section on C# is poorly laid-out, very confusing (for example in finding a logical path thru all the topics), easy to get lost and miss things .  As an experienced developer I was trying to find something that gave me an introduction and walk-thru of C#, this isn't it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@IBrooke -- thank you for your feedback.  You are welcome to leave it here:
- [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio)
