### ISSUE TITLE
vs docs issue

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#5222]
_From @bergano65 on Friday, April 17, 2020 6:47:33 PM_

**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes'

3. Scroll down to '.Fixed In This Release of Visual Studio 2019 version 16.5'

Fixed an issue where Goto next/previous entry failed to work in the find results list when "preview selected files in find results" is turned off.
is duplicated and should be emphasized as.
Fixed an issue where "Goto next/previous entry" failed to work in the find results list when "Preview selected files in find results" is turned off.

5.
Fixed an issue where the find list view did not navigate to results when enter was hit.
 should be
Fixed an issue where the find list view did not navigate to results when "Enter" was hit.

_Copied from original issue: MicrosoftDocs/feedback#2680_

**Comment by JacquelineWiddis** [comment]
Fixed duplicate issue.  #please-close
