### ISSUE TITLE
not  meaningful topics

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#5223]
_From @bergano65 on Thursday, April 16, 2020 4:32:29 PM_

**Describe the bug**

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/visualstudio/?view=vs-2019'

3. Scroll down to '.vs subscription'
"Portal"," Administration" is not informative

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

_Copied from original issue: MicrosoftDocs/feedback#2675_

**Comment by gewarren** [comment]
_From @welcome[bot] on Thursday, April 16, 2020 4:32:31 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by ghogen** [comment]
@evanwindom The user requests more details on this page about the VS Subscriptions entries on the VS products hub page.  What do you think? I think this is not the place for a fuller description. We could change the link text.  Perhaps "Administrative Portal" ?

**Comment by evanwindom** [comment]
I agree completely.  I don't own that page, but I think I know who can make changes.  I think it should say "Subscriber portal" and "Administrator portal".

**Comment by ghogen** [comment]
@evanwindom I own the page and can make the changes. Thanks.

**Comment by evanwindom** [comment]
Well… that was easy.  😊
