### ISSUE TITLE
Need Documentation for using Python for Test Automation in Visual Studio

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#5226]
_From @PythonAutomate on Friday, March 27, 2020 5:54:55 PM_

I'm attempting to convert C# Selenium tests to Python Selenium tests in Visual Studio.
I'm on Windows 10, with python 3.8 installed, visual studio 2017 professional.

I've looked at this site https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2019  which has no documentation for this type of setup.

It would be nice to see documentation that stepped the user through which python type of project
to select, which type of python files to add, and the specific code blocks that will call up a website 
using the selenium webdriver.  Several setup arrangements have simply failed for me.

To take this a step further, it would also be nice to see documentation for using python in visual studio to test RESTful api's. Seems like Microsoft should be able to accomplish this as easily as a 
product like Postman can. 

_Copied from original issue: MicrosoftDocs/feedback#2621_

**Comment by gewarren** [comment]
_From @welcome[bot] on Friday, March 27, 2020 5:54:56 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by JoshuaPartlow** [comment]
We'd recommend looking at the Selenium docs for this issue, so we're closing. If you feel it should still be addressed, feel free to reopen.
