### ISSUE TITLE
Rruunning is misspelled

### ISSUE THREAD

**Issue by PeterRockstars** [MicrosoftDocs/visualstudio-docs#523]
Running is misspelled in the last sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6962d2-a42a-ea79-bcda-d4adcaf2406c
* Version Independent ID: 9da717ab-b573-b81f-45f0-2c2a3a5b66eb
* [Content](https://docs.microsoft.com/en-us/visualstudio/connected-environment/get-started-netcore-visualstudio-06)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/connected-environment/get-started-netcore-visualstudio-06.md)
* Service: unspecified

**Comment by gewarren** [comment]
@PeterRockstars Thank you for the feedback. It looks like this has been fixed.
