### ISSUE TITLE
Unable to uninstall VS community edition

### ISSUE THREAD

**Issue by chibiconsulting** [MicrosoftDocs/visualstudio-docs#5230]
Visual Studio 2019 does not work without an Internet connection and refuses to uninstall without an Internet connection so it is useless and taking up disk space.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dac42ba7-edf2-06fb-dc6a-13a0c47b43c5
* Version Independent ID: 98b5c39a-ff89-f4c8-ef77-ae239564998a
* Content: [Uninstall Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/uninstall-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/install/uninstall-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/uninstall-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@chibiconsulting -- Doug, thank you for your feedback.  If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
