### ISSUE TITLE
Referencing menu items

### ISSUE THREAD

**Issue by ChrisEAlfred** [MicrosoftDocs/visualstudio-docs#5232]
There are many cases in the documentation written like:

`
... select **Code Snippets Manager** from the **Tools** menu ...
`

It is much clearer to maintain the user operational order:

`
... select the **Tools** menu, then select **Code Snippets Manager** ...
`

**Comment by WilliamAntonRohm** [comment]
@ChrisEAlfred -- Chris, thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
