### ISSUE TITLE
Rule CA1710: Add configurability section - Exclude indirect base types

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5234]
@Evangelink commented 3 days ago — with docs.microsoft.com
Rule CA1710 was updated to allow for a new configurability section. This restrict the analysis to the current base type.

Note that on another PR we updated the default value to be true.

See https://github.com/dotnet/roslyn-analyzers/pull/3148/files#diff-1b5cdc4937a8cdfc79545945ad6c0783R413-R438 and see also dotnet/roslyn-analyzers#3236

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83202117-8bd8-aa22-d55c-42ecc59fc11f
* Version Independent ID: 2374ea4f-0f8d-283e-5803-7c8de04b48f7
* Content: [CA1710: Identifiers should have correct suffix - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1710?view=vs-2019#configurability)
* Content Source: [docs/code-quality/ca1710.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1710.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for raising this.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@Evangelink How does this look?

### Exclude indirect base types

Starting in version 3.0.0 of the analyzers, you can configure whether to exclude indirect base types from the rule. By default, this rule is set to true, which restricts analysis to the current base type.

```ini
dotnet_code_quality.CA1710.exclude_indirect_base_types = false
```

**Comment by Evangelink** [comment]
@Mikejo5000 LGTM. It might be useful to indicate that this is a breaking change compared to behavior of previous versions. I don't know how you usually represent such breaking change.

**Comment by Mikejo5000** [comment]
Fix is live now
