### ISSUE TITLE
Examples Suggestion

### ISSUE THREAD

**Issue by swesonga** [MicrosoftDocs/visualstudio-docs#5236]
It would be quite helpful to have examples illustrating these solution & project configuration assignments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b17767-3a4a-fd12-4690-e772b8aaccc6
* Version Independent ID: 2d66b972-2b14-49a4-4198-44214ce8574a
* Content: [Understand build configurations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/understanding-build-configurations?view=vs-2019#feedback)
* Content Source: [docs/ide/understanding-build-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/understanding-build-configurations.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
Thanks for the suggestion! The product teams aren’t always watching this repository, so to make sure it gets in front of them for triage, please [submit your idea]( https://developercommunity.visualstudio.com/content/idea/post.html?space=21) here.
