### ISSUE TITLE
How to debug unit tests remotely on Linux

### ISSUE THREAD

**Issue by drache42** [MicrosoftDocs/visualstudio-docs#5237]
How would I go about debugging unit tests on Linux? As far as I can tell I can only attach to a process in Linux over SSH, but there is no way to start it directly from visual studio.

Right now my only option seems to be to add a wait-for-keypress pause in the unit tests, run unit tests via `dotnet vstest`, attach to to test runner, press any key. That doesn't scale.

**Comment by WilliamAntonRohm** [comment]
@drache42 -- Steffen, thank you for your question. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
