### ISSUE TITLE
"foreach loop to LINQ query" quick fix not available?

### ISSUE THREAD

**Issue by johannes-riecken** [MicrosoftDocs/visualstudio-docs#5239]
The article mentions the "foreach loop to LINQ query" quick fix. How can I make that show up? The following two code snippets only offer quick fixes to convert the foreach loops into for loops:

First example:
---------------
            var arr = new List&lt;int&gt; { 1, 2, 3 };
            foreach (var i in arr)
            {
                Console.WriteLine(i);
            }

Second example:
-------------------
            var arr = new List&lt;int&gt; { 1, 2, 3 };
            var sum = 0;
            foreach (var i in arr)
            {
                sum += i;
            }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1815d49f-fef6-46ef-8443-7a6db8e970c1
* Version Independent ID: 3a8e4fea-8492-8ccd-08cd-a4ca74b35cd4
* Content: [Increase your productivity for .NET development - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/csharp-developer-productivity?utm_source=VisualStudio&utm_medium=aspnet-getstarted&utm_campaign=VisualStudio&view=vs-2019#feedback)
* Content Source: [docs/ide/csharp-developer-productivity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/csharp-developer-productivity.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@johannes-riecken -- Johannes, thank you for your question.  Please see [this article](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-foreach-linq?view=vs-2019).
