### ISSUE TITLE
Reference documentation for solution file

### ISSUE THREAD

**Issue by aggieben** [MicrosoftDocs/visualstudio-docs#524]
This page should link to or include reference documentation for syntax in the .sln file format.  In my particular case, I am trying to learn more about the "VisualStudioVersion" directive / setting, but there is nothing about that here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9177b266-5055-95d6-407f-ca4aad75257a
* Version Independent ID: 4586847b-d990-df3b-4cce-bd9a471eda33
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/solution-dot-sln-file)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/extensibility/internals/solution-dot-sln-file.md)
* Service: unspecified

**Comment by walterdolce** [comment]
I was also looking forward to learning about the "Project" directive/section and what can be defined within it but couldn't find any information about it anywhere in this documentation so far.

**Comment by dksimpson** [comment]
It looks like this issue has been addressed, so I am closing this. Thanks!

**Comment by walterdolce** [comment]
@dksimpson where? how? Any links? Thanks.

**Comment by dksimpson** [comment]
@walterdolce, the original issue opened by @aggieben was addressed here: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/4192.

**Comment by dksimpson** [comment]
@walterdolce, we appreciate your interest in helping us improve the content. You're welcome to file a new issue or PR with your additional ideas for improving this article.

**Comment by walterdolce** [comment]
Thanks for the above @dksimpson. Please note the link to the PR leads to a 404 page. ;)

**Comment by aggieben** [comment]
Yep, I also tried to view the PR and it's gone (it appears the repository is private).
