### ISSUE TITLE
MSBuild CLI Environmental Variables are missing in docs

### ISSUE THREAD

**Issue by Nirmal4G** [MicrosoftDocs/visualstudio-docs#5240]
.NET CLI has listed their `env` variables [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet#environment-variables).

It would be most helpful, if the msbuild cli page also lists the available `env` variables, it's defaults and it's usage & examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
All environment variables in the environment that MSBuild is started from are converted into properties, and so any variable can be used in projects in the same way as any other property.  These aren't owned by MSBuild, though.

**Comment by Nirmal4G** [comment]
@ghogen NOT that.

Environmental Variables that are declared and used in MSBuild source specific to the MSBuild functionality.

**Comment by ghogen** [comment]
According to the engineering team, yes, there are some environment variables, but these are intentionally not documented. They are created when behavior that is not thought to be significant is changed and we provide a way (by setting an environment variable) to return to the previous behavior if a compatibility scenario requires it.  Users can find these variables in the open source code, but I will close this issue, since there is no need to expose these to general use.

**Comment by Nirmal4G** [comment]
There is a general use case. i.e. Debugging.

MSBuild is not a predictable software. So we need certain env Variables to be set when debugging it. Searching in Docs is way easier than searching in the source code.

**Comment by Nirmal4G** [comment]
@ghogen

**Comment by Nirmal4G** [comment]
There is a general use case. i.e. Debugging.

MSBuild is not a predictable software. So, we need certain env Variables to be set when debugging it. Searching these in the Docs is way easier than searching in the source code.
