### ISSUE TITLE
Not the most helpful

### ISSUE THREAD

**Issue by KyleADOlson** [MicrosoftDocs/visualstudio-docs#5242]
I'm looking to do something which should be fairly simple, globally suppress a few messages in the IDE, but since you only offer per file as an option and these docs are so weak it's turned into one of those things that more work than it's worth.

On the minor side, there's the localization part of the example. I don't think anyone outside of MS will bother to localize the name and description of their rule set, particularly when you need to use a resource DLL to do so, and it's one of those things where you just have to know already to understand how it works if you want to bother.

The "Tip: It's easier to edit a rule set in the graphical Rule Set Editor than by hand." is a cop out, as I'm only at this page because  the RuleSet editor isn't well documented.

I'm looking for a "How To" and all I've got is this page which says "here's a ruleset" and another page which pretty much gives me the ToolTip text for the RuleSet editor. So I get to do a bunch of trial and error to figure out what it all means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f961b0d-0ef1-f507-d8ad-626903a9d848
* Version Independent ID: e2ef819f-6c68-4776-cd36-499ca7661d85
* Content: [Code analysis rule sets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2019#feedback)
* Content Source: [docs/code-quality/using-rule-sets-to-group-code-analysis-rules.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/using-rule-sets-to-group-code-analysis-rules.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@KyleADOlson -- Kyle, thank you for your feedback.  Please try these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

cc @Mikejo5000 for awareness

**Comment by Mikejo5000** [comment]
I will take a look at this to see.

**Comment by Mikejo5000** [comment]
@KyleADOlson Are you using rulesets with source code or binary (legacy) analysis? If you are using source code analysis (FxCop Analyzers), you can configure rules using EditorConfig for multiple projects: https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019#enabling-editorconfig-based-configuration
