### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by Yrp1994** [MicrosoftDocs/visualstudio-docs#5244]
I wish to position scrollbar on the left

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9440cd51-f00a-2a66-c895-0c093c6c883d
* Version Independent ID: 77cf076b-949f-ce9a-882f-7a0c02d268d0
* Content: [Scroll bar map mode and bar mode - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-track-your-code-by-customizing-the-scrollbar?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-track-your-code-by-customizing-the-scrollbar.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Yrp1994 -- than you for for your question. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
