### ISSUE TITLE
The new implementation of CA2109 won't check for SecurityPermissionAttribute

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#5248]
With PR https://github.com/dotnet/roslyn-analyzers/pull/3417, available in FxCop 3.1.0 the analyzer will no longer have a specific check for the `SecurityPermissionAttribute` on the event handler method. The description about the security issue still remains valid IMO and could be kept as-is. @mavasani WDYT?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4fce2219-e2c5-c538-c619-720960c6b8c8
* Version Independent ID: 5e043309-e1a4-8ccd-f953-2a5d0907b8ef
* Content: [CA2109: Review visible event handlers - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2109)
* Content Source: [docs/code-quality/ca2109.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca2109.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
@dotpaul Is it OK to close this issue? If the security issue mentioned in the doc is still valid, we can close this out.

**Comment by Mikejo5000** [comment]
@dotpaul Closing this out, as it appears the security issue is likely valid, according to @Evangelink
