### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by SychevIgor** [MicrosoftDocs/visualstudio-docs#5249]
Both screenshots are from VSTS, not from Azure DevOps
https://docs.microsoft.com/en-us/visualstudio/subscriptions/_img/vs-alternate-identity/sign-in-with-alternate-account.png
https://docs.microsoft.com/en-us/visualstudio/subscriptions/_img/vs-alternate-identity/enter-alternate-account-my-visual-studio-com-portal.png

Could you update to latest experience 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e967e1-0b8e-a6b5-13ef-bd206ca6d13a
* Version Independent ID: 612623f5-6252-6353-8c7c-c1be43bd8801
* Content: [Identities for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-alternate-identity)
* Content Source: [subscriptions/vs-alternate-identity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-alternate-identity.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by jillre** [comment]
@evanwindom, please look into this issue.  Thanks!

**Comment by evanwindom** [comment]
Merging a PR to replace one image and remove one.  
#please-close
