### ISSUE TITLE
Doesn't exist anymore apparently - devenv switch

### ISSUE THREAD

**Issue by keyoti** [MicrosoftDocs/visualstudio-docs#525]
When I run devenv /resetaddin I get
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv" /ResetAddin

Microsoft Visual Studio 2017 Version 15.0.27130.2010.
Copyright (C) Microsoft Corp. All rights reserved.

Invalid Command Line. Unknown Switch : ResetAddin.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b69f4b92-06df-e530-8376-4bd834152b7c
* Version Independent ID: d6217fc3-c4a8-7f6d-7ec9-3b95ab433983
* [Content](https://docs.microsoft.com/en-gb/visualstudio/ide/reference/resetaddin-devenv-exe)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/reference/resetaddin-devenv-exe.md)
* Service: unspecified

**Comment by gewarren** [comment]
@keyoti thanks for the feedback. I will see if this switch has been removed from the product.

**Comment by gewarren** [comment]
@keyoti I have removed this topic from the [documentation](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches). Thanks for helping us improve docs!
