### ISSUE TITLE
How do I delete Project and item templates?

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [MicrosoftDocs/visualstudio-docs#5254]
Hello, I did not find any information about how to delete Project and item templates, this site describes how to create:
https://docs.microsoft.com/en-us/visualstudio/ide/creating-project-and-item-templates?view=vs-2019

I deleted the zip in C:\Users<user>\Documents\Visual Studio 2019\My Exported Templates\

but that did not help, in the "Visual Studio Create new Project Dialog" it is still visible and I can use the deleted template to create a new project,
Thanks for the help.

**Comment by WilliamAntonRohm** [comment]
@Andreas-Schniertshauer -- thank you for your question. Here are a few options where you might consider asking it:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@TerryGLee -- please look into this issue.

**Comment by Andreas-Schniertshauer** [comment]
Found the "ugly" solution, you need to manually remove the zip from all these locations, else it comes back.
`%UserProfile%\Documents\Visual Studio 2019\Templates\ProjectTemplates
%UserProfile%\Documents\Visual Studio 2019\My Exported Templates
%UserProfile%\AppData\Roaming\Microsoft\VisualStudio\<Version>\ProjectTemplatesCache
`

**Comment by WilliamAntonRohm** [comment]
cc @TerryGLee for awareness
