### ISSUE TITLE
Package version 3.3.x

### ISSUE THREAD

**Issue by cyril-ftp** [MicrosoftDocs/visualstudio-docs#5255]
This page mentions FxCopAnalyzers package version 3.3.x, but the latest one is 3.0.0 (prerelease included). 
Is it a mistake or is there an incoming version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8b2b086b-cda0-2741-2b2b-b2d7e87d0ac9
* Version Independent ID: 29465605-4eda-76c5-4254-8976bc17ca37
* Content: [Configure FxCop analyzers using editorconfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019#feedback)
* Content Source: [docs/code-quality/configure-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/configure-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mavasani Should the version here be 3.0.0?

**Comment by mavasani** [comment]
@Mikejo5000 3.3.0-beta1 is soon plan to be released. The doc change was made pro-actively as the change was already merged into roslyn-analyzers, and I did not want to forget updating the docs as this is an important feature support.

**Comment by mavasani** [comment]
@cyril-ftp Feel free to try out https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers/3.3.0-beta1.20257.2 if you wish to get this feature sooner.

**Comment by Mikejo5000** [comment]
OK, thanks, sounds good. I will close this.
