### ISSUE TITLE
Batch build is not simultaneouse

### ISSUE THREAD

**Issue by richard-broadhurst** [MicrosoftDocs/visualstudio-docs#5256]
The page has the click bait of batch build Batch build is not simultaneously, but batch build is serial, the opposite!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90dc0492-db3d-7312-b76c-9d94022c113a
* Version Independent ID: d786a336-7b5e-89cc-7bc8-f336cdd2f919
* Content: [How to: Build multiple configurations simultaneously - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-build-multiple-configurations-simultaneously?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-build-multiple-configurations-simultaneously.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-build-multiple-configurations-simultaneously.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@richard-broadhurst -- thank you for your feedback.  Please see also [this page](https://docs.microsoft.com/en-us/visualstudio/msbuild/building-multiple-projects-in-parallel-with-msbuild).

You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report this issue. 






I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @ghogen for awareness

**Comment by ghogen** [comment]
I think this should be investigated as a content issue - the description of the Batch Build feature might be misleading or confusing.

**Comment by richard-broadhurst** [comment]
> @richard-broadhurst -- thank you for your feedback. Please see also [this page](https://docs.microsoft.com/en-us/visualstudio/msbuild/building-multiple-projects-in-parallel-with-msbuild).
> 
> You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report this issue.
> 
> I am closing this issue now. You are welcome to @ mention me for any followup.
> We hope to hear from you again.
> 
> cc @ghogen for awareness

That page is not about building multiple configurations in parallel, it is about building multiple projects in parallel, which is very different and just requires an option change in the GUI.

**Comment by richard-broadhurst** [comment]
There seems to be a MS page that does describe building multiple configurations simultaneously, although it uses the more common term in parallel.
https://docs.microsoft.com/en-gb/visualstudio/msbuild/msbuild-task?view=vs-2015&redirectedfrom=MSDN
Although this is with some king of config files, which I have avoided in the 23 years of near daily VS use.
