### ISSUE TITLE
An example of how to pass a variable for the parameter.

### ISSUE THREAD

**Issue by tskilken** [MicrosoftDocs/visualstudio-docs#5259]
This would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aca23b9d-d075-c0fd-e4be-97a5760da8bf
* Version Independent ID: 9cd620d8-19ea-247f-c199-e0781835795c
* Content: [Create parameterized TableAdapter queries - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-parameterized-tableadapter-queries?view=vs-2019&source=docs#feedback)
* Content Source: [docs/data-tools/create-parameterized-tableadapter-queries.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-parameterized-tableadapter-queries.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@tskilken -- thank you for your feedback.  Please see these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- please look into this issue.

**Comment by ghogen** [comment]
Closing out issues on older technology areas. Consider using newer data technology areas such as Entity Framework.
