### ISSUE TITLE
Support for Visual Studio for Mac

### ISSUE THREAD

**Issue by xtellurian** [MicrosoftDocs/visualstudio-docs#5262]
This page doesn't mention whether the tools are available for Visual Studio on Mac OS.

Are they?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe1b67a-347e-9ce6-f81a-4d2b3636c634
* Version Independent ID: c7e2aa26-33ce-0d36-b820-b94e351b21e3
* Content: [What's new for design in Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/modeling/what-s-new-for-design-in-visual-studio?view=vs-2017&viewFallbackFrom=vs-2019#VersionSupport)
* Content Source: [docs/modeling/what-s-new-for-design-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/what-s-new-for-design-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@xtellurian -- Rian, thank you for your question.  Those tools do not appear to be supported on Mac.  Here are a few options where you might consider looking:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​
