### ISSUE TITLE
A link

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/visualstudio-docs#5263]
The SharePoint Page Types link in this page, says that it only applies to SharePoint Foundation 2010. I wonder if it's a better idea to replace that link with one that includes something newer (SharePoint Server 2016, SharePoint Online, etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5193fdb8-c501-6729-bf8c-0ee93e8e5ef8
* Version Independent ID: 7053478b-68d6-7e11-3e88-2541655db3d0
* Content: [Creating Application Pages for SharePoint - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/sharepoint/creating-application-pages-for-sharepoint?view=vs-2019)
* Content Source: [docs/sharepoint/creating-application-pages-for-sharepoint.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/sharepoint/creating-application-pages-for-sharepoint.md)
* Product: **visual-studio-windows**
* Technology: **sharepoint-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@hwkwicre -- thank you for your feedback.  

@John-Hart -- please look into this issue.  The nearest modern link I've found is [Creating pages for SharePoint](https://docs.microsoft.com/en-us/visualstudio/sharepoint/creating-pages-for-sharepoint?view=vs-2019#types-of-sharepoint-pages).

**Comment by John-Hart** [comment]
Thanks @hwkwicre for the feedback.  

I believe you're right the applies to field on the SharePoint Page Types document hasn't been updated in a while.  I believe the information is still correct for SharePoint Solutions.  If you interested in more modern SharePoint technology please see: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/sharepoint-framework-overview
