### ISSUE TITLE
Report new problem button

### ISSUE THREAD

**Issue by BWMerlin** [MicrosoftDocs/visualstudio-docs#5268]
The page has a note stating the following

> Note
>The Report new problem button only appears in the Visual Studio interface for Developer >Community. You can't report a problem directly on the Developer Community website.

However on the Developer Community website there is now a report problem button.  Can this note please be update/removed as it is no longer correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@madskristensen -- Mads, please review [private PR 6566](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6566).
