### ISSUE TITLE
Issues with Windows SDK version 10.0.14393 or earlier

### ISSUE THREAD

**Issue by data-metrics** [MicrosoftDocs/visualstudio-docs#5272]
Hi,

The known issue page mentions:
"You cannot install Windows SDK version 10.0.14393 or earlier. Certain packages fail to install and workloads that depend on those packages will not work."
https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container-issues?view=vs-2017

Is there anywhere I can find more information on this issue: e.g. root cause,  issue's fix status?

My applications requires these older Windows SDKs (including WIndows SDK 8.x and Windows SDK 7.x). Does anyone has any work around for that?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a03297c-c10e-c0e8-679c-df90b709d475
* Version Independent ID: 2e9073e3-4dc7-5ccc-55ac-ecbf039e7c29
* Content: [Known issues for containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container-issues?view=vs-2017#feedback)
* Content Source: [docs/install/build-tools-container-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container-issues.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@data-metrics -- Liam, thank you for your question. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

cc @ornellaalt for awareness
