### ISSUE TITLE
Syntax for file types unspecified

### ISSUE THREAD

**Issue by breyed** [MicrosoftDocs/visualstudio-docs#5273]
What are the rules for customizing the types of files to search.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e27881f-04bc-b7ba-e217-8360278a14f8
* Version Independent ID: d31c8050-339a-688c-869e-ff7942fd3f74
* Content: [Find in Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2019)
* Content Source: [docs/ide/find-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/find-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@breyed -- Edward, thank you for your question.  Please see **Look at these file types** under [Find options](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2019#find-options).

**Comment by breyed** [comment]
I saw that section. I just mentions "types of files", but doesn't specify the syntax for indicating the types of files. Can you use regular expressions? Wildcards? Recursive wildcards (`**`)?

**Comment by WilliamAntonRohm** [comment]
@breyed -- Edward, thank you for clarifying.  We are looking into this issue.

**Comment by TerryGLee** [comment]
@breyed Thanks for your inquiry and apologies for our delayed response. We've recently revised the [**Find in Files**](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2019) page, which now includes the content updates to the following sections:

- the [**File types**](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2022#file-types) section, which includes information about how you can tailor your search string for specific file types
- the [**Search box**](https://docs.microsoft.com/visualstudio/ide/find-in-files?view=vs-2019#search-box) section, which includes information about how the **Use regular expressions** checkbox toggles the **Expression Builder** button, which provides you with more information about how to [use regular expressions](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019) in your search strings

We'll close this issue now with our further thanks to you for helping us improve the documentation.
