### ISSUE TITLE
Getting started with Docker

### ISSUE THREAD

**Issue by eostarman** [MicrosoftDocs/visualstudio-docs#5274]
Excellent!! The note about the "mounts denied" error message was a life saver. Thanks :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22e20f91-d94c-419c-3a64-7616af5e7429
* Version Independent ID: 0f4f0b1a-2506-ec3d-6bda-ccce7565cb64
* Content: [Get started with Docker - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/docker-quickstart?view=vsmac-2019)
* Content Source: [mac/docker-quickstart.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/docker-quickstart.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment]
@eostarman -- you're welcome!

cc @heiligerdankgesang as the author
