### ISSUE TITLE
Requesting for Reactjs with redux tutorial

### ISSUE THREAD

**Issue by emamcoder** [MicrosoftDocs/visualstudio-docs#5275]
Kindly add the tutorial for the reactjs with redux CURD operation application.
It will be really very helpful in order to learn to develop a web app using this library in visual studio for mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad6c500-5eb9-38c2-dbc7-2276c2bf131d
* Version Independent ID: 9b4b00d1-6d7a-55df-64d4-b85805604f5c
* Content: [Extending an existing ASP.NET Core web application - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tutorial-aspnet-core-vsmac-extending?view=vsmac-2019#feedback)
* Content Source: [mac/tutorial-aspnet-core-vsmac-extending.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tutorial-aspnet-core-vsmac-extending.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by WilliamAntonRohm** [comment]
@emamcoder -- Emamul, thank you for your feedback.  Please see the following resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@sayedihashimi -- Sayed, please look into this issue.

**Comment by sayedihashimi** [comment]
@WilliamAntonRohm I'm no longer working with Visual Studio for Mac. I think this would be better assigned to @jmatthiesen.
