### ISSUE TITLE
Create simple data science projects using tools provided for the community 

### ISSUE THREAD

**Issue by jparra0419** [MicrosoftDocs/visualstudio-docs#5277]
Can Jupyter notebooks with Matplotlib and other packages that run with python be accessed without azure service?        

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79668399-b304-e485-f724-04d8ead4b2ed
* Version Independent ID: d3b473dc-7804-8e1d-eb41-affd3bbc0123
* Content: [Data Science and Analytical Applications workload - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/data-science-and-analytical-applications-workload?view=vs-2019)
* Content Source: [docs/python/data-science-and-analytical-applications-workload.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/data-science-and-analytical-applications-workload.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@jparra0419 -- thank you for your question. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by jparra0419** [comment]
W A. Rohm,
It is too bad you didn't answer my question.
Here goes again:"  " After a Web Application is completed with VisualStudio is it 
possible to publish the application (app.py) in GitHub as a
Website by following the  GitHub’s procedure? 
The procedure consists of a few steps that GitHub provides to anybody who registers with this company. This allows a person to publish the WebSite public (free) or private (pay). 
Thank you for your help,
Jorge Parra

 

    On Monday, May 11, 2020, 06:26:43 PM EDT, William Anton Rohm <notifications@github.com> wrote:  
 
 


@jparra0419 -- thank you for your question. Here are a few options you might consider:​
   
   - https://social.msdn.microsoft.com/Forums/vstudio
   - https://www.stackoverflow.com
   - https://www.reddit.com/r/VisualStudio/

**Comment by WilliamAntonRohm** [comment]
@jparra0419 -- thank you for clarifying.

@JoshuaPartlow -- please look into this potential documentation issue.

**Comment by JoshuaPartlow** [comment]
Hi @jparra0419 - For your first question around Jupyter Notebooks, there are a number of services for hosting them, with Azure being one option. As far as what can be done with GitHub, I'd have to defer to their [support site](https://help.github.com/) for guidance.

**Comment by JoshuaPartlow** [comment]
Closing given time open. If this is still an issue, please feel free to reopen.
