### ISSUE TITLE
This is out of date

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/visualstudio-docs#5278]
When trying to invoke this command and pass arguments, Visual Studio 2019 (16.5.4) reports the message:

`Command "Edit.FindinFiles" does not accept arguments or switches.`

Either this page is wrong and the ability to pass arguments to this command has been removed, or there is a bug that prevents running this command and passing arguments.
Please advise which.
I really hope it's a bug as I want the ability to pass arguments to this command.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c0cc55-2f9c-eee3-88a9-18b855628667
* Version Independent ID: 6cf127d4-6f3d-c9e6-3984-a38ba5a41984
* Content: [Find in Files Command - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/find-in-files-command?view=vs-2019)
* Content Source: [docs/ide/reference/find-in-files-command.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/find-in-files-command.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by mrlacey** [comment]
Seems previously reported as a bug at https://developercommunity.visualstudio.com/content/problem/976771/editfindinfiles-not-working-in-visual-studio-2019.html

**Comment by TerryGLee** [comment]
@mrlacey As this issue has been reported as a bug with the product, it's not one with the documentation. Therefore, we'll close this now. Thank you though for your feedback!

**Comment by mrlacey** [comment]
Sad this doesn't seem worth noting in the docs :(

**Comment by TerryGLee** [comment]
@mrlacey A belated thank you for taking the time to write up this issue. And a belated update: You're right, this was worth noting in the docs, and we've done so, now. We've added a note to the [Find in Files Command](https://docs.microsoft.com/visualstudio/ide/reference/find-in-files-command?view=vs-2019) page that says, "Support for this command was discontinued in version 16.5 of Visual Studio 2019. If you use this command with version 16.5 or a later version, you might see an error message that says, *Command "Edit.FindinFiles" does not accept arguments or switches.*"
