### ISSUE TITLE
SkipInvalidConfigurations missing

### ISSUE THREAD

**Issue by VerdonTrigance** [MicrosoftDocs/visualstudio-docs#5286]
Where are every parameters that begins with /p ? For example SkipInvalidConfigurations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019#see-also)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@VerdonTrigance -- thank you for your question.  Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- please look into this issue.

**Comment by ghogen** [comment]
The /p or -p is listed under -/property or -property.  That's the way you set an MSBuild property at the command line.  So SkipInvalidConfigurations is a property defined by the Visual Studio build system in Microsoft.Common.CurrentVersion.targets in the MSBuild\Bin folder in a Visual Studio installation.  It should be documented somewhere, but not in this topic. Maybe in https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019

**Comment by ghogen** [comment]
The property determines whether an invalid platform/configuration combination generates an error or a warning.  If "true", invalid combinations are skipped with a warning; otherwise, it's an error.

**Comment by ghogen** [comment]
I keep hitting the wrong button and closing, but I mean to keep this open until we add some documentation for this property somewhere.
