### ISSUE TITLE
Cannot see deploy option

### ISSUE THREAD

**Issue by chintalpatel89** [MicrosoftDocs/visualstudio-docs#5287]
Even after performing all the steps before the section "Create the publish settings file in IIS on Windows Server" I cannot see the "Deploy" option under "Default Web Site" on the IIS Manager settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c014f3-7ada-66ae-1db4-c59982504159
* Version Independent ID: 98041d92-c537-bf0a-9a11-ff50965d2cef
* Content: [Publish to IIS by importing publish settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-import-publish-settings-iis?view=vs-2019#feedback)
* Content Source: [docs/deployment/tutorial-import-publish-settings-iis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-import-publish-settings-iis.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by chintalpatel89** [comment]
As per the article "Web Deployment Agent Service" was running but "Web Management Service" was not running under the services. I had to restart the "Web Deployment Agent Service" and only after that "Web Management Service" started. After doing this I can now see the "Deploy" option.

**Comment by Mikejo5000** [comment]
@chintalpatel89 That is great feedback, thanks. I'll make an edit to the docs to clarify.
