### ISSUE TITLE
Do Directory.Build.props work for .net framework?

### ISSUE THREAD

**Issue by chucklu** [MicrosoftDocs/visualstudio-docs#5291]
I am trying to use Directory.Build.props in .net framework project, it seems did not work.
https://github.com/ChuckTest/ConcurrentTest/tree/test
Could you make a declare in documentation if the Directory.Build.props support .net framework project or not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@chucklu Thanks for the report. I've reproduced the issue, using the solution in your repo.  Investigating.

**Comment by ghogen** [comment]
@chucklu Still investigating, but in the meantime, you might be aware that you can specify the assembly version in source code in AssemblyInfo.cs in the Properties folder of the solution.  You can also set it in the Project Properties, on the Application tab, choose Assembly Information and specify the version there.

**Comment by chucklu** [comment]
@ghogen  I am trying to use https://github.com/ygoe/NetRevisionTask to embed the git commit hash into product version of assembly. I do not want use the AssemblyInfo.cs to set the version which means I need to add nuget reference for all projects.

By the way,  another person told me the version property only works for .net core project.
https://github.com/microsoft/msbuild/issues/2008#issuecomment-628029124

**Comment by chucklu** [comment]
According [Choose between adding properties to a .props or .targets file](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#choose-between-adding-properties-to-a-props-or-targets-file), I have no idea about what you are talking about .

> If you set another property there and then create a target (say in Directory.Build.targets in the same folder) to print it out,

print it out? who did this action?

**Comment by rainersigwald** [comment]
@chucklu It sounds like you have an issue with the third-party NetRevisionTask. It looks like it claims to support non-.NET Core SDK projects, but there may be a bug affecting your case.

@ghogen is demonstrating that `Directory.Build.props` is in fact imported into your project: the property `$(Version)` is observable in the project. But it doesn't do anything, because nothing reads the Version property in a standard build of a non-Core-SDK project.

**Comment by ghogen** [comment]
@chucklu Yes, to clarify, you can prove to yourself that $(Version) is set correctly (and therefore Directory.Build.props *is* read properly) by doing the following:

1. Add Directory.Build.targets to the same folder as Directory.Build.props, with content as follows:

```xml
 <Project>
  <Target Name="PrintVersion" BeforeTargets="Build">
     <Message Text="Version: $(Version)"/>
  </Target>
  </Project>
```

2. Clean and build.  You should see the version you set in the build output.
