### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5292]
@JBorras-summar commented on Nov 11, 2019 — with docs.microsoft.com
Link to "MPN Program Administrator Guide" does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f04b1d-cc98-8383-82cc-67b1be25d3ca
* Version Independent ID: e4855453-e4ed-7eb6-dbf3-5da7e79298ea
* Content: [Visual Studio subscriptions offered to partners in the Microsoft Partner Network (MPN)](https://docs.microsoft.com/en-us/visualstudio/subscriptions/program-mpn#feedback)
* Content Source: [subscriptions/program-mpn.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/program-mpn.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for raising this.

**Comment by TerryGLee** [comment]
@evanwindom FYI

**Comment by evanwindom** [comment]
@CeciAc -- Thanks for flagging that.  It looks like the program guide was replaced with a new version.  I've updated the link in the article, and it should be live soon.

**Comment by evanwindom** [comment]
#please-close
