### ISSUE TITLE
GenerateSwitchCases Line Endings

### ISSUE THREAD

**Issue by yxrkt** [MicrosoftDocs/visualstudio-docs#5293]
I seem to often have mixed line endings in my code, always in my switch statements. I believe this is because the GenerateSwitchCases snippet function generates LF line endings. If there's a better place to report this, I'd be happy to be directed there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87786dea-7de0-a5c1-cbeb-d551219f38c5
* Version Independent ID: ef34ed8f-8e9d-ee55-3dfd-7689315f2fc9
* Content: [Code Snippet Functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippet-functions?view=vs-2019#feedback)
* Content Source: [docs/ide/code-snippet-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-snippet-functions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@yxrkt -- thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by yxrkt** [comment]
Thank you!

**Comment by WilliamAntonRohm** [comment]
You're welcome!
