### ISSUE TITLE
Navigate among Tool Windows Instruction Anomaly

### ISSUE THREAD

**Issue by nick1941** [MicrosoftDocs/visualstudio-docs#5295]
In the section "Navigate among tool windows in the IDE", the last line has instructions for "Navigate among Files in the Editor" instead of "tool windows."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ee07712-936b-ed70-835c-b5cf97ad06aa
* Version Independent ID: 689c4231-f16d-2ffe-efa2-46d6cf91f409
* Content: [How to move around in the IDE - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-move-around-in-the-visual-studio-ide?view=vs-2019)
* Content Source: [docs/ide/how-to-move-around-in-the-visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-move-around-in-the-visual-studio-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@nick1941 -- thank you for your feedback.  I am not seeing that phrase in that section, so I am closing this issue now.

**Comment by nick1941** [comment]
Here is the URL: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-move-around-in-the-visual-studio-ide?view=vs-2019

 

Here is the erroneous section (highlighted).

 

Navigate among tool windows in the IDE

The IDE Navigator also lets you cycle through the tool windows you have open in the IDE. You can use either of two commands to access the IDE Navigator to cycle through tool windows, depending on the order in which you want to cycle through. Window.PreviousToolWindowNav allows you to move to the file most recently accessed and Window.NextToolWindowNav allows you to move in the reverse order. General Development Settings assigns Shift+Alt+F7 to Window.PreviousDocumentWindowNav and Alt+F7 to Window.NextDocumentWindowNav.

 

 

Nick Piazza

**Comment by TerryGLee** [comment]
@nick1941 I can't see the highlight in your response; was it this sentence that you were concerned with?

"The IDE Navigator also lets you cycle through the tool windows you have open in the IDE. "

**Comment by nick1941** [comment]
No, it is this sentence:

 

“General Development Settings assigns Shift + Alt + F7 to Window.PreviousDocumentWindowNav and Alt + F7 to Windows.NextDocumentWindowNav.”

 

Since the segment is about “Navigate among tool windows in the IDE”, the sentence should be related for instructions regarding Window.PrevioustoolWindowNav and Window.NexttoolWindowNav instead of the “Document” window navigation instructions.

 

Nick Piazza

**Comment by TerryGLee** [comment]
@nick1941 Thanks for the clarification. We'll look into this and report back.
