### ISSUE TITLE
Can be misleading

### ISSUE THREAD

**Issue by tdworshak** [MicrosoftDocs/visualstudio-docs#5297]
This warning can be misleading. Developers typically call ToString() explicitly to avoid boxing and the related performance penalty. Making the suggested change defeats this optimization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ccd9512e-fd70-0730-d2b0-27109bdb1704
* Version Independent ID: 3be2a986-43b2-e3b8-e5c2-29aab9257c96
* Content: [Simplify string interpolation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/simplify-string-interpolation?view=vs-2019)
* Content Source: [docs/ide/reference/simplify-string-interpolation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/simplify-string-interpolation.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@tdworshak -- thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. 

cc @mikadumont for awareness
