### ISSUE TITLE
Instructions incomplete

### ISSUE THREAD

**Issue by JN-LT** [MicrosoftDocs/visualstudio-docs#5298]
Under "Add a reference" on this page, you say "In Solution Explorer, right-click on the References or Dependencies node ...".

Where do I find the 'References or Dependencies node'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284369-f16f-2748-2a55-8cd24a06b940
* Version Independent ID: f7b0c577-b584-98dc-90a2-4efcf095b35d
* Content: [Add references in the Reference Manager - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2019#feedback)
* Content Source: [docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@JN-LT -- thank you for your question.  The sentence is referring to two distinct nodes, one named **References** and one named **Dependencies**.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by JN-LT** [comment]
@WilliamAntonRohm Since neither **References** nor **Dependencies** appears anywhere in the Solution Explorer panel, I don't see how this answers my question.

![Solution Explorer](https://user-images.githubusercontent.com/55243838/82097929-860fd980-96c9-11ea-9238-cfaf20eb0de9.jpg)

**Comment by WilliamAntonRohm** [comment]
@JN-LT -- thank you for clarifying.  Please try these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
