### ISSUE TITLE
Step missing for setting up numpy in the python environment on the Deep Learning Virtual Machine

### ISSUE THREAD

**Issue by nzigel** [MicrosoftDocs/visualstudio-docs#530]
After provisioning a Deep Learning Virtual Machine on Azure there is a step missing in setting up numpy in the python environment on that machine. As a result of this the job fails in File "convolutional.py", line 32, in <module> import numpy ImportError: No module named numpy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ff24ba6-41f5-f6a5-949a-54d8e4df7e0e
* Version Independent ID: bb68990d-084f-be46-8c0a-6c9d34a060ac
* [Content](https://docs.microsoft.com/en-us/visualstudio/ai/tensorflow-vm)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ai/tensorflow-vm.md)
* Service: multiple

**Comment by gewarren** [comment]
@nzigel Thank you for the feedback. @rloutlaw is there anyone I can assign this to to add the missing step?

**Comment by chris-lauren** [comment]
@Genevieve Warren<mailto:Genevieve.Warren@microsoft.com> I believe this was the issue we just confirmed worked as documented and should be closed correct?

**Comment by gewarren** [comment]
Ameya confirmed that the documented steps actually do work correctly. Closing this issue.
