### ISSUE TITLE
Missing documentation for security warnings CA5359, CA5360 and CA5362

### ISSUE THREAD

**Issue by chadsugithub** [MicrosoftDocs/visualstudio-docs#5301]
Security Warnings - Visual Studio

CA5359 Do Not Disable Certificate Validation
CA5360 Do Not Call Dangerous Methods In Deserialization
CA5362 Do Not Refer Self In Serializable Class

They are missing on https://docs.microsoft.com/en-us/visualstudio/code-quality/security-warnings?view=vs-2019. And clicking the links (CA5359, CA5360 and CA5362) on https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeAnalysis.FxCopAnalyzers/Microsoft.CodeAnalysis.FxCopAnalyzers.md results in 404 - Page not found.

**Comment by Mikejo5000** [comment]
CA5359 and CA5362 are live now.
CA5360 is merged and will be getting published soon.
