### ISSUE TITLE
Require updates on shortcut keys for "comment out code"

### ISSUE THREAD

**Issue by Antonio-Kim** [MicrosoftDocs/visualstudio-docs#5302]
Microsoft Visual Studio Community 2019
Version 16.5.4

Initially, the text editor toolbar was not shown and required some digging around to enable it. Please add this instruction to the tutorial in the near future. Also, even though the shortcut keys to comment (Ctrl+K, Ctrl+C) does comment out the blocked codes, the Studio indicates that the shortcut command  Ctrl+E, Ctrl+C is another way to comment out the code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7651b1f-ceaf-cccf-a47d-bee98d8806e0
* Version Independent ID: ecb6330d-4205-1b65-4fbf-ddb6552b3890
* Content: [Introduction to editing for C# developers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-editor?view=vs-2019#feedback)
* Content Source: [docs/get-started/csharp/tutorial-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Antonio-Kim Thanks for letting us know; we'll check in to getting this tutorial updated and report back soon.
