### ISSUE TITLE
VS 2019 for python project, in add reference, where the Browse button/Tab gone?

### ISSUE THREAD

**Issue by haithamsungkar** [MicrosoftDocs/visualstudio-docs#5305]
since I migrating from VS2015 to VS2017 or VS2019, I don't know how to:
- resolve import clr
- activate intellisense after clr.&lt;....&gt; 
- add reference to external dll to my IronPython project and activate intellisense for their related dependency

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d59f61b3-8cae-f461-e85e-5c159a56e7c4
* Version Independent ID: 80d076a4-12f3-e0b2-7793-33e8d8f1840a
* Content: [Manage Python application projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-projects-in-visual-studio?view=vs-2019#feedback)
* Content Source: [docs/python/managing-python-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/managing-python-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@haithamsungkar -- thank you for your question. It looks like you're having an issue with the products themselves. Here are a few options where you might consider asking your question:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.
