### ISSUE TITLE
To submit a support request using the benefit, you must first activate it. Follow the steps in the next section to complete the activation.

### ISSUE THREAD

**Issue by 5U8cVs** [MicrosoftDocs/visualstudio-docs#5306]
I must first activate it.  Presumably Microsoft executives decided to make using the "benefit" as difficult as possible to limit the ability of their paying customers to use it.  I've used it several times.  The Indian and Philippine technicians are friendly, somewhat knowledgeable, and have the phone number of developers in Washington state.  The results are not necessarily satisfactory.  BREAK/FIX is quite the concept.   Pure B.S.  That Microsoft obligates itself to fix problems in only NON-PRODUCTION environments speaks volumes about Microsoft's commitment to product quality.  I have often tried to engage the highly paid executives at Microsoft in a debate about their misguided policies.  No response.  The line to the executive suite is dead.  I can only conclude that the metric that matters to Microsoft executives is those year-end bonuses.   Customer satisfaction may be 99.9% of users who get Windows with their PC along with Office 365.  In my organization we do a whole lot more ON our PCs than typically is done.  Does Microsoft care?  No evidence of that.  As for this page...  Well, I have paid Microsoft tons of money over the years for being a "developer" in the "network."    It is no longer called that.  But I felt it was a necessary expense in order to get non-production exposure to the products which I do get paid to configure and maintain.  Cortana seems to be a big executive concern at Microsoft.  As a customer I would tell the executives to dump it like Trump.   Cortana is absolutely useless.  Treat it like you did Frontpage.    There are constituencies other than shareholders in Microsoft stock.  It is time to pay attention to people like me who are not the idiots Microsoft executives assume them to be.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79453c-3962-2f0c-5b99-4fbde91972f8
* Version Independent ID: c845c29e-dfd7-316e-81b2-ebe288a384c1
* Content: [Technical Support Benefit](https://docs.microsoft.com/en-ca/visualstudio/subscriptions/vs-tech-support#feedback)
* Content Source: [subscriptions/vs-tech-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-tech-support.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@5U8cVs -- thank you for your feedback.
