### ISSUE TITLE
XAML Tag 'OnPlatform' deprecated

### ISSUE THREAD

**Issue by RSadocchi** [MicrosoftDocs/visualstudio-docs#531]
The XAML tag OnPlatform is deprecated, outherwise we can use the Device object (code behind) like: 
switch (Device.RuntimePlatform)
{
    case Device.UWP:
        break;
    case Device.iOS:
        break;
    case Device.Android
        break;
.......
}

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 3b25d4cd-0c3f-e9a6-6256-ea54d0972d4b
* Version Independent ID: babd49b7-8e18-13dc-99f2-6783495cb0dc
* [Content](https://docs.microsoft.com/it-it/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr.it-it/blob/live-sxs/docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md)
* Service: unspecified

**Comment by gewarren** [comment]
@RSadocchi thank you for the feedback. We hope to have updated Xamarin docs soon.

**Comment by jclark993** [comment]
I got compiler error when trying to Build WeatherApp
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0656	Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'	WeatherApp	C:\...\source\repos\WeatherApp\WeatherApp\WeatherApp\Core.cs	17	Active

What is the fix for this, thanks

**Comment by charlespetzold** [comment]
The **Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'** error can result from using a `dynamic` variable in a .NET Standard 2.0 library. To fix it, add the **Microsoft.CSharp** NuGet package to the **WeatherApp** library.

Updated versions of the **WeatherApp** sample will be published soon.

**Comment by mekwebsite-dev** [comment]
Hi, also please remove  Microsoft.Net.Http NuGet package.

**Comment by charlespetzold** [comment]
If you're talking about the Xamarin.Forms weather sample, which is here:

https://github.com/xamarin/xamarin-forms-samples/tree/master/Weather

the **Microsoft.Net.Http** package was removed in January. The cross-platform native version of Weather:

https://github.com/xamarin/mobile-samples/tree/master/Weather

is currently being revised.

**Comment by jclark993** [comment]
Yeah I got it working.    Thanks!
  

  
  

  
  
>

**Comment by conceptdev** [comment]
Docs & sample are in the process of being updated. Thanks for the feedback!
