### ISSUE TITLE
Browser support doesn't match between different docs pages

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/visualstudio-docs#5317]
Browser support doesn't match between:
- https://docs.microsoft.com/en-us/visualstudio/deployment/choosing-a-clickonce-deployment-strategy?view=vs-2019#web-browser-support

> ## Web browser support
> Applications that target .NET Framework 3.5 can be installed using any browser.
> Applications that target .NET Framework 2.0 require Internet Explorer.

... and:
- https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-security-and-deployment

> |Browser|.NET Framework version|
> |-------------|----------------------------|
> |Internet Explorer|2.0, 3.0, 3.5, 3.5 SP1, 4|
> |Firefox|2.0 SP1, 3.5 SP1, 4|

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d23f344-069f-b648-ed6c-2bb5ca771af8
* Version Independent ID: 1af9f79c-7ca4-fce9-e261-c63119b789eb
* Content: [Choosing a ClickOnce Deployment Strategy - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/choosing-a-clickonce-deployment-strategy?view=vs-2019#feedback)
* Content Source: [docs/deployment/choosing-a-clickonce-deployment-strategy.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/choosing-a-clickonce-deployment-strategy.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please let me know which document is correct and I will update the other one.

**Comment by alfredmyers** [comment]
> @Mikejo5000 -- Mike, please let me know which document is correct and I will update the other one.

While at it, support info on Chrome and Edge would be a nice addition to the docs

**Comment by Mikejo5000** [comment]
Looks like the table needs an update. According to the first referenced doc, .NET 3.5 is required for general browser support. Updating.
