### ISSUE TITLE
very helpful tutorial

### ISSUE THREAD

**Issue by asherabrams** [MicrosoftDocs/visualstudio-docs#532]
As someone new to coding, I found this a very useful and user-friendly introduction to creating a C# application in VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d76c8494-9961-83b4-9591-6696b684b6f8
* Version Independent ID: 1ff35af8-a624-f51d-4426-345f821d3eff
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/step-11-run-your-program-and-try-other-features)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/step-11-run-your-program-and-try-other-features.md)
* Service: unspecified

**Comment by gewarren** [comment]
@asherabrams thanks for the feedback! @TerryGLee

**Comment by TerryGLee** [comment]
@asherabrams Thanks again; we appreciate your feedback!
