### ISSUE TITLE
Stop the debugger instruction is under wrong header

### ISSUE THREAD

**Issue by yihezkel** [MicrosoftDocs/visualstudio-docs#5320]
The line, "Stop the debugger by pressing the Stop Debugging red button Stop Debugging or Shift + F5." is under the section heading, "Run to cursor". It doesn't belong there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed9dcc5d-ade9-c88a-76f6-538231671b0b
* Version Independent ID: 6d86c444-dba6-8d0e-4b2c-a4cc57c11365
* Content: [First look at the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debugger-feature-tour?view=vs-2019#feedback)
* Content Source: [docs/debugger/debugger-feature-tour.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debugger-feature-tour.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- please review [private PR 6597](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6597).
