### ISSUE TITLE
Explain 'benefits'

### ISSUE THREAD

**Issue by iamalexmang** [MicrosoftDocs/visualstudio-docs#5324]
Hi! I'm trying to understand the benefits table.
Can you please elaborate the meaning of 'benefit'? More specifically, if I only have VS Professional Subscribers, can I NOT use Azure Pipelines, either hosted or self-hosted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@iamalexmang Hi Alex.  Professional subscriptions have access to the Basic Plan.  Details of what's included are available here:  https://azure.microsoft.com/pricing/details/devops/azure-devops-services/ 

Professional subscriptions should have one hosted and one self-hosted pipeline.

**Comment by WilliamAntonRohm** [comment]
@iamalexmang -- Alex, thank you for your questions.  Here are some additional resources:
- If you have a subscription, contact [Visual Studio Subscriptions Support](https://visualstudio.microsoft.com/subscriptions/support/).​ 
- If you are not sure if you have a subscription, sign in to [https://my.visualstudio.com/subscriptions](https://my.visualstudio.com/subscriptions) to see all the subscriptions assigned to your email address.​ 
- If you do not have a subscription, consider using either our [Live Chat]( https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation issues, or reaching out to us and other Visual Studio developers through our [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

 
@evanwindom -- thank you for answering.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by iamalexmang** [comment]
Thanks for the replies. 
Respectfully though, I am still extremely confused by the page, especially with the extra link provided by @evanwindom. If you care to take a look at the page I've opened the issue for, it says Azure Pipelines (self-hosted) is a benefit for Visual Studio Enterprise with GitHub Enterprise, but **NOT** for Visual Studio Professional (Standard, monthly cloud).
Yet my organization has 10 Visual Studio Enterprise subscribers and has no benefits compared to any other organization.
This begs the question: if we are to downgrade our subscriptions to Professional, are **we going to be blocked from using Azure Pipelines in self-hosted**?
Similarly, **are we going to be prevented from using test-plans** (which is in the same case)? 
If the answer is NO, can you please elaborate what the benefit actually is?
According to 

> Professional subscriptions have access to the Basic Plan

you'd assume Professionals and Enterprise subscribers have the same benefits. Yet the page linked above says different.

To add to the confusion, the page here (https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/), also linked by @evanwindom, mentions that '_Subscribers get access to any number of accounts and don't count against your 5 free users._', which does not refer to the benefits page.

Looking forward to hearing from you.

**Comment by evanwindom** [comment]
@iamalexmang Hi Alex.  I don't understand what you mean when you say "Yet my organization has 10 Visual Studio Enterprise subscribers and has no benefits compared to any other organization."  Can you elaborate on that, please?

**Comment by iamalexmang** [comment]
Despite the number of subscribers, we got a single self-hosted pipeline which doesn't suggest that would be a benefit of the subscriber.
That might suggest that if we don't have the Enterprise subscriptions anymore, but Professional ones we might loose the ability of using even that single self-hosted pipeline, which is apparently free.
Avertedly, any other organization also gets a free self-hosted pipeline. Which therefore implies the supposed benefit isn't a benefit. 
Which brings me back to the issue: because of the very confusing and non-elaborated table of benefits, it is unclear what the self-hosted benefit the table refers to and whether, once we downgrade, the functionality will still be available or not.

**Comment by evanwindom** [comment]
@iamalexmang We've made some changes to the article to provide some clarity.   Remember that the content of the Basic plan is determined by Azure, not by the Visual Studio subscription.  Both Professional and Enterprise receive the Basic plan.  If there are question about the implementation and use of the Basic plan, those should be addressed with Azure support.

**Comment by evanwindom** [comment]
#please-close

**Comment by iamalexmang** [comment]
Is the update not yet published? The article was last updated on March 24th. Are you sure we are referring to the same article?
I ask this specifically because the article has an eligibility section which enumerates the type of Visual Studio subscriptions, and yet in your last comment you're mentioned _the content of the Basic plan is determined by Azure, not by the Visual Studio subscription._
What is undeniably confusing, after having customers raise the exact question over the past two weeks is whether or not Visual Studio Professional subscribers get Azure Pipelines self-hosted benefits or not.

In my opinion, the best way to clear up that confusion is to replace "Azure Pipelines (self-hosted)" and replace that with "Included additional self-hosted parallel jobs", for example. I believe strongly that this would emphasize that every subscriber gets access to use Azure Pipelines in any way they choose, but the fact that they are an **enterprise** subscriber gets them additional parallelism of their jobs, granted their using self-hosted agents.

**Comment by evanwindom** [comment]
The Azure team determines the contents of the “Basic” offer.  The PR has been submitted and merged but has apparently not gone live yet.

**Comment by evanwindom** [comment]
Since the content hasn’t gone live yet, I’ve made a couple of additional updates and submitted a new PR.

From: Evan Windom
Sent: Wednesday, July 22, 2020 2:36 PM
To: MicrosoftDocs/visualstudio-docs <reply@reply.github.com>; MicrosoftDocs/visualstudio-docs <visualstudio-docs@noreply.github.com>
Subject: RE: [MicrosoftDocs/visualstudio-docs] Explain 'benefits' (#5324)

The Azure team determines the contents of the “Basic” offer.  The PR has been submitted and merged but has apparently not gone live yet.

**Comment by iamalexmang** [comment]
Do you mind linking the PR? The article is still not uodated and shows March 24th as the last change. On GitHub, it shows as it was last updated on April 10th, without having the date updated.

Also, respectfully, please understand that I’ve never argued the content of the Basic plan. Quite the contrary, the purpose of the Issue is to emphasize the confusion of enjmearting Azure Pipeline as an exclusive benefit of an Visual Studio Enterprise subscriber.

For that bery reason I rethorically asked: if I downgrade my subscription to another SKU, am I blocked from using Pipelines? Of course I can still use Pipelines! My apologies if that was too obscure...

After all, that was even the reason of suggesting the change in the first place: mentioning “additional self-hosted parallel job” or something along that lines.
As of right now, the table eludes that the usage of Azure Pipelines (self-hostes) is an exclusive benefit of Visual Studio Enterprise subscribers, which is incorrect.

Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by evanwindom** [comment]
Okay, for clarity:

  1.  No, pipelines are not exclusive to Enterprise subscriptions.
  2.  No, if you downgrade, you will not be blocked from using pipelines.

Pipelines are included in the Basic plan.  So, if the subscription has Basic, it has pipelines.

**Comment by iamalexmang** [comment]
Thanks for clarifying.
That's exactly the point I'm making too, but not what the document article describes.
To its point, the article 'Azure DevOps **benefits** for Visual Studio subscribers' is listing the following **benefit** _exclusively_ available for Visual Studio Enterprise subscribers: **Azure Pipelines (self-hosted)**, which is, respectfully, simply incorrect and not the same as mentioned by you or to what I eluded before. 
That's because 
- Azure Pipelines is not a benefit, irrelevant if the job is running on self-hosted agent or not
- Azure Pipelines is available irrelevant of the Visual Studio subscription level, irrelevant if the job is running on a self-hosted agent or not

The actual benefit, which is nowhere deterministic by the article (which is the reason of the issue - not sure why it's closed yet), is that Visual Studio Enterprise (only) subscribers get additional non-extra paid parallel jobs for self-hosted agents. Would you agree?

![image](https://user-images.githubusercontent.com/5773281/88260745-ae214780-cccd-11ea-8bd1-12ae6ace7e05.png)

**Comment by evanwindom** [comment]
Ahh….  I see now.  My apologies for all the churn.  I’m not an Azure expert so I was struggling with the distinction.

Here’s a piece of content from Azure’s documentation that I think clarifies the issue.

As a Visual Studio Enterprise subscriber, do I get additional parallel jobs for TFS and Azure Pipelines?
Yes. Visual Studio Enterprise subscribers get one parallel job in Team Foundation Server 2017 or later<https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-pipelines-tfs?view=azure-devops> and one self-hosted parallel job in each Azure DevOps Services organization where they are a member.
So, yes – it looks like the Basic plan is talking about Microsoft-hosted jobs, and the Enterprise subscriptions come with an additional self-hosted parallel job as described here.

It looks like my earlier clarifications were INCORRECT in light of the “self-hosted” distinction.  I’m going to validate this with Azure before finalizing the article.
