### ISSUE TITLE
Project will still use old format

### ISSUE THREAD

**Issue by Duranom** [MicrosoftDocs/visualstudio-docs#5325]
Perhaps a small notification in the documentation that the project generated still uses the old format, meaning if you have such a project and collaborate with developers that use Visual Studio Code or other tools that your project will not reflect added or removed files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59adf9c7-5894-84ba-32ee-df842aa4658d
* Version Independent ID: 50683e7c-4b31-1773-f20e-00732a0ffbcc
* Content: [Quickstart: Create your first Vue.js app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/quickstart-vuejs-with-nodejs?view=vs-2019#feedback)
* Content Source: [docs/javascript/quickstart-vuejs-with-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/quickstart-vuejs-with-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Duranom I'm looking at this. By "old format", what are you referring to? Updates to the project file, or and older version of vue.js? Please clarify. Thanks.

**Comment by Mikejo5000** [comment]
@Duranom Do you have a link to info on a new project format? I've checked the release notes, and I don't see anything. Thanks.

**Comment by Duranom** [comment]
Sorry for late response. I mean that the nsproj that is being created uses an old way to define files and folders in the structure unlike projects created for .net core which includes all code files immediately. This means if you use this way to create and/or manage a Vue.js project and you collaborate with developers who use edit or add files in another way can result in Visual Studio not showing a files inside the project until you add an existing file, which can lead to confusion.

A small workaround in such a case is to add in the nsproj file a <Content Include="**"> for every directory inside the project that is created and/or later added, but it does not cover all cases as the root content of the project will only be added a single time this way.

**Comment by Mikejo5000** [comment]
OK, thanks for the clarification. Yes, .NET Core uses a newer project format. This would require some updates to the product to support something similar for nsproj. If you don't mind, would you please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html).
If the workaround doesn't fully resolve the issue, then it's best to get a change to the product.
