### ISSUE TITLE
Include ASCII codes!

### ISSUE THREAD

**Issue by saundecp** [MicrosoftDocs/visualstudio-docs#5327]
Come on, the advice is "Use the notation %&lt;xx&gt; in place of the special character, where &lt;xx&gt; represents the hexadecimal value of the ASCII character." You've got a table already, can you please provide the ASCII codes here for each character as a column?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e990c1d-5b08-0b80-6851-68bd737f9c7b
* Version Independent ID: f898e9ad-99e7-5584-4b7e-a808d3f63728
* Content: [Special Characters to Escape - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/special-characters-to-escape?view=vs-2019#feedback)
* Content Source: [docs/msbuild/special-characters-to-escape.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/special-characters-to-escape.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@saundecp Thanks for your feedback, we could do that.  In the meantime, type "ascii table" into a search engine to bring up the hex codes.

This might be a good opportunity for a community contribution - you are welcome to submit a PR to add the codes in our GitHub repo.

**Comment by saundecp** [comment]
@ghogen - Done, great idea, thanks :)
