### ISSUE TITLE
Statement on signing manisfests in the Publish Wizard seems incorrect.

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/visualstudio-docs#5331]
The section on [Code-signing certificates](https://docs.microsoft.com/en-us/visualstudio/deployment/securing-clickonce-applications#code-signing-certificates) states:

> ... Alternatively, you can sign the manifests with a key file during the publishing process, using the Publish Wizard.

... but there's no such option on Publish Wizard (tested on Visual Studio 15.5.0) and [How to: Publish a ClickOnce Application using the Publish Wizard](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard) states:

> Before you run the Publish Wizard, you should set the publishing properties appropriately. For example, **if you want to designate a key to sign your ClickOnce application, you can do so on the Signing page of the Project Designer**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe8cafe-31f2-f1fc-2a56-3cc60abe530a
* Version Independent ID: 7d725c68-64d8-76b4-33a3-cd9c731554e9
* Content: [Securing ClickOnce Applications - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/securing-clickonce-applications?view=vs-2019#see-also)
* Content Source: [docs/deployment/securing-clickonce-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/securing-clickonce-applications.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Verified this. Removing the incorrect statement. Thanks!
