### ISSUE TITLE
Multitargeting?

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#5332]
Based on the information [here](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2019), it seems that the debugger-side and debuggee-side code need to reside in separate DLLs. But what is still unclear, is if I want to write a visualizer that targets multiple frameworks, the debuggee-side code needs to be multitargeted, like [this](https://github.com/zspitz/ExpressionTreeVisualizer/blob/master/Debuggee/Debuggee.csproj#L4); and it's not at all clear from the documentation which frameworks can/should be targeted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb4b6f3-7c88-077e-26a6-c840c7081bd0
* Version Independent ID: 03b40f67-739c-dbcf-4a88-2ab8e9d1313b
* Content: [Create custom data visualizers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2019)
* Content Source: [docs/debugger/create-custom-visualizers-of-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-visualizers-of-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@WardenGnaw Are all TFM values supported in the debuggee-side code?
Or only a subset?
https://docs.microsoft.com/en-us/dotnet/standard/frameworks

**Comment by zspitz** [comment]
@Mikejo5000 Any way I can see a diff of the changes?

**Comment by Mikejo5000** [comment]
Yes, as soon as it goes live, which should be by noon today. Changes are in the create-custom-visualizers-of-data.md and how-to-install-a-visualizer.md. You can check the history for those topics.

**Comment by Mikejo5000** [comment]
https://github.com/MicrosoftDocs/visualstudio-docs/commit/e2ed44c7a9bf463f68a261562d00ca0697270015#diff-234817d7e925d10670ca74586ed5ef78

and 

https://github.com/MicrosoftDocs/visualstudio-docs/commit/e2ed44c7a9bf463f68a261562d00ca0697270015#diff-30adef46d3a9f3cc3bb5f2ab80035d3e
