### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by v-radelg** [MicrosoftDocs/visualstudio-docs#5341]
@Chadoxi commented 10 hours ago — with docs.microsoft.com

Hello, I would like to know because not long ago, I made a generator with visual studio which generates dummy bank cards. my teacher thinks it was a real one when i just wanted to test a shop site to see their negative answer because the card did not pass because i am developing a site.
Can I know if I make a generator without the need for internet is legal?
Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26fa83b1-ca9d-0800-423b-ce6f4a1668a8
* Version Independent ID: fc5869c5-4d4b-bba3-1c32-caf9d13dfd21
* Content: [Code Generation and T4 Text Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019#feedback)
* Content Source: [docs/modeling/code-generation-and-t4-text-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/code-generation-and-t4-text-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@v-radelg -- Ramiro, thank you for raising this issue.  Please convey the following to @Chadoxi:

> Merci pour votre question.  Ce sujet est en dehors de notre documentation technique, et je regrette de ne pas pouvoir vous offrir des réponses.
