### ISSUE TITLE
Third-party dependency management

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#5346]
I know I can use third-party libraries in my visualizer as long as they are in the same folder as the debugger or debuggee DLLs. However, I am liable to break other visualizers if I overwrite their version of the library with my own. I would also like to avoid my own visualizers being broken. Is there any guidance on how to handle this?

Any solution needs to work with both the debugger DLL and the debuggee DLL.

The simplest solution (from a developer's perspective) might be to use something like .NET Core's single-file publish, IL Merge, or Fody Costura. But that comes with [it's own really-hard-to-debug problems](https://github.com/zspitz/ExpressionTreeVisualizer/issues/112).

Alternatively, perhaps it might be possible for each visualizer to put third-party dependencies in a dedicated subfolder? As it is, the primary DLLs are potentially spread across four folders -- [the root visualizers folder, and three subfolders for each target framework](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2019#to-install-a-visualizer-for-visual-studio-2019). Having each visualizer maintain a separate subfolder structure for dependencies would look like this (files in parentheses):

    Visualizers
        (MyVisualizer.dll)
        MyVisualizer
            (Dependency1.dll)
            (Dependency2.dll)    
        net2.0
            (MyVisualizer-Debuggee.dll)
            MyVisualizer
                (Dependency3.dll)
                (Dependency4.dll)
        netstandard2.0
            (MyVisualizer-Debuggee.dll)
            MyVisualizer
                (Dependency3.dll)
                (Dependency4.dll)
        netcoreapp
            (MyVisualizer-Debuggee.dll)
            MyVisualizer
                (Dependency3.dll)
                (Dependency4.dll)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb4b6f3-7c88-077e-26a6-c840c7081bd0
* Version Independent ID: 03b40f67-739c-dbcf-4a88-2ab8e9d1313b
* Content: [Create custom data visualizers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2019)
* Content Source: [docs/debugger/create-custom-visualizers-of-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-visualizers-of-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@zspitz -- Zev, it looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​

**Comment by zspitz** [comment]
@WilliamAntonRohm Thank you for your response.

I am sure there are any number of solutions which don't involve changing the way Visual Studio loads the visualizer DLLs (e.g. specifying output paths in subfolders with a structure similar to what I described). But I think the documentation should describe the problem, and describe one or more possible solutions; and this can be done right away. At such point when the product is changed to better handle this out of the box, then the documentation can be revisited.

**Comment by zspitz** [comment]
I've implemented [this](https://github.com/zspitz/Periscope.Debuggee/blob/master/SubfolderAssemblyResolver.cs).

**Comment by WilliamAntonRohm** [comment]
@zspitz -- Zev, thank you for your followup.

@Mikejo5000 -- Mike, please look into this potential documentation issue.

**Comment by Mikejo5000** [comment]
@WardenGnaw Andrew, do you have a suggestion on how to resolve the issue of third-party dependency management, as described here?

**Comment by WardenGnaw** [comment]
We have someone currently reviewing this problem on this [feature request](https://developercommunity.visualstudio.com/content/idea/1046755/improve-ease-dependency-management-for-custom-visu.html).

**Comment by Mikejo5000** [comment]
We had some offline discussion; classifying this as a product issue, no doc update planned.

**Comment by zspitz** [comment]
@Mikejo5000 

As I noted [above](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5346#issuecomment-633129596), as long as it hasn't been fixed in the product, the documentation is still lacking.

For the visualizers I've written, I tried a number of solutions that were all incredibly fragile and difficult to debug before settling on [this](https://github.com/zspitz/Periscope.Debuggee/blob/master/SubfolderAssemblyResolver.cs). The entire process was very frustrating both for me and the users of the visualizers.

> We had some offline discussion

Could I request some information about this discussion?
