### ISSUE TITLE
Questions?

### ISSUE THREAD

**Issue by joerattz** [MicrosoftDocs/visualstudio-docs#5347]
I have a couple questions.

1.  So the DebuggerVisualizerAttribute goes on both the debugger and debuggee sides?

2.  If I have to add attributes to the object type I want the visualizer for, I assume I can't create a custom visualizer for classes I don't have the code for, specifically string in my case?  I would like to create a custom string visualizer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb4b6f3-7c88-077e-26a6-c840c7081bd0
* Version Independent ID: 03b40f67-739c-dbcf-4a88-2ab8e9d1313b
* Content: [Create custom data visualizers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2019#feedback)
* Content Source: [docs/debugger/create-custom-visualizers-of-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-visualizers-of-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@joerattz -- thank you for your questions. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 


cc @Mikejo5000 for awareness

**Comment by Mikejo5000** [comment]
@joerattz Did you try the walkthrough here: https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2019
I believe that will answer your questions, since they create a visualizer for a string. If that doesn't work in your scenario, you should be able to extend the string class and create the visualizer on the extended class.
