### ISSUE TITLE
Confusing

### ISSUE THREAD

**Issue by joerattz** [MicrosoftDocs/visualstudio-docs#5348]
I understand that there are two sides, debugger and debuggee but I'm finding the documentation very confusing.  For example, it says:

"To add the debuggee-side code
    Add the following attribute code to DebuggerSide.cs, after the using directives but before namespace MyFirstVisualizer"

How does adding an attribute to the DebuggerSide.cs add it to the debuggee side?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5d2403-0edc-8ee9-22f6-6ca370b40346
* Version Independent ID: d34a6007-354e-0bdb-3ad7-9f15a2cb56f2
* Content: [Write a visualizer in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2019)
* Content Source: [docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@joerattz In the example here, the attribute specifies System.String, which is the name of the visualizer object source, i.e., the "debuggee". I can clarify that in the description. Did the steps in the article work for you?
