### ISSUE TITLE
Both sides must have assemblies added?

### ISSUE THREAD

**Issue by joerattz** [MicrosoftDocs/visualstudio-docs#5349]
It looks like both the debugger and debuggee side must have the assembly of the other linked in?  Is that correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb4b6f3-7c88-077e-26a6-c840c7081bd0
* Version Independent ID: 03b40f67-739c-dbcf-4a88-2ab8e9d1313b
* Content: [Create custom data visualizers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2019#feedback)
* Content Source: [docs/debugger/create-custom-visualizers-of-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/create-custom-visualizers-of-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@joerattz -- thank you for your questions.

@Mikejo5000 -- please look into this issue.

**Comment by Mikejo5000** [comment]
Both sides must have a reference to the DebuggerVisualizers DLL.
Only the debuggee side needs a reference to the debugger side DLL.
The debugger side needs the attribute that specifies the object source (debuggee objects to visualize).
I will do a couple edits to clarify.
