### ISSUE TITLE
I don't think the sample is correct - running the msbuild task in batching mode will run each batch item sequentially.

### ISSUE THREAD

**Issue by robertunoki** [MicrosoftDocs/visualstudio-docs#535]
Here's a much simpler sample that actual works...

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="Parent">

  <Target Name="Child">
    <Message Text="Hello from child $(childid)"/>
    <Exec Command="powershell.exe -command sleep 5"/>
  </Target>

  <ItemGroup>
    <Projects Include="$(MSBuildProjectFile)"><Properties>childid=0</Properties></Projects>
    <Projects Include="$(MSBuildProjectFile)"><Properties>childid=1</Properties></Projects>
    <Projects Include="$(MSBuildProjectFile)"><Properties>childid=2</Properties></Projects>
  </ItemGroup>
  
  <Target Name="Parent">
    <MSBuild Projects="@(Projects)" Targets="Child" BuildInParallel="true"/>
  </Target>
  
</Project>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a625a3cf-0959-49fc-d5ee-af8971bce20c
* Version Independent ID: ddfe2557-53b6-5cff-c7b9-4a729f53ce70
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/building-multiple-projects-in-parallel-with-msbuild)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/building-multiple-projects-in-parallel-with-msbuild.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Fix in place

**Comment by robertunoki** [comment]
Hey Mike - thanks for fixing.  When can we expect to see the updated content?
