### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by nateepaul** [MicrosoftDocs/visualstudio-docs#5350]
my vs studio doesn't have a view other windows option

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca858db-d7bf-c894-af0a-eb1ba07c29ea
* Version Independent ID: 330f9197-38cd-73b7-c2cc-5d032a3bdc33
* Content: [Python in Visual Studio tutorial step 5, install packages](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2019#feedback)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@nateepaul -- thank you for your feedback. It looks like you're having an issue with the product itself. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
