### ISSUE TITLE
Example not valid with the upcoming .NET 5

### ISSUE THREAD

**Issue by jairbubbles** [MicrosoftDocs/visualstudio-docs#5352]
TFM for .NET 5 will be `net5.0` (see https://devblogs.microsoft.com/dotnet/announcing-net-5-preview-4-and-our-journey-to-one-net/). Using this condition will probably break things when porting projects to .NET 5 as it is more similar to .NET Core than .NET Framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019#feedback)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@jairbubbles -- thank you for your feedback.  Please clarify your issue.  Are you referring to this condition?

>     <PropertyGroup Condition="'$(TargetFramework.TrimEnd(`0123456789.`))' == 'net'">

**Comment by jairbubbles** [comment]
Yes! I think removing the trimming of `.` should fix it.
