### ISSUE TITLE
Poor guidance for newcomers. Walkthrough breaks at step 6 in the first section.

### ISSUE THREAD

**Issue by JohnnyGuy** [MicrosoftDocs/visualstudio-docs#5354]
At the top of this document is a section titled "Create a minimal application". I attempted to follow this.

I got to stop 6: "Build the application by typing csc helloworld.cs at the command prompt."

But I got a predictable failure: "'csc' is not recognized as an internal or external command, operable program or batch file."

I know the basics of what this error represents.

I tried skipping ahead in this document to the section that recommends editing your PATH variables: "At the command prompt, type set PATH=%PATH%;%ProgramFiles%\MSBuild or set PATH=%PATH%;%ProgramFiles(x86)%\MSBuild."

This also failed to solve my problem.

This tutorial then suggests the following: "Alternatively, if you have Visual Studio installed, you can use the Developer Command Prompt for Visual Studio, which has a path that includes the MSBuild folder."

I would rather not do this. I was attempting to learn about MSBuild with the goal of being able to write scripts that would help other developers avoid some tedious steps. By using the crutch of the Developer Command Prompt, I have lost the insights I need to know the minimal requirements to run a build.

The result is that this document is a poor experience for someone who is attempting to get introduced with MSBuild. The initial "hello world" program fails to build, and I immediately forced to troubleshoot. The document is seemingly out of order, or the document needs to outline prerequisites.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bc6800-41dc-a7a4-5942-0f103a290cf9
* Version Independent ID: 56b974f2-30d2-ae79-2b78-7eb073ec7cd1
* Content: [Walkthrough: Creating an MSBuild Project File from Scratch - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch?view=vs-2019&source=docs#feedback)
* Content Source: [docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@JohnnyGuy -- thank you for your feedback.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- please look into this issue.

**Comment by ghogen** [comment]
@JohnnyGuy Thanks for pointing this out. This was out-of-date information.  I've submitted a fix for this.
