### ISSUE TITLE
dotnet_style_prefer_is_null_check_over_reference_equality_method is listed in multiple sections

### ISSUE THREAD

**Issue by danieljamescarpenter** [MicrosoftDocs/visualstudio-docs#5357]
dotnet_style_prefer_is_null_check_over_reference_equality_method is appears in both the Expression-level preferences and the "Null" checking preferences sections when it is only listed under the contents of "Null" checking preferences.

The instance in the "Null" checking preferences is missing the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5299f22f-4b0f-9e81-883e-d34b2b520bf2
* Version Independent ID: 6a9db168-c592-29a0-59b7-1ff2f517e558
* Content: [.NET language conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019)
* Content Source: [docs/ide/editorconfig-language-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-language-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@danieljamescarpenter -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@mikadumont -- Mika, please review [private PR 6640](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6640).
