### ISSUE TITLE
Is cloud based load testing deprecated? What does it really mean 

### ISSUE THREAD

**Issue by girishacharya** [MicrosoftDocs/visualstudio-docs#5358]
Came across an article https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/ which says that cloud-based load testing service has been deprecated.

in this article, at one point it says that,

> Running a load test in the cloud using Visual Studio (both auto-provisioned agents and self-provisioned ‘bring-your-own’ agents): You can continue to run the tests but self-hosted with Test Controller/Test Agent option outlined above.

If all my load testing agents, controllers are created as VMs in Azure - and I use my VSTS subscription to run these load tests then do I need to worry? The above paragraph is a little confusing, hence asking. What does it really mean?

**Comment by TerryGLee** [comment]
@girishacharya It looks like you've asked that question on the actual blog post itself; that's the best avenue for an answer, as this forum is for Visual Studio documentation issues on https://docs.microsoft.com/visualstudio only.
