### ISSUE TITLE
Snippets location for Visual Studio for Mac?

### ISSUE THREAD

**Issue by hnabbasi** [MicrosoftDocs/visualstudio-docs#5360]
Where can I find the snippets now? It used to be that we could find the code snippets under this location,

`~/Library/VisualStudio/<version>/Snippets`

but, it seems that they have moved after 8.4.2

**Comment by WilliamAntonRohm** [comment]
@hnabbasi -- Hussain, thank you for your question.  I am looking into this issue.  Meanwhile, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by WilliamAntonRohm** [comment]
@hnabbasi -- Hussain, are you referring to information in a specific docs.microsoft.com article?  If so, please provide the article's URL.

@cobey -- Cody, my research indicates that is still the current location but I don't have a Mac for a live test.  Is there a newer snippets location?

**Comment by jmatthiesen** [comment]
Hi, @hnabbasi – The default code snippets are packaged into the Visual Studio.app bundle. If you want to create your own Snippets you can either use the Visual Studio > Preferences... > Code Snippets menu, or you can create the `~/Library/VisualStudio/8.0/Snippets` on disk and copy your snippets directly into that folder.

Here's a nice article discussing this, by a member of our community: https://www.benday.com/2019/06/20/code-snippets-for-visual-studio-visual-studio-code-and-visual-studio-for-mac/

**Comment by jmatthiesen** [comment]
#please-close
