### ISSUE TITLE
uninstall-vsmac.sh misses Visual Studio Update

### ISSUE THREAD

**Issue by ppdac** [MicrosoftDocs/visualstudio-docs#5361]
Expected script to uninstall Visual Studio Update, but it leaves it behind in `/Library/Application Support/Visual Studio`

Source page: https://github.com/MicrosoftDocs/visualstudio-docs/blob/266915e9d776128e777fd190ac9ae85416230358/mac/uninstall.md

See "You can uninstall Visual Studio and Xamarin components in one go by using the uninstall script."

**Comment by WilliamAntonRohm** [comment]
@ppdac -- Louis, it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).
