### ISSUE TITLE
Typo in the article

### ISSUE THREAD

**Issue by eddyuk** [MicrosoftDocs/visualstudio-docs#5364]
Step 7 in the Add some code section, there is small mistake. The page should be Index.cshtml instead of index.html
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68483bc8-45dc-fc2e-b289-2901a70461ff
* Version Independent ID: 5167502a-bd55-8927-5656-1c4f107884d7
* Content: [Create an ASP.NET Core app with TypeScript - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2019)
* Content Source: [docs/javascript/tutorial-aspnet-with-typescript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-aspnet-with-typescript.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review [private PR 6641](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6641).
