### ISSUE TITLE
Distribute snippets with vs2019

### ISSUE THREAD

**Issue by jdkeifer** [MicrosoftDocs/visualstudio-docs#5365]
This does not work for C# using VS 2019 16.6.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c60cdeb-c3af-ebb1-80e7-1ec682896734
* Version Independent ID: 04010067-02f9-548e-467b-fa4efa391860
* Content: [Distribute code snippets as an extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-distribute-code-snippets?view=vs-2019)
* Content Source: [docs/ide/how-to-distribute-code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-distribute-code-snippets.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@jdkeifer -- thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. 

cc @TerryGLee for awareness
