### ISSUE TITLE
It would be useful to have an example using namespaces

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#5369]
It would be useful to have an example using namespaces.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea4474bd-b6d2-241c-244a-695579a1e7af
* Version Independent ID: 458e32a8-93b3-5da1-b7e1-4718721be9dc
* Content: [XmlPeek Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/xmlpeek-task?view=vs-2019)
* Content Source: [docs/msbuild/xmlpeek-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/xmlpeek-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@paulomorgado -- Paulo, thank you for your suggestion.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- Gordon, please look into this issue.
