### ISSUE TITLE
Step Create the model is impossible as no ADO.NET Entity

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/visualstudio-docs#5371]
This is not present:

> Create the model
> Right-click on the project node in Solution Explorer and choose Add > New Item. In the left pane, under the C# node, choose Data and in the middle pane, choose ADO.NET Entity Data Model.
> 

Even if I installed everything correctly

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c0fa43-0ca5-9c86-f8c4-4b3eb7176250
* Version Independent ID: bb93e3ff-0d52-9e93-c3a8-545b16f03a30
* Content: [Simple data application with WPF and Entity Framework 6 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2019)
* Content Source: [docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by msavazzi** [comment]
Instructions are not fully correct. It does work if you choose WPF (.NET) project while it does not if you create a WPF (.NET Core) project.
The same goes with the libraries. If you install EF Core it does not work.

It would be great to have the example for .NET Core and EF Core. But in any case it must be specified the requirements to work

**Comment by ghogen** [comment]
For now this needs to clarify that it's only covering EF6 and .NET Framework but I agree that in the near future, we need to add support for .NET Core and EF Core if that's applicable.
