### ISSUE TITLE
How to output from a test to view in Test Explorer panel

### ISSUE THREAD

**Issue by framlingham** [MicrosoftDocs/visualstudio-docs#5374]
Please document how to output from a test, and be able to view it in the Test Explorer panel. :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3681419-a041-da72-a134-37401922a536
* Version Independent ID: 57b6194d-cb07-0e89-8f38-544bf4ce9816
* Content: [Run and debug unit tests with Test Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2019)
* Content Source: [docs/test/run-unit-tests-with-test-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/run-unit-tests-with-test-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@framlingham It sounds like you want more of a get started doc here? This one is more reference. Please see this topic:
https://docs.microsoft.com/en-us/visualstudio/test/getting-started-with-unit-testing?view=vs-2019

**Comment by Mikejo5000** [comment]
Adding a link to the get started topic.
