### ISSUE TITLE
Incorrect tag in example

### ISSUE THREAD

**Issue by InteXX** [MicrosoftDocs/visualstudio-docs#5375]
The example markup indicates a `ProjectType` of `CSharp`, but that type doesn't exist anywhere in the documented schema, let alone in the list of project types.

Is this correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f66438c2-1bb4-f5f9-12f8-64c25f5460ce
* Version Independent ID: 5e9669ca-e652-1459-1dd7-542249a9d237
* Content: [Add or edit tags on project templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-tags?view=vs-2019)
* Content Source: [docs/ide/template-tags.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-tags.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @minsa110
* Microsoft Alias: **somin**

**Comment by WilliamAntonRohm** [comment]
@minsa110 -- Soojin, please review [private PR 6642](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6642).
