### ISSUE TITLE
Many project templates lack their F# counterparts

### ISSUE THREAD

**Issue by idchlife** [MicrosoftDocs/visualstudio-docs#5379]
Making it very hard to create multiple linked projects.

e.g.: Xamarin iOS project Single Page in F# + WatchOS extension app. Parent app has F# language and WatchOS does not have because VS For Mac does not have template for WatchOS in F#.

Where to find needed templates?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 776b3956-55f3-6f3e-640c-d322203a8395
* Version Independent ID: 700a8e79-12a9-d4b9-7984-980e1cb9ed7f
* Content: [Creating new Projects and Solutions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/create-new-projects?view=vsmac-2019)
* Content Source: [mac/create-new-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/create-new-projects.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment]
@idchlife -- thank you for your question.  Please consider these resources:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
