### ISSUE TITLE
typo - toggle bookmark

### ISSUE THREAD

**Issue by mehagar** [MicrosoftDocs/visualstudio-docs#538]
I believe the keyboard shortcut for toggling a bookmark is ctrl+k, ctrl+k.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac5a1c94-4cd3-3519-d437-491b4c19c9fb
* Version Independent ID: 807d3d11-fd62-b359-e0c7-06033ba252cf
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/setting-bookmarks-in-code?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.BookmarkWindow)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%26rd%3Dtrue)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/setting-bookmarks-in-code.md)
* Service: unspecified

**Comment by gewarren** [comment]
@mehagar this is fixed now. Thanks so much for the feedback!
