### ISSUE TITLE
Visual Studio Tutorials for web development

### ISSUE THREAD

**Issue by apikman** [MicrosoftDocs/visualstudio-docs#5384]
Can someone point me towards tutorials of how to use Visual studio to create websites. 

Thank you

**Comment by neneeen** [comment]
Like, https://docs.microsoft.com/en-us/aspnet/core/?view=aspnetcore-3.1#develop-asp-net-core-apps ?

**Comment by WilliamAntonRohm** [comment]
@apikman -- please try here:  https://docs.microsoft.com/en-us/learn/modules/develop-web-apps-with-vs-code/

@neneeen -- thank you for your suggestion.
