### ISSUE TITLE
Topic is out of date with the latest release of Visual Studio

### ISSUE THREAD

**Issue by AngelosP** [MicrosoftDocs/visualstudio-docs#5386]
Topic is out of date with the latest release of Visual Studio. Also more topics need to be added for the Azure Services supported in VS that are not included in these docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86fd07bc-4fee-166e-c7ff-fbc2a568f22b
* Version Independent ID: 908ad034-ee90-9a6e-9838-ea5f334156b9
* Content: [Add Azure Storage by using Connected Services - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-connected-services-storage?view=vs-2019)
* Content Source: [docs/azure/vs-azure-tools-connected-services-storage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/azure/vs-azure-tools-connected-services-storage.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
We added a number of topics for this, and updated this doc as well.
