### ISSUE TITLE
binlog default ProjectImports seems to be wrong

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/visualstudio-docs#5388]
The doc says that the default is Embed - however without setting any ProjectImports option I get a msbuild.ProjectImports.zip file meaning that the default is ZipFile.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by asklar** [comment]
so it turns out the default is Embed but a temporary zip file is still created (then deleted). see https://github.com/microsoft/msbuild/issues/5383

**Comment by WilliamAntonRohm** [comment]
@asklar -- Alexander, thank you for your followup.
