### ISSUE TITLE
Additional notice for Functions deployment overwriting existing content

### ISSUE THREAD

**Issue by vlkuznet** [MicrosoftDocs/visualstudio-docs#5389]
Looks like this has been brought up in Azure Functions documentation, but should be mentioned on the VS side as well:
https://github.com/MicrosoftDocs/azure-docs/issues/18258
https://github.com/MicrosoftDocs/azure-docs/issues/18114

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f38987-1d2b-6dfc-e531-d1ca50fbb11c
* Version Independent ID: 592a4f31-6e8f-0ba6-4b8d-58b44600faf3
* Content: [Deployment overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components-resources?view=vs-2019#azure-app-service)
* Content Source: [docs/deployment/deploying-applications-services-and-components-resources.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/deploying-applications-services-and-components-resources.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
We're not covering every Azure service in the VS docs currently, mainly App Service.
