### ISSUE TITLE
This documentation appears totally irrelevant to Visual Studio 2017 15.5.6

### ISSUE THREAD

**Issue by bluemonkmn** [MicrosoftDocs/visualstudio-docs#539]
After updating to 15.5.6, the "Other" category under the Options dialog's Xamarin category has only a mention of "Xamarin Live Player (Preview)" and none of my previous Xamarin/Android SDK environment works any more. I think this documentation or Visual Studio or Xamarin need to be fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e28dd684-9239-01be-cfdd-c8e2c7ce063f
* Version Independent ID: 8363dcd1-a095-3b76-4ba2-4e9d90885ae6
* [Content](https://docs.microsoft.com/en-us/visualstudio/cross-platform/verify-your-xamarin-environment)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/cross-platform/verify-your-xamarin-environment.md)
* Service: unspecified

**Comment by gewarren** [comment]
@conceptdev should we redirect to a more up-to-date topic for now?

**Comment by gewarren** [comment]
The xamarin topics are now updated. Please check them out [here](https://docs.microsoft.com/en-us/xamarin/cross-platform/get-started/requirements).

**Comment by gewarren** [comment]
@charlespetzold Can [Verify your xamarin environment](https://docs.microsoft.com/en-us/visualstudio/cross-platform/verify-your-xamarin-environment) be updated?

**Comment by conceptdev** [comment]
@gewarren we are planning to redirect this to content in https://docs.microsoft.com/xamarin/

**Comment by charlespetzold** [comment]
@gewarren : An update to that page is part of this PR: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1683

**Comment by conceptdev** [comment]
The PR above has been merged, and the updated document has been published.
