### ISSUE TITLE
Build time increased by more than 10x time after enabling the Code Analysis in VS 2019

### ISSUE THREAD

**Issue by himalpatel81** [MicrosoftDocs/visualstudio-docs#5392]
We've a solution of around 40 .net core projects. We enabled Code Analysis for all of those projects. When we build the solution, now it takes around 45 minutes to compile. Without Code Analysis, the solution compiles in about 3 minutes. 

Is there any thing that can be done to reduce the time ? Can we configure it such that it doesn't run the code analysis for Release build ?
Thanks,

**Comment by WilliamAntonRohm** [comment]
@himalpatel81 -- Himal, thank you your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com topic you’re referencing.  

Meanwhile, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by himalpatel81** [comment]
@WilliamAntonRohm : I'm referring to https://docs.microsoft.com/en-us/visualstudio/windows/?view=vs-2019
Please let me know if you need any other detail.

**Comment by WilliamAntonRohm** [comment]
@himalpatel81 -- Himal, thank you for clarifying.  That link goes to a large overview page.  Please let me know which specific article pointed you to using Code Analysis.  This repo is solely for documentation issues, with limited support options other than to point you to the links in my initial comment.

**Comment by himalpatel81** [comment]
Hi @WilliamAntonRohm : Never mind. False alarm. It's not related to Documentation.
