### ISSUE TITLE
The asset quickstart-publish-azure.png is not the one present in the visualstudio-docs-pr repo.

### ISSUE THREAD

**Issue by AngelosP** [MicrosoftDocs/visualstudio-docs#5395]
The asset **quickstart-publish-azure.png** is not the one present in the visualstudio-docs-pr repo.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852946c7-d511-76d8-ce40-a03c7d9d7ff2
* Version Independent ID: 4b1be0b3-7e28-d414-553f-9e1be7ef04a0
* Content: [First look at deployment - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components?view=vs-2019)
* Content Source: [docs/deployment/deploying-applications-services-and-components.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/deploying-applications-services-and-components.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Eng team is working on a bug that prevented old image from getting deleted. For a quick workaround, renaming this image.
