### ISSUE TITLE
corrupted links.

### ISSUE THREAD

**Issue by eaydemir** [MicrosoftDocs/visualstudio-docs#5398]
Determine which editor opens a file in a project pages (
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/internals/determining-which-editor-opens-a-file-in-a-project.md )

See also links are corrupted.

**Comment by WilliamAntonRohm** [comment]
@acangialosi -- Anthony, please review [private PR 6643](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6643).

**Comment by WilliamAntonRohm** [comment]
@eaydemir -- Emre, those links appear to be working on the live site:
- https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/determining-which-editor-opens-a-file-in-a-project?view=vs-2019

Please let me know if you still see otherwise.

**Comment by eaydemir** [comment]
ok. it's my mistake, no problem.
