### ISSUE TITLE
corrupted link2

### ISSUE THREAD

**Issue by eaydemir** [MicrosoftDocs/visualstudio-docs#5399]
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/how-to-open-standard-editors.md

some links in documents (begin with xref:) links are corrupted!

**Comment by WilliamAntonRohm** [comment]
@eaydemir -- Emre, those links appear to be working on the live site:

- https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-open-standard-editors?view=vs-2019

Please let me know if you still see otherwise.

**Comment by eaydemir** [comment]
ok. it's my mistake, no problem.
