### ISSUE TITLE
Profile XSLT option missing

### ISSUE THREAD

**Issue by polakovicp** [MicrosoftDocs/visualstudio-docs#540]
In VS2017 Pro, I don't have any Profile XSLT option in XML menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35fb6787-7c57-d5f5-8fec-8105c3280dc7
* Version Independent ID: efc508af-6e6b-bd3a-6052-01d29aa3fde7
* [Content](https://docs.microsoft.com/en-us/visualstudio/xml-tools/xslt-profiler#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/xml-tools/xslt-profiler.md)
* Service: unspecified

**Comment by gewarren** [comment]
@polakovicp Is it grayed out, or just doesn't appear at all? If it's grayed out, it will become enabled if you open an XSLT file.

**Comment by polakovicp** [comment]
Doesn't appear at all.
XML menu item appears when .xsl file is opened and this is what I get:
[image: Inline images 1]

**Comment by gewarren** [comment]
@polakovicp I will check. Perhaps the profiler is only available in the Enterprise edition.

**Comment by llali** [comment]
@polakovicp The Xslt profiler is only available in the Enterprise edition.
