### ISSUE TITLE
When to suppress part

### ISSUE THREAD

**Issue by koszeggy** [MicrosoftDocs/visualstudio-docs#5400]
Locking on `this` has nothing to do with weak identity and cross-AppDomain accessibility. Please either exclude it from the list or change the _When to suppress_ part something like this:

> It is safe to suppress the warning if the locked object is `this`/`Me` and the visibility of self object type is private/internal, and the instance is not accessible via any public references.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b97ee078-36f0-1f9b-cb29-93293989d5f6
* Version Independent ID: 786d0d32-ffdc-a6e5-fcd7-484b04cc3cf1
* Content: [CA2002: Do not lock on objects with weak identity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2002?view=vs-2019)
* Content Source: [docs/code-quality/ca2002.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2002.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mavasani Should the suggested statement be added to "When to suppress" section?

**Comment by mavasani** [comment]
That sounds reasonable

**Comment by Mikejo5000** [comment]
OK, thanks. I'll make the change.
