### ISSUE TITLE
c++ snippet shortcut shouldn't start with _

### ISSUE THREAD

**Issue by gorangrubic** [MicrosoftDocs/visualstudio-docs#5404]
In code editor (Version 16.5.4) C++ snippets having shortcut starting with _ can not be confirmed/selected from IntelliSense suggestion list by pressing tab (or any other keyboard command). 

If this is an intentional behavior, please describe it on this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60a5feab-7e47-6a02-1e07-26334dcc08ce
* Version Independent ID: db56c14c-1cfc-c46e-ead5-c8bea566e5cc
* Content: [Code snippets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets?view=vs-2019)
* Content Source: [docs/ide/code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-snippets.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@gorangrubic -- Goran, thank you for your feedback.  I have confirmed that one may select a snippet name beginning with an underscore with the Insert Snippet command, but that name does not appear in Intellisense.

@TerryGLee -- please look into this issue.
