### ISSUE TITLE
Many of the described options are missing from VS

### ISSUE THREAD

**Issue by slepmog** [MicrosoftDocs/visualstudio-docs#5405]
Many of the options described on the page are actually missing from VS 2019 v16.5.4 respective options dialog.

It would appear that they were removed between v16.4 and v16.5, which was never documented (or was a mistake).

An example StackOverflow question: https://stackoverflow.com/q/62104151/11683

Please fix documentation / bring back the removed options (not just the one mentioned in the question above).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c524aa1d-eec4-d776-8346-dfdc632eec76
* Version Independent ID: c0f65c4f-6369-10ce-5edc-0ab5fbae736a
* Content: [General, Debugging, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box?view=vs-2019)
* Content Source: [docs/debugger/general-debugging-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/general-debugging-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updating options to reflect 16.6

**Comment by Mikejo5000** [comment]
The option referred to in the stack post will only show up in the VS 2017 view now.
