### ISSUE TITLE
The link to designing user interfaces in the top navigation bar is broken

### ISSUE THREAD

**Issue by user135711** [MicrosoftDocs/visualstudio-docs#541]
The link from the navbar menu under the tasks item titled "Design User Interfaces" from the [main ide page](https://docs.microsoft.com/en-us/visualstudio/ide/) (or any page) has an extra "review" in the link (https://review.docs.microsoft.com/en-us/visualstudio/designers/designing-user-interfaces)that prevents public viewing. It should be https://docs.microsoft.com/en-us/visualstudio/designers/designing-user-interfaces

**Comment by gewarren** [comment]
@kraigb are you able to fix the link in the header?

**Comment by gewarren** [comment]
@user135711 thanks for reporting the broken link.

**Comment by kraigb** [comment]
@gewarren Yes, I'll take care of it.

**Comment by kraigb** [comment]
I've corrected it. @user135711 thanks for letting us know!
