### ISSUE TITLE
Totally outdated!

### ISSUE THREAD

**Issue by itsChris** [MicrosoftDocs/visualstudio-docs#5410]
This section is totally outdated:

Configure Web Deploy Publishing https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-import-publish-settings-iis?view=vs-2019#install-and-configure-web-deploy-on-windows-server

Web Deploy 3.6 is like .. 5 years old? and you combine this with Visual Studio 2019 and .NET Core. Please!

also Create the publish settings file in IIS on Windows Server -> i follow the instructions, step-by-step -> two times on two machines. With the result that 

https://docs.microsoft.com/en-us/visualstudio/deployment/media/tutorial-configure-web-deploy-publishing.png?view=vs-2019

Configure Web Deploy Package is missing in the context menu. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62c014f3-7ada-66ae-1db4-c59982504159
* Version Independent ID: 98041d92-c537-bf0a-9a11-ff50965d2cef
* Content: [Publish to IIS by importing publish settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-import-publish-settings-iis?view=vs-2019)
* Content Source: [docs/deployment/tutorial-import-publish-settings-iis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-import-publish-settings-iis.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by itsChris** [comment]
also: 
- Web Platform Installer is currently 5.1 -> you mention 5.0
- if you follow the instructions step-by-step -> when you try to install Web Deploy 3.6 for Hosting Servers (using Web Platform Installer 5.1)-> it fails -> because Web Deploy is already installed with Visual Studio 2019 (also for 2017 was the case).

**Comment by Mikejo5000** [comment]
In the scenario here, the server is described as remote and VS is installed on a local machine. But yes, if you are trying to run VS on the same Windows Server machine, you would need to uninstall Web Deploy. There is a step to that effect, though (except that it mentions only version 3.6)
![image](https://user-images.githubusercontent.com/11948536/83423866-6e7e6380-a3e0-11ea-9872-64cc142c40a8.png). I'll make a couple of edits.
