### ISSUE TITLE
Misleading Condition Example

### ISSUE THREAD

**Issue by ncarandini** [MicrosoftDocs/visualstudio-docs#5414]
I know is just an example, but IMHO it would be better to write

`Condition="'$(Configuration)'=='DEBUG'"`

instead of

`Condition="'$(CONFIG)'=='DEBUG'"`

Because `CONFIG` do not a Build reserved property.
Nothing wrong here, just a probably misleading example.

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@ncarandini Thanks, I agree that this would be a good change.
