### ISSUE TITLE
Update: Windows container are supported.

### ISSUE THREAD

**Issue by saifbadran9** [MicrosoftDocs/visualstudio-docs#5415]
Hello Team,

Regarding the note in point (7) in the beginning of the document, it says "Windows containers are not supported to deploy to Azure App Service as a container."

Although, I believe it is supported as per the following QuickStart document, which we can follow to create Windows containers through VSCode:
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-windows-container

Did I misunderstand this point, or it needs to be updated?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58deff4-ba81-3d85-9fcc-8ddebb9143a6
* Version Independent ID: f28d7797-d245-a242-2b4a-533ed72acbbb
* Content: [Deploy an ASP.NET Core Docker container to Azure App Service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/deploy-app-service?view=vs-2019#feedback)
* Content Source: [docs/containers/deploy-app-service.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/deploy-app-service.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@saifbadran9 -- Saif, thank you for your feedback.

@ghogen -- Gordon, please look into this issue.  If Windows containers are now supported, let me know & I will create a PR to delete that sentence.

**Comment by ghogen** [comment]
@saifbadran9 @WilliamAntonRohm Thanks, this article is a little out-of-date. In addition to Windows containers being supported, there are also some UI updates that will mean the screenshots have to be updated, so I'll take this on.
