### ISSUE TITLE
adding code

### ISSUE THREAD

**Issue by asherabrams** [MicrosoftDocs/visualstudio-docs#542]
The CheckTheAnswer() method in Step 1 goes inline with the other methods, [StartTheQuiz()] etc.  In Step 2, the if else statement refers to the statement in the previously created [timer1_Tick] method (not the if-else statement in the code we just added).  The edit to the [else if] clause introduces the decrement notation [timeLeft--;].

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f87fb21b-1d37-f2a8-0d32-5fa2ff83a563
* Version Independent ID: 6a34cee6-9920-b9c5-8e33-79d026931fa2
* [Step 4: Add the CheckTheAnswer() method](https://docs.microsoft.com/en-us/visualstudio/ide/step-4-add-the-checktheanswer-parens-method)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/step-4-add-the-checktheanswer-parens-method.md)
* Service: unspecified

**Comment by TerryGLee** [comment]
@asherabrams Thanks for your feedback; we appreciate it. This is in our backlog queue to get fixed; we'll report back when it is.

**Comment by ManaviPai** [comment]
Can I work on this?

**Comment by nithinb99** [comment]
> Can I work on this?

No

**Comment by nithinb99** [comment]
Can I work on this?

**Comment by ornellaalt** [comment]
Hi @asherabrams, thanks for your feedback! I edited the content to specify where to add the CheckTheAnswer() method, as well as which if else statement to add the new method in (that of the Timer1_Tick() method). In the else if clause, the comments explain the decrement notation-- "Decrease the time left by one second and display the new time left by updating the Time Left label." Closing out this issue.
