### ISSUE TITLE
Add a description for the purpose of the label attribute

### ISSUE THREAD

**Issue by chris-sekira** [MicrosoftDocs/visualstudio-docs#5423]
The `<ItemGroup>` `Label` attribute is mentioned but its use is not clarified. While it can be somewhat inferred that it doesn't matter functionally, it's inclusion in some Microsoft examples and repos (like in the code sample [here](https://github.com/microsoft/MSBuildSdks/tree/91a96e75a54d29a7d2e0f595cc683346312bdce8/src/Artifacts#using-as-a-project-sdk)) can lead some to believe that it may cause some "backend black magic" when used. The only additional documentation that I've found is in the C++ specific MSBuild docs like [this](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=vs-2019#projectconfigurations-itemgroup-element).

If the Label attribute truly does nothing except for assist Visual Studio with C++ projects, this should probably be noted or at least referenced. Hopefully this will prevent future developer "arguments" over it being required in C#/VB MSBuild projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7148a9c-77db-81c7-0362-f2ce6b0c6274
* Version Independent ID: ccef6249-9a81-9376-a9c8-fe884d0b094f
* Content: [ItemGroup Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/itemgroup-element-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/itemgroup-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/itemgroup-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
The purpose of the Label attribute is to allow you to express the intent of an ItemGroup, to make project files more readable and understandable. It is not used in MSBuild target files to control any build behavior.  What arguments are you having about this?  

In principle, it is another available value that could be used to control behaviors, but that is not its primary intended purpose.

**Comment by ghogen** [comment]
@chris-sekira It turns out that the Label attribute *is* used to control some build behaviors. It's used in C++ build system, and in certain non-SDK builds for .NET projects. The next update for this article will reflect this.

**Comment by chris-sekira** [comment]
@ghogen Awesome, thanks for the update!
