### ISSUE TITLE
Polls Flask Web Project requirements.txt requires deprecated meta-package

### ISSUE THREAD

**Issue by carlos-riquelme** [MicrosoftDocs/visualstudio-docs#5424]
[Enter feedback here]
The Polls Flask Web Project template has the meta-package azure-storage in the requirements.txt file, but that meta-package has been deprecated.

According to the project's webpage in Pypi.org, "Starting with v0.37.0, this package is deprecated. Please install the service specific packages prefixed by azure-storage needed for your application."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47801555-59fa-e88e-8f78-17e4ba4d1e03
* Version Independent ID: 3272c6ed-afe8-3fb9-8e15-dbb30d5a4d23
* Content: [Learn Flask tutorial in Visual Studio step 5, Polls project template](https://docs.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-05-polls-flask-web-project-template?view=vs-2019)
* Content Source: [docs/python/learn-flask-visual-studio-step-05-polls-flask-web-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-flask-visual-studio-step-05-polls-flask-web-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by judej** [comment]
Thank you for your input. We agree and have added this work to our planning board. We will go ahead and close this issue, but continue to track the work internally.  If you think this issue should remain open, please reopen it with a comment explaining why. Tag me for visibility.


We appreciate your investment in our content.
