### ISSUE TITLE
The example for GetPathOfFileAbove is an example for GetDirectoryNameOfFileAbove

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#5425]
The example for `GetPathOfFileAbove` is an example for `GetDirectoryNameOfFileAbove`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
It looks like it's just saying that the GetPathOfFileAbove is functionally equivalent to the given call to GetDirectoryNameOfFileAbove, so I'm not convinced this is a problem.

**Comment by ghogen** [comment]
@paulomorgado Thanks for filing this issue. Does my previous comment clarify? I think we can close this, unless I'm not understanding the problem.

**Comment by paulomorgado** [comment]
I don't think most of the examples, if any, are any exemplificative.

Better exemples would show an example file/directory structure and would show the values returned for the functions in the examples.
