### ISSUE TITLE
Load Project dependencies option for VS 2019 and .NET Core/Standard projects

### ISSUE THREAD

**Issue by ankitvijay** [MicrosoftDocs/visualstudio-docs#5427]
The load project dependencies options for VS 2019 and .NET Core/Standard projects are different from what is shown in the screenshot. We see the following two options:
- Load Direct dependencies of Project
- Load Entire dependency Tree  of Project

![image](https://user-images.githubusercontent.com/5988564/83698733-899ddd00-a645-11ea-9080-fb6d46184488.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108b5373-83a5-8d82-0414-939b0caf2866
* Version Independent ID: 9bb010ce-5641-c2a4-ce2a-d53943ac5432
* Content: [Load a subset of projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019)
* Content Source: [docs/ide/filtered-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/filtered-solutions.md)
* Product: **visual-studio-dev16**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **stsu**

**Comment by jillre** [comment]
@TerryGLee can you take a look at this?
