### ISSUE TITLE
Visual Studio PROBLEMS

### ISSUE THREAD

**Issue by MikeMGW** [MicrosoftDocs/visualstudio-docs#5428]
**2013 vb.net** on windows 7 used to be really great. Running vb.net on widows 10 is a nightmare.
eg. right clicking on an aspx file and clicking set as start page used to work. Now it doesn't.
Accessing MySQL with an ODBC connection I cant get to work.
Online help often says click on this and then that but the that is not there!
While all works great on Windows 7, you tell me it is history. I conclude that the years and years I have spent using VB,net will now prove to be going down the drain.
I am not happy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a2bfea-c771-a183-ed02-d2338516a223
* Version Independent ID: b0e5f18b-29bb-858c-6b04-b4e72240f777
* Content: [Change the startup experience - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/customizing-the-start-page-for-visual-studio?view=vs-2019)
* Content Source: [docs/ide/customizing-the-start-page-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/customizing-the-start-page-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@MikeMGW -- thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem. 

Also, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
