### ISSUE TITLE
Cannot see references even after clicking show all files, unable to Shim MS references (Microsoft Fakes)

### ISSUE THREAD

**Issue by SpiritBob** [MicrosoftDocs/visualstudio-docs#5429]
I'm unable to find the references section in my solution explorer, even when I've enabled "Show All Files". What I did, to get it to work supposedly, was simply faking the assembly by going to Projects > Right-clicking the project and selecting Add Fake assembly.

This is okay I guess? But when I wanted to fake the behavior of DateTime, I was required to add a fakes assembly for System.dll.

Sadly, I couldn't do that - I cannot see the dll anywhere in my solution explorer as mentioned before, I can only link projects with the way described above.

Any help will be appreciated!

**VS Version** used: VS 2019 Enterprise, latest preview. (For a .NET Core project)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 069d29c9-b269-6e1f-08af-91ac135ebb1e
* Version Independent ID: cd993f76-8077-d566-4c48-0ab425c62b83
* Content: [Isolating Code Under Test with Microsoft Fakes - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/isolating-code-under-test-with-microsoft-fakes?view=vs-2019)
* Content Source: [docs/test/isolating-code-under-test-with-microsoft-fakes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/isolating-code-under-test-with-microsoft-fakes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@SpiritBob -- thank you for your feedback. Here are a few options you might consider:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are also welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 


cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
