### ISSUE TITLE
Owner / Chief Consultant ~ techBo.ca

### ISSUE THREAD

**Issue by techBo130** [MicrosoftDocs/visualstudio-docs#543]
The techBo congomlerant of companies includes, but is not limited to techbo.ca - enterprise level IT & security management; techBoLabs.ca - Novel Compound Research for Mental Health Relief; techBoInvestments.ca - Sustaining and evolving the distributed block-chain initiatives with investments and support of change that disrupts commerce and re-invents ethical and environmental currencies.

**Comment by ghogen** [comment]
Closing - please don't use our feedback system for promoting or offering services and products.
