### ISSUE TITLE
Which binaries will be installed by each workload/package?

### ISSUE THREAD

**Issue by AndreyMlashkin** [MicrosoftDocs/visualstudio-docs#5432]
I am looking for a package, which contains cl.exe, nmake.exe and MSBuild.exe. Could you please advise? It is not clear from the documentation.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e062363-94e9-f776-650f-a0723ab713a3
* Version Independent ID: 9181db12-cbdf-6f95-27f1-833930d6d323
* Content: [Visual Studio Build Tools workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools?view=vs-2019#msbuild-tools)
* Content Source: [docs/install/workload-component-id-vs-build-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-build-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @AndreyMlashkin, thanks for your question. cl.exe is the MSVC compiler and would be included in any of the MSVC labelled components (e.g.  Microsoft.VisualStudio.Component.VC.Tools.x86.x64). There are many components like that available depending on which version or target you are looking for. MSBuild.exe would be in Microsoft.Component.MSBuild. For information about nmake.exe, see the reference [here](https://docs.microsoft.com/en-us/cpp/build/reference/nmake-reference?view=vs-2019)
