### ISSUE TITLE
Can`t create superuser

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5437]
@teodred commented on [Thu Jun 04 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/105)

[Введите отзыв здесь]
Well. I think it is just because i`m stupid but, I can`t create super user.
I have such rows: 
You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
I`m trying to type it down and run exactly how it tells but it doesn`t work and answer me in that way : 
>>> python manage.py migrate
  File "<stdin>", line 1
    python manage.py migrate
                ^
SyntaxError: invalid syntax
---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 485e6157-bf3f-1065-d944-9860f198662c
* Version Independent ID: 8daa9161-23cb-8bfb-b736-6695b6e50ee8
* Content: [Руководство по Django в Visual Studio, шаг 4: шаблон веб-проекта](https://docs.microsoft.com/ru-ru/visualstudio/python/learn-django-in-visual-studio-step-04-full-django-project-template?view=vs-2019)
* Content Source: [docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/blob/live/docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

---

@srvbpigh commented on [Thu Jun 04 2020](https://github.com/MicrosoftDocs/visualstudio-docs.ru-ru/issues/105#issuecomment-639066213)

Hello, @teodred
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for raising this issue.  Please convey the following to @teodred:

This software can be challenging for anyone.  

Please see the following resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

cc @JoshuaPartlow for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
