### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ruisilva450** [MicrosoftDocs/visualstudio-docs#544]
In the section "Configuring your JavaScript project" there is a TODO messages that probably doesn't belong here:
" * package.json and bower.json list dependencies used by your project and by default are included in Automatic Type Acquisition (ATA) <TODO - add link>"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bdd1c8ed-73a2-a511-2d8e-7f0582d0a0ed
* Version Independent ID: 5f96f2ff-a494-3e00-e3bf-3689da9f1f0a
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/javascript-in-vs-2017#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/javascript-in-vs-2017.md)
* Service: unspecified

**Comment by babuw** [comment]
testing feel free to delete

**Comment by Mikejo5000** [comment]
@ruisilva450 Thanks for the feedback! Removing TODO
