### ISSUE TITLE
user install vs. system vs. zip

### ISSUE THREAD

**Issue by MaDnKount-r** [MicrosoftDocs/visualstudio-docs#5443]
Ok. So let me get this straight. Sure the user install is more efficient for the install and upgrades. But there's no guarantee I'd be the only user with access to the download. Where as the system install perhaps has some sort of parameters that I can set into place. Am I getting this right?

_Originally posted by @MaDnKount-r in https://github.com/MicrosoftDocs/sql-docs/issues/1657#issuecomment-640284273_

**Comment by WilliamAntonRohm** [comment]
@MaDnKount-r -- thank you for your feedback.  I am re-opening the original issue #1657, and closing this issue as a duplicate.

**Comment by WilliamAntonRohm** [comment]
@MaDnKount-r -- thank you for your question.  We are looking into it.

Meanwhile, please see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by WilliamAntonRohm** [comment]
@ornellaalt -- Ornella, please look into this potential documentation issue.
