### ISSUE TITLE
CA1824

### ISSUE THREAD

**Issue by aravindsamy33** [MicrosoftDocs/visualstudio-docs#5444]
Unable to find 'Application' tab or 'Package' tab in Solution Explorer Properties. kindly suggest. 

I am following below link

https://docs.microsoft.com/en-in/visualstudio/code-quality/ca1824?view=vs-2017&redirectedfrom=MSDN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e7c18d-51c4-2c20-9fa3-d95852d533fa
* Version Independent ID: 15863a04-568b-9f15-f244-3f83cb4c524f
* Content: [CA1824: Mark assemblies with NeutralResourcesLanguageAttribute - Visual Studio](https://docs.microsoft.com/en-in/visualstudio/code-quality/ca1824?view=vs-2017&redirectedfrom=MSDN)
* Content Source: [docs/code-quality/ca1824.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1824.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by aravindsamy33** [comment]
@Mikejo5000 any solution for this issue ?

**Comment by Mikejo5000** [comment]
@aravindsamy33 What kind of project are you using, and what version of Visual Studio?

**Comment by Mikejo5000** [comment]
I took a quick look at .NET Framework, .NET Core, ASP.NET, ASP.NET Core, and UWP, and they all have either the Application or Package tab in the project properties page.

**Comment by aravindsamy33** [comment]
> @aravindsamy33 What kind of project are you using, and what version of Visual Studio?

@Mikejo5000 i am using ASP.NET web application. Using Visual Studio 2017
i can see below options in properties page
![image](https://user-images.githubusercontent.com/66587314/84355267-eff3a400-abdf-11ea-8b47-f6e518245fca.png)

**Comment by Mikejo5000** [comment]
I see those properties for some ASP.NET Web Site templates in VS 2017, but I don't see them for any templates in VS 2019. So, it looks like that particular template was deprecated/removed. It doesn't include a project file, so no MSBuild integration. There's a possible workaround described here: https://stackoverflow.com/questions/4068360/c-sharp-warning-mark-assemblies-with-neutralresourceslanguageattribute, though I'm not sure it will work with this template.
@mavasani in case he has a suggestion for you.

**Comment by Mikejo5000** [comment]
You might also want to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by aravindsamy33** [comment]
@Mikejo5000 thank you for letting me know this.

**Comment by Mikejo5000** [comment]
Closing this as a support request vs. a doc issue
