### ISSUE TITLE
Does not discover service

### ISSUE THREAD

**Issue by Tvalone** [MicrosoftDocs/visualstudio-docs#5448]
Working thru the documentation using Visual Studio 2017. I can create and run the WCF service and perform the hello test with getdata. However when I create the windows form app paste the url and click go then click discover I get 

There was an error downloading 'http://localhost:55706/Service1.svc/$metadata'.
Unable to connect to the remote server
No connection could be made because the target machine actively refused it 127.0.0.1:55706
Metadata contains a reference that cannot be resolved: 'http://localhost:55706/Service1.svc'.
There was no endpoint listening at http://localhost:55706/Service1.svc that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
Unable to connect to the remote server
No connection could be made because the target machine actively refused it 127.0.0.1:55706
If the service is defined in the current solution, try building the solution and adding the service reference again.

**Comment by WilliamAntonRohm** [comment]
@Tvalone -- thank you for your feedback.  Are you reading a particular docs.microsoft.com article?  Meanwhile, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue.

**Comment by Tvalone** [comment]
Thanks yes I was reading

https://docs.microsoft.com/en-us/visualstudio/data-tools/walkthrough-creating-a-simple-wcf-service-in-windows-forms?view=vs-2019

I am using VS2017. Not sure if that matters. What is skipped is the fact that you need to add two projects to the solution. Then of course this enables the client to discover the Service.  It is just not spelled out for people like me!

**Comment by WilliamAntonRohm** [comment]
@Tvalone -- thank you for clarifying.

@ghogen -- please look into this issue.
