### ISSUE TITLE
How can I locate the Knowledge Base article Q133174

### ISSUE THREAD

**Issue by buzz3791** [MicrosoftDocs/visualstudio-docs#545]
This article references

Q133174 How to Locate Where a General Protection (GP) Fault Occurs

and implies that searching http://support.microsoft.com/ for Q133174 will succeed.  If you try such a search, you'll find that it returns no useful results.  I've unsuccessfully looked everywhere for Knowledge Base article Q133174.  What are accurate instructions for locating Q133174?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75130292-7d5a-450b-8620-d8be308d4fbd
* Version Independent ID: 8acc88fb-b0a5-57dc-bdcd-a438e5aaa264
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/how-can-i-debug-access-violations-when-running-my-program-outside-the-debugger-q)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/how-can-i-debug-access-violations-when-running-my-program-outside-the-debugger-q.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@buzz3791 Looks like Q133174 was retired. I will remove the reference

**Comment by Mikejo5000** [comment]
Fix published
