### ISSUE TITLE
Documents are not accurate on how to activate account

### ISSUE THREAD

**Issue by MichaelMacc** [MicrosoftDocs/visualstudio-docs#5457]
On the page for activating your windows developer account for visual studio, it says to click the link 
https://developer.microsoft.com/ and then click signup. In the picture it shows Signup being part of a Store menu selection.

there is no such selection on it and no where to click sign up. Can you please update how you would do this please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9339facb-e027-7d83-b1ab-b4c4363a109b
* Version Independent ID: c9000f86-0aa5-59ff-d3e0-a0e649708b88
* Content: [Windows Developer Account Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-windows-dev)
* Content Source: [subscriptions/vs-windows-dev.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-windows-dev.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- I am unable to assign this issue to you, and it requires an assignee.

**Comment by evanwindom** [comment]
Caity it is, then.

**Comment by evanwindom** [comment]
@MichaelMacc - I apologize for the delay on this.  It turns out the path to the sign up page changed.  We've updated the article to reflect the new path, and should have the behavior of the tile in the benefits portal updated soon as well.  Thanks for flagging this issue for us.

**Comment by evanwindom** [comment]
#please-close
