### ISSUE TITLE
Can I modify the default remote output directory?

### ISSUE THREAD

**Issue by mayi-ask** [MicrosoftDocs/visualstudio-docs#5464]
Whenever I build a new Linux project, the remote output directory set to "~/projects", I need to modify it every time. It's inconvenient.

**Comment by WilliamAntonRohm** [comment]
@mayi-ask -- Mayi, thank you for your question.  Please clarify the docs.microsoft.com article you are reading.  Meanwhile, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
