### ISSUE TITLE
VERY USELESS THINGS

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/visualstudio-docs#5469]
I moved this from here: https://github.com/MicrosoftDocs/visualstudio-docs.it-it/issues/16
The comments below were machine-translated

@enzonoseda commented 12 hours ago
In so many years of programming, I have always wondered what these bogus examples of "how to make a program" useless because "console" applications are useless. Unnecessary because in this way people who would like to learn something do not learn anything and are rather distanced from the art of programming.
If you want to do TRAINING on programming, create a simple WINDOWS project that manages a small database (for example "geometric figures") that allows you to calculate and draw the essential elements such as a triangle, to calculate the area, sides, angles, bisector, perimeter etc. and then allow you to print a page and save it as a PDF as well as allowing you to save the image. In short, a REAL complete PROGRAM that allows you to understand all aspects of programming.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc5022ad-0de6-a16f-3f79-394f57f78903
* Version Independent ID: ecc54693-3334-34f6-ff75-0a0413be4bec
* Content: [Create your first console app with Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-visual-basic-console?view=vs-2019)
* Content Source: [docs/ide/quickstart-visual-basic-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-visual-basic-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@CeciAc -- Cecilia, thank you for forwarding this issue.  Please convey the following to @enzonoseda (machine-translated):

@enzonoseda, grazie per il suo suggerimento dettagliato. Per aggiungere questo, utilizzare l'opzione "Suggerisci una funzionalità" nella [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). Saremmo felici di averlo registrato, dove gli altri possono vederlo e votarlo. Per altre informazioni su questo problema funziona nella community di sviluppatori, vedere la pagina [Suggerisci una funzionalità](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature). 

cc @ornellaalt for awareness
