### ISSUE TITLE
What does "Supported in the following document modes" actually mean?

### ISSUE THREAD

**Issue by adamdicarlo** [MicrosoftDocs/visualstudio-docs#547]
I want to know whether `someString.replace(/foo/g, '')` will work (that is, will honor the global flag) on IE 11.

I can't tell based on the wording here. Supported in "IE 11 standards document mode" sounds like it *could* indicate that IE 11 supports it, or it could just indicate that Edge, when configured as "IE 11 standards" supports, but the actual IE 11 browser does not.

(The "document mode" jargon is probably clear to (a subset of) Microsoft employees....)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0c46c5d-9ca7-c33a-874c-05ee04ef2b53
* Version Independent ID: ed8d560c-4b11-b7d7-2c26-005f6498575b
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/global-property-regular-expression-javascript)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/reference/global-property-regular-expression-javascript.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@adamdicarlo Thanks for your feedback! Granted, there could be more info on this page (and every JS reference topic), but details about document compatibility mode are out of scope here. The link takes you to Version Info page for JS, which indicates Edge does not support any legacy modes, and the version page links you to this page: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/cc288325(v=vs.85), which gives more details about document compatibility mode (a browser setting, rather than a JS issue).

**Comment by Mikejo5000** [comment]
Closing

**Comment by adamdicarlo** [comment]
Thanks for the response. The compatibility table answered my question once I accepted that "IE __ Standards" is a thing that **IE __ itself actually does**. That probably sounds like a strange thing to be confused about, but pretty much the only time I've ever seen "IE __ Standards Mode" is in the DevTools menu _which makes it emulate an older version_, and I have no clue whether that emulation is exact (an embedded version of the old browser's engine), or approximate.

Thus, I'd thought that "IE __ Standards Mode" was just a DevTools feature that lets you emulate (or maybe just approximate) how a document would render for an older version of the browser. And if that were the case, and the accuracy was "approximate," then it seemed like this page did not have a definitive answer of what the actual IE 11 would do. (And I also wondered why the page would tell me how something would work when _emulating_ an old version of the browser?)

I'm not sure if a ton of people had this misconception but I can't have been the _only_ one.

(Yes, I understand now that IE __ Standards is how (the real) IE __ renders a page that it doesn't think needs weird workarounds.)
