### ISSUE TITLE
Migrating SSIS Projects From Visual Studio 2008 to Visual Studio 2019

### ISSUE THREAD

**Issue by Ur-Average-Programmer** [MicrosoftDocs/visualstudio-docs#5470]
In relation to this page, I'm seeking support and/or helpful guidance on what my options are in terms of migrating SSIS packages created in projected developed in Visual Studio 2008 to Visual Studio 2019. 

Any help would be greatly appreciated. Is it at all feasible? If so, how? Is there documentation or reference guide or online support that can be leveraged to perform this kind of migration? Is the reference material easily digestible to someone who is NOT a Microsoft Engineer?

Thanks!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3315d1-e6d3-e86d-9cce-1ff9ce0fc482
* Version Independent ID: ae3fd143-bf0b-4cfe-bcad-557eb41fdc2c
* Content: [Port, migrate, and upgrade projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?utm_source=getvssdk&utm_medium=referral&view=vs-2019)
* Content Source: [docs/porting/port-migrate-and-upgrade-visual-studio-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/porting/port-migrate-and-upgrade-visual-studio-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Ur-Average-Programmer -- thank you for your questions.

Visual Studio 2008 is no longer supported.  See [Visual Studio Product Lifecycle and Servicing](https://docs.microsoft.com/en-us/visualstudio/releases/2019/servicing).

Please consider downloading the [latest preview](https://visualstudio.microsoft.com/vs/preview/) of Visual Studio and [latest version](https://www.microsoft.com/en-us/sql-server/sql-server-2019) of SQL Server. You can refer to the [SQL Server upgrade](https://docs.microsoft.com/en-us/sql/database-engine/install-windows/upgrade-sql-server?view=sql-server-2017) documentation.

Meanwhile, consider these resources as well:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
