### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by avbhardwaj** [MicrosoftDocs/visualstudio-docs#5473]
Maybe a typo
![cap](https://user-images.githubusercontent.com/21962284/84557065-9624d400-acdc-11ea-902b-367eb6993a1b.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73356ab4-87d3-09fb-557f-4533fc133156
* Version Independent ID: ce5ed4b4-1406-9126-832a-ddcdc5cf25bc
* Content: [Microsoft Azure benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure)
* Content Source: [subscriptions/vs-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **lank**

**Comment by evanwindom** [comment]
@avbhardwaj  -  Thank you for bringing our attention to the error.  I have submitted a PR to correct the typo.

**Comment by evanwindom** [comment]
#please-close
