### ISSUE TITLE
The SignTask can't support all file types.

### ISSUE THREAD

**Issue by Dylan-zhu** [MicrosoftDocs/visualstudio-docs#5481]
[Enter feedback here]
The SignTask can't support all file types. For now, it seems that the task only supports exe and dll. Please add more to the usage conditions about SignTask.
Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c09ffd23-115c-368b-c17f-7d3af54f0a67
* Version Independent ID: b640eb45-9978-0a9e-f8dc-fd2581e84fb5
* Content: [SignFile Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/signfile-task?view=vs-2019)
* Content Source: [docs/msbuild/signfile-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/signfile-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review [private PR 6743](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6743).
