### ISSUE TITLE
It should be "Release". and not "Release."

### ISSUE THREAD

**Issue by WaqasAthar** [MicrosoftDocs/visualstudio-docs#5484]
Under configuration it says 
The configuration that you are building, either "Debug" or **"Release."** whereas it should be "Release". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@WaqasAthar Thanks - you can also contribute changes like this by clicking on the Edit button, editing the source in the browser, and then submitting the change using the buttons on that page.

**Comment by WilliamAntonRohm** [comment]
@WaqasAthar -- the existing punctuation is correct per the [Microsoft Style Guide](https://docs.microsoft.com/en-us/style-guide/punctuation/quotation-marks).

cc @ghogen for awareness
