### ISSUE TITLE
The page has no resources regarding Visual Studio for Mac.

### ISSUE THREAD

**Issue by SittenSpynne** [MicrosoftDocs/visualstudio-docs#5486]
The only editor discussed is the version in Visual Studio for Windows. There's not even a "Mac" version in the drop-down on the side. I managed to find some documentation for VS for Mac, but I had to use Google, not MS's docs site, to find it.

This page should either walk through the VS for Mac XAML editor or link to portions of the site that do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbc81f40-f1fc-1047-636e-4b8c501cb3c4
* Version Independent ID: f6c1ba8a-fe76-da62-c53d-616c59947212
* Content: [XAML code editor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-code-editor?view=vs-2019#feedback)
* Content Source: [docs/xaml-tools/xaml-code-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/xaml-code-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by LyalinDotCom** [comment]
This documentation is for Visual Studio 2019 as indicated by the top-left version selector. I am not aware of any VS for Mac code editor documentation but we can at least link off to https://docs.microsoft.com/en-us/visualstudio/mac/xamarin?view=vsmac-2019 as a resource. Otherwise this is all by design right now.

**Comment by TerryGLee** [comment]
@SittenSpynne We've added two Mac links to the **[See also](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-code-editor?view=vs-2019#see-also)** section that should help. We appreciate your helping us to improve the documentation!
