### ISSUE TITLE
.NET Project Debugging - Open as Project or Solution

### ISSUE THREAD

**Issue by luisquintanilla** [MicrosoftDocs/visualstudio-docs#5487]
When working with a .NET project in Visual Studio, you have to Open as Project or Solution. Opening a folder, setting it as Startup item and running it won't work.

Choose either:

1. **File > Open > Project/Solution**
2. **Ctrl** + **Shift** + **O**
3. On launch screen *Open a project or solution*

  ![image](https://user-images.githubusercontent.com/46974588/84836404-afdb5980-b003-11ea-9cfb-7e69e6fbe0e6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 970f0d59-b2b4-7082-1c2c-a468c93571ef
* Version Independent ID: a3135966-c343-5a6b-cd97-772a0c34fd93
* Content: [Develop code without projects or solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/develop-code-in-visual-studio-without-projects-or-solutions?view=vs-2019)
* Content Source: [docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/develop-code-in-visual-studio-without-projects-or-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@luisquintanilla We appreciate your pointing this out. To address the issue, we changed the text that said "You can open code into Visual Studio in _any_ of the following ways" to "You can open code into Visual Studio in the following ways" -- and then we added a note to the list item that mentions opening code by using "the Open Folder link on the start window," which explains that this method can't be used in every circumstance.

We're closing this issue now, with our thanks to you for helping improve the documentation!
