### ISSUE TITLE
`typeof` can also return `unknown`

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#549]
Older versions of IE can also return `unknown` for various objects. Please describe where this might happen, and how to coerce such values to native Javascript types.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5f73877-a969-d859-e74e-42559b908c19
* Version Independent ID: b611b040-0244-dd22-5a4c-e13b6534b71f
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/typeof-operator-decrementjavascript)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/reference/typeof-operator-decrementjavascript.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Looking into this.

**Comment by Mikejo5000** [comment]
@bterlson for input

**Comment by bterlson** [comment]
A common case was XMLHTTPRequest, but in general any object which was on the other side of a COM boundary returned a typeof of ‘unknown’. This included things like VBScript types with no analogue in JS as well I seem to recall.

There is no way to coerce such values to a native JS type. I suppose you could wrap it in a similar object? But some of those ‘unknown’ types had very strange behavior, e.g. support for event syntax (`obj::click = function() { }`) and references returned from function calls (e.g. list.item(1) = 1), neither of which have any analogue in actual JS.

Documenting the well-known cases where unknown is returned would be useful, but there is no universal way to coerce these things to "known" types.

**Comment by Mikejo5000** [comment]
Adding unknown as a possible return value with a short description based on comments above.

**Comment by Mikejo5000** [comment]
Fix is in the master branch; it should go live tomorrow.
