### ISSUE TITLE
RegEx Capture Group Enumeration Not Working

### ISSUE THREAD

**Issue by RocketCityElectromagnetics** [MicrosoftDocs/visualstudio-docs#5490]
I am using MSVS 2019.  I try the exact example for using capture groups for the replace string in search and replace, and it does not work, and yes, I have RegEx ticked.  It is not liking assignment of a number to the regex capture group (the regex turns red).

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@RocketCityElectromagnetics -- thank you for your feedback.  I have tested the example and it is working on my machine.  Please double-check the characters in your search and replace strings, and consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
