### ISSUE TITLE
Typo in release notes

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#5494]
---
**Issue moved from MicrosoftDocs/feedback#2852**
- Please respond to @msivia.

---

_From @msivia on Thursday, June 11, 2020 4:35:19 PM_

Typo in [Visual Studio 2019 version 16.6 Release Notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.6.2)

Typo in [IntelliSense shows that "tilde-slash" (~/) points to ASP .NET Core 3.1 project root **instread** of wwwroot subfolder after upgrading Visual Studio Enterprise 16.5.6->16.6.0](https://developercommunity.visualstudio.com/content/problem/1043674/intellisense-shows-tha-tilda-points-to-asp-net-cor.html)

**Comment by TerryGLee** [comment]
@JaquelineWiddis FYI on this

**Comment by JacquelineWiddis** [comment]
A PR with the fix has been submitted.

**Comment by TerryGLee** [comment]
The PR is processed and the fix is live. 
@msivia Thanks for helping us improve the documentation! 
Closing this issue, now.
