### ISSUE TITLE
Visual Studio 2019 v16.6.1: Help missing for options dialogs

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#5495]
---
**Issue moved from MicrosoftDocs/feedback#2828**
- Please respond to @SetTrend.

---

_From @SetTrend on Saturday, June 6, 2020 4:31:08 PM_

After updating to Visual Studio 2019 v16.6.1, again quite a number of help pages are missing.

Please, don't publish a new Visual Studio version to public without having help pages for all options available at the ready.

**Comment by TerryGLee** [comment]
Related issues:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/5158
https://github.com/MicrosoftDocs/visualstudio-docs/issues/1090

**Comment by TerryGLee** [comment]
@SetTrend Thanks for your feedback. We must close this GitHub Issue now; we are aware that some **Tools** > **Options** pages might not be documented but in keeping with our prioritization matrix, we've focused on making sure that the most-used options that are common across all [workloads](https://learn.microsoft.com/visualstudio/install/modify-visual-studio#change-workloads-or-individual-components) are fully documented. If you think that we're missing an Options page that matches those criteria, please open a new issue and we'll review it.
