### ISSUE TITLE
Which workload is for JSON intellisense for Visual Studio?

### ISSUE THREAD

**Issue by SLdragon** [MicrosoftDocs/visualstudio-docs#5501]
Hi, team, 
I cannot find any document about which workload is for JSON intellisense, I want to enable or disable this workload, but I cannot find what workload is indeed for JSON.

**Comment by WilliamAntonRohm** [comment]
@SLdragon -- Renlong, thank you for your question.  Can you provide any link to a docs.microsoft.com article that got you here?  Meanwhile, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by SLdragon** [comment]
Thanks, from test we found the json intellisense is include in "Javascript and TypeScript language support" workload, and I think we can add some tips in this doc: https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019

**Comment by WilliamAntonRohm** [comment]
@SLdragon -- Renlong, thank you for clarifying.

@ornellaalt -- Ornella, please look into this issue.

**Comment by ornellaalt** [comment]
Thank you for your feedback @SLdragon. The components in the component directories for Visual Studio Enterprise, Community, Professional, etc are automatically generated for each release. I will include a note to the engineering team that we should specify JSON support in the Javascript and TypeScript language support description. 

Closing out this issue.
