### ISSUE TITLE
Would be great to have docs for the ms build commands that can be used in Azure Dev ops pipeline tasks

### ISSUE THREAD

**Issue by Dima11235813** [MicrosoftDocs/visualstudio-docs#5502]
Specifically looking for info around Ms Build CLI parameters
/p:WebPublishMethod
/p:PublishUrl
/p:PrecompileBeforePublish
/p:DeployOnBuild
/p:PackageAsSingleFile
/p:SkipInvalidConfigurations
/p:PackageLocation
/p:DeployDefaultTarget
/p:DesktopBuildPackageLocation
For example, which commands override other commands.

When I changed p:PackageAsSingleFile to false, it still produced a zip.

When I removed WebPublishMethod=Package it followed the command.

Would using 
/p:WebPublishMethod=FileSystem /p:publishUrl="$(build.artifactstagingdirectory)\customOutputFolder"
also effectively avoid zipping but enable setting a folder under the artifact staging dir
Does that folder exist, or would it have to be made manually?

Does using, p:publishUrl prevent using 
/p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\PortalApiWebApp.zip

There have been a number of inquiries around how to avoid making a zip.

https://stackoverflow.com/questions/50495038/msbuild-arguments-to-generate-files
https://stackoverflow.com/questions/48076103/vsts-build-ended-with-empty-build-artifacts?rq=1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Properties can come from the various SDKs and not necessarily from MSBuild itself, so these properties are specific to the project types you are building.

See https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019 for a list of *MSBuild* frequently used properties, but I only see SkipInvalidConfigurations there, not the others.
