### ISSUE TITLE
Mac Visual Studio Community Project Template File Location

### ISSUE THREAD

**Issue by filjan** [MicrosoftDocs/visualstudio-docs#5504]
I have Mac Visual Studio 2019 installed but these folders are not on my computer

rm -rf ~/Library/Application\ Support/VisualStudio
rm -rf ~/Library/Application\ Support/VisualStudio/7.0/LocalInstall/Addins/
rm -rf ~/Library/Application\ Support/VisualStudio/8.0/LocalInstall/Addins/

Is this incorrect? It would be nice to know where the Addins folder is located.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Uninstall Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?ranMID=24542&ranEAID=msYS1Nvjv4c&ranSiteID=msYS1Nvjv4c-4Z.4NXOmGMhB2w7i4DfoGg&epi=msYS1Nvjv4c-4Z.4NXOmGMhB2w7i4DfoGg&irgwc=1&OCID=AID2000142_aff_7593_1243925&tduid=(ir__roprmhwya0kfrmflkk0sohzixu2xn9sqyq30u1x900)(7593)(1243925)(msYS1Nvjv4c-4Z.4NXOmGMhB2w7i4DfoGg)()&irclickid=_roprmhwya0kfrmflkk0sohzixu2xn9sqyq30u1x900&view=vsmac-2019)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment]
@filjan -- Filjan, thank you for your question.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@heiligerdankgesang -- Dominic, please look into this issue.

**Comment by jmatthiesen** [comment]
Hi, @filjan – If you've opened Visual Studio 2019 for Mac, you should see those file paths, except for the "7.0" path. If you switch to the macOS Finder and choose the Go > Go To Folder... menu, enter "~/Library/Application Support/VisualStudio/" in the folder path, and click Go, does that take you to a folder? If you tried using that menu before, for example, and included the "\" in the Application Support name, it wouldn't work.

**Comment by heiligerdankgesang** [comment]
We cannot reproduce this issue and haven't heard back since our last comment. I'm closing this issue. Please reach back out if you have any questions.

#please-close
