### ISSUE TITLE
Json validation in Visual Studio 2019 do not validate comments

### ISSUE THREAD

**Issue by SLdragon** [MicrosoftDocs/visualstudio-docs#5505]
Comments in JSON are not an official standard, and Visual Studio cannot detect this.
For example in VS, when a JSON with some comments, it doesn't show error message:
![image](https://user-images.githubusercontent.com/5545529/85093633-62d3cf00-b21f-11ea-8f6e-2536516ce56d.png)

And in VSCode, it can detect this:
![image](https://user-images.githubusercontent.com/5545529/85093766-b514f000-b21f-11ea-9d34-633551a9dd74.png)

And from the Options->JSON in Visual Studio, I cannot find any options related to the comments validation.

I think we should better follow the stardard JSON spec in Visual Studio and give some warning message about this just as VSCode do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34d7baa-5b74-4a87-ed21-d7fc8d9366b3
* Version Independent ID: 0249ae3d-5f05-812d-46f0-ad5a921358a4
* Content: [JavaScript and TypeScript in Visual Studio 2019 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2019?view=vs-2019)
* Content Source: [docs/javascript/javascript-in-vs-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/javascript-in-vs-2019.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@SLdragon That's a good idea and thanks for bringing it up. It doesn't appear to be a doc issue though, which is what we are tracking here. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
