### ISSUE TITLE
Typo in MSBuild command-line reference

### ISSUE THREAD

**Issue by mikolka221** [MicrosoftDocs/visualstudio-docs#5508]
> In this case the file is overwritten: msbuild myfile.proj -l:FileLogger,Microsoft.Build;logfile=MyLog.log
In this case the file is appended: msbuild myfile.proj -l:FileLogger,Microsoft.Build;logfile=MyLog.log;append=true
In this case the file is appended: msbuild myfile.proj -l:FileLogger,Microsoft.Build;logfile=MyLog.log;append=false

Last line should be:
In this case the file is overwritten: msbuild myfile.proj -l:FileLogger,Microsoft.Build;logfile=MyLog.log;append=false

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Are you sure this is a typo?  I haven't tried this out yet, but did you observe that the log is overwritten in this case?  There's also a line in the doc that says: "If you include the append switch, no matter whether it is set to true or false, the log is appended."

**Comment by ghogen** [comment]
@mikolka221 Tests show that append=false still appends. I'm working on a change that clarifies the counter-intuitive behavior.

@rainersigwald Is this a product bug?  Shouldn't append=false mean the log is not appended, but overwritten?

**Comment by rainersigwald** [comment]
🤦‍♂️

That sure would make sense, yeah. Filed microsoft/msbuild#5452.
