### ISSUE TITLE
PropertyGroup Example - Missing Closing Tag

### ISSUE THREAD

**Issue by gojimmypi** [MicrosoftDocs/visualstudio-docs#5514]
[Enter feedback here]

last XML example on the page is missing a closing `/` for `<PropertyGroup>` and should look like this:

```
<PropertyGroup>
   <PlatformTarget>x86</PlatformTarget>
   <Configuration>Debug</Configuration>
</PropertyGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a80e5d7-2db7-48c0-e8b6-ca8c3ff30017
* Version Independent ID: ad64635b-06d5-1b87-8f02-80cf25c12520
* Content: [MSBuild Target Framework and Target Platform - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-target-framework-and-target-platform.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-target-framework-and-target-platform.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review [private PR 6775](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6775).
