### ISSUE TITLE
JSON intellisense sometimes do not show all the error / warning messages in Visual Studio 2019

### ISSUE THREAD

**Issue by SLdragon** [MicrosoftDocs/visualstudio-docs#5516]
When Open a JSON file with some error / warnings, sometimes Visual Studio 2019 do not show all the errors / warnings.

![image](https://user-images.githubusercontent.com/5545529/85493342-a38c6900-b5ce-11ea-8dbe-f73ca7defb9b.png)

Related issue:
https://github.com/microsoft/vs-dtdl-language-support/issues/6

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34d7baa-5b74-4a87-ed21-d7fc8d9366b3
* Version Independent ID: 0249ae3d-5f05-812d-46f0-ad5a921358a4
* Content: [JavaScript and TypeScript in Visual Studio 2019 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2019?view=vs-2019)
* Content Source: [docs/javascript/javascript-in-vs-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/javascript-in-vs-2019.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@SLDragon Thanks for your feedback; we appreciate it. This looks like a product issue. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by SLdragon** [comment]
Thanks, I put the issue here: https://developercommunity.visualstudio.com/content/problem/1093682/json-intellisense-sometimes-do-not-show-all-the-er.html
