### ISSUE TITLE
Can I use "Assign unique names" feature for Xamarin.Forms?

### ISSUE THREAD

**Issue by yanxiaodi** [MicrosoftDocs/visualstudio-docs#5519]
Hi, there, I have a Xamarin.Forms project and the target platform is UWP. I try to use "Assign unique names" to create the automation Id but I cannot find **Name Interactive Elements.** in the **Tool** menu. Can I apply it for Xamarin.Forms? Thanks.

![image](https://user-images.githubusercontent.com/3395915/85631616-fa2a9d80-b6c9-11ea-9711-39362de25e8d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0a48be5-f89a-6133-7af7-a9abf1519968
* Version Independent ID: 64f4314d-4d96-5f46-99f3-e1bea2ddf1fb
* Content: [Set a Unique Automation Property for UWP Controls for Testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/set-a-unique-automation-property-for-windows-store-controls-for-testing?view=vs-2019)
* Content Source: [docs/test/set-a-unique-automation-property-for-windows-store-controls-for-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/set-a-unique-automation-property-for-windows-store-controls-for-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@yanxiaodi -- Yan, thank you for your question. Please consider these resources:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

As well, you might also consider using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

cc @Mikejo5000 for awareness
