### ISSUE TITLE
What about Iron Python?

### ISSUE THREAD

**Issue by Linc2GitHub** [MicrosoftDocs/visualstudio-docs#5520]
Is Iron Python a viable option to build a standalone app working with VS 2019?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ccada0-aa56-4952-5ba5-3c39137f41e4
* Version Independent ID: 083f73fd-0085-e8a3-d451-1e78ea172ad4
* Content: [Python support in Visual Studio on Windows](https://docs.microsoft.com/en-us/visualstudio/python/overview-of-python-tools-for-visual-studio?view=vs-2019)
* Content Source: [docs/python/overview-of-python-tools-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/overview-of-python-tools-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@Linc2GitHub -- thank you for your question.  Please visit this link:
- https://stackoverflow.com/questions/54275820/how-to-install-iron-python-in-visual-studio

cc @JoshuaPartlow for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
