### ISSUE TITLE
Visual Basic *does* implement this implicit ToString() evaluation.

### ISSUE THREAD

**Issue by billvolt** [MicrosoftDocs/visualstudio-docs#5525]
Page states:  Visual Basic does not implement this implicit ToString() evaluation.
Actually:  Visual Basic does implement this implicit ToString() evaluation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653452d1-1586-e971-1f6c-370a91be613f
* Version Independent ID: 348f41ea-994c-7ed2-7af5-77077f2b5696
* Content: [Display custom info using DebuggerDisplay - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2019)
* Content Source: [docs/debugger/using-the-debuggerdisplay-attribute.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-the-debuggerdisplay-attribute.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@billvolt -- thank you for your feedback.

@Mikejo5000 -- please review [private PR 6785](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6785).
