### ISSUE TITLE
Assemblies Missing From Code Coverage; Exhausted All Troubleshooting Steps

### ISSUE THREAD

**Issue by Good-man** [MicrosoftDocs/visualstudio-docs#5529]
I have a solution with 4 assemblies, 2 of them MS test assemblies, 1 dll and 1 exe (console app).  The DLL and its test assembly show up in code coverage results, but the exe does not even though I have passing test runs on that assembly.  I added the sample .runsettings file and commented out all exclusions, leaving only include all exe and dll.

I have tried all of the relevant troubleshooting steps, but none of them solved my problem.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4d41fc7-bc52-8fe3-6b25-c1b2c3f89eb1
* Version Independent ID: 9d141754-5f8f-d330-0974-75cbcf45a011
* Content: [Troubleshooting Code Coverage - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/troubleshooting-code-coverage?view=vs-2019)
* Content Source: [docs/test/troubleshooting-code-coverage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/troubleshooting-code-coverage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Good-man -- Mark, thank you for your question.  Please consider these resources:​  

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
