### ISSUE TITLE
Options not available

### ISSUE THREAD

**Issue by jeubank12** [MicrosoftDocs/visualstudio-docs#553]
For a quick-start document, this needs to list pre-requisites.  Out-of-the box I do not see any of these options for c++ code.  vcxproj, Professional version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4074bba-2193-a551-616f-54fa34d27192
* Version Independent ID: f01119e7-4ac0-0850-1842-452ef34e9a74
* [Content](https://docs.microsoft.com/en-us/visualstudio/code-quality/quick-start-code-analysis-for-c-cpp)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/code-quality/quick-start-code-analysis-for-c-cpp.md)
* Service: unspecified

**Comment by gewarren** [comment]
@mikeblome can you take look?

**Comment by jeubank12** [comment]
Just need to put a comment that this is for visual studio 2017 projects
only. If it is still in the 2015 format (v140) it is not sufficient to
simply open the project in 2017.

**Comment by gewarren** [comment]
@jeubank12 We've added the "Visual Studio 2017" label above the table of contents, so hopefully this is less confusing now.

![image](https://user-images.githubusercontent.com/24882762/50928975-ec6b5480-1410-11e9-9565-f91f3baa812b.png)
