### ISSUE TITLE
Mention that a breakpoint cannot be set on a declaration.

### ISSUE THREAD

**Issue by DeborahK** [MicrosoftDocs/visualstudio-docs#5534]
[Enter feedback here]
I received a notice from someone taking one of my courses that they could not set a breakpoint on this line of code:

public event EventHandler<string> EnrollmentFull;

I explained that one cannot set a breakpoint on a declaration unless it's being assigned a value or has a getter/setters. I then went to this documentation to provide a reference to back up my statement, and was unable to find any information on this important point.

The docs say this:

"You can't set a breakpoint on the namespace or class declarations, or on the method signature."

Please consider adding variable declarations to this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use breakpoints in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2019)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@DeborahK Thanks for the feedback. I'll plan to update the doc.

**Comment by Mikejo5000** [comment]
Updating doc. Fix should be live around 5 PM.

**Comment by DeborahK** [comment]
Was hoping for a bit more ... especially now reading this first paragraph:

`You can set a breakpoint on any line of executable code. For example, in the following C# code, you could set a breakpoint on the variable declaration, the for loop, or any code inside the for loop. You can't set a breakpoint on declarations for a namespace, class, or variable, or on the method signature.`

So we first say: ` you could set a breakpoint on the variable declaration`

Then say: `You can't set a breakpoint on declarations for a namespace, class, or variable`

If I were a beginner, I would be very confused by that?

Would it be possible to elaborate? And say when we *can* and when we *cannot* set a break point on a variable declaration?

Thank you!

**Comment by Mikejo5000** [comment]
You're right. I missed that first sentence. I'll look at this a bit closer.

**Comment by Mikejo5000** [comment]
I checked this. In the example, you can set the breakpoint because there's an assignment, so the line executes (you can pause on it while running code). You can't set a breakpoint on a variable declaration if there's no assignment. I'll edit this.

**Comment by Mikejo5000** [comment]
Updating. It should be live around 5 PM. Added the getter/setter info, too.
