### ISSUE TITLE
Unable to open Diff view with double click.

### ISSUE THREAD

**Issue by v4n5h4j** [MicrosoftDocs/visualstudio-docs#5535]
Point 4 (part 2): "Double-click a file in the Changes list to open a diff view for that file."

1.  Nothing happens on double clicking the modified file in Changes list. However, clicking "Compare with Unmodified" in the right click menu for the file does open Diff view.
![Untitled Project](https://user-images.githubusercontent.com/60320402/85969664-f6f32280-b9e5-11ea-8e1d-7d96b8b26713.gif)

**UPDATE:**
2.  Double clicking a file in changes list does open diff view given that the file name doesn't have an asterisk symbol in front of it. Ex. In the image below, double clicking 'app.txt' opens it in diff view but double clicking 'styles.txt' doesn't. The right click menu option 'Compare with Unmodified..' works with both.
![image](https://user-images.githubusercontent.com/60320402/86239989-fb723380-bbbd-11ea-9bb3-32bf8d36feaa.png)

↠ I've tried restarting VS 2019.

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2103a566-905f-f3a1-08b6-a07d076398ad
* Version Independent ID: 926343f9-0e59-1991-473c-f604ab369eb5
* Content: [Python in Visual Studio tutorial step 6, work with Git](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Closing given time open and as this doesn't seem to be an issue with the documentation. If it's still a problem you think should be addressed, please feel free to reopen and tag me.
