### ISSUE TITLE
Doesn't seem to address repos NOT on an Asure DevOps server???

### ISSUE THREAD

**Issue by kehollin** [MicrosoftDocs/visualstudio-docs#5545]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f31dd7-e676-aa47-cb11-8ad77412fb5a
* Version Independent ID: 6cce7a4b-8f62-610d-f75f-fafc7b4c444a
* Content: [Connect to projects in Team Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/connect-team-project?view=vs-2019)
* Content Source: [docs/ide/connect-team-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/connect-team-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@kehollin -- Kevin, thank you for your feedback.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@TerryGLee -- Terry, please look into this issue.

**Comment by TerryGLee** [comment]
@kehollin Thanks for contacting us. To answer your inquiry, we do support connecting to repos that are not hosted on Azure DevOps. The first paragraph on the page says "Team Explorer connects Visual Studio to Git and GitHub repositories, Team Foundation version control (TFVC) repositories, and projects hosted on Azure DevOps Services or an on-premises Azure DevOps Server (formerly known as TFS)." Notice that the words "Git and GitHub repositories" are the first type of repos that are listed.

Granted, the UI in Visual Studio does highlight Hosted Services Providers such as Azure DevOps at the top of the Team Explorer-Connect dialog, but right below that in the UI is a section that says "Local Git Repositories". To make this functionality more clear, I've added a link to the "See also" section of this [Connect to projects in Team Explorer](https://docs.microsoft.com/visualstudio/ide/connect-team-project?view=vs-2019) page to our "[Open a project from a repo](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-open-project-from-repo?view=vs-2019)" tutorial, which includes an "[Open a project from a GitHub repo](https://docs.microsoft.com/visualstudio/get-started/tutorial-open-project-from-repo?view=vs-2019#open-a-project-from-a-github-repo)" section. 

We'll close this issue for now, with our thanks to you for helping us improve the documentation!

~ Terry

p.s. We are working on new Git functionality in the product, currently in [Preview](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview?view=vs-2019) if you'd like to try it out. You can read more about it in the following blog post, [Improved Git Experience in Visual Studio 2019](https://devblogs.microsoft.com/visualstudio/improved-git-experience-in-visual-studio-2019/). As an FYI: After this feature is out of Preview, we'll update all our Docs pages to reflect the new experience.
