### ISSUE TITLE
Docker VS2017 instructions: installPath ignored & dev prompt errors out

### ISSUE THREAD

**Issue by helmesjo** [MicrosoftDocs/visualstudio-docs#5548]
I copy-pasted the dockerfile shown [here](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2017), and replaced:
`--add Microsoft.VisualStudio.Workload.AzureBuildTools`
with:
`--add Microsoft.VisualStudio.Workload.VCTools;includeRecommended`

So extremely minimalistic example.

**First issue** is that the `--installPath` is ignored (installs to default path nontheless). This appears to be a recurring problem looking at other issues here, why?

**Second issue** (if I use the default path) is that the `VsDevCmd.bat` script fails to start:
```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt vError 0x57: Unknown parameter: path
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
```

**Also**, why does it say "Visual Studio 2019 Developer Command Prompt" when I'm explicitly installing the VS2017 tools?

**Comment by helmesjo** [comment]
FWIW, [this](https://github.com/microsoft/vs-dockerfiles/blob/master/native-desktop/Dockerfile) example works (and shows correct "2017" command prompt)...

**Comment by helmesjo** [comment]
And `--installPath` stops working and the `Unknown parameter: path` error happens if I change base image from:
`microsoft/dotnet-framework:3.5-sdk-windowsservercore-1709`
to:
`mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2019`

**Comment by helmesjo** [comment]
Small note: 
Using above base image I'm having trouble cloning repositories with git, which appears to be related specifically to the 1709 build:
https://github.com/git-for-windows/git/issues/1403

**Comment by helmesjo** [comment]
Update:
Changed to base image `mcr.microsoft.com/powershell:lts-windowsservercore-1809` and it solves above mentioned problems.

**Comment by ornellaalt** [comment]
Hi @helmesjo, just to confirm, was your issue solved? If so, I'll close out this issue.

**Comment by helmesjo** [comment]
@ornellaalt Sorry for late response!
Well "not all", but yes it at least fixes the issues related to this issue so you can close it. :)

**Comment by hjmallon** [comment]
I am hitting very similar issues I wonder if anyone can help. Why does installing using 2017 sometimes put things in 2019? Is it actually installing 2019 underneath?

**Comment by j-martens** [comment]
#reassign:@anandmeg

**Comment by anandmeg** [comment]
#reassign:@ghogen container related issue?

**Comment by ghogen** [comment]
#reassign:@anandmeg This relates to the installation of VS tools into a container, which I don't own. I only own the Container Tools docs for developers working with their own containers (e.g. deploying and debugging containerized apps)

**Comment by anandmeg** [comment]
@hjmallon - thank you for your feedback. This appears to be a product issue rather than a documentation issue. Please add it here: 
- [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio)

I am closing this issue now; thanks again for contacting us.
