### ISSUE TITLE
Update TDD doc

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/visualstudio-docs#555]
The [Test Driven Development with C#](https://docs.microsoft.com/en-us/visualstudio/test/quick-start-test-driven-development-with-test-explorer) doc is looking a bit dated. We should redo the screenshots and perhaps update some of the wording.

**Comment by gewarren** [comment]
@kendrahavens Is this something you can do, or do you need help from me?

**Comment by kendrahavens** [comment]
@gewarren It'd be great to get help on this. (Sorry for the slow response.)

Some of the wording like the "Show All" button does not exist in VS2017. All the screenshots are looking outdated. I haven't stepped through the whole doc, but wouldn't be surprised if the instructions for method and type generation from tests has changed a bit as well.

**Comment by gewarren** [comment]
~2K page views per month.

**Comment by gewarren** [comment]
I updated this topic in July.
