### ISSUE TITLE
indicate how to disable all assertions temporarily

### ISSUE THREAD

**Issue by Caleb-D** [MicrosoftDocs/visualstudio-docs#5550]
Many times I am debugging code partially written by someone else.  I get lots of unnecessary assertions (for one reason or another) and have to click past them all.  I finally found how to disable all assertions (temporarily).  Would be good to update this topic with a link to this page: https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/1y71x448(v=vs.100)?redirectedfrom=MSDN

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b528831-6809-773c-e160-a90f9698addf
* Version Independent ID: 1e9e4cae-c0f5-93c5-60f1-4e39743fe1b5
* Content: [C/C++ Assertions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/c-cpp-assertions?view=vs-2019)
* Content Source: [docs/debugger/c-cpp-assertions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/c-cpp-assertions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Current doc for [_CtrSetReportMode](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/crtsetreportmode?view=msvc-160)

**Comment by Mikejo5000** [comment]
Adding link. Fix should go live by EOD today.
