### ISSUE TITLE
I used runsettings but it does not exclude given assemblies

### ISSUE THREAD

**Issue by manishi2V** [MicrosoftDocs/visualstudio-docs#5553]
I questioned this issue in [stackoverflow.](https://stackoverflow.com/questions/62710466/runsettings-xml-file-not-working-with-dotnet-test-coverage-command)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43dc6fcf-df9f-9d2a-5c6e-8da0f6925afc
* Version Independent ID: d0bf2cae-9b59-d537-7acb-7af5f560d8c1
* Content: [Customizing Code Coverage Analysis - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/customizing-code-coverage-analysis?view=vs-2019)
* Content Source: [docs/test/customizing-code-coverage-analysis.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/customizing-code-coverage-analysis.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@manishi2V -- Manish, thank you for your feedback.  In addition to StackOverflow, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@Mikejo5000 -- Mike, please look into this potential documentation issue.

**Comment by Mikejo5000** [comment]
@manishi2V Did you try using the Exclude element to exclude WC_ControllerTests.Common and WC_ExportTestCase?

**Comment by Mikejo5000** [comment]
I would try using Exclude to resolve this. In addition, It sounds like you either have something in your runsettings file that's causing the unexpected behavior, or there's a bug in the product. If you think it's the latter, please log an issue by using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). There, you can engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
You might also test it as a regular expression instead of Exclude. Let me know if that works better.

<Include>
  <ModulePath>.*WCController.dll$</ModulePath>
</Include>

**Comment by Mikejo5000** [comment]
Closing as presumably resolved, or we need more info.
