### ISSUE TITLE
Example code for .net core should be added

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/visualstudio-docs#5555]
Section 3.) under: https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2019&redirectedfrom=MSDN#build-the-target

example code for .net core should be added to the docs:
`msbuild buildapp.csproj -t:HelloWorld` --> dotnet core: `dotnet msbuild buildapp.csproj -t:HelloWorld`

I've prepended the ´HelloWorld´ target before `</Project>`, but I don't get to see the specified message, just:

> dotnet msbuild -t:HelloWorld
> Microsoft (R) Build Engine version 16.7.0-preview-20310-07+ee1c9fd0c for .NET
> Copyright (C) Microsoft Corporation. All rights reserved.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41d57f6-25bf-bc84-7ba8-4cb4ecedac05
* Version Independent ID: 69c3bd43-6c2b-834b-18d2-0555a79961a7
* Content: [Walkthrough: Using MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-using-msbuild?view=vs-2019&redirectedfrom=MSDN)
* Content Source: [docs/msbuild/walkthrough-using-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-using-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by Legends** [comment]
Ok, I can now see the output of the `Message` task by adding the `-v:detailed` switch

**Comment by WilliamAntonRohm** [comment]
@Legends -- thank you for your suggestion and followup.

@ghogen -- please look into this issue.
