### ISSUE TITLE
Unclear about pipeline access to non enterprise Visual Studio Subscriptions

### ISSUE THREAD

**Issue by duncanhunter** [MicrosoftDocs/visualstudio-docs#5556]
It is unclear if all Visual Studio Subscribers have rights to author release pipelines and manage releases as expressed on this other part of the docs https://docs.microsoft.com/en-us/azure/devops/organizations/security/access-levels?view=azure-devops.

Our large government customer read this as their Visual Studio Subscribers can not use pipelines.

I would suggest listing pipelines in the benefits for all the listed subscriptions here.

![pipelines-descrepency](https://user-images.githubusercontent.com/2058227/86555336-68f1db80-bf93-11ea-9de3-7fc6a7304428.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@duncanhunter  We've made some changes to the article to provide some clarity.   Remember that the content of the Basic plan is determined by Azure, not by the Visual Studio subscription.  Both Professional and Enterprise receive the Basic plan.  If there are question about the implementation and use of the Basic plan, those should be addressed with Azure support.

**Comment by evanwindom** [comment]
#please-close
