### ISSUE TITLE
Information is partially invisible at 1366x768

### ISSUE THREAD

**Issue by Anton-V-K** [MicrosoftDocs/visualstudio-docs#5558]
Left column of the table is usually invisible when viewing in a browser at 1366x766 - it is covered by right floating-like area/panel with page content:
https://i.ibb.co/km5Z95J/2020-07-06-Visual-Studio-Community-component-directory-1366x768-Firefox.png
And there is no horizontal scrollbar.
There are 10%-like marging at left and right edges, which are just a waste of space.
You cannot hide the tree-like structure, which eats a lot of space, but is useless when you reviewing the page content.

Checked browsers: Vivaldi 2.11.1811.47, Opera 67.0.3575.79, Firefox 74.0

**Workaround**: you can bring hidden information into view with the mouse - left-click and drag as if selecting some text.

![2020-07-06-Visual-Studio-Community-component-directory-1366x768-Firefox 1](https://user-images.githubusercontent.com/20116984/86611019-c64b5400-bfb6-11ea-82f9-4c60402690eb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4891ebc9-fdea-c376-94f6-17295ca275d7
* Version Independent ID: ccc61918-cc18-a7ff-cc6c-8659d6c9c78a
* Content: [Visual Studio Community workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2017)
* Content Source: [docs/install/workload-component-id-vs-community.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-community.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@Anton-V-K -- thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
