### ISSUE TITLE
Incorrect KB shortcut for Promote

### ISSUE THREAD

**Issue by djsmith** [MicrosoftDocs/visualstudio-docs#5562]
The KB shortcut for _Promote the definition window to a regular document tab_ is shown as **Shift+Alt+Home**, but on my computer with VS 2017 (15.9.24) it is **Ctrl+Alt+Home**.

I don't think I manually changed the KB mapping for this function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5581850-0f4e-f0b4-21e9-ae6cd686614f
* Version Independent ID: e0e80b01-94a0-99de-6a93-70cc341cc212
* Content: [Using Peek Definition - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-view-and-edit-code-by-using-peek-definition-alt-plus-f12?view=vs-2019)
* Content Source: [docs/ide/how-to-view-and-edit-code-by-using-peek-definition-alt-plus-f12.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-view-and-edit-code-by-using-peek-definition-alt-plus-f12.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@djsmith -- Dan, thank you for your feedback.  My Visual Studio 2019 agrees with your keyboard and I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- Terry, please review [private PR 6843](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6843).
