### ISSUE TITLE
Where is Output parameter described?

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/visualstudio-docs#5564]
https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-inline-tasks?view=vs-2019#input-and-output-parameters

Where is Output parameter described?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d2edce4-67ce-e93c-269e-e4200895a1b9
* Version Independent ID: 4af4b53f-7103-e8b8-996f-79fbc71b83b6
* Content: [MSBuild Inline Tasks - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-inline-tasks?view=vs-2019#input-and-output-parameters)
* Content Source: [docs/msbuild/msbuild-inline-tasks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-inline-tasks.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Legends -- thank you for your question.  That section describes parameters, each of which may be an input, an output, or both.  An output parameter, that is, a parameter that must have a value upon return, is defined with the optional `Output` attribute set to `true`:

```
  <Tally ParameterType="System.Int32" Output="true" />
```

I hope this helps to answer your question.  
I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Legends** [comment]
@WilliamAntonRohm 

Yes, I have one further question. How do you consume the Output parameter?
For example I want to use it in another `Task` or print it to the console after execution.

```
<ParameterGroup>
   <Tally ParameterType="System.Int32" Output="true" />
</ParameterGroup>
```

**Comment by WilliamAntonRohm** [comment]
@Legends -- please see this section:
- https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-inline-task?view=vs-2019#define-the-adder-task

The Output parameter C is consumed in this line:
```
    <Output PropertyName="Sum" TaskParameter="C" />
```

Please let me know if this helps answer your question.

**Comment by Legends** [comment]
Thanks for the link William, this is what I was looking for.

I guess it would be good to add it to:
docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-inline-tasks?view=vs-2019#input-and-output-parameters

instead of going through the walkthrough. But this is up to you guys.

Thanks.

**Comment by WilliamAntonRohm** [comment]
cc @ghogen for awareness

**Comment by ghogen** [comment]
Thanks @WilliamAntonRohm - I will update the docs accordingly.
