### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#557]
First paragraph. (Note: Benefit must by activated before you can submit a support request.). "by" should be "be"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79453c-3962-2f0c-5b99-4fbde91972f8
* Version Independent ID: c845c29e-dfd7-316e-81b2-ebe288a384c1
* [Content](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-tech-support#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/subscriptions/vs-tech-support.md)
* Service: unspecified

**Comment by Nathan-Tarin** [comment]
Last section. Submitting an incident within the Azure portal. Step 4. Enter the provide “Access ID” and “Contact ID” provided in #1 above. "Contact ID" should be "Contract ID".

**Comment by gewarren** [comment]
@Nathan-Tarin thanks for letting us know about these typos!

**Comment by Nathan-Tarin** [comment]
No problem ☺

I am a SME for this Microsoft product (Visual Studio Subscriptions) so feel free to let me know if you need any support on the matter.

Regards,


Nathan Tarin
Arvato Programs Facilitator
M O N T E R R E Y
arvato
BERTELSMANN
Avenida San Jeronimo # 880
Col. San Jeronimo
64634 Monterrey,
Nuevo León, Mexico
mailto:jonathan.tarin@arvato.com
(Please note new email address)
Office: +1 (519) 513-1127 ext 3004
Mobile: +52 1 (812) 150 6149
Please consider your environmental responsibility before printing this e-mail.
The information contained in this message is privileged, confidential, and protected from disclosure. This message is intended for the individual or entity addressed herein. If you are not the intended recipient, please do not read, copy, use or disclose this communication to others; please notify the sender by replying to this message, and then delete it from your system.

**Comment by evanwindom** [comment]
@gewarren Can we close this, please?  The corrections are live.
