### ISSUE TITLE
Regarding publishing a rest API from Visual Studio to Azure App service.

### ISSUE THREAD

**Issue by yaxum** [MicrosoftDocs/visualstudio-docs#5571]
Hi!

I have followed the guide:
https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-to-azure?view=vs-2019

However after publishing the app it does not work att all, I only get 404 and 500 in the error message. 
The strange thing is that I get it to work when trying out the same thing with the default weatherforcast rest API but not with my own rest API that I made... Do you have any ideas of where I should debugg to fix it for my own rest API?

**Comment by WilliamAntonRohm** [comment]
@yaxum -- Yaxum, thank you for your question.  Please consider these resources:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are also welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
