### ISSUE TITLE
CA1724 documentation should describe the cases where naming collisions would cause confusion

### ISSUE THREAD

**Issue by DaleStan** [MicrosoftDocs/visualstudio-docs#5572]
The documentation for CA1724 says "Before you suppress the warning, carefully consider how the users of your library might be confused by the matching name." However, there is no example of how the naming collision could cause confusion.

I understand that a class named `BusinessDomain.BusinessObjects.Display.Display` is a bad idea, but in my particular case, I am building a library for my business domain, and I have a conflict between the type `BusinessDomain.BusinessObjects.Display` and the namespace `Serilog.Formatting.Display`. Under what circumstances would this or similar naming conflicts cause confusion?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91945e5b-8c25-f409-fc76-e57bdf58cb15
* Version Independent ID: 5cfb7f25-82e3-5d35-f798-12c2e0396f19
* Content: [CA1724: Type Names Should Not Match Namespaces - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1724?view=vs-2019)
* Content Source: [docs/code-quality/ca1724.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1724.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@DaleStan It sounds like you have carefully considered whether users of your library might be confused, and you've concluded that they will not be confused. For a long discussion of the issue, I'd suggest this post: https://social.msdn.microsoft.com/Forums/en-US/86c94c19-8ba5-44db-84d6-61469b38c520/typenamesshouldnotmatchnamespaces-aka-ca1724?forum=vstscode

**Comment by Mikejo5000** [comment]
I looked at this more closely to see whether it makes sense to add an example to show how confusion might result. Here's a naming collision, flagged in the IDE by CS0104, an ambiguous reference, in addition to CA1724.

```csharp
using System;
using MyContainers.Array;

namespace MyNamespace
{
    class Program { 
        public void Main()
        {
            Array arr; 
        }
    }
}

namespace MyContainers.Array
{
    public class Array
    {
    }
}
```
The article doesn't actually mention "naming collisions", however, just confusion to users by the matching names, so I'm not sure this example ought to go in the docs. Closing for now. Let me know if you have any additional thoughts about it.

**Comment by DaleStan** [comment]
@Mikejo5000 Your example doesn't answer the question I was trying to ask. It demonstrates confusion between two different types both named `Array`, and presents a strong case for "Do not use type names that are used in the System namespace." It also violates the guideline "Do not use the same name for a namespace and a type in that namespace."

As far as I can tell, CA1724 is not trying to enforce either of those guidelines. Rather, it says that Alice should not write a library containing:
```cs
namespace Alice.Library
{
    public class Server
    {
    }
}
```
She should not do this because Bob might get confused when writing:
```cs
namespace Bob
{
    class Program
    {
        static void Main()
        {
            // Bob gets confused here because he doesn't know whether "Server" means
            // the type Alice.Library.Server or the namespace Microsoft.SqlServer.Server.
        }
        // Bob might get confused here also/instead.
    }
}
```

I'm looking for an example that expands on Bob's file to demonstrate his confusion.

**Comment by Mikejo5000** [comment]
Thanks for clarifying. My impression of this rule, reading through the doc and various discussions, is that the level of confusion that results from this situation may vary quite a bit.

In the forums thread I linked to about CA1724, it is stated:

"Given that a type and a namespace are not likely interchangable, it's reasonable to expect that the namespace System.Security.Util, for example, would never be mistaken for a type such as WindowsApplication1.Util; especially once a compile takes place." (Which I think is also what you are saying when you ask for an example?)

I don't see in the response a suggestion that customers actually will mistake a namespace for a type. Instead, the response is:

"**The issue arises when users import (via an using statement for C#, or imports statement/default imports for Visual Basic) namespaces with types that contain the same name**, or you need to use a namespace that contains the same name as a type or vice versa. Although you may like to fully qualify types to distinguish between these types/namespaces, other users may not and do not. However, by naming them the same as other types your forcing your consumers to do this."

In the thread, it is also stated in a later response:

"Although, after re-reading the guidelines there is no explicit guideline stipulating that a type should not be named the same as a namespace, we have decided to keep this rule. We only rip rules if they don't provide useful analysis, we feel that this rule does;  naming your type 'System' or 'Windows' or 'Drawing' is just bad."

.NET made some changes to the rule implementation at that point, but it looks to me that the preceding appears to still apply.

**Comment by DaleStan** [comment]
The section you bolded in the referenced thread is talking about "Do not use the same name for a namespace and a type in that namespace". I stand corrected; CA1724 does enforce this rule. I understand that rule, but I'm trying to understand a different rule that CA1724 is also enforcing.

> "Given that a type and a namespace are not likely interchangable, it's reasonable to expect that the namespace System.Security.Util, for example, would never be mistaken for a type such as WindowsApplication1.Util; especially once a compile takes place." (Which I think is also what you are saying when you ask for an example?)

I'm not entirely sure what Peter meant by "especially once a compile takes place." but I think that's the sort of example I'm looking for.

> "we feel that this rule does [provide useful analysis]; naming your type 'System' or 'Windows' or 'Drawing' is just bad."

Creating a type named System is definitely a Bad Thing, but I feel like Windows would be a reasonable name for a collection type in a library that interfaces with X, and WPF has a System.Windows.Media.Drawing class.

Is there a way Bob could confuse the namespace Microsoft.SqlServer.Server and the class Alice.Library.Server? If not, I now think CA1724 should be relaxed to enforce the rule "Type names should not match _top level or ancestor_ namespaces". In application, this would mean that no one should ever name a class System or Microsoft, and Alice should not name any of her classes Alice or Library, but she can name a class Server without conflicting with the Microsoft.SqlServer.Server namespace.

**Comment by Mikejo5000** [comment]
OK, although that makes sense to me, it's a change in rule implementation (vs. doc issues here). So, you could open the request here to move it forward:
https://github.com/dotnet/roslyn-analyzers
