### ISSUE TITLE
Multi-caret selection - Select All

### ISSUE THREAD

**Issue by JeepNL** [MicrosoftDocs/visualstudio-docs#5574]
In the docs at https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019#multi-caret-selection it says:

`Ctrl+Shift+Alt+,`    Add all matching text as selections

That doesn't work (_Version 16.7.0 Preview 3.1_) but `Alt+Shift+;` does. (_Googled it_)

**Comment by TerryGLee** [comment]
@JeepNL Thanks for letting us know; we'll check in to this and report back soon.

**Comment by TerryGLee** [comment]
There's a PR on the public repo that'll address this; it should be published, soon. 
https://github.com/MicrosoftDocs/visualstudio-docs/pull/5978

**Comment by TerryGLee** [comment]
@JeepNL We've updated the keyboard shortcuts in the [Multi-caret selection](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019#multi-caret-selection) section on the "Find & Replace Text" page to reflect what you reported. We'll make further updates to the page to capture recent feature changes, soon. Meanwhile, we thank you for your help with improving our documentation!
