### ISSUE TITLE
Issue: Left side table of contents doesn't display in Microsoft Edge Browser

### ISSUE THREAD

**Issue by jdodds-air** [MicrosoftDocs/visualstudio-docs#5575]
Microsoft Edge 44.19041.1.0

Google Chrome and Edge Chromium don't have the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38ae1727-4def-5921-86ec-bc65e9f0b8e4
* Version Independent ID: aed7dda1-6bfd-945f-04a5-86ee0fe62d95
* Content: [Overview of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-studio-ide?view=vs-2017)
* Content Source: [docs/get-started/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-studio-ide.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@jdodds-air -- thank for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by jdodds-air** [comment]
I submitted this from one of the broken pages. I didn't pick this location.
