### ISSUE TITLE
Renewal

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#558]
Can we add a section to this documentation that provides instructions and background for subscription renewals? i.e. how to apply the renewal code and more importantly, when this can be applied and when it can't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21b45f8d-2c76-7fa7-252d-31c99ada9ae6
* Version Independent ID: aa760ad5-2298-c6aa-a6c9-fd8e5238a8cd
* [Content](https://docs.microsoft.com/en-us/visualstudio/subscriptions/buy-vs-subscriptions)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/subscriptions/buy-vs-subscriptions.md)
* Service: unspecified

**Comment by evanwindom** [comment]
Are you asking about renewing using a 5x5?  Using the key is the same whether the customer buys a new subscription or a renewal.  We could note that, but it doesn't warrant its own section.

**Comment by Nathan-Tarin** [comment]
Yes, I think a note or an explanation that activating a new subscription and renewing it should be there. To clarify the process for the untrained eyes. ☺

**Comment by evanwindom** [comment]
We're moving away from the use of this page entirely and will instead use smaller, more specific pages to detail the different acquisition experiences.  

@gewarren  Can you close this for us, please?  Thanks!
