### ISSUE TITLE
Base class example in C#, derived class example in VB

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [MicrosoftDocs/visualstudio-docs#5580]
On this page, the code for the base class (`TypeA`) is written in C#, but the example for the derived class (`TypeB`) is in VB. This feels kind of odd.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54561ecc-39fa-b5e3-d51f-e4725182eb4f
* Version Independent ID: ea8b6449-40aa-f4bc-d341-d636fe8c43c0
* Content: [CA2215: Dispose methods should call base class dispose - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2215)
* Content Source: [docs/code-quality/ca2215.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca2215.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Bosch-Eli-Black -- thank you for your feedback.  I believe the different examples are to show the ideas as expressed in each language.

@Mikejo5000 -- please advise.

**Comment by Mikejo5000** [comment]
It's a little odd. Looks like the second example should be in C#, or both.

**Comment by Bosch-Eli-Black** [comment]
I suppose that ideally, each example would have both C# and VB variants, with the option for the user to choose which language he wants to view the samples in, as is done on some other pages :D

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22039](https://github.com/dotnet/docs/issues/22039)
