### ISSUE TITLE
The namespace name 'SyntaxTree' could not be found on MacOS

### ISSUE THREAD

**Issue by marcelwooga** [MicrosoftDocs/visualstudio-docs#5581]
# Tested with:
* Unity version: 2018.4.19f1
* Visual Studio for Mac version: 8.6.5 (build 23)
* MacOS 10.15.5

# Issue:
If Visual Studio for Mac is installed, the constant `ENABLE_VSTU` becomes active and breaks scripts which do project file customization because the namespace `SyntaxTree` can't be found on the Mac.

# Steps to reproduce:
1. Install Unity and Visual Studio for Mac
2. Copy example script from [here](https://docs.microsoft.com/en-us/visualstudio/cross-platform/customize-project-files-created-by-vstu?view=vs-2019#example)
3. Paste it into the Unity project (Editor folder or normal folder, doesn't matter)
4. You will get this error: `error CS0246: The type or namespace name 'SyntaxTree' could not be found (are you missing a using directive or an assembly reference?)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a4fd25-8def-13c4-d35f-e81043b21e4d
* Version Independent ID: 55ceba14-64a8-20a9-73ce-e16f410f1936
* Content: [Customize Project Files Created by VSTU - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/customize-project-files-created-by-vstu?view=vs-2019)
* Content Source: [docs/cross-platform/customize-project-files-created-by-vstu.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/customize-project-files-created-by-vstu.md)
* Product: **visual-studio-windows**
* Technology: **vs-unity-tools**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by WilliamAntonRohm** [comment]
@marcelwooga -- Marcel, thank you for your feedback.

@conceptdev -- Craig, please look into this issue.

**Comment by conceptdev** [comment]
Unfortunately I no longer work in this area - I'll ping someone from the team to take a look. They should probably remove me from the metadata too.

**Comment by WilliamAntonRohm** [comment]
@conceptdev, thank you for your assistance.
