### ISSUE TITLE
This is four BuildEngines out of date

### ISSUE THREAD

**Issue by Forgind** [MicrosoftDocs/visualstudio-docs#5584]
Should be on IBuildEngine7

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c479e76-fd43-499b-7ef1-dbf935224702
* Version Independent ID: 52955c08-25dc-ad9e-f610-6f3aecdd8fb3
* Content: [Task Base Class - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/task-base-class?view=vs-2019)
* Content Source: [docs/msbuild/task-base-class.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/task-base-class.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Forgind -- thank you for your feedback.

@ghogen -- please look into this issue.

**Comment by Forgind** [comment]
More than four BuildEngines out of date now...

We also have a PR out to change the schema entirely, which would make it not change as fast. I don't care too much about this part of our documentation, though, so I'm fine with letting it be closed.
