### ISSUE TITLE
Very Good Description

### ISSUE THREAD

**Issue by sivanathanb04** [MicrosoftDocs/visualstudio-docs#5586]
All where properly explained.It would have better if **Automatically download updates** was shown with a red box in the image

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3386e-6b18-1cbd-9f1b-523b27b6521b
* Version Independent ID: 5ddf5e28-86d1-28b6-80ef-332bf93e17ac
* Content: [Update Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2019)
* Content Source: [docs/install/update-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@sivanathanb04 -- thank you for the compliment!  That setting was not highlighted in a red box because it is optional.

cc @ornellaalt for awareness
