### ISSUE TITLE
Substitution mechanism of e.g. `Condition=` values unclear

### ISSUE THREAD

**Issue by lukasjuhrich** [MicrosoftDocs/visualstudio-docs#5588]
The documentation is incomplete in the following aspects.

1. The example for string equality (`Condition="'$(Configuration)'=='DEBUG'"`) uses a dollar-construct. However, nowhere in this particular page of the documentation it is mentioned that any kind of preprocessing happens.

2. `Condition` values seem to be context sensitive: If I use a condition on an `Item`, appearently one cannot access metadata values.

**To expand on 1:** I am aware that with `$(PropertyName)` I can – at many locations in a `.csproj` file – substitute the value of properties. In the [MSBuild properties documentation](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-properties?view=vs-2019), it is acknowledged that
> Throughout the project file, properties are referenced by using the syntax `$(<PropertyName>)`.

However, in my opinion, that is completely insufficient: It fails to define the precise scope of when such a substitution happens or is valid, and furthermore only talks about properties, while other substitutions such as `@()` and `%()` are also possible.
It would be way more helpful if there was one page explaining all available substitutions, plus their context dependence.
This would also encourage cross-referencing, as it would make more sense to link  from the “MSBuild Conditions” article to such a reference article instead of to that one sentence in the “MSBuild properties” article.

**To give an example for point 2**:
```xml
    <EmbeddedResource Update="**\*.resx" Condition="'%(FileName)' == 'MySpecialFileName'">
      <foo>worked</foo>
    </EmbeddedResource>
```
…yields
> The reference to the built-in metadata "FileName" at position 1 is not allowed in this condition "'%(FileName)' == 'MySpecialFileName'".

On the other hand, using this condition string inside e.g. `<foo>` or any other `MetadataItem` works perfectly fine.

**Summary**
An explanation concerning what substitutions are allowed under which circumstances (and even what syntactical constructs are supported) is missing. However, precise specs are important for something that aims to be reference documentation. Speaking from my own experience, knowledge about this mostly comes from finding other people's code snippets and observing what works. This is inefficient, and bears the risk of spreading incorrect information. I propose a central location for explaining all of the available substitution mechanisms.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@lukasjuhrich -- Lukas, thank you for your detailed feedback.

@ghogen -- Gordon, please look into this issue.

**Comment by lukasjuhrich** [comment]
Bump because I think this is valuable feedback and not just some obscure bug nobody cares about. :-)

**Comment by lukasjuhrich** [comment]
Reopen. If the MSBuild articles aspire to be reference documentation, this needs to be clarified.

**Comment by ghogen** [comment]
I agree this content is needed. I've added the "exempt" to keep the bot from automatically closing it.

**Comment by ghogen** [comment]
@lukasjuhrich I've opened an internal PR for this.

**Comment by ghogen** [comment]
This is fixed and should show up on the live site today.
