### ISSUE TITLE
Autorecover folder outdated for 2019 and a small typo for <=2017

### ISSUE THREAD

**Issue by pbarranis** [MicrosoftDocs/visualstudio-docs#5590]
[Enter feedback here]
This appears to be outdated information for 2017 and prior.  In 2019 I'm finding the Autorecover documents stored at %localappdata%\Microsoft\VisualStudio\BackupFiles, as per the 2nd-most-upvoted answer provided at: https://stackoverflow.com/a/59277526/358578

Also, even for 2017 and prior, I believe there's a typo.  Instead of '%USERPROFILE%\Documents\Visual Studio\[version]\Backup Files\[projectname]', it should say '%USERPROFILE%\Documents\Visual Studio [version]\Backup Files\[projectname]' (note the missing slash).  This is as-per the most-upvoted answer in the link above and corresponds to what I see on my machine too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5090ac82-e40b-257a-cea4-d6ea75d5964c
* Version Independent ID: 88e71b46-e31f-1a7b-7b76-41cfc3c57ed3
* Content: [AutoRecover, Environment, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/autorecover-environment-options-dialog-box?view=vs-2019)
* Content Source: [docs/ide/reference/autorecover-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/autorecover-environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@pbarranis Thanks for your feedback; we'll check in to this and report back soon.

**Comment by TerryGLee** [comment]
@pbarranis We've researched this and you are right; the page required an update, which is published now. Thank you for helping us improve the documentation!
