### ISSUE TITLE
Release notes for VS 16.5 have 404 error

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#5592]
---
**Issue moved from MicrosoftDocs/feedback#2884**
- Please respond to @ike2016.

---

_From @ike2016 on Monday, June 22, 2020 11:04:24 AM_

**Describe the bug**
Missing page. Noticed [here](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release)

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.5

**Expected behavior**
Proper release notes.

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#2884**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Monday, June 22, 2020 11:04:25 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by JacquelineWiddis** [comment]
This problem has been resolved.  Thank you for helping us constantly improve our documentation and release processes.  We appreciate it!  #please-close
