### ISSUE TITLE
Please link VS docs to VS Code docs

### ISSUE THREAD

**Issue by jamescadd** [MicrosoftDocs/visualstudio-docs#5596]
The title of this doc is exactly what I'm looking for, but I need the VS Code version.  Bing brought me to the VS proper version, so it would be great if the docs could have a selector for VS Code (could be similar to selecting .NET Framework API versions).  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95bc6d7e-2b58-4755-4411-c5f369011a6c
* Version Independent ID: d5710161-bc97-6d33-6c6b-77fc9cfe9c62
* Content: [Troubleshoot breakpoints in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/troubleshooting-breakpoints?view=vs-2019)
* Content Source: [docs/debugger/troubleshooting-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/troubleshooting-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@jamescadd This is a docs platform issue. Currently, VS Code docs have their own build/rendering system, so the two can't be easily integrated. It might be addressed in the future through other channels/discussions.
