### ISSUE TITLE
Northwind Transact-SQL script - link fails

### ISSUE THREAD

**Issue by SolidRockProgrammer** [MicrosoftDocs/visualstudio-docs#5598]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfe690a0-e17d-4a9c-a107-7189e29fe815
* Version Independent ID: 87bbbd28-a5a0-76dd-468d-52c4a930f8cd
* Content: [Walkthrough: Creating an N-Tier Data Application - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/walkthrough-creating-an-n-tier-data-application?view=vs-2019)
* Content Source: [docs/data-tools/walkthrough-creating-an-n-tier-data-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/walkthrough-creating-an-n-tier-data-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@SolidRockProgrammer -- thank you for your feedback.  For me, that link opens this SQL source file:
- https://raw.githubusercontent.com/MicrosoftDocs/visualstudio-docs/master/docs/data-tools/samples/northwind.sql

Please clarify your issue.

**Comment by ghogen** [comment]
@SolidRockProgrammer @WilliamAntonRohm 
You should not have to be a member of any repo to access that script.
Perhaps this was a transient issue or you have some client-specific issue that's preventing the file from being dowloaded, perhaps a browser or firewall security setting.

In the meantime, here is a zip file that contains the SQL script:
[Northwind.zip](https://github.com/MicrosoftDocs/visualstudio-docs/files/4933424/Northwind.zip)

**Comment by WilliamAntonRohm** [comment]
@ghogen -- thank you for your assistance!

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
