### ISSUE TITLE
Add documentation for MSBuild target framework functions

### ISSUE THREAD

**Issue by sfoslund** [MicrosoftDocs/visualstudio-docs#5599]
Intrinsic functions for handling target framework and target platform values were added in microsoft/msbuild#5429 and microsoft/msbuild#5234

**Comment by sfoslund** [comment]
Fixed with https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6866

**Comment by dsplaisted** [comment]
Here's the link to the docs for this: https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019#msbuild-targetframework-and-targetplatform-functions
