### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by microkost** [MicrosoftDocs/visualstudio-docs#560]
How to pass parameter $(Version) as value from msbuild command line? Could you extend documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e908f0-23c4-07b2-f1f7-371a96a0b45d
* Version Independent ID: ec52aadf-b1e2-355e-60ba-21d29dc43ea1
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-element-msbuild)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/property-element-msbuild.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
It's a good idea to do this, but the work is currently out of scope.
