### ISSUE TITLE
where are my functions???

### ISSUE THREAD

**Issue by jmaschle** [MicrosoftDocs/visualstudio-docs#5604]
Why are stored _functions_ not available in the dataset designer?  I see stored procedures in my packages, but no functions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e58075dd-0907-d5e2-ef0e-46bd705c6412
* Version Independent ID: a96641c0-88ce-0850-55d6-46219813183d
* Content: [Create and configure datasets - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-and-configure-datasets-in-visual-studio?view=vs-2019)
* Content Source: [docs/data-tools/create-and-configure-datasets-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-and-configure-datasets-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@jmaschle -- thank you for your question.  You have probably already seen step 4 in this topic:
- [Create a new dataset by using the Data Source Configuration Wizard](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-and-configure-datasets-in-visual-studio?view=vs-2019#create-a-new-dataset-by-using-the-data-source-configuration-wizard)

Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are also welcome to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
