### ISSUE TITLE
ViewBox is available in UWP

### ISSUE THREAD

**Issue by michalkania** [MicrosoftDocs/visualstudio-docs#5606]
ViewBox is available in UWP though the page states it's only available for WPF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdaf3d5-a7bc-fb9f-9750-9aee54546670
* Version Independent ID: d0e43ac2-9a43-a803-93bd-720a4ebaf664
* Content: [Organize objects into layout containers in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/organize-objects-into-layout-containers-in-xaml-designer?view=vs-2019)
* Content Source: [docs/xaml-tools/organize-objects-into-layout-containers-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/organize-objects-into-layout-containers-in-xaml-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@LyalinDotCom FYI on this.

**Comment by LyalinDotCom** [comment]
Yep seems true. What controls are available is a platform decision so at some point they must have added it:

https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Viewbox?view=winrt-19041

So we can accept the change

**Comment by TerryGLee** [comment]
@michalkania You're right; we've made the update that you recommended. Thanks for helping us improve the documentation! (@LyalinDotCom thanks to you, too.)
