### ISSUE TITLE
Live Unit Testing and code generation

### ISSUE THREAD

**Issue by jbockle** [MicrosoftDocs/visualstudio-docs#5607]
I'm using live unit testing with Microsoft Orleans, which has a Microsoft.Orleans.CodeGenerator.MSBuild package that generates code at build time.  This doesn't appear to be working with LUT, is there something I need to configure so that LUT runs the package targets during build?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d963b3f7-abc8-a9e7-9ac7-2a5c7ad53c28
* Version Independent ID: 2866e780-84b2-a833-24fb-8a4354a9c0f4
* Content: [Live Unit Testing FAQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq?view=vs-2019)
* Content Source: [docs/test/live-unit-testing-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/live-unit-testing-faq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@jbockle -- thank you for your question.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
