### ISSUE TITLE
The term version is used in the context of a version and a release

### ISSUE THREAD

**Issue by karlamrock** [MicrosoftDocs/visualstudio-docs#5608]
Hi,

When I read the document, I cant' figure out if you're saying that, I can install multiple versions of VS, or that I can install multiple version and multiple releases of that version.

Please update the document to call out installing multiple releases of a version of VS.

Releases is the term Microsoft uses for an update to a VS Version.

**Version examples**
Visual Studio Enterprise 2019
Visual Studio Professional 2019
Visual Studio Community 2019
Visual Studio Enterprise 2017
Visual Studio Professional 2017
Visual Studio Community 2017

**Release examples**
Visual Studio 2019 Enterprise 16.5.4
Visual Studio 2019 Enterprise 16.5.5
Visual Studio 2019 Enterprise 16.6.0
Visual Studio 2019 Enterprise 16.6.4

Thank you for updating the document so that it explicitly calls out SxS version as well as SxS releases.

Thank you,

Karl Shifflett

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 788a1b72-8bf6-2f87-e317-a176bfced823
* Version Independent ID: 9ba41f95-d832-0668-f976-29f93f72320c
* Content: [Install Visual Studio versions side-by-side - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio-versions-side-by-side?view=vs-2019)
* Content Source: [docs/install/install-visual-studio-versions-side-by-side.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-visual-studio-versions-side-by-side.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
Hi @karlamrock, thanks for your feedback. We recently updated the page to include more information about downloading minor versions side-by-side. It should go live this afternoon.
