### ISSUE TITLE
Unable to identify which workloads correspond to older Visual Studio features

### ISSUE THREAD

**Issue by PGCCajb** [MicrosoftDocs/visualstudio-docs#5609]
I work in a moderately-large organization, which does automated software deployment over the network.

I inherited from one of my predecessors a network install source for Visual Studio 2012 which is less than 1.5GB in size. Documentation of how this was created, what choices were made in creating it, or anything along those lines, was not left behind along with this.

I am attempting to create a network install source for Visual Studio 2019, so that we can deploy that instead of 2012. However, the base "all workloads and components" install source ("layout") for VS2019 is nearly 34GB.

A size increase by a factor greater than 20 for an analogous feature set, over a time difference of less than ten years, does not seem remotely plausible. I therefore conclude that the feature set of this type of install is broader than the one in the existing VS2012 install source. I want to reduce the selected workload (etc.) set to something which will provide a feature set comparable to what is in the existing VS2012 install source, and will presumably be much closer to the VS2012 install source's size.

The only thing I've thus far managed to find in the VS2012 install source which looks like it might be a listing of selected or deselected features is a file named AdminDeployment.xml, at the root of the install source. It contains a list of 38 SelectableItemCustomization values, all of them with 'Selected="Yes"', and many of them labeled "hidden"; I don't see anything in it listed as 'Selected="No"' or otherwise disabled. It seems likely, although not certain, that this may be the full set of non-mandatory features for a VS2012 install.

I have been unable to find anything resembling documentation of what VS2019 workload or component IDs correspond to even the feature set of a "complete" or "default" install of earlier versions of Visual Studio, never mind a mapping between current workload/etc. IDs and previous version feature choices. The lists of workload/etc. IDs which I have found do not seem to map in anything like a recognizable way to the apparent features listed in AdminDeployment.xml in the VS2012 install source.

The obvious place to look for such documentation would be in the official Visual Studio install documentation, and particularly the pages related to workload and component IDs, which is where I got to this place from. However, as far as I can tell, there is no such information there.

I have attempted to ask questions about this on the Visual Studio developer community, in the principle that presumably others will have encountered this problem (even though I haven't been able to find mention of such in online searches) and be able to advise me. However, I can't find a way to post there except via "report a problem" or "suggest a feature"; the former requires installing Visual Studio, which I don't want to do since I don't intend to use it myself, and the latter would not be appropriate for this type of question.

Please provide a listing of features for earlier Visual Studio versions, the labels by which those features can be selected in install configurations, the locations within a configured install source where the set of selected features for that installation can be found, and the workload / component / etc. IDs within current Visual Studio versions which are most directly analogous to those features. Please make this listing findable, if not directly in the existing Visual Studio workload / component ID listing pages, then preferably (though not necessarily only) via links directly from those pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f80d9f-168b-e3cb-6499-e03a44206826
* Version Independent ID: 4b235b0d-1436-0a36-ef55-f76ba8d95bd1
* Content: [Visual Studio workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019)
* Content Source: [docs/install/workload-and-component-ids.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-and-component-ids.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@PGCCajb -- thank you for your thorough feedback.

@ornellaalt -- please look into this issue.

**Comment by ornellaalt** [comment]
@tobyhu87, can you please check out this issue? Thank you!

**Comment by Rockies98** [comment]
My apologies at taking so long to get back to you on this. As the Visual Studio product has evolved considerably since the 2012 version, the VS 2019 product is quite different. I suggest you visit https://docs.microsoft.com/en-us/visualstudio/install/workload-and-component-ids?view=vs-2019 to gain info on the Workloads and Components that are offered in VS2019. From there you can work with your development teams to determine which Workloads and Components to include or exclude as needed.

Thanks,
Allen Denver
Visual Studio

**Comment by AllenD-MSFT** [comment]
Additionally, let me apologize for my post above which was posted using my personal GitHub account. That should have come from this MSFT account.

**Comment by ornellaalt** [comment]
Closing out this issue as it doesn't require a documentation change.
