### ISSUE TITLE
Where are the reported problems listed?

### ISSUE THREAD

**Issue by TobiasKnauss** [MicrosoftDocs/visualstudio-docs#561]
I just reported a problem from within VS2015, but without signin in in my VS. Where did the report go? Where does it go when being signed in?
I added my email address, but I did not receive a copy of my report. I suggest that you send out copies, including a link where to find them online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Service: unspecified

**Comment by gewarren** [comment]
@TerryGLee could you ask one of your contacts about this?

**Comment by TerryGLee** [comment]
@TobiasKnauss Have you had an opportunity to check out the [Developer Community for Visual Studio 2015](https://developercommunity.visualstudio.com/search.html?f=&type=question+OR+problem+OR+problem&type=question+OR+problem+OR+problem&c=&redirect=search%2Fsearch&sort=relevance&q=Visual+Studio+2015) page to see if the problem you reported is listed there?

**Comment by TobiasKnauss** [comment]
> Have you had an opportunity to check out the Developer Community for Visual Studio 2015 page to see if the problem you reported is listed there?

I just checked out every issue of the last 10 days in various searches, it's not listed.
Also, how could it be listed there? This website uses GitHub accounts, and my VS2015 does not know my GitHub login.

**Comment by cparmarmsft** [comment]
@TobiasKnauss the feedback  you report through VS 2015 does not go to developer community. It was an old system that did not expose any feedback on a community forum. Starting VS 2017 all feedback you submit is available on Developer Community portal as Terry suggested.

**Comment by IrishChieftain** [comment]
This is a total farce. The Connect website is no more. It's replacement "Collaboration" is an empty shell with no functionality. Where is the official repository for reported, fixed and outstanding bugs for the entire developer stack right now? Also, why was I forced to use my GitHub account to even post a comment here? This reeks of being outsources and I see zero ownership by Microsoft.
