### ISSUE TITLE
Incorrect event handler when the VSTO Add-in is unloaded

### ISSUE THREAD

**Issue by qiuyangnie** [MicrosoftDocs/visualstudio-docs#5613]
In the second row and second column of **ThisAddIn members to use for other tasks** section, the `ThisAddIn_Startup` seems incorrect, which should be replaced with `ThisAddIn_Shutdown`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2db2d7da-16be-b472-b1a3-c1cff6460226
* Version Independent ID: fb24e313-a9cf-58e1-b152-4948a5fd6ca1
* Content: [Program VSTO Add-ins - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/programming-vsto-add-ins?view=vs-2019)
* Content Source: [docs/vsto/programming-vsto-add-ins.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/programming-vsto-add-ins.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
