### ISSUE TITLE
Incorrect example in the page

### ISSUE THREAD

**Issue by kunal-chowdhury** [MicrosoftDocs/visualstudio-docs#5614]
The doc topic is "How to: Programmatically search within a specific folder" but the content and the example describes "How to search a mail having a specific subject". So, the content is misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53cb97d-2c1f-8b19-1496-d91cf408e6d2
* Version Independent ID: c4f16638-df03-4440-4dca-763dbdc3fdbe
* Content: [How to: Programmatically search within a specific folder - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-search-within-a-specific-folder?view=vs-2019)
* Content Source: [docs/vsto/how-to-programmatically-search-within-a-specific-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-search-within-a-specific-folder.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
Thanks for the feedback.  I think the article does have a sample that shows how to search in the inbox which is an Outlook.Folder.
