### ISSUE TITLE
May want to clarify something...

### ISSUE THREAD

**Issue by vistalogic** [MicrosoftDocs/visualstudio-docs#5616]
I worked through this and was getting network errors when the WebFrontEnd tried to communicate with the MyWebAPI project. The resulting errors were not helpful and sent me down a complicated road to try to resolve using Docker network settings, etc.

It turns out, the "WebFrontEnd" project was selected as the startup project instead of "docker-compose" (I think I set it to test the project before adding the back end project). Looking back at the screen shots I now see that the docker-compose project is bold, but you may want to add some clarifying language in the documentation so people can avoid this mistake.  Hopefully this will help save people some time and frustration.

**Comment by WilliamAntonRohm** [comment]
@vistalogic -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please let us know which docs.microsoft.com article you’re referencing, or provide more context around your general task.

**Comment by vistalogic** [comment]
I was completing the steps outlined in https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2019

I am sure I did something that was not part of the instructions, but in general feel like it isn’t obvious that the startup project should be docker-compose (especially for developers who are very used to setting the web application as the startup project).  I just think it would be worthwhile to add that to the tutorial.

I was working on this tutorial because I wasn’t able to get the eShopOnContainers solution to work (for the same reason)
https://docs.microsoft.com/en-us/dotnet/architecture/microservices/
So you may want to add some clarification in that article as well. It might be good to include how you would change the docker-compose project to launch a different project on startup (since there are multiple projects you may want to start up).

Thanks for following up!
Dan

**Comment by WilliamAntonRohm** [comment]
@vistalogic -- Dan, thank you for clarifying.

@ghogen -- Gordon, please look into this issue.

cc @nishanil for awareness

**Comment by ghogen** [comment]
@vistalogic Thanks for the feedback. I will update the article appropriately.
