### ISSUE TITLE
Switch Sample is not a valid value for the START switch.

### ISSUE THREAD

**Issue by maidamai0** [MicrosoftDocs/visualstudio-docs#5618]
Test command error:
```PowerShell
❯ VSPerfCmd.exe /Start:Sample /Output:TestApp.exe.vsp
Error VSP1393: Switch Sample is not a valid value for the START switch. Aborting.
❯ which vsperfcmd.exe
/c/Program Files (x86)/Microsoft Visual Studio/2017/Professional/Team Tools/Performance Tools/vsperfcmd.exe
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0d83d03-a6c7-9f13-c75d-b5abfe3286e8
* Version Independent ID: 8ac09799-df92-435a-afc6-9cc6f64ff760
* Content: [Start - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/start?view=vs-2017)
* Content Source: [docs/profiling/start.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/start.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@maidamai0  In VS 2017, this option should work as documented. Thanks for your feedback. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
Closing for now as it does not appear to be a doc issue.
