### ISSUE TITLE
Is there source code can download for the example in this page?

### ISSUE THREAD

**Issue by Yang09701194** [MicrosoftDocs/visualstudio-docs#5619]
Is there source code can download for the example in this page? or just read the article with only part of source code cannot practice by hand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66fe9e04-c830-3350-3ff9-9a3ecb7cfe5e
* Version Independent ID: e1063d2e-aace-86b2-a4b4-6378c45c55a0
* Content: [Unit testing fundamentals - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019)
* Content Source: [docs/test/unit-test-basics.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/unit-test-basics.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Yang09701194 -- thank you for your question.  This article is a conceptual overview with example code snippets, not a full working example.  Please see this section:
- [The MyBank solution example](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019#the-mybank-solution-example)

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
