### ISSUE TITLE
What happens if the download is interrupted?

### ISSUE THREAD

**Issue by TobiasKnauss** [MicrosoftDocs/visualstudio-docs#562]
What happens, if I abort the download? Will it restart at the beginning at next execution or does it continue at the component where it was interrupted? Will existing components be downloaded again if I execute it with different set of workloads?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/install/install-vs-inconsistent-quality-network.md)
* Service: unspecified

**Comment by gewarren** [comment]
@TerryGLee perhaps you can add the info to the topic if you can find answers.

**Comment by srikanthbollojula** [comment]
it will continue from where it got failed.

**Comment by CamelCaseMaster** [comment]
I already made a copy (--layout ~45GB) & whenever some time passes I re-execute the same command:
vs_community.exe --layout c:\notAnIsoThisIsAwesome --lang en-US
It verifies the packages then adds new ones which is what i want to keep it fresh in case I need it but is there a way to delete old versions of some packages already downloaded? or it does it automatically?

**Comment by tedvz** [comment]
Re: cleaning up older packages, please see:

https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio#how-to-remove-older-versions-from-a-layout

and the --clean command.
