### ISSUE TITLE
We need some basic information on the ActionPanes collection.

### ISSUE THREAD

**Issue by CLIRResearch** [MicrosoftDocs/visualstudio-docs#5627]
This page implies that a ThisWorkbook class must be added to a VSTO object.  The BaseWorkbook class does not contain the ActionPanes collection.  What is the base class for ThisWorkbook that actually contains the ActionPanes collection?  How would I add a ThisWorkbook class to a VSTO for Excel in Visual Studio 2019?  

Also, there is no such thing as Globals.ThisWorkbook.  There is only a Globals.ThisAddIn and this does not contain a ActionPanes collection.

Where is the documentation for the ThisWorkbook class?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3433475e-7319-0e37-22a3-bf49eb58e86f
* Version Independent ID: 1a85e45e-204b-46d1-6488-e3f801d83fc0
* Content: [Add Actions pane to Word documents or Excel workbooks - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-add-an-actions-pane-to-word-documents-or-excel-workbooks?view=vs-2019)
* Content Source: [docs/vsto/how-to-add-an-actions-pane-to-word-documents-or-excel-workbooks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-add-an-actions-pane-to-word-documents-or-excel-workbooks.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@CLIRResearch -- thank you for your feedback.  Please consider these options:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@John-Hart -- please look into this issue.

**Comment by yaqiyang** [comment]
This walkthrough only applies to document-level projects for Excel and Word which always have ThisWorkbook  or ThisDocument as the base add-in object.  See
![Annotation 2020-08-06 154259](https://user-images.githubusercontent.com/14302929/89589908-94b6ea00-d7fb-11ea-9330-43cd89a791c1.png)
It is not a problem of the documentation. You need to create a "Excel VSTO Workbook" or "Word VSTO Document" project to use this walkthrough.
