### ISSUE TITLE
What is the difference between an AddIn and a Document?

### ISSUE THREAD

**Issue by CLIRResearch** [MicrosoftDocs/visualstudio-docs#5628]
What is the difference between an AddIn and a Document?

Can a Document be used from an AddIn?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7a1da2-e11d-a8a6-f5df-c3db41df72ba
* Version Independent ID: f3a1171e-c739-185a-a7e9-f28f5b9881b1
* Content: [Create VSTO Add-ins for Office by using Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/create-vsto-add-ins-for-office-by-using-visual-studio?view=vs-2019)
* Content Source: [docs/vsto/create-vsto-add-ins-for-office-by-using-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/create-vsto-add-ins-for-office-by-using-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
The simple answer is: 

Document-level customizations are associated with a specific document.

VSTO Add-ins are associated with the application itself.

please see https://docs.microsoft.com/en-us/visualstudio/vsto/office-project-templates-overview and https://docs.microsoft.com/en-us/visualstudio/vsto/office-solutions-development-overview-vsto for more information
