### ISSUE TITLE
Rule CA1822 is missing api_surface configuration section

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#5629]
The doc for rule CA1822 is missing the configurability section regarding the api_surface user option. See doc for https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1000?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73190016-ddef-0e31-ffb2-d72d551e0d0b
* Version Independent ID: 44822112-d0c7-3f59-75c0-3e81f1ee57d7
* Content: [CA1822: Mark members as static - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822?view=vs-2019)
* Content Source: [docs/code-quality/ca1822.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1822.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
This has been fixed
https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1822?view=vs-2019#configurability
