### ISSUE TITLE
Example in #transform-modifiers in wrong location

### ISSUE THREAD

**Issue by Dykam** [MicrosoftDocs/visualstudio-docs#563]
The example at the end of #transform-modifiers seems to belong to the first sample, not the second.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e902b152-739e-3492-7b49-b144925a74a1
* Version Independent ID: 90a940de-1386-58ff-04b3-d53364cabbda
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-transforms#transform-modifiers)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/msbuild-transforms.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Working on fix

**Comment by Mikejo5000** [comment]
Fix is in the master branch. It should go live tomorrow.
