### ISSUE TITLE
Custom Task Pane is not visible.  I followed this example exactly.

### ISSUE THREAD

**Issue by CLIRResearch** [MicrosoftDocs/visualstudio-docs#5630]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f3eae76-f780-15a5-57ee-eba13d5ee20f
* Version Independent ID: b6b22852-a90c-3af7-3c71-d78206a2bbc4
* Content: [Synchronize custom task pane with Ribbon button - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-synchronizing-a-custom-task-pane-with-a-ribbon-button?redirectedfrom=MSDN&view=vs-2019)
* Content Source: [docs/vsto/walkthrough-synchronizing-a-custom-task-pane-with-a-ribbon-button.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-synchronizing-a-custom-task-pane-with-a-ribbon-button.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
It should be visible when you hit the toggle button and this event code is run:

private void toggleButton1_Click(object sender, RibbonControlEventArgs e)
{
    Globals.ThisAddIn.TaskPane.Visible = ((RibbonToggleButton)sender).Checked;
}

If it's not try setting a breakpoint on this line and inspect the visible property

**Comment by CLIRResearch** [comment]
I am using the Microsoft Documentation at

 https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-add-a-custom-task-pane-to-an-application?view=vs-2019.  

- The task pane manager is never visible.  It is instantiated.   

- The ribbon bar works without any issue.

- If I programmatically set the visibility of the task pane to true, it is still not visible.

- I can programmatically exchange data and commands between the ribbon bar code and the task pane.  I cannot, however make the task pane visible.

I have seen some examples where developers are instantiating instance of the custom task pane when workbooks are activated (and not in the ThisAddIn_Startup event handler.  I am starting a new VSTO AddIn to research a number of questions.

1. What should the parent window of a task pane be?  Since, it is an AddIn, should the parent be the AddIn class or should it be a Workbook, Ribbon Bar, or Worksheet class?  

2.  How would I assign the parent window (hWnd) of a Custom Task Pane?  The CustomTaskPane interface has a read-only Window object.  Do I need to implement a CustomTaskPane class and add a constructor that I can pass a parent window to?

3. Typically, a reference is made to "Excel Window".  But, technically AddIn, Worksheet, Workbook, User Control, etc.  are all derived from a Window base class.  Is there a specific "Excel Window" that should be used to instantiate a Custom Task Pane?

4.  Some are creating a new instance of the task pane for each workbook.  If this is the case I need to create a class derived from workbook.  I am doing some research on how to implement a class derived from WorkBookbase to handle the events.  The documentation at:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.tools.excel.workbookbase.sheetchange?view=vsto-2017

does not indicate where the example code is implemented.  Is this in the ThisAddIn.cs?  







2.

**Comment by John-Hart** [comment]
Hi @CLIRResearch,

I believe this is a similar issue to this one (#5659), that you also opened that we're helping you with. So I'm going to go ahead and close this one issue. If I miss-understood just let me know. 

thanks
John
