### ISSUE TITLE
Even your Twitter account says, you're crazy :)

### ISSUE THREAD

**Issue by daniel-scholten** [MicrosoftDocs/visualstudio-docs#5632]
"When you develop with Visual Studio, you read from and write to a lot of files, which increases the disk I/O activity. It's best to choose your fastest drive to handle the load." -- Says it all about you idiots. Took me a while and a little bit of Python scripting to remove the mess, the installation did on my system drive. If I had been on a laptop with one limited c drive, you crazy people would have killed it. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f065a76a-2046-ebfd-2aa2-ebb0afbc4110
* Version Independent ID: f3501eb1-bfa1-1c2e-9e05-bc0f1fa8971d
* Content: [Select installation locations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/change-installation-locations?view=vs-2019)
* Content Source: [docs/install/change-installation-locations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/change-installation-locations.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@daniel-scholten -- Daniel, thank you for your feedback.
