### ISSUE TITLE
Update / Add delete steps to include components folders

### ISSUE THREAD

**Issue by inikityuk** [MicrosoftDocs/visualstudio-docs#5635]
Hi guys,
Was going through complete uninstall/install process of all related things to Xamarin recently as a last resort and eventually figured out that deletion of "components" folder does the job. Would be nice to update documentation to include the link to https://docs.microsoft.com/en-us/xamarin/cross-platform/troubleshooting/questions/component-storage page or include folder in one of the scripts here: https://docs.microsoft.com/en-us/xamarin/get-started/installation/uninstalling-xamarin or here:  https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Uninstall Visual Studio for Mac - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by inikityuk** [comment]
Still relevant

**Comment by WilliamAntonRohm** [comment]
@inikityuk -- Igor, thank you for your followup.

@heiligerdankgesang -- Dominic, please look into this issue.

**Comment by j-martens** [comment]
@anandmeg - something to add to that doc?
