### ISSUE TITLE
Missing details on how to add link instead of file when uploading extension

### ISSUE THREAD

**Issue by stefanov-stefan** [MicrosoftDocs/visualstudio-docs#5639]
Hi,

when uploading extension from the marketplace, there was an option to publish a link to an extension instead of the extension itself, as the docs state it: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/walkthrough-publishing-a-visual-studio-extension.md - see step 7

However, on the portal there is no longer such option. Can we elaborate on the docs how this can be achieved?

**Comment by WilliamAntonRohm** [comment]
@stefanov-stefan -- Stefan, thank you for your question.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@acangialosi -- Anthony, please look into this issue.

**Comment by acangialosi** [comment]
Tried to move to leslierichardson95 but didn't have permission to add new assignee.
