### ISSUE TITLE
How do I even get to the Utilization View Screen?

### ISSUE THREAD

**Issue by nathvi** [MicrosoftDocs/visualstudio-docs#564]
I'm not sure the steps I need to even get to this Utilization View screen... I have the Concurrency Visualizer for 2017 installed already...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2463d9c5-9ef0-37c2-b667-e809bf8cb9a9
* Version Independent ID: 9ad74e00-02b1-8e05-e14a-12db6f5da26a
* [Content](https://docs.microsoft.com/en-us/visualstudio/profiling/utilization-view)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/profiling/utilization-view.md)
* Service: unspecified

**Comment by nathvi** [comment]
I figured it out. You have to click on the "Analyze" menu and then on the "Concurrency Visualizer".
This would have been really useful information to know for people not familiar with how previous versions of the product worked. Please be sure to add it to the documentation.

**Comment by nathvi** [comment]
Console.WriteLine("Sweet Baby Jesus!");

**Comment by Mikejo5000** [comment]
Fix published
