### ISSUE TITLE
Clarify Azure roles able to purchase VS subscriptions

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/visualstudio-docs#5640]
This doc says: "You'll need to be an owner or contributor for an Azure subscription that was created for your EA" [to purchase a VS subscription]

But in https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-overview#who-can-buy-visual-studio-cloud-subscriptions it says: "Anyone with owner, service admin or co-admin access to the Azure subscription can purchase cloud subscriptions"

These statements are contradictory. The roles required to purchase VS subscriptions (depending on Azure subscription type if necessary) need to be clarified in both docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf290c37-d7fa-9d10-b8ef-865647e58a70
* Version Independent ID: 1334b162-8560-5e0a-c874-9439b697dd96
* Content: [Billing FAQ for Visual Studio Enterprise and Visual Studio Professional cloud subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-billing-faq)
* Content Source: [subscriptions/vscloud-billing-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-billing-faq.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
cc @evanwindom for awareness

**Comment by evanwindom** [comment]
@jtuliani - Hi Jonathan.  Thanks for bringing the issue to our attention.  I'm investigating this, and will post a clarification to both articles once I have a definitive answer.  Thanks again for highlighting the error.  --Evan

**Comment by evanwindom** [comment]
An update has been posted to both articles addressed in this issue.

**Comment by evanwindom** [comment]
#please-close
