### ISSUE TITLE
ProjectReference documentation appears to be missing item metadata

### ISSUE THREAD

**Issue by clisc** [MicrosoftDocs/visualstudio-docs#5642]
There is definitely some missing item metadata like `<CopyLocal>` and `<CopyToOutputDirectory>`, for example.  I imagine a lot more is missing.  Can someone please add all the item metadata for the ProjectReference item?  Thanks!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97e663f7-3bac-61af-28bb-f0e471dcdca6
* Version Independent ID: 97985f56-e0ac-a03d-f651-b86cc2b85804
* Content: [Common MSBuild Project Items - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2019)
* Content Source: [docs/msbuild/common-msbuild-project-items.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-items.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@clisc -- thank you for  your feedback.  Please consider these resources:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@ghogen -- please look into this issue.

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, it looks like `CopyToOutputDirectory` is currently documented, but `CopyLocal` is not.
