### ISSUE TITLE
Is there any way to create template on VS for mac 8?

### ISSUE THREAD

**Issue by naughtyGitCat** [MicrosoftDocs/visualstudio-docs#5647]
[Enter feedback here]

this page only works for vs, not vs for mac 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e16e6e-e5d1-964b-f220-cbb2c7e4b5e2
* Version Independent ID: 94f82ff9-c61f-31d1-df37-f5e4320daf1c
* Content: [Create project templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-project-templates?view=vs-2019)
* Content Source: [docs/ide/how-to-create-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-create-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@naughtyGitCat -- thank you for your question.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by TerryGLee** [comment]
@naughtyGitCat Unfortunately, I don't have an answer for you on this; the page where you registered your question is specific to Windows. However, there is **[Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/?view=vsmac-2019)** documentation set that you might want to visit for general info on that product.

Further info: While I did not see a topic there that addresses custom templates specifically, you might want to take a look at both the **[Projects and Solutions in Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/projects-and-solutions?view=vsmac-2019)** page and the **[Visual Studio 2019 for Mac Release Notes](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2019-mac-relnotes)** (which mentions a few pre-packaged templates) for further details.

As well, you might want to peruse previously submitted Visual Studio for Mac product-related issues on the **[Developer Community](https://developercommunity.visualstudio.com/spaces/41/index.html)** page; if there is an issue logged there that matches your inquiry, you can upvote it to place it higher in the queue to be addressed by the engineering team. You can also suggest a new feature for the product (such as the ability to create a template, should it be missing) from this page, too.
