### ISSUE TITLE
How to Remove AKS Support from Visual Studio Docker Compose Project

### ISSUE THREAD

**Issue by vnwonah** [MicrosoftDocs/visualstudio-docs#5648]
The Documentation Below Tells you how to Add Helm/Kubernetes Support. When you follow it and try to run it prompts for an AKS resource in Auzre. How do you revert to just debugging locally with docker/docker-compose? simply removing the generated files don't work.

Would be great to include how to revert in the Documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Kubernetes tools tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-kubernetes-tools?view=vs-2019)
* Content Source: [docs/containers/tutorial-kubernetes-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-kubernetes-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by vnwonah** [comment]
For anyone hitting this issue, I solved by going into Properties/launchSettings.json and removed the Azure Dev Spaces Section

**Comment by WilliamAntonRohm** [comment]
@vnwonah -- Vincent, thank you for your question and the answer.

@ghogen -- Gordon, please look into this issue.
