### ISSUE TITLE
bug Report outdated

### ISSUE THREAD

**Issue by trivalik** [MicrosoftDocs/visualstudio-docs#5649]
Since last VS2019 update the bug report feature opens always a browser window.

Aditional bug report:
**Can you please forward to VS2019 team that it is now for me not possible anymore to report bugs because the connection between VS2019 and browser does not work.**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@trivalik -- Trivalik, thank you for your feedback here.  For issues with the Feedback Tool in Visual Studio, please email us at vsfeedback@microsoft.com.

cc @madskristensen for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
