### ISSUE TITLE
How do I specify Assembly Information Options in VS for Mac?

### ISSUE THREAD

**Issue by kiazhi** [MicrosoftDocs/visualstudio-docs#565]
I'm building a .NET Core Class Library for PowerShell Module on Visual Studio for Mac and I cannot find the option to specify AssemblyFileVersionAttribute and AssemblyVersionAttribute before compiling. Is the Assembly Information Option even available in VS for Mac? Or it is just available in VS for Windows?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69679340-d7cb-4a95-b2da-7b09377baaa8
* Version Independent ID: 11469a16-835d-ebb6-2285-4f9d41a7235b
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/managing-solutions-and-project-properties)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/mac/managing-solutions-and-project-properties.md)
* Service: unspecified

**Comment by mrward** [comment]
Visual Studio for Mac does not currently have a page where you can specify the Assembly version or file version.

With a .NET Core console project, Visual Studio 2017 on Windows allows you to set the assembly version and assembly file version by selecting Project menu - ProjectName Properties - Package. This does not exist in Visual Studio for Mac.
