### ISSUE TITLE
Where do I put the new code?

### ISSUE THREAD

**Issue by Mykeala** [MicrosoftDocs/visualstudio-docs#5650]
The directions for all of the steps up until this point are perfectly laid out where you are supposed to write the code that is being given to you. However, with this step I have absolutley little of even half a clue know where I am supposed to write this

public void StartTheQuiz()
{...}
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ebf98f2-d920-def8-7c71-6c236603b33d
* Version Independent ID: f427c6dd-7abe-ae96-0325-e9e9ad579c8d
* Content: [Step 2: Create a random addition problem - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-2-create-a-random-addition-problem?view=vs-2019)
* Content Source: [docs/ide/step-2-create-a-random-addition-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-2-create-a-random-addition-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@Mykeala -- thank you for your question.  You can add that code right after Step 4's integer variable declarations.  All the code in this example is inside the Form1 class.

@ornellaalt -- please look into this issue.

**Comment by Mykeala** [comment]
When I add it after the integer variable declarations Visual Studios throws back error "CS0106 C# The modifier 'public' is not valid for this item" as well as error "CS1061 C# 'Form1' does not contain a definition for and no accessible extension method accepting a first argument of type 'Form1' could be found (are you missing a using directive or an assembly reference?)"

**Comment by WilliamAntonRohm** [comment]
@Mykeala -- thank you for clarifying.  We are investigating this issue.

**Comment by Mykeala** [comment]
The issue was that I deleted the button event from the primary Form1 code. I went into the Form 1 code and added this back at the bottom of the form1 code:
``` 
        private void startButton_Click(object sender, EventArgs e)
        {

        }
```
That solved the CS1061 Error.

After that, I was adding the 
```
     public void StartTheQuiz()
{...}
```
method into the 
```
        private void Form1_Load(object sender, EventArgs e)
        {
            
      
         }
```
method, instead of inside the class:
```
public partial class Form1 : Form
{
}
```
Now my code looks like this and it works:
```
    public partial class Form1 : Form
    {
        Random randomizer = new Random();

        int addend1;
        int addend2;

        public Form1()
        {
            InitializeComponent();
        }

        private void Form1_Load(object sender, EventArgs e)
        {
        }

        public void StartTheQuiz()
        {
            addend1 = randomizer.Next(51);
            addend2 = randomizer.Next(51);
            plusLeftLabel.Text = addend1.ToString();
            plusRightLabel.Text = addend2.ToString();
            sum.Value = 0;
        }

        private void startButton_Click(object sender, EventArgs e)
        {
        }
    }
```

Thank you for taking the time to look into this. Also, thank you to my boyfriend for fixing it for me and writing this answer.

**Comment by WilliamAntonRohm** [comment]
@Mykeala -- I'm glad you've gotten it working, and kudos to your boyfriend as well.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
