### ISSUE TITLE
Page has incorrect context information

### ISSUE THREAD

**Issue by gregsohl** [MicrosoftDocs/visualstudio-docs#5651]
The page content is about auto completing date and time format strings, not date and time literals.
References to 'literals' should be replaced with 'format strings'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 305c7be4-2818-b3d4-ee50-c1d1ac126866
* Version Independent ID: 69c4a204-9b0f-a1e4-0f0b-7a122cf03006
* Content: [DateTime and TimeSpan completion through IntelliSense menu - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/datetime-timespan-completion?view=vs-2019)
* Content Source: [docs/ide/reference/datetime-timespan-completion.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/datetime-timespan-completion.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mikadumont** [comment]
I went ahead and updated the text: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6942
