### ISSUE TITLE
Outdated code

### ISSUE THREAD

**Issue by b-bly** [MicrosoftDocs/visualstudio-docs#5652]
Looks like this tutorial needs to be updated.  TraceWriter is deprecated, and I think HttpRequest should be used instead of HttpRequestMessage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7374155f-a387-9625-bc29-c38fd0c35bae
* Version Independent ID: dc64e04a-b1cf-3334-a5cc-65db6986f72a
* Content: [Tutorial: Azure Functions - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/azure-functions-lab?view=vsmac-2019)
* Content Source: [mac/azure-functions-lab.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/azure-functions-lab.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
This should be assigned to Jordan Matthiesen. I’m no longer of the Visual Studio for Mac team.

**Comment by WilliamAntonRohm** [comment]
@jmatthiesen -- Jordan, please address or close this issue.
