### ISSUE TITLE
Document APIs incompatible with single-file publish and IL3000, IL3001 warnings

### ISSUE THREAD

**Issue by agocke** [MicrosoftDocs/visualstudio-docs#5654]
See https://github.com/dotnet/roslyn-analyzers/pull/3921 for the analyzer warnings

**Comment by agocke** [comment]
+ @lakshanf

**Comment by WilliamAntonRohm** [comment]
@mavasani -- Manish, I'm assigning this issue to you because you approved that PR.  Please re-assign as needed.

**Comment by mavasani** [comment]
https://github.com/dotnet/roslyn-analyzers/blob/master/GuidelinesForNewRules.md has guidelines on adding documentation for new rules (see section `5. Documentation requirements` for details)

I believe @Mikejo5000 could help in documenting/reviewing these.

**Comment by agocke** [comment]
I tried some documentation here, but my PR was autoclosed (#5676) since I need to create it on the private repo, but I don't have permissions to access that repo.

**Comment by mavasani** [comment]
@Mikejo5000 @mikadumont Can you please help @agocke get permissions to https://github.com/MicrosoftDocs/visualstudio-docs-pr? Once you have permissions, you can look at https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6800 as a sample PR adding new rule documentation and links to various tables.

**Comment by Mikejo5000** [comment]
Looks like @agocke has opened a PR on the private repo: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/696, for IL3000. I'll expect to see IL3001 before long.

**Comment by Mikejo5000** [comment]
@agocke Is IL3001 in the works?

**Comment by agocke** [comment]
Yup should have a PR soon

**Comment by Mikejo5000** [comment]
Verified both were doc'ed. Thanks!
