### ISSUE TITLE
You should see a clickable infobar at top of the ruleset editor. - is not shown

### ISSUE THREAD

**Issue by kumarmohe** [MicrosoftDocs/visualstudio-docs#5656]
Hi,

As per the list of instructions under the headline "Convert an existing Ruleset file to EditorConfig file", I don't see the "Clickable Info Bar"  (exact words: "**You should see a clickable infobar at top of the ruleset editor.**") in my "Microsoft Visual Studio Enterprise 2019 Version 16.6.5" 

I know this can be done through command line using "**NuGet package Microsoft.CodeAnalysis.RulesetToEditorconfigConverter.**" (which I did not try yet), I am wondering why the "Clickable Info Bar is not shown to me.

Could you have a look at it please?

![VS-Error](https://user-images.githubusercontent.com/11891841/89082492-2c2fbf00-d35c-11ea-9ae1-a98e4cdb1558.png)

Thanks,
Mohan

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer rule severity and suppression - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by kumarmohe** [comment]
I see this is tagged as Document Bug. isn't a bug in VS 2019? If .editorconfig is the preferred way to go forward, why VS 2019 is not showing the option to convert the Ruleset to editorconfig file?

**Comment by Mikejo5000** [comment]
@kumarmohe I tested this on VS 16.7.1 with a .NET and .NET Core app. In both cases, I do see the info bar for converting the .ruleset to .editorconfig, so this could be a bug. What kind of app/project are you working on?

To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
Closing for now as it appears to be a product or environment issue.

**Comment by kumarmohe** [comment]
@Mikejo5000 Hi Mike, I see that the issue fixed in 16.7.1. But When I logged this issue, 16.6.5 was the latest. However this feature supposedly available in 16.5 itself as per the documentation 

**Starting in Visual Studio 2019 version 16.5, ruleset files are deprecated in favor of the EditorConfig file for analyzer configuration for managed code.**

I see that the issue here is product feature implementation and documentation did not match. I guess the engineering did not implement this feature in 16.3 or it had a bug.

Thanks,
Mohan

**Comment by Mikejo5000** [comment]
Yes, might have been a bug in 16.5

**Comment by JimBobSquarePants** [comment]
Not visible in 16.8.2

**Comment by EluciusFTW** [comment]
I have the same problem now in 17.4.4 the infobar simply does not appear.

**Comment by AlexMatsyuk** [comment]
The same problem.
Is there any other way to directly call this action from IDE?

**Comment by AlexMatsyuk** [comment]
and the problem appears because the ruleset was placed in the root folder but not added as the solution file:
right-click the Solution (or project) -> Add -> Existing item -> choose the ruleset file -> open it again in visual studio from the solution. then it works.
