### ISSUE TITLE
Package version 2.9.10 is out

### ISSUE THREAD

**Issue by billybednar** [MicrosoftDocs/visualstudio-docs#5658]
Update package table row for Visual Studio 2017 version 15.9.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2017#fxcopanalyzers-package-versions)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by msebolt** [comment]
@billybednar Thank you for the feedback.

Compatibility will need to be confirmed, please note [version 3.0.0](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/3.0.0) is the latest stable release.

Assigning this to the author for further review.

**Comment by billybednar** [comment]
From the release notes:
[v2.9.10](https://github.com/dotnet/roslyn-analyzers/releases/tag/v2.9.10) - "Works with VS 2017 15.9 or later."
[v3.0.0](https://github.com/dotnet/roslyn-analyzers/releases/tag/v3.0.0) - "Works with VS 2019 or later."

**Comment by msebolt** [comment]
@billybednar Thank you for the info, the documentation has been updated and is pending review.

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- please review this update in [private PR 6948](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6948).
