### ISSUE TITLE
The "-manual" option has been retired.

### ISSUE THREAD

**Issue by Mazelmat** [MicrosoftDocs/visualstudio-docs#566]
This is reported when using the -manual flag as specified under the "Capture frames interactively." section:
Unrecognized command-line switch "-manual": ignoring
(The "-manual" option has been retired. Use "-frame manual" instead.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3ddd9f0-c302-50af-24a1-d91151e58e12
* Version Independent ID: 99328c33-1fd1-31a6-f2cc-5935ca007853
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/graphics/command-line-capture-tool)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/debugger/graphics/command-line-capture-tool.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@Mazelmat Thanks! I'm updating the doc with the requested info.

**Comment by Mikejo5000** [comment]
fix published
