### ISSUE TITLE
Bad reference

### ISSUE THREAD

**Issue by B-54** [MicrosoftDocs/visualstudio-docs#5660]
The sentence:
"You must specify service locations on the **Services** page to use client application services.", should probably read
"You must specify service locations on the **References** page to use client application services."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4a8054d-d5f5-8fbb-119e-9080fb6c89bd
* Version Independent ID: bb2d8825-e5ed-82a1-1a75-8f436746c976
* Content: [Services Page, Project Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/services-page-project-designer?view=vs-2019)
* Content Source: [docs/ide/reference/services-page-project-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/services-page-project-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by msebolt** [comment]
@B-54  Thank you for the feedback.

Locations are set within the [Client Application Services settings](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/bb384312(v%253dvs.100)).

Perhaps this wording should be `You must specify service locations in the Client Application Services settings.`?

**Comment by B-54** [comment]
Hi Matthew,

 

When I look at the services page, everything including the field “Enable client application services” is grayed out.

In the documentation for the Services page, it says. “You must specify service locations on the Services page to use client application services.”

My point was that I am on the Services page, and that is obviously not the page meant in the quote above.

 

I’m not trying to configure this. But after using VS for ten years I finally decided to read the documentation. And the above did not look right.

 

Best regards

Sigve
