### ISSUE TITLE
Need to document new HelpLink parameter

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/visualstudio-docs#5662]
HelpLink has been added to the Error task: https://github.com/dotnet/msbuild/pull/5488.

This should be documented.

Warning version of this issue is here: https://github.com/MicrosoftDocs/visualstudio-docs/issues/5663

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92240a7d-b3d0-997d-4608-0cbf9b0772b8
* Version Independent ID: 730a0427-8083-e401-0f3b-6b75b9c6f94a
* Content: [Error Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/error-task?view=vs-2019#feedback)
* Content Source: [docs/msbuild/error-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/error-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by Forgind** [comment]
Note that the ordering of parameters was altered here:
[dotnet/msbuild#5572](https://github.com/dotnet/msbuild/pull/5572)

**Comment by BenSokolGarmin** [comment]
This doesn't appear to have been fixed. The documentation is still missing HelpLink.
