### ISSUE TITLE
Need to document new HelpLink parameter 

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/visualstudio-docs#5663]
HelpLink has been added to the Error task: https://github.com/dotnet/msbuild/pull/5488.

This should be documented.

Error version of this issue is here: https://github.com/MicrosoftDocs/visualstudio-docs/issues/5662

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62871e82-3b22-e086-0825-3592347b2d87
* Version Independent ID: f5b6192f-4daf-42c7-a6ac-60b307b5cb6e
* Content: [Warning Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/warning-task?view=vs-2019)
* Content Source: [docs/msbuild/warning-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/warning-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by Forgind** [comment]
Note that the ordering of parameters was altered here:
[dotnet/msbuild#5572](https://github.com/dotnet/msbuild/pull/5572)

**Comment by BenSokolGarmin** [comment]
This doesn't appear to have been fixed. The documentation is still missing HelpLink.
