### ISSUE TITLE
Microsoft Doc Accessibility Workshop for Write the Docs, August 9, 2020

### ISSUE THREAD

**Issue by tedhudek** [MicrosoftDocs/visualstudio-docs#5664]
# Microsoft Doc Accessibility Workshop for Write the Docs, August 9, 2020

We're so glad you could join us today!

We will be bringing the most frequently visited docs in the Visual Studio documentation repo into alignment with accessibility recommendations in the Microsoft Style Guide.  By doing so, we'll set a precedent for the community, as well as Microsoft's writers.

Specifically, we're going to update occurrences of the word click, according to the following style guide recommendations:

[Describing interactions with UI](https://docs.microsoft.com/en-us/style-guide/procedures-instructions/describing-interactions-with-ui)

Here's how to proceed:

1. Look at [vs-filenames-with-click](https://gist.github.com/tedhudek/fb0b8117a0006002f77e6c6721f120c6).
2. In the list, pick a block of files to work on.
3. Look in the discussion in this issue to ensure that no one else is already working on that block. Add a comment that you are starting work on it.
4. Either work in the browser (hint: use the `t` keyboard shortcut on GitHub to get to the file picker, where you can quickly find files) or `git clone https://github.com/MicrosoftDocs/visualstudio-docs` and work locally.
5. Open one pull request to contain all your changes. In the PR, add `#5664` in the conversation to link to this issue.
6. Add the `Write-the-Docs-2020` label to the PR so we can triage all the fixes later.

If you have questions, don't hesitate to message Ted Hudek on the Hopin platform during Writing Day.

Thank you for your help making our docs more accessible for everyone!

**Comment by tcmetzger** [comment]
I'll tackle block 21!

**Comment by AstroChoco** [comment]
I'm working on block 1.

**Comment by AlexB-SheldonMFG** [comment]
I will take a shot at block 9.

**Comment by caro-oviedo** [comment]
HI! I'll take block #28.

**Comment by AlexB-SheldonMFG** [comment]
Finished block 9. I did not change designers\windows-forms-designer-overview file (line 200 in the files list). The procedure described in it seems to require exact knowledge the touchscreen UI to accurately describe. Cheers! -Alex.

**Comment by technicaltidbits** [comment]
I'll take block 18

**Comment by tcmetzger** [comment]
I'll get started on block 22.

**Comment by tedhudek** [comment]
Thanks for everyone's time! We'll process these as soon as we can.
