### ISSUE TITLE
setup completed with warning visual studio community 2019

### ISSUE THREAD

**Issue by ricardo-nikolay2** [MicrosoftDocs/visualstudio-docs#5667]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85fb6cbc-bab9-2aa9-d462-fad147bb0b6d
* Version Independent ID: 594fc9a0-560b-5672-7bc1-ff8406bdda0d
* Content: [Developer Community guidelines - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/developer-community-guidelines?view=vs-2019)
* Content Source: [docs/ide/developer-community-guidelines.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/developer-community-guidelines.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by msebolt** [comment]
@ricardo-nikolay2 Thank you for the feedback.

For documentation concerns, please provide a reference to any necessary changes.

For product issues, please try soliciting feedback from the product team [here](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by WilliamAntonRohm** [comment]
@ricardo-nikolay2 -- Ricardo, please consider these resources:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
