### ISSUE TITLE
Building ASP.NET Core applications in Visual Studio for Mac - Task 1 & 2 Outdated 

### ISSUE THREAD

**Issue by justinjinsukkim312** [MicrosoftDocs/visualstudio-docs#5669]
https://docs.microsoft.com/en-us/visualstudio/mac/building-asp-net-core?view=vsmac-2019
**Problem I found in Task 1**
When following the directions for 'Creating a new ASP.NET Core application' in Task 1 there is a problem at Step 3. It asks you to 'Select the .NET Core > App category and the ASP.NET Core Web App (C#) template. Click Next.'

**What is the problem with this? - Results in Task 2**
As a result In Task 2 step 1 you do not see the folder structure that is shown with Dependency, Controller, Views and wwwroot. 

After the user builds the application the folders shown are Dependency, Pages, Properties and wwwroot.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee1a5546-d01a-213d-d806-f2ffdca30929
* Version Independent ID: 042dc42b-b153-bbd3-30fa-a786e72686fd
* Content: [Building ASP.NET Core applications - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/building-asp-net-core?view=vsmac-2019)
* Content Source: [mac/building-asp-net-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/building-asp-net-core.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
This should be assigned to @jmatthiesen, I am no longer on the Visual Studio for Mac team, and I don't have permission to re-assign.
