### ISSUE TITLE
Target build order appears to be incorrect

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [MicrosoftDocs/visualstudio-docs#567]
In MSBuild 15.5.180.51428 for .NET Framework, I created a simple project file by hand:

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" DefaultTargets="EntryPoint">
  
  <Target Name="Before_ConditionalTarget"
          BeforeTargets="ConditionalTarget">
  
    <Message Text="Running Before_ConditionalTarget" />
  
  </Target>
  
  <Target Name="DependencyOf_ConditionalTarget">
  
    <Message Text="Running DependencyOf_ConditionalTarget" />
  
  </Target>
  
  <Target Name="ConditionalTarget"
          Condition="'$(MyProperty)' == 'true'"
          DependsOnTargets="DependencyOf_ConditionalTarget">
  
    <Message Text="Running ConditionalTarget" />
  
  </Target>
  
  <Target Name="After_ConditionalTarget"
          AfterTargets="ConditionalTarget">
  
    <Message Text="Running After_ConditionalTarget" />
  
  </Target>
  
  <Target Name="EntryPoint"
          DependsOnTargets="ConditionalTarget">
    
    <Message Text="Running EntryPoint" />
    
  </Target>
  
</Project>
```

The results of running this project in MSBuild differ from the Determining the Target Build Order section indicated above when the project is run with no additional parameters, and the condition on `ConditionalTarget` is false. Per the documentation, the expected build order would be `After_ConditionalTarget`, `EntryPoint`. The actual build order is `Before_ConditionalTarget`, `After_ConditionalTarget`, `EntryPoint`. This shows that even if `ConditionalTarget` is skipped (step 3), targets that list it in a `BeforeTargets` attribute still run.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0889ca82-f08c-9328-e6d7-02e13ec3c1f7
* Version Independent ID: 0cf6e63e-dc5a-6f90-7c53-8ff8db424198
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/target-build-order)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/target-build-order.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@Joe-Sewell-PreEmptive Thanks for the comments--sorry for the slow response time. Would it clarify the build order to append Step 3 with the following statement: "Targets that list the conditional target in `BeforeTargets` or `AfterTargets` still execute in the prescribed order."

**Comment by Joe-Sewell-PreEmptive** [comment]
That sounds fine to me. Thanks for looking into this.
