### ISSUE TITLE
Collect profiling data from the command line: how to examine output

### ISSUE THREAD

**Issue by michaelandsylas234** [MicrosoftDocs/visualstudio-docs#5672]
The document describes how to collect profiling data from the command line and says to load the file in visual studio to examine it, but it does not explain how to load the file into visual studio. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e998101e-f5d8-517a-7f74-356b973a2b07
* Version Independent ID: 36f07905-43eb-019a-a0f6-a732b9d10da6
* Content: [Run profiling tools with or without the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/running-profiling-tools-with-or-without-the-debugger?view=vs-2019#collect-profiling-data-from-the-command-line)
* Content Source: [docs/profiling/running-profiling-tools-with-or-without-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/running-profiling-tools-with-or-without-the-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@michaelandsylas234 Should work by using the File > Open command in Visual Studio, then locating the output .diagsession file. I'll add that info to doc.
