### ISSUE TITLE
Visual studio for mac integrated terminal : how to clear the content after each use or anytime

### ISSUE THREAD

**Issue by Progbasic** [MicrosoftDocs/visualstudio-docs#5674]
Hi,

Visual studio for mac integrated terminal: anybody knows how to clear the content after each use or anytime I which to. I did not find any shortcut? It seems pretty basic necessity to me. I mean even after shutting down the app, the terminal brings back yesterday’s data? Very annoying. Still pleasant add up but…

Have a good one,

prog

**Comment by WilliamAntonRohm** [comment]
@Progbasic -- Prog, please consider these resources:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
