### ISSUE TITLE
Inaccurate Instructions

### ISSUE THREAD

**Issue by mevanecek** [MicrosoftDocs/visualstudio-docs#568]
Something is wrong with the instructions. I create a solution, selected Git as the repository, and created a project and a test project. Added some files, ran some tests, everything looked good. Went to Version Control, and the option available was to Review and Commit. So I review and commit. Now, "Publish in Version Control" is greyed out. There is no way to push the code up to the remote project I created in VSTS. Please update the instructions above to specify a way that will work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606d4c70-3daf-8b03-9c31-b690927a7136
* Version Independent ID: 24a13aaf-3d14-c810-182c-2c2d93fc299b
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository#publishing-an-existing-project)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/mac/set-up-git-repository.md)
* Service: unspecified

**Comment by jpdevspace** [comment]
Same thing here too. My "Publish in Version Control" option is greyed out. Any solutions

**Comment by jpdevspace** [comment]
BTW, I was just able to successfully push my code to Github. I'm on a mac computer... I did:
Version Control > Manage Branches and Remote 
Clicked the Remote Sources tab 
Added my Github branch with the url provided by Github when I created my branch

Then I did Version Control > Push Changes 

and I was asked for my Github username (NOT my email) and my Github password.

Hope it helps!

**Comment by asb3993** [comment]
Hey @mevanecek, thanks for the report. I've been able to reproduce the same issue at my end from an existing project. The one thing I've noticed is that you must select the **Solution name** from the solution pad, before you can get the "Publish to version control" option and follow the steps as shown in the guide. While this isn't a bug, per se, it's definitely a usability issue with the product and so i've created a developer community issue for the problem [here](https://developercommunity.visualstudio.com/content/problem/215477/version-control-usability-issue.html). Please feel free to contribute to that issue as you see fit.

From a documentation point of view, I've updated the guide to mention that the Solution Name must be selected.

**Comment by asb3993** [comment]
Clarified the issue here: fd10ea7ff4ca04ba81ed88621828ce457131ab45

The developer community issue is also under investigation by our UX team. 

I'm closing this issue for now, but please do not hesitate to re-open or add a comment to this issue if necessary.
