### ISSUE TITLE
CA1812: Avoid uninstantiated internal classes

### ISSUE THREAD

**Issue by nirrave** [MicrosoftDocs/visualstudio-docs#5683]
In Basic there is no shared class and module, which promoted, is a bad idea for a friend class to specific use. So do some about, because suppressing the message does not work.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4303a22-627d-4024-fee7-40db88a544ac
* Version Independent ID: 37cc2f4d-7002-1b29-cfa4-b8be2924d0a7
* Content: [CA1812: Avoid uninstantiated internal classes - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1812)
* Content Source: [docs/code-quality/ca1812.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1812.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@nirrave -- thank you for your feedback.  Please provide additional details and context for your request.  Meanwhile, consider these resources:

- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

cc @Mikejo5000 for awareness

**Comment by nirrave** [comment]
William thank you for your the respond,

Replacing a friend class with a friend module, which is promoted and exposed outside the "everywhere", is a bad idea when it intended for specific use within a specific scope. Such as: Debugger Type Proxy class, helper class, class extensions or dependency property change methods, that are classes just to not exposed their methods outside their scope. 

By the way,
Yesterday I got the VS 16.7 update and suddenly the CA1812 suppress is working.

**Comment by WilliamAntonRohm** [comment]
@nirrave, you're welcome!  Thank you for clarifying.

@Mikejo5000, please look into this issue.

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moving issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22038](https://github.com/dotnet/docs/issues/22038)
