### ISSUE TITLE
Help menu does not show "send feedback"

### ISSUE THREAD

**Issue by alexolog** [MicrosoftDocs/visualstudio-docs#5684]
[Enter feedback here]
There is no "send feedback" submenu under the "help" menu

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio](https://docs.microsoft.com/en-ca/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
For sign-in errors or for issues with the Feedback Tool in Visual Studio, please email us at vsfeedback@microsoft.com.
