### ISSUE TITLE
Exclude Command not in Visual Studio any more

### ISSUE THREAD

**Issue by karlamrock** [MicrosoftDocs/visualstudio-docs#5687]
[Enter feedback here]
Please update this doc page to match Visual Studio 16.7.0.

This entire section is no longer correct, please fix.  Please open up your VS and correct these docs.  Exclude is not a menu option which changes the developers workflow completely from the docs.

Exclude all tests in a project or solution
To select the individual projects in unit tests, do the following after Live Unit Testing is started:

Right-click the solution in Solution Explorer and choose Live Tests > **Exclude** to exclude the entire solution.
Right-click each test project that you'd like to include in the tests and choose Live Tests > Include.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3113c2af-d97e-7b35-17ce-c675c3dff889
* Version Independent ID: b716c4af-d92b-cb3b-8af0-1b3ada479ac0
* Content: [Live Unit Testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2019#feedback)
* Content Source: [docs/test/live-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/live-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@karlamrock Tested this. Menu option is "Live Unit Testing" instead of "Live Tests". I'll update doc. Thanks!
