### ISSUE TITLE
Incomplete documentation. Only covers bare minimum.

### ISSUE THREAD

**Issue by plangevin** [MicrosoftDocs/visualstudio-docs#5690]
This documentation is very incomplete.

It does not cover how to set up/tear down test cases.

It also omit how to configure a test project (Like tweaking parameters) like it is possible when having access to the "main" fonction.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee608ee-eb3f-e95d-1eea-d9e35a6e0bc0
* Version Independent ID: daf80b3e-5bf1-652c-d6a0-602c8bc2bb0c
* Content: [How to use Google Test for C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-google-test-for-cpp?view=vs-2019)
* Content Source: [docs/test/how-to-use-google-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-use-google-test-for-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@plangevin 
Yes, the simplicity of this article is intentional. Once you've hooked up the test automation, we expect you to learn about the details of [using Test Explorer](https://docs.microsoft.com/visualstudio/test/run-unit-tests-with-test-explorer) in the linked documentation, rather than duplicating it on this page.

**Comment by plangevin** [comment]
@corob-msft So how can I specify that I want the xml output as I would do in the main like this:
::testing::GTEST_FLAG(output) = "xml:my_output.xml";

I am happy with the VS integration but when the same tests are ran on a build server, I might need to configure extra settings.

**Comment by corob-msft** [comment]
@plangevin 
The short answer is, I don't know. The [test adapter readme file](https://github.com/microsoft/TestAdapterForGoogleTest) seems to indicate it's possible to use commands in the Test Explorer under **Tools > Options >Test Adapter for Google Test**, at least for some subset of options. Or, it also describes using the command-line test adapter driver, and using options flags there. That may work best on remote systems.
