### ISSUE TITLE
Broken link in See Also section: "Packages, metadata, and frameworks"

### ISSUE THREAD

**Issue by coletrumbo-ss** [MicrosoftDocs/visualstudio-docs#5691]
When I clicked the link, I ended up at a 404 page, at this URL https://docs.microsoft.com/en-us/dotnet/core/packages
Is the article missing? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1927440c-08b4-d442-d315-24b677603034
* Version Independent ID: e334f0d3-627a-a3f6-cdfb-b3abfcccd1e7
* Content: [How to: Reference an MSBuild Project SDK - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019)
* Content Source: [docs/msbuild/how-to-use-project-sdk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-use-project-sdk.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@coletrumbo-ss -- Cole, thank you for your question.  Apologies for the delay in responding.

@ghogen -- Gordon, please look into this issue.

**Comment by WilliamAntonRohm** [comment]
@coletrumbo-ss, @ghogen -- Cole, Gordon, this issue has been superseded by #5773.
