### ISSUE TITLE
Remainder operator, not modulus operator

### ISSUE THREAD

**Issue by Engineer2B** [MicrosoftDocs/visualstudio-docs#570]
See also https://nl.mathworks.com/matlabcentral/answers/221157-diffrence-between-rem-and-mod#comment_288807 for the differences.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 820b2a22-568b-126c-6149-467830f6c46e
* Version Independent ID: 54045e28-8f44-b985-3d18-8a65ce5b15b7
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/modulus-operator-decrementjavascript)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/scripting-docs/javascript/reference/modulus-operator-decrementjavascript.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Updating references to modulus
