### ISSUE TITLE
Obsolete link

### ISSUE THREAD

**Issue by askrinnik** [MicrosoftDocs/visualstudio-docs#571]
A link to the People Trax application code leads to unavailable page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9f12119-004d-6146-ad95-e21deea81be8
* Version Independent ID: 1c424d51-c436-59bd-852f-c7fbb969bc44
* [Content](https://docs.microsoft.com/en-us/visualstudio/profiling/peopletrax-sample-profiling-tools)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/profiling/peopletrax-sample-profiling-tools.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@askrinnik These particular tools are in the legacy tooling set, and it's possible the sample is no longer supported and has been removed. I need to verify this before removing all associated documentation.
