### ISSUE TITLE
'Make Object Id' is not available.

### ISSUE THREAD

**Issue by wrkettlitz** [MicrosoftDocs/visualstudio-docs#5714]
See link:
https://i.imgur.com/lhN6BQV.png

Why not?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72264f70-4d8e-7612-87c9-3dab87fb2f14
* Version Independent ID: b7b7d351-5d53-c225-47e4-5ae46d6afc75
* Content: [Set a watch on variables - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/watch-and-quickwatch-windows?view=vs-2019#bkmk_objectIds)
* Content Source: [docs/debugger/watch-and-quickwatch-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/watch-and-quickwatch-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@wrkettlitz -- thank you for your question.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Mikejo5000** [comment]
@wrkettlitz This could be a doc issue if the feature is not supported for your app type/project. What language and project type are you working with, and what version of Visual Studio? If it is a product bug, please use the resources mentioned above. Thanks!

**Comment by Mikejo5000** [comment]
Retested. Features works as expected in VS 2019 for me. You can only use this command on reference types, not on value types (e.g., typically a primitive type like "x" in the statement, int x = 10 is a value type), which is likely the issue here, but that is already stated in this section of the docs. If there is another issue, please let me know @wrkettlitz

**Comment by wrkettlitz** [comment]
@Mikejo5000 I was not the issue, but I think I figured out what the problem was. I was debugging a xamarin Android app, and that feature simply doesn't seem to be supported for Android.
