### ISSUE TITLE
The operation did not complete within the time allotted.

### ISSUE THREAD

**Issue by dershver** [MicrosoftDocs/visualstudio-docs#5719]
[Enter feedback here]
The above message was not listed as one of the causes for 'Unable to connect to the Microsoft Visual Studio Remote Debugging Monitor." I am getting this error continuously when trying to deploy an app to HoloLens 2.
There is no info on this document page to guide me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 284b9094-8c91-69e1-01a2-0183ca3ec2a9
* Version Independent ID: 8f7a16bb-32f6-3047-16e3-b82b82fbb7c0
* Content: [Unable to Connect to the Microsoft Visual Studio Remote Debugging Monitor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor?view=vs-2019)
* Content Source: [docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/unable-to-connect-to-the-microsoft-visual-studio-remote-debugging-monitor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@dershver -- thank you for your feedback.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
