### ISSUE TITLE
Dependency validation 2019 support page not showing

### ISSUE THREAD

**Issue by mikko-pulli** [MicrosoftDocs/visualstudio-docs#5724]
Hi
I tried to solve why I cannot open the dependecy validation diagram I made with visual studio 2019 Enterprise in visual studio 19 professional. This page has the information for 17 but when I change it to 19 nothing happens it stays in the support for 17 page

Thank you
Mkko
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fe1b67a-347e-9ce6-f81a-4d2b3636c634
* Version Independent ID: c7e2aa26-33ce-0d36-b820-b94e351b21e3
* Content: [What's new for design in Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/modeling/what-s-new-for-design-in-visual-studio?view=vs-2017&viewFallbackFrom=vs-2019#VersionSupport)
* Content Source: [docs/modeling/what-s-new-for-design-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/what-s-new-for-design-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@mikko-pulli -- Mikko, thank you for your feedback.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@JoshuaPartlow -- Joshua, please look into this issue.

**Comment by j-martens** [comment]
@mikko-pulli - yes, this behavior is as-designed. This page does not exist for 2019 as noted in the banner. 
![image](https://user-images.githubusercontent.com/8481597/121105745-492ded80-c7ca-11eb-82a5-272873269f72.png)

Thank you. We will now proceed to close this issue. #please-close.
