### ISSUE TITLE
VS Command?

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/visualstudio-docs#5728]
What's the command name of this feature?
I accidentally messed up the shortcut and don't know what's the command to set the shortcut to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b0abc5-a74f-4138-7608-6b4215bca8c0
* Version Independent ID: a16608ea-41ce-f2c2-dfd3-8ed50a5a083c
* Content: [Go To Line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/go-to-line?view=vs-2019)
* Content Source: [docs/ide/reference/go-to-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/go-to-line.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@weitzhandler -- Shimmy, thank you for your question.  Please see https://docs.microsoft.com/en-us/visualstudio/ide/reference/go-to-command?view=vs-2019.
