### ISSUE TITLE
References

### ISSUE THREAD

**Issue by Victex** [MicrosoftDocs/visualstudio-docs#573]
Thanks for the extra references

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3adec9eb-97b5-4f9f-77d6-a9eb9130ed10
* Version Independent ID: 90fb8ff4-4ccd-98c1-92c2-02a33252c681
* [Content](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-01-create-project)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/python/tutorial-working-with-python-in-visual-studio-step-01-create-project.md)
* Service: unspecified

**Comment by gregvanl** [comment]
You are welcome
