### ISSUE TITLE
Is "convert anonymous type to class" really available for VS2017?

### ISSUE THREAD

**Issue by untilted-document** [MicrosoftDocs/visualstudio-docs#5738]
The documentation seemingly indicates that it is.. If I choose 2015 I get a "not supported" banner:

![image](https://user-images.githubusercontent.com/18049243/90290716-46968c00-de76-11ea-89ef-f33cef306b35.png)

This banner does *not* appear for 2017:

![image](https://user-images.githubusercontent.com/18049243/90290776-662db480-de76-11ea-8906-17e05e64fa24.png)

Yet, I cannot get my 2017 Pro to show the option:

![image](https://user-images.githubusercontent.com/18049243/90290432-c6702680-de75-11ea-8645-13dc0f1db15d.png)

But 2019 shows it:

![image](https://user-images.githubusercontent.com/18049243/90290532-f5869800-de75-11ea-8b72-e771417a7ba9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adae0162-4dd5-d0c5-d230-14b841995419
* Version Independent ID: f9976678-8c96-4e10-936d-1e9cdb875d8f
* Content: [Convert Anonymous Type to Class - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-anonymous-type-to-class?view=vs-2017)
* Content Source: [docs/ide/reference/convert-anonymous-type-to-class.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/convert-anonymous-type-to-class.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@untilted-document -- Mao, thank you for your question, and for your moniker.  I am investigating.  Meanwhile, please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@mikadumont -- Mika, please look into this potential documentation issue.

**Comment by WilliamAntonRohm** [comment]
@untilted-document -- this feature is only available in Visual Studio 2019.  I am updating the documentation.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
