### ISSUE TITLE
InMemory Table creation issue

### ISSUE THREAD

**Issue by Vikenesh** [MicrosoftDocs/visualstudio-docs#574]
I am gettinig the followiing error ,The operation 'AUTO_CLOSE' is not supported with databases that have a MEMORY_OPTIMIZED_DATA filegroup while running 

ALTER DATABASE imoltp ADD FILEGROUP [imoltp_mod]

  CONTAINS MEMORY_OPTIMIZED_DATA;  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/visual-studio-ide.md)
* Service: unspecified

**Comment by gewarren** [comment]
@Vikenesh I'm not sure how you landed on this Issues page of the Visual Studio docs repo. It looks like you are having a problem with SQL Server. Is that correct?
