### ISSUE TITLE
Are rules going to be taken from editorconfig during build or not? It is not clear.

### ISSUE THREAD

**Issue by SayusiAndo** [MicrosoftDocs/visualstudio-docs#5740]
> Starting in Visual Studio 2019 version 16.5, ruleset files are deprecated in favor of the EditorConfig file for analyzer configuration for managed code. Most of the Visual Studio tooling for analyzer rule severity configuration has been updated to work on EditorConfig files instead of ruleset files. EditorConfig files allow you to configure both analyzer rule severities and analyzer options, including Visual Studio IDE code style options. It is highly recommended that you convert your existing ruleset file to an EditorConfig file. It is also recommended that you save the EditorConfig file at the root of your repo or in the solution folder. By using the root of your repo or solution folder, you make sure that the severity settings from this file are automatically applied to the entire repo or solution, respectively.

Could you please clarify that when I convert my ruleset files to editorconfigs than when I build the project from command line the rules from editorconfig will be applied or not?
I have the assumption editorconfig configures the IDE only and the the build level code analysis.
Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer rule severity and suppression - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#analyzers-in-solution-explorer)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mikadumont Mika, does EditorConfig work when building the project from the command line?

**Comment by Mikejo5000** [comment]
@SayusiAndo Doc may have been updated; there's a section here on building the command-line that talks about the requirements:
[Command-line usage](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#command-line-usage).
Looks like a minor update is needed to clarify that this also works for both the NuGet package and the .NET 5 SDK. I will open a PR. @mavasani @mikadumont in case I missed something.

**Comment by mavasani** [comment]
Please see https://docs.microsoft.com/dotnet/fundamentals/code-analysis/overview#code-style-analysis for details of enabling IDE code style rules on build.

**Comment by mavasani** [comment]
@Mikejo5000 This already exists on VS docs as well: https://docs.microsoft.com/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019#enforce-code-styles-on-build

**Comment by Mikejo5000** [comment]
Thanks, Manish. I'll add a link to that to the PR for code styles.

**Comment by mavasani** [comment]
@Mikejo5000 I think the FAQs at https://docs.microsoft.com/en-us/visualstudio/code-quality/analyzers-faq?view=vs-2019 already cover that EditorConfig and Rulesets are equivalent. Feel free to clarify as appropriate.

**Comment by Mikejo5000** [comment]
My main concern is that the "Command-line usage" section in this doc lists requirements, which can be confusing when they're not complete (yes/no?). Given the scenario, it seems like a link to your first link would be appropriate here, for code style support.
