### ISSUE TITLE
"Convert to Azure Cloud Service Project" is missing from Visual Studio 2019

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/visualstudio-docs#5741]
Hello,

I am using Visual Studio 2019 and "Convert > Convert to Azure Cloud Service Project" is missing for me.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1cf71fe-6918-d8fb-1faa-1c5efb838842
* Version Independent ID: 8311f3ea-3412-4e13-f1fe-4a817cae70e6
* Content: [Publish an Azure cloud service - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-publish-azure-application-wizard?view=vs-2019)
* Content Source: [docs/azure/vs-azure-tools-publish-azure-application-wizard.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/azure/vs-azure-tools-publish-azure-application-wizard.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ravick4u -- Ravi, thank you for your feedback.  Please provide some additional context for your environment or task.  Meanwhile, consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by ravick4u** [comment]
This option is to deploy Web Application to Azure Cloud Service. 

I guess, as Microsoft is not encouraging to use Cloud Service VS2019 might be missing the feature.

**Comment by WilliamAntonRohm** [comment]
@ravick4u -- Ravi, thank you for clarifying.

@ghogen -- Gordon, please look into this potential documentation issue.

**Comment by ghogen** [comment]
That option was removed. I will update the article to reflect that.
You can find alternative steps here:
https://docs.microsoft.com/visualstudio/azure/vs-azure-tools-migrate-publish-web-app-to-cloud-service?view=vs-2019
