### ISSUE TITLE
Page info not accurate

### ISSUE THREAD

**Issue by raymondjstone** [MicrosoftDocs/visualstudio-docs#5744]
While this page states there is no advantage to building tests as 64 bit it's wrong. In some cases it is required to define the bitness since the test may involve calling a module internally that only works for a specific bitness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7145ed3-6107-b870-4d6b-2d4419235f07
* Version Independent ID: f6bd7e86-8a5a-d00c-c1c1-7ed5fbd5ca83
* Content: [Run a unit test as a 64-bit process - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/run-a-unit-test-as-a-64-bit-process?view=vs-2019)
* Content Source: [docs/test/run-a-unit-test-as-a-64-bit-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/run-a-unit-test-as-a-64-bit-process.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AbhitejJohn to confirm. That sounds correct to me. I'll plan to update this.

**Comment by AbhitejJohn** [comment]
I agree. Not sure when/why that comment was made.
/cc: @kendrahavens
