### ISSUE TITLE
Is there a Move To Namespace?

### ISSUE THREAD

**Issue by jmichas** [MicrosoftDocs/visualstudio-docs#5746]
Is there a way in VS Mac to move a class to a new namespace? I do this often when refactoring on windows VS. Seems like a must have. Maybe it is not documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2bb0ef-5a52-c8ef-8fc7-cdc14262a467
* Version Independent ID: f73a4bb6-5990-01ee-6271-c4024b9a86a5
* Content: [Refactoring code - Visual Studio 2019 for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/refactoring?view=vsmac-2019)
* Content Source: [mac/refactoring.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/refactoring.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @cobey
* Microsoft Alias: **cobey**

**Comment by WilliamAntonRohm** [comment]
@jmichas -- Jason, thank you for your question.  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

You are welcome to use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 


cc @cobey for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
