### ISSUE TITLE
Database Profiling not working.

### ISSUE THREAD

**Issue by junpark12** [MicrosoftDocs/visualstudio-docs#5748]
[Enter feedback here]
I've followed all the instruction. but i only see query itself..
![image](https://user-images.githubusercontent.com/20918194/90457910-cb63fd00-e137-11ea-9dc0-1985aa6be6d3.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35ed7d5-c912-2b88-49fe-8adfcd2c01dc
* Version Independent ID: 40f67010-183d-3a20-b012-fe4137b5f474
* Content: [Analyze database usage for .NET Core projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/analyze-database?view=vs-2019)
* Content Source: [docs/profiling/analyze-database.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/analyze-database.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @esteban-herrera
* Microsoft Alias: **esherrer**

**Comment by WilliamAntonRohm** [comment]
@junpark12 -- thank you for your feedback.  Please provide some additional context around your task.  Meanwhile, consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
