### ISSUE TITLE
Woah! this feedback system is so dope. 

### ISSUE THREAD

**Issue by abdulhannanali** [MicrosoftDocs/visualstudio-docs#575]
OMG! Every company should have this! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/visual-studio-ide.md)
* Service: unspecified

**Comment by abdulhannanali** [comment]
Comments too work seamlessly as well as reactions. AWESOME!

**Comment by abdulhannanali** [comment]
CLOSING IT

**Comment by gewarren** [comment]
@abdulhannanali thanks for your positive feedback!
