### ISSUE TITLE
Unable to connect to the Remote Debugger tool (msvsmon) located on a distant machine

### ISSUE THREAD

**Issue by StephRagazzi** [MicrosoftDocs/visualstudio-docs#5752]
Prereqs:

- Visual Studio Pro 2019 version 16.7.2
- Remote Debugger tool (msvsmon) installed on a distant machine.

Steps to reproduce the issue:

- Run Visual Studio
- _Debug_>_Attach to Process..._
- The _Attach to Process_ window appears
- Click on _Find..._
- The _Remote Connections_ window appears
- _Searching..._ trying to discover a remote debugger instance
- Type the ip address/port of the distant machine where the Remote Debugger tool  is installed. For example: _10.70.71.72:4024_
- Click on the refresh arrow
- A search is initiated, but nothing is found.

It works fine when the ip address/port is typed directly in the _Connection target_ field:
- Run Visual Studio
- _Debug_>_Attach to Process..._
- The _Attach to Process_ window appears
- In the _Connection target_ field, type the ip address/machine name and press _Enter_
- The Remote Debugger instance is found

Does the documentation need to be updated? It seems that the _Remote Connections_ window is only for Remote Debugger instances that can be found automatically through UDP 3702, but not sure... Perhaps it's a bug...

**Comment by WilliamAntonRohm** [comment]
@StephRagazzi -- thank you for your thorough feedback.  Are you following a particular docs.microsoft.com article?  Please consider these resources:
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
