### ISSUE TITLE
Examples and explanation needed

### ISSUE THREAD

**Issue by HugoRoss** [MicrosoftDocs/visualstudio-docs#5755]
I think this whole rule needs some examples of how and why such ambiguities may occur and a good explanation why it contradicts everything that was preached the last 30 odd years. It was always the rule to convert to lower-case as there are more lower-case letters than upper-case ones and therefore some information might get lost when converting to upper-case.

Example: The German lower-case "ß" sign is converted to "SS" in all 8-bit codepages and one could not determine whether the word "MASSE" is the upper-case of "Maße" (dimensions) or "Masse" (ground/mass/matter), therefore to avoid such an ambiguity it was recommended to always convert to lower-case.

Please add some examples why in Unicode the opposite might happen and why converting to upper-case is no problem (e.g. if Unicode would define more upper-case letters than lower-case ones and it is guaranteed that every lower-case letter has an upper-case letter defined).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b21ab6f-aa64-74e4-c539-84a9bfbe4004
* Version Independent ID: 5ffe620b-63d0-6f78-886c-8a1720312113
* Content: [CA1308: Normalize strings to uppercase - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1308)
* Content Source: [docs/code-quality/ca1308.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1308.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22037](https://github.com/dotnet/docs/issues/22037)
