### ISSUE TITLE
Update native code debugging for .Net Core projects

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/visualstudio-docs#5758]
In a recent version of VS 2019, a .Net Core project has an "Enable native code debugging" option. But this article says that it doesn't and links to a closed GitHub issue. I think the article should be updated to reflect the current status.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec762474-4eeb-cba2-5290-fd664ab88f8c
* Version Independent ID: 318fa7f6-e54a-1777-1f3f-3a30bb736f69
* Content: [Tutorial: Debug C# and C++ code (mixed mode) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-managed-and-native-code?view=vs-2017#feedback)
* Content Source: [docs/debugger/how-to-debug-managed-and-native-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-debug-managed-and-native-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@svick Thanks! I will plan to update this.

**Comment by Mikejo5000** [comment]
Fix will be live 11/4/20 around noon PST.
