### ISSUE TITLE
Dockerfile leads to multiple installations of Visual Studio Build Tools

### ISSUE THREAD

**Issue by michielvoo** [MicrosoftDocs/visualstudio-docs#5765]
The example Dockerfile installs Visual Studio Build Tools in `C:\BuildTools`, but the parent image is a .NET Framework SDK image, which already has Visual Studio Build Tools installed (in `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools`). So building this Dockerfile will result in an image with two different installations of Visual Studio Build Tools.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by andysterland** [comment]
Thanks for filling the issue @michielvoo. The build tools can be based on a .NET runtime image (mcr.microsoft.com/dotnet/framework/runtime:4.8)  rather than SDK image. I'll work on a PR to update the docs.

**Comment by ornellaalt** [comment]
Hi @michielvoo, the docs have been updated with the fix. Closing out this issue.
