### ISSUE TITLE
Suspected bug.

### ISSUE THREAD

**Issue by TimonYang** [MicrosoftDocs/visualstudio-docs#5766]
[Enter feedback here]
The document says that for managed code, after selecting "change time", the debugger will hit the breakpoint on the first evaluation.
![image](https://user-images.githubusercontent.com/28781772/91007791-6e70b700-e60f-11ea-89c4-1deb95a6870a.png)
However, when I use c# for testing, the debugger will not treat the first evaluation of the condition as a change, but behave like native code. Is this a documentation error? Or is there a deviation in my understanding?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use breakpoints in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2019#create-a-conditional-expression)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@TimonYang -- Timon, thank you for your questions.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@Mikejo5000 -- Mike, please look into this potential documentation issue.

**Comment by Mikejo5000** [comment]
@TimonYang I tested this and I see the same behavior you do. It may be that the managed behavior was changed at some point to match the native behavior. I'll update this. @leslierichardson95 for comment.

**Comment by Mikejo5000** [comment]
Update should be live now.
