### ISSUE TITLE
No "Include line numbers" in Print dialog

### ISSUE THREAD

**Issue by jtsoftware** [MicrosoftDocs/visualstudio-docs#5769]
There is no "Include line numbers" in the Print dialog.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d26f2c7-9dc7-f759-7d83-63b2b6a1acdc
* Version Independent ID: 7f55cfd7-5a45-21ac-294c-37b2130ebbcd
* Content: [Display line numbers for code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/how-to-display-line-numbers-in-the-editor?view=vs-2019)
* Content Source: [docs/ide/reference/how-to-display-line-numbers-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/how-to-display-line-numbers-in-the-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@jtsoftware You're right; we've updated the topic. Thanks for helping us to improve the documentation!
