### ISSUE TITLE
Just a note - project templates

### ISSUE THREAD

**Issue by pgmolloy** [MicrosoftDocs/visualstudio-docs#577]
Project must be the current selected startup project if there is a large number of projects in the solution. This caught me when I first tried the export template in a large multi project solution.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99e16e6e-e5d1-964b-f220-cbb2c7e4b5e2
* Version Independent ID: 94f82ff9-c61f-31d1-df37-f5e4320daf1c
* [Content](https://docs.microsoft.com/en-ca/visualstudio/ide/how-to-create-project-templates)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/how-to-create-project-templates.md)
* Service: unspecified

**Comment by gewarren** [comment]
@pgmolloy You can select the project you want to export as a template from a drop-down list on the first page of the Export Template wizard. So it's not necessary to set it as the startup project.
![wizard](https://user-images.githubusercontent.com/24882762/36620814-b1679f32-18a9-11e8-9ecf-906c63b47495.png)
