### ISSUE TITLE
reading this page makes we want to put a loaded gun in my mouth.

### ISSUE THREAD

**Issue by cellurl3** [MicrosoftDocs/visualstudio-docs#5772]
[Enter feedback here]
reading this page makes we want to put a loaded gun in my mouth.

Shouldn't you be off buying tiktoc or such?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cff4fb7d-66a8-29bc-ff88-dca4f11074b0
* Version Independent ID: 02d11237-7352-d699-852c-b7f4117dd628
* Content: [Create a Web Service Test - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-web-service-test?view=vs-2019)
* Content Source: [docs/test/how-to-create-a-web-service-test.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-create-a-web-service-test.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so we have closed it.
