### ISSUE TITLE
Remove broken link in msbuild-toolset

### ISSUE THREAD

**Issue by dmonroym** [MicrosoftDocs/visualstudio-docs#5773]
In https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-toolset-toolsversion.md#L42 the link for "Packages, metadata, and frameworks" is broken.

Don't think it's relevant anymore as the second link provided there for "Additions to the csproj format for .NET Core." is sufficient

**Comment by WilliamAntonRohm** [comment]
@dmonroym -- Daniel, thank you for this contribution to the accuracy of our documentation.

@ghogen -- Gordon, please review Daniel's [PR 5774](https://github.com/MicrosoftDocs/visualstudio-docs/pull/5774).
