### ISSUE TITLE
Several broken links in VS 2019 16.8 Preview 2 release notes

### ISSUE THREAD

**Issue by vaindil** [MicrosoftDocs/visualstudio-docs#5775]
Several of the links on [this page](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#--visual-studio-2019-version-168-preview-2-) in the "Visual Studio 2019 version 16.8 Preview 2" section are broken.

For example, the text "inline parameter name hints" links to the URL below, which is not correct.

```
https://docs.microsoft.com/en-us/visualstudio/releases/2019/%22https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-csharp-advanced#editor-help%22
```

**Comment by JacquelineWiddis** [comment]
Thank you for highlighting this error.  Issues have been resolved.   #please-close
