### ISSUE TITLE
Create a custom ruleset instructions out of date

### ISSUE THREAD

**Issue by mattfrear** [MicrosoftDocs/visualstudio-docs#5777]
This page says:
Create a custom rule set from an existing rule set

> 
> To create a custom rule set, you can open a built-in rule set in the rule set editor. From there, you can add or remove specific rules, and you can change the action that occurs when a rule is violated—for example, show a warning or an error.
> 
>     In Solution Explorer, right-click the project and then select Properties.
> 
>     On the Properties pages, select the Code Analysis tab.
> 
>     In the Active rules drop-down list, do one of the following:
> 
>     Choose the rule set that you want to customize.
> 
>     - or -
> 
>     Select <Browse> to specify an existing rule set that is not in the list.
> 
>     Select Open to display the rules in the rule set editor.

I am running Visual Studio 2019 16.7.2, and I don't see any of those options. All I see is:

![image](https://user-images.githubusercontent.com/169179/91246798-e1f7fd00-e7a4-11ea-886f-558dcddb6485.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 546e8122-8074-7a9f-0ec5-de27f6c27637
* Version Independent ID: 827d1628-ecba-4f3f-51f2-0a5c9dd1424f
* Content: [Create a custom code analysis rule set - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-create-a-custom-rule-set?view=vs-2019)
* Content Source: [docs/code-quality/how-to-create-a-custom-rule-set.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-create-a-custom-rule-set.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Looks like the doc needs to be updated for VS 2019; existing content is probably VS 2017.
The content is for legacy rulesets, however, so lowering to Pri3.

**Comment by Mikejo5000** [comment]
Test this on 16.8.3 for a .NET Framework 4.7.2 project, and it looks possible there was a UI problem in 16.7.2. If so, it has been resolved since. I see the Active Rules drop-down, and can select Browse to find a ruleset.

From your screenshot, it looks like you have a .NET Core or .NET Standard project, which doesn't support this procedure. I will update the note that mentions .NET Core / Standard to reflect the latest UI.

![image](https://user-images.githubusercontent.com/11948536/102554824-6636fe80-407a-11eb-888c-05b4582f56ee.png)

**Comment by Mikejo5000** [comment]
Doc fix should be live by end of day, 12/17

**Comment by mattfrear** [comment]
Cool, thanks @Mikejo5000. Yes you are correct, I am using a .NET Standard project.
