### ISSUE TITLE
Consider mentioning making a class sealed as a fix for CA1816

### ISSUE THREAD

**Issue by Tragetaschen** [MicrosoftDocs/visualstudio-docs#5778]
In my opinion, the documentation page for CA1816 should put a bit more emphasis on how `sealed` classes influence the warning. There is some mention of unsealed classes that trigger it, but something like
* If possible and if it is not a breaking API change, mark the class as `sealed`

in the "How to fix violations" section offers another solution depending on the context

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 106c0062-7e8f-d661-3117-1c50a553f06f
* Version Independent ID: 6335a601-2328-2cdf-59f9-d84d1560facb
* Content: [CA1816: Call GC.SuppressFinalize correctly - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1816)
* Content Source: [docs/code-quality/ca1816.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1816.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22036](https://github.com/dotnet/docs/issues/22036)
