### ISSUE TITLE
Message box in catch

### ISSUE THREAD

**Issue by maryob77062** [MicrosoftDocs/visualstudio-docs#578]
When you put a message box in your catch and don't close your connection until the finally, your connection stays open until your user gets back from lunch and responds to the message box in the catch.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e2e854-d2d8-8ec2-ae41-beee6636fae3
* Version Independent ID: 2c1c8dae-ea87-e7a0-f0eb-7bc0b775f8d5
* [Content](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-by-using-adonet#BKMK_setupthesampledatabase)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/data-tools/create-a-simple-data-application-by-using-adonet.md)
* Service: unspecified

**Comment by gewarren** [comment]
@maryob77062 thank you for the feedback. I'll try to improve the code in this topic :)

**Comment by gewarren** [comment]
@maryob77062 I'm going to close this issue out as we don't plan to change the code that you pointed out. If you're concerned about connections staying open in your app if the message box isn't closed, one solution is that you could output the message in a label on the form instead.

**Comment by maryob77062** [comment]
I am not concerned about my apps but the newbies that follow your code.
