### ISSUE TITLE
Out of Date Information

### ISSUE THREAD

**Issue by atarng** [MicrosoftDocs/visualstudio-docs#5780]
https://forum.unity.com/threads/c-compression-zip-missing.577492/#post-3849472
"Note that in Unity 2018.3, this file should be renamed to csc.rsp, instead of mcs.rsp."

Adding reference to mcs.rsp is insufficient on the latest versions of Unity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f103240-7b3b-4732-12a9-39fdef044a08
* Version Independent ID: 0c9fb9a9-f254-fa5c-a334-3fff7dfccb92
* Content: [Using .NET 4.x in Unity - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/unity-scripting-upgrade?view=vs-2019)
* Content Source: [docs/cross-platform/unity-scripting-upgrade.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/cross-platform/unity-scripting-upgrade.md)
* Product: **visual-studio-windows**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by therealjohn** [comment]
Thanks! I'm in the process of updating these docs and will make sure this info is corrected as well.
