### ISSUE TITLE
IDiaDataSource::loadDataForExe doesn't download PDB files from the specified server without symsrv.dll.

### ISSUE THREAD

**Issue by M3ikShizuka** [MicrosoftDocs/visualstudio-docs#5781]
Hello, I have read the documentation [Debug Interface Access SDK](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2019) and encountered a problem in practice.
[IDiaDataSource::loadDataForExe](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/idiadatasource-loaddataforexe?view=vs-2019) doesn't download PDB files from the specified server if symsrv.dll it isn't located in the same folder as the program's executable file.
![nosymsrv](https://user-images.githubusercontent.com/15715676/91363799-15b73f00-e806-11ea-9a8d-8190c18e73a8.png)
E_PDB_NOT_FOUND == 0x806d0005

When I copy symsrv.dll from "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64" in the folder with the executable file everything works correctly and characters are downloaded from the server to the specified folder.
![symsrv](https://user-images.githubusercontent.com/15715676/91366617-ebb54b00-e80c-11ea-9d08-fb489d0ee6d5.png)
![symsrv_downloaded](https://user-images.githubusercontent.com/15715676/91364391-48ae0280-e807-11ea-93eb-4df3b45f02ce.png)
I didn't find any mention in the [Debug Interface Access SDK](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2019) that symsrv.dll need to put in the folder with the executable file so that everything works correctly. I think need to add information about this.
Also, I think it will be useful to add a link on [Symbol path syntax](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/symbol-path#symbol-path-syntax) to describe the possible values of the "searchPath" parameter in the [IDiaDataSource::loadDataForExe](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/idiadatasource-loaddataforexe?view=vs-2019) method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af73624a-f0aa-11c2-618c-ac7262da6f91
* Version Independent ID: 78f7c920-0aab-3c25-3b0e-b84f045a87fd
* Content: [Debug Interface Access SDK - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2019)
* Content Source: [docs/debugger/debug-interface-access/debug-interface-access-sdk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-interface-access/debug-interface-access-sdk.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, asking about this.

**Comment by Mikejo5000** [comment]
Adding an update for symsrv.dll. The fix should be live by EOD, 3/15/2021
