### ISSUE TITLE
Add another project type bullet at the top for classic (non-Core, non-Node.js)

### ISSUE THREAD

**Issue by clairestreb** [MicrosoftDocs/visualstudio-docs#5784]
We can use npm in Visual Studio for classic/legacy project types, too.  Examples:

- https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2015-rtm-vs
- https://stackoverflow.com/questions/51361349/working-with-single-file-vue-js-components-in-orchard-asp-net-mvc-razor
- https://www.c-sharpcorner.com/article/react-js-with-asp-net-mvc-setup-using-node-js-babel-and-webpack/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25963783-6129-cbef-174c-9dd4adde494b
* Version Independent ID: 85926796-ac02-c41b-8ffc-c8987e22f387
* Content: [Manage npm packages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/npm-package-management?view=vs-2019)
* Content Source: [docs/javascript/npm-package-management.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/npm-package-management.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@clairestreb Yes, thanks for mentioning that. It is supported, but there's no link because we don't have any current docs here for that scenario, and currently, we're not planning to add them.
