### ISSUE TITLE
Visaul studio 17

### ISSUE THREAD

**Issue by cesesa** [MicrosoftDocs/visualstudio-docs#5786]
[Enter feedback here]
How to specify icon in the windows control desc > Programs > Program unload in Visiual studio 17 for visual basic
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f36735fb-5d5f-72c0-e71d-cff66dd1e909
* Version Independent ID: 8f3d80cc-7f07-1f8e-130a-cc28051418db
* Content: [Application page of VB project properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/application-page-project-designer-visual-basic?view=vs-2019)
* Content Source: [docs/ide/reference/application-page-project-designer-visual-basic.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/application-page-project-designer-visual-basic.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@cesesa -- thank you for your feedback; we appreciate it. To make sure we have all the information needed to triage your issue, please provide more context around your general task.  Meanwhile, consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
