### ISSUE TITLE
404 to "Packages, metadata, and frameworks"

### ISSUE THREAD

**Issue by trivalik** [MicrosoftDocs/visualstudio-docs#5787]
The link behind "Packages, metadata, and frameworks" in note is not working anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77079cd6-4aaf-f6d9-bbe8-22e7c710d4ac
* Version Independent ID: 33bd5e27-8763-c387-15f1-9218a20d82c1
* Content: [MSBuild Toolset (ToolsVersion) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-toolset-toolsversion.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-toolset-toolsversion.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@trivalik -- Trivalik, thank you for your feedback.  This issue is being addressed in issue #5773.
