### ISSUE TITLE
A credit card is required??? Why???

### ISSUE THREAD

**Issue by chrisleadbeater** [MicrosoftDocs/visualstudio-docs#5789]
A credit card is required??? Why???

Trying to redeem this "benefit" is too painful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 739abd7e-9578-4b74-305f-f48dd9723ac4
* Version Independent ID: 427a6df7-d990-00fc-4fa8-52c76963fb9a
* Content: [Power BI Pro Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-pbi)
* Content Source: [subscriptions/vs-pbi.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-pbi.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@chrisleadbeater - Thanks for reaching out.  I understand your concerns.  The redemption process is defined by the group that provides the offer, which is normally a paid service.  So we don't have control over that process.  That said, there is a workaround that may at least mitigate your concerns.  On the "How do you want to pay" page, choose "Invoice" as the payment method, and select "pay by the year".  That way, no credit card is required.  You'll receive an email once a year to let you know your invoice is available to view.  The invoice will show that $0 is due.  You don't need to take any action around the invoice.  

Thanks again for your feedback.  I hope the workaround is helpful for you.

**Comment by evanwindom** [comment]
#please-close

**Comment by chrisleadbeater** [comment]
Thank you. I will try again.
