### ISSUE TITLE
This is not a "walk-through"

### ISSUE THREAD

**Issue by larryedwards** [MicrosoftDocs/visualstudio-docs#5793]
As a noobie with this, I need a lot more detail for a "walk-through". When I try to "build" I get errors, so I'm not even getting to this second step. 

Please show screen shots of where that first code block goes, for example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c5b3e0f-71aa-4626-3e12-361ad0aa3096
* Version Independent ID: 803b5060-80ba-e73c-16a7-89832ae5b85c
* Content: [Walkthrough: Create a custom tab by using Ribbon XML - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-a-custom-tab-by-using-ribbon-xml?view=vs-2019)
* Content Source: [docs/vsto/walkthrough-creating-a-custom-tab-by-using-ribbon-xml.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/walkthrough-creating-a-custom-tab-by-using-ribbon-xml.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by larryedwards** [comment]
![ScrnShot](https://user-images.githubusercontent.com/3360573/91655873-9b362b80-ea60-11ea-949c-065c8e44af6a.png)

**Comment by larryedwards** [comment]
![Image2](https://user-images.githubusercontent.com/3360573/91655947-1ac3fa80-ea61-11ea-8bb8-11d8a9a7985d.png)

**Comment by WilliamAntonRohm** [comment]
@larryedwards -- thank you for your feedback.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@John-Hart -- please look into this issue.

**Comment by larryedwards** [comment]
Re: [MicrosoftDocs/visualstudio-docs] This is not a "walk-through" (#5793)



   Thanks, William.

-- Larry

===== Orig. Msg. =====

**Comment by John-Hart** [comment]
Hi @larryedwards,

thanks for the feedback,  

You're right this "walkthrough" is rather simple.  In the two images you posted I see two separate errors.  In the first image, the errors are because you've pasted the Visual Basic code outside of the Class, try moving the code inside the End Class statement.  The second image shows that you pasted C# code inside a Visual Basic Class. 

I hope that helps to get you started. 

thanks
John
