### ISSUE TITLE
Methods on classes that inherit from `MarshalByRefObject` should not be marked as static

### ISSUE THREAD

**Issue by viniciusvillas** [MicrosoftDocs/visualstudio-docs#5796]
I understand that another exception to this rule would be on methods declared by classes that inherit from `MarshalByRefObject`, used for both remoting and communication between different AppDomains.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73190016-ddef-0e31-ffb2-d72d551e0d0b
* Version Independent ID: 44822112-d0c7-3f59-75c0-3e81f1ee57d7
* Content: [CA1822: Mark members as static - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1822)
* Content Source: [docs/code-quality/ca1822.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1822.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22035](https://github.com/dotnet/docs/issues/22035)
