### ISSUE TITLE
This rule must be suppressed when implementing IXmlSerializable

### ISSUE THREAD

**Issue by viniciusvillas** [MicrosoftDocs/visualstudio-docs#5797]
The method `GetSchema` inherited from `IXmlSerializable` does not fit any of the described exceptions on the article (listed below). Nonetheless, it's impossible to adhere to these rules when implementing `System.Xml.Serialization.IXmlSerializable`, because the method *must* be implemented.

- The method performs a time-consuming operation. The method is perceivably slower than the time that is required to set or get the value of a field.
- The method performs a conversion. Accessing a field does not return a converted version of the data that it stores.
- The Get method has an observable side effect. Retrieving the value of a field does not produce any side effects.
- The order of execution is important. Setting the value of a field does not rely on the occurrence of other operations.
- Calling the method two times in succession creates different results.
- The method is static but returns an object that can be changed by the caller. Retrieving the value of a field does not allow the caller to change the data that is stored by the field.
- The method returns an array.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b128d86f-bbc8-2446-f67c-d58696605c27
* Version Independent ID: 300d4a05-887f-3cd9-0161-eeb42b8c91ac
* Content: [CA1024: Use properties where appropriate - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1024)
* Content Source: [docs/code-quality/ca1024.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1024.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22034](https://github.com/dotnet/docs/issues/22034)
