### ISSUE TITLE
Version Control For Office Primary Interop Assemblies

### ISSUE THREAD

**Issue by TomTurkington** [MicrosoftDocs/visualstudio-docs#5799]
This page does not specify which versions of Office have PIA's (that is essential information).  It also indicates that you need to specify .Net Programmability Support when installing Office but doesn't give details on how that is done nor what to do if Office is already installed.  When I go to 'Change' Office in Program and Features, it doesn't actually offer a 'Change' option, just a 'Repair' option and I am not seeing where I have an option to add the .Net Programmability Support during the repair.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e97e75d6-dc3e-800e-7cff-d097023df034
* Version Independent ID: 89401b4f-16db-66ab-512c-cce9f949ac10
* Content: [How to: Install Office primary interop assemblies - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-office-primary-interop-assemblies?view=vs-2019)
* Content Source: [docs/vsto/how-to-install-office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-install-office-primary-interop-assemblies.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@TomTurkington -- thank you for your feedback.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@John-Hart -- please look into this issue.

**Comment by TomTurkington** [comment]
Thanks; but I think you missed the point.  I was commenting on the specific page which doesn't mention Office PIA versions nor how to install the .Net Programmability when Office is already installed.  The lack of reference on Office PIA versions makes that page virtually worthless.  I did somewhat resolve the issue via other resources on the web.

Tom Turkington
(206) 352-8202
tomt@zumasys.com
