### ISSUE TITLE
CA2231: Cryptic

### ISSUE THREAD

**Issue by ericwj** [MicrosoftDocs/visualstudio-docs#5804]
I've read the warning message for CA2231 three times and I still have no idea what it is talking about.

```
warning CA2231: Overload operator equals on overriding value type Equals
```

Yet the cause is crystal clear: [A value type overrides System.Object.Equals but does not implement the equality operator](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2231?view=vs-2019).

I am not event driven and don't follow patterns like a compiler, perhaps if the message is a directive or suggestion certainly first of all don't use **on** but **when** and generally I think there should be 1-2-3 words extra in the message to make it read like it is normal English.

**Comment by WilliamAntonRohm** [comment]
@ericwj -- Eric, thank you for your feedback.  This repo is for documentation only, and updating an error text belongs to the product team instead.  If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

For future reference, consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

cc @Mikejo5000 for awareness

**Comment by ericwj** [comment]
[Cryptic and duplicate analyzer warnings (CA2231, CS0168, IDE0059)](https://developercommunity.visualstudio.com/content/problem/1173959/cryptic-and-duplicate-analyzer-warnings-ca2231-cs0.html)
