### ISSUE TITLE
doesn't tell me how to perform code analysis

### ISSUE THREAD

**Issue by gregveres** [MicrosoftDocs/visualstudio-docs#581]
I realize that there is a side bar with more topics and one of this probably tells me how to launch a code analysis, but I landed on this page from a google search. Apparently google thinks this is the best match for searching visual studio and code analysis. As a result, I was scratching my head trying to figure out why this page didn't tell me where to go in the product to kick off an analysis. If it is listed in another page, maybe one of the first sentences could be reworded to allow you to link to that page.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b417a6f-2527-9ec4-7e00-a0ce8e55f997
* Version Independent ID: d250f719-b8d7-7b03-d883-968e0b961d49
* [Content](https://docs.microsoft.com/en-ca/visualstudio/code-quality/code-metrics-values)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/code-quality/code-metrics-values.md)
* Service: unspecified

**Comment by gewarren** [comment]
@gregveres thanks for the feedback about the search results. I will try to improve this so it is more clear.

**Comment by carentsen** [comment]
@gewarren isn't it as simple at adding a paragraph after the intro with a link like:
To get started, go here:  https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data
