### ISSUE TITLE
Theme switcher dropdown is missing?

### ISSUE THREAD

**Issue by FaridAhamat** [MicrosoftDocs/visualstudio-docs#5810]
I can't find the button to switch theme in MS Docs. Has this been removed? I remember it was there...

I'm talking about this:
https://docs.microsoft.com/en-us/teamblog/media/september-docs-update/theme_switch.png

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3af9c07-73f9-1936-066a-1b58197f2ec9
* Version Independent ID: 8b5b0c70-23b0-7ddb-8e2f-31bd33b18ca0
* Content: [Error - The web server is not configured correctly - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-the-web-server-is-not-configured-correctly?view=vs-2019)
* Content Source: [docs/debugger/error-the-web-server-is-not-configured-correctly.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/error-the-web-server-is-not-configured-correctly.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@FaridAhamat -- Farid, on that example page ("Error - The web server is not configured correctly - Visual Studio"), the Theme selector has moved down to the lower left corner, next to the language selector:

![image](https://user-images.githubusercontent.com/27738025/92161463-84d3fb00-ede5-11ea-8483-cdbc2c275f1b.png)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
