### ISSUE TITLE
Improve docs for publish profiles

### ISSUE THREAD

**Issue by ghogen** [MicrosoftDocs/visualstudio-docs#5816]
publish profiles aren't only for aspnet.core projects, they apply to Windows desktop apps (WinForms, WPF, WinU)

originally submitted as https://github.com/dotnet/AspNetCore.Docs/issues/19767

@stevenbrix @Rick-Anderson

**Comment by stevenbrix** [comment]
Thank you for filing this @ghogen!

The reason I'm asking for better docs is because we're stumbling over some things at the moment :)

It would also be helpful if there was guidance on how this works with the Windows Application Packaging Project.

Adding @SvetBonev for guidance
