### ISSUE TITLE
Document new EditorConfig code style settings

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#5817]
Commit https://github.com/MicrosoftDocs/visualstudio-docs/commit/d5c01b3f3e3d7adc365a8ef78a1272da1df03407 added the following new EditorConfig settings to the example EditorConfig file on the [overview page](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019). Those settings should also be documented on the [Language conventions page](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019).

- [ ] file_header_template
- [ ] dotnet_style_operator_placement_when_wrapping
- [ ] dotnet_style_prefer_simplified_boolean_expressions
- [ ] dotnet_remove_unnecessary_suppression_exclusions
- [ ] csharp_style_prefer_not_pattern
- [ ] csharp_style_prefer_pattern_matching

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5299f22f-4b0f-9e81-883e-d34b2b520bf2
* Version Independent ID: 6a9db168-c592-29a0-59b7-1ff2f517e558
* Content: [.NET language conventions for EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019)
* Content Source: [docs/ide/editorconfig-language-conventions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-language-conventions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#20884
