### ISSUE TITLE
Default value of the csharp_using_directive_placement EditorConfig setting

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#5818]
Commit https://github.com/MicrosoftDocs/visualstudio-docs/commit/d5c01b3f3e3d7adc365a8ef78a1272da1df03407 changed the default value of the EditorConfig setting `csharp_using_directive_placement` from `outside_namespace` to `inside_namespace`. But is this really correct? According to the [source code](https://github.com/dotnet/roslyn/blob/d602c498ab42c2657c36c67c8c00690c5a70f71f/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/CSharp/CodeStyle/CSharpCodeStyleOptions.cs#L280-L291) it's still `outside_namespace`.

If this change was wrong, it should be reverted.
But if it was correct, the default value on the page [Language conventions](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019) should also be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* Content: [.NET coding convention settings For EditorConfig - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019)
* Content Source: [docs/ide/editorconfig-code-style-settings-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/editorconfig-code-style-settings-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by gewarren** [comment]
This issue was moved to dotnet/docs#20886
