### ISSUE TITLE
Per the Note.. Did lightweight solution load get removed or was the choice of using it removed?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#582]
It looked like a band-aid feature and was unfinished.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50302b6c-c81b-4a07-656c-ff8446a78629
* Version Independent ID: b78f187a-0ed7-abf3-2a2c-5f0a77980ced
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/optimize-visual-studio-startup-time)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/optimize-visual-studio-startup-time.md)
* Service: unspecified

**Comment by gewarren** [comment]
@StingyJack the feature was removed.

**Comment by gewarren** [comment]
Here's a [blog post](https://blogs.msdn.microsoft.com/visualstudio/2017/11/20/large-c-and-vb-solutions-load-significantly-faster-in-15-5-update/) about the improved startup performance.
