### ISSUE TITLE
Pluralsight subscription is not 3-6 months as seen in Microsoft article

### ISSUE THREAD

**Issue by nikoescobal** [MicrosoftDocs/visualstudio-docs#5821]
https://imgur.com/gallery/PfMgOjF --> It'd be great if the subscription could be brought back to 3-6 months as right now it just says 1 month. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e41abd-81dd-4dd2-d2d2-6bc513ad9e48
* Version Independent ID: 911d149e-8d78-b552-12a2-b061e2c1f41c
* Content: [Pluralsight benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-ca/visualstudio/subscriptions/vs-pluralsight)
* Content Source: [subscriptions/vs-pluralsight.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-pluralsight.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@nikoescobal -- Nikolas, thank you for your suggestion.

@evanwindom -- please look into this issue.

**Comment by nikoescobal** [comment]
Thank you for looking into this @WilliamAntonRohm and @evanwindom 🙂

**Comment by evanwindom** [comment]
@nikoescobal - Hi Nikolas.  Thanks for reaching out.  There are three different Pluralsight subscriptions.  Which one is available to you depends on what kind of Visual Studio subscription you have.
Visual Studio Enterprise:  6 months.  (We used this subscription as an example in the document.)
Visual Studio Professional: 3 months.
Visual Studio Dev Essentials:  1 month.

If you have more than one subscription, such as a Visual Studio Enterprise subscription and a Dev Essentials free membership, you may be viewing the Dev Essentials membership.  That would explain why you're seeing a subscription with a shorter duration.  You should be able to see the subscription you're using in the purple band at the top of the screen.  You can switch subscriptions using the subscription drop-down list, or by visiting the subscriptions tab (https://my.visualstudio.com/subscriptions) and choosing the subscription you want to use.  

If you are using a Dev Essentials membership, it is entitled to one month of Pluralsight.  

The image of the tile included in the article is an **_example_**. It shows what a Visual Studio Enterprise subscriber would see in the portal.  It is not intended to state that all subscribers or program memberships would receive six months of Pluralsight use.   The Eligibility table in the article shows what Pluralsight subscriptions are included with various Visual Studio subscriptions and memberships.  https://docs.microsoft.com/visualstudio/subscriptions/vs-pluralsight#eligibility 

I hope this helps provide some clarity.  I will add a note somewhere around that tile image in the article to indicate it's just an example.  

Thanks, 
Evan

**Comment by evanwindom** [comment]
#please-close
