### ISSUE TITLE
mirosoft.Common.concole

### ISSUE THREAD

**Issue by Rino99811** [MicrosoftDocs/visualstudio-docs#5824]
hello 

i need some help with this
file:///C:/Users/Eier/Pictures/mirosoft.Common.concole.png

**Comment by WilliamAntonRohm** [comment]
@Rino99811 -- thank you for your request.  Please provide additional details or context for your task.  Meanwhile, consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 


Your picture is not visible -- you can copy the image and paste it into this dialog.
