### ISSUE TITLE
Package Deprecated

### ISSUE THREAD

**Issue by djpirra** [MicrosoftDocs/visualstudio-docs#5825]
This package seems to be deprecated.
What are the instructions to replace it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 993843c2-ba31-ddf5-17a0-1f5390c49c2a
* Version Independent ID: 3a4f3b37-3233-859e-80c2-f705936309df
* Content: [Create a Load Test Plug-In - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-create-a-load-test-plug-in?view=vs-2019)
* Content Source: [docs/test/how-to-create-a-load-test-plug-in.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-create-a-load-test-plug-in.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@djpirra -- Luis, thank you for your question.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

@Mikejo5000 -- please look into this issue.

**Comment by Mikejo5000** [comment]
The blog post mentioned in the note talks about the alternatives:
https://devblogs.microsoft.com/devops/cloud-based-load-testing-service-eol/
