### ISSUE TITLE
Link for viewing more WPF tutorials does not work

### ISSUE THREAD

**Issue by asmahaslam** [MicrosoftDocs/visualstudio-docs#5826]
Link/button for viewing more WPF tutorials does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329e32a3-766c-1739-022b-5d1a8bc6f4aa
* Version Independent ID: d74a678c-d9b5-90c4-cd63-8451fefaa887
* Content: [Hello World app with WPF in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@asmahaslam -- thank you for your feedback.  I just clicked on that button and it correctly took me to the [WPF Walkthroughs](https://docs.microsoft.com/dotnet/desktop/wpf/getting-started/wpf-walkthroughs?view=netframeworkdesktop-4.8) page.  Please try again on your computer.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
