### ISSUE TITLE
Link "Download the ZIP" doesn't work

### ISSUE THREAD

**Issue by alexandair** [MicrosoftDocs/visualstudio-docs#5827]
@ghogen 
Link "Download the ZIP" redirects to 404 page instead of app.zip file in Assets.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by DaudiWampamba-Tribe** [comment]
After running the setup command, I was able to access the app.zip file at 'http://localhost/assets/app.zip' (the link in the docs goes to '/assets/app.zip'). I was only able to find this by opening the container that the setup command launched, to find a similar looking tutorial hosted on 'https://localhost/tutorial/', although I believe this to be a more general tutorial. It seems to have all the right files though. I hope that helps in the meantime while they amend the docs.

**Comment by WilliamAntonRohm** [comment]
@alexandair -- thank you for your feedback.

@DaudiWampamba-Tribe -- thank you for your research and answer.

@ghogen -- please look into this issue.

**Comment by alexandair** [comment]
@DaudiWampamba-Tribe Excellent find.
The doc still needs a modification/clarification.

**Comment by ghogen** [comment]
This doc was updated, thanks for reporting this.

**Comment by WilliamAntonRohm** [comment]
[See also this answer regarding stopping IIS.](https://github.com/MicrosoftDocs/visualstudio-docs/issues/5998#issuecomment-712449349)

**Comment by pandood** [comment]
For the link to work you must have docker for windows or community edition already installed.

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please see the previous post.
