### ISSUE TITLE
https://github.com/MicrosoftDocs/visualstudio-docs

### ISSUE THREAD

**Issue by RUBBERBULLET21323** [MicrosoftDocs/visualstudio-docs#5828]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bacc9e83-02eb-9732-89c4-d62ce7b0acc2
* Version Independent ID: 05ce4135-c2cf-39de-b488-a1aa646d49f0
* Content: [Object expected](https://docs.microsoft.com/en-us/scripting/javascript/misc/object-expected?f1url=%3FappId%3DDev12IDEF1%26l%3DEN-US%26k%3Dk(VS.WebClient.Help.SCRIPT5007))
* Content Source: [scripting-docs/javascript/misc/object-expected.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/scripting-docs/javascript/misc/object-expected.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Not actionable
