### ISSUE TITLE
Can't access MyWebApi from browser

### ISSUE THREAD

**Issue by vlapenkov** [MicrosoftDocs/visualstudio-docs#5829]
I have the following docker-compose.yml but i can't access webapi from browser. Only webfrontend via http://localhost:5008
Can i access webapi?

docker-compose.yml
version: '3.4'

services:
  webfrontend:
    image: ${DOCKER_REGISTRY-}webfrontend  
    ports: ["5008:80"]
    build:
      context: .
      dockerfile: WebFrontEnd/Dockerfile

  mywebapi:
    image: ${DOCKER_REGISTRY-}mywebapi    
    ports: ["5010:90"]
    build:
      context: .
      dockerfile: MyWebApi/Dockerfile

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aee46f8-9db1-33ef-b637-fc8e8881fab9
* Version Independent ID: 6c469f9f-9751-669f-3dd4-c4fb49c9ae19
* Content: [Multicontainer tutorial using Docker Compose & ASP.NET Core - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2019#feedback)
* Content Source: [docs/containers/tutorial-multicontainer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-multicontainer.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@vlapenkov -- thank you for your question.  This repo is solely for documentation issues, with limited support options.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @ghogen for awareness
