### ISSUE TITLE
42 is not the answer to life, the universe, and everything

### ISSUE THREAD

**Issue by nathvi** [MicrosoftDocs/visualstudio-docs#583]
"The Visible Timeline Profile shows that 42 percent of the visible thread time is consumed by I/O."
This is wrong. It is 44%.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84100a50-c4c1-7369-12e1-3489487d6f58
* Version Independent ID: d5ab85d8-7456-78df-8aec-5dac0ad1a710
* [Content](https://docs.microsoft.com/en-us/visualstudio/profiling/common-patterns-for-poorly-behaved-multithreaded-applications)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/profiling/common-patterns-for-poorly-behaved-multithreaded-applications.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Putting fix in place

**Comment by nathvi** [comment]
The link "Content Source" is  broken and is giving me a 404.

**Comment by Mikejo5000** [comment]
@navthi Hmm, temporary outage? Both links work for me.

**Comment by nathvi** [comment]
Still getting the 404 for 
https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/profiling/common-patterns-for-poorly-behaved-multithreaded-applications.md

**Comment by Mikejo5000** [comment]
@nathvi Ah, didn't notice that the Content Source link goes to the private repo (-pr). The Content link is the only one you will be able to use on the page. However, you can use this link instead:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/live/docs/profiling/common-patterns-for-poorly-behaved-multithreaded-applications.md

**Comment by Mikejo5000** [comment]
Fix verified

**Comment by nathvi** [comment]
And to think, it only took 11 days to fix something simple. Wow. Shows how much Microsoft cares about their documentation.
