### ISSUE TITLE
Bind WPF controls to a dataset:Define the user interface

### ISSUE THREAD

**Issue by OldVSDeveloper** [MicrosoftDocs/visualstudio-docs#5831]
[Enter feedback here]
XAML for first button generates an error.  You have to 'escape' the < label on the button.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233d01cd-0d37-00bd-e5a7-e2f1d5981199
* Version Independent ID: 94efd478-fd6f-67f7-309b-55982e918d95
* Content: [Bind WPF controls to a dataset - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/bind-wpf-controls-to-a-dataset?view=vs-2019)
* Content Source: [docs/data-tools/bind-wpf-controls-to-a-dataset.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/bind-wpf-controls-to-a-dataset.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review [private PR 7127](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7127).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
