### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by nigelhawkins** [MicrosoftDocs/visualstudio-docs#5833]
The page neglects to mention that one of the requirements to access the downloads is some sort of subscription to something unspecified. I just get a "no subscriptions found" warning and a request for a "5x5" code.

Expected behaviour: Get a page where I can download the remote debugging tools for VS2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2fd746-82f7-1bac-9932-27c14cdfe0ca
* Version Independent ID: 46b43a94-b750-2073-5e28-82183af092a9
* Content: [Remote Debug a C# or VB project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by nigelhawkins** [comment]
Please note that this is from a signed-in account.

**Comment by WilliamAntonRohm** [comment]
@nigelhawkins -- Nigel, thank you for your feedback.

@evanwindom -- Evan, please look into this issue.

cc @Mikejo5000 for awareness

**Comment by evanwindom** [comment]
@WilliamAntonRohm - William, the article to which the issue refers is not part of the subscriptions repo.  If the goal here is to add content to the article stating that a Visual Studio subscription is required for access to https://my.visualstudio.com/downloads, the issue should be assigned to @mikejo5000. 

@nigelhawkins - Hi Nigel.  I did some checking, and it looks like the following are available to members of Visual Studio Dev Essentials, which is a free program:

Remote   Tools for Visual Studio 2017 (version 15.0)
Remote Tools   for Visual Studio 2017 (version 15.9)
Remote Tools   for Visual Studio 2019 (version 16.0)
Remote Tools   for Visual Studio 2019 (version 16.4)
Remote Tools   for Visual Studio 2019 (version 16.7)

For information about joining Visual Studio Dev Essentials, please see:  https://visualstudio.microsoft.com/dev-essentials/ .

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- thank you for clarifying.

**Comment by evanwindom** [comment]
#please-close
