### ISSUE TITLE
Cross-site scripting attack

### ISSUE THREAD

**Issue by nigelhawkins** [MicrosoftDocs/visualstudio-docs#5834]
Clicking the "feedback on this page" button causes the noscript plugin for firefox to generate a warning for a potential cross-site scripting attack from microsoft.com to github.com. The suspicious data is basically the "document details" section below.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2fd746-82f7-1bac-9932-27c14cdfe0ca
* Version Independent ID: 46b43a94-b750-2073-5e28-82183af092a9
* Content: [Remote Debug a C# or VB project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by nigelhawkins** [comment]
Full warning is:

NoScript detected a potential Cross-Site Scripting attack
from https://docs.microsoft.com to https://github.com.
Suspicious data:
Error: Timeout! DOS attack attempt?,(URL) https://github.com/MicrosoftDocs/visualstudio-docs/issues/new?title=&body=
[Enter feedback here]
---
#### Document Details
â  *Do not edit this section. It is required for docs.microsoft.com â GitHub issue linking.*
* ID: 4a2fd746-82f7-1bac-9932-27c14cdfe0ca
* Version Independent ID: 46b43a94-b750-2073-5e28-82183af092a9
* Content: [Remote Debug a C# or VB project - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@nigelhawkins -- Nigel, thank you for bringing this to our attention.  We are investigating this issue.

**Comment by Mikejo5000** [comment]
@WilliamAntonRohm Any updates on this? This looks like a site issue, rather than doc enhancement.

**Comment by WilliamAntonRohm** [comment]
@nigelhawkins -- Nigel, thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
