### ISSUE TITLE
Cross site scripting attack

### ISSUE THREAD

**Issue by nigelhawkins** [MicrosoftDocs/visualstudio-docs#5835]
Clicking the download link for the VS2017 remote debugging tools causes the noscript plugin for firefox to generate a potential cross-site scripting attack warning.
NB: This only happens if you are signed in.

Possibly related: Link is very slow and allowing the request breaks the browser "back" button. Possible infinite redirect?
Full warning data below:

NoScript detected a potential Cross-Site Scripting attack

from https://app.vssps.visualstudio.com to https://login.microsoftonline.com.

Suspicious data:

Error: Timeout! DOS attack attempt?,(URL) https://login.microsoftonline.com/common/oauth2/authorize?client_id=499b84ac-1321-427f-aa17-267ca6975798&site_id=501454&response_mode=form_post&response_type=code+id_token&redirect_uri=https://app.vssps.visualstudio.com/_signedin&nonce=e283a4ea-446c-4f12-955d-725a1db4e3df&state=realm=my.visualstudio.com&reply_to=https%3A%2F%2Fmy.visualstudio.com%2FDownloads%3Fq%3Dremote%2520tools%2520visual%2520studio%25202017&ht=3&mkt=en-GB&nonce=e283a4ea-446c-4f12-955d-725a1db4e3df&resource=https://management.core.windows.net/&cid=e283a4ea-446c-4f12-955d-725a1db4e3df&wsucxt=1&githubsi=true&msaoauth2=true&mkt=en-GB

**Comment by WilliamAntonRohm** [comment]
@nigelhawkins -- Nigel, thank you for this information.  We are investigating.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
