### ISSUE TITLE
Custom installation from Code Analysis properties not visible

### ISSUE THREAD

**Issue by Xelit3** [MicrosoftDocs/visualstudio-docs#5836]
Hi all, trying to follow the documentation, from VisualStudio 2019 version 16.3 should be visible the custom installation from project properties on Code Analysis window, however it is not the case

- Expected:
![image](https://user-images.githubusercontent.com/55638917/92463781-9134cb00-f1cc-11ea-904c-a8a1147379f7.png)
- Current:
![image](https://user-images.githubusercontent.com/55638917/92463835-a27dd780-f1cc-11ea-9bdc-4d93f1937830.png)

As mentioned, I using VS 2019 v 16.7.2 (> 16.3)

Thank you in advance

**Comment by WilliamAntonRohm** [comment]
@Xelit3 -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?

**Comment by Xelit3** [comment]
Hi @WilliamAntonRohm 

Thank you for quick reply, yes, I am following this [link](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019)

**Comment by Mikejo5000** [comment]
Doc has been updated previously. Those screenshots were removed.
