### ISSUE TITLE
api_surface of code analyzer rule in .editorconfig can be "none"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#5838]
The documentation does not list `none` among the allowable values for `api_surface`. However, the following syntax in .editorconfig seems to effectively disable the code analyzer rule, when using Microsoft.CodeAnalysis.FxCopAnalyzers 2.9.4. Please consider documenting it.

```
[*.cs]
dotnet_code_quality.CA1716.api_surface = none
```

The `none` name matches [`SymbolVisibilityGroup.None`](<https://github.com/dotnet/roslyn-analyzers/blob/a1a198d1c5d2359e93dd4ab4b1c4f7421512724e/src/Utilities/Compiler/Options/SymbolVisibilityGroup.cs#L19> "roslyn-analyzers/SymbolVisibilityGroup.cs at v2.9.4 · dotnet/roslyn-analyzers").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b376237-1957-7b92-899d-0c816dac5412
* Version Independent ID: 0a02458c-2f69-80c3-4215-436f2250ced0
* Content: [.NET code quality analyzer configuration options - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-quality-rule-options)
* Content Source: [docs/code-quality/fxcop-analyzer-options.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/code-quality-rule-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by KalleOlaviNiemitalo** [comment]
`none` there is particularly useful for older Visual Studio versions that do not support configuring [rule severity](https://docs.microsoft.com/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#rule-severity) in .editorconfig. Unlike [rule sets](https://docs.microsoft.com/visualstudio/code-quality/using-rule-sets-to-group-code-analysis-rules?view=vs-2019), .editorconfig makes it easy to add comments that will be seen by people who edit the file.

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22074](https://github.com/dotnet/docs/issues/22074)
