### ISSUE TITLE
Space needed in "illustration.The "

### ISSUE THREAD

**Issue by nathvi** [MicrosoftDocs/visualstudio-docs#584]
"illustration.The" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84100a50-c4c1-7369-12e1-3489487d6f58
* Version Independent ID: d5ab85d8-7456-78df-8aec-5dac0ad1a710
* [Content](https://docs.microsoft.com/en-us/visualstudio/profiling/common-patterns-for-poorly-behaved-multithreaded-applications)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/profiling/common-patterns-for-poorly-behaved-multithreaded-applications.md)
* Service: unspecified

**Comment by gewarren** [comment]
@nathvi thanks for reporting this typo. For reference, you can edit the topic by clicking the Edit button near the top right, if you'd like to help us by fixing issues like this that you come across. Otherwise, reporting an issue is great too :)

**Comment by kraigb** [comment]
@Mikejo5000 I'll fix this one as part of the other changes to profiling topics that I'm doing for the SKU scrub.

**Comment by Mikejo5000** [comment]
@kraigb I see the fix
