### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kingbrown727** [MicrosoftDocs/visualstudio-docs#5842]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f79453c-3962-2f0c-5b99-4fbde91972f8
* Version Independent ID: c845c29e-dfd7-316e-81b2-ebe288a384c1
* Content: [Technical Support Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-tech-support)
* Content Source: [subscriptions/vs-tech-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-tech-support.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@kingbrown727 Hi.  I see you posted an issue, but there's no content/feedback included.  Can you provide some context, please?  If the issue was opened in error, feel free to close it.

**Comment by evanwindom** [comment]
@kingbrown727 I hope all is well with you.  Since we haven't heard from you, I'm going to close the issue.  If you need anything, you can post it here.  Thanks!

**Comment by evanwindom** [comment]
#please-close
