### ISSUE TITLE
Documentation of the Null checking settings is hard to find

### ISSUE THREAD

**Issue by olegsych** [MicrosoftDocs/visualstudio-docs#585]
The following settings are documented in the [Expression-level preferences](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#a-nameexpressionlevelexpression-level-preferencesa) section even though they are displayed in the _null checking_ section of the C# Code Style settings of the Visual Studio Options dialog.
- `dotnet_style_coalesce_expression`
- `dotnet_style_null_propagation` 

They would be easier to find in the ["Null" checking preferences](
https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#null_checking) section along with the other null-checking settings:
- `csharp_style_throw_expression`
- `csharp_style_conditional_delegate_call`

While the Null checking settings section is currently C#-specific, it could be moved to the .NET section of the documentation page with language applicability documented for individual settings, similar to other sections, like [This. and Me. clarifiers](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#a-namethisandmethis-and-me-qualifiersa)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 410f3156-99cc-2a5c-2696-9d354c4f34c7
* Version Independent ID: fe3c3dfe-251f-2585-fe18-7fae3bcc76d0
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#a-namethisandmethis-and-me-qualifiersa)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/ide/editorconfig-code-style-settings-reference.md)
* Service: unspecified

**Comment by gewarren** [comment]
@olegsych thank you for the feedback. I will make the changes you suggested.
