### ISSUE TITLE
how to exclude project(s) from yml file

### ISSUE THREAD

**Issue by sdksmm** [MicrosoftDocs/visualstudio-docs#5850]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee095664-5b6b-bfb0-6d08-2c01b4a5c682
* Version Independent ID: 5c61c163-69be-96df-979c-3d0cb5abdc89
* Content: [How to: Exclude projects from a build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-exclude-projects-from-a-build?view=vs-2019)
* Content Source: [docs/ide/how-to-exclude-projects-from-a-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-exclude-projects-from-a-build.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@sdksmm -- Mohammad, thank you for your feedback.  Please provide additional details or context for your task.  Meanwhile, consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)
