### ISSUE TITLE
CPU Usage is disabled. What's wrong?

### ISSUE THREAD

**Issue by dontsovcmc** [MicrosoftDocs/visualstudio-docs#5852]
Microsoft VS Community 2015 update 3, 14.0.25431.01

![Screenshot_3](https://user-images.githubusercontent.com/6192152/92712174-fa017c00-f361-11ea-82ac-cd0964731050.png)

https://docs.microsoft.com/ru-ru/visualstudio/profiling/cpu-usage?view=vs-2015

**Comment by WilliamAntonRohm** [comment]
@dontsovcmc -- Evgeny, thank you for your question.  Have you tried changing to a Release configuration from Debug?  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio) 

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
