### ISSUE TITLE
CA1303 should mention Localizable(false) as fix

### ISSUE THREAD

**Issue by RobinHood70** [MicrosoftDocs/visualstudio-docs#5853]
In the various methods of overriding CA1303's detection, the focus seems to be on avoiding hitting the rule or using traditional code suppression. It should also mention that it's possible to suppress this for specific methods by tagging the parameter with `[Localizable(false)]`. This is implied in passing at in the beginning, but that's the only time that LocalizableAttribute is ever mentioned.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a0a1a48-3a9f-05c8-53fd-4d126bb275ad
* Version Independent ID: 65f77e05-47ac-9e01-ce54-9669c2dd9b2b
* Content: [CA1303: Do not pass literals as localized parameters - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1303)
* Content Source: [docs/code-quality/ca1303.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1303.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22033](https://github.com/dotnet/docs/issues/22033)
