### ISSUE TITLE
Does not indicate how to do this activity using VS on MacOS

### ISSUE THREAD

**Issue by xamarinermanoj** [MicrosoftDocs/visualstudio-docs#5858]
Hi,

I think it would greatly help if this page also showed the screens and steps on how to create a simple Forms Application on the Visual Studio for MacOS also.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8664d15-b038-4d16-3a83-c7c3354997c1
* Version Independent ID: 04a14caf-8611-d997-8ab7-9b4ac6db7730
* Content: [Create a Windows Forms app with Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-a-visual-basic-winform-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/create-a-visual-basic-winform-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-a-visual-basic-winform-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@xamarinermanoj -- thank you for your suggestion.  Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [https://social.msdn.microsoft.com/Forums/vstudio](https://social.msdn.microsoft.com/Forums/vstudio) 
- [https://www.stackoverflow.com](https://www.stackoverflow.com) 
- [https://www.reddit.com/r/VisualStudio/](https://www.reddit.com/r/VisualStudio)

**Comment by ornellaalt** [comment]
Hi @xamarinermanoj, please see our [Visual Studio for Mac documentation](https://docs.microsoft.com/en-us/visualstudio/mac/?view=vsmac-2019) for Mac-specific tutorials.
