### ISSUE TITLE
Link break: enforce the .NET coding conventions on build

### ISSUE THREAD

**Issue by wellwind** [MicrosoftDocs/visualstudio-docs#5859]
There is a link named "enforce the .NET coding conventions on build" in "Enforce code styles on build" section, but after click I got 404 error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faebd126-53cd-1a98-bf75-38225933b0f2
* Version Independent ID: 4340fcba-6779-68d2-6c51-2ae37123dc26
* Content: [Code style options and code cleanup - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2019)
* Content Source: [docs/ide/code-styles-and-code-cleanup.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/code-styles-and-code-cleanup.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by cremor** [comment]
Note that the same broken link is also on the page https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2019

**Comment by cremor** [comment]
Seems like this was fixed by https://github.com/MicrosoftDocs/visualstudio-docs/commit/1ff41bd9513b5d2f3d0a006d95f40a7bfb481757

**Comment by WilliamAntonRohm** [comment]
@cremor -- thank you for the update.

@mavasani -- thank you for fixing this.
