### ISSUE TITLE
Pre-publish tasks

### ISSUE THREAD

**Issue by SimpleSamples** [MicrosoftDocs/visualstudio-docs#586]
What do we need to do before publishing? If there is nothing special then I apologize but I assume there are things we need to do for Clickonce applications. Is there anything special we need to do to use the file system? Clickonce applications have limitations so is there anything we need to ensure we remain within the limitations? I see many, many articles describing what to do when we get to the deployment stage but if there is anything we must do before we are ready to deploy then I am looking for that/those articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0f34bbe2-cc90-693f-8ec3-22b7fc86d1df
* Version Independent ID: 92505bd9-cd9e-73e5-ab3e-dbd96bd1b0d4
* [Content](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-deployment-samples-and-walkthroughs)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/deployment/clickonce-deployment-samples-and-walkthroughs.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@SimpleSamples Does this topic answer your question?
https://docs.microsoft.com/en-us/visualstudio/deployment/application-deployment-prerequisites

**Comment by SimpleSamples** [comment]
I suppose. I apologize but I forget why I asked.
