### ISSUE TITLE
CA1815 Explanation is Wrong for Blittable Types

### ISSUE THREAD

**Issue by tapiester** [MicrosoftDocs/visualstudio-docs#5863]
The explanation of CA1815 (Override equals and operator equals on value types) on Microsoft Docs says the following:

>For value types, the inherited implementation of Equals uses the Reflection library... Reflection is computationally expensive...

However, this is **not true** for blittable types. The documentation should be updated accordingly.

(The analyzer probably should be updated too, but this issue is just about the doc)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5197777a-4320-d8ad-1da5-44fbe2087c01
* Version Independent ID: 70e92335-5785-e967-75d0-9f736b6fba26
* Content: [CA1815: Override equals and operator equals on value types - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1815)
* Content Source: [docs/code-quality/ca1815.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1815.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated content links

**Comment by Mikejo5000** [comment]
Moved issue to .NET
Closing this in favor of [https://github.com/dotnet/docs/issues/22032](https://github.com/dotnet/docs/issues/22032)
