### ISSUE TITLE
Simple typo (of instead of if)

### ISSUE THREAD

**Issue by kdethlefs** [MicrosoftDocs/visualstudio-docs#5869]
"You can set a different port number of you like." was probably meant to be "You can set a different port number if you like."

Simple typo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c19e4f-4623-c462-e399-008a85ea1523
* Version Independent ID: bc0b82bb-acc8-7438-7b18-5165de39d847
* Content: [Remote Debugger Port Assignments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugger-port-assignments?view=vs-2019)
* Content Source: [docs/debugger/remote-debugger-port-assignments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugger-port-assignments.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@kdethlefs -- Kevin, thank you for catching this typo.  

@Mikejo5000 -- Mike, please review a tiny [private PR 7177](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7177).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
