### ISSUE TITLE
No mention of command-line switch: /bl

### ISSUE THREAD

**Issue by tomuxmon** [MicrosoftDocs/visualstudio-docs#587]
Binary and Structured Log is already a part of MSBuild

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab4c199-c44d-b8c6-9bf5-5500a30a6992
* Version Independent ID: ed692025-4ede-d7f1-be2f-6ee1f8ce16eb
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/obtaining-build-logs-with-msbuild.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Working on this
