### ISSUE TITLE
"Place 'System' directives first when sorting usings" option is broken

### ISSUE THREAD

**Issue by JunyiYi** [MicrosoftDocs/visualstudio-docs#5875]
The option is not working on
> Microsoft Visual Studio Enterprise 2019
  Version 16.7.3

Here I have turned on this option.
![image](https://user-images.githubusercontent.com/6908392/93402628-29b8f400-f83a-11ea-8c6a-1cc68538e8a1.png)

But when I click the "Remove and Sort Usings" in the context menu of a C# code file:
![image](https://user-images.githubusercontent.com/6908392/93402717-5e2cb000-f83a-11ea-955f-bdd91ce3b445.png)

It moves all System usings to the end of the using block.
![image](https://user-images.githubusercontent.com/6908392/93402765-78668e00-f83a-11ea-9008-b092094b37d9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f41602f7-2c5e-bf2a-9eab-50740dd10784
* Version Independent ID: c6b1f7c4-eb2d-a62a-7e1b-eb32b8a88947
* Content: [Options, Text Editor, C#, Advanced - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-csharp-advanced?view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-csharp-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-csharp-advanced.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @akhera99
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@JunyiYi -- Junyi, thank you for your feedback.  This may be a product-related issue rather than a documentation issue.  I am looking into this article.

**Comment by JunyiYi** [comment]
Thanks @WilliamAntonRohm , yes it is actually a product issue rather than the document issue.

**Comment by WilliamAntonRohm** [comment]
@JunyiYi -- Junyi, thank you for clarifying.  Please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report this issue. 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
