### ISSUE TITLE
Typo in the text

### ISSUE THREAD

**Issue by ZhabinDA** [MicrosoftDocs/visualstudio-docs#5876]
Under "Use the Disassembly window" typo, two identical options "under Tools> Options (or Tools> Options)> Debugging"
https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-disassembly-window?view=vs-2019#use-the-disassembly-window

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e06a8c0-39c1-de75-efe3-1f2091a75e5b
* Version Independent ID: 196d81a3-691f-e36a-cc0f-504fcce8daa1
* Content: [View Disassembly Code in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-disassembly-window?view=vs-2019)
* Content Source: [docs/debugger/how-to-use-the-disassembly-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-use-the-disassembly-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review [private PR 7186](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7186).
