### ISSUE TITLE
Blend for visual studio 2019 does not contain some shapes in asset window

### ISSUE THREAD

**Issue by Jcardif** [MicrosoftDocs/visualstudio-docs#5877]
Tried to create the path on Visual studio 2019 using the information provided on this page but there are only two shapes on my version of visual studio 2019. 

![image](https://user-images.githubusercontent.com/29174946/93469689-816a6480-f8f9-11ea-988b-88d5c56fbf98.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0301c8-416c-59be-43a1-b5489716e50b
* Version Independent ID: c20b4f11-e646-5ba3-d5c7-82a753c4eef3
* Content: [Draw shapes and paths - Blend for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/draw-shapes-and-paths?view=vs-2019)
* Content Source: [docs/xaml-tools/draw-shapes-and-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/draw-shapes-and-paths.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Jcardif You're right; we've updated the screenshot on the [**Draw shapes and paths**](https://docs.microsoft.com/visualstudio/xaml-tools/draw-shapes-and-paths) page. Thanks for helping us improve the documentation!

(As an FYI, there is a related  [**Developer Community**](https://developercommunity.visualstudio.com/spaces/8/index.html) post, [_Missing drawing assets polygons, paths, polyline and lines in Shapes Asset window_](https://developercommunity.visualstudio.com/content/problem/795343/missing-drawing-assets-polygons-paths-polyline-and.html), which mentions an SDK that you might consider downloading and installing.)
