### ISSUE TITLE
Links to page describing configuring Server 2012

### ISSUE THREAD

**Issue by chrisgull** [MicrosoftDocs/visualstudio-docs#5878]
Page is about setting up a development environment, which would typically be a client OS - Windows 10 these days - but the link  "IIS 8.0 Using ASP.NET 3.5 and ASP.NET 4.5" describes configuring Server 2012, which is quire different in configuration than Windows 10. Perhaps an update is warranted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f92897-6665-8360-154d-7de43c557dfc
* Version Independent ID: 6916e374-6a55-39bf-6858-a13314e69fe8
* Content: [Enable debugging for ASP.NET apps - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-enable-debugging-for-aspnet-applications?view=vs-2019)
* Content Source: [docs/debugger/how-to-enable-debugging-for-aspnet-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-enable-debugging-for-aspnet-applications.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@chrisgull Yes, that topic is focused on WS, not Windows. I can clarify that in the docs. I'm not aware of docs that show the configuration steps on Windows 10, which in general is out of scope here for the VS docs.
