### ISSUE TITLE
target a specific installation-directory of .NET instead of defaulting to the GAC

### ISSUE THREAD

**Issue by optikos** [MicrosoftDocs/visualstudio-docs#588]
This WWWpage does not mention any way to target a specific installation-directory of, say, V4.0 .NET assemblies instead of defaulting to the Global Assembly Cache (which is malfunctioning in 2 projects (out of 17) when building Mono's current Embeddinator-4000 from a totally fresh install.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a80e5d7-2db7-48c0-e8b6-ca8c3ff30017
* Version Independent ID: ad64635b-06d5-1b87-8f02-80cf25c12520
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/msbuild-target-framework-and-target-platform.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, do you have any input on this issue?

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, do you know if there's a way to do this?

**Comment by rainersigwald** [comment]
I'm not sure I understand the question. If it's "is it possible to remove the GAC as a resolution source for bare references" the answer is yes, by removing `{GAC}` from `$(AssemblySearchPaths)` (it is there by default).

**Comment by Mikejo5000** [comment]
We will need more context for this before making a doc change. Closing for now.
