### ISSUE TITLE
'c' specifier original watch value

### ISSUE THREAD

**Issue by brucekaskel** [MicrosoftDocs/visualstudio-docs#5881]
Original Watch Value for 'c (single character)' indicates <location> which seems wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a5c135d-ace1-1f09-041a-13411c054ff3
* Version Independent ID: 083fc572-d877-2216-19a9-326636c1d8e6
* Content: [Format specifiers in the debugger (C++) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-cpp?view=vs-2019)
* Content Source: [docs/debugger/format-specifiers-in-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/format-specifiers-in-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review [private PR 7192](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7192).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
