### ISSUE TITLE
Ok to suppress for TryParse

### ISSUE THREAD

**Issue by JasonCard** [MicrosoftDocs/visualstudio-docs#5883]
Moving issue from [https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/94](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/94) as it's feedback for English content.

Matti-Koopa commented 8 days ago
Shouldn't this rule be ok to suppress for own "TryParse"-methods? I think the article should add that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89b0f64-db03-af39-fdf7-ccb31c9ae01b
* Version Independent ID: 95c4aac2-4e98-240b-54e5-64981ab68cec
* Content: [CA1031: Do not catch general exception types - Visual Studio](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1031)
* Content Source: [docs/code-quality/ca1031.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/ca1031.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated content links.

**Comment by Mikejo5000** [comment]
Ported issue to .NET.
Closing this in favor of [https://github.com/dotnet/docs/issues/22030](https://github.com/dotnet/docs/issues/22030)
