### ISSUE TITLE
Last step(s) missing

### ISSUE THREAD

**Issue by JasonCard** [MicrosoftDocs/visualstudio-docs#5884]
Moving issue from [https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/90](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/90) as it's feedback for English content.

Beautyod commented on Jul 20
Nice article, but a little bit incomplete.
I recommend to add the further step(s), where you select a project and directory.
At the end of the article I would show the result: An "extended" Team Explorer view, which now shows "Builds" and "Tasks".

Thanks (-:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22f31dd7-e676-aa47-cb11-8ad77412fb5a
* Version Independent ID: 6cce7a4b-8f62-610d-f75f-fafc7b4c444a
* Content: [Connect to projects in Team Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/connect-team-project?view=vs-2019)
* Content Source: [docs/ide/connect-team-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/connect-team-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@JasonCard Respectfully, we must decline to update the [Connect to projects in Team Explorer](https://docs.microsoft.com/visualstudio/ide/connect-team-project?view=vs-2019) page exactly as you've requested. Instead, we've added a link to it to another, newer page, [Compare Git and Team Explorer side-by-side](https://docs.microsoft.com/visualstudio/ide/git-team-explorer-feature-comparison?view=vs-2019), which includes most of what you described that you wanted to see. The link should appear within 12 hours of this reply.

We'll close this issue now, with our thanks to you for helping us improve the documentation!
