### ISSUE TITLE
mstest /testsettings runsettings config file format

### ISSUE THREAD

**Issue by JasonCard** [MicrosoftDocs/visualstudio-docs#5885]
Moving issue from [https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/89](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/89) as it's feedback for English content.

Hi

you defined the Format for the runsettings file in here:
https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

This leads to (Just all structures made empty):
The file '...\mstest\default.runsettings' has unknown format and cannot be converted to the current version.

There is no information about "Local.runsettings". I just would like to find a simple empty Format or Format description for that content of that file. The error message is totally useless for that purpose.

Why do you not provide a download for an easy Local.runsettings and Maybe a complex one. (I just want to add one single Parameter into the TestContext.Properties to configure a set of unit Tests. And this Parameter shall be defined in the Local.runsettings. Where else?)

Best regards
fi

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27af73d-196c-4653-aa07-acf7e8b425e3
* Version Independent ID: b8957d80-ffa0-1c42-d3f0-6e4d00bf7a1e
* Content: [VSTest.Console.exe command-line options - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2019)
* Content Source: [docs/test/vstest-console-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/vstest-console-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by JasonCard** [comment]
Mikejo5000 commented on Jul 17 • 
@fifromrs Local.Runsettings is just a filename for a .runsettings file, normally placed in the project root. I can clarify this in the doc. I tested TestContext.Properties using a basic .runsettings file like the following, which seems to work fine when I test it.

<?xml version="1.0" encoding="utf-8"?>

<RunSettings>
<RunConfiguration>
<ResultsDirectory>.\TestResults</ResultsDirectory>
</RunConfiguration>
<TestRunParameters>
<Parameter name="docsUrl" value="https://docs.microsoft.com" />
</TestRunParameters>
</RunSettings>

and this code:

private string docsUrl;
public TestContext TestContext { get; set; }

[TestMethod]
public void TestMethod1()
{
docsUrl = TestContext.Properties["docsUrl"].ToString();
}

@Mikejo5000 Mikejo5000 mentioned this issue on Jul 17
[https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6874](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/6874)
 Merged
 
Mikejo5000 commented on Jul 17
Updating doc

**Comment by JasonCard** [comment]
@Mikejo5000 I moved the issue from [https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/89](https://github.com/MicrosoftDocs/visualstudio-docs.de-de/issues/89), but it looks like you may have already addressed this issue. Please go ahead to close if already resolved.

**Comment by fifromrs** [comment]
Hello Mr. Jones,

I just add a sample of the results, I got from you, to this mail. And really, mstest /testsettings does not work with it. If you configure it in Visual Studio with Visual Studio Unit Testing, the RunSettings file works. But the test is started using mstest within a  Jenkins job…


With that command line:
mstest /testcontainer:My.dll /test:MyClass.MyFunction /testsettings:"c:\temp\TestRunSettings.runsettings"

I get the following error:
Loading c:\temp\TestRunSettings.runsettings...
c:\temp\TestRunSettings.runsettings
The file ' c:\temp\TestRunSettings.runsettings ' has unknown format and cannot be converted to the current version.

If the path is invalid, the system returns, the path for the settings file is invalid. But here, the format is wrong. But I used the format, as you have shown in your examples, attached to this mail.

And sadly, there is no better hint. How to get a correctly formatted file for mstest /testsettings command line argument??? I would like to get the data as described in our mail communication within this chat…

Best regards,
Dirk Fischer

**Comment by Mikejo5000** [comment]
@pavelhorak @AbhitejJohn Are there any odd issues with using .runsettings along with Jenkins? I have not been able to repro this issue, but I wasn't using Jenkins.

**Comment by AbhitejJohn** [comment]
ah, mstest.exe is a legacy runner which does not understand runsettings. You'd want to use vstest.console.exe instead from a VS install directory (<VSInstallDir>\Common7\IDE\Extensions\TestPlatform\vstest.console.exe) or [this](https://www.nuget.org/packages/Microsoft.TestPlatform) package.
/cc: @nohwnd, @pavelhorak

**Comment by Mikejo5000** [comment]
Thanks! That makes sense; in my own tests, I was using vstest.console.exe, per the instructions in the docs. Closing this for now, unless another issue comes up.

**Comment by fifromrs** [comment]
Hi Mr. John, Mr. Jones,

Thanks for your responses!

I would like to use vstest.console.exe, but there is no Jenkins plugin, which can analyse and interpret vstest.console.exe results output. It is available, even if not very well done, for mstest.
Thererfore, what is the format of the /testsettings file. Is there any (easy) example?

Best regards
Dirk Fischer

**Comment by pavelhorak** [comment]
@fifromrs  can you use [https://plugins.jenkins.io/vstestrunner/](https://plugins.jenkins.io/vstestrunner/) Jenkins plugin with VSTest.Console.exe.

**Comment by pavelhorak** [comment]
no need

**Comment by fifromrs** [comment]
Hi Mr. Horak,

sadly, vstest.console.exe is not as stable as expected…. and as mstest.exe is…
[cid:image001.png@01D6B818.7761EAC0]

I have a deadlock when using vstest.console.exe with the scenario above.

Therefore, I would really like to know, … what is the format of mstest’s file “mysettings.testsettings” for parameter “/testsettings:mysettings.testsettings”?

Sorry for my seemingly never ending requests…

Best regards,
Dirk Fischer
