### ISSUE TITLE
Add details for working with a different test root directory

### ISSUE THREAD

**Issue by YZN3RF** [MicrosoftDocs/visualstudio-docs#5887]
As I just found out in https://github.com/microsoft/PTVS/issues/5851#issuecomment-547185604 , you could add the following to this page:
* Only the directory configured in Project Properties > Test > Root directory will be searched for tests by the Test Explorer. Sub directories of the configured root directory will *not* be searched.
* If a sub directory of the project folder is configured as Test > Root directory (e.g. tests), you need to add an empty `__init__.py` file in the sub directory (e.g. `tests\__init__.py`). Otherwise the Test Explorer will not be able to import the test files.
This is true for working with unittest and Visual Studio 16.4.3.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
* Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
* Content: [Unit test Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/unit-testing-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/unit-testing-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by sterred** [comment]
Update: solution has been found: by using as **Root Directory** the main folder and two dots as subfolder, it will discover all tests in all subfolders under the main folder! (**test\\..**)
![image](https://user-images.githubusercontent.com/71386513/94654625-9ed9fe00-02fd-11eb-8c09-8f7300e26074.png)

**Comment by YZN3RF** [comment]
> Update: solution has been found: by using as **Root Directory** the main folder and two dots as subfolder, it will discover all tests in all subfolders under the main folder! (**test\..**)

Yes, by using `my_test_script_sub_directory\..` or simply `my_root_directory` as "Root directory" in the test configuration, the Test Explorer does actually find scripts in all sub directories.
But even with that solution, an `__init__.py` file does still need to exist in each sub directory.

**Comment by rjmolyneaux** [comment]
Hi @YZN3RF, it appears that a resolution has been found for part of your issue! We have since then updated the docs and will bring this suggestion to the team's attention. 

Thank you very much for notifying us of this pain-point and helping us improve Microsoft documentation.
