### ISSUE TITLE
CA1051: Mention the new configurability option

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#5888]
Following PR https://github.com/dotnet/roslyn-analyzers/pull/4162 there will be a new option to disable the rule for `struct`. The documentation page shall be updated accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c9be9f4-407a-3a19-67bf-1e979541a877
* Version Independent ID: bc1d7314-c55a-a831-0640-9350c0e55dfc
* Content: [CA1051: Do not declare visible instance fields - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1051?view=vs-2019)
* Content Source: [docs/code-quality/ca1051.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1051.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
The option has been added, so closing this issue.

https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1051#exclude-structs
