### ISSUE TITLE
MSBuild Project Properties: Enhance documentation for OutputType and DisableWinExeOutputInference

### ISSUE THREAD

**Issue by StevenBonePgh** [MicrosoftDocs/visualstudio-docs#5893]
OutputType documentation should be expanded to indicate that in some cases it can be silently changed due to inferencing. Mentioning the setting DisableWinExeOutputInference will get bonus points and hopefully save the next poor individual who encounters this new and breaking behavior when migrating to new sdk project format.

See https://github.com/dotnet/sdk/issues/13331

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by gewarren** [comment]
Consider adding a see also link to https://docs.microsoft.com/en-us/dotnet/core/compatibility/windows-forms/5.0/automatically-infer-winexe-output-type.
