### ISSUE TITLE
Please describe HelpKeyword in more detail

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/visualstudio-docs#5894]
The current doc's say: 
>`HelpKeyword` : Optional String parameter. The Help keyword to associate with the error.

Which kind of is not very helpful.

Please document what can and can't be done using `HelpKeyword`.

(e.g. I can "see" that whatever I input there it seems to always redirect to `docs.microsoft.com`. Is there any way to get this to link to somewhere else?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92240a7d-b3d0-997d-4608-0cbf9b0772b8
* Version Independent ID: 730a0427-8083-e401-0f3b-6b75b9c6f94a
* Content: [Error Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/error-task?view=vs-2019)
* Content Source: [docs/msbuild/error-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/error-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@nils-a I think this is used by Visual Studio to generate an F1 query, which are exclusively processed by docs.microsoft.com, so if that's the case, there's no way to direct this traffic anywhere else, or any way to add user keywords.

**Comment by nils-a** [comment]
> I think [...]

This illustrates my point, doesn't it. 😄 

For me, adding `HelpKeyword` will always result in a link to `https://msdn.microsoft.com/query/dev16.query?appId=Dev16IDEF1&l=EN-US&k=k(MY-KEYWORD-HERE)&rd=true`.
If that is really the case, and there is nothing to do about it then the docs shoutd read *"Internal use by Microsoft. Nothing can be gained by using this property."* (or something like it...)

(The thing is.. When developing a roslyn analyser, there is a `HelpLink`, which will create a nice linkt to whatever url is given - so I'm guessing this is not only Visual Studio doing things here...)

**Comment by nils-a** [comment]
@ghogen in https://github.com/dotnet/msbuild/issues/4029 @davkean writes:
> HelpKeyword has a different meaning; it means the keyword that we use to look up a help topic in help.

So it seems, that the documentation really should read something along the lines of *"Keyword to a help-topic. Visualization of this keyword is build-system dependent. For Visual Studio this points to a Keyword-Search on msdn.microsoft.com."*

**Comment by nils-a** [comment]
Action is still required.
