### ISSUE TITLE
Connecting Dot Net Applications to  R

### ISSUE THREAD

**Issue by yusufmsalh** [MicrosoftDocs/visualstudio-docs#590]
let's say I have a project like an MVC project ,I want to 
*preform summary statistics using R on a Column (SQl DB).
*Display the summary on MVC page.
How Visual Studio 2017 may help me ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11431a6-8401-2c63-b53c-e7f489b08ba7
* Version Independent ID: 1f8a17a4-122f-b2ef-f866-87dfdeaf3332
* [Content](https://docs.microsoft.com/en-us/visualstudio/rtvs/)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/rtvs/index.md)
* Service: unspecified

**Comment by kraigb** [comment]
What's presently available is the ability to embed R code within SQL stored procedures, which you should then be able to invoke from any other application through SQL queries.

See https://docs.microsoft.com/en-us/visualstudio/rtvs/integrating-sql-server-with-r#working-with-sql-server-stored-procedures.
