### ISSUE TITLE
Documentation for OLE/COM Object Viewer for Visual Studio 2019 is missing

### ISSUE THREAD

**Issue by rossmpersonal** [MicrosoftDocs/visualstudio-docs#5903]
[Enter feedback here]

Documentation for OLE/COM Object Viewer for Visual Studio 2019 is missing. Please provide it.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e85674-5e2a-1a40-158b-14bad23ea47f
* Version Independent ID: 4666f4d3-3a21-1694-c879-9f53afcf182c
* Content: [COM Debugging Tools - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/com-debugging-tools?view=vs-2019)
* Content Source: [docs/debugger/com-debugging-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/com-debugging-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rossmpersonal This looks like a tool in the Windows SDK. Have you been using this tool on Windows 10? What I see so far looks like it has likely been deprecated. The link from this topic:
https://docs.microsoft.com/en-us/windows/win32/com/ole-com-object-viewer
Goes to an archived VS 2017 topic here:
https://docs.microsoft.com/en-us/previous-versions/d0kh9f4c(v=vs.140)

**Comment by Mikejo5000** [comment]
No longer supported?
https://superuser.com/questions/1128768/oleview-not-available-on-windows-10

**Comment by Mikejo5000** [comment]
Looks like the tool is no longer supported. If you would like to see this changed, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by rossmpersonal** [comment]
Where is the official Microsoft documentation that it is unsupported?

**Comment by Mikejo5000** [comment]
@rossmpersonal Thanks for the feedback. I did just find it under C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86\oleview.exe, so that suggests it is still supported. It is a Windows SDK tool, so they would need to evaluate whether doc'ing the tool is a priority for them. If you still would like to see docs for this, please open the issue under:
https://docs.microsoft.com/en-us/windows/win32/com/ole-com-object-viewer

**Comment by rossmpersonal** [comment]
There is no place to open an issue under https://docs.microsoft.com/en-us/windows/win32/com/ole-com-object-viewer . Why should I do?

**Comment by Mikejo5000** [comment]
Looks like you're right; issues aren't enabled for those docs. Please use the Report a Problem link above and ask for docs for the viewer. Thanks!
