### ISSUE TITLE
The $attach command has been removed

### ISSUE THREAD

**Issue by agoodwin** [MicrosoftDocs/visualstudio-docs#5906]
Hi,

This page of documentation briefly mentions an `$attach` command, which seems to no longer exist - as described here:

https://github.com/microsoft/PTVS/issues/4636

So I suppose this should be removed from the documentation, and/or the documentation could be updated to describe whatever is the current way to debug Python code run from an interactive Window.

The same link above includes some alternatives to the `$attach` command, which I haven't tried yet, but at first glance none seem as easy as the `$attach` command so I wouldn't want to specify what I think is the "correct" thing to document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a426e3db-8d10-e7d2-0957-5eb07d28e76d
* Version Independent ID: e54ea195-0592-0424-a5b1-54dba78257e4
* Content: [Python interactive window (REPL) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/python-interactive-repl-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/python-interactive-repl-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/python-interactive-repl-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @agoodwin - Thanks for pointing out this change. I've updated the docs to remove the `$attach` from the Visual Studio 2019 version.
