### ISSUE TITLE
Inconsistent examples

### ISSUE THREAD

**Issue by j2associates** [MicrosoftDocs/visualstudio-docs#5907]
This topic is very helpful, but it is needlessly confusing because in the one example the Book has a Text property and in the other example the Book has a Title property. The properties should be the same in both cases so that the only changes are the ones used to fix the badly implemented code.

Thanks
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2abbde5-ab63-5722-cb28-80ef50e7b081
* Version Independent ID: a3c27bfe-3129-5d73-dd1e-ab7254fd7e47
* Content: [CA2240: Implement ISerializable correctly - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2240?view=vs-2019)
* Content Source: [docs/code-quality/ca2240.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2240.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Currently this rule only exists in the legacy analyzers.

**Comment by Mikejo5000** [comment]
Thanks for the feedback! Updating sample. It should go live by end of day, 12/17.
