### ISSUE TITLE
There needs to be a clear and concise definition of a "Solution Folder" in Visual Studio.

### ISSUE THREAD

**Issue by CLIRResearch** [MicrosoftDocs/visualstudio-docs#5908]
There needs to be a clear and concise definition of a solution folder in Visual Studio.  

Entries in a project file often contain path specifications that reference the "Solution Folder".  Without a clear and concise definition of the "Solution Folder", checking the paths is an exercise in guess-work.

For example, we recently lost a good chunk of time diagnosing a problem with NuGet packages.  NuGet said the packages were there. The Build said the packages are missing.  When you unload the project to find out where the project thinks the package is, all paths are references to the solution folder. 

There needs to be a hard, clear and concise rule for identifying the solution folder.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@CLIRResearch We've added information about the solution folder, here: https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2019#solution-folder. We hope that this information proves useful, and regret that it wasn't available when you needed it. That being said, we'll close this now, with our thanks to you for helping us improve the documentation!
