### ISSUE TITLE
Delete and redirect CAxxxx rules reference

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#5911]
Once https://github.com/dotnet/docs/pull/20702 is published, the CAxxxx code quality rules reference docs in this repo should be deleted and redirected. Is there anything that we need to do for F1 and for the links from the Error List when users hit these warnings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06de1bb8-181e-9d03-6109-9e8389414e98
* Version Independent ID: bff2b131-67f5-ba4e-f413-da452761b19d
* Content: [Code quality rules overview - .NET](https://review.docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/rules/quality-rules-reference?branch=pr-en-us-20702)
* Content Source: [docs/fundamentals/code-analysis/rules/quality-rules-reference.md](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/rules/quality-rules-reference.md)
* Product: **dotnet**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by gewarren** [comment]
Also can delete this file, except perhaps the part about predefined rule sets if they don't apply to the .NET SDK.

https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-fxcop-analyzers?view=vs-2019

**Comment by mikadumont** [comment]
@gewarren can you do the redirects and delete the files? I will create an issue on Roslyn to redirect F1 and for the links from the Error List.

**Comment by gewarren** [comment]
The rules have been deleted and redirects put in place by Manish in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7239. So I think this issue can be closed if Mika is going to track the Roslyn work separately.

**Comment by mikadumont** [comment]
@gewarren here is the issue for CA diagnostic linking to docs: https://github.com/dotnet/roslyn-analyzers/issues/4286
