### ISSUE TITLE
The docs for Find-In-Files are completely outdated wrt. VS 2019

### ISSUE THREAD

**Issue by bilbothebaggins** [MicrosoftDocs/visualstudio-docs#5912]
The docs for Find-In-Files are completely outdated wrt. VS 2019!
You rewrote the dialog -- https://devblogs.microsoft.com/visualstudio/modernizing-find-in-files/ -- but forgot to add new documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e27881f-04bc-b7ba-e217-8360278a14f8
* Version Independent ID: d31c8050-339a-688c-869e-ff7942fd3f74
* Content: [Find in Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2019&source=docs)
* Content Source: [docs/ide/find-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/find-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@bilbothebaggins Yes; you're right. The good news is that we're working on updating that documentation as I write this. I'll respond when it's complete and published, at which time we'll close this issue.

**Comment by TerryGLee** [comment]
@bilbothebaggins We've updated the [Find in Files](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2019) page to reflect the new UI (user interface) and functionality for Visual Studio 2019; we'll close this now with our thanks for your inquiry and interest in helping us improve the documentation.
