### ISSUE TITLE
what to name the .ts files.?  

### ISSUE THREAD

**Issue by edthehorse** [MicrosoftDocs/visualstudio-docs#5915]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31cd207e-b406-7db7-70f3-babadbd78008
* Version Independent ID: ffd57744-3aa5-5ed4-0f64-e9da6f62b2bd
* Content: [Compile and build TypeScript code using NuGet - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/compile-typescript-code-nuget?view=vs-2019)
* Content Source: [docs/javascript/compile-typescript-code-nuget.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/compile-typescript-code-nuget.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@edthehorse You can name them anything. Did you run into an issue with naming a .ts file?

**Comment by edthehorse** [comment]
thanks for telling me that. How to  "run " the ts/js? refer to them from
an html page?

On 24/09/2020 23:37, Mike Jones wrote:

> @edthehorse [1] You can name them anything. Did you run into an issue with naming a .ts file? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].
 

Links:
------
[1] https://github.com/edthehorse
[2]
https://github.com/MicrosoftDocs/visualstudio-docs/issues/5915#issuecomment-698623721
[3]

**Comment by Mikejo5000** [comment]
I see. I should add some links here. The Visual Studio commands are described in the quickstarts and tutorials. You might go through one of these docs to learn more. Here's a section on "running" the app:

https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-nodejs?toc=%2Fvisualstudio%2Fjavascript%2Ftoc.json&view=vs-2019#run-the-application

**Comment by Mikejo5000** [comment]
Adding links to the doc

**Comment by Mikejo5000** [comment]
Fixed in MicrosoftDocs/visualstudio-docs-pr/pull#7293
