### ISSUE TITLE
Include guide for .NET Core 3.1 web project

### ISSUE THREAD

**Issue by Ogglas** [MicrosoftDocs/visualstudio-docs#5919]
Could you please write a guide on how to integrate with a .NET Core 3.1 web project? Got it working with a Node.js Console Application but that was not straight forward either. See my reply on SO:

https://stackoverflow.com/a/64064559/3850405

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32738a06-835b-5bd5-7a6c-942c681aca97
* Version Independent ID: e715d12c-a4aa-eec3-c05f-1ff6243d209b
* Content: [Unit testing JavaScript and TypeScript - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2019)
* Content Source: [docs/javascript/unit-testing-javascript-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/unit-testing-javascript-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Ogglas Thanks for the suggestion. I will add it to the backlog, and try to take a look at this soon.

**Comment by Mikejo5000** [comment]
Doc update coming. For now, see this:

MicrosoftDocs/visualstudio-docs#6306

**Comment by Mikejo5000** [comment]
Updated the doc with a new section for ASP.NET Core & JS/TS. Let me know if I missed anything.
[Write unit tests for ASP.NET Core](https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2019&tabs=mocha#write-unit-tests-for-aspnet-core)
