### ISSUE TITLE
Incorrect advice re PyLint

### ISSUE THREAD

**Issue by Richard210363** [MicrosoftDocs/visualstudio-docs#5925]
This part:
"On the command line, navigate to your project root (which has your .pyproj file) and run the following command to generate a commented configuration file:

command:  pylint --generate-rcfile > .pylintrc"

simply isn't true.  pylint won't be recognised as a command.

The correct command is:

py -m pylint --generate-rcfile > .pylintrc
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42523e4f-5af1-7e09-74df-a1b9c3a228d4
* Version Independent ID: f82e07ad-c4e8-6789-0952-7c739d437e27
* Content: [Use PyLint for Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/linting-python-code?view=vs-2019)
* Content Source: [docs/python/linting-python-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/linting-python-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@JoshuaPartlow -- Joshua, please review this change in [private PR 7257](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7257).

**Comment by JoshuaPartlow** [comment]
Hi @Richard210363 - Following the topic, my experience was that pylint was recognized without using the launcher with module flag. Perhaps your experience was because the pylint package wasn't installed for your default global environment?

**Comment by JoshuaPartlow** [comment]
Closing issue given timeframe with no reply, please reopen if this is still an issue.
