### ISSUE TITLE
RunEachTargetSeparately parameter of MSBuild task CallTarget is not an output parameter

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [MicrosoftDocs/visualstudio-docs#593]
`RunEachTargetSeparately` is listed as an *Optional Boolean **output** parameter* (emphasis added). It is an input parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 85c98183-151e-7f93-8463-34518c030861
* Version Independent ID: 36e2369d-f5cd-2024-f235-68b13aa2d7bf
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/calltarget-task#feedback)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/msbuild/calltarget-task.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@Joe-Sewell-PreEmptive Thanks! Making the fix

**Comment by Mikejo5000** [comment]
Verified
