### ISSUE TITLE
Connection type "Python remote(debugpy)" missing

### ISSUE THREAD

**Issue by ghaefele** [MicrosoftDocs/visualstudio-docs#5933]
Connection type "Python remote(debugpy)" missing. Need infos on debugpy and remote debugging on localhost.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91ab3b84-305b-434b-2155-b288fa98c973
* Version Independent ID: 22fb753b-a8a2-5572-03fd-9b98cd118c90
* Content: [Debug Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/debugging-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/debugging-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @ghaefele - Thank you for the feedback. The peer topic [Remotely debug Python code on Linux](https://docs.microsoft.com/en-us/visualstudio/python/debugging-python-code-on-remote-linux-machines) talks about `Python remote (debugpy)`. If that's not what you were looking for and you think this is an issue that should still be addressed, please feel free to reopen.
