### ISSUE TITLE
Download Zip link

### ISSUE THREAD

**Issue by ian1127** [MicrosoftDocs/visualstudio-docs#5936]
Get the App - https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application#get-the-app
"Download the ZIP" Link for code points to : http://localhost/assets/app.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ian1127 -- thank you for your feedback. This issue is being tracked in #5827.

**Comment by adrynov** [comment]
The link still does not work.

Just put the code to GitHub and be done with this issue, please

**Comment by WilliamAntonRohm** [comment]
@adrynov -- Andrei, please see the updated step 1 under [Get the App](https://docs.microsoft.com/visualstudio/docker/tutorials/your-application#get-the-app) for a clarification of the ZIP file's location.
