### ISSUE TITLE
Tokens for Other Languages

### ISSUE THREAD

**Issue by JediSQL** [MicrosoftDocs/visualstudio-docs#5941]
The (!) Note in the "Tokens and comments" section says "For other languages, see the Custom tokens section."
The "Custom tokens section" has no content with regards to using tokens with other languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1261884-8284-53f9-a325-15061bf897f8
* Version Independent ID: 4520c20f-86f6-5066-298b-d3d428901f87
* Content: [Use the Task List - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2019)
* Content Source: [docs/ide/using-the-task-list.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-the-task-list.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@JediSQL Thanks for letting us know; we'll look in to this and report back.

**Comment by TerryGLee** [comment]
@JediSQL We've updated the [Use the Task List](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2019) page; hopefully, it's clearer than it was before on how to create tokens for other programming languages. 

Specific changes include the following:
- We moved the Note about default tokens to the "Custom tokens" section
- We then changed the sentence that previously said "For other languages, see the Custom Tokens section" to now say "To create your own tokens for other programming languages, use the following steps."

Our thanks to you for helping to improve the documentation!
