### ISSUE TITLE
Does the GitHub Enterprise benefit apply to Partner subscriptions? 

### ISSUE THREAD

**Issue by DaveBurnisonMS** [MicrosoftDocs/visualstudio-docs#5942]
I got the following question from one of the Microsoft CSAs:
> Does this mean that partners who get VS though partner program will not be eligible for the **GitHub Enterprise** benefit. I got this question a couple of times.

There are other VS Subscriber benefits where this is spelled out, for example the Azure DevOps benefit for VS Subscribers: https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops#eligibility
![VS Benefits for Partners](https://user-images.githubusercontent.com/53453038/94974568-d4c8df00-04c3-11eb-98d1-14e9bf9afe09.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e0dbc2-35de-0efe-ae1b-b9d2507f2b4d
* Version Independent ID: f1e1caeb-78d3-262f-6311-6606720893a3
* Content: [Visual Studio with GitHub Enterprise](https://docs.microsoft.com/en-us/visualstudio/subscriptions/access-github)
* Content Source: [subscriptions/access-github.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/access-github.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@DaveBurnisonMS Hi Dave.  Thanks for reaching out.  The GitHub Enterprise bundle is offered only to EA customers,  It's a separate SKU, and is not included in any NFR offerings.

**Comment by evanwindom** [comment]
@please-close

**Comment by DaveBurnisonMS** [comment]
Closing as per @evanwindom's comments. Thanks for the clarification.
