### ISSUE TITLE
Directory.Solution.props and Directory.Solution.targets lack documentation

### ISSUE THREAD

**Issue by Adam-S-Daniel** [MicrosoftDocs/visualstudio-docs#5948]
https://github.com/dotnet/msbuild/issues/4784 _"Need Solution File extensibility point that works for multiple solution files"_ included the following:
> Finally, the feature should be documented here: https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

The feature, released on 2020/04/09 with MSBuild 16.4.0, does not appear to have been added to the documentation yet.

A good starting place for the content might be the commit comment on https://github.com/dotnet/msbuild/commit/b74f8ddfe5311585e09086cf12b2f9f3e0afec45:
> …gets (https://github.com/dotnet/msbuild/pull/4785)
> Implementation of https://github.com/dotnet/msbuild/issues/4784
>For the generated metaproj project this imports a file named `Directory.Solution.props` at the top and a file named `Directory.Solution.targets` at the bottom.
> This allows users to create a single file that lets them extend the building of all solution files in their repository.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by marcin-krystianc** [comment]
+1

**Comment by Adam-S-Daniel** [comment]
Can someone indicate why this issue was closed? @jeffkl @ghogen @rainersigwald

**Comment by rainersigwald** [comment]
@Adam-S-Daniel With my access I can see that there was a PR to an internal fork of the repo with docs that will be live on the docs site + merged back to public soonish.

**Comment by Adam-S-Daniel** [comment]
Ah! That’s great; thanks so much.
