### ISSUE TITLE
Please include information about NuGet package license expression

### ISSUE THREAD

**Issue by weitzhandler** [MicrosoftDocs/visualstudio-docs#5967]
Hi,

Please include information about the fields under License:

![image](https://user-images.githubusercontent.com/2716316/95691695-a49ee000-0c29-11eb-9835-6d0b3ec31047.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1490ea17-1bce-6eb1-0a78-1b8159b82e4e
* Version Independent ID: 4350b38b-6f06-16b6-da75-4d85c6c43909
* Content: [Assembly Information Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/assembly-information-dialog-box?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vb.ProjectPropertiesAssemblyInfo)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/reference/assembly-information-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/assembly-information-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@weitzhandler Thanks for your suggestion; we've added the following sentence to a Note about NuGet at the bottom of the page, as follows:

> And for more information about Licensing and Expressions as they relate to a NuGet package, see [licenses.nuget.org](/nuget/nuget-org/licenses.nuget.org/).

We'll close this issue now, with our thanks to you for helping us improve the documentation!
