### ISSUE TITLE
What are _actual_ commands to install SDK from command line?

### ISSUE THREAD

**Issue by thejonan** [MicrosoftDocs/visualstudio-docs#597]
The link provided points to general reference for command line arguments of VS. There is not a single word on `SDK` in that page. One would suggest checking in "Workloads IDs" description, but _no_ there's not such thing there either. Others may think that Building Tools will have that, but there will be negative surprise again. 

Can you, please, provide _meaningful_ descriptions when writing documentation? Thank you very much.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909713ca-f78f-1321-d2a0-01d9be22fd18
* Version Independent ID: 9f3298ff-4a82-da0e-2cf4-8e2a7439bc34
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/installing-the-visual-studio-sdk#installing-the-visual-studio-sdk-from-the-command-line)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/installing-the-visual-studio-sdk.md)
* Service: unspecified

**Comment by gregvanl** [comment]
Hi @thejonan The "Visual Studio extension development" workload ID is Microsoft.VisualStudio.Workload.VisualStudioExtension. We'll update the topic shortly to make this more explicit. Thanks for your feedback.

**Comment by thejonan** [comment]
Thank you for your reply. Unfortunately the referred workload is reported non available, when I try to install it on a machine that has VS Building Tools only. Which is why I needed this manual way of installation at the first place.

Going with PSH's: `Install-Package Microsoft.VSSDK.BuildTools` fails again with no success in finding the designated package. Is it impossible to have VSSDK on Building Tools? It sounds quite natural, when installing an automated building machine.
