### ISSUE TITLE
typo in the example code

### ISSUE THREAD

**Issue by adrianmikula** [MicrosoftDocs/visualstudio-docs#5971]
The following code example doesn't work. The correct package name should be Office.**Core**.DocumentProperties, not Office.DocumentProperties:

```
private string ReadDocumentProperty(string propertyName)
{
    Office.DocumentProperties properties;
```

Page affected: https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-create-and-modify-custom-document-properties?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b7941790-134c-39a5-d0e4-0df82f723870
* Version Independent ID: 11357b83-d186-2df2-f73e-adf79191ea9c
* Content: [How to: Create and modify custom document properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-create-and-modify-custom-document-properties?view=vs-2019)
* Content Source: [docs/vsto/how-to-create-and-modify-custom-document-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-create-and-modify-custom-document-properties.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@adrianmikula -- Adrian, in the third paragraph of that article:
- ... These properties return a DocumentProperties object...

That object name is a link, which goes to [DocumentProperties Interface](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.core.documentproperties?view=office-pia), which in turn clarifies the object hierarchy.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
