### ISSUE TITLE
Installing FxCop page is out of date

### ISSUE THREAD

**Issue by jpbulman** [MicrosoftDocs/visualstudio-docs#5972]
Currently, the [installing FxCop page ](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019) says that users should click the 'Code analysis' tab to install. However, in newer version of VS, visiting this tab will greet you with this page 
<img width="389" alt="deprecated" src="https://user-images.githubusercontent.com/12652192/95865648-e9636d80-0d34-11eb-9f32-baad7afe628a.PNG">

The docs should be updated to reflect this change and either remove this installation method (and suggest the custom one instead), or provide the new location where it can be installed through VS.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee67c1d-5856-93e0-e2d3-e9551436aabc
* Version Independent ID: b756aa96-bbb1-40e8-34ca-97f9939bf7e9
* Content: [Install FxCop analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-fxcop-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-fxcop-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-fxcop-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Doc has been updated.
