### ISSUE TITLE
Where is work item association during commit?

### ISSUE THREAD

**Issue by aaronhudon** [MicrosoftDocs/visualstudio-docs#5973]
How do you associate Azure DevOps work items during a commit? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb36e99-33ae-20a2-a12d-a3e5d056a153
* Version Independent ID: b5a43c4a-c8bb-2c8a-56b3-09b12a713e58
* Content: [New Git experience in Visual Studio (Preview)](https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @prnadago
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@prnadago FYI on this; thanks.

**Comment by Taysser-Gherfal** [comment]
You can associate work item during commit by using the "#" character. 

![image](https://user-images.githubusercontent.com/43084518/95902781-21c17680-0d4a-11eb-9809-c8690f1abfe1.png)

**Comment by aaronhudon** [comment]
> You can associate work item during commit by using the "#" character.
> 
> ![image](https://user-images.githubusercontent.com/43084518/95902781-21c17680-0d4a-11eb-9809-c8690f1abfe1.png)

Thanks!  Looks the documentation needs this secret feature!

**Comment by TerryGLee** [comment]
@aaronhudon Thanks for your inquiry; we've made an addition to the document that will be published later this afternoon. We'll close this issue now, with our thanks for helping us improve the documentation!
