### ISSUE TITLE
AssemblyResolution

### ISSUE THREAD

**Issue by mlop3s** [MicrosoftDocs/visualstudio-docs#598]
AssemblyResolution is wrongly documented. It should read: <AssemblyResolution> <Directory path="D:\myfolder\bin\" includeSubDirectories="false"/> </AssemblyResolution>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Service: unspecified

**Comment by mlop3s** [comment]
Somehow, my  example was cutoff. This is the correct way: Directory path="D:\myfolder\bin\" includeSubDirectories="false"

**Comment by gewarren** [comment]
@mlop3s thanks so much for reporting this. It's fixed now.
