### ISSUE TITLE
Information messages may have changed since this page was generated

### ISSUE THREAD

**Issue by d-c-d** [MicrosoftDocs/visualstudio-docs#5980]
The text and screen shots on this page about the yellow informational bar at the top of the designer 
The page indicates
  Scaling on your main display is set to 200% (192 dpi). This might cause rendering problems in the designer window.
( ignoring the actual scale values - ( I can't get 200% scaling choices ), I see an updated message 
 Scaling on your main display is set to 125%.      Restart Visual Studio with 100% scaling      Help me decide      

Looks like this page is out of date with Visual Studio?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2019)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@d-c-d Thanks for taking the time to write up this issue, and apologies for our delayed response.

The good news is, we've updated the screenshot on the [Disable DPI-awareness to address scaling issues with Windows Forms Designer in Visual Studio](https://docs.microsoft.com/visualstudio/designers/disable-dpi-awareness) page, as well as its supporting text, to reflect your feedback.

We'll close this issue now, with our additional thanks to you for helping to improve the documentation!
