### ISSUE TITLE
expired play with docker link

### ISSUE THREAD

**Issue by shivsasan** [MicrosoftDocs/visualstudio-docs#5984]
the "Play with Docker" link is wrong the corrent link is: https://labs.play-with-docker.com/
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d47baca-b80e-9315-f92f-83458b56b636
* Version Independent ID: 2936e948-5b26-9d56-1784-101a326b6928
* Content: [Docker tutorial - Part 3: Share your app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/share-your-app)
* Content Source: [docker/tutorials/share-your-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/share-your-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@shivsasan -- thank you for your feedback.  The existing link resolves to your suggested URL.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
