### ISSUE TITLE
Incorrect download link for sample app

### ISSUE THREAD

**Issue by pirey** [MicrosoftDocs/visualstudio-docs#5985]
![image](https://user-images.githubusercontent.com/10344542/96086964-4efa5a00-0eed-11eb-8e1a-67c0b3315db4.png)

The link in [this section](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application#get-the-app) points to http://localhost/assets/app.zip which couldn't be accessed by visitors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@pirey -- Yeri, thank you for your feedback. This issue is being tracked in #5827.
