### ISSUE TITLE
Unable to report error from outside VS 2019

### ISSUE THREAD

**Issue by kam1986** [MicrosoftDocs/visualstudio-docs#5986]
Hey

I got a problem.

can't report an critical error with VS 2019 since I can't launch it, can't reinstall it, can't nothing but manually wipe it from disk file by file.

How do I report an error when it wont start at all. no startup logo, nothing..

The only thing that happens since it launched last was updating Windows

**Comment by WilliamAntonRohm** [comment]
@kam1986 -- Kasper, thank you for your feedback.  Please try the suggestions in the following article:
- https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019#get-support

Let us know if you are successful.
