### ISSUE TITLE
Wrong method example in documentation

### ISSUE THREAD

**Issue by anato-s** [MicrosoftDocs/visualstudio-docs#5997]
Expected example for `GetPathOfFileAbove`
Actual example for - `GetDirectoryNameOfFileAbove`

[This microsoft documentation page](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2017)

**Comment by ghogen** [comment]
@anato-s It looks like this is fixed now. Please reactivate if that's not the case.
