### ISSUE TITLE
Can't Access Zip File

### ISSUE THREAD

**Issue by rhornjr** [MicrosoftDocs/visualstudio-docs#5998]
When I click the link to download the zip, I get a 404.
http://localhost/assets/app.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@rhornjr -- Bob, thank you for your feedback. This issue is being tracked in #5827.

**Comment by rhornjr** [comment]
I looked at that issue and it didn't help me. It says this:

"After running the setup command, I was able to access the app.zip file at 'http://localhost/assets/app.zip' "

What setup command? `docker run`?

I ran that. And the issue states the person was able to access the file at that URL. But I still can't. It needs to be made more clear for me.

**Comment by WilliamAntonRohm** [comment]
@rhornjr -- Bob, thank you for your followup.

@ghogen -- Gordon, please look into this potential clarification issue.

**Comment by rhornjr** [comment]
I got it. I stopped my local IIS and was then able to hit the container by using that link. As devs, I'm guessing others will have their local port 80 already running in IIS. Just stop that first.

**Comment by WilliamAntonRohm** [comment]
@rhornjr -- thank you for those details.  Glad you got it to work.

cc @ghogen for awareness
