### ISSUE TITLE
C26499

### ISSUE THREAD

**Issue by egyik** [MicrosoftDocs/visualstudio-docs#600]
This is an experimental rule but it's not clear what it means. Can it be documented?

I see it cropping up e.g. in Microsoft C++/WinRT code.

1>.\packages\cppwinrt.2017.10.13.1\build\native\include\winrt\base.h(11217): warning C26499: Could not find any lifetime tracking information for '*that'

More broadly why doesn't Microsoft ship code which compiles clean under /Wall and these checkers. The Visual Studio 2017 STL egregiously doesn't, new stuff like C++/WinRT doesn't either.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c0ac069-957b-8245-3d2c-616768f6353f
* Version Independent ID: 83f5ac6a-f1b7-39e1-b8b7-449cbebdd2a9
* [Content](https://docs.microsoft.com/en-gb/visualstudio/code-quality/code-analysis-for-cpp-corecheck)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/code-quality/code-analysis-for-cpp-corecheck.md)
* Service: unspecified

**Comment by mikeblome** [comment]
investigating

**Comment by egyik** [comment]
This is clearly relevant.
https://blogs.msdn.microsoft.com/vcblog/2016/03/31/c-core-guidelines-checkers-preview-of-the-lifetime-safety-checker/

**Comment by egyik** [comment]
Thanks for fixing!

**Comment by mikeblome** [comment]
@egyik Thanks for filing the issue!
