### ISSUE TITLE
Q: What's the difference between annual and monthly cloud subscriptions?

### ISSUE THREAD

**Issue by teomonda** [MicrosoftDocs/visualstudio-docs#6000]
This questions plus a few other references to the ANNUAL Visual studio cloud subscriptions should probably be removed /changed.
I read here that annual subscriptions are no longer a thing:
https://visualstudio.microsoft.com/vs/pricing-details/
Microsoft no longer offers Visual Studio Professional Annual Subscription and Visual Studio Enterprise Annual Subscriptions in Cloud Subscriptions. There will be no change to existing customers experience and ability to renew, increase, decrease, or cancel their subscriptions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf290c37-d7fa-9d10-b8ef-865647e58a70
* Version Independent ID: 1334b162-8560-5e0a-c874-9439b697dd96
* Content: [Billing FAQ for Visual Studio Visual cloud subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-billing-faq?source=docs#q-what-types-of-azure-subscriptions-can-be-used-to-buy-visual-studio-cloud-subscriptions)
* Content Source: [subscriptions/vscloud-billing-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-billing-faq.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@teomonda Thanks for the question.  We're no longer offering new annual subscriptions.  This has been the case for some time now.  But as stated on the page, those who already have them are unaffected.  They can still renew their existing annual subscriptions.

**Comment by evanwindom** [comment]
#please-close

**Comment by teomonda** [comment]
makes sense, thanks!
