### ISSUE TITLE
VS2019 Support for Windows Workflow Foundation

### ISSUE THREAD

**Issue by craig-martin** [MicrosoftDocs/visualstudio-docs#6001]
Visual Studio 2019 does not load Windows Workflow Foundation projects.
The upgrade report directs users to a page that says WF projects are support but that is not the case.
The upgrade report should instead direct users to this page:
https://docs.microsoft.com/en-us/visualstudio/workflow-designer/developing-applications-with-the-workflow-designer?view=vs-2019

But also include instructions to install the Office Components.

Installing the Windows Workflow Foundation component does not solve the project on its own, as this article suggests:
https://docs.microsoft.com/en-us/visualstudio/workflow-designer/developing-applications-with-the-workflow-designer?view=vs-2019

Here is a StackOverflow post on the issue:
https://stackoverflow.com/questions/57002898/migrating-workflow-foundation-to-visual-studio-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0307b5-7ea1-5bba-4894-0c3a9cc77f12
* Version Independent ID: 67637a95-a6a2-3180-d070-d83584d0f08e
* Content: [Developing Applications with the Workflow Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/workflow-designer/developing-applications-with-the-workflow-designer?view=vs-2019)
* Content Source: [docs/workflow-designer/developing-applications-with-the-workflow-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/workflow-designer/developing-applications-with-the-workflow-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-workflow-designer**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@craig-martin Thanks for letting us know; we'll take a look at this and report back.
