### ISSUE TITLE
The screenshots used for Visual Studio Publish are outdated

### ISSUE THREAD

**Issue by AngelosP** [MicrosoftDocs/visualstudio-docs#6005]
The screenshots used for Visual Studio Publish are outdated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 878a2a3e-60ac-aa4e-8166-fdd230d3d87d
* Version Independent ID: e7e9d77b-57c0-cd2b-fb00-a166cbcb7cf4
* Content: [Remote Debug ASP.NET Core on IIS and Azure - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-azure?view=vs-2019)
* Content Source: [docs/debugger/remote-debugging-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AngelosP Thanks! I'll take a look at that.

**Comment by AngelosP** [comment]
And if you need new screenshots or any kind of help please let me know. My team owns Publish so I can help.
