### ISSUE TITLE
trtyr

### ISSUE THREAD

**Issue by rmonnier** [MicrosoftDocs/visualstudio-docs#601]
rtr

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 852946c7-d511-76d8-ce40-a03c7d9d7ff2
* Version Independent ID: 4b1be0b3-7e28-d414-553f-9e1be7ef04a0
* [Content](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/deployment/deploying-applications-services-and-components.md)
* Service: unspecified

**Comment by jolyrojr** [comment]
how do i deploy to a device?
