### ISSUE TITLE
Wonky menu

### ISSUE THREAD

**Issue by DickBaker** [MicrosoftDocs/visualstudio-docs#6010]
Doc text says "Debug > Options > Symbols" but should read "Tools > Options > Debugging > Symbols" (with underscore chars or actual underscoring!). HTH (I liked Sagar's vstoolbox vid!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 988f4847-7ff2-3e5b-d73d-d9ef95facf16
* Version Independent ID: d0120a8a-6d0f-23c3-a85a-a28cb7637048
* Content: [Optimizing Profiler settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/optimize-profiler-settings?view=vs-2019)
* Content Source: [docs/profiling/optimize-profiler-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/optimize-profiler-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Sagar-S-S
* Microsoft Alias: **sashe**

**Comment by WilliamAntonRohm** [comment]
@Sagar-S-S -- Sagar, please review [private PR 7349](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7349).

**Comment by WilliamAntonRohm** [comment]
@DickBaker -- Dick, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
