### ISSUE TITLE
Name that task

### ISSUE THREAD

**Issue by DickBaker** [MicrosoftDocs/visualstudio-docs#6011]
Given importance of name in the results, should be a tip how to assign a name to awaited task (probably under a #if DEBUG conditional)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 988f4847-7ff2-3e5b-d73d-d9ef95facf16
* Version Independent ID: d0120a8a-6d0f-23c3-a85a-a28cb7637048
* Content: [Optimizing Profiler settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/optimize-profiler-settings?view=vs-2019)
* Content Source: [docs/profiling/optimize-profiler-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/optimize-profiler-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Sagar-S-S
* Microsoft Alias: **sashe**

**Comment by Sagar-S-S** [comment]
Hey @DickBaker thanks for your feedback! Do you mind clarifying what you mean by name in results and how that relates to this particular doc's theme of optimizing profiling settings?

**Comment by Mikejo5000** [comment]
This could be a request to name the async task (shows up in the Name column) for the [Async tool](https://docs.microsoft.com/en-us/visualstudio/profiling/analyze-async?view=vs-2019). @DickBaker to comment.

**Comment by DickBaker** [comment]
If developer explicitly names a task then the debugging experience is improved to distinguish the myriad concurrent tasks in parallel tasks window

**Comment by Mikejo5000** [comment]
@DickBaker I'm looking at this. At first look, it doesn't appear there is a way to name a Task, unlike a thread. I see a few workaround type suggestions](https://stackoverflow.com/questions/13762286/how-can-i-assign-a-name-to-a-task-in-tpl), like naming the method executed by a Task, but these seem incomplete. Did you identify a good way to name a Task?
