### ISSUE TITLE
documentation on deterministic builds is hard to find and dated

### ISSUE THREAD

**Issue by bbarry** [MicrosoftDocs/visualstudio-docs#6018]
Searching online for variations of "C# deterministic roslyn default build configuration," I am led to 3 official-ish points of documentation about configuring the Roslyn deterministic flag. I can't find a way to get from one to another within documentation or any of the other related pages if there are any: 

* https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#directorybuildprops-example - the only example I can find about the msbuild property related to the compiler flag
* https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/deterministic-compiler-option - about the compiler flag itself
* https://github.com/dotnet/roslyn/blob/master/docs/compilers/Deterministic%20Inputs.md - source reference material?

[An archived post on reddit](https://www.reddit.com/r/dotnet/comments/9pje6r/why_is_deterministic_builds_the_new_ms_norm_now/) suggests (not really sure what the default is for new projects or how that might be sourced) that the default is currently deterministic=true and [a random malformed xml configuration gist](https://gist.github.com/aelij/b20271f4bd0ab1298e49068b388b54ae) suggests setting `PathMap` while at it for non-portable pdbs (with less documentation available about what this means).

There should be a SEO friendly page somewhere that users can find documenting this property, what it does, what side effects it has and relating it to other pages like one for `PathMap` and something about pdbs.

Additionally the documentation here probably doesn't need the word "new" in "access the new Roslyn `/deterministic` feature" which is now 5+ years old. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Closing this issue, because the only reference to /deterministic is really as an example of something you might set, which was chosen solely because it's an easy true/false value and therefore makes a clean example.

**Comment by ghogen** [comment]
Opening an issue in the dotnet/docs repo as you suggested makes sense.
