### ISSUE TITLE
Add parameter to existing constructor (C# only) - Correction

### ISSUE THREAD

**Issue by indikaanu83** [MicrosoftDocs/visualstudio-docs#602]
I think its Ctrl and . is the shortcut to get that menu. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4dd39fe2-328a-b8a2-9795-ab8c6c735761
* Version Independent ID: 075639a3-171c-6ade-85fc-a3845f933b82
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-constructor)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/reference/generate-constructor.md)
* Service: unspecified

**Comment by gewarren** [comment]
@indikaanu83 thank you for the feedback. The doc is trying to convey that Ctrl and . is the shortcut, but using the syntax "Ctrl+.". Is that not clear because of the + sign?

**Comment by indikaanu83** [comment]
hi,

At the very first time, I tried CTRL, + and . all together. Maybe it's just
me. But I feel the + sign makes little bit confusing.

On Fri, Feb 23, 2018 at 11:33 PM, Genevieve Warren <notifications@github.com

**Comment by gewarren** [comment]
I improved the bolding of Ctrl and . to try and help clarify the shortcut.
