### ISSUE TITLE
Opened files per branch

### ISSUE THREAD

**Issue by eloyucu** [MicrosoftDocs/visualstudio-docs#6023]
Hi everyone.

This is not a issue but a proposal... I hope you like it :) 

I´d like to keep some files opened in the editor depending in the branch I am working in. I mean, if I have only one project in each instance of VisualStudio, it could be great that the files opened were saved by branch, in the way that in the brach X the files opened are file_1 and file_2, and in the branch Y file_3... if I am in branch X and I close the file_1 next time I´ll do _git checkout X_ only file_2 will remain opened. 

Well, I hope I was clear. Thanks in advance.

**Comment by WilliamAntonRohm** [comment]
@eloyucu -- Eloy, thank you for your proposal.  Please add your idea here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
