### ISSUE TITLE
domain missing for updates: akamaized.net

### ISSUE THREAD

**Issue by mdro** [MicrosoftDocs/visualstudio-docs#6029]
We had trouble updating VS2019 (from 16.7.1 to 16.7.7), the installer couldn't self-update.
By examining the firewall logs we found out that the installer tried to download its new version from `akamized.net`, so it should be added to the "Install Visual Studio" section.
The question is, which sub-section? It's neither a microsoft-owned domain, nor related to a 3rd party workload.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2019)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@evanwindom, @ornellaalt -- please look into this issue.

**Comment by evanwindom** [comment]
@WilliamAntonRohm - This issue is specific to the Visual Studio IDE and not applicable to subscriptions.

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- thank you for clarifying.

**Comment by ornellaalt** [comment]
Added in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7406
