### ISSUE TITLE
"Most recent version" doesn't exactly pin this documentation down.

### ISSUE THREAD

**Issue by rkpatrick** [MicrosoftDocs/visualstudio-docs#603]
There are too many versions of documentation floating around to use "Most recent version does X or Y".  I cannot even count how many times I have seen that only to find the documentation to be inaccurate because it was written in the past to where "Most recent version" no longer applies.  In this case, the errors are at least minimal (for instance, as of VS2017, the text no longer reads "Cache symbols from symbol servers to this directory"...it's "Cache symbols in this directory"), but it still makes me wonder if I'm having issues getting source debugging to work because these steps are out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e04e717-61a6-99eb-60cd-34263fa597b5
* Version Independent ID: 3ee15675-d5bd-f3c9-fb85-1b65b3d71897
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-dotnet-framework-source)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/how-to-debug-dotnet-framework-source.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@rkpatrick Thanks! I am updating the steps for this article.

**Comment by Mikejo5000** [comment]
Refreshed doc. Published.
