### ISSUE TITLE
We should consolidate all Suppress violations information into single doc page

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#6030]
We have https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019#suppress-violations section on this page, but also have a dedicate page for source suppressions overview: https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019

I think we should move the section in this page to the dedicate page for source suppressions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer configuration - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by Mikejo5000** [comment]
@manish @mikadumont I can create a user story for this. Looks like the dedicated page only talks about the attribute. It also appears that there's two ways to suppress a message in source code: the #pragma warning or the SuppressMessage attribute, which provides a lot more detailed configuration options.

**Comment by KalleOlaviNiemitalo** [comment]
.NET 5 additionally has [UnconditionalSuppressMessageAttribute](https://docs.microsoft.com/dotnet/api/system.diagnostics.codeanalysis.unconditionalsuppressmessageattribute?view=net-5.0) from <https://github.com/dotnet/runtime/pull/35387> for ILLink.
