### ISSUE TITLE
Sum avg time of all descendants or provide hot path(s)

### ISSUE THREAD

**Issue by Camios** [MicrosoftDocs/visualstudio-docs#6034]
1. The column "Total Time" label is misleading - it is only an avg time spent explicitly in this task. It doesn't count time spent in child tasks.
2. I suggest a column is required to sum up all the descendants' times or an automated hot-path identifier.
If this isn't provided, from what I saw in the channel 9 video, the user can't easily find hot paths - instead the user has to drill down into every single task and all its descendants

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1ff01f-ec92-a385-f11b-83ed8919b056
* Version Independent ID: 8ffd1f76-0577-d50e-4277-713284897974
* Content: [Analyze performance of .NET asynchronous code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/analyze-async?WT.mc_id=vstoolbox-c9-niner&view=vs-2019)
* Content Source: [docs/profiling/analyze-async.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/profiling/analyze-async.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @esteban-herrera
* Microsoft Alias: **esherrer**

**Comment by WilliamAntonRohm** [comment]
@Camios -- Cameron, thank you for your feedback.  @esteban-herrera may be able to address your first issue.  For the second issue, please add your suggestion here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).

**Comment by Mikejo5000** [comment]
@Camios Closing this since it is a suggestion for a product improvement. Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). @Sagar-S-S @esteban-herrera for visibility.

**Comment by Camios** [comment]
@Mikejo5000 the existing behaviour is wrong and a suggestion is only provided as a way to fix it.  Can you reopen please?

**Comment by Mikejo5000** [comment]
Sounds like the doc needs a refresh, is that right?

**Comment by Mikejo5000** [comment]
I think I see what you mean; in the screenshot, it appears that Total Time includes the time spent in child tasks, if I'm reading it right. I look into this.

**Comment by Mikejo5000** [comment]
@Camios I tested the async profiling tool using the [async operator example code](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await).

Would you clarify which version of .NET "dot point 1" refers to? I tested this on .NET Core 1.1, 2.1, and 3.1, along with .NET F 4.7.2. (Doesn't work at all in 1.1)

I only see Start Time, End Time, and Total Time that show expected values, and the Total Time appears inclusive of all the nested async tasks (for example, the Program.Main task always ends last, and its values appear inclusive). Let me know if I'm missing something, and what it is in the doc that needs to be corrected. Thanks!

**Comment by Camios** [comment]
@Mikejo5000 sorry it has been a while since I raised this and I didn’t check it again when You closed. Thank you for the confirmation it is working as documented. I can close the ticket
