### ISSUE TITLE
Moving arrow to different instruction is mostly not working with C++ app and remote Linux connection

### ISSUE THREAD

**Issue by HoppeMateusz** [MicrosoftDocs/visualstudio-docs#6036]
Hi,

When debugging C++ linux app from VS i am not able to move arrow to next instruction to be executed most of the times - there is popup window saying:
---------------------------
Microsoft Visual Studio
---------------------------
This operation will set the next statement to a different function. Are you sure?
---------------------------
Yes   No   
---------------------------

although i am only skipping one if check.
Sometimes ( very rarely ) it works - for only small portions of code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01b337f5-ece8-2924-8b1a-e3457c53aef4
* Version Independent ID: 4ccba011-d3bc-4c38-8a4f-5bf9a4147e60
* Content: [Navigate code with the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/navigating-through-code-with-the-debugger?view=vs-2019)
* Content Source: [docs/debugger/navigating-through-code-with-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/navigating-through-code-with-the-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by HoppeMateusz** [comment]
Hello, 
No, there is no option not to show the message - only "YES/NO" buttons.
But even when i click YES, nothing happens - execution point is not moved to the place where i moved the arrow.

**Comment by Mikejo5000** [comment]
@andrewwang2015 Andrew, is this behavior by design? Or is it a bug?

**Comment by WardenGnaw** [comment]
This behavior is not by design. Please file a bug.

Thank you

**Comment by HoppeMateusz** [comment]
Ok, thanks
here is link
https://developercommunity2.visualstudio.com/t/moving-arrow-to-different-instruction-is-mostly-no/1243895?from=email&preview=true
