### ISSUE TITLE
Documentation does not describe the actual behavior of VS 2019 when it comes to ToolsVersion

### ISSUE THREAD

**Issue by darkoa-msft** [MicrosoftDocs/visualstudio-docs#6038]
Some of the claims on this page are incorrect.
VS 2019 uses the Framework MSBuild in .NET Core projects when you specify Current as ToolsVersion or omit it altogether.
I raised a bug through Visual Studio, but I don't think that is going anywhere.
Please fix the documentation to reflect the actual behavior.

If you run the msbuild (or dotnet msbuild) from command line, you run the correct one. VS 2019 does not care, it always picks the Framework build (and that one is not even in the path but is found somehow, see below). Two builds are different enough to make local vs CI/CD experience different (only one can build to x64, not both).

```
C:\Windows\System32>where msbuild.exe
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe
C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a149d2bb-ccbf-42d8-5ea4-971fe211fdb6
* Version Independent ID: 3bcdf305-4f85-fe4d-24f5-1ce2ecec8d15
* Content: [Standard and Custom Toolset Configurations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/standard-and-custom-toolset-configurations?view=vs-2019)
* Content Source: [docs/msbuild/standard-and-custom-toolset-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/standard-and-custom-toolset-configurations.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@darkoa-msft -- thank you for your feedback.  Please specify the Visual Studio bug you created.

**Comment by darkoa-msft** [comment]
I would love to but I do not know how to find the bug I created.
I created the bug ("reported a problem") through Visual Studio (as instructed).
I do not recall that I had to change login from AME to MSFT, so it might have gone into a weird place.

**Comment by darkoa-msft** [comment]
I stand corrected, I found it with ame.gbl (there was some transient error under 'my feedback')

https://developercommunity2.visualstudio.com/t/VS-2019-is-using-wrong-MSBuildexe/1229200

**Comment by WilliamAntonRohm** [comment]
@darkoa-msft -- thank you for finding that additional information for us.
