### ISSUE TITLE
Keyword property panel

### ISSUE THREAD

**Issue by zacharyk-suzy** [MicrosoftDocs/visualstudio-docs#6040]
The Keyword property panel needs more info.  You give reference to the default value and tooltip, but leave out what we can put in the Function area. What is an Identifier? What are Values? I can assume some of these things, but have no idea how to be certain.  I'm especially interested in the Function capability.  Thanks!
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c165c6c-3afb-ec14-fc40-13c504aa2492
* Version Independent ID: eb03852b-8ccf-a6f7-b62d-a6912a97430d
* Content: [Code Snippets - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/snippets?view=vsmac-2019)
* Content Source: [mac/snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/snippets.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @cobey
* Microsoft Alias: **cobey**

**Comment by WilliamAntonRohm** [comment]
Please see [Code snippets schema reference](https://docs.microsoft.com/en-us/visualstudio/ide/code-snippets-schema-reference?view=vs-2019).

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
