### ISSUE TITLE
How to return the focus from search to the tool window content?

### ISSUE THREAD

**Issue by mostafa8026** [MicrosoftDocs/visualstudio-docs#6041]
I think it is better to elaborate how to return focus on the tool window when using (alt+`). really I don't know how to return focus on the tools window content and I have to use mouse for that? take a look at this GIF:

![07](https://user-images.githubusercontent.com/1726531/97744587-bc68d600-1afc-11eb-90ac-35bce6c64ff8.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c680d2e-f7b5-7213-c67c-b17c1293a7dc
* Version Independent ID: 1bfd8f04-11bb-954d-d7a2-4d96729df8e3
* Content: [Keyboard and mouse shortcuts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/productivity-shortcuts?view=vs-2019)
* Content Source: [docs/ide/productivity-shortcuts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/productivity-shortcuts.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@mostafa8026 We haven't heard anything back on our proposed solution to the problem you outlined; as such, we'll close this issue now. Thanks for your feedback and your continued interest in Microsoft products and services!
