### ISSUE TITLE
Love it

### ISSUE THREAD

**Issue by rodolforp01** [MicrosoftDocs/visualstudio-docs#6043]
[Enter feedback here]
love it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f3b242-e5be-0e07-79bf-c3f1652d3861
* Version Independent ID: 61c049c6-c028-692e-5b76-5cd8cb0ea020
* Content: [Tutorial: Get started with Visual Basic - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-basic/tutorial-console?view=vs-2019)
* Content Source: [docs/get-started/visual-basic/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-basic/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@rodolforp01 -- thank you!

cc @ornellaalt for awareness
