### ISSUE TITLE
See Also missing link to aspnet.exe documentation

### ISSUE THREAD

**Issue by jmwolfe** [MicrosoftDocs/visualstudio-docs#6044]
This doc comes up early in search results for aspnet_compiler.exe.  Suggest there be a See Also link to the actual exe documentation itself (which is what I was looking for).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc98b038-d374-848d-b55a-47dd9c9128d2
* Version Independent ID: a0025e1a-8343-b873-fa8c-9423c9579749
* Content: [Use AspNetCompiler Task to precompile ASP.NET - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/aspnetcompiler-task?view=vs-2019)
* Content Source: [docs/msbuild/aspnetcompiler-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/aspnetcompiler-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@jmwolfe -- Jesse, thank you for your feedback.  I found this information and have added it to the article.
- [ASP.NET Compilation Tool (aspnet_compiler.exe)](https://docs.microsoft.com/en-us/previous-versions/ms229863(v=vs.100))

@ghogen -- Gordon, please review [private PR 7420](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7420).
