### ISSUE TITLE
Dead link to support URL

### ISSUE THREAD

**Issue by snakex2000** [MicrosoftDocs/visualstudio-docs#6049]
Dead link to support, not acceptable.   

Repro:
1)  click link under Resources: 
Visual Studio Administration and Subscriptions Support

2)  Navigates to 404 error  & customer cannot get support

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a47a443c-b3f6-8fc1-6c38-d7a6c6ec9bf2
* Version Independent ID: aca4f0e1-0cbc-87c1-a1d2-d01672d0a949
* Content: [Contact your subscription admin in the Subscriber Portal](https://docs.microsoft.com/en-us/visualstudio/subscriptions/contact-my-admin)
* Content Source: [subscriptions/contact-my-admin.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/contact-my-admin.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@snakex2000 Thanks for reporting the problem.  You are absolutely correct.  I've just merged a PR to correct the error.  Thanks again for letting us know.

**Comment by evanwindom** [comment]
#please-close
