### ISSUE TITLE
`ExtensionsToDeleteOnClean` isn't documented

### ISSUE THREAD

**Issue by rigdern** [MicrosoftDocs/visualstudio-docs#606]
`ExtensionsToDeleteOnClean` isn't documented.

I found this property in `Microsoft.Cpp.Common.props`.

Adam Comella
Microsoft Corp.

**Comment by gregvanl** [comment]
@rigdern Can you provide more context on this setting? For example, in which configuration file would you set it or which existing docs.microsoft.com topic would likely include the description. This will help with assigning the issue to the appropriate doc team and writer. Thanks

**Comment by rigdern** [comment]
@gregvanl Sorry, I'm new to msbuild and wasn't sure what context would be useful. I updated the issue description with an additional detail. Let me know if that's sufficient.

**Comment by gregvanl** [comment]
@rigdern Great, this helps. Sounds like it is C++ specific for MSBuild.

**Comment by Mikejo5000** [comment]
Property looks specific to C++ and maybe extensibility also. I don't see any docs on this subject, but it would probably belong in C++ if it were doc'ed. I looked through their docs, and it doesn't look like they are doc'ing every property either (though that would be nice). Closing as out of scope.
