### ISSUE TITLE
Also in case you were wondering

### ISSUE THREAD

**Issue by Rixius44** [MicrosoftDocs/visualstudio-docs#6060]
yes i'm reading this guide front to back

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15b81f2c-0402-fa4e-fdc7-0edd1f3c4ba9
* Version Independent ID: f2fbe0e0-67b6-995a-f1c1-2f1d135e07d5
* Content: [Windows Forms Designer tutorial - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/walkthrough-windows-forms-designer?view=vs-2019)
* Content Source: [docs/designers/walkthrough-windows-forms-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/walkthrough-windows-forms-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Rixius44 -- how was your experience with this tutorial?

**Comment by Rixius44** [comment]
so far all the tutorials have been great! a few minor inconveniences like missing example files on the microsoft website but nothing that can't be bypassed with a trick or two or a little google search. the worst there is is just some typos but it's overall perfect.

**Comment by WilliamAntonRohm** [comment]
@Rixius44 -- thank you for your great review!  If you have the time, please let us know the details of any glitches so we can address them.
