### ISSUE TITLE
"missing" object does not exist

### ISSUE THREAD

**Issue by chmod771** [MicrosoftDocs/visualstudio-docs#6061]
I'm new to C# and programming as well. I'm confused about this "missing" object that is declared in the example, it doesn't seem to work. Am I missing a reference? I tried null and it threw an exception.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 242ba39d-6ba5-8380-a842-a40d46d99ab4
* Version Independent ID: fae75896-6a21-6416-b987-3fd340b7adfb
* Content: [How to: Programmatically search for text in worksheet ranges](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-search-for-text-in-worksheet-ranges?view=vs-2019)
* Content Source: [docs/vsto/how-to-programmatically-search-for-text-in-worksheet-ranges.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-search-for-text-in-worksheet-ranges.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by chmod771** [comment]
"Missing.Value" seems to work

it seems the correct example would be the following:

currentFind = Fruits.Find("apples", Missing.Value,
            Excel.XlFindLookIn.xlValues, Excel.XlLookAt.xlPart, 
            Excel.XlSearchOrder.xlByRows, Excel.XlSearchDirection.xlNext, false,
            Missing.Value, Missing.Value);

**Comment by WilliamAntonRohm** [comment]
@chmod771 -- thank you for your questions and followup.  Please see this article regarding the built-in `missing` variable:
- [Use optional parameters of methods in the ThisDocument class in Visual C# document-level projects for Word](https://docs.microsoft.com/visualstudio/vsto/optional-parameters-in-office-solutions?view=vs-2019#use-optional-parameters-of-methods-in-the-thisdocument-class-in-visual-c-document-level-projects-for-word)

@John-Hart -- please look into the example above, as a potential documentation issue.
