### ISSUE TITLE
Option to use an Azure group for assigning permissions is missing

### ISSUE THREAD

**Issue by clerckjo** [MicrosoftDocs/visualstudio-docs#6063]
On my tenant, when clicking Add, there is no option to link the subscription assignment to a group, only individual subscriber or bulk add are present, although we do have an Azure subscription and I am a global admin in my tenant.

I haven't found any information on what is required to activate this option, so I reckon some crucial information is missing from this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac6f4b8-da9d-5b7b-0c18-b6ed1f85433a
* Version Independent ID: 1ac1ddeb-b1a4-e8d3-9abf-0e629796c5ef
* Content: [Assign licenses to groups of users for Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-license-bulk#use-azure-active-directory-groups-to-assign-subscriptions)
* Content Source: [subscriptions/assign-license-bulk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/assign-license-bulk.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- Evan, please look into this issue.

**Comment by evanwindom** [comment]
@clerckjo - Thanks for reaching out.  I apologize for the delayed response.  The option to use Azure Active Directory groups is available for "trusted" agreements only.  If your company is using an agreement like Open or Select, the option is not available to use Azure AD groups.  The limitation is listed in the blue "Important" section displayed just above the video in the article.

**Comment by evanwindom** [comment]
#please-close
