### ISSUE TITLE
is the page up to date?

### ISSUE THREAD

**Issue by uranio238** [MicrosoftDocs/visualstudio-docs#6066]
Hi, the page seems to link to the wrong resources and it doesn't say which version of visual studio you need.
I have visual studio 2019 professional and it doesn't seem to have it available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb79e97f-6d8a-0f06-96db-db4fc1e135ae
* Version Independent ID: 097107da-2105-400d-3ad3-1f47c1422209
* Content: [Getting Started with Domain-Specific Languages - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/getting-started-with-domain-specific-languages?view=vs-2019)
* Content Source: [docs/modeling/getting-started-with-domain-specific-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/getting-started-with-domain-specific-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by mgoertz-msft** [comment]
@uranio238 The note in the [Prerequisites](https://docs.microsoft.com/en-us/visualstudio/modeling/getting-started-with-domain-specific-languages?view=vs-2019#prerequisites) section explains that you need to install the optional Modeling SDK component in the Extensibility workload.

**Comment by j-martens** [comment]
Thank you for reaching out, @uranio238  We hope this solves your issue. Add a comment if you still don't see what you need.  #please-close
