### ISSUE TITLE
Invalid XML in example in CodeCoverage data collector

### ISSUE THREAD

**Issue by b099l3** [MicrosoftDocs/visualstudio-docs#6069]
In the section [CodeCoverage data collector](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019#codecoverage-data-collector) the code example is not valid XML, an extra end tag of `</Codecoverage>` is added whoops!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by b099l3** [comment]
Created a PR for this #6070

**Comment by WilliamAntonRohm** [comment]
@b099l3 -- Iain, thank you for your contribution.

@Mikejo5000 -- Mike, please review PR https://github.com/MicrosoftDocs/visualstudio-docs/pull/6070.

**Comment by Mikejo5000** [comment]
Fixed in the referenced PR.
