### ISSUE TITLE
VS 2019 Preview Release Notes page has many massive links

### ISSUE THREAD

**Issue by vaindil** [MicrosoftDocs/visualstudio-docs#6084]
The [VS 2019 Preview Release Notes page](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview) has many massive links as of today, which is messing up the formatting. Everything underlined in the image below, for example, is one link.

![image](https://user-images.githubusercontent.com/771134/98728193-25efac80-2367-11eb-9b1e-e727aa0e06da.png)

**Comment by WilliamAntonRohm** [comment]
@vaindil -- Steven, thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

**Comment by vaindil** [comment]
Sorry, are you saying that the links in that article (that don't actually link to anything) are an intentional design choice, not a bug?

**Comment by WilliamAntonRohm** [comment]
@vaindil -- Steven, thank you for your follow-up.  I misunderstood your original point, and yes it's a typo.

@JacquelineWiddis -- Jacqueline, please look into this issue.

**Comment by JacquelineWiddis** [comment]
Thank you for letting us know about this issue.  I always appreciate how engaged our user community is in spotting errors and letting us know.  It is fixed now.  #please-close
