### ISSUE TITLE
Please clarify that "New WPF XAML Designer for .NET Framework" is only available on "preview builds".

### ISSUE THREAD

**Issue by vpereira01** [MicrosoftDocs/visualstudio-docs#6088]
I tried to enabled the preview feature on "New WPF XAML Designer for .NET Framework" on VS2019 16.8 but it isn't available.

After searching and searching around I found [this post](https://docs.microsoft.com/en-gb/visualstudio/releases/2019/release-notes-preview#16.9.0-pre-1.0) that says 

> To get started, go to Options > Preview Features, select “New WPF XAML Designer for .NET Framework” and restart Visual Studio. **This feature is only available in the Preview channel for early testing**; its final release details have not yet been determined.

This page doesn't clarify that it's only available on the preview channel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e11091e-5194-644c-8d48-8afb5a7cafb3
* Version Independent ID: 62eeeafe-f6f2-a64c-b425-1cb39b0fa3fd
* Content: [Use Design Time Data with the XAML Designer in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-designtime-data?view=vs-2019)
* Content Source: [docs/xaml-tools/xaml-designtime-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/xaml-designtime-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @alihamie
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@LyalinDotCom @alihamie Please take a look at this and verify; then, we can update the content. Thanks. :)

**Comment by LyalinDotCom** [comment]
Yes the new designer right now is only for preview channel, that will change in the future (maybe even in 16.9 Preview 2 or 3) but its true today

**Comment by TerryGLee** [comment]
@LyalinDotCom @alihaime We'll need to update the Requirements section, then. I'll work with you offline to get that sorted. Meanwhile, @vpereira01, thanks for bringing this to our attention. We'll report back after we have the page updated.

**Comment by TerryGLee** [comment]
@vpereira01 To follow up, we've updated the [Requirements](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-designtime-data?view=vs-2019#troubleshooting) section of the _Use Design Time Data with the XAML Designer in Visual Studio_ page to include the information that you pointed out was missing. We'll close this issue now, with our thanks to you for helping us improve the documentation.
