### ISSUE TITLE
Debug > Restart = Ctrl+Shift+F5

### ISSUE THREAD

**Issue by gjuwindev** [MicrosoftDocs/visualstudio-docs#6097]
This page says:

    Then restart the app (Debug > Restart, Ctrl+F5,

and it should be:

    Then restart the app (Debug > Restart, Ctrl+Shift+F5,

:-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7542d51c-4ba4-db5d-cd34-4517779684a8
* Version Independent ID: ef7b3a39-814e-9c56-c2e1-6611464aa650
* Content: [Learn Flask tutorial in Visual Studio step 1, Flask basics](https://docs.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-01-project-solution?view=vs-2019)
* Content Source: [docs/python/learn-flask-visual-studio-step-01-project-solution.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-flask-visual-studio-step-01-project-solution.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
