### ISSUE TITLE
Provide information about Intelisense when using Python

### ISSUE THREAD

**Issue by agribot2** [MicrosoftDocs/visualstudio-docs#6098]
[Enter feedback here]

This section of documentation mentions various programming languages such as C, C++, etc. It should also provide information about how intellisense works with Python.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 783173cc-7542-ed8c-be48-dcb9d79d622c
* Version Independent ID: 9828af4d-65f3-7303-c9b6-3edffba94c66
* Content: [Parameter info, list members, and quick info - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-intellisense?view=vs-2019)
* Content Source: [docs/ide/using-intellisense.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/using-intellisense.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@agribot2 -- thank you for your suggestion.  I'm adding a link in the See Also section to [this article](https://docs.microsoft.com/en-us/visualstudio/python/editing-python-code-in-visual-studio?view=vs-2019#intellisense).
