### ISSUE TITLE
Download Zip Link Broken

### ISSUE THREAD

**Issue by Articho28** [MicrosoftDocs/visualstudio-docs#6099]
When going through the tutorial, the Download the Zip link at the top of the page did not work. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Articho28 -- Artsiom, thank you for your feedback. This issue is being tracked in #5998.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
