### ISSUE TITLE
Missing change log for VS Tools for Unity 3.5.0.3

### ISSUE THREAD

**Issue by Axemagus** [MicrosoftDocs/visualstudio-docs#610]
3.5.0.3 was released last month, but the change log was never posted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd09a24e-305b-bb2e-a8b5-9ea9c52fd8a4
* Version Independent ID: 83bf7326-a96c-3bc4-a2ff-b1f510ea9308
* [Content](https://docs.microsoft.com/en-us/visualstudio/cross-platform/change-log-visual-studio-tools-for-unity)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/cross-platform/change-log-visual-studio-tools-for-unity.md)
* Service: unspecified

**Comment by sailro** [comment]
Yes, I'm going to update the changelog. Thanks

**Comment by Axemagus** [comment]
Thanks for the quick turn around on this!
