### ISSUE TITLE
下载 ZIP  url Error url is localhost

### ISSUE THREAD

**Issue by weiyinjuan** [MicrosoftDocs/visualstudio-docs#6101]
[在此处输入反馈]
下载 ZIP url Error url is localhost

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker 教程 - 第 1 部分：生成并运行待办事项列表示例应用](https://docs.microsoft.com/zh-cn/visualstudio/docker/tutorials/your-application#feedback)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-cn/blob/live/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@weiyinjuan -- thank you for your feedback.  This issue is being tracked in https://github.com/MicrosoftDocs/visualstudio-docs/issues/5998.

cc @ghogen for awareness
