### ISSUE TITLE
Python profiling is under the main menu Debug, not Analyze

### ISSUE THREAD

**Issue by romanliv** [MicrosoftDocs/visualstudio-docs#6106]
[Enter feedback here]
> Profiling is started through the Analyze > Launch Python Profiling menu command, which opens a configuration dialog:

Python profiling is not under the Analyze menu command, but under the Debug one.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399822f9-b83b-a607-4310-a7f496cf1f27
* Version Independent ID: c1300996-f8f4-e297-993a-1d614efe7e79
* Content: [Measure performance of Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/profiling-python-code-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/profiling-python-code-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/profiling-python-code-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
