### ISSUE TITLE
Blank solution template not present

### ISSUE THREAD

**Issue by lukos** [MicrosoftDocs/visualstudio-docs#6107]
The page talks about creating a blank solution but this is not present in my "Create a new project" dialog. I can't imagine that it wouldn't be installed by default but the article should say what to do if the template is not present/available when you search for it.

I have VS 16.8.0 on Windows 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e5b432e-98af-2784-12f3-5da298a7a6a3
* Version Independent ID: 0d0b207d-4ea3-3716-3894-b898b279e667
* Content: [Introduction to projects and solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-projects-solutions?view=vs-2019)
* Content Source: [docs/get-started/tutorial-projects-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/tutorial-projects-solutions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@lukos Thanks for letting us know about your experience. After testing, we've discovered that after you install a workload or two, there are more templates for you to choose from, which pushes the Blank Solution template to the **Other results based on your search** section of the list. We've updated the page by adding a Tip note that indicates this. We'll close this issue now, with our thanks for helping us improve the documentation.
