### ISSUE TITLE
Breakpoint Visual

### ISSUE THREAD

**Issue by Jacquers** [MicrosoftDocs/visualstudio-docs#6108]
It looks like the visual has changed?

The arrow looks bigger and it doesn't look as nice as before.

![image](https://user-images.githubusercontent.com/31434053/99258468-4d3ff100-2821-11eb-896b-0abc10f8411f.png)

* This is for C#

**Comment by WilliamAntonRohm** [comment]
@Jacquers -- thank you for your feedback.  Are you following a particular docs.microsoft.com article?

**Comment by Jacquers** [comment]
Guess I should have left it on VS feedback. Got here via a link on the last VS release notes page.

**Comment by WilliamAntonRohm** [comment]
@Jacquers -- here's a feedback link:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
