### ISSUE TITLE
Thin explanation without references (code metrics)

### ISSUE THREAD

**Issue by frankbj57** [MicrosoftDocs/visualstudio-docs#611]
This article only scratches the surface of what VS can - and doesn't do anything to justify and explain more deeply why these code metrics have any relevance. The least you could do was to insert links to references either on your own site or relevant articles.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b417a6f-2527-9ec4-7e00-a0ce8e55f997
* Version Independent ID: d250f719-b8d7-7b03-d883-968e0b961d49
* Content: [https://docs.microsoft.com/en-us/visualstudio/code-quality/code-metrics-values](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-metrics-values)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/code-metrics-values.md)
* Service: unspecified

**Comment by gewarren** [comment]
@frankbj57 thank you for the feedback. I will look into improving the code metrics documentation when time allows.
