### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [MicrosoftDocs/visualstudio-docs#6110]
The markup version of the readme that is displayed for the main page in this repo contains the following link:
Status code [404:NotFound] - Link: https://github.com/Microsoft/vsdocs

In the readme the comment after the link says "Traffic to the old URLs is redirected here."
However this is not the case and 404 happens instead of a redirect.

Perhaps this comment just needs removing?

**Comment by WilliamAntonRohm** [comment]
@MrCull -- Mark, thank you for your prompt action.  

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
