### ISSUE TITLE
CPreprocessOptions should include /E

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/visualstudio-docs#6115]
If you are specifying a non-empty CPreprocessOptions, it should include /E to actually pre-process the idl file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c9801fb-3278-8e3d-e11a-19cfc07b903c
* Version Independent ID: e5900f57-a15f-19be-eb93-51da01b3ad1b
* Content: [MIDL Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/midl-task?view=vs-2019)
* Content Source: [docs/msbuild/midl-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/midl-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
It appears to be fixed already - the article says to use /E option.
