### ISSUE TITLE
Really? This page disregards all instructions from the docs.

### ISSUE THREAD

**Issue by xcITs-Xian** [MicrosoftDocs/visualstudio-docs#6119]
I don't get it. There is a very good best practice page https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices#avoid-logic-in-tests and this page makes all the "bad" things which are described on that page. 
I don't think this is helpful for new devs.

I think the documentation needs a little more unit testing itself ... ;-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13cf2292-058f-6ea7-ecab-d69c2f99d516
* Version Independent ID: 2a8b10ba-770e-745e-9038-0598dacf9dba
* Content: [Learn how to test your code with Live Unit Test - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-start?view=vs-2019)
* Content Source: [docs/test/live-unit-testing-start.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/live-unit-testing-start.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@xcITs-Xian Thanks for bringing this up! I will be interested to look at the best practices, and see about making some updates.
