### ISSUE TITLE
Clear and concise, but a request...

### ISSUE THREAD

**Issue by gmonkman** [MicrosoftDocs/visualstudio-docs#612]
Clear description, but could microsoft work with CPython people to ensure that the pdb's are published on their ftp site at the time of the windows binary releases.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a28d662-7af8-e0cc-dc6c-b300d22eb16d
* Version Independent ID: 61410436-ef1f-6858-618d-c3a2da35309a
* [Content](https://docs.microsoft.com/en-gb/visualstudio/python/debugging-symbols-for-mixed-mode-c-cpp-python)
* [Content Source](https://github.com/MicrosoftDocs/visualstudio-docs-pr/blob/live/docs/python/debugging-symbols-for-mixed-mode-c-cpp-python.md)
* Service: unspecified

**Comment by kraigb** [comment]
Moved this issue to the PTVS repo instead so the engineering team can track it.
