### ISSUE TITLE
Missing documentation for Intrinsic Functions

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#6127]
This page is missing documentation for some functions defined in https://github.com/dotnet/msbuild/blob/master/src/Build/Evaluation/IntrinsicFunctions.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by rainersigwald** [comment]
I'll take a crack at this @ghogen.
