### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Rixius44** [MicrosoftDocs/visualstudio-docs#6132]
Hello!
In the "Install the sample application," the sample files are missing from Github  and the Microsoft website. I had to use my own sample file (the matching game tutorial project) to finish this tutorial...

Not a big deal, just a minor annoyance, I guess.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5db8407-cc91-c741-6bc4-9d059ab40308
* Version Independent ID: 8d477def-5203-6085-915b-31971afeccab
* Content: [Walkthrough: Build an application - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application?view=vs-2019)
* Content Source: [docs/ide/walkthrough-building-an-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/walkthrough-building-an-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
We should either say users should use their own sample, or provide an up-to-date link.

**Comment by DenMurphy** [comment]
This step is still confusing. The link "[Introduction to building WPF applications](https://github.com/microsoft/wpf-samples/tree/main/Getting%20Started/Concepts)" takes you to a page that does not have any download 'zip' files available. The nearest download page is 2 clicks away, going back up the Github tree to the "WPF Samples" page:  https://github.com/microsoft/WPF-Samples

Download via Zip is also hidden under the 'Code' button. This is also not clear to newbies.

This page does not have the "ExpenseItIntro.sln" sample within, and even when searching all of Github this does not exist.

Please fix or change this as I'm sure I'm not the only one stumped at this step.

**Comment by WilliamAntonRohm** [comment]
@DenMurphy -- Dennis, thank you for your follow-up.

@ghogen -- Gordon, please look into this new information.

**Comment by ghogen** [comment]
I think it's better now, this was recently updated.
