### ISSUE TITLE
How can the extension be updated after publishing?

### ISSUE THREAD

**Issue by icnocop** [MicrosoftDocs/visualstudio-docs#614]
How can the extension be updated after publishing?

For example, I published v1.0 of the extension and now I want to publish v1.1.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac223936-2fe5-45ea-bd78-656013f0d6e0
* Version Independent ID: fcae191e-6ea3-85ca-25a9-7cc5c32ca008
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension#remove-the-extension)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/walkthrough-publishing-a-visual-studio-extension.md)
* Service: unspecified

**Comment by icnocop** [comment]
@gregvanl, Thank you.

After several minutes I figured out that I have to click the following:
1. Manage (Extension)
2. Extension Menu > Edit
3. Edit package (Pencil icon), under "1. Upload extension"
4. Select vsix file from my local machine
5. Open

I was expecting an "Update" item in the extension menu, mentioned in another doc, https://docs.microsoft.com/en-us/vsts/extend/publish/overview#update.

**Comment by innovocad** [comment]
I am getting the following error for all my extensions when trying to update our extensions...
Error: TF400733: The request has been canceled: The request has exceeded request timeout, please try again.

Last week I did not get this error.

**Comment by HansUXdev** [comment]
I used to know how to update my extension pack but A). MS documentation is trash and B). fuck this azure shit. Just pull from github or npm like normal people. My god this is completely unnecessary crap to update a goddamn json file...
