### ISSUE TITLE
Using CSFile to exclude a file from the build only works if the code in the file compiles

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/visualstudio-docs#6140]
The following way to exclude a file from the build doesn't work if the code doesn't compile. If excluded files must compilate, can something be added to that effect?

```
<ItemGroup>
    <CSFile Include="*.cs" Exclude="MyFile.cs"/>
</ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30273668-658c-d411-5b6d-7f58256bb0f3
* Version Independent ID: c8812ae3-0fb1-a30f-02dd-ebc2d28b9dc8
* Content: [How to: Exclude Files from the Build - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-exclude-files-from-the-build?view=vs-2019)
* Content Source: [docs/msbuild/how-to-exclude-files-from-the-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-exclude-files-from-the-build.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by mrlife** [comment]
This is technically [visual-studio-mac/prod]

**Comment by WilliamAntonRohm** [comment]
cc @jmatthiesen, @heiligerdankgesang for awareness per previous comment
