### ISSUE TITLE
No Javascript console  in Visual Studio 2019

### ISSUE THREAD

**Issue by vikas0380** [MicrosoftDocs/visualstudio-docs#6150]
Javascript console has been removed from Visual Studio 2019
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94e35a50-ce68-c40b-fc74-1c30ca1f0d77
* Version Independent ID: 6300dc91-429e-cb7e-df48-c9e40843d5c1
* Content: [Debug a WebView control (UWP) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-a-webview-control?view=vs-2017)
* Content Source: [docs/debugger/debug-a-webview-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-a-webview-control.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@vikas0380 Thanks. If you switch the VS version selector in the upper left from VS 2017 to VS 2019, you get a message indicating the page does not exist in VS 2019 (because the feature was removed).
