### ISSUE TITLE
Comment that python 3.8 is not supported!

### ISSUE THREAD

**Issue by axelande** [MicrosoftDocs/visualstudio-docs#6155]
Tried to follow this guide, spend a rather long time trying to get it to work before I release that Python 3.8 wasn't supported in this mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@axelande -- Axel, thank you for your feedback.  For future reference, see [The Python Environments window](https://docs.microsoft.com/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2019#the-python-environments-window).

There is a Note in [Install Python interpreters](https://docs.microsoft.com/visualstudio/python/installing-python-interpreters?view=vs-2019):
-  Visual Studio supports Python version 2.7, as well as version 3.5 and greater. While it is possible to use Visual Studio to edit code written in other versions of Python, those versions are not officially supported and features such as IntelliSense and debugging might not work.

@JoshuaPartlow -- Joshua, please look into this clarification.

**Comment by JoshuaPartlow** [comment]
Thanks for your feedback @axelande, I'll get a clarification about supported version added to the docs.
