### ISSUE TITLE
Where do you set EnableNETAnalyzers property to true?

### ISSUE THREAD

**Issue by Possibility454** [MicrosoftDocs/visualstudio-docs#6158]
[Enter feedback here]
This page does not explain where or how to set EnableNETAnalyzers property to true, which is the whole point of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04393392-f11e-4825-2d02-ba41e6c6d882
* Version Independent ID: c86598c1-1363-d11b-df15-ca32bf970de5
* Content: [Enable or install .NET analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-net-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-net-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-net-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Possibility454 -- thank you for your question.  Please see this section:
- [MSBuild reference for .NET SDK projects](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#enablenetanalyzers)

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

cc @Mikejo5000 for awareness
