### ISSUE TITLE
Wrong template tag illustrated, should be "static"

### ISSUE THREAD

**Issue by benjaminhigginsliquid** [MicrosoftDocs/visualstudio-docs#6160]
Instructions indicate that you can use `{% load staticfiles %}` to then run `{% static 'site.css' %}`, but the declared template tag is "static", not "staticfiles". Following the instructions verbatim will result in an error from python indicating that "staticfiles" is not a defined tag. 

All mentions of the phrase "staticfiles" in this article should be replaced with "static" to remedy this
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1cd413-a2a8-9cb5-3f3a-94822a96af51
* Version Independent ID: feadb7ab-ebba-051d-e68c-a758235ce514
* Content: [Learn Django tutorial in Visual Studio step 3, static files and pages](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages?view=vs-2019)
* Content Source: [docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by benjaminhigginsliquid** [comment]
Further review indicates that the "staticfiles" tag was deprecated post Django 2.1 and removed in Django 3 (consolidated into "static"). I believe the VS project type(s) associated with Django inherently pull the latest version of Django, so in addition to the doc updates (assuming the doc is desired to reflect Django 3), a separate issue should be considered to update the related VS templates

**Comment by judej** [comment]
Thank you for your input. We agree and have added this work to our planning board. We will go ahead and close this issue, but continue to track the work internally.  If you think this issue should remain open, please reopen it with a comment explaining why. 

We appreciate your investment in our content.
