### ISSUE TITLE
PlatformTarget vs TargetPlatform

### ISSUE THREAD

**Issue by gstech99** [MicrosoftDocs/visualstudio-docs#6164]
The article refers to the target platform (similar to target framework)  but the xml file has <PlatformTarget>. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a80e5d7-2db7-48c0-e8b6-ca8c3ff30017
* Version Independent ID: ad64635b-06d5-1b87-8f02-80cf25c12520
* Content: [MSBuild Target Framework and Target Platform - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-target-framework-and-target-platform.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-target-framework-and-target-platform.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@gstech99 -- thank you for your feedback.  I see the inconsistency you mention, between the prose description and the XML property name.  Even with that hiccup, the article seems clear on the usage.

cc @ghogen for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
