### ISSUE TITLE
Alternative approaches section is incomplete

### ISSUE THREAD

**Issue by yeganer** [MicrosoftDocs/visualstudio-docs#617]
Your list of alternative approaches to creating a Python extension lacks modern tools like pybind (https://github.com/pybind/pybind11). This header only library is a very convenient tool to wrap C++ code for python.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* [Content](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Service: unspecified

**Comment by kraigb** [comment]
@yeganer Thanks for the input. Do you have more information on pybind as would match the other entries in that table? (Though I own the topic, I unfortunately don't have the bandwidth to research the specifics here. Folks in our engineering team might know, and I will consult with them in any case.) Also, when you mention other "modern" tools, are there others besides pybind that should be included?

**Comment by kraigb** [comment]
https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio#alternative-approaches has been updated.

**Comment by Sultaneous** [comment]
Solution builds fine.  But when run, I get this error:
ImportError: dynamic module does not define module export function (PyInit_superfastcode)
