### ISSUE TITLE
Visual studio 2019 Django tutorial out of date

### ISSUE THREAD

**Issue by JanKinable** [MicrosoftDocs/visualstudio-docs#6179]
The documentation on Django tutorial presented doesn't match the visual studio environment anymore.
Example: setting the environment, whilst on page https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2019 the documentation is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bb4dc5-b036-60f4-37aa-8b28b092cac9
* Version Independent ID: 06f64682-5a5a-2aa8-face-14ecc6823038
* Content: [Learn Django tutorial in Visual Studio, step 1, Django basics](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-01-project-and-solution?view=vs-2019)
* Content Source: [docs/python/learn-django-in-visual-studio-step-01-project-and-solution.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-01-project-and-solution.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @JanKinable - Thank you for the feedback. I'm tracking a number of topics that need UI refresh and I'll get this added to the list.
