### ISSUE TITLE
Change the word "topic" to "article"

### ISSUE THREAD

**Issue by tysonn** [MicrosoftDocs/visualstudio-docs#618]
We use the word "article" now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
* Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
* [Content](https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/python/unit-testing-python-in-visual-studio.md)
* Service: unspecified

**Comment by kraigb** [comment]
FYI, there are hundreds of instances of "topic" within the VS documentation that we haven't scrubbed. I'll do my areas (Python and RTVS), but doing it more pervasively is beyond the scope of this one issue and is probably best handled on a subfolder basis.

**Comment by gewarren** [comment]
Change has been merged.
