### ISSUE TITLE
The "example" for opening an existing Word document is incomplete and unusable.

### ISSUE THREAD

**Issue by txwizard** [MicrosoftDocs/visualstudio-docs#6193]
The page at [https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-open-existing-documents?view=vs-2019](url) is a single statement. There is nothing in it about how to create the this object upon which it relies, or its type. As it stands, the example is incomplete on its own.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97a15058-85f8-fecc-f7a9-dc14fd788868
* Version Independent ID: eb12329d-e2d9-3483-518a-3cf81bfbfbda
* Content: [How to: Programmatically open existing documents - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-open-existing-documents?view=vs-2019)
* Content Source: [docs/vsto/how-to-programmatically-open-existing-documents.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-open-existing-documents.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@txwizard -- David, thank you for your feedback.  There appears to be a missing code example in the [Compile the code](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-open-existing-documents?view=vs-2019#compile-the-code) section.

@John-Hart -- John, please look into this issue.

**Comment by txwizard** [comment]
Thank you, @WilliamAntonRohm for your prompt and succinct response. To you and @John-Hart, let me add that I eventually worked it out on my own, and am making great progress on the project.
