### ISSUE TITLE
Suggest using the package when you enable all rules

### ISSUE THREAD

**Issue by meziantou** [MicrosoftDocs/visualstudio-docs#6196]
In my case, I use rules that are not enabled by default using `<AnalysisMode>AllEnabledByDefault</AnalysisMode>` ([doc](https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019)). If I use the package from the SDK, I won't get bug fixes for these rules as explained by Manish Vasani in these comments https://github.com/dotnet/roslyn-analyzers/issues/4552#issuecomment-742652501 and https://github.com/dotnet/roslyn-analyzers/issues/4549#issuecomment-742650676:

> Note that because .NET 5 SDK itself has a much higher bug bar, all fixes to analyzers which are off by default (like CA1508) which were made after the release of initial .NET 5.0 SDK would only be available in .NET 6 SDK or the NuGet package releases of Microsoft.CodeAnalysis.NetAnalyzers on nuget.org.

I think one of these documentation pages should explain this behavior
- https://docs.microsoft.com/en-us/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019
- https://docs.microsoft.com/en-us/visualstudio/code-quality/install-net-analyzers?view=vs-2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04393392-f11e-4825-2d02-ba41e6c6d882
* Version Independent ID: c86598c1-1363-d11b-df15-ca32bf970de5
* Content: [Enable or install first-party .NET analyzers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/install-net-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/install-net-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/install-net-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mavasani Manish, I can update doc with this suggestion if that sounds OK. Probably make the change in just the migration doc.

**Comment by mavasani** [comment]
@Mikejo5000 To clarify, `I won't get bug fixes for these rules` from the .NET SDK is not true, the correct statement being you will get the bug fixes much quicker if you are consuming the analyzers via the NuGet package as opposed to getting them from the .NET SDK itself. You will _eventually_ get all the bug fixes even if you are consuming the analyzers from the SDK. However, the cadence of new .NET SDK releases is much slower as compared to the cadence of us publishing `Microsoft.CodeAnalysis.NetAnalyzers` NuGet package with the same fixes on NuGet.org.

So, this is a valid issue in the sense that we did not list this con of consuming analyzers from the .NET SDK as opposed to NuGet package, but consuming the analyzers from the .NET SDK has the pro that you don't need to manually do any NuGet package version tracking/upgrades, and you will automatically get new analyzers + bug fixes as and when you update your .NET SDK. Latter is indeed mentioned in a NOTE in https://docs.microsoft.com/visualstudio/code-quality/install-net-analyzers

I am not sure how to correctly frame this message, @Mikejo5000 I will let you clarify this appropriately.

**Comment by Mikejo5000** [comment]
Updating the note in the install doc

**Comment by Mikejo5000** [comment]
The update to the install doc should go live by end of day.
