### ISSUE TITLE
Specify Feature Scope in Documentation (e.g. Enterprise+, Professional+, etc.)

### ISSUE THREAD

**Issue by Chiramisu** [MicrosoftDocs/visualstudio-docs#620]
Please start updating your software documentation to include the edition scope of features? For instance, if a particular document is referencing a feature only available in Enterprise, please specify that up front. If only portions of the document are for a particular version, please add inline notes accordingly (similar to how you already make other inline comments in your documentation using the CSS classes "NOTE alert").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14c9c033-b09d-d7bf-3711-c6b603813fff
* Version Independent ID: 952f8bfb-5cc5-39ff-d27d-d06704b9a7c0
* [Content](https://docs.microsoft.com/en-us/visualstudio/modeling/use-code-maps-to-debug-your-applications#start-mapping-the-code)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/modeling/use-code-maps-to-debug-your-applications.md)
* Service: unspecified

**Comment by gewarren** [comment]
@Chiramisu thanks for the feedback. We do try to note edition limitations as much as possible. Are you referring specifically to this [modeling topic](https://docs.microsoft.com/en-us/visualstudio/modeling/use-code-maps-to-debug-your-applications#start-mapping-the-code)?

Sometimes the feature isn't available if you haven't installed the proper workload, and perhaps there are topics that need to be updated with workload information. You can also compare editions [here](https://www.visualstudio.com/vs/compare/).

**Comment by Chiramisu** [comment]
Yes sir, that is correct; specifically for this article.
