### ISSUE TITLE
Instructions not quite right?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/visualstudio-docs#6201]
[Enter feedback here]
"To disable the Diagnostic Tools, start a debugging session, choose Tools > Options > Enable Diagnostic Tools, and deselect the option."

I think this should read "Tools > Options > Debugging > Enable Diagnostic Tools while debugging"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f7e6c9-3f47-4caa-b69f-ae6393bde555
* Version Independent ID: dc59c52a-163f-40fb-c84d-ba7b1b8118b4
* Content: [Tips to improve performance - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-performance-tips-and-tricks?view=vs-2019)
* Content Source: [docs/ide/visual-studio-performance-tips-and-tricks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-performance-tips-and-tricks.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@kgreed We appreciate your feedback. We've updated the text based on your suggestion, so we'll close this issue now, and extend to you our thanks for helping us improve the documentation!
