### ISSUE TITLE
Indicate to remove 'Target' property when 'Scope' is set to 'module'

### ISSUE THREAD

**Issue by lbelloq** [MicrosoftDocs/visualstudio-docs#6208]
Hi,

It would avoid weird errors if the _Module suppression scope_ section explains that the `Target` property must be removed/commented out if the `Scope` property is set to `module`. It's not that hard to deduce, but having it in the documentation would make it easier.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517e8321-aa13-0814-3398-9606d7c2664b
* Version Independent ID: 59efa3c4-ceaf-a384-94af-0f76584efe3f
* Content: [Suppress code analysis violations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019)
* Content Source: [docs/code-quality/in-source-suppression-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/in-source-suppression-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mavasani** [comment]
This sounds a reasonable addition to the documentation - SuppressMessageAttribute with scope module applies to the whole assembly. The `Target` argument to the attribute is used to specify a specific symbol in the assembly, but is only applicable for scopes other than module (such as type, method, field, etc.).
