### ISSUE TITLE
Typo in image

### ISSUE THREAD

**Issue by michaelmaston** [MicrosoftDocs/visualstudio-docs#621]
On this page at the top there are 3 phone screen images in a row.  The last one has a typo that reads "Time of sunriweatherse" instead of "Time of sunrise".  Somehow the word "weather" got inserted into the text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14465304-3ced-6b36-5054-a85ac11e667e
* Version Independent ID: 9d2d9ca3-8d71-b81c-dbbb-bf4b269db034
* [Content](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio#feedback)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md)
* Service: unspecified

**Comment by gewarren** [comment]
@conceptdev does this fall under your area? the typo is in the screenshot itself otherwise I'd fix it.

**Comment by conceptdev** [comment]
@gewarren yes, this page is already due for an edit for other reasons, will be sure the screenshot is fixed (then I'll close this issue).

**Comment by conceptdev** [comment]
The screenshot was updated during a number of fixes, culminating in https://github.com/MicrosoftDocs/visualstudio-docs/commit/8cd749350a94d40de3deb008f7647630c9bc30d9

Thanks @michaelmaston for letting us know!
