### ISSUE TITLE
What are the guarantees of RemoveDuplicates output parameter Filtered?

### ISSUE THREAD

**Issue by chwarr** [MicrosoftDocs/visualstudio-docs#622]
Consider improving the documentation for the MSBuild [RemoveDuplicates](https://docs.microsoft.com/en-us/visualstudio/msbuild/removeduplicates-task) task to discuss the guarantees, if any, of the output parameter `Filtered`.

The reason I'm looking for these details is I'm trying to implement an check in my targets that a given Item doesn't contain duplicates. (If it does, my targets will encounter file sharing violations at build time. I can't just remove the duplicates, as the Item metadata may be significant. The consumer of the targets needs to ensure there are no duplicates.)

I was going to check for this situation by doing something like this:

```xml
<Target Name="CheckNoDuplicateFooItems"
        BeforeTargets="DoSomethingWithFoo"
        Condition="'@(Foo)' != ''">
  <RemoveDuplicates
      Inputs="@(Foo)">
    <Output
        TaskParameter="Filtered"
        ItemName="_FooFiltered"/>
  </RemoveDuplicates>

  <Error Text="The Foo item contains duplicates. Ensure that each Foo item is only included once. (Check for explicit includes and globs that also match.)"
         Condition=" '@(Foo)' != '@(_FooFiltered)' " />
</Target>
```

However, for such a check to work, I need to know that `Filtered` preserves the input order. Or, alternatively, I need to be able to perform a set-comparison in MSBuild. Looking at the current [implementation](https://github.com/Microsoft/msbuild/blob/a9f64ebd108702c3fc65339c66cb124217854524/src/Tasks/ListOperators/RemoveDuplicates.cs#L44-L60), it is order preserving. However, this does not appear to be contractual behavior. For example, there are [no tests](https://github.com/Microsoft/msbuild/blob/6851538897f5d7b08024a6d8435bc44be5869e53/src/Tasks.UnitTests/RemoveDuplicates_Tests.cs#L19) that it is order preserving.

Really, though, something like the .NET SDK's [CheckForDuplicateItems](https://github.com/dotnet/sdk/blob/c6e6bc98e60df7934b6957caf2ef4d3fe2f6702e/src/Tasks/Microsoft.NET.Build.Tasks/CheckForDuplicateItems.cs#L10) task actually solves my problem directly, but
1. I'm not sure whether that's part of the SDKs public interface and
1. I don't know whether this SDK will always be available where my targets are running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a4d1763-973a-e01c-4659-3340a25d0882
* Version Independent ID: bda17ef2-ad9e-dc90-f04a-b9491da81ed1
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/removeduplicates-task)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/removeduplicates-task.md)
* Service: unspecified

**Comment by chwarr** [comment]
If it helps, I've written unit tests to assert the in order behavior, so if a strengthing of the guarantee is deemed appropriate, regressions due to future changes can be minimized. 


If this strengething is something that should be discussed in the MSBuild repository instead/as well, let me know. (The unit tests changes will need to end up there.)

https://github.com/chwarr/msbuild/commit/528bb735bd51db60a11a6e831f315cfd5d1e3fcd

**Comment by rainersigwald** [comment]
Since it has been order-preserving, I agree: we should document that it is order-preserving, and we should test that contract. It'd be great if you could open an MSBuild PR with those tests.

**Comment by chwarr** [comment]
I've created PR #632 to update the documentation.
