### ISSUE TITLE
Add Azure AD Group for VS Subscription Management Not an Option

### ISSUE THREAD

**Issue by ajblackie** [MicrosoftDocs/visualstudio-docs#6220]
I was looking for better ways to automate Visual Studio subscriptions for our employees that need it and was hopeful when I found this page about utilizing Azure AD Groups to do so but I couldn't find that option in our admin portal. 
When I reached out to support they informed me that feature had been removed, but it's still on the page. 

Either remove it from the page, or re-enable the feature
https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-license-bulk#use-azure-active-directory-groups-to-assign-subscriptions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac6f4b8-da9d-5b7b-0c18-b6ed1f85433a
* Version Independent ID: 1ac1ddeb-b1a4-e8d3-9abf-0e629796c5ef
* Content: [Assign licenses to groups of users for Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-license-bulk#use-azure-active-directory-groups-to-assign-subscriptions)
* Content Source: [subscriptions/assign-license-bulk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/assign-license-bulk.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@ajblackie -- thank you for your feedback.

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@ajblackie - Thanks for reaching out.  The feature is still active.  As mentioned in the article, it's only available for trusted agreements.  Do you know if your organization has a trusted agreement?

**Comment by ajblackie** [comment]
Thanks Evan, I'm embarassed that I missed that!

I would have assumed we did, but we must not if that feature isn't showing up.

What's the easiest way for me to check that? I have access to our azure admin portal
________________________________

**Comment by evanwindom** [comment]
@ajblackie  - No worries.  :)  You're definitely not the first person to ask that question.  In fact, I'm in the process of tweaking the article to include this issue in the FAQ.  To see what kind of agreement you have, you can log into the admin portal at https://manage.visualstudio.com/ and click on the agreement details tool, which is the second icon from the top at the far left.

**Comment by evanwindom** [comment]
@ajblackie - You can also tell if your agreement is trusted by checking to see if you are able to over-allocate subscriptions.  If not, the agreement is not a trusted type.  To see overallocations, click the "Overview" button, which is the top one of the four on the far left.  

I've just submitted several changes to the article to clarify this issue.  Thanks for bringing it to my attention!

**Comment by ajblackie** [comment]
Thanks for the clarifications! Looks like we're setup with Pay-As-You-Go Visual Studio, which I assume is not a trusted agreement.

Part of my confusion came from my chat with support stating that the option had been disabled for VS as a whole, but maybe I had misinterpreted what they were saying:

[cid:9a9f8763-1d44-4bed-8e31-cc6cfc536704]

[cid:05ba511f-27b3-470d-9bb8-559b798230bb]


________________________________

**Comment by evanwindom** [comment]
#please-close
