### ISSUE TITLE
Please explain where the git command line went after introducing this new Git Changes tab

### ISSUE THREAD

**Issue by zmarty** [MicrosoftDocs/visualstudio-docs#6221]
Please explain where the git command line went after introducing this new Git Changes tab

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb36e99-33ae-20a2-a12d-a3e5d056a153
* Version Independent ID: b5a43c4a-c8bb-2c8a-56b3-09b12a713e58
* Content: [The Git experience in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@zmarty Thanks for your inquiry; we'll circle back with you, soon.

@prnadago @Taysser-Gherfal FYI

**Comment by prnadago** [comment]
You can open the command line through the Git menu option - 
![image](https://user-images.githubusercontent.com/30607258/105639403-04ae4080-5e2d-11eb-9c37-0778e63c3b76.png)

**Comment by TerryGLee** [comment]
@prnadago Thanks for answering the inquiry; we'll close this issue now (although, let's make sure we document this in the content that we continue to update on our new home for Git-related pages at [Visual Studio version control documentation](https://docs.microsoft.com/visualstudio/version-control/)).
