### ISSUE TITLE
bridge-quickstart.sh fails with  This chart location is deprecated

### ISSUE THREAD

**Issue by TomGeske** [MicrosoftDocs/visualstudio-docs#6223]
When following steps as described:

```
git clone https://github.com/Microsoft/mindaro
cd mindaro
chmod +x ./bridge-quickstart.sh
./bridge-quickstart.sh -g MyResourceGroup -n MyAKS

```
I'm getting the following message as result:

```
helm install traefik ingress controller in bikeapp
Error: template: deprecation/templates/NOTES.txt:10:3: executing "deprecation/templates/NOTES.txt" at 
*******************************************************
This chart location is deprecated. Learn more here: 
https://helm.sh/blog/charts-repo-deprecation/    
*******************************************************
error calling fail:
*******************************************************
* This chart location is deprecated. Learn more here: *
* https://helm.sh/blog/charts-repo-deprecation/       *
*******************************************************

```
seems like the wrong chart repo is being referenced.

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25b96907-35cf-ff1f-d7ad-a231aa78418b
* Version Independent ID: 620e59a0-5658-9a05-c177-8d0687656e2a
* Content: [Use Bridge to Kubernetes with Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/bridge-to-kubernetes?view=vs-2019#feedback)
* Content Source: [docs/containers/bridge-to-kubernetes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/bridge-to-kubernetes.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by greenie-msft** [comment]
This has been addressed by the product team: https://github.com/microsoft/mindaro/commit/199b26ce8a40472a692be0113266b70365bc2648

**Comment by TomGeske** [comment]
In my case I also needed to remove:

`--version 1.85.0`

![image](https://user-images.githubusercontent.com/3658893/103160055-dc510900-47d0-11eb-8e8f-f3387f0ab8ec.png)

**Comment by TomGeske** [comment]
Just tested latest version and it worked for me. Thanks for fixing it!
