### ISSUE TITLE
MSBuild Item Include attribute is documented as required, but is not required

### ISSUE THREAD

**Issue by chwarr** [MicrosoftDocs/visualstudio-docs#623]
The [table](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild#attributes-and-elements) indicates that the Item `Include` attribute is required. However, as the [Update example shows](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild#examples), this is not the case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 434a3db6-e5c1-51c7-4c80-24e0ba5a01ec
* Version Independent ID: f8850e9c-8e55-16f1-da9e-65b08e0325d4
* [Content](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild#examples)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/item-element-msbuild.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
Updating doc

**Comment by Mikejo5000** [comment]
Fixed on master branch. It should go live tomorrow

**Comment by chwarr** [comment]
Hrm... I don't see such a change.

https://github.com/MicrosoftDocs/visualstudio-docs/commits/master/docs/msbuild/item-element-msbuild.md

Am I looking at the wrong branch?

**Comment by Mikejo5000** [comment]
The fix was on the private repo master branch. Can you open this? https://review.docs.microsoft.com/en-us/visualstudio/msbuild/item-element-msbuild?branch=master#examples
If not, please re-open and tomorrow's merge should close this and notify you. I will plan to wait to close issues until the live merge next time. Thanks!

**Comment by chwarr** [comment]
I can see the changes on the link you provided.
No, I wasn't able to re-open this issue.

I'm good now.
