### ISSUE TITLE
Download the ZIP link points to localhost

### ISSUE THREAD

**Issue by imamitjain** [MicrosoftDocs/visualstudio-docs#6232]
`Download the ZIP` link points to localhost URI. It should suppose to be repository link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by msebolt** [comment]
@imamitjain Thank you for the feedback.

Please review the step 1 information that states, `The install process makes the ZIP file containing the sample available at the localhost address`.  

If there are still issues, please comment below and we can investigate further.

**Comment by imamitjain** [comment]
@msebolt Following steps has worked for me.

1. I installed docker using [Docker for Windows installation documentation](https://docs.docker.com/docker-for-windows/install/) 
2. Run `docker run -d -p 80:80 docker/getting-started` as stated in [Getting started](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/docker-tutorial) to get `app.zip`

I think, current documentation for Step 1. assumes that installing docker also starts `getting-started` docker container which is not right. We should mention above docker run command in step 1 of documentation for better customer experience.

**Comment by WilliamAntonRohm** [comment]
@imamitjain -- Amit, thank you for your follow-up.  As this is working for you, I am closing this issue.  You are welcome to @ mention me for any further information.

cc @ghogen for awareness -- see also issue #5998.
