### ISSUE TITLE
License notifications using AAD group sync

### ISSUE THREAD

**Issue by audunsolemdal** [MicrosoftDocs/visualstudio-docs#6233]
Hello, specific question regarding email notifications

When users are synced with AAD groups as opposed to adding individual users - do users still get email notifications for newly assigned/unassigned licenses?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac6f4b8-da9d-5b7b-0c18-b6ed1f85433a
* Version Independent ID: 1ac1ddeb-b1a4-e8d3-9abf-0e629796c5ef
* Content: [Assign licenses to groups of users for Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-license-bulk#use-azure-active-directory-groups-to-assign-subscriptions)
* Content Source: [subscriptions/assign-license-bulk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/assign-license-bulk.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@audunsolemdal -- Audun, thank you for your question.

@evanwindom -- Evan, please look into this issue.

**Comment by evanwindom** [comment]
@audunsolemdal - Hi, Audun.  Thanks for reaching out.  It's my understanding that the assignment triggers the notification, regardless of whether the assignment is individual, bulk, or Azure AD linked.  But I'll verify that with our engineering team.  Given that we're in the midst of the holidays, though, there may be a delay in the response.

**Comment by audunsolemdal** [comment]
@evanwindom  any updates?

**Comment by evanwindom** [comment]
@audunsolemdal - Hi Audun.  Sorry for the late response.  I did confirm that the assignment triggers a notification, regardless of how the assignment is done.

**Comment by evanwindom** [comment]
#please-close
