### ISSUE TITLE
MSBuild Exec task implements undocumented UseUtf8Output parameter

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#6237]
A `UseUtf8Output` parameter was added to the `Exec` task in <https://github.com/dotnet/msbuild/pull/442> but that has not been documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb479ee7-d34c-dd5d-6843-4abdec6c3894
* Version Independent ID: 40cd6644-b061-335e-7bd4-6beede753c5d
* Content: [Exec Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019)
* Content Source: [docs/msbuild/exec-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/exec-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@KalleOlaviNiemitalo Thanks - the parameter is UseUtfEncoding. We need to add this to the documentation.

**Comment by KalleOlaviNiemitalo** [comment]
@ghogen, where do you see the "UseUtfEncoding" name? [Searching for that in the MSBuild repo](https://github.com/dotnet/msbuild/search?q=UseUtfEncoding) doesn't find anything.

**Comment by ghogen** [comment]
@KalleOlaviNiemitalo It's actually UseUtf8Encoding - sorry!
