### ISSUE TITLE
Publish to Azure from Visual Studio 2019 for Mac Not Covered

### ISSUE THREAD

**Issue by cleicester** [MicrosoftDocs/visualstudio-docs#6238]
The document doesn't cover an equivalent way to import a downloaded Azure deployment settings into Visual Studio 2019 for Mac. It would be useful if this were included in a section on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a4cdce0-fb0c-5c4f-13a3-b24d39662b64
* Version Independent ID: 70146337-d649-c442-0a37-0810f3dfc9a8
* Content: [Publish to Azure by importing publish settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/tutorial-import-publish-settings-azure?view=vs-2019)
* Content Source: [docs/deployment/tutorial-import-publish-settings-azure.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/tutorial-import-publish-settings-azure.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
VS for Mac is quite a different IDE, so the the VS for Mac docs have a different location. Please see these [deployment docs](https://docs.microsoft.com/en-us/visualstudio/mac/web-app-deployment?view=vsmac-2019) for VS for Mac.

**Comment by Mikejo5000** [comment]
Re-opening, and correcting the product label.

**Comment by sayedihashimi** [comment]
We have a tutorial for that over at https://docs.microsoft.com/en-us/visualstudio/mac/publish-app-svc?view=vsmac-2019. I'm not sure what the best way to integrate that into this doc is. It would be good to have a link in this doc pointing the the Visual Studio for Mac doc at least. @Mikejo5000 thoughts?
