### ISSUE TITLE
Visual Studio 2017 no longer creates the Registry Entries

### ISSUE THREAD

**Issue by stuartbronk** [MicrosoftDocs/visualstudio-docs#624]
How can you modify the ChannelOperationTimeout when using Visual Studio 2017 as this does not support these registry keys ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb74da18-3da7-8f5e-4433-62588cc744e9
* Version Independent ID: 2544b951-5c44-a722-b6f6-ef3b4e11c110
* [Content](https://docs.microsoft.com/en-us/visualstudio/sharepoint/debugging-extensions-for-the-sharepoint-tools-in-visual-studio)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/sharepoint/debugging-extensions-for-the-sharepoint-tools-in-visual-studio.md)
* Service: unspecified

**Comment by TerryGLee** [comment]
@stuartbronk Thanks for your feedback; we appreciate it. We've got this issue listed in our backlog queue to investigate.

**Comment by John-Hart** [comment]
@stuartbronk Visual Studio 2017 is using a private registry.  See this doc for information on how to add the registry entries: [Tools for detecting and managing Visual Studio instances](https://docs.microsoft.com/en-us/visualstudio/install/tools-for-managing-visual-studio-instances?view=vs-2017)
