### ISSUE TITLE
Add see also link to SDK properties reference

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#6242]
Consider adding a link to https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props. I see there's a see also link to https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props on the common msbuild *items* page, but I think it should be on this properties page instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@gewarren Thanks, will add that.
