### ISSUE TITLE
$pragma directives missing in suppressions

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/visualstudio-docs#6246]
`#pragma warning` directives can be used to suppress code analysis violations.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517e8321-aa13-0814-3398-9606d7c2664b
* Version Independent ID: 59efa3c4-ceaf-a384-94af-0f76584efe3f
* Content: [Suppress code analysis violations - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019)
* Content Source: [docs/code-quality/in-source-suppression-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/in-source-suppression-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mavasani** [comment]
Agreed. Earlier, CA violations from FxCop could only be suppressed with SuppressMessageAttributes. With the move to port CA rules to Roslyn analyzers, inline pragma suppressions are also a valid way to suppress diagnostics. We should add a section for it in the documentation.

**Comment by paulomorgado** [comment]
Although there are images showing `#pragma` directives, they are not mentioned in the text.

Is this code correct?

````csharp
[Scope:SuppressMessage("Rule Category", "Rule Id", Justification = "Justification", MessageId = "MessageId", Scope = "Scope", Target = "Target")]
````

/cc @mavasani

**Comment by mavasani** [comment]
@paulomorgado They do seem to be mentioned in this section: https://docs.microsoft.com/en-us/visualstudio/code-quality/in-source-suppression-overview?view=vs-2019#suppress-violations-in-source-code

Do you feel the section title should be more explicit about in source suppressions actually being `#pragma` directives?

**Comment by paulomorgado** [comment]
My bad! Searched the page but my typing dyslexia might have kicked in.

There have been some changes to the page since I reported this, but not linked to this issue.
