### ISSUE TITLE
Outdated method

### ISSUE THREAD

**Issue by HSNHK** [MicrosoftDocs/visualstudio-docs#6248]
Hello 
Django documentation prefers now {% load static %}.

{% load staticfiles %} works but I think it is deprecated.

https://docs.djangoproject.com/en/dev/ref/templates/builtins/#static

Unfortunately, this method does not work in newer versions of Django and causes errors.
The error is as follows:
TemplateSyntaxError at /
'staticfiles' is not a registered tag library
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 485e6157-bf3f-1065-d944-9860f198662c
* Version Independent ID: 8daa9161-23cb-8bfb-b736-6695b6e50ee8
* Content: [Learn Django tutorial in Visual Studio step 4, web project template](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-04-full-django-project-template?view=vs-2019)
* Content Source: [docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Thank you for your input. We agree and have added this work to our planning board. We will go ahead and close this issue, but continue to track the work internally. If you think this issue should remain open, please reopen it with a comment explaining why.

We appreciate your investment in our content.
