### ISSUE TITLE
Download link returns a 404 error :)

### ISSUE THREAD

**Issue by tanicFilip** [MicrosoftDocs/visualstudio-docs#6255]
Download installer link returns a 404 error. Perhaps the page was not updated soon? :)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35176f2-ca94-7bb8-08a5-9e415d364ef3
* Version Independent ID: a9f184a6-78b9-315b-4a02-1c93bd4c3940
* Content: [Getting Started with Visual Studio Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity?pivots=windows)
* Content Source: [gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by WilliamAntonRohm** [comment]
@tanicFilip -- thank you for finding that typo.  I believe the intended link is [Install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio?view=vs-2019) and I am updating this article.
