### ISSUE TITLE
翻譯問題

### ISSUE THREAD

**Issue by averywu** [MicrosoftDocs/visualstudio-docs#6256]
「如果您尚未這麼做，請開啟終端機並移至 app 具有的目錄 Dockerfile 。」

這句應該翻成 「如果您尚未這麼做，請開啟終端機並移到您下載並解壓縮後的 app 目錄中去建立 Dockerfile 檔案」

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker 教學課程-第1部分：建立和執行 todo 清單範例應用程式](https://docs.microsoft.com/zh-tw/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs.zh-tw/blob/live/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
(Bing translation)
"If you haven't already done so, open the terminal and move to dockerfile, which the app has." 」

This sentence turns into "If you haven't done that yet, open the terminal and move to your next app and solve it壓縮 to create a Dockerfile file"

@averywu -- Avery, thank you for your feedback.  

@ghogen -- Gordon, please look into this potential clarification.

**Comment by ghogen** [comment]
@JasonCard This might be an issue with the translation. Should we move it to the visualstudio-docs.zh-cn repo?

**Comment by JasonCard** [comment]
@averywu @WilliamAntonRohm @ghogen Thank you for your feedback. This article is machine translated, so please understand that some translation quality issues are expected. While we are working to improve our MT engine, it's not scalable to fix all MT issues. It appears that this translation issue could be considered minor, so please go ahead to close this issue. For MT translation that's difficult to understand, we would encourage users to use the "Read in English" toggle to quickly refer back to the original sentence in English.
