### ISSUE TITLE
MSBUILDEMITSOLUTION=0 doesn't work, environment variable needs to be removed

### ISSUE THREAD

**Issue by vbaderks** [MicrosoftDocs/visualstudio-docs#6257]
It may be useful to add the remark that MSBUILDEMITSOLUTION=0 doesn't work. The environment variable needs to be removed completely. See also: https://github.com/dotnet/msbuild/issues/5166

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50dca6ea-13b0-25a5-5610-15528bb97b0d
* Version Independent ID: 2dbcef84-bad9-310b-89b1-d3a3236bc829
* Content: [Use MSBuild.exe to build specific targets in solutions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe?view=vs-2019)
* Content Source: [docs/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/how-to-build-specific-targets-in-solutions-by-using-msbuild-exe.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@vbaderks -- Victor, thank you for your feedback.  For your suggestion to remove that environment variable, please consider:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

@ghogen -- Gordon, please look into this potential remark.

cc @rainersigwald for awareness

**Comment by rainersigwald** [comment]
The product-side fix was rejected as low-priority in that MSBuild bug.

I feel like this line in the doc covers the request:

> Do not build with this environment variable set unless you need this internal view. 

But we could consider changing the doc to say "look in the binlog" instead. Though that's a bigger change.

**Comment by exoosh** [comment]
Hi, did I get it right that this means the variable is here to stay for whenever we need it? Personally I only ever use it for the `=1` case, though (to see what's going on under the hood).

**Comment by rainersigwald** [comment]
@exoosh Yes, we expect to preserve the `MSBUILDEMITSOLUTION=1` behavior for the foreseeable future.
