### ISSUE TITLE
The bits about header propagation might need some clarifiying

### ISSUE THREAD

**Issue by rytmis** [MicrosoftDocs/visualstudio-docs#626]
The previous step stated this about HeaderPropagatingHttpClient:

> We'll see later how this facilitates a more productive development experience in team scenarios.

while this page says:

> Note that this routing requires propagation headers to be forwarded in your app code, as illustrated in the previous step of this guide.

which is sort of anticlimactic, and I think also obscures the importance of _using header propagation for all inter-container requests_. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f6962d2-a42a-ea79-bcda-d4adcaf2406c
* Version Independent ID: 9da717ab-b573-b81f-45f0-2c2a3a5b66eb
* [Content](https://docs.microsoft.com/en-us/visualstudio/connected-environment/get-started-netcore-visualstudio-06)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/connected-environment/get-started-netcore-visualstudio-06.md)
* Service: connected-environment

**Comment by ghogen** [comment]
@johnsta

**Comment by ghogen** [comment]
This doc is no longer in the visualstudio-docs repo.
