### ISSUE TITLE
Enforce code style in CI/CD pipeline

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#6268]
Does that statement need to be updated to say that [it is possible with the .NET 5 SDK](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview?view=vs-2019#code-style-analysis)?

"Conventions that are set in an EditorConfig file cannot currently be enforced in a CI/CD pipeline as build errors or warnings. Any style deviations appear only in the Visual Studio editor and Error List."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [EditorConfig settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mavasani** [comment]
Agreed - we should either remove this note or reword it as @gewarren suggested.
