### ISSUE TITLE
include `"compileOnSave": true` in tsconfig.json 

### ISSUE THREAD

**Issue by shockylemi** [MicrosoftDocs/visualstudio-docs#6269]
>In Step 3. under **Add Some Code**
tsconfig.json example better include `"CompileOnSave": true` by default.

change the tsconfig.json code snippet with this one:

```json

{
  "compileOnSave": true,
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "wwwroot/js"
  },
  "include": [
    "scripts/**/*"
  ]
}

```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68483bc8-45dc-fc2e-b289-2901a70461ff
* Version Independent ID: 5167502a-bd55-8927-5656-1c4f107884d7
* Content: [Create an ASP.NET Core app with TypeScript - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2019)
* Content Source: [docs/javascript/tutorial-aspnet-with-typescript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-aspnet-with-typescript.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review [private PR 7715](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7715).
