### ISSUE TITLE
New Git Experience and Azure Dev Ops

### ISSUE THREAD

**Issue by davrob01** [MicrosoftDocs/visualstudio-docs#6273]
The New Git Experience documentation does not mention how to properly Publish a new local repo to Azure Dev Ops. In the old system, there was a convenient button and menu for this purpose in Team Explorer. I expected to see something similar in the new Git Experience. But instead I am finding Git Hub integrations only. So I think you either need to add the integrations, or at least mention the steps to properly publish (or "connect", whatever you want to call it) to Azure Dev Ops from Visual Studio. I realized that the new way to do this via the new UI is to go to Git -> Push to Git Service... -> Other -> Existing remote and then paste the URL of the Azure Dev Ops repo (which I got from navigating to the repo from the Azure Dev Ops portal for the project at hand). If you guys want to adequately continue to support Azure Dev Ops, I think you should make this more clear, either in this documentation, or by adding instructions in Visual Studio itself. 

Thank you very much!
-David

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb36e99-33ae-20a2-a12d-a3e5d056a153
* Version Independent ID: b5a43c4a-c8bb-2c8a-56b3-09b12a713e58
* Content: [The Git experience in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@davrob01 -- David, thank you for your well-considered feedback.

@TerryGLee -- Terry, please look into this issue.

**Comment by prnadago** [comment]
Thanks @davrob01, you're correct about using the Existing remote option. We have that documented with the line - 'Or, you can link your repository with any existing empty remote repository on any other Git provider by using the Existing remote option.'
But maybe @TerryGLee, we can further clarify by mentioning Azure DevOps specifically in this sentence.

With regards to implementing the functionality in VS, we do have an open suggestion ticket that we haven't gotten to yet, but are reviewing - https://developercommunity.visualstudio.com/idea/1112915/create-and-push-a-new-repo-to-azure-devops-in-the.html

**Comment by TerryGLee** [comment]
@davrob01 We've further clarified the info in the sentence that @prnadago mentioned. It now reads as follows:

"Or, you can link your local project with an existing empty remote repository on Azure DevOps or any other Git provider by using the **Existing Remote** option."

We've also published a new page that might be of interest to you, [**Side-by-side comparison of Git and Team Explorer**](https://docs.microsoft.com/visualstudio/ide/git-team-explorer-feature-comparison?view=vs-2019).

Thanks once again for your feedback, and for helping improve the documentation!
