### ISSUE TITLE
TreatAsLocalProperty seems like has no effect in SDK format csproj files

### ISSUE THREAD

**Issue by stpatrick2016** [MicrosoftDocs/visualstudio-docs#6274]
When running msbuild from the command line and specifying property with **-p**, it overrides project properties. It is possible to cancel such behavior by setting TreatAsLocalProperty. It works correctly with the old csproj format but seems has no effect on projects with the new SDK format. 

Tried that with VS2017 and property OutDir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2d4b23-f7b9-7f95-0690-7d528fb4b323
* Version Independent ID: 2c45725e-2689-bfd3-001b-ea1f7043128a
* Content: [Project Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/project-element-msbuild?view=vs-2019)
* Content Source: [docs/msbuild/project-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/project-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@rainersigwald - This looks like MSBuild product feedback.

**Comment by ghogen** [comment]
Entered product issue.
https://github.com/dotnet/msbuild/issues/7656
