### ISSUE TITLE
Convert to FAQ page type

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#6278]
Consider converting this page to the new FAQ page type for SEO.

https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-faq-guide?branch=master

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ca23766-4d28-9392-2119-1ed933c82ced
* Version Independent ID: c5bd6fc4-161d-f1b7-6aa2-9fc1af46a8b4
* Content: [Frequently Asked Questions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/devinit/faq?view=vs-2019)
* Content Source: [docs/devinit/faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/devinit/faq.md)
* Product: **visual-studio-windows**
* Technology: **devinit**
* GitHub Login: @andysterland
* Microsoft Alias: **andster**

**Comment by j-martens** [comment]
This page will be deleted. #Please-close
