### ISSUE TITLE
Screenshots need to be adjusted as the checkbox position has changed in latest version of VS

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#628]
"Enable full solution analysis" checkbox is now the first checkbox in the Text Editor -> C# -> Advanced page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c86ab93-c317-1fb8-16a8-d221138435d1
* Version Independent ID: 71cbbca2-44d0-8f69-1937-a286fef52bdb
* [Content](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-enable-and-disable-full-solution-analysis-for-managed-code#feedback)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/how-to-enable-and-disable-full-solution-analysis-for-managed-code.md)
* Service: unspecified

**Comment by mavasani** [comment]
![image](https://user-images.githubusercontent.com/10605811/36820709-1e4e651a-1ca4-11e8-9fa9-b987ec56c006.png)

**Comment by gewarren** [comment]
@mavasani thanks Manish!

**Comment by gewarren** [comment]
Fixed with https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/1670.
