### ISSUE TITLE
F1 leads to this page, which is irrelevant. Help seems to be badly broken.

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/visualstudio-docs#6282]
[Enter feedback here]
Whenever I hit "F1" in a Visual Studio 2019 IDE window, while a C++ identifier  is highlighted, instead of getting help on that keyword, I end up here on "Work with solutions and projects" which isn't so useful.

Most versions of Visual Studio had a robust help system, where hitting F1 on an API call, for example, would show the MSDN documentation on that API call. VERY useful. Or, it used to be.

If my Visual Studio is misconfigured, it's fairly vanilla, so there should be something on this page like "did you end up here looking for help?" and a link to the correct setting.

I notice this "suggestion":
https://developercommunity.visualstudio.com/idea/529598/fix-context-sensitive-help-f1-in-visual-studios-ma.html

It's basic common sense. As johnb reported, F1 used to work pretty well, and MSDN was known as a good place to go for developer information. MSDN is becoming increasingly irrelevant. This makes me sad. 

        == John ==

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d9f53c-6ece-ea3c-9a51-9edd0efeebe3
* Version Independent ID: 9c927a8e-3ebd-0c8a-76cc-9b1c980b98a3
* Content: [Work with solutions and projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/creating-solutions-and-projects?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(FIGURETOPRINT%252FSYSTEM_PROCESSOR_PERFORMANCE_INFORMATION_R);k(SYSTEM_PROCESSOR_PERFORMANCE_INFORMATION_R);k(SolutionItemsProject);k(DevLang-C%252B%252B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/creating-solutions-and-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/creating-solutions-and-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@jgwinner Thanks for your feedback; we'll investigate and report back.

**Comment by ghogen** [comment]
@jgwinner Are you seeing this issue with a specific subset of identifiers, or for all identifiers you've tried.  The functionality appears to work in general in my VS 2019 instance, but the behavior is dependent on metadata that relates to each individual string, be it an identifier, language keyword, operator, etc. I tried with "printf" and "GetFileAttributes" in the windows API and both gave the correct pages.
@corob-msft

**Comment by jgwinner** [comment]
All identifiers.

Huh - I just tried printf(), and it actually went to the printf page.

*sigh* I can't duplicate the bug now.

I will say that my FireFox and Edge browsers were occasionally acting weird - refusing to open pages, etc. I had plenty of system RAM. I have noticed (I have a LOT of open web pages) that when this happens, some resource - often handles - are leaked, and the system gets, hard to explain, "weird". Outlook has a bad handle leak, and over time the system becomes unresponsive.

Maybe something in Visual Studio wasn't passing the right URL through.

Anyway, sorry for the trouble - you can close this.

Ford doesn't tell you if you've been in an accident with your car to go home, and restart your trip, but it does appear the fix for this is for me to reboot. Memory leaks in Edge and Firefox, and Outlook isn't your problem :) So you can close this!

        == John ==

**Comment by ghogen** [comment]
@jgwinner Check the focus in the IDE. It has to be on the editor window. We are seeing data that suggests that this is a common issue, with focus being on some other window, like Solution Explorer.

**Comment by jgwinner** [comment]
It was solidly in the IDE, I had just double clicked to highlight the keyword.

Honestly - I was surprised it worked as I'm using some API's that are in the "don't use this" internal windows headers. But they did!

I'll do more work if I can duplicate it again when the system gets crufted up. 

        == John ==
