### ISSUE TITLE
What is the difference between pre-production and production inventory?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/visualstudio-docs#6289]
The documentation does not give a definition of pre-production inventory. What is the difference between pre-production and production inventory? Licenses are assigned to users to use them. Where is the concept of pre-production inventory coming in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 356558a8-2479-d26d-7d80-6f0291945bb3
* Version Independent ID: fc8fdc26-3a24-487f-71e8-ec5331f0262d
* Content: [Pre-production inventory in Visual Studio subscription](https://docs.microsoft.com/en-us/visualstudio/subscriptions/admin-inventory)
* Content Source: [subscriptions/admin-inventory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/admin-inventory.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@Anand-Moghe -- Anand, thank you for your questions.

@evanwindom -- Evan, please look into this issue.

**Comment by evanwindom** [comment]
@Anand-Moghe - Hi Anand.  Thanks for your question.  It may be helpful to think of it as "non-production" rather that "pre-production".  With a few exceptions, the software included with the subscriptions - along with the Azure credits, are licensed for development and testing use only.  The licenses do not cover production use.  The full terms of the license can be found at https//aka.ms/licensing.

**Comment by Anand-Moghe** [comment]
@evanwindom Thanks for the explanation. I think there should be an explanation in a info note somewhere on the page why we are calling it as pre-production or non-production. Because the title will be somewhat incomprehensible to someone who is coming to this page and doesn't really understand Microsoft inherent licensing conditions/terms.

**Comment by evanwindom** [comment]
@Anand-Moghe Thanks for the suggestion.  I've annotated the article as follows:  
"Visual Studio subscriptions software is not licensed for production environments, including any environment accessed by end users for more than acceptance testing or feedback, an environment connecting to a production database, supporting disaster recovery or production backup, or used for production during peak periods of activity. Exceptions to this include specific benefits for certain subscription levels, outlined in the [Visual Studio Licensing White Paper](https://aka.ms/vslicensing)."

**Comment by evanwindom** [comment]
#please-close
