### ISSUE TITLE
IE / Edge is using Windows settings to override locale.

### ISSUE THREAD

**Issue by joacim-boive** [MicrosoftDocs/visualstudio-docs#629]
I consider this to be incorrect behaviour.

Ex;
const sum = 10000;
sum.toLocaleString('sv-SE', {
  style: 'currency',
  currency: 'SEK'
});

Should give: 10 000,00 kr
But gives: 10.000,00 kr 

Note the dot (.) as thousand separator.
This is because of the incorrect(?) setting in Windows: Region and Language / Customize Format / Currency / Digit grouping symbol.

This is set to a dot (.) despite setting everything to Swedish the thousand separator is still incorrect by default.
The only chance to correct this is to manually change it - which won't happen out in the real world.

Every other modern browser respects the locale and doesn't care about the OS settings (until you specify undefined as locale) which is the correct behaviour.

The bug is the same in Windows 7 / 10 and IE11 and Edge (only onces tested)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f00ea08c-f089-5023-68e8-a0a55aa03708
* Version Independent ID: 37d53051-d099-79dd-6838-100f00163e54
* [Content](https://docs.microsoft.com/en-us/scripting/javascript/reference/intl-numberformat-object-javascript)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/scripting-docs/javascript/reference/intl-numberformat-object-javascript.md)
* Service: unspecified

**Comment by gewarren** [comment]
@Mikejo5000 can you take a look at this and escalate as appropriate? And perhaps route the OP to product feedback if this is more about the product than the documentation.

**Comment by JennieHubbard** [comment]
@joacim-boive Thank you so much for that feedback! Looks like the team is sharing your feedback with the engineering team as well.

**Comment by joacim-boive** [comment]
@JennieHubbard My pleasure. :)
Another solution to this problem is to install the Swedish Language pack. When that is installed the dot (.) thousand separator is automatically replaced with a space ( ) without further user intervention.
(Only tested on Windows 10)

Personally, although, I'm a Swede I prefer my software in English and would normally not do that then.

**Comment by JennieHubbard** [comment]
@joacim-boive Interesting! Good to know. 👍

**Comment by Mikejo5000** [comment]
@bterlson Bug in browser or Intl.NumberFormat? Can we route to the correct people?

**Comment by bterlson** [comment]
My guess is this is fixed in ChakraCore bits which use ICU rather than Windows Globalization APIs. Perhaps @dilijev can confirm.

**Comment by dilijev** [comment]
I think @jackhorton might have better visibility on this in particular, but I'd expect a lot of things to be fixed (or at least different) with the migration to ICU instead of Windows Globalization. I believe we were discussing with those folks how to handle the JS/Intl/ICU semantics to pick up Windows user preferences when applicable as well.

**Comment by jackhorton** [comment]
@jefgen for insight on ICU + user locale preferences.

I think this is probably an issue with Windows Globalization data. A canary build of Chakra + ICU 59 formats this as `10&nbsp;000,00&nbsp;kr`, which is much closer to what is expected here (I don't know any Swedish and thus don't have the language pack installed :) ).

I will add this to our test cases but I don't think its an Edge issue in particular

**Comment by jefgen** [comment]
Currently ICU basically ignores any user preferences that might have been set in the OS -- other than picking up the user's preferred locale/language. (The inbox/Kit version will use the UPLL, whereas the public non-UWP version will use the NLS User Locale).

This isn't really an Edge issue, as you pointed out the default thousands separator in the Windows CPL seems wrong to you. This is actually more of a locale "data" issue with the sv-SE locale in Windows instead.

What is happening with the Chakra+ICU scenario that @jackhorton mentioned is that ICU essentially ignores the settings in the Windows CPL. So what you are getting from Chakra+ICU is really the 'unmodified' data from CLDR (the Unicode Common Locale Data Repository) for the currency format.

We do import the CLDR data for the Windows NLS data, so you would also get the same data from NLS as well, **except** that there is currently an override in place for the format on the NLS side.

I've filed an internal bug for investigating if this override should possibly be removed, as based on your report it seems that CLDR has the correct data, and NLS does not.

**Comment by ghogen** [comment]
As this is being tracked internally, I will close this issue. Thanks for your feedback.

**Comment by jackhorton** [comment]
If you have a recent Insider build of Windows (anything greater than ~17670, I think), the correct answer is given in Edge, as we switched to using ICU for locale-sensitive methods. I will let @jefgen comment on the status of updating the NLS data, however my understanding is that such a fix likely would _not_ come to already-released versions of Windows.

**Comment by jefgen** [comment]
The internal bug to change the NLS data should hopefully be in the next upcoming release of Windows.
However, as @jackhorton pointed out, locale data changes are generally not serviced down-level.
Unfortunately, this likely means that you will need to work around this issue.
(cc: @targetdev-bot as FYI.)
