### ISSUE TITLE
Lack of information on updated prereqs for a Visual Studio 15.* minor update

### ISSUE THREAD

**Issue by alfredmyers** [MicrosoftDocs/visualstudio-docs#630]
Given the problem stated at https://developercommunity.visualstudio.com/content/problem/46789/stuck-with-vs2017-on-windows-server-2012.html **it seems** the Visual Studio 2017 installer updated it's pre-reqs from Windows Server 2012 to Windows Server 2012 R2 during one of the minor release updates.

But, I haven't found any mention of this in any of the release notes for versions 15.1 through 15.5.x.
So know I'm in doubt if this information is missing in the corresponding release notes or if Visual Studio 2017 RTM already checked for the Windows Server 2012 R2 as the minimum server OS and somebody somehow found a way to install it anyway on Windows Server 2012.

**Comment by TerryGLee** [comment]
@alfredmyers Thanks for your feedback. We do have a System Requirements page, here: [https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs), which includes a mention of Windows Server 2012 R2. The [System Requirements](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs) is listed in tandem with the [Release Notes](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes). However, we'll pass along your feedback to the appropriate channels.

**Comment by alfredmyers** [comment]
@TerryGLee Thanks for the quick response. Later down https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs, where it is stated 

> Microsoft Visual Studio Build Tools 2017
> The Build Tools support the same system requirements as Visual Studio with the following changes:
>     Also installs on Windows Server 2008 R2 SP1

Would that be Windows Server 2008 R2 SP1 **and later**? And if that is the case would it include Windows Server 2012 with the latest service pack?

**Comment by PoulChapman** [comment]
@alfredmyers -- Visual Studio 2017 has never supported Windows Server 2012 or Windows Server 2008 R2. It may be as you note that users found a way to install on Windows Server 2012 despite the stated system requirements. As @TerryGLee mentions, the full supported system requirements can be found at https://docs.microsoft.com/en-us/visualstudio/productinfo/vs2017-system-requirements-vs. 

Thanks!
-Paul Chapman
Visual Studio Program Manager
