### ISSUE TITLE
Csc task has many undocumented parameters

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#6301]
The documentation of the Csc task omits several parameters that are however set by the "CoreCompile" target in Microsoft.CSharp.Core.targets:

- AdditionalFiles
- Analyzers
- ChecksumAlgorithm
- CodeAnalysisRuleSet
- EmbedAllSources
- EmbeddedFiles
- ErrorEndLocation
- ErrorLog
- Features
- HighEntropyVA
- Instrument
- PathMap
- PublicSign
- Prefer32Bit
- PreferredUILang
- ProvideCommandLineArgs
- ReportAnalyzer
- RuntimeMetadataVersion
- SharedCompilationId
- SkipCompilerExecution
- SourceLink
- SubsystemVersion
- UseSharedCompilation
- VsSessionGuid

See also <https://github.com/dotnet/docs/issues/20061> about documenting the options of csc.exe.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: caef0578-7b6a-6b5a-8cc4-268ddb2fb743
* Version Independent ID: a99db5b2-2ff5-a675-95c2-333db10231ff
* Content: [Csc Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/csc-task?view=vs-2017)
* Content Source: [docs/msbuild/csc-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/csc-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
We added all of the parameters that are documented in the C# compiler docs. Some parameters are not intended for use, and  remain undocumented.
