### ISSUE TITLE
Where is the configuration of remote branches? 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#6303]
I have to revert to the old view to be able to configure things like this.  

Its kind of silly that I cant have both the old and the new git experiences enabled at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb36e99-33ae-20a2-a12d-a3e5d056a153
* Version Independent ID: b5a43c4a-c8bb-2c8a-56b3-09b12a713e58
* Content: [The Git experience in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by prnadago** [comment]
Hi @StingyJack - all configuration of branches has been moved to the new Git experience. You can use the left pane in the Git Repository window to see and interact with the branch tree view. The top level menu Git -> Settings has all your settings, including the ability to set 'prune remote branches during fetch'. Is there something else that you're looking for? Please let us know.

**Comment by StingyJack** [comment]
@prnadago  - yes, per the title; Where can I configure remote branches in the new UI?  This is where it was before
![image](https://user-images.githubusercontent.com/15381181/105195794-f7c9de00-5b08-11eb-854b-2408c9399f48.png)

... and is what I'm looking for in the new git tool window (aka "experience")

There aren't any menus available in the new window, just the DDL, linkbuttons, etc.

**Comment by prnadago** [comment]
Thanks for sharing the image, that clarifies what you're looking for. You can manage your remotes from **Tools -> Options**. 
![image](https://user-images.githubusercontent.com/30607258/105261183-05e92000-5b44-11eb-9bdf-bb46fb7144d2.png)

It's easy to access from the Git menu by clicking on **Manage remotes**.
![image](https://user-images.githubusercontent.com/30607258/105261191-0aadd400-5b44-11eb-8b4b-5632121f4d0e.png)

Hope this helps!

**Comment by StingyJack** [comment]
It does, and thank you. 

I'm probably still going to leave the old experience enabled though. I want to go to one place for dealing with Git, not a tool window _and_ a main menu (on opposite sides of the UI, with duplicated functionality - mostly =/   have the last 30 years of UI design lessons been forgotten in Redmond?) I also dont want to increase amount of times "git" is displayed within VS when I can help it. If you didn't notice, the new "experience" has  Git taking over all four corners of the VS UI.

TL = Git Menu
BL = toast for checkout/pull/push notifications (why on the left and not on the right like every other toast)
TR = Git Changes
BR = Branch and other selectors 

For someone who has used VS a long time and who does not like Git, the amount of real estate it is afforded is a real turn off .  I dont expect a response to the editorial, but if you could tag or flag it as product feedback that would be appreciated.
