### ISSUE TITLE
Incorrect Code in the Timer

### ISSUE THREAD

**Issue by Smith-Rick** [MicrosoftDocs/visualstudio-docs#6314]
There is a section of code in the example that should read either  "timeLeft = timeLeft - 1;" or it should read "timeLeft = --timeLeft;"

The incorrect code is written in the tutorial as "timeLeft = timeLeft - 1;"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f87fb21b-1d37-f2a8-0d32-5fa2ff83a563
* Version Independent ID: 6a34cee6-9920-b9c5-8e33-79d026931fa2
* Content: [Step 4: Add the CheckTheAnswer() method - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-4-add-the-checktheanswer-parens-method?view=vs-2019)
* Content Source: [docs/ide/step-4-add-the-checktheanswer-parens-method.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/step-4-add-the-checktheanswer-parens-method.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@Smith-Rick -- Rick, thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@ornellaalt -- Ornella, please review [private PR 7755](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7755).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
