### ISSUE TITLE
Unused variable/line of code

### ISSUE THREAD

**Issue by savitaverma** [MicrosoftDocs/visualstudio-docs#6317]
[Enter feedback here]
The Python Code Snippet in Step 1 has an unused variable/line of code. It declares a variable "rad" and assign it radians(x), but rad is not used anywhere.
In Code Snippet, Line 5: rad = radians(x) 

Either remove Line 5
Or
use "rad" in Line 6 as 
numspaces = int(20 * cos(rad) + 20)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f46b5339-857e-3398-c654-97bd9757ea44
* Version Independent ID: ed197ab6-8b08-2d23-d8b5-5a85eedda590
* Content: [Python in Visual Studio tutorial step 4, debugging](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-04-debugging?view=vs-2019)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-04-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/tutorial-working-with-python-in-visual-studio-step-04-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @savitaverma - Thanks for pointing out the unused local variable. I've updated the code sample and the change should be reflected in the documentation in an update soon.
