### ISSUE TITLE
Explain relationship with git for Windows

### ISSUE THREAD

**Issue by davisnw** [MicrosoftDocs/visualstudio-docs#6318]
Previously, I've always installed git for Windows (https://git-scm.com/download/win) to enable git in a command line - and I fact previous Microsoft documentation recommended installing it. However, this page mentions command line equivalents without mentioning anything about getting git configured on the command line.

Perhaps related to #6221 although that seems to be implying a command line launched from Visual Studio itself, while I'm concerned about generic system command lines and having consistent behavior and avoiding conflicts. 

Please keep in mind that many of us maintain projects across multiple technology stacks that all use git for version control. So visual studio having its own git support is fine but it should not interfere with and should be consistent with the generic git installation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb36e99-33ae-20a2-a12d-a3e5d056a153
* Version Independent ID: b5a43c4a-c8bb-2c8a-56b3-09b12a713e58
* Content: [The Git experience in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@davisnw Visual Studio does not require that you install Git for Windows separately, but if you want to use the command line, then you'd want to do so. We mention the command-line examples in the topic because we want people to see how the UI relates to the equivalent command-line function. We'll close this now, with our thanks for your feedback.

FYI @Taysser-Gherfal @prnadago
