### ISSUE TITLE
Rename in the light bulb icon menu is very counter productive.

### ISSUE THREAD

**Issue by jvanlangen** [MicrosoftDocs/visualstudio-docs#6319]
Hi there.

The most worse  light bulb icon menu action is the Rename action. It's even worse... it's the default action!    #fail
It's probably invented by someone who doesn't use the product.

It would be great if there was an option to remove it from the menu. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d231e9f6-7c0c-7073-6727-81a08019e589
* Version Independent ID: d0078914-0fc3-e988-ce0e-559c09f0b4c8
* Content: [Refactor rename - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/rename?view=vs-2019)
* Content Source: [docs/ide/reference/rename.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/rename.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@jvanlangen -- Jeroen, thank you for your feedback.  Please add your concern here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
