### ISSUE TITLE
git stash

### ISSUE THREAD

**Issue by extensibleseth** [MicrosoftDocs/visualstudio-docs#6326]
Please include instructions on stashing files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fb36e99-33ae-20a2-a12d-a3e5d056a153
* Version Independent ID: b5a43c4a-c8bb-2c8a-56b3-09b12a713e58
* Content: [The Git experience in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/git-with-visual-studio?view=vs-2019)
* Content Source: [docs/ide/git-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/git-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@extensibleseth Thanks for your feedback; we'll look into this and report back.
@Taysser-Gherfal @prnadago FYI on this request.

**Comment by TerryGLee** [comment]
@extensibleseth As I remarked in a previous GitHub Issue you posted, we're still in the process of adding new content, but we've recently published a page that includes info about the Stash process that might answer your inquiry. It's also in the "Git Changes" section of the new [Side-by-side comparison of Git and Team Explorer](https://docs.microsoft.com/en-us/visualstudio/ide/git-team-explorer-feature-comparison?view=vs-2019#git-changes) page, along with the Commit info that you inquired about under separate cover. 

We'll close this issue now, but please stay tuned; we'll have even more content on the new Git experience published in the next few months. And, thanks for reaching out!

**Comment by extensibleseth** [comment]
Thanks again @TerryGLee. That side-by-side page answers this ticket just fine. I'll stay tuned for further updates!
