### ISSUE TITLE
F1 default page feedback

### ISSUE THREAD

**Issue by TheBoardMan** [MicrosoftDocs/visualstudio-docs#633]
In a database project, I added a post deployment script and wanted to get help about the build action in the properties of the script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a28ee58-bd99-e74a-0c0c-30f5a41da08e
* Version Independent ID: 2467c672-a567-583c-2801-87dcaf0f2c91
* [Content](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.Ambient)%26rd%3Dtrue)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/not-in-toc/default.md)
* Service: unspecified

**Comment by gewarren** [comment]
@TheBoardMan thank you so much for letting us know. So your cursor was in the Properties window for the script?
