### ISSUE TITLE
Missing options in search dialog

### ISSUE THREAD

**Issue by ygoe** [MicrosoftDocs/visualstudio-docs#6334]
My search dialog has these options:

* Suchen in (search in: document, project, solution etc.)
    * Externe Elemente einschließen (include external elements)
    * Sonstige Dateien einschließen (include other/misc. elements)
* Dateitypen (file types)

The two options in the middle of my list are not explained. What are they good for? Why was the first unchecked and the second prechecked?

I have the latest stable version of VS 2019 16.8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e27881f-04bc-b7ba-e217-8360278a14f8
* Version Independent ID: d31c8050-339a-688c-869e-ff7942fd3f74
* Content: [Find in Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.findreplace.findinfiles)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/find-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/find-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ygoe Thanks for your feedback. We are working on updating our documentation and should have it published very soon. Meanwhile, please see the [Modernizing Find in Files](https://devblogs.microsoft.com/visualstudio/modernizing-find-in-files/) blog post for more information about the Find in Files feature changes.

**Comment by ygoe** [comment]
Thanks for the info. And, oh well, those are bad descriptions in the UI.

> When searching a solution, there are checkboxes to include miscellaneous files (files that you’ve opened but aren’t part of the solution) as well as external items (files like “windows.h” that you might reference but aren’t part of the solution).

Let me suggest the following alternatives that might avoid the user's way to the documentation altogether:

* Include opened documents not part of the solution
* Include referenced files not part of the solution

Because who knows what somebody was thinking of when writing "miscellaneous" and "external". It could be anything, really.

**Comment by TerryGLee** [comment]
@ygoe Thanks for your inquiry, and apologies for our delayed response. We've updated the page to include descriptions of the UI (user interface) and how each option might be useful to folks. 

As to your ideas about how we could optimize the actual in-product UI, please consider using our [**Suggest a Feature**](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2019) option, where product issues and suggestions are triaged and acted upon. 

Meanwhile, we'll close this issue, with our thanks to you for helping us improve the documentation.

**Comment by ygoe** [comment]
Done: https://developercommunity.visualstudio.com/t/Change-search-dialog-texts-to-make-them/1491709
