### ISSUE TITLE
This cheat sheet isn't a sheet and it isn't downloadable

### ISSUE THREAD

**Issue by martingbrown** [MicrosoftDocs/visualstudio-docs#6337]
I came to this page from here https://visualstudio.microsoft.com/vs/features/net-productivity/ by clicking on the "Download cheat sheet link". I was expecting to download a PDF that could be printed to give me a summary of Visual Studio 2019's keyboard shortcuts. Something like this one for VS Code https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf. But alas all I ended up with was a web page that is way too long to fit on a single sheet and isn't a neat quick reference.

![image](https://user-images.githubusercontent.com/5264795/106167558-39036300-6185-11eb-9a2e-b4642f41e8f5.png)
 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1815d49f-fef6-46ef-8443-7a6db8e970c1
* Version Independent ID: 3a8e4fea-8492-8ccd-08cd-a4ca74b35cd4
* Content: [Increase your productivity for .NET development - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/csharp-developer-productivity?view=vs-2019)
* Content Source: [docs/ide/csharp-developer-productivity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/csharp-developer-productivity.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@martingbrown -- Martin, thanks for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
