### ISSUE TITLE
Can't access Zip file.

### ISSUE THREAD

**Issue by danielksmith** [MicrosoftDocs/visualstudio-docs#6339]
On this page: https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application there is a link to a zip file. The URL points to localhost/assets/app.zip. Is it possible to change the URL please? I can't get the zip file and therefore can't work alongside the tutorial. This is a shame as the tutorial is really nicely written and easy to follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@danielksmith -- Daniel, thank you for your feedback. This issue is being tracked in #5827.

cc @ghogen for awareness

**Comment by ghogen** [comment]
@danielksmith The localhost zip file should be created when you install Docker for Windows. Let us know if that's not the case in your installation.
