### ISSUE TITLE
search always returns 7,480 items

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/visualstudio-docs#6343]
No matter what I search for, it returns 7,480 items
how can you find anything?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7254052d-2d37-509e-e6c8-d5674ea775ca
* Version Independent ID: a2acc423-07d3-409c-7de1-21dd88e3cdcd
* Content: [Report a problem: States and FAQ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2019)
* Content Source: [docs/ide/report-a-problem.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/report-a-problem.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by madskristensen** [comment]
We're in the process of replacing the backend of Developer Community which will bring in a new search that is a lot more accurate. The current search is unfortunately pretty bad, as you experienced. It will take some months before the new search is taking over the current one.

**Comment by WilliamAntonRohm** [comment]
@Ofer-Gal -- Ofer, thank you for your feedback.

@madskristensen -- Mads, thank you for your clarification.

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by Ofer-Gal** [comment]
Thank you all
