### ISSUE TITLE
How to enabled C++ Edit and Continue?

### ISSUE THREAD

**Issue by zartcosgrove** [MicrosoftDocs/visualstudio-docs#635]
There is a section about enabling edit and continue that doesn't tell you how to enable edit and continue. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6df6320-ceff-75ff-64fb-69cf079d122f
* Version Independent ID: fb274ee3-13ef-ecda-9893-2411eb94f222
* [Content](https://docs.microsoft.com/en-us/visualstudio/debugger/debugging-mixed-mode-applications)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/debugging-mixed-mode-applications.md)
* Service: unspecified

**Comment by Mikejo5000** [comment]
@zartcosgrove This doc is more about mixed mode debugging, but it looks like a link to that doc is needed.

**Comment by Mikejo5000** [comment]
Working on this.

**Comment by Mikejo5000** [comment]
Fixed on master branch. This should go live tomorrow.
