### ISSUE TITLE
No mention of "Sdk" as an attribute of Project element in the table

### ISSUE THREAD

**Issue by explorest** [MicrosoftDocs/visualstudio-docs#6352]
The Sdk is mentioned as an element in the table  which is fine.  But there is no mention of "Sdk" in Attributes column for Project Element. 

Since the  "Sdk" attribute is the key and default way for mentioning sdks in modern project files, I was expecting it to be mentioned there. 
It should either be mentioned in the Attributes column 
--OR--  
a little note (somewhere on the page) should tell us the reason WHY its not there!

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73afcd0b-3717-082a-e429-428bfac1c826
* Version Independent ID: 7f6f3bd1-c584-6a63-513d-a541db4e585c
* Content: [MSBuild Project File Schema Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-project-file-schema-reference?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-project-file-schema-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-project-file-schema-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@explorest Thanks - it should be added.
