### ISSUE TITLE
Incorrect folder structure

### ISSUE THREAD

**Issue by prasanve** [MicrosoftDocs/visualstudio-docs#6358]
https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2019#metricsexe

Point. No 4. says navigate to folder src/Tools
but the next line says Execute the following command to build the Metrics.csproj project: 
where Metrics.csproj is not found. the point no. 4 should say src/Tools/Metrics
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c654586-8571-cfe1-1ee1-3adaf79e2dcf
* Version Independent ID: 334b3914-dbcd-3ece-26b3-fab7c766a377
* Content: [Generate code metrics from the IDE or command line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-generate-code-metrics-data?view=vs-2019)
* Content Source: [docs/code-quality/how-to-generate-code-metrics-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/how-to-generate-code-metrics-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review [private PR 7808](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7808) containing this change.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
