### ISSUE TITLE
Docker tutorial - Part 1: URL to sample app is broken

### ISSUE THREAD

**Issue by DannyAllegrezza** [MicrosoftDocs/visualstudio-docs#6360]
Hello,

Just wanted to highlight that the URL to download the sample app (expected: `app.zip`) is currently set to `localhost/assets/app.zip` which is incorrect. This is located under step 2 of the "Get the app" section (https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md#get-the-app) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@DannyAllegrezza -- Danny, thank you for your feedback. This issue is being tracked in #5827.

cc @ghogen for awareness
