### ISSUE TITLE
zipped application link is broken

### ISSUE THREAD

**Issue by elraikhm** [MicrosoftDocs/visualstudio-docs#6361]
[Enter feedback here]
Not able to download the application zip file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cddd74b1-e0f1-1cae-e92d-c7c2b81e77e3
* Version Independent ID: f853e977-81c2-64d6-682e-1e712344cbad
* Content: [Docker tutorial - Get started with Docker](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/docker-tutorial)
* Content Source: [docker/tutorials/docker-tutorial.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/docker-tutorial.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@elraikhm -- Elena, thank you for your feedback. This issue is being tracked in #5827.

cc @nebuk89 @ghogen for awareness
