### ISSUE TITLE
Are these benefits available to Azure Devops Server (Onpremise)?

### ISSUE THREAD

**Issue by maulik-modi** [MicrosoftDocs/visualstudio-docs#6368]
In case we have Visual Studio professional licenses, Are we entitled to Azure Boards & Repos (Basic Plan) on premise? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@maulik-modi -- thank you for your question.

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@maulik-modi -- I apologize for the delay in the response here.  Yes -- you can use Boards and Repos on premise.  Your Visual Studio subscription comes with a CAL for on-prem.   You can get all the details around licensing here:  http://aka.ms/vslicensing.

**Comment by evanwindom** [comment]
#please-close

**Comment by maulik-modi** [comment]
@WilliamAntonRohm and @evanwindom , May I know the reason for taking 1month+ in response - ?  Is Azure DevOps Server being retired or consolidation of team members to Github - this is very important as we are planning to make a transition from SVN? 

 What about Azure Artifacts, Is it available under Basic license? If we are an organisation with 120 visual studio professional license users, limit of 2 GB per organisation for Azure artifacts is too low. Please provide the rationale if it is Hard limit (2GB per organisation) irrespective of size or organisation.
https://marketplace.visualstudio.com/items?itemName=ms.feed
