### ISSUE TITLE
Useless GIT Management On VS for MAC

### ISSUE THREAD

**Issue by tanser** [MicrosoftDocs/visualstudio-docs#6377]
Please add com 3part extension for git management. 

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1ebf72-a4ef-3b5f-99d5-95a0a83973d9
* Version Independent ID: b839d4b7-e42d-758c-2762-8fc7a93551e9
* Content: [Working with Git - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/working-with-git?view=vsmac-2019)
* Content Source: [mac/working-with-git.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/working-with-git.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
@tanser -- Tanser, thank you for your feedback.  This repo is solely for documentation issues, and this is a product issue.  Please add your concern here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

Please also consider these options:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.
