### ISSUE TITLE
Wrong markings in the documentation

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#6381]
---
**Issue moved from MicrosoftDocs/feedback#3431**
- Please respond to @pengyouak.

---

_From @pengyouak on Friday, January 29, 2021 3:33:07 AM_

**Describe**
page: https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/shared-colors-for-visual-studio?view=vs-2019

path:  **“Common shared controls”** - **“Drop-downs and combo boxes”**

Wrongly marked `ComboBoxGlyph` as `ComboBoxGlyphBackground`

**Screenshots**
![image](https://user-images.githubusercontent.com/4636155/106228147-ba123700-6225-11eb-8dab-60d814302c81.png)

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3431**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Friday, January 29, 2021 3:33:08 AM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3431**
- Please respond to @JasonWHowell.

---

_From @JasonWHowell on Friday, January 29, 2021 11:20:31 PM_

@acangialosi please take a look at this image which has an issue.
#assign:acangialosi

**Comment by PRMerger18** [comment]
acangialosi is already assigned.
