### ISSUE TITLE
How do I allow a semicolon in the File header? (possible bug)

### ISSUE THREAD

**Issue by 304NotModified** [MicrosoftDocs/visualstudio-docs#6386]
With this:

.editorconfig:
```
; Top-most EditorConfig file
root = true
[*.cs]
file_header_template = a;b;c
```

Add -> Class, will generate:

```c#
// a

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NLog
{
    class Class1
    {
    }
}
```

I expected `// a;b;c` and not `// a`

It this a bug as [the specs](https://editorconfig-specification.readthedocs.io/#file-format) say it should not be interpreted as comment. 

> Comment: starts with a ; or a #.
> 
> Inserting a # or ; after non-whitespace characters in a line (i.e., inline) shall neither be parsed as a comment nor as part of the section name, pair (defined below) key or value in which it was inserted. This may change in the future; thus, is not recommended.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25effdb0-73bc-c23f-9f68-94678b42cd78
* Version Independent ID: 3a31cc05-2a3c-5d5f-8dc6-357f56002261
* Content: [Add file header - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/add-file-header?view=vs-2019)
* Content Source: [docs/ide/reference/add-file-header.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/add-file-header.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@304NotModified -- Julian, thank you for your detailed feedback and editor PR.

@mikadumont -- Mika, please look into this issue and PR.

**Comment by mikadumont** [comment]
> @mikadumont -- Mika, please look into this issue and PR.

This seems to be a PR to the feature itself. Do you know how I can move this to https://github.com/dotnet/roslyn/issues ?

**Comment by WilliamAntonRohm** [comment]
@mikadumont -- thank you for your followup.  I am investigating how to move it.

**Comment by 304NotModified** [comment]
polite bump @WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@304NotModified -- Julian, thank you for the reminder.  I have copied this issue's contents to the Roslyn repo -- is the new issue's link visible for you above this comment?  The link won't show unless you are a member.  


cc @mikadumont for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
We hope to hear from you again.

**Comment by 304NotModified** [comment]
Yes it's visible. The layout is a bit broken. Maybe it was better if I copied the issue myself?

**Comment by WilliamAntonRohm** [comment]
My oversight -- I copied the display text, not the source text; fixed now.

**Comment by 304NotModified** [comment]
Thanks!

**Comment by 304NotModified** [comment]
last news in https://github.com/dotnet/roslyn/issues/44596
