### ISSUE TITLE
There is no context menu item to "Add > New Item > C++ Unit Test."

### ISSUE THREAD

**Issue by wai-t** [MicrosoftDocs/visualstudio-docs#6390]
In the section, [To add unit tests in the same project](https://docs.microsoft.com/en-us/visualstudio/test/how-to-write-unit-tests-for-cpp-dlls?view=vs-2019#sameProject), it instructs the user to choose "Add > New Item > C++ Unit Test". However, this option does not exist in the context menu for the selected project.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 219fd3d1-1a91-3c9a-76f1-a9d3f5298212
* Version Independent ID: 34795fc8-706d-1256-72a2-e4381504d887
* Content: [Write Unit tests for C++ DLLs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-write-unit-tests-for-cpp-dlls?view=vs-2019#sameProject)
* Content Source: [docs/test/how-to-write-unit-tests-for-cpp-dlls.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/how-to-write-unit-tests-for-cpp-dlls.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@wai-t 

Thanks for the report. That's not the only issue in this procedure, so I've updated the text and the fix should appear sometime tomorrow. It will read something like this:

### To add unit tests in the same project

1. Modify the product code project properties to include the headers and library files that are required for unit testing.

   1. In **Solution Explorer**, in the shortcut menu of the project under test, choose **Properties**. The project **Properties** window opens.

   1. Choose **Configuration Properties** > **VC++ Directories**.

   1. Edit the Include and Library directories:

       |Directory|Property|
       |-|-|
       |**Include Directories** | **$(VCInstallDir)Auxiliary\VS\UnitTest\include** |
       |**Library Directories** | **$(VCInstallDir)Auxiliary\VS\UnitTest\lib** |

1. Add a C++ Unit Test file:

   1. Right-click on the project node in **Solution Explorer** and choose **Add** > **New Item**.

   1. In the **Add New Item** dialog, select  **C++ File (.cpp)**, give it an appropriate name, and then choose **Add**.

   Go to [Write the unit tests](https://docs.microsoft.com/visualstudio/test/how-to-write-unit-tests-for-cpp-dlls?view=vs-2019#addTests).
