### ISSUE TITLE
State Error	CS0103	The name 'lblHelloWorld' does not exist in the current context

### ISSUE THREAD

**Issue by jamesailgatta** [MicrosoftDocs/visualstudio-docs#6398]
[Enter feedback here]

I opened Visual Studio 2019 and a Windows Forms App
Entered the EXACT line from copy & Paste

This is my Code

using System;
using System.Windows.Forms;

namespace HelloWorld
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            lblHelloWorld.Text = "Hello World!";
        }
    }
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95ecd145-51ba-c1ea-312d-69c3c8a6221f
* Version Independent ID: 69b3580e-7066-6df2-decc-afe2e5f8cfc3
* Content: [Create a Windows Forms app with C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-csharp-winform-visual-studio?toc=%2Fvisualstudio%2Fget-started%2Fcsharp%2Ftoc.json&bc=%2Fvisualstudio%2Fget-started%2Fcsharp%2Fbreadcrumb%2Ftoc.json&view=vs-2019)
* Content Source: [docs/ide/create-csharp-winform-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-csharp-winform-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@jamesailgatta -- thank you for your feedback.  I am looking into this article.

**Comment by WilliamAntonRohm** [comment]
@jamesailgatta -- please try the steps in the [Add a label to the form
](https://docs.microsoft.com/en-us/visualstudio/ide/create-csharp-winform-visual-studio#add-a-label-to-the-form) section, and let me know if that resolves your issue.
