### ISSUE TITLE
Show Contents of Installed Packages

### ISSUE THREAD

**Issue by dennislwarner** [MicrosoftDocs/visualstudio-docs#640]
There should be a way to access a listing of all functions within a selected package, and a description of each function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82bd11a6-536c-df58-14ae-b0d8daa62432
* Version Independent ID: 7837b036-cbd0-3fbe-bd65-2e7b7c0e1963
* [Content](https://docs.microsoft.com/en-us/visualstudio/rtvs/r-package-manager-in-visual-studio)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/rtvs/r-package-manager-in-visual-studio.md)
* Service: unspecified

**Comment by kraigb** [comment]
@dennislwarner Thanks for the suggestion. I've moved this to https://github.com/Microsoft/RTVS/issues/4295 because it's a product feature request rather than a documentation issue.
