### ISSUE TITLE
Error in first example description

### ISSUE THREAD

**Issue by khamyl** [MicrosoftDocs/visualstudio-docs#6406]
https://docs.microsoft.com/en-us/visualstudio/msbuild/delete-task?view=vs-2019

The first example description states:
>The following example deletes the file **_MyApp.pdb_** when you build the DeleteDebugSymbolFile target.

The correct value of the deleted file name should be **_ConsoleApp1_**. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22b02536-b99d-e0f5-165c-40c041b2178d
* Version Independent ID: 721b076f-0bab-642a-3754-fa7a2ad8f474
* Content: [Delete Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/delete-task?view=vs-2019)
* Content Source: [docs/msbuild/delete-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/delete-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review [private PR 7837](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7837).
