### ISSUE TITLE
Why are tutorials for Azure App Service listed under Visual Studio product?

### ISSUE THREAD

**Issue by NoNameProvided** [MicrosoftDocs/visualstudio-docs#6407]
I wanted to provide feedback for Azure App Service extensions, however when clicking the `This Product` button in the feedback section it takes me to the Visual Studio feedback portal instead of a feedback portal for Azure App Service.

This is because this articles is on the Visual Studio docs portal but it's about Azure App Service. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed41e92f-bae3-d625-83a4-90aba38de53e
* Version Independent ID: afb985d5-3e2b-69a8-6770-8dea58d9f2b7
* Content: [Configure Python on Azure App Service (Windows) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-on-azure-app-service?view=vs-2019)
* Content Source: [docs/python/managing-python-on-azure-app-service.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/managing-python-on-azure-app-service.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@NoNameProvided -- Attila, thank you writing us.  What is the feedback that you wanted to attach?

@JoshuaPartlow -- Joshua, please look into this issue.

**Comment by NoNameProvided** [comment]
My feedback is about how run a mixed NodeJS, Python app inside app service? One can do this via deploying a NodeJS app service and by adding the Python 3.6.4 x64 extension, but that version is close to EOL and the whole Python as extension thing is deprecated in Azure. So if I understand things correctly, there is no way to run both NodeJS and Python in the same app service instance currently.

**Comment by j-martens** [comment]
This is not a doc bug. @NoNameProvided you can find this link here: https://docs.microsoft.com/en-us/azure/app-service/overview
