### ISSUE TITLE
Where is visualstudio-16.8.6 which I installed yesterday listed?

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#6408]
I cannot find the entry for visualstudio-16.8.6 which I installed on 2021-02-22.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by maxwellb** [comment]
If this issue is not quick to resolve, are you able to share the release notes in this issue for anyone considering the update?

**Comment by ornellaalt** [comment]
We are actively working on a fix. In the meantime, if you need the build version for this release, here is the table entry:
`| 16.8.6 | Release | February 22, 2021 | 16.8.31019.35 |`

**Comment by ornellaalt** [comment]
@maxwellb Thank you for your comment. This page does not contain the release notes for the updates. To see the latest release notes, please visit https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

**Comment by maxwellb** [comment]
Thank you @ornellaalt . For myself, my question was related to the summary of changes. It sounds like that is around the corner, so nevermind on the suggestion.

**Comment by binki** [comment]
@ornellaalt the page you link is also missing the release notes for this version ;-).

**Comment by ornellaalt** [comment]
@binki gotcha, would you mind submitting feedback on that page directly through one of the links [here](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#feedback-and-suggestions)? I'll also escalate this to the appropriate team. Unfortunately, this page only hosts a list of releases with dates and the build versions, so I can't advise on the release notes.

**Comment by maxwellb** [comment]
@binki For your benefit, I discovered today the list of community changes included in the release on [developercommunity2.visualstudio.com](https://developercommunity2.visualstudio.com/search?q=%5bFixed+In%3a+Visual+Studio+2019+version+16.8.6%5d). Sounds like a major Azure Functions publishing bug was fixed, as well as a significant GitHub integration issue.

**Comment by maxwellb** [comment]
A note: I also came here looking for the release notes. I think what is unclear is that the release notes page does not live in the GitHub repo, hence why the issue could not be linked to that page, and is referring to the versions table page. We have gotten the message across most of MicrosoftDocs, that the source of content on docs.microsoft.com lives in GitHub now. I will join others in opening an issue via feedback as well, thank you @ornellaalt.

**Comment by maxwellb** [comment]
Updating once again (sorry!) that I appear not to be able to submit feedback through the instructions provided.

![image](https://user-images.githubusercontent.com/3590441/108908886-da010480-75f1-11eb-9ac1-fdc2ad6f97a0.png)

I am using the Build Tools (no IDE) and get this error when attempting to sign in to the feedback portal from the Installer.

**Comment by maxwellb** [comment]
For anyone else arriving here, this is an issue in the Feedback portal, per instructions from @ornellaalt :

https://developercommunity.visualstudio.com/t/No-Release-Notes-for-version-1686/1346863?entry=problem&space=8&sort=newest

**Comment by ghogen** [comment]
All publishing to docs.microsoft.com was blocked starting on 2/18/21. The underlying issue was diagnosed and addressed. Some publishing has resumed, but normal publishing hasn't yet resumed. I expect Visual Studio docs and the release notes will be published as soon as the build system allows it.

**Comment by Andreas-Schniertshauer** [comment]
> We are actively working on a fix. In the meantime, if you need the build version for this release, here is the table entry:
> `| 16.8.6 | Release | February 22, 2021 | 16.8.31019.35 |`

I also need the correct download link for the Professional version as on the page https://docs.microsoft.com/en-us/visualstudio/releases/2019/history published, because I need to build an installer layout with it.
Thanks.

**Comment by ghogen** [comment]
The release notes have been published
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

@Andreas-Schniertshauer you can find the download links for the 16.8.6 version of each SKU at the link you gave - it has been updated as of now.

The build numbers aren't yet updated in this article - but you can get them from Ornella's comment in this thread.

**Comment by Andreas-Schniertshauer** [comment]
The link https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.8.0.pre.5.0 on https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview is wrong should be 16.9.0.pre.5.0

**Comment by ghogen** [comment]
@Andreas-Schniertshauer Thanks for reporting that. We'll get it fixed, but the build issues are still a problem, so it may take a little while for it to be updated.

**Comment by Andreas-Schniertshauer** [comment]
For me it wasn't a problem, I edited the link manually and was able to download the preview. Thanks for the help, I could do the layout for both compilers.
