### ISSUE TITLE
Is Run and Create IntelliTest invokable outside of right clicking the ActiveDocument?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#641]
Manually opening each file and right clicking it to run or create is slow. 

I want to generate unit tests for an existing Solution (about 6K files). If I can script most or all of that, it would be great (and I dont mean a script that hooks into the DTE and uses SendKeys or something).  

Is this possible?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b8edaf-7667-a3e6-38dc-371c53bcd386
* Version Independent ID: 580e757e-8ce7-1437-3843-c88ff4f3ab54
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/generate-unit-tests-for-your-code-with-intellitest#QandALink)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/generate-unit-tests-for-your-code-with-intellitest.md)
* Service: unspecified

**Comment by gewarren** [comment]
@kendrahavens can you comment on this?

**Comment by gewarren** [comment]
@prlakshm can you help this customer out?

**Comment by pvlakshm** [comment]
The only way to invoke IntelliTest is via the context menu commands in the Visual Studio IDE.
It can be invoked at the level of a method, or a class, or a namespace. Accordingly it will explore and generate tests for the method, all public methods on the class, all public methods on public classes within the namespace.
Scripting it is not supported.

**Comment by StingyJack** [comment]
Will the namespace scope include namespaces beneath the selected one in the hierarchy?  

Is scripting or some other extensibility point in the future plans?
