### ISSUE TITLE
Clarification required for Azure Devops use rights with MPN benefit VS licenses

### ISSUE THREAD

**Issue by jikuja** [MicrosoftDocs/visualstudio-docs#6410]
Documentation lists Visual Studio Enterprise(Microsoft Partner Network) as eligible for `Azure Boards & Repos (Basic2), Azure Test Plans, self-hosted parallel jobs.`

Are Azure Devops benefits available for all use cases or only for internal work like described here https://docs.microsoft.com/en-us/visualstudio/subscriptions/program-mpn ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@jikuja -   Thanks for your question.  The Azure DevOps benefits are licensed for dev/test only.  They are not licensed for production use.  Any limitations of the MPN program would also apply.

**Comment by evanwindom** [comment]
#Please-close
