### ISSUE TITLE
Incorrect instruction

### ISSUE THREAD

**Issue by ghhv** [MicrosoftDocs/visualstudio-docs#6411]
[Enter feedback here]
This is slightly incorrect - it should say _press CTRL-ALT_ while you click.
"To select multiple carets, click or make first text selection as usual, and then _press Alt_ while you click or select text in each additional location. "

Also, might clarify to enclose 'Go to Definition' in quotes and specify Tools > Options > Text Editor > General. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b328a871-7747-31d6-737c-4e3f6d10d9d1
* Version Independent ID: 2b455842-a4ef-25bd-c386-f36e0d14ce3d
* Content: [Find and replace text, and multi-caret selection - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019#multi-caret-selection)
* Content Source: [docs/ide/finding-and-replacing-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-replacing-text.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ghhv Thanks for your feedback; we'll take a look at this (the page is already in the queue to be updated soon, so we'll add this to the list.)

**Comment by TerryGLee** [comment]
@ghhv Apologies for the delay, but we've updated the "Multi-carat selection" section both the Visual Studio 2019 and Visual Studio 2017 version of the **Find and Replace text** page, per your feedback:

- Visual Studio 2019 - [Find and replace text](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019#multi-caret-selection)
- Visual Studio 2019 - [Find and replace text](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2017#multi-caret-selection)

We're still working on adding keyboard shortcut info, etc., to the Visual Studio 2022 version of the page, which should be published soon. 

But meanwhile, having added your suggested text updates, we'll close this issue now with our thanks to you for helping improve the documentation!
