### ISSUE TITLE
Link to SonarLint navigating to Sonar lint link for Visual studio 2017 not to Sonar lint link for Visual studio 2019

### ISSUE THREAD

**Issue by nabodhe** [MicrosoftDocs/visualstudio-docs#6412]
Link to SonarLint navigating to Visual studio 2017 not Visual studio 2019

Below Link shows details for Visual studio 2019
https://docs.microsoft.com/en-us/visualstudio/ide/csharp-developer-productivity?view=vs-2019

However when I click SonarLink link, it navigates to SONAR lint for VS 2017.
Not sure if this is bug or intentional ?

<img width="196" alt="VS_SonarLint_Issue" src="https://user-images.githubusercontent.com/14955244/108959404-5c450380-769a-11eb-8462-1597ad659f47.PNG">

Regards,
Nilesh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1815d49f-fef6-46ef-8443-7a6db8e970c1
* Version Independent ID: 3a8e4fea-8492-8ccd-08cd-a4ca74b35cd4
* Content: [Increase your productivity for .NET development - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/csharp-developer-productivity?view=vs-2019)
* Content Source: [docs/ide/csharp-developer-productivity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/csharp-developer-productivity.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@nabodhe Good catch; thanks for letting us know. We'll place this in the queue to get fixed, soon. Meanwhile, the link should be this, instead, for Visual Studio 2019: 
https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2019

**Comment by TerryGLee** [comment]
@nabodhe The link fix should go live after 4:00 P.M. Pacific Standard Time today.
