### ISSUE TITLE
updates about the visual studio API for CSP Partner center

### ISSUE THREAD

**Issue by marsmichel** [MicrosoftDocs/visualstudio-docs#6417]
Any updates on the Visual studio API so we can automate the purchasing of VS in our end user self service portal?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f413cb5d-d6c4-2036-62e2-0af9b041ade3
* Version Independent ID: 7c96f714-fb4f-a578-546e-2cfba9366d76
* Content: [Visual Studio cloud subscription purchasing for CSPs](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-csp)
* Content Source: [subscriptions/vscloud-csp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-csp.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
Hi @marsmichel  -- I don't have any new information about automation of purchasing at this time.

**Comment by evanwindom** [comment]
#please-close
