### ISSUE TITLE
The sample app link doesn't download anything.

### ISSUE THREAD

**Issue by TimothyMalahy** [MicrosoftDocs/visualstudio-docs#6419]
Where it says "Download the ZIP" underneath Get the App>step 2.

The URL for that is 
http://localhost/assets/app.zip

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by TimothyMalahy** [comment]
Sorry - I now realized where I went wrong.

I would think the docs could better explain that you download docker and then run the command. For example, why can I not run docker/getting-started etc.

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please look into the above comment.
