### ISSUE TITLE
C1189: Py_LIMITED_API is incompatible with Py_DEBUG, Py_TRACE_REFS, and Py_REF_DEBUG still here

### ISSUE THREAD

**Issue by TarasDikanev** [MicrosoftDocs/visualstudio-docs#6425]
I've set Multi-threaded DLL (/MD) for all configurations but "C1189: Py_LIMITED_API is incompatible with Py_DEBUG, Py_TRACE_REFS, and Py_REF_DEBUG" error still happened until I removed _DEBUG preprocessor definition under debug configuration.

![image](https://user-images.githubusercontent.com/25967394/109296366-3efe6980-7841-11eb-869b-15c33d105161.png)

After that everything seems ok, mixed mode debugging works fine.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by zooba** [comment]
I'm addressing this in https://github.com/MicrosoftDocs/visualstudio-docs/pull/6632

**Comment by JoshuaPartlow** [comment]
Closing as this was addressed in recent PR to the docs.
