### ISSUE TITLE
set command is used instead of setx one in legacy code analysis setup

### ISSUE THREAD

**Issue by alvinseville7cf** [MicrosoftDocs/visualstudio-docs#6426]
[set](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/set_1) command is used instead of [setx](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx) one in [legacy code analysis setup](https://docs.microsoft.com/en-us/visualstudio/code-quality/how-to-run-legacy-code-analysis-manually-for-managed-code?view=vs-2019):
```bat
set EnableLegacyCodeAnalysis = true
```
But the right command is:
```bat
setx EnableLegacyCodeAnalysis true
```
I've checked it out - it works properly.

**Comment by WilliamAntonRohm** [comment]
@alvinseville7cf -- Alvin, thank you for your feedback and fix.
