### ISSUE TITLE
[Suggested Content:]Invoice Description Question to be answered

### ISSUE THREAD

**Issue by seanatdp** [MicrosoftDocs/visualstudio-docs#6428]
Please include what invoice details will show up on a purchase order or credit statement, such as abbreviations can be expected

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf290c37-d7fa-9d10-b8ef-865647e58a70
* Version Independent ID: 1334b162-8560-5e0a-c874-9439b697dd96
* Content: [Billing FAQ for Visual Studio Visual cloud subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-billing-faq)
* Content Source: [subscriptions/vscloud-billing-faq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vscloud-billing-faq.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@seanatdp -- Sean, thank you for your feedback.

@evanwindom -- Evan, please look into this issue.

**Comment by evanwindom** [comment]
@seanatdp - Hi, Sean.  Thanks for your question.  The best place to get answers to questions about Azure instruments like invoices or statements would be in the Azure documentation, as it is written and maintained by people with the full context.  But you raise a good point.  I'll include a link in our article to relevant content on the Azure side.  

https://docs.microsoft.com/en-us/azure/cost-management-billing/understand/understand-invoice

**Comment by evanwindom** [comment]
#please-close
