### ISSUE TITLE
Visualizer for net5.0 and netcoreapp

### ISSUE THREAD

**Issue by janovrom** [MicrosoftDocs/visualstudio-docs#6432]
Hi,

I just went through the tutorial and I've run into an issue with VisualizerDevelopmentHost. If the test method is called form .netframework console app (v4.8) then it works as expected. However, when the console app is either .netcore 3.1 or .net5.0 the call to VisualizeDevelopmentHost.ShowVisualizer() results in an exception:

System.MissingMethodException: 'Method not found: 'Void System.AppDomainSetup.set_ApplicationBase(System.String)'.'

When installed thought, it runs as expected on all platforms. This was tested with Visual Studio Community 16.9.0 Preview 3.0. 

Best regards,
Roman Janovsky 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 611c0cd6-9526-a950-c384-31987aa8aa21
* Version Independent ID: 8e7f4271-9b92-cd04-a489-b6a97d55671b
* Content: [Test and Debug a Visualizer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-test-and-debug-a-visualizer?view=vs-2019)
* Content Source: [docs/debugger/how-to-test-and-debug-a-visualizer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-test-and-debug-a-visualizer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@WardenGnaw Andrew, I could repro this issues testing a .NET Core console app against a .NET Core visualizer. Do you know how to fix the error in the test harness?

![image](https://user-images.githubusercontent.com/11948536/122450501-ea9c0880-cf5b-11eb-819c-eb668a238a08.png)

**Comment by WardenGnaw** [comment]
@mpeyrotc Will investigate. With the recent changes to how visualizers now work, the test harness also needs to be updated.

**Comment by Mikejo5000** [comment]
@mpeyrotc @WardenGnaw OK, let me know if you find a workaround and I'll update the doc.

**Comment by Mikejo5000** [comment]
@WardenGnaw I spent some time testing the custom visualizer for .NET Core by installing it rather than using the test harness. I could make the scenario work using a .NET Core console app, but the visualizer (debugger-side) had to be .NET Framework. Is that what you would expect at this point?

**Comment by mpeyrotc** [comment]
Hello @Mikejo5000 , the debugger-side visualizer is loaded in the devenv.exe process, so it can only be .NET Framework or .NET Standard (version 1.3 if I am not mistaken). The debuggee-side can be either .NET Framework or .NET Core depending on what process you wish to use it on since it gets loaded into the process being debugged by VS.

**Comment by Mikejo5000** [comment]
Updated doc after testing and discussion with owners. Currently, we recommend creating a .NET Framework visualizer (.NET Standard 1.3 is no longer supported, so did not test that). Calling app may be .NET Core. Custom data object may be .NET Standard. Doc is updated now:

https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp

**Comment by Mikejo5000** [comment]
Also, added a note to the Test doc referenced in this issue:

https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-test-and-debug-a-visualizer?view=vs-2019
