### ISSUE TITLE
Window colours?

### ISSUE THREAD

**Issue by jeremy-songtradr** [MicrosoftDocs/visualstudio-docs#6433]
Would be neat to show how to customise colours of windows, not just the Theme. For example, when Light Theme is picked, the Terminal window is practically impossible to use. Seems to be no way of selecting foreground / background colours for this window, I was hoping this article would explain how.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86994b58-45d2-1490-02e9-3d1e7b09a23e
* Version Independent ID: 08ac7422-416b-4286-27d1-741b5c98a6bd
* Content: [Customizing the IDE - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/customizing-the-ide?view=vsmac-2019)
* Content Source: [mac/customizing-the-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/customizing-the-ide.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment]
@jeremy-songtradr -- thank you for your feedback.  Please let me know if this page is helpful:
- [How to: Change fonts and colors for the editor in Visual Studio](https://docs.microsoft.com/visualstudio/ide/reference/how-to-change-fonts-and-colors-in-the-editor)

**Comment by jeremy-songtradr** [comment]
@WilliamAntonRohm thanks for the reply - but this does not cover the question.

Mac Visual Studio, as far as I can tell, has not got the same options as the link you sent me, which is for Windows Visual Studio.

[https://docs.microsoft.com/en-gb/visualstudio/ide/reference/how-to-change-fonts-and-colors-in-the-editor?view=vs-2019](url)

If you can point me in the direction of the same page in MacOS Visual Studio, that would be great, but I can't find it. The only options I can find are under Preferences -> Environment -> Visual Style to select a theme.

**Comment by WilliamAntonRohm** [comment]
@jeremy-songtradr -- thank you for your followup.  This article may be more helpful, so you can create a custom scheme:
- [Applying Languages and Themes](https://docs.microsoft.com/archive/msdn-magazine/2017/december/visual-studio-customizing-visual-studio-for-mac#applying-languages-and-themes)
