### ISSUE TITLE
This feature is absolutley STUPID.  

### ISSUE THREAD

**Issue by AriethNinja** [MicrosoftDocs/visualstudio-docs#6437]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d756ce43-92a4-e3fc-14e5-00762c715790
* Version Independent ID: 4fdef01a-d2b2-948e-8ac8-8684b00ff729
* Content: [Trust Settings for Files and Folders - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/trust-settings?view=vs-2019)
* Content Source: [docs/ide/reference/trust-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/trust-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @2percentsilk
* Microsoft Alias: **allisb**

**Comment by TimShererWithAquent** [comment]
Hi @AriethNinja - I'm guessing this is the same issue that you commented on in MicrosoftDocs/visualstudio-docs/issues/6438, so I'm going to mark it as duplicate on that one, but please contact us with additional info, if this is a different issue.
