### ISSUE TITLE
DockerLaunchAction seems to depend on log to start browser

### ISSUE THREAD

**Issue by mathysd** [MicrosoftDocs/visualstudio-docs#6441]
<DockerLaunchAction>LaunchBrowser</DockerLaunchAction> won't work if the log setting for 
Microsoft.Hosting.Lifetime is not set to information. Visual studio seems to wait for _Now listening on: http://[::]:80_ before actually launching a browser. No warning or error is written anywhere. So it took my quite some time to figure this one out. 

I added docker and docker-compose to an existing project. This project uses serilog with serilog request logging (UseSerilogRequestLogging) and all microsoft logging is set to Warning.

So maybe it's a good idea to add this to the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e8ab223-566b-c9bc-ce39-22e23531415a
* Version Independent ID: f58fe488-72a0-98aa-ff60-f1f7585ea107
* Content: [Docker Compose build settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019)
* Content Source: [docs/containers/docker-compose-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/docker-compose-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Entered in product repo. Closing here.
@mathysd Please follow the issue at the link above (#323 in microsoft/DockerTools)
