### ISSUE TITLE
Include command line interface equivalent for this command.

### ISSUE THREAD

**Issue by grcodemonkey** [MicrosoftDocs/visualstudio-docs#6451]
Can this page also include instructions on how to achieve the same result using the command line tools?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9d2be7-406b-0422-c49c-d62f972419e0
* Version Independent ID: 127bdbb0-a2ce-dd7c-99b7-1ee55d691e48
* Content: [Publish to a folder - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-folder?view=vsmac-2019)
* Content Source: [mac/publish-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-folder.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
FYI the links are now appearing in the live docs

**Comment by sayedihashimi** [comment]
#please-close
