### ISSUE TITLE
Use of graphic to show code prevents copying and ease of use

### ISSUE THREAD

**Issue by RobertGBryan** [MicrosoftDocs/visualstudio-docs#6454]
[Enter feedback here]
This is a general comment that applies to all docs.Mircorsoft.com pages that shows example code as a graphic. The problem with this approach is that users can't easily copy the sample code. This hinders ease of use. Why can't colored ascii text be used instead? This would allow the code to be copied and then imported into a text editor. At least, that is how I would do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb48054-70fa-c5eb-748e-4db24ef64fd4
* Version Independent ID: 9ca41665-2e31-87da-4ba9-a8c60150db51
* Content: [Generate C# Equals and GetHashCode Method Overrides - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2019)
* Content Source: [docs/ide/reference/generate-equals-gethashcode-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-equals-gethashcode-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@RobertGBryan We do include code in our tutorials that you can copy. (Here's an example: [Tutorial: Create a simple C# console app in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019)). But for general content that's typically not a complete code sample, i.e. instead, it's a short snippet of code that's meant to highlight what a specific feature of the Visual Studio IDE can do, we typically won't include include it as something you can copy.  Thanks for inquiring, though!

**Comment by RobertGBryan** [comment]
Is there a procedure to reopen and escalate this issue? If so, then please do so.

Whoever came up with the policy of putting code in a graphic so that it can't be copied does not seem to care about what users expect and helping them do their jobs efficiently. Just because the displayed code is only a few lines long does not mean that copying that code is somehow not helpful and useful. This is a significant issue and if you don't see it that way, then perhaps you are not a developer that works with code everyday.

You see, I wanted to copy the code on this page, but was unable to do so because it is displayed in a graphic image. if I wanted to copy the code, then many others will want to do the same. What I ended up doing was typing the code I saw and referred back to it several times while typing it in to make sure I got it right. I probably should have used OneNote's OCR function to copy the text from the page. But, that is not a perfect solution either.

Who set this policy of putting code inside of a graphic image and what is the rationale behind it? What do you gain from it over using colored text? Graphic images consume more resources than displaying text, so it can't be about efficiency. Does it somehow take less time for contributors to put code inside of a graphic .vs. using colored text?

Bob Bryan - author of Interviewing For The .NET Stack series

**Comment by TerryGLee** [comment]
@RobertGBryan I understand where you're coming from; and, you make some excellent points. Our sincere apologies for the inconvenience that you experienced. As for the content on this page, it was created a while ago so I cannot answer some of the questions you asked. However, I will pass this feedback on to our team and going forward, we'll endeavor to add code that you can copy, snippet or otherwise, to all new Visual Studio content that we create.

**Comment by TerryGLee** [comment]
@RobertGBryan Just a quick FYI: I revised the [Generate Equals and GetHashCode method overrides](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2019) page to include code that you can copy. I also revised the screenshots so that you can see the coloring that's available in Visual Studio.

**Comment by RobertGBryan** [comment]
@TerryGLee Very nice. Thanks.
    On Tuesday, March 9, 2021, 04:35:19 PM PST, Terry G. Lee <notifications@github.com> wrote:  
 
 


@RobertGBryan Just a quick FYI: I revised the Generate Equals and GetHashCode method overrides page to include code that you can copy. I also revised the screenshots so that you can see the coloring that's available in Visual Studio.
