### ISSUE TITLE
Ambiguous Tutorial Step

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/visualstudio-docs#6458]
Under the section **Reference .NET libraries: write to a log**, step 4 refers to a while loop.  There are 3 in the code at this point so I suggest adding text to make it unambiguous to which while loop you're referring, otherwise it could cause confusion.

 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80ccbb63-7f84-55e6-1b3e-f48400aa17ae
* Version Independent ID: 6aba5d1b-f8ce-7b82-560e-c6a9926423ac
* Content: [Tutorial: Extend a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2019#add-a-nuget-package-write-to-a-json-file)
* Content Source: [docs/get-started/csharp/tutorial-console-part-2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console-part-2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@JustaSimpleUser This was fixed a while ago. Thanks for the feedback.
