### ISSUE TITLE
Add Reference Link to Trace Library

### ISSUE THREAD

**Issue by JustaSimpleUser** [MicrosoftDocs/visualstudio-docs#6459]
It might be nice to add a link to an explanation/definition of the Trace library so beginners can explore this feature without having to search the MSDocs website.  As it exists now, the short intro to Trace is out of context and not supported with opportunities for further exploration.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80ccbb63-7f84-55e6-1b3e-f48400aa17ae
* Version Independent ID: 6aba5d1b-f8ce-7b82-560e-c6a9926423ac
* Content: [Tutorial: Extend a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2019#add-a-nuget-package-write-to-a-json-file)
* Content Source: [docs/get-started/csharp/tutorial-console-part-2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console-part-2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by JustaSimpleUser** [comment]
I think this is simple enough to do and would contribute to the reader's understanding of what the Trace library could do.  A simple link at the bottom or even in the text of the section involved would contribute to greater understanding of the tutorial and growth of overall knowledge of C#'s existing capabilities.  This should take 10 mins to implement.

**Comment by ghogen** [comment]
@JustaSimpleUser 
Thanks for your patience. I agree with your suggestion and will add a link.
