### ISSUE TITLE
Downgrade Visual Studio for Mac

### ISSUE THREAD

**Issue by tsequeira-vhs** [MicrosoftDocs/visualstudio-docs#6461]
Is there anyway to downgrade Visual Studio for Mac? I want to downgrade from 8.9 to 8.8.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f3608c-d434-e892-85db-032af35f919b
* Version Independent ID: d546284e-5cd8-6a41-790b-5302b628d357
* Content: [Updating Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-gb/visualstudio/mac/update?view=vsmac-2019)
* Content Source: [mac/update.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/update.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by heiligerdankgesang** [comment]
@tsequeira-vhs thanks for your patience. Right now, there isn't a way in the product for you to downgrade to an older version. If you email me, though, I can help you downgrade.

dominicn@microsoft.com

I'll keep an eye out for your email. When you reach out, could you please let me know if there's a particular issue you're hitting in 8.9 that has caused you to want to downgrade.

Thanks!

#please-close
