### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by scegg** [MicrosoftDocs/visualstudio-docs#647]
parameter --layout is not working with the vs setup file since March 2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Service: unspecified

**Comment by gewarren** [comment]
@scegg thanks for the feedback. @TerryGLee could you forward this to the appropriate people?

**Comment by TerryGLee** [comment]
@gewarren Will do.
