### ISSUE TITLE
Missing Polls Django Web Project template

### ISSUE THREAD

**Issue by Kaltininkas** [MicrosoftDocs/visualstudio-docs#6472]
Where is the Polls Django Web Project template???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e918f82f-35af-2934-34d1-913c59cfa927
* Version Independent ID: 009bc101-2451-89b2-5bd1-5ac48a47b33a
* Content: [Learn Django tutorial in Visual Studio step 6, Polls project template](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-06-polls-django-web-project-template?view=vs-2019)
* Content Source: [docs/python/learn-django-in-visual-studio-step-06-polls-django-web-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-06-polls-django-web-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@Kaltininkas -- thank you for your question.  Please see these sections, and let me know if you are still blocked:
- [Prerequisites](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-01-project-and-solution?view=vs-2019#prerequisites)
- [Step 1-1: Create a Visual Studio project and solution](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-01-project-and-solution?view=vs-2019#step-1-1-create-a-visual-studio-project-and-solution)

**Comment by JoshuaPartlow** [comment]
@savannahostrowski - Would you be able to comment here?

**Comment by savannahostrowski** [comment]
@Kaltininkas Sorry about the confusion. This template is no longer supported. The last release that included this template was 16.7. You can install an older version (like 16.7) of Visual Studio [here](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release).
