### ISSUE TITLE
Missing Polls Flask Web Project template 

### ISSUE THREAD

**Issue by kamolui** [MicrosoftDocs/visualstudio-docs#6474]
I am using visual studio 2019, and Polls Flask Web Project template is not showing up. Where can I download the template?

I did all the steps except that one
![imagen_2021-03-11_134821](https://user-images.githubusercontent.com/61925980/110845595-7113c080-8270-11eb-849e-24c4e279653d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47801555-59fa-e88e-8f78-17e4ba4d1e03
* Version Independent ID: 3272c6ed-afe8-3fb9-8e15-dbb30d5a4d23
* Content: [Learn Flask tutorial in Visual Studio step 5, Polls project template](https://docs.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-05-polls-flask-web-project-template?view=vs-2019)
* Content Source: [docs/python/learn-flask-visual-studio-step-05-polls-flask-web-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-flask-visual-studio-step-05-polls-flask-web-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
@savannahostrowski - Would you be able to comment here?

**Comment by kamolui** [comment]
Yes i could

**Comment by savannahostrowski** [comment]
@kamolui Sorry about the confusion. This template is no longer supported. The last release that included this template was 16.7. You can install an older version (like 16.7) of Visual Studio [here](https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release).
