### ISSUE TITLE
Alternate account not working

### ISSUE THREAD

**Issue by hsmahal** [MicrosoftDocs/visualstudio-docs#6477]
I have added my alternate account via my work visual studio professional subscription, however I cannot see this subscription when logging into the azure portal with my alternate account. I have an enterprise subscription that is due to expire and need to transfer my resources to the professional subscription.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a760034-6571-5206-1476-0a0d6b2ef031
* Version Independent ID: d5ce817f-c949-e070-459d-4c7728329550
* Content: [Manage Visual Studio Subscriptions](https://docs.microsoft.com/en-gb/visualstudio/subscriptions/manage-vs-subscriptions#managing-my-profile)
* Content Source: [subscriptions/manage-vs-subscriptions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/manage-vs-subscriptions.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@hsmahal -- thank you for your feedback.

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@hsmahal  - I apologize for the delay in responding here.  The feedback channel is really not designed or equipped to handle individual support requests.  If you have question about using your alternate ID with Azure, we recommend contacting Azure support.  https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview should get you there.

**Comment by evanwindom** [comment]
#please-close
