### ISSUE TITLE
Constructor misspelling

### ISSUE THREAD

**Issue by marlonfsolis** [MicrosoftDocs/visualstudio-docs#648]
public class StockAnalyzer  
{  
    private IStockFeed stockFeed;  
    public Analyzer(IStockFeed feed)  // Should be StockAnalyzer?
    {  
        stockFeed = feed;  
    }  
    ...
} 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1834a8fa-cc25-bacf-1379-b6691051cf39
* Version Independent ID: 56f3b218-56c5-6135-0593-41e83370a813
* [Content](https://docs.microsoft.com/en-us/visualstudio/test/using-stubs-to-isolate-parts-of-your-application-from-each-other-for-unit-testing)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/using-stubs-to-isolate-parts-of-your-application-from-each-other-for-unit-testing.md)
* Service: unspecified

**Comment by gewarren** [comment]
@marlonfsolis thanks for the heads up, I will fix this. Or if you'd like to fix it, you can click the Edit button near the top right of the page.
