### ISSUE TITLE
deploy to windows iis

### ISSUE THREAD

**Issue by privateWH** [MicrosoftDocs/visualstudio-docs#6483]
I have no idea what to do after Publish to a folder. I want to bring the dlls to an live windows iis server but I am confused. as to what to do next. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c9d2be7-406b-0422-c49c-d62f972419e0
* Version Independent ID: 127bdbb0-a2ce-dd7c-99b7-1ee55d691e48
* Content: [Publish to a folder - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/publish-folder?view=vsmac-2019)
* Content Source: [mac/publish-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/publish-folder.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
@privateWH I believe the content that you are looking for is at https://docs.microsoft.com/aspnet/core/tutorials/publish-to-iis. I'm happy to add a link to that doc. If you could let me know if that helps you, I'll go ahead and get the link added.
