### ISSUE TITLE
Link to xUnit.net extension not ideal

### ISSUE THREAD

**Issue by swisscoder** [MicrosoftDocs/visualstudio-docs#6484]
The link to the xUnit.net Extension is that of an old one for VS2015 which is not shown when using the extension manager. I guess the correct one (vor VS2017 and VS2019) would be this link instead:
https://marketplace.visualstudio.com/items?itemName=YowkoTsai.xUnitnetTestGenerator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a859ec6-03a2-2d8c-bcfe-c9499db55286
* Version Independent ID: 4ac4f045-660e-e159-edeb-315cf491568c
* Content: [Create unit test method stubs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/create-unit-tests-menu?view=vs-2019#use-third-party-unit-test-frameworks)
* Content Source: [docs/test/create-unit-tests-menu.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/create-unit-tests-menu.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review this update in [private PR 7911](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7911).
