### ISSUE TITLE
Add a how to "install BuildTools with PowerShell in a container"

### ISSUE THREAD

**Issue by Robertschv** [MicrosoftDocs/visualstudio-docs#6486]
CMD is now in maintenance mode see https://www.theregister.com/2020/05/27/windows_cmd_maintenance_mode/
Using PowerShell will be the future, I want to use something in the company I am working that should not change in the next 10 years at least.

Is there any example how to install Build-Tools and using just PowerShell?
It would be awesome to see the tutorial of how to install Build Tools in a container using just powershell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by Robertschv** [comment]
I hope this can help

`# escape=`

# Use the latest Windows Server Core image with .NET Framework 4.8.
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

# Use Powershell to run this script.
SHELL ["powershell", "-command"]

# Download the Build Tools bootstrapper.
ADD https://download.visualstudio.microsoft.com/download/pr/1192d0de-5c6d-4274-b64d-c387185e4f45/c9cc192eb63bbdf2b29ce7a437a629b7ef83accf11c34a4eabb1faf2cb7f35b4/vs_BuildTools.exe  C:\TEMP\vs_buildtools.exe

# Install Build Tools.
RUN "Start-Process -Wait 'C:\TEMP\vs_buildtools.exe' -ArgumentList '--quiet --norestart --nocache --installPath C:\BuildTools --add Microsoft.VisualStudio.Workload.AzureBuildTools --includeRecommended' -PassThru"


# This entry point starts the developer PowerShell and launches the PowerShell shell.
ENTRYPOINT "$vsInstallPath = 'C:\BuildTools' ; if($?) { Import-Module C:\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll ; if($?) { Enter-VsDevShell -VsInstallPath $vsInstallPath -SkipAutomaticLocation}} ; powershell ; "`

**Comment by Robertschv** [comment]
#add#6516

**Comment by anandmeg** [comment]
@Robertschv, thank you for the suggestion. We will look into adding it for future updates and consider it based on customer feedback. 

Thanks again! Let us know if you have any other feedback for us.
