### ISSUE TITLE
DPI scaling on designers

### ISSUE THREAD

**Issue by chopsnsauce** [MicrosoftDocs/visualstudio-docs#6499]
Is there a planned feature to make designers always 100% scaling?  If so it would be great to link that to the article.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2019)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@chopsnsauce -- thank you for your feedback.  If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​ 

See also the [Visual Studio Roadmap](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-roadmap).

cc @TerryGLee for awareness
