### ISSUE TITLE
Latest update is missing

### ISSUE THREAD

**Issue by mfriedrich74** [MicrosoftDocs/visualstudio-docs#650]
15.6.27428.1 missing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* [Content](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Service: unspecified

**Comment by TerryGLee** [comment]
@mfriedrich74 Thanks for letting us know. A PR for this was placed in the queue yesterday; it should go live today.

**Comment by TerryGLee** [comment]
@mfriedrich74 The update is now live: [Visual Studio 2017 build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates)
