### ISSUE TITLE
Default port for Remote debugger is wrong

### ISSUE THREAD

**Issue by VinothKumar-Atos** [MicrosoftDocs/visualstudio-docs#6500]
It's mentioned 4024 is the default port in the Remote debugger but it is 4022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090c870a-9e10-7802-cc46-18b595864cb7
* Version Independent ID: 71d3f80d-23e2-0542-c5b6-35e8b6b5060f
* Content: [Attach to running processes with the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019)
* Content Source: [docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/attach-to-running-processes-with-the-visual-studio-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review this update in [private PR 7947](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7947).

**Comment by Mikejo5000** [comment]
@VinothKumar-Atos What version of Visual Studio are you running?

**Comment by VinothKumar-Atos** [comment]
Hi Mike,

I'm running VS 2017. but in the document you mentioned 4024 is the default port number for Remote Debugger but it is 4022

Regards,
Vinoth
________________________________

**Comment by Mikejo5000** [comment]
Thanks, you're correct it is 4022 in VS 2017. The port number increments 2 in each version of VS. [see here](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugger-port-assignments?view=vs-2019) The doc should be updated to make that distinction.

**Comment by Mikejo5000** [comment]
Actually, just checked the doc. If you switch to the VS 2017 view (upper left version selector), you do get the right information (port 4022). I know it's difficult to notice the version switcher at times, but that's the way we handle these cases currently. Link:
 [VS 2017 view](https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2017)
