### ISSUE TITLE
Version numbers not sorted

### ISSUE THREAD

**Issue by tinytone** [MicrosoftDocs/visualstudio-docs#6508]
When multiple versions are released on the same day, the version numbers don't appear to be sorted.

page:
https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019

table:

-- | -- | -- | --
16.4.20 | Release | March 9, 2021 | 16.4.31026.101
16.7.13 | Release | March 9, 2021 | 16.7.31026.100
16.9.1 | Release | March 9, 2021 | 16.9.31105.61

Shouldn't 16.9.1 be first, then 16.7.13 and then lastly 16.4.20 ?

This occurs with other version number entries throughout the table giving you the impression that you're releasing the versions that are lower, then higher, then lower etc

One would expect the latest version(s) at the top of the table, and reading down the table, the version numbers decrease (not jump around)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2019)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by ornellaalt** [comment]
The versions appear in date order, not in version number order.
