### ISSUE TITLE
Visual Studio Extension Development (VSIX): Docs for Codelens development

### ISSUE THREAD

**Issue by BillWagner** [MicrosoftDocs/visualstudio-docs#6509]
Moved from dotnet/docs#23401. Original issue by @lsoft

**Help us make content visible**

Searching for 'codelens' gives nothing.

**Describe the new article**

Visual Studio allows its users to create a VSIX with their custom codelenses. But information about that process is small and obsolete. We need a set of articles that shed light onto:

0. How to debug codelenses (see https://github.com/dotnet/docs/issues/23396)
1. How to target codelens to constructors or methods? (what is possible at all?)
1. Information about structure and components of the codelens window.
2. How to reorganize codelens window with custom controls etc.
3. How to organize a communication channel **from VS host to codelens** (for example, I want to refresh my codelenses)
4. Any hidden difficulties.

I hope, the next generations of VSIX authors will have a lesser troubles we had.

**Comment by j-martens** [comment]
#reassign:lerich

**Comment by PRMerger8** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: lerich
