### ISSUE TITLE
Template installed like this just creates an empty project.

### ISSUE THREAD

**Issue by DrewBrasher** [MicrosoftDocs/visualstudio-docs#651]
I followed these instructions to create an ASP.NET Core 2 Web Application template and after running the VSIX file I have the new project template listed but when I create a new project with it none of the files are there.  It is just an empty project.  My attempt can be found here:  https://github.com/DrewBrasher/ExampleAspNetCoreTemplate

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4359c3-e7ae-fac2-8dc8-0edfc543f46a
* Version Independent ID: ba448b8a-8bfc-bdc7-e22d-751cd84bcbe6
* [Content](https://docs.microsoft.com/en-us/visualstudio/extensibility/getting-started-with-the-vsix-project-template)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/getting-started-with-the-vsix-project-template.md)
* Service: unspecified

**Comment by DrewBrasher** [comment]
I believe this is a Visual Studio bug but I have found a workaround.  After exporting the project as a template (step 1b), you need to:

 1. Extract the zip file.
 2. Add this to the "TemplateData" section of the .vstemplate file:

> `<CreateInPlace>true</CreateInPlace>`

 3. Compress the files back into a zip file.
 4. Continue with the rest of the documentation.

Sources:
https://developercommunity.visualstudio.com/content/problem/21751/creating-new-project-from-vs-2017-rc-exported-temp-1.html

https://stackoverflow.com/questions/48553375/exported-project-template-in-vs2017-misses-source-files

**Comment by gorangrubic** [comment]
Just to confirm +DrewBasher's solution: It works. (VS2017 Community 15.7.4)

**Comment by gregvanl** [comment]
User is happy with workaround to product issue.
