### ISSUE TITLE
vs-installation: --remove option must be used with the modify command (at least?)

### ISSUE THREAD

**Issue by Skywalker13** [MicrosoftDocs/visualstudio-docs#6514]
Hello, the options are not very well described. I've lost **hours** to understand that to remove a product, I must use `--remove` with the **`modify`** command. The problem is that the `--remove` option is in the **Install options** section.. It's odd... 

---

![image](https://user-images.githubusercontent.com/397862/112168087-4a02aa80-8bf1-11eb-91b5-e580d922a167.png)  
![image](https://user-images.githubusercontent.com/397862/112168132-5129b880-8bf1-11eb-9281-aafc72662491.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@Skywalker13, we appreciate your feedback!
The [Using --remove](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---remove) section of the [Command-line parameter examples](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019) doc shows an example of using _--remove_ parameter with the _modify_ command. Hope this helps. 
We'll close this issue now, with our thanks to you for your feedback!

**Comment by Skywalker13** [comment]
Thank you @anandmeg, it's much better now
