### ISSUE TITLE
Track changes should indicate changes since last commit of TFS

### ISSUE THREAD

**Issue by ezeh2** [MicrosoftDocs/visualstudio-docs#6519]
## At the moment the feature `track changes`:
Only indicates changes since the file was opened. This indications are not shown anymore, if the file is closed and opened anymore.

## What I would like to have:
Indication, which show changes compared to the last commit in version control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ezeh2 -- thank you for your feedback.  If you are looking for functionality that isn’t currently provided by the product, please use our “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this works in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) page.​



cc @TerryGLee for awareness
