### ISSUE TITLE
Invalid Time format

### ISSUE THREAD

**Issue by RisingLiberty** [MicrosoftDocs/visualstudio-docs#6523]
The time format specified is invalid, visual studio uses
DD-MM-YY 00:00:00 AM/PM
instead of the given format
DD/MM/YYYY 00:00:00.

Maybe it uses the users' specified format in Windows settings?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f4a0078-1a87-6e3a-791e-d3068fb7032c
* Version Independent ID: 1d2d976d-2698-88d6-fac4-4d34e3855e2a
* Content: [Project and item template parameters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019)
* Content Source: [docs/ide/template-parameters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/template-parameters.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by RisingLiberty** [comment]
Yes, this is still an issue, although it has low priority.
I verified and it is using the user's date format settings.

**Comment by WilliamAntonRohm** [comment]
@RisingLiberty -- Nick, thank you for your followup.

@TerryGLee -- Terry, please look into this potential documentation issue.

**Comment by TerryGLee** [comment]
@RisingLiberty Thanks for your patience. You're right, it's the user settings that determine the time format. We've updated the page accordingly. We'll close this issue now, with our thanks to you for helping improve the documentation!
