### ISSUE TITLE
Feedback on the page I was just on

### ISSUE THREAD

**Issue by JN-LT** [MicrosoftDocs/visualstudio-docs#6524]
Help says "click uninstall or disable"... 
But there are no Disable or Uninstall buttons as shown in the snip. How do I make these buttons appear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and install extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.ExtensionManager);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.7.2)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@JN-NT Thanks for inquiring. Whether or not the **Extensions** > **Manage Extensions** dialog box shows an Uninstall option depends on the extensions that are installed. For example, here's a screenshot from my computer, where the first two extensions don't have an **Uninstall** button; they only have **Disable** and **Revert** buttons:

![image](https://user-images.githubusercontent.com/23244653/126715677-1982b09c-83bf-4446-a62f-9f8d790d20f3.png)

However, the third extension from the top does include an **Uninstall** button, as follows:

![image](https://user-images.githubusercontent.com/23244653/126716132-2ee0ab38-a081-4766-97d6-4ad538ccdd0a.png)

We'll close this issue now; please don't hesitate to contact us again if we can be of further help.
