### ISSUE TITLE
Not available in VS2019

### ISSUE THREAD

**Issue by karenpayneoregon** [MicrosoftDocs/visualstudio-docs#6525]
[Enter feedback here]
Unless told otherwise `generate Type` with the option to create a new type in another project or in the same project under a specific folder is missing in VS2019, have it in VS2017.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 716af324-80f2-afab-8bb2-292cb1ac8850
* Version Independent ID: 4b6ee1c4-79e7-77db-ee77-fa0ff0ef4804
* Content: [Generate class or type - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/generate-class-type?view=vs-2019)
* Content Source: [docs/ide/reference/generate-class-type.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/generate-class-type.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@karenpayneoregon Thanks for letting us know about this; we'll investigate, make content updates required, and report back.
