### ISSUE TITLE
Version matrix is out of date

### ISSUE THREAD

**Issue by mcx808** [MicrosoftDocs/visualstudio-docs#6527]
dotnet v5.0 (preview) is still showing. This has been in general release for a while now.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aecb3dcf-8452-6f71-9202-3ee7564abe06
* Version Independent ID: b57059a9-c666-2481-d2c0-452382220c7b
* Content: [.NET Core support - Visual Studio for Mac](https://docs.microsoft.com/en-gb/visualstudio/mac/net-core-support?view=vsmac-2019)
* Content Source: [mac/net-core-support.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/net-core-support.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @sayedihashimi
* Microsoft Alias: **sayedha**

**Comment by sayedihashimi** [comment]
This has been fixed

**Comment by sayedihashimi** [comment]
#please-close
