### ISSUE TITLE
Menu items don't match current versions

### ISSUE THREAD

**Issue by richardlawler** [MicrosoftDocs/visualstudio-docs#653]
The menu items in this doc don't match those in the default configuration of current version (7.4) of VS Community Mac.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86994b58-45d2-1490-02e9-3d1e7b09a23e
* Version Independent ID: 08ac7422-416b-4286-27d1-741b5c98a6bd
* [Content](https://docs.microsoft.com/en-us/visualstudio/mac/customizing-the-ide)
* [Content Source](https://github.com/Microsoft/visualstudio-docs/blob/master/mac/customizing-the-ide.md)
* Service: unspecified

**Comment by asb3993** [comment]
Hi @richardlawler, I've noticed some screenshots are a little outdated, but is there a menu item in particular that you noticed as being outdated?

**Comment by richardlawler** [comment]
I think this has been addressed in the subsequent edits to the docs.
