### ISSUE TITLE
Broken image links on Visual Language Dictionary

### ISSUE THREAD

**Issue by astrohart** [MicrosoftDocs/visualstudio-docs#6534]
RE: https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/visual-language-dictionary-for-visual-studio?view=vs-2019

The image reference links for the **Merge** and **Up** concepts are broken.

![image](https://user-images.githubusercontent.com/8261875/112724191-803d7400-8ee8-11eb-8641-37b8eea45332.png)
**Figure 1.** Entry for the **Merge** concept is missing its image.

![fig02](https://user-images.githubusercontent.com/8261875/112724163-52582f80-8ee8-11eb-9f91-210e499e2e42.png)
**Figure 2.** Entry for the **Up** concept is missing its image.

**Comment by TerryGLee** [comment]
@astrohart Thanks for the heads-up; we'll get this fixed and republished within 24 hours. We appreciate you helping to improve the documentation!
