### ISSUE TITLE
Find In Files dialog: "File Types" pattern rules are not documented

### ISSUE THREAD

**Issue by alegrigoriev** [MicrosoftDocs/visualstudio-docs#6535]
The find in files dialog changed, looks different, and the path pattern exclusion in File Types box is not documented (it's not really File Types anymore, because it allows patterns with paths)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b328a871-7747-31d6-737c-4e3f6d10d9d1
* Version Independent ID: 2b455842-a4ef-25bd-c386-f36e0d14ce3d
* Content: [Find and replace text, and multi-caret selection - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019)
* Content Source: [docs/ide/finding-and-replacing-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-replacing-text.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@alegrigoriev Thanks for posting; this page is in the queue to be updated. We'll report back when it's complete.

**Comment by TerryGLee** [comment]
@alegrigoriev Thanks for taking the time to write up this issue and apologies for our delayed response.

The good news is that we've updated the **_Find and replace text_** page to include updated screenshots for the following Visual Studio versions:

- [Visual Studio 2022 - Find and replace text](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2022)
- [Visual Studio 2019 - Find and replace text](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019)
- [Visual Studio 2017 - Find and replace text](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2017)

In addition, we added links to the two pages where each of the options on the screenshots are explained in detail, as follows:

"For more detailed information, see the [Find in Files](find-in-files.md) and [Replace in Files](replace-in-files.md) pages."

We'll close this issue now, with our additional thanks to you for helping improve the documentation!
