### ISSUE TITLE
Search paths only works for symbols

### ISSUE THREAD

**Issue by Cynacyn** [MicrosoftDocs/visualstudio-docs#6536]
Search paths only works for symbols, so autocomletion may propose you `custom.py` as `custom` when you pass it to **import**, but **import** itself will not have visibilty on from where to load `custom.py`. Only way to actually add `custom.py` visibility for import is to utilize `site` module in order to make custom modules paths visible for **import**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e34b9c9a-6356-61fa-d895-97c459465e75
* Version Independent ID: c317a64e-06a3-1081-08db-3fb278ea7fbf
* Content: [How Python search paths are applied - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/search-paths?view=vs-2019)
* Content Source: [docs/python/search-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/search-paths.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Thank you for you feedback. Given the age of this issue I'm closing it, but please feel free to reopen it if you feel it is still an issue that should be addressed.
