### ISSUE TITLE
WinForms tutorial is still targeting .NET Framework

### ISSUE THREAD

**Issue by ChayoteJarocho** [MicrosoftDocs/visualstudio-docs#6539]
Consider updating the screenshots and the instructions to instead target .NET 5.0.

This tutorial: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-csharp-winform-visual-studio.md

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@ChayoteJarocho, we appreciate your feedback!
The Windows Forms app tutorial is designed to use the default .NET Framework. 

We will close this issue now, but thank you again for contacting us.
