### ISSUE TITLE
hyperlink leading to a 404

### ISSUE THREAD

**Issue by aradarbel10** [MicrosoftDocs/visualstudio-docs#6550]
[Enter feedback here]
in the purple box right under "Write Test Methods", there's a link pointing towards Google Test Primer which leads to a 404 page on github. it sends to [this link](https://github.com/google/googletest/blob/master/googletest/docs/primer.md), but probably should send to [this active one](https://github.com/google/googletest/blob/master/docs/primer.md)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c18bdf17-06e1-aaf2-b6ce-c606c0e260da
* Version Independent ID: bd627b8f-54f0-84e0-55cd-285597af022d
* Content: [Write unit tests for C/C++ - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2019)
* Content Source: [docs/test/writing-unit-tests-for-c-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/writing-unit-tests-for-c-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@aradarbel10 
Thanks for the report. A fix should appear within a day.
