### ISSUE TITLE
dockerfile example is broken on the RUN instruction where build tools is installed

### ISSUE THREAD

**Issue by solstice333** [MicrosoftDocs/visualstudio-docs#6553]
In the dockerfile example, this exists:

```dockerfile
# Install Build Tools with the Microsoft.VisualStudio.Workload.AzureBuildTools workload, excluding workloads and components with known issues.
RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
    --installPath C:\BuildTools `
    --add Microsoft.VisualStudio.Workload.AzureBuildTools `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 `
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 `
    --remove Microsoft.VisualStudio.Component.Windows81SDK `
 || IF "%ERRORLEVEL%"=="3010" EXIT 0
 ```

Similarly, in my dockerfile, I used to have this:

```dockerfile
RUN C:\TEMP\vs_professional.exe --quiet --wait --norestart --nocache `
    --installPath C:\VisualStudioProfessional_16.5.4 `
    --config "C:\TEMP\foo.vsconfig" `
    || IF "%ERRORLEVEL%"=="3010" EXIT 0
```

On my machine, I'm able to consistently reproduce the case where the command fails to block until the installer is done. After `docker build` is complete, I `docker run` the image, and the path passed into `--installPath` does not exist. 

To fix this, I've referenced https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---wait which helped me change the command to

```dockerfile
RUN ["powershell", "-Command", "Start-Process -FilePath C:\\TEMP\\vs_professional.exe -ArgumentList \"--quiet\",\" --wait\",\"--norestart\",\"--nocache\",\"--installPath\",\"C:\\VisualStudioProfessional_16.5.4\",\"--config\",\"C:\\TEMP\\foo.vsconfig\" -Wait -PassThru"]
```

and now the command seems to really wait for the installer to finish before moving on to the next command

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@solstice333 -- thank you for your well-researched feedback.

@ornellaalt -- please look into this issue.

**Comment by jc01rho** [comment]
is there any updates on this issue?


when i try to install buildtools in conatiner,

```
FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Install build tools 2019
# Restore the default Windows shell for correct batch processing.
SHELL ["cmd", "/S", "/C"]

ADD https://aka.ms/vs/16/release/vs_buildtools.exe "C:\TEMP\vs_buildtools.exe"

RUN C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache \
	--installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools" \
    --add Microsoft.VisualStudio.Workload.VCTools \
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
    --add Microsoft.VisualStudio.Component.Windows10SDK.19041 \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10240 \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.10586 \
    --remove Microsoft.VisualStudio.Component.Windows10SDK.14393 \
    --remove Microsoft.VisualStudio.Component.Windows81SDK \
 || IF "%ERRORLEVEL%"=="3010" EXIT 0

RUN del C:\TEMP\vs_buildtools.exe

# Define the entry point for the docker container.
# This entry point starts the developer command prompt and launches the PowerShell shell.
ENTRYPOINT [ \
    "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\Common7\\Tools\\VsDevCmd.bat", \
    "&&", \
    "powershell.exe", "-NoLogo", "-ExecutionPolicy", "Bypass" \
]
```

it acutually install in C:\\Program Files (x86)\\Microsoft Visual Studio\\2022 not 2019
why installer ignores installPath parameter?

**Comment by milarso81** [comment]
@jc01rho I tried your example and it correctly installed into `"%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools"`. There is an issue when using the .NET images which I am addressing in PR which should resolve those issues. Please let me know if you are still running into issues.
