### ISSUE TITLE
Little recomendation

### ISSUE THREAD

**Issue by VS--** [MicrosoftDocs/visualstudio-docs#6555]
Hello! 
I read "Note
The following animation isn't intended to duplicate the preceding code. It's intended only to show how the autocomplete feature works."
But if you show the example maybe it will be better to show it without mistakes, i mean before the printing "c" variable value in animation we should define it.
Thanks and sorry for my not perfect english.
Best regards, Vladimir.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f783f152-b26c-0ea4-8017-3929c7465368
* Version Independent ID: 8777c084-6578-8a7f-89db-80b3f9d547a7
* Content: [Tutorial: Create a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by WilliamAntonRohm** [comment]
@VS-- Vladimir, thank you for your feedback.  Your English is very clear!

@ornellaalt -- Ornella, please look into this issue.

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@VS-- , we appreciate your feedback!
Please note that the animation isn't meant to duplicate the code exactly; instead, it's meant only to show the autocomplete feature. 
We'll close this issue now, but thank you for contacting us!

Please check out some duplicates of the same issue:
- https://github.com/MicrosoftDocs/visualstudio-docs/issues/4836
- https://github.com/MicrosoftDocs/visualstudio-docs/issues/4000
- https://github.com/MicrosoftDocs/visualstudio-docs/issues/3630
