### ISSUE TITLE
Please document how to disable all language specific analysers

### ISSUE THREAD

**Issue by pi3k14** [MicrosoftDocs/visualstudio-docs#656]
Since only English (en) dictionary is supported there should be a simple method to disable all language specific code analysers.

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: a6418bfb-3f92-b3ea-c957-8916d29964d9
* Version Independent ID: eb21172d-0108-0a88-a3a9-bb1ac13b9fc2
* Content: [CA1704: Identifiers should be spelled correctly | Microsoft Docs](https://docs.microsoft.com/nb-no/visualstudio/code-quality/ca1704-identifiers-should-be-spelled-correctly)
* Content Source: [docs/code-quality/ca1704-identifiers-should-be-spelled-correctly.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/ca1704-identifiers-should-be-spelled-correctly.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani is there an easy way to disable the language-specific code analysis rules?

**Comment by mavasani** [comment]
All language specific rules have category "Microsoft.Naming" (see [here](https://docs.microsoft.com/nb-no/visualstudio/code-quality/naming-warnings). User will need to add a ruleset suppression entry for each naming rule ID.

**Comment by gewarren** [comment]
@mavasani thanks for the quick reply. @pi3k14 I hope this answers your question.

**Comment by pi3k14** [comment]
@mavasani it answered my question - all though not the answered I searched for ...
Thanks for your speedy reply, hope you add this as a feature request.
