### ISSUE TITLE
Out of date template code

### ISSUE THREAD

**Issue by SuRFDownUnder** [MicrosoftDocs/visualstudio-docs#6561]
The html template code on this page is out of date.

{% load staticfiles %} < !-- Instruct Django to load static files -->

should be

{% load static %} < !-- Instruct Django to load static files -->

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1cd413-a2a8-9cb5-3f3a-94822a96af51
* Version Independent ID: feadb7ab-ebba-051d-e68c-a758235ce514
* Content: [Learn Django tutorial in Visual Studio step 3, static files and pages](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages?view=vs-2019)
* Content Source: [docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@JoshuaPartlow -- Joshua, please review this update in [private PR 7999](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/7999).

**Comment by JoshuaPartlow** [comment]
Hi @SuRFDownUnder - Thanks for taking the time to open this issue. Right now the tutorials are tied to the templates and the templates are using an earlier version of Django. We'll take this into account though when we next refresh the Django content.
