### ISSUE TITLE
Additional Step To Enable Custom Nesting

### ISSUE THREAD

**Issue by mbursill** [MicrosoftDocs/visualstudio-docs#6563]
To make custom nesting work in non web projects I had to add the following to the csproj:

```
  <ItemGroup>
    <ProjectCapability Include="DynamicFileNesting" />
  </ItemGroup>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2019)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by AngelosP** [comment]
How can I help?

**Comment by Nirmal4G** [comment]
I think what he asks is that should be mentioned in the Docs. Appropriate section that this could be added in the .NET SDK (w.r.t. `Microsoft.NET.Sdk`) pages

**Comment by Nirmal4G** [comment]
@AngelosP Has this been added to docs? I checked but it's not there.
