### ISSUE TITLE
MSBuild property function documentation should include version comparison functions

### ISSUE THREAD

**Issue by dsplaisted** [MicrosoftDocs/visualstudio-docs#6572]
We should add documentation for the version comparison property functions that were added here: https://github.com/dotnet/msbuild/pull/4911

/cc @marcpopMSFT @BenVillalobos

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019#msbuild-targetframework-and-targetplatform-functions)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by KalleOlaviNiemitalo** [comment]
This was already fixed in <https://github.com/MicrosoftDocs/visualstudio-docs/pull/6128> as part of <https://github.com/MicrosoftDocs/visualstudio-docs/issues/6127>.

**Comment by BenVillalobos** [comment]
> This was already fixed in #6128 as part of #6127.

Sounds like this can be closed

**Comment by WilliamAntonRohm** [comment]
#please-close
