### ISSUE TITLE
"Default" behaviour listed is incorrect

### ISSUE THREAD

**Issue by MatthewSteeples** [MicrosoftDocs/visualstudio-docs#6574]
`BackgroundDownloadDisabled`, `AdministratorUpdatesEnabled` and `AdministratorUpdatesOptOut` all indicate in the Default column that they have a default value of `1`. In the Description column the behaviour described indicates that a missing value behaves the same as a `0` value.

Only one of the above statements can be true

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2004ebd-c212-8698-c08b-f8ea800381be
* Version Independent ID: ccebc457-d543-c681-a2e7-de071bef28c6
* Content: [Set defaults for enterprise deployments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/set-defaults-for-enterprise-deployments?view=vs-2019)
* Content Source: [docs/install/set-defaults-for-enterprise-deployments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/set-defaults-for-enterprise-deployments.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @ornellaalt
* Microsoft Alias: **ornella**

**Comment by christineruana** [comment]
Thank you for reporting this doc bug Matthew.  I made a few corrections to the content today.
