### ISSUE TITLE
Update screenshots of editorconfig

### ISSUE THREAD

**Issue by Youssef1313** [MicrosoftDocs/visualstudio-docs#6575]
Update the screenshot of editorconfig .NET template under "Add an EditorConfig file to a project" heading if/when https://github.com/dotnet/templates/pull/461 gets merged.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [EditorConfig settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2019#add-an-editorconfig-file-to-a-project)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by TimShererWithAquent** [comment]
@WilliamAntonRohm I didn't assign, but it looks like an enhancement.

**Comment by Youssef1313** [comment]
PR is merged. The screenshot can be updated when it flows in a future release (not sure if it's going to be 16.10 or not)

**Comment by Youssef1313** [comment]
screenshot was updated at some point. Closing.
