### ISSUE TITLE
Host media files outside of the repo

### ISSUE THREAD

**Issue by 89z** [MicrosoftDocs/visualstudio-docs#6577]
I noticed that for some reason, large media files are being stored in the repo. For example, here is a 22 MB video file:

https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/snippets/csharp/VS_Snippets_Wpf/IntroToWPFSnippets/CSharp/Media/WPF.wmv

because of this, the Zip download for the repo is 444 MB:

https://github.com/MicrosoftDocs/visualstudio-docs/archive/refs/heads/master.zip

it might make sense to host the larger files outside of the repo, as it doesnt make sense to version control them, as they are not text files.

**Comment by ghogen** [comment]
This is standard for all docs.microsoft.com repos, so I think we should follow the existing practice.
