### ISSUE TITLE
Should article date reflect date of most recent change?

### ISSUE THREAD

**Issue by mrlife** [MicrosoftDocs/visualstudio-docs#6579]
There are updates from this year, however the date on the article is 10/11/2018.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0b8848-c2af-28e9-28bf-761d1cdf3d6d
* Version Independent ID: 7cc1bef7-ef0c-5c62-2b5f-45910764ba80
* Content: [Supported Code Changes (C# and Visual Basic) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-csharp?view=vs-2019)
* Content Source: [docs/debugger/supported-code-changes-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/supported-code-changes-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@mrlife Great feedback, thanks! I'll update the date.
