### ISSUE TITLE
Code UI test need to be install if missing under test.

### ISSUE THREAD

**Issue by ezzidrees** [MicrosoftDocs/visualstudio-docs#658]
https://docs.microsoft.com/en-us/visualstudio/test/use-ui-automation-to-test-your-code#creating-coded-ui-tests

Please add in following points 
I don't see the **Coded UI Test* project templates.*
Feature can be install if missing with Visual Studio Installer in VS Enterprise Edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75817b8c-177c-f5f0-2035-e18a9dd21ae3
* Version Independent ID: faa7aa5a-42d6-9695-8692-31e2d13e5bc9
* Content: [Use UI Automation To Test Your Code | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/test/use-ui-automation-to-test-your-code#creating-coded-ui-tests)
* Content Source: [docs/test/use-ui-automation-to-test-your-code.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/use-ui-automation-to-test-your-code.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by shahrukhshakil424** [comment]
In visual studio installer, under test and debugging Codedui is not listed. what should I do?
