### ISSUE TITLE
MSBuild: Information on locating msbuild is inaccurate

### ISSUE THREAD

**Issue by BenVillalobos** [MicrosoftDocs/visualstudio-docs#6587]
The `Get-MSBuildCmd` function uses the registry to locate MSBuild but MSBuild is not generally present in the registry. Can we update the sample to use `vswhere` or a similar technique?

/cc: You can ask @rainersigwald for more context.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f4be807-0eec-f478-f42c-8c89a8d87376
* Version Independent ID: 90ddaac9-ec34-16ee-3fa1-9e16459a9b35
* Content: [Use PowerShell to publish to dev and test environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-publishing-using-powershell-scripts?view=vs-2019)
* Content Source: [docs/azure/vs-azure-tools-publishing-using-powershell-scripts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/azure/vs-azure-tools-publishing-using-powershell-scripts.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@BenVillalobos -- Ben, thank you for your suggestion.

@ghogen -- Gordon, please look into this issue.
