### ISSUE TITLE
No Text Editor Advanced Page

### ISSUE THREAD

**Issue by fitdev** [MicrosoftDocs/visualstudio-docs#6588]
Whole page of Advanced Settings under Text Editor is missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?view=vs-2019)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by kkm000** [comment]
Yes, please. Some options are not obvious, and require trial an error to figure out. The fiirst one is the most intriguing, and has 4 choices :)
  
Sorry about the huge screenshot, my laptop has a high DPI, but the W10 screenshot tool ignores my 200% scaling. :(

![image](https://user-images.githubusercontent.com/8228229/116958798-99a4af00-ac50-11eb-9486-d2a549e75a4e.png)

**Comment by TerryGLee** [comment]
@fitdev Thanks for taking the time to write up this issue. We've received several reports about this missing page, and we're currently working on creating it and should have the new page published soon. However, in the interest of efficiency, we're closing this older report now in deference to the newest report of the same problem. However, we'll make sure to report back here when the new page is published, to close the loop. In the interim, please accept our sincere thanks for helping to improve the Visual Studio documentation!

**Comment by TerryGLee** [comment]
@fitdev To follow up, this previously missing page is now published; see [Options dialog box: Text Editor > Advanced](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-advanced).
