### ISSUE TITLE
Details on setting up for windows services

### ISSUE THREAD

**Issue by AlexKeySmith** [MicrosoftDocs/visualstudio-docs#659]
It would be good to have authoritative details on using this for windows services for the Visual Studio 2017 version.
There are a few blog posts, however rather old and I suspect the CLSID has changed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 995e3a2f-5674-63c4-5899-ba9a6b0e5da6
* Version Independent ID: b93833ad-9195-96b4-6fac-8893836cde4e
* Content: [Using the IntelliTrace stand-alone collector | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-intellitrace-stand-alone-collector)
* Content Source: [docs/debugger/using-the-intellitrace-stand-alone-collector.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/using-the-intellitrace-stand-alone-collector.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@deborahc Deborah, do you have any input for this issue? Thx

**Comment by Mikejo5000** [comment]
@AlexKeySmith Alex, sorry for the slow response. Sounds like you already saw this blog post?
https://blogs.msdn.microsoft.com/devops/2015/05/14/collect-data-from-a-windows-service-using-the-intellitrace-standalone-collector/

**Comment by Mikejo5000** [comment]
Let me know if you are still having issues with the CLSID and I'll get you in touch with the right folks.

**Comment by AlexKeySmith** [comment]
Hi @Mikejo5000 sorry for not responding to you sooner, I haven't been back on the same project recently to have another go. But yes I'd seen that post thank and you're correct I was having trouble with the CLSID.

Thanks for your help.

**Comment by Mikejo5000** [comment]
@AlexKeySmith OK, great. For help with the issue, would you start a conversation with the IntelliTrace team at protid@microsoft.com

**Comment by PhilBarila** [comment]
@Mikejo5000, I tried that e-mail, but got a bounce that there is no such address at Microsoft.com.  Typo?

**Comment by PhilBarila** [comment]
I found another post where the recommendation was to register the Intellitrace.Profiler DLL in order to get the CLSID.  That worked, the 2017 CLSID that worked for me is:  {BBB416E1-1473-4012-8081-C1DBF569AF1F}
