### ISSUE TITLE
Description of logic for choosing between multiple available debuggee-side DLLs

### ISSUE THREAD

**Issue by zspitz** [MicrosoftDocs/visualstudio-docs#6592]
From my testing, if there are multiple target framework debuggee DLLs -- `netcoreapp`, `netstandard2.0`, `net2.0`:

* For **.NET Framework** -- If the debugged process runtime supports `netstandard2.0`, and there is a `netstandard2.0` debuggee-side DLL, that will be used; otherwise `net2.0` will be used.
* For **.NET Core** and **.NET 5+** -- `netcoreapp` will always be used, even if the runtime supports `netstandard2.0` and there is a `netstandard2.0` debuggee-side DLL available.

Not sure how to describe this in the documentation, or even if it should be described.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c0470059-27e3-58a0-155e-84fbaefae158
* Version Independent ID: 95c9afb2-32f3-945b-9381-9f711179c77d
* Content: [Install a Visualizer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-install-a-visualizer?view=vs-2019)
* Content Source: [docs/debugger/how-to-install-a-visualizer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/how-to-install-a-visualizer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@zspitz I'm a little concerned about losing clarity and creating more confusion here. Let me know if you have a suggestion you feel strongly about.
