### ISSUE TITLE
Not able to follow

### ISSUE THREAD

**Issue by wimmerb72** [MicrosoftDocs/visualstudio-docs#6593]
I could not follow the example starting at "Reference .NET libraries: write to a log"
step 4. Tried placing the code before several While loops and all failed. Is there a final code example to look at?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80ccbb63-7f84-55e6-1b3e-f48400aa17ae
* Version Independent ID: 6aba5d1b-f8ce-7b82-560e-c6a9926423ac
* Content: [Tutorial: Extend a simple C# console app - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-console-part-2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console-part-2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@wimmerb72 It looks like what's intended is to add the calculator variable just before while (! endApp)

**Comment by wimmerb72** [comment]
thank you for the quick response!
