### ISSUE TITLE
confusing screen shot

### ISSUE THREAD

**Issue by noxiouscloud** [MicrosoftDocs/visualstudio-docs#660]
The screenshot in the step discussing the addition of the event handler shows the properties of the wrong control. It shows those of the time label, not the sum numeric control.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29cdd64b-99b4-4fe2-7129-6be73efd0891
* Version Independent ID: b67dcedd-6653-6304-b3d8-3473fa84047b
* Content: [Step 5: Add Enter Event Handlers for the NumericUpDown Controls | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/ide/step-5-add-enter-event-handlers-for-the-numericupdown-controls)
* Content Source: [docs/ide/step-5-add-enter-event-handlers-for-the-numericupdown-controls.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/step-5-add-enter-event-handlers-for-the-numericupdown-controls.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@noxiouscloud Thanks for your feedback; we appreciate it. It's in our backlog queue to get fixed; we'll report back when it is.
