### ISSUE TITLE
Can you please help provide a video recording of this process? We have customers asking for a demo and a video recording would be great.

### ISSUE THREAD

**Issue by thoaingan** [MicrosoftDocs/visualstudio-docs#6604]
I'd like to request a video recording of this process of migrating from Visual Studio to VS+GH licenses from the MSDN Admin experience's perspective ("**Moving to Visual Studio with GitHub Enterprise**"). We have customers who are inquiring about this process and a video would be great to present since we do not have access to MSDN portals to demo this process ourselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5ebc0e0-3c9e-d757-6701-325db481c575
* Version Independent ID: a56278d0-ee74-055d-5795-bee05424bc7f
* Content: [Assign Visual Studio subscriptions with GitHub Enterprise](https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-github)
* Content Source: [subscriptions/assign-github.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/assign-github.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@thoaingan -- Thanks for your request.  It turns out that we already have a video in the planning stage right now for this topic.  Are there specific aspects of the process that you'd like to see covered?

**Comment by thoaingan** [comment]
We have a customer asking for a demo of this section particularly "Moving to Visual Studio with GitHub Enterprise" (which looks like 2 clicks :) https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-github#moving-to-visual-studio-with-github-enterprise

**Comment by evanwindom** [comment]
@thoaingan -- It is pretty straightforward.  It sounds like the planned video will meet the need.  Thanks again!

**Comment by evanwindom** [comment]
#please-close

**Comment by thoaingan** [comment]
> @thoaingan -- It is pretty straightforward. It sounds like the planned video will meet the need. Thanks again!

Awesome! Thank you!
