### ISSUE TITLE
Incomplete MSBuild Special Characters

### ISSUE THREAD

**Issue by tulis** [MicrosoftDocs/visualstudio-docs#6610]
List of MSBuild Special Characters is incomplete. From [`Microsoft.Build.Shared.EscapingUtilities` class](https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Shared/EscapingUtilities.cs#L311) point of view, the list currently is missing `(`, `)`, and `\`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 665605c0-95ba-10a1-1d91-3c2b863630b1
* Version Independent ID: 2b544ce8-21dc-74b9-4bc2-53d36a0add15
* Content: [MSBuild Special Characters - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters?view=vs-2019)
* Content Source: [docs/msbuild/msbuild-special-characters.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-special-characters.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by KalleOlaviNiemitalo** [comment]
The backslash `\` is not listed in `s_charsToEscape` and should not be added to the MSBuild Special Characters doc page. In the `s_charsToEscape` source code, the backslash only occurs as `'\''` to escape the apostrophe character `'`, which is already listed on the page.

**Comment by tulis** [comment]
@KalleOlaviNiemitalo Yes, you are right!!
