### ISSUE TITLE
The example doesn't show anything about this page

### ISSUE THREAD

**Issue by AntoninB** [MicrosoftDocs/visualstudio-docs#662]
The WizardData section is empty in the example and that's what I was searching for when I read the WizardData page.
And while providing an example of completion would be good, it would be better if there was an example of an xml file being used to get data from a wizard.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26f6ecce-e3ab-5f6f-a456-97c9fc199670
* Version Independent ID: da5a180e-d58f-9504-7263-e617a3098708
* Content: [WizardData Element (Visual Studio Templates) | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/extensibility/wizarddata-element-visual-studio-templates)
* Content Source: [docs/extensibility/wizarddata-element-visual-studio-templates.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/wizarddata-element-visual-studio-templates.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
WizardData is used to send extra data to the custom wizard extension not get data from a wizard. The contents depends on the custom wizard and can be any XML blob for the wizard. 
Unfortunately the custom wizard example on docs.microsoft.com at https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-wizards-with-project-templates doesn't show a sample WizardData XML blob.
