### ISSUE TITLE
ClickOnce user.config

### ISSUE THREAD

**Issue by NormanGiHu** [MicrosoftDocs/visualstudio-docs#6627]
This article is from 2016.
And ClickOnce doesn't merge user.config file anymore.
With .net 5 the user.config is not merged into new ClickOnce Version Folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f461aa-b3ae-4202-4f1f-d1b440f1cd63
* Version Independent ID: 48b9d6c3-3ca8-66c9-32ab-364fdb49ae16
* Content: [ClickOnce and Application Settings - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-and-application-settings?view=vs-2019)
* Content Source: [docs/deployment/clickonce-and-application-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/clickonce-and-application-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Thanks, we'll take a look at this.
