### ISSUE TITLE
Worth mentioning, I think, that this appears _not_ to be a feature of VS for mac.

### ISSUE THREAD

**Issue by capsicumDreams** [MicrosoftDocs/visualstudio-docs#6628]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 108b5373-83a5-8d82-0414-939b0caf2866
* Version Independent ID: 9bb010ce-5641-c2a4-ce2a-d53943ac5432
* Content: [Load a subset of projects - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/filtered-solutions?view=vs-2019)
* Content Source: [docs/ide/filtered-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/filtered-solutions.md)
* Product: **visual-studio-dev16**
* Technology: **vs-ide-general**
* GitHub Login: @jillre
* Microsoft Alias: **stsu**

**Comment by TerryGLee** [comment]
@capsicumDreams We've added a Note; thanks for your feedback and for helping to improve the documentation!
