### ISSUE TITLE
This is cool

### ISSUE THREAD

**Issue by morgs32** [MicrosoftDocs/visualstudio-docs#663]
```
This is a code block
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* Content: [Overview of Visual Studio 2017 | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide#feedback)
* Content Source: [docs/ide/visual-studio-ide.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/visual-studio-ide.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@morgs32 thanks for your feedback. Can you elaborate on what you are providing feedback about?

**Comment by morgs32** [comment]
@gewarren Using github for comments is genius. I love it. Do you think you will open source your work on it or shall I get to work making my own?

**Comment by gewarren** [comment]
@morgs32 thanks so much. @jdanyow can you comment on whether the work to enable github issues will be open sourced?

**Comment by gewarren** [comment]
@morgs32 my guess is that the GitHub issues linking code will not be open-sourced.

**Comment by jdanyow** [comment]
Sorry, just seeing this.

@morgs32 the open source version is https://utteranc.es
