### ISSUE TITLE
Description of "File Types" makes no mention of syntax

### ISSUE THREAD

**Issue by LegalizeAdulthood** [MicrosoftDocs/visualstudio-docs#6639]
There are two important things to understand about the syntax of the text entered into this field:

1) multiple file types can be entered by separating them by semi-colons (;)
2) You can exclude file types by specifying an exclamation point (!) before the file type

For example, suppose you want to search all *.txt files, but exclude files named *-foo.txt, you could enter

`*.txt;!*-foo.txt`

To restrict the search to all .txt files that don't have "-foo" at the end of the filename.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e27881f-04bc-b7ba-e217-8360278a14f8
* Version Independent ID: d31c8050-339a-688c-869e-ff7942fd3f74
* Content: [Find in Files - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.findreplace.findinfiles)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/find-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/find-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@LegalizeAdulthood Thanks for your inquiry and apologies for our delayed response. We've recently revised the [**Find in Files**](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2019) page, which now includes the updates you've suggested to the [**File types**](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2022#file-types) section.

We'll close this issue now with our further thanks to you for helping us improve the documentation.
