### ISSUE TITLE
Add IsPublishable documentation

### ISSUE THREAD

**Issue by MiYanni** [MicrosoftDocs/visualstudio-docs#6643]
Related: https://github.com/dotnet/project-system/pull/7165

The [`IsPublishable`](https://github.com/dotnet/sdk/blob/397a0beb1dd8ccbea15c59909314d648a91054db/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L17) property allows the [`Publish`](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets#default-build-targets) target to run for MSBuild. The [`dotnet publish`](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) command runs the `Publish` target. According to the targets documentation, VS uses `PublishOnly` target since it won't do a build. The CLI docs specifically state that they use the `Publish` target.

In this case, we want to have a `IsPublishable` option for a .csproj file so that someone can control the affect of running `dotnet publish` on the project. This is especially useful if you run `dotnet publish` on a solution file; thus allowing project filtering via this property. The only 'documentation' that exists is a comment made in this [GitHub thread](https://github.com/dotnet/docs/issues/13365#issuecomment-512152483). We would like some official documentation for this property.

**Comment by WilliamAntonRohm** [comment]
@MiYanni -- Michael, thank you for your well-researched feedback.  Are you referring to this [dotnet publish](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish?tabs=netcore21) article?

**Comment by MiYanni** [comment]
@WilliamAntonRohm I don't know where the documentation for `IsPublishable` should exist. It affects the `Publish` target. The command `dotnet publish` runs the `Publish` target. But, you can run the `Publish` target independent of that command. We (.NET project system for VS) are adding the ability to change the value of `IsPublishable` in our project property pages (right click on project, select Properties). We provide links to documentation for each property so someone can look up information about what the property does. In this case, `IsPublishable` has no documentation, so we have no link to provide the user.

**Comment by WilliamAntonRohm** [comment]
@MiYanni -- Michael, thank you for clarifying.  I am looking into this issue.

**Comment by WilliamAntonRohm** [comment]
@MiYanni -- thank you for clarifying.  I am looking into this issue.

**Comment by tdykstra** [comment]
I would document it here: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#publish-related-properties and mention it in the dotnet publish reference https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish

@gewarren what do you think?

**Comment by MiYanni** [comment]
This was published here: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#ispublishable

**Comment by diegosasw** [comment]
Is this accurate? It does not seem to work for my .NET 5 test projects.
https://github.com/dotnet/docs/issues/13365#issuecomment-932957609

**Comment by gewarren** [comment]
@diegosasw It sounds like your question is resolved and that it does work in .NET 5.
