### ISSUE TITLE
ClickOnce documentation uses he/him pronouns when referring to a user

### ISSUE THREAD

**Issue by Remi05** [MicrosoftDocs/visualstudio-docs#6647]
Consider using gender-neutral pronouns (they/them/their) when referring to a user. For example, the following passage of the "[Permission elevation and updates](https://docs.microsoft.com/en-us/visualstudio/deployment/choosing-a-clickonce-update-strategy?view=vs-2019#permission-elevation-and-updates)" section could be more inclusive by avoiding the use of the pronouns "he"/"him" when talking about the user.

> If a new version of a ClickOnce application requires a higher level of trust to run than the previous version, ClickOnce will prompt the user, asking **him** if **he** wants the application to be granted this higher level of trust.

I can send out a PR later this week if it helps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68edbcaa-2659-5028-67a5-37213e773f91
* Version Independent ID: cb725635-0bce-53dd-7353-8113d64c110f
* Content: [How ClickOnce Performs Application Updates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-clickonce-performs-application-updates?view=vs-2019)
* Content Source: [docs/deployment/how-clickonce-performs-application-updates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-clickonce-performs-application-updates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Remi05 -- Rémi, thank you for your feedback.  You are welcome to create a PR for an update.
