### ISSUE TITLE
Don't recommend using diagnostic text logs without also suggesting binlogs and the structured log viewer

### ISSUE THREAD

**Issue by dsplaisted** [MicrosoftDocs/visualstudio-docs#6652]
Trying to make sense of MSBuild text logs, especially at the diagnostic verbosity, is painful.  In documentation such as this page, we should recommend using a binary log and [MSBuild Structured Log Viewer](https://msbuildlog.com/) in addition to, or instead of, using a diagnostic verbosity text log.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 388a3b6c-b978-d46a-4650-e23be5c64951
* Version Independent ID: 6ac25a2f-7799-19fe-b3e0-b4d9a39c0e8c
* Content: [MSB3277: Found conflicts between different versions of 'assembly' that could not be resolved - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb3277?view=vs-2019)
* Content Source: [docs/msbuild/errors/msb3277.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/errors/msb3277.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, thank you for your follow-up.

#please-close
