### ISSUE TITLE
No mention of two of the five visible options displayed

### ISSUE THREAD

**Issue by mr-intj** [MicrosoftDocs/visualstudio-docs#6665]
Came to this page for more information about **Use editor background in the Find All References tool window**., but it's not mentioned (neither is **Automatically limit search to selection**).

Specifically, does "editor background" refer to the _background color_?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad4a8307-4cd1-1865-7c20-c60a4e461c3f
* Version Independent ID: 1a0d569a-d577-c5ef-fc19-e2520abc5dd7
* Content: [Find and Replace, Environment, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/find-and-replace-environment-options-dialog-box?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Environment.FindReplace);k(TargetFrameworkMoniker-.NETFramework,Version%253Dv4.6.1)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/ide/reference/find-and-replace-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/find-and-replace-environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@mr-intj -- Scott, thank you for your feedback and question.  Yes, it is the background color.

**Comment by TerryGLee** [comment]
@mr-intj We've updated the [Find and Replace, Environment, Options Dialog Box](https://docs.microsoft.com/en-us/visualstudio/ide/reference/find-and-replace-environment-options-dialog-box?view=vs-2022) page to include the information you were looking for. Thanks for bringing this to our attention, and also for helping us to improve the documentation!
