### ISSUE TITLE
html entity display error

### ISSUE THREAD

**Issue by successgo** [MicrosoftDocs/visualstudio-docs#6667]
the html entity `'` in the 2nd link in 'Recommended content' may display error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 911666fa-55ac-cbc1-ce79-66c058859ad9
* Version Independent ID: 571eec5d-8fb9-2401-fc4c-8a7896723eb7
* Content: [MSBuild - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2019)
* Content Source: [docs/msbuild/msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@successgo -- Success, thank you for your feedback.  Please clarify where the single quote is -- are you referring to this link?
- [Walkthrough: Create an MSBuild project file from scratch](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch)

**Comment by successgo** [comment]
@WilliamAntonRohm thanks for your reply.

No, it not the link in your comment. And I see the recommend content list changed when you revisit the page.

Here is the screenshot abount the problem link.

![image](https://user-images.githubusercontent.com/13791720/117915238-77c5bf00-b317-11eb-9d63-06145111c2e9.png)

And for convienience here are the links below:

https://docs.microsoft.com/en-us/visualstudio/msbuild/whats-new-msbuild-16-0

https://docs.microsoft.com/en-us/visualstudio/msbuild/what-s-new-in-msbuild-15-0

**Comment by WilliamAntonRohm** [comment]
@successgo -- Success, thank you for clarifying.  I am updating those titles.

**Comment by WilliamAntonRohm** [comment]
@successgo -- Success, thank you for catching these.  I have updated the documentation and it should be live by tomorrow.

**Comment by successgo** [comment]
Yes, it worked perfectly now. Thanks @WilliamAntonRohm
