### ISSUE TITLE
Feature: Can you add to the docs how to configure solution configuration correctly

### ISSUE THREAD

**Issue by Legends** [MicrosoftDocs/visualstudio-docs#667]
I want to configure the solution, but I have an issue:

Look [here](https://stackoverflow.com/questions/49200229/vs2017-solution-configuration-wont-apply-changes).

Is this normal behaviour?

**Comment by gewarren** [comment]
@Legends thanks for the feedback. I will try to make this clearer in the build docs.

**Comment by Legends** [comment]
I would't change the Docs, but rather rethink the implementation in VS. Make it more intuitive.
When you open the solution properties and change the selection from  "All configurations" to anything else, it prompts you : Do you want to save the changes made to the property pages?
**What changes?** 

When you iterate over the single configurations it doesn't prompt you again, until you reach "All configurations" again and then change it to another configuration.

The solution property form and the Configuration Manager Form are so similar, that I can't see any difference between them.

It's very confusing...

**Comment by Legends** [comment]
Perhaps one of the VS IDE team can take a look at this

**Comment by gewarren** [comment]
@prnadago who is the right PM to forward this build configuration feedback to?

**Comment by prnadago** [comment]
That would be Ruben Rios. :)

**Comment by gewarren** [comment]
@prnadago thank you. @rub8n can you look at this feedback?

**Comment by Bethannfrum** [comment]
Fix and return to original

**Comment by gewarren** [comment]
@Legends Sorry for the delay on this, but we do have a new feature suggestion capability on [Developer Community](https://developercommunity.visualstudio.com/content/idea/post.html?space=8). Please make your feature suggestion there and it will get more traction from the product team.
