### ISSUE TITLE
This documentation doesn't appear to be relevant to the latest VS 2017

### ISSUE THREAD

**Issue by metamoof** [MicrosoftDocs/visualstudio-docs#668]
Starting up the Blank project sets up a Blank solution, with no subprojects

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b25d4cd-0c3f-e9a6-6256-ea54d0972d4b
* Version Independent ID: babd49b7-8e18-13dc-99f2-6783495cb0dc
* Content: [Learn app-building basics with Xamarin.Forms in Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio#solution)
* Content Source: [docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by gewarren** [comment]
@metamoof thanks for the feedback. @conceptdev can you comment on this?

**Comment by metamoof** [comment]
This appears to be a bug on my system... You cannot create the subprojects if you're updating the Android SDK in the background. Once that finished, it worked.

It can be closed.
