### ISSUE TITLE
Doc for DebuggerTypeProxyAttribute and DebuggerDisplayAttribute could mention VisualStudio options that impact their behavior in the debugger

### ISSUE THREAD

**Issue by b8adamson** [MicrosoftDocs/visualstudio-docs#6685]
I would've found it helpful if the Doc for DebuggerTypeProxyAttribute and DebuggerDisplayAttribute would have linked or mentioned the Visual Studio Debugging option to "Show raw structure of objects in variables windows" (and any other settings that may impact how the debugger uses these attributes).

The  "Show raw structure of objects in variables windows"  option appears to _partially_ disable the debugger from using these attributes.

I say partially because the attributes seem to still be applied when hovering the mouse over some of the variables in the source text document window regardless of this setting.

It would also be helpful to know if there was a setting to _fully_ disable the use of these attributes in the debugger when working with code that may have poorly written customizations using these attributes.

In any case I think it's important for people thinking of using the Debugger customizing attributes in their code to know that the "Show raw structure of objects in variables windows"  option exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ba74624-2169-35d8-f2be-ae51f9d367d8
* Version Independent ID: ad2b7ddf-b5f6-b3f3-76e2-7974a3d94cbf
* Content: [Display custom type using DebuggerTypeProxy - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/using-debuggertypeproxy-attribute?view=vs-2019)
* Content Source: [docs/debugger/using-debuggertypeproxy-attribute.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/using-debuggertypeproxy-attribute.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Adding a note in this doc.
