### ISSUE TITLE
Dismissing the dialog box does not correct this error

### ISSUE THREAD

**Issue by DavidHogue** [MicrosoftDocs/visualstudio-docs#669]
I realize the underlying problem may be somewhere else, but the solution listed here is not helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b20c58b-4ca0-a827-1d3d-57e0bf19b5c2
* Version Independent ID: 5aa70859-b679-36d8-6494-6f9122276062
* Content: [Could not retrieve schema information for database object <object name> | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/data-tools/could-not-retrieve-schema-information-for-database-object-object-name)
* Content Source: [docs/data-tools/could-not-retrieve-schema-information-for-database-object-object-name.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/data-tools/could-not-retrieve-schema-information-for-database-object-object-name.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@DavidHogue thank you for the feedback. I'll try to improve this topic.
