### ISSUE TITLE
Out-of-Date

### ISSUE THREAD

**Issue by tnblank77** [MicrosoftDocs/visualstudio-docs#6691]
This page seems incredibly out-of-date with respect to the "modernization" of the "Find in Files" dialog:

https://devblogs.microsoft.com/visualstudio/modernizing-find-in-files/

This command no longer accepts arguments or switches:

Command "Edit.FindInFiles" does not accept arguments or switches

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69c0cc55-2f9c-eee3-88a9-18b855628667
* Version Independent ID: 6cf127d4-6f3d-c9e6-3984-a38ba5a41984
* Content: [Find in Files Command - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/find-in-files-command?view=vs-2019)
* Content Source: [docs/ide/reference/find-in-files-command.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/find-in-files-command.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by tnblank77** [comment]
Also: I would love if it still supported all or most of these arguments and switches as my Extension calls this directly and is currently not working in Visual Studio 2019 16.5 and beyond.

**Comment by TerryGLee** [comment]
@tnblank77 Thanks for taking the time to write up this issue. Unfortunately, the feature's been deprecated; as such, we added the following note to the [Find in Files Command](https://docs.microsoft.com/visualstudio/ide/reference/find-in-files-command?view=vs-2019) page that says, "Support for this command was discontinued in version 16.5 of Visual Studio 2019. If you use this command with version 16.5 or a later version, you might see an error message that says, *Command "Edit.FindinFiles" does not accept arguments or switches.*"

However, there is some information provided by the community that might help you with the problem you describe with your Extension; please check out the following DevComm ticket and the remarks in includes, here: https://developercommunity.visualstudio.com/content/problem/976771/editfindinfiles-not-working-in-visual-studio-2019.html

We'll close this issue now, with our (additional) thanks to you for your help in improving the documentation.

**Comment by tnblank77** [comment]
Yes I am already on DevComm ticket (Tyler Blank).

I hope there's something offered for Extensions in the future as this feature was pretty much pulled out from underneath me with the 16.5 update (along with other Extension developers on there).

**Comment by TerryGLee** [comment]
@tnblank77 I'm sorry to hear about how this feature deprecation adversely affected you. Also, I apologize for pointing you to a solution on DevComm that you yourself devised. 

If it helps, please know that this GitHub issue is associated with the [Find in Files Command](https://docs.microsoft.com/visualstudio/ide/reference/find-in-files-command?view=vs-2019) page, so if others experience the same problem, they'll be able to view this issue and the links within it, which hopefully might prove useful to them.
