### ISSUE TITLE
Still Waiting for Visual Studio 2019 support after 2 years of release...

### ISSUE THREAD

**Issue by stijnveeke** [MicrosoftDocs/visualstudio-docs#6693]
Hey Microsoft in fear that you've forgotten the 2 year active issue here you go. The community would like you to add this to Visual Studio 2019 please give us a status update. With kind regards the waiting community.

https://developercommunity.visualstudio.com/t/add-intellitest-support-for-net-corestandard/359250

In case you're not planning to do this please let us know and change the docs to inform us about it.

**Comment by dgerding** [comment]
Agreed. A useful tool that evaporated .

**Comment by kendrahavens** [comment]
We haven't forgotten the active issue. Unfortunately, we simply didn't have interesting updates to provide. I've commented on the ticket that we need to re-cost this work and we do believe it would be a significant investment involving some re-writes and needing to re-build our team knowledge around the code base.

Thank you for continuing to show interest in this as it definitely does impact our priorities when we are assessing what we can accomplish in the next release cycles.
