### ISSUE TITLE
Broken link with 404 error

### ISSUE THREAD

**Issue by JasonCard** [MicrosoftDocs/visualstudio-docs#6696]
The link in following string is broken with 404 error: 
```
For detailed instructions for IIS, see [How to specify additional document types for HTTP compression](https://support.microsoft.com/help/234497).
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4baae220-67c0-09b8-caf6-43a6dedb8f5a
* Version Independent ID: 498f0add-fbd5-c603-e350-1ddf5d9bb740
* Content: [Server/client configuration issues (ClickOnce) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/server-and-client-configuration-issues-in-clickonce-deployments?view=vs-2019)
* Content Source: [docs/deployment/server-and-client-configuration-issues-in-clickonce-deployments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/server-and-client-configuration-issues-in-clickonce-deployments.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by JasonCard** [comment]
@WilliamAntonRohm Thank you for the update, but I just checked and the link is still broken with 404 error, so could you please help to review and fix again?

**Comment by WilliamAntonRohm** [comment]
@JasonCard -- Jason, I'm fixing a typo I introduced in the destination URL.  Here is the correct link:
- https://docs.microsoft.com/en-us/troubleshoot/iis/content-types-http-compression

**Comment by JasonCard** [comment]
@WilliamAntonRohm Thank you, confirmed the link is now fixed :)
