### ISSUE TITLE
Is there a way to LIST all of the assigned key shortcuts?

### ISSUE THREAD

**Issue by MappingSteve** [MicrosoftDocs/visualstudio-docs#6697]
This doc page does an excellent job of describing how to find a command in the list of commands, and assign a keyboard shortcut.

But that isn't what I want to do. I want to do the "opposite":

See a complete list of all keys that have been assigned, and what they are assigned to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5859be-5f6e-4354-a0b0-c14ffc047d23
* Version Independent ID: d2033d27-92b9-6f70-286a-cefb0a58b15a
* Content: [Identify and customize keyboard shortcuts - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@MappingSteve -- Steve, thank you for your question.  Please add this issue as a suggestion here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
