### ISSUE TITLE
Table in EditorConfig article is too wide

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/visualstudio-docs#67]
The table at the end of the article [Create portable, custom editor settings with EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options#support-editorconfig-for-your-language-service) is too wide in my 1338px-wide Firefox window, which causes it to overlap with the article TOC:

![](https://cloud.githubusercontent.com/assets/287848/24550192/50188186-161d-11e7-8dc5-cc534b2aea03.png)

I think this should be fixed, though I'm not sure what would be the right way to do that.

**Comment by kempb** [comment]
Hi svick,
Thanks for your report. I viewed the topic you referenced on different browsers on my system (Chrome, Edge, and IE) and couldn't replicate this issue. It could be a rendering issue with your system or a transient problem. If you haven't already, try rebooting the system and see if the problem persists. If it does persist, does it happen on different web browsers, or only a specific one? Does it happen with other topics that have tables, or just this topic?  Thanks!

**Comment by svick** [comment]
Yeah, the behavior seems to be different now. Instead of overlapping, the table is truncated, with seemingly no way to access the part that is not visible. And it's not just one browser, Firefox and Edge behave the same.

Screenshot from Firefox:

![](https://user-images.githubusercontent.com/287848/27301207-b8d96c4a-5532-11e7-8668-b59df8e6c281.png)

From Edge:

![](https://user-images.githubusercontent.com/287848/27301248-d6a03d44-5532-11e7-8c18-4fbcf1c8106d.png)

So, it's still a problem, just a different problem than before.

**Comment by kempb** [comment]
Okay, thanks for checking and reporting back. I'm going to file a bug on this for further investigation.

**Comment by gewarren** [comment]
I have created a PR to fix this. It should be live in a couple days' time. Thanks for reporting this.
