### ISSUE TITLE
__proto__ has been deprecated. 

### ISSUE THREAD

**Issue by user135711** [MicrosoftDocs/visualstudio-docs#671]
Since __proto__  has been deprecated and could cease working, these examples should be updated to suggest another method for changing the prototype of an instance for instance Object.setPrototypeOf(player, Foe.prototype); with a note about performance when changing the prototype or even Reflect.sePrototypeOf(target, prototype).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f922a5d-685c-64d6-9750-4c78a066153c
* Version Independent ID: 65b41c77-4a81-2932-c22a-cb69297dc684
* Content: [Prototypes and Prototype Inheritance | Microsoft Docs](https://docs.microsoft.com/en-us/scripting/javascript/advanced/prototypes-and-prototype-inheritance)
* Content Source: [scripting-docs/javascript/advanced/prototypes-and-prototype-inheritance.md](https://github.com/Microsoft/visualstudio-docs/blob/master/scripting-docs/javascript/advanced/prototypes-and-prototype-inheritance.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Working on fix
