### ISSUE TITLE
TransformText

### ISSUE THREAD

**Issue by jcaruso001** [MicrosoftDocs/visualstudio-docs#6714]
TransformText is missing here.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a170869-23a9-96c9-d85b-372adcb19230
* Version Independent ID: d900eb64-973b-78dc-47eb-799aad1ee592
* Content: [Run-Time Text Generation with T4 Text Templates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/run-time-text-generation-with-t4-text-templates?view=vs-2019)
* Content Source: [docs/modeling/run-time-text-generation-with-t4-text-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/run-time-text-generation-with-t4-text-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by JoshuaPartlow** [comment]
Hi @jcaruso001 - Could you elaborate about what's missing? TransformText is discussed on that page [here](https://docs.microsoft.com/en-us/visualstudio/modeling/run-time-text-generation-with-t4-text-templates?view=vs-2019#the-code-built-from-the-template).

**Comment by JoshuaPartlow** [comment]
Closing given no reply. If this is still an issue you think should be addressed, please feel free to reopen.
