### ISSUE TITLE
Linkedin learning benefits are not activating from my.visualstudio.com

### ISSUE THREAD

**Issue by Emarcode** [MicrosoftDocs/visualstudio-docs#6716]
Document Details

ID: 817e4651-f9f9-4b7f-8740-0e6057bf58ad
Sign-in address: mohamed.fawzi@student.aast.edu
Subscription: Visual Studio Dev Essentials
Content: LinkedIn Learning Benefit in Visual Studio Subscriptions
Content Source: subscriptions/vs-linkedin-learning.md
 Product: vs-subscription

**Comment by WilliamAntonRohm** [comment]
@Emarcode -- thank you for your feedback regarding [The LinkedIn Learning benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-linkedin-learning).   

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@Emarcode - Thanks for reaching out.  Visual Studio Dev Essentials is a free program.  It does not include the same LinkedIn Learning benefits as a Visual Studio Professional or Visual Studio Enterprise subscription.  The LinkedIn Learning tile in Dev Essentials is basically just a link to LinkedIn Learning's free trial.  So the experience outlined in the article isn't applicable to Dev Essentials.  I will add a note to the article to clarify that.

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- thank you for clarifying.

**Comment by Emarcode** [comment]
@evanwindom 
Thank you for clarifying, but for this, you should remove the LinkedIn benefit as the LinkedIn free trial exists with or without your services.

**Comment by evanwindom** [comment]
@Emarcode -- The documents are not intended to address Visual Studio Dev Essentials.  The Visual Studio subscriptions are paid services and contain more robust offers for LinkedIn Premium that are not included in Dev Essentials.  So, from the standpoint of paid subscriptions, the existence of the free trial is moot.  The information in the article is definitely relevant to Visual Studio subscriptions, but not to VSDE.
