### ISSUE TITLE
There is no "install" command

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/visualstudio-docs#6720]
There is no "install" command. The only commands are modify, update, repair, uninstall, and export. It appears that the "(blank)" command is for both "install" and "layout maintenance." 

Please make `install` an alias of the `(blank)` command in both code and documentation. It might also be helpful to have an explicit "layout" command for cache layout maintenance.

Explicit is better than implicit.

(blank)     The default command both installs the product, and it is used for all layout maintenance operations.
modify      Modifies an installed product.
update      Updates an installed product.
repair      Repairs an installed product.
uninstall   Uninstalls an installed product.
export      Exports installation selection to an installation configuration file. Note: Can only be used with vs_installer.exe.

Bootstrapper commands and command-line parameters

Parameters Description

--installPath <dir>     For the default **install command**, this parameter is Optional and describes where the instance will be installed on the client machine. For other commands like update or modify, this parameter is Required and denotes the installation directory for the instance to act upon.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by WilliamAntonRohm** [comment]
@Liturgist -- Paul, thank you for your considered feedback.  Please add this issue here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

@j-martens -- Josée, please look into this potential documentation issue.

**Comment by j-martens** [comment]
We are happy to document once it has been added to the product. 

@Liturgist, please share your product enhancement idea here: 
Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/).

#please-close as not a documentation issue.
