### ISSUE TITLE
XInput functions 404

### ISSUE THREAD

**Issue by DeviantBit** [MicrosoftDocs/visualstudio-docs#6721]
All XInput function pages, except XInputGetDSoundAudioDeviceGuids, 404.

This is from the Programming Guide, Programming Reference, and search. When I looked at the public mirror for win32 online documentation, the pages don't seem to exist.

https://docs.microsoft.com/en-us/windows/win32/xinput/functions

This page doesn't even mention the functions: https://docs.microsoft.com/en-us/windows/win32/api/xinput/

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks @DeviantBit - we have an internal bug logged against our content engineering team for a related issue. I'll continue to track that and see if your issue is resolved with that fix.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @DeviantBit - an engineering fix seems to have resolved your issue. 

@WilliamAntonRohm - this issue can be closed.
