### ISSUE TITLE
The "Report a problem directly to the Visual Studio developer community" is not correct at all.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#673]
You cannot report a problem directly. Period. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* Content: [How to Report a Problem with Visual Studio 2017 | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#feedback)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio-2017.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@StingyJack Thanks for reporting this! You are correct; we've fixed this text in the doc and the fix will go live tomorrow.
