### ISSUE TITLE
This doc should mention that the WCF Connected Service is only for .NET Core projects.  For .NET Framework projects it should mention the Add Service Reference dialog

### ISSUE THREAD

**Issue by John-Hart** [MicrosoftDocs/visualstudio-docs#6736]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89a74dad-9ebf-c219-2ad8-3aefaa7f8127
* Version Independent ID: 353c73ea-98dc-b0d9-2a83-fd9af8f6840a
* Content: [Add, update, or remove a WCF data service reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/how-to-add-update-or-remove-a-wcf-data-service-reference?view=vs-2019)
* Content Source: [docs/data-tools/how-to-add-update-or-remove-a-wcf-data-service-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/how-to-add-update-or-remove-a-wcf-data-service-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Fixed in private PR https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9091
