### ISSUE TITLE
Visual Studio Subscription with GitHub Enterprise setup status as "Temporarily Unavailable"

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/visualstudio-docs#6738]
I reviewed the setup or onboarding process for accessing GHE as a benefit of VS Subscription. I do not see the same flow explained in the VS Benefits documentation for GHE access. I am seeing   **Temporarily unavailable**  status when I login to my VS subscription benefit portal. Can you add any content in the FAQ of this same page to explain how to resolve this and meaning of this status?

![image](https://user-images.githubusercontent.com/7546032/120854929-a27bef80-c532-11eb-9001-4b5458d719ee.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e0dbc2-35de-0efe-ae1b-b9d2507f2b4d
* Version Independent ID: f1e1caeb-78d3-262f-6311-6606720893a3
* Content: [Visual Studio subscriptions with GitHub Enterprise](https://docs.microsoft.com/en-us/visualstudio/subscriptions/access-github)
* Content Source: [subscriptions/access-github.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/access-github.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by WilliamAntonRohm** [comment]
@Anand-Moghe -- Anand, thank you for your feedback and question.

@evanwindom -- Evan, please look into this issue.

**Comment by evanwindom** [comment]
@Anand-Moghe Hi Anand.  Thanks for the report.  I'm investigating, and will post an update when new information is available.

**Comment by Anand-Moghe** [comment]
@WilliamAntonRohm  and @evanwindom Thanks a lot for looking into this.

**Comment by evanwindom** [comment]
@Anand-Moghe -  I just heard from our engineering team that the issue has been resolved.  If you continue to see problems, please let me know.  Thanks again for the report.

**Comment by evanwindom** [comment]
#please-close
