### ISSUE TITLE
Is that path correct?

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/visualstudio-docs#674]
If I have read this correctly, then in the example about merging props file from the parent directory, should this line: `<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />` be changed to this: `<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)'))" /> `

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d410ebeb-3841-a0a9-efb4-185823add4dc
* Version Independent ID: 7e397179-4ccc-054c-8137-5e8f2430d794
* Content: [Customize your build | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build)
* Content Source: [docs/msbuild/customize-your-build.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/customize-your-build.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, can you verify this before I change it? Thanks.

**Comment by rainersigwald** [comment]
I think it's correct as it currently is.

In this scenario, you have something like

```
S:\WORK\DBPROPSDEMO_ROOT
│   Directory.Build.props
│
└───folder
    └───subfolder
            Class1.cs
            Directory.Build.props
            subfolder.csproj
```

Without the `..`, you get a warning:

```
s:\work\DBPropsDemo_Root\folder\subfolder\Directory.Build.props(2,1): warning MSB4011: "s:\work\DBPropsDemo_Root\folder\subfolder\Directory.Build.props" cannot be imported again. It was already imported at "C:\Program Files (x86)\Microsoft Visual Studio\Preview\EntInt\MSBuild\15.0\Microsoft.Common.props (36,3)". This is most likely a build authoring error. This subsequent import will be ignored. [s:\work\DBPropsDemo_Root\folder\subfolder\subfolder.csproj]
```

That's because `GetPathOfFileAbove` is somewhat confusingly named. It starts its search in the argument directory and then looks upward. Since there is a Directory.Build.props file in the current directory (it's the current file!) it just finds that again.

If you want `subfolder/Directory.Build.props` to import `root/Directory.Build.props`, it must start its search (at least) one folder up.

Does that make sense @dazinator?

**Comment by dazinator** [comment]
Ah I see. Yes the name of the method had me confused as to exactly what it was doing, but the explaination makes sense :-)

**Comment by dazinator** [comment]
So its more of a: `FindFileInDirectoryOrDirectoryAbove` :-)

**Comment by rainersigwald** [comment]
Indeed. I claim innocence on the naming since we were going for consistency with an existing name added before any of us was on the team 😇
