### ISSUE TITLE
How to hide annotations?

### ISSUE THREAD

**Issue by PeterAdam** [MicrosoftDocs/visualstudio-docs#6741]
How to hide annotations is missing from subtitle "Use annotations to reveal useful information about your code".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 378274af-75f0-8696-cc1a-5067834c6dd8
* Version Independent ID: 560d03f2-e5e8-44a2-8794-7e7bfe15f322
* Content: [Accessibility tips and tricks for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/accessibility-tips-and-tricks?view=vs-2019)
* Content Source: [docs/ide/reference/accessibility-tips-and-tricks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/accessibility-tips-and-tricks.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@PeterAdam -- thank you for your feedback.  There does not appear to be a way to hide annotations.  Please note this as a feature request here:

- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
