### ISSUE TITLE
ERROR: "The project doesn't know how to run the profile IIS Express."

### ISSUE THREAD

**Issue by smking204** [MicrosoftDocs/visualstudio-docs#6744]
I get this error message when I try to run IIS Express:

"The project doesn't know how to run the profile IIS Express."

This error message is not addressed within the tutorial, and I have not been able to find a solution online. I am using VS 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core?view=vs-2019)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@smking204 - This issue may provide you with a solution to your support question. https://github.com/MicrosoftDocs/visualstudio-docs/issues/763

**Comment by WilliamAntonRohm** [comment]
@j-martens -- Josée, thank you for that pointer.

@smking204 -- Steve, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
