### ISSUE TITLE
This window is not supported for the selected project

### ISSUE THREAD

**Issue by tazhanzhou** [MicrosoftDocs/visualstudio-docs#6746]
Are you sure the Data Sources is supported by Windows Forms App? "This window is not supported for the selected project" is showing in Data Sources window.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0568679-0027-5e02-88f6-2e27ec1aa733
* Version Independent ID: b86cf53c-2b52-7bab-c45e-b6a935194d18
* Content: [Create a Windows Form to search data - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-windows-form-to-search-data?view=vs-2019)
* Content Source: [docs/data-tools/create-a-windows-form-to-search-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-windows-form-to-search-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@tazhanzhou The article should say, as other pages do, that this scenario is only supported for .NET Framework WIndows Forms projects (project template name "Windows Forms App (.NET Framework)" not "Windows Forms App". If you are using .NET Core Windows Forms (e.g. 3.1 or 5), then it is not supported. I will update the article to make this limitation clear.

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, thank you for updating this documentation.

@tazhanzhou -- Ta, this issue will be auto-closed when Gordon's update is ready for publish.  This documentation update should be live by tomorrow.
