### ISSUE TITLE
very useful

### ISSUE THREAD

**Issue by esjimenezp** [MicrosoftDocs/visualstudio-docs#675]
Thank team for share this information about modify the Workloads of Visual Studio, best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d0cb94-2886-79ce-39dd-0336282369b9
* Version Independent ID: e8bcc58e-98af-e3ad-2629-0b4515047d0b
* Content: [Modify Visual Studio 2017 | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio)
* Content Source: [docs/install/modify-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/modify-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@esjimenezp Thank you very much for saying so!
