### ISSUE TITLE
Incorrect info on python profiling

### ISSUE THREAD

**Issue by baidurja** [MicrosoftDocs/visualstudio-docs#6756]
In VS2019, it is under Analyze->Launch Python Profiling and NOT Debug->Launch Python Profiling

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399822f9-b83b-a607-4310-a7f496cf1f27
* Version Independent ID: c1300996-f8f4-e297-993a-1d614efe7e79
* Content: [Measure performance of Python code - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/profiling-python-code-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/profiling-python-code-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/profiling-python-code-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@baidurja -- Baidurja, after looking at a fresh install of Visual Studio 2019, I'm seeing it as documented.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
