### ISSUE TITLE
Could not download the zip file.

### ISSUE THREAD

**Issue by ehackett00** [MicrosoftDocs/visualstudio-docs#6759]
Hello,

Sorry, I am new to this.  I have started with git but I have not yet downloaded any code or application.  The zip file was a good idea, but it did not work for me.  This was step 2 in get the app.  Does anyone have any suggestions other than continuing the git tutorial?

Ed
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38a38919-b557-4723-7ea9-b0fbafbfdc52
* Version Independent ID: 2117c374-eda9-906e-392e-c55e1ebf8060
* Content: [Docker tutorial - Part 1: Build and run the todo list sample app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/your-application)
* Content Source: [docker/tutorials/your-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/your-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ehackett00 -- thank you for your feedback.  This issue is being tracked in #5827.

cc @ghogen for awareness

**Comment by ghogen** [comment]
I've updated the tutorial with some clearer instructions. It should be visible by tomorrow.

**Comment by ghogen** [comment]
Navigate to the repo https://github.com/docker/getting-started, click on the green Code button, choose Download ZIP, then open the downloaded ZIP file, Extract All.
