### ISSUE TITLE
Missing documentation of required Unity Editor preference to enable debugging

### ISSUE THREAD

**Issue by anticrisis** [MicrosoftDocs/visualstudio-docs#676]
From the Unity documentation: "Editor Attaching: Check this box to allow debugging of scripts in the Unity Editor. If this option is disabled, it is not possible to attach a script debugger to Unity to debug your scripts." -- https://docs.unity3d.com/Manual/Preferences.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56378a75-b639-d64b-d7fb-00a7eafa20b5
* Version Independent ID: c66870c5-4153-7b42-7aad-fc454c39f9cd
* Content: [Using Visual Studio Tools for Unity | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity)
* Content Source: [docs/cross-platform/using-visual-studio-tools-for-unity.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/cross-platform/using-visual-studio-tools-for-unity.md)
* Service: **unspecified**
* GitHub Login: @conceptdev
* Microsoft Alias: **crdun**

**Comment by conceptdev** [comment]
Thanks @anticrisis, you're right about the preferences. Generally this should be enabled by default, but I agree that we should cover this case if customers are having issues.

**Comment by anticrisis** [comment]
Thanks for your reply. I discovered this preference after several hours and much support from Unity QA when trying to understand why the debugger was simply failing to attach without any error message. It's possible that installing one of their 2018 beta versions turned the Editor Attaching option off on my machine.

**Comment by gewarren** [comment]
Fix has been merged.
