### ISSUE TITLE
Missing wait 

### ISSUE THREAD

**Issue by zleight1** [MicrosoftDocs/visualstudio-docs#6765]
See https://github.com/MicrosoftDocs/visualstudio-docs/issues/6102

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2019)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
@zleight1  thanks for your post. Can you provide more information about the doc bug you are experiencing? Thank you!

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@zleight1, thanks for your feedback!
We are updating the page ([Advanced example for containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2019)) to address this issue, the page should be live later today. 

We'll close this issue now, with our thanks to you for helping to improve the documentation!
