### ISSUE TITLE
Move .Net Core warning to first page/top of installation instructions

### ISSUE THREAD

**Issue by BillStrait** [MicrosoftDocs/visualstudio-docs#6766]
It would be cool if you mentioned Class Designer is not available for .Net Core somewhere before the installation instructions. I spent a good ten minutes trying to figure out why the installation wasn't working before I saw a note on a specific way to open the designer saying Core projects can't use it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a723ca4-ee71-386d-aa7a-461dd565bc84
* Version Independent ID: fa9856a9-4bab-805d-c5a1-bd8e506e4fb0
* Content: [Use Class Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/class-designer/designing-and-viewing-classes-and-types?view=vs-2019)
* Content Source: [docs/ide/class-designer/designing-and-viewing-classes-and-types.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/class-designer/designing-and-viewing-classes-and-types.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@BillStrait -- thank you for your suggestion.  I have added a note to this article regarding applicability, copied from [To display the contents of a complete project in a class diagram](https://docs.microsoft.com/en-us/visualstudio/ide/class-designer/how-to-add-class-diagrams-to-projects?view=vs-2019#to-display-the-contents-of-a-complete-project-in-a-class-diagram).
