### ISSUE TITLE
Please Provide Simple Working Example

### ISSUE THREAD

**Issue by solvingj** [MicrosoftDocs/visualstudio-docs#677]
We've tried both syntaxes of the CTest "add_test()" command and neither work.  Please provide an example which works. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3f12b8-8048-3c19-8582-2ab35cbda74e
* Version Independent ID: 860805e8-915b-1c76-b6d3-4addc07da1a0
* Content: [How to use CTest for C++ in Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-ctest-for-cpp)
* Content Source: [docs/test/how-to-use-ctest-for-cpp.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/how-to-use-ctest-for-cpp.md)
* Service: **unspecified**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
investigating

**Comment by esweet431** [comment]
This [blog post](https://cognitivewaves.wordpress.com/cmake-and-visual-studio/) provides an [example](https://github.com/cognitivewaves/CMake-VisualStudio-Example) of a CMake project that uses CTest in Visual Studio. 

It's possible you are missing the enable_testing() command which is mentioned in the [CTest documentation](https://gitlab.kitware.com/cmake/community/wikis/doc/ctest/Testing-With-CTest).

**Comment by mikeblome** [comment]
topic has been updated to mention enable_testing()
