### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by DrPepperBianco** [MicrosoftDocs/visualstudio-docs#6770]
[Enter feedback here]

»For a list of control IDs, see Office 2010 help files: Office fluent user interface control identifiers.«

links to 
https://www.microsoft.com/download/details.aspx?id=6627

But this link is dead!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a0b25-416d-8a39-c054-32d4520cb887
* Version Independent ID: 5842f7a6-11f8-86cb-01b2-d739c7dcf12d
* Content: [How to: Customize a built-in tab - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-customize-a-built-in-tab?view=vs-2019)
* Content Source: [docs/vsto/how-to-customize-a-built-in-tab.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-customize-a-built-in-tab.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by DrPepperBianco** [comment]
I assume this is the newer version of the resource:
https://www.microsoft.com/en-us/download/confirmation.aspx?id=50745

**Comment by WilliamAntonRohm** [comment]
@DrPepperBianco -- please see this repository and let me know if it's sufficient:
- [Office Fluent User Interface Control Identifiers](https://github.com/OfficeDev/office-fluent-ui-command-identifiers)

@John-Hart -- is the above repo suitable for the target of the download link in step 4 here?
- [To add groups to a built-in tab](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-customize-a-built-in-tab?view=vs-2019#to-add-groups-to-a-built-in-tab)
