### ISSUE TITLE
Link to Image Library is broken

### ISSUE THREAD

**Issue by KathleenDollard** [MicrosoftDocs/visualstudio-docs#6774]
The link to the Image Library is broken. If this is no longer available, this page should probably be removed or at least edited heavily. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05fe994a-b63e-dfc1-9de9-97e56a4e4917
* Version Independent ID: 95c63cef-e907-f443-a885-d1265f47c171
* Content: [Image Library - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/the-visual-studio-image-library?view=vs-2019)
* Content Source: [docs/designers/the-visual-studio-image-library.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/the-visual-studio-image-library.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@KathleenDollard Thanks for the feedback; can you try again? I tested the link and it works. Also, please note that while the top of the page has an advert for the Surface, if you scroll down, you can see the details where you can download the Image Library:

![image](https://user-images.githubusercontent.com/23244653/122260934-b0156b80-ce88-11eb-81c8-8dc009fc9f48.png)

**Comment by TerryGLee** [comment]
@KathleenDollard Since we cannot repro this issue, we'll close it now. Thanks though for contacting us; we appreciate it.
