### ISSUE TITLE
Cannot install Visual Studio 2019 after removal

### ISSUE THREAD

**Issue by pulak777** [MicrosoftDocs/visualstudio-docs#6776]
Visual Studio installer window disappearing every time after showing (image below)

![Screenshot 2021-06-17 002652](https://user-images.githubusercontent.com/54091088/122279395-9f570b00-cf05-11eb-8c3a-8ffb65db1ffc.png)

_Background_ 
It's been a few weeks since I started getting this [#issue](https://github.com/PowerShell/PowerShell/issues/15550) on PowerShell. I thought it was due to newly installed Visual Studio, and since the ` VS Installer ` wasn't opening, I manually removed `Visual Studio` folders from my PC, and then tried to reinstall `VS2019` and got into this state. How to resolve this?

**Comment by WilliamAntonRohm** [comment]
@pulak777 -- Pulak, thank you for your feedback and that issue.  It looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by pulak777** [comment]
@WilliamAntonRohm thanks for your time, actually I forgot to mention that I tried the steps mentioned on [Troubleshoot Visual Studio installation and upgrade issues](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues?view=vs-2019), but the problem is still persisting.
The outcomes for the above troubleshooting methods

**`Step 1 - Check whether this problem is a known issue`**  Found the issue on developer community, but no solution is mentioned there. [#issue](https://developercommunity2.visualstudio.com/t/Visual-Studio-Installer-disappearing-aft/1409258?space=8&q=disappearing+installer)
**`Step 2 - Try repairing Visual Studio`** vs_installer.exe isn't opening, so cannot perform repair
**`Step 3 - Check with the developer community`** same as Step 1
**`Step 4 - Delete the Visual Studio Installer directory to fix upgrade problems`** tried this step several times
 **`Step 5 - Report a problem`** cannot perform, for the same reason as "Step 2"  [vslogs.zip](https://1drv.ms/u/s!AmB4LF85LjN5jjFfv0EppUN5XBZ7?e=fpYHCf)
**`Step 6 - Run InstallCleanup.exe to remove installation files`**   `"C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\layout\` at this path I only have `Setup.exe` file and **no** `InstallCleanup.exe` file

I will share the "Live chat" and "Gitter" responses as soon as I get them.

**Comment by pulak777** [comment]
Finally solved. `C:\$Mft` file was corrupted. Now VS working perfectly fine.
