### ISSUE TITLE
docker-compose no longer works as soon as a breakpoint is hit

### ISSUE THREAD

**Issue by mtrtm** [MicrosoftDocs/visualstudio-docs#6796]
I have been using this for years, and now all my old projects and new projects exhibit the same behavior.  Anytime a breakpoint is hit when running multiple containers with docker-compose as the startup project, Visual Studio locks up and gives me a notification box which won't respond until I kill VS with task manager.  

Please get this working!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aee46f8-9db1-33ef-b637-fc8e8881fab9
* Version Independent ID: 6c469f9f-9751-669f-3dd4-c4fb49c9ae19
* Content: [Work with multiple containers using Docker Compose - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2019)
* Content Source: [docs/containers/tutorial-multicontainer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/tutorial-multicontainer.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@mtrtm -- thank you for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do so, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by mtrtm** [comment]
Maybe you could help me contact them.  There's already an issue, and it's been open for months.  Closing this because you want good statistics doesn't help me.

https://vsf-prod.westus.cloudapp.azure.com/idea/1144960/cannot-debug-into-xunit-tests-with-docker-compose.html

**Comment by WilliamAntonRohm** [comment]
@mtrtm -- thank you for your followup.  I am investigating escalation paths.

**Comment by MarioAtTrimble** [comment]
Thanks - I really appreciate it!

**Comment by WilliamAntonRohm** [comment]
@BigMorty, @luboms -- Mike, Lubo, can you help escalate this blocking issue?

**Comment by BigMorty** [comment]
Hi @mtrtm, I am the Program Manager that owns the VS Docker & Compose tooling. If you would email me at mike.morton@microsoft.com I would be happy to schedule a call for you, I, and a developer on my team to work through the problem you are having.

**Comment by WilliamAntonRohm** [comment]
@BigMorty -- thank you for your assistance.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by BigMorty** [comment]
I am meeting with @MarioAtTrimble this week to discuss the issue. I would keep it open until we meet and have a resolution or workaround.

**Comment by BigMorty** [comment]
Myself and few others from our team met with @MarioAtTrimble today and it turned out the issue he was seeing with debugging a Docker Compose project was only happening when he had ReSharper enabled. @WilliamAntonRohm, I think we can close this issue now. :-)
