### ISSUE TITLE
Subscription Level / Program

### ISSUE THREAD

**Issue by stscholz914** [MicrosoftDocs/visualstudio-docs#681]
All listed are marked Not available which ones are available?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60b2872e-438a-b86e-9ff5-6dc0021f3fe8
* Version Independent ID: 8b9e935e-07ad-4992-edb9-e8361d867617
* Content: [EMS Benefit | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-ems)
* Content Source: [subscriptions/vs-ems.md](https://github.com/Microsoft/visualstudio-docs/blob/master/subscriptions/vs-ems.md)
* Service: **unspecified**
* GitHub Login: @ghogen

**Comment by gewarren** [comment]
@evanwindom Can you take a peek at this question?

**Comment by evanwindom** [comment]
The eligibility information has been corrected.  This issue can be closed.

**Comment by stscholz914** [comment]
Fixed
