### ISSUE TITLE
Dead link: Control ID list for built-in Ribbon tabs

### ISSUE THREAD

**Issue by eeskildsen** [MicrosoftDocs/visualstudio-docs#6812]
The link to the list of built-in Ribbon tab control IDs is dead.

> For a list of control IDs, see [Office 2010 help files: Office fluent user interface control identifiers](https://www.microsoft.com/download/details.aspx?id=6627).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a0b25-416d-8a39-c054-32d4520cb887
* Version Independent ID: 5842f7a6-11f8-86cb-01b2-d739c7dcf12d
* Content: [How to: Customize a built-in tab - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-customize-a-built-in-tab?view=vs-2019)
* Content Source: [docs/vsto/how-to-customize-a-built-in-tab.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-customize-a-built-in-tab.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@eeskildsen -- Eric, thank you for your feedback.  Please see [my related comment](https://github.com/MicrosoftDocs/visualstudio-docs/issues/6770#issuecomment-866319992) in issue #6770.

Closing this issue as a duplicate.

cc @John-Hart for awareness
