### ISSUE TITLE
Explain required version of setup executable

### ISSUE THREAD

**Issue by anfangda** [MicrosoftDocs/visualstudio-docs#6814]
Hi,

you should note that the NEW setup executable of the desired version is needed to update an existing, older versioned layout folder/content. The 16.9.6 setup does not upgrade to 16.10.2, but the 16.10.2 setup does. This is not noted anywhere.

Thanks and best regards
Daniel

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc51a257-b7a9-4660-7e12-88cdfcd9cd53
* Version Independent ID: dad2fd97-7244-6802-e853-5d5974838996
* Content: [Update a network-based installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/update-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/update-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@anfangda, thank you for your feedback! We've added information on how to update the layout to a specific version of the product to the page: [Create a network installation of Visual Studio.](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022) The changes should be live later today.

Closing this now. Please let us know if you any other feedback. Thanks again!
