### ISSUE TITLE
Wrong descriptions under Usage

### ISSUE THREAD

**Issue by victorjz** [MicrosoftDocs/visualstudio-docs#682]
See properties Item and Collection.  The text under Usage describes adding to the collection.  It should describe checking to see if an item exists in the collection.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 521ccaa4-af21-d095-2158-ca66f8ca2c59
* Version Independent ID: 6c78afa4-bc0a-76f7-215d-4d802fc06b48
* Content: [ExistsInCollection<T> Activity Designer | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/workflow-designer/existsincollection-t-activity-designer)
* Content Source: [docs/workflow-designer/existsincollection-t-activity-designer.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/workflow-designer/existsincollection-t-activity-designer.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@victorjz thanks for the feedback. I will fix this.
