### ISSUE TITLE
Steps to "find" installcleanup.exe do not work 

### ISSUE THREAD

**Issue by johndhunter** [MicrosoftDocs/visualstudio-docs#6821]
Tried installing visual studio (enterprise) - get to workloads choice - close window - navigate to C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\layout - the only resource is Setup.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2019)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by johndhunter** [comment]
Instead found installcleanup.exe at C:\Program Files (x86)\Microsoft Visual Studio\Installer

**Comment by TerryGLee** [comment]
@johndhunter Thanks for letting us know; we'll investigate and report back soon.

**Comment by TerryGLee** [comment]
@johndhunter Apparently, this is a known but temporary issue; a workaround is posted to the Developer Community, where product issues are triaged and resolved. Here's the thread on DevComm: [**cannot uninstall the vs and find InstallCleanup.exe**](https://developercommunity.visualstudio.com/t/cannot-uninstall-the-vs-and-find-Install/1465251?space=8&q=InstallCleanup.exe) 

The synthesis of this is that it's a temporary problem with a proposed solution, per the comment from Xiu Li in the DevComm post, who says the following:

> "The InstallCleanup tool was accidentally dropped from 16.10 but added back into the 16.11.
> It a completely isolated tool, so you can download 16.11 Preview and run the bootstrapper file to update VS Installer.
> https://visualstudio.microsoft.com/vs/preview/ 
> Then you can find InstallCleanup.exe in C:\Program Files (x86)\Microsoft Visual Studio\Installer." 

We'll close this now with our thanks to you for bringing the problem to our attention, and for helping us to socialize its solution, too, by way of this GitHub Issue.

Cheers,
~ Terry
