### ISSUE TITLE
PyBind11 recommendation warning - ABI compatibility issues

### ISSUE THREAD

**Issue by brandonmpetty** [MicrosoftDocs/visualstudio-docs#6824]
I think there should be a note, or warning, about using PyBind11 for C++ with regard to module ABI compatibility.
Essentially, there is none between minor versions of Python since PyBind11 cannot use the **Py_LIMITED_API** flag.
See: 
https://github.com/pybind/pybind11/issues/1755
https://docs.python.org/3/c-api/stable.html

What that means is that anyone who creates a module from a C++ project and targets Python 3.7 will not be able to distribute that module to anyone else using a version other than 3.7.  This makes it nearly impossible to distribute.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by rjmolyneaux** [comment]
Thank you @brandonmpetty for notifying us of the potential compatibility issue. As a result, we will be updating this document to reflect this change. We appreciate you taking the time to help us improve documentation!
