### ISSUE TITLE
What are the targets?

### ISSUE THREAD

**Issue by ciaran036** [MicrosoftDocs/visualstudio-docs#683]
I can see that there is a BeforeBuild and AfterBuild target, but what is the full list of targets? There doesn't appear to be any link to mention what targets are available...

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a67233-ab6a-e330-7b2d-21c95dd9caba
* Version Independent ID: 381c76df-d847-6ee0-b16e-c7bbc52cec13
* Content: [MSBuild Targets | Microsoft Docs](https://docs.microsoft.com/en-gb/visualstudio/msbuild/msbuild-targets)
* Content Source: [docs/msbuild/msbuild-targets.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/msbuild-targets.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ciaran036 Thanks for your comments! Can you clarify? There is a link to the Target element, which shows all the defined attributes supported for Target. Otherwise, BeforeBuild and AfterBuild specify any named target, based on the Name attribute.

**Comment by seanwhitepc** [comment]
I can try to clarify the initial question:
There doesn't seem to be a comprehensive list of default Targets for MSBuild.  For example, I have found in existing code in my job that there are targets for /t:Build and /t:Publish for .sqlproj but I have found no documentation or list of targets that ship with MSBuild by default nor additional properties for those targets (for example, /p:SqlPublishProfilePath for /t:Publish).  This is extremely frustrating as it limits the user's ability to really use MSBuild to its full extent.  I'm not sure how anyone has figured the default ones out that I've seen online, and none of those people give a list of available default Targets.
There's a full Task Reference in the table of contents for Visual Studio's documentation.  Can a similar one be created for Targets?

**Comment by Mikejo5000** [comment]
@seanwhitepc Thanks for the additional context. It may be that the default targets change a lot depending on a wide variety of starting points (what type of project, what template), and also that they change a lot based on updates, and that they are owned by the team that owns the template (so it is somewhat external to MSBuild itself). @rainersigwald for input

**Comment by rainersigwald** [comment]
It's impossible to have a full, complete list, but we could and probably should put a sketch of the [common.targets](https://github.com/microsoft/msbuild/blob/0f3d8e94ac11dd892c0c2fadb28b1a42e0d45fb1/src/Tasks/Microsoft.Common.CurrentVersion.targets) things and their intentions up. That's "documented" in comments there (but those need to be edited quite a bit).

> I'm not sure how anyone has figured the default ones out that I've seen online

Mostly via the difficult mechanism of reading the targets files. (I'm not saying that's a good experience.)

**Comment by mwpowellhtx** [comment]
I concur, this should be clearly enumerated, documented, etc.

**Comment by lostromb** [comment]
I have gone through the Microsoft.Common.CurrentVersion.Targets file and summarized all of the public targets in this pastebin: https://pastebin.com/hgA9Qg1E

For the sake of summarily answering the original question, here are the most common targets defined in the typical project build process:

Build
Rebuild
Clean
Run
Publish
PublishOnly
ResolveReferences
ResolveProjectReferences
ResolveAssemblyReferences
GenerateBindingRedirects
PrepareResources
ResGen
Compile
GenerateManifests
PrepareForRun
CopyFilesToOutputDirectory

And the ones that are intended to be overridden in projects (though keep in mind that the same target can only be overridden once)
BeforeBuild
AfterBuild
BeforeRebuild
AfterRebuild
BeforeResolveReferences
AfterResolveReferences
BeforeResGen
AfterResGen
BeforeCompile
AfterCompile
BeforeClean
AfterClean
BeforePublish
AfterPublish

**Comment by rainersigwald** [comment]
Thanks @lostromb!

Because of the last-override-wins policy, I reccomend _not_ overriding any of those targets; instead `BeforeTargets`/`AfterTargets` them and leave them as stubs. That's different from the original guidance but works more reliably.

**Comment by mwpowellhtx** [comment]
Great start! How about for outer/inner loop targets? i.e. multi-target framework targets?

**Comment by cowlinator** [comment]
Thanks @lostromb .
Can we please put this on a documentation page rather than just in a issue comment?

**Comment by simoncal** [comment]
Per conversation above, the list of common targets was added to the page.
#please-close

**Comment by cowlinator** [comment]
@simoncal , I don't see the list on https://docs.microsoft.com/en-gb/visualstudio/msbuild/msbuild-targets?view=vs-2019 .

Which page are you referring to?

**Comment by mwpowellhtx** [comment]
I too see no updates to the docs.
