### ISSUE TITLE
When using Visual Studio Tools for Unity Codelens, ServiceHub.Host.CLR.x86 is crashed

### ISSUE THREAD

**Issue by CynicalChups** [MicrosoftDocs/visualstudio-docs#6834]
When using the Unity scripts and message functions of CodeLens provided by the Visual Studio Tools for Unity, the memory usage of ServiceHub.Host.CLR.x86 process in Visual Studio increases and it crashes by out of memory. 
After this, all references of CodeLens are broken.

Visual Studio 2019 v16.10.3
Visual Studio Tools for Unity v4.10.3.0
Unity 2021.1.10f1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cef7253f-6433-e163-ada8-e509dbf5807d
* Version Independent ID: adcb47e7-8b56-a3e1-e0b4-4a997f4cfaf6
* Content: [Visual Studio Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/visual-studio-tools-for-unity)
* Content Source: [gamedev/unity/get-started/visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/gamedev/unity/get-started/visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by WilliamAntonRohm** [comment]
@CynicalChups -- thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please raise your concern here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​
