### ISSUE TITLE
Connection to a 64-bit (*.accdb) Database

### ISSUE THREAD

**Issue by Groundsel223** [MicrosoftDocs/visualstudio-docs#6835]
[Enter feedback here]

The connection method described in

https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms?view=vs-2019 

(for connecting a Visual Studio project to an *.accdb database) does not work for our X64 build GUI.  

The *.accdb was created from its *.mdb counterpart with Access 1600.  When I try to connect to said *.accdb, Visual Studio wants the Microsoft.ACE.OLEDB.12.0 provider and says it is not registered on my machine.

The PowerShell command:

"(New-Object system.data.oledb.oledbenumerator).GetElements() | select SOURCES_NAME, SOURCES_DESCRIPTION"

lists both Microsoft.ACE.OLEDB.12.0 and ACE.OLEDB.16.0.  However, the single executable C:\Windows\System32\odbcad32.exe seems to be deemed registered as Microsoft.ACE.OLEDB.16.0.

After extensive googling, I found a reference seeming to suggest that if I open a command window, navigate to C:\Windows\System32 and enter the command

regsvr32 dboledb12.dll regsvr32 dboledba12.dll

then I would register the executable as the desired Microsoft.ACE.OLEDB.12.0 and could then use Visual Studio.

But this fails.  The desired dboledba12.dll  is not there.  So, presumably, it was not in my downloaded accessdatabaseengine_X64.exe.  

If that is the hold-up, can I talk you into putting that dll (back?) in the install packet?  
I have obtained an X64 build of our GUI complete with connection to our 64-bit Archive database.  However, this entailed making the connection first with the old *.mdb; then manually changing the connection string in the relevant *.resx file to connect to the *.accdb with provider Microsoft.ACE.OLEDB.16.0.

Naturally, I would rather do this properly, making the 64-bit connection with Visual Studio rather than manually monkeying with designer maintained files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c5b210-2ecd-fc40-54c9-38a8ba9c7493
* Version Independent ID: a9236354-4965-a214-17f7-746c20de8ec4
* Content: [Connect to data in an Access database - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms?view=vs-2019)
* Content Source: [docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Groundsel223 -- Tom, thank you for your thorough feedback.  We are looking into this issue.

**Comment by Groundsel223** [comment]
Hello William,

Is someone really going to look into this?  If anyone did and found my complaint without merit, I would appreciate hearing that; especially if it came with advice to do something other than what I have done informally.  

I cannot say anything with academic finality because the definitive experiment cannot be made in the absence of dboledba12.dl.  Certainly, there are postings on various web sites suggesting that registration of your 64-bit Access provider as Microsoft.ACE.OLEDB.12.0 can be made with it.  Not by me because I do not have it!  I am guessing that the postings recommending it are old and that since then, this dll has been taken out of your 64-bit install packet.  So, putting it back would seem to solve the problem.

Alternatively, if I could get Visual Studio to solicit Microsoft.ACE.OLEDB.16.0 when I try to connect to an *.accdb database, that would probably work.  What I have managed suggests that this provider can connect to just about any Access database if only Visual Studio would try it.

Cheers!
Tom Stevens

**Comment by WilliamAntonRohm** [comment]
@Groundsel223 -- Tom, thank you for your followup.

@ghogen -- Gordon, is this a documentation issue or a product issue?

**Comment by Groundsel223** [comment]
I was hopeful, this morning, on seeing the posting [https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsg-links.stackoverflow.email%2Fls%2Fclick%3Fupn%3DFhKQFemTFIJzn5ywFPMHvni76Wx7eeSM4UTVwzVAAnBbDAQjD9L7cUtQS2PDHvCxUb8BKpBZGmKlBGRs2vhuEA-3D-3Dhk_j_qk1-2Fpo-2FBTAOrrspGP3AMa91yutft9UHG5A-2BDyrIT0CDjRW1m0uP8IPYkmxhovYRy36S5DDOPUkQfxFXQXQFYj4W2v4Jx09c8ANlcBMGJZ6FlGewytPFrxgsHGGgDGJnACNDvhSK5xVtkowgJ1YnofhCuuxdUrGLE-2FchH5isDKaRW6xGCcOYv02E1Yxjst7U7-2BuWV6fG1-2BneE4zXd56-2FxFmy6jdF94tGwJPY5hEmwBFpn8Hs1S-2B4X-2BPtBu2KBjIG6Kg5XPMrnuChD2FqbOUjYllVtv6iSdKBaptg9Lkzt0T5TWY64Oy6X6V7nO17X5yJPvSmWg6ZKiBvhBUKr0fSIAFG-2FQ-2B97jlSd6CdFd5gvGYoQtAfdoMKZa5OcmypSMglyhpOaxja3OOgKRbl4zf-2BL3M-2B9ak0wNUMDinCQ6rJOrfKxedvK4ruWtD1LOwBAO8T6C2tmUAdewPydIIV-2FdYMs9A1ieA54DOTFDMJ6xc28-2FF2G7dYC3lhabEVbml78f9InxctT8Ff-2FEQM68VIBejK-2BYg-3D-3D&data=04%7C01%7Ctom.stevens%40opg.com%7C7a03dfb6208246d363f408d969e93b38%7C962f21cf93ea449f99bf402e2b2987b2%7C0%7C0%7C637657272705633147%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=n5WvIUQaDdbBO%2Fqfx3udTyvLpCQNWYmcIyq1YzdtMtU%3D&reserved=0](url)  that a new engine identifiable as ACE 12.0 had been placed as the 64-bit engine downloaded.

However, it appears to be same old, same old.  The problem remains that Visual Studio version 2015 and 2019 identify the 64-bit engine as ACE 16.0 and will not try to connect to it in the usual fashion.  And the executable which could talk the system into identifying the downloaded engine - and indirectly Visual Studio - as ACE 12.0 is no longer available.  The engine is perfectly OK.  The problem is getting Visual Studio - I have used VS 2015 and VS 2019 - to "try" and connect to it in the usual way.  Visual Studio simply says that ACE 12.0 is not registered on the local machine.  If it would just so much as try, it would succeed.

I believe my earlier missive has identified the root cause correctly - but was prepared to be proven wrong especially if that assertion were accompanied by advice as to what should be done differently.  It appears, however, that the "decision" (by default) is to leave the status quo (dysfunctional information) in place.  And I shall have to retire with my Mickey Mouse work- around the final answer.

**Comment by ghogen** [comment]
@Groundsel223 You closed this issue, but it doesn't seem to be resolved yet. I'm looking into this issue this month. It seems there is some confusion regarding 32-bit and 64-bit issues that needs to be addressed,

**Comment by ghogen** [comment]
We added a note that explains that you need to match the bitness of Visual Studio with the bitness of Office installation. So, VS 2022 is required to use the data tools features for a 64-bit Access.
