### ISSUE TITLE
Provide a standalone installer, please

### ISSUE THREAD

**Issue by elMestre** [MicrosoftDocs/visualstudio-docs#6836]
This solution sucks. It's overly complicated, and really hard to share with another computer.

Not Having a standalone installer is truly detrimental for rural areas, people in the margins of society and rising countries where regular internet access is not guaranteed.

Not a problem for myself, but it sure is for a considerable percentage of my students.

Please, think about it.

Best regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2019)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by WilliamAntonRohm** [comment]
@elMestre -- Carlos, thank you for your thoughtful feedback.  This repo is solely for documentation issues, and this is product-related.  Please add your concern here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

cc @j-martens, @TerryGLee for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
