### ISSUE TITLE
No information on how to mount to non-root applications

### ISSUE THREAD

**Issue by jgwinner** [MicrosoftDocs/visualstudio-docs#6847]
This is partly a docs issue, but may also be an issue with the wfastcgi app itself. At a minimum, the docs need to change though, so I'll start here.

1. I could not find anywhere to lodge a bug for wfastcgi. The pypi page doesn't have it, and this page doesn't.
2. Regardless of 1, there needs to be clear documentation on how to mount specific routes. For example, in development I may use:
/home
/about
etc. However, unless my Python app is taking over the entire website, I may want to mount this in production as:
/ourapp/home
/ourapp/about
etc.

I don't see an easy way to do this. Most of the Stackoverflow articles discuss ways to modify the Flask application itself, but this is not a DRY principle; it couples deployment to development. It should be easy to take a Flask app that assumes root web and deploy it to any subdirectory on IIS by configuration of the sysadmin (or CI/CD pipeline), not by having to go back to the original developer.

I mean, this implies every app hosted on IIS has to be hardcoded to a particular URL structure.  

I did discover I could manually copy the 'static' folder to the same level at IIS, and let it serve up the static content (better anyway) but the basic problem remains - I have to code in the route information into the app itself, instead of deciding that at hosting time.

Do you have any ideas? I've found stackoverflow questions going back over eight years on similar issues.

Thank you for listening

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed35685d-e409-d962-c450-7297a1f3c003
* Version Independent ID: 224fab0f-fd26-396f-cdd8-921533d2aeba
* Content: [Configure Python web apps for IIS - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/configure-web-apps-for-iis-windows?view=vs-2019)
* Content Source: [docs/python/configure-web-apps-for-iis-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/configure-web-apps-for-iis-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@jgwinner -- thank you for your considered feedback.  You're welcome to report the wfastcgi bug here:
- [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) 

Please consider these resources:
- [Visual Studio on Q&A](https://docs.microsoft.com/en-us/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Reddit](https://www.reddit.com/r/VisualStudio)

@JoshuaPartlow -- please look into this issue.

**Comment by jgwinner** [comment]
Thanks William

It's not a problem with Visual Studio, it's with WFastCGI, so that bug reporting link isn't really the correct spot.

**Comment by jgwinner** [comment]
Ah, my last comment wasn't clear. This is at least a problem with the visual studio docs. WFastCGI does seem to support mounting at non-root locations, but the Visual Studio docs don't tell you how to set that up, and debugging it seems to be nearly impossible.

So while filing a bug may be needed, the biggest issue is documenting how to develop and debug non-root WFastCGI apps.

**Comment by rjmolyneaux** [comment]
Hi @jgwinner! Unfortunately, since the authoring of this doc, wfastcgi has been deprecated. We apologize for the inconvenience and will be updating our documentation to reflect this change. In the meantime, please consider these resources: 

- [Understanding Sites, Applications, and Virtual Directories on IIS 7](https://docs.microsoft.com/en-us/iis/get-started/planning-your-iis-architecture/understanding-sites-applications-and-virtual-directories-on-iis)
- [PyPi WFastCGI](https://pypi.org/project/wfastcgi/)

We appreciate your continued contribution and assistance with improving Microsoft documentation.
