### ISSUE TITLE
Missing semicolon in C# 

### ISSUE THREAD

**Issue by jckz82** [MicrosoftDocs/visualstudio-docs#685]
For the include "using System.Data.SqlClient  " in NewCustomer.cs, the C# code is missing the semicolon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0e2e854-d2d8-8ec2-ae41-beee6636fae3
* Version Independent ID: 2c1c8dae-ea87-e7a0-f0eb-7bc0b775f8d5
* Content: [Create a simple data application by using ADO.NET | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-by-using-adonet#feedback)
* Content Source: [docs/data-tools/create-a-simple-data-application-by-using-adonet.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/data-tools/create-a-simple-data-application-by-using-adonet.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jckz82 thanks for taking the time to let us know; this should be fixed in the next day or so too.
