### ISSUE TITLE
How can I see the AAD group rule that have been configured in the past?

### ISSUE THREAD

**Issue by Emmanuel-Thouraud** [MicrosoftDocs/visualstudio-docs#6850]
How can we see the AAD group rules that been defined? 
Are we able to edit them? to delete them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ac6f4b8-da9d-5b7b-0c18-b6ed1f85433a
* Version Independent ID: 1ac1ddeb-b1a4-e8d3-9abf-0e629796c5ef
* Content: [Assign licenses to groups of users for Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-license-bulk#use-azure-active-directory-groups-to-assign-subscriptions)
* Content Source: [subscriptions/assign-license-bulk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/assign-license-bulk.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **v-evwin**

**Comment by evanwindom** [comment]
@Emmanuel-Thouraud -- Thank you for the question.  I'm not sure I fully understand what you're asking, though.  The limitations for the use of Azure AD groups for assigning subscriptions are listed in the article.  If you're asking about the rules for the Azure AD group itself, those would be determined in Azure rather than in the subscriptions administration portal.

**Comment by Emmanuel-Thouraud** [comment]
In the documentation, there is the process to add a new AD group assignment but I do not see where I can find the list of what was already assigned by using an AD group nor how to change it.

**Comment by evanwindom** [comment]
@Emmanuel-Thouraud -- Thank you for the additional information.  If you have added an Azure AD group, it will be listed in your subscriber list.   If you sort the list alphabetically, it will be sorted in the list according to the name of the group.  You can also sort the list by individual versus groups by clicking on the small "person" icon at the left of the subscriber list.  

If you click on the name of the group, you'll be able to see a list of the members in that group.  You'll notice that you can't make changes to the group contents in the portal, however.  To add or remove people from that list, you need to add or remove them from the Azure AD group.  (To close the list, click on "All subscriptions" located just above the subscriber list.)

To see how to add or remove members in the group, visit this article in the Azure documentation:  https://docs.microsoft.com/azure/active-directory/fundamentals/active-directory-groups-members-azure-portal

Please let me know if you have any further questions.  

Thanks! 
Evan

**Comment by evanwindom** [comment]
#please-close
