### ISSUE TITLE
Not a solution for DPI-awareness

### ISSUE THREAD

**Issue by ggavaghan** [MicrosoftDocs/visualstudio-docs#6859]
Per article https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2019

Turning OFF the screen scaling while working with the Forms Designer is not a solution.  Not only is that nothing more than a work-around (at best), it is impossible to accomplish in many situations, like when working with a VM or over RDP.  And even in those cases where this tactic can be used, I'm expected to repeatedly log-off/log-in each time I need to switch between the Form-Designer and code?  How very smooth and convenient!

This issue has been around for nearly 10 years now (at least 3 versions of VS that I know of, and likely more), and Microsoft still can't figure it out, or maybe they just aren't trying.

The worst part is that being a developer of 35+ years, I KNOW it is a solvable issue.  I mean really, Windows itself can display it all perfectly fine with or without scaling in-use, so we know the logic already exists. the question is, why hasn't it been implemented in Visual Studio?  I realize it's not a cut-and-paste operation, but it is far from impossible.

How about we forgo yet ANOTHER version of Windows (11) and Visual Studio (2022), and just FIX what we already have?  This is exactly why people think of MS as nothing but money-grabbing pieces of ****.  You ALWAYS leave things like this hanging in the breeze, presumably so that you can include the 'fix' as a 'feature' in the next release, if it ever gets fixed at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness in Visual Studio - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2019)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ggavaghan -- thank you for your feedback.  Please add this concern here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by ggavaghan** [comment]
Hi Will,

(Can I call you Will?)

That's the thing, I wasn't trying to submit an issue, but rather just a 
comment/feedback for the page I was on (using the "Feedback for This 
Page" button).  I was simply pointing out that it (a) fails to address a 
large portion of the users having that issue, and (b) it's more of a 
hack than a fix, which you must repeat back-and-forth over and over.  It 
disturbs me that everyone at MS that looked at that page to review & 
approve it said "Yup! Good to go!".

I have no interest in trying to get MS to do anything, seems a little 
too much like 'tilting at windmills' for my taste. Besides, if they 
fixed it, they wouldn't have as many "New Features" to give us in 
VS2022!  Though that's assuming they finally update the VS graphical 
engine to match Windows' (after ~2 decades of failing to do it), sooooo, 
yeah.  Here's me holding my breath.

But thank you for the feedback.  I will be closing this email-thread 
now.  Please feel free to contact us with any further questions or concerns.

G.Gavaghan
Vector IV Software, LLC.
