### ISSUE TITLE
kubernetes-route-as syntax incorrect

### ISSUE THREAD

**Issue by scp-mb** [MicrosoftDocs/visualstudio-docs#6863]
The annotation syntax in the following is incorrect:

> Replicates your chosen service in the cluster in the same namespace and adds a routing.visualstudio.io/route-from=SERVICE_NAME label and routing.visualstudio.io/route-on-header=kubernetes-route-as: GENERATED_NAME annotation.
Configures and starts the routing manager in the same namespace on the Kubernetes cluster. The routing manager uses a label selector to look for the routing.visualstudio.io/route-from=SERVICE_NAME label and routing.visualstudio.io/route-on-header=kubernetes-route-as: GENERATED_NAME annotation when configuring routing in your namespace.

`routing.visualstudio.io/route-on-header=kubernetes-route-as: GENERATED_NAME`
Should be:
`routing.visualstudio.io/route-on-header=kubernetes-route-as=GENERATED_NAME`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: baf294f2-e31d-f580-e16f-64a26221dfcf
* Version Independent ID: 3030e5bf-42be-82ae-2826-1869d7cd7ef6
* Content: [How Bridge to Kubernetes works - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/containers/overview-bridge-to-kubernetes?view=vs-2019)
* Content Source: [docs/containers/overview-bridge-to-kubernetes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/overview-bridge-to-kubernetes.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review this change in [private PR 8424](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8424).
