### ISSUE TITLE
Typescript tests tutorial is vague and is not helpful enough to beginners.

### ISSUE THREAD

**Issue by anddrzejb** [MicrosoftDocs/visualstudio-docs#6868]
I was trying to use the docs to see how the testing works, but unfortunately, I failed.
My first issue was with the snippet in [Write unit tests for ASP.NET Core](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/unit-testing-javascript-with-visual-studio.md#write-unit-tests-for-aspnet-core) point 8:
```ts
function getData(value) {
   if (value > 1) {
      return true;
   }
}
 
module.exports = getData;
```
intellisense was complaining: 
![image](https://user-images.githubusercontent.com/6518006/125923269-aea917c9-7921-4b96-a44b-df432255930e.png)

In my research I found out that I need to add to the `package.json` in the `dependencies` section this entry: `@types/node`. I could not find this information anywhere in the docs.

But after that, test discovery returned an error: `Test discovery error: ReferenceError: jQuery is not defined`. Mind that the page is running fine, and `jQuery` is properly discovered both in the page as by the intellisense. It seems to me that only tests cannot see the jquery. When I moved the tested function to `app.ts` and switched the `required` to point to `app.js`, the test was discovered and run successfully. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32738a06-835b-5bd5-7a6c-942c681aca97
* Version Independent ID: e715d12c-a4aa-eec3-c05f-1ff6243d209b
* Content: [Unit testing JavaScript and TypeScript - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2019&tabs=mocha#write-unit-tests-for-aspnet-core)
* Content Source: [docs/javascript/unit-testing-javascript-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/unit-testing-javascript-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@anddrzejb -- Andrzej, thank you for your feedback and researches.

@Mikejo5000 -- Mike, please look into this issue.
