### ISSUE TITLE
Better and easier work-around for side-stepping VS screen-scaling issue

### ISSUE THREAD

**Issue by ggavaghan** [MicrosoftDocs/visualstudio-docs#6870]
This work-around should work for most users, including those running VS in a VM.  I am not sure if this works, or can be modified to work, for RDP users connecting to remote bare-metal PCs.  It has the following benefits over the hack provided by MS (found here https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2019):

- It eliminates the need to restart VS when switching from designing a form to writing code.
- It will persist for as long as VS remains running
- It works for users developing on a local (bare-metal) PC as well as local (and remote?) VMs

### Hardware used:
- HOST: TR2970WX 24-core w/ 64GB RAM, w/ 1x 2080-TI and 1x RX 560
- GUEST: Provisioned with 8-processors and 8GB RAM
- MONITORS: 1x 32" 4K (primary) at 150% scaling on the 2080Ti, and 2x 24" HD at 100% scaling on the RX560

Note: The HOST also has VS installed, and was used to test the bare-metal solution.

### Software used:
- HOST: Win 10 x64 v10.0.19041, Hyper-V v10.0.19041.1
- GUEST: Win 10 x64 v10.0.19042, with Visual Studio 2015 v14.0.25431.01 update 3

The primary 4K monitor was the focus here since it is the primary display and is using 150% scaling.

While this was only tested using VS2015, it should work for 2017 and possibly 2019, but I do not use either of those because 2017 was, well if you've used it you know, and 2019 was designed for MS-Java developers exclusively, though most people just call it C#.

### The work-around
For VS running on a VM:

1. Be sure the VM is running, but you are NOT connected to it
2. On the HOST, set screen-scaling to 100%
3. Connect to the VM, and launch VS
4. Return to the HOST and set Screen-scaling to the desired scale (eg 150%)
5. Go back to the VM and load your project/solution

For VS running on a bare-metal PC;

1. Set screen-scaling to 100%
2. Launch VS
3. Set Screen-scaling to 150%
4. Load your project

When you go back to VS and you load your project/solution, you will see that the forms are enlarged and displayed proportionately, and the text is also scaled, exactly as you would expect it to be (and exactly how it SHOULD be).

### Before and After pictures
This image shows what the VS GUI looks like by default with scaling at 150%:
![VS-IncorrectlyScaled](https://user-images.githubusercontent.com/39640802/125988502-b99d4e6b-b954-4ba9-b6aa-c9c7e50d658b.jpg)

This image shows what the VS GUI looks like with scaling at 150% after applying this work-around:
![VS-CorrectlyScaled](https://user-images.githubusercontent.com/39640802/125988498-887fb2ef-5907-4516-b5f3-83e3ecb9ecd9.jpg)

The down side is that **_YOU NEED TO DO THIS EACH TIME YOU LAUNCH VISUAL STUDIO_**.  While still a bit tedious, it does not require you to constantly logout/login from/to VS each time you want to switch from designing forms to writing code.  And if you only close the Project/solution, but leave VS running, you can avoid unnecessary repeats of this procedure.

In addition, as you can see from the images, this work-around does produce slightly blurred results (in both the form-designer and code windows), but I consider this a very minor inconvenience relative to the issue it resolves.

The most surprising thing in all of this is that MS claims VS **_can't do this_** (display forms and text scaled correctly at the same time when scaling <> 100%), because it is not DPI-aware.  That cannot be entirely accurate else this work-around would not be possible.  I'm not arguing that VS is in fact DPI-aware, I'm saying the claim VS can't display forms correctly with screen-scaling ON is patently incorrect, which this work-around clearly demonstrates.  

Since it all comes down to the scaling in effect when you launch VS, I suggest MS starts looking into the initialization code for VS to find the actual and real underlaying cause of this (at least) 6-year old issue.  (PS: I do contract work, so if MS needs a hand, I'd be happy to provide them with my current rates).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness in Visual Studio - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2019)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ggavaghan -- thank you for your researches.  We are investigating this issue.

Related to #6859

**Comment by WilliamAntonRohm** [comment]
@ggavaghan -- this seems more like a product issue than a documentation issue.  Please add your concerns here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 

We'll close this issue now with our thanks to you for taking the time to outline a solution that others might find useful, too.
