### ISSUE TITLE
Outdated page

### ISSUE THREAD

**Issue by glibg10b** [MicrosoftDocs/visualstudio-docs#6872]
I believe this page is outdated. VS Community 2019 doesn't have these options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2019)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/install-architecture-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
The previous page in the docs details which tool is supported in which edition of VS: https://docs.microsoft.com/en-us/visualstudio/modeling/analyze-and-model-your-architecture?view=vs-2019#edition-support-for-architecture-and-modeling-tools

**Comment by WilliamAntonRohm** [comment]
@glibg10b -- thank you for your feedback.

@mgoertz-msft -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
