### ISSUE TITLE
[New Topic] Develop and Debug with Docker in Visual Studio

### ISSUE THREAD

**Issue by JRAlexander** [MicrosoftDocs/visualstudio-docs#688]
# Develop and Debug with Docker in Visual Studio

This was proposed as part of the Docker articles last year and was filed over at the [dotnet/docs repo]( https://github.com/dotnet/docs/issues/2692). Refiling issue here.

1. Table of Contents Location

   - TBD

2. Abstract
   Learn how to debug with Docker in Visual Studio.

3. Outline
    - [ ] Have Docker 4 windows installed
    - [ ] Screenshots of VS file new project.
    - [ ] Note that currently Adding Docker support only works if there are no Docker artifacts already in your project.

4. Reviewer Request

**Comment by gewarren** [comment]
@JRAlexander thanks! @ghogen does this fall under your new area of ownership?

**Comment by JRAlexander** [comment]
@gewarren Sure! Let me know if you have any questions.

**Comment by StingyJack** [comment]
I think this also needs a section for when you want to publish the thing you have been debugging to somewhere else. 

And please remember many of your customers aren't using .net core, can't/won't use EF, and could be using an MVC approach, but not necessarily asp.net's flavor of MVC.

**Comment by gewarren** [comment]
@JRAlexander @ghogen Is this request covered by these topics that are dated September 2018?

- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/docker/visual-studio-tools-for-docker?view=aspnetcore-2.2
- https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker
- https://docs.microsoft.com/en-us/visualstudio/docker/vs-azure-tools-docker-edit-and-refresh?view=vs-2017

**Comment by JRAlexander** [comment]
@Thraka - thoughts?

**Comment by ghogen** [comment]
That's a partial solution, but I have a PR that moves us forward a little more, and more work items planned in this space.   @JRAlexander  I think we can close the issue.  We can discuss the ongoing work at your convenience.

**Comment by JRAlexander** [comment]
@ghogen - I agree with you but I'm on a new team and @thraka is the Lead for that now. His call. :)

**Comment by Thraka** [comment]
Yeah this seems to be covered in the VS docs. 

Would it be a more complete solution in visual studio if you all did a whole Create, debug, deploy tutorial?

**Comment by ghogen** [comment]
Closing this issue now as the main problem appears to be solved and lots of content has either already been added or plans exist.
