### ISSUE TITLE
documentation 'add connection' with regards to MS Access at odds with reality

### ISSUE THREAD

**Issue by sandokanfirst** [MicrosoftDocs/visualstudio-docs#6895]
[Enter feedback here]
The documentation on connecting to MS Access doesn't fit with what actually happens on my system, with an Access 2013 (accdb) database) and Visual Studio 2019 on Windows 10, 64 bit. When I try to add a Datasource and get to the Add Connection screen this doesn't show a 'Browse Database' button and path. The only thing featured on the Add Connection screen is the connection string.
![addc](https://user-images.githubusercontent.com/36963445/126866271-d555bb52-13c4-4b32-89ae-6660e80af3c2.jpg)

To my surprise, the Test Connection button replies "Test connection succeeded" when pressed.
(While this should be totally irrelevant, I have installed Office and most other applications on D:\. Apparently this is the reason I cannot import or export Access databases in MSSMS [Microsoft Sequel Server Management Studio] if my research is correct. While Microsoft talks a lot of unit testing and isolation, and preaches avoiding hard-coded paths, apparently the development process at MS in practice is rather quick and dirty).

Edit 26-07-2021:
So I just encountered https://developercommunity.visualstudio.com/t/unable-to-connect-2016-accdb-to-2019-visual-studio/1433183
This basically and ironically says this is NOT a bug. I think this is a bug by all means and I am of the opinion that either this functionality should be corrected OR the documentation or both. How many more poor souls must spend hours to find out how access to MS Access is supposed to work? I'd like to point out that my problem is different in that I don't get the error “Microsoft.ACE.OLEDB.12.0 provider is not registered on the local machine.” I'm still testing the solution discussed in that thread.
There are too many inconsisitencies and discrepancies here and I think these should be addressed in the documentation.
First off, one needs to have a database engine installed, apparently. This database engine is called **database engine** except for Office 2013 where you apparently have to download the **runtime** instead of the database engine. There is no mention of this prerequisite of having a database engine installed on this website.
Secondly, apparently because Visual Studio is 32 bits, the database engine needs to be 32 bits too. This means that if you have Office 64 bits installed you can't access the MS Access database from Visual Studio. I suppose that means you have to reinstall Office 32 bits even if you have a 64 bit machine...
So one is basically caught between a rock and a hard place. As Microsoft refuses to transition Visual Studio to 64 bits wel will have to deal with a legacy situation for years to come. Which forces developers and users to spend many days to find ways to get their solutions to work, probably only to find out it isn't possible at all in the end.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c5b210-2ecd-fc40-54c9-38a8ba9c7493
* Version Independent ID: a9236354-4965-a214-17f7-746c20de8ec4
* Content: [Connect to data in an Access database - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms?view=vs-2019)
* Content Source: [docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@sandokanfirst -- thank you for your considered feedback.

@ghogen -- please look into this issue.

**Comment by ghogen** [comment]
We added a note to this article recently that says that VS 2022 is required to use the 64-bit Access database engine.
