### ISSUE TITLE
Should this page include "TargetFramework" property?

### ISSUE THREAD

**Issue by maroonedsia** [MicrosoftDocs/visualstudio-docs#6902]
[Enter feedback here]
I am trying hard to to find all the built-in parameters that I can use in a .csproj file for MsBuild. 
The best page I found is this one, and I wonder why it doesn't include the very famous '$(TargetFramework)' property? 

So, if TargetFramework is missed, could you please add it to this page, or if it doesn't belong here, could you please point me to the page that includes it? 

Thank you so much. 
Cheers,
Sia 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Thanks for the issue report. The TargetFramework property is documented here, along with a few other properties that apply to SDK projects:
https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props

It could well be added to this page, perhaps along with others in that category.

**Comment by maroonedsia** [comment]
Thank you so much for the update.

Regards,
Siavash Mortazavi
