### ISSUE TITLE
Documentation about ExitCode is misleading

### ISSUE THREAD

**Issue by DerekSMorin** [MicrosoftDocs/visualstudio-docs#6905]
[Enter feedback here]

MSBUILD Exec task can return -1 if something with the word "Error" is written to standard error.
There is a regex that is used internally.
It was very confusing to figure out why a given task was returning -1.

https://stackoverflow.com/questions/48117302/does-the-msbuild-exec-task-search-stdout-for-the-string-error?rq=1

The workaround is to use:

IgnoreStandardErrorWarningFormat="true" 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb479ee7-d34c-dd5d-6843-4abdec6c3894
* Version Independent ID: 40cd6644-b061-335e-7bd4-6beede753c5d
* Content: [Exec Task - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task?view=vs-2019)
* Content Source: [docs/msbuild/exec-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/exec-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@DerekSMorin Added a clarification to the article. It should appear soon.
