### ISSUE TITLE
Out of Date or Inaccurate Guidelines

### ISSUE THREAD

**Issue by nate-buck** [MicrosoftDocs/visualstudio-docs#6912]
> In Solution Explorer, right-click on the References or Dependencies node and choose Add Reference. You can also right-click on the project node and select Add > Reference.

There is no 'Add > Reference' option. The list only contains 'Add Project Reference', 'Add Shared Project Reference', 'Add COM Reference'.

I'm using Visual Studio 2019 Enterprise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284369-f16f-2748-2a55-8cd24a06b940
* Version Independent ID: f7b0c577-b584-98dc-90a2-4efcf095b35d
* Content: [Add references in the Reference Manager - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2019)
* Content Source: [docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@nate-buck You're absolutely right; we've updated this section of the page per your input. We'll close this issue now, with our thanks to you for helping to improve the documentation!
