### ISSUE TITLE
Worked like charm.

### ISSUE THREAD

**Issue by Ganeshmakwana** [MicrosoftDocs/visualstudio-docs#6914]
Worked like a charm.
Good work
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db7f9ca8-40ce-6b6d-15df-bbb3b6829430
* Version Independent ID: 3dd10fed-b3d3-269c-623e-00031a81ed83
* Content: [Quickstart: Create a Python web app with Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-python?view=vs-2019)
* Content Source: [docs/ide/quickstart-python.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-python.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by WilliamAntonRohm** [comment]
@Ganeshmakwana -- Ganesh, thank you for your kind words.
