### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by martijnhoekstra** [MicrosoftDocs/visualstudio-docs#692]
The link to "Basic Project" in "For an example of an implementation of the IVsProjectFactory interface, see PrjFac.cpp that is contained in the Basic Project sample directory." is dead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36255b00-b16d-cbc8-7932-d3b7cca8ab56
* Version Independent ID: b209ff6c-76e6-072f-e34b-78eaa2ccca79
* Content: [Creating Project Instances By Using Project Factories - Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/creating-project-instances-by-using-project-factories#feedback)
* Content Source: [docs/extensibility/internals/creating-project-instances-by-using-project-factories.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/internals/creating-project-instances-by-using-project-factories.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by jotasprout** [comment]
I got this!

**Comment by gewarren** [comment]
Issue is resolved in pull request #1748.
