### ISSUE TITLE
Path to InstallCleanup.exe is wrong

### ISSUE THREAD

**Issue by MarkLTX** [MicrosoftDocs/visualstudio-docs#6925]
The doc on this page says the path is...
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\layout\InstallCleanup.exe"

However on my installation of VS2019, the path is
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\InstallCleanup.exe"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2019)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @j-martens
* Microsoft Alias: **jmartens**

**Comment by j-martens** [comment]
#reassign:@anandmeg

**Comment by anandmeg** [comment]
@MarkLTX, thank you for your feedback and your you help in improving our docs!
We have updated the doc -  [Remove Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2019).
