### ISSUE TITLE
GetPathOfFileAbove has an undocumented second argument

### ISSUE THREAD

**Issue by mcturn** [MicrosoftDocs/visualstudio-docs#6932]
[Customize Your Build > Directory.Build.props and Directory.Build.targets > Use case: multi-level merging](https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2019#use-case-multi-level-merging) cites an example that invokes `GetPathOfFileAbove` with two arguments:

> ``<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />``

As noted on [a comment on MSBuild Issue 2456](https://github.com/dotnet/msbuild/issues/2456#issuecomment-489047636), the second argument is undocumented.

I tracked down [the source code for this function](https://github.com/dotnet/msbuild/blob/9bcc06cbe19ae2482ab18eab90a82fd079b26897/src/Build/Evaluation/IntrinsicFunctions.cs#L324), which explains the two arguments (although lines 326 and 327 appear to be transposed, corrected here for clarity):

```csharp
/// <summary>
/// Searches upward for the specified file, beginning in the specified <see cref="IElementLocation"/>.
/// </summary>
/// <param name="file">The name of the file to search for.</param>
/// <param name="startingDirectory">An optional directory to start the search in.  The default location is the directory
/// of the file containing the property function.</param>
/// <param name="fileSystem">The file system abstraction to use that implements file system operations</param>
/// <returns>The full path of the file if it is found, otherwise an empty string.</returns>
internal static string GetPathOfFileAbove(string file, string startingDirectory, IFileSystem fileSystem)
```

While we're in the area, the summary description for the `GetDirectoryNameOfFileAbove` function is misleading, referring to "the current directory" as if it were not a parameter.

My proposed changes are on branch https://github.com/mcturn/visualstudio-docs/tree/mcturn-patch-1

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019#msbuild-getpathoffileabove)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@mcturn -- Michael, thank you for your feedback and creating that pull request.

@ghogen -- please review his [PR 6933](https://github.com/MicrosoftDocs/visualstudio-docs/pull/6933).
