### ISSUE TITLE
MSBuild item functions documentation is missing some functions

### ISSUE THREAD

**Issue by alexrp** [MicrosoftDocs/visualstudio-docs#6940]
This page seems to be missing some item functions that exist in MSBuild. A few I noticed (but there may be more):

* `Exists`
* `Combine`
* `GetPathsOfAllDirectoriesAbove`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62ddc739-9c79-2dda-20b4-09aa26d348d1
* Version Independent ID: 21d74f53-5b13-5efb-704e-27e28d6dc586
* Content: [Item Functions - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/item-functions?view=vs-2019)
* Content Source: [docs/msbuild/item-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/item-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by KalleOlaviNiemitalo** [comment]
`Exists`, `Combine`, and `GetPathsOfAllDirectoriesAbove` were implemented in <https://github.com/dotnet/msbuild/pull/4231>, which includes brief descriptions of each.

In the future documentation of `Exists`, it might be good to note that the same name is also used in other syntax:

- `Condition="Exists('path')"` in [MSBuild conditions](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2019)
- `$([System.IO.File]::Exists("path"))` in [Static property functions](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2019#static-property-functions)

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for your well-researched followup.

**Comment by KalleOlaviNiemitalo** [comment]
Why was this issue closed? The live version of the item functions documentation still incorrectly claims:

> The functions Exists and HasTrailingSlash are not item functions.

Which makes this a doc bug rather than a doc feature request.

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for your followup.

@ghogen -- please look into this remaining potential documentation issue.

**Comment by ghogen** [comment]
@KalleOlaviNiemitalo 
Thanks. I've submitted a new PR that addresses that old information.
