### ISSUE TITLE
Edit and Continue for ASP.NET 5 is not supported?

### ISSUE THREAD

**Issue by billti** [MicrosoftDocs/visualstudio-docs#6943]
The page states "Unsupported apps and platforms include **ASP.NET 5**, Silverlight 5, and Windows 8.1.", however the feedback issue at https://developercommunity.visualstudio.com/t/edit-and-continue-not-working-with-aspnet/414645 says it does/was fixed, as well as issue https://github.com/dotnet/aspnetcore/issues/7390

There is confusingly a bunch of work in the ASP.NET 6 milestone to implement edit and continue and hot reload, so maybe support is partial? Anyways, I just tried it with ASP.NET 5 and latest VS 2019 and it seemed to work fine.

It would be great to clarify/correct in the docs if Edit and Continue is actually supported (at least partially) for ASP.NET 5. (CC @DamianEdwards. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0b8848-c2af-28e9-28bf-761d1cdf3d6d
* Version Independent ID: 7cc1bef7-ef0c-5c62-2b5f-45910764ba80
* Content: [Supported Code Changes (C# and Visual Basic) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-csharp?view=vs-2019)
* Content Source: [docs/debugger/supported-code-changes-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/supported-code-changes-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by DamianEdwards** [comment]
Yes Edit and Continue **does** work in ASP.NET Core 5, but only for C# (.cs) files. It **does not** work for Razor (.cshtml or .razor) files. That support is coming in .NET 6.
