### ISSUE TITLE
Issue with Prerequisites

### ISSUE THREAD

**Issue by FrankAtHexagon** [MicrosoftDocs/visualstudio-docs#6949]
The _Prerequisites_ section mentions the following:
> Visual Studio 2019 v16.9 Preview 1 or later versions with the .NET Core Debugging with WSL 2 optional component.
The optional component is included by default with the .NET Core cross-platform or the ASP.NET and web development workloads. You must install one or both of these workloads.

The .NET Core Debugging with WSL 2 component is _not_ included by default with the mentioned workloads. In addition, it's called .NET Debugging with WSL 2, not .NET Core Debugging with WSL 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a793d6b-b669-b973-9370-fe0fc5bb5c98
* Version Independent ID: 15f08932-d7f0-fc85-5d3c-83ab56856985
* Content: [Debug .NET apps in Linux using WSL 2 - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-dotnet-core-in-wsl-2?view=vs-2019)
* Content Source: [docs/debugger/debug-dotnet-core-in-wsl-2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/debug-dotnet-core-in-wsl-2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@FrankAtHexagon Thanks for bringing this up! I'll take a look at it.

**Comment by FrankAtHexagon** [comment]
Thank you for fixing this.

**Comment by Mikejo5000** [comment]
@FrankAtHexagon Sure, thanks for bringing it up!
