### ISSUE TITLE
Feature Request : Word Wrap in Visual Studio for Mac

### ISSUE THREAD

**Issue by SquidwardHill** [MicrosoftDocs/visualstudio-docs#695]
Would it be possible to build in an option to wrap text in VS for Mac? It would help make code more legible.

**Comment by asb3993** [comment]
Hey @SquidwardHill, Thanks for taking the time to provide feedback! This is an great feature idea. To ensure that it gets into the hands of the product team, I'd recommend adding your voice to [this](https://visualstudio.uservoice.com/forums/563332-visual-studio-for-mac/suggestions/17166137-text-wrapping) uservoice.

**Comment by asb3993** [comment]
I'm closing this issue for now, but please do not hesitate to add a comment or re-open if necessary. I'll be sure to update the docs when we get this feature!
