### ISSUE TITLE
how do I know what is taken a shortcut  

### ISSUE THREAD

**Issue by Ribosome2** [MicrosoftDocs/visualstudio-docs#6960]
[Enter feedback here]
when I type Ctrl+E ,VisualStudio wait for second key chord ,how to I know what command is waiting , I just want to use Ctrl+E to do perform action, the main problem is I cannot find how to search for shortcuts instead of commands 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5859be-5f6e-4354-a0b0-c14ffc047d23
* Version Independent ID: d2033d27-92b9-6f70-286a-cefb0a58b15a
* Content: [Identify and customize keyboard shortcuts - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Ribosome2 -- KyleLin, thank you for your feedback.  Please see this article:
 -[Default keyboard shortcuts in Visual Studio](https://docs.microsoft.com/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Ribosome2** [comment]
I already read that arctible before,Did not solve my problem, Still need a way to conveniently search for what is taking the shortcut instead of browser throngh the default keyboard scheme, I set my custom shortcut , doesn't work, just frustrating !


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MicrosoftDocs/visualstudio-docs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月13日(星期五) 凌晨2:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MicrosoftDocs/visualstudio-docs] how do I know what is taken a shortcut   (#6960)





 
@Ribosome2 -- KyleLin, thank you for your feedback.  Please see this article:
 -Default keyboard shortcuts in Visual Studio
 
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WilliamAntonRohm** [comment]
@Ribosome2 -- KyleLin, thank you for your followup.  This seems more like a product issue than documentation.  Please add your suggestion here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
