### ISSUE TITLE
repos

### ISSUE THREAD

**Issue by meressekyalwe** [MicrosoftDocs/visualstudio-docs#6968]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5c36c-d8ef-6b2d-2c62-5243d1ac2ce1
* Version Independent ID: 91c57e20-c75c-3c8d-e31f-727fa1e2af29
* Content: [Repair Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2019)
* Content Source: [docs/install/repair-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/repair-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@meressekyalwe -- Kyalwe, thank you for your feedback.  Please clarify the nature of your task or issue.  Meanwhile, consider these resources:
- If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 
- We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 
- Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by meressekyalwe** [comment]
thank you very much I solved the problem ))
