### ISSUE TITLE
ProvideLanguageCodeExpansionAttribute has wrong arguments.

### ISSUE THREAD

**Issue by nils-a** [MicrosoftDocs/visualstudio-docs#6973]
Looking at https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-implementing-code-snippets?view=vs-2019#to-register-code-snippets-for-a-specific-guid, step 8 is:

> Add the ProvideLanguageCodeExpansionAttribute to the TestCompletionHandler class. This attribute can be added to any public or internal (non-static) class in the project. (You may have to add a using directive for the Microsoft.VisualStudio.Shell namespace.)
> ```
> [ProvideLanguageCodeExpansion(
>     SnippetUtilities.LanguageServiceGuidStr,
>     "TestSnippets", //the language name
>     0,              //the resource id of the language
>     "TestSnippets", //the language ID used in the .snippet files
>     @"%InstallRoot%\TestSnippets\Snippets\%LCID%\TestSnippets.xml", //the path of the index file
>     SearchPaths = @"%InstallRoot%\TestSnippets\Snippets\%LCID%\",
>     ForceCreateDirs = @"%InstallRoot%\TestSnippets\Snippets\%LCID%\")]
> internal class TestCompletionCommandHandler : IOleCommandTarget
> ```

However, the first parameter of [`ProvideLanguageCodeExpansion`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.providelanguagecodeexpansionattribute) seems to be of type `Type` (and represents the type of the language service) instead of type `string`.

**Comment by nils-a** [comment]
I believe this feedback is still actionable.

**Comment by WilliamAntonRohm** [comment]
@nils-a -- Nils, thank you for your follow-up.

**Comment by nils-a** [comment]
I believe this feedback is still actionable.

**Comment by nils-a** [comment]
I believe this feedback is still actionable.
