### ISSUE TITLE
Please clarify which version of the bootstrapper should be used when updating the layout 

### ISSUE THREAD

**Issue by sryabkov** [MicrosoftDocs/visualstudio-docs#698]
When we originally create a layout, we download a bootstrapper (e.g. `vs_enterprise.exe`) from [https://www.visualstudio.com/downloads/](https://www.visualstudio.com/downloads/) and then run it with the `-layout` parameter. So, let's say we downloaded the bootstrapper after v15.6 was released and we saved it to c:\tmp\vs2017\15.6. Slightly modifying your example, we would run:
```
 c:\tmp\vs2017\15.6\vs_enterprise.exe --layout c:\VS2017Layout --add Microsoft.VisualStudio.Workload.ManagedDesktop --lang en-US
```
After the layout operation is over, c:\tmp\vs2017\15.6 and c:\VS2017Layout will contain the identical copies of  `vs_enterprise.exe`.

Now, at some point in future, let's say when v 15.7 is released, we want to update the layout. Should we download the bootstrapper again and run the downloaded version of the bootstrapper or should we run the bootstrapper from the layout folder?

In other words, let's say we downloaded the bootstrapper _again_ after v15.7 was released and we saved it to c:\tmp\vs2017\15.7

Should we run 
```
 c:\tmp\vs2017\15.7\vs_enterprise.exe --layout c:\VS2017Layout
```

or 
```
c:\VS2017Layout\vs_enterprise.exe --layout c:\VS2017Layout
```
Does it matter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc51a257-b7a9-4660-7e12-88cdfcd9cd53
* Version Independent ID: dad2fd97-7244-6802-e853-5d5974838996
* Content: [Update a network-based installation of Visual Studio - Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio)
* Content Source: [docs/install/update-a-network-installation-of-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/update-a-network-installation-of-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @timsneath
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@sryabkov Thanks for your input. We're looking in to this.

**Comment by SelmaI** [comment]
@sryabkov, you do not need the new version of the bootstrapper. 
Both commands should update the layout with 15.7 packages when they're available. 

Thanks,
Selma

**Comment by sryabkov** [comment]
@TerryGLee Thank you for your response and clarification
