### ISSUE TITLE
typo: IntermediateOutputPath does not start with '/'

### ISSUE THREAD

**Issue by hokb** [MicrosoftDocs/visualstudio-docs#6987]
The example path provided for IntermediateOutputPath reads: '/obj/Debug/'. Hoewever, in real there is no leading slash in the value at runtime. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9dbdd881-dc08-3ff7-d7f4-f9fa9373ea9b
* Version Independent ID: 23ee268e-c6fa-9420-3a8d-a52f81104da7
* Content: [Common MSBuild Project Properties - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019)
* Content Source: [docs/msbuild/common-msbuild-project-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/common-msbuild-project-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review this update in [private PR 8579](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8579).

**Comment by ghogen** [comment]
@WilliamAntonRohm @hokb Looks good, thanks!
