### ISSUE TITLE
Migration guide missing a step, does not currently resolve CA0507 which links to this page

### ISSUE THREAD

**Issue by PikeUK** [MicrosoftDocs/visualstudio-docs#6988]
The CA0507 warning links to this page.

> CA0507	Post-build Code Analysis (FxCopCmd.exe) has been deprecated in favor of FxCop analyzers, which run during build. Refer to https://aka.ms/fxcopanalyzers to migrate to FxCop analyzers.

However following the migration guide on this page will not resolve CA0507. In addition to installing NetAnalyzers as suggested, you also need to remove the following from your project file (or turn off "Run on build" in Properties->Code Analysis):

`<RunCodeAnalysis>true</RunCodeAnalysis>`

This information should be part of the migration guide.

I found the above information here:

https://developercommunity.visualstudio.com/t/several-ca0507-run-code-analysis-warnings-after-in/480652#T-N482101-N482090

Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72cc081c-b26c-cea8-a551-16a9f01dd077
* Version Independent ID: acf5c283-76c3-ae95-5f2b-d0282a8d05d1
* Content: [Migrate from FxCop analyzers to .NET analyzers - Visual Studio (Windows)](https://docs.microsoft.com/en-gb/visualstudio/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers?view=vs-2019)
* Content Source: [docs/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/migrate-from-fxcop-analyzers-to-net-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@PikeUK Thanks, I will look into this issue.

**Comment by Mikejo5000** [comment]
Fix should be live by EOD, 9/17/21. Thanks!
