### ISSUE TITLE
Outdated Page

### ISSUE THREAD

**Issue by Johnrobmiller** [MicrosoftDocs/visualstudio-docs#6989]
This page is outdated.  Please go over it and edit as needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35176f2-ca94-7bb8-08a5-9e415d364ef3
* Version Independent ID: a9f184a6-78b9-315b-4a02-1c93bd4c3940
* Content: [Getting Started with Visual Studio Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity)
* Content Source: [gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by therealjohn** [comment]
Thanks @Johnrobmiller. I'm working on updating these docs and will publish them soon. If there is anything specific that you noticed, please let me know so I can double-check that I've addressed it. Thanks!

**Comment by therealjohn** [comment]
We've published the updates. Thanks!

@WilliamAntonRohm This issue can be closed.

**Comment by WilliamAntonRohm** [comment]
#please-close
