### ISSUE TITLE
Broken Links [ 404 ] 

### ISSUE THREAD

**Issue by Bob123abc** [MicrosoftDocs/visualstudio-docs#699]
Unicode in Microsoft Foundation Class Library link Gives 404 in Edge Browser 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb0873f-6486-57fb-93db-1bc662cbbfca
* Version Independent ID: 91f46431-09ff-2f01-bd20-e8e1a9490a0b
* Content: [Project and Solution File Types - Visual Studio | Microsoft Docs](https://docs.microsoft.com/en-us/visualstudio/ide/reference/project-and-solution-file-types)
* Content Source: [docs/ide/reference/project-and-solution-file-types.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/reference/project-and-solution-file-types.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by Bob123abc** [comment]
https://docs.microsoft.com/en-us/cpp/mfc/unicode-in-mfc 
May need to point to -> 
https://docs.microsoft.com/en-us/cpp/text/unicode-and-mbcs

**Comment by gewarren** [comment]
@Bob123abc thanks for letting us know. I will fix it.
