### ISSUE TITLE
Broken links for xml documentation

### ISSUE THREAD

**Issue by JackGrinningCat** [MicrosoftDocs/visualstudio-docs#70]
Hi, 

I was looking up some examples and hoped that the new 2017 version had anything new, but reaching this point, the links were broken. I didn't found the right link location to correct, some simple approaches din't worked out, So... here is the site url

https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/supplying-xml-code-comments.md

Kind regards

**Comment by kempb** [comment]
Hello,
When I go to the live topic for the link you supplied (Supplying XML Code Comments - https://docs.microsoft.com/en-us/visualstudio/ide/supplying-xml-code-comments), the links work okay for me. Are they still broken for you?
