### ISSUE TITLE
Unit test refactoring suggestions actually break the purpose of the test.

### ISSUE THREAD

**Issue by Bradbev** [MicrosoftDocs/visualstudio-docs#7006]
The refactoring recommendations (change from Assert.ThrowsException to try/catch) break the original purpose of the test.  If that refactoring is performed, then the bank code is free to stop asserting, and the test will not catch it.
Better would be 
`var e = Assert.ThrowsException<System.ArgumentOutOfRangeException>(() => account.Debit(debitAmount)); StringAssert.Contains(e.Message, "Amount exceeds balance");`
This could be very confusing for new coders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* Content: [C# unit test tutorial - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2019)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Bradbev Thanks for the feedback. Looking at this. It appears that the bug in the refactoring section is fixed in the next section, "Retest, rewrite, and reanalyze". When the bug is fixed, the test fails if the expected exception is not thrown. Or are you seeing something different?

**Comment by Bradbev** [comment]
Goodness - I totally missed that it was fixed in the next section.  Sorry
for wasting time!

**Comment by Mikejo5000** [comment]
I appreciate the confirmation! Thanks!
