### ISSUE TITLE
PRF0025: No data was collected

### ISSUE THREAD

**Issue by paddyboyd** [MicrosoftDocs/visualstudio-docs#702]
I am encountering this issue, but it does not match the description of the problem as noted above (the profiling tools in VS2015 worked without issue, however this problem started occuring when using VS2017).

The documentation notes that 'This problem can be caused by several issues: ' and then goes on to describe a single scenario - was something missed here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a9922d2-95be-5875-618c-1016302ce421
* Version Independent ID: 77c5829d-0d50-e6cc-3708-530e768fe760
* Content: [Troubleshooting Performance Tools Issues - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/profiling/troubleshooting-performance-tools-issues)
* Content Source: [docs/profiling/troubleshooting-performance-tools-issues.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/profiling/troubleshooting-performance-tools-issues.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@paddyboyd I wonder if there is insufficient CPU activity? I saw this old post:
https://blogs.msdn.microsoft.com/profiler/2010/01/14/prf0025-no-data-was-collected-why-is-that/

**Comment by paddyboyd** [comment]
I don't think so, it's quite CPU intensive and I had previously had good
use out of the profiler in VS 2015.

**Comment by Mikejo5000** [comment]
@paddyboyd I discussed with the profiling team. Can you use the "Send Feedback" link at the top of Visual Studio (next to the Notifications icon) to provide feedback? To provide additional help, the profiling team would need to be able to get a repro. Thanks!

**Comment by Mikejo5000** [comment]
Closing this (support request)
