### ISSUE TITLE
I have a different menu compared to the one displayed in the article

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/visualstudio-docs#7020]
I do not get the option in the latest version of Visual Studio 2019.  Note that I am set to General Settings and have tried to reset my settings.

![image](https://user-images.githubusercontent.com/40300659/131743896-14108de8-d9bb-4361-8a8f-839710af0ee8.png)

How do I get the menu options shown in the article?

Just to be clear about my version of Visual Studio:
![image](https://user-images.githubusercontent.com/40300659/131744283-e19dfdc4-bbaf-4ea9-af16-fb85f1b67847.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83570d18-e0b6-0097-6966-1ffd6856955e
* Version Independent ID: 2a191933-b3ab-60ae-3e31-f1fb129ceefa
* Content: [Remove unused references - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/remove-unused-references?view=vs-2019)
* Content Source: [docs/ide/reference/remove-unused-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/remove-unused-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mdell-seradex** [comment]
It seems I am getting the "Project and Solution Context Menus | References" context menu instead of the "Project and Solution Context Menus | Reference Root" context menu (or something based on it).  I will check out the article you mentioned.

**Comment by mdell-seradex** [comment]
> @mdell-seradex -- thank you for your question. Please see this article and let me know if it helps resolve your issue:
> 
> * [How to use Solution Explorer](https://docs.microsoft.com/visualstudio/ide/use-solution-explorer)

I don't see anything in that link that is specific to the References menu.

Here is a larger image that shows I am attempting to access this from the Solution Explorer:
![image](https://user-images.githubusercontent.com/40300659/131747833-54024373-aa2f-42da-b625-71d4e3fcfc38.png)

**Comment by mdell-seradex** [comment]
FYI.  I did some testing at it is indeed the "Project and Solution Context Menus | Reference Root" context menu (or something based on it) that I am getting.  I just do not know why the options are not being displayed.

**Comment by WilliamAntonRohm** [comment]
@mdell-seradex -- thank you for pursuing those avenues.  If you feel this is a product issue, please add it here:
- [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) 

@mikadumont -- please look into this puzzle.

cc @TerryGLee for awareness

**Comment by mdell-seradex** [comment]
I honestly do not know what it is.  My initial thought was because there was something different about my environment or settings based on the fact that the documentation shows separate menu choices for adding different types of references.

**Comment by KalleOlaviNiemitalo** [comment]
<https://github.com/dotnet/project-system/pull/6692> was implemented in the .NET Project System repository. I suspect that "Remove Unused References" may be available only for projects that use the .NET Project System (with `<Project Sdk="Microsoft.NET.Sdk">`) rather than the original .NET Framework C# project system (with `<Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />`).

**Comment by mdell-seradex** [comment]
So, does that mean it is only available for certain C# projects, and not all C# and VB projects as the documentation currently indicates?

**Comment by KalleOlaviNiemitalo** [comment]
The documentation says:

> Right click on a project name or **dependencies** node in Solution Explorer.

Your screen shot has a **References** node rather than a Dependencies node, i.e. your project appears to be using the older project system.

If you create a new project from one of the .NET Core or .NET Standard templates, then that will use the newer project system, and you can then change the `TargetFramework` of the project to `net48` or another version of .NET Framework while keeping the project system.

But you are right, the documentation is not clear enough on this.

**Comment by mdell-seradex** [comment]
Note that I have tried to create a new style project before and then change it after to target the .NET Framework 4.x, but was unable to determine how to do so from the Visual Studio interface.
For instance, when trying to create a "Windows Forms Class Library", in the creation dialog I can only target ".NET 5.0 (Current)" and ".NET Core 3.1 (Long-term support)".
From the project properties, after the solution is created, I can only select ".NET 5.0", ".NET Core 3.0", ".NET Core 3.1", and "Install other frameworks...".  I can't imagine how the last option (other frameworks) would work since I can already create .NET Framework projects.

**Comment by mdell-seradex** [comment]
I try not to edit the project file itself directly since the documentation on that seems to lacking and I do not want to break anything.
In addition, I want to be able to direct other employees how to do this in a simple fashion.

**Comment by mdell-seradex** [comment]
> The documentation says:
> 
> > Right click on a project name or **dependencies** node in Solution Explorer.
> 
> Your screen shot has a **References** node rather than a Dependencies node, i.e. your project appears to be using the older project system.
> 
> If you create a new project from one of the .NET Core or .NET Standard templates, then that will use the newer project system, and you can then change the `TargetFramework` of the project to `net48` or another version of .NET Framework while keeping the project system.
> 
> But you are right, the documentation is not clear enough on this.

Please note that I did not understand that "Dependencies node" was an actual node in some projects, and that was further obscured by the fact that the image hides that fact.  I had just thought that "Dependencies node" was just being used as a general term that to describe types of reference, and possibly other similar nodes.  If it is actually only for references, then it is odd that Microsoft would rename it, as I would think that would cause confusion for people that have been using the product for many years.  That plus the fact that nothing else mentions that this is only for newer-style projects and cannot normally be applied to projects that target the .NET Framework added to my confusion.

I find it disappointing that a feature that we had before, for VB.NET projects in older versions of Visual Studio, was removed, and then re-added later on, but only for newer style projects.

@mikadumont, Please note that I have no clue why this issue is closed since it seems that nothing was done to at least improve the comprehension.  @KalleOlaviNiemitalo even stated as such (the documentation is not clear enough on this).
Note that I looked at the history for that page in GitHub to see if there were newer changes that improve the comprehension and saw nothing.

I appreciate hearing your feedback on this.

**Comment by mikadumont** [comment]
Hi I noticed that you are not able to see the PR that I linked to. I updated the description that Remove Unused References only works for SDK style projects which is why you dont see the option in Solution Explorer. Please update to .NET Core or .NET Standard (SDK style projects) to use this feature.

**Comment by mdell-seradex** [comment]
Thank you for the info.  It is greatly appreciated.
It seems odd that I can't see your pull request.  I am used to GitHub adding a reference to the PR in the issue when the PR references it.

**Comment by KalleOlaviNiemitalo** [comment]
Perhaps the pull request is in the private repository <https://github.com/MicrosoftDocs/visualstudio-docs-pr>, which haa been mentioned in some other issues. I don't work for Microsoft and don't have access to that.

**Comment by WilliamAntonRohm** [comment]
@mdell-seradex -- @KalleOlaviNiemitalo is correct, that the PR was opened in the private (pre-publication staging) repo and so it doesn't show up here.  That PR is now merged and the updated article should be available by tomorrow.

**Comment by mdell-seradex** [comment]
I had no idea that a private repo existed.
It still seems a little odd that it wouldn't be referenced here, but I don't really know how GitHub works. 🙂

**Comment by KalleOlaviNiemitalo** [comment]
I see the docs page now says: "Lets you remove unused references for SDK style projects."

It would still be helpful if you could replace the screen shot with one that shows the "Dependencies" title of the node.

**Comment by mdell-seradex** [comment]
I agree.
I think some people would not quite get the implication of "SDK style projects", and an updated image would be helpful.
I am not sure of what other wording could make it better, but at least the improved description and an updated image would be helpful.   The only other potential for a wording change that comes to mind at the moment would be to say `the newer SDK style projects`, but over time, "newer" would probably loose meaning.

**Comment by KalleOlaviNiemitalo** [comment]
Even better if "SDK style projects" were a link to a page that explains:

* How do I know whether my project is SDK-style
* Which project templates create SDK-style projects and which ones don't
* Which Visual Studio features are only available for SDK-style projects (e.g. editing the project file without unloading)
* How do I create an SDK-style project and target (or even multitarget) .NET Framework
* How do I convert a legacy project to SDK style (perhaps it's easiest to create a new project and copy the files and settings)
* Which types of projects I cannot convert to SDK style
* Any disadvantages of SDK-style projects (there may apparently be a problem if an ASP.NET web site, which does not have a project file and instead lists its references in the solution file, references a SDK-style C# project)

**Comment by mdell-seradex** [comment]
@KalleOlaviNiemitalo, I think those are excellent suggestions.

**Comment by mikadumont** [comment]
Great point, I will go ahead and add a link to the docs: https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview

**Comment by mdell-seradex** [comment]
@mikadumont, that does look like it should provide enough clarity for people, although I didn't see it covering much of the points @KalleOlaviNiemitalo raised.
