### ISSUE TITLE
How does the explorer determine which properties to show?

### ISSUE THREAD

**Issue by rkpatrick** [MicrosoftDocs/visualstudio-docs#703]
I've got datacontext objects where the explorer always leaves out several properties - usually the one(s) I'm interested in - instead showing a few that have no apparent difference from the ones it did not show. Could the documentation explain what critieria it uses to not show certain properties?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2baf39-d3c3-5d5a-d93c-f4040430c3dd
* Version Independent ID: c443e681-03f0-ea47-a09d-718693448b3d
* Content: [Inspect XAML properties while debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/inspect-xaml-properties-while-debugging)
* Content Source: [docs/debugger/inspect-xaml-properties-while-debugging.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/inspect-xaml-properties-while-debugging.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rkpatrick Thanks for the feedback. Can you take a look at this article?
https://visualstudiomagazine.com/articles/2015/08/01/debugging-xaml.aspx
It discusses limits on what is shown in the visual tree, and talks about how to view the default values that aren't specified in XAML.

**Comment by Mikejo5000** [comment]
@rkpatrick I took another look at this issue. If you click "Show properties", do the properties you are interested in show up in the Live Property Explorer? (It looks like properties that aren't directly specified in XAML can be found in the Live Property Explorer.) Also, if the DataContext object contains a large number of elements, maybe they are only added to the object as required, similar to a virtualized list for a ListView object? (as noted in the article)
