### ISSUE TITLE
15.6.274828.2005 is missing

### ISSUE THREAD

**Issue by Blonder** [MicrosoftDocs/visualstudio-docs#704]
https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates

**Comment by TerryGLee** [comment]
@Blonder Thanks for letting us know; this should be fixed either later today or tomorrow morning.

**Comment by TerryGLee** [comment]
@Blonder This page is now updated: [Visual Studio 2017 build numbers and release dates](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates) Thanks again for your feedback!
