### ISSUE TITLE
No menu item as shown 

### ISSUE THREAD

**Issue by maryob77062** [MicrosoftDocs/visualstudio-docs#7046]
I tried clicking on the project name in Solution Explorer. No such item on the context menu for removing references.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83570d18-e0b6-0097-6966-1ffd6856955e
* Version Independent ID: 2a191933-b3ab-60ae-3e31-f1fb129ceefa
* Content: [Remove unused references - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/remove-unused-references?view=vs-2019)
* Content Source: [docs/ide/reference/remove-unused-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/remove-unused-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mikadumont** [comment]
Hi there! Do you see the option when you right-click on a dependencies node? Are you using a [SDK style project](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview)?

**Comment by maryob77062** [comment]
@mikadumont  Thank you. It was the word "node" that solved it. I was being very dense. When I clicked on the individual node in the references node I got a Remove Option

**Comment by WilliamAntonRohm** [comment]
@maryob77062 -- Mary, thank you for your follow-up & success!

@mikadumont -- Mika, thank you for your insights.
