### ISSUE TITLE
the mt.exe page layout is messed up

### ISSUE THREAD

**Issue by lovettchris** [MicrosoftDocs/visualstudio-docs#7049]
See [https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe](https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe).

This is what I see (and the back has no feedback link at the bottom):

![image](https://user-images.githubusercontent.com/18707114/133307850-4eceb3ca-ad83-4675-be11-6640c0e83655.png)

**Comment by WilliamAntonRohm** [comment]
@lovettchris -- Chris, thank you for bringing this to our attention.  We're looking into this rendering issue.

**Comment by TerryGLee** [comment]
@mcleanbyron FYI.

**Comment by WilliamAntonRohm** [comment]
@lovettchris -- Chris, I added this issue to the documentation feedback site:
- https://github.com/MicrosoftDocs/feedback/issues/3687

If you find any more layout issues, please add them here:
- [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

**Comment by mcleanbyron** [comment]
FYI - We have fixed the formatting issues in the article: https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe
