### ISSUE TITLE
Property attribute needs to be capitalized

### ISSUE THREAD

**Issue by benmcmorran** [MicrosoftDocs/visualstudio-docs#705]
property needs to be Property in this snippet

<Setter property="FontFamily" Value="{DynamicResource VsFont.EnvironmentFontFamily}" />  
<Setter property="FontSize" Value="{DynamicResource VsFont.EnvironmentFontSize}" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf687dd-8919-8117-3d5a-b4f02aa297a9
* Version Independent ID: 18fe4bea-d914-21e2-77c0-37b2103427d9
* Content: [Fonts and Formatting for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/fonts-and-formatting-for-visual-studio)
* Content Source: [docs/extensibility/ux-guidelines/fonts-and-formatting-for-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/fonts-and-formatting-for-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
@benmcmorran Thanks for pointing this out!
