### ISSUE TITLE
Question regarding the scope of feature execution

### ISSUE THREAD

**Issue by alexander-dunn3** [MicrosoftDocs/visualstudio-docs#7054]
[Enter feedback here]
Is it possible to configure VS to execute these features per file/project/solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f59179f0-9d12-13be-bb50-cf36eff69b5a
* Version Independent ID: a0311f32-013d-7465-269c-5ebfbbb81300
* Content: [Wrap, indent, and align refactorings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/wrap-indent-align-refactorings?view=vs-2019)
* Content Source: [docs/ide/reference/wrap-indent-align-refactorings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/wrap-indent-align-refactorings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mikadumont** [comment]
Not at the moment but we are discussing converting this refactoring to a code style. You can follow this issue regarding that: https://github.com/dotnet/roslyn/issues/53464
