### ISSUE TITLE
Examples on how to use colours from `Environment` class

### ISSUE THREAD

**Issue by conniey** [MicrosoftDocs/visualstudio-docs#706]
I am trying to style my controls to look like the ones in VS.. but when I try to use the environment colours (ie. `{DynamicResource Environment.PanelHyperlink}`), I get binding errors that the resource cannot be found... A sample of using these from WPF VS would be awesome.

I found someone who had a similar question on [StackOverFlow](https://stackoverflow.com/questions/18913208/colors-in-visual-studio-extension), but its WPF sample doesn't match what I see in the styling guide.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcce5094-5214-8d84-ba80-15ba4a5d82fc
* Version Independent ID: 44443f75-0fba-cd33-1287-b4dcfbe69a04
* Content: [Shared Colors for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/shared-colors-for-visual-studio#feedback)
* Content Source: [docs/extensibility/ux-guidelines/shared-colors-for-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/ux-guidelines/shared-colors-for-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by r3m0t** [comment]
This may be useful https://github.com/Microsoft/PTVS/blob/7f63190f02a7d3960851645a7ae592927b55b351/Common/Product/SharedProject/Wpf/Controls.xaml

**Comment by gregvanl** [comment]
Community member provided an example.
