### ISSUE TITLE
Page should note for which VS editions this is and is not available.

### ISSUE THREAD

**Issue by ScottWelker** [MicrosoftDocs/visualstudio-docs#7065]
This page should clearly note for which VS editions this is and is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2019)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/modeling/install-architecture-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
@ScottWelker That information is contained on the first page: https://docs.microsoft.com/en-us/visualstudio/modeling/analyze-and-model-your-architecture?view=vs-2019#edition-support-for-architecture-and-modeling-tools

**Comment by WilliamAntonRohm** [comment]
@mgoertz-msft -- Marco, thank you for clarifying.

#please-close
