### ISSUE TITLE
TURN OFF DARK MODE

### ISSUE THREAD

**Issue by superdex** [MicrosoftDocs/visualstudio-docs#7069]
Holy crap it gives my eyes fits. Please either turn it off or provide an option. please. My eyes will be thankful (and I can't imagine I'm the only one)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 160a060d-7dc1-5826-8beb-f47097d0928f
* Version Independent ID: cc8a11cf-df37-97e9-bd0a-8c8ddd5037c7
* Content: [Copy Task - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2019&source=docs#feedback)
* Content Source: [docs/msbuild/copy-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/copy-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@superdex Do you mean the dark mode theme on docs pages?

To change the theme (dark, light, or high contrast) on docs pages as rendered in a browser on the desktop, scroll all the way to the bottom, and use the "Theme" link/button on the left side.

**Comment by superdex** [comment]
(sheepishly) thank you :)
