### ISSUE TITLE
ApplicationDeployment is not included in .Net Core 3.1 or 5

### ISSUE THREAD

**Issue by MrJohnLocke** [MicrosoftDocs/visualstudio-docs#7078]
The use of the ApplicationDeployment namespace (System.Deployment) is not included in .Net Core 3.1 or 5.0 .  I did not see a note stating this on the page, so I thought it might be good to include that for people wanting a way to programmatically update their WPF projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4c30cb0-8e88-4277-bfb9-e32d85538ce2
* Version Independent ID: 84b1bcd6-9554-b545-134f-ad66fb66e114
* Content: [Automatic app updates using ClickOnce deployment API - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-check-for-application-updates-programmatically-using-the-clickonce-deployment-api?view=vs-2019)
* Content Source: [docs/deployment/how-to-check-for-application-updates-programmatically-using-the-clickonce-deployment-api.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-check-for-application-updates-programmatically-using-the-clickonce-deployment-api.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by AngelosP** [comment]
Sorry @Mikejo5000 I don't know much about WinForms, WPF and ClickOnce these days. I mainly focus on web technologies.

**Comment by Mikejo5000** [comment]
@MrJohnLock Thanks for pointing this out. I've updated the articles referencing ApplicationDeployment class with a note. More updates coming with .NET 7.
