### ISSUE TITLE
Very helpful

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/visualstudio-docs#7081]
It was very helpful why we don't have a quick video on how to get started with Blend?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 285a65b7-d68e-ce1c-b5ba-56b10a50ac10
* Version Independent ID: 6aecce84-ff32-ade9-aa66-5b2f68648a8e
* Content: [Modify the style of objects - Blend for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/modify-the-style-of-objects-in-blend?view=vs-2019)
* Content Source: [docs/xaml-tools/modify-the-style-of-objects-in-blend.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/modify-the-style-of-objects-in-blend.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@rogerms -- thank you for your compliment!  Please add your suggestion here:
- [Visual Studio Developer Community](https://developercommunity.visualstudio.com)


cc @TerryGLee for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
