### ISSUE TITLE
Clarification for the article

### ISSUE THREAD

**Issue by Pitools** [MicrosoftDocs/visualstudio-docs#7084]
After creating projects, you need to configure ports in the "profile" / "applicationUrl" section in the launchSettings.json file (BackendProject).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Pitools Thanks for the feedback! I ran a few quick tests on this using the TypeScript template, and saw the same (or a similar issue). Vue page doesn't finish loading, and I see this message in the console:
Proxy error: Could not proxy request /weatherforecast from localhost:5002 to https://localhost:5001/.

I know launch.json is set to 5002 at present. How did you resolve this?

**Comment by Pitools** [comment]
I changed the project backend settings to: "https://localhost:5001;http://localhost:5003". And the project start.

![VueAndASP01](https://user-images.githubusercontent.com/55897247/135020959-7eabd9d2-abf6-452e-8a19-b97539759d78.jpg)
![VueAndASP04](https://user-images.githubusercontent.com/55897247/135021008-045e1b23-76b7-48f3-9637-89393d0758d2.jpg)

**Comment by Mikejo5000** [comment]
Thanks! That works for me, too. I'll update the doc.
