### ISSUE TITLE
Double-clicking on a Column in DataSet Designer does NOT create a new ColumnChanging event

### ISSUE THREAD

**Issue by tinmanjk** [MicrosoftDocs/visualstudio-docs#7087]
According to this: https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/validate-data-in-datasets.md

"The best place to add validation to your application is in the dataset's partial class file. In Visual Basic or Visual C#, open the Dataset Designer and **double-click the column or table** for which you want to create validation. This action **automatically creates** an **ColumnChanging** or RowChanging event handler."

In My VS 2019 Community 16.6, this is not the case. It instead opens the *.cs file but does not create a ColumnChanging event handler.

Should the documentation be updated?

**Comment by ghogen** [comment]
@tinmanjk 
Thanks for the feedback. I've updated the article to include the ColumnChanging event handler code. It is apparently not generated by Visual Studio.
