### ISSUE TITLE
Missing key information

### ISSUE THREAD

**Issue by FletcherJohnsonZ** [MicrosoftDocs/visualstudio-docs#7090]
Hello,

Please add information on how to confirm that the document was actually saved.
1) You don't mention Saved() as a way to check if it saved or not.
2) You don't mention Saved() for those situations where it won't (or didn't).  For example, open a sheet from a network drive and someone else has it open (both as read-write).  The other person makes a change and calls save.  Now you programmatically update the sheet, call save() then check Saved() - and it returns true - even though someone else made a change and saved it. Now close the work sheet.  When the other user closes their worksheet, the version on the network is their version, even if they make no more changes to it.  But Saved() returns true..... Office 365 with current updates, C# .net 4.8.  So it might be nice to have something more definitive on how to verify that the data was saved.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 638adb42-c2fb-a0ad-ff05-98619c53ce4a
* Version Independent ID: f5d6b740-cd03-3835-d7f7-b69d1931345e
* Content: [How to: Programmatically save workbooks - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-save-workbooks?view=vs-2019)
* Content Source: [docs/vsto/how-to-programmatically-save-workbooks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-save-workbooks.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@FletcherJohnsonZ would it be helpful if the article described how to check the [BuiltinDocumentProperties ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.tools.excel.workbook.builtindocumentproperties?view=vsto-2017) like "Last Save Time" ?

**Comment by John-Hart** [comment]
I add information about using the document properties to tell if the save was successful. @FletcherJohnsonZ I was not able to find a better solution for your network share issue.  I recommend working with customer support if you still have issues.
