### ISSUE TITLE
MyDSLDSLDocView

### ISSUE THREAD

**Issue by ArturGudiev** [MicrosoftDocs/visualstudio-docs#710]
A typo. 
Correct it, please.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb4f2a5-261b-15ef-fe63-e5c9e4df69c7
* Version Independent ID: 04a65c32-f983-ec19-c440-db7a2b7df16b
* Content: [Embedding a Diagram in a Windows Form - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/modeling/embedding-a-diagram-in-a-windows-form#feedback)
* Content Source: [docs/modeling/embedding-a-diagram-in-a-windows-form.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/modeling/embedding-a-diagram-in-a-windows-form.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ArturGudiev thanks for the feedback, I will fix this. Unless you would like to? If you are inclined, you can click the Edit button near the top right of the page, and then commit the change.

**Comment by ArturGudiev** [comment]
@gewarren ok. I have created a [pull request](https://github.com/MicrosoftDocs/visualstudio-docs/pull/712)

**Comment by gewarren** [comment]
@ArturGudiev thanks again for noticing and fixing this typo.
