### ISSUE TITLE
Vite should be documented as well as webpack

### ISSUE THREAD

**Issue by pedro-gilmora** [MicrosoftDocs/visualstudio-docs#7111]
Please, Vite is nicer & modern bundler than webpack, much faster, cleaner and easy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@pedro-gilmora -- Pedro, thank you for your feedback.  Please add this suggestion here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.mik
