### ISSUE TITLE
Very helpful indeed

### ISSUE THREAD

**Issue by nikky4D** [MicrosoftDocs/visualstudio-docs#7113]
[Very helpful in understanding how to get my data off docker unto the host folder. Thank you ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e42a144-9901-78d8-1082-a1c5b35a3602
* Version Independent ID: 34e7cab6-29bd-cb03-f100-a186b407a23f
* Content: [Docker tutorial - Part 6: Use bind mounts](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/use-bind-mounts)
* Content Source: [docker/tutorials/use-bind-mounts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/use-bind-mounts.md)
* Product: **visual-studio-family**
* Technology: **vs-docker**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@nikky4D -- Nkiruka, thank you for your kind words.  Congratulations on your Doctorate!

cc @ghogen for awareness
