### ISSUE TITLE
why is the rule deprecated

### ISSUE THREAD

**Issue by jtavernaro-progressive** [MicrosoftDocs/visualstudio-docs#7117]
The page doesn't say why the rule is deprecated and  takes me to a vague page with list of deprecated rules, but no reasons.  and the link on the page takes me back to the original pages that will take me back to the list of deprecated rules.  It's a meaningless circular reference.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836e7028-0bda-ef7c-fc11-4babb54ae70a
* Version Independent ID: 540dfe05-8e43-ed02-93d9-444c22485f84
* Content: [CA2202: Do not dispose objects multiple times - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2202?view=vs-2019)
* Content Source: [docs/code-quality/ca2202.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2202.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Russell-Horwood** [comment]
Why was this issue closed?

**Comment by WilliamAntonRohm** [comment]
@Russell-Horwood -- the original poster closed this issue 11 minutes after creating it, and that OP is no longer in GitHub.
