### ISSUE TITLE
Incorrect documentation about ruleset vs editorconfig precedence

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#7129]
---
**Issue moved from dotnet/docs#26234**
- Please respond to @mavasani.

---

_From @mavasani on Thursday, September 23, 2021 1:15:32 PM_

@mavasani Sorry to come back to this again:

Though the documentation referred in my last post may be correct, but the documentation referred in my initial post 
> According to https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2019:
> >Setting a rule's severity in an EditorConfig file takes precedence over any severity that's set in a rule set or in Solution Explorer.

seems not.

Edit: Anyway, thanks for the helping support so far!

_Originally posted by @julianbartel in https://github.com/dotnet/roslyn/issues/55920#issuecomment-925735644_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36455e6f-5542-5223-b242-9cddf6df267c
* Version Independent ID: 946abcdb-7e41-b5b5-e062-9cd8c914fbd3
* Content: [Code analysis using Roslyn analyzers - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/code-quality/roslyn-analyzers-overview?view=vs-2019)
* Content Source: [docs/code-quality/roslyn-analyzers-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/roslyn-analyzers-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@mavasani -- Manish, thank you for your followup.

@mikadumont -- Mika, please look into this issue.

**Comment by mavasani** [comment]
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#severity-options has the correct precedence rules

**Comment by mavasani** [comment]
You should migrate to using only editorconfig and globalconfig files, precedence rules between those files are here: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#precedence

Ruleset files are deprecated for managed projects

**Comment by j-martens** [comment]
Thank you for your post. We believe this answer is now available. We will now proceed to close this issue. If you feel this should be reopened, let us know.
