### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by scrollsaw** [MicrosoftDocs/visualstudio-docs#713]
Doesn't work as described. Something to do with the call to getData in the res.render line, but I haven't found the issue yet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec2387f-0fc8-9fdd-6f1c-85a0c8221939
* Version Independent ID: 671683ac-2ae6-e40c-b096-cd54f5785991
* Content: [Create a Node.js and Express app - Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/nodejs/tutorial-nodejs#feedback)
* Content Source: [docs/nodejs/tutorial-nodejs.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/nodejs/tutorial-nodejs.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@scrollsaw Hi, thanks for the feedback. Retested this topic. Most likely, you need to make the change shown in the Use IntelliSense section to make the app work. One goal is to show how the IDE works, but I will clarify in the doc that the code won't work until you make the fix described later. (I'm pretty sure that's the issue you hit, but if not, I'd double check that you are using the VS template specified in the doc).

**Comment by scrollsaw** [comment]
assuming that the line is supposed to be:
res.render('index', { title: 'Express', "data": getData() });
that is what I have.

Template is the same.
Latest version of visual studio 2017 community. Latest node.js

To clarify a bit, the app build and runs, but the images don't load.

If I use the breakpoint as described, I see the following error:
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

**Comment by Mikejo5000** [comment]
Hmm, yes I don't see that issue on Node.js 8.9.4 and the latest VS Enterprise 2017. If you have time, can you check your package.json? See if package versions are different. If different, you could try pasting this in your package.json, right-click the npm node, and update your packages. Thx!

  "dependencies": {
    "body-parser": "1.15.0",
    "cookie-parser": "1.4.0",
    "debug": "2.2.0",
    "express": "4.14.0",
    "morgan": "1.7.0",
    "pug": "2.0.0-beta6",
    "serve-favicon": "2.3.0"
  },

**Comment by scrollsaw** [comment]
mine was the same

"dependencies": {
    "body-parser": "^1.15.0",
    "cookie-parser": "^1.4.0",
    "debug": "^2.2.0",
    "express": "^4.14.0",
    "morgan": "^1.7.0",
    "pug": "^2.0.0-beta6",
    "serve-favicon": "^2.3.0"
  },

I ran an update and now it's

  "dependencies": {
    "body-parser": "^1.15.0",
    "cookie-parser": "^1.4.0",
    "debug": "^2.2.0",
    "express": "^4.14.0",
    "morgan": "^1.7.0",
    "pug": "^2.0.2",
    "serve-favicon": "^2.3.0"
  },

Same issue

Here is my index.js

'use strict';
var express = require('express');
var router = express.Router();

var getData = function () {
    var data = {
        'item1': 'http://public-domain-photos.com/free-stock-photos-1/flowers/cactus-76.jpg',
        'item2': 'http://public-domain-photos.com/free-stock-photos-1/flowers/cactus-77.jpg',
        'item3': 'http://public-domain-photos.com/free-stock-photos-1/flowers/cactus-78.jpg'
    }
    return data;
}

/* GET home page. */
router.get('/', function (req, res) {
    res.render('index', { title: 'Express', "data": getData() });  
});

module.exports = router;

**Comment by Mikejo5000** [comment]
OK, thanks. I'll update my Node version to 8.10 and see what happens.

**Comment by scrollsaw** [comment]
yeah, i'm using 8.10. Should have said that earlier.

I'm not sure if maybe the 'use strict' is causing some issues? Don't know enough about it to tell.

**Comment by Mikejo5000** [comment]
Node 8.10 works for me with no errors.
What happens if you remove 'use strict' from index.js?
A longshot, but you might also try removing quotes from data, i.e.,:     res.render('index', { title: 'Express', data: getData() });

**Comment by scrollsaw** [comment]
If I remove use strict, then the error I see when viewing getData() during runtime :

TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them

Doesn't show up. But the result is still the same. You are unable to see into the getData function as shown on the screenshot in the tutorial.

Also, clicking on the buttons does load an image. But there is a broken image when the page first loads. Is that supposed to happen?

I'm starting to think that perhaps it's working as it's supposed to but the tutorial is maybe just confusing.

**Comment by Mikejo5000** [comment]
Right, there aren't any images loaded until you start clicking on the buttons. That could be clarified in the doc.
You should, however, be able to stop on getData in the debugger after setting a breakpoint there. Are you hitting the breakpoint (yellow line) when you run it? If yes, then you can hover over getData and see the function (you actually have to expand the function to see it's properties; that is not stated in the doc).

**Comment by scrollsaw** [comment]
Yeah, it certainly looks like something is wrong because you get a broken image on first load.

Here is what I see

![2018-03-20 15_18_43-test_node_project_1 debugging - microsoft visual studio](https://user-images.githubusercontent.com/31285079/37677678-18f68dfa-2c52-11e8-90cc-af4c9b2d735c.png)

**Comment by Mikejo5000** [comment]
OK, that's good, I see the same thing. The screenshot is out of date (not sure what has changed that is giving more information than before, maybe a debugger bug fix in the VS update or something). This looks like expected behavior before the image loads. I'll update the screenshot.

**Comment by scrollsaw** [comment]
ok, thanks for all the help!

**Comment by Mikejo5000** [comment]
Sure, thanks for the feedback!

**Comment by swiac** [comment]
To fix the broken image on first load you need to enter an image src in index.pug at:

a: img(id='myImage' height='200' width='200' src='')

The current code has src='' so no image will display thus showing missing image. You can fix this by adding one of the example image links:

a: img(id='myImage' height='200' width='200' src='http://public-domain-photos.com/free-stock-photos-1/flowers/cactus-76.jpg')
