### ISSUE TITLE
great tutorial

### ISSUE THREAD

**Issue by asherabrams** [MicrosoftDocs/visualstudio-docs#714]
Created the app and got it running on the first try!  Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efa4d104-fb09-7060-8894-48a3ec73f98d
* Version Independent ID: a64a6fe9-fa60-d30d-65cd-cc9eda21d36d
* Content: [Step 8: Customize the Quiz - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/step-8-customize-the-quiz)
* Content Source: [docs/ide/step-8-customize-the-quiz.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/step-8-customize-the-quiz.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@asherabrams Thank you for saying so! :)
