### ISSUE TITLE
Incorrect RUN command (open parentheses without closing)

### ISSUE THREAD

**Issue by amirtoole** [MicrosoftDocs/visualstudio-docs#7140]
The `RUN` command to install `vs_buildtools.exe` is missing a closing parentheses:

```
RUN `
    # Download the Build Tools bootstrapper.
....
    && (start /w C:\TEMP\Install.cmd vs_buildtools.exe --quiet --wait --norestart --nocache modify `
```

Similar implementation can be found on this page:
https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019
Which has a closing parentheses; checking for `%ERRORLEVEL%`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2019)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@anandmeg -- Megha, please review [private PR 8873](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8873).
