### ISSUE TITLE
Missing documentation on configuring launch settings (Proxy error: Could not proxy request)

### ISSUE THREAD

**Issue by jimmytricks** [MicrosoftDocs/visualstudio-docs#7152]
Firstly thanks for having some documentation to scaffold Vue with Asp.Net Core.

I followed this along and was stuck with this error when trying to run:

Proxy error: Could not proxy request /weatherforecast from localhost:5002 to https://localhost:5001/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

I needed to remove this default information from the profiles part of the launch settings:

```
    "IIS Express": {
      "commandName": "IISExpress",
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
```

So my end launchSettings looks like:

```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:44618",
      "sslPort": 44366
    }
  },
  "profiles": {
    "hpicksbackend": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:5001;http://localhost:5003",
      "dotnetRunMessages": "true"
    }
  }
}
```

Unsure if this was just something affecting me but wanted to share as it took me a lil' while to figure it out.

Cheers,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@jimmytricks -- James, you're welcome!  And thank you for a solution.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@PranavSenthilnathan for comment on this workaround.

**Comment by Mikejo5000** [comment]
@jimmytricks Using the info in the linked issue (7253), I wasn't able to repro. If you continue to see this, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
