### ISSUE TITLE
Option Gm is listed as requirement, but will pop a warning for deprecation.

### ISSUE THREAD

**Issue by Thieum** [MicrosoftDocs/visualstudio-docs#7155]
To enable Edit and Continue, the second requirement is:

_C/C++ > Code Generation > Enable Minimal Rebuild: Yes (/Gm)_

But when setting this value, we get the following warning in VS2019:

Warning	D9035	option 'Gm' has been deprecated and will be removed in a future release

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c7c3f46-90e4-71f0-513c-a37ac5875515
* Version Independent ID: b676aec2-b85a-a85d-0e48-246b17ad0094
* Content: [Supported Code Changes (C++) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-cpp?view=vs-2019&source=docs#feedback)
* Content Source: [docs/debugger/supported-code-changes-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/supported-code-changes-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Thieum** [comment]
/Gm is still documented as deprecated here: https://docs.microsoft.com/en-us/cpp/build/reference/gm-enable-minimal-rebuild but still documented in the steps here: https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-cpp

**Comment by Mikejo5000** [comment]
@Thieum Thanks, this has been fixed in a doc update.
