### ISSUE TITLE
Corrections to "Create the Customers Table" and "Create the Orders Table"

### ISSUE THREAD

**Issue by nick1941** [MicrosoftDocs/visualstudio-docs#7161]
In the instructions for "Create the Customers Table", the following should be added in step 6 after 'CREATE TABLE [dbo].[Customers]'
6a. Change the CONSTRAINT to read 'CONSTRAINT [PK_Customers] PRIMARY KEY ([CustomerID]).
In the instructions for "Create the Orders Table", the following should be added in step 3 after 'CREATE TABLE [dbo].[Orders]'
3a. Change the CONSTRAINT to read 'CONSTRAINT [PK_Orders] PRIMARY KEY ([OrderId)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11d19e1d-1448-e5b3-6580-9b11042e03ab
* Version Independent ID: 549472fa-f3be-53bc-cf9f-170c1183c834
* Content: [Create a database file and use table designer - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2019)
* Content Source: [docs/data-tools/create-a-sql-database-by-using-a-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/data-tools/create-a-sql-database-by-using-a-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review [private PR 8884](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8884).
