### ISSUE TITLE
Convert to Linq option missing?

### ISSUE THREAD

**Issue by marinepix-home** [MicrosoftDocs/visualstudio-docs#7168]
For some reason, I'm unable to find the "convert to Linq" refactoring option. Has it been removed? 
Is there a package i need to install first?
I'm using vs2019pro (16.11.3). 
Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36a7fc54-584b-4ae2-ad71-6343ad8e2801
* Version Independent ID: 0784bf12-f389-3660-ae7a-1641a82d3e46
* Content: [Convert a foreach loop to LINQ - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/convert-foreach-linq?view=vs-2019)
* Content Source: [docs/ide/reference/convert-foreach-linq.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/convert-foreach-linq.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by j-martens** [comment]
This appears to be a technical support issue and not a documentation issue. The links above are best suited. We will now proceed to close this issue. Thank you.
