### ISSUE TITLE
Confusing information

### ISSUE THREAD

**Issue by samiraguiar** [MicrosoftDocs/visualstudio-docs#717]
In the remarks section it's said that "the Exec task, unlike a more specific task, cannot gather output from the tool or command that it runs.". Isn't this what the `ConsoleToMsBuild` parameter does?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb479ee7-d34c-dd5d-6843-4abdec6c3894
* Version Independent ID: 40cd6644-b061-335e-7bd4-6beede753c5d
* Content: [Exec Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task)
* Content Source: [docs/msbuild/exec-task.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/exec-task.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by samiraguiar** [comment]
Another thing: from my tests the working directory for the Exec task is by default the same directory as the .csproj file. Maybe this could be added to the documentation?

**Comment by Mikejo5000** [comment]
@rainersigwald It does sounds as if ConsoleToMsBuild is getting output from the tool that the Exec task is calling. Rainer, can you clarify?

**Comment by rainersigwald** [comment]
Yeah, that sentence is confusing. I think it was intended to say something more like "cannot do additional processing or conditional operations based on the result of the tool or command". You can indeed capture stdout and stderr from Exec.

**Comment by rainersigwald** [comment]
> Another thing: from my tests the working directory for the Exec task is by default the same directory as the .csproj file. Maybe this could be added to the documentation?

Unfortunately, it's more subtle and potentially confusing than that:

* When a project build starts, the working directory is set to the project's directory.
* A task can change the current working directory, but most don't.
* If Exec's `WorkingDirectory` parameter isn't specified, it uses the current working directory.

**Comment by Mikejo5000** [comment]
Updating the confusing sentence based on Rainer's suggestion above. Leaving the "working directory" content as-is.

**Comment by samiraguiar** [comment]
Nice, thank you guys.
