### ISSUE TITLE
Described menus don't exist on MacOS VS

### ISSUE THREAD

**Issue by jelmerS2** [MicrosoftDocs/visualstudio-docs#7175]
This guide described in the purple "Note" section is not correct for MacOS 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d2642c7f-04bb-56eb-0f26-d867703cf2f4
* Version Independent ID: 9c3f65b2-143b-8053-35ad-866152ea905e
* Content: [Encoding and line break characters - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/encodings-and-line-breaks?view=vs-2019)
* Content Source: [docs/ide/encodings-and-line-breaks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/encodings-and-line-breaks.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@jelmerS2 Thanks for your feedback. The page you reference is specifically for Visual Studio **for Windows**, and not for Visual Studio for Mac:

![image](https://user-images.githubusercontent.com/23244653/146438977-84a44e87-7c9b-4b7d-97a1-d0068ecde257.png)

For information about Visual Studio for Mac, i.e. the MacOS, please see the content set for it, here: [**https://docs.microsoft.com/en-us/visualstudio/mac/**](https://docs.microsoft.com/en-us/visualstudio/mac/).
