### ISSUE TITLE
This Project Does NOT Work!

### ISSUE THREAD

**Issue by graftedin** [MicrosoftDocs/visualstudio-docs#719]
There are many parts of this that are not consistent with the latest version of visualstudio.  After wasting close to 4 hours I gave up.  Please just delete this if you are not going to keep it updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 14465304-3ced-6b36-5054-a85ac11e667e
* Version Independent ID: 9d2d9ca3-8d71-b81c-dbbb-bf4b269db034
* Content: [Build apps with native UI using Xamarin in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio#feedback)
* Content Source: [docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/cross-platform/build-apps-with-native-ui-using-xamarin-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by conceptdev** [comment]
Thanks for your feedback, we're aware this doc needs some work and it's on our list. 

In the meantime, we recently updated the companion Xamarin.Forms doc here:
https://docs.microsoft.com/en-us/visualstudio/cross-platform/learn-app-building-basics-with-xamarin-forms-in-visual-studio

If you have an Android device, you might also be interested in our Getting Started guide using the Xamarin Live Player app, here:
https://developer.xamarin.com/getting-started/

There are also platform-specific getting-started guides for Android, iOS, Mac, and Xamarin.Forms on the Xamarin Documentation site:
https://docs.microsoft.com/xamarin/

**Comment by conceptdev** [comment]
This document has been updated - you will notice from the first screenshot, which now shows a UWP app instead of Windows Phone. I hope you have more success with the new version.

**Comment by dbybanez** [comment]
Still not working. As of Sept 20, 2018. When deploying to physical device and getting the weather, it throws an exception.

Unhandled Exception:

System.ArgumentException: You must obtain an API key from openweathermap.org/appid and save it in the 'key' variable.
