### ISSUE TITLE
Reference library in node_modules

### ISSUE THREAD

**Issue by RiadKatby** [MicrosoftDocs/visualstudio-docs#7192]
As you .NET Core MVC Project only reference javascript library that is under wwwroot folder and npm is storing his package in node_modules how to make visual studio see those package for both runs debug and deploy?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25963783-6129-cbef-174c-9dd4adde494b
* Version Independent ID: 85926796-ac02-c41b-8ffc-c8987e22f387
* Content: [Manage npm packages - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/npm-package-management?view=vs-2019#aspnet-core-projects)
* Content Source: [docs/javascript/npm-package-management.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/npm-package-management.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gcrev93** [comment]
@RiadKatby Can you share an example or screenshot on your issue?

**Comment by Mikejo5000** [comment]
We can revisit whether to re-open this if we get additional info. But, to make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
