### ISSUE TITLE
Clarity on step 9

### ISSUE THREAD

**Issue by Tks-Minion** [MicrosoftDocs/visualstudio-docs#7193]
In step 9 it says:

> To resolve the ambiguity, rename the namespace from **Calculator** to **CalculatorProgram** in both **Program.cs** and **CalculatorLibrary.cs**.
>
> `namespace CalculatorProgram`

There is no **Calculator** namespace in **CalculatorLibrary.cs**, it has the **CalculatorLibrary** namespace.

I checked further down the tutorial for the "_it should resemble this code_" section for both and can see there isn't anything in **CalculatorLibrary.cs** called "CalculatorProgram".

Should the step actually be only to update the namespace in **Program.cs**, rather than in both?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80ccbb63-7f84-55e6-1b3e-f48400aa17ae
* Version Independent ID: 6aba5d1b-f8ce-7b82-560e-c6a9926423ac
* Content: [Tutorial 2: Extend your C# console app - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-console-part-2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console-part-2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by TerryGLee** [comment]
@ghogen FYI, too.

**Comment by WilliamAntonRohm** [comment]
@anandmeg -- Megha, please review this update in [private PR 8945](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/8945).
