### ISSUE TITLE
It's not there anymore. 

### ISSUE THREAD

**Issue by milonilo** [MicrosoftDocs/visualstudio-docs#7203]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce19f95f-b1b3-98d0-76c1-ae7bd64e3b50
* Version Independent ID: f5615c72-044d-65c7-73f7-189cebcdf2c2
* Content: [Grow data science skills with DataCamp in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-datacamp)
* Content Source: [subscriptions/vs-datacamp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-datacamp.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **cabuschl**

**Comment by evanwindom** [comment]
@milonilo - Hi Milonilo.  I haven't heard from you and don't have sufficient context to take any action on this issue, so I'm going to close it.  Please feel free to reach out if you still need anything.

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger15** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.

**Comment by WilliamAntonRohm** [comment]
Thank you @evanwindom!

#please-close
