### ISSUE TITLE
Why aren't the version numbers listed for the cleanup tool? Where do I get the correct information for the tool?

### ISSUE THREAD

**Issue by BrianMinister** [MicrosoftDocs/visualstudio-docs#7205]
Why aren't the version numbers listed for the cleanup tool? Where do I get the correct information for the tool?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a3b0ef4-76d9-9c1e-4625-9cd56689b43a
* Version Independent ID: e882e8dc-8fb1-231d-d0bb-1f3e9dfec90d
* Content: [Remove Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/remove-visual-studio?view=vs-2019)
* Content Source: [docs/install/remove-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/remove-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@BrianMinister -- Brian, thank you for your question.  If I understand you correctly, that version number is the version of Visual Studio you're uninstalling.  The Visual Studio version number is shown under its Help menu, in About Microsoft Visual Studio.

cc @anandmeg for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
