### ISSUE TITLE
Thank

### ISSUE THREAD

**Issue by thanhanhhao06** [MicrosoftDocs/visualstudio-docs#7206]
[Nhập phản hồi vào đây]

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Create an ASP.NET Core web app in C# - Visual Studio (Windows)](https://docs.microsoft.com/vi-vn/visualstudio/ide/quickstart-aspnet-core?view=vs-2019)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@thanhanhhao06 -- Không có gì!
