### ISSUE TITLE
Nice Screenshot

### ISSUE THREAD

**Issue by vassilych** [MicrosoftDocs/visualstudio-docs#721]
I am happy that people working for Microsoft are also human and using the uTorrent App on a corporate MacBook

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0be31e5a-ccb8-93c5-43a0-ef8327f4ed4e
* Version Independent ID: 2ed7a14e-12ea-ea72-6678-0db050023a62
* Content: [Setup Visual Studio for Mac Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/mac/setup-vsmac-tools-unity)
* Content Source: [mac/setup-vsmac-tools-unity.md](https://github.com/Microsoft/visualstudio-docs/blob/master/mac/setup-vsmac-tools-unity.md)
* Service: **unspecified**
* GitHub Login: @dantogno
* Microsoft Alias: **v-davian**

**Comment by gewarren** [comment]
@vassilych thanks for pointing this out. @v-davian perhaps we should redo this screenshot? Apparently uTorrent can be used for downloading pirated files.

**Comment by gewarren** [comment]
@dantogno perhaps we should redo this screenshot? Apparently uTorrent can be used for downloading pirated files.
