### ISSUE TITLE
can not find fonts settings

### ISSUE THREAD

**Issue by hurluhum** [MicrosoftDocs/visualstudio-docs#7212]
can not find (  Find Highlight (Extension) ).?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b328a871-7747-31d6-737c-4e3f6d10d9d1
* Version Independent ID: 2b455842-a4ef-25bd-c386-f36e0d14ce3d
* Content: [Find and replace text, and multi-caret selection - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2019)
* Content Source: [docs/ide/finding-and-replacing-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-replacing-text.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@hurluhum Apologies; that text should read **Find Match Highlight** instead. We've updated the page; the fix should go live tomorrow. We'll close this now though, with our sincere thanks to you for bringing this to our attention, thereby helping us improve the documentation.
