### ISSUE TITLE
A sub-heading has basically the same words as the main heading and confusion over versions required for this to work

### ISSUE THREAD

**Issue by PandaWood** [MicrosoftDocs/visualstudio-docs#7213]
I'm quite confused by the sub-heading of `Build .NET ClickOnce applications from the command line`
Which is under the main heading of `Build ClickOnce applications from the command line`

The only difference is .NET - but the whole page must assume .Net, so how can this subheading make sense?

I've followed the instructions in this article, as closely as I can, and using a target of "publish" and providing a publish profile, simply does not work. Does not publish any files and just builds the project as normally.
Some of the help about creating a "publish profile" refers to a page that ultimately requires VS2019 16.8 as a minimum (why not provide information for all?)

So I'm completely confused - do I need VS2019 16.8 to do any of this? All of this?
And why would/could providing `/target:publish` on the command line for my project, which has a ClickOnce profile in it, do no publishing whatsoever (just building) and with no errors?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1672c325-b08a-dbc0-0e3e-31c832753613
* Version Independent ID: c479d585-37bb-795d-1e1c-4833c2262db6
* Content: [Building ClickOnce Applications from the Command Line - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2019)
* Content Source: [docs/deployment/building-clickonce-applications-from-the-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/building-clickonce-applications-from-the-command-line.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@PandaWood Checking the history, it looks like the doc had some additions for .NET Core and I believe it needs a correction or some clarification as a result of the last set of doc changes. I will plan to take a look at it. The doc was first written for .NET Framework scenarios. From this statement, "...properties are inserted into your project file by the Publish Wizard or in the publish profile file for .NET Core 3.1, or later projects", I think the .pubxml is only relevant for .NET Core 3.1 and later (and VS 2019 16.8). Currently, it does seem confusing. The publish profile doc you refer to only applies to .NET Core 3.1 and later (and VS 2019 16.8).

**Comment by Mikejo5000** [comment]
And this statement: "For .NET Core 3.1, or later, projects these settings are provided in the pubxml file."

**Comment by Mikejo5000** [comment]
Clarifying the section on .NET to refer to .NET Core 3.1 and .NET 5 and later.

**Comment by Mikejo5000** [comment]
Updated and the changes should be available live by EOD today.
PR:
https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10441
