### ISSUE TITLE
Add information about how to escape command line arguments

### ISSUE THREAD

**Issue by softworkz** [MicrosoftDocs/visualstudio-docs#7218]
In my case it was about passing a percent sign followed by a number without it getting interpreted/modified.
Others are struggling with passing '<' and '>' chars.

Like here:
- https://stackoverflow.com/questions/7882295/how-to-include-the-percent-character-in-the-visual-studio-debugger-command-line
- https://stackoverflow.com/questions/47991831/escaping-in-visual-studio-debugging-command-arguments/48006894

This information should be included here on this page rather than on just some SO responses.

Thanks,
sw

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bfbcccc-d2ac-0029-86cf-a67c2390272a
* Version Independent ID: e1352298-0650-bba1-7c15-e90eb7209e40
* Content: [Project settings for a C++ debug config - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/project-settings-for-a-cpp-debug-configuration?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VC.Project.IVCLocalDebugPageObject.CommandArguments)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/debugger/project-settings-for-a-cpp-debug-configuration.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/project-settings-for-a-cpp-debug-configuration.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updating this doc.

**Comment by softworkz** [comment]
@Mikejo5000  - Thanks for addressing this. How can I view the change?

The history of this file: https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/project-settings-for-a-cpp-debug-configuration.md

..still shows Jan11 for the latest commit.

**Comment by Mikejo5000** [comment]
@softworkz It goes live by about 5:00 pm PST.

**Comment by WilliamAntonRohm** [comment]
@softworkz -- yes, there is a private (staging) repo that gets published twice daily into this public-ready one.

**Comment by softworkz** [comment]
Ah alright, understood. That's am interesting kind of setup.
Thanks for taking care of this!
