### ISSUE TITLE
Update screenshots to Visual Studio 2022

### ISSUE THREAD

**Issue by kendrahavens** [MicrosoftDocs/visualstudio-docs#7225]
Update screenshots to Visual Studio 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3113c2af-d97e-7b35-17ce-c675c3dff889
* Version Independent ID: b716c4af-d92b-cb3b-8af0-1b3ada479ac0
* Content: [Live Unit Testing - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2022)
* Content Source: [docs/test/live-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/live-unit-testing.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
cc @Mikejo5000 for awareness

**Comment by kendrahavens** [comment]
Fixed in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9211
