### ISSUE TITLE
Documentation says that invalid references are found in Task List which is incorrect

### ISSUE THREAD

**Issue by RedX2501** [MicrosoftDocs/visualstudio-docs#7227]
https://docs.microsoft.com/en-us/visualstudio/ide/troubleshooting-broken-references?view=vs-2019#reference-path-is-incorrect

Says that invalid references will appear in the `Task List` AFAIK they appear in the `Error List` under MSB3245 (which does not appear to have a documentation page).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f552234-e74f-1cfc-848c-ba15571b35c6
* Version Independent ID: 2c89a49a-0aac-15bf-fb17-e644dfd115cc
* Content: [Troubleshoot broken references - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/troubleshooting-broken-references?view=vs-2019)
* Content Source: [docs/ide/troubleshooting-broken-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/troubleshooting-broken-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by RedX2501** [comment]
This has not been fixed yet.

**Comment by WilliamAntonRohm** [comment]
@RedX2501 -- thank you for your follow-up.

@TerryGLee -- please look into this issue.
