### ISSUE TITLE
Admin Privileges and Git with GCM Core

### ISSUE THREAD

**Issue by SamGrantham** [MicrosoftDocs/visualstudio-docs#7228]
Hi all,

I've seen several cases where using GIT with GCM as it is natively installed with VS 2017 and 2019 and users in NON Admin configurations will be able to complete commands from Git on the command line tool (though the GCM prompts every time for credentials). However after prompting for Credentials, _and completing the git action _ Visual Studio reports a failure as it was unable to save the credential to the windows credential store.  This is not a great experience for users and I'm not sure what we can do about it from a "fix" standpoint but I think that we need to call out that as it stands using Git with NTLM (at least) in VS requires you to be able to perform an action and save the credential 1 time at least as admin (after that it's just referencing it) and you can be a standard user unless you need to change it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc5e99e-c7bd-9519-c739-bfc6ab1a97fe
* Version Independent ID: 03884a15-6e09-1a83-e83a-584addb57248
* Content: [Run as administrator - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/user-permissions-and-visual-studio?view=vs-2019)
* Content Source: [docs/ide/user-permissions-and-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/user-permissions-and-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Taysser-Gherfal Please take a look at this; thanks.

**Comment by TerryGLee** [comment]
@rub8n Please take a look at this; thanks.

**Comment by TerryGLee** [comment]
@SamGrantham Hello; apologies for the delay in getting back to you on the issue you filed. I've checked in with our engineering team and here is what they had to say: 

"Regarding the specific problem of failing to write to the Windows Credential Store...the best place to go for support on issues like these is the GCM public issues on GitHub: https://github.com/GitCredentialManager/git-credential-manager (or complete an issue template at https://github.com/GitCredentialManager/git-credential-manager/issues/new/choose)."

We'll close this issue, but we hope you'll contact us again with your ideas on how we can improve the documentation.
