### ISSUE TITLE
CTest with MSBuild style projects

### ISSUE THREAD

**Issue by SamuelEnglard** [MicrosoftDocs/visualstudio-docs#723]
Can CTest be used with MSBuild style projects?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3f12b8-8048-3c19-8582-2ab35cbda74e
* Version Independent ID: 860805e8-915b-1c76-b6d3-4addc07da1a0
* Content: [How to use CTest for C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-ctest-for-cpp)
* Content Source: [docs/test/how-to-use-ctest-for-cpp.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/how-to-use-ctest-for-cpp.md)
* Service: **unspecified**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gewarren** [comment]
@mikeblome can you answer this one?

**Comment by mikeblome** [comment]
@SamuelEnglard Can you provide more specifics about your scenario? For example, are you asking whether CTest tests work with the Solutions and Projects that CMake can generate via the command line for Visual Studio?  CMake will generate a RUN_TESTS project that can run the CTests at build time but you don't get full IDE support via Test Explorer etc. It is best to just use the native CMake support.  If you are asking whether CTests can be run from a .vcxproj project, it might be possible by running a custom pre- or post-build step that invokes CMake to run  the tests.

**Comment by SamuelEnglard** [comment]
@mikeblome I was asking about generated from the command line, which you answered. Thanks!
