### ISSUE TITLE
Modification into: To create a minimal MSBuild project file 

### ISSUE THREAD

**Issue by Byron2016** [MicrosoftDocs/visualstudio-docs#7230]
in section "To create a minimal MSBuild project file" you can find: "In the text editor, replace the existing text by using these two lines:" ....
but which is the existing test? thre are not reference about what file it is talking about, is it a new file? is it a existing file

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bc6800-41dc-a7a4-5942-0f103a290cf9
* Version Independent ID: 56b974f2-30d2-ae79-2b78-7eb073ec7cd1
* Content: [Create an MSBuild project file from scratch - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch?view=vs-2019)
* Content Source: [docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Byron2016 -- apologies for the delay in replying.  It should say "create a new file"; I updated the article and it should be live by tomorrow.
