### ISSUE TITLE
Unable to create blank solution

### ISSUE THREAD

**Issue by adamy** [MicrosoftDocs/visualstudio-docs#7235]
It seems the "blank solution" template has disappeared from the current version of VS 2019.

![image](https://user-images.githubusercontent.com/1879576/140671344-ff7a4ca6-0e33-4675-82d6-19a880f1c177.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d9f53c-6ece-ea3c-9a51-9edd0efeebe3
* Version Independent ID: 9c927a8e-3ebd-0c8a-76cc-9b1c980b98a3
* Content: [Create projects & solutions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/creating-solutions-and-projects?view=vs-2019)
* Content Source: [docs/ide/creating-solutions-and-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/creating-solutions-and-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@adamy -- Adam, thank you for your feedback.  I just now updated my Visual Studio 2019 to v16.11.5, and this is what I see:![snap00314](https://user-images.githubusercontent.com/27738025/140833695-48d67097-8b47-4552-9b61-df5b590b8b12.png)

cc @TerryGLee for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by adamy** [comment]
Thanks @WilliamAntonRohm , I can see it now after upgrade to v16.11.5

**Comment by arganoid** [comment]
I am on VS 16.11.9 - there are no results when searching for "solution". If I search "blank" these are the only results: 
![image](https://user-images.githubusercontent.com/11721687/150639426-74f9572a-d180-44e8-b77c-8216babe2415.png)
