### ISSUE TITLE
ITrackingSpan section doesn't describe the SpanTrackingModes properly

### ISSUE THREAD

**Issue by kylereedmsft** [MicrosoftDocs/visualstudio-docs#724]
Look at the section about ITrackingSpan, it refers to SpanTrackingMode in all cases instead of the actual SpanTrackingMode enum value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f9f6314-07f7-4a22-2f4a-e29636bdda91
* Version Independent ID: d109c631-e7c0-5364-c6e4-12e2c47b1974
* Content: [Inside the Editor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/inside-the-editor#)
* Content Source: [docs/extensibility/inside-the-editor.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/inside-the-editor.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@kylereedmsft thanks for your feedback.

**Comment by gewarren** [comment]
Many enum field links were broken during the conversion from MSDN to docs.microsoft.com.
