### ISSUE TITLE
Descriptions on this page and reality are two very different things

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/visualstudio-docs#7241]
This page shows old information that is not shown in VS 2022 (release).  I've had this for a day and all I am finding is errors.  I guess the same people who released Win 11 released this.  The ability to not run code in the designer is something I have relied on for quite a while and it looks like that is out the window.

LLoyd Sheen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa80a87f-b85b-2282-f95f-d697f2e5b4c5
* Version Independent ID: c869f446-fe53-01f0-a170-30a3c43ff041
* Content: [Debug or disable project code in XAML Designer - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/debugging-or-disabling-project-code-in-xaml-designer?view=vs-2022)
* Content Source: [docs/xaml-tools/debugging-or-disabling-project-code-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/xaml-tools/debugging-or-disabling-project-code-in-xaml-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@sqlguy6212 Thanks for your feedback; we're looking into this and will report back.

**Comment by TerryGLee** [comment]
@sqlguy6212 We're still reviewing the page, but thus far we've added new information about the different process names that affect different versions of Visual Studio, which we hope proves helpful.

**Comment by TerryGLee** [comment]
@sqlguy6212 We are closing this issue now, as the key critical updates to the content were made earlier by adding the table that lists the process names that affect different versions of Visual Studio. Belatedly, we thank you again for your feedback and for your interest in improving the Visual Studio documentation.
