### ISSUE TITLE
VS 2022 uninstall SDK script instructions

### ISSUE THREAD

**Issue by cpboyd** [MicrosoftDocs/visualstudio-docs#7247]
`sudo ./ dotnet-uninstall-pkgs.sh` has an extra space after the `/`.

It should simply be:
```bash
sudo ./dotnet-uninstall-pkgs.sh
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cd4c8a0-03f3-68df-2107-3934c2da5655
* Version Independent ID: 7cd4c8a0-03f3-68df-2107-3934c2da5655
* Content: [Visual Studio for Mac 17.0 and .NET on Apple Silicon machines - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall-net-2022?view=vsmac-2019)
* Content Source: [mac/uninstall-net-2022.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/uninstall-net-2022.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by Murphy-Joe** [comment]
I had the same issue as cpboyd, copying the command `sudo ./ dotnet-uninstall-pkgs.sh` did not work. 
The change that worked for me was `sudo "dotnet-uninstall-pkgs.sh"`

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
