### ISSUE TITLE
Automatically Interaction between MVC and R projects

### ISSUE THREAD

**Issue by RawanRadi** [MicrosoftDocs/visualstudio-docs#725]
I have mvc project and R project I want to run mvc first display it on browser then send some arguments to R script in R project then run R project and refreshing mvc based on results of R project 

Currently I can execute Script.r only line by line the results saved as html then I run mvc and html results from R are displayed on browser I need to make it automatically.

My code is like this code https://1drv.ms/u/s!Ar6hTIP_Ln58h6JtpQQ3yt3JjIsIFg

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e11431a6-8401-2c63-b53c-e7f489b08ba7
* Version Independent ID: 1f8a17a4-122f-b2ef-f866-87dfdeaf3332
* Content: [R Tools for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/)
* Content Source: [docs/rtvs/index.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/rtvs/index.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@RawanRadi Thanks for your question. At present, Visual Studio's R support doesn't offer anything I know of that provides for interaction between R and other languages. If there are possibilities, and I'm not saying there are, providing such support is unfortunately beyond the scope of this forum which is for documentation issues only (thus I'm closing this issue). I can only suggest that you work through other channels, e.g. StackOverflow.
