### ISSUE TITLE
This page is not easily viewable with a browser zoom of 150%

### ISSUE THREAD

**Issue by DataJuggler** [MicrosoftDocs/visualstudio-docs#7251]
I was able to solve it be decreasing my browser zoom to 110% all the information became viewable. For some reason, the table is listed in a frame, and the frame width cuts of the information, and I didn't see a horizontal scroll bar.

I probably can't figure this out anyway (A VS 2022 version of my extension), but being able to read the docs without changing my zoom increases my chances.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe19410b-78ed-da1b-f8e1-fd3dc88061f0
* Version Independent ID: 71d3905b-5dbc-2c18-ec51-784ecf8fb349
* Content: [VS SDK NuGet packages - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/migrated-assemblies?view=vs-2022)
* Content Source: [docs/extensibility/migration/migrated-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/migration/migrated-assemblies.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @leslierichardson95
* Microsoft Alias: **lerich**

**Comment by WilliamAntonRohm** [comment]
@DataJuggler -- thank you for your feedback.  You can submit issues related to your overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).


cc @leslierichardson95, @TerryGLee for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
