### ISSUE TITLE
Is there a github project to download the example project source code?

### ISSUE THREAD

**Issue by besley** [MicrosoftDocs/visualstudio-docs#7254]
It seemed that the step is easy, but you can not run once exactly, some errors will be thrown out. If there is a source code package to download, it will make it much helpful.

Thanks for this article and the author!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@besley -- Besley, thank you for your question and your kind words.  Please see the links I replied with, in your previous issue #7253.  If you don't find a related GitHub project, please add a request here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
