### ISSUE TITLE
Please add article explaining differences between VS2022 and VS2022 (Github) versions

### ISSUE THREAD

**Issue by Amoenus** [MicrosoftDocs/visualstudio-docs#7255]
Currently, we have two versions and two serial keys for the new Visual Studio Professional 2022 from our subscription.

The one is just Visual Studio Professional 2022 and the second is Visual Studio Professional 2022 (Github). 

It would be great to have an article explaining the differences between the two and why they have different license keys.

Both legal and functional differences are important especially in a corporate environment where it's crucial to use software with correct licenses.

**Comment by WilliamAntonRohm** [comment]
@Amoenus -- Romans, thank you for your considered feedback.  Are you following a particular docs.microsoft.com article as a starting point?

@evanwindom -- Evan, please look into this issue.

cc @CaityBuschlen for awareness

**Comment by evanwindom** [comment]
@Amoenus -- Thank you for reaching out.  It sounds like you're not referring to one of our current articles as much as wondering why things look like they do in the downloads or product keys pages?  Is that correct?

**Comment by Amoenus** [comment]
You could say so, yes. It's just confusing to see and I couldn't find any
specific information on the topic. Hence the request :)

**Comment by evanwindom** [comment]
@Amoenus - Sorry for the extended delay here.  I've passed your feedback along to the engineering team for the portal.

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger18** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.
