### ISSUE TITLE
Code Style severities of "Error" do NOT cause builds to fail.

### ISSUE THREAD

**Issue by Xorcist77** [MicrosoftDocs/visualstudio-docs#7258]
[Enter feedback here]

The statement:

Violations appear as Errors in the Error List and in command-line build output, **and cause builds to fail.**

is incorrect, builds never actually fail due to any Code Style severities set to Error, and have never done so, ever since the introduction of this feature in VS2017.

Please correct this documentation, or fix the product.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c27ec225-8fc2-3578-05a0-a3e56e1c6510
* Version Independent ID: 186d9286-10db-6135-b542-81b1bf71575a
* Content: [Analyzer configuration - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022)
* Content Source: [docs/code-quality/use-roslyn-analyzers.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/use-roslyn-analyzers.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@mikadumont -- Mika, please review [private PR 9100](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9100).
