### ISSUE TITLE
Image library for VS 2022

### ISSUE THREAD

**Issue by YBAZAN** [MicrosoftDocs/visualstudio-docs#7266]
A big job has been done in Visual Studio 2022 about the icons. Is it expected to release the image library for it as for the previous versions? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05fe994a-b63e-dfc1-9de9-97e56a4e4917
* Version Independent ID: 95c63cef-e907-f443-a885-d1265f47c171
* Content: [Image Library - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/designers/the-visual-studio-image-library?view=vs-2022)
* Content Source: [docs/designers/the-visual-studio-image-library.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/the-visual-studio-image-library.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@YBAZAN Thanks for inquiring; we're looking into this and will report back soon.

**Comment by YBAZAN** [comment]
Hi @TerryGLee
Any news on this point ?

**Comment by qwqoq** [comment]
Looking forward to download

**Comment by TerryGLee** [comment]
@YBAZAN @qwqoq Thanks for taking the time to write up/respond to this GitHub Issue. The Microsoft Downloads page now includes an option to download a .zip file for the Visual Studio 2022 image library. We'll close this issue now with our additional thanks to you for your interest in this!
