### ISSUE TITLE
How to get a specific version of the installer

### ISSUE THREAD

**Issue by bzuu** [MicrosoftDocs/visualstudio-docs#727]
The documentation mentions "If you want to get the URLs for a specific channel, you can download the channel from https://aka.ms/vs/15/release/channel, open the JSON file, and examine the bootstrapper URLs." which is not very helpful at all. The JSON file only contains a single link to a vs_setup.exe file, and in no way seems to give a clue to where to obtain the vs_buildtools.exe. Please update the documentation to be more specific on where to find the correct download links and SHA hashes. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced Example for Containers - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container#feedback)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/advanced-build-tools-container.md)
* Service: **unspecified**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@heaths Can you take a look at this, please?

**Comment by heaths** [comment]
This is actually not supported (hadn't been decided when I wrote this). The supported way to get an older release is to build and maintain a layout from that release, as documented at https://docs.microsoft.com/visualstudio/install/visual-studio-administrator-guide. I will update the documentation to remove that and reference the layout docs instead.

**Comment by TerryGLee** [comment]
@heaths Is this updated? In other words, can we close this issue?

**Comment by heaths** [comment]
Yes, the topic was updated to guide the user to create a layout.
