### ISSUE TITLE
Data science and analytical applications workload missing.

### ISSUE THREAD

**Issue by jvsca** [MicrosoftDocs/visualstudio-docs#7270]
[Enter feedback here]
The **_Data science and analytical applications_** workload is missing.
In VS 2019 the ID is **_Microsoft.VisualStudio.Workload.DataScience_**.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe411145-ff47-dfe5-1e57-db8d54671b58
* Version Independent ID: 4dac6d72-8c3c-dec8-d473-a2902e4e1fb9
* Content: [Visual Studio Professional workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2022&preserve-view=true#feedback)
* Content Source: [docs/install/workload-component-id-vs-professional.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-professional.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@jvsca, thank you for your feedback. We've updated the page to add the missing workloads and component IDs. The changes are live now. 
Let us know if you have any other feedback. Thanks again for helping us improve our docs!

**Comment by jvsca** [comment]
> @jvsca, thank you for your feedback. We've updated the page to add the missing workloads and component IDs. The changes are live now. Let us know if you have any other feedback. Thanks again for helping us improve our docs!

Thank you.
