### ISSUE TITLE
Remote debugger link not working, points to Visual Studio download page

### ISSUE THREAD

**Issue by antoniohlopes** [MicrosoftDocs/visualstudio-docs#7272]
![Screenshot 2021-11-12 141741](https://user-images.githubusercontent.com/12420488/141413887-c4691678-adaf-45f7-99ac-65db9e8c6062.jpg)
Remote debugger link not working, points to Visual Studio download page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Can you re-try? I believe I fixed this issue end of day yesterday, and it works for me. What browser does it open?
