### ISSUE TITLE
Document states VS2022 is in preview and it is now released.

### ISSUE THREAD

**Issue by CZEMacLeod** [MicrosoftDocs/visualstudio-docs#7273]
There are many references on this page stating `Visual Studio 2022 is currently in preview and is not licensed for use in production environments.`
Given that VS2022 has now been released these should probably now be removed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2022)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@CZEMacLeod -- Cynthia, thank you for writing to us.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@CZEMacLeod -- Cynthia, this doc has been updated and is now live.

**Comment by CZEMacLeod** [comment]
@WilliamAntonRohm Updated to remove the message, but the instructions do not work. Obviously this has not been tested.

- You are missing backticks on the continuation lines (34 and 35) in the docker file.
- The install command (step 8/9) just runs forever and does not complete.
- You are installing to `%ProgramFiles(x86)%` when VS2022 is 64bit.
- The docker file uses the preview channel and preview executable URLs.

FYI the output of step 8/9 is
```pre
 ---> Running in 480b45cea7c8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1607k  100 1607k    0     0  1607k      0  0:00:01  0:00:01 --:--:--  9.8M
```
The only way out is to Ctrl+C and when you try to get the logs you get
`Error: No such container:path: 480b45cea7c8:C:\vslogs.zip`
I assume that using Ctrl+C cancels the step and doesn't save the container state so it is useless for diagnosing the issue.

And the `docker cp 480b45cea7c8:C:\vslogs.zip "%TEMP%\vslogs.zip"` command only works in CMD not PowerShell which is now the default on Windows and isn't mentioned. (The box containing the code is titled shell and is misleading if it means cmd not powershell).

**Comment by WilliamAntonRohm** [comment]
@CZEMacLeod -- Cynthia, thank you for your thorough follow-up.

@anandmeg -- Megha, please look into these issues.

**Comment by CZEMacLeod** [comment]
@WilliamAntonRohm @anandmeg Just to be clear - I use a docker image of VS2019 quite successfully at the moment, based almost exclusively on the previous version's documentation. And I then base an Azure DevOps self-hosted build agent image off that.
I have not found a way to make that into a VS2022 version, even when referring to the current documentation, which is why I was trying your 'vanilla' instructions as-is, but couldn't get that to work either.
It might be useful to actually publish a github repo with working solutions (perhaps with a branch for vs2019 and one for vs2022?).

**Comment by anandmeg** [comment]
@CZEMacLeod, thank you for your feedback! We've updated the doc, the updates should be live later today.

Thank you for your other suggestions, we will keep those in mind when making further updates. 
Thanks again and hope you hear from you again!

**Comment by CZEMacLeod** [comment]
@anandmeg I've tried the updated scripts and they still hang at stage 8/9 and do not complete.
Obviously, this is still completely untested.
Also, you still seem to be forcing the install to x86 despite VS2022 being 64bit.
