### ISSUE TITLE
Setting up proxy / ports

### ISSUE THREAD

**Issue by slbentley** [MicrosoftDocs/visualstudio-docs#7275]
In the section on setting up the ports, inside my net core launchSettings.json, I see 2 instances of "applicationUrl". One under "issSettings" and one under "profiles/[project name]".  Which one should be used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@PranavSenthilnathan for comment on this question. Which applicationUrl should be updated? Thanks.

**Comment by slbentley** [comment]
Updating. I assume it should be the ones under "profiles" as those are the two that the .net core host runs as, 1 under http and another under https. I've tried verifying  those, hitting them directly, and I get, in this demo case, the weather data back. But when I set my setupProxy.js up using either of those it never connects. I also played with setting the "secure" value in the setupProxy file to true, when using the .net core apps https port. But also tried with it off, not knowing exactly what its intent is. But no combination of any of that allows the front end react app to connect to the proxied net core app. This is 100% straight out of a new vs 2022 install, and two fresh projects using the templates: 1 react, 1 net core api, no changes made to the code other than what is mentioned in the article WITH THE EXCEPTION, that I have  a port conflict with the default port of 3000 and changed my start script in package.json to include "set PORT=3003" and then changed the .vscode\launch.json file to use 3003 when launching my browsers.

so, from launchSettings.json
 "applicationUrl": "https://localhost:7266;http://localhost:5266",
 
 from setupProxy.js
     const appProxy = createProxyMiddleware(context, {
        target: 'https://localhost:7266',
        secure: true
    });


I realize its possible its my environment and that is beyond the scope of this support, but starting here in case something was omitted from this documentation.

**Comment by slbentley** [comment]
I see now that it would be the settings under the profile, i.e. 
"applicationUrl": "https://localhost:7266;http://localhost:5266", Got past that, I set it to the 7266 port. Now the frontend is throwing cors errors when its trying to proxy to the backend.

**Comment by slbentley** [comment]
I resolved this once I started realizing what this was doing. But the documentation could use a little more clarification. Below is my launchSettings file
{
  "$schema": "https://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:58401",
      "sslPort": 44388
    }
  },
  "profiles": {
    "ReactProjectASPNETCore_Backend": {
      "commandName": "Project",
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "https://localhost:7266;http://localhost:5266",
      "dotnetRunMessages": true
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}

**Comment by PranavSenthilnathan** [comment]
The `https` endpoint should be used. For the shared profile here, it would be `https://localhost:7266`.
