### ISSUE TITLE
Missing IntelliTrace Component ID

### ISSUE THREAD

**Issue by starsunyzl** [MicrosoftDocs/visualstudio-docs#7276]
Missing IntelliTrace Component ID, which is:
Microsoft.VisualStudio.Component.IntelliTrace.FrontEnd

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022&preserve-view=true#desktop-development-with-c)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@starsunyzl, thanks for your feedback. We've updated the page to include the missing workloads and component IDs. The changes are live now. Let us know if you have any other feedback. Thanks again!
