### ISSUE TITLE
Line  writer.WriteValue("Divide"); should be outside of the if{} otherwise when divide by zero will cause exception in writer.WritePropertyName("Result");

### ISSUE THREAD

**Issue by hank165** [MicrosoftDocs/visualstudio-docs#7281]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80ccbb63-7f84-55e6-1b3e-f48400aa17ae
* Version Independent ID: 6aba5d1b-f8ce-7b82-560e-c6a9926423ac
* Content: [Tutorial 2: Extend your C# console app - Visual Studio (Windows)](https://docs.microsoft.com/en-gb/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-console-part-2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/csharp/tutorial-console-part-2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@hank165 -- thank you for finding this.  I have updated the article and it should be live by tomorrow.
