### ISSUE TITLE
Wrong...

### ISSUE THREAD

**Issue by GearTheWorld** [MicrosoftDocs/visualstudio-docs#7285]
Everything is wrong with Visual Studio 2022 just released.  There's no such command and the shortcut CTRL-K, CTRL-S reports that Surround With is not currently available

![image](https://user-images.githubusercontent.com/8614008/141708788-3939d762-3598-4b3a-b979-07d296ad3bfe.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0360876b-37ed-53ac-5b8a-5964574ee41a
* Version Independent ID: 27d1ddfd-0ec9-a6ac-b0f1-34b1f33f004b
* Content: [How to use surround-with code snippets - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-use-surround-with-code-snippets?view=vs-2022)
* Content Source: [docs/ide/how-to-use-surround-with-code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-use-surround-with-code-snippets.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@GearTheWorld Thanks for letting us know; we're checking in to this and will report back soon.

**Comment by TerryGLee** [comment]
@GearTheWorld You're right; the "Surround With" keyboard shortcuts do not work in Visual Studio 2022. We've removed references to them in the Visual Studio 2022 documentation. We thank you for giving us a heads-up about this and for your part in helping us improve the documentation.

We'll close this issue now vis-à-vis its Docs impact, but if you'd like to influence a change in the product itself, we encourage you to use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) mechanism to do so.

**Comment by GearTheWorld** [comment]
All good.  Keep the good work
