### ISSUE TITLE
Suggested additions to Go To Line document

### ISSUE THREAD

**Issue by svick** [MicrosoftDocs/visualstudio-docs#729]
The *Go To Line* document is currently fairly barebones. Things that I think should be added:

* Keyboard shortcut.
* Screenshot.
* Link to other documents about navigation, possibly https://docs.microsoft.com/en-us/visualstudio/ide/go-to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5b0abc5-a74f-4138-7608-6b4215bca8c0
* Version Independent ID: a16608ea-41ce-f2c2-dfd3-8ed50a5a083c
* Content: [Go To Line - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/go-to-line)
* Content Source: [docs/ide/reference/go-to-line.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/reference/go-to-line.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@svick these are great suggestions, thank you Petr.

**Comment by gewarren** [comment]
It should at least link to this topic: https://docs.microsoft.com/en-us/visualstudio/ide/go-to
