### ISSUE TITLE
Remote testing dialog not accurate

### ISSUE THREAD

**Issue by michaeljunkin** [MicrosoftDocs/visualstudio-docs#7290]
The drop down shown on this page does not exist.  Instead there is a test "filter" that does not do what this page explains.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ec9455-ef64-8854-94bc-9be28887a6a4
* Version Independent ID: 9adeea5e-7ba1-065f-5de0-aae9147f9c85
* Content: [Remote Testing in Visual Studio - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022)
* Content Source: [docs/test/remote-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/remote-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@michaeljunkin What version of Visual Studio are you using? @kendrahavens for awareness.

**Comment by michaeljunkin** [comment]
Visual Studio 2022.

**Comment by kendrahavens** [comment]
@michaeljunkin The drop down only appears if you have a `testenvironments.json` in the root of your solution where you define the environments that you have set up for remote testing. https://docs.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022#set-up-the-remote-testing-environment

**Comment by WilliamAntonRohm** [comment]
@kendrahavens -- Kendra, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.

**Comment by GaTechThomas** [comment]
I had the same issue - that being that no environment dropdown was showing. I had to restart VS 2022 in order for it to show up the first time.

**Comment by kendrahavens** [comment]
Ah, @GaTechThomas Thank you for mentioning that! I'll follow up with the team and figure out if we always need a restart (and change the documentation) or if we can have it appear as soon as the file is added.

**Comment by kendrahavens** [comment]
@GaTechThomas I heard back from the engineers. A restart should never be required, we definitely built it to automatically detect the file and update the Test Explorer so we aren't seeing this normally. If you see this again or are able to repro at all, would you mind filing a bug? https://developercommunity.visualstudio.com/

Again, thank you for mentioning the issue!
