### ISSUE TITLE
Issues in "Create an offline installation" page

### ISSUE THREAD

**Issue by PerseusTheGreat** [MicrosoftDocs/visualstudio-docs#7293]
At page [Create an offline installation of Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022), section `Use the command line to create a local cache`, [Step 1 - Download the Visual Studio bootstrapper](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022#step-1---download-the-visual-studio-bootstrapper) there are 2 issues:

1. In bootstrappers table, column `Edition`, Row 4, the text should be `Visual Studio 2022 Build Tools` but it is `Visual Studio 2022 Professional`
2. Enterprise link downloads `17.1.0 Preview` bootstrapper instead of `17.0.0 LTSC`. I think it would be better if `Preview` and `LTSC` versions be presented separately in two columns. Currently there is not a way to download `LTSC` version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@PerseusTheGreat, thank you for the feedback! We've updated the page for Visual Studio 2022 release and the bootstrapper links have been updated.

 Closing this now. Please let us know if you any other feedback. Thanks again!
