### ISSUE TITLE
Admin guide missing documentation for new VS2022 installer functionality

### ISSUE THREAD

**Issue by aursulis** [MicrosoftDocs/visualstudio-docs#7297]
Hi there,

I was quite excited to hear that the Visual Studio Installer shipped with VS 2022 has a number of great improvements for administrators, specifically the ability to change an installation's update channel, improvements with working with layouts etc. The [launch presentation](https://www.youtube.com/watch?v=EE8-TaXA-3I) notes that all this should be documented in the Visual Studio administrator guide at https://aka.ms/vs/admin/guide, however going through all the pages there I couldn't find it.

Any chance the information about programmatically switching between layouts, distributing the VS2022 installer with downlevel layouts etc. will be up soon?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed6b5f4-371f-825c-cf8a-3fdac127864f
* Version Independent ID: 5f721d18-882b-4fdf-3b02-c389026c62bc
* Content: [Visual Studio administrator guide](https://docs.microsoft.com/en-gb/visualstudio/install/visual-studio-administrator-guide?view=vs-2022)
* Content Source: [docs/install/visual-studio-administrator-guide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/visual-studio-administrator-guide.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@aursulis, thank you for your feedback! We've updated the page [Visual Studio administrator guide](https://docs.microsoft.com/en-gb/visualstudio/install/visual-studio-administrator-guide?view=vs-2022) and other related documents for Visual Studio 2022. The changes should be live later today. 

Closing this now. Please let us know if you any other feedback. Thanks again!
