### ISSUE TITLE
Documentation describes command that doesn't appear to be valid

### ISSUE THREAD

**Issue by saillingaway** [MicrosoftDocs/visualstudio-docs#7298]
While trying to use the `AddNewItem` command in order to automate adding files to a project with item templates, the command fails even when using the exact example from the documentation. The documentation says `AddNewItem` '_Adds a new solution item...to the current solution and opens it_' but it simply doesn't work for anyone in our org. `AddNewItem` doesn't appear in the tab completion drop down, and running `File.AddNewItem` results in **Command ">File.AddNewItem" is not valid.**

After some searching I found that other people have had somewhat similar issues with other cmds on VS2017 and VS2019:
- [command File.AddExistingItem is not valid](https://developercommunity.visualstudio.com/t/fileaddexistingitem-does-not-appear-visual-studio/536640)
- microsoft developer community post: [File.AddExistingItem not valid](https://developercommunity.visualstudio.com/t/fileaddexistingitem-does-not-appear-visual-studio/536640)
- [predefined VS cmds not available/working](https://social.msdn.microsoft.com/Forums/Windowsserver/en-US/60af4535-7217-427e-a5e7-17b2d00fce58/predefined-visual-studio-commands-not-available-or-just-not-working-properly?forum=vsx) (from 2012, but could still be relevant so I included)

I'm wondering if there are some ongoing bugs for these, or if the command just isn't supported anymore. Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d4adf8f-cb53-424e-6dac-85290cf1cc97
* Version Independent ID: fcc518e4-9576-4891-22c1-7618740b80da
* Content: [Add New Item Command - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/add-new-item-command?view=vs-2019)
* Content Source: [docs/ide/reference/add-new-item-command.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/add-new-item-command.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@saillingaway Thanks for letting us know; we're looking into this issue and will report back soon.

**Comment by saillingaway** [comment]
Hey any update on this?

**Comment by TerryGLee** [comment]
@sailingaway We tested this in Visual Studio 2022, Visual Studio 2019, & Visual Studio 2017. Then, we double-checked with the Engineering team. Turns out that you're absolutely right; the command is no longer supported. We've deleted the page. We'll close this issue now, with our thanks to you for helping improve the documentation!
