### ISSUE TITLE
React to UX changes to background analysis scope

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#7303]
Once https://github.com/dotnet/roslyn/pull/57172#issuecomment-970105416 goes in, we need to update the docs accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c981176b-8d39-beef-22d1-4a3721c4bf2a
* Version Independent ID: c76dfdc3-8584-e324-577c-991dbdd7bbac
* Content: [Configure live code analysis scope for .NET - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/code-quality/configure-live-code-analysis-scope-managed-code?view=vs-2022)
* Content Source: [docs/code-quality/configure-live-code-analysis-scope-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/configure-live-code-analysis-scope-managed-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mavasani** [comment]
@gewarren

**Comment by gewarren** [comment]
@mikadumont Are you taking care of this one? I see the roslyn PR is merged.

**Comment by gewarren** [comment]
#sign-off
