### ISSUE TITLE
Multi-caret selection: provide additional info

### ISSUE THREAD

**Issue by dubeg** [MicrosoftDocs/visualstudio-docs#7304]
Suggestion: 
In the "Muti-caret selection", could we add the commands related to the keyboards shortcuts as well? In this case:
```
Edit.LineUpExtendColumn (add caret up)
Edit.LineDownExtendColumn (add caret down)
```
I had them unmapped for years and I guess they sync'd via my Microsoft account when I logged into VS 2022, so I had no idea what these shortcuts were referencing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b328a871-7747-31d6-737c-4e3f6d10d9d1
* Version Independent ID: 2b455842-a4ef-25bd-c386-f36e0d14ce3d
* Content: [Find and replace text, and multi-caret selection - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2022)
* Content Source: [docs/ide/finding-and-replacing-text.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-replacing-text.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@dubeg Thanks for your feedback; we'll look in to adding this info as soon as we can (and we'll report back after we do).

**Comment by TerryGLee** [comment]
@dubeg Thanks for taking the time to provide us with your feedback; we appreciate it. We've added a "Commands" sub-section to the "Multi-caret selection" section of the [Find and replace text](https://docs.microsoft.com/visualstudio/ide/finding-and-replacing-text?view=vs-2022#multi-caret-selection) page, which includes the information you requested. We'll close this issue now, with our thanks to you for helping to improve the documentation!
