### ISSUE TITLE
Clarifying needed what tool this applies to

### ISSUE THREAD

**Issue by mm6502** [MicrosoftDocs/visualstudio-docs#731]
I have spent half a day trying to run MSTest with .runsettings. 

There should be explicitly stated which tool this applies to. MSTest IS mentioned, while the actual tool this applies to (vstest.console.exe) IS NOT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests in Visual Studio with a .runsettings file - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mm6502 thank you for this feedback. @pvlakshm can you clarify what tools .runsettings files are used for?

**Comment by amelvill** [comment]
Has there been any progress on this? I have the same question.

**Comment by gewarren** [comment]
@PBoraMSFT can you clarify which tools .runsettings is used for, or point me to someone that could clarify?

**Comment by gewarren** [comment]
@amelvill @mm6502 .runsettings files can be used to run tests from the command line, in the IDE, or as part of a CI/CI pipeline using the VSTest task. The topic should be updated by tomorrow. Sorry for the confusion this caused.
