### ISSUE TITLE
Need to update MPCs for VS2022

### ISSUE THREAD

**Issue by ManuelRin** [MicrosoftDocs/visualstudio-docs#7310]
The page version for Visual Studio 2022 is outdated. It currently states that Visual Studio 2022 is still in preview but it was released last week.
It would be great to have this page updated to list the necessary MPCs for all Visual Studio 2022 editions to be used with StorePID.exe.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11e2b93a-e89d-42ce-23d7-4cf85f47ba25
* Version Independent ID: 4083c0d5-c871-ef24-d11c-b6ec1adbb571
* Content: [Automatically apply product keys - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/automatically-apply-product-keys-when-deploying-visual-studio?view=vs-2022)
* Content Source: [docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/automatically-apply-product-keys-when-deploying-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@ManuelRin -- Manuel, thank you for your feedback.  Please see related issue #7252.
