### ISSUE TITLE
The configsection example has errors

### ISSUE THREAD

**Issue by alexander-anderson-salesforce** [MicrosoftDocs/visualstudio-docs#7311]
I was reading through the document and tried to use the <configSection> portion of sample xml.  However, it appears to have several errors which prevent me from using it directly.

--> type versus Type
--> missing >
--> VS gives an error regarding empty content

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a149d2bb-ccbf-42d8-5ea4-971fe211fdb6
* Version Independent ID: 3bcdf305-4f85-fe4d-24f5-1ce2ecec8d15
* Content: [Standard and Custom Toolset Configurations - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/standard-and-custom-toolset-configurations?view=vs-2022)
* Content Source: [docs/msbuild/standard-and-custom-toolset-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/standard-and-custom-toolset-configurations.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@alexander-anderson-salesforce Thanks for pointing out the issues with the sample code in this article. We're investigating the issue.

**Comment by ghogen** [comment]
Fixed.
@alexander-anderson-salesforce Thanks for reporting this issue.
