### ISSUE TITLE
Missing section

### ISSUE THREAD

**Issue by casterle** [MicrosoftDocs/visualstudio-docs#7315]
In the docs, there should be an 'Advanced' topic in addition to the 'General' and 'File Extension' topics.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@casterle Thanks for letting us know; we always appreciate customer feedback on our documentation. The good news is that we're working on creating this page, but we're tracking it and will report back via another, previously submitted issue, here: https://github.com/MicrosoftDocs/visualstudio-docs/issues/6588.

We'll close this now, but thanks again for contacting us!
