### ISSUE TITLE
Unity Tools: Remove IDE0051 from Unity API Messages

### ISSUE THREAD

**Issue by RicardoNiepel** [MicrosoftDocs/visualstudio-docs#7319]
CodeLens and Intellisense works wonderfully with Unity API Messages.

But VS Code Analysis is always showing warnings for them:
[Remove unused private member (IDE0051)](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0051)

Please use [DiagnosticSuppressor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor) to suppress IDE0051 for Unity API Messages.

If "Visual Studio Tools for Unity" are OSS, please made me aware of the repository hosting it and I will create a PR.
Otherwise please see this as a little feature request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5c0874b-2fb8-85a2-6e3a-2dc3c0ae82f2
* Version Independent ID: a02a434f-a213-ee56-5dd8-ecaf60e2dac3
* Content: [Using Visual Studio Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/using-visual-studio-tools-for-unity)
* Content Source: [gamedev/unity/get-started/using-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/gamedev/unity/get-started/using-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by WilliamAntonRohm** [comment]
@RicardoNiepel -- Ricardo, thank you for your detailed feedback.  Please clarify "OSS".

@therealjohn -- John, please look into this potential documentation issue.

**Comment by RicardoNiepel** [comment]
@WilliamAntonRohm Open source software - give me code access and I'm happy to contribute. We can also follow up internally.

**Comment by WilliamAntonRohm** [comment]
@RicardoNiepel -- Ricardo, thank you for your reply.  I've sent you an e-mail & am closing this issue as not being documentation-related.

**Comment by therealjohn** [comment]
Hi @RicardoNiepel 

Visual Studio Tools for Unity only supports Visual Studio. We recommend using Visual Studio when developing with Unity. 

There is currently no support for VS Code in the Tools for Unity.
