### ISSUE TITLE
Roslyn version support page stops at Visual Studio 2019

### ISSUE THREAD

**Issue by jnm2** [MicrosoftDocs/visualstudio-docs#7320]
https://docs.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2022:

![image](https://user-images.githubusercontent.com/8040367/142644177-9d255f37-f27f-47e8-8ce4-0f0924ae0f44.png)

Also, it doesn't explain how to line up 2019 update numbers with Roslyn package versions.

**Comment by jnm2** [comment]
Updates within 2019 and 2022 are still not listed.

**Comment by WilliamAntonRohm** [comment]
@jnm2 -- Joseph, thank you for your follow-up.

@ghogen -- Gordon, please look into this issue, and reassign if needed.

**Comment by ghogen** [comment]
See https://github.com/MicrosoftDocs/visualstudio-docs/pull/8373

**Comment by ghogen** [comment]
@jnm2 Thanks for reporting this issue. The PR https://github.com/MicrosoftDocs/visualstudio-docs/pull/8373 fixes this.
