### ISSUE TITLE
"Data science and analytical applications" workload is missing from VS 2022 workloads and components pages

### ISSUE THREAD

**Issue by jberezanski** [MicrosoftDocs/visualstudio-docs#7325]
The pages which list workloads and components for VS 2022 Community/Enterprise/Professional, i.e.

https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2022
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2022

do not contain information about the "Data science and analytical applications" workload (Microsoft.VisualStudio.Workload.DataScience). However, the workload does exist - it can be added to VS 2022 instances via the Visual Studio Installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@jberezanski -- Jakub, thank you for your feedback and contribution.  See related issue #7270.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.


cc @anandmeg for awareness

**Comment by jberezanski** [comment]
Oh, sorry, I missed that one.
