### ISSUE TITLE
15.6.4 is missing

### ISSUE THREAD

**Issue by JGroot** [MicrosoftDocs/visualstudio-docs#733]
15.6.4 is missing from the list. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio 2017 build numbers and release dates - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@JGroot Thanks; this list will be updated mid-day today.
