### ISSUE TITLE
I have expected to find info about Test doubles [Dummy, Fake, Stubs, Spies, Mocks] ?

### ISSUE THREAD

**Issue by raymendthomas** [MicrosoftDocs/visualstudio-docs#7331]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32738a06-835b-5bd5-7a6c-942c681aca97
* Version Independent ID: e715d12c-a4aa-eec3-c05f-1ff6243d209b
* Content: [Unit testing JavaScript and TypeScript - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/unit-testing-javascript-with-visual-studio?view=vs-2022&tabs=mocha#feedback)
* Content Source: [docs/javascript/unit-testing-javascript-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/unit-testing-javascript-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@raymendthomas -- Raymond, thank you for your feedback.  Can you please be more specific about this request?

**Comment by Mikejo5000** [comment]
@raymendthomas Thanks for your feedback! The intent of the article is to show how to get unit testing working with various third party frameworks like Mocha, Jest, Jasmine, and to get unit testing working with the Test Explorer in VS. In-depth info on the specific frameworks and how to use them is currently out of scope for this article. Did you check the docs for the unit testing framework that you're using?
