### ISSUE TITLE
Is there a Visual Studio Code or CLI version of this page

### ISSUE THREAD

**Issue by solrevdev** [MicrosoftDocs/visualstudio-docs#7335]
I can't seem to find how to achieve this with just visual studio code or the cli? 

I've searched my local dotnet new --list and also nuget.org for those standalone vue templates but cannot seem to find them. 

I would happily help create a page on how to do the same using cli or visual studio code if I was pointed in the right direction...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@solrevdev Hi, the docs you're referring to apply only to Visual Studio, so we can't help you here for VS Code or CLI questions. For VS Code, you might start here: https://code.visualstudio.com/docs/nodejs/vuejs-tutorial
