### ISSUE TITLE
Relative line numbering 

### ISSUE THREAD

**Issue by SangeetAgarwal** [MicrosoftDocs/visualstudio-docs#7336]
Can we please have relative line numbering.

**Comment by WilliamAntonRohm** [comment]
@SangeetAgarwal -- Sangeet, thank you for your request.  Please add it here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 
- 
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by SangeetAgarwal** [comment]
@WilliamAntonRohm Thanks for looking into this, but since I use VIM w/Visual Studio 2022, _not_ having relative line numbering is a "show stopper", & I suspect other folks using VIM might feel this way. Is there any way to have this feature shipped out?

**Comment by SangeetAgarwal** [comment]
@WilliamAntonRohm  I've suggested a "new feature" at https://developercommunity.visualstudio.com/home for having relative line numbering. Though honestly, I find it hard to classify relative line numbering in a text editor as a feature, this should always be there in a text editor, especially, if you writing code.

**Comment by WilliamAntonRohm** [comment]
@SangeetAgarwal -- Sangeet, thank you for your followup there & here.  This does not seem to be a documentation issue, so it is outside my charter.  I do agree that's a helpful feature!

**Comment by SangeetAgarwal** [comment]
@WilliamAntonRohm who else can I bother then? I think it's more than just a useful feature, its more of a necessity, I just can't use vim without relative line numbering on VS2022

**Comment by WilliamAntonRohm** [comment]
@SangeetAgarwal -- Sangeet, I am investigating an escalation path for this.

**Comment by SangeetAgarwal** [comment]
@WilliamAntonRohm  much appreciated, I'm dead in the water without relative line numbering since I use VIM and I can't work without relative line numbering in VS2022. Again, thank you so much for pursuing this.

**Comment by TerryGLee** [comment]
@SangeetAgarwal There's a request for more information on your ticket in the Developer Community, here: https://developercommunity.visualstudio.com/t/Can-we-please-have-relative-line-numberi/1602470?space=8&q=relative+line+numbering. Please take a moment to follow up? Doing so can help us to further help you. :)

**Comment by SangeetAgarwal** [comment]
@TerryGLee thanks for following up, I have added a comment to explain. But, just to clarify, relative line numbering the way you have in VSCode.

I use [https://marketplace.visualstudio.com/items?itemName=BrianSchmitt.RelativeNumber](https://marketplace.visualstudio.com/items?itemName=BrianSchmitt.RelativeNumber) in VS 2019 but can't in VS 2022. Besides, relative line #'ing should be a built in feature.
