### ISSUE TITLE
Page should explain how it works

### ISSUE THREAD

**Issue by lukepuplett** [MicrosoftDocs/visualstudio-docs#7337]
This page does not allow me to build a mental model of how it all works. It teaches me nothing. As a developer, it is **paramount** that you explain the mechanisms under the hood.

_How does the publishing tool know to publish a container and set the App Service up with containers?_

_What happens when I don't want to use a container on Azure but I want to use a container for local development?_

Perhaps I'm in the middle of changing from IIS-hosted Kestrel to a container and the live App Service does things differently to my development team in the interim.

 _How do containers work on the Azure side?_

_What ports are mapped? How does SSL work? Do I need to write code to detect and use an SSL certificate locally, but not when running on Azure?_

These questions are all critical path concepts and completely overlooked for the sake of giving a false hope of simplicity.

I've been coding on the MS stack for 23 years and this stuff is not obvious. I am slowly moving from Microsoft stack. I'm writing this on a Mac, which I thought I'd never say, because I don't want magic and false hope, I want to know how it works. Over 10 years you've stopped explaining how things work. You've stopped using diagrams.

You used to have deep whiteboard sessions on Channel 9. Even the latest .NET is proud of how little code is needed for an HTTP server, competing with Node and Go, but code is highly instructive, it's documentation in itself, and you can step through it.

Luke

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c58deff4-ba81-3d85-9fcc-8ddebb9143a6
* Version Independent ID: f28d7797-d245-a242-2b4a-533ed72acbbb
* Content: [Deploy an ASP.NET Core container to Azure App Service - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/containers/deploy-app-service?view=vs-2022)
* Content Source: [docs/containers/deploy-app-service.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/deploy-app-service.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@lukepuplett Thanks for the feedback. Your feedback goes well beyond this one page is and is a critique of trends in documentation and in API design that have occurred over many years. I'm sharing this with our engineering team and hope to get a range of responses to this.  I think there's a place for quickstarts and tutorials for people who just want to get something hooked up, but I hear your concern that there still has to be somewhere where you can deconstruct every detail and see how things work under the hood. I'm not sure that should be here in the tools docs, though. There's also the [App Service docs](https://docs.microsoft.com/en-us/azure/app-service/) and the [ASP.NET docs](https://docs.microsoft.com/en-us/aspnet/core/introduction-to-aspnet-core?view=aspnetcore-6.0), which should have much more detail on the concepts behind those technologies that you'll need when you go through this scenario.

**Comment by lukepuplett** [comment]
Thanks for your prompt reply. I'm in the other docs right now.

Techies equipped with a clear understand of how a system works are able to figure out how to get a system into a working state ourselves. This probably means less documentation is needed.

I think it can still be a quick start even with some writing or touching on what's going on. You could have a section titled **What just happened?** and say that the publishing tool found a Dockerfile and built an image, then somehow got it up to Azure which has Docker running and maps some default ports, or something (I'm making all that up).

In fact, any doc like this could have that section. It'd be so useful.

If I'm being really honest, I'm not convinced that a quick start that doesn't sign-post the reader into finding out how it's working is actually of much use. If the UX in the tooling is good enough, a quick start that scrimps on technical detail is superfluous.

It's funny. Right now, my underfloor heating is broken. It's just a bunch of unlabelled wires and some basic switching components and pumps. I could easily fix it myself if I only someone had labeled the wires and written down the logic.

**Comment by ghogen** [comment]
@lukepuplett Thanks for the response. I'll leave this open and consider how we can improve the article in some of the ways you suggest.
