### ISSUE TITLE
Why is this warning not emitted in UWP apps?

### ISSUE THREAD

**Issue by phraemer** [MicrosoftDocs/visualstudio-docs#734]
I've tried the following in a C# UWP app but it no warning is emitted.

```
{
    var tempFolder = ApplicationData.Current.TemporaryFolder;
    var filename = Guid.NewGuid().ToString();
    var tmpFile = await tempFolder.CreateFileAsync(filename, CreationCollisionOption.GenerateUniqueName);

    // Expect a warning that stream is not disposed
    var stream = await tmpFile.OpenAsync(FileAccessMode.ReadWrite);
    var dw = new DataWriter(stream);
    dw.WriteString("New file");
    // stream.Dispose();
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c370a407-b61d-0de6-6ac4-9b0ab49216b9
* Version Independent ID: a96e421e-65d3-07ba-097e-3feff2b3c677
* Content: [CA2000: Dispose objects before losing scope - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope)
* Content Source: [docs/code-quality/ca2000-dispose-objects-before-losing-scope.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/ca2000-dispose-objects-before-losing-scope.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mavasani can you answer this question please?

**Comment by mavasani** [comment]
@gewarren Seems like a bug in both legacy FXCop and FXCop analyzers implementation. Can you please port this issue to https://github.com/dotnet/roslyn-analyzers/issues?

**Comment by gewarren** [comment]
@phraemer thanks for letting us know about this behavior. Would you like to create an issue in the roslyn-analyzers repo so you can take credit, or would you like me to?

**Comment by phraemer** [comment]
Sure I can do it. Thanks.

**Comment by gewarren** [comment]
@phraemer thanks for porting this bug.
