### ISSUE TITLE
Only API part of app works

### ISSUE THREAD

**Issue by sandeshkarki55** [MicrosoftDocs/visualstudio-docs#7345]
It doesn't render react part of app. It just works for API

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1abf884f-eb39-1007-25a6-d049b87504a3
* Version Independent ID: 33636e79-d3e1-8c24-f3a5-0c3c79e2a488
* Content: [Visual Studio Container Tools with ASP.NET Core and React.js](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2022)
* Content Source: [docs/containers/container-tools-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/containers/container-tools-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@sandeshkarki55 
Is JavaScript enabled in the browser?

**Comment by sandeshkarki55** [comment]
Yes, JavaScript is enabled in my browser.

**Comment by ghogen** [comment]
@sandeshkarki55 
OK, so it worked for me quite recently with VS 2022 and .NET 6, so I think the content is probably good for that case.  Consider entering this as a product issue at the Developer Community site: https://developercommunity.visualstudio.com/search?space=8

**Comment by sandeshkarki55** [comment]
> @sandeshkarki55 OK, so it worked for me quite recently with VS 2022 and .NET 6, so I think the content is probably good for that case. Consider entering this as a product issue at the Developer Community site: https://developercommunity.visualstudio.com/search?space=8

Is is possible to provide me with the docker file you used?
