### ISSUE TITLE
Complete (corect command line docker run bind mount

### ISSUE THREAD

**Issue by thispointer** [MicrosoftDocs/visualstudio-docs#7346]
[Enter feedback here]
Please add the -w /app flag to the command line. In the VS code terminal on Manjaro Linux it did not work correctly. 

Hence the command is:
docker run -dp 3000:3000 -w /app -v ${PWD}:/app node:12-alpine sh -c "yarn install && yarn run dev"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e42a144-9901-78d8-1082-a1c5b35a3602
* Version Independent ID: 34e7cab6-29bd-cb03-f100-a186b407a23f
* Content: [Docker tutorial - Part 6: Use bind mounts](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/use-bind-mounts)
* Content Source: [docker/tutorials/use-bind-mounts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docker/tutorials/use-bind-mounts.md)
* Product: **visual-studio-family**
* Technology: **vs-docker**
* GitHub Login: @nebuk89
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@thispointer -- Bert, thank you for your feedback.

@ghogen -- Gordon, please review this update in [private PR 9119](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9119).

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
