### ISSUE TITLE
Link broken : "Visual Studio 2019 Remote tools"

### ISSUE THREAD

**Issue by lorenchorley** [MicrosoftDocs/visualstudio-docs#7352]
Hello,

The link for "Visual Studio 2019 Remote tools link" is broken. 2017 works though.
I spent a good 15 minutes running around trying to find the link via the broken link before realising the link for 2017 could get me the link for 2019.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2fd746-82f7-1bac-9932-27c14cdfe0ca
* Version Independent ID: 46b43a94-b750-2073-5e28-82183af092a9
* Content: [Remote Debug a C# or VB project - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-csharp?view=vs-2022)
* Content Source: [docs/debugger/remote-debugging-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugging-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by The-MAZZTer** [comment]
Anyone who's finding this issue and just wants a valid download link (this is probably not what you guys want to put in the docs though):

32-bit: https://download.visualstudio.microsoft.com/download/pr/9565895b-35a6-434b-a881-11a6f4beec76/a35a08ec313a248fc764134adb258f4d5ad1d8c3075fa7f2738db295fc61e5dc/VS_RemoteTools.exe

64-bit: https://download.visualstudio.microsoft.com/download/pr/9565895b-35a6-434b-a881-11a6f4beec76/518543c40390b13d735f266292e808637553f41fbdafebcfd60d13168620342b/VS_RemoteTools.exe

**Comment by Mikejo5000** [comment]
@lorenchorley Thanks, I'm updating this.
