### ISSUE TITLE
VS2019 Port

### ISSUE THREAD

**Issue by paulovila** [MicrosoftDocs/visualstudio-docs#7353]
Hi, Could you please specify the port for Visual Studio 2019 Remote Debugger?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c19e4f-4623-c462-e399-008a85ea1523
* Version Independent ID: bc0b82bb-acc8-7438-7b18-5165de39d847
* Content: [Remote Debugger Port Assignments - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugger-port-assignments?view=vs-2022)
* Content Source: [docs/debugger/remote-debugger-port-assignments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/debugger/remote-debugger-port-assignments.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@paulovila -- thank you for your question.  The port is 4024.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
