### ISSUE TITLE
Change link from blog post to official docs

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [MicrosoftDocs/visualstudio-docs#7356]
The page at https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2022?view=vs-2022 links to the blog post https://devblogs.microsoft.com/visualstudio/the-new-javascript-typescript-experience-in-vs-2022-preview-3/ for more details about the new JavaScript project type.

I think it'd be better if this page linked to https://docs.microsoft.com/en-us/visualstudio/javascript/?view=vs-2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6dfb3b1-b0cd-5f84-5bd8-e8777328430a
* Version Independent ID: ea11fd8a-cd57-a76e-ac76-f64b0d52ec8e
* Content: [JavaScript and TypeScript in Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-vs-2022?view=vs-2022)
* Content Source: [docs/javascript/javascript-in-vs-2022.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/javascript-in-vs-2022.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by Bosch-Eli-Black** [comment]
Thanks! 🙂
