### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by CuriousMax69** [MicrosoftDocs/visualstudio-docs#7357]
For versions VS 2017, 2019 and 2022 the link points to the same page:

https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2017ColorThemeEditor

Must be:

**Color Theme Editor for Visual Studio 2017**
https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2017ColorThemeEditor
**Color Theme Editor for Visual Studio 2019**
https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2019ColorThemeEditor
**Visual Studio Color Theme Designer**
https://marketplace.visualstudio.com/items?itemName=ms-madsk.ColorThemeDesigner

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b9f7bdc-2be2-9733-db40-4153a7463910
* Version Independent ID: 8aa09492-2143-3861-d51f-5e2961e1793f
* Content: [General, Environment, Options Dialog Box - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/general-environment-options-dialog-box?view=vs-2022)
* Content Source: [docs/ide/reference/general-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/general-environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@CuriousMax69 Thanks for letting us know. We'll get that page updated later today. Meanwhile, here are the links you're looking for:

- [Color Theme Designer for Visual Studio 2022](https://marketplace.visualstudio.com/items?itemName=idex.colorthemedesigner2022)
- [Color Theme Designer for Visual Studio 2019](https://marketplace.visualstudio.com/items?itemName=ms-madsk.ColorThemeDesigner)
- [Color Theme Editor for Visual Studio 2017](https://marketplace.visualstudio.com/items?itemName=VisualStudioPlatformTeam.VisualStudio2017ColorThemeEditor)
