### ISSUE TITLE
Using .resx files in shared project does not work well

### ISSUE THREAD

**Issue by mayerwin** [MicrosoftDocs/visualstudio-docs#7360]
I followed these guidelines and wasted a lot of time as .resx files are basically not supported in shared projects. 

To replicate, in the original VS2019 VSIX project, add some strings as resources, and try to move the resulting .resx and .cs code to the shared project. Any change to the resx won't be reflected in the .cs file (code generation doesn't work), and at runtime it'll throw a MissingManifestResourceException when trying to access the resource from the VS2019 or VS2022 project.

So I ended up having to create an additional "Resources" library project to share them.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff61d138-af47-2a63-05c8-8d4b20ae1518
* Version Independent ID: de85151d-17c1-d230-f110-fd4e94e7da45
* Content: [Update a Visual Studio extension - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)
* Content Source: [docs/extensibility/migration/update-visual-studio-extension.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/migration/update-visual-studio-extension.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @leslierichardson95
* Microsoft Alias: **lerich**

**Comment by WilliamAntonRohm** [comment]
@mayerwin -- thank you for your well-researched feedback.  You are welcome to add this here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 


@leslierichardson95 -- please look into this issue.

**Comment by mayerwin** [comment]
This is still actionable.

**Comment by WilliamAntonRohm** [comment]
@mayerwin -- thank you for your follow-up.


@leslierichardson95 -- please look into this issue.

**Comment by mayerwin** [comment]
This is still actionable.

**Comment by mayerwin** [comment]
This is still actionable.
