### ISSUE TITLE
Mysterious Git Hub made so more mysterious by Visual Basic Visual Studio

### ISSUE THREAD

**Issue by Corncheese2** [MicrosoftDocs/visualstudio-docs#7361]
[Enter feedback here]
It really becomes annoying when Visual Studio Visual Basic programs such as Form vb with a button and simple coomand such as showing an image when the button is clicked gives and error message yet why should the code then be uploaded to Git and induce more errors? Visual Basic Tools are scattered any which way in Visual Studio and I think it is lame for Microsoft to expect someone coding to "go fetch" each single tool and add it manually to the toolbox list? There are definetly tools missing from the original VB Toolbox it seems. Its idiocy to fetch and search for tools instead of working on the GUI and code immediately.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20f3b242-e5be-0e07-79bf-c3f1652d3861
* Version Independent ID: 61c049c6-c028-692e-5b76-5cd8cb0ea020
* Content: [Tutorial: Get started with Visual Basic - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/visual-basic/tutorial-console?view=vs-2022)
* Content Source: [docs/get-started/visual-basic/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/get-started/visual-basic/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@Corncheese2 -- thank you for your considered feedback.  Please add it here:
- [SQL Server feedback](http://aka.ms/sqlfeedback)

This repo is solely for documentation issues, and this appears to be product-related.  I am closing this issue now.  You are welcome to @ mention me for any followup.  

cc @anandmeg for awareness
