### ISSUE TITLE
Steps do not work.

### ISSUE THREAD

**Issue by MarcM-PL** [MicrosoftDocs/visualstudio-docs#7366]
I'm running VS 2019 with node v14.18.0.  These steps do not work for me, I get the error when building:

------ Build started: Project: XYZ Configuration: Debug Any CPU ------
		> xyz@0.1.0 build
		> vue-cli-service build
EXEC(0,0): error Error: Cannot find module '@vue/babel-preset-app'

I then run 'npm install' from the root project directory and it gets past that error. Then when I build I get:

		> vue-cli-service build
		-  Building for production...
		 ERROR  Failed to compile with 1 error2:19:12 PM
		 ERROR  Build failed with errors.
EXEC(0,0): error : TypeError: Cannot read property 'parseComponent' of undefined
		You may use special comments to disable some warnings.
		Use // eslint-disable-next-line to ignore the next line.
		Use /* eslint-disable */ to ignore all warnings in a file.

I then manually installed the matching version of the vue-template-compiler package @2.6.14 (previously 2.6.12 was installed)
and I got the project to compile/build.

-Marc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59adf9c7-5894-84ba-32ee-df842aa4658d
* Version Independent ID: 50683e7c-4b31-1773-f20e-00732a0ffbcc
* Content: [Quickstart: Create your first Vue.js app - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/quickstart-vuejs-with-nodejs?view=vs-2019)
* Content Source: [docs/javascript/quickstart-vuejs-with-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/javascript/quickstart-vuejs-with-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gcrev93** [comment]
Hey can you please use the [Report a Problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) tool to report the issue. My team cannot track the issue here since this is the issues for the docs but when you report it we can add it to your backlog!

**Comment by Mikejo5000** [comment]
@MarcM-PL Please see previous comment. We want to track this in the right place. Thanks!
