### ISSUE TITLE
ref missing 15 times

### ISSUE THREAD

**Issue by menjic** [MicrosoftDocs/visualstudio-docs#7367]
What is :

ref missing, ref missing, ref missing, ref missing, ref missing, 
ref missing, ref missing, ref missing, ref missing, ref missing,
ref missing, ref missing, ref missing, ref missing, ref missing

And why 15 times, why not 16 or 14 or 1 or 75 ?

If we try to write anything else in C# exact same 2 words 15 times in () it would never work ?

What is the issue here you may ask. Yes it is my lack of knowledge but that is why I am reading this, to learn. I found more than one example like this, other stuff in this page are either pretty well explained or self explained but this one I think is not. 

It may be just me not knowing enough but I like to think I am not the only one stupid. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f67c7ecf-15ba-62e3-acf0-83dd80b5a874
* Version Independent ID: b3cc3ad2-00df-783c-7257-a1609f33453b
* Content: [How to: Programmatically loop through found items in documents](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-programmatically-loop-through-found-items-in-documents?view=vs-2022)
* Content Source: [docs/vsto/how-to-programmatically-loop-through-found-items-in-documents.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/vsto/how-to-programmatically-loop-through-found-items-in-documents.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@menjic thanks for the feedback.

The sample code is calling [Find.Execute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word.find.execute?view=word-pia) which takes 12 optional parameters.  In the sample, some of the parameters are already set on the Range.Find property so they're just passing in the "missing" variable that is defined in ThisAddIn as a [System.Type.Missing](https://docs.microsoft.com/en-us/dotnet/api/system.type.missing?view=netframework-4.8);

You can see more information on how to use optional parameters in the [Optional parameters in Office solutions](https://docs.microsoft.com/en-us/visualstudio/vsto/optional-parameters-in-office-solutions?view=vs-2022#use-optional-parameters-of-methods-in-the-thisdocument-class-in-visual-c-document-level-projects-for-word) document.
