### ISSUE TITLE
Visual Studio 2022 no template again

### ISSUE THREAD

**Issue by joshjlgr** [MicrosoftDocs/visualstudio-docs#7374]
Pls stop pretending it will work. Instead please just let people download their templates off a controlled site. 

1 cannot install properly
2 cannot even update
Get this error https://ibb.co/YTbSCsH

3 too many report same problem 
4 its the same problem for many years
https://developercommunity.visualstudio.com/myfeedback?port=1025&fsid=c898ddd2-8437-4ef3-a0a0-6230406517f5&entry=myfeedback

Look at number of people reported no template and just kept being swept under the carpet! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99f36dca-129d-9839-0e4b-fcadaa4b63d7
* Version Independent ID: 02d93129-77e2-e667-a06f-ad79f5f7240a
* Content: [Templates for projects and files - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/creating-project-and-item-templates?view=vs-2022)
* Content Source: [docs/ide/creating-project-and-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/creating-project-and-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@joshjlgr -- Josh, thank you for your feedback.  Please add/upvote it here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

@TerryGLee -- Terry, please look into this issue.

**Comment by TerryGLee** [comment]
@joshjlgr Also, for the error message, please consider reporting that via the [**Report a Problem**](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) tool. Meanwhile, I will look over the [Project and item templates](https://docs.microsoft.com/en-us/visualstudio/ide/creating-project-and-item-templates?view=vs-2022) to see if it requires any updates. Thanks.

**Comment by joshjlgr** [comment]
@TerryGLee Already this was done and submitted in this method multiple times. 

There seem no sharing of workarounds on the net. 

Even this do not contain info on troubleshooting 2022 installation
https://support.microsoft.com/en-us/topic/common-issues-in-visual-studio-2015-setup-017ff42c-ec62-3983-910b-7fa5dcac3c33?WT.mc_id=365AdminCSH_Smc

I worked with Joyce Yin[MSFT] who responded at my tickets after viewing my submitted logs.

It is working now:

1. 1st I manually removed all old Visual Studio files from C: local Including those in C:\Program Files (x86) and C:\Program Files\Microsoft Visual Studio

2. I ran sfc /scannow on Command Prompt as admin.

3. Then I uninstalled it properly off my other drive. T:

4. Reboot and do a clean install. C: will have main files. Cache and tools can park at an alternate drive for space management. 

5. Installation success without errors and copy has templates.

**Comment by joshjlgr** [comment]
Please share solutions and update Visual Studio 2022 install problems and workaround. It is still talking about 2015.

Please allow voting and not keep closing tickets! I note this to be a constant problem as far as 8 years ago. Project templates do not show! It seems after so many versions the problem remains.
