### ISSUE TITLE
Wrong information in the German translation of the article

### ISSUE THREAD

**Issue by Tiglat1** [MicrosoftDocs/visualstudio-docs#7377]
According to this article 
2 The Pluralsight benefit in selected Visual Studio subscriptions renews when your subscription renews. For example, if you have an annual subscription that you renew each year, the benefit is available to you each year when you renew. **If you have a multi-year subscription, the Pluralsight benefit is available to you once during the term of the subscription. If you renew a multi-year subscription, the benefit will be available again following the renewal.**

The German version of this article says:
2 Der Pluralsight-Vorteil wird in ausgewählten Visual Studio-Abonnements gemeinsam mit dem Abonnement verlängert. Wenn Sie beispielsweise ein Jahresabonnement abgeschlossen haben, das jährlich verlängert wird, profitieren Sie so lange von diesem Vorteil, bis das Abonnement gekündigt wird. **Wenn Sie ein Abonnement mit einer Laufzeit von mehreren Jahren abgeschlossen haben, ist der Pluralsight-Vorteil so lange verfügbar, wie das Abonnement besteht. Wenn dieses Abonnement verlängert wird, können Sie auch weiter von dem Vorteil profitieren.** [If you have a multi-year subscription, the Pluralsight benefit is available as long as the subscription lasts.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64e41abd-81dd-4dd2-d2d2-6bc513ad9e48
* Version Independent ID: 911d149e-8d78-b552-12a2-b061e2c1f41c
* Content: [Pluralsight benefit in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-pluralsight#eligibility)
* Content Source: [subscriptions/vs-pluralsight.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/vs-pluralsight.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@Tiglat1 -- thank you for bringing this to our attention.

@evanwindom -- please look into this issue.

**Comment by WilliamAntonRohm** [comment]
This issue is being tracked in https://ceapex.visualstudio.com/CEINTL/_workitems/edit/535301.
