### ISSUE TITLE
Rebase picture is incorrect

### ISSUE THREAD

**Issue by Wzshun** [MicrosoftDocs/visualstudio-docs#7379]
In section 'rebase', the picture has mistake, should be highlight **Rebase ‘New_Feature’ onto ‘main’**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e59f7c3-34dd-c376-9b0c-54601abe6c33
* Version Independent ID: 3e59f7c3-34dd-c376-9b0c-54601abe6c33
* Content: [Manage a repo in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/version-control/git-manage-repository?view=vs-2022)
* Content Source: [docs/version-control/git-manage-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/version-control/git-manage-repository.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Taysser-Gherfal
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Taysser-Gherfal FYI on this.

**Comment by TerryGLee** [comment]
@Wzshun Thanks for letting us know! We'll get this fixed shortly.

**Comment by TerryGLee** [comment]
@Wzshun We've fixed the screenshot; we'll close this issue now with our thanks to you for your help with improving the documentation!
