### ISSUE TITLE
All or part of System.DateTime?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#738]
> The System.DateTime class provides the current time, which is not under the control of IntelliTest.

It only provides it if I use `DateTime.Now` or `DateTime.UtcNow`. If I'm testing a class like this..

```
public class TestTarget
{
   public DateTime AddSomething(int minutes)
   {
       return GetNow().AddMinutes(minutes);
   }
   
   protected virtual DateTime GetNow()
   {
     return DateTime.Now();
   }
}
```

and I use a virtual class like this....
```
public class TestTargetUnitTestClass
{
  public DateTime When {get;set;}
  protected override DateTime GetNow()
  {
     return When;
  }
}
```

and create a unit test to instantiate `TestTargetUnitTestClass` but to test `AddSomething`, is intellitest going to think that this is non-deterministic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afd1b2f6-e89f-ecdb-0060-de0c7e43d110
* Version Independent ID: 9195e48c-d85e-d940-519a-c3642d17aa33
* Content: [Overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/intellitest-manual/introduction#the-hello-world-of-intellitest)
* Content Source: [docs/test/intellitest-manual/introduction.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/intellitest-manual/introduction.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@AbhitejJohn Could you comment on this question?

**Comment by AbhitejJohn** [comment]
@StingyJack : This is a pretty old issue. I'm assuming you've already understood that the answer for this is a non-deterministic analysis because AddSomething does call DateTime.Now in GetNow(). Please feel free to report any issues you have with this workflow as such on developer community.

**Comment by StingyJack** [comment]
I think I was trying to figure out how to substitute the derived class (or something like it) in place of the base class in order to  let Intellitest continue to find permutations. But like you said, it was a while ago and I don't remember specifically.
