### ISSUE TITLE
TargetFrameworkVersion entries for dotnet core/5/6 are missing

### ISSUE THREAD

**Issue by jeremy-visionaid** [MicrosoftDocs/visualstudio-docs#7382]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ac034a-a498-f3e3-28d0-175b6fead219
* Version Independent ID: 747194a8-ffcf-60b3-b525-6f8fe00066a2
* Content: [Configure unit tests with a .runsettings file - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2022)
* Content Source: [docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/configure-unit-tests-by-using-a-dot-runsettings-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AbhitejJohn Abhitej, it looks like this issue refers to the example section:

```xml
<!-- Framework35 | [Framework40] | Framework45 -->
    <TargetFrameworkVersion>Framework40</TargetFrameworkVersion>
```

I see in the table that **FrameworkCore10** is used for .NET Core sources, but what is the valid value for .NET 5/6?

**Comment by nohwnd** [comment]
The values to be used are either the full name of the framework, or the framework moniker which developers are familiar from csproj `<TargetFramework>`. Nuget.Frameworks is used to parse those values, so there is no finite set of values to list, but it is at least the currently available versions of .NET and .NET Framework. Values that are not currently valid, are still parsed as long as they start with `net` e.g. net11.0, or net9999. Values that are not a valid moniker fail the run.

```xml
<TargetFrameworkVersion>.NETFramework,Version=v4.7.2</TargetFrameworkVersion>
<TargetFrameworkVersion>.NETCoreApp,Version=v6.0.0</TargetFrameworkVersion>

<TargetFrameworkVersion>net472</TargetFrameworkVersion>
<TargetFrameworkVersion>net6.0</TargetFrameworkVersion>
```

**Comment by nohwnd** [comment]
No, it does not sound silly. You are absolutely right. #7782.
