### ISSUE TITLE
There is no tool menu to start with.....

### ISSUE THREAD

**Issue by kasiakolo27** [MicrosoftDocs/visualstudio-docs#7385]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00e3e8d0-48c3-3df6-8aeb-acd9624ffcd5
* Version Independent ID: 13f5da30-9f06-236f-4110-b6a172c52d1f
* Content: [Word wrap - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/how-to-manage-word-wrap-in-the-editor?view=vs-2022)
* Content Source: [docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/how-to-manage-word-wrap-in-the-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@kasiakolo27 You can find Tools from the menu bar, here:

![image](https://user-images.githubusercontent.com/23244653/144914320-a4f4d4e2-3ec9-4b45-aede-a0acadade902.png)

I'll add some info to the topic that describes exactly where the Tools menu is; the update will appear later today. And, thanks for your help with improving our documentation!

**Comment by kasiakolo27** [comment]
[image: Screenshot 2021-12-06 at 21.15.06.jpg]
