### ISSUE TITLE
article does not explain what to do about MSB3327 in devops pipeline use case

### ISSUE THREAD

**Issue by FocusedWanderer** [MicrosoftDocs/visualstudio-docs#7388]
MSB3327 warning thrown in azure devops pipeline, but no 'current user certificate store' exists in pipeline build to add cert into.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ed6eb12-2e14-2818-f26b-334e50bc512a
* Version Independent ID: a1e372ab-4b19-8d69-3219-b8d1e0e7d176
* Content: [MSB3327 - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb3327?view=vs-2022)
* Content Source: [docs/msbuild/errors/msb3327.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb3327.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@FocusedWanderer Thanks for your issue report. We're investigating.

**Comment by ghogen** [comment]
In a devops pipeline context, you could use the [certutil](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/certutil) command-line tool.

```
certutil –f –p [certificate_password] –importpfx <path to pfx file>
```
