### ISSUE TITLE
How to create multiple solutions like the eShopOnContainers sample project

### ISSUE THREAD

**Issue by EmpeRoar** [MicrosoftDocs/visualstudio-docs#739]
Is there a documentation or tutorial how to setup multiple Solutions like the eShopOnContainers sample project?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and Projects in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@EmpeRoar not that I am aware of. Are you wondering how to separate related projects out into different solutions?

**Comment by EmpeRoar** [comment]
Hi @gewarren , I already achieved what I wanted to implement using dotnet cli. Thanks you. 👍
