### ISSUE TITLE
Startup cannot find a browser instance

### ISSUE THREAD

**Issue by kevinkeadle** [MicrosoftDocs/visualstudio-docs#7392]
When following the steps exactly using Visual Studio 2022 version 17.0.1, the project cannot find an instance of the browser when starting even though the OS has the selected browser installed.

I believe this error comes about when Chrome is not installed on the OS because the React UI defaults to Chrome. Even selecting Edge or Firefox at the end of the documented steps will not fix the issue.

To fix the issue, PRIOR to adding the ASP.NET Web API project, select an alternate browser which *is* installed on the OS as the startup for the React project. *Then*, add the ASP.NET Web API project and proceed with all of the documented steps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022#feedback)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@kevinkeadle Thanks, I can add that as a workaround.
