### ISSUE TITLE
No Git menu in VS2022

### ISSUE THREAD

**Issue by Bob-HL** [MicrosoftDocs/visualstudio-docs#7397]
Is this document outdated, or there is a bug in VS2022? I have a fresh installation of VS2022 Enterprise with Git component, but I couldn't find the Git menu. When I select File => Clone Repository..., nothing occurred.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47681749-a303-6964-5aaf-50669805b780
* Version Independent ID: 47681749-a303-6964-5aaf-50669805b780
* Content: [Clone a repo in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/version-control/git-clone-repository?view=vs-2022)
* Content Source: [docs/version-control/git-clone-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-clone-repository.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by Bob-HL** [comment]
Found out the cause: there is a need to set Git as the source control plug in within the Options (for me TFVC was set). It will help to mention this in the document.

**Comment by TerryGLee** [comment]
@Bob-HL Thanks for letting us know about the issue you experienced, and also for providing the workaround! We've taken your advice and added that info to the page; it'll be published later this afternoon. We'll close this issue now, with our thanks to you for your help with improving the documentation. Cheers!

**Comment by WilliamAntonRohm** [comment]
@SomeTroglodyte -- thank you for your follow-up.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
