### ISSUE TITLE
“Repository contains no commits. For managing branches you've to do an initial commit first.” when trying to publish a new project.

### ISSUE THREAD

**Issue by francoscarpa** [MicrosoftDocs/visualstudio-docs#7399]
I’m following the steps to [publish a new project](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository?view=vsmac-2019#publishing-a-new-project) from Visual Studio for Mac, but after doing the first commit and going to the <kbd>Version Control</kbd> > <kbd>Review and Commit</kbd> option, I get the following prompt:

<img width="277" alt="Screenshot 2021-12-08 at 16 06 03" src="https://user-images.githubusercontent.com/9530051/145231743-585bba21-7888-43f5-94ca-2fdf5e967a53.png">

However, going to the <kbd>Version Control</kbd> > <kbd>View Repository History</kbd>, I see my first commit.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 606d4c70-3daf-8b03-9c31-b690927a7136
* Version Independent ID: 24a13aaf-3d14-c810-182c-2c2d93fc299b
* Content: [Setting up a Git Repository - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/set-up-git-repository?view=vsmac-2019)
* Content Source: [mac/set-up-git-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/set-up-git-repository.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by francoscarpa** [comment]
I upgraded Visual Studio for Mac and now I’m able to publish a new project.

**Comment by ngshukun** [comment]
hi what do you meant by you upgraded VS? you bought the full licence?

**Comment by kushalvaghani8** [comment]
not sure if it'll help but I had same issue after today's update. I did a couple of commits and then restarted VS, went to manage branches and remote, and it went through without giving this error.

**Comment by ngshukun** [comment]
Still cannot, everything works fine when I switch to window is, not sure if this is Mac VS issue

Regards
Shu Kun

________________________________

**Comment by kushalvaghani8** [comment]
that's strange - I did that on Mac and it worked for me.
