### ISSUE TITLE
Python Environment selection is missing

### ISSUE THREAD

**Issue by mstibel** [MicrosoftDocs/visualstudio-docs#740]
I have followed the tutorial and the first attempt didn't work. Digging into the configuration, I realized that my Visual Studio selected by default Python 3.6 (64-bits) as the environment for the Python application, so the 32-bit C++ pyd library was not recognized as a valid dll. Changing Python Environments to a compatible 32-bit one, did the work. Adding this step in the Create Python Application section would help others to avoid this error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Working with C++ and Python in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks for reporting the issue. I'll include a note in my next set of revisions.

**Comment by kraigb** [comment]
The addition is live now.
