### ISSUE TITLE
ProjectReference and transitivity 

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#7401]
---
**Issue moved from dotnet/docs#27305**
- Please respond to @nkolev92.

---

_From @nkolev92 on Monday, November 29, 2021 6:01:21 PM_

**Issue description**

ProjectReference items work different in .NET (Core) world vs the standard csproj, .NET Framework world. 

In particular, the ProjectReference in .NET (Core) are transitive. 

For example, say you have:

Project 1 -> Project 2 -> Project 3.

In .NET Framework, Project 1 won't be able to consume Project 3 and code against it.

In .NET Core, Project 1 will be able to consume Project 3 and code against it. 

I might've missed, so if I did a pointer would be great, https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#projectreference. 

**Target framework**

- [ ] .NET Core
- [ ] .NET Framework
- [ ] .NET Standard

<details>
<summary><strong>dotnet --info output</strong> or <strong>About VS info</strong></summary>

```console
<replace>
```
</details>

**Comment by WilliamAntonRohm** [comment]
@nkolev92 -- Nikolche, thank you for your feedback.

@ghogen -- Gordon, please look into this issue.

**Comment by nkolev92** [comment]
Is there a link to the change?

I get this question often, so I want to be able to share the doc instead :)

**Comment by WilliamAntonRohm** [comment]
@nkolev92 -- Nikolche, thank you for your question.  The new information is in the note at the end of this section:
- [ProjectReference](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022#projectreference)
