### ISSUE TITLE
Reference to Vista should be updated.

### ISSUE THREAD

**Issue by FletcherJohnsonZ** [MicrosoftDocs/visualstudio-docs#7406]
You may want to update the section that starts with:
Embed manifest with default settings. Supports the typical manner in which Visual Studio operates on Windows Vista, 

Recommendation: Remove "Vista" from the above so the content does not appear out of date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: db2f3877-b9ea-1ee4-b4ab-ec146139cf5b
* Version Independent ID: b9e98d4e-1053-4ac3-f1f0-a31c12e72f6f
* Content: [Application page of C# project properties - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/application-page-project-designer-csharp?view=vs-2022)
* Content Source: [docs/ide/reference/application-page-project-designer-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/application-page-project-designer-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
