### ISSUE TITLE
Create an offline installation of Visual Studio 2017 (Community)

### ISSUE THREAD

**Issue by gremlinsmasher** [MicrosoftDocs/visualstudio-docs#741]
1. Download the Visual Studio Community 2017 installer
2. Go to the installer Folder file where you download it. Usually it is C:\Users\<YourAccountName>\Downloads
3. Go to the top of the Explorer and type in cmd
4. Type mkdir vs2017
5. Type vs_Community.exe --lang en-en --layout f:\vs2017 --all

5 lines of instructions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an Offline Installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gremlinsmasher** [comment]
Type vs_Community.exe --lang en-us --layout f:\vs2017 --all 

I used the same command last year but forgot the command. I have to look it up again and copy the command from stackoverflow. The person typed in en-en instead of en-us. lol

**Comment by TerryGLee** [comment]
@gremlinsmasher Thanks for your contribution. FYI: You can also find further examples on the following page: [https://docs.microsoft.com/visualstudio/install/install-vs-inconsistent-quality-network](https://docs.microsoft.com/visualstudio/install/install-vs-inconsistent-quality-network). 

Cheers,
~ Terry

**Comment by gremlinsmasher** [comment]
You are welcome. Thank you for posting.

**Comment by LeFiend** [comment]
Can I edit what components I can add?

**Comment by lowiza** [comment]
how to create an installation when i already downloaded it not using cmd

**Comment by arvindsoniindia** [comment]
Can we download only some part of it not MSDN in Visual Studio 2017 (Community) because it full size around 30gb

**Comment by TCB13** [comment]
> Can we download only some part of it not MSDN in Visual Studio 2017 (Community) because it full size around 30gb

Yes you can, instead of `--layout f:\vs2017 --all` you can do something like this:

`vs_community.exe --layout c:\vs2017 --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --lang en-US`

To discover the actually names of what you need you can run a normal setup of VS with everything you need and then export a `.vsconfig` file from there. Open the file and you'll see the names of everything you installed. Here is mine:

```
{
	"version": "1.0",
	"components": [
		"Microsoft.VisualStudio.Workload.NativeDesktop",
		"microsoft.visualstudio.component.debugger.justintime",
		"microsoft.visualstudio.component.vc.diagnostictools",
		"microsoft.visualstudio.component.vc.cmake.project",
		"microsoft.visualstudio.component.vc.testadapterforboosttest",
		"microsoft.visualstudio.component.vc.testadapterforgoogletest",
		"microsoft.component.vc.runtime.ucrtsdk",
		"microsoft.visualstudio.component.windows81sdk",
		"microsoft.visualstudio.component.vc.atlmfc",
		"microsoft.visualstudio.component.vc.cli.support",
		"microsoft.visualstudio.component.vc.140",
		"component.linux.cmake"
	]
}
```

Just use the `--add` flag to add what you need.

**Comment by anuradha27** [comment]
where to find the offline folder after creating offline installer for visual studio 2017 ?

**Comment by JohnDoit2** [comment]
Thank you for the commands, it was helpful. However there is a small error that I was able to fix. The fifth line the command "Type vs_Community.exe --lang en-en --layout f:\vs2017 --all" --lang en-en is wrong it is supposed to be "--lang en-us" or "--lang en-uk" and so on.

**Comment by gremlinsmasher** [comment]
Yes, it was a typo. Thanks

**Comment by HaashimButt167** [comment]
hi there m new here its my first time on github platform...
well i wanna know i want to install vs2017 offline. Issue is my internet is so slow and i want to install vs2017 in my computer lab in which there are more than 50 computers so my question is.. is this article solve my problem or not ???

**Comment by HaashimButt167** [comment]
![Untitled](https://user-images.githubusercontent.com/55978107/65866737-c61a8a00-e38e-11e9-8795-ac76a8c51000.png)
look here i am following the same 5 instructions... !!
after this i just have to copy this vs2017 folder to where i want to install and run the setup file is that right ????

**Comment by nosware1** [comment]
Download [visual studio 2017 offline installer ](https://www.nosware.com/visual-studio-2017-offline-installer/1528/)from our site
Open downloaded folder and do the following steps
1.Right click and extract the zip file
2. Open the extracted folder and open the folder named certificates
3. Right-click and install all three files and click back
4. Scroll down to the last and double-click on vs setup.exe file and install.
Enjoy!!!!

**Comment by j-martens** [comment]
**Comment above with link to the nosware site was edited to replace the link away from the product downloads back to our official downloads at Microsoft.**
