### ISSUE TITLE
Update for VS2022/.NET 6

### ISSUE THREAD

**Issue by cremor** [MicrosoftDocs/visualstudio-docs#7410]
This page should be updated for VS2022/.NET 6. The information seems to be already documented [here](https://docs.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022) but this page should be updated too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd0b8848-c2af-28e9-28bf-761d1cdf3d6d
* Version Independent ID: 7cc1bef7-ef0c-5c62-2b5f-45910764ba80
* Content: [Supported Code Changes (C# and Visual Basic) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/supported-code-changes-csharp?view=vs-2022)
* Content Source: [docs/debugger/supported-code-changes-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/supported-code-changes-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@cremor Thanks for pointing this out. I will look into possible updates.

**Comment by Mikejo5000** [comment]
@LyalinDotCom Dmitry, it looks like we should update this article. Any thoughts about this?

**Comment by cremor** [comment]
This issue is still relevant.

**Comment by Mikejo5000** [comment]
Updating doc. Article update should be live by end of day today.
