### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bodines1** [MicrosoftDocs/visualstudio-docs#7411]
Link to [Application settings overview (https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/application-settings-overview)] in the [See Also] section is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f461aa-b3ae-4202-4f1f-d1b440f1cd63
* Version Independent ID: 48b9d6c3-3ca8-66c9-32ab-364fdb49ae16
* Content: [ClickOnce and Application Settings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-and-application-settings?view=vs-2019)
* Content Source: [docs/deployment/clickonce-and-application-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/clickonce-and-application-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@bodines1 -- that link is working now.  Thank you for your feedback.
