### ISSUE TITLE
Troubleshooting addition

### ISSUE THREAD

**Issue by dIeGoLi** [MicrosoftDocs/visualstudio-docs#7413]
Troubleshooting: In case you enable Docker support while creating the web API project, the backend will start using the docker profile and not be listening on the configured port 5001. Set your backend as Startup Project, then switch the profile using the launch button drop down to your "yourbackendapp" profile . After that set again to multiple startup projects on the solution context menu. I couldn't figure out where it is saved/configured which profile is started.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@dleGoLi Thanks for the info! I'm adding this workaround to the troubleshooting section.
