### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by qsdfplkj** [MicrosoftDocs/visualstudio-docs#7414]
In the text there is this paragraph:
A solution that has a modeling project with a dependency diagram. This dependency diagram must be linked to artifacts in C# or Visual Basic projects that you want to validate. See _Create dependency diagrams from your code_.

The link to https://docs.microsoft.com/en-us/visualstudio/modeling/create-layer-diagrams-from-your-code?view=vs-2022
does not reflect the text: Create dependency diagrams from your code

It looks broken to me.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a25a17b-a48c-f9f1-f61e-6b3e1479a199
* Version Independent ID: 3ccc0a49-c4d3-8c92-1b11-81a4198441d3
* Content: [Validate code with dependency diagrams - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/validate-code-with-layer-diagrams?view=vs-2022#feedback)
* Content Source: [docs/modeling/validate-code-with-layer-diagrams.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/validate-code-with-layer-diagrams.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by WilliamAntonRohm** [comment]
@qsdfplkj -- thank you for your feedback.  That link is working now.
