### ISSUE TITLE
Adding example for static method that takes parameters

### ISSUE THREAD

**Issue by TEC10101** [MicrosoftDocs/visualstudio-docs#7419]
I searched for a while for examples of how to shim a static method that takes parameters.  I suppose I could have researched delegates themselves, but that started to confuse the issue for me.

A simple example like this would be helpful to know to make the shim code's parameters be the same variable names as the real code.

Code Under Test:
`public static MyType GetDataFromStore(Category category, StoreLocation location, string upc)
{
    // implementation that needs to be bypassed because it cannot be ran in the test environment
}`

Shim Code:
`ShimMyClass.GetDataFromStoreCategryStoreLocationString =
                    (category, location, upc) => null;  // or a mock object or something`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b356f491-a828-65ee-915b-b1ccdf71024c
* Version Independent ID: 3fa9dddf-b328-8e2f-c7b2-016a38f71bf6
* Content: [Isolate your app with shims (unit testing) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing?view=vs-2022)
* Content Source: [docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/using-shims-to-isolate-your-application-from-other-assemblies-for-unit-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AbhitejJohn for input on the suggested example.

**Comment by AbhitejJohn** [comment]
That's a good point, we could certainly add another example to make this more clearer. I've logged an internal bug to track this - https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1499726

**Comment by Mikejo5000** [comment]
Closing this in favor of the product work item.
