### ISSUE TITLE
Instructions for enabling hot reload are outdated

### ISSUE THREAD

**Issue by PassivePicasso** [MicrosoftDocs/visualstudio-docs#7427]
In Visual Studio 2019, on version 16.11.2 (possibly other versions as well)
The directions on this page indicate that the HotReload for Xaml controls can be found under Debugging/General
The settings have been moved to Debugging/Hot Reload and the changes required are different.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8368af75-bb65-b3bc-bcbc-67a2739e5bc3
* Version Independent ID: f6142191-d659-83f2-76a2-6b8afda90774
* Content: [Troubleshooting XAML Hot Reload - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-troubleshooting?view=vs-2019)
* Content Source: [docs/xaml-tools/xaml-hot-reload-troubleshooting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xaml-tools/xaml-hot-reload-troubleshooting.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@PassivePicasso You're right; we've updated this page to include the latest info, as follows: 

- For Visual Studio 2019: https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-troubleshooting?view=vs-2019
- For Visual Studio 2022: https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload-troubleshooting?view=vs-2019

We'll close this now, with our thanks to you for your help in improving the documentation!
