### ISSUE TITLE
No contextual option to generate XML from XSD

### ISSUE THREAD

**Issue by mchassy** [MicrosoftDocs/visualstudio-docs#7431]
I opened an industry standard XSD from SWIFT. There is no contextual option to generate a sample XML file.
You don't accept XSDs so I changed the extension to TXT

![image](https://user-images.githubusercontent.com/15926092/146373682-c2373de0-94fc-4a9f-8d19-1d36e86f2fed.png)

---
[MT103.txt](https://github.com/MicrosoftDocs/visualstudio-docs/files/7727281/MT103.txt)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39783221-4553-f01b-7c14-ac8dc737fda4
* Version Independent ID: bc10071a-5d64-57bf-3880-485828a54cdb
* Content: [How to: Create an XML Document Based on an XSD Schema - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/xml-tools/how-to-create-an-xml-document-based-on-an-xsd-schema?view=vs-2022)
* Content Source: [docs/xml-tools/how-to-create-an-xml-document-based-on-an-xsd-schema.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xml-tools/how-to-create-an-xml-document-based-on-an-xsd-schema.md)
* Product: **visual-studio-windows**
* Technology: **vs-xml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@mchassy -- Mark, thank you for your feedback.  This repo is solely for documentation issues, and this appears product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
