### ISSUE TITLE
Using task list page is outdated 

### ISSUE THREAD

**Issue by angelica-serafini-cko** [MicrosoftDocs/visualstudio-docs#7441]
Verified using: Visual Studio Code version 1.63.0
Referring to this page:  https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2022

Current GUI has changed for task list, it is not available under View Menu but under the Activity bar

Issue 01
Title:  The Task List window
Paragraph: "When Task List is open, it appears at the bottom of the application window.
To open Task List, select View > Task List, or from the keyboard press Ctrl+\,T. "

Description:
Currently on this Studio Code version there is no View > Task list option anymore but available in the Activity Bar
 keyboard shortcut does not work or not valid anymore  (https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2022)

Issue 02
Title:  Custom tokens
Paragraph: "To create a custom token:
On the Tools menu, choose Options.
Open the Environment folder and then choose Task List. "

Description: Tool menu is not available hence could not find how to create a custom token

I don't believe that this is the only document page that should be updated - please update with the correct interface steps
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93b78b04-7dd5-453e-de60-8cdd16594a99
* Version Independent ID: 27ddd786-e4c5-2b2e-e7c8-e103745dd656
* Content: [Task List, Environment, Options Dialog Box - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/task-list-environment-options-dialog-box?view=vs-2022)
* Content Source: [docs/ide/reference/task-list-environment-options-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/task-list-environment-options-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@angelica-serafini-cko The problem you describe is for [Visual Studio Code](https://code.visualstudio.com/) (which includes a text editor), but the content you visited is for [Visual Studio](https://docs.microsoft.com/visualstudio/get-started/visual-studio-ide?view=vs-2022) (which includes a fully integrated development environment). In other words, these are two separate products in the [Visual Studio family](https://docs.microsoft.com/en-us/visualstudio/?view=vs-2022). 

However, here is a Visual Studio Code page that might help you with the problem you describe: https://code.visualstudio.com/Docs/editor/tasks.

We'll close this issue now; thanks for reaching out and we hope that the link helps you with the issue that you described.
