### ISSUE TITLE
Error in "Capture and implicitly number the expression contained within parenthesis" Example

### ISSUE THREAD

**Issue by greyknight79** [MicrosoftDocs/visualstudio-docs#745]
To use the capture group the syntax is "$1" not "\1".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Using Regular Expressions in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/using-regular-expressions-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@greyknight79 thanks for the feedback. I tested this out and the regular expression works as defined. \1 does refer back to the first defined group. My understanding is that \number refers back to a group within a regular expression, and $number refers to a group in a *[replacement pattern](https://docs.microsoft.com/en-us/dotnet/standard/base-types/substitutions-in-regular-expressions#substituting-a-numbered-group)*.

**Comment by gewarren** [comment]
Please reopen if you disagree.
