### ISSUE TITLE
Remove and Sort Usings Settings?

### ISSUE THREAD

**Issue by vaughn-pworx** [MicrosoftDocs/visualstudio-docs#7452]
Aren't there some settings that can help sort these in different ways? For example, how would you set this up to put the "system" using declarations first, followed by the project or 3rd party references next?

This information is available elsewhere online, but I think it would be nice if it were mentioned here since this documentation is the first search result for "visual studio remove and sort usings" (good job on SEO!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fd299e-66bc-90cb-f1a6-f5a4a1425cb8
* Version Independent ID: 0c95b38c-e177-9a7a-665d-d720b2c102b8
* Content: [Sort usings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/sort-usings?view=vs-2022)
* Content Source: [docs/ide/reference/sort-usings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/sort-usings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mikadumont** [comment]
Added a screenshot and explanation of the option: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9794
