### ISSUE TITLE
New text editor option "Show bidirectional text control characters" in VS 2019/2022 is not documented.

### ISSUE THREAD

**Issue by MikeDiack** [MicrosoftDocs/visualstudio-docs#7458]
The new tools editor option (new in VS 2019 16.11.8 and VS 2022 17.0.3 and later) "Show bidirectional text control characters" (to prevent the Trojan Source Code attack), is not shown in this help page.

See here for background reading:
https://certitude.consulting/blog/en/invisible-backdoor/
https://trojansource.codes/

See release notes here:
https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes#17.0.3
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.11.8

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.General)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@MikeDiack Thanks for letting us know; we appreciate it. We've added the _**Show bidirectional text control characters**_ option to the "Display" section of the [Options dialog box: Text Editor > General](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?view=vs-2022#display) page, where we also updated the screenshot, too. We'll close this issue now, with our thanks to you for helping improve the documentation.
