### ISSUE TITLE
What are the legitimate values for PexAssemblySettings(TestFramework) ? 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#746]
"Naked" and "MSTestv2" are the values I've come across, but what are acceptable and what doesnt work?

Also the value "Naked" is bound to be offensive to someone and probably should be changed. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e934d62b-8c75-5a3e-d6d4-fa35b4d51743
* Version Independent ID: c622c8c0-accb-bb9d-4686-164a43b46b96
* Content: [Attribute glossary - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/intellitest-manual/attribute-glossary#pexassemblysettings)
* Content Source: [docs/test/intellitest-manual/attribute-glossary.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/intellitest-manual/attribute-glossary.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@StingyJack thanks for the feedback. @pvlakshm can you answer this one?

**Comment by StingyJack** [comment]
I couldnt find anything that used the value when poking around in ILspy. (And FWIW, I dont choose to be offended by the word.)

**Comment by gewarren** [comment]
@kendrahavens Do you know who would be able to answer this question?

**Comment by kendrahavens** [comment]
@AbhitejJohn May be able to shed some light.

**Comment by AbhitejJohn** [comment]
@StingyJack : Currently those values are generated by extensions, MSTestv2 is one of those that is installed by default. [This ](https://docs.microsoft.com/en-us/visualstudio/test/generate-unit-tests-for-your-code-with-intellitest?view=vs-2019#q-can-i-use-other-unit-test-frameworks-with-intellitest) link has a few more.

**Comment by StingyJack** [comment]
@AbhitejJohn - so the test runner would be supplying a constant to use for that value?
