### ISSUE TITLE
The keyboard shortcuts page should not explain what a command does by expanding the command ID in the English Language

### ISSUE THREAD

**Issue by TryerGit** [MicrosoftDocs/visualstudio-docs#7470]
Consider webpage: https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/default-keyboard-shortcuts-in-visual-studio.md

An amateur using Visual Studio for the first time, even if English is not his first language, can reasonably be expected to know that command "Edit.BreakLine" is supposed to, well, "Break Line". This is not rocket science.

What he is possibly expecting from a professionally maintained website is to know what exactly the command *does* and how this command behaves differently from the command "Edit.BriefBreakLine", which is another command that is available in Visual Studio.

Can some effort be put in by the folks that maintain this website (this will require coordinating with Visual Studio developers and sitting down with them and have them break down each and every command to figure out what is actually going on) so that users are not left having to guess what each command does ?

For e.g., in a different (and better) universe, I might expect that there is a brief video demonstration / gif to accompany each command that visually shows what it is expected to do.

Another example is: How is Window.PreviousDocumentWindow different from Window.PreviousDocumentWindowNav ? The column titled "Command" is of zero utility in this regard.

I am disappointed to note that on the webpage I linked to, column "Command" is useless waste of internet bandwidth since it is just repeating what is already stated in column "Command ID"

Thanks.

----

Edited to add: See similar questions that are as yet unanswered from Visual Studio users below:

https://stackoverflow.com/questions/69053610/how-does-visual-studios-underware-brief-commands-emulation-compare-to-emacs-and

https://stackoverflow.com/questions/70489299/visual-studio-ide-difference-between-commands-that-differ-slightly

**Comment by TerryGLee** [comment]
@TryerGit Thanks for your detailed response. Respectfully, the point of including the Command IDs on the [Keyboard shortcuts in Visual Studio](https://docs.microsoft.com/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2022) page is not to provide a comprehensive list of Command IDs, but instead, they're there to help those who change/personalize their default keyboard shortcuts with a way to map them back to the original Command ID, should they run into conflicts.

What you're asking for would not apply to this page and would instead, constitute a larger content request. We'll take it under advisement, but meanwhile we'll close this issue as it's linked to a page that does not require updating in the manner in which you've described.

We do appreciate your feedback, however. We've logged it internally for further consideration.
