### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by CraigAP** [MicrosoftDocs/visualstudio-docs#7473]
In Step 3-2: Serve static files from your app, the html for the index.html file says to use "load staticfiles".  For me, that fails, but using "load static" works.

The documentation at https://docs.djangoproject.com/en/3.0/howto/static-files/#configuring-static-files 
says to use "load static".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a1cd413-a2a8-9cb5-3f3a-94822a96af51
* Version Independent ID: feadb7ab-ebba-051d-e68c-a758235ce514
* Content: [Learn Django tutorial in Visual Studio step 3, static files and pages](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages?view=vs-2022)
* Content Source: [docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/learn-django-in-visual-studio-step-03-serve-static-files-and-add-pages.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by WilliamAntonRohm** [comment]
#reassign @rjmolyneaux 

@rjmolyneaux -- Ryan, please review [private PR 9318](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9318).
