### ISSUE TITLE
DebuggerVisualizer with code stepping support

### ISSUE THREAD

**Issue by Atma9** [MicrosoftDocs/visualstudio-docs#7476]
Dear All,

The DebuggerVisualizer attribute would be most useful, if it would allow the visualization window to remain open, while stepping through the code and auto updating the content of the open window. Even the current interface would be OK, if the debugger would be resending variable data to all not-closed visualizers for every F10 or F11. 

Is this possible in VS.IDE? Which API is to be used to make that work?

Thanks!
Atmapuri

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edb4b6f3-7c88-077e-26a6-c840c7081bd0
* Version Independent ID: 03b40f67-739c-dbcf-4a88-2ab8e9d1313b
* Content: [Create custom data visualizers - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2022)
* Content Source: [docs/debugger/create-custom-visualizers-of-data.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/create-custom-visualizers-of-data.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Atma9 -- Atmapuri, please see my response in #7475.
