### ISSUE TITLE
The page layout makes it hard to read table content even at 1920x1080

### ISSUE THREAD

**Issue by Anton-V-K** [MicrosoftDocs/visualstudio-docs#7477]
Here is how the [page](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019#azure-development) looks at 1920x1080 in Vivaldi browser:
![147562552-3e900229-4173-4990-9ac6-cf833592b2fa-crop](https://user-images.githubusercontent.com/20116984/147563463-6d46024c-b991-43f8-b6bc-e08b71c5ce69.png)

You should use the horizontal scroll bar (which is at the bottom of the table!) to view the info in a row.
In the same time the left and right "panels" occupy the limited space and cannot be hidden, though their information is redundant while you're viewing the workloads list.
Redesing the layout so both left and right "panels" can be hidden.

I already sumbitted similar issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/5558 more than a year ago, and though my screen resolution increased since then, the page is still unfriendly :(

If the issue should belong to other list, please, move it there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4891ebc9-fdea-c376-94f6-17295ca275d7
* Version Independent ID: ccc61918-cc18-a7ff-cc6c-8659d6c9c78a
* Content: [Visual Studio Community workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2019#feedback)
* Content Source: [docs/install/workload-component-id-vs-community.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/workload-component-id-vs-community.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@Anton-V-K -- thank you for your follow-up.  You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

I am closing this issue now.  You are welcome to @ mention me for any followup.
