### ISSUE TITLE
Shouldn't you at least mention that VS Emulator for Android has been abandoned by Microsoft?

### ISSUE THREAD

**Issue by Britford** [MicrosoftDocs/visualstudio-docs#748]
It seems that this emulator has been abandoned and if so, that should top this article.

https://stackoverflow.com/questions/44864647/running-api-level-24-on-vs-emulator-for-android-hyper-v

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6bdda1ea-471b-6285-427f-4b14a44de863
* Version Independent ID: 0f51f444-6bad-3e06-928d-dbd70f2cc4b8
* Content: [Visual Studio Emulator for Android - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/cross-platform/visual-studio-emulator-for-android)
* Content Source: [docs/cross-platform/visual-studio-emulator-for-android.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/cross-platform/visual-studio-emulator-for-android.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Yes, we do need to say something about that. Thanks. In some VS tooling, the VS Emulator for Android is no longer available, so it's less of an issue.

**Comment by Mikejo5000** [comment]
Revising the note and making this information more prominent.

**Comment by Britford** [comment]
Thank you and have a great weekend!
