### ISSUE TITLE
Incorrect instructions for retrieving the download script

### ISSUE THREAD

**Issue by jameswestgate** [MicrosoftDocs/visualstudio-docs#7480]
It appears the documentation was written for a windows user when downloading the script in the first step. This is highly unlikely, since this page is for M1 Mac users. Following the instructions will cause the user to download an html version of the script instead.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09335e11-79f7-cb3d-e62f-6c8297093e61
* Version Independent ID: 09335e11-79f7-cb3d-e62f-6c8297093e61
* Content: [Visual Studio for Mac 8.10 and .NET on Apple Silicon machines - Visual Studio for Mac](https://docs.microsoft.com/en-gb/visualstudio/mac/uninstall-net-2019?view=vsmac-2019)
* Content Source: [mac/uninstall-net-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/uninstall-net-2019.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by j-martens** [comment]
#reassign:@jmatthiesen
