### ISSUE TITLE
Make each step deep-linkable

### ISSUE THREAD

**Issue by zivkan** [MicrosoftDocs/visualstudio-docs#7481]
I frequently need to redirect customers to this page, and tell them "Use record your actions, as shown in step 8". I think it would be easier if step 8 is deep-linkable. Also consider a more detailed section about recording the actions, and shows clicking the record button and clicking stop again at the end.

As an engineer working on Visual Studio, these recordings are tremendously useful to understanding some bugs, and occasionally customers don't understand what we're asking for, even when we link to this docs page, unless we explicitly call out step 8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [How to report a problem with Visual Studio - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by zivkan** [comment]
It's my turn in my team's support rotation again this week, and I've needed to ask customers 3 times to record their steps, so I have to really point out step 8 in this list. If there's another docs page where there's more information about the "record your actions" process, I can't find it.

Also, the docs page doesn't actually use the same words as the feedback tool. The screenshot shows "record your actions to reproduce the issue", but doing a text search for "record your actions" on the docs page doesn't have any hits.

**Comment by WilliamAntonRohm** [comment]
@zivkan -- Andy, thank you for your follow-up.  We have updated this article with your suggestions, and it should be live by tomorrow.
