### ISSUE TITLE
C++ debugging tutorial page refers to multiple versions of Visual Studio

### ISSUE THREAD

**Issue by SamVanheer** [MicrosoftDocs/visualstudio-docs#7482]
This tutorial page refers to multiple versions of Visual Studio at the same time. It should only refer to a single version (the one that the page is linked to in the version drop-down). It also duplicates this line:
```
If you haven't already installed Visual Studio, go to the Visual Studio downloads page to install it for free.

If you haven't already installed Visual Studio 2022, go to the Visual Studio 2022 downloads page to install it for free.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27c156a7-933c-1a70-6cc7-b0ae2d1d4a8c
* Version Independent ID: 4ffdd3f4-03d9-655f-f77d-fa66338e740f
* Content: [Tutorial: Debug C++ code - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/getting-started-with-the-debugger-cpp?view=vs-2022)
* Content Source: [docs/debugger/getting-started-with-the-debugger-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/getting-started-with-the-debugger-cpp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@SamVanheer -- Sam, my apology for the delay.  I have updated the documentation and it should be live by tomorrow.
