### ISSUE TITLE
/Build (devenv.exe) Documentation Inaccuracy

### ISSUE THREAD

**Issue by AndrewNRe** [MicrosoftDocs/visualstudio-docs#7484]
![DOCERROR](https://user-images.githubusercontent.com/53196429/147835488-d43b82c5-e853-4a15-9580-a2b24d7a7861.JPG)

The _SolutionName_ part of the 2019 compiler documentation states, "Required. The full path and name of the solution file." when in reality you only need to be relative to the solution's directory.

So if you were to on the command line after having set up the environment variables to use devenv
cd directory_of_sln_file
devenv sln_file.sln

This works just fine, so you don't need to write the _full path and name of the solution file_ like

devenv directory_of_sln_file\sln_file.sln

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 977d821f-ce22-b324-8348-a3777e476e37
* Version Independent ID: 86413bc0-26dc-5bfb-0bdd-9471b9c8a26a
* Content: [-Build (devenv.exe) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/build-devenv-exe?view=vs-2019)
* Content Source: [docs/ide/reference/build-devenv-exe.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/build-devenv-exe.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- Terry, please review this clarification in [private PR 9319](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9319).
