### ISSUE TITLE
Don't just build the project - you must run it after the first build

### ISSUE THREAD

**Issue by JamieL22** [MicrosoftDocs/visualstudio-docs#7488]
Before running the Data Source Configuration Wizard from the Add New Data Objects, run the project.  This way, the table falues under WPF_EF (Customers, Orders, and OrderDetails) will appear and allow you to check them.  In the instructions, it says Build the project (Ctrl-Shift-B), but what needs to happen at that point is to run the project once.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c0fa43-0ca5-9c86-f8c4-4b3eb7176250
* Version Independent ID: bb93e3ff-0d52-9e93-c3a8-545b16f03a30
* Content: [Simple data app with WPF and Entity Framework 6 - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2019)
* Content Source: [docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@JamieL22 
Thanks, I will confirm and update as appropriate.
