### ISSUE TITLE
Mention that not all editions support Live Unit Tests

### ISSUE THREAD

**Issue by ffes** [MicrosoftDocs/visualstudio-docs#749]
At https://github.com/MicrosoftDocs/visualstudio-docs/blame/master/docs/test/getting-started-with-unit-testing.md#L66 there is no mention that the Enterprise Edition of VS is required for Live Unit Testing.

**Comment by gewarren** [comment]
@ffes thanks for the feedback. I will try to make the edition requirements for LUT clearer.
