### ISSUE TITLE
Visual Studio - Tools > Options > Text Editor > Advanced: Missing

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/visualstudio-docs#7494]
The entire documentation for Visual Studio: `Tools > Options > Text Editor > Advanced is missing`.

When you click the question mark at the top right of the settings dialog you end up on the documentation for `Visual Studio: Tools > Options > Text Editor > General`.

![image](https://user-images.githubusercontent.com/7513795/148063122-05e4cad6-18ba-497c-a922-ca4fa2a5f299.png)

![image](https://user-images.githubusercontent.com/7513795/148063895-5ea664c6-68df-4aab-a23a-1e398710a6a0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.Advanced)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Bartolomeus-649 This previously missing page is now published; see [Options dialog box: Text Editor > Advanced](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-advanced). We'll close this issue now, with our thanks to you for your interest in improving the documentation for Visual Studio!
