### ISSUE TITLE
GetAssemblyIdentity Task example's XML is not well-formed

### ISSUE THREAD

**Issue by Eagle3386** [MicrosoftDocs/visualstudio-docs#750]
The line that reads `<Target Name="RetrieveIdentities>` is missing a quote sign right before the `>`.
Additionally, the added empty lines are violating the XML specification and therefore should be fixed, too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3945ae26-b64e-b73c-36ca-c99c16445c39
* Version Independent ID: 13a0ec0d-9246-c291-fc94-d65e9e366e1a
* Content: [GetAssemblyIdentity Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/getassemblyidentity-task)
* Content Source: [docs/msbuild/getassemblyidentity-task.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/getassemblyidentity-task.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Eagle3386 Fix in progress. Thanks for the correction!

**Comment by Eagle3386** [comment]
Not fixed as @fenxu's commit 09736cac5e1ea79601c26c66837c0d992b9ab9a3 left [line 49](https://github.com/MicrosoftDocs/visualstudio-docs/blame/master/docs/msbuild/getassemblyidentity-task.md#L49) (sorry for blame-abuse, but GH can't highlight `.md` files) unchanged and XML forbids empty lines.

**Comment by Mikejo5000** [comment]
Removed one additional blank line.

**Comment by Eagle3386** [comment]
@Mikejo5000 Thanks for that!

Though, there are still issues with the docs, so to finally fix this issue, I've created PR #803 and already signed the CLA. Looking forward to your review.
