### ISSUE TITLE
Need a way to automate this

### ISSUE THREAD

**Issue by RaidIsNotABackup** [MicrosoftDocs/visualstudio-docs#7500]
[Enter feedback here]
I need to be able to install the Remote Debugging Tools for 2022 and Enable them to run as a Service with automation.
I can currently run the installer using Ansible or PowerShell just fine but I am not able to start the service since it requires the GUI Wizard to be run.

I do not see any CLI options for the Wizard or any documentation on alternate ways to get this done this is a big issue for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022#bkmk_configureService)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/remote-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@RaidIsNotABackup Hi, to make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

I don't know if the scenario is supported or not, but I believe only the GUI method is doc'ed, so I suggest Report a Problem. Please let me know if you get more information on this. Thanks!

**Comment by Mikejo5000** [comment]
@RaidIsNotABackup Please also take a look at the Help page installed with the Remote Tools:
type msvsmon.exe /? from the command line. There are instructions for command line usage, but I'm not sure, again, whether it supports the service scenario via command line.

See the Note:
https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022#fileshare_msvsmon
