### ISSUE TITLE
This sample does not compile after making change specified in Step 7

### ISSUE THREAD

**Issue by WhiskeyRomeoLima** [MicrosoftDocs/visualstudio-docs#7503]
Error	CS0029	Cannot implicitly convert type 'ConsoleApp_FirstApp.GType.Type' to 'ConsoleApp_FirstApp.GType'	Galaxy ConsoleApp	

referring to the four case statements below.

switch (type)
            {
                case 'S':
                    MyGType = Type.Spiral;
                    break;
                case 'E':
                    MyGType = Type.Elliptical;
                    break;
                case 'l':
                    MyGType = Type.Irregular;
                    break;
                case 'L':
                    MyGType = Type.Lenticular;
                    break;
                default:
                    break;
            }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c335a864-b746-4322-7543-16ff56594ba3
* Version Independent ID: 587465fb-8267-99b5-8cbe-282ade499f7c
* Content: [Debugging code for absolute beginners - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/debugging-absolute-beginners?view=vs-2022&tabs=csharp)
* Content Source: [docs/debugger/debugging-absolute-beginners.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/debugging-absolute-beginners.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@WhiskeyRomeoLima Hi, thanks for the feedback. I can reproduce the CS0029 error if I change the original source code, from:
``` public object MyGType { get; set; }```
to:
``` public GType MyGType { get; set; }```

However, the line of code that needs to change is this one (should be around line 47):
``` public GType GalaxyType { get; set; }```

The doc mentions this correctly, but it's probably a little too easy to edit the wrong line of code. I will consider a possible edit.

**Comment by WhiskeyRomeoLima** [comment]
Thanks. I did finally see my error.  Line numbers would have helped, but I don’t know how you make them so that they do no copy over. 

Bill Lucas
