### ISSUE TITLE
Sections out of order in Unity quick start doc

### ISSUE THREAD

**Issue by JVimes** [MicrosoftDocs/visualstudio-docs#7513]
I think the section "Add a version of Visual Studio that is not listed" needs to go above the section "Install or update the Visual Studio Editor package" for the steps to make sense. The former asks the reader to click Browse, but they've already moved out of the Preferences dialog that has Browse. They're now on the Package Manager, which doesn't.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35176f2-ca94-7bb8-08a5-9e415d364ef3
* Version Independent ID: a9f184a6-78b9-315b-4a02-1c93bd4c3940
* Content: [Quickstart: Install & configure Visual Studio Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity)
* Content Source: [gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by therealjohn** [comment]
@JVimes 

Thank you! I agree and have fixed it. The PR is building now.
