### ISSUE TITLE
Bug in https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp?view=vs-2019

### ISSUE THREAD

**Issue by zhenxuanjameszhang** [MicrosoftDocs/visualstudio-docs#7519]
In the document, the following code are not correct
```
#include <boost/test/included/unit_test.hpp\>
```
It should be
```
#include <boost/test/included/unit_test.hpp>
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f45fbddc-51f2-1c42-eaf2-f78e6220a9e7
* Version Independent ID: 1ce72223-80ab-651a-40f3-dc8112b2a3cf
* Content: [How to use Boost.Test for C++ - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-boost-test-for-cpp?view=vs-2019#add-include-directives)
* Content Source: [docs/test/how-to-use-boost-test-for-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/how-to-use-boost-test-for-cpp.md)
* Product: **visual-studio-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by WilliamAntonRohm** [comment]
@zhenxuanjameszhang -- I have updated the documentation and it should be live by tomorrow.

**Comment by zhenxuanjameszhang** [comment]
Dear William,

Thanks for your quick response on improving documentation!

Regards,
James
________________________________
