### ISSUE TITLE
Defaults are not specified for each optional parameter

### ISSUE THREAD

**Issue by agoln** [MicrosoftDocs/visualstudio-docs#752]
Each optional parameter should specify what the default value is

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb479ee7-d34c-dd5d-6843-4abdec6c3894
* Version Independent ID: 40cd6644-b061-335e-7bd4-6beede753c5d
* Content: [Exec Task - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/exec-task)
* Content Source: [docs/msbuild/exec-task.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/exec-task.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Rainer, is there a good way to identify the default values?

**Comment by rainersigwald** [comment]
No, only reading [the code](https://github.com/Microsoft/msbuild/blob/765affbc5c990d4a5690af1b348e2447609a769d/src/Tasks/Exec.cs). :(

However:

* `IgnoreExitCode` defaults to `false`
* `WorkingDirectory` defaults to the project's current working directory
* `Custom*RegularExpression` default to null (no custom processing)
