### ISSUE TITLE
Automatic Brace Completion

### ISSUE THREAD

**Issue by chund** [MicrosoftDocs/visualstudio-docs#7520]
![image](https://user-images.githubusercontent.com/26091233/148927271-59bc13a6-c37b-4dbf-9bc8-11c64d5b0c68.png)

I cannot find any documentation about the option "Automatic brace completion"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3db88056-66c6-f9ff-a06d-803349f2a488
* Version Independent ID: be8d9066-47a5-db65-f029-d1f95fca4181
* Content: [Options, Text Editor, All Languages - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-all-languages?view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-all-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-all-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@chund Thanks for letting us know. It looks like we're missing a "General" page for C++; we'll look to add that later. Meanwhile, this page might include the information you need, for now: https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-c-cpp-advanced?view=vs-2022#brace-completion

**Comment by chund** [comment]
The "Automatic brace completion" is also missing for the "General" page fpr "All Languages" 

https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-all-languages?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.All_Languages.General)%26rd%3Dtrue&view=vs-2022

**Comment by TerryGLee** [comment]
@chund Thanks; we'll get that updated, too.

**Comment by TerryGLee** [comment]
@chund We've updated the [Options dialog box: Text Editor > All Languages](https://docs.microsoft.com/visualstudio/ide/reference/options-text-editor-all-languages) page based on your feedback. We'll close this issue now, with our thanks to you for helping to improve the Visual Studio documentation!
