### ISSUE TITLE
Informative video

### ISSUE THREAD

**Issue by chuckb35** [MicrosoftDocs/visualstudio-docs#753]
The links to resources were also good. Great documentation page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50836ec0-a917-7b98-5721-560ff38354d1
* Version Independent ID: 8688bd4f-7d01-ea08-945e-8c8e7500cac9
* Content: [Introducing Live Unit Testing - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-intro)
* Content Source: [docs/test/live-unit-testing-intro.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/live-unit-testing-intro.md)
* Service: **unspecified**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by gewarren** [comment]
@chuckb35 thanks for the feedback for @rpetrusha!
