### ISSUE TITLE
Permissions Required to Assign Licenses in Subscriptions Portal

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/visualstudio-docs#7534]
This page says what permissions are required on the Azure side, but doesn't mention if any rights are required in the subscription portal

https://docs.microsoft.com/en-us/visualstudio/subscriptions/admin-responsibilities

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf290c37-d7fa-9d10-b8ef-865647e58a70
* Version Independent ID: 1334b162-8560-5e0a-c874-9439b697dd96
* Content: [Billing FAQ for Visual Studio Visual cloud subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-billing-faq)
* Content Source: [subscriptions/vscloud-billing-faq.yml](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vscloud-billing-faq.yml)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@fowl2 -- James, thank you for your feedback.

@evanwindom -- Evan, please look into this issue.

**Comment by fowl2** [comment]
It appears that after purchasing a license, enough access to the portal is granted to assign the purchased license. Not sure if it's based on who made the purchase or rights to the subscription etc - which would be great to clarify in the document .

**Comment by evanwindom** [comment]
@fowl2 Hi James.  Can you give me a little more context?  Are you talking specifically about cloud subscriptions purchased with Azure?  Are you purchasing as part of Volume License agreements?

**Comment by fowl2** [comment]
Yes, I'm talking about Visual Studio subscriptions purchased with an Azure subscription.

**Comment by evanwindom** [comment]
@fowl2 Hi James -- I thought I had responded to this previously.   My apologies for the horribly long delay here .  I'll have a look through the article and see if I can bring some clarity to the situation.  Thanks again for helping us improve our content.

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger5** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.

**Comment by evanwindom** [comment]
@fowl2 -- Hi James, I apologize for the delay here.  When cloud subscriptions are purchased with an Azure subscription, if you have User Access Administrator rights on the Azure subscription, we automatically pick those up when you sign into the admin portal.  We check on the first sign-in for new admins.  If you have previously assigned subscriptions, we'll check each time you sign in.  If you haven't previously assigned any subscriptions, you may need to add the agreement to the portal before you'll see those subscriptions.  Further information is in this article:  https://docs.microsoft.com/en-us/visualstudio/subscriptions/add-monthly-subs.  I'm going to work with the admin team to include some cross-references in some of the articles so it's easier to find this information.  THANKS for helping us make our content better!
