### ISSUE TITLE
Info for those with private MSDN Enteprise subscriptions

### ISSUE THREAD

**Issue by randomITperson** [MicrosoftDocs/visualstudio-docs#7535]
Team, for those who have or those interested in buying a personal MSDN Enterprise/professional subscription, can you provide some feedback on whether the GitHub Enterprise instance is available to them ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78e0dbc2-35de-0efe-ae1b-b9d2507f2b4d
* Version Independent ID: f1e1caeb-78d3-262f-6311-6606720893a3
* Content: [Visual Studio subscriptions with GitHub Enterprise](https://docs.microsoft.com/en-us/visualstudio/subscriptions/access-github)
* Content Source: [subscriptions/access-github.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/access-github.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@randomITperson  - Thanks for your question.  The GitHub Enterprise license is only available to customers with Enterprise agreements, so purchases through the Microsoft Store, for example, would not qualify.  I have added a new topic to the Frequently Asked Questions to make this clear.

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger5** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.

**Comment by WilliamAntonRohm** [comment]
#please-close
