### ISSUE TITLE
Document keyboard shortcuts for Output Window

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#7536]
I can’t figure out how to control the “Show output from” in Output Window using keyboard shortcuts. Could this be added to the documentation please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d663a2e8-a3e5-e59b-77b1-f035578383ee
* Version Independent ID: fb0f955e-8ec1-d53d-e682-042096539f5f
* Content: [Output Window - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/output-window?view=vs-2022)
* Content Source: [docs/ide/reference/output-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/output-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@binki -- Nathan, thank you for your feedback and question.  Please try this menu item in Visual Studio 2022:
- Tools > Options > Environment > Keyboard

and search for "Output".  Let me know if this helps.

![image](https://user-images.githubusercontent.com/27738025/149586794-187ed982-214d-4351-9346-8d8dad1bb44c.png)

cc @TerryGLee for awareness

**Comment by binki** [comment]
@WilliamAntonRohm Debug.Output lets me assign a shortcut to opening the debug output. However, none of those options provide a way to get to the Show output from dropdown. Surely there must be a way? Or if there isn’t one I need to file a bug?

**Comment by binki** [comment]
I.e., being able to directly pull up Debug Output doesn’t solve my problem. My particular problem would be solved if I could directly load Tests output. But that isn’t generalized.

**Comment by TerryGLee** [comment]
@binki Please take a look at the [Keyboard shortcuts in Visual Studio](https://docs.microsoft.com/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio) page. Let us know if it doesn't include what you're looking for.

**Comment by binki** [comment]
@TerryGLee None of those shortcuts are relevant. They include `View.Output` which raises the Output window but doesn’t let me switch to a different output source. [The above picture](https://github.com/MicrosoftDocs/visualstudio-docs/issues/7536#issuecomment-1013482230) shows `Debug.Output` which raises the Output window in addition to switching it to Debug output, but what I need is to switch to Test output or a way to just generally switch outputs (because arbitrary output categories are added to the “Show output from:” box).

The “Show output from:” label includes a mnemonic for “S”, but the Test menu (near File, Edit, View, Project, …) has “S” as a mnemonic, so alt+s always opens the menu instead of activating the “Show output from:” dropdown.

ctrl+alt+pgup/pgdown and alt+F6 switches to different windows rather than switching the value of “Show output from:”.

I am pretty sure none of those resources describe how to get to the “Switch output from:” box using the keyboard.

**Comment by TerryGLee** [comment]
@binki Thanks for the additional information. From what I can surmise, it doesn't look like there's a keyboard shortcut for what you describe. It might be a good time to request this functionality by using the [Suggest a Feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) tool. When you've filed a ticket, please be sure to circle back to this issue and include a link to it. That way, other people who experience this issue too can view the ticket and either upvote it or find a definitive answer, as provided directly from the product engineering team.

**Comment by binki** [comment]
* [Access the “Show output from:” dropdown](https://developercommunity2.visualstudio.com/t/-/1640406)
* [Directly navigate to Tests Output](https://developercommunity2.visualstudio.com/t/-/1640404)

**Comment by TerryGLee** [comment]
@binki Thanks for including the links. I'll close this issue now, as it's being handled elsewhere, but I'll keep an eye on it for any future Docs impact.
