### ISSUE TITLE
Missing the Bulk Add

### ISSUE THREAD

**Issue by CoMMyCZ** [MicrosoftDocs/visualstudio-docs#754]
The Bulk Add button is missing / we have to add one by one :-( Are there any requirements for the button to appear or the portal is just not working properly?
(Azure Subscription Guid : e0b51305-0dd7-47f7-aaf6-bfa37b5556f6)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c91aef8d-e8b8-c90f-bf4e-04fa609b1bb6
* Version Independent ID: 6106adef-6bab-f93e-fa2b-d60bdd9379b6
* Content: [Assigning Licenses in the Visual Studio Subscriptions Administrator Portal](https://docs.microsoft.com/en-us/visualstudio/subscriptions/assign-license)
* Content Source: [subscriptions/assign-license.md](https://github.com/Microsoft/visualstudio-docs/blob/master/subscriptions/assign-license.md)
* Service: **unspecified**
* GitHub Login: @ghogen

**Comment by evanwindom** [comment]
Thank you for your question, CoMMyCZ.  It looks like you're managing Cloud subscriptions.  The bulk add capability is not yet live for Cloud subscriptions, but we anticipate it will be available very soon.

**Comment by evanwindom** [comment]
Hi Terry,

I’ve responded to the comment.  How can I close the issue?  Is that something that you need to do?

**Comment by TerryGLee** [comment]
@evanwindom Thanks for responding, Evan. I'll close the issue for you, now.
