### ISSUE TITLE
Description how to report a problem is incomplete: - if the Visual Studio installer fails, you simply cannot start the Visual Studio installer to report a problem

### ISSUE THREAD

**Issue by arnead** [MicrosoftDocs/visualstudio-docs#7542]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Troubleshoot installation or upgrade issues - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues?view=vs-2022)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/troubleshooting-installation-issues.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@arnead -- for issues with the Feedback Tool in Visual Studio, please email us at vsfeedback@microsoft.com. 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
