### ISSUE TITLE
Documentation says to see below, but there's nothing below 🙂

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [MicrosoftDocs/visualstudio-docs#7544]
The documentation at https://docs.microsoft.com/en-us/visualstudio/ide/javascript-intellisense?view=vs-2022#automatic-acquisition-of-type-definitions says "If you do not wish to use auto-acquisition, disable it by adding a configuration file as outlined below", but this is the last sentence on this page, so there is nothing outlined below 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60bc9e49-61dd-b909-63ec-4d3daba0e72d
* Version Independent ID: f49d1a0d-f8fd-1512-2da7-f6c1557e82d0
* Content: [JavaScript IntelliSense - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/javascript-intellisense?view=vs-2022)
* Content Source: [docs/ide/javascript-intellisense.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/javascript-intellisense.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Bosch-Eli-Black Thanks for pointing this out. I am removing that statement.
