### ISSUE TITLE
Should explain how to run tests from command line.

### ISSUE THREAD

**Issue by placasse** [MicrosoftDocs/visualstudio-docs#7545]
Unit tests are intended to be run from the CI/CD on a build machine.
It needs to be runs from a command line.
This page should either explain how to run unit tests from the command line or link to a page that explains it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ad1796-f0fa-b93d-f885-542e7e50e3d2
* Version Independent ID: bacdf7a8-a577-bd17-769c-46397b5850b5
* Content: [Creating and Running Unit Tests for UWP apps - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps?view=vs-2022)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@placasse We have a topic on running unit tests from the command line:
https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2022
Please let me know if that is what you need.

**Comment by placasse** [comment]
Hi @Mikejo5000, thanks for this reply.
The page you refer would be appropriate, but it needs an example specific to UWP.
All examples use a .dll but for UWP it would be a .build.appxrecipe instead.
This is not so easy to guess.
I found something here  https://github.com/microsoft/vstest/issues/1534#issuecomment-381080307
Here is my command line (it works):
`& vstest.console.exe /Logger:trx /Platform:x64 /framework:frameworkuap10 UnitTestsUWP\bin\x64\Release\UnitTestsUWP.build.appxrecipe`

**Comment by Mikejo5000** [comment]
@placasse Thanks! I'll add that example
