### ISSUE TITLE
Dropdown not found in the Application section

### ISSUE THREAD

**Issue by xtofl** [MicrosoftDocs/visualstudio-docs#755]
On VS2017, in a .Net Standard 2.0 project, the setting is to be found in the Project Properties -> Package -> "Assembly neutral language" drop down.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43e7c18d-51c4-2c20-9fa3-d95852d533fa
* Version Independent ID: 15863a04-568b-9f15-f244-3f83cb4c524f
* Content: [CA1824: Mark assemblies with NeutralResourcesLanguageAttribute - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1824-mark-assemblies-with-neutralresourceslanguageattribute)
* Content Source: [docs/code-quality/ca1824-mark-assemblies-with-neutralresourceslanguageattribute.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/ca1824-mark-assemblies-with-neutralresourceslanguageattribute.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@xtofl thank you for letting us know; this should be fixed in the next couple of days.
