### ISSUE TITLE
Missing simulator in drop-drown in Visual Studio 2022

### ISSUE THREAD

**Issue by DanieleScipioni** [MicrosoftDocs/visualstudio-docs#7555]
Hello,

it seems that Simulator option from the drop-down list next to the Start Debugging button is missing, is there any plant to add it again?

Thanks in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ccd79a7-1ce8-ecb1-765a-db03899e8158
* Version Independent ID: 7b026550-e924-8969-0ff1-76cd7f4bdffc
* Content: [Run UWP apps in the simulator - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/run-windows-store-apps-in-the-simulator?view=vs-2022)
* Content Source: [docs/debugger/run-windows-store-apps-in-the-simulator.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/run-windows-store-apps-in-the-simulator.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@DanieleScipioni I suspect it's been deprecated and I don't think it will be added back. I may need to remove this doc from the VS 2022 doc set. Are you using VS 2022?

**Comment by DanieleScipioni** [comment]
> @DanieleScipioni I suspect it's been deprecated and I don't think it will be added back. I may need to remove this doc from the VS 2022 doc set. Are you using VS 2022?

I started to use few days ago for an enterprise UWP app. I'm checking if all the features I need are available, and simulator is missing. Simulator is an important tool to for my daily work, it allow to inspect and test app in ways that debug on local machine does not allow (for example: focus independent, touch, rotate, screen resolution).

**Comment by Mikejo5000** [comment]
@DanieleScipioni OK, might be a product bug. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

I will close this issue here, since these issues are for doc issues. Please let me know if you find out more.

**Comment by Mikejo5000** [comment]
@DanieleScipioni It's not clear to me what you get, but you could try the Download Emulators link where you would normally see the Simulator.

**Comment by TyJOrtiz** [comment]
has this been resolved? I see the article was updated in September; it is almost december and the Simulator is still not there. 

Microsoft needs to do better.

**Comment by DanieleScipioni** [comment]
> @DanieleScipioni It's not clear to me what you get, but you could try the Download Emulators link where you would normally see the Simulator.

@Mikejo5000 Download Emulators link proposes only Microsoft Emulator for Windows 10 mobile. I'm referring to the simulator (a desktop application that simulates a UWP app), described in the referenced documentation page.
