### ISSUE TITLE
How to add GTest support to an exisitng project?

### ISSUE THREAD

**Issue by charlie-ht** [MicrosoftDocs/visualstudio-docs#756]
This looks good if I'm starting from scratch, but how do I add GTest support to an existing project? Can't see how after furiously clicking around. :-)

I am using the CMake adaptor in VS 15.6.4 if that is relevant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ee608ee-eb3f-e95d-1eea-d9e35a6e0bc0
* Version Independent ID: daf80b3e-5bf1-652c-d6a0-602c8bc2bb0c
* Content: [How to use Google Test for C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-google-test-for-cpp#configure-the-test-project)
* Content Source: [docs/test/how-to-use-google-test-for-cpp.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/how-to-use-google-test-for-cpp.md)
* Service: **unspecified**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gewarren** [comment]
@mikeblome Can you help @charlie-ht out?

**Comment by mikeblome** [comment]
@Charlie-ht 
With CMake projects, you can install GTest using vcpkg: https://docs.microsoft.com/en-us/cpp/vcpkg
Type "vcpkg install gtest" and then reference the vcpkg.cmake file in your CMakeLists file.

**Comment by tnovotny** [comment]
@mikeblome And if I have a solution / project?

**Comment by gewarren** [comment]
@rchiodo Can you answer how to add GTest support to an existing project/solution?

**Comment by rchiodo** [comment]
Didn't @mikeblome already answer? Reference the vcpkg.cmake file in your cmake project.

**Comment by gewarren** [comment]
@rchiodo Thanks, wasn't sure if @tnovotny was asking a slightly different question. I'll close this issue then.

**Comment by tnovotny** [comment]
I was actually looking for a solution without using vcpkg or cmake . I already had an existing solution (not cmake generated) that I wanted to use. I managed to add it somehow, but don"t ask me how anymore.

**Comment by rchiodo** [comment]
This would likely work too if you didn't want to use vcpkg:
https://www.nuget.org/packages/googletest/

**Comment by tnovotny** [comment]
I already had gtest/gmock locally. All of these steps mean doing something I don't want to do, then adjusting the changes made by these steps to the paths that I have. I
