### ISSUE TITLE
Incorrect exit code

### ISSUE THREAD

**Issue by DanyiLin** [MicrosoftDocs/visualstudio-docs#7576]
Shouldn't !ERR! be %ERR% in https://github.com/MicrosoftDocs/visualstudio-docs/blame/main/docs/install/advanced-build-tools-container.md#L53 , or just exit with %ERRORLEVEL%?
[advanced-build-tools-container[1].md](https://github.com/MicrosoftDocs/visualstudio-docs/files/7928182/advanced-build-tools-container.1.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2022)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@DanyiLin, this script is using delayed expansion and using !ERR! allows for variable expansion at execution time. This thread has some info on this topic: https://stackoverflow.com/questions/25324354/windows-batch-files-what-is-variable-expansion-and-what-does-enabledelayedexpa 

Do you get an incorrect exit code when you try to run this script?

**Comment by anandmeg** [comment]
@DanyiLin, could you please share the error details when you try to run this script to help us investigate this issue further.
Thanks again for your feedback and helping us improve our documentation!

**Comment by DanyiLin** [comment]
@anandmeg the docker build will get stuck at running installation of buildtools:
```
 ---> Using cache
 ---> d67e80840e0f
Step 8/9 : RUN     curl -SL --output vs_buildtools.exe https://aka.ms/vs/17/release/vs_buildtools.exe         && (start /w C:\TEMP\Install.cmd vs_buildtools.exe --quiet --wait --norestart --nocache modify         --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools"         --channelUri C:\TEMP\VisualStudio.chman         --installChannelUri C:\TEMP\VisualStudio.chman         --add Microsoft.VisualStudio.Workload.AzureBuildTools         --remove Microsoft.VisualStudio.Component.Windows10SDK.10240         --remove Microsoft.VisualStudio.Component.Windows10SDK.10586         --remove Microsoft.VisualStudio.Component.Windows10SDK.14393         --remove Microsoft.VisualStudio.Component.Windows81SDK)         && del /q vs_buildtools.exe
 ---> Running in 987d3dbdd45e
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1610k  100 1610k    0     0  1333k      0  0:00:01  0:00:01 --:--:-- 1333k
```
It works if runs installation without **C:\TEMP\Install.cmd**.

**Comment by anandmeg** [comment]
#reassign: @milarso81
@milarso81, a containers related issue. This seems similar to https://github.com/MicrosoftDocs/visualstudio-docs/issues/7278

**Comment by milarso81** [comment]
I have a fix in to the fix the example. Thanks!
