### ISSUE TITLE
Copy task source files example

### ISSUE THREAD

**Issue by khellinx** [MicrosoftDocs/visualstudio-docs#7591]
Example 2 shows a way to copy files recursively.
However, it only copies the files that are present at the start of the build.
This means that after the first build, no files will be copied.
If a new build would result in new files, those will also not be copied the first time they are created.
This is most probably not what users would expect.

A stackoverflow issue has been created in the past:
https://stackoverflow.com/questions/606605/msbuild-copy-task-not-copying-files-the-first-time-round
The accepted solution works, but since MSBuild 3.5, just putting the 'MySourceFiles' ItemGroup in the Target element, works as expected.

This might improve the documentation, is a simple change and might prevent some confusion and hard to debug effects.

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="CopyFiles">
        <ItemGroup>
            <MySourceFiles Include="c:\MySourceTree\**\*.*"/>
        </ItemGroup>

        <Copy
            SourceFiles="@(MySourceFiles)"
            DestinationFiles="@(MySourceFiles->'c:\MyDestinationTree\%(RecursiveDir)%(Filename)%(Extension)')"
        />
    </Target>

</Project>
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 160a060d-7dc1-5826-8beb-f47097d0928f
* Version Independent ID: cc8a11cf-df37-97e9-bd0a-8c8ddd5037c7
* Content: [Copy Task - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2022)
* Content Source: [docs/msbuild/copy-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/copy-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@khellinx 
Thanks, this looks like a good improvement.

**Comment by Seabizkit** [comment]
OMG is this badly documented.... wow they really need to make this resource more available in 2022, just spend a stupid amount of time trying to figure this out.

aka here is stuff... but its wrong..
https://makolyte.com/dotnet-copy-files-to-a-specified-directory-after-the-build/
