### ISSUE TITLE
Error following all steps

### ISSUE THREAD

**Issue by codearmalik** [MicrosoftDocs/visualstudio-docs#7596]
Dear Team,

Follow this tutorial of VueJs and .net core template and I got the following error:

Proxy error: Could not proxy request /weatherforecast from localhost:5002 to https://localhost:49727/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

If there is need to enable CORS etc, that must be mentioned in the tutorial as well.
Thanking you

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@codearmalik Did you find a workaround involving CORs? Also, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
@codearmalik I retested and I could not get a repro for this issue. I am adding some clarifications to the doc.
Please make sure that the https endpoint in launchSettings.json and vue.config.js match, and try 5002 if 5001 doesn't work. Also, please make sure your npm (Node.js) is current, since that could be an issue.
If issue remains unresolved, please use the Report a Problem link above to report the issue. Thanks!
