### ISSUE TITLE
WPF Hello World Tutorial does not work as described

### ISSUE THREAD

**Issue by silmaril42** [MicrosoftDocs/visualstudio-docs#7598]
The tutorial contains the step "Change the name of MainWindow.xaml".  
If you do this, the project is broken and the following steps don't work as described.

I'd recommend removing this step.

Another possible solution would be describing the complete process necessary to successfully rename this file and everything that's connected with it. But since VS doesn't provide any assistance for this kind of refactoring, this would probably confuse the target audience of this very basic tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 329e32a3-766c-1739-022b-5d1a8bc6f4aa
* Version Independent ID: d74a678c-d9b5-90c4-cd63-8451fefaa887
* Content: [Hello World app with WPF in C# - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@silmaril42, thanks for your feedback. We've updated the doc to modify the flow. The changes should be live later today.

Thanks again for helping us improve our documentation. Let us know if you have any other feedback. Thanks!
