### ISSUE TITLE
The enumerator object should be made open source

### ISSUE THREAD

**Issue by yereverluvinunclebert** [MicrosoftDocs/visualstudio-docs#760]
In the spirit of javascript from which jscript is derived the enumerator object should be made open source. Other incarnations of javascript can run on the desktop outside of a browser and are perfect for scripting to allow access to the APIs that Windows provide. The enumerator object is an extension for jscript alone and is unavailable to other javascript variants. In practice this means that you cannot access a collection derived from a WMI query as a collection is not a native javascript data type. There is no similar tool such as the enumerate object to perform this task. If Microsoft made such language enhancements available in the form of polyfills or discrete programs that javascript could utilise, this would be most useful . It would continue in the spirit of open source code and the ethos of javascript. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3e921b9-9dda-bf60-6118-96d703ca309c
* Version Independent ID: c16716ce-f613-9299-618f-e2ce5416da4e
* Content: [Enumerator Object (JavaScript)](https://docs.microsoft.com/en-us/scripting/javascript/reference/enumerator-object-javascript)
* Content Source: [scripting-docs/javascript/reference/enumerator-object-javascript.md](https://github.com/Microsoft/visualstudio-docs/blob/master/scripting-docs/javascript/reference/enumerator-object-javascript.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@bterlson This sounds like a proposal for ECMAScript standards committee.

**Comment by bterlson** [comment]
Enumerator will not be a part of ES which already offers similar functionality: iterators and generators (and their recently introduced async variants). Any code that makes use of Enumerator merely for the API would be far better served using standard iterators.

I also don't think there is anything to open source here. Aside from the API surface area, Enumerator is a whole lot of COM/legacy windows platform stuff. Anything we open sourced would be heavily tied to this technology and platform and of very little use for other engines (e.g. browsers and node).

**Comment by Mikejo5000** [comment]
Closing this one, since it is not actionable
