### ISSUE TITLE
Crap

### ISSUE THREAD

**Issue by FutureInfinite** [MicrosoftDocs/visualstudio-docs#7601]
This is an absolutely pathetic tutorial. It's like someone was walking around just spewing out comments and someone writing it down. The example does not work - there are errors / inconsistencies /un clarity in the document. Very poor. For a multi billion dollar company you think they could get someone to right a decent tutorial. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7aee46f8-9db1-33ef-b637-fc8e8881fab9
* Version Independent ID: 6c469f9f-9751-669f-3dd4-c4fb49c9ae19
* Content: [Work with multiple containers using Docker Compose - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2022)
* Content Source: [docs/containers/tutorial-multicontainer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/tutorial-multicontainer.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@FutureInfinite Hmm, that sounds bad. However, I just went through this one fairly recently and it worked for me.  That makes me think there might be something in particular that's going wrong. What's the first error or step that didn't work as expected for you?

**Comment by FutureInfinite** [comment]
How is the call to the API going to work?

 �

**Comment by ghogen** [comment]
@FutureInfinite 
I think I see the problem. The article uses the phrase "run locally" but what is really meant is "run normally" that is, without Docker Compose. You have to use a different URL when testing without trying to use Docker Compose. When you run with Docker Compose the URL is as follows:
```
request.RequestUri = new Uri("http://mywebapi/WeatherForecast");
```
But I mention in section "Add code to call the Web API", step 8  that if you are running without Docker Compose, it's
```
request.RequestUri = new Uri("http://localhost:{port}/WeatherForecast");
```

You can get the port from the browser or from the project settings.
Try reading step 8 with "run normally, without Docker Compose" and see if it makes more sense.
