### ISSUE TITLE
Documentation inaccurate for container orchestration support configuration steps.

### ISSUE THREAD

**Issue by GaTechThomas** [MicrosoftDocs/visualstudio-docs#7612]
Regarding section:

https://docs.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2022#docker-compose-support

In VS 2022 Pro, the following sentence seems to be inaccurate:

"To add container orchestration support using Docker Compose, right-click on the solution or project node in Solution Explorer, and choose Add > Container Orchestration Support."

Based on actual VS behavior, it seems that this would be the correct wording:

"To add container orchestration support using Docker Compose, right-click on the project node in Solution Explorer, and choose Add > Container Orchestration Support."

To be clear, I am not seeing the option to add container orchestration support when right clicking on the solution node.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e76adc87-d3e4-d443-b1ae-d49d039d08ae
* Version Independent ID: 4c3938df-6bbe-0ef0-50a8-14b6f192deed
* Content: [Visual Studio Container Tools for Docker on Windows - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2022)
* Content Source: [docs/containers/overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@GaTechThomas 
Thanks for pointing this out. I'll get that corrected.
