### ISSUE TITLE
It would be nice if DateTimeOffset static functions where included too

### ISSUE THREAD

**Issue by gmarbury** [MicrosoftDocs/visualstudio-docs#7615]
[Enter feedback here]

DateTimeOffset.Now.ToString() would be nice to use in msbuild scripts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@gmarbury  
Thanks for your feedback. Is this a product suggestion?  If so, it should be entered at https://developercommunity.visualstudio.com/report?entry=suggestion&space=8

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, thank you for your follow-up.  I wasn't sure whether these static functions could be added to the [list in the article](https://docs.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#static-property-functions).

**Comment by ghogen** [comment]
It doesn't work in MSBuild 17.0.

```
<Project>

<PropertyGroup>
  <Today>$([System.DateTime]::Now)</Today>
  <Today2>$([System.DateTimeOffset]::Now)</Today2>
</PropertyGroup>

<Target Name="Print">
  <Message Text="$(Today) $(Today2)"/>
</Target>

</Project>
```

I get:
`error MSB4185: The function "Now" on type "System
.DateTimeOffset" is not available for execution as an MSBuild property function.`

**Comment by ghogen** [comment]
Entered in the MSBuild repo as a feature request.
https://github.com/dotnet/msbuild/issues/7504

**Comment by ghogen** [comment]
@gmarbury
I entered a feature request. The engineers agreed this is a reasonable request.

**Comment by gmarbury** [comment]
@ghogen 
Thank you for moving and considering my request. I responded to your request for example usage.
