### ISSUE TITLE
Dataset-URL moved to: "https://archive.ics.uci.edu/ml/machine-learning-databases/spambase/spambase.data"

### ISSUE THREAD

**Issue by ErikBoSo** [MicrosoftDocs/visualstudio-docs#7617]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44d264fa-6d4e-0128-b0a0-f997d01c19a9
* Version Independent ID: 7d2e1867-4890-20fc-f60c-45f0242b4f7f
* Content: [Quickstart - Create Python projects using Cookiecutter - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter?view=vs-2022)
* Content Source: [docs/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/quickstart-04-python-in-visual-studio-project-from-cookiecutter.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by WilliamAntonRohm** [comment]
@ErikBoSo -- Erik, thank you for your feedback.

@rjmolyneaux -- Ryan, I'm not sure which link this is, in the article.  Please advise, and I will update it.

**Comment by rjmolyneaux** [comment]
Hi @ErikBoSo, 
Thank you for reaching out with your concern. We care unable to located the URL that you're referring to. Are you able to provide more information on this issue so that we can better assist?

**Comment by ErikBoSo** [comment]
> Hi @ErikBoSo, Thank you for reaching out with your concern. We are unable to locate the URL that you're referring to. Are you able to provide more information on this issue so that we can better assist?

'''
Sorry, I am referring to the URL pointing to the example data in classifier.py from the Microsoft/python-sklearn-classifier-cookiecutter template:
"
...
This script performs the basic process for applying a machine learning
algorithm to a dataset using Python libraries.

The four steps are:
   1. Download a dataset (using pandas)
   2. Process the numeric data (using numpy)
   3. Train and evaluate learners (using scikit-learn)
   4. Plot and compare results (using matplotlib)


The data is downloaded from URL, which is defined below. As is normal
for machine learning problems, the nature of the source data affects
the entire solution. When you change URL to refer to your own data, you
will need to review the data processing steps to ensure they remain
correct.

============
Example Data
============
The example is from **https://archive.ics.uci.edu/ml/datasets/Spambase**
It contains pre-processed metrics, such as the frequency of certain
words and letters, from a collection of emails. A classification for
each one indicating 'spam' or 'not spam' is in the final column.
See the linked page for full details of the data set.

This script uses three classifiers to predict the class of an email
based on the metrics. These are not representative of modern spam
detection systems.
'''

# Remember to update the script for the new data when you change this URL
URL = https://archive.ics.uci.edu/ml/datasets/Spambase/spambase.data
"

hth
Bo
![cookiecut](https://user-images.githubusercontent.com/21060699/157876519-1be748ac-c3c2-465c-b4c0-a8a2d15c8d7f.png)

**Comment by ErikBoSo** [comment]
wrong button, :-(

**Comment by AdamYoblick** [comment]
Hi @ErikBoSo - the url you're referring to is at https://github.com/microsoft/python-sklearn-classifier-cookiecutter/blob/master/%7B%7Bcookiecutter.app_name%7D%7D/classifier.py#L33, but this file hasn't changed in four years. Are you saying that the dataset in this file no longer exists, and we should be updating the URL to the new one you specified?

**Comment by ErikBoSo** [comment]
Hi @AdamYoblick
Excactly 👍

**Comment by AdamYoblick** [comment]
This has been fixed with https://github.com/microsoft/python-sklearn-classifier-cookiecutter/pull/3.

@rjmolyneaux , feel free to close out this issue.

**Comment by rjmolyneaux** [comment]
This is great. @AdamYoblick, thank you for working to solve this! Closing this issue for now.

#please-close
