### ISSUE TITLE
Side-by-side comparison disabled

### ISSUE THREAD

**Issue by mcalexster** [MicrosoftDocs/visualstudio-docs#7621]
[Enter feedback here]
Fix your CSS! A "side-by-side" comparison is impossible without two 24" monitors, because whenever you increase the width of the browser window, the column that gets the most expansion is the RHS sidebar.

Either add column minimiser buttons, or restrict expansion of the sidebar to a max pixel count (not %age)

![image](https://user-images.githubusercontent.com/6275182/152276289-19da0e8e-8819-4c29-a8bc-b05edc6c8b44.png)

See attached:  Why is there a horizontal scroll bar for the main (middle) content, and three miles of whitespace to the right of the column with: 'Branches', 'Conflict Resolution', 'Next Steps', 'See Also' 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa1e2fe5-6a2b-f507-5b04-ba9dbd6783d5
* Version Independent ID: dfce8efa-e1b7-89b3-6d91-5d2865c1a7da
* Content: [Side-by-side comparison of Git and Team Explorer in Visual Studio 2019](https://docs.microsoft.com/en-us/visualstudio/version-control/git-team-explorer-feature-comparison?view=vs-2019)
* Content Source: [docs/version-control/git-team-explorer-feature-comparison.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-team-explorer-feature-comparison.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Taysser-Gherfal
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@mcalexster -- thank for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
