### ISSUE TITLE
$(pwd) does not resolve in DockerfileRunArguments

### ISSUE THREAD

**Issue by JohnTheGray** [MicrosoftDocs/visualstudio-docs#7628]
Regarding the example for  launchSettings.json:
"DockerfileRunArguments": "-v $(pwd)/host-folder:/container-folder:ro",

$(pwd) does not resolve when running the docker project for visual studio.

The following does work (when added to the project file as opposed to the launchSettings.json):
<DockerfileRunArguments>-v $(pwd)/host-folder:/container-folder:ro</DockerfileRunArguments>

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0eb0463-50c5-9697-2eaf-a5f5fcb01513
* Version Independent ID: bf27ddf9-e6a3-0717-1d3c-620c054f0d5c
* Content: [Visual Studio Container Tools launch settings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/containers/container-launch-settings?view=vs-2019)
* Content Source: [docs/containers/container-launch-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/container-launch-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@JohnTheGray 
Thanks for the report. This looks like a product issue. It might be related to https://github.com/microsoft/DockerTools/issues/324
Would you enter it in that repo, or add your example to the previous issue?

**Comment by JohnTheGray** [comment]
@ghogen I think you're right. I've added a comment on [https://github.com/microsoft/DockerTools/issues/324](https://github.com/microsoft/DockerTools/issues/324).
