### ISSUE TITLE
Attach to process - does not work

### ISSUE THREAD

**Issue by comtronic** [MicrosoftDocs/visualstudio-docs#7630]
I'm experiencing the attach-to-process issue quite often in general. Last time I needed to reinstall Windows to get rid of the problem.

Now, I'm at the same point again. Unfortunately, none of the suggestions at this web-page works. It seems quite complicated to get this to work 100% ? 

Can I get access to some log-files ? I checked the firewall-logs in c:\windows32 and I also tried to get some useful information from sysinternals-process-monitor but I couldn't find anything wrong there.

It stopped working after I added MS Hyper-V to my computer! I tried to reverse this and made a full uninstall but it's still not working.

Software details:
Visual Studio Version: 16.11.9 (Currently the latest 2019-version)
Unity versions seems to be irrelevant because I tried multiple versions and it's same VS-behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b8aa8c5-5a0f-a3fe-13db-84762f6dfd83
* Version Independent ID: 910576e9-feb5-9423-6fa1-1d81f8ef08da
* Content: [Troubleshooting and known issues (VS Tools for Unity)](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/troubleshooting/troubleshooting-and-known-issues-visual-studio-tools-for-unity)
* Content Source: [gamedev/unity/troubleshooting/troubleshooting-and-known-issues-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/gamedev/unity/troubleshooting/troubleshooting-and-known-issues-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by therealjohn** [comment]
Hi @comtronic 

I'm sorry to hear about the repeated issue. I absolutely want to help get this resolved. It will be helpful to report this using Visual Studio after the issue occurs using the Help > Send Feedback > Report a Problem menu. That will guide you through submitting a ticket and it will include a lot of diagnostic information automatically that answers a lot of the questions we need to understand the environment. Please share a link to the Developer Community issue after it's created, and I'll help triage it. Thank you!

**Comment by comtronic** [comment]
Updated information with more details.

**Comment by therealjohn** [comment]
@comtronic 

If you're using Unity 2020.x, make sure that the latest Visual Studio Editor package is installed using the Unity Package Manager. If that is up-to-date, I wonder if something with Hyper-V is conflicting with the port usage of the debugger. 

Please use the Visual Studio > Help > Submit Feedback > Report a Problem menu to log a bug ticket which automatically includes the diagnostics we need to get started investigating. It will also help us track this quicker. 

Thank you!

**Comment by WilliamAntonRohm** [comment]
@therealjohn -- John, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by comtronic** [comment]
Thanks for the concern. I tried to find the issue for days but I needed to reinstall Windows. Again.

**Comment by comtronic** [comment]
> 

Microsoft closed the ticket. I couldn't attach to any Unity editor with either Visual Studio Code or Visual Studio 2019/22. The problem must have been related to any network issue with the Hyper-X installation but I didn't have weeks available for investigating it further.

**Comment by therealjohn** [comment]
@comtronic 

Is this the ticket you mentioned? https://developercommunity.visualstudio.com/t/Cant-attach-the-debugger-to-Unity/1656918

If you do run into the issue again, please let us know on that ticket and we'll continue to help investigate. Thank you!
