### ISSUE TITLE
Change Office 365 Developer Program to Microsoft 365 Developer Program

### ISSUE THREAD

**Issue by Lauragra** [MicrosoftDocs/visualstudio-docs#7632]
Please change Office 365 Developer Program to Microsoft 365 Developer Program to reflect the rebranding of the developer program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [Microsoft 365 developer subscriptions in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by evanwindom** [comment]
@WilliamAntonRohm - it looks like there is more to do here.  The branding on Office threat protection seems to have changed, and the activation experience is a little different so I'm doing an end-to-end update.

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- so noted!

**Comment by corob-msft** [comment]
@Lauragra @WilliamAntonRohm @evanwindom 
I don't know what I did, but I did not intentionally close this issue. It appears to have happened as a side effect of my local repo sync. Please reopen this if it's still active.

**Comment by Lauragra** [comment]
@corob-msft , it looks like this is fixed on the live site so we're good to close! Thanks.
