### ISSUE TITLE
A related documentation feedback

### ISSUE THREAD

**Issue by lextm** [MicrosoftDocs/visualstudio-docs#764]
https://github.com/MicrosoftDocs/visualstudio-docs/issues/763

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ab4333f-c992-f580-5a1f-cfc60bcfb650
* Version Independent ID: e354bcf5-e277-8d35-9850-e5accfb8ace8
* Content: [Use Visual Studio to create an ASP.NET Core web app in C# - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/quickstart-aspnet-core)
* Content Source: [docs/ide/quickstart-aspnet-core.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/quickstart-aspnet-core.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@lextm Thanks for your input. We appreciate your adding a reference to the extra information you provided on a related article.
