### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by w3b2-99** [MicrosoftDocs/visualstudio-docs#765]
Where is the source code for this example? Please provide a download link. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702dd6fa-5ad3-b9c7-04bc-e9431c228623
* Version Independent ID: 4d8a2c98-429a-b04e-1489-74475df5951a
* Content: [Mixed-mode debugging for Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio)
* Content Source: [docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Thanks. I agree that I need to get the sample up somewhere. Stay tuned.

**Comment by kraigb** [comment]
You can find it on https://github.com/Microsoft/python-sample-vs-cpp-extension. Let me know if you have any issues with it. I'll be adding a link to the article as well, but in the meantime I'm closing the issue.
