### ISSUE TITLE
Following instructions in Create an ASP.NET Core app with React - Visual Studio (Windows): project doesn't load initially

### ISSUE THREAD

**Issue by wallergoble** [MicrosoftDocs/visualstudio-docs#7651]
When you follow these instructions, the app won't boot initially. The startup exe runs in a loop with the following problem: 
![image](https://user-images.githubusercontent.com/19699858/153268206-57aaf43e-b005-4437-9b90-4b4dc60aa14c.png)

When I ran npm run start on it's own, I found the error to be:
![image](https://user-images.githubusercontent.com/19699858/153268372-16c7fdee-2bfa-4b39-bf2d-a772fcb47395.png)

Chaing the package.json start script to ` "start": "rimraf ./build && react-scripts --openssl-legacy-provider start",` fixes the problem.

I'm not sure if this is a great fix, but thought I'd bring up the issue regardless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@wallergoble -- Waller, thank you for your feedback and research.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@wallergoble Please let me know if this is still an issue. I have tested the React project as described in the article and have not been able to repro.
