### ISSUE TITLE
Link QuickStart

### ISSUE THREAD

**Issue by wcrowther** [MicrosoftDocs/visualstudio-docs#7652]
The QuickStart Vue/React/Angular project setup pages should contain a reference to Tutorial pages (for the same Vue/React/Angular) that show how to integrate the client-side technology with server-side Asp.Net Core API and vice versa.

Particularly if you are hitting the site from a search engine, you may miss one set of articles or the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8355edff-3658-6c23-6f5c-c4acfc18ab2e
* Version Independent ID: 54ecbbc0-c870-0ed8-b4c6-07a6da2ec806
* Content: [Create a Vue.js app - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-create-vue-app?view=vs-2022)
* Content Source: [docs/javascript/tutorial-create-vue-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-create-vue-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@wcrowther Good idea. I will plan to add the links.
