### ISSUE TITLE
Windows 11 support

### ISSUE THREAD

**Issue by colinc1709** [MicrosoftDocs/visualstudio-docs#7658]
The registry setting HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers does not appear in Windows 11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness for scaling in forms - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2022#resolve-hdpi-display-problems)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@colinc1709 Thanks for your patience on this issue. I checked in with the engineering team and they remarked as follows: 

"Certain registry keys might not exist if they’ve never been used or needed before. If the **AppCompatFlags** key isn’t there, it doesn’t mean that the instructions won’t work on Windows 11. It just means that if those keys are missing, you’ll need to create them. When you do so on a computer running Windows 11 and set the **devenv** flags per the instructions, launch Visual Studio, and it shows up as DPI unaware, then it means everything still works as expected."

We'll close this issue now with our thanks for your inquiry, as this answer is now on file for anyone else who might need this information.
