### ISSUE TITLE
There are a few confusing lines “Step 2: Step 2: Release your app” in the doc

### ISSUE THREAD

**Issue by MNF** [MicrosoftDocs/visualstudio-docs#766]
Is it suppose to have Go To “Step 2: Release your app”?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65d6eb45-903b-7cc8-d09f-6195240aecfa
* Version Independent ID: 749c6317-c32f-a1ea-8959-b319af1815c1
* Content: [Diagnose problems after deployment | Microsoft Docs](https://docs.microsoft.com/en-au/visualstudio/debugger/diagnose-problems-after-deployment)
* Content Source: [docs/debugger/diagnose-problems-after-deployment.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/diagnose-problems-after-deployment.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@MNF Thanks for catching this! Fix in progress
