### ISSUE TITLE
Broken in VS 2019

### ISSUE THREAD

**Issue by monkeycoder99** [MicrosoftDocs/visualstudio-docs#7661]
This no longer works for C# in VS 2019. Regularly get the following dialog, even though the property/field most definitely exists. This has happened on numerous occasions in completely different modules.

![image](https://user-images.githubusercontent.com/35289977/153664420-f45d8968-b00c-4e48-b90d-97e4f0dab7b6.png)

And from Watch window to prove the value exists and clearly evaluates to a boolean.

![image](https://user-images.githubusercontent.com/35289977/153664535-1c3d386b-b90b-40c8-a19c-48caca4b5ef7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use breakpoints in the debugger - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2022)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/using-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@monkeycoder99 -- thank you for your feedback.  Please add this here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

cc @markingmyname for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
