### ISSUE TITLE
Fantastic document. Well structured and complete, answering all the questions that I had about .editorconfig

### ISSUE THREAD

**Issue by dangspaceiq** [MicrosoftDocs/visualstudio-docs#7667]
Fantastic document. Well structured and complete, answering all the questions that I had about .editorconfig
Thank you for your effort.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [EditorConfig settings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@dangspaceiq -- thank you for your kind words!

cc @mikadumont, @j-martens
