### ISSUE TITLE
Incorrect numbering of docker tutorial parts.

### ISSUE THREAD

**Issue by deep-bhatt** [MicrosoftDocs/visualstudio-docs#7669]
![image](https://user-images.githubusercontent.com/25231083/154022618-4e7d2075-3844-4d90-b044-2baca433d614.png)

"Share your app" should be Part 4 instead,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa8d34fc-cf0d-5e1d-db30-54eca31615d9
* Version Independent ID: ce0dcf52-94ee-c9ba-b918-8ef27b08a8dc
* Content: [Docker tutorial - Part 3: Update your app](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/update-your-app)
* Content Source: [docker/tutorials/update-your-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docker/tutorials/update-your-app.md)
* Product: **vs-code**
* GitHub Login: @BigMorty
* Microsoft Alias: **mikemort**

**Comment by deep-bhatt** [comment]
Here's the PR that fixes this: https://github.com/MicrosoftDocs/visualstudio-docs/pull/7670

**Comment by WilliamAntonRohm** [comment]
@deep-bhatt -- Deep, thank you for your contribution.  Your PR has been approved and merged.  It should be visible by tomorrow.
