### ISSUE TITLE
Poor

### ISSUE THREAD

**Issue by amckern** [MicrosoftDocs/visualstudio-docs#767]
Overall, this is good feedback, but I have an active and installed version of VS2017 community.

Problem is, i am unable to modify the installed copy, and instead the launcher wants me to install a new copy.

Please modify article for "if install option is only present but have installed copy"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8d0cb94-2886-79ce-39dd-0336282369b9
* Version Independent ID: e8bcc58e-98af-e3ad-2629-0b4515047d0b
* Content: [Modify Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio)
* Content Source: [docs/install/modify-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/modify-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@amckern Thanks for your feedback. We'll investigate this and reply soon.

**Comment by TerryGLee** [comment]
@amckern We have added more information to the [Modify Visual Studio 2017](https://docs.microsoft.com/visualstudio/install/modify-visual-studio) to address the issue you brought to our attention. Again, thanks for doing so.
