### ISSUE TITLE
Wrong Sample?

### ISSUE THREAD

**Issue by ChristianHaefner** [MicrosoftDocs/visualstudio-docs#7679]
Regarding the sample:
- Visual Studio 2022 version 17.1.0 update classified as a "Feature Pack" will apply to Visual Studio 2022 editions licensed for enterprise use on the client that is on the Current channel, and it will update it to the 17.1.0 version.

Shouldn't it also update the LTSC channel 17.0?  

- Visual Studio 2022 version 17.1.0 update classified as a "Feature Pack" will apply to Visual Studio 2022 editions licensed for enterprise use on the client that is __on either the Current channel or the 17.0 LTSC channel__, and it will update it to the 17.1.0 version.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6ec9e8a-02c6-b17a-ed66-391c4df991ce
* Version Independent ID: 1bacfcf8-6e2a-940d-93e5-97e2be9bd2b8
* Content: [Applying administrator updates to Visual Studio with Microsoft Endpoint Configuration Manager](https://docs.microsoft.com/en-us/visualstudio/install/applying-administrator-updates?view=vs-2022)
* Content Source: [docs/install/applying-administrator-updates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/applying-administrator-updates.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@ChristianHaefner, thanks for your question. 
The 17.0 LTSC channel will only have 17.0.x versions (until we have the 17.2 LTSC channel in Spring 2022, see [LTSC support](https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-servicing#enterprise-professional-and-build-tools-editions-support)). The 17.1 version will not go on the 17.0 LTSC channel.  It only applies to the current channel.

The LTSC are separate release Channels based on the even-numbered minor version updates, for example, 17.0 and 17.2. 
For more information on Preview Channel, see [Visual Studio Channels and Release Rhythm](https://docs.microsoft.com/en-us/visualstudio/productinfo/release-rhythm).

Let us know if you have any other questions. Thanks!

**Comment by ChristianHaefner** [comment]
@anandmeg Thanks for clarification. With your explanation, it will generally not be possible to switch from a LTSC channel to the Current Channel with a Feature Pack Update as it is the case when updating from 17.0 to 17.1. Is this really intended?
