### ISSUE TITLE
Question - Does it install packages for a specific OS?

### ISSUE THREAD

**Issue by SirJosh3917** [MicrosoftDocs/visualstudio-docs#768]
Let's say I start creating a local cache on a Windows 7 machine. Can I use the exact same cache for another OS, say windows 10, and expect it to work fine?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@SirJosh3917 Thanks for your feedback. We'll investigate this and report back, soon.

**Comment by MikeMarlowe** [comment]
When installing Visual Studio, some components may be installed that are OS version/architecture specific.  
However, when you can create an offline layout, it will not be specific to that OS version.  It will contain everything it needs to install Visual Studio on any supported OS version.  For example, you could create a layout on a Windows 7 x86 machine and install Visual Studio from that layout on Windows 7, Windows 8.1 and Windows 10 machines.
