### ISSUE TITLE
Typo in example?

### ISSUE THREAD

**Issue by mudnug** [MicrosoftDocs/visualstudio-docs#7687]
Looking at this example:
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

    <Target Name="CopyFiles">
        <ItemGroup>
            <!-- Because this ItemGroup is inside the target, this will enumerate
                 all files just before calling Copy. If the ItemGroup were outside
                 the target , it would enumerate the files during evaluation, before
                 the build starts, which may miss files created during the build. -->
            <MySourceFiles Include="c:\MySourceTree\**\*.*"/>
        </ItemGroup>

        <Copy
            SourceFiles="@(MySourceFiles)"
            DestinationFiles="@(MySourceFiles->'c:\MyDestinationTree\%(RecursiveDir)%(Filename)%(Extension)')"
        />
    </Target>

</Project>
```

Should
` DestinationFiles="@(MySourceFiles->'c:\MyDestinationTree\%(RecursiveDir)%(Filename)%(Extension)')"`
be 
` DestinationFiles="c:\MyDestinationTree\%(RecursiveDir)%(Filename)%(Extension)"`
?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 160a060d-7dc1-5826-8beb-f47097d0928f
* Version Independent ID: cc8a11cf-df37-97e9-bd0a-8c8ddd5037c7
* Content: [Copy Task - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/copy-task?view=vs-2022)
* Content Source: [docs/msbuild/copy-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/copy-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@mudnug -- Matthew, thank you for your question.  I am looking into updating this article.

**Comment by ghogen** [comment]
Both work, but the proposed change is simpler, so it seems reasonable to accept it.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
