### ISSUE TITLE
tracking assigments via PowerShell/CLI

### ISSUE THREAD

**Issue by ValerianHts** [MicrosoftDocs/visualstudio-docs#7688]
Are there any possibilities to track assigments using PowerShell and/or AzureCLI-Commandlets?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b247463-3cad-8d7d-e897-d0be5f9f7441
* Version Independent ID: 1f233b1e-d4d8-641d-6fa0-e7a68fa585de
* Content: [Track assignments and process orders in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/assignments-orders)
* Content Source: [subscriptions/assignments-orders.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/assignments-orders.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@ValerianHts Thank you for reaching out.  I will investigate this and post an answer soon.

**Comment by evanwindom** [comment]
@ValerianHts - I checked with our engineering team, and those capabilities are not currently supported and are not something we're planning in the near term.  For requests like this, however, we typically keep track of what's being requested and use those requests for long term planning.

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger10** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.
