### ISSUE TITLE
Problem debugging C++ extensions for Python x64

### ISSUE THREAD

**Issue by bitsrules** [MicrosoftDocs/visualstudio-docs#769]
Please help me with the debugging problem posted on StackOverflow. https://stackoverflow.com/questions/49571007/debugging-c-extension-for-python

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Working with C++ and Python - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio#feedback)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by bitsrules** [comment]
I have a problem when I try to debug my C++ extension for Python.
The error is   
**Fatal Python error: PyThreadState_Get: no current thread**

I followed this [guide][1] and it works when I run in the release version.

Python code:

    from itertools import islice
    from random import random
    from time import perf_counter
    
    COUNT = 500000  # Change this value depending on the speed of your computer
    DATA = list(islice(iter(lambda: (random() - 0.5) * 3.0, None), COUNT))
    
    e = 2.7182818284590452353602874713527
    
    def sinh(x):
        return (1 - (e ** (-2 * x))) / (2 * (e ** -x))
    
    def cosh(x):
        return (1 + (e ** (-2 * x))) / (2 * (e ** -x))
    
    def tanh(x):
        tanh_x = sinh(x) / cosh(x)
        return tanh_x
    
    def sequence_tanh(data):
        '''Applies the hyperbolic tangent function to map all values in
        the sequence to a value between -1.0 and 1.0.
        '''
        result = []
        for x in data:
            result.append(tanh(x))
        return result
    
    def test(fn, name):
        start = perf_counter()
        result = fn(DATA)
        duration = perf_counter() - start
        print('{} took {:.3f} seconds\n\n'.format(name, duration))
    
        for d in result:
            assert -1 <= d <=1, " incorrect values"
    
    from superfastcode import fast_tanh
    if __name__ == "__main__":
	   test(lambda d: [fast_tanh(x) for x in d], '[fast_tanh(x) for x in d]')

C++ code:

    #include <Python.h>
    #include <cmath>
    
    const double e = 2.7182818284590452353602874713527;
    
    double sinh_impl(double x) {
    	return (1 - pow(e, (-2 * x))) / (2 * pow(e, -x));
    }
    
    double cosh_impl(double x) {
    	return (1 + pow(e, (-2 * x))) / (2 * pow(e, -x));
    }
    
    PyObject* tanh_impl(PyObject *, PyObject* o) {
    	double x = PyFloat_AsDouble(o);
    	double tanh_x = sinh_impl(x) / cosh_impl(x);
    	return PyFloat_FromDouble(tanh_x);
    }
    
    static PyMethodDef superfastcode_methods[] = {
    	// The first property is the name exposed to Python, fast_tanh, the second is the C++
    	// function name that contains the implementation.
    	{ "fast_tanh", (PyCFunction)tanh_impl, METH_O, nullptr },
    
    	// Terminate the array with an object containing nulls.
    { nullptr, nullptr, 0, nullptr }
    };
    
    static PyModuleDef superfastcode_module = {
    	PyModuleDef_HEAD_INIT,
    	"superfastcode",                        // Module name to use with Python import statements
    	"Provides some functions, but faster",  // Module description
    	0,
    	superfastcode_methods                   // Structure that defines the methods of the module
    };
    
    PyMODINIT_FUNC PyInit_superfastcode() {
    	return PyModule_Create(&superfastcode_module);
    }

I am using the 64 bit version of Python 3.6, and are building the C++ code in x64 mode. Visual Studio 2017 15.6.4

I am linking with C:\Python\Python36.x64\libs\python36_d.lib and including header files from C:\Python\Python36.x64\include   
My Python interpreter is in C:\Python\Python36.x64\

I get this result when I run the release build

    [fast_tanh(x) for x in d] took 0.067 seconds

  [1]: https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio

**Comment by bitsrules** [comment]
I managed to get it working with Win32 (x86) of Python 3.6. 
Will try again from scratch with x64 Py.

**Comment by bitsrules** [comment]
On x64 I can hit the break point when debugging 
When I step over (F10) it crashes in typeobject.c in the method PyType_IsSubtype()
It works in x86.

![debugbreakhit](https://user-images.githubusercontent.com/33675621/38224439-f87b4c94-372a-11e8-8240-741fde7d64e7.PNG)
![exceptionthrow](https://user-images.githubusercontent.com/33675621/38224442-fbd121ac-372a-11e8-9d01-024ef598c193.PNG)

**Comment by kraigb** [comment]
Hi @bitsrules -- because you're looking at a potential product bug (that goes beyond documentation), please file an issue on https://github.com/Microsoft/PTVS/issues so the engineering team can help you out for your specific version of VS and PTVS. Do @ mention me as well so I can follow the thread and amend the documentation as necessary.

**Comment by kraigb** [comment]
BTW, in general I believe you need to use a 32-bit CPython environment to work with C++ at present (which is in the docs). You may be running into x64 incompatibilities, but again, the engineering team can help you better there.

Close this issue once you get the PTVS one file (and ref this one).

**Comment by kraigb** [comment]
Sorry, hit the wrong button...didn't mean to close. :)

**Comment by kraigb** [comment]
Closing as it's been transferred to PTVS issues.
