### ISSUE TITLE
Not mention about .Net Core (.NET 6) not supported

### ISSUE THREAD

**Issue by nolme** [MicrosoftDocs/visualstudio-docs#7690]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d4d170-fcf4-6caf-da44-dfe6e194a257
* Version Independent ID: c980b0f6-ed24-9c4a-0b2e-77962aafc81d
* Content: [Use config file to define data source - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-using-a-configuration-file-to-define-a-data-source?view=vs-2022)
* Content Source: [docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@kendrahavens Kendra, can you confirm the APIs are .NET Framework only? I can update doc, if that's correct.

**Comment by kendrahavens** [comment]
Ah, this is a doc bug. For .NET Core, users should use DynamicData https://github.com/Microsoft/testfx-docs/blob/master/RFCs/006-DynamicData-Attribute.md

We do have a popular issue to port it to .NET Core / 5 / 6, but we haven't been able to get to it.

**Comment by Mikejo5000** [comment]
@kendrahavens In the interim, I'll add a note that DataSourceAttribute is .NET Framework only. How does that sound?

**Comment by kendrahavens** [comment]
@Mikejo5000 sounds good!
