### ISSUE TITLE
"How to: Distribute code snippets" - wrong path in HelloWorldVB.pkgdef

### ISSUE THREAD

**Issue by TPIvan** [MicrosoftDocs/visualstudio-docs#7692]
The document instructs to put in HelloWorldVB.pkgdef file following content
```
// Visual Basic
[$RootKey$\Languages\CodeExpansions\Basic\Paths]
"HelloWorldVB"="$PackageFolder$"
```
The problem is that than the selection the path from snippet selection menu is **1.0**/HelloWorldVB/...

![IncorrectSnippetSample1](https://user-images.githubusercontent.com/39948593/154745414-bf940f17-eeb1-46c6-a12b-1a0f6ba67eeb.png)

![IncorrectSnppetsample2](https://user-images.githubusercontent.com/39948593/154745524-f19da6cb-b1dc-40bb-8f5c-d42d392dd431.png)

The content of the file should be

```
// Visual Basic
[$RootKey$\Languages\CodeExpansions\Basic\Paths]
"HelloWorldVB"="$PackageFolder$\HelloWorldVB"
```

(the HelloWorldVB text is added to the string) and when this content is used the path from snippet selection menu is **HelloWorldVB**/...

![correctsnippetsample](https://user-images.githubusercontent.com/39948593/154745224-c7964ed5-4094-42ec-93db-3748696cf6be.png)

The idea is taken from:
https://github.com/madskristensen/HtmlSnippetPack/blob/master/src/Snippets/snippets.pkgdef

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c60cdeb-c3af-ebb1-80e7-1ec682896734
* Version Independent ID: 04010067-02f9-548e-467b-fa4efa391860
* Content: [Distribute code snippets as an extension - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-distribute-code-snippets?view=vs-2022)
* Content Source: [docs/ide/how-to-distribute-code-snippets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-distribute-code-snippets.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@TerryGLee -- Terry, please review this update in [private PR 9635](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9635).

**Comment by TPIvan** [comment]
By my opinion the wrong content is still present on the page [Add the .pkgdef file](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-distribute-code-snippets?view=vs-2022#add-the-pkgdef-file)

**Comment by WilliamAntonRohm** [comment]
@TPIvan -- thank you for your followup.  I am updating this article.
