### ISSUE TITLE
Visual Studio\Debug\Windows\Tasks\Parent - empty values

### ISSUE THREAD

**Issue by NikVladi** [MicrosoftDocs/visualstudio-docs#7696]
Can someone provide a sample code to get the Parent field in the task window in debug to be populated. I created a question on [stackoverflow](https://stackoverflow.com/questions/71135423/visual-studio-debug-windows-tasks-parent-empty-values), but no one knows.

I made a simple example After a few seconds, I pause and see that all the values in the parent field are empty.

**Question**: What code do I need to write to see the filled parent fields in the specified debug window?

```
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    
    namespace ConsoleApp1
    {
        class Program
        {
            static void Main(string[] args)
            {
                void MyMethod()
                {
                    Console.WriteLine(Task.CurrentId);
                    Task.Run(MyMethod);
                    Thread.Sleep(10000);
                }
    
                MyMethod();
            }
        }
    }

```
> or

```
    using System;
    using System.Threading;
    using System.Threading.Tasks;
    
    namespace ConsoleApp1
    {
        class Program
        {
            static void Main(string[] args)
            {
                void MyMethod()
                {
                    Console.WriteLine(Task.CurrentId);
                    new Task(MyMethod, TaskCreationOptions.AttachedToParent).Start();
                    Thread.Sleep(10000);
                }
    
                MyMethod();
            }
        }
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1b431a-4afc-27ae-b2d9-0d1299eba257
* Version Independent ID: 72c6c954-6989-4ca7-1db4-38d6ac3f3c40
* Content: [Using the Tasks Window - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-tasks-window?view=vs-2022)
* Content Source: [docs/debugger/using-the-tasks-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/using-the-tasks-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@NikVladi -- thank you for your research and question.  This repo is solely for documentation issues, with limited support options.  I see you've tried stackoverflow; please consider these resources as well:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Reddit](https://www.reddit.com/r/VisualStudio)

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
