### ISSUE TITLE
Documentation not matching visual studio and sample with errors.

### ISSUE THREAD

**Issue by Wasserwecken** [MicrosoftDocs/visualstudio-docs#7697]
While going through the guide I was not able to start the sample as described.
I downloaded the recent version of VS Community 2022 (17.1.0) and added the web packages.
![image](https://user-images.githubusercontent.com/15609168/154806118-5c773c44-7b58-4198-abd4-0f18c2c36d6a.png)

Step "Set the project properties": _Next, right-click the Vue project and select the Properties menu and go the Debugging section. Change the Debugger to launch to the launch.json option._
The properties do not match the documentation and also miss completly the debug section.
![image](https://user-images.githubusercontent.com/15609168/154806582-c1d85675-c24b-4f74-8034-709fb1f963f3.png)

Also, when launching the project after going through the guide the vue project has exceptions:
![image](https://user-images.githubusercontent.com/15609168/154806927-756dc414-33ed-4b32-bd38-0bf47912d772.png)

Dont know if its me, or the guide or the sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Wasserwecken** [comment]
Okay, it was me.

1. I installed vue.js 3.0 before. It looks like the template is using vue.js 2.0 code. His fixed the template for me:
![image](https://user-images.githubusercontent.com/15609168/154810360-90486c85-bf3e-49e4-b4fb-8fb9c154aa90.png)

2. The IIExpress configuration in launchSettings.json for the ASP.NET Core app can be removed. Not breaking, but confused me.

**Comment by WilliamAntonRohm** [comment]
@Wasserwecken -- thank you for your feedback & congratulations on its subsequent resolution.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
