### ISSUE TITLE
Duplicate document content

### ISSUE THREAD

**Issue by fenneishi** [MicrosoftDocs/visualstudio-docs#7700]
![image](https://user-images.githubusercontent.com/33345538/154835092-3aa94e2f-d877-4628-8722-967a09e4f965.png)
in:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md

**Comment by rjmolyneaux** [comment]
Hi @fenneishi, 
Thank you for bringing this to our attention! We've updated the doc to reflect the accurate property settings, with [PR #9616](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9616). You should be able to see this live shortly!

**Comment by rjmolyneaux** [comment]
Cc: @ijoosong @j-martens

**Comment by rjmolyneaux** [comment]
#please-close
