### ISSUE TITLE
sad

### ISSUE THREAD

**Issue by phanluutienquang** [MicrosoftDocs/visualstudio-docs#7701]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20d270df-0135-8e2f-b47c-e070293e7669
* Version Independent ID: bacb3cc1-342f-92a0-0bf5-c050de84757f
* Content: [Code editor features - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/writing-code-in-the-code-and-text-editor?utm_source=VisualStudio&utm_medium=aspnet-getstarted&utm_campaign=VisualStudio&view=vs-2022#generate-fix-or-refactor-code)
* Content Source: [docs/ide/writing-code-in-the-code-and-text-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/writing-code-in-the-code-and-text-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
