### ISSUE TITLE
I cannot find Autos window at all. Can you please explain why and how to fix? Thx

### ISSUE THREAD

**Issue by LEAAN** [MicrosoftDocs/visualstudio-docs#7705]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba01381-dfb4-7830-e86c-1ee94f346b03
* Version Independent ID: 11513787-4812-9d2d-3288-82d3dc73012d
* Content: [Inspect variables - Autos and Locals windows - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/autos-and-locals-windows?view=vs-2022)
* Content Source: [docs/debugger/autos-and-locals-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/autos-and-locals-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Closing as not enough info (no repro). If this is still an issue, please let me know. You may need to use the Report a Problem too.
