### ISSUE TITLE
Need grammatical correction of this sentence on this page...

### ISSUE THREAD

**Issue by dbkudale** [MicrosoftDocs/visualstudio-docs#7713]
Need grammatical correction of this sentence on this page:
Wrong sentence: With XAML Hot Reload, you can incrementally build and test XAML code for **your your** WPF and UWP apps.
Correct sentence: With XAML Hot Reload, you can incrementally build and test XAML code for **your** WPF and UWP apps.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32cf985-f78d-371b-6f1a-687005169704
* Version Independent ID: 7f543c79-af0f-ebf0-67f3-446e425891a4
* Content: [XAML Hot Reload for WPF and UWP apps - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2022&source=docs#feedback)
* Content Source: [docs/xaml-tools/xaml-hot-reload.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xaml-tools/xaml-hot-reload.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@dbkudale Thanks for bringing this to our attention! We've fixed this. We'll close this issue now, with our further thanks to you for helping to improve the documentation.
