### ISSUE TITLE
Extreamly helpful in uninstalling a complex VIsual Studio install

### ISSUE THREAD

**Issue by Bookworm370** [MicrosoftDocs/visualstudio-docs#7715]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 030a8363-a4d4-9391-0fc2-554656b905fc
* Version Independent ID: 4a056ae9-03cb-074f-cffa-037f780dfbaf
* Content: [Uninstall Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall?view=vsmac-2019#net-core-script)
* Content Source: [mac/uninstall.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/uninstall.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-install**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
@Bookworm370 -- George, thank you for your kind words regarding this article.  They are much appreciated.
