### ISSUE TITLE
Issue with Documentation when running in Docker

### ISSUE THREAD

**Issue by justin-appointmentreminder** [MicrosoftDocs/visualstudio-docs#7719]
HI,

Could not get this to work at all following on page instructions, every single time the API app started on a port 49135, no matter what I changed in the launchSettings.json (as per the documentation). My issue was running in docker, so had to add httpPort and sslPort to the docker profile in the launchsetting.json (shown below)
```
  "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,   
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
      "publishAllPorts": true,
      "useSSL": true,
      "httpPort": 5003,   //<---- This
      "sslPort": 5001      //<---- And This
    }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@justin-appointmentreminder Thanks, that is very helpful. Please take a look at MicrosoftDocs/visualstudio-docs#7413 for another workaround and let me know what you think. It appears helpful to add the information you have provided here about launchSettings.json, so I will plan to add that.
