### ISSUE TITLE
Invalid example setting collection->SomeStrings = new Collection

### ISSUE THREAD

**Issue by colbroth** [MicrosoftDocs/visualstudio-docs#772]
In the example, the code shows   collection->SomeStrings = newCollection; But the class indicates the property setter violates the warning. I believe the example should remove the line of code "collection->SomeStrings = newCollection;" as it is not needed. The Clear and AddRange will set the SomeStrings value.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8db6af07-b7d6-9395-223e-1a0f83fb2405
* Version Independent ID: 5ee87730-ff01-2571-494e-91d29c5fe211
* Content: [CA2227: Collection properties should be read only - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2227-collection-properties-should-be-read-only)
* Content Source: [docs/code-quality/ca2227-collection-properties-should-be-read-only.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/ca2227-collection-properties-should-be-read-only.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@colbroth thank you for the feedback! I will look into this.

**Comment by gewarren** [comment]
@colbroth I looked at this a little more closely, and while it probably could be made more clear in the code comments, I think the example was intentionally written that way. It's trying to show that if the collection property is *not* read only, the entire collection can be replaced in that line of code. I'll update the code comments to make this more clear.
