### ISSUE TITLE
This option is not available in Visual Studio 2022 17.1

### ISSUE THREAD

**Issue by RikaEndo0** [MicrosoftDocs/visualstudio-docs#7725]
Starting with Visual Studio 2022 17.1, the debug section is missing from the React project's properties menu. It has been modified to launch with the launch.json option by default, so step 3 is not required.

https://github.com/MicrosoftDocs/visualstudio-docs/blob/4939b942c2eb73655c82eb810f33588ff1851477/docs/javascript/tutorial-asp-net-core-with-react.md#set-the-project-properties

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review this update in [private PR 9759](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/9759).

**Comment by RikaEndo0** [comment]
It looks like the documentation hasn't been fixed yet. Could you please delete step 3?

**Comment by Mikejo5000** [comment]
It looks like it's updated now.

**Comment by RikaEndo0** [comment]
I confirmed that the note was added. Thank you for your support!
