### ISSUE TITLE
error cs0239

### ISSUE THREAD

**Issue by mattiafrega** [MicrosoftDocs/visualstudio-docs#7729]
The guide results in errore code CS0239 when Rebuilding the Solution after adding the custom code classes.

![error2](https://user-images.githubusercontent.com/62997722/156181802-b32792d3-483b-4b0b-a25d-44a48acaa41e.png)

"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0239	'TrackingPropertyDSLPackage.Initialize()': cannot override inherited member 'AsyncPackage.Initialize()' because it is sealed	DslPackage	C:\Users\matti\source\repos\TrackingPropertyDSL\DslPackage\CustomCode\Package.cs	8	Active
"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edee447c-4c13-6d94-d33f-da1a145cada4
* Version Independent ID: 57ba4012-9250-4ffb-eb8d-3047f380af47
* Content: [Add tracking property to DSL definition - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/adding-a-tracking-property-to-a-domain-specific-language-definition?view=vs-2022)
* Content Source: [docs/modeling/adding-a-tracking-property-to-a-domain-specific-language-definition.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/adding-a-tracking-property-to-a-domain-specific-language-definition.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
@mattiafrega That changed sometime in Dev16 when support for AsyncPackages was added. The method to override now is [InitializeAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.asyncpackage.initializeasync?view=visualstudiosdk-2022).
