### ISSUE TITLE
Missing the "Debugging section" in the Properties menu.

### ISSUE THREAD

**Issue by hultsk** [MicrosoftDocs/visualstudio-docs#7731]
So when following the "Tutorial: Create an ASP.NET Core app with React in Visual Studio" in step 3, im supposed to right-click the React project and select the Properties menu and go the Debugging section. Change the Debugger to launch to the launch.json option. 

The problem is that option dosent show up for me. 

![image](https://user-images.githubusercontent.com/94978179/156244035-bfa460ac-6c40-4693-828a-b1cceb4cd8f3.png)
 
Also later in development i got this error "Error TS6053 node_modules/agent-base/dist/src/index' not found. The file is in the program because: Root file specified for compilation" which i asume is correlated with this missing step in the tutorial?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@hultsk Hi, thanks for the feedback. This is a UI bug. Would you please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
@orzech123123 There is a known bug around this that should be fixed in a coming update.

If you are on a localized version, you might try updating to [SDK version 0.5.7-alpha](https://www.nuget.org/packages/Microsoft.VisualStudio.JavaScript.SDK/0.5.7-alpha), although you may still run into the other bug. Let me know if that helps.

Also, are you using a new project? Or opening a previously created project in VS? If it's an older project, you might try creating a new one.

I can ask about a workaround.

**Comment by Mikejo5000** [comment]
@orzech123123 More info: The default path for the launch.json is under .vscode/launch.json. so if the launch.json is already there (all our templates put it there by default) then F5/debugging will work with no problems. So in most cases, the workaround is to just skip the step for accessing the config page.

This is a known product bug that will likely be fixed shortly in a VS update. I'm adding a relevant note in the docs.

**Comment by hultsk** [comment]
@orzech123123, I did as @Mikejo5000 said and skipped the step for accessing the config page. Works well, the only problem I have is that i got a lot of error message regarding Type script. Dont know if this is related, but these "errors" can be deisabled in settings in VS

**Comment by Mikejo5000** [comment]
@kenzie-gossett I am hoping it gets fixed in VS 2022 Update 2, but I don't know yet. Please see my earlier comment about the workaround.

**Comment by joj** [comment]
I checked this this morning. The right click is supposed to happen on the webapi project. The screenshot on the first comment is from the react project. The doc states this:
In Solution Explorer, right-click the ASP.NET Core project and choose Properties.
