### ISSUE TITLE
Is this page relevant for Visual Studio 2022? 

### ISSUE THREAD

**Issue by kjlk2j3sd** [MicrosoftDocs/visualstudio-docs#7733]
Is this page relevant for Visual Studio 2022?  If so the page clearly has a "doc bug" as it says "Visual Studio is only supported on devices using a x86 or AMD64/x64 based processor.".  But Visual Studio 2022 is not supported on an x86 device, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5a7fdd5-9d50-a1ee-62b3-ab6457e392d2
* Version Independent ID: 81da91ce-8fe0-d919-2f91-123d4ec44430
* Content: [Visual Studio on ARM powered devices - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022)
* Content Source: [docs/install/visual-studio-on-arm-devices.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/visual-studio-on-arm-devices.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@kjlk2j3sd, thank you for the feedback. We've updated the [page ](https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022)and it should be live later today.

Please let us know if you have any other questions or feedback. Thanks!
