### ISSUE TITLE
Would like to see documented where Solution Property Pages are stored 

### ISSUE THREAD

**Issue by SpocWeb** [MicrosoftDocs/visualstudio-docs#7738]
While it is nice to edit these Settings manually, we must be able to add them to Source Control. 
Project Properties are stored in the *.csproj but I couldn't find where the List of Startup Projects is stored. 
![image](https://user-images.githubusercontent.com/10584012/156519393-641ed5f5-93b6-4071-a389-293f950fee4b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ee03d-4ce2-07ac-4158-8cde123e95eb
* Version Independent ID: 1aa8e54a-17cf-5a32-4ea4-adcdadeae5cf
* Content: [Manage project and solution properties - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/managing-project-and-solution-properties?view=vs-2022)
* Content Source: [docs/ide/managing-project-and-solution-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/managing-project-and-solution-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Taysser-Gherfal -- Taysser, please look into this issue.

**Comment by drewnoakes** [comment]
@SpocWeb thanks for your feedback. I think your request is similar in spirit to [this feedback ticket](https://developercommunity2.visualstudio.com/t/Persist-startup-projects-in-solution-/1678968). You can vote and comment on that issue so the owning team understands your scenario.

Today the startup project(s) are stored in the `.suo` file, which should not be added to version control.

**Comment by TerryGLee** [comment]
@drewnoakes Thanks for your input! @SpocWeb, we've added information about the Solution User Options file type to the page, which should appear later this afternoon. We'll close this issue now, with our thanks to you for your interest in improving the Visual Studio documentation!
