### ISSUE TITLE
Suppress this warning for exceptions in portable class libraries

### ISSUE THREAD

**Issue by S-List** [MicrosoftDocs/visualstudio-docs#774]
As serialization doesn't seem to be available for Portable Class Libraries, I guess it is also OK to suppress this warning for exceptions in these libraries when the other three constructors are implemented.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a55e7ba0-f8c0-68fb-d2db-c8b45d60c4ad
* Version Independent ID: e21c9a8e-faf0-e484-f8b0-f8e991b1e601
* Content: [CA1032: Implement standard exception constructors - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/code-quality/ca1032-implement-standard-exception-constructors)
* Content Source: [docs/code-quality/ca1032-implement-standard-exception-constructors.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/ca1032-implement-standard-exception-constructors.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@S-List thanks for the feedback. I'll confirm this and update the doc as necessary.

**Comment by gewarren** [comment]
@S-List were you seeing this warning from Roslyn-based FxCop analyzers, or the legacy FxCop?
