### ISSUE TITLE
Visual Studio DataBinding using Property Window, DataContext, Create DataBinding Dialog WPF

### ISSUE THREAD

**Issue by HerbertFeichtinger** [MicrosoftDocs/visualstudio-docs#7741]
After searching the usual books (Troelsen C#, Christian Nagel C#, ...) newest edition and the Web, I see that the handling of  DataContext / DataBinding Property/Dialog in Visual Studio is practically nowhere described.
I do not consider the Property Window DataContext nor the New dialog intuitive and propose better guidance for the most often used situations:
- binding XAML element to single POCO object
- binding ListView, Tree, Grid to .NET Collection.

There is still to much I must know about databinding (plumbing).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b34372fb-6376-fcd2-97cc-6b1520748999
* Version Independent ID: 358bc6fc-b41c-538e-5b90-55dbcff51309
* Content: [Bind to data in XAML Designer - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/walkthrough-binding-to-data-in-xaml-designer?view=vs-2022)
* Content Source: [docs/xaml-tools/walkthrough-binding-to-data-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xaml-tools/walkthrough-binding-to-data-in-xaml-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@HerbertFeichtinger Thanks for reaching out. We've added a link to the page that describes more about how to [Bind controls to data in Visual Studio](https://docs.microsoft.com/visualstudio/data-tools/bind-controls-to-data-in-visual-studio); this page also contains links to further info on the subject, such as one to the [Visual Studio data tools for .NET](https://docs.microsoft.com/visualstudio/data-tools/visual-studio-data-tools-for-dotnet) and more. We hope this proves useful to you and to others. We'll close this issue now, with our thanks to you for helping to improve the documentation!
