### ISSUE TITLE
Could not convert to integer 3221225477, Path 'exitCode'. Value was either too large or too small for an Int32

### ISSUE THREAD

**Issue by sglvladi** [MicrosoftDocs/visualstudio-docs#7748]
When trying to run the [Call the DLL from Python](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022#call-the-dll-from-python) section, nothing gets printed on screen and the console simply prompts me to press any key. Upon closing the terminal, I get a Visual Studio error window, with the following description:

``Could not convert to integer 3221225477, Path 'exitCode'. Value was either too large or too small for an Int32``

For reference, I have only followed the PyBind11 section, and my `.py` and `.cpp` files are shown below:
* ``main.py``
```python
from random import random
from time import perf_counter
from superfastcode import fast_tanh

COUNT = 500000  # Change this value depending on the speed of your computer
DATA = [(random() - 0.5) * 3 for _ in range(COUNT)]

e = 2.7182818284590452353602874713527

def sinh(x):
    return (1 - (e ** (-2 * x))) / (2 * (e ** -x))

def cosh(x):
    return (1 + (e ** (-2 * x))) / (2 * (e ** -x))

def tanh(x):
    tanh_x = sinh(x) / cosh(x)
    return tanh_x

def test(fn, name):
    start = perf_counter()
    result = fn(DATA)
    duration = perf_counter() - start
    print('{} took {:.3f} seconds\n\n'.format(name, duration))

    for d in result:
        assert -1 <= d <= 1, " incorrect values"

if __name__ == "__main__":
    print('Running benchmarks with COUNT = {}'.format(COUNT))

    test(lambda d: [tanh(x) for x in d], '[tanh(x) for x in d] (Python implementation)')

    test(lambda d: [fast_tanh(x) for x in d], '[fast_tanh(x) for x in d] (PyBind11 C++ extension)')
```
* ``module.cpp``:
``` c++
#include <pybind11/pybind11.h>

#include <Windows.h>
#include <cmath>

const double e = 2.7182818284590452353602874713527;

double sinh_impl(double x) {
    return (1 - pow(e, (-2 * x))) / (2 * pow(e, -x));
}

double cosh_impl(double x) {
    return (1 + pow(e, (-2 * x))) / (2 * pow(e, -x));
}

double tanh_impl(double x) {
    return sinh_impl(x) / cosh_impl(x);
}

namespace py = pybind11;

PYBIND11_MODULE(superfastcode, m) {
    m.def("fast_tanh", &tanh_impl, R"pbdoc(
        Compute a hyperbolic tangent of a single argument expressed in radians.
    )pbdoc");

#ifdef VERSION_INFO
    m.attr("__version__") = VERSION_INFO;
#else
    m.attr("__version__") = "dev";
#endif
}
```

I should not that the above error occurs during the import statement ``from superfastcode import fast_tanh``.

Any clues? Thanks much in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by rjmolyneaux** [comment]
Hi @sglvladi, 
I'm sorry to hear that you're having difficulty with this. The [Troubleshooting Import Errors](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022#troubleshoot-importing-errors) section should help mitigate import errors. If any of these steps do not provide you with a solution, please feel free to reach out. We'll do our best to assist!

**Comment by rjmolyneaux** [comment]
@WilliamAntonRohm - Are we able to transfer this issue to the microsoft/PTVS repo, so the product team can properly triage?

Cc: @int19h

**Comment by WilliamAntonRohm** [comment]
@rjmolyneaux -- Ryan, I created a new issue in that repo, as noted above:  
- https://github.com/microsoft/PTVS/issues/6931

@sglvladi -- Lyudmil, I am closing this issue now, as it will be addressed in the other repo.  They will follow up with you from there.
