### ISSUE TITLE
Excel connection string - defaultdir

### ISSUE THREAD

**Issue by haragopal87** [MicrosoftDocs/visualstudio-docs#775]
Excel connection string works only when default dir is provided as "defaultdir=.\;" instead of "defaultdir=.;" without quotes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d4d170-fcf4-6caf-da44-dfe6e194a257
* Version Independent ID: c980b0f6-ed24-9c4a-0b2e-77962aafc81d
* Content: [Walkthrough: Using a Configuration File to Define a Data Source in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-using-a-configuration-file-to-define-a-data-source)
* Content Source: [docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/walkthrough-using-a-configuration-file-to-define-a-data-source.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@haragopal87 thank you for the feedback. I'll update the doc.
