### ISSUE TITLE
Error "directory is invalid" when choosing Standalone Typescript Angular template in VS 2022 17.1

### ISSUE THREAD

**Issue by prakash-manit** [MicrosoftDocs/visualstudio-docs#7751]
Team- 
when project is created in a new solution and solution and project names being different and “add integration for empty asp.net web api” option is selected, getting "directory is invalid".

Please check this and in the time being you may add this as known error in the doc.

Thanks,
Prakash

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by travis-icorein** [comment]
I get the same error even with it unchecked. 

<details>
<summary>VS "about" diag info</summary>

> Microsoft Visual Studio Community 2022
> Version 17.1.3
> VisualStudio.17.Release/17.1.3+32328.378
> Microsoft .NET Framework
> Version 4.8.04084
> 
> Installed Version: Community
> 
> Visual C++ 2022   00482-90000-00000-AA398
> Microsoft Visual C++ 2022
> 
> .NET Core Debugging with WSL   1.0
> .NET Core Debugging with WSL
> 
> ADL Tools Service Provider   1.0
> This package contains services used by Data Lake tools
> 
> ASA Service Provider   1.0
> 
> ASP.NET and Web Tools 2019   17.1.358.51495
> ASP.NET and Web Tools 2019
> 
> ASP.NET Web Frameworks and Tools 2019   17.1.358.51495
> For additional information, visit https://www.asp.net/
> 
> Azure App Service Tools v3.0.0   17.1.358.51495
> Azure App Service Tools v3.0.0
> 
> Azure Data Lake Tools for Visual Studio   2.6.5000.0
> Microsoft Azure Data Lake Tools for Visual Studio
> 
> Azure Functions and Web Jobs Tools   17.1.358.51495
> Azure Functions and Web Jobs Tools
> 
> Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
> Microsoft Azure Stream Analytics Tools for Visual Studio
> 
> C# Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
> C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> Cookiecutter   17.0.21344.1
> Provides tools for finding, instantiating and customizing templates in cookiecutter format.
> 
> Extensibility Message Bus   1.2.6 (master@34d6af2)
> Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.
> 
> Fabric.DiagnosticEvents   1.0
> Fabric Diagnostic Events
> 
> Microsoft Azure Hive Query Language Service   2.6.5000.0
> Language service for Hive query
> 
> Microsoft Azure Service Fabric Tools for Visual Studio   17.0
> Microsoft Azure Service Fabric Tools for Visual Studio
> 
> Microsoft Azure Stream Analytics Language Service   2.6.5000.0
> Language service for Azure Stream Analytics
> 
> Microsoft Azure Tools for Visual Studio   2.9
> Support for Azure Cloud Services projects
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft Library Manager   2.1.161+abc97ecc7d.RR
> Install client-side libraries easily to any web project
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio Tools for Containers   1.2
> Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> Mono Debugging for Visual Studio   17.1.10 (65f98f5)
> Support for debugging Mono processes with Visual Studio.
> 
> Node.js Tools   1.5.40105.1 Commit Hash:1822ee94b29c6cf748a19825f14cc26d30b0b871
> Adds support for developing and debugging Node.js apps in Visual Studio
> 
> NuGet Package Manager   6.1.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/
> 
> Office Developer Tools for Visual Studio   17.0.32009.00
> Microsoft Office Developer Tools for Visual Studio
> 
> Python - Django support   17.0.21344.1
> Provides templates and integration for the Django web framework.
> 
> Python - Profiling support   17.0.21344.1
> Profiling support for Python projects.
> 
> Python with Pylance   17.0.21344.1
> Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.
> 
> Razor (ASP.NET Core)   17.0.0.2206201+62a2c1d6162f828801565a7ca26d9d48b810a05b
> Provides languages services for ASP.NET Core Razor.
> 
> SQL Server Data Tools   17.0.62203.25080
> Microsoft SQL Server Data Tools
> 
> ToolWindowHostedEditor   1.0
> Hosting json editor into a tool window
> 
> TypeScript Tools   17.0.1229.2001
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Basic Tools   4.1.0-5.22165.10+e555772db77ca828b02b4bd547c318387f11d01f
> Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.
> 
> Visual F# Tools   17.1.0-beta.21610.4+07b5673e4f2fa7630e78abe37f16b372353a7242
> Microsoft Visual F# Tools
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Container Tools Extensions   1.0
> View, manage, and diagnose containers within Visual Studio.
> 
> Visual Studio IntelliCode   2.2
> AI-assisted development for Visual Studio.
> 
> Visual Studio Tools for Containers   1.0
> Visual Studio Tools for Containers
> 
> VisualStudio.DeviceLog   1.0
> Information about my package
> 
> VisualStudio.Foo   1.0
> Information about my package
> 
> VisualStudio.Mac   1.0
> Mac Extension for Visual Studio
> 
> Workflow Manager Tools 1.0   1.0
> This package contains the necessary Visual Studio integration components for Workflow Manager.
> 
> Xamarin   17.1.0.324 (d17-1@590ddb7)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin Designer   17.1.0.87 (remotes/origin/main@d50fb5635)
> Visual Studio extension to enable Xamarin Designer tools in Visual Studio.
> 
> Xamarin Templates   17.1.8 (590388a)
> Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.
> 
> Xamarin.Android SDK   12.2.0.4 (d17-1/19b97b7)
> Xamarin.Android Reference Assemblies and MSBuild support.
>     Mono: a5d1934
>     Java.Interop: xamarin/java.interop/d17-1@7ac33610
>     ProGuard: Guardsquare/proguard/v7.0.1@912d149
>     SQLite: xamarin/sqlite/3.37.1@0893b3b
>     Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-1@db125a7
> 
> 
> Xamarin.iOS and Xamarin.Mac SDK   15.8.0.2 (79ddd0840)
> Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

**Comment by oamm** [comment]
I have the same issue, 
When i try to create a Standalone Typescript Angular  VS 2022 throw me the same message,
but i notice that ocurr only when i change the project name, i don't know what happen it when the name is changed

**Comment by WilliamAntonRohm** [comment]
@prakash-manit, @travis-icorein, @oamm -- please add your feedback here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

**Comment by travis-icorein** [comment]
Thanks for pointing me in the right direction.  It has been reported and a fix expected to be a part of VS 17.2 preview 3, as per [this comment](https://developercommunity.visualstudio.com/t/Standalone-Typescript-Angular-directory/1668068#T-N1700957) (for any others who end up here).

**Comment by Mikejo5000** [comment]
17.2 is released. If this is still an issue, let us know.

**Comment by excellent-1** [comment]
When adding a standalone typescript angular project to my solution (in Visual Studio 2022 17.4.4) I receive the error "Illegal characters in path" everytime.

**Comment by Mikejo5000** [comment]
@excellent-1  I can run the standalone typescript angular project in VS 2022 17.5 Preview 5 without any errors. It sounds like this only happens when you add the project to an already existing solution? To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
