### ISSUE TITLE
Some information is incorrect/out of date

### ISSUE THREAD

**Issue by mkstarr** [MicrosoftDocs/visualstudio-docs#7755]
I am guessing a lot is out of date or incorrect, but I'm using VS Code, and there's no options further under "New", just "New File" and "New Window". I didn't bother finishing reading your article because I'm looking for the information I need, not doing free debugging for Microsoft (which I'm guessing it gets a lot of, but could use more badly).

Good day.
Mike

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d9f53c-6ece-ea3c-9a51-9edd0efeebe3
* Version Independent ID: 9c927a8e-3ebd-0c8a-76cc-9b1c980b98a3
* Content: [Create projects & solutions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/creating-solutions-and-projects?view=vs-2022)
* Content Source: [docs/ide/creating-solutions-and-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/creating-solutions-and-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by j-martens** [comment]
@mkstarr This article is for Visual Studio, not VS Code.  You can find VS Code docs here: https://code.visualstudio.com/docs

If you have specific feedback about Visual Studio documentation, please let us know. 

Have a good day.
