### ISSUE TITLE
Visual Studio Team Services - Amount of users

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#776]
Hello,

It was my understanding that as part of the benefit through VSS, VSTS accounts for Standard subscriptions provided the new users with 5 free users initially, with the opportunity to purchase more if needed and that Cloud subscriptions had unlimited users for free. Is this no longer true?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34c186b2-096e-e066-ed2c-6ae725c5eff1
* Version Independent ID: b93a5dea-8d1f-eb84-0248-5b1fbf2f7638
* Content: [VSTS benefits for Visual Studio subscribers](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-vsts)
* Content Source: [subscriptions/vs-vsts.md](https://github.com/Microsoft/visualstudio-docs/blob/master/subscriptions/vs-vsts.md)
* Service: **unspecified**
* GitHub Login: @ghogen

**Comment by TerryGLee** [comment]
@Nathan-Tarin Thanks for your inquiry and apologies for the late reply.
@evanwindom @prrana Is this something you could help with?

**Comment by evanwindom** [comment]
@Nathan-Tarin Hi Nathan.  The details of what is provided in terms of Azure DevOps (formerly VSTS) are available here:  https://azure.microsoft.com/en-us/services/devops/compare-features/ 

Additional information about Azure DevOps is available in the Azure DevOps documentation, https://docs.microsoft.com/en-us/azure/devops/?view=vsts

**Comment by TerryGLee** [comment]
@evanwindom Thanks for answering the inquiry. I will close this now.
