### ISSUE TITLE
Why the hell Visual Studio suggests updating to a bugged version?!

### ISSUE THREAD

**Issue by Zilkode** [MicrosoftDocs/visualstudio-docs#7760]
[Enter feedback here]
If this is a known issue then why the hell you suggested me to update my VS version?!?!
What the F happen to Visual Studio product manager he became retarded or something?!
Since last year every single update of Visual Studio is bugged and faulty, every update is worse than the one before!
Crashes, GPU overwhelming, tons of memory eager processes just to debug, custom preferences reset, Hot reload break and this is only partial list. WHAT THE HELL?!

So now I am stuck with buggy Visual Studio environment, and I need to choose between reinstalling improper netcore version and reinstalling Visual Studio just because you were too moron not to block failed version.

Is it ever going to change or should I move to IntelliJ now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09335e11-79f7-cb3d-e62f-6c8297093e61
* Version Independent ID: 09335e11-79f7-cb3d-e62f-6c8297093e61
* Content: [Visual Studio for Mac 8.10 and .NET on Apple Silicon machines - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/uninstall-net-2019?view=vsmac-2019)
* Content Source: [mac/uninstall-net-2019.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/uninstall-net-2019.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
@Zilkode -- Tomer, thank you for your thorough feedback.  Please consider adding these issues here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again!
