### ISSUE TITLE
Page outdated for Visual Studio 2022 .Net Projects

### ISSUE THREAD

**Issue by jlinstrum** [MicrosoftDocs/visualstudio-docs#7762]
This page seems to be outdated for .Net 6 projects under Visual Studio 2022. At least the large graphic showing the project properties is different than what I'm seeing on my .Net 6 console app. It would be nice if there were a link to the other format so I could follow along better. MS info relating to the new format is a bit scanty:

    https://devblogs.microsoft.com/visualstudio/revamped-project-properties-ui/
    
Regards,
John Linstrum

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4938a042-e5db-4f9c-2288-930b904e888c
* Version Independent ID: 6db1e386-22e4-4940-cc2c-bdeaa5883299
* Content: [Change the build output directory - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2022)
* Content Source: [docs/ide/how-to-change-the-build-output-directory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-the-build-output-directory.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@jlinstrum 
Thanks for pointing that out. I'm updating the image now.
