### ISSUE TITLE
Could not get this to work on VS2022

### ISSUE THREAD

**Issue by geoffongit** [MicrosoftDocs/visualstudio-docs#7764]
Document was ok to  Databind the model to the XAML page step 5.  

Seemed when using VS2022 the resource failed to create.  <Grid DataContext="{StaticResource customerViewSource}">

Instructions did work on VS2019

Geoff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c0fa43-0ca5-9c86-f8c4-4b3eb7176250
* Version Independent ID: bb93e3ff-0d52-9e93-c3a8-545b16f03a30
* Content: [Simple data app with WPF and Entity Framework 6 - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2022)
* Content Source: [docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@geoffongit 
There is a product issue in Visual Studio 2022 with the databinding step. It should be fixed in one of the upcoming updates. Thanks,
Gordon
