### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by muhammadashkir** [MicrosoftDocs/visualstudio-docs#7765]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b29bb94e-46c2-5fae-7178-a9c4f2331c03
* Version Independent ID: b29bb94e-46c2-5fae-7178-a9c4f2331c03
* Content: [Tutorial: Add math problems to a Windows Forms app - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-math-quiz-add-math-problems?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-math-quiz-add-math-problems.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-math-quiz-add-math-problems.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@muhammadashkir -- thank you for your feedback.  Please provide additional information about your intended task.  Meanwhile, consider these resources:
