### ISSUE TITLE
'important note' about Visual Studio bookmarks seems to be mistaken.

### ISSUE THREAD

**Issue by elenzil** [MicrosoftDocs/visualstudio-docs#7771]
The [page](https://docs.microsoft.com/en-us/visualstudio/ide/setting-bookmarks-in-code?view=vs-2022) about visual studio bookmarks has the following:

> Important: The bookmark is set to the line number, not to the code. If you modify the code, the bookmark is retained at the line number, and does not move with the code.

Happily, this note seems to be mistaken.
If I set a bookmark at line 100, and then go and insert 5 lines up at line 50, the bookmark stays attached to the lines of text I put it on, which are now at line 105.  Even if I edit the file in an external text editor (ie, not Visual Studio) it works this way.   I can only get the behavior described by editing the file while VS is actually closed.  The way it's working is definitely the way I want it to work.  Just the documentation note seems wrong or at least a little misleading.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac5a1c94-4cd3-3519-d437-491b4c19c9fb
* Version Independent ID: 807d3d11-fd62-b359-e0c7-06033ba252cf
* Content: [Set code bookmarks - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/setting-bookmarks-in-code?view=vs-2022)
* Content Source: [docs/ide/setting-bookmarks-in-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/setting-bookmarks-in-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@elenzil You're absolutely right about this; we've updated the page accordingly by removing the Note. We apologize for the delay in doing so, but we'll close this issue now with our thanks to you for helping to improve the Visual Studio documentation!

**Comment by ToMakeSense** [comment]
> I can only get the behavior described by editing the file while VS is actually closed.

@elenzil  You are working in a team, your colleagues add/remove some lines of code ahead of where you set a bookmark, when you sync the code, you will get the similar situation，this is common situation.
