### ISSUE TITLE
Incorrect Wording

### ISSUE THREAD

**Issue by myxxmikeyxx** [MicrosoftDocs/visualstudio-docs#7773]
"549472fa-f3be-53bc-cf9f-170c1183c834"
On [This Page](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2022#populate-the-tables-with-data)
At **[Populate the tables with data](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-sql-database-by-using-a-designer?view=vs-2022#populate-the-tables-with-data)**
Item number 3 says `Open the shortcut menu for the Customers table, and then select **View Data**.`
But if you are using **Server Explorer** it actually says **Show Table Data** not **View Data**
While if you use **SQL Server Object Explorer** it does say **View Data**
This was just mildly confusing since the wording is different depending on which view you are using.
Not sure if you wanted to change it to `Open the shortcut menu for the Customers table, and then select  **Server Explorer** or **View Data**.`

The reason I would put **Show Table Data** first is because in item number 1 it list **Server Explorer** before **SQL Server Object Explorer**. This would just infer that the first item lines up with the first option and the second item with the second option.

 **Server Explorer** right click menu says  **Server Explorer**
 **SQL Server Object Explorer** right click menu says **View Data**

**Comment by ghogen** [comment]
@myxxmikeyxx 
Thanks for the suggestion. By the way, you can submit a PR to make the change, right here in this repo. Just click on the Edit button on the top right of the page, edit the document in GitHub, and use GitHub's UI to submit the PR.

**Comment by myxxmikeyxx** [comment]
I will have to do that this weekend.
I did not know that was thing!
