### ISSUE TITLE
%VSINSTALLDIR% is mentioned in docs but no longer exists

### ISSUE THREAD

**Issue by patrikhuber** [MicrosoftDocs/visualstudio-docs#7774]
`%VSINSTALLDIR%` is mentioned on this docs page (or more specifically `%VSINSTALLDIR%\Common7\Packages\Debugger\Visualizers`), but this environment variable doesn't seem to exist anymore, at least on my Windows 11 machine with VS 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@patrikhuber Thanks, it's a good question; the syntax here is an old way of documenting a placeholder; I don't believe it refers to any environment variable, but just the placeholder for the VS install directory. So, for VS 2022, this would be:
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Packages\Debugger\Visualizers.
I'll update the doc with a different syntax.

**Comment by patrikhuber** [comment]
@Mikejo5000 Ah, that makes sense! I think more people than just me would read `%VARIABLE%` as an environment variable (perhaps it was one in the past, I thought so), so the new docs syntax is definitely better. Thanks!

**Comment by rainersigwald** [comment]
The `VSINSTALLDIR` environment variable is defined in `Developer Command Prompt for VS 2022` and related environments.

**Comment by patrikhuber** [comment]
@rainersigwald Good point! I guess when you're reading that docs page, you don't necessarily have a Developer Command Prompt in mind, and you'd more likely use the `explorer`, where putting a location like `%USERPROFILE%\Documents\Visual Studio 2022\Visualizers` works but `%VSINSTALLDIR%\...something...` wouldn't. I think the updated wording is clearer in the given context, but given what you said, the old wording was actually not incorrect/outdated.

**Comment by rainersigwald** [comment]
Yeah, the docs change looks good to me! Just wanted to put that here in case somebody else came looking :)
