### ISSUE TITLE
Nothing on the CS 2019 page is called 'Project Designer'. Unable to find what is being talked about.

### ISSUE THREAD

**Issue by DougRoyer** [MicrosoftDocs/visualstudio-docs#7775]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f82ee03d-4ce2-07ac-4158-8cde123e95eb
* Version Independent ID: 1aa8e54a-17cf-5a32-4ea4-adcdadeae5cf
* Content: [Manage project and solution properties - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/managing-project-and-solution-properties?view=vs-2022)
* Content Source: [docs/ide/managing-project-and-solution-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/managing-project-and-solution-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@DougRoyer Thanks for letting us know. We've updated the "[Project properties](https://docs.microsoft.com/visualstudio/ide/managing-project-and-solution-properties?view=vs-2019#project-properties)" section of this article to clearly mention the [**Project Designer**](https://docs.microsoft.com/visualstudio/ide/reference/project-properties-reference?view=vs-2019), and then included links to more information about it. We hope this addresses your concern; meanwhile, we'll close this issue with our thanks to you for helping to improve the documentation!
