### ISSUE TITLE
Step is possibly outdated

### ISSUE THREAD

**Issue by k3davis** [MicrosoftDocs/visualstudio-docs#7779]
Following these directions with Visual Studio 17.1.1, I can get as far as "Set the project properties" where step 3 seems to be outdated (or missing something). The vue project properties contain Build and Deploy headings only (no Debugging).

Thanks for any assist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@k3davis There is a known bug around this that should be fixed in a coming update.

If you are on a localized version of Visual Studio, you might try updating to [SDK version 0.5.7-alpha](https://www.nuget.org/packages/Microsoft.VisualStudio.JavaScript.SDK/0.5.7-alpha), although you may still run into the other bug. Let me know if that helps.

Also, are you using a new project? Or opening a previously created project in VS? If it's an older project, you might try creating a new one.

**Comment by k3davis** [comment]
@Mikejo5000 Thanks, I'm not looking for an urgent fix as I was previously using a method with VueCliMiddleware package that still works in .NET 6. It's just not the best and I look forward to the underlying experience explained here being improved. But that's unrelated to the docs 🤣

I was following the directions as explicitly as possible, using a new project. The esproj file created has an SDK version of 0.5.7-alpha without any intervention on my part with this VS version. The screen shows a "vueprojectpages Property Pages" modal that I don't know how to open. Right-clicking the vue project and selecting Properties as indicated in the doc has a different experience, like doing so in the API project but with far fewer options.

**Comment by Mikejo5000** [comment]
@k3davis More info: The default path for the launch.json is under .vscode/launch.json. so if the launch.json is already there (all our templates put it there by default) then F5/debugging will work with no problems. So in most cases, the workaround is to just skip the step for accessing the config page.

I will add a note in the docs about this.
