### ISSUE TITLE
Video no longer available

### ISSUE THREAD

**Issue by joseangelmt** [MicrosoftDocs/visualstudio-docs#778]
The videos (in popscreen.com) are no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a762743-426f-ae8a-5c4a-fdb7fcfe250d
* Version Independent ID: b1ec684f-90fc-04f4-19cf-c6b6dce6d078
* Content: [Animate objects in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/animate-objects-in-xaml-designer)
* Content Source: [docs/designers/animate-objects-in-xaml-designer.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/designers/animate-objects-in-xaml-designer.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@joseangelmt thank you for the feedback. I'll get this link updated.
