### ISSUE TITLE
Link texts for "See also" links in some Common Data Views pages are incomplete

### ISSUE THREAD

**Issue by eugenern** [MicrosoftDocs/visualstudio-docs#7788]
For pages within the Common Data Views section, the "See also" links sometimes have descriptive text (Summary, Caller/Callee) and sometimes are vague (Modules, Functions, Lines, Instruction Pointers (IPs), and Call Tree where the links are placed above the "See also" section).
Also, in the Common data views page itself, the pages listed for the section are in a different order from how they're listed in the sidebar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 008c44c0-9bde-99a6-2138-9ca02bce555f
* Version Independent ID: b0679905-0ad5-70e8-ee52-d06bf32b4b3a
* Content: [Common Data Views - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/profiling/common-data-views?view=vs-2017)
* Content Source: [docs/profiling/common-data-views.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/profiling/common-data-views.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@eugenern Thanks for the feedback! These docs are under the Performance Explorer docs, which are available only for VS 2017 and older. We are not making any doc updates in this area.
