### ISSUE TITLE
Deploy wpf application with access database

### ISSUE THREAD

**Issue by shalihamza** [MicrosoftDocs/visualstudio-docs#779]
I build a wpf application using access database now I want to deploy this application. There is no perfect solution in any one. will you help me please share me this idea.
ah85863@gmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30631bf6-bd74-a200-27b4-277ea35325e8
* Version Independent ID: 45a25442-c600-2b20-e815-792bbf67a47a
* Content: [How to: Publish a ClickOnce Application using the Publish Wizard - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard)
* Content Source: [docs/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard.md)
* Service: **unspecified**
* GitHub Login: @stevehoag
* Microsoft Alias: **shoag**

**Comment by gewarren** [comment]
@Mikejo5000 it looks like some topics are still assigned to shoag. Can you see if you can answer this question?

**Comment by Mikejo5000** [comment]
@shalihamza Hi shali, can you clarify the issue you are seeing? Is the Build > Publish option (or the right-click the solution in Solution Explorer and choose Publish) available in your project? What is the VS WPF template you are using, and in what version of VS? What is the limitation you are seeing for your app? Thx

**Comment by shalihamza** [comment]
I deploy my wpf application using visual studio installer with access database. But there is the problem that when I install it on my or other computer application read records but cann't modify it or add new record in it
