### ISSUE TITLE
Impossible to see screen shots with black background!

### ISSUE THREAD

**Issue by plitwin** [MicrosoftDocs/visualstudio-docs#7790]
[Enter feedback here]
Please change your theme to a white background before taking screen shots. The included screen shots are very hard to read. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfc1f93c-4eb8-a2e6-4b09-bf24f4ae444b
* Version Independent ID: cfc1f93c-4eb8-a2e6-4b09-bf24f4ae444b
* Content: [Resolve merge conflicts in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/version-control/git-resolve-conflicts?view=vs-2022)
* Content Source: [docs/version-control/git-resolve-conflicts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-resolve-conflicts.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Taysser-Gherfal
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@plitwin -- Paul, thank for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
