### ISSUE TITLE
Databound bad example?

### ISSUE THREAD

**Issue by foldar** [MicrosoftDocs/visualstudio-docs#7795]
I used to program in multitier, witha  separate datalayer. I don't think with databound the user interface is not separate from the database layer, and therefore you can't use databound forms when you are programming in multitier, which was the way to go in our programming company. Therefore I think a program with databound controls is a bad example for programming. It may be faster, but not good programming.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42c0fa43-0ca5-9c86-f8c4-4b3eb7176250
* Version Independent ID: bb93e3ff-0d52-9e93-c3a8-545b16f03a30
* Content: [Simple data app with WPF and Entity Framework 6 - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6?view=vs-2022)
* Content Source: [docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/create-a-simple-data-application-with-wpf-and-entity-framework-6.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@foldar -- Nico, thank you for your thoughtful feedback.  Please add it here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 


cc @ghogen for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
