### ISSUE TITLE
RegionTableAdapter1 Incorrectly Named

### ISSUE THREAD

**Issue by HopWorks** [MicrosoftDocs/visualstudio-docs#7796]
I am sure it is probably something I did, but I was very methodical on how I followed this example/tutorial. RegionTableAdapter1 was an incorrect name. I had to remove the "1" for this to work. The same applied to another named object where a 1 followed it, as in NorthwindDataSet1. So I wish I understood why these objects were named as if they were a numerical instance of an object, instead of RegionTableAdapter and NorthwindDataSet.

Thank you for the example! It got me over the hump adding, removing, and updating my databases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b2535c6-e0c6-843e-eb22-7aeb0d85397c
* Version Independent ID: 603627ab-5450-e26d-723c-c9ce3b8e4155
* Content: [Save data with the TableAdapter DBDirect methods - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/save-data-with-the-tableadapter-dbdirect-methods?view=vs-2022)
* Content Source: [docs/data-tools/save-data-with-the-tableadapter-dbdirect-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/save-data-with-the-tableadapter-dbdirect-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@HopWorks
Yes, when using VS 2022, I did see the same issue. What version of VS were you using?

**Comment by HopWorks** [comment]
VS2022. I thought that the version was in the header information.

**Comment by HopWorks** [comment]
I appreciate you clarifying this for me. Now it makes sense. As to why my
example from scratch did not have a "1" added is beyond me. Probably some
obscure setting I have not encountered yet.
