### ISSUE TITLE
Is there a command line debugger and disassembler?

### ISSUE THREAD

**Issue by Foadsf** [MicrosoftDocs/visualstudio-docs#7800]
Following [this question](https://github.com/MicrosoftDocs/cpp-docs/issues/3777) and [this Twitter discussion](https://twitter.com/fsfarimani/status/1504099486758539265?s=20&t=SiuLFPHAB87KOgI2mU3ImA), I wonder if there are any command-line debugger and disassemblers? 

I am aware of the `devenv.com` / `devenv.exe` that according to [this](https://docs.microsoft.com/en-us/visualstudio/ide/reference/debugexe-devenv-exe?view=vs-2022) and [this](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2022#:~:text=Devenv%20lets%20you%20set%20various,IDE%20in%20a%20particular%20configuration.) page seem to invoke the MS VS IDE in debugger mode with the command

    devenv /DebugExe "<path\to\executable>.exe"

and of course, it doesn't come with the "minimal installation" that I am looking for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2e06a8c0-39c1-de75-efe3-1f2091a75e5b
* Version Independent ID: 196d81a3-691f-e36a-cc0f-504fcce8daa1
* Content: [View Disassembly Code in the debugger - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-use-the-disassembly-window?view=vs-2022)
* Content Source: [docs/debugger/how-to-use-the-disassembly-window.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/how-to-use-the-disassembly-window.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Foadsf** [comment]
There is `ildasm.exe` but it seems to be specifically for C# and .NET, not for C/C++ compiled executables.

**Comment by Mikejo5000** [comment]
@Foadsf  To be clear, the MSVC toolset you referenced is not what you are looking for? What command-line toolset are you looking for? Thanks! @gregg-miskelly Gregg, do you have any suggestions here, or a contact for this question?

**Comment by gregg-miskelly** [comment]
@Foadsf By "command line debugger", I am assuming you are looking for a console-mode (non-GUI) debugger? If so, the only Microsoft provided console debuggers are cdb.exe/ntsd.exe from the "Debugging Tools for Windows" -- https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/debugger-download-tools

If you are looking for a command line disassemblier, `dumpbin /disasm` can dump out the disassembly of a particular .exe/.dll.

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000, @gregg-miskelly -- Mike, Gregg, thank you for clarifying.


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
