### ISSUE TITLE
Add dotnet template doc for aspnet F#

### ISSUE THREAD

**Issue by jkone27** [MicrosoftDocs/visualstudio-docs#7805]
Please add the dotnet template cli version for aspnet in f#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6c45893-e97e-ba11-c906-46e2abd3d777
* Version Independent ID: eacfee0f-7dda-9ef0-c34d-bfa97fe8cc98
* Content: [Tutorial: Create an ASP.NET Core web service in F# - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-fsharp-web-app?view=vs-2022)
* Content Source: [docs/get-started/tutorial-fsharp-web-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/tutorial-fsharp-web-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@jkone27, thank you for reaching out. It's not clear if your question is related to the[ Tutorial: Create an ASP.NET Core web service in F#](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-fsharp-web-app?view=vs-2022. ) doc. Could you please share some more details on your scenario and the information you are looking for?

Here are some links related to .NET CLI:
- [Get Started with F# Using the .NET CLI](https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/september/fsharp-do-it-all-with-fsharp-on-net-core?msclkid=ee246587aec011ecae8df05e2e4f7c60#get-started-with-f-using-the-net-cli)
- [.NET default templates]( https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new-sdk-templates?msclkid=f1c75901aed811ec8af04a1ccd8da657)
- [dotnet new](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-new?msclkid=b7fd3b54aec111eca377c157c4d0ab0f)

Thanks!

**Comment by jkone27** [comment]
Thanks, sorry i didn't specify i meant dotnet template, like code template to create the F# aspnet solution via dotnet new 
```
dotnet new webapi --language F#
```

**Comment by anandmeg** [comment]
@jmatthiesen, user is not seeing the code template to create the F# aspnet solution via dotnet new on his mac.
