### ISSUE TITLE
Icon design theme color for visual studio 2022

### ISSUE THREAD

**Issue by qwqoq** [MicrosoftDocs/visualstudio-docs#7807]
A big job has been done in Visual Studio 2022 about the icons design. Please update it is icon color design 😁

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: this page does not support. 😢 
* Version Independent ID:  this page does not support.😢 
* Content: [Images and Icons for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2022)
* Content Source: [docs/extensibility/ux-guidelines/images-and-icons-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/extensibility/ux-guidelines/images-and-icons-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-sdk**
* GitHub Login: @leslierichardson95
* Microsoft Alias: **lerich**

**Comment by WilliamAntonRohm** [comment]
@qwqoq -- thank you for your suggestion.  Please add it here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
