### ISSUE TITLE
Repeated Instructions

### ISSUE THREAD

**Issue by hammtronic** [MicrosoftDocs/visualstudio-docs#7810]
I could just be very confused reading this article, but it seems like some of the steps are repeated. The text changes, but not the information, which makes it difficult to understand if it is supposed to be telling me something new.

e.g.:

View Environments steps 4 and 5 - both tell you to hover your cursor over the same thing, to see the same information, with the same explanation of what you will see and why

Install packages using the Python Environments window - this is all messed up

* Step 3 says to select the packages tab, which you have already selected in step 1
* Step 4 says to consent to elevated permissions, which is relevant after doing step 2
* Step 6 says to search matplotlib which you already did (and installed) in step 2
* Step 7 says to install matplotlib which you already did in step 2
* Step 8 says to consent to elevated permissions, which again is relevant after step 7, but step 7 itself isn't relevant any more
* Step 9 says the exact same thing as step 5

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca858db-d7bf-c894-af0a-eb1ba07c29ea
* Version Independent ID: 330f9197-38cd-73b7-c2cc-5d032a3bdc33
* Content: [Python in Visual Studio tutorial step 5, install packages](https://docs.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2022)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by rjmolyneaux** [comment]
Hi @hammtronic,
Thank you for bringing this to our attention. We've updated the docs and eliminated the redundancies. You should expect to see the changes in a few days. We appreciate you taking the time to contribute to Microsoft Docs!

**Comment by rjmolyneaux** [comment]
#please-close
