### ISSUE TITLE
Missing instructions for the `DynamicMemberLookup` intrinsic

### ISSUE THREAD

**Issue by rhoot** [MicrosoftDocs/visualstudio-docs#7814]
Most of the intrinsics on the "Expressions in the debugger" page have arguments documented, as well as some brief text explaining what it does. But I cannot find any usage instructions or examples for `DynamicMemberLookup` neither in this document nor anywhere on the web. Knowing what the arguments are and how it's used would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c9e78f0d-b032-0697-0818-ee7d7c87fa5f
* Version Independent ID: f779a143-1fa6-69a7-ca2c-c7e423384f05
* Content: [Expressions in the debugger - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger?view=vs-2022)
* Content Source: [docs/debugger/expressions-in-the-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/expressions-in-the-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rhoot We added more details to the miscellaneous functions a while ago, mainly because there was feedback that _findnonnull and the TreeTraverse functions were needed for some customer scenarios. I'm not sure if the helper functions are needed for any direct customer scenarios. If you have more information, let me know. Thanks for your feedback!

**Comment by rhoot** [comment]
What I was specifically trying to solve was writing a [natvis file for debugger visualization](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022), for a type containing a member that may or may not exist. Consider a type like this:

```cpp
struct MyType
{
#if defined(_DEBUG)
    const char* debugName;
#endif
};
```

When writing the visualizer for that type I would have to somehow check whether the type was compiled with or without the `debugName` member in the current build, so that I can display it if it exists. If I just _assume_ that it exists, the natvis file fails to load completely when it does _not_ exist, leading to no visualization at all.

The documentation on that page states:

> Because [debugger intrinsic functions](https://docs.microsoft.com/en-us/visualstudio/debugger/expressions-in-the-debugger?view=vs-2022#BKMK_Using_debugger_intrinisic_functions_to_maintain_state) are side-effect free, they may be freely called from any Natvis expression, even though other function calls are disallowed.

Following that link is how I ended up on the page mentioned in this issue. When looking through that list of the miscellaneous functions I spotted `DynamicMemberLookup`, whose description suggests that it _might_ have helped solve my problem. But while it's listed on that page, and there's a brief description of what it does, there's no documentation for how to actually use it. I was thus unable to try it.

It's also very possible I mistook the function for doing more than it does, and that it wouldn't have helped me at all. Without being able to try I couldn't say.

**Comment by Mikejo5000** [comment]
I'll ask about it. Thanks!

**Comment by rhoot** [comment]
Revisiting this: I was able to solve my problem with the `Optional` attribute in the natvis file, which I had somehow missed. If it fails to parse that expression it will instead just skip that field. I'm thus no longer in need of the intrinsic (regardless of what it does), so I'll go ahead and close this again.

Thanks for looking into it nonetheless! 🙂
