### ISSUE TITLE
Python 2.7 is deprecated

### ISSUE THREAD

**Issue by jbrwilkinson** [MicrosoftDocs/visualstudio-docs#7816]
This page mentions Python 2.7 which was deprecated on [1st Jan 2020](https://www.python.org/doc/sunset-python-2/).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2cc4efe-a1a2-b461-baca-d8acf4957382
* Version Independent ID: cc2c9b90-a9b9-29eb-89c2-c9f09521d9e0
* Content: [Unit test Python code - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/unit-testing-python-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/unit-testing-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/unit-testing-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by rjmolyneaux** [comment]
Hi @jbrwilkinson, 
Thank you for bringing this to our attention. With your assistance, we have updated the document to reflect the most recent version of Python. You should see the updated change in the next couple of days! Closing this issue for now.

**Comment by rjmolyneaux** [comment]
#sign-off
