### ISSUE TITLE
How do we modify the default code generated

### ISSUE THREAD

**Issue by weirdyang** [MicrosoftDocs/visualstudio-docs#7824]
[Enter feedback here]
Would be helpful to provide information on how to change the default code generated 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20d270df-0135-8e2f-b47c-e070293e7669
* Version Independent ID: bacb3cc1-342f-92a0-0bf5-c050de84757f
* Content: [Code editor features - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/writing-code-in-the-code-and-text-editor?view=vs-2022#generate-fix-or-refactor-code)
* Content Source: [docs/ide/writing-code-in-the-code-and-text-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/writing-code-in-the-code-and-text-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@weirdyang -- thank you for your question.  Please clarify your intended task.  You can edit the default code directly.

**Comment by weirdyang** [comment]
How do I edit the default code directly?

For example this question;

https://stackoverflow.com/questions/71618670/how-to-edit-default-code-generation-in-vs22?noredirect=1#comment126577331_71618670

**Comment by WilliamAntonRohm** [comment]
@weirdyang -- thank you for your follow-up.  Your question seems to be about coding in general, which is beyond the scope of this documentation.  Please see:
- [Create portable, custom editor settings with EditorConfig](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @TerryGLee

**Comment by weirdyang** [comment]
Hi
No I was wondering how do I cha ge the default code generated when I select refactoring options such as add null checks.

**Comment by WilliamAntonRohm** [comment]
@weirdyang -- please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Reddit](https://www.reddit.com/r/VisualStudio)
