### ISSUE TITLE
modify command with --remove options installs the workloads instead of removing them

### ISSUE THREAD

**Issue by tristanbarcelon** [MicrosoftDocs/visualstudio-docs#783]
I installed Visual Studio Enterprise 15.6.5 from an offline layout which contained the following workloads:
'Microsoft.VisualStudio.Workload.CoreEditor', 'Microsoft.VisualStudio.Workload.Azure', 'Microsoft.VisualStudio.Workload.Data', 'Microsoft.VisualStudio.Workload.Node', 'Microsoft.VisualStudio.Workload.Python', 'Microsoft.VisualStudio.Workload.DataScience', 'Microsoft.VisualStudio.Workload.ManagedDesktop', 'Microsoft.VisualStudio.Workload.NetCoreTools', 'Microsoft.VisualStudio.Workload.NetWeb', 'Microsoft.Component.HelpViewer', 'Microsoft.VisualStudio.Component.LinqToSql', 'Microsoft.VisualStudio.Component.TestTools.CodedUITest', 'Microsoft.VisualStudio.Component.TestTools.Core'

Since I had forgotten to specify specific workloads when running the install command, it installed all of them. I then ran the modify command twice, once to remove the DataScience workload. Exact syntax used was: vs_setup.exe modify --remove Microsoft.VisualStudio.Workload.DataScience --passive --installPath "c:\program files (x86)\Microsoft Visual Studio\2017\Enterprise". I expected it to clear some space on my hard drive but it didn't. The exact opposite happened.

I ran the second modify command to remove the Node and Python workloads. However, instead of removing, I saw Visual Studio installer installing the workloads because that's what it says in the UI. Unfortunately, when i fire up Visual Studio Installer from Start Menu, the 3 workloads are not present. What could be causing this? I'm now down roughly 15-20GB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio#feedback)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by tristanbarcelon** [comment]
Here's a screenshot of what I happened to catch while the modify command was running.

![image](https://user-images.githubusercontent.com/5810165/38401179-4a1ffa2e-3922-11e8-8dd5-662900548534.png)

**Comment by TerryGLee** [comment]
@tristanbarcelon Thanks for letting us know. We'll reply with more information, soon.

**Comment by tristanbarcelon** [comment]
Hi Terry,
     Are you able to confirm whether this is an installation issue or a documentation issue? In other words, can the workloads supplied at time of install be a subset of the workloads downloaded to an offline layout? Likewise, what's the likely explanation for the behavior I've observed? Thanks in advance.

**Comment by AaronValor** [comment]
Is there a command line option for 64 bit?

**Comment by Davsterl** [comment]
Hi Tristan,
This is an installation issue in particular with our use of the Anaconda package. We've fixed the bug in an upcoming release. 
Thanks,
-David Sterling 
Visual Studio Setup Team

**Comment by tristanbarcelon** [comment]
Thank you @Davsterl Is this fix in 15.6.7 or in the 15.7 preview?

**Comment by Davsterl** [comment]
Hi Tristan,
15.7 Preview at the moment.  

Thanks,
-David
