### ISSUE TITLE
visual studio and dpi aware issues

### ISSUE THREAD

**Issue by brownrb** [MicrosoftDocs/visualstudio-docs#7831]
Would it not be a better idea to actually fix this issue which has been around for yonks
I mean lets face it, who actually programs anything at 100% on large 4K screens, No-one. 
It is just nuts that there are so many options that really are not options at all, 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness for scaling in forms - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2022)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@brownrb -- Robert, thank you for your feedback.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

cc @TerryGLee for awareness
