### ISSUE TITLE
Needs updating for Vue 3

### ISSUE THREAD

**Issue by RamblingGeekUK** [MicrosoftDocs/visualstudio-docs#7836]
[Enter feedback here]
In HelloWorld.vue

From Line 31 needs updating to

```   import { defineComponent } from 'vue';

    export default defineComponent({
        data: () => {
            return {
                loading: false,
                post: null
            };
        },
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
Created new bug report:  https://developercommunity.visualstudio.com/t/Standalone-Vue-template----possible-code/10033277.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
