### ISSUE TITLE
outdated

### ISSUE THREAD

**Issue by InternetPseudonym** [MicrosoftDocs/visualstudio-docs#784]
The majority of this document is outdated - it is completely sufficient to install the data connectivity components and select "Microsoft Access Database file" instead of "other" and everything will work from there -- the additional steps are completely unnecessary for VS2017 ... apparently ACCDB files are now supported

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83c5b210-2ecd-fc40-54c9-38a8ba9c7493
* Version Independent ID: a9236354-4965-a214-17f7-746c20de8ec4
* Content: [Connect to data in an Access database (Windows Forms) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/data-tools/connect-to-data-in-an-access-database-windows-forms#feedback)
* Content Source: [docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/data-tools/connect-to-data-in-an-access-database-windows-forms.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by InternetPseudonym** [comment]
yes, i am talking about ACCDB files - MDB works, too

**Comment by gewarren** [comment]
@InternetPseudonym thank you for telling us about this. I will try it out and update the doc as necessary.
