### ISSUE TITLE
Can't nest .razor.css under .razor.scss because of default rules' precedence

### ISSUE THREAD

**Issue by yugabe** [MicrosoftDocs/visualstudio-docs#7852]
Trying to nest .razor.css files under .razor.scss files doesn't work when defining the relevant rules. It seems the default rules take precedence, and first nest .razor.css files under .razor files. 

If there is a project or user-specific ruleset, that should always be evaluated _before_ the global (or higher-level) rulesets.

Reordering the rules are not sufficient, as I don't want to specify all rules in the Web template once more (I want to use the default one supplied with the IDE, in case it gets updated).

Steps to repro: 
```
dotnet new blazorwasm
echo "" > Pages\Index.razor.css
echo "" > Pages\Index.razor.scss
```

When using VS with the Web file nesting template, and creating the .css file, it should nest under the Index.razor file. When also creating the above .scss file, it should nest under the .razor file, then the .css file should nest under the .scss file.

I'd be happy to see this either in the default Web template in VS, or a solution to this specific problem if you could provide a custom .filenesting.json that is NOT a root ruleset. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by WilliamAntonRohm** [comment]
@yugabe -- Gabe, thank you again for your feedback.  Please see the links in my previous comment 
 ~ https://github.com/MicrosoftDocs/visualstudio-docs/issues/7851#issuecomment-1086396673.

@AngelosP -- Angelos, please look into this potential documentation issue.

**Comment by yugabe** [comment]
Thank you for the reply here too! 
I'm going to close this here and move it over to the VS team, as this isn't really related to the docs.

**Comment by costleya** [comment]
As a more simple solution for now, the filenesting.json file is processed in order. If you make a custom one, and just move "addedExtension" to the end, it will work as described.

```
{
  "help": "https://go.microsoft.com/fwlink/?linkid=866610",
  "root": true,

  "dependentFileProviders": {
    "add": {
      "pathSegment": {
        "add": {
          ".*": [
            ".js",
            ".css",
            ".html",
            ".htm",
            ".less",
            ".scss",
            ".coffee",
            ".iced",
            ".config",
            ".cs",
            ".vb",
            ".json"
          ]
        }
      },
      "extensionToExtension": {
        "add": {
          ".js": [
            ".coffee",
...
     "allExtensions": {
        "add": {
        }
      },
      "addedExtension": {

      }
    }
  }
}
```
