### ISSUE TITLE
Heading still saying VS2019 but the rest was updated to VS2022

### ISSUE THREAD

**Issue by mrwellmann** [MicrosoftDocs/visualstudio-docs#7861]
This still saying VS2019 but the rest was updated to VS2022

![Screenshot 2022-04-04 151601](https://user-images.githubusercontent.com/247111/161552039-2868e3c0-eeaf-4c7b-b6ae-ab60a2da211d.png)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a35176f2-ca94-7bb8-08a5-9e415d364ef3
* Version Independent ID: a9f184a6-78b9-315b-4a02-1c93bd4c3940
* Content: [Quickstart: Install & configure Visual Studio Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity?pivots=windows)
* Content Source: [gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/gamedev/unity/get-started/getting-started-with-visual-studio-tools-for-unity.md)
* Product: **visual-studio-dev16**
* Technology: **vs-unity-tools**
* GitHub Login: @therealjohn
* Microsoft Alias: **johmil**

**Comment by WilliamAntonRohm** [comment]
@therealjohn -- John, this entire section is labelled this way.  Please check whether the selector should be Visual Studio 2019 or 2022, and I believe I can make that update.

**Comment by therealjohn** [comment]
@WilliamAntonRohm This section can be changed to just say "Visual Studio". It's the same for both 2019 and 2022. Just like how we labeled it Visual Studio for Mac without the year.

**Comment by WilliamAntonRohm** [comment]
#reassign @WilliamAntonRohm
