### ISSUE TITLE
Unchecking "Enable Just My Code" is required for "Regular" development mode

### ISSUE THREAD

**Issue by kobiga** [MicrosoftDocs/visualstudio-docs#7871]
Took me some time to figure this out. When debugging in regular development mode (meaning, not "fast") no symbols were loaded for the files although the PDBs were in place. The solution for me was Unchecking the "Enable Just My Code" option

If that's a common issue or by design, then I'd suggest adding this to the docs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dd3515a-c60f-141c-a27a-6a22bc47ad1e
* Version Independent ID: 8d117e3a-6089-74ba-1d0f-dd0ad1351fb2
* Content: [Visual Studio Container Tools build and debug overview - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2022)
* Content Source: [docs/containers/container-build.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/container-build.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@kobiga
Thanks for reporting this issue. I'm updating the article to add this information.

**Comment by ghogen** [comment]
@kobiga
Engineering team reports that this is a product bug. I'll close this doc issue.
