### ISSUE TITLE
Visual Studio Perpetual is back

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/visualstudio-docs#7877]
After perpetual software and software subscriptions were merged into "software" in April, a VS 2022 perpetual license was also added. Looks like VS is no longer only available as a subscription?

See screenshots for reference
![image](https://user-images.githubusercontent.com/15677312/162241387-217feb94-7399-472f-a273-979f1d647e7d.png)
![image](https://user-images.githubusercontent.com/15677312/162241947-5814df90-45bc-4b8e-a250-75c8d08bcecb.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f413cb5d-d6c4-2036-62e2-0af9b041ade3
* Version Independent ID: 7c96f714-fb4f-a578-546e-2cfba9366d76
* Content: [Visual Studio cloud subscription purchasing for CSPs](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vscloud-csp)
* Content Source: [subscriptions/vscloud-csp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vscloud-csp.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@jonwbstr -- thank you for your question. 

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@jonwbstr - Thank you for reaching out.  I'm not sure I understand the context of your question.  Are you attempting to purchase cloud subscriptions on behalf of a customer?

**Comment by jonwbstr** [comment]
I am puzzled by your confusion. Let's break this down

Do you see my screenshot?
Do you see in the screenshot where it says "perpetual software" and "visual studio' in the same screen?
Do you see in the screenshot where it shows the breadcrubs that lead to this page (partner center > customers > a customer > subscriptions > add subscription > perpetual software)?
Do you agree that this means the partner center allows partners to purchase visual studio perpetual licenses for a customer?
Have you looked at the software catalog for the month of april to confirm the product exists in the catalog?

Ok, now lets look at the article I'm submitting feedback to.

Do you see where it says "Microsoft no longer offers Visual Studio Professional Annual subscriptions and Visual Studio Enterprise Annual subscriptions in Cloud Subscriptions."?
Do you see where the title of the page is "Buy and manage Visual Studio cloud subscriptions for your customers" ?

If you agree that partners can buy a perpetual license of VS for their customers, and the page says that is not an option, that the page is out of date and should be updated to reflect the current experience?

Let me know where I lost you and we can go from there!
-jon

**Comment by jonwbstr** [comment]
My mistake. I thought perpetuals were no longer available but it's Annual subscriptions that were removed. Perpetual has been around for a while. Apologies. having a how to purchase subscription but not how to purchase perpetual seems a little odd, but it is a straightforward process so I don't particularly see a need for an article either.

have a great weekend

**Comment by evanwindom** [comment]
Thanks for getting back to me.  I have made minor changes to the article to clarify that the monthly subscriptions (non-perpetual) are still available and it’s just the annual subscriptions that aren’t available for new purchases.  I’m also going to make some changes to the other article about purchasing so the volume license path is a little more clear.  That’s for helping us improve our content!
