### ISSUE TITLE
Production Use

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#788]
Also, would it be possible to know within a single source, and not different, scattered, statements, what "Production Use" is and why it isn't allowed within the subscription's licensing terms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2c630f-bb11-e092-d5c1-263ba42fb18e
* Version Independent ID: 80e2c72a-f2b1-2901-5606-c3bf164bc256
* Content: [Visual Studio subscriptions license terms](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-license-terms)
* Content Source: [subscriptions/vs-license-terms.md](https://github.com/Microsoft/visualstudio-docs/blob/master/subscriptions/vs-license-terms.md)
* Service: **unspecified**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@Nathan-Tarin Thanks for your inquiry and apologies for the late reply.
@evanwindom @prrana Is this something that we could update the docs with?

**Comment by evanwindom** [comment]
@Nathan-Tarin Thanks for the feedback.  I'll be happy to forward your request to our licensing team.  I did find a reference in the English license terms that's specific to subscriptions:  
"Additional License Terms for Visual Studio Subscriptions
In addition to the rights in the License Model Terms, Customer may allocate a Visual Studio Subscription for each License it acquires. For Visual Studio Subscriptions, the “Software” means software made available to Customer’s subscription level via Visual Studio Subscription Subscriber Downloads. Any online service made available with Customer’s Visual Studio Subscription may not be used in a Production Environment. "

Hovering over the link for "Production Environment" provides this text:  
"Production Environment means any Physical or Virtual OSE running a production workload or accessing production data, or Physical OSE hosting one or more Virtual OSEs running production workloads or accessing production data."

I hope that information is helpful to you. 

As to providing reasons in the terms for why production use is not permitted, license terms are designed to state the terms, and rarely provide discussion or justification as to why those are the terms.  They are essentially statements of the terms.

**Comment by TerryGLee** [comment]
@evanwindom Thanks for your answer to the inquiry. I'll close this issue now that the inquiry has been "asked and answered" -- and forwarded to the licensing team.
