### ISSUE TITLE
Folder .vs should be .vscode

### ISSUE THREAD

**Issue by CrazedBear** [MicrosoftDocs/visualstudio-docs#7884]
I beleive in this doc 
    %userprofile%\.vs\Extensions
Should be 
    %userprofile%\.vscode\extensions

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* Content: [Add editor support for other languages - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages?view=vs-2022)
* Content Source: [docs/ide/adding-visual-studio-editor-support-for-other-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@CrazedBear -- thank you for your suggestion.  I am investigating.

cc @TerryGLee for awareness
