### ISSUE TITLE
Folders do not exist

### ISSUE THREAD

**Issue by DreamU1952** [MicrosoftDocs/visualstudio-docs#7887]
I have VS2022 installed and neither of the Interop folders mentioned on this page exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88fddd73-1fac-2149-71db-5f20c8c94934
* Version Independent ID: 46e037ee-a5fd-7274-b072-8df92ce70eda
* Content: [Office primary interop assemblies - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/vsto/office-primary-interop-assemblies?view=vs-2022)
* Content Source: [docs/vsto/office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/office-primary-interop-assemblies.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@DreamU1952, did you select the Office Workload and Visual Studio Tools for Office when you installed VS 2022?  The workload is not selected by default.  If you did, the files should be installed to %ProgramFiles(x86)%\Microsoft Visual Studio\Shared\Visual Studio Tools for Office\PIA\ on a 64-bit machine.  If they're still not their please report this from inside Visual Studio using the Help > Send Feedback >  Report a problem menu

**Comment by DreamU1952** [comment]
Thanks for responding. I did not select those components. But not sure why I would. The Workload called 'Office/Sharepoint Development says it is 'used to create Add-ins'. I do not want to create add-ins. I just want to open an Excel spreadsheet from C# and read/write some of the cells.

I see two Individual Components: 1) Office Developer Tools for VS and 2) Visual Studio Tools for Office which were not selected (probably because Office/Sharepoint Workload was not selected?). Do I need both of those? We do an offline install so I will need to download the right component for my offline layout, namely I assume 'Microsoft.VisualStudio.Component.TeamOffice'. Will that component include those two Individual components?

Frankly, I can already add a COM reference in VS2022 to 'Microsoft Excel 16.0 Object Library' so do I really need anything else? That works but I am assuming perhaps this page is describing an updated version I may want/should use??

Regards,
Jim Thoimas
________________________________
