### ISSUE TITLE
Technical Support

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#789]
Can we update the information regarding how to submit a technical support incident for Azure? Subscribers have to access this link in order to do so: Portal.Azure.com > Help + support > New support request.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73356ab4-87d3-09fb-557f-4533fc133156
* Version Independent ID: ce5ed4b4-1406-9126-832a-ddcdc5cf25bc
* Content: [Microsoft Azure Benefit](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure)
* Content Source: [subscriptions/vs-azure.md](https://github.com/Microsoft/visualstudio-docs/blob/master/subscriptions/vs-azure.md)
* Service: **unspecified**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@Nathan-Tarin Thanks for your inquiry and apologies for the late reply.
@evanwindom @prrana Is this something that we could update the docs with?

**Comment by TerryGLee** [comment]
@evanwindom Thanks for submitting the changes; and @Nathan-Tarin thanks again for your feedback. We'll close this issue now that updates to the docs are in (or quickly on their way in).
