### ISSUE TITLE
For Apple Silcon - per the getting started application

### ISSUE THREAD

**Issue by jmccartan** [MicrosoftDocs/visualstudio-docs#7892]
Docker File should be

FROM node:12-alpine
# Adding build tools to make yarn install work on Apple silicon / arm64 machines
RUN apk add --no-cache python2 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cddd74b1-e0f1-1cae-e92d-c7c2b81e77e3
* Version Independent ID: f853e977-81c2-64d6-682e-1e712344cbad
* Content: [Tutorial: Get started with Docker apps in Visual Studio Code](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/docker-tutorial)
* Content Source: [docker/tutorials/docker-tutorial.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docker/tutorials/docker-tutorial.md)
* Product: **vs-code**
* GitHub Login: @ucheNkadiCode
* Microsoft Alias: **uchen**

**Comment by ucheNkadiCode** [comment]
@ghogen, would there be a proper landing spot to point users to when it comes to mac user

**Comment by ghogen** [comment]
@ucheNkadiCode  
For the Docker / VS Code user? Maybe we should create that. I'm not aware of any page right now for Mac-specific guidance. Usually, it would just be mentioned in the text wherever there is a significant difference.

**Comment by ucheNkadiCode** [comment]
@jmccartan, thank you for your feedback! Would you mind pasting the entire Dockerfile top to bottom so we know what you're saying to add in context? Are you saying that the tutorial does not work for you unless you make these additions to the Dockerfile? 

Thanks
