### ISSUE TITLE
VS2022 project template location should not be be the 32 bit program files (x86) but the 64 bit program files directory

### ISSUE THREAD

**Issue by sommmen** [MicrosoftDocs/visualstudio-docs#7896]
Since vs 2022 is 64 bit now the documentation should be updated, because it still points to `%ProgramFiles(x86)%` which should be `%ProgramFiles%` instead for vs2022 and above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08f8f1c1-ffab-4a28-28e0-01ab59f8f827
* Version Independent ID: fb87ecb9-aaf2-a693-a30b-f5a4aea01ba8
* Content: [Locate templates - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-locate-and-organize-project-and-item-templates?view=vs-2022)
* Content Source: [docs/ide/how-to-locate-and-organize-project-and-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-locate-and-organize-project-and-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@sommmen -- thank you for your feedback.  I am investigating and will update this article accordingly.

cc @TerryGLee for awareness

**Comment by TerryGLee** [comment]
@sommmen You're right; thanks for bringing this to our attention. We've updated the page; you should see the updates published later today. Thanks to you for your help in improving the documentation!
