### ISSUE TITLE
Typo - Overview

### ISSUE THREAD

**Issue by Nathan-Tarin** [MicrosoftDocs/visualstudio-docs#790]
There is a typo on the introduction statement. It should say "subscriptions" and it says: subscriptoins.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9339facb-e027-7d83-b1ab-b4c4363a109b
* Version Independent ID: c9000f86-0aa5-59ff-d3e0-a0e649708b88
* Content: [Windows Developer Account Benefit in Visual Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-windows-dev)
* Content Source: [subscriptions/vs-windows-dev.md](https://github.com/Microsoft/visualstudio-docs/blob/master/subscriptions/vs-windows-dev.md)
* Service: **unspecified**
* GitHub Login: @ghogen

**Comment by gewarren** [comment]
@Nathan-Tarin Thanks for reporting this typo. @TerryGLee this is an easy fix if you get a chance.

**Comment by TerryGLee** [comment]
@Nathan-Tarin Thanks for reporting this; we have a PR in play [https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/2249](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/2249), which should get this fixed by tomorrow an noon.

Cheers,
~ Terry
