### ISSUE TITLE
Misinformation or Outdated information

### ISSUE THREAD

**Issue by abmaurya** [MicrosoftDocs/visualstudio-docs#7910]
The [page ](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-managed-and-native-code?view=vs-2022)mentions that one can step into the native code and as per the screenshot on the page, Visual Studio opens the native code source file and shows the current location of the "instruction pointer". 
This is misinformation or doesn't happen anymore with VS 2022. I have the source of native code, and the dll was generated on the same machine where the managed app is being debugged. The pdb file and the dll file are on the same location but it still doesn't work.
NOTE: The dll works fine, I just can't step into it as this document seems to suggest.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec762474-4eeb-cba2-5290-fd664ab88f8c
* Version Independent ID: 318fa7f6-e54a-1777-1f3f-3a30bb736f69
* Content: [Tutorial: Debug C# and C++ code (mixed mode) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-debug-managed-and-native-code?view=vs-2022)
* Content Source: [docs/debugger/how-to-debug-managed-and-native-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/how-to-debug-managed-and-native-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@abmaurya Was your .NET code .NET Framework or .NET/.NET Core?

**Comment by abmaurya** [comment]
@Mikejo5000 
My project targets .Net Framework (4.7.1 if it helps) but I am not sure how that matters since the document mentions both .Net Core and Framework as valid projects.

**Comment by Mikejo5000** [comment]
@abmaurya I tested several flavors of this app in VS 2022 (17.1.2) and have not been able to repro the issue (I can hit the code in the DLL as described via F11). I tried with .NET and .NET Framework calling app. Are you using the code described in the article? If not, there might be a relevant issue there. If you are, then I suspect something needs to be tweaked in the configuration, maybe the file path referenced in Program.cs, or the setting to enable native code debugging, or a configuration setting in the DLL such as x64 vs x86.
I am making some VS 2022 updates to the articles now, but none of the steps are really changing in a significant way in terms of the issue you're describing.

**Comment by abmaurya** [comment]
@Mikejo5000 
The code is not the same as the article, but that shouldn't matter(as the dll code works), although configurations can make/break things. I am sure the C++ project has the same configuration as suggested in the article but I can't say that about the C# project, although I have enabled/checked the "Enable native code debugging" in Debug option in the project's properties. Is there any other dependency that might be missing from the C# project's configuration ? 

I can provide you with relevant files if you need any, to examine the project configuration that I might be missing( I usually don't modify config files directly, so I might be missing something there)
This may/may not improve the article and may/may not help someone stumbling upon this thread due to similar case.

**Comment by Mikejo5000** [comment]
@abmaurya OK, interesting. If I target an x64 DLL (instead of x86) from .NET Framework app, I do have issues. A possible workaround (for debugging purposes), is to compile the DLL as x86 and reset the path to the x86 DLL in the C# Program.cs file. 
Would you mind reporting this problem? please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
It might have something to do with the calling app being set to Any CPU vs. the DLL being either x86 or x64, but I'm not sure.

**Comment by Mikejo5000** [comment]
@admaurya I got this to work for the article's example app by setting the app platform to x64 in the Configuration Manager for the calling .NET Framework app. (Debug toolbar > Configuration Manager. Then I could add a New configuration and set it to x64.
![image](https://user-images.githubusercontent.com/11948536/163650460-fc0c70b4-6d78-4632-a438-cd4a446288a1.png)

**Comment by Mikejo5000** [comment]
I'm adding this info as a step for x64 DLL from .NET Framework and will close the doc bug when I merge the change. If you are still experiencing the issue, please use the Report a Problem link above, since that is the best venue. Thanks!
