### ISSUE TITLE
No startup class created

### ISSUE THREAD

**Issue by benoit160** [MicrosoftDocs/visualstudio-docs#7911]
Hi, 

In "Create the bacnend app, section 3, the image show a startup class in the project, but none is actually created using the template "ASP.net core web api"

the image should be edited to make it reflect the newest version of the template

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@benoit160 It sounds like they changed the template in a recent update. Besides the out-of-date screenshot, do the steps work?

**Comment by benoit160** [comment]
Yes, it's only the picture that needs updating

**Comment by Mikejo5000** [comment]
Updated the screenshot. Should be live by EOD today.
