### ISSUE TITLE
Standalone Typescript React Template " Add integration for Empty ASP.NET Web API Project option" not available.

### ISSUE THREAD

**Issue by moonk2** [MicrosoftDocs/visualstudio-docs#7914]
In this document, Step 3. " Add integration for Empty ASP.NET Web API Project option" is not available for Standalone Typescript React Template in VS2022 Version 17.1.3
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by MarcusGambit** [comment]
Hi, 
In fact, Step 3 of the document states "The standalone **TypeScript** React Template is not currently supported in this tutorial". The option is available with the JavaScript version of the Template (VS 17.1.6).
That's being said, it would be very nice to have the option for the TypeScript version of the Template :)

**Comment by Mikejo5000** [comment]
@MarcusGambit Thanks for the feedback! If you are looking for functionality that isn’t currently provided by the product, please use our new “Suggest a feature” option in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html). We’d be happy to have this on record, where others can view it and upvote it, too. For more information about this new functionality in the dev community, see our [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature?view=vs-2017) page.
