### ISSUE TITLE
Class Designer has become 'optional' component with VS 2017

### ISSUE THREAD

**Issue by ChrisMaddock** [MicrosoftDocs/visualstudio-docs#792]
As of VS 2017, the class designer appears to have become an optional component which must be installed separately. This page and others should mention this. (But this was the first page I was brought to by Google!)

Source of information: https://stackoverflow.com/q/42233831/1768779

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c8eb126-b9c4-b81f-ee87-97ba405c0c25
* Version Independent ID: efdcd83c-0280-dbeb-97de-b4da4895c5bc
* Content: [How to: Add Class Diagrams to Projects (Class Designer) - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/class-designer/how-to-add-class-diagrams-to-projects#feedback)
* Content Source: [docs/ide/class-designer/how-to-add-class-diagrams-to-projects.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/class-designer/how-to-add-class-diagrams-to-projects.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ChrisMaddock thanks so much, i'll update this topic.

**Comment by gewarren** [comment]
This is fixed now. Thanks again!

**Comment by ChrisMaddock** [comment]
Thanks!
