### ISSUE TITLE
Title is incorrect

### ISSUE THREAD

**Issue by LibertyToad** [MicrosoftDocs/visualstudio-docs#7921]
Although the title claims it will tell you how to remove references, the text fails to say how to do that.

Please either fix the misleading title or complete the instructions to make the title accurate.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284369-f16f-2748-2a55-8cd24a06b940
* Version Independent ID: f7b0c577-b584-98dc-90a2-4efcf095b35d
* Content: [Add references in the Reference Manager - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2019)
* Content Source: [docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@LibertyToad We appreciate your feedback, and we've updated the page to include a "[Remove a reference](https://learn.microsoft.com/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager#remove-a-reference)" section. We'll close this issue now, with our thanks to you for your help in improving the product documentation!
