### ISSUE TITLE
Angular with Visual Studio

### ISSUE THREAD

**Issue by RobIngleby** [MicrosoftDocs/visualstudio-docs#7925]
Like all too many others  I've run into the following when trying to build the solution:
 Error	MSB3073	The command "npm install" exited with code 1.
 
 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 187a9aa8-1f64-5a37-f8a6-0d408642014e
* Version Independent ID: 1fb3868f-4175-279e-6372-91765426547c
* Content: [Create an Angular app - Visual Studio (Windows)](https://docs.microsoft.com/en-gb/visualstudio/javascript/tutorial-create-angular-app?view=vs-2022)
* Content Source: [docs/javascript/tutorial-create-angular-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-create-angular-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@RobIngleby What version of VS are you running? It could be this issue: https://github.com/dotnet/aspnetcore/issues/37520
What does your output say?

**Comment by RobIngleby** [comment]
I'm running: 
Microsoft Visual Studio Community 2022 (64-bit) - Current 
Version 17.1.5 

The "top-level" error message in Visual Studio is: 
Severity Code Description 
Error MSB3073 The command "npm install" exited with code 1. 

with a reference to a line in the .esproj file that reads: 
<Exec WorkingDirectory="$(SpaRoot)" Command="npm install" /> 


I have not investigated this properly yet but just a quick search seems to indicate that this is a known issue. 


Fra: "Mike Jones" ***@***.***> 
Til: "MicrosoftDocs/visualstudio-docs" ***@***.***> 
Cc: "RobIngleby" ***@***.***>, "Mention" ***@***.***> 
Sendt: onsdag, 20. april 2022 17:38:48 
Emne: Re: [MicrosoftDocs/visualstudio-docs] Angular with Visual Studio (Issue #7925) 





[ https://github.com/RobIngleby | @RobIngleby ] What version of VS are you running? It could be this issue: [ https://github.com/dotnet/aspnetcore/issues/37520 | dotnet/aspnetcore#37520 ] 
What does your output say?

**Comment by Mikejo5000** [comment]
@RobIngleby Did you figure out a resolution to this?

**Comment by RobIngleby** [comment]
Hej,no because I"ve been in hospital!
----- Original meddelelse -----
Fra: Mike Jones ***@***.***>
Til: MicrosoftDocs/visualstudio-docs ***@***.***>
Cc: RobIngleby ***@***.***>, Mention ***@***.***>
Sendt: Thu, 19 May 2022 00:18:04 +0200 (CEST)
Emne: Re: [MicrosoftDocs/visualstudio-docs] Angular with Visual Studio (Issue #7925)

@RobIngleby Did you figure out a resolution to this?

**Comment by Mikejo5000** [comment]
@RobIngleby Sorry to hear that. Hope you recover quickly.

**Comment by Mikejo5000** [comment]
@RobIngleby I retested on VS 17.2.5 and could not repro. I updated to the current Node.js/npm and current Angular CLI, created a new project, and still everything worked. I could create the project, build, and run. If this is still an issue, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
