### ISSUE TITLE
These steps don't work for Linux containers

### ISSUE THREAD

**Issue by sethflowers** [MicrosoftDocs/visualstudio-docs#7926]
See this issue reported here: https://github.com/dotnet/aspnetcore/issues/41093

The confusing response was:

> For docker scenarios it is recommended that you run the .NET app separately from the SPA frontend during development.
> 
> You can disable the automatic SPA launch from the .NET app and run it inside the container and then start the SPA frontend manually with npm run start in the host during development.

And the msftbot commented:

> We've moved this issue to the Backlog milestone. This means that it is not going to be worked on for the coming release. We will reassess the backlog following the current release and consider this item at that time. To learn more about our issue management process and to have better expectation regarding different types of issues you can read our [Triage Process](https://github.com/dotnet/aspnetcore/blob/main/docs/TriageProcess.md).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1abf884f-eb39-1007-25a6-d049b87504a3
* Version Independent ID: 33636e79-d3e1-8c24-f3a5-0c3c79e2a488
* Content: [Visual Studio Container Tools with ASP.NET Core and React.js](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2022)
* Content Source: [docs/containers/container-tools-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/container-tools-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@sethflowers 
Thanks for reporting this. Investigating.

**Comment by ThanhCuD** [comment]
I have the same issue. 
I comment here. If anything else new please let me know. Thanks

**Comment by ThanhCuD** [comment]
@WilliamAntonRohm why need more info? Ghogen knows the issue and he is Investigating?

**Comment by WilliamAntonRohm** [comment]
@ThanhCuD -- thank you for your follow-up.  Gordon himself needs more information.

**Comment by ghogen** [comment]
I'm investigating this, but the change in .NET 6 is quite significant, making the scenario very different.  The proxy was introduced in ASP.NET Core 6.0, and that also means that the JavaScript or TypeScript client app runs on the local machine, but the container that contains the ASP.NET backend server runs in the container.  I have some updates in draft form that might help, but I'm currently unable to properly attach the debugger to the container. I can debug the ClientApp (hit breakpoints in JavaScript or TypeScript), but so far I haven't been able to debug into the server.  Also, if the JavaScript runs locally, not in the container, but only in development, not in production, I'm not sure what that means for our Dockerfile. The Dockerfile sets up the container for Node runtime but that's not used, at least not in development mode.

**Comment by ghogen** [comment]
There will be an update to this topic soon. I think one key factor is "publishAllPorts" should not be used.
