### ISSUE TITLE
Bad video links

### ISSUE THREAD

**Issue by HAllenMoody** [MicrosoftDocs/visualstudio-docs#793]
Several links to tutorial videos are to popscreen.com but are no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdaf3d5-a7bc-fb9f-9750-9aee54546670
* Version Independent ID: d0e43ac2-9a43-a803-93bd-720a4ebaf664
* Content: [Organize objects into layout containers in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/organize-objects-into-layout-containers-in-xaml-designer)
* Content Source: [docs/designers/organize-objects-into-layout-containers-in-xaml-designer.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/designers/organize-objects-into-layout-containers-in-xaml-designer.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@HAllenMoody thanks for the feedback. I'll fix these links.
