### ISSUE TITLE
These packages do not seem to exist?

### ISSUE THREAD

**Issue by TashaSkyUp** [MicrosoftDocs/visualstudio-docs#7931]
![image](https://user-images.githubusercontent.com/15312630/164534492-c94eece3-11db-4453-b702-9978ef6eab0d.png)
![image](https://user-images.githubusercontent.com/15312630/164534551-17887529-d679-44fb-ad48-4e9952254278.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2022)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/install-architecture-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by TashaSkyUp** [comment]
Turns out these do exist but only for the "Enterprise" edition, this should be mentioned somewhere easy to see.

**Comment by mgoertz-msft** [comment]
@TashaSkyUp It's explained on the previous page in the docs: https://docs.microsoft.com/en-us/visualstudio/modeling/analyze-and-model-your-architecture?view=vs-2022#edition-support-for-architecture-and-modeling-tools
