### ISSUE TITLE
Can't find DSL Tools Lab?

### ISSUE THREAD

**Issue by bricelam** [MicrosoftDocs/visualstudio-docs#7932]
The referenced DSL Tools Lab is ridiculously hard to find these days. For convenience, I've uploaded a copy to [bricelam/DslToolsLab](https://github.com/bricelam/DslToolsLab) on GitHub. This is an invaluable resource for learning how to use the Modeling SDK.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb79e97f-6d8a-0f06-96db-db4fc1e135ae
* Version Independent ID: 097107da-2105-400d-3ad3-1f47c1422209
* Content: [Getting Started with Domain-Specific Languages - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/getting-started-with-domain-specific-languages?view=vs-2022)
* Content Source: [docs/modeling/getting-started-with-domain-specific-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/getting-started-with-domain-specific-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by WilliamAntonRohm** [comment]
@bricelam -- Brice, thank you for your feedback and consideration.  This repo is solely for documentation issues and this appears more product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

cc @mgoertz-msft for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by bricelam** [comment]
I'm referring to the lab mentioned in this article. The link is essentially broken, and the lab is nearly impossible to find.

https://github.com/MicrosoftDocs/visualstudio-docs/blob/46011f55b37dec8b5afa03eb2c9854234068be91/docs/modeling/getting-started-with-domain-specific-languages.md?plain=1#L21

**Comment by WilliamAntonRohm** [comment]
@bricelam -- Brice, thank you for your follow-up.

@mgoertz-msft -- Marco, please look into this issue.

**Comment by mgoertz-msft** [comment]
Looping in @aprilspeight who wrote the [MSDN Code Gallery retirement page](https://docs.microsoft.com/en-us/teamblog/msdn-code-gallery-retired). Apparently, this content was missed and should have been moved to the Visual Studio code sample archive.

**Comment by aprilspeight** [comment]
Hi @mgoertz-msft I've transitioned to a different team. Please reach out to @rloutlaw for assistance.
