### ISSUE TITLE
binary format debug format specifier for C#

### ISSUE THREAD

**Issue by BennyBread** [MicrosoftDocs/visualstudio-docs#7945]
[Enter feedback here]

Binary format specifier is missing. For C++ the specifier "b" exists. Is it possible to have it for C# as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92ab3309-0c6a-5150-64d8-0339a03f3238
* Version Independent ID: e29ede27-d73c-7294-cdcc-c1227353bbb9
* Content: [Format specifiers in the debugger (C#) - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/format-specifiers-in-csharp?view=vs-2019)
* Content Source: [docs/debugger/format-specifiers-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/format-specifiers-in-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@BennyBread -- Benny, thank you for your question.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
