### ISSUE TITLE
Selecting and pressing Enter no longer opening files in "Find All File" results. 

### ISSUE THREAD

**Issue by jeffjmc** [MicrosoftDocs/visualstudio-docs#7952]
[Enter feedback here]
 
In prior versions of Visual Studio.  when the results of a search were selected,  Say with a Ctl-A for selecting all.  pressing enter would open each file in a visual Studio tab.  This no longer seems to be the case in VS 2022.  Could you add a section to this page discussing this change of behavior?  and if possible,  point to how to get an open all function to work as in the past. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e27881f-04bc-b7ba-e217-8360278a14f8
* Version Independent ID: d31c8050-339a-688c-869e-ff7942fd3f74
* Content: [Find in Files - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2022)
* Content Source: [docs/ide/find-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/find-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@jeffjmc -- thank you for your feedback.

- Visual Studio 2017 -- selecting all Find in Files results and pressing Enter opens all found files in their respective tabs.
- Visual Studio 2019 and 2022 -- open only the top Find result's file in a new (if not already open) tab.

@TerryGLee -- please look into this issue.

**Comment by TerryGLee** [comment]
@jeffjmc Thanks for your feedback; we appreciate it. An investigation into the issue revealed that this functionality changed starting with Visual Studio 2019. Our documentation addresses how the feature works for Visual Studio 2019 and Visual Studio 2022, so it is current. However, if you'd like to influence a change in the product itself with regard to the **Find in Files** feature, please consider using the [Suggest a feature](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) tool to do so. Our engineering team uses this tool to triage feature updates. 

We'll close this issue now; we hope to hear from you again!
