### ISSUE TITLE
Misleading explanation, bad approach for VS's lack of support for multiple workspaces open

### ISSUE THREAD

**Issue by gcarbonell** [MicrosoftDocs/visualstudio-docs#7956]
Stating that "all applications on a Mac, including Visual Studio for Mac, are single-instance apps" is misleading, at best it's only half the story: macOS apps are each a single instance but with support multiple documents open (xcode, terminal, etc).  That's the macOS model and this problem is just a shortcoming of VS For Mac.

So the real fix for VS For Mac is to have each workspace/solution in a separate document window inside the same app instance.  That would allow to use the OS and users to handle app-switching vs app window switching, Mission Control, etc, in a native way.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c6c338d-6f88-ff4d-9ba9-b6c5be0559ab
* Version Independent ID: f95c3515-48e2-1d4d-90f5-54288f672ac4
* Content: [How to: Open multiple solutions - Visual Studio for Mac](https://docs.microsoft.com/en-au/visualstudio/mac/open-multiple-solutions?view=vsmac-2019)
* Content Source: [mac/open-multiple-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/open-multiple-solutions.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by jmatthiesen** [comment]
Thanks for the feedback! Yes, this is a shortcoming in the product currently that stems from some core architectural challenges. The current multiple instance support is more of a workaround solution for now to help developers have some way to open multiple solutions until we can fix the design. You can add your vote for the feature on the Developer Community suggestion for this feature, and follow-along for future updates: https://developercommunity.visualstudio.com/content/idea/758215/make-it-easier-to-open-multiple-solutions.html
