### ISSUE TITLE
Ask about package installation

### ISSUE THREAD

**Issue by BO-DI** [MicrosoftDocs/visualstudio-docs#7961]
Hello,Sir.
   I have a problem to ask you about  Visual Studio Installer Projects.
   I wrote a WPF program,the target framework is NET 5.0. after the WPF program is successfully packaged through visual studio installer projects, when I open the program, I find that there is no Net SDK 5.0 Windows environment, WPF program cannot be opened, and a download will pop up Net window.
 this is a screenshot:
![image](https://user-images.githubusercontent.com/53505854/166230325-9ea50451-60f8-49af-bcc0-19f992926e7f.png)

Can you solve this problem through the necessary components of visual studio installer projects. Because I didn't find it in the prerequisites net sdk 5.0。

this is a screenshot:
![image](https://user-images.githubusercontent.com/53505854/166230707-85c90378-b2a7-4fd8-85ed-47bbf59ecc3b.png)

That all
thanks.

 BO-DI
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f59111-46ee-3f59-3635-616f93a92c2a
* Version Independent ID: edc371ba-5f33-803a-34e7-3de69f053691
* Content: [Visual Studio Installer Projects and .NET 6.0](https://docs.microsoft.com/en-us/visualstudio/deployment/installer-projects-net-core?view=vs-2019)
* Content Source: [docs/deployment/installer-projects-net-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/installer-projects-net-core.md)
* Product: **visual-studio-windows**
* GitHub Login: @MSLukeWest
* Microsoft Alias: **lukewest**

**Comment by MSLukeWest** [comment]
@BO-DI - For a .NET 5 WPF app you'd want to include the prerequisite named ".NET Desktop Runtime 5.0.16 (x64)" (or the x86 version if your app is x86).  Note that the ".16" part could be slightly different based on what VS build you have installed.

**Comment by BO-DI** [comment]
> @BO-DI - For a .NET 5 WPF app you'd want to include the prerequisite named ".NET Desktop Runtime 5.0.16 (x64)" (or the x86 version if your app is x86). Note that the ".16" part could be slightly different based on what VS build you have installed.

If the framework_version of my WPF app is 5.0.0,check the prerequisites when packaging and installing is ".NET Desktop Runtime 5.0.16 (x64)" still appropriate?

**Comment by BO-DI** [comment]
@MSLukeWest  i installed " .NET Desktop Runtime5.0.16(x64)" (or the x86 version if your app is x86),but it didn't work.
this is a screenshot:
![image](https://user-images.githubusercontent.com/53505854/166403175-98d5a01a-9ffa-4e22-a791-ad8bedcb0035.png)
![image](https://user-images.githubusercontent.com/53505854/166403262-3aba5e9c-6a02-4341-9bb5-498928ebbb9d.png)

**Comment by MSLukeWest** [comment]
@BO-DI - Two questions:
 1) Are you by chance targeting Arm32 or Arm64 with this app?
 2) Right next to your app exe, in both the bin folder and the install folder, there should be a file called <Your_App_Name>.runtimeconfig.json.  Inside that file there should be a "runtimeOptions" section, can you tell me what that says?  It will look something like this:

```
"runtimeOptions": {
    "tfm": "net5.0",
    "framework": {
      "name": "Microsoft.WindowsDesktop.App",
      "version": "5.0.0"
    }
```

**Comment by BO-DI** [comment]
@MSLukeWest 
Hello sir.
First question:
Do you mean the windows operating environment when you refer to arm32 or arm64?

Second  question:
![image](https://user-images.githubusercontent.com/53505854/167049714-53dbb542-6d71-4309-ae2c-f52365aa0cac.png)

**Comment by MSLukeWest** [comment]
@BO-DI Your answer to my second question shows why you're getting this error dialog.  Your app requires "Microsoft.AspNetCore.App", meaning you need the "ASP.NET Core Runtime".  So, this must be an ASP.NET app, not just WPF.  Unfortunately, Installer Projects don't support ASP.NET scenarios, so there's no corresponding prerequisite for you to use.  If you'd like to request this functionality there's a Visual Studio feedback ticket you can upvote here: https://developercommunity.visualstudio.com/t/Creating-MSI-with-Microsoft-Visual-Stud/1405579

Alternately, if you're not actually using ASP.NET, you may be able to alter your project file in a way that eliminates this requirement.

**Comment by BO-DI** [comment]
> @BO-DI Your answer to my second question shows why you're getting this error dialog. Your app requires "Microsoft.AspNetCore.App", meaning you need the "ASP.NET Core Runtime". So, this must be an ASP.NET app, not just WPF. Unfortunately, Installer Projects don't support ASP.NET scenarios, so there's no corresponding prerequisite for you to use. If you'd like to request this functionality there's a Visual Studio feedback ticket you can upvote here: https://developercommunity.visualstudio.com/t/Creating-MSI-with-Microsoft-Visual-Stud/1405579
> 
> Alternately, if you're not actually using ASP.NET, you may be able to alter your project file in a way that eliminates this requirement.

Thank you very much .I Will try.
