### ISSUE TITLE
Create task tokens for other programming languages doesn't work at all

### ISSUE THREAD

**Issue by Neutrino-Sunset** [MicrosoftDocs/visualstudio-docs#7966]
The documentation describes how a task defined in a comment is comprised of three parts, the comment marker (//), the token (TODO), and the comment text which forms the task description.

It goes on to describe how you can create your own tokens for other programming languages using `Tools -> Options -> Task List`. Except it doesn't work at all. All you can configure is the token in the Name field, but since there is no way to configure the comment marker then it doesn't work in any language that does not have C like comment syntax.

E.g. In a cshtml file I have `@* TODO: something *@`

There is no way to enable this to be picked up by the Task List.

Even defining the comment as `@* // TODO: Something *@` doesn't work.

I don't see any support for non C style task comments at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1261884-8284-53f9-a325-15061bf897f8
* Version Independent ID: 4520c20f-86f6-5066-298b-d3d428901f87
* Content: [Use the Task List - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/using-the-task-list?view=vs-2022)
* Content Source: [docs/ide/using-the-task-list.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/using-the-task-list.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Neutrino-Sunset -- thank you for your well-researched feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by Neutrino-Sunset** [comment]
@WilliamAntonRohm I would say this *is* a documentation issue. The documentation totally mischaracterizes the functionality.

Now whether the existing functionality is by design or is a defect is probably not for us to say, and even if it is considered a defect experience would suggest it's the sort of thing the VS team will shug about and then ignore for years. Irrespective of that leaving the documentation 'as is' to continue to mislead people, potentially for years to come, would seem to me to be lax.

**Comment by WilliamAntonRohm** [comment]
@Neutrino-Sunset -- Neutrino, thank you for your follow-up.  Please see the initial reply.
