### ISSUE TITLE
Is it possible to limit navigation back-forward within the file (active tab)?

### ISSUE THREAD

**Issue by ideafixxxer** [MicrosoftDocs/visualstudio-docs#7967]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c31dfca-90f6-b76a-5bed-a312eebf0803
* Version Independent ID: 36699eca-48cc-2913-8a27-ae9bc48f940b
* Content: [Code navigation commands - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/navigating-code?view=vs-2022)
* Content Source: [docs/ide/navigating-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/navigating-code.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@ideafixxxer -- Boris, thank you for your question.  Are you referring to setting the maximum number of navigation locations?  [Navigate Backward and Navigate Forward commands](https://docs.microsoft.com/en-us/visualstudio/ide/navigating-code?view=vs-2022#navigate-backward-and-navigate-forward-commands) has:
> You can use the Navigate Backward (Ctrl+-) and Navigate Forward (Ctrl+Shift+-) buttons on the toolbar to move the insertion point to previous locations, or to return to a more recent location from a previous location. These buttons retain the last 20 locations of the insertion point.
