### ISSUE TITLE
Go to Implementation should consider generic type arguments

### ISSUE THREAD

**Issue by motion-x86** [MicrosoftDocs/visualstudio-docs#7969]
Working with generic interfaces in C# is extremely painful due to navigation tooling not considering type arguments when matching results.

## Steps to reproduce
1. Create an interface such as:  `IMapper<TSource, TDestination>`
2. Implement `IMapper` more than once with different types for `TSource` and `TDestination`
3. Have a member of a class be of type `IMapper<SomeSourceType, SomeDestinationType>` that was implemented in step 2.
4. Initiate "go to implementation" on the member from 3

## Expected behavior
Only the implementation of `IMapper` with the correct type arguments results should show up in the results of go to implementation

## Actual behavior
All classes that implement `IMapper` (any type arguments) will show up in the results.

**Comment by WilliamAntonRohm** [comment]
@motion-x86 -- Jesse, thank you for your considered feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

**Comment by mekk1t** [comment]
+ 9000 !!!

@motion-x86, please, tell us, did you manage to suggest this feature request to Visual Studio Developer Community?
If so, is there any news? A link to the request would help also.
