### ISSUE TITLE
Missing documentation for Visual Studio 'MEF' composition log

### ISSUE THREAD

**Issue by gundermanc** [MicrosoftDocs/visualstudio-docs#7971]
Documentation for Visual Studio includes a page on the use of [managed extensibility framework](https://docs.microsoft.com/en-us/visualstudio/extensibility/managed-extensibility-framework-in-the-editor?view=vs-2022) in VS extensions.

MEF is the core underpinning of all editor extensions and can be used like so to integrate an extension with VS:

```csharp
    [Export(typeof(ITextViewCreationListener))]
    [ContentType("CSharp")]
    [TextViewRole(PredefinedTextViewRoles.Editable)]
    [Name("My foo listener")]
    [Order]
    public class MyFooListener : ITextViewCreationListener
    {
        [Import]
        ITextEditorFactoryService editorFactory;

        public void TextViewCreated(ITextView textView)
        {
        }
    }
```

[Export] -> indicates that the class should be exported under that 'contract'.
[Import] -> indicates that we want the shared instance of that 'contract'.

This is well known and documented, however, a common stuck point for users is when they try to import something that doesn't exist in the current VS install, or they incorrectly author their import or export.

The primary way to find and address these issues is to reference the 'MEF composition error log'., stored at %localappdata%\Microsoft\VisualStudio\[yourVSVersion]\ComponentModelCache\Microsoft.VisualStudio.Default.err.

This log file is currently completely undocumented. Can we please document it on the following pages:
- https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2022
- https://docs.microsoft.com/en-us/visualstudio/extensibility/managed-extensibility-framework-in-the-editor?view=vs-2022
- https://docs.microsoft.com/en-us/visualstudio/extensibility/inside-the-editor?view=vs-2022

I'd also recommend creating a dedicated page for troubleshooting extensions.

**cc: ** @madskristensen, @matteo-prosperi, @leslierichardson95

**Comment by adamint** [comment]
I would appreciate if this were prioritized. I had to find this path **by stumbling upon this specific issue.**
