### ISSUE TITLE
Encoding adds a BOM but default does not.

### ISSUE THREAD

**Issue by RevenantBob** [MicrosoftDocs/visualstudio-docs#7972]
The documentation implies a BOM but doesn't directly speak of it. I was using `WriteLinesToFile` with UTF8 Encoding and old Visual Studio RC compiler would explode on the file. I didn't realize the BOM at the beginning was being written right away. Removing encoding all together fixed it. I think this is very important to note in the encoding documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee06fdb3-143d-fa36-54ee-5f9af813615e
* Version Independent ID: 5739dfe6-6a88-1487-4f29-1b91502ec7ad
* Content: [WriteLinesToFile Task - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/writelinestofile-task?view=vs-2022)
* Content Source: [docs/msbuild/writelinestofile-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/writelinestofile-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@RevenantBob 
It seems that Unicode encodings follow the Unicode standard and have a BOM, but encodings that aren't Unicode encodings don't. I didn't find a clear statement of this, although there's a note in the [Encoding.GetPreamble](https://docs.microsoft.com/dotnet/api/system.text.encoding.getpreamble?view=net-6.0) page that gives a cautionary warning that says "most encodings" don't have BOM, but the Unicode encodings do.  I don't see this as an MSBuild documentation issue, as the behavior is more about the .NET Encoding class, and would show up in many different usage scenarios, other than MSBuild's WriteLinesToFile task.

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
