### ISSUE TITLE
Installing Visual Studio in a Docker container using process isolation idles indefinitely

### ISSUE THREAD

**Issue by JanWosnitza** [MicrosoftDocs/visualstudio-docs#7976]
Follow up of #7907 as requested [by @milarso81.](https://github.com/MicrosoftDocs/visualstudio-docs/issues/7907#issuecomment-1115280028)

# What I'm trying to do
Build Unreal Engine 5 inside a Docker container using Jenkins (CI). Unreal Engine 5 requires VS2019 (VS2022 isn't supported yet).

# The Problem
Building the example image using "process" isolation-mode results in the setup processes to idle indefinitely.

But inside the VM "hyperv" isolation-mode isn't available, but "process" isolation-mode is. (also "hyperv" is less efficient, but would be fine for the image building)

The behaviour is the same for VS2022 Build Tools[^vs2022] and VS2019 Build Tools[^vs2019].
And also same on my local PC[^pc].

Stuck output (my PC):
![image](https://user-images.githubusercontent.com/2276629/166895799-7bafae10-39fd-43e4-b7c3-dbf96109ffe6.png)

Idling processes (my PC):
![image](https://user-images.githubusercontent.com/2276629/166899192-75280b78-8cc0-4788-b0b9-88e61be4d771.png)

# Reproduce
Follow the "Advanced example for container" steps on a Windows 11 and build the image with this commandline
`docker build --isolation=process --build-arg FROM_IMAGE=mcr.microsoft.com/windows/server:ltsc2022 -m 2GB .`

# The Workaround
Build the image locally and push to a private registry.

While this works, it's not ideal as the Dockerfile and the actually used image of the build job can get out of sync.

Best
Jan Wosnitza

[^vs2022]: https://aka.ms/vs/17/release/vs_buildtools.exe
[^vs2019]: https://aka.ms/vs/16/release/vs_buildtools.exe
[^pc]: OS Name: Microsoft Windows 11 Pro; Version: 10.0.22000 Build 22000; Hardware Abstraction Layer: Version = "10.0.22000.527"
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab2a8f7e-986d-a39a-7370-65ee7d538e88
* Version Independent ID: 5eaf0974-732a-edda-88e4-27de9179144d
* Content: [Advanced example for containers - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/advanced-build-tools-container?view=vs-2022)
* Content Source: [docs/install/advanced-build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/advanced-build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@JanWosnitza -- Jan, thank you for following up and creating this issue.  It appears to be product-related; please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@anandmeg -- Megha, please look into this potential documentation issue.

**Comment by JanWosnitza** [comment]
@WilliamAntonRohm thanks, [I reported it over here](https://developercommunity.visualstudio.com/t/Installing-Visual-Studio-Build-Tools-in/10032805?entry=problem)

**Comment by WilliamAntonRohm** [comment]
@JanWosnitza -- Jan, thank you.  I upvoted it.
