### ISSUE TITLE
Why do users' subscriptions show as expired?

### ISSUE THREAD

**Issue by User284699672** [MicrosoftDocs/visualstudio-docs#7977]
[Enter feedback here]
On https://manage.visualstudio.com/Subscribers there's a column labelled expiry which has a date in the past despite my agreement being valid for two more years.  Why does it do that?  How do I fix it?  None of these instructions seem to have any useful information about it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 905ea2e8-3aea-4a35-ce3d-a38049b7c4ab
* Version Independent ID: 4275be98-3837-08e2-580c-38da7e07aa93
* Content: [Handle expired licenses in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/handle-expired-license)
* Content Source: [subscriptions/handle-expired-license.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/handle-expired-license.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@User284699672 -- thank you for your questions.

@evanwindom -- please advise.

**Comment by evanwindom** [comment]
@User284699672 - Thank you for reaching out.  I have a couple of questions to help me understand your situation.
1. How many agreements do you have?
2. Do all the subscribers have past expiration dates?
3. If you select the second icon from the top on the far left of the portal, you should see "Agreement details".  What kind of agreement is it?  What does it show for end date and status?

**Comment by User284699672** [comment]
I have one agreement.

All subscribers look the same, yes.
***@***.***

Program:
OLV
Start date:
01/05/2021
End date:
30/04/2024
Status:
Active

**Comment by evanwindom** [comment]
#please-close

**Comment by PRMerger12** [comment]
Only Microsoft employees can close issues or pull requests via commenting in this repo.
