### ISSUE TITLE
Keyboard shortcuts for Quick Search are not documented

### ISSUE THREAD

**Issue by SittenSpynne** [MicrosoftDocs/visualstudio-docs#7978]
The shortcut `⌘` + `.` opens the Quick Search, and I'm pretty sure there are a handful of other shortcuts related to it, but these don't seem to be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2a1d38f-f2fc-3fe6-bfb4-b73b7f4a56bc
* Version Independent ID: 90b1f5ca-71dd-2c14-8023-c3f238fc2686
* Content: [Default Keyboard Shortcuts - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/keyboard-shortcuts?view=vsmac-2019)
* Content Source: [mac/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/keyboard-shortcuts.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by jmatthiesen** [comment]
Good catch, thanks @SittenSpynne!
