### ISSUE TITLE
Good and effective article - I love

### ISSUE THREAD

**Issue by ziaur210** [MicrosoftDocs/visualstudio-docs#798]
Waaaaaaooooooo:)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd2baf39-d3c3-5d5a-d93c-f4040430c3dd
* Version Independent ID: c443e681-03f0-ea47-a09d-718693448b3d
* Content: [Inspect XAML properties while debugging - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/inspect-xaml-properties-while-debugging#using-xaml-tools-with-running-applications)
* Content Source: [docs/debugger/inspect-xaml-properties-while-debugging.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/inspect-xaml-properties-while-debugging.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ziaur210 Thanks, ziaur! We appreciate the feedback.
