### ISSUE TITLE
"Switches for loggers" is truncated on the right

### ISSUE THREAD

**Issue by mr-e2** [MicrosoftDocs/visualstudio-docs#7980]
[Enter feedback here]
The section of this web page with section heading "Switches for loggers" has text that continues past the right edge of the display area. This text is not visible in the web browser. However, if it is selected, copied, and pasted into a text editor, it can be viewed. So the text is all present, it is just clipped and not visible on the web site.

The previous and subsequent sections handle the margins correctly. It is only "Switches for loggers" that has a problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@mr-e2 -- thank you for catching this.  I have updated the article and it will go live by tomorrow.  The revised table now has a horizontal slider bar at the bottom for scrolling the entire text.
