### ISSUE TITLE
MSBuild Tutorial references csc compiler that is no longer accessible

### ISSUE THREAD

**Issue by geronimus** [MicrosoftDocs/visualstudio-docs#7987]
Hello there.

I am following this tutorial in Windows 11 with dotnet 6.0.202 installed.

The referenced csc compiler no longer exists on the PATH!

Finding a work-around takes an entire afternoon of sifting through StackOverflow and GitHub. And then, when you finally think you've located the answer:

```pwsh
> dotnet 'C:\Program Files\dotnet\sdk\6.0.202\Roslyn\bincore\csc.dll' -r:"C:\Program Files\dotnet\sdk\6.0.202\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.dll" .\HelloWorld.cs
Microsoft (R) Visual C# Compiler version 4.1.0-5.22128.4 (5d10d428)
Copyright (C) Microsoft Corporation. All rights reserved.

HelloWorld.cs(6,7): error CS0518: Predefined type 'System.Object' is not defined or imported
HelloWorld.cs(8,12): error CS0518: Predefined type 'System.Void' is not defined or imported
```
😵‍💫

And actually, the further I go through this demo, the more I realize how horrendously out of date it is. None of the code examples work with the current dotnet CLI / SDK model.

And guessing what is wrong with them is utterly confounding.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09bc6800-41dc-a7a4-5942-0f103a290cf9
* Version Independent ID: 56b974f2-30d2-ae79-2b78-7eb073ec7cd1
* Content: [Create an MSBuild project file from scratch - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch?view=vs-2022)
* Content Source: [docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/walkthrough-creating-an-msbuild-project-file-from-scratch.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@geronimus -- Graham, thank you for your feedback.  Please consider these resources as well:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Reddit](https://www.reddit.com/r/VisualStudio)

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
@geronimus 
I agree it's out-of-date and not tested with .NET 6 and SDK-style projects. While it may be that it needs to be updated, we'll also need to consider the content itself and whether everything in it would still be the best practice or recommendation. So that will take a bit of time, but in the meanwhile, I'll add a note that it's not designed to work with SDK-style projects, etc.

**Comment by ghogen** [comment]
I have updates to the article, but the intent is not to show building with the SDK model, which brings in its own build infrastructure. The intent is to show basic MSBuild functionality for those who want to build "from scratch" meaning with nothing other than fundamental tools. It does rely on the tools used being on the PATH environment variable, as it says you can start with the Visual Studio Developer Command prompt.

**Comment by geronimus** [comment]
Thank you, @ghogen for the updates.

I was interested in "from scratch" precisely because the Visual Studio licensing model doesn't really work for my scenario - which is trying to convince my employer, from within, that if they want their software to work on Windows, it should be developed natively. With Visual Studio in the mix, I lose on cost right out of the gate.

But there is scarce little information on how to get started in .NET without VS. I'm not afraid XML, nor of understanding which .dll files need to provide what functionality, nor whether I must put them in the deployment package (eg, installer) or expect to use the version on the user's system.

I just need to know where the primary source information on how to build and deploy .NET applications without VS is meant to come from.

(I'm not averse to paying for it either. But I am averse to VS hiding it from me, however conveniently it may do so.)
