### ISSUE TITLE
SHE -> SEH

### ISSUE THREAD

**Issue by PfhorSlayer** [MicrosoftDocs/visualstudio-docs#799]
In the $exceptionstack description, I believe that should be "SEH" ("Structured Exception Handler"), not "SHE".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a26e9139-f916-9a84-94fa-8c54e944b2f1
* Version Independent ID: 44e76195-6067-acf9-d664-25d3cb5ada07
* Content: [Pseudovariables - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/pseudovariables)
* Content Source: [docs/debugger/pseudovariables.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/pseudovariables.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
@PfhorSlayer thank you for the feedback. @Mikejo5000 can you take this one?

**Comment by Mikejo5000** [comment]
@PfhorSlayer Good catch, thanks. Fixing.
