### ISSUE TITLE
File nesting in Solution Explorer should not be only supported for ASP.NET Core projects.

### ISSUE THREAD

**Issue by mioualalen** [MicrosoftDocs/visualstudio-docs#7990]
File nesting in Solution Explorer should **not** be **only** supported for ASP.NET Core projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by WilliamAntonRohm** [comment]
@mioualalen -- Michel, thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
