### ISSUE TITLE
The page lists options that are NOT available, i.e. the "Download all, then install" feature

### ISSUE THREAD

**Issue by CarlBateman** [MicrosoftDocs/visualstudio-docs#7999]
[Enter feedback here]
The page lists options that are NOT available, i.e. the "Download all, then install" feature

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by christineruana** [comment]
@CarlBateman - I'm a little confused by your assertion that this page lists options that are not available.  This page is discussing how to create a local cache of the Visual Studio files onto the local machine.  If you are using the installer to manually install the product, on the screen where you pick workloads there is a dropdown where you can specify to "Install while downloading" or "download all, then install" just like what's shown in the picture.  

What exactly are you doing that's leading you to believe the option isn't available?

**Comment by christineruana** [comment]
#reassign: @christineruana

**Comment by CarlBateman** [comment]
From a **clean** install, the dialog had no options, specifically no dropdown, and no options to "Install while downloading" or "download all, then install".
I can't recreate without uninstalling, which I'm afraid I don't have time for (it took over 5 hours last time :( ).
HTH

**Comment by christineruana** [comment]
#please-close
