### ISSUE TITLE
add info about Visual Studio Enterprise (Microsoft for Startups)

### ISSUE THREAD

**Issue by TiloGit** [MicrosoftDocs/visualstudio-docs#8000]
Please add “Visual Studio Enterprise (Microsoft for Startups)” to the table. 

This link: https://docs.microsoft.com/en-us/visualstudio/subscriptions/program-startups claims is has: 
"These are the same subscriptions that are offered commercially, with no special limitations or restrictions"

But we can't seem to use the Azure credit. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e815fbd3-dd2c-cced-ae4b-2709f62a4290
* Version Independent ID: e815fbd3-dd2c-cced-ae4b-2709f62a4290
* Content: [Azure Dev/Test credits eligibility in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-eligibility)
* Content Source: [subscriptions/vs-azure-eligibility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vs-azure-eligibility.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@TiloGit -- thank you for your feedback.

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@WilliamAntonRohm  - Thanks. 
@TiloGit - Thanks for reaching out with your question.  The subscriptions provided through the Startups program are identical to the cloud subscriptions offered through the Azure marketplace.  None of the monthly cloud subscriptions receive Azure credits.  For more information about what's included in the monthly subscriptions, see https://visualstudio.microsoft.com/vs/pricing-details/ 

I will make a couple of changes to the Startups article to make it more clear what's included.

**Comment by WilliamAntonRohm** [comment]
@evanwindom -- Evan, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
