### ISSUE TITLE
Misleading title

### ISSUE THREAD

**Issue by WrongBit** [MicrosoftDocs/visualstudio-docs#8001]
Page you named "network installation" has nothing common with "network" at all! It is page where user can make REAL OFFLINE distro (which can be copied to any place and installed from there). And page you named "offline install" explains something clumsy - "offline, but on this disk only" method. Swap these pages, so when user searches "offline visual studio", he should get immediately page "network installation" (which you rename, of course).
We do not like when MS counts us as stupid! We KNOW the difference between network/offline install, so stop making misleading titles - it at least unfair.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by christineruana** [comment]
Hi @WrongBit - Thank you for the feedback and I completely agree with it.  We have this work item queued up high on our to-do list as we continue to make improvements to the docs.
