### ISSUE TITLE
does not mention the <reference> element

### ISSUE THREAD

**Issue by leotohill** [MicrosoftDocs/visualstudio-docs#8004]
the reference element is a child of the itemgroup element . It is used to reference an assembly.  It is not mentioned in this article.  This article defines `<item>` as the only child type of itemgroup.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7148a9c-77db-81c7-0362-f2ce6b0c6274
* Version Independent ID: ccef6249-9a81-9376-a9c8-fe884d0b094f
* Content: [ItemGroup Element (MSBuild) - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/itemgroup-element-msbuild?view=vs-2022)
* Content Source: [docs/msbuild/itemgroup-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/itemgroup-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@leotohill 
Probably what is needed here is a statement that any of various elements that are items can be used.  For example, any of the elements listed as item types here: https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-items?view=vs-2022
