### ISSUE TITLE
Visual Studio 2022 Preview 17.3 .svg files

### ISSUE THREAD

**Issue by nandosilvajr** [MicrosoftDocs/visualstudio-docs#8007]
After update to Visual Studio 2022 Preview 17.3 all files used as icons on Maui was changed to black.

**Comment by WilliamAntonRohm** [comment]
@nandosilvajr -- thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
