### ISSUE TITLE
Wrong Component IDs of the Primary Interop Assemblies for Office 2016 32 bit

### ISSUE THREAD

**Issue by matei-tm** [MicrosoftDocs/visualstudio-docs#8008]
The column with Office 2016 32 bit shows wrong ids (copies from 64 bit)
![image](https://user-images.githubusercontent.com/12191374/168043684-dafdaea4-18f0-41d3-b02d-8d8190e172f1.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9904c-bc2c-49e6-b661-5598354dbc40
* Version Independent ID: 6dca41d0-9c34-f5cc-a2b0-6c6e9df76063
* Content: [Deploying a VSTO Solution Using Windows Installer](https://docs.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2022)
* Content Source: [docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
I'm looking into this

**Comment by John-Hart** [comment]
this was fixed with #8009
