### ISSUE TITLE
Adding new Unity files and folders

### ISSUE THREAD

**Issue by eugenezenkevich** [MicrosoftDocs/visualstudio-docs#801]
It is not very useful. On the contrary, more often I want to add a general c# class or interface, but there is no way to do this through the context menu in the Solution pad.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55502210-e9fc-ac0a-acd2-f505d3626b57
* Version Independent ID: bdd0ad92-67f6-64f3-b9e1-26ca89230d4b
* Content: [Using Visual Studio for Mac Tools for Unity](https://docs.microsoft.com/en-us/visualstudio/mac/using-vsmac-tools-unity)
* Content Source: [mac/using-vsmac-tools-unity.md](https://github.com/Microsoft/visualstudio-docs/blob/master/mac/using-vsmac-tools-unity.md)
* Service: **unspecified**
* GitHub Login: @dantogno
* Microsoft Alias: **v-davian**

**Comment by gewarren** [comment]
@eugenezenkevich thank you for the feedback. Are you saying the topic is not very useful, or the feature?

**Comment by gewarren** [comment]
@conceptdev or @dantogno could you pass this feedback on to the product team?

**Comment by conceptdev** [comment]
I've passed this on to the engineering team. @eugenezenkevich feel free to use https://developercommunity.visualstudio.com/spaces/41/index.html to provide further product ideas - they are easier to see, vote on, and track there.

Thanks again for your feedback.

**Comment by eugenezenkevich** [comment]
@sailro @conceptdev @gewarren  Thank you very much ! This is cool!
