### ISSUE TITLE
Accessibility Page is very helpful!

### ISSUE THREAD

**Issue by mlanca** [MicrosoftDocs/visualstudio-docs#8017]
Accessibility Page is very helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2913896-b0f2-5f3c-d733-09fe5c4e86b1
* Version Independent ID: c997c373-c946-0f02-d4c2-0904e6aab42e
* Content: [Change themes, fonts, text, and contrast for accessibility](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@mlanca Thanks for taking the time to write this! We appreciate your doing so. :)
