### ISSUE TITLE
Missing information on #pragma Support

### ISSUE THREAD

**Issue by cmccambridge** [MicrosoftDocs/visualstudio-docs#802]
Hi! The linked page for more information about "#pragma Support" does not actually contain any information on that topic. Could either that page be updated to include information on `#pragma prefast`, or perhaps a different link to a better resource be made from this article?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 392c386c-755c-3a5e-dab1-f157cac7f4f2
* Version Independent ID: 75a83eac-2475-4fd8-c9e3-2b2c9cea885e
* Content: [Code Analysis for C/C++ Overview - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/code-analysis-for-c-cpp-overview#pragma-support)
* Content Source: [docs/code-quality/code-analysis-for-c-cpp-overview.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/code-quality/code-analysis-for-c-cpp-overview.md)
* Service: **unspecified**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gewarren** [comment]
@cmccambridge thank you for the feedback. @mikeblome perhaps we could link to [this](https://docs.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword) topic?

**Comment by mikeblome** [comment]
@craigcaseyMSFT looks good thanks!

**Comment by mikeblome** [comment]
fixed.
