### ISSUE TITLE
Possible fix for hung debuggers

### ISSUE THREAD

**Issue by TecsiAron** [MicrosoftDocs/visualstudio-docs#8021]
[Enter feedback here]
Tried debugging an app running on Ubuntu. The debugger was showing that it is attached, but nothing worked. Deleting ~/.vs-debugger folder on the target fixed the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ecc1202-a940-caa0-968f-9abfe2679d8b
* Version Independent ID: 20ed4d8d-35ff-f1fe-74e4-ce2c27bb72c8
* Content: [Debug .NET Core on Linux - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/remote-debugging-dotnet-core-linux-with-ssh?view=vs-2022)
* Content Source: [docs/debugger/remote-debugging-dotnet-core-linux-with-ssh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/remote-debugging-dotnet-core-linux-with-ssh.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@TecsiAron Thanks for the suggestion! @gregg-miskelly Gregg, is this something I should add to the doc?

**Comment by gregg-miskelly** [comment]
@Mikejo5000 We released a new version of the Linux debugger on Friday, and it looks like this issue is alerting us to a bug in the upgrade scenario. So this is an excellent work around right this second, but I am not sure it should be in the docs.

**Comment by Mikejo5000** [comment]
Thanks, Gregg. Closing this since there is no doc update planned.

**Comment by gregg-miskelly** [comment]
FYI I new install script is now deployed which will correctly uninstall the old version of upgrade. So hopefully this will never be an issue again.
