### ISSUE TITLE
"Create minidumps for a Visual Studio process with all call stacks steps" need polish

### ISSUE THREAD

**Issue by schwjm** [MicrosoftDocs/visualstudio-docs#8037]
Step 3 says "Check the relevant Managed and Native check boxes and press **Attach**." It says afterwards in Step 4 to pick the process from the list. These steps are in the wrong order or possibly missing a step or two. "Check the relevant Managed and Native check boxes" is also vague as the provided screenshot no longer matches what Visual Studio (2019 and later) displays.

Rough suggestion besides updating the screenshot:
1. Next to "Attach To:", press the Select button
2. Check the Managed (.NET 4.x) and Native check boxes and press OK (the button in this dialog is not "Attach")
3. Select the other Visual Studio instance to attach to from the list of running processes, then press Attach (now that the process has been selected, "Attach" may be clicked)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef410b52-1f8f-6f71-1b86-92d73fd258f6
* Version Independent ID: 7b83a96b-1d79-48f7-c702-da151b91ddff
* Content: [Collect an ETL trace with PerfView and create minidumps with all call stacks - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem-perfview-minidumps?view=vs-2022#create-minidumps-for-a-visual-studio-process-with-all-call-stacks)
* Content Source: [docs/ide/report-a-problem-perfview-minidumps.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/report-a-problem-perfview-minidumps.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by Mikejo5000** [comment]
@schwjm Thanks for the feedback! Fix should be in place by end of day.
