### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by Existente** [MicrosoftDocs/visualstudio-docs#8039]
In the "Regenerating the code automatically" section of "Design-Time Code Generation by using T4 Text Templates" article you find a suggestion to insert the following xml at the end of your project file:
<Import Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v16.0\TextTemplating\Microsoft.TextTemplating.targets" />
<PropertyGroup>
   <TransformOnBuild>true</TransformOnBuild>
   
</PropertyGroup>

But current project files are not xml anymore

**Comment by Existente** [comment]
misunderstanding

**Comment by WilliamAntonRohm** [comment]
@Existente -- thank you for your interest, and I'm glad you were able to resolve that misunderstanding.  Please let us know if there was anything unclear in the article.
