### ISSUE TITLE
Inaccurate description/verbiage

### ISSUE THREAD

**Issue by MatrixArchitect** [MicrosoftDocs/visualstudio-docs#8041]
The verbiage underlined in image below is not correct. There's no configuration dropdown at the top of the build properties. It used to exist in VS 2019. It doesn't exist in VS2022. Perhaps it's a defect in VS 2022 that build configuration dropdown but it hasn't been noticed?

![image](https://user-images.githubusercontent.com/55520144/169410820-6a418e43-6f73-4542-bf6d-b8ecb3e5e545.png)

VS2019 has the configuration dropdown

![image](https://user-images.githubusercontent.com/55520144/169427268-ffb50d86-bf80-4c81-abbd-5af3b5eccaa5.png)

VS2022 doesn't

![image](https://user-images.githubusercontent.com/55520144/169427421-50b9f091-d01a-48c4-9e99-f5e05b42edb9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4938a042-e5db-4f9c-2288-930b904e888c
* Version Independent ID: 6db1e386-22e4-4940-cc2c-bdeaa5883299
* Content: [Change the build output directory - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2022)
* Content Source: [docs/ide/how-to-change-the-build-output-directory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-the-build-output-directory.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@MatrixArchitect 
Yes, this UI has changed for C# .NET Core/5/6 projects. We expect to update the article shortly.
