### ISSUE TITLE
Add SDK to Selected Project button is greyed out

### ISSUE THREAD

**Issue by spacejim** [MicrosoftDocs/visualstudio-docs#8047]
[Enter feedback here]

In my case the [Add SDK to Selected Project] button is greyed out with no explanation, and the explanation is missing from this documentation, I have nothing to go on.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc7770e6-e328-f549-6061-a5b516b56c55
* Version Independent ID: 2d48080a-3b15-9f23-c61f-ca0db094db06
* Content: [Concurrency Visualizer SDK - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/profiling/concurrency-visualizer-sdk?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.cv.sdk.about)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/profiling/concurrency-visualizer-sdk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/profiling/concurrency-visualizer-sdk.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@spacejim I tested this and the **Add SDK to Selected Project** button appears to work, so I can't repro. Two suggestions: (1) Did you make sure you installed the Concurrency Visualizer first? and (2) Was it the correct version matching Visual Studio? The latest version was released on 2/17.
