### ISSUE TITLE
VS/VS4Mac Compatibility Icons are Pixelated

### ISSUE THREAD

**Issue by TanayParikh** [MicrosoftDocs/visualstudio-docs#8048]
<img width="449" alt="image" src="https://user-images.githubusercontent.com/14852843/169589669-923f0e6f-c03d-4c31-84dc-4cb3d737a28a.png">

Looks like they may be cropped as well. Would it be possible to switch over to an `.svg`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab856c02-f379-f49e-e802-87bf64aaaf64
* Version Independent ID: cef1c93e-b929-502d-a553-158aea470c1c
* Content: [Publishing ClickOnce Applications - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/deployment/publishing-clickonce-applications?view=vs-2022)
* Content Source: [docs/deployment/publishing-clickonce-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/publishing-clickonce-applications.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@TanayParikh -- Tanay, thank you for your feedback.  I am not seeing pixelation, either in your attached image or in the document, in either Light or Dark themes.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by TanayParikh** [comment]
Here's a zoomed image:

<img width="107" alt="image" src="https://user-images.githubusercontent.com/14852843/169607805-6f795e62-afa5-4d79-b93a-c54298ad77df.png">


I'm working off of a ~4K display, this issue may be more pronounced on very high res displays.

**Comment by TanayParikh** [comment]
Specifically this is an issue with 

https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/media/yes-icon.png

and

https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/media/no-icon.png

I believe if these were changed to `.svg` assets, this issue wouldn't persist (as svg a vector format that automatically handles scaling).

https://github.com/MicrosoftDocs/visualstudio-docs/blob/8a44757d4c5a6ceda6c704a62a44b7c3259cf99d/docs/includes/applies-to-version/_vs-windows.md

@WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@TanayParikh -- Tanay, thank you for your follow-up.  I am investigating how to re-create these images as .svg's.

**Comment by WilliamAntonRohm** [comment]
@TanayParikh -- Tanay, I've created a [docs feedback issue](https://github.com/MicrosoftDocs/feedback/issues/3833) for this.
