### ISSUE TITLE
Should refer to RoslynCodeTaskFactory since CodeTaskFactory is deprecated/nonportable

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#805]
https://github.com/Microsoft/msbuild/issues/2890 states that `CodeTaskFactory` is going away and will be replaced by `RoslynCodeTaskFactory`. If that is true, this howto and the walkthrough should both be able to be rewritten in terms of `RoslynCodeTaskFactory`. Otherwise, people are going to waste time writing solutions for the deprecated `CodeTaskFactory`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d2edce4-67ce-e93c-269e-e4200895a1b9
* Version Independent ID: 4af4b53f-7103-e8b8-996f-79fbc71b83b6
* Content: [MSBuild Inline Tasks - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-inline-tasks)
* Content Source: [docs/msbuild/msbuild-inline-tasks.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/msbuild-inline-tasks.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@rainersigwald Looks like a doc update will be needed in this topic before long. There may be a need to document both methodologies for a period of time?

**Comment by rainersigwald** [comment]
@jeffkl is working on this--Jeff, let's make sure we update docs when we've settled on a direction.

**Comment by rainersigwald** [comment]
@jeffkl do we need more than #1080? If not I think we can close this.

**Comment by jeffkl** [comment]
Yeah this is now done.  Please close this issue.

https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory
