### ISSUE TITLE
Stand Alone Profiler Executable Mentioned But Not available ...

### ISSUE THREAD

**Issue by KdGitHub101** [MicrosoftDocs/visualstudio-docs#8058]
[Enter feedback here]
The information is either just wrong or poorly communicated.
The link in step 1, results in the "Remote Tools for VS 2022" being listed. If you click to download that, you don't get a "vs_standaloneprofiler.exe" file. If you execute the "VS_RemoteToole.exe" that is downloaded, when you click the link in Step1, you don;t get the "vs_standaloneprofiler.exe" installed either. So, where do I get this file?
Very poor documentation. I'd be only to happy to apologise to the authors, if they can show what I'm doing wrong!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb6a064-a3ec-7013-d28f-36d860bb9128
* Version Independent ID: 78db436e-7099-f9b0-4ca4-79a796a595df
* Content: [Install the Stand-Alone Profiler - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/profiling/how-to-install-the-stand-alone-profiler?view=vs-2017)
* Content Source: [docs/profiling/how-to-install-the-stand-alone-profiler.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/profiling/how-to-install-the-stand-alone-profiler.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updated the archive link as well. It should be live by 12:00 PST.
