### ISSUE TITLE
Full install

### ISSUE THREAD

**Issue by chrisdr2** [MicrosoftDocs/visualstudio-docs#806]
In step 2 the following command is given to download the entire layout: vs_community.exe --layout c:\vs2017layout --lang en-US

In step 3 what command line can I use to install everything?

Thanks

Christopher

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@chrisdr2 Thanks for your inquiry; we'll investigate and respond soon.

**Comment by nymbols** [comment]
Run the following command c:\vs2017layout\vs_community.exe
