### ISSUE TITLE
Feature not working as expected

### ISSUE THREAD

**Issue by cleames** [MicrosoftDocs/visualstudio-docs#8062]
[Enter feedback here]
This wants to remove six references my project absolutely uses.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83570d18-e0b6-0097-6966-1ffd6856955e
* Version Independent ID: 2a191933-b3ab-60ae-3e31-f1fb129ceefa
* Content: [Remove unused references - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/remove-unused-references?view=vs-2022)
* Content Source: [docs/ide/reference/remove-unused-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/remove-unused-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@cleames -- thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
