### ISSUE TITLE
Move to namespace refactoring doesn't work with file-scoped namespace

### ISSUE THREAD

**Issue by Davidsv** [MicrosoftDocs/visualstudio-docs#8065]
My file defines the namespace using the file scoped namespace syntax. Following the documentation instructions, I press ctrl + . when the caret is on the class identifier. The context menu that appears does not contain a "Move to namespace" choice.

But, if I change the namespace definition to block scoped namespace, the choice appears as documented.

Please advise on how to access this refactoring when using file scoped namespace. All my files are using file scoped namespaces, so it is not an option for me to revert to block scoped namespace syntax.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaa5d8fa-b34c-4452-931d-b6230e0dff71
* Version Independent ID: 6b10c735-49f1-6341-84f7-6442a6febbdd
* Content: [Move type to namespace - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/move-type-to-namespace?view=vs-2019)
* Content Source: [docs/ide/reference/move-type-to-namespace.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/move-type-to-namespace.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by mikadumont** [comment]
Closing this as a bug to be tracked on Roslyn: https://github.com/dotnet/roslyn/issues/61539
