### ISSUE TITLE
Title of document

### ISSUE THREAD

**Issue by mrdemc** [MicrosoftDocs/visualstudio-docs#807]
Text instead of test

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: da36da82-f6c7-ce0f-1fe4-9b74add6b5a3
* Version Independent ID: 7f2a458d-cf8a-e430-919f-201e64d9dd63
* Content: [Editing Text Mix Models in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/edit-test-mix-models-to-specify-the-probability-of-a-virtual-user-running-a-test)
* Content Source: [docs/test/edit-test-mix-models-to-specify-the-probability-of-a-virtual-user-running-a-test.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/edit-test-mix-models-to-specify-the-probability-of-a-virtual-user-running-a-test.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@mrdemc thank you, i will fix this soon!
