### ISSUE TITLE
grammatical error

### ISSUE THREAD

**Issue by jeffreyb0923** [MicrosoftDocs/visualstudio-docs#8070]
"In Solution Explorer, choose multiple files ..." +

"that have can be compiled actions," < should this say:  

"... that have ACTIONS that CAN BE compiled,"  ?  OR ...
"... that HAVE COMPILED actions," OR ...
"... <something else altogether>"

+ "... open the shortcut menu for one of those files, and then choose Compile, or press Ctrl+F7."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a5f2f50-d3f4-cee5-4345-7d21f138b1fe
* Version Independent ID: 7ecd51c8-e90a-4f15-c301-60496c5c4e1a
* Content: [Building and Cleaning Projects and Solutions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/building-and-cleaning-projects-and-solutions-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/building-and-cleaning-projects-and-solutions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/building-and-cleaning-projects-and-solutions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review my updated wording in [private PR 10043](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10043).
