### ISSUE TITLE
incorrect section heading

### ISSUE THREAD

**Issue by joellyons** [MicrosoftDocs/visualstudio-docs#808]
The instructions section heading is "To specify the agents to use for a scenario".  But, shouldn't it be something like "To specify the percentage of new users to use for a scenario"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bd31ab32-03e7-3af7-24a8-59c41f099e47
* Version Independent ID: ab8d3396-b9ff-306e-d433-845e29b6377d
* Content: [Specify the Percentage of Virtual Users that Use Web Cache Data for load tests in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-specify-the-percentage-of-virtual-users-that-use-web-cache-data#to-specify-the-agents-to-use-for-a-scenario)
* Content Source: [docs/test/how-to-specify-the-percentage-of-virtual-users-that-use-web-cache-data.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/how-to-specify-the-percentage-of-virtual-users-that-use-web-cache-data.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@joellyons thank you, i'll take a look and fix as necessary.
