### ISSUE TITLE
Help button and content when installing dotNet Core

### ISSUE THREAD

**Issue by johnnyv303** [MicrosoftDocs/visualstudio-docs#8081]
The install stalled with a message that I was attempting to add an item to a source-controlled project.... The popup message included a Help button that when clicked resulted in an "F1 help no-match" page.

![image](https://user-images.githubusercontent.com/28766817/170740100-3c1b5ff5-bbe8-4ead-adcc-b0d99eda7f06.png)

![image](https://user-images.githubusercontent.com/28766817/170740124-b06f0453-4842-4378-8400-260dc751c299.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a28ee58-bd99-e74a-0c0c-30f5a41da08e
* Version Independent ID: 2467c672-a567-583c-2801-87dcaf0f2c91
* Content: [F1 help no-match fallback - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/not-in-toc/default?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(keywords_removed)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/ide/not-in-toc/default.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/not-in-toc/default.md)
* Product: **visual-studio**
* Technology: ****
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@johnnyv303 -- it looks like you’re having an issue with installation. If your Visual Studio installation fails, see [Troubleshooting Visual Studio installation and upgrade issues](https://docs.microsoft.com/visualstudio/install/troubleshooting-installation-issues) for step-by-step guidance.​ 

We also offer a [Live Chat](https://visualstudio.microsoft.com/vs/support/#talktous) (English only) support option for installation-related issues.​ 

Here are a few more support options:​ 
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
 

Use your [GitHub](https://github.com/) account to talk to us and other Visual Studio developers in the [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio).

**Comment by gewarren** [comment]
I think this issue was more about the fact that no help page is hooked up to that Help button.
