### ISSUE TITLE
Document MSBuild "ShowProjectFile" logger parameter

### ISSUE THREAD

**Issue by carlreinke** [MicrosoftDocs/visualstudio-docs#8082]
MSBuild has a [`ShowProjectFile`](https://github.com/dotnet/msbuild/blob/9fd120730f6319606b57d412820897e4861d61ac/src/Build/Logging/BaseConsoleLogger.cs#L1054) logger parameter that shows/hides the project file path in error messages.  It should be documented in the [MSBuild Command-Line Reference](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-command-line-reference.md).

**Comment by ghogen** [comment]
@carlreinke 
Thanks, I see that there is such a parameter. So far, I don't see any difference in the output, though I do see it is recognized and sets an internal variable in MSBuild source.
There's another undocumented logger parameter, ShowEnvironment, that does actually show the environment.

**Comment by carlreinke** [comment]
```
Z:\temp\ConsoleApp1\ConsoleApp1>msbuild /verbosity:quiet /nologo
Z:\temp\ConsoleApp1\ConsoleApp1\Program.cs(5,13): warning CS0183: The given expression is always of the provided ('int') type [Z:\temp\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
```

```
Z:\temp\ConsoleApp1\ConsoleApp1>msbuild /verbosity:quiet /consoleLoggerParameters:ShowProjectFile=false /nologo
Z:\temp\ConsoleApp1\ConsoleApp1\Program.cs(5,13): warning CS0183: The given expression is always of the provided ('int') type
```

**Comment by carlreinke** [comment]
Was this supposed to be closed?  The parameter seems to still be undocumented.

**Comment by WilliamAntonRohm** [comment]
@carlreinke -- Carl, thank you for your followup.  This issue was auto-closed after the documentation file was updated and staged for publication.  The updated article will be published live tomorrow.
