### ISSUE TITLE
There are some errors in the document

### ISSUE THREAD

**Issue by sangeun-jo** [MicrosoftDocs/visualstudio-docs#8088]
[여기에 피드백 입력]
1. This document has no way how to add timer objects.
2. itemLabel is not used. The seconds and "Time's up" message must set the itemLable, not the timeLabel.
3. When the Start button is pressed, the button must be disabled. 
`startButton.Enable = false `
must be added to the bottom of the startButton_Click method.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: af83dce0-a830-c876-e355-d9e3ca095b30
* Version Independent ID: af83dce0-a830-c876-e355-d9e3ca095b30
* Content: [Tutorial: Add a timer to a Windows Forms app - Visual Studio (Windows)](https://docs.microsoft.com/ko-kr/visualstudio/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@sangeun-jo, thanks for your feedback. Create a timed Math quiz is a series of 4 tutorials.
1. The timer control is added in [Tutorial Part 3: Add a Timer control to a math quiz WinForms app](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-math-quiz-add-timer?view=vs-2022&tabs=csharp#add-a-countdown-timer) 
2. The time remaining label is added in [Tutorial Part 1](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-math-quiz-create-project-add-controls?view=vs-2022#create-the-time-remaining-box) as timeLabel.
3. Disabling the Start button after click is added in [Tutorial Part 2: Add math problems to a math quiz WinForms app](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-math-quiz-add-math-problems?view=vs-2022&tabs=csharp#add-an-event-handler-to-the-start-button)

Hope this helps! Please let us know if we can help with anything else. Thanks.
