### ISSUE TITLE
Missing tutorial for own SDKs 

### ISSUE THREAD

**Issue by dotChris90** [MicrosoftDocs/visualstudio-docs#809]
This new SDK System is really interesting and makes MSBuild much more comfortable. Just one question : is there a tutorial, example or "how to do" for creating own SDK? just was thinking about a GCC or Clang SDK for myself so i was wondering how to make own SDK :D 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8162092-2fc2-e1a2-8193-0a5abd0f6248
* Version Independent ID: 25c59329-4edd-2c4d-f135-10c19a8a9ff7
* Content: [Sdk Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/sdk-element-msbuild)
* Content Source: [docs/msbuild/sdk-element-msbuild.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/msbuild/sdk-element-msbuild.md)
* Service: **unspecified**
* GitHub Login: @jeffkl
* Microsoft Alias: **jeffkl**

**Comment by gewarren** [comment]
@jeffkl or @Mikejo5000 can one of you address this issue?

**Comment by Mikejo5000** [comment]
@dotChris90 Did you see this topic?
https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk

The Sdk element is mainly used by .NET Core projects currently. There is more info in their docs: 
https://docs.microsoft.com/en-us/dotnet/core/packages
https://docs.microsoft.com/en-us/dotnet/core/tools/csproj

**Comment by dotChris90** [comment]
@Mikejo5000  thanks for Reply. I know that there is possibility to specify a Folder e.g. "C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Hello.World.Sdk\Sdk" with Targets and props. MSBuild even can find. But you Need admin rights for this. From the page you gave me there must be a "nuget" resolver - am I correct that resolver Looks for SDK in ".nuget" Folder and do I always have to define a global.json file for own SDK?

**Comment by dotChris90** [comment]
Ok - i think I found a good solution. 

- Created a nuget package with dummy "SDK" (which contains props and targets). 
- Started a Project with nuget.config and <add key="repositoryPath" Node (referencing my dummy SDK).
- created the global.json and modifed like on page you posted
- modifed msbuild Project file with SDK Attribut 

everything worked! :D thanks for hint. 

the ticket can be closed - but just one last question : the global.json is necessary and the "official way" or is there other way? 

wish you all a good week.

**Comment by Mikejo5000** [comment]
@dotChris90 What is the limitation you see for the global.json? @rainersigwald @jeffkl Per the question above, is global.json the only option?

**Comment by dotChris90** [comment]
@Mikejo5000 just curious if it is the official way or if user shall use other ways. No limitation - dont worry. I find it already very nice way. Thanks. :)

**Comment by rainersigwald** [comment]
Jeff's on vacation this week. `global.json` is the way to go -- see https://github.com/Microsoft/msbuild/issues/2803 for some design notes until we get full documentation for NuGet-delivered SDKs.

**Comment by dotChris90** [comment]
@rainersigwald thanks for inform. :)
