### ISSUE TITLE
Very buggy tutorial

### ISSUE THREAD

**Issue by trstill** [MicrosoftDocs/visualstudio-docs#8091]
Pretty worthless.  Very little of this tutorial matches up with what visual studio 2022 actually creates.
Starting form the first step.  The project type in the tutorial is not available in VS 2022

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@trstill I retested the article and everything worked correctly. There are a couple screenshots out of date. I will clarify a few points. A few possible issues might be that your prerequisities were not installed (the VS workload, or Node.js/npm or the Vue CLI). Also, instructions specify when to right-click the solution, versus the Node project, versus the ASP.NET Core Web API project, but you will see different results if you don't select the right node in Solution Explorer.

**Comment by Mikejo5000** [comment]
Updated screenshots and several edits should go live by EOD Monday.
