### ISSUE TITLE
There is no DATA MENU

### ISSUE THREAD

**Issue by nvnfdddddddd** [MicrosoftDocs/visualstudio-docs#8092]
The is no DATA MENU.  You start the whole thing around the DATA MENU and there is not a DAT MENU.  Fuck...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 233d01cd-0d37-00bd-e5a7-e2f1d5981199
* Version Independent ID: 94efd478-fd6f-67f7-309b-55982e918d95
* Content: [Bind WPF controls to a dataset - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/bind-wpf-controls-to-a-dataset?view=vs-2022)
* Content Source: [docs/data-tools/bind-wpf-controls-to-a-dataset.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/bind-wpf-controls-to-a-dataset.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
Try the `View` menu, and then select `Other Windows>`.
