### ISSUE TITLE
Deeper explanation of how to configure, and options in project files, would be great

### ISSUE THREAD

**Issue by jeffputz** [MicrosoftDocs/visualstudio-docs#8093]
Deeper explanation of how to configure, and options in project files, would be great. Right now it's largely magic. For example, I can see it work even when I save a Typescript file in a web project, but if the TS file is in a Razor Class Library that the web project references, it doesn't reload. If I save a .cshtml file in the RCL, it does propagate the change to the web project that references it.

Maybe what I'm really suggesting is that the doc should describe what front-end client code change scenarios are and are not supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf99ebda-50c8-0eba-4164-6b7b0c5c11c9
* Version Independent ID: cf99ebda-50c8-0eba-4164-6b7b0c5c11c9
* Content: [Write and debug code by using Hot Reload - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/hot-reload?view=vs-2022)
* Content Source: [docs/debugger/hot-reload.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/hot-reload.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by jeffputz** [comment]
@WilliamAntonRohm those resources (especially SO) have a lot of vague answers about changes to .csproj that may or may not be reflective of the release version, and no one was able to [answer my specific question](https://stackoverflow.com/questions/72297714/hot-reload-for-typescript-compile-in-razor-class-library-in-visual-studio-2022) despite 151 views. That's why I'm suggesting that the official docs should have more information about how this stuff works. Developers only like magic until it doesn't work. :)

**Comment by Mikejo5000** [comment]
@jeffputz Their is a page for ASP.NET Core where the more specific guidance belongs for Razor scenarios. I am adding a link to that doc to resolve here. I don't see the TypeScript/Razor scenario described there yet, but I do see some configuration info. But do you mind opening the issue on that article if you would like to see more?
https://docs.microsoft.com/en-us/aspnet/core/test/hot-reload?view=aspnetcore-6.0
