### ISSUE TITLE
Microsoft.VisualStudio.ReleaseManagement.BuildInfo.targets missing in VS2017

### ISSUE THREAD

**Issue by GeorgeTsiokos** [MicrosoftDocs/visualstudio-docs#81]
VS2017 doesn't contain the referenced targets file in this location:
```
$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\BuildInfo\Microsoft.VisualStudio.ReleaseManagement.BuildInfo.targets
```
https://github.com/Microsoft/visualstudio-docs/blame/master/docs/debugger/diagnose-problems-after-deployment.md#L88

https://github.com/Microsoft/azure-docs/blame/master/articles/application-insights/app-insights-how-do-i.md#L100

**Comment by kempb** [comment]
I'm investigating this now, thanks.

**Comment by RoopeshNair** [comment]
AFAIK, Feature was deprecated and removed from VS2017. 

It is recommended to use AppInsights for diagnostic requirements.
https://azure.microsoft.com/en-us/documentation/articles/app-insights-visual-studio/
