### ISSUE TITLE
This page does not correspond to reality!

### ISSUE THREAD

**Issue by ptoye** [MicrosoftDocs/visualstudio-docs#810]
I want to ask a question - went to the dev community page - put in a search which didns't find anything related. So went to the bottom of the page as in the Report New Problem para here and there isn't a "Report New Problem" button. And when I click the "Report Problem" at the top of the page next to the search text I get a window with some very sketchy in formation on it, and when I click "Got it!" I just get back to the search results. So how to I get to ask a question?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d648cd73-34e8-1a47-35cc-3c5a1ff9f8f5
* Version Independent ID: a02d528a-85f7-00f6-cf00-3416713ed4d9
* Content: [How to Report a Problem with Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#report-a-new-problem-a-namereportnewproblema)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio-2017.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/how-to-report-a-problem-with-visual-studio-2017.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ptoye Thanks for your inquiry. The feedback mechanics that we offer are two-fold: 

1. You can [search for and "upvote" an existing problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#search-and-vote-for-similar-problems-a-namesearchandvotea) or [report a new problem](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#report-a-new-problem-a-namereportnewproblema) by using the Report a Problem tool.
2. You can [provide product feedback or a suggestion](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#reporting-alternatives-a-namealternatereportinga) by using the [UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide) forum. 

These feedback options are described on the [How to report a problem in Visual Studio 2017](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) page.

However, if you have a general question, you might want to consider submitting one to [StackOverflow](https://stackoverflow.com/search?q=visual+studio).

Thanks,
~ Terry

**Comment by gewarren** [comment]
@ptoye I think i see where the confusion came in. The "Report new problem" button appears in the Visual Studio UI, not on Developer Community itself. The steps in the article assume you are searching for issues through the Visual Studio interface, not through a web browser. I'll update the topic to make this clearer.

**Comment by ptoye** [comment]
Thanks.
