### ISSUE TITLE
Error in file

### ISSUE THREAD

**Issue by PatrickvanHemert** [MicrosoftDocs/visualstudio-docs#8101]
[Enter feedback here]
Comment out the selected lines button on the Text Editor toolbar. If you prefer to use the keyboard, select Ctrl+E, C.

should be Ctrl+K, C.

Also for undoing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb032bdf-ccea-19a3-d083-7e0466cdf332
* Version Independent ID: f794a23f-f86c-3b9e-962e-171f8e7d9aa9
* Content: [Introduction to editing in the code editor - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-editor?view=vs-2022)
* Content Source: [docs/get-started/tutorial-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/tutorial-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@PatrickvanHemert You're absolutely right; thanks for letting us know. We'll get that fixed and report back after it is.

**Comment by TerryGLee** [comment]
@PatrickvanHemert We've updated the page; we'll close this issue now. Thanks again for your feedback and your interest in improving the Visual Studio documentation!
