### ISSUE TITLE
Missing description for $TICK

### ISSUE THREAD

**Issue by kimrandell** [MicrosoftDocs/visualstudio-docs#811]
Under "Breakpoint Actions and Tracepoints", there is no description for $TICK, and a duplicate entry for $TNAME.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use Breakpoints in the Debugger in Visual Studio - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/debugger/using-breakpoints)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/using-breakpoints.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@kimrandell Thanks for catching this. $TICK appears to be a timestamp in hex format, but I'm asking about it.
