### ISSUE TITLE
setuptools not work

### ISSUE THREAD

**Issue by fenneishi** [MicrosoftDocs/visualstudio-docs#8114]
[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://docs.microsoft.com/nl-nl/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

### problems
I want to use [setuptools](https://setuptools.readthedocs.io/) to installs the module in my Python environment,but I failed and got blew:
> ----- Installing 'D:\qilong\Test\Test_Pybind11\' -----
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
PackagesNotFoundError: The following packages are not available from current channels:
>  - \qilong\test\test_pybind11\
>Current channels:
>  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/win-64
>  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/main/noarch
>  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/win-64
>  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/r/noarch
>  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/win-64
>  - https://mirrors.bfsu.edu.cn/anaconda/pkgs/msys2/noarch
>To search for alternate channels that may provide the conda package you're
>looking for, navigate to
>    https://anaconda.org
>and use the search bar at the top of the page.
>----- Failed to install 'D:\qilong\Test\Test_Pybind11\' -----

The possible reason is what?And how to fixed it? please

### PS
I follow this [tutorial](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md) step by step.

**Comment by WilliamAntonRohm** [comment]
@fenneishi -- thank you for your feedback.  Please see the resource links I mentioned in your previous issue.


@rjmolyneaux -- please look into this potential documentation issue.

**Comment by ijoosong** [comment]
@fenneishi it sounds like it could be a conda issue. what version of conda are you using? Have you taken a look here? https://github.com/conda/conda/issues/9367

**Comment by fenneishi** [comment]
> @fenneishi it sounds like it could be a conda issue. what version of conda are you using? Have you taken a look here? [conda/conda#9367](https://github.com/conda/conda/issues/9367)

thanks a lot ! I'm using  conda 4.13.0.I will check https://github.com/conda/conda/issues/9367

**Comment by rjmolyneaux** [comment]
Hi @fenneishi! Looks like @ijoosong might have provided you with a good resource to follow! Will close this for now. However, should you find yourself needing any further assistance, please do not hesitate to contact us again.

**Comment by rjmolyneaux** [comment]
#please-close
