### ISSUE TITLE
'Follow project coding conventions' needs better documentation

### ISSUE THREAD

**Issue by HughWarrington** [MicrosoftDocs/visualstudio-docs#8115]
> Follow project coding conventions
> 
> When selected, the project's specified coding conventions override any coding conventions you use on your personal projects.

This explanation is too vague and raises more questions than it answers.

1. What does 'the project' refer to when I have open a solution containing multiple projects?
2. What are 'personal projects' and what should they be contrasted to -- 'work projects'? How does Visual Studio know the difference?
3. What are the 'coding conventions' in any case? Does this refer to other settings in the same settings page, and if so, how would I define those on a per-project basis? Or does it refer to the per-language 'Code Style' options pages? Or something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c03f0366-9eb0-a623-57dc-23c34ca5c73a
* Version Independent ID: 4682db7d-610f-2cf1-523b-34fdc10a016f
* Content: [Options, Text Editor, General - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-general?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Text_Editor.General)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.6.1)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-general.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-general.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by HughWarrington** [comment]
I don't understand, closing the old issues makes more noise while not actually helping fix anything. Just order by newest if that's what you want to do.

**Comment by WilliamAntonRohm** [comment]
@HughWarrington -- Hugh, thank you for your follow-up.  In reply to your points:

1. My understanding is that "the project" is the currently selected one.
2. "Personal project" is contrasted [here](https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022) as:
> You can still set your own personal editor preferences in the Visual Studio Options dialog box. Those settings apply whenever you're working in a codebase without an .editorconfig file, or when the .editorconfig file doesn't override a particular setting. 
3.  "Coding conventions" are linked in the updated note in this article to [here](https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022#code-consistency).

Please let me know if this answers your questions.

**Comment by HughWarrington** [comment]
Thanks for the reply. I think I now understand what this checkbox does. It's easier to phrase my new understanding as a suggestion. If this suggestion is nonsense then I still don't understand :-)

I suggest to modify "When selected, the project's specified coding conventions override any coding conventions you use on your personal projects" as follows:
* "the project's specified coding conventions" -> "any .editorconfig files in the project's source tree"
* "any coding conventions you use on your personal projects" -> "the code syntax and style rules defined on the other pages of this settings dialog"

It could even just be labelled "Enable EditorConfig support".

**Comment by j-martens** [comment]
#reassign:@anandmeg

**Comment by anandmeg** [comment]
@HughWarrington, thanks for your feedback. We've updated the doc and the changes should be live by tomorrow. 
Let us know if you have any additional feedback. Thanks!
