### ISSUE TITLE
Stack Trace is Truncated

### ISSUE THREAD

**Issue by YodasWs** [MicrosoftDocs/visualstudio-docs#812]
:warning: The stack trace in IE11 is truncated to 1030 bytes, making this nearly impossible to use when you have a very long stack trace to comb through.

:warning: Even `console.trace()` outputs no more than 1031 bytes! That's so useless!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a75dd21d-d850-a972-3fde-7db8fec9b02a
* Version Independent ID: ffef8042-7b5a-0449-999c-ca8a6e9b72de
* Content: [stack Property (Error) (JavaScript)](https://docs.microsoft.com/en-us/scripting/javascript/reference/stack-property-error-javascript)
* Content Source: [scripting-docs/javascript/reference/stack-property-error-javascript.md](https://github.com/Microsoft/visualstudio-docs/blob/master/scripting-docs/javascript/reference/stack-property-error-javascript.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by bterlson** [comment]
Sorry for the delay. @Mikejo5000 you are correct in that the stack property is not a standard, so the overriding concern is interoperability with other implementations.

@liminzhu can comment on whether Chakra error.stack still exhibits this behavior. If it's just IE11, then as long as the limitation is documented, I think no action is required.

**Comment by liminzhu** [comment]
This behavior is gone in Edge/Chakra.
