### ISSUE TITLE
Branch Name has wrong error message after typing /

### ISSUE THREAD

**Issue by Rose-Kenner-Biamp** [MicrosoftDocs/visualstudio-docs#8128]
When entering a new branch name an error is shown after entering feature/

The error shown is "Invalid character in the branch name".

The error is actually that the branch name cannot end with forward slash.

As a cautious new git user this caused me to make my first branches without being in feature; it would be helpful to have the error message update to be accurate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 982d97c4-0275-dc36-e2e0-669b90d52a7a
* Version Independent ID: 982d97c4-0275-dc36-e2e0-669b90d52a7a
* Content: [Create a branch - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/version-control/git-create-branch?view=vs-2022)
* Content Source: [docs/version-control/git-create-branch.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-create-branch.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Rose-Kenner-Biamp -- Rose, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.

**Comment by Rose-Kenner-Biamp** [comment]
Thank you for the speedy turnaround, William
