### ISSUE TITLE
Add any documentation that can help include assembly version in the publish folder path

### ISSUE THREAD

**Issue by SvendK** [MicrosoftDocs/visualstudio-docs#8133]
I'm building a .NET 6 WPF application and publishing to a folder.
I'd like to include the current assembly version in the publishing folder, like ...\MyApp_1.2.0.23\*.*
Is there any way to accomplish this?
This page suggests to use `$([Class]::Property)` format - like `$([System.Guid]::NewGuid())?  for creating a GUID. 
https://stackoverflow.com/questions/50404043/dynamic-folder-name-for-visual-studio-publish
This works, but only for a subset of system methods, not custom static classes, unfortunately.

Also see my StackOverflow which explains more what I have tried: 
https://stackoverflow.com/questions/72562902/how-to-publish-to-folder-while-including-assembly-version-in-path-in-visual-stud

The feedback for this page is: If it **is** possible to include a version number, maybe also a assembly name, in the folder path, then please add it to this page documentation :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a7f38987-1d2b-6dfc-e531-d1ca50fbb11c
* Version Independent ID: 592a4f31-6e8f-0ba6-4b8d-58b44600faf3
* Content: [Deploy your Visual Studio app to a folder, IIS, Azure, or another destination](https://docs.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components-resources?view=vs-2022)
* Content Source: [docs/deployment/deploying-applications-services-and-components-resources.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/deploying-applications-services-and-components-resources.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@SvendK -- thank you for your thorough feedback.  Please consider these resources:
- [Visual Studio on Microsoft Q&A](https://docs.microsoft.com/answers/products/vs) 
- [Visual Studio MSDN Forum](https://social.msdn.microsoft.com/Forums/vstudio) 
- [Reddit](https://www.reddit.com/r/VisualStudio)

@Mikejo5000 -- please look into this issue.

**Comment by Mikejo5000** [comment]
@SvendK Hi, there is no way to configure a dynamic folder name in the Publish UI. So, it becomes an MSBuild question, which is out of scope for this article. Would you try using [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to ask about this. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by SvendK** [comment]
Sorry for the (very) late response. I had my notifications go to an email folder I wasn't monitoring. That is now fixed...

For anyone ending up on this page after an internet search, I have created a new post for Visual Studio team. 
**Please go and vote for it**
https://developercommunity.visualstudio.com/t/Publish-to-folder:-Add-variables-to-the/10369195
