### ISSUE TITLE
Visual Studio 2022 Issue

### ISSUE THREAD

**Issue by drag737** [MicrosoftDocs/visualstudio-docs#8139]
Hey! I just downloaded Visual Studio and am a completely new user. I am not in full screen mode, but have no Tool menu option. Only  "File | Edit | Selection | View | Go | Run | Terminal | Help". I would really appreciate it if someone could help me figure out how to get the Tools and other menu options working in Visual Studio 2022.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49fe9dd7-3720-5ea9-6c5a-7bde27cb993e
* Version Independent ID: c7c693df-ef68-dc9f-268e-ffac03132a29
* Content: [Customize menus and toolbars - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-customize-menus-and-toolbars-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-customize-menus-and-toolbars-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-customize-menus-and-toolbars-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gregvanl** [comment]
Hi @drag737 From the list of menu options you listed, it appears that you are running Visual Studio Code, not Visual Studio IDE.

What does your editor say on the top menu bar?

You can check your installation by running Help > About and you should see "Visual Studio Code" in the dialog.

If you are running Visual Studio IDE, you can check by running Help > About Microsoft Visual Studio.
