### ISSUE TITLE
Period in new class name leads to VS not appending the file type (ie '.cs')

### ISSUE THREAD

**Issue by RichardWhitfield** [MicrosoftDocs/visualstudio-docs#8140]
Perhaps this is by design for users to easily add files of any type in VS but the behaviour seems unexpected to me.

On action:
- Right click in Solution Explorer -> Add -> Class
- Include a period ('.') in the file name 
- Click 'Add'

Issue/Bug:
VS does not append the file type even for known file types.  

Suggested Fix:
When a known file type is selected in the 'Add New Item' screen then append the filename regardless of whether the typed 'Name' has a period in.  Alternatively pop up a dialogue box to notify the user that, for instance, a 'C# Items : Class' will not be created due to the file name.

![image](https://user-images.githubusercontent.com/17287260/173255507-cc3761da-8359-457a-95cb-22eaa9fa22d4.png)

**Comment by WilliamAntonRohm** [comment]
@RichardWhitfield -- Richard, thank you for your well-researched feedback.  Please add this as a new issue here:

- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
