### ISSUE TITLE
Options, Text Editor, Advanced - Visual Studio (Windows): Clarify meaning of "Box Selection"

### ISSUE THREAD

**Issue by softworkz** [MicrosoftDocs/visualstudio-docs#8144]
![image](https://user-images.githubusercontent.com/4985349/173467653-7c316537-bead-418c-89dc-9c9be5fd4fc4.png)

The sentence is not incorrect, but you really need to read this three times plus the purple box to understand this.

The option naming is really unfortunate, because it gives the impression that you enable some new behavior while it doesn't.

It should better be named like

- Use simple box selection
- Use legacy box selection
- Use classic box selection

even better to reverse the checkbox and name it the other way:

- Use new multi-caret selection 

(enabled by default)

But at the side of the docs, at least that weird sentence could be changed:

> This option is unselected by default, which provides for the following multi-caret selection behavior that's new in Visual Studio 2022

"Select this option to disable the new multi-caret..."  is just a very simple example of what's understandable :-)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e121ed12-639f-15d5-b1f6-b73e59c0d2c1
* Version Independent ID: e121ed12-639f-15d5-b1f6-b73e59c0d2c1
* Content: [Options, Text Editor, Advanced - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-advanced?view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-advanced.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@softworkz Thanks for your feedback; we appreciate it. We've augmented the text on the Docs page, based on your suggestion. However, to influence how the label is phrased in the product itself, please use the [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) feedback mechanism that's designed for product-specific feedback. We'll close this Docs issue now, with our thanks to you for your help with improving the documentation!

**Comment by softworkz** [comment]
Thanks for fixing the docs. Though, please understand that I don't agree that "Suggest a Feature" is the right channel for such matters.

First of all: this is not about a feature - it is about clarity of UI and usability.

Such things are more of a "goes without saying" category. "Suggest a Feature" is about real features and a site where votes are counted to determine which features to implement or not. And unfortunate naming of an option is not something for which much votes are to be expected.

I think for such kind of things, you should have internal channels to communicate. I mean, when even the doc-writers have a hard time to properly explain an option, this should be reason enough for the product/feature owner to re-think about it.

I mean look how ridiculous this is: For example, you create a  product with a button labeled: 

"Do not press this button if you don't want to happen what doesn't happen when you don't press the button"

And then, when customer complain that they do not understand the button, you say to the customer:

"Hm, yea, the label is not ideal, but you will first need to start a voting campaign to see who many other customers will tell us that they don't understand the label from which we already know that it can't be understood" :-)

**Comment by WilliamAntonRohm** [comment]
@softworkz -- thank you for your thorough and clear follow-up.
