### ISSUE TITLE
Options, Text Editor, Advanced - Visual Studio (Windows): Max length explanation incorrect

### ISSUE THREAD

**Issue by softworkz** [MicrosoftDocs/visualstudio-docs#8145]
![image](https://user-images.githubusercontent.com/4985349/173469114-4c7df15f-e2ff-4fc7-9a4a-8b658ea047be.png)

This does not make sense. The value determines up to which length the text will be copied as rich text. But it doesn't limit the amount of text you can copy/paste. Beyond the limit it will still be copied, just as plain text rather than rich text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e121ed12-639f-15d5-b1f6-b73e59c0d2c1
* Version Independent ID: e121ed12-639f-15d5-b1f6-b73e59c0d2c1
* Content: [Options, Text Editor, Advanced - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-advanced?view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-advanced.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-advanced.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@softworkz Thanks for your feedback; we appreciate it. We've augmented the text on the page based on your suggestion. We'll close this issue now, with our thanks to you for your help with improving the Visual Studio documentation!
