### ISSUE TITLE
Visual Studio 2022 keeps asking for credentials.

### ISSUE THREAD

**Issue by gallettoNL** [MicrosoftDocs/visualstudio-docs#8147]
After installing Visual Studio 17.2.x, It keeps asking me for credentials, presumably for Azure Devops.
I can ignore it, everything keeps working Ok, but it's a pain in the b....
The window hides behind the Visual studio window.
Looks like  a bug to me.

Thanks,

Will de Haan

**Comment by WilliamAntonRohm** [comment]
@gallettoNL -- Will, thank you for your feedback.  
- To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
