### ISSUE TITLE
VS2022 properties does not contain a Web tab.

### ISSUE THREAD

**Issue by skrabbe001** [MicrosoftDocs/visualstudio-docs#8150]
I tried to follow the guide, but when I open the properties for the project, it looks like this, there is no "Web" section.

There are only these 7 categories:

Application
Build
Package
Code Analysis
Debug
Resources
TypeScript

I am using VS2022, like the guide - here is a screenshot of my Visual Studio about page:

![image](https://user-images.githubusercontent.com/77054120/173625266-65fea44c-6cc7-4113-a9e2-99b9a44be64c.png)

If course the *ASP.NET and web development workload* is installed.
I am using the IIS Express server included with Visual Studio.
I also tried to start visual studio as admin, but the result was the same.

The problem I am trying to solve, is to get internal errors shown in the visual studio output window, currently they are only shown in ```https://<appname>.scm.azurewebsites.net/api/vfs/LogFiles/eventlog.xml```.

The problem is that an error occurs, but visual studio closes the running process with success (no errors reported). Sigh. 

Here is a picture of my visual studio project properties:

<img width="332" alt="properties" src="https://user-images.githubusercontent.com/77054120/173609221-9797f1aa-7c81-49b1-b5e9-41b03d851975.png">

Here is the image from the guide - it looks like a completely different version of visual studio:

![image](https://user-images.githubusercontent.com/77054120/173624796-8f36d65a-cb61-477b-89ba-6cd3317b10bd.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f92897-6665-8360-154d-7de43c557dfc
* Version Independent ID: 6916e374-6a55-39bf-6858-a13314e69fe8
* Content: [Enable debugging for ASP.NET apps - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-enable-debugging-for-aspnet-applications?view=vs-2022#iis)
* Content Source: [docs/debugger/how-to-enable-debugging-for-aspnet-applications.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/how-to-enable-debugging-for-aspnet-applications.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@skrabbe001 -- thank you for your thorough feedback.

@Mikejo5000 -- please look into this issue.  Also, do you know what the asterisk next to `Web*` stands for?

**Comment by skrabbe001** [comment]
Just as an aside, I found an option in visual studio, that prevents the debug process from stopping, when the sign-in popup is closed:

![image](https://user-images.githubusercontent.com/77054120/173790111-7a04f190-1728-4e17-a1b3-c10ea0c2c498.png)

It was impossible to google.

**Comment by Mikejo5000** [comment]
@scrabbe001 Hi, those properties in your screenshot are for an ASP.NET Core app. The article has a separate sub-section for ASP.NET Core.

**Comment by duaneking** [comment]
Getting the same issue, but for a net48 project.  The Web tab simply doesn't show up.

**Comment by duaneking** [comment]
I'm honestly running into this same issue; The web tab that the docs expect simply do not exist.

**Comment by Mikejo5000** [comment]
Taking a look at this

**Comment by Mikejo5000** [comment]
Tested ASP.NET MVC, and ASP.NET Web API for ASP.NET Framework. I do see the **Web** tab. Web tab is not available for ASP.NET Core. I'm making a clarification to help avoid the confusion here.

**Comment by Mikejo5000** [comment]
Update should be live be EOD today

**Comment by duaneking** [comment]
I am getting no web tab for a net48 project.  What is the guidance?

**Comment by Mikejo5000** [comment]
@duaneking Can you tell me what ASP.NET project template you used to create the app?

**Comment by duaneking** [comment]
Its a Web Solution, hence the confusion over not having a web tab.  Uses net48 MVC.

**Comment by Mikejo5000** [comment]
Is that a third party project? I'm not familiar with it.

**Comment by Mikejo5000** [comment]
@duaneking If you're blocked on this, please use the Report a Problem link.
