### ISSUE TITLE
Describe how to remember "rename file to match type" checkbox

### ISSUE THREAD

**Issue by sandersaares** [MicrosoftDocs/visualstudio-docs#8154]
The page says:

> when you rename a type that matches the name of the file it's in, a checkbox appears that enables you to rename the file at the same time

It would be good to also describe how to make Visual Studio remember the state of this checkbox. I assume such a feature exists, as this is a very common checkbox to want ticked.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d231e9f6-7c0c-7073-6727-81a08019e589
* Version Independent ID: d0078914-0fc3-e988-ce0e-559c09f0b4c8
* Content: [Refactor rename - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/rename?view=vs-2022)
* Content Source: [docs/ide/reference/rename.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/rename.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@sandersaares -- Sander, thank you for your feedback.  Please add it here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
