### ISSUE TITLE
VS2019 Publish. Application Install

### ISSUE THREAD

**Issue by SteveMacha1** [MicrosoftDocs/visualstudio-docs#8179]
I can understand why MS  wants to install installations in a safe folder area, but I still need need to be able to install an application in a folder of my choosing.

**Comment by WilliamAntonRohm** [comment]
@SteveMacha1 -- Steve, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com). 


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
