### ISSUE TITLE
Sample code for EncodeData on DisassemblyData contains errors

### ISSUE THREAD

**Issue by snalexp** [MicrosoftDocs/visualstudio-docs#818]
There is a missing brace after the namespace declaration.
The line 
``for (int i = 0; i < guidDataLength; i++) ``
should be constrained by the sizeof char
``for (int i = 0; i < guidDataLength / sizeof(char); i++)``

Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4328cd3f-fe0f-f0ee-4932-54b740f769db
* Version Independent ID: a00ae928-f4fa-836c-28b4-10c26032ee4c
* Content: [DisassemblyData - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/debugger/reference/disassemblydata)
* Content Source: [docs/extensibility/debugger/reference/disassemblydata.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/debugger/reference/disassemblydata.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@snalexp Thanks for letting us know about these errors! If you'd like to take a stab at updating the topic yourself, there's an Edit button on the top right-hand side. Otherwise we can address it too.

**Comment by snalexp** [comment]
Thanks @gewarren, I've opened https://github.com/MicrosoftDocs/visualstudio-docs/pull/825
