### ISSUE TITLE
Error in DebuggerVisualizer example

### ISSUE THREAD

**Issue by Laniusexcubitor** [MicrosoftDocs/visualstudio-docs#8187]
In section **Add a debuggee-side data object** point 10,
the code should be
```CSharp
// String myString = "Hello, World";
CustomDataObject customDataObject = new CustomDataObject();

DebuggerSide.TestShowVisualizer(customDataObject);
```
instead of
```CSharp
// String myString = "Hello, World";
CustomDataObject customDataObject = new CustomDataObject();

DebuggerSide.TestShowVisualizer(customDataObject.MyData);
```
the created debugger expects the custom object now and not a string and will run in a NullReferenceException otherwise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5d2403-0edc-8ee9-22f6-6ca370b40346
* Version Independent ID: d34a6007-354e-0bdb-3ad7-9f15a2cb56f2
* Content: [Write a visualizer in C# - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2019)
* Content Source: [docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/walkthrough-writing-a-visualizer-in-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Laniusexcubitor -- thank you for finding and fixing this issue.

**Comment by Mikejo5000** [comment]
Merged the fix. Should be live by 12:00 today PST.
