### ISSUE TITLE
"Locals" window does not appear

### ISSUE THREAD

**Issue by asjensse** [MicrosoftDocs/visualstudio-docs#8188]
The window called "locals", used to view local variables and values, is not visible in the menu as this article describes.
That said, it does not appear while searching for "Locals" either

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ba01381-dfb4-7830-e86c-1ee94f346b03
* Version Independent ID: 11513787-4812-9d2d-3288-82d3dc73012d
* Content: [Inspect variables - Autos and Locals windows - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/autos-and-locals-windows?view=vs-2022)
* Content Source: [docs/debugger/autos-and-locals-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/autos-and-locals-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@asjensse Did you try to open the Locals window while paused in the debugger (break mode)? That is the usual problem here. Otherwise, what kind of project / scenario are you working on?

**Comment by asjensse** [comment]
That was the issue. Sorry
