### ISSUE TITLE
Visual studio

### ISSUE THREAD

**Issue by wababa222** [MicrosoftDocs/visualstudio-docs#819]
can't install professional

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Troubleshooting installation issues - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/troubleshooting-installation-issues.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@wababa222 Thanks for contacting us. We're sorry that you're having troubles installing Visual Studio. However, this venue is meant to alert us to issues with the documentation. If you are having issues with installing the product itself, please see the "[More support options](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues#more-support-options)" section of the [Troubleshooting Visual Studio 2017 installation and upgrade issues](https://docs.microsoft.com/en-us/visualstudio/install/troubleshooting-installation-issues) page. There, you'll see that for installation issues, we offer a [live chat](https://www.visualstudio.com/vs/support/#talktous) option, and a [Visual Studio conversation in the Gitter community](https://gitter.im/Microsoft/VisualStudio) option. 

We hope that these options are helpful to you. 

Thanks again,
~ Terry

**Comment by andiguda** [comment]
After the visual studio installer has finished to download and installing it says almost done, then it closes the installer and afeter that it does nothing
