### ISSUE TITLE
AfterBuild/BeforeBuild targets

### ISSUE THREAD

**Issue by smoothdeveloper** [MicrosoftDocs/visualstudio-docs#8193]
I believe AfterBuild and BeforeBuild targets aren't supported anymore in dotnet SDK (they get overwritten somehow), they rather need to be defined as custom targets with `AfterTargets="Build"` or equivalent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72a67233-ab6a-e330-7b2d-21c95dd9caba
* Version Independent ID: 381c76df-d847-6ee0-b16e-c7bbc52cec13
* Content: [MSBuild Targets - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-targets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-targets.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@smoothdeveloper 
Yes, any guidance about these targets needs to be updated, thanks.
There are several options for workarounds, one of which you mentioned. Users can also use explicit imports. These options are discussed thoroughly at https://github.com/dotnet/msbuild/issues/1680
