### ISSUE TITLE
Link to Visual Studio Extensibility Forum is incorrect

### ISSUE THREAD

**Issue by DefaultRyan** [MicrosoftDocs/visualstudio-docs#8200]
On the page [Support for the Visual Studio SDK](https://docs.microsoft.com/en-us/visualstudio/extensibility/support-for-the-visual-studio-sdk?view=vs-2022) it has a link for the "Visual Studio Extensibility Forum".

But that link is https://docs.microsoft.com/en-us/azure/devops/integrate/index?view=azure-devops&viewFallbackFrom=vsts&preserve-view=true which goes someplace completely different.

**Comment by WilliamAntonRohm** [comment]
@DefaultRyan --Ryan, thank you for catching this.  I am updating the article.
