### ISSUE TITLE
Minor typo of "contain" vs "container" 

### ISSUE THREAD

**Issue by leewebb** [MicrosoftDocs/visualstudio-docs#8204]
Under the [Update the code and replace the container](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/docker-tutorial#update-the-code-and-replace-the-container) section "container" is misspelt as "contain" under item 2 (emphasis added):

> 2. Stop and remove the current version of the container. More than one **contain** can't use the same port.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cddd74b1-e0f1-1cae-e92d-c7c2b81e77e3
* Version Independent ID: f853e977-81c2-64d6-682e-1e712344cbad
* Content: [Tutorial: Get started with Docker apps in Visual Studio Code](https://docs.microsoft.com/en-us/visualstudio/docker/tutorials/docker-tutorial)
* Content Source: [docker/tutorials/docker-tutorial.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docker/tutorials/docker-tutorial.md)
* Product: **vs-code**
* GitHub Login: @ucheNkadiCode
* Microsoft Alias: **uchen**

**Comment by ucheNkadiCode** [comment]
Thank you for reporting this!
