### ISSUE TITLE
Task Window is missing in VS 2022 (Mac, ARM)

### ISSUE THREAD

**Issue by cgruenwied** [MicrosoftDocs/visualstudio-docs#8207]
[Hier Feedback eingeben]
The provided description is wrong, as there is no more a task list for vs 2022 ...

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b3b8460c-13aa-7c2b-a82e-17d82b7f0bb1
* Version Independent ID: ba75963d-9300-2a35-8e86-876c0cf60096
* Content: [Task Comments - Visual Studio for Mac](https://docs.microsoft.com/de-de/visualstudio/mac/task-comments?view=vsmac-2022)
* Content Source: [mac/task-comments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/task-comments.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by jmatthiesen** [comment]
Thanks for the feedback! We're working to bring this feature back in an upcoming release. For now I'll go ahead and update the documentation to better clarify that it will be available soon.

**Comment by jmatthiesen** [comment]
#assign:jmatthiesen

**Comment by cgruenwied** [comment]
Cool! Thank you - for the fast reply and the fixing!



Christian Grünwied

Head of IT

AYI Expert



***@***.******@***.***>



AYI® - Tradition, Innovation, Inspiration

http://ashtangayoga.info<http://ashtangayoga.info/>

________________________________
Von: Jordan Matthiesen ***@***.***>
Gesendet: Monday, June 27, 2022 8:25:32 PM
An: MicrosoftDocs/visualstudio-docs ***@***.***>
Cc: Christian Grünwied ***@***.***>; Author ***@***.***>
Betreff: Re: [MicrosoftDocs/visualstudio-docs] Task Window is missing in VS 2022 (Mac, ARM) (Issue #8207)


Thanks for the feedback! We're working to bring this feature back in an upcoming release. For now I'll go ahead and update the documentation to better clarify that it will be available soon.

**Comment by GivennameSurname** [comment]
Hope it will be implemented soon.

**Comment by jmatthiesen** [comment]
Hi, @cgruenwied & @GivennameSurname - I've updated our documentation for now to say this isn't yet supported in Visual Studio 2022 for Mac.

This feature is coming back soon and you can try it in the latest public preview release: http://aka.ms/vsmac-preview

Please let us know what you think!

#please-close

**Comment by cgruenwied** [comment]
Super! I'm very happy - thank you for your effort!
