### ISSUE TITLE
Need more info on how to  registered your GitHub repository with the Visual Studio for Mac team

### ISSUE THREAD

**Issue by JoacimWall** [MicrosoftDocs/visualstudio-docs#8213]
[Enter feedback here]
Can't find any team named Visual Studio for Mac team

Visual Studio for Mac will display the latest version of your extension that is compatible with the Visual Studio for Mac installation that was used to access the extension repository.
As long as you registered your GitHub repository with the Visual Studio for Mac team, your extension release will be picked up by Visual Studio for Mac within 24 hours.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 152afd6c-f908-0041-064d-4513daa7426a
* Version Independent ID: 63210f12-2bb8-515a-f65e-c56930a74d37
* Content: [Troubleshooting: How do I release a new version of my existing extension? - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/migrate-extensions?view=vsmac-2019#release-a-new-version)
* Content Source: [mac/migrate-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/migrate-extensions.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
@JoacimWall -- Joacim, thank you for your feedback.  I believe the team is the group email alias as described at the start of this article:
> As an author of an existing extension, you'll need to follow a different workflow to release further updates. This process consists of:

1. Setting up a public GitHub repository for each extension
1. Sharing the repository URL to the Visual Studio for Mac team via the [extension publishing mailing list](mailto:vsmextpub@microsoft.com)
1. Updating your extension by using the releases feature in GitHub

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.


cc @jmatthiesen for awareness
