### ISSUE TITLE
Add /noscale option

### ISSUE THREAD

**Issue by alansingfield** [MicrosoftDocs/visualstudio-docs#8217]
You can also add the /noscale option to the first section; this opens in a DPI-disabled mode which allows accurate layout on the WinForms designer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05945d0a-396b-0697-ab78-81d617b365c9
* Version Independent ID: 860cb1bf-47aa-b35d-4d30-be9f62796d40
* Content: [Devenv command line switches - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches?view=vs-2022)
* Content Source: [docs/ide/reference/devenv-command-line-switches.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/devenv-command-line-switches.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@alansingfield Thanks for your suggestion; we appreciate it. We've updated the first section of the [Devenv command-line switches](https://docs.microsoft.com/visualstudio/ide/reference/devenv-command-line-switches) page to include the `/noscale` option, per your request. We'll close this issue now, with our thanks to you for your help with improving the Visual Studio documentation!
