### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by iburleigh** [MicrosoftDocs/visualstudio-docs#8227]
[This page seems outdated for Visual Studio for Mac 2022. The screenshots appear to be incorrect.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c1ebf72-a4ef-3b5f-99d5-95a0a83973d9
* Version Independent ID: b839d4b7-e42d-758c-2762-8fc7a93551e9
* Content: [Working with Git - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/working-with-git?view=vsmac-2022)
* Content Source: [mac/working-with-git.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/working-with-git.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by jmatthiesen** [comment]
@iburleigh - thank you for the feedback, this page has been updated to reflect the latest Visual Studio 2022 for Mac release. https://docs.microsoft.com/en-us/visualstudio/mac/working-with-git?view=vsmac-2022

#please-close
