### ISSUE TITLE
Add an option to disable notifcations

### ISSUE THREAD

**Issue by TooManyDots** [MicrosoftDocs/visualstudio-docs#823]
I don't mean "give me the ability to a disable notfication". I mean "never have any notifications". It is so annoying. I decide when I want updates, not you. Stop annoying me and everyone else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3386e-6b18-1cbd-9f1b-523b27b6521b
* Version Independent ID: 5ddf5e28-86d1-28b6-80ef-332bf93e17ac
* Content: [Update Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio)
* Content Source: [docs/install/update-visual-studio.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/update-visual-studio.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@TooManyDots Thanks for providing your feedback. As you've observed, we do document how to turn off the notifications, but it looks like you'd rather there be no notifications in the product at all. We've noted your input here, but if you'd like to provide this product-specific feedback in a venue that is designed specifically for that purpose, please consider adding your input to the [UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide).
