### ISSUE TITLE
Example video can not play.

### ISSUE THREAD

**Issue by zkwhatuwant1993** [MicrosoftDocs/visualstudio-docs#8231]
The example video on youtube in this document can not play. The response is **"Video can not play, this is a private video."** when I access the video link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a0301c8-416c-59be-43a1-b5489716e50b
* Version Independent ID: c20b4f11-e646-5ba3-d5c7-82a753c4eef3
* Content: [Draw shapes and paths - Blend for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/draw-shapes-and-paths?view=vs-2022)
* Content Source: [docs/xaml-tools/draw-shapes-and-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xaml-tools/draw-shapes-and-paths.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @maddymontaquila
* Microsoft Alias: **maleger**

**Comment by TerryGLee** [comment]
@zkwhatuwant1993 Thanks for letting us know. It turns out that the videos are no longer available, so we've deleted the links. We'll close this issue now with our thanks to you for your help in improving the documentation!
