### ISSUE TITLE
Partial info is worst than no info

### ISSUE THREAD

**Issue by AlbertoBN** [MicrosoftDocs/visualstudio-docs#8235]
Apparently a bunch of stuff need to be configured in order for such a project to work.
Here is an example on how  write such a tutorial https://jflower.co.uk/using-a-vue-js-spa-with-asp-net-core-web-api/
Now **that** works as expected. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AlbertoBN Thanks for the tutorial link. It looks interesting. That type of content probably belongs in the ASP.NET docs more than the VS docs, which at least in the JS/TS space are tailored more toward the templates included with VS. (I'm wondering if that tutorial project works correctly in VS? Maybe I will test that at some point.) Closing this for now.
