### ISSUE TITLE
Interactive box Suggestion

### ISSUE THREAD

**Issue by youssefelhefnawy** [MicrosoftDocs/visualstudio-docs#8236]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2019)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**I think you can add a textbox for us to test the regex ourselves**

**Comment by WilliamAntonRohm** [comment]
@youssefelhefnawy -- Youssef, thank you for your suggestion.  Please add it here:
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
