### ISSUE TITLE
Needs update for image for VS 2022 and dotnet 6.x

### ISSUE THREAD

**Issue by ET3117** [MicrosoftDocs/visualstudio-docs#8237]
Pretty much as the headline says - needs to be updated to show more recent images to include VS 2022 and dotnet 6.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875c43bc-a462-823a-28b9-038d8e297c2a
* Version Independent ID: a7ed6cea-1e8a-000f-5447-9bd34c49695a
* Content: [Using Visual Studio on an Azure Virtual Machine](https://docs.microsoft.com/en-us/visualstudio/install/using-visual-studio-vm?view=vs-2022)
* Content Source: [docs/install/using-visual-studio-vm.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/using-visual-studio-vm.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@ET3117, thanks for your feedback and help in improving our docs. I've updated the doc and the changes should be live later today.

Thanks again!
