### ISSUE TITLE
Data Sources Window Icons

### ISSUE THREAD

**Issue by jotway** [MicrosoftDocs/visualstudio-docs#824]
What does the red no entry icon that shows up against some data items mean?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51391fb9-2aec-a122-ef69-1641a559f094
* Version Independent ID: 88c115d2-7c88-312e-650f-fa7db82e1a66
* Content: [Set the control to be created when dragging from the Data Sources window - Visual Studio](https://docs.microsoft.com/en-au/visualstudio/data-tools/set-the-control-to-be-created-when-dragging-from-the-data-sources-window)
* Content Source: [docs/data-tools/set-the-control-to-be-created-when-dragging-from-the-data-sources-window.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/data-tools/set-the-control-to-be-created-when-dragging-from-the-data-sources-window.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@jotway thanks, i will try to find out and let you know.

**Comment by jotway** [comment]
Thank you Gennevieve.

 

I was puzzled by the meaning of the “No Entry” icon.  Maybe the documenters could a visual  like below with a brief explanation for the dummies like me.

 



 

Although any documentation is seldom has the piece of detail you need I think the Microsoft doco is superb.

 

I know how hard it is to produce material of this quality and I thank you for it.

 

Also, impressed by your response.

 

Best regards,

 

Joe Otway

MOBILE: + 61 (0)4 07 02 1188

 

15 Beach Road

Marmion WA 6020

AUSTRALIA

 

PHONE: + 61 (0)8 9447 8427

FAX: + 61 (0)8 9243 0369

EMAIL jotway@megaprime.com.au <mailto:jotway@megaprime.com.au> 

Skype: joe_otway

 

http://www.megaprime.com.au <http://www.megaprime.com.au/> 

 

++++++++++++++++++++++++++

**Comment by gewarren** [comment]
@jotway Thanks for your nice response.

Regarding the icon, are you referring to the cursor icon that appears when you attempt to drag a data source control to a designer? This icon appears because some designers may not support dropping data source controls. 

You can also post your question at https://developercommunity.visualstudio.com and we might be able to better answer your question there.

**Comment by jotway** [comment]
Hello Genevieve.

 

I never seen the cursor icon that appears when you attempt to drag a data source control to a designer.

 

The Icon I meant is depicted in the list of data sources shown in the data Sources Window..

I know the icon’s meaning is described in the body of the document but maybe something like the following would be good too.

 




Short description of the functionality indicated by the icon




Ditto the above




Ditto the above




Ditto the above

Your hard work is most appreciated.

 

Best regards,

 

Joe Otway

MOBILE: + 61 (0)4 07 02 1188

 

15 Beach Road

Marmion WA 6020

AUSTRALIA

 

PHONE: + 61 (0)8 9447 8427

FAX: + 61 (0)8 9243 0369

EMAIL jotway@megaprime.com.au

Skype: joe_otway

 

http://www.megaprime.com.au <http://www.megaprime.com.au/> 

 

++++++++++++++++++++++++++

**Comment by gewarren** [comment]
@jotway Did you ever figure out what the icon was? Could you post a screenshot of the icon in question?

**Comment by gewarren** [comment]
@jotway To prioritize our work, we are closing this issue due to low page views on the topic in question (~350/month) and that we haven't had any other inquiries about the icon you mentioned.
