### ISSUE TITLE
Incorrect link for 'inferred anonymous type member names'

### ISSUE THREAD

**Issue by HughWarrington** [MicrosoftDocs/visualstudio-docs#8246]
The link next to 'Apply inferred anonymous type member names preferences' is wrong. It takes you to docs for 'this and Me preferences' instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faebd126-53cd-1a98-bf75-38225933b0f2
* Version Independent ID: 4340fcba-6779-68d2-6c51-2ae37123dc26
* Content: [Code style options and code cleanup - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2022)
* Content Source: [docs/ide/code-styles-and-code-cleanup.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/code-styles-and-code-cleanup.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@HughWarrington -- Hugh, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
