### ISSUE TITLE
Old Link?

### ISSUE THREAD

**Issue by doverain** [MicrosoftDocs/visualstudio-docs#8250]
On this webpage:  https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-visual-studio?view=vs-2022
There is a link on the lower left, under Resources for "JavaScript and TypeScript docs repo" that seems old:
https://github.com/Microsoft/JSTSdocs
It is for VS 2017 and 2019.  Surely there's something more recent?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6dfb3b1-b0cd-5f84-5bd8-e8777328430a
* Version Independent ID: ea11fd8a-cd57-a76e-ac76-f64b0d52ec8e
* Content: [JavaScript and TypeScript in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/javascript/javascript-in-visual-studio?view=vs-2022)
* Content Source: [docs/javascript/javascript-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/javascript-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@doverain -- thank you for your question.  I am investigating.

**Comment by WilliamAntonRohm** [comment]
@doverain -- the Visual Studio 2022 replacement for those documents is [Visual Studio tutorials | JavaScript and TypeScript](https://docs.microsoft.com/en-us/visualstudio/javascript/?view=vs-2022).  I have updated the title of the resource link to clarify that it is for older versions.
