### ISSUE TITLE
How to update key bindings

### ISSUE THREAD

**Issue by tfrokt** [MicrosoftDocs/visualstudio-docs#8255]
```
1. Select Visual Studio (menu) > Preferences (⌘,).
2. Go to Environment > Key Bindings.
3. Scroll through the list, or search for the shortcut or command.
```

a) Can't find "Environment" anywhere after Preferences (⌘,)
![Screen Shot 2022-07-11 at 4 57 15 pm](https://user-images.githubusercontent.com/82917641/178206548-ebc6b32a-4f12-4bc8-b406-ef3569cbf7bd.png)

b) Searching for "key bindings" shows key bindings settings, but: there is no list ..
![Screen Shot 2022-07-11 at 4 58 41 pm](https://user-images.githubusercontent.com/82917641/178206631-9107f630-7137-449b-93be-67ae0f2265c1.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 875d8f40-071d-4d89-5da1-7e43100da6e8
* Version Independent ID: fcd8dcad-dbe6-916c-7b68-78d433a0c12a
* Content: [Keyboard navigation in Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/accessibility-keyboard?view=vsmac-2022)
* Content Source: [mac/accessibility-keyboard.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/accessibility-keyboard.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
@tfrokt -- Tobias, my mistake.  That command path doesn't apply to Mac.

@jmatthiesen -- Jordan, please look into this issue.
