### ISSUE TITLE
No indication of where the magic strings come from

### ISSUE THREAD

**Issue by r3m0t** [MicrosoftDocs/visualstudio-docs#826]
Where does ToolNumKeys, ToolDir0 etc come from? Are they documented? Do they match .vssettings files, if so what elements/attributes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cda15bb6-a9d7-fbc7-fa47-c75ac51ccc88
* Version Independent ID: f0c858f7-c1fa-4c06-c394-d0de661ed7ee
* Content: [Writing to the User Settings Store - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/writing-to-the-user-settings-store)
* Content Source: [docs/extensibility/writing-to-the-user-settings-store.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/writing-to-the-user-settings-store.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
@r3m0t These are the registries settings for adding an External Tool (Tools > External Tools... > Add) and is just being used as an example to illustrate the Settings Store API. They are an implementation detail of External Tools registration (they could change) and not an actual extension point.
You can check the latest version of the settings for your install per the registry path described.
![image](https://user-images.githubusercontent.com/12818376/38950234-b0a44724-42f9-11e8-88e0-5a4cb5973f3f.png)
