### ISSUE TITLE
Release date incorrect for Visual Studio 2019 version 16.11.17

### ISSUE THREAD

**Issue by t-anderson** [MicrosoftDocs/visualstudio-docs#8260]
Date is showing July 21 instead of July 12
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes?view=vs-2022#visual-studio-2019-version-1611-releases
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes?view=vs-2022#release-notes-icon-visual-studio-2019-version-161117

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 155d0d14-d882-6811-e5f5-0f92c4ac6c26
* Version Independent ID: a9744c85-d4e0-7fb2-0833-02da5ac72fde
* Content: [What's new in Visual Studio docs - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/whats-new-visual-studio-docs?toc=%2Fvisualstudio%2Freleases%2Ftoc.json&bc=%2Fvisualstudio%2Freleases%2F_breadcrumb%2Ftoc.json&view=vs-2022)
* Content Source: [docs/ide/whats-new-visual-studio-docs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/whats-new-visual-studio-docs.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by WilliamAntonRohm** [comment]
@t-anderson -- these dates have been corrected.
