### ISSUE TITLE
video in docs for debugging python and native c modules can not play: Video unavailable This video is private

### ISSUE THREAD

**Issue by code4lala** [MicrosoftDocs/visualstudio-docs#8266]
[Enter feedback here]

> For an introduction to building, testing, and debugging native C modules with Visual Studio, see [Deep Dive: Create Native Modules](https://youtu.be/D9RlT06a1EI) (youtube.com, 9m 09s). The video is applicable to both Visual Studio 2015 and 2017.

the link can not play
https://youtu.be/D9RlT06a1EI

Video unavailable
This video is private

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 702dd6fa-5ad3-b9c7-04bc-e9431c228623
* Version Independent ID: 4d8a2c98-429a-b04e-1489-74475df5951a
* Content: [Mixed-mode debugging for Python - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/debugging-mixed-mode-c-cpp-python-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/debugging-mixed-mode-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by WilliamAntonRohm** [comment]
@code4lala -- thank you for your feedback.  This video has been retired, and I am updating the article.

**Comment by j-martens** [comment]
@WilliamAntonRohm is this issue ready to be closed? Thank you.

**Comment by WilliamAntonRohm** [comment]
Thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
