### ISSUE TITLE
Property page seems to be missing a lot of settings

### ISSUE THREAD

**Issue by adegeo** [MicrosoftDocs/visualstudio-docs#8267]
The DEBUG tab listed in the page no longer exists in this way. Instead there is a single link that opens a launch profile configuration window where you can configure different launch options.

The BUILD tab shows 5 settings in the article, yet in Visual Studio there are 42 settings split between 6 sub sections.

![image](https://user-images.githubusercontent.com/67293991/178768952-84b26f35-917e-4fa0-ac29-76f154e99a11.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70dc5ee9-90cf-6465-2cf5-3a8866d624de
* Version Independent ID: 70dc5ee9-90cf-6465-2cf5-3a8866d624de
* Content: [Project Settings for a .NET C# debug config - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/project-settings-for-csharp-debug-configurations-dotnetcore?view=vs-2022)
* Content Source: [docs/debugger/project-settings-for-csharp-debug-configurations-dotnetcore.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/project-settings-for-csharp-debug-configurations-dotnetcore.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@adegeo I do see the info on the Launch Profiles UI here; let me know if you were looking for something different. For Build tab, I believe the intent was to document the settings most relevant to debugging (the full Build tab ref is a link in the intro). I will clarify this in the doc though.

**Comment by adegeo** [comment]
Ack @Mikejo5000 Yeah I added that debug in reediting my issue before submission. Sorry about that. I'm not seeing the full build tab reference link? I see a single link in the first paragraph that just navigates down, and the other links don't seem to go to a reference page.

**Comment by Mikejo5000** [comment]
Ah, OK, thanks. There should be a link to the Build tab UI ref doc. I'll add that.
