### ISSUE TITLE
Typo error - VS2022 page

### ISSUE THREAD

**Issue by RaviKandula** [MicrosoftDocs/visualstudio-docs#8268]
Typo error. 
![VS2022-typo](https://user-images.githubusercontent.com/7104843/178808324-38103195-5381-4d11-bfa6-2ed8b12ba3dc.PNG)

![image](https://user-images.githubusercontent.com/7104843/178808099-f72565da-b603-4b93-a191-ff753bdf3f05.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@RaviKandula -- Ravi, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
