### ISSUE TITLE
incorrect variable type and information.

### ISSUE THREAD

**Issue by Riahoo** [MicrosoftDocs/visualstudio-docs#8275]
the the datatype (NothwindDataset) are incorrect and also the method within it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7e89db1-8103-ace1-e707-edcceaf5991e
* Version Independent ID: 2ecdf830-2edf-00ac-8a08-62e5a4c9a49e
* Content: [Edit data in datasets - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/data-tools/edit-data-in-datasets?view=vs-2022&tabs=csharp)
* Content Source: [docs/data-tools/edit-data-in-datasets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/edit-data-in-datasets.md)
* Product: **visual-studio-windows**
* Technology: **vs-data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Riahoo -- Riahoo, thank you for your feedback.  Please be more specific, as there are several instances.
