### ISSUE TITLE
Please describe how to configure VS2022 project to target ARM64 platform

### ISSUE THREAD

**Issue by tauheedul** [MicrosoftDocs/visualstudio-docs#8278]
Please update documentation to include steps to include ARM64 as a target platform for debug and release.
Presently this page only describes x86 and x64 targeting 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb5a706d-01d5-40c8-69af-e223a73a5948
* Version Independent ID: 8d5a1950-1b98-7e22-0f40-02a8ab0e7233
* Content: [How to: Configure projects to target platforms - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms?view=vs-2022)
* Content Source: [docs/ide/how-to-configure-projects-to-target-platforms.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-configure-projects-to-target-platforms.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@tauheedul 
Thanks - we'll need to add information to support this scenario. Here is some basic information on ARM64 development in Visual Studio generally: https://devblogs.microsoft.com/visualstudio/arm64-visual-studio/
