### ISSUE TITLE
Edit and Continue means a lot of waiting

### ISSUE THREAD

**Issue by bmusical** [MicrosoftDocs/visualstudio-docs#8282]
I'm writing a fairly sizeable Blazor Server app and sometimes, Edit and Continue leaves me waiting so long I have to kill VS 2022 and restart it. I'm sure this has been reported, just testifying that it can really affect work time. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bd35f01-ab8a-78ff-028a-e3bac4370161
* Version Independent ID: 40f17fad-6b3b-66b2-2644-a267a76b4cc9
* Content: [Stop Code Changes - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/how-to-stop-code-changes?view=vs-2022)
* Content Source: [docs/debugger/how-to-stop-code-changes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/how-to-stop-code-changes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@bmusical -- Harvey, thank you for your feedback.  Please add this product-related issue here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
