### ISSUE TITLE
Feedback on GitHub integration in Visual Studio

### ISSUE THREAD

**Issue by wbaker51** [MicrosoftDocs/visualstudio-docs#8298]
I am a former developer and development manager. I currently teach programming at Clark Community College in Vancouver WA. I use Visual Studio Code for my Python class. The integration with GitHub is simple and straight forward and works 99% of the time. I use GitHub Classroom to create a repo for each student. They clone the repo to their machine, do an assignment, then commit and push back to GitHub. A straightforward workflow.

I also teach an intro C# class using Visual Studio. I am updating my content to use VS Community 2022 for this fall. I have NOT been able to figure out how to execute the same workflow in VS. I'm not sure what is going on, but it is not pushing to the GitHub repo that I cloned to my machine. I've been at this for hours over multiple days. I'm giving up and will be using GitHub Desktop to clone, commit and push the repos.

In short, the Git integration in VS seems to be overly complicated and I can't seem to make it work for my simple workflow.

email: bill@baker88.com or wbaker@clark.edu
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47681749-a303-6964-5aaf-50669805b780
* Version Independent ID: 47681749-a303-6964-5aaf-50669805b780
* Content: [Clone a repo in Visual Studio](https://docs.microsoft.com/en-us/visualstudio/version-control/git-clone-repository?view=vs-2022)
* Content Source: [docs/version-control/git-clone-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-clone-repository.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Taysser-Gherfal FYI

**Comment by TerryGLee** [comment]
@wbaker51 Thanks for your feedback; we'll follow up with you under separate cover. Meanwhile, we'll close this GitHub Issue as it's not specifically related to documentation, along with our thanks to you for your interest in our products and services.
