### ISSUE TITLE
How to deploy ASP.NET Core API and React in separate projects

### ISSUE THREAD

**Issue by quanljh** [MicrosoftDocs/visualstudio-docs#8299]
Hi,  I'm following this guide, but I didn't find any info about deploy and publish.
Do we have a doc introducing how to deploy under this new solution structure?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@quanljh -- thank you for your feedback and question.  Please see the Note at the beginning of this article, and [this GitHub comment](https://github.com/MicrosoftDocs/visualstudio-docs/issues/7135#issuecomment-954217538).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
