### ISSUE TITLE
"Generate files with the TextTransform utility" page has outdated file paths

### ISSUE THREAD

**Issue by CalebBellWebCE** [MicrosoftDocs/visualstudio-docs#8305]
The page lists the paths where the TextTransform.exe utility can be found, but those paths say "2019" (rather than "2022") and also reference the "Program Files (x86)" directory (as you would expect for a 32-bit installation) rather than the "Program Files" directory (as you would expect for a 64-bit installation).

> TextTransform.exe is located in the following directory:
> 
> \Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE
> 
> for Professional edition, or
> 
> \Program Files (x86)\Microsoft Visual Studio\**2019**\Enterprise\Common7\IDE
> 
> for Enterprise edition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8177d9b-f8d7-419e-d81d-ce25a44b084f
* Version Independent ID: 43a69770-1eab-06e1-868c-3d8f1c32716d
* Content: [Generating Files with the TextTransform Utility - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/generating-files-with-the-texttransform-utility?view=vs-2022#feedback)
* Content Source: [docs/modeling/generating-files-with-the-texttransform-utility.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/generating-files-with-the-texttransform-utility.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by WilliamAntonRohm** [comment]
@CalebBellWebCE -- Caleb, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
