### ISSUE TITLE
Assembly sinning is needed in NET Core project when publish it by ClickOnce

### ISSUE THREAD

**Issue by John-Qiao** [MicrosoftDocs/visualstudio-docs#8307]
The publishing assembly needs to be signed with a strong name key file in .NET Core project, if not, ApplicationSettingsBase.Upgrade Method not copying settings after new ClickOnce publish. We should document the signing is necessary and  it can be configured in .NET Core project's properties. Please see dryms's question and solution in his ticket here: https://developercommunity.visualstudio.com/t/ApplicationSettingsBaseUpgrade-Method-n/1672135.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69f461aa-b3ae-4202-4f1f-d1b440f1cd63
* Version Independent ID: 48b9d6c3-3ca8-66c9-32ab-364fdb49ae16
* Content: [ClickOnce and Application Settings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/deployment/clickonce-and-application-settings?view=vs-2022)
* Content Source: [docs/deployment/clickonce-and-application-settings.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/clickonce-and-application-settings.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@John-Quao Thanks for the feedback! Appreciate the suggestion. I wonder if this is a bug? From the ticket: 
*For .NET Core and .NET 5+, strong-named assemblies do not provide material benefits. The runtime never validates the strong-name signature, nor does it use the strong-name for assembly binding.*
Maybe with ClickOnce, it does matter, and this doesn't really apply...

**Comment by Mikejo5000** [comment]
I asked about this issue, and it is believed to be a bug in .NET deployment. Closing, as we are only tracking doc issues here. Please comment further in the feedback ticket you mentioned, or open a new one, if this is still an issue.
