### ISSUE TITLE
Doesn't work in 17.6.4 - "Evaluating the function timed out" error

### ISSUE THREAD

**Issue by dozer75** [MicrosoftDocs/visualstudio-docs#831]
I get this error all the time in the above mentioned version since it has inline variables, doing what the message says and this article doesn't fix the issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cfd7078-683e-9fd6-247b-e75d4ed16a32
* Version Independent ID: ae3300c4-55a8-59b6-846b-50c48c88dcfe
* Content: [Error: Evaluating the function 'function' timed out and needed to be aborted in an unsafe way - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way)
* Content Source: [docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/error-evaluating-the-function-function-timed-out-and-needed-to-be-aborted-in-an-unsafe-way.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@dozer75 Thanks for reporting this. Have you been able to identify a fix that does work in your scenarios? I could update the doc.

**Comment by dozer75** [comment]
Unfortunately no I haven't. I was hoping that someone else had any suggestions.

**Comment by Mikejo5000** [comment]
@andysterland Andy, do you know someone who might be able to help with this?

**Comment by Mikejo5000** [comment]
Sorry for the delayed response on this issue. I'm asking about it.

**Comment by dozer75** [comment]
Sorry for the delay, an update on this from me, It seems that this was caused by a function in Resharper to watch variables inline in code together with VS on larger solution, by disabling that functionality the issue went away for me...

**Comment by edward-a** [comment]
I have the same problem with 15.7.4. Very annoying. Please fix!

**Comment by gyurisc** [comment]
I have the same problem with 15.7.3. Please fix, it drives me crazy and I cannot do my job :((((

**Comment by Mikejo5000** [comment]
Asking about this. @andysterland

**Comment by cccuscott** [comment]
Resharper was the culprit for me as well.

**Comment by Mikejo5000** [comment]
There were a few changes in 15.8 that may reduce the circumstances where you see this error. However, it's best to use the Send Feedback link at the top of VS and choose Report a Problem.

**Comment by gewarren** [comment]
The product team requested that this issue stay open.

**Comment by ghogen** [comment]
Closing this issue - this repo is only for doc issues, so any product issues need to be tracked in the appropriate place, on https://developercommunity.visualstudio.com/spaces/8/index.html
