### ISSUE TITLE
Having Visual Studio properties in projects means changing thousands of projects' settings. 

### ISSUE THREAD

**Issue by br2aj** [MicrosoftDocs/visualstudio-docs#8311]
If you're trying to discourage people from upgrading, that will do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b4f9424-22ae-4731-2ba3-7f0fd867f299
* Version Independent ID: 7925b401-247e-dd53-c44d-173f19243f42
* Content: [Debug Source Files/Solution Property Pages - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-source-files-common-properties-solution-property-pages-dialog-box?view=vs-2022)
* Content Source: [docs/debugger/debug-source-files-common-properties-solution-property-pages-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/debug-source-files-common-properties-solution-property-pages-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@br2aj -- thank you for your feedback.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
