### ISSUE TITLE
DebuggerDisplay only appears to work on types

### ISSUE THREAD

**Issue by sfallier** [MicrosoftDocs/visualstudio-docs#8312]
[Enter feedback here]

The documentation says the DebuggerDisplayAttribute can be used for "types, delegates, properties, fields, and assemblies", but in my experimental experience I've only had it work when applied to type definitions.  Scouring the internet, there's stackoverflow posts that claim this worked way back in Visual Studio 2013, but not in any visual studio version since then.  The Quick Actions menu for properties and fields doesn't have an option to add a DebuggerDisplay, as it does for a class - which makes me think this is known and intentional.

Based on the documentation, I'd expect something like this to work, but it does not:
```
//[DebuggerDisplay("TimeStamp - {new DateTime(TimeStamp * 1000)}")] // This works for instances of SomeClass
public class SomeClass
{
	// Display time stamp in seconds as a date/time string.  This has no effect on the debugger UI.
	[DebuggerDisplay("{new DateTime(TimeStamp * 1000)}")]
	public int TimeStamp { get; private set; }
}
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 653452d1-1586-e971-1f6c-370a91be613f
* Version Independent ID: 348f41ea-994c-7ed2-7af5-77077f2b5696
* Content: [Display custom info using DebuggerDisplay - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/using-the-debuggerdisplay-attribute?view=vs-2022)
* Content Source: [docs/debugger/using-the-debuggerdisplay-attribute.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/using-the-debuggerdisplay-attribute.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@sfallier I'm asking about this.

**Comment by Mikejo5000** [comment]
@sfallier Looking at a few things, I'm thinking it always needs to be applied at the class level. (There are no other examples.) But the string name specified in the attribute can be a field, property, or method.

From the Remarks in the API:

The [DebuggerDisplayAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.debuggerdisplayattribute.-ctor?view=net-6.0) constructor has a single argument: a string to be displayed in the value column for instances of the type. This string can contain braces ({ and }). The text within a pair of braces is evaluated as the name of a **field, property, or method**. For example, the following C# code causes "Count = 4" to be displayed when the plus sign (+) is selected to expand the debugger display for an instance of MyHashtable.

```
[DebuggerDisplay("Count = {count}")]  
class MyHashtable  
{  
    public int count = 4;  
}
```

**Comment by Mikejo5000** [comment]
Updating doc. Got confirmation that you can't apply the attribute to fields and properties anymore. Thanks, @sfallier !
Fix should be live by noon tomorrow.
