### ISSUE TITLE
Code coverage option only available in VStudio Enterprise

### ISSUE THREAD

**Issue by ericnewton76** [MicrosoftDocs/visualstudio-docs#8313]
It should be noted that Code Coverage is only availabe in VStudio Enterprise 2019 and not in the SKU i have, Professional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Code coverage testing - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2022&tabs=csharp)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ericnewton76** [comment]
Sorry just noticed this in Requirements... but I feel like it should be in the paragraph as well.

**Comment by WilliamAntonRohm** [comment]
@ericnewton76 -- Eric, thank you for your suggestion.  I've reviewed this article, and the subsequent paragraphs already rely on the Requirements statement.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
