### ISSUE TITLE
Unclear what happens if you <Import> a non-existent file

### ISSUE THREAD

**Issue by drewnoakes** [MicrosoftDocs/visualstudio-docs#8316]
As discussed in https://github.com/dotnet/project-system/pull/8341, it seems that an `<Import>` element might not fail if the source file doesn't exist on disk. Is that the case? It would be good to explain that in this document.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af512ce8-46bd-b15a-c5a2-f8315d2b258a
* Version Independent ID: e2c221b8-466f-df7f-078c-bab89be71828
* Content: [Import Element (MSBuild) - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/import-element-msbuild?view=vs-2022)
* Content Source: [docs/msbuild/import-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/import-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@drewnoakes 
I get MSB4019

`MSBuild version 17.4.0-preview-22372-01+a44cc4393 for .NET Framework
Build started 8/10/2022 12:59:33 PM.
Project "c:\source\repos\MSBuild-import\testimport.csproj" on node 1 (default targets).
c:\source\repos\MSBuild-import\testimport.csproj(2,5): error MSB4019: The imported project "c:\source\repos\MSBuild-imp
ort\foo.proj" was not found. Confirm that the expression in the Import declaration "foo.proj" is correct, and that the
file exists on disk.
Done Building Project "c:\source\repos\MSBuild-import\testimport.csproj" (default targets) -- FAILED.


Build FAILED.

"c:\source\repos\MSBuild-import\testimport.csproj" (default target) (1) ->
  c:\source\repos\MSBuild-import\testimport.csproj(2,5): error MSB4019: The imported project "c:\source\repos\MSBuild-i
mport\foo.proj" was not found. Confirm that the expression in the Import declaration "foo.proj" is correct, and that th
e file exists on disk.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.47`

**Comment by ghogen** [comment]
This seems like an MSBuild product issue.

**Comment by WilliamAntonRohm** [comment]
@drewnoakes -- Drew, please add this as a suggestion:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@ghogen -- Gordon, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
