### ISSUE TITLE
The page miss how to maintain OpenAPI connected services

### ISSUE THREAD

**Issue by JanRou** [MicrosoftDocs/visualstudio-docs#8317]
It's easy to **add** a new OpenAPI connected service. However the maintenance is the real unsolved problem in VS2022. It's the good old Microsoft way: Restart from scratch. I expected more from Microsoft than just a tool to create a connected service when using the term "Manage" and the possibility to "Edit", which for openAPIs don't work at all.
Please describe:

- The workarounds for proper maintenance of OpenAPis.
- How to handle two OpenAPIs that result in compiler errors due to two set of NSWAG generated ApiException partial classes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55284369-f16f-2748-2a55-8cd24a06b940
* Version Independent ID: f7b0c577-b584-98dc-90a2-4efcf095b35d
* Content: [Add references in the Reference Manager - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-add-or-remove-references-by-using-the-reference-manager?view=vs-2022)
* Content Source: [docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-add-or-remove-references-by-using-the-reference-manager.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@JanRou -- Jan, thank you for your feedback.  This article describes how to use the UI in Visual Studio to add or remove references. It's not meant to describe how to resolve errors or to outline a maintenance scenario to manage references.

Please add your product suggestion here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
