### ISSUE TITLE
symbols locations does not work.

### ISSUE THREAD

**Issue by HppZ** [MicrosoftDocs/visualstudio-docs#832]
I add a location here:  D:\appsymbols\, but VS2017.15.6.2 can not find those pdbs in that folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce80d99-822d-3e3a-4c7f-6ec593029cef
* Version Independent ID: 61420028-368e-e122-1490-003b9340cb39
* Content: [Specify symbol (.pdb) and source files in the debugger - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger)
* Content Source: [docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Need more info to help resolve issue
