### ISSUE TITLE
Named Domain Class tool??

### ISSUE THREAD

**Issue by kwlininger** [MicrosoftDocs/visualstudio-docs#8324]
[Enter feedback here]
The walk-thru says "Use the Named Domain Class tool to..." I cannot find on this page or in a google search where in the world the "Named Domain Class tool" is.  I hope by the time you read this to have figured it out, but for the next guy, please provide some kind of link or help text to explain how to get to this tool, and the other tools mentioned after this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 211cc693-f42f-c8a6-1a94-698c20d32e57
* Version Independent ID: 8dd135d0-0dca-17af-0961-e2da4e545bf4
* Content: [Create a Windows Forms-Based Domain-Specific Language - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/creating-a-windows-forms-based-domain-specific-language?view=vs-2022)
* Content Source: [docs/modeling/creating-a-windows-forms-based-domain-specific-language.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/creating-a-windows-forms-based-domain-specific-language.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
Hi @kwlininger, you can find the **Named Domain Class** tool as well as any other tool mentioned here in the **Toolbox** tool window. In case it's hidden you can open it via View->Toolbox. I hope this helps.

**Comment by TimShererWithAquent** [comment]
Thanks @kwlininger - We'll look at adding some detail -

**Comment by WilliamAntonRohm** [comment]
@kwlininger, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
