### ISSUE TITLE
Missing C:\BuildTools

### ISSUE THREAD

**Issue by kerrhome** [MicrosoftDocs/visualstudio-docs#833]
I run this exactly as it is written, but when I start up a container there is no C:\BuildTools at all.  I look in C:\Program Files (x86) and visual studio isn't there either.

I'm running a powerful server with fresh installation of Windows 10 Pro for Workstations 1709 and the latest stable version of Docker, 18.03.0-ce-win59 (16762).  I have 14TB of disk space.  I have Docker configuration storage-opts set to size=200G.  I see no failures when running this and the exit value is zero.  I had to comment out the ENTRYPOINT line because C:\BuildTools did not exist.  I tried uninstalling Docker, then HyperV, and reinstalling HyperV, reboot, then Docker.  I still get the same result.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Build Tools into a Container - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container#step-5-create-and-build-the-dockerfile)
* Content Source: [docs/install/build-tools-container.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/build-tools-container.md)
* Service: **unspecified**
* GitHub Login: @heaths
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@kerrhome Thanks for your inquiry; we'll investigate and respond soon. (@heaths - FYI)

**Comment by kerrhome** [comment]
btw, I was able to use this dockerfile adding '--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended to the vs_buildtools.exe execution and it does work:

https://blogs.msdn.microsoft.com/heaths/2017/09/18/installing-build-tools-for-visual-studio-2017-in-a-docker-container/

**Comment by heaths** [comment]
The dockerfiles and instructions were tested, so it may be something specific to your configuration. If you start the container, and download and run https://aka.ms/vscollect, you can copy the logs out of the container for further analysis.

**Comment by kerrhome** [comment]
Reinstalling HyperV and Docker resolved the issue.

**Comment by heaths** [comment]
See https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools for the individual component IDs you can pass to `--add`. We documented all the command line arguments including `--includeOptional` at https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio.

**Comment by solvingj** [comment]
Thank you very much.

**Comment by solvingj** [comment]
I've installed the `build_tools` in a windows container with the following commands, but the build tools can't find the `v140` toolset.  Is there something we can set in our build server/image to help visual studio find the tools?  For example, set an environment variable?

Alternatively, is there a different/official process for automated downloading and installing the build tools which we can use?  I believe the chocolatey packages are outdated. 

```
RUN choco install --yes visualstudio2017buildtools --pacakge-parameters --includeRecommend --includeOptional

RUN choco install --yes visualstudio2017-workload-vctools --includeRecommend --includeOptional
```

The logs showed the v140 toolset get downloaded and installed: 
```
Installed:
 - kb3033929 v1.0.3
 - chocolatey-core.extension v1.3.3
 - visualstudio2017-workload-vctools v1.2.0
 - vcredist2017 v14.12.25810
 - vcredist140 v14.12.25810
 - kb3035131 v1.0.1
```

The files are all where they're supposed to be: 
```
d:\sources>docker run --rm  -v d:\sources\git-new\CMN\vs_base:C:/Users/ContainerAdministrator/project windows_build_container:latest cmd /C "dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\""
 Volume in drive C has no label.
 Volume Serial Number is 7CEB-CA94

 Directory of C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build

04/26/2018  01:35 PM    <DIR>          .
04/26/2018  01:35 PM    <DIR>          ..
04/26/2018  01:34 PM                13 Microsoft.VCRedistVersion.default.txt
04/26/2018  01:34 PM               291 Microsoft.VCToolsVersion.default.props
04/26/2018  01:34 PM                13 Microsoft.VCToolsVersion.default.txt
04/26/2018  01:34 PM                39 vcvars32.bat
04/26/2018  01:34 PM                39 vcvars64.bat
04/26/2018  01:34 PM             9,187 vcvarsall.bat
04/26/2018  01:34 PM                43 vcvarsamd64_x86.bat
04/26/2018  01:34 PM                43 vcvarsx86_amd64.bat
               8 File(s)          9,668 bytes
               2 Dir(s)  31,976,964,096 bytes free

d:\sources>
```

This is the error:
```
     2>C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".
```

**Comment by solvingj** [comment]
And i immediately found this article after posting the comment: 
https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container

**Comment by solvingj** [comment]
Copied and pasted the dockerfile, replaced from with:
`FROM microsoft/windowsservercore-insider:10.0.17134.1`

Produces error on the `RUN C:\TEMP\vs_buildtools.exe` step:
`The token '||' is not a valid statement separator in this version.`

**Comment by heaths** [comment]
Can you copy/paste the exact error with formatting from the console output? A group does test a very similar Dockerfile with the insider builds and have not mentioned such an error.

Also make sure you have the back tick declared as the escape and that it's at the end of the line before `||`.

**Comment by loschorts** [comment]
@heaths can you please provide more instructions on how to run `collect.exe`? i am having the same problems as the OP but a reinstall of Docker did not solve the problem.

**Comment by heaths** [comment]
The updated Dockerfile examples show how to. You can also see https://aka.ms/vscollect for more information.
