### ISSUE TITLE
Common errors

### ISSUE THREAD

**Issue by galastiaos** [MicrosoftDocs/visualstudio-docs#8335]
I would like to see some common errors in VS (such as intellicode errors) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fc5c36c-d8ef-6b2d-2c62-5243d1ac2ce1
* Version Independent ID: 91c57e20-c75c-3c8d-e31f-727fa1e2af29
* Content: [Repair Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/repair-visual-studio?view=vs-2019)
* Content Source: [docs/install/repair-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/repair-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@galastiaos, thanks for your feedback. We will take your suggestion into consideration.

Meanwhile here are some resources: 
Intellicode errors are covered in the [troubleshoot ](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio#troubleshoot) section of the [Intellicode for Visual Studio overview](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio) doc.

Here are some other resources for Visual Studio related errors:
- Search for your error message in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/search?space=8). Other members of the community might have found a solution or workaround to your problem.
- [Known Issues section of our release notes](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#-known-issues).
- [Provide feedback or request a feature](https://docs.microsoft.com/en-us/visualstudio/intellicode/intellicode-visual-studio#provide-feedback).

Thanks again!
