### ISSUE TITLE
<Type Name="ATL::CStringT&lt;wchar_t,*&gt;">   <DisplayString>{m_pszData,su}</DisplayString>   <StringView>m_pszData,su</StringView> </Type>

### ISSUE THREAD

**Issue by kuhlmanjakob** [MicrosoftDocs/visualstudio-docs#8337]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e6335eb-8b73-9c11-2da7-4f397200ba0f
* Version Independent ID: af0eeed2-da17-ad14-98ce-0295afd5554b
* Content: [Create custom views of C++ objects - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/create-custom-views-of-native-objects?view=vs-2022)
* Content Source: [docs/debugger/create-custom-views-of-native-objects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/create-custom-views-of-native-objects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
