### ISSUE TITLE
Syntax highlighting/coloring not present in the code examples for T4 Text Templates

### ISSUE THREAD

**Issue by KirillBorunov** [MicrosoftDocs/visualstudio-docs#8340]
In the page there are no syntax highlighting (or coloring) in the code examples. Other pages about T4 Text Templates also suffer this problem, so I reporting the problem including all these pages also.
In the other Microsoft documentation pages always there is a syntax highlighting, why there is not?
I think it makes more difficult to understand the code for beginners.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc675b33-6811-66d4-608d-eaeb3255d908
* Version Independent ID: 0aa08402-9474-f803-0497-2919849ca6f4
* Content: [Writing a T4 Text Template - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/writing-a-t4-text-template?view=vs-2022)
* Content Source: [docs/modeling/writing-a-t4-text-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/writing-a-t4-text-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
Hi @KirillBorunov, the unfortunate reason for that is that T4 doesn't have any syntax highlighting in Visual Studio either. There is a Suggestion Ticket, but unfortunately it doesn't have many upvotes: https://developercommunity.visualstudio.com/t/provide-full-editoride-support-for-t4-template-tt/1114630

**Comment by WilliamAntonRohm** [comment]
@KirillBorunov -- Kirill, thank you for your feedback.

@mgoertz-msft -- Marco, thank you for clarifying.  I upvoted that ticket.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
