### ISSUE TITLE
Error language-locale translation on offline installation doc page

### ISSUE THREAD

**Issue by QyQj** [MicrosoftDocs/visualstudio-docs#8343]
It works well with English but when switch to  Chinese(Simplified),  the language-locale for English will be zh-CN

![English](https://user-images.githubusercontent.com/56919433/183623225-42702d47-7fcd-4ed2-bf24-c5c672ed0ece.PNG)
![Chinese(Simplified)](https://user-images.githubusercontent.com/56919433/183623249-eee90bdb-80c9-444d-a5df-dd906be034f6.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022#feedback)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@QyQj, thanks for your feedback and helping us improve our docs.
We've fixed the issue and the fix should be live later today.

Thanks!
