### ISSUE TITLE
The page references code style inference feature in IntelliCode which seems to have been removed from IntelliCode

### ISSUE THREAD

**Issue by freljung** [MicrosoftDocs/visualstudio-docs#8344]
Hello,

The page https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022#other-ways-to-add-an-editorconfig-file references code style inference in IntelliCode, but that feature seems to have been removed from IntelliCode. I found this commit: https://github.com/MicrosoftDocs/intellicode/commit/6cd2a1d174f265fd265fb86a02593b43091764e9 of the IntelliCode documentation where it was removed from the docs at least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [EditorConfig settings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by kjhf** [comment]
Interested in this.

According to https://learn.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022#other-ways-to-add-an-editorconfig-file 
"There are a couple of other ways you can add an EditorConfig file to your project:

The [code inference feature](https://learn.microsoft.com/en-us/visualstudio/intellicode/code-style-inference) of IntelliCode for Visual Studio infers your code styles from existing code. It then creates a non-empty EditorConfig file with your code-style preferences already defined."

and this feature was present in previous VS versions, see [IntelliCode](https://visualstudio.microsoft.com/services/intellicode/) "IntelliCode is installed by default with any workload that supports C#, C++, TypeScript/JavaScript, or XAML in Visual Studio 2022.", "which dynamically creates an .editorconfig file from your codebase to define coding styles and formats."

**Comment by ed-graham** [comment]
I too am interested in this.  Is there any way of getting the feature back or does the Microsoft Learn documentation have to be updated?
