### ISSUE TITLE
Please add the new MAUI workloads and components added in 17.3

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/visualstudio-docs#8349]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe411145-ff47-dfe5-1e57-db8d54671b58
* Version Independent ID: 4dac6d72-8c3c-dec8-d473-a2902e4e1fb9
* Content: [Visual Studio Professional workload and component IDs](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2022)
* Content Source: [docs/install/workload-component-id-vs-professional.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/workload-component-id-vs-professional.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@dotMorten, thanks for the feedback. We've already updated the page and the changes should be live later today. 
Thanks!
