### ISSUE TITLE
Suggested edit to Unit Tests Walkthrough Page

### ISSUE THREAD

**Issue by s52** [MicrosoftDocs/visualstudio-docs#8359]
This is a very clear page. One issue I have come across, and it is fairly minor, is the section starting :-

Fix your code and rerun your tests
The test result contains a message that describes the failure. 

The wording suggests that a message will be displayed describing the failure, but when I tried this in VS 2019 and VS 2022, the user in fact needs to click on the red circle and white cross three times before the Error Message column shows a message.

It would be good if the documentation could be amended to say :-

The test result contains a message that describes the failure. You may need to drill down to see this message.

This would help users new to unit testing, like myself.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b98c1d2a-1393-21d2-58c1-ff01d9aec0be
* Version Independent ID: e109ff12-0172-f3ee-c10d-2e2e8a7aa699
* Content: [C# unit test tutorial - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-managed-code?view=vs-2022)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/walkthrough-creating-and-running-unit-tests-for-managed-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@s52, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
