### ISSUE TITLE
Button no longer available for Developer tenant/license?

### ISSUE THREAD

**Issue by jotheman0303** [MicrosoftDocs/visualstudio-docs#8365]
I (and other colleagues as well) have noticed that the button for creating an (M365 E5 license based) tenant is no longer available. Is that a fault on our side on have things changed?
Additionally: It is still the case that there is no option to add that license to an existing tenant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [Microsoft 365 developer subscriptions in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-m365)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@jotheman0303 Thanks for reaching out.  Can you be a little more specific, please?  There's no button where, exactly?

**Comment by jotheman0303** [comment]
Sorry for the late reply!
The button to activate the M365 dev subscription is not visible for me and others I heard from. I mean this one:
![image](https://user-images.githubusercontent.com/34010893/185784279-ddeb1752-8d81-44c3-a040-89555cdf2b7b.png)

**Comment by evanwindom** [comment]
@jotheman0303 Thanks for getting back to me with the additional information.  
- What country are you in?
- What kind of subscription are you using?  (One thing that causes people to not see benefits is that they have multiple subscriptions available to them, and the wrong one is selected.  The most common scenario is that they have a Visual Studio subscription and a Dev Essentials membership.  You can select https://my.visualstudio.com/subscriptions to see what's assigned to your email address and choose the subscription you want to use.)

**Comment by jotheman0303** [comment]
- I am in the Netherlands
- I have a VS Enterprise subscription. I validated it just in case, but clicking/switching to the subscription in the list (where I see Ihave Essential and -Enterprise available) and seeing whether the tile appears after I did that, did not have any effect...
