### ISSUE TITLE
Required Extension

### ISSUE THREAD

**Issue by kennethGardzinskiatDuncanSolutions** [MicrosoftDocs/visualstudio-docs#8372]
I believe the page is also showing features that require the 'Easy Git Integration Tools'
Thats what the 'red diamond icon' is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce0fea4-c38c-4bef-8884-8f503c0c086d
* Version Independent ID: 1ce0fea4-c38c-4bef-8884-8f503c0c086d
* Content: [Create a Git repo - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/version-control/git-create-repository?view=vs-2022)
* Content Source: [docs/version-control/git-create-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-create-repository.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@kennethGardzinskiatDuncanSolutions -- Kenneth, thank you for your feedback.  We are investigating.

**Comment by TerryGLee** [comment]
@kennethGardzinskiatDuncanSolutions Thanks for your feedback. The page that you refer to, [Create a Git repository](https://docs.microsoft.com/en-us/visualstudio/version-control/git-create-repository?view=vs-2022), and the icons that are present in the screenshots on that page are from the [integrated Git tools](https://docs.microsoft.com/en-us/visualstudio/version-control/git-with-visual-studio?view=vs-2022) in **Visual Studio 2022**. 

This integrated set of Git tools became the default experience starting with Visual Studio 2019 [version 16.8](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-v16.8), and continues to the be default experience in Visual Studio 2022. In other words, prior versions of Visual Studio might benefit from the "[Easy Git Integration Tools](https://marketplace.visualstudio.com/items?itemName=jzoss.GitSourceControlProvider2015)" extension, but that extension's not necessary now.

We hope this additional information is helpful. Meanwhile, we'll close this issue now with our thanks to you for your continued interest in Microsoft products and services!
