### ISSUE TITLE
Student data

### ISSUE THREAD

**Issue by 8489153342k** [MicrosoftDocs/visualstudio-docs#8377]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7d9f53c-6ece-ea3c-9a51-9edd0efeebe3
* Version Independent ID: 9c927a8e-3ebd-0c8a-76cc-9b1c980b98a3
* Content: [Create projects & solutions - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/creating-solutions-and-projects?view=vs-2022)
* Content Source: [docs/ide/creating-solutions-and-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/creating-solutions-and-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@8489153342k, I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
