### ISSUE TITLE
Seems to re-download everything

### ISSUE THREAD

**Issue by nbwns** [MicrosoftDocs/visualstudio-docs#838]
Hi,
I've followed the commands to create a layout and then launch the installer but it seems it downloads again everything even if all the required packages have been downloaded already ! What a waste of time and bandwidth... :(

Nicolas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by nbwns** [comment]
Please ignore this comment, I think it's just downloading a couple of things that were not in the layout, it works fine after this initial download :)

**Comment by TerryGLee** [comment]
@nbwns Thanks for your follow-up; we're glad to hear that everything works fine now for you. :) 
We'll close this issue.
