### ISSUE TITLE
Datacamp benefit not available - Student Account

### ISSUE THREAD

**Issue by govinder001** [MicrosoftDocs/visualstudio-docs#8380]
[Enter feedback here]

Hi, I have just registered myself with the Microsoft Azure Student Account. However, I do not see the Datacamp benefit available anymore. Is it only for normal accounts? Or has the benefit/free subscription expired? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce19f95f-b1b3-98d0-76c1-ae7bd64e3b50
* Version Independent ID: f5615c72-044d-65c7-73f7-189cebcdf2c2
* Content: [Grow data science skills with DataCamp in Visual Studio subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/vs-datacamp)
* Content Source: [subscriptions/vs-datacamp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vs-datacamp.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@govinder001 Hello, and thank you for reaching out.  The Microsoft Azure Student Account isn't a part of Visual Studio subscriptions, so I can't provide reliable answers regarding its offerings.  If you're interested, there are short term training offerings available from Pluralsight and LinkedIn Learning through Visual Studio Dev Essentials.  This is a free program that offers access to a variety of tools and services.  You can learn more at https://visualstudio.microsoft.com/dev-essentials/.

**Comment by evanwindom** [comment]
#please-close
