### ISSUE TITLE
Printable Shortcuts Font Suggestions

### ISSUE THREAD

**Issue by MissyGH** [MicrosoftDocs/visualstudio-docs#8383]
On the printable keyboard shortcuts you have linked from this page, it would be great if you could make the descriptions for shortcuts as big as possible and bold so they can be read from farther away.   It would make the cheat sheet much more usable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 23332067-130b-a343-b902-7d09680d3519
* Version Independent ID: 09bb5d36-f067-5422-2ab2-e4c7a8f1d6ed
* Content: [Keyboard shortcuts - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/default-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/default-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TimShererWithAquent** [comment]
@MissyGH Thanks for your suggestion - We'll look into possible changes for the article.

**Comment by TerryGLee** [comment]
@MissyGH Initial investigatory efforts reveal that this might be difficult to do, based on the amount of information we want to include on the page. However, you might be able to manually adjust the size of the page when you print it; try searching for "how to adjust the size of a PDF to print" to see if there's a solution listed in the search results that could work for you.

We'll close this issue now, but we'll also log it in our internal queue to consider when we next update the printable page. And thanks again for the suggestion!

**Comment by MissyGH** [comment]
Thanks for considering it.  Just emboldening the type would make a difference and not change the line breaks.
