### ISSUE TITLE
Combination of switches give "Invalid project configuration" error

### ISSUE THREAD

**Issue by tzuhsun** [MicrosoftDocs/visualstudio-docs#839]
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.com" ..\AllProject.sln /project ProjectA /rebuild UnitTest /projectConfig UnitTest

Above line give errors below:

Microsoft Visual Studio 2017 Version 15.0.27428.2037.
Copyright (C) Microsoft Corp. All rights reserved.

Invalid project configuration

Use:
devenv  [solutionfile | projectfile | anyfile.ext]  [switches]
...

I am using VS Professional 2017 v15.6.2

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05945d0a-396b-0697-ab78-81d617b365c9
* Version Independent ID: 860cb1bf-47aa-b35d-4d30-be9f62796d40
* Content: [Visual Studio devenv command line switches - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/ide/reference/devenv-command-line-switches)
* Content Source: [docs/ide/reference/devenv-command-line-switches.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/reference/devenv-command-line-switches.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@tzuhsun I think you should be using devenv.exe instead of devenv.com.

**Comment by tzuhsun** [comment]
Hi @gewarren, even devenv.exe give same error, the different is the error message show in windows popup unlike the other show in console.

I found the root cause by read the message again, it says we need to include 'Platform' together with the setting name if there is multiple platforms, that solve my issue.

my batch file now become like this:
..\AllProjects.sln" /Rebuild "UnitTest|Win32" /Project ProjectA /ProjectConfig "UnitTest|Win32"

Need to enclose with double quote.

The message doesn't show in Microsoft Docs website, I think need to update in the web to make them more helpful.

-----
Part of messages picked out:
-----
...
Invalid project configuration

Use:
devenv  [solutionfile | projectfile | anyfile.ext]  [switches]

The first argument for devenv is usually a solution file or project file.
You can also use any other file as the first argument if you want to have the
file open automatically in an editor. When you enter a project file, the IDE
looks for an .sln file with the same base name as the project file in the
parent directory for the project file. If no such .sln file exists, then the
IDE looks for a single .sln file that references the project. If no such single
.sln file exists, then the IDE creates an unsaved solution with a default .sln
file name that has the same base name as the project file.

Command line builds:
devenv solutionfile.sln /build [ solutionconfig ] [ /project projectnameorfile [ /projectconfig name ] ]
Available command line switches:

/Build          Builds the solution or project with the specified solution
                configuration. For example "Debug". **If multiple platforms
                are possible, the configuration name must be enclosed in quotes
                and contain platform name. For example: "Debug|Win32"**.
/Clean          Deletes build outputs.
/Command        Starts the IDE and executes the command.
/Deploy         Builds and then deploys the specified build configuration.
/Edit           Opens the specified files in a running instance of this
                application. If there are no running instances, it will
                start a new instance with a simplified window layout.
/LCID           Sets the default language in the IDE for the UI.
/Log            Logs IDE activity to the specified file for troubleshooting.
/NoVSIP         Disables the VSIP developer's license key for VSIP testing.
/Out            Appends the build log to a specified file.
/Project        Specifies the project to build, clean, or deploy.
                Must be used with /Build, /Rebuild, /Clean, or /Deploy.
/ProjectConfig  Overrides the project configuration specified in the solution
                configuration. For example "Debug". **If multiple platforms are
                possible, the configuration name must be enclosed in quotes
                and contain platform name. For example: "Debug|Win32"**.
                Must be used with /Project.
...

Thanks,
tzuhsun

**Comment by gewarren** [comment]
@tzuhsun thank you for the info. I'm reopening the issue so i can track the work to update the topic with the info you provided. Thanks again!

**Comment by tzuhsun** [comment]
You are welcome 😄
