### ISSUE TITLE
Incorrectly nested launchSettings.json snippets

### ISSUE THREAD

**Issue by mccreah** [MicrosoftDocs/visualstudio-docs#8398]
Most launchSettings.json snippets are wrongly nested:

For example

```
{
    "profiles": {
      "test2": {
        "commandName": "DockerCompose",
        "composeLaunchServiceName": "webapplication1",
        "serviceActions": {
          "external1": "DoNotStart",
          "external2": "DoNotStart",
          "webapplication1": "StartDebugging",
          "webapplication2": "StartWithoutDebugging",
          "webapplication3": "DoNotStart"
        },
        "composeLaunchAction": "LaunchBrowser",
        "commandVersion": "1.0",
        "composeLaunchUrl": "{Scheme}://localhost:{ServicePort}"
      }
   }
}
```
it should be like this

```
{
    "profiles": {
      "test2": {
        "commandName": "DockerCompose",
        "composeLaunchServiceName": "webapplication1",
        "composeLaunchAction": "LaunchBrowser",
        "commandVersion": "1.0",
        "composeLaunchUrl": "{Scheme}://localhost:{ServicePort}",
        "serviceActions": {
          "external1": "DoNotStart",
          "external2": "DoNotStart",
          "webapplication1": "StartDebugging",
          "webapplication2": "StartWithoutDebugging",
          "webapplication3": "DoNotStart"
        }
      }
   }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a32e14-63ef-6da2-c2a6-eeaec1856c8f
* Version Independent ID: 8382f7bf-9618-aee5-5b24-8bfa97aa4a31
* Content: [Launch a subset of Docker Compose services - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/containers/launch-profiles?view=vs-2022)
* Content Source: [docs/containers/launch-profiles.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/launch-profiles.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@mccreah 
Aren't those equivalent structures?  These are generated by Visual Studio, so they might not match how a human would write it, but I think they're equally valid.

**Comment by mccreah** [comment]
I don't think so, if you place them outside the exact profile they get underlined as wrong syntax.

**Comment by ghogen** [comment]
The only difference there is the ordering, so I believe this syntax is equivalent and since it's generated by Visual Studio, it makes sense to leave it as it is.
