### ISSUE TITLE
Slight improvement

### ISSUE THREAD

**Issue by FrankLefeber** [MicrosoftDocs/visualstudio-docs#8409]
Thanks for the tutorial, it is really helpful. There is one thing to improve though. Since there is no check for the second click, you can reveal more than two icons and some of them will remain revealed.
So in the click function we need to add:
`if(secondClicked == null)`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e7af439-071e-44be-fd2f-bfedc028d48f
* Version Independent ID: 0e7af439-071e-44be-fd2f-bfedc028d48f
* Content: [Tutorial: Add a timer to your matching game - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-match-game-labels?view=vs-2022&tabs=csharp)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-match-game-labels.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-match-game-labels.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@anandmeg -- Megha, please review this change in [private PR 10380](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10380).

**Comment by anandmeg** [comment]
@FrankLefeber, thanks for your feedback.
I'm unable to repro the behavior where you can reveal more than two icons. There are two 2 click variables and they are set to null every time.

This article ([Tutorial: Add a timer to your matching game - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-match-game-labels?view=vs-2022&tabs=csharp)) is part 3 in a 4-part tutorial series (Create a matching game). Let us know if you run into this issue after running through all the parts of this tutorial series.

Thanks again!
