### ISSUE TITLE
Default Values would be helpful

### ISSUE THREAD

**Issue by louiskody** [MicrosoftDocs/visualstudio-docs#841]
It would be great if the default value for each property was given. This can help devs who have tried various options but want to revert back to a default configuration. (For all the settings/options too).  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c524aa1d-eec4-d776-8346-dfdc632eec76
* Version Independent ID: c0f65c4f-6369-10ce-5edc-0ab5fbae736a
* Content: [General, Debugging, Options Dialog Box - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/debugger/general-debugging-options-dialog-box?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(VS.ToolsOptionsPages.Debugger.General)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%3Bk(DevLang-typescript)%26rd%3Dtrue)
* Content Source: [docs/debugger/general-debugging-options-dialog-box.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/debugger/general-debugging-options-dialog-box.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@louiskody Thanks for the feedback. That's a good idea. At times, the defaults change between VS versions, so the information could get out of date. You can reset your settings using Tools > Import and Export Settings. You can only limit the reset to debugger settings, however, if you save the current settings before you make changes (via the same Tools > Import and Export Settings option). It might be helpful for us to mention these options in these pages.

**Comment by Mikejo5000** [comment]
Adding the preceding info to the topic.
