### ISSUE TITLE
DPI Awareness settings do not work

### ISSUE THREAD

**Issue by PX03AFK** [MicrosoftDocs/visualstudio-docs#8410]
None of the settings described in this article work for VS 2022 c++.  I have tried every combination and still my form opens with controls the wrong size and overlapped.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness for scaling in forms - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2022)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by PX03AFK** [comment]
Since posting this I did some more digging and suddenly found that the font set for the dialog was not installed on my machine.  The source had come from another system which did have this font installed and I do not believe I had any indication that the font wasn't there.  At least now the form looks better, still not exactly the same as my other system .

**Comment by WilliamAntonRohm** [comment]
@PX03AFK -- David, thank you for your feedback, and glad to see you've found a solution.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by PX03AFK** [comment]
Whilst what I found may have improved things for me there are still areas which are definitely not fixed:
1.  Why was there no warning that the font wasn't on the machine
2. Why does the dialog appear differently on a High DPI screen
3. Why do none of the settings suggested for making a dialog look the same on a High DPI screen not work

**Comment by PX03AFK** [comment]
How does one re-open a closed case?

**Comment by WilliamAntonRohm** [comment]
@PX03AFK -- David, thank you for your follow-up.  This repo is solely for documentation issues, and this is product-related.  Please add your concerns here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​
