### ISSUE TITLE
I can't report a problem, because the problem is with the report a problem!

### ISSUE THREAD

**Issue by dazinator** [MicrosoftDocs/visualstudio-docs#842]
I wanted to report a problem with VS.

Everywhere I go to do this, it directs me to report the problem via the feedback tool. This seems to be the only mechanism.

However the problem is with the feedback tool itself - it isn't working.

So how do I report a problem with that?

Here is the problem. When I open the feedback tool I see this:

![image](https://user-images.githubusercontent.com/3176632/39084815-71b76af2-4572-11e8-8f00-6d2878d2a9ac.png)

If I click on "let us know" I see this:

![image](https://user-images.githubusercontent.com/3176632/39084827-86f2e7de-4572-11e8-9587-d8c23408d19a.png)

So now what?

**Comment by TerryGLee** [comment]
@dazinator Thanks for your feedback. Are you still experiencing this problem with signing in to the [Visual Studio developer community](https://developercommunity.visualstudio.com/)? We'd like to verify that this isn't a temporary glitch.

**Comment by dazinator** [comment]
Yeah still experience this issue.
On my windows 10 machine I sign in with a non admin (standard) user account. The problem then seems to occur if I Run VS as Administrator.

I opened two instances of vs2017 community side by side to test this, only difference was one was run as administrator. The one running as admin I could not sign with for the feedback tool. Same thing effects the installer.

**Comment by mariaghiondea** [comment]
@dazinator Please visit https://www.visualstudio.com/subscriptions/support/ and select “Account, Subscription & Billing Support” under the “Contact Us!” heading. Follow the prompts that will connect you to a support agent who can help troubleshoot this issue with your account. You can set Issue to “Subscription sign in support” for issues signing into the product
Your second issue is similar to https://developercommunity.visualstudio.com/content/problem/232328/visual-studio-installer-feedback-sign-in-let-us-kn.html. We are replacing this part of the UI in the future.
