### ISSUE TITLE
Incorrect note about editorconfig settings not supported in CI/CD

### ISSUE THREAD

**Issue by mavasani** [MicrosoftDocs/visualstudio-docs#8426]
This is no longer true for C#/VB:
![AC606DA0-9E51-4452-9CD1-BC6FA638BFC5](https://user-images.githubusercontent.com/10605811/188041993-7bbea555-25ee-4b2a-9ad9-56ed7a287de1.png)

See https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview#code-style-analysis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f45eb4-3596-866a-2c16-ee225737d956
* Version Independent ID: cea055e7-fe9b-95c7-6d25-086f182c01d2
* Content: [EditorConfig settings - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2022)
* Content Source: [docs/ide/create-portable-custom-editor-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/create-portable-custom-editor-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@mavasani -- Manish, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
