### ISSUE TITLE
MSBuild UsingTask Runtime="NET"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#8436]
<https://github.com/dotnet/msbuild/pull/6994> added support for `Runtime="NET"` in the MSBuild `UsingTask` element. That was released in MSBuild v17.1.0 and should be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b3f5bf-9736-884e-9d08-e9422b4891a5
* Version Independent ID: fa34a483-01a9-8062-ac26-a0c8de0821b5
* Content: [UsingTask Element (MSBuild) - MSBuild](https://docs.microsoft.com/en-us/visualstudio/msbuild/usingtask-element-msbuild?view=vs-2022)
* Content Source: [docs/msbuild/usingtask-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/usingtask-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by rainersigwald** [comment]
We should also be clear that you can't call NET tasks from a .NET framework (CLR4) MSBuild, and you can't call CLR2/CLR4 tasks from a .NET MSBuild (`dotnet build`).

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- thank you for your question.  It takes up to a day to propagate to the live site.
