### ISSUE TITLE
Updating the Visual Studio version for feature "IEnumerable visualizer" as its now released 

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [MicrosoftDocs/visualstudio-docs#8439]
At the top it still talks about Preview versions of Visual Studio where this feature is now released as per release notes at [isual-studio-2022-version-17.3](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1730--visual-studio-2022-version-173)
> Starting in Visual Studio 2022 Update 2 Preview 1, you can view IEnumerable collections in a tabular view.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3d09500-3313-0e42-30d9-4ca6fe59add2
* Version Independent ID: d3d09500-3313-0e42-30d9-4ca6fe59add2
* Content: [View .NET collections with the IEnumerable visualizer - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/view-data-in-ienumerable-visualizer?view=vs-2022)
* Content Source: [docs/debugger/view-data-in-ienumerable-visualizer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/view-data-in-ienumerable-visualizer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Update will be live by end of day today, 12/19/22
