### ISSUE TITLE
EF Power Tools for VS 2015

### ISSUE THREAD

**Issue by IrishChieftain** [MicrosoftDocs/visualstudio-docs#844]
Following Julie Lehrman's EF6 tutorial and her blog on installing EF Power Tools in VS 2015:

http://thedatafarm.com/data-access/installing-ef-power-tools-into-vs2015/

She says to update the version of VS in the SupportedProducts section. However, when I downloaded the exteension and followed the steps I saw that there is no Such section in the extension.vsixmanifet file anymore. Then I saw this article on how the syntax has been since changed:

https://blogs.msdn.microsoft.com/visualstudio/2013/08/08/update-for-extension-authors-vsix-manifest-version-range-attribute/

I cannot understand the above article. Can someone help me with the syntax to change to VS 2015 Enterprise?

<InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[11.0,16.0)" />

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55af1eb8-318c-fac9-410d-550b74425218
* Version Independent ID: 5b62e93a-9d46-6cde-9293-9c775ae61816
* Content: [VSIX Extension Schema 2.0 Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference)
* Content Source: [docs/extensibility/vsix-extension-schema-2-0-reference.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/vsix-extension-schema-2-0-reference.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gewarren** [comment]
@IrishChieftain Anthony,

Julie links to a VSIX where she already made the modifications. You can grab it here http://1drv.ms/1IkWSkR.

The SupportedProducts element was deprecated in VS2017. Since, VS2012, you have been able to specify an InstallationTarget instead like this:

<Installation>
  <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0, 16.0)" />
</Installation>

Does this help?

**Comment by gewarren** [comment]
@IrishChieftain awesome! Closing the issue then.
