### ISSUE TITLE
Missing import of Microsoft.CSharp.targets

### ISSUE THREAD

**Issue by NightProgramming** [MicrosoftDocs/visualstudio-docs#8440]
I created a new .NET 6 C# consple project with Visual Studio 17.3. [Here](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process?view=vs-2022&tabs=csharp#import-the-text-transformation-targets) it says to find a line like `<Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />` in .csproj file. There is no such line in .csproj though. Adding it manually results in:

```
C:\Program Files\dotnet\sdk\6.0.400\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(37,3): warning MSB4011: "C:\Program Files\do
tnet\sdk\6.0.400\Microsoft.CSharp.targets" cannot be imported again. It was already imported at "C:\Users\MyUser\Deskt
op\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj (10,2)". This is most likely a build authoring error. This subsequent imp
ort will be ignored.
```

```
C:\Program Files\dotnet\sdk\6.0.400\Microsoft.Common.CurrentVersion.targets(823,5): error : The BaseOutputPath/OutputPa
th property is not set for project 'ConsoleApp1.csproj'.  Please check to make sure that you have specified a valid com
bination of Configuration and Platform for this project.  Configuration='Debug'  Platform='AnyCPU'.  You may be seeing
this message because you are trying to build a project without a solution file, and have specified a non-default Config
uration or Platform that doesn't exist for this project. [C:\Users\MyUser\Desktop\ConsoleApp1\ConsoleApp1\ConsoleApp1.
csproj]

```

I tried both `dotnet build` and `msbuild` commands.

BTW, [here](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process?view=vs-2022&tabs=csharp#buildserver) VS 2019 paths (%ProgramFiles(x86)%\Microsoft Visual Studio\2019...) are mentioned. But on the upper left corner under "Version" it says "Visual Studio 2022".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca46de41-5103-a318-3553-3bf05c59751b
* Version Independent ID: 27b60762-dfe8-9320-c891-164e2f0ca980
* Content: [Code Generation in a Build Process - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-in-a-build-process?view=vs-2022&tabs=csharp)
* Content Source: [docs/modeling/code-generation-in-a-build-process.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/code-generation-in-a-build-process.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by WilliamAntonRohm** [comment]
@NightProgramming -- thank you for your detailed feedback.  I am investigating.

**Comment by NightProgramming** [comment]
@WilliamAntonRohm Thank you. I think the solution might be to just remove the whole ` find a line like this` section from the docs because

1. the import line isn't there by default in a .csproj in the first place.
2. It seems to work without explicitly importing `Microsoft.CSharp.targets` anyway, probably because the SDK imports it by default? I guess it does so because when importing it explicitly in my .csproj I get the `It was already imported at` warning.

**Comment by WilliamAntonRohm** [comment]
@mgoertz-msft -- Marco, please review this update in [private PR 10421](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10421).
