### ISSUE TITLE
bookmarks are losted after checkout branch when working on a project compiled by cmake

### ISSUE THREAD

**Issue by fszr** [MicrosoftDocs/visualstudio-docs#8442]
[Enter feedback here]
I am working o a project compiled by cmake, after checkout to another branch and then back
visual studio 2022 can not display bookmarks, and .suo file exists in corresponding .vs folder 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac5a1c94-4cd3-3519-d437-491b4c19c9fb
* Version Independent ID: 807d3d11-fd62-b359-e0c7-06033ba252cf
* Content: [Set code bookmarks - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/setting-bookmarks-in-code?view=vs-2022)
* Content Source: [docs/ide/setting-bookmarks-in-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/setting-bookmarks-in-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@fszr -- thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
