### ISSUE TITLE
Neither of suggested ways to report a problem works

### ISSUE THREAD

**Issue by BSarmady** [MicrosoftDocs/visualstudio-docs#8443]
It has been about 6 years that I keep telling you in certain conditions Report feedback doesn't work. And microsoft people still insist that this is the best way to report problems. and nobody had issue sending issues this way. The problems with reports this way have issue cannot sending it this way and since it doesn't work they cannot send their issues!

As usual I was trying to install vs 2022 in same PC that Installed 2017 and 2019 previously and had the same issue and same issue is happening again. which installer refuses to install anything and feedback tool doesn't work either!

An offline installation fails and obviously Report a problem will also fail since that tool cannot magically gain access to internet.

I run the installer on a PC that has access to Internet and it runs fine and I can see the UI and click on report a problem!
Clicking on Report a problem in Visual Studio installer opens a command prompt and an error message with a link (trimmed with ... at the end) that says application not found!

![Capture](https://user-images.githubusercontent.com/2040435/189039607-91bd426f-0f27-4b39-851d-d82bbef1103d.PNG)

if your only reason for wanting people to use report from installer is that you need the diagnostics and logs why don't you create an app that collects this information and then ask users to attach it for you? Is there anything in the logs that you are sending to yourself and don't want users to know? 

I'm so annoyed that I cannot leave feedback in the community feedback and every time I get an issue either you are asking me to send it via our enterprise admin or totally ignoring it by closing the issue because it is not related to documentation.

Would you tell me how can I reach MS people who are responsible developing this installer if I cannot reach them in anyway?

BTW for previous installations I had to carry 3 PCs to different floor in our office and connect them to internet to be able to install visual studio (separately) and wasn't able to use offline installer repo at all! I am using microsoft products since 1996 and have never seen so much annoyance that I have seen since 2015.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [Report a problem with Visual Studio - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by BSarmady** [comment]
Oh BTW, The button under Feedback -> Submit and view feedback for "This Product" doesn't work either, after sending me trough sign in process, it doesn't log me into feedback website and even after I manually sign in to page, I cannot do anything other than reading other people's feedback on **Developer Community - Your open channel to Microsoft engineering teams**

**Comment by WilliamAntonRohm** [comment]
@BSarmady -- Bob, thank you for your considered feedback.  That does sound difficult.  Please try this direct link:
- [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

Let me know if can report your problem there.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by BSarmady** [comment]
@WilliamAntonRohm I would love to know how.

I can't see any button allowing me to add feedback in your mentioned website.

![Capture](https://user-images.githubusercontent.com/2040435/191146613-536954c5-a505-41a8-876b-e4e96b247f7e.PNG)
![Capture1](https://user-images.githubusercontent.com/2040435/191146960-6e898565-38e5-446d-9771-c549f2bec9fa.PNG)

**Comment by WilliamAntonRohm** [comment]
@BSarmady -- Bob, thank you for your follow-up.  Please try these two links on the lower left of that screen:
- `> Report a problem`
- `> Request a feature`

You are also welcome to email us at directly at [vsfeedback@microsoft.com](mailto:vsfeedback@microsoft.com).

**Comment by BSarmady** [comment]
Thank you for following up, but "Report a problem" doesn't have any form to actually report a problem.

Since my issue is a bug Filling Request a feature will not work (as they immediately delete it and mark it as "Inappropriate comment removed for violating the Microsoft Community Code of Conduct." which is humiliating too!

![Capture3](https://user-images.githubusercontent.com/2040435/192179380-ec146093-3b1c-4b92-a610-368fad99576f.PNG)

**Comment by WilliamAntonRohm** [comment]
@BSarmady -- Bob, thank you for clarifying.  I have no idea why this straightforward issue would be deemed "inappropriate".

Please try this e-mail:
- [vsfeedback@microsoft.com](mailto:vsfeedback@microsoft.com)
