### ISSUE TITLE
And then what?

### ISSUE THREAD

**Issue by TangoSensory** [MicrosoftDocs/visualstudio-docs#845]
What a useless document

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39d90aa3-99ab-1506-a311-5f79362abc3a
* Version Independent ID: 590e6716-7694-6082-9575-2ec262427acf
* Content: [How to: Create an Atom Feed for a Private Gallery - Visual Studio](https://docs.microsoft.com/en-gb/visualstudio/extensibility/how-to-create-an-atom-feed-for-a-private-gallery#feedback)
* Content Source: [docs/extensibility/how-to-create-an-atom-feed-for-a-private-gallery.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/how-to-create-an-atom-feed-for-a-private-gallery.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Sorry that you were disappointed by the documentation. Have a look at the general Private Gallery topic https://docs.microsoft.com/en-gb/visualstudio/extensibility/private-galleries for more context.
