### ISSUE TITLE
Step 3 of Create the Backend App references a new solution name, but we already are adding it to an existing solution

### ISSUE THREAD

**Issue by pb-413** [MicrosoftDocs/visualstudio-docs#8452]
re https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022#create-the-backend-app

Step 3 of 'Create the backend app' starts by saying "Give your project and solution a name." 

At this stage in the tutorial, we are adding a new project to our existing solution, and we don't need to specify a solution name. 

Specifying the project name and location are the only options of the "Configure your project" step/screen. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review this update in [private PR 10423](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10423).
