### ISSUE TITLE
The section on how to disable JIT debug could be clearer.

### ISSUE THREAD

**Issue by chendrixson** [MicrosoftDocs/visualstudio-docs#8457]
The "Disable Just-In-Time debugging from the Windows registry" should be changed to just say, "Delete the following keys if they exist on your machine", and list out all the reg entries.  A customer was confused from this because the 3. section says "if key exists or you're running 32bit", but both he and I saw 32bit and skipped reading that bullet.  Fact is most people need to delete all these keys since they're running 64 bit machines, and debugging both 32 and 64 bit code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 975e5ca6-98b1-0e2e-1c57-364fe1e13337
* Version Independent ID: 1b18b1df-023b-3c13-f95e-e0166ee7f704
* Content: [Debug using the Just-In-Time Debugger - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/debugger/debug-using-the-just-in-time-debugger?view=vs-2022)
* Content Source: [docs/debugger/debug-using-the-just-in-time-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/debug-using-the-just-in-time-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- Mike, please review this update in [private PR 10422](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10422).
