### ISSUE TITLE
Support  creating VSIX with WinForms Toolbox Controls targeting .NET 4.0

### ISSUE THREAD

**Issue by Misiu** [MicrosoftDocs/visualstudio-docs#846]
When following steps from this guide:
https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/extensibility/creating-a-windows-forms-toolbox-control.md I was able to create VSIX with user control that targets .NET 4.5 (this framework version is default when creating new project).
As soon as I set target framework to 4.0 I can't add new controls using Add >New Item > Extensibility.

![snap 2018-04-06 at 13 58 02](https://user-images.githubusercontent.com/1741838/39129248-4e0042fc-470a-11e8-98fa-ea6c369e6464.png)

How can I create VSIX that will contain Controls that target .NET 4.0? IS this possible in Visual Studio 2017?

I've created similar issue here: https://github.com/Microsoft/VSSDK-Extensibility-Samples/issues/127

**Comment by Misiu** [comment]
@gregvanl any news about this?
I've tried creating `ProvideToolboxControl ` manually and adding it to my UserControll class but that didn't work.
Ideally after changing target to .NET 4.0 WinForms Toolbox Control should be available in Add New Item menu.

**Comment by Misiu** [comment]
@gregvanl any news on this?

**Comment by gregvanl** [comment]
Hi @Misiu Unfortunately the product team says the Extensibility project templates required 4.5.
