### ISSUE TITLE
Unable to get this working

### ISSUE THREAD

**Issue by geoffnormanconsulting** [MicrosoftDocs/visualstudio-docs#8460]
Hi,

I have followed the walkthrough instructions on this page, and successfully got to the point where I "Click Finish" to create a new project in VS2022.

I then get the following in VS2022:
- Solution Explorer:    Solution 'CallingCodeFromVBA' (0 projects).  
                                   Nothing else appears in the Solution Explorer.
- Background tasks:    Indexing files CallingCodeFromVBA is continually running in the background.

Much appreciated if this issue can be resolved.

Regards, Geoff

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fb5616f-d7aa-e79f-7068-2ac6d00a6bc9
* Version Independent ID: c5598dc6-1b8c-586c-c7f1-74ce650f54cb
* Content: [Walkthrough: Call code from VBA in a Visual Basic project](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-calling-code-from-vba-in-a-visual-basic-project?view=vs-2022)
* Content Source: [docs/vsto/walkthrough-calling-code-from-vba-in-a-visual-basic-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/walkthrough-calling-code-from-vba-in-a-visual-basic-project.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by geoffnormanconsulting** [comment]
PS.  I have tried the same procedure with an Excel file and got exactly the same result.

**Comment by John-Hart** [comment]
@geoffnormanconsulting  can you please provide feedback through Visual Studio for this issue?  You can do that by accessing the  Help > Send Feedback > Report a Problem in Visual Studio
