### ISSUE TITLE
Why does switching environments have to be so difficult know?  I just want to apply a different version to a script and you want to update and install for the whole folder.  Ridiculous.

### ISSUE THREAD

**Issue by mgarard** [MicrosoftDocs/visualstudio-docs#8465]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3330f57-6530-be0c-ce7d-a2ffb37891c9
* Version Independent ID: 38575887-8943-74fa-22b9-d4e53fddb496
* Content: [Choose a Python environment - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/python/selecting-a-python-environment-for-a-project?source=recommendations&view=vs-2022)
* Content Source: [docs/python/selecting-a-python-environment-for-a-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/selecting-a-python-environment-for-a-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @rjmolyneaux
* Microsoft Alias: **rmolyneaux**

**Comment by WilliamAntonRohm** [comment]
@mgarard -- Marc, thank you for your feedback.  Please add it here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
