### ISSUE TITLE
LoadStdProfileSettings is NOT defined in  VISUAL STUDIO 2017. 

### ISSUE THREAD

**Issue by ingconti** [MicrosoftDocs/visualstudio-docs#847]
try to use an MFC app from Vs 2017: You got:

Error (active)	E0020	identifier "LoadStdProfileSettings" is undefined.

**Comment by corob-msft** [comment]
@ingconti First things first: Have you installed MFC/ATL support in your copy of Visual Studio? If not, I'd expect other errors well before this one, and squiggles under all kinds of things, but it's the first place to start. Run the VS installer, choose the **Modify** button for your installation, choose the **Individual components** tab, scroll down to the **SDKs, libraries, and frameworks** section and verify that **MFC and ATL support (x86 and x64)** is checked. If not, check it and press **Modify** and see if that doesn't fix your issue.

If that's not the problem, then verify that you've got the right headers in your source file. Normally the MFC headers are included by the precompiled header, stdafx.h, so open that file and verify that afxwin.h is included there. You should also verify that your source file includes stdafx.h before anything else, especially before any other **#define** or **#include** statement. I'd also expect squiggles galore if this were the case, but you never know.

One last thing to check; you need to call **LoadStdProfileSettings** from within a member function of your App class (that is, usually the main class for your app, the one that's derived from 
**CWinAppEx**), preferably in its **InitInstance** member function. It won't be visible outside your app class, unless you've overridden it and made it **public** (it's **protected** by default).

**Comment by corob-msft** [comment]
@ingconti Why is LoadStdProfileSettings commented out in your headers? I created a new MFC app with the wizard, and it calls LoadStdProfileSettings in the main app class' InitInstance member function. If I put the cursor on the call to LoadStdProfileSettings and press F12, it takes me to the declaration in afxwin.h on line 5207, where it definitely is not commented out. If it's commented out for you, then I wonder if the right symbols are defined for the preprocessor. As far as I can tell, that part of the file is only commented out if either RC_INVOKED or the include guard, __AFXWIN_H__, is defined. Neither should be the case in your source code. Is _AFXDLL defined? WIN32? WINDOWS? UNICODE?

**Comment by ingconti** [comment]
I will delete and reinstall from scratch.
Also for me is strange, i never touch MS files.

**Comment by corob-msft** [comment]
Closing this, because it's not a documentation issue. For product issues, we recommend the Feedback control at the upper right in the Visual Studio IDE.

**Comment by ingconti** [comment]
ok
