### ISSUE TITLE
Please document that /Tests parameter matches not just test name, but rather it's complete name (including the namespace and class name)

### ISSUE THREAD

**Issue by ayeltsov** [MicrosoftDocs/visualstudio-docs#8476]
We spent half a day troubleshooting why /Tests:Blah executes all tests in the assembly, not just that one.

```
vstest.console.exe MyTests.dll /Tests:Blah
Microsoft (R) Test Execution Command Line Tool Version 17.3.0-preview-20220626-01 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test discovery, please wait...
A total of 1 test files matched the specified pattern.
  Passed Abc [16 ms]   <-- unexpected
  Passed Blah [16 ms]  
  Passed Xyz [< 1 ms] <-- unexpected
  
```

It turns out that matching is done over complete test name, including it's namespace.
Our tests were in something like
```
namespace Tests.Blah {
    [TestClass]
    public class MyTestClass
    {
        [TestMethod]
        public void MyTestMethod()
	}
	<...>
}
```
Since Blah is substring of full test name Tests.Blah.MyTestClass.MyTestMethod, this automatically opted in all the tests in the assembly. 

This was hard to discover because output of vstest.console.exe does not show full namespace.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e27af73d-196c-4653-aa07-acf7e8b425e3
* Version Independent ID: b8957d80-ffa0-1c42-d3f0-6e4d00bf7a1e
* Content: [VSTest.Console.exe command-line options - Visual Studio (Windows)](https://docs.microsoft.com/en-us/visualstudio/test/vstest-console-options?view=vs-2022)
* Content Source: [docs/test/vstest-console-options.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/vstest-console-options.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AbhitejJohn Abhitej, It seems to make sense to add a note to the effect that the command matches on the full test name. I'll open a PR, but let me know if you think otherwise (or if this is a bug).

**Comment by Mikejo5000** [comment]
@ayeltsov Thanks for the suggestion! I'll make an update that should go live by the end of the day.
