### ISSUE TITLE
Visual Studio .NET

### ISSUE THREAD

**Issue by feliciousity** [MicrosoftDocs/visualstudio-docs#8486]
[.NET Framework]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 096c3d10-b2c8-92a8-aac3-172be5a7a7c1
* Version Independent ID: b6a30164-f1f4-02d1-c49e-63322d737b67
* Content: [Signing in to Visual Studio for Mac - Visual Studio for Mac](https://learn.microsoft.com/en-us/visualstudio/mac/signing-in?view=vsmac-2022)
* Content Source: [mac/signing-in.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/signing-in.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
Hello again Felicia!

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
