### ISSUE TITLE
Looking for command line installation option for 64 bit

### ISSUE THREAD

**Issue by AaronValor** [MicrosoftDocs/visualstudio-docs#849]
Command line installation defaults to 32 bit.
Is there an option for 64 bit?

**Comment by gewarren** [comment]
@TerryGLee can you take this one?

**Comment by TerryGLee** [comment]
@AaronValor Thanks for your feedback. We'll investigate and report back.

**Comment by artl93** [comment]
@AaronValor  - what do you mean by it defaulting to 32-bit? Visual Studio is a 32-bit application for all Windows platforms. Are you seeing 64-bit components missing in some cases (e.g. 64-bit ETW collectors or debugging?)

**Comment by TerryGLee** [comment]
@AaronValor We haven't heard back from you re: @artl93's inquiry; we'll close this for now but if you do have further information for us, please feel free to add it later or open a new GitHub Issue. 

Thanks,
~ Terry

**Comment by AaronValor** [comment]
This was a mistake in my understanding.  I thought there was a 64-bit version of visual studio.
