### ISSUE TITLE
Duplicated Entity Exception

### ISSUE THREAD

**Issue by rogerms** [MicrosoftDocs/visualstudio-docs#8500]
I followed all the instructions on this page but when I added the UWP Project reference into the Test Project I couldn't run the tests anymore.
I got the "Duplicated Entity" error message.
I fixed that by excluding the Assets folder and Properties\Default.rd.xml file from the Test Project.
I wished this page had included those pieces of information. It would have saved me some hours. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 06ad1796-f0fa-b93d-f885-542e7e50e3d2
* Version Independent ID: bacdf7a8-a577-bd17-769c-46397b5850b5
* Content: [Create and run unit tests for Universal Windows Platform (UWP) apps - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps?view=vs-2022)
* Content Source: [docs/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/walkthrough-creating-and-running-unit-tests-for-windows-store-apps.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Mikejo5000 -- please see the previous comment.

**Comment by Mikejo5000** [comment]
Updating article. Should be live by end of day today.
