### ISSUE TITLE
File nesting no longer only available for ASP.NET Core projects.

### ISSUE THREAD

**Issue by MacShack** [MicrosoftDocs/visualstudio-docs#8501]
After the first paragraph it has a note which states:

> The feature is currently only supported for ASP.NET Core projects.

But since Visual Studio 17.3 this is no longer the case. As now all CPS Based projects support this feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by WilliamAntonRohm** [comment]
@AngelosP -- Angelos, please review this update in [private PR 10475](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10475).
