### ISSUE TITLE
Missing explanation

### ISSUE THREAD

**Issue by ktb8n** [MicrosoftDocs/visualstudio-docs#8507]
1. The refactored application returns/displays the calculated value with this {0:0.##\n}  The tutorial never explains what is happening here, and I can't google my way into understanding it either.
2. FAWNING APPRECIATION: I REALLY appreciate these tutorials, so pls do not take this suggestion as anything other than trying to learn the language as best I can. TY.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Version Independent ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Content: [Tutorial: Create a simple C# console app  - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@ktb8n -- Katie, thank you for your kind feedback.  That expression is an example of composite formatting, as described here:
- [Composite formatting](https://learn.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting)

So for
- `else Console.WriteLine("Your result: {0:0.##}\n", result);`

In this case in `{0:0.##\n}`, the initial zero indicates that it will be replaced by the value of the first item in the list following the comma, namely `result`.  The colon separates that index from the format specification itself.  `0.##` means "always have a leading single digit (even if it's zero), then a literal period (decimal point), and two digits of precision, where the octothorpes are replaced by the digits in the incoming numeric value".  The `\n` says to add a linefeed after the whole value, which makes the next `WriteLine` start at the beginning of the subsequent line.  Seems pretty intuitive :^)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
