### ISSUE TITLE
Adding unit test to project

### ISSUE THREAD

**Issue by malchera** [MicrosoftDocs/visualstudio-docs#851]
I want to add a unit test file to a Win32 Console Application (same project), as described in this document ("Right-click on the project node in Solution Explorer and choose Add | New Item | C++ Unit Test.").
Unfortunately, the "Add New Item" dialog does not provide any template for C++ Unit Tests. Am I missing something? My version is VS2015 Professional.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c83cfa6a-8be4-e7b5-bf06-9f70023aaa65
* Version Independent ID: 92877cae-f39e-6653-ce1e-233f75988ba0
* Content: [Use the Microsoft Unit Testing Framework for C++ in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp)
* Content Source: [docs/test/how-to-use-microsoft-test-framework-for-cpp.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/how-to-use-microsoft-test-framework-for-cpp.md)
* Service: **unspecified**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by mikeblome** [comment]
@malchera. Sorry for the confusion. This feature was introduced in Visual Studio 2017.  This topic describes how to add a unit test project in VS 2015: https://msdn.microsoft.com/en-us/library/hh598957.aspx.

**Comment by ClaudeZhao** [comment]
I think this part document is not correct. I use latest VS2017 Professional (15.9.2), only Google Test and Boost Test exist when **Add | New Item**.

Here is a workaround if you need add project internal unit test:
1) Add $(VCInstallDir)Auxiliary\VS\UnitTest\include to Include Directories to target project;
2) Add $(VCInstallDir)Auxiliary\VS\UnitTest\lib to Library Directories to target project;
3) Create a new cpp file to target project;
4) Copy the below content to the new cpp file in step 3, and customize your own test code.
```
#include "stdafx.h"
#include "CppUnitTest.h"

using namespace Microsoft::VisualStudio::CppUnitTestFramework;

namespace UnitTest
{
    TEST_CLASS(UnitTestInternal)
    {
    public:

        TEST_METHOD(TestMethodInternal)
        {
            // TODO: Your test code here
        }

    };
}
```
