### ISSUE TITLE
Delete Python environment

### ISSUE THREAD

**Issue by Voxellence** [MicrosoftDocs/visualstudio-docs#8512]
In the section of the document entitled...
> Modify the registry to correct an environment that doesn't have a repair option, or to remove an invalid environment

...there is mention of two places in the Registry where Python is stored. However, there is actually a third location for 32-bit versions of Python which is...
HKEY_LOCAL_MACHINE\Software\Wow6432Node\

Perhaps that should be added to the page?
...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 563f476d-a91b-58c7-9e32-b238756cc97d
* Version Independent ID: 0a0e9cac-a8dc-47a1-14e1-1dacc3441613
* Content: [Manage Python environments and interpreters - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2022#fix-invalid-environments)
* Content Source: [docs/python/managing-python-environments-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/managing-python-environments-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @ijoosong
* Microsoft Alias: **joesong**

**Comment by j-martens** [comment]
#reassign: @cwebster-99

**Comment by cwebster-99** [comment]
Thanks for the bug report! Documentation has been updated. #please-close
