### ISSUE TITLE
Links for remote tools are broken !!!

### ISSUE THREAD

**Issue by eng-marani** [MicrosoftDocs/visualstudio-docs#8517]
Links for remote tools are broken !!!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3a52d11c-1c52-fb1d-c785-75845f6edee3
* Version Independent ID: 35a11332-d74c-03dd-dbdd-75f256bd68b3
* Content: [Remote debugging - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging?view=vs-2022)
* Content Source: [docs/debugger/remote-debugging.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/remote-debugging.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@eng-marani -- Marantz, thank you for your feedback.  I just tested all 6 links in this section and they are working:
- [Download and Install the remote tools](https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging#download-and-install-the-remote-tools)

You may need an active Visual Studio subscription to see some of them.


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by eng-marani** [comment]
No, they are still not working. Try the "Remote Debugging for Visual Studio 2022". It sends to main index download page. The link for VS2019 anyway do works indeed

**Comment by WilliamAntonRohm** [comment]
@eng-marani -- Marantz, that is odd.  When I click on that link, it sends me to 
- https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2022

which is the correct destination:

![image](https://user-images.githubusercontent.com/27738025/193697291-c6551a25-4ed2-46eb-9faf-ac9835df55ca.png)

**Comment by WilliamAntonRohm** [comment]
@eng-marani -- Marantz, if you are still not able to get to the correct destination, please add this issue here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

**Comment by eng-marani** [comment]
It is still broken, sorry. At least for "italian" version. The tool link goes straight on the generic download page

**Comment by WilliamAntonRohm** [comment]
@eng-marani -- Marantz, thank you for clarifying.  The Italian version is also working, at least here:
![it](https://user-images.githubusercontent.com/27738025/194678471-8c3bc1f9-3d62-4c3f-bece-61ecc03e3cd8.png)

**Comment by eng-marani** [comment]
This is the offending link:

https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2022

It still do not open any specific page for me. But i understand now that i have to mannually open the accordion control below to access the remote tools. Just i was expecting the ancher link to go stright there and not generically to the top download page,

**Comment by WilliamAntonRohm** [comment]
@eng-marani -- Marantz, thank you again for clarifying.  I'm glad you were able to find the right location.
