### ISSUE TITLE
Will this page contain details about specific features that will not be available in ARM64?

### ISSUE THREAD

**Issue by AngelosP** [MicrosoftDocs/visualstudio-docs#8523]
Hello there,

My team is responsible for certain features that will not be available in the ARM64 builds of Visual Studio. We want to provide our customers with a link that explains which features are not available, why and what the mitigation action would be. Is this the page we can expect to contain this information or will there be a different page in the future?

Thank you
Angelos

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e5a7fdd5-9d50-a1ee-62b3-ab6457e392d2
* Version Independent ID: 81da91ce-8fe0-d919-2f91-123d4ec44430
* Content: [Visual Studio on ARM powered devices - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-on-arm-devices?view=vs-2022)
* Content Source: [docs/install/visual-studio-on-arm-devices.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/visual-studio-on-arm-devices.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@AngelosP, thanks for your feedback.

We are planning to update the docs timed with general availability release, to reflect what is included in the release and is currently in Preview.

Currently, the preview notes contain the list of features released:
[Blog Preview 1](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-4-preview-1/#arm64)
[Blog Preview 2](https://devblogs.microsoft.com/visualstudio/visual-studio-2022-17-4-preview-2/#arm64)
[Preview release notes](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#summary-of-whats-new-in-this-release-of-visual-studio-2022-version-174-preview-2)
