### ISSUE TITLE
CPython vs PyBind11 performance

### ISSUE THREAD

**Issue by GilbertSchuurman** [MicrosoftDocs/visualstudio-docs#8531]
I did exactly as instructed. There is a huge difference in performance between CPython and PyBind11 approach.

Running benchmarks with COUNT = 500000
[tanh(x) for x in d] (Python implementation) took 0.570 seconds

[fast_tanh(x) for x in d] (CPython C++ extension) took 0.157 seconds

[fast_tanh2(x) for x in d] (PyBind11 C++ extension) took **13.368** seconds

Visual C++ 2017
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @ijoosong
* Microsoft Alias: **joesong**

**Comment by WilliamAntonRohm** [comment]
@GilbertSchuurman -- Gilbert, thank you for your feedback.  This is a product issue more than a documentation issue -- please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
