### ISSUE TITLE
competing rules : first or last wins, and compete/duplicate/hierarchy conflicts ?

### ISSUE THREAD

**Issue by DickBaker** [MicrosoftDocs/visualstudio-docs#8537]
The .editorconfig file(s) drive the analysis and code-cleanup behaviour, but are hierarchical (like CSS) unless "root=true" is set at the level of the current code file. Likewise individual "rules" can belong to particular scope e.g. `[*.{cs,vb}] or [*.cs]` so there is plenty of opportunity for conflicting rules to exist. Nowhere have I seen prioritisation (apart from the root designation) in docs that states whether first/last occurence wins.

IMHO the VS editor for .editorconfig files should surface any such conflicts (and/or duplication) of the "key" in each nvp tuple.

Given that content is free-form (devs can edit at will to change order, spacing etc) the editor should also cope with parsing away such subjective styles to compare such standardised tokens/values.

Ditto explain overlaps between [say] IDE0003/IDE0009 and the long-form textual equivalents (`dotnet_style_qualification_for_`_foo_).

Sadly tools intended to help devs sometimes add yet more complexity (".. now you have two problems.." ain't just for regex!)

It would be great to have a WINMERGE-type 2-way/3-way comparison utility that would allow disparate ruleset files be compared. I suggest that a user could elect one of the candidate files be deemed principal, s.t. the other(s) would be juggled to match any subjective whitespace etc. Please!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: efd1e8a4-67b0-57f9-7026-dab24253f7a9
* Version Independent ID: b04dd946-edef-3bbc-ebd1-b6ac43d19689
* Content: [EditorConfig versus analyzers - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/code-quality/analyzers-faq?source=recommendations&view=vs-2022)
* Content Source: [docs/code-quality/analyzers-faq.yml](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/code-quality/analyzers-faq.yml)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@DickBaker -- Dick, thank you for your thorough feedback.  Please add the product suggestions here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@Mikejo5000 -- Mike, please look into the first paragraph above.
