### ISSUE TITLE
Response file puzzle

### ISSUE THREAD

**Issue by sakuragaoka2001** [MicrosoftDocs/visualstudio-docs#8543]
Somebody please explain something I don't understand about the response files. On my system, there is no autoresponse file "MSBuild.rsp" in the directory that contains MSBuild.exe. There aren't any rsp files in other related locations (e.g. parent folder) either. So now, while runing a build in Visual Studio 2019, I use the process explorer to figure out the command line that was used to call the compiler (cl.exe) and which contains the name of the temporary response file that has been submitted to the compiler. What puzzles me is that the compiler options that I find in that file are very different from the ones I see in the VS2019 > Project > Properties > C/C++ > Command Line. I would expect these two sets of options to be identical, but they aren't at all. Would anybody please clarify this phenomenon, and maybe add some text to this page for people to understand what's really going on? Generally speaking, there is extremely little information to be found on the Internet about these response files. Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 962f15c2-d0d4-dc36-b3d4-8ce382bb78b7
* Version Independent ID: 8e4e0436-ec38-6ed0-9c09-a033da7618a4
* Content: [MSBuild Response Files - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-response-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-response-files.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@sakuragaoka2001 
The concept of response file is documented in the compiler command-line documentation for the various compilers and tools.https://learn.microsoft.com/en-us/cpp/build/reference/at-specify-a-compiler-response-file?view=msvc-170

Yes, the command-line may differ, and if you change the Verbosiy settings in Tools > Options > Projects and Solutions > Build and Run, you can view the command-line that's actually used. Those settings are described here: https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-dialog-box-projects-and-solutions-build-and-run?view=vs-2022

We're looking into updating the docs in various places to make this more clear. The verbosity options in that Tools > Options dialog relate to the -verbosity MSBuild command-line option and are described at https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022

**Comment by WilliamAntonRohm** [comment]
@sakuragaoka2001 -- Mario, thank you for your considered feedback.

@ghogen -- Gordon, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
