### ISSUE TITLE
MMC closes at step C

### ISSUE THREAD

**Issue by MJ1223** [MicrosoftDocs/visualstudio-docs#8545]
In trying to follow the steps on this for mmc  after clicking OK at the end of step c  MMC closes.   so I cannot get to setps d, e or f

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4e4bce72-0471-4ff0-6948-671f2e1f9f9f
* Version Independent ID: 3a255b89-a741-5bcc-4342-e4e4943197e1
* Content: [Install certificates for an offline installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/install-certificates-for-visual-studio-offline?view=vs-2022)
* Content Source: [docs/install/install-certificates-for-visual-studio-offline.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/install-certificates-for-visual-studio-offline.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@MJ1223 -- thank you for your feedback.  The instructions are wrong, so don't click OK on either step 1.c. or 2.a.  I am updating the article.
