### ISSUE TITLE
support for cpp on visual studio mac and linux

### ISSUE THREAD

**Issue by DeveloperKev** [MicrosoftDocs/visualstudio-docs#8548]
Hi,
we all 've been longing for c++ support on mac & linux which is lacking.
pls make it cross-platform, so that users will skyrocket as vscode did. 
Best.

**Comment by WilliamAntonRohm** [comment]
@DeveloperKev -- thank you for your feedback and request.  This is repo is solely for documentation issues, and this is product-related.  Please add it here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
