### ISSUE TITLE
 end tag for CopyToOutputDirectory has typo error

### ISSUE THREAD

**Issue by CDTamhankar** [MicrosoftDocs/visualstudio-docs#8555]
typo error

`<CopyToOutputDirectory>PreserveNewest<CopyToOutputDirectory>`

for `<CopyToOutputDirectory>` tag , end tag is wrongly typed as `<CopyToOutputDirectory>`

it should have been 
`</CopyToOutputDirectory>`

So entire  line should have been  .....
`<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 54968ac1-07eb-8537-1a9d-13dccc31f259
* Version Independent ID: af818105-b95d-8f5a-8152-a4414962921d
* Content: [MSB3577: Two output file names resolved to the same output path: 'path' - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3577?view=vs-2022)
* Content Source: [docs/msbuild/errors/msb3577.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb3577.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@CDTamhankar -- thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
