### ISSUE TITLE
Bring back the option for a condensed version of the Sync screen

### ISSUE THREAD

**Issue by nvangyseghem** [MicrosoftDocs/visualstudio-docs#8560]
[It's all nice and well to have the screen-wide sync screen covering your code to give the "git experience", but we're mainly using VS for SSRS and SSIS, and would like to keep the sync screen in the Team explorer as a tab along with the solution explorer in the right column. When moving the scree-wide sync there, the fetch and pull information is hardly available, as it tries to list all info on one line, instead of on multiple lines under a "fetch" section or a "pull" section. I honestly don't see the improvement for our work by removing the Team explorer "changes" section to a "git experience" section that covers our reports & packages.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b9f93437-0395-edd6-508e-127ca4c9a5ad
* Version Independent ID: b9f93437-0395-edd6-508e-127ca4c9a5ad
* Content: [Browse repos, compare branches & commits - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/version-control/git-browse-repository?view=vs-2022)
* Content Source: [docs/version-control/git-browse-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-browse-repository.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Taysser-Gherfal
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@nvangyseghem -- thank you for your well-considered feedback.  As this is a product issue, and not a documentation issue, please add it here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
