### ISSUE TITLE
Rename Unit testing section or extract some sub-sections

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#8566]
Multiple of the articles or tools mentioned under the `Unit testing` section are applicable also for component, integration, acceptance... tests so I think it would be easier to either rename category in `Testing` or promote some sub-sections.

**Comment by WilliamAntonRohm** [comment]
@Evangelink -- Amaury, thank you for your suggestion.  Are you following a particular learn.microsoft.com article?

**Comment by WilliamAntonRohm** [comment]
@Evangelink -- Amaury, thank you for your followup.  Please provide the URLs of a couple of articles in those realms and I will contact their author(s).

**Comment by Evangelink** [comment]
Hey @WilliamAntonRohm, sorry I totally missed this issue (got quite a lot on my plates lately). Most of the articles in this tree view would need to be updated to be a little more generic: https://learn.microsoft.com/visualstudio/test/unit-test-basics

**Comment by WilliamAntonRohm** [comment]
@Evangelink -- Amaury, thank you for following up with that information.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Evangelink** [comment]
@Mikejo5000 @WilliamAntonRohm I would really like to move forward on this. Today MSTest doc is split in multiple sections and that's really hard for users to find the right info.

If no answer, I will submit a PR and see from there.

**Comment by Mikejo5000** [comment]
@Evangelink Sounds like you have a plan in mind! Please go ahead and submit a PR and I'll add comments. Please use the private repo for the PR. Thanks!
