### ISSUE TITLE
Code coverage ignores project with keyword "DataCollector" in their name

### ISSUE THREAD

**Issue by A-Katopodis** [MicrosoftDocs/visualstudio-docs#8571]
There is a hidden behavior not mentioned anywhere. If your project is named anywhere as `DataCollector` the code coverage wont pick it up.

It should be noted here as a troubleshot step that if your project has the word/setence "DataCollector" in it. It won't work.

Examples of project names that wont be picked up:
- DataCollectorUnitTests
- Fabrikam.DataCollector
- Fabrikam.DataCollector.UnitTests

The above info should be added to the docs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4d41fc7-bc52-8fe3-6b25-c1b2c3f89eb1
* Version Independent ID: 9d141754-5f8f-d330-0974-75cbcf45a011
* Content: [Troubleshooting Code Coverage - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/troubleshooting-code-coverage?view=vs-2022)
* Content Source: [docs/test/troubleshooting-code-coverage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/troubleshooting-code-coverage.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@pavelhorak Pavel, is it OK to document this behavior? I assume this is some kind of reserved name.

**Comment by Mikejo5000** [comment]
Fix should be live by the end of the day.
