### ISSUE TITLE
document typo ng start

### ISSUE THREAD

**Issue by Yang09701194** [MicrosoftDocs/visualstudio-docs#8576]
in this file

https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md

 there is

    The Angular CLI running the ng start command

is it mean `ng serve`?

**Comment by WilliamAntonRohm** [comment]
@Yang09701194 -- thank you for your feedback.  According to this article, `ng start` is sufficient for .Net to kick off `ng serve`:
 - [Run ng commands](https://learn.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-6.0&tabs=visual-studio#run-ng-commands)


cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
