### ISSUE TITLE
This is supposed to be To be "Tutorial 1 Create a Picture Viewer (VB)", but suddenly, from the sourec (https://learn.microsoft.com/en-us/visualstudio/ide/create-a-visual-basic-winform-in-visual-studio?toc=%2Fvisualstudio%2Fget-started%2Fvisual-basic%2Ftoc.json&bc=%2Fvisualstudio%2Fget-started%2Fvisual-basic%2Fbreadcrumb%2Ftoc.json&view=vs-2019)  to linked page  (https://learn.microsoft.com/en-us/visualstudio/ide/tutorial-windows-forms-picture-viewer-layout?view=vs-2019)  it has become "Tutorial: Create a picture viewer (C#)"

### ISSUE THREAD

**Issue by exjnb** [MicrosoftDocs/visualstudio-docs#8578]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98193b8b-ad46-6f5f-225f-aae4a34ed401
* Version Independent ID: 98193b8b-ad46-6f5f-225f-aae4a34ed401
* Content: [Tutorial: Create a 'picture viewer' Windows Forms app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-picture-viewer-layout?view=vs-2019)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-picture-viewer-layout.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-picture-viewer-layout.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@exjnb -- thank you for your feedback.  The second article in this tutorial is labeled C# but there is no code, so it applies to both C# and Visual Basic.  In the third article, you can choose to see the Visual Basic or C# versions:
![image](https://user-images.githubusercontent.com/27738025/198945455-3e7bb6f7-cd3d-4081-b624-2f09db8a5316.png)


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
