### ISSUE TITLE
Extra tools needed for arm64

### ISSUE THREAD

**Issue by arorholt** [MicrosoftDocs/visualstudio-docs#8579]
I'm running Linux on arm64. I had to add
RUN apk add --no-cache python2 g++ make
before
WORKDIR /app
in my Dockerfile

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cddd74b1-e0f1-1cae-e92d-c7c2b81e77e3
* Version Independent ID: f853e977-81c2-64d6-682e-1e712344cbad
* Content: [Tutorial: Get started with Docker apps in Visual Studio Code](https://learn.microsoft.com/en-us/visualstudio/docker/tutorials/docker-tutorial?WT.mc_id=vscode_docker_aka_getstartedwithdocker)
* Content Source: [docker/tutorials/docker-tutorial.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docker/tutorials/docker-tutorial.md)
* Product: **vs-code**
* GitHub Login: @ucheNkadiCode
* Microsoft Alias: **uchen**

**Comment by WilliamAntonRohm** [comment]
@ghogen -- Gordon, please review this addition in [private PR 10582](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10582).
