### ISSUE TITLE
Remove MSBuildLocator.RegisterDefault examples

### ISSUE THREAD

**Issue by jzabroski** [MicrosoftDocs/visualstudio-docs#8588]
> > `MSBuildLocator.RegisterDefault()` is recommended by the Microsoft documentation
> 
> Where? We should fix that immediately.
> 
> I wonder if we should consider changing `RegisterDefault` to do this, instead.
> 
> I regret ever making `RegisterDefault`. I would like to remove it in an upcoming release--it does a _very_ poor job of hiding the complexity of selecting an instance, and I think it'd be better to push that directly to the Locator-using developer. I don't think `RegisterLatest` really helps much on that front, because it doesn't account for workloads or possible version incompatibilities.
> -- @rainersigwald , https://github.com/microsoft/MSBuildLocator/pull/184

**Comment by WilliamAntonRohm** [comment]
@jzabroski -- John, thank you for your feedback.

@ghogen -- Gordon, please look into this issue, and see [this comment](https://github.com/microsoft/MSBuildLocator/pull/184#issuecomment-1253320510).
