### ISSUE TITLE
MSBuild properties for static graph build

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#8589]
Please document the MSBuild properties that are used by the static graph feature (`-graphBuild` option):

- InnerBuildProperty
- InnerBuildPropertyValues
- IsGraphBuild

The `InnerBuildProperty` and `InnerBuildPropertyValues` properties are described in <https://github.com/dotnet/msbuild/blob/58c672337b92d9c9975a70ac445a3a4330fa2940/documentation/specs/static-graph.md>. The `IsGraphBuild` property is not described there, but developers need to know about it (see <https://github.com/dotnet/msbuild/issues/6852#issuecomment-1287839644>).

I'm not sure whether the static graph feature is still considered experimental. The `msbuild -help` output [calls the `-graphBuild` option experimental](https://github.com/dotnet/msbuild/blob/58c672337b92d9c9975a70ac445a3a4330fa2940/src/MSBuild/Resources/Strings.resx#L786), but the documentation at <https://learn.microsoft.com/en-us/visualstudio/msbuild/build-process-overview?view=vs-2022#graph-option> and <https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022#switches> says no such thing. Anyway, even if the feature is experimental and you don't yet want to document the properties fully, it would be good to list them in the table and state that they are used by the static graph feature, to warn developers against using them for other purposes.

I think these should be classified as "well-known properties" rather than "Common MSBuild project properties", because they are used in the C# source code of MSBuild, rather than only in _.targets_ files or SDKs. They are not "reserved properties", because they can be overridden.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab5a5a0e-ae03-1237-6ebe-743066f27fa9
* Version Independent ID: a342bfa4-4b0c-0a47-3695-858044f5aa5f
* Content: [MSBuild Reserved and Well-known Properties - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-reserved-and-well-known-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-reserved-and-well-known-properties.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@KalleOlaviNiemitalo 
I've created an internal PR to address this issue
