### ISSUE TITLE
It would be nice if you discussed how to uncomment code.

### ISSUE THREAD

**Issue by mweel1** [MicrosoftDocs/visualstudio-docs#8593]
It would be nice if you discussed how to uncomment code.

Thx!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caccb9e2-62f4-1a44-fc22-f60600f6e48c
* Version Independent ID: 4a0a7029-bcd7-f7d4-c69d-8eaca94fc23d
* Content: [Comment out code - Visual Studio for Mac](https://learn.microsoft.com/en-us/visualstudio/mac/comments?view=vsmac-2022)
* Content Source: [mac/comments.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/comments.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @jmatthiesen
* Microsoft Alias: **jomatthi**

**Comment by WilliamAntonRohm** [comment]
@mweel1 -- Mardo, thank you for your feedback.  To uncomment code, just repeat what you did to comment it.

> To comment out an entire block of code:
> Select the code and select Toggle Line Comment(s) from the context menu
> OR
> Use the cmd + / key binding on the selected code.
> These methods can be used to comment and uncomment sections of code.


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
