### ISSUE TITLE
Reference-style links broken

### ISSUE THREAD

**Issue by Joe-Sewell-PreEmptive** [MicrosoftDocs/visualstudio-docs#860]
The [reference-style links](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) on pages in the `docs/ide/dotfuscator` directory are broken. Here’s what one page looks like on the rendered document:

![reference-links](https://user-images.githubusercontent.com/25648343/39311195-418eb95e-493a-11e8-8f06-dea86f3569e7.png)

It looks like the problem is that each page’s list of references was turned into a bulleted list. This happened in commit effd099d – for example, [here](https://github.com/MicrosoftDocs/visualstudio-docs/commit/effd099d3a5538178aced2f35bcd177e4b277193#diff-a098f7bcf69c49241ec0bd3f43734c90L76) the lines defining the “2017-install” and “get-started” references were prefixed with a bullet.
 
I should note that I work for the Dotfuscator team, so I’m filing this issue both as a reader and as the content owner. I did search if other pages were affected by this issue, but I didn’t find any.

I'll be filing a PR to fix this issue shortly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ce8729-6a95-31d9-9f1c-110011d074a1
* Version Independent ID: 7862fca2-ef34-b629-34a6-1158ae4c1dae
* Content: [Dotfuscator Community Edition (CE) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/dotfuscator/)
* Content Source: [docs/ide/dotfuscator/index.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/dotfuscator/index.md)
* Service: **unspecified**
* GitHub Login: @Joe-Sewell-PreEmptive
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Joe-Sewell-PreEmptive thanks, and sorry for breaking the links! next time i'll ask you to review it.

**Comment by Joe-Sewell-PreEmptive** [comment]
No problem, and thanks for the quick turnaround on this issue.

**Comment by Joe-Sewell-PreEmptive** [comment]
@gewarren Do you know how soon these changes will go live on docs.microsoft.com?

**Comment by gewarren** [comment]
@Joe-Sewell-PreEmptive They should have been live already but there is an issue with the sync between our public and private repos. Sorry; it should be fixed later today!

**Comment by Joe-Sewell-PreEmptive** [comment]
@gewarren Do you have an updated ETA on this syncing problem? Should I file a new GitHub issue to track its progress?

**Comment by gewarren** [comment]
@Joe-Sewell-PreEmptive the syncing problem was resolved yesterday, however today's publish-to-live hasn't quite happened yet (it should happen in the next hour though). Once that happens, I think you'll see your updates. Sorry about this!

**Comment by Joe-Sewell-PreEmptive** [comment]
@gewarren Great, thanks for the update.

**Comment by gewarren** [comment]
@Joe-Sewell-PreEmptive look for this to be live in the next 30 minutes.

**Comment by Joe-Sewell-PreEmptive** [comment]
This looks to be fixed. Thanks @gewarren!
