### ISSUE TITLE
Missing UseTrustedSettings option

### ISSUE THREAD

**Issue by varnk** [MicrosoftDocs/visualstudio-docs#8600]
The documentation does not mention the **UseTrustedSettings** attribute, which I didn't know existed until I found it on a forum on the web.  https://stackoverflow.com/questions/33017004/error-during-xsl-transformation-execution-of-the-document-function-was-pro

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2edf4455-765e-3107-5b5b-11162a965b65
* Version Independent ID: 37110ada-36c1-f545-d0e0-1c5bacbf71ab
* Content: [Target Element (MSBuild) - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/target-element-msbuild?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(http%253A%252F%252Fschemas.microsoft.com%252Fdeveloper%252Fmsbuild%252F2003%2523XslTransformation)%3Bk(http%253A%252F%252Fschemas.microsoft.com%252Fdeveloper%252Fmsbuild%252F2003%2523Target)%3Bk(vs.xmleditor)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.6.1)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/msbuild/target-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/target-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@varnk
Thanks for reporting this. I think the option needs to be added to the XslTransformation task.
https://learn.microsoft.com/en-us/visualstudio/msbuild/xsltransformation-task?view=vs-2022

In the meantime, there is documentation here for this task parameter:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.xsltransformation.usetrustedsettings?view=msbuild-17-netcore
