### ISSUE TITLE
Remove reference to using registry keys to set devenv.exe process DPI awareness

### ISSUE THREAD

**Issue by merriemcgaw** [MicrosoftDocs/visualstudio-docs#8603]
It turns out that the section re: the registry keys to set are incompatible with the out of proc WinForms designer (originally targeted to the .NET Core) and even some scenarios for the in-proc (.NET Framework)  designer. We should remove this recommendation, and potentially recommend that the user NOT use registry keys to set the devenv.exe process DPI Awareness any way other than the command line or clicking the gold bar should it display (it only displays with the in proc designer). See https://github.com/dotnet/winforms/issues/7997 for details

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Disable DPI-awareness for scaling in forms - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2022)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@merriemcgaw Thanks so much for the heads-up on this. Before we update the page, can you please verify that this also applies to Visual Studio 2019? The page includes monikered information for both Visual Studio 2019 and Visual Studio 2022, so we want to make sure that it applies to both of those versions or to one or the other before we publish an updated page.

**Comment by merriemcgaw** [comment]
@TerryGLee Yes it would apply anywhere VS supports PerMonitor DPI awareness.

**Comment by TerryGLee** [comment]
@merriemcgaw Thanks again for the suggested edit. We've updated the page; please let us know if we should make any further changes.
