### ISSUE TITLE
Can't Publish in Docker Linux (.NETFramework were not found)

### ISSUE THREAD

**Issue by michael-aguilar-ps** [MicrosoftDocs/visualstudio-docs#8615]
Hi, I've  followed the tutorial and works great, except when I try to publish in docker Linux, I am getting this error:
`#15 2.510 /usr/share/dotnet/sdk/6.0.402/Microsoft.Common.CurrentVersion.targets(1220,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/src/test-web/test-web.esproj]
`

I don't know why is calling NETFramework, is there something I can do to avoid this?

I am using the default dockerfile created by Visual Studio:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["test-api/test-api.csproj", "test-api/"]
RUN dotnet restore "test-api/test-api.csproj"
COPY . .
WORKDIR "/src/test-api"
RUN dotnet build "test-api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "test-api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "test-api.dll"]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@michael-aguilar-ps -- Michael, please see related issue #8585, and let me know if that helps answer your question.

cc @Mikejo5000 for awareness

**Comment by michael-aguilar-ps** [comment]
No, there is no solution yet

**Comment by Mikejo5000** [comment]
@michael-aguilar-ps I will ask about this.

**Comment by runehalfdan** [comment]
Try setting this in your esproj-file
<ResolveNuGetPackages>false</ResolveNuGetPackages>

The ResolveNuGetPackageAssets-targets has conditinal on the above property, and exists('$(ProjectLockFile)'). And ProjectLockFile is obj\project.assets.json, which probably got create in a previous build.

**Comment by michael-aguilar-ps** [comment]
> Try setting this in your esproj-file
false

Setting false in what property?

**Comment by runehalfdan** [comment]
> > Try setting this in your esproj-file
> > false
> 
> Setting false in what property?

Apologies; forgot to mark code as code. Updated now

**Comment by alexmg** [comment]
I tested the `ResolveNuGetPackages` setting and still got the same build error.

**Comment by michael-aguilar-ps** [comment]
I am using NET 7 with Visual Studio updated and still getting the same error

**Comment by af-wieda** [comment]
I had this issue as well, and posting for anyone in the same situation as I've spent many hours on solving this.

The Microsoft.JavaScript.Sdk esproj template seems to be the cause of this, see Sdk.targets XML row 112 in nuget package 
https://www.nuget.org/packages/Microsoft.VisualStudio.JavaScript.SDK

I solved it by going into the configuration management in Visual Studio and unchecking the "build" and "deploy" targets for the frontend project. Once they were unchecked my Tekton pipeline could invoke the custom targets from the template which allowed me to run npm install and npm run build to produce the frontend application artifacts.

**Comment by michael-aguilar-ps** [comment]
@af-wieda you are right, that seems to be the issue.
Still, I hope this bug could be fixed, it shouldn't depend of NET Framework. I've tried to build my project on Linux and get the same error.
`/usr/share/dotnet/sdk/7.0.202/Microsoft.Common.CurrentVersion.targets(1229,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/home/michael/Documents/TestReact/reactapp/reactapp.esproj]`

**Comment by Macrox14** [comment]
I've found a workaround after many attemps:

1. In the esproj folder I had to create 2 files:
- Directory.Build.props
```
<Project>
</Project>
```

- Directory.Build.targets
```
<Project>
    <PropertyGroup Label="Globals">
      <TargetFrameworkMoniker></TargetFrameworkMoniker>
    </PropertyGroup>
</Project>
```

After this, the .NET Framework doesn't occurs anymore. Now I can build the app in Linux

2. In order to create the docker, it was necessary to check this [doc](https://learn.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2022), this is my final Dockerfile:
```
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y libpng-dev libjpeg-dev curl libxi6 build-essential libgl1-mesa-glx
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN apt-get install -y nodejs
WORKDIR /src
COPY ["reactapp/nuget.config", "reactapp/"]
COPY ["webapi/webapi.csproj", "webapi/"]
COPY ["reactapp/reactapp.esproj", "reactapp/"]
RUN dotnet restore "webapi/webapi.csproj"
COPY . .
WORKDIR "/src/reactapp"
RUN npm ci
WORKDIR "/src/webapi"
RUN dotnet build "webapi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "webapi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "webapi.dll"]
```

To the default Dockerfile, I had to install nodejs, and `RUN npm ci`

Hope this helps somebody else
