### ISSUE TITLE
Need more info on deploy

### ISSUE THREAD

**Issue by andrewhood** [MicrosoftDocs/visualstudio-docs#8631]
It would be helpful to have more information on how to deploy correctly. I've tried to deploy to an Azure app service, and can see that the api is working, but the react front-end does not load. It works locally when running the project.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by andrewhood** [comment]
Maybe my azure app service settings are wrong, I don't know, but the answer here worked for me: https://stackoverflow.com/a/73784739/1767005

If all these [different deploy methods](https://github.com/MicrosoftDocs/visualstudio-docs/issues/8481) need code changes, maybe the template should be updated, or more info added to the documentation.

**Comment by Mikejo5000** [comment]
@andrewhood The template likely does need an update, which is a known issue and is getting looked at. I tested a workaround on Azure App Service, and it seems to work. See https://github.com/MicrosoftDocs/visualstudio-docs#8661. Doc will be updated by EOD today with the workaround, 11/29/22.
