### ISSUE TITLE
Missing rules

### ISSUE THREAD

**Issue by gwtov** [MicrosoftDocs/visualstudio-docs#8637]
Hi! It seems like the following rules are defined in the NativeMinimumRules.ruleset file (for Visual Studio 2022) but not listed on this page:

[C28308](https://learn.microsoft.com/en-us/cpp/code-quality/c28308)
[C28309](https://learn.microsoft.com/en-us/cpp/code-quality/c28309)
[C33001](https://learn.microsoft.com/en-us/cpp/code-quality/c33001)
[C33010](https://learn.microsoft.com/en-us/cpp/code-quality/c33010)
[C33020](https://learn.microsoft.com/en-us/cpp/code-quality/c33020)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7cb78651-8c5e-c4c3-e1d2-dfaeacc013cc
* Version Independent ID: ee7e71b0-2d2c-e5db-d850-41a1906607df
* Content: [Native Minimum Rules rule set - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/code-quality/native-minimum-rules-rule-set?view=vs-2022)
* Content Source: [docs/code-quality/native-minimum-rules-rule-set.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/code-quality/native-minimum-rules-rule-set.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@gwtov I see those rules documented in this section for C++: https://learn.microsoft.com/en-us/cpp/code-quality/c33020?view=msvc-170
It's easy to miss, but this section is the legacy section for the .NET analyzers.
