### ISSUE TITLE
Find in Files is broken

### ISSUE THREAD

**Issue by RecourseDesign** [MicrosoftDocs/visualstudio-docs#8640]
[Enter feedback here]
when "Current Project" is selected, there appears to be a random chance that it will work - otherwise it searches the entire solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e27881f-04bc-b7ba-e217-8360278a14f8
* Version Independent ID: d31c8050-339a-688c-869e-ff7942fd3f74
* Content: [Find in Files - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2022)
* Content Source: [docs/ide/find-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/find-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@RecourseDesign -- Richard, thank you for your feedback.  Please add this as a potential product issue here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
