### ISSUE TITLE
Request Blocked when Downloading WebPI from MS Learn page link

### ISSUE THREAD

**Issue by marknoble** [MicrosoftDocs/visualstudio-docs#8656]
When I click here: https://learn.microsoft.com/en-us/visualstudio/debugger/error-unable-to-start-debugging-on-the-web-server?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.http)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.7.2)%26rd%3Dtrue&view=vs-2022#vxtbshttpservererrorsthingstocheck:~:text=use%20the%20Web%20Platform%20Installer%20(WebPI)

I get sent to this URL: https://www.microsoft.com/web/downloads/platform.aspx

I see a strange error that says:
The request is blocked.
0WqtuYwAAAABVrqeUKBU9TambaPWHeQ/ZU0pDMjExMDUxMjA5MDM1ADUzZjhkNTEyLTY1Y2YtNDFlOS1hNGIzLWNlODhiMzg5N2ViMQ==

But if I open the same URL in an In Private Window, the page is not blocked and opens properly.

The browser is: Microsoft Edge
Version 107.0.1418.35 (Official build) (64-bit)

I also reported this issue to the Edge team.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 12b3da70-ab86-495d-abfe-384f369660fe
* Version Independent ID: 2456d73a-68bd-cc6b-bff0-e7666e53f404
* Content: [Unable to Start Debugging on the Web Server - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/error-unable-to-start-debugging-on-the-web-server?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(vs.debug.error.http)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%253Dv4.7.2)%26rd%3Dtrue&view=vs-2022#aspnet)
* Content Source: [docs/debugger/error-unable-to-start-debugging-on-the-web-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/error-unable-to-start-debugging-on-the-web-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@marknoble WebPI is near end-of-life. Please see https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-7-5-computer?view=vs-2022#BKMK_deploy_asp_net for alternative method to install ASP.NET.
For ASP.NET Core, see https://learn.microsoft.com/en-us/visualstudio/debugger/remote-debugging-aspnet-on-a-remote-iis-computer?view=vs-2022#install-aspnet-core-on-windows-server
I will update this article. Thank!

**Comment by Mikejo5000** [comment]
Update will be live by end of day, 12/16/22
