### ISSUE TITLE
Steps are missing

### ISSUE THREAD

**Issue by flywhc** [MicrosoftDocs/visualstudio-docs#8663]
There are only steps 1,2 and 5 in the section [create the AddIn Setup project](https://learn.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2022#to-create-the-addin-setup-project) . I guess Search and Select Installer projects are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9904c-bc2c-49e6-b661-5598354dbc40
* Version Independent ID: 6dca41d0-9c34-f5cc-a2b0-6c6e9df76063
* Content: [Deploying a VSTO Solution Using Windows Installer](https://learn.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2022)
* Content Source: [docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
Thanks @flywhc for letting us know.  If you change the Version of Visual Studio to Visual Studio 2019, all steps are shown:  https://learn.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2019#to-create-the-addin-setup-project
