### ISSUE TITLE
Views: folder or file?

### ISSUE THREAD

**Issue by simon-sellick** [MicrosoftDocs/visualstudio-docs#8673]
https://learn.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-04-full-django-project-template?view=vs-2022#step-4-2-understand-the-views-and-page-templates-created-by-the-project-template 

The paragraph specifies a folder app/views, but this actually seems to be a single file, views.py, containing all three views.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 485e6157-bf3f-1065-d944-9860f198662c
* Version Independent ID: 8daa9161-23cb-8bfb-b736-6695b6e50ee8
* Content: [Learn Django tutorial in Visual Studio step 4, web project template](https://learn.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-04-full-django-project-template?view=vs-2022)
* Content Source: [docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/learn-django-in-visual-studio-step-04-full-django-project-template.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
Thanks for the report @simon-sellick - I will investigate this.

**Comment by cwebster-99** [comment]
#sign-off

**Comment by cwebster-99** [comment]
Documentation has been updated to reflect the proper file references. #please-close
