### ISSUE TITLE
MSTest v2 API documentation

### ISSUE THREAD

**Issue by Evangelink** [MicrosoftDocs/visualstudio-docs#8679]
Hi there,

I am the owner of MSTest and I would like to know how to ensure that the MSTest API documentation (see https://learn.microsoft.com/dotnet/api/microsoft.visualstudio.testtools.unittesting) is updated? Is there some mechanism of auto-update? 

Also, we are now actively working on the tool and there will be APIs added or remove and I would like to understand how we could surface the version to improve user experience.

**Comment by Evangelink** [comment]
I think this issue is of high importance. We are currently displaying stale information to our users and if it's not possible to find a way to have up-to-date information I would rather prefer not to display any information.

**Comment by WilliamAntonRohm** [comment]
@Evangelink -- Amaury, thank you for your followup.  I believe the API documentation is auto-generated from the source files' comments.  I don't know the refresh schedule.  Please create a new issue for this, in the [dotnet/dotnet-api-docs](https://github.com/dotnet/dotnet-api-docs/issues) repo.

cc @leslierichardson95 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.
