### ISSUE TITLE
Add instructions for how to find the tool 

### ISSUE THREAD

**Issue by BretJohnson** [MicrosoftDocs/visualstudio-docs#868]
We should add instructions to tell the user how to actually find and run this tool, as it's not at all obvious.
These are the steps, I believe: https://stackoverflow.com/questions/41105665/vsix-color-editor-tool
It's installed to a path like Microsoft Visual Studio\2017\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin\VsixColorEditor.exe
You have to find it there and run it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 805e3a08-8dae-ea45-05d3-e778af88d77e
* Version Independent ID: ea62b6c9-5b1b-ac79-f5f9-2e5df6350915
* Content: [VSIX Color Editor - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/internals/vsix-color-editor)
* Content Source: [docs/extensibility/internals/vsix-color-editor.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/internals/vsix-color-editor.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
@BretJohnson Good suggestion. Feel free to submit a PR.

**Comment by gregvanl** [comment]
Some of the other VS SDK tools provide the location and it's not hard to search under the Developer Command Prompt to find the tool.
