### ISSUE TITLE
Debug > Windows > Modules  ?

### ISSUE THREAD

**Issue by TheOnlyDasBoot** [MicrosoftDocs/visualstudio-docs#8680]
Did you actually try going to (Debug > Windows > Modules  ?

There is no selection MODULES there.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95bc6d7e-2b58-4755-4411-c5f369011a6c
* Version Independent ID: d5710161-bc97-6d33-6c6b-77fc9cfe9c62
* Content: [Troubleshoot breakpoints in the debugger - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/troubleshooting-breakpoints?view=vs-2022)
* Content Source: [docs/debugger/troubleshooting-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/troubleshooting-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@TheOnlyDasBoot The usual issue here is that you're not or no longer in Debug mode. I.e., your app needs to be running and paused, generally at a breakpoint. Then you can see the the Modules option there.

**Comment by Mikejo5000** [comment]
Closing as we need more info to continue.
