### ISSUE TITLE
microsoft blend

### ISSUE THREAD

**Issue by bigfishtoddslivewire** [MicrosoftDocs/visualstudio-docs#8681]
[Enter feedback here] Blend czn be ago to for simple tak and developing projects.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb4a86d-efe1-3ff6-2456-eac6659c6d09
* Version Independent ID: a1faa99b-0e1a-8291-f87c-747dcccb3b0b
* Content: [Blend for Visual Studio feature tour](https://learn.microsoft.com/en-us/visualstudio/xaml-tools/creating-a-ui-by-using-blend-for-visual-studio?view=vs-2022&source=docs)
* Content Source: [docs/xaml-tools/creating-a-ui-by-using-blend-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xaml-tools/creating-a-ui-by-using-blend-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @maddymontaquila
* Microsoft Alias: **maleger**

**Comment by WilliamAntonRohm** [comment]
@bigfishtoddslivewire -- Todd, thank you for your feedback.  


cc @maddymontaquila for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
