### ISSUE TITLE
[Wrong category designation] Related Links/Alternate Account

### ISSUE THREAD

**Issue by CarreEau** [MicrosoftDocs/visualstudio-docs#8683]
Hi,

There is a little mistake misleading customers when they try to add an alternate account.

On the VS Portal, we can read "Add alternate account" under the title "Alternate Account".
But on the public documentation, we have this "Add alternate account" under the title "Related Links".

<img width="467" alt="Related Links Alternate Accounts" src="https://user-images.githubusercontent.com/116568920/203342260-723570b6-4fb7-4eff-b8d5-7a859e823b12.png">

When customers search for this "Related Links", it appears nowhere as it does not exist.
Could you replace "Related Links" by "Alternate account" after review, please?

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a760034-6571-5206-1476-0a0d6b2ef031
* Version Independent ID: d5ce817f-c949-e070-459d-4c7728329550
* Content: [Manage Visual Studio Subscriptions](https://learn.microsoft.com/en-us/visualstudio/subscriptions/manage-vs-subscriptions#linking-my-subscription-to-existing-azure-devops-services-or-azure-subscriptions)
* Content Source: [subscriptions/manage-vs-subscriptions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/manage-vs-subscriptions.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
Thank you for bringing this error to our attention.  I’ve submitted the change and it should be visible soon.

Thanks for helping us improve our content!

Evan

From: CarreEau ***@***.***>
Sent: Tuesday, November 22, 2022 6:41 AM
To: MicrosoftDocs/visualstudio-docs ***@***.***>
Cc: Evan Windom ***@***.***>; Mention ***@***.***>
Subject: [MicrosoftDocs/visualstudio-docs] [Wrong category designation] Related Links/Alternate Account (Issue #8683)


[EXTERNAL EMAIL]

Hi,

There is a little mistake misleading customers when they try to add an alternate account.

On the VS Portal, we can read "Add alternate account" under the title "Alternate Account".
But on the public documentation, we have this "Add alternate account" under the title "Related Links".

[Related Links Alternate Accounts]<https://user-images.githubusercontent.com/116568920/203342260-723570b6-4fb7-4eff-b8d5-7a859e823b12.png>

When customers search for this "Related Links", it appears nowhere as it does not exist.
Could you replace "Related Links" by "Alternate account" after review, please?

Regards,

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 7a760034-6571-5206-1476-0a0d6b2ef031
  *   Version Independent ID: d5ce817f-c949-e070-459d-4c7728329550
  *   Content: Manage Visual Studio Subscriptions<https://learn.microsoft.com/en-us/visualstudio/subscriptions/manage-vs-subscriptions#linking-my-subscription-to-existing-azure-devops-services-or-azure-subscriptions>
  *   Content Source: subscriptions/manage-vs-subscriptions.md<https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/manage-vs-subscriptions.md>
  *   Product: visual-studio-family
  *   Technology: vs-subscriptions
  *   GitHub Login: @evanwindom<https://github.com/evanwindom>
  *   Microsoft Alias: amast
