### ISSUE TITLE
An additional reason why breakpoints might not be hit, for the documentation

### ISSUE THREAD

**Issue by ekolis** [MicrosoftDocs/visualstudio-docs#8684]
Breakpoints might also  be skipped if you're debugging the wrong type of code (e.g. script code vs. .NET 4 vs. .NET Core), as set when attaching to a process.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95bc6d7e-2b58-4755-4411-c5f369011a6c
* Version Independent ID: d5710161-bc97-6d33-6c6b-77fc9cfe9c62
* Content: [Troubleshoot breakpoints in the debugger - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/troubleshooting-breakpoints?view=vs-2022)
* Content Source: [docs/debugger/troubleshooting-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/troubleshooting-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ekolis Thanks! That is a good addition to the doc. I'll make an update.

**Comment by Mikejo5000** [comment]
Update should be live by end of day today.

**Comment by Mikejo5000** [comment]
PR: https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10693
