### ISSUE TITLE
Broken Link for Visual Studio Administration Updates

### ISSUE THREAD

**Issue by Cosmo121** [MicrosoftDocs/visualstudio-docs#8685]
Article
https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-administrator-guide?view=vs-2022

Section
![tip](https://user-images.githubusercontent.com/3526206/203443590-f26b3566-0136-4a49-8f89-62c3742fa40d.png)

_enroll their client machines into Visual Studio Administrator Updates_
`<a href="https://vs/admin/updates/au/blog" data-linktype="external">…</a>`

I think https://vs/admin/updates/au/blog is trying to redirect somewhere in learn.microsoft.com, but not sure where exactly.

**Comment by TerryGLee** [comment]
@anandmeg See also https://github.com/MicrosoftDocs/visualstudio-docs/pull/8662

**Comment by anandmeg** [comment]
@Cosmo121, thanks for your feedback. 
The link has been fixed and the fix should be live later today.
Thanks again!
