### ISSUE TITLE
Azure Tool support has been removed/reduced in VS2022

### ISSUE THREAD

**Issue by BerndK** [MicrosoftDocs/visualstudio-docs#8688]
[Enter feedback here]
It seems that this document describes the behavior of VS2019 - in current version 2022 the feature of e.g. Azure Server Explorer has been removed, see here https://learn.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-resources-managing-with-cloud-explorer?view=vs-2022
So there is (from my perspective) no way to see the storage explorer inside VS2022, you need to use the external Storage Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 047bb5ba-0f0c-15ef-5446-9b7fec4bfda9
* Version Independent ID: 57be5157-8c86-7663-e42e-24458cf86974
* Content: [Browse and manage storage resources - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-storage-resources-server-explorer-browse-manage?view=vs-2022)
* Content Source: [docs/azure/vs-azure-tools-storage-resources-server-explorer-browse-manage.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/azure/vs-azure-tools-storage-resources-server-explorer-browse-manage.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
This should be fixed later today by adding a note similar to ones on other articles.

**Comment by ghogen** [comment]
@BerndK 
Thanks for the issue report. A fix is in the queue.
