### ISSUE TITLE
Visual Studio 2022 C# file icons

### ISSUE THREAD

**Issue by MRahilly** [MicrosoftDocs/visualstudio-docs#8692]
The Visual Studio icons for a C# source file and a C# project file should be interchanged. It is quite easy to choose the wrong file looking at the icons alone.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Version Independent ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Content: [Tutorial: Create a simple C# console app  - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@MRahilly -- thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
