### ISSUE TITLE
admin and admindocs discrepancies

### ISSUE THREAD

**Issue by simon-sellick** [MicrosoftDocs/visualstudio-docs#8694]
Para 10 steps do not align with the content of the web app downloaded, specifically the entries in urls.py, which looks as below.

Note 1: admin is already included (and does work in the app), but admindocs is not. 
Note 2: "from django..." is highlighted by intellisense as undefined
Note 3: the routes use path instead of include

I suspect that I have an earlier or later version than the document describes, but it would be useful to be able to download the actual template used in the examples.  But the undefined 'django' leads me to think that something is missing - although the app seems to run OK.

"""
Definition of urls for DjangoWeb.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e07a-6d43-8800-fd06-be7f8ad21d20
* Version Independent ID: e6b188d8-adc0-cb16-cffa-63bfe2d3ecd4
* Content: [Learn Django tutorial in Visual Studio, step 5, authentication](https://learn.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-05-django-authentication?view=vs-2022)
* Content Source: [docs/python/learn-django-in-visual-studio-step-05-django-authentication.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/learn-django-in-visual-studio-step-05-django-authentication.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
Thanks for the bug report! Documentation has been updated. #please-close
