### ISSUE TITLE
How to enforce anonymous member name to be defined?

### ISSUE THREAD

**Issue by devovercome** [MicrosoftDocs/visualstudio-docs#870]
Hi! 
I am working on setup which includes `dotnet_style_prefer_inferred_anonymous_type_member_names ` for asp.net solution.

Here is global problem - team used to abuse anon object in order to return JSON result. Hovewer, I want to enforce (or encourage at least) write anon object _properties_ of JSON repsonse explicitly. Why? Because if source field of anon object has been renamed - the JSON output will be changed, and JS-frontend would be broken and hard to fix. 

To be more specific, case like:
```
// consider datetime as user-defined structure.
return Json(datetimes.Select(x => new 
{
    x.Mounth // typo, will break js when refactored
//    Mounth = x.Month // wont break after backend refactoring.
})
```

Here is the sampes for the case.
- [editor.config](https://github.com/devovercome/Tmp.EditorConfig.Enforce.AnonTypeNames/blob/master/.editorconfig)
- [csharp code](https://github.com/devovercome/Tmp.EditorConfig.Enforce.AnonTypeNames/blob/master/EditorConfig.Enforce.AnonTypeNames/Program.cs)
- [entire solution (big picture)](https://github.com/devovercome/Tmp.EditorConfig.Enforce.AnonTypeNames)

Environment:
ASP.NET 
.NET 4.7.1
VS 2017 15.6.6

**Comment by gewarren** [comment]
@devovercome To clarify, are you saying that **dotnet_style_prefer_inferred_anonymous_type_member_names = false:error** is not producing the error you're expecting in the following code?

                        var foo = new
			{
				dateTime.Month // this should raise error.
			};

**Comment by devovercome** [comment]
**Yes**,
but it could be some other setting. For separation of concerns sake. 
I really believe it should be separate setting.

**Comment by gewarren** [comment]
@devovercome This sounds like more of a feature request. If so, can you open a request at [Roslyn issues](https://github.com/dotnet/roslyn/issues) instead? It sounds like this is not a documentation issue.
