### ISSUE TITLE
Description is no longer valid with studio 2022

### ISSUE THREAD

**Issue by Delgathar** [MicrosoftDocs/visualstudio-docs#8704]
Code map and live dependency validation no longer show up as components to install with VS 2022.  
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2022)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/install-architecture-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
@Delgathar What SKU of Visual Studio do you have? You need the Enterprise Edition for Code Map and Dependency Validation as stated in the previous page in the section [Edition support for architecture and modeling tools](https://learn.microsoft.com/en-us/visualstudio/modeling/analyze-and-model-your-architecture?view=vs-2022#edition-support-for-architecture-and-modeling-tools).
