### ISSUE TITLE
Visual Studio and git

### ISSUE THREAD

**Issue by rolandwales10** [MicrosoftDocs/visualstudio-docs#8706]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e59f7c3-34dd-c376-9b0c-54601abe6c33
* Version Independent ID: 3e59f7c3-34dd-c376-9b0c-54601abe6c33
* Content: [Manage Git repos in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/version-control/git-manage-repository?view=vs-2022#copy-commits-cherry-pick&wt.mc_id=visualstudio_gitlearningseriesrepo_webpage_cnl)
* Content Source: [docs/version-control/git-manage-repository.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/version-control/git-manage-repository.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @houghj16
* Microsoft Alias: **tglee**

**Comment by rolandwales10** [comment]
I am responding to the documentation here:

https://github.com/microsoft/Git-Learning-Series#msdynttrid=LBKSjsfl76R7z5DAt3N8AMsZwPnwqDIR0ue06DnE8vg

It refers to an Edit button to edit comments on a previous commit.  I have the latest version of Visual Studio 2022, which matches up to the screen print, but there is no Edit button.  This would be really useful.

On cherry picking, Studio has the option greyed out in the menu.  It would be really useful for Studio to provide help on why options are greyed out.

**Comment by TerryGLee** [comment]
@rolandwales10 Thanks for your feedback. To make sure that it goes to the right place, please file it with the Git Learning Series directly, at [https://github.com/microsoft/Git-Learning-Series/issues](https://github.com/microsoft/Git-Learning-Series/issues).

We'll close this now and include with it our thanks to you for your continued interest in our products and services.
