### ISSUE TITLE
Update Windows base image version of Dockerfile example

### ISSUE THREAD

**Issue by ShuiRuTian** [MicrosoftDocs/visualstudio-docs#8718]
[Enter feedback here]
The latest image has already been 2022 rather than 2019, please reference https://hub.docker.com/_/microsoft-windows-servercore

```
# Use the latest Windows Server Core 2019 image.
FROM mcr.microsoft.com/windows/servercore:ltsc2019
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b91a4a43-5353-97cf-7532-7644aa3b497f
* Version Independent ID: 858d9a5c-72f3-6a85-9270-0a0dd9e0438b
* Content: [Install Visual Studio Build Tools into a container](https://learn.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2022)
* Content Source: [docs/install/build-tools-container.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/build-tools-container.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by ShuiRuTian** [comment]
Sorry, I got something wrong....

**Comment by anandmeg** [comment]
We've updated the doc, changes should be live later today.
Thanks for your feedback and helping us improve our docs, @ShuiRuTian.
