### ISSUE TITLE
Offline installer

### ISSUE THREAD

**Issue by macmule** [MicrosoftDocs/visualstudio-docs#873]
Any progress?

Or even progress for an installer that can be deployed programmatically to macOS clients with the SDK's installable in a central location.

**Comment by gewarren** [comment]
@TerryGLee Do you know if there's an progress on this?

**Comment by TerryGLee** [comment]
@asb3993 I believe this is a Visual Studio for Mac question; would you take a look, please?

**Comment by asb3993** [comment]
I've contacted the engineering team to request more information on this. 

In the meantime, I would suggest adding a vote and/or comment to this relevant uservoice: https://visualstudio.uservoice.com/forums/563332-visual-studio-for-mac/suggestions/33816103-visual-studio-for-mac-missing-offline-installer

**Comment by macmule** [comment]
Thanks, folks. Upvoted.

**Comment by vyedin** [comment]
As a workaround, you can download the files listed in our manifest and use that to provision machines: https://www.xamarin.com/static/installer_assets/v4/Mac/Universal/InstallationManifest.xml. This will not install the Android dependencies or emulators, however.
