### ISSUE TITLE
More crap on this page

### ISSUE THREAD

**Issue by sqlguy6212** [MicrosoftDocs/visualstudio-docs#8739]
A right click does not provide what this page says.  MS once again kills their docs with facts that are not true.  Why does MS think people don't like this product????
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f07df07-7ae7-fe46-3c33-7fa4c662894c
* Version Independent ID: 7c08eba3-cc69-c4e5-9f3a-5d837ead9732
* Content: [Implement an interface - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/implement-interface?view=vs-2022)
* Content Source: [docs/ide/reference/implement-interface.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/implement-interface.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@sqlguy6212 -- thank you for your feedback.  If you feel this is a product issues, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @TerryGLee for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
