### ISSUE TITLE
Software Engineer

### ISSUE THREAD

**Issue by RoswellMiller** [MicrosoftDocs/visualstudio-docs#874]
I tried using the MockLanguageExtension and the types ProcessStartInfo and Process are no where to be found.  Ditto for the two class Attributes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff91657a-173a-0013-62e4-e7c8531b8240
* Version Independent ID: 27988cad-5114-41e3-c48a-357431af0fe1
* Content: [Adding a Language Server Protocol extension - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-an-lsp-extension)
* Content Source: [docs/extensibility/adding-an-lsp-extension.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/adding-an-lsp-extension.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @RoswellMiller, those types are in System.Diagnostics part of the .NET Framework.

**Comment by DanTup** [comment]
I had the same issue - the default VSIX template didn't have a reference to System. I also had to add a bunch of others (like Shell and CoreUtility) to get things working. This doc should be updated so there aren't missing steps the user has to figure out.
