### ISSUE TITLE
Big downloads could break!?

### ISSUE THREAD

**Issue by HL-1234** [MicrosoftDocs/visualstudio-docs#875]
If (A complete Visual Studio 2017 layout requires at least 35 GB of disk space) -  it would be nice if I could use a download manager to not start form the beginning when the internet connection breaks or does the vs_[sku].exe work in this way? I see no example for that option or a remark for that problem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for Visual Studio installation - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/command-line-parameter-examples.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@HL-1234 Thanks for your feedback. I'll investigate and report back.

**Comment by TerryGLee** [comment]
@HL-1234 Unfortunately, we don't offer a download manager; however, if that is something that you'd like to see us add, please consider suggesting this to us on our  **[UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide)** forum, where we collect product feature requests.
