### ISSUE TITLE
Build script configuration in package.json

### ISSUE THREAD

**Issue by sameerjalnapurkar** [MicrosoftDocs/visualstudio-docs#8750]
`"scripts": {
 "build": "webpack-cli ./app.tsx --config webpack-config.js"
}`

which is supposed to be added in package.json after the dependencies section, produces the error
`configuration.entry should not contain the item './app.tsx' twice`

It appears that this is because webpack-config.js already contains
`entry: "./app.tsx"`

If we modify the build config in package.json as follows, the problem seems to go away -
`"scripts": {
 "build": "webpack-cli --config webpack-config.js"
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Create a Node.js and React app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2022)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by TimShererWithAquent** [comment]
Hi @sameerjalnapurkar - Thanks for finding this. We're looking into updating the article.
