### ISSUE TITLE
that's not help that's just saying what it is!

### ISSUE THREAD

**Issue by Elantonio** [MicrosoftDocs/visualstudio-docs#8752]
Just give a step by step guide how to resolve this!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 082295f3-9acb-6b3f-cdb4-425d9a249df0
* Version Independent ID: ce3c3863-2426-420e-4387-9d73cc949437
* Content: [MSB3270: There was a mismatch between the processor architecture of the project being built 'architecture' and the processor architecture of the reference 'reference', 'architecture'. - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3270?view=vs-2022)
* Content Source: [docs/msbuild/errors/msb3270.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb3270.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@Elantonio 
I wonder how this could be more helpful. The solution would be different for different projects, so I'm not sure there is a step-by-step way to resolve this. It depends on the intended output architecture, and the availability of architecture-specific builds of the referenced assemblies. It could be that there's no available version of a referenced assembly for the target architecture (provided for by a third-party vendor, for example), thus making it impossible to build the intended target for that architecture.
