### ISSUE TITLE
Some of the 'See also' links are broken. Potential fix suggested.

### ISSUE THREAD

**Issue by ChristopherBenson** [MicrosoftDocs/visualstudio-docs#8753]
This issue refers to the landing page for the Visual Studio Administrator Guide. There is a **See Also** section near the foot of that page, consisting of eight links. Several (three?) of those eight links are broken and result in a **404-Not-Found** error message.

In each case, the broken target URI text ends with .md
The links work correctly if that suffix is removed.

For example ...

The penultimate link is Visual Studio product life-cycle and servicing
and its (broken) target is `https://learn.microsoft.com/en-us/visualstudio/productinfo/vs-servicing.md`
If that link is changed to `https://learn.microsoft.com/en-us/visualstudio/productinfo/vs-servicing`
then the link will work correctly.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ed6b5f4-371f-825c-cf8a-3fdac127864f
* Version Independent ID: 5f721d18-882b-4fdf-3b02-c389026c62bc
* Content: [Visual Studio administrator guide](https://learn.microsoft.com/en-gb/visualstudio/install/visual-studio-administrator-guide?view=vs-2022)
* Content Source: [docs/install/visual-studio-administrator-guide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/visual-studio-administrator-guide.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by TimShererWithAquent** [comment]
Thanks @ChristopherBenson - fix is in progress!
