### ISSUE TITLE
Unable to set breakpoints while troubleshooting

### ISSUE THREAD

**Issue by raymond1** [MicrosoftDocs/visualstudio-docs#8755]
The instructions will not work if your default browser is not Edge or Chrome. If someone is using Firefox for their default browser, then they will not be able to put in a breakpoint. The documentation should add a note saying this so that beginners can use the debugging feature.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68483bc8-45dc-fc2e-b289-2901a70461ff
* Version Independent ID: 5167502a-bd55-8927-5656-1c4f107884d7
* Content: [Create an ASP.NET Core app with TypeScript - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2022)
* Content Source: [docs/javascript/tutorial-aspnet-with-typescript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-aspnet-with-typescript.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@raymond1 Thanks for the feedback! Were you able to set the breakpoint in Visual Studio? You could not hit the breakpoint in the running app (w/Firefox)? Is that correct?

**Comment by raymond1** [comment]
I was not actually able to set the breakpoint completely. When I clicked 
on the side, it was only half set, meaning there as a point on the left, 
but it was not a solid circle. It was kind of an empty circle instead of 
a solid, filled-in dot. When I was going through the documentation, it 
was hard to figure out why I wasn't able to set the break point.

**Comment by raymond1** [comment]
I missed your second question. That is correct. When my app was running, 
I couldn't hit the breakpoint using Firefox.

**Comment by Mikejo5000** [comment]
@raymond1 It sounds like you set the breakpoint while the app was running? (The empty circle means the breakpoint won't be hit, for some particular reason, but usually only shows up as empty at run time.) Do you get the same result when you set the breakpoint before running the app? Can you still not hit the breakpoint when you run the app?

**Comment by Mikejo5000** [comment]
@raymond1 Also, I"m not sure how you are starting the app, but you may need to add Firefox in the **Start** > Browse with** dialog box prior to debugging, then use F5 (Debug > Start Debugging) to start the debugger session. 
![image](https://user-images.githubusercontent.com/11948536/208533305-9b2a9dcc-8657-4016-9397-363944e30375.png)

**Comment by raymond1** [comment]
Hi Mike,

I set the breakpoint while the app was stopped. If you are able to get 
breakpoints to work in Firefox, then there's no problem with the 
documentation. Otherwise, there's a problem.

According to this quote from this page: 
https://learn.microsoft.com/en-us/visualstudio/javascript/debug-nodejs?view=vs-2022, 
it's clear that client-side debugging will only work with Chrome or 
Edge:

"Debug client-side script

*Visual Studio provides client-side debugging support only for Chrome 
and Microsoft Edge (Chromium).* In some scenarios, ..."

I just think the documentation for a tutorial for beginners should 
reflect this fact. This is the link I was using for the tutorial:
https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-aspnet-with-typescript?view=vs-2022

Raymond

**Comment by Mikejo5000** [comment]
@raymond1 Yes, I also see this Feedback item:
https://developercommunity.visualstudio.com/t/vs2022-firefox-not-listed-in-browsers-for-debug/1479752
I'll add a note in the doc. Thanks!

**Comment by Mikejo5000** [comment]
Doc update will be live by end of day today, 12/19/22
