### ISSUE TITLE
VS Dev Prompt 2022 locations still point to 2019 ones

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/visualstudio-docs#8758]
The paths for where the Developer Command Prompt lives point to the 2019 location still instead of the 2022 location ([in this section](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022#developer-command-prompt))

> "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"

And similar should instead be

> "%ProgramFiles%\Microsoft Visual Studio\2022\Community\Common7\Tools\VsDevCmd.bat"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 513f1e35-aba1-8b92-845e-1ed4ccad8e62
* Version Independent ID: 45eb46ce-a9b1-f141-5a97-c448b9349c48
* Content: [Command-line shells & prompt for developers - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022)
* Content Source: [docs/ide/reference/command-prompt-powershell.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/command-prompt-powershell.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@michael-hawker Appreciate the feedback; we've fixed that. Thanks for helping to improve the Visual Studio documentation!
