### ISSUE TITLE
How to target an Azure cloud PC / Windows365 that I have access to

### ISSUE THREAD

**Issue by lgp1985** [MicrosoftDocs/visualstudio-docs#8759]
How to target an Azure cloud PC / Windows365 that I have access to via Remote Desktop app.
I don't see ways to target the machine, as I have no clue what would be the public name, as it seems to be behind a RDP gateway. Is there ways to proxy the connection via that?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ec9455-ef64-8854-94bc-9be28887a6a4
* Version Independent ID: 9adeea5e-7ba1-065f-5de0-aae9147f9c85
* Content: [Remote Testing in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022)
* Content Source: [docs/test/remote-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/remote-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@AbhitejJohn Abhitej, is remote testing supported for Azure scenarios? Are there any details we can add?

**Comment by AbhitejJohn** [comment]
Yikes, I'm sorry this fell through the cracks. We do not have a way of connecting to environments where a machine name/ip address cannot be specified in the testenvironments.json file [here](http://aka.ms/remotetesting).

**Comment by Mikejo5000** [comment]
Closing, as I don't think there is a doc issue here.
