### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by mflanagan** [MicrosoftDocs/visualstudio-docs#876]
I notice there's no separate section for step 7: "Check Coverage." Can I do this if my production code is in a DLL, AND my unit tests aren't in that same project? If not, any thoughts on what I'd need to do? I suspect I can change my production lib to be a static lib, but I have 30+ production dll's that I'd like to test. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68de6547-7902-7ee9-bc79-42fa5f382f9e
* Version Independent ID: 65e6b992-16c2-02e6-0646-e7d50e65bf21
* Content: [How to: Write unit tests for C++ DLLs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/walkthrough-writing-unit-tests-for-cpp-dlls)
* Content Source: [docs/test/walkthrough-writing-unit-tests-for-cpp-dlls.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/test/walkthrough-writing-unit-tests-for-cpp-dlls.md)
* Service: **unspecified**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by gewarren** [comment]
@mikeblome could you take a peek at this one?

**Comment by mikeblome** [comment]
@mflanagan apologies for delayed response. Yes, it should work with a DLL. You can create a separate test project (or multiple test projects if desired) and reference the DLLs from there. Are you able to run unit tests successfully in general? Is only code coverage broken? Remember that code coverage is a VS Enterprise feature, so you need to be using that edition of VS for it to work.
