### ISSUE TITLE
Update to .NET 7?

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/visualstudio-docs#8762]
Default version is .NET 7 for the target framework.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a29f3723-6a51-ae9f-c1a7-07d59b30d0a2
* Version Independent ID: 9cd1552e-1579-7da1-ffc0-e41b51fb3ae1
* Content: [Visual Studio for Mac IDE Tour - Visual Studio for Mac](https://learn.microsoft.com/en-us/visualstudio/mac/ide-tour?view=vsmac-2022)
* Content Source: [mac/ide-tour.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/ide-tour.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by mairaw** [comment]
This feedback is still actionable

**Comment by WilliamAntonRohm** [comment]
@mairaw -- Maira, thank you for your followup.  Are you referring to this screenshot?

![image](https://user-images.githubusercontent.com/27738025/231888791-d556296c-da8b-4281-ad3f-a3947111468b.png)

**Comment by mairaw** [comment]
Yes @WilliamAntonRohm. I believe when I opened the issue, I saw .NET 7.0 as the default option in VS for Mac.

**Comment by j-martens** [comment]
#assign: @anandmeg

**Comment by anandmeg** [comment]
@mairaw, thanks for your feedback! We've updated the page and the changes are live now. Thanks!
