### ISSUE TITLE
Instructions are missing link to Nuget Packages

### ISSUE THREAD

**Issue by rogermyung** [MicrosoftDocs/visualstudio-docs#8764]
The solutions offered on this page did not fix this problem for me. The best solution I found was to add the package reference to [Microsoft.NETFramework.ReferenceAssemblies](https://www.nuget.org/packages/Microsoft.NETFramework.ReferenceAssemblies), which is also explained in https://github.com/Microsoft/dotnet/tree/main/releases/reference-assemblies

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d37f1f1b-ed94-5769-bf8d-c6963e1b4d6c
* Version Independent ID: 83419c12-eb75-f725-3452-8a631c94f660
* Content: [MSB3644: The reference assemblies for 'version' were not found. - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb3644?view=vs-2022)
* Content Source: [docs/msbuild/errors/msb3644.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb3644.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@rogermyung 
Thanks, I'm adding links to those resources.
