### ISSUE TITLE
Replace vue-cli with vite

### ISSUE THREAD

**Issue by klim09** [MicrosoftDocs/visualstudio-docs#8766]
Since vue-cli is in Maintenance mode, this tutorial should be switched to vite based setup.
The template change to switch is fairly minimal.

**Comment by WilliamAntonRohm** [comment]
@klim09 -- thank you for your suggestion.  Please provide the URL of this tutorial article.

**Comment by klim09** [comment]
Here is the tutorial.
https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022

Here is the vue-cli js page with the mention of "Maintenance mode".
https://cli.vuejs.org/

![image](https://user-images.githubusercontent.com/35288076/208210593-1279b710-3011-4e78-8b04-38643e142674.png)

**Comment by Mikejo5000** [comment]
Thanks for the information! I'm asking about this.

**Comment by Mikejo5000** [comment]
@klim09 Product team is aware of this issue and there is planning to address it. Closing as it is currently not a doc issue.
