### ISSUE TITLE
Could the preview workloads be included in these docs?

### ISSUE THREAD

**Issue by ryanjaeb** [MicrosoftDocs/visualstudio-docs#878]
It would be useful to have a list of the workloads that are part of preview releases.  For example, the [upcoming release](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-Preview-relnotes#BuildToolsUWP) includes a workload for UWP.  I would like to see what happens if I try to install that workload in a [Docker container](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container), but I can't find the workload ID anywhere.

Alternatively, if there's a way to discover the available workloads via the installer, it would be good enough (for me) to have that documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e062363-94e9-f776-650f-a0723ab713a3
* Version Independent ID: 9181db12-cbdf-6f95-27f1-833930d6d323
* Content: [Visual Studio Build Tools 2017 workload and component IDs - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools#nodejs-build-tools)
* Content Source: [docs/install/workload-component-id-vs-build-tools.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/install/workload-component-id-vs-build-tools.md)
* Service: **unspecified**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@ryanjaeb Thanks for your feedback. We'll investigate the possibility and report back soon.

**Comment by TerryGLee** [comment]
@ryanjaeb We appreciate your suggestion, but we respectfully decline to provide separate workload data for Preview releases. The reason? The workloads are generally static release to release right now. As for the Docker scenario that you describe: Although we’ve not published guidance on it yet, we plan to. Please stay tuned.

Cheers,
~ Terry
