### ISSUE TITLE
hat*tricks

### ISSUE THREAD

**Issue by elvismunyikiiru** [MicrosoftDocs/visualstudio-docs#8786]
[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cddd74b1-e0f1-1cae-e92d-c7c2b81e77e3
* Version Independent ID: f853e977-81c2-64d6-682e-1e712344cbad
* Content: [Tutorial: Get started with Docker apps in Visual Studio Code](https://learn.microsoft.com/en-gb/visualstudio/docker/tutorials/docker-tutorial?WT.mc_id=vscode_docker_aka_getstartedwithdocker)
* Content Source: [docker/tutorials/docker-tutorial.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docker/tutorials/docker-tutorial.md)
* Product: **vs-code**
* GitHub Login: @ucheNkadiCode
* Microsoft Alias: **uchen**

**Comment by ucheNkadiCode** [comment]
Hey @WilliamAntonRohm would you mind removing me from getting tagged on these issues? I’m no longer at the company

**Comment by WilliamAntonRohm** [comment]
@ucheNkadiCode -- Uche, can you recall who took over for you, that is, to whom should I assign the authorship?

**Comment by ucheNkadiCode** [comment]
My former manager @spboyer will know! Thank you!
