### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by ymeric** [MicrosoftDocs/visualstudio-docs#879]
Followed instructions in VS 2017 Enterprise 15.6.6 and getting two errors:
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ValidateVsixParts" task could not be initialized with its input parameters.	VSIXProject1			
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ContentManifest" parameter is not supported by the "ValidateVsixParts" task. Verify the parameter exists on the task, and it is a settable public instance property.	VSIXProject1			

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99d54da6-38c2-4cc4-9b22-a8f817c83f29
* Version Independent ID: fffed6f2-3b8e-d2c7-e3e3-34ec8bf090d2
* Content: [Hello World - Visual Studio](https://docs.microsoft.com/en-in/visualstudio/extensibility/extensibility-hello-world#create-an-extensibility-project)
* Content Source: [docs/extensibility/extensibility-hello-world.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/extensibility/extensibility-hello-world.md)
* Service: **unspecified**
* GitHub Login: @gregvanl
* Microsoft Alias: **gregvanl**

**Comment by gregvanl** [comment]
Hi @ymeric Sorry to hear you are having trouble compiling the Hello World example. I tried with VS 2017 15.6.7 and didn't see your compiler error. Perhaps you could try updating your installation using the Visual Studio Installer and see if that helps. Another possibility is that you have a corrupt VS SDK  installation which you could try to repair by removing the "VS extension development" workload and adding it back.
