### ISSUE TITLE
Article related to image name that is being created

### ISSUE THREAD

**Issue by poornachandra07** [MicrosoftDocs/visualstudio-docs#8802]
Hi,

It would be helpful if there is some information related to the image names of custom docker images that are being created in this way.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7aee46f8-9db1-33ef-b637-fc8e8881fab9
* Version Independent ID: 6c469f9f-9751-669f-3dd4-c4fb49c9ae19
* Content: [Work with multiple containers using Docker Compose - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/containers/tutorial-multicontainer?view=vs-2022#add-docker-compose-support-1)
* Content Source: [docs/containers/tutorial-multicontainer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/tutorial-multicontainer.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
Related to #8791.
