### ISSUE TITLE
Updated local Help Viewer documentation not in sync with online documentation

### ISSUE THREAD

**Issue by ejasonstone** [MicrosoftDocs/visualstudio-docs#8805]
Hello,

I asked this question at learn.microsoft.com and a Microsoft MSFT acknowledged the issue and suggested that I post the issue here:

I am using Help Viewer 2.3 with Visual Studio 2022 Community Edition.

According to the "Manage Content" tab in Help Viewer, all local content is up to date. However, I find the local documentation topics compared to online documentation may be out of date.

For example, as of 12/29/2022, my "updated" local help documentation for ASP.NET Core/Fundamentals/Overview is dated 11/07/2019 but the online version is significantly different and dated 06/13/2022.

Another example: An updated .NET Core Guide/Get Started with .NET Core local document dated 07/19/2022 will link to an online document dated 08/12/2022 when using "View this topic online in your default browser."

I have tried removing the documentation for a given "book" and then adding it again, but I get the same result.

Why is current downloadable documentation not in sync with help documentation at https://learn.microsoft.com/?

**Comment by WilliamAntonRohm** [comment]
@ejasonstone -- thank you for your thorough feedback.  You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback). 

Also, please add this information here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @j-martens for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
