### ISSUE TITLE
Doc are out of date

### ISSUE THREAD

**Issue by epark99** [MicrosoftDocs/visualstudio-docs#8809]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa65a08-a9e2-721d-e00c-1f28afffe2be
* Version Independent ID: babf20c3-c235-d839-7340-fb9c11c449dc
* Content: [Create a Node.js and Express app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs?view=vs-2022)
* Content Source: [docs/javascript/tutorial-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@epark99 -- thank you for your feedback.  Please be more specific.

**Comment by Mikejo5000** [comment]
I think there has been a template change recently. I will follow up.

**Comment by Mikejo5000** [comment]
PR: MicrosoftDocs/visualstudio-docs-pr#10659

**Comment by Mikejo5000** [comment]
Doc update should be live by around 12 noon PST, 1/20/23
