### ISSUE TITLE
bad maximumFractionDigit field

### ISSUE THREAD

**Issue by monarchdodra** [MicrosoftDocs/visualstudio-docs#881]
The `maximumFractionDigit` field in the code snippet should actually be `maximumFractionDigits` (plural).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d71e6f22-ce3f-9fc7-06aa-aca4cc38742e
* Version Independent ID: ba98a0d5-966c-2914-8768-67c434d35c41
* Content: [format Property (Intl.NumberFormat)](https://docs.microsoft.com/en-us/scripting/javascript/reference/format-property-intl-numberformat)
* Content Source: [scripting-docs/javascript/reference/format-property-intl-numberformat.md](https://github.com/Microsoft/visualstudio-docs/blob/master/scripting-docs/javascript/reference/format-property-intl-numberformat.md)
* Service: **unspecified**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@monarchdodra Thanks for the feedback! I will plan to fix this
