### ISSUE TITLE
Browse for other Type no longer exists

### ISSUE THREAD

**Issue by HughWarrington** [MicrosoftDocs/visualstudio-docs#8811]
This documentation appears to be outdated.

The option to 'Browse' for other types in the Type dropdown has apparently been removed. See https://developercommunity.visualstudio.com/t/VS2022-Properties-gt;Settingssettings/1690711 which I found originally via https://stackoverflow.com/q/73843512/1688738.

I suppose the docs should be updated now that the functionality is gone. Although I would much rather of course that the feature was added back to VS... I'm not sure how I'm going to work around this one yet, having just ported a large project .NET Framework -> .NET.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d42d594f-fb40-0518-68a0-23c5ed00e5b9
* Version Independent ID: 7338e7b8-9f34-30e1-9d55-55900ebd48ec
* Content: [Settings Page, Project Designer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/settings-page-project-designer?view=vs-2022&source=docs)
* Content Source: [docs/ide/reference/settings-page-project-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/settings-page-project-designer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@HughWarrington -- Hugh, thank you for your well-researched feedback.  As to your suggestion to have this feature reinstated, please add it here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@TerryGLee -- Terry, please look into this issue.

**Comment by HughWarrington** [comment]
For anyone interested, my request to reinstate the Browse functionality is [here](https://developercommunity.visualstudio.com/t/Reinstate-the-Type-Browse-option-to-Set/10244864).

**Comment by TerryGLee** [comment]
@HughWarrington Thanks for letting us know and for following up with a request to reinstate the Browse functionality via the Developer Community. Meanwhile, I've updated the documentation to include the following statement: 

"**Browse** is available only for .NET Framework projects. **Browse** isn't available for .NET or .NET Core projects." 

We'll keep an eye on this and if the situation changes, we'll either revise or remove the statement. Meanwhile, we'll close this issue with our further thanks to you for your help in improving the Visual Studio documentation (and possibly, the project, too).
