### ISSUE TITLE
Install Visual Studio 2022 from a local layout

### ISSUE THREAD

**Issue by HuoZhengtang** [MicrosoftDocs/visualstudio-docs#8817]
[Enter feedback here]
I have created a local layout using the command "vs_Community.exe --layout D:\VS2022 --add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --lang en-US zh-CN".
Then I start to install it. I find there are two executable files in the folder as follow:
![图片](https://user-images.githubusercontent.com/57654602/210741565-45a0f9fc-1019-4489-b3e8-9fbfff9c14d8.png)
I run them both and the same workload and packages are listed as follow
![图片](https://user-images.githubusercontent.com/57654602/210742004-2419a752-19e3-4b01-8645-2f49c5479a44.png)
![图片](https://user-images.githubusercontent.com/57654602/210742065-23fb0a63-fdc8-4580-9726-847bc7d12af1.png)
And I need 9GB to install them. So I try the command to install VS2022, like this "vs_Community.exe --noweb --add Microsoft.VisualStudio.Workload.NativeDesktop --includeOptional"
However, I get different packages to install as following:
![图片](https://user-images.githubusercontent.com/57654602/210742832-139c9336-b205-432a-904d-b043c39446cd.png)
![图片](https://user-images.githubusercontent.com/57654602/210742883-d11af23e-9c57-483f-96e5-9fed8a091330.png)
And I need 30GB to install them.

I am confused why the files installed in the two ways are different and which one I should chose?
Anyone shall give me advise?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an offline installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-an-offline-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
Closing as being related to #8816.

cc @anandmeg for awareness
