### ISSUE TITLE
Minor documentation adjustment for clarity on updating Visual Studio via the command line

### ISSUE THREAD

**Issue by jrybacek** [MicrosoftDocs/visualstudio-docs#8824]
This link gives some steps for updating Visual Studio via the command line, but I missed the importance of downloading the latest version of the installer.

https://learn.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2022#update-in-two-steps

Is there a benefit to adding one more command line that suggest downloading the correct version of Community, Professional, or Enterprise from these links?

https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022

The script does not if you have an old version of the `vs_[Version].exe` installer.  Perhaps, we could add this line before the two others?

Invoke-WebRequest -OutFile vs_community.exe -Uri https://aka.ms/vs/17/release/vs_community.exe

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2022#update-in-two-steps)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@jrybacek, thanks for your feedback. Hope the above info is helpful.

I'm closing this issue now but please reach out to us again if you have further questions.
Thanks!
