### ISSUE TITLE
MSBuild Item functions - Metadata() function behavior is not fully explained

### ISSUE THREAD

**Issue by jrdodds** [MicrosoftDocs/visualstudio-docs#8827]
The intrinsic item function `Metadata` is documented as

> Returns the values of the metadata that have the metadata name.

This description doesn't mention an important detail of the `Metadata` function's behavior. Although the function is creating a new item collection, metadata in the 'source' is copied over. It's not an obvious assumption that the `Metadata` function would behave this way.

Consider the following example:

```XML
  <Target Name="MetadataToItem">
    <ItemGroup>
      <Sample Include="AAA" SomeItems="1;2;3" />
      <Sample Include="BBB" SomeItems="3;4;5" />
    </ItemGroup>

    <ItemGroup>
      <AllSomeItems Include="@(Sample->Metadata('SomeItems'))" KeepDuplicates="false" />
    </ItemGroup>
    <Message Text="AllSomeItems is @(AllSomeItems)" />
  </Target>
```

The output produced is:

```
MetadataToItem:
  AllSomeItems is 1;2;3;3;4;5
```

Note there are two items with the Identity of '3' despite the `KeepDuplicates="false"` attribute. This is because the metadata of the two Items are different. One Item 3 has metadata of `SomeItems="1;2;3"` and the other Item 3 has metadata of `SomeItems="3;4;5"`. This can be a baffling result because the documentation doesn't explain that the metadata of the source items will be copied to the new items.

If the example code is changed to add a `RemoveMetadata="SomeItems"` attribute, then the output will be `1;2;3;4;5`.

```XML
    <ItemGroup>
      <AllSomeItems Include="@(Sample->Metadata('SomeItems'))" KeepDuplicates="false" RemoveMetadata="SomeItems" />
    </ItemGroup>
```

Although the behavior is unexpected, there is value to having the `Metadata` function copy over the metadata.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62ddc739-9c79-2dda-20b4-09aa26d348d1
* Version Independent ID: 21d74f53-5b13-5efb-704e-27e28d6dc586
* Content: [Item Functions - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/item-functions?view=vs-2022)
* Content Source: [docs/msbuild/item-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/item-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@jrdodds 
Thanks, this is an interesting issue and well-explained.
I've added a new section to the Item Functions page and also referenced this issue in the Items page in the KeepDuplicates section.
The page updates should be live soon.
