### ISSUE TITLE
.NET SDKs missing from out of support list?

### ISSUE THREAD

**Issue by ShawnMcGough** [MicrosoftDocs/visualstudio-docs#8828]
Should this page include out of support .NET *SDK*s?
Specifically, .NET 5 SDK went out of support December 2022, should it be added here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a246e9cb-50e4-57fe-9c33-5b184b14caf3
* Version Independent ID: a246e9cb-50e4-57fe-9c33-5b184b14caf3
* Content: [Visual Studio out-of-support components](https://learn.microsoft.com/en-us/visualstudio/install/out-of-support-components?view=vs-2022)
* Content Source: [docs/install/out-of-support-components.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/out-of-support-components.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@shawnMcGough, thanks for your feedback. We've updated the doc to add the new out -of-support components for 2019.
Thanks!

**Comment by anandmeg** [comment]
@shawnMcGough, thanks for your feedback. We've updated the doc to add the new out -of-support components for 2019.
Thanks!
