### ISSUE TITLE
"View Call Hierarchy" not "View Class Hierarchy"

### ISSUE THREAD

**Issue by MappingSteve** [MicrosoftDocs/visualstudio-docs#883]
Re "You can display the Call Hierarchy window by selecting a method (or property or constructor) and then choosing View Class Hierarchy ..." -- the correct menu item is View CALL Hierarchy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b960c4e0-ac54-9e65-6397-44d7a5750764
* Version Independent ID: 224d2c57-b542-8030-6b77-ce8a7889b466
* Content: [View code structure in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/viewing-the-structure-of-code)
* Content Source: [docs/ide/viewing-the-structure-of-code.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/viewing-the-structure-of-code.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@MappingSteve Thanks, I will fix this.
