### ISSUE TITLE
C++/CLI - Immediate and Watch... and mixed mode...

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [MicrosoftDocs/visualstudio-docs#8833]
[visualstudio-docs](https://github.com/MicrosoftDocs/visualstudio-docs)/[docs](https://github.com/MicrosoftDocs/visualstudio-docs/tree/main/docs)/[debugger](https://github.com/MicrosoftDocs/visualstudio-docs/tree/main/docs/debugger)/walkthrough-debugging-at-design-time.md

(and others) talk about things such as referencing a variable in the immediate window... However with C++/CLI much does not work [and since it seems unlikely to get fixed, should be documented asw such]. 

Simple repo:

`class Sample
{
public:
    void Foo();
    static void Bar();
};

void Sample::Foo()
{ 
    int x = 1;
}
void Sample::Bar() { int x = 1; }

int main()
{
    Sample s;
    std::cout << "Hello World!\n";
}
`

Compile WITHOUT/clr,  set breakpoint on the cout and invoke s.Foo() -- all good...
Now compile wiht /clr [making it a C++/CLI program!!!] and "Unable to resolve identifier: 'Foo" is the result.

**Comment by Mikejo5000** [comment]
@dcorbin-wintellect Thanks for the feedback! I will update the article.

**Comment by davidcorbin-atmosera** [comment]
@Mikejo5000  - Did the article ever get updated?

**Comment by Mikejo5000** [comment]
@davidcorbin-atmosera Not yet, thanks for the comment. I should be able to publish the update soon.
