### ISSUE TITLE
Would this work with later version of Excel?

### ISSUE THREAD

**Issue by ChaiSwaddipong** [MicrosoftDocs/visualstudio-docs#8839]
The page only specifies Excel 2010 and 2013. How about Excel 2016,2018,2021,etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 926f7f34-3f79-cfe2-c9ea-2d36bcdbafae
* Version Independent ID: 7ac3f98c-c147-3378-a2c8-7bd2944a2acd
* Content: [Walkthrough: Create your first VSTO Add-in for Excel - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel?view=vs-2022&tabs=csharp)
* Content Source: [docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/walkthrough-creating-your-first-vsto-add-in-for-excel.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@ChaiSwaddipong -- Chai, thank you for your question.  Please try the Version control in the upper left of the page:

![image](https://user-images.githubusercontent.com/27738025/212440604-ca627362-62d5-4bb5-b09d-2a38b4bc034c.png)


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
