### ISSUE TITLE
Call Hierarchy window - clarify which languages and/or product versions show "Calls From"

### ISSUE THREAD

**Issue by MappingSteve** [MicrosoftDocs/visualstudio-docs#884]
It appears that managed languages (C#,VB), at least in Community edition, have "Calls To", but do NOT have "Calls From". Please state which languages (C++?) and/or product versions (Pro/Enterprise?) are required, to have this feature.  In the doc text, the relevant phrase is "... and lists the methods that are called from that method.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b960c4e0-ac54-9e65-6397-44d7a5750764
* Version Independent ID: 224d2c57-b542-8030-6b77-ce8a7889b466
* Content: [View code structure in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/viewing-the-structure-of-code)
* Content Source: [docs/ide/viewing-the-structure-of-code.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/ide/viewing-the-structure-of-code.md)
* Service: **unspecified**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@MappingSteve Thanks, I will try to clarify the information.
