### ISSUE TITLE
Description column of table is not displaying complete tetcts (right margin)

### ISSUE THREAD

**Issue by ObjectViewer** [MicrosoftDocs/visualstudio-docs#8843]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 797c58ff-3694-adda-188b-4ec4d079bd5c
* Version Independent ID: 442f90ff-9a99-c7dd-23c8-fbe51bcd8c0d
* Content: [Build actions for files - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/build-actions?view=vs-2022)
* Content Source: [docs/ide/build-actions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/build-actions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@ObjectViewer -- please use the horizontal scroll bar at the bottom of the table to see the rest of the column.
