### ISSUE TITLE
Learn Django in Visual Studio Step 2-2.2 incorrect code generates error

### ISSUE THREAD

**Issue by MarissaB** [MicrosoftDocs/visualstudio-docs#8847]
Step 2-2: Run the app from the Django project
Step 2 has a code section that uses **django.conf.urls** to import **url**, which looks like it's been deprecated and removed [(source on removal here)](https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0) from the latest version of Django.
Old code:

```
from django.conf.urls import include, url
import HelloDjangoApp.views

# Django processes URL patterns in the order they appear in the array
urlpatterns = [
    url(r'^$', HelloDjangoApp.views.index, name='index'),
    url(r'^home$', HelloDjangoApp.views.index, name='home'),
]
```
I stumbled over it, but I found the correct implementation [(source)](https://docs.djangoproject.com/en/4.1/ref/urls/) using **django.urls** to import **re_path** (below):
```
from django.urls import include, re_path
import HelloDjangoApp.views

# Django processes URL patterns in the order they appear in the array
urlpatterns = [
    re_path(r'^$', HelloDjangoApp.views.index, name='index'),
    re_path(r'^home$', HelloDjangoApp.views.index, name='home')
]
```
First time submitting an issue - hope I did it right! :)
Edited to update to using re_path instead of url. This applies for the other sections later in the guide where the other pages are added (About, etc).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09d5f2d3-bebb-5564-87df-8ab0eedb410c
* Version Independent ID: c1dac521-a8f2-1b81-af35-bd9da71fb6e8
* Content: [Learn Django tutorial in Visual Studio step 2, views and page template](https://learn.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-02-create-an-app?view=vs-2022)
* Content Source: [docs/python/learn-django-in-visual-studio-step-02-create-an-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/learn-django-in-visual-studio-step-02-create-an-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by WilliamAntonRohm** [comment]
@MarissaB -- Marissa, thank you for your feedback and solution.  You're welcome to submit these edits yourself via a Pull Request (PR).  This will allow authors to directly add your text to the documentation. This also displays your GitHub image on the page of authors, and lists you as a contributor to the documentation.

- Navigate to the page of interest
- Select the "Edit" button at the top right of the page
- Select the "Pencil" icon on the right
- Modify the text within the text box in markdown format
- Name your file change and copy the link to your Git Issue into the "extended description" box
- Select "Propose file change"
- Select "Create pull request" on the 'Comparing changes' page
- Select "Create pull request" on the 'Open a pull request' page
- Wait for an author to review and approve the change request - this can take a bit depending on the complexity

If you'd prefer to put in our queue, use the `#reassign` automation command to assign it to @cwebster-99:  `#reassign: @cwebster-99`

**Comment by MarissaB** [comment]
Okay awesome, I'll make a pull request in the next few days. :)

**Comment by WilliamAntonRohm** [comment]
@MarissaB -- Marissa, thank you for your two PRs!  Your contribution is appreciated.
