### ISSUE TITLE
ASP.NET Core with Angular Multiple Project Doesn't Work

### ISSUE THREAD

**Issue by scarez** [MicrosoftDocs/visualstudio-docs#8850]
The process described on this page does not work.  When setting multiple startup projects with the API project on top, the Angular project always starts first and blocks the API project from starting.  When you force close the Angular console the API console starts.  I have found no way to get both consoles to be open at the same time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by scarez** [comment]
Solution Property Page showing API project set to start before Angular project.
![image](https://user-images.githubusercontent.com/6879999/212443349-c168e01c-09f2-4e0a-915a-0b00d2c1cce0.png)

Can see in Output window that the Angular project is built and attempts to deploy with no indication that the API project is being built or started.

**Comment by Ziumper** [comment]
Same problem here even with API project set to be started as first one.

**Comment by Ziumper** [comment]
There is a way to run it by chanigng the Api project as a start project and afterwards use npm start in seperate terminal inside solution folder.  

By the way , I tried dependency checks and etc. but it didn't work. I think the best way is simply use npm start command option but I am not sure how to configure visual studio to run debugger for API project in that case.

**Comment by scarez** [comment]
I do think it has to do with the Angular project being set to Deploy while the API project does not have a deploy option.  If I uncheck Deploy for the Angular project then the API project starts first, but the Angular project never starts.

**Comment by Mikejo5000** [comment]
@scarez I tested the steps in the article with 17.5 Preview 2 and everything worked as expected. @safacero in case she has a suggestion. Otherwise, please use [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
Closing since I can't repro the issue, so there's no doc update without additional information.
