### ISSUE TITLE
Required updates are very unclear

### ISSUE THREAD

**Issue by HughWarrington** [MicrosoftDocs/visualstudio-docs#8856]
Near the top of the page it says:

> A ClickOnce application periodically reads its deployment manifest file to see whether updates to the application are available. If available, the new version of the application is downloaded and run.

But further down:

> Make updates required
> There may be occasions when you want to require users to run an updated version of your application [...] In this case, you would want to mark your update as required and prevent users from running the earlier version.

Well, that sounds like what happens anyway, according to the first section. What is a non-required update, when the first section makes it sound like new versions are always downloaded and run, at least if the application has recently checked for the presence of new versions?

I think the missing link here (discovered by experimentation) is that if you don't make updates required, the user is presented with a choice about upgrading:

![image](https://user-images.githubusercontent.com/5960770/212723107-6d1eb4d5-bf18-4290-b4d1-2b41d3f8b8bd.png)

I think this page needs rephrasing. Add something about the user by default being given a choice whether to upgrade -- unless the update is marked as required.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2af9ac7e-1011-df44-6232-89136459646e
* Version Independent ID: c2dcd806-769a-87a9-8228-15bf5398ad6c
* Content: [Choosing a ClickOnce Update Strategy - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/deployment/choosing-a-clickonce-update-strategy?view=vs-2022)
* Content Source: [docs/deployment/choosing-a-clickonce-update-strategy.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/choosing-a-clickonce-update-strategy.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updating doc. Fix should be live by EOD today, 1/27/23
