### ISSUE TITLE
VS 2017, I dont have option to check a box to "Create a new Git repository."

### ISSUE THREAD

**Issue by bbartling** [MicrosoftDocs/visualstudio-docs#886]
Hi, in my visual studio 2017... Im trying to follow all of the steps in 1.1 but I dont have option to check a box to "Create a new Git repository." Is there a setting in VS that I need to do in order to enable Git? Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92bb4dc5-b036-60f4-37aa-8b28b092cac9
* Version Independent ID: 06f64682-5a5a-2aa8-face-14ecc6823038
* Content: [Tutorial - Learn Django in Visual Studio, step 1 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-01-project-and-solution#feedback)
* Content Source: [docs/python/learn-django-in-visual-studio-step-01-project-and-solution.md](https://github.com/Microsoft/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-01-project-and-solution.md)
* Service: **unspecified**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
Ah, yes, thanks for pointing out that oversight in the pre-reqs. Open the VS installer, select Modify, and go to the "Individual components" tab. Scroll down to "Code tools" and check the options for "Git for Windows" and "GitHub Extension for Visual Studio". Let me know, though, if those are already selected and you still don't see the checkbox.

**Comment by kraigb** [comment]
And thanks for filing the issue; I do need to update the article, so I appreciate knowing.

**Comment by kraigb** [comment]
Prereqs in the article are updated.
