### ISSUE TITLE
Marking enterprise only content would help professional and community users.

### ISSUE THREAD

**Issue by bmusical** [MicrosoftDocs/visualstudio-docs#8860]
[Enter feedback here]
I am using VS 2022 Professional, and it took me many pages of searching to find out by process of elimination that I can't create code maps and that the documentation is not meant for me. Is there any indication that something is intended for Enterprise only?  I finally found a page stating that pro-versions can only edit and comment, and even that was not clear.  This is apparently why I can't find the  components it directs me to install. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?source=recommendations&view=vs-2022)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/install-architecture-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by anandmeg** [comment]
@bmusical , thanks for your feedback.

Closing this now as this issue and its fix is being tracked by GitHub issue https://github.com/MicrosoftDocs/visualstudio-docs/issues/8938.

Thanks again!
