### ISSUE TITLE
Clarification wanted for ClickOnce's Application Launcher with .NET6/7

### ISSUE THREAD

**Issue by nickkfwong** [MicrosoftDocs/visualstudio-docs#8867]
Hello,
Im doing migration for our WPF app from .NET 4.8 into .NET6 and we publish our app through ClickOnce.

After reading the migration doc,
I understood the ApplicationDeployment class is removed and so I followed the guideline to add a custom class to read them back from Environment variables.

One thing written in the page is that an app launcher is created starting with .NET7 and it will be responsible to set the "ClickOnce_*" variables for the app to read.

My first question here is, if I target my app to .NET6, does the launcher work still?

To test this out, I created a simple app targeted on .NET6, on my dev machine which have .NET7 & latest VS installed. 
I can see the launcher is created and can be published.
When I run this sample app through CO on a client machine which only have .NET6 runtime installed, I can see the "ClickOnce_*" environment variables, as expected.

By experiment, it seems to work. But since I can't any more document talking about ..."having a CO deployed app built with .NET7 sdk but targeted to run on .NET6", I just want some clarification if this is completely ok or might cause potentially issue?

My second question is, before the migration we already use CO to deploy our app.
When we migrate the app with a newer application deployment file, does the update work seamlessly? (ie. do we need to delete the previous installation (app on .NET4.8) in order to install the new one (app on .NET6)?) 

I haven't tested till this step yet, but I notice there is an entry point listed in the application manifest (app.dll.manifest).

Thanks in advance for your help.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4d06a354-685e-5465-f4a6-254524b6658e
* Version Independent ID: 4d06a354-685e-5465-f4a6-254524b6658e
* Content: [Access ClickOnce deployment properties for .NET - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/deployment/access-clickonce-deployment-properties-dotnet?view=vs-2022)
* Content Source: [docs/deployment/access-clickonce-deployment-properties-dotnet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/access-clickonce-deployment-properties-dotnet.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@nickkfwong Asking about this

**Comment by nickkfwong** [comment]
> @nickkfwong Asking about this

@Mikejo5000 Any chance you might find anything on this topic from the wider team?
I think at least it would be good to know which target framework `Launcher.exe` is built against of, although the doc mentioned the command for adding launcher is only available after SDK7, it would be safe for us if the exe is fully compatible with .NET6.

**Comment by Mikejo5000** [comment]
@nickkfwong I have not heard back on this issue, and am asking again. My best suggestion is that you use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the question/issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
@nickkfwong Response from the team: You can use any .NET SDK to build ClickOnce deployment for apps that target older .NET releases. I.e. if customer has .NET 7 SDK, they can build ClickOnce deployment using dotnet-mage 7.0, to deploy apps that target 7.0 or older .NET (all the way back to 3.1).
