### ISSUE TITLE
excellent tutorial

### ISSUE THREAD

**Issue by PaulArvada** [MicrosoftDocs/visualstudio-docs#8873]
Thanks for creating the python tutorial

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2103a566-905f-f3a1-08b6-a07d076398ad
* Version Independent ID: 926343f9-0e59-1991-473c-f604ab369eb5
* Content: [Python in Visual Studio tutorial step 6, work with Git](https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git?view=vs-2022)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/tutorial-working-with-python-in-visual-studio-step-06-working-with-git.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by WilliamAntonRohm** [comment]
@PaulArvada -- Paul, you're welcome!
