### ISSUE TITLE
Misleading text

### ISSUE THREAD

**Issue by kmustang** [MicrosoftDocs/visualstudio-docs#8883]
The Modify Selection button operates on an item in the toolbar, not the toolbar itself:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/4107808/214386631-a76fbf69-f040-450f-9cdd-cacd1ca145bb.png">

I would like to move a "sub-toolbar" from one toolbar to another, but there does not appear to be a way to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49fe9dd7-3720-5ea9-6c5a-7bde27cb993e
* Version Independent ID: c7c693df-ef68-dc9f-268e-ffac03132a29
* Content: [Customize menus and toolbars - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-customize-menus-and-toolbars-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-customize-menus-and-toolbars-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-customize-menus-and-toolbars-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@kmustang We appreciate your feedback. We've updated the page to correct for the error you noted. We'll close this issue now with our thanks to you for your help in improving the documentation! (An addendum: If there's something you think the product should do but currently doesn't, i.e. provide a way to move a sub-menu from one toolbar to another, please consider creating a request by using the [Suggest a Feature](https://learn.microsoft.com/visualstudio/ide/suggest-a-feature) tool.)
