### ISSUE TITLE
VS has a dialog box that says "To restore these packages, fix your layout from the command line. How do I fix my layout?" and links me to this page

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#8895]
...but I dont see on here what its specifically talking about. 

This is the full error screenshot
![image](https://user-images.githubusercontent.com/15381181/215123731-3ccbe428-3d9f-4e40-9b60-15f411bc4378.png)

I dont know if the docs are just missing these instructions or the product is errantly linking to this page. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc51a257-b7a9-4660-7e12-88cdfcd9cd53
* Version Independent ID: dad2fd97-7244-6802-e853-5d5974838996
* Content: [Update a network-based installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019#fix-a-layout)
* Content Source: [docs/install/update-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/update-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@StingyJack, thanks for bringing this issue to our attention. Looks like the destination of the link is incorrect. The link should point to the following: [Fix a layout](https://learn.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2019#fix-a-layout)

We're tracking this bug to fix at our end. Thanks again!
