### ISSUE TITLE
Can not use DisplayAttribute in T4 template

### ISSUE THREAD

**Issue by testmabnanet** [MicrosoftDocs/visualstudio-docs#8898]
In my custom T4 template I have to read DisplayAttribute of a type. But I'm keep getting different errors after struggling with several solutions. Here is part of my .tt file :

```
<#@ template debug="true" hostspecific="true" language="C#" compilerOptions="/langversion:10" #>
<#@ assembly name="System" #>
<#@ assembly name="System.Runtime" #>
<#@ assembly name="System.Core" #>
<#@ assembly name="System.ComponentModel.Annotations" #>

<#@ import namespace="System" #>
<#@ import namespace="System.Reflection" #>
<#@ import namespace="System.Runtime" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ import namespace="System.ComponentModel.DataAnnotations" #> 
<#@ output extension=".cs" #>

<#
    static string GetEnumValueDisplayName(Enum value)
    {
        Type type = value.GetType();
        MemberInfo[] memInfo = type.GetMember(value.ToString());
        DisplayAttribute? dispalyAttribute = null;
        if (memInfo != null && memInfo.Length > 0)
        {
            object[] attrs = memInfo[0].GetCustomAttributes(typeof(DisplayAttribute), false);

            if (attrs != null && attrs.Length > 0)
                dispalyAttribute = attrs[0] as DisplayAttribute;
        }
        return dispalyAttribute?.Name ?? "";
    }
#>


<#
 foreach(myEnum en in Enum.GetValues(typeof(MyEnum)))
 {#>
          public static class <#=@en.ToString()#> { public const string Value = "<#=@en.ToString()#>";public const string Text = "<#=@GetEnumValueDisplayName(en)#>";}
<#}#>
```

And here is my compile time error :

_Compiling transformation: The type name 'DisplayAttribute' could not be found in the namespace 'System.ComponentModel.DataAnnotations'. This type has been forwarded to assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' Consider adding a reference to that assembly._

I am using .net 6 with Visual Studio 2022(17.0.4).

[stackoverflow link](https://stackoverflow.com/questions/75275533/can-not-use-displayattribute-in-t4-template?noredirect=1#comment132831817_75275533)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 26fa83b1-ca9d-0800-423b-ce6f4a1668a8
* Version Independent ID: fc5869c5-4d4b-bba3-1c32-caf9d13dfd21
* Content: [Code Generation and T4 Text Templates - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2022)
* Content Source: [docs/modeling/code-generation-and-t4-text-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/code-generation-and-t4-text-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
Same response as on SO:

> I am using .net 6

That would be a problem. The VS T4 engine only supports .NET Framework at this point, which means that it cannot load any .NET Core libraries during the transformation. We have started working on a .NET Core version of the engine but there is no ETA on when this would become available. Any updates would be communicated through this [Suggestion Ticket](https://developercommunity.visualstudio.com/content/idea/881587/support-loading-of-net-core-libraries-in-t4-templa.html).

**Comment by WilliamAntonRohm** [comment]
@testmabnanet -- thank you for your thorough feedback.

@mgoertz-msft -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
