### ISSUE TITLE
kurtulan

### ISSUE THREAD

**Issue by huso88kurtulan** [MicrosoftDocs/visualstudio-docs#8900]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4153ba00-a317-3b68-89c4-37e6f5db9804
* Version Independent ID: 4153ba00-a317-3b68-89c4-37e6f5db9804
* Content: [How to deploy an app into a container in the cloud with Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/containers/deploy-containerized?view=vs-2022)
* Content Source: [docs/containers/deploy-containerized.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/deploy-containerized.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@huso88kurtulan -- thank you for your feedback.  I am unsure of your request, and so I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
