### ISSUE TITLE
Issue with following tutorial

### ISSUE THREAD

**Issue by vijayiyer97** [MicrosoftDocs/visualstudio-docs#8913]
[Enter feedback here]
Selecting the "Standalone JavaScript React Template" runs a script file that fails due to a restriction with npx. The issue is the script attempts to create a temp react project using the "create-react-app" command with npx producing an error that says "npx cannot create project" and "project name cannot contain capital letters".

for reference here is my device specs, and installed pkg versions

Device Info:
Device name	IYERS-OMEN-6H7
Processor	11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
Installed RAM	32.0 GB (31.6 GB usable)
Device ID	        EDF1861A-84EF-4407-848B-7A460E2D55EA
Product ID	00330-81485-61560-AA545
System type	64-bit operating system, x64-based processor

OS Info:
Edition	Windows 11 Pro
Version	21H2
Installed on	‎8/‎22/‎2022
OS build	22000.1165
Experience	Windows Feature Experience Pack 1000.22000.1165.0

Software Info:
Visual Studio 2022 (64-bit) Version 17.4.4
.NET 7.0
node.JS v18.13.0
npm 8.19.3
npx 8.19.3
npx create-react-app 5.0.1

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@vijayiyer97 -- Vijay, thank you for your detailed feedback.  This seems more product-related than documentation-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
