### ISSUE TITLE
ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by salavatov** [MicrosoftDocs/visualstudio-docs#8922]
On VS2022 and Node.js v18.14.0 transpile step fails without following option

`set NODE_OPTIONS=--openssl-legacy-provider`
-or-
`"scripts": { "build": "set NODE_OPTIONS=--openssl-legacy-provider && webpack-cli ./app.tsx --config webpack-config.js" }`

Or Node.js needs to be downgraded to v16

Reference: [https://github.com/webpack/webpack/issues/14532#issuecomment-947012063](url)

**Comment by WilliamAntonRohm** [comment]
@salavatov -- Konstantin, thank you for your feedback.  Are you following a particular learn.microsoft.com article?

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
