### ISSUE TITLE
Exit full-screen keys not working

### ISSUE THREAD

**Issue by aananthcn** [MicrosoftDocs/visualstudio-docs#8924]
Alt+Shift+Enter butten as described in the page didn't work for me. But F11 worked! Please correct this page or add more hints.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68544507-42a5-6364-b7e2-17115bd5c88d
* Version Independent ID: e588245e-c033-32a1-18b8-8bb81d7461fe
* Content: [Full screen and virtual space mode - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-manage-editor-modes?view=vs-2022)
* Content Source: [docs/ide/how-to-manage-editor-modes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-manage-editor-modes.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@aananthcn Thanks for letting us know. We've updated the article to include the correct keyboard shortcut combo (**Shift**+**Alt**+**Enter**) along with more info about the relationship between commands and their keyboard shortcuts (and how to how to view, verify, or change a keyboard shortcut if you choose to). We also added a link to the master list of keyboard shortcuts that apply to Visual Studio as a whole. 

We'll close this issue now, with our further thanks to you for your help in improving the Visual Studio documentation!
