### ISSUE TITLE
Unactionable and therefore useless

### ISSUE THREAD

**Issue by boomalator** [MicrosoftDocs/visualstudio-docs#8929]
I originally said there was no instructions to find the tool. I see since I was mistaken.

I think i glossed over it because of the ridiculous idea that in order to remove a installation, which gives a very unhelpful "something went wrong" error, the required step is to first install it.... which isn't working either. Really, someone actually suggested and then someone else signed off on a plan that said "when the really complicated installer fails to install or uninstall a product, we'll get the user to install the product so that they can then have the uninstaller".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dac42ba7-edf2-06fb-dc6a-13a0c47b43c5
* Version Independent ID: 98b5c39a-ff89-f4c8-ef77-ae239564998a
* Content: [Uninstall or remove Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/uninstall-visual-studio?view=vs-2022)
* Content Source: [docs/install/uninstall-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/uninstall-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@boomalator -- BP, thank you for your feedback.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
