### ISSUE TITLE
No option "Keep modified files open after Replace All" in Replace in Files window.

### ISSUE THREAD

**Issue by SylwesterZarebski** [MicrosoftDocs/visualstudio-docs#8933]
Documentation page is mentioning option "Keep modified files open after Replace All", but in VS 2022 there are no such option.
Current Replace in Files window is:
![obraz](https://user-images.githubusercontent.com/1755531/217233472-1e7f1509-4bc5-428b-9839-7f1404854fd2.png)

VS 2022 in version 17.4.4.
Please update documentation.

PS. There are discussion about removed option, but while this is discussed docs should be updated accordingly:
https://developercommunity.visualstudio.com/t/Keep-modified-files-open-after-replace/10195256?q=Keep+modified+files+open+after+Replace+All
Please also look at answer mentioning removed option:
https://developercommunity.visualstudio.com/t/Replace-all-not-replacing-occurrences/10148690#T-N10149904

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59a29e77-60f1-25d9-0bfb-6f364d0eab55
* Version Independent ID: 10f80429-0596-3c6e-cb55-957462f50785
* Content: [Replace in files - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/replace-in-files?view=vs-2022)
* Content Source: [docs/ide/replace-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/replace-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@SylwesterZarebski Thanks for letting us know and for the detailed info you provided. We've updated the page; we'll close this issue now with our additional thanks for your help with improving the Visual Studio documentation!
