### ISSUE TITLE
`CustomAfterMicrosoftCommonTargets` is missing from the docs

### ISSUE THREAD

**Issue by TymurGubayev** [MicrosoftDocs/visualstudio-docs#8937]
After the `CustomBeforeMicrosoftCommonTargets` the **after** version of the property should be mentioned.

https://github.com/MicrosoftDocs/visualstudio-docs/blob/b01fbed63a61e5b8fda0adc5a1dac86df6322477/docs/msbuild/common-msbuild-project-properties.md?plain=1#L53

**Comment by WilliamAntonRohm** [comment]
@TymurGubayev -- Timur, thank you for your suggestion.

@ghogen -- Gordon, please review this addition in [private PR 10887](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/10887).
