### ISSUE TITLE
Missing Description 

### ISSUE THREAD

**Issue by GGabc** [MicrosoftDocs/visualstudio-docs#8942]
[The article did not describe what the symbols ⌥  and ⇧ mean.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c5180cb1-401a-66b4-890d-acc3f741b9a3
* Version Independent ID: b73e9808-ac17-ab15-c597-87a7c16fd96c
* Content: [Multi-caret editing - Visual Studio for Mac](https://learn.microsoft.com/en-us/visualstudio/mac/multi-caret-editing?view=vsmac-2022)
* Content Source: [mac/multi-caret-editing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/multi-caret-editing.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by WilliamAntonRohm** [comment]
@GGabc -- thank you for your feedback.  ⌥  is the Option/Alt key, and and ⇧ is either Shift key.  I am updating this article.
