### ISSUE TITLE
Link to Visual Studio 2022 Remote toools broken

### ISSUE THREAD

**Issue by heretic13** [MicrosoftDocs/visualstudio-docs#8946]
Unable to download Remote Tools for VS2022

**Comment by WilliamAntonRohm** [comment]
@heretic13 -- Yaroslav, please try this link:
- [Download and Install the remote tools](https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2022)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by heretic13** [comment]
This link not work. It's redirect me to https://visualstudio.microsoft.com/ru/
Tested on Chromium, Edge, Tor on two computers.

**Comment by heretic13** [comment]
Worked after switching Tor to English.
Blocking the download based on the language in the browser?

Interesting. Is this an official Microsoft policy???

**Comment by WilliamAntonRohm** [comment]
@heretic13 -- Yaroslav, I'm glad it is working for you.  I changed the language identifier in my URL from en-us to ru-ru and got the correct download page in Russian:
- https://learn.microsoft.com/ru-ru/visualstudio/debugger/remote-debugging?view=vs-2022

**Comment by heretic13** [comment]
This page (https://learn.microsoft.com/ru-ru/visualstudio/debugger/remote-debugging?view=vs-2022) contains a description of the tools and a lot of other documentation.
She's fine.

It contains the same download link - https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2022

And this page makes a redirect, provided that the language in the browser is Russian (not the URL, but the language of the browser).
I just changed the page priority in Edge. I made it so that pages in English are shown first, and only then pages in Russian. After that, the tool download page opened normally.

However, the fact of discrimination based on language has been proven (at least for me). :)

Perhaps another department (not the documentation department) deals with problems with Microsoft download servers, but you could send a bug report to them.
