### ISSUE TITLE
This page has the standard links at the bottom for feedback but the This Product button doesnt take users to where they can report feedback about the product.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#8948]
It just takes them to the forum where they can report a problem or request a feature for Visual Studio, VS Mac, .NET, C++, AzDo, AzDo Server, DevBox, and Az Load testing. There is no separate space for the reporting problems or suggesting features for the feedback tools themselves. 

So if you are having a problem with the tools for any reason (like if you cant report a problem), there is really nowhere to report that is happening.. IMO the "This Product" button on this page should be disabled or removed until there is a system in place to support it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85fb6cbc-bab9-2aa9-d462-fad147bb0b6d
* Version Independent ID: 594fc9a0-560b-5672-7bc1-ff8406bdda0d
* Content: [Developer Community guidelines - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/developer-community-guidelines?WT.mc_id=visualstudio_community_aka_vsfeedbackguidelines&view=vs-2022)
* Content Source: [docs/ide/developer-community-guidelines.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/developer-community-guidelines.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by madskristensen** [comment]
@jasonchlus this is the same feedback we've heard before where DevCom doesn't have a dedicated space for itself. It's not intuitive to report a problem/request a feature about DevCom itself to the Visual Studio space. I wonder if we should look into adding DevCom as a separate space?

@StingyJack thanks for the prompt

**Comment by madskristensen** [comment]
@WilliamAntonRohm can you assign @jasonchlus instead of me? He's now the owner of the Developer Community.

**Comment by WilliamAntonRohm** [comment]
#reassign:jasonchlus

**Comment by StingyJack** [comment]
Not being able to report issues with the feedback tools themselves is still a relevant issue.

**Comment by StingyJack** [comment]
The bot is neither constructive or useful.

**Comment by j-martens** [comment]
Hi @StingyJack , I tried the link and it does send me over to the Developer Community. Are you still seeing the issue? 
You can also see how to provide feedback here: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022

Have a good day.

**Comment by StingyJack** [comment]
@j-martens - The product in this case is the developer community site. I've wanted to report a problem with it on several occasions, but when I click that button I get sent to the site that I'm having a problem with in the first place, and there is no "space" or category to report problems with the site, moderators, or other staff.

Its a dead end for anyone having a legitimate problem.

**Comment by j-martens** [comment]
Thank you, @StingyJack, for the context.   @madskristensen / @jasonchlus - can an update be provided on the avenue to provide feedback on the Developer Community's site design or operations? 

Noting that this feedback is not about this article or content on the Learn site. It is feedback about the Dev. Community site.
