### ISSUE TITLE
Logger output does NOT appear in the Output Window

### ISSUE THREAD

**Issue by abdekker** [MicrosoftDocs/visualstudio-docs#8950]
[Enter feedback here]

The article states:
"The Logger class contains static methods to write to the Output Window."

This is not correct.

Using Visual Studio Professional 2019 v16.11.16 with a C++ "Native Unit Test Project" project. When the tests are debugged or just run, Logger::WriteMessage("my message"); commands are not displaying anything in the Output Window.

I raised this issue on StackOverflow:
https://stackoverflow.com/questions/75439723/microsoft-native-unit-test-for-c-where-is-the-logger-output-going

Someone pointed out in a comment that the output is actually displayed in the "Test Detail Summary" section of Test Explorer. They tried this is Visual Studio 2022. I can confirm this is where my messages are being displayed in VS 2019 as well.

The documentation is wrong and misleading. Also, the feature is not very usable. In order to see the summary, you have to allow the whole test to complete, and you cannot see the message "live" as you debug. This might be its' intended use, in which case the documentation might point this out.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51e3ec17-4193-8059-56de-fbad2fab239c
* Version Independent ID: e0e84806-41ff-fa5e-1aa1-775beed16d78
* Content: [Microsoft.VisualStudio.TestTools.CppUnitTestFramework API - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference?view=vs-2022#logger)
* Content Source: [docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/microsoft-visualstudio-testtools-cppunittestframework-api-reference.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by abdekker** [comment]
The issue (incorrect documentation) is still valid and should (hopefully) be actioned.

**Comment by WilliamAntonRohm** [comment]
@abdekker -- thank you for your follow-up.

@TylerMSFT -- please look into this issue.

**Comment by TylerMSFT** [comment]
Will do, but this is lower on my priority list and my list is very long right now. I will mark this as triaged and get to it as I'm able.
