### ISSUE TITLE
Wait parameter is not documented (or working)

### ISSUE THREAD

**Issue by LadyCailin** [MicrosoftDocs/visualstudio-docs#8960]
When running `VSInstaller.exe --help`, it mentions the existence of a `--wait` parameter. In fact, this might rightly be undocumented on this page, because it doesn't do anything. However, if the feature has been removed, it should be removed from the `--help` documentation. (Or, ideally, if it's simply broken, a bug should be filed against the installer, and it should also be added to this page.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@LadyCailin -- Lady Cailin, thank you for your well-considered feedback.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@anandmeg -- Megha, please look into this potential documentation issue.

**Comment by anandmeg** [comment]
@LadyCailin, thanks your feedback. Can you please share some more info on the scenario where `--wait` failed for you?

Here's some help info on `--wait` usage:
-  `--wait` is documented in the [Layout command and command-line parameters]((https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022#layout-command-and-command-line-parameters)) table on  the [Use command-line parameters to install, update, and manage Visual Studio page](https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022#layout-command-and-command-line-parameters).
- Check out an [example usage of `--wait` command](https://learn.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2022#using---wait).

If you're running into a case where `--wait` is failing for you, please report your issue using the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool.

Thanks!

**Comment by LadyCailin** [comment]
Ah! I missed it, I'm seeing it now with Ctrl-F. Anyways, it's not working, so I will report a problem, but it sounds like you're saying that it definitely should work, in which case it is for sure a bug, not a documentation problem. Thanks!
