### ISSUE TITLE
Missing link to the actual Targets values

### ISSUE THREAD

**Issue by PierreChetelat** [MicrosoftDocs/visualstudio-docs#8963]
Hello,
It would be nice to have a link to what values are possible for those targets, it's not that easy to find out as it's only in github repository ! Would be even nicer to have all provided values by .NET with a small human description.
Here's the link that I was searching for https://github.com/dotnet/sdk/blob/main/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Publish.targets#L359

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 72a67233-ab6a-e330-7b2d-21c95dd9caba
* Version Independent ID: 381c76df-d847-6ee0-b16e-c7bbc52cec13
* Content: [MSBuild Targets - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-targets?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-targets.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-targets.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
OK, this might be more appropriate for the .NET SDK documentation, but it makes sense that it needs to be covered somewhere.
