### ISSUE TITLE
Describe different between tmLanguage in Visual Studio and Visual Studio Code

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/visualstudio-docs#8964]
ITNOA

Many different between tmLanguage in Visual Studio and Visual Studio Code (for example supporting on `firstLineMatch` [Why grammar does not highlight keyword](https://stackoverflow.com/a/73288423/1539100) ). I think it is very essential to describe all different in supporting features and concepts (for example I do not find that [Visual Studio supported injection grammars](https://stackoverflow.com/q/75474952/1539100) or etc.)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* Content: [Add editor support for other languages - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages?view=vs-2022)
* Content Source: [docs/ide/adding-visual-studio-editor-support-for-other-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@soroshsabz -- thank your for your feedback.  I have upvoted this `tmlanguage` issue:
- https://developercommunity.visualstudio.com/t/Support-firstLineMatch-in-tmlanguage-for/10281813

It is impractical to describe every difference between Visual Studio and VS Code.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by soroshsabz** [comment]
@WilliamAntonRohm I think every user need to know about all constraints about tmLanguage support in Visual Studio, for example some major feature like [injection grammar](https://stackoverflow.com/q/75474952/1539100) or something else

@TerryGLee I think this issue is not close, but add comprehensive documentation about tmLanguage feature support by Visual Studio

thanks

**Comment by soroshsabz** [comment]
@WilliamAntonRohm Do you can get me your note about my last note

> I think every user need to know about all constraints about tmLanguage support in Visual Studio, for example some major feature like [injection grammar](https://stackoverflow.com/q/75474952/1539100) or something else

and if you agree with me, please reopen this issue, and if you disagree with me, please give me your cause to better understant

I do not find any place to learn tmLanguage feature gap in Visual Studio and then I do not know how to write my own extension for supporting my new language

thanks

**Comment by WilliamAntonRohm** [comment]
@soroshsabz -- thank you for your followup.  Your questions are outside the scope of our existing and planned documentation.  Please consider these resources:
- Ask a question or find an answer on the [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/176/vs) page for Visual Studio.
- Report product issues to the engineering team via the [Report a problem](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.
- Track product issues and engineering team responses in the [Visual Studio Developer Community](https://aka.ms/feedback/suggest?space=8).

**Comment by soroshsabz** [comment]
Thanks for response, but as I say before, Visual Studio 2022, does not support completely [Syntax Highlight Guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide), So I think Microsoft must writes document and describe the scope of support of TML
