### ISSUE TITLE
Add documentation about adding icon based on file type extension

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/visualstudio-docs#8966]
ITNOA

Hi,

I think it is good to add documentation about adding icon for specific new language file based on file type extension

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 02810ab3-cd5b-c837-b6b7-ab1090aa3577
* Version Independent ID: b245aa2a-1fe8-5c7b-342b-ca9c7c0252c5
* Content: [Add editor support for other languages - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/adding-visual-studio-editor-support-for-other-languages?view=vs-2022)
* Content Source: [docs/ide/adding-visual-studio-editor-support-for-other-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/adding-visual-studio-editor-support-for-other-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by soroshsabz** [comment]
related to https://stackoverflow.com/q/75481734/1539100

**Comment by soroshsabz** [comment]
I think it is related to https://learn.microsoft.com/en-us/visualstudio/extensibility/internals/manifest-from-resources?view=vs-2022

**Comment by WilliamAntonRohm** [comment]
@soroshsabz -- thank you for your continued interest and thorough feedback.  What does ITNOA indicate?

@TerryGLee -- please look into this issue.

**Comment by TerryGLee** [comment]
This has been reported as a product bug here: https://developercommunity.visualstudio.com/t/New-icon-for-custom-file-type-is-not-d/10283644

**Comment by WilliamAntonRohm** [comment]
@soroshsabz -- please try this download to get predefined icons you can use with Visual Studio:
- [Visual Studio Image Library](https://www.microsoft.com/en-us/download/details.aspx?id=35825)

For example, that download includes:

![image](https://user-images.githubusercontent.com/27738025/220719905-39660c7f-fb98-44e5-880f-dddc4788da2f.png)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by soroshsabz** [comment]
@WilliamAntonRohm thanks for reply me, but i think you do not close this issue, because in this issue, I want to say, that Microsoft add developer documents about adding Icon to new file type based on extension in Visual Studio extension.

I do not think add this document in docs.microsoft.com so I think this issue is reopen again.

thanks
