### ISSUE TITLE
Incorrect Visual Studio version information for 17.4.5

### ISSUE THREAD

**Issue by craigktreasure** [MicrosoftDocs/visualstudio-docs#8969]
The recent update for the release of VS 17.4.5 on February 14, 2023 was entered incorrectly as 17.4.4. There are now two entries for 17.4.4. The most recent version number should be 17.4.5.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ea27919-8e31-6592-9b9e-9a0cabb0a7ff
* Version Independent ID: 093eeeb2-0306-4af9-2bfc-6d4eefbebf9b
* Content: [Visual Studio build numbers and release dates](https://learn.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates?view=vs-2022)
* Content Source: [docs/install/visual-studio-build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/visual-studio-build-numbers-and-release-dates.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@craigktreasure Thanks for letting us know and for the PR, too, which will get merged and then published today.
