### ISSUE TITLE
Visual Studio Installer Microsoft R Client very old

### ISSUE THREAD

**Issue by swayson** [MicrosoftDocs/visualstudio-docs#897]
Hi there,

I am trying to install a version of R. In particular, 3.4. However, the VS2017 installer dialog window only shows 3.3.2. This is a rather old version, how do I overcome this?

I have tried installing the Microsoft R Client directly from Microsoft. But offline installation keeps failing. I am behind corporate firewall, so need to install either offline or through VS installer.

Please advise.

**Comment by gewarren** [comment]
@TerryGLee or @kraigb do you know how @swayson can install a newer version of R tools?

**Comment by kraigb** [comment]
@jflam Do you have suggestions?

**Comment by swayson** [comment]
@kraigb yep, have tried following those direct links, however, they try and download more data from a server which the corporate firewall blocks. There are other instructions on how to install it in a offline fashion, but they also fail, because again, they try and download more data from a server, its like the offline mode doesn't activate. I have tried this with admin rights as well. Same story.

Is this part of the log insightful? 

MSI (s) (10:CC) [13:46:32:408]: Windows Installer installed the product. Product Name: Microsoft R Client. Product Version: 3.4.3.0. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 1603.

VS installer still points to older versions.

**Comment by kraigb** [comment]
Thanks. Am investigating.

**Comment by swayson** [comment]
Any news on this?

**Comment by kraigb** [comment]
Not yet...I'm still waiting to hear back from the engineering team.

**Comment by kraigb** [comment]
@swayson Ultimately what needs to change here is that the VS installer should reference the newer version. Because that's a product and not a documentation issue, please file issue on https://github.com/Microsoft/rtvs/issues (and refer to this present doc issue). That way you'll be in the conversation directly with the engineering team.

In the meantime, I'm closing this issue in the docs repo here. Thanks.

**Comment by swayson** [comment]
Finally got this to work.

1. Copy the following files to your temporary directory.
	MLM_9.1.0.0_1033.cab
	SRS_9.3.0.0_1033.cab
	SRO_3.4.3.0_1033.cab

2. To access the temporary directory open windows explorer and enter the address %TEMP%. Now paste those files in there

3. Close any running visual studio 2017 process that may be open.

4. Now run the RCLientSetup.exe file.

5. After the installation successfully completes open Visual Studio 2017.

6. Enable the newly Microsoft Client as your R interpreter. (i.e. Microsoft R Client (3.4.3.0))

7. You may experience strange UI errors in Visual Studio R Interactive Window.

8. Close Visual Studio 2017.

9. Go to C:\Users\[YOUR_USERNAME]\AppData\Local\Microsoft\VisualStudio

10. Now delete any 15.*** directories that may be in there.

11. Open Visual Studio 2017.

**Comment by kraigb** [comment]
Glad to hear it, and thanks for writing all the details! Issues here do appear n the docs page, so others will benefit from your sharing!
