### ISSUE TITLE
 "Standalone Javascript React Project" template script and case sensitivity error

### ISSUE THREAD

**Issue by taleleuma** [MicrosoftDocs/visualstudio-docs#8978]
[Enter feedback here]
I followed the steps.  When used "Standalone Javascript React Project" template, VS Studio throws a following script error:
I updated VS Studio 2022 but same error when used that template. 

```
Cannot create a project named "tempProjectCreation" because of npm naming restrictions:
  * name can no longer contain capital letters
Please choose a different project name.
Press any key to continue . . .

```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f741cc8-668b-dde5-4fa4-5d775508265f
* Version Independent ID: 86cc0d4f-89a3-de59-55ee-168f4bf15a00
* Content: [Create a React app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-create-react-app?view=vs-2022)
* Content Source: [docs/javascript/tutorial-create-react-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-create-react-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by taleleuma** [comment]
just to make sure, I am clear:  tempProjectCreation is not my project name but a name that VS 2022 template used inside its script.

**Comment by WilliamAntonRohm** [comment]
@taleleuma -- thank you for your feedback and clarification.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@Mikejo5000 -- please look into this potential documentation issue.

**Comment by taleleuma** [comment]
Thank you. will do. Looks like, Visual Studio 2022 version 17.5.0  (that got released yesterday!!!) solved this issue. What a coincidence!
