### ISSUE TITLE
Missing link for the vs_community.exe bootstrapper.

### ISSUE THREAD

**Issue by mikeh36** [MicrosoftDocs/visualstudio-docs#8979]
There is no link for the vs_community.exe bootstrapper file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022#download-the-visual-studio-bootstrapper-to-create-the-network-layout)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@mikeh36 - Mike, thank you for your feedback.  I am updating this article.  The link is:
- https://aka.ms/vs/17/release/vs_community.exe

**Comment by mikeh36** [comment]
Hi @WilliamAntonRohm Is the link going to ever actually be added to the article? It's been almost two months since I raised the issue.

**Comment by WilliamAntonRohm** [comment]
@mikeh36 -- Mike, the Community Edition is not typically licensed for network distribution, which requires an Enterprise license:
- [Software License Terms](https://visualstudio.microsoft.com/license-terms/vs2022-ga-community)

**Comment by mikeh36** [comment]
@WilliamAntonRohm We're educational so we fall under 1b-v I believe. We deploy it for our student labs through ConfigMgr as student's can't install it themselves. But to be able to do a silent install you need to have the offline files. And using your argument then Pro shouldn't be linked either.

**Comment by WilliamAntonRohm** [comment]
@mikeh36 -- thank you for clarifying.  I am following up internally.
