### ISSUE TITLE
False positive for CA2000

### ISSUE THREAD

**Issue by LukeOwlclaw** [MicrosoftDocs/visualstudio-docs#898]
Warning CA2000 is shown for:

            using (var writer = new Windows.Storage.Streams.DataWriter
            {
                ByteOrder = Windows.Storage.Streams.ByteOrder.LittleEndian
            }
            )
            {
                writer.WriteByte(data);
                return writer.DetachBuffer();
            }

Without simplified object initialization there is no warning:

            using (var writer = new Windows.Storage.Streams.DataWriter())
            {
                writer.ByteOrder = Windows.Storage.Streams.ByteOrder.LittleEndian;
                writer.WriteByte(data);
                return writer.DetachBuffer();
            }

Is this a false positive? The documentation does not mention this case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c370a407-b61d-0de6-6ac4-9b0ab49216b9
* Version Independent ID: a96e421e-65d3-07ba-097e-3feff2b3c677
* Content: [CA2000: Dispose objects before losing scope - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca2000-dispose-objects-before-losing-scope)
* Content Source: [docs/code-quality/ca2000-dispose-objects-before-losing-scope.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca2000-dispose-objects-before-losing-scope.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@LukeOwlclaw Thanks for the feedback; I'll look into this.

**Comment by gewarren** [comment]
@mavasani Can you comment if this is a false positive?

**Comment by mavasani** [comment]
@LukeOwlclaw Can you please let us know how you invoked code analysis? Did you execute "Run Code Analysis" command from Visual Studio analysis menu OR you installed Microsoft.CodeAnalysis.FxCopAnalyzers [NuGet package](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/)? See https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers?view=vs-2017 for the differences. between the two.

You can also try the latest 2.9.x prerelease NuGet package from https://dotnet.myget.org/feed/roslyn-analyzers/package/nuget/Microsoft.CodeAnalysis.FxCopAnalyzers, which has the latest fixes to the CA2000 implementation in the FxCop analyzers package to see if this repros for you. I believe the above case is handled by our latest NuGet package, I will confirm later by reducing your repro further to avoid using Windows.Storage types.

**Comment by jherby2k** [comment]
Using the 2.9.0 analyzers package, i'm getting what I believe are false positives when out parameters return an IDisposable. For example, this one:

```c#
while (Handles.TryDequeue(out var handle))
                handle.Dispose();
```

**Comment by mavasani** [comment]
@jherby2k Note the CA2000 instance for this case is not flagging a dispose leak but is a suggestion to use one of standard recommended dispose pattern (try-finally pattern with a dispose invocation in finally) to protect against future leaks where some code added prior to dispose might not be foolproof against exceptions and cause a leak. Dispose within a finally will protect against such a leak. We probably need an option to tweak whether such suggestions should be reported or not. @gewarren can we port the last reported comment to a separate issue on roslyn-analyzers repo?

**Comment by jherby2k** [comment]
I opened it myself with another repro as well. https://github.com/dotnet/roslyn-analyzers/issues/2245

**Comment by gewarren** [comment]
I think all the issues here have been addressed in one way or another. Please comment if that is not the case.

**Comment by mavasani** [comment]
Yes, please try FxCop analyzers release 2.9.2 to confirm.
