### ISSUE TITLE
Clearly document default values / behaviour

### ISSUE THREAD

**Issue by greg-ww** [MicrosoftDocs/visualstudio-docs#8982]
I spent an infuriatingly long time trying to figure out why visual studio was insisting on running my docker file from the solution directory (causing it to work inconsistently with the default of the docker cli). 

I found out from this article that their is a value called DockerfileContext and that by default it points to the parent directory of the docker file. However it took a very long time to locate this information because the _**only reference to this behavior appears to be in a comment in the example at the bottom of the page**_. 

I feel this is a common kind of issue in visual studio and some other Microsoft products, where a lot of things are set up for me invisibly and I have no way of knowing what these values are and what there defaults might be. So in order to find the property or variable responsible I have to reverse engineer the concept that controls the behavior I am seeing and it's naming enough to be able to google it, and maybe I am lucky and an article covers it. In this particular example I got stuck looking for words like "Path" and "Directory" instead of "Context" and I wasn't sure if it was a docker specific issue or I had somehow messed up a MSBuild Property, which lead me down a painful dead end of dozens of tabs worth of reading.

Ideally I'd prefer if Visual Studio explicitly generated a comprehensive settings file in my project that included the default values being set, as this would streamline the process by giving me one place to look for values relevant to my problem and also save me the step of figuring out where I can modify them. 

But in the meantime I'd appreciate if there could be some kind of consistent format in the documentation for listing the default values / behavior for properties like the ones in this article, perhaps with some styling to make the less intuitive / more important to note ones stand out more. I am also open to other suggestions for how information on behavior like this can be more easily located in Visual Studio / Microsoft docs.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84f968ae-2fa3-06af-06c0-74e122071ce5
* Version Independent ID: af37447f-bb94-abac-c4cc-cac649575d2c
* Content: [Visual Studio Container Tools build properties - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2022)
* Content Source: [docs/containers/container-msbuild-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/container-msbuild-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@greg-ww -- Greg, thank you for your thorough feedback.  For your product suggestions, please add them here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@ghogen -- Gordon, please look into the documentation aspects of this issue.

**Comment by ghogen** [comment]
@greg-ww
This is good feedback, thanks. Some of this will be passed on to the program managers.
As far as the docs, I will look into this and try to find places to add this important information.

**Comment by ghogen** [comment]
@greg-ww
The DockerfileContext is set by Visual Studio and it is set differently for .NET Framework projects than for .NET Core projects. For .NET Framework projects, it is set to "." (the project file), but for .NET Core projects, it it set to ".." (the solution folder, usually). This is to make sure certain build artifacts are included in the container, such as Directory.Build.props which is usually in the solution folder.

I'm adding those default values to the table in this article, and adding a note that explains this.
