### ISSUE TITLE
Setup/FAQ should mention the Winfows Projected Files System requirement.

### ISSUE THREAD

**Issue by OranguTech** [MicrosoftDocs/visualstudio-docs#8985]
[Enter feedback here]
(Possibly this should go in the FAQ page (https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq?view=vs-2022) instead)

Setup/FAQ makes no mention that the [Projected File System](https://learn.microsoft.com/en-us/windows/win32/projfs/projected-file-system) windows feature [must be enabled](https://learn.microsoft.com/en-us/windows/win32/projfs/enabling-windows-projected-file-system).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3113c2af-d97e-7b35-17ce-c675c3dff889
* Version Independent ID: b716c4af-d92b-cb3b-8af0-1b3ada479ac0
* Content: [Live Unit Testing - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2022)
* Content Source: [docs/test/live-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/live-unit-testing.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@OranguTech Thanks for the feedback! Is the projected file system on by default? If not, what is the scenario where this setting must be enabled? @AbhitejJohn fyi

**Comment by Mikejo5000** [comment]
@OranguTech I believe in the current version of LUT, you only need to manually enable ProjFS for Dev Drive support. We just updated the FAQ with that information. Please let me know if we missed anything. Link:
https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq?view=vs-2022#dev-drives

**Comment by OranguTech** [comment]
@Mikejo5000 - thanks, sorry I didn't see/reply to your earlier comment.  I don't know what scenario led to ProjFS not being enabled, I was just trying to use Live Unit Testing on a new-ish install. (That already had dev mode enabled).

This was before DevDrive was even announced/available, so it wasn't in that context.
