### ISSUE TITLE
MSBuildLocator DOES NOT find MSBuild!!!!

### ISSUE THREAD

**Issue by BittermanAndy** [MicrosoftDocs/visualstudio-docs#8993]
MSBuildLocator DOES NOT find MSBuild, which means it FAILS in the basic task stated at the top of the page: you CANNOT use it to match your Visual Studio builds, because it does not find MSBuild installed by any Visual Studio!

Instead, MSBuildLocator ONLY finds dotnet.exe from a DotNet SDK. This is NOT the same as MSBuild and, among other things, means you CANNOT build any projects that depend on Visual Studio extensions, because the DotNet SDK does not know anything about Visual Studio or its extensions!

This is RIDICULOUSLY frustrating and COMPLETELY THE OPPOSITE of what this page claims it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c49ddfdc-ab00-cead-2565-61819c78dcdd
* Version Independent ID: dae11163-768f-fbca-c383-f52112b67402
* Content: [Find MSBuild and use its API - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/find-and-use-msbuild-versions?view=vs-2022)
* Content Source: [docs/msbuild/find-and-use-msbuild-versions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/find-and-use-msbuild-versions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@BittermanAndy -- Andy, thank you for your feedback.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@ghogen -- Gordon, please look into this potential documentation issue.

**Comment by ghogen** [comment]
@BittermanAndy 
That sounds very frustrating. I'm investigating this now. Are you using QueryVisualStudioInstances ?
https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.locator.msbuildlocator.queryvisualstudioinstances?view=msbuildlocator-1.5

**Comment by BittermanAndy** [comment]
@ghogen Yes, QueryVisualStudioInstances, or RegisterDefaults - any of it. Only picks up dotnet SDK versions of MSBuild, not Visual Studio.

I have since learned that the behaviour (undocumented anywhere, and in complete contradiction to the information on this page) is as follows:

- If making a .NET Framework application and the .NET Framework version of MSBuildLocator, it will query will Visual Studio instances, which use a .NET Framework build of the MSBuild libraries. For hopefully-obvious reasons, I'm not making a .NET Framework application, so this is not the behaviour I see.
- If making a .NET application and the .NET version of MSBuildLocator, it will NOT query Visual Studio instances, as the .NET Framework build of the MSBuild libraries provided with Visual Studio cannot be used with .NET. Instead, it locates only the dotnet SDK versions of MSBuild - which know nothing about Visual Studio nor any of its extensions or SDKs, and which are **completely useless** for anyone wanting to build a tool that uses the same MSBuild libraries as Visual Studio, which is what all the documentation incorrectly says MSBuildLocator does.

The response I got on the MSBuildLocator github page was "oh, just rebuild your application in .NET Framework", as though that excuses not mentioning that restriction anywhere, or gives me back my wasted week trying to figure out why this wasn't working, or as if suggesting .NET Framework as a solution isn't an obviously absurd position for Microsoft to take when they're supposedly trying to convince everyone to use .NET 6+ instead.

I am also completely baffled why Microsoft are not eating their own dogfood and using a .NET build of MSBuild in Visual Studio, rather than .NET Framework. (Come to that, I'd like to know what drugs the Microsoft project managers were taking when they decided that .NET Framework 4.7, .NET Framework 4.8, .NET Core, .NET Core 2, .NET Core 3, .NET 5, .NET 6 was a naming sequence that would make sense to any human being on Earth, and it makes every conversation about this kind of thing unnecessarily confusing). All of this, of course, I recognise is out of scope for this ticket or this page of documentation. But if the behaviour really must be as described above, then at least tell us about it!!! On every page of the documentation, in big bold capital letters so no-one will miss it, not secretly in the developers' heads.

**Comment by ghogen** [comment]
@BittermanAndy 
Thanks for the quick follow-up with detailed information. I wasn't aware of that limitation, but after your note, I started to suspect something like that might be the problem. I will make sure to update this article to make that clear.

**Comment by BittermanAndy** [comment]
Thank you.
