### ISSUE TITLE
Confusing example for CS1816

### ISSUE THREAD

**Issue by LukeOwlclaw** [MicrosoftDocs/visualstudio-docs#900]
All code examples include

    GC.SuppressFinalize(this);

This is confusion as the correct and incorrect samples are identical. Only the correct sample should include it. The line could be commented out in the incorrect samples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15926869-1ca4-46de-9552-f0c407ed8f80
* Version Independent ID: 91f3206c-8d88-3740-1e05-73185514b62d
* Content: [CA1816: Call GC.SuppressFinalize correctly - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1816-call-gc-suppressfinalize-correctly)
* Content Source: [docs/code-quality/ca1816-call-gc-suppressfinalize-correctly.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1816-call-gc-suppressfinalize-correctly.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@LukeOwlclaw Thanks for the feedback. I think the incorrect example is trying to show that it's incorrect because it's passing something other than "this" to SuppressFinalize. It should be made more clear, however, so I'll address that.

**Comment by LukeOwlclaw** [comment]
Oops, you are right, it is `GC.SuppressFinalize(this);` vs. `GC.SuppressFinalize(true);`. So there *is* a difference. I did not see that. So, yes, a hint/explanation would be nice.
