### ISSUE TITLE
Error in how link is formatted - includes &lt and &gt

### ISSUE THREAD

**Issue by iUnknwn** [MicrosoftDocs/visualstudio-docs#9002]
There is a bug in how some of the links are formatted on this page:
![image](https://user-images.githubusercontent.com/1129122/221702161-cd401c21-6d0b-4f32-8413-e32a5b7dbdbe.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ed35685d-e409-d962-c450-7297a1f3c003
* Version Independent ID: 224fab0f-fd26-396f-cdd8-921533d2aeba
* Content: [Configure Python web apps for IIS - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/configure-web-apps-for-iis-windows?view=vs-2022)
* Content Source: [docs/python/configure-web-apps-for-iis-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/configure-web-apps-for-iis-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by WilliamAntonRohm** [comment]
@iUnknwn -- Sean, thank you for catching these.  I am updating this article.

**Comment by WilliamAntonRohm** [comment]
@iUnknwn -- Sean, upon investigation, this is an issue with the rendering engine, rather than a documentation error.  Please add it here:
- https://aka.ms/sitefeedback

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
