### ISSUE TITLE
Bug in the full Example of product.xml

### ISSUE THREAD

**Issue by matanj83** [MicrosoftDocs/visualstudio-docs#9005]
In the following section:
```xml
 \<InstallChecks>
    <MsiProductCheck Product="IsMsiInstalled"
      Property="{XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}"/>
  </InstallChecks>
```
"Product" and "Property" are swapped.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9d1385b1-f794-fec6-852f-0645e39872bd
* Version Independent ID: a2a295a9-6233-835b-f24f-fa11a2d36202
* Content: [Create a Product Manifest - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/deployment/how-to-create-a-product-manifest?view=vs-2022)
* Content Source: [docs/deployment/how-to-create-a-product-manifest.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/how-to-create-a-product-manifest.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@matanj83, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
