### ISSUE TITLE
Autocomplete is missing the <OnError> option in VS 2022 (Version 17.5.0)

### ISSUE THREAD

**Issue by dsorak** [MicrosoftDocs/visualstudio-docs#9008]
This option does not appear in autocomplete/suggestions when editing the project file within Visual Studio Version 17.5.0. Having a incomplete list is almost as detrimental as having none at all. If I cannot see all the options, I do not have a full picture of what is available and may decide that the processing I am attempting is not possible, or worse, spend valuable time attempting to accomplish that I need in the wrong way. PLEASE FIX.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89361327-5787-0055-75ec-76d6d89fc96e
* Version Independent ID: 02a0bc56-020a-4a4b-5629-cb3709a4be2c
* Content: [OnError Element (MSBuild) - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/onerror-element-msbuild?view=vs-2022)
* Content Source: [docs/msbuild/onerror-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/onerror-element-msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@dsorak -- Dan, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @ghogen for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
