### ISSUE TITLE
Not working in VS 2017

### ISSUE THREAD

**Issue by samsudeenks** [MicrosoftDocs/visualstudio-docs#901]
Will this not work in VS 2017?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9422755-824a-b8b0-3da4-063b10ecaf44
* Version Independent ID: d4bfd8d2-d97c-1a71-579f-d677cdae6b94
* Content: [How to: Build to a common output directory - Visual Studio](https://docs.microsoft.com/en-in/visualstudio/ide/how-to-build-to-a-common-output-directory)
* Content Source: [docs/ide/how-to-build-to-a-common-output-directory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/how-to-build-to-a-common-output-directory.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@samsudeenks I'll look into this and get back to you.

**Comment by samsudeenks** [comment]
This happens only when connected to Mac agent for building Xamarin.Forms for iOS project.

**Comment by gewarren** [comment]
@conceptdev can you look into this Xamarin issue?

**Comment by conceptdev** [comment]
@samsudeenks if you are experiencing issues with Xamarin or Visual Studio, please use the **Help > Report a problem** menu item or visit [Developer Community](https://developercommunity.visualstudio.com/). This will guide you create a report so that we can investigate and fix any problems. Thanks!
