### ISSUE TITLE
[broken link] The link exported vsconfig file referenced in the Using winget section

### ISSUE THREAD

**Issue by wesmacdonald** [MicrosoftDocs/visualstudio-docs#9015]
Clicking the link returns a 404 - Page not found. Link references an [.md file](https://learn.microsoft.com/en-us/import-export-installation-configurations.md) vs this [page](https://learn.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations)

**Comment by WilliamAntonRohm** [comment]
@wesmacdonald -- Wes, thank you for catching this.  Which learn.microsoft.com article is the source link in?

**Comment by wesmacdonald** [comment]
On this [page](https://learn.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples) in the "Using winget" section.

Sorry about that.

Wes

**Comment by WilliamAntonRohm** [comment]
@wesmacdonald -- Wes, thank you for clarifying!  I am updating the page.
