### ISSUE TITLE
Vue and ASP.NET Core (Preview) typescript template is exactly the same as the javascript template

### ISSUE THREAD

**Issue by SamGeodynamics** [MicrosoftDocs/visualstudio-docs#9017]
- both the javascript and the typescript version are exactly the same javascript project.
- why not invest in the create-vue approach instead of the now maintained state of vue-cli

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@SamGeodynamics Asking about this

**Comment by Mikejo5000** [comment]
@SamGeodynamics Product team is aware of this issue and there is planning to address it. Closing as it is currently not a doc issue.

**Comment by drowhunter** [comment]
please fix this

**Comment by WilliamAntonRohm** [comment]
@drowhunter -- Trevor, thank you for your follow-up.  As this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
