### ISSUE TITLE
Step 3 - Learn Django in VS Authenticate users

### ISSUE THREAD

**Issue by bbartling** [MicrosoftDocs/visualstudio-docs#902]
Please delete post, I was looking at the documentation wrong..
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e07a-6d43-8800-fd06-be7f8ad21d20
* Version Independent ID: e6b188d8-adc0-cb16-cffa-63bfe2d3ecd4
* Content: [Tutorial - Learn Django in Visual Studio, step 5 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/python/learn-django-in-visual-studio-step-05-django-authentication)
* Content Source: [docs/python/learn-django-in-visual-studio-step-05-django-authentication.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/python/learn-django-in-visual-studio-step-05-django-authentication.md)
* Service: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
OK, will do! I appreciate the issue in any case. :)
