### ISSUE TITLE
Tables cut off

### ISSUE THREAD

**Issue by chipplyman** [MicrosoftDocs/visualstudio-docs#9020]
The switches tables are wider than the article, and their right-most side is cut off unless my window is wider than 1664px.  The tables do have a horizontal scrollbar but a) the tables are so long that the scrollbar is difficult to discover, and b) eww @horizontal scrollbars in principle.

IMO the best fix would be to embed the "In This Article" TOC within the main column.  It eats a _lot_ of horizontal space and all that useless whitespace could be filled with useful content.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-command-line-reference.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@chipplyman --thank you for your feedback.  You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).
