### ISSUE TITLE
Inapplicable to visual Studio Code

### ISSUE THREAD

**Issue by jerryemery** [MicrosoftDocs/visualstudio-docs#9023]
For some reason google recommends this page when asking how to run visual basic code in visual stuide code.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 758f9d8f-9071-0753-3c52-d56543ec5557
* Version Independent ID: 758f9d8f-9071-0753-3c52-d56543ec5557
* Content: [Tutorial: Create a simple Visual Basic (VB) console app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/visual-basic/tutorial-console?view=vs-2022)
* Content Source: [docs/get-started/visual-basic/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/visual-basic/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@jerryemery -- Jerry, this does not appear to be a supported scenario:
- [extension for running Visual Basic script in Visual Studio Code](https://learn.microsoft.com/en-us/answers/questions/597185/extension-for-running-visual-basic-script-in-visua)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
