### ISSUE TITLE
Clarify documentation in "Configure a launch condition to detect the VSTO Runtime" Step 4

### ISSUE THREAD

**Issue by AdamTibi** [MicrosoftDocs/visualstudio-docs#9025]
Documentation says:

**Configure a launch condition to detect the VSTO Runtime**
...
4. In the **Launch Conditions**(OfficeAddInSetup) editor, right-click Requirements on Target Machine, and then click Add Registry Launch Condition. This search condition can search the registry for a key that the VSTO runtime installs. The value of the key is then available to the various pieces of the installer through a named property. The launch condition uses the property defined by the search condition to check for a certain value.

However, the window name is now confused with the item in the window "Launch Conditions" and it is not clear that this refers to "Search Target Machine"

**Comment by WilliamAntonRohm** [comment]
@AdamTibi -- Adam, thank you for your feedback.  

- [Configure a launch condition to detect the VSTO Runtime](https://learn.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2022#configure-a-launch-condition-to-detect-the-vsto-runtime)

@John-Hart -- John, please look into this issue.
