### ISSUE TITLE
"Device window" is not present. What is needed to be installed?

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#903]
I don't see "Device window" in my project.  There is only a drop-down list of screen sizes and orientation buttons. It seems it is not a standard part of design view and needs a touch to tell what should be installed to see it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eeeb6491-1f2c-73a7-fef2-afb69fd08948
* Version Independent ID: 7e3209b0-a116-3488-a80f-993edf9515a4
* Content: [Creating a UI by using XAML Designer in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/creating-a-ui-by-using-xaml-designer-in-visual-studio)
* Content Source: [docs/designers/creating-a-ui-by-using-xaml-designer-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/creating-a-ui-by-using-xaml-designer-in-visual-studio.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yilmazdurmaz Thanks for the feedback. I'll get an answer and update the topic as necessary.

**Comment by yilmazdurmaz** [comment]
it is 2017 versions, and true for both VS and blend for a UWP app.

**Comment by Bluejanis** [comment]
Currently with version 2017 15.8.8 there is no device window entry in the design menu.

**Comment by gewarren** [comment]
@diverdan92 Can you comment on whether the Device Window was removed from XAML Designer?
