### ISSUE TITLE
Section instructs to use obsolete tool in Server Explorer

### ISSUE THREAD

**Issue by vassilyl** [MicrosoftDocs/visualstudio-docs#9032]
The "Access your Azure account in Server Explorer" section is not relevant anymore according to https://learn.microsoft.com/en-us/visualstudio/azure/vs-azure-tools-virtual-machines-access-from-server-explorer?view=vs-2022

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bff48e07-208e-a8b1-0855-3f677cdf788b
* Version Independent ID: 0fd3926f-d997-c744-3f48-85568a2d462e
* Content: [Sign in - Visual Studio (Windows)](https://learn.microsoft.com/en-gb/visualstudio/ide/signing-in-to-visual-studio?view=vs-2022#how-to-sign-in-to-visual-studio)
* Content Source: [docs/ide/signing-in-to-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/signing-in-to-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@vassilyl, thanks for your feedback. We've updated the doc and the changes should be live later today.
Thanks!
