### ISSUE TITLE
.net framework 4.8 version

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/visualstudio-docs#9033]
I am using .net framework 4.8 version with VS2019 where we don't have an option for publishing profile. Could you please help me understand how I can do the same with this specific version of .net?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1672c325-b08a-dbc0-0e3e-31c832753613
* Version Independent ID: c479d585-37bb-795d-1e1c-4833c2262db6
* Content: [Building ClickOnce Applications from the Command Line - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2022)
* Content Source: [docs/deployment/building-clickonce-applications-from-the-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/building-clickonce-applications-from-the-command-line.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@ravick4u Except for the sub-section specific to .NET Core and .NET 5+, the rest of the instructions are specific to .NET Framework and will work with VS 2019.  After following instructions described in the article, the MSBuild command line would be:
msbuild /t:publish /p:PublishDir="<specific location>"
I will update the heading, and maybe some of the text, to clarify this.

**Comment by ravick4u** [comment]
Thanks for the update. I tried below command and it did not publish the app to the mentioned URL. Am I doing something wrong here?
msbuild /t:publish /p:PublishURL="<url>"

**Comment by Mikejo5000** [comment]
@ravick4u Did you publish once first from VS per instructions? https://learn.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2022#create-and-build-a-basic-clickonce-application-with-msbuild
Also, what happens when you leave off the /p switch? The /p switch is not required.

**Comment by ravick4u** [comment]
@Mikejo5000 Yes its working from VS without any issue. Because I need to setup this in my CI/CD pipeline I am trying the same with ms build command. Here is what I tried and which build the package but doesn't publish anything is not working. From VS I gets a prompt to enter uid/pwd for my publish url(which is ftp location)

msbuild /p:Configuration=Release /target:publish /property:PublishUrl=<publishurl>

**Comment by ravick4u** [comment]
@Mikejo5000 By the way when I don't put '/p' or '/property' it doesn't work and gives me below error.

![msbuilderror](https://user-images.githubusercontent.com/11890407/224127209-2663cd9e-e6b9-4913-88f4-98fb1e21035e.png)

**Comment by Mikejo5000** [comment]
@ravick4u I believe PublishUrl is only set in the Publish properties, and MSBuild does not use it directly but is part of the VS process. See the following:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/8853
![image](https://user-images.githubusercontent.com/11948536/224133721-959404b5-d5e8-45c7-a94b-38b06d6bfc4e.png)
I believe the typical behavior for PublishDir and PublishUrl described by Sujit applies to both .NET and .NET Framework.
https://learn.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2022#publish-properties
There is a doc update coming to clarify some of this.
If this doesn't help, please let me know and then use [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by ravick4u** [comment]
Thanks for the clarification. How about other properties which have been mentioned in the microsoft post. Are there any other properties being ignored by MSBuild? for e.g. InstallUrl

In this case could you please suggest what is the approach we are supposed to use to publish the packages after the build complete to the ftp or any other web location?

**Comment by Mikejo5000** [comment]
I believe there are two methods: (1) create an MSBuild publish task. https://stackoverflow.com/questions/2130985/problems-using-msbuild-using-command-line-for-publish-click-once?noredirect=1&lq=1
Or (2) use command-line version of mage.exe:
https://learn.microsoft.com/en-us/visualstudio/deployment/walkthrough-manually-deploying-a-clickonce-application?view=vs-2022
I'm not certain about the other properties, but I will need to ask about that as part of the doc update. Please use Report a problem to engage directly with the engineering team.

**Comment by ravick4u** [comment]
Looks like this tools is only for the trusting the packages. How we are supposed to publish the packages?

**Comment by Mikejo5000** [comment]
@ravick4u I think you're correct about that. Step 10 in this article says, "Copy all of the files in the deployment directory to the deployment destination or media. This may be either a folder on a Web site or FTP site, a file share, or a CD-ROM."
So, outside of the VS Publish feature in the UI, it looks like this step is based on whatever 3rd party tool you use to copy the files, or on the MSBuild publish task I mentioned before. The MSBuild publish task looks like an MSBuild feature rather than ClickOnce, so the MSBuild docs might be the best place to look (if the SO post is not helpful).

**Comment by Mikejo5000** [comment]
Decided to refactor into two articles, to help clarify publish profile (.NET) vs. project file and Project Designer for .NET Framework.
Clarified issues around build vs. deployment and PublishURL.
