### ISSUE TITLE
ZIndex for overlapping elements

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#904]
The following expression should use "higher" instead of "lower", or "back" instead of "front"

"An element that has a lower ZIndex value appears in front when elements overlap."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bfd1636-a149-bcf7-823f-d2ecf0a0120f
* Version Independent ID: c65af203-fb57-0609-7f12-902bfb497fdd
* Content: [Working with elements in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/working-with-elements-in-xaml-designer)
* Content Source: [docs/designers/working-with-elements-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/working-with-elements-in-xaml-designer.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yilmazdurmaz Thanks for this feedback; I'll fix it in the next sprint. Also in case you didn't know about it, we do allow the public to edit the docs too, if you want to give that a go. There's an Edit button near the top right corner.

**Comment by gewarren** [comment]
@diverdan92 Can you confirm that the statement "An element that has a higher ZIndex value appears in front when elements overlap." is correct? If so, I'll update the article.

**Comment by diverdan92** [comment]
cc @LyalinDotCom 
Yes - that statement is correct.

**Comment by gewarren** [comment]
@yilmazdurmaz Already [fixed this last May](https://github.com/MicrosoftDocs/visualstudio-docs/commit/ea6019b588e7653d2226b80a220ca8d352ffd06f#diff-ea8122eabde9fe3cffcd169fd1d348b1). Thank you!
