### ISSUE TITLE
Link to "exported vsconfig file" is broken

### ISSUE THREAD

**Issue by mikaelnordin** [MicrosoftDocs/visualstudio-docs#9044]
The link for "exported vsconfig file" is broken and returns a 404. 
The link can be found under the heading [Use winget to install Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022#use-winget-to-install-visual-studio**)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022#use-winget-to-install-visual-studio)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@mikaelnordin -- Mikael, thank you for your feedback.  That link is working on my computer:
- [exported vsconfig file](https://learn.microsoft.com/visualstudio/install/import-export-installation-configurations?view=vs-2022)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
