### ISSUE TITLE
[!WARNING] and [!NOTE] sections have auto translated titles while page is in English

### ISSUE THREAD

**Issue by Tim-Maes** [MicrosoftDocs/visualstudio-docs#9050]
On a Dutch PC, warning is shown as 'waarschuwing' while the documentation is English.

![image](https://user-images.githubusercontent.com/91606949/224658373-21dfc9a5-3f69-4dc2-92ca-d95bde023062.png)

Same for notes:
![image](https://user-images.githubusercontent.com/91606949/224658667-86732780-f068-4a53-972b-31fc7b912236.png)

**Comment by WilliamAntonRohm** [comment]
@Tim-Maes -- Tim, thank you for bringing this to our attention.  I am notifying our translation team.

**Comment by WilliamAntonRohm** [comment]
@Tim-Maes -- Tim, please add a link to a learn.microsoft.com article that shows this behavior.  I am only finding all-Dutch pages, such as this one:
- [Een filter wijzigen of verwijderen](https://learn.microsoft.com/nl-nl/azure/azure-portal/set-preferences#modify-or-delete-a-filter)
