### ISSUE TITLE
Operator precedence?

### ISSUE THREAD

**Issue by chipplyman** [MicrosoftDocs/visualstudio-docs#9056]
This page could use some explanation of operator precedence.  Based on experience, the [in]equality operators take precedence over 'And' and 'Or'.  But it is unclear whether 'And' takes precedence over 'Or' as in C-family languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@chipplyman -- thank you again for your feedback.


@ghogen -- please look into this issue.

**Comment by ghogen** [comment]
@chipplyman 
And takes precedence over Or in all recent versions of MSBuild, for the last decade at least.
I'm updating this page to state that.
Thanks for the feedback!
