### ISSUE TITLE
Generation of command line from VSInstaller for offline installation

### ISSUE THREAD

**Issue by mprevot** [MicrosoftDocs/visualstudio-docs#906]
Would it be possible to generate the command line from the GUI ? It's so much more practical than "searching for command options to match the installation scheme I found to be fine in the GUI" !

**Comment by TerryGLee** [comment]
@mprevot Thanks for your feedback; we appreciate your input. However, this forum is for documentation feedback. Please consider providing a [product suggestion](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017#reporting-alternatives-a-namealternatereportinga) such as this by using the **[UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide)** forum.
