### ISSUE TITLE
Missing image in debugging documentation

### ISSUE THREAD

**Issue by Flassari** [MicrosoftDocs/visualstudio-docs#9069]
There's an image missing on this page under "Pin Properties in data tips", there's just this text instead: `![Pinning a property in a data tip](../debugger/media/basic-pin-data tip.gif "Pinning a property in a data tip")`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5dfa327-8d82-cf28-e9e8-b8034fbb7e6d
* Version Independent ID: 5f5a5d4d-c407-7570-1299-e6dbe8ef7e11
* Content: [View variable values in data tips - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/view-data-values-in-data-tips-in-the-code-editor?view=vs-2022)
* Content Source: [docs/debugger/view-data-values-in-data-tips-in-the-code-editor.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/view-data-values-in-data-tips-in-the-code-editor.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Flassari -- Ari, thank you for catching this. I have updated the documentation and it should be live by tomorrow.
