### ISSUE TITLE
Are these directions for the older style of template where you Export from VS? 

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#9077]
Or are they for the newer `dotnet new` template system?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5b76e208-2a2a-9fc3-98ff-147540157f32
* Version Independent ID: 5f5c9adf-da1d-ec0b-8af3-ccd2e27eaadc
* Content: [Create multi-project templates - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2022)
* Content Source: [docs/ide/how-to-create-multi-project-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-create-multi-project-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TimShererWithAquent** [comment]
We should clarify this -

**Comment by ghogen** [comment]
@StingyJack 

Yes, the context used here refers to project templates that are used when projects are created in Visual Studio, not the projects that you can create using `dotnet new` from the command line.

I'll update the article to make that clear.
