### ISSUE TITLE
Lightweight fonts impeded readability

### ISSUE THREAD

**Issue by Geronimo1989** [MicrosoftDocs/visualstudio-docs#9081]
The font used in the article (and here) is a lightweight non-serif font. It can be difficult for tired eyes to see that the font color is blue, indicating a hyperlink. I would suggest using a "heavier" weight font, such as Times New Roman or Georgia, to make it easier for the reader to see that something has been linked.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a7f38987-1d2b-6dfc-e531-d1ca50fbb11c
* Version Independent ID: 592a4f31-6e8f-0ba6-4b8d-58b44600faf3
* Content: [Deploy your Visual Studio app to a folder, IIS, Azure, or another destination](https://learn.microsoft.com/en-us/visualstudio/deployment/deploying-applications-services-and-components-resources?view=vs-2022#what-publishing-options-are-right-for-me)
* Content Source: [docs/deployment/deploying-applications-services-and-components-resources.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/deploying-applications-services-and-components-resources.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Geronimo1989 -- thank you for your feedback; we appreciate it. You can submit issues related to overall site experience, or suggestions for improved site functionality or design, at [https://aka.ms/sitefeedback/](https://aka.ms/sitefeedback).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
