### ISSUE TITLE
Xaml designer for WinIU?

### ISSUE THREAD

**Issue by ShaneOss** [MicrosoftDocs/visualstudio-docs#9087]
I'm in the process of moving across one of my UWP apps to WinUI and noticed there's no designer? Is that right? Where is the designer for WinUI?

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eeeb6491-1f2c-73a7-fef2-afb69fd08948
* Version Independent ID: 7e3209b0-a116-3488-a80f-993edf9515a4
* Content: [Create UIs with Visual Studio XAML Designer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/xaml-tools/creating-a-ui-by-using-xaml-designer-in-visual-studio?view=vs-2022)
* Content Source: [docs/xaml-tools/creating-a-ui-by-using-xaml-designer-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xaml-tools/creating-a-ui-by-using-xaml-designer-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-xaml-tools**
* GitHub Login: @maddymontaquila
* Microsoft Alias: **maleger**

**Comment by WilliamAntonRohm** [comment]
@ShaneOss -- Shane, thank you for your questions.  Apparently there is no such designer.  For example, see https://github.com/microsoft/WindowsAppSDK/issues/766.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by soroshsabz** [comment]
ITNOA

As documentation preview, I think it is important to specify which platform support by XAML Designer,

I think Microsoft must update this page and add list of supported framework.

**Comment by soroshsabz** [comment]
related to https://github.com/microsoft/microsoft-ui-xaml/issues/5917

**Comment by WilliamAntonRohm** [comment]
cc @maddymontaquila for awareness

**Comment by soroshsabz** [comment]
@maddymontaquila I strongly recommend you, to hear all feedback and requests in https://github.com/microsoft/microsoft-ui-xaml/issues/5917 and in below Developer Community tickets

* [[Feature request] Visual designer for WinUI 3](https://developercommunity.visualstudio.com/t/Feature-request-Visual-designer-for-Wi/1608476?q=WinUI+Designer) - more than 47 votes
* [winui 3 xaml designer still missing](https://developercommunity.visualstudio.com/t/winui-3-xaml-designer-still-missing/10386589?q=WinUI+Designer)
* [Blend 2022 and WinUI3 when will designer be available?](https://developercommunity.visualstudio.com/t/Blend-2022-and-WinUI3-when-will-designer/1593656?q=WinUI+Designer)
