### ISSUE TITLE
Doesnt work for Vendor IDE's who dont use C# as a language

### ISSUE THREAD

**Issue by PGTBoos** [MicrosoftDocs/visualstudio-docs#9094]
Working with vsiualstudio for Beckhoff PLC's  tasklist is broken.
The solution is targeted at c# but there are more languages out there in the wild...

[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: c981176b-8d39-beef-22d1-4a3721c4bf2a
* Version Independent ID: c76dfdc3-8584-e324-577c-991dbdd7bbac
* Content: [Configure live code analysis scope for .NET - Visual Studio (Windows)](https://learn.microsoft.com/nl-nl/visualstudio/code-quality/configure-live-code-analysis-scope-managed-code?view=vs-2022)
* Content Source: [docs/code-quality/configure-live-code-analysis-scope-managed-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/code-quality/configure-live-code-analysis-scope-managed-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-code-analysis**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@PGTBoos -- thank you for your feedback.  Please add it here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by PGTBoos** [comment]
This isnt a new future request, it still is the broken todo task list, i hoped here would be a hotfix for it, since hardware can be bound to specific versions of Visual studio variants, (its not possible to upgrade them either, if you have older PLC's in the field for example). Maybe I post it at Beckhof their a partner of MS

**Comment by WilliamAntonRohm** [comment]
@PGTBoos -- thank you for your followup.  I'm not sure what you mean by Beckhoff task list, nor how hardware is involved with the scope of this article -- please provide additional details or context.

**Comment by PGTBoos** [comment]
visual studio as an editor, is used by partners of Microsoft, Beckhof is a major vendor of PLC's their coding tools are build based upon visual studio, despite that though todo's dont scan a project in other languages such as the open standardized programming language from beckhof an industry standard.

**Comment by PGTBoos** [comment]
Please clarify your anwer

**Comment by WilliamAntonRohm** [comment]
@PGTBoos -- this issue is implementation- and product-related, rather than documentation-related.  Please add your suggestions here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
