### ISSUE TITLE
VS 2022 - vs_enterprise is not found

### ISSUE THREAD

**Issue by kgoldman** [MicrosoftDocs/visualstudio-docs#9096]
VS 2022 - vs_enterprise is not found.   I suppose I have to install it first, but there are no instructions.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2022)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/command-line-parameter-examples.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@kgoldman -- Ken, thank you for your feedback.  Please see this article:
- [Use command-line parameters to install, update, and manage Visual Studio](https://learn.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2022)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by kgoldman** [comment]
Huh?  I pointed to an article with missing information, and you closed the issue by pointing me back to the same article.

@WilliamAntonRohm

**Comment by WilliamAntonRohm** [comment]
@kgoldman -- Ken, thank you for your followup.  The article I mentioned, which is indeed very similar, lists the installer links in its first section.
