### ISSUE TITLE
Update for private nuget sources

### ISSUE THREAD

**Issue by JRosanowski** [MicrosoftDocs/visualstudio-docs#9097]
Private nuget sources are not working with Visual Studio for Mac without editing the nuget.config and specifying the private artifactory username and password. Could this page be updated with information on how to get it to work?

Thanks,
Jonathan

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e32dfe2-b389-c1ec-cd29-14c081d140a2
* Version Independent ID: 3d0606b2-e98a-819e-6090-1ca8b7d1ed51
* Content: [Including a NuGet package in your project - Visual Studio for Mac](https://learn.microsoft.com/en-us/visualstudio/mac/nuget-walkthrough?view=vsmac-2022)
* Content Source: [mac/nuget-walkthrough.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/nuget-walkthrough.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by j-martens** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@JRosanowski, thanks for your feedback.

The scenario you're trying seems like it's a possible product issue. Please file a product issue with details of your specific scenario in the [developer community forum](https://developercommunity.visualstudio.com/VisualStudioMac).

Thanks again!

**Comment by JRosanowski** [comment]
So no intention of documenting supported behaviour in the product? Great...I and anyone else attempting to do this will just waste time googling how to do it. Thanks.

**Comment by heiligerdankgesang** [comment]
Hi @JRosanowski - any version of Visual Studio for Mac 17.x will store username and passwords for private NuGet sources in the keychain. It looks like you've mentioned using JFrog's Artifactory to host your NuGet repository. While I'm not intimately familiar with this scenario, if this is what you're doing, I suspect a product or config issue. 

After reading your initial Issue again in conjunction with your most recent comment, let me ask a quick clarifying question. Are you:

1. Saying that this scenario isn't working unless you add the info to the nuget.config file and you want a more acceptable solution OR
2. Saying that adding the information for the Artifactory credentials to the nuget.config file is a reasonable solution and that you just want it documented on the [NuGet package documentation page](https://learn.microsoft.com/visualstudio/mac/nuget-walkthrough?view=vsmac-2022)

Am I correct in assuming the latter?

Thanks for your time!
