### ISSUE TITLE
Error in link for "download the full list"

### ISSUE THREAD

**Issue by mhyon** [MicrosoftDocs/visualstudio-docs#910]
There is a trailing underscore in the Excel file link that seems to prevent download.  https://download.microsoft.com/download/1/5/4/15454442-CF17-47B9-A65D-DF84EF88511B/Products_by_Benefit_Level.xlsx_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10ab4ecc-3cca-8224-8b30-7bccd1ebae31
* Version Independent ID: 2e89b277-021e-b185-ea1a-bc153481b0e1
* Content: [Using Subscriber Downloads on Visuals Studio Subscriptions](https://docs.microsoft.com/en-us/visualstudio/subscriptions/subscriber-downloads)
* Content Source: [subscriptions/subscriber-downloads.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/subscriptions/subscriber-downloads.md)
* Service: **vs-subscription**
* GitHub Login: @evanwindom
* Microsoft Alias: **jaunger**

**Comment by TerryGLee** [comment]
@mhyon This has been fixed. Thanks for reporting it! And @evanwindom, thanks for fixing it. :)
