### ISSUE TITLE
Project type GUIDs

### ISSUE THREAD

**Issue by KaraOttewell** [MicrosoftDocs/visualstudio-docs#9101]
Presumably, Microsoft does actually know what sort of project the old, now unsupported GUIDs, referred to. Given that the project conversion results page actually has the GUID in the URI, it would be great if the landing page actually told you what that project type was, and suggested a way forward for those trying to update old projects, rather than a generic landing page with no obvious way to interpret the GUID.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f3315d1-e6d3-e86d-9cce-1ff9ce0fc482
* Version Independent ID: ae3fd143-bf0b-4cfe-bcad-557eb41fdc2c
* Content: [Port, migrate, and upgrade projects - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/porting/port-migrate-and-upgrade-visual-studio-projects?wt.mc_id=getvssdk&view=vs-2022)
* Content Source: [docs/porting/port-migrate-and-upgrade-visual-studio-projects.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/porting/port-migrate-and-upgrade-visual-studio-projects.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@KaraOttewell, thanks for your feedback!
Please submit your product feature suggestion on [Visual Studio Developer Community](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Ffeedback%2Fsuggest%3Fspace%3D8&data=05%7C01%7Cmeghaanand%40microsoft.com%7Cc6bdc28879f048b2d12f08db41ce5f27%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638176126843019256%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3jaViVIj9uaahz9EUuS3E2FA6bAyHzFwrR55W5T2240%3D&reserved=0).

Thanks!
