### ISSUE TITLE
Page is pathetic - no Maui, no mention of installing workloads

### ISSUE THREAD

**Issue by robomac** [MicrosoftDocs/visualstudio-docs#9107]
Maui is not, by default, in current installs of VS Mac 2022.  The Maui directions say, install the workloads.  
On Windows, VS Installer is a distinct app.  It doesn't appear to be so on the Mac, or at least that isn't mentioned.
The main reason someone would come here, isn't covered.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0c51e5f1-10c6-bf93-8ccf-092a2c587903
* Version Independent ID: f445f27b-642c-e62b-b0cf-27c4bb3fda46
* Content: [Visual Studio for Mac Workloads - Visual Studio for Mac](https://learn.microsoft.com/en-us/visualstudio/mac/workloads?view=vsmac-2022)
* Content Source: [mac/workloads.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/workloads.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by j-martens** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@robomac, thanks for you feedback. We've updated the doc and the changes should be live later today.
