### ISSUE TITLE
The link to the printable pdf leads to the "Visual Studio 2019" shortcut pdf. The preview is titled "Visual Studio"

### ISSUE THREAD

**Issue by akhilgeothom** [MicrosoftDocs/visualstudio-docs#9116]
The link to the printable pdf leads to the "Visual Studio 2019" shortcut pdf. The preview is titled "Visual Studio" only. I think the preview is showing a later version than what the link is pointing to.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23332067-130b-a343-b902-7d09680d3519
* Version Independent ID: 09bb5d36-f067-5422-2ab2-e4c7a8f1d6ed
* Content: [Keyboard shortcuts - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2022#Printable%20shortcut%20cheatsheet)
* Content Source: [docs/ide/default-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/default-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@akhilgeothom (and @BenjaminVanDerKwaak) We've updated the [Keyboard shortcuts in Visual Studio](https://learn.microsoft.com/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio) page with a newly updated PDF. We'll close this issue now, with our thanks to you for your help with improving the Visual Studio documentation!
