### ISSUE TITLE
/Fd compiler switch documentation not complete?

### ISSUE THREAD

**Issue by tamlin-mike** [MicrosoftDocs/visualstudio-docs#9117]
I believe the following text is incomplete
> without using **/Fd**, the compiler creates two .pdb files

Without further qualification, that suggests _any_ use of **/Fd** will suppress creation of VC&lt;n&gt;.pdb.

**/Fd** can be used in two ways.
1. Specify a destination _filename_.
2. Specify a destination _path_ (by ending with a path-separator).

Experience suggest it's only the first form that prevents creation of VC&lt;n&gt;.pdb.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ce80d99-822d-3e3a-4c7f-6ec593029cef
* Version Independent ID: 61420028-368e-e122-1490-003b9340cb39
* Content: [Symbol / PDB files in the Visual Studio debugger](https://learn.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2022)
* Content Source: [docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@tamlin-mike Thanks for the correction! Updating the doc. Update should be live by EOD today.
