### ISSUE TITLE
Signed in. Cannot report a problem (Timeout). Message is almost instant

### ISSUE THREAD

**Issue by statler** [MicrosoftDocs/visualstudio-docs#9119]
Signed in. Cannot report a problem. Message is almost instant

![image](https://user-images.githubusercontent.com/337991/230228062-b6fe2563-3d2b-4e57-98d1-879e13a26de7.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [Report a problem with Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-au/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@statler -- thank you for your feedback.  Please report the problem here:  vsfeedback@microsoft.com

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
