### ISSUE TITLE
Event handler confusion in tutorial 

### ISSUE THREAD

**Issue by cwiek** [MicrosoftDocs/visualstudio-docs#9123]
In the "Add event handlers for the NumericUpDown controls" section, the tutorial instructs me to assign a method to `NumericUpDown` control's `Enter` event. This method uses `answerBox.Select` method to select the contents of the entered `NumericUpDown` control.

This works as expected when using <kbd>Tab</kbd> key to switch focus to the `NumericUpDown` control. When using mouse click, however,  it does not work as expected - clicking on the control only executes the default action of focusing the control and placing the keyboard cursor at clicked place, ignoring (or maybe overriding?) the method written by following the tutorial.

I've only started just started learning Windows Forms development, but I'm guessing the `Enter` event is fired before the default handling of mouse on the text input box, so the default mouse handler clears the selection made by this method.

I'd suggest this article makes note of that problem, so users don't get confused when nothing happens after doing exactly what the tutorial says. Perhaps it could also offer some solution to this problem. I've worked around it by adding the same code in another method and assigning it as a handler for `MouseDown` event. It works, but perhaps more experienced people can offer a better solution in the tutorial. :)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c83af54-5ee9-2700-f076-51ebf82cf035
* Version Independent ID: 4c83af54-5ee9-2700-f076-51ebf82cf035
* Content: [Tutorial: Customize a Windows Forms app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-math-quiz-customize-ui?view=vs-2022&tabs=csharp)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-math-quiz-customize-ui.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-math-quiz-customize-ui.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@cwiek, thanks for your feedback. We've added a fix to the doc. The changes should be live later today.
Thanks again!
