### ISSUE TITLE
Page very out of date

### ISSUE THREAD

**Issue by steven-pearson** [MicrosoftDocs/visualstudio-docs#9125]
Only shows old versions of .Net and VS Mac. Link is from this page
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.202-macos-x64-installer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff562e19-8882-cfcf-7d92-85417535634f
* Version Independent ID: ff562e19-8882-cfcf-7d92-85417535634f
* Content: [.NET Core support - Visual Studio for Mac](https://learn.microsoft.com/en-gb/visualstudio/mac/supported-versions-net?WT.mc_id=dotnet-35129-website&view=vsmac-2022)
* Content Source: [mac/supported-versions-net.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/supported-versions-net.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by j-martens** [comment]
#reassign: @anandmeg

**Comment by anandmeg** [comment]
@steven-pearson, thanks for your feedback. We've updated the page and the changes should be live later today.

Thanks again!
