### ISSUE TITLE
Assets panel vs. Toolbox panel

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#913]
There are two places this line is in "You can find them all in the Assets panel".

At first, I could not find Assets panel and I thought my installation is broken. Then realized there are differences in "VS" and "Blend for VS". Since these parts are not Blend related alone,  I thought editing it in github but could not decide what to write. it should read something like this: "You can find them all in the Toolbox panel in VS and in the Assets panel in Blend for VS"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbdaf3d5-a7bc-fb9f-9750-9aee54546670
* Version Independent ID: d0e43ac2-9a43-a803-93bd-720a4ebaf664
* Content: [Organize objects into layout containers in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/organize-objects-into-layout-containers-in-xaml-designer)
* Content Source: [docs/designers/organize-objects-into-layout-containers-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/organize-objects-into-layout-containers-in-xaml-designer.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yilmazdurmaz Thanks so much for this clarification; the designers docs are going to be much better when all your feedback is addressed! :)
