### ISSUE TITLE
What are you talking about

### ISSUE THREAD

**Issue by Roscoe-Sandstone** [MicrosoftDocs/visualstudio-docs#9135]
[Enter feedback here]
What are you talking about.?  Straight out of the box you reference a "Get Started" POS that doesn't show up.  So I open a folder and instead of "Folder View" I get "Select Folder".  So I select a folder with my .py file in it, and it goes down hill from there.  I don't want to send a farging rocket to Mars, I simply want to run a python file from Visual Studio 2022.  What a POS.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfaa1bb6-20e0-dadf-7b12-30fa947c520e
* Version Independent ID: 87b861c0-0a08-f6fd-6fa2-9117e853dbbc
* Content: [Quickstart - Open a Python code folder - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/quickstart-05-python-visual-studio-open-folder?view=vs-2022)
* Content Source: [docs/python/quickstart-05-python-visual-studio-open-folder.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/quickstart-05-python-visual-studio-open-folder.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
The Get Started pane shows up on the right of the screen when you launch Visual Studio. There you can select **Open a local folder**. If you already have Visual Studio open, you can select **File -> Open -> Folder** instead. Once you find the folder containing your Python files, click **Select Folder** to load the project into Visual Studio. 

Once you open your folder in Visual Studio, you will see **Solution Explorer - Folder View** where your Python files will live.

**Comment by cwebster-99** [comment]
This issue can be closed as the documentation reflects up-to-date steps and UI.

**Comment by anandmeg** [comment]
@Roscoe-Sandstone, thanks for your feedback.
Closing this issue now per @cwebster-99 comments above.

Thanks!
