### ISSUE TITLE
TFS doesn't load projects

### ISSUE THREAD

**Issue by SachinCS1992** [MicrosoftDocs/visualstudio-docs#914]
After you've entered the server URL, username, password, etc. and click next, it shows the 'Loading Projects' popup and just remains there forever and doesn't load the projects. I'm confirmed the details are correct - it just wouldn't load.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87e2c464-3537-278a-da5a-5301af0fb6d5
* Version Independent ID: 29cb95b8-5cc2-e816-2d2e-ea6945ae7a5d
* Content: [TF Version Control - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/tf-version-control)
* Content Source: [mac/tf-version-control.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/tf-version-control.md)
* Service: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by cassiomansini** [comment]
Did you fix it?

**Comment by mikehachen** [comment]
How did you fix it? I still have this problem...

**Comment by hernandoz** [comment]
I am also having this problems ... any updates ?

**Comment by jerryg78258** [comment]
I'm also having this problem.  Using safari, I determined that I was able to access my TFS server web page, so it's not an authentication issue.

**Comment by SachinCS1992** [comment]
It's not fixed yet. Microsoft is currently looking into this at the moment
https://developercommunity.visualstudio.com/content/problem/248618/cant-connect-to-tfs-version-control-in-visual-stud.html
