### ISSUE TITLE
Redundant Code Screenshots on Generate Equals and GetHashcode Method Overrides

### ISSUE THREAD

**Issue by Callindrill** [MicrosoftDocs/visualstudio-docs#9140]
The page has screen shots of code in addition to code snippets. The screen shots are redundant and generally less helpful than the snippets, and should be removed. This would also make the page appear more consistent with other pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb48054-70fa-c5eb-748e-4db24ef64fd4
* Version Independent ID: 9ca41665-2e31-87da-4ba9-a8c60150db51
* Content: [Generate C# Equals and GetHashCode Method Overrides - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2022)
* Content Source: [docs/ide/reference/generate-equals-gethashcode-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/generate-equals-gethashcode-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Callindrill -- Jon, thank you for your considered feedback.  The screenshots are meant to show the actual displayed results in Visual Studio, for people new to it.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
