### ISSUE TITLE
Wrong again

### ISSUE THREAD

**Issue by Roscoe-Sandstone** [MicrosoftDocs/visualstudio-docs#9142]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db7f9ca8-40ce-6b6d-15df-bbb3b6829430
* Version Independent ID: 3dd10fed-b3d3-269c-623e-00031a81ed83
* Content: [Quickstart: Create a Python web app with Visual Studio](https://learn.microsoft.com/en-us/visualstudio/ide/quickstart-python?view=vs-2022)
* Content Source: [docs/ide/quickstart-python.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/quickstart-python.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by Roscoe-Sandstone** [comment]
When I rigt-click on app.py, there is no "select as startup file" in the box that opens.  Y'know, I would hate to see a car that was designed and built by Microsoft.

**Comment by cwebster-99** [comment]
Hi @Roscoe-Sandstone, what version of Visual Studio/Python Tools are you using? Once you add app.py in the solution explorer, right-clicking on app.py should display an option that says "Set as Startup File" as mentioned in the [getting started tutorial](https://learn.microsoft.com/en-us/visualstudio/ide/quickstart-python?view=vs-2022#run-the-application).

**Comment by anandmeg** [comment]
Closing per @cwebster-99's comments above.
Thanks for your feedback, @Roscoe-Sandstone!
