### ISSUE TITLE
matplotlib not installing in Python Environment

### ISSUE THREAD

**Issue by MaxFun** [MicrosoftDocs/visualstudio-docs#9144]
https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2022 

Followed instructions on page and matplotlib would not install in Python 3.9 (64-bit) or Python 10 (64-bit). I'm using VS2022.

Saved project, closed VS2022 and reopen it. Opened the project and matplotlib was installed.
Anyway to VS2022 without closing it?
Also images on page do not reflect what I see with VS2022 I installed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca858db-d7bf-c894-af0a-eb1ba07c29ea
* Version Independent ID: 330f9197-38cd-73b7-c2cc-5d032a3bdc33
* Content: [Python in Visual Studio tutorial step 5, install packages](https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2022)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
@MaxFun could you provide some more information about what you were experiencing? 

Was numpy not installed or were you seeing yellow squiggles in the editor when referencing numpy?

**Comment by MaxFun** [comment]
Had open new Python project to follow the tutorial. Following instructions on https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2022

I opened the Python Environments window, selected from the dropdown menu “Packages (PyPl), searched for matplotlib and found matplotlib (3.7.1) and then clicked “Run command: pip install matplotlib. I did not save the output and the code “import matplotlib.pyplot as plt” was still marked as error.

Closed VS2022 and reopened it, then the code “import matplotlib.pyplot as plt” was not marked as error.
I don’t remember numpy having yellow squiggles, the only thing that appeared to have error is matplotlib.pyplot.

I hope this helps

**Comment by cwebster-99** [comment]
@MaxFun thanks for providing more information about this. It sounds like a Pylance bug that has been fixed in a previous release https://github.com/microsoft/PTVS/issues/7068 . If this issue persists, please open a new issue on the [PTVS repo](https://github.com/microsoft/PTVS/issues/new/choose).

**Comment by cwebster-99** [comment]
@WilliamAntonRohm please close
