### ISSUE TITLE
The page is wrong MSBuild  is not in the latest dotnet it was taken out in 2022

### ISSUE THREAD

**Issue by owenn** [MicrosoftDocs/visualstudio-docs#9149]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 911666fa-55ac-cbc1-ce79-66c058859ad9
* Version Independent ID: 571eec5d-8fb9-2401-fc4c-8a7896723eb7
* Content: [MSBuild - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild?view=vs-2022)
* Content Source: [docs/msbuild/msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@owenn 
MSBuild should still be installed when you install the .NET SDK and it should be invoked when you use `dotnet build`. If you're seeing something different, let me know the details of what you installed and how that differed from your expectations.
