### ISSUE TITLE
You need to recognize that source file folders are a fundamental property of the source code and preserve them

### ISSUE THREAD

**Issue by wkailey** [MicrosoftDocs/visualstudio-docs#9150]
This is a very good IDE, in fact one of the best ones out there. But the fact that you do not transparently reflect the organization of my source code into folders as it exists in the host operating system and as it exists in the repository, is a major shortcoming, probably the biggest shortcoming. It is very frustrating to developers working on large, complex software projects. How can your developers not know that my source code is organized into folders, and these folders are meaningful to me, and I need to be able to see the same folders in the IDE, in the OS, and in the repository? Do you honestly not get this? Really? This is just unacceptable. I feel like the Grinch: "Why for forty-three years I've put up with it now!"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [What are Visual Studio solutions & projects? - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/solutions-and-projects-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@wkailey Thanks for your feedback; we appreciate it. A question: Have you tried using the **Switch Views** button in [**Solution Explorer**](https://learn.microsoft.com/en-us/visualstudio/ide/use-solution-explorer?view=vs-2022#solution-explorer-ui)?

For example, the default view in Solution Explorer is this:

![image](https://user-images.githubusercontent.com/23244653/233473143-a4398b3e-c67f-46bc-8026-bcb2fd89c561.png)

But after selecting the **Switch Views** button, I see this:

![image](https://user-images.githubusercontent.com/23244653/233473467-b57e46b2-33ad-44af-a329-c50d85cf73b7.png)

And when I double-click the top-level folder, I see this:

![image](https://user-images.githubusercontent.com/23244653/233473706-d164599d-ff0f-4c53-b1e8-6d555d6e4237.png)

As for version control/source control, this functionality is also described in the "**View files in Solution Explorer**" section of the "[Open a project from a repo](https://learn.microsoft.com/en-us/visualstudio/get-started/tutorial-open-project-from-repo?view=vs-2022)" tutorial, where it's mentioned that the Folder view is the default for the Git tooling in Visual Studio. 

Does this help? In other words, is this the functionality that you were looking for?

**Comment by TerryGLee** [comment]
@wkailey Thanks for your continued interest in the Visual Studio family of products. While we haven't heard back from you, we'd like to share with you the following resources as we close this issue:

- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/visualstudio/ide/suggest-a-feature) IDE menu item.
- Track feature suggestions, reported product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
