### ISSUE TITLE
new coding style

### ISSUE THREAD

**Issue by barakisbrown** [MicrosoftDocs/visualstudio-docs#9153]
[Enter feedback here]

Since the code is using .net Core 6+ and if you are using inline statement, would it make sense to move the Calc class below the program file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Version Independent ID: 8067c580-66bc-f2a2-49c8-e9990547db48
* Content: [Tutorial: Create a simple C# console app  - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-console.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-console.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@barakisbrown -- Matthew, thank you for your suggestion.

For this simple change to the documentation, it may be faster for you to submit the edit yourself via a Pull Request (PR). You can do so by following these steps:

- Navigate to the page of interest
- Select the "Edit" button at the top right of the page
- Select the "Pencil" icon on the right
- Modify the text within the text box in markdown format
- Name your file change and copy the link to your Git Issue into the "extended description" box
- Select "Propose file change"
- Select "Create pull request" on the 'Comparing changes' page
- Select "Create pull request" on the 'Open a pull request' page
- Wait for an author to review and approve the change request - this can take a bit depending on the complexity

Doing this will allow authors to directly add your text to the documentation. This also displays your github image on the page of authors, and list you as a contributor to the documentation.

Please let me know if this option is of interest to you.
