### ISSUE TITLE
Please update VS2022 part

### ISSUE THREAD

**Issue by aiksiongkoh** [MicrosoftDocs/visualstudio-docs#9157]
The section below needs to be updated. Thanks.
"Create a test project in Visual Studio 2022"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c18bdf17-06e1-aaf2-b6ce-c606c0e260da
* Version Independent ID: bd627b8f-54f0-84e0-55cd-285597af022d
* Content: [Write unit tests for C/C++ - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/writing-unit-tests-for-c-cpp?source=recommendations&view=vs-2022)
* Content Source: [docs/test/writing-unit-tests-for-c-cpp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/writing-unit-tests-for-c-cpp.md)
* Product: **visual-studio-windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by WilliamAntonRohm** [comment]
@aiksiongkoh -- thank you for your feedback.  Please provide details on what needs to be updated.

**Comment by aiksiongkoh** [comment]
Sure. Please send me link for this issue since I had made several 
reports and am not sure which one this refers to.
Thanks,
Aik-Siong Koh

William Anton Rohm wrote:

**Comment by WilliamAntonRohm** [comment]
@aiksiongkoh -- Aik-Siong, thank you for your follow-up.  It is this issue:  https://github.com/MicrosoftDocs/visualstudio-docs/issues/9157

**Comment by aiksiongkoh** [comment]
Referring to "Create a test project in Visual Studio 2022" section.
In "Add a new project", I chose Google Test.
Then there was "Configure your new project" which is not documented.
After I click Create, there was the Test Project Configuration dialog which is again not documented.
I am sure there are other missing parts too. 
So it would be very useful to beginners in the world to be able to follow an up-to-date tutorial. Thanks.
