### ISSUE TITLE
Question: Microsoft 365 Dev Benefit and Microsoft Azure Credits

### ISSUE THREAD

**Issue by loaderladdy** [MicrosoftDocs/visualstudio-docs#9162]
this issue is only an issue in so far as I am not able to find the answer to the question elsewhere.

I have my Azure Credit benefit with my VS Enterprise subscription. I also have an active Microsoft 365 E5 Dev tenant set up.  Is it possible to associate the Azure Credit benefit with the Azure AD tenant associated with my Microsoft 365 E5 dev tenant?

if it is possible then could you add a section to the learning material that describes the steps required to make this work please?

Regards,

Pete

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89e73c3b-9ec3-eda3-442b-65700567ea86
* Version Independent ID: f79046c8-a4d0-1186-52de-f716f64601a5
* Content: [Microsoft 365 developer subscriptions in Visual Studio subscriptions](https://learn.microsoft.com/en-us/visualstudio/subscriptions/vs-m365)
* Content Source: [subscriptions/vs-m365.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vs-m365.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@loaderladdy -- thank you for your questions.

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@loaderladdy Hi Pete.  Can you tell me a little more about what you're hoping to accomplish here?  Are you using the same credentials to access both Azure credits and M365?

**Comment by loaderladdy** [comment]
@evanwindom Hi Evan. I was working on a solution that told me it required the sorts of features that you get with M365 E5 Dev subs benefit. In this instance AAD P1 or P2. My employer provided VS Ent subs is assigned to a Microsoft Account and my Azure Credits benefit is being used on that AAD instance.  Of course the M365 E5 Dev benefit requires you to set up a new M365 tenant that uses different credentials as it is a Work & School account.  So to work around the problem of my Azure Credit benefit not having AAD P1 or P2 I saw an opportunity to resolve this by trying to find a way to associate the Azure Credit benefit with the M365 E5 Dev tenant.  Does that make sense?

**Comment by loaderladdy** [comment]
i have added an alternative ID to my Enterprise Subscription that is my work account, but are you suggesting that I add the “work” account for my M365 E5 Developer benefit tenant as the work account?

**Comment by evanwindom** [comment]
@loaderladdy  Yes.  If you're using three different IDs to access various assets, I'm unaware of any way to link all of them.

**Comment by loaderladdy** [comment]
@evanwindom i rechecked and the alt ID I have used is the work account ID for my M365 E5 Dev benefit tenant, and not my ‘real’ work account.  When I re-read the text describing the use of the alternative email ID, which states…

> Alternate account
You can connect an alternate email to your subscription to activate your monthly Azure dev/test individual credit, access Azure DevOps, and sign-in to the Visual Studio IDE. Adding an alternate email account does not provide a copy of your subscription to your alternate email or change your subscription sign-in for my.visualstudio.com.

I think the best way to make sure my understanding is correct is through the picture below.  In the picture it shows the my question was about using my M365 E5 Dev benefit (A) with my Azure Credit benefit (1).  But I believe the wording from the above quote is telling me I can associate (A) with either (2) or (3) or both but not (1) by using an alternative ID created when I built (A).  Is that the correct interpretation?

![image](https://user-images.githubusercontent.com/15855352/236399690-2bcfba9c-4627-451d-bb50-73a6fe6c2441.jpeg)

Thanks again,

Pete

**Comment by evanwindom** [comment]
@loaderladdy 
Hi Pete, 
I checked with an engineering PM, and he said that as long as the services call our API to authenticate the subscription, they should work since both the sign-in ID and the alternate ID are associated with it.

**Comment by loaderladdy** [comment]
@evanwindom okay I'll see how I get on and update you on my experience
