### ISSUE TITLE
Screenshots of Screen color styles

### ISSUE THREAD

**Issue by NaveedAnwar786** [MicrosoftDocs/visualstudio-docs#9164]
Would be nice if there were screenshots showing how the screen would look for dark/light/etc...instead of us having to pick each one and seeing it for ourselves.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2913896-b0f2-5f3c-d733-09fe5c4e86b1
* Version Independent ID: c997c373-c946-0f02-d4c2-0904e6aab42e
* Content: [Change themes, fonts, text, and contrast for accessibility](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@NaveedAnwar786 Respectfully, we must decline this suggestion; we're not convinced that it's a good idea to take up valuable on-screen real estate with screenshots of that which can be easily seen in real-time directly within the Visual Studio user interface (in that you don't have to close and reopen Visual Studio to see what the themes look like; you can change themes within the UI and then immediately see the changes it makes and then decide which one suits you best). 

However, we appreciate your taking the time to send us your feedback, and we hope to hear from you again.
