### ISSUE TITLE
issue with "docker build -t getting-started ."

### ISSUE THREAD

**Issue by jawslab** [MicrosoftDocs/visualstudio-docs#9165]
Suggest to add

**### "change to the folder with Dockerfile, then"**

Build the updated version of the image. In the file explorer, right-click Dockerfile, then select Build Image.

Or, to build on the command line, use the same command you used before. **### "change to the folder with Dockerfile, then"**

Bash

Copy

docker build -t getting-started .

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 209c93c2-2fbb-c8a5-adc1-4fac8a6b5f5a
* Version Independent ID: 209c93c2-2fbb-c8a5-adc1-4fac8a6b5f5a
* Content: [Tutorial: Share Docker apps in Visual Studio Code](https://learn.microsoft.com/en-gb/visualstudio/docker/tutorials/docker-tutorial-share)
* Content Source: [docker/tutorials/docker-tutorial-share.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docker/tutorials/docker-tutorial-share.md)
* Product: **vs-code**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@jawslab
Thank you for the suggestion. I incorporated the change and the page should be updated later today.
