### ISSUE TITLE
wrong in image

### ISSUE THREAD

**Issue by GhayasAbouFakher** [MicrosoftDocs/visualstudio-docs#9167]
Hello, this documentation has wrong information in one image that attached to this feedback.
Selected workolad should be .Net desktop development not Desktop development with C++.

![image](https://user-images.githubusercontent.com/88130432/233941219-c2e88343-66c1-4ed7-b0ff-e1d2a5e0b5ec.png)
Regards!
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfd5474-49ef-be76-4267-4b1f72692865
* Version Independent ID: 6dfd5474-49ef-be76-4267-4b1f72692865
* Content: [Tutorial: Create Windows App SDK Apps with Visual Studio & C#](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wasdk?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-wasdk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-wasdk.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@GhayasAbouFakher, thanks for your feedback. We've updated the doc and it should be live later today.

Thanks again!
