### ISSUE TITLE
For File Nesting, There's No Such Icon as the one indicated in the image in the instructions on this page

### ISSUE THREAD

**Issue by yannduran** [MicrosoftDocs/visualstudio-docs#9182]
![image](https://user-images.githubusercontent.com/2031126/235210895-368026fc-fff5-49d6-a81a-ec9510202a2a.png)

The toggle button that the arrow points to in the image is not present in either `Community 17.5.3` or `Preview17.6.0 Preview 2.0`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2d25dd44-f173-dd83-3afc-d6608613d450
* Version Independent ID: e121cedc-5cbe-a399-e2a8-5d192aaea770
* Content: [File nesting rules for Solution Explorer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022)
* Content Source: [docs/ide/file-nesting-solution-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/file-nesting-solution-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by ghogen** [comment]
@yannduran 
I see the button in my Solution Explorer. I don't know if there is any dependency on project type, but in an ASP.NET Core Web Project, I see it as long as my Solution Explorer window is expanded large enough. It disappears if the window is resized.

**Comment by ghogen** [comment]
The article says .NET Core is required, so that explains why I don't see it in a .NET Framework project.  Have you tried different project types?

**Comment by yannduran** [comment]
@ghogen Ahh, I missed that! I was indeed using a .NET Framework project (a VSIX). This is something that would be useful for ALL project types. I had to install an extension to even get nesting working how I needed, as there seems to be no built-in way (that I could find) to manually nest a file under another file. Other than hacking the project file, of course, but who wants to do that???

Thanks!
