### ISSUE TITLE
VS 15.5.4 Call Hierarchy fails frequently and disastrously

### ISSUE THREAD

**Issue by ro-jo** [MicrosoftDocs/visualstudio-docs#920]
Solution with 100 projects, view call hierarchy hangs - status bar shows "Parsing files in solution..." (why?? how often does it need parsing?)

Any call that's reasonably abstract will crash intellisense.  From that point the search never completes.  Intellisense stops working properly.  The call hierarchy search cannot be cancelled.  Visual Studio cannot be closed - it sticks on 'Unloading the selected projects...'

Only resolution is to terminate the process and reboot PC for good measure.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ca4cea-be24-22ad-49d0-d34e3f800900
* Version Independent ID: 8cd52773-0617-684e-8136-bd4ea03515de
* Content: [Viewing call hierarchy in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/call-hierarchy)
* Content Source: [docs/ide/reference/call-hierarchy.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/call-hierarchy.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@ro-jo Thanks for the feedback. Would you mind logging this under "Product feedback" instead of "Documentation feedback" at the bottom of the Call Hierarchy topic? It will get better traction from the product team that way. Also, have you tried upgrading to the latest version, 15.7.1?

**Comment by ro-jo** [comment]
Thanks, I couldn't sign in on Product feedback, or find anywhere else to report the issue.  I think here's a good place, other users who experience the problem need to know about it.

I installed 15.7.1 today.  It flickers a lot and disables the GUI during intellisense updates so prevents me from triggering a second search while it's already updating - and as such it hasn't blown up yet.

I just don't know how msft didn't notice it during testing.

**Comment by gewarren** [comment]
@ro-jo If you are still experiencing problems with Call Hierarchy on the latest version, let me know and I'll transfer this issue to Developer Community (product feedback). For now, I'm closing this issue since it's not actionable from a docs perspective.
