### ISSUE TITLE
Documentation is for Visual Studio but has steps for Visual Studio Code.  Can't follow instructions in Visual Studio

### ISSUE THREAD

**Issue by br3nt** [MicrosoftDocs/visualstudio-docs#9201]
> **Understanding the launch.json**
> The launch.json is currently located in the .vscode folder. If you cannot see the .vscode folder in Solution Explorer, select Show All Files.
> 
> If you have worked with Visual Studio Code before, the launch.json file will look familiar. The launch.json here works in much the same way as it does in Visual Studio Code to denote launch configurations used for debugging. Each entry specifies one or more targets to be debugged.

The head of the documentation specifies that this document applies to Visual Studio, not Visual Studio Code.

Following the instructions does not work in Visual Studio.  E.g. there is no `.vscode` folder or `launch.json` file.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7aa65a08-a9e2-721d-e00c-1f28afffe2be
* Version Independent ID: babf20c3-c235-d839-7340-fb9c11c449dc
* Content: [Create a Node.js and Express app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-nodejs?toc=%2Fvisualstudio%2Fjavascript%2Ftoc.json&view=vs-2022)
* Content Source: [docs/javascript/tutorial-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@br3nt Tested the article in VS 17.6 Preview 6. There is a .vscode folder and launch.json in the VS template, provided to support round-tripping w/VS Code, I believe. From the article:
"If you have worked with Visual Studio Code before, the launch.json file will look familiar. The launch.json here works in much the same way as it does in Visual Studio Code to denote launch configurations used for debugging. Each entry specifies one or more targets to be debugged."
