### ISSUE TITLE
Sort Imports or usings missing from "Code Cleanup settings"

### ISSUE THREAD

**Issue by prlcutting** [MicrosoftDocs/visualstudio-docs#9208]
Hi,

Apologies in advance... this might not be the correct place to log this, but if it's not, I didn't know where the correct place was! 😃

This page states:

> Settings in an EditorConfig file take precedence over code styles that are specified in the Options dialog box.

However, I've noticed that running code cleanup does not honor/respect the `dotnet_sort_system_directives_first` setting defined in the `.editorconfig` file. It only works based on the "Place 'System' directives first when sorting usings" setting in the IDE.

This page also states (emphasis mine):

> _Most_ of the code cleanup settings map to one or more .NET code styles supported in .editorconfig.

This suggests that not all `.editorconfig` settings take precedence. I guess that doesn't technically contradict the previous assertion, because that pertains specifically to code styles defined in the Options dialog box, but it certainly is not intuitive.

So my request is first-and-foremast a software enhancement, where the "Sort Imports or usings" code cleanup _does_ honor the preferences defined in `.editorconfig` and override the IDE settings. That's essential for sharing consistent settings/experience across a team of developers. But if that's not possible for some reason, a clarification in the documentation would be helpful to avoid confusion, like mine.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: faebd126-53cd-1a98-bf75-38225933b0f2
* Version Independent ID: 4340fcba-6779-68d2-6c51-2ae37123dc26
* Content: [Code style options and code cleanup - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2022)
* Content Source: [docs/ide/code-styles-and-code-cleanup.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/code-styles-and-code-cleanup.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@prlcutting -- thank you for your thorough feedback.  For the software enhancement, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@Mikejo5000 -- please look into this documentation aspects of this issue.
