### ISSUE TITLE
Components are missing.

### ISSUE THREAD

**Issue by DrSharky** [MicrosoftDocs/visualstudio-docs#9209]
[Enter feedback here]

"Scroll down to the Code tools section and select Code Map and Live Dependency Validation."

These components do not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2022)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/install-architecture-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
@DrSharky They do exist, but only in the Enterprise Edition. That clarification is being added as part of Issue #8938

**Comment by WilliamAntonRohm** [comment]
@DrSharky -- thank you for your feedback.

@mgoertz-msft -- thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
