### ISSUE TITLE
This may be broken in VS Version 17.5.5

### ISSUE THREAD

**Issue by DarkNoir** [MicrosoftDocs/visualstudio-docs#9210]
After following the steps in the article, only the Angular command window opens and the asp.net core projects command window never opens. Visual Studio thinks the Angular app has not completed startup/deployment. And yes, asp.net core project file has the edits that were defined in the article that look like what's supposed to prevent that from happening. Did something change in VS releases that may require some modifications to this article? The deployment settings have a script that runs "ng start" so it never returns and VS thinks it never finishes deployment. This template seems more of a hacked mess than a way to officially support this paradigm.  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@DarkNoir I will look into this

**Comment by Mikejo5000** [comment]
@DarkNoir Thanks for your feedback. I'm asking about this. But please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.

**Comment by Mikejo5000** [comment]
@DarkNoir @cristianfd This issue appears to be something that was fixed in 17.6, due to Node using ipv6 instead of ipv4.

**Comment by Mikejo5000** [comment]
Also, a workaround: downgrade node to <= 16 or add a commandline flag " --host 127.0.0.1" in their package.json in their "start" script to force it to use ipv4 like before

**Comment by DarkNoir** [comment]
Yes, verified fixed in 17.6

William Wallace
Technology Leader
William Wallace | LinkedIn<https://www.linkedin.com/in/wwallace/>
***@***.***
