### ISSUE TITLE
Typo: shortcut key

### ISSUE THREAD

**Issue by benny779** [MicrosoftDocs/visualstudio-docs#9222]
https://learn.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2022#:~:text=button%2C%20or%20press-,Alt%2BE,-.

In the Quick Replace dialog box, make sure to select the Use Regular Expressions button, or press ~~Alt+E~~ Alt+R.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@benny779 -- Benny, in my Visual Studio 2022 Quick Replacement dialog, Alt-e does in fact toggle the Use Regular Expressions button, but Alt-r doesn't seem to do anything there.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by benny779** [comment]
@WilliamAntonRohm 
This is true. I just checked and you are right.
It may have changed when I updated VS (about 2 weeks ago).
