### ISSUE TITLE
New ASP.NET with React template troubles

### ISSUE THREAD

**Issue by Lanshir** [MicrosoftDocs/visualstudio-docs#9223]
Hello, i'd like to report some issues i had on publishing reactapp with new template:

1. WebApi Program.cs file is missing  app.MapFallbackToFile("index.html"); line, which causes 404 errors for spa routes other then index.html in non-development environment;
2. Reactapp esproject has building error when running without NetFramework SDK installed (or publishing in net7.0 docker). For more details look here - https://youtrack.jetbrains.com/issue/RIDER-91987.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@Lanshir -- thank you for your feedback.  If you feel the second point is product-related, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@Mikejo5000 -- please look into the documentation aspects of this issue.

**Comment by Mikejo5000** [comment]
@Lanshir I asked the product team about this. If these require a fix, it looks like product fixes will be needed to resolve issues. Please use [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
