### ISSUE TITLE
Printable version of Default Keyboard Shortcut shows 2019

### ISSUE THREAD

**Issue by TheEnjiBenji** [MicrosoftDocs/visualstudio-docs#9225]
Minor detail: the printable version of the Default Keyboard Shortcut has "Visual Studio 2019" in its header instead of just Visual Studio as shown in the preview.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 23332067-130b-a343-b902-7d09680d3519
* Version Independent ID: 09bb5d36-f067-5422-2ab2-e4c7a8f1d6ed
* Content: [Keyboard shortcuts - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/default-keyboard-shortcuts-in-visual-studio?view=vs-2022&utm_source=vshelp)
* Content Source: [docs/ide/default-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/default-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@TheEnjiBenji A fix is in process. We'll close this now, as it's been previously reported (see https://github.com/MicrosoftDocs/visualstudio-docs/issues/9116) but we thank you for taking the time to let us know.
