### ISSUE TITLE
Create an Angular app - Some inaccuracies and missing info

### ISSUE THREAD

**Issue by sedwick1024** [MicrosoftDocs/visualstudio-docs#9226]
It says in step 2 to "select Standalone TypeScript Angular Template", while the screenshot and VS show "Standalone TypeScript Angular Project."  There is no mention of the "Create" button to click after step 3, nor of the command window that briefly pops up, which asks if you want to submit information as it outputs installation results.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 187a9aa8-1f64-5a37-f8a6-0d408642014e
* Version Independent ID: 1fb3868f-4175-279e-6372-91765426547c
* Content: [Create an Angular app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-create-angular-app?view=vs-2022)
* Content Source: [docs/javascript/tutorial-create-angular-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-create-angular-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@sedwick1024 I didn't see a window that asks if you want to submit information. However, I'm updating the other steps that you mentioned. Thanks for the feedback!

**Comment by Mikejo5000** [comment]
Update should be live by EOD today.
