### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/visualstudio-docs#923]
# Idea Title
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.dynamicdataattribute.-ctor?view=mstest-net-1.2.0#Microsoft_VisualStudio_TestTools_UnitTesting_DynamicDataAttribute__ctor_System_String_System_Type_Microsoft_VisualStudio_TestTools_UnitTesting_DynamicDataSourceType_

## Issue Details
Would be nice to have more of a description for the 3 arg constructor in the DynamicDataAttribute class.

this issue is from https://github.com/MicrosoftDocs/feedback/issues/243

**Comment by gewarren** [comment]
@jayaranigarg Jayarani, do you own the Microsoft.VisualStudio.TestTools.UnitTesting namespace? If so, can you address this issue? If not, can you let me know who I should assign this to? Thank you.

**Comment by jayaranigarg** [comment]
@gewarren : I would be the rightful owner for this. If I understand you correctly, you want me to provide more description of 3 arg constructor in a way stating that how is it different from a 2 arg constructor? Correct me If I am wrong. Arguments of the constructor are already described.

**Comment by gewarren** [comment]
@jchesshir can you take a look at the proposed change at Microsoft/testfx#422 and let us know if that is what you are looking for, or something different?

**Comment by jayaranigarg** [comment]
@jchesshir @gewarren : Any updates on the PR I raised?

**Comment by jayaranigarg** [comment]
Pushed in the PR. Feel free to close this.

**Comment by gewarren** [comment]
@jayaranigarg Thank you so much!

**Comment by jchesshir** [comment]
@gewarren Sorry.  I've been out of this realm for a little while.

Looks good.  Thank you very much!
