### ISSUE TITLE
Windows Infra use cases

### ISSUE THREAD

**Issue by FlorianHeigl** [MicrosoftDocs/visualstudio-docs#9233]
This looks really cool...
Any chance you could take an hour and show it to the people responsible for tuning windows update/TiWorker.exe with it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d338de3f-935c-06e9-cc91-2b934eacf491
* Version Independent ID: d338de3f-935c-06e9-cc91-2b934eacf491
* Content: [Identify hot paths with the Flame Graph - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/profiling/flame-graph?view=vs-2022)
* Content Source: [docs/profiling/flame-graph.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/profiling/flame-graph.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@FlorianHeigl -- Florian, thank you for your positive feedback and suggestion.  This repo is solely for documentation issues, and this is out-of-scope.

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
