### ISSUE TITLE
Not working with Blazor projects

### ISSUE THREAD

**Issue by cookston** [MicrosoftDocs/visualstudio-docs#9234]
Why doesn't this work with Blazor projects.

See https://stackoverflow.com/questions/76249594/visual-studio-2022-debugging-string-visualizer-watch-magnifying-glass-not-appear

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b3761f60-ec2f-2c51-cfa1-1e192c71bebe
* Version Independent ID: 714a4254-b006-5509-9fa1-355da2184942
* Content: [String Visualizer (Text, XML, HTML, JSON) - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/string-visualizer-dialog-box?view=vs-2022)
* Content Source: [docs/debugger/string-visualizer-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/string-visualizer-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@cookston -- thank you for your feedback.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
