### ISSUE TITLE
I can not find the Architecture menu 

### ISSUE THREAD

**Issue by RedhwanGhailan** [MicrosoftDocs/visualstudio-docs#9235]
Hey, 

I am trying to create a dependency graph and based on the info it is under the menu "Architecture". But I can not find that menu in the VS. 

FYI I am using Professional and Enterprise version (2022)
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6db0df9a-ef09-a374-d289-9beda002a71d
* Version Independent ID: 2fcc9ad1-f65f-b242-ef0b-3a128ecd23a6
* Content: [Create dependency diagrams from your code - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/create-layer-diagrams-from-your-code?view=vs-2022)
* Content Source: [docs/modeling/create-layer-diagrams-from-your-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/create-layer-diagrams-from-your-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
@RedhwanGhailan The reason you may not see this menu is most likely one of the following:
* You don't have the Visual Studio Enterprise SKU (see [Edition support for architecture and modeling tools](https://learn.microsoft.com/en-us/visualstudio/modeling/analyze-and-model-your-architecture?view=vs-2022#edition-support-for-architecture-and-modeling-tools)
* You haven't selected `Live Dependency Validation` in the VS Installer (see [Install Code Map and Live Dependency Validation](https://learn.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2022))

**Comment by WilliamAntonRohm** [comment]
@RedhwanGhailan -- Redhwan, thank you for your feedback.

@mgoertz-msft -- Marco, thank you for clarifying.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
