### ISSUE TITLE
Every VSTO page should have the warning that it's no longer compatible with future versions of Outlook.

### ISSUE THREAD

**Issue by dombat** [MicrosoftDocs/visualstudio-docs#9237]
Every VSTO page should now have the warning (such as the one of https://learn.microsoft.com/en-us/office/dev/add-ins/overview/learning-path-transition#Overview ) saying that VSTO is no longer compatible with future versions of Outlook.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c7a1da2-e11d-a8a6-f5df-c3db41df72ba
* Version Independent ID: f3a1171e-c739-185a-a7e9-f28f5b9881b1
* Content: [Create VSTO Add-ins for Office by using Visual Studio](https://learn.microsoft.com/en-us/visualstudio/vsto/create-vsto-add-ins-for-office-by-using-visual-studio?view=vs-2022)
* Content Source: [docs/vsto/create-vsto-add-ins-for-office-by-using-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/create-vsto-add-ins-for-office-by-using-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by WilliamAntonRohm** [comment]
@dombat -- Dominic, thank you for your continued interest in our documentation.  I am investigating which articles should add such a warning.
