### ISSUE TITLE
some differences of WPF/UWP and VS/Blend

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#924]
XAML is in both WPF and UWP as far as I understand. But there are problems using resource dictionaries, and of course, VS and Blend behave a little different. Please tell me if this is something intentional, or let developers know the issue.

for WPF, everything is nice in Blend. It asks for and creates a new dictionary file, and includes it in App.xaml. But VS does not include a "new" button, and one needs to include the dictionary by hand. After that, every resource can be extracted into dictionary file.

for UWP, contrary to my expectations, Blend has "new" button, but will not include this file in the application or in its pages, nor extract the resource to the file. Both VS and Blend can use dictionary file if filled and included manually (and need a rebuild), but still, none can extract a resource back into the file. 

by the way, it would be good to reference an address in the paragraph where "Resource Dictionary" is mentioned. I have one for UWP: https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/resourcedictionary-and-xaml-resource-references

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc63992-69ba-beeb-591b-c95b4af9fb53
* Version Independent ID: b9f2015e-e7c7-0f91-1a02-87dcd95d3312
* Content: [How to create and apply a resource - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/how-to-create-and-apply-a-resource)
* Content Source: [docs/designers/how-to-create-and-apply-a-resource.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/how-to-create-and-apply-a-resource.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yilmazdurmaz Thank you for the feedback!

**Comment by gewarren** [comment]
@yilmazdurmaz I am just now getting around to adding the link to the resource dictionary page - thank you for pointing that out.

For the product feedback, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool. When you do this, your report becomes part of the work items that are tracked on Visual Studio [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
