### ISSUE TITLE
New EV Code Signing certificates requirements (stored on HSM and can't be exported to a file) don't work for VSTO cloud build pipelines

### ISSUE THREAD

**Issue by CameronDwyer** [MicrosoftDocs/visualstudio-docs#9243]
As of June 2023 EV Code signing certificates are required to be stored on HSM devices. For cloud based builds it is possible to have the EV Code Signing certificate stored in Azure Key Vault (which is backed by HSM - in premium SKU) but you can't extract the certificate as a local file to sign with mage. For standard signing of files, AzureKeySign can be used to sign files directly with the certificate in Azure Key Vault as described here > https://learn.microsoft.com/en-us/answers/questions/732422/ev-code-signing-with-azure-keyvault-and-azure-pipe. How can we accomplish this for VSTO projects?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aa1d480-9c75-bbac-9fe2-0119cd556e4a
* Version Independent ID: 44c115b0-721d-4f00-48a5-7768328a9c03
* Content: [How to: Sign Office solutions - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/vsto/how-to-sign-office-solutions?view=vs-2022)
* Content Source: [docs/vsto/how-to-sign-office-solutions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/how-to-sign-office-solutions.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@CameronDwyer please take a look at the [dotnet/sign: Code Signing CLI tool supporting Authenticode, NuGet, VSIX, and ClickOnce (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fsign&data=05%7C01%7CJohn.Hart%40microsoft.com%7C982972761fa14ba65abf08db56f4df1c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638199381962896145%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S3FYhaRgO9SNdPCwEDdpuNXWhBWFZfmXsH%2FmizVo34c%3D&reserved=0)

**Comment by AvishekElite** [comment]
Hello, Does this work for .NET Framework 4.8 projects? Is this process i.e. storing the certificate on Azure Key Vault and using AzureSignTool to sign artifacts supported for office vsto addins and manifest files? We're storing the certificate on AKV for the new HSM requirement for private keys and using ADO pipelines to sign other file types e.g. exe and dlls. But it seems to be not working for vsto files.
