### ISSUE TITLE
Missing Links

### ISSUE THREAD

**Issue by samzuercher** [MicrosoftDocs/visualstudio-docs#9244]
Can you Add these Links / Explanaitions:
- github-repo
- where to get the 'angular and asp.net core template (preview)'
- what to 'Modify' in the Visual-Studio-Installer

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Please see the **Prerequisites** section and the **Create a front end app** section. This tells you the VS installer workload you need and the instructions to create the project based on the Preview template. (The template is not available on GitHub).

**Comment by Mikejo5000** [comment]
@samzuercher I think I see what you're saying. To use the Preview template, it seems like you would need a Preview version of VS. However, the Preview template is available in VS 17.5, so you don't actually need the Preview version of VS. (If someone wants the Preview version installed, it is easier to use the provided VS download link, and then select the Preview option on the far right.)

**Comment by samzuercher** [comment]
I did not have the preview-template available by only installing the toolchain. But probably it's just my setup / environment or something.

I think, probably it would be easier to be able to just download template-files instead of using the installer.

thanks,
