### ISSUE TITLE
XAML, but WPF, UWP or both?

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#925]
I have begun reading these pages starting at "https://docs.microsoft.com/en-us/visualstudio/designers/designing-user-interfaces".

I sometimes have difficulties with the content. With the date it has, I assumed it is (and evolves to be) a part of Windows 10 related design.

I sometimes stumble upon links that go to W8.1 development pages. and sometimes things are not working for UWP apps.

How shall I think about these? are they things to be corrected? or things to be accepted?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cc63992-69ba-beeb-591b-c95b4af9fb53
* Version Independent ID: b9f2015e-e7c7-0f91-1a02-87dcd95d3312
* Content: [How to create and apply a resource - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/how-to-create-and-apply-a-resource)
* Content Source: [docs/designers/how-to-create-and-apply-a-resource.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/how-to-create-and-apply-a-resource.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yilmazdurmaz If links are going to Windows 8.1 articles, then those should probably be corrected. But to be honest, these articles haven't been updated in a long time, so I can't say for sure whether something should work on UWP or not. If you have a specific thing in mind, I can ask the product team to verify whether it should work for UWP.

**Comment by msebolt** [comment]
@yilmazdurmaz @gewarren Thank you for the feedback!  

WPF and UWP are two entirely different application frameworks.  While there's a push by Microsoft to adopt the UWP, the platform is limited to .NET core functionality and only creating apps for the Microsoft Store, see https://docs.microsoft.com/windows/uwp/get-started/universal-application-platform-guide for details.

However, if your application requires full .NET support you should use WPF, see  https://docs.microsoft.com/windows/desktop/choose-your-technology for a detailed comparison.

We are continually in the process of fixing links and broken tutorials.  If specific examples can be addressed please comment below.
