### ISSUE TITLE
Menu options don't align with my VS build.

### ISSUE THREAD

**Issue by MNTrailBoss** [MicrosoftDocs/visualstudio-docs#9262]
[There is no View==>Other Window option.   I'm running build 1.78.2 on Windows 10.   So I'm trying to import pygame in a program, and I need to load this into the environment some how.]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ca858db-d7bf-c894-af0a-eb1ba07c29ea
* Version Independent ID: 330f9197-38cd-73b7-c2cc-5d032a3bdc33
* Content: [Python in Visual Studio tutorial step 5, install packages](https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages?view=vs-2022)
* Content Source: [docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/tutorial-working-with-python-in-visual-studio-step-05-installing-packages.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by WilliamAntonRohm** [comment]
@MNTrailBoss -- Bob, thank you for your feedback.  I just tried Visual Studio 2022 and added the Python environment (see [Install Python support in Visual Studio](https://learn.microsoft.com/en-us/visualstudio/python/tutorial-working-with-python-in-visual-studio-step-00-installation?view=vs-2022)) and I see the menu item as described.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
