### ISSUE TITLE
about "Tour of the Tools panel"

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#927]
At first, I thought clicking on the arrow in the bottom-right corner of these tools, they would show the other elements of the category shown in A to F. But one needs to press and hold the mouse on the tool to show them. I think this would be nice to include in the paragraph.

And the video link at the end goes to a 6 years old tutorial of good old days. I guess it is time for a new series about the new "Blend for VS" from MS/VS team (or a link change maybe, if one exists already)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fb4a86d-efe1-3ff6-2456-eac6659c6d09
* Version Independent ID: a1faa99b-0e1a-8291-f87c-747dcccb3b0b
* Content: [Creating a UI by using Blend for Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/creating-a-ui-by-using-blend-for-visual-studio)
* Content Source: [docs/designers/creating-a-ui-by-using-blend-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/creating-a-ui-by-using-blend-for-visual-studio.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@yilmazdurmaz I apologize that many of these docs are out-of-date, and I thank you again for all your suggested improvements!
