### ISSUE TITLE
Extract Method nukes visual studio if it fails

### ISSUE THREAD

**Issue by dalton478** [MicrosoftDocs/visualstudio-docs#9270]
I ran Extract Method on a block of code. It gave me an error box saying not all code paths return a value. I then took the option to do it anyway, with plans to fix the issues manually.

The operation then failed quietly. I didn't realize it at the time but it had also nuked visual studio in the process.

A few minutes later I noticed that intellisense had disappeared for many parts of VS, the compiler failed for invalid reasons, and restarting VS and the entire computer had no effect on the issue.

This is unacceptable for a feature that is not marked as experimental. It appears my only option is to reinstall VS from scratch.

Here is info from the about screen; the language is C#:
Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.3.6

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3506512-caae-6f4e-d27c-5204edb95e77
* Version Independent ID: 84c00803-50fe-c354-491e-e5c2f65d8d07
* Content: [Extract a method - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/extract-method?view=vs-2022)
* Content Source: [docs/ide/reference/extract-method.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/extract-method.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by dalton478** [comment]
To follow up, I updated to the latest Visual Studio 17.6.2, restarted the computer, and tried browsing to other branches in the repo. The intellisense and compiling issues persisted. No files were marked as changed in the branch where this originated.

The mitigation that worked was to reclone my repo.

I don't require resolution for this but have no plans to use that feature again. If anyone else ends up here with the same issue, just bite the bullet and reclone. It's unfortunate but since a mitigation step exists it is unlikely to be addressed anytime soon.

**Comment by WilliamAntonRohm** [comment]
@dalton478 -- Dalton, thank you for your feedback and research, and glad to hear you were able to work it out.

You're welcome to add this here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
