### ISSUE TITLE
Windows no longer supports python applications on app service

### ISSUE THREAD

**Issue by tspring418** [MicrosoftDocs/visualstudio-docs#9272]
It is noted that windows is no longer a supported option for python on app service:
https://learn.microsoft.com/en-us/azure/app-service/configure-language-python
https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/python_support.md

I believe noting a disclaimer would be good on this page or a link to the supported versions and OS's!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 104afbeb-46ae-8fc0-d70e-c801a1645e8a
* Version Independent ID: c891f059-05a6-3af4-ec80-0f93e4b6c95b
* Content: [Publish a Python app to Azure App Service on Windows - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/publish-to-app-service-windows?view=vs-2022)
* Content Source: [docs/python/publish-to-app-service-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/publish-to-app-service-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by anandmeg** [comment]
@tspring418, thanks for your feedback. 
We've updated the doc and the changes should be live later today. 

Thanks again.
