### ISSUE TITLE
Component ID for .NET Desktop Development Workload is incorrect

### ISSUE THREAD

**Issue by gregboyko** [MicrosoftDocs/visualstudio-docs#9284]
The documentation shows the component ID for the .NET Desktop Development Workload as:

    Microsoft.VisualStudio.Workload.ManagedDesktopproductArchx64

The correct component ID is:

    Microsoft.VisualStudio.Workload.ManagedDesktop

The impact of this incorrect documentation is that the workload will not be installed if a user uses the ID in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b29a1009-5ef4-707b-258e-fe8bbe7275b6
* Version Independent ID: 00fac5a7-fc6d-c9cb-2d26-d820c7055890
* Content: [Visual Studio Enterprise workload and component IDs](https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022&preserve-view=true)
* Content Source: [docs/install/workload-component-id-vs-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/workload-component-id-vs-enterprise.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by DmitriyShepelev** [comment]
I just hit this issue too. There are multiple component IDs incorrectly suffixed with `productArchx64`:
- `Microsoft.VisualStudio.Workload.UniversalproductArchx64`
- `Microsoft.VisualStudio.Workload.NativeDesktopproductArchx64`
- `Microsoft.VisualStudio.Workload.NativeGameproductArchx64`

**Comment by WilliamAntonRohm** [comment]
@gregboyko, @DmitriyShepelev -- Greg, Dmitriy, thank you for catching these.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@anandmeg -- Megha, please review this change in [private PR 11297](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/11297).

**Comment by anandmeg** [comment]
@gregboyko, thanks for your feedback. We've updated the page and the changes should be live now.
Thanks!
