### ISSUE TITLE
Add 2nd Firewall URL for Visual Studio Subscriptions Licensing Service

### ISSUE THREAD

**Issue by russ-msft** [MicrosoftDocs/visualstudio-docs#9288]
The section that says: Visual Studio Subscriptions Licensing Service

Should add the following 2nd URL - https://api.subscriptions.visualstudio.microsoft.com/Me/Entitlements/IDEBenefits

Questions contact Microsoft alias: **russc** and **jamew**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2022#urls-to-add-to-an-allowlist-and-ports-and-protocols-to-open)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
Thanks @russ-msft. Doc is updated and changes are live now.
