### ISSUE TITLE
Trying to launch start page.

### ISSUE THREAD

**Issue by terryhutt** [MicrosoftDocs/visualstudio-docs#9289]
Trying to launch Start page. Where did it go? View doesn't list it. Tools -> Options -> Environment -> Start up doesn't exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38a2bfea-c771-a183-ed02-d2338516a223
* Version Independent ID: b0e5f18b-29bb-858c-6b04-b4e72240f777
* Content: [Change the startup experience - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/customizing-the-start-page-for-visual-studio?view=vs-2022)
* Content Source: [docs/ide/customizing-the-start-page-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/customizing-the-start-page-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@terryhutt -- Terry, please try Tools > Options > Environment > General, and scroll to the bottom to see the `On startup` options:

![Startup](https://github.com/MicrosoftDocs/visualstudio-docs/assets/27738025/97f3c08e-9db9-4490-bb18-08327e7fbee0)

cc @TerryGLee for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by TerryGLee** [comment]
@terryhutt @WilliamAntonRohm The content is correct for Visual Studio 2019 but not for Visual Studio 2022. I'll get a content fix in and update this issue when it's published.

**Comment by TerryGLee** [comment]
@terryhutt The page has been updated to reflect the UI in Visual Studio 2022. We'll close this issue now, with our thanks to you for helping to improve the Visual Studio documentation. Cheers!
