### ISSUE TITLE
Download PDF link is down.

### ISSUE THREAD

**Issue by adriannadiaz** [MicrosoftDocs/visualstudio-docs#929]
The link

https://docs.microsoft.com/en-ca/scripting/opbuildpdf/javascript/TOC.pdf?branch=live

 to Download PDF documentation at 

https://docs.microsoft.com/en-ca/scripting/javascript/advanced/recursion-javascript

Does not work. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e391bc6b-eb62-016e-7a19-137f9fdcfc1b
* Version Independent ID: 4af94735-aefb-88e3-787d-6607c2c3fef3
* Content: [Recursion (JavaScript)](https://docs.microsoft.com/en-ca/scripting/javascript/advanced/recursion-javascript)
* Content Source: [scripting-docs/javascript/advanced/recursion-javascript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/scripting-docs/javascript/advanced/recursion-javascript.md)
* Service: **windows-client-threshold**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
@adriannadiaz Thank you for reporting this! The PDF is working now. Closing the issue.
