### ISSUE TITLE
Error in Workload ID when downloading VS 2022 using CLI

### ISSUE THREAD

**Issue by cookiem3r** [MicrosoftDocs/visualstudio-docs#9292]
When attempting to download VS2022 Managed Desktop layout using the specified layout ID resulted in an error.

Error: The package 'Microsoft.VisualStudio.Workload.ManagedDesktopproductArchx64' is not recognized.
Error: Failed to plan for Layout.
Error: Setup completed with errors.
 
The correct package ID seems to be 'Microsoft.VisualStudio.Workload.ManagedDesktop' 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe411145-ff47-dfe5-1e57-db8d54671b58
* Version Independent ID: 4dac6d72-8c3c-dec8-d473-a2902e4e1fb9
* Content: [Visual Studio Professional workload and component IDs](https://learn.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-professional?view=vs-2022)
* Content Source: [docs/install/workload-component-id-vs-professional.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/workload-component-id-vs-professional.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@cookiem3r -- Yong, thank you for your feedback.  This issue is a subset of #9284.
