### ISSUE TITLE
why not jsut ask me to install the dependency?

### ISSUE THREAD

**Issue by Tom-Neverwinter** [MicrosoftDocs/visualstudio-docs#9293]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d901b841-b868-50e8-3036-c2eb1d129c86
* Version Independent ID: d901b841-b868-50e8-3036-c2eb1d129c86
* Content: [MSBuild error MSB8020 - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8020?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(MSB8020)%26rd%3Dtrue&view=vs-2022)
* Content Source: [docs/msbuild/errors/msb8020.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb8020.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@Tom-Neverwinter -- Tom, thank you for your question.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
