### ISSUE TITLE
Should Language be cs or C#

### ISSUE THREAD

**Issue by caspChristian** [MicrosoftDocs/visualstudio-docs#9297]
Several of the examples has `Language="C#"`
While the documentation says it should be `Language="cs"`
The examples might need an overview?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b8c66d6-dd9b-dddc-dd69-41d22284ec10
* Version Independent ID: 1b750d67-95da-aa4c-ad32-2de54d7a46c5
* Content: [MSBuild Inline Tasks with RoslynCodeTaskFactory - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-roslyncodetaskfactory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-roslyncodetaskfactory.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@caspChristian -- Christian, thank you for catching this.  I am updating the article.

**Comment by WilliamAntonRohm** [comment]
@caspChristian -- Christian, thank you for your feedback.  I have updated the documentation and it should be live by tomorrow.
