### ISSUE TITLE
Should describe behavior of existing item with ItemName parameter

### ISSUE THREAD

**Issue by binki** [MicrosoftDocs/visualstudio-docs#930]
When using the `ItemName` parameter with an existing item, the output parameter values are added to the existing item. The documentation does not clearly specify this, leaving the reader wondering if the item is cleared first when written to.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fcd9d10-b620-994d-a92e-3fe2ac7b9cae
* Version Independent ID: 5b884eee-e0fd-5741-6ab8-b0c1b0222753
* Content: [Output Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/output-element-msbuild)
* Content Source: [docs/msbuild/output-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/output-element-msbuild.md)
* Service: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@binki Thank you. I will plan to update the docs for this issue.
