### ISSUE TITLE
Dockerfile dependencies are old/broken

### ISSUE THREAD

**Issue by oshea00** [MicrosoftDocs/visualstudio-docs#9300]
The instructions on building the first Dockerfile result in the build failing due to dependencies that have
since changed related to the package.json in the sample project. Specificaly the jest package wants a newer node version 14 or greater. The node:12-alpine is too old. I updated the docker file as follows and that fixes the build:

```
FROM node:14-alpine
RUN apk add --no-cache python3 g++ make
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "/app/src/index.js"]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cddd74b1-e0f1-1cae-e92d-c7c2b81e77e3
* Version Independent ID: f853e977-81c2-64d6-682e-1e712344cbad
* Content: [Get started with Docker apps in Visual Studio Code](https://learn.microsoft.com/en-us/visualstudio/docker/tutorials/docker-tutorial?WT.mc_id=vscode_docker_aka_getstartedwithdocker)
* Content Source: [docker/tutorials/docker-tutorial.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docker/tutorials/docker-tutorial.md)
* Product: **vs-code**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@oshea00 -- Mike, I've updated the documentation and it should be live by tomorrow.
