### ISSUE TITLE
expired(?) product content

### ISSUE THREAD

**Issue by yilmazdurmaz** [MicrosoftDocs/visualstudio-docs#931]
It seems there is a lot of work to be done in these documents here. Most of the content is linked to old "Expression Blend" series and does not reflect new "Blend for VS". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d1891f3-ab1c-7638-584e-2d32c6e974bc
* Version Independent ID: a8d765ba-3a89-4552-fd68-f0eac8b0b5d8
* Content: [Insert controls and modify their behavior in XAML Designer - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/designers/insert-controls-and-modify-their-behavior-in-xaml-designer)
* Content Source: [docs/designers/insert-controls-and-modify-their-behavior-in-xaml-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/designers/insert-controls-and-modify-their-behavior-in-xaml-designer.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
~1000 page views per month = P2

**Comment by gewarren** [comment]
@diverdan92 Is it worthwhile to invest in updating Blend for VS docs? How much is it used?

**Comment by diverdan92** [comment]
@gewarren - Blend is worth updating the docs for. We have decent usage and we are still making several updates to the product. Maybe we can sync this week on a strategy to refresh the docs?

**Comment by gewarren** [comment]
The Blend docs have been updated (this particular article was removed and now redirects to the VS 2015 version).
