### ISSUE TITLE
By default, the webapi project will ignore launchSettings.json and only listen to the default port of 5000.

### ISSUE THREAD

**Issue by craniumrat** [MicrosoftDocs/visualstudio-docs#9310]
If you only follow the steps provided, vue_config.js will have a proxy set to https://localhost:7018. launchConfiguration.json will also have the same value for the https profile. However, the way run is configured, it will not use any of of the profiles and will simply default to listening on port 5000. Either the net run command should specify the profile to be used, or the project template should add the environment variable ASPNETCORE_URLS with the proxy value set in vue_config.js.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@craniumrat -- Mridul, thank you for your clear feedback.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@craniumrat Thanks for your feedback! I just updated the article based on the templates released in VS 2022 17.7.2. The Vue template uses Vite (vite.config.js) now instead of the Vue CLI, and the steps have been changed a bit. If you continue to encounter this issue with the updated template, please let us know.
