### ISSUE TITLE
Document correction required

### ISSUE THREAD

**Issue by JohnDnnstn** [MicrosoftDocs/visualstudio-docs#9315]
Minor correction required to documentation:
Point 8 of section "Manually create an item template" in the VS2022 version still points to VS2019

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e44d5ce-a797-8367-d4d0-0c3a29f0b18c
* Version Independent ID: d3203ea3-2a1b-f418-62a9-0024c5e03685
* Content: [Create item templates - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-create-item-templates?view=vs-2022)
* Content Source: [docs/ide/how-to-create-item-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-create-item-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@JohnDnnstn -- John, thank you for catching this.  I am updating the article.
