### ISSUE TITLE
Add information to article to aid troubleshooting of error messages

### ISSUE THREAD

**Issue by nick599** [MicrosoftDocs/visualstudio-docs#9323]
[Enter feedback here]
Currently the article only contains limited information that allows users / developers to troubleshoot errors e.g. crashes & hangs.
Requesting more comprehensive & detailed information is added to enable this.
E.g. a table of common extensions (eg .rdl), language(s) used (eg c++), links to articles about file structure of those extensions, suggested software on windows that can aid troubleshooting, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and install extensions - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2022#extension-crash-and-unresponsiveness-notifications)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/finding-and-using-visual-studio-extensions.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@nick599 Thanks for taking the time to write up this issue. Respectfully, we must decline your request at this time, as it's beyond the scope of this page's design. The purpose of the "Find, install, and manage extensions" page is to show how to find, install, and from a top-level perspective, manage extensions. It isn't meant to delve into the detail that you've described (some of which is covered in our [**Visual Studio Extensibility**](https://learn.microsoft.com/visualstudio/extensibility/) pages), nor is it meant to delve into C++ scenarios (which are covered in a separate [**Microsoft C++, C, and Assembler**](https://learn.microsoft.com/en-us/cpp/?view=msvc-170) content set).

That being said, we'll log this request in our backlog to consider for future updates, as we are making changes to the extensions space that might see us re-envisioning our extensions content, too (see the [**Build Better Extensions with VisualStudio.Extensibility (Preview 3)**](https://devblogs.microsoft.com/visualstudio/visualstudio-extensibility-preview-3/) blog post for details).

Meanwhile, we'll close this issue now; again, we appreciate your taking the time to send us your feedback, and we thank you for your continued interest in both Visual Studio and its documentation.
