### ISSUE TITLE
Limit download rate?

### ISSUE THREAD

**Issue by danield72** [MicrosoftDocs/visualstudio-docs#9324]
I've been interested in this sort of thing since it's no longer possible to download Visual Studio ISOs.

For various reasons (primarily: isolation) I tend to install VS in multiple virtual machines, each working independently.  As my internet connection is slow, installing VS through the internet is a *very* time-consuming task - multiply by the number of VMs that have to install it, and it becomes an exercise in frustration.  Even a "regular" update has to be planned carefully so as not to impact my day.  As a result, many of my VMs simply lag a few versions behind as I don't bother updating all of them religiously.

I have an old machine that I essentially use as a NAS.  I'm not going to install VS on there, but if I can just tell it to download all files, so *other* systems can access the latest installer from the network share, that'd be ideal.  I can do that with the --layout option.  But:

The only problem is that I don't want this machine to hog my entire bandwidth for hours at a time.  Which leads me to this - is there a way to tell the installer to limit its download speed to [xyz] KB/s?  If it takes a whole week to download all files from scratch, I'm fine with letting them trickle in slowly over time.

The way it works right now is that while the download is taking place, it's going as fast as it can...which slows everything else down until that task is done.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@danield72 -- Daniel, thank you for your thorough feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
