### ISSUE TITLE
I can not find VSDiagnostics.exe after installation of Remote Tools for Visual Studio 2022

### ISSUE THREAD

**Issue by spietre** [MicrosoftDocs/visualstudio-docs#9327]
I can not find VSDiagnostics.exe after installation of Remote Tools for Visual Studio 2022 to my path C:/RemoteToolsVS22 on production machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: da087498-0880-91ec-7e9a-b0a2c1dca212
* Version Independent ID: efd0ec0a-bf21-4e73-54b9-b434ab9ca313
* Content: [Measure performance from the command line - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/profiling/profile-apps-from-command-line?view=vs-2022#config_file)
* Content Source: [docs/profiling/profile-apps-from-command-line.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/profiling/profile-apps-from-command-line.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@spietre -- thank you for your feedback.  On my machine, `VSDiagnostics.exe` is located under

`C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Team Tools\DiagnosticsHub\Collector`


I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
