### ISSUE TITLE
Attribute referred to is deprecated

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/visualstudio-docs#9329]
Doc says 
> Applying the [SuppressIldasmAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.suppressildasmattribute) attribute to an assembly or module prevents Visual Studio from attempting decompilation.

However the link to the attribute clearly states this attribute is obsolete and has no effect in .net6+.
Please add documentation on how to correctly prevent Visual Studio from violating terms of use of closed source software.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 321e264c-24ad-ce2e-b82d-3e6ddee86b71
* Version Independent ID: ef0c9ec0-8cac-e90b-a30d-d2c1c60de6f2
* Content: [Decompile .NET code while debugging - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/decompilation?view=vs-2022)
* Content Source: [docs/debugger/decompilation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/decompilation.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@dotMorten -- Morten, thank you for your feedback.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
Asking about this.

**Comment by Mikejo5000** [comment]
Updating the doc. Visual Studio still honors this attribute, even though it is obsolete in .NET 6.

**Comment by dotMorten** [comment]
Thanks for confirming

**Comment by Mikejo5000** [comment]
Update should be live by EOD today, 6/29/23
