### ISSUE TITLE
How to update local cache?

### ISSUE THREAD

**Issue by willnode** [MicrosoftDocs/visualstudio-docs#933]
Does running the same arguments from existing local cache only update things that necessary? It shouldn't redownload everything, correct?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b2a7f87-7685-2618-9be0-f2286662342f
* Version Independent ID: 626a45d3-732a-6992-9f0c-bf06bc87fe1c
* Content: [Install on low bandwidth or unreliable network environments - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/install-vs-inconsistent-quality-network#)
* Content Source: [docs/install/install-vs-inconsistent-quality-network.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/install-vs-inconsistent-quality-network.md)
* Service: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by nymbols** [comment]
Yes, it doesn't re-download everything. You can just run "vs_enterprise.exe --layout c:\VS2017Layout" to update. It remembers previous and subsequent settings.

**Comment by TerryGLee** [comment]
@nymbols Thanks for your input! I concur. @willnode, I'll close this now.
