### ISSUE TITLE
Debug .NET Framework source "How To" page discusses "Enable .NET Framework Source Stepping" which is not in Visual Studio 2022

### ISSUE THREAD

**Issue by timgranata** [MicrosoftDocs/visualstudio-docs#9337]
This page talks about toggling a debugging setting called "Enable .NET Framework Source Stepping", but Visual Studio 2022 does not have this option present anymore:

![visual studio 2022 debugging settings](https://github.com/MicrosoftDocs/visualstudio-docs/assets/50630368/a567debf-f655-4316-a789-e3cb2d49e3cb)

It seems Visual Studio 2019 still has this option, so I assume somewhere between 2019 and 2022 this option has been removed.  I don't know what replaced it (I am assuming the "Enable Just My Code" setting inherited it).

This page should be updated appropriately.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e04e717-61a6-99eb-60cd-34263fa597b5
* Version Independent ID: 3ee15675-d5bd-f3c9-fb85-1b65b3d71897
* Content: [Debug .NET Framework source - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-debug-dotnet-framework-source?view=vs-2022)
* Content Source: [docs/debugger/how-to-debug-dotnet-framework-source.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/how-to-debug-dotnet-framework-source.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@timgranata Thanks for the feedback! I'm asking about this.

**Comment by Mikejo5000** [comment]
@timgranata I found this information in a dev community post:
https://developercommunity.visualstudio.com/t/Enable-NET-Framework-source-stepping/10372238?q=Enable+.NET+Framework+source+stepping&viewtype=all

post:
https://developercommunity.visualstudio.com/t/Enable-NET-Framework-source-stepping/10372238?q=Enable+.NET+Framework+source+stepping&viewtype=all
I will update the article.

**Comment by Mikejo5000** [comment]
Update will be live by noon 7/21, PST
