### ISSUE TITLE
Adding custom fonts

### ISSUE THREAD

**Issue by dustin2711** [MicrosoftDocs/visualstudio-docs#9338]
Site explains everything well except how to add custom fonts. This should not miss.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2913896-b0f2-5f3c-d733-09fe5c4e86b1
* Version Independent ID: c997c373-c946-0f02-d4c2-0904e6aab42e
* Content: [Change themes, fonts, text, and contrast for accessibility](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@dustin2711 -- Dustin, thank you for your feedback.  The available fonts are all the fonts installed on your system.  To add a custom font, first add it to your system, then select it in Visual Studio as described in this article.  

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
