### ISSUE TITLE
When its not a Visual Studio Extension, why does this show up?

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#934]
Souce control explorer, RDLC designer, etc. are part of visual studio, and aren't extensions like Markdown Editor, POSH tools, etc. 

Why does VS notify me about these things instead of just reporting telemetry to you (so you can hopefully fix it)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c50729d-6836-feee-b306-cfab96b36d17
* Version Independent ID: afec4f9e-ac95-d414-62d7-c6a654721f5b
* Content: [Find and use Visual Studio extensions - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions#extension-crashunresponsiveness-notifications)
* Content Source: [docs/ide/finding-and-using-visual-studio-extensions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/finding-and-using-visual-studio-extensions.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@PooyaZv can you comment on this issue about extension unresponsiveness?

**Comment by PooyaZv** [comment]
@StingyJack: We should not be showing notification for system extensions. Can you please report this through the feedback button if you run into it again? (More details on reporting feedback using the feedback tool: https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio-2017) Once you do, please reply to this with the DC link and I'll follow up with the product teams. Thank you.

**Comment by StingyJack** [comment]
There is little use logging anything on that site. At most, only about 20 percent of the issues I reported got a meaningful response, and the PEM running the show figured it was easier to suspend my accounts than to put some effort into resolving reported issues.

**Comment by PooyaZv** [comment]
If these are notifications regarding startup performance, this is by design. You can use the "Never show this again" button to stop seeing the notifications. However, if this is regarding unresponsiveness specifically, we should not be showing the notification and if you use feedback and include the link here, we can take a look (my team owns that feature).

**Comment by StingyJack** [comment]
The problem with those "Never show this again" links is that they just show something else to me a few days later. or the just [never](https://developercommunity.visualstudio.com/content/problem/36322/dependency-validation-messages-wont-stop-bothering.html),  [go](https://developercommunity.visualstudio.com/content/problem/102206/one-or-more-projects-needs-to-be-updated-to-perfor.html),  [away](https://developercommunity.visualstudio.com/content/problem/154615/the-package-at-path-to-replaced-nuget-package-fail.html). There are more than those three, but searching on that site is painful. One of the more recent reports related to this topic should have the feedback collection attached to it, but users cant see if they have attached something or not.

So I _really_ dislike the the gold bars in VS (and the TFS2015 "try the new build system), and what I really want is to turn them off permanently.

**Comment by PooyaZv** [comment]
@StingyJack: We are sorry for the inconvenience this has caused you. We do not use GitHub issues opened against docs.microsoft.com to track,/assess/resolve potential issues in Visual Studio performance notifications. Please use the developer community/feedback tool to report issues/provide suggestions. Thank you.

**Comment by StingyJack** [comment]
Not sure if you read and are trying to sidestep, or didn't read. 

Either way, this is one of those "could be docs or could be product" issues. Since you assert it's product, I'll leave this closed and wait for additional prepared pushoff statements from the Wangs until the RoiChen bot requests that I open a different request.

**Comment by PooyaZv** [comment]
@StingyJack just a clarification, different notifications (gold bars) are owned by different teams. The ones mentioned in this doc, are specifically crash notifications and unresponsiveness notifications, which our team owns. Other notifications like the ones you had the links to, are owned by a variety of teams. We currently do not have a feature to disable all gold bars. The reason I suggested DC feedback was that it is one of the channels we use for customer suggestions on new features. Thank you and have a good weekend :)
