### ISSUE TITLE
More property changes needed to build C++ project for Python

### ISSUE THREAD

**Issue by zooba** [MicrosoftDocs/visualstudio-docs#9351]
Step 7 in the "Create the core C Projects" section has a list of properties that need to be updated in a C++ project before building with Python.

As of the current version of VS/MSVC/some part of the tooling, there are two more options that need to be changed as well as the rest of these. Without changing these options, you cannot build your extension in Debug mode with release Python (i.e. `python.exe` not `python_d.exe`).

The options are:
* C/C++ -> General -> Debug Information Format = `Program Database (/Zi)`
* C/C++ -> Code Generation -> Basic Runtime Checks = `Default`

(Thanks @anna-dingler for figuring these out!)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022#create-the-core-c-projects)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by anna-dingler** [comment]
Was looking into this more, and we **do not** need the `C/C++ -> General -> Debug Information Format = Program Database (/Zi)` change

The only change required is **Basic Runtime Checks**

**Comment by cwebster-99** [comment]
@anna-dingler @zooba Thanks for the issue report! @WilliamAntonRohm  This change is reflected in the above PR and can now be closed.

**Comment by WilliamAntonRohm** [comment]
#please-close
