### ISSUE TITLE
this link doesn't get to the specified resource Visualization and Modeling SDK

### ISSUE THREAD

**Issue by ed7257** [MicrosoftDocs/visualstudio-docs#9352]
this link in the document doesn't take to the specified resource: Visualization and Modeling SDK

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb79e97f-6d8a-0f06-96db-db4fc1e135ae
* Version Independent ID: 097107da-2105-400d-3ad3-1f47c1422209
* Content: [Getting Started with Domain-Specific Languages - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/getting-started-with-domain-specific-languages?view=vs-2022)
* Content Source: [docs/modeling/getting-started-with-domain-specific-languages.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/getting-started-with-domain-specific-languages.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
@ed7257 Which link are you referring to? The DSL Tools Lab one? It looks like that lab was lost when the MSDN site was retired. However, a Microsoft engineer has posted a copy he found somewhere in his personal GitHub repo here: https://github.com/bricelam/DslToolsLab
