### ISSUE TITLE
Manage Connected Services not present

### ISSUE THREAD

**Issue by IGx89** [MicrosoftDocs/visualstudio-docs#9361]
Hello! At the top this page says `Get started by right-clicking on the Connected Services node in Solution Explorer and select Manage Connected Services.` That doesn't seem to be valid anymore in the latest VS 2022 (17.6.4) -- "Manage Connected Services" is not present in the right-click menu on the Connected Services node for me. The only way I've found to bring it up is by right-clicking the project itself, selecting Add, and then Connected Service.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: dc577df9-051f-8f28-d3d7-46a2668d6a46
* Version Independent ID: dc577df9-051f-8f28-d3d7-46a2668d6a46
* Content: [Connected services - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/azure/overview-connected-services?view=vs-2022#connect-your-app-to-grpc-openapi-and-wcf-endpoints)
* Content Source: [docs/azure/overview-connected-services.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/azure/overview-connected-services.md)
* Product: **visual-studio-windows**
* Technology: **vs-azure**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@IGx89 -- Matthew, thank you for your feedback and solution.

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
@IGx89
Thanks for pointing this out. I recently updated all these pages for recent changes in VS 2022 update releases, but you're right that  I missed that.
