### ISSUE TITLE
Some documentation improvement suggestions about `.natstepfilter` and `.natjmc` files

### ISSUE THREAD

**Issue by yeputons** [MicrosoftDocs/visualstudio-docs#9363]
Hello!

I suggest to add some information on the page that I had to find myself using trial and error. I'm happy to open pull request(s) into this repository with exact wording, suggest it in a comment, or open separate issues for these points.

1. Some extensions (namely, [JetBrains ReSharper C++](https://stackoverflow.com/a/76543880/767632)) may interfere with `.natstepfilter` files. Granted, any extension can interfere with anything, but maybe it's worth adding the following sentence in the very end of the " Customize C++ stepping behavior independent of Just My Code settings" section:
> Some third-party extensions may disable `.natstepfilter` functionality altogether.
2. I fill the difference between `.natstepfilter` and `.natjmc` can be highlighter better. The former will step over non-user function altogether even if some user code is executed in it. The latter will make the specified function "transparent": the debugger will step into the first line of user code inside the function. There is no such functionality in other debuggers that I know, so it seems useful to highlight. I propose to change the "C++ Just My Code" section as follows:
> During C++ debugging **non-user code is skipped by default**:
> Debug > Step Into (or F11) on non-user code **either** steps over the code ~~to the next line of user code~~ **or runs to the next line of user code, if such is called from non-user code**.
> Debug > Step Out (or Shift+F11) on non-user code runs to the next line of user code **strictly outside of the current stack frame**.
and the "Customize C++ stepping behavior independent of Just My Code settings" section as follows:
> In C++ projects, you can specify functions to step over by listing them as ~~non-user code~~ **no-step-into functions** in `*.natstepfilter` files.
> ...
>  NoStepInto - tells the debugger to step over the function**, even if it calls some `StepInto` functions or other user code**.
4. The ability to add `.natstepfilter` and `.natjms` files directly to the solution/project is not mentioned at all, while [it was added in Visual Studio 2022 version 17.6](https://developercommunity.visualstudio.com/t/Allow-natstepfilter-and-natjmc-to-be-i/561718#TPIN-N10364299).
5. The fact that syntax errors in `.natstepfilter` and `.natjmc` files is not reported in Debugger's "Output" window (unlike for `.natvis`) files also worth mentioning, I think.
6. Another important piece of information is that both `.natstepfilter` and `.natjmc` files are not hot-reloaded (unlike `.natvis`), they're reloaded somewhere in the beginning of the debug session, no need to restart Visual Studio or rebuild the solution. It seems that `.natstepfilter` settings are currently cached per a function in the solution (wheter to `NoStepInto` or not), and `.natjmc` settings allows for marking functions as "external code" during a debugging session, but I'm not sure if that's the intended behavior. 
7. The `NonUserCode`/`Function` element's `Name` attribute seem to accept wildcards with `*` and `?` (not regular expressions), that is not mentioned anywhere, but is important for supporting templated function.
8. The `StepFilter`/`Function`/`Name` element's value's example of `MyNS::MyClass.*` is slightly incorrect: not only it will mark all methods of `MyNS::MyClass`, but also all methods of `MyNS::MyClass2` and a function called `MyNS::MyClassFunction`. I suggest `MyNs::MyClass::.*` instead.
9. Neither of two above descriptions mention anything about templates, while suggesting `&lt;*&;gt`/`&lt.*` would be useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c93cd83-ee45-dbd4-e3b2-48c731e46419
* Version Independent ID: e8920cca-b8db-369a-e249-938b995b5f14
* Content: [Debug user code with Just My Code - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2019#BKMK_CPP_Customize_stepping_behavior)
* Content Source: [docs/debugger/just-my-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/just-my-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@yeputons -- Egor, thank you for your detailed feedback.  You are welcome to create a PR and add this information to the article.

Please see here for guidlines:
- https://learn.microsoft.com/en-us/contribute/

**Comment by WilliamAntonRohm** [comment]
@yeputons -- Egor, please let me know if you are still considering adding this information.  Your assistance is appreciated, and you will be listed as a Contributor for this article.

**Comment by yeputons** [comment]
@WilliamAntonRohm I'm currently figuring out CLA with my employer, I'm not sure how long it will take. In any case, feel free to proceed without me if you've got time.

**Comment by WilliamAntonRohm** [comment]
@yeputons -- Egor, thank you for your follow-up.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
Updating this article

**Comment by Mikejo5000** [comment]
Article should be updated by noon PST on 8/15/23.

**Comment by Mikejo5000** [comment]
@yeputons The update is live now. Thanks! If you want to review this, let me know the feedback. Also, is this item in the **Additional information...** section clear and unambiguous:

- For template functions, the use of `&lt;*&;gt` or `&lt.*` in the name may be helpful.

**Comment by yeputons** [comment]
@Mikejo5000 Thanks a lot! Some comments:

> Step Into (or F11) on non-user code steps over the code or runs to the next line of user code, if Step Into is called from non-user code.

I'm not sure if the part after comma is actually needed? If I'm in user code and I press F11, debugger runs to the next line of user code, be it in the same stack frame or (immediately) inside the function it steps into. If I'm in non-user code, F11 seems to disable `.natjmc` until I'm back in user code, but I'm not sure here.

>  For template functions, the use of &lt;*&;gt or &lt.* in the name may be helpful.

If I have a `template<typename A, typename B> void foo(A, B)` called like `foo(10, 'b')`, `.natjmc` considers its name to be `foo<int,char>`, not simply `foo`. If this function is external code, its `Name` should consider that, e.g. by allowing all names like `foo<*>` (that will allow `foo`, but not `foo1`, unlike `foo*`). Additionally, `<` and `>` are not valid characters inside XML attribute value, so one has to use `&lt;` and `&gt;` instead.
