### ISSUE TITLE
Missing setting for ESLint path

### ISSUE THREAD

**Issue by Axemagus** [MicrosoftDocs/visualstudio-docs#9367]
The document states, "You can also use the ESLint Path setting in Tools > Options > Text Editor > JavaScript/TypeScript > Linting to specify a directory from which to load ESLint."

This setting does not exist in 17.6.4 or earlier.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff6ceff-02c9-e161-0971-bd0a60e9470a
* Version Independent ID: 6ff6ceff-02c9-e161-0971-bd0a60e9470a
* Content: [Linting JavaScript in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/linting-javascript?view=vs-2022#installing-eslint-dependencies)
* Content Source: [docs/javascript/linting-javascript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/linting-javascript.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Axemagus I see the setting in 17.7 Preview 2. I'll update the doc. Thanks!
