### ISSUE TITLE
Include snippets of PropertyGroup (or other) Xml tags

### ISSUE THREAD

**Issue by mwpowellhtx** [MicrosoftDocs/visualstudio-docs#937]
In other Xml dialects, it is possible to include snippets of common, boilerplate code from another file. Given the migration of bits from areas such as AssemblyInfo, where this was possible before, it would be great if we could do that in the CSPROJ format as well. Or, if it is already, I'm not aware how to do it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa26a042-4407-51d2-7df9-f045aaef2a3d
* Version Independent ID: 57f71dc5-34b2-6431-c4a4-c308e48adf0b
* Content: [PropertyGroup Element (MSBuild) - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/propertygroup-element-msbuild)
* Content Source: [docs/msbuild/propertygroup-element-msbuild.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/propertygroup-element-msbuild.md)
* Service: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
@rainersigwald Do you know if it's possible to include snippets of boilerplate code in the PropertyGroup element in a .csproj file?

**Comment by rainersigwald** [comment]
I'm not sure I understand the question here. Can you give an example of what you wish worked, or describe it in a bit more detail?

**Comment by Mikejo5000** [comment]
@mwpowellhtx Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
