### ISSUE TITLE
Azure Images are giving an error saying images not available for VS 2022

### ISSUE THREAD

**Issue by the-jake-z** [MicrosoftDocs/visualstudio-docs#9372]
Azure Images are not available - Is the documentation missing data centers where this image is available?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 875c43bc-a462-823a-28b9-038d8e297c2a
* Version Independent ID: a7ed6cea-1e8a-000f-5447-9bd34c49695a
* Content: [Using Visual Studio on an Azure Virtual Machine](https://learn.microsoft.com/en-us/visualstudio/install/using-visual-studio-vm?view=vs-2022)
* Content Source: [docs/install/using-visual-studio-vm.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/using-visual-studio-vm.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@jzarob -- Jake, thank you for your question.  Please provide additional context for this issue -- can you attach a screenshot?

**Comment by the-jake-z** [comment]
I would suggest trying to create a Visual Studio VM using the Visual Studio image in Azure to recreate the issue. Many of the reviews for the image contain the text from the error I experienced.  Attached image from marketplace for reference.

![BE9131D9-3703-4161-BDE8-BFF0480884FD](https://github.com/MicrosoftDocs/visualstudio-docs/assets/2938827/de7f14a4-dfa9-4167-9236-b53a37f4cfd7)

**Comment by WilliamAntonRohm** [comment]
@the-jake-z -- Jake, thank you for your followup.  

@anandmeg -- Megha, please look into this potential documentation issue.

**Comment by rub8n** [comment]
Thanks @the-jake-z for the feedback! We are currently investigating the issue.

In the meantime, can you try these VS2022 images instead? 
https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoftvisualstudio.visualstudioplustools?exp=ubp8&tab=Overview

**Comment by anandmeg** [comment]
Thanks for your feedback, @the-jake-z!
We've updated the doc with links to:

- [Visual Studio 2022 (Microsoft Dev Box compatible)](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoftvisualstudio.visualstudioplustools?exp=ubp8&tab=Overview)
- [Visual Studio 2019 (Microsoft Dev Box compatible)](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoftvisualstudio.visualstudio2019plustools?exp=ubp8&tab=Overview)

The changes should be live later today.

As mentioned above, our team was unable to repro the issue. Closing this issue now. 
Please respond to this with additional feedback or open a new issue if you have any other feedback. Thanks!
