### ISSUE TITLE
Productive Microsoft 365 apps for enterprise in Visual Studio subscriptions - Eligibility/12-month trial/existing tenant

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/visualstudio-docs#9376]
In the "Eligibility" section for "Visual Studio Enterprise (Standard)" under "Benefit" it states "12-month trial" and "Renewable?" is "No". 

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/12844147/6aef9cb8-b735-4e83-b463-3ec8f6853098)

Does this imply the benefit is only for the first year of the subscription? The use of "trial" also contradicts other statements about this being for "productive use" without qualification, such as on [this pricing page](https://visualstudio.microsoft.com/vs/pricing-details/).

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/12844147/152b7856-23ed-40d6-9467-79bf048bde09)

When activating it is also listed a trial: 

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/12844147/8a9ae332-c251-4994-85a1-92265975c329)

Also note the instructions are for creating a new tenant, but most users will have a tenant for their organization. The above message indicates my administrators need to take some action to allow this, but doesn't say what nor does this document.

So could the follwing be clarified/added:
1. if this is a rolling benefit or one time per subscription? If it is one time, the various other pricing pages need to be updated too! (and "one time" clarified to be eg. per organization, per named user, etc)
2. how administrators can allow adding of this benefit to their tenants (and which administrators these are - M365, VS Subscriptions admins, etc)

Thanks in advance! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 737f8499-4067-8033-6e5e-edc9eba38fcb
* Version Independent ID: cf03c560-a70c-256e-fc22-f39c51b38b7e
* Content: [Microsoft 365 apps for enterprise in Visual Studio subscriptions](https://learn.microsoft.com/en-gb/visualstudio/subscriptions/microsoft-365-apps-for-enterprise)
* Content Source: [subscriptions/microsoft-365-apps-for-enterprise.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/microsoft-365-apps-for-enterprise.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@fowl2 -- James, thank you for your detailed feedback.

@evanwindom -- Evan, please look into this issue.

**Comment by evanwindom** [comment]
@fowl2 Hi James.  Thanks for reaching out.  The benefit is provided by the M365 team, who decide that the terms of the offer are.  The subscription is indeed a trial and is designed to be used by a single user on their own tenant.  The term of the trial is 12 months so it's not available for the entire length of some of the subscriptions purchased through Volume Licensing.  If the subscription is renewed, the subscription will renew but a new tenant will be required.  The "production use" refers to how the product is licensed.  Most of the tools and services in the Visual Studio subscriptions are limited to dev/test usage, but the M365 apps for Enterprise allows the subscriber to use the apps for non-dev related work.  That doesn't change its status as a trial offer.  I know it's confusing.  I'll look for ways to bring some clarity.

**Comment by evanwindom** [comment]
I've posted a couple of updates to the article.  
#please-close

**Comment by fowl2** [comment]
@evanwindom I can see the [changes](https://github.com/MicrosoftDocs/visualstudio-docs/commit/0a887bbe2c41b4ebb172f2b9ea0d5db46d06b3e4), thanks!

1. There are various other pages, such as the [pricing page](https://visualstudio.microsoft.com/vs/pricing-details/) I linked in my original issue,
2. How do we add this to our existing tenants? Are we expected to create a new tenant each year?

**Comment by evanwindom** [comment]
@fowl2 Hi James, 
There's a project underway right now to refresh several pages on the Visual Studio site, including the pricing page, so I'll provide feedback into that process.  (I don't own those pages...)

As far as the tenant issue is concerned -- yes, a new tenant is required each time the offer is activated.  I know that's really not optimal, but that's the way the trials are currently structured.  Incorporation into subscriptions is not a typical use for those trial offers, so the process isn't ideal.
