### ISSUE TITLE
Can't reset toolbars after you removed the "Tools" menu

### ISSUE THREAD

**Issue by PieterjanDeClippel** [MicrosoftDocs/visualstudio-docs#9378]
Tools > Customize > Commands > Remove the Tools menu

Now you're unable to restore the toolbar, since you cannot search for it either.

(I removed all items in order to re-add them later, just because there were some actions missing from the menu)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 49fe9dd7-3720-5ea9-6c5a-7bde27cb993e
* Version Independent ID: c7c693df-ef68-dc9f-268e-ffac03132a29
* Content: [Customize menus and toolbars - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-customize-menus-and-toolbars-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-customize-menus-and-toolbars-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-customize-menus-and-toolbars-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@PieterjanDeClippel -- Pieterjan, I've confirmed your findings.  I had thought one could restore the Tools menu from the View menu but that does not seem to be the case.

I suggest leaving at least one Tool menu item active, then add the items you prefer, then delete the placeholder item.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
