### ISSUE TITLE
WriteCodeFragment: Document _TypeName metadata

### ISSUE THREAD

**Issue by rainersigwald** [MicrosoftDocs/visualstudio-docs#9379]
https://github.com/dotnet/msbuild/pull/6285 introduced new metadata respected by the `WriteCodeFragment` task to specify the type of parameters. It should be documented here.

We probably need an example--the ones provided in that PR by @reduckted are excellent.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9b571575-db30-7502-9787-a65d97200d10
* Version Independent ID: e6d55b9a-17f2-cb5e-1949-c800b394228e
* Content: [WriteCodeFragment Task - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/writecodefragment-task?view=vs-2022)
* Content Source: [docs/msbuild/writecodefragment-task.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/writecodefragment-task.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@rainersigwald -- Rainer, thank you for that information.

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
This was fixed.
