### ISSUE TITLE
Can't move default workspace root to Dev Drive

### ISSUE THREAD

**Issue by lgp1985** [MicrosoftDocs/visualstudio-docs#9387]
Please add a section for `Options` > `Live Unit Testing` > `General` > `Default workspace root` __can't__ be defined currently to a [Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/). As it'll fail with _InvalidArg for 'Windows Projected File System'_.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d963b3f7-abc8-a9e7-9ac7-2a5c7ad53c28
* Version Independent ID: 2866e780-84b2-a833-24fb-8a4354a9c0f4
* Content: [Live Unit Testing FAQ - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq?view=vs-2022)
* Content Source: [docs/test/live-unit-testing-faq.yml](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/live-unit-testing-faq.yml)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@lgp1985 I'm asking about this. Thanks for the feedback!

**Comment by lgp1985** [comment]
There's one requirement to have [Live Unit Testing](https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2022) workspace root moved to a [Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/), you'll need to enable `Windows Projected File System` via the command below:
```Shell
fsutil devdrv setfiltersallowed PrjFlt
```

**Comment by Mikejo5000** [comment]
Update will be live by EOD today, 7/25, PST.
