### ISSUE TITLE
CA1305 mention Invariant()

### ISSUE THREAD

**Issue by LukeOwlclaw** [MicrosoftDocs/visualstudio-docs#939]
Please consider adding a hint to the documentation about CA1305 that method [Invariant()](https://msdn.microsoft.com/en-us/library/system.formattablestring.invariant(v=vs.110).aspx) can be used for fixing. A quick action would be awesome as well!

Had to look [here](https://stackoverflow.com/questions/29333390/specifying-locale-for-string-interpolation-in-c6-roslyn-ctp6#answer-29338846) to find this solution.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f418cad-87d9-537a-497c-991d209cb178
* Version Independent ID: 10bbdf2e-c425-4f8d-bfec-a5b821a41698
* Content: [CA1305: Specify IFormatProvider - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1305-specify-iformatprovider)
* Content Source: [docs/code-quality/ca1305-specify-iformatprovider.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1305-specify-iformatprovider.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@LukeOwlclaw Thanks for this suggestion. I will add a mention of Invariant()!
