### ISSUE TITLE
as-casts in overridable Equals(object) are dangerous and should not be recommended in the doc

### ISSUE THREAD

**Issue by m-ringler** [MicrosoftDocs/visualstudio-docs#9397]
The code

~~~
public override bool Equals(object obj)
    {
        return Equals(obj as ImaginaryNumber);
    }
~~~

is common but dangerous when Equals(object) can be overridden by a derived class.

This will easily lead to a violation of symmetry when a subclass of ImaginaryNumber overrides Equals(object), and with certainty if that subclass uses the same construct.

Let's say we have 
~~~cs
public class GreenImaginaryNumber : ImaginaryNumber
{
public override bool Equals(object obj)
    {
        return this.Equals(obj as GreenImaginaryNumber);
    }

   public bool Equals(GreenImaginaryNumber other)
  {
        if (other == null) return false;
        ...
  }
}
~~~
Then, with
~~~cs
var a = new ImaginaryNumber();
var b = new GreenImaginaryNumber();
~~~

we'll have a.Equals(b) == true, but b.Equals(a) == false.

The example code should therefore either seal Equals(object) or use this.GetType() == other.GetType() rather than `as ImaginaryNumber`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cb48054-70fa-c5eb-748e-4db24ef64fd4
* Version Independent ID: 9ca41665-2e31-87da-4ba9-a8c60150db51
* Content: [Generate C# Equals and GetHashCode Method Overrides - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2022)
* Content Source: [docs/ide/reference/generate-equals-gethashcode-methods.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/generate-equals-gethashcode-methods.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@m-ringler -- thank you for your interesting feedback.

@TerryGLee -- please look into this issue.

**Comment by j-martens** [comment]
#reassign:@mikejo5000

**Comment by m-ringler** [comment]
please review
