### ISSUE TITLE
MSBuild 17.8 static property functions for System.OperatingSystem

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#9405]
A future version of MSBuild will support static property functions for System.OperatingSystem.  That feature should be documented here, when it is known which version of MSBuild will ship with this change.  The feature was requested in <https://github.com/dotnet/msbuild/issues/5982> and implemented in <https://github.com/dotnet/msbuild/pull/8935>.

These property functions will return information about the operating system on which MSBuild is running.  For example, if your project targets Linux and you build it on macOS, the property functions will return information about macOS.

In MSBuild running on .NET (e.g. `dotnet build`), all static methods of the [System.OperatingSystem](https://learn.microsoft.com/dotnet/api/system.operatingsystem?view=net-7.0) class will be callable as static property functions.

In MSBuild running on .NET Framework (e.g. `MSBuild.exe`), only the following methods of System.OperatingSystem will be callable as static property functions.  MSBuild will implement them internally, because System.OperatingSystem does not define them on .NET Framework.  Other methods such as System.OperatingSystem::IsTvOS will not be callable, but developers won't need them because .NET SDK cannot be installed on those operating systems.

* System.OperatingSystem::IsOSPlatform
* System.OperatingSystem::IsOSPlatformVersionAtLeast
* System.OperatingSystem::IsLinux
* System.OperatingSystem::IsFreeBSD
* System.OperatingSystem::IsFreeBSDVersionAtLeast
* System.OperatingSystem::IsMacOS
* System.OperatingSystem::IsMacOSVersionAtLeast
* System.OperatingSystem::IsWindows
* System.OperatingSystem::IsWindowsVersionAtLeast

The Microsoft.Build.Framework.OperatingSystem type is an implementation detail and should not be documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82a1a083-bea0-e53e-dc9e-78f201ac1314
* Version Independent ID: 904dae68-65cb-ec55-2fb3-1075ceaf6f1c
* Content: [Property Functions - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022)
* Content Source: [docs/msbuild/property-functions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/property-functions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- Kalle, thank you for your very detailed feedback.

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
Docs added, under review internally.
