### ISSUE TITLE
VS Cloud subscriptions

### ISSUE THREAD

**Issue by si-chan** [MicrosoftDocs/visualstudio-docs#9406]
Although it is not ideal to not have a specific RBAC role for VS subscription admin purchased via Azure cloud subscriptions, it is also not ideal that the documentation suggests using User Access Administrator role.

This is because UAA is the second-highest administrator level, after Owner.
Someone with UAA can grant themselves or anyone else full access to the subscription.

I would recommend changing the documentation to reflect the fact that Contributor is the best choice in this situation (although as mentioned, it's still not ideal - there should be a specific RBAC role with limited rights to manage VisualStudio resource types only - but that's a product feature request, not a documentation issue).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4ff3400-d8b9-eeaa-c785-3859c0b8e40e
* Version Independent ID: e01d9d35-733c-d892-e1e8-19e5f2553ebf
* Content: [Setting up admins for monthly Visual Studio subscriptions](https://learn.microsoft.com/en-us/visualstudio/subscriptions/cloud-admin)
* Content Source: [subscriptions/cloud-admin.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/cloud-admin.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@si-chan Thank you for reaching out.  I've forwarded this to a few folks with deeper knowledge of the subject.  I'll let you know what I find out.
