### ISSUE TITLE
This page is so stupid

### ISSUE THREAD

**Issue by WeiStreamingRtc** [MicrosoftDocs/visualstudio-docs#9412]
[Enter feedback here]
How to "use the dynamic UCRT library", why not give instruction here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 579461d1-3f48-4419-c2a4-508626b9233c
* Version Independent ID: 579461d1-3f48-4419-c2a4-508626b9233c
* Content: [MSBuild error MSB8024 - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/errors/msb8024?view=vs-2022)
* Content Source: [docs/msbuild/errors/msb8024.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb8024.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@WeiStreamingRtc -- please see this article:
- https://learn.microsoft.com/en-us/cpp/porting/upgrade-your-code-to-the-universal-crt

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
