### ISSUE TITLE
ClickOnce File Association: explain how to access the filename

### ISSUE THREAD

**Issue by nzain** [MicrosoftDocs/visualstudio-docs#9420]
Recently clickonce file association has started to work again, it was broken for years (!) since we moved to .net "core" from .Net Framework. However, the latest documentation does not explain how to actually use it. If the user double-clicked a file, he expects the responsible app to _open the file_. To make this happen, the app has to detect which file was clicked.

It looks like the `ClickOnce_ActivationData_0` enviroment variable is populated with that double-clicked filename. However, I'm guessing here... any documentation on this would be valuable! Thanks in advance :)

Original issue: https://github.com/dotnet/deployment-tools/issues/113

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8c2575a9-5973-2a77-ecf6-2142eefcd554
* Version Independent ID: 63223f10-3ed0-238c-545f-5dd810b304a7
* Content: [Create file associations (ClickOnce app) - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/deployment/how-to-create-file-associations-for-a-clickonce-application?view=vs-2022)
* Content Source: [docs/deployment/how-to-create-file-associations-for-a-clickonce-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/how-to-create-file-associations-for-a-clickonce-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-deployment**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by nzain** [comment]
Please read both articles. They do not explain what I'm referring to.

**Comment by Mikejo5000** [comment]
@nzain Hmm. OK, I read some of the linked issues to try to get clarity on this.

I see this page:
https://github.com/dotnet/deployment-tools/issues/254

which has this information:

Usage scenario
Developer can read these environment variables to discover ActivationData content, using something like the following:
`string value = Environment.GetEnvironmentVariable("ClickOnce_ActivationData_0");`

Previously, for .NET FX apps, this would have been achieved using the following code:
`string value = AppDomain.CurrentDomain?.SetupInformation?.ActivationArguments?.ActivationData?[0];`

That seems to be the information missing from the docs. Is that correct?

**Comment by nzain** [comment]
Ah, yes, that sounds good. If you add the "count" variable explanation, it is complete! It is very complicated, but that's what I expected.

**Comment by Mikejo5000** [comment]
New article should be live by EOD 8/14/23, PST.
https://learn.microsoft.com/en-us/visualstudio/deployment/access-clickonce-activation-data-dotnet
