### ISSUE TITLE
there is no code map in visual studio professional 2022 17.5.1

### ISSUE THREAD

**Issue by shengyu-kmust** [MicrosoftDocs/visualstudio-docs#9427]
[Enter feedback here]
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/9101211/f1437c6d-ab9a-4d6f-9459-73480293206f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ae31d3c-d703-6431-8f01-e1d5c579846c
* Version Independent ID: 5d6a50bb-d976-2473-fa81-10f6159d562f
* Content: [Install architecture code tools - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/install-architecture-tools?view=vs-2022)
* Content Source: [docs/modeling/install-architecture-tools.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/install-architecture-tools.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by mgoertz-msft** [comment]
That right, there isn't. You need Visual Studio Enterprise for that.

> To create a code map in Visual Studio Enterprise...
