### ISSUE TITLE
uninstall error

### ISSUE THREAD

**Issue by apple3000** [MicrosoftDocs/visualstudio-docs#9438]
i installed vs2022 pro with layout.
but i can not uninstall it.
At windows controllpannel, to remove product , clicked vspro 2022. but can not fined installed product.
So,, i just delete folder "c:\program files\microsoft visualstudio\2022\professional".
why installer can not find installed product?
help me.

**Comment by WilliamAntonRohm** [comment]
@apple3000 -- please see my reply in related issue #9436.
