### ISSUE TITLE
Live Unit Test on Dev Drive

### ISSUE THREAD

**Issue by lgp1985** [MicrosoftDocs/visualstudio-docs#9446]
Please add the requirement to have [Live Unit Testing](https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2022) workspace root moved to a [Dev Drive](https://learn.microsoft.com/en-us/windows/dev-drive/), you'll need to enable `Windows Projected File System` via the command below:
```Shell
fsutil devdrv setfiltersallowed PrjFlt
```

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3113c2af-d97e-7b35-17ce-c675c3dff889
* Version Independent ID: b716c4af-d92b-cb3b-8af0-1b3ada479ac0
* Content: [Live Unit Testing - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/live-unit-testing?view=vs-2022)
* Content Source: [docs/test/live-unit-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/live-unit-testing.md)
* Product: **visual-studio-windows**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
Related to MicrosoftDocs/windows-dev-docs/issues/4535

**Comment by Mikejo5000** [comment]
@lgp1985 Thanks for the information! I'm asking about this.

**Comment by Mikejo5000** [comment]
Update will be live by EOD today, 7/25, PST.
