### ISSUE TITLE
Application popup: Visual Studio Just-In-Time Debugger

### ISSUE THREAD

**Issue by kian25** [MicrosoftDocs/visualstudio-docs#9449]
Application popup: Visual Studio Just-In-Time Debugger : An unhandled win32 exception occurred in [5108] soffice.bin. Just-In-Time debugging this exception failed with the following error: No installed debugger has Just-In-Time debugging enabled. In Visual Studio, Just-In-Time debugging can be enabled from Tools/Options/Debugging/Just-In-Time.

Just got this error and it caused my LibreOffice app to crash destroying all its saved files, is this something malicious, anyone have a clue why this happened?

**Comment by WilliamAntonRohm** [comment]
@kian25 -- thank you for this report.  It is outside the scope of documentation.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
