### ISSUE TITLE
Require REVOLUTION by MS VS Team to provide last endly a reliable Test Platform

### ISSUE THREAD

**Issue by TheDuQe** [MicrosoftDocs/visualstudio-docs#9455]
Ok. For the 20th time in four years, tests are not running in my solution.... again.

Why is the Test feature in Visual Studio so unreliable, so bad, so buggy ? I've started programming in .NET in 2001 and 
Test feature in Visual Studio was unreliable
22 years after, Test feature in Visual Studio is unreliable

No code change by my side, i could run them for two weeks ago. One Visual Studio upgrade after, they stopped working.
I do not need any support from your side : i just expect a REVOLUTION by MS VS Team to provide last endly a reliable Test Platform, after 20 years of MISFIRE !

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3681419-a041-da72-a134-37401922a536
* Version Independent ID: 57b6194d-cb07-0e89-8f38-544bf4ce9816
* Content: [Run unit tests with Test Explorer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/run-unit-tests-with-test-explorer?view=vs-2022)
* Content Source: [docs/test/run-unit-tests-with-test-explorer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/run-unit-tests-with-test-explorer.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@TheDuQe -- David, thank you for your considered feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

**Comment by TheDuQe** [comment]
Sorry, William to waste your time.

**Comment by WilliamAntonRohm** [comment]
@TheDuQe -- David, thank you for your followup.  It's no problem at all!
