### ISSUE TITLE
Feedback on VS 2022 Preview 

### ISSUE THREAD

**Issue by AGoh2019** [MicrosoftDocs/visualstudio-docs#9461]
[Enter feedback here]
I am wondering whether the enhanced Python support for VS Preview includes developing desktop and cloud apps using Python. I would say the Python environment is robust, but I am also specifically looking for Python + Windows Forms or UWP. 

As for machine learning using Python on VS.  Wonder if just these four Python libraries - Pandas, NumPy, Scikit learn and Matplotlib are sufficient for AI applications.  Does Python on VS support other open source libraries.

I would also like Microsoft Research (since it has all the brainy PhDs) to fix the 4 Rust language extensions. It installs but it doesn't allow me to do anything with Rust code.  What about adding Rust WebAssembly, desktop and cloud extensions to it as well.  These are just my thoughts for the future.

Thanks and Regards,

Andrew  Goh
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3330f57-6530-be0c-ce7d-a2ffb37891c9
* Version Independent ID: 38575887-8943-74fa-22b9-d4e53fddb496
* Content: [Choose a Python environment - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/selecting-a-python-environment-for-a-project?view=vs-2022)
* Content Source: [docs/python/selecting-a-python-environment-for-a-project.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/selecting-a-python-environment-for-a-project.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by WilliamAntonRohm** [comment]
@AGoh2019 -- Andrew, thank you for your well-considered feedback.  This seems more product-related than documentation-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @cwebster-99 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
