### ISSUE TITLE
Please add page for Debug apps in a Remote Docker Host container

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/visualstudio-docs#9476]
ITNOA

Visual Studio is a first class product for Development for Microsoft Ecosystem, So I think Microsoft must add all enterprise features from Visual Studio Code to Visual Studio Enterprise Edition. With this assumption, I think Visual Studio must have feature for developing and debugging seamlessly on remote docker host. as you can see in https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host for Visual Studio Code

**So Please add page for Debug apps in a Remote Docker Host container**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b6e74c3-2796-a2c3-ce35-18767cecb702
* Version Independent ID: 60d27ba1-d713-23dc-93ec-b72feda17016
* Content: [Debug apps in a local Docker container - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/containers/edit-and-refresh?view=vs-2022)
* Content Source: [docs/containers/edit-and-refresh.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/edit-and-refresh.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by soroshsabz** [comment]
related to https://github.com/MicrosoftDocs/visualstudio-docs/issues/9477

**Comment by WilliamAntonRohm** [comment]
@soroshsabz -- thank you for your feedback and suggestion.

@ghogen -- please look into this potential documentation issue.

**Comment by ghogen** [comment]
@soroshsabz 
Are you suggesting a product feature? If so, it should be added at the Developer Community site. 
If you're suggesting a doc page, then of course we would need there to already be support in the product for the scenario and/or steps to get this to work with Visual Studio.  Have you actually done this, or do you just think it might be possible?

**Comment by soroshsabz** [comment]
I do not know Visual Studio support this or not, but in worst case (Visual Studio does not support remote Docker Host), I think for important features and frequently development task in modern environment, it is good to add article about this subject and add some workaround for this requirement, to help developer.

**Comment by ghogen** [comment]
Checked with the engineering team - this is not a supported scenario. If you think this should be implemented, please enter a feature request at the Dev Community site. https://developercommunity.visualstudio.com/home

**Comment by soroshsabz** [comment]
@ghogen I suggest add this note (Visual Studio does not support this feature) in some where in documentaiton, to reduce confusion for some developers like me

thanks

**Comment by soroshsabz** [comment]
I add ticket for this too, and I hope all developers vote up this

https://developercommunity.visualstudio.com/t/Debug-apps-in-a-Remote-Docker-Host-conta/10466341

**Comment by ghogen** [comment]
Adding a note to one of our pages would be reasonable.

**Comment by ghogen** [comment]
Watch for the note in https://learn.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2022 - scheduled to go live later today.

**Comment by soroshsabz** [comment]
@ghogen If I understand correctly, this feature done in https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#cross-platform-enchot-reload-debugging-support

so I think https://learn.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2022 must be updated for this changes.

Am I correct?

thanks

---

_We have added support for Edit and Continue for F5 (with debugger) and Ctrl-F5 (no debugger) scenarios when diagnosing and debugging apps hosted on Linux containers or in Windows Subsystem for Linux (WSL). Please note the F5 debugging scenario relies on .NET 8 RC1 and above._
