### ISSUE TITLE
How to specify DOCKER_HOST on dcproj?

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/visualstudio-docs#9477]
ITNOA

As you can see in [2. Using DOCKER_HOST environment variable to set up the target engine](https://www.docker.com/blog/how-to-deploy-on-remote-docker-hosts-with-docker-compose) in manual way we can use `DOCKER_HOST` to run docker in remote host, But I do not know how to set this variable in Visual Studio `dcproj` for Remote Development and remote Debugging and Remote Testing?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2e8ab223-566b-c9bc-ce39-22e23531415a
* Version Independent ID: f58fe488-72a0-98aa-ff60-f1f7585ea107
* Content: [Docker Compose build settings - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2022&source=recommendations)
* Content Source: [docs/containers/docker-compose-properties.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/docker-compose-properties.md)
* Product: **visual-studio-windows**
* Technology: **vs-container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@soroshsabz 
The article mentions DOCKER_HOST but presents it as one of several options, with the preferred option being the use of contexts to specify the docker engine to use. 

My guess is that this is not supported, but it might be educational to attempt to get such a scenario working to see where the blocking points are.  Maybe someone could write an extension that handles the scenario if it doesn't work out of the box.

**Comment by soroshsabz** [comment]
I could not find this option in https://learn.microsoft.com/en-us/visualstudio/containers/docker-compose-properties, where is this option mention?

I do not know, that Visual Studio support this or not, but I think if Visual Studio support this, docs must be speak about that, and if Visual Studio does not support this, I think it is good to add `note` in docs to explicitly says not supporting.

I think in important features (such as DOCKER_HOST) product documents have to explicitly explain supporting or not supporting.

**Comment by ghogen** [comment]
Checked with the engineering team - this is not a supported scenario. If you think this should be implemented, please enter a feature request at the Dev Community site. https://developercommunity.visualstudio.com/home

**Comment by soroshsabz** [comment]
I add this, I hope all of developers vote up this

https://developercommunity.visualstudio.com/t/Support-DOCKER_HOST-on-dcproj/10466337
