### ISSUE TITLE
Typo on page

### ISSUE THREAD

**Issue by jgyngell** [MicrosoftDocs/visualstudio-docs#9486]
There is a sentence on the page "We don't make all of a customer's annual cloud subscriptions coterminothere's common with Microsoft volume licensing agreement purchasing." that has a typo

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cf290c37-d7fa-9d10-b8ef-865647e58a70
* Version Independent ID: 1334b162-8560-5e0a-c874-9439b697dd96
* Content: [Billing FAQ for Visual Studio Visual cloud subscriptions](https://learn.microsoft.com/en-us/visualstudio/subscriptions/vscloud-billing-faq)
* Content Source: [subscriptions/vscloud-billing-faq.yml](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vscloud-billing-faq.yml)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@jgyngell - Thanks for bringing this to my attention.  I just hate it when aboauggaerk happens in our content.  :)  I have submitted a PR to fix the issue, and the updated content should be visible by tomorrow.  Thanks again!
