### ISSUE TITLE
Vue and ASP.NET Core (Preview) typescript template issues

### ISSUE THREAD

**Issue by DaleMckeown** [MicrosoftDocs/visualstudio-docs#9488]
I have a number of issues with this template:

1. When running the project, it opens the Vue frontend in Edge, while the webapi opens in Chrome. My debug settings are configured to use Chrome, I'd expect both projects to open Chrome windows. I cannot find any way of changing which browser the Vue app opens in.
2. The Vue frontend gives a privacy error, with the dev certificate not being trusted. This is despite all VS popups about certificates being accepted. The swagger endpoint runs fine with no certificate issues.
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/1249673/646753d4-3e24-4c63-897e-b61e40ca56ee)
3. When stopping debugging, the two console windows remain open and do not close down automatically. We currently have to manually close each console window.
4. Vue-CLI is now in maintenence mode, it should probably be replace with Vite.

**Comment by WilliamAntonRohm** [comment]
@DaleMckeown -- Dale, thank you for your detailed feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

**Comment by DaleMckeown** [comment]
@WilliamAntonRohm Thanks - have reported via a community post.
