### ISSUE TITLE
Dead link https://datacamp.groovehq.com/help_center

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#949]
Found in subscriptions//vs-datacamp.md

**Comment by gewarren** [comment]
@nschonni Thanks for letting us know about all of these broken links. @evanwindom can you take a look at this issue and the others like it?

**Comment by TerryGLee** [comment]
@prrana FYI on this.

**Comment by evanwindom** [comment]
This is fixed.
