### ISSUE TITLE
Please add sample project for remote testing with docker

### ISSUE THREAD

**Issue by soroshsabz** [MicrosoftDocs/visualstudio-docs#9491]
ITNOA

I do not understand what to doing with this doc, please add sample project for this and add link in doc

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 90ec9455-ef64-8854-94bc-9be28887a6a4
* Version Independent ID: 9adeea5e-7ba1-065f-5de0-aae9147f9c85
* Content: [Remote Testing in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022)
* Content Source: [docs/test/remote-testing.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/test/remote-testing.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by soroshsabz** [comment]
I think https://stackoverflow.com/q/76617282/1539100 example is good

**Comment by soroshsabz** [comment]
I like to added

**Comment by Mikejo5000** [comment]
Adding the example

**Comment by Mikejo5000** [comment]
@soroshsabz Update will be live by 12:00 noon PST. Please take a look and let me know if you have any feedback.
