### ISSUE TITLE
Page keeps redirect to the VS 2019 version as the "latest" version

### ISSUE THREAD

**Issue by danroth27** [MicrosoftDocs/visualstudio-docs#9496]
This page seems to always redirect to the 2019 version as the "latest" version even though VS 2022 is actually the newest VS version.

Also, it's a bit strange that in the Quickstarts node there are two Vue.js quickstarts that have almost identical names.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 59adf9c7-5894-84ba-32ee-df842aa4658d
* Version Independent ID: 50683e7c-4b31-1773-f20e-00732a0ffbcc
* Content: [Quickstart: Create your first Vue.js app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/quickstart-vuejs-with-nodejs?view=vs-2019&viewFallbackFrom=vs-2022)
* Content Source: [docs/javascript/quickstart-vuejs-with-nodejs.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/quickstart-vuejs-with-nodejs.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@danroth Thanks for pointing this out. When you're on a VS 2019-only page, you can't get to a different VS 2022 article by switching the Version Selector (top left selector); you just get stuck on the VS 2019 page. The versioning currently works better when the versioned content is contained in a single article/URL. Besides this, there's some buggy behavior due, I believe, to caching of the TOC (left nav pane). 
I'm updating the TOC entry names to disambiguate the TOC entries. There is an in-topic link that goes to the VS 2022 article for Vue.

**Comment by dw-roth** [comment]
@Mikejo5000 I think you intended to tag @danroth27, not me.

**Comment by Mikejo5000** [comment]
TOC update should be live by EOD today, 8/8/23 PST
