### ISSUE TITLE
MSBuild Toolset documentation needs overhaul

### ISSUE THREAD

**Issue by rainersigwald** [MicrosoftDocs/visualstudio-docs#95]
These documents are mostly unchanged from VS2013/MSBuild 12.0, and need to be updated for the new "Willow"/ side-by-side VS installs world.

https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-toolset-toolsversion 

https://docs.microsoft.com/en-us/visualstudio/msbuild/standard-and-custom-toolset-configurations 

@Microsoft/msbuild-maintainers -- when one of us gets time this would be useful.

**Comment by kempb** [comment]
Added these issues to MSBuild doc update tracking task [986973](https://mseng.visualstudio.com/TechnicalContent/Visual%20Studio/_workitems?id=986973&_a=edit&triage=true).

**Comment by Mikejo5000** [comment]
Waiting for response from product unit

**Comment by KirillOsenkov** [comment]
just FYI @rainersigwald in on leave until end of year...

**Comment by Mikejo5000** [comment]
Thx. We will wait until he's back

**Comment by Mikejo5000** [comment]
Merged PR with fixes: MicrosoftDocs/visualstudio-docs-pr#1357
