### ISSUE TITLE
Microsoft

### ISSUE THREAD

**Issue by jchernand0** [MicrosoftDocs/visualstudio-docs#9508]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e6a5f0fc-0af8-6023-5b49-f5091a66dca5
* Version Independent ID: 9865696d-778c-4130-f1bc-9a551f15def2
* Content: [Create a visual map of the call stack - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio?view=vs-2022)
* Content Source: [docs/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/map-methods-on-the-call-stack-while-debugging-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by TimShererWithAquent** [comment]
@jchernand0 Thanks for your feedback. We appreciate it. To make sure we have all the information needed to triage your issue, please let us know which topic you’re referencing, or provide more context around the general task.

**Comment by WilliamAntonRohm** [comment]
I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
