### ISSUE TITLE
Was good chance to understand about ASP.NET frameworks presented by MS 

### ISSUE THREAD

**Issue by MacTechIN** [MicrosoftDocs/visualstudio-docs#9509]
[Enter feedback here]

Good exercise for mac users. 
I really want to use ASP.NET frame works for REST API also 
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ee1a5546-d01a-213d-d806-f2ffdca30929
* Version Independent ID: 042dc42b-b153-bbd3-30fa-a786e72686fd
* Content: [Building ASP.NET Core applications - Visual Studio for Mac](https://learn.microsoft.com/en-us/visualstudio/mac/building-asp-net-core?view=vsmac-2022)
* Content Source: [mac/building-asp-net-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/mac/building-asp-net-core.md)
* Product: **visual-studio-mac**
* Technology: **vs-ide-general**
* GitHub Login: @heiligerdankgesang
* Microsoft Alias: **dominicn**

**Comment by TimShererWithAquent** [comment]
Thanks @MacTechIN !
