### ISSUE TITLE
What is the b362ae64-b1c1-4f4d-a0af-76fe2cfdbd70 folder for?

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#951]
Seems to just be boilerplate OpenPublishing files and no content. Just wondering if it has a purpose or should be deleted

**Comment by gewarren** [comment]
@nschonni Thanks for noticing this folder. We do actually have a plan to give it a name and start putting docs in this folder, so I am going to close out your PR that removes it.
