### ISSUE TITLE
Missing code in XAML

### ISSUE THREAD

**Issue by DavideDunne** [MicrosoftDocs/visualstudio-docs#9512]
During the tutorial it is never mentioned to add `Click="Button_Click"` in the XAML in order to connect and trigger the button to the `Button_Click` function created in **Add code to the display button** section

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0e0c76-73a7-a310-88ab-3eaa5d43b03b
* Version Independent ID: 27c3bf84-6aac-ab22-008b-63e21cd16665
* Content: [Hello World app with WPF in C# - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-wpf.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-wpf.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@DavideDunne, thanks for your feedback. When you double click the "Display" button in We've updated the doc in step1 of the [Add code to the display button](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wpf?view=vs-2022#add-code-to-the-display-button) section, the XAML is updated with `Click="Button_Click"`.

The doc is updated and the changes should be live later today. Thanks!
