### ISSUE TITLE
Finding all Calls....(not comprehensive)

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [MicrosoftDocs/visualstudio-docs#9514]
C++  (with or without /clr) is challenging. Consider a class that has implicit constructors and destructors (compiler provided), there is nothing in the source code for them, but they are referenced throughout the code...
```
class Foo {}
void Bar()
{
   Foo f;
}
``` 
Now find all places where Foo is constructed or destructed....

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 27ca4cea-be24-22ad-49d0-d34e3f800900
* Version Independent ID: 8cd52773-0617-684e-8136-bd4ea03515de
* Content: [Find calls to a method - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/call-hierarchy?view=vs-2022)
* Content Source: [docs/ide/reference/call-hierarchy.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/call-hierarchy.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by j-martens** [comment]
#reassign:@ghogen

**Comment by ghogen** [comment]
@davidcorbin-atmosera 
My guess is that the only thing we could do here is add a disclaimer of some kind saying it doesn't find implicit calls.  I assume you tried this and were not finding the implicit destructor ?

**Comment by davidcorbin-atmosera** [comment]
> @davidcorbin-atmosera My guess is that the only thing we could do here is add a disclaimer of some kind saying it doesn't find implicit calls. I assume you tried this and were not finding the implicit destructor ?

1) The provlem should be reproducable with the snippet  in the original post on this issue [if it is not then it means I am wrong]. and instand of "Foo" is constructed and destructed within "Bar" but there is no documentation generated (again, that I saw).

2) I agree that a "disclaimer" (possibly using that snipped or similar) is the most practical. I have been (intermittently) working on identifying all similar conditions in a million-line ball of object **disoriented** code and still have not found a viable method of detecting them.

As a side note, the reason I am interested/concerned about this is for dependency analysis and lifetime management. So the code containing "Bar" is dependent on "Foo" (ie delete Foo and Bar will be Broken), but because the constructors and destructors are default (do nothing) and there are no members accessed, it could actually be removed (but this gets to the deeper levels than this particular report is about).

**Comment by ghogen** [comment]
@davidcorbin-atmosera 
I will add a note specifying more clearly what the limitations are. 

For your case, it is the case that unique internal symbols are generated for implicit methods; these follow certain patterns that you could find in certain intermediate output files. For managed code, you could examine IL. For native code, you might be able to output to assembler or analyze the intermediate object files (in Debug builds, not Release builds since those will elide some of these calls, certainly the no-ops) and get all the symbols you need for your analysis.
