### ISSUE TITLE
What about all the other configurations?

### ISSUE THREAD

**Issue by nickhoeferpickpro** [MicrosoftDocs/visualstudio-docs#9515]
This article doesn't go in any depth of the setup projects at all. it only gives instructions for a VERY basic project. Theres not even any links to any other deeper documentation of all the other configurations...

what do all of these options even do???
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/109171402/d4368f28-04b3-441a-9cbe-2cff5f9f05d7)

what about all these configurations?
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/109171402/7d0dd5a5-0fe3-4fc9-85cb-61e96220b7a0)

what about documentation for the .vdproj file?
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/109171402/4d43993c-fc41-4f4d-8da5-fe6340aaf607)

What about documentation on how to integrate this with build automation tools or command line tools?
It took me forever to figure out that the way to build it from command line is with the devenv.com tool (which I believe REQUIRES visual studio to be installed on a build server).

There's just so much that's missing...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8f59111-46ee-3f59-3635-616f93a92c2a
* Version Independent ID: edc371ba-5f33-803a-34e7-3de69f053691
* Content: [Visual Studio Installer Projects and .NET 6.0](https://learn.microsoft.com/en-us/visualstudio/deployment/installer-projects-net-core?view=vs-2022)
* Content Source: [docs/deployment/installer-projects-net-core.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/deployment/installer-projects-net-core.md)
* Product: **visual-studio-windows**
* GitHub Login: @MSLukeWest
* Microsoft Alias: **lukewest**

**Comment by nickhoeferpickpro** [comment]
This is still an issue

**Comment by j-martens** [comment]
#assign:@mikejo5000

**Comment by Mikejo5000** [comment]
@nickhoeferpickpro Yes, it looks like a few more links are needed.
For 2nd screenshot, these are doc'ed here:
https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/seykw6dt(v=vs.100)
I'm looking at others.

**Comment by Mikejo5000** [comment]
Update to the doc should be live by EOD today, PST.
