### ISSUE TITLE
Wrong release date for VSTO?

### ISSUE THREAD

**Issue by RCDane** [MicrosoftDocs/visualstudio-docs#9517]
I can see that the release date for VSTO runtime 10.0.60910 is set to 08/08/24, and the page has been updated today. Is this a mistake and the real release data is 08/08/23?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 655a04bf-4de2-c8d2-3727-dadf55884472
* Version Independent ID: 5a04593f-b108-48ab-5cc0-b7f87b587a2b
* Content: [Visual Studio Tools for Office Runtime Lifecycle Policy](https://learn.microsoft.com/en-us/visualstudio/vsto/visual-studio-tools-for-office-runtime?view=vs-2022)
* Content Source: [docs/vsto/visual-studio-tools-for-office-runtime.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/visual-studio-tools-for-office-runtime.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by TimShererWithAquent** [comment]
@John-Hart can you verify? I see you added this entry last week.

**Comment by John-Hart** [comment]
Thanks Tim!

**Comment by John-Hart** [comment]
it should be fixed now.  Thanks again @TimShererWithAquent

**Comment by TimShererWithAquent** [comment]
And thanks @RCDane for finding the issue in the first place!
