### ISSUE TITLE
"Issue Reporting" link on index page points to old Connect site depreciation warning

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#952]
The link to https://go.microsoft.com/fwlink/?linkid=833104 resolves to https://docs.microsoft.com/en-us/collaborate/connect-redirect. Not sure if it should get updated to the devcommunity site or something else. It's a pretty prominent link and doesn't lead to an actionable issue reporting site.

**Comment by gewarren** [comment]
@nschonni Thanks for reporting this. We'll definitely get the link updated at https://docs.microsoft.com/en-us/visualstudio/.

**Comment by gewarren** [comment]
@TerryGLee has an idea to fix this.

**Comment by TerryGLee** [comment]
PR in play: [https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/2062](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/2062)

**Comment by TerryGLee** [comment]
@nschonni Thanks; we've fixed this so that the Issues Reporting link points to our [Talk to Us](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) page. We appreciate your help with this. :)
