### ISSUE TITLE
"Include miscellaneous files" needs more explanation

### ISSUE THREAD

**Issue by Maintenance-Partnership-Systems** [MicrosoftDocs/visualstudio-docs#9522]
The "Include miscellaneous files" option needs more explanation, as it actually does some unexpected things.  A more detailed explanation of exactly what is does and does not include in the search scope needs to be provided.

For example: if "Include miscellaneous files" is ticked, then "Find in Files" will include compiler-generated temporary files found in the users AppData\Local\Temp folder in its search scope - generally adding entirely spurious hits to the search result that just confuse matters.  Such files certainly do not fall under the definition of "files that you've opened but aren't part of a solution", as you have not "opened" them at all.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0e27881f-04bc-b7ba-e217-8360278a14f8
* Version Independent ID: d31c8050-339a-688c-869e-ff7942fd3f74
* Content: [Find in Files - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/find-in-files?view=vs-2022&source=docs)
* Content Source: [docs/ide/find-in-files.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/find-in-files.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@Maintenance-Partnership-Systems -- thank you for your detailed feedback.  If you feel this is also a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@TerryGLee -- please look into this issue.

**Comment by j-martens** [comment]
#reassign:@ghogen

**Comment by Maintenance-Partnership-Systems** [comment]
> @Maintenance-Partnership-Systems -- thank you for your detailed feedback. If you feel this is also a product issue, please add it here:
> 
>     * Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​

Thank you; I have logged an issue report for Visual Studio.

**Comment by ghogen** [comment]
I think entering an issue was an appropriate thing to do, since that behavior sounds like it should be investigated as a bug. I'll close this as a documentation issue.
