### ISSUE TITLE
Visual Studio 2022 installation path

### ISSUE THREAD

**Issue by Zer0cul** [MicrosoftDocs/visualstudio-docs#9528]
[Visual Studio 2022 version 17.1](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1710--visual-studio-2022-version-171-newreleasebutton) or later on a 64-bit machine

C:\Program Files (x86)\Microsoft Visual Studio\2022\ ...
on my Windows 10 64bit correct path is:
C:\Program Files\Microsoft Visual Studio\2022\ ...

btw, great article!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 513f1e35-aba1-8b92-845e-1ed4ccad8e62
* Version Independent ID: 45eb46ce-a9b1-f141-5a97-c448b9349c48
* Content: [Command-line shells & prompt for developers - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/command-prompt-powershell?view=vs-2022)
* Content Source: [docs/ide/reference/command-prompt-powershell.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/command-prompt-powershell.md)
* Product: **visual-studio-windows**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@Zer0cul You're absolutely right, we'll get that fixed ASAP and report back when the fix is published. And, thanks for the compliments on the page, too!

**Comment by TerryGLee** [comment]
@Zer0cul The updated page is published; we'll close this issue now with our thanks to you for your interest & help with improving the Visual Studio documentation!
