### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by conyg** [MicrosoftDocs/visualstudio-docs#9544]
[Enter feedback here]
I had developed a console application using .Net Framework that references Primary Interop Assemblies.
When deploying the application I need the Primary Interop Assemblies redistributables if the machine does not have office installed.

I was searching for it on the Microsoft website and I couldn't find it. I found this page that talks about installation of the assemblies and I thought that I finally found my answer. But no, the page is missing the other method of installation (from the redistributable package). 

Here is the current link to the redistributable package: https://www.microsoft.com/en-ie/download/details.aspx?id=3508

Please add this info.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e97e75d6-dc3e-800e-7cff-d097023df034
* Version Independent ID: 89401b4f-16db-66ab-512c-cce9f949ac10
* Content: [How to: Install Office primary interop assemblies - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/vsto/how-to-install-office-primary-interop-assemblies?view=vs-2022)
* Content Source: [docs/vsto/how-to-install-office-primary-interop-assemblies.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/how-to-install-office-primary-interop-assemblies.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
It's recommend that you use embedded types instead of using the PIAs?  Otherwise it looks like https://www.microsoft.com/en-US/Download/details.aspx?id=3508 is the only available download
