### ISSUE TITLE
Format makes content nearly impossible to use

### ISSUE THREAD

**Issue by mickeyjf** [MicrosoftDocs/visualstudio-docs#955]
With scrollable sidebars on either side, the main content is restricted to fewer characters than fit horizontally, but there is no way even to scroll sideways without first scrolling to the bottom of the document. At this point, you lose your place, and when you go back up you can no longer see the left most part of the line(s) you cared about anyway.  "Download PDF" fails with bad format. "Copy" does not copy anything useful. This applies to all documents, not just the one linked to this comment. Please provide a way to hide or minimize the sidebars, scroll the main window sideways, download or copy the content to use in a user's reader of choice or something, otherwise there's not much point in even bothering with providing this because using it is a struggle.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6254da8-fbe7-cc2a-2c10-1ba918a61039
* Version Independent ID: 7d3100b1-8ab0-f17f-6494-d183bdeb9081
* Content: [MSBuild Command-Line Reference - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference#feedback)
* Content Source: [docs/msbuild/msbuild-command-line-reference.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild/msbuild-command-line-reference.md)
* Service: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by gewarren** [comment]
@mickeyjf Thanks for reporting this. We had another complaint about this same issue recently #1098. I'm forwarding this feedback to the site design team.

**Comment by TerryGLee** [comment]
@gewarren Thanks for forwarding this to the site design team for their consideration. I'll close this issue now, as it's being handled via another venue.
@mickeyjf Thanks for your suggestions on how we can improve the documentation!
