### ISSUE TITLE
Questions about the Visual Studio Proposals API

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#9554]
---
**Issue moved from dotnet/dotnet-api-docs#9147**
- Please respond to @fortenforge.

---

_From @fortenforge on Tuesday, July 18, 2023 3:33:47 AM_

The Visual Studio 2022 SDK includes the [Proposals](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.proposals?view=visualstudiosdk-2022) API, which is largely undocumented. I fully understand that this API is not yet finalized and can change without warning. Nevertheless, I have some questions about it that I hope someone can answer.

* When exactly is RequestProposalsAsync called? I see there's a list of [ProposalScenario](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.proposals.proposalscenario?view=visualstudiosdk-2022#fields)s that indicate it could be called in many circumstances, but when is it actually called right now? In practice it seems like if there's non-trivial text to the right of the caret, proposals are never shown.
* I'm encountering a rather annoying issue where when the user hits Enter, the caret gets visually auto-indented in virtual space, but the underlying text buffer does not reflect this indentation. As such, whatever proposal I return tends to include this indentation which makes the proposal be rendered away from the actual caret. What's the best solution for this?
* Several of the [ProposalFlag](https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.proposals.proposalflags?view=visualstudiosdk-2022#fields)s don't seem to have any effect. Specifically QueueProposalRequestOnCommit and SingleTabToAccept. Are these expected to work?

**Comment by gewarren** [comment]
---
**Issue moved from dotnet/dotnet-api-docs#9147**
- Please respond to @dotnet-issue-labeler[bot].

---

_From @dotnet-issue-labeler[bot] on Tuesday, July 18, 2023 3:34:02 AM_

I couldn't figure out the best area label to add to this issue. If you have write-permissions please help me learn by adding exactly one area label.

**Comment by gewarren** [comment]
---
**Issue moved from dotnet/dotnet-api-docs#9147**
- Please respond to @tarekgh.

---

_From @tarekgh on Thursday, August 17, 2023 8:34:20 PM_

@gewarren do you know if the docs https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.proposals?view=visualstudiosdk-2022 belong to this repo?

**Comment by gewarren** [comment]
---
**Issue moved from dotnet/dotnet-api-docs#9147**
- Please respond to @gewarren.

---

_From @gewarren on Monday, August 21, 2023 3:07:07 PM_

@tarekgh No, they're coming from this private repo: https://github.com/MicrosoftDocs/visualstudio-docs-dotnet-api-pr/blob/live/visualstudiosdk. @gregvanl where should we transfer this issue?

**Comment by fortenforge** [comment]
would love to talk to someone at VS who understands this API

**Comment by gewarren** [comment]
@ghogen Do you know who can answer questions about the Microsoft.VisualStudio.Language.Proposals API?
