### ISSUE TITLE
windows command prompt

### ISSUE THREAD

**Issue by jessehouwing** [MicrosoftDocs/visualstudio-docs#9555]
All the prompt examples show " windows command prompt", but that's misleading, it should probably read "visual studio command window" or something similar, cause on a normal command prompt you can't use these commands.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1e03360d-8d59-3358-ee32-980e1a87958e
* Version Independent ID: 9fac3efe-af10-d842-c55a-095ec6474d93
* Content: [Open File Command - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/open-file-command?view=vs-2022)
* Content Source: [docs/ide/reference/open-file-command.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/open-file-command.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@jessehouwing -- Jesse, thank you for your interest in improving our documentation.  I am updating that terminology.
