### ISSUE TITLE
Updated path to open Visual Studio from Unreal Engine

### ISSUE THREAD

**Issue by maxjaudio** [MicrosoftDocs/visualstudio-docs#9562]
Path to open Visual Studio in UE 5.1+ is Tools -> Open Visual Studio, not File -> Open Visual Studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32c8fa86-3234-362e-c4a0-27d26056596f
* Version Independent ID: 32c8fa86-3234-362e-c4a0-27d26056596f
* Content: [Quickstart: Visual Studio Tools for Unreal Engine](https://learn.microsoft.com/en-us/visualstudio/gamedev/unreal/get-started/vs-tools-unreal-quickstart)
* Content Source: [gamedev/unreal/get-started/vs-tools-unreal-quickstart.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/gamedev/unreal/get-started/vs-tools-unreal-quickstart.md)
* Product: **visual-studio**
* Technology: **vs-unreal-engine-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **TWhitney**

**Comment by TylerMSFT** [comment]
Thank you for catching that. Fixed. Will be live by Monday afternoon.
