### ISSUE TITLE
Could Add Information on Finding the Include / Libs Paths

### ISSUE THREAD

**Issue by fundmntlTheorem** [MicrosoftDocs/visualstudio-docs#9569]
Really great tutorial!  

As I had never done this kind of thing, I had to search around to find the appropriate include path, which changed once I made a new environment as described in the tutorial.  Adding information about how to get the include and libs path would have been helpful.  I found this here:
https://stackoverflow.com/questions/35071192/how-to-find-out-where-the-python-include-directory-is

    from sysconfig import get_paths
    from pprint import pprint

    info = get_paths()  # a dictionary of key-paths

    pprint(info)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 40e3b6b1-a3d2-f4f2-b1ad-dd654a062343
* Version Independent ID: b2418b84-04f4-60d2-ec1d-291a5d4d0c51
* Content: [Write C++ extensions for Python - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/working-with-c-cpp-python-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/working-with-c-cpp-python-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
Thanks for the feedback! I have added links to the official Python documentation for help regarding this. #please-close
