### ISSUE TITLE
ASP.NET Core app with React  out of date

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/visualstudio-docs#9571]
Search for `Once the project is created, Solution Explorer should look like this:`

Looks like when this doc was written a Web API app was used. It's currently using minimal APIs so there's no controller, no `WeatherForcast.cs` file, etc.

The current template looks much different.

<img width="205" alt="image" src="https://github.com/MicrosoftDocs/visualstudio-docs/assets/3605364/2dc7fc64-4056-47ee-a18f-cad5198a9bb2">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f5beb7f5-5d28-d5e5-92ba-3e04c75e44b5
* Version Independent ID: 867e3a3f-2387-ba46-c911-10822f8c4a81
* Content: [Create an ASP.NET Core app with React - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-react?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-react.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Rick-Anderson** [comment]
@Mikejo5000 I'm working on this.

**Comment by Mikejo5000** [comment]
Updates in linked PR now merged.
