### ISSUE TITLE
ASP.NET Core app with Angular out of date

### ISSUE THREAD

**Issue by Rick-Anderson** [MicrosoftDocs/visualstudio-docs#9574]
Same as #9571

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
Updates in linked PR now merged.
