### ISSUE TITLE
Where is this "Application" tab"?

### ISSUE THREAD

**Issue by mcswell** [MicrosoftDocs/visualstudio-docs#9582]
Instructions say "When the Project Designer appears, click the Application tab."  There is no "Application" tab, in fact the Project Designer looks nothing like the picture.  On my system, this Property Pages dlg box has 3 controls across the top, for "Configuration", "Platform" and "Configuration Manger..."  Below that are two columns: on the left is "Configuration Properties" with a number of sub-entries, like "General", "Advanced", "C/C++" etc.  On the right are some properties.  If I have "General" selected on the left, then the right column shows "General Properties" like "Output Directory", "Intermediate Directory" etc.  No where do I see anything labeled "Application".

Where is this "Application" tab"?  And if what I describe above is not the Project Designer, what is it, and how do I get to the Project Designer?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: db2f3877-b9ea-1ee4-b4ab-ec146139cf5b
* Version Independent ID: b9e98d4e-1053-4ac3-f1f0-a31c12e72f6f
* Content: [Application page of C# project properties - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/application-page-project-designer-csharp?view=vs-2022)
* Content Source: [docs/ide/reference/application-page-project-designer-csharp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/application-page-project-designer-csharp.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by j-martens** [comment]
#reassign:@anandmeg

**Comment by anandmeg** [comment]
@mcswell, are you working with a C# project? The page [Application page of C# project properties - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/application-page-project-designer-csharp?view=vs-2022) applies to a C# project. From the description of what you're seeing, it sounds like your project might be C++.

**Comment by anandmeg** [comment]
@mcswell, closing this issue now. Please review the comments above and feel free to re-open the issue with additional information.

Thanks again for your feedback!
