### ISSUE TITLE
Move Type To File issue

### ISSUE THREAD

**Issue by reponemec** [MicrosoftDocs/visualstudio-docs#9583]
This doesn't work for me in Visual Studio 2022, version 17.7.2. It pretends to do it, but nothing happens.
Workaround: @oleg-shilo https://marketplace.visualstudio.com/items?itemName=OlegShilo.MoveTypeToFile works perfectly.

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8139dca2-5127-1385-f3a3-d945b12b9d2e
* Version Independent ID: c455e23d-6d9b-c0f0-5f7c-be5dea7a5259
* Content: [Move type to matching file refactoring - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/move-type-to-matching-file?view=vs-2022&tabs=csharp)
* Content Source: [docs/ide/reference/move-type-to-matching-file.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/move-type-to-matching-file.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by reponemec** [comment]
I am currently using Visual Studio 2022 Enterprise, Version 17.8.2 and the problem still persists.

**Comment by WilliamAntonRohm** [comment]
Please add this as a product issue here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
