### ISSUE TITLE
Mr. Claud Lowe

### ISSUE THREAD

**Issue by battleaxe1151** [MicrosoftDocs/visualstudio-docs#9586]
Excellent but confusing to me since I'm a tad old. My main interest is to make an executable when I complete a project in VS so I can let others have it and use it.
My thanks for providing this information.
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a5db8407-cc91-c741-6bc4-9d059ab40308
* Version Independent ID: 8d477def-5203-6085-915b-31971afeccab
* Content: [Tutorial: Build an application - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/walkthrough-building-an-application?view=vs-2022)
* Content Source: [docs/ide/walkthrough-building-an-application.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/walkthrough-building-an-application.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@battleaxe1151 -- Claud, thank you for your kind words!

cc @ghogen

**Comment by battleaxe1151** [comment]
Any time.
