### ISSUE TITLE
How do I know which exception will be thrown?

### ISSUE THREAD

**Issue by shukla18** [MicrosoftDocs/visualstudio-docs#959]
In some cases, possible no of exceptions can be more than one. There are chances that we may leave one or some exceptions. 

Is there a way to figure out all possible exception which can be thrown by code in try block?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d89b0f64-db03-af39-fdf7-ccb31c9ae01b
* Version Independent ID: 95c4aac2-4e98-240b-54e5-64981ab68cec
* Content: [CA1031: Do not catch general exception types - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1031-do-not-catch-general-exception-types)
* Content Source: [docs/code-quality/ca1031-do-not-catch-general-exception-types.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/code-quality/ca1031-do-not-catch-general-exception-types.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@shukla18 The documentation for .NET API methods tells you which exception(s) they throw - for example take a look at [FileStream.Lock()](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.lock?view=netframework-4.7.1#System_IO_FileStream_Lock_System_Int64_System_Int64_) which throws three exceptions: ArgumentOutOfRangeException, ObjectDisposedException, and IOException.

For a good article about catch exceptions in C#, see this [MSDN magazine article](https://msdn.microsoft.com/en-us/magazine/mt620018.aspx). Hope this helps.

**Comment by gewarren** [comment]
@shukla18 Please reopen if you feel that updates need to be made to this topic.

**Comment by bartosz-jarmuz** [comment]
The problem is that .NET API is not the only API that people use. With this warning, one has to know what type of exception can come from each of the 3rd party methods called in a try-catch block.
That sucks, especially if a developer actually DOES something (e.g. log) with the exception - not just swallow it.
