### ISSUE TITLE
Customize on tools...

### ISSUE THREAD

**Issue by SMECMS** [MicrosoftDocs/visualstudio-docs#9593]
So let's see if I get this straight, for customizing your shortcuts you go into tools and you see costumize... and options... and the logical conclusion that the geniuses at Microsoft arrived was to put this costumization feature in the options.. menu instead of the, I dunno, costumize... menu, now this is design coherence 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5859be-5f6e-4354-a0b0-c14ffc047d23
* Version Independent ID: d2033d27-92b9-6f70-286a-cefb0a58b15a
* Content: [Identify and customize keyboard shortcuts - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@SMECMS -- thank you for your feedback.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
