### ISSUE TITLE
Wrong using directive in CalculatorLibrary.cs - Section "Add a NuGet Package: Write to a JSON file"

### ISSUE THREAD

**Issue by pcjb** [MicrosoftDocs/visualstudio-docs#9608]
In step 3 of section ["Add a NuGet Package: Write to a JSON file"](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022#add-a-nuget-package-write-to-a-json-file) I miss the modification of the using directive in CalculatorLibrary.cs:
The directive `using System.Diagnostics;` is no longer necessary as the tutorial does not use the .NET Trace class in the following steps.
Instead the directive `using Newtonsoft.Json;` must be added to be able to use JsonWriter in this step of the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80ccbb63-7f84-55e6-1b3e-f48400aa17ae
* Version Independent ID: 6aba5d1b-f8ce-7b82-560e-c6a9926423ac
* Content: [Tutorial 2: Extend your C# console app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-console-part-2?view=vs-2022#add-a-nuget-package-write-to-a-json-file)
* Content Source: [docs/get-started/csharp/tutorial-console-part-2.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-console-part-2.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@pcjb, thanks for your feedback and your contribution to our docs, helping us improve our docs.
