### ISSUE TITLE
Article is outdated.

### ISSUE THREAD

**Issue by Owlinated** [MicrosoftDocs/visualstudio-docs#961]
According to [1] "Calls From" has been removed since VS 2015.
I am not a fan of that change, but I think the documentation should reflect it.

[1] https://developercommunity.visualstudio.com/content/problem/74344/in-call-hierarchy-windows-calls-from-is-missing.html

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27ca4cea-be24-22ad-49d0-d34e3f800900
* Version Independent ID: 8cd52773-0617-684e-8136-bd4ea03515de
* Content: [Viewing call hierarchy in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/reference/call-hierarchy)
* Content Source: [docs/ide/reference/call-hierarchy.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/reference/call-hierarchy.md)
* Service: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@Owlinated Thank you Florian, I will update this.

**Comment by gewarren** [comment]
The article has been updated. Thanks for noticing this @Owlinated .
