### ISSUE TITLE
This page uses the value "v4.0" in the example for TargetFrameworkVersion, but does not list it as a valid version.

### ISSUE THREAD

**Issue by StingyJack** [MicrosoftDocs/visualstudio-docs#9618]
It doesnt make sense. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a80e5d7-2db7-48c0-e8b6-ca8c3ff30017
* Version Independent ID: ad64635b-06d5-1b87-8f02-80cf25c12520
* Content: [MSBuild Target Framework and Target Platform - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-target-framework-and-target-platform?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-target-framework-and-target-platform.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-target-framework-and-target-platform.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- Andrew, thank you for your close reading.  I am updating those instances to "v4.8".

**Comment by StingyJack** [comment]
@WilliamAntonRohm  - I brought this up because I've never actually seen this value be anything other than v4.0 in a config file, so this page is rather confusing.

**Comment by WilliamAntonRohm** [comment]
@StingyJack -- Andrew, thank you for clarifying.

@ghogen -- Gordon, please look into this issue.
