### ISSUE TITLE
CustomBuildEventArgs doc updates

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/visualstudio-docs#9623]
Extracted from https://github.com/dotnet/docs/issues/36403:

- [ ] https://learn.microsoft.com/en-us/dotnet/api/microsoft.build.framework.custombuildeventargs?view=msbuild-17-netcore needs to link to https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/custombuildeventargs.
- [x] Refresh the MSBuild API ref to include these new types:

  ExtendedCustomBuildEventArgs
  ExtendedBuildErrorEventArgs
  ExtendedBuildMessageEventArgs
  ExtendedBuildWarningEventArgs

  Once the API ref is live, it would be good to update https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/custombuildeventargs with xref links to those types in the "Recommended action" section.

**Comment by ghogen** [comment]
Submitted MSBuild PR:
https://github.com/dotnet/msbuild/pull/9221

**Comment by ghogen** [comment]
The MSBuild team should be publishing the 17.9 updates to the docs soon, which should mean my fix for the first task in this bug will be fixed.
