### ISSUE TITLE
mention vs_installer

### ISSUE THREAD

**Issue by cowlinator** [MicrosoftDocs/visualstudio-docs#963]
This page (or another page) should make mention of vs_installer.exe and vs_installershell.exe .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@cowlinator Thanks for your suggestion; we'll take this into consideration. :)

**Comment by charlesprakash** [comment]
Still searching for vs_installer doesn't give anything anywhere on the Internet. Is it possible to upgrade an existing VS installation using the vs_installer.exe? If so, please provide the steps. Thanks!

**Comment by TerryGLee** [comment]
@tydunkel FYI, and any input you can provide would be appreciated (as always)

**Comment by tydunkel** [comment]
@charlesprakash Yes, you can use the vs_installer.exe for an update to a VS installation. When scripting we recommend using the latest vs_<sku>.exe from the web to ensure that the latest vs_installer.exe is installed to handle the installation. However, when running interactively it is unnecessary to download vs_<sku>.exe to update. Simply start the VS Installer from a start menu or `"%programfiles(x86)%\Microsoft Visual Studio\Installer\vs_installer.exe"` and click the "Update" button.

**Comment by cowlinator** [comment]
@tydunkel , what about "headless" (no UI) situations such as inside docker containers?

**Comment by tydunkel** [comment]
@cowlinator it is still possible to use vs_installer.exe directly when running headless. Typically, you can build the full path to the installer using the %programfiles(x86)% environment variable.

e.g. `"%programfiles(x86)%\Microsoft Visual Studio\Installer\vs_installer.exe" update --installPath "C:\Program Files (x86)\Microsoft Visual Studio
2017" --quiet`

If an update is required to the installer it should automatically apply it. If you are running in a script, though, the installer will shut down and your script will likely continue executing without waiting for the product update to complete. For this, we recommend running two commands to update the installer then the product.

e.g. `vs_community.exe --update --quiet` followed by the above command or `vs_community.exe update --installPath <your path> --quiet --wait`

See the [admin docs](https://docs.microsoft.com/en-us/visualstudio/install/update-a-network-installation-of-visual-studio?view=vs-2019#how-to-deploy-an-update-to-client-machines) for more details.

**Comment by cowlinator** [comment]
@tydunkel , thank you, that's exactly the kind of documentation I'm talking about.  The kind that should exist on documentation pages such as https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019 .  

Also, is it possible to add components using `vs_installer.exe`?  

Also, it seems that `vs_installershell.exe` is giving verbose output to stdout, unlike `vs_installer.exe`.  But `vs_installershell.exe` is never documented anywhere.  It's a well-kept secret.

**Comment by tydunkel** [comment]
@cowlinator Yes, `vs_installer.exe` can be used to add components. It uses the same command line parameters as `vs_<sku>.exe` in that regards.

e.g. `vs_installer.exe modify --installPath <Path to VS> --add Microsoft.VisualStudio.Workload.ManagedDesktop;includeRecommended;includeOptional --Microsoft.VisualStudio.Workload.NativeDesktop;includeRecommended --quiet`

The main reason to use the `vs_<sku>.exe` is when writing scripts to update or install a product. You can use two commands to update the installer then the VS installation and the script will wait for both to complete before continuing. When you are just running commands through a cmd prompt there is user interaction so running the `vs_installer.exe` directly should fit your needs.

**Comment by cowlinator** [comment]
@tydunkel , thank you for clarifying all of this.  

I'm unfamiliar with any real-world use-case where one would bother to run non-scripted commands through a cmd prompt and then use the UI instead of just using the UI to begin with.  

I am most interested in the use-case where one writes scripts to update or install a product.  

The problem being that when `vs_<sku>.exe` or `vs_installer.exe` with `--quiet` fail, they fail silently.  It's non-trivial to get these installers to run synchronously and return an real return code (requires a batch script with both `/wait` and `--wait > nul`, see https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019 ).

`vs_installershell.exe` gives verbose output, clearly prints errors to the console, and is synchronous by default.

It seems useful enough to document.

**Comment by goyzhang** [comment]
Is there any example of how `vs_installershell.exe` works? I need to use this to install components in my docker image. But I can't find any.

**Comment by TerryGLee** [comment]
Thanks everyone for your inquiries on this subject. We're adding text to this page regarding the use of `vs-installer.exe`. 

But, after confirming with the engineering team, we respectfully decline to document using `vs_installershell.exe` on this page. For more information about Visual Studio Build Tools and Docker, please see the following pages instead:

- [Install Build Tools into a container](https://docs.microsoft.com/visualstudio/install/build-tools-container?view=vs-2019) 
- [Advanced example for containers](https://docs.microsoft.com/visualstudio/install/advanced-build-tools-container?view=vs-2019)
- [Known issues for containers](https://docs.microsoft.com/visualstudio/install/build-tools-container-issues?view=vs-2019)

**Comment by cowlinator** [comment]
@TerryGLee , Understood, that's unfortunate, but thanks for looking into this.  Hopefully the docs you linked are as helpful.

@goyzhang , As of now, the arguments for `vs_installershell.exe` appear to be identical to the arguments for `vs_installer.exe`.
For example, to install `Microsoft.Net.Component.4.7.1.SDK` I would use this command: 
```
vs_installershell.exe modify --norestart --quiet --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional" --add Microsoft.Net.Component.4.7.1.SDK
```
