### ISSUE TITLE
This help page is not helpful

### ISSUE THREAD

**Issue by tjet33** [MicrosoftDocs/visualstudio-docs#9632]
[Enter feedback here]

How about writing the step-by-step process by which to set VB DPI to 100% scaling?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a2f87f79-412c-6d45-9a5f-e1690a7dce12
* Version Independent ID: 708a3cc0-a8eb-3b23-9d11-737d0060d730
* Content: [Fix DPI display issues in Windows Form Designer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2022#restart-visual-studio-as-a-dpi-unaware-process)
* Content Source: [docs/designers/disable-dpi-awareness.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/designers/disable-dpi-awareness.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-designers**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by WilliamAntonRohm** [comment]
@tjet33 -- Jesse, thank you for your feedback.  Please see this section and the two subsequent sections:
- [Restart Visual Studio as a DPI-unaware process](https://learn.microsoft.com/en-us/visualstudio/designers/disable-dpi-awareness?view=vs-2022#restart-visual-studio-as-a-dpi-unaware-process)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
