### ISSUE TITLE
VSTO Outlook Plugin: AppointmentItem GlobalAppointmentItem behavior is not matching with exchange data using GRAPH APIs for the recurring meetings

### ISSUE THREAD

**Issue by ManojPatelA** [MicrosoftDocs/visualstudio-docs#9635]
**With outlook VSTO plugin, GlobalAppointmentID is same for series master and individual occurrences, however with GRAPH API event resource type it is different for each occurrences.**

https://learn.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0 (refer iCalUid)

Since this is different behavior, how can we access GlobalAppointmentID of individual occurrences which is there on exchange without querying GRAPH APIs.

**Is there any documentation available about this difference between outlook client plugins and exchange data ?**

Thanks, Manoj

**Comment by WilliamAntonRohm** [comment]
@ManojPatelA -- Manoj, thank you for your feedback.  Please see this article, and let me know if it applies to your situation:
- [Obtain immutable identifiers for Outlook resources](https://learn.microsoft.com/en-us/graph/outlook-immutable-id)

**Comment by ManojPatelA** [comment]
@WilliamAntonRohm Thanks, Actually this will not help in this scenario as I am looking for GlobalAppointmentID (iCAlUID) for the individual occurrences from the VSTO plugin. 
Also, there is no documentation available about this difference in the behaviour for outlook plugins and exchange data (GRAPH APIs).
