### ISSUE TITLE
RTC page is almost useless

### ISSUE THREAD

**Issue by mdeisher** [MicrosoftDocs/visualstudio-docs#9637]
The help page on RTC does not explain how to enable RTC.  It is truly frustrating to be told that an option exists but not to be told where in the numerous configuration dialogs it can be set.  Why force the user to do a brute force search when you could just tell them where it is?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9bd0927-8b4a-07c0-4010-919a22f0d2e0
* Version Independent ID: 231c93c7-bb31-6c1a-d9f5-04ea61f52152
* Content: [Use Native Run-Time Checks - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/how-to-use-native-run-time-checks?view=vs-2022)
* Content Source: [docs/debugger/how-to-use-native-run-time-checks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/how-to-use-native-run-time-checks.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by JHBeyer** [comment]
It is sort of even worse than that.  Smaller Type Check (C/C++/Code Generation) is now recommended to NEVER be used.  If so, then why is it there?  It conflicts (flags code that is not incorrect) with STL libraries.

https://developercommunity.visualstudio.com/t/uniform_int_distribution-in-1751-cause/10304203?viewtype=solutions

**Comment by Mikejo5000** [comment]
@mdeisher Thanks for the feedback! It looks like it's documented here:
https://learn.microsoft.com/en-us/cpp/build/reference/rtc-run-time-error-checks?view=msvc-170#remarks

I'll update this article to point to the other article, and we will need to mention that issue about Smaller Type Check.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/11948536/632f7979-7471-49bd-a288-a40ca1a53315)

**Comment by Mikejo5000** [comment]
Updated article. Update will be live be EOD 10/24, PST.
