### ISSUE TITLE
Documentation on Source Control options

### ISSUE THREAD

**Issue by thomb1** [MicrosoftDocs/visualstudio-docs#964]
Cannot find any documentation on Tools -> Options  -> Source Control. What does "Independent Developer" vs "Custom" etc do? from what I can tell, it just causes checkboxes you've unchecked to magically check themselves. Note I'm using Dynamsoft as the source control provider.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9290996a-853e-bfcc-5e4a-d8746f453620
* Version Independent ID: faae284e-2f81-6f6f-c437-0bd8c959dd2b
* Content: [Overview of Visual Studio 2017 - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/visual-studio-ide#feedback)
* Content Source: [docs/ide/visual-studio-ide.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/visual-studio-ide.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@thomb1 Thank you for the additional feedback. I will review the topic and get the missing content added.

**Comment by thomb1** [comment]
You’re probably going to hate me :)
I’ll likely be posting these regularly...

I’ve inherited an absurdly over engineered visual studio solution- folks used things just for the sake of using them .... and now I have to make it work moving forward .

so getting hung up on not finding an answer I’d rather help you all out vs just yelling at the screen :)

I write all of our documentation so I know it’s a thankless job. I appreciate you taking the time to respond.

On May 16, 2018, at 5:45 PM, Genevieve Warren <notifications@github.com<mailto:notifications@github.com>> wrote:


@thomb1<https://github.com/thomb1> Thank you for the additional feedback. I will review the topic and get the missing content added.

**Comment by gewarren** [comment]
@thomb1 Actually no, I truly appreciate feedback from the user perspective! Thank you.

**Comment by nschonni** [comment]
@gewarren that option appears when you select "Visual Studio Team Foundation Server" and then look at the new node `Environment`. GH appears to refuse to upload my image, but you'll find it once you flip your plug-in selection 👍

**Comment by gewarren** [comment]
@nschonni Ah, thanks! I see them now.

![image](https://user-images.githubusercontent.com/24882762/42108149-8f171c94-7b8e-11e8-8f8c-2bc801d3508b.png)

**Comment by gewarren** [comment]
@thomb1 Did you see this? https://www.dynamsoft.com/help/SCM%20Hosted/Visual-Studio-Package-Plugin/Source-Control--Environment-Settings.htm It sounds like you're seeing something a little different though. It seems to me that "Team Foundation" and "Independent Developer" are just preconfigured profiles that check/uncheck boxes to set the check out behavior for that profile. Or, you can create your own "Custom" profile with custom check out behavior.

**Comment by thomb1** [comment]
Hi Genevieve and all,
First of all, thank you for all the work you’ve put into this!

I am embarrassed to say that no didn’t really spend a lot of time looking at DynamSoft’s docs…mostly because as you said, its not the same screens – their docs are specific to older revs of Visual Studio.

Anyhow, I was able to get source control configured reasonably well using the below –  this is probably not helpful to you’all… but just in case, these settings are giving me the best user experience…I’m scared to click around too much – many Bothans died to get to this set up ☺

[cid:image003.jpg@01D40FBA.98814790]
[cid:image004.jpg@01D40FBA.98814790]

Regards,
Thom

Thom C. Blackwell,  VP Technical Services
Boston Software Systems, Inc.
Phone: 866.653.5105 x807
Mobile: 508.423.8463
Fax: 508.319.3015
www.bostonsoftwaresystems.com<http://www.bostonsoftwaresystems.com/>

The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by LisandroSu** [comment]
Hi @gewarren can we close this issue?

Thanks!
