### ISSUE TITLE
New VSTOR version link

### ISSUE THREAD

**Issue by stdin82** [MicrosoftDocs/visualstudio-docs#9640]
New VSTOR version is released last month, as security update
https://support.microsoft.com/help/5029497

if it is possible to update "Visual Studio 2010 Tools for Office runtime" setup download link to the latest
or better use permalink:
http://go.microsoft.com/fwlink/?linkid=140384 or https://aka.ms/VSTORuntimeDownload

language pack link can also be:
http://go.microsoft.com/fwlink/?LinkId=140386

but make a notice that this latest version is SHA2-signed only (unlike previous version from 2018)
aside from the installer signature, the runtime files are still compatible with Windows XP and later

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 452374f5-e8d0-37e6-558d-c44c3926fec4
* Version Independent ID: 8f3cb5a2-ed9e-3c10-a507-6a9e3bc0588e
* Content: [How to: Install the Visual Studio Tools for Office Runtime Redistributable](https://learn.microsoft.com/en-us/visualstudio/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable?view=vs-2022&source=recommendations)
* Content Source: [docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@stdin82 thanks for letting us know

**Comment by John-Hart** [comment]
this should be fixed soon
