### ISSUE TITLE
There is no Contact My Admin button

### ISSUE THREAD

**Issue by dbakepner** [MicrosoftDocs/visualstudio-docs#9644]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a47a443c-b3f6-8fc1-6c38-d7a6c6ec9bf2
* Version Independent ID: aca4f0e1-0cbc-87c1-a1d2-d01672d0a949
* Content: [Contact your subscription admin in the Subscriber Portal](https://learn.microsoft.com/en-us/visualstudio/subscriptions/contact-my-admin)
* Content Source: [subscriptions/contact-my-admin.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/contact-my-admin.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@dbakepner Thank you for reaching out.  Whether you see a button to contact your admin depends on whether your subscription is actually managed by an admin.  For example, if your subscription was purchased at the Microsoft Store, it's not managed by an admin so the button won't appear.

**Comment by dbakepner** [comment]
Thanks for replying so quickly.  I don’t know where to turn to activate my Visual Studio for which I have an order receipt from 6 June 23 for Visual Studio Professional Subscription (Renewal), as it does not show up when I log in with my work email, only a devops subscription the previous subscription of VS as expired.  The activation code from the order doesn’t even work, saying it’s incorrect.  There’s no way to log in to that renewed subscription.
I guess that’s not your department probably.

Regards,



<http://www.danakepner.com>[cid:DanaKepnerLogo_92c387e7-880e-44d7-9efe-956bf6242ec0.jpg]<http://www.danakepner.com/>


Scott Saari
Database Engineer
Dana Kepner Company, LLC
***@***.******@***.***>
| Denver, CO 80204
Office: 303.623.6161
Direct: 303.446.3978
Mobile: 602.230.7824

**Comment by evanwindom** [comment]
@dbakepner Hi Scott, 
The most frequent cause I've seen for that is that the renewal subscription isn't the same type as the original subscription, or the customer has purchased the renewal subscription when they didn't have an original subscription or the original had expired long enough ago that it wasn't eligible for renewal at the discounted price.  I suggest reaching out to our support team who can investigate that for you.  

https://visualstudio.microsoft.com/subscriptions/support/

**Comment by evanwindom** [comment]
@dbakepner Hi Scott. Is there any news on this?  Have you been able to get this resolved?

**Comment by dbakepner** [comment]
Very kind of you to ask.  The underlying problem was that the renewed visual studio subscription was not showing up.
I had the impression that the subscription would update itself on the visual studio portal, but it doesn't until you scroll down and click the Activate Retail Subscription button and enter the new product key.  It would have been nice if that instruction were included in the receipt email for the subscription renewal.




<http://www.danakepner.com>[cid:DanaKepnerLogo_92c387e7-880e-44d7-9efe-956bf6242ec0.jpg]<http://www.danakepner.com/>


Scott Saari
Database Engineer
Dana Kepner Company, LLC
***@***.******@***.***>
| Denver, CO 80204
Office: 303.623.6161
Direct: 303.446.3978
Mobile: 602.230.7824













________________________________

**Comment by evanwindom** [comment]
@dbakepner I'm glad it's resolved.

**Comment by evanwindom** [comment]
#please-close
