### ISSUE TITLE
Mention hard limit on total number of concurrent data breakpoints

### ISSUE THREAD

**Issue by Rageking8** [MicrosoftDocs/visualstudio-docs#9648]
In the data breakpoint (DP) section of the following article, it would be nice to mention the hard limit of 4 concurrently enabled data breakpoints due to the underlying hardware limitations.

AFAICT there does not seem to be any mention of the above in any docs I could find (If the limit information is already stated elsewhere, feel free to close this issue directly).

Since the DP section already contains some information regarding hardware/architecture specific limitations such as the maximum watch size (in bytes), it should be ok to add the DP quantity limit information in too.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9da322b-ed73-b3e4-6fa0-e0ebd4a7475c
* Version Independent ID: dc0dbf50-e2e8-8dfc-0f0f-f0a86d31ea73
* Content: [Use breakpoints in the debugger - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/using-breakpoints?view=vs-2022)
* Content Source: [docs/debugger/using-breakpoints.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/using-breakpoints.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@Rageking8 Appreciate the feedback! I'll ask about that and get the article updated.

**Comment by Mikejo5000** [comment]
Updated article. Update should be live by EOD on 12/6/23 PST.
