### ISSUE TITLE
Offline Required

### ISSUE THREAD

**Issue by yhjhoo** [MicrosoftDocs/visualstudio-docs#965]
Please provide offline installer.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5cd139e6-bbd6-4c1a-1b40-5abd63031a9a
* Version Independent ID: bc91c619-c340-40e6-9c55-8c496eb24da5
* Content: [Create an Offline Installer for Visual Studio for Mac - Visual Studio for Mac](https://docs.microsoft.com/en-us/visualstudio/mac/create-offline-installer)
* Content Source: [mac/create-offline-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/mac/create-offline-installer.md)
* Service: **unspecified**
* Product: **visual-studio-mac**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by TerryGLee** [comment]
@asb3993 Would you please field this request? It's for Visual Studio for Mac.

**Comment by asb3993** [comment]
We understand this is a feature you care about, but unfortunately we have no additional information at this time.

To ensure your feedback is heard, please use the [Give product feedback](https://developercommunity.visualstudio.com/spaces/41/index.html) button. There you can vote for features and participate in the discussion on when and how they are implemented. Alternatively, you can also upvote this [uservoice](https://visualstudio.uservoice.com/forums/563332-visual-studio-for-mac/suggestions/33816103-visual-studio-for-mac-missing-offline-installer) query.
