### ISSUE TITLE
Build from source instructions could be more noticeable or larger

### ISSUE THREAD

**Issue by DrSharky** [MicrosoftDocs/visualstudio-docs#9654]
I build the Unreal Engine from source code, and I've been troubleshooting the Visual Studio integration plugin for Unreal Engine for a few days now. I have obviously skimmed the page several times, and missed one key piece of information:

> If your engine code is built from source or if your project isn't compatible with Unreal Engine Marketplace plugins, install the plugin manually by cloning and installing the plugin from the [GitHub vc-ue-extensions repo](https://aka.ms/vc-ue-extensions)

This is definitely my fault for not reading carefully. However, I feel like this could be made more obvious, as there are plenty of people who build from source, and it is a *totally* different set of steps to install it. After I figured it out, it worked. But before that, I was getting an error that it was not installed, yet I thought I had installed it correctly from following the instructions for the marketplace version of the Unreal Engine. Secondly, when opening the Unreal Engine editor, and checking the plugins that are installed, there are 3 plugins that show up now that are all very similarly named, and that confused me. When opening the plugins menu in Unreal Editor, I see "Visual Studio Code Integration", "Visual Studio Integration", and "Visual Studio Integration Tools".
The first plugin I didn't realize refers to Visual Studio Code, the program. For a while I assumed it just meant "Code Integration" via Visual Studio. Once I had installed the plugin from source, I disabled "Visual Studio Integration", thinking that I didn't need it, since I thought it was the same thing as "Visual Studio Integration Tools". Then I realized I need both. So enabling "Visual Studio Integration" and "Visual Studio Integration Tools" is required. Arriving at this conclusion took me longer than it should have.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a6433ff1-51c3-2079-1212-4914e94efe3c
* Version Independent ID: a6433ff1-51c3-2079-1212-4914e94efe3c
* Content: [Install Visual Studio Tools for Unreal Engine](https://learn.microsoft.com/en-us/visualstudio/gamedev/unreal/get-started/vs-tools-unreal-install)
* Content Source: [gamedev/unreal/get-started/vs-tools-unreal-install.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/gamedev/unreal/get-started/vs-tools-unreal-install.md)
* Product: **visual-studio**
* Technology: **vs-unreal-engine-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by WilliamAntonRohm** [comment]
@DrSharky -- thank you for your well-considered feedback.

@TylerMSFT -- please look into this issue.

**Comment by TylerMSFT** [comment]
@DrSharky, thank you for this feedback. I will add this to my list of things to do.

**Comment by TylerMSFT** [comment]
Adding some activity to keep the bot at bay.

**Comment by TylerMSFT** [comment]
I have moved this issue to an internal work item tracking system because we are moving away from using GitHub issues to track C++ doc work.
