### ISSUE TITLE
Python environment used unclear

### ISSUE THREAD

**Issue by dariopnc** [MicrosoftDocs/visualstudio-docs#9661]
[Enter feedback here]
This page does not explain which Python environment is used when launching a command where `TargetType` is `script`. I expect it to be the active Python environment but it isn't specified

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 25718b21-cfe7-6f58-c610-c6aa0c0e4e53
* Version Independent ID: 73f90583-c024-e9bf-fe5c-432dfbdb034d
* Content: [Define custom menu commands for Python projects - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/defining-custom-python-project-commands?view=vs-2022)
* Content Source: [docs/python/defining-custom-python-project-commands.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/defining-custom-python-project-commands.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
Thanks for the suggestion and your intuition is correct -the script will run in the activated project environment. I added a note to clarify this in the docs. #please-close
