### ISSUE TITLE
no information on where to configure linting

### ISSUE THREAD

**Issue by gavinreid2004** [MicrosoftDocs/visualstudio-docs#9664]
I have a solution that constantly reports 205 linting errors in node_modules
I think these are in the solution root folder. 
The solution contains several web projects but this page does not have any reference to customising this option. I know I can add an .eslintrc.json file, but should that be in every project, in the root of the solution, in the .vs. I am loosing hours to this annoying invalid errors reported by Visual studio.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6ff6ceff-02c9-e161-0971-bd0a60e9470a
* Version Independent ID: 6ff6ceff-02c9-e161-0971-bd0a60e9470a
* Content: [Linting JavaScript in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/linting-javascript?view=vs-2022)
* Content Source: [docs/javascript/linting-javascript.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/linting-javascript.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@gavinreid2004 -- Gavin, thank you for your feedback.  This repo is solely for documentation issues, and this seems product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @Mikejo5000 for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by gavinreid2004** [comment]
@WilliamAntonRohm I raised it as a documentation problem as I could not identify where to customise the linting in Visual Studio from this page about configuring linting in visual studio. In particular how or if there is a solution vs project distinction in configuration. How do the eslintrc configuration files fit in with the visual tooling or are the various eslintrc file types incompatible? I outlined my issue to illustrate why I was asking for an expansion to the documentation.

**Comment by WilliamAntonRohm** [comment]
@gavinreid2004 -- Gavin, thank you for your detailed follow-up.

@Mikejo5000 -- Mike, please look into this issue.

**Comment by Mikejo5000** [comment]
@gavinreid2004 Thanks for the feedback! I'm asking about this.

**Comment by Mikejo5000** [comment]
@gavinreid2004 Per-project support for eslint is available, and is pretty standard eslint configuration. The recommendation from the product team is to read through this section of eslint docs:
https://eslint.org/docs/latest/use/configure/configuration-files#using-configuration-files

**Comment by Mikejo5000** [comment]
Closing, since I don't think we need a doc update for this. We have a link to the official eslint doc already.
