### ISSUE TITLE
I can't get the help I need.

### ISSUE THREAD

**Issue by MarlonCarbone** [MicrosoftDocs/visualstudio-docs#9666]
I'm trying to turn on auto closing tags.  NOTHING gives me this info for VS community 2022.  EVERYTHING starts with CS Code.  I've been searching for this setting for more than 2 hours.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5ea14445-5f1e-6781-af3b-47447e3c996d
* Version Independent ID: 8c89b91c-887a-1f83-6287-b8ebcd2d3918
* Content: [Options, Text Editor, HTML (Web Forms), Formatting - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/options-text-editor-html-formatting?view=vs-2022)
* Content Source: [docs/ide/reference/options-text-editor-html-formatting.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/options-text-editor-html-formatting.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@MarlonCarbone -- Marlon, please use this option:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/27738025/967ad130-5447-4b6e-8355-8bca60cbed05)

I was able to find this setting by searching for "closing" in the Visual Studio search box.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by MarlonCarbone** [comment]
That is set and it does not work.



Thank you,



Marlon Carbone

Implementation Specialist

P: 405-735-5144 option 2

F: 405-237-3112

MyPatientLink.com<http://www.mypatientlink.com/>



[1460401626187_Signature.png]

NOTICE: This e-mail message and all attachments transmitted with it may contain legally privileged and confidential information intended solely for the use of the addressee. If the reader of this message is not the intended recipient, you are hereby notified that any reading, dissemination, distribution, copying, or other use of this message or its attachments is strictly prohibited. If you have received this message in error, please notify the sender immediately by telephone at (405) 735-5144 or by electronic mail and delete this message and all copies and backups thereof.

________________________________

**Comment by WilliamAntonRohm** [comment]
@MarlonCarbone -- Marlon, if you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
