### ISSUE TITLE
Download PDF

### ISSUE THREAD

**Issue by shahrouz9** [MicrosoftDocs/visualstudio-docs#967]
Download PDF link at the bottom left is not working. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5416573b-dd99-f3c9-1707-32fb38023788
* Version Independent ID: 45ebd856-0161-4ea2-2833-d1ec165ebc97
* Content: [Visual Studio testing tools - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/test/improve-code-quality#feedback)
* Content Source: [docs/test/improve-code-quality.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/test/improve-code-quality.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@shahrouz9 Thanks for reporting that the PDF link is broken. We are looking into it.

**Comment by gewarren** [comment]
The PDF is working now. Closing the issue. Thanks again for reporting it.
