### ISSUE TITLE
Typo under `Modify the event handler`

### ISSUE THREAD

**Issue by jentamm** [MicrosoftDocs/visualstudio-docs#9673]
I think there's a typo. Under Modify the event handler, Step 1 asks us to open MainPage.xaml.cs. I believe this should be MainWindow.xaml.cs

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dfd5474-49ef-be76-4267-4b1f72692865
* Version Independent ID: 6dfd5474-49ef-be76-4267-4b1f72692865
* Content: [Tutorial: Create Windows App SDK Apps with Visual Studio & C#](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-wasdk?view=vs-2022)
* Content Source: [docs/get-started/csharp/tutorial-wasdk.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-wasdk.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
Duplicate of #9672
