### ISSUE TITLE
Tutorial crashed

### ISSUE THREAD

**Issue by RiKelleher** [MicrosoftDocs/visualstudio-docs#9679]
When going through the tutorial steps and pressing Create to configure the project it gave error "Exception from HRESULT: 0x80042001. Every time I retry it gives the same error and never finishes the creation process.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a12b2f91-753b-4771-85c2-75808137088a
* Version Independent ID: a047d08b-9306-8f1e-2d69-a932417f97b2
* Content: [Create your first document-level customization for Excel](https://learn.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-document-level-customization-for-excel?view=vs-2022&tabs=csharp)
* Content Source: [docs/vsto/walkthrough-creating-your-first-document-level-customization-for-excel.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/walkthrough-creating-your-first-document-level-customization-for-excel.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@RiKelleher please follow https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022 to send feedback to the Visual Studio team on this issue.
