### ISSUE TITLE
Jupyter Notebook 

### ISSUE THREAD

**Issue by ShivaKumar-Jadipalli** [MicrosoftDocs/visualstudio-docs#9680]
Does visual studio IDE 2022 supports jupyter notebook , I am a machine learning researcher , I have been using visual studio code for a long time but I want to improve my coding speed so I am thinking of using visual studio ide but I am unable to find " how to use jupyter notebook here " please help me to sort this out

**Comment by WilliamAntonRohm** [comment]
@ShivaKumar-Jadipalli -- Shivakumar, thank you for your question.  It appears that Jupyter notebooks are supported by Visual Studio Code (VS Code), but not by Visual Studio itself.

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
