### ISSUE TITLE
Why dont you give simple and coherent instructions??!!??

### ISSUE THREAD

**Issue by AvatharBehemoth** [MicrosoftDocs/visualstudio-docs#9686]
[Enter feedback here]
I HAVE NO IDEA WHAT YOU MEAN. I AM BUILDING A C++ PROJECT AND THESE INSTRUCTIONS DO NOT MAKE ANY SENSE!!!!!!!!!!!
HOW DO I CHANGE THE OUTPUT DIRECTORY? 

WHY DOES VS2022 CREATE A REDUNDANT SUB DIRECTORY?
WHAT IS THE STARTING DIRECTORY FOR VS2022??!!!?
IT CANT OPEN "shaders/frag.spv" and "shaders/vert.spv". WHY??!!?? WHY ARE YOU FUCKING UP YOUR OWN SYSTEM??!!? WHY CANT I CHECK WHY I CANT OPEN THE GODDAMNED FILES?? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4938a042-e5db-4f9c-2288-930b904e888c
* Version Independent ID: 6db1e386-22e4-4940-cc2c-bdeaa5883299
* Content: [Change the build output directory - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-the-build-output-directory?view=vs-2022)
* Content Source: [docs/ide/how-to-change-the-build-output-directory.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-the-build-output-directory.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-compile**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by AvatharBehemoth** [comment]
TURNS OUT THE STARTING DIRECTORY IS THE SUPERFLUOUS REDUNDANT DIRECTORY YOU SUDDENLY DECIDED TO ADD IN THE CREATION OF THE PROJECT??!!?? 
WHY IS THE .sln NOT IN THE SAME DIRECTORY AS THE .vcxproj .filters and .user files??!!??
I fixed my problem, but why did you do this??!!?? it makes no sense!

**Comment by WilliamAntonRohm** [comment]
@AvatharBehemoth -- please add this issue here:
- [Suggest a Feature](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature)
