### ISSUE TITLE
Line 1 of the "View UE Blueprints in Visual Studio" refers to a different file "LyraGamplayAbility.h"

### ISSUE THREAD

**Issue by Holosim** [MicrosoftDocs/visualstudio-docs#9688]
Is taht supposed to be pointing to LyraCharacter.h location?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 32c8fa86-3234-362e-c4a0-27d26056596f
* Version Independent ID: 32c8fa86-3234-362e-c4a0-27d26056596f
* Content: [Quickstart: Visual Studio Tools for Unreal Engine](https://learn.microsoft.com/en-us/visualstudio/gamedev/unreal/get-started/vs-tools-unreal-quickstart)
* Content Source: [gamedev/unreal/get-started/vs-tools-unreal-quickstart.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/gamedev/unreal/get-started/vs-tools-unreal-quickstart.md)
* Product: **visual-studio**
* Technology: **vs-unreal-engine-tools**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **TWhitney**

**Comment by TylerMSFT** [comment]
Thank you for taking the time to point that out! Fixed. 
The fix should be live by tomorrow afternoon.

Really appreciate you taking the time to log this issue so that others won't run into this in the future.

**Comment by WilliamAntonRohm** [comment]
#please-close
