### ISSUE TITLE
how do i suggest a feature??!!??

### ISSUE THREAD

**Issue by AvatharBehemoth** [MicrosoftDocs/visualstudio-docs#9692]
[Enter feedback here]
where is the option to suggest a feature??!!!?? 
doesnt anyone do ux?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 785f2716-1297-f343-24fa-705a42c2ff64
* Version Independent ID: 732cf4ab-6056-31a6-abda-c63a37f90e45
* Content: [Suggest a feature - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/suggest-a-feature?view=vs-2022)
* Content Source: [docs/ide/suggest-a-feature.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/suggest-a-feature.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by WilliamAntonRohm** [comment]
@AvatharBehemoth -- thank you for your followup.  That was my typo, sorry.  These are the correct links:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
