### ISSUE TITLE
Incorrect sign-posting to CSP price list

### ISSUE THREAD

**Issue by Priscilla-C** [MicrosoftDocs/visualstudio-docs#9694]
https://learn.microsoft.com/en-gb/visualstudio/subscriptions/vscloud-csp#view-visual-studio-pricing-for-csp-partners
The following information is incorrect: 
To view Visual Studio pricing for CSP partners, log into the [Partner Center](https://partnercenter.microsoft.com/). Choose Pricing and offers from the left nav. Choose the current month pricing file under usage-based services in the upper right. After the Excel spreadsheet downloads, go to the Azure Price List sheet, and filter the Meter Category column to Visual Studio.

It is found in Pricing > Current month > Azure plan pricing > Azure plan consumption pricing. 

Select applicable country to download the file. After the spreadsheet downloads, go to the Azure Consumption sheet, and filter the ProductTitle to Visual Studio Subscription

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f413cb5d-d6c4-2036-62e2-0af9b041ade3
* Version Independent ID: 7c96f714-fb4f-a578-546e-2cfba9366d76
* Content: [Visual Studio cloud subscription purchasing for CSPs](https://learn.microsoft.com/en-gb/visualstudio/subscriptions/vscloud-csp)
* Content Source: [subscriptions/vscloud-csp.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vscloud-csp.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@Priscilla-C  - Thanks for bringing this to my attention.  Once I can verify the steps you've provided, I'll update the article.  Thanks again!
