### ISSUE TITLE
Please correct description of --wait

### ISSUE THREAD

**Issue by cowlinator** [MicrosoftDocs/visualstudio-docs#970]
The "Visual Studio Team" at https://developercommunity.visualstudio.com/comments/26893/view.html stated that the description for --wait is incorrect:  "The Visual Studio team has determined that this issue is not a bug. The --wait option documentation may be misleading but it is for a different purpose.  When running from CMD or PS shell please use the call command which will wait for the process to wait."  Please update the description for --wait to describe what it actually does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5e97b834-fa82-6aa0-5913-4d5a8ed23366
* Version Independent ID: e988e3ea-8565-ca88-6ade-ab67425a51ae
* Content: [Use command-line parameters to install Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio)
* Content Source: [docs/install/use-command-line-parameters-to-install-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/use-command-line-parameters-to-install-visual-studio.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@cowlinator Thanks for your feedback; we'll investigate and report back.

**Comment by TerryGLee** [comment]
@tydunkel Can you verify, please?

**Comment by tydunkel** [comment]
@cowlinator Thank you for the feedback! The `--wait` command description is correct, the `vs_<SKU>.exe` process will wait to close until after the install is complete. However, different command utilities behave differently when given commands. Batch scripts will wait for a process to quit before continuing, so `--wait` will block until the install completes. Powershell scripts **will not** block for processes to exit, so `--wait` alone is not enough to block a Powershell script while the install completes.

e.g. To block a Powershell script from continuing:
```ps
$returnCode = Start-Process -FilePath vs_community.exe -ArgumentList "--installPath", "C:\VS", "--passive", "--wait" -Wait -PassThru
```
or
```ps
$startInfo = New-Object System.Diagnostics.ProcessStartInfo
$startInfo.FileName = "vs_enterprise.exe"
$startInfo.Arguments = "--all --quiet --wait" 
$process = New-Object System.Diagnostics.Process
$process.StartInfo = $startInfo
$process.Start() 
$process.WaitForExit()
```
We should probably add these examples to [Command-line parameter examples for Visual Studio 2017 installation](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2017).

**Comment by cowlinator** [comment]
Thank you for the response.  
I agree that additional examples would be very helpful.

**Comment by tydunkel** [comment]
@TerryGLee FYI - we will work on adding more examples to the docs for this since it is a common point of confusion.

**Comment by TerryGLee** [comment]
@tydunkel I am assigning the content updates to the April sprint; FYI.

**Comment by TerryGLee** [comment]
@cowlinator As previously stated, the description of the --wait parameter is correct, but we have updated the "[Using --wait](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2019#using---wait)" section of the [Command-line parameter examples](https://docs.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples) page to include PowerShell examples. We'll close this issue now; however, you can still add comments to it, should you wish. 

Thanks for helping us to improve our documentation!
