### ISSUE TITLE
Code Gives Warning

### ISSUE THREAD

**Issue by Twerps** [MicrosoftDocs/visualstudio-docs#9700]
The code line 

Label iconLabel = control as Label;

gives the warning CS8600 - Converting null literal or possible null value to non-nullable type.

It requires ? to remove warning

Label? iconLabel = control as Label;
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9577c259-7ee7-eab5-bdef-3ae87d93ff80
* Version Independent ID: 9577c259-7ee7-eab5-bdef-3ae87d93ff80
* Content: [Tutorial: Add icons to the matching game - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-match-game-icons?view=vs-2022&tabs=csharp)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-match-game-icons.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-match-game-icons.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@Twerps -- thank you for your well-researched feedback.

@anandmeg -- please review this change in [private PR 11988](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/11988).
