### ISSUE TITLE
Incorrect documentation for Go to Type functionality

### ISSUE THREAD

**Issue by lloydw-sportsbet** [MicrosoftDocs/visualstudio-docs#9710]
The view described does not match the current Visual Studio release which displays the large slow and useless UI instead of the small GoToType Window

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2b5f9224-0fef-e5c9-f0ad-789ed940d79d
* Version Independent ID: 494a3e3a-074f-b4ab-132b-adc4c1482044
* Content: [Go to file, go to symbol, go to line - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/go-to?view=vs-2022)
* Content Source: [docs/ide/go-to.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/go-to.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@lloydw-sportsbet 
You might be interested in the following.
To enable or disable this feature, go to Tools > Options > Environment > Preview Features > New Visual Studio Search experience.
