### ISSUE TITLE
Please provide a link to accompany a statement "wherever a Condition attribute is allowed"

### ISSUE THREAD

**Issue by gh-andre** [MicrosoftDocs/visualstudio-docs#9713]
At the top of the page it says:

> MSBuild supports a specific set of conditions that can be applied wherever a Condition attribute is allowed.

However, finding out which elements actually support `Condition` requires visiting each element's schema page. It would be helpful if on the page describing conditions, a list of elements that allow conditions would be included, with links to their schema documentation pages.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 378f740b-d567-135e-0de9-a3cbd311b2dd
* Version Independent ID: ff69814c-8600-f24a-530e-9a219bd6d8de
* Content: [MSBuild Conditions - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-conditions?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-conditions.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-conditions.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@gh-andre 
Thanks, I like this idea.
