### ISSUE TITLE
Formatting DOES NOT FUNCTION

### ISSUE THREAD

**Issue by NeilWP** [MicrosoftDocs/visualstudio-docs#9721]
Following the instruction formatting a python document  using Edit Advanced Format Document  / Format Selection and the short cuts fails.
Checked formatting tools existed and tried all three which were installed.
Pretty basic  expectation that  it would would work rather than manually going through the document
Pretty poo that it fails
 
#disappointment 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 67031305-2f97-3aa4-ced1-b66092dd4d41
* Version Independent ID: 37603282-7242-21de-fb56-9f1bbae9dc43
* Content: [Reformat your python code in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/formatting-python-code?view=vs-2022)
* Content Source: [docs/python/formatting-python-code.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/formatting-python-code.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by WilliamAntonRohm** [comment]
@NeilWP -- Neil, thank you for your feedback.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
