### ISSUE TITLE
Visual Studio Startup options too limited

### ISSUE THREAD

**Issue by stevehuizenga** [MicrosoftDocs/visualstudio-docs#9722]
Yes, it's great to select what to open when VS starts, but I'm really getting tired of it automatically building at that time.  When my solution loads and I start working, the fact that it's doing a build interferes with that process.  For example, a pop-up will show up and steal my focus from what I'm doing.  There is no advantage to me for a build to happen at that time.  If code was changed and I wanted to build it, I did that before I closed VS and it's wasting my time and interfering with my work when it builds when I reopen VS or load a solution.  I've searched and searched and there doesn't seem to be a way to disable this annoying behavior that blocks my progress and there should be... or just take it out... I don't see why it would help anyone and it's so easy to start a build when you want one.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 38a2bfea-c771-a183-ed02-d2338516a223
* Version Independent ID: b0e5f18b-29bb-858c-6b04-b4e72240f777
* Content: [Change the startup experience - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/customizing-the-start-page-for-visual-studio?view=vs-2022)
* Content Source: [docs/ide/customizing-the-start-page-for-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/customizing-the-start-page-for-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@stevehuizenga -- Steve, thank you for your solid feedback.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
