### ISSUE TITLE
Is 'either' extra here?

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/visualstudio-docs#9728]
Hello,

kindly check if 'either' is redundant in this string: "You can export an installation configuration file from **either** a previously installed instance of Visual Studio."

If not, the sentence would need the second option also.

Kind regards,
Anne H., CQ

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 517f011b-d4f4-b1d3-3212-6725204a71e3
* Version Independent ID: 77f048ce-d750-9c9d-f33a-5ec4f4a9965a
* Content: [Import or export installation configurations](https://learn.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2022)
* Content Source: [docs/install/import-export-installation-configurations.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/import-export-installation-configurations.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@QueryCoordinator, thanks for your feedback. We've updated the doc. The changes should be live later today.
Thanks!
