### ISSUE TITLE
CodeTaskFactory is limited by the language version - RoslynCodeTaskFactory is not

### ISSUE THREAD

**Issue by tonyhallett** [MicrosoftDocs/visualstudio-docs#9729]
The document suggests that RoslynCodeTaskFactory is only necessary for .NET Core.  This is most definitely not the case.

Given the following UsingTask
```
  <UsingTask TaskName="FailsCompilationTask" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll">
    <Task>
      <Code Type="Class">
        using Microsoft.Build.Framework;
        public class FailsCompilationTask : Microsoft.Build.Utilities.Task
        {
          public bool FailsCompilation { get; set; } = true;

          public override bool Execute()
          {
            Log.LogMessage(MessageImportance.High, "Works with RoslynCodeTaskFactory");
            return true;
          }
        }
      </Code>
    </Task>
  </UsingTask>
```

<img width="353" alt="image" src="https://github.com/MicrosoftDocs/visualstudio-docs/assets/11292998/3548c97c-fb63-4fc4-b50a-807067b5e1cc">

You can see that the compilation error is the initializer.

C# version 6.0
Released July, 2015
Version 6.0, released with Visual Studio 2015, released many smaller features that made C# programming more productive. Here are some of them:
[Auto-property initializers](https://learn.microsoft.com/en-us/dotnet/csharp/properties)

Switch to RoslynCodeFactory and no such error.

CodeTaskFactory uses CodeDomProvider https://github.com/dotnet/msbuild/blob/221fd2e8790a22ead513eb71630557efc02060e2/src/Tasks/CodeTaskFactory.cs#L805
which uses csc.exe for C#
( follow through if desired https://referencesource.microsoft.com/#System/compmod/microsoft/csharp/csharpcodeprovider.cs,3555 )

RoslynCodeFactory uses its own csc.exe.  Which uses the internal Microsoft.CodeAnalysis.CSharp.CSharpCompiler

The docs should state that CodeTaskFactory is limited to C#4 and to use RoslynCodeTaskFactory if using MSBuild >= 15.8.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d2edce4-67ce-e93c-269e-e4200895a1b9
* Version Independent ID: 4af4b53f-7103-e8b8-996f-79fbc71b83b6
* Content: [MSBuild Inline Tasks - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-inline-tasks?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-inline-tasks.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-inline-tasks.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@tonyhallett -- Tony, thank you for your well-researched feedback.

@ghogen -- Gordon, please look into this issue.

**Comment by ghogen** [comment]
@tonyhallett 
Interesting, thanks, I'll investigate and update as appropriate.
