### ISSUE TITLE
What is the meaning of 'Table' here?

### ISSUE THREAD

**Issue by QueryCoordinator** [MicrosoftDocs/visualstudio-docs#9733]
Hello,

would you kindly check this string: "**Table** Use this dropdown listbox to select a table within the dataset that you want to visualize."

What is the meaning of "Table" in the beginning of this string? Or is there a formatting issue here?

Kind regards,
Anne H., QC

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7e21bbf4-ccbe-859e-5d2b-177316c2dd1a
* Version Independent ID: b434beff-75a3-95b9-3c31-7209c8489476
* Content: [Dataset Visualizer Dialog Box - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/dataset-visualizer-dialog-box?view=vs-2019)
* Content Source: [docs/debugger/dataset-visualizer-dialog-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/dataset-visualizer-dialog-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@QueryCoordinator -- Anne, thank you for your question.  The first word **Table** is in the first cell of a two-column row, and it refers to the UI element with that name in the Dataset Visualizer Dialog Box itself.  The second cell contains the description of that **Table** UI element.

**Comment by QueryCoordinator** [comment]
Hi @WilliamAntonRohm 

Thank you for your reply. This is what I thought also, but since there is no table, no lines around, it can be a bit confusing:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/124143083/6b236240-3e99-4376-8640-d81ad53c3f2a)
