### ISSUE TITLE
Visualizing memory pointers

### ISSUE THREAD

**Issue by ElectricErger** [MicrosoftDocs/visualstudio-docs#9734]
Some tools only output pointers to memory (e.g., heap snapshots, specifically the Sparse Arrays Insight). I think it would be helpful to document that you can view the contents of an object given its memory pointer by adding `{CLR}@<memoryAddress>` (where `<memoryAddress>` is the pointer to memory ex., 0x1F00112233) to a Watch tool.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb85208e-4337-ea43-ec0c-6ca67c4c5fc3
* Version Independent ID: 0d98280d-8c1c-c729-14c7-0717202e3f22
* Content: [View memory for variables in the debugger - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/debugger/memory-windows?view=vs-2022)
* Content Source: [docs/debugger/memory-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/debugger/memory-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-debug**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by ElectricErger** [comment]
Sorry if I'm doing this wrong y'all (first timer using GitHub docs). From the metadata I assume that it's clear that my feedback is about the page specified there.

**Comment by WilliamAntonRohm** [comment]
@ElectricErger -- thank you for your thoughtful feedback.

@Mikejo5000 -- please look into this issue.

**Comment by Mikejo5000** [comment]
@ElectricErger Thanks for the feedback! That seems like a good tip. I will plan to update the article.

**Comment by Mikejo5000** [comment]
@ElectricErger I ran a few quick tests. Is your intent here to view the contents of the object in the Memory window or the Watch window? (You mention the Watch tool).

**Comment by Mikejo5000** [comment]
I'm adding a new section to this article, which should be live by noon PST on 12/01/23. Let me know if you have any comments, plus see my earlier question. Thanks!

**Comment by ElectricErger** [comment]
Looks wonderful @Mikejo5000. I was personally looking for the Memory window, but once I found out that I could use that same address in the Watch window, that was even more ideal. I don't think there's an ideal way to loosely document this symbol-memory map trick that can be used in so many different places without having it being in some greater tutorial.
