### ISSUE TITLE
Missing just one critical piece of information.

### ISSUE THREAD

**Issue by thomb1** [MicrosoftDocs/visualstudio-docs#974]
This is an excellent writeup - oh but it leaves out what for me is the hardest part: It starts out exactly as it should:
Replace the product code with the GUID for the redistributable component.
But then... how does one determine the GUID for the redistrutable? There are 2 main ways this process fails - you've got the URL wrong, or you have the GUID wrong - and none of the write ups anywhere on Microsoft[dot]com tell you exactly how to determine these. Its like a conspiracy to make sure the priests retain the power over the congregation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d1385b1-f794-fec6-852f-0645e39872bd
* Version Independent ID: a2a295a9-6233-835b-f24f-fa11a2d36202
* Content: [How to: Create a Product Manifest - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/deployment/how-to-create-a-product-manifest)
* Content Source: [docs/deployment/how-to-create-a-product-manifest.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/deployment/how-to-create-a-product-manifest.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by thomb1** [comment]
This suggests the best approach would be to add the GUID/URL to the download page of any Microsoft redistributable - that's a lot of work just to set up a script that moves some files from point a to point b...
https://stackoverflow.com/questions/29937568/how-can-i-find-the-product-guid-of-an-installed-msi-setup

**Comment by Mikejo5000** [comment]
@thomb1 Thanks for the feedback! This does sound like arcane information. I'll inquire if there's an easier way.

**Comment by thomb1** [comment]
Just curious about the arcane comment why is it considered arcane?
You do a search on Bootstrap / clickonce and there’s thousands of folks out there with problems  of all sorts - either where vendors screwed up what this describes, or it’s a development problem  where I can’t find the proper information to fill out what this documentation describes.
In reality clickonce is SHOCKLY simple technology – its just a matter of moving files from a URL and searching a list (the registry) to find matchs on strings (GUID).
Simple documentation listing these exact values per distributable (or heck just provide the damn files) – that’s not on you btw - but I sure wish I could pass that to whomever it is on.

That would have prevented the vast majority  of these problems – its not esoteric at all – it’s absolutely fundamental to success.

**Comment by Mikejo5000** [comment]
Looking at the article, I would also assume that getting the GUID would not be so hard. That's what I meant.

This stack post shows how to get it programmatically:

https://stackoverflow.com/questions/502303/how-do-i-programmatically-get-the-guid-of-an-application-in-net2-0

But posting the GUID and URL with the downloadable sounds easier, though outside of my area of influence (which is docs).

**Comment by thomb1** [comment]
Gotcha!
And hope I didn’t come across as venting on you personally or even to your organization in general. I am responsible for all the documentation of our software and I know it’s a thankless job.  I appreciate you replying to me; I know it helps when customer point things out to me even when I don’t necessarily like hearing it ☺

So please take my comments as simply trying to help!
Regards,
Thom


Thom C. Blackwell,  VP Technical Services
Boston Software Systems, Inc.
Phone: 866.653.5105 x807
Mobile: 508.423.8463
Fax: 508.319.3015
www.bostonsoftwaresystems.com<http://www.bostonsoftwaresystems.com/>

The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.

**Comment by Mikejo5000** [comment]
Sure, no problem. I'm asking about it. At the moment, I don't have any contacts that could get that kind of info added to the download pages. There may also be a reason that info is not included, though I'm not sure what reason that might be.

**Comment by Mikejo5000** [comment]
@thomb1 Thanks for your feedback; we appreciate it. To make sure that this is logged in the right place, please use the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool to report the issue. When you do this, your report becomes part of the work items that are listed in the in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html), which allows you to engage directly with the engineering team while they address and fix the problem.
