### ISSUE TITLE
Visual Studio Spellchecker: Ignore vs. Add

### ISSUE THREAD

**Issue by ericmutta** [MicrosoftDocs/visualstudio-docs#9747]
It's really nice to see Visual Studio finally get a spell checker! I am filing this here because I don't know where else to put the feedback:

First, a spell checker for programmers really should know about words like **enum** out of the box. Right now, it seems to think I should replace **enum** with **enemas** (which is both funny and disturbing):

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/20465797/a8083ce1-62de-4943-9aa3-e082b3de6fdd)

Second, I think the wording for **ignore** should be changed to something like **Add to dictionary**. Consider the following UI from Microsoft Word (which is probably where all of us first encountered spell checking):

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/20465797/b0d5cb37-7ec3-471e-a1b2-8a8fc29a6d7c)

...in Microsoft Word, **ignore** is different from **add**. In the VS spell checker, **ignore** adds an entry to an exclusions file and thus behaves like **add** from Microsoft Word but with different terminology (which is confusing).

All in all, spell checking is a great addition and I look forward to seeing it improve...thanks to those who worked on it!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d60df15c-4e92-4780-93ce-366bd2f5ddc2
* Version Independent ID: d60df15c-4e92-4780-93ce-366bd2f5ddc2
* Content: [Learn about the Spell Checker - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/text-spell-checker?view=vs-2022)
* Content Source: [docs/ide/text-spell-checker.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/text-spell-checker.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@ericmutta -- Eric, thank you for your positive feedback!  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.

**Comment by ericmutta** [comment]
Many thanks for following up @WilliamAntonRohm! I have used the "suggest a feature" menu item and provided the [feedback here](https://developercommunity.visualstudio.com/t/Visual-Studio-Spellchecker:-Ignore-vs-A/10501433?port=1025&fsid=ff9c01de-e2db-4556-8cb7-1b4fc54b73b7) 👍

**Comment by ericmutta** [comment]
Hello @WilliamAntonRohm....I have always been somewhat reluctant to use `developercommunity.visualstudio.com` because in my experience, it is where feedback goes to die. Part of the problem I believe, is that it's a popularity contest over there, so legitimate problems get ignored if no one else votes on them. As a contributor here on GitHub it takes less than 24 hours for a human to respond (much like you did - which was awesome), but [over there](https://developercommunity.visualstudio.com/t/Visual-Studio-Spellchecker:-Ignore-vs-A/10501433?) it's been two weeks and only a bot responded.

In any case, here's another odd error from the Visual Studio spellchecker:

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/20465797/7bd3077c-c891-4755-a0bd-a20ea0290a3b)

For programmers, `destructuring` is very much a word and even the first Google search result points to MDN (a programmer's reference):

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/20465797/0eaed2ed-9536-4460-9e8f-0b20268bd757)
