### ISSUE TITLE
Clarity on scope of benefits

### ISSUE THREAD

**Issue by rrhkpmg** [MicrosoftDocs/visualstudio-docs#9750]
It's taken me a while to realise something that's perhaps obvious, so it might be worth clarifying in this page? I've got a VS subscription on domain A, with an alternate account on domain B. The B account has been added to a client's ADO organisation + project, and so when I log in to VS with the A account, I expected the list of ADO servers available to include the client's instance, hoping that VS would list ADO instances for both accounts. I can't login to VS directly using the B account, because I'm using a cloud-hosted box (for D365 F&O development), and the B domain is restricted to corporate devices. I believe the answer is that we need the client to add account A directly to their ADO organisation: the _alternate account_ is getting the subscription benefits, but the _primary account_ isn't getting the _alternate account_ access/privileges.  I think the _Note_ about signin at my.visualstudio.com goes a tiny bit of the way to explaining this "non-reciprocal" relationship, but still would like it to be clear what does **& doesn't** happen by account association. Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8a5f5e2-2957-f296-5551-750ff9d0cff1
* Version Independent ID: 88a13bf8-eddc-3e72-0c97-93d7013854ac
* Content: [Use connected identities in Visual Studio subscriptions](https://learn.microsoft.com/en-us/visualstudio/subscriptions/use-connected-identities)
* Content Source: [subscriptions/use-connected-identities.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/use-connected-identities.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by WilliamAntonRohm** [comment]
@rrhkpmg -- thank you for your feedback.

@evanwindom -- please look into this issue.

**Comment by evanwindom** [comment]
@rrhkpmg Thank you for reaching out.  I would expect it to be exceedingly rare for a subscriptions admin to assign a subscription to one identity and then their Azure DevOps access to another.  I'm concerned that trying to explain the ramifications of such a niche situation could inject complexity into the document that would cause more confusion than it solves.

**Comment by rrhkpmg** [comment]
@evanwindom I'll let you folks make that call. It's a scenario I see for dozens of colleagues literally every day, and I've had multiple employers who only allow their domain accounts to authenticate on domain-joined machines, but concede it's only in the last five years that I've encountered so much cloud-hosted VM use, so I appreciate this experience may still fall into the category of "exceedingly rare" across the entire audience for this page. Would it be accurate to say that the benefits only flow in one direction?

**Comment by evanwindom** [comment]
@rrhkpmg Thanks for the feedback.  We'll keep an eye on this and see if others have the same question.  If they do, we'll revisit it.

**Comment by evanwindom** [comment]
#please-close

**Comment by evanwindom** [comment]
@WilliamAntonRohm Can you close this, please?

**Comment by WilliamAntonRohm** [comment]
#please-close
