### ISSUE TITLE
The image for the Find-Command box is older than I am

### ISSUE THREAD

**Issue by collinstevens** [MicrosoftDocs/visualstudio-docs#9753]
The image for the VS2022 Find-Command box in the documentation is older than I am.

https://learn.microsoft.com/en-us/visualstudio/ide/find-command-box?view=vs-2022

I've included the image here for posterity.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/19230602/150fd0e6-6f84-410a-8af1-2e63b53d0039)

For what it's worth, I was able to find the VS2022 version of this which is in a new location different from where the documentation states; it also looks slightly different, but you can still run finds and commands from it funnily enough.

It is still in the `Standard` toolbar's `Commands`, but it is under the `Edit` category and it has been renamed to `Go to Find Combo` from `Find`. The documentation says it is named `Find`, but that is a different button.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/19230602/fedb6024-b675-48a4-a664-510fd29f5a27)

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/19230602/7bc18256-d4c6-41bf-ba8c-46ced265b778)

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/19230602/14684a34-b09b-4806-a367-61269e1b61b6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d0b30872-8d41-43f9-8ad1-030324efc322
* Version Independent ID: 294bf85a-1e76-cb93-bed9-d97fd081e1f7
* Content: [Find-Command Box - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/find-command-box?view=vs-2022)
* Content Source: [docs/ide/find-command-box.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/find-command-box.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@collinstevens 
Yes, it looks like the image is pretty old. I'll see about getting this article updated soon.

**Comment by ghogen** [comment]
I have updates ready for this article. Thanks for the detailed instructions on how to find the new version of this toolbar item, it helped me quickly find it and update the article.
