### ISSUE TITLE
Incorrect cli flag

### ISSUE THREAD

**Issue by jakauppila** [MicrosoftDocs/visualstudio-docs#9758]
Under `Configure the contents of a layout` it states `--vsconfig to use a config file to specify the components that should be included in the layout.`, but I believe the flag is simply `--config` ?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ff556dcf-4de1-8483-702a-73699062be1f
* Version Independent ID: cba846ae-6af4-af49-b194-28b546169426
* Content: [Create a network-based installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/create-a-network-installation-of-visual-studio?view=vs-2022)
* Content Source: [docs/install/create-a-network-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/create-a-network-installation-of-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@jakauppila -- Jared, thank you for catching this.

@anandmeg -- Megha, please review [private PR 11919](https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/11919).
