### ISSUE TITLE
Dead Link in: "Visual Studio debugging samples"

### ISSUE THREAD

**Issue by michael-dwan** [MicrosoftDocs/visualstudio-docs#9768]
The [Visual Studio debugging samples]https://learn.microsoft.com/en-us/visualstudio/extensibility/debugger/visual-studio-debugging-samples?view=vs-2022) references a sample with the URL: [https://code.msdn.microsoft.com/Visual-Studio-Debug-Engine-c2e21c0e](https://code.msdn.microsoft.com/Visual-Studio-Debug-Engine-c2e21c0e) 

However, the link to the sample redirects to the main MSDN samples page, and searching for the sample there does not return any results.

I tried to dredge it up somewhere else, to provide more helpful information here, but, wasn't able to uncover anything.

Would it be possible to put the sample back up somewhere discoverable, and update the MSDN docs?

**Comment by j-martens** [comment]
#assign:@mikejo5000

**Comment by Mikejo5000** [comment]
@michael-dwan This might be a better link: https://github.com/microsoft/ConcordExtensibilitySamples

**Comment by Mikejo5000** [comment]
@gregg-miskelly Gregg, is this a good link for people to find sample for the native debug engine:
https://github.com/microsoft/ConcordExtensibilitySamples

**Comment by gregg-miskelly** [comment]
No, ConcordExtensibilitySamples is something else. The debug engine sample hasn't been maintained in a long time, but here is a copy: https://github.com/microsoftarchive/msdn-code-gallery-microsoft/tree/master/Visual%20Studio%20Product%20Team/Visual%20Studio%20Debug%20Engine%20Sample

**Comment by Mikejo5000** [comment]
Updated link should be live by EOD today, PST. Thanks, @gregg-miskelly !
