### ISSUE TITLE
Grammar or typo in the documentation

### ISSUE THREAD

**Issue by ldegrazia** [MicrosoftDocs/visualstudio-docs#9772]
Now that you've configured source control for your project, you can create the virtual environment the necessary Flask packages that the project requires.

Change to 
Now that you've configured source control for your project, you can create the virtual environment with the necessary Flask packages that the project requires.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7542d51c-4ba4-db5d-cd34-4517779684a8
* Version Independent ID: ef7b3a39-814e-9c56-c2e1-6611464aa650
* Content: [Learn Flask tutorial in Visual Studio step 1, Flask basics](https://learn.microsoft.com/en-us/visualstudio/python/learn-flask-visual-studio-step-01-project-solution?view=vs-2022)
* Content Source: [docs/python/learn-flask-visual-studio-step-01-project-solution.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/learn-flask-visual-studio-step-01-project-solution.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
Thanks for identifying and creating this bug report. This has been addressed in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/11856 #please-close
