### ISSUE TITLE
Missing CopyLocalLockFileAssemblies property make references DLLs be skipped from created package

### ISSUE THREAD

**Issue by Tasteful** [MicrosoftDocs/visualstudio-docs#9774]
If the `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` is omitted from the csproj the DLLs from the referenced packages will not be included in the nupkg.

This can be tested with example adding the System.Text.Json package `<PackageReference Include="System.Text.Json" Version="7.0.3" PrivateAssets="All" />` and after that check the output folder bin/debug/netstandard2.0 and the task-folder inside nupkg to ensure the referenced dlls are included.

Found this property in this answer https://stackoverflow.com/a/44763964

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6cf3ed7e-8425-d255-938b-7319e865fd9a
* Version Independent ID: 6cf3ed7e-8425-d255-938b-7319e865fd9a
* Content: [Create a custom task - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022)
* Content Source: [docs/msbuild/tutorial-custom-task-code-generation.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/tutorial-custom-task-code-generation.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@Tasteful 
That property is documented here: https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#copylocallockfileassemblies

Are you suggesting that this custom task project should also use this property?

**Comment by Tasteful** [comment]
Yes. It should help if it was included. If we see the https://learn.microsoft.com/en-us/visualstudio/msbuild/tutorial-custom-task-code-generation?view=vs-2022#mark-dependencies-as-private section it's described how to add reference to other packages, but if I do that and without the above property I got an runtime error that the reference package cant be found.

After adding the property the dll from reference package is included into the created nupkg for the task and task was working as it should.
