### ISSUE TITLE
Make .NET Core the default screenshot and update screenshots to include .NET 8

### ISSUE THREAD

**Issue by AngelosP** [MicrosoftDocs/visualstudio-docs#9780]
Hello there, just a routine 'update with the latest' request:

1. Let's make the scenario of changing the framework version of a .NET Core app the first thing, and .NET Framework app the second thing we show. Just flip the order of the two around.
2. Let's refresh the screenshots that show the .NET Core version to include .NET 8.

Thank you very much, and let me know if you need any help with the screenshots. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8aa305bd-12c4-689f-1398-bae83bde4ba4
* Version Independent ID: 67a2e7ec-f55e-80b9-dec0-054891f3861b
* Content: [Targeted .NET Frameworks - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/visual-studio-multi-targeting-overview?view=vs-2022#change-the-target-framework)
* Content Source: [docs/ide/visual-studio-multi-targeting-overview.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/visual-studio-multi-targeting-overview.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@AngelosP, thanks for the feedback! We've updated the doc, and changes should be live later today. Let us know if you have any additional feedback. Thanks!
