### ISSUE TITLE
Outdated and incorrect information

### ISSUE THREAD

**Issue by MrRWolf** [MicrosoftDocs/visualstudio-docs#9788]
The directories listed where imported snippets are stored references Visual Studio 2019 (%USERPROFILE%\Documents\Visual Studio 2019\Code Snippets\) for the Visual Studio 2022 version of the page.

The structure for Replacement Parameters is incorrect.  The <Declarations> element should be in the <Snippets> element.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c7c36c-84d9-9237-3d78-689e76d080f9
* Version Independent ID: 6584735a-e8db-429d-5427-687fc709e6f8
* Content: [Walkthrough: Create a code snippet in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2022)
* Content Source: [docs/ide/walkthrough-creating-a-code-snippet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/walkthrough-creating-a-code-snippet.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by MrRWolf** [comment]
> Replacement Parameters
After un-crossing my eyes , I realized that the example is correct 😖.  The <Declarations> element is at the same level as the <Code> element... but it would maybe help if the <CodeSnippet> element was shown in the example just for clarity.

Thanks

**Comment by Mikejo5000** [comment]
Updating article to put the VS 2022 paths first, and to remove VS 2022 from the VS 2019 view. Fix should be live by EOD PST, today.
