### ISSUE TITLE
I dont understand it, 

### ISSUE THREAD

**Issue by syedrashid47** [MicrosoftDocs/visualstudio-docs#979]
what would be the reason to not give me a straight forward iso, don't give me BS about how you have saved me from downloading a few Gb's of data, 
as a developer we need our freedom, What to install when to install, and when to modify without being linked to Internet, 
Give me a straign forward, TRUE answer , Why?????

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 228076d1-94bf-c502-c018-08f7c0faf377
* Version Independent ID: c64a5cd5-6236-4192-2bfc-923aa20c94da
* Content: [Create an Offline Installation of Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/install/create-an-offline-installation-of-visual-studio)
* Content Source: [docs/install/create-an-offline-installation-of-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/install/create-an-offline-installation-of-visual-studio.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by TerryGLee** [comment]
@syedrashid47 We're sorry to hear that you're not happy with our installation experience. For the answers to your questions, please see @tedvz's response to [GitHub Issue #607 - This still needs an offline installer](https://github.com/MicrosoftDocs/visualstudio-docs/issues/607).

**Comment by TerryGLee** [comment]
Meanwhile, please know that this page is meant for documentation issues. The best way to leave us product-specific feedback is by using the [UserVoice](https://visualstudio.uservoice.com/forums/121579-visual-studio-ide) venue. For more information about that and other ways to provide feedback, see the [Talk to Us](https://docs.microsoft.com/visualstudio/ide/talk-to-us) page.
