### ISSUE TITLE
This page keeps refereeing to a Tools option that doesn't exist.

### ISSUE THREAD

**Issue by JayGrace** [MicrosoftDocs/visualstudio-docs#9791]
The Tools option mentioned doesn't exist in my version of Visual Studio Code and I've been looking everyone for an equivalent.  Grrr.

[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z (1 day ago)
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

[Copy] [OK]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2913896-b0f2-5f3c-d733-09fe5c4e86b1
* Version Independent ID: c997c373-c946-0f02-d4c2-0904e6aab42e
* Content: [Change themes, fonts, text, and contrast for accessibility](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@JayGrace -- Jay, thank you for your feedback.  This article only applies to Visual Studio, and not Visual Studio Code:

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/27738025/cf33df7c-ea5e-41f7-b1f8-787769d70e84)
