### ISSUE TITLE
No styles for collapsed regions / comments / outlining

### ISSUE THREAD

**Issue by ramoneeza** [MicrosoftDocs/visualstudio-docs#9795]
Although the list of possible changes in the text editor is extensive, there are certain non-configurable styles that disrupt a coherent modification of styles and colors.
To be specific, it's not possible to change the text styles of collapsed elements that have a box around them. They can end up even more highlighted than the uncollapsed text.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e2913896-b0f2-5f3c-d733-09fe5c4e86b1
* Version Independent ID: c997c373-c946-0f02-d4c2-0904e6aab42e
* Content: [Change themes, fonts, text, and contrast for accessibility](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-change-fonts-and-colors-in-visual-studio?view=vs-2022&source=docs)
* Content Source: [docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-change-fonts-and-colors-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@ramoneeza -- Ramon, thank you for your feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

cc @anandmeg for awareness

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
