### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by duncanthescot** [MicrosoftDocs/visualstudio-docs#9802]
The Angular page is blank.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 187a9aa8-1f64-5a37-f8a6-0d408642014e
* Version Independent ID: 1fb3868f-4175-279e-6372-91765426547c
* Content: [Create an Angular app - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-create-angular-app?view=vs-2022)
* Content Source: [docs/javascript/tutorial-create-angular-app.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-create-angular-app.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@duncanthescot -- Duncan, thank you for your feedback.  Please provide more context.
