### ISSUE TITLE
MSBuild built-in DefiningProjectExtension etc. metadata

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [MicrosoftDocs/visualstudio-docs#9805]
All open-source versions of MSBuild apparently recognize these metadata names that are not documented:

- DefiningProjectFullPath
- DefiningProjectDirectory
- DefiningProjectName
- DefiningProjectExtension

They are implemented here: <https://github.com/dotnet/msbuild/blob/195e7f5a3a8e51c37d83cd9e54cb99dc3fc69c22/src/Shared/Modifiers.cs#L554-L594>

Of those, %(DefiningProjectExtension) is used by [Microsoft.NET.Sdk.DefaultItems.targets](https://github.com/dotnet/sdk/blob/v8.0.100/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.DefaultItems.targets) in .NET SDK, i.e. it is not private to MSBuild.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62db4b12-8d5d-6a33-b5f6-b3f7320dd3f8
* Version Independent ID: 19ee6154-2eb2-b6a0-ab2e-96de2cfc05b2
* Content: [MSBuild Well-known Item Metadata - MSBuild](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-well-known-item-metadata?view=vs-2022)
* Content Source: [docs/msbuild/msbuild-well-known-item-metadata.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/msbuild-well-known-item-metadata.md)
* Product: **visual-studio-windows**
* Technology: **msbuild**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@KalleOlaviNiemitalo -- Kalle, thank you again for your clear and thoughtful feedback.

@ghogen -- Gordon, please look into this issue.
