### ISSUE TITLE
Close but no Cigar

### ISSUE THREAD

**Issue by ItsDuGuRu** [MicrosoftDocs/visualstudio-docs#9822]
HTML/XML et al have associated components. Some are nice to have, some are required. Rather than blasting into any subject with a plethora of industry acronyms and/or buzz words, yee ole flow charts replete with DEFINITIONS really, really, really would be helpful, or could it be the intent is to overwhelm, confuse, and confound?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61361e59-f416-76fe-a426-31acbdb16270
* Version Independent ID: f1d959da-ea25-7ce1-4c06-46f8beddf370
* Content: [XML editor and schema designer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/xml-tools/xml-tools-in-visual-studio?view=vs-2022)
* Content Source: [docs/xml-tools/xml-tools-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/xml-tools/xml-tools-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-xml-tools**
* GitHub Login: @dzsquared
* Microsoft Alias: **drskwier**

**Comment by ghogen** [comment]
Thanks for your feedback. After consulting with the engineering team about this, we think that changes to this document are not in our plans at this time, but your thoughts will be noted for future consideration.
