### ISSUE TITLE
Add documentation for enabling/disabling option

### ISSUE THREAD

**Issue by alexravenna** [MicrosoftDocs/visualstudio-docs#9833]
This article only talks about the feature itself, but not that it can be enabled or disabled in Options -> Text Editor -> C# -> Advanced. Maybe some users will be wondering why it isn't showing up and that's simply because it's not enabled. Additionally, there's no documentation that it's experimental, or why it's experimental.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/29532881/dcea2700-948c-433b-a86f-79b396eadb6e)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83570d18-e0b6-0097-6966-1ffd6856955e
* Version Independent ID: 2a191933-b3ab-60ae-3e31-f1fb129ceefa
* Content: [Remove unused references - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/remove-unused-references?view=vs-2022)
* Content Source: [docs/ide/reference/remove-unused-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/remove-unused-references.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by j-martens** [comment]
#assign:@mikejo5000

**Comment by Mikejo5000** [comment]
@alexravenna Thanks for the feedback! Updating the article to clarify how to enable the option. It is experimental because it could be removed in the future. Update should be live by EOD today, PST.

**Comment by Mikejo5000** [comment]
PR: MicrosoftDocs/visualstudio-docs-pr#12186
