### ISSUE TITLE
Dead link https://www.visualstudio.com/explore/cplusplus-mdd-vs.aspx

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#984]
Found in https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-visual-cpp-for-cross-platform-mobile-development

**Comment by gewarren** [comment]
@nschonni Thank you!

**Comment by gewarren** [comment]
The link seems to be working now and points to https://visualstudio.microsoft.com/vs/features/cplusplus-mdd/.

**Comment by nschonni** [comment]
Looks like the original link was removed.
PS: https://www.visualstudio.com/explore/cplusplus-mdd-vs.aspx still 404s

**Comment by gewarren** [comment]
@nschonni www.visualstudio.com is now visualstudio.microsoft.com.

**Comment by nschonni** [comment]
Yup, it redirects to https://visualstudio.microsoft.com/explore/cplusplus-mdd-vs, which is a 404
Not sure if it's something that can/should get remapped, but I know that's more of a marketing site link than a Docs link

**Comment by gewarren** [comment]
@nschonni Ahh, I see. Thanks, I'll let marketing know that their redirect is broken.
