### ISSUE TITLE
Documentation needs to be updated ...

### ISSUE THREAD

**Issue by bdcoder2** [MicrosoftDocs/visualstudio-docs#9847]
Was experimenting with T4 text templates using Visual Studio 2022 Version 17.8.2.   Followed the documentation directions, but noted the following:

In the section entitled **To create a run-time text template**, the documentation states:  
   In the **Add New Item** dialog box, select **Runtime Text Template**.

- In Visual Studio 2022 no such item seems to exist, the only option found when using the **Add New Item** was **Text Template** -- the **Runtime Text Template** seems to be missing from Visual Studio 2022.   Not sure if this is a bug in Visual Studio or the documentation needs to be updated with instructions on how to install the **Runtime Text Template** if not available.

I was able to use the **Text Template** and set the file's **Custom Tools** property to **TextTemplatingFilePreprocessor** as per the documentation.  However, when I compiled the program, the following build errors occurred:

```
Error	CS1069	The type name 'CompilerErrorCollection' could not be found in the namespace 'System.CodeDom.Compiler'. This type has been forwarded to assembly 'System.CodeDom, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly.
```

The documentation needs to be updated to include the following additional step before compiling / using templates:  

- Add the [System.CodeDom NuGet package](https://www.nuget.org/packages/System.CodeDom/) to your project.

Adding the above NuGet package fixed the problem.  Hope the above will help others new to templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a170869-23a9-96c9-d85b-372adcb19230
* Version Independent ID: d900eb64-973b-78dc-47eb-799aad1ee592
* Content: [Run-Time Text Generation with T4 Text Templates - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/modeling/run-time-text-generation-with-t4-text-templates?view=vs-2022&tabs=csharp)
* Content Source: [docs/modeling/run-time-text-generation-with-t4-text-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/modeling/run-time-text-generation-with-t4-text-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @mgoertz-msft
* Microsoft Alias: **mgoertz**

**Comment by ghogen** [comment]
@bdcoder2
I'm seeing the RuntimeTextTemplate option presented in Add New Item in a recent release of Visual Studio Community, without installing any Individual Components, at least when trying this with a .NET 8 Console App project.  What project type are you trying to use?
