### ISSUE TITLE
Repeated headline and section at release notes page

### ISSUE THREAD

**Issue by PerseusTheGreat** [MicrosoftDocs/visualstudio-docs#9861]
Hi.

At page [Visual Studio 2022 version 17.8 Release Notes](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes), the headline and the section of "**_Visual Studio 2022 version 17.8.1_**" have repeated twice.

**Comment by ghogen** [comment]
This appears to be fixed now.
