### ISSUE TITLE
synchronize visual studio settings does not work

### ISSUE THREAD

**Issue by learn-GPU** [MicrosoftDocs/visualstudio-docs#9869]
[Enter feedback here]

Spent an hour adjusting the fonts and colors and layout etc., closed and saved visual studio after a few hours (Synchronize VS setting across devices was checked), then launched VS and everything back to default. Redid the whole thing, installed VS on another device, logged in to synchronize, and still my preferences did not load. Can you tell one of your monkey devs to write a piece of code that actually works?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f452163a-5b45-243c-9601-585359deec53
* Version Independent ID: 881229c0-dfb7-6e68-00ae-868abd0c6687
* Content: [Synchronize settings - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/synchronized-settings-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/synchronized-settings-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/synchronized-settings-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by WilliamAntonRohm** [comment]
@learn-GPU -- thank you for your detailed feedback.  This repo is solely for documentation issues, and this is product-related.  Please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Use the new [Suggest a feature for Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/suggest-a-feature) IDE menu item.
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
