### ISSUE TITLE
Dead link https://www.visualstudio.com/en-us/features/unitytools-vs.aspx

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#987]
Found in docs/cross-platform//cross-platform-mobile-development-in-visual-studio.md

https://docs.microsoft.com/en-us/visualstudio/cross-platform/cross-platform-mobile-development-in-visual-studio

**Comment by gewarren** [comment]
@asb3993 Can you take a look?

**Comment by asb3993** [comment]
@nschonni This seems to redirect to https://www.visualstudio.com/vs/features/game-development/#tab-4b0d0be8de5f65564ad , which looks to be correct. What happens when you click the link?

**Comment by nschonni** [comment]
@asb3993 it's working for me now too :+1: 
Maybe someone fixed this up with the other debugger tools links that got flagged
