### ISSUE TITLE
Steps for adding additional information are wrong

### ISSUE THREAD

**Issue by davkean** [MicrosoftDocs/visualstudio-docs#9872]
The steps for adding additional more info is wrong. It states:

> When an issue is missing important information, we assign the Needs More Info state. We comment on the issue with the specific information we need, and you'll receive an email notification. If we don't receive the information within seven days, then we send you a reminder. After that, we close the ticket after 14 days of inactivity.

> Follow the link in the email to the problem report or go to the home page to see all reports in the Needs More Info state.

If you navigate via the email and try to attach "System logs and recordings", you get the following:

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/1103906/d1ac5bb2-a295-4b4c-a0cc-a39a3f58f1e1)

You need to navigate to the feedback ticket via Help -> Send feedback -> My feedback and not the email to be able to attach logs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2386e67e-a67b-de55-db57-e29a83dcb410
* Version Independent ID: 6247fba9-4255-9a59-c206-0e8547e12335
* Content: [Report a problem with Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022#when-further-information-is-needed)
* Content Source: [docs/ide/how-to-report-a-problem-with-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/how-to-report-a-problem-with-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @madskristensen
* Microsoft Alias: **madsk**

**Comment by j-martens** [comment]
#assign:@anandmeg

**Comment by anandmeg** [comment]
@davkean, thanks for the feedback.
We've updated the doc, changes should be live later today.
