### ISSUE TITLE
Function keys beyond F16 don't function the same way

### ISSUE THREAD

**Issue by zippy72** [MicrosoftDocs/visualstudio-docs#9889]
If you're using an Apple keyboard on Windows, you can't use F17, F18 and F19 unless you combine them with SHIFT, CTRL or ALT. Yet F13-F16 work fine. (I assume this would be the same for other manufacturers with additional function keys) Is there a reason for that? I know it's niche but I feel like the documentation should mention that, it's got me scratching my head about it - one of the attractions of an Apple keyboard for me is having the extra function keys to use with VS!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5859be-5f6e-4354-a0b0-c14ffc047d23
* Version Independent ID: d2033d27-92b9-6f70-286a-cefb0a58b15a
* Content: [Identify and customize keyboard shortcuts - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/identifying-and-customizing-keyboard-shortcuts-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by anandmeg** [comment]
@zippy72, thanks for the feedback. We've taken your feedback to the product team, and they're investigating & tracking the issue for a possible fix.
A similar issue is also posted in dev community:
[Allow the F17-F24 keys to be used for keyboard shortcuts - Developer Community (visualstudio.com)](https://developercommunity.visualstudio.com/t/Allow-the-F17-F24-keys-to-be-used-for-ke/10482857?q=fn+keys+f16-f19). You can upvote the issue, add any additional comments, and follow the ticket for updates.
Thanks again!

**Comment by anandmeg** [comment]
@zippy72, Thanks for your feedback. We appreciate it being brought to our attention and the appropriate engineering team is aware of it and has added it for consideration to their backlog. We'll use the DevCom ticket ([Allow the F17-F24 keys to be used for keyboard shortcuts - Developer Community (visualstudio.com)](https://developercommunity.visualstudio.com/t/Allow-the-F17-F24-keys-to-be-used-for-ke/10482857?q=fn+keys+f16-f19)) to track the work to enable the extended function key support. You can follow the DevCom ticket for updates on the issue. 
Closing this issue now. Please reach out to us for any additional feedback. Thanks.
