### ISSUE TITLE
XML Block is not showing the actual content

### ISSUE THREAD

**Issue by dskc** [MicrosoftDocs/visualstudio-docs#9892]
Within this article, wherever there is a place holder to show the block of codes, it doesn't display. It appears as OBJECT.OBJECT.OBJECT.. ETC., 
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/1244769/eedfaee1-2a00-42fa-9d66-27526898b5e6)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4286e883-bc14-0f1e-1262-08e8432b1b46
* Version Independent ID: 09df456f-db19-ad41-9d7f-fa81ddb33c92
* Content: [Create an ASP.NET Core app with Angular - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-angular?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-angular.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-angular.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@dskc -- thank you for your feedback.  On my screen, the XML renders as intended:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/27738025/91da87fe-e5e5-4006-800d-4bedbe126ad6)

Please provide additional details on your scenario.
