### ISSUE TITLE
doc also applies to Visual Studio Code

### ISSUE THREAD

**Issue by rootsmusic** [MicrosoftDocs/visualstudio-docs#9896]
Doesn't this doc also apply to Visual Studio Code?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Use regular expressions and review examples - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/using-regular-expressions-in-visual-studio?view=vs-2022)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@rootsmusic -- thank you for your question; they are different.  The Visual Studio regular expressions are described in that article.  Visual Studio Code regular expressions are described here:
- [Advanced search options](https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options)

I am closing this issue now.  You are welcome to @ mention me for any followup.  We hope to hear from you again.
