### ISSUE TITLE
Install Class Diagrams Component Missing Step

### ISSUE THREAD

**Issue by jeshortz** [MicrosoftDocs/visualstudio-docs#9904]
In section "Add class diagrams to projects", steps to install the component are missing a step: user must click on `Modify` after opening the VS Installer if they have already installed Visual Studio (this is why the screenshot in the documentation says "Modifying" at the top). (There's probably a different step missing if the component is being installed as part of a fresh VS install.)
<img width="675" alt="Screenshot" src="https://github.com/MicrosoftDocs/visualstudio-docs/assets/136673740/0b550726-bb84-450b-b690-0748b81474fa">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1a723ca4-ee71-386d-aa7a-461dd565bc84
* Version Independent ID: fa9856a9-4bab-805d-c5a1-bd8e506e4fb0
* Content: [Design, visualize, & refactor with Class Designer - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/class-designer/designing-and-viewing-classes-and-types?view=vs-2022)
* Content Source: [docs/ide/class-designer/designing-and-viewing-classes-and-types.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/class-designer/designing-and-viewing-classes-and-types.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
Thanks, it looks like this is fixed now.
