### ISSUE TITLE
Can Visual Studio Subscription licenses get access to both Azure DevOps Server and Azure DevOps Service org at the same time?

### ISSUE THREAD

**Issue by Anand-Moghe** [MicrosoftDocs/visualstudio-docs#9916]
As per my knowledge, AzDO server CAL licenses are not transferrable to AzDO service. So when someone gets VS Subscription license assigned to them by their Enterprise organization, does that users use the single VS subscription license to get access on both on-prem TFS (or AzDO Server) and AzDO service org as part of the benefits that comes with owning VS Subscription liense? Can this information be explicitly added in our documentation with clear guidance?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86accd88-89c8-f5bd-154f-c038c385d73d
* Version Independent ID: 18efab26-6236-f0e7-2959-dcc5735fff6e
* Content: [Azure DevOps benefits eligibility for subscribers - Visual Studio Subscription](https://learn.microsoft.com/en-us/visualstudio/subscriptions/vs-azure-devops)
* Content Source: [subscriptions/vs-azure-devops.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/subscriptions/vs-azure-devops.md)
* Product: **visual-studio-family**
* Technology: **vs-subscriptions**
* GitHub Login: @evanwindom
* Microsoft Alias: **amast**

**Comment by evanwindom** [comment]
@Anand-Moghe Thanks for reaching out.  I'm not well versed in this issue, so I'm checking with SMEs.  I'll post an update here once I have more information.

**Comment by evanwindom** [comment]
Depending on your subscription, you can have access to the Azure DevOps Service through activation of benefit in the subscriber portal AND a server license and CAL for DevOps Server.  I've added an excerpt from the licensing whitepaper to the article as an FAQ pair to make this information available in the article.

**Comment by evanwindom** [comment]
@WilliamAntonRohm Can you close this, please?

**Comment by WilliamAntonRohm** [comment]
#please-close
