### ISSUE TITLE
Primary Output not configured correctly to take into account VSTO build versions

### ISSUE THREAD

**Issue by Pher0ah** [MicrosoftDocs/visualstudio-docs#9921]
The document states in step ["To add the ExcelAddIn project Output"](https://learn.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2022#to-add-the-exceladdin-project-output) that you simply choose "Primary Output"; however, this does not align with the fact that under the primary output there is a folder "Application Files" that contains the assembled VSTO code and mainfest with a version number for each build.

To correct this, I have had to recreate that setup in the user's machine; since there is no way to tell the VSTO mainfest to use the correct location in the target machine.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3df9904c-bc2c-49e6-b661-5598354dbc40
* Version Independent ID: 6dca41d0-9c34-f5cc-a2b0-6c6e9df76063
* Content: [Deploy a VSTO Solution with Windows Installer (Visual Studio)](https://learn.microsoft.com/en-us/visualstudio/vsto/deploying-a-vsto-solution-by-using-windows-installer?view=vs-2022)
* Content Source: [docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/vsto/deploying-a-vsto-solution-by-using-windows-installer.md)
* Product: **visual-studio-windows**
* Technology: **office-development**
* GitHub Login: @John-Hart
* Microsoft Alias: **johnhart**

**Comment by John-Hart** [comment]
@Pher0ah, the Application Files folder was created for a ClickOnce publish when you either published the add-in or hit F5.  Does selecting the Primary Output not work for you?  It should.

**Comment by Pher0ah** [comment]
It has nothing to do with selecting the output, i am talking about the end
result. I.e. the installed folders on the target device.

**Comment by John-Hart** [comment]
@Pher0ah, maybe you can start from the beginning, you follow the instructions in the document, install the msi you created with the installer and what happened?

**Comment by ghogen** [comment]
@Pher0ah 
We'll close this issue for now. If you could clarify the nature of the problem, we can reopen and investigate further. Thanks!
