### ISSUE TITLE
Wrong product

### ISSUE THREAD

**Issue by JulianSMoore** [MicrosoftDocs/visualstudio-docs#9931]
I hit F1 on a an Excel VBA keyword. Why was I brought here? (excel 2019, Windows 10 64-bit home.)

I *really* want my offline help back.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9a28ee58-bd99-e74a-0c0c-30f5a41da08e
* Version Independent ID: 2467c672-a567-583c-2801-87dcaf0f2c91
* Content: [F1 help no-match fallback - Visual Studio (Windows)](https://learn.microsoft.com/en-gb/visualstudio/ide/not-in-toc/default?view=vs-2022&f1url=%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(keywords_removed)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue)
* Content Source: [docs/ide/not-in-toc/default.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/not-in-toc/default.md)
* Product: **visual-studio**
* Technology: ****
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by JulianSMoore** [comment]
@WilliamAntonRohm Thanks for directing me to other resources; fortunately I do know how to *search* for answers, the point was that I want to be able to *look them up* and that is what the in-app capability used to do/should do. I appreciate the constraints, but having raised the point in the issue log that the app sent me to the completely wrong place (which is a bug IMO & not the first time, so not a temporary fail of something, and probably affecting many), I have been generously proactive: I will not now be adding a "suggestion" via the "dev community" simply to repeat myself. Alas the fact that it sent me to the wrong place ends up creating an issue re the wrong product; however, as the Poles delightfully say, "not my circus, not my monkey": Microsoft is Microsoft. Not your fault, but wouldn't it be nice if whoever's fault it is could be made aware via a single point of contact.

**Comment by WilliamAntonRohm** [comment]
@JulianSMoore -- Julian, thank you for your considered follow-up.  I'll pursue this on internal channels.
