### ISSUE TITLE
Page is out of date with current VS2022 17.8.3

### ISSUE THREAD

**Issue by bzuidgeest** [MicrosoftDocs/visualstudio-docs#9935]
in 17.8.3 aspnetcore-https.js no longer exists in the project. The screenshots still show preview on the project template which is gone. And the extra settings for publishing al already done in the template

It's still usuable but maintenance is key.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c924f1c1-823e-3e29-bf09-405fc4c6bbb8
* Version Independent ID: 585c2426-5f9b-8499-8eda-0e56bd64c93c
* Content: [Create an ASP.NET Core app with Vue - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/javascript/tutorial-asp-net-core-with-vue?view=vs-2022)
* Content Source: [docs/javascript/tutorial-asp-net-core-with-vue.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/javascript/tutorial-asp-net-core-with-vue.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@bzuidgeest Thanks for the feedback! Updating the article.
