### ISSUE TITLE
Profiling is currently not supported for 3.11.4

### ISSUE THREAD

**Issue by AndrewR66** [MicrosoftDocs/visualstudio-docs#9939]
Deciced to try Python Profiling, and got this error:

Traceback (most recent call last):
  File "c:\program files\microsoft visual studio\2022\enterprise\common7\ide\extensions\microsoft\python\profiling\proflaun.py", line 35, in <module>
    vspyprof.profile(__file__, globals(), locals(), profdll)
  File "c:\program files\microsoft visual studio\2022\enterprise\common7\ide\extensions\microsoft\python\profiling\vspyprof.py", line 74, in profile
    raise NotImplementedError("Profiling is currently not supported for " + sys.version)
NotImplementedError: Profiling is currently not supported for 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
------------
I'm using Visual Studio Enterprise 2022
VisualStudio.17.Release/17.8.3+34330.188

Google wouldn't help me this time.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 399822f9-b83b-a607-4310-a7f496cf1f27
* Version Independent ID: c1300996-f8f4-e297-993a-1d614efe7e79
* Content: [Use profiler to measure Python code performance - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/profiling-python-code-in-visual-studio?view=vs-2022)
* Content Source: [docs/python/profiling-python-code-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/profiling-python-code-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
@AndrewR66 thanks for filing this issue! This issue may be better triaged in the [PTVS repo](https://github.com/microsoft/PTVS). If you are still experiencing this, please open an issue in our repo with thorough repro steps and information on your environment configuration. Thanks!

**Comment by cwebster-99** [comment]
#please-close

**Comment by cwebster-99** [comment]
Profiling is not supported while using Python 3.11. Please try profiling using Python 3.9 or prior. I updated the docs to include a screenshot that didn't show Python 3.11 in https://github.com/MicrosoftDocs/visualstudio-docs-pr/pull/12083
