### ISSUE TITLE
Visual Studio GitHub Copilot Chat requires 17.8+ now (used to be 17.6+)

### ISSUE THREAD

**Issue by ikeras** [MicrosoftDocs/visualstudio-docs#9955]
The requirements for the VS GitHub Chat extension have changed to be 17.8+. The prerequisites listed on this page need to be updated to match: https://learn.microsoft.com/en-us/visualstudio/ide/visual-studio-github-copilot-chat?view=vs-2022#prerequisites

**Comment by anandmeg** [comment]
@ikeras, thanks for the feedback. I've updated the doc, changes should be live later today.
Thanks!
