### ISSUE TITLE
Code snippets manager is no longer in Tools menu

### ISSUE THREAD

**Issue by epsitec** [MicrosoftDocs/visualstudio-docs#9963]
I'm using Microsoft Visual Studio Professional 2022 (64-bit) - Preview / Version 17.9.0 Preview 2.1, and the _Code snippets manager_ does not show up in the _Tools_ menu.

## Public Visual Studio 17.8.3

![Visual Studio Version 17.8.3](https://github.com/MicrosoftDocs/visualstudio-docs/assets/3872435/6395ac24-d792-4016-b337-ea9f3e8b7d2f)

## Preview Visual Studio 17.9.0 Preview 2.1

![Visual Studio Version 17.9.0 Preview 2.1](https://github.com/MicrosoftDocs/visualstudio-docs/assets/3872435/3d1f7abe-7913-4d89-828f-9f3294488420)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 77c7c36c-84d9-9237-3d78-689e76d080f9
* Version Independent ID: 6584735a-e8db-429d-5427-687fc709e6f8
* Content: [Create a code snippet in Visual Studio - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-code-snippet?view=vs-2022)
* Content Source: [docs/ide/walkthrough-creating-a-code-snippet.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/walkthrough-creating-a-code-snippet.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by WilliamAntonRohm** [comment]
@epsitec -- Pierre, thank you for your feedback.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@Mikejo5000 -- Mike, please look into this potential documentation issue.

**Comment by Mikejo5000** [comment]
@epsitec This has been reported here:
https://developercommunity.visualstudio.com/t/Code-Snippets-Manager-Missing/10550540
Looks like there's a fix in place, but it's not released yet.
