### ISSUE TITLE
Dead link  http://www.microsoft.com/resources/sharedsource/ccp.mspx

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/visualstudio-docs#997]
Found in docs/debugger//how-to-debug-with-code-center-premium-source.md

**Comment by gewarren** [comment]
@Mikejo5000 can you take a look?

**Comment by Mikejo5000** [comment]
@nschonni Nick, thanks for pointing out the bad links. I'm fixing a set of them in a PR right now. Were you running a link test tool on all the MSDN and FwLinks links in the repo, or only a subset?

**Comment by nschonni** [comment]
Going by folder, so i'd be running something like `find docs/debugger/ -name \*.md -exec markdown-link-check {} \;`
