### ISSUE TITLE
Cosmos DB Emulator on container not starting

### ISSUE THREAD

**Issue by nikolayarhangelov** [MicrosoftDocs/visualstudio-docs#9970]
**Steps to Reproduce**
Using Visual Studio 2023 and the Connected Services window, add a new _Cosmos DB Emulator on containter (Local)_ service dependency.
Start the dependencies and observe the Docker logs for Cosmos DB.

**Actual Result**
Cosmos DB will not start and will continuously throw error `Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified`.

**Root Cause**
The generated Docker Compose configuration sets a 2GB memory limit on the Cosmos DB Emulator container and it needs more.
Related issue: https://github.com/Azure/azure-cosmos-db-emulator-docker/issues/77

**Workaround**
Navigate to the _.vs/sd/<_GUID_>/local_ folder of your solution. Find and edit file `cosmosdb1.docker-compose.yml`. Set a _4G_ memory limit.
```
mem_limit: 4G
```

Restart the service dependencies and Cosmos DB Emulator will now start properly.

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/5097161/2ed63674-5cdb-4ae4-b835-8ba2d43132e8)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c72e65ea-3853-a5db-99a2-9e3ad06f5102
* Version Independent ID: 58e6282c-3ee9-407a-b43c-30714b630d85
* Content: [Add Azure Cosmos DB by using Connected Services - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/azure/azure-cosmosdb-add-connected-service?view=vs-2022)
* Content Source: [docs/azure/azure-cosmosdb-add-connected-service.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/azure/azure-cosmosdb-add-connected-service.md)
* Service: **visual-studio-windows**
* Sub-service: **azure-development**
* GitHub Login: @AngelosP
* Microsoft Alias: **angelpe**

**Comment by WilliamAntonRohm** [comment]
@nikolayarhangelov -- Nikolay, thank you for your well-researched feedback.

@AngelosP -- Angelos, please look into this issue.

**Comment by j-martens** [comment]
#assign:@ghogen
