### ISSUE TITLE
Error on page visual studio sdk api - where do I create issue

### ISSUE THREAD

**Issue by tonyhallett** [MicrosoftDocs/visualstudio-docs#9978]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivsfontandcolordefaultsprovider.getobject?view=visualstudiosdk-2022&source=docs

https://github.com/MicrosoftDocs/visualstudio-docs-dotnet-api-pr/blob/db9bf3f336dd8c6255e40feef16ec93af554c139/visualstudiosdk/Microsoft.VisualStudio.Shell.Interop/IVsFontAndColorDefaultsProvider.xml
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/11292998/2ab5e004-0fac-450b-8cbe-27c32b606983)

https://github.com/MicrosoftDocs/visualstudio-docs-dotnet-api-pr/blob/live/visualstudiosdk/Microsoft.VisualStudio.Shell.Interop/IVsFontAndColorDefaultsProvider.xml
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/11292998/65eb5698-d42e-46dc-a144-fc8457db2ac7)

https://github.com/MicrosoftDocs/visualstudio-docs-dotnet-api-pr/blob/live/visualstudiosdk/Microsoft.VisualStudio.Shell.Interop/IVsFontAndColorDefaultsProvider.xml
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/11292998/93a47396-610d-4be4-9684-bcfa5dcb1b11)

![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/11292998/6dee7167-c19f-43f4-8974-3fcfc00a3248)

**Comment by WilliamAntonRohm** [comment]
@tonyhallett -- Tony, please consider these options:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).
