### ISSUE TITLE
What about folder-based projects?

### ISSUE THREAD

**Issue by CarolinaB-visiba** [MicrosoftDocs/visualstudio-docs#9979]
I am trying to get a git repository originally set up for VS Code operational in Visual Studio 2022. It seems I can not add this to a full-fledged visual studio project, as you are using in this example. Thus, there is no search path node to click to add the paths I need. Is there any way to acheive this, or do all developers have to use the same IDE when working with pyhton?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e34b9c9a-6356-61fa-d895-97c459465e75
* Version Independent ID: c317a64e-06a3-1081-08db-3fb278ea7fbf
* Content: [How Python search paths are applied - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/python/search-paths?view=vs-2022)
* Content Source: [docs/python/search-paths.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/python/search-paths.md)
* Service: **visual-studio-windows**
* Sub-service: **python**
* GitHub Login: @cwebster-99
* Microsoft Alias: **cowebster**

**Comment by cwebster-99** [comment]
@CarolinaB-visiba, thanks for filing this issue. Could you provide more information about your scenario, such as, are you trying to add the VS Code workspace to an existing Python project in VS Code or do you just want to open the repo to work on as-is in PTVS? You should be able to open/clone the git repo in Visual Studio without the need to create a Python project in Visual Studio.

**Comment by CarolinaB-visiba** [comment]
Sure, I'll try to explain:
We have a python tool that has been created using VS Code. It is published on GitHub and from there I can retreive it to Visual Studio 2022 (is that PTVS?). When I do so, I get a Folder view in Solution Explorer, like so:
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/99891139/7d3a4ec3-13e5-4ca8-8923-93177db49a93)

Looking at the python files in the project, the interpretor does not recognize some paths. I tried adding the line with four starting dots, which works. It references the same module as the statement two lines down, which does not work.
![image](https://github.com/MicrosoftDocs/visualstudio-docs/assets/99891139/b949767d-7c4c-4b58-94d5-61ba5c064a5c)

I was thinking that adding a path somewhere would alleviate this. The code runs as expected in a python environment, so there is nothing actually wrong here, and I would not want to add the inital dots in all python files since I am ot sure how VS Code will behave and it also clutters everything.

**Comment by CarolinaB-visiba** [comment]
If there is a way to load the github-based folder into a Visual Studio project, I'd be happy to try that but I find no way to do that with an existing github repo.

**Comment by anandmeg** [comment]
Thanks for the feedback, @CarolinaB-visiba. Closing this now. Let us know if you have any additional feedback.
