### ISSUE TITLE
This week's solutions are not correct

### ISSUE THREAD

**Issue by chucklu** [MicrosoftDocs/visualstudio-docs#998]
Hi team,
      It's 2018-05-21 11:14:00 +08:00, and it's Monday now.
      And I have set the first day of week to Monday on my computer.
      However you still show the solution I oepned last week, I  am not sure what's the default first day of a week by win10. I wonder you guys forgot to check the first day of week configured on computer, which show wrong solutions for this week.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b057a09a-e208-8daf-58b0-3dfb3bb4ea0e
* Version Independent ID: f891d20f-a2c8-3208-ed23-91dfef901eaf
* Content: [Solutions and projects in Visual Studio - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/ide/solutions-and-projects-in-visual-studio)
* Content Source: [docs/ide/solutions-and-projects-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/ide/solutions-and-projects-in-visual-studio.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by gewarren** [comment]
@abuchholtzau Do you know which solutions are supposed to display on the Start Page under "This week"? Is it from the last 7 days, or starting on Sunday, or ??

**Comment by gewarren** [comment]
@chucklu Could you please file this as an issue or suggestion on [Developer Community](https://developercommunity.visualstudio.com/spaces/8/index.html)? You'll get more traction from the product team there.
