### ISSUE TITLE
Describe how to use docker-compose with react SPA created by Vite

### ISSUE THREAD

**Issue by mikolajpiecuch** [MicrosoftDocs/visualstudio-docs#9980]
Hi, I found it useful to configure Docker support for React + .NET Core but there is no information how to use it with docker-compose. I think it could be helpful for anyone who already usese docker-compose. I mean mostly, how to configure Debug (e.g. start multiple projects: docker-compose and Vite) and Release configurations (e.g just docker-compose).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1abf884f-eb39-1007-25a6-d049b87504a3
* Version Independent ID: 33636e79-d3e1-8c24-f3a5-0c3c79e2a488
* Content: [Build React app with Visual Studio Container Tools](https://learn.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2022)
* Content Source: [docs/containers/container-tools-react.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/containers/container-tools-react.md)
* Service: **visual-studio-windows**
* Sub-service: **container-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by ghogen** [comment]
@mikolajpiecuch 
This is a potentially interesting scenario for a blog post, but it's not currently considered a core scenario for our documentation. Let us know if you get this working, and consider sharing your solutions and posting a link to your work.
