### ISSUE TITLE
The "Remove unused references" feature does not exist in Visual Studio 2022

### ISSUE THREAD

**Issue by Tam66662** [MicrosoftDocs/visualstudio-docs#9981]
In Visual Studio 2022 (I'm using build 17.8.5), the 'Remove unused references' feature does not exist. Also, if I navigate to enable the checkbox via **Tools->Options->Text Editor->C#->Advanced->Show "Remove Unused References" command in Solution Explorer (experimental)**, it still doesn't show up from a right-click context menu on any part of the Solution Explorer.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83570d18-e0b6-0097-6966-1ffd6856955e
* Version Independent ID: 2a191933-b3ab-60ae-3e31-f1fb129ceefa
* Content: [Remove unused references - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/ide/reference/remove-unused-references?view=vs-2022)
* Content Source: [docs/ide/reference/remove-unused-references.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/ide/reference/remove-unused-references.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @mikadumont
* Microsoft Alias: **midumont**

**Comment by WilliamAntonRohm** [comment]
@Tam66662 -- thank you for your feedback.  If you feel this is a product issue, please add it here:
- Report product issues to us via the [Report a Problem](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio) tool that appears both in the Visual Studio Installer and in the Visual Studio IDE.​ 
- Suggest a feature, track product issues, and find answers in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com).

@mikadumont -- please look into this potential documentation issue.

**Comment by j-martens** [comment]
#assign:@anandmeg

**Comment by hfickes** [comment]
Lots of people still use .Net Framework because we need to.  In our case, because Office only supports .Net Framework with VSTO.  We can't move to the latest .Net.

Please add this feature.
