### ISSUE TITLE
Is it possible to add custom nodes to the Shader Designer?

### ISSUE THREAD

**Issue by lolgube010** [MicrosoftDocs/visualstudio-docs#9985]
As the title says, the documentation doesn't really mention this feature anywhere. Yes, you can just edit the HLSL code and get past it that way, but since the "nodes" are a part of the toolbox, having some sort of information about how to expand it would be nice. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7ff1e79e-d0e3-b408-ec3d-ddad7de2fa3b
* Version Independent ID: 31384d5f-3b03-09cb-03b4-3ba3367ad055
* Content: [About Shader Designer nodes - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/designers/shader-designer-nodes?view=vs-2022)
* Content Source: [docs/designers/shader-designer-nodes.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/designers/shader-designer-nodes.md)
* Service: **visual-studio-windows**
* Sub-service: **ui-designers**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by Mikejo5000** [comment]
@lolgube010 Thanks for the feedback! Sorry for the slow response. Docs for this feature area are in maintenance mode. Can you provide details for this procedure? If so, I can add it to the documentation. Or, you can submit a PR to make the updates directly.
