### ISSUE TITLE
Give example command lines using PowerShell

### ISSUE THREAD

**Issue by Liturgist** [MicrosoftDocs/visualstudio-docs#9987]
[Enter feedback here]
It is 2024 already. PowerShell has been out for 1.5 decades. Why are command examples still using cmd.exe language.
Are you wanting users to stay stuck on "batch" files?
Is calling cmd.exe "shell" really appropriate?
Make PowerShell the goto language. Or, at least first choice.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eedaccf1-bbb7-9a7c-21be-64217359acb5
* Version Independent ID: da785eb8-7187-0831-0b3c-1b422c6f2a15
* Content: [Command-line parameter examples for installation - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/command-line-parameter-examples?view=vs-2022)
* Content Source: [docs/install/command-line-parameter-examples.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/command-line-parameter-examples.md)
* Service: **visual-studio-windows**
* Sub-service: **installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by ghogen** [comment]
@Liturgist 
Thanks for this suggestion. It seems like a great idea and we've created a work item for this internally. We'll go ahead and close the issue here while we're continuing to track the work in our systems. Thanks!
