### ISSUE TITLE
thank you that was so easy and helpful 

### ISSUE THREAD

**Issue by sabaMK47** [MicrosoftDocs/visualstudio-docs#9989]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 03e3ba56-450a-ff3f-6f76-2153e4941621
* Version Independent ID: 6e9f3066-f40b-b83f-5175-8abf2dda3da0
* Content: [Build dataset in Dataset Designer (.NET Framework) - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/data-tools/walkthrough-creating-a-dataset-with-the-dataset-designer?view=vs-2022)
* Content Source: [docs/data-tools/walkthrough-creating-a-dataset-with-the-dataset-designer.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/data-tools/walkthrough-creating-a-dataset-with-the-dataset-designer.md)
* Service: **visual-studio-windows**
* Sub-service: **data-tools**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by WilliamAntonRohm** [comment]
@sabaMK47 -- Maryam, thank you for your kind words.  They are much appreciated.

cc @ghogen, @j-martens
