### ISSUE TITLE
installed.packages() get packages list

### ISSUE THREAD

**Issue by avichaygrafi** [MicrosoftDocs/visualstudio-docs#999]
Hey, is there a way to get it by script/code? thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82bd11a6-536c-df58-14ae-b0d8daa62432
* Version Independent ID: 7837b036-cbd0-3fbe-bd65-2e7b7c0e1963
* Content: [Package manager for R - Visual Studio](https://docs.microsoft.com/en-us/visualstudio/rtvs/r-package-manager-in-visual-studio)
* Content Source: [docs/rtvs/r-package-manager-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/rtvs/r-package-manager-in-visual-studio.md)
* Service: **unspecified**
* Product: **visual-studio-dev15**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
@avichaygrafi Apologies for my delay in responding...was at PyCon, then had time off...you know how that goes.

I don't know of an API that gets you this information, but you should be able to write a simple script to enumerate the folders in the two install locations noted in the article: C:\Program Files\Microsoft\R Client\R_SERVER\library for packages installed with RTVS, and %userprofile%\Documents\R\win-library\3.3 for user-installed libraries.

I don't have such a script handy, unfortunately, but shouldn't be difficult to write. In fact, you can probably search for "Python script to list folders in a directory" or something like that to find a script that someone has already written.
