### ISSUE TITLE
Mistake causing compilation error in guide "Matching Game"

### ISSUE THREAD

**Issue by Filifek** [MicrosoftDocs/visualstudio-docs#9996]
There is a mistake at part "Assign a random icon to each label" in both Polish and English versions of guide
Compilation will always fail because of question mark in the line:

**Label? iconLabel = control as Label;**

the correct line should be:

**Label iconLabel = control as Label;**

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9577c259-7ee7-eab5-bdef-3ae87d93ff80
* Version Independent ID: 9577c259-7ee7-eab5-bdef-3ae87d93ff80
* Content: [Tutorial: Add icons to the matching game - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/get-started/csharp/tutorial-windows-forms-match-game-icons?view=vs-2022&tabs=csharp)
* Content Source: [docs/get-started/csharp/tutorial-windows-forms-match-game-icons.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/get-started/csharp/tutorial-windows-forms-match-game-icons.md)
* Service: **visual-studio-windows**
* Sub-service: **general-ide**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by ghogen** [comment]
This is fixed now. Thanks for the feedback!
